### ISSUE TITLE
Default set of templates for LU, LG, dialog snippets available at Composer GA

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1003]
In order for people to get started successfully w Composer, by public preview we need to include examples/out-of-box content such as:

Standard Intents - Marieke/Riham/Yochay to talk
   - Greeting
  - Quit
  - Etc.
  - Predefined domains such as cities, states, Time/date etc.

LG - Ben/Sang/Yochay to talk
  - Confirmation | VA?
  - Disambiguation | Marieke to ask Lisa Stifelman
  - Adaptive card  | hero-card samples?

**Comment by vishwacsena** [comment]
@mareekuh @benbrown can we close on this? Is this about providing a set of pre-built LU and LG files? If so, how do users discover and use them in composer?

**Comment by mareekuh** [comment]
I agree that adding all predefined domains is not desirable. 
However, having some will be very valuable to get things started. I'll propose a solution - next week ok?

**Comment by vishwacsena** [comment]
Today, we have prebuilt domain intents with example utterances, patterns, entities and intent in LUIS. We have skills that use some of these prebuilt domain intent and adds dialog + LG to make a skill. Cortana has prebuilt LG templates used today by 1P. 

This task is about figuring out and designing of these prebuilt LU, LG, dialog snippets we will make available as prebuilt template (asset library) for composer GA.

**Comment by mareekuh** [comment]
This has come up also in discussions with PVA. They have the following set, which looks like a good start:
Age
Age of a person, place, or thing, extracted as a number
Prebuilt

Boolean
Positive or negative responses, extracted as a Boolean
Prebuilt

City
City names, extracted as a string
Prebuilt

Color
Primary colors and hues on the color spectrum, extracted as a string
Prebuilt

Continent
Continent names, extracted as a string
Prebuilt

Country or region
Country and region names, extracted as a string
Prebuilt

Date and time
Dates, times, days of the week, and months relative to a point in time, extracted as a string
Prebuilt

Duration
Lengths of time, extracted as a string, in standard TimeSpan format
Prebuilt

Email
Email addresses, extracted as a string
Prebuilt

Event
Event names, extracted as a string
Prebuilt

Language
Language names, extracted as a string
Prebuilt

Money
Monetary amounts, extracted as a number
Prebuilt

Number
Cardinal numbers in numeric or text form, extracted as a number
Prebuilt

Ordinal
Ordinal numbers in numeric or text form, extracted as a number
Prebuilt

Organization
Names of organizations, associations, and corporations, extracted as a string
Prebuilt

Percentage
Percentages in numerical or text form, extracted as a number
Prebuilt

Person name
A person's partial or full name, extracted as a string
Prebuilt

Phone number
Phone numbers in the standard US format, extracted as strings
Prebuilt

Point of interest
Points of interest, extracted as a string
Prebuilt

Speed
Speed, extracted as a number
Prebuilt

State
Names and abbreviations for the United States, extracted as a string
Prebuilt

Street address
Numbered addresses, streets or roads, city, state, zip or postal code in the standard US format, extracted as a string
Prebuilt

Temperature
Temperature, extracted as a number
Prebuilt

URL
Website URLs and links, extracted as a string
Prebuilt

Weight
Weight, extracted as a number
Prebuilt

Zip code

**Comment by mareekuh** [comment]
@vishwacsena @cwhitten  - where are we with this?

**Comment by vishwacsena** [comment]
@mareekuh @cwhitten I'd like to make progress on this in R10 or close it one way or another. Can you clarify if you believe this is an R10 issue for composer? 

For prebuilt LU, we can totally have the LUIS pre-built domain intents and entities available as LU files. We would simply need to coordinate with LUIS team to figure out the source for those and have them be pulled in by composer so we do not duplicate the actual models. 

For LG, we will need to build content from scratch - we could reach out to Lisa to see what we can leverage from her team's work. 

For Dialogs, I'm not sure we have any but we could start building dialogs over prebuilt domain models and make them available which would actually offer an E2E solution than having to start from scratch. Part of what VA skills offer is basically this - they start from LUIS prebuilt domains and then add dialog and LG on top. Another route would be to just offer the skills as prebuilt dialog templates. 

Thoughts?

**Comment by mareekuh** [comment]
1. Prebuilt -> Use LUIS domains : Yes
2. LG -> ask Lisa : Yes. (We can also ask the Marvel team who does the personality chats) - I'll ask and maybe we get both
3. Dialog snippets: The Samples include have pretty good building blocks. Right now they're full bots, but for 
- asking questions
- interruptions
- Controlling conversation flow has a lot of them
..

**Comment by cleemullins** [comment]
Composer has gone GA. Closing this issue as obsolete.

**Comment by mareekuh** [comment]
Having default content that includes predefined LU, LG and dialog assets remains an important need/requirement.
Please connect this to the 'Asset Library' to not lose track.

**Comment by clearab** [comment]
This should be part of the core + assistant work (VA). The sample assets should be the same assets that are added on top of the core bot in order to create the componentized, adaptive version of the VA bot.

**Comment by clearab** [comment]
Closing this, this work is being tracked as part of the component model.
