### ISSUE TITLE
Documentation | bugbash to identify broken links, un-helpful links etc.

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1004]
From Hackathon:
Instruction, samples or details are missing; 
- ( i )’s go to generic pages vs specific parts of them page/section - >  Yochay & Kamran to set - ( i) include instructions or examples vs information - inconsistent with eachother and how i is and should be used
- links to documentation broken
- no documentation available for certain topics

**Comment by Kaiqb** [comment]
@a-b-r-o-w-n  This seems like an issue in the Composer that needs to be fixed by pointing to the content that is on GitHub.
