### ISSUE TITLE
prefer $designer.name for root field over sdk override

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#1014]
## Version
Build SHA: f8e211d

## Describe the bug
The editable title in the form should use the designer name first if present, then fallback to the override.

## To Reproduce
1. Go to a OnBeginDialog trigger
2. Edit the title in the form
3. Refresh the page
4. Instead of the new title, it shows the override

## Expected behavior
It should use the new title instead.

**Comment by cwhitten** [comment]
Cannot repro - reopen if this is still an issue
