### ISSUE TITLE
You can open multiple context menus at the same time.

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1017]
## Describe the bug
You can open multiple context menus at the same time.

## To Reproduce
1. Click '...' on the left nav next to triger - a context menu with 'delete' option appears
2. Click '...' on one of the action nodes on the visual canvas - a context menu with 'delete' option appears

## Expected behavior
There should be only one context menu appearing at once.

## Screenshots
![Screen Shot 2019-10-01 at 4 47 28 PM](https://user-images.githubusercontent.com/50963385/66008499-a311d800-e46b-11e9-9654-e5d4e2954447.png)

## Additional context
It displays the desirable behavior - closing currently opened context menu upon clicking different '...' button - within the same modal.

**Comment by yeze322** [comment]
I just tested on our latest build, already fixed.
