### ISSUE TITLE
Prompt properties 'value' and 'default' value shouldn't share the same term

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1028]
![Screen Shot 2019-10-04 at 12 06 13 PM](https://user-images.githubusercontent.com/50963385/66233404-2582dd80-e6a0-11e9-8217-02716fbe9982.png)

The word 'value' is being used with different meanings between the two properties side by side. Need to come up with a new name for one of them.

@yochay @vishwacsena @mareekuh @cwhitten

**Comment by mareekuh** [comment]
@vishwacsena 
I would propose to add the following copy inside the field: <'Enter value to use when max turn count was exceeded >  
For 'value' we should display the description text that one gets when clicking (i)

**Comment by vishwacsena** [comment]
This should be tracked via SDK issue - https://github.com/microsoft/botbuilder-dotnet/issues/2934
