### ISSUE TITLE
Commenting code blocks in BF Composer

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1055]
**Is your feature request related to a problem? Please describe.**

- Will Composer support commenting "code block" like what we do in code? 

Comments play an important role to improve code readability. Comments are supported in both .lg and .lu files, but there is no way to comment on "code blocks" in Composer when users compose their bots. 

**Describe the solution you'd like**
I think this is a useful feature to be implemented to improve code readability and bot development user experience.

**Comment by zxyanliu** [comment]
Closing at this point. Shall reopen if needed.

**Comment by xieofxie** [comment]
Although it is under discussion, please allow me to reopen this.
Also add tag to indicate it is required by skills team.
