### ISSUE TITLE
Visual Editor arrow key navigation has incorrect behavior

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#1082]
## Version

711c2344

## Describe the bug

There is still some issues with the cursor move logic. See my gif (I was pressing <kbd>&leftarrow;</kbd> and <kbd>&rightarrow;</kbd>):

![keyboard-bug-move](https://user-images.githubusercontent.com/8528761/66670800-d85eb880-ec17-11e9-86cd-201a160b71c9.gif)

## To Reproduce
1. create a promt input node
2. create a if condition node
3. insert steps in IfCondition's two branches
4. focus on the true branch's node, pressing &leftarrow; and &rightarrow; repeatively

## Expected behavior

pressing &leftarrow; and &rightarrow; should lead me to sibling nodes

### Expected behavior
1. If pressing &uparrow; and &downarrow;, cursor should move to previous / following node.
2. If cursor is focusing on a node with siblings, pressing &leftarrow; and &rightarrow; should navigate to siblings.
3. If cursor is focusing on 'BotSays' node of a prompt type, pressing &downarrow; should nav to 'UserAnswers', then pressing &rightarrow; should nav to 'Exceptions'; if focusing on 'Exceptions', pressing &uparrow; should nav to 'BotSays'
![image](https://user-images.githubusercontent.com/8528761/66694960-89487000-ec77-11e9-98f0-9d3bec003e65.png)

**Comment by cwhitten** [comment]
addressed in #1082
