### ISSUE TITLE
LU should allow invalid data to save

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#1089]
#### All up view and form view (without hoisted lu section)

To allow invalid data to save, before we have hoisted lu sections, it's should be as simple as . 
-  [x] update the logic to allow save even with validation errors

#### All up view
- [x] update the logic to allow save even with validation errors

#### In-line LG editor
- [x] update lg parse to be robust when invalid content are given
  - [x] done in C#
  - [x] migrate to js
- [x] migrate to new version of lg parser

**Comment by cwhitten** [comment]
As part of the linting effort we will close this out

**Comment by hibrenda** [comment]
addressed in #1667
