### ISSUE TITLE
Separate the sample bots into their own repos

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#1092]
**Is your feature request related to a problem? Please describe.**
As we continue to create new and update existing sample bots, they should be moved into repos of their own. This help will prevent accidental modifications to these being committed during normal dev and testing on the Composer app.

**Comment by cwhitten** [comment]
Punting to R8, not enough of a concrete plan

**Comment by cwhitten** [comment]
This is happening as part of the core runtime/packages work. Closing.
