### ISSUE TITLE
[Suggestion] Support intent folding in LU editor

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#1100]
## Version
What version of the Composer are you using? Paste the build SHA found on the about page.

## Describe the bug
Support intent pack up in LU editor. The LU file may have many utterances, so it will be hard to edit.  If we support pack up them by intent, LU edit will be much more easier.

**Comment by xieofxie** [comment]
Like ![image](https://user-images.githubusercontent.com/2876650/69603659-4808f580-1056-11ea-9a10-a2210852c042.png)

**Comment by cwhitten** [comment]
@DingmaomaoBJTU @xieofxie I'm not clear what you mean by "intent pack up" can you describe this a bit more?

**Comment by xieofxie** [comment]
@cwhitten It is the folding capability. See the down arrow in image.
It is useful when one is editing in the Bot Responses/User Input page.

**Comment by cwhitten** [comment]
This is coming in with R12
