### ISSUE TITLE
Updates on Content (minor) to align w ABS-H

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1130]
Please check out an updated version of the Bot Settings page here.
Updates are:
- Intro copy + link to documentation
- Nav order (settings, then publish)
- Button label = Test as soon as bot is started and opened in Emulator
- Deploy -> Publish
- Bot settings -> Settings
- Published -> In production
- Integration -> In test
https://www.figma.com/file/HLtKaKHctLldivPnzQ7BqQOI/Composer-MI-lotsotings?node-id=1596%3A4404

**Comment by cwhitten** [comment]
This is addressed
