### ISSUE TITLE
Set Dialog name to Begin Dialog action, when creating a new dialog from within a Begin Dialog action

### ISSUE THREAD

**Issue by yochay** [microsoft/BotFramework-Composer#1144]
## Describe the bug / To Reproduce
1. Add a Begin Dialog action
2. From the Begin Dialog action, create a new dialog
3. Results in a new dialog, which you can edit normally. 
4. However, the newly created dialog (setp #2) doesn't get assigned to the Begin Dialog steps, unless specifically (manually) setting the new dialog. 

## Expected behavior
The newly created dialog should be the value of the Begin Dialog action and being automatically set.

**Comment by alanlong9278** [comment]
I have tried to reproduce the bug, but got the expected behavior. Is the behavior shown in the following gif correct? @yochay  @a-b-r-o-w-n 
![beginDialog](https://user-images.githubusercontent.com/5860999/69125070-eb4e8d80-0adf-11ea-95fa-18896adba1b7.gif)
