### ISSUE TITLE
incorrect multi line lg

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#1152]
## Version
What version of the Composer are you using? Paste the build SHA found on the about page.

https://github.com/microsoft/BotFramework-Composer/commit/db1095302f2b674e6cf809da42379e0083ff6199

## Describe the bug
Give a clear and concise description of what the bug is.

Case 1:
![image](https://user-images.githubusercontent.com/2876650/67193346-b9d29b80-f427-11e9-8cce-8ba7810895d1.png)
![image](https://user-images.githubusercontent.com/2876650/67193362-c1924000-f427-11e9-94c8-922683b2fe17.png)

Case 2:
![image](https://user-images.githubusercontent.com/2876650/67193441-e1296880-f427-11e9-8506-4173d9a698ee.png)
![image](https://user-images.githubusercontent.com/2876650/67193456-e686b300-f427-11e9-8a76-aa67580a04c2.png)

## To Reproduce
1. Tested in ControllingConversation -> IfCondition

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by vishwacsena** [comment]
Dropping SDK label. Emulator/ webchat appears to be ignoring blank lines.
