### ISSUE TITLE
Output error for failed evaluation for better debugging

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#1153]
**Is your feature request related to a problem? Please describe.**

Failed evaluation evaluates to false now:
![image](https://user-images.githubusercontent.com/2876650/67193711-52691b80-f428-11e9-9477-9233ade11247.png)
![image](https://user-images.githubusercontent.com/2876650/67194006-dd4a1600-f428-11e9-8e73-d95f83c92343.png)

If could throw error at Branch, it will help debugging

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vishwacsena** [comment]
Tracked via the SDK issue referenced above.
