### ISSUE TITLE
cross button of prompt dialog is confusing

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#1168]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/19773357/67201859-d972bf80-f439-11e9-8beb-e05f292dc991.png)
the cross icon is confusing. it looks like you can close something or you have an exception here. but it is a button to open the exceptions page of prompt.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cwhitten** [comment]
Closing "as designed".
