### ISSUE TITLE
When new bot created, the bot page have about several seconds delay to show the bot.

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#1180]
## Version
master

## Describe the bug
When new bot created, the bot page have about several seconds delay to show the bot.

## To Reproduce
1. Go to create a new bot
2. The bot page still show the previous opened bot
3. It takes seconds to refresh to the new bot

This bug probably is because currently large amout of files need to be copied while creating a new bot.
We should not wait until it finished.

**Comment by cwhitten** [comment]
@sangwoohaan we need a loading convention in Composer :)

**Comment by sangwoohaan** [comment]
Is there anywhere else that a loading spinner would be needed? I personally have never experienced this.

**Comment by cwhitten** [comment]
Closing "as designed".
