### ISSUE TITLE
Many blank lines written to common.lg after adding and deleting lg activities

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#1211]
## Version
57baf4c8

## Describe the bug
Unecessary blank lines appear in common.lg file
![image](https://user-images.githubusercontent.com/8528761/67389802-f3dda200-f5cd-11e9-8ebd-ce2a36952685.png)

## To Reproduce
1. add a SendActivity action, input some text
2. delete it
3. repeat 1 & 2
4. check the common.lg file

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by yeze322** [comment]
In current master, there is zero blank line between lg templates:
![image](https://user-images.githubusercontent.com/8528761/68771022-2c6b1b80-0662-11ea-8276-2c41b940b48b.png)

Maybe we need at least 1 line?
@hibrenda @zhixzhan I reopened this issue

**Comment by cwhitten** [comment]
yes we should have one line separating each template

**Comment by zhixzhan** [comment]
> In current master, there is zero blank line between lg templates:
> ![image](https://user-images.githubusercontent.com/8528761/68771022-2c6b1b80-0662-11ea-8276-2c41b940b48b.png)
> 
> Maybe we need at least 1 line?
> @hibrenda @zhixzhan I reopened this issue

Will flow up with LG team @Danieladu 
1. '#bfdactivity-1234'  -- parse ---> {'bfdactivity-1234', [], '')    --- addTemplate --> '#bfdactivity-1234()'
2. line gap between templates

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1676
