### ISSUE TITLE
Delete multi-selected nodes won't clean LG resources

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#1213]
## Version
57baf4c8

## Describe the bug
Using the 'Delete' button in single click can delete LG resources, however, using multi-selection to select nodes and deleting them won't clean LG resources.

Related to #922 (parent)

## To Reproduce
1. create two SendActivity actions, input something
2. drag select them
3. click Delete in toolbar
4. common.lg not cleaned

## Expected behavior
Should be deleted

**Comment by yeze322** [comment]
pending on #1512

**Comment by yeze322** [comment]
in pr #1580

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1580
