### ISSUE TITLE
Composer should keep the state of 'Design Flow' page

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1220]
Current behavior
1. When a user is on the visual canvas
2. He/she transitions to Home page, LU all-up view, LG all-up view, settings view
3. Switching back to the visual canvas view would reset the state and auto-select the root dialog

Desired behavior
1. When a user is on the visual canvas
2. He/she transitions to Home page, LU all-up view, LG all-up view, settings view
3. Switching back to the visual canvas view should remember its state and display it as it was left off.

**Comment by yeze322** [comment]
which states should the editor remember?  I think at least two states 
1. which node was elected
2.  scroll position

**Comment by sangwoohaan** [comment]
Yeah that would work!

**Comment by yeze322** [comment]
i'm working on another item which may have conflicts with this item, so i plan to start this one in next sprint

**Comment by yeze322** [comment]
My plan didn't work 😭 keep it open but not for R8

**Comment by yeze322** [comment]
@lei9444 This is an old issue, it could be solved from Shell router.
The expected behavior is: when user switching back to 'Design Flow', states of 'Design Flow' should be remained(or recovered) instead of cleared.

To solve this problem, technically, we can either hide the component under a url instead of remount it (remained), or use some router cache to recover previous page (recovered).

**Comment by cwhitten** [comment]
Users can use the back button to achieve this today.

**Comment by sangwoohaan** [comment]
I strongly recommend us to implement this behavior – when you are moving between different pages, you don't always intentionally use the back button in order to go back to where it was. Also, the page state has to be preserved when you moved to multiple pages none-linearly. i.e) visual canvas -> LU all-up -> LG all-up -> home page -> visual canvas you should see the same state of visual canvas you left off

**Comment by cwhitten** [comment]
@sangwoohaan I didn't say we're not doing this, I only said we invested in supporting the browsers back button for these types of treatments. We will do this.

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/2671

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2969
