### ISSUE TITLE
Update installation instructions (docker etc)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#1247]
How do I install, step by step, prerequisites, and link from main readme.

(ref: https://github.com/microsoft/BotFramework-Composer/tree/stable/Composer)

**Comment by Kaiqb** [comment]
@cwhitten - are we supporting docker?

**Comment by zxyanliu** [comment]
Hi @scheyal 
FYI. Our current installation doc with yarn is [here](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/setup-yarn.md). I have doubled checked with @boydc2014, he said "docker is not recommended and supported" at this point. 

Thanks!

Yan

**Comment by zxyanliu** [comment]
We are closing this issue at this point and will reopen when the "docker" installation is supported in Composer. Thanks!
