### ISSUE TITLE
[hack 10/24] UX inconsistency when adding properties/conditions/intents in the right pane

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#1253]
## Version
Build SHA d547b08

## Describe the bug
The UX to add Validation rules in the exceptions tab of the "Bot Asks" text prompt requires you to hit Enter to add the validation rule after entering it in the textbox
![image](https://user-images.githubusercontent.com/17152540/67530732-e3cccd80-f674-11e9-8e6b-c20aa22be781.png)

The regex intent UX, which accomplishes the same kind of action, requires you to first click the Add button, which reveals new textboxes in which you type your values. 
![image](https://user-images.githubusercontent.com/17152540/67530841-39a17580-f675-11e9-854c-01ab2eab0234.png)

## Expected behavior
When jumping from one to the other I was confused. Consider consolidating these experiences

**Comment by sangwoohaan** [comment]
Being addressed in #1510
