### ISSUE TITLE
Update samples for public preview

### ISSUE THREAD

**Issue by yochay** [microsoft/BotFramework-Composer#1267]
Clean up pass for Samples

Change name of samples

|current name| new name| Description|
|----|----|---|
|Cards_Samples | Responding-with-Cards-Sample| A sample bot that uses Language Generation to create cards|
|Inputs_Samples | Asking-Questions-Sample| A sample bot that shows how to ask question and capture user input|
|Interrupt| Interruption-Sample| An advance sample bot that shows how to handle context switching and interruption in a conversation |
|Message_Samples | Responding-with-Text-Sample| A sample bot that uses Language Generation to create bot responses|
|ControlingConversation | Controlling-Conversation-Flow-Sample| A sample bot that shows how to control the flow of a conversation |
|Steps_Samples | Steps-Sample| A sample bot that shows how to use Dialog actions|
|ToDoBot | Todo-Sample|  A sample bot that allows you add, list, remove to do items |
|ToDoLuisBot | Todo-with-LUIS-Sample| A sample bot that allows you add, list, remove to do items and uses language Understanding |

Samples to remove:
- Bot Reminder has uses Az Function. We can't have that checked in or someone will abuse the function. 
- MyEmailBot
- QnAMakerSample --> remove until the sample is ready

### Updates to samples

**Cards**
- add a card that show how to bind to memory object in the bot. Within the branch set some memory object and use that in the template. Use https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/language-generation#using-chatdown-style-cards
- Add a new card example that includes structured resposne  https://github.com/microsoft/BotBuilder-Samples/blob/vishwac/master-4.6/experimental/language-generation/docs/structured-response-template.md
- does the samples uses the #cardActionTemplate?

**Responding-with-text** 
- show more advance LG 
- include samples from https://github.com/microsoft/BotBuilder-Samples/blob/vishwac/master-4.6/experimental/language-generation/docs/lg-file-format.md
and advnace samples from feature from https://github.com/microsoft/BotBuilder-Samples/blob/vishwac/master-4.6/experimental/language-generation/docs/structured-response-template.md
- add template composition 

**Steps**
-  in emit event, the begin dialog action is missing dialog name
- , add a QnA step, just call a QnA --> leave field empty (do not put QnA values)

Related to #762

**Comment by luhan2017** [comment]
all samples updates are merged, we can close this, please reopen if anything else is needed.
