### ISSUE TITLE
UX - Templates should get a default name 

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1291]
When opening a template, the user will likely expect to immediately see that template. Instead, one gets a file-new kind of experience. This is fine, but it'd be more userfriendly to pre-name the file, starting with the template name and a number or other so that the user can just hit next/open and continue the process vs stop and think what to name a file they didnt create on their own nor have seen what it contains. 

![Screen Shot 2019-10-28 at 10 58 51 AM](https://user-images.githubusercontent.com/48503434/67706209-994d9880-f975-11e9-8444-eee59d01111d.png)

**Comment by cwhitten** [comment]
Naming convention:

ExampleName-1
ExampleName-2
ExampleName-3
ExampleName-4

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1583

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1668
