### ISSUE TITLE
Hackathon instruction - needs info about LUIS authoring key

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1292]
The Hackathon instructions on Github currently do not mention the (potential) need to fill out a LUIS authoring key and or info on where to get this.

https://github.com/microsoft/BotFramework-Composer/blob/master/docs/07-11-2019-Hack.md#Create-your-first-bot-using-the-Composer

Could we add this info and/or a link to documentation (0pen up in other tab)?

Also - does this still work after using the 'Migration' flow from LUIS? I am not getting an error ...

**Comment by Kaiqb** [comment]
The document referenced no longer exists.
