### ISSUE TITLE
Ensure V4 to V4++ (Composer) compatibility

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#1293]
Ensure that the migration+integration path from V4 to Composer compatible productivity is smooth, easy, and fully supported.

Consideration: Team that has invested in developing substantial bot assets in V4 (or just completed migration from V3) would like to leverage the composer capabilities for all future development. 
They would need a supported one swing "migration" to convert their assets to composer compatible. At minimum they'll need an easy integration path.

**Comment by cwhitten** [comment]
@scheyal I'm going to close this as it's likely an ask on you, and I don't think you use Composer to track your work. Please check-in with me if I'm unclear here.
