### ISSUE TITLE
UX Copy - Publish to LUIS

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1295]
![Screen Shot 2019-10-28 at 12 26 35 PM](https://user-images.githubusercontent.com/48503434/67711032-5c39d400-f97e-11e9-8174-2b78c137622b.png)

The user clicked 'start bot' - seeing a dialog with the text Publish to LUIS is not only unexpected, it is also 'scary' - What??? I am publishing? To what? Who is LUIS anyways?

Proposed : change copy. if this is about LUIS then let's not show non-LUIS things. Let's stay away from the word 'publish' until we're actually publishing.
And: Replace button label to 'Test' - this is what ABS-H will have also.

Before:
Publish LUIS models

To use your language model, first publish the latest intents and examples to your LUIS instance. Where can I find this?
 NOTE: the current 'where can I find this' link goes to an internal site not accessible for no-msft people

-- PROPOSED ---
Start and test your bot

Your bot is using LUIS for natural language understanding and needs your account information and authoring key to connect to the ### _LUIS service_< link to LUIS.ai>. If you do not have an account yet, create a new account first. Learn more. <link to LUIS documentation >

- Project name (REMOVE TOOLTIP THINGY)
- Environment is not a LUIS setting - do we need this here? Can we remove this question and leave it to the 'PUBLISH' experience?

Link to authoring key info is herehttps://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-how-to-azure-subscription#trial-key

If I cannot change 'region' and 'Language', can we remove it?

**Comment by cwhitten** [comment]
@mareekuh we made some changes to improve this and we want to backlog this/look at in R8
