### ISSUE TITLE
Update lg template reference syntax

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#1308]
LG is moving in the direction of deprecating the syntax of '[]', in favor of "@{}" for consistence. 

And all the samples in SDK is using "@{}" already.

We should 3 places to present this new syntax,
1. update samples
2. the dialogFactory which do template creation 
3. the template extracting in dialogIndexer

to prompt this new syntax

**Comment by yeze322** [comment]
It's a blocker to Zhixiang, mark it as P0

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1663

**Comment by boydc2014** [comment]
reopen this to track the follow up work.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1676
