### ISSUE TITLE
[Bug Bash] [Bug Bash] Composer links to wrong syntax documentation for property names

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#1310]
## Version
Build SHA ac4bb13c

## Describe the bug
That links to [here](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/common-expression-language/prebuilt-functions.md) when it should probably link to [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/common-expression-language#variables). It seems like Composer doesn't differentiate between L-values and R-values.

## Screenshots
![image](https://user-images.githubusercontent.com/17152540/67727759-da5ea080-f9a7-11e9-87a0-e8e7ab2cd8f0.png)

note: submitted by Kyle Delaney in [VSO ](https://fuselabs.visualstudio.com/c3ee6a0b-5c54-4a3c-a479-588cfb0313ae/_workitems/edit/38465)

**Comment by cwhitten** [comment]
This was addressed
