### ISSUE TITLE
Show warning or indicator when user break the lg reference. 

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#1319]
A follow up of https://github.com/microsoft/BotFramework-Composer/issues/1300#issuecomment-547236442

We close that one due to the bug is fixed. Open this one to track the better experience when user intent to break some lg reference. What ux treatment should we provide so user can be aware the consequences of those operations? 

Also considering the capability of the editor interface the capability of language server, for implementation.

**Comment by a-b-r-o-w-n** [comment]
@boydc2014 is this still needed? I think the LG editor supports this now.
