### ISSUE TITLE
Composer should prevent changes being overwritten by other users/other tabs

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#1330]
**Is your feature request related to a problem? Please describe.**
It is currently quite easy to accidentally overwrite changes you've made to a dialog by editing an older version of that dialog that is already open in another browser window or browser tab.

Keeping multiple tabs and browser windows open is a very common practice. This will only get worse when multiple users edit the same bot in a hosted situation.

**Describe the solution you'd like**

If a user edits a dialog file, before persisting the changes, we should ensure that no NEWER CHANGES have already been written.

To achieve this, we can track the last modified date.  When the client sends the dialog content to be stored, the server should validate that the *client* date is the same as the *server* date, indicating that no newer changes have been stored.  Then, both the client and server dates are updated.

If the server date is newer than the client date, this indicates that new changes have been stored. The server should return an error message indicating that the user should reload the dialog to refresh it with the latest changes. Their local changes will be discarded.

**Comment by hibrenda** [comment]
@benbrown @cwhitten we did not solve the overwritten issues for multi-user scenario. how do we want to address this ? target to R9 or later ?
