### ISSUE TITLE
UX Copy | Capitalization consistency

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1333]
Please check the CapitAlizaTioN for the menUs to ensure they are all Sentence case (vs Title Case) to make sure we're consistent

- Property management -> all flyouts should have 'property' in lower case
- Dialog management -> Replace and Repeat have 'dialog' in lower case
- Conditions -> Branch: if/else
- Conditions -> Branch: Switch

Please update
Connect to QnA Knowledge base to - Connect to QnA Maker

**Comment by cwhitten** [comment]
This was addressed in the recent Naming party
