### ISSUE TITLE
Authoring key will be persist to disk

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1353]
## Version
master & stable

## Describe the bug
Authoring key , endpointkey and knowledgebaseid will be persist to disk.

## To Reproduce
1. Go to setting page
2. enter qna configuration and luis authoring key 
3. password will be persist to disk 

## Expected behavior
all these sensitive messages should only be cached in memory

**Comment by luhan2017** [comment]
Closed by #1424
