### ISSUE TITLE
UX | Why can I not change the trigger type once I've selected it? 

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1361]
There are many trigger types that the user can select from. They may need to open it and view it in the canvas before they understand what they do and decide if the one selected is indeed the one the had in mind. It'd be great if we can allow users to change the trigger type easily. I think this will come in very handy as it allows people to copy and paste and just change the trigger type when they want to start another, similar trigger/dialog.

**Comment by cwhitten** [comment]
ping
