### ISSUE TITLE
Update default folder when Creating a new bot

### ISSUE THREAD

**Issue by yochay** [microsoft/BotFramework-Composer#1363]
## Version
cd1cc71f (from Master 10/30/2019)

## Describe the bug
When creating a new bot, use a dedicated folder that is outside of Composer repo. The default project folder for new bots should not be MyBots under Composer. 

![image](https://user-images.githubusercontent.com/896149/67896101-ec138580-fb18-11e9-89a3-989b67c87f96.png)

For windows use %userprofile%\Documents\Composer\
- create the folder if doesn't exists 

For Mac it should be in /user/documents/composer 
- create the folder if doesn't exists

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1548
