### ISSUE TITLE
Selection of actions doesn't scroll to the right

### ISSUE THREAD

**Issue by Jeffders** [microsoft/BotFramework-Composer#1365]
When I try to select a bunch of actions and they are off the screen, the selection doesn't 'scroll' to the right or left. It does allow scroll down, but not left or right.

**Comment by alanlong9278** [comment]
I've file an issue to Fabric UI Repo. https://github.com/OfficeDev/office-ui-fabric-react/issues/11047

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1607
