### ISSUE TITLE
CSharp BotProject won't run or build with CLI dotnet

### ISSUE THREAD

**Issue by Jeffders** [microsoft/BotFramework-Composer#1367]
## Version
master (of the universe)

## Describe the bug
I went to the BotProject/CSharp directory and tried to do 'dotnet run' and got errors. I then tried dotnet build' and got these errors:

c:\Repos\BotFramework-Composer\BotProject\CSharp>dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for c:\Repos\BotFramework-Composer\BotProject\CSharp\BotProject.csproj...
  Restoring packages for c:\Repos\BotFramework-Composer\BotProject\CSharp\Tests\Tests.csproj...
C:\Program Files\dotnet\sdk\2.2.101\NuGet.targets(114,5): error : Unable to load the service index for source https://msazure.pkgs.visualstudio.com/_packaging/Official/nuget/v3/index.json. [c:\Repos\BotFramework-Composer\BotProject\CSharp\BotProject.sln]
C:\Program Files\dotnet\sdk\2.2.101\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [c:\Repos\BotFramework-Composer\BotProject\CSharp\BotProject.sln]

Build FAILED.

C:\Program Files\dotnet\sdk\2.2.101\NuGet.targets(114,5): error : Unable to load the service index for source https://msazure.pkgs.visualstudio.com/_packaging/Official/nuget/v3/index.json. [c:\Repos\BotFramework-Composer\BotProject\CSharp\BotProject.sln]
C:\Program Files\dotnet\sdk\2.2.101\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [c:\Repos\BotFramework-Composer\BotProject\CSharp\BotProject.sln]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:06.56

## To Reproduce
See above

## Expected behavior
Runs and builds.

**Comment by luhan2017** [comment]
Close it because it is not an composer issue, it should be user's local environment issue. Please reopen it if it is still an issue
