### ISSUE TITLE
[Docs] Introduction to Bot Framework Composer Doc bugs

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#1370]
List of minor edits:

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/bfcomposer-intro.md#introduction-to-bot-framework-composer

1) First sentence; two uses of "for" seems odd; second should maybe "to build" instead of "for building"
 
https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/bfcomposer-intro.md#advantage-of-developing-bots-botframework-composer

2) Second column; "combination of adaptive dialogs" should probably just be "use of adaptive dialogs"

3) "Drag-and-drop UI in BF Composer IDE"; maybe "visual representation and editing in Composer IDE"?  I'm not sure we even have drag & drop.

4) "Runtime Environment" should probably be "Debugging environment", i think runtime means something different in this context.

5) "No longer need to set up or maintain LU model as it is maintained within app" - probably should be "No longer need to navigate between experiences to maintain LU model as it is editable within the app".

6) Last paragraph in this section describes making life simpler but ends up sounding very complex.  Reduce?  "Overall the Bot Framework Composer makes it simpler and quicker for both experienced and novice developers to create robust bots by visualizing dialogs, leveraging language generation (LG) to simplify complex tasks (interruption, developing bots with character, etc), reducing the number of steps necessary to gets bots running, and keeping and training of the NLU components of your bot all within the Bot Framework Composer."

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/bfcomposer-intro.md#language-understanding-lu

7) Title is mixed case for this section; others are capitalized

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/bfcomposer-intro.md#unified-toolset

8) Assume known, however:  "[Adaptive Dialogs](Yan's link, or link to adaptive?)" needs replaced

9) First time I've seen this phrase: "Bot Framework library." ; does it mean repo or library of tools, or?

**Comment by emgrol** [comment]
Closing this now that the aforementioned changes in my previous comment are now [live](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/bfcomposer-intro.md).
