### ISSUE TITLE
[Hack 10/30] Creating a bot from scratch using a name of an existing bot, loads the existing bot instead of warning me

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#1372]
## Version
Build SHA 7652c4d4

## Describe the bug
Creating a bot from scratch using a name of an existing bot, loads the existing bot instead of warning me.

## To Reproduce
0. Make sure you have an existing bot with dialogs in the default folder
1. Go to the home and click "New"
2. Click on Create from scratch and click next
3. Give it the same name as the existing one in your folder
4. Composer loads the existing bot

## Expected behavior
Composer should warn that a bot with the same name exists and prompt for a new name or something along those lines.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/issues/1445
