### ISSUE TITLE
[Docs] Naming capitalization inconsistency

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#1373]
Assuming it's across docs, but minimally in this one: https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/bfcomposer-intro.md

We have "language understanding", "Language understanding", "Language Understanding", and "LU" sprinkled throughout.  Similar for Language Generation.  We should determine if these are proper nouns, and if so, capitalize consistently.  Probably also impacts "Adaptive Dialogs", but i didn't see it here.

**Comment by emgrol** [comment]
I edited the docs (see commits) to use the naming schema proposed above. Closing this now that everything is consistent.
