### ISSUE TITLE
[Docs] Edits to "Create an echo bot using Bot Framework Composer"

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#1375]
https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/tutorial-create-echobot.md#creating-an-echo-bot

1) "This is a simple echo bot. It echos back the user's response." - should be echoes.

2) Since this is the first time they're introduced, we should have links for "Recognizer and LUIS Models" to reference or dictionary items describing what these things are (content below)

"On the right in the Property panel click the dropdown under Recognizer Type and select None. Since this is a simple echo bot you don't need to use any recognizers or LUIS models."

**Comment by emgrol** [comment]
Closing this now that the aforementioned changes in my previous comment are live.
