### ISSUE TITLE
[DOCS] Remove / change comparison between Adaptive / Composer to Waterfall

### ISSUE THREAD

**Issue by yochay** [microsoft/BotFramework-Composer#1376]
## Version
doc - https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/bfcomposer-intro.md#advantage-of-developing-bots-botframework-composer 

We should remove the table. 

We can pick some of the benefits highlighted in to the "advantage" column.

Adaptive is built on top of V4 SDK. You will be able to call a waterfall dialog from within Adaptive. 

But we should not compare.

**Comment by emgrol** [comment]
Removed the table, added advantages in bullet format. Closing now that changes are [live](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/bfcomposer-intro.md) and visible.
