### ISSUE TITLE
Cannot delete a dialog | does the : (triple dot) not work or can we not remove a dialog from the left nav?

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1378]
I created a dialog with all of the trigger events available and now want to remove that whole dialog. when clicking the dialog no 'delete' button shows up in the toolbar and no menu for edit options shows up on clicking the : tripple dot button

<img width="600" alt="Screen Shot 2019-10-30 at 2 53 49 PM" src="https://user-images.githubusercontent.com/48503434/67902048-7f52b800-fb25-11e9-84f0-779630117144.png">

**Comment by cwhitten** [comment]
Closing "as designed". The delete dialog control is the kebab icon next to the dialogs name ini the left nav.
