### ISSUE TITLE
Step 01 in WeatherBot instructions should show Intent = None highlighted

### ISSUE THREAD

**Issue by seaen** [microsoft/BotFramework-Composer#1379]
## Version
MASTER - 10/30 bugbash

## Describe the bug
Give a clear and concise description of what the bug is.

## To Reproduce
1. Follow this tutorial till step 8:
https://github.com/vishwacsena/composer-managed-lab/blob/master/01-create_bot.md

Note: instructions say to select Recognizer = None, but the screenshot selects Recognizer = LUIS.

## Expected behavior
Expected: screenshot shows None selected

## Screenshots
![image](https://user-images.githubusercontent.com/38896146/67902141-c04acc80-fb25-11e9-9031-ed1fd3ce6e34.png)

**Comment by emgrol** [comment]
I've updated the file in [this commit](https://github.com/microsoft/BotFramework-Composer/commit/488f065ebc00a4861aa1706053cc40fe5f248b9d) and added a [.gif](https://github.com/microsoft/BotFramework-Composer/raw/kaiqb/BFC-Docs/docs/media/tutorial-weatherbot/01/recognizer-none.gif) showing the `None` type being selected.
