### ISSUE TITLE
[Docs] dialogs topic

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#1380]
https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-dialog-draft.md

1) "in a visual interface and does not require you to write code." - and do not require you

2) [!NOTE] is this supposed to be shown or a messed up markdown tag?

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-dialog-draft.md#types-of-dialogs

3) "new bot and it has a .Main extension."  has a .Main file extension when you view the files on disk.

4) GIF should have alt text, and not be click-navigable

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-dialog-draft.md#anatomy-of-a-dialog

5) "A dialog contains a set of event handlers. Triggers are event handlers that can be triggered to handle different events." - not sure but I think this is a circular description.  What is the value of the term triggers if everything is described as an event/event handler?

6) "LUIS recognizer (default) and Regular Expression Recognizer" - needs consistent casing

7) "Users can also add branchs and loops"  - branches

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-dialog-draft.md#use-dialogs

8) "You can leave the Localtion field as is at this time." - location rather than localtion

9) "**Congradulations! You have created your first bot **" - Congratulations.

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-dialog-draft.md#add-a-dialog

10) "contains a chunck of functionality" - chunk

11) "you created on the nevigation pane." - navigation

12) "Begin a new dialog is a dialog action that begins a dialog." - circular definition; may be okay.

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-dialog-draft.md#dialog-actions

13) "few dialogs or even dozens of hundres of individual dialogs" - hundreds.

14) "individual dialogs and it is a big challenge to manage the dialog system and the conversation with user" - maybe this should be "and traditionally it's difficult to manage the..." since the following statement is that the composer makes it easier.

**Comment by zxyanliu** [comment]
Closing since all bugs are fixed.
