### ISSUE TITLE
"Create a trigger" options are not clear and need more explanation - both in the UI and in docs

### ISSUE THREAD

**Issue by seaen** [microsoft/BotFramework-Composer#1381]
## Version
MASTER - 10/30 bugbash

## Describe the bug
In "Create a trigger" dialog, it is not clear what the options other than Intent and Unknown Intent do.  Needs better explanation in UI and docs.

## To Reproduce
1. Follow  Weather Bot part 02:  https://github.com/vishwacsena/composer-managed-lab/blob/master/02-create_dialog.md
2. Reach step 5 on that page
ISSUE:  Handle Intent and Handle Unknown intent are straightforward - but have no idea what the other three options are.  

## Expected behavior
Expecting more details on what to do with three options at the end of the list - and need a short explanation in the UI and a short overview of these steps in Step 5 in tutorial

## Screenshots
![image](https://user-images.githubusercontent.com/38896146/67902745-25eb8880-fb27-11e9-95c4-c02460d08173.png)

**Comment by mareekuh** [comment]
Link to proposed design: https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=2274%3A1
