### ISSUE TITLE
[DOCS] Images should not have transparent backgrounds

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#1383]
## Version
https://github.com/microsoft/BotFramework-Composer/tree/kaiqb/Ignite2019

## Describe the bug
Images with transparent backgrounds don't look right when viewed on different backgrounds, like when the image is viewed on its own instead of on a GitHub page. Text on a transparent background can become unreadable.

## Expected behavior
Images should have solid backgrounds.

## Screenshots
![image](https://user-images.githubusercontent.com/41968495/67902832-53d0cd00-fb27-11e9-8736-bee3e5b1db30.png)

![image](https://user-images.githubusercontent.com/41968495/67902789-3dc30c80-fb27-11e9-912b-19cbf5c7d4ed.png)

**Comment by emgrol** [comment]
The image [background](https://raw.githubusercontent.com/microsoft/BotFramework-Composer/master/docs/media/introduction/composer-overview.png) is now white, not transparent. Closing this now that the changes are live.
