### ISSUE TITLE
LUIS list entities and multi-choice prompts should be the same

### ISSUE THREAD

**Issue by Jeffders** [microsoft/BotFramework-Composer#1388]
I have a fixed list of choices, each with a set of synonyms. For example, if I support 8 different regions. I can have an intent with a "list entitiy" with the set of list values so the user can type:

"Run the test in West US"

And then LUIS and the list entity helps me figure out the region. 

But if the user types in:

"Run the test"

I then need to prompt the user for the region, which logically I would do with a multi-choice prompt. But the source list, is the exact same as I already typed into LUIS and it stinks keeping these two lists in sync.

So my feature request is to make list data available as both a list entity and a multi-choice prompt in some easy way.

**Comment by cwhitten** [comment]
@Jeffders the SDK discussion was closed and is a requirement for this -- can you recreate the ask on `botbuilder-dotnet` ? 

Closing for now.

**Comment by AlexBrownShi** [comment]
I don't understand what happened to this request.  Was it implemented?
