### ISSUE TITLE
[DOCS] Clicked images should link to the raw image instead of a GitHub code page

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#1391]
## Version
https://github.com/microsoft/BotFramework-Composer/tree/kaiqb/Ignite2019

## Describe the bug

Users have to click on images to enlarge them so they can read the small text. Documentation images link to GitHub code pages like this: https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/media/introduction/overview.png

This is not an ideal format to view the image because it doesn't automatically scale to fit the screen.

## Expected behavior
If we link to the raw image like [this](https://user-images.githubusercontent.com/41968495/67903741-a27f6680-fb29-11e9-9ae2-06ef29b5ff7c.png) instead then the browser can provide the usual functionality for making images easy to view.

## Screenshots
![image](https://user-images.githubusercontent.com/41968495/67903844-e4101180-fb29-11e9-8e41-6207d00991fc.png)

**Comment by Kaiqb** [comment]
The docs for Composer are going to move from GitHub into docs.microsoft.com and that will address this issue. For the public preview, we are using GitHub as it is easier to manage things.
