### ISSUE TITLE
[Docs] Events and Triggers Topic

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#1394]
https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-events-and-triggers-draft.md#handle-intent-events

1) "The Handle Unknown Intent handles "none" intent." - does this mean specifically the LUIS none intent, or any unknown intent?

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-events-and-triggers-draft.md#luis-recognizer

2) "The content is managed by LUDown, a command line tool that helps covert .lu file(s) into JSON files for language processing applications such as LUIS and QnA knowledge base." - not sure customer needs to know about LUDown (or that it even exists).  Also we don't feed QnA anymore from LU files, correct?  It's a new format or something?  Also, consider using "language understanding"

3) "child dialogs using the syntax memory path" - what is a syntax memory path?  Link?

4) "On the right side of the Composer menu, choose Regular Expression as recognizer type" - include "for your trigger" as that is a context sensitive panel?

**Comment by zxyanliu** [comment]
Closing since all bugs are fixed.
