### ISSUE TITLE
Pressing "Restart bot" and then "Test in emulator" opens the new instance of emulator every time

### ISSUE THREAD

**Issue by seaen** [microsoft/BotFramework-Composer#1395]
## Version
MASTER - 10/30 bugbash

## Describe the bug
Pressing "Restart bot" and then "Test in emulator" opens the new instance of emulator every time instead of _restarting_ the current test in emulator.

## To Reproduce
1. Work on a bot
2. Press Restart bot
3. Press Test in emulator.   Emulator opens.  Test the bot.
4. Work on the bot more in Composer
5. Press Restart bot
6. Press Test in Emulator.

ISSUE: instead of restarting the conversation, entirely new window of Emulator opens.  After a few minutes, you have 20+ emulator windows open. 

## Expected behavior
EXPECTED INSTEAD:  If you press Restart and then Test in Emulator, I expect the same instance of emulator to restart - not an entirely new instance to open.    Fallback: maybe open a new tab in the existing emulator instance if you want to preserve the past debugging session.

## Screenshots
![image](https://user-images.githubusercontent.com/38896146/67904598-13278280-fb2c-11e9-9a19-86edcc8dd246.png)

**Comment by cwhitten** [comment]
This is not the behavior on my Mac. @hibrenda can you repro on Windows?

**Comment by hibrenda** [comment]
Yes. this is reproduced on Windows.

**Comment by shyambabu-kolipaka** [comment]
This is the issue at Emulator side. This is an enhancement for Emulator. You could check the enchancement updates [here](https://github.com/microsoft/BotFramework-Emulator/issues/1589)
