### ISSUE TITLE
Typing while publishing is a no-no

### ISSUE THREAD

**Issue by Jeffders** [microsoft/BotFramework-Composer#1400]
## Version
m@$ter

## Describe the bug
I published a big chunk of LU, and as it was publishing, I made some changes...probably made some mistakes in the LU, and then I got an error saying there was a problem publishing.

## To Reproduce
Make a big LU file, click restart bot, then keep changing the LU...you'll get an error

## Expected behavior
Probably shouldn't be able to edit things while you are publishing.

## Screenshots
N/A

## Additional context
I was doing bad things. So I got a bad result.

**Comment by boydc2014** [comment]
Given the structure change and the runtime decoupling effort, we probably do this after all settle down, punt this to R9

**Comment by boydc2014** [comment]
@liweitian  can you confirm again, if we still have this? i think by bringing into cross-train, we should already resolve this.

**Comment by liweitian** [comment]
@boydc2014 test it again on my side. I cannot reproduce this bug.

**Comment by cwhitten** [comment]
Thanks @liweitian
