### ISSUE TITLE
[Hackathon] Deployment fails

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/BotFramework-Composer#1401]
## Version
Master branch for 10/30 hack

## Describe the bug
Deployment step fails

## To Reproduce
1. Go to "Configuration"
2. Click on "Publish"
3. On the "Create Azure Resources" page, click "Copy to clipboard"
4. Run the command in Powershell.
5. Yout get the following error:
PS C:\Temp\BFC\BFComposer\MyBots\HelloComposer> pwsh ./Scripts/create.ps1 -name HelloComposer -environment HelloComposerKI -location USNatWest -appPassword '1qazXSW@3edcVFR$'                                                                  '--identifier-uris' is required for creating an application
! Could not provision Microsoft App Registration automatically. Review the log for more information.
! Log: C:\Temp\BFC\BFComposer\MyBots\HelloComposer\Scripts\..\create_log.txt
+ Provision an app manually in the Azure Portal, then try again providing the -appId and -appPassword arguments. See https://aka.ms/vamanualappcreation for more information.
PS C:\Temp\BFC\BFComposer\MyBots\HelloComposer>

## Expected behavior
Azure resources are created.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1423
