### ISSUE TITLE
[Docs] Defining Triggers edits

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#1406]
https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/howto-defining-triggers.md#defining-triggers

1) "Each dialog in Bot Framework Composer includes a set of triggers (event handlers) that contain instructions for how the bot will respond to inputs received when the dialog is active. There are several different types of event handlers available in the Composer menu. They all work in a similar manner and can be interchanged in some cases. In this article, we will walk you through how to define each type of the triggers. If you are not familar with events and triggers in Composer, please read the events and triggers concept article."

We should just remove all use of event handler here.  If they're all "triggers", then they're triggers and event handler should only be used once to describe them conceptually, maybe in a glossary or reference topic.

2) "each type of the triggers" should be "each type of trigger"

3) "familar" should be "familiar".

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/howto-defining-triggers.md#1-select-a-recognizer-type

4) Should the product UI refer to LUIS as "Language Understanding Cognitive Service" instead?  Acronym seems non-discoverable except to those in the know.

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/howto-defining-triggers.md#define-handle-unknown-intent

5) "utterence is not recognized (the None Intent). Unlike" - is None Intent a LUIS concept or generally a recognizer concept?  Otherwise lets just use "Unknown intent".

6) "utterence is not recognized (the None Intent). Unlike" - utterance.

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/howto-defining-triggers.md#define-handle-an-event-activity

7) "Handle an Event: Activity is a type of trigger used to handle activity events such as a Handle ConversationUpdate activity. " - more precisely; "Handle an event: Activity is a type of trigger used to handle events such as your bot receiving a ConversationUpdate Activity."

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/howto-defining-triggers.md#1-define-an-emit-a-custom-event-event

8) "On the peroperty editor on the right side, " - should be property

9) "check Bubble event. When Bubble eventis checked this event will be passed on to the parent dialogs to look for handlers to handle it." - is "Bubble event" a verb, or a noun?  Also, "evenits" is "event is"

**Comment by zxyanliu** [comment]
Closing since all bugs are fixed.
