### ISSUE TITLE
Impossible to guess validation rules field can have more than one rule

### ISSUE THREAD

**Issue by seaen** [microsoft/BotFramework-Composer#1408]
## Describe the bug
Impossible to guess validation rules field can have more than one rule; need an affordance in the UI to indicate possibility of multiple rules

## To Reproduce
1. Go to Ask a user -> Text input -> Exceptions
2. Click on Validation Rules field.

ISSUE: this field supports multiple rules (can be accessed by typing a rule and pressing Enter).
But there is no indication of that in the UI - no "+" sign or similar like in other places of the UI.

## Expected behavior
EXPECTED INSTEAD: There should be a "+" sign or some other UI affordance/indicator signalling that this field accepts multiple rules.

## Screenshots

![image](https://user-images.githubusercontent.com/38896146/67906374-913a5800-fb31-11e9-8cc5-38ea4f8b694f.png)

**Comment by sangwoohaan** [comment]
Being addressed in #1510
