### ISSUE TITLE
[Docs] Language Generation topic

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#1409]
https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-genereation-draft.md#language-generation

1. "Bot Framework Composer natively supprt language generation" - natively supports

2. " current bots' memory" - shouldn't this be "current bot's memory"?

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-genereation-draft.md#tamplates

3. "Tamplates" should be "Templates" (found multiple places)

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-genereation-draft.md#template-types

4. "Strucutred template (this is new and read more here)" - Structured

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-genereation-draft.md#where-to-define

5. "there are two LG editors: an inline LG editor and an LG editor (Bot Responses) listing all templates" - confusing; maybe "an inline LG editor and the Bot Responses LG editor that lists all templates"

6. "LG editor which hoists the relevant templates content." - hosts

7. "Click on the bot icon on the left side of the navigation pane' - maybe indicate to click the "Bot Responses item (bot icon when collapsed)"

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-genereation-draft.md#how-to-define

8. "To define a multi-line response you will need to use a pair of triple dots to wrap the multi-line responses." - sample doesn't show triple dots.  My guess is they are lost as markdown interprets them on github

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-genereation-draft.md#structured-template

9. "Cards, SuggestedActions and other Chatdown style constructs." - is Chatdown still a thing?

**Comment by zxyanliu** [comment]
Closing since all bugs are fixed.
