### ISSUE TITLE
[Docs] Language Understanding Topic

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#1410]
https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-understanding-draft.md#language-understanding

1) "Language Understanding (LU) is the process for a bot to understand language naturally and contextually so a bot will decide what to do next in a conversation flow. " - I found the use of "the process for a bot to" to be confusing - maybe "Language Understanding (LU) is used by the bot to understand language naturally and contextually to determine what next to do in a conversation flow".  

2)  "on to event hanlders which define" - handlers, or possibly triggers?

3) "You wire up LU models with dialog" - not sure what this really means

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-understanding-draft.md#intents

4) "The basic idea behind is quite simple:" - behind Intents?

5) "When an intent is captured some pre-defined action will fire." - maybe instead reuse the word "trigger"; ie "when an intent is identified, an associated trigger causes an action to fire"

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-understanding-draft.md#entities

6) "Entities are a collection of objects data extracted " - object data?

7) "An intent presents the prediction of the entire utterance. "  - this is confusing.  maybe "An intent indicated what the user is trying to do" or something

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-understanding-draft.md#step-one-set-up-a-recognizer-for-specific-dialog

 8) "LU content" - generally; this feels like it shouldn't be an acronym we use everywhere.  Not sure what to replace with though

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-understanding-draft.md#step-three-wire-up-lu-with-handle-an-intent-trigger

9) "The Handle an Intent trigger is an event handler which defines " - maybe "The Handle and Intent trigger defines"; - "is an event handler" isn't needed IMO

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/concept-language-understanding-draft.md#step-four-publish-lu-luis

10) "and wether it is published or not." - whether

**Comment by zxyanliu** [comment]
Closing since the content is updated.
