### ISSUE TITLE
[Docs] Set up Bot Framework Composer using Yarn

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#1411]
https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/setup-yarn.md#open-composer-in-a-browser

1) " https://localhost:3000." - i'm betting there's no ssl cert on localhost.

**Comment by emgrol** [comment]
The [page](https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/setup-yarn.md#open-composer-in-a-browser) now has the correct address. Closing this issue now that the changes are live.
