### ISSUE TITLE
"+ New Dialog" button should stay at the top, not keep creeping down to the bottom of the dialog list

### ISSUE THREAD

**Issue by seaen** [microsoft/BotFramework-Composer#1415]
## Describe the bug
When adding more and more dialogs, the "+ New Dialog" keeps staying at the bottom of the list of dialogs and keeps getting harder and harder to get to.  Instead, should stay at the top of the list.

## To Reproduce
1. Create a complex bot with many dialogs
2. Add more dialogs

OBSERVE ISSUE: "+ New dialog" button keep sliding further and further off-screen, becoming harder and harder to access.  

![image](https://user-images.githubusercontent.com/38896146/67908230-f729de00-fb37-11e9-8238-7270dbeb1cb6.png)

 ## Expected behavior
EXPECTED INSTEAD:  New Dialog button should stay docked at the top of the list of the dialogs and not move further away with each new dialog. 

Should stay in the same, predictable space. Like so, but with the proper UI look:
![image](https://user-images.githubusercontent.com/38896146/67908370-833c0580-fb38-11e9-9287-36c070b9b0e1.png)

**Comment by mareekuh** [comment]
The comment makes sense (good point), however the solution to add a button as suggested won't scale... Please implement the universal 'add' button in the toolbar which allows the user to choose what to add if there is ambiguity.
1. add a 'add' button in the toolbar.
2. When click 'add', show menu with the following options:
Dialog (Show 'Open dialog' ux )  
Trigger   (Show 'create trigger' ux)  
Skill  (Show 'skill picker' ux )  
Action >  (cascading menu that shows same options as + icon in the flow in Design mode)

<img width="511" alt="Screen Shot 2020-01-25 at 7 32 17 PM" src="https://user-images.githubusercontent.com/48503434/73130233-6b461780-3fa9-11ea-9d23-b63f04c2727f.png">

@hibrenda 
@sangwoohaan 
@cwhitten

**Comment by sangwoohaan** [comment]
I think the universal add button would make sense, but I have an overall concern about the scope of the toolbar actions. Some of the items are bot-level actions(Undo, Redo, and potentially the universal add button) while some of them are just canvas-level(Cut/Copy/Delete only work for action nodes) currently. We probably need to clarify this scoping issue first. Cut/Copy/Delete actions could potentially do the same for dialogs and triggers, but then the current design of the toolbar should change to look more like it is a global thing.

**Comment by sangwoohaan** [comment]
Related issue : https://github.com/microsoft/BotFramework-Composer/issues/1860

**Comment by cwhitten** [comment]
Closing. Reference attached issues for updated.
