### ISSUE TITLE
Condition editor should offer view into memory/autocomplete

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#1422]
When constructing a Dialog within Composer using the `Event` trigger I needed to check properties on the Activity.

Being new to the composer it wasn't clear what the variable/memory name was for the received activity. The canvas shows MessageActivity:

![image](https://user-images.githubusercontent.com/33519520/67931966-e66e7c00-fbba-11e9-8dbd-615830d9718b.png)

The Condition Editor doesn't provide any help when trying to figure out what is in memory. `activity` would be natural expectation (from a developer point of view but won't be a expectation we can rely on given the broader userbase). 

By digging through some samples I found an example `turn.activity` at which point I could then perform the check for SemanticAction needed (`turn.activity.SemanticAction !=null`)

## Expected behavior
- Code completion for local memory variables and properties on these objects 
- Design time validation of expressions - for example I was able to type `activity.SemanticAction != null` which only displayed an error at runtime.

**Comment by zxyanliu** [comment]
@hibrenda is this issue resolved?

**Comment by cwhitten** [comment]
This is done! Closing
