### ISSUE TITLE
UX Backlog | Design and implement 'add' menu for toolbar

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1436]
Design 'add' menu for the toolbar from where people can choose what type of thing to add w/o having to go to the Home page or rely on inline + buttons.
This includes determining the UX for what happens when an action gets added. Where does it get added?

![Screen Shot 2019-10-31 at 3 09 01 PM](https://user-images.githubusercontent.com/48503434/67989919-93fc8200-fbf1-11e9-8a1d-871569c6317c.png)

**Comment by cwhitten** [comment]
This has been done (a few times since this ticket was created)
