### ISSUE TITLE
Trigger node label, trigger type, trigger name changing

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1437]
Addressing https://github.com/microsoft/BotFramework-Composer/issues/1428, https://github.com/microsoft/BotFramework-Composer/issues/1244, https://github.com/microsoft/BotFramework-Composer/issues/1407, and an additional interaction design issue that appeared through some of the decisions we made separately.

Currently, once you create any type of trigger, you can change its name on the right pane. I don't think this should be possible at this point since we are not allowing users to define names for triggers, besides the intent trigger(even for the intent trigger, we ask users to specify 'intent name' which we are making it its trigger name as well). 

My suggestions regarding this:
- The re-naming behavior on the right pane should be removed for all triggers except the intent trigger.
- For the intent trigger, it is not clear whether the name you specified in the trigger wizard is the name for your intent or trigger – because you were just asked to fill out an intent name but what you are changing on the right pane is a trigger name. It should be **the trigger name** that users would be asked to specify in the trigger wizard, not the intent name.

Regarding #1428, here's my design suggestion (see the designs in the red box)
https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=3054%3A195

**Comment by sangwoohaan** [comment]
The final design suggestion for reviewing 11/7 : https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=3129%3A1408

**Comment by yeze322** [comment]
We need to finalize what's the exact content (black/grey text) shown in trigger text of each trigger type
![image](https://user-images.githubusercontent.com/8528761/68368981-2792fd00-0174-11ea-9305-0a644532b286.png)

![image](https://user-images.githubusercontent.com/8528761/68369665-d08e2780-0175-11ea-9e09-ce40dd8bbc1b.png)

Collected some details from design:

|Trigger Type|Name to show (black)|Label to show (grey)|
|-------|--------|----|
|Intent|`$designer.name` > ?| `(Intent trigger)`|
|Unrecognized intent|`$designer.name` > ?|`(Unrecognized intent trigger)`|
|Dialog trigger|`$designer.name` > ?|?|
|Activity trigger|`$designer.name` > ?|?|
|Message activity trigger|`$designer.name` > ?|?|
|Custom trigger|`$designer.name` > ?|?|

**Comment by yeze322** [comment]
In PR #1529

**Comment by mareekuh** [comment]
i swear I already responded to this.
For Intent show: 

- Intent
- Unrecognized intent

Dialog trigger, show:

- Dialog started (BeginDialog)
- Dialog cancelled (CancelDialog)
- Error occurred
- Re-prompt for input

Activity trigger show:
- Conversation started (ConversationUpdate)
- Conversation ended
- Handover to human
- Conversation invoked
- User is typing
- Event received

Message activity trigger, show: 

- Message received
- Message updated
- Message deleted
- Message reaction (thumbs up/down)

Custom trigger:
Custom trigger
