### ISSUE TITLE
Docs  | Introduction to Composer

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1438]
Comments for this document:
https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/bfcomposer-intro.md

---

1. Please replace the picture. Better to make the call-outs live text so it's editable. 
/Users/Mariekei/Downloads/ScreenshotComposer.png

2. Terms and areas on the page that would be valuable to call out:
Menu​
- Design​
- Bot Responses​
- User input​
 - Settings​

Trigger
Action
Authoring canvas
Property Panel
Dialog
Properties 

3. ## Advantage of developing bots with Composer -> 
Add references to the UI terms: Language Generation (Bot Responses) and LU (User input) 

Can we add the visual element as an advantage: The ability to design a dialog visually

4. It's not quite drag and drop. You can copy, paste, reuse and drag and drop actions or groups of actions, but you can't quite drag/drop any element

5. Can we move this section to the top of the dialog (under '## Advantage of developing bots with Composer). [Overall] Composer makes it simpler and quicker for both experienced and novice developers to create robust bots by visualizing dialogs, leveraging language generation (LG) to simplify complex tasks (interruption, developing bots with character, etc), reducing the number of steps necessary to gets bots running, and keeping and training of the NLU components of your bot all within Composer.

It is a nice introduction and provides some context that is helpfful to understand the 'advantages'/

6. ## Language understanding (LU) -> Language Understanding (User Input)

7. ## Language Generation (LG) -> Language Generation (Bot Responses)

8. Move this ## Unified toolset above ## Language Understanding (User Input)

**Comment by Kaiqb** [comment]
Removed the LU/LG from the headings. Using them in the content.

**Comment by mareekuh** [comment]
@Kaiqb - for some reason I cannot view the updated github page (404) - is it posted locally or in a special build?
