### ISSUE TITLE
Bot name issues in creating a new bot

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1445]
## Version
master

## Describe the bug
Bot Name could not be show up during bot creating.

Go to home page , create a new bot, 2 issues.
1. go to default myBot directory, there is no bot name show up but actually I do have bot created
![image](https://user-images.githubusercontent.com/43408889/68006461-91faf780-fcb3-11e9-8462-4619a91a8727.png)

2. check dup bot name should check for the location loaded but not "myBot"
![image](https://user-images.githubusercontent.com/43408889/68006551-ddada100-fcb3-11e9-8adb-86890cc475e8.png)

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/issues/1445
