### ISSUE TITLE
Need more improvements on UI

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#1447]
**Is your feature request related to a problem? Please describe.**

Some UI needs more guidance

**Describe the solution you'd like**

* Notify user that Branch: Switch -> Branches, Prompt for text -> Other -> Validation Rules require enter
* Max turn count should not be less than 1
* Need grammar checker for structured ones
![image](https://user-images.githubusercontent.com/2876650/68016196-02fbd880-fccf-11e9-8dc9-0c097fa4ff26.png)
* Gap should be constant distance. Now it grows as more actions:
![image](https://user-images.githubusercontent.com/2876650/68016891-781bdd80-fcd0-11e9-940c-1e9681490ba1.png)
![image](https://user-images.githubusercontent.com/2876650/68016877-6df9df00-fcd0-11e9-8b17-3ee6051af8be.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by sangwoohaan** [comment]
#1510 addresses the issue 1.
