### ISSUE TITLE
Undo action should switch the visual canvas if nodes updates to different triggers

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1451]
## Version
master

## Describe the bug
Undo action should switch the visual canvas if nodes updates to different triggers

![image](https://user-images.githubusercontent.com/43408889/68020368-3479a180-fcd9-11e9-9b08-b0922a4ffdb7.png)

Showed in above, if user cut nodes from trigger "conversationUpdates" and paste to trigger "Unknown" , then click "Undo", the nodes can be undo as expected. eg. nodes move back to "conversationUpdates" but visual canvas does not switch.

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by cwhitten** [comment]
Let's discuss this further before scheduling
