### ISSUE TITLE
Docs | concept-dialog-draft.md

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1453]
1. I think the following image is helpful to communicate what a dialog is and what elements it's made up of/related to. These are the definitions we're using in the SDK documentation. 
Reading further in the doc it looks like it actually is in there, but much later. For context I'd move it to the top, for the copy to make sense.

![adaptive-dialog-anatomy](https://user-images.githubusercontent.com/48503434/67991637-1a679280-fbf7-11e9-9b00-899dee9f4b66.png)

2. Update images - the trigger menu has different text and no longer refers to 'handle' and 'event'.

3. The create new image is out dated. The home page looks quite different now.

4. The objective of the 'Description' is to describe what the bot is doing/what it is for. moving forward we will be parsing this content to bootstrap the bot so it'd be good to start giving meaningful examples for how to use this field.

5.At this section"You can test the result by clicking the Start button on the upper corner and then click Test in Emulator. You should be able to see the following result in the emulator:"
It'd be useful to include an image of the emulator running the bot as there are now 2 big windows/apps to be managed. And... the emulator needs to be installed first.
Also - before the emulator opens, one will need to provide their LUIS Authoring/Primary key

**Comment by zxyanliu** [comment]
Hi-
Thanks for all the feedback on this topic. 
We have updated the content please see [here](https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/BFC-Docs/docs/concept-dialog.md).

**Comment by zxyanliu** [comment]
Closing since the content is updated.
