### ISSUE TITLE
Docs | docs/deploy-bot.md

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1454]
1. Replace all instances of 'Deploy' with Publish, including screenshots.
2. Make the following a clickable link, or even better, include the instructions in the current page. Follow the wizard for Deploy Bot to Azure and deploy your bot to Azure.
3. Have these steps been tested on multiple machines (incl. Macs) and with multiple user states (have/have not Azure account, etc). The instructions seem overly simple for something that requires a Dev and some.

**Comment by emgrol** [comment]
Hey @mareekuh, @zxyanliu and I have a few clarifying questions regarding your points:
1. What do you mean by "instances", the language or screenshots (or both)? And will the word _deploy_ be replaced with _publish_ in Composer in the future? I don't want to confuse users who are familiar with deployment already, and using language not used in Composer doesn't make the most sense to us. 
2. No questions, we'll add a link.
3. We haven't tested this on multiple machines nor with multiple user states. We need more content/information from the devs to write about that.

**Comment by Kaiqb** [comment]
@emgrol 
#1. She means occurrence of the word.
#3. That is testing on the product engineering side. It's not a content issue.

**Comment by zxyanliu** [comment]
The content is updated. See [here](https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/BFC-Docs/docs/deploy-bot.md). Therefore closing this issue. Thanks.
