### ISSUE TITLE
Docs | How to add a QnA Maker knowledge base to your bot

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1455]
Just making sure you all incl. @diberry and @simer99  Tulasi (not sure what her git alias is) have reviewed and approved this doc:

https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/how-to-add-qna-to-bot.md

**Comment by Kaiqb** [comment]
Done.
