### ISSUE TITLE
Docs | howto-controlling-conversation-flow.md

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1456]
Can we rename this to something that relates more to 'Condition' so that it maps to the "Condition' Action item in the + menu?

(note: the option in the + menu used to be called 'flow')
https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/Ignite2019/docs/howto-controlling-conversation-flow.md

**Comment by Kaiqb** [comment]
When naming topics, we follow the scenario instead of the actual screen. So, in this case, it is about controlling conversation flow, but there are specific steps showing how one can do that in the "How-To" topic.
