### ISSUE TITLE
Docs | howto-defining-triggers.md

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1457]
@Kaiqb Please see issue 1224 for the updates to the 'add trigger' menu, which affect the images and the wording on this page.

**Comment by zxyanliu** [comment]
Hi -
Thanks for your feedback on this topic. 
We have updated the content please see [here](https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/BFC-Docs/docs/howto-defining-triggers.md).

**Comment by zxyanliu** [comment]
Closing since the content on this topic has been updated.
