### ISSUE TITLE
Remove SLN file from Bot Proejct

### ISSUE THREAD

**Issue by yochay** [microsoft/BotFramework-Composer#1460]
## Version
cf7eea3 (master 11/1)

## Describe the bug
Solution file (SLN) in Bot Project is busted. Regardless it is a file that should not be part of our release

## To Reproduce
1. create a new bot
2. go to mybots/newbotfolder 
3. click on BotProject.SLN
4. see image

## Expected behavior
Open the BotProject solution pointing to the bot project file and not test. 
Regardless, if any, we shoud use the .prj file and not .sln.

## Screenshots
![image](https://user-images.githubusercontent.com/896149/68057147-4ac03700-fcb2-11e9-9c77-9450c6ac84ca.png)

**Comment by hibrenda** [comment]
remove from sprint17. once we decided how to handle it, we will add it back to sprint
