### ISSUE TITLE
Disable shapes on the design canvas

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#1474]
As a developer, during dialog construction I may wish to disable shapes (right click -> disable) to suppress execution of that shape during testing. Right now you have to delete shapes (!) and put them back afterwards.

For example, if I'm diagnosing an issue that is generated by a given shape I may wish to comment this out to continue processing past it.

**Comment by sangwoohaan** [comment]
Being addressed in https://github.com/microsoft/BotFramework-Composer/issues/1695
