### ISSUE TITLE
Provide a human readable comment/name for a shape 

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#1476]
**Is your feature request related to a problem? Please describe.**

Consider this simple set of shapes below 

![image](https://user-images.githubusercontent.com/33519520/68076107-93f2b280-fda8-11e9-98ac-51e992105cad.png)

The reasoning/logic behind a set of shapes may not be clear. There should be a way to provide a "comment" that appears instead of the Expression which is not very useful in this view. Alternatively the ability to change the title of the shape could be used for this as well.

You could perhaps have a `group` shape which you can apply a comment to and then collapse the shapes inside to improve readability.

**Comment by sangwoohaan** [comment]
We might want to revisit the design system for action nodes entirely. Sure, we can patch this up with few tweaks, but it will cause bigger problems across the board if we don't approach this holistically. I briefly talked about it with @mareekuh before as well.

**Comment by mareekuh** [comment]
Agreed - would like to have the design of the nodes be relevant to the action they represent vs the same box for all, just with color differentiation..

**Comment by mareekuh** [comment]
@sangwoohaan  - do we have an uber-issue that captures/collects all the node-redesign requests/Ideas. If so can we tag this one to it and if not, can we create one @hibrenda

**Comment by sangwoohaan** [comment]
referred in https://github.com/microsoft/BotFramework-Composer/issues/1701
