### ISSUE TITLE
Unable to disable Dialogs/Triggers

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#1481]
This could be viewed as a complication caused by [this issue](https://github.com/microsoft/botbuilder-dotnet/issues/2906) as "overriding" dialogs/triggers can cause problems however I still think it's reasonable as part of a developer/user workflow to want to disable/deactivate a certain dialog/trigger to aid with testing.

For example you may wish to disable a dialog/trigger to test a scenario (unhandled intent) or disable functionality going into a specific test envrionment.

Right now you have to delete an entire dialog/trigger and then re-create it :-(

**Describe the solution you'd like**
- An enabled/disable flag on a dialog/trigger

**Comment by sangwoohaan** [comment]
Being addressed in https://github.com/microsoft/BotFramework-Composer/issues/1695

**Comment by mareekuh** [comment]
@DesignPolice - please work with Sang on visual representation of the various types of nodes (including end-node, comment flag etc) as well as the look and feel of the nodes that are affected.
