### ISSUE TITLE
Prompt LG editor auto-correct too sensitive

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#1482]
When constructing a prompt you provide LG input into the LG pane but the auto-correct for utcnow is too aggressive. Pressing enter after typing `- Sure, let me know where you are right now` to go to the next line to provide another entry ends up with `- Sure, let me know where you are right utcNow(format?: string)`

![image](https://user-images.githubusercontent.com/33519520/68093454-9c5bf380-fe63-11e9-98bc-b50f13998281.png)

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Type `- Sure, let me know where you are right now` into the LG editor and press enter

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1504
