### ISSUE TITLE
Can't select an existing Intent when configuring Language Understanding for a new dialog

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#1483]
## Describe the bug
A set of LU intents were provided as part of the LU editor (copy/paste from an existing LU file). I then wanted to configure Language Understanding for this dialog but the editor only appears to enable me to create a new Intent not reference an existing one (#FindPointOfInterest)

![image](https://user-images.githubusercontent.com/33519520/68093591-3a9c8900-fe65-11e9-9ee4-67cdd8bf1ec0.png)

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
- Be able to reference an existing intent - ideally auto-completion/validation as well.

**Comment by cwhitten** [comment]
@darrenj you have an error in your LU syntax. This will be much more obvious when we land the LU language server for the Monaco editor.
