### ISSUE TITLE
[Managed LG] Language Server Extension + Monaco editor for LG

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1485]
**Is your feature request related to a problem? Please describe.**
We will provide LSP support for LG . This will solve several issues found for inline LG editing.

**Describe the solution you'd like**
Tech Spec
https://microsoft.sharepoint.com/:w:/t/ConversationalAI785/EXoh4n_YaTdPqnFt_8CKn58BtvAt-u-Ywaq5RlDQvqzEBQ?CID=AC09E735-48D6-4A61-A8A4-E1B7952B9F0C&wdLOR=cB6D06958-5642-4E22-8146-DAF02D4FA855

**Describe alternatives you've considered**

**Additional context**

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1504
