### ISSUE TITLE
Use SVG in Visual Editor

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#1497]
## Describe the bug
Give a clear and concise description of what the bug is.

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.

**Comment by yeze322** [comment]
@cwhitten I'm not quite sure about the context, could you help adding more info here? Thanks!

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1987
