### ISSUE TITLE
Only support westus deployment in Deployment UX

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#1500]
**Is your feature request related to a problem? Please describe.**
#1459 

**Describe the solution you'd like**
By default select region: westus in the deployment UX

**Describe alternatives you've considered**

**Additional context** 
remove this and by default select west us
![image](https://user-images.githubusercontent.com/32191031/68176723-f1614c00-ffc0-11e9-8137-96cc88fa9bed.png)

**Comment by VanyLaw** [comment]
Hi @hibrenda, I think it's a little bit similar with the concept @mareekuh suggested in [here](https://github.com/microsoft/BotFramework-Composer/issues/1295).

If we support WestUs as default and remove other options, Maybe we should use TextField instead and make it not editable. Or just simply don't show this value to user, hardcode it in code.

If we can support 3 regions below, I think it's better to keep those options, and make WestUs as default.
- (US)West US
- (Asia Pacific) Australia East
- (Europe) West Europe

**Comment by hibrenda** [comment]
@mareekuh @cwhitten  what is your thoughts ? I prefer the simple version which align with the new design.
