### ISSUE TITLE
need to take care location in bot creation 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1506]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
User could specify the bot location during the bot creation and next time the location will be loaded from recent usage. Default folder location defined in #1363. 

If user create the bot by specifying the location, and then delete such folder, user will see error shows as following. and click next, bot will be created into default folder "MyBot".
![image](https://user-images.githubusercontent.com/43408889/68209476-70c93c80-000e-11ea-9a87-c4c0d32d64bb.png)

So we need to check if recent usage is still valid ,  if folder has been moved, we should load default folder. If something wrong with default folder, at least we should let user to update the bot create location.  

Steps 
- create a new bot with valid folder
- delete folder 
- go to homepage and create a new bot again
- hit error 

## Version
master

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1548
