### ISSUE TITLE
CTA for Array UI

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1510]
Addressing https://github.com/microsoft/BotFramework-Composer/issues/1408, https://github.com/microsoft/BotFramework-Composer/issues/1306, https://github.com/microsoft/BotFramework-Composer/issues/1253

New design suggestion : 
https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=3129%3A2674

Need further review

**Comment by hibrenda** [comment]
Let's go through this in tomorrow's stands up.

**Comment by sangwoohaan** [comment]
Final design : https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=3129%3A2529

- Changed the font style of the guiding text to italic. If possible, please apply this rule to all the guiding texts on the right pane.
- I have removed the thin-gray box around the empty synonym field.
![Screen Shot 2019-11-14 at 11 40 24 AM](https://user-images.githubusercontent.com/50963385/68890382-953eac00-06d3-11ea-829e-22683268b486.png)
All the empty optional input fields would have the same box style as the normal items.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1617
