### ISSUE TITLE
CardAction does not have an evaluator

### ISSUE THREAD

**Issue by jcoenen** [microsoft/BotFramework-Composer#1513]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
When trying to create HeroCard response using example from documentation I get error `CardAction does not have an evaluator, it's not a built-in function or a customized function in expression 'CardAction('See our library', 'postBack', 'http://contoso.com/cards/all')'`

Using HeroCard example from this page https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/language-generation/docs/structured-response-template.md

![image](https://user-images.githubusercontent.com/101447/68267158-7418f400-001f-11ea-9956-10cbb15906ea.png)

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).
![image](https://user-images.githubusercontent.com/101447/68267111-492ea000-001f-11ea-89e3-4180ebd6b10f.png)

## Browser
What browser are you using?

- [ X] Chrome

## OS 
What operating system are you using?
- [X ] Windows

## To Reproduce
1.  Create a resonse with the HeroCard Example code above
2. Notice syntax error on the buttons definition

## Expected behavior
No Error and HeroCard to render with actionbuttons

## Additional Information

Here is full HeroCard Example copied off documentation

[HeroCard
    title = BotFramework Hero Card
    subtitle = Microsoft Bot Framework
    text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.
    image = https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
    buttons = {CardAction('Show more cards')} | {CardAction('See our library', 'postBack', 'http://contoso.com/cards/all')}
]

**Comment by yochay** [comment]
Hello @jcoenen . Thank you for the issue and love the fact you are trying the Composer Public Preview.  Feedback is always welcome. 

Must be a doc issue. Try the following and use CardActionTemplate. 
```
buttons = {cardActionTemplate('imBack', 'Show more cards', 'Show more cards')}
```
It works with bot imBack and postBack.

Also, try and open a the Card example, it includes few HearCarads including referencing bot memory and postBack/ imBack options.

Copied from https://github.com/microsoft/BotFramework-Composer/blob/stable/Composer/packages/server/assets/projects/RespondingWithCardsSample/ComposerDialogs/common/common.lg

here is an example:
```
[HeroCard
    title = BotFramework Hero Card
    subtitle = Microsoft Bot Framework
    text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.
    image = https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
    buttons = {cardActionTemplate('imBack', 'Show more cards', 'Show more cards')}
]
```
FYI @vishwacsena and @Kaiqb  for LG docs issues.

**Comment by jcoenen** [comment]
Thank yochay.   I tried your example with the cardActionTemplate but still get a similar error

![image](https://user-images.githubusercontent.com/101447/68296799-700ec580-0063-11ea-9fc8-2a6fe903dc7d.png)

**Comment by kenakamu** [comment]
you need to add cardActionTemplate to common as you reference it in buttons.
# cardActionTemplate(type, title, value)
[CardAction
    Type = ${if(type == null, 'imBack', type)}
    Title = ${title}
    Value = ${value}
    Text = ${title}
]
