### ISSUE TITLE
Decouple BotManager and BotRuntime

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#1516]
Currently local bot runtime and bot manager are tightly coupled, Bot manager is another endpoint in bot runtime which accepts a post request from composer. The payload contains all the bot resource files, Composer saves it at a local tmp folder and Reload that new bot. Please refer to this doc to see more details. [How to connect to BotRuntime](https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/authorize?client_id=00000003-0000-0ff1-ce00-000000000000&response_mode=form_post&protectedtoken=true&response_type=code+id_token&resource=00000003-0000-0ff1-ce00-000000000000&scope=openid&nonce=0CD6B065DBAFF6E489BA9BBCBD280900EDE1C12651E284BB-C41EDB244F7BA5DA7CD0B8F7EB84E60BD74C29F0CAACB4B42F152E3907EA16A4&redirect_uri=https%3a%2f%2fmicrosoftapc-my.sharepoint.com%2f_forms%2fdefault.aspx&wsucxt=1&cobrandid=11bd8083-87e0-41b5-bb78-0bc43c8a8e8a&client-request-id=5426159f-b0fe-0000-35e7-c040dafde5d9&sso_nonce=AQABAAAAAACQN9QBRU3jT6bcBQLZNUj7Xq13Wq2Nbq1ct7KHsi8xPSOyG0HZb7UqAAaR_CYEHPJqXCFqUpcDBuZNRmbsBV9VJO8KRBh116AXZd5w1wjb7yAA&mscrid=5426159f-b0fe-0000-35e7-c040dafde5d9)

#483 is one issue which is caused by the current mechanisim.

We want to decouple the BotManager and BotRuntime and make BotManager a built in component in Composer. 

## Design Principles
- Bot runtime should be a SDK bot template, which is deployable and runnable and independent which Composer.
- Composer should start a bot by 1. copy the bot assets to ComposerDialogs folder. 2. just run a start script.

### Design Doc
https://microsoft.sharepoint.com/:w:/t/ConversationalAI785/ET5w2rXKpldNvddO9447K3QBH9wfwbRPJM4DIGIRSUQHKg?e=rbymdb

## BotManager
Implement BotManager within composer which have such functionalities:
- [x] Start a bot by endpoint and other parameters like secrects settings, returns a PID. needs to investigate the command line, for dotnet, dotnet clean & dotnet build & dotnet run & PID=$! should work.
- [ ] Be able to start multiple bots and maintain the status. Using different endpoint.
- [x] Stop a bot by PID. 
- [ ] Check status of a bot. (Running, NotRuning)
- [ ] List all bot status (for display)

BotManager maintains all the runtime status in Composer

| BotName | Bot Location | EndPoint | ProcessId | Type(C#,JS,Others) | Status
| - | - | - | - | - | -

## BotRuntime 
Bot Runtime should be a stand alone SDK bot template. 
BotRuntime will just follow the protocals and implemented a start script. 

## Exceptions
TBD, Need to figure out a way to catch the runtime exceptions and show that to user.

## Bot Dashboard
Add another page in composer to show an overview of the Bot Runtime Dashboard.

**Comment by cwhitten** [comment]
@luhan2017 let's discuss the technical design and how this will map to the custom schema/custom runtime approach. We _may_ not need a BotManager interface and want to understand concretely how this plays with our long term strategy.

**Comment by cwhitten** [comment]
@christopheranderson to provide some dotnet resources on process management

**Comment by hibrenda** [comment]
Decouple bot runtime item will be tracked here. so linked #883 #885 issues to this as well

**Comment by boydc2014** [comment]
Follow up with today's discussion, here is the previous issues
* More info in this PR https://github.com/microsoft/BotFramework-Composer/pull/47 
* The issue in DotNet core https://github.com/dotnet/cli/issues/7426

**Comment by luhan2017** [comment]
> Follow up with today's discussion, here is the previous issues
> 
> More info in this PR #47
> The issue in DotNet core dotnet/cli#7426

@boydc2014 , I am confused, sees the PR #47 already fixed the process can't be stopped issue. So we can just start and stop a bot by the mechanism in that PR, is this correct?

**Comment by hibrenda** [comment]
@sangwoohaan  need your suggestion from UX experience . Attached the spec as below.
https://microsoft.sharepoint.com/:w:/t/ConversationalAI785/EfCWS6gMy_NEpOm8UAiQp3sB_1aEB-zH1Dz2MbFElzmasg?e=1Ln8BI
