### ISSUE TITLE
Create new dialog - should let me start with an example

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1523]
When creating a new dialog, we currently show an empty dialog with 2 fields. We no longer allow people to start the dialog with a sample. Can we show the 'create new' for create new dialog.
<img width="835" alt="Screen Shot 2019-11-06 at 5 06 17 PM" src="https://user-images.githubusercontent.com/48503434/68351381-2a301c80-00b8-11ea-88c3-4b7a42400a5f.png">

**Comment by cwhitten** [comment]
We want to evaluate this scenario in the effort to create a Asset Library where designers can selectively pull-in Dialog, LG, & LU into their workflow.

**Comment by cwhitten** [comment]
Closing as a duplicate
