### ISSUE TITLE
Unable to install the dependant packages

### ISSUE THREAD

**Issue by RamPrasadMeenavalli** [microsoft/BotFramework-Composer#1525]
I am trying to setup the Bot Composer by following the instructions here - https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/setup-yarn.md

Below are the steps I followed
``
git clone https://github.com/microsoft/BotFramework-Composer.git
``
``
cd Composer 
``
``
yarn install
``

![image](https://user-images.githubusercontent.com/30853327/68357747-4e354180-013c-11ea-8b70-b956c5c17733.png)

Its failing to fetch the packages
error An unexpected error occurred: "https://botbuilder.myget.org/F/botbuilder-declarative/npm/lodash.get/-/lodash.get-4.4.2.tgz: Request failed \"401 Unauthorized\"".

Are these packages supposed to be available publicly?

**Comment by jpd21122012** [comment]
I have the same issue

**Comment by cwhitten** [comment]
Hi @RamPrasadMeenavalli & @jpd21122012, thank you for the issue.

We discovered that this feed was briefly made Private by accident. Sorry! It should be public again. Can you try again and let us know if this fixes your issue?

**Comment by jpd21122012** [comment]
@RamPrasadMeenavalli Thanks for the response, I've tried again the yarn install command, but another error is shown:

https://botbuilder.myget.org/F/botbuilder-declarative/npm/botbuilder-expression-parser/-/botbuilder-expression-parser-4.5.9.tgz: Request failed 404 Not Found

**Comment by cwhitten** [comment]
Ah, shoot. Give us a little time to audit all of the myget feeds we use.

**Comment by cwhitten** [comment]
Hello again @RamPrasadMeenavalli & @jpd21122012 , this should now be addressed via #1527. We've pushed his commit into both master & stable branches. Please try again and let us know if you're still experiencing issues.

**Comment by RamPrasadMeenavalli** [comment]
Thank you @cwhitten ,
Its working now. I am able to build and run the composer.

We were working on a similar solution at our company. Cant wait to get my hands on this and see how we can integrate this in our solution.
