### ISSUE TITLE
404 Not Found botbuilder-lg/-/4.7.0-preview0.tgz

### ISSUE THREAD

**Issue by cheahengsoon** [microsoft/BotFramework-Composer#1526]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
Give a clear and concise description of what the bug is.
When I run the command yarn install the error shown as below:
error An unexpected error occurred: "https://botbuilder.myget.org/F/botbuilder-declarative/npm/botbuilder-lg/-/4.7.0-preview0.tgz: Request failed \"404 Not Found\"".

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).
Refer to https://github.com/microsoft/BotFramework-Composer/blob/a3172de3a3f53d4880989556ec56e5c242c6017d/docs/setup-yarn.md

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce
1.Clone 
git clone https://github.com/microsoft/BotFramework-Composer.git
2.
cd Composer 
yarn install

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.

**Comment by cwhitten** [comment]
Hello @cheahengsoon - we’re aware of this issue and actively working to address it. Thanks.

**Comment by cheahengsoon** [comment]
Thank you @cwhitten

**Comment by cwhitten** [comment]
Hello again @cheahengsoon, this should now be addressed via https://github.com/microsoft/BotFramework-Composer/pull/1527. We've pushed his commit into both `master` & `stable` branches. Please try again and let us know if you're still experiencing issues.

**Comment by cheahengsoon** [comment]
After I run the command "yarn startall", the error shown as below
<img width="567" alt="YarnStartAllfail" src="https://user-images.githubusercontent.com/2833325/68442830-35489100-020d-11ea-8461-7bbae518c6ab.png">

**Comment by cwhitten** [comment]
Hello @cheahengsoon, you are missing the dotnet cli. see https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/setup-yarn.md#set-up-bot-framework-composer-using-yarn for dependencies. Closing this for now. Open a new issue if you continue to have trouble.
