### ISSUE TITLE
QnA Maker integration - Composer settings to written to appsettings.json

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#1538]
Whenever I add the QnA Maker KB details to the Composer's settings in the UI, those values are not written to the appsettings.json of my bot and therefore, the QnA Maker is not reachable and I get "Object not set to instance of an object" as a bot's reply in the emulator after trying to query QnA Maker.

However, if I insert the KBid, Key and Host directly into the "Connect to QnA Knowledgebase" in the dialog, this is working...

This is the content of my bot's appsettings.json after Restarting from Composer:

```
{
  "microsoftAppId": "",
  "bot": "ComposerDialogs",
  "cosmosDb": {
    "authKey": "",
    "collectionId": "botstate-collection",
    "cosmosDBEndpoint": "",
    "databaseId": "botstate-db"
  },
  "applicationInsights": {
    "InstrumentationKey": ""
  },
  "blobStorage": {
    "connectionString": "",
    "container": "transcripts"
  }
}
```

## Version
Application SHA - test

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
@stephanbisser are you connecting to the bot once you've deployed, or is the bot running locally?

**Comment by hibrenda** [comment]
QnA maker settings are correctly set into appsettings but the endpoint key does not handle correctly.

**Comment by VanyLaw** [comment]
@hibrenda  It's because the botproject(runtime) read qna.endpointkey from disk before. Now, we need to send this from composer server to botproject(runtime).

**Comment by stephanbisser** [comment]
@cwhitten I connect to my local running bot as I have not deployed it yet...

**Comment by cwhitten** [comment]
Hi @stephanbisser, his should be addressed in the `master` branch via https://github.com/microsoft/BotFramework-Composer/pull/1571

**Comment by stephanbisser** [comment]
Thanks a lot @cwhitten working now!
