### ISSUE TITLE
cannot start bot - property 'name' undefined

### ISSUE THREAD

**Issue by michalmar** [microsoft/BotFramework-Composer#1541]
I followed instruction and have upgraded node, installed yarn and build the application. But when I try to create bot and then test/run (just a simple Echo Bot from template) - I am getting:

**Sorry, something went wrong with connecting bot runtime.**
Cannot read property 'name' of undefined.

## Version
Release: Preview 1.0
Application SHA: test
SDK runtime packages: 4.6.0-preview2

## Browser
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ x] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce
i folowed https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial-create-echobot.md

## Screenshots
![image](https://user-images.githubusercontent.com/16072588/68501444-6f8e4e80-025e-11ea-9c45-b67525198343.png)

**Comment by cheahengsoon** [comment]
after I Test in Emulator, the Bot does not work well for Echo Bot. 
The error is shown below.
![ErrorEcho](https://user-images.githubusercontent.com/2833325/68527161-ebe86680-031e-11ea-8704-cbd5f4cbb992.png)

**Comment by hibrenda** [comment]
You may hit #1535 and we've already merged the fix into master . This will sync with stable branch soon.

**Comment by michalmar** [comment]
Ok, and is there a workaround? (Or how to bot start from scratch?

Michal

**Comment by cheahengsoon** [comment]
@michalmar  I think still not fixed.

**Comment by christopheranderson** [comment]
Work around is to checkout the master branch and use that until the fix lands in stable.

**Comment by cheahengsoon** [comment]
This case can closed, I had test with the latest update.
