### ISSUE TITLE
Can't build project with yarn

### ISSUE THREAD

**Issue by owususamuel** [microsoft/BotFramework-Composer#1545]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
Following the installation steps to get the project to run locally. I have gotten to step 3 `$ yarn build` but it doesn't work.

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.
![Annotation 2019-11-10 124804](https://user-images.githubusercontent.com/14825172/68544207-a37d8700-03b8-11ea-9228-ca77cbde1c81.png)

**Comment by Dan-Newton** [comment]
Looks like you might need to set the directory as "D:\\developx\opensource\\BotFramework-Composer\Composer"

e.g. `cd D:\\developx\opensource\\BotFramework-Composer\Composer` or `pushd D:\\developx\opensource\\BotFramework-Composer\Composer` I use the pushd example as cd wasn't working for me.

**Comment by owususamuel** [comment]
Thanks. It worked
