### ISSUE TITLE
OAuth sample for Composer

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/BotFramework-Composer#1551]
For the docs, we need an auth sample. Here is the [work item](https://fuselabs.visualstudio.com/BFDocs/_workitems/edit/37536) tracking the doc work.

**Comment by cwhitten** [comment]
@Kaiqb We have an oAuth doc, but the visuals need to be updated. Can you take https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/how_to_use_oauth.md?

**Comment by Kaiqb** [comment]
We've added a topic on auth in the R7 release.
