### ISSUE TITLE
Visuals | Update color for 'checked' item in Welcome 'menu/wizard'

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1554]
Please take a look at the green currently used to indicate that a step in the Onboarding Flow was completed. The green probably worked ok when the dialog was blue/cyan but does not look as elegant now that we have deep purple as a color.

**Comment by sangwoohaan** [comment]
Also, the arrows should face outwards 
<img width="282" alt="Screen Shot 2019-11-11 at 4 35 04 PM" src="https://user-images.githubusercontent.com/50963385/68631983-bfa92300-04a1-11ea-8aea-ef006de7607c.png">

**Comment by DesignPolice** [comment]
I have addressed the colors and icon change -

Check marks will change to #0078D4 Blue
Circle Arrows will be #656565 Gray

the icon change to Pinch Out F4D7. (images attached) 

https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=3353%3A967

![Screen Shot 2019-11-12 at 10 02 32 AM](https://user-images.githubusercontent.com/45223620/68698006-d5b3f380-0534-11ea-8f1d-ca5cdaa63487.png)
![Screen Shot 2019-11-12 at 10 10 17 AM](https://user-images.githubusercontent.com/45223620/68698011-d8164d80-0534-11ea-8311-048b4144d948.png)

@tdurnford @cwhitten
