### ISSUE TITLE
investigate running e2e tests using the cypress runner

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#1559]
Cypress hosts a service which will execute our e2e tests in parallel. It's free for open source projects so I think it's worth looking into in hopes of 1. speeding the builds up. 2. gaining stability and trust in our e2e suite.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1602
