### ISSUE TITLE
Error: Could not find resource 'Main.lu.dialog'

### ISSUE THREAD

**Issue by WTobor** [microsoft/BotFramework-Composer#1569]
## Version
branch `stable`, commit a4a2697

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Generate new test bot from template ToDoLuis
2. Open .sln in Visual Studio 2019
3. Start bot
4. Write to bot in Emulator

## Expected behavior
Bot responds

## Current behavior
There is an error in `LoadRootDialogAsync()`, "Could not find resource 'Main.lu.dialog'
Parameter name: Main.lu.dialog"

## Screenshots
![image](https://user-images.githubusercontent.com/22730914/68762512-98279700-0616-11ea-8e71-63c78f36d9c5.png)

**Comment by fabioparra** [comment]
I am also having this problem..

**Comment by a-b-r-o-w-n** [comment]
@WTobor @fabioparra Thanks for reporting the issue. 

For clarification, are you all starting the bot from Visual Studio? The `generated` folder in @fabioparra ComposerDialogs is empty. These files get generated when starting your bot from within Composer and are required for your bot to work properly. 

Specifically, a file named `Main.lu.dialog` gets created which the bot runtime uses which holds the information about how to connect to the Luis service.

**Comment by WTobor** [comment]
Yes, I am starting the bot from Visual Studio. As I can see, I don't have the `generated` folder in my bot app.
![image](https://user-images.githubusercontent.com/22730914/68791063-d3db5480-0648-11ea-8f0f-8acfe829c8de.png)
I did not modify the code and folder structure :(

**Comment by a-b-r-o-w-n** [comment]
Thanks @WTobor .

The bot runtime that is generated when creating a bot through Composer is meant to enable you to deploy to Azure. However, for now, running your bot locally requires using Composer. 

I hope this helps.

**Comment by WTobor** [comment]
Thank you for your answer. When will it be possible to launch the bot in Visual Studio?
