### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#1570]
I always get this error message when I try to restart the bot:

> Sorry, something went wrong with connecting bot runtime
> 
> Cannot read property 'name' of undefined

I think it has to do something with the LUIS settings in the bot, even though I don't use any of the Recognizers here. But if I enter any name into the LUIS name section of the settings I can restart the bot once until I edit something in the dialogs, then I have to re-change the settings to some different value.

## Version
test

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
@hibrenda can you try and reproduce this for us?

**Comment by stephanbisser** [comment]
Happy to jump on a call if you need to get details or see what actually happens on my machine...

**Comment by a-b-r-o-w-n** [comment]
@stephanbisser We have had similar reports of this in the past (#1542 & #1535). We just merged in a fix to our stable branch yesterday. Are you up-to-date?

**Comment by hibrenda** [comment]
@stephanbisser I've tried the latest stable branch and sounds like this issue has been fixed. Please let me know if you hit any issues. Thanks

**Comment by stephanbisser** [comment]
@a-b-r-o-w-n not updated recently. btw. is there any documentation on how to best upgrade composer? if there is I would try the steps and upgrade/update and check if that's working then

**Comment by a-b-r-o-w-n** [comment]
@stephanbisser There is not any documentation about updating Composer yet. 

If you just cloned this repo, you will need to run `git fetch && git reset --hard origin/stable`. (Assuming your remote is called origin).

If you are working from a fork, you need to add a remote pointing to this repo and run the above command with the remote name.

**Comment by stephanbisser** [comment]
Does that remove my already created bots from the filesystem as well?

**Comment by a-b-r-o-w-n** [comment]
If they are in the MyBots folder, then they will not be removed -- everything in that folder is ignored by git. If they are stored outside of the repo folder, then you don't have to worry about it.

**Comment by stephanbisser** [comment]
Great thx for clarification!
