### ISSUE TITLE
Missing lubuild package - no error message during deployment

### ISSUE THREAD

**Issue by WTobor** [microsoft/BotFramework-Composer#1572]
## Version
branch `stable`, commit a4a2697

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Generate bot from template ToDoLuis
2. Run `pwsh ./Scripts/create.ps1` with valid parameters (status: Done)
3. Run `pwsh ./Scripts/deploy.ps1` with valid parameters and no `lubuild` installation

##Current behaviour
There is no message about success or error
![image](https://user-images.githubusercontent.com/22730914/68775364-a2ee2600-062e-11ea-9b94-4c6e483cb9ec.png)

## Expected behavior
There should be an error message (the same as after rerunning deploy script)
![image](https://user-images.githubusercontent.com/22730914/68775524-eba5df00-062e-11ea-9654-8c81ec09ee65.png)

**Comment by cwhitten** [comment]
@luhan2017 can we add some better error logging in the powershell script?

**Comment by luhan2017** [comment]
@WTobor , I can't repro you error, I can always get the error message as expected. Can you give us more detailed description. It seems you just got stucked when you run deploy.ps1 for the first time?

**Comment by WTobor** [comment]
Yes, I have got no error message, when I was running `deploy.ps1` for the first time (without `lubuild` installation). Of course now everything works (because I have installed `lubuild`).

**Comment by Stevenic** [comment]
`lubuild` has been deprecated. Please use `bf cli` tool instead:

https://github.com/microsoft/botframework-cli
