### ISSUE TITLE
Error from Emulator - mismatched input ‘help’ expecting <EOF>

### ISSUE THREAD

**Issue by huislaw** [microsoft/BotFramework-Composer#1576]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
I was following the doc at https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial/bot-tutorial-add-help.md.

After added the help, the emulator is showing error:
[Error] line 31:0 - line 31:98: source: common.lg. error message: mismatched input ‘help’ expecting <EOF> in template reference from help

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).
Application SHA: test
SDK runtime packages: 4.6.0-preview2

## Browser
Chrome

## OS 
Windows 10

## To Reproduce
I was following the doc at https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial/bot-tutorial-add-help.md.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.
https://ibb.co/GFv0mJc

**Comment by hibrenda** [comment]
@huislaw Could you confirm the send a Response editor with following format ?
![image](https://user-images.githubusercontent.com/43408889/68836906-5bcb6800-06f6-11ea-9674-34c779d14668.png)

**Comment by huislaw** [comment]
@hibrenda 
Here it is:
![composer](https://user-images.githubusercontent.com/2201663/68841713-0eec8f00-0700-11ea-8daf-0a552ce9efb2.png)

**Comment by hibrenda** [comment]
@huislaw If you don't mind, would you mind to share your common.lg  file?

**Comment by huislaw** [comment]
> @huislaw If you don't mind, would you mind to share your common.lg file?

Sure:
[common.zip](https://github.com/microsoft/BotFramework-Composer/files/3845561/common.zip)

**Comment by hibrenda** [comment]
@huislaw  I guess you'd like to input a string for following sentences : 
- [from help] I am a weather bot! I can tell you the current weather conditions. Just say WEATHER.
But this will invoke a build-in function and the grammar is not correct. so this introduced the error.

If you want to input a string, please   use escape to avoid the build-in function
- \[from help] I am a weather bot! I can tell you the current weather conditions. Just say WEATHER.

Let me know if this worked or not.

**Comment by benbrown** [comment]
The escaping behavior is demonstrated here in the LG docs:
https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/language-generation/docs/lg-file-format.md#escape-character

**Comment by huislaw** [comment]
> @huislaw I guess you'd like to input a string for following sentences :
> 
> ```
> - [from help] I am a weather bot! I can tell you the current weather conditions. Just say WEATHER.
> But this will invoke a build-in function and the grammar is not correct. so this introduced the error.
> 
> If you want to input a string, please   use escape to avoid the invocation of build-in function. To avoid such confusion, we are working on this fix. it will be available soon. 
> - \[from help] I am a weather bot! I can tell you the current weather conditions. Just say WEATHER.
> ```
> 
> Let me know if this worked or not.

Thanks, no more error after escaping the [ and ].
