### ISSUE TITLE
Disable stylecop rule SA1412StoreFilesAsUtf8BOM

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#1577]
When I try to deploy a bot, it pop up an error that the build is failure and dll is not exist.

This is because when we copy the botProject template to the new bot folder, the files are saved as UTF8 defaultly and the stylecop rule requires the file format to be UTF8 with BOM.

![image](https://user-images.githubusercontent.com/32191031/68830614-17849b80-06e7-11ea-8496-b90c935f1ccb.png)

## Version
master

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Create a bot from a template
2. Run create.ps1
3. Run deply.ps1

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/issues/1577
