### ISSUE TITLE
(Echo Bot example). Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by huislaw** [microsoft/BotFramework-Composer#1588]
## Describe the bug

In another machine:
1. User start a project with Echo Bot example.
2. Click Start Bot / Restart Bot and get "Something went wrong" message.
![composer](https://user-images.githubusercontent.com/2201663/68911129-eeb7e100-078e-11ea-8128-7c28838904fe.png)

3. In Emulator, it keeps showing This is a default bot.
![emulator](https://user-images.githubusercontent.com/2201663/68911153-03947480-078f-11ea-8abc-d6984a3480c5.png)

## Version
Application SHA: test
SDK runtime packages 4.6.0-preview2

## Browser
Chrome

## OS 
Windows 10

**Comment by hibrenda** [comment]
@huislaw Could you please sync with the latest stable branch. this sounds like the dup of #1535

**Comment by huislaw** [comment]
> sync with the latest stable branch

May I know how to sync with the latest stable branch ?

**Comment by hibrenda** [comment]
git pull origin stable

**Comment by huislaw** [comment]
> git pull origin stable
After run this, the user has this error when type "yarn startall" :
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/2201663/68927926-dca46580-07c3-11ea-984f-a84276af8a0c.png)

**Comment by hibrenda** [comment]
So you have already followed the steps as below ?

![image](https://user-images.githubusercontent.com/43408889/68928717-c3041d80-07c5-11ea-9aa7-83ffdf677d0d.png)

**Comment by zxyanliu** [comment]
@huislaw I was wondering if you followed the steps of this [article](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/tutorial-create-echobot.md)?

**Comment by cwhitten** [comment]
@huislaw please follow the instructions above and let us know if you are still experiencing issues. If you are still having trouble please create a new issue.
