### ISSUE TITLE
Revisit state management topic in Visual Editor

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#1589]
## Describe the bug

Migrating to `useReducer` hook (Refactoring).

Our previous bugs like 'redraw' problem and multi-selection problem are all related to state management. As the visual editor logic become much more complicated than before, our previous solution built on top of `useContext` and `useEffect` hooks looks not efficient enough to support our future plans because it's hard to be tested and maintained.

As discussed, leveraging the `useReducer` hook which follows the redux-style state management is one of the recommended strategy for complicated React applications. We can centralized all shared states (for example `focusedId`, `selectedNodes`) into a single store and it will enable us doing further optimizations on state syncing logic with ShellApi.

This work will improve our components' code quality and benifit us on future features like debugging, drag&drop.

**Comment by yeze322** [comment]
![image](https://user-images.githubusercontent.com/8528761/68919178-0e113700-07ac-11ea-9702-9a957b8e9921.png)

**Comment by yeze322** [comment]
We had an experimental PR on that https://github.com/microsoft/BotFramework-Composer/pull/1243/files#diff-20.
It worked good but outdated. But we can have a preview on the code structure after leveraging `useReducer` and redux-style state management.

![image](https://user-images.githubusercontent.com/8528761/68919370-c808a300-07ac-11ea-8aa8-506c15f29cf3.png)

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/1745

**Comment by yeze322** [comment]
I think it's time to restart this item after we finished the schema-driven item.
In long term, we will need a better state management pattern to supoort scenarios such as 'Multi-user' & #1220 

#1745

**Comment by yeze322** [comment]
After removing `<iframe>` container, Visual Editor consumes the states in `ExtensionContext` directly. State management becomes simpler and no longer a problem.

Since we've had a good pattern, I just close this issue.
