### ISSUE TITLE
Yarn upgrade failed on "botbuilder-expression-parser@^4.5.11"

### ISSUE THREAD

**Issue by WTobor** [microsoft/BotFramework-Composer#1590]
## Version
branch `master`, commit `d0ed216f`

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Run `yarn upgrade` (according to error message during build)
![image](https://user-images.githubusercontent.com/22730914/68922329-96c3af00-077b-11ea-9c03-e82cf884780e.png)

## Expected behavior
Upgrade works

## Screenshots
![image](https://user-images.githubusercontent.com/22730914/68921929-8a8b2200-077a-11ea-9c88-73bd3c73e1f2.png)

**Comment by WTobor** [comment]
So I cannot build application from the latest commit. When I move back to commit `326026e`, build works.

**Comment by hibrenda** [comment]
@WTobor  we don't support yarn upgrade. Please follow the installation instruction : yarn install -> yarn build -> yarn start

**Comment by WTobor** [comment]
Thanks for the response. Maybe consider adding this information in console output (after failed build)? ;)

**Comment by cwhitten** [comment]
We will attempt to update the text that comes out of the tooling to not confuse users - thanks for the feedback!

**Comment by Kaiqb** [comment]
Removing doc label as this doesn't seem to be a doc issue.

**Comment by hibrenda** [comment]
close this issue as it is already addressed in #1645
