### ISSUE TITLE
QnA configuration - "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by WTobor** [microsoft/BotFramework-Composer#1591]
## Version
branch `master`, commit `326026e`

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Create bot app from template "Luis & QnA"
2. Create QnA knowledgebase
3. In `Settings` add valid 
4. Update flow to use only Qna on start:
![image](https://user-images.githubusercontent.com/22730914/68922866-1aca6680-077d-11ea-8783-14421bbe6e32.png)
5. Open bot in Emulator

## Current behaviour
![image](https://user-images.githubusercontent.com/22730914/68922890-261d9200-077d-11ea-9a81-76f4ffba6886.png)

## Expected behavior
There is no error

## Additional information
There is no error after steps:
- copy qna node from `BotProject/ComposerDialog/settings/appsettings.json` to `BotProject/appsettings.json` 
- manually add missing `endpointkey` node in `qna` node

**Comment by hibrenda** [comment]
@WTobor  Composer settings will be set into BotProject/ComposerDialog/settings/appsettings.json but not  BotProject/appsettings.json . The latter one is for deployment usage. 
"endpointkey" is persist into the memory so that's why you could not see it in appsettings.json 

I followed your steps but could not reproduce the issues.  

Could you double confirm you have input everything under "qna" setting ?
![image](https://user-images.githubusercontent.com/43408889/68928477-20e43580-07c5-11ea-9d23-e8b17e17565d.png)

**Comment by WTobor** [comment]
Yes, I can confirm.

**Comment by hibrenda** [comment]
@WTobor  Updated comment to check apsettings file (see above) , by the way for your dialog step in welcome, the QnA step won't be invoked in above flow. We'd better to have tirgger intent with utterance to invoke QnA.

**Comment by VanyLaw** [comment]
Hi @WTobor I can't reproduce too. If you set those value correctly into settings, It should be persist to disk (ComposerDialog/settings/appsettings.json), and no need to manually add endpoingkey to file. Could you try again in the latest master branch?

FYI. this is the file I get in my localhost, which included endpointkey already.
![image](https://user-images.githubusercontent.com/21174180/69029153-1b7a2b80-0a0f-11ea-8ad5-df436aab88e6.png).

And the property name in settings should be the same as the value you filled in the form.
![image](https://user-images.githubusercontent.com/21174180/69028978-a6a6f180-0a0e-11ea-84b3-80d988828ff2.png)
![image](https://user-images.githubusercontent.com/21174180/69029300-7b70d200-0a0f-11ea-9a41-9a401d398fe9.png)
