### ISSUE TITLE
Can't build using npm command

### ISSUE THREAD

**Issue by surajit09** [microsoft/BotFramework-Composer#1593]
Complete the necessary portions of this template and delete the rest.

## Description
When I run the npm run build command I get the following error:
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'react-dev-utils/chalk'
## Version
Didn't find the version in the README file. I cloned the stable branch

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.

**Comment by cwhitten** [comment]
Hello @surajit09 thanks for the issue, please see https://github.com/microsoft/BotFramework-Composer#get-started for running Composer. I'll close this but please create a new issue if you are having trouble.
