### ISSUE TITLE
Echobot not able to launch the Emulator. App Crashes with exit node 1 

### ISSUE THREAD

**Issue by rahulvkalidindi** [microsoft/BotFramework-Composer#1594]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
Cannot start the echobot that is created from the template.

## Version
Application SHA
test
SDK runtime packages
4.6.0-preview2

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
Cloned the repo
Yarn install
yarn build 
yarn startall

Created an Echo Bot from the template, changed the recognizer to None. Clicked on Start Bot

On starting the Bot the following error comes up.
<img width="383" alt="Capture1" src="https://user-images.githubusercontent.com/57859904/69005974-78f47680-0942-11ea-8378-40b91f2dbfa7.PNG">

On console, the error is:
```
[start] [start:server] GET /home 304 37.316 ms - -
[start] [start:server] GET /extensionContainer.html 304 2.343 ms - -
[start] [start:server] GET /extensionContainer.html 304 0.633 ms - -
[start] [start:server] GET /api/projects/recent 304 22.954 ms - -
[start] [start:server] GET /api/assets/projectTemplates 304 39.652 ms - -
[start] [start:server] GET /api/projects/opened 200 184.061 ms - 160757
[start] [start:server] PUT /api/projects/opened 200 282.858 ms - 177850
[start] [start:server] Sun, 17 Nov 2019 09:46:22 GMT express deprecated res.send(status): Use res.sendStatus(status) instead at build\controllers\project.js:163:17
[start] [start:server] PUT /api/projects/opened/dialogs/Main 204 43.194 ms - -
[start] [start:server] GET /api/launcher/connect?botEnvironment=production 400 209.692 ms - 82
[start] [start:server] GET /api/launcher/connect?botEnvironment=production 400 137.670 ms - 82
[start] [start:server] GET /api/launcher/connect?botEnvironment=production 400 158.344 ms - 82
[runtime] npm run runtime exited with code 1
--> Sending SIGTERM to other processes..
[start] npm run start exited with code 1
error Command failed with exit code 1.

```

## Expected behavior
Should have launched the emulator and started the Bot.

## Additional context
BotFramework Emulator 4.6.0 is installed already

**Comment by rahulvkalidindi** [comment]
Keeps crashing everytime and action is performed. Even navigating to created project crashes the build.

`yarn run v1.19.1
$ concurrently --kill-others-on-fail "npm:runtime" "npm:start"
[start]
[start] > @bfc/root@ start C:\VA Code\BotFramework-Composer\Composer
[start] > cross-env NODE_ENV=production PORT=3000 concurrently --kill-others-on-fail "npm:start:server"
[start]
[runtime]
[runtime] > @bfc/root@ runtime C:\VA Code\BotFramework-Composer\Composer
[runtime] > cd ../BotProject/CSharp/ && dotnet build && dotnet run
[runtime]
[runtime] Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
[runtime] Copyright (C) Microsoft Corporation. All rights reserved.
[runtime]
[runtime] C:\Program Files\dotnet\sdk\2.1.100\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [C:\VA Code\BotFramework-Composer\BotProject\CSharp\BotProject.csproj]
[runtime] C:\Program Files\dotnet\sdk\2.1.100\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [C:\VA Code\BotFramework-Composer\BotProject\CSharp\Tests\Tests.csproj]
[runtime]
[runtime] Build FAILED.
[runtime]
[runtime] C:\Program Files\dotnet\sdk\2.1.100\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [C:\VA Code\BotFramework-Composer\BotProject\CSharp\BotProject.csproj]
[runtime] C:\Program Files\dotnet\sdk\2.1.100\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [C:\VA Code\BotFramework-Composer\BotProject\CSharp\Tests\Tests.csproj]
[runtime]     0 Warning(s)
[runtime]     2 Error(s)
[runtime]
[runtime] Time Elapsed 00:00:00.89
[runtime] npm ERR! code ELIFECYCLE
[runtime] npm ERR! errno 1
[runtime] npm ERR! @bfc/root@ runtime: `cd ../BotProject/CSharp/ && dotnet build && dotnet run`
[runtime] npm ERR! Exit status 1
[runtime] npm ERR!
[runtime] npm ERR! Failed at the @bfc/root@ runtime script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[runtime]
[runtime] ┌──────────────────────────────────────────────────────────────┐
[runtime] │                   npm update check failed                    │
[runtime] │             Try running with sudo or get access              │
[runtime] │             to the local update config store via             │
[runtime] │ sudo chown -R $USER:$(id -gn $USER) C:\Users\S934569\.config │
[runtime] └──────────────────────────────────────────────────────────────┘
[runtime]
[runtime] npm ERR! A complete log of this run can be found in:
[runtime] npm ERR!     C:\Users\S934569\AppData\Roaming\npm-cache\_logs\2019-11-17T10_17_40_539Z-debug.log
[start] [start:server]
[start] [start:server] > @bfc/root@ start:server C:\VA Code\BotFramework-Composer\Composer
[start] [start:server] > yarn workspace @bfc/server start
[start] [start:server]
$ node build/server.js
[start] [start:server]
[start] [start:server]
[start] [start:server] Composer now running at:
[start] [start:server]
[start] [start:server] http://localhost:3000
[start] [start:server]
[start] npm run start exited with code 1
[start] [start:server] GET /about 304 22.095 ms - -
[start] [start:server] GET /extensionContainer.html 304 1.424 ms - -
[start] [start:server] GET /extensionContainer.html 304 0.575 ms - -
[start] [start:server] GET /api/projects/opened 200 207.134 ms - 160795
[start] [start:server] GET /api/projects/recent 200 4.335 ms - 351
[start] [start:server] GET /api/assets/projectTemplates 304 8.038 ms - -
[start] [start:server] PUT /api/projects/opened 200 72.090 ms - 160795
[runtime] npm run runtime exited with code 1
--> Sending SIGTERM to other processes..
[start] npm run start exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by cwhitten** [comment]
@rahulvkalidindi what branch are you using? `master` or `stable` ?

**Comment by luhan2017** [comment]
"The current .NET SDK does not support targeting .NET Core 2.1. Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1."
@rahulvkalidindi , it seems like you didn't install .NET Core 2.1 in your environment, could you install that and try again?

**Comment by rahulvkalidindi** [comment]
> "The current .NET SDK does not support targeting .NET Core 2.1. Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1."
> @rahulvkalidindi , it seems like you didn't install .NET Core 2.1 in your environment, could you install that and try again?

Hi @luhan2017 - I already have dotnet version 2.1.100 version on my machine.

Is there a specific version that I need to be on? If yes, please let me know.

@cwhitten - I am on stable version right now. Cloned on 17th Nov 2019

**Comment by christopheranderson** [comment]
@rahulvkalidindi - could you please run `dotnet --info` and provide the output? That will include SDKs that are installed. It will look like this:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Team notes: We should probably add dotnet --info in the startall command for the time being.

**Comment by zxyanliu** [comment]
Hi @rahulvkalidindi 

FYI. Please make sure to meet all the prerequisites listed in the [Sep up Bot Framework Composer using Yarn](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/setup-yarn.md) article before you follow the steps instructed in the [Create an echo bot using Bot Framework Composer](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/tutorial-create-echobot.md) article. 

Thanks!

Yan

**Comment by gabog** [comment]
We think this issue has been addressed, closing it.

**Comment by narulasrinivas** [comment]
@gabog & BOT Composer Community Folks,

In the docs, it is given as **NET Core SDK 2.2** required to test your bot.

I installed **NET Core SDK 2.2**, as per documentation. But I'm getting same error as @rahulvkalidindi 

Here is my `**dotnet --info**`
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by narulasrinivas** [comment]
After digging a little bit I understood that all the relevant folders are missing for the composer to execute. In my case, **BotProject**  folder was missing from main folder.

Initially I took only Composer folder and above issue occurred, once I added all folders from extracted zip. it started working.
