### ISSUE TITLE
UX Design for luis publish error message when user start/restart the bot

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1597]
**Is your feature request related to a problem? Please describe.**
#1573  

**Describe the solution you'd like**
As a composer user, when I start or restart the bot, it will go through the luis publish flow.
If luis publish fail, user would like to get more detail info instead of just the sentence with "Error publish to luis". So user will know how they will move forward.

For composer server side, we can add "console.err()"  to print the error output in console server. How end user could understand what happens , we need to address this from the client.

**Describe alternatives you've considered**

**Additional context**

**Comment by mareekuh** [comment]
Show the dialog in which the user needs to fill out the LUIS information, and mark the field with the error. Use standard Fabric component & look and feel.
<img width="409" alt="Screen Shot 2020-01-25 at 6 55 58 PM" src="https://user-images.githubusercontent.com/48503434/73129961-5d41c800-3fa4-11ea-82c7-a7dbf500d613.png">

Back to you, @hibrenda 
FYI @cwhitten

**Comment by hibrenda** [comment]
lubuild errors have been pop up after click "start bot" button if user hit luis failure. so close it.
