### ISSUE TITLE
[Inline LU] Add ability to edit intent trigger utterances in form

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1598]
**Describe the solution you'd like**
The form editor for Intent Trigger should expose an inline LU editor so that users can modify intent trigger phrases inline.

https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19-?node-id=1600%3A9

Things to consider:
* update lu intent name when user edits trigger name

Depends on #1641

**Comment by a-b-r-o-w-n** [comment]
Moving out of R7 into R8.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1786
