### ISSUE TITLE
unable to enter custom name for new bot

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#1603]
## Describe the bug
#1583 introduced a bug in which a user is unable to type a custom name for a new bot because the input field cannot be cleared. It is always reset to the 'default' name.

## Version
21516678c2

**Comment by a-b-r-o-w-n** [comment]
Side note --  even though e2e tests are not failing the build, it is up to the developer to make sure new code does not break existing tests.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1668
