### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by renoleite** [microsoft/BotFramework-Composer#1611]
I cloned the latest version to install on a different computer and after running yarn on the Composer folder, the dependencies install fails as below:

PS C:\temp\BotFramework-Composer\Composer> yarn
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://botbuilder.myget.org/F/botbuilder-declarative/npm/lubuild/-/1.0.3-preview.tgz: Integrity check failed for "lubuild" (computed integrity doesn't match our records, got "sha512-PHBy7+Szk2+6ZpKP4p++YEgi7HKu5EHBKaXhJ3yWEBraD2FZbol68it2F9VXj9ahSv/+KlHcEFzl77jndtWT0Q== sha1-DT/hG3IjHhIb8llqw4l46BvpkNg=")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

With that I can't finish setup and preview the actual tool. Appreciate guidance on how to fix that.

**Comment by cwhitten** [comment]
hi @renoleite - we'll have `stable` updated soon that fixes this. we'll comment on this issue when that happens. thanks!

**Comment by a-b-r-o-w-n** [comment]
@renoleite we have released a new version of the stable branch which addresses this issue.

**Comment by renoleite** [comment]
> @renoleite we have released a new version of the stable branch which addresses this issue.

Worked perfectly now :) Thanks a lot.
