### ISSUE TITLE
Newly created bot not showing on list of recent bots

### ISSUE THREAD

**Issue by yochay** [microsoft/BotFramework-Composer#1622]
## Describe the bug
Created a new bot and it doesnt show on the home screen recent bots 

## Version
Application SHA
e47d8ecc
SDK runtime packages
4.6.0-preview2

## Browser
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS 

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. create a new bot
2. back to home page  - bot is not listed on recent 

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
![image](https://user-images.githubusercontent.com/896149/69283701-bf93dc00-0ba1-11ea-8d91-e00eed81bb90.png)

**Comment by liweitian** [comment]
Cannot reproduce. Probably it is solved by recent default folder pr.
