### ISSUE TITLE
[Linting and Validation] Align with the new design in form for inline error display

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1623]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=3278%3A26678

**Describe alternatives you've considered**

**Additional context**

**Comment by a-b-r-o-w-n** [comment]
The remainder of this work (surfacing ALL errors in the form) will be tracked with #1699.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1683
