### ISSUE TITLE
Add more UT to improve test coverage

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1625]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Please reference : https://coveralls.io/github/microsoft/BotFramework-Composer?branch=master

**Describe alternatives you've considered**

**Additional context**

**Comment by cwhitten** [comment]
Client:

Composer/packages/client/src/pages/home/index.tsx
Composer/packages/client/src/pages/design/index.tsx
Composer/packages/client/src/pages/language-understanding/index.js (convert to TypeScript)
Composer/packages/client/src/pages/language-understanding/table-view.js (convert to TypeScript)
Composer/packages/client/src/pages/language-generation/table-view.tsx
Composer/packages/client/src/ShellApi.ts

Server:

Composer/packages/server/src/controllers/project.ts
