### ISSUE TITLE
Input anything in Prompts in Inputs will got an error

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#1626]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
Input anything in the Prompts in InputDialog will got an error, and the content will be lost after you refresh.

## Version
master

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. new a bot from any template
2. Click on add a TextInput
3. Input whatever in Prompt

## Screenshots
![image](https://user-images.githubusercontent.com/32191031/69319837-ed991f00-0c7a-11ea-83b2-8f7bfb8ab630.png)

**Comment by Kaiqb** [comment]
I am also having this issue on Windows using Edge.

**Comment by luhan2017** [comment]
Yes, I tried again locally, this issue happens in Edge only.

**Comment by zhixzhan** [comment]
This bug come from old version LG Parser, used an Edge unsupported `String.trimStart()` methods.
will flow up with LG team.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/issues/1626
