### ISSUE TITLE
Malformed json in Interruption template GetProfile.dialog

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#1627]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
Create from template doesn't work, crated empty bot. Seeing error when adding a new dialog shows an error 

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.
![image](https://user-images.githubusercontent.com/32191031/69321676-7f565b80-0c7e-11ea-846c-f1009ecf16d5.png)

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1624
