### ISSUE TITLE
error info has not been saved into LG (missed auto-completion part)

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1628]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
If user input error info in LG with auto-completion, the auto suggested part will not be saved into LG file and only typed words have been saved . Redo this again, it just append the typed words but not update it with user inputs. (see attached )

## Version
Master

## Browser
What browser are you using?

- [X ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## Expected behavior
error info should be saved 

## Screenshots
https://recordit.co/W5eT57kUS8

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1504
