### ISSUE TITLE
Basic Auth for "Send an HTTP Request"

### ISSUE THREAD

**Issue by mlipinski** [microsoft/BotFramework-Composer#1629]
**Is your feature request related to a problem? Please describe.**
I am trying to make a HTTP request that needs to leverage the basic auth and not able to find the area to enter in the credentials for basic auth within Composer. 

**Describe the solution you'd like**
I would like an extra area on the HTTP request which allows for Basic Authentication.

**Describe alternatives you've considered**
There are no alternatives, I am unable to use the http request to my api url which requires the basic auth.

**Additional context**
HTTP requests should provide a basic auth when accessing a url api call.

**Comment by DingmaomaoBJTU** [comment]
![image](https://user-images.githubusercontent.com/16643193/69394751-e8d67880-0d17-11ea-8ef8-6227bb7dbea0.png)

**Comment by hibrenda** [comment]
@mlipinski  let us know if you need more info.

**Comment by zxyanliu** [comment]
Hi @mlipinski 
FYI. We are currently working on a doc for the "Sending an HTTP Request using Auth" topic. The content will be available soon. 

Yan

**Comment by mlipinski** [comment]
Just to make sure I understand, I should be using the headers to somehow pass basic auth?  An Example would be great thanks.

**Comment by cwhitten** [comment]
@mlipinski Essentially, yes. Most basic authentication scenarios will require the caller to provide a computed hash using a shared secret. These requirements are driven by the API you are communicating with. The HTTPAction can accept this hash as a query string parameter, or as a value in an `Authorization` header. A example of a header definition using HTTPAction would be:

```json
{
  "Authorization": "Basic ${YOUR_COMPUTED_HASH}"
}
```

**Comment by cwhitten** [comment]
Closing this for now.  Keep an eye out for the HTTP Auth document that @zxyanliu mentioned.

**Comment by sahil-41** [comment]
Hi @zxyanliu can you please send me the link of a doc for Sending an HTTP Request using Auth. So what I was trying is to call service now api’s through bot framework so I need to know how can I  give my username and password as basic auth in headers in bot framework
