### ISSUE TITLE
Writing invalid lg inline breaks the all-up view UX

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#1635]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
lg all-up view can get in a broken state

## Version
Application SHA 2f96b521
SDK runtime packages 4.6.0-preview2

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce
1. https://share.getcloudapp.com/4gu7oDqQ

## Expected behavior
The all-up view should load successfully

**Comment by xieofxie** [comment]
It becomes worse in current [master](https://github.com/microsoft/BotFramework-Composer/commit/32ce9096fac98f4efafbe482f1ccbd0d40ee60e3).. Any lg will break it

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1504
