### ISSUE TITLE
Documentation: example of how to deploy Composer as an Azure Web App

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#1636]
Or some Azure cloud equivalent.  Azure Container Instance? Azure Files?

https://teams.microsoft.com/l/message/19:ca6b46b734d04d0b8763d6d086e532b0@thread.skype/1574083536814?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=76218e2a-691b-4d46-8c7a-19ca8c03e0c8&parentMessageId=1574083536814&teamName=Bot%20Framework%20Composer%20Private%20Preview&channelName=General&createdTime=1574083536814

**Comment by Kaiqb** [comment]
@cwhitten - the link above doesn't open anything. Do you have additional information on what you'd like covered?
