### ISSUE TITLE
LUIS and Dialog telemetry in Sample Bot Project

### ISSUE THREAD

**Issue by Ganesamurthy** [microsoft/BotFramework-Composer#1639]
**Is your feature request related to a problem? Please describe.**
Telemetry support for Bot created using Composer UI.

**Describe the solution you'd like**
Application insights telemetry support for Recognizer(LUIS) and Dialogs in Bot project

**Additional context**
This will help in monitoring scenarios and for utilizing Power BI report template in Virtual assistant template(https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/).

**Comment by christopheranderson** [comment]
Hey @Ganesamurthy 

This is a really good idea. We definitely want to light all of that up in the bot project. You can do it today, of course, since you own that code that gets created.

We'll address this in a future milestone.

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/2471
