### ISSUE TITLE
Create Azure resources fails - Code Unauthorized

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#1642]
## Describe the bug
When running the command for creating the Azure resources I get this error within my command line:

$ pwsh ./Scripts/create.ps1 -name QnA-Express-SBI -environment QnA-Express-SBI-Test -location WestUS -appPassword 'ThisIsMySecret9!' -luisAuthoringKey eea97ba4823748f683cff09a40a8664d
> Creating resource group ...
> Validating Azure deployment ...
> Deploying Azure services (this could take a while)...
Deployment failed. Correlation ID: 4539b0f7-8a33-4cf6-8627-35ac7b65c6c3. {
  "Code": "Unauthorized",
  "Message": "The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.",
  "Target": null,
  "Details": [
    {
      "Message": "The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option."
    },
    {
      "Code": "Unauthorized"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "52020",
        "MessageTemplate": "The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option.",
        "Parameters": [
          "default"
        ],
        "Code": "Unauthorized",
        "Message": "The scale operation is not allowed for this subscription in this region. Try selecting different region or scale option."
      }
    }
  ],
  "Innererror": null
}
! Deployment failed. Review the log for more information.

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

test

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by luhan2017** [comment]
@stephanbisser , could you check the sku settings in this file(https://github.com/microsoft/BotFramework-Composer/blob/stable/BotProject/Templates/CSharp/DeploymentTemplates/template-with-preexisting-rg.json) to see whether it is aligned with you subscription.

For example:
botSku: F0
newAppServicePlanSku: S1
luisServiceRunTimeSku: S0

**Comment by stephanbisser** [comment]
These are my settings:

```
  "name": {
            "type": "string",
            "defaultValue": "[resourceGroup().name]"
        },
        "appId": {
            "type": "string",
            "metadata": {
                "description": "Active Directory App ID, set as MicrosoftAppId in the Web App's Application Settings."
            }
        },
        "appSecret": {
            "type": "string",
            "metadata": {
                "description": "Active Directory App Password, set as MicrosoftAppPassword in the Web App's Application Settings. Defaults to \"\"."
            }
        },
        "useCosmosDb": {
            "type": "bool",
            "defaultValue": true
        },
        "shouldCreateAuthoringResource": {
            "type": "bool",
            "defaultValue": true
        },
        "cosmosDbName": {
            "type": "string",
            "defaultValue": "[resourceGroup().name]"
        },
        "botId": {
            "type": "string",
            "metadata": {
                "description": "The globally unique and immutable bot ID. Also used to configure the displayName of the bot, which is mutable."
            }
        },
        "botSku": {
            "defaultValue": "F0",
            "type": "string",
            "metadata": {
                "description": "The pricing tier of the Bot Service Registration. Acceptable values are F0 and S1."
            }
        },
        "luisAuthoringKey": {
            "type": "string",
            "defaultValue": ""
        },
        "newAppServicePlanName": {
            "type": "string",
            "defaultValue": "[resourceGroup().name]",
            "metadata": {
                "description": "The name of the new App Service Plan."
            }
        },
        "newAppServicePlanSku": {
            "type": "object",
            "defaultValue": {
                "name": "S1",
                "tier": "Standard",
                "size": "S1",
                "family": "S",
                "capacity": 1
            },
            "metadata": {
                "description": "The SKU of the App Service Plan. Defaults to Standard values."
            }
        },
        "appServicePlanLocation": {
            "type": "string",
            "metadata": {
                "description": "The location of the App Service Plan."
            }
        },
        "existingAppServicePlan": {
            "type": "string",
            "defaultValue": "",
            "metadata": {
                "description": "Name of the existing App Service Plan used to create the Web App for the bot."
            }
        },
        "newWebAppName": {
            "type": "string",
            "defaultValue": "[resourceGroup().name]",
            "metadata": {
                "description": "The globally unique name of the Web App. Defaults to the value passed in for \"botId\"."
            }
        },
        "appInsightsName": {
            "type": "string",
            "defaultValue": "[resourceGroup().name]"
        },
        "location": {
            "type": "string",
            "defaultValue": "[resourceGroup().location]"
        },
        "appInsightsLocation": {
            "type": "string",
            "defaultValue": "[resourceGroup().location]"
        },
        "useStorage": {
            "type": "bool",
            "defaultValue": true
        },
        "storageAccountName": {
            "type": "string",
            "defaultValue": "[resourceGroup().name]"
        },
        "luisServiceName": {
            "type": "string",
            "defaultValue": "[concat(resourceGroup().name, '-luis')]"
        },
        "luisServiceAuthoringSku": {
            "type": "string",
            "defaultValue": "F0"
        },
        "luisServiceRunTimeSku": {
            "type": "string",
            "defaultValue": "S0"
        },
        "luisServiceLocation": {
            "type": "string",
            "defaultValue": "[resourceGroup().location]"
        }
    },
```

What shall I change here? Or where can I see if it's aligned with my subscription?

**Comment by luhan2017** [comment]
Can you try in your azure portal to check the available pricing in you subscription? for example:
![image](https://user-images.githubusercontent.com/32191031/69598738-53075a00-1045-11ea-8130-cab3a0631e45.png)

**Comment by stephanbisser** [comment]
Hi, yes it is here:
![image](https://user-images.githubusercontent.com/29750798/69898708-24e38c00-135d-11ea-8071-568290790646.png)

**Comment by hibrenda** [comment]
Sounds like a subscription issue?  please reference  https://stackoverflow.com/questions/53790218/error-scale-operation-is-not-allowed-for-this-subscription-in-this-region-when

**Comment by stephanbisser** [comment]
no I already checked that because I was able to provision the bot and so manually in that subscription...
But is there a way of selecting the subscription when executing that script you provide?

**Comment by luhan2017** [comment]
@stephanbisser  'az account list' to list all your subscriptions, 'az account set' to set the current active subscription.  

PS C:\Users\luhan> az account list
[
  {
    "cloudName": "AzureCloud",
    "id": "3e71927d-2914-4c36-bc5d-6369d1f42457",
    "isDefault": true,
    "name": "STCA-Bing Next - Official Account",
    "state": "Enabled",
    "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47",
    "user": {
      "name": "luhan@microsoft.com",
      "type": "user"
    }
  },

PS C:\Users\luhan> az account set --help

Command
    az account set : Set a subscription to be the current active subscription.

Arguments
    --subscription -s [Required] : Name or ID of subscription.

**Comment by stephanbisser** [comment]
Would it be possible to include the subscription settings in the Deploy dialog to pass that as a param to the script then? I think users might be confused about that way for setting the subscription

**Comment by cwhitten** [comment]
@stephanbisser are you still looking for assistance on this?

**Comment by stephanbisser** [comment]
Sorry I haven't tested this in a while but will do so tomorrow and give feedback @cwhitten

**Comment by stephanbisser** [comment]
@cwhitten sorry for taking so long, but now I finally tested it and the issue has been resolved, therefore I think we can close this issue
