### ISSUE TITLE
Ability to dynamically set Mulitple Choice options

### ISSUE THREAD

**Issue by smithbrianscott** [microsoft/BotFramework-Composer#1644]
**Is your feature request related to a problem? Please describe.**
Currently multiple choice options can only be set in a static format. I manually have to write each option and cannot set the options to an array from an http call.

**Describe the solution you'd like**
I would like the ability to make an http call, get back a list or array of values and then ask the user a question in which they would be able to select the option from that result. For example

HTTP call returns ["Red", "Blue", "Green"]
Bot asks user: What is your favorite color?
Options are Red, Blue, and Green

**Describe alternatives you've considered**
We have considered displaying a string format of options with ID values and requesting the user to input the ID value next to the option they wish.

**Comment by a-b-r-o-w-n** [comment]
@smithbrianscott Thanks for the issue! We are aware of this and should start working to address this soon. We will use this issue to track that work.

**Comment by LiorArmiev** [comment]
This is a must feature if possible as there is no other way to turn the content to be dynamic in the card

**Comment by a-b-r-o-w-n** [comment]
@LiorArmiev We are actively working on this now. Expect to see it in the stable branch in a couple of weeks.
