### ISSUE TITLE
OAuth connection problem

### ISSUE THREAD

**Issue by LiorArmiev** [microsoft/BotFramework-Composer#1646]
I'm adding OAuth to by composer and its getting to the point of returning 
"Please enter this validation code into the chat window to complete the sign-in:" with a code for the bot.
but from this point, nothing happened. Is it not a problem that someone encountered?
I had in mind that maybe its a problem with the redirect but it looks good.

I use simple AD connection, the connection is working, and on login, it's getting to the login page and getting back a number to enter in the console. but from that point nothing.

**Comment by luhan2017** [comment]
@LiorArmiev could you share more information to us. For example, How did you set the OAuthInput and also your setting page. Have you set the appid and password in the settings page and also in the emulator?

**Comment by luhan2017** [comment]
@LiorArmiev could you share more information to us. For example, How did you set the OAuthInput and also your setting page. Have you set the appid and password in the settings page and also in the emulator?

**Comment by luhan2017** [comment]
@LiorArmiev could you share more information to us. For example, How did you set the OAuthInput and also your setting page. Have you set the appid and password in the settings page and also in the emulator?

**Comment by LiorArmiev** [comment]
It was my mistake, I forgot to add the ID and key in the emulator itself, is it in the documentation?
Thanks

**Comment by luhan2017** [comment]
@zxyanliu could you help add the step(config the appid and password in the emulator) in the doc?

**Comment by g138** [comment]
@LiorArmiev can you guide me on how did you solve the issue?
