### ISSUE TITLE
save Composer version in generated bot

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#1650]
**Is your feature request related to a problem? Please describe.**
 When composer is updated, previously generated bot may not be able to be opened and it is not easy to figure out the version it is generated by.

**Describe the solution you'd like**
Save version somewhere.
So user could also upgrade the bot if upgrading guideline is provided.

**Describe alternatives you've considered**

**Additional context**
It is important when this is stable..

**Comment by hibrenda** [comment]
Thanks for the suggestion. This issue will be addressed when composer support versioning.
