### ISSUE TITLE
When should we expect the Composer to run as a centralized hosted web application? 

### ISSUE THREAD

**Issue by alexmoraru25** [microsoft/BotFramework-Composer#1654]
When should we expect the Composer to run as a centralized hosted web application? Is there a roadmap of the project or something similar?

**Comment by benbrown** [comment]
@alexmoraru25 when you say "centralized hosted application" -- do you mean, you'd like to use Composer as a service, or do you mean you'd like to host Composer in the cloud yourself?

**Comment by alexmoraru25** [comment]
Right now the Composer is a web app that is run locally and does not have capabilities to handle multiple users, creating their own bots and storing somewhere cetralized. Is this something you will be working on or should this be developed separatelly by each individual?

**Comment by cwhitten** [comment]
Hi @alexmoraru25.

The Composer web-app is intended to be a platform component that anyone can take and host on their own infrastructure. This includes plugging in to storage, user models, environment models, authentication, asset versioning, workflow, etc. The Composer server has [interfaces ](https://github.com/microsoft/BotFramework-Composer/tree/stable/Composer/packages/server/src/models) that allow individuals to being their own adapters to fit their existing infrastructure. As an example, we currently have storage adapter implementations for [AzureBlob](https://github.com/microsoft/BotFramework-Composer/blob/stable/Composer/packages/server/src/models/storage/azureBlobStorage.ts) and [FileSystem](https://github.com/microsoft/BotFramework-Composer/blob/stable/Composer/packages/server/src/models/storage/localDiskStorage.ts).

We'd love your feedback on this model and if this could fit your needs as we mature these interfaces and had formal documentation to help users host Composer in this way. We're actively working on this now.

Thanks!

**Comment by tdurnford** [comment]
@cwhitten Any updates on the status of this?

**Comment by cwhitten** [comment]
Closing this issue. See https://github.com/microsoft/BotFramework-Composer/issues/1654#issuecomment-558913572 for guidance on how to self-host Composer.
