### ISSUE TITLE
Organize lg parsing logic to 'shared' lib

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#1659]
Relates to #1308 

**Where are we parsing lg strings?**
1. In 'visual -> ObiEditor.ts', we parse lg string to extract lg name and node id to perform lg copy.
2. In 'visual -> utils -> hooks.ts', we parse lg string to extract lg name (and then invoke lgApi to update template)
3. In 'client -> lgUtils.ts', we parse lg string to extract lg name
4. In 'packages/lib -> indexers -> dialogIndexer.ts', we parse lg string to extract lg name
5. In 'form -> TableField -> line 100', extract lg name out of string
6. In 'form -> LgEditorWidget.tsx -> line 35~52, line 102', construct a lg id.

**How will we organize those parsing logic?**
1. We will implement some shared lg string parsing APIs, in the 'shared' lib.
2. Then replace all appearances above to let them share the same logic.

**Related Concepts**
- `- @{bfd-1234}` = LgText
- `@{bfd-1234}` = LgTemplateRef
- `bfd-1234` = LgName

**Interfaces we need:**
https://github.com/microsoft/BotFramework-Composer/pull/1351#issuecomment-553405746

```ts
class LgTemplateRef { // '@{bfdactivity-123456}'
    type: string; // 'activity' | 'prompt' | ...
    designerId: string; // '123456'
    params?: any[];
}
isLgTemplateRef: (input: string) => boolean;
parseLgTemplateString: (input: string) => LgTemplateRef;
toLgTemplateString: (ref: LgTemplateRef) => string; // '@{bfdactivity-123456}'
toLgTemplateName: (ref: LgTemplateRef) => string; // 'bfdactivity-123456'
```

We will use `toLgTemplateString` to create the content written to dialogFile;
we will use `toLgTemplateName` to create the required input parameters to call lgUtils.

**Comment by boydc2014** [comment]
From a consistence perspective,  a set of api should be self contained, which means 

``` javascript

// Section 1:    
// this is a self contained  lgRef <=> string convesion
class LgTemplateRef {
    name: string;
    parameters?: string[]
    toString(): string; 
}

isLgTemplateRef(input:string) => boolean
parseLgTemplateRef(input:string) => LgTemplateRef  // this should be called parseLgTemplateRef

// above is self-contained, and only have lg knowledge

// Section 2
// this is a lgName <=> some conversion
class LgMetaData 
{
   type:  string;
   desginerId: string;
}

generateLgTemplateName(metadata: LgMetadata): string
extractMetaData(lgName: string): LgMetaData
```

**Comment by boydc2014** [comment]
> From a consistence perspective, a set of api should be self contained, which means
> 
> ```js
> // Section 1:    
> // this is a self contained  lgRef <=> string convesion
> class LgTemplateRef {
>     name: string;
>     parameters?: string[]
>     toString(): string; 
> }
> 
> isLgTemplateRef(input:string) => boolean
> parseLgTemplateRef(input:string) => LgTemplateRef  // this should be called parseLgTemplateRef
> 
> // above is self-contained, and only have lg knowledge
> 
> // Section 2
> // this is a lgName <=> some conversion
> class LgMetaData 
> {
>    type:  string;
>    desginerId: string;
> }
> 
> generateLgTemplateName(metadata: LgMetadata): string
> extractMetaData(lgName: string): LgMetaData
> ```

**Comment by zhixzhan** [comment]
Seems above API missing a lot util methods.
I suggest a 'shared' lib should cover all current methods used in server/dialogIndexer, client/lgUtil.
or we can base on client/lgUtil.ts, extend it to be a shared lg uitl.
https://github.com/microsoft/BotFramework-Composer/blob/e47d8ecc7154d1c36a469c8b5959be98391c436a/Composer/packages/client/src/utils/lgUtil.ts#L138-L153

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1663
