### ISSUE TITLE
provide a link(button) to User Input editor / external editor for lu

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#1660]
**Is your feature request related to a problem? Please describe.**

This editor is somehow limited compared to the User Input or some external ones (e.g. VS Code)
![image](https://user-images.githubusercontent.com/2876650/69599889-a2e82000-1049-11ea-9c8a-e1f6e29e23f9.png)

User Input:
![image](https://user-images.githubusercontent.com/2876650/69599904-ac718800-1049-11ea-93fe-8fd92e4c4049.png)

**Describe the solution you'd like**

User still could do some quick edits here, and also be able to navigate to the advanced User Input editor / favored external editor with simply clicking one link(button).

**Describe alternatives you've considered**

**Additional context**

**Comment by hibrenda** [comment]
@sangwoohaan As a composer user, people would like to easily navigate from inline LG/LU editing to LG/LU all up view for better editing experience and user could also be easily navigate back to continue the dialog flow editing.

**Comment by mareekuh** [comment]
@xieofxie and @sangwoohaan - what is the issue here? To make the editing experience of LU comparable to LG?

**Comment by sangwoohaan** [comment]
No I think @xieofxie is suggesting to simply put a link to LG all-up view so that you can write LG in a bigger text field instead of in the small text field in the property editor. I am tackling this as a part of managed LG UX

**Comment by boydc2014** [comment]
> No I think @xieofxie is suggesting to simply put a link to LG all-up view in property editors with LG text fields so that you can write LG in a bigger text field instead of in the small text field in the property editor. I am tackling this as a part of managed LG UX

yes, user is asking a "navigate to all up view" button for more powerful editing experience.

**Comment by xieofxie** [comment]
Yes.
And I also think we could add a button to navigate back
