### ISSUE TITLE
Running docker-composer up currently fails

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#1669]
## Describe the bug
Currently, docker-compose up results in a failure with a SIGKILL during the build process.

<img width="821" alt="Screen Shot 2019-11-27 at 12 07 45 PM" src="https://user-images.githubusercontent.com/729873/69748772-adb8b880-110e-11ea-8ce3-9b653ca2518b.png">

## Version
current stable

## OS 
What operating system are you using?

- [x] macOS

## To Reproduce

1. Clone repo
2. Amend Composer/Dockerfile with `ENV NODE_OPTIONS "--max-old-space-size=4096"`
3. Run docker-composer up
4. Error!

## Expected behavior
I would expect the build to complete and for Composer to run.

## Additional context
This has been reported by a customer running Windows locally as well.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1709
