### ISSUE TITLE
Learn More link on settings is pointing to Microsoft SPO tenant

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#1675]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
If you go to settings and click the "Learn more" button it points to http://aka.ms/absh/docs/settings which resolves into https://microsoft.sharepoint.com/teams/ConversationalAI785/_layouts/15/AccessDenied.aspx?Source=https%3A%2F%2Fmicrosoft%2Esharepoint%2Ecom%2Fteams%2FConversationalAI785%2F%5Flayouts%2F15%2FWopiFrame%2Easpx%3Fsourcedoc%3D%252Fteams%252FConversationalAI785%252FShared%2520Documents%252FGeneral%252FConversational%2520AI%26action%3Dedit%26wd%3Dtarget%2528PM%252Eone%257C67355280%252D3DBF%252D4364%252D8F4B%252D101757B6A7F8%252FHow%2520to%2520manage%2520secrets%2520in%2520ABSH%257CBE75E9DF%252D4C41%252D413D%252D86A6%252D97E1285B78CC%252F%2529&correlation=c7dd1c9f%2Db075%2D0000%2Dc913%2D2eb4d11f48d9&Type=item&name=7328fdb7%2De3b7%2D4ca8%2Da861%2D7cd21066950c&listItemId=9 which of course cannot be accessed if you don't have permissions on the SharePoint site.
Would be nice to have that resolved to a public link.

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).
test

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by mareekuh** [comment]
Should be pointing to this 
https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/deploy-bot.md

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1691
