### ISSUE TITLE
[LSP]  auto-suggestion for template name/body should be meaningful

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1678]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Editing in LG all up view, when you type template name/body, it will auto suggest lots of irrelevant info .

**Describe alternatives you've considered**
- For template name, should not auto-suggest or should auto-suggest based on the context 
   eg. list out the template name during template editing , this could help user to avoid duplicate name definition across different dialog. 
- For body editing, only auto suggest  pre-built function and the predefined template name to make the LG editing more productive.

**Additional context**

**Comment by sangwoohaan** [comment]
I think there are three micro-contexts here
1. Creating a new template: start with #
2. Referring to a template or a property: @{
3. Prebuilt function: Anytime

1) should suggest nothing, 2) would only suggest other templates, then 3) suggests all the prebuilt functions(not templates). Would this make sense? @cwhitten  @a-b-r-o-w-n

**Comment by a-b-r-o-w-n** [comment]
3 would only make since in a template body I believe. Other than that, this makes sense.

**Comment by sangwoohaan** [comment]
Ok, that makes sense. Could we also suggest known properties like dialog.XXX after @{? Would this potentially cause runtime errors?

**Comment by a-b-r-o-w-n** [comment]
We should be able to do that eventually. The language server work should enable that, but I'm not sure what's required to do so.

**Comment by zhixzhan** [comment]
In language server, we can recognize current context, and return proper suggestion list. I will take this
