### ISSUE TITLE
[LSP] need to provide accurate error info for inline lg editing 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1680]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
user input error format for template body in sendactivity .eg "hey" (without "-")
switch to other dialog and add another sendactivity. it will always complain error due to wrong format in all up view.  This is not friendly to user as he could not understand why correct step will lead to an error message.

**Describe alternatives you've considered**

**Additional context**

**Comment by zhixzhan** [comment]
located problem here is inline editor bring in full context error. I will filter this, let inline editing only show error from itself

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1676
