### ISSUE TITLE
navigate back action for LG table view edit

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1681]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
navigate from dialog flow to LG all up view, do not change the focus. now "All" is selected in lg all up view.
click 3 dot to edit the specific template
click 'back' in browser, it will still in edit mode
click 'back' again, navigate back to dialog flow 
Actually I am expecting to back to the table view first and then back to the dialog flow.
so we'd better refine the navigation path for lg all up view

**Describe alternatives you've considered**

**Additional context**

**Comment by zhixzhan** [comment]
Let me clarify this.
```
PageA----> PageB---> PageB(status1) ---> PageB(status2)
                                  
          when click back                  
 <-------------------------------------|

status1 is table view.
status2 is editor view.
```
The question is shall we allow `internal status` in one single url?
if yes, click back jump over to PageA i think make sense.

if we really need those status reflect with forward/back, we should add query like `url?view=tablelist` keep  consistency between view and url.
