### ISSUE TITLE
Output code in NodeJs

### ISSUE THREAD

**Issue by kushalbhabra** [microsoft/BotFramework-Composer#1682]
[Feature request]

We're working on NodeJS platform and have implemented, custom logging, custom dialogs etc.

The bot composer is great but I'm unable to use my existing code to integrate in it as the output code is in c#.

It'd be great if we have option to select output code language in bot composer as NodeJs allowing us to integrate existing codebase easily.

**Comment by cwhitten** [comment]
Hello @kushalbhabra and thank you for the issue - we're actively working on support for Node.js. We're anticipating preview Node.js support in early 2020. 

I'll pin this issue for future reference and update this thread as appropriate.

**Comment by HesselWellema** [comment]
+1

**Comment by SamuelTassell** [comment]
+1

**Comment by Halceyon** [comment]
+1

**Comment by HesselWellema** [comment]
Hi Team,

Any update on this? I would like to start building my projects with composer but need  to be able to add existing functionality (in Node).

**Comment by benbrown** [comment]
This is underway and you can track progress here: #3198

**Comment by kushalbhabra** [comment]
This is amazing.. Great effort!!

**Comment by HesselWellema** [comment]
I second that. Great job!

**Comment by michal-turzynski** [comment]
Great work - thank you!!
