### ISSUE TITLE
[docs] How much is linting & validation implemented in Composer?

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1684]
**General purpose of filing this issue** 

We plan to document on "Linting" in Composer and need support as to the following doubts:
-  How much is linting implemented in Composer now? specifically in terms of 
   - dimension/level and its categorization (dialog/trigger/steps/fields/lg/lu)? 
   - types of errors and warnings? 
   - features as specified in this doc: [Validation in BF Composer](https://microsoft.sharepoint.com/:w:/r/teams/ConversationalAI785/_layouts/15/doc2.aspx?sourcedoc=%7B45BEB97C-C5BA-4429-A131-65E5CD8A0376%7D&file=Validation%20in%20Composer.docx&action=default&mobileredirect=true&cid=b28fe13f-a935-4ccb-918f-55a0be35231f), see "user scenarios" and "interactive scenarios" sections below. 

**Resources explored**
- issues: [694](https://github.com/microsoft/BotFramework-Composer/issues/694), [1499](https://github.com/microsoft/BotFramework-Composer/issues/1499)
- PR: [1518](https://github.com/microsoft/BotFramework-Composer/pull/1518)
- doc: [Validation in BF Composer](https://microsoft.sharepoint.com/:w:/r/teams/ConversationalAI785/_layouts/15/doc2.aspx?sourcedoc=%7B45BEB97C-C5BA-4429-A131-65E5CD8A0376%7D&file=Validation%20in%20Composer.docx&action=default&mobileredirect=true&cid=b28fe13f-a935-4ccb-918f-55a0be35231f)

**User scenarios**
(please check features implemented already)
P0: 
- [x] An all-up view of errors across all assets
- [x] When there are errors, clicking "start/restart" should show indication of errors and then redirect to the all-up view of errors

P1: 
- [ ] At dialog level (show error indication in the left navigation pane)
- [ ] At trigger level of a specific dialog 
- [ ] At step level of a given dialog 
- [ ] At step's properties level 
- [ ] Toggle On/Off visual errors indication

**Interaction scenarios**
(please check features implemented already)
P0: 
- [ ] When adding a new step, Composer provides visual indication for all mandatory fields.
- [ ] When filling invalid data input in a given property, indicators should show. 
- [ ] When writing a malformed expression in a condition property with syntax errors, e.g. unknown function, missing brace, wrong operator, etc.,  
  - [ ] visual indicator should show in the text editor of the condition.
  - [ ] the edit box will be highlighted.
- [ ] When writing a malformed (syntactically wrong) LG, red lines will show under the erroneous syntax. 
- [ ] When writing a malformed (syntactically wrong) LU, red lines will show under the erroneous syntax. 

**Extra comments**

**Comment by hibrenda** [comment]
This is a brief summary and more detail we can sync offline.
- As a composer user,  If I edit the properties in form editor, I can get inline error syntax reminder. This includes following inline validation.
 a. user is making lu editing for lu file
 b. user is making response(sendactivity) & inputs editing for lg file
 c. user is editing "expression" field in property editor
- As a composer user, If I edit the LU/LG all up view, I can get inline error syntax reminder.
   and if I hover to the error reminder, I can get the suggestion for the fix
- As a composer user, I can go to notification page to view all the editing(LU/LG/Expression) errors/warnings with dialog location. If I click on the specific error, it will navigate to the specific dialog /property editor .
  a. for LG error, it will navigate back to the LG all up view with red rectangle 
  b. for LU error, it will navigate back to the dialog and LU editor will be displayed in red frame
  c. for expression(dialog) error, it will navigate back to the dialog as well and error inputs will be in red frame as well.
- coming soon for "When there are errors, "start/restart" should be in grey and could not be clickable . There is a indication of errors and then redirect to the all-up view of errors"

**Comment by zxyanliu** [comment]
Hi @hibrenda 
Thanks for the info. It's very helpful.
With your suggestion, I did a bit of research and testing, and here is what I got so far in terms of the three parts of validation in Composer: 

- Validation in lg file:
   - [ ] error reminder shows in inline editor
   - [ ] error will syn up to lg all-up view
   - [ ] error will syn up to notification all-up view 
   - [ ] mouse over error reminder will show details (both work in form editor and all-up view)

- Validation in lu file:
   - [ ] error reminder does not show in inline editor, but entire lu editor form box will show red
   - [ ] error is not reflected to lu all-up view
   - [ ] error is not reflected in notification all-up view
   - [ ] can still publish LUIS, bot can run, lu error message show in emulator

- Validation in expressions:
  - [ ] error reminder shows in form editor
  - [ ] error is not reflected in notification all-up view 
  - [ ] bot can still run, emulator will display the error of expression

**Comment by zxyanliu** [comment]
Closing because the questions are answered and the doc is done at this point.
