### ISSUE TITLE
UX Copy - Deploy should be : Publish

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1688]
Please update all references to 'Deploy' with 'Publish'.
Docs : 
Deploy bot (title and content)
Deploy Composer - can we replace this to 'Install'?

Maybe search and replace through the docs?

**Comment by zxyanliu** [comment]
Hi @mareekuh 

- I have replaced all references to "Deploy" with "Publish" in this [publish a bot](https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/R7-Doc-Updates/docs/deploy-bot.md) (title and content) article.

- Not sure if Composer UI should have consistent wording:
![image](https://user-images.githubusercontent.com/32497439/70092676-ac3a3500-15d3-11ea-9272-1f02aaf6b40a.png)

- I am not sure if we could replace "Deploy" Composer to 'Install'. That article is not in our [docs](https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/R7-Doc-Updates/toc.md).

**Comment by mareekuh** [comment]
Yes they should also be updated in Composer. I think there already is another bug for that.
@hibrenda  - could you verify this?

**Comment by hibrenda** [comment]
@mareekuh to double confirm your request: red circle will be replaced into "install" ? and yellow part will be "publish" ?
![image](https://user-images.githubusercontent.com/43408889/70141558-408ac180-16d2-11ea-8cad-71126de0616b.png)

**Comment by mareekuh** [comment]
No it should be PUBLISH. The left nav already is called Publish. 

There is a dock that talks about how to get BFC installed using docker etc. - for that document, 'Install' is probably more clear and sets it apart from the document(s) about publishing to your bot.

**Comment by mareekuh** [comment]
Has this been completed in the documentation @zxyanliu

**Comment by zxyanliu** [comment]
Hey @mareekuh, FYI. It's been fixed in the [documentation](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/how-to-publish-bot.md), but not in Composer UI. 

- Yan

**Comment by VanyLaw** [comment]
I will change it and merge it to https://github.com/microsoft/BotFramework-Composer/pull/2023 this PR.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2227
