### ISSUE TITLE
LG syntax highlighting for fault tolerance 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1689]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
If user input something as following in LG all up view, then it will introduce the error for LG syntax highlighting. Due to bracket missing in line3, so all the following lines are handled  incorrectly.

![image](https://user-images.githubusercontent.com/43408889/70030150-8cab0880-15e3-11ea-97a6-ad128eb0be62.png)

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1690
