### ISSUE TITLE
Change the font of guiding texts in property editors

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1692]
Currently, Composer is using the regular font for guiding texts
<img width="403" alt="Screen Shot 2019-12-03 at 1 39 49 PM" src="https://user-images.githubusercontent.com/50963385/70092707-bbb97e00-15d3-11ea-86dc-4b5686674024.png">

We'd like to use the italic font with dimmer color ( #BDBDBD )
<img width="335" alt="Screen Shot 2019-12-03 at 1 46 34 PM" src="https://user-images.githubusercontent.com/50963385/70092750-d0961180-15d3-11ea-9786-c1fa6885c371.png">

The complete inventory of property editor content can be found here : 
https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-UI-Master-library?node-id=144%3A0

**Comment by cwhitten** [comment]
This is done
