### ISSUE TITLE
Property editor font size adjustments

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1693]
There are a few gaps between the design and the build that can provide an immediate improvement by addressing them

<img width="315" alt="Screen Shot 2019-12-03 at 2 00 41 PM" src="https://user-images.githubusercontent.com/50963385/70093480-56ff2300-15d5-11ea-8914-26eb4615d493.png">

1. The sub-label ("Prompt for text" in the screenshot) font weight should be 400 (currently 600)
2. Prompt tab("Bot asks", "User input", "Other") font size is 16px (currently 18px)
3. Input field title("Property to fill") font size is 12px (currently 14px)
4. There's a 10px gap between the prompt tabs and the stroke above them(currently 0px)

**Comment by DesignPolice** [comment]
I added a quick link and updated spec for this... just keeping the spacing consistent. Spaces are in increments of 4 (4,8,12,16...) this makes it easier to have less options and no strange odd numbers.

https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=4095%3A28034

![Screen Shot 2019-12-09 at 9 42 24 AM](https://user-images.githubusercontent.com/45223620/70459200-8647e100-1a68-11ea-9018-6d3fa10c872a.png)
