### ISSUE TITLE
There shouldn't be an arrow after End this dialog node

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1695]
<img width="252" alt="Screen Shot 2019-12-03 at 2 05 20 PM" src="https://user-images.githubusercontent.com/50963385/70093796-0805bd80-15d6-11ea-9a57-e77ad1806357.png">
Currently, there's an arrow coming out below End this dialog node which allows you to add more actions after. I think End this dialog should be a dead-end, shouldn't it? This can be quite confusing. Although while changing it to a dead-end seems to be an easy solution, there's still a problem when you put this node in the middle of a flow, or in a conditional branch. Need design explorations.

**Comment by sangwoohaan** [comment]
Design : https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=3540%3A657

On top of all the inserting-endthisdialog-in-the-middle cases, I've added a default antion flow case with unremovable End this dialog action node as @mareekuh requested. Let's review.

**Comment by sangwoohaan** [comment]
Addressing https://github.com/microsoft/BotFramework-Composer/issues/1481, https://github.com/microsoft/BotFramework-Composer/issues/1474 in this issue.

**Comment by mareekuh** [comment]
@DesignPolice - do we have new designs for the 'end dialog' node?

**Comment by sangwoohaan** [comment]
Final design : https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=4586%3A0

@mareekuh @cwhitten

**Comment by DesignPolice** [comment]
@mareekuh I made some differently styled Nodes - but paused with iterations on the new style nodes with more information in them could either different or not needed... So for now just removing the arrow will let this function. 

https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=3898%3A0

**Comment by mareekuh** [comment]
@DesignPolice - did we settle on an end node indicator?

**Comment by DesignPolice** [comment]
I did a lot of different options, Sang selected just the plain Node box in gray with End this dialog in it. Any lines that came out of an End Dialog would look like this... I was unclear if or why that interaction would exist, if it ends then it ends... if it keeps going then delete the end. IDK 

![Screen Shot 2020-04-15 at 8 49 40 AM](https://user-images.githubusercontent.com/45223620/79358518-253c8800-7ef6-11ea-9a08-b9ee46c24ae7.png)

**Comment by mareekuh** [comment]
@DesignPolice @sangwoohaan  - remind me to follow up w both of you on this, Sang & Marc - I am not clear on what's decided and or if this done/closed or not?

**Comment by DesignPolice** [comment]
I think the diagram above is what we selected, not sure if it was built. May need to remove some arrowheads based on what Sangwoo was seeing.

https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=4308%3A87
