### ISSUE TITLE
Change label "Dialog" to "Dialog name" in Replace this dialog node

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1697]
<img width="390" alt="Screen Shot 2019-12-03 at 2 09 18 PM" src="https://user-images.githubusercontent.com/50963385/70094165-c6c1dd80-15d6-11ea-9e82-a06e149e88d1.png">

There's an inconsistency between this and the same field in Begin a new dialog(where it says "Dialog name"). Let's change this label to Dialog name so that they match.

**Comment by tdurnford** [comment]
The SDK Schema has the dialog title as "Dialog name" for both Replace and Begin Dialog. We should update the App Schema for Replace Dialog to reflect the title in the SDK Schema.

### Begin Dialog
#### SDK Schema

https://github.com/microsoft/BotFramework-Composer/blob/028775b3c5fcf8345c52203bd11269bfed558378/BotProject/CSharp/Schemas/sdk.schema#L813
#### App Schema

https://github.com/microsoft/BotFramework-Composer/blob/028775b3c5fcf8345c52203bd11269bfed558378/Composer/packages/lib/shared/src/appschema.ts#L249


### Replace Dialog
#### SDK Schema
https://github.com/microsoft/BotFramework-Composer/blob/028775b3c5fcf8345c52203bd11269bfed558378/BotProject/CSharp/Schemas/sdk.schema#L6218
#### App Schema
https://github.com/microsoft/BotFramework-Composer/blob/028775b3c5fcf8345c52203bd11269bfed558378/Composer/packages/lib/shared/src/appschema.ts#L2735

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1966
