### ISSUE TITLE
Send an HTTP request input field header update 

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1698]
'Body' and 'Header' fields' headers and tooltips are inconsistent with the rest.

Current : 
<img width="380" alt="Screen Shot 2019-12-03 at 2 17 59 PM" src="https://user-images.githubusercontent.com/50963385/70094639-d130a700-15d7-11ea-89bd-e04188b4716d.png">

Design : 
<img width="369" alt="Screen Shot 2019-12-03 at 2 16 20 PM" src="https://user-images.githubusercontent.com/50963385/70094648-d7bf1e80-15d7-11ea-989d-9cf4ad49a0fc.png">

Also, we need header texts for the array.

Design : https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-UI-Master-library?node-id=144%3A1046

**Comment by tdurnford** [comment]
Resolved by https://github.com/microsoft/BotFramework-Composer/pull/1858
