### ISSUE TITLE
[linting&validation] Error suggestion in property editor does not sync with the notification page. 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1699]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
Error suggestion in property editor does not sync with the notification page. We need the error info  to be synced between composer server and client.

user add a if/else step and leave condition as empty. 
in notification page, we will have following errors but these does not show up in property editor.
![image](https://user-images.githubusercontent.com/43408889/70116175-e15e8a00-169c-11ea-9198-08e2311bf572.png)

Meanwhile, a string in property editor marked in red and these info won't show up in notification page. 

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.

**Comment by boydc2014** [comment]
It's unrelated to server/client syncing issue. Because all what you see, is done at client. 

In Form today, we haven't show the detailed error message when checking property yet.  With @alanlong9278's work in https://github.com/microsoft/BotFramework-Composer/pull/1683, he will be able to show the detailed error message. 

Re-assign this to @alanlong9278, and mark as enhancement.

**Comment by a-b-r-o-w-n** [comment]
@boydc2014 @alanlong9278 work was just a refactor of existing error UI. It does not enable that UI for other types of fields, only LU, LG, and expressions. 

Further, the errors surfaced in the form are not driven by the shell, rather the individual fields may implement their own validation logic independently of the dialog indexer. There is more work to be done here. 
1. The form needs to accept the diagnostics generated by the dialog indexer in a way that the form can understand.
2. The error UI needs to be added to every type of field in the form (dropdowns, number widgets, date widgets, etc).

**Comment by alanlong9278** [comment]
@a-b-r-o-w-n  The pr is for the first item. And the notifications page just show the lg, lu and expression diagnostics, so for the second item, do we need to check the other types of field ourselves in the form editor?

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1737
