### ISSUE TITLE
lg content does not show in **Send a response** action node

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1700]
## Describe the bug
I authored lg inline, but the content does not show in **Send a response** action node. 

## Screenshots
![image](https://user-images.githubusercontent.com/32497439/70190824-d7905300-16ab-11ea-92f5-5fcdfddb6847.png)

**Comment by hibrenda** [comment]
similar to this https://github.com/microsoft/BotFramework-Composer/issues/1212

**Comment by yeze322** [comment]
broke by changes in #1676 
![image](https://user-images.githubusercontent.com/8528761/70231853-1e5a7780-1796-11ea-96ee-8fa38abdf3c7.png)
this will trigger a 'postMessage' error
![image](https://user-images.githubusercontent.com/8528761/70231879-2ca89380-1796-11ea-9a2d-a2f49c278879.png)
@zhixzhan

**Comment by zhixzhan** [comment]
> broke by changes in #1676
> ![image](https://user-images.githubusercontent.com/8528761/70231853-1e5a7780-1796-11ea-96ee-8fa38abdf3c7.png)
> this will trigger a 'postMessage' error
> ![image](https://user-images.githubusercontent.com/8528761/70231879-2ca89380-1796-11ea-9a2d-a2f49c278879.png)
> @zhixzhan
> LgParser cannot be executed in ShellApi

Window.postMessage will clone json message body, and body need to be a plain object. raw parse result contains prototype methods can't be cloned. it need to be filtered
fixed in https://github.com/microsoft/BotFramework-Composer/pull/1707

**Comment by zhixzhan** [comment]
Addressed in #1707
