### ISSUE TITLE
LU all-up-view editing don't reflect on form editor

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#1702]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
LU all-up-view editing don't reflect on form editor

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Go to '/language-understanding'
2. Click on 'edit'
3. make some change on lu file
4. Go to '/dialog/Main'
5. new change don't reflect here.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1704
