### ISSUE TITLE
need  more specific error message on editor 

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#1705]
**Is your feature request related to a problem? Please describe.**

when loaded file got error, (form inline editor/ all-up-view editor, lg, lu), we got error hint like this:

![image](https://user-images.githubusercontent.com/49866537/70212526-65367600-1772-11ea-8b21-3447baef5ec0.png)

`This text has errors in the syntax. Refer to the syntax documentationhere.`
current error message displayed below editor don't give any help, 

**Describe the solution you'd like**
I prefer here give specific error message, actually we already have this error from server diagnostics/ luParser/ lgParser, but those message may not be very meaningful, or absolutely correct. for the reason don't confuse user, we now hide it, and display an generic error.

But I think a long term better way is to improve the accuracy of Parser. not hide it.

**Additional context**
We now have two layer error hint in inline-editor:
1. inside editor, vscode style diagnostics, ( from editor LSP Server )
2. outside editor, red boarder & error message. ( from client/server diagnosis )

**Comment by zhixzhan** [comment]
@hibrenda @boydc2014 do you have any comments?

**Comment by cwhitten** [comment]
once https://github.com/microsoft/BotFramework-Composer/pull/1711 lands this will be much more clear
