### ISSUE TITLE
[build] package.json in lib/indexers has unresolved botbuilder-expression-parser

### ISSUE THREAD

**Issue by hailiu2586** [microsoft/BotFramework-Composer#1715]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
Give a clear and concise description of what the bug is.

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.

**Comment by cwhitten** [comment]
@hailiu2586 we don't think this is an issue. Can you refer to @a-b-r-o-w-n 's guidance in #1714 ?

**Comment by zhixzhan** [comment]
fixed in https://github.com/microsoft/BotFramework-Composer/pull/1737
