### ISSUE TITLE
UX | Using all content and features to improve LU ML (LUIS, QnA, etc)

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1720]
Managed LU - UX
4. Composer helps to improve language understanding by automatically using all content and features, independent of the associated recognizers (LUIS, QnA, etc)

**Comment by cwhitten** [comment]
@mareekuh I don't know what this means but leaving this as a UX/Design task.

**Comment by mareekuh** [comment]
I have no idea either. I think this came from one of Brenda's items in the project list. (-;
