### ISSUE TITLE
UX | Create, edit and test re-usable bot responses (LG templates) in the context of a dialog

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1722]
Managed LG - UX
1. Composer allows me to create, edit and test re-usable bot responses (LG templates) in the context of a dialog, supporting the following:
    1. Type of bot response : text (question), text (answer), image, value, link etc.
    2. Multiple communication mediums (speech, text, gestures, visuals/cards)
    3. Multiple languages
    4. Alternative responses (same response, different phrasing)
    5. Conditions when to use which response
    6. Definition of valid, expected user input
    7. Behavior and/or response when user input does not meet expectation

**Comment by mareekuh** [comment]
@DesignPolice to work with Sang on visual presentation/optimization of LG editor, in parallel with UX design & input from Windows CUX team (ie connect with Sang and discuss current progress to see where and how you can assist - do not wait until UX is approved).

**Comment by cwhitten** [comment]
This is coming in as part of the updated LG authoring in R12/R13. Closing
