### ISSUE TITLE
UX  | Test bot prompts and responses (LG) in a visual manner in the context of dialogs/conversations

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1723]
Managed LG - UX

2.  LG testing  | Composer enables me to test the conversations and bot Responses (LG) in a visual manner in the context of dialogs/conversations, and provides actionable information to improve recognition and flow

**Comment by cwhitten** [comment]
Closing as stale. Will work with triad on updated requirements and priorities.
