### ISSUE TITLE
UX | multi-language support: review and edit translations in the context of dialogs

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1726]
Managed LG | UX Multi-lang support
5. Composer enables me to create bot responses in multiple languages, and allows me to review and edit translations in the context of dialogs. [p1/p2]

**Comment by mareekuh** [comment]
@cwhitten and @sangwoohaan  - let's use this Git issue to add multi lang support 
- at a bot level : export/import LG; set default language if multiple exist
- at dialog level : review and edit LG per dialog to adjust to appropriate for the language/culture

@sangwoohaan  - make this a priority please, after R8 deliverables are done (01/31)

**Comment by sangwoohaan** [comment]
Design WIP : https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=4269%3A0

@mareekuh @DesignPolice

**Comment by mareekuh** [comment]
Updated designs are here:
https://www.figma.com/file/HLtKaKHctLldivPnzQ7BqQOI/Composer-MI-lotsotings?node-id=2134%3A7
<img width="426" alt="Screen Shot 2020-02-25 at 7 40 44 PM" src="https://user-images.githubusercontent.com/48503434/75309729-c10b1b00-5806-11ea-9a9c-4bd8dddcf633.png">

**Comment by mareekuh** [comment]
Postponed to R10 or undetermined?
