### ISSUE TITLE
UX | Bot-bot for assistance in using Composer

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1727]
UX | Implementation and productization of Xi's bot-bot demo
(original  Github issue: https://github.com/microsoft/BotFramework-Composer/issues/772)

·  Handoff slide: ClippyHandoff.pptx
·  Figma (coachmarks and teaching bubbles): https://www.figma.com/file/NqlONHOHjE0amtoHlLlopg9p/Composer-XY-07.16?node-id=1391%3A2042
 
Business Justification - 

- allows us to assist users in context in a conversational manner and 
- allows us to keep content accurate, up to date and 
- get telemetry about what people struggle with
- test our multi-bot runtime capabilities/feature

**Comment by mareekuh** [comment]
Can we add Xi's bot-bot back in?
Now that we have the native ability to run more than one bot at the time, I think this is a really cool and useful and demo-able thing to add. And now that Yan has a ton of content and have 'support' for QnA maker, this is a great way to expose it.

**Comment by cwhitten** [comment]
Closing as stale. Will work with triad on updated requirements and priorities.
