### ISSUE TITLE
UX | Create-new wizard extension and enhancement 

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1728]
Pick up where we left off with the Create New bot/dialog wizard.

Business justification:
Currently, Composer skips the step if Design/Plan and jumps right into building a dialog, assuming the user knows what they are creating and why, and that they are fluent with Composer and the SDK. The 'Created New' wizard attached below helps people getting started by asking them to input some information in a 'human' /conversational manner, and uses this to bootstrap the dialog. I believe this will lower the threshold for users to get started with Composer and hit the ground running and making it easier to understand concepts such as LG, LU, Events, Triggers etc. as they are already repopulated with the content provided in the Wizards.

Also 
- We are approaching the stage where we're allowing people to create multiple types of dialogs, so our Create New flow needs to scale to support this and make this easily discoverable:
- adaptive dialogs & sub-dialogs
- generated dialogs
- QnA dialogs
- Samples

https://www.figma.com/file/NqlONHOHjE0amtoHlLlopg9p/Composer-XY-07.16?node-id=1632%3A25465

Enable users to 'seed' their dialog with 
- Take full advantage of Managed LU

**Comment by mareekuh** [comment]
@DesignPolice - As I know that you are not pleased with the current design for 'create new', in particular because of the presentation of the many (ex)samples in the dialog, this is an FYI. Would love to hear your suggestions

**Comment by DesignPolice** [comment]
@mareekuh I will update the flow that Xi made and add a link here, with a few screen grabs for those who don't want to get into Figma.

**Comment by DesignPolice** [comment]
This is an existing issue, but has gotten cold, maybe just link it to restart the conversation.

The Create New modal needs color help to pass, it is also a very long list of boxes. I think the original thoughts that there were some "templates" that were better suited to start from vs some of the examples on how to do specific things. 

I moved 3 template options up to the "New" row these could be the Top3 or just more complex starting points to save time?

If we aren't ready to do that, I made a few options for just making a better Modal and we can put off the HomePage for awhile. 

If you want I can work on some different options based on your thoughts - I just want to clean this up and make it more friendly and clear.

Here is the Figma link.
https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=4392%3A31054

![Screen Shot 2020-01-27 at 11 52 26 AM](https://user-images.githubusercontent.com/45223620/73208553-86c13780-40fb-11ea-84e4-4e11a392abd8.png)


![Screen Shot 2020-01-27 at 11 49 38 AM](https://user-images.githubusercontent.com/45223620/73208339-23370a00-40fb-11ea-922a-3091b7bc431e.png)

@mareekuh @cwhitten

**Comment by cwhitten** [comment]
see https://github.com/microsoft/BotFramework-Composer/issues/1533

**Comment by mareekuh** [comment]
Let's go with option 3. I expect we'll need to revisit the Create dialog when we can create things like skills (remote and local) and (re)usable dialogs so let's just use the easiest and most scalable approach (dropdown* for navigation to the right folder, list view for selection).

Marc's design does not have a dropdown to indicate the folder for which we're showing the content.

**Comment by DesignPolice** [comment]
@cwhitten @mareekuh - ah yes good point on the folder and changes - do you want me to look at that addition or wait for the need to be there.??

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2521
