### ISSUE TITLE
UX | Connect bot/dialog to an existing bot, dialog or skill

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1729]
UX - Create Skill/Dialog

As a composer user, I want to connect my current bot/dialog to an existing bot, dialog or skill to enhance the functionality and/or abilities of my bot:
- Created with Composer - Use w/o customization
- Created with Composer - use as sample and customize
- Created in another program or tool beside Composer (PVA etc)
- Created with BF SDK V4 or V3
- Connect to a externally running service (ie a remote skill) 

@christopheranderson and @darrenj to collaborate with @sangwoohaan and @emivers8 on spec and flow. Please also provide clarity between dialogs, reusable skills and remote skills so that we are using the same definition across the team.

**Comment by sangwoohaan** [comment]
Would this also touch QnA Maker?

**Comment by mareekuh** [comment]
Yes we already have this enabled. If you expect we need to change that experience based on this issue (1729), then let's discuss.
We will also work on the ability to create a dialog from a Q & Answer pair, or integrate one into an existing dialog.

**Comment by mareekuh** [comment]
@sangwoohaan  - Please work with Em to design the flow for:
1. - Save Composer bot/set of dialogs as a skill such as a BF SDK V4 or V3 bot
2.  Open and connect to external skill (VA)
2.  Open and connect to existing dialog/skill 
3. Open and connect to external skill - PVA
4. Post skill created in Composer to be consumed by PVA (needs to be validated before it is included in PVA skill library - check out how they do this now, can we do this automatically for them?)

This is a priority. Please start this asap after R8 deliverables are done. 
Dev needs to start on this soon.

**Comment by cwhitten** [comment]
This has shipped with Bot Projects
