### ISSUE TITLE
UX | Design UX for 'Generated dialog', allowing users to capture more than one piece of user input at the time (aka form)

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1730]
For task-oriented dialogs such as ordering food, a table or tickets, the bot typically needs information from the user. Sometimes users provide all of the needed information at once (I want a double tall soy latte with Ice) and sometimes the bot needs to ask the user to ask additional questions to complete the order or request. 
How can we build on the current composer UX and SendMessage/Prompt experience to define more than one user input/question?

See also :
https://www.figma.com/file/HLtKaKHctLldivPnzQ7BqQOI/Composer-MI-lotsotings?node-id=1873%3A158

**Comment by cwhitten** [comment]
This has shipped with form dialogs
