### ISSUE TITLE
Ability to rename Dialogs

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#1741]
Feedback from Microsoft MVP's!

**Comment by sangwoohaan** [comment]
Can't you do this already in the current build? @cwhitten

**Comment by mareekuh** [comment]
There are 3 places where the user can rename a dialog
1. In the left nav
2. Breadcrumb
3. Properties panel 
4. Create-new - dialog
5. Save as - dialog

https://www.figma.com/file/HLtKaKHctLldivPnzQ7BqQOI/Composer-MI-lotsotings?node-id=2108%3A13659
@cwhitten

**Comment by sangwoohaan** [comment]
I think clicking on a dialog on Breadcrumb should take you to the dialog instead of renaming it? At least that's how it works currently.

**Comment by sangwoohaan** [comment]
Per discussion with @mareekuh today 
- Renaming in the left nav, properties panel stays as it is.
- Don't allow renaming in the breadcrumb. @mareekuh and I think the breadcrumb needs to be removed entirely, needs further discussion.
- 4. Create-new isn't really renaming.
- 5. Save-as needs rescoping.

**Comment by cwhitten** [comment]
Adding to R13 for prioritization discussion

**Comment by garypretty** [comment]
@cwhitten @mewa1024 Let's discuss in our next sync.

**Comment by cwhitten** [comment]
Why was this closed?

**Comment by mareekuh** [comment]
It's been open since Dec 9, 2019  - Happy to reopen if we intend to address it?

**Comment by mewa1024** [comment]
did renaming in the project tree get removed? it's not in the ... menu, and clicking on the name doesn't seem to work. I think the project tree might be the more expected place to change the name then the property pane.

**Comment by mewa1024** [comment]
Is this the same issue as #6291?

You can rename a dialog in the UI via the form editor (aka property pane), but that just changes the name field in the designer. For example, I renamed my dialog from "test2" to "test1234":

![image](https://user-images.githubusercontent.com/39317542/124377232-d6e0e980-dc5f-11eb-8df7-3eb6dcef95bc.png)

But my .dialog file still has the old name:
![image](https://user-images.githubusercontent.com/39317542/124377249-ee1fd700-dc5f-11eb-8a4a-940861709d6f.png)
