### ISSUE TITLE
[Linting & Validation] LU error is not removed after selecting 'none' recognizer type

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#1744]
### Current workaround
If you are no longer using an LU file and are seeing this, you can either delete the file or correct the syntax error in the file and then refresh the page.

Steps:
1. Create a dialog and select `LUIS` recognizer type
2. add invalid LU -- see an error inline and in the notifications page
3. Select `None` in the recognizer type dropdown
4. Notice the LU error still shows in the notifications page.

Side effect of this is that a user is unable to start a bot because there is an error even though LU is not being used.

**Comment by cwhitten** [comment]
Diagnostics/Indexer should not block the runtime if there is an error in the .lu, but the .lu is not being used.
