### ISSUE TITLE
lu inline editor swallow characters

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#1748]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
inline lu editor swallow characters if enter quickly.

## Version
master branch

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
![1234](https://user-images.githubusercontent.com/39758135/70534867-e9379600-1b96-11ea-99e4-fc6d3ae09b91.gif)

**Comment by zhixzhan** [comment]
looks like unexpected re-render, i will take a look

**Comment by yeze322** [comment]
the solution should be controling the submission rate of that editor to avoid triggerring save api too frequent. form editor also ran into this problem.

to entirely solve this kind of issue, we should avoid resetting global state at each invocation of the save handler

**Comment by zhixzhan** [comment]
> the solution should be controling the submission rate of that editor to avoid triggerring save api too frequent. form editor also ran into this problem.
> 
> to entirely solve this kind of issue, we should avoid resetting global state at each invocation of the save handler

Sure it is, every form commit would case a global state change. For one component, if the value it referred changed, it would auto re-render it self. for most component, it works fine. But for some editing field, like monaco-editor, text-input, it cause lost forcus or blur cursor. My current solution here is maintain a local state, avoid re-render triggered by global state, not the best but works anyway.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1765
