### ISSUE TITLE
Small bugs in Composer samples

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1763]
Here are a few bugs I found in [current Composer samples](https://github.com/microsoft/BotFramework-Composer/tree/master/Composer/packages/server/assets/projects). 

#### 1. ControllingConveresationFlowSample
Bug: The properties panel of `Dialog cancelled` event shows "Unsupported field schema for field Main#.trigger". 

![image](https://user-images.githubusercontent.com/32497439/70668641-03ba4f80-1c29-11ea-84ac-e34f664f6ad5.png)

#### 2. AskingQuestionsSample
Bug: In the `help` LG template, the number should be `01-07` instead of `01-04`

![image](https://user-images.githubusercontent.com/32497439/70668783-614e9c00-1c29-11ea-98d0-1118a022ed94.png)

#### 3. InterruptionSample
Bug: the LG templates with suggestions do not work as expected. 

`- Hello, I'm the interruption demo bot! \n \[Suggestions=Get started | Reset profile]`

Tested in Emulator: 
![image](https://user-images.githubusercontent.com/32497439/70669012-049fb100-1c2a-11ea-82ef-177de461112d.png)

Expected behavior: 
Should have real suggested options displayed as buttons. 

#### 4. RespondingWithTextSample 
Bug: Choose `1. SimpleText` and `3. TextWithLG` output same result because `SimpleText` references `TextWithLG` template. What does `TextWithLG` mean? Does it mean `LGComposition`? It is confusing. 

![image](https://user-images.githubusercontent.com/32497439/70669321-dff80900-1c2a-11ea-8e27-8d0eee13a659.png)

Proposed solution: 
Delete `TextWithLG` template and define `SimpleText` template as follows: 
```
# SimpleText
- Hi, this is simple text
- Hey, this is simple text
- Hello, this is simple text
```
This definition is to show that any defined simple text in this template will be picked by random.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1735
