### ISSUE TITLE
Publish | UX for Deploy/publish should show screenshot  vs Movie/animation

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1764]
To prevent confusion (the user may think it is a hosted Terminal).
Please use a screenshot instead.

![Screen Shot 2019-12-11 at 2 27 48 PM](https://user-images.githubusercontent.com/48503434/70672378-e63eb300-1c33-11ea-9832-1fddfb4ad0b4.png)
![Screen Shot 2019-12-11 at 2 31 45 PM](https://user-images.githubusercontent.com/48503434/70672381-e8a10d00-1c33-11ea-9d9c-68889f944564.png)

**Comment by benbrown** [comment]
Fix has been merged!
