### ISSUE TITLE
UX | Create speech-command dialog type (enable Tahiti requirements)

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1769]
![Screen Shot 2019-11-20 at 2 20 43 PM](https://user-images.githubusercontent.com/48503434/70752522-a6d19e80-1ce7-11ea-881e-b9012fb43807.png)
Screen Shot 2019-11-20 at 2.21.00 PM

https://www.figma.com/file/FD66GJlnSmsyV4uDzSRTpu/Custom-Commands

**Comment by cwhitten** [comment]
I don't believe this is in scope any longer. Will close and add a new tracking item when appropriate.
