### ISSUE TITLE
Schema Driven Visual Editor

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#1770]
**Description**
Visual Editor and Form Editor are both visualization libs for AdaptiveDialog schema, they work on the same abstraction level.

In Form Editor, we have an [`uischema.ts`](https://github.com/microsoft/BotFramework-Composer/blob/stable/Composer/packages/extensions/obiformeditor/src/schema/uischema.ts) file in which render process is defined by a json.
![image](https://user-images.githubusercontent.com/8528761/70773846-82db8f00-1db3-11ea-8819-13533f29ccd1.png)

We should also have a schema definition file in Visual Editor. Then we can possibily
1. define multiple versions of schema to support different SDK versions' rendering
2. let users define their own ui elements for customization

**Interface**
Ideally, a semantic Visual Editor could be used like this
```ts
import  { uischema } from '@bfc/schema/4.7.0'

const customizedSchema = { ...uischema, ...myshema };

const render = () => {
    return (
        <VisualEditor
               data={data}
               schema={customizedSchema}
         />
    );
}
```
## PR plan
- [x] **stage 1** (merged #1811 ) - support basic rendering with uischema definition
    - set up `uischema` definition & implement a generic renderer based on `uischema`
    - covered $types: 15 simple $types, such as `LogAction`
- [ ] stage 2 - support complicated content rendering
    - extract more widget to support complicated node content
    - covered $types: `SendActivity`, `ReplaceDialog`, `BeginDialog`
- [ ] stage 3 - support multiple nodes rendering
    - implement a InputWidget which looks like current `BaseInput`
    - covered $types: all input $types, such as `TextInput`, `NumberInput` (but exclude `OauthInput`)
- [ ] stage 4 - support nested uischema definition
    - extend 'uischema''s definition to support rendering nested $types such as `IfConditon, Foreach`
    - covered $types: branching - `IfCondtion`, `SwitchConditon`; loop - `Foreach`, `ForeachPage`;

**Comment by yeze322** [comment]
@cwhitten this is the 'schema driven' topic we talked today

**Comment by yeze322** [comment]
In FormEditor, uischema contains several types of elements:
1. `ui:widget`
2. `ui:field`
3. `ui:order`
4. `ui:hidden`
4. `ui:options`

1 & 2 define what a SDK type looks like; 3,4,5 provide us convenience to config the form.
___
In Visual Editor, we will build something similar with FormEditor. Here is an example on 'SendActivity'.


```ts
const FormCard = (title, content, menu) => <div>{title}{content}{menu}</div>;
const AdaptiveTitle = data => ConceptLabels[data.$type].title;
const LgField= value = > <LgContent value={value} />

const uischema = {
  [SDKTypes.SendActivity]: {
    'ui:widget': FormCard,
    'ui:theme': <a group of styles>,
    title: AdaptiveTitle,
    content: data => <LgField value={data.activity} />,
  }
}
```
It will produce a node like this:
![image](https://user-images.githubusercontent.com/8528761/70982559-2bf6f200-20f2-11ea-8299-fbd72b4619de.png)

**Comment by yeze322** [comment]
Another example on `IfCondition`.
```ts
const uischema = {
  [SDKTypes.IfCondition]: {
    'ui:widget': IfCondition,
    condition: {
      'ui:widget': FormCard,
      title: 'Condition',
      content: data => data.condition,
    }
  }
}
```

**Comment by yeze322** [comment]
@cwhitten @a-b-r-o-w-n do you have suggestions on the schema format?

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/1811

**Comment by yeze322** [comment]
## PR plan
- [x] **stage 1** (in PR) - support basic rendering with uischema definition
    - set up `uischema` definition & implement a generic renderer based on `uischema`
    - covered $types: 15 simple $types, such as `LogAction`
- [ ] stage 2 - support complicated content rendering
    - extract more widget to support complicated node content
    - covered $types: `SendActivity`, `CallDialog, `BeginDialog`
- [ ] stage 3 - support multiple nodes rendering
    - implement a InputWidget which looks like current `BaseInput`
    - covered $types: all input $types, such as `TextInput`, `NumberInput` (but exclude `OauthInput`)
- [ ] stage 4 - support nested uischema definition
    - extend 'uischema''s definition to support rendering nested $types such as `IfConditon, Foreach`
    - covered $types: branching - `IfCondtion`, `SwitchConditon`; loop - `Foreach`, `ForeachPage`;

**Comment by yeze322** [comment]
closed by
- #1811 (migrated 14 simple types)
- #1840 (migrated SendActivity, BeginDialog, ReplaceDialog)
- #1874 (migrated 6 Input types)
- #1899 (migrated IfCondition, SwitchCondition, Foreach, ForeachPage)
