### ISSUE TITLE
Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by ananthukrishnendu** [microsoft/BotFramework-Composer#1771]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
I have created a Pilot bot suing the template of LUIS n QNA.When i ask the questions, the bot showing "Value cannot be null.
Parameter name: source".I cannot trace the bug also/can't identify the root cause.
<img width="960" alt="error" src="https://user-images.githubusercontent.com/29114062/70799089-afe96b00-1dce-11ea-90ae-1af0faeb331f.PNG">

## Version
4.6.0-preview2

## Browser
chrome

## OS 
windows 10

## To Reproduce
1.select the template [luis+qna].
2.train a scenario
3.run the bot using bot framework emulator
4.getting the error by asking the question after "welcome"

## Expected behavior
Need to get the utterance based on the intent.

**Comment by luhan2017** [comment]
Could you try to query your QnAKnowledge Base directly to see whether your answer contains a "source" field? it seems like you are missing the source field in the result. 

A sample looks like this:
{
    "answers": [
        {
            "questions": [
                "What is a Skill",
                "how can i book a meeting"
            ],
            "answer": "Bot Framework Skills are capabilities that can be integrated with a Virtual Assistant.\nLearn more by visiting [here](https://aka.ms/virtualassistant).",
            "score": 100,
            "id": 2,
            "source": "custom editorial",
            "metadata": [],
            "context": {
                "isContextOnly": false,
                "prompts": []
            }
        }
    ],
    "debugInfo": null,
    "activeLearningEnabled": true
}
