### ISSUE TITLE
Versioning Support for Bots (Git)

### ISSUE THREAD

**Issue by ppaltmann** [microsoft/BotFramework-Composer#1772]
**Is your feature request related to a problem? Please describe.**
Currently when building / testing bot development with the composer I don't have a visual UI element to "commit" a current version of my bot. I would need to go to the local file system and put my bot under version control. 

**Describe the solution you'd like**

_Normal User_

* An option in composer to "commit" a certain version of my bot including a descriptive message. 
* Restore a old version but keep the current worked version "stashed". 

_Advanced User_
Kind of [SourceTree](https://www.sourcetreeapp.com/) like view which files are changed etc. on a more developer centric level. 

**Describe alternatives you've considered**
A simple button to open the current bot in the command line to commit the changes. For most user this would be not the right way as that would be to complicated but for devs ok.

**Comment by cwhitten** [comment]
Hello @ppaltmann ! Thanks for opening the issue. We are currently working on an extension/plugin protocol that would allow this type of feature to be built. When we have the design ready to share we can update this and get your feedback.
