### ISSUE TITLE
Dialog hamburger menu button not shown when hovering over dialog name

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#1774]
The hamburger menu button against a dialog is only shown if you hover over the far right of the Dialog Name. If you hover over the name itself the button is not visible, which makes discoverability hard.  

Please excuse the photos - I tried to take a screenshot, but it didn't capture the cursor! :)

![composer_delete_button](https://user-images.githubusercontent.com/3900649/70826305-76206080-1dde-11ea-9dfb-97986b8183ed.jpg)
![composer_no_delete_button](https://user-images.githubusercontent.com/3900649/70826307-76206080-1dde-11ea-9ce8-eef269f56c22.jpg)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2331
