### ISSUE TITLE
packages/server/package.json can't be installed successfully stand alone

### ISSUE THREAD

**Issue by hailiu2586** [microsoft/BotFramework-Composer#1778]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
see title

To repro, run "npm install --production" on package.json from  packages/server. This will have install ed incomplete dependencies because there are missing dependency entries from various lib modules such as @bfc/lg-languageserver.

For shared code, if 'node/no-extraneous-import' rules is turned on. Then those missing dependency would have been caught by 'yarn lint'

**Comment by cwhitten** [comment]
@hailiu2586 we'd prefer if you did not install the server standalone. @a-b-r-o-w-n and @christopheranderson plan to chat with you about an alternative approach.
