### ISSUE TITLE
We need to be able to tell the user that we are busy with SendActivity of type "typing"

### ISSUE THREAD

**Issue by eduardmartos** [microsoft/BotFramework-Composer#1781]
**Is your feature request related to a problem? Please describe.**
We do not know how to adapt the Bot template generated by Bot composer so that in each action that the Bot performs, a method that sends the typing message event can be called.
We try this on **ComposerBot.cs**:

```
 public override async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
        {
            **await turnContext.ShowTypingIndicator(100);**

```
But it seems that is not working when one if the actions is busy (for example an Http get request).

**Describe the solution you'd like**
We believe that best solution would be to have a method that we could overwrite in the core of the composer, so that each time it was to process an action, this method would be called first. In it we could add "typing" by code.

**Describe alternatives you've considered**
Another alternative was having an especial Emit Event named "Bot Is Typing" or similar.

**Additional context**

**Comment by cwhitten** [comment]
Hi @eduardmartos and thanks for the issue. We'll be in touch with what we think is a workaround to achieve this. Stay tuned!

**Comment by luhan2017** [comment]
@eduardmartos , could you please try this? 
You can add a ShowTypingMiddleware in Startup.cs->ConfigServices
like this:  services.AddSingleton<ShowTypingMiddleware>();
add then adapter.Use(showTypingMiddleware) in the Adapter.

Please let me know if you have more questions on this.

**Comment by eduardmartos** [comment]
> @eduardmartos , could you please try this?
> You can add a ShowTypingMiddleware in Startup.cs->ConfigServices
> like this: services.AddSingleton();
> add then adapter.Use(showTypingMiddleware) in the Adapter.
> 
> Please let me know if you have more questions on this.

Amazing luhan2017!

I removed my extension on ComposerBot.OnTurnAsync() "await turnContext.ShowTypingIndicator(1);" and following your instructions:

[StartUp.cs]

 ...
 public void ConfigureServices(IServiceCollection services)
 {
	...
	services.AddSingleton<InspectionMiddleware>();
	services.AddSingleton<ShowTypingMiddleware>(); // <- Added this line
	...
	
 services.AddSingleton<IBotFrameworkHttpAdapter, BotFrameworkHttpAdapter>((s) =>
 {
	...
	.Use(new InspectionMiddleware(inspectionState, userState, conversationState, credentials))
    .Use(new ShowTypingMiddleware()); // <- Added this line
	...
	
...

And that's fine! It seems to work perfect!
