### ISSUE TITLE
yarn problem

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [microsoft/BotFramework-Composer#1782]
When I try to build the Project with "yarn install", I get the following error:

```
$ yarn build
yarn run v1.21.1
error Couldn't find a package.json file in "C:\\Users\\NAME\\OneDrive - XY AG\\Documents\\Visual Studio 2019\\Source\\BotFramework-Composer"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried "yarn Cache clean", but Nothing helped under Windows.

Does anybody has the same Problems?

**Comment by a-b-r-o-w-n** [comment]
Hi @andreas-sommer-engenious! It looks like you have run a `yarn` command in the repository root directory. Try running those commands in the `Composer` directory. 

See https://github.com/microsoft/BotFramework-Composer#get-started for more information.

**Comment by andreas-sommer-engenious** [comment]
Sorry. Next Problem:
 husky
error C:\Users\SOMMERA\OneDrive - EnBW AG\Documents\Visual Studio 2019\Source\BotFramework-Composer\Composer\node_modules\cypress: Command
failed.
Exit code: 1

Is the node.js Version too new?
Tanks again
