### ISSUE TITLE
[Linting & Validation] expression fields in arrays do not get validated

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#1783]
For instance, `DeleteProperties.items.property` does not get validated as an expression.

**Comment by a-b-r-o-w-n** [comment]
Upon some investigation, the function `getExpressionProperties` does not get all of the properties that need to be validated as expressions so these are not getting picked up.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1798
