### ISSUE TITLE
Yarn error when installing the dependencies

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [microsoft/BotFramework-Composer#1795]
Hi,
When I try to install all dependencies via yarn, I get the following Husky error:

$ yarn install
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
warning monaco-languageclient@0.10.2: The engine "vscode" appears to be invalid.
warning vscode-languageclient@5.3.0-next.9: The engine "vscode" appears to be invalid.
[4/5] Linking dependencies...
warning " > @cypress/webpack-preprocessor@4.1.1" has unmet peer dependency "webpack@^4.18.1".
warning "@cypress/webpack-preprocessor > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
warning "jest > jest-cli > @jest/core > jest-resolve-dependencies@24.5.0" has unmet peer dependency "jest-resolve@^24.1.0".
warning "jest > jest-cli > jest-config > jest-resolve@24.5.0" has unmet peer dependency "jest-haste-map@^24.0.0".
warning " > react-testing-library@6.1.2" has unmet peer dependency "react@*".
warning " > react-testing-library@6.1.2" has unmet peer dependency "react-dom@*".
warning " > @bfc/obiformeditor@1.0.0" has unmet peer dependency "react@16.9.0".
warning " > @bfc/obiformeditor@1.0.0" has unmet peer dependency "react-dom@16.9.0".
warning " > @bfc/visual-designer@1.0.0" has unmet peer dependency "react@16.x".
warning " > @bfc/code-editor@0.0.0" has unmet peer dependency "react@16.9.0".
warning " > @bfc/code-editor@0.0.0" has unmet peer dependency "react-dom@16.9.0".
warning " > @bfc/shared@0.0.0" has unmet peer dependency "format-message@^6.2.1".
warning " > @bfc/shared@0.0.0" has unmet peer dependency "react@16.9.0".
warning " > @bfc/shared@0.0.0" has unmet peer dependency "react-dom@16.9.0".
warning "workspace-aggregator-397caff4-e9f9-4083-9346-c6c8898deb94 > @bfc/client > eslint-config-react-app@3.0.8" has incorrect peer dependenc
y "eslint@5.x".
warning "workspace-aggregator-397caff4-e9f9-4083-9346-c6c8898deb94 > @bfc/client > eslint-config-react-app@3.0.8" has unmet peer dependency "e
slint-plugin-flowtype@2.x".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
[1/6] ⡀ core-js-pure
[2/6] ⡀ cypress
[3/6] ⡀ core-js-pure
**[4/6] ⡀ husky
error C:\Users\NAME\OneDrive - XY\Documents\Visual Studio 2019\Source\BotFramework-Composer\Composer\node_modules\cypress: Command fai
led.
Exit code: 1
Command: node index.js --exec install
Arguments:**

Is the node.js Version wrong? Any ideas?

**Comment by boydc2014** [comment]
Hi, @andreas-sommer-engenious can you share which version of OS and Node you are in?

**Comment by andreas-sommer-engenious** [comment]
I work with Windows 10 and Node Version 12.13.1
Thanks

**Comment by andreas-sommer-engenious** [comment]
It's funny, with another Windows 10 compoter it works. Maybe the path ist too long?

**Comment by boydc2014** [comment]
> It's funny, with another Windows 10 compoter it works. Maybe the path ist too long?

em.. it's definitely possible, let me see what i can do
