### ISSUE TITLE
Interruption sample runtime error

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1802]
## Describe the bug
InterruptionSample `Start/Restart` generates runtime error. 

## To Reproduce
1. Load InterruptionSample
2. Click on `Start/Restart` 
3. Fill in LUIS authoring key
4. See the runtime error

## Screenshots
![image](https://user-images.githubusercontent.com/32497439/71386672-31e24c80-25a4-11ea-8c40-01b3666e4709.png)

## Additional context
1. Click `Try again` did not solve the issue. 
2. This error only happens with InterruptionSample.

**Comment by hibrenda** [comment]
Attached the error message , meanwhile "Getprofile" recognizer need to changed into LUIS.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
[runtime]       An unhandled exception has occurred while executing the request.
[runtime] System.Exception: C:\Repo\BFC\BotProject\CSharp\bin\Debug\netcoreapp2.1\tmp\9dd66943a9b04c559fa7f4ab1350ab31\Main\Main.dialog error: Error converting value "trim(this.value)" to type 'Microsoft.Bot.Builder.Dialogs.Adaptive.Input.TextOutputFormat'. Path 'outputFormat', line 35, position 44.
[runtime] Requested value 'trim(this.value)' was not found.

**Comment by hibrenda** [comment]
Three issues found so far. 
- "trim(this.value)" will introduce error. @zidaneymar , could you comment for runtime error ?
- outputformat is "" will introduce runtime error as well. (user edit something in outputformat and then delete what has been input. so "outputformat" will be "" and these will be write back to the dialog file.) @lei9444 @boydc2014  Could shellapi handle such validation before runtime loaded it ?
- Properties auto-correction. If user switch to other bot, and reload current bot again, 'outputformat:""  ' will be still there. but when you click on the dialog, the 'outputformat:""  ' will be deleted from dialog as form will auto correct the unformed data. so we need to improve the user experience. It is not consistent. (eg. bot load , dialog load, start bot...) If shellapi could handle the validation and auto-correction, these would be easier. ? @a-b-r-o-w-n @cwhitten @boydc2014

**Comment by zidaneymar** [comment]
The latest SDK version doesn't have this issue, update the package version will fix this issue.
