### ISSUE TITLE
Using 'ctrl+z' multiple times all LG content disappear

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1803]
## Describe the bug
I was editing LG in the all-up view. After using 'ctrl+z' multiple times all LG content will disappear and seems cannot restore. 

## To Reproduce
1. Go to `Bot Responses`
2. Click on any place in the LG all-up view
3. Use 'ctrl+z' several times in a row then all LG content is gone.

## Expected behavior
Should not make content gone even with continuous use of `ctrl+z`. 

## Screenshots
https://share.getcloudapp.com/WnuEBA4Z

## Additional context
I have this terrible habit of using 'ctrl+z' multiple times. Users with better behavior may not encounter this issue at all, but losing all my previously-edited LG template and cannot restore them is really a sad story. 

Different samples behavior differently on this bug.

**Comment by zhixzhan** [comment]
addressed in #1804
