### ISSUE TITLE
Problem with running Composer created project from VS2017

### ISSUE THREAD

**Issue by vovanb** [microsoft/BotFramework-Composer#1816]
We use windows service to host bot. Before test it in windows service I decided to use Composer output in IISExpress host: I created in Composer new empty project and just added simple response on beginning, then tried to open Composer output from BotFramework-Composer\MyBots\ folder using VS 2017. It compiled correct but then when I tried to debug it in IISExpress I got below error: System.InvalidOperationException: 'Could not find 'UserSecretsIdAttribute' on assembly 'BotProject'. Check that the project for 'BotProject' has set the 'UserSecretsId' build property. – 

## Version
4.6.0-preview2

Windows

## To Reproduce
1. Create new Empty project in composer
2. Test it in Emulator
3. Open new project VS2017
4. Compile and execute
5. Will be exception :
System.InvalidOperationException: 'Could not find 'UserSecretsIdAttribute' on assembly 'BotProject'. Check that the project for 'BotProject' has set the 'UserSecretsId' build property.

## Screenshots
![CompserBug](https://user-images.githubusercontent.com/6763621/71574159-3486f980-2af0-11ea-823a-f68ca32f74a3.PNG)

**Comment by hibrenda** [comment]
@vovanb Thanks for the suggestions. At this moment, the bot runtime created under each bot folder could not be executed as many resources have not been included. eg. bot assets - SecretsId and also other assets - luis related.  Could you share the requirements why you are using VS instead of composer run ?

**Comment by vovanb** [comment]
@hibrenda below number of reasons:
1. I want to add storing state into MS SQL Data 
2. I want to deploy Bot to be running from on-premise server and not from Azure and hosted in IIS
3. I want to add custom c# libraries we need to interact from Bot (not https API) 
So idea is to use Composer to create Dialogs Flow and then use VS2017 to modify/add libraries as we usually doing in c# SDK.

**Comment by hibrenda** [comment]
@vovanb Thanks for sharing the requirements. Yes. Bring your own bot runtime is on our roadmap. After #1672 PR integrated, you can do it much easier.

**Comment by hibrenda** [comment]
@vovanb this issue has been solved, please sync with latest updates.

If your bot is using luis, please make sure do following steps before run by VS.
- create bot by composer
- click "start bot" button 
- open your bot in vs
- update the luis setting in "Composer\...\<bot>\ComposerDialogs\settings\appsettings.json as following 
![image](https://user-images.githubusercontent.com/43408889/73747681-ea4e0380-4792-11ea-9137-f5121e6ad299.png)
- If you did not use westus, please follow the format "https://{region}.api.cognitive.microsoft.com/", and reference https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-regions for region setting.
