### ISSUE TITLE
Default Greeting trigger contains loop and branch code

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1821]
## Describe the bug
After creating an empty bot from scratch, the default `Greeting` trigger contains loop and branch code. Is this by design? 

## Version
Most recent version. Fetched most recent master branch. 

## To Reproduce
1. Create an Empty Bot. 
2. Click on 'Greeting'
3. See the code 

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.
![image](https://user-images.githubusercontent.com/32497439/71686360-d6f0e800-2d4f-11ea-846e-ad5816a7aa70.png)

**Comment by hibrenda** [comment]
@zxyanliu Yes. This is by design and introduced by #1794 . The user experience for greeting does not change.

**Comment by zxyanliu** [comment]
@hibrenda thanks for your reply! This is coool! Closing the issue now.
