### ISSUE TITLE
Small bug in Set properties description

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1822]
## Describe the bug
In the **Properties panel** of `Set properties` action, the description shows `delete properties`.

## Expected behavior
The description should show `set properties`. 

## Screenshot
![image](https://user-images.githubusercontent.com/32497439/71687971-d6f2e700-2d53-11ea-8f99-49da48f94ee5.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1798
