### ISSUE TITLE
Toggling LG all-up view shows an error message

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1827]
## Describe the bug
Toggle `Edit Mode` in LG all-up view shows the error message "`Something went wrong`". 

## To Reproduce
1. Go to `Bot responses`
2. Toggle `Edit Mode`
3. See an error message

## Screenshots
![issue](https://user-images.githubusercontent.com/32497439/71847630-34ec3b00-3082-11ea-9b98-9fc0f708b98f.gif)

## Expected
Should not show an error message. 

## Additional information 
1. It's just an error message, and it does not generate any error. 
2. LU all-up view does not have this problem.

**Comment by zhixzhan** [comment]
Hi @zxyanliu, can you provide some error log from command line prompt? I can't reproduce at my local environment, but in this case seems the server is down. 
And can you try another sample bot, it help clarify the bug is from code or bot file.

**Comment by zxyanliu** [comment]
Hi @zhixzhan, I think it's a bug from the bot file. Unfortunately, I cannot reproduce it either. I am closing this issue for now and will reopen it if I see the same bug again. You are right, I tried different sample bots and did not find the bug.
