### ISSUE TITLE
Allow Composer to send a HTTP request using non-json body

### ISSUE THREAD

**Issue by jamesemann** [microsoft/BotFramework-Composer#1829]
#### Background

I'd like to be able to HTTP POST non-json data. Right now I am constrained to json-only.  

As an example I'd like to POST `application/x-www-form-urlencoded` to request an access token from Azure AD.

Currently the validation stops me from saving this:

![image](https://user-images.githubusercontent.com/6830648/71909082-27f54780-3167-11ea-8071-5ea364d5d07a.png)

Ideally, this would save without validating the input and make it the responsibility of the person composing the conversation to get it right.  Alternatively, if it is necessary to validate, have a dropdown to select the `Content-Type` similarly to postman/fiddler where you can choose from `form-data`, `x-www-form-urlencoded`, `json`, `raw`.

#### Current workaround

I am working around this by proxying the request to Azure AD with a custom API which accepts json input and the Composer/ Adaptive Dialog can connect through to.

**Comment by cwhitten** [comment]
To fixer: we need allow the user to select a body type `raw`, `form-data`, and `x-www-formurlencoded`. `form-data` and `x-www-formurlencoded` need the use the key:value controls.

Prior to fixing in Composer we need to verify the HttpAction supports these.

**Comment by sangwoohaan** [comment]
Design : https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=3930%3A130

**Comment by luhan2017** [comment]
In SDK, there is a StringExpression property called contentType, and its default value is application/json.

@jamesemann Can you work around this by the following?
1. use string type, which you can input everything, we don't really validate.
2. set your contentType to form-data

An example:
![image](https://user-images.githubusercontent.com/32191031/81366580-99e19b80-911d-11ea-937c-26efe4ecb663.png)

**Comment by samaroj** [comment]
> 
> #### Background
> 
> I'd like to be able to HTTP POST non-json data. Right now I am constrained to json-only.
> 
> As an example I'd like to POST `application/x-www-form-urlencoded` to request an access token from Azure AD.
> 
> Currently the validation stops me from saving this:
> 
> ![image](https://user-images.githubusercontent.com/6830648/71909082-27f54780-3167-11ea-8071-5ea364d5d07a.png)
> 
> Ideally, this would save without validating the input and make it the responsibility of the person composing the conversation to get it right. Alternatively, if it is necessary to validate, have a dropdown to select the `Content-Type` similarly to postman/fiddler where you can choose from `form-data`, `x-www-form-urlencoded`, `json`, `raw`.
> #### Current workaround
> 
> I am working around this by proxying the request to Azure AD with a custom API which accepts json input and the Composer/ Adaptive Dialog can connect through to.

do you have a step by step of your current workaround? mine doesn't work. Thank you.

**Comment by cxbuilders** [comment]
I am also not able to make a post request using content type: application/x-www-form-urlencoded
I have tried Json Body and the string body in the style of client_id=23232323&client_secret=1212121212

When using the string body style it gives an error Parent is missing, when using Json body style, the result is simply a 403 as it can't see the data coming in. How to do this?

**Comment by samaroj** [comment]
> I am also not able to make a post request using content type: application/x-www-form-urlencoded
> I have tried Json Body and the string body in the style of client_id=23232323&client_secret=1212121212
> 
> When using the string body style it gives an error Parent is missing, when using Json body style, the result is simply a 403 as it can't see the data coming in. How to do this?

Hi @cxbuilders , remove the **application/x-www-form-urlencoded** in the Headers and put the **application/x-www-form-urlencoded** on the Content type textbox.

**Comment by cxbuilders** [comment]
@samaroj That's exactly what I have;
![image](https://user-images.githubusercontent.com/49873947/86788372-61e7cd80-c066-11ea-88c0-2be8d0adb691.png)

**Comment by samaroj** [comment]
@cxbuilders by the way what bot framework composer version are you using now?

**Comment by cxbuilders** [comment]
@samaroj f9128fbd

**Comment by luhan2017** [comment]
SDK had a fix on this https://github.com/microsoft/botbuilder-dotnet/pull/4064, but composer didn't take that yet.
You could 
1. Eject your runtime.
2. Go to the runtime location, and update the packages to the nightly build which includes this fix.

**Comment by cxbuilders** [comment]
@luhan2017 is there a planned date when you will use the SDK with that fix?

**Comment by luhan2017** [comment]
@cxbuilders I think we will update the sdk package within 2 weeks, there are some important new features depending on the new sdk. will that work for you?

**Comment by cxbuilders** [comment]
@luhan2017 Yes, that works for me, can use a workaround in the meanwhile. Thanks!

**Comment by mg-arrow** [comment]
I have exactly the same issue with POST using application/x-www-form-urlencoded format. I am running Bot Composer 1.0.2 and SDK 4.9.3.

I've tried various suggestions listed above and none seems to work.

How can I use the nightly build of the SDK ?

Any other suggestions ?

**Comment by mg-arrow** [comment]
Any updates on new version of the composer, which can resolve the issue ?

I've tried all suggestions but none worked for me. See message above.

Thanks

**Comment by luhan2017** [comment]
You could
1. Eject your runtime.
2. Go to the runtime location, replace "4.9.3" with "4.10.0-daily.20200731.152444", please note that the Debug package is 4.9.3-preview. you also need to update it with"4.10.0-daily.20200731.152444" without a preview suffix.

**Comment by mg-arrow** [comment]
I tried your suggestion but Eject Run Time gives an error, when I select C#

Runtime already exists at C:\...\chatbot\ChatbotPocWithLuisAndQnmaker\runtime

Also, how do I download and install version 4.10.0-daily.20200731.152444 ?

Thanks

**Comment by luhan2017** [comment]
@mg-arrow sorry for the late response, composer already updated the sdk package to 4.10.0, you can try with the latest main branch.

**Comment by karloberas** [comment]
Need help on this, I'm unable to send form-data in the body of my HTTP request. The server does not receive the body content.

I tried with object
![image](https://user-images.githubusercontent.com/7484848/93572177-0ae86800-f9c8-11ea-8332-37fbcf7f39c4.png)

and with string
![image](https://user-images.githubusercontent.com/7484848/93572387-5c90f280-f9c8-11ea-9b39-a0de68be0c14.png)

on both cases, the server could not process the request body

My Bot Composer SDK is 4,10.2

**Comment by fallintoplace** [comment]
Does anyone know how to get this body of type "multipart/form-data" to work in Bot Composer? I have tried so many combinations but couldn't get this to work. And I couldn't find any suitable answer either.
![curl_form_data](https://user-images.githubusercontent.com/38443830/105569263-9a1fd680-5d40-11eb-9e44-50f499c441c7.PNG)
![form_data](https://user-images.githubusercontent.com/38443830/105569241-56c56800-5d40-11eb-8ebb-8e6f2e20326b.PNG)
