### ISSUE TITLE
Repeat this dialog node visual disappeared

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1831]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
When you add a Repeat this dialog node, it would add a unclickable blank space instead of an action node.

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [O ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce
Create a Repeat this dialog node anywhere.

## Screenshots
![Screen Shot 2020-01-07 at 1 20 08 PM](https://user-images.githubusercontent.com/50963385/71934419-3c324800-3159-11ea-8ca1-52193b25540e.png)

**Comment by yeze322** [comment]
in pr

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1835
