### ISSUE TITLE
Manage LUIS intents in Hierarchy way with multiple LUIS sources?

### ISSUE THREAD

**Issue by JonathanHades** [microsoft/BotFramework-Composer#1838]
Hello all, 
After I added a trigger to the main with LUIS as recognizer, I added another trigger with another LUIS source. I wonder if it's possibile to fire the second trigger in a way the second source of LUIS returns the intents specifics for the dialogue.
EX.
FIRST LUIS
Where is the shopping mall?
Intents
Info about mall
SECOND LUIS
Where is the shopping mall?
Intents 
Position mall

In this way i can delegate to the luis the task to guess the specific intent of the user. But the composer doesn't send the question after passing the first source of luis.

is there a way to achive this? and is it an ideal approach?

thank you.

**Comment by hibrenda** [comment]
Hi @JonathanHades , Could you provide the dialog assets for us ?

**Comment by JonathanHades** [comment]
Hello @hibrenda what mean exactly for the dialog assets?
Anyway to better understand my question i put below the scheme of the dialog.

In few words I would want take advantage of the luis to get the first intent and then resend the same question to another luis specific for a matter like general info about the shopping mall and then get a second intent between for example where and when. So the bot can give the right responses without asking any further questions.


.Main
LUIS Meta Language
# Info
> position of the mall, timetables
- where is the shopping mall?
- when the shopping mall opens?
# Shops
> Shops of the mall
- what are the shops of the mall?
- what are the electronics shops of the mall?
INFO.Dialog
LUIS Meta Language
# MallPosition
- where is the shopping mall?
# MallTimetable
- when the shopping mall opens?

User question:
Where is the shopping mall?
intent recognized by Luis:
#Info 
- INFO.Dialog started
second intent recognized by Luis:
# MallPosition
- INFOPOSITION.Dialog started
Bot response:
To get to the mall take the route 33 untill you get to the roundabout...

**Comment by luhan2017** [comment]
@JonathanHades There is an "activityProcessed" feature in SDK which is not integrated in Composer yet. when Begin a new Dialog you can you can set activityProcessed=true/false to determine whether the utterance need to be processed by the sub-dialog. Here is the example:

```C# 
var rootDialog = new AdaptiveDialog()
{
    AutoEndDialog = false,
    Recognizer = new RegexRecognizer()
    {
        Intents = new List<IntentPattern>()
        {
            new IntentPattern()
            {
                Intent = "mallIntent",
                Pattern = "where is the shopping mall"
            }
        }
    },
    Triggers = new List<OnCondition>() 
    {
        new OnBeginDialog() 
        {
            Actions = new List<Dialog>() 
            {
                new SendActivity("What can I do for you?")                
            }
        },
        new OnIntent()
        {
            Intent = "mallIntent",
            Actions = new List<Dialog>()
            {
                new BeginDialog()
                {
                    activityProcessed=false,
                    Dialog = new AdaptiveDialog()
                    {
                        AutoEndDialog = false,
                        Recognizer = new RegexRecognizer()
                        {
                            Intents = new List<IntentPattern>()
                            {
                                new IntentPattern()
                                {
                                    Intent = "mallPosition",
                                    Pattern = "where is the shopping mall"
                                }
                            }
                        },
                        Triggers = new List<OnCondition>()
                        {
                            new OnIntent()
                            {
                                Intent = "mallPosition",
                                Actions = new List<Dialog>()
                                {
                                    new SendActivity("To get to the mall take the route 33 untill you get to the roundabout...")
                                }
                            },
                            new OnUnknownIntent()
                            {
                                Actions = new List<Dialog>()
                                {
                                    new SendActivity("you are in sub-dialog's on unknownIntent")
                                }
                            }
                        }
                    }
                }
            }
        }
    }
};
```

**Comment by hibrenda** [comment]
Thanks @luhan2017  for the detailed explanation. @JonathanHades Just like mentioned above, composer will enable this feature soon. There will be an UI implementation to set this property for "Begin a new Dialog" step. Then you can easily try this feature through the composer.

**Comment by JonathanHades** [comment]
thanks for the explanation, yes I think that's would resolved the issue.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1996
