### ISSUE TITLE
Documentation: DescribeWeather template format is wrong, missing @'s

### ISSUE THREAD

**Issue by dinobrago** [microsoft/BotFramework-Composer#1839]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
In the Composer tutorial, https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial/bot-tutorial-lg.md, the tutorial has you create a new template to demonstrate conditional messages, and parameterized messages.

## Version
docs: R7 Doc Release (#1743)

## To Reproduce
On step 8, the tutorial says to paste the following text:
`# DescribeWeather(weather)`
`- IF: {weather.weather=="Clouds"}`
`    - It is cloudy`

This generates a set of errors: if and elseif should [sic] followed by one valid expression

## Expected behavior
See the tutorial, should be accepted in the LG editor

The syntax should be:
`# DescribeWeather(weather)`
`- IF: @{weather.weather=="Clouds"}`
`    - It is cloudy`

**Comment by zxyanliu** [comment]
Hi @dinobrago Thanks for reporting the bug. You are right, the `@` is missing in this lg template. We have updated a couple of more in [this branch](https://github.com/microsoft/BotFramework-Composer/tree/kaiqb/composer-review). The updated docs will be available soon.

**Comment by zxyanliu** [comment]
Hey, thanks again for your report. We have updated the docs [here](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/tutorial/tutorial-lg.md). Closing this issue because it is addressed.

**Comment by aalmada** [comment]
I was following the Weather tutorial and got stuck on ['Get weather report'](https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial/bot-tutorial-get-weather.md). The HTTP request doesn't work and all the error messages show the property names instead of the values because of the missing `@`.
Documentation needs to be updated in many more places...

**Comment by zxyanliu** [comment]
Hey @aalmada thanks for your report. FYI. The updated docs are actually in master branch [here](https://github.com/microsoft/BotFramework-Composer/blob/master/toc.md).

**Comment by aalmada** [comment]
@zxyanliu Thanks! I missed that your previous link was pointing to `master`. GitHub defaults to `stable` so it will be confusing for most people.
