### ISSUE TITLE
Multiple choice option does not respect undo/redo

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-Composer#1842]
## Describe the bug
Multiple choice option does switch between dynamic and static choices in multiple choice prompt.

## Browser
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Add Multiple Choice prompt to bot
1. Navigate to 'User Input' in the Form Editor
1. Add choice options
1. Change the type from `static` to `dynamic`
1. Hit undo/redo buttons

## Screenshots
![undo](https://user-images.githubusercontent.com/17039790/72090098-30ae6080-32c2-11ea-9e9d-6e35e10c8b03.gif)

**Comment by cwhitten** [comment]
closed via https://github.com/microsoft/BotFramework-Composer/pull/1844
