### ISSUE TITLE
[Inline LU] Create user inputs with utterance in form when creating inputs 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1848]
**Describe the solution you'd like**
- similar editing experience for intent with utterance when creating triggers
- dialog/bot level setting for merging sections
- Inputs includes Text, Number, Confirm, DateTime and MultiChoice.

**Comment by boydc2014** [comment]
Hi @hibrenda 

I was discussing the issues remaining in managed-lu with @cwhitten . That a proper split up of tasks in the hoisting experience of Lg  is two tasks
1. let @alanlong9278 to work on the data flow (using shell api of LU) of hoisting Lu in Form, the deliverable of this one is a working version of hoisted lu editors in Form. But without any intelligence. 
2. then @tdurnford can take from there to make LU LSP working in a `inline` mode.  This will involve updating the payload in the LSP protocol and add handlers and some mechanism similar to LG inline mode.

**Comment by hibrenda** [comment]
@cwhitten Do I need to file another issue to track LU LSP working in a inline mode for TJ ? So this one will only cover the form inline data flow.

**Comment by liweitian** [comment]
hi, @hibrenda  @tdurnford, how is the lu inline editor going? And @cwhitten Do I still need to wait lu inline editor on this PR https://github.com/microsoft/BotFramework-Composer/issues/1848

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/2159
