### ISSUE TITLE
Save automatically the conversation on blob storage for future analysis 

### ISSUE THREAD

**Issue by JonathanHades** [microsoft/BotFramework-Composer#1849]
**Describe the solution you'd like**
It would very useful have in a settings form, the chance to enable auto save conversation of the bot in a blob storage, in order to analyze the answers of the bot for future improving.

thanks.

**Comment by cwhitten** [comment]
Thanks @JonathanFingold for the suggestion. We don't have plans to add this functionality natively in Composer any time soon, but achieving this will be possible while utilizing Composer extensions and custom runtime functionality. We're working on these items right now and will have documentation for users to reference in the coming months. I'll close this for now, thanks!
