### ISSUE TITLE
Sorry, something went wrong with publishing. Try again or exit out of this task.

### ISSUE THREAD

**Issue by v-madhal** [microsoft/BotFramework-Composer#1851]
After changing the LUIS, by adding some utterances and intents, bot composer does not publish the LUIS file and throws an error with a message **"Sorry, something went wrong with publishing. Try again or exit out of this task.**

## Describe the bug
I have three intents in my LUIS, say I1,I2 and I3. Now after adding additional utterances in any of the intents, if I click on **"Start Bot"** button on the top, it throws an error. I have ensured that the primary key of LUIS which is added in appSettings.json file is exactly same as in LUIS portal.

## Browser
What browser are you using?

- [x] Chrome
- [x] Edge

## OS 
What operating system are you using?
- [x] Windows

## Screenshots
![image](https://user-images.githubusercontent.com/52025229/72238155-f830be80-3602-11ea-9363-e06091482cd2.png)

**Comment by VanyLaw** [comment]
Hi @v-madhal, which branch do you use? we update the error display part in master branch, maybe our newest code can give you more information. Could you please try again and tell me if your problem was fixed?

**Comment by VanyLaw** [comment]
@v-madhal And you can set environment value DEBUG into composer* before run composer to see more debug messages. such like this `set DEBUG=composer* & yarn start`

**Comment by v-madhal** [comment]
@VanyLaw - I am following the steps mentioned in the documentation. [Link](https://github.com/microsoft/BotFramework-Composer/blob/stable/toc.md) . Also my initial bot (Basic bot and weather bots are working successfully) but this error I am  getting while adding additional utterances in LUIS through the bot composer.

I also tried in an alternate way to train the LUIS with newly added utterances and then just add those utterances in bot composer and start the bot. It also didn't worked.

Then I removed the additional utterances from LUIS and tried publishing the LUIS from the bot composer, there I am getting this error.

**Comment by VanyLaw** [comment]
@v-madhal Seems like it's a special luis error. Could you share your error bot that I can try to repo it.

**Comment by prasadreddybv** [comment]
Hi @v-madhal - I am facing the same issue with the Weather bot. I have created a LUIS app (weather) and this app's primary key has been configured in appsettings.json file in the Composer Bot. But while publishing i am getting Something went wrong error.

The LUIS model i have created was in the Westeurope region and i have changed it manually in the Composer settings as well. But its not publishing.Could you please help me out here if i am missing anything.

**Comment by berhen** [comment]
Hi, we have a similar problem with publishing to LUIS out of the Bot Composer, with the same error. But only if the LUIS settings in the configuration section of the Bot Composer are set to:
```
"authoringRegion": "westeurope",
"defaultLanguage": "de-de",
```
If we change the defaultLanguage to "en-us" everything works well (tried it with "fr-fr" too, no problem either).

The LUIS app gets created well, but publishing fails with the following error in node.js:
`POST /api/projects/opened/luFiles/publish 400 1550.402 ms - 39`

**Comment by InDieTasten** [comment]
I'm facing the same exact issue. en-us and fr-fr working, de-de however fails

**Comment by InDieTasten** [comment]
The bad request is as follows:

```
POST http://localhost:3000/api/projects/opened/luFiles/publish HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Content-Length: 51
Accept: application/json, text/plain, */*
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Content-Type: application/json;charset=UTF-8
Origin: http://localhost:3000
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:3000/dialogs/Main
Accept-Encoding: gzip, deflate, br
Accept-Language: de,de-DE;q=0.9,en-US;q=0.8,en;q=0.7

{"authoringKey":"<REDACTED, because my actual key>"}
```

Which yields the following HTTP response:

```
HTTP/1.1 400 Bad Request
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Content-Type: application/json; charset=utf-8
Content-Length: 110
ETag: W/"6e-VYI2EO4pFo6la9ETcRrKkFYxwd8"
Vary: Accept-Encoding
Date: Tue, 11 Feb 2020 09:31:49 GMT
Connection: keep-alive

{"message":"The application version tokenizer version must be the same as the application tokenizer version."}
```

I have no idea what this is supposed to mean ...

**Comment by VanyLaw** [comment]
I think it maybe because the utterances in lu file are not matched with the language in `defaultLanguage` field. 
I try to set as 
```
"authoringRegion": "westus",
"defaultLanguage": "de-de",
```
with all english utterances. It will throw "The application version tokenizer version must be the same as the application tokenizer version." And LUIS breaks an utterance into tokens based on culture, If utterance and defaultLanguage don't match, luis will throw error. 

FYI.
https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-language-support

**Comment by InDieTasten** [comment]
So there is no way currently to build a german LUIS recognizer bot using bot composer?

**Comment by SupriyaBhogi** [comment]
Hello everyone
![image](https://user-images.githubusercontent.com/83270427/131314922-19ed4303-13f6-47c1-add3-9218ea38bba3.png)

, i am facing one issue in bot framework composer can you pls give suggestion for this
