### ISSUE TITLE
luis resource setting should be consistent between composer run and local dotnet run

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1852]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
-  created the bot by Composer with luis
- start the bot in composer 
- open in vs2019 ,  build/run it
- test in emulator will throw "invalid rul xxx" error 

This is only happened for bot created with luis and no error for echobot.

**Comment by VanyLaw** [comment]
**Cause**: Run composer in Local will filter sensitive fields like luis.endpointKey ```, means not save those fields in the appsetting.json file. So it will throw "invalid url xxx" error in vs2019.
**Solution**: User who want to start runtime without composer should add MicrosoftAppPassword, endpointKey and endpoint back into ComposerDialog/appsetting.json 
endpoint is the url match authoringRegion. Detail in https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-regions
FYI.
![image](https://user-images.githubusercontent.com/21174180/72504407-b90ba300-3878-11ea-9996-e8b9ef2e1d93.png)
