### ISSUE TITLE
Composer crashed after clicking 'Start Bot' button.

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#1855]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
Click start bot, composer crashed.

## Version
What version of the Composer are you using? Paste the build SHA found on the about page 

master

## Browser
What browser are you using?

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce
1. Open a bot
2. Click on 'Start Bot'
3. See error

## Screenshots
![ade68d01-893f-4ab3-8cd8-36c48c209cb5](https://user-images.githubusercontent.com/39758135/72322999-a2cbde80-36e2-11ea-91c7-d3622277e735.jpg)

**Comment by VanyLaw** [comment]
fix in #1857
