### ISSUE TITLE
Composer crashes when editing dialog bot asks.

### ISSUE THREAD

**Issue by Kaipie5** [microsoft/BotFramework-Composer#1859]
Complete the necessary portions of this template and delete the rest.

## Describe the bug

If you put a blank line at the start of a bot asks then the server immediately crashes.

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

![Screen Shot 2020-01-14 at 4 34 01 PM](https://user-images.githubusercontent.com/25380224/72394610-b6c80e00-36eb-11ea-98aa-501f20c440c7.png)

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce
1. Go to Design Flow tab
2. Click on a trigger
3. Click on a intent box that contains a bot asks tab
4. Hit enter before the "-" of the current bot dialog statement. 
ex. 

- Which list should I add **@{dialog.item}** to?

5. See error as your local instance of the bot framework composer immediately exits with exit code 1. 

## Expected behavior
The ability to continue editing the bot asks text box should not crash the server. I should be able to in the process of editing add a new line before or in the process of adding new information to the bot asks text box.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.
![Screen Shot 2020-01-14 at 4 46 17 PM](https://user-images.githubusercontent.com/25380224/72395248-aadd4b80-36ed-11ea-8bed-7da86fcef181.png)

![Screen Shot 2020-01-14 at 4 46 28 PM](https://user-images.githubusercontent.com/25380224/72395238-a5800100-36ed-11ea-9ec6-8eecf0c88522.png)

![Screen Shot 2020-01-14 at 4 46 46 PM](https://user-images.githubusercontent.com/25380224/72395228-a153e380-36ed-11ea-8269-f83c4cb43fac.png)

![Screen Shot 2020-01-14 at 4 47 03 PM](https://user-images.githubusercontent.com/25380224/72395219-9bf69900-36ed-11ea-83f7-0595392a5043.png)

**Comment by zhixzhan** [comment]
Hi @Kaipie5 I tried on master get no error, seems it has been fixed.

**Comment by hibrenda** [comment]
I can reproduce it on stable branch. so we will fix this by master branch sync.

**Comment by hibrenda** [comment]
We need to fix the wrong syntax highlighting in LG.

**Comment by hibrenda** [comment]
close this as no crash after sync with master branch
