### ISSUE TITLE
I want to delete a trigger, but the "Delete" button is disabled

### ISSUE THREAD

**Issue by jefferydai** [microsoft/BotFramework-Composer#1860]
##Describe the bug
I want to delete a trigger, but the delete button is disabled.

## Version
I use downloaded BotFramework-Composer-stable.zip
<img width="955" alt="WeChat Screenshot_20200115173642" src="https://user-images.githubusercontent.com/44393697/72423307-ff9cc700-37be-11ea-9251-a147b12471ab.png">

## Browser
What browser are you using?
- [ x] Firefox

## OS 
What operating system are you using?
- [ x] Windows

## Screenshots
![image](https://user-images.githubusercontent.com/44393697/72423130-b482b400-37be-11ea-8cd4-3e1a2b0d0f5b.png)

**Comment by hibrenda** [comment]
@jefferydai please hover to the trigger and you can find the 3 dot to delete the trigger. "Delete" in tool bar is used for deleting the nodes if such node is selected inside the visual canvas. Hope following can help. 
![image](https://user-images.githubusercontent.com/43408889/72423726-b600ac00-37bf-11ea-852f-4ce169746c09.png)

**Comment by jefferydai** [comment]
Hi Brenda,

Thank you very much. With your help, I have deleted the trigger.
I don't know if there is any document where I can find the solution when I encounter such kind of problem.

Thanks a lot.


dai_juntang@pactera.com
 
From: Brenda Bai
Date: 2020-01-15 17:52
To: microsoft/BotFramework-Composer
CC: jefferydai; Mention
Subject: Re: [microsoft/BotFramework-Composer] I want to delete a trigger, but the "Delete" button is disabled (#1860)
@jefferydai please hover to the trigger and you can find the 3 dot to delete the trigger. "Delete" in tool bar is used for deleting the nodes if such node is selected inside the visual canvas. Hope following can help.

**Comment by mareekuh** [comment]
@hibrenda | delete option should be enabled when the trigger is selected in left nav. 
If there is ambiguity on what to delete (ie nothing is selected), the button is grayed out by design.

@cwhitten 
@sangwoohaan
