### ISSUE TITLE
form not converting text into lg template

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#1862]
Complete the necessary portions of this template and delete the rest.

## Describe the bug

In Controlling Conversation Flow Sample, the inline lg Editor in ForeachStep can't update the lg file

![bug1](https://user-images.githubusercontent.com/39758135/72429936-ffef8f00-37cb-11ea-94b6-7a42940dcb4d.gif)
 

## Version
master

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. create a bot from Controlling Conversation Flow Sample 
2. Click ForeachStep dialog
3. update the last action

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.
![image](https://user-images.githubusercontent.com/39758135/72429643-6a53ff80-37cb-11ea-8c59-e8909791a3c7.png)

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/issues/1862
