### ISSUE TITLE
How to get user email ID in composer when we are connected to MsTeams

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#1864]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
Give a clear and concise description of what the bug is.

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).

## Browser
What browser are you using?

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.

**Comment by hibrenda** [comment]
@KoradaRajesh Could you provide more detail about your requirement ?

**Comment by KoradaRajesh** [comment]
@mdrichardson @vishwacsena  can you help me out

**Comment by gustavo-lara-molina** [comment]
@KoradaRajesh 
I have the same question, did you find a way to do it?
