### ISSUE TITLE
Bot Framework Composer fails with HTTP 502.5 process

### ISSUE THREAD

**Issue by HexaCubist** [microsoft/BotFramework-Composer#1866]
# Describe the bug

When deployed to azure using the provided script, the app service fails to launch with the following error:
![image](https://user-images.githubusercontent.com/8563277/72473260-2bfe2500-384b-11ea-9414-dc19bea86f23.png)

Following the instructions for debugging this error, I found the following error on the server:

```
Error:
  An assembly specified in the application dependencies manifest (BotProject.deps.json) was not found:
    package: 'System.Private.ServiceModel', version: '4.5.0'
    path: 'runtimes/win/lib/netstandard2.0/System.Private.ServiceModel.dll'
```

Note that the bot launches and runs perfectly fine locally, this seems to be an issue somewhere between publishing and deploying it onto Azure

## Version
![image](https://user-images.githubusercontent.com/8563277/72473389-72ec1a80-384b-11ea-9133-76e0bc13ed30.png)

I'm unsure if I'm using the right version here - I downloaded the repository when https://github.com/microsoft/BotFramework-Composer/commit/1a750e5800639f50b6c27df5e34153d2efc86eb7 was the latest commit

## Browser
What browser are you using?

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce
1. Create bot from scratch on 
2. Use publish scripts (create resources & deploy)
3. Visit app service URL

## Expected behavior

Expected the app service to launch without crashing

**Comment by HexaCubist** [comment]
In the process of wiping everything and starting from scratch to see if it was due to some mistake made during the setup process.

**Comment by cwhitten** [comment]
Hi @HexaCubist, did starting from scratch address the issue for you?

**Comment by HexaCubist** [comment]
Hi @cwhitten yep - not sure what the underlying issue is here but I imagine it could have been some configuration error on my part.
