### ISSUE TITLE
Update Language Generation document - IF condition format

### ISSUE THREAD

**Issue by narulasrinivas** [microsoft/BotFramework-Composer#1867]
## Describe the bug
In Language Generation documentation, If Else condition need to be formated

[Language generation document link](https://github.com/microsoft/BotFramework-Composer/edit/stable/docs/tutorial/bot-tutorial-lg.md
)

## Browser
What browser are you using?

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce
Currently it is without `@` infront of { in IF ELSE condition

```
`# DescribeWeather(weather)
- IF: {weather.weather=="Clouds"}
    - It is cloudy
- ELSEIF: {weather.weather=="Thunderstorm"}
    - There's a thunderstorm
- ELSEIF: {weather.weather=="Drizzle"}
    - It is drizzling
- ELSEIF: {weather.weather=="Rain"}
    - It is raining
- ELSEIF: {weather.weather=="Snow"}
    - There's snow
- ELSEIF: {weather.weather=="Clear"}
    - The skies are clear
- ELSEIF: {weather.weather=="Mist"}
    - There's a mist in the air
- ELSEIF: {weather.weather=="Smoke"}
    - There's smoke in the air
- ELSEIF: {weather.weather=="Haze"}
    - There's a haze
- ELSEIF: {weather.weather=="Dust"}
    - There's a dust in the air
- ELSEIF: {weather.weather=="Fog"}
    - It's foggy
- ELSEIF: {weather.weather=="Ash"}
    - There's ash in the air
- ELSEIF: {weather.weather=="Squall"}
    - There's a squall
- ELSEIF: {weather.weather=="Tornado"}
    - There's a tornado happening
- ELSE:
    - {weather.weather}`
```

## Expected behavior
Above code need to be updated with right format.
```
# DescribeWeather(weather)
- IF: @{weather.weather=="Clouds"}
    - It is cloudy
- ELSEIF: @{weather.weather=="Thunderstorm"}
    - There's a thunderstorm
- ELSEIF: @{weather.weather=="Drizzle"}
    - It is drizzling
- ELSEIF: @{weather.weather=="Rain"}
    - It is raining
- ELSEIF: @{weather.weather=="Snow"}
    - There's snow
- ELSEIF: @{weather.weather=="Clear"}
    - The skies are clear
- ELSEIF: @{weather.weather=="Mist"}
    - There's a mist in the air
- ELSEIF: @{weather.weather=="Smoke"}
    - There's smoke in the air
- ELSEIF: @{weather.weather=="Haze"}
    - There's a haze
- ELSEIF: @{weather.weather=="Dust"}
    - There's a dust in the air
- ELSEIF: @{weather.weather=="Fog"}
    - It's foggy
- ELSEIF: @{weather.weather=="Ash"}
    - There's ash in the air
- ELSEIF: @{weather.weather=="Squall"}
    - There's a squall
- ELSEIF: @{weather.weather=="Tornado"}
    - There's a tornado happening
- ELSE:
    - @{weather.weather}
```

## Screenshots
If it is used without @ infront of {, then below error occurs.
![image](https://user-images.githubusercontent.com/2491903/72475400-b8c0c880-37e2-11ea-9121-0fe1a2d721f3.png)

## Additional context
I referred this format in [language file format page](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/language-generation/docs/lg-file-format.md).

**Comment by zxyanliu** [comment]
Hi! Thanks for reporting the bug. Yes, you are right. We have updated the docs in [this branch](https://github.com/microsoft/BotFramework-Composer/blob/kaiqb/composer-review/docs/tutorial/bot-tutorial-lg.md), and the content will be available soon.

**Comment by zxyanliu** [comment]
Hey, thanks for your report again. We have updated the content [here](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/tutorial/tutorial-lg.md) . Closing the issue because it was addressed.
