### ISSUE TITLE
LU all up view enhancement for enabling LSP 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1869]
**Describe the solution you'd like**
After LU LSP enabled in LU all up view, following need to be updated.
- if there is an error in lu format, switch back from dialog view to LU all up view, it will pop up several errors  (need to remove the error pop up)
- if there is an error in lu format, error message will show up at the bottom of the frame. but if the error is too long, it can not be showed correctly (need to show the whole error message)
- If there is an error in lu format, error message will show "linexxx, error ..".  so we need to add line number in LU all up view
![image](https://user-images.githubusercontent.com/43408889/72582253-2c66f080-391d-11ea-98d4-4cf6194ac10a.png)

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1879
