### ISSUE TITLE
[Inline LG] lsp error info disagrees with diagnostics.

### ISSUE THREAD

**Issue by alanlong9278** [microsoft/BotFramework-Composer#1871]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
`monacoEditor` error behavior disagree with diagnostics.

## To Reproduce
1. Create a `sendResponse` step, there is a error in editor, but diagnostics is null.

## Expected behavior
There should not have error in `monacoEditor`.

## Screenshots
![image](https://user-images.githubusercontent.com/5860999/72589352-f84bf980-3935-11ea-9f88-a8d68ec37992.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1861
