### ISSUE TITLE
help step not fully documented for weather demo 

### ISSUE THREAD

**Issue by narulasrinivas** [microsoft/BotFramework-Composer#1878]
## Describe the bug
**Please specify your postcode in the form #####** response step is not documented.
Step missing from the documentation

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
Follow steps given in [Add Help and Cancel](https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial/bot-tutorial-add-help.md)

**Please specify your postcode in the form #####** response step was NOT documented.

## Expected behavior
When a user types **help** while BOT is asking for **What is your zipcode?**. It should give response as **Please specify your postcode in the form #####**. But the step was missing from the documentation.

 Please correct if I'm missing something.

**Comment by hibrenda** [comment]
@narulasrinivas  please reference https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial/bot-tutorial-get-weather.md for setting your TextInput. These info has been included in "Invalid and Unrecognized" field.

**Comment by narulasrinivas** [comment]
@hibrenda - No, this is not having information to prompt **Please specify your postcode in the form #####**

Please check the gif image which was given in [Add Help and Cancel documentation](https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial/bot-tutorial-add-help.md). **Please specify your postcode in the form #####** response is missing.

![image](https://user-images.githubusercontent.com/2491903/72802841-9268b600-3c44-11ea-8acd-f5fca1787f85.png)

**Comment by zxyanliu** [comment]
Hi! @narulasrinivas Thanks for reporting the bug. I think we need to update the .gif file. We apologize for the confusion. The updated content will be available soon. : )

**Comment by zxyanliu** [comment]
Hey @narulasrinivas I believe the issue you reported has been addressed in this [doc](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-help). 
Therefore closing this issue. 
Thanks!
