### ISSUE TITLE
Cannot change the Authoring region while publishing the bot

### ISSUE THREAD

**Issue by prasadreddybv** [microsoft/BotFramework-Composer#1885]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
I have created a sample bot in the Composer in my local and selected the Recognizer type as LUIS. 
SO when i try to Publish the LUIS model i am getting error as Something went wrong. The LUIS model which i am trying to configure was created in **WestEurope** region but i am unable to change the region in the Publish window.

![image](https://user-images.githubusercontent.com/28754600/72802773-8267cb00-3c72-11ea-9449-bde17c298e8a.png)

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).
I am using 4.6.0-preview2 version.

## Browser
What browser are you using? ---  Chrome

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
I need to change the region to west europe or please give me the alternate solution for this to solve.Thanks in advance.

## Screenshots
![image](https://user-images.githubusercontent.com/28754600/72803020-12a61000-3c73-11ea-9771-368482341e0e.png)
Note : For **Authoring key** i am giving the LUIS model **Primary key**.

**Comment by narulasrinivas** [comment]
Hi @prasadreddybv  - Even I encountered same issue and after digging a bit on this. I realised appettings.json file gets updated from UI. So, I manually updated the value for region as **westeurope**  and ran powershell given in the scripts folder.

It created resources in Azure and all looks good. I think composer team is still working on this.

**Comment by prasadreddybv** [comment]
> Hi @prasadreddybv - Even I encountered same issue and after digging a bit on this. I realised appettings.json file gets updated from UI. So, I manually updated the value for region as **westeurope** and ran powershell given in the scripts folder.
> 
> It created resources in Azure and all looks good. I think composer team is still working on this issue.

Hi @narulasrinivas - Thanks for your response. Could you please let me know the command which you have used while running the powershell and can you please confirm if the scripts folder is the one which i am providing below.

![image](https://user-images.githubusercontent.com/28754600/72878647-57888000-3d21-11ea-8d98-9816e79d19dd.png)(Bot framework Composer -->Scripts) or should we go to scripts folder inside the Composer folder?

**Comment by narulasrinivas** [comment]
@prasadreddybv  - First you need to point to application folder. Each application has **scripts** folder and in that **create.ps1** and **deploy.ps1** are there to create resources and deploy solution.

Here is the command, I'm using to run the script and create resources in **UKSouth**. Please refer below screenshot.

![image](https://user-images.githubusercontent.com/2491903/72924171-620a4000-3d48-11ea-99ff-55f945b685da.png)

**Comment by cwhitten** [comment]
In #1500 and corresponding pull-request, regions were removed from the UI. With some investigation we can add known supporting authoring regions and consider updating documentation for workarounds to manual edit the appropriate files

**Comment by cwhitten** [comment]
THANK YOU @narulasrinivas for the help! You're awesome

**Comment by darrenj** [comment]
Authoring Region is still grayed out in the UX impacting customers operating outside of the westus region (e.g. europe)

![image](https://user-images.githubusercontent.com/33519520/82892140-d77c5c00-9f46-11ea-9ffe-e1ed0d6521db.png)

**Comment by narulasrinivas** [comment]
@darrenj -
First you need to point to application folder. Each application has **scripts** folder and in that **create.ps1** and **deploy.ps1** are there to create resources and deploy solution.

Here is the command, I'm using to run the script and create resources in **UKSouth**. Please refer below screenshot.

![image](https://user-images.githubusercontent.com/2491903/82893146-7bb2d280-9f48-11ea-9923-3f9ecfa7cd00.png)

**Comment by tdurnford** [comment]
@narulasrinivas You should be able to set the Authoring Region to 'West Europe' in the latest version of Composer.

![image](https://user-images.githubusercontent.com/17039790/93836556-df12ef80-fc1e-11ea-8b93-b18fc654ffc7.png)
