### ISSUE TITLE
Different delete icons are used for the same functions

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1888]
![Screen Shot 2020-01-21 at 12 58 21 PM](https://user-images.githubusercontent.com/50963385/72854076-18e2bf00-3c68-11ea-9d69-3ad65b97be48.png)
![Screen Shot 2020-01-21 at 12 58 18 PM](https://user-images.githubusercontent.com/50963385/72854078-18e2bf00-3c68-11ea-9ba5-b2f384c81436.png)

These two icons are supposed to be the same. Let's replace the X with the trash can.

**Comment by tdurnford** [comment]
Should the trash can icon also be added to the delete trigger menu option?

![image](https://user-images.githubusercontent.com/17039790/72931035-03c26a80-3d12-11ea-9799-22b352fe8988.png)

**Comment by sangwoohaan** [comment]
@tdurnford No, that stays the same for now, since it's a different action - we are going to work on visually differentiating it later.
