### ISSUE TITLE
When we are asking a question type File or Attachment and the user responds to it a text message then the retry prompt is not triggering again it displaying the prompt message

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#1894]
**When we are asking a question type File or Attachment and the user responds to it a text message then the retry prompt is not triggering again it displaying the prompt message.**

**if the max turn count is 1 then we want to display a different message which is not there in prompt message.**

**Comment by cwhitten** [comment]
@vishwacsena can you assess if this could be an SDK gap?

**Comment by vishwacsena** [comment]
@KoradaRajesh I believe this is addressed via [this](microsoft/botbuilder-dotnet#3486), tracked via this bug https://github.com/microsoft/botbuilder-dotnet/pull/3486. 

Please reactivate if you continue to see this issue in latest composer. 

@cwhitten FYI.
