### ISSUE TITLE
Improved LG experience design

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1896]
Creating a new issue to collect and track previously filed LG related issues

Move LG away from common and to one .lg file per dialog
https://github.com/microsoft/BotFramework-Composer/issues/796

UX | multi-language support: review and edit translations in the context of dialogs
#1726 

UX | Create, edit and test re-usable bot responses (LG templates) in the context of a dialog
#1722 

provide a link(button) to User Input editor / external editor for lu
#1660

**Comment by cwhitten** [comment]
@sangwoohaan your list is not complete, and not all of these are in-scope/part of the prioritized spec. Let's connect and make sure we're crisp on what the asks from design are. cc @mareekuh

**Comment by sangwoohaan** [comment]
@cwhitten Yes, this list is partially for me to organize and keep track of LG related issues cause there are so many. We definitely need to connect and discuss.

**Comment by mareekuh** [comment]
@cwhitten - who is the best person from the dev team to work with us on this?
PVA is very interested in this also, so we may want to include them when we're a bit further with this.
