### ISSUE TITLE
Connect to QnA bot doesn't accept a valid hostname

### ISSUE THREAD

**Issue by ismendes** [microsoft/BotFramework-Composer#1897]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
I've been trying to connect a QnA kb without success. I get the following error:
Hostname must be an expression: Error: syntax error at line 1:5 mismatched input ':' expecting <EOF>). Refer to the syntax documentation here
In the link, I could find nothing about hostname syntax, and I'm using the one from my knowledge base, following the example from the input field, i.e., https://pt-bot.azurewebsites.net/qnamaker

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).
Application SHA
test
Release: Preview 1.0

## Browser
What browser are you using?
- [x] Edge

## OS 
What operating system are you using?
- [x] Windows

## To Reproduce
1. Create a bot using the LUIS and QnA template
2. Try to input a valid Hostname

## Screenshots
![image](https://user-images.githubusercontent.com/56369624/73044588-0ced2d80-3e1f-11ea-976a-659ec7f13793.png)

**Comment by prasadreddybv** [comment]
Hi @ismendes . You need to configure the QnA details in the Settings page and access them dynamically in the intent page as shown below.
**settings.qna.knowledgebaseid**
**settings.qna.hostname
settings.qna.knowledgebaseid**

**Comment by narulasrinivas** [comment]
Hi @ismendes - 

Settings which you're modifying in the below screen are loading from **appsettings.json** file in the **settings** folder in application solution folder.

![image](https://user-images.githubusercontent.com/2491903/73071329-66e70500-3eaa-11ea-90f3-1490cfc1a6ce.png)

![image](https://user-images.githubusercontent.com/2491903/73071500-ccd38c80-3eaa-11ea-91ae-b2814f0621e1.png)

**Comment by narulasrinivas** [comment]
> Hi @ismendes . You need to configure the QnA details in the Settings page and access them dynamically in the intent page as shown below.
> **settings.qna.knowledgebaseid**
> **settings.qna.hostname settings.qna.knowledgebaseid**

@prasadreddybv - As far as I understood, settings page details are mainly used to create and deploy the solution. But not the settings related to application components.

**Comment by cwhitten** [comment]
@ismendes The comments from @narulasrinivas & @prasadreddybv are correct. If you're still having trouble, please paste the JSON data in your Settings page and we can debug the issue from there. Closing this for now but let's continue to use this thread to communicate. Thank you!
