### ISSUE TITLE
Unable to sync content to bot runtime

### ISSUE THREAD

**Issue by prasadreddybv** [microsoft/BotFramework-Composer#1898]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
Not able to publish the bot. Cant predict the exact issue as it is showing the below error.
Unable to sync content to bot runtime when i click on Restart bot.

## Version
What version of the Composer are you using? Paste the build SHA found on the about page (`/about`).
4.6.0-preview2

## Browser
What browser are you using?

- [> ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS 
What operating system are you using?

- [ ] macOS
- [> ] Windows
- [ ] Ubuntu

## Expected behavior
Publish should happen and open the emulator to test the bot.

## Screenshots
If applicable, add screenshots/gif/video to help explain your problem.
![image](https://user-images.githubusercontent.com/28754600/73062736-15973f80-3ec3-11ea-8c53-05d154f2792b.png)

**Comment by narulasrinivas** [comment]
@prasadreddybv - how did you create and deploy your solution?

From my observation, publish is part of deployment. Can you give more information on below points:

1. Which template you've chosen in BOT composer?
2. What changes you done to it?
3. What you're trying to achieve?

**Comment by cwhitten** [comment]
@prasadreddybv are you still having issues? The deployment/publish mechanisms are not driven by the "Start/Restart Bot" button in your screenshot.

**Comment by prasadreddybv** [comment]
@narulasrinivas - I have created a weather bot and using LUIS as Recognizer type.
I did not used any template. This a new bot which i created from scratch.
I have tried toinclude QnA details in settings page. After including this details bot is not working as earlier. So i have reverted the changes and restarted the bot.
Then i was facing this issue.

**Comment by prasadreddybv** [comment]
@cwhitten - After publishing here in Composer, I have deployed the C# code directly in the Azure  which the bot generates in the Composer folder.

**Comment by cwhitten** [comment]
Ok, that sounds like you're all set, Can we close this issue?

**Comment by prasadreddybv** [comment]
But after deployment the bot is not responding for any of the questions!!!

**Comment by luhan2017** [comment]
Could you share your bot logic here? I can help you to debug it if you provide more info. @prasadreddybv
