### ISSUE TITLE
Create an echo bot - cannot connect to a bot runtime, make sure you start the bot runtime error

### ISSUE THREAD

**Issue by chrisuru** [microsoft/BotFramework-Composer#1900]
Complete the necessary portions of this template and delete the rest.

## Describe the bug
I've [set up yarn](https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/setup-yarn.md) and now am trying to [create an echo bot](https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial-create-echobot.md).

I'm getting stuck at step 4 and receive the following error when clicking 'Start Bot':
![image](https://user-images.githubusercontent.com/57016323/73102410-c8fe3500-3ebf-11ea-99b4-0680cdc00e64.png)

## Version
Application SHA: [test](https://github.com/microsoft/BotFramework-Composer/commit/test)
SDK runtime packages: [4.6.0-preview2](https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder.Dialogs.Adaptive/4.6.0-preview2)

## Browser
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS 
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce
1. [Setup Bot Framework Composer using Yarn](https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/setup-yarn.md)
2. [Create an echo bot using Bot Framework Composer](https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial-create-echobot.md)

## Expected behavior
As per [Create an echo bot using Bot Framework Composer](https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial-create-echobot.md), I would expect to see the 'Test in Emulator' pop-up in stpe 4 and be able to proceed to step 5.

## Screenshots
Error:
![image](https://user-images.githubusercontent.com/57016323/73102663-59d51080-3ec0-11ea-9ee0-490958301449.png)

## Additional context
I'm quite a beginner to these things, so I would appreciate any help and apologies for any ignorance.

**Comment by cwhitten** [comment]
@chrisuru can you upload a screenshot of the terminal state when you follow documented commands to start the application and see this error?

**Comment by srinathgnath** [comment]
Hi All,
I got the same error "_**cannot connect to a bot runtime, make sure you start the bot runtime**_" while starting the bot.

Noticed below message executing YARN STARTALL command. Hope this might help in troubleshooting the issue.
![image](https://user-images.githubusercontent.com/35440448/73144615-96963880-4075-11ea-9df8-c1dedab3d79f.png)

**Comment by chrisuru** [comment]
@cwhitten, thanks for the reponse. Please see below for the terminal state when trying to run the bot.
![image](https://user-images.githubusercontent.com/57016323/73179254-f4ac3580-40e0-11ea-9cf2-53a2134b4662.png)

**Comment by cwhitten** [comment]
@chrisuru I have one more ask of you - we just updated the `stable` branch of Composer that includes various bug fixes that may or may not address your issue. Can you update the Composer bits by fetching and updating your clone of Composer and try the instructions again? You may need to recreate the bot.

**Comment by chrisuru** [comment]
Thanks for the response @cwhitten. To provide an update, I've redone the instructions as per the original email and will need to update to .NET Core 3.0 before proceeding. I'll try to do this tomorrow when I'm in the office and report back.

![image](https://user-images.githubusercontent.com/57016323/73489066-fe02ff80-4377-11ea-9884-fd6fc3d7b278.png)

**Comment by prasadreddybv** [comment]
Hi @cwhitten,

I am trying out a bot for one of my business use case. I am getting the below issue when i try to publish the bot.
![image](https://user-images.githubusercontent.com/28754600/74129011-8e590400-4c04-11ea-9e73-7ae91797164a.png)

Please check the terminal status when i publish the bot. its saying as it needs LUIS endpoint key even though i am providing as shown below.

![image](https://user-images.githubusercontent.com/28754600/74129068-afb9f000-4c04-11ea-8ba3-71f52868c53b.png)

Please refer the setting page below.

![image](https://user-images.githubusercontent.com/28754600/74129240-17703b00-4c05-11ea-8311-23cf9453838b.png)

**Comment by prasadreddybv** [comment]
> Thanks for the response @cwhitten. To provide an update, I've redone the instructions as per the original email and will need to update to .NET Core 3.0 before proceeding. I'll try to do this tomorrow when I'm in the office and report back.
> 
> ![image](https://user-images.githubusercontent.com/57016323/73489066-fe02ff80-4377-11ea-9884-fd6fc3d7b278.png)

@chrisuru -- I have got the latest stable version of composer and tried running again but no luck. Still i am getting the same error. I am not getting the "require dotnet core 3.0" error though. Could you please confirm like is this mandatory to update to 3.0?

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/issues/1927
