### ISSUE TITLE
Page Headers and Type consistency

### ISSUE THREAD

**Issue by DesignPolice** [microsoft/BotFramework-Composer#1902]
Hello I'm going through Composer and doing a visual check for consistency.

I have attached few images of all the different headers. We have a variety and I would like them to be the same as much as possible.

**Home - Bot Framework Composer:**
Currently - 28px Segoe Reg - Swap to 28px/36px Segoe SemiBold (600)

 **Dialog/Main**
This doesn't really have a header, but Breadcrumb should be:
Breadcrumbs - 18px / 24px Segoe Regular

LG "Bot Responses"
Page/Pane, Suite Nav - 20px / 28px Segoe Semibold (600)

LU "User Input"
Page/Pane, Suite Nav - 20px / 28px Segoe Semibold (600)

**Notifications**
Page/Pane, Suite Nav - 20px / 28px Segoe Semibold (600)

**Settings - 3 settings pages. Currently all in Bold**
   Settings, Publish and Onboarding Switch all to

20px / 28px Segoe Semibold (600)

**About**
This page has several different font sizes. change as follows.a

About - 20px / 28px Segoe Semibold (600)
Release info - 18px / 24px Segoe Regular
Bot framework paragraph 16px / 22px Segoe Regular
Application SHA
SDK
Getting help
set all of this in  16px / 22px Segoe Semibold (600) 

Hyperlinks I believe need an underline 

## Describe the bug
Give a clear and concise description of what the bug is.

## Version
4.6.0-preview2

## Browser
What browser are you using?

- [ ] Chrome

## OS 
What operating system are you using?

- [ ] macOS

<img width="744" alt="Screen Shot 2020-02-05 at 5 52 32 PM" src="https://user-images.githubusercontent.com/45223620/73899125-7a965200-4840-11ea-9461-9b8dabca1365.png">

<img width="787" alt="Screen Shot 2020-02-05 at 5 52 42 PM" src="https://user-images.githubusercontent.com/45223620/73899140-884bd780-4840-11ea-9bab-e5ff1ce90dd2.png">

https://www.figma.com/file/BAfsTrZ9ehIYZ0oYuyskUN2R/Web-Fluent?node-id=8349%3A51185

**Comment by liweitian** [comment]
Hi @DesignPolice, does '/' means 'or' here? 
For example,
Home - Bot Framework Composer:
Currently - 28px Segoe Reg - Swap to 28px/36px Segoe SemiBold (600)

**Comment by DesignPolice** [comment]
Sorry @liweitian my email was going to the wrong place.

That is correct. Home - Bot Framework will be Semibold now. 

I realize now that my comments were not clear - I will update the graphic to show what I want them to be as well what it currently is. #sorry
