### ISSUE TITLE
Visual Canvas Background Color

### ISSUE THREAD

**Issue by DesignPolice** [microsoft/BotFramework-Composer#1903]
Color updates

I would like to lighten the background color it seems to have gotten darker through out this process, I that is on us, we have several different comps that have different colors. 

Currently it looks like we are using #E3E3E3 I would like to drop it back to **#F6F6F6** 

After doing this we may need to lighten the Composer Icon. The text under neath 
**"Select a trigger..." Should be #545454** to hit numbers against the new background.

## Browser
What browser are you using?
- [ ] Chrome

What operating system are you using?
- [ ] macOS

![Screen Shot 2020-01-27 at 10 15 28 AM](https://user-images.githubusercontent.com/45223620/73201514-01835600-40ee-11ea-9ffc-4de0208940ac.png)

thank you!

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1959
