### ISSUE TITLE
ChoiceInput Node Edit

### ISSUE THREAD

**Issue by DesignPolice** [microsoft/BotFramework-Composer#1905]
This is an edit to the ChoiceInput "side node" - I'm not sure if it has an official name.

the box has gotten a little too small and it crushes in on the circle, making it look odd. We also need to match up the Hoover state shape. 

The image below show that we have the top to radius but this one has rounded on the bottom as well. 

hoover color should match the other nodes.. 

![Screen Shot 2020-01-27 at 10 33 22 AM](https://user-images.githubusercontent.com/45223620/73202849-ca627400-40f0-11ea-8b1d-a6b3a7ae5652.png)

![Screen Shot 2020-01-27 at 10 32 45 AM](https://user-images.githubusercontent.com/45223620/73202865-d2221880-40f0-11ea-87e7-b3c255154a24.png)

Mac 10.15.2
Chrome

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1950
