### ISSUE TITLE
Visual Canvas Arrows, Lines and Adds

### ISSUE THREAD

**Issue by DesignPolice** [microsoft/BotFramework-Composer#1906]
This is a little bit of a tricky solve.
I know we have talked about switching to SVG files so that we can add a zoom in and out on the Canvas a feature I would love to see.

What have with the PNG versions is that the pixel grid is throwing things off of alignment. I have added two different ways to solve for this - I will let Chris W decided scope and timing 

This also makes the + signs closer to the size I would like.

Anytime we have gray background #F4F4F4 and want to use gray type we will use #545454 

![Screen Shot 2020-01-27 at 10 38 54 AM](https://user-images.githubusercontent.com/45223620/73203465-f3373900-40f1-11ea-962b-6f82f31dd258.png)

**Comment by cwhitten** [comment]
@yeze322 let's wrap up the svg work before we take this one.

**Comment by yeze322** [comment]
okay!

**Comment by DesignPolice** [comment]
Awesome, let me know if you need any assets for this @yeze322

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1987
