### ISSUE TITLE
Multiple ChoicInput

### ISSUE THREAD

**Issue by DesignPolice** [microsoft/BotFramework-Composer#1907]
Hello,

Just another spacing issue on this node, when it add 3 items to a ListType - spacing around the boxes needs to change. I have spec'd out the spacing on all of the node, and it's options. 

Should be a pretty easy fix. 

Thanks again.

![Screen Shot 2020-01-27 at 10 52 37 AM](https://user-images.githubusercontent.com/45223620/73204839-94bf8a00-40f4-11ea-8edb-1c48b138513b.png)

MacOS 10.15.2
Chrome
Stable

**Comment by yeze322** [comment]
Quote Mark's comments https://github.com/microsoft/BotFramework-Composer/pull/1954#issuecomment-582690508

> Hey Alan,
> 
> not sure why I didn't get an email on this - I need to check my email settings. Sorry to not get back to you sooner.
> 
> I have a couple of current issues that also have I have noticed a similar treatment, I would love to just make a couple of tweaks.
> 
> The top corners on the nodes have a corner radius of 2px - the hoover outline should have that as well.
> 
> I have mocked up some screen shots on these two.
> 
> [ChoiceInput Node Edit #1905](https://github.com/microsoft/BotFramework-Composer/issues/1905) - these will need changes on other nodes
> 
> Hoover State on Nodes #1904 [https://github.com/microsoft/BotFramework-Composer/issues/1904](url)
> 
> but also attached here.
> 
> reach out if that you would like more clarity... happy to help out. Thank you!
> M
> 
> <img alt="screen grab" width="1104" src="https://user-images.githubusercontent.com/45223620/73897583-63089a80-483b-11ea-9f21-f353d1aba013.png">

**Comment by alanlong9278** [comment]
hey, @DesignPolice , Could u send the latest figma for me, I wanna to check all the node ui with it.

**Comment by DesignPolice** [comment]
Hi Alan. Will do, I will be in the office in about :30 minutes - thanks

**Comment by DesignPolice** [comment]
Here you go Alan... 
let me know if you have any questions. Always happy to chat
https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=3276%3A95

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1954
