### ISSUE TITLE
Trigger names

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1911]
**Is your feature request related to a problem? Please describe.**
Current naming of triggers is a bit confusing. 

![image](https://user-images.githubusercontent.com/32497439/73224555-b0d82100-411e-11ea-8e53-a01d856cdca7.png)

**Describe the solution you'd like**

<img width="1286" alt="Screen Shot 2020-01-21 at 4 09 28 PM" src="https://user-images.githubusercontent.com/32497439/73224356-17a90a80-411e-11ea-8217-50b1848feee8.png">

**Comment by mareekuh** [comment]
Updated design: https://www.figma.com/file/HLtKaKHctLldivPnzQ7BqQOI/Composer-MI---lotsotings?node-id=2108%3A13658

(also addresses other issues with usability/discoverability for Trigger types but I cannot find that).

**Comment by hibrenda** [comment]
Need more clarification and also need to address the RecognizerSet as well .

**Comment by zxyanliu** [comment]
@mareekuh FYI. You might have already found this in the trigger menu:

I think the first trigger type in the **Message events** drop-down menu should be **Message received**. What is shown now is 

**Message events**
-> **Message events**
-> **Message deleted**
-> **Message reaction**
-> **Message updated**

What it is supposed to be: 

**Message events**
-> **Message received**
-> **Message deleted**
-> **Message reaction**
-> **Message updated**

![Untitled](https://user-images.githubusercontent.com/32497439/74773981-c802be00-5247-11ea-8f6a-476819cbf459.png)

Thanks.

**Comment by mareekuh** [comment]
Yes : Message received vs Message Events
The dropdown should not have the word 'events' in it, per our discussion.
Trigger type: Language understanding/Dialog/Message/Other activities/Custom. Yes?

**Comment by zxyanliu** [comment]
Hey @mareekuh 
I agree that the word 'events' should be removed from some of the drop-down menus. 
However, I think it might also be helpful to keep 'events' in the first-level menu. Thanks to @boydc2014 who explained "events" and "triggers" to me so that I have a better understanding of the two terms. 

Here are my rough thoughts:

**What initiates the trigger?** 
-> **Recognizer events** 
-> **Dialog events**
-> **Message activity events** 
-> **Other activity events** 
-> **Custom event**

The major reason to include **events** in the first-level menu is that it might help users to understand that **triggers** are created to react to some type of **events**.  

Thanks.

**Comment by mareekuh** [comment]
No I'd like to leave out the word event.
Select a trigger type:
Intent  _(the 2nd field should show all existing intents and 'create new' at the top)_
Not recognized intent _(2nd field is empty)_
Dialog trigger
Message activity
Other activity 
Custom trigger

**Comment by zxyanliu** [comment]
@mareekuh It looks good! Just one thing, can we add "trigger" to each type of them? I feel it's more consistent. But this will bring another issue, some trigger names may be too long.

**Comment by mareekuh** [comment]
I can try it out..

**Comment by zxyanliu** [comment]
Yes, I agree. No need to duplicate in 2nd level menu.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2151
