### ISSUE TITLE
Toolbar redesign

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1912]
The current toolbar needs a redesign since it has a scope issue. Currently,
- Undo/Redo works globally.
- Cut/Copy/Paste only works for action nodes on the visual canvas.

This will be a small design tweak.

Related issues:
https://github.com/microsoft/BotFramework-Composer/issues/1860, https://github.com/microsoft/BotFramework-Composer/issues/1415

**Comment by a-b-r-o-w-n** [comment]
Duplicate of #3494
