### ISSUE TITLE
Support of CodeStep using Composer

### ISSUE THREAD

**Issue by vikramdadwal** [microsoft/BotFramework-Composer#1914]
## Describe the solution you'd like

Currently I do not see any Code Step that can be added in the Composer Application in the Dialog files. We were using several custom Code Steps while using AdaptiveDialog. Can we have this feature in Composer?

**Comment by cwhitten** [comment]
Hi @vikramdadwal. We're discussing as a team how we want to provide the CodeStep integration. Can you share details more about your scenarios and current use cases for it? This will help us design the solution.

**Comment by vikramdadwal** [comment]
Hi @cwhitten, thanks for the quick response.

We are building a common BOT platform (using V4.6) for our organization. As a platform we want the tenants to provide the BOT Template files (dialog and lg files), which would define their business scenarios workflows. Our platform will integrate these dialog workflows when Tenant will on-board.

Now there are scenarios when they could have a complex calculation OR complex integration (generating JWT token, or token for legacy apps) steps in between their dialog workflow. One more use case is, as a platform we want to inject some dynamic behavior (common reusable Actions which are platform specific) in between the Actions defines in the templates, so we were thinking is we can have some custom Action, something like:

```
"actions": [
        {
          "$type": "Microsoft.CustomCodeStep",
          "$designer": {
            "id": "254582",
            "name": "Code Step"
          },
          customClassName: "ClassName"  // This will be inherited from some special interface e.g. IAdaptiveCustomAction
		  //Some more properties
        },
```

Happy to discuss further. Thanks.

**Comment by tdurnford** [comment]
@cwhitten do you have any updates on this?
