### ISSUE TITLE
Inconsistent names b/w prompt in authoring canvas and properties panel

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1915]
## Is your feature request related to a problem? Please describe.

Should we make the items in the prompt consistent? 

- Currently in Composer **Prompt**: 

**Text input** matches **Bot Asks** 
**User Answers(Text)** matches **User Input**
The icon matches **Other** 

![prompt](https://user-images.githubusercontent.com/32497439/73316402-a03fad80-41e7-11ea-9a20-834f9011f79c.gif)

## Describe the solution you'd like

We should make the item names of the prompt in the properties panel and the authoring canvas consistent.

**Comment by yeze322** [comment]
addressed in #1940

**Comment by cwhitten** [comment]
closed via https://github.com/microsoft/BotFramework-Composer/pull/1940
