### ISSUE TITLE
Update the server to generate and store a unique bot ID for every bot project that is opened

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#1917]
Provide a server-generated GUID to identify a specific bot project location.
This GUID will be used to make calls to the server to modify the project without having to know or expose its specific location.

## Describe the solution you'd like

- [x] Update project service so that openProject will return as part of the bot project a GUID
- [x] Update project service to load/persist the mapping of GUID to location in the config store.
- [x] Introduce getBotProjectId that uses the GUID map to load the project from storage
   - [x] if no ID is found in mapping, return error indicating client direct user to reopen
   - [x] If project does not exist in storage, remove ID from map and return error indicating client should direct user to reopen
- [x] Replace use of getCurrentBotProject with getBotProjectById in the project controller. Update all relevant API endpoints to accept a bot ID as part of the request payload.
- [x] Replace use of getCurrentBotProject with getBotProjectById in the csharpBotConnector
- [x] Refactor/remove code that refers to the global "currentBotProject" from the BotProjectService - replace where appropriate with getBotProjectById

**Comment by benbrown** [comment]
This is done and present in #2023

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2023
