### ISSUE TITLE
Update client code to receive and pass back a bot ID

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#1918]
The client code needs to be updated to manage the identify of the open bot project. Up to this point, that information was stored in the server, but responsibility will now move to the client code to enable multi-user scenarios.

## Describe the solution you'd like

- [x] When a bot project is opened or created, capture the included bot id and make it easily available throughout the app 
- [x] Amend the code for all `actions` that make API calls to the server to include the bot id as part of the payload (~ 15 endpoints)
- [x] Update client code to include bot ID in the routes such that `/dialogs/main` is now `/bot/:ID:/dialogs/Main`. This applies to all routes that refer to content from a bot project, including settings.
- [x] Ensure that, given a bot id in the url, the application is loads the appropriate content into the editor and provides the correct value to api calls
- [x] Handle errors resulting from an invalid bot id - redirect user to the home screen and/or the open bot dialog.

**Comment by benbrown** [comment]
This is completed in #2023

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2023
