### ISSUE TITLE
Dependancy on .NET version needs to be indicated in the README

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#1925]
## Describe the bug
.NET 2.1.4 version is a hard dependency to fire up composer for development. 

## Version
Master Branch

## Browser
Chrome (N/A)

## OS
MACOS

## To Reproduce
1. Check out master
2. Install the latest .NET runtime and SDK (3.1)
3. Run Composer and create a sample welcome bot
4. When composer tries to spin up a bot we get the error that .NET 2.1.4 version needs to be installed
5. We can also go into the CSharp folder for the bot and try to run dotnet run. We can replicate the same error

## Expected behavior
If .NET 2.1.4 is a hard dependency then we need to add it to the README as it would give clarity to people ramping up development on this project.

**Comment by boydc2014** [comment]
With recent change, we are requiring .net 3.1 from now, @zxyanliu i thought you have a doc update for that, right?

**Comment by zxyanliu** [comment]
Hey @boydc2014 Yes, we have the update in this [doc](https://docs.microsoft.com/en-us/composer/setup-yarn).
