### ISSUE TITLE
Unable to execute because the specified command or file could not be found error when running Echo bot example

### ISSUE THREAD

**Issue by selmi5** [microsoft/BotFramework-Composer#1927]
When I run the Echo Bot example I get this error message : Unable to execute because the specified command or file could not be found. Possible reasons: * You misspelled an integrated dotnet command. * You intended to run a .NET Core program, but dotnet-bin / Debug / netcoreapp2.1 / BotProject.dll does not exist. * You intended to run a global tool, but the executable with the name indicated above dotnet was not found in the PATH.

I have all the prerequisites:

Node.js: version 12.13.0
Yarn: latest stable version
Bot Framework Emulator: latest stable version
.NET Core SDK 2.2: required to test your bot

I have also .Net Core v3.1 & v 3.0 installed in my machine

**Comment by yomikakokei** [comment]
I had a same error in my environment.
Windows Server 2016 1607
Node.js: v12.14.1
.Net Core SDK 3.2.202
Yarn 1.21.1

**Comment by luhan2017** [comment]
It seems like a dotnet build failure. I met this problem too when I try to start a bot which is created last month. Could you try to create a new bot to see whether this still happens? 

If that still not works, you can try to open and build the botproject in the bot folder and paste your detailed error message here.

**Comment by VanyLaw** [comment]
> When I run the Echo Bot example I get this error message : Unable to execute because the specified command or file could not be found. Possible reasons: * You misspelled an integrated dotnet command. * You intended to run a .NET Core program, but dotnet-bin / Debug / netcoreapp2.1 / BotProject.dll does not exist. * You intended to run a global tool, but the executable with the name indicated above dotnet was not found in the PATH.
> 
> I have all the prerequisites:
> 
> Node.js: version 12.13.0
> Yarn: latest stable version
> Bot Framework Emulator: latest stable version
> .NET Core SDK 2.2: required to test your bot
> 
> I have also .Net Core v3.1 & v 3.0 installed in my machine

Do you run it by clicking start in composer? If so, you need to use SDK version bigger than 3.0. If it still throw exception, maybe it's because dotnet build failed with some package version compatibility. you can check it by running dotnet build command under your samplebot folder.

**Comment by aalmada** [comment]
I'm getting this when I click on "Start Bot".

![2020-02-03 18_25_22-Window](https://user-images.githubusercontent.com/534533/73679596-a4217300-46b2-11ea-834f-178082fe0f20.png)

I have the following .NET Core versions installed:

Runtimes
```
Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

SDKs
```
2.1.803 [C:\Program Files\dotnet\sdk]
2.2.207 [C:\Program Files\dotnet\sdk]
3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
3.1.100-preview2-014569 [C:\Program Files\dotnet\sdk]
3.1.101 [C:\Program Files\dotnet\sdk]
3.1.200-preview-014883 [C:\Program Files\dotnet\sdk]
```

**Comment by InDieTasten** [comment]
Running into the same issue with newly created Bots as well:
![image](https://user-images.githubusercontent.com/7047377/73733229-dd51f580-473b-11ea-870f-aaad6f65fb99.png)

Note, my exception message is translated to German somehow, I guess due to my OS language.

**Comment by VanyLaw** [comment]
hi @selmi5, I found this issue is because the original version package references were remove from myget/nuget, so it will make the build failed. Try to use 4.7.2 version to bypass this issue. We will update it ASAP.

FYI. 
you can change the botproject.csproj under your sample bot folder like this to bypass.
![image](https://user-images.githubusercontent.com/21174180/73744144-25e4cf80-478b-11ea-93aa-fdc0ea013856.png)

**Comment by yomikakokei** [comment]
> I had a same error in my environment.
> Windows Server 2016 1607
> Node.js: v12.14.1
> .Net Core SDK 3.2.202
> Yarn 1.21.1

I could run it to use workaround which VanyLaw wrote.

**Comment by VanyLaw** [comment]
> > I had a same error in my environment.
> > Windows Server 2016 1607
> > Node.js: v12.14.1
> > .Net Core SDK 3.2.202
> > Yarn 1.21.1
> 
> I could run it to use workaround which VanyLaw wrote. (I needed to install .Net Core 2.2 too.)

**Comment by VanyLaw** [comment]
@yomikakokei we will update to netcoreapp3.1 soon. At that time .Net Core 2.2 require will be removed.

**Comment by hinojosachapel** [comment]
I'm also having the same issue. I wonder why the message is in Spanish. My OS is in Spanish, but the language of my browser (Chrome) is set to English.

![echo-bot error1](https://user-images.githubusercontent.com/17761991/74015719-6ca41680-4991-11ea-981b-956d9d3106c1.png)

On the other hand, when I open the solution with Visual Studio, the following errors are found:

![echo-bot error2](https://user-images.githubusercontent.com/17761991/74016063-184d6680-4992-11ea-9d6e-8faaee282712.png)

The errors are found no matter the template I use.

**Comment by jssuthahar** [comment]
I am also having same issue , anyone has solutions

**Comment by InDieTasten** [comment]
@jssuthahar 
This issue is related with the output solution not able to compile.
Go the location of your generated bot (The one you set when creating a new bot, defaults to User Documents > Composer).
Run `dotnet build` in your bot directory and see the errors.
Then try to resolve the build errors. There can be a range of sources for the build not to run.
Wrongly configured Nuget sources, misaligned package version etc.
This thread has a couple of suggestions which seem to cover all the cases.
Once the build succeeds, launching the bot via Composer also works.

Good luck

**Comment by jssuthahar** [comment]
@InDieTasten, yes I have open Project in VS 2019 and modified Target version to .Net Core 2.2 and its started building and run the application us VS, but trying to"Start Run" in composer, its give same issue

**Comment by jssuthahar** [comment]
Hi, Ignore my previous steps, I have just followed below one started working, I have open the project and updated ,CS project  reference like below 

 ` <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.4" />
    <PackageReference Include="Microsoft.Bot.Builder" Version="4.7.1" />
    <PackageReference Include="Microsoft.Bot.Builder.ApplicationInsights" Version="4.7.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Azure" Version="4.7.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Adaptive" Version="4.7.1-preview" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Debugging" Version="4.7.1-preview" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Declarative" Version="4.7.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.ApplicationInsights.Core" Version="4.7.0-preview-191208-1" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.7.0-preview-191208-1" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs" Version="4.7.1" />
    <PackageReference Include="Microsoft.Bot.Connector" Version="4.7.1" />
    <PackageReference Include="MSTest.TestFramework" Version="1.4.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.66">`

@team: Please update Project template nuget packages, its may resolve for all the issue

**Comment by andreatosato** [comment]
I build correct project (2.1 current), then I update all packages and build on 2.2.
I have update this line:
https://github.com/microsoft/BotFramework-Composer/blob/028775b3c5fcf8345c52203bd11269bfed558378/Composer/packages/server/src/models/connector/csharpBotConnector.ts#L153-L157


2.1 and 2.2 build correct on dotnet, but file not found.
dir is correct? Can I see dir in console.log?

My folder projects
![image](https://user-images.githubusercontent.com/24985956/74135087-f6e7b700-4beb-11ea-94cf-37c7185fef20.png)

**Comment by jssuthahar** [comment]
@andreatosato : You are correct Please don't change dot net core version .
1.Go the location of your generated bot (The one you set when creating a new bot, defaults to User Documents > Composer).
2. Open project in visual studio
3. Edit your .csproject for now(@team : maybe they will update project template later )
4. modify following 
`<PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.4" /> <PackageReference Include="Microsoft.Bot.Builder" Version="4.7.1" /> <PackageReference Include="Microsoft.Bot.Builder.ApplicationInsights" Version="4.7.1" /> <PackageReference Include="Microsoft.Bot.Builder.Azure" Version="4.7.1" /> <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Adaptive" Version="4.7.1-preview" /> <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Debugging" Version="4.7.1-preview" /> <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Declarative" Version="4.7.1" /> <PackageReference Include="Microsoft.Bot.Builder.Integration.ApplicationInsights.Core" Version="4.7.0-preview-191208-1" /> <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.7.0-preview-191208-1" /> <PackageReference Include="Microsoft.Bot.Builder.Dialogs" Version="4.7.1" /> <PackageReference Include="Microsoft.Bot.Connector" Version="4.7.1" /> <PackageReference Include="MSTest.TestFramework" Version="1.4.0" /> <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.66">`
5. Build the solutions for now 
6. Try maybe it will work

**Comment by andreatosato** [comment]
<PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.66">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

**Comment by andreatosato** [comment]
For now, I fixed with this change:

```js
const runtime = child_process_1.spawn('dotnet', ['bin/Debug/netcoreapp2.1/BotProject.dll', `--urls`, this.endpoint, ...this.getConnectorConfig(config)], {
                    cwd: 'D:/GitHub/BotFramework-Composer-stable/BotProject/CSharp',                    
                    stdio: ['ignore', 'pipe', 'pipe'],
                });
```

**Comment by andreatosato** [comment]
Bot build correct, I open emulator, but display only "**This is a default bot.**"
I tried with default template: "EchoBot" and "RespondingWithCardsSample".
What's wrong?

**Comment by andreatosato** [comment]
I think that **dialog** and **lg** files cannot copy to my bot.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/issues/1927
