### ISSUE TITLE
Redundant setup instructions

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#1929]
## Describe the bug

In [setup-yarn.md](https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/setup-yarn.md), it doesn't make sense to type `cd Composer` after already navigating to the Composer folder:

> After cloning the repo open a terminal and navigate to the Bot Framework Composer folder. Navigate to the **Composer** folder and run the following commands:
> ```
> cd Composer 
> yarn 
> ```

**Comment by zxyanliu** [comment]
Hey Kyle, I agree and we already rephrased this step to the following in the [master branch](https://github.com/microsoft/BotFramework-Composer/blob/master/toc.md): 

> After cloning the repository, navigate to the **Bot Framework Composer** folder. Then run the following commands to navigate to the **Composer** folder and get all required packages:
> ```
> cd Composer 
> yarn 
> ```

Please let us know if it works! We appreciate your feedback. : )

Yan

**Comment by v-kydela** [comment]
While correct, I think it could be less wordy:

> After cloning the repo, open a terminal in the **BotFramework-Composer\Composer** folder and run the following command:
>
> ```
> yarn 
> ```

**Comment by v-kydela** [comment]
I'm noticing the document is also an example of inconsistency between "Composer" and "the Composer."

**Comment by zxyanliu** [comment]
Key, that's also a nice catch! 

FYI. There is some disagreement over if we should put the article "the" before "Composer". So far our team have agreed on using "The Bot Framework Composer" for the first time in a doc and use "Composer" later in the same doc. 

In the future, we might need to consult the product team to decide what is the official name for Composer. 

Thanks again for your feedback! : )

**Comment by v-kydela** [comment]
Of course
