### ISSUE TITLE
[Visual Designer] too much space below "User Answers" node

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#1930]
## Describe the bug

There is extra space below the "User Answers" node in the visual designer.

## Version

db239d0e

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge (chromium)

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## Screenshots

![image](https://user-images.githubusercontent.com/3619060/73575692-927b6980-442d-11ea-8c15-824755b3de27.png)

**Comment by yeze322** [comment]
working on it

**Comment by yeze322** [comment]
addressed in #1931
