### ISSUE TITLE
foreach loop functionality in Bot Framework Composer

### ISSUE THREAD

**Issue by SowmyaPitchika-Acu** [microsoft/BotFramework-Composer#1933]
I am working with array in bot framework composer. How to access the individual element of an array using foreach loop?

![Screenshot (3)](https://user-images.githubusercontent.com/60602402/73644938-526dee00-469c-11ea-92af-8963c9051e5b.png)

**Comment by luhan2017** [comment]
@SowmyaPitchika-Acu you can use dialog.foreach.index as the index and dialog.foreach.value as the value.
