### ISSUE TITLE
UX Copy: Remove "Event" from UX

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1938]
We've received feedback that there is confusion about both using the word trigger AND event. 
We'll be updating the 'create trigger' flow to avoid the word 'event' in the UX.
We should do a pass through the UX Copy to remove the others.

<img width="733" alt="Screen Shot 2020-02-03 at 7 38 10 PM" src="https://user-images.githubusercontent.com/48503434/73711853-0d0de880-46bd-11ea-8cfa-b47145bec7e0.png">

**Comment by vishwacsena** [comment]
@mareekuh are we doing anything here for R9? 

Dropping myself from assignee since I'm not actively working on this.

**Comment by mareekuh** [comment]
(approved) design is here: https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-%2F-UI-library?node-id=313%3A2806

The labels used in the menu should be the same as the ones in the UI.
Lmk if you have specific q's or when I can check out updates in the build (-:

**Comment by mareekuh** [comment]
Do you know if this is done? @vishwacsena s

**Comment by mareekuh** [comment]
@sangwoohaan - is this related to the UX terms PR you did the other day?

**Comment by zxyanliu** [comment]
Please see https://github.com/microsoft/BotFramework-Composer/issues/3175.
