### ISSUE TITLE
Migrate lubuild to bf cli tool chain

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#1943]
## Is your feature request related to a problem? Please describe.

we are using lubuild under tool utility and not fully move to bf lu cli. This does not impact user functionality but might buggy there and some latest feature for LU (eg. role labeling after luis publish does not well supported) . so we need to migrate lubuild to bf cli .

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1997
