### ISSUE TITLE
Delete Triggers and Dialogs

### ISSUE THREAD

**Issue by InDieTasten** [microsoft/BotFramework-Composer#1944]
## Is your feature request related to a problem? Please describe.

It's very easy to create new triggers and dialogs using the composer, but there is no way to remove previously created dialogs or triggers.

## Describe the solution you'd like

I'd like to have some sort of UI to be able to remove/delete triggers and dialogs.

## Describe alternatives you've considered

With dialogs I can at least delete the entire folder in the output location, but with individual triggers, I would have to manually edit the JSON, which is not a great experience at all.

## Additional context

Screenshot of trigger that I would like to remove:
![image](https://user-images.githubusercontent.com/7047377/73757101-f4f3a300-4768-11ea-98e7-32a020f714e0.png)
As you can see, there is no button for deleting the trigger itself. Only a button for deleting actions inside of the flow.

**Comment by cwhitten** [comment]
Hi @InDieTasten 

It is possible to delete a dialog or a trigger, but it's discoverability is lacking and we're looking to improve this. cc @sangwoohaan 

See attached for the menu control to delete a trigger. The same does for a Dialog (that isn't the Root/main dialog)

<img width="861" alt="Screen Shot 2020-02-04 at 1 48 05 PM" src="https://user-images.githubusercontent.com/1156704/73790292-15196700-4755-11ea-9296-67f9eeb83ea2.png">

**Comment by cwhitten** [comment]
Closing this as we have a UX workstream to improve the discoverability of this functionality tracked separately.

**Comment by InDieTasten** [comment]
@cwhitten 

Can you link the mentioned tracking?

Does this also cover deleting dialogs?
