### ISSUE TITLE
Visuals | New icon for error

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1947]
When there are errors in my expressions, a x (inside a circle) shows up. in order to see what the errors are, I need to click the x.
Normally, clicking an X results in closing a menu or deleting something, which makes me hestitant to click it, as I don't want it to go away (get deleted) before seeing what the errors are. Can we please use a bell or something that is typically used for notifcations? PVA uses this too.
For the page with the error list, is there another, more common icon we can use instead of the paint swatch?

<img width="318" alt="Screen Shot 2020-02-04 at 2 44 36 PM" src="https://user-images.githubusercontent.com/48503434/73794413-4007b900-475d-11ea-98c0-403529ef20f8.png">

**Comment by cwhitten** [comment]
This will ship with the updated diagnostics panel (and we've added a Bell icon)
