### ISSUE TITLE
Visuals | Improve node design for "Ask a question" nodes

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#1948]
When creating a prompt, 3 items appear on the canvas. One of them corresponds to the 'other' tab in the right pane. It contains the 'fall back' options for the prompt, in case the user input is invalid or is not understood. So technically it should be a re-prompt or 'fall back' node. Can we design something that better represent this than an (x) (especially since it is also used to indicate an error).

<img width="302" alt="Screen Shot 2020-02-04 at 2 49 16 PM" src="https://user-images.githubusercontent.com/48503434/73794831-1b601100-475e-11ea-8c24-c22c7df299e2.png">

**Comment by yeze322** [comment]
yes! it would a nice improvement. pls assign this item to me once design is ready

**Comment by cwhitten** [comment]
@mareekuh are you wanting to keep this open and assign a designer? I'd like to drive this to closure one way or another.

**Comment by mareekuh** [comment]
Yes this does need to get fixed. Both the representation in the canvas as well as the right-side pane, for 2 important reasons
- reduce friction when coming from PVA and creating prompts in BF (with this funky presentation, we're unnecessarily different from PVA in a way that is difficult to follow as there is no clear mapping between the 2 apps for this action
- the order in which the user is supposed to fill-out the fields (bot response, user input, other) is represented incorrectly. @sangwoohaan had done in-depth research here to figure out what the expected flow is. I really believe this will improve both the learning curve as well as speed-of-entry .

@sangwoohaan  has detailed designs for this ready to go

**Comment by mareekuh** [comment]
@sangwoohaan  - let's get the designs that improves the 'ask question' experience in terms of flow and alignment with the PVA experience. ours is too cumbersome.

**Comment by sangwoohaan** [comment]
This is a work in progress right now! ( https://www.figma.com/file/wh94oh7BPJdXwCK8kcZvDO/SH_Property-fields-and-more?node-id=560%3A257 ) <- These are still WIP stuff, miles and miles away from final designs

**Comment by mareekuh** [comment]
﻿Can you put some in-progress screenshots in and get this to a stable by R14?
It’s getting urgent to improve the transition from and to PVA.

From: sangwoohaan ***@***.***>
Date: Monday, April 26, 2021 at 4:56 PM
To: microsoft/BotFramework-Composer ***@***.***>
Cc: Marieke Iwema ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/BotFramework-Composer] Visuals | 'Other' is not an error, but is represented with a red (x) (#1948)

This is a work in progress right now! ( https://www.figma.com/file/wh94oh7BPJdXwCK8kcZvDO/SH_Property-fields-and-more?node-id=560%3A257<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.figma.com%2Ffile%2Fwh94oh7BPJdXwCK8kcZvDO%2FSH_Property-fields-and-more%3Fnode-id%3D560%253A257&data=04%7C01%7Cmariekei%40microsoft.com%7Ceaec5463aa7942d3b77008d9090ee894%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637550781914944885%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=19094zV7gbt6JiiZMCSmEQEU9U6%2F3ZUj9AQ7CvYP91s%3D&reserved=0> ) <- These are still WIP stuff, miles and miles away from final designs

**Comment by sangwoohaan** [comment]
Yeah this is gonna be stabled by R14. Here's the WIP 
![Frame 53151](https://user-images.githubusercontent.com/50963385/116306322-c5f49300-a759-11eb-85ae-41ea8b08864a.png)
