### ISSUE TITLE
Entity Recognizer functionality

### ISSUE THREAD

**Issue by SowmyaPitchika-Acu** [microsoft/BotFramework-Composer#1951]
I am trying to work on Entity Recognizer in a dialog. I need to know, how the individual Entity Recognizer works?  

![Screenshot (4)](https://user-images.githubusercontent.com/60602402/73832942-26cf3d00-482f-11ea-91e2-f0a65a462345.png)

**Comment by luhan2017** [comment]
@SowmyaPitchika-Acu which exact EntityRecognizer you want to understand? Let me explain how it works briefly. You can enable a "Microsoft.AgeEntityRecognzier" under a RegexRecognizer. Then is you input a message like "I am 10 years old", an age entity will be recognized and you can use it by "@age". Do you want a doc/sample to explain how all the EntityRecognizer work?

**Comment by SowmyaPitchika-Acu** [comment]
Hi Lu Han,
                    Thank you. I tried working on regex recognizer with the information which you gave. I got clarity about all the regex recognizer except Microsoft.RegExEntityRecognizer. Please provide doc/sample regarding RegExEntityRecognizer to be clear about that.

Thanks & Regards,
sowmya
Software Engineer - Trainee
Acuvate Software Pvt Ltd|1st & 2nd Floor MJR Arcade, Ayyappa Society,Madhapur.
Cont: 9908093646 | Visit us: www.acuvate.com<http://www.acuvate.com/>

[cid:image001.png@01D21980.077F7EB0]<http://www.acuvate.com/>[facebook-icon]<https://www.facebook.com/AcuvateSoftware>[twitter-icon]<https://twitter.com/Acuvate>[linkedin-icon]<https://www.linkedin.com/company/acuvate-software-pvt.-ltd>
Awarded 37th Rank among 50 Fastest Growing Technology Firms in India by Deloitte

**Comment by luhan2017** [comment]
@SowmyaPitchika-Acu Here is a sample of using RegexEntityRecognizer:
![image](https://user-images.githubusercontent.com/32191031/73923101-4afd4d80-4905-11ea-811f-c9e53b996a3d.png)

If you configure a RegexEntityRecognizer like the above, you will get a @color entity when you match the patten. 

Here is a more detailed example on declarative format: https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/RegexRecognizerTests/RegexRecognizerTests_Entities.test.dialog

Please let me know if you have any other questions.

**Comment by SowmyaPitchika-Acu** [comment]
Hi Lu Han,
                    Thank you. I am unable to trigger dialog when I am using RegExEntityRecognizer.

Thanks & Regards,
sowmya
Software Engineer - Trainee
Acuvate Software Pvt Ltd|1st & 2nd Floor MJR Arcade, Ayyappa Society,Madhapur.
Cont: 9908093646 | Visit us: www.acuvate.com<http://www.acuvate.com/>

[cid:image001.png@01D21980.077F7EB0]<http://www.acuvate.com/>[facebook-icon]<https://www.facebook.com/AcuvateSoftware>[twitter-icon]<https://twitter.com/Acuvate>[linkedin-icon]<https://www.linkedin.com/company/acuvate-software-pvt.-ltd>
Awarded 37th Rank among 50 Fastest Growing Technology Firms in India by Deloitte

**Comment by luhan2017** [comment]
We had disabled the EntityRecognizer in Regex in latest build and plan to support editing regex recognizer in the future. So I am closing this issue for now, please reopen it or file anther issue if necessary.
