### ISSUE TITLE
Should not require .NET Core SDK 2.2

### ISSUE THREAD

**Issue by aalmada** [microsoft/BotFramework-Composer#1953]
## Is your feature request related to a problem? Please describe.

The [setup page specifies `.NET Core SDK 2.2` as a requirement](https://github.com/microsoft/BotFramework-Composer/blob/49a5ef94b9a0123bcaab375f13172717c022301b/docs/setup-yarn.md).

As [it can be found on the .NET Core downloads page](https://dotnet.microsoft.com/download/dotnet-core), `.NET Core 2.2` as reached `end-of-life`.

![2020-02-05 10_43_14-Download  NET Core (Linux, macOS, and Windows) and 8 more pages - Profile 1 - Mi](https://user-images.githubusercontent.com/534533/73834937-7fd5ab80-4804-11ea-87bd-1227d88006de.png)

## Describe the solution you'd like

Either support `.NET Core SDK 2.1` or `.NET Core SDK 3.1` (recommended).

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/1939

**Comment by zxyanliu** [comment]
@hibrenda @boydc2014 The doc has been updated [here](https://docs.microsoft.com/en-us/composer/setup-yarn). 
If there is nothing else impacted, please feel free to close this issue. 

Thanks!
