### ISSUE TITLE
Language generation text window - very slow response, corrupted keystrokes

### ISSUE THREAD

**Issue by dinobrago** [microsoft/BotFramework-Composer#1956]
## Describe the bug
When typing into the language generation textbox, the lag between a keystroke and updating the textbox has become very long and keystrokes are often lost. 

## Version
Release Preview 2.0
Application SHA   test
SDK runtime packages
4.7.0-preview-191208-1

## Browser

- [X ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

This may be associated with my specific bot. But
1. Open a Dialog
2. Click on Begin Dialog
3. Add a "Send Response" to the flow
4. Click in the Language Generation window and begin typing

The characters do not immediately appear in the text box but lag behind your typing. In some cases keystrokes are lost. In other cases, clicking outside of the textbox forces a refresh and the characters appear. 

## Expected behavior

One expects that the text window will keep up with one's typing and update the text box in a timely fashion without losing characters. 

## Screenshots
![2F8BA5A9-19CA-4698-B97B-DCA49D27F957](https://user-images.githubusercontent.com/41213271/73895133-613ad900-4833-11ea-8a95-8c84d1f27018.GIF)

I was typing at a constant rate, it doesn't quite come across on the animated gif because you can't hear my keystrokes. Also, the longer you type, the slower the update frequency. Clicking outside of the textbox forces a refresh.

I've taken to composing the text in a text editor and pasting it into the language generation text box because it works around the problem. 
![ABCB798D-0E8A-45A4-80DB-032DC278DD72](https://user-images.githubusercontent.com/41213271/73895497-a7dd0300-4834-11ea-8a38-3d2f5be62375.GIF)

**Comment by zhixzhan** [comment]
Hi @dinobrago, It seems like a performance issue, I tried to re-produce it on my laptop ( Lenovo X1 2014) but it seems ok, no significant lag. Can you provide more information, or try it on another machine, make sure it's not some bug from bot.

**Comment by dinobrago** [comment]
I assume that it's a function of my bot. I see the problem on different machines. But it's a significant performance problem. I'll investigate what aspect of the bot send to be causing the problem.

________________________________

**Comment by cwhitten** [comment]
@dinobrago were you able to uncover anything in your bot?

**Comment by dinobrago** [comment]
No except that it seems to be a function of the number of items in the file. It's the auto complete that seems to be slow refreshing and causing problems for me. But I haven't spent any time investigating further.

Dean

________________________________

**Comment by cwhitten** [comment]
Can you attach the .lg file(s) in question?
