### ISSUE TITLE
Access to Channel Data

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#1958]
Hi all,
I need to access to Microsoft Teams informations, like _UPN, Email, Personal Image, Tenant Id_ (context information) and _Teams, Chat_ (Microsoft Teams application information that usually collect from Microsoft Graph).

Can Composer access to **channel informations**?
Composer can fill property with channel informations?

Thanks a lot

**Comment by luhan2017** [comment]
@andreatosato, We don't support this in Composer yet. You need to have another call to get the TeamsChannelInfo according to this doc https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet#nodejs-example

But in AdaptiveSDK., we don't have this built-in functionality yet.
@vishwacsena, do you have plan to support this?

**Comment by andreatosato** [comment]
@luhan2017 
how do I use this feature in the composer?
I have scenarios in which the composer speeds up development a lot but unfortunately we need to contextualize the user information in which the bot is installed.

I had already used the functionality described for TeamsChannelInfo in other Bots. I understand that at the moment code and composer are 2 separate worlds. So it is not possible to combine the two features.

**Comment by cwhitten** [comment]
@vishwacsena please assess if this can come in for R8, initial investigation suggests the cost is reasonable.

**Comment by andreatosato** [comment]
@cwhitten Is this feature confirmed in R8?
Thanks a lot

**Comment by vishwacsena** [comment]
@andreatosato adaptive dialogs (and hence composer) does not support `TeamsActivityHandler` 

You can get channel data directly available on the incoming activity via `turn.activity`. 

Tracked on SDK side via this ticket - https://github.com/microsoft/botbuilder-dotnet/issues/3566
