### ISSUE TITLE
Greeting needs to be updated in the Weather tutorial

### ISSUE THREAD

**Issue by aalmada** [microsoft/BotFramework-Composer#1962]
## Describe the bug

When following the Weather tutorial, on step ['Give your bot something to say'](https://github.com/microsoft/BotFramework-Composer/blob/1a750e5800639f50b6c27df5e34153d2efc86eb7/docs/tutorial/bot-tutorial-introduction.md#give-your-bot-something-to-say), it the shows the following image:

![Greeting](https://github.com/microsoft/BotFramework-Composer/blob/1a750e5800639f50b6c27df5e34153d2efc86eb7/docs/media/tutorial-weatherbot/01/new-flow.png?raw=true)

but what I find is the following

![Screen Shot 2020-02-06 at 12 44 09](https://user-images.githubusercontent.com/534533/73938090-76207680-48de-11ea-9379-f798802afc0e.png)

Both the images and the step descriptions need to be updated.

## Version

Stable

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by zxyanliu** [comment]
Hey @aalmada Thanks for reporting. We will update the screenshot soon. 
FYI. The most up-to-date docs are in the [master branch](https://github.com/microsoft/BotFramework-Composer/blob/master/toc.md).

**Comment by aalmada** [comment]
@zxyanliu This is found in [master branch](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/tutorial/tutorial-add-dialog.md#create-a-new-dialog). That's why I'm reporting. ;)

**Comment by zxyanliu** [comment]
Yes, that's a nice catch. We should fix that screenshot.

**Comment by zxyanliu** [comment]
Hey @aalmada I believe the issue you mentioned is addressed [here](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather). 
Therefore closing this issue. 
Thank!
