### ISSUE TITLE
Please fix the bug in the RespondingWithTextSample

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1963]
## Describe the bug

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/32497439/73966536-1076bf00-48cb-11ea-9354-9758c7bc9bc8.png)

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/32497439/73966545-1371af80-48cb-11ea-9b7c-8314bc88dd32.png)

## To Reproduce
1. Open the RespondingWithTextSample from Composer. 
2. See the error in the screenshots above. 

## Suggested solution 
Remove spaces b/w the words solves the problem. 

![73966791-909d2480-48cb-11ea-952b-9f7e789caf07](https://user-images.githubusercontent.com/32497439/73967118-2769e100-48cc-11ea-921d-cce9c418b224.png)

## Expected behavior
Please fix the bug as suggested.

**Comment by zxyanliu** [comment]
FYI. @WashingtonKayaker.

**Comment by hibrenda** [comment]
@zxyanliu Close this as the sample template won't change once we adopt latest SDK changes for string and expression alignment.
