### ISSUE TITLE
POST 500 directline.conversations.:conversationId.activities

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#1965]
## Describe the bug

Whenever I start a bot where LUIS is used (so not an echo bot) even if I don't change anything the emulator outputs **POST 500 directline.conversations.:conversationId.activities** as soon as I hit the endpoint in the emulator. Have tried several LUIS keys all with the same result. The LUIS apps get created correctly by Composer and the model is fine, but I cannot chat with the bot. If I remove the LUIS intent triggers from the bot in Composer, it works fine.

![image](https://user-images.githubusercontent.com/29750798/73969679-29f42700-491c-11ea-8a75-504c61804164.png)

## Version

test

## Browser
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by SiarheiKuchukBelitsoft** [comment]
I have the same issue

**Comment by SiarheiKuchukBelitsoft** [comment]
![image](https://user-images.githubusercontent.com/60220228/75159634-94350600-5729-11ea-99d6-16d31a78943a.png)

**Comment by boydc2014** [comment]
Hi @stephanbisser  @SiarheiKuchukBelitsoft  we have some changes recently, can you try the latest master and make sure you create a new bot (otherwise you are still using the old runtime bits), see if it still an issue?

**Comment by SiarheiKuchukBelitsoft** [comment]
Hello

@boydc2014 . My issue has been resolved by adding postfix to bot URL in bot emulator /api/messages. I with I wouldn't do prefixes but I understand why it should be so.

**Comment by stephanbisser** [comment]
@boydc2014 works now thanks!

**Comment by Vrushil12** [comment]
Hey @SiarheiKuchukBelitsoft, Actually I am facing same issue. So can you help me with adding postfix to the bot URL in bot emulator /api/messages??
Thank you in advance!!

**Comment by SiarheiKuchukBelitsoft** [comment]
@Vrushil12  
Upon connection Bot Emulator will ask for URL.
Specify http://127.0.0.1:3978/api/messages 
(localhost or http://127.0.0.1:3978 won't work)

**Comment by sposaro** [comment]
I'm also hitting this issue in 4.1.8 framework + Luis (the 127.0.0.1 did not help).
It didn't seem to start happening until I added back in the ConverstationState to my bot.

**Comment by rehakara** [comment]
Version 4.8.1 and I'm using ConversationState+UserState in my bot. Having the same 500 issue. Is there any update about this issue?

**Comment by cwhitten** [comment]
hello @sposaro & @rehakara 

can your attach your bot assets assets, or a smallest representation that reproduces the issue? I'm unable to reproduce by using both user & conversation state in my bot.

**Comment by Arjun-Jakka-Sridhar** [comment]
![image](https://user-images.githubusercontent.com/72132528/95392387-4666ba00-0916-11eb-844d-576bd7057b5c.png)



Can somebody please tell me why I am getting POST 500 and how to resolve it?

Thank You

**Comment by divyesh-inferenz-ai** [comment]
@SiarheiKuchukBelitsoft your solution does not resolve this issue.

@Arjun-Jakka-Sridhar I am facing the same issues
can anyone have any solution regarding this issue? please help.

Thank you in advance.

**Comment by rvinothrajendran** [comment]
@divyesh-inferenz-ai  ref here : https://github.com/Microsoft/botframework-sdk/issues/4184
maybe it will help

**Comment by divyesh-inferenz-ai** [comment]
Can you suggest how to integrate any bot framwork chatbot with existing
android application?

Thanks & Regards,
Divyesh.

**Comment by parsalotfy** [comment]
same issue [here](https://github.com/microsoft/botframework-sdk/issues/6285)

**Comment by anjaligarg29** [comment]
[16:38:50]POST500directline/conversations/<conversationId>/activities getting same error what should i do
