### ISSUE TITLE
RespondingWithCardsSample not start bot

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#1967]
Start Bot (RespondingWithCardsSample-0) not work
I download latest BotFramework-Composer, so I build with yarn and run at localhost:3000.
After that, I create default template Bot with Card Response.

## Version
![image](https://user-images.githubusercontent.com/24985956/74020296-89dce300-4999-11ea-9153-d1379d505935.png)

## Browser
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

#dotnet cli versions
My machine have .net core 3.1 and 2.2 and 2.1 installed
![image](https://user-images.githubusercontent.com/24985956/74023353-c3b0e800-499f-11ea-8614-7dd02f2d4884.png)

## To Reproduce
Start template bot Respond with card.
`Could not execute because the specified command or file was not found. Possible reasons for this include: * You misspelled a built-in dotnet command. * You intended to execute a .NET Core program, but dotnet-bin/Debug/netcoreapp2.1/BotProject.dll does not exist. * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
`
## Expected behavior
Start bot applications

## Screenshots
![image](https://user-images.githubusercontent.com/24985956/74020121-281c7900-4999-11ea-9feb-9096cf415214.png)

**Comment by andreatosato** [comment]
2 Method
### Docker-Compose
PS D:\GitHub\BotFramework-Composer-stable> docker-compose up
Building composer
Step 1/27 : FROM node:12-alpine as build
 ---> afd897e3184b
Step 2/27 : WORKDIR /src/Composer
 ---> Using cache
 ---> 1f4db2feca9c
Step 3/27 : COPY . .
 ---> Using cache
 ---> c82198223eae
Step 4/27 : RUN yarn install --frozen-lock-file
 ---> Using cache
 ---> e4c88766a5cb
Step 5/27 : ENV NODE_OPTIONS "--max-old-space-size=4096"
 ---> Using cache
 ---> 05b5ed2b7b4b
Step 6/27 : ENV NODE_ENV "production"
 ---> Using cache
 ---> f292c75b2790
Step 7/27 : RUN yarn build:prod
 ---> Running in 97748ce09733
yarn run v1.21.1
$ yarn build:dev && yarn build:server && yarn build:client
$ yarn build:lib && yarn build:tools && yarn build:extensions
$ yarn workspace @bfc/libs build:all
$ yarn build:shared && yarn build:indexers && yarn build:code-editor
$ cd shared && yarn build
$ yarn clean && yarn build:css && yarn build:ts
$ rimraf lib demo/dist
$ copyfiles --up 1 "src/**/*.css" "src/**/*.scss" lib
$ tsc --build tsconfig.build.json
$ cd indexers && yarn build
$ yarn clean && yarn build:css && yarn build:ts
$ rimraf lib demo/dist
$ copyfiles --up 1 "src/**/*.css" "src/**/*.scss" lib
$ tsc --build tsconfig.build.json
$ cd code-editor && yarn build
$ yarn clean && yarn build:css && yarn build:ts
$ rimraf lib demo/dist
$ copyfiles --up 1 "src/**/*.css" "src/**/*.scss" lib
$ tsc --build tsconfig.build.json
$ yarn workspace @bfc/tools build:all
$ concurrently --kill-others-on-fail "yarn:build:language-servers"
[build:language-servers] $ cd language-servers && yarn build
[build:language-servers] $ yarn build:lg && yarn build:lu
[build:language-servers] $ cd language-generation && yarn build
[build:language-servers] $ tsc --build tsconfig.build.json
[build:language-servers] $ cd language-understanding && yarn build
[build:language-servers] $ tsc --build tsconfig.build.json
[build:language-servers] yarn run build:language-servers exited with code 0
$ yarn workspace @bfc/extensions build:all
$ concurrently --kill-others-on-fail "yarn:build:obiformeditor" "yarn:build:visual-designer"
[build:obiformeditor] $ cd obiformeditor && yarn build
[build:visual-designer] $ cd visual-designer && yarn build
[build:visual-designer] $ yarn clean && yarn build:css && yarn build:ts
[build:obiformeditor] $ yarn clean && yarn build:css && yarn build:ts
[build:visual-designer] $ rimraf lib demo/dist
[build:obiformeditor] $ rimraf lib demo/dist
[build:visual-designer] $ copyfiles --up 1 "src/**/*.css" "src/**/*.scss" lib
[build:obiformeditor] $ copyfiles --up 1 "src/**/*.css" "src/**/*.scss" lib
[build:visual-designer] $ tsc --build tsconfig.build.json
[build:obiformeditor] $ tsc --build tsconfig.build.json
[build:visual-designer] yarn run build:visual-designer exited with code 0
[build:obiformeditor] yarn run build:obiformeditor exited with code 0
$ yarn workspace @bfc/server build
$ tsc -p tsconfig.build.json
$ yarn workspace @bfc/client build
$ node scripts/build.js
Creating an optimized production build. This may take a few minutes..
error Command failed with signal "SIGKILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.21.1/lib/cli.js build
Directory: /src/Composer/packages/client
Output:

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Service 'composer' failed to build: The command '/bin/sh -c yarn build:prod' returned a non-zero code: 1

**Comment by hibrenda** [comment]
Please reference https://github.com/microsoft/BotFramework-Composer/issues/1927

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/issues/1927
