### ISSUE TITLE
How to get user's first name or last name in facebook messenger using bot composer

### ISSUE THREAD

**Issue by swaraj27** [microsoft/BotFramework-Composer#1968]
Bot Info  
    -SDK Platform: .NET
    -SDK Version: 3.0.10.
    -Active Channels: WebChat, Facebook
    -Deployment Environment: Azure App Service

Issue Description: 
   I m taking Http request. I put there url of  Graph Api Explorer of my facebook developer account where I keep my bot page, Here I m getting the the user's first name , But the problem is while I m testing it in another device on different facebook account I m getting  my name in another messenger account. 
  I want to display the first name as per there respective account of the user. I am waiting for reply

**Comment by andreatosato** [comment]
#1958 Similar to this request.
Channel data informations is not supported
