### ISSUE TITLE
 but dotnet-bin/Debug/netcoreapp2.1/BotProject.dll does not exist. * You intended to run a global tool, but a dotnet-prefixed

### ISSUE THREAD

**Issue by jssuthahar** [microsoft/BotFramework-Composer#1969]
Hi All,
I have done all set up, but while starting its getting following error , any idea why i am getting 

Sorry, something went wrong with connecting bot runtime

Could not execute because the specified command or file was not found. Possible reasons for this include: * You misspelled a built-in dotnet command. * You intended to execute a .NET Core program, but dotnet-bin/Debug/netcoreapp2.1/BotProject.dll does not exist. * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by andreatosato** [comment]
Similar ti #1967

**Comment by jssuthahar** [comment]
@andreatosato 
Project template having issues, just follow here for now #1927

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/issues/1927
