### ISSUE TITLE
list and generic template to be added in channel data (facebook messenger) composer

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#1970]
Right now i have created some dialogs and using those dialogs in echo bot and i have connected to facebook i'm able to render hero cards in messeger cause hero cards are adding into the attachments but now i want to deisplay generic template in messager for we need to add generic tempate json to channel data . it is possible ? if how to add template json to channel data

https://developers.facebook.com/docs/messenger-platform/reference/template/generic

**Comment by hibrenda** [comment]
similar to #1958

**Comment by cwhitten** [comment]
Closing. See #1958
