### ISSUE TITLE
cannot connect to a bot runtime, make sure you start the bot runtime

### ISSUE THREAD

**Issue by prasadreddybv** [microsoft/BotFramework-Composer#1971]
I am getting the below error while running the bot.

![image](https://user-images.githubusercontent.com/28754600/74145844-c755a080-4c25-11ea-948b-c20347242412.png)

It was working on the other day but TodayI have got the latest stable version of Composer and it started giving the above error since then. Please help on this if anybody have came across on this.

Please check the below terminal message.

![image](https://user-images.githubusercontent.com/28754600/74146066-4d71e700-4c26-11ea-91f0-ac85fbd6cebd.png)

It was working earlier though i have not provided the endpoint key.

**Comment by VanyLaw** [comment]
@prasadreddybv Do the request for `POST /api/projects/opened/luFiles/publish `api get 200? which http request you got 400? in `GET /api/launcher/connect` or  `POST /api/launcher/sync` ?
FYI. 
![image](https://user-images.githubusercontent.com/21174180/74231030-9007f200-4d00-11ea-856d-d408aed4646e.png)

**Comment by prasadreddybv** [comment]
@VanyLaw Please check below.

![image](https://user-images.githubusercontent.com/28754600/74232130-28e14200-4cee-11ea-85fe-9d04aa925828.png)

**Comment by VanyLaw** [comment]
Your luis publish is successful. But you failed in connect api, maybe it's because your firewall. Can you run `yarn build`, `yarn start` again, then opening in other browser or new traceless window to try it?

**Comment by prasadreddybv** [comment]
I tried yarn build command and got the below errors.

![image](https://user-images.githubusercontent.com/28754600/74323199-2abd0b00-4dab-11ea-8596-b0909585568d.png)

**Comment by prasadreddybv** [comment]
@VanyLaw - I ran the **yarn build, yarn start** commands and opened in a new window. Nowi got a new error as shown below.

![image](https://user-images.githubusercontent.com/28754600/74333589-3b2ab100-4dbe-11ea-9a99-6de785e47102.png)

I am not sure which command i am missing out here. please help me out.

**Comment by VanyLaw** [comment]
Hi @prasadreddybv, This error was bot runtime build failed. It's because we need to update the reference packages and schema. We will fix it in master branch soon.
FYI.
https://github.com/microsoft/BotFramework-Composer/pull/1939
https://github.com/microsoft/BotFramework-Composer/issues/1927

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/issues/1927
