### ISSUE TITLE
[Linting & Validation] some diagnostics do not get reported in form due to path format

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#1972]
## Describe the bug

Fields in deep paths do not show errors in the form.

## Version

22685455

## To Reproduce

1. Open up the `Dialog Actions` sample.
2. Go to the `SwitchConditon` dialog.
3. In the `SwitchConditon` action, add an action that includes a condition
4. Add an invalid condition, ex. `foo = bar`
5. Notice the error appears in the notifications page, but not in the form.

## Expected behavior

Error should also appear in the form.

## Screenshots

![image](https://user-images.githubusercontent.com/3619060/74184085-facf0580-4bfa-11ea-858c-46b0fb44c61c.png)

## Additional context

LG errors still show in the form.

**Comment by a-b-r-o-w-n** [comment]
This has not been fixed following the repro steps in b2501bf8

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2013
