### ISSUE TITLE
Aligning the array UI implementation

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1974]
The implementations of array UI seem to be different in some action nodes.

Branch : Switch - has an unnecessary 'value' label between 'Case' and the array.
![Screen Shot 2020-02-10 at 9 55 13 AM](https://user-images.githubusercontent.com/50963385/74187952-6668a100-4c02-11ea-9f16-356d41671a1a.png)

Intent recognized, Delete properties - missing the stroke below the title
![Screen Shot 2020-02-10 at 9 56 27 AM](https://user-images.githubusercontent.com/50963385/74188256-ef7fd800-4c02-11ea-8c37-323ed45c8990.png)
![Uploading Screen Shot 2020-02-10 at 9.54.05 AM.png…]()

In prompt nodes - indented, and missing the stroke
![Screen Shot 2020-02-10 at 9 54 15 AM](https://user-images.githubusercontent.com/50963385/74188391-2a820b80-4c03-11ea-90e3-3d9a7485ddf7.png)

**Comment by sangwoohaan** [comment]
Refer to this [link](https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=4661%3A46) for the correct design

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2118
