### ISSUE TITLE
Recognizer settings UI for dialogs(esp. for RegEx)

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#1976]
The property editor UI for dialog recognizers don't fit the design system, and it also has a few gaps to the design. I did a path on a new design here:
https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=4663%3A156

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1991
