### ISSUE TITLE
[LU Editor] support inline LU section editing 

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#1980]
## Is your feature request related to a problem? Please describe.

To support LU intent (section) editing in form, visual, we need implement Inline-LU Editor base on recently integrated LU LSP.

### Areas:
1. LU all up view intent editing.
2. Visual page new trigger creating.
3. Form editor inputs components.

### Inline features:
- LU syntax highlight.
- LU content validation.
- SubSection / Nested section editing.

### Related works:
https://github.com/microsoft/BotFramework-Composer/pull/1786 @liweitian 
https://github.com/microsoft/BotFramework-Composer/issues/1641

https://github.com/microsoft/BotFramework-Composer/issues/1848 @alanlong9278 
https://github.com/microsoft/BotFramework-Composer/issues/1598

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/1994
