### ISSUE TITLE
The Asking Questions Sample - a few questions

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1983]
Here are a few questions Steve (@WashingtonKayaker) and I have about the [AskingQuestions](https://github.com/microsoft/BotFramework-Composer/tree/stable/Composer/packages/server/assets/projects/AskingQuestionsSample/ComposerDialogs) Sample. 

###  1. About _Always prompt_
Does **Max turn count** overwrite **Always prompt**? Testing the **Always prompt** functionality in the sample and no difference found in bot's behavior b/w when it is checked or unchecked. 

![image](https://user-images.githubusercontent.com/32497439/74269399-4bf3fd80-4cbe-11ea-8ebc-5eed0161f352.png)

###  2. About _Confirm Options_
The **Confirm Options** section in the **ConfirmInput** prompt is confusing. Does **ConfirmInput** prompt needs **Confirm Options** as **ChoiceInput** does? Testing adding the following options and found selecting the first option will always return "confirmation: True" and the rest all return "confirmation: False". 

![image](https://user-images.githubusercontent.com/32497439/74270128-932ebe00-4cbf-11ea-9418-f332530e7e4f.png)

Testing in the Emulator: 

![image](https://user-images.githubusercontent.com/32497439/74270313-dee16780-4cbf-11ea-9ea4-9e3bb767529e.png)

### 3. About _Append choices_

What does **Append choice** do in **ChoiceInput** prompt? What impacts will this option have when checked and unchecked? what other fields it depends on or is related to? 

![image](https://user-images.githubusercontent.com/32497439/74270822-b27a1b00-4cc0-11ea-852f-41979901c3a3.png)

### 4. About _OAuth login_
The **OAuth login** prompt under the **Ask a quesiton** action. Is there any difference b/w the  **OAuth login** prompt under the **Ask a quesiton** action and the **OAuth login** action under the **Access external resources** action menu?  

![image](https://user-images.githubusercontent.com/32497439/74271311-86ab6500-4cc1-11ea-8e08-7c5dc9dc4eb9.png)

![image](https://user-images.githubusercontent.com/32497439/74271485-d38f3b80-4cc1-11ea-8fd5-a6a7930b5ec5.png)

**Comment by luhan2017** [comment]
Thanks for the feedbacks. 
1. InputsDialog has a feature that if you configure the Value property, for example, user.age. The InputDialog will check whether user.age has a value, if it has, then it will not prompt. 
AlwaysPrompt is used to prompt an input whenever the Value property has a value. 

Maxcount is not related AlwaysPrompt, it is used with defaultValue, if the user's input didn't pass the validation, it will reprompt. and if the reprompt times reaches maxcount, it will returns default value. 

2. The choiceOptions in Confirm Input is just a way to provide alternative way to tweak the choices rendered to the user. In most cases, it is not needed to confirm that. 

3. It looks like a schema bug, the appendChoices didn't map to any logic in the code, I will follow up on the sdk side. 

4. the two OAuthInput are exactly the same, we may need to consider to just keep one of them.

**Comment by hibrenda** [comment]
@mareekuh @sangwoohaan  we may need UI updates for item 2 and minor change for item 4 of the duplicated fly-out menu. @luhan2017 will evaluate item 3 .

**Comment by zxyanliu** [comment]
Closing this issue for now and will probably reopen it later when necessary.
