### ISSUE TITLE
Error when using RegEx in Validation Rule

### ISSUE THREAD

**Issue by MuellerEric** [microsoft/BotFramework-Composer#1985]
Hello everyone,

I am using the most up to date version of composer (`v1.21.1`).

In my bot, I have a 'Text Input' action to ask the user for a email address.
I want to validate the user input by using a validation rule. This rule is based on a RegEx.

As stated in your documentation, I used the `isMatch` Method. The parameters are `this.value` and `^[a-zA-Z0-9.!#$%&’*+/=?^_\``{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$`

I got the RegEx from [here](https://emailregex.com/)

Now here is the problem: I get an error in the BotComposer:
![image](https://user-images.githubusercontent.com/22045540/74325759-78c11700-4d89-11ea-9e6e-97c029fb2912.png)

Additionally, I have another maschine on which I developped the Bot using the Composer Version `v1.19.2`. On this maschine the validation works.

Can anyone help me ?

Best regards,
MuellerEric

**Comment by cwhitten** [comment]
@boydc2014 & @lei9444 are you tracking this?
