### ISSUE TITLE
OAuth Signin

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#1986]
I user OAuth SignIn in my sample.
I configure Bot Channel with AAD v2 and I started from: [docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp#create-your-azure-ad-application)
## Version
2.0 preview
## Browser
Teams Channel and ngrok
## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
I follow this:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp#create-your-azure-ad-application

Response is **BAD REQUEST**.
I saw microsoft login (Office 365) page of my corporation, but after login, we not return on bot but have Bad Request.

**Comment by zxyanliu** [comment]
Hi! Thanks for your feedback. Please follow this OAuth doc [here](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/how-to-use-oauth.md).
