### ISSUE TITLE
The Controlling Conversation Flow sample - questions

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#1990]
Here are a few questions Steve (@WashingtonKayaker) and I have about the [ControllingConversationFlowSample](https://github.com/microsoft/BotFramework-Composer/tree/stable/Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs). 
#### 1. The _Dialog actions_. 

In this sample, three dialog actions are covered: **Cancel all dialogs**, **Repeat this dialog**, and **End dialog turn**. There are six _dialog actions_ under the **Dialog management** action menu. 

![image](https://user-images.githubusercontent.com/32497439/74364712-896d8f00-4d81-11ea-8e00-4248fd1fc91e.png)

#### 2. The _Begin a new dialog_ Properties pane
This is not sample-specific, it is a general question. 

- How to use the **Key** and **Value** fields in **Options**? 
- How to use the **Property** field? 
- What does **Include Activity** do? what impact it will have when checked and unchecked? 

![image](https://user-images.githubusercontent.com/32497439/74364221-faf90d80-4d80-11ea-90e2-89ee3a31372e.png)

Thanks!

Yan

**Comment by luhan2017** [comment]
I've already resolved this with Yan offline.
