### ISSUE TITLE
Question: How to access a JSON inner value?

### ISSUE THREAD

**Issue by aalmada** [microsoft/BotFramework-Composer#1992]
The weather tutorial gets the following JSON response from the weather service:

```json
{
  "id": 500,
  "main": "Rain",
  "description": "light rain",
  "icon": "http://openweathermap.org/img/wn/10n@2x.png",
  "weather": "Rain",
  "temp": 31,
  "high": 33,
  "low": 30,
  "rain": true,
  "city": "Schenectady"
}
```

It then stores the content in `dialog.weather` and gets the weather and temperature using `The weather is @{dialog.weather.weather} and the temp is @{dialog.weather.temp}&deg;`

I'm trying to use [OpenWeather](https://openweathermap.org/) service which returns the following JSON:

``` json
{
    "coord": {
        "lon": -9.13,
        "lat": 38.72
    },
    "weather": [
        {
            "id": 300,
            "main": "Drizzle",
            "description": "light intensity drizzle",
            "icon": "09d"
        }
    ],
    "base": "stations",
    "main": {
        "temp": 288.12,
        "feels_like": 287.16,
        "temp_min": 287.15,
        "temp_max": 288.71,
        "pressure": 1026,
        "humidity": 93
    },
    "visibility": 10000,
    "wind": {
        "speed": 3.1,
        "deg": 210
    },
    "clouds": {
        "all": 75
    },
    "dt": 1581595588,
    "sys": {
        "type": 1,
        "id": 6901,
        "country": "PT",
        "sunrise": 1581579052,
        "sunset": 1581617449
    },
    "timezone": 0,
    "id": 2267057,
    "name": "Lisbon",
    "cod": 200
}
```

I also store the content in `dialog.weather` and then try to get the same info using `The weather is @{dialog.weather.weather.main} and the temp is @{dialog.weather.main.temp}&deg;`. I get the following error: `common.lg:Error occurs when evaluating expression bfdactivity-738194(): Error occurs when evaluating expression ‘dialog.weather.weather.main’: dialog.weather.weather.main is evaluated to null`

If I use this instead: `The weather is @{dialog.weather.weather} and the temp is @{dialog.weather.main}&deg;`. I don't get an error but the following: `The weather is [ { “id”: 802, “main”: “Clouds”, “description”: “scattered clouds”, “icon”: “03d” } ] and the temp is { “temp”: 16.05, “feels_like”: 16.23, “temp_min”: 15, “temp_max”: 16.67, “pressure”: 1025, “humidity”: 87 }°`.

**Comment by luhan2017** [comment]
@aalmada , could you try this: The weather is @{dialog.weather.weather[0].main} and the temp is @{dialog.weather.main.temp}. weather property is an array, so you need to query the item by index.

**Comment by aalmada** [comment]
@luhan2017 Thank you so much for the help!

Just for reference, using this card:

``` 
[ThumbnailCard
    title = Weather for @{dialog.weather.name}
    text = The weather is @{dialog.weather.weather[0].main} and @{dialog.weather.main.temp}&deg; (feels like @{dialog.weather.main.feels_like}&deg;)
    image = http://openweathermap.org/img/wn/@{dialog.weather.weather[0].icon}@2x.png
]
```

I now get the following:

<img width="493" alt="Screen Shot 2020-02-17 at 10 01 54" src="https://user-images.githubusercontent.com/534533/74643447-a1238980-516c-11ea-9b3a-709c089fec7a.png">
