### ISSUE TITLE
Output of the code in python

### ISSUE THREAD

**Issue by mounikac16** [microsoft/BotFramework-Composer#1993]
We are currently working on bot framework in python. The bot composer has made dialog writing a great deal easier but the generated code is in C#. It would be great if there was an option to choose the language, where the generated code can be in python.

**Comment by cwhitten** [comment]
Hello @mounikac16.

Adaptive Dialog support in the Bot Framework SDK is limited to C# at the moment. We will introduce additional language support in the future. Your request will help us prioritize this effort. 

I'll pin this issue so the community can participate in this discussion.

**Comment by vijaysaimutyala** [comment]
+1 

We also have our existing bots built in Python and our future bots will also be in Python. Would love to have Python support.

**Comment by phrenol** [comment]
Same here. Would be awesome!

**Comment by bradrlaw** [comment]
Have a client that asked for this today.  They would be porting their existing bots from the Rasa framework and really liked the integration of the LU/LG files into the tooling.

**Comment by khandelwal-aman** [comment]
Any idea when this feature would be available for usage??

**Comment by thakursarvesh** [comment]
I am also looking forward for it. any eta when this would be added?
