### ISSUE TITLE
Get weather report property

### ISSUE THREAD

**Issue by bigdatawork** [microsoft/BotFramework-Composer#1999]
When attempting to follow this guide
https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial/bot-tutorial-get-weather.md

I cannot get any of the properties to work as documented. If the branch I was able to get '{this.vaue}' to work only after changing it to '{this.vaue}'. I have attempted every variation I could to get {user.zipcode} to populate but I cannot get the value to pass. 

In step 8 trim is also incorrect because there is not a trim value that doesnt accept a parameter
so 'should' be something like trim('{user.zipcode}')..... if I could get the value to fill in
https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/common-expression-language/prebuilt-functions.md#trim

## Version

4.7.0-preview-191208-1

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'just follow the instructions from the first link'
2. Click on ''
3. Scroll down to 'step 8'
4. Run the bot and '{this.value}' throws an error if you use the word tomato

**Comment by zxyanliu** [comment]
Hey @bigdatawork Thanks for your report. 
Please read the [doc](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/tutorial/tutorial-get-weather.md) in the master's branch.
