### ISSUE TITLE
Bot created using Microsoft BotFramework Composer fails to launch after deployment

### ISSUE THREAD

**Issue by deenaMaistering** [microsoft/BotFramework-Composer#2001]
Bot created using Microsoft Bot Framework Composer fails to launch after deployment.
While running the code locally, it shows the error as it is looking for a file with the name "Main.lu.dialog" which does not exist. 

![bot-composer-error](https://user-images.githubusercontent.com/55096753/74721217-0bb3f280-525d-11ea-8d38-7646c5fc504a.jpg)

**Comment by hibrenda** [comment]
@deenaMaistering  Could you click "start bot" inside composer before you run it locally ?

**Comment by SowmyaPitchika-Acu** [comment]
**@deenaMaistering** When you update your composer you need to click "start bot" to save the changes and then you can run it locally.The error is because you did not click "start bot" and trying to run it locally.

**Comment by deenaMaistering** [comment]
Ok. Thank you @hibrenda and @SowmyaPitchika-Acu. But my bot still doesn't get launched after deployment. So I started the same sample with a fresh install and deployed weather bot sample step by step. It started to work in the web app but got stuck when I included LUIS as a recognizer. Now it shows "Invalid URI: The hostname could not be parsed" as a response while invoking with an utterance.
![Screenshot (43)](https://user-images.githubusercontent.com/55096753/74937874-f5e82e00-5412-11ea-80b2-b38eec96a7bb.jpg)

**Comment by SowmyaPitchika-Acu** [comment]
**@deenaMaistering** I feel that the luis format what you have added in **appsettings.json** is incorrect. Try to add luis in **appsettings.json** in the below format.

![Screenshot (6)](https://user-images.githubusercontent.com/60602402/74940066-ec60c500-5416-11ea-8bdf-43b1a8560bf4.png)

**Comment by deenaMaistering** [comment]
@SowmyaPitchika-Acu Thank you... It working!
