### ISSUE TITLE
Teams Channel - Actionable Designer

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#2002]
Hi folks,
I need some clarification about Adaptive Card and Action.
I create some Card Action with Confirm Button.
When Confirm Button is pressed, I need to post json to my API. Great works, but...
Now bot flow is locked, bot wait something.

I need to design some UI like this samples ([https://amdesigner.azurewebsites.net/](https://amdesigner.azurewebsites.net/))

Reference articles...
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions

https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook#incoming-webhook-key-features

_Teams bots, messaging extensions, and the Bot Framework support Adaptive Cards, an open cross-card platform framework. Teams connectors do not currently support Adaptive Cards. However, it is possible to create a flow that posts adaptive cards to a Teams channel._

Now I am a bit confused.
Please, explain me. I need to:

1. Collect data from Card Action and post json
2. Read Button clicked and data that user write in card
3. Create some if/else flow based on Card input field.

**Comment by andreatosato** [comment]
Related questions:
I create this example Action Card:
[https://adaptivecards.io/explorer/Action.Submit.html](https://adaptivecards.io/explorer/Action.Submit.html)

```javascript
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [
		{
			"type": "TextBlock",
			"text": "Present a form and submit it back to the originator"
		},
		{
			"type": "Input.Text",
			"id": "firstName",
			"placeholder": "What is your first name?"
		},
		{
			"type": "Input.Text",
			"id": "lastName",
			"placeholder": "What is your last name?"
		}
	],
	"actions": [
		{
			"type": "Action.Submit",
			"title": "Action.Submit",
			"data": {
				"x": 13
			}
		}
	]
}
```

This work great at UI level, but, flow go to next step.

I need to read Input.Text field and then design if/else flow.
**How do I wait for an answer?**

**Comment by andreatosato** [comment]
Related question:
**How can I read the value of the variables of the previous adaptive card?**

**Comment by cwhitten** [comment]
@andreatosato please use stackoverflow for how-to questions. Closing

**Comment by andreatosato** [comment]
@cwhitten 
You'd tell me that you can't use Adaptive Card with Action.Submit?
This feature is missing.

It's not a question from "How does it work!"

**Comment by andreatosato** [comment]
@cwhitten can you please reopen?
Adaptive card with Action Submit not wait response and skip to next step.
This is clearly a bug.

**Comment by luhan2017** [comment]
@andreatosato , Composer will support this after we enable an AdaptiveCardRecognizer which is already enabled in the SDK. We are actively investigating on this and will release it in our R10.

**Comment by luhan2017** [comment]
@andreatosato, we release the AdaptiveCardRecognizer in the latest main branch and Electron 1.1.1, could you please have a try on this? close this issue, and please feel free to reopen it if nessessary.
