### ISSUE TITLE
Teams Channel - Incoming Messages

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#2003]
I need to post messages to bot or to Teams user.

Scenario:
**Bot need to receive messages**

I plan to support approval flow to my bot.
So, when UserA send request, we need to accomplish 2 operation.
1. ManagerA receive message directly
2. UserA, wait (lock or not lock) approval flow from ManagerA.

Can I implement this flow?

**Comment by xieofxie** [comment]
Hi @andreatosato you need proactive message.
I am not sure if this is supported in Composer now? @hibrenda

If not, you could use it directly via SDK https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/16.proactive-messages 
or use code from Solutions https://microsoft.github.io/botframework-solutions/solution-accelerators/samples/proactive-notifications/

Once you could use proactive message, you could then 
* UserA sends request and bot sends proactive message to ManagerA
* ManagerA sends approval and bot sends result to UserA

Thanks

**Comment by xieofxie** [comment]
More info that may be helpful 
* https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp
* https://github.com/microsoft/botbuilder-dotnet/issues/3191

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/1515 At this moment, we don't support it but this feature is on our roadmap.

**Comment by andreatosato** [comment]
@xieofxie I know proactive message but it requires code. Bot Framework Composer and Proactive message is not support for now :(

**Comment by cwhitten** [comment]
Closing. See https://github.com/microsoft/botbuilder-dotnet/issues/3566 for updates
