### ISSUE TITLE
Visualize Adaptive Dialogs from code in Composer canvas 

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#2008]
Consider feature support for the following scenario:
1. Author bots using adaptive dialog code
2. Visualize the bot dialog hierarchy in composer (RO)
(3. Stretch: partial RW edit / annotate code)

Useful for design reviews.

**Comment by hibrenda** [comment]
This is also the requirement from skill team for "When the dialog is too many it is hard to manage them in one level."
