### ISSUE TITLE
Need a lighweight lg text syntax highlighting lib used in Visual Editor

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2010]
## Is your feature request related to a problem? Please describe.
Relates to #1701 . In the new design, Lg text inside a block will be displayed as it is in LgEditor, with specific colors.

However, we can't reuse current lg-editor. The problem is, LgEditor([code-editor](https://github.com/microsoft/BotFramework-Composer/blob/stable/Composer/packages/lib/code-editor/src/languages/lg.ts)) depends on monaco and LSP heavily, it's not very easy to port the whole lib to Visual Editor.

Considering the scenario in Visual Editor is readonly, we need a lightweight lib to provide this feature.

## Describe the solution you'd like
![image](https://user-images.githubusercontent.com/8528761/74804585-9eb36200-531b-11ea-9982-01d8c129f4fc.png)
### [Option 1]
Let lg monaco editor has a readonly mode, the feature will be entirely based on current monaco project.
My concern here is the performance. We will show many SendActivity nodes in one page, monaco's performance is poor.

### [Option 2]
We consume the output result of a LGParser, with the output tokens, we render them in specifc colors.
The LG parser should be lightweight to make sure performance.

## Describe alternatives you've considered
Regardless what underlying parser we use, the output we need is a list of tokens:
```ts
const tokens: Token[] = tokenize("- Hi");
```
```json
[
    {  "label": "IF", "range": "Range(0,2)", "value": "IF" },
    {  "label": "template_name", "range": "Range(15, 20)", "value": "sayHi" }
]
```

### Questions on LG scenario
1. IF - ELSEIF - ELSE. What to show?
    ```
    > Using entity references
    # welcome
    - IF: ${userName}
        - ${welcome-user(userName)}
    - ELSE:
        - ${welcome-user('DongLei')}
    ```

**Comment by yeze322** [comment]
Went through the scenario with Zhixiang and Shuai, got a lot of inputs.
What's your guys opinion on the implementation plan? I prefer to create a new lib as the lightweight lg tokenizer. @zhixzhan @boydc2014

**Comment by yeze322** [comment]
Another question here is, considering the fact that we cannot show `IF - ELSEIF - ELSE` contents in visual nodes, will it be more efficient that we only use a **Regex** to discover template references like `${templateName(param1, param2)}`?

If so, we don't need to use the LGFIleParser.

**Comment by zhixzhan** [comment]
[Option 1] leverage Monaco Editor Lexer-Colorization system, but lost performance.
[Option 2] requires implement our own Lexer-Colorization system, and as Ze said, we can output Lexer from LGParser, add write an Colorization lib.

> Another question here is, considering the fact that we cannot show IF - ELSEIF - ELSE contents in visual nodes, will it be more efficient that we only use a Regex to discover template references like ${templateName(param1, param2)}?
> 
> If so, we don't need to use the LGFIleParser.

I prefer not restrict the inputs only from template-body, support both whole-content and partial-content can adapt scenarios more than only for Visual Editor.

**Comment by yeze322** [comment]
@zhixzhan Yes, I agree with you that it shouldn't be Visual Editor only.

**Comment by yeze322** [comment]
It's still a nice-to-have feature but not urgent, assign back to myself for better prioritization.

**Comment by yeze322** [comment]
deprecated
