### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by patrickianco** [microsoft/BotFramework-Composer#2029]
When starting an echo bot from the tutorial. I get the error and the node app crashes.

## Version

Release: Preview 2.0
Application SHA test
SDK runtime packages
4.7.0-preview-191208-1

## Browser

- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an Echo Bot
2. Click Start Bot

## Expected behavior

Bot will run just as what the tutorial stated

## Screenshots

![image](https://user-images.githubusercontent.com/27019238/74925400-1910de80-540f-11ea-84a8-4d04270b7c39.png)
![image](https://user-images.githubusercontent.com/27019238/74925424-24fca080-540f-11ea-9382-98de0f683b7b.png)

**Comment by VanyLaw** [comment]
hi @patrickianco  which branch do you use? Could you switch to newest master branch and try again? Because we update the dotnet version to 3.1 in master, maybe stable branch far behind.

**Comment by patrickianco** [comment]
Hi @VanyLaw I've already switched to the master branch and I still get the same error. :(

**Comment by patrickianco** [comment]
Here is the error shown in the console @VanyLaw 
![image](https://user-images.githubusercontent.com/27019238/75024675-cb5ea980-54d4-11ea-9e65-07758835fe4b.png)

**Comment by VanyLaw** [comment]
After clicking start button, it will run dotnet command to build and run your bot runtime. According to your `connection_refuse` error, it maybe because you time out when doing dotnet restore. Could you run `dotnet build` under your /Mybots/echobot-0 to see if the build succeed?

**Comment by patrickianco** [comment]
Do I need any other CLIs installed before running this project? @VanyLaw

**Comment by patrickianco** [comment]
@VanyLaw I fixed the first one by installing the dotnet SDK, but now I have this issue

![image](https://user-images.githubusercontent.com/27019238/75131693-3398cf80-570f-11ea-96cd-bacd309d618c.png)

**Comment by patrickianco** [comment]
Here is the error when I run `dotnet build`

`C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder.Dialogs from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder.Dialogs.Adaptive 4.7.1-preview -> Microsoft.Bot.Builder.Dialogs (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder.Dialogs (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder.Dialogs from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder.Dialogs.Adaptive 4.7.1-preview -> Microsoft.Bot.Builder.Dialogs (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder.Dialogs (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder.Dialogs from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder.Dialogs.Debugging 4.7.1-preview -> Microsoft.Bot.Builder.Dialogs (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder.Dialogs (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder.Dialogs from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder.Dialogs.Debugging 4.7.1-preview -> Microsoft.Bot.Builder.Dialogs (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder.Dialogs (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder.Dialogs.Debugging 4.7.1-preview -> Microsoft.Bot.Builder (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder.Dialogs.Debugging 4.7.1-preview -> Microsoft.Bot.Builder (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder.Dialogs from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder.Dialogs.Declarative 4.7.1-preview -> Microsoft.Bot.Builder.Dialogs (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder.Dialogs (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder.Dialogs from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder.Dialogs.Declarative 4.7.1-preview -> Microsoft.Bot.Builder.Dialogs (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder.Dialogs (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder.Dialogs.Declarative 4.7.1-preview -> Microsoft.Bot.Builder (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder.Dialogs.Declarative 4.7.1-preview -> Microsoft.Bot.Builder (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder.Dialogs.Adaptive 4.7.1-preview -> Microsoft.Bot.Builder.AI.QnA 4.7.1 -> Microsoft.Bot.Builder (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj : error NU1605:  BotProject -> Microsoft.Bot.Builder (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605: Detected package downgrade: Microsoft.Bot.Builder from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version.  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder.Dialogs.Adaptive 4.7.1-preview -> Microsoft.Bot.Builder.AI.QnA 4.7.1 -> Microsoft.Bot.Builder (>= 4.7.1)  [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj : error NU1605:  Tests -> BotProject -> Microsoft.Bot.Builder (>= 4.7.0-preview-191208-1) [C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.sln]
  Restore failed in 1.35 sec for C:\Users\Patrick\Documents\Composer\EchoBot-0\BotProject.csproj.
  Restore failed in 1.35 sec for C:\Users\Patrick\Documents\Composer\EchoBot-0\Tests\Tests.csproj.

Build FAILED.`

**Comment by VanyLaw** [comment]
Yes, we need to install dotnet 3.1 SDK first.  And because we updated the package reference in runtime, ( no longer used 4.7.0-preview-191208-1), some old bot may not work. The best way to fix this problem is create new bot in newest master branch, then click start to run.

**Comment by bigdatawork** [comment]
So I have a temporary solution that consistently fixes it.
Create the new project in Composer. Click Restart Bot (It will fail)
Open the .csproj file in Notepad++ and swap the following xml inside the PackageReference section
`<PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.4" /> <PackageReference Include="Microsoft.Bot.Builder" Version="4.7.1" /> <PackageReference Include="Microsoft.Bot.Builder.ApplicationInsights" Version="4.7.1" /> <PackageReference Include="Microsoft.Bot.Builder.Azure" Version="4.7.1" /> <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Adaptive" Version="4.7.1-preview" /> <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Debugging" Version="4.7.1-preview" /> <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Declarative" Version="4.7.1" /> <PackageReference Include="Microsoft.Bot.Builder.Integration.ApplicationInsights.Core" Version="4.7.0-preview-191208-1" /> <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.7.0-preview-191208-1" /> <PackageReference Include="Microsoft.Bot.Builder.Dialogs" Version="4.7.1" /> <PackageReference Include="Microsoft.Bot.Connector" Version="4.7.1" /> <PackageReference Include="MSTest.TestFramework" Version="1.4.0" /> <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.66">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>`
Save it and then click Restart Bot in Composer. Works every time
