### ISSUE TITLE
Composer cannot find ./Scripts/build_release.sh with default install on Ubuntu server

### ISSUE THREAD

**Issue by kishanhickman** [microsoft/BotFramework-Composer#2034]
## Describe the bug

After cloning the git repo and running the yarn commands per the installation instructions, everything appears to work accept trying to start the Bot for testing.  

When I click the "Start Bot" button on the top right corner (for the simple todo bot demo that comes with composer), I get the following error message:

"Sorry, something went wrong with connecting bot runtime
./Scripts/build_runtime.sh: 3: ./Scripts/build_runtime.sh: [[: not found" 

As I dont know the root folder of this relative path, I have tried to add the build_runtime.sh into the following folder with little success (even after providing chmod 777 permissions)

/var/www/**html**/BotProject/CSharp/Scripts  - where html is the root folder of the git repo.

I have manually been able to dotnet commands to build the bot in the terminal, but I cant work out where this build_runtime.sh script is supposed to live, i.e. whats the root path that that the composer client is look at.

## Version

Application SHA
test
SDK runtime packages
4.7.0-preview-191208-1

## Browser

- [X] Chrome

## OS

- [x] Ubuntu

## To Reproduce

1. Create a 'ToDo' sample bot
2. Click on 'Design Flow'
3. Click on 'Start Bot' located in the top right of that page
4. See error  in screenshot below

## Expected behavior

I would expect the bot to be built with some kind of confirmation and a test window to be ready for use.

## Screenshots

![image](https://user-images.githubusercontent.com/5497558/74946328-01c2f880-53f1-11ea-9669-844dcff0a457.png)

## Additional context

This maybe a permissions issue on my end but I think its more likely the the Script folder has been copied correctly and hence does not exist where it should, If I knew that I may be able to maunally correct this.

**Comment by VanyLaw** [comment]
The build_runtime.sh file we used to build runtime always settle in the sampleBot folder(like botframework-composer/mybots/echobot). you can track the file in sampleBot/Scripts folder. Another solution is create a new bot and migrate the ComposerDialogs folder to the new bot.

**Comment by kishanhickman** [comment]
Thanks I have found the file there and placed it there but it must be looking for somewhere.  I think I know where it could be looking, ill respond to this shorty.

**Comment by kishanhickman** [comment]
Hi Guys

This issue still seems to persist.  I have located the correct ./Scripts/build_runtime.sh but it still gives me the same error message.  If I run this manually from the project root folder e.g.

sudo bash ./Scripts/build_runtime.sh  msbuild starts as expected.  Ive changed all my persmissions so I sholudnt need to sudo exceute the script, but because it trys to access another tmp folder which is separate to this folder, I still need to run that.  I can fix this myself in the future.  Though im not sure if its still unable to find the script as the error message is very unhelpful and specific.  Is there a log file somewhere I can look at?  

If I need to re-install it and correct the permissions so its not using root, thats fine I can do that in the future.  I tested this manually and now im getting a different build issue around the libraries referenced in project file being obsolete:

![image](https://user-images.githubusercontent.com/5497558/75029567-2fb04780-549a-11ea-8516-7a1a75cb0171.png)

Is there a version of composer that is it a bit more stable or has a new one just been released which I can install again?

**Comment by kishanhickman** [comment]
I've just noticed the master branch references 4.7.2 ill give that a whirl and report back

**Comment by kishanhickman** [comment]
Hi guys

I have managed to get this working by starting again with the master branch and just ensuring that my linux server and fixing up permissions, so feel freet to close this

**Comment by kishanhickman** [comment]
there is a close button here - over and out
