### ISSUE TITLE
Begin a skill action node

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#2035]
UI / UX : 
https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=5013%3A2

Need the final approval from @mareekuh, then we are good to do.

**Comment by mareekuh** [comment]
We should use something as close to this experience as possible.
![PVA-AddSkill](https://user-images.githubusercontent.com/48503434/75200723-50d39b00-571b-11ea-9f8c-4b5f745e481a.gif)

here is a super quick mockup
https://www.figma.com/file/HLtKaKHctLldivPnzQ7BqQOI/Composer-MI-lotsotings?node-id=2681%3A0

![Screen Shot 2020-02-24 at 3 58 52 PM](https://user-images.githubusercontent.com/48503434/75201898-93e33d80-571e-11ea-80f2-c83b895727c9.png)
