### ISSUE TITLE
Multiple Choice HeroCard complex string values

### ISSUE THREAD

**Issue by fathorMB** [microsoft/BotFramework-Composer#2038]
## Is your feature request related to a problem? Please describe.

In multiple choice we have some Choice Options containing complex string values like "Do Something" or "Do This/That". The same issue is encountered when dealing with accented characters. We're trying to use those string in switch operators for comparisons but they're not easily usable. We tried referencing to values with quotes and double quotes but nothing changed.

## Describe the solution you'd like

Can be synonyms used in this scenario to make a lookup and consider Options as key/value?

## Describe alternatives you've considered

Maybe numeric values or non-complex strings can be used as keys.

## Additional context

![Capture](https://user-images.githubusercontent.com/13238241/75030945-81120400-54a5-11ea-9033-09219a823f5a.PNG)

**Also consider that could be useful to have language features in Choise Options names.**

@andreatosato

**Comment by fathorMB** [comment]
Another strange binding behavior we noticed with Auto List Style is the following:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/13238241/75045701-14f2c880-54c4-11ea-8916-34e33f48c7c1.png)

The value we expected in this case was "Due" but as you can see we got another one

**Comment by cwhitten** [comment]
@luhan2017 are you tracking this?

**Comment by luhan2017** [comment]
@fathorMB , sorry for the late response. I tried in the build and got the expect result, please let me know if this issue still exist. is there any special settings in your bot? 

![image](https://user-images.githubusercontent.com/32191031/77280210-aee5a500-6cfe-11ea-966d-1e422fca9903.png)

![image](https://user-images.githubusercontent.com/32191031/77280221-b5741c80-6cfe-11ea-912c-eb883f33f237.png)

![image](https://user-images.githubusercontent.com/32191031/77280377-1996e080-6cff-11ea-990b-00c7027db7b7.png)

**Comment by luhan2017** [comment]
@fathorMB , I am closing it for now, please reopen it if you still see this issue.
