### ISSUE TITLE
[Visual Designer] support modifying actions in the "EditActions" step

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#2044]
## Is your feature request related to a problem? Please describe.

Currently, the only way to modify actions in EditAction steps is through the form. This is the only place in composer that adding / removing / navigating to actions is done via the form instead of the visual designer.

## Describe the solution you'd like

The visual designer should support all action operations so that we can remove that from the form.

## Additional context

![image](https://user-images.githubusercontent.com/3619060/75058293-98de8d80-548f-11ea-8a3a-fa4876dd3335.png)

**Comment by yeze322** [comment]
Technically we can support it, either display it as an inline Form node or make it nested as IfConditon and SwitchCondition.

**Comment by yeze322** [comment]
pls assign back to me when design is ready

**Comment by a-b-r-o-w-n** [comment]
@sangwoohaan ping

**Comment by mareekuh** [comment]
@a-b-r-o-w-n  - I think I need more info to understand what it is your'e trying to do

**Comment by a-b-r-o-w-n** [comment]
@mareekuh there is an EditActions in the sdk which currently has no visual design for. We decided a while back that new actions should only ever be created from the visual editor, but the visual editor does not yet have support for this for EditActions.

**Comment by a-b-r-o-w-n** [comment]
Here is the schema for the action: https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.EditActions.schema

**Comment by mareekuh** [comment]
@sangwoohaan  - could you take a look at this?

**Comment by mareekuh** [comment]
@sangwoohaan

**Comment by vishwacsena** [comment]
We do not show the EditAction action today in composer but we can now given we have the ability in SDK now to know what the active dialog is. See PR - https://github.com/microsoft/botbuilder-dotnet/pull/4037#issuecomment-646800500

@sangwoohaan happy to chat when you are ready to look at this.

**Comment by sangwoohaan** [comment]
I'll start work on this soon. Let's chat.

**Comment by mewa1024** [comment]
Is a visual design still needed for EditActions? Also, are there other actions in the SDK that need nodes? I saw these in the SDK docs but couldn't find their counterparts in the node menus:
	•	CancelDialog
	•	UpdateActivity
	•	DeleteActivity
	•	GetActivityMembers
	•	GetConversationMembers
