### ISSUE TITLE
LU LSP bugs

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2046]
## Describe the bug

In playing with the auto-suggest, auto-complete capabilities for LU,  I ran into the following issues - 
1. Picking from the entity type (list) adds the entity type without a space and the parser complains of no space. We should not auto-complete content that will result in known parser errors. 
```
repro: 
1. Type '@' and wait for the entity type auto-suggest UI
2. Pick list entity type 
```
2. Adding sub-lists in list entity definition is missing space after ‘-‘ 
```
repro:
1. Type '@ list city = ' and hit enter. Notice '- ' auto-complete for normalized value.
2. Type 'seattle : ' and hit enter
3. Notice we no longer offer auto-complete '- ' with appropriate indentation for sub-lists
```
3. Hyphen stops working on new utterances on new intent added after entity definition
```
repro:
1. Add an intent section - e.g. 
# greeting 
- hello
2. Then add an entity definition - e.g. 
@ ml testEntity
3. Then add another intent section - e.g. '# testIntent' and hit enter
4. Notice the auto-complete for '- ' no longer works.
```
4. No hyphen auto-inserted after @ phraselist todoItem = <enter>
```
repro:
1. Type '@ phraselist test = ' and hit enter. We should auto-complete each line with '- ', this is just a list of values similar to intent definition. 
```
5. No auto-suggest for (interchangeable) for phrase list 
```
repro: 
1. Type ' @ phraselist test(' 
We should offer auto-complete for '@ phraselist test(interchangeable)'
```

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/issues/2046
