### ISSUE TITLE
[Accessibility][Functional - Bot responses-More Option]: Functionality of 'Make a Copy' menu item is not working.

### ISSUE THREAD

**Issue by ashish315** [microsoft/BotFramework-Composer#2048]
**User Experience:**
For keyboard users it is difficult to perform the task is if any control does not perform its functionality.

**Test Environment:**
Environment: Chromium Edge (Anaheim) + Narrator
Build Version: 2004 (OS Build 19564.1005)​​
Microsoft Edge Version: 82.0.425.0 (Official build) canary (64-bit)​
Test URL: http://localhost:3000/home

**Repro Steps:**
1. Open URL: http://localhost:3000/home
2. Select 'Bot Responses' link from left navigation.
3. Navigate within the table using tab key.
4. Press right arrow key & navigate up to 'More option' button & activate it.
5. Select 'Make a copy' menu item and observe the issue.

**Actual Result:**
Functionality of 'Make a Copy' menu item is not working. Nothing is performed on activating it.

**Expected Result:**
Functionality of 'Make a Copy' menu item should work. 

**Attachment:**
[Functional_Bot responses_More option_Make a Copy.zip](https://github.com/microsoft/BotFramework-Composer/files/4239039/Functional_Bot.responses_More.option_Make.a.Copy.zip)

**Comment by corinagum** [comment]
![Functional_Bot responses_More option_Make a Copy](https://user-images.githubusercontent.com/14900841/75413806-760f0780-58db-11ea-983d-0e31207d985f.png)


I think this qualifies as a regular bug (not just a11y)

**Comment by zhixzhan** [comment]
Hi @ashish315, did you scroll down to the bottom of this table list? The copied one would appear in the bottom.
Anyway, it's hard for user notice that, I will make some update when do copy, auto focus to created   item.

**Comment by ashish315** [comment]
As checked and verified on below environment, the issue is fixed now. So, we are closing the issue.
**Test Environment**
Browser: Microsoft Edge Dev {Version 83.0.467.0 (Official build) dev (64-bit)}
OS build: 2004 (19588.1000)
Screen Reader: Narrator
URL: [Bot Framework Composer](http://localhost:3000/dialogs/Main)
[**Prerequisite Here**](https://github.com/microsoft/BotFramework-Composer)
