### ISSUE TITLE
[Accessibility][Screen Reader -New Trigger]: On activating 'New Trigger' button, narrator narrates all the info available in the dialog box in a single flow.

### ISSUE THREAD

**Issue by ashish315** [microsoft/BotFramework-Composer#2059]
**User Experience** 
The screen reader dependent user will get confused if all the information is narrated in a single flow.

**Test Environment**
Browser: Microsoft Edge Canary Version: 82.0.425.0 (Official build)
OS build: 2004 (19564.1005)
Screen Reader: Narrator
URL: [Bot Framework Composer](http://localhost:3000/dialogs/Main)
[**Prerequisite Here**](https://github.com/microsoft/BotFramework-Composer)

**Repro Steps:** 
1. Open the above mentioned URL in EDGE.
2. Select 'Design Flow' from left navigation.
3. Now, navigate to 'New Trigger' button available in the filter dialog pane and activate it..
4. Observe the narrator narration.

**Actual:** 
The narrator narrates all the information available on the 'New Trigger' dialog in a single flow.

**Expected:**
The narrator should only narrate the tittle of the pane along with close button.

**Observation:**
Same issue observed with NVDA.

**MAS Reference:** [MAS4.2.1](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={a12f3779-bdf1-40c2-bbcc-0e314ea94858})

**Attachment:**
[MAS4.2.1_Narrator narrates all the info in a single flow.zip](https://github.com/microsoft/BotFramework-Composer/files/4241256/Usable_Narrator.narrates.all.the.info.in.a.single.flow.zip)

**Comment by beyackle** [comment]
Verified this is still happening. Working on it now.

**Comment by beyackle** [comment]
This looks like a problem with the interaction between Dialog and Dropdown. I can reproduce it in a CodePen just using off-the-shelf Fabric UI pieces: https://codepen.io/beyackle/pen/ExjOdBq

**Comment by corinagum** [comment]
@ashish315 could we have this bug filed with Fabric team? 
@beyackle I'm going to move this to 'In Review' list for visual clarity, feel free to change if you disagree

**Comment by beyackle** [comment]
Thanks for forwarding the question along. I put a question in the Fabric React channel in their team and haven’t gotten a response yet, but you can see the CodePen in there.

**Comment by ashish315** [comment]
@corinagum Will let you know once confirmed with Fabric Team.

**Comment by ashish315** [comment]
@corinagum will share the bug ID once the fabric team provide us. Meanwhile we are closing the issue.

**Comment by ashish315** [comment]
As checked with fabric team the issue is not repro at their end as well as 'New Trigger' dialog UI gets updated and currently narrator narration is acceptable.
