### ISSUE TITLE
[Accessibility][Usable - New Dialog] : Once the error appears it can't remove again even after the removal of the filed which have error.

### ISSUE THREAD

**Issue by ashish315** [microsoft/BotFramework-Composer#2060]
**User Experience** 
The screen reader dependent user will get confused as well as it effects low vision user as the error message didn't disappear even after correcting the field where the error appears.

**Test Environment**
Browser: Microsoft Edge Canary Version: 82.0.425.0 (Official build)
OS build: 2004 (19564.1005)
Screen Reader: Narrator
URL: [Bot Framework Composer](http://localhost:3000/dialogs/Main)
[**Prerequisite Here**](https://github.com/microsoft/BotFramework-Composer)

**Repro Steps:** 
1. Open the above mentioned URL in EDGE.
2. Select 'Design Flow' from left navigation.
3. Now, navigate to 'New Dialog' button available in the filter dialog pane and activate it..
4. Type the name of the dialog which is already created ex- Actions.
5. Observer the issue after correcting the name of the dialog.

**Actual:** 
The error message i.e. "Duplication of the dialog" is not gets disappeared even after correcting the name in the dialog.

**Expected:**
As the user delete the previously entered dialog name the error message should gets disappeared.

**MAG Guideline:** [MAG](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7BF98F4235-B6BD-47D3-8DA4-F28B9B6FBFA8%7D&file=Guideline%20101%20%E2%80%93%20Recommended%20Assistive%20Technology%20Tools%20for%20MAS%20Testing%20of%20Microsoft%20Digital%20Properties.docx&action=default&mobileredirect=true)

**Attachment:**
[Usable_error message can't gets corrected even after correcting the error field.zip](https://github.com/microsoft/BotFramework-Composer/files/4241282/Usable_error.message.can.t.gets.corrected.even.after.correcting.the.error.field.zip)

**Comment by beyackle** [comment]
This issue will be solved once the form-validation thing goes through; it's an artifact of the same problem (#2074 ).

**Comment by ashish315** [comment]
As checked and verified on below environment, the issue is fixed now. So, we are closing the issue.
**Test Environment**
Browser: Microsoft Edge Dev {Version 83.0.467.0 (Official build) dev (64-bit)}
OS build: 2004 (19588.1000)
Screen Reader: Narrator
URL: [Bot Framework Composer](http://localhost:3000/dialogs/Main)
[**Prerequisite Here**](https://github.com/microsoft/BotFramework-Composer)
