### ISSUE TITLE
Node creation menu: duplicated `Oauth Login` entires

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2064]
## Describe the bug

`Oauth Login` appears twice in a node creation menu:
![image](https://user-images.githubusercontent.com/8528761/75128670-36d88f00-5700-11ea-9d27-98f1701da5a1.png)

![image](https://user-images.githubusercontent.com/8528761/75128685-435ce780-5700-11ea-8c67-e56936136321.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by hibrenda** [comment]
@mareekuh just double confirm, should we remove the OAuth login from the inputs ("ask questions" ) section.

**Comment by mareekuh** [comment]
No we leave it in there. Remove the option from 'access other resources':

Here is a summary of the back and forth between Vish and myself 02.24'2020: 

"Originally I proposed to have 'OAuth' in the  'ask a question' menu for composer. You proposed for it to be in external resources - what was the reason again?

Vishwac Sena Kannan
    You can look at it two ways - external resource - the reason why you need OAuth is to access an external resource. or as input because you are asking the user to login. Fine if we move this back under input. From SDK POV, this actually is another input dialog 

Marieke Iwema
    It is currently in both - sounds ok then ? I got a q from brenda about it

Vishwac Sena Kannan
    Might be cleaner to just be in ask a question section "

**Comment by yeze322** [comment]
A one-line change in #2072 if we need a cleanup.

**Comment by yeze322** [comment]
Quote Ben's comments

> > Was this the decision we landed on? I think @benbrown would argue that this should exist in the external resources grouping. I sort of agree.
> 
> Yes, I agree with this assertion. Oauth is a special beast and doesn't fit neatly into "ask a question." It is in both places right now because I wanted to make sure people could find it if they are thinking "this is something I need to collect" OR if they are thinking "I need to connect into my external login flow"

https://github.com/microsoft/BotFramework-Composer/pull/2072#issuecomment-591052873
