### ISSUE TITLE
BotFramework-Composer web in Azure VM

### ISSUE THREAD

**Issue by mrahmadt** [microsoft/BotFramework-Composer#2066]
## Is your feature request related to a problem? Please describe.

I have a customer started using BotFramework-Composer on local machine and they want to deploy it in Azure VM, they managed to do that (Ubuntu server) but when they "Start Bot" they are getting below error because the bot emulator of course not installed on the VM

## Describe the solution you'd like

It will be nice if we have a template in Azure Market place ready with BotFramework-Composer and can be used remotely with bot emulator from local machine or even teams.

**Comment by cwhitten** [comment]
Hello @mrahmadt. What is the error? I don't see anything in the submitted issue.

We're actively looking at ways to provide Composer as a template web app available in places like the Azure Marketplace.
