### ISSUE TITLE
Couldn't find package "@bfcomposer/bf-lu@^1.1.8"

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#2084]
Latest release not work. 
Yarn Install emit this warning.

Couldn't find package "@bfcomposer/bf-lu@^1.1.8" required by "@bfc/indexers@0.0.0" on the "npm" registry.

![image](https://user-images.githubusercontent.com/24985956/75268704-23a8ea80-57f8-11ea-93e7-ac870ecdc686.png)

**Comment by andreatosato** [comment]
![image](https://user-images.githubusercontent.com/24985956/75268669-14c23800-57f8-11ea-8154-fba3fac7e9cd.png)

**Comment by lei9444** [comment]
Hi, @andreatosato 
The "@bfcomposer/bf-lu@^1.1.8" hasn't publish to npm registry now. You can find it in https://botbuilder.myget.org/feed/botbuilder-declarative/package/npm/@bfcomposer/bf-lu

If you want to yarn install the composer, the yarn.lock can't be deleted.
![image](https://user-images.githubusercontent.com/39758135/75304181-ade76200-587d-11ea-9dde-a0166d3ca814.png)

**Comment by andreatosato** [comment]
Hi @lei9444, yarn.lock isn't present in path.
I download project now and file is present. 
**Now build correctly**
