### ISSUE TITLE
Could not get valid Azure access token, BotFramework Composer

### ISSUE THREAD

**Issue by Ada-develop** [microsoft/BotFramework-Composer#2085]
## Could not get valid Azure access token

I using BotFramework Composer, and can't deploy it to the Azure. I created resource groups in Azure, and then by trying for deploy I faced problem, like :    **Could not get valid Azure access token** .
How should I solve this problem?
I have spent a lot of hours trying to solve this problem. I would appreciate any help I can get.
Any ideas how to fix it?

## Browser

- [x] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

1. Go to BotFramework Composer > Configuration> Publish
2. Click on 'Deploy bot to Azure'
3. Run generated commands in Command Line like on the screen
4. Error, Could not get valid Azure access token

## Screenshots

<p><img src="https://i.stack.imgur.com/09DwH.png"></p>
<p><img src="https://i.stack.imgur.com/nROM4.png"></p>

**Comment by zidaneymar** [comment]
Hi, @Ada-develop , please try to use "az login" command to login with your azure account.

**Comment by Ada-develop** [comment]
> 
> 
> Hi, @Ada-develop , please try to use "az login" command to login with your azure account.

Hi @zidaneymar ,  I tried , it doesn't help :(

**Comment by zidaneymar** [comment]
> > Hi, @Ada-develop , please try to use "az login" command to login with your azure account.
> 
> Hi @zidaneymar , I tried , it doesn't help :(

I can't repro on my machine, could you please provide some error messages? Does "az login" succeed?
