### ISSUE TITLE
[onboarding] product tour should be interactive

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/BotFramework-Composer#2086]
## Is your feature request related to a problem? Please describe.

In the onboarding flow, I would like to be able to click on parts of the UX between the steps. For instance, during the "Add a welcome message" step, I cannot click on the UI to add the welcome message as the tour is suggesting. Right now, any clicks off the modal result in a "confirm you're leaving the product tour" prompt.

## Describe the solution you'd like

I should be able to click around in the UI between the guided steps (aka, when the tour outline view is open, not the nav modals).

Such as in the screenshot:

![image](https://user-images.githubusercontent.com/2252976/75298500-85ad2400-57e7-11ea-870b-1c1f2b6ecc91.png)

## Describe alternatives you've considered

None

## Additional context

As part of the E2E onboarding story, this is an important flow that I'm hoping to we can get to be about 2-2.5 minutes average.

**Comment by mewa1024** [comment]
for reference, this is the screenshot of the modal that appears when you click on anything other than the teaching bubbles:
![image](https://user-images.githubusercontent.com/39317542/124376532-3fc66280-dc5c-11eb-817d-0912610f300b.png)
