### ISSUE TITLE
Onboarding UX should be on by default. 

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#2087]
We are not getting enough feedback (or any?) about the Onboarding experience.
Please turn the experience on by default and show it until it is fully run at least once or until the user turns it off in settings.

**Comment by hibrenda** [comment]
As discussed today, if user first install the composer, on-boarding will be enabled and after that it will be disabled. so does this make sense ?

**Comment by cwhitten** [comment]
This is on by default, for the users first bot creation. Closing for now.
