### ISSUE TITLE
Need Asset library to view and insert dialog building blocks & (remote) skills

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#2088]
Building a bot from scratch is fun, but building with building blocks is faster and will lead to higher quality experiences (customers can create and leverage reusable components).

Our first need for a library like this is skills - allowing people to browse select and insert (remote) skills such as Calendar, Email, Todo and Weather.

What does this involve
1. Add new item in the menu list (left pane): Asset library
2. On navigating to this, show a list view : Icon | Name  | Type | Last modified
Initially we have a flat list that includes different types of items allowing users to 'sort' by type or name. Eventually we'll want to have sub items and allow 'search'.
3. On select an item, show details such as an image, description etc.

Below is a wireframe image - @DesignPolice is working on a HighFi version.

<img width="551" alt="Screen Shot 2020-02-25 at 7 55 03 PM" src="https://user-images.githubusercontent.com/48503434/75310390-bcdffd00-5808-11ea-9ca5-9968fc2ebbd4.png">

**Comment by DesignPolice** [comment]
just going through everything assigned to me... Do we to look at this again in R10?

**Comment by mareekuh** [comment]
yes I think so (-: Chris included it in the most recent team project review (-:

**Comment by cwhitten** [comment]
This has shipped with Bot Projects & Packages
