### ISSUE TITLE
Yarn install Bug

### ISSUE THREAD

**Issue by perappr** [microsoft/BotFramework-Composer#2104]
## Describe the bug
Upon running yarn install throws unable to get local issuer certificate.

When setting up the Bot composer tool the yarn install command throws the error as per below

**yarn install v1.22.0**
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning Pattern ["@bfcomposer/bf-lu@https://botbuilder.myget.org/F/botbuilder-declarative/npm/@bfcomposer/bf-lu/-/@bfcomposer/bf-lu-1.1.8.tgz"] is trying to unpack in the same destination "C:\\Users\\perappr\\AppData\\Local\\Yarn\\Cache\\v6\\npm-@bfcomposer-bf-lu-1.1.8--integrity\\node_modules\\@bfcomposer\\bf-lu" as pattern ["@bfcomposer/bf-lu@^1.1.8","@bfcomposer/bf-lu@^1.1.8"]. This could result in non-deterministic behavior, skipping.
**error** An unexpected error occurred: "https://registry.yarnpkg.com/office-ui-fabric-react/-/office-ui-fabric-react-7.62.0.tgz: unable to get local issuer certificate".

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce
steps tried from this link https://github.com/microsoft/BotFramework-Composer
Below are the steps executed.
$ cd Composer // switch to Composer folder
$ yarn install // install dependencies  ---> 

Follow steps

**Comment by lei9444** [comment]
Hi, @perappr which os did you use? I have tried the master branch in win10, but it worked well

**Comment by a-b-r-o-w-n** [comment]
Hello @perappr this looks related to https://github.com/yarnpkg/yarn/issues/841. Can you read through that issue and see if the suggested config changes apply to you?
