### ISSUE TITLE
The link to the LU file format doc leads to a 404

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#2105]
## Describe the bug

The link to the LU file format doc leads to a 404.

This link is present inside the LU file template

Incorrect link is: https://github.com/microsoft/botframework-cli/blob/master/packages/lu/docs/lu-file-format.md

Correct link is: https://github.com/Microsoft/botbuilder-tools/blob/master/packages/Ludown/docs/lu-file-format.md

## Version

master

**Comment by hibrenda** [comment]
Sounds like the latest luis format doc is here : https://github.com/microsoft/botframework-cli/blob/master/packages/luis/docs/lu-file-format.md

**Comment by a-b-r-o-w-n** [comment]
I will be updating this to use the aka link (https://aka.ms/lu-file-format)
