### ISSUE TITLE
Upgrade Bot project

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#2106]
Hi folks,
I'm prototyping solution with Bot Framework composer.
I'm working on bot framework composer release (January). Now, I start with new release (Current Stable).

Can I update csproj automatically? 
I need to check each nuget packages version?
I need to check each .cs files?
I need to export json+lu files and recreate project?

Thanks a lot

**Comment by luhan2017** [comment]
Hi, you could not get your created bot updated automatically.
You may need to copy the .csproj and .cs files into your bot folder.

Could you try and get back to us if anything is not working well?

**Comment by andreatosato** [comment]
Why only .cs and .csproj?
Lg and JSON file is very important to.

I think that I must create new project and Copy only lg and JSON file. 
Is this correct way if I not implement new code?

**Comment by cwhitten** [comment]
hello @andreatosato. While Composer is in a PREVIEW state, you may at times need to hand modify your existing runtimes and .dialog, .lu, .lg files to match to underlying Bot Framework SDK changes that are not backwards compatible. Closing.
