### ISSUE TITLE
Specified argument was out of the range of valid values. Parameter does not match memory scopes

### ISSUE THREAD

**Issue by WizX20** [microsoft/BotFramework-Composer#2111]
## Describe the bug
Writing a parameter value throws an out of range exception:
`Specified argument was out of the range of valid values. (Parameter ‘‘test123’ does not match memory scopes:turn,settings,dialog,class,this,conversation,user’)`

I am using two steps in a new dialog:
* Set a property: set property *user.test* with value *test123*
* Send a response: write out a response with the format `Hi @{user.test}`

## Version

* Composer Version: Latest version as of today 27th of February 2020 (12:00 UTC)

## Browser

- [X] Chrome
- [X] Edge (Latest edge-chromium stable)
- [X] Bot Framework Emulator v 4.7.0

## OS

- [X] Windows

## To Reproduce

1. Start the composer
2. Create a new regex intent: servicenow/servicenow
3. Create a new trigger with the intent servicenow
4. From there, start a new dialog
5. Add two steps to the dialog
6. Step 1: Set a property: set property *user.test* with value *test123*
7. Step 2: Send a response: write out a response with the format `Hi @{user.test}`
8. Start the bot and open the emulator
9. type the servicenow intent
10. The response will be an exception: 
```
Specified argument was out of the range of valid values. (Parameter ‘‘test123’ does not match memory scopes:turn,settings,dialog,class,this,conversation,user’)
```

## Expected behavior

I'm expecting it to write out: *Hi test123*

## Screenshots

![image](https://user-images.githubusercontent.com/1008647/75443754-5c64d300-5962-11ea-80e0-14cb1ed76efd.png)
![image](https://user-images.githubusercontent.com/1008647/75443774-671f6800-5962-11ea-8fb7-acafd41231a8.png)
![image](https://user-images.githubusercontent.com/1008647/75443793-730b2a00-5962-11ea-9f2b-4699c442753c.png)

## Additional context

**JSON Response**
```
{
  "type": "message",
  "serviceUrl": "http://localhost:53979",
  "channelId": "emulator",
  "from": {
    "id": "e4b20110-5953-11ea-83a5-0f2d99b94e0c",
    "name": "Bot",
    "role": "bot"
  },
  "conversation": {
    "id": "190280d1-5958-11ea-83a5-0f2d99b94e0c|livechat"
  },
  "recipient": {
    "id": "a67e76b2-551e-4741-8388-d070e8cd4aeb",
    "role": "user"
  },
  "text": "Specified argument was out of the range of valid values. (Parameter ''test123' does not match memory scopes:turn,settings,dialog,class,this,conversation,user')",
  "inputHint": "acceptingInput",
  "replyToId": "1b975c80-5958-11ea-994a-bfafd57c45d1",
  "id": "1ba195b0-5958-11ea-994a-bfafd57c45d1",
  "localTimestamp": "2020-02-27T12:55:54+01:00",
  "timestamp": "2020-02-27T11:55:54.379Z",
  "locale": "en-US"
}
```

**Comment by hibrenda** [comment]
@WizX20 please use quote for your parameter as following. 
![image](https://user-images.githubusercontent.com/43408889/75449996-fbacb900-59a8-11ea-868f-bcb852c3e077.png)

**Comment by WizX20** [comment]
Ok that worked, I can't believe I did not try that...
