### ISSUE TITLE
[Accessibility][Screen reader - Property Pane_Ask a question (Bot Asks)]: Incorrect role is announced for ? as button in property pane.

### ISSUE THREAD

**Issue by ashish315** [microsoft/BotFramework-Composer#2115]
**User Experience** 
User who rely on screen reader will get confused if incorrect role is announced by the screen reader.

**Test Environment**
Browser: Microsoft Edge Canary Version: 82.0.425.0 (Official build)
OS build: 2004 (19564.1005)
Screen Reader: Narrator
URL: [Bot Framework Composer](http://localhost:3000/dialogs/Main)
[**Prerequisite Here**](https://github.com/microsoft/BotFramework-Composer)

**Repro Steps:** 
1. Open the above mentioned URL in EDGE and turn on narrator.
2. Navigate to already created dialog tree item and activate it. Such as- Greetings, Actions, EndDialog etc.
3. Click on "+" and select 'Ask a question'. Then select any of the available options except Oauth login.
4. Navigate to property pane appeared at right side of the screen.
5. Now, navigate to '?' just beside of 'Prompt.
6. Observe the issue.

**Actual:** 
On getting the focus, narrator announces role as button along with the descriptive information.

**Expected:**
As it has no functionality, the narrator shouldn't announce the control as button.

**Note:**
Same issue is observed for all the Property Pane which have "?".

**MAS Reference:** [MAS4.2.1](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730})

**Attachment:**
[MAS4.1.2_incorrect role is defined.zip](https://github.com/microsoft/BotFramework-Composer/files/4261888/MAS4.1.2_incorrect.role.is.defined.zip)
![MAS4 1 2_Incorrect role is defined for question mark button](https://user-images.githubusercontent.com/60913131/75450843-8a173f80-5995-11ea-81f4-8bad42b8c4c8.png)

**Comment by ashish315** [comment]
@cwhitten @beyackle As checked on below environment the issue is still repro.

**Test Environment**
Browser: Microsoft Edge Dev {Version 83.0.467.0 (Official build) dev (64-bit)}
Browser: Microsoft Edge Canary {Version 83.0.474.0 (Official build) canary (64-bit)}
OS build: 2004 (19588.1000)
Screen Reader: Narrator
URL: [Bot Framework Composer](http://localhost:3000/dialogs/Main)
[**Prerequisite Here**](https://github.com/microsoft/BotFramework-Composer)

**Comment by ashish315** [comment]
@cwhitten Stil narrator announces as '?' as button.

**Comment by cwhitten** [comment]
@ashish315 what branch are you running on the Composer project to test these fixes?

**Comment by ashish315** [comment]
@cwhitten We downloaded the latest 'Master build' from [https://github.com/microsoft/BotFramework-Composer/tree/master](https://github.com/microsoft/BotFramework-Composer/tree/master)

**Comment by beyackle** [comment]
@ashish315 Could you confirm that PR#2551 (this one: https://github.com/microsoft/BotFramework-Composer/pull/2551/files) is on there? That's the one that fixes this issue, and those "?" things in the field labels are no longer buttons in that one.

**Comment by ashish315** [comment]
As checked i guess this is not present their. Have a look below image

![image](https://user-images.githubusercontent.com/60913131/78807912-57c01f80-79e2-11ea-87b7-ecaaa3030239.png)

**Comment by beyackle** [comment]
I've rebuilt from master to double-check this myself and the screen reader reads the contents of the tooltip (followed by "group", because that's the kind of thing it's focused on). Here's a link to the video. https://microsoft-my.sharepoint.com/:v:/p/beyackle/EQg6A97M3xhKnlMH38nCmzMBV-lQoPhUVlycqfA9ockYQg?e=9pYPIh

**Comment by corinagum** [comment]
+1 to beyackle. I have cloned the latest master and can see his fix. Please re-verify.

**Comment by ashish315** [comment]
@corinagum As checked, the issue is fixed on the latest Master Bot. So, HCL is closing the issue.
Now, narrator narrates them as group with proper information.
