### ISSUE TITLE
Unsure how to feed data to an Adaptive card

### ISSUE THREAD

**Issue by WizX20** [microsoft/BotFramework-Composer#2129]
I created an adaptive card using the [online designer](https://adaptivecards.io/designer/). After that I added the json in the common.lg. I also added an Activity so I can call on the card from the Composer UI:

```
# TicketsSummeryCard(data, resultcount)
[Activity
    Attachments = @{json(ticketssummeryjson(data, resultcount))}
]

# ticketssummeryjson(data, resultcount)
- '''
{
    "type": "AdaptiveCard",
```

Writing out one of the arguments in the template works fine, like for example:
`"text": "**@{resultcount} INCIDENTS**"`

But I am unable to feed the template with any data like the [online designer](https://adaptivecards.io/designer/) does. Just simply outputting the data does not work:
`"$data": "@{data}",` or `"$data": "@{json(data)}",`

The data being a JSON response I got from the composer via a http-request.

Any suggestions would be appreciated.

**Comment by WizX20** [comment]
After some searching I managed to find:
- https://github.com/microsoft/AdaptiveCards/issues/2448
- https://docs.microsoft.com/en-us/adaptive-cards/templating/language

So I added the $data property, so far no success. It does not repeat the data for me.

**Comment by WizX20** [comment]
Related:
- [Feedback on 'Repeating items in an array' #211](https://github.com/MicrosoftDocs/AdaptiveCards/issues/211)
- [Two bugs in the repeat method. #251](https://github.com/MicrosoftDocs/AdaptiveCards/issues/251)

**Comment by Danieladu** [comment]
`{}`  is the render form of AdaptiveCard itself, and the card renderer SDK is required to make up the final form style.

But in Composer/BotBuilder.lg, there is no dependency on any AdaptiveCard SDK and format. We just treat the AdaptiveCard string as the normal template string and render it with `@{}` (which is migrated to ${} in the latest SDK version) to another output string. There is no AdaptiveCard template participation in the entire process.

So, I suggest you change templating `{}` to `@{}`(or maybe `${}`), it supposed to work. 

Additionally, We are now working with AdaptiveCards team to explore the integration of templating format.

Thank you for your attention, we will continue to follow this issue.😊

**Comment by WizX20** [comment]
> So, I suggest you change templating {} to @{}(or maybe ${}), it supposed to work.
Thank you for your reply. @{} does indeed work as I stated in the first message of this issue.
The problem is though, when you receive a big payload from an external service, and you would like to use that as the data-source for the card.

Some thoughts:
- Add an extra method to let the framwork know we are working with an adaptive card (adaptivecardjson)
```
   # TicketsSummeryCard(data, resultcount)
   [Activity
       Attachments = @{adaptivecardjson(ticketssummeryjson(data, resultcount))}
   ]
```
- Add reflection
```
   # TicketsSummeryCard(data, resultcount)
   [Activity
       Attachments = @{#MyAssembly.MyMethod(data, ticketssummeryjson())#}
   ]
```

**Comment by cwhitten** [comment]
Hello @WizX20. The functionality you seek needs to first be possible with the Adaptive Cards technology. Closing this. Please redirect your query to those two Adaptive Cards issues you opened.

**Comment by WizX20** [comment]
Hi @cwhitten, I'm not sure what you are trying to say but this is supported by the Adaptive Cards as I demonstrated here. But I'm very satisfied with @Danieladu his answer. So I guess closing this issue is fine.

**Comment by Danieladu** [comment]
> Hi @cwhitten, I'm not sure what you are trying to say but this is supported by the Adaptive Cards as I demonstrated here. But I'm very satisfied with @Danieladu his answer. So I guess closing this issue is fine.

Hi @WizX20 The latest Adaptive Card has been migrated to our Template format, the link is here:
https://docs.microsoft.com/en-us/adaptive-cards/templating/ 😊
