### ISSUE TITLE
Have UI separate dialog/conversation/user settings from property definition

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#2132]
## Is your feature request related to a problem? Please describe.

As a user of Composer, I would like to better understand the way that properties are defined in the UI.

## Describe the solution you'd like

Currently in the Composer UI, a user has to use a string such as dialog.{property} or user.{property}.  See screenshot below:
![image](https://user-images.githubusercontent.com/18688053/75556816-879ffe80-5a04-11ea-8791-da39d333968f.png)

I would like to see if we could separate this to allow a better understanding to the user on the options and why they might select each.  As a new User to building Bots, it is not clear as to your options.  Separating this into a dropdown list with a definition in the Help icon next to it would be a great way to teach new Users the different states in which you might want to store the property and why.

Here is a sample UI that I think makes more sense to a User:
![image](https://user-images.githubusercontent.com/18688053/75558340-4f4def80-5a07-11ea-991b-217d3d098d04.png)

## Describe alternatives you've considered

alternatively, we could put more documentation in the ? to explain all of this, but the concept seems easier when you break it apart for the user.

**Comment by sangwoohaan** [comment]
This is actually a great point, and we can extend the idea further in other input fields. I'll take a look into it.

**Comment by Dewain27** [comment]
Can I get an update on the status of this one?

**Comment by cwhitten** [comment]
@sangwoohaan is this now stale. Please close if so.
