### ISSUE TITLE
inline editing for lu errors and inline editing refresh for notification navigation

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2141]
Please reference following video :
https://recordit.co/7c4apRcaLx

- Editing in all up view with error
- (lsp issue) press enter after one utterance (expect the new line starts with '-', but '-' has been added to the next line and this new added starts with nothing)
- Notification page showed the errors 
- navigation back to "design flow" page
- (error) form does not refreshed (as no error showed) 
- refresh manually and inline form reloaded
- (error) inline editing in form to eliminate the error (but the lu file does not updated)
-so notification error does not change and back to all up view still can see the error

**Comment by alanlong9278** [comment]
This is because  the error line can not be written into the lu file when input a intent body with error line    in inline lu intent editor. I talked to @zhixzhan.
