### ISSUE TITLE
How can I send an http post request with properties, in the body or in headers?

### ISSUE THREAD

**Issue by MunozVictor** [microsoft/BotFramework-Composer#2149]
## Describe the bug

How can I send an http post request with properties, in the body or in headers?

I don't know what the correct syntax is to be able to send properties in the "Send Http request". or if it is possible or not, since when I put the properties in the body the json validator does not pass and in headers it returns an error. Is it possible to remove the json validator to allow the reference of properties?

## Browser

- Chrome

## OS

- Windows

## To Reproduce

1. Create a property
2. Set it with some value.
3. Try to reference that property from "Send http request" from the body or headers

## Screenshots

![Captura](https://user-images.githubusercontent.com/22679201/75686190-1a0dff80-5c9c-11ea-9433-c565917404c6.PNG)

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/tutorial/tutorial-get-weather.md#add-an-http-request @MunozVictor  is this help?

**Comment by MunozVictor** [comment]
This is an alternative solution because it only works through query string parameters, but it does not work with properties in the body or headers

**Comment by cwhitten** [comment]
hi @MunozVictor can you share the exact shape of the body you expect to use?

**Comment by MunozVictor** [comment]
It's in the picture @cwhitten  . The problem is not in my json , the problem is that you cannot put a reference to a property in the body. I rewrite my question, **How can I send an http post request with a body builded dynamically?**

It's indifferent if is this : 
`{"username": @{user.property} }`

or this : 

`@{user.property}`

Because my property can be an a json. The problem is the validator to json and syntax to reference to the properties inside the body and headers

**Comment by luhan2017** [comment]
@MunozVictor, could we know which composer version are your using? Previously we are using this format to form a HttpBody: 
`"username": {user.property} }`
After the recent update in master branch, now you can form a HttpBody like this:
`"username": ${user.property} }`

Please try that and let me know if it works.

**Comment by MunozVictor** [comment]
Thanks @luhan2017 , but doesn't works. I downloaded the master branch today (I was working with the default branch stable) and I tested all possibilities but none works.

Option 1 : 
![Captura1](https://user-images.githubusercontent.com/22679201/75875369-ddfdaa80-5e13-11ea-8e74-aeb1c6898441.PNG)

Option 2: 
![Captura2](https://user-images.githubusercontent.com/22679201/75875372-de964100-5e13-11ea-86c2-51b051d47c2e.PNG)

Option 3:
![Captura3](https://user-images.githubusercontent.com/22679201/75875368-dd651400-5e13-11ea-96a2-5184fea2088d.PNG)

**Comment by luhan2017** [comment]
@MunozVictor oh, I am really sorry, I missed the quotes in my reply.
could you try this: 
`{"username": "${user.property}" }`

**Comment by MunozVictor** [comment]
> @MunozVictor oh, I am really sorry, I missed the quotes in my reply.
> could you try this:
> `{"username": "${user.property}" }`

Works! Thanks @luhan2017

**Comment by MunozVictor** [comment]
> > @MunozVictor oh, I am really sorry, I missed the quotes in my reply.
> > could you try this:
> > `{"username": "${user.property}" }`
> 
> Works! Thanks @luhan2017

Hi @luhan2017 , How can I send a integer ?, because your solution it's only valid for send strings

**Comment by cwhitten** [comment]
@munozemilio this can be achieved using the `int` expression function. https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/common-expression-language/prebuilt-functions.md#int

Closing

**Comment by BarisC** [comment]
Hello, I am getting a bad request error after this request. Where do you think I'm making a mistake?

![error2](https://user-images.githubusercontent.com/16959031/101464477-bfeb4a80-394f-11eb-93be-46af9bfe61df.PNG)

**Comment by luhan2017** [comment]
@BarisC I think this is because it is a GET request, and you want to POST the body. Could you please try to update the GET to POST?

**Comment by BarisC** [comment]
Sorry I'm getting the same error. There is information that there is a
grant-type error. I want to show you the way I sent it and the error I got.
It is attached.

[image: 55.PNG]                           [image: error2.PNG]

Lu Han <notifications@github.com>, 9 Ara 2020 Çar, 04:17 tarihinde şunu
yazdı:

**Comment by BarisC** [comment]
Note: I used Post instead of Get. The problem continued.

Barış Çoruh <barislg54@gmail.com>, 9 Ara 2020 Çar, 12:45 tarihinde şunu
yazdı:

**Comment by aForero-GitHub** [comment]
Hi, if you still need a hand with this, here is what worked for me. 
![image](https://github.com/microsoft/BotFramework-Composer/assets/61327428/814f3198-c05e-49a8-abd6-f542853d1ed8)
