### ISSUE TITLE
Auto-generated Bot Response templates are not removed when entire dialog (trigger) is deleted

### ISSUE THREAD

**Issue by Zenulous** [microsoft/BotFramework-Composer#2150]
Creating new responses inside a bot action auto-generates bot response templates. These response templates are automatically deleted if you delete the response actions. This does not happen if you remove entire dialog (triggers) which contain such auto-generated templates.

## Version

Preview 2.0 (test)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot response in a trigger with some response text
2. Observe that the response template is created in `/language-generation/common`
3. Remove the dialog trigger in which you placed the response
4. Observe that the auto-generated template is still present in `/language-generation/common`

## Expected behavior

I expect that when I delete a dialog triggers, all auto-generated bot response templates are also removed.

## Screenshots

Happy case: if I delete a bot response directly, the auto generated template is also removed.

![1](https://user-images.githubusercontent.com/45333650/75694247-80991a80-5ca8-11ea-9213-889da7e52b4d.PNG)

Sad case: if I delete a dialog trigger containing a bot response, the auto generated template is not removed.

![2](https://user-images.githubusercontent.com/45333650/75694267-85f66500-5ca8-11ea-8d62-1a362f1fc24e.PNG)

## Additional context

My expectation may not be the intended behavior. The main problem with not deleting the the auto-generated templates that in a long-running project a bunch of unused auto-generated templates will be left in `/language-generation/common`.

**Comment by zhixzhan** [comment]
We are planning a final solution to this type resource problem on R10, discussed in #2312 #2699.

**Comment by zhixzhan** [comment]
Addressed.
