### ISSUE TITLE
lg inline editor swallow characters

### ISSUE THREAD

**Issue by alanlong9278** [microsoft/BotFramework-Composer#2152]
## Describe the bug

lg inline editor swallow characters if inputing comments.

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Screenshots

![lg](https://user-images.githubusercontent.com/5860999/75759139-0cc24500-5d70-11ea-9875-3c595f62c120.gif)

**Comment by zhixzhan** [comment]
The issue is lg parser do not include comments to this template body correctly, reported to LG team, I guess it would be fixed soon.

**Comment by cwhitten** [comment]
@zhixzhan will the LG team be fixing this? Can you reference an issue if so?

**Comment by zhixzhan** [comment]
@cwhitten Yes, they already fixed it at https://github.com/microsoft/botbuilder-js/pull/1849, I will integrate it later

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2373
