### ISSUE TITLE
Double scroll bars in dialog's properties pane

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2157]
## Describe the bug

![image](https://user-images.githubusercontent.com/32497439/75823681-08d5f900-5d57-11ea-8343-65df1d95bf86.png)

## To Reproduce

1. Select a dialog in the navigation pane.
2. See error.

## Expected behavior

Remove one scroll bar.

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/2163
