### ISSUE TITLE
How to create an **Intent recognized** trigger for a Regex-defined intent?

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2158]
## Describe the bug
I was trying to update the weather tutorials and came up with this question: how to create an **Intent recognized** trigger and configure it to an intent defined using Regular Expressions? It seems users can only create an **Intent recognized** trigger using LUIS as recognizer type in the current new trigger wizard design implemented in [PR1786](https://github.com/microsoft/BotFramework-Composer/pull/1786). 
@luhan2017 and @hibrenda found the similar issue during our meeting yesterday.

## To Reproduce

1. Create an intent using Regular Expressions as a recognizer type. 
2. Create an **Intent recognized** trigger 
3. Have no idea to configure the intent defined using RegEx to this trigger

## Expected behavior

**Intent recognized** trigger should be created to 

## Screenshots

![QQ截图20200303145930](https://user-images.githubusercontent.com/32497439/75828688-4b043800-5d61-11ea-817e-1fcfca013e51.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2151
