### ISSUE TITLE
Visual Edior svg edges have accumulated deviation under some zoom rates

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2167]
## Describe the bug

This issue occurred under several zoom rates: 90%, 150%, 250%
SVG elements are placed at correct position but not drawn accurately:

![image](https://user-images.githubusercontent.com/8528761/75900580-1505a780-5e78-11ea-8a7d-5f1692525216.png)
![image](https://user-images.githubusercontent.com/8528761/75901842-1932c480-5e7a-11ea-9aa1-8054292b0971.png)
(Also a 1px bias on the ‘+’ icon)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create 10+ actions
2. See the edges

**Comment by yeze322** [comment]
I'll fix it tommorrow

**Comment by yeze322** [comment]
Last week I had a discussion with Chris about this bug. It should be the absolute position of nodes that led to this bug. A potential fix is we using integer position instead of float position. Still assigned to me

**Comment by cwhitten** [comment]
@yeze322 let's address this in R9 as it's affecting the Electron application significantly.

**Comment by yeze322** [comment]
![svg-deviation](https://user-images.githubusercontent.com/8528761/79203352-7d7b7780-7e6d-11ea-8d11-cbc4f60aa711.gif)
I think I found the root cause of this bug

**Comment by yeze322** [comment]
in PR #2638
