### ISSUE TITLE
activity content and inline LG content should be displayed 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2174]
![image](https://user-images.githubusercontent.com/43408889/75964569-6195c500-5f02-11ea-93bb-4a77dc4355b7.png)

- Activity content need to be fully displayed ( visual nodes)
- Inline LG content need to be showed as expected (inline LG editor in form )

**Comment by hibrenda** [comment]
@mareekuh  see attached image. For activity content, what should be displayed in visual editor? 

 most of the nodes have been updated to the new design but only SendActivity  has no big change for "Activity" content and it has been rendered as above. Do you have any comments for this ? we should show all the content in visual or we have some trade off if you think this is too much.  include @yeze322 as well to be aware of this issue.
# bfdactivity-775572
[Activity
    Text = ${Add-Todo-Text()}
    ${Welcome-Actions()}
]

**Comment by alanlong9278** [comment]
@hibrenda For activity can not be displayed in form editor, I find the reason. As the pic show, activity.designer.id is not equal to activityId. in lg file, the content is bind to the activity id, but form editor lg content is filter by activity.designer.id. I think we should sync with @boydc2014  @luhan2017  Should we update the main.dialog or modify form editor filter condition.
![image](https://user-images.githubusercontent.com/5860999/75994229-996a3000-5f35-11ea-98b5-096f2492e4d4.png)
