### ISSUE TITLE
Visual Editor flickering issue in nested flow when deleting / inserting

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2175]
## Describe the bug

After inserting / deleting an action under a nested action type (IfCondition, SwitchCondition, Foreach), Visual Editor will be rendered twice (flickering).

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a IfCondition node
2. Create a nested IfCondition node under the true branch
3. Insert some nodes / delete some nodes under the nested true branch

**Comment by yeze322** [comment]
This issue is introduced by a latest feature PR #2005 .
In that PR, visual editor storaged all nodes' sizes into a global cache to avoid frequently re-computation of element sizes. It did help us have a stable layout.

However, with that cache mechanism, when user deleting / inserting a leaf node, parent nodes' sizes will still be loaded from cache instead of recalculating the size, it makes the layouter consumes an outdated size, then deletion/insertion of any nested node will cause flickering issue.

**Comment by yeze322** [comment]
The solution is making some improvements on layout cache management:
![image](https://user-images.githubusercontent.com/8528761/75971615-fd2c3300-5f0c-11ea-8157-c21ab06e6c8d.png)

**Comment by yeze322** [comment]
> The solution is making some improvements on layout cache management:
> ![image](https://user-images.githubusercontent.com/8528761/75971615-fd2c3300-5f0c-11ea-8157-c21ab06e6c8d.png)

Addressed in #2176.
Fix it just as I described

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2176
