### ISSUE TITLE
git pull origin stable (breaks working version)

### ISSUE THREAD

**Issue by ADefWebserver** [microsoft/BotFramework-Composer#2178]
Running git pull origin stable breaks working version

I run:
C:\Users\Michael\Source\Repos\BotFramework-Composer\Composer>yarn startall

and get this:

> C:\Users\Michael\Source\Repos\BotFramework-Composer\Composer>yarn startall
> yarn run v1.22.0
> $ node scripts/update.js && concurrently --kill-others-on-fail "npm:runtime" "npm:start"
> Checking for updates...
> 
> From https://github.com/microsoft/BotFramework-Composer
>    81232c5f..c0c3aa0a  benbrown/plugins        -> origin/benbrown/plugins
>  * [new branch]        chrande/electron2       -> origin/chrande/electron2
>  * [new branch]        cwhitten/left-align-flow -> origin/cwhitten/left-align-flow
>  * [new branch]        cwhitten/update-checksums -> origin/cwhitten/update-checksums
>  * [new branch]        donglei/plugins         -> origin/donglei/plugins
>  * [new branch]        julong/activity         -> origin/julong/activity
>  * [new branch]        julong/doubleScrollinForm -> origin/julong/doubleScrollinForm
>  * [new branch]        julong/headerTag        -> origin/julong/headerTag
>  * [new branch]        julong/nameForComponent -> origin/julong/nameForComponent
>  * [new branch]        luhan/updateHttpSample  -> origin/luhan/updateHttpSample
>    6ff0da3f..781f3877  master                  -> origin/master
>  * [new branch]        qika/FixBotProject      -> origin/qika/FixBotProject
>  * [new branch]        qika/deployupdate       -> origin/qika/deployupdate
>  * [new branch]        qika/deployupdate2      -> origin/qika/deployupdate2
>    1a6839d6..322e74c4  vishwac/master          -> origin/vishwac/master
>    1a750e58..62ed4719  vishwac/stable          -> origin/vishwac/stable
>  * [new branch]        wenyi                   -> origin/wenyi
>  * [new branch]        wenyluo/plugins         -> origin/wenyluo/plugins
> An update to Composer is available.
> 
> Run 'git pull origin stable' or fetch from origin/stable using another git-based tool.

I then run this:
**git pull origin stable**

and see this:

>  create mode 100644 Composer/packages/server/assets/projects/AskingQuestionsSample/ComposerDialogs/TextInput/TextInput.lg
>  create mode 100644 Composer/packages/server/assets/projects/AskingQuestionsSample/ComposerDialogs/settings/appsettings.json
>  create mode 100644 Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/CancelDialog/CancelDialog.lg
>  create mode 100644 Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/ForeachPageStep/ForeachPageStep.lg
>  create mode 100644 Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/ForeachStep/ForeachStep.lg
>  create mode 100644 Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/IfCondition/IfCondition.lg
>  create mode 100644 Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/Main/Main.lg
>  create mode 100644 Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/RepeatDialog/RepeatDialog.lg
>  create mode 100644 Composer/packages/server/assets/projects/ControllingConversationFlowSample/ComposerDialogs/SwitchCondition/SwitchCondition.lg
>  create mode 100644 Composer/packages/server/assets/projects/EchoBot/ComposerDialogs/Main/Main.lg
>  create mode 100644 Composer/packages/server/assets/projects/EmptyBot/ComposerDialogs/Main/Main.lg
>  create mode 100644 Composer/packages/server/assets/projects/InterruptionSample/ComposerDialogs/GetProfile/GetProfile.lg
>  create mode 100644 Composer/packages/server/assets/projects/InterruptionSample/ComposerDialogs/Main/Main.lg
>  create mode 100644 Composer/packages/server/assets/projects/QnAMakerLUISSample/ComposerDialogs/Main/Main.lg
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithCardsSample/ComposerDialogs/Main/Main.lg
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/IfElseCondition/IfElseCondition.lg
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/IfElseCondition/IfElseCondition.lu
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/LGComposition/LGComposition.lg
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/LGWithParam/LGWithParam.lg
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/Main/Main.lg
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/MultiLineText/MultiLineText.lg
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/MultiLineText/MultiLineText.lu
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/SimpleText/SimpleText.lg
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/StructuredLG/StructuredLG.lg
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/StructuredLG/StructuredLG.lu
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/SwitchCondition/SwitchCondition.lg
>  delete mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/TextWithLG/TextWithLG.dialog
>  create mode 100644 Composer/packages/server/assets/projects/RespondingWithTextSample/ComposerDialogs/TextWithMemory/TextWithMemory.lg
>  create mode 100644 Composer/packages/server/assets/projects/ToDoBotWithLuisSample/ComposerDialogs/Main/Main.lg
>  create mode 100644 Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/AddToDo/AddToDo.lg
>  create mode 100644 Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/ClearToDos/ClearToDos.lg
>  create mode 100644 Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/DeleteToDo/DeleteToDo.lg
>  create mode 100644 Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/Main/Main.lg
>  create mode 100644 Composer/packages/server/assets/projects/TodoSample/ComposerDialogs/ShowToDos/ShowToDos.lg
>  create mode 100644 Composer/packages/server/src/store/__mocks__/store.ts
>  delete mode 100644 Composer/packages/server/src/types/ludown.d.ts
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/.gitignore
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/README.md
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/__tests__/app.test.ts
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/__tests__/helpers/server.ts
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/__tests__/mocks/greeting.lu
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/__tests__/mocks/initialize-params.json
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/__tests__/unitTest/serverUtil.test.ts
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/demo/.eslintrc.js
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/demo/src/attach.ts
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/demo/src/server.ts
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/demo/tsconfig.json
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/jest.config.js
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/package.json
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/src/LUServer.ts
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/src/entityEnum.ts
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/src/index.ts
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/src/matchingPattern.ts
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/tsconfig.build.json
>  create mode 100644 Composer/packages/tools/language-servers/language-understanding/tsconfig.json
>  create mode 100644 docs/introduction.md
>  create mode 100644 docs/media/dialog/action-menu.gif
>  delete mode 100644 docs/media/dialog/action_menu.gif
>  delete mode 100644 docs/media/dialog/begin_dialog_action.png
>  delete mode 100644 docs/media/dialog/create_new_bot.png
>  create mode 100644 docs/media/dialog/main-and-child-dialog.png
>  delete mode 100644 docs/media/dialog/main_child_dialog.png
>  delete mode 100644 docs/media/dialog/main_dialog.png
>  delete mode 100644 docs/media/dialog/new_bot.png
>  delete mode 100644 docs/media/dialog/new_weather_dialog.png
>  delete mode 100644 docs/media/dialog/send_response.gif
>  delete mode 100644 docs/media/dialog/test_emulator.png
>  create mode 100644 docs/media/dialog/trigger-menu.png
>  delete mode 100644 docs/media/dialog/trigger_menu.gif
>  delete mode 100644 docs/media/dialog/weather_dialog.png
>  delete mode 100644 docs/media/dialog/wire_up_dialog.gif
>  create mode 100644 docs/media/events-triggers/BookFlight-configure.png
>  create mode 100644 docs/media/events-triggers/LUIS-intent.png
>  create mode 100644 docs/media/events-triggers/activities.png
>  create mode 100644 docs/media/events-triggers/begin-a-new-dialog.png
>  create mode 100644 docs/media/events-triggers/begin-dialog.png
>  create mode 100644 docs/media/events-triggers/cancel-trigger.png
>  rename docs/media/{events_triggers/conversationupdate.png => events-triggers/conversation-update.png} (100%)
>  create mode 100644 docs/media/events-triggers/custom-event-property.png
>  create mode 100644 docs/media/events-triggers/custom-event-response.gif
>  rename docs/media/{events_triggers/custom_event_response.png => events-triggers/custom-event-response.png} (100%)
>  create mode 100644 docs/media/events-triggers/dialog-events.png
>  rename docs/media/{events_triggers/emit_custom_event_property.gif => events-triggers/emit-custom-event-property.gif} (100%)
>  create mode 100644 docs/media/events-triggers/emit-custom-event-property.png
>  create mode 100644 docs/media/events-triggers/emit-custom-event.png
>  create mode 100644 docs/media/events-triggers/intent-trigger.png
>  create mode 100644 docs/media/events-triggers/luis-recognizer.png
>  create mode 100644 docs/media/events-triggers/regex-recognizer.png
>  create mode 100644 docs/media/events-triggers/regular-expression-intent.png
>  create mode 100644 docs/media/events-triggers/score.png
>  create mode 100644 docs/media/events-triggers/trigger-menu.gif
>  create mode 100644 docs/media/events-triggers/unknown-intent-response.gif
>  create mode 100644 docs/media/events-triggers/unknown-intent.png
>  create mode 100644 docs/media/events-triggers/welcome.gif
>  create mode 100644 docs/media/events-triggers/wire-up-dialog.gif
>  delete mode 100644 docs/media/events_triggers/BookFlight_configure.png
>  delete mode 100644 docs/media/events_triggers/LUIS_intent.png
>  delete mode 100644 docs/media/events_triggers/activities.png
>  delete mode 100644 docs/media/events_triggers/activity_trigger.png
>  delete mode 100644 docs/media/events_triggers/anatomy_trigger.png
>  delete mode 100644 docs/media/events_triggers/author_LUIS_intent.gif
>  delete mode 100644 docs/media/events_triggers/author_RegEx_intent.gif
>  delete mode 100644 docs/media/events_triggers/begin_dialog.png
>  delete mode 100644 docs/media/events_triggers/cancel_trigger.png
>  delete mode 100644 docs/media/events_triggers/configure_dialog.png
>  delete mode 100644 docs/media/events_triggers/configure_trigger.png
>  delete mode 100644 docs/media/events_triggers/create_custom_trigger.png
>  delete mode 100644 docs/media/events_triggers/custom_event.png
>  delete mode 100644 docs/media/events_triggers/custom_event_property.png
>  delete mode 100644 docs/media/events_triggers/custom_event_response.gif
>  delete mode 100644 docs/media/events_triggers/custom_trigger.png
>  delete mode 100644 docs/media/events_triggers/define_intents.png
>  delete mode 100644 docs/media/events_triggers/dialog_events.png
>  delete mode 100644 docs/media/events_triggers/dialog_trigger.png
>  delete mode 100644 docs/media/events_triggers/emit_custom_event.gif
>  delete mode 100644 docs/media/events_triggers/emit_custom_event.png
>  delete mode 100644 docs/media/events_triggers/emit_custom_event_property.png
>  delete mode 100644 docs/media/events_triggers/empty_custom_trigger.png
>  delete mode 100644 docs/media/events_triggers/empty_intent_trigger.png
>  delete mode 100644 docs/media/events_triggers/empty_unrecognized_intent.png
>  delete mode 100644 docs/media/events_triggers/event_name_greeting.png
>  delete mode 100644 docs/media/events_triggers/greeting_trigger.gif
>  delete mode 100644 docs/media/events_triggers/intent_trigger.png
>  delete mode 100644 docs/media/events_triggers/luis_recognizer.png
>  delete mode 100644 docs/media/events_triggers/message_activity_trigger.png
>  delete mode 100644 docs/media/events_triggers/new_trigger.png
>  delete mode 100644 docs/media/events_triggers/recognizer_type.png
>  delete mode 100644 docs/media/events_triggers/regex_recognizer.png
>  delete mode 100644 docs/media/events_triggers/regular_expression_intent.png
>  delete mode 100644 docs/media/events_triggers/score.png
>  delete mode 100644 docs/media/events_triggers/setup_LUIS_recognizer.gif
>  delete mode 100644 docs/media/events_triggers/setup_LUIS_recognizer.png
>  delete mode 100644 docs/media/events_triggers/setup_RegEx_recognizer.gif
>  delete mode 100644 docs/media/events_triggers/setup_RegEx_recognizer.png
>  delete mode 100644 docs/media/events_triggers/trigger_menu.png
>  delete mode 100644 docs/media/events_triggers/unknown_intent.png
>  delete mode 100644 docs/media/events_triggers/unknown_intent_response.gif
>  delete mode 100644 docs/media/events_triggers/welcome.gif
>  create mode 100644 docs/media/introduction/Bot-Responses.png
>  create mode 100644 docs/media/language-generation/Bot-Responses.png
>  create mode 100644 docs/media/language-generation/lg-inline-editor.png
>  create mode 100644 docs/media/language-understanding/LU-content.png
>  create mode 100644 docs/media/language-understanding/publish-lu.png
>  create mode 100644 docs/media/language-understanding/select-recognizer.png
>  create mode 100644 docs/media/language-understanding/user-input.png
>  create mode 100644 docs/media/language-understanding/wireup-intent.png
>  delete mode 100644 docs/media/language_generation/bot_responses.png
>  delete mode 100644 docs/media/language_generation/bot_says.png
>  delete mode 100644 docs/media/language_generation/inline_editor.png
>  delete mode 100644 docs/media/language_generation/multi_line_response.gif
>  delete mode 100644 docs/media/language_generation/one_line_response.gif
>  delete mode 100644 docs/media/language_generation/send_an_activity.gif
>  delete mode 100644 docs/media/language_generation/single_line_response_expression.png
>  delete mode 100644 docs/media/language_generation/single_line_response_text.png
>  delete mode 100644 docs/media/language_understanding/all_up_view.png
>  delete mode 100644 docs/media/language_understanding/intents.gif
>  delete mode 100644 docs/media/language_understanding/luis.png
>  delete mode 100644 docs/media/language_understanding/new_trigger.png
>  delete mode 100644 docs/media/language_understanding/select_dialog.png
>  delete mode 100644 docs/media/language_understanding/user_say.png
>  delete mode 100644 docs/media/language_understanding/wireup_intent.png
>  create mode 100644 docs/media/memory/delete-properties.png
>  create mode 100644 docs/media/memory/set-properties.png
>  create mode 100644 docs/media/tutorial-weatherbot/01/WelcomeTheUser.gif
>  delete mode 100644 docs/media/tutorial-weatherbot/01/add-send-activity.gif
>  delete mode 100644 docs/media/tutorial-weatherbot/01/create-welcome-trigger.png
>  delete mode 100644 docs/media/tutorial-weatherbot/01/greeting-in-emulator.png
>  delete mode 100644 docs/media/tutorial-weatherbot/01/new-flow.png
>  create mode 100644 docs/media/tutorial-weatherbot/01/new.png
>  delete mode 100644 docs/media/tutorial-weatherbot/01/recognizer-none.gif
>  create mode 100644 docs/media/tutorial-weatherbot/01/send-activity.gif
>  delete mode 100644 docs/media/tutorial-weatherbot/01/send-activity.png
>  delete mode 100644 docs/media/tutorial-weatherbot/02/begin-dialog-congifure.gif
>  create mode 100644 docs/media/tutorial-weatherbot/02/begin-dialog.png
>  delete mode 100644 docs/media/tutorial-weatherbot/02/begindialog-trigger.png
>  create mode 100644 docs/media/tutorial-weatherbot/02/connect-dialog.png
>  create mode 100644 docs/media/tutorial-weatherbot/02/create-getweather-dialog.png
>  delete mode 100644 docs/media/tutorial-weatherbot/02/create-getweather.png
>  create mode 100644 docs/media/tutorial-weatherbot/02/dialog-management.png
>  delete mode 100644 docs/media/tutorial-weatherbot/02/emulator-weather-draft.png
>  create mode 100644 docs/media/tutorial-weatherbot/02/emulator-weather.png
>  create mode 100644 docs/media/tutorial-weatherbot/02/getweather-dialog.gif
>  delete mode 100644 docs/media/tutorial-weatherbot/02/getweather-draft.png
>  create mode 100644 docs/media/tutorial-weatherbot/02/intent-pattern.png
>  create mode 100644 docs/media/tutorial-weatherbot/02/recognizer-type.png
>  delete mode 100644 docs/media/tutorial-weatherbot/02/regexp-recognizer.gif
>  delete mode 100644 docs/media/tutorial-weatherbot/02/select-begin.gif
>  create mode 100644 docs/media/tutorial-weatherbot/02/weather-intent-trigger.png
>  delete mode 100644 docs/media/tutorial-weatherbot/02/weather-intent.png
>  delete mode 100644 docs/media/tutorial-weatherbot/02/weather-trigger.png
>  delete mode 100644 docs/media/tutorial-weatherbot/03/empty-prompt.png
>  delete mode 100644 docs/media/tutorial-weatherbot/03/http-props.png
>  create mode 100644 docs/media/tutorial-weatherbot/03/http-result-property.png
>  create mode 100644 docs/media/tutorial-weatherbot/03/http-url.png
>  delete mode 100644 docs/media/tutorial-weatherbot/03/prompt-tabs.png
>  create mode 100644 docs/media/tutorial-weatherbot/03/set-a-property.png
>  delete mode 100644 docs/media/tutorial-weatherbot/03/tab-exceptions.png
>  create mode 100644 docs/media/tutorial-weatherbot/03/user-prompts.png
>  delete mode 100644 docs/media/tutorial-weatherbot/03/zipcode-flow.png
>  create mode 100644 docs/media/tutorial-weatherbot/04/begin-new-dialog-cancel.png
>  create mode 100644 docs/media/tutorial-weatherbot/04/cancel-intent.png
>  delete mode 100644 docs/media/tutorial-weatherbot/04/help-props.png
>  create mode 100644 docs/media/tutorial-weatherbot/04/intent-trigger-cancel.png
>  create mode 100644 docs/media/tutorial-weatherbot/04/plus-sign-icon.png
>  create mode 100644 docs/media/tutorial-weatherbot/04/select-begindialog-trigger.png
>  create mode 100644 docs/media/tutorial-weatherbot/04/select-cancel-dialog.png
>  create mode 100644 docs/media/tutorial-weatherbot/04/select-help-dialog.png
>  create mode 100644 docs/media/tutorial-weatherbot/04/select-textinput-action.png
>  create mode 100644 docs/media/tutorial-weatherbot/05/Select-the-BeginDialog-trigger.png
>  create mode 100644 docs/media/tutorial-weatherbot/05/bot-responses.png
>  delete mode 100644 docs/media/tutorial-weatherbot/05/nav2.png
>  create mode 100644 docs/media/tutorial-weatherbot/05/select-the-WelcomeTheUser-trigger.png
>  create mode 100644 docs/media/tutorial-weatherbot/06/getWeather-beginDialog2.png
>  rename docs/{tutorial-onboarding.md => onboarding.md} (100%)
>  rename docs/{tutorial-create-echobot.md => quickstart-create-bot.md} (96%)
>  delete mode 100644 docs/tutorial/bot-tutorial-add-dialog.md
>  delete mode 100644 docs/tutorial/bot-tutorial-add-help.md
>  delete mode 100644 docs/tutorial/bot-tutorial-cards.md
>  delete mode 100644 docs/tutorial/bot-tutorial-get-weather.md
>  delete mode 100644 docs/tutorial/bot-tutorial-introduction.md
>  delete mode 100644 docs/tutorial/bot-tutorial-lg.md
>  create mode 100644 docs/tutorial/tutorial-add-dialog.md
>  create mode 100644 docs/tutorial/tutorial-add-help.md
>  create mode 100644 docs/tutorial/tutorial-cards.md
>  create mode 100644 docs/tutorial/tutorial-create-bot.md
>  create mode 100644 docs/tutorial/tutorial-get-weather.md
>  create mode 100644 docs/tutorial/tutorial-introduction.md
>  create mode 100644 docs/tutorial/tutorial-lg.md
>  rename docs/tutorial/{bot-tutorial-luis.md => tutorial-luis.md} (86%)

I then run:

C:\Users\Michael\Source\Repos\BotFramework-Composer\Composer>yarn startall

> yarn run v1.22.0
> $ node scripts/update.js && yarn start
> Checking for updates...
> 
> You are using the most up to date version of Composer.
> $ cross-env NODE_ENV=production PORT=3000 yarn start:server
> $ yarn workspace @bfc/server start
> $ node build/server.js
> 
> Composer now running at:
> 
> http://localhost:3000

I open http://localhost:3000

If I create an empty bot with a simple greeting I get:

![image](https://user-images.githubusercontent.com/1857799/76000234-400feb80-5eb8-11ea-9d02-62d3b840212a.png)

> [Error]common.lg:ENOENT: no such file or directory, open 'common.lg' line 0:0 - line 0:0 [Error]common.lg:ENOENT: no such file or directory, open 'common.lg' . Refer to the syntax documentationhere.
> 
> [Error]common.lg:ENOENT: no such file or directory, open 'common.lg' line 0:0 - line 0:0 [Error]common.lg:ENOENT: no such file or directory, open 'common.lg' . Refer to the syntax documentationhere.

## Version

Application SHA test
SDK runtime packages 4.6.0-preview2

## Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Expected behavior

That git pull origin stable upgrade would work

**Comment by ADefWebserver** [comment]
I tried to start from scratch.
I deleted everything.

Microsoft Windows [Version 10.0.18363.657]
(c) 2019 Microsoft Corporation. All rights reserved.

I ran:

C:\Users\Michael\Source\Repos\microsoft\BotFramework-Composer\Composer>yarn install

I get:

> yarn install v1.22.0
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> warning Pattern ["@bfcomposer/bf-lu@https://botbuilder.myget.org/F/botbuilder-declarative/npm/@bfcomposer/bf-lu/-/@bfcomposer/bf-lu-1.1.8.tgz"] is trying to unpack in the same destination "C:\\Users\\Michael\\AppData\\Local\\Yarn\\Cache\\v6\\npm-@bfcomposer-bf-lu-1.1.8-a3c7767de038025157bdc8cf9f56b393f1428fd4-integrity\\node_modules\\@bfcomposer\\bf-lu" as pattern ["@bfcomposer/bf-lu@^1.1.8","@bfcomposer/bf-lu@^1.1.8"]. This could result in non-deterministic behavior, skipping.
> error https://botbuilder.myget.org/F/botbuilder-declarative/npm/@microsoft/bf-cli-command/-/@microsoft/bf-cli-command-1.0.0.tgz: Integrity check failed for "@microsoft/bf-cli-command" (computed integrity doesn't match our records, got "sha512-FuXsPQhZXPurHp3GSIg0zjYhtXyUSJ0lCgqpWxIEESNdf9vEKjLu2lRQwW3rERTFfp56qvvSvVcqLkhSCWU7xA== sha1-AeLCNNgmnv3ACTWvXBjHT6zcAiY=")
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I run:

C:\Users\Michael\Source\Repos\microsoft\BotFramework-Composer\Composer>yarn build

I get:

> yarn run v1.22.0
> $ node scripts/update.js && node scripts/begin.js && yarn build:prod
> internal/modules/cjs/loader.js:797
>     throw err;
>     ^
> 
> Error: Cannot find module 'react-dev-utils/chalk'
> Require stack:
> - C:\Users\Michael\Source\Repos\microsoft\BotFramework-Composer\Composer\scripts\update.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
>     at Module.require (internal/modules/cjs/loader.js:849:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (C:\Users\Michael\Source\Repos\microsoft\BotFramework-Composer\Composer\scripts\update.js:5:15)
>     at Module._compile (internal/modules/cjs/loader.js:956:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
>     at Module.load (internal/modules/cjs/loader.js:812:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Users\\Michael\\Source\\Repos\\microsoft\\BotFramework-Composer\\Composer\\scripts\\update.js'
>   ]
> }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by cwhitten** [comment]
Hi @ADefWebserver, thank you for the issue and I'm sorry you're running into problems.

I think you're running into a few issues as we're preparing a significant release to the `stable` branch. You have a few options available to you:

1. switch to the `master` branch and update your local branch using your preferred git tool.
2. `yarn cache clean`; `yarn tableflip`; `yarn startall`

This will clear your cache, blow away and reinstall your dependencies, and restart the application.

New builds off of the `stable` branch are tainted at the moment, due to a dependency that was improperly deployed two days ago and is now failing version checksums. This is fixed in the `master` branch. We're preparing a fix into the `stable` branch, but there is no exact ETA when this will happen.

As to your Composer bots being broken when updating your `stable` branch--this could happen from time to time as Composer and associated core libraries continue to work through their preview state to a stable release. This policy will change when we deem all this technology "Generally Available."

Thank you for trying Composer!

**Comment by ADefWebserver** [comment]
Thank you for your response! 
That fixed it!

**Comment by sammydeprez** [comment]
It might be a good idea to write this in the install guide that you need the master branch at the moment.
