### ISSUE TITLE
Adding a send a response action immediately triggers LG valiadtion error

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2179]
We should ensure that we do have system throw errors on valid user action. On latest master, I started a new bot, added a sendActivity action and see an error immediately. We should fix this so the user does not get the impression of immediately starting on a bad path

[capture1.mov.zip](https://github.com/microsoft/BotFramework-Composer/files/4294401/capture1.mov.zip)

See same error in all up view as well

**Comment by boydc2014** [comment]
Closed due out-dated, no longer have this issue in main branch
