### ISSUE TITLE
Consider removing inline validations in the form editor when user is typing

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2181]
It causes too much visual distraction and clutter to have the error message change on each keystroke. I know what I'm trying to type and I know content is invalid as I'm typing. Its entertaining to see the error message change but super distracting.

[Screen Recording 2020-03-05 at 10.25.32 AM.zip](https://github.com/microsoft/BotFramework-Composer/files/4294458/Screen.Recording.2020-03-05.at.10.25.32.AM.zip)

**Comment by a-b-r-o-w-n** [comment]
@vishwacsena are the inline errors (shown inside the editor with the wavy red underline)just as distracting? Do you suggest we leave those and only show the field error (at the bottom) when the user stops typing?

**Comment by vishwacsena** [comment]
@a-b-r-o-w-n in general the red squiggly lines are not as visually distracting. It usually is content shifting/ movement that causes distractions. I think we could show the field error (at the bottom) as a summary of all errors (there can be more than one) when the input control loses focus or when user is navigating/ deep linking back into the form from the validation notifications but will defer to @mareekuh for guidance on right visual treatment.

**Comment by a-b-r-o-w-n** [comment]
Input from design:

1. Do not show the error message at the bottom if the user is editing the document (still show red border)
2. Show the error message when the editor loses focus.
3. Show the error on first render, before the editor has focus (then hide when editor gets focus)
