### ISSUE TITLE
Managed LU R8 scoping for dialogs with regex recognizer 

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2183]
If the recognizer on a dialog is set to regex and not LUIS, 
- In add new trigger wizard
    - allow user to select intent name from a drop down list of configured intents
    - add a link to the dialog's form editor for the user to change recognizer setting
- no changes necessary to prompt inputs since we already only show the hoisted editor when recognizer is set to LUIS.

**Comment by hibrenda** [comment]
addressed in #2158 as well

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2151
