### ISSUE TITLE
Move `Value` property `User Input` tab

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2184]
At the moment `Value` property is in the `Other` tab. This needs to move to `User Input` tab. We will need to enable users to use this easily with managed LU. The UX now makes it hard to context switch when working with the mono editor for user utterances.

![Untitled 2](https://user-images.githubusercontent.com/20918136/76036878-3e671780-5efa-11ea-967b-6ef0043dc95f.png)

**Comment by hibrenda** [comment]
need to align with following 
![image](https://user-images.githubusercontent.com/43408889/76066992-99b40b00-5fc9-11ea-8fcb-02634b95972f.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2194
