### ISSUE TITLE
Set `allowInerruption` to `true` or provide guidance to do this when user has LU content in prompts

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2185]
Today, it is unclear that user needs to set allowinterruptions to true. We should either consider defaulting this to true since we now support managed LU or provide guidance through appropriate UX for users to know to do this.

**Comment by hibrenda** [comment]
As discussed, this will be addressed after R8 . composer will provide the auto default setting for #Inputs
