### ISSUE TITLE
Composer needs to serialize LU content for prompts using sections

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2186]
Composer should leverage [sections support][1] and write out content that belongs to a input action under a generic intent section for that trigger. 

It is sufficient to write a section into LU only if there are any inputs with LU content within that trigger.

Without this, a trigger with more than one input action will not work.

e.g. 
```
> !# @enableSections = true
> !# @enableMergeIntents = true

# <triggerIntentName>_inputs
## TextInput.response-140564
- my name is {@name}
- {@name = vishwac} is my name

@ prebuilt personName hasRoles name

## NumberInput.response-479205
- I'm {@userage}
- {@userage = 36}
- I'm {@userage = 36} years old

@ prebuilt age hasRoles userage
```

[1]:https://github.com/microsoft/botframework-cli/issues/137#Nested-intents

**Comment by hibrenda** [comment]
Discussed with @boydc2014 , we may not need this in R9.  so close this issue and reopen it if this will be required later.
