### ISSUE TITLE
Unable to successfully publish to LUIS (sometimes)

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2195]
After creating an initial LU application and then publishing updated model data associated with input lu, I see the following and can no longer successfully publish:

```bash
[WARN]: Invalid model info found. Skipping "> !# @enableSections = true"
POST /api/projects/opened/luFiles/publish 200 21600.032 ms - -
(node:75647) UnhandledPromiseRejectionWarning: Error: The application cannot be published. One or more models in the application version require training.
    at new RestError (/Users/chriswhitten/src/BotFramework-Composer/Composer/node_modules/@azure/ms-rest-js/dist/msRest.node.js:2400:28)
    at /Users/chriswhitten/src/BotFramework-Composer/Composer/node_modules/@azure/ms-rest-js/dist/msRest.node.js:3544:37
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:75647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
```

Steps to repro:

1. Create Bot w/ LUIS recognizer
2. Create Intent trigger and Intent definition
3. Inside Trigger flow, create new Prompt and provide labeled utterances for entity extraction
4. Repeat 1-2 times, eventually see error.
5. Once in this state, seems unable to recover

**Comment by boydc2014** [comment]
@cwhitten after some investigation, this is an issue when user have an utterance with no utterances in it. This is an interface change in LUIS service api that don't allow empty intent anymore (which is supported previously). 

Anyhow, @feich-ms will do a fix in bf-cli side, that issue a warning when empty intent found, and filter empty before publishing, then @lei9444 will pick that up. 

Thanks @lei9444 and @feich-ms.  It takes some time to reproduce :)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2201
