### ISSUE TITLE
Unable to copy actions across dialog files

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2199]
## Describe the bug
As reported by @cwhitten , if an action has lg inside it (SendActivity, TextInput), copying it to another dialog file will always fail.

The console will raise an error:
![image](https://user-images.githubusercontent.com/8528761/76184134-aa50c500-6205-11ea-8778-e071a60fa625.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
This bug is related to recent lg file structure changes. Previously, we only have one lg file 'common.lg', but for now, each dialog file has a default lg file, makes our copyLgTemplate api won't work if user wants to copy a template from 'Main.lg' to 'Todo.lg'.

**Comment by yeze322** [comment]
@zhixzhan Since we've already covered LG copy/delete, does LU resources need special treatment?
For example,  deep clone LU resources when copying/pasting actions with inline LU.

If so, what's the format of inline LU string and which actions have inline LU?
(I know TJ has had a PR to support deep deletion of LU resources in *Input types)

**Comment by zhixzhan** [comment]
The CopyLgTemplate is implemented copy in one file, when it comes to across file case, as Ze said we need to consider deep copy nested template. It's not reliable like one file case. 
Even though, we can still reach copy cross file by
```
1. getLgTemplate in file1
2. createLgTemplate in file2
```
And Lg delete will only delete it self, won't touch it's import, I believe it's more safe compare to deleting it's import.

For LU, we now have CRUD API on LU Intent/Section( the delete policy should be same to Lg),
Copy is not covered for now. if we plan implement it, I image it probably would look like current CopyLgTemplate, cause so far LU do not have cross file import. If copy lu is a valid requirement, I think we should have it.

You mentioned TJ's PR deep deletion, the 'deep' means is for dialog json, right? 
cause for both lg/lu we never covered deep copy/delete in file, but we indeed
have a few 'deep' scenarios for lg copy/delete/traverse in dialog json. @yeze322

**Comment by yeze322** [comment]
Thanks @zhixzhan! LG part is clear enough, I will track with you the implementation of LU part in another issue

**Comment by yeze322** [comment]
closed by #2198 .
