### ISSUE TITLE
Do not add _interruption intent if there are no inputs in that dialog that have `AllowInterruption` set

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2203]
At the moment, we cross train and add the _interruption intent to a dialog even if none of the inputs within that dialog have `AllowInterruption` set. If no inputs allow interruption, we do not need to cross-train interruption intent. 

[Optimization, P1]

**Comment by hibrenda** [comment]
@vishwacsena if this dialog is not leave node  and it will accept the interruption from children. So for this scenario, even if no inputs allow interruption in this dialog, we still need _interruption intent.
