### ISSUE TITLE
Delete trigger should also delete LU intents and LG templates

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2209]
The LG issues addressed #2150 .
This issue track the LU intents as the further _Interruption contents will be impacted  as well.

Both the trigger utterance and the inputs utterance should be removed.

**Comment by hibrenda** [comment]
#2312

**Comment by yeze322** [comment]
@yeze322 refs #2312

**Comment by yeze322** [comment]
@lei9444 what's our status of this issue? If it's not started yet, I can pick it

**Comment by yeze322** [comment]
#2844

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2844
