### ISSUE TITLE
"Restart Bot" Button and "Test in Emulator" are not reset when new bot is created or switched to another bot. 

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#2213]
## Describe the bug

In the latest master, when I create a new bot, I expected in the right up corner the button is ‘“Start Bot”.
when I switch to anther bot, I expect the Test in Emulator link will be updated to the other bot. 

But now, the "Test in Emulator" link and "Restart Button" is not refreshed. it still points to the previous opened bot. 

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2255
