### ISSUE TITLE
Authoring region not set in deploy.ps1 for lubuild command

### ISSUE THREAD

**Issue by WizX20** [microsoft/BotFramework-Composer#2218]
## Describe the bug

Source: https://github.com/microsoft/botframework-cli/blob/master/packages/luis/README.md#bf-luisbuild

[./Scripts/deploy.ps1 is missing the --region argument on line 136](https://github.com/microsoft/BotFramework-Composer/blob/ed080a2edd9ad2a37b375c7e229339c59ce21007/BotProject/Templates/CSharp/Scripts/deploy.ps1#L136) which results in lubuild always using the **westus** region even when another region was set.

## Version

- Release: Preview 2.0
- Application SHA: test
- SDK runtime packages: 4.7.0-preview-191208-1

## Browser

- [x] Chrome
- [ ] Safari
- [x] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to http://localhost:3000/setting/deployment
2. Click *deploy bot to Azure*
3. Copy the generated script and add ` -luisAuthoringRegion westeurope` to the end
4. The output of the command will tell you it is publishing the models for the region **westus**

## Expected behavior

I except the _-luisAuthoringRegion_ argument to be used, for example:
`lubuild --authoringKey $luisAuthoringKey --region $luisAuthoringRegion`

## Additional information

![image](https://user-images.githubusercontent.com/1008647/76313623-98d6ee00-62d5-11ea-929b-4f45762bd241.png)

**Comment by zidaneymar** [comment]
Thanks @WizX20 , this issue will be fixed soon.

**Comment by WizX20** [comment]
I actually think there might be more going on, I'm not sure if the lubuild command works at all in the script.

I personally got it working by installing the latest preview version of the botbuilder-tools. I updated the build script like this:
```
# Execute lubuild command
if (Get-Command bf luis:build -errorAction SilentlyContinue) {
	Write-Host "Start building luis models..."
	#lubuild --authoringKey $luisAuthoringKey --region $luisAuthoringRegion --config $luconfigPath
	bf luis:build --in $localBotPath --botName $name --authoringKey $luisAuthoringKey --region $luisAuthoringRegion
}
else {
	Write-Host "luis:build does not exist, use the following commands to install luis-build:"
	Write-Host "npm config set registry https://botbuilder.myget.org/F/botframework-cli/npm/"
	Write-Host "npm install -g @microsoft/botframework-cli@4.9.0-preview.112501"
	Write-Host "npm config set registry https://registry.npmjs.org/"
	Write-Host "> Please visit https://botbuilder.myget.org/feed/botframework-cli/package/npm/@microsoft/botframework-cli to check the latest version"
	Break
}
```

The only thing now is, the composer generates an empy .lu file for each new dialog; and the luis:build command will not like those.

**Comment by zidaneymar** [comment]
Script is using luis:build and add a filter for empty luis model.

**Comment by TylerOdenthal** [comment]
Did you guys push this update because I'm still getting this when I'm trying to publish from Composer.

I was using only language generation until yesterday, and the moment I added LUIS to my bot in composer I am unable to deploy. It seems my whole project can't redeploy even though I removed all of my LUIS intents in my bot.

Pretty rough bug, as I can't deploy to Teams right now until this is fixed.

```
C:\Users\Tyler\Desktop\ChatWorks\MicrosoftTeamsBots\BotFramework-Composer-stable\BotProject\HRBotPrototype>pwsh ./Scripts/deploy.ps1 -name HRBotPrototype -environment testing
The MSBuild project 'C:\Users\Tyler\Desktop\ChatWorks\MicrosoftTeamsBots\BotFramework-Composer-stable\BotProject\HRBotPrototype\BotProject.csproj' has already been initialized with a UserSecretsId.
0
bf luis:build does not exist, use the following command to install:
1. npm config set registry https://botbuilder.myget.org/F/botframework-cli/npm/
2. npm install -g @microsoft/botframework-cli
3. npm config set registry http://registry.npmjs.org
```
