### ISSUE TITLE
Drop adding `=` prefix if property value starts with `=`

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2222]
Consider dropping double `=` if property value already has `=` prefix.

![image](https://user-images.githubusercontent.com/20918136/76351345-873c1900-62ca-11ea-9a4a-2bf050dc298e.png)

**Comment by boydc2014** [comment]
Discussed with @brenda.  The proper fix to me is 

add a default ``, if there is no trailing '=', 
trim the = at beginning if there is a trailing '=',

 to be able to distinguish string and expression. 

So if a property is abc, then the ui will be
```
property = `abc`
```

if the property is =abc, then the ui will be 
```
property = abc
```,

looks good @vishwacsena @mareekuh . @cwhitten

**Comment by boydc2014** [comment]
the decision made is to use : instead of =.
