### ISSUE TITLE
Setup Electron Publishing DevOps Pipeline

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Composer#2225]
- [x] One-click Package & Publish for Composer Electron Application
  - [x] Package
    - [x] Windows
    - [x] Mac
    - [x] Linux
  - [x] Sign
    - [x] Windows
    - [x] Mac
  - [x] Publish to GitHub Releases

**Comment by BruceHaley** [comment]
This is completed. Set up as 3 builds and 1 release.
3 builds: https://fuselabs.visualstudio.com/Composer/_build?definitionScope=%5CComposer
	Composer-linux
	Composer-mac-signed
	Composer-windows-signed
1 release: https://fuselabs.visualstudio.com/Composer/_release?_a=releases&view=all&definitionId=1 
	Push-Composer-to-Github
