### ISSUE TITLE
Implement Auto-Update UX for Composer Electron

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Composer#2226]
Work with @DesignPolice to implement in-app UX for automatic application updates.

**Comment by DesignPolice** [comment]
Sounds like fun, what are the requirements for this... Any ideas on the number of buttons or copy... or I can do some searching on others who have gone before us. @tonyanziano

**Comment by DesignPolice** [comment]
@sangwoohaan @tonyanziano @srinaath @cwhitten 

Hey gentlemen, Marieke would like Sangwoo to take a pass at this before dropping it to me to verify the visuals we want to use - 

Sang here are a couple of the screen grabs from Emulator that has a similar auto update, though there are some key differences. 

![Edu16_STEM_05](https://user-images.githubusercontent.com/45223620/78293707-e235ea00-74dd-11ea-8439-c49ad7bb8058.png)
![Picture1](https://user-images.githubusercontent.com/45223620/78293710-e3ffad80-74dd-11ea-8a8b-345fb41e2c01.png)

**Comment by sangwoohaan** [comment]
My two cents :
In the first screen where you select an option, it would make more sense if there were just two options (download and update manually / install and restart), and have 'Automatically download and update' as a checkbox option for the future.

**Comment by tonyanziano** [comment]
Here are some of the auto update lifecycle events we can key off of (points in which we can show / update the UI):

- started checking for an update
- update is available
- update is **not** available
- download progress has updated
- update has been downloaded
- encountered an error

**Comment by DesignPolice** [comment]
Might be worth exploring using the (Bell) notification option in the header? then start the modals - We don't currently use any of the User Log in or settings up there, but could be a familiar way to surface needs if people aren't using the autoupdate option. 

![Screen Shot 2020-04-08 at 11 20 45 AM](https://user-images.githubusercontent.com/45223620/78819385-0173c200-798b-11ea-9e8d-67ce395a7730.png)

**Comment by sangwoohaan** [comment]
The first draft
https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=1212%3A11996

**Comment by tonyanziano** [comment]
@sangwoohaan do you happen to know the name of the icon in the app header? I can only find a similar icon with the direction of the arrow reversed on the Fabric / Fluent website:

![image](https://user-images.githubusercontent.com/3452012/79494803-745ae980-7fd8-11ea-8c86-e2d8e20dd6fe.png)

**Comment by DesignPolice** [comment]
Hey Tony
I don't think it makes a big difference on the direction, but here is the icon.

![Screen Shot 2020-04-16 at 11 57 28 AM](https://user-images.githubusercontent.com/45223620/79495452-740f1e00-7fd9-11ea-8fe3-f09793e3f601.png)

**Comment by DesignPolice** [comment]
https://www.iconcloud.design/home/FULL%20MDL2%20Assets/Fabric%20MDL2%20Assets/e81c

**Comment by tonyanziano** [comment]
Sounds good! Thanks

**Comment by tonyanziano** [comment]
Functionally, I believe this feature to be complete. Here's what I have:

![update-available](https://user-images.githubusercontent.com/3452012/79599290-17c00300-809a-11ea-8635-dcdd1ca2c364.PNG)
![update-failed](https://user-images.githubusercontent.com/3452012/79599291-18589980-809a-11ea-8173-7e0a957b9bbe.PNG)
![update-progress-1](https://user-images.githubusercontent.com/3452012/79599292-18f13000-809a-11ea-92d7-70c0bdc67c60.PNG)
![update-progress-2](https://user-images.githubusercontent.com/3452012/79599293-18f13000-809a-11ea-8142-2b6fb6702d1c.PNG)
![update-succeeded-1](https://user-images.githubusercontent.com/3452012/79599295-18f13000-809a-11ea-974d-1588ffd0603c.PNG)
![update-succeeded-2](https://user-images.githubusercontent.com/3452012/79599297-1989c680-809a-11ea-832b-b3932d89a9fc.PNG)
![update-unavailable](https://user-images.githubusercontent.com/3452012/79599300-1989c680-809a-11ea-8d6e-3dcb0fda45df.PNG)

I added an extra "Update unavailable" state for the future, when we add a button that will allow users to explicitly check for updates through maybe the app menu or some other piece of UI.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2721
