### ISSUE TITLE
LU all up view (activity column) is out of sync of publish status

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2230]
After luis publish, still get "Unknown state" for activity status
![image](https://user-images.githubusercontent.com/43408889/76389510-592c0700-63a6-11ea-8416-cb7990e95e28.png)

**Comment by zhixzhan** [comment]
This issue seems imported by cross train commit  https://github.com/microsoft/BotFramework-Composer/pull/2069 with lost Luis status in return value,  I did not figure out how to recalculate it. Can you guys @lei9444 @liweitian  help take a look?

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2256
