### ISSUE TITLE
How to work with dynamic multiple choice and arrays?

### ISSUE THREAD

**Issue by MunozVictor** [microsoft/BotFramework-Composer#2232]
## Browser

- [ ] Chrome

## OS

- [ ] Windows

## To Reproduce

In the documentation is missing the specific steps to :

1 - Initialize an array
2 - Configure a dynamic multiple choice with the arrray (or variable)

## Expected behavior

Build an a multiple choice with dynamic values

**Comment by hibrenda** [comment]
You can reference following doc : https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/how-to-ask-for-user-input.md#multiple-choice

**Comment by MunozVictor** [comment]
Hi @hibrenda , in this link its not specify how build an dynamic multiple choice, and this explications are very short. I'm trying to create an array and when I pass the property to prompt not works

**Comment by hibrenda** [comment]
@MunozVictor  Attached the screenshot (against the master branch) for how to use it. 

![image](https://user-images.githubusercontent.com/43408889/76599285-a68fac00-653f-11ea-84d0-f10252db8fcc.png)

**Comment by MunozVictor** [comment]
Thanks!

**Comment by philip-mc** [comment]
Hi,

I don't see the dynamic dropdown on bot composer v.1.3.0

I have a dynamic value called ${conversation.slot1} set to "tomorrow"which I am trying to use as an option in multiple choice. I cannot get the property to evaluate to "tomorrow".

**Comment by philip-mc** [comment]
Can I bump this guys I would like to know how to do this in the latest version of composer.

**Comment by hibrenda** [comment]
@philip-mc 
![image](https://user-images.githubusercontent.com/43408889/105691553-598aad80-5f38-11eb-8d3b-a654347dd74d.png) thanks to bring this up. could you try out ? we will update the doc later. @zxyanliu

**Comment by philip-mc** [comment]
Thanks for the message, still getting an issue tho:

![image](https://user-images.githubusercontent.com/73343537/105699368-24159e00-5eff-11eb-89db-26cf9316de9e.png)

![image](https://user-images.githubusercontent.com/73343537/105699411-37c10480-5eff-11eb-95b5-f0ec8feae29f.png)

**Comment by chandsalam1108** [comment]
> @philip-mc
> ![image](https://user-images.githubusercontent.com/43408889/105691553-598aad80-5f38-11eb-8d3b-a654347dd74d.png) thanks to bring this up. could you try out ? we will update the doc later. @zxyanliu

Hi, I'm unable to see a placeholder to provide expression. Please help.

![image](https://user-images.githubusercontent.com/48621464/115986691-277dfb80-a5ba-11eb-9f43-e4c466ecfecc.png)
