### ISSUE TITLE
schema mismatch for message received

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2235]
New trigger -> Message events -> Message received 
Run bot 
Complains following error
![image](https://user-images.githubusercontent.com/43408889/76417390-c2783e00-63d7-11ea-90a0-a44d6479b23f.png)

Need to update "$type": "Microsoft.OnMessageReceivedActivity" into "Microsoft.OnMessageActivity".

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2248
