### ISSUE TITLE
Regex validation

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#2237]
We should leverage the common regex module in expression library to validate the regex patterns used in regex recognizer or any places we support a regex pattern. 

There is no indicator now in schema now to indicate which field is expecting a regex yet, we probably can hardcode it first, and seek for a more schema-driven approach later.

**Comment by hibrenda** [comment]
#1985

**Comment by cwhitten** [comment]
removing from R9, cc @lei9444

**Comment by cwhitten** [comment]
@boydc2014 @lei9444 I've bumped this to R11 for now.

**Comment by boydc2014** [comment]
Close this as of out-of-date
