### ISSUE TITLE
Message received trigger - error

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2243]
## Describe the bug

**Before** creating the **Message received** trigger, everything works. 

![image](https://user-images.githubusercontent.com/32497439/76462231-8ffe1f00-639e-11ea-8c48-ab36076ab6cf.png)

![image](https://user-images.githubusercontent.com/32497439/76462348-c340ae00-639e-11ea-9ac2-158022dd567a.png)

**After** creating a **Message received** trigger, things are not working. 

![image](https://user-images.githubusercontent.com/32497439/76462401-dce1f580-639e-11ea-8e54-d090b53fe161.png)

![image](https://user-images.githubusercontent.com/32497439/76462511-0e5ac100-639f-11ea-9c5b-53ea6c287179.png)

Tried multiple times did not help.

**Comment by hibrenda** [comment]
#2235 to track the issues.
