### ISSUE TITLE
Shell - debouncedUpdateLg cannot handle paralleled lg update requests

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2247]
## Describe the bug
In a parralleled scenario, `deboundcedUpdateLg` api will lose changes.

Scenario:
Moves lg template A from 'D1.lg' to 'D2.lg', fires 2 paralleled api calls:
1. create template A' in 'D2.lg'
2. delete template A from 'D1.lg'

In this case, the first request will be cancelled.

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
Possible solutions:
1. use well-managed immutable states + observer
2. event stream

**Comment by yeze322** [comment]
Another hack I found in composer codebase (1y ago hacked by Andy)
![image](https://user-images.githubusercontent.com/8528761/76845473-e6290180-6879-11ea-8adf-79ad6b704a95.png)
It should also be addressed here

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2348
