### ISSUE TITLE
Optimize builtin variable names

### ISSUE THREAD

**Issue by Danieladu** [microsoft/BotFramework-Composer#2252]
For someone who is Familiar with BotFramework SDK, he/she may know what is `turn.Activity.membersAdded` means, and what is `turn.Activity.Recipient.id` means.

But for those who are new to this tool even new to BF, the learning cost is tooo high to learn what these variables mean. 

If Composer can provide some prompt suggestions or the select box, or just use the alias to simplify the use of built-in variables, that would be more friendly.

**Comment by hibrenda** [comment]
built-in variables could be auto suggested in LG editor. This issue is tracking auto suggest features in each property editor .

**Comment by hibrenda** [comment]
tracked under #1422
