### ISSUE TITLE
bot name edit issue

### ISSUE THREAD

**Issue by Danieladu** [microsoft/BotFramework-Composer#2253]
![Capture](https://user-images.githubusercontent.com/7289268/76520184-6841b080-649d-11ea-9b65-84bcc1fdfee8.PNG)

After creating a new bot, I found that bot name could be edited and looks like there are no format restrictions. But when I changed the name of the bot, the real bot name didn't seem to change.

**Comment by hibrenda** [comment]
you are changing the dialog "designer name" which only showed in property editor. So there is no restriction for the naming. Rename the dialog is not supported and tracked  under #1741 

So this issue will track the requirement for "designer name" update to the bot rename behavior.

**Comment by a-b-r-o-w-n** [comment]
@hibrenda 

> So this issue will track the requirement for "designer name" update to the bot rename behavior.

Is this a requirement? Or should the data flow go the other way? (Changing the name of the dialog updates that field?).

**Comment by hibrenda** [comment]
I agree. Renaming bot should support both dialog left nav and the property panel. This will track the name validation if we support renaming later.
