### ISSUE TITLE
Load project from X: hard drive

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#2257]
Hi all,
I need to load project from D drive!
From the GUI, I cannot select a different drive than C:

![image](https://user-images.githubusercontent.com/24985956/76534733-2e12e780-647a-11ea-971d-2ae6d434f611.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2274

**Comment by liweitian** [comment]
need to test it on linux system today.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2412
