### ISSUE TITLE
Handle empty lg file better

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#2261]
When creating a new empty bot, all of the lg fields give this error. Should we suppress this?

![image](https://user-images.githubusercontent.com/3619060/76570669-18e68a80-6473-11ea-94f7-6cf33c791221.png)

**Comment by Danieladu** [comment]
It is actually a warning diagnostic, the editor needs to distinguish between warning and error diagnostics.

**Comment by zhixzhan** [comment]
Sure, will update it

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2289
