### ISSUE TITLE
Publish not working for us

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2262]
## Describe the bug
Both @emgrol and I tried to publish a bot created using Composer to Azure and failed. 

After running the scripts in the **Create Azure Resources** step, 
We got the same error in the `create_log.txt` file:
```
{
  "error": {
    "code": "InvalidTemplateDeployment",
    "details": [
      {
        "code": "InsufficientQuota",
        "details": null,
        "message": "Insufficient quota. Cannot create/update/move resource 'EchoBot-Yan0311-Testing-luis-Authoring'.",
        "target": null
      }
    ],
    "message": "The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is 'f613963d-1aba-4aae-90a8-5e2f12b8cc38'. See inner errors for details.",
    "target": null
  },
  "properties": null
}
```

## To Reproduce

1. Create a bot using Composer.
2. Publish bot to Azure.
3. See the error. 

## Additional context
@luhan2017 We also tried creating a bot with LUIS intent definition to append LUIS key in scripts. The  **Create Azure Resources** worked, but the **Publish your bot** did not work.

**Comment by luhan2017** [comment]
@zxyanliu , what the error of the publishing, you only listed Create Azure Resources errors，this is not an issue after you append the LuisAuthoringKey, right?

**Comment by luhan2017** [comment]
Talked with Yan, this is because we updated to lubuild package source to botframework-cli. She successfully deployed after the updating the lubuild package.  @zxyanliu  will help to update the documentation.

**Comment by zxyanliu** [comment]
Thanks @luhan2017 for your help. I just verified the steps to publish a bot to Azure with success. 
![test-deploy](https://user-images.githubusercontent.com/32497439/76587308-abe9e980-64a0-11ea-9731-66decad8cd25.gif)
