### ISSUE TITLE
Schema-driven copy / paste behavior

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2268]
## Describe the solution you'd like
If a field is detected to be 'Micorosft.IActivityTemplate', it should be treated as a LgTemplate. Such as:
- `activity` in SendActivity
- `prompt` in TextInput
- `activity` in SkillDialog
- ...

Then we can call LG api to copy it.

If a field is detected to be an array of 'Microsoft.IDialog', it should be treated as an action list. Such as:
- `actions` in Foreach
- `actions`, `elseActions` in IfCondition
- `default`, `cases` in SwitchCondition
- ...

Then we can iterate the list to copy it.

If LU ...
- ?

Then we can call LU api to copy it.

**Comment by hibrenda** [comment]
This could solve the custom action node copy & paste if this custom action with LG/LU requirement.

**Comment by yeze322** [comment]
@hibrenda I move it to R10 to align with the timeline of #2312

**Comment by yeze322** [comment]
Close this issue because of it's overlapped with the 'v-dialog' feature which is under development by Zhixiang.
