### ISSUE TITLE
No editor are shown when I select "Regular Expression" or "LUIS" on "Recognizer Type"

### ISSUE THREAD

**Issue by Danielchui** [microsoft/BotFramework-Composer#2269]
No editor are shown when I select "Regular Expression" or "LUIS" on "Recognizer Type"

![Capture](https://user-images.githubusercontent.com/13895330/76693240-e7510780-669c-11ea-9c95-7e530dbbda6c.PNG)

## Browser
Edge or Chrome

## OS
Win 10

##Node Version
v12.13.0

##yarn version
1.22.0

##Composer version
4.7.0-preview-191208-1
Release: Preview 2.0

**Comment by zxyanliu** [comment]
Hey @Danielchui Thanks for reporting the issue. 

Here are the steps to create either a LUIS / RegEx trigger. 

1. Select the desired dialog in the **Navigation** pane of Composers' Design Flow page.
2. In the **Propertie**s panel of your selected dialog, choose **LUIS** or **Regular Expression** as recognizer type for your dialog.
3. Create an **Intent recognized** trigger. Select **New Trigger** in the **Navigation** pane then **Intent recognized** from the drop-down list.
  a. Enter a name in the **What is the name of this trigger** field. This is also the name of the intent.
  b. Enter a Regular Expression pattern or LUIS training data in the **Please input regex pattern** / **Trigger phrase** field.

The following image shows the definition of an **Intent recognized** trigger using **Regular Expression** recognizer.

![regex-intent-weather](https://user-images.githubusercontent.com/32497439/76809182-400cc700-67a7-11ea-9423-9bbbd34b16fb.png)

The following image shows the definition of an **Intent recognized** trigger using **LUIS** recognizer.

![luis-with-lu-content](https://user-images.githubusercontent.com/32497439/76809203-574bb480-67a7-11ea-9467-481fa9835665.png)


BTW, the updated Composer docs will be released in a day or two. 

Thanks.

**Comment by zxyanliu** [comment]
FYI. The [updated docs](https://docs.microsoft.com/en-us/composer/) got published this morning. 
Feel free to reopen the issue if you have any. 

Thanks.
