### ISSUE TITLE
Text input and Luis/regex text editor

### ISSUE THREAD

**Issue by Borg93** [microsoft/BotFramework-Composer#2270]
## Describe the bug

I tried to follow instructions to creata an weather bot by prompting the user for a location. However it seems like that text input dosen't save the user input as an variable...

Also, when I choice Luis or Regex --> There is no text editor as in the documentation

## Version

###Node Version
v12.13.0

###yarn version
1.22.0

###Composer version
4.7.0-preview-191208-1

- [X ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ X] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior

To get the weather for the user.location 
api:
http://openweathermap.org/data/2.5/weather?q={user.location},se&appid=<My-key>

Tried to debug it with an end dialog, but it seems that the user.location dosen't save any value..
both tried @{user.location} and {user.location}

## Screenshots
<img width="1178" alt="Screenshot 2020-03-15 at 15 52 51" src="https://user-images.githubusercontent.com/48671678/76703848-08cde580-66d5-11ea-8ae2-45505e1c8eed.png">

**Comment by zxyanliu** [comment]
Hey @Borg93 Thanks for reporting the issue. 

Here are the steps to create either a LUIS / RegEx trigger. 

1. Select the desired dialog in the **Navigation** pane of Composers' Design Flow page.
2. In the **Propertie**s panel of your selected dialog, choose **LUIS** or **Regular Expression** as recognizer type for your dialog.
3. Create an **Intent recognized** trigger. Select **New Trigger** in the **Navigation** pane then **Intent recognized** from the drop-down list.
  a. Enter a name in the **What is the name of this trigger** field. This is also the name of the intent.
  b. Enter a Regular Expression pattern or LUIS training data in the **Please input regex pattern** / **Trigger phrase** field.

The following image shows the definition of an **Intent recognized** trigger using **Regular Expression** recognizer.

![regex-intent-weather](https://user-images.githubusercontent.com/32497439/76809182-400cc700-67a7-11ea-9423-9bbbd34b16fb.png)

The following image shows the definition of an **Intent recognized** trigger using **LUIS** recognizer.

![luis-with-lu-content](https://user-images.githubusercontent.com/32497439/76809203-574bb480-67a7-11ea-9467-481fa9835665.png)


BTW, the updated Composer docs will be released in a day or two. 

Thanks.
Follow the steps to define an Intent recognized trigger with Regular Expression recognizer:

1. Select the desired dialog in the **Navigation** pane of Composers' Design Flow page.
2. In the **Propertie**s panel of your selected dialog, choose **Regular Expression** as recognizer type for your dialog.
3. Create an **Intent recognized** trigger. Select **New Trigger** in the **Navigation** pane then **Intent recognized** from the drop-down list.
  a. Enter a name in the **What is the name of this trigger** field. This is also the name of the intent.
  b. Enter a Regular Expression pattern in the **Please input regex pattern** field.

The following image shows the definition of an Intent recognized trigger named BookFlight. User input that matches the Regex pattern will fire this trigger.

![regular-expression-intent](https://user-images.githubusercontent.com/32497439/76808950-7433b800-67a6-11ea-9f9e-15a3d03dcdd8.png)

BTW, the updated Composer docs will be released in a day or two. 

Thanks.

**Comment by Borg93** [comment]
Hi! Thanks for answering! Why didn’t the User.location work?

Best, Gabriel

Skickat från min iPhone

17 mars 2020 kl. 00:59 skrev Yan Liu <notifications@github.com>:

﻿

Hey @Borg93<https://github.com/Borg93> Thanks for reporting the issue.

Here are the steps to create either a LUIS / RegEx trigger.

  1.  Select the desired dialog in the Navigation pane of Composers' Design Flow page.
  2.  In the Properties panel of your selected dialog, choose LUIS or Regular Expression as recognizer type for your dialog.
  3.  Create an Intent recognized trigger. Select New Trigger in the Navigation pane then Intent recognized from the drop-down list.
a. Enter a name in the What is the name of this trigger field. This is also the name of the intent.
b. Enter a Regular Expression pattern or LUIS training data in the Please input regex pattern / Trigger phrase field.

The following image shows the definition of an Intent recognized trigger using Regular Expression recognizer.

[regex-intent-weather]<https://user-images.githubusercontent.com/32497439/76809182-400cc700-67a7-11ea-9423-9bbbd34b16fb.png>

The following image shows the definition of an Intent recognized trigger using LUIS recognizer.

[luis-with-lu-content]<https://user-images.githubusercontent.com/32497439/76809203-574bb480-67a7-11ea-9467-481fa9835665.png>

BTW, the updated Composer docs will be released in a day or two.

Thanks.
Follow the steps to define an Intent recognized trigger with Regular Expression recognizer:

  1.  Select the desired dialog in the Navigation pane of Composers' Design Flow page.
  2.  In the Properties panel of your selected dialog, choose Regular Expression as recognizer type for your dialog.
  3.  Create an Intent recognized trigger. Select New Trigger in the Navigation pane then Intent recognized from the drop-down list.
a. Enter a name in the What is the name of this trigger field. This is also the name of the intent.
b. Enter a Regular Expression pattern in the Please input regex pattern field.

The following image shows the definition of an Intent recognized trigger named BookFlight. User input that matches the Regex pattern will fire this trigger.

[regular-expression-intent]<https://user-images.githubusercontent.com/32497439/76808950-7433b800-67a6-11ea-9f9e-15a3d03dcdd8.png>

BTW, the updated Composer docs will be released in a day or two.

Thanks.

**Comment by zxyanliu** [comment]
FYI. The updated [Composer docs](https://docs.microsoft.com/en-us/composer/) are live today. 
Also, I think you should use `${user.location}`. Please try again and let us know.

Thanks.

Yan

**Comment by zxyanliu** [comment]
Please refer to the [updated docs](https://docs.microsoft.com/en-us/composer/). 
Feel free to report an issue if you still have some. 

Thanks!
