### ISSUE TITLE
Need to support LU intent copy / delete / move

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2273]
- select one node or several nodes (inputs with user utterance)
- copy and paste in the dialog, no lu intent copied 
- move to the new dialog, no lu content copied

**Comment by cwhitten** [comment]
Before implementation we need to check-in with @vishwacsena's opinion on giving users the option to copy lu data as a reference/import or a total clone of the data into new dialog's lu file. I believe we should give this option when copying lu data across dialogs.

**Comment by yeze322** [comment]
As I discussed with Chris, the LU copy work will be postponed.
Instead, I will focus on a refactoring PR to move the copy hebavior from Visual Editor to Shell and make it a shared logic across Visual/Form/Shell. Then we can have the flexibility to let users choose whether they need to carry LU data during copy.

**Comment by yeze322** [comment]
We had a decision that

>  it is fine and intended to do a deep-copy of LU data for now
> 
> The recommendation is to deep copy from the flow operations, but allow direct file modifications from the all-up views 
> 
> So if a user wanted to change it to a reference across dialogs or triggers, they can do that

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2718
