### ISSUE TITLE
How to use composer on an existing bot-framework app?

### ISSUE THREAD

**Issue by niks3089** [microsoft/BotFramework-Composer#2276]
I have a Microsoft Teams App which I have created using Yeoman generator for which I would like to add intelligence and make it a conversational bot using the composer. How do I go about doing this? 

Also, I would like the conversation to be translated to an api call in the backend to my service which needs to be outputted to the user. Is this possible? 
I didn't find any reference for creating a Microsoft Teams Bot using the Composer. Any help?

**Comment by cwhitten** [comment]
Hello @niks3089. To achieve this, you would host your Yeoman generated bot as a Skill and make it available from a Composer-built bot. See https://microsoft.github.io/botframework-solutions/overview/skills/ & https://docs.microsoft.com/en-us/composer/ for more details. Closing.
