### ISSUE TITLE
How to create RegEx trigger

### ISSUE THREAD

**Issue by tcbjc** [microsoft/BotFramework-Composer#2280]
## Version
git clone https://github.com/microsoft/BotFramework-Composer.git
Node.js 12.16.1
Bot Framework Emulator: 4.8
Yarn: 12.22.1

## Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Select WeatherBot.Main in the Navigation pane
2. Find the Language Understanding section of the in the Properties panel
3. Select Regular Expression from the Recognizer Type drop-down list.
4. nothing

## Screenshots
![image](https://user-images.githubusercontent.com/26422656/76777873-da8afb80-67e3-11ea-8d73-7cb2ec1e6b81.png)

**Comment by zxyanliu** [comment]
Hey @tcbjc Thanks for reporting the issue. 

Here are the steps to create a RegEx trigger. 

Follow the steps to define an Intent recognized trigger with Regular Expression recognizer:

1. Select the desired dialog in the **Navigation** pane of Composers' Design Flow page.
2. In the **Propertie**s panel of your selected dialog, choose **Regular Expression** as recognizer type for your dialog.
3. Create an **Intent recognized** trigger. Select **New Trigger** in the **Navigation** pane then **Intent recognized** from the drop-down list.
  a. Enter a name in the **What is the name of this trigger** field. This is also the name of the intent.
  b. Enter a Regular Expression pattern in the **Please input regex pattern** field.

The following image shows the definition of an Intent recognized trigger named BookFlight. User input that matches the Regex pattern will fire this trigger.

![regular-expression-intent](https://user-images.githubusercontent.com/32497439/76808950-7433b800-67a6-11ea-9f9e-15a3d03dcdd8.png)

BTW, the updated Composer docs will be released in a day or two. 

Thanks.

**Comment by tcbjc** [comment]
> Hey @tcbjc Thanks for reporting the issue.
> 
> Here are the steps to create a RegEx trigger.
> 
> Follow the steps to define an Intent recognized trigger with Regular Expression recognizer:
> 
> 1. Select the desired dialog in the **Navigation** pane of Composers' Design Flow page.
> 2. In the **Propertie**s panel of your selected dialog, choose **Regular Expression** as recognizer type for your dialog.
> 3. Create an **Intent recognized** trigger. Select **New Trigger** in the **Navigation** pane then **Intent recognized** from the drop-down list.
>    a. Enter a name in the **What is the name of this trigger** field. This is also the name of the intent.
>    b. Enter a Regular Expression pattern in the **Please input regex pattern** field.
> 
> The following image shows the definition of an Intent recognized trigger using Regular Expression recognizer.
> 
> ![regex-intent-weather](https://user-images.githubusercontent.com/32497439/76809592-8dd5ff00-67a8-11ea-9f43-02936e02ecc8.png)
> 
> BTW, the updated Composer docs will be released in a day or two.
> 
> Thanks.


Thaks
