### ISSUE TITLE
Issue starting bot after updating to latest stable branch

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#2282]
## Describe the bug
After updating composer to the latest stable branch, and updating my existing bot to the latest code from the echo bot template and version 4.8.1 of the SDK, I get the following error when starting the bot in the composer:

`
Could not execute because the specified command or file was not found. Possible reasons for this include: * You misspelled a built-in dotnet command. * You intended to execute a .NET Core program, but dotnet-bin/Debug/netcoreapp2.1/BotProject.dll does not exist. * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
`

I ran `dotnet build` in the project folder directly without errors. 

Here is the console output:
![image](https://user-images.githubusercontent.com/27976702/76801791-9112c000-6793-11ea-8731-2757beb2ef5b.png)

## Version
Latest stable branch

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by hibrenda** [comment]
Hi @lauren-mills , composer made changes for bot project template , can you try to create a new bot to sync with the latest changes and copy your existing composerdialogs into it to see if this could be reproduced ? Please also make sure the .NET Core SDK is 3.1 and above.

**Comment by cwhitten** [comment]
@lauren-mills are you still having issues?
