### ISSUE TITLE
Support disabled nodes in visual editor 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2286]
https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19-?node-id=4586%3A0

- User can disable/enable nodes (single/multi selected) nodes
- copy/paste/move does not change nodes state
- condition nodes will be taken as "one block" to be disabled 

If nodes have been disabled, corresponding LU intent will not be published as well.

**Comment by yeze322** [comment]
TODOs:
- [ ] disabled effect: if an action's `disabled` field set to true, make this node and its child nodes gray (leveragin the css `filter`)
- [ ] In Shell toolbar, provide 2 buttons - `Disable` | `Enable`, make them clickable when selected nodes are detected to be able to toggle the state
    - If all selected nodes are `disabled`, show **| Disable (unclickable) | Enable (clickable) |**
    - If all selected nodes are `NOT disabled`, show **| Disable (clickable) | Enable (unclickable) |**
    - If selected nodes are half `disabled` and half `NOT disabled`, show **| Disable (clickable) | Enable (clickable) |**
    - If no selected node, show **| Disable (unclickable) | Enable (unclickable) |**

**Comment by yeze322** [comment]
LU publish part (@hibrenda who is responsible for the LU publish?)
- [ ] If nodes have been disabled, corresponding LU intent will not be published as well

**Comment by yeze322** [comment]
@sangwoohaan do you provide what's the icon names of 'Disable' and 'Enable' button?
![image](https://user-images.githubusercontent.com/8528761/81818988-4cbc5a00-9561-11ea-836c-de1ae7858498.png)

**Comment by hibrenda** [comment]
> LU publish part (@hibrenda who is responsible for the LU publish?)
> 
> * [ ]  If nodes have been disabled, corresponding LU intent will not be published as well

@lei9444 be aware of the lu content for luis publish.
