### ISSUE TITLE
composer crashed when delete dialog

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#2288]
## Version
master

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. create a new empty-bot
2. add a new dialog
3. delete the new dialog

## Screenshots
![image](https://user-images.githubusercontent.com/39758135/76835198-888cb900-6869-11ea-93c6-f3a1ec1dc1f7.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2290
