### ISSUE TITLE
When refresh the composer web, all lg files will be appended an empty line

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2291]
## Describe the bug

* When refresh the composer web, all lg files will be appended an empty line
* No SHA is shown
![image](https://user-images.githubusercontent.com/2876650/76844585-77977400-6878-11ea-86fa-d20febe63274.png)

## Version

ab052fc806178f7c88d5f5102b4f8dfc22bac926

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by zhixzhan** [comment]
It comes from a helper function help migrate single common.lg to multiple lg, this helper function would be disabled soon.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2164
