### ISSUE TITLE
Get weather report property

### ISSUE THREAD

**Issue by tcbjc** [microsoft/BotFramework-Composer#2292]
## Describe the bug
When attempting to follow this guide
https://github.com/microsoft/BotFramework-Composer/blob/master/docs/tutorial/tutorial-get-weather.md

I cannot get any of the properties to work as documented. If the branch I was able to get '{this.vaue}' to work only after changing it to '{this.vaue}'. I have attempted every variation I could to get {user.zipcode} to populate but I cannot get the value to pass.

I feel (trim(this.value)) in output format and ('@{this.value}') are invalid.

## Version
git clone https://github.com/microsoft/BotFramework-Composer.git
Node.js 12.16.1
Bot Framework Emulator: 4.8
Yarn: 12.22.1

## Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

4. See error 'Step 8: Enter trim(this.value) in the Output Format field. Step 10: In the Unrecognized Prompt field, enter: Step 11: In the Invalid Prompt field, enter:'

## Screenshots

![image](https://user-images.githubusercontent.com/26422656/76864026-64e26680-689b-11ea-8054-dabe5857c455.png)
![image](https://user-images.githubusercontent.com/26422656/76864065-7297ec00-689b-11ea-80a4-85ca484019a5.png)
![image](https://user-images.githubusercontent.com/26422656/76864086-7af02700-689b-11ea-8fe8-8ef449e8f12d.png)

**Comment by zxyanliu** [comment]
FYI. The updated content is live today. 
https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather

You are right, should be: `=trim(this.value)` in output format and `${this.value}`.

Please refer to the updated documentation and if there is any further question to ask. 

Thanks.
