### ISSUE TITLE
Docker image broken

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#2300]
## Describe the bug

running docker-compose up starts Composer but I can't click anywhere as I always get this error:

![image](https://user-images.githubusercontent.com/29750798/76985288-497d6700-6940-11ea-9ac2-79bd7fea97a9.png)

I freshly cloned the repo and haven't touched anything just ran docker-compose up. Error is the same for stable and master branch. Is anyone aware of that?

In the dev console I get these errors:

![image](https://user-images.githubusercontent.com/29750798/76985499-95c8a700-6940-11ea-8b5b-e570d2dde4dd.png)

## Browser
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
hey @stephanbisser, we'll look at this soon.

**Comment by stephanbisser** [comment]
thanks! If additional information is needed just ping me @cwhitten

**Comment by hibrenda** [comment]
@VanyLaw could you have a look ?

**Comment by VanyLaw** [comment]
Sure, I will have a look too.

**Comment by stephanbisser** [comment]
any updates on this @VanyLaw ?

**Comment by luhan2017** [comment]
@cwhitten , @boydc2014  Do we still support Docker scenario in Composer?

**Comment by VanyLaw** [comment]
stale
