### ISSUE TITLE
update app to read/write $kind instead of $type

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#2301]
In 4.8, the SDK has begun deprecating the `$type` in favor of `$kind`. Our app currently only knows about `$type`. We need to read & write `$kind` instead.

**Comment by yeze322** [comment]
Will a global replacement work? I guess so

**Comment by a-b-r-o-w-n** [comment]
@yeze322 maybe to start, but I want to be more intentional about it to make sure we don't miss anything. I assigned you in hopes that you can take ownership of the visual editor changes. I am trying to wrap up the form work and then I can work on this so if you get started, just open a draft PR and I can commit directly to that.

**Comment by yeze322** [comment]
@a-b-r-o-w-n okay

**Comment by yeze322** [comment]
#2333

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2333
