### ISSUE TITLE
What are the risk with a Bot created with Bot Composer?

### ISSUE THREAD

**Issue by MunozVictor** [microsoft/BotFramework-Composer#2314]
I watched a lot info in relation with Bot Composer its a preview, but i dont know if when I create a bot and I publish it, that bot have any dependecies with risk or what are the real risk?(if exists)  Thanks

**Comment by cwhitten** [comment]
Hi @munozemilio 

Composer and its underlying technology are still in preview. Delivering this technology as a component of a critical business solution for end-users is not recommended at this time. Closing.
