### ISSUE TITLE
Access to appsettings in Bot Framework Composer

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#2317]
Hi folks,
I need to read some settings from Bot Dialog.
In settings I expose some **base api url**.
Can I read this settings?

**Comment by cwhitten** [comment]
Composer has a Settings page where you can serialize and use this type of data. Closing as "how-to". See https://docs.microsoft.com/en-us/composer/ for more details.

**Comment by andreatosato** [comment]
Answer is on this [docs](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/adaptive-dialog/docs/memory-model-overview.md#settings-scope)

**Comment by SSanjeevi** [comment]
@andreatosato Link broken - please share latest link.
Not able to access appsettings values in any properties.
