### ISSUE TITLE
Luis on Container

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#2318]
Can I use Luis on Container?
Where Can I insert local endpoint?

**Comment by cwhitten** [comment]
Hi @andreatosato. LUIS does have a container, however to use it in a Composer bot, you would need to configure and register a custom runtime component to connect to this container. See the following: https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/adaptive-dialog/docs/recognizers-rules-steps-reference.md#recognizers

Closing as a "how-to", please continue on [stackoverflow](https://stackoverflow.com/) for how-to questions.

**Comment by andreatosato** [comment]
@cwhitten 

Luis on container started latest year:
https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-container-howto?tabs=v3#get-the-container-image-with-docker-pull

I need this recognizer.
Bot framework composer setting need **Endpoint URI**
```cs
var rootDialog = new AdaptiveDialog("rootDialog")
{
    Recognizer = new LuisAdaptiveRecognizer() 
    {
        ApplicationId = "<LUIS-APP-ID>",
        EndpointKey = "<ENDPOINT-KEY>",
        Endpoint = "<ENDPOINT-URI>"
    }
}
```
