### ISSUE TITLE
Skills: Selection & auto-fill/suggest appropriate field values from manifest

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2325]
When calling a SkillDialog, we should allow a user to select from a list of Skills currently available in the bot.

When the user has provided a Skill to call, pre-fill any deterministic fields available from the skill's manifest in the SkillDialog properties. In cases where these fields are deterministic (ex. `activity` we should suggest a list of elements to fill in these fields for the user.

Example: https://ericv3skillspizzabot.azurewebsites.net/wwwroot/pizza-bot-manifest.json

For the activity field in the SkillDialog given this manifest we should suggest `OrderPizza`, and when selected, fill-in the activity field for the user.

Note: auto-completion should probably come off of the LG LSP, like memory state is indexed into auto-suggestion.

**Comment by DesignPolice** [comment]
Here is the spec for the Skills node. 

There is a new dark blue added to the Theme... that should be perfect for this. I want them to look a little different with the icon in white on the right... also a blank version if that presents a scale problem - but I think it should be easy to pic an icon for each one... 

Here is the link to the Figma: 

https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=3276%3A95

![Screen Shot 2020-04-09 at 11 36 35 AM](https://user-images.githubusercontent.com/45223620/78930262-a9a38c80-7a58-11ea-9c88-13be85e83889.png)

**Comment by DesignPolice** [comment]
okay - well with a no-go on the custom icons... In honor of the excitement we all have to get a box from UPS or Fedex right now - that can contain any thing we can imagine. #skillbox 

Same colors as above. 

https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=5564%3A0


![Screen Shot 2020-04-15 at 3 40 53 PM](https://user-images.githubusercontent.com/45223620/79395980-b54af380-7f2f-11ea-9baf-703173e81c04.png)

@tdurnford @cwhitten

**Comment by cwhitten** [comment]
You want the Icon in the body of the node opposed to the header? currently icons in the nodes are in the header (next to Bot Skill)

**Comment by DesignPolice** [comment]
Oh my bad - I just looked a few that had the icon down there. Yes would rather have it up top... 

and Marieke said that the PVA Team is using this icon in a "similar fashion" soooo lets do this.

![Screen Shot 2020-04-16 at 8 23 58 AM](https://user-images.githubusercontent.com/45223620/79474811-bb86b180-7fbb-11ea-946e-f734e08ec699.png)
