### ISSUE TITLE
Skills: Manifest generation

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2327]
In order for a Composer-built bot to be available as a Skill, a new file needs to be created (.manifest). This file is strongly typed using JSON-Schema and is versioned, similar to .dialog files.

We should leverage the strong typing of the file format to auto-generate form fields like we do the form editor in the Design page, as well as re-use UI controls across the forms and this manifest page.

**Comment by tdurnford** [comment]
Waiting on changes to Skill Manifest Schema
https://github.com/microsoft/botframework-sdk/issues/5794

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2815
