### ISSUE TITLE
Skills: Test story for //BUILD

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2328]
Calling a Skill from a locally built Composer bot can be difficult to test. It requires registration on the Azure portal, ngrok, and a lot of mechanical steps to make communication possible between the local bot and the remote skill. 

This issue represents the story for BUILD that we ask customers to reference when they want to test calling a Skill from a Composer bot.

**Comment by zxyanliu** [comment]
I happen to have an active [PR](https://github.com/MicrosoftDocs/composer-docs-pr/pull/66) for this.
