### ISSUE TITLE
LG LSP: Add auto-complete/auto-suggest for Activity and Cards

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2330]
Add auto-complete/auto-suggest into the LG LSP to provide support when authoring Activities and Cards. See RespondingWithCards sample for list of Cards to suggest auto-complete.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2363

**Comment by cosmicshuai** [comment]
I need to add support of suggestion of cards in inline mode. So I reopen this issue.
