### ISSUE TITLE
lu file can't save when changing in dialog page.

### ISSUE THREAD

**Issue by VanyLaw** [microsoft/BotFramework-Composer#2336]
## Describe the bug

After create a interruptionSample, changed the getProfile dialog into luis recognizer, show error.
![image](https://user-images.githubusercontent.com/21174180/77290562-65ee1a80-6d17-11ea-97c8-697c12d995d8.png)

I change the lu as below, but it can't save in that panel. it can only save in lu page.

```
- my name is {personName:userName}
- {personName:userName}
- {age:userAge}
- I'm {age:userAge} years old
 
@ prebuilt  personName userName
@ prebuilt  age userAge
```

![image](https://user-images.githubusercontent.com/21174180/77290917-2e33a280-6d18-11ea-96fe-bff8b8382c02.png)

## Version

master branch

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by zhixzhan** [comment]
it's kind of known issue inline lu editor can't save with error. talked on #2141 #2267, and will be fixed in #2272
