### ISSUE TITLE
Logging Conversations to cosmos

### ISSUE THREAD

**Issue by prasadreddybv** [microsoft/BotFramework-Composer#2339]
Can we log all the conversations of the bots developed in the Composer?
-- I am trying to store all the conversations which will be building  by the bots developed in the composer. Please assist me on this if anyone has worked on it or have any idea on how to implement this through Composer. Appreciate the help.

**Comment by hibrenda** [comment]
You can enable the cosmosDB configuration in appsettings.json in your bot directory as following .
```
"cosmosDBEndpoint": "<your-cosmos-db-URI>"
 "authKey": "<your-primary-key>"
```
make sure "collectionId": "botstate-collection" and "databaseId": "botstate-db" in sync with your db creation. 
![image](https://user-images.githubusercontent.com/43408889/77662457-d797c400-6fb6-11ea-8cdd-c04e57c05ff7.png)

**Comment by hibrenda** [comment]
if this does not solve the issues, feel free to reopen

**Comment by mohsenualam** [comment]
> You can enable the cosmosDB configuration in appsettings.json in your bot directory as following .
> 
> ```
> "cosmosDBEndpoint": "<your-cosmos-db-URI>"
>  "authKey": "<your-primary-key>"
> ```
> 
> make sure "collectionId": "botstate-collection" and "databaseId": "botstate-db" in sync with your db creation.
> ![image](https://user-images.githubusercontent.com/43408889/77662457-d797c400-6fb6-11ea-8cdd-c04e57c05ff7.png)
> 
> For cosmosDB configuration, please reference :
> https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp#using-cosmos-db

This documentation is for configuring CosmosDB with manually developed bot. How can we store conversation to CosmosDB when the bot is built within Composer?

When I selected CosmosDB in the publish profile, it's saving only the last text from a conversation to CosmosDB's bot-state database, how can we save all conversations?
