### ISSUE TITLE
BotProject need to load the .dialog under the root folder rather than Main.dialog 

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#2351]
## Version

latest master, since we merge Zhixiang's multi-language support PR which updates the bot folder hierarchy, we need to update the botproject to load *.dialog under root folder instead of Main.dialog.

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Composer
2. Clone any bot template
3. Click Start Bot
4. You will get 500 error in the emulator because the bot is not successful loaded

**Comment by boydc2014** [comment]
dup to #2350
