### ISSUE TITLE
multi-locale/file serialization regressions

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2357]
1. serialization has a couple minor issues:
   - when a template is selected for creation, the main/entry dialog is the name of the template, when it should be the name the user gave for the bot.
   - sub-dialogs in the /dialogs folder are not lower-cased.
2. Configuring LUIS as recognizer appears to break. (500's from emulator)

**Comment by boydc2014** [comment]
in 3#, there is no "generated" folder, looks like lubuild isn't up to date with multi-locale change, co-assign Leilei for this.

**Comment by zhixzhan** [comment]
Hi @cwhitten for 
> sub-dialogs in the /dialogs folder are not lower-cased

did you mean previously  existed  bot? created by composer or not?

ps: current migration script use `Main.dialog` as a flag of old structure bot and apply serialization

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2360
