### ISSUE TITLE
Getting the user properties to store in DB

### ISSUE THREAD

**Issue by vidyakdil** [microsoft/BotFramework-Composer#2366]
I've created a Bot solution where I identify certain user inputs as user attributes and store them in DB with reference to the user details.

eg: If a user is chatting with Bot in Facebook channel, few entities identified by LUIS is stored in form of JSON in a table against the ConversationID of the user for reference and few analysis

 As the properties we are setting (like user.age) in Composer also serves a similar purpose, Is there any way by which we can get these values in every turn so that we can store them in DB.

**Comment by hibrenda** [comment]
You can use cosmosDB to save the botstate. please reference #2339

**Comment by hibrenda** [comment]
if this does not solve your issues, feel free to reopen.

**Comment by vidyakdil** [comment]
Hi @hibrenda  , my requirement is not to log the conversation as it is. From the incoming user activity, I would like to get if any user property got filled. e.g: user.age, user.name . If so, fetch that data and store it in the DB. Is there a way by which I'll be able to just get the user property filled.

**Comment by cwhitten** [comment]
@vidyakdil can you just inspect the existence of those variables and make a call to the database using the HTTP Action?

**Comment by SattaRavi** [comment]
@mchelen - we are looking to get conversation id but cannot find the data under the value.conversation object ? more here #3757
