### ISSUE TITLE
Use folder to manage dialog

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2376]
## Is your feature request related to a problem? Please describe.
When the dialog is too many it is hard to manage them in one level.

## Describe the solution you'd like
 If support folder in dialog level the structure will be more clear.

**Comment by hibrenda** [comment]
Yue is asking if we have similar solution as LU/LG for dialog hierarchy. eg. common folder for dialog used by other  dialog.

**Comment by xieofxie** [comment]
I guess Yue needs folder in the navigation column? For example, add a new folder button in the bottom
![image](https://user-images.githubusercontent.com/2876650/77631712-eca92e80-6f87-11ea-86fb-4feed5c23d22.png)

**Comment by zhixzhan** [comment]
The latest bot file structure have some changes, integrated with multiple locale support.
https://github.com/microsoft/BotFramework-Composer/pull/2164.  for one dialog, the folder abstract is
```
    /[dialog]
        [dialog].dialog
        /dialogs/[childs]
        /language-generation
            /[locale]
                 [dialog].[locale].lg
        /language-understanding
            /[locale]
                 [dialog].[locale].lu
```

you can put "common dialogs" in /dialogs

**Comment by hibrenda** [comment]
item2 in #2008 as well.

**Comment by cwhitten** [comment]
please follow #2008 for updates to Design/UX of dialog visualization

**Comment by gary-x0pa** [comment]
May I know how this issue is solved? How do we put dialogs in folders/nested folders

**Comment by zhixzhan** [comment]
> May I know how this issue is solved? How do we put dialogs in folders/nested folders

Hi @gary-x0pa you can put your folder like this

```
    /[dialog]
        [dialog].dialog
        /[your-folder]
        /dialogs/[childs]
        /language-generation
            /[locale]
                 [dialog].[locale].lg
        /language-understanding
            /[locale]
                 [dialog].[locale].lu
```

**Comment by gary-x0pa** [comment]
I tried this and the nested dialog folder doesnt show up in the bot composer ui?

**Comment by zhixzhan** [comment]
@gary-x0pa Yes, our current strategy is exclude customize folder from composer management, if files in composer named path like 
```
        /dialogs/**
        /language-generation/**
        /language-understanding/**
```
composer will apply some reformat or migration on those files inside.
