### ISSUE TITLE
could not create the dialog in begin dialog in form dropdown 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2379]
- add the action "begin dialog"
- select "create a new dialog" in begin dialog drop down list
![image](https://user-images.githubusercontent.com/43408889/77627424-d6986f80-6f81-11ea-9caa-df0164745f38.png)
- hit errors and could not proceed

**Comment by a-b-r-o-w-n** [comment]
@hibrenda can you try again today? I wasn't able to repro on master.
