### ISSUE TITLE
need hints for how to use certain variables like options in begin a dialog

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2380]
## Is your feature request related to a problem? Please describe.

Some times the explanation just explains itself literally, but I still don't know how to use these variables in the called dialog
![image](https://user-images.githubusercontent.com/2876650/77632151-8e308000-6f88-11ea-8d9c-2c26fdc6d13d.png)

**Comment by xieofxie** [comment]
OK, I just knew that it could be used like dialog.taskContent if
![image](https://user-images.githubusercontent.com/2876650/77714567-46efd100-7014-11ea-8ca5-f87d440a1c11.png)

**Comment by hibrenda** [comment]
need to provide a sample and includes following scenarios.
- begin a dialog with options and properties
- activity processed
