### ISSUE TITLE
incomplete rename dialog capability

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2383]
## Is your feature request related to a problem? Please describe.

Rename a dialog is not supported or it is incomplete?
(I rename in the right top but nothing happens)

![image](https://user-images.githubusercontent.com/2876650/77634143-73abd600-6f8b-11ea-95e8-aa3f63c69013.png)

## Describe the solution you'd like

Also add a rename option here
![image](https://user-images.githubusercontent.com/2876650/77634209-8e7e4a80-6f8b-11ea-8ef9-281d9943bf53.png)

## Additional context

https://github.com/microsoft/BotFramework-Composer/issues/1741

**Comment by hibrenda** [comment]
Tracked in #1741
