### ISSUE TITLE
allow word wrap, line numbers, resize for rich text editors

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2385]
## Is your feature request related to a problem? Please describe.

Word wrap, line numbers should be options
Actually we have plenty of space for editors like these:

![image](https://user-images.githubusercontent.com/2876650/77634587-2da34200-6f8c-11ea-9fae-a954d0c7614e.png)

## Additional context

https://github.com/microsoft/BotFramework-Composer/issues/1041

**Comment by a-b-r-o-w-n** [comment]
Let's get design input before making this change. I think it's reasonable to actually add some global configuration in the settings page so this can be set on a per-user basis, sine we all have opinions about these options.

**Comment by KayMKM** [comment]
for example in calendar skill:
![image](https://user-images.githubusercontent.com/19773357/77882225-26817a00-7293-11ea-997c-6520e55a5e92.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2552
