### ISSUE TITLE
option button of trigger doesn't display

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2386]
## Describe the bug
![image](https://user-images.githubusercontent.com/19773357/77644117-85957500-6f9b-11ea-9f41-cc252f2a27bb.png)
there should display a option button like dialog
![image](https://user-images.githubusercontent.com/19773357/77644216-a65dca80-6f9b-11ea-9f93-49529d885314.png)
seems the button is hidden by scroll bar

## Version

stable branch

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. open a bot with too many trigger that need to scroll
2. try to delete a trigger

## Expected behavior

the option button display when focus on the trigger

**Comment by hibrenda** [comment]
please reference https://github.com/microsoft/BotFramework-Composer/issues/1774

**Comment by hibrenda** [comment]
addressed via #2331
