### ISSUE TITLE
Have we already supported EditActions in Composer?

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#2392]
## Describe the bug

![image](https://user-images.githubusercontent.com/32191031/77719034-490b5d00-701f-11ea-9a5b-54312eed2cf1.png)

If we support, we need to add it to the visual menu, and fix the form display issue. 

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by a-b-r-o-w-n** [comment]
We "support" it but need a visual design before exposing it in the menu. We do not want to create actions in the form, only through the visual designer. cc @yeze322

**Comment by yeze322** [comment]
@luhan2017 @a-b-r-o-w-n We can, there is a related item blocking us from supporting EditActions: #2044 , we are in the UX design stage

**Comment by yeze322** [comment]
loop in @sangwoohaan

**Comment by hibrenda** [comment]
![image](https://user-images.githubusercontent.com/43408889/77914848-18e6e700-72c9-11ea-8c59-41448e81e37a.png)
This exist in Interruption sample, we need to fix it.

**Comment by cwhitten** [comment]
@hibrenda until we have a visual design for the form we should remove this from the sample

**Comment by cwhitten** [comment]
Closing as duplicate
