### ISSUE TITLE
copy/cut to OS's clipboard

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2395]
## Is your feature request related to a problem? Please describe.

Currently, copy/cut happen in internal state of composer.
It would be better to use OS's clipboard to fulfill these functions.
Thus enable scenarios like copy paste to another composer project, use clipboard history management software

**Comment by cwhitten** [comment]
unassigning @yeze322 . this need to be discussed & prioritized

**Comment by yeze322** [comment]
A good news here is we are closer to it after #2236 .
No technical blocking issue, we can achieve that by leveraging Action Consturctor and Copy Constructor

**Comment by benbrown** [comment]
I think this is important too, this was part of my original copy/paste spec. 

This allows someone to copy and paste into a text document, then copy back into composer, etc.

This would enable:
* copy between dialogs
* copy between projects
* copy from an existing library of stuff into a new project

**Comment by yeze322** [comment]
@benbrown Ben do you have comments on how we can copy LG / LU (and QnA) resources along with 
dialog via the clipboard?

I suppose that we need a serialize/deserialize protocol, for example when I copy a TextInput (it has LG & LU resources), the content in the clipboard would be
```ts
const clipboardContent = {
  composer-version: '1.1.1',
  dialog: { $type: 'Microsoft.TextInput' },
  lg: [ { name: '<regenerate an id>', content: '- hello' } ],
  lu: [...],
  <other external resources>: [...],
}
```

**Comment by yeze322** [comment]
To be compatible with plain text copy, Zhixiang and I figured out another format when serialzing action with LU resources
```
        {
          "$kind": "Microsoft.TextInput",
          "$designer": {
            "id": "7dnCij"
          },
          "maxTurnCount": 3,
          "alwaysPrompt": false,
          "allowInterruptions": true,
          "prompt": "${bfdprompt-7dnCij()}",
          "_lu": "-hi\n-hello"
        }
```
