### ISSUE TITLE
expression input box will lost focus if it occurs syntax error

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2396]
## Describe the bug

expression input box will lost focus if it occurs syntax error, or the error is solved.

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. add a if condition
2. choose expression as condition
3. input an expression like "dialog.result==xxx"
4. the focus lost when enter the "=" of dialog.

## Expected behavior

you can always focus on input box

## Screenshots

![image](https://user-images.githubusercontent.com/19773357/77739899-46bff780-704d-11ea-93ad-be408ca3fa1f.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2408
