### ISSUE TITLE
inline lg editor always shows warning, even for valid lg

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2400]
new trigger wizard to create the new intent with utterance. 

![image](https://user-images.githubusercontent.com/43408889/77750240-67447d80-705e-11ea-9976-e95acf907aab.png)

**Comment by a-b-r-o-w-n** [comment]
@liweitian it looks like we just need to provide the LU editor with the diagnostics and let it handle rendering the error/warning.

**Comment by hibrenda** [comment]
The warning is also showed for inline form as well.
![image](https://user-images.githubusercontent.com/43408889/77813995-1f6a3880-70e8-11ea-9976-1c8582d2c337.png)
![image](https://user-images.githubusercontent.com/43408889/77814002-33ae3580-70e8-11ea-861a-d19899638671.png)

**Comment by a-b-r-o-w-n** [comment]
I think I misunderstood what this issue was. @zhixzhan This is likely another parser/lsp bug.
