### ISSUE TITLE
new created bot will share the same runtime if bot name is same with the deleted bot

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2401]
- create a bot named "EchoBot-1"
- start bot to create the bot runtime under plugin folder
- delete the bot asset under composer directory
- re-create the bot with same name  "EchoBot-1"
![image](https://user-images.githubusercontent.com/43408889/77751000-d8d0fb80-705f-11ea-8f26-b4fb3b64d191.png)

The bot id will be same, so all the new created bot assets will be saved in old bot runtime folder if I click start bot later. This will mixed new bot assets with old bot assets. 
![image](https://user-images.githubusercontent.com/43408889/77750867-842d8080-705f-11ea-9dff-478c54f347f4.png)
![image](https://user-images.githubusercontent.com/43408889/77750917-a1624f00-705f-11ea-9b80-0f37e05f3f97.png)

**Comment by boydc2014** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2716
