### ISSUE TITLE
[dialog factory] create lg template when an lg field has a default value

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#2406]
## Describe the bug

Currently, when adding actions that include default values for lg, like QnA step, the editors complain that there are no templates in the lg file. To fix this, the form should create one if there is no value and a default is provided.

## To Reproduce

1. Create a new QNA maker step in a brand new bot without any lg (like EmptyBot).

## Expected behavior

No error should be shown.

## Screenshots

![image](https://user-images.githubusercontent.com/3619060/77788724-ff227700-701e-11ea-805f-f185a25d1993.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/issues/2247

**Comment by a-b-r-o-w-n** [comment]
re-opening due to bug in #2487

**Comment by a-b-r-o-w-n** [comment]
@yeze322  let's consider this case during the unified api work.

**Comment by yeze322** [comment]
> @yeze322 let's consider this case during the unified api work.

Okay, it could be (and seems already been) solved.

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2718
