### ISSUE TITLE
settings scope cannot be accessed like described in doc

### ISSUE THREAD

**Issue by kenakamu** [microsoft/BotFramework-Composer#2409]
## Describe the bug
I follow https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot to add QnA maker but action property didn't properly read if I simply use ```settings.qna.hostname```.
Instead, I have to do ```${settings.qna.hostname}``` to get the settings value 

## Version
I just get from stable branch.

## Browser
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x ] Edge

## OS
- [ ] macOS
- [ x ] Windows
- [ ] Ubuntu

## To Reproduce
1. Go to 'https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot' and add QnA 

## Expected behavior
Just works

## Additional context
Workaround is to use ${}

**Comment by hibrenda** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/issues/2344

**Comment by kenakamu** [comment]
Thanks, so using =settings.xx is the proper way than doing ${}?
