### ISSUE TITLE
Inspection Middleware disabled ?

### ISSUE THREAD

**Issue by InnoraG** [microsoft/BotFramework-Composer#2410]
## Describe the bug

Emulator inspector not able to debug Composer generated bot

## Version

4.7.0-preview-191208-1

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Composer -> Start Bot
2. Emulator -> Debug

## Expected behavior

Should see like "/INSPECT attach db2fbbba-da64-4d74-b4b8-3d4dc054f0a9"

**Comment by luhan2017** [comment]
Yes, I disabled it because the trace of BotState is already by-default enabled in the Bot and emulator. 
Could I know what is the specific feature you want for InspectionMiddleware, can "BotState trace" meet your requirement? @InnoraG

**Comment by InnoraG** [comment]
Thanks for clarity.
BotState can be ok when in local dev environment but inspection middleware is great for remote debugging of production bot, I am using inspection middleware to troubleshoot use case on real user on real channel for example.
Inspection middleware is the dependency of Bot Framework Emulator -> Debug -> Start Debugging so this feature doesn't currently work on Composer generated bots.
Anyway it could be activated easily.

**Comment by luhan2017** [comment]
@InnoraG you can enabled it by runtime configuration now.
