### ISSUE TITLE
Being able to use lg custom functions on condition expressions

### ISSUE THREAD

**Issue by eduardmartos** [microsoft/BotFramework-Composer#2413]
## Is your feature request related to a problem? Please describe.

BotFramework Composer
v2.0
SDK 4.8.0

Many times we need to validate data with a complex and very long lg expressions. We can create this lg expressions as an lg templates that can be break down in an other templates/functions for an easy mantain of that expressions.
But, when we need to use that lg custom templates on a condition, we can’t.
Composer Editor tell as that the expressions on conditions can be only memory vars or pre-built functions.

## Describe the solution you'd like
I would like to use my custom lg template/function in a condition like that:

`common.lg      # validateID(text)    - length(text)==9 && isMatch(text, ‘[0-9]{9}’)`

Condition: `${validateID(turn.activity.text)}`

## Describe alternatives you've considered

# Additional context
![609552D0-A7E7-4FBC-A492-787A5AE8F649](https://user-images.githubusercontent.com/54709623/77846200-a08f0180-71b4-11ea-9dd9-694ee344fe39.jpeg)

![897D8531-ECA2-416A-B9DF-093733E84D13](https://user-images.githubusercontent.com/54709623/77846209-b43a6800-71b4-11ea-85c3-8db103de4bd5.jpeg)

![D6353B45-4E53-453D-AD77-CF66C1B14477](https://user-images.githubusercontent.com/54709623/77846212-bdc3d000-71b4-11ea-959f-9c8d4462f2a1.jpeg)

**Comment by vishwacsena** [comment]
Tracked via Microsoft/BotBuilder-Dotnet#3652
