### ISSUE TITLE
multi-line value editor

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2415]
## Is your feature request related to a problem? Please describe.

If we use expression for a value, it could be very long and a single-line editor is quite limited.

![image](https://user-images.githubusercontent.com/2876650/77870119-1f4a7400-7273-11ea-8735-3be39c59ccc0.png)

## Describe the solution you'd like

Change it to multi-line

**Comment by ssss141414** [comment]
![image](https://user-images.githubusercontent.com/18118994/77882648-fbe3f100-7293-11ea-8aa5-313168c12404.png)
My set properties are very long, but they're hard to edit.

**Comment by mareekuh** [comment]
@DesignPolice - could you please include a visual solution for this a part of the overall design language for Nodes.
