### ISSUE TITLE
hint for undo/redo

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2416]
## Is your feature request related to a problem? Please describe.

Show hints for undo/redo. Or we don't know want will be done.

![image](https://user-images.githubusercontent.com/2876650/77871422-a9e0a280-7276-11ea-9194-003ae8e9b8d9.png)

## Describe the solution you'd like

Show what will be done when mouse is over the button

**Comment by hibrenda** [comment]
UI display (for last time state show up)  if click undo

**Comment by hibrenda** [comment]
#1451
