### ISSUE TITLE
keep previous value when changing type like in forms

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2417]
## Is your feature request related to a problem? Please describe.

When changing type, the previous value will be cleared even if you change back

![image](https://user-images.githubusercontent.com/2876650/77871513-f1672e80-7276-11ea-912e-9d00c8751ccd.png)

It is quite unpleasant!

## Describe the solution you'd like

Keep a cache in composer

## Additional context

Similar to https://github.com/microsoft/BotFramework-Composer/issues/1074

**Comment by a-b-r-o-w-n** [comment]
Does the undo feature not work for this scenario?

**Comment by xieofxie** [comment]
Yes, undo could revert the change.
But I would like a more friendly approach like caching values for different types in the composer and when user changes/tries different types, user could always get the value for that type easily.

**Comment by cwhitten** [comment]
cc @sangwoohaan @mareekuh 

We need control guidance for the following types

<img width="285" alt="Screen Shot 2020-03-31 at 9 54 11 AM" src="https://user-images.githubusercontent.com/1156704/78053557-9f391280-7335-11ea-9f53-6330e0b06039.png">

**Comment by mareekuh** [comment]
@cwhitten  - Sang is working on this. @sangwoohaan, maybe you can list a short update here?
