### ISSUE TITLE
Visual Editor's multi-selection feature is broken

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2421]
## Describe the bug
Drag to select multiple nodes always failed.

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
@a-b-r-o-w-n This feature was broke by Form Extension PR.
`onFocus` will redraw Visual Editor completely caused the selection states cleared. Do you know what's the changes on `onFocus` API or ExtensionContainer?

**Context**
Visual Editor's multi-selection behavior:
1. Start dragging
2. If only one node is selected, call `onFocus` with that node's id
3. If multiple nodes selected, call `onSelect` with node ids
4. End dragging

**Comment by a-b-r-o-w-n** [comment]
I'll fix this today.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2439
