### ISSUE TITLE
error message is different from UI

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2422]
## Is your feature request related to a problem? Please describe.

For example: skill host bot id is empty in ui
![image](https://user-images.githubusercontent.com/2876650/77875066-925ae700-7281-11ea-9d5d-163b4500b612.png)
It complains about client id
![image](https://user-images.githubusercontent.com/2876650/77875073-9555d780-7281-11ea-822a-f3adb887795e.png)

**Comment by hibrenda** [comment]
This issue addressed 2 issues. 
- check for empty field if this can not be null.
- how composer user can get the errors more specific instead of the default SDK errors. 
   eg. error information display as : "settings.skillid is null".
