### ISSUE TITLE
Sorry, something went wrong with connecting bot runtime

### ISSUE THREAD

**Issue by prasadreddybv** [microsoft/BotFramework-Composer#2425]
Hello,

I have  created a simple bot with a greeting message and QnA Integration including in it.
when i try to publish, the bot is giving the below error even though i have upgraded to the .Net Core SDK 3.1.

Error : Could not execute because the specified command or file was not found. Possible reasons for this include: * You misspelled a built-in dotnet command. * You intended to execute a .NET Core program, but dotnet-bin/Debug/netcoreapp3.1/BotProject.dll does not exist. * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

Please find below the logs.

![image](https://user-images.githubusercontent.com/28754600/77902910-91d14900-729f-11ea-8781-8aad3e2cff96.png)

These are the reference packages i have used in the code. I have checked it by using dotnet build command under my bot folder and the build has happened successfully.

![image](https://user-images.githubusercontent.com/28754600/77903203-1c19ad00-72a0-11ea-93c4-49e7544bb9e5.png)

Still i am facing this issue and could not run the bot and test it. Please assist me on this if i have missed out anything.

**Comment by prasadreddybv** [comment]
The issue got resolved when i restarted the composer and cretaed a new bot from scratch.
Hence closing the issue. Thanks.

**Comment by TylerOdenthal** [comment]
I still think this is an issue, I experienced it today using Composer Desktop. 

Remaking my bot would waste a day.

![SorryConnectingToBotRuntime](https://user-images.githubusercontent.com/63730511/86832767-78cdf600-c04d-11ea-858f-36dd5631429e.png)

**Comment by TylerOdenthal** [comment]
I think I'm experiecing a similar problem. Remaking my bot would waste a day, so it isn't a great solution.

I was trying to create a new LUIS intent and upon next compile I got this.

![SorryConnectingToBotRuntime](https://user-images.githubusercontent.com/63730511/86832890-a155f000-c04d-11ea-8537-985b59baecc4.png)

I was constructing a new intent inside of the main dialog.
