### ISSUE TITLE
After connecting to skill, sending response will cause 'No generator found for language '

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2426]
## Describe the bug

I follow this https://github.com/microsoft/BotFramework-Composer/blob/master/docs/how-to-connect-to-remote-skill.md

And if I want to send something after the skill, it will say 
![image](https://user-images.githubusercontent.com/2876650/77903701-dff14700-72b5-11ea-91c1-43cf37fd5227.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by darrenj** [comment]
In our multi-locale support for VA there's a number of scenarios where locale is sometimes not set on incoming activities (e.g. beginConversation, events, speech, some channels). To address the ocassional lack of locale we have a localeMiddleware that stamps locale on an activity with a default if it's not present which is important for down-streams scenarios that expect a locale to be present.

Not saying that's this is the solution for the above but FYI

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/botbuilder-dotnet/pull/3624

**Comment by xieofxie** [comment]
No, I think this issue should be fixed via https://github.com/microsoft/botbuilder-dotnet/pull/3739
Fallback to some default is not the correct behavior since we have locale when the turn started.
