### ISSUE TITLE
"No generator found for language" in webchat

### ISSUE THREAD

**Issue by VanyLaw** [microsoft/BotFramework-Composer#2427]
## Describe the bug

Publish a todoluis to azure, but show "No generator found for language" in webchat
![image](https://user-images.githubusercontent.com/21174180/77903724-eb447280-72b5-11ea-9302-d58387095932.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/botbuilder-dotnet/pull/3624
