### ISSUE TITLE
keep 'Edit mode' on in 'Bot Responses' when switching files

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2443]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when switching files in 'Bot Responses', I have to switch 'Edit mode' on every time

**Comment by cwhitten** [comment]
To implementer:

When someone selected "Edit mode" in the all-up LU or LG pages, persist this setting globally and let it hydrate the page during ongoing navigation
