### ISSUE TITLE
Can't navigate to Users folder in Open

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2447]
## Is your feature request related to a problem? Please describe.

 I'm always frustrated when I am opening the bot:
I can't enter the path, I can't even find Users folder!
![image](https://user-images.githubusercontent.com/2876650/77999629-92ccae00-7365-11ea-9ac2-ecb6fe970c06.png)

**Comment by boydc2014** [comment]
@liweitian  can you help investigate this?

**Comment by a-b-r-o-w-n** [comment]
I would be cool to allow typing with autocomplete instead of having to use the list view to select a location

**Comment by liweitian** [comment]
it seems this is another permission issue. The glob function in globby does not have the permission to scan some directory.
