### ISSUE TITLE
keep getting taken to template selection when selecting destination folder while creating a new bot

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#2455]
## Screenshots

![Screen Recording 2020-03-31 at 02 22 PM](https://user-images.githubusercontent.com/3619060/78076459-4ed4ab80-735b-11ea-9413-7ed81acd3ab6.gif)

## Additional context

refs #2412

**Comment by a-b-r-o-w-n** [comment]
Well it seems like I am unable to repro this morning. ¯\_(ツ)_/¯

**Comment by hibrenda** [comment]
close it for now. if hit this again, feel free to open.
