### ISSUE TITLE
Creating a bot from scratch doesn't give you a blank sheet

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#2457]
When I create a new bot from scratch, the greetings trigger comes with a loop and an if/else branch with some random conditions. It should give me a completely blank canvas with just a greetings trigger.
![Screen Shot 2020-03-31 at 2 58 04 PM](https://user-images.githubusercontent.com/50963385/78079071-3fa42c80-7360-11ea-85ef-6ba491ce6225.png)

**Comment by cwhitten** [comment]
This is be design, closing.
