### ISSUE TITLE
The property pane for Delete properties action is broken

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#2458]
It appears to be broken.

![Screen Shot 2020-03-31 at 3 34 40 PM](https://user-images.githubusercontent.com/50963385/78082977-28b60800-7369-11ea-8878-c81eb1150f7f.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2460
