### ISSUE TITLE
Trigger phrase fields of old bot samples appear as a single line input field, and it doesn't show right content

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#2459]
When you opened a bot created with an older build (presumably build before the property pane update), the trigger phrase fields of intent triggers appear as a single line input field and the content looks empty(LG all-up view looks correct). This is supposed to be a Monaco editor with LG. 
![Screen Shot 2020-03-31 at 3 55 02 PM](https://user-images.githubusercontent.com/50963385/78083998-ea6e1800-736b-11ea-8844-ffbd326cb552.png)

**Comment by a-b-r-o-w-n** [comment]
Is this a regex recognizer or a luis recognizer? I believe this is the correct UI for regex recognizer

**Comment by sangwoohaan** [comment]
Oh sorry, it was set to Regex. Strange I've never changed it
