### ISSUE TITLE
[Electron] Unable to connect to bot with generic error

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2468]
## Describe the bug

Electron app for Mac. Create a bot from scratch (or use any sample), add a welcome message, hit start bot, connect to it in emulator.

Unable to talk to bot with a generic `No generator found for language` message in Emulator. No additional issues observed in Electron dev tools console or network tab.

## Version

Application SHA
test
SDK runtime packages
4.7.0-preview-191208-1
Getting Help

## Browser

Electron app

## OS
MacOS Catalina 10.15.4

## To Reproduce

1. Install mac os electron app from releases.
2. Create a new bot from scratch (or open any sample)
3. Add a welcome message (if creating an app from scratch)
4. Start bot
5. Open in emulator.

## Expected behavior

Able to talk to bot in emulator.

## Screenshots

![image](https://user-images.githubusercontent.com/20918136/78178265-36749780-7414-11ea-9d85-b3de688e6cb4.png)

## Additional information
- For bots with LU content, I can verify that clicking on start bot actually publishes the LUIS applications

**Comment by vishwacsena** [comment]
Verify/ ensure that emulator has locale set. 

![image](https://user-images.githubusercontent.com/20918136/78178675-df22f700-7414-11ea-9d72-64c0f89cc0d9.png)

**Comment by cwhitten** [comment]
Emulator issue created to default to this value: https://github.com/microsoft/BotFramework-Emulator/issues/2122
