### ISSUE TITLE
The examples list on the home page leads to a blank screen

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#2469]
## Describe the bug

Clicking on an example in the examples list according to [these instructions](https://docs.microsoft.com/en-us/composer/quickstart-create-bot#create-an-echo-bot) results in a blank page.

## Version

test

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Install Composer according to [these instructions](https://docs.microsoft.com/en-us/composer/setup-yarn)
2. After starting Composer in a browser, click the Echo Bot button at the top of the Examples list on the homepage.
3. See blank page

## Expected behavior

The Composer UI should remain loaded in the browser window and the popup to setup the example should be displayed.

## Screenshots

![image](https://user-images.githubusercontent.com/41968495/78181637-991c6200-7419-11ea-9690-3f1d26d462f5.png)

## Additional context

In the terminal:

```
Composer now running at:

http://localhost:3000

GET / 304 9.202 ms - -
GET /robots.txt?1585771191328 200 1.274 ms - 834
GET /api/projects/recent 304 1.865 ms - -
GET /api/assets/projectTemplates 304 4.526 ms - -
GET /api/storages 304 0.660 ms - -
GET /api/projects/recent 304 0.945 ms - -
GET /api/storages 304 0.405 ms - -
GET /api/assets/projectTemplates 304 9.901 ms - -
GET /api/assets/projectTemplates 304 2.377 ms - -
GET /api/assets/projectTemplates 304 2.150 ms - -
```

**Comment by v-kydela** [comment]
@zxyanliu - Should the documentation say to use the stable branch instead of master?

**Comment by a-b-r-o-w-n** [comment]
@v-kydela stable is the default branch when cloning this repository, so for most users, there is no need to tell them to use that branch.

Closing this as it should already be addressed in the latest version of master.
