### ISSUE TITLE
Revise the runtime code we provide to users for configurability

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#2471]
This is a draft ticket the requirements for this work are being gathered right now.

We need to make sure the runtime code we provide to users during the eject process (#2470) as well as when we deploy a bot in its unmodified form is well designed for configurability and extension.

Some major behaviors should be configuration driven:
* location of declarative assets
* state storage type
* TelementryloggerMiddleware (#2423)
* [Dong] ShowTypingMiddleware (#1781 )
* [Dong] InspectionMiddleware (#2410)
* set up to work from a sub-folder of a bot project
* TranscriptLoggerMiddleware 
* some channel related configures such as Direct Line App Service Extension(#2240 ), Direct Speech Channel(#1638)...

We will need to make sure that, when deployed, the runtime will still be able to find the assets, and those assets will be in a logical location.

MORE TBD

**Comment by boydc2014** [comment]
@benbrown  added two examples of middle-wares and @luhan2017  may have more options

**Comment by luhan2017** [comment]
#2423 this PR is to enable a telemetry middleware in botproject.

**Comment by luhan2017** [comment]
@benbrown, are you working on this right now?  @zidaneymar in my team is working on some issues relates to middleware and some specific channel configurations. He probably can resolve most of the items in this list.

**Comment by benbrown** [comment]
@luhan2017 I am not actively working on the code - I was just trying to gather requirements for the next revision of the code, particularly as it relates to the new "eject" feature described in #2470

**Comment by luhan2017** [comment]
> @luhan2017 I am not actively working on the code - I was just trying to gather requirements for the next revision of the code, particularly as it relates to the new "eject" feature described in #2470

OK, then I will ask @zidaneymar to work on this, and we can discuss more details if needed.

**Comment by InnoraG** [comment]
This draft would bring great enhancement.
Please look for adapters as well if possible : https://github.com/microsoft/botbuilder-dotnet/tree/master/libraries/Adapters

**Comment by carlosscastro** [comment]
Hello @luhan2017 ! I'm doing some refactors on bot project and integration with other potential deployment avenues such as azure Functions down the road. Do you have a branch where you folks are working?

**Comment by cwhitten** [comment]
@carlosscastro @luhan2017 please address the following security issues as part of this work:

Critical

https://fuselabs.visualstudio.com/Composer/_componentGovernance/115206/alert/2301093?typeId=1031785

 

Medium Priority

https://fuselabs.visualstudio.com/Composer/_componentGovernance/115206/alert/2226216?typeId=1031785
https://fuselabs.visualstudio.com/Composer/_componentGovernance/115206/alert/2301078?typeId=1031785
https://fuselabs.visualstudio.com/Composer/_componentGovernance/115206/alert/1967473?typeId=1031785
https://fuselabs.visualstudio.com/Composer/_componentGovernance/115206/alert/1967474?typeId=1031785
https://fuselabs.visualstudio.com/Composer/_componentGovernance/115206/alert/2301091?typeId=1031785
https://fuselabs.visualstudio.com/Composer/_componentGovernance/115206/alert/2301092?typeId=1031785
https://fuselabs.visualstudio.com/Composer/_componentGovernance/115206/alert/1702087?typeId=1031785
https://fuselabs.visualstudio.com/Composer/_componentGovernance/115206/alert/2571210?typeId=1031785
https://fuselabs.visualstudio.com/Composer/_componentGovernance/115206/alert/1605678?typeId=1031785
https://fuselabs.visualstudio.com/Composer/_componentGovernance/115206/alert/2656470?typeId=1031785

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2679
