### ISSUE TITLE
Update "open bot" feature to recognize legacy "custom runtime" projects

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#2472]
Previous versions of Composer would include the runtime code in every new project, resulting in a folder structure like "MyBot/proj.cs" and "MyBot/ComposerDialogs/Main.dialog"

Newer versions of Composer do not include runtime code, resulting in a much flatter structure.

We should update this behavior to recognize both as bot projects, and, in connection with the runtime settings page (#2470) automatically configure legacy projects to use their locally packaged runtime when testing

- [ ] Detect both file structures as "bot projects" (do not require opening ComposerDialogs directly)
- [ ] When a bot project contains a ComposerDialogs folder, if custom runtime settings are absent, automatically route user to the /settings/runtime page and pre-fill the location and start command with the known location of the runtime

**Comment by boydc2014** [comment]
See https://github.com/microsoft/BotFramework-Composer/issues/2470#issuecomment-607700037, this is somehow conflict with allow user to config path to runtime.

**Comment by benbrown** [comment]
A different solution has superceded this.
