### ISSUE TITLE
Exporting bot to repackage it

### ISSUE THREAD

**Issue by EPinci** [microsoft/BotFramework-Composer#2473]
## Is your feature request related to a problem? Please describe.

I need to build a bot as part of larger microservices oriented application hosted in AKS.
I need to be able to package the bot  in a container and execute in AKS along the other components.

## Describe the solution you'd like

I'd like to be able to "publish to folder" or "export somehow" a code solution that I can repackage (in my case in a container).

## Describe alternatives you've considered

At the moment looks like the only publishing option is directly to azure.

**Comment by cwhitten** [comment]
Hello @EPinci. If I understand your scenario, the assets that Composer generates when you create the bot using the tool is the code solution you're seeking to repackage. If you navigate on your filesystem to the location where you created the bot you will see all of these assets for you to take and use. Does this help?

**Comment by EPinci** [comment]
Hey Chris,
in the folder I picked to save the created bots I can see some ```.dialog``` files and three folders (language-generation, language-understanding and settings).
None of this is a c# project or something I recognize as repackageable.
What am I missing?

**Comment by EPinci** [comment]
@cwhitten I'm using the preview build published in the releases.

**Comment by cwhitten** [comment]
Hi @EPinci thanks for your patience.

When https://github.com/microsoft/BotFramework-Composer/pull/2572 lands in the `master` branch this behavior will come back into the app. We've diverged from `stable` a bit while landing new features and UX in this area.
