### ISSUE TITLE
Extend bot code with custom routines

### ISSUE THREAD

**Issue by EPinci** [microsoft/BotFramework-Composer#2474]
## Is your feature request related to a problem? Please describe.

I need to build a bot as part of larger microservices oriented application hosted in AKS.
I need to be able to extend the bot my code with custom code to interact with other services and data sources (e.g.: a database).

## Describe the solution you'd like

I'd like to be able to add to a bot either a compiled DLL or .Net source code to call from the graphic designer in order to integrate the bot with the rest of the application.

## Describe alternatives you've considered

It is not documented how the current composer generated bot are supposed to integrate with data ecosystems.

**Comment by cwhitten** [comment]
Hello @EPinci and thanks for opening the issue. Mechanisms to create and expose custom bot code will soon be available in Composer. Adaptive Dialogs has an extensibility feature that allows one to create custom dialog actions. We anticipate the UX and documentation will be available in the May '2020 timeframe.

**Comment by EPinci** [comment]
That sound super cool, thank you.

**Comment by cwhitten** [comment]
@EPinci this is possible by ejecting your runtime and following the instructions in the /schemas directory
