### ISSUE TITLE
Getting all Responses from .lg file and qna KB in emulator

### ISSUE THREAD

**Issue by prasadreddybv** [microsoft/BotFramework-Composer#2475]
## Describe the bug

If user asks any query, the bot is responding with all the responses configured in the LG file.

## Version

Release: Preview 2.0

## Browser

 - [ ] Chrome

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

 Windows

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to ''

## Expected behavior

Bot should respond with only one answer from the configured responses

## Screenshots

![image](https://user-images.githubusercontent.com/28754600/78212495-88c5bf00-74cd-11ea-8154-0d16b6386dfd.png)

![image](https://user-images.githubusercontent.com/28754600/78212569-c3c7f280-74cd-11ea-9650-c230a0fd7c8c.png)

## Additional context

Also let me know if we can split up the response and send it back to user.

**Comment by hibrenda** [comment]
Hi, Could you attache the LG file so that we can look into detail?

**Comment by prasadreddybv** [comment]
Its a common LG file imported by default when i created the bot

**Comment by cwhitten** [comment]
@pchoudhari where is the content in your screenshot defined? In the common.lg file? Please attach a snippet so we can inspect it. I believe you may have an error in it.
