### ISSUE TITLE
OAuth login not works

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2477]
## Describe the bug

When using OAuth login, the bot will occurs error: Object reference not set to an instance of an object.

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Add an OAuth login step
2. Start the bot
3. Bot returns error: Object reference not set to an instance of an object.

## Expected behavior

OAuth step works well

**Comment by luhan2017** [comment]
This is because a sdk issue, in the sdk side, it requires alwaysPrompt field not null. you can work around this by set it to true.

**Comment by luhan2017** [comment]
I've already submitted a PR in the sdk side. https://github.com/microsoft/botbuilder-dotnet/pull/3664

**Comment by cwhitten** [comment]
Closing as a duplicate tracked in the comment above.
