### ISSUE TITLE
Confusing UX to add HTTP Header

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2478]
## Describe the bug

the header won't be saved after set the header

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. add a httprequest step
2. add a header
3. click other elements to save it
4. click httprequest step and check the header

## Expected behavior

header is saved

**Comment by KayMKM** [comment]
I found I need to press enter to save the header now... But I think this behavior is not consistent with others. I think the behavior should be when user finished editing the input box, and the user click other elements then the header is saved and append another empty header input box.

**Comment by a-b-r-o-w-n** [comment]
cc @sangwoohaan 

@KayMKM This is consistent with other form properties (choice input, input validations, etc). We will take a look at the UX of this to see if there are improvements.
