### ISSUE TITLE
[Electron] Monaco editor is not updating in a few areas 

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/BotFramework-Composer#2479]
## Describe the bug

Upon creation of new trigger (Intent Recognized) Trigger Phrases section freezes

## Version

4.7.0-preview-191208-1 - Desktop version

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Main Dialog
2. Select LUIS as Recognizer Type
3. Create new Trigger, select Intent Recognized
4. You will see an error there. 

## Expected behavior

It should let me (user) add the trigger phrases.

## Screenshots

![Composer-Bug](https://user-images.githubusercontent.com/16351038/78251237-cca3dd00-753c-11ea-9cc7-015b741ee83b.jpg)

## Describe the bug

![image](https://user-images.githubusercontent.com/32497439/78309047-dad30880-74fe-11ea-91cd-6ba301c4963d.png)

## Version
Electron pre-release. 

## OS
- [x] Windows

## To Reproduce

1. Go to 'Settings' on Composer menu
2. Click on 'Settings' in navigation
3. See error

### Bot Responses 

![image](https://user-images.githubusercontent.com/32497439/78309441-cba08a80-74ff-11ea-849f-8c677e06599c.png)

### User Input

![image](https://user-images.githubusercontent.com/32497439/78309533-0e626280-7500-11ea-97c1-428c1bc7c1c7.png)

## Version
Electron pre-release. 

## OS
- [x] Windows

## To Reproduce

1. Go to 'Bot Responses'/'User Input' on Composer menu
2. Select any dialog in navigation pane.
3. Toggle on 'Edit Mode'

## Additional text
I tried electron pre-release and finished the whole [weather bot tutorials](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-introduction) except [the one using LUIS](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis) (due to this [bug](https://github.com/microsoft/BotFramework-Composer/issues/2479)). It is a great experience!

**Comment by boydc2014** [comment]
Hi, @arafattehsin thanks for trying Composer Electron release, we are kind of experiment this approach now, and we are working on adding auto update on it, then we will have a formal release for Electron. 

So can you try the traditional way of using Composer, follow the readme in repo home page for now, and try Desktop version later when have a formal release?

**Comment by cwhitten** [comment]
I've been able to drill-down into a Promise that is not resolving causing this:

https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/packages/lib/code-editor/src/BaseEditor.tsx#L113

**Comment by cwhitten** [comment]
This will be addressed in our next electron released

**Comment by arafattehsin** [comment]
Thanks @cwhitten 👍
