### ISSUE TITLE
Settings show Loading...

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2488]
## Describe the bug

![image](https://user-images.githubusercontent.com/32497439/78309047-dad30880-74fe-11ea-91cd-6ba301c4963d.png)

## Version
Electron pre-release. 

## OS
- [x] Windows

## To Reproduce

1. Go to 'Settings' on Composer menu
2. Click on 'Settings' in navigation
3. See error

## Additional text
I tried electron pre-release and finished the whole [weather bot tutorials](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-introduction) except [the one using LUIS](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis) (due to this [bug](https://github.com/microsoft/BotFramework-Composer/issues/2479)). It is a great experience!

**Comment by cwhitten** [comment]
@zxyanliu the same issue is appearing in multiple places. I'm going to converge this into one ticket and close this as a duplicate.

**Comment by cwhitten** [comment]
see https://github.com/microsoft/BotFramework-Composer/issues/2479
