### ISSUE TITLE
Bot Responses and User Input show Loading...

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2489]
### Bot Responses 

![image](https://user-images.githubusercontent.com/32497439/78309441-cba08a80-74ff-11ea-849f-8c677e06599c.png)

### User Input

![image](https://user-images.githubusercontent.com/32497439/78309533-0e626280-7500-11ea-97c1-428c1bc7c1c7.png)

## Version
Electron pre-release. 

## OS
- [x] Windows

## To Reproduce

1. Go to 'Bot Responses'/'User Input' on Composer menu
2. Select any dialog in navigation pane.
3. Toggle on 'Edit Mode'

## Additional text
I tried electron pre-release and finished the whole [weather bot tutorials](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-introduction) except [the one using LUIS](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis) (due to this [bug](https://github.com/microsoft/BotFramework-Composer/issues/2479)). It is a great experience!

**Comment by cwhitten** [comment]
Closing as a duplicate

**Comment by cwhitten** [comment]
see https://github.com/microsoft/BotFramework-Composer/issues/2479
