### ISSUE TITLE
TextInput action will messed the dialog file

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2490]
- New bot based on Empty template
- Add a TextInput 
- click visual canvas -> the inputs box go away 
- click User input tab -> blank page
- click other trigger -> everything will turn into TextInput
https://recordit.co/PnlY0R3sdj

**Comment by cwhitten** [comment]
@a-b-r-o-w-n https://github.com/microsoft/BotFramework-Composer/commit/df97a7e8ef99572cfa570ad53be912ebe743813a looks to have introduced this behavior

**Comment by a-b-r-o-w-n** [comment]
i reverted the original commit.
