### ISSUE TITLE
Template "todo with luis" not work

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2494]
## Describe the bug

When I create a bot from the template "todo with luis", and use the emulator to test, I got an error.
![image](https://user-images.githubusercontent.com/44257569/78336748-7aa59a80-75c2-11ea-8415-86a576939bee.png)
![image](https://user-images.githubusercontent.com/44257569/78336887-ae80c000-75c2-11ea-8f98-3c9b6be1b0bd.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2497
