### ISSUE TITLE
list value in options is convert to json string

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2498]
## Describe the solution you'd like
When I try to pass a list in begin dialog. The value is converted to a json string. So I have to convert it back to list in another dialog

## Describe alternatives you've considered

The type of value should be retained during passing them between dialogs

**Comment by a-b-r-o-w-n** [comment]
@KayMKM  Can you provide a screenshot of what you see in the form and paste in the resulting dialog data?

**Comment by KayMKM** [comment]
dialog.AttendeeList is a list
![image](https://user-images.githubusercontent.com/19773357/78637442-efd3e100-78dc-11ea-91f1-d51cf1e4976a.png)
in findContactDialog:
![image](https://user-images.githubusercontent.com/19773357/78637488-067a3800-78dd-11ea-8f53-40620e48b216.png)

**Comment by a-b-r-o-w-n** [comment]
This is because you are using the string interpolation expression (`"${dialog.AttendeeList}"`) instead of a value expressions (`"=dialog.AttendeeList"`). Try that and let me know if it works.

**Comment by KayMKM** [comment]
Thanks. It works now.
