### ISSUE TITLE
repeat this dialog not working

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2499]
## Describe the bug

For this dialog, after ask, go back to main
![image](https://user-images.githubusercontent.com/2876650/78351482-6faa3480-75d9-11ea-8647-0ce87bb0286d.png)

## Version

Current master

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by xieofxie** [comment]
Also, what's the difference between 'repeat this dialog' and 'replace this dialog'? Why not just select this dialog in replace?

**Comment by luhan2017** [comment]
Circular reference is not supported in the current declarative loader, so you can't replace yourself right now.

**Comment by luhan2017** [comment]
Is this a trigger in main or a separated dialog? if this is a trigger in main dialog, it is by design to repeat the main dialog. I've tried the Repeat dialog Sample in Action sample, it works well.

**Comment by xieofxie** [comment]
> Is this a trigger in main or a separated dialog? if this is a trigger in main dialog, it is by design to repeat the main dialog. I've tried the Repeat dialog Sample in Action sample, it works well.

Thanks! I understand the replacing main part. My second issue is that option is not used and I created a pr to fix this.

**Comment by pyramidsoftwaresolutions** [comment]
how to apply GOTO concept so that we repeat a flow again from begining?
