### ISSUE TITLE
Publish UX - Composer

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#2503]
https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=877%3A5532

Visual design is done
feature is implemented!'
Close?

**Comment by benbrown** [comment]
What is this ticket for? The development work on this is already underway with a design that was marked as final.

**Comment by DesignPolice** [comment]
@benbrown Sorry Ben, this was/is a final pass to make sure are pulling in as much UI as we can from Fabric - I have made edits to the Modals and have a couple of screens on the List views that I will visit with @mareekuh about today and then we will be done. EOD at the latest

**Comment by mareekuh** [comment]
UX is final, some of the visual comments (included in the figma for the last week and a half) had not been addressed. We have a mandate to align our work across FUSE and across msft. This is part of that. See also email sent on Friday (resent it to you as I couldn’t get it to attach to this one).
This includes:
•	the header for the page (above the nav and listview) will be context sensitive and contain the ‘status’ that is in the UX design part of another header in the list view
•	notifications -> visual representation of progress indications in one place across the app (upper right corner. Marc to figure out how this works across pages)

Hope this helps and let me know if you have questions.
Marc, this should go pretty quickly right?

Marieke

**Comment by DesignPolice** [comment]
I know this is already going, but the Visual pass is done. 

One thing you will above all of the Publish Changes is that we have a blue header. As part of moving back to Azure - we loose our icon and our black background. I don't know when the best time to change that is, but headers will be blue going forward.

Here is the link:
https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=313%3A2805
thanks

**Comment by mareekuh** [comment]
Done!

**Comment by DesignPolice** [comment]
yeah!
