### ISSUE TITLE
Search (Marc & Marieke)

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#2505]

**Comment by DesignPolice** [comment]
I have updated this to have the "filter" icon - not sure what we want to do with this for a11y or as far as R9 - R10 etc. This has been moved to Master Design Specs.

https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=1123%3A19432

**Comment by cwhitten** [comment]
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/3795
