### ISSUE TITLE
Properties panel (Sang)

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#2509]
Project: Authoring

**Comment by DesignPolice** [comment]
@cwhitten what is the timing on this for engineering... I can start on it next week, but would like to know how fast to go, there are a lot of moving parts on this one.

**Comment by a-b-r-o-w-n** [comment]
@DesignPolice I imagine we will be working on this in smaller bits, starting in the next couple of weeks depending on design readiness. Not sure if that helps.

**Comment by DesignPolice** [comment]
Alright @a-b-r-o-w-n that is a good ballpark.
