### ISSUE TITLE
Webchat and Speech (Em and Eyal)

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#2511]
Link to spec https://microsoft.sharepoint.com/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B9A1C050F-EB45-475F-876A-E96CB70F4705%7D&file=WebChat%20for%20Speech%20UX.docx&action=default&mobileredirect=true

**Comment by cwhitten** [comment]
This is tracked via another ticket and shipping in R13
