### ISSUE TITLE
LU does not support new schema

### ISSUE THREAD

**Issue by bobokids** [microsoft/BotFramework-Composer#2524]
## Is your feature request related to a problem? Please describe.

I cannot add the new LU data to composer
![image](https://user-images.githubusercontent.com/19182479/78623616-a377a980-78ba-11ea-8758-1a3f7b39ffec.png)

## Describe the solution you'd like

Support the new schema.

**Comment by hibrenda** [comment]
![image](https://user-images.githubusercontent.com/43408889/78626342-16841e80-78c1-11ea-93d2-6b37c2e52f28.png)

sounds like editing experience is correct in all up. so we need to fix for inline editing

**Comment by zhixzhan** [comment]
I tried in inline editor, seems work fine

<img width="457" alt="image" src="https://user-images.githubusercontent.com/49866537/78629408-90b8a100-78c9-11ea-8bdf-0024bb598e34.png">


@bobokids Does your composer build is latest master? if so, can you upload a demo bot that can re-pro the bug.
