### ISSUE TITLE
Dialog create not restrict name to lowercase

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#2525]
## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior

- Option 1. Restrict it to lowercase, let [filename] = [dialogDisplayName]
- Option 2. Do not restrict, decouple them, let [filename] = [dialogDisplayName].toLowercase()
  <img width="597" alt="image" src="https://user-images.githubusercontent.com/49866537/78625236-18001780-78be-11ea-9d7e-a1ed61ec0cbd.png">

## Screenshots

<img width="643" alt="image" src="https://user-images.githubusercontent.com/49866537/78624545-7926eb80-78bc-11ea-9c7f-1c57163837d9.png">

## Additional context

Since our bot file structure have changed to all lowercase path/filename, creation needs to be updated

**Comment by zhixzhan** [comment]
Hi @cwhitten do you have any suggestion?

**Comment by cwhitten** [comment]
Can we use the $designer.name field as the display name? Option 2

**Comment by cwhitten** [comment]
Actually @zhixzhan at the moment let's just accept whatever the user provides and write that as the file name, as long as it is an acceptable value (no special characters).

**Comment by boydc2014** [comment]
@cwhitten  today it's implemented this way, so no immediate action need for this. @zhixzhan  If we feels like we need to disable editable of dialog in form to avoid confusing, let's open a new issue.

**Comment by zhixzhan** [comment]
OK, sounds like we do not need do any change on dialog creation.
