### ISSUE TITLE
Didn't delete files in proj folder

### ISSUE THREAD

**Issue by ssss141414** [microsoft/BotFramework-Composer#2526]
## Describe the bug
I delete dialogs in composer, but files in my project folder remain.
Because creating and deleting files are frequent things. There will be many files leaving in my disk.
![image](https://user-images.githubusercontent.com/18118994/78627413-f3a73980-78c3-11ea-9a93-1a81e4f96ecf.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by boydc2014** [comment]
I think we resolved one issue like this before, looks like a regression, @lei9444  @liweitian  can you help check is there recent changes brought this?

**Comment by hibrenda** [comment]
Try to reproduce this and find only directory is left but all the files have already been deleted.
For the dialog delete action. only first time (eg. delete dialog 'abc'),  hit following error.
![image](https://user-images.githubusercontent.com/43408889/78675627-e9168f80-7917-11ea-8e5f-11441a58d24d.png) but no errors for the upcoming delete action.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2587
