### ISSUE TITLE
LG error message incorrect

### ISSUE THREAD

**Issue by ssss141414** [microsoft/BotFramework-Composer#2528]
## Describe the bug
For this lg text:
\# ShowName(Name)
\- The name is ${Name.x1}

I missed to set Name.x1, and lg error message is:
![image](https://user-images.githubusercontent.com/18118994/78627746-d6269f80-78c4-11ea-8ab5-46ca02cb7383.png)

The error message is incorrect. It should tell me 'Name don't have x1 property', but not 'not match scope'. It's confusing.

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by boydc2014** [comment]
This is a known issue in SDK, we will share updates here if we made any progress in SDK side.
