### ISSUE TITLE
Need to sort triggers

### ISSUE THREAD

**Issue by ssss141414** [microsoft/BotFramework-Composer#2529]
## Is your feature request related to a problem? Please describe.
![image](https://user-images.githubusercontent.com/18118994/78629038-80ec8d00-78c8-11ea-84ab-86d8cc1d2536.png)
Triggers are sorted by when they were added in. But Dialogs are sorted by alphabetic order.
Please sort triggers too, or provided a 'Move UP/DOWN' button, so that we can organize them by ourselves.

**Comment by luhan2017** [comment]
It can't be sorted by alphabet because the trigger ordering decides the priority of the trigger.
