### ISSUE TITLE
Expose bot port in Composer

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#2530]
## Describe the bug

In the skill doc, we have a step to use ngrok to configure the skillHostEndpoint, since our bot port is not restricted to 3979 any more. we need to have to way to let user know what is the port of the runing bot. 

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2676
