### ISSUE TITLE
can not see the error message in the User Input page.

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2531]
## Describe the bug
I can not see my error messages in the  User Input page.
![image](https://user-images.githubusercontent.com/44257569/78633503-64eee880-78d4-11ea-967f-0257e8612f5a.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by zhixzhan** [comment]
addressed via #2540
