### ISSUE TITLE
can not use a list entity without synonyms

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2532]
## Describe the bug
When I use list entity with synonyms, the bot works OK.
![image](https://user-images.githubusercontent.com/44257569/78634065-aaf87c00-78d5-11ea-981d-11e8696c1e2e.png)

But when I use a list entity without synonyms, the bot failed to start. I think a list entity without synonyms should be valid?
![image](https://user-images.githubusercontent.com/44257569/78634046-9d42f680-78d5-11ea-84ea-fd06c8c5f424.png)
![image](https://user-images.githubusercontent.com/44257569/78633937-5bb24b80-78d5-11ea-9452-d9b1f4c21353.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by boydc2014** [comment]
@feich-ms  can you check whether this feature is no longer supported in bf-cli?

**Comment by feich-ms** [comment]
@boydc2014, verified that luis build still support that format. But it will add a warning like: [WARN] line 4:0 - line 4:24: no synonyms list found for list entity definition: "$SlotAttributeName:room=". I think composer treat warning as error.

**Comment by zhixzhan** [comment]
I found the reason is publishing Luis did not filter diagnostics by Error. fixed in #2639
