### ISSUE TITLE
error when create a new dialog with luisRecognizer but without any utterences

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2534]
## Describe the bug
When I create a new dialog, and set recognizer as luis, and then restart the bot, it throws an empty .lu error.

![image](https://user-images.githubusercontent.com/44257569/78635213-44289200-78d8-11ea-85f1-bb064d2e6e60.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by boydc2014** [comment]
This behavior is as expected, @lei9444  can we investigate this to make this reported beforeahead in notification page.
