### ISSUE TITLE
SetProperty 'type' not work when setting default values

### ISSUE THREAD

**Issue by ssss141414** [microsoft/BotFramework-Composer#2535]
## Describe the bug
When I SetProperty and change type to int or number, 0 cannot be set.
![image](https://user-images.githubusercontent.com/18118994/78639451-940b5700-78e0-11ea-858a-da11647cf45f.png)
Maybe because default value cannot be set.

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2592
