### ISSUE TITLE
Delete properties doesn't work

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2536]
## Describe the bug

![image](https://user-images.githubusercontent.com/19773357/78639642-e6e50e80-78e0-11ea-9058-ec57fa4f26ee.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. add a Delete properties

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/2458

**Comment by KayMKM** [comment]
fixed in latest master build
