### ISSUE TITLE
support expression in body of http action

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2537]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when I can't use expression in body

## Describe the solution you'd like

Change to UI like options in begin dialog:
![image](https://user-images.githubusercontent.com/2876650/78644285-37ac3580-78e8-11ea-8ff8-f30ae2441d31.png)

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/1829

**Comment by cwhitten** [comment]
@xieofxie please give more information in your request. It is possible to use both variables and expressions in the body of an HTTP call today.

**Comment by KayMKM** [comment]
Calendar skill need add multiple attendee email in http request body like:
```
"attendees": [
    {
      "emailAddress": {
        "address": "${user.ResolvedAttendees[0]}"
      }
    }
  ]
```
Now we can only add fixed count of items in list, because the body should be a json format.

**Comment by cwhitten** [comment]
why can't you use a foreach node with setproperty inside of it to create your object and then assign it into the body?

**Comment by KayMKM** [comment]
Do you mean that I create a attendee list object, then add it in body like this?
```
"attendees": [
    ${dialog.attendeeList}
  ]
```
This is not a valid json, so will get an error.

**Comment by cwhitten** [comment]
Ah, I see. I think you would want
```
{
  "attendees": ${dialog.attendeeList}
}
```

**Comment by KayMKM** [comment]
Yes. That is what I want.

**Comment by cwhitten** [comment]
We'll look to make this possible in R9

**Comment by xieofxie** [comment]
@cwhitten At first look I thought I can't use string(expression) in the body, however after some investigation, I found the following works:
* Assume dialog.a is an object/array/string
This will serialize the content of a to data, thus object/array/string could be set dynamically
```
{
    "data":"=dialog.a"
}
```
* Assume dialog.a is an object
This will serialize the content of a to json, thus key-value pairs could be set dynamically
`"=dialog.a"`

@KayMKM will this solve your problem?

@hibrenda I may close this now. But this is different from #1829 as that one requires body could be other types instead of json

Thanks

**Comment by hibrenda** [comment]
@xieofxie thanks for the investigation. I just removed the link to issue 1829. And we also need to document or show this usage in sample as well @luhan2017 .
