### ISSUE TITLE
precheck for Value expression

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2543]
## Is your feature request related to a problem? Please describe.
When I set a property and set the value used an invalid expression, I got the error when I chat with the bot. 
![image](https://user-images.githubusercontent.com/44257569/78660408-97620b00-78ff-11ea-88e6-d0f9030fbb03.png)
![image](https://user-images.githubusercontent.com/44257569/78660437-a5179080-78ff-11ea-9777-894a671238b4.png)

## Describe the solution you'd like
Support a precheck for the expression when I type in so that I can fix the error before publish.

**Comment by hibrenda** [comment]
This requires the expression validation support.
