### ISSUE TITLE
Scrollbar is missing

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2544]
## Describe the bug

![image](https://user-images.githubusercontent.com/19773357/78661577-99c56480-7901-11ea-8b99-78e472fed2c5.png)
there should be a scroll bar

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2547
