### ISSUE TITLE
Full features of luis prediction

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2545]
## Is your feature request related to a problem? Please describe.
I used luis in composer, and deployed it into the portal.
I got the predict result from luis portal with all intents and instance data:
`“{"query":"find a confroom","prediction":{"topIntent":"FindMeetingRoom","intents":{"FindMeetingRoom":{"score":0.430218428},"None":{"score":0.09387313},"CreateMeeting":{"score":0.0279416535},"AcceptMeeting":{"score":0.00673450669},"ShowNextMeeting":{"score":0.00178787776}},"entities":{"SlotAttributeName":[["room"]],"$instance":{"SlotAttributeName":[{"type":"SlotAttributeName","text":"confroom","startIndex":7,"length":8,"modelTypeId":5,"modelType":"List Entity Extractor","recognitionSources":["model"]}]}}}}”`

But the composer just get a simple predict result:
![image](https://user-images.githubusercontent.com/44257569/78672917-eade5400-7913-11ea-9ca8-a2b0316685af.png)

## Describe the solution you'd like
Provide a way to set the predict options so that we can get more predict result if we need.
https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.AI.LUIS/V3/LuisPredictionOptions.cs

**Comment by luhan2017** [comment]
I checked the LuisRecognizer schema.

```
"predictionOptions": {
            "type": "object",
            "properties": {
                "includeAllIntents": {
                    "type": "boolean",
                    "title": "Include all intents",
                    "description": "True for all intents, false for only top intent."
                },
                "includeInstanceData": {
                    "type": "boolean",
                    "title": "Include $instance",
                    "description": "True to include $instance metadata in the LUIS response."
                },
                "log": {
                    "type": "boolean",
                    "title": "Log utterances",
                    "description": "True to log utterances on LUIS service."
                },
                "preferExternalEntities": {
                    "type": "boolean",
                    "title": "Prefer External Entities",
                    "description": "True to prefer external entities to those generated by LUIS models."
                },
                "slot": {
                    "type": "string",
                    "title": "Slot",
                    "description": "Slot to use for talking to LUIS service like production or staging."
                },
                "version": {
                    "type": "string",
                    "title": "Version",
                    "description": "LUIS application version to use."
                }
            }
```

Out solution to this could be:

let the lubuild to generate a default configure file like this:
```
{
      predictionOptions: {
             "includeAllIntents" : "=settings.luis.preditionOptions.includeAllIntents",
             "includeInstanceData": "=settings.luis.preditionOptions.includeInstanceData" 
      }
}
```

And user can set those configurations in the settings page, and this configuration is applied to all the luisRecognizers in the bot. 

Besides this, we may need to create another two items for externalEntityRecognizer and dynamicLists. 

@boydc2014 , @vishwacsena , thoughts?

**Comment by vishwacsena** [comment]
What's the use case for full prediction results? @luhan2017 @xhr0804

**Comment by xhr0804** [comment]
As the above example, SlotAttributeName is a list entity, "room" is a list entity name and "confroom" is a synonym
```
$SlotAttributeName:room=
- meeting room
- conference room
- confroom
```
When I ask "find a confroom", the result entity is just a SlotAttributeName "room", but I want to get the text "confroom" which is in the $instance. 
For the list entity, if we want to get the original text in the utterance, we all need to open the "includeInstanceData" options. @vishwacsena

**Comment by vishwacsena** [comment]
@xhr0804 thanks for the clarification. @luhan2017 it makes sense to configure the required properties via `predictionOptions` in setting. @feich-ms for the luis:build side change to write out the additional properties with the LUIS recognizer configuration. We probably should probably write it out like this to cover cases where the setting is not explicitly specified. Right? 

```json
{
      predictionOptions: {
             "includeAllIntents" : "=coalesce(settings.luis.preditionOptions.includeAllIntents, false)",
             "includeInstanceData": "=coalesce(settings.luis.preditionOptions.includeInstanceData, false)" 
      }
}
```

**Comment by feich-ms** [comment]
fix here https://github.com/microsoft/botframework-cli/pull/709
