### ISSUE TITLE
need the botid path for the dialog referenced in "Defined in" in lu all up

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2546]
- click "Defined in" to navigate to the corresponding dialog in lu all up 
![image](https://user-images.githubusercontent.com/43408889/78677385-44498180-791a-11ea-8955-da10313987fd.png)
- hit following error
![image](https://user-images.githubusercontent.com/43408889/78677511-69d68b00-791a-11ea-9984-708d4073884c.png)
- This is due to no botid url attached 
![image](https://user-images.githubusercontent.com/43408889/78677583-7d81f180-791a-11ea-8a20-3e4af074cb88.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2561
