### ISSUE TITLE
LG ChannelData return BadRequest on facebook

### ISSUE THREAD

**Issue by InnoraG** [microsoft/BotFramework-Composer#2549]
## Describe the bug

Below LG template return badrequest when tried on facebook channel
But is fine on emulator, showing This text is showing well on emulator

!# bfdactivity-731979()
[Activity
Text = This text is showing well on emulator
ChannelData = {"text":"This text should not be generating BadRequest on facebook channel"}
] 

## Version

4.7.0-preview-191208-1

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create Send a response component with below activity
[Activity
Text = Text showing on emulator
ChannelData = {"text":"This text should not be generating BadRequest on facebook channel"}
] 
2. Restart and Run bot
2. Test from facebook channel
3. Get BadRequest

## Expected behavior

Should show This text should not be generating BadRequest on facebook channel on Facebook in messenger chat box

## Screenshots

Correct on Emulator :
![image](https://user-images.githubusercontent.com/6458346/78702808-d6995780-7911-11ea-929e-533b345512fb.png)  

BadRequest on Facebook channel :
![image](https://user-images.githubusercontent.com/6458346/78701595-f760ad80-790f-11ea-8f2d-60b98c592e17.png)

**Comment by Danieladu** [comment]
May you try modify the ChannelData into object? Because `{"text":"This text should not be generating BadRequest on facebook channel"}` it self is just a plain text.

e.g. change it to
```
ChannelData = ${json('{"text":"This text should not be generating BadRequest on facebook channel"}'}
```

**Comment by InnoraG** [comment]
Big Thanks @Danieladu  , it works
Even happier on the great product

**Comment by Danieladu** [comment]
> Big Thanks @Danieladu , it works
> Even happier on the great product
> 
> Last : any way to specify different ChannelData for different channel using LG ?

I am not sure whether the below sample is what you find
```

# activity(channel)
[Activity 
        text=your text
        ChannelData=${if (channel == 'facebook', json(facebookchannelData()), '' )}
]


# facebookchannelData
-```{
    "attachment":{
      "type":"template",
      "payload":{
        "template_type":"button",
        "text":"What do you want to do next?",
        "buttons":[
          {
            "type":"web_url",
            "url":"https://www.messenger.com",
            "title":"Visit Messenger"
          }
        ]
      }
    }
}```

```

Or if you have many channels
```
# activity(channel)
[Activity 
        text=your text
        ChannelData=${GetChannelData(channel)}
]

# GetChannelData(channel)
- IF:${channel == 'facebook'}
- ${json(facebookChannelData())}
- ELSEIF: ${channel == 'line'}
- ${lineChannelData()}
- ELSE: 
- ${json(fromFile('./defaultchannelDate.txt'))}

# facebookchannelData
-```{
        xxx
    }```

# lineChannelData
[lineChannelData
  text = mytext
  xxx = yyy
]
```

**Comment by InnoraG** [comment]
> > Big Thanks @Danieladu , it works
> > Even happier on the great product
> > Last : any way to specify different ChannelData for different channel using LG ?
> 
> I am not sure whether the below sample is what you want
> 
> ```
> 
> # activity(channel)
> [Activity 
>         text=your text
>         ChannelData=${if (channel == 'facebook', json(facebookchannelData()), '' )}
> ]
> 
> 
> # facebookchannelData
> -```{
>     "attachment":{
>       "type":"template",
>       "payload":{
>         "template_type":"button",
>         "text":"What do you want to do next?",
>         "buttons":[
>           {
>             "type":"web_url",
>             "url":"https://www.messenger.com",
>             "title":"Visit Messenger"
>           }
>         ]
>       }
>     }
> }```
> ```
> 
> Or if you have many channels
> 
> ```
> # activity(channel)
> [Activity 
>         text=your text
>         ChannelData=${GetChannelData(channel)}
> ]
> 
> # GetChannelData(channel)
> - IF:${channel == 'facebook'}
> - ${json(facebookChannelData())}
> - ELSEIF: ${channel == 'line'}
> - ${lineChannelData()}
> - ELSE: 
> - ${json(fromFile('./defaultchannelDate.txt'))}
> 
> # facebookchannelData
> -```{
>         xxx
>     }```
> 
> # lineChannelData
> [lineChannelData
>   text = mytext
>   xxx = yyy
> ]
> ```
> 
> Maybe you can get the channel from the received `activity.chanelId`?

Exactly @Danieladu  
It is so powerful...
Thanks again
