### ISSUE TITLE
Bring other SDK features in Composer

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#2560]
This issue is to track what are the SDK actions/inputs/conditions/recognizers are not yet enabled in Composer.

#Actions 
- [ ] ContinueConversationLater
- [ ] GotoAction
- [ ] DebugBreak
- [ ] CodeAction
- [ ] EditActions
- [x] GetActivityMembers
- [x] GetConversationMembers
- [x] ThrowException

#EntityRecognizers 
- [ ] ChannelMentionEntityRecognizer
- [ ] ConfirmationEntityRecognizer
- [ ] CurrencyEntityRecognizer
- [ ] DateTimeEntityRecognizer
- [ ] DimensionEntityRecognizer
- [ ] EmailEntityRecognizer
- [ ] GuidEntityRecognizer
- [ ] HashtagEntityRecognizer
- [ ] IpEntityRecognizer
- [ ] MentionEntityRecognizer
- [ ] NumberEntityRecognizer
- [ ] NumberRangeEntityRecognizer
- [ ] OrdinalEntityRecognizer
- [ ] PhoneNumberEntityRecognizer
- [ ] RegexEntityRecognizer
- [ ] TemperatureEntityRecognizer
- [ ] TextEntityRecognizer
- [ ] UrlEntityRecognizer

#OthersRecognizers 
- [ ] OnContinueConversation
- [ ] OnInstallationUpdateActivity

#TeamsChannelRelated
- [ ] Teams.OnAppBasedLinkQuery
- [ ] Teams.OnCardAction
- [ ] Teams.OnChannelCreated
- [ ] Teams.OnChannelDeleted
- [ ] Teams.OnChannelRenamed
- [ ] Teams.OnFileConsent
- [ ] Teams.OnMessagingExtensionCardButtonClicked
- [ ] Teams.OnMessagingExtensionConfigurationQuerySettingUrl
- [ ] Teams.OnMessagingExtensionConfigurationSetting
- [ ] Teams.OnMessagingExtensionFetchTask
- [ ] Teams.OnMessagingExtensionQuery
- [ ] Teams.OnMessagingExtensionSelectItem
- [ ] Teams.OnMessagingExtensionSubmitAction
- [ ] Teams.OnO365ConnectorCardAction
- [ ] Teams.OnTaskModuleFetch
- [ ] Teams.OnTaskModuleSubmit
- [ ] Teams.OnTeamRenamed

**Comment by yeze322** [comment]
After several iterations, it would be much easier to support all those SDK kinds.

@yeze322 I can help on Visual Editor;
updating sdk.schema will automatically enable them in Form Editor.

One more thing is we need to group the popup menu, refs #2578 . If possible, we need a search box as well.

**Comment by garypretty** [comment]
@EricDahlvang will be adding to the list of available Teams actions / triggers in the next release.  Once we have a clear picture of the list which will need to be surfaced inside of Composer we will raise an associated issue and link it to this issue for tracking.

**Comment by raviraushanweb** [comment]
Hey, Why am I not seeing _ ContinueConversation_ _ ContinueConversationLater_ and _ GotoAction_ in composer v2.1.1 and v2.1.2? 

I saw these options available in v2.1.2 in a youtube video. Here is a screenshot from that video: [GoToAction](https://youtu.be/3EO8-uLgieY?t=15)
<img width="1046" alt="Screenshot 2022-08-29 at 9 02 12 AM" src="https://user-images.githubusercontent.com/41154960/187117810-75bd3700-772d-49e9-bdca-07a91690fa31.png">
