### ISSUE TITLE
Value will be cleared in Headers with only one backspace hit

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2562]
## Describe the bug

I just hit backspace only once:
![cnhbNK3xu2](https://user-images.githubusercontent.com/2876650/78760595-fa14de80-79b3-11ea-955b-7fd159729424.gif)
It happens when this is edited at first time(e.g. after refresh)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by a-b-r-o-w-n** [comment]
related to #2566

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2592
