### ISSUE TITLE
Manage schema and sample through runtime plugin

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#2563]
## Is your feature request related to a problem? Please describe.

We decoupled runtime code from Composer core with the plugin architecture, that leaves us the questions of how should we manage schemas files for bot. 

Do we attach that at the beginning of creation bot or do we leave it later when ejecting the runtime?

## Describe the solution you'd like
Given schema is more close to runtime, and attaching schema at very beginning don't really support user to do customization without code ejected there. So it make sense to put them together when ejecting the bot. 

Then it also make sense to let the runtime plugin to provide schema since it manage the code, so we need a way to let runtime plugin to provide the schema. 

The design is 
1. Put a "version" field in bot settings
2. Plugin system allow the extension to register a lookup method to look up schema based on version
3. Server will call this method and get the schema and merged the schema found in bot folder and sent to client. 

the version can be just "latest" or "lastest_csharp"  before we version it very precisely. 

### Samples
A sample may not have to bind into one specific runtime version, so it make sense to support adding sample for multiple versions. 

For example, i would vision a sample extension API like this. 

```js
Composer.AddSample(sample: SampleDef)

Interface SampleDef
{
  id: string
  description: string
  path: string
  type: basic | advanced
  tags: []
  runtimes: string[]   // a list of versions of runtime this sample supports
}

```

**Comment by benbrown** [comment]
What would the `runtimes` field be holding?
