### ISSUE TITLE
Flickering issue of LG editor 'loading' indicator

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2564]
## Describe the bug
![i0408-lg-editor-loading](https://user-images.githubusercontent.com/8528761/78776571-a3ff6580-79ca-11ea-885a-c1895235b2f6.gif)

AFAK, there is a synced version implementation of the `getLgTemplates` API, there should be no 'loading' when user opening an activity node. Consider removing the 'loading' text.

## Version
Preview 2.0

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by a-b-r-o-w-n** [comment]
Hey @yeze322 This is due to the editor component remounting. I'm not sure we can do much about this as the behavior exists inside of the library.

**Comment by yeze322** [comment]
@zhixzhan do you know about the 'Loading' text in LGEditor?

**Comment by zhixzhan** [comment]
@yeze322 seems to be a Monaco Editor default behavior, I looked up the document/issue page, not found any clue.

**Comment by yeze322** [comment]
Thanks @zhixzhan ! If we can't solve it, feel free to close it
