### ISSUE TITLE
Http request header disappeared when I click other item

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2566]
## Describe the bug

I have a header in the http request, and I want to change it. But after I change it, click another form and then click back, the header disappeared
![headerbug](https://user-images.githubusercontent.com/44257569/78788413-5c82d480-79de-11ea-8f40-344ad84ea3a8.gif)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2592
