### ISSUE TITLE
Touch up visuals on Settings page

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#2573]
Super quick turnaround on the Settings page!
It could use a little bit of text and or visual love to make the settings a bit more clear.

**Comment by DesignPolice** [comment]
Is the Settings page in your Lotsofthings file or in Master Composer? @mareekuh

**Comment by mareekuh** [comment]
We need to create a new Settings page that has:
- Multilang (in Master)
- LG settings  (@a-b-r-o-w-n  can send you as screenshot of his update to Settings for this)
- authoring keys - add a UI version vs just editor (JSON) version
- Onboarding on/off

**Comment by mareekuh** [comment]
Draft Setting pages design is here: https://www.figma.com/file/HLtKaKHctLldivPnzQ7BqQOI/Composer-MI-lotsotings?node-id=3505%3A8449

@a-b-r-o-w-n  would you mind sending @DesignPolice a screenshot of the Build with the LG editor settings in it so we can include this in the design?

**Comment by a-b-r-o-w-n** [comment]
@mareekuh done.

**Comment by DesignPolice** [comment]
@a-b-r-o-w-n didn't get it. Can you just post here or email to Bostian@allovus.com

**Comment by a-b-r-o-w-n** [comment]
![image](https://user-images.githubusercontent.com/3619060/79366330-da743d80-7f00-11ea-894e-84351a7396d2.png)

**Comment by mareekuh** [comment]
@a-b-r-o-w-n  and @cwhitten 
Settings design (with visual pass) is ready available here:
https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=1514%3A1499

still working on adding the 'Runtime settings' section but the page template and all other content is ready to go.

**Comment by mareekuh** [comment]
@DesignPolice please update this git when runtime UI has been included (-:

**Comment by DesignPolice** [comment]
Will do, hoping to drop those in today -

**Comment by DesignPolice** [comment]
This has been updated with the Custom Runtime UI - ping if you have questions. 

https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=1514%3A656

**Comment by DesignPolice** [comment]
Here are a few screen grabs.

![Screen Shot 2020-04-22 at 4 36 18 PM](https://user-images.githubusercontent.com/45223620/80043810-901e2e00-84b7-11ea-905c-cfd8df06fe05.png)

![Screen Shot 2020-04-22 at 4 36 46 PM](https://user-images.githubusercontent.com/45223620/80043808-8f859780-84b7-11ea-8283-9f8b41ff2f2b.png)

![Screen Shot 2020-04-22 at 4 37 01 PM](https://user-images.githubusercontent.com/45223620/80043803-8dbbd400-84b7-11ea-84df-0f813f257e49.png)

**Comment by DesignPolice** [comment]
Here are the SVG files for the icons... they are on a pixel grid so should be as clear as possible.


[IconsZip.zip](https://github.com/microsoft/BotFramework-Composer/files/4524230/IconsZip.zip)

**Comment by mareekuh** [comment]
@a-b-r-o-w-n  and @DesignPolice   is this closed or is this done in the build?

**Comment by a-b-r-o-w-n** [comment]
This has not been worked on. I have been focused on issues with the R9 label so this hasn't been on my radar.
