### ISSUE TITLE
delete menu for triggers, dialogs disappears

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2574]
## Describe the bug

In the current master, the resizing is very cool. However, the delete menu disappears:
![image](https://user-images.githubusercontent.com/2876650/78853028-7826c300-7a50-11ea-903b-14beae63fa28.png)

Previous:
![img](https://user-images.githubusercontent.com/1156704/73790292-15196700-4755-11ea-9296-67f9eeb83ea2.png)

## Version

aca735819a63caed7bfcdf6ce1ebba3611d00c1b

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2582
