### ISSUE TITLE
scroll bar works incorrectly and disappears

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2575]
## Describe the bug

Should not show in this case:
![image](https://user-images.githubusercontent.com/2876650/78853355-43ffd200-7a51-11ea-9332-8bda682b20d9.png)
Should show in this case (there are interruption etc. at the bottom):
![image](https://user-images.githubusercontent.com/2876650/78853388-58dc6580-7a51-11ea-872e-ee7cdb6360d3.png)

## Version

aca735819a63caed7bfcdf6ce1ebba3611d00c1b

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2592
