### ISSUE TITLE
Expected responses is not kept when cut-paste for text input

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2576]
## Describe the bug

1 create a text input with Expected responses
2 cut paste it
3 Expected responses is gone

## Version

aca735819a63caed7bfcdf6ce1ebba3611d00c1b

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by hibrenda** [comment]
same issue to https://github.com/microsoft/BotFramework-Composer/issues/2273

**Comment by cwhitten** [comment]
Brenda let's not overcount work items please. Remove R9 label

**Comment by yeze322** [comment]
@xieofxie did you mean LU resources not copied?

**Comment by xieofxie** [comment]
> @xieofxie did you mean LU resources not copied?

Yes, the utterances in Expected responses are not kept in lu file

**Comment by yeze322** [comment]
@xieofxie I got it. LU copy is not supported yet, you can track it via #2237 as Brenda posted

**Comment by yeze322** [comment]
duplicated with https://github.com/microsoft/BotFramework-Composer/issues/2273
