### ISSUE TITLE
use special UI for disabled nodes

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2577]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when I can't know whether some nodes are disabled or not

## Describe the solution you'd like

Gray-out the nodes that are disabled by **boolean false**
Or line through like 
![image](https://user-images.githubusercontent.com/2876650/78854204-4b27df80-7a53-11ea-99b9-d4ccc5aa7f1e.png)

**Comment by hibrenda** [comment]
This will be supported in R10 with nodes color updates . https://github.com/microsoft/BotFramework-Composer/issues/2286
