### ISSUE TITLE
Need to support custom schema e2e

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2578]
Scenarios listed as below.
User has a customized action eg. MSGraph. user would like to enable it in composer.
-[] Flyout format

**Comment by yeze322** [comment]
The content of flyout menu could come from schema file
![image](https://user-images.githubusercontent.com/8528761/78976759-6ecd5180-7b49-11ea-84a7-5ec74cbebf29.png)

**Comment by mareekuh** [comment]
I was initially thinking of tucking it into a 'custom' menu, but seeing it this way, I think adding it as an extra item is not only most discoverable but also works for any type of extension.
Could we allow people to add it to the group they believe their schema extends, such as if Speech Commands the author might want to group it in with 'Ask a question' .

**Comment by yeze322** [comment]
> I was initially thinking of tucking it into a 'custom' menu, but seeing it this way, I think adding it as an extra item is not only most discoverable but also works for any type of extension.
> Could we allow people to add it to the group they believe their schema extends, such as if Speech Commands the author might want to group it in with 'Ask a question' .

Hi Marieke, I think we can provide two ways of customization:
1. By default, if user only drops a schema file 'myspeech.schema', we just put it under the 'custom' menu (maybe 'custom' -> 'myspeech' -> 'Speech.Command') 
2. Advancedly, if user wants to merge extra commands to built-in menu, user can then customize an extra menu schema.
What's your opinion?

**Comment by sangwoohaan** [comment]
I think Ze's idea works. Since this is a temporary solution until we have a more schema-driven way of adding custom schemas in R10, putting custom schemas under the 'custom' menu sounds fair to me with the ability for advanced users to customize that.

**Comment by mareekuh** [comment]
Especially if temporary, I still think adding it as a menu item vs tucking under custom is fine with the option to add to any of the other menus if the author chooses to do so. Given we’re open source, giving those that build on our system some prime(ish) real estate seems right and more encouraging to invest and share/improve our product is worth it IMO

Regards,
Marieke
________________________________

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/2757
so both runtime location and customized schema location will be in customized path specified in bot setting page?

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/2760

**Comment by cwhitten** [comment]
@hibrenda I don't understand your recent comments. Let's be crisp here before we cut tickets and assign them to R9.

@yeze322 @mareekuh @sangwoohaan We should have a default Custom Actions fly-out item that everything will show up in. This is the least amount of effort on the developers to configure their schema. What's not represented here is this user effort to achieve Ze's suggestion, and it adds friction.

I do like the idea of allowing the user to more granularly configure the fly-out, however I see that as a P1. Happy to discuss further.

@yeze322 my recommendation for the technical solution is to default to a "Custom Actions" fly-out that everything falls into with a line of sight to extend this into your suggestion.

**Comment by cwhitten** [comment]
By the way, the schema work should happen in this ticket: https://github.com/microsoft/BotFramework-Composer/issues/2563 cc @boydc2014 

The work associated with this ticket is only the solution to add custom actions into the flyouts

**Comment by yeze322** [comment]
@a-b-r-o-w-n here is the thread about action fly-out menu

**Comment by yeze322** [comment]
#2806

**Comment by yeze322** [comment]
Plan
> Hi Brenda - the custom schema stuff should land in R9, at least the pieces I’m thinking. I thought Dong was going to make sure the schemas get included when the runtime is ejected, and that the app will  respect the schema with the runtime.
Zeye needs to deliver the mechanism for custom actions to show up in the action flyouts in a new “catch all” for custom actions

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2806
