### ISSUE TITLE
LG editing issue

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2580]
## Describe the bug
The lg template will be deleted when add '[' in other template
And this bug destroyed many lg templates of my bot...

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. add a response 'a'
2. add a response 'b'
3. add a '[' before 'a' 
![image](https://user-images.githubusercontent.com/19773357/78880540-24d06700-7a88-11ea-8b26-f542a62b801b.png)

**Comment by zhixzhan** [comment]
Another corner case same to https://github.com/microsoft/BotFramework-Composer/issues/2398
I know @Danieladu LG team is working on a parser refactor, hope can totally resolve this type issue.

**Comment by hibrenda** [comment]
As this will be fixed in LG in R9. so composer will adopt the updates in R9 as well.
