### ISSUE TITLE
Form Editor overflow scroll

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2584]
## Describe the bug
There is no scroll bar when content is overflowed
![image](https://user-images.githubusercontent.com/8528761/78894101-13468980-7a9f-11ea-81b2-1ae211fd0f3e.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by a-b-r-o-w-n** [comment]
duplicate of #2575
