### ISSUE TITLE
Provide ‘Reveal in explorer’ functionality to quick access bot project's source folder 

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2585]
## Is your feature request related to a problem? Please describe.
After the init creation flow, it will be quite unstraightforward to know where my bot is.
As a user
- I want to share my bot to cooperators
- I want to use plain text editor to edit my bot project

## Describe the solution you'd like
1. Provide functionality similar to 'Reveal in explorer', system file explorer will be opened after clicking on the context menu
2. Alternatively, users can copy the absolute resource path to the bot project folder (system dependent)
![reaveal-in-exp](https://user-images.githubusercontent.com/8528761/78974504-b7364080-7b44-11ea-9010-861619984a10.gif)

**Comment by a-b-r-o-w-n** [comment]
This is a cool feature, but will need to be implemented with the storage plugin in mind. Not all "files" will live on a local disk.

Something that we can consider is allowing plugins to provide contextual menu items like VS Code, but that is a way bigger task.

**Comment by yeze322** [comment]
@a-b-r-o-w-n I'm not sure if it's a common requirement.
As a Composer user, I asked this feature because I want to share my bot to other cooperators, however, the storage position of a bot is not obvious enough to be found.

A resource link would help, or I heard there will be a 'export to ZIP' feature, it will help as well
