### ISSUE TITLE
File and Folder selection UX is wonky

### ISSUE THREAD

**Issue by corinagum** [microsoft/BotFramework-Composer#2594]
![image](https://user-images.githubusercontent.com/14900841/78947101-54c43e00-7a79-11ea-843a-bc2aff9aca5d.png)

## Describe the bug

When selecting the bot to open, currently the required behavior is to double click on the bot name. However, an intuitive UX would also have a 'Next' button at the bottom of the dialog to continue with the highlighted bot.

## Version
https://github.com/microsoft/BotFramework-Composer/commit/4f0790af43b49c4ed433f0c4823c6af48c38d5f6

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Composer home page
2. Click the 'Open' button
3. Select (single click) a previously chosen bot (e.g. EchoBot-0)
4. User must double click the selected bot in order to select it, whereas some users might want to click a 'Next' or 'Open' button
5. Note that 'Enter' when highlighting the bot name does work.

## Expected behavior
When selecting a bot to open, the user should have multiple experiences for opening the bot. 

The user should have a 'Next' or 'Open' button at the bottom of the dialog in order to select that bot.

## Screenshots
See above

## Additional context

@sangwoohaan @DesignPolice 
@beyackle and I discussed this casually, but could you guys weigh in?

**Comment by beyackle** [comment]
Issue #2635 and its fix (PR#2645) are related to this one, where the icon at the head of the Notification  row becomes a single-click way to activate it (double-clicking the whole row still works). I could add that behavior to this Open dialog as well as the Recent Bots list on the home page if that's something we decide should be done.
