### ISSUE TITLE
LG syntax incompatible change

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#2596]
## Describe the bug

LG team recently  changed the naming policy. https://github.com/microsoft/botbuilder-dotnet/pull/3712
- Remove dash in identifier (template name)

It's an incompatible change, and previous LG file must change their template name, probably use _ instead.

e.g,  replace dash  `-` to underline `_`
```
bfdactivity-76HgfJ 
-> 
bfdactivity_76HgfJ
```

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by zhixzhan** [comment]
We can upgrade all sample bot, and composer generate LG template pattern. One migration solution is before we switch to new lg parser (which would failed to parse), do replacement at current lg  parser ( which both support dash - & underline  _  ).

**Comment by boydc2014** [comment]
@zhixzhan  your 3 work items are right. But i'm not sure about about the "migration solution" you mentioned, can we do a regex replace and match on every dialog and lg file, when loading bot will that work?

**Comment by zhixzhan** [comment]
@boydc2014 Sure, regex replacement seems more reliable compared to use parser do update.
