### ISSUE TITLE
Card Action button  is not working with hero card in facebook messenger

### ISSUE THREAD

**Issue by swaraj27** [microsoft/BotFramework-Composer#2599]
Bot info
- SDK Platform: .NET
- SDK Version: 3.0.10.
- Active Channels: WebChat,  Facebook
- Deployment Environment: Azure App Service

Issue Description
 - I created a  HeroCard. It have a button (CardAction) to select the item. If the user clicks on the button (the button title should be "click me"), I expect the user to see the response of "click me" intent. After clicking on button in messenger it gives error like "Object Serialized to String. JObject instance expected". 
- In the emulator it works perfectly. but in messenger it is not getting value, it is getting title as text
and giving the above mentioned   error.

Code Example
```
# HeroCard
[HeroCard
  title = Lets Begin
  subtitle = Microsoft Bot Framework
  text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack,   Office 365 mail and other popular services.
  image = https://greatsmilesbirmingham.com/wp-content/uploads/2017/09/canstockphoto30606317.jpg
  buttons = @{cardActionTemplate( 'imBack',  'click me', 'click me intent' )}
]
# cardActionTemplate( type,  title, value)
[CardAction
    Types = @{if(type == null, 'imBack', type)}
    Title = @{title}
    Value = @{value}
    Text = @{value}
]  
```

**Comment by luhan2017** [comment]
@boydc2014 , so is there any action need to take in the Composer run time part? or do we need to add more samples/docs on this?

**Comment by boydc2014** [comment]
> @boydc2014 , so is there any action need to take in the Composer run time part? or do we need to add more samples/docs on this?

The work is verify our cardSamples in latest Composer, works E2E in facebook, if not, identify and fix the gap, at least one known issue is the locale, there probably be others as well.

**Comment by zidaneymar** [comment]
> > @boydc2014 , so is there any action need to take in the Composer run time part? or do we need to add more samples/docs on this?
> 
> The work is verify our cardSamples in latest Composer, works E2E in facebook, if not, identify and fix the gap, at least one known issue is the locale, there probably be others as well.

@boydc2014 the lg test account on facebook meets some security issues and has been banned by facebook, I will test the cardsample once the account recovers.

**Comment by InnoraG** [comment]
1-Can see it works fine using native as per below :

- on emulator debug/inspect : 

![image](https://user-images.githubusercontent.com/6458346/79077831-c7008100-7d0c-11ea-9c20-f12e8c29ae34.png)

- which reflect on facebook as (LG Prompt used : - You said text ${turn.activity.text} or value ${turn.activity.value} So which card would you like to display? ) : 

![image](https://user-images.githubusercontent.com/6458346/79077824-c10aa000-7d0c-11ea-9641-b873680cf698.png)


2-Or through ChannelData as explained with good sample here https://github.com/microsoft/BotFramework-Composer/issues/2549

**Comment by cwhitten** [comment]
@zidaneymar have you been able to do any additional investigation?

**Comment by zidaneymar** [comment]
Could not repro on latest composer build.
![image](https://user-images.githubusercontent.com/9328933/82998576-7f268680-a03a-11ea-8ea0-03830357bc6f.png)

**Comment by zidaneymar** [comment]
@swaraj27  Hi Swaraj, I will close this issue since the issue could not be reproduced, If you have any questions please reopen this issue and provide more details.
