### ISSUE TITLE
Publish script returns wrong path for LocalPublish

### ISSUE THREAD

**Issue by kenakamu** [microsoft/BotFramework-Composer#2602]
## Describe the bug

using aca7358 electron
https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/packages/client/src/pages/setting/deployment/deployWizardStep-createDeploy.js

it returns incorrect path as "cd D:/a/1/s/Composer/plugins/localPublish/hostedBots/38730.13125826321". It should be bot composer installed path.

## Version
using aca7358 electron version

## Browser
electron

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Run electron app
2. Create bot
3. Go to publish and create publish script

## Expected behavior
Path should return <composer install path>\plugins\localpublish....

**Comment by cwhitten** [comment]
Addressed in 1.0
