### ISSUE TITLE
missing builtin functions

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2605]
## Describe the bug

Some builtin functions are not recognized like [isBoolean](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/common-expression-language/prebuilt-functions.md#isBoolean)

![image](https://user-images.githubusercontent.com/2876650/78981486-97a61480-7b52-11ea-8c9b-fd5e44c674cc.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by hibrenda** [comment]
Discussed with LG team, this verification has already been supported but composer does not get the latest package.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2607
