### ISSUE TITLE
Ability to show all the properties in set properties form

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2606]
## Is your feature request related to a problem? Please describe.
Could a "+" button be added besides the "2 more", so that user can click the button and see the remaining propertis
![image](https://user-images.githubusercontent.com/44257569/78983157-3c762100-7b56-11ea-8dfa-d735861bd7cc.png)

**Comment by yeze322** [comment]
unassigned myself until design is ready

**Comment by yeze322** [comment]
@sangwoohaan I tend to no change the height of the node block, alternatively, we provide a scroll bar
