### ISSUE TITLE
Unable to delete a dialog

### ISSUE THREAD

**Issue by EPinci** [microsoft/BotFramework-Composer#2609]
## Describe the bug

After a dialog has been created in a project, there's no way to delete it.

## Version

aca7358

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

In the application installed.

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a project
2. Add a dialog to project
3. Try to delete it

## Expected behavior

Have the ability of deleting a dialog.

**Comment by cwhitten** [comment]
Hi @EPinci this should be addressed in the `master` branch https://github.com/microsoft/BotFramework-Composer/pull/2587
