### ISSUE TITLE
Add down-sampling before publishing Lu files 

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#2610]
## Is your feature request related to a problem? Please describe.

1. If the number of intent's utterances more than 10(can be customized) times the least number of the intent's utterances, do a re-sampling process to keep the proportion;

2. If detect > 15000 utterances, downsize the utterances.

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2629
