### ISSUE TITLE
Save as project failed in e2e test

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#2611]
## Describe the bug
![image](https://user-images.githubusercontent.com/39758135/78990342-ccbd6180-7b68-11ea-94e8-da048bcfecc4.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2601
