### ISSUE TITLE
Why no AddBotApplicationInsights?

### ISSUE THREAD

**Issue by kenakamu** [microsoft/BotFramework-Composer#2617]
Just out of curiosity, is there any reason why we don't use AddBotApplicationInsights?

**Comment by cwhitten** [comment]
hi @kenakamu. As you may know, the runtime is intended to be a template that in some scenarios will need to be customized. However we're looking at adjusting the template leading up to our GA release. Adding @garypretty in for comment as he has been doing some investigation into the analytics modules available in Adaptive Dialogs.

**Comment by kenakamu** [comment]
Thanks a lot. The question comes from the fact we provision Application Insight resource, but it goes nowhere. I also want to set the telemetry key to bot registration channel and app service by using the script.

**Comment by garypretty** [comment]
@kenakamu Yes, we are planning to make some updates to Composer as part of the next release to ensure Telemetry is wired up correctly. I will update this issue once the changes are in PR.  The changes will require the 4.10 release of the SDK once that has been released.

**Comment by garypretty** [comment]
We are now tracking the changes for this in #2697.  This change is under development and should make the next release. Thanks for reporting @kenakamu .
