### ISSUE TITLE
prebuilt-function subtractFromTime not work

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2619]
## Describe the bug
When I used the sample "subtractFromTime('2018-01-02T00:00:00Z', 1, 'Day')" described [here](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/common-expression-language/prebuilt-functions.md#subtractFromTime,) it caused an error.
![image](https://user-images.githubusercontent.com/44257569/79067804-a1677d80-7cf4-11ea-9ba3-455c5939b2fb.png)

## Version

"9027223cc6b57ebd23f3c85"
## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cosmicshuai** [comment]
Try to use '2018-01-02T00:00:00.000Z' as input.

**Comment by boydc2014** [comment]
@cosmicshuai  the doc seems to be wrong 

![image](https://user-images.githubusercontent.com/3829387/79097523-906d4980-7d92-11ea-990d-00211ddaede4.png)


i'm closing this, please update the doc
