### ISSUE TITLE
unnecessarily fetch project at every route change

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#2620]
## Describe the bug

Everytime click on left navigation (route change), composer will fetch project again.

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Screenshots
![Untitled2](https://user-images.githubusercontent.com/49866537/79087415-c0f0bb80-7d71-11ea-9d2a-ce8bdc5eb184.gif)

**Comment by zhixzhan** [comment]
Not sure which PR imported this bug.

**Comment by a-b-r-o-w-n** [comment]
@cwhitten I think this has already been done. I will confirm today.

**Comment by a-b-r-o-w-n** [comment]
This has already been addressed in #2842
