### ISSUE TITLE
Print HTTPrequest response

### ISSUE THREAD

**Issue by ssss141414** [microsoft/BotFramework-Composer#2624]
## Describe the bug
When I make a http request, it's hard to print its result.

e.g. Http request is:
![image](https://user-images.githubusercontent.com/18118994/79090089-1d0c0d80-7d7b-11ea-85aa-10731d316340.png)
![image](https://user-images.githubusercontent.com/18118994/79090240-8ee45700-7d7b-11ea-95c1-1a510b03ea13.png)

And I try to send response:
\- ${dialog.contosodata}                                 Not work
\- ${dialog.contosodata.content}                    Not work
\- ${string(dialog.contosodata)}                      Not work
\- ${string(dialog.contosodata.content)}         Not work

error message:
![image](https://user-images.githubusercontent.com/18118994/79090543-9bb57a80-7d7c-11ea-9c61-218dc7a3fbaf.png)

The only working way is weird:
\- ${dialog.contosodata} 1
![image](https://user-images.githubusercontent.com/18118994/79090595-bf78c080-7d7c-11ea-85c1-44f5fb481fb4.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by boydc2014** [comment]
Fixed in new SDK version.
