### ISSUE TITLE
more detailed error message like for switch empty condition

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2626]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when I only see an error message but don't know what is the cause.

For example, if condition is empty for switch, it will send
![image](https://user-images.githubusercontent.com/2876650/79098939-9fa1c680-7d95-11ea-9fb2-a8963816e91d.png)

But I don't know the cause and there is no hint on UI.

## Describe the solution you'd like

- Provide source/cause of the error
- Provide hint on UI

**Comment by hibrenda** [comment]
we do have empty check before. so we can evaluate how to address this through the validation before start the bot.

**Comment by xieofxie** [comment]
Another possible approach:
1 generate an uuid for each element's id field when created in composer
2 review all error messages generated in SDK to include the id field

Then one could search for that id for the related element.
Or at list do the 2nd step as the computed id is also meaningful.
