### ISSUE TITLE
it is very slow when writing lg in 'send an activity'

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2627]
## Is your feature request related to a problem? Please describe.

In chrome, `yarn build`, current master:
![C9jJO49vD7](https://user-images.githubusercontent.com/2876650/79104203-b13c9b80-7da0-11ea-8db5-442315673f57.gif)

I guess it is querying the possible functions for auto completion? But I am not writing expression.

**Comment by yeze322** [comment]
I met this issue before as well
@lei9444

**Comment by zhixzhan** [comment]
Seems like it's a parse performance issue, every typing would trigger a parse lg file. if you are lg file are extremely large, it would be more obviously.

**Comment by yeze322** [comment]
> Seems like it's a parse performance issue, every typing would trigger a parse lg file. if you are lg file are extremely large, it would be more obviously.

We can improve the UX by always showing latest keyboard input instead of waiting for lg validation (parser) result.

Displayed text = realtime user input not validated yet
onChange() result = lg content proved to be valid

![image](https://user-images.githubusercontent.com/8528761/79121108-1e632780-7dc7-11ea-8d22-ca8208426137.png)

**Comment by cwhitten** [comment]
@a-b-r-o-w-n & I are looking at this.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2632

**Comment by hibrenda** [comment]
https://recordit.co/OnmwhqIfI1 sounds like it is still slow on my desktop. I am using the latest master.

**Comment by a-b-r-o-w-n** [comment]
@hibrenda I do not see any perfomance issues. Can you share the bot you have opened with me? I have a suspicion that it has something to do with the size of the lg files being edited.

**Comment by cwhitten** [comment]
@hibrenda closing this again as this isn't a side-effect to typing, but a side-effect of the lg parser. cc @zhixzhan

**Comment by hibrenda** [comment]
[todoskill.zip](https://github.com/microsoft/BotFramework-Composer/files/4501600/todoskill.zip)
Attached the bot asset. Synced with @zhixzhan this also reproduced in his desktop.
Comparing the editing performance in lg all up view, inline editing is slower. Just FYI. 
@boydc2014 as well.

**Comment by zhixzhan** [comment]
@hibrenda I committed a patch PR to improve this by adding debounce to call update, you can have a try.

**Comment by boydc2014** [comment]
FYI @cwhitten, i reopened this one for Leilei and add this to R9-RC board.
