### ISSUE TITLE
How to integrate a Bot with existing Skill Bot in Composer

### ISSUE THREAD

**Issue by VijayaReddipalli** [microsoft/BotFramework-Composer#2628]
I have created a Bot in the Composer.
There is an existing skill bot developed using BotFramework SDK V4.
I want to integrate skill Bot with the Composer Bot.
Will I be able to do that using "Begin a Skill Dialog" from Composer?

**Comment by hibrenda** [comment]
You may reference this. https://github.com/microsoft/BotFramework-Composer/blob/master/docs/how-to-connect-to-remote-skill.md
