### ISSUE TITLE
Need to align the 'BeenUsed' mark for LU and LG

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2633]
Synced with @zhixzhan , BeenUsed will be "checked" if such template has been used in dialog file for LG. eg. send-activity with #bfd-xxx. But for LU text input hoisting, no "checked" if this has been used .
![image](https://user-images.githubusercontent.com/43408889/79184391-96246700-7e46-11ea-8a33-713de96dc84f.png)
![image](https://user-images.githubusercontent.com/43408889/79184367-8147d380-7e46-11ea-99a3-7ea62162b86e.png)

**Comment by zhixzhan** [comment]
Since now we can't tell a intent is used or not, only according to dialog json, I would suggest disable this column in LU at this moment.
