### ISSUE TITLE
Drop down info for skill selection

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2636]
Try to load different manifest version for same skill.
Hard to tell which one should be selected for "begin a skill". 
![image](https://user-images.githubusercontent.com/43408889/79191889-2e781700-7e5a-11ea-92a2-fc0a9c3d8c1f.png)

Could we include more info for drop down list ? @sangwoohaan @mareekuh

**Comment by cwhitten** [comment]
@hibrenda why do you have two different manifests with the same name?

**Comment by hibrenda** [comment]
As these are developed for the same skill, so name is same inside the manifests.
I can edit the skill name in setting page but that does not apply into the drop down list.

**Comment by mareekuh** [comment]
Are you saying that the name as edited in the settings page is not reflected in the dropdown?
Are you asking for version name to be included in the dropdown?

**Comment by cwhitten** [comment]
Based on the manifest schema, a best practice could be that if you use two different manifest versions of the same skill in the same bot, the manifest author would give them different names: `Email Skill - v1 manifest`, `Email Skill - v2 manifest`. They would show up in the dropdown as such.

I'm currently working on a way to override the given Name from an authored manifest used in a bot in the Skills page so users can guard against not following this practice, and make sure this override when provided shows up in the dropdown. This will make this problem go away.

**Comment by cwhitten** [comment]
![Screen Shot 2020-04-15 at 9 46 10 AM](https://user-images.githubusercontent.com/1156704/79364281-ff1ae600-7efd-11ea-954e-fd5599e6c483.png)

![Screen Shot 2020-04-15 at 9 46 54 AM](https://user-images.githubusercontent.com/1156704/79364334-1063f280-7efe-11ea-9903-0ba9541cb99d.png)

**Comment by cwhitten** [comment]
I've added the ability for custom names, closing this as complete.
