### ISSUE TITLE
trigger/action name setting error

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2641]
## Describe the bug
1. I can not change the name of the actions like "send response" as well as the trigger "custom action"
![ChangeFailed](https://user-images.githubusercontent.com/44257569/79210004-c71c9000-7e76-11ea-9410-ffff550b2c0f.gif)
![image](https://user-images.githubusercontent.com/44257569/79203215-47d68e80-7e6d-11ea-91ff-898f48498e79.png)
2. When I added name manually in the .dialog file, it works. But if I want to change it, the property will be cleared again.
![ChangeBack](https://user-images.githubusercontent.com/44257569/79209998-c552cc80-7e76-11ea-9a5c-5c84dc67eaa5.gif)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by hibrenda** [comment]
@a-b-r-o-w-n need your suggestion

**Comment by a-b-r-o-w-n** [comment]
I'll look at this today. I thought I had fixed this issue.

**Comment by a-b-r-o-w-n** [comment]
This was fixed in #2592. Please update your master branch.
