### ISSUE TITLE
Publish plugins should provide a form for the JSON configuration

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#2644]
## Is your feature request related to a problem? Please describe.

As part of the plugin registration, the plugin should provide a basic form for the JSON configuration that can be used as a placeholder in the "add new profile" flow on the publish page.

## Describe the solution you'd like

As part of the payload to `addPublishMethod`, the plugin should profile a JSON shape.

This will then be included in the call to `/publish/types`, and made available to the front end client.

The front end client should use this JSON shape to pre-fill the JSON configuration field in the "add new profile" flow.

Related to #2355

**Comment by benbrown** [comment]
@a-b-r-o-w-n hey Andy, this was part of your feedback from a few days ago. Is there a specific way to have the JSON editor pre-filled with this other than just setting the default value?

**Comment by a-b-r-o-w-n** [comment]
There is a `schema` prop on the editor that will be used if present. The editor will not set a default value, so that needs to happen outside of the editor.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2719
