### ISSUE TITLE
Is this at all related to Healthbot?

### ISSUE THREAD

**Issue by rosenjcb** [microsoft/BotFramework-Composer#2647]
Is this at all related to the Healthbot service available in Azure? Many features look similar but the UI looks different. Just a curious question.

**Comment by cwhitten** [comment]
Hi @rosenjcb. The Health Bot Service has their own authoring application that is not Composer, however both tools strive to write to Bot Framework common file formats (.dialog, .lg, .lu). At the moment I'm not sure where Health Bot Service is in their venture to provide this type of serialization.
