### ISSUE TITLE
`http://localhost:3000` no longer shows after running `yarn startall`

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2648]
## Describe the bug
Shall we display `Composer now running at: http://localhost:3000` after running `yarn startall` as we used to do? Otherwise some users may not know how to run Composer in a browser without reading our [documentation](https://docs.microsoft.com/en-us/composer/setup-yarn). 

#### This is what we had before:

![image](https://user-images.githubusercontent.com/32497439/79279163-45bb0280-7e62-11ea-9ff0-7ae1bf4ca591.png)

####  This is what we have now: 
![image](https://user-images.githubusercontent.com/32497439/79279292-887cda80-7e62-11ea-9d92-7d48c534e3f2.png)

## Version
Current master branch. 

## Browser
- [x] Chrome

## OS
- [x] Windows

## To Reproduce

1. Check out lastest master branch. 
2. Navigate to `C:\Users\UserName\Documents\GitHub\BotFramework-Composer\Composer` folder
3. Execute `yarn install`, then `yarn build`, then `yarn startall`

## Expected behavior
Should show `Composer now running at: http://localhost:3000`.

**Comment by boydc2014** [comment]
I think this is due to we removed all console.log or replaced with `debug` package @a-b-r-o-w-n @cwhitten , maybe we can set some default env args like DEBUG= (* or some value we see ok)?

**Comment by cwhitten** [comment]
we should add this back

**Comment by garypretty** [comment]
Yep - just hit this and thought it had hung :)

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2702
