### ISSUE TITLE
Http request occurs an error

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2651]
## Describe the bug

Http request occurs an error
![image](https://user-images.githubusercontent.com/19773357/79292873-cdf1e400-7f04-11ea-8728-170b0a441c15.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. add a 'send an http request' 
2. click it

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2659
