### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by bgeissler** [microsoft/BotFramework-Composer#2654]
## Describe the bug
I can't see any icons nor edit any values within the Electron version of composer. I assume this has something to do with our proxy, but I havn't found any setttings to configure a proxy for the Electron app

## Version
aca7358
Application SHA  test
SDK runtime packages  4.7.0-preview-191208-1

## Browser
- [ ] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Start Electron app

## Expected behavior

I should be able to edit the different fields and values

## Screenshots

![grafik](https://user-images.githubusercontent.com/47319993/79306175-10132980-7ef5-11ea-9628-7333a4b02b42.png)

**Comment by cwhitten** [comment]
@bgeissler are you behind a corporate firewall that disallows resolving public resources on the internet over `https`?

**Comment by bgeissler** [comment]
Yes, I'm behind a corporate firewall, but using our proxy I should (hopefully) be able to load the required data. I just don't know how to configure the Electron app to use our proxy or is this done automatically?

**Comment by cwhitten** [comment]
We do not expose currently this ability. This may take some investigation before we can resolve this. You're asking for the application to accept a proxy url to be used for all external network calls?

**Comment by bgeissler** [comment]
Yes, either the application should accept a proxy url or use the default proxy setting from the os, like Firefox is doing it for example

**Comment by cwhitten** [comment]
@tonyanziano tagging you to take a look at this after the auto-update pieces land.

**Comment by daveta** [comment]
@cwhitten : Should this be slotted for R14?
