### ISSUE TITLE
enable resize, enter path of open bot popup

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2655]
## Is your feature request related to a problem? Please describe.

 I'm always frustrated when it is too small (only show four items!!) and i can't edit the path (also copy etc.):
![image](https://user-images.githubusercontent.com/2876650/79308198-bb8aa100-7f2a-11ea-94a1-ca8435270dd7.png)

## Describe the solution you'd like

Enable edit path and resize to display more items

**Comment by hibrenda** [comment]
@sangwoohaan @mareekuh may need your attention.

**Comment by mareekuh** [comment]
Please extend the path box to the width of the list view and make it copy/paste and editable.
@benbrown  and @cwhitten  - is this doable?

**Comment by hibrenda** [comment]
@boydc2014 as well
