### ISSUE TITLE
enable hide left panel and right panel; show scroll bar when can't show all

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2656]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when I am comparing two dialogs and I don't have a big monitor or two monitors:

![image](https://user-images.githubusercontent.com/2876650/79309316-add61b00-7f2c-11ea-8496-d2cd3a0c3300.png)

It is very crowded and it should show scroll bars in this situation.

## Describe the solution you'd like

Enable hide and even auto-hide (only show when click an element)

**Comment by yeze322** [comment]
Scroll bar - duplicated with #2575 , was it fixed?
Hide - follow-up of #987

**Comment by cwhitten** [comment]
@xieofxie what viewport dimensions are you constrained to? can you use the browser tool to zoom the page out?

**Comment by xieofxie** [comment]
@cwhitten my monitor is only 24" 1080p. If I want to see two columns of elements like this:

![image](https://user-images.githubusercontent.com/2876650/79407926-b2521080-7fcc-11ea-902c-ac8d9012fc78.png)

I could use 75% but the text is very small and hard to see clearly

**Comment by hibrenda** [comment]
Just showed the scenario in today's stand up. resizing for each panel could not solve the issues. This mainly focus on each panel (navigation, visual, form) could be hide & pinned

**Comment by hibrenda** [comment]
@sangwoohaan @mareekuh for awareness
