### ISSUE TITLE
can't use 0 in switch

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2658]
## Describe the bug

1. Set a case value to integer - 0
2. switch to another action
3. switch back
You will find the integer - 0 disappears and set to boolean

![Ai86sRAnK5](https://user-images.githubusercontent.com/2876650/79314819-ca765100-7f34-11ea-85b2-e084ef92aba8.gif)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
@a-b-r-o-w-n
