### ISSUE TITLE
Error in `Send an HTTP request` action 

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2664]
## Describe the bug
![http-error](https://user-images.githubusercontent.com/32497439/79372302-a69e1580-7f0a-11ea-8334-5bad049b2b15.gif)

## Version
Mater branch.

## Browser
- [x] Chrome

## OS
- [x] Windows

## To Reproduce

1. Go to 'Excess external resources'
2. Click on 'Send an HTTP request'
3. See error

**Comment by cwhitten** [comment]
duplicate of https://github.com/microsoft/BotFramework-Composer/issues/2651
