### ISSUE TITLE
Can't select certain action nodes

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#2667]
After pulling the latest commit in the master branch, all the prompt nodes, as well as condition nodes, have become unselectable.

**Comment by yeze322** [comment]
@alanlong9278 pls have a look

**Comment by yeze322** [comment]
Broken by #2638 
![image](https://user-images.githubusercontent.com/8528761/79352764-d7af3200-7f6c-11ea-9962-35a15740f5ce.png)

**Comment by yeze322** [comment]
@cwhitten I found a trick in DOM order:
- elements declared **before** `<svg />` are unreachable
- elements declared **after** `<svg />` are reachable

I will fix it
