### ISSUE TITLE
Better grouping bot setting

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#2668]
We probably need to group the bot settings betters moving forward. It's not something we were paying too much attention, while we are adding and designing features like skills, runtime, related. 

So for examples, today we serialized with key `skill`: {} for connected skills, and probably skillHostEndpoint as a separate key.

Also in the design of custom runtime, we are talking about two fields like 
customizedRuntime: true
runtimeCommand: ...

what we could do is starting to at least group settings in top level like
```
app:
   microsoft...

luis:  
    ...
qna:
    ... 
skill
    connectedSkills: []
    skillHostEndpoint.
    skill...
runtime
   { 
     type: managed\customized
     version: .. (in managed type only)
     command: (in custmized only)
     features: []
   }
```

**Comment by luhan2017** [comment]
I like your idea, but I think it is not necessarily to add a group key there. We can just group them by location. Later, we will have a new setting page. We could group them by the UX rather than add extra group key. How do you think?

**Comment by yeze322** [comment]
How do we consider plugins config? For example, luis is already a plugin and qna will be a new plugin
