### ISSUE TITLE
support variable auto completion

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2670]
## Is your feature request related to a problem? Please describe.

Now lg editor can only auto complete prebuilt functions. I hope composer can support variable auto completion in lg editor and expression editor. After I defined many variables, it is hard to remember all of the name.

## Describe the solution you'd like

support variable auto completion in lg editor and expression editor

**Comment by hibrenda** [comment]
@boydc2014 for your awareness
