### ISSUE TITLE
Support dialog navigation status saving

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2671]
## Is your feature request related to a problem? Please describe.

When I am editing a long and complex dialog, once I navigate to other page and return the dialog. It always returns to the begin of dialog. It is hard to find the last editing position.

## Describe the solution you'd like

I hope composer can save the editing status when navigate to different dialog.

**Comment by hibrenda** [comment]
@boydc2014 @lei9444 for your awareness
