### ISSUE TITLE
number in settings shouldn't be parsed as string

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2675]
## Is your feature request related to a problem? Please describe.

I added a number property in settings like:
```
{
  "MicrosoftAppId": "",
  "DisplaySize": 3,
  ...
}
```
When I try to use it in dialog, it is parsed to a string. So I have to use it by `int(settings.DisplaySize)`. 

## Describe the solution you'd like

the number in settings should be parsed to a number

**Comment by hibrenda** [comment]
https://github.com/microsoft/botbuilder-dotnet/issues/3698

**Comment by a-b-r-o-w-n** [comment]
Closing this since it is being tracked in https://github.com/microsoft/botbuilder-dotnet/issues/3698
