### ISSUE TITLE
bf luis:build does not exist

### ISSUE THREAD

**Issue by TylerOdenthal** [microsoft/BotFramework-Composer#2690]
## Describe the bug

I have been developing on Composer for a couple week and am building out a pretty comprehensive HR bot. **The issue is that when I added LUIS to my bot in composer, I am unable to publish to Azure.** 

Up until this point I was just using language generation and setting up my bot architecture. I am now to the point where I need to parse entities in conversation for slot filling and survey purposes.

**I am able to test my bot in emulator and it is able to access my LUIS application just fine, WHEN using emulator. BUT, my composer will not publish to Azure anymore and is throwing this error.**

## Version

Application SHA
test

SDK runtime packages
4.7.0-preview-191208-1

I believe I'm using the most recent stable branch.

## Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Not 100% sure, but all I did was add this LUIS intent to a block that is screening for FoodAllergies.

```
# TextInput.response-844063
- I have shrimp allergies
- Milk doesn't make me feel good
- This is to food survey
- This is a for the food survey
- I want to take the food survey

$foodAllergies:Lactose=
	- Cow's Milk
	- Milk
	- Cheese
	- Dairy
$foodAllergies:Shrimp=
	- Shrimp
$foodAllergies:Tree Nut=
	- Almond
	- Cashew
	- Brazil Nut
	- Tree Nut
$foodAllergies:Peanuts=
	- Peanuts
```

## Expected behavior

Deploy to Azure with LUIS resources attached to my Bot Framework.

## Screenshots

![Issue1](https://user-images.githubusercontent.com/63730511/79500658-a45aba80-7fe1-11ea-8e9d-578df456ef02.JPG)

## Additional context

I have also tried the commands that the console instructed me to try and it did not fix the problem.

Error Text:

```
C:\Users\Tyler\Desktop\ChatWorks\MicrosoftTeamsBots\BotFramework-Composer-stable\BotProject\HRBotPrototype>pwsh ./Scripts/deploy.ps1 -name HRBotPrototype -environment testing
The MSBuild project 'C:\Users\Tyler\Desktop\ChatWorks\MicrosoftTeamsBots\BotFramework-Composer-stable\BotProject\HRBotPrototype\BotProject.csproj' has already been initialized with a UserSecretsId.
bf luis:build does not exist, use the following command to install:
1. npm config set registry https://botbuilder.myget.org/F/botframework-cli/npm/
2. npm install -g @microsoft/botframework-cli
3. npm config set registry http://registry.npmjs.org
```

**Comment by TylerOdenthal** [comment]
Removed LUIS Auth Key from appsettings.Deployment.JSON

I am able to deploy my bot to Azure again. I will refrain from using LUIS at this time until I get a reply.

![IssueResolved](https://user-images.githubusercontent.com/63730511/79515174-c1e94d80-7ffc-11ea-8b64-d787ac16893a.JPG)

**Comment by TylerOdenthal** [comment]
I believe that this will solve my problem as I don't have LUISGen installed, but now I'm running into a new issue.

dotnet tool install --global LUISGen --version 2.2.0

`C:\Users\Tyler\Desktop\ChatWorks>dotnet tool install --global LUISGen --version 2.2.0
error NU1100: Unable to resolve 'luisgen (>= 2.2.0)' for '.NETCoreApp,Version=v3.1'.
error NU1100: Unable to resolve 'luisgen (>= 2.2.0)' for '.NETCoreApp,Version=v3.1/any'.
The tool package could not be restored.
Tool 'luisgen' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool`

**Comment by zidaneymar** [comment]
@TylerOdenthal Hi, actually you need to npm install @microsoft/botframework-cli command line package to enable bf:luis command which would be used in this script.
And if you remove the luis authoring key and luis authoring region in the appsettings, the script will not try to train the luis models based on your *.lu files.
So if you have any luis features inside your bot, I suggest your following the instructions to install @microsoft/botframework-cli, or it may not work as expect.
