### ISSUE TITLE
Variables are not parsed in the Url of an Http Request 

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#2695]
## Describe the bug

When using a variable in the Url field of an HTTP request, like so; 
${dialog.apiUrl}
The variable is not parsed. The help icon of the Url field says that data binding is supported.

## Version

4.7.0-preview-191208-1

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

1. Add Set a property (Property: dialog.apiUrl, Value:'http://www.test.com')
2. Add Send a HTTP request (Method: Get, Url: ${dialog.apiUrl})
3. Run the bot

## Expected behavior

Variable should have been parsed in the Url field

**Comment by luhan2017** [comment]
@cxbuilders , I think that is because the version you are using is too old. could you check the latest master, you can refer to the HttpRequest step in the DialogActions template: 

![image](https://user-images.githubusercontent.com/32191031/79555596-71442400-80d2-11ea-99d3-ea7372f1724e.png)

**Comment by cxbuilders** [comment]
Works now!

**Comment by rslavey** [comment]
I have the same issue. I'm on 1.3.0.

My Url field shows required and has (abc) in the icon to the left and not (fx). I can set a property to the URL string and it shows fine in a message but passes the actual property name.

    value in message: https://graph.microsoft.com/v1.0/users/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    value in Http GET command: label: "HttpRequest[GET =`${$game.userTargetUrl}`]"

**Comment by luhan2017** [comment]
@rslavey We've updated some of the fields to adaptive expressions in 1.3.0, could you try to add a '=' before your string.

**Comment by rslavey** [comment]
This was successful. Thank you.

**Comment by shwars** [comment]
I am trying to use variable substitution in Bot Composer 1.3.1, and I cannot make substitution to work. I am trying to substitute an entity `country` extracted in the LUIS trigger. I tried the following:
* `http://my.rest.service/api/${@country}` - does not do substitution
* `=http://my.rest.service/api/${@country}` as suggested by @luhan2017 - gives an error "mismatched input ‘:’ expecting <EOF>" in the bot chat
* I have tries assigning `@country` to another variable such as `${user.country}` in a separate block, and using `${user.country}` instead - no difference
I would appreciate any help. @rslavey, what was the exact syntax you have used which solved the problem?

**Comment by mpcrossley** [comment]
Same here - I cna't seem to add variables in any URL for HTTP requests.

**Comment by rslavey** [comment]
Here is how I made it work:

    =concat('https://graph.microsoft.com/v1.0/users/',$game.whoUserId,'/photo/$value')

I think once you put the equals sign, you have to use the concat function to put strings together. It may work if you assign the whole URL to a single variable and then use

    =${@url}

but I'm not sure.

**Comment by rahul-8437008949** [comment]
@shwars Did it work for you? I am also facing the same problem as you faced . Did you fing solution for it?

**Comment by Sakyawira** [comment]
I still cannot get this working btw. I am on 2.0
![image](https://user-images.githubusercontent.com/41171000/125395192-f7970500-e3fe-11eb-8fcb-860d7ed1dbea.png)
![image](https://user-images.githubusercontent.com/41171000/125395230-054c8a80-e3ff-11eb-9187-3efe45bdda35.png)

**Comment by Paanshul** [comment]
@Sakyawira instead of title={$user.anime}, write it like title=${user.anime}.

**Comment by tortura** [comment]
Hi, i am having the same issue, 
![image](https://user-images.githubusercontent.com/1259897/132026567-4687c925-1ac5-4958-94af-0148861d1007.png)

grabbing an input
![image](https://user-images.githubusercontent.com/1259897/132026511-3e8241bf-c70c-4056-a86f-4da6d98a24d6.png)

results in 
![image](https://user-images.githubusercontent.com/1259897/132026647-b20b2189-b819-41d7-9754-a16c87f78d72.png)

any help appreciated
