### ISSUE TITLE
goto first trigger(i.e. BeginDialog) after click a dialog

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#2696]
## Is your feature request related to a problem? Please describe.

Currently we just open the default view

Or at least when clicking from begin dialog action

**Comment by cwhitten** [comment]
This is a deliberate design decision. @sangwoohaan

**Comment by cwhitten** [comment]
To implementer:

When not the entry dialog, navigate to the dialog's BeginDialog trigger when selected from the nav.
