### ISSUE TITLE
FacebookAdapter [OnTurnError] unhandled error : Value cannot be null. (Parameter 'ConversationState')

### ISSUE THREAD

**Issue by InnoraG** [microsoft/BotFramework-Composer#2705]
## Describe the bug

-Added Microsoft.Bot.Builder.Adapters.Facebook on the runtime as per https://github.com/microsoft/botbuilder-dotnet/tree/master/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook
and https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/61.facebook-adapter
-Bot runs with no error and facebook webhook subscription validate well tested with ngrok.
-Issue is when messages flow : 

> info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Microsoft.BotBuilderSamples.Controllers.FacebookController.PostAsync (BotProject)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Post", controller = "Facebook"}. Executing controller action with signature System.Threading.Tasks.Task PostAsync() on controller Microsoft.BotBuilderSamples.Controllers.FacebookController (BotProject).
fail: Microsoft.Bot.Builder.Adapters.Facebook.FacebookAdapter[0]
      [OnTurnError] unhandled error : Value cannot be null. (Parameter 'ConversationState')
System.ArgumentNullException: Value cannot be null. (Parameter 'ConversationState')
   at Microsoft.Bot.Builder.Dialogs.DialogManager.OnTurnAsync(ITurnContext context, CancellationToken cancellationToken)

## Version

4.7.0-preview-191208-1

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Configure/Add FacebookAdapter on the runtime
2. Run bot
3. Subscribe webhook
4. Send message from messenger

## Expected behavior

Bot to work without error

## Screenshots

![image](https://user-images.githubusercontent.com/6458346/79641518-aae36080-81a0-11ea-859e-13ff2ebe0b5d.png)

**Comment by zidaneymar** [comment]
@InnoraG Hi, based on the log, I think you should add UserState and ConverstaionState to your bot adapter as well.
Could you please try this code?
```
IStorage storage = new MemoryStorage();
var userState = new UserState(storage);
var conversationState = new ConversationState(storage);
adapter
    .UseStorage(storage)
    .UseState(userState, conversationState);
```

**Comment by InnoraG** [comment]
Thanks @zidaneymar , managed to make it work by adding these state.

But the FacebookAdapter seems not compatible with Composer runtime, it is having issue in handling anything except text.

**Comment by zidaneymar** [comment]
> Thanks @zidaneymar , managed to make it work by adding these state.
> 
> But the FacebookAdapter seems not compatible with Composer runtime, it is having issue in handling anything except text.

Sorry for replying late, do you have more details?

**Comment by luhan2017** [comment]
@InnoraG , we want to know the reproduce steps, like how do you use the FacebookAdapter in Composer and how do you do the deployment and testing.

**Comment by cwhitten** [comment]
Assigning @luhan2017 as an owner to get requirements and an appropriate solution

**Comment by zidaneymar** [comment]
Will investigate how to enable customized adapter in Composer runtime in the next few days.

**Comment by zidaneymar** [comment]
Just get a work around for facebook adapter.
Using [dotnet sdk](https://github.com/microsoft/botbuilder-dotnet), commit hash: f127fca9

Here are the concrete steps to create facebook adapters based on the composer dotnet runtime:

1. Register your facebook page and facebook app and configure related details based on this [doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0#complete-configuration-of-your-facebook-app)

2. Create a funtion in Startup.cs to get facebook adaper:

```
        public FacebookAdapter GetFacebookAdapter(IStorage storage, BotSettings settings, UserState userState, ConversationState conversationState, IServiceProvider s)
        {
            var adapter = new FacebookAdapter(this.Configuration);
            adapter
              .UseStorage(storage)
              .UseBotState(userState, conversationState)
              .Use(new RegisterClassMiddleware<IConfiguration>(Configuration));
            adapter.OnTurnError = async (turnContext, exception) =>
            {
                await turnContext.SendActivityAsync(exception.Message).ConfigureAwait(false);
                await conversationState.ClearStateAsync(turnContext).ConfigureAwait(false);
                await conversationState.SaveChangesAsync(turnContext).ConfigureAwait(false);
            };
            return adapter;
        }
```

3. Register the facebook adapter in services:
```
            services.AddSingleton<FacebookAdapter>((sp) => GetFacebookAdapter(storage, settings, userState, conversationState, sp));
```

4. Configure the following configuration file in appsettings.json:

```
{
  "FacebookVerifyToken": "<Your token>",
  "FacebookAppSecret": "<Your app secret>",
  "FacebookAccessToken": "<Your access token>"
}
```
5. Create a facebook controller:
```
    [Route("api/facebook")]
    [ApiController]
    public class FacebookController : ControllerBase
    {
        private readonly FacebookAdapter _adapter;
        private readonly IBot _bot;

        public FacebookController(FacebookAdapter adapter, IBot bot)
        {
            _adapter = adapter;
            _bot = bot;
        }

        [HttpPost]
        [HttpGet]
        public async Task PostAsync()
        {
            // Delegate the processing of the HTTP POST to the adapter.
            // The adapter will invoke the bot.
            await _adapter.ProcessAsync(Request, Response, _bot);
        }
    }
```
5. Use ngrok or deploy the bot to azure and configure the endpoint to https://<your endpoint>/api/facebook. on your facebook settings.

6. Start testing with facebook messenger or on your facebook page.

Here is the sample result for echo bot:

![image](https://user-images.githubusercontent.com/9328933/88525316-05584c80-d02d-11ea-9202-22f07051f442.png)

**Comment by igordevezas** [comment]
Hi @zidaneymar, I tried to use the FacebookAdapter with Composer... After 6 hours understanding the way, I was able to get the connection. The problem now is to display the cards/texts.

![image](https://user-images.githubusercontent.com/1262003/103560470-1e0c3e80-4eb8-11eb-955d-fc2dde79273d.png)

**Comment by igordevezas** [comment]
Just to inform that after trying use ChannelData to replace HeroCards:

```
# MyMessage
[Activity 
        ChannelData=${json(channelData())}
]

# channelData
-```{
    "attachment":{
      "type":"template",
      "payload":{
        "template_type":"button",
        "text":"What do you want to do next?",
        "buttons":[
          {
            "type":"web_url",
            "url":"https://www.messenger.com",
            "title":"Visit Messenger"
          }
        ]
      }
    }
}```
```

I get:

![image](https://user-images.githubusercontent.com/1262003/103570192-ea85e000-4ec8-11eb-81d8-76ce6028a81d.png)


Any lights here, please?

Many thanks.
