### ISSUE TITLE
Responding with cards sample no renderer for adaptive card

### ISSUE THREAD

**Issue by timenick** [microsoft/BotFramework-Composer#2709]
## Describe the bug
Choose adaptive card self, it works. But when you select all cards, the last card will show No renderer for this attachment.

## Version

composer stable

## Screenshots

![image](https://user-images.githubusercontent.com/3319068/79712114-9320ef00-82fc-11ea-8ac7-c9e4f8fa7c7e.png)

![image](https://user-images.githubusercontent.com/3319068/79712132-a92eaf80-82fc-11ea-9c6e-3d60e7f959e9.png)

**Comment by Danieladu** [comment]
change the `AllCards` template from 
```
# AllCards
[Activity
    Attachments = ${HeroCard()} | ${ThumbnailCard()} | ${SigninCard()} | ${AnimationCard()} | ${VideoCard()} | ${AudioCard()} | ${AdaptiveCard()}
    AttachmentLayout = ${AttachmentLayoutType()}
]
```

to 
```
# AllCards
[Activity
    Attachments = ${HeroCard()} | ${ThumbnailCard()} | ${SigninCard()} | ${AnimationCard()} | ${VideoCard()} | ${AudioCard()} | ${json(adaptivecardjson())}
    AttachmentLayout = ${AttachmentLayoutType()}
]
```

The reason is that, you can not insert an activity entity into the value of attachment property.

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2752
