### ISSUE TITLE
Hover in new bot wizzard looks weird

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#2715]
## Describe the bug

![image](https://user-images.githubusercontent.com/3829387/79741307-9aafba80-8333-11ea-9608-410e6213e980.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2728
