### ISSUE TITLE
There is an extra black border when select a template from the template list

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#2725]
## Describe the bug

when select a template from the list, there is an extra black border there. 

![image](https://user-images.githubusercontent.com/32191031/79842171-0a34b100-83eb-11ea-8bce-f7da189cf85e.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2728
