### ISSUE TITLE
LG template name not correct

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2726]
## Describe the bug
refs #2597

1. LG in SendActivity
![image](https://user-images.githubusercontent.com/8528761/79843786-4c5ef200-83ed-11ea-982d-e2d418f29640.png)
2. LG after copied
![image](https://user-images.githubusercontent.com/8528761/79844102-cf804800-83ed-11ea-9717-95f1d0efbdc3.png)

They should follow
![image](https://user-images.githubusercontent.com/8528761/79843893-79130980-83ed-11ea-81df-f4fb4c991996.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
fixed in #2718

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2718
