### ISSUE TITLE
Dialog scope does not show in JSON trace

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#2727]
The dialog object does not show in the JSON trace.

## Version

4.7.0-preview-191208-1

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X ] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

- Set property dialog.test with value "test"
- Run Bot
- Click on the last trace and try to find the property dialog.test in the JSON output

## Expected behavior

- have the dialog properties show up so you can debug

**Comment by hibrenda** [comment]
This can not be reproduced on master branch. 
![image](https://user-images.githubusercontent.com/43408889/79991911-62e87480-84e5-11ea-9868-7275b2ac6d2f.png)

**Comment by cxbuilders** [comment]
Sorry hibrenda, latest version this is fixed.
