### ISSUE TITLE
Remove trailing blank lines in template 'TodoBotWithLuis'

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2730]
## Describe the bug
![image](https://user-images.githubusercontent.com/8528761/79856248-b0d67d00-83fe-11ea-84a3-dfe56e83d747.png)

![image](https://user-images.githubusercontent.com/8528761/79954062-5f39fb00-84af-11ea-9a54-69cf380c5c9c.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
@zhixzhan

**Comment by zhixzhan** [comment]
@yeze322 I don't think lgParser should modify the inputs. Actually recently lgParser made some refactor to truly respect what user input, when do updateTemplate save it.

for example, when you are typing in form editor, then inputs would not always be valid, likes

```
- 
```

```
- h
\n
```

```
- h
\n
> comments
```

```
[Activity
\n

```
```
[Activity
\n
]
```
if parser modify the inputs when do updateTemplate, user side will see strange behavior, 'swallowing blank at end', 'swallow invalid line >' ...

**Comment by yeze322** [comment]
@zhixzhan I got it. So the action we need to take is updating the TodoLUISTemplate.
It contains many unecessary blank lines
![image](https://user-images.githubusercontent.com/8528761/79953864-200baa00-84af-11ea-979a-0d445e2ee8bf.png)

**Comment by zhixzhan** [comment]
I guess so, manually clean up template sample bot sounds resonable.

**Comment by boydc2014** [comment]
Close to not valid anymore
