### ISSUE TITLE
Not possible to set property to a ISO 8601 date

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#2731]
When storing a date in the ISO 8601 format with 0 milliseconds it gets truncated. When you set a property user.date with the following value:
"2020-04-21T11:36:40.000Z"
it actually stores it as
"2020-04-21T11:36:40Z"

Also storing it as ${string('2020-04-21T11:36:40.000Z')} makes no difference. 

This then fails all other date functions like ${addSeconds(user.date, 120)}.

## Version

4.7.0-preview-191208-1
## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

- Add a Set a Property element: user.date = 2020-04-21T11:36:40.000Z
- Add a Send a response element: -${addSeconds(user.date, 120)}
- Run Bot
- Check user object trace

## Expected behavior

Date to be stored in proper ISO 8601 format also when milliseconds are set to 0

**Comment by hibrenda** [comment]
@cosmicshuai  do you have comments for this issue ?

**Comment by cosmicshuai** [comment]
I tried evaluating 'string(formatDateTime("2020-04-21T11:36:40.000Z"))' in AdaptiveExpression, and it returned "2020-04-21T11:36:40.000Z". Would you have a try? 
It think it is caued by the editor, the value is changed before the runtime recieved.

**Comment by cosmicshuai** [comment]
I create a PR in SDK to solve this issue.
https://github.com/microsoft/botbuilder-dotnet/pull/3792

**Comment by cosmicshuai** [comment]
Hi @cxbuilders, 
after some discussion with the SDK team, I would suggest you use ${addSeconds(formatDateTime(user.date ) ,120)} temporarily. 
We found the gap of serialization between dialogStateManager and the prebuilt functions.
We will change some datetime functions to support DateTime object in C# and JS. 
It will takes some time. And for now,  ${addSeconds(formatDateTime(user.date ) ,120)} works on Composer. 
Sorry for the inconvenience, we will notice you under this issue once all datetime functions are ready for DateTime input.

**Comment by cwhitten** [comment]
@cosmicshuai closing this issue. please link the appopriate SDK ticket
