### ISSUE TITLE
Only part of dialogs are shown in lu/lg navigation list

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2738]
## Describe the bug
In my bot, I have lots of dialogs and I can see all of them as below
![image](https://user-images.githubusercontent.com/44257569/79934332-df973680-8484-11ea-8507-5cd10dead8e2.png)
But in the LU/LG navigation list, I can just see part of them
![image](https://user-images.githubusercontent.com/44257569/79934777-f7bb8580-8485-11ea-972e-1aa333a3baa4.png)

![image](https://user-images.githubusercontent.com/44257569/79934400-07869a00-8485-11ea-99ea-c6641fd16837.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2747
