### ISSUE TITLE
"Disable" option missing

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2745]
## Describe the bug
Can't find the "Disable” option, it's a bug or by design?
![image](https://user-images.githubusercontent.com/44257569/80054137-1470bf80-8551-11ea-9026-001dc9b8a05f.png)

## Version

"71e6acdab35f3cfedb8a6"

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
Hi @xhr0804. we removed this capability as the experience in using it was not what we want. we want people to use the visual editor to select and disable groups of nodes.

As a workaround, you now can click "Show code" and add the disabled: true flag to an object that you wish to disable and it will work.

![Screen Shot 2020-04-22 at 8 11 50 PM](https://user-images.githubusercontent.com/1156704/80055028-8e636300-84d5-11ea-8b0e-3d97bf72da95.png)

**Comment by xhr0804** [comment]
@cwhitten Thanks, but I can not find the "show code" button.(The code updated yesterday). Am I doing something wrong?
![image](https://user-images.githubusercontent.com/44257569/80055674-d6759a80-8554-11ea-8d1f-39c6bf2561a1.png)

**Comment by cwhitten** [comment]
@xhr0804 if you pulled the latest `master`, https://github.com/microsoft/BotFramework-Composer/commit/3a7dbce5c902d18e3320a46a5d88084a7b292a80 introduced it

**Comment by xhr0804** [comment]
@cwhitten it works, thanks!
