### ISSUE TITLE
Unified ScreenReader behavior in Visual Editor

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2746]
## Describe the bug
Delete a node -> read something
Copy a node -> read something
......

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
I can list out several events which should trigger the ScreenReader:
- Delete Actions => read "N actions deleted"
- Create an Action => read "action created"
- Copy Actions => read "action copied"
- Paste Actions => read "action pasted"
- Move Actions => read "action moved"

@cwhitten @beyackle do you guys think the sentences are proper? Need your help on deciding what content should be read.

**Comment by cwhitten** [comment]
@yeze322 is this ticket necessary? we have other a11y issue tracking this work I thought.

**Comment by alanlong9278** [comment]
This ticket is the same with #2079

**Comment by cwhitten** [comment]
Thanks @alanlong9278. Closing this as a duplicate
