### ISSUE TITLE
unexpected error when I set the property

### ISSUE THREAD

**Issue by xhr0804** [microsoft/BotFramework-Composer#2748]
## Describe the bug
When I edit the value in the set property, if I type in quickly, the result will be presented very slowly. And often throw an error.
![Error](https://user-images.githubusercontent.com/44257569/80065370-91f5f900-856c-11ea-88af-8e411e0c3f40.gif)

![image](https://user-images.githubusercontent.com/44257569/80065438-b18d2180-856c-11ea-863c-f41e2ea60c56.png)

and some lg file will be deleted automatically.

![image](https://user-images.githubusercontent.com/44257569/80065542-ded9cf80-856c-11ea-8e82-76198346c97b.png)

## Version

"3a7dbce5c902d"

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by zhixzhan** [comment]
After some dig, It can only be re-pro on `an old laptop` +` yarn build && yarn start`

**Comment by hibrenda** [comment]
addressed in #2786
