### ISSUE TITLE
Visual: Banner color update from black to blue

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#2755]
In the visual alignment review of the FUSE products and the deltas with the Fluent style guide Composer did very well. There were a few areas where we're unnecessarily different:

1. Banner color (currently black) and 
2. Icon in the upper left : we have our custom icon, Fluent apps have the 9 grid which on click brings a pane with 1 click access to related products.

Number 2 does not seem a reasonable one to introduce at this time.
Could we do 1?

@DesignPolice - could you include a pointer to the design?

**Comment by DesignPolice** [comment]
Hey Chris here is the update on this... 

We can just change the color **Phase 1** for now, but I have added the **Phase 2** - for reference when we are ready to use the Waffle menu, add Search and take off the Icon. 

**Figma Link**

https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=1929%3A13

**Screen Shot**

![Screen Shot 2020-04-28 at 12 43 08 PM](https://user-images.githubusercontent.com/45223620/80530764-597c6380-894e-11ea-85d3-ba24b8f3b192.png)

**Comment by mareekuh** [comment]
Thanks @DesignPolice and @cwhitten  - that would be great (Phase 1 for now).

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2779
