### ISSUE TITLE
load schema from the path of 'Use custom runtime'

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2760]
## Describe the bug
As a follow up of #2572, after pointed the runtime to a customized position
![image](https://user-images.githubusercontent.com/8528761/80192740-3d28b000-864a-11ea-891a-93eb1a657dda.png)
Composer should also load the schema files under that runtime folder.

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
@yeze322  i'm closing this. this ticket is already tracked and represented.
