### ISSUE TITLE
bot publishing failed

### ISSUE THREAD

**Issue by KayMKM** [microsoft/BotFramework-Composer#2763]
## Describe the bug

![image](https://user-images.githubusercontent.com/19773357/80202231-e3c77d80-8657-11ea-939a-7b0df6f525a1.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
@KayMKM I can't reproduce this. Can you provide more detail in your issue? For example, reproduction steps, or what browser & OS you are using? The template are intended to be actually used.

**Comment by luhan2017** [comment]
This is because the bot is not created in the latest Composer branch. You can add this configure to your settings\appsettings.json file to mitigate this. 

  "runtime": {
    "customRuntime": false,
    "path": "",
    "command": ""
  },

@cwhitten @boydc2014 , I think we should help users add this default value if their runtime config is missing.

**Comment by boydc2014** [comment]
We should just add guard on null, @VanyLaw can you check this?

**Comment by darrenj** [comment]
I ran into this as well - thanks @luhan2017. Falling back to the above defaults would help with customers who have existing projects and I assume any samples

**Comment by cwhitten** [comment]
> I ran into this as well - thanks @luhan2017. Falling back to the above defaults would help with customers who have existing projects and I assume any samples

totally agree. we will protect backwards compat. and provide migration options in these scenarios post GA.
