### ISSUE TITLE
Composer with LUIS

### ISSUE THREAD

**Issue by nvikey** [microsoft/BotFramework-Composer#2764]
I am exploring Composer. I already use bot-framework c# model in Azure that connects with LUIS. We developed a one step FAQ bot (not multi-turn conversations) with only one main dialog. We used to extract the Luis intent and score whenever users type a text. We get answer from a Sharepoint list for FAQs by passing the identified LUISIntent as a column filter. 

1. Is it possible to do the same in Composer to get the intent identified and score for each input we get from user.? 

2. Also, instead of training the LU model in composer, can we train the utterances in the LUIS portal and consume the same intent/score in composer?

**Comment by cwhitten** [comment]
Hi @nvikey, here is the info I have do you:

> Is it possible to do the same in Composer to get the intent identified and score for each input we get from user.?

If I'm understanding your question, yes -- you have the ability to call a sharepoint service inside an OnIntent trigger definition and provide the identified intent.

 > Also, instead of training the LU model in composer, can we train the utterances in the LUIS portal and consume the same intent/score in composer?

Do achieve this, you would need to export the LU model in the LUIS portal once you have done your training, and paste it into your Composer bot's LU model.

Closing as a how-to, happy to continue troubleshoot on this ticket.

**Comment by nvikey** [comment]
Do we need to create one trigger for each intent? If yes, then I think, we need to re-write the SharePoint piece of code in all the 100 intents, which is not an easier way. Please confirm.

**Comment by Kirill-Ovc** [comment]
> Do achieve this, you would need to export the LU model in the LUIS portal once you have done your training, and paste it into your Composer bot's LU model.

Thanks for this helpful tip. Didn't know about it.
