### ISSUE TITLE
Date gets altered in body of Post Request

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#2765]
## Describe the bug
When adding a date using dateFormatTime() in the body of a Post Request, the - are getting replaced by _

## Version
Cannot see SHA in about page

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Add a Send a HTTP request component in the flow
    Method -> POST
    Url -> https://graph.microsoft.com/v1.0/me/events
    Body -> 
{
  "date": "${formatDateTime(utcNow(), 'yyyy-MM-ddTHH:mm')}",
  "date2": "2020-04-24T14:22"
}
2. Run the flow
3. Check the HttpRequest trace: value -> request -> content
4. Notice that the first date has _ in it, the second one is unaffected

## Expected behavior

Date with 202-04-02 format instead of 2020_04_02

**Comment by cwhitten** [comment]
Ugh, this is an LG issue. cc @zhixzhan @feich-ms

**Comment by boydc2014** [comment]
uassign vishwac and fei, after testing in sdk and in composer of just using ${formatDateTime(utcNow(), 'yyyy-MM-ddTHH:mm')}, it works as expected. So largely it's something wrong after we reload the bot and try to transform it.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2774
