### ISSUE TITLE
Error messagebox prompt and rendering issue

### ISSUE THREAD

**Issue by bobokids** [microsoft/BotFramework-Composer#2767]
## Describe the bug

. Add a event trigger
. Add SetProperties
. Add a property and input the property name "conversation.keyword"

Result:
1. while input, a error dialog is pop up for many times, each time with different error msg. This is not a smooth authoring experience. 
2. rendering issue of the error dialog when scroll the error msg.
3. input perf is very bad, known issue.

![image](https://user-images.githubusercontent.com/19182479/80227786-be9b3500-8680-11ea-932b-f1ea1350abe0.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
@bobokids I can't reproduce this on a new bot. Can you please create a bot from scratch and see if the issue still exists?

**Comment by hibrenda** [comment]
I can reproduce this issue. sounds like more easily to hit for complicated bot editing (eg. who skill) but never reproduced on my echo bot. @cwhitten

**Comment by boydc2014** [comment]
@zhixzhan  can you investigate why "editing a property will cause lg file not exist"

**Comment by hibrenda** [comment]
error message will be tracked https://github.com/microsoft/BotFramework-Composer/issues/2748.
this issue will track performance issue.
