### ISSUE TITLE
remove dialog sometimes will throw error

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#2783]
## Describe the bug
![image](https://user-images.githubusercontent.com/39758135/80358419-f687bf80-88ae-11ea-9bb8-58b1a818d4f5.png)

remove dialog may throw this error.

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by zhixzhan** [comment]
track on #2793
