### ISSUE TITLE
The configuration settings in Composer UI does not get reflected in app settings

### ISSUE THREAD

**Issue by manvendrautralia** [microsoft/BotFramework-Composer#2784]
## Describe the bug

The configuration settings at UI or any change in LUIS subscription does not get reflected in app settings. As a result the deployment fails with error ->

_Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-cli/issues                                                                                                       Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.                        lubuild succeeded                                                                                                                                                                                                  Getting Luis accounts...                                                                                                                                                                                           Return invalid status code while gettings luis accounts: 401, error message: StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:_  

>>>I modified manually "appsettings.Deployment.json" and it worked.

## Version

Preview version

## Browser

- [X ] Chrome

## OS

- [X] Windows

## To Reproduce

Getting this error while running " ./Scripts/deploy.ps1" -> Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
lubuild succeeded

## Expected behavior

Successful deployment in Azure portal as per documentation -> https://docs.microsoft.com/en-us/composer/how-to-publish-bot

## Screenshots
![image](https://user-images.githubusercontent.com/45286102/80359221-23ca7280-889b-11ea-8db0-57e85f24b098.png)

**Comment by zidaneymar** [comment]
@manvendrautralia Hi, thanks for your feedback. Have your tried 'az login' before running the deploy.ps1 script? You should login to the Azure then run 'create.ps1' to create related Azure resources firstly, and then run 'deploy.ps1' to deploy your source code (bot dialog files).

**Comment by manvendrautralia** [comment]
So I did these:

>>> az login
>>> az account set --subscription "XXXXXXXX"

As mentioned above, I was able to deploy after manually adding LUIS keys in "appsettings.Deployment.json".

**Comment by zidaneymar** [comment]
> As mentioned above, I was able to deploy after manually adding LUIS keys in "appsettings.Deployment.json".

I see, you add the luis key to composer customized settings. 
'deploy' script also accepts luis authoring key and luis authoring region as parameters.
@hibrenda  Currently we don't support the customized luis authoring key for deployment, composer will write your luis authoring key to settings/appsettings.json, but deploy script doesn't search keys in that file. 

```
Param(
	[string] $name,
	[string] $environment,
	[string] $luisAuthoringKey,
	[string] $luisAuthoringRegion,
	[string] $language,
	[string] $projFolder = $(Get-Location),
	[string] $botPath,
	[string] $logFile = $(Join-Path $PSScriptRoot .. "deploy_log.txt")
)
```

**Comment by ericchansen** [comment]
@manvendrautralia Can you please provide an example of your configuration file? I'd like to know the structure of your JSON.

**Comment by manvendrautralia** [comment]
> @manvendrautralia Can you please provide an example of your configuration file? I'd like to know the structure of your JSON.
> 
> This is tied to issue #2858.

{
  "MicrosoftAppId": "XXXXXXX",
  "MicrosoftAppPassword": "XXXXXXX",
  "bot": "ComposerDialogs",
  "luis": {
    "authoringKey": "XXXXXXX",
    "endpointKey": "XXXXXXX",
    "region": "westus"
  },
  "blobStorage": {
    "connectionString": "DefaultEndpointsProtocol=https;AccountName=XXXXXXXtesting;AccountKey=XXXXXXX;EndpointSuffix=core.windows.net",
    "container": "transcripts"
  },
  "applicationInsights": {
    "InstrumentationKey": "0fdfab58-487f-476f-b39f-XXXXXXX"
  },
  "cosmosDb": {
    "authKey": "XXXXXXX",
    "collectionId": "botstate-collection",
    "cosmosDBEndpoint": "https://XXXXXXX-testing.documents.azure.com:443/",
    "databaseId": "botstate-db"
  }
}

**Comment by manvendrautralia** [comment]
> @manvendrautralia Can you please provide an example of your configuration file? I'd like to know the structure of your JSON.
> 
> This is tied to issue #2858.

{
  "MicrosoftAppId": "XXXXXXX",
  "MicrosoftAppPassword": "XXXXXXX",
  "bot": "ComposerDialogs",
  "luis": {
    "authoringKey": "XXXXXXX",
    "endpointKey": "XXXXXXX",
    "region": "westus"
  },
  "blobStorage": {
    "connectionString": "DefaultEndpointsProtocol=https;AccountName=XXXXXXXtesting;AccountKey=XXXXXXX;EndpointSuffix=core.windows.net",
    "container": "transcripts"
  },
  "applicationInsights": {
    "InstrumentationKey": "{
  "MicrosoftAppId": "XXXXXXX",
  "MicrosoftAppPassword": "XXXXXXX",
  "bot": "ComposerDialogs",
  "luis": {
    "authoringKey": "XXXXXXX",
    "endpointKey": "XXXXXXX",
    "region": "westus"
  },
  "blobStorage": {
    "connectionString": "DefaultEndpointsProtocol=https;AccountName=XXXXXXXtesting;AccountKey=XXXXXXX;EndpointSuffix=core.windows.net",
    "container": "transcripts"
  },
  "applicationInsights": {
    "InstrumentationKey": "XXXXXXX"
  },
  "cosmosDb": {
    "authKey": "XXXXXXX",
    "collectionId": "botstate-collection",
    "cosmosDBEndpoint": "https://XXXXXXX-testing.documents.azure.com:443/",
    "databaseId": "botstate-db"
  }
}
"
  },
  "cosmosDb": {
    "authKey": "XXXXXXX",
    "collectionId": "botstate-collection",
    "cosmosDBEndpoint": "https://XXXXXXX-testing.documents.azure.com:443/",
    "databaseId": "botstate-db"
  }
}

**Comment by cwhitten** [comment]
@manvendrautralia are you still experiencing issues? Can you try this on version 1.1.1?

Thanks

**Comment by tdurnford** [comment]
Close due to inactivity. @manvendrautralia  if you are still having an issue with this please feel free to reopen.
