### ISSUE TITLE
The "New Trigger" and "New Dialog" are missing from the Dialog navigation pane

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2788]
## Describe the bug
The "New Trigger" and "New Dialog" are missing from the Dialog navigation pane.

![image](https://user-images.githubusercontent.com/32497439/80402880-7d1eab80-8873-11ea-92c9-97b449da26cd.png)

## Version
The most recent master branch (updated by April 27 at 9 am)

## Browser
- [x] Chrome

## OS
- [x] Windows

## To Reproduce

1. Install Composer using the latest master branch
2. Create an echo bot using the template
3. Go to "Design Flow" and see the error

## Expected behavior
Both the "New Trigger" and "New Dialog" should appear in the Dialog navigation pane.

**Comment by cwhitten** [comment]
Hi @zxyanliu - this is by design. You use the Add button at the top now.

**Comment by zxyanliu** [comment]
I see. Thanks!
