### ISSUE TITLE
Runtime middleware configuration 

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#2789]
Some feedback wasn't picked up before the PR that made the runtime configurable got merged.  https://github.com/microsoft/BotFramework-Composer/pull/2679#event-3276572882

The changes mentioned in the comments are...

 - **The TelemetryLoggerInitializer middleware should always be added to the adapter pipeline** (i.e. not have it added based on the UseTelementryLoggerMiddleware setting).  This setting should be removed. Then the telemetry settings (logActivities and logPersonalInformation) are used to control if further telemetry is logged, using the TelemetryLoggerMiddleware internally.  Telemetry capture is only ever enabled if a developer sets their App Insights instrumentation key and so all we do with this setting right now is mean they have to enable two things to turn on telemetry (it also can give the false impression that all telemetry is off if you have this set to false, which is not true, telemetry will just be incomplete).

 - **Right now the UseInspectionMiddleware setting is adding the TelemetryInitializerMiddleware, instead of adding the InspectionMiddleware**.  https://github.com/microsoft/BotFramework-Composer/blob/dff6dec2f5a7046200f0d0240129be85be2d7e40/BotProject/Templates/CSharp/Startup.cs#L57-L63
This needs to be fixed and then the TelemetryInitializerMiddleware needs to be added to the pipeline too (without a conditional setting as per above).

**Comment by zidaneymar** [comment]
Hi @garypretty, I create a draft PR fixing this issue, could you please help review it?

**Comment by hibrenda** [comment]
This issue also track the configurable section and all related settings to compose default settings page.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2800
