### ISSUE TITLE
Bot Responses and User Input navigation pane not aligned

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2791]
## Describe the bug
This is not a functional issue. It's just that the navigation panes are not aligned as they used to be. 
In my personal opinion, the previous alignment looks better. 

* Current **Bot Responses** navigation pane
![image](https://user-images.githubusercontent.com/32497439/80419955-dea04380-888e-11ea-9ddd-29fa97ad3cad.png)

* Previous **Bot Responses** navigation pane
![bot-responses](https://user-images.githubusercontent.com/32497439/80420639-ee6c5780-888f-11ea-8712-ec9b4918c5f0.png)

* Current **User Input** navigation pane
![image](https://user-images.githubusercontent.com/32497439/80420007-f5df3100-888e-11ea-8cee-9a4212bb2361.png)

* Previous **User Input** navigation pane
![zipcode-regex-entity](https://user-images.githubusercontent.com/32497439/80420857-54f17580-8890-11ea-96c5-a91b6416b456.png)

## Version
The latest master branch.

## Browser
- [x] Chrome

## OS
- [x] Windows

## To Reproduce

1. Go to 'Bot Responses...'/ 'User Input'
2. See the described issues. 

## Expected behavior
Should be aligned.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2799
