### ISSUE TITLE
Validation issues - can we get some features back?

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2792]
## Describe the bug
* Users are NOT able to expand the incomplete error message in the Language Generation inline editor. 
![image](https://user-images.githubusercontent.com/32497439/80429178-52971780-88a0-11ea-816d-639e051058a7.png)

* Users are NOT able to expand the incomplete error message in the Language Understanding inline editor. 
![image](https://user-images.githubusercontent.com/32497439/80429382-c9ccab80-88a0-11ea-815b-dd588c9f21fa.png)

* Users are able to expand the incomplete error message but need a link pointing to the [Adaptive Expressions](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/common-expression-language) reference doc.
![image](https://user-images.githubusercontent.com/32497439/80429634-698a3980-88a1-11ea-9499-e55b51990ecb.png)

## Version

Latest master branch

## Browser
- [x] Chrome

## OS
- [x] Windows

## To Reproduce

1. Produce an error on purpose in the LG/LU inline editor
2. Click on the generated error message
3. See error

## Expected behavior
- Should allow users to expand the error message.
- Should provide corresponding reference docs for syntax. 

## Additional
What we used to have:
* **lg**
![lg-inline-error](https://user-images.githubusercontent.com/32497439/80430246-f1247800-88a2-11ea-95e0-c7b353fccc72.png)

* **lu**
![lu-inline-error](https://user-images.githubusercontent.com/32497439/80430250-f5509580-88a2-11ea-89d5-d4909c6d11e9.png)

* **Expressions**
![expand-expression-error](https://user-images.githubusercontent.com/32497439/80430252-f71a5900-88a2-11ea-8e42-6f22337e07a8.png)

**Comment by a-b-r-o-w-n** [comment]
@beyackle Do you have thoughts on this? I know that this change was introduced to address some a11y issues, but I don't have all the context. Could you take a look at this and recommend an approach?

**Comment by beyackle** [comment]
If I remember right, the approach we decided on was to get rid of the reveal arrow and just have the message be expanded all the time (the messages are never so long that this would be a problem; boxes below them just get pushed downward). So the problem here is that they're showing up shrunk in the first place.

**Comment by cwhitten** [comment]
@beyackle can you investigate to see why parts of the elements are hidden?

**Comment by beyackle** [comment]
Just noticed that PR doesn't also add the docs link to the Condition field. I'll fix that.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2811

**Comment by beyackle** [comment]
This isn't done yet - there still needs to be a fix to the need for a link to the Adaptive Expressions doc. I have a PR for that too that I'll link here.
