### ISSUE TITLE
Inaccurate warning message when delete a dialog

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#2795]
## Describe the bug
When trying to delete dialog B which is called by dialog A and call dialog C inside, the warning message shows it is used by A and C, which is confusing. 
![image](https://user-images.githubusercontent.com/16643193/80455930-3c9c5c00-895f-11ea-8243-8de77594fb73.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. create dialog A, B, C
2. make A start dialog B, B start dialog C
3. delete dialog B
4. warning shows B is currently used in both A and C

## Expected behavior
warning can show B is currently used in A

**Comment by cwhitten** [comment]
No short term plans to improve this at the moment. Closing.
