### ISSUE TITLE
Immediate intent recognizer without  luis trigger

### ISSUE THREAD

**Issue by nvikey** [microsoft/BotFramework-Composer#2797]
Do we need to create one trigger for each intent? If yes, then I think, we need to re-write some code blocks in all the intents(say 80 intent in my case), which is not an easier way. Please confirm.

In our case, we pass the recognized intents to a SharePoint list and filter a value to give it as an answer to the user. This is the same for each intents. So creating 80 triggers for 80 intents is difficult.

Or is there any way how to identify intents without intent recognized trigger?

**Comment by cwhitten** [comment]
Hi @nvikey - the answer to your initial question is yes, you create an intent trigger for each intent you have defined in your language model. 

I believe I understand your scenario enough to suggest that the 80 intents call the same fulfillment dialog, say `CallSharepointDialog` that accepts the recognized intent as a parameter, and `CallSharepointDialog` can do the work of calling the service with the appropriate payload. In this case you would have 80 very shallow intents that all call the same dialog with different parameters.

Alternatively you can avoid defining any intent triggers and funnel _everything_ into the `UnknownIntent` trigger, which will act as a fallback intent where you can extract and pass whatever information you need to the Sharepoint service.
