### ISSUE TITLE
Bot gets created in the wrong folder

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#2798]
When creating a new bot and not changing the location folder (as it was ok from last time), the bot gets created in the folder C:\Users\<username>\Documents\Composer

## Version

SHA displays test

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new bot
2. Select Create from template, Echo Bot and click next
3. Leave location as is and click next
4. Check location of bot in file explorer

## Expected behavior

Storing in correct folder

**Comment by a-b-r-o-w-n** [comment]
@cxbuilders Can you provide the version of Composer that you are using? The specific git commit is most helpful.

**Comment by cwhitten** [comment]
@liweitian we see some odd behavior here when creating a new bot in another directory. We're seeing validation errors that shouldn't exist.

![Screen Shot 2020-04-28 at 9 50 13 AM](https://user-images.githubusercontent.com/1156704/80514672-adc71980-8935-11ea-90c3-37a9cfcd1a50.png)

**Comment by cxbuilders** [comment]
git describe --always -> ac1e959b

Teh application SHA on teh ABout page always just displays test. Guess that's a bug, or am I missing something?

**Comment by liweitian** [comment]
> @liweitian we see some odd behavior here when creating a new bot in another directory. We're seeing validation errors that shouldn't exist.
> 
> ![Screen Shot 2020-04-28 at 9 50 13 AM](https://user-images.githubusercontent.com/1156704/80514672-adc71980-8935-11ea-90c3-37a9cfcd1a50.png)

@cwhitten fixed in the above PR

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2826
