### ISSUE TITLE
Skill scenario is broken - can't set skill endpoint

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#2801]
## Describe the bug

When I try to add a Begin a skill dialog action. 

The skill endpoint is not auto filled and can not be edit. 

![image](https://user-images.githubusercontent.com/32191031/80469275-e9340900-8972-11ea-94d1-4f907eac5bc0.png)

This is the two manifest I used to test:
https://yuesuemailskill0207-gjvga67.azurewebsites.net/manifest/manifest-1.0.json 
http://localhost:3983/manifest.json
```
{
    "$schema": "https://schemas.botframework.com/schemas/skills/skill-manifest-2.0.0.json",
    "$id": "TodoSimple",
    "name": "Todo skill",
    "version": "1.0",
    "description": "This skill echoes whatever the user says",
    "publisherName": "Microsoft",
    "privacyUrl": "https://myskill.contoso.com/privacy.html",
    "copyright": "Copyright (c) Microsoft Corporation. All rights reserved.",
    "license": "",
    "iconUrl": "https://myskill.contoso.com/icon.png",
    "tags": [
        "sample",
        "echo"
    ],
    "endpoints": [
        {
            "name": "default",
            "protocol": "BotFrameworkV3",
            "description": "Production  endpoint for SkillBot.",
            "endpointUrl": "http://localhost:3983/api/messages",
            "msAppId": "303d5b8-a3b6-4d50-82c7-af10a8a96b20c"
        }
    ],
    "activities": {
        "message": {
            "type": "message",
            "description": "A message activity containing the utterance that the skill will echo back to the user"
        }
    }
}
```

@tdurnford 
## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
The SkillDialog schema changed and the Skill form template needs to be updated:

https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/packages/server/schemas/sdk.schema#L13962

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2816
