### ISSUE TITLE
How to call custom c# code using custom runtime

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#2804]
I was wondering what the proposed methodology is on integrating custom c# code into the composer bot. I have enabled the custom runtime config and hooked up Visual studio debugger, so it's all ready to go.

Which mechanism should I use for this and how is that implemented. Custom Events? Or creating a dialog (will that appear in Composer)?

Hope someone has an answer on this, since so far making use of the hybrid approach is not yet clear to me.

**Comment by cwhitten** [comment]
Calling custom code can be achieved in two different ways:

1. Over the network: creating a Azure function and calling the function from an HTTPAction
2. Local Adaptive SDK extensions: writing this C# code as a custom action in your bot's code, and updating the schema used when the bot is loaded in Composer to express this capability. This requires your ejecting the runtime template and customizing it, and running the bf-cli `dialog:merge` tool to generate a schema representing your custom runtime capabilities. While this will be the preferred approach, we don't yet have documentation to help users achieve this just yet, but will in the coming weeks.

**Comment by cxbuilders** [comment]
@cwhitten Is there any news on the documentation for the code action component? Tried to figure it out, but that takes a lot of time, so waiting for the docs to be there, or maybe a quick instruction would help as well?
