### ISSUE TITLE
Revisit option to single-click list items

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2810]
Options:

1, Convert one of the rows field to a link
2. Add a new column - "Open" or some derivation of this

I like #1

**Comment by beyackle** [comment]
Agreed. #2 was the first idea I had, but #1 makes more sense.

**Comment by beyackle** [comment]
Okay, this turns out to be an easy fix. I'll have a PR up for it shortly.

**Comment by beyackle** [comment]
Could we get this added to some board or other so we can mark it in-review/closed as appropriate?

**Comment by cwhitten** [comment]
done!
