### ISSUE TITLE
Composer report error when select "false" in if-else step

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#2818]
## Describe the bug
Composer report error when select "false" in if-else step
![image](https://user-images.githubusercontent.com/16643193/80559795-51392c80-8a11-11ea-8935-919e7277d5d7.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. create a if-else step
2. choose bool for condition, select "false"

## Expected behavior
Should not report error for this case

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2821
