### ISSUE TITLE
Publish & Create resource script are missing the \runtime directory

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#2828]
## Describe the bug

Since having the new /runtime directory for the c# code, the publish and create resource scripts fail as the scripts folder is now under /runtime

1. Go to Configuration -> Publish
2. Click on Create Azure Resources
3. Run scripts

## Version

843d639a

**Comment by hibrenda** [comment]
you can goto runtime folder to run the script. could you have a try ?

**Comment by cxbuilders** [comment]
that's of course what I do now, just filing the bug here..

**Comment by hibrenda** [comment]
Do you create a new bot and copy all the legacy bot asset and then start the bot to eject the new runtime?

**Comment by cxbuilders** [comment]
I don't understand. This is clearly a bug, why would it be a question?

**Comment by darrenj** [comment]
The UX is missing the runtime folder on the directory - needs updating

![image](https://user-images.githubusercontent.com/33519520/80797961-0ba86b00-8b9b-11ea-85a8-fd3992d00c4d.png)

**Comment by cxbuilders** [comment]
all fixed / irelevant with new scripts
