### ISSUE TITLE
UX Issue when creating new dialog using Add button

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#2833]
## Describe the bug
When I create a new dialog using the "Add" dropdown, then click the "BeginDialog" trigger, it opens a blank page and I can't edit the dialog. If I create the dialog from within a "Begin a new dialog" action with the "Create a new dialog", I can click the BeginDialog trigger and edit it as expected.  

## Version

Application SHA
test
SDK runtime packages
4.7.0-preview-191208-1

(master branch as of 4/28/20)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by hibrenda** [comment]
sounds like you hit https://github.com/microsoft/BotFramework-Composer/issues/2775. it has already been fixed.
