### ISSUE TITLE
Clean out unused code in assetManager model

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#2835]
There is some code in the assetManager model that overlaps with the eject function and is most likely not used anymore. We should clean this out and/or make sure it is in alignment with the way eject works.

In particular:

* copyRuntimeTo()
* runtimeTemplates[]
* getProjectRuntime()

**Comment by boydc2014** [comment]
Hey, @benbrown , i cleaned it in this https://github.com/microsoft/BotFramework-Composer/pull/2805, my plan is to include your biolerplate also with plugin, make sense?
