### ISSUE TITLE
Send a response action gets created with Send an Activity as the name

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#2841]
![Screen Shot 2020-04-29 at 4 32 27 PM](https://user-images.githubusercontent.com/50963385/80656838-07fbd380-8a37-11ea-8dc2-e95858530c73.png)
When a Send a response action gets created, the name field on the property pane says Send an Activity. But the node title says Send a response.

**Comment by cwhitten** [comment]
I've also seen in a couple areas that overridden labels are not getting applied. See attached. Adaptive Dialog should actually say the name of the Bot (TodoWithLuis)

![Screen Shot 2020-05-04 at 9 49 18 AM](https://user-images.githubusercontent.com/1156704/80991276-9c29ba00-8dec-11ea-8153-77260a4e3e0b.png)

**Comment by a-b-r-o-w-n** [comment]
@cwhitten that particular issue is due to malformed dialog data.

**Comment by a-b-r-o-w-n** [comment]
@sangwoohaan what is the suggestion here? Which label should we use?

**Comment by cwhitten** [comment]
@a-b-r-o-w-n the example was a vanilla creation from sample. it's unclear what is malformed.

**Comment by a-b-r-o-w-n** [comment]
The sample has 

```
{
  $designer: {
    $designer: {
      ...
    }
  }
}
```

I will update it.
