### ISSUE TITLE
Create Azure Resources fails

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#2843]
## Describe the bug

For a new bot when running Create Azure Resources it fails with the following error:
Set-Location: Cannot find path 'C:\Temp\BotFrameworkComposer\BotFramework-Composer\Composer\plugins\localPublish\hostedBots\15143.22364462799' because it does not exist.

## Version

75362387

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X ] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new EchoBot
2. Goto Settings, Publish, Create Azure Resources and fill in details
3. Copy first line (cd .....) and run in PowerShell

**Comment by cxbuilders** [comment]
Figured out that the the bot in the hostedBots folder gets created after you run the bot once. However I have an existing bot and installed an new version of composer. I cannot run the bot as it uses Luis, so needs to be deployed first. Bit of catch22

**Comment by hibrenda** [comment]
@cxbuilders  you can create a new bot and just copy the bot asset files to replace the new created one. then click start bot. it will eject the new runtime structure for you. by the way make sure you include following in the setting page before you click the start button. otherwise you will hit https://github.com/microsoft/BotFramework-Composer/issues/2763
```
"runtime": {
"customRuntime": false,
"path": "",
"command": ""
},
```

**Comment by luhan2017** [comment]
@cxbuilders , same as issue #2858. you could try our new node js deployment script, which is placed in your created bot folder, please follow the readme and run scripts under script folder.

**Comment by luhan2017** [comment]
removed P0 and R9-RC since we are deprecating the powershell script.

**Comment by cxbuilders** [comment]
All fixed
