### ISSUE TITLE
Consolidate labeling in the property & visual editors

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#2845]
![Screen Shot 2020-04-29 at 12 52 57 PM](https://user-images.githubusercontent.com/50963385/80748429-c2441700-8ad9-11ea-9f82-1e28dfe87038.png)

Currently, we are displaying the default name of an action in the secondary label. As a result, when you first created an action node you get duplicate names in the main label and the secondary label. Let's change the secondary label content to the raw control name. i.e. Microsoft.IfCondition in the screenshot above.

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2930
