### ISSUE TITLE
A minor issue in the Empty Bot example

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2849]
## Describe the bug
I created an EmptyBot using the EmptyBot sample. 
There is a **Send a response** action (which does not exist in the previous releases) in the Greeting's trigger. 
I tried to edit the LG in the **Send a response** action and generated an error. 
I was updating this [doc](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-create-bot). 

![error](https://user-images.githubusercontent.com/32497439/80761706-e874b180-8aef-11ea-91fe-01587fcefe6e.gif)

## Version
Latest master branch.

## Browser
- [x] Chrome

## OS
- [x] Windows

## To Reproduce

1. Create a bot using the Empty Bot template.
2. Click on 'Greeting' trigger
3. Select the **Send a response** action
4. Edit the LG file in the inline editor
5. See the error

## Expected behavior
Should be able to edit the LG file in the **Send a response** action.
Proposed solution: Should get rid of this pre-defined action. It is a template defined as a common template (see **Bot Responses** -> **All**)

## Additional context
The **Send a response** action is something new. There is not such an action pre-defined in the sample in the previous releases.

**Comment by cwhitten** [comment]
Todo:

- Fix the EmptyBot & EchoBot samples to utilize the inline SendActivity template and _call_ the resuable WelcomeUser lg template
- In all samples, change name of reusable LG template from help to WelcomeUser and update any callsites where help is invoked to WelcomeUser

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2864
