### ISSUE TITLE
[DCR] Interchangeable Runtimes: definition, requirements, commands and code impact

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/BotFramework-Composer#2852]
Currently composer supports a single runtime for Azure deployment, local ejection and local execution. The only choice of runtime is in C# and using Asp.Net Core web apps. Conceivably, Composer should be runtime agnostic, and as should be Composer code with the exception of the plugins. At the code level, this means evaluating lots of assumptions such as removing direct calls to dotnet build / run. At the extensibility and artifact level, the implications of interchangeable runtimes are that each runtime needs a different set of commands and actions. Thus, runtimes need a common mechanism to define those actions, since Composer needs to answer questions such as 'How do I build this runtime?' 'How do deploy this runtime to a non-azure environment?'.

The scope of this DCR and proposal is:

- **Definition of a runtime manifest along with its axiomatic actions:** What are the set of commands that runtimes should provide for appropriate flexibility? Right now init command, build command and package/publish command could be a good start to ignite discussion
- **Definition of interface defining a physical instance of the runtime in composer:** At the code level, a well defined Runtime interface that includes access to the manifest and potentially could be used as an insertion point for custom code
- **Cleanup of runtime specific code** from the Composer codebase

Given that the Javascript runtime is coming close to ready and that we are preparing for multiple hosting environments such as Azure WebApps and Azure functions, this is a great timing for this DCR.

The foundational work being done as part of DCR https://github.com/microsoft/BotFramework-Composer/issues/2840 also lays a solid foundation for multi-runtime support from a structural point of view.

**Comment by carlosscastro** [comment]
@cwhitten @benbrown FYI this is Post R9 but wanted to run it by you early.

**Comment by cwhitten** [comment]
@carlosscastro closing as we changed direction a bit
