### ISSUE TITLE
Emit a custom event - Event name - choosing built-in event option freezes and crashes the browser window

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#2853]
## Browser

- [x] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create Emit a custom event action node
2. (On the property editor) Under Event name field, choose built-in event option from the dropdown on the right
3. As soon as you click the option, the browser window freezes.

**Comment by a-b-r-o-w-n** [comment]
fixed in #2871
