### ISSUE TITLE
Ability to rename triggers

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#2857]
## Is your feature request related to a problem? Please describe.

When creating new triggers it is not possible to rename them. Especially wjen using multiple custom events to trigger dialogs the trigger name Custom event is not very useful.

## Describe the solution you'd like

Ability to rename triggers, probably by clicking on the trigger name when editing the trigger, or / and by clicking on the dots next to the trigger.

**Comment by cwhitten** [comment]
tracking here: https://github.com/microsoft/BotFramework-Composer/issues/1361

closing this as a duplicate
