### ISSUE TITLE
ToDo Sample has LG issue

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#2859]
## Describe the bug

When creating a new project based on the Todo with LUIS sample. When you type `Show` you get an LG error.

```
viewitem.en-us.lg:[Error] line 19:0 - line 19:14: Invalid template name. Template name should start with letter/number/_ and can only contains letter/number/./_.

[Error] line 20:0 - line 20:32: Unexpected content. Expecting a comment, template definition, import statement or option definition.

[Error] line 22:0 - line 22:17: Invalid template name. Template name should start with letter/number/_ and can only contains letter/number/./_.

[Error] line 23:0 - line 23:38: Unexpected content. Expecting a comment, template definition, import statement or option definition.

[Error] line 25:0 - line 25:18: Invalid template name. Template name should start with letter/number/_ and can only contains letter/number/./_.

[Error] line 26:0 - line 26:40: Unexpected content. Expecting a comment, template definition, import statement or option definition.

[Error] line 18:8 - line 18:13: [showLists]Expecting ‘```’ to close the multi-line block.

```

## Version

test
4.7.0-preview-191208-1

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new ToDo with LUIS project
2. Publish
3. Type `Show`

## Expected behavior

Works as expected

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/80804132-2b945a80-8bac-11ea-9a5b-36144c3072ed.png)

**Comment by beyackle** [comment]
Taking a look at this now. From the error messages it looks like a problem in just the one LG file.
