### ISSUE TITLE
Composer Electron app - start bot fails (bot has LU content)

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2862]
# Describe the bug
- Created a new bot
- Add some OnIntent triggers with LU content
- Provide LUIS authoring key and click on start bot

## Version
- Composer app. 
Application SHA
test
SDK runtime packages
4.7.0-preview-191208-1

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch composer electron app
2. Create a new bot
3. Add one or more triggers with LU content
4. Click startbot
5. Provide LUIS authoring key

## Expected behavior
Bot can start

## Screenshots
![image](https://user-images.githubusercontent.com/20918136/80831135-1402a500-8b9f-11ea-9151-cc27b9e08c57.png)

## Additional context
```
Sorry, something went wrong with connecting bot runtime

EPERM: operation not permitted, mkdir 'C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\build\plugins\localPublish\hostedBots'
```

**Comment by cwhitten** [comment]
@srinaath is looking at this

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2894
