### ISSUE TITLE
Composer electron app freezes when clicking on ConfirmInput

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2867]
##  Describe the bug

Add a confirm input action to canvas. Select it to view the form editor, click on `Bot asks` node on the flow canvas, click on `User input` in the flow canvas.

## Version
Composer electron app latest build.

Application SHA
test
SDK runtime packages
4.7.0-preview-191208-1

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot from scratch
2. Select the welcome trigger
3. After the send activity node, add a confirm input node
4. Click on either of the `Bot Asks` or `User input` node in the flow canvas to view the form editor.

## Expected behavior
App does not freeze.

**Comment by cwhitten** [comment]
This is reproduced on web. So far I've found the following:

```bash
for (var g = 0, x = c, w; g < A; ++g) {
      switch (w = S[g].call(B, d, x, e, h, a, m, b, v, n, q)) {
        case void 0:
        case !1:
        case !0:
        case null:
          break;

        default:
          x = w;
      }
    }

Paused before potential out of memory crash
```

I've been able to track this down to https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/packages/extensions/adaptive-form/src/utils/resolveFieldWidget.ts, this is getting invoked infinitely.. @a-b-r-o-w-n any ideas?

**Comment by a-b-r-o-w-n** [comment]
I'll fix this tomorrow.

**Comment by vishwacsena** [comment]
Also happens for HttpAction

**Comment by vishwacsena** [comment]
I'm unable to make progress on my build demo videos. @a-b-r-o-w-n or @cwhitten can you help me get set up with a patch? Thanks much!

**Comment by a-b-r-o-w-n** [comment]
Looking at this now.

**Comment by a-b-r-o-w-n** [comment]
@vishwacsena Can you try on that PR I created?

**Comment by vishwacsena** [comment]
@a-b-r-o-w-n building now...
