### ISSUE TITLE
Wrong runtime directory

### ISSUE THREAD

**Issue by EPinci** [microsoft/BotFramework-Composer#2868]
## Describe the bug

In the "bot runtime settings", once activated the custom runtime, clicking on the link "get a new copy of the runtime code" and selecting "csharp" results in an error dialog with:

```
No such dir C:\Users\Edoardo\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\BotProject\Templates\CSharp}
```

## Version

d749977

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [X] Windows app

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

**Comment by tonyanziano** [comment]
Working with @benbrown to fix this

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2887
