### ISSUE TITLE
Copy paste is broken

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2869]
## Describe the bug
Copy (or cut) followed by paste is broken in master. Paste results in a blank node inserted on canvas. 

Can repro this in both latest master branch as well as in latest electron app

## To Reproduce

1. Create a flow
2. Select one or more actions
3. Click on cut or copy
4. Switch to a different flow and click on [+] -> paste

**Comment by yeze322** [comment]
investigating
