### ISSUE TITLE
Start bot broken for a bot that has LU information 

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#2870]
## Describe the bug

Latest in master. 
Open a bot that has LU information
Click Start bot. 
App is stuck. See attached video. 

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open attached bot.
2. Click on start bot

[Sample bot](https://github.com/vishwacsena/composer-build-2020/tree/master/DDayBot-1)

[Repro video.zip](https://github.com/microsoft/BotFramework-Composer/files/4569466/Repro.video.zip)

**Comment by boydc2014** [comment]
After some digging, the start bot feature in Windows is now broken, see https://github.com/microsoft/BotFramework-Composer/pull/2861#issuecomment-623077033. 

Can you use Mac to work around now?

**Comment by boydc2014** [comment]
@vishwacsena  can you try https://github.com/microsoft/BotFramework-Composer/pull/2873

**Comment by cwhitten** [comment]
i went ahead and took https://github.com/microsoft/BotFramework-Composer/pull/2873
