### ISSUE TITLE
QnAMaker form not rendering

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2878]
See attached.
![Screen Shot 2020-05-04 at 8 04 34 AM](https://user-images.githubusercontent.com/1156704/80980782-e9525f80-8ddd-11ea-95ad-c236cb185cdb.png)

**Comment by a-b-r-o-w-n** [comment]
@vishwacsena The QnAMakerDialog is missing from our latest schema.

**Comment by vishwacsena** [comment]
@a-b-r-o-w-n The schemas moved out of adaptive and into the QnA maker library .. they are here. https://github.com/microsoft/botbuilder-dotnet/tree/master/libraries/Microsoft.Bot.Builder.AI.QnA/Schemas

I'm not familiar with how you pick up the component schema definitions. Does this work or do you need an SDK side fix?

**Comment by a-b-r-o-w-n** [comment]
I think we just run `bf dialog:merge` in the sdk repo. @luhan2017 Can you update the schema with the qna dialog?
