### ISSUE TITLE
Dynamic flow positioning layout in visual editor

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2879]
Currently the flow is positioned statically on the canvas. This is centered and is optimized for small, mostly linear flows. Flows that grow in breadth are unable to utilize the space given to the flow editor and requires users to scroll. 

An optimization I'd like to add is to reposition the flow to be left-aligned instead of centered when a flow with breadth is rendered, or a combination of gradual left alignment as the breadth increases in a flow, culminating in a complete left-alignment.

**Comment by yeze322** [comment]
I can implement the 'gradual left alignment'.
