### ISSUE TITLE
Does main dialog have a .Main extension now?

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2880]
In R8 and previous releases, the main dialog has a **.Main** extension after creation. This feature is gone for the latest master branch. Are we deprecating this feature for this release? 

**Screenshots:** 

* Previous release: 
![main-and-child-dialog](https://user-images.githubusercontent.com/32497439/80985508-2b7e9f80-8de4-11ea-97c5-a3b0fcbddb1d.png)

* Current master branch:
![image](https://user-images.githubusercontent.com/32497439/80985692-6680d300-8de4-11ea-851e-01859c322093.png)

**Comment by cwhitten** [comment]
Hi @zxyanliu. "Main" is no longer represented in the UI. It is only the Bot's name.

**Comment by zxyanliu** [comment]
Ok. So the dialog on top is the main dialog, right? 
I will update this in the [dialog concept](https://docs.microsoft.com/en-us/composer/concept-dialog) article. Thanks.
