### ISSUE TITLE
Cannot correctly edit a form header

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#2881]
If you backspace on the editable field, it resets to the original value

Additionally, the field is not populated with the correct overridden value when it exists. (See attached)

![Screen Shot 2020-05-04 at 9 36 38 AM](https://user-images.githubusercontent.com/1156704/80990174-d1cda380-8dea-11ea-993c-a877e9766a8b.png)

**Comment by a-b-r-o-w-n** [comment]
duplicate of #2662
