### ISSUE TITLE
Azure deployment of Composer bot results in LUIS configuration issue

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#2886]
## Describe the bug

Testing a Composer based Bot that uses LUIS locally works fine however when publishing to Azure *(using previous publish script) or the [new publish capability](https://github.com/microsoft/BotFramework-Composer/pull/2733) results in a Bot that when tested through Emulator that works fine until LUIS is used at which point it throws this error

```
“” is not a valid LUIS subscription key.
```

## Version

`test`
master and [this branch](https://github.com/microsoft/BotFramework-Composer/pull/2733)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

- Publish any Bot project that uses LUIS to Azure
- I am using [this project](https://github.com/microsoft/botframework-skills/tree/preview-build2020/skills/declarative/whoskill) with a change to include the `runtime` element as per recent changes

## Expected behavior

LUIS recognizer works as expected

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/81001772-23544d80-8e40-11ea-8519-99f07fe78b89.png)

## Additional context

Can share my App Service for debugging if of help.

**Comment by darrenj** [comment]
Update. I deleted the existing RG in case it was causing problems and created a new deployment which showed the same issue.

Observations (with the latest azure publishing code)

- DeploymentTemplates no longer exists within the runtime\azureWebApp folder or indeed anywhere within the hostedBots folder hierarchy. I sourced and manually put within the runtime\azureWebApp folder and ran create.ps1
- New publishing experience isn't clear that you need to have an existing RG and it won't kick that process off itself. I tried to see if it would but got a confusing {"error":{"code":"BadArgument","message":"Failed to parse azure account information object object."}} error.
- FYI create.ps1 uses a now deprecated AZ CLI approach group deployment versus deployment group
- Publishing worked to the App Service however I get the same LUIS error noted above

**Comment by zidaneymar** [comment]
Hi @darrenj , I test the publishing feature with lastest master todo luis bot but can't repro. Here are my repro steps:

1. use this command to create resources:

`node provisionComposer.js --subscriptionId=<subId> --name=ToDoLuisTestBotQika2 --appPassword=<password> --environment=dev --createLuisAuthoringResource false --createCosmosDb false --createStorage false --createAppInsights false`

2. copy the results to azure publish plugin and add your AuthoringKey to the json:

![image](https://user-images.githubusercontent.com/9328933/81143603-cfaf4480-8fa4-11ea-8b3b-777390f922b5.png)

3. publish the bot.

 
![image](https://user-images.githubusercontent.com/9328933/81143665-f0779a00-8fa4-11ea-9725-232d6c5ca22b.png)

**Comment by luhan2017** [comment]
@darrenj , we are deprecating the powershell create and deploy scripts, could you try our new node js deployment script, which is placed in your created bot folder, please follow the readme and run scripts under script folder.

**Comment by VanyLaw** [comment]
Hi @darrenj, we will not support the powershell script anymore, so, could you please try the provision script (js script) under botfolder/script to create the azure resources? We also have a readme about the provision in botfolder for the new bot. By the way, We will figure out how to do the migration for the old bot in https://github.com/microsoft/BotFramework-Composer/issues/2625

**Comment by darrenj** [comment]
@benbrown and I were debugging this yesterday. Through kudu I was able to observe that there is `appsettings.json`, `appSettings.Deployment.json` and `ComposerDialogs/settings/appSettings.json` :-o

looking at `appSettings.json` it had the following. Note that luis->endpointKey is blank and is the root cause of the above issue. Manually setting it resolve the issue.

```json
{
    "bot": "ComposerDialogs",
    "root": "ComposerDialogs",
    "applicationInsights": {
        "InstrumentationKey": "REDACTED"
    },
    "cosmosDb": {
        "cosmosDBEndpoint": "<endpoint url>",
        "authKey": "<auth key>",
        "databaseId": "botstate-db",
        "collectionId": "botstate-collection",
        "containerId": "botstate-container"
    },
    "blobStorage": {
        "connectionString": "REDACTED",
        "container": "botstorage"
    },
    "luis": {
        "endpoint": "https://westus.api.cognitive.microsoft.com",
        "endpointKey": "",
        "whoskill_en_us_lu": "GUID REDACTED"
    },
    "MicrosoftAppId": "REDACTED",
    "MicrosoftAppPassword": "REDACTED"
}
```

@benbrown found the root cause - there was a `luisAuthoringKey` element in the appsettings file at the root level. Removing this solved the issue - not quite clear why but I can now publish to Azure without manual changes by kudu

**Comment by zidaneymar** [comment]
@darrenj appsettings.deployment.json has the highest priority among all settings, this part is updated in commit 4e8a637b

currently the priority is: appsettings.deployment.json > settings/appsettings.json > appsettings.json(root)

![image](https://user-images.githubusercontent.com/9328933/81168624-ec11a800-8fc9-11ea-82e2-ee62c1766188.png)

**Comment by luhan2017** [comment]
@darrenj looks like this issue is already resolved, I am closing this, please feel free to reopen if needed.
