### ISSUE TITLE
Use ui plugin / ui schema for trigger creation modal

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#2889]
related to #2845

**Comment by yeze322** [comment]
During Trigger creation process, the modal UI could be divided into 2 sections:
1. Hierarchical dropdown menu - to finally drop down to a Trigger `$kind`.
2. Properties form - to fill required fields of Trigger data.
![image](https://user-images.githubusercontent.com/8528761/88156776-75855d80-cc3c-11ea-99a9-ff97fef5f622.png)

For section 1, it's similar to the `menu` part in uischema, we describe a Trigger dropdown menu in uischema.
For section 2, we can leverage plugin system, a plugin hooks a React Component to a Trigger $kind and declares it should be displayed during the Trigger creation process.

**Comment by yeze322** [comment]
addressd om #4079
