### ISSUE TITLE
Recognizer text editor not visible

### ISSUE THREAD

**Issue by pradeeprajendran** [microsoft/BotFramework-Composer#2892]
## Browser

- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [x ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Main Dialog
2. Choose Recognizer type as luis or Regular Expression

## Expected behavior
Show text editor as shown in documentation
https://raw.githubusercontent.com/microsoft/BotFramework-Composer/stable/docs/media/tutorial-weatherbot/07/luis-recognizer.png

## Screenshots

![image](https://user-images.githubusercontent.com/1390668/81037905-f026b400-8e69-11ea-8020-bb1aeeb4d988.png)

**Comment by cwhitten** [comment]
Hello @pradeeprajendran. The docs you link to are out of date. To see the recognizer text you need to select the trigger in which handles the intent.

![Screen Shot 2020-05-05 at 7 47 22 AM](https://user-images.githubusercontent.com/1156704/81079682-b32be300-8ea4-11ea-991e-491a95c32fb9.png)

**Comment by pradeeprajendran** [comment]
Thanks. Should this be a documentation bug?
