### ISSUE TITLE
Need ability to add existing LUIS app to composer

### ISSUE THREAD

**Issue by pradeeprajendran** [microsoft/BotFramework-Composer#2893]
## Is your feature request related to a problem? Please describe.
I have existing trained LUIS models I need to be able to use in composer

## Describe the solution you'd like
1)Ability to provide existing LUIS app details to the composer
2) Composer should then expose the LUIS app models in markdown format for editing/updating

## Describe alternatives you've considered
I tried updating the appsettings.json file with LUIS appid etc but Composer did not seem to recognize that

**Comment by cwhitten** [comment]
Hello @pradeeprajendran and thank you for the issue.

In order to use existing LUIS models, you need to export the model as .lu from the portal and move its contents into a Composer bot, which will republish and generate new LUIS applications.

**Comment by pradeeprajendran** [comment]
Thanks. Would this be a future enhancement? I have the same LUIS models being used by multiple apps so generating new LUIS Applications will be hassle to update in all other apps.

**Comment by hebaelfadly** [comment]
@cwhitten have the same question, why there is no option to set LUIS appId instead of creating new one every time I need to use the SAME LUIS app?

**Comment by mukdenchild** [comment]
Any updates on this request? It makes lots of sense to be able to link a Luis app already built in Luis.ai, instead of exporting everything into a LU file and rebuilding the bot every time when there is a minor update on the Luis app from Luis.ai. This makes the easy-to-use Luis.ai portal much less useful.

**Comment by cwhitten** [comment]
Hello all. We have no plans to support this functionality in Composer. I understand the desire, it's just not something we're staffed to tackle at the moment. Open Source contributions are welcome!
