### ISSUE TITLE
Cannot use multi-selection when Visual Editor container is focused

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#2907]
## Describe the bug
Observed by Brenda after #2898 merged.
![bug-focus-beh](https://user-images.githubusercontent.com/8528761/81139937-2b280500-8f9a-11ea-8ad8-86530aa72b1a.gif)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
@hibrenda

**Comment by yeze322** [comment]
This issue was linked to a wrong PR 2908 but I cannot unlink it. It's a github bug.
If it's auto closed by 2908, we need to reopen it.

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2913
