### ISSUE TITLE
Default hint in trigger wizard will introduce error

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2910]
![image](https://user-images.githubusercontent.com/43408889/81147476-f6717900-8fac-11ea-9dc4-2b5528b97119.png)

Checked with ZhiXiang and Fei, this can be mitigate by following

![image](https://user-images.githubusercontent.com/43408889/81147653-4ea87b00-8fad-11ea-9b3c-9ca9741f9318.png)

**Comment by zhixzhan** [comment]
FYI @feich-ms  ,  I find out it comes from empty comments line e.g
```
> welcome
>                    // this empty comments line caused a lu parse error
> bye
``

**Comment by feich-ms** [comment]
Will take a look. Please let me know if this is blocker for R9 release.

**Comment by cwhitten** [comment]
yes we should address this

**Comment by feich-ms** [comment]
Fixed in this PR https://github.com/microsoft/botframework-cli/pull/763 which is targetting BF-CLI next RC
