### ISSUE TITLE
Unify the version of express in yarn.lock

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#2912]
## Describe the bug
Now we have three versions of @types/express in use, 4.17.6, 4.17.1, 4.16.1(in yarn.lock file). 
But the  dependency package @types/express-serve-static-core has only one version(4.16.2) now, and the version does not match @types/express@4.17.6 now. 

![image](https://user-images.githubusercontent.com/39758135/81147452-ea85b700-8fac-11ea-90c3-4e894b01b11f.png)

![image](https://user-images.githubusercontent.com/39758135/81147525-0d17d000-8fad-11ea-964b-4aa21b3b5996.png)

![image](https://user-images.githubusercontent.com/39758135/81147614-389aba80-8fad-11ea-945f-93ddc3836671.png)

![image](https://user-images.githubusercontent.com/39758135/81148686-4bae8a00-8faf-11ea-8a1c-b430cf5e96c3.png)

## Version
master

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by boydc2014** [comment]
Just add there seems to be a breaking change in types for expression-server-core-static in 4.17.5
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40905

**Comment by yeze322** [comment]
relates to #2581

**Comment by boydc2014** [comment]
@lei9444 please double check this

**Comment by yeze322** [comment]
Note that there is a compatibility issue for express 4.17.* https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40138
Typescript cannot resolve express types correctly and raises error: "Property 'headers', 'body', 'query' does not exist on type 'Request<any>'"

Stick to 4.16 will work.
![image](https://user-images.githubusercontent.com/8528761/106080073-5ddde300-6151-11eb-9801-a0e08b5cae5e.png)

**Comment by lei9444** [comment]
this task is out of data, so close it
