### ISSUE TITLE
Telemetry configuration broken in runtime

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#2915]
Some changes to the runtime have broken the telemetry configuration.

- IBotTelemetryClient is no longer registered for DI
- The TelemetryInitializerMiddleware is never added to the adapter pipeline

I have a fix ready to PR for this - will raise the PR once this issue is opened.

**Comment by benbrown** [comment]
@luhan2017 Can you also help verify that this is properly using the `applicationInsights.InstrumentationKey` field in the configuration?

**Comment by zidaneymar** [comment]
> @luhan2017 Can you also help verify that this is properly using the `applicationInsights.InstrumentationKey` field in the configuration?

based on this [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core), the InstrumentationKey will be used in 'AddApplicationInsightsTelemetry',  

![image](https://user-images.githubusercontent.com/9328933/81266700-cd69ea80-9077-11ea-99d2-c81059c4e114.png)

**Comment by garypretty** [comment]
The issue here is not that the Instrumentation Key is not used.  If you eject the bot and the key is populated in the appSetting.json file, then this is used and works as expected.  The behavior I am seeing is that if you populate the instrumentation key in settings via the composer UI and run the bot in a hosted fashion (i.e. the setting is populated in '\plugins\localPublish\hostedBots\XXXXXX\settings\appSettings.json', but it is blank in '\plugins\localPublish\hostedBots\59451.85293451945\runtime\azurewebapp\appSettings.json') then the telemetry is not logged correctly.

I am assuming the issue here is somewhere in how we are using multiple config files in the hosted scenario and how they play together.

**Comment by garypretty** [comment]
FYI - I got to the bottom of this and make an additional change in the related PR.

The overloaded configuration file is working correctly, but the overridden instrumentation key was not being respected by the AddBotApplicationInsights method.  I have now amended the runtime code to pass this into the extension method explicitly.  Once you do this, everything works as expected.
