### ISSUE TITLE
skill manifest url

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2918]
In order to call a remote skill, we need to provide the web access for manifest file to the caller bot.
This url should support both localhost and azure host.

http://localhost:3979/manifests/EchoBot-13-2-1-preview-1-manifest.json
https://echobot-13-0506-dev.azurewebsites.net/manifests/EchoBot-13-2-1-preview-1-manifest.json

With the current bot runtime structure, both locahost and azure deploy can not get the right file. 

For local host, this need to be hosted under "localPublish\hostedBots\27159.75275676705\runtime\azurewebapp" 
For azure publish, we need to include the manifest file as well.

**Comment by SonalBannagare** [comment]
How to get this url?
