### ISSUE TITLE
no error reported if skill manifest can not be accessed

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2920]
- connect to a new skill
- input the url which can not be accessed:
![image](https://user-images.githubusercontent.com/43408889/81186527-7a475780-8fe5-11ea-9a06-6c879c6c4697.png)
- no error reported but get following empty line
![image](https://user-images.githubusercontent.com/43408889/81186444-5e43b600-8fe5-11ea-91ab-d39f7000c2a7.png)

Sometimes, I add the new skill through the drop down list.
![image](https://user-images.githubusercontent.com/43408889/81186848-e32ecf80-8fe5-11ea-9d82-4b2117845684.png)
it showes empty but actually it is not empty as the url has already been added.
![image](https://user-images.githubusercontent.com/43408889/81187104-2f7a0f80-8fe6-11ea-8f8d-7b519c438a6b.png)

**Comment by cwhitten** [comment]
to fixer: when someone inputs a manifest url, fetch the url and make sure we get a successful HTTP 200 back before accepting it as a manifest
