### ISSUE TITLE
Runtime: Azure Functions support 

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/BotFramework-Composer#2924]
Preview version of azure functions support. Runtime changes done as part of https://github.com/microsoft/BotFramework-Composer/issues/2471 allowed for code reuse and integration with azure functions.

This issue is to allow a first, simple integration based on allowing deployment to Functions of the current assets.

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2923
