### ISSUE TITLE
Do we need explicit `UseCosmosDbPersistentStorage` setting

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#2927]
Currently, to enable the cosmos db features in the runtime, you must BOTH specify a cosmosDB config section.

Can we use the presence or absence of the cosmosDB config section to control whether this feature is used? Having 2 settings required seems easy to miss.

**Comment by luhan2017** [comment]
@benbrown Just to clarify, do you mean we remove this section
```
"feature": {
    "UseTelementryLoggerMiddleware": false,
    "UseTranscriptLoggerMiddleware": false,
    "UseShowTypingMiddleware": false,
    "UseInspectionMiddleware": false,
    "UseCosmosDb": false
  }
```

and just use this to check whether to enable those middlewares?
```
"cosmosDb": {
    "authKey": "",
    "collectionId": "botstate-collection",
    "cosmosDBEndpoint": "",
    "databaseId": "botstate-db"
  },
  "applicationInsights": {
    "InstrumentationKey": ""
  },
  "telemetry": {
    "logPersonalInformation": false,
    "logActivities": true
  },
  "blobStorage": {
    "connectionString": "",
    "container": "transcripts"
  }
```
Sure we can do this, That is how we did before. I thought you want those be explicit configurable because we will have a more fancy setting page, in that page, you can turn on/off a switch and fill in detailed setting like this one:

![image](https://user-images.githubusercontent.com/32191031/81265214-474ca480-9075-11ea-874b-4e9040cbe0fc.png)

**Comment by garypretty** [comment]
I think the suggestion here is to just remove "UseCosmostDbPersistentStorage" setting, in favor of enabling that automatically if the user has populated their cosmosDb config section. @benbrown is that right?

If so, then I think I agree.  We have done the same with telemetry. i.e. We don't have a feature switch, we just enable telemetry if the user populates their instrumentation key.

**Comment by benbrown** [comment]
Correct - is a user has specified the `cosmosDB` key in the config, the runtime should enable the storage without needing a separate flag. The presence or absence of the dependent config is enough.

We only need feature flags for things that are NOT driven by some other configuration - for example, the show typing and inspection middlewares.

**Comment by benbrown** [comment]
There is another problem here --

in the sample settings in Composer, we expose `UseCosmosDb` in the settings.

however, the setting name is actually `UseCosmosDbPersistentStorage`

I still think we should completely remove this setting, but at a minimum we need to clean up this inconsistency!

**Comment by garypretty** [comment]
There should also be no useTelemetryLoggerMiddleware or use TelemetryInitializerMiddleware settings anymore. These were removed from the runtime and from settings, but I think at least one of them has made its way back in. Can we check and remove them please?

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/2964
