### ISSUE TITLE
Enable the blob storage state system in the runtime

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#2928]
In addition to the CosmosDB state driver, we should also have blob storage.

Can we reuse the same blob storage configuration that is currently being provided for the transcript logger? This would be ideal!

Blob storage is much faster to provision. If we can enable this in the runtime, PERHAPS we can default to using this instead of CosmosDB? This merits discussion!

**Comment by garypretty** [comment]
I raised the same subject with @darrenj - I think his thoughts on this, from experience with the VA, is that Cosmos will avoid some common issues as customers need to scale out / up.  I do see some benefits to enabling blob storage, given the reduced complexity for setup / configuration from a customer perspective.

**Comment by darrenj** [comment]
I'm conflicted about this having seen too many customers ship with defaults - memorystorage being the worst example! My leaning is towards setting people up for success with an optional "step back" for development/testing because of this. Blob Storage is by no means as bad as memorystorage but I've yet to see a customer go live on Blob Storage (happy to be corrected).

I think we should take this change, but be very clear in the UX (@emivers8 ?) that this is for development/testing purposes only and make it super easy to switch up afterwards?

**Comment by garypretty** [comment]
Just to add some colour here - most of the bots I have seen go live have used blob storage.  I think the difference here is likely the size / scale of the bots being deployed and the type of bot.  Blob is likely to be fine for a relatively low load bot.

I think I am leaning towards @darrenj's thinking on balance.  At least for the initial release we could go with just Cosmos and add blob based on feedback.  We could also ensure we have discoverable docs to educate folks how to swap out cosmos for blob if they wanted to? Although, thinking about it, that should already be covered in the BF docs anyway.

**Comment by benbrown** [comment]
Putting aside our default provisioning configuration --

I think having the blob storage state driver loaded and ready to go, enabled only if configured, is something we should include.

The goal is that a developer can choose the right option through configuration only without having to worry about runtime code. 

If we default them to blob storage, they can add cosmos later and vice versa because the code knows how to handle both. We can "step" them back or forward however we want. 

So back to whether we provision cosmos by default or not ---

My main concern is that the cosmos provision part takes the longest -- it seems to adds minutes to the wait. If we feel strongly that Cosmos is the right place to configure *most bots automatically*, then we can let it continue to be the default.

We are already also provisioning blob storage for transcripts.

**Comment by benbrown** [comment]
I updated this ticket to more clearly indicate that changing the default is just a potential side effect of this

**Comment by tomlm** [comment]
Yeah to weigh in on this...if I'm making a bot for my wife's choir, I can't afford CosmosDB. It's way too expensive.  Functions+TableStorage is great for light loads. 
Having the option is good and having information about the reason for one over the other is super good. 

Something like:
* **TableStorage** - Inexpensive storage suitable for light to medium chat loads in one data center.
* **CosmosDB** - Scalable storage suitable for light to heavy work loads which can span multiple data centers.
* **MemoryStorage** - Storage used for testing on a single machine only.

**Comment by cwhitten** [comment]
Taking an R10 item to visit this.

**Comment by luhan2017** [comment]
old runtime deprecated.
