### ISSUE TITLE
UI bug in Text Input action

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#2933]
## Describe the bug
Editing property in the "User Input" tab of input actions jumps back to the "BeginDialog" view after a few seconds.

## Version

Application SHA test
SDK runtime packages 4.7.0-preview-191208-1
(latest master branch)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. New dialog
2. In BeginDialog trigger, add input prompt
3. Edit properties in the User Input tab

**Comment by hibrenda** [comment]
@tdurnford  could you take a look ?

**Comment by yeze322** [comment]
refs #2922 @tdurnford
