### ISSUE TITLE
when parse content '-{ test = test' will show console error

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#2940]
## Describe the bug
![81236640-8108a700-8fb2-11ea-9587-ec381092bd3b](https://user-images.githubusercontent.com/39758135/81280726-7837d400-908b-11ea-91d6-088dcb5ac0b4.gif)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by feich-ms** [comment]
Fixed in this PR https://github.com/microsoft/botframework-cli/pull/763. Wait for it's merged into next BF-CLI RC
