### ISSUE TITLE
QnA Maker integration docs not working

### ISSUE THREAD

**Issue by fathorMB** [microsoft/BotFramework-Composer#2941]
## Describe the bug

We are trying to implement QnA Maker integration following the docs here: [DOCS](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot)

We get the following error when the Connect to QnA Knowledgebase block is reached:

> Object reference not set to an instance of an object.

We already tried some different configurations, guided by other issues we found here flagged as closed.

## Version

Application SHA
test
Branch: stable

## Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Expected behavior

We are exactly replicating the docs, so we expect it to work.

## Screenshots

![image](https://user-images.githubusercontent.com/13238241/81299868-3309a700-9077-11ea-9594-802608ce2381.png)

![screenshot](https://user-images.githubusercontent.com/13238241/81300843-88928380-9078-11ea-9e93-8c0302dd263e.png)

## Additional context

Bypassing the appsettings way, we also tried "hardcoding" the configuration in the Connect to QnA Knowledgebase block but nothing changed.

Our bot is working properly with common LUIS operations, we used an Intent to route to QnA as suggested by docs.

We also tried to call QnA starting the Bot from VS. We obtain the same exception and it seems to be related to something happened here: [Microsoft BotBuilder](https://github.com/microsoft/botbuilder-dotnet/commit/a6fe8f3d6057f10d7ede469a6c792368e8374452)

@onoflo
@andreatosato

**Comment by zxyanliu** [comment]
Hi @fathorMB thanks for reporting. I am not sure if it related, but we have another QnA maker issue reported [here](https://github.com/microsoft/BotFramework-Composer/issues/2878). @hibrenda please let me know if there is anything I should update on the [docs](https://docs.microsoft.com/en-us/composer/).

**Comment by fathorMB** [comment]
Hi @zxyanliu, i don't think it's related. In my case the block is rendering successfully. Maybe can be related to [this one](https://github.com/microsoft/BotFramework-Composer/issues/1591)?

**Comment by hibrenda** [comment]
@fathorMB could you share more detail for the dialog file ? in the dialog flow, do you only include the QnA step or there are other steps may introduce this error ?

**Comment by fathorMB** [comment]
@hibrenda the QnA step is the only one in the dialog. I also tried to put it in a separate dialog and directly in the intent recognized trigger, but fails the same way. I tried to put other steps to check if the problem was in my dialog but all other steps are working.

**Comment by hibrenda** [comment]
if possible, could you share your bot (dialog) to us (no need to share qna) , we may have a try .

**Comment by fathorMB** [comment]
@hibrenda It's pretty simple to reproduce. I just created a new bot from scratch and then added a intent recognized trigger with some of the questions i have in my QnA. I see that LUIS is recognizing correctly, the trigger is fired and it contains only the QnA block. Configured as you see in the screenshot, so as explained in the documentation. At runtime, when reaching the QnA block, the only bot response is the error i did include in the issue description.

**Comment by hibrenda** [comment]
@fathorMB Thanks for reporting this issue. now I see . 
could you input something in following field and retry.  
![image](https://user-images.githubusercontent.com/43408889/81408226-69c2e880-916f-11ea-9a6e-ca52729052b4.png)

We test with qna sample and not reproduce this issue as all have been settled in the sample.

**Comment by fathorMB** [comment]
@hibrenda I'll try and let you know. Thanks in advance for support

**Comment by fathorMB** [comment]
@hibrenda It is now working filling all the fields you pointed out. Thank you!

**Comment by hibrenda** [comment]
By the way in master branch, we do have improvement even if you leave these as empty.
