### ISSUE TITLE
Loosen schema diff when getting custom actions to show in action flyout

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#2946]
## Describe the bug

If there are variations in the schema (title, description, etc), the schema items are added to the custom actions flyout. We should only diff the names in the definitions property.

**Comment by yeze322** [comment]
The schema diff only checks $kind, I will confirm it first

**Comment by yeze322** [comment]
@a-b-r-o-w-n I cannot repro this problem, I guess it's because those kinds are not included in your built-in sdk.schema?

The diff function receives and compares two schemas
1. The built-in schema file provided by server (BotFrameworkComposer\Composer\packages\server\schemas\sdk.schema)
2. The ejected schema file from custom runtime (BOT_PROJECT\schemas\sdk.schema)

**Comment by a-b-r-o-w-n** [comment]
Looking at the code it's not clear what was happening, but @lauren-mills had the 4.9 schema which includes more definitions than just `Microsoft.*` (like `boolenExpression`) which showed up in the custom actions flyout. Admittedly in this case, our base schema was out of date so the algorithm was correct.

Maybe the restriction should actually be tightened a bit and only include actions that have `$role: 'implements(IDialog)'`?

**Comment by yeze322** [comment]
@a-b-r-o-w-n Yes, I also think it's necessary to check `$role` is IDialog. I will do it.

Ideally, we would have 3 kinds of menus: Recognizer, Trigger, Action. After differentiating them,
- The fly-out menu receives Action part.
- New Trigger Wizard receives Trigger part.
- Recognizer dropdown receives Recognizer part.
Then the custom schema story could be a completed story. Let me start from a tightend filter.

**Comment by yeze322** [comment]
@a-b-r-o-w-n do we want to have the fix in 'R9-RC' or 'R10'?

**Comment by a-b-r-o-w-n** [comment]
I think R10 is ok for this.

**Comment by yeze322** [comment]
The custom Trigger topic is related to this issue. Besides the `IDialog` intefarce, handle the `ITrigger` interface as well.
