### ISSUE TITLE
About the date format on the Publish page

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2948]
<Decribe>

Tested the publish functionality to update this [doc](https://docs.microsoft.com/en-us/composer/how-to-publish-bot), and noticed the date format in the publish page is DD/MM/YYYY. 

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/32497439/81381854-3ece8b00-90c2-11ea-86d4-7f5e06a9569c.png)

I am not sure if we need to use the American date format which is MM/DD/YYYY. 
This US format is quite unique though. In most of the rest of the world, the format is (DD/MM/YYYY), in some places like China, this order is flipped (YYYY/MM/DD).

@mareekuh I was wondering what do you think?

See the following date format in Azure and LUIS:

* Azure
![image](https://user-images.githubusercontent.com/32497439/81428134-b0352a80-9110-11ea-95e8-cf8d2bb3b4ba.png)

* LUIS 
![image](https://user-images.githubusercontent.com/32497439/81428167-bdeab000-9110-11ea-952a-00d0444c8571.png)

**Comment by VanyLaw** [comment]
fix in https://github.com/microsoft/BotFramework-Composer/pull/2953
