### ISSUE TITLE
Manifest not copy to eject runtime folder

### ISSUE THREAD

**Issue by VanyLaw** [microsoft/BotFramework-Composer#2952]
## Describe the bug

currently manifest not copy to eject runtime folder before publish.

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by luhan2017** [comment]
I've verified this, it works well, so close this.
