### ISSUE TITLE
Labeling on if condition is confusing

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#2970]
## Issue

The Greeting template drops me into this view
![image](https://user-images.githubusercontent.com/17789481/81478145-3d8b8400-91d0-11ea-9a5c-26d60ad9b805.png)
I had real difficulting parsing what it was saying.  I think it's because the False is stacked on top of the True.
I read them in order, instead of thinking of them side-by-side.  I had to deconstruct mentally to figure out the right + was the false path.

## Describe the solution you'd like

I think it is clearer if the False is next to the + button
![image](https://user-images.githubusercontent.com/17789481/81478179-7d526b80-91d0-11ea-8043-d6affa625554.png)

**Comment by yeze322** [comment]
It's a nice change! Current layout came from design but the suggested solution is obviously more reasonable

**Comment by yeze322** [comment]
addressed in #2981

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/2981
