### ISSUE TITLE
Help! I've lost my bot!

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#2971]
## Describe the bug

OK, actually, I can't figure out where my bot is being created.  I've opened a bot and started editing it and there is NO file path ANYWHERE?  :(

## Version

![image](https://user-images.githubusercontent.com/17789481/81478287-26996180-91d1-11ea-965f-365a9baa9dce.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge (chrome)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Open a bot.

## Expected behavior

I expect a path to be someplace in the UI, probably in the title bar

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/81478279-15e8eb80-91d1-11ea-9255-b4e4dd973c10.png)

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/2980
