### ISSUE TITLE
Composer puts bot turd in my documents folder

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#2973]
## Describe the bug

When I install Composer it puts a "EmptyBot-01" in my **documents folder**.  That's a very unfriendly thing to do, I never put source code in my documents folder.  My documents folder is sancrosanct, it's where I put my taxes for turing-sake.

## Version

0.0.1 (2 days ago)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge (chrome)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

install composer and figure out where this EmptyBot-01 got put.  

## Expected behavior

Don't guess where you should put bots, ask me.

**Comment by cwhitten** [comment]
@tomlm we should allow users to choose Documents if they wish, however addressing https://github.com/microsoft/BotFramework-Composer/issues/2972 will not default or lead with this location.

**Comment by cwhitten** [comment]
And to clarify, we _don't_ add any bots on a users behalf that they don't explicitly use Composer to create. Perhaps you created a EmptyBot-01 and Composer doesn't show it's path. However https://github.com/microsoft/BotFramework-Composer/pull/2980 addresses that.

**Comment by tomlm** [comment]
Oh, that's possible, could be an old turd :)
