### ISSUE TITLE
I can't delete a bot.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#2974]
## Describe the bug

I have a EmptyBot-01 turd in my documents folder (see #2973 ) and I can't delete it. I don't know where it put it (see #2973 ).  And now there is no way for me to delete it from composer.

## Version

0.0.1 (2 days ago)

## Browser
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge (chrome)

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. open compose
2. try to get rid of EmptyBot-01

## Expected behavior

1. Right Click gives menu to "Delete Bot"
2. Opening the bot gives me menu to "delete the bot"

**Comment by cwhitten** [comment]
@tomlm this has been discussed in the past, and is a very fair requirement. The work is not hard to plumb this through.  To implementer:

When deleting the bot directory, we also need to remove any application level state referencing the deleted bot. The bot field from `data.json` needs to be removed and any information in LocalStorage pertaining to the bot needs to be removed. `composer:DialogSetting` and `composer:LuFileStatus` has this state in LocalStorage.

**Comment by hibrenda** [comment]
@cwhitten @benbrown  do we need to delete the runtime as well. Runtime maybe hosted in local or customized path ? Meanwhile, need the placeholder for delete action. @mareekuh need your suggestion.

**Comment by cwhitten** [comment]
@hibrenda yes the bot directory needs to get blown away and if they have injected a /runtime is will also get removed.

**Comment by benbrown** [comment]
We should definitely NOT delete anything outside of the main bot project folder. That is, if the custom runtime path is pointing at a totally different folder, it should NOT delete these files.

**Comment by mareekuh** [comment]
Quick screenshot here -
Marc may do some cleaning up but this is the idea (below).
Lives in the toolbar of bot settings page.

![Screen Shot 2020-05-11 at 6 14 22 PM](https://user-images.githubusercontent.com/48503434/81627576-5bfda500-93b3-11ea-9dc0-a9b2b354a116.png)

https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=1514%3A656

@DesignPolice and @liweitian

**Comment by yeze322** [comment]
refs #919

**Comment by VanyLaw** [comment]
@cwhitten @benbrown Talk about it, Do we need a design for stop runtime too?  We need to stop runtime before delete a running bot.

**Comment by DesignPolice** [comment]
Good points @VanyLaw and @yeze322 - I will look at those this morning as well... Ben and Chris fill in any other info I might need.

**Comment by liweitian** [comment]
@DesignPolice @mareekuh  We already have a 'delete' button on that tool bar used to delete node in the visual editor. So we probably need another design.

**Comment by benbrown** [comment]
I have never seen a delete button that acted like a dropdown like that. Seems error prone.

**Comment by benbrown** [comment]
I do not think we need to explicitly stop a bot before deleting it. It should automatically stop if you delete (or close) the project.

**Comment by cwhitten** [comment]
Agreed, the delete dropdown with options looks weird.

**Comment by DesignPolice** [comment]
Hmm, so do we just want to have a stand alone "Delete Bot"  - I think the other options could moved into the settings drop downs - and if I don't need to Stop the runtime to delete would free up some options. 

I will make some options and we can discuss in the standup, rather than this thread blowing up everyone all morning.

**Comment by mareekuh** [comment]
@liweitian and @DesignPolice 
Our buttons in the toolbar are contextual to the content of the page.
So in the Design view, when the user has selected a node, delete applies to that node.

In the Settings page, there are no nodes visible and delete applies to the content on bot settings or app settings.
- delete a language  (only available >2)
- delete the bot
etc;

So what we do for add, when there are multiple things that can be added in the context of the page, we do a dropdown. We should do the same for Delete...

If this is concerning to you all, we can add the 'delete bot' and 'delete language' and 'Delete runtime' all next to one another in the short term.
@benbrown @cwhitten

**Comment by cwhitten** [comment]
This is why I suggested we add it to the Homepage.

**Comment by mareekuh** [comment]
when adding it to the home page we'd be making it possibly more prominent than needed for a task like this and we'd have to have a 'picker' page: which bot to delete.
In the settings page you're already 'in' a bot - you're already managing the bot...

**Comment by cwhitten** [comment]
Yes but you just contradicted yourself saying the operations in the Settings page need to apply to the content on bot settings or app settings so I'm questioning the system here...

**Comment by mareekuh** [comment]
We have 2 settings pages: Bot settings - which is where 'delete bot' fits, and App settings. (composer app - neither deleting language or bot fits here)

**Comment by cwhitten** [comment]
We only have one Settings page at the moment.

**Comment by mareekuh** [comment]
Right. 
Today the settings for the current bot as well as the ones for Composer as the app are on one page. So buttons related bot either go on that page.

**Comment by DesignPolice** [comment]
Updating some info after a busy day. 

I know what I have designed on this page is more robust than we have time for - but the basic need is a single button to delete the entire bot. That also gives plenty of extra warnings that you are making a very permanent decision. 

![Screen Shot 2020-05-12 at 7 40 04 PM](https://user-images.githubusercontent.com/45223620/81765605-1ca18800-9489-11ea-9d51-04dba2cab3e8.png)

https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=1514%3A1499

Let me know if you want to make any tweaks - thanks everyone.
m

**Comment by liweitian** [comment]
The functionality is done waiting for review. Let me know if the UI is finalized. We need a checkbox right?

**Comment by DesignPolice** [comment]
Thanks @liweitian I will get with @beyackle today and get you a mock-up or we will fix it... thanks so much for all the hours! M

**Comment by beyackle** [comment]
Yeah, the functionality there looks exactly like what I had in mind (given that the box starts unchecked). It needs a design mockup, which I think @DesignPolice is already on.

**Comment by cwhitten** [comment]
@beyackle can you go ahead and take this over once Marc gets the design mock to you?

**Comment by DesignPolice** [comment]
@beyackle here you go.. the only change I made was to the modal - Should we make the toolbar button say Delete Bot? @mareekuh @cwhitten - not a strong opinion, but if I'm scanning the page there are lots of things that might be deletable 

here is the Figma:
https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=2193%3A1035

![Screen Shot 2020-05-14 at 12 05 21 PM](https://user-images.githubusercontent.com/45223620/81975222-8f227d00-95db-11ea-87b7-26ac77980e11.png)

**Comment by beyackle** [comment]
@DesignPolice How does this look to you?

![image](https://user-images.githubusercontent.com/61990921/82087020-30750600-96a4-11ea-8425-ee7b590ce156.png)

**Comment by mareekuh** [comment]
(-: loud and clear

**Comment by DesignPolice** [comment]
Awesome.

This is goofy, but can we shorten the text limit a little bit to get "Going" to drop down to the next line and hopefully get another word to the bottom.. so we don't have folder alone?

If not - push it -

thanks!

**Comment by beyackle** [comment]
@DesignPolice 

![image](https://user-images.githubusercontent.com/61990921/82090415-69b07480-96aa-11ea-84e9-5945eacb5ad9.png)

**Comment by DesignPolice** [comment]
Wooot!

just the little stuff, appreciate the help - IPAs on me - ship it!
