### ISSUE TITLE
I can't rename a bot!

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#2975]
## Describe the bug

I started editing EmptyBot-01, but now I want to rename it.  I can't. I also don't know where it is (see #2971 ).  But it's my masterpiece, and now it will forevermore be known as EmptyBot-01, along with all of the other masterpieces people have created and can't rename.

## Version

0.0.1 (2 days ago)

## Browser
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge (chrome)

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. open composer
2. try to get rename EmptyBot-01

## Expected behavior

1. Right Click gives menu to "Rename or move Bot"
2. Opening the bot gives me menu option to "Rename or Move the bot"

**Comment by cwhitten** [comment]
This is tracked here:https://github.com/microsoft/BotFramework-Composer/issues/1741

closing as a duplicate
