### ISSUE TITLE
Create a dialog dialog is very confusing.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#2977]
## Describe the bug
When I create a dialog via the add menu (see #2976 ) it then shows me a dialog which is completely disconnected from the operation I think I'm doing.  

The title of the dialog is "Describe your conversational objective" ???

This is 
* way way weird, what the heck is a conversational objective?  I though I was creating a dialog?
* The title should align with the operation I am performing
* the help text is not aligned with the fields, which causes confusion about what I am supposed to do where.

## Version

0.0.1 (2 days ago)

## Browser
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge (chrome)

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. open composer
2. open EmptyBot-01
3. Click Add Dialog (should be create #2976)
Look at the dialog and weep.
![image](https://user-images.githubusercontent.com/17789481/81478880-e63be280-91d4-11ea-8ce9-4556a87a1cb0.png)
![image](https://user-images.githubusercontent.com/17789481/81478925-2bf8ab00-91d5-11ea-93e8-1676e5979efd.png)

## Expected behavior
Dialog title which matches the action I am performing. Like this:
![image](https://user-images.githubusercontent.com/17789481/81479269-12586300-91d7-11ea-8209-b6a5285fa584.png)

**Comment by cwhitten** [comment]
@mareekuh as you provided the copy here quite awhile ago -- are you interested in updating this before BUILD?

**Comment by cwhitten** [comment]
By the way, I agree and have always felt that "Conversation objective" and "What can the user accomplish through this conversation" is off.

**Comment by mareekuh** [comment]
Lol - yeah, I'll fix it (-:
I think this comes from the era when we were designing a longer create-new flow (a year ago?) and especially when it's only a single dialog, this is odd.

**Comment by mareekuh** [comment]
Ok fixed see here: https://github.com/microsoft/BotFramework-Composer/issues/2976

<img width="647" alt="Screen Shot 2020-05-10 at 9 02 49 PM" src="https://user-images.githubusercontent.com/48503434/81523162-dc63cd80-9301-11ea-9903-4fe1ea10d68b.png">

**Comment by tomlm** [comment]
much better!

**Comment by hibrenda** [comment]
@mareekuh do we sign off on this so we can start the dev work.

**Comment by zxyanliu** [comment]
Thanks for your valuable feedback. Please see https://github.com/microsoft/BotFramework-Composer/issues/3175.
