### ISSUE TITLE
LUIS trigger phrases fail to show in the inline editor after trigger creation

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2982]
Describe the bug
I selected LUIS as a recognizer type and created an Intent Recognized trigger. 
I enter the intent name and trigger phrases in the **Create a trigger** window, but after submit, the data is now shown on the Properties panel. 
Note: the data can be published to LUIS. It's just that they are not shown in the inline lu editor as they are supposed to. 

## Version
Latest master branch.

## Browser
- [x] Chrome

## OS
- [x] Windows

## To Reproduce

1. Select LUIS as a recognizer type
2. Select **+ Add** then **+ Add new trigger** in the toolbar to create an Intent Recognized trigger. 
3. Enter the intent name and trigger phrases, select **Submit**.
4. After creation, in the **Properties** panel on the right side, you cannot see the trigger phrases you created. The lu editor is empty. 

## Expected behavior
Should be able to show the trigger phrases in inline lu editor after creating the intent recognized trigger.

## Screenshots
* Create Intent Recognzied trigger with trigger phrases. 
![image](https://user-images.githubusercontent.com/32497439/81531208-230ff280-9317-11ea-8c15-be372ccc7583.png)

* After creation, the inline lu editor was empty. 
![image](https://user-images.githubusercontent.com/32497439/81531276-4470de80-9317-11ea-9d3a-3b3186600261.png)

* Was able to publish the training data to LUIS. 
![image](https://user-images.githubusercontent.com/32497439/81531128-04116080-9317-11ea-94e9-1a02b0072704.png)

**Comment by hibrenda** [comment]
Form dialog is not refreshed . if you click the reload this page, it will be displayed.

**Comment by lei9444** [comment]
we should sync the data if the update is from shell
