### ISSUE TITLE
Need to support different endpoint for luis publish 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#2986]
User would like to publish the luis to mooncake. 
eg. chinaeast2 region is targeting https://chinaeast2.api.cognitive.azure.cn instead of https://${region}.api.cognitive.microsoft.com.  

So need to support different endpoint for luispublish
https://github.com/microsoft/botframework-cli/issues/778

**Comment by feich-ms** [comment]
CLI now supports to specify endpoint in build function, please help to update composer side to consume it @lei9444
