### ISSUE TITLE
Prebuilt isInteger function not working

### ISSUE THREAD

**Issue by fathorMB** [microsoft/BotFramework-Composer#2987]
## Describe the bug

When trying to use the prebuilt function "isInteger" via the Composer, i get the following error:

> isInteger does not have an evaluator, it's not a built-in function or a customized function

## Version

test
Branch: stable

## Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Expected behavior

Should work returning a boolean value indicating if the given value is an integer number.
Following this [documentation](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/common-expression-language/prebuilt-functions.md#isinteger)

## Screenshots

![image](https://user-images.githubusercontent.com/13238241/81558030-45445780-938d-11ea-8a81-171ead72e9ac.png)

![image](https://user-images.githubusercontent.com/13238241/81558063-51301980-938d-11ea-960f-e9a6a4f35b68.png)

## Additional context

Every other prebuilt function in working, like "where" or string manupulation ones.
Also checked every other block in the current dialog but that's the only error i get.

**Comment by boydc2014** [comment]
@cosmicshuai can you take a look at this?

**Comment by cosmicshuai** [comment]
@fathorMB The stable branch currently does not have type checking functions. They are available in master branch.  Also, stable branch will have those functions in the next release.
