### ISSUE TITLE
Unable to find the Custom event and Message events triggers...

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#2988]
## Describe the bug
The **Custome event** trigger and **Message events** trigger are lost. I was unable to find them anywhere. Is this by design? Do we only support the following four types of triggers?

* Intent recognized
* Unknown intent
* Activities 
* Dialog events

## Version
Latest master branch. 

## Browser
- [x] Chrome

## OS
- [x] Windows

## To Reproduce

This is what I did in my desired dialog: 

1. Select **Recognizer Type** to be **None**. Select **+Add** Then **Add new trigger**.
![image](https://user-images.githubusercontent.com/32497439/81584948-4dd66700-9368-11ea-9adc-45593910e648.png)

2. Select **Recognizer Type** to be **Regular Expression**. Select **+Add** Then **Add new trigger**.
![image](https://user-images.githubusercontent.com/32497439/81585039-6ba3cc00-9368-11ea-9dd2-bef2abfac36a.png)

3. Select **Recognizer Type** to be **LUIS**. Select **+Add** Then **Add new trigger**.
![image](https://user-images.githubusercontent.com/32497439/81585086-7cecd880-9368-11ea-81d7-a93a2901fb8e.png)

## Expected behavior
Should get the **Custom event** trigger and the **Message events** trigger back.

**Comment by a-b-r-o-w-n** [comment]
@zxyanliu The custom event has moved into the dialog events form. And as far as I can tell, the message event has been removed from the sdk. This was changed in #2911

**Comment by zxyanliu** [comment]
@a-b-r-o-w-n Thanks for your response and I was not aware of this change. 

I cannot find custom event from the dialog events form: 
![image](https://user-images.githubusercontent.com/32497439/81595576-8fbad980-9377-11ea-8b62-534aaa0b5867.png)

@luhan2017 Could you please confirm that Message events are removed from the sdk? Thanks.

**Comment by a-b-r-o-w-n** [comment]
@zxyanliu so instead of having a "CustomEvent" trigger, the sdk just supports a "DialogEvent" trigger with a custom event name. So the UX change was to allow users to type the custom event name. Sorry for the impact to docs.

**Comment by zxyanliu** [comment]
@a-b-r-o-w-n It's fine, I was just wondering what is the best way to update [this article](https://docs.microsoft.com/en-us/composer/how-to-define-triggers) so that our users do not get confused. Should we just document the trigger types that are exposed in Composer UI? i.e.

* Intent recognized
* Unknown intent
* Activities
* Dialog events

**Comment by zxyanliu** [comment]
Hey @a-b-r-o-w-n, the flow to create a **Custom event** trigger is unfamiliar to me. Instead of having a drop-down to choose from, I need to type in something in the **Which event** field. Actually whatever I typed in that field, a **Custom event** trigger will be created with the name of **Custom event**, not the name I typed. I was wondering if we could add **Custom event** to the **Dialog events** drop-down list since custom event has moved into the dialog events form. 

![image](https://user-images.githubusercontent.com/32497439/81719640-264bd100-9432-11ea-826b-443005d81925.png)

**Comment by a-b-r-o-w-n** [comment]
@sangwoohaan do you have any input here?

**Comment by luhan2017** [comment]
The message events are still valid in the sdk side, but we don't have samples for them yet, this is mainly for the Teams channel user scenarios. 
@cwhitten @a-b-r-o-w-n , just want to confirm with you that do we remove them intentionally?  

```
                {
			"$ref": "#/definitions/Microsoft.OnMessageActivity"
		},
		{
			"$ref": "#/definitions/Microsoft.OnMessageDeleteActivity"
		},
		{
			"$ref": "#/definitions/Microsoft.OnMessageReactionActivity"
		},
		{
			"$ref": "#/definitions/Microsoft.OnMessageUpdateActivity"
		},
```

**Comment by a-b-r-o-w-n** [comment]
I met with Sang and Tom today to understand this better. I will be reverting these changes tomorrow.

**Comment by a-b-r-o-w-n** [comment]
@zxyanliu The custom event is added back and the message events are now under the activities section. Please let me know if you need anything else.

**Comment by zxyanliu** [comment]
@a-b-r-o-w-n Thanks! I will update the [define triggers](https://docs.microsoft.com/en-us/composer/how-to-define-triggers) article tonight. Will let you know if I have further questions!

**Comment by a-b-r-o-w-n** [comment]
Sorry for the late changes!

**Comment by zxyanliu** [comment]
That's fine. No worries. : -) Thanks for the update!
