### ISSUE TITLE
`Invalid URI: The URI is empty` when invoking a Skill

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#2989]
## Describe the bug

When using the `Begin a Skill Dialog` and registering a SkillDialog using a provided manifest file it successfully creates the configuration but then errors with `Invalid URI: The URI is empty` when you try to invoke

## Version

- Latest

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Composer project
2. Register a Skill Dialog and try to invoke (I can provide a manifest)
3. Test locally (not azure deployed)

## Expected behavior

- Skill to work as expected or better warning/debugging to guide the user.

## Additional context

- When Composer bot is running locally and you add a remote Skill you will need to ensure ngrok is configured as the Skill Host Endpoint - automatically if running within composer IMHO. Not sure this is the underlying issue though.
- You also need an AppId for security so that will need to be configured too.

**Comment by cwhitten** [comment]
You need to register all involved bots (parent, child, etc) and include the AppId _and_ AppPassword in all bots for the framework to work.

This invalid URI error message is coming out of the SDK.

**Comment by cwhitten** [comment]
Closing with the assumption that this was a appid/password issue. Please re-open if assistance is still needed.
