### ISSUE TITLE
Cosmetics - User input page - left nav panel is missing line. Font style needs updated.

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3000]
![Screen Shot 2020-05-11 at 4 22 42 PM](https://user-images.githubusercontent.com/48503434/81622941-1cc95700-93a7-11ea-8334-6a253aae6a16.png)

Leftnav font and size and style should match Authoring Canvas leftnav.

![Screen Shot 2020-05-11 at 4 48 11 PM](https://user-images.githubusercontent.com/48503434/81623047-5d28d500-93a7-11ea-9979-240c8ee11275.png)

**Comment by zhixzhan** [comment]
I can't re-pro this, @hibrenda how about you ?

**Comment by hibrenda** [comment]
on windows / chrome , I could not reproduce this either.

**Comment by beyackle** [comment]
No repro here either (Win10, Edge)

**Comment by cwhitten** [comment]
Closing without clear repro or understanding of the issue. Please open a new issue if this exists still with more detail
