### ISSUE TITLE
Authentication shows validation code instead of redirecting

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3004]
## Describe the bug

When adding Authentication using an application registration from a different subscription the redirect page shows;
![image](https://user-images.githubusercontent.com/49873947/81678667-0926fa80-9452-11ea-8d77-bac5a3398150.png)

I have followed the steps in this [manual](https://docs.microsoft.com/en-us/composer/how-to-use-oauth#configure-the-oauth-connection-settings-in-composer). The code that is returned does not work at all and I would expect the page to redirect to my bot. I have filled in the appId & password in the bot settings.

I tested this in Azure itself as in the Emulator it works with a different SIgn In mechanism.

## Version

Latest Today

**Comment by luhan2017** [comment]
@cxbuilders You need to copy the code to your chat window where the sign in card pop us and continue the conversation there. This url is just used for OAuth validation and it don't know where to redirect.

**Comment by cxbuilders** [comment]
Wow, never even tested that, as that seemed too clumpsy... Has this always been the case with Bot Framework?

**Comment by nahlaGit** [comment]
i had the same issue,i want to know if there is any way to redirect to the bot directly without copy manually the code in bot window

**Comment by SSanjeevi** [comment]
Am also looking for way to avoid copy paste manually - this is not the case in bot framework.
