### ISSUE TITLE
File Open doesn't allow me to paste a path in

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#3009]
## Version

0.0.1

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge (chrome)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to OPEN BOT
2. I have a bot in a known location.  I can't type in a path, I can't paste a path. 

## Expected behavior

To be able to PASTE in a path or TYPE A path

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/2655
