### ISSUE TITLE
Maximum call stack size exceeded when open a bot

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#3023]
## Describe the bug
![image](https://user-images.githubusercontent.com/39758135/81790833-8b89ea00-9538-11ea-8e7b-5d759e37136d.png)

## Version
master

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'home'
2. Click on 'open a new bot'
3. See error

**Comment by yeze322** [comment]
@a-b-r-o-w-n Andy do you know what's happening here?
The first time I open a bot, it could be loaded correctly; if I go back to home page and reopen the bot again, whole page crashed.
