### ISSUE TITLE
QnA Maker integration dynamic "Strict Filters"

### ISSUE THREAD

**Issue by sachabruttin** [microsoft/BotFramework-Composer#3026]
## Describe the bug
We are trying to implement QnA Maker integration with a static filter that is the result of a previous user answer on the current dialog.

We need to use the value stored on "dialog.topic" on the Strict Filters. 
After trying all kind of formatting ( =dialog.topic, ${dialog.topic}, =$topic, =topic), all of them were not able to inject the memory value.

## Version

Application SHA : test
SDK runtime packages : 4.7.0-preview-191208-1

Branch: stable

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Define a property "dialog.topic" = "selected by user"
2. Add a "Connect to QnA Knowledgebase"
3. Add an item in Static Filters with name=domain and were "value" is injected from the dialog.topic property

## Expected behavior

On the HTTP Message, the stricFilters object must contains { "name":"domain", "value"="selected by user" }

**Comment by hibrenda** [comment]
![image](https://user-images.githubusercontent.com/43408889/82436434-652ff580-9ac8-11ea-8400-d9a941e2da13.png)

**Comment by sachabruttin** [comment]
It works like that, thanks for your answer.

It looks more like a workaround. I would have preferred to be able to do databinding directly on the editor like when using the HTTP request connector.

**Comment by muratkakun** [comment]
Same error occurs on composer version:2.1.1 and can not set Strict filters as object
![image](https://user-images.githubusercontent.com/28807269/147004889-025b19a1-6cfb-418a-9c1e-14dea434372b.png)
