### ISSUE TITLE
Unable to open another bot (sometimes)

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#3028]
## Describe the bug

Sometimes, when opening another bot, I am redirected to the design page with the last bot I had open instead of the new bot.

I haven't been able to come up with a consistent repro, but it is happening regularly for me.

**Comment by ryanlengel** [comment]
I can reproduce this on my setup (using latest)...

* Active project: VirtualAssistant
   * Home > Select EmptyBot-0, opens EmptyBot-0
![image](https://user-images.githubusercontent.com/43043272/81866455-157b8800-9524-11ea-8dde-533efcbe75b2.png)


* Active project: EmptyBot-0
   * Home> Select VirtualAssistant, opens EmptyBot-0
![image](https://user-images.githubusercontent.com/43043272/81866498-24fad100-9524-11ea-8214-8142664ecba7.png)

However, going back to home shows that the VirtualAssistant was the most recent project. Selecting VirtualAssistant now correctly loads my bot.
![image](https://user-images.githubusercontent.com/43043272/81866714-72773e00-9524-11ea-9b4e-e10256b7de56.png)

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/3051
