### ISSUE TITLE
Impossible to choose my local folder where I create/edit a bot 

### ISSUE THREAD

**Issue by michielpr** [microsoft/BotFramework-Composer#3032]
## Describe the bug

Upon creating a new bot from template on mac, I can't seem to choose the appropriate folder where I want to save my bot. The only folders are "/" and "/users". In addition, I can't seem to find a way how to browse the folder I want. 
## Version

Bot Framework Composer
                
                Version:  0.0.3
                Electron: 8.0.2
                Chrome: 80.0.3987.86
                NodeJS: 12.13.0
                V8: 8.0.426.16-electron.0

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot from template,
2. Select EchoBot 
3. Open the location dropdown and select one
4. Remove the location 
5. Open dropdown again and previous location doesn't show 
6. LocationAddress field is locked and I can't manually write a path here 

## Expected behavior
I would expect a browse option where I get to browse the various folders on my machine. 
I would also expect a 'previous locations' folder.  

## Screenshots

<img width="1024" alt="Screen Shot 2020-05-13 at 1 13 49 PM" src="https://user-images.githubusercontent.com/47259560/81860473-a732c780-951b-11ea-81a8-86b11e73d88a.png">

**Comment by a-b-r-o-w-n** [comment]
Hello @michielpr, you should be able to scroll in the list where it says "Applications" and "Library". To navigate to another folder, just click on the folder name in that list. We will consider ways to improve this experience, but hope this helps in the meantime!
