### ISSUE TITLE
Impossible to run LUIS model from a non 'westus' region

### ISSUE THREAD

**Issue by EPinci** [microsoft/BotFramework-Composer#3034]
## Describe the bug

It is impossible to run LUIS model from a non "westus" region.
Even changing it on the settings results in a non working model (publishing works, running it doesn't).

## Version

v0.0.3

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [X] Electron

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Expected behavior

Need to run LUIS model from a non "westus" region (e.g.: "westeurope").

**Comment by hibrenda** [comment]
Fix in #3029 for different luis region publish but can not specify with other language.

**Comment by hibrenda** [comment]
could I close it as more comments in #3035

**Comment by EPinci** [comment]
Yes, let's close this. Thank you! :)
