### ISSUE TITLE
Tags in export skill dialog are still not working right

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#3037]
## Describe the bug

Because the JSON parsing happens on every keystroke, it's very awkward to enter tags that contain spaces at all (because spaces get instantly trimmed by the parser). That fix should be reverted.

## Version

0.0.3

## Browser

desktop

## Expected behavior

I should be able to enter a comma-separated list of tags (which may contain spaces) and have the resulting JSON properly reflect that list.

**Comment by beyackle** [comment]
I have an idea how to solve this without just reverting my old change. I'll see if I can get this working.

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/3038
