### ISSUE TITLE
.gitignore for an ejected C# runtime needs updating

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3039]
## Describe the bug
When you eject your C# runtime it includes several `.gitignore` files for Azure Functions, Azure Web Apps, and Core. The Azure Web App and Core `.gitignore` files are overly thin and you'll end up checking in your runtimes `obj` & `bin` folders which means you're checking in binaries which could trigger a security alert.  These files should all be updated to follow best practices and include the restrictions found here: https://github.com/github/gitignore/blob/master/VisualStudio.gitignore
 
## Version
0.0.3

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/3043
