### ISSUE TITLE
can not open a bot if manifest url is invalid

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#3047]
- create a consumer bot
- create a skill connection and skillbot hosted in local as following
![image](https://user-images.githubusercontent.com/43408889/81918140-b04d9280-9608-11ea-9a16-0570fde9618c.png)
- shut down composer
- restart composer 
- open consumer bot will hit following error
- bot can not be opened

![image](https://user-images.githubusercontent.com/43408889/81917810-3f0ddf80-9608-11ea-8f82-d304c57afccb.png)

Workaround: start the skillbot and make sure in port 3979.

**Comment by boydc2014** [comment]
The expected behavior should be this error should not block opening.

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/3050
