### ISSUE TITLE
Composer bot history dup and out of order

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#3048]
## Describe the bug

![image](https://user-images.githubusercontent.com/16643193/81919901-015e8600-960b-11ea-8c57-6aac5d0015ac.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by liweitian** [comment]
Opening a bot will move the bot to the first place of the recent bot list. It does not change the data modification time.
