### ISSUE TITLE
A package reference version inconsistent issue - custom action

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#3063]
Describe the bug

Actually @luhan2017 found this issue when she helped me test the **custom action** feature, and it is a recent change. 
@srinaath Thanks for your effort on this as well. : )

When testing **custom action**, after eject runtime, the package reference version of the `Microsoft.BotFramework.Composer.CustomAction.csproj` file in the custom action folder shows "4.9.0-rc4", which is inconsistent with the package reference versions of the `Microsoft.BotFramework.Composer.WebApp.csproj` file in the `azurewebapp` folder and `core` folder. This will generate conflict when executing the command to generate the schema file, and testing custom action fails. 

![image](https://user-images.githubusercontent.com/32497439/82003282-d1b47b80-9614-11ea-8e8a-28a05743670c.png)

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/32497439/82003071-4a670800-9614-11ea-9648-5aebc39c42b0.png)

## Version
latest master branch.

## Browser
- [x] Chrome

## OS
- [x] Windows

## Expected behavior
The package reference version of the `Microsoft.BotFramework.Composer.CustomAction.csproj` file in the custom action folder should be "4.9.0" for this release, consistent with the other package reference versions. 

## Additional text
Changing the version to `4.9.0` solves the conflict and testing **custom action** successfully.

**Comment by srinaath** [comment]
thanks for spotting and creating this ticket @zxyanliu
