### ISSUE TITLE
Change the theme color of custom action nodes

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#3065]
## Describe the bug
From a grey node to Gray20
![image](https://user-images.githubusercontent.com/8528761/82012517-c4e26700-96aa-11ea-858a-aca8f182b92f.png)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/3066
