### ISSUE TITLE
cache won't clean after a bot is opened

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#3068]
## Describe the bug

Introduced by #2786 , server cache cause composer not sync with local file system's bot file

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/3067
