### ISSUE TITLE
Cannot edit dialog properties, always jump to 'dialog started' trigger

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#3070]
## Describe the bug
![bug-cannot-focusdialog](https://user-images.githubusercontent.com/8528761/82028599-717f1180-96c8-11ea-828f-8b3e9b273691.gif)

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by hibrenda** [comment]
mitigation method: delete the begin dialog.
