### ISSUE TITLE
editing Luis  intent mess up the file

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#3071]
## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Screenshots

![Untitled2](https://user-images.githubusercontent.com/49866537/82031503-8fe70c00-96cc-11ea-84b9-b010906f9f54.gif)

**Comment by zhixzhan** [comment]
Seems text below `[]` not counted in `#hi`

**Comment by feich-ms** [comment]
lu parser is fixed. Composer need to switch to the latest bf-lu lib to resolve this issue.
