### ISSUE TITLE
SendActivity actions with structured activity responses show as empty on canvas

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#3072]
## Describe the bug

When a Send Activity action is configured with a structured activity response (LG) it shows as empty on canvas leading to the user mistakenly thinking no response is set.

![image](https://user-images.githubusercontent.com/33519520/82041147-9f9c2b80-969f-11ea-9599-79c5bebe5986.png)

![image](https://user-images.githubusercontent.com/33519520/82041231-bf335400-969f-11ea-9173-efbd13758c58.png)

## Version

latest

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

- Add a SendActivity action
- Paste this into the LG

```markdown
[Activity
    SuggestedActions = ${CardAction('previous', 'imBack', concat('show schedule on ', dialog.previousDate))} | ${CardAction('next', 'imBack', string(concat('show schedule on ', dialog.nextDate)))}
]
```
## Expected behavior

Some visual treatment to indicate that LG is present but just can't be rendered?

**Comment by yeze322** [comment]
I will pick this item Darren

**Comment by yeze322** [comment]
Nothing displayed because of `SuggestedActions` is not recognized by canvas

**Comment by yeze322** [comment]
addressed in #3073 
![image](https://user-images.githubusercontent.com/8528761/82069523-02281280-9706-11ea-81d2-36d1e860722d.png)

**Comment by cwhitten** [comment]
Thank you @yeze322

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/3073
