### ISSUE TITLE
provisionComposer script fails

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3075]
## Describe the bug

provisionComposer fails as it picks the wrong TenantId in the script. This is introduced in #2964

The getTenantId function is not correct. It just gets the first tenant out of the list and uses that, whilst I need my default one. This then fails as I have multiple tenants. The token from the call creds.getToken on line 346 already contains the correct tenantId (I guess that's the default one). So I suppose that could be used instead.

For me this now fails as the wrong tenant is used.

## Version

6cd92ee

**Comment by benbrown** [comment]
Thanks for the info, @cxbuilders.  I am about to open a PR to resolve this.

* Will use the tenantId from the creds
* Will allow you to specify one as a parameter

Thanks!

**Comment by hibrenda** [comment]
addressed in #3084
