### ISSUE TITLE
HandOff to Human Agent From Bot Framework Composer

### ISSUE THREAD

**Issue by UmPrel** [microsoft/BotFramework-Composer#3077]
## Human HandOff from Bot Framework Composer
We are trying to configure the human agent handoff from Bot Framework Composer, i could see there is an activity available, but would like to know if there is a skill/feature available to take it forward. Or is there a way to add omni channel for customer service into Composer.

Please help.

**Comment by benbrown** [comment]
There is not a currently available skill that implements all the features necessary for human handoff. You can send the necessary activities, but your bot must implement the actual features required.

**Comment by UmPrel** [comment]
Thanks for your response. Is there any samples available to talk to external engagement hub

**Comment by arturl** [comment]
Hi @UmPrel 
This is not supported in the Composer out of the box yet, but you can build a [custom action](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action) that generates the handoff event as described [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-handoff-human?view=azure-bot-service-4.0).
What agent engagement platform are you considering?

**Comment by UmPrel** [comment]
Hi @arturl ,

Thanks for your response. I want to connect to Omni Channel for Customer Service. 
I will refer the link and get back for any queries.

**Comment by cwhitten** [comment]
Closing this for now.
