### ISSUE TITLE
Provision script does not use provided luis authoring key or region

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3080]
## Describe the bug

These values are specified as parameters, but are not actually applied to the provisioning process.

Do we need to apply these to the ARM template? Or should we remove them from the script?

See here:
https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/plugins/samples/assets/shared/scripts/provisionComposer.js#L88

## Expected behavior

If specified, these would be applied to the provisioned resources and included in the resulting publishing profile as appropriate.

**Comment by VanyLaw** [comment]
Hi @benbrown, we don't need luisKey and Region in provision script, the region is the same as other resources set in --location. I remove those in https://github.com/microsoft/BotFramework-Composer/pull/3108
