### ISSUE TITLE
feature: Share intent & entity definitions across triggers. 

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3086]
## Is your feature request related to a problem? Please describe.

I don't see a way that I can currently have two different triggers that share the same intent & entity definitions. I have to essentially create a new intent for every trigger. 

There are lots of reasons for wanting to do this. I might want to add conditional expressions to trigger slightly different flows.

**Comment by hibrenda** [comment]
@mareekuh

**Comment by mareekuh** [comment]
Could you add some scenarios?

**Comment by Stevenic** [comment]
Closing because it's old...
