### ISSUE TITLE
feature: Add "None" intent to UserInput screen

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3088]
## Is your feature request related to a problem? Please describe.

There's currently no way to train a "None" intent for your bot via composer. As an example... I added a new "START_TIMER" intent to my bot and LUIS currently maps utterance like "hello" to that intent. To fix this issue you need to train your bots "None" intent but there's no way I can find to do that short of adding a trigger for "None" which you don't want to do. 

Currently, to work around this limitation, you have to go to the LUIS portal for your bot and train the "None" intent there.

## Describe the solution you'd like

Just add a fixed "None" intent to the UserInput screen.

**Comment by hibrenda** [comment]
@mareekuh

**Comment by cwhitten** [comment]
We should be careful not to muck with the None intent auto-generation via Managed LU. @vishwacsena can you comment here?

**Comment by hibrenda** [comment]
By the way, if user add "None" through "intent recognized" trigger wizard, we should not include this in  "_interruption"  right ? but currently we include it in "_interruption".

**Comment by vishwacsena** [comment]
This is possible in composer and the right place to do this so as to not interfere with your triggers (unless you really want to handle the `None` intent) is to do it in the `all-up` view. Please ensure the right `dialog` is selected and you are adding the utterances to the right place. With composer, you have one LUIS app per dialog. 

![image](https://user-images.githubusercontent.com/20918136/82955767-57fd8580-9f64-11ea-903a-ef10aa12ec16.png)
