### ISSUE TITLE
feature: Allow multiple instances of composer

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3091]
## Is your feature request related to a problem? Please describe.

You currently can only open a single instance of composer. This makes copying from samples to your bot difficult.

**Comment by cwhitten** [comment]
This is being worked on as part of the multi-bot management workstream.

**Comment by cwhitten** [comment]
Closing. The UX direction will be to use a single Composer instance to house and author multiple bots. This is coming in R11

**Comment by brendan-murphy-oist** [comment]
I can open up two documents in two instances of word to compare them, and I can open up two scripts in VS Code side-by-side. What is the justification for not using that same model for Composer? Working from the examples is nearly impossible when you can't see them and your own bot at the same time.
