### ISSUE TITLE
Provision script should enable app insights for luis and web app

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3093]
When a bot is configured via the Azure portal, it configures app insights on the web app and LUIS instance.

Our current provision process does not configure these settings.

If possible, we should make it so that a bot provisioned via Composer is configured in the same way it would be if done via the portal.

**Comment by goergenj** [comment]
Adding detail on what's missing:
- On AppInsights an API-Key need to be created to read the telemetry from the Bot Service.
- On Bot Service add AppInsights settings on the "settings" page.
- On Bot WebApp activate AppInsights and configure to use the same AppInsights instance as the Bot Services.

Yes, it should be the same experience as when creating a "Web App Bot" via the Azure Portal.

**Comment by zidaneymar** [comment]
> When a bot is configured via the Azure portal, it configures app insights on the web app and LUIS instance.
> 
> Our current provision process does not configure these settings.
> 
> If possible, we should make it so that a bot provisioned via Composer is configured in the same way it would be if done via the portal.

Hi @benbrown , currently the provision would create a app insights service on Azure and generate a  instrumentation key in appsettings.deployment.json and this key would be used to initialize a telemetry client in runtime
User could open this app insights service on portal to see the details.
![image](https://user-images.githubusercontent.com/9328933/82546253-6d506980-9b8a-11ea-9ed8-1267140c8279.png)

![image](https://user-images.githubusercontent.com/9328933/82546440-aa1c6080-9b8a-11ea-8578-e5ded105943c.png)

**Comment by xieofxie** [comment]
I guess we should set this 
![image](https://user-images.githubusercontent.com/2876650/82552848-7eeb3e80-9b95-11ea-954a-010c96547040.png)
Ref: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-4.0

**Comment by benbrown** [comment]
Yes, we should set the bot service analytics as well as the webapp service.

**Comment by zidaneymar** [comment]
I didn't find a way to link luis with application insights but link the bot service and app insights based on @xieofxie 's comment in PR #3425
