### ISSUE TITLE
Please make sure you can't create a bot in the root of the hard drive.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#3097]
## Describe the bug
Now that we have Bot Delete it is very important that we don't allow you to create a bot in the root because deleting the bot will delete your harddrive.

I made this mistake with software I shipped 20 years ago.  I want to make sure you don't make the same mistake.

**Comment by cwhitten** [comment]
We did not make this same mistake.

![Screen Shot 2020-05-15 at 6 25 37 PM](https://user-images.githubusercontent.com/1156704/82107022-7e583100-96d9-11ea-87ad-5fbdc55ff7b6.png)
