### ISSUE TITLE
Composer should upgrade provisioning scripts on version upgrade

### ISSUE THREAD

**Issue by EPinci** [microsoft/BotFramework-Composer#3102]
## Describe the bug

If a bot is created with a certain version of the BotComposer and an update for BotComposer comes thru, the provisioning scripts never get upgraded.

## Version

v1.0.0

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [X] Electron

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

**Comment by hibrenda** [comment]
@EPinci Thanks for the feedback. similar to this https://github.com/microsoft/BotFramework-Composer/issues/2625 . we need to add the version management for runtime/script/schema and so on.

**Comment by cwhitten** [comment]
@benbrown as discussed, it makes sense to this "update ejected scripts" mechanism in the runtime config page.
