### ISSUE TITLE
feature: add middleware to remove @mentions for MSTeams

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3104]
## Is your feature request related to a problem? Please describe.

Messages from MS Teams include an @mention of the bots name at the beginning of every message.  This generally needs to be stripped off using `ActivityExtensions.RemoveRecipientMention()` otherwise `TextInput` actions will include it as part of the users response. I ejected my host and customized my `OnTurnAsync()` implementation to include the block below but we should really formalize this into a piece of middleware that can be turned on & off as a feature like the inspection middleware. 

```CS
       public override async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (turnContext.Activity.Type == "message") {
                turnContext.Activity.RemoveRecipientMention();
            }
```

**Comment by jwiersem** [comment]
I have this same problem when I use botframework composer for creating a MS teams groupchat scoped bot. How do I fix this like you have done @Stevenic ? Or is there a permanent solution for this issue already?
