### ISSUE TITLE
Projects appsettings.json file checked in by default

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3105]
## Describe the bug

There's no `.gitignore` file added to the root of new composer projects. This results in the projects `appsettings.json` being checked in by default.  That file can contain access tokens and authoring keys which makes checking it in a security risk. We should add a default `.gitignore` file to the root of the project that prevents this file from being checked in.
 
## Version
1.0.0

**Comment by VanyLaw** [comment]
I think the .gitignore file can prevent user mis-upload the appsettings.json file. But the sensitive value will still be persisted in appsettings.json file. So, I will remove those value in file and save in browser localStorage.
