### ISSUE TITLE
feature: add app password field to skills screen

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3106]
## Is your feature request related to a problem? Please describe.

Adding skills to your bot requires you enter your bots App ID which gets written to the bot settings file for the project.  The moment you fill in that setting you're required to also fill in the App Password field. If you don't you won't be able to test your bot in the emulator.

The upshot is that if you fill out this screen the "Test In Emulator" button for your project will launch the emulator but you'll get a 400 error from the bot host due to the missing password. Filling in the password field fixes the issue.

One solution would be to add an app password field to the skills screen to ensure that the user fills in all of the required fields needed to keep everything working.

**Comment by hibrenda** [comment]
@mareekuh @sangwoohaan need your comments

**Comment by mareekuh** [comment]
Yes please add this to the properties pane for Skills

https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=1174%3A823
