### ISSUE TITLE
Unable to open bot error

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3107]
## Describe the bug

Twice today I've hit the error below. I haven't worked out yet what causes it. I have really simple bots at this point but I am jumping back and forth between them. The actual error is an extra '}' at the end of the projects `appsettings.json` file. Removing this character fixes the issue...

![image](https://user-images.githubusercontent.com/698939/82133658-8ed4de00-97a3-11ea-83ec-fccd3ff03ba7.png)

## Version
1.0.0 for Windows

**Comment by hibrenda** [comment]
I can reproduce it but not always hit this error.  @liweitian maybe you can take a look. I just send you the bot files.

**Comment by boydc2014** [comment]
@liweitian can we at least to show the file path of the malformated file so user can manually correct that

**Comment by cwhitten** [comment]
Closing as stale
