### ISSUE TITLE
Dynamically passing json to channelData

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#3111]
I have store Generic template json in property and I was trying to assign that property value to ChannelData inorder to render the gengeric tempale in facebook channel but it not getting rendered.
@vishwacsena  can you look into it.
![Screenshot (50)](https://user-images.githubusercontent.com/51915291/82153520-94a2f000-9885-11ea-9593-3989186589eb.png)

**Comment by hibrenda** [comment]
@KoradaRajesh  Maybe you can reference following ? 
https://github.com/microsoft/BotFramework-Composer/issues/2549#issuecomment-611442549

**Comment by vidyakdil** [comment]
@hibrenda , here the value to be added in to ChannelData is being sent from a function app.  

The JSON is assigned to a variable and we are trying to render the template in the following way where dactivity is the response content we got back from the action.

# dactivity()
- '${dialog.response.content}'
 
# bfdactivity-387808()
[Activity 
        ChannelData=${json(dactivity())}
]

Is there anything we are missing or doing wrong?

**Comment by KoradaRajesh** [comment]
@hibrenda I'm able to render facebook templates by assaigning the json value to channel data in activity by staticaly but i want to pass an Action response to that channel data for this scenario I have tried the folowing..

[Activity
ChannelData=${json(dialog.result.content)}
]
--------------------------------------------------

[Activity
ChannelData=${dialog.result.content}
]
----------------------------------------------

#dactivity()
-'${dialog.response.content}'

#bfdactivity-387808()
[Activity
ChannelData=${json(dactivity())}
]

**Comment by Danieladu** [comment]
hi, @KoradaRajesh I may could answer this issue
`-'${dialog.response.content}'` would be evaluated to a string like `'{jsonbody}'`, I guess what you expect to get is just the string format of `{jsonbody}`, the way use `'` to transfer the json result into string is not correct, the right way is use `string` convert function, try this one:

```
#dactivity()
-${string(dialog.response.content)}

#bfdactivity_387808() // LG does not support '-' in the latest version
[Activity
ChannelData=${json(dactivity())}
]
```

it supposed to work. Thanks.

**Comment by KoradaRajesh** [comment]
@Danieladu i tried that but it's not rendering the template is there any other solution to achieve this.

#TemplateJson()
-${dialog.response.content}

# DisplayTemplate
[Activity
ChannelData=${TemplateJson()}
]

**Comment by Danieladu** [comment]
@KoradaRajesh what is the value of "dialog.result.content"?

**Comment by KoradaRajesh** [comment]
{
    "attachment":{
      "type":"template",
      "payload":{
        "template_type":"button",
        "text":"What do you want to do next?",
        "buttons":[
          {
            "type":"web_url",
            "url":"https://www.messenger.com",
            "title":"Visit Messenger"
          }
        ]
      }
    }
}

**Comment by Danieladu** [comment]
@KoradaRajesh WOW, this sample is the same with #2618, you can have a reference. 
If finally still can not achieve the expected result, please check the code into a specific branch, and we can repro this issue. Thanks.

**Comment by KoradaRajesh** [comment]
@Danieladu In this #2618 they gave data statically in LG but In my scenario, I'm storing JSON value in a property and trying to send it to the ChannelData but it's not working but if I store soon value in LG property and send it to the ChannelData it's working fine. What would be the issue here?

This is the property I'm storing json  **dialog.response.content**

This is the process I'm passing JSON to the ChannelData

#bfdactivity_387808()
[Activity
ChannelData=${dialog.response.content}
]

#bfdactivity_387808()
[Activity
ChannelData=${josn(dialog.response.content)}
]

**Comment by KoradaRajesh** [comment]
@Danieladu In this #2618 they gave data statically in LG but In my scenario, I'm storing JSON value in a property and trying to send it to the ChannelData, It's not working but if I store JSON value in LG property and send it to the ChannelData it's working fine. What would be the issue here?

This is the property I'm storing json  **dialog.response.content**

This is the process I'm passing JSON to the ChannelData
Below scenarios I have tried.
#bfdactivity_387808()
[Activity
ChannelData=${dialog.response.content}
]
_____________________________
#bfdactivity_387808()
[Activity
ChannelData=${josn(dialog.response.content)}
]
_____________________________
#TemplateJson()
-${dialog.response.content}

#DisplayTemplate
[Activity
ChannelData=${TemplateJson()}
]
_____________________________
#TemplateJson()
-${json(dialog.response.content)}

#DisplayTemplate
[Activity
ChannelData=${TemplateJson()}
]
_____________________________
#TemplateJson()
-${dialog.response.content}

#DisplayTemplate
[Activity
ChannelData=${json(TemplateJson())}
]

**Comment by boydc2014** [comment]
@Danieladu can you create a sample bot that picking channel data from memory, and display it via LG to make sure this step is validated in @KoradaRajesh side. if it's working in KoradaRajesh's side, then the problem will be in memory value perhaps not correectly set.

Also @KoradaRajesh can you attach your bot here? so @Danieladu  can help debug directly probabaly?

**Comment by Danieladu** [comment]
hi @KoradaRajesh  I have test the dynamic assignment with composer, and it works. Here is the bot project: 
[EmptyBot-0.zip](https://github.com/microsoft/BotFramework-Composer/files/4692997/EmptyBot-0.zip)
The output result is as same as the static assignment.
Maybe you can try it and look forward to your reply

**Comment by KoradaRajesh** [comment]
@Danieladu It's working but the template is not rendering without activity text is this possible to render templates without text. I have tried it but it's not rendering.

[Activity 
  ChannelData=${dialog.response.content}
]

**Comment by Danieladu** [comment]
hi @KoradaRajesh  It's a bug in SDK. I have filed an issue to track this one. link is here : 
https://github.com/microsoft/botbuilder-dotnet/issues/4001
The workaround is add a text property in activity structure. Thanks!

**Comment by KoradaRajesh** [comment]
Thanks @Danieladu I will track that Issue

**Comment by boydc2014** [comment]
Close this in favor of microsoft/botbuilder-dotnet#4001
