### ISSUE TITLE
Unable to convert object to json and pass to Http body

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#3112]
Http body accepting only json but I'm unable to convert the object to json and pass in to it.

**Comment by hibrenda** [comment]
Maybe you can define the json format in body directly.  
eg. 
```
{
    "age":"18"
}
```
or Assume dialog.a is an object (this will dynamically set body content)

```
{
    "data":"=dialog.a"
}
```
or you can directly define it in body with string and specified the content type. reference https://github.com/microsoft/BotFramework-Composer/issues/1829#issuecomment-625608050

**Comment by KoradaRajesh** [comment]
Thank you lot @hibrenda
