### ISSUE TITLE
azure-function deployment need to take care luis resource

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#3114]
- create a bot with luis in composer
- provision to azure based on azure-function template
- deploy with azure-function 
- run in emulator hit luis not found issues
![image](https://user-images.githubusercontent.com/43408889/82172625-4d584600-98fd-11ea-9688-2419c1391413.png)

**Comment by VanyLaw** [comment]
@zidaneymar will help to check this issue.
