### ISSUE TITLE
How to halt conversation after HeroCards so user can select a card?

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3115]
When displaying HeroCards with a messageBack button for users to select an option, I do not see any way to halt the conversation and wait for the user to click on any of the HeroCards?

**Comment by hibrenda** [comment]
@cxbuilders could you share more detail for the HeroCards and how you test the cards? 
In samples - RespondingWithCardSample,  if you tested the HeroCards sample in emulator, the conversation will wait for user select.

**Comment by cxbuilders** [comment]
@hibrenda Thanks that works, however in this situation the HeroCard in combination with the End dialog turn is actually an ask a question type of functionality. For me it triggers Luis and jumps dialog there. In each ask a question component it is possible to set Allow Interuptions to true. For HeroCards this should also be possible

**Comment by cxbuilders** [comment]
Nevermind, got it working by using displayText and keep text empty;
[CardAction
    type = ${if(type == null, 'imBack', type)}
    title = ${title}
    value = ${value}
    text = null
    displayText = ${title}
]
