### ISSUE TITLE
mac download icon looks funky in the mac dock

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3124]
<img width="36" alt="Screen Shot 2020-05-18 at 5 19 59 PM" src="https://user-images.githubusercontent.com/48503434/82271268-2ebd7380-992c-11ea-8f8a-485121c71592.png">

Regular icon looks ok

**Comment by cwhitten** [comment]
@mareekuh is that your Downloads icon?

**Comment by cwhitten** [comment]
ping

**Comment by mareekuh** [comment]
yes

**Comment by benbrown** [comment]
This is the result of the app icon sitting on top of other apps inside the downloads folder.

If you move it out of downloads or launch the app, you should see the normal icon.
