### ISSUE TITLE
Pre-defined lg template cannot be changed in EmptyBot sample - electron

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#3132]
## Describe the bug
The `${WelcomeUser()}` template is pre-defined in the EmptyBot sample and cannot be updated. 

## Version
master branch works
electron 1.0.0 does not. 

## Browser
- [x] Chrome

## OS
- [x] Windows

## To Reproduce

1. Create an EmptyBot from template
2. Click on `${WelcomeUser()}` template and update to the following: 
Hi! I'm a friendly bot that can help with the weather. Try saying WEATHER or FORECAST.
3. Test in Emulator and it still shows: 

## Expected behavior
Should allow users to update the pre-defined LG template. 

## Screenshots
1. This is the pre-defined LG template
![image](https://user-images.githubusercontent.com/32497439/82367507-c2dd1880-99c8-11ea-968c-3fffbff26502.png)

2. Update the LG template
![image](https://user-images.githubusercontent.com/32497439/82367607-f6b83e00-99c8-11ea-92b7-b5484b0d42f4.png)

3. Still see the welcome message
![image](https://user-images.githubusercontent.com/32497439/82367745-223b2880-99c9-11ea-86bd-15a914d155d6.png)

## Additional context
In master branch, the pre-defined LG template can be updated.

**Comment by hibrenda** [comment]
@zxyanliu  I did not reproduce it. maybe it starts on different port so make sure you test it on corresponding localhost:xxxx .
