### ISSUE TITLE
showcode will mess up the dialog content across different dialog

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#3134]
- create a empty bot
- create a new dialog A
- click show code
- switch between  Main (greeting triggers) and A (begin dialog) dialog, you will see the everything becomes into begin dialog 
- but sounds like both a dialog and the wrong begin dialog action are not serialized into disk

https://recordit.co/NSlcuxcReb
![image](https://user-images.githubusercontent.com/43408889/82393044-f2972980-9a77-11ea-8b0b-059a380f9e60.png)
![image](https://user-images.githubusercontent.com/43408889/82393072-03479f80-9a78-11ea-8557-bf909290dac8.png)
![image](https://user-images.githubusercontent.com/43408889/82393091-1195bb80-9a78-11ea-9582-d1729b36128d.png)

**Comment by hibrenda** [comment]
By the way sounds like I hit the thread blocking, so after create the dialog A, this is not written to the disk. so that's why content has not been updated . I create another bot and did not hit thread blocking, so after show code messed the dialog content, all the errors are serialized into disk.

**Comment by lei9444** [comment]
> By the way sounds like I hit the thread blocking, so after create the dialog A, this is not written to the disk. so that's why content has not been updated . I create another bot and did not hit thread blocking, so after show code messed the dialog content, all the errors are serialized into disk.

**Comment by lei9444** [comment]
> By the way sounds like I hit the thread blocking, so after create the dialog A, this is not written to the disk. so that's why content has not been updated . I create another bot and did not hit thread blocking, so after show code messed the dialog content, all the errors are serialized into disk.

fix in #3138

**Comment by xieofxie** [comment]
a real sad story

**Comment by cwhitten** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/3138
