### ISSUE TITLE
LG parse may mess up the content in lg file

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#3136]
- create a dialog
- add sendactivity with "${$ xxx}"
- add more sendactivity steps with "hello", "welcome" ...
- back to the first sendactivity inline editing , quickly type "backspaces" 
- all the following  sendactivity content will be deleted. (eg. "hello", "welcome" will be deleted)

This will mess up the whole lg file content .

**Comment by boydc2014** [comment]
@zhixzhan will take this together with the LG file been emptied issue.

**Comment by zhixzhan** [comment]
@boydc2014 @Danieladu to reproduce this:
```
# Exit
-Thanks for using todo bot.${ 

# Greeting
-What's up bro
```

* notice `${ ` break the parse, then parse result is one template
{
name : 'Exit'
body: `
-Thanks for using todo bot.${ 

# Greeting
-What's up bro
`
}

if we continue update body on `Exit`, it will mess up `# Greeting`
