### ISSUE TITLE
Generated Skill Manifest not correct

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3140]
When exporting (strange action name for generating a manifest) as a skill the generated manifest is not correct. The $schema is below the name;
![image](https://user-images.githubusercontent.com/49873947/82428290-938ee000-9a8a-11ea-8252-b8d460ed2585.png)

It should be:
![image](https://user-images.githubusercontent.com/49873947/82433570-e9b35180-9a91-11ea-8e19-a9b7a034a6d9.png)

When manually changing this it will automatically put it back in the wrong order again.
Power Virtual Agents won't accept the manifest with the wrong order, however this takes ages to figure out as it won't tell you anything about what was wrong. After eliminating step by step I found out the $schema was placed on the wrong line.

**Comment by xieofxie** [comment]
I would suggest we update to the order of $schema, $id, blah as it is supported by PVA and described in schema https://schemas.botframework.com/schemas/skills/skill-manifest-2.0.0.json

**Comment by cxbuilders** [comment]
Just updated the issue as one of the screenshots was not correct. PVA really wants first $schema then $id then the rest. Not sure why it is so picky

**Comment by cwhitten** [comment]
Why does PVA require ordering of the keys? This seems like an odd constraint.

**Comment by sbacha** [comment]
@cwhitten will open a bug in PVA to investigate this.
