### ISSUE TITLE
AuditLog and CrashReport mechanism

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#3142]
We should consider add telemetry in our application to record user action and be able to wrap up and generate a "crash report" with the context (like the env, the bot, the settings maybe).  Like many applications do.

It would be very helpful for us to debug certain issues, especially the ones that hard to repro.

**Comment by cwhitten** [comment]
@boydc2014 I'm interested in this generally, but please be more detailed on what you would want to expose.
