### ISSUE TITLE
Interruption sample behaves incorrectly under Dutch regional setting

### ISSUE THREAD

**Issue by MathieuDiepman** [microsoft/BotFramework-Composer#3153]
## Describe the bug
The GetStarted trigger has a precondition that is evaluated incorrectly. 0,8884471 is evaluated as <0.7. 

## Version
Release: Preview 2.0

## Browser
- [X] Chrome

## OS
- [X] Windows

Set regional settings of machine to Dutch
1. Go to 'Interruption-Sample'
2. Run it (say 'Hi')
3. Notice that the bot does not detect the GetStarted trigger even though LUIS classifies it as >0.7
## Expected behavior
0,8 is evaluated as >0.7

**Comment by hibrenda** [comment]
@vishwacsena be aware of this issue.

**Comment by vishwacsena** [comment]
@hibrenda @boydc2014 this seems related to the locale issue we saw in #1640 

@MathieuDiepman can you share what your OS UI language as well as locale settings are for number format etc?
