### ISSUE TITLE
Can't check for updates

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/BotFramework-Composer#3156]
## Describe the bug

When I click on Check For Updates, it gives me an error

## Version

1.0.0

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [x] Electron 

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Help Menu
2. Click on Check For Updates

## Expected behavior

It should either update or give me a friendly message that my Bot Framework Composer is up to date. 

## Screenshots

![Annotation 2020-05-21 212712](https://user-images.githubusercontent.com/16351038/82554850-08a50700-9baa-11ea-9f98-211de85f0eaf.jpg)

**Comment by hibrenda** [comment]
@tonyanziano can you take a look ?

I could not repro.
![image](https://user-images.githubusercontent.com/43408889/83246269-74075e00-a1d4-11ea-9546-9cdd4769c7d0.png)

**Comment by tonyanziano** [comment]
I'll look into this.

**Comment by tonyanziano** [comment]
@arafattehsin are you running Composer as administrator?

**Comment by arafattehsin** [comment]
Hi @tonyanziano - No. I am not a System Administrator but after re-installing it and running it with *Just for me* I do not get an error. However, I also do not get any prompt as **Composer is up to date** but it gets updated at the backend. 

Secondly, the latest Nightly build does not launch for the folks who are not Administrator :)

**Comment by tonyanziano** [comment]
Hi @arafattehsin ,

Thanks for all the info!

Another Composer dev and myself looked into this issue and it seems that the following factors result in the UAC prompt:

- The user installed Composer "for all users"
- The user **did not** run Composer as admin
- The user enabled the auto updates (silent install) option

Some workarounds for this include:

- Install Composer for "only current user"
- Install Composer "for all users" but run as admin
- Install Composer "for all users" but disable auto updates (silent installs) option

===

Regarding the latest nightly, it's actually a bug that got checked in yesterday that is causing the startup to fail regardless of how you run the app (fails for me as well :)). A PR (#3280) just got checked in to fix that bug and tonight's nightly should continue to startup properly,

**Comment by arafattehsin** [comment]
It works great! Except.. there's something I'd still love to see. If the Bot Framework Composer is running and I click on *check for updates* (being a non Administrator), I still get the above error. However, if my composer is the most updated one then it does not show any pop up (even the successful one). 

Happy to close this issue if you want to keep it separate.

**Comment by tonyanziano** [comment]
Ok so the original issue has been solved, but you are saying that if you explicitly check for updates using **"Help" -> "Check for updates"** you are not receiving any feedback via a dialog?

If you have the "Auto update" setting toggled in the App Settings page then this is the expected behavior.

![image](https://user-images.githubusercontent.com/3452012/84054235-f24bc900-a967-11ea-8a38-4154cb5c6ec2.png)

However, if you think this UX could be improved and that we should always show the user feedback when manually checking for an update regardless of whether that option is checked or not, I can speak with design and we can reevaluate this scenario.

**Comment by arafattehsin** [comment]
This is 100% correct. However, as you mentioned about the UX part. As a user, I will love to see a prompt even if I have setup the auto update option to true. 

Secondly, as I mentioned earlier that if my Composer is not updated to the latest item, it shows me a dialog with the error I reported earlier in my issue.

**Comment by tonyanziano** [comment]
Hi @arafattehsin ,

I'm going to go ahead and close this issue then. I've created a separate issue that will track the proposal to show feedback when explicitly checking for updates using the "Help -> Check for updates" menu item:

https://github.com/microsoft/BotFramework-Composer/issues/3357
