### ISSUE TITLE
Change menu label from Design Flow to Design. Asap.

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3157]
I noticed that the menu label for the authoring canvas had been changed from Design to Design flow.

We have agreed with PVA that this is called the Authoring canvas. This would be too long for a label, and neither Authoring or Canvas on its own would work.
'Design' works, as it is a verb. One can 'Design in the authoring canvas'.
Design Flow will not work (flow has many other meanings and I doubt that PVA will ever agree to use this also. Note: Currently, PVA has a button to go to the Authoring canvas, not a tab. They continue to receive feedback that people cannot find the authoring canvas and it takes too many clicks to get there. It's likely that they'll make it top-level also, just like Composer. If so i'd recommend they choose the same label as we use and Design FLOW is a no-go for the reasons above.

Please ...

1. change this back asap to Design
2. Fix all labels to sentence cap
3. Update the documentation
4. Notify me and Yan whenever **changes need to be considered** for labels and concept terms. Neither of this knew about this. I work closely with the copywriters of PVA and all of these things are carefully discussed, weighed and agreed upon. When all of a sudden things get changed and the first thing I know about it is when I see it in the Build, we're damaging carefully built-up trust with our partners in PVA.
Marieke

**Comment by cwhitten** [comment]
@mareekuh it clearly says "Design flow" in your master UX designs. It has been this way as long as I can remember.

**Comment by zxyanliu** [comment]
I will update the docs as soon as it's changed. : -)

**Comment by hibrenda** [comment]
@liweitian  we can submit a PR for this today.
