### ISSUE TITLE
"User was not found" when running node provisionComposer.js

### ISSUE THREAD

**Issue by timoconnellaus** [microsoft/BotFramework-Composer#3160]
## Describe the bug

When I run the provisionComposer.js script I get the error "User was not found"

![image](https://user-images.githubusercontent.com/3151605/82623466-95d87200-9c23-11ea-9a43-c6771420d4d9.png)

I'm using an MSDN subscription
The user running the command is account admin on that subscription and has permissions to create app registrations - I have created them through the Azure CLI and through the portal successfully

I get a similar error when I create the app registration first
![image](https://user-images.githubusercontent.com/3151605/82629375-e3a8a680-9c32-11ea-8b80-7afe287ad2bf.png)

## Version

I'm using release 1.0.0

Sha: 414f00d2896885959f91074dd70c3187fdf1b2cf

## Browser

- [x] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by timoconnellaus** [comment]
I was able to resolve this issue by making a change to the provisionComposer.js. The adjustment was to pass the tenant ID to .interactiveLogin()

Solution was found here - https://github.com/Azure/azure-sdk-for-node/issues/1821

**Comment by zidaneymar** [comment]
Hi @benbrown , I think we should enable users to enter their tenant id for provision, according to the link provided by @timoconnellaus , we should use this following code to login to Azure. What do you think about this?
`msRestAzure.interactiveLogin({domain: 'your-tenant-id}, function(err, credentials, subscriptions)
`

**Comment by benbrown** [comment]
@zidaneymar yes, since it is already possible to pass in the tenantId as a parameter, we should use this if specified in the login.

**Comment by GAURI02X** [comment]
Hi Team,
Could you please help me with the exact change needed in js file. I got the same "user was not found" error while publish bot made from composer. I had azure subscription from hotmail account. Uploaded provision composer js file as zip for your ref. Do let me know if more info needed.
[provisionComposer.zip](https://github.com/microsoft/BotFramework-Composer/files/4725668/provisionComposer.zip)

msRestNodeAuth
  .interactiveLogin()
  .then(async creds => {
    const createResult = await create(
      creds,
      subId,
      name,
      location,
      environment,
      appId,
      appPassword,
      createLuisResource,
      createLuisAuthoringResource,
      createCosmosDb,
      createStorage,
      createAppInsignts
    );

**Comment by GAURI02X** [comment]
Hi,
After making below change, I am still getting same error - "user was not found". I am using azure subscription from hotmail account. 
msRestNodeAuth
  .interactiveLogin({ domain: tenantId })
  .then(async creds => {
    const createResult = await create(
      creds,
      subId,
      name,
      location,
      environment,
      appId,
      appPassword,
      createLuisResource,
      createLuisAuthoringResource,
      createCosmosDb,
      createStorage,
      createAppInsignts
    );

**Comment by GAURI02X** [comment]
@benbrown @zidaneymar @cwhitten Hi Team,
Can you please help me with above issue.

**Comment by GAURI02X** [comment]
@benbrown @zidaneymar @cwhitten 
Hi Team,
This is not working. I created a new project from template (AskingQuestionsSample) from 1.0.1 version. Below is what I get after running the command.
Also, could you please let me know how to fix the project created with 1.0.0 version. Its still showing "user was not found."

C:\GC\Bots\Bot from Composer\AskingQuestionsSample-0\scripts>node provisionComposer.js --subscriptionId=8ab821e5-72b0-4237-a319-34adfc7e5ce4 --name=Third --appPassword=3efn$NIP${k$GU_y --environment=Dev
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- C:\GC\Bots\Bot from Composer\AskingQuestionsSample-0\scripts\provisionComposer.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\GC\Bots\Bot from Composer\AskingQuestionsSample-0\scripts\provisionComposer.js:3:15)
[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\GC\\Bots\\Bot from Composer\\AskingQuestionsSample-0\\scripts\\provisionComposer.js'[39m
  ]
}

**Comment by GAURI02X** [comment]
@benbrown @zidaneymar @cwhitten
Hi Team,
This is not working. I created a new project from template (AskingQuestionsSample) from 1.0.1 version. I still get same error.
Also, could you please let me know how to fix the project created with 1.0.0 version. Its still showing "user was not found."

**Comment by cwhitten** [comment]
Hi @GAURI02X, can you copy the updated provisioning directory to your bot scripts folder and try again on your 1.0.0 bot?

https://github.com/microsoft/BotFramework-Composer/tree/master/Composer/plugins/samples/assets/shared/scripts

**Comment by hanchen79** [comment]
> @benbrown @zidaneymar @cwhitten
> Hi Team,
> This is not working. I created a new project from template (AskingQuestionsSample) from 1.0.1 version. I still get same error.
> Also, could you please let me know how to fix the project created with 1.0.0 version. Its still showing "user was not found."

Did you fix the issue? I am facing exactly the same issue. I am also using a hotmail Azure subscription.

**Comment by hanchen79** [comment]
> > @benbrown @zidaneymar @cwhitten
> > Hi Team,
> > This is not working. I created a new project from template (AskingQuestionsSample) from 1.0.1 version. I still get same error.
> > Also, could you please let me know how to fix the project created with 1.0.0 version. Its still showing "user was not found."
> 
> Did you fix the issue? I am facing exactly the same issue. I am also using a hotmail Azure subscription.

I pass the AAD tenant ID as a parameter for provisionComposer.js. Then issue is resolved. I think somehow it did not get the corrrect tenant ID when the value is not passed.

**Comment by sandeeptalabathula** [comment]
provisionComposer.js script is picking up the first one in the list which might not be your intended one. 
![image](https://user-images.githubusercontent.com/1611624/88879608-52fcd100-d248-11ea-930f-5f739db88b7a.png)

Try adding below parameter: 
`--tenantId=<AAD Tenant Id>`
