### ISSUE TITLE
How to call a skill action from PVA and pass user utterance for entity extraction

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3163]
I realize this is a bit of an overlapping question between PVA and Composer / Bot Framework. However I have the following scenario;

I have a pizza skill in Composer, with 2 intents (order pizza, order status). It has three activities exposed in the manifest.json:
 - Message (having the skill detect intent & entities)
 - Order Pizza (variables: size, topping)
 - Order status: (variables: order #)

In PVA you can call the message activity, which passes the user sentence and the intent & entities are nicely extracted. However when each activity is called directly when PVA is used to detect the intent, I would like to have the user sentence and detect the entities that are in there. Now it's either drop the user in the skill with the message activity and let the skill handle everything or select an intent directly from PVA, but then the skill has nothing to work with.

I realize I can use PVA to extract the entities and pass them on in the event, but the whole reason was that there is complex date extraction (pizza is example) and the skill needs to handle that.

So ideally I would like to have the option in PVA to:
- Call an event activity
- Pass the users last sentence
- Have the skill extract the entities from the users last sentence

How would I do that?

**Comment by hibrenda** [comment]
The skill can be called directly in PVA instead of call an event activity. 
![image](https://user-images.githubusercontent.com/43408889/82903179-2bad2d80-9f93-11ea-9f24-fe643c4f89c7.png)

**Comment by cxbuilders** [comment]
yes, so the event activity currently never has the last user message, so it's either message or event, I want both.
For entity extraction I would expect in Composer to be a Extract Entities step, which is something needed quite often.

**Comment by hibrenda** [comment]
@luhan2017 @vishwacsena any comments ?

**Comment by luhan2017** [comment]
There is an activityProcessed property in BeginSkill action, will this meet your requirement? @cxbuilders 

![image](https://user-images.githubusercontent.com/32191031/83002177-4fc64880-a03f-11ea-8b8b-d07079cbec1d.png)

**Comment by vishwacsena** [comment]
@Stevenic @clearab @gabog for skills.

**Comment by clearab** [comment]
I believe you should be able to send the original text as a parameter with the event you're sending to your skill, then allow the skill to process that text. You'd use the `value` object in the `activity` object in your skill manifest definition.

https://docs.microsoft.com/en-us/azure/bot-service/skills-write-manifest-2-1?view=azure-bot-service-4.0#activities

**Comment by clearab** [comment]
It would look something like:
```
"orderPizza": {
            "description": "Orders a pizza",
            "type": "event",
            "name": "OrderPizza",
            "value": {
              "type": "object",
              "properties": {
                  "utterance": {
                      "type": "string",
                      "description": "The original utterance."
                  }
            },
            "resultValue": {
                "$ref": "#/definitions/bookingInfo"
            }
        }
```

**Comment by cxbuilders** [comment]
@clearab This is not possible in PVA. When you select an event action from a skill that exposes a property utterance, it cannot be filled in by PVA as it does not allow you to pick that as an input.
Also even when PVA would allow you to do this, how would you run an entity extraction on that utterance property in Composer?

So 2 issues;

- PVA cannot send last user input as a variable into a skill event action
- Composer cannot extract ad-hoc entities from a given variable

As this is a cross platform issue, I hope this can be dealt with from here..

**Comment by sbacha** [comment]
Heyy @cxbuilders ,

PVA allows last user utterance passed to skill by leveraging the activity type “message” in the manifest.

What this means:
Once you switch the activity type to “message” in manifest:
No longer need that input utterance
PVA will send the last thing the user said as part of the 1st request to the skill.
This will allow the skill to leverage its own NLU to determine intent and entities.


Thanks

**Comment by cxbuilders** [comment]
@sbacha As I stated in my original question, I want to be able to do both. Call an specific action AND pass the last user utterance for entity extraction. It does not make sense to be able to either just pass the full utterance and have the skill figure it out OR call an action whilst there is additional entity info in the user utterance in PVA.

So calling an action to start a specific dialog in the skill AND be able to pass the utterance for entity extraction would be the way to go for lots of scenarios.

**Comment by cxbuilders** [comment]
Probably an example will explain this better.

Suppose I have a skill with 2 intents (and entities)
- Boook meeting (startTime, endTime, location)
- Show meetings (date)

Calling the skill from a PVA I currently have two options;
**Message activity**
Create an intent in PVA that catches all meeting related input and call the message action. So Book a meeting tomorrow at 10:00 will activate the Book Meeting intent in the skill and extract startTime.

**Event Action**
This allows PVA owners to have more flexibility and pick and choose certain skill actions they want to use. They would setup an intent in PVA that catches Book Meeting and call the skill Book Meeting event action in the PVA topic. When user enters now "Book a meeting tomorrow at 10:00", the skill's intent is triggered but it does not know about the tomorrow at 10:00 part.

What I want to be able to do is have the Event Action WITH last user utterance. Then in the skill I want to have an Ad Hoc entity extraction (like is possible with any typical bot building tool) and have the PVA owner specifically target an action but still have the power of the last user utterance if there is info about entities in it.

**Comment by sbacha** [comment]
Thank you for the clarification. 
Yup already raised this as a feature request in PVA. You have access to last user utterance in PVA but only "Fallback" topic, the ask would be to expose it for every topic. 

Current workarounds that you can implement to unblock yourself:
Option 1:
You can have PVA extract entities and use these entities as input params to the skill.

Option 2: 
Not the best option but something you can consider :
Keep using the message activity type for skill invocation so you don't lose the user utterance and you can have a "Action Flow" call before the skill in the topic to give you intent id or something that you can pass as input in the skill so you can recognize the intent and call a specific dialog in the skill.
P.S : this will not scale well if you have a lot of topics that requires this scenario since you need to create a unique flow for every topic that requires this.

But will definitely unblock you :)

Thanks, 
Let me know what you think.

**Comment by cxbuilders** [comment]
@sbacha Thanks for creating the request. Option 1 is not possible for the typical complex entities that the skill extracts, option 2 is not something I think we can ask of our internal clients :)

We'll wait for the utterance to be available as input and keep using the current two actions available.
