### ISSUE TITLE
How to use Skills

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#3166]
Is there any refernce to for using skills

![image](https://user-images.githubusercontent.com/51915291/82679544-b2e36400-9c68-11ea-868f-73f3727a160d.png)

**Comment by zxyanliu** [comment]
Hi @KoradaRajesh Here is a [doc](https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill) for your reference.

**Comment by KoradaRajesh** [comment]
Thank you! @zxyanliu

**Comment by KoradaRajesh** [comment]
@zxyanliu I have to add skill manifest and tried to access through a browser but I'm getting like undefined.

![image](https://user-images.githubusercontent.com/51915291/82844538-76c93100-9efe-11ea-8288-8298dab47677.png)

![image](https://user-images.githubusercontent.com/51915291/82844552-8c3e5b00-9efe-11ea-81d1-b00ead75594e.png)
