### ISSUE TITLE
Something went wrong dialog displays in various contexts

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#3167]
## Describe the bug
If I leave version 1.0.0 of Composer running on my Mac overnight, in the morning a "Something went wrong!" dialog is displayed.  Clicking Ok closes the dialog, and best I can tell, the product has no adverse behavior that I can detect.

## Version
1.0.0

## Browser
For this repro, I'm running the Electron distribution on macOS

## OS

- [x ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer
2. Perform authoring activities. (unclear if this has any impact on the issue or not)
3. Leave Composer running overnight.  May also require more than 24 hours to reproduce.  0.0.3 reproduced it overnight.  1.0.0 seems a little more resilient and requires more idle time to repro.

## Screenshots
<img width="675" alt="Screen Shot 2020-05-22 at 9 38 27 AM" src="https://user-images.githubusercontent.com/733559/82689882-07a6c080-9c10-11ea-831e-f49c0aa19afc.png">

## Additional context
I've gotten this regardless of which authoring activity page I'm on.  I've gotten it when I'm on the main authoring canvas.  I've also gotten it when I was on the Publish page.

**Comment by hibrenda** [comment]
@zhixzhan @boydc2014 be aware of this . 
Re-pro similar issues before.

**Comment by bartbilliet** [comment]
@cwhitten ok, duplicate. Although in my experience, this does not only happen after a period of time. It happens live during clicking or typing in Composer and actually blocks me from making basic changes.

**Comment by cwhitten** [comment]
Hi @bartbilliet. I understand. The class of bug is very likely the same. When the team looks at this we will make sure it addresses all scenarios where it manifests.

**Comment by boydc2014** [comment]
This may due to LSP connection break after a long time, @zhixzhan is looking at ignoring this specific issue and reconnect after a certain period.

**Comment by zhixzhan** [comment]
Sure, will fix soon

**Comment by salvo-uk** [comment]
Hi, I'm getting this a lot. It makes the composer unusable. Is a fix forthcoming?

**Comment by sgellock** [comment]
This was fixed months ago.  what version are you running?

**Comment by cwhitten** [comment]
@salvo-uk please open up a new github issue with what you are seeing and reproduction steps and the team will engage and investigate. it is likely unrelated to this particular issue.
