### ISSUE TITLE
Error when trying to use isArray() within an expression

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3168]
## Describe the bug

I get an error when trying to use the `isArray()` function within an expression. It is in fact a valid function:

![image](https://user-images.githubusercontent.com/698939/82718288-7e66ac80-9c56-11ea-8842-ad6ed9d87928.png)

## Version
1.0.0

**Comment by boydc2014** [comment]
this should be also be fixed in https://github.com/microsoft/BotFramework-Composer/issues/3168

**Comment by zhixzhan** [comment]
> this should be also be fixed in #3141, right @zhixzhan

Yes, it's fixed in #3141
