### ISSUE TITLE
Output Code in c# for Version 1.0.0

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#3171]
I have integrated composer in my existing code For Version 0.0.4 when I'm trying to Migrate composer to the latest version in my code I'm unable to find the Output code for newly created dialogs.

I'll be grateful if you provide the Outputcode in C#

**Comment by luhan2017** [comment]
What do you mean by Output code? Can you elaborate more on this?

**Comment by KoradaRajesh** [comment]
Whenever we create dialogs in the previous version of the composer it's generating one solution file in the local system but for now, it's generating only dialog folders. If you provide the solution file as well then it will be helpful.
**File generated for previous versions:**
![image](https://user-images.githubusercontent.com/51915291/82884095-e6700800-9f60-11ea-8f58-6b2f1573cf4a.png)

**File generated for current versions:**
![image](https://user-images.githubusercontent.com/51915291/82884234-191a0080-9f61-11ea-8715-9647d6b2d9ee.png)

**Comment by hibrenda** [comment]
@KoradaRajesh Yes. This is expected for current composer version. you can reference https://github.com/microsoft/BotFramework-Composer/issues/3172#issuecomment-633899040
![image](https://user-images.githubusercontent.com/43408889/82890479-d109d680-9f7e-11ea-930d-0fab1669665b.png)

**Comment by cwhitten** [comment]
Closing as designed. Please utilize the runtime ejection mechanism.

**Comment by KoradaRajesh** [comment]
Sure @cwhitten , Thank you @hibrenda, @luhan2017

**Comment by owenpww** [comment]
Hello @cwhitten and @luhan2017 where is this ejection mechanism in the Mac version2.0.0?
![image](https://user-images.githubusercontent.com/93670080/145241342-e26d0b18-a0b3-49a7-b6ed-231e0579ca5a.png)
