### ISSUE TITLE
folder scaffolding not created

### ISSUE THREAD

**Issue by MartinGudel** [microsoft/BotFramework-Composer#3172]
I'm currently using 
PowerShell 7.0.1 
.NET SDK 3.1.300
node.js version 12.16.3 
yarn 1.22.4
on Windows 10 Enterprise Build 2004
when I create my bots and go to the bots folder, I can see that the folder scaffolding is incomplete.
I get only folders
language-generation
language-understanding
scripts (note the lowercase "s")
settings
Readme.md
mybotname.dialog
(atatched you find an example resulting folder)

but no additional folder structure like the Scripts folder with the create.ps1 and deploy.ps1, no Controllers or ComposerDialogs folders. 
I'm using Bot Framework Composer on other computers with a similar setup but wasn't faced with that, yet.

Unfortunately, when looking for a similar issue on the scaaffolding I didn't find any result.
Is this a known issue? How can I resolve that?

I appreciate your response!
 
  
![scaffolding-issues](https://user-images.githubusercontent.com/29344403/82741124-56a73f80-9d4f-11ea-9ded-200af1b72697.png)

**Comment by IT-Spezl** [comment]
#push

**Comment by PhillipGabold** [comment]
#push

**Comment by luhan2017** [comment]
@PhillipGabold , currently in the latest composer master branch, we folder structure you showed here is expected. If you want to view and edit the runtime, you can do an eject (go to settings page->enable custom runtime), composer will copy the runtime folder into your bot.

**Comment by cwhitten** [comment]
Closing as designed. Please use the runtime ejection mechanism if you want to control the runtime assets. We've also updated the folder structure with this release.

**Comment by owenpww** [comment]
Hello @cwhitten and @luhan2017 where is this ejection mechanism in the Mac version2.0.0?
![image](https://user-images.githubusercontent.com/93670080/145241342-e26d0b18-a0b3-49a7-b6ed-231e0579ca5a.png)
