### ISSUE TITLE
Need extract of ALL copy & labels in a single place for copy edit, review and approval

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3175]
Several issues have been raised about the terms, terminology and UX copy in Composer and how it relates to the SDK (and we're getting several questions about disconnects between terms in Composer and PVA).
In order to create alignment between the SDK, the UX in Composer and PVA (note: alignment does not mean we're using the exact same term everywhere), could we please create a way to extract and review the copy in **ONE place**, so that we can do a series of passes and reviews and with sign off from UX, dev and tech writers on all teams impacted. 
I've spent hours and hours on copy already on this (mostly with Vishwac as well as with Yan) and it remains an ad-hoc approach in which we either overlook things or changes are made without realizing they're impacting other decisions and agreements (this happens both ways: changes in Composer impact decisions in the SDK and vice versa).

@cwhitten @tomlm @Stevenic

**Comment by zxyanliu** [comment]
Here is a list of issue related to terms, I just group them here:

- [ ] https://github.com/microsoft/BotFramework-Composer/issues/1938
- [ ] https://github.com/microsoft/BotFramework-Composer/issues/3262
- [ ] https://github.com/microsoft/BotFramework-Composer/issues/3177
- [ ] https://github.com/microsoft/BotFramework-Composer/issues/2978
- [ ] https://github.com/microsoft/BotFramework-Composer/issues/3174
- [ ] https://github.com/microsoft/BotFramework-Composer/issues/2977
- [ ] https://github.com/microsoft/BotFramework-Composer/issues/2976

**Comment by a-b-r-o-w-n** [comment]
Related to #3458. @beyackle has extracted the copy from the app in order to prep it for i18n. That will be a good first step in centralizing all copy in a single place (with the exception of any sdk/uischema copy)
