### ISSUE TITLE
design: Action Menu Scalability Issues...

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3176]
The current action menu design isn't going to scale...

![image](https://user-images.githubusercontent.com/698939/82769089-be10ce00-9de7-11ea-99b5-9fe42d79c015.png)

It works ok for the current pallet of built-in actions but even just watching the //build VA presentations we had to add 6 or 7 custom actions for performing graph manipulations.  What happens when my project needs 4 - 5 action libraries that add 5 - 10 new actions each?  We could end up needing to show 30 - 40 actions on the custom actions menu.

Toolbox management is a fundamental issue that all visual programming tools have to deal with. The issue is you tend to pull tools into your project in suites but your actual project may only ever use 4 - 5 controls from a given suite. Take a look at [Telerik's Silverlight Library](https://www.telerik.com/products/silverlight/overview.aspx). A single library adds over 100 new controls of which you may use 10.

Looking at our UX I've been trying to figure out where we could expose a proper toolbox and I believe it's in the right pane where the property editor is.  If we look at the current UX we can end up highlighting 2 nodes in blue when you click an insert point. One represents the node represented by the property inspector and the second represents the insertion point:

![image](https://user-images.githubusercontent.com/698939/82769699-85262880-9dea-11ea-975e-eaf0638772ab.png)
 
My thought is we could trim down the action menu that gets displayed to be a simple list of most commonly or recently used actions. A "more" link at the bottom would dismiss the menu and then cause a toolbox panel to be displayed in the right hand pane.  This works UX wise because we would just keep the current insertion point highlighted in blue.  But now we could surface a search box and accordion for browsing actions by category. We could also support the pinning of actions to either the top of the toolbox pane or popup menu.

**Comment by Stevenic** [comment]
@carlosscastro and I have kicked around some ideas for how to use machine learning to essentially learn the 1 - 3 actions that most commonly follow a given sequence of actions. This isn't any different then learning the words to "auto suggest" in a messaging app.  Just replace the words with actions.

**Comment by mareekuh** [comment]
This is a great point.... - I'll add this to our list to look into.

**Comment by Stevenic** [comment]
Closing because it's old

**Comment by mareekuh** [comment]
@vivekkshankar I know you worked on this as well - do we have the most recent work in the build right now?
