### ISSUE TITLE
Composer labels my triggers with weird names.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#3177]
## Describe the bug

When I add an trigger such as OnBeginDialog, OnIntent, OnUnknownIntent, etc. the trigger gets labeled with weird words that don't match our SDK, documentation or samples.  This causes an education burden and cognitive load for our developers because they have to learn what the SDK, Documentation and samples call it, and what composer calls it.

## Version
1.0

## To Reproduce

1. Start Composer
2. Add trigger for OnBeginDialog 
3. When you get the picker you see this.  Where's OnBeginDialog?
![image](https://user-images.githubusercontent.com/17789481/82771338-83f7fa00-9df0-11ea-946b-b1bdf2e86f7a.png)
I have to slow down and read to find the thing I'm looking for and then figure out the words are trying to describe something in a way that is duplicated and complicated.
4. The label that is applied to the trigger is NOT what I just picked, it's somebodies words that got put there.  What is Dialog started?  THE ENTIRE SDK HAS USED **BEGIN** DIALOG FOR 4 YEARS. All 100,000 developers that have used our SDK have used BEGIN DIALOG. 
The API is BeginDialog, the event is OnBeginDialog. 

## Expected behavior

I expect that 
1. The drop down has the ACTUAL WORD **OnBeginDialog** because that is what all of our SDK, conceptual docs and samples have.  Duplicated across **4 languages**.
2. It's great that we can assign a custom label, but the DEFAULT label for a trigger should be the type of the trigger, aka, **OnBeginDialog**.  Because it's a label, the author has the freedom to be able to rename it to anything they want.
NOT this 
![image](https://user-images.githubusercontent.com/17789481/82771550-48116480-9df1-11ea-8aab-fce04749e327.png)
But This
![image](https://user-images.githubusercontent.com/17789481/82771562-51023600-9df1-11ea-91e5-d9ffd7c0dab7.png)
![image](https://user-images.githubusercontent.com/17789481/82771574-565f8080-9df1-11ea-8983-46fd4d27f6d3.png)

This is true for ALL of our triggers. 

Related to this.  Someone decided to rename ResultProperty => Property.  It's not property, because property is ambigious. We spent a lot of time and effort picking names, and they should NOT be changed without filing DCRs to change it across the entire SDK, samples and docs.

**Comment by mareekuh** [comment]
I responded to 3177 in another related issue filed by Tom - this is a larger issue.

I absolutely understand and respect your perspective and request and also have an over arching objective (customer and leadership driven) to align terms and terminology across Conversational AI products, services and teams at Microsoft. But I need your help with this.... 
What can we do to collect some form of overview of ALL the copy and labels? I've tried to manually capture this in here but this is both incomplete and very difficult to manage.
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/doc2.aspx?sourcedoc=%7B68C90DC0-2EA7-4D6B-88B2-9718354499C0%7D&file=terms%20across%20products.xlsx&nav=MTFfe0ExRUJBQzU4LUU5MDYtNDM5OC04MkQyLUM1MTM4RkZDNjE0N31fezYzOEQ0RDAwLUM3RTYtREQ0MS1CQzIyLTQ0NjI2Q0U4NjA1NH0&action=default&mobileredirect=true&cid=bc3028e6-2b3a-4b3d-8898-4e8c88b1097f

We each come at copy and terms from a different strategies and rationale and it's been very hard to tackle these on an one off basis with multiple people making updates in way that matches their strategy but may have an impact on others, including collaboration with PVA, PVA, Speech etc. So in order get us address this issue, and get us out of the place we're in right now with a mishmash of terms and UX copy and labeling strategies, we need to create a better way to collect, and review the current terms and terminology across Composer.

Please help -

**Comment by zxyanliu** [comment]
Thanks for your valuable feedback. Please see https://github.com/microsoft/BotFramework-Composer/issues/3175.
