### ISSUE TITLE
issue with Composer preview vs Composer IDE

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-Composer#3184]
I have tried both the tools and created bot.I found that the code structure generating by both the tools are different my question is i earlier created a weather bot using preview version.

can i import that in composer IDE ?

if yes can anybody suggest the steps.I am new to composer it will be very helpful.

**Comment by cwhitten** [comment]
hi @madbeher. Composer is now Generally Available, and in doing so has updated the directory structure when creating .dialog, .lu, .lg files. The version you used in Composer preview is no longer supported. You need to update your structure to the new mechanism, or re-create your using the Composer IDE.

**Comment by madbeher** [comment]
thanks @cwhitten  please give me more clarity. I have the existing structure is there any command or option available in new composer to update your structure to the new mechanism.

**Comment by cwhitten** [comment]
We do not have a command to automatically update the preview structure to the current structure.

**Comment by madbeher** [comment]
thanks for quick response @cwhitten  please clarify one more doubt.

can we import the new structure code in Visual studio. Because I found that  there is no .sln file present compared to preview version. So how can I import the code in visual studio?
