### ISSUE TITLE
Default location for new bot should be different

### ISSUE THREAD

**Issue by RustyDes** [microsoft/BotFramework-Composer#3189]
## Describe the bug
The first time creating a new project with Composer suggest creating it at the root of the user profile (%USERPROFILE%).

For windows, a more meaningful place would be a subfolder of that such as:
    %USERPROFILE%\source\repos\
or
    %USERPROFILE%\source\bots\

## Version
1.0.0

## Browser

N/A

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch composer
2. Click on New
3. Click on Next
4. See dialog with the Location information

## Expected behavior

Default location to be:
    %USERPROFILE%\source\repos\
(or something along those line)

**Comment by boydc2014** [comment]
This is what i refereed as the pattern of VS in our previous chat, @tomlm @cwhitten what do you think?

**Comment by cwhitten** [comment]
@RustyDes we're closing this as a wont-fix. Defaulting to the user directory is the least opinionated decision we could make, and at the moment we feel this is correct. When https://github.com/microsoft/BotFramework-Composer/pull/3302 the experience of pasting a known path in will be easier and we hope this will address your issue at least partially.
