### ISSUE TITLE
LG templates sometimes automatically replaced with random templates that don't exist

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#3191]
I don't know how to recreate this issue at the moment, but at some point Composer replaced all LG responses and prompts in action nodes with random template references that don't exist. I captured what I got below

![Screen Shot 2020-05-26 at 4 53 07 PM](https://user-images.githubusercontent.com/50963385/82961326-dd3b6700-9f71-11ea-945d-a8ef3b677849.png)
![Screen Shot 2020-05-26 at 4 52 32 PM](https://user-images.githubusercontent.com/50963385/82961327-de6c9400-9f71-11ea-8466-f4efe7445daf.png)
![Screen Shot 2020-05-26 at 4 51 42 PM](https://user-images.githubusercontent.com/50963385/82961328-de6c9400-9f71-11ea-8d0d-dd8d1203de01.png)

**Comment by boydc2014** [comment]
Should be fixed in #3141, we probably need a patch release for this, what do you think @cwhitten

**Comment by hibrenda** [comment]
close this issues as this is addressed in #3141 . @sangwoohaan I hit similar issues before, this is due to LG parsing errors and then all following LG editor will be turn into this
