### ISSUE TITLE
Move skill definitions and feature settings to separate file.

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3204]
## Is your feature request related to a problem? Please describe.

The current `appsettings.json` file contains all of the bots settings including features, appId, password, publishing profiles, and skill bindings.  Since it contains keys it can't be checked in which means the bots enabled featurs and skill bindings also can't be checked in.  The result is the project is in a broken state if you try to run it on another developers machine.

We should break out things like skill bindings and features to a seperate settings file that can be checked in.

**Comment by cwhitten** [comment]
@Stevenic currently the features and the skill settings are needed by the runtime. This is why is all serializes into the settings file.

This is a common convention for web developers today, in that you share your settings files via other means than git. Zerobin is an example to securely share these types of files with sensitive information in them. I'm not sure why Composer needs to add additional layers on top of this convention.

**Comment by cwhitten** [comment]
.botproj is such a file. Closing
