### ISSUE TITLE
composer with visual studio

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-Composer#3206]
can we import the new composer  structure code in Visual studio. Because I found that there is no .sln file present compared to preview version. So how can I import the code in visual studio?

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/3171#issuecomment-633943571
please reference this. using eject can easily help you get the runtime code .

**Comment by owenpww** [comment]
Hello @hibrenda where is this ejection mechanism in the Mac version2.0.0? The github issue you seem to be referencing is old.
![image](https://user-images.githubusercontent.com/93670080/145241342-e26d0b18-a0b3-49a7-b6ed-231e0579ca5a.png)
