### ISSUE TITLE
Access to Passwords in Azure Devops

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3208]
I am currently setting up a pipeline in Azure Devops that deploys the resources and builds & publishes the Composer bot. So far all is working great, however I am not sure how to deal with passwords in the following scenarios;

**Initial Pipe Line run -> Deploying Resources**
- In the deployment step I have a PowerShell script that generates a new appSecret. This is then used in the deployment of the resources using the arm template.
- The returned output from the arm template contains additional passwords for luis etc. that Composer needs
- I currently echo these in the pipeline steps and copy these values back into the Composer settings again which is not nice. I would somehow like to store these back into the repo for Composer to pick up with a pull. How could I do this?

**Consequent Pipe Line runs -> Building & Publishing**
- In order to publish to Luis I need the Authoring Key in DevOps. How can I get this?

At a later stage I want to integrate the push to a repo in Composer, so that the whole flow is automated. I do need to get this sorted out first though.

**Comment by VanyLaw** [comment]
Hi @cxbuilders, Do you mean you setup a pipeline for Bot to do the CICD whenever the Bot update? I think you can go through the provision to get resources first. Then set those into `appsettings.deployment.json` which composer also did the same operation in deploy. But I'm afraid you need to get your accessToken update everytime you run the pipeline (maybe you can set in yaml file).
Authoring Key can get in provision step. you just need to set into `appsettings.deployment.json` I think.

**Comment by VanyLaw** [comment]
Maybe this Doc can help you.
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/apps/devops-cicd-chatbot

**Comment by cxbuilders** [comment]
@VanyLaw The pipeline handles both deployment and publishing of the bot. During publishing however I want to update Luis and I need to extract the Luis key from the repo somehow. How can I do this?

**Comment by VanyLaw** [comment]
@cxbuilders, luis key is come from azure luisAuthoring resource (check it in azure portal Keys and Endpoint) or luis portal. It's not generated by composer or Bot, So I think you don't have to extract the Luis key from the repo. You can just set your luis key you get from azure resource in pipeline.

**Comment by cxbuilders** [comment]
@VanyLaw Yeah I extract it from the arm deployment step in my pipeline and output that. Then I copy these settings over in Composer Bot Settings. So Composer does have it somewhere (it removes the keys from the settings and stores is where?)

I guess for now I will take the pipeline variables route and keep the secrets there.

**Comment by VanyLaw** [comment]
Because of secrecy problem, we won't persist luiskey into settings file in disk. We save those value into localStorage in Browser.

**Comment by VanyLaw** [comment]
Another way is you can eject runtime in composer and make some changes under runtime folder. Then  using the customized runtime to do the publish.
