### ISSUE TITLE
Replace edit mode toggle with a simple user mouse click on the resource

### ISSUE THREAD

**Issue by hristp** [microsoft/BotFramework-Composer#3214]
There's an Edit mode in Bot Responses and User Input. However, the current design feels a little bit awkward -- the edit mode is up and above and very easy to miss.

How about just going into edit mode when a user clicks on a resource (see attached), and then stopping editing by clicking away from the editing space? This feels more intuitive than the extra clicks.

![Composer_Edit](https://user-images.githubusercontent.com/17205657/83184431-4fc95580-a0de-11ea-9070-d4bcd6208290.jpg)

**Comment by hibrenda** [comment]
@mareekuh @sangwoohaan

**Comment by mareekuh** [comment]
Edit on click should allow the user to edit directly in the list view but not jump to the Editor.
@hibrenda
