### ISSUE TITLE
Question: Are [Suggestions] supported?

### ISSUE THREAD

**Issue by knightmeister** [microsoft/BotFramework-Composer#3216]
Apologies for raising an issue to ask a question, but I've spent a lot of time on this and I've been able to get everything else I need working with the exception of suggestions. If there is some documentation I've somehow missed, please point me towards it. 

I became aware of Suggestions due to autocomplete in composer. It shows as `[Suggestions]` with a `SuggestedActions` property/attribute.

I raised a [question](https://stackoverflow.com/questions/62059108/what-is-the-correct-way-to-send-suggestions-to-the-user-with-the-suggestions-r) on StackOverflow yesterday where I explain the situation.

I am trying to return a suggestion to a user as a CardAction. I define a function called `urlCard` as so:

```
# urlCard(title, value)
[CardAction
    Type = openUrl
    Title = ${title}
    Value = ${value}
]  
```

When I try to use this action, like this:
```
[Suggestions
      SuggestionActions = ${urlCard( 'Google', 'https://google.com/' )}
    ]
```

Everything validates fine, but I get JSON rendered in the Bot Framework Emulator:
![image](https://user-images.githubusercontent.com/1528425/83222043-bde34a80-a1ba-11ea-836b-7cbd25a4e11b.png)

Would appreciate any pointers.

**Comment by hibrenda** [comment]
```
# urlCard(title, value)
[CardAction
    Type = openUrl
    Title = ${title}
    Value = ${value}
] 

# activityWithSuggestionActions(title, text)
[Activity
    Text = what do you like
    SuggestedActions = firstItem | ${urlCard(title, text)}
]
```
