### ISSUE TITLE
HTTP Request properties "learn more" tooltips link botbuilder-samples

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#3222]
## Describe the bug
For the HTTP Request property sheet, the "Learn more" links for the "?" help icons all navigate to BotBuilder-Samples/experimental/common-expression-language/README.md file on GitHub

## Version
1.0.0

## Browser

Electron distribution
## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot project
2. On the design canvas, add an HTTP Request by [+] -> Access external resources -> Send an HTTP Request 
3. From the property sheet for the HTTP Request invoke the tooltips for any of the following properties:  Url, body, result property, content type, or response type.
4. Click on the "Learn more" link found in the tooltip.

We launch a browser window that displays the boatbuilder-samples/experimental/common-expression-language README.md on GitHub.
 
## Expected behavior
Expect to see a browser window launched that takes me to appropriate documentation

**Comment by zxyanliu** [comment]
Hey @sgellock Thanks for reporting the broken doc link. I have already fixed it in [PR3238](https://github.com/microsoft/BotFramework-Composer/pull/3238).
