### ISSUE TITLE
"Learn more" link in settings page is a 404

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#3224]
![image](https://user-images.githubusercontent.com/17152540/83288305-faea1580-a197-11ea-81af-959aa26aacd0.png)

**Comment by zxyanliu** [comment]
Hey @Andrea-Orimoto Thanks for reporting the broken doc link. I have already fixed it in [PR3238](https://github.com/microsoft/BotFramework-Composer/pull/3238).
