### ISSUE TITLE
Publish Bot to azure

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#3226]
I am trying to publish the bot to azure using bot framework composer. I already have required app services created in azure. i am providing values in json but its throwing error "Error: getaddrinfo ENOTFOUND name-environment.scm.azurewebsites.net".  

i am not using "applicationInsights","cosmosDb" and "Luis".

Here is my json.

{
  "accessToken": "<AccessToken>",
  "name": "<Name of the app service>",
  "environment": "dev",
  "settings": {
    "MicrosoftAppId": "<App id of app service>",
    "MicrosoftAppPassword": "<Password of app service>"
  }
}

________________________
I tried like this also

{
  "accessToken": "Bearer <access token>",
  "name": "Web App name",
  "environment": "dev",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": ""
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "",
      "authKey": "",
      "databaseId": "",
      "collectionId": "",
      "containerId": ""
    },
    "blobStorage": {
      "connectionString": "",
      "container": ""
    },
    "luis": {
      "endpointKey": "",
      "authoringKey": "",
      "region": ""
    },
    "MicrosoftAppId": "***************",
    "MicrosoftAppPassword": "****************"
  }
}

**Comment by KoradaRajesh** [comment]
Basically my existing bot app service name is **pocbotdev** I gave the name in publish JSON like **pocbot** and environment like **dev** it's combing the name and environment with **-** and  it trying to find the bot app service with **pocbot-dev** but the actual name is **pocbotdev**

**Comment by VanyLaw** [comment]
Hi @KoradaRajesh, currently, we set resource group name like `${name}-${environment}`; If you service name is `pocbotdev`, you can add `hostname: pocbotdev` in your json profile and try again.

**Comment by benbrown** [comment]
@KoradaRajesh as @VanyLaw said above, add the `hostname` key to your publish profile at the root level with the name of your already existing resource.

```
{
  accessToken: '...',
  name: '...',
  hostname: '...',
  ...
}
```
