### ISSUE TITLE
Cut, copy paste appears to not work with a selected action

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#3227]
## Describe the bug
I'm unable to cut or copy a selected action
 
## Version
1.0.0

## Browser
- [ ] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer
2. Open a bot project that has a dialog
3. Open the dialog in the design canvas that has more than one action
4. Select an action
5. Edit.Cut or Edit.Copy
6. Click on a + sign in the design surface to paste the action
7.  Notice that paste is disabled.  Also notice that Edit.Paste from the main menu is enabled.

## Expected behavior
Expect to be able to paste the action

## Screenshots
<img width="1071" alt="Screen Shot 2020-05-29 at 11 13 18 AM" src="https://user-images.githubusercontent.com/733559/83291580-6d112900-a19d-11ea-82bc-008b4299774b.png">

**Comment by cwhitten** [comment]
The workaround is to use the Command bar in the application to take these actions. The bug is that Cut/Copy/Paste from the Edit menu simply do not work right now. Related: https://github.com/microsoft/BotFramework-Composer/issues/3225

**Comment by yeze322** [comment]
Seems the bug only appears on Safari. It works on Windows platform. Could anyone help validating if it work on Chrome for Mac? We don't have a Mac for testing.

BTW where is this button `Edit.Paste from the main menu`?

**Comment by yeze322** [comment]
I'm not sure if I got the repro steps accurately, but didn't repro it under Windows environment.
Then I asked Zhixiang to verify it on Macbook
![copy-on-safari](https://user-images.githubusercontent.com/8528761/83390934-4ebd5e80-a425-11ea-8255-6d3ad105bdef.gif)

**Comment by yeze322** [comment]
If the bug still exits, I guess it's related to the module `FrameAPI` which should be retired after we removing iframe.

**Comment by benbrown** [comment]
@yeze322 I believe Scott here is referring to the "system" edit menu that appears in the windows app, not the Composer app toolbar.

**Comment by sgellock** [comment]
@yeze322 @benbrown yes, ben is correct.  On macOS there are application top-level menus that allow what is being replicated in the actual application toolbar.  
<img width="267" alt="Screen Shot 2020-06-01 at 10 29 37 AM" src="https://user-images.githubusercontent.com/733559/83436574-f3727880-a3f2-11ea-8ba7-2f5182c1f8c9.png">

**Comment by yeze322** [comment]
@benbrown @sgellock thanks all! I got it

**Comment by yeze322** [comment]
Investigated this issue, not likely to fix it in Composer Web, probably we can fix it in Compose Electron.

The [Menu Bar menus](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/) are controlled by MacOS, pressing a keyboard shortcut can trigger that event; but clicking on the menu won't fire key pressing events. Thus our Keyboard Shortcut listener will never receive those menu events.

It's the applications' (Chrome / Safari) duty to adapt to Menu Bar menus, they can even customize that Menu in OC.
In Composer Web, the only thing we can do is leveraging browser native features, however, our cut/copy/undo/redo operations are not just plain text edit;
in Composer Electron, it may be possible to adapt to MacOs Menu.

**Comment by cwhitten** [comment]
@yeze322 why are you labeling this as Blocked?

**Comment by yeze322** [comment]
> @yeze322 why are you labeling this as Blocked?

Oh did I misused this label? I marked it as 'blocked' because I thought we may not be able to fix this issue in Composer Web. Need help on fixing that

**Comment by yeze322** [comment]
@cwhitten Chris I heard that you had a solution on adapting the system menu in Electron app, can that solution work in the web app as well?

**Comment by yeze322** [comment]
addressed in #3660
