### ISSUE TITLE
Minimap shows for LG editor and I'm not able to hide it

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#3229]
## Describe the bug
the LG editor is displaying the minimap.  see the attached image below.  I can't figure out a way to hide it

## Version
1.0.0
## Browser
- [ ] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce
I'm not sure how I got into this state.

## Expected behavior
no minimap, or at least a way to toggle the minimap so I can hide it.

## Screenshots
<img width="566" alt="Screen Shot 2020-05-29 at 11 40 29 AM" src="https://user-images.githubusercontent.com/733559/83294401-1d812c00-a1a2-11ea-9d68-8f62d2fdf3cd.png">

**Comment by cwhitten** [comment]
You can hide the minimap by going to Settings -> App settings -> Minimap

**Comment by sgellock** [comment]
@cwhitten thanks Chris.  that did it.
