### ISSUE TITLE
Learn more links should open in a regular browser window

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#3230]
## Describe the bug
The current Learn more links, and there may be other links that exhibit this behavior as well, don't open a normal browser window.

## Version
1.0.0
## Browser
- [ ] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce
1. From the property panel, hover over a property that has a tooltip that has a Learn more link.
2. Click the Learn more link
3. A limited browser window opens.  

## Expected behavior
Would like links to help content or external website links to open as part of my normal browser functionality.  e.g. in a new tab

this will give me bookmarking functionality and browser history, etc.

**Comment by cwhitten** [comment]
To fixer: the Electron environment is causing this. To preserve the web support we need to wrap _all_ external link areas with the knowledge if it is running inside Electron or not. 

Here is an example of this: https://github.com/microsoft/BotFramework-Composer/blob/master/Composer/packages/client/src/pages/home/ItemContainer.tsx#L79

Electron API: https://www.electronjs.org/docs/api/shell#shellopenexternalurl-options

**Comment by tonyanziano** [comment]
Fixed by #3326
