### ISSUE TITLE
Usability: Hard to figure out why "Intent recognized" trigger is not available

### ISSUE THREAD

**Issue by arturl** [microsoft/BotFramework-Composer#3232]
The "Intent recognized" trigger type is only available if the dialog has a non-None recognizer type. 
It took me a long time to figure it out. Options:
- Make RegEx the default recognizer type for new bots
- Show "Intent recognized" in the list and if the user picks that, set the dialog recognizer during that process.

**Comment by hibrenda** [comment]
Thanks Artur, @mareekuh & @sangwoohaan be aware of this

**Comment by benbrown** [comment]
I think this is a good suggestion!

**Comment by mareekuh** [comment]
I do too - I'd rather not have Regex by default, but when the user picks intent we should do the right thing.  (I thought this was already the case- I think this has come up before)

**Comment by sangwoohaan** [comment]
I like the second option. Great suggestions!

**Comment by hibrenda** [comment]
More triggers will be introduced which may attach to different recognizer type as well.  
eg. QnA Recognizer for  OnQnAMatch , RecognizerSet(LUIS+QnA) for OnChooseIntent.
So we may need more discussion for the consistent UX experience.

**Comment by hibrenda** [comment]
Addressed and solved in Composer 1.1.1
