### ISSUE TITLE
How to get Max turn count value

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#3235]
I'm trying to give an invalid response to the user based on the Max turn count value but I'm unable to get the value. How can I achieve this?

if bot re-prompt user for first time different invalid response 
if it is second time another invalid response

for each turn, I want to catch that increasing max turn count

**Comment by luhan2017** [comment]
you can use "this.turncount" @KoradaRajesh

**Comment by KoradaRajesh** [comment]
Thank you! @luhan2017
