### ISSUE TITLE
UAC prompts me to uninstall Composer

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/BotFramework-Composer#3237]
After successfully exiting from Composer. A prompt appears on my screen asking me to give permission to old-uninstaller.exe to actually uninstall the Composer _that too from an uknown source_

## Version

1.0

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [x] Electron app

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Exit the Composer client and the popup will appear.

## Expected behavior

There shouldn't be such popup. 

## Screenshots

![b4d2324a-356c-4b6c-8437-b7d2f3ef360b](https://user-images.githubusercontent.com/16351038/83331562-5de3c580-a2da-11ea-851a-7812f7573f5d.jpg)

**Comment by cwhitten** [comment]
@arafattehsin could you have installed a pre-release version of the desktop application?

@tonyanziano does this look familiar to you?

**Comment by arafattehsin** [comment]
Hi @cwhitten - there may be a possibility but I remember it downloading after Build's announcement. I can download the fresh one and re-install this again tomorrow and update you folks here.

**Comment by arafattehsin** [comment]
Hi folks! I re-installed from the link provided in the docs - the issue still persists. As soon as I close the Composer, it prompts me to uninstall.

**Comment by bartbilliet** [comment]
I'm experiencing the same issue: 

Enabling the **Early Adopters** feature does uninstall Composer, but doesn't succeed installing the new build. No error messages are shown, but Composer just gets uninstalled every time after the Electron app is closed. 

**Steps to reproduce the behavior:**

1. Activate in **Settings** the **Auto update** and **Early Adopters** features, such as in screenshots below. 
2. Click **Check for Updates**
3. Watch how a new nightly build is downloaded to: C:\Users\<username>\AppData\Local\@bfc\electron-server\pending\BotFramework-Composer-1.0.0-nightly.134872.10c809a-windows-setup.exe
4. Exit Composer. 
5. A prompt will be shown in UAC to uninstall the existing version of Composer (see screenshot below). 
6. Nothing happens after uninstall, Composer gets successfully uninstalled, but the nightly build does not get installed. 

![image](https://user-images.githubusercontent.com/23324404/83417524-81198c80-a422-11ea-817d-951659f836ec.png)

**Workaround:**

Disable the **Early Adopters** feature in **Settings**

**Comment by tonyanziano** [comment]
Sounds like it's related to this issue:

https://github.com/electron-userland/electron-builder/issues/2363

I'm looking into it.

**Comment by tonyanziano** [comment]
@arafattehsin & @bartbilliet when you install the app can you try installing it for the current user only by selecting the following radio button in the installer:

![image](https://user-images.githubusercontent.com/3452012/83458268-16af1f00-a417-11ea-9c39-dca3980775e9.png)

Another alternative would be to make sure you are running Composer as an administrator if possible.

It seems like there might be some underlying issue when updating where Composer is running the old uninstaller script to get rid of the old version, and then fails to install the downloaded update due to not having sufficient permissions (when installing for all users on a machine).

**Comment by bartbilliet** [comment]
@tonyanziano Your assumption seems correct. When running as "only for me" the UAC dialog does not appear, and installation seems to work (at least from what I can see in add/remove programs). 
After installation, however, I can not open Composer. Clicking the start menu & desktop icons launches 3 processes in task manager, but no UI is loading. But that might be a different issue (maybe a problem with the current nightly build). 
Same results when installed for 'all users' and running composer as admin

![image](https://user-images.githubusercontent.com/23324404/83464272-a6cd8280-a470-11ea-9f96-7db0123a873b.png)

**Comment by arafattehsin** [comment]
Yes, the **Only for me** option works well now.

**Comment by tonyanziano** [comment]
Another Composer dev and myself looked into this issue and it seems that the following factors result in the UAC prompt (all 3 conditions must be true):

- The user installed Composer "for all users"
- The user **did not** run Composer as admin
- The user enabled the auto updates (silent install) option

Some workarounds for this include:

- Install Composer for "only current user"
- Install Composer "for all users" but run as admin
- Install Composer "for all users" but disable auto updates (silent installs) option. This will result in an update dialog being shown, which should guide you through the update process manually and will result in a successful install.
