### ISSUE TITLE
Regex pattern in if condition

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#3240]
Can we create if condition using regex

![image](https://user-images.githubusercontent.com/51915291/83339461-b96a7f00-a2eb-11ea-80dc-e9c8a931edb7.png)

**Comment by cwhitten** [comment]
Does this work if you write:
`=isMatch('dk8439', '([a-z]|[A-Z])')`

**Comment by KoradaRajesh** [comment]
Thank you! @cwhitten
