### ISSUE TITLE
Intruptions for intent

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#3241]
I'm trying to allow interruption only for Particular intent how can I mention the only intent interruption

I have tried the below but it's not working

![image](https://user-images.githubusercontent.com/51915291/83344931-f0ac5080-a32a-11ea-841c-ff7948a54c95.png)

**Comment by cwhitten** [comment]
@KoradaRajesh see the Interruptions sample for correct use of Allow Interruptions. You can't specify an exact intent.

**Comment by KoradaRajesh** [comment]
I found some intents are getting added into Luis but I didn't get those intents in the dialog folder and there are no triggers as well

![image](https://user-images.githubusercontent.com/51915291/83363461-4cbcb680-a3b7-11ea-9bf9-51d8d799eed7.png)
