### ISSUE TITLE
Integrate Luis Active Learning

### ISSUE THREAD

**Issue by bartbilliet** [microsoft/BotFramework-Composer#3244]
## Is your feature request related to a problem? Please describe.

I'm trying to transition from an existing bot logic & Luis app to Composer, to benefit of the integrated approach of intent recognition & dialogs. Bot Framework Composer allows to author Luis intent recognition right from within the Composer UI and then publish these intents and sample utterances to a Luis app. 
I used to improve the Luis model via active learning. Luis allows active learning, which captures endpoint queries and selects user's endpoint utterances that it is unsure of. You can [review these utterances in Luis](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-how-to-review-endpoint-utterances) to select the correct intent and mark entities for these read-world utterances. These changes are then added to your example utterances and used to further train the Luis app. 
Correct me if wrong, but I don't think there is an easy way today to integrate Luis active learning with utterances authored from within Composer. 

## Describe the solution you'd like

Currently, the active training part happens purely in the Luis.AI portal via 'review endpoint utterances', and Composer has no way to know about any changes made to the Luis utterances. Actually when publishing updates to the bot in Composer, the utterances that were added via the Luis.AI portal are even lost.
It would be great to have a way to either import added or changed Luis utterances back into Composer, or do the real-world utterances review process entirely from within the composer UI. 

## Describe alternatives you've considered

Currently I'm manually exporting the updated Luis utterances as .Lu files, and doing the rewriting work to get this merged back to the utterances existing in Composer.

**Comment by tdurnford** [comment]
@vishwacsena Do you have any thoughts/updates on this issue?

**Comment by ninggao** [comment]
@darrenj  can you take a look on this please?

**Comment by ninggao** [comment]
@darrenj Any updates on this one?

**Comment by cwhitten** [comment]
hi @bartbilliet, we will take this as a feature request and look to plan and prioritize this in an upcoming release.

**Comment by SChandlee-ARIFleet** [comment]
Hello,
I am interested in similar functionality. Is there an update or alternative solution?
Thank you
