### ISSUE TITLE
Add ctrl+click and shift+click support to multi-select

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3249]
Currently you have to use mouse drag to select multiple nodes in composer. Windows users expect to be able to use `ctrl+click` and `shift+click` to toggle item selection.  `shift+click` performs ranged selection and `ctrl+click` toggles the selection of a single item.  It would be nice if composer supported these key bindings in addition to mouse drag.

Additionally, you don't disable the property editor when multi-selecting. You should either re-scope the property editor to show only common properties or disable it all together.

**Comment by yeze322** [comment]
I remembered it used to be on the R9 feature list, we cut it due to timeline pressure. @alanlong9278 can help with that.

**Comment by cwhitten** [comment]
The Mac behavior would be `cmd+click`.  @yeze322 do you have bandwidth to look at this in R10?

**Comment by yeze322** [comment]
I can start from Ctrl + Click which is much easier than Shift + Click.

**Comment by sangwoohaan** [comment]
Just checked out the feature, I noticed some loose ends.

Scenario 1.
- You have a node that isn't part of any condition or loop(let's call this node A).
- You have a switch branch with multiple conditions and have some nodes on each of them.
- You selected node A, and the shift-clicked nodes in one of the branches. 
- The selection shows you have only selected node A, the switch node, and nodes in one branch, but when you CRUD the selection actually includes the entire switch branch. There's a gap between what you see and the actual selection.

Scenario 2.
- You have two if/else nodes(if A, if B)
- You have nodes in them(if A - nodes, if B - nodes)
- You selected an if A - node, and then shift-clicked an if B - node. 
- The visual selection includes if A - node, if B, if B - node. But the actual selection is if A - node, and everything in if B.
- As well as the gap mentioned in Scenario 1, I see edge case problems with across-loop selections.

Suggestion
1) Regardless of multi-selecting, when you clicked on a loop / condition node, the visual selection should include every node embedded in it. 
2) When you shift-clicked or drag-selected nodes across different loops, it expands the selection to the entire node. So in scenario 1, when you shift-clicked the nodes in a branch of the switch node, the selection should automatically expand to node A - the switch node - everything embeded in it. In scenario 2, the end result should be 'the entire if A node group and the entire if B node group'.

Ctrl-click is relatively dry and simple so it wouldn't have the same problem. It would still share the same rule about the selection a condition / loop node. When you ctrl-clicked an if branch, it would select the entire group.

**Comment by yeze322** [comment]
@sangwoohaan We have double-selection feature applied in TextInput to indicate that user selected all of the three parts in a node. Not sure if this design language can be applied here as well.
