### ISSUE TITLE
Add Find & Replace feature

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3250]
## Is your feature request related to a problem? Please describe.

Refactoring variable names in composer is a bit of a pain. It would be great if there was a Find & Replace feature that you could use for this. For example I could enter "dialog.item" as the find string and "dialog.timer" as the replace string.  Pressing <next>/<previous> would move me between nodes containing "dialog.item".  Hitting <replace> would replace "dialog.item" for the current node with "dialog.timer".  Hitting <replace all> would just replace them all.

**Comment by mareekuh** [comment]
@DesignPolice - Could you add this scenario to your Search designs and see if we can make this work?
