### ISSUE TITLE
Compare new luis model vs current production (batch testing)

### ISSUE THREAD

**Issue by bartbilliet** [microsoft/BotFramework-Composer#3252]
### Compare a new Luis model in Composer vs Luis model in production
Luis has a [batch testing](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-concept-batch-test) feature which allows to check if your newly added utterances will not negatively affect existing intent recognition. 
It would be great to have the ability to run batch testing from Composer to see upfront how changes made to User Input will influence the intent recognition results, compared to the current Luis model used in production. When implementing this type of feature, it should be possible to run batch testing in Composer before publishing updates to the bot in Azure.

**Comment by hibrenda** [comment]
BF CLI tool (bf luis :test) has already support the luis testing through .lu file format. We may need more design in UX part. @sangwoohaan @mareekuh .

**Comment by mareekuh** [comment]
Agreed - we need lu testing, better integrated with the product. I have some designs for this but they're older.

**Comment by bartbilliet** [comment]
@mareekuh if you need feedback, let me know 😉

**Comment by tdurnford** [comment]
@mareekuh Do you have any updates to report?

**Comment by mareekuh** [comment]
I do not - it's on the Design backlog. 
@bartbilliet  - I am very familiar with the feature/functionality that is currently available in LUIS, but it would help to get more specifics around the scenarios in which batch-testing and/or evaluation of language model/understanding would enable/improve your/your customers' bots. Or, without these capabilities, the hurdles you experience or need to find work-arounds for? I can incorporate these when defining and prioritizing solutions.

groetjes,
Marieke
