### ISSUE TITLE
Unable to load web application in an IFrame using Microsoft Edge browser.

### ISSUE THREAD

**Issue by SowmyaPitchika-Acu** [microsoft/BotFramework-Composer#3254]
I'm trying to load the web application on the Intranet web page through IFRAME. I'm getting the below error using microsoft edge browser but working fine with other browsers like chrome and IE. Web application is enabled with Azure AD Authentication.
![image](https://user-images.githubusercontent.com/60602402/83378804-88777080-a3f7-11ea-813b-8866c9f24aff.png)

**Comment by benbrown** [comment]
Hi @SowmyaPitchika-Acu  - what web application are you talking about, and where is it hosted?

**Comment by SowmyaPitchika-Acu** [comment]
Hi @benbrown,
1. Asp.Net Webforms application hosted in Azure.
2. Loading this web application on the Intranet web page through IFRAME.
3. Enabled Azure AD Authentication.
4. The intranet is SSO enabled with OKTA.

**Comment by benbrown** [comment]
@SowmyaPitchika-Acu Sorry, does this have to do with Bot Framework Composer?

**Comment by cwhitten** [comment]
@SowmyaPitchika-Acu we're not sure how we can help you. This repository is for Bot Framework Composer. Closing.
