### ISSUE TITLE
Saving a new bot doesn't let me create a new folder for it

### ISSUE THREAD

**Issue by hristp** [microsoft/BotFramework-Composer#3260]
Could be either a bug or a feature, but this functionality is pretty standard, so I'm leaning towards bug.

When creating a bot, the folder selection pop up only allows selecting an existing folder. Should be allowed to create a folder here, too.

**Comment by hibrenda** [comment]
@hristp  Thanks for the feedback. This a feature and we are aware of this . so label change to Enhancement.

**Comment by liweitian** [comment]
It is also required in #3302, I am working on it.
