### ISSUE TITLE
Action - Ask Question: String validation Expression - Doesn't appear to work 

### ISSUE THREAD

**Issue by Todd442** [microsoft/BotFramework-Composer#3261]
There doesn't appear to be a way to validate a sting value enter in the "Ask Question" action.

The weather sample uses a "length(this.value) == 5" expression to validate the users entered value. 

What if you need to actually do a string comparison "this.value == 'full'" as an example. 

I have tried using 'string(this.value) == 'full'"

I can confirm this works if I use any fuction that processes "this.value" and returns a numeric value. 

Its only string compare that doesn't seem to work (or is it not supported"

![image](https://user-images.githubusercontent.com/7561232/83453324-e7e97680-a41f-11ea-9184-5ed30de2347b.png)

**Comment by hibrenda** [comment]
@Todd442  this should work.
![image](https://user-images.githubusercontent.com/43408889/83520599-7f2df700-a510-11ea-9eef-6b29e8135b7e.png)

**Comment by Todd442** [comment]
@hibrenda - Confirmed this does not work. I have others also confirm this is an issue

**Comment by Todd442** [comment]
@hibrenda - BTW: Thanks for responding. Further clarification, we tried the above as well as about 15 different permutations and as long as you include a built in function like "length" the content of "this.value" is evaluated. 

The simple string comparison above just doesn't work.

**Comment by hibrenda** [comment]
could you attache the bot you are using  so we can further debug?

**Comment by Todd442** [comment]
[WeatherTutorial.zip](https://github.com/microsoft/BotFramework-Composer/files/4717877/WeatherTutorial.zip)

Here's the code. @hibrenda

**Comment by tdurnford** [comment]
@Todd442 In the "User Input" tab on the Text Input component, you have the  'Output format' property set to `=toUpper(this.value)` which is causing the validation to fail. I recommend that you either remove the 'Output format' or change the validation to match that logic - `this.value == 'FULL'`.

**Comment by zxyanliu** [comment]
Hey @Todd442 thanks for reporting the issue. Please try again as suggested by @tdurnford and @hibrenda. 
Closing this issue at this moment since it's been answered. 
Feel free to reopen it when you feel necessary. We appreciate your feedback.
