### ISSUE TITLE
Be able to drag and drop dialog elements in the visual editor

### ISSUE THREAD

**Issue by hristp** [microsoft/BotFramework-Composer#3263]
Would be great to select an element (e.g. send a response), and drag it to a different location.

This would make moving elements much easier, as well as more user-friendly to fix an element accidentally put in the wrong place.

**Comment by yeze322** [comment]
Link our previous discussion in #510. @cwhitten what's your opinion on this feature?

**Comment by cwhitten** [comment]
My opinion is that it is still a nice to have. Not in scope for [Fe] but we can keep it on the backlog.
