### ISSUE TITLE
LUIS Scoring not evaluated in trigger evaluation

### ISSUE THREAD

**Issue by Todd442** [microsoft/BotFramework-Composer#3264]
![image](https://user-images.githubusercontent.com/7561232/83453885-e66c7e00-a420-11ea-92d5-ba620c6a8ecc.png)

If you also include another dialog that asks for user input that allows for interruption, Other dialogs trigged based on LUIS intents are fired even though their scores do not meet the threshold.

please note the LUIS score returned during testing yet the Cancel rule required a great than .8 confidence

![image](https://user-images.githubusercontent.com/7561232/83454010-19167680-a421-11ea-83c6-80c55b6761b2.png)

What am I missing here?

**Comment by luhan2017** [comment]
@Todd442 I tried the ToDoBotWithLuisSample in composer which have similar functionalities, but it worked fine in my side, could you share more details of your bot logic or zip your bot and share? Then I can help debug on this.

**Comment by Todd442** [comment]
@luhan2017 Thanks for responding. I was using the Weather tutorial as the base then added another dialog triggered on a different intent. This works as expected. It was only when I added as Ask Question activity with "allow interruption" == True that this occurs. 

I will see if I can package that up today and include it here
