### ISSUE TITLE
provisionComposer.js should create a full bot, rather than a bot registration

### ISSUE THREAD

**Issue by hristp** [microsoft/BotFramework-Composer#3265]
I followed this doc: https://docs.microsoft.com/en-us/composer/how-to-publish-bot

I ran the provisionComposer.js script:
node provisionComposer.js --subscriptionId=<YOUR AZURE SUBSCRIPTION ID> --name=<NAME OF YOUR RESOURCE GROUP> --appPassword=<APP PASSWORD> --environment=<NAME FOR ENVIRONMENT DEFAULT to dev>

But this provisioned a bot registration. I was expecting this to have deployed my full bot and work right away in Test in WebChat. However, it didn't, because it's a bot registration.

Could the script provision a full bot (and upload the bot code, too)?

**Comment by luhan2017** [comment]
@hristp , the provision script is just designed for creating services/resources in azure, for a deployment, you should 

1. Add new profile and paste your provision result there.
2. Publish to selected profile

Thanks for your feedback, we will continue to improve the publishing experience in our next release.

**Comment by hibrenda** [comment]
close it as this is the expected design.
