### ISSUE TITLE
Docs: Publish to Azure Functions

### ISSUE THREAD

**Issue by bartbilliet** [microsoft/BotFramework-Composer#3268]
The [docs pages on how to publish a bot to Azure](https://docs.microsoft.com/en-us/composer/how-to-publish-bot#create-azure-resources) are well written, but mostly with only Azure Web App publishing in mind. Please include in the docs pages that parameter `-customArmTemplate` with value `DeploymentTemplates/function-template-with-preexisting-rg.json` is required in the 'node provisionComposer.js' command to deploy the bot to Azure Functions. 

Since the Composer UI still allows to create a publishing profile to publish to Azure Functions (even though the node provisionComposer.js, as listed in the docs, deployed the Azure WebApp Services), it took me quite some time to figure out why I was not seeing an Azure Function appear in Azure after publishing via the Azure Functions publishing profile. 

Ultimately the option to create a publishing profile should be related to the type of Azure Services deployed via the node command, and it should not allow me to choose a publishing profile that doesn't match the Azure Services deployed. 
Better even would be if the publishing profile could run the node provisionComposer.js automatically from within Composer. That way the correct Azure Services would be deployed based on the user's choice in the Composer UI.

![image](https://user-images.githubusercontent.com/23324404/83463023-1b9ebd80-a46d-11ea-964e-37a754cf1ac1.png)

**Comment by luhan2017** [comment]
@zxyanliu could you help on this?

**Comment by zxyanliu** [comment]
@luhan2017 Sure. I will take a look.

**Comment by zxyanliu** [comment]
The content is updated and will go live soon. Thanks again for your feedback.
