### ISSUE TITLE
enable set skill directly instead of only from manifest url

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#3269]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when I am debugging bot-skill interaction. I need to set a manifest file which is only needed to provide information like appid, url that could be set directly.

## Describe the solution you'd like

The user could provide either manifestUrl or the required values:
![image](https://user-images.githubusercontent.com/2876650/83491978-2bf27f00-a4e5-11ea-84e3-357b6304acc9.png)

**Comment by hibrenda** [comment]
@mareekuh @sangwoohaan  do we have more options for skill page.
