### ISSUE TITLE
Local PDF File - Bot Framework Composer

### ISSUE THREAD

**Issue by UmaPrelude** [microsoft/BotFramework-Composer#3271]
Hi,
I want to know how to refer a local pdf file in composer.
For ex: i have a pdf which needs to be opened while clicking on a hero card button.
how to create folder in composer and refer the pdf.
like http://localhost:3979/Files/MyPDF.pdf.

Thanks in advance.

**Comment by luhan2017** [comment]
Can you eject your runtime? put it under the wwwroot folder of runtime and check whether it works? 

![image](https://user-images.githubusercontent.com/32191031/83496727-159bf180-a4ec-11ea-8e3e-7d56d60ab20d.png)

**Comment by UmaPrelude** [comment]
Hi @luhan2017 , 
Thanks a lot. That worked.
