### ISSUE TITLE
Composer keeps changing my code.

### ISSUE THREAD

**Issue by AndyHue** [microsoft/BotFramework-Composer#3277]
I create a ask a question action and when I type the text it keeps changing to this 
- ${TextInput_Prompt_08NWN4()} and en error occurs, a window shows up saying something went wrong and re-try to change it and goes back to - ${TextInput_Prompt_08NWN4()}

## Version

V 1.0 
Electron 8.0.2
Chrome 80.0.3987.86
NodeJS 12.13.0
V8 : 8.0.426.16-electron.0

## Browser

- [X ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Authoring canvas '
2. Click on 'Select the Bot Asks (Text) action.'
3. Change the Prompt for text.

## Expected behavior

It should let me add my own text without changing it automatically to 
- ${TextInput_Prompt_08NWN4()}

## Screenshots
![image](https://user-images.githubusercontent.com/66331142/83560498-f85f2700-a4db-11ea-9272-5782456da0bb.png)
![image](https://user-images.githubusercontent.com/66331142/83560539-090f9d00-a4dc-11ea-942b-1e333cf805cb.png)

**Comment by cwhitten** [comment]
hi @AndyHue - this is a known issue and being actively worked in. We will submit a patch that addresses this.

**Comment by AndyHue** [comment]
Fantastic @cwhitten really appreciate it mate, have a good one!!

**Comment by cwhitten** [comment]
This is fixed in version 1.0.1

**Comment by bartbilliet** [comment]
@AndyHue here you go: https://github.com/microsoft/BotFramework-Composer/releases
