### ISSUE TITLE
support for manifest for skill

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#3283]
## Is your feature request related to a problem? Please describe.

When the composer bot runs as a skill, we need a manifest.

Do we have a plan for adding a page to edit this?
Or we could just start by adding one in the runtime\dotnet\azurewebapp\wwwroot folder.
Thanks!

By the way, we used to have a 'searching similar issue' ability when submitting a new issue, now it is gone..

**Comment by hibrenda** [comment]
we have skill manifest editor and not fully implemented in current version. We do have plan to add more later. Thanks for the feedback.

**Comment by xieofxie** [comment]
I see.. it is here:
![image](https://user-images.githubusercontent.com/2876650/83707493-b1dd0a00-a64c-11ea-8264-215591b4b419.png)
