### ISSUE TITLE
provide warning if id & host endpoint not set when using skills

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#3284]
## Is your feature request related to a problem? Please describe.

 I'm always frustrated when I forget to set them and it takes time to figure out why my skills don't work.

## Describe the solution you'd like

Provide warning if id & host endpoint not set when using skills:
![image](https://user-images.githubusercontent.com/2876650/83605106-ecda3180-a5a9-11ea-81ed-f2e311676b68.png)

**Comment by hibrenda** [comment]
Good suggestion!
