### ISSUE TITLE
Question: Conversation logging

### ISSUE THREAD

**Issue by knightmeister** [microsoft/BotFramework-Composer#3286]
Is there any documentation for logging conversations with Composer?

We are porting a bot written in C# and logging is a hard requirement for us for auditing and repudiation reasons.

I see #2339 has raised this, the response appears to address storing bot state in Cosmos DB and not logging. I have set this up locally and all I see in my local Cosmos instance is bot state - no logs.

Thanks.

**Comment by zidaneymar** [comment]
@knightmeister Hi, currently composer runtime is using telemetry client to Log information, you can use 'telemetry' config section to control the behavior of telemetry. (In Composer settings)
```
      telemetry: {
        logPersonalInformation: false,
        logActivities: true,
      },
```

And If you want to know the concrete activities, you should config 
```
        public BlobStorageConfiguration BlobStorage { get; set; }
```
in your Composer settings, which has the properties named 'ConnectionString' and 'Container' to enable TranscriptLoggerMiddleware, which is a middleware for logging incoming and outgoing activities.

**Comment by hibrenda** [comment]
need to add blob storage configuration in setting.

**Comment by knightmeister** [comment]
I appreciate the response - is this documented somewhere? What settings do I need to configure in Composer to use this?

**Comment by luhan2017** [comment]
Here is an example of the settings:

blobStorage is used to enable TranscriptLoggerMiddleware.
cosmosDb is used to store user and conversation data.
applicationInsights is used to enable the telemetry logger.

I guess you may need to enable the TranscriptLoggerMiddleware or Telemetry logger, Please let me know if you have further question. 

{
    "applicationInsights": {
      "InstrumentationKey": "*******************************"
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "****",
      "authKey": "****",
      "databaseId": "botstate-db",
      "collectionId": "botstate-collection",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "DefaultEndpointsProtocol=https;AccountName=****;AccountKey=********;EndpointSuffix=core.windows.net",
      "container": "transcripts"
    },

**Comment by knightmeister** [comment]
@luhan2017 That's awesome, thanks for your help

**Comment by madbeher** [comment]
thanks @hibrenda @cwhitten its helpfull.....

**Comment by gary-x0pa** [comment]
Hello may I know how to do this in botframework composer 2.0.0? I tried adding the blob storage to my settings.json do i need to modify my `startup.cs` file as well?
