### ISSUE TITLE
Missing way to extract only the keys from a JSON object

### ISSUE THREAD

**Issue by ms-yuhara** [microsoft/BotFramework-Composer#3287]
## Is your feature request related to a problem? Please describe.
I use [Send an HTTP request] feature to call an external REST API, which returns a JSON object that looks like this:

```
{
  "sheepdog": [
    "english",
    "shetland"
  ],
  "shiba": [],
  "spaniel": [
    "blenheim",
    "brittany",
    "cocker",
    "irish",
    "japanese",
    "sussex",
    "welsh"
  ]
}
```

I would like to get an array containing only the keys from this JSON result and let the user select it, but I can't find such a function in the adaptive expressions and can't achieve it.
In the above example, I want to enumerate only **seepdog, shiba, and spaniel**.

Actually, you can try it with the following open source API.

https://dog.ceo/api/breeds/list/all

## Describe the solution you'd like
It seems to be possible to handle this by creating a custom action, but I'd like to achieve it without writing code.

**Comment by Danieladu** [comment]
`foreach(items, item, item.key)` supposed to work

**Comment by ms-yuhara** [comment]
Thanks. Specifically, how can I describe that in Composer's [Set a property]?

![image](https://user-images.githubusercontent.com/38028987/83618988-333d8980-a5c6-11ea-8493-9d12f0252f0e.png)

**Comment by ms-yuhara** [comment]
Wow, I have achieved my objective with the following. Thanks a lot!

```
=foreach(dialog.dog_list_response.content.message, x, x.key)
```

The documentation is [here](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#foreach).

**Comment by shihanlk** [comment]
@ms-yuhara Can you put a full screenshot of the dialog ? I'm having a simile issue.

**Comment by ms-yuhara** [comment]
@shihanlk It worked as expected below. The left is a screenshot of the dialog, the right is an actual result in the emulator. Hope it helps.

![composer_3287](https://user-images.githubusercontent.com/38028987/87919062-3b885000-cab2-11ea-8494-915d3369806a.png)

**Comment by shihanlk** [comment]
Thanks @ms-yuhara. Can you post 2 more screenshots of set property value and User input ?

**Comment by ms-yuhara** [comment]
@shihanlk Here you are. The full value of [Set a property] box is below as I mentioned.

```
= foreach(dialog.dog_list_response.content.message, x, x.key)
```

![composer_3287_2](https://user-images.githubusercontent.com/38028987/87941789-9d5ab100-cad6-11ea-93f7-254059dd7ab0.png)

**Comment by shihanlk** [comment]
Thanks a lot @ms-yuhara in my cause it's not working because my json format is like below 

{}Content
	[]Data
		{}0
			{}attributes
					Title
{}1
			{}attributes
					Title
{}2
			{}attributes
					title

And I want to take only the values of each "title".

Do you think it's possible in Bot framework composer ? @Danieladu

**Comment by Danieladu** [comment]
hi @shihanlk  does the json sample looks like this? 
```
{
    "Content": {
        "Data": [
            {
                "attributes": "a1",
                "title": "t1"
            },
            {
                "attributes": "a2",
                "title": "t2"
            },
            {
                "attributes": "a3",
                "title": "t3"
            }
        ]
    }
}
```
What you really want is to get such a result: `['t1', 't2', 't3']`?
If so, the below solution may work as expected:
`foreach(YOUR_PRE_MEMORY_PATH.Content.Data, x, x.title)`

**Comment by shihanlk** [comment]
@Danieladu The jason sample looks like 
"response": {
      "content": {
        "data": [
          {
            "attributes": {
                "title": "Angular Star with Node.js"
            },
			{
            "attributes": {
                "title": "(TL-STL level)"
            },
			"attributes": {
                "title": ".Net Captain"
            },
			"attributes": {
                "title": ".Net Experience (SE and above Level)"
            }
         ]
    }
}

Yes the results should be Angular Star with Node.js, (TL-STL level), .Net Captain, .Net Experience (SE and above Level)

This =foreach(dialog.api_response.content.data, x, x.title) gives me 

[

null,

null,

null,

null

]

**Comment by Danieladu** [comment]
Maybe `=foreach(dialog.api_response.content.data, x, x.title)` -> `=foreach(dialog.api_response.content.data, x, x.attributes.title)` ?

**Comment by shihanlk** [comment]
the result of that is 

![image](https://user-images.githubusercontent.com/63157529/88008827-be4ef080-cb2e-11ea-9cb3-5477426751f5.png)

**Comment by Danieladu** [comment]
> the result of that is 
> 
> ![image](https://user-images.githubusercontent.com/63157529/88008827-be4ef080-cb2e-11ea-9cb3-5477426751f5.png)
> 

Maybe the equal mark is missing?

**Comment by shihanlk** [comment]
> > the result of that is
> > ![image](https://user-images.githubusercontent.com/63157529/88008827-be4ef080-cb2e-11ea-9cb3-5477426751f5.png)
> 
> Maybe the equal mark is missing?

Yes you are correct. now it comes like this. Thanks for the support. only thing now is to remove the []

![image](https://user-images.githubusercontent.com/63157529/88009977-741b3e80-cb31-11ea-98a6-2961e678dc3f.png)

**Comment by Danieladu** [comment]
> Yes you are correct. now it comes like this. Thanks for the support. only thing now is to remove the []
> 
> ![image](https://user-images.githubusercontent.com/63157529/88009977-741b3e80-cb31-11ea-98a6-2961e678dc3f.png)

Cool!
