### ISSUE TITLE
Question: Use existing LUIS instance

### ISSUE THREAD

**Issue by knightmeister** [microsoft/BotFramework-Composer#3288]
Is it possible to use an existing LUIS instance, or at the very least change the generated LUIS name? The format [project](Composer)-[project].en-us.lu is verbose.

**Comment by luhan2017** [comment]
@knightmeister Thanks for your feedback. 

You can customize your bot name here
![image](https://user-images.githubusercontent.com/32191031/83612706-590e6280-a5b5-11ea-91c1-d7d07dfb559c.png)
Then luis service name will be YourBotName(environment)-DialogName.en-us.lu

**Comment by hibrenda** [comment]
@knightmeister is this meet your requirement ?

**Comment by knightmeister** [comment]
@hibrenda Not really - I would like to be able to use the name exactly without the suffix. Should I raise a feature request?

**Comment by luhan2017** [comment]
@knightmeister, Thanks for your feedback, but I don't think we can do this, because there is not only one luis service in one bot in Composer, you could add multiple lu files in multiple dialogs, so we must put the DialogName at the end to differentiate them.

**Comment by knightmeister** [comment]
Thanks for the responses guys - makes sense.

**Comment by rahulr9801** [comment]
@cwhitten Thanks for explaining. In my organization, things are different - Platform team takes care of creating the components (LUIS, QnA, Azure bot Service) and development team simply uses it. I am just curious to know how we can use Composer in such a scenario.

**Comment by NeilDechert** [comment]
I would also like to be able to use an existing LUIS application here, since for more complex LUIS apps the editor on the website is much better than what the Bot Framework Composer provides.  In addition, editing or adding any intents on the website seems to break the LUIS / composer integration, at least in the limited testing I have done.

**Comment by drdamour** [comment]
i'm getting lost on how i have diff environments for the same bot application, i have different subscriptions in azure, thus different resource groups and different LUIS pairs (authoring + predict) all created by terraform by another team.  lets call em test & prod.  I expected to use composer locally with my existing luis test app, then when done publish the luis stuff out to my prod luis app (that has already been created by my luis team).

are there:
(1) good docs on how we're supposed to promote stuff through say 3 environments?
(2) docs explaining how the multiple luis apps thing works in composer?

**Comment by mohd-ismail-siddiqui** [comment]
I am creating a Bot using Composer using an existing LUIS app with out composer generated LUIS. Please let me know how its possible. If its possible please tell me workaround.
