### ISSUE TITLE
Should Add Possible Values Hints for Enum Type

### ISSUE THREAD

**Issue by zidaneymar** [microsoft/BotFramework-Composer#3290]
I think Composer should provide more hints for what kind of the enum value could be set to a specific field.

For example, in Activity Received Trigger, If user want to set the 'activity type' field, maybe he would be confused because this is a enum type. All possible values are 
```							
"description": "Contains the activity type. Possible values include: 'message', 'contactRelationUpdate',\n'conversationUpdate', 'typing', 'endOfConversation', 'event', 'invoke', 'deleteUserData',\n'messageUpdate', 'messageDelete', 'installationUpdate', 'messageReaction', 'suggestion',\n'trace', 'handoff'",
```
But currently composer is just showing the description in sdk.schema.
![image](https://user-images.githubusercontent.com/9328933/83617707-0e441900-a5bc-11ea-940f-72cc83a34dca.png)

**Comment by hibrenda** [comment]
@sangwoohaan be aware of this.

**Comment by cwhitten** [comment]
We'll continue to add updated copy to schema definitions and track them through other work items
