### ISSUE TITLE
opening project is extremely slow now

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#3295]
## Describe the bug

When opening a big project like https://github.com/microsoft/botframework-skills/tree/preview-build2020/skills/declarative/todoskill, it is extremely slow now.

## Version

74299ee0138136d2b3c70c8d6333891302b5edb5

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. open composer of that version
2. open project
3. wait for a extremely long time

## Additional context

This 447e83919c1dfd21bfe837a168bd0bf72d124c0b is good

**Comment by lei9444** [comment]
![image](https://user-images.githubusercontent.com/39758135/83658555-f2a93480-a5f4-11ea-9b0d-499488a5f69a.png)
I have found lg parser took a lot of time. @Danieladu has a PR to improve the lg parser performance now.

**Comment by Danieladu** [comment]
supposed to be fixed by https://github.com/microsoft/botbuilder-dotnet/pull/4021

**Comment by hibrenda** [comment]
should be fixed and addressed by #3337
