### ISSUE TITLE
output logs from runtime to console

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#3296]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when there is some runtime server error and I don't know the cause

## Describe the solution you'd like

Output error logs from runtime to console as what we have done for building the runtime

**Comment by a-b-r-o-w-n** [comment]
@xieofxie We use the `debug` package for this. When running Composer as a web app, set `DEBUG=composer*` environment variable before starting the app. You will start to see much more output in the console.

Let me know if that is sufficient for you.

**Comment by xieofxie** [comment]
I use powershell in windows and `$env:DEBUG = 'composer*'` works!
