### ISSUE TITLE
LG files keep getting deleted

### ISSUE THREAD

**Issue by ThoSt81** [microsoft/BotFramework-Composer#3298]
Randomly (it appears that way) some of my LG files get removed. The last time this affected the <botname>.en-us.lg file under <projectpath>\<botname>\language-generation\
This happened a few times already and I have no explanation why. I'm not sure if it's always the same file but I will keep an eye on it.

Since my project folder is stored in OneDrive, I am able to recover the file from the recycle bin.

## Version

V1.0.0

## Browser

- [X] Chrome
- [ ] Safari
- [X] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. User Bot Framework Composer normally
2. Wait for error message
3. Check the directory mentioned above for the LG file and find the file removed

## Expected behavior

Files should not be deleted automatically.

**Comment by hibrenda** [comment]
Hi @ThoSt81  , the patch release 1.0.1 is available today. you can update and this issue should be resolved.

**Comment by ThoSt81** [comment]
Thanks! I will test this and let you know if I see the same issue again!
