### ISSUE TITLE
Luis Bot -> Error: Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3299]
When a new bot is created with Luis enabled, in the Emulator it throws an error:
Response status code does not indicate success: 403 (Forbidden).

## Version

ffde16f0

## To Reproduce

1.Create new echo based bot
2. Switch to Luis and add trigger with intent and some utterances
3. Run provision script
4. Copy settings from script in Bot settings in Composer
5. Start Bot & Run emulator
6.  Type something to see the error
![image](https://user-images.githubusercontent.com/49873947/83646184-9c67d180-a5b3-11ea-8baa-4b381201378b.png)

**Comment by luhan2017** [comment]
@cxbuilders , so you started a local runtime by a deployed config. could you check the generated folder of your bot?

We are using this pattern to load the luis config file:
luis.settings.{luis.environment}.{luis.authoringRegion}.json

could you check the generated folder of your bot and your settings to see whether they match.

**Comment by cxbuilders** [comment]
@luhan2017 This is a vanilla bot in the latest version. I created the bot, enabled luis, ran the provisioncomposer.js script, filled in the settings in the appsettings and that's it. 

File looks ok:
![image](https://user-images.githubusercontent.com/49873947/83717439-02e00480-a633-11ea-89e9-32936d75b58c.png)
![image](https://user-images.githubusercontent.com/49873947/83717554-463a7300-a633-11ea-897b-e988c58bc035.png)

**Comment by luhan2017** [comment]
@cxbuilders , Oh, I know why this happen, in the deployment process, we are assigning the authored luis resource to the prediction luis service, which binds the endpointKey. So you should missed this part. You can try the following:

1. Use the authoringKey as the endpointKey.
2. kick of a deployment to bind the endpointKey with the luis resource.

**Comment by cxbuilders** [comment]
@luhan2017 Not completely clear. Are you saying I missed something or this is a bug?

**Comment by luhan2017** [comment]
@cxbuilders I mean you missed the deployment step, you can't just do provision and use the settings to start a local bot, you missed a luis endpoint assignment process which is in the deployment process.

**Comment by cxbuilders** [comment]
@luhan2017 Yeah but the provisionComposer.js script is the deployment script, right? Which I did run as mentioned

**Comment by luhan2017** [comment]
No, you should do deployment like this:

1. Click Add new profile, paste your provision result in the publish Configuration
    
![image](https://user-images.githubusercontent.com/32191031/83856965-e932e000-a74c-11ea-80b4-78e1b6a9c072.png)

2. Click publish to selected profile, select OK, then you are kicking off a deployment.

**Comment by mudasar** [comment]
I am having a similar error. It was working fine a couple of days ago but now when trying to run the bot on local with Luis integration it is returning this strange error without any further help that which kind of authentication is failed.

**Comment by luhan2017** [comment]
@mudasar , could you help paste your error message here?

**Comment by luhan2017** [comment]
@cxbuilders sure, there is a logic in composer, if user don't add luis:endpointKey, we will take luis:authoringKey as the luis: endpointKey. 
We've found a bug yesterday and I think it maybe related to the error you met. Which is:

Previously in composer, we auto generated the luis authoring and prediction endpoint by this pattern: https://${luis.region}.api.cognitive.microsoft.com which works fine for a while.

But recently, there is a change in the luis side which update the naming pattern as this:
https://{your-resource-name}.api.cognitive.microsoft.com
see https://docs.microsoft.com/en-us/azure/cognitive-services/luis/developer-reference-resource as a reference.

Could you check in you luis portal to check the endpoint url of your prediction and authoring resource? If that is the new pattern (https://{your-resource-name}.api.cognitive.microsoft.com), that should be the problem and we have a PR to fix this. #3364 .

Sorry for the confusing, please let me know if it works or not.

**Comment by cxbuilders** [comment]
No I have the https://westus.api.cognitive.microsoft.com/ url.

Today I removed the resource group and created it all from scratch;

- Simple bot with Luis enabled and some intents
- Run provisionComposer.js
- Copy Output of script into new publishing profile
- Publish the Bot
- Start the bot

And again:
![image](https://user-images.githubusercontent.com/49873947/84361280-b5800c00-abcb-11ea-9144-4c8d75efd581.png)

This is still the issue that the wrong key is used for the (composer) Luis model.

I have the feeling that we're running in circles here, if no-one just gives this a try to see if it replicates.

**Comment by mudasar** [comment]
> @mudasar , could you help paste your error message here?

I have got it fixed. I think the issue is with Composer when you change something in the settings (config) you have to some times restart the Composer and then restart the bot. The config changes are not reflected.
You are on the settings screen and update the config (update the Luis key in my case) you may restart the bot as many times but the key is not going to take effect. unless you navigate to a different screen in the Composer and then close/reopen the Composer.

**Comment by luhan2017** [comment]
> No I have the https://westus.api.cognitive.microsoft.com/ url.
> 
> Today I removed the resource group and created it all from scratch;
> 
> * Simple bot with Luis enabled and some intents
> * Run provisionComposer.js
> * Copy Output of script into new publishing profile
> * Publish the Bot
> * Start the bot
> 
> And again:
> ![image](https://user-images.githubusercontent.com/49873947/84361280-b5800c00-abcb-11ea-9144-4c8d75efd581.png)
> 
> This is still the issue that the wrong key is used for the (composer) Luis model as I mentioned in the previous message. This is only happening locally, in Azure the bot runs fine.
> 
> I have the feeling that we're running in circles here, if no-one just gives this a try to see if it replicates.

@cxbuilders, I have tried your steps can't repro this error in my side. Could you share more information here? for your reproduce steps, did you update the local configuration after publishing the bot?  what is your exact config of the local setting? 

For local setting, It currently has the authoringKey and endpointKey properties, if endpointKey is not used, we will use the authoring service for both authoring and prediction. 

I saw a screenshot at the beginning of this thread, you are using both authoringKey and endpointKey. 

If you have assigned an endpointKey(which comes from the luis prediction service) in the local setting to start a local bot, you should manually add the prediction resource to your luis app as the following. Could you double check on whether the endpointKey is associated with the luis app?  

https://docs.microsoft.com/en-us/azure/cognitive-services/luis/get-started-portal-deploy-app#assign-the-resource-key-to-the-luis-app-in-the-luis-portal

**Comment by cxbuilders** [comment]
@luhan2017 I am not sure anymore how we can get this issue any further. If you are up for it I can show you this is a call and explain what is going wrong. Otherwise I will just keep the endpointKey and authoringKey switched around in the local settings as a dirty workaround and wait for some other issue to get this fixed. 
Let me know.

**Comment by cxbuilders** [comment]
@luhan2017 Whatever combination of steps I try, it always fails. Would it be possible to have a call about this, as that would be a whole lot simpler to show my side.

**Comment by luhan2017** [comment]
@cxbuilders , sorry for the late response, sure, let's have a call on this. I am not sure how can we do this, what is your timezone? I am in Beijing. Please ping me when you are available.

**Comment by cxbuilders** [comment]
@luhan2017 I have sent you a mail (what I think is your mail) let me know if you received it.

**Comment by luhan2017** [comment]
@cxbuilders , I didn't receive your email, did you send it to luhan@microsoft.com?

**Comment by granicz** [comment]
So what was the solution at the end or was this a misconfiguration issue?

**Comment by praveenvavilla** [comment]
I am facing the same issue and shared details with @alanlong9278

**Comment by ma9az** [comment]
The solution shared by @DnlCYan worked for me as well
