### ISSUE TITLE
Create Publish Profile -> Error: undefined is not a valid publishing target type. There may be a missing plugin.

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3300]
When creating a new publish profile it always throws this error
![image](https://user-images.githubusercontent.com/49873947/83646380-d9cc5f00-a5b3-11ea-85e4-72461d9d2ae6.png)

## Version
ffde16f0

**Comment by luhan2017** [comment]
I also met this issue, just click OK, you can still use the profile you added. @cxbuilders 

@VanyLaw , could you help take a look on this?

**Comment by VanyLaw** [comment]
@luhan2017  Sure, I will take a look and fix it.
