### ISSUE TITLE
Publishing -> Error: Only absolute URLs are supported

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3301]
## Describe the bug

When creating a new Publishing Profile and copying over the settings from the provisioncomposer script and then running it it always fails with the following error;
![image](https://user-images.githubusercontent.com/49873947/83646547-1009de80-a5b4-11ea-8e13-c46787e0fab8.png)
![image](https://user-images.githubusercontent.com/49873947/83646624-316aca80-a5b4-11ea-8da8-e2f004be3a03.png)

## Version
ffde16f0

**Comment by hibrenda** [comment]
This should be fixed in latest master . https://github.com/microsoft/BotFramework-Composer/pull/3285

**Comment by luhan2017** [comment]
@cxbuilders, Could you go to this folder: BotFramework-Composer\Composer\plugins\azurePublish, delete the yarn.lock, and run yarn build again? 

#3285 will only take effect after you do the above. we have another issue to track this #3311 .
Sorry for the inconvenience.

**Comment by cxbuilders** [comment]
@luhan2017 Thanks for the update. I will wait for #3311 to be merged with master.

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/3322

**Comment by luhan2017** [comment]
@cxbuilders #3322 is merged, could you please try again on this?

**Comment by VanyLaw** [comment]
stale

**Comment by damarqmsft** [comment]
I'm also having this issue. I've tried pulling latest commit ( fd5d15a36d7e8407f47b301b05d3af548d9da776 ) and rebuilding

I see this message:
PUT /api/projects/70662.33507170361/files/appsettings.json 200 54.801 ms - 34
{
  status: 'DEPLOY_INFO',
  message: 'C:\\repos\\External\\BotFramework-Composer\\Composer\\plugins\\azurePublish\\lib\\publishBots\\2c8d239a607f2128c8455c973deecae9\\azurewebapp\\bin\\Release\\netcoreapp3.1\\ComposerDialogs\\language-understanding\\en-us\\timerskill.en-us.lu loaded\n'
}
{
  status: 'DEPLOY_ERROR',
  message: '{"stack":"TypeError: Only absolute URLs are supported\\n    at getNodeRequestOptions (C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\node_modules\\\\node-fetch\\\\lib\\\\index.js:1299:9)\\n    at C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\node_modules\\\\node-fetch\\\\lib\\\\index.js:1404:19\\n    at new Promise (<anonymous>)\\n    at fetch (C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\node_modules\\\\node-fetch\\\\lib\\\\index.js:1401:9)\\n    at NodeFetchHttpClient.<anonymous> (C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\plugins\\\\azurePublish\\\\node_modules\\\\@azure\\\\ms-rest-js\\\\dist\\\\msRest.node.js:3269:39)\\n    at step (C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\plugins\\\\azurePublish\\\\node_modules\\\\tslib\\\\tslib.js:141:27)\\n    at Object.next (C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\plugins\\\\azurePublish\\\\node_modules\\\\tslib\\\\tslib.js:122:57)\\n    at C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\plugins\\\\azurePublish\\\\node_modules\\\\tslib\\\\tslib.js:115:75\\n    at new Promise (<anonymous>)\\n    at Object.__awaiter (C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\plugins\\\\azurePublish\\\\node_modules\\\\tslib\\\\tslib.js:111:16)\\n    at NodeFetchHttpClient.fetch (C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\plugins\\\\azurePublish\\\\node_modules\\\\@azure\\\\ms-rest-js\\\\dist\\\\msRest.node.js:3267:22)\\n    at NodeFetchHttpClient.<anonymous> (C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\plugins\\\\azurePublish\\\\node_modules\\\\@azure\\\\ms-rest-js\\\\dist\\\\msRest.node.js:2544:51)\\n    at step (C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\plugins\\\\azurePublish\\\\node_modules\\\\tslib\\\\tslib.js:141:27)\\n    at Object.next (C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\plugins\\\\azurePublish\\\\node_modules\\\\tslib\\\\tslib.js:122:57)\\n    at fulfilled (C:\\\\repos\\\\External\\\\BotFramework-Composer\\\\Composer\\\\plugins\\\\azurePublish\\\\node_modules\\\\tslib\\\\tslib.js:112:62)","message":"Only absolute URLs are supported"}'
}
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\repos\External\BotFramework-Composer\Composer\node_modules\node-fetch\lib\index.js:1299:9)
    at C:\repos\External\BotFramework-Composer\Composer\node_modules\node-fetch\lib\index.js:1404:19
    at new Promise (<anonymous>)
    at fetch (C:\repos\External\BotFramework-Composer\Composer\node_modules\node-fetch\lib\index.js:1401:9)
    at NodeFetchHttpClient.<anonymous> (C:\repos\External\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\@azure\ms-rest-js\dist\msRest.node.js:3269:39)
    at step (C:\repos\External\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\repos\External\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\tslib\tslib.js:122:57)
    at C:\repos\External\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\repos\External\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\tslib\tslib.js:111:16)
    at NodeFetchHttpClient.fetch (C:\repos\External\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\@azure\ms-rest-js\dist\msRest.node.js:3267:22)
    at NodeFetchHttpClient.<anonymous> (C:\repos\External\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\@azure\ms-rest-js\dist\msRest.node.js:2544:51)
    at step (C:\repos\External\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\repos\External\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\tslib\tslib.js:122:57)
    at fulfilled (C:\repos\External\BotFramework-Composer\Composer\plugins\azurePublish\node_modules\tslib\tslib.js:112:62)
GET /api/publish/70662.33507170361/status/science-timer2 500 62.106 ms - -

**Comment by VanyLaw** [comment]
Hi @damarqmsft, Could you check your publish profile endpoint and authoringEndpoint field? and remove the place holder if existed to get around this. like:  
![image](https://user-images.githubusercontent.com/21174180/85937042-68719900-b932-11ea-8804-75ebb30ccfbd.png)

I will change the schema to fix this.

**Comment by damarqmsft** [comment]
> Hi @damarqmsft, Could you check your publish profile endpoint and authoringEndpoint field? and remove the place holder if existed to get around this. like:
> ![image](https://user-images.githubusercontent.com/21174180/85937042-68719900-b932-11ea-8804-75ebb30ccfbd.png)
> 
> I will change the schema to fix this.

Thanks! That seemed to fix the original issue.

It still doesn't publish though. It's stuck in this part:
![image](https://user-images.githubusercontent.com/66396148/86064937-2ffdb800-ba23-11ea-92d6-22d48d238f47.png)

_}
{ status: 'DEPLOY_INFO', message: 'lubuild succeed' }
GET /api/publish/70662.33507170361/status/science-timer 202 71.829 ms - 170
GET /api/publish/70662.33507170361/status/science-timer 202 58.224 ms - 170
GET /api/publish/70662.33507170361/status/science-timer 202 56.355 ms - 170
{
  status: 'DEPLOY_INFO',
  message: 'Assigning to luis app id: 22627641-9889-4873-b167-19e3876bfa21'
}
{
  status: 'DEPLOY_INFO',
  message: { code: 'Success', message: 'Operation Successful' }
}
{ status: 'DEPLOY_INFO', message: 'Luis Publish Success! ...' }
{ status: 'DEPLOY_INFO', message: 'Packing up the bot service ...' }
GET /api/publish/70662.33507170361/status/science-timer 202 78.490 ms - 170
GET /api/publish/70662.33507170361/status/science-timer 202 78.068 ms - 170_


I can only publish using Composer standalone app.

**Comment by VanyLaw** [comment]
Hi @damarqmsft, It's the zipping issue when we zip the runtime before upload. we will fix it in #3536
