### ISSUE TITLE
Unable to add promts

### ISSUE THREAD

**Issue by Msutapalli** [microsoft/BotFramework-Composer#3304]
Sometimes I can able to add prompts perfectlu, but while I'm in middle of developing it I'm getting issues with the promts.

**Comment by hibrenda** [comment]
Could you provide more info ? eg. what error might pop up or something else ?

**Comment by Msutapalli** [comment]
Hello Brenda, 

I have the bot built initially and it worked fine. But I opened the bot after some time then I have seen errors in all the prompts as below, 

${ TextInput_Prompt_KWS8WO ()} 
${ TextInput_Prompt_jjl3ut ()} 

Could you please check that. 

Thank you. 

Manasa Sutapalli 
Lead Researcher - MS Cognitive 
Phone : (248)-412-0347 
Mobile : (850)-081-2097 
Email : [ mailto: | msutapalli@miraclesoft.com ] 
		Miracle Software Systems, Inc. 
45625 Grand River Avenue 
Novi MI(48374) USA 
[ https://www.miraclesoft.com/ | www.miraclesoft.com ] 
[ https://www.facebook.com/miracle45625/ ] 	[ https://www.linkedin.com/company/miracle-software-systems-inc ] 	[ https://www.youtube.com/c/Team_MSS ] 	[ https://www.instagram.com/team_mss/ ] 

[ https://www.miraclesoft.com/ ]

**Comment by hibrenda** [comment]
@Msutapalli  this is a known issue and we have fixed in patch release. you can upgrade to latest version and have a  try.

**Comment by Msutapalli** [comment]
Sure, I will seek your help if I have same issue. 

Thank you. 

Manasa Sutapalli 
Lead Researcher - MS Cognitive 
Phone : (248)-412-0347 
Mobile : (850)-081-2097 
Email : [ mailto: | msutapalli@miraclesoft.com ] 
		Miracle Software Systems, Inc. 
45625 Grand River Avenue 
Novi MI(48374) USA 
[ https://www.miraclesoft.com/ | www.miraclesoft.com ] 
[ https://www.facebook.com/miracle45625/ ] 	[ https://www.linkedin.com/company/miracle-software-systems-inc ] 	[ https://www.youtube.com/c/Team_MSS ] 	[ https://www.instagram.com/team_mss/ ] 

[ https://www.miraclesoft.com/ ]

**Comment by cwhitten** [comment]
This has been addressed. Please re-open if you continue to see the issue. Thanks!
