### ISSUE TITLE
Allow configuring app settings without opening a bot project

### ISSUE THREAD

**Issue by bartbilliet** [microsoft/BotFramework-Composer#3309]
## Is your feature request related to a problem? Please describe.

The **Settings** > **App Settings** menu, which contains general Composer settings (e.g. editor preferences, nightly build updates, ..) is only available when a bot project is loaded. If no project is loaded, the cog is grayed out. A minor enhancement would be to make this Settings menu also available when no bot project is currently loaded, as there is no dependency on the bot logic. 

![image](https://user-images.githubusercontent.com/23324404/83685107-642eb600-a5e8-11ea-8316-91ed388c7c68.png)

![image](https://user-images.githubusercontent.com/23324404/83674917-7a347a80-a5d8-11ea-8580-21d916e32593.png)

## Describe the solution you'd like

- Make the **Settings** cog icon available also when no bot is loaded, but only show the **App Settings**. 
- When a bot is loaded, also show the **Bot Settings** and **Runtime Config** tabs.

**Comment by cwhitten** [comment]
@bartbilliet this is known and tracked with the UX Design team. In an upcoming sprint we will be addressing this.

**Comment by mareekuh** [comment]
as part of this, could we move the settings gear icon to the bottom of the left menu pane, per Fluent guidelines? And maybe include 'about' in here also.

**Comment by cwhitten** [comment]
Proposal:

1. Move Info page into Settings page
2. Remove/replace Info icon/location with Settings cog (move to bottom left)
3. Settings cog is _always_ enabled and interactable
4. _Bot settings_ & _Runtime config_ in subnav of Settings page are disabled if no bot is currently loaded.

**Comment by bartbilliet** [comment]
Proposal works for me 👍

**Comment by hatpick** [comment]
@mareekuh in what order the list should appear under the settings:
Here are the items: Bot settings,  App settings, Runtime config and About. (this is the current order)
Given that the App settings and About are enabled all the time and app settings will be pre-selected when one navigates to settings by clicking gear icon.

**Comment by mareekuh** [comment]
Response to Chris' proposal:

1. Move Info page into Settings page - MI Agreed (info = 'About'? -> Add 'About' nav item in Settings for this info.
2. Remove/replace Info icon/location with Settings cog (move to bottom left) - MI Agreed.
3. Settings cog is always enabled and interactable - MI Agreed.
4. Bot settings & Runtime config in subnav of Settings page are disabled if no bot is currently loaded. - MI Can we make 'runtime' part of bot settings? 

in terms of the order
Bot Settings (includes
- general  (includes name icon etc)
- run time
App settings
About

**Comment by hatpick** [comment]
@mareekuh I did not understand the last part regarding the ordering, would you please elaborate?

**Comment by mareekuh** [comment]
1. Bot Settings 
- General
- Run time

2. App settings
3. About

https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=2812%3A357

**Comment by GeoffCoxMSFT** [comment]
@cwhitten - We need to figure out if we want to make the proposed small improvement or not do it as the larger figma specified improvements are pending.  Also, @hatpick  has a conflict between the react router paths that are settings based vs. bot specific to resolve that needs your guidance.

**Comment by mareekuh** [comment]
What are you referring to for the large vs small improvement.
As far as I understand, this is about.
1. Moving settings to the bottom left
2. Adding 'about' to the settings as a tab
3. Adding 'runtime' as a sub-section in Bot settings.

**Comment by cwhitten** [comment]
Soroush and I chatted and I believe we're aligned. He is going to update
some internal routing definitions and will report back if it doesn't get us
to where we need to be.
