### ISSUE TITLE
[MCS-DE-GO] KeyVault Integration for Bot Runtime

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#3315]
All keys and secrets have to be stored in a secure way leveraging Azure KeyVault as a customer requirement. Secret information is not allowed to be stored in unencrypted configuration files.

This is true for at lease all FSI customers in Europe and most other Industries.

KeyVault Integration should be enabled via "appsettings" as boolean plus configuration of the KeyVault URL for the KeyVault to be used.
Add KeyVault as an ICONFIGURATION source.
To enable multiple Bots with the same KeyVault default settingsnames should be prefixed by the botname.

@joaollq @sgellock @benbrown

**Comment by goergenj** [comment]
Adding info from project. We use the AppSettings on the Bot WebApps now and put these into the KeyVault. This is all Azure Services configuration so should be okay. You just need to make sure that the publishing scripts do now store secrets within the appsettings.files on the WebApps themselves. We ensure this by doing the deployment via Azure DevOps Pipelines.

I believe this topic can be solved without major changes mainly by providing proper documentation on how to to is. We can provide input, if needed.

**Comment by goergenj** [comment]
@benbrown @cwhitten Any update on potential timeline for this?

**Comment by goergenj** [comment]
@benbrown Any update on potential timeline for this?

**Comment by rahul-8437008949** [comment]
@goergenj can you tell how you implemented azure devops pipelines with bot composer

**Comment by goergenj** [comment]
@rahul-8437008949 What does your question relate to? The KeyVault-integration? We created special Publishing Plug-Ins in Composer which run git commands to push the changes to DevOps and start the Build/Release pipelines. Also triggering pull-requests with approval gates for publishing into productive environments.
The pipelines themselves take settings from the DevOps Libraries at the time of deployment to create the proper appsettings.

**Comment by rahul-8437008949** [comment]
@goergenj i also tried deploying code via ado pipelines.The bot gets deployed on azure but bot channel registration doesn't get linked. I thought this is a problem of composer but as you have implemented ado pipeline implementation can you help me out please. For key vault i was trying to use managed identity somehow.

**Comment by goergenj** [comment]
@rahul-8437008949 We are not deploying the Bots Azure Services. They are pre-setup via Terraform. We populate only the Bot code, LUIS, QnaMaker, etc.

If you want to add the Azure Services deployment to the pipeline, I recommend to use an ARM-template which is parameterized so you can run this. I would separate this from the code publishing however, to avoid re-deploying the Azure Services each time.

**Comment by rahul-8437008949** [comment]
@goergenj Can you please share a few details regarding how you integrated key vault with ado please.
Thanks.

**Comment by goergenj** [comment]
@rahul-8437008949 Please send me an e-mail to jan.goergen@microsoft.com. Not sure what you need.

**Comment by goergenj** [comment]
Any update on this?
