### ISSUE TITLE
[MCS-DE-GO] KeyVault Integration for Composer and Publishing Plug-In settings

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#3316]
All keys and secrets have to be stored in a secure way leveraging Azure KeyVault as a customer requirement. Secret information is not allowed to be stored in unencrypted configuration files.

This is true for at lease all FSI customers in Europe and most other Industries.

KeyVault Integration should be enabled via "appsettings" as boolean.

Composer-relevant settings that should be pulled from KeyVault use the KeyVault-Connection-String as a value, if KeyVault is enabled otherwise use value as is.

@joaollq @sgellock @benbrown

**Comment by cwhitten** [comment]
To implementer:

We did work internally last year to serialize sensitive settings information to a secure cloud product like KeyVault.

The work here would be to pick that back up and represent it as a plugin or part of the storage serialization mechanism to persist settings data to a secure cloud store instead of a local appsettings.json.

**Comment by goergenj** [comment]
@cwhitten Any update on potential timeline for this?

**Comment by goergenj** [comment]
@benbrown Any update on this? We currently solve this with our own publishing pipelines but would be good to have this support in the default plug-ins as well.

**Comment by goergenj** [comment]
@benbrown / @garypretty Any update regarding timeline for this?

**Comment by jeff-breece** [comment]
@goergenj, I am having the same problem here with an energy client of ours who wants to use Bot Composer but has a hard requirement of using Key Vault for secrets. Would you be willing to share a brief bit of info on how you solved this using publishing pipelines as you mentioned before? The process is not so clear to me as far as how Bot Composer creates and builds its artifacts. Thanks in advance.

**Comment by goergenj** [comment]
@jeff-breece  Please reach out to @joaollq. He can share our code I believe.

**Comment by jeff-breece** [comment]
Thanks, @goergenj . 

In other news, I got an hour with one of the Bot Composer engineers in Beijing for the deployment stuff and another SME who lives in the US. It seems that Key Vault integration is in fact on the road map for Bot Composer but, as of yet, it is not funded or scheduled. Still, the estimate I got was "possibly" sometime around MS Build.

@joaollq, here's my personal email address (below), I'd really like to see the solution you came up with to bridge the gap in the Bot Composer tool with regards to security and Key Vault (and hopefully ADO integration).

jeff@jeffbreece.com

Thanks, everyone.

**Comment by sgellock** [comment]
I want to be as transparent as I can here.  The team is really good about honoring delivery dates when we have work booked, planned, and resources allocated.  When that's not the case, meaning when work is on our backlog, and hasn't yet been officially booked for a release, any timeline communicated is simply aspirational dialog at this point.  

I don't want to say we're not aware of the KV feature ask and that it's not important, we understand it is.  However, I want to be transparent and try to not have anyone make assumptions around actual delivery, and therefore set expectations that may not currently align to the team's deliver commitments.

**Comment by jeff-breece** [comment]
@sgellock, haha! I amended my statement which had the **noncommittal** time frame I was given, in a non NDA conversation, in quotes. I really hope you all make this enterprise-ready by not only adding Key Vault integration but full CI/CD pipeline integration. Keep up the hard work!

**Comment by gerald560** [comment]
any update on this?
