### ISSUE TITLE
[MCS-DE-GO] Change query to LUIS & QnAMaker within the Bot Runtime to include optional parameters

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#3317]
1. When sending a query to LUIS we want to be able to control the logging behaviour via the optional LUIS API parameter "log" (boolean). This is relevant for GDPR compliance. We want to turn this on/off via an appsetting.
2. When sending a query to LUIS we want to be able to control which publishing slot in LUIS (Staging or Production) is being used. We want to configure which slot to use via appsettings.
See for 1 and 2: https://westus.dev.cognitive.microsoft.com/docs/services/luis-endpoint-api-v3-0/operations/5cb0a91e54c9db63d589f433

3. When sending a query to QNAMAKER we want to be able to send the optional "userID" information for logging. This is relevant for GDPR compliance. We want to turn this on/off via an appsetting.
See: https://docs.microsoft.com/en-us/rest/api/cognitiveservices/qnamakerruntime/runtime/generateanswer

@joaollq @sgellock @benbrown

**Comment by vishwacsena** [comment]
related to microsoft/botframework-cli#805

**Comment by vishwacsena** [comment]
@pchoudhari I do not see `UserID` exposed via the the `qnamakerrecognizer`. Can you comment?

**Comment by pchoudhari** [comment]
We currently do not support UserID in our API call, as it is not used in our service.

**Comment by vishwacsena** [comment]
Given we do not have any plans to address the QnA side of this ask, the rest will be tracked via microsoft/botbuilder-dotnet#4149

**Comment by sgellock** [comment]
@vishwacsena, not doing this may prevent QnA from being used in Germany.

**Comment by vishwacsena** [comment]
@pchoudhari can you comment? Should the [API documentation][1] needs update to drop `UserId`? What is the customer mitigation for GDPR compliance in absence of `UserId`? 

[1]:https://docs.microsoft.com/en-us/rest/api/cognitiveservices/qnamakerruntime/runtime/generateanswer#request-body

**Comment by pchoudhari** [comment]
In case of QnA Maker all the user data and logs are stored in the customer's Azure subscription. So, I don't think there is an issue of GDPR. @sgellock, are there any specific requirements for userId in Germany?

**Comment by sgellock** [comment]
@pchoudhari I've reached out to the customer.  will provide an update here when I hear back from them.

**Comment by goergenj** [comment]
Hi guys,

if you don't support sending this optional parameter via the API, why is it in the documentation?
https://docs.microsoft.com/en-us/rest/api/cognitiveservices/qnamakerruntime/runtime/generateanswer#request-body

Please update this on whether this is supported or not and clear up this confusion.

The UserID would be relevant for GDPR as this is the only way to look-up information or to delete information from the logs for a specific user. This is not specific to Germany.

It is not critical to add this support, if it is not there but you definitely need to clear up your documentation! We keep getting in trouble with customer conversations, especially regarding compliance, if these things are not properly communicated and the documentation is not reliable!

So, please let us know what is the latest state on this? Is this supported or not?

@joaollq @sgellock @pchoudhari

**Comment by goergenj** [comment]
@pchoudhari Any update on this? Will you do something about this feature or at least correct the documentation to avoid people being misled? Is this something that will be completey new with QnAMaker v2?

**Comment by pchoudhari** [comment]
Hi @goergenj , sorry I misspoke in my previous comment.

The userId in the GenerateAnswer API is used in the telemetry we store in the User's App Insights. See more details here: https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/get-analytics-knowledge-base

**Comment by goergenj** [comment]
@garypretty Any update regarding timeline for this?
