### ISSUE TITLE
[MCS-DE-GO] UI-Plug-Ins should allow adding buttons to the Composer UI for new features

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#3318]
UI-Plug-Ins should allow adding buttons to the Composer UI for new features.

Currently we need to have additions for:
- Logout of users logged in via AAD Authentication plug-in.
- Lock / Unlock of Bots (required as part of the multi-user setup of a hosted Composer)
- Hide the start bot button
- replace start bot button with our own action / test link

@joaollq @sgellock @benbrown

**Comment by cwhitten** [comment]
@a-b-r-o-w-n to consider these scenarios are part of UI plugin work

**Comment by goergenj** [comment]
@cwhitten Any update on potential timeline for this?

**Comment by a-b-r-o-w-n** [comment]
@goergenj we are investing in the extension platform for this release cycle (11/11). We can consider this during that work, but may want to defer to the next release as we develop the core capabilities. 

If you have thoughts or want to propose a design for this, that would be welcomed!

**Comment by goergenj** [comment]
@benbrown @cwhitten Any update on potential timeline for this?

**Comment by goergenj** [comment]
@cwhitten Any update on potential timeline for this?

**Comment by cwhitten** [comment]
@a-b-r-o-w-n can you update @goergenj on where we are at with this?
