### ISSUE TITLE
Error while creating a new publishing profile

### ISSUE THREAD

**Issue by hraz-msft** [microsoft/BotFramework-Composer#3320]
Add the publish profile throws that error:
![image](https://user-images.githubusercontent.com/66222191/83743606-9f21ff80-a663-11ea-9241-199a3f147afb.png)

## Version

![image](https://user-images.githubusercontent.com/66222191/83743686-bb25a100-a663-11ea-87c5-f2e1a5c44fcc.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Generate publish config with the `provisionComposer.js`
2. Create a new profile
3. Paste the configuration, choose `Publish bot to an Azure Web App (preview)` and give a name
4. Click `Save`

## Expected behavior

No error

## Screenshots

Above

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/3300

**Comment by hraz-msft** [comment]
I'm not sure if this is related. But all of my publishes are failed (no matter what profile it is):
![image](https://user-images.githubusercontent.com/66222191/83748798-66862400-a66b-11ea-95a9-c7cf55ff909e.png)

**Comment by hraz-msft** [comment]
I will open a separate bug
