### ISSUE TITLE
QnA Maker AND Dialog Interruptions

### ISSUE THREAD

**Issue by Todd442** [microsoft/BotFramework-Composer#3325]
I'm working on a project to the US Labor department and we have a dialog focused on job search with works fine. 

We added QnA to address questions on Unemployment and it works...

BUT if the user starts the Job Search dialog and is in the process of answering questions when we have "**Interruptions" set to true.** The bot fails to break out of the job search dialog, if the user changes their mind and states something like "How do I get unemployment"

Is there pattern here we're missing when QnA is integrated?

The interruptions WORK if this is just intent based.

**Comment by vishwacsena** [comment]
@Todd442 yes. this is known. we expect to have deeper integration with QnA including ability to have QnA as interruptions in an upcoming release. For now, only `intent` based interruptions are possible. A short term workaround for you would be to add a few `questions` to an `OnIntent` trigger and add a `QnA` action to it.

**Comment by cwhitten** [comment]
Closing this as a answered question. Support for what you are looking for should come into Composer in the coming months.

**Comment by narulasrinivas** [comment]
@cwhitten , @vishwacsena - Is there any timeline for this feature to release in BOT composer?

**Comment by cwhitten** [comment]
@narulasrinivas this has been released and requires that you author the QnA KB in Composer and publish it similarly to the way you author LUIS models. See https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb for more information.
