### ISSUE TITLE
Need visibility into the publishing logs and errors

### ISSUE THREAD

**Issue by cgarcia-msft** [microsoft/BotFramework-Composer#3328]
## Describe the bug

When publishing fails, there's very little information about the error available to the user, which makes problems very hard to debug. E.g.:
 
1. Create a bot with an ejected runtime and a custom action
2. In the custom action reference and external dll outside of the runtime folder (e.g. ..\..\mydll.dll)
3. Try publishing 

Result: Publish will fail but the only error will be that the dotnet build command failed. It fails because during the publish the runtime folder is copied to a temporary location, so the dll reference fails. However, this is not at all visible to the user so its really hard to diagnose.

I was able to find the error by running Composer from the source (yarn startall), which gave me visibility into the logs where I could clearly see the problem.

## Version

4.9

## Browser
Chrome

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

**Comment by luhan2017** [comment]
@cgarcia-msft can this meet your requirement? 

1. select a deployment item
2. click See Log

![image](https://user-images.githubusercontent.com/32191031/83836935-9e52a180-a727-11ea-9458-a3ef2926e886.png)

**Comment by cgarcia-msft** [comment]
Unfortunately, no. I did open the log when the deployment failed, but there were no details. The error I got was that the command “dotnet publish <long temp paths and options>” failed.

What I really needed to debug this was the output of that “dotnet publish” command. I was able to see this running Composer from source via “yarn startall”.

Thanks.
