### ISSUE TITLE
Cannot pick a folder that has a csproj for 'open', 'new' or 'saveas' locations

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#3330]
## Describe the bug

I have a bunch of folders on my machine and I'd like composer to save the bot to a sub-folder within a root folder that has a csproj file either at at folder level or within any arbitrary sub-folder under that folder. I cannot do this in composer. 

e.g. 
|--rootFolder
|----composerDialogs //intended location to save the composer bot
|----rootFolder.csproj

## Version

Release: 1.0.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch composer
2. Click on New, select from scratch
3. In the file location picker, try to select a folder that has a csproj file.

## Expected behavior

Random csproj files are not detected as a bot

## Screenshots

You can see that the samples folder here is detected as a bot. It is not. 

![image](https://user-images.githubusercontent.com/20918136/83816800-1a8dac00-a678-11ea-973d-f09bdc2fc587.png)

**Comment by hibrenda** [comment]
May need more investigation as I hit this issue as well. no .csproj in my Desktop directory but "Desktop" is recognized as a Bot.

**Comment by liweitian** [comment]
checked on @hibrenda PC. 
**private isBotFolder = async (storage: IFileStorage, path: string) => {
    // locate new structure bot:
    const children = await storage.readDir(path);
    const dialogFile = /.+(.)dialog/;
    const isNewBot = children.some((name) => dialogFile.test(name));
    // locate old structire bot: Main.dialog
    const mainPath = Path.join(path, 'Main', 'Main.dialog');
    const isOldBot = await storage.exists(mainPath);
    return isNewBot || isOldBot;
  };**
This is how we check whether a folder is a bot. It is looking for .dialog file in current folder or current folder/main/main.dialog. We probably need a better way to identify a bot.

**Comment by boydc2014** [comment]
> This is how we check whether a folder is a bot. It is looking for .dialog file in current folder or current folder/main/main.dialog. We probably need a better way to identify a bot.

This logic make sense to me, perhaps we can remove the old compatible behavior for main/main.dialog. But i don't understand why in Vishwac or Breanda's PC, a certain folder is identified as bot, because there seems to be no *.dialog at top level and also no main/main.dialog, right? am i missing something?

**Comment by boydc2014** [comment]
Also @vishwacsena , looks like you are navigting in the wrong folder, in the left view you are navigating at c:\repos\botbuilder-dotnet, in the right view, you are navigating at c:\repos\botbuilder-samples\samples.

I think if your c:\repos\botbuilder-dotnet\samples do have a *.dialog,  the logic is expected for now.  

Take off bug, and add enhancement for better checking, we don't have a better way to check bot yet.

**Comment by liweitian** [comment]
The pattern is not correct. Opened pr to fix it. But if a folder contains a .dialog file, it is still recognized as a bot.
