### ISSUE TITLE
LU editors auto-suggest, auto-complete not working in 1.0.1

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#3331]
## Describe the bug

Auto-suggest, auto-complete features in the inline LU editor does not work in 1.0.1 version.

## Version

1.0.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to any dialog
2. Set the recognizer to LUIS
3. Add an `OnIntent` trigger
4. Start typing in utterances as well as entity definitions.

## Expected behavior

Auto-suggest, auto-complete did not regress from 1.0.0

## Screenshots

[Media1.zip](https://github.com/microsoft/BotFramework-Composer/files/4733034/Media1.zip)

**Comment by zhixzhan** [comment]
It's my regression from #3270 , will fix soon.
