### ISSUE TITLE
improve skill manifest editing experience

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#3333]
## Is your feature request related to a problem? Please describe.

 I'm always frustrated when skill manifest editing experience needs improvements.

## Describe the solution you'd like

* This section should be included in the default template for being used as a skill (some automation of msAppId would be better)
```
"endpoints": [
      {
        "name": "production",
        "protocol": "BotFrameworkV3",
        "description": "Production endpoint",
        "endpointUrl": "https://YOUR_DEPLOYED.azurewebsites.net/api/messages",
        "msAppId": "YOUR_ID"
      }
    ]
```
* Provide a place for displaying and copying the full url for manifest like https://YOUR_DEPLOYED.azurewebsites.net/manifests/YOUR_BOT-0-2-1-preview-1-manifest.json. The url for manifest is not obvious now and Composer can't display the name fully:
![image](https://user-images.githubusercontent.com/2876650/83831453-04d0c300-a71a-11ea-83e6-e207964045ec.png)
* Provide a bigger place for manifest editing. Here are some almost real world manifest examples: https://github.com/microsoft/botframework-skills/blob/master/skills/csharp/todoskill/wwwroot/manifest/manifest-1.1.json, https://github.com/microsoft/botframework-skills/blob/master/skills/csharp/calendarskill/wwwroot/manifest/manifest-1.1.json
They are easy to be over several hundreds lines long.

**Comment by hibrenda** [comment]
similar requirements has already roll up .  @sangwoohaan @mareekuh for awareness. 

As a skill Bot for skill configuration 
-	P0: endpointURl change (not direct as it exists in manifest editor) but this need to be updated frequently for localhost testing ("endpointUrl" : http://localhost:3979/api/messages )
-	P0: manifest path could be easily referenced and copied to consumer bot
-	P1: manifest CRUD (support manifest delete, rename, can create multiple manifest on same version)

As a consumer Bot in Skill page setting
-  No manifest option for end user (in case the skill does not have manifest)
-  Easy to tell something is broken in skill page – eg. Endpoint is invalid
    (Bug: If manifest URL is broken due to the endpoint change, nothing showed in skill page and dropdown list in property editor will be empty as well)
- Skill Host Endpoint validation check if  "begin a skill" exist to invoke the skill

**Comment by mareekuh** [comment]
Can we please combine this effort with getting started on the asset library. This allows us to scale and remain in sync with PVA.
We can show status and properties in the right panel, which is consistent with our interaction model.

**Comment by xieofxie** [comment]
Syncing with PVA is great. For the examples I mentioned, most of the lines are actions and definitions for PVA actions. It will be great if we can leverage them like better definition editing experience, tips for definition when creating action etc.

**Comment by mareekuh** [comment]
I just reread this. You're asking for a larger area to edit the manifest.
Does it need to be larger than this? https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=1428%3A14724

As far as I understand these flows are still plan-of-record, but didnt make it in before Ignite

**Comment by xieofxie** [comment]
To be honest, since we are offering a plain text editing experience here. I often just open it in VSCode etc. to edit.
