### ISSUE TITLE
Docs: Schemas folder missing for adding custom actions

### ISSUE THREAD

**Issue by bartbilliet** [microsoft/BotFramework-Composer#3343]
## Describe the bug

The [documentation on Custom Actions](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#update-the-schema-file) says in step 5: 

> Navigate to to the Schemas (bot/**runtime/azurewebapp/Schemas**) folder and then run the command update.sh.
> 
> You will see that the partial schema (MultiplyDialog.schema inside customaction/Schemas) has been appended to the default sdk.schema file to generate one single consolidated sdk.schema file.
> 
> Copy the newly generated sdk.schema into the schemas (bot/schemas) folder at the root of the ejected runtime.

In version v1.0.1 of the Bot Framework Composer, after ejecting the runtime, the **Schemas** folder is missing in both:
- bot/runtime/**azurewebapp** 
- bot/runtime/**azurefunctions**

It appears the schema files & corresponding scripts have moved to: 
- bot/**schemas**

## Version

![image](https://user-images.githubusercontent.com/23324404/83943766-d547b680-a7fe-11ea-8edb-8dac5db26e77.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Eject the runtime as described [here](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#eject-bot-runtime). 
2. When trying to [update the Schema files](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#update-the-schema-file), you will find the mentioned **Schemas** folder is not present in both azurewebapp or azurefunctions.

## Expected behavior

The documentation should be updated to reflect the functioning of the new scripts path, and the sdk.schema does not need to be copied anymore:  

- Navigate to to the `schemas (bot/schemas)` folder. This folder contains a Powershell script and a bash script. Run either of these scripts `./update-schema.ps1 -runtime azurewebapp` or `sh ./update-schema.sh -runtime azurewebapp`. To use the Azure Functions runtime, run the script with `-runtime azurefunctions`. The runtime `azurewebapp` is chosen by default if no argument is passed.

- Validate that the partial schema (MultiplyDialog.schema inside customaction/Schema) has been appended to the default sdk.schema file to generate one single consolidated sdk.schema file.

The above steps should have generated a new sdk.schema file inside `schemas` folder for Composer to use. Reload the bot and you should be able to include your new custom action!

## Screenshots

Ejected runtime generated on v1.0.0: 

![image](https://user-images.githubusercontent.com/23324404/83943808-1d66d900-a7ff-11ea-97bf-accbd349ebe7.png)

Ejected runtime on v1.0.1:

![image](https://user-images.githubusercontent.com/23324404/83943761-c7923100-a7fe-11ea-8fc9-2cba4a295dfe.png)

![image](https://user-images.githubusercontent.com/23324404/83943750-b9dcab80-a7fe-11ea-8c1f-0c6b81dc042d.png)

## Additional context
- An additional remark on this related docs page: 
When testing in the **Bot Framework Emulator**, Composer will always use the **azurewebapp** runtime, even if afterward you deploy to Azure Functions. It means that during development you will need to make the changes to the *.csproj* and *startup.cs* files in **both** the **azurewebapp** and **azurefunctions** folders.

**Comment by zxyanliu** [comment]
@bartbilliet I just reproduced this issue. Thanks for reporting. 
@luhan2017 Please let me know if there anything I should update in the [doc](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#update-the-schema-file).

**Comment by luhan2017** [comment]
@bartbilliet it was moved to the botfolder/schemas folder. For now, you can just run updateSchema command under the schemas folder, you don't need to do an extra copy from runtime/schemas to schemas folder right now. 

@zxyanliu please help update the doc based on the above.

**Comment by zxyanliu** [comment]
Hi @bartbilliet, here is [a working PR](https://github.com/MicrosoftDocs/composer-docs-pr/pull/134) to address this issue. Please also be noted that you might need to restart your electron to see the **custom action** enabled in Composer UI when [testing it](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#test). I added a `Note box` in the [doc]() for this [known issue](https://github.com/microsoft/BotFramework-Composer/issues/3363).  The content will go live soon. 

Thanks!

**Comment by bartbilliet** [comment]
@zxyanliu I believe the *composer-docs-pr* repo might be private, as I'm unable to follow the PR link. Anyway, I'll see when the content goes live then. Thanks for the updates! :-)

**Comment by zxyanliu** [comment]
Hey @bartbilliet thanks again for reporting this issue. The content has been updated and will go live soon. 
Thanks for helping me with this @luhan2017 @srinaath.

**Comment by zxyanliu** [comment]
Hey @bartbilliet the [content](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action) has been updated and is live now. Thanks again for your feedback, we appreciate it! : -)
