### ISSUE TITLE
Qnamaker and Luis sample: answer with prompts breaks business logic 

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-Composer#3345]
The idea of this sample is to first try and understand the intent of a user (Luis) and if bot succesfull find an answer in a connected knowledgebase. 
As soon as the answer from qnamaker containts prompts, Luis seems not to be consulted for the next user input. 

How to reproduce:
Create a qna answerpair with prompts
Create a qna answerpair with 'help' in it.
Start Bot
type help -> the intent in Luis is used
type question with answer in QnAKB -> answer is shown with prompts
type help -> the QnAKB is consulted and answer in QnaQB is shown (with help in it)

**Comment by hibrenda** [comment]
@HesselWellema If I understand correctly, you want luis to be recognized but not the QnA answerpair even if the 'help' includes in the QnA answerpaire.  

We do plan to support this scenario in upcoming release in composer.

**Comment by HesselWellema** [comment]
Exactly. First Luis needs to be recognized. If that fails, QnaMaker needs to be recognized.

**Comment by vishwacsena** [comment]
@HesselWellema when you have multi-turn prompt in QnA maker, then subsequent user replies to multi-turn prompt are only handled by QnA maker. We are working on a more deeper integration with QnA maker and until that is available in composer there isn't a way to do consultation across LUIS and QnA maker. 

This capability however does exist in the SDK. You could consider switching your bot to be SDK based and use the [cross-trained recognizer][1]. See [this sample][2]. 

@pchoudhari @cwhitten 

[1]:https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-dialog-recognizers?view=azure-bot-service-4.0#cross-trained-recognizer-set
[2]:https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/adaptive-dialog/08.todo-bot-luis-qnamaker

**Comment by HesselWellema** [comment]
thanks @vishwacsena. This is exactly what I need. I use JS for bot development and know adaptive daialogs are in preview. Do you  expect this recognizer to become available (in preview) soon in JS?

**Comment by vishwacsena** [comment]
@HesselWellema sure, JS is available in 'preview'. See sample [here][1]

[1]:https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-dialog/javascript_nodejs/08.todo-bot-with-luis-qnamaker

**Comment by HesselWellema** [comment]
Ok, tnx for your support
