### ISSUE TITLE
Connect to QnAKnowledgebase: impossible  to change 'Threshold'

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotFramework-Composer#3346]
Steps to reproduce

Open QnAMaker & LUIS Sample
Open Unknown intent  trigger
Open Connect to QnA Knowledge base
Try and change threshold from 0.3 in another value. You will not succeed

**Comment by luhan2017** [comment]
@HesselWellema 
There are two ways to do this:
1. You can try to click the arrows in the right side when the type is number:
![image](https://user-images.githubusercontent.com/32191031/83989534-47dca180-a979-11ea-80bc-e8d640bb161e.png)

2. update it to expression and you can write the expression as following
![image](https://user-images.githubusercontent.com/32191031/83989579-6e024180-a979-11ea-802f-087e769b7180.png)

Please let me know if it still not works.

**Comment by HesselWellema** [comment]
Tnx. That helped! Don't know why I missed those arrows.
