### ISSUE TITLE
Composer gets stuck at the blank screen when opening up my existing Bot

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/BotFramework-Composer#3349]
## Describe the bug

Till yesterday, I was using one of my bots and even did a little showcase during my talk at the Microsoft Reactor. Today, when I tried to open it up, it gave me this

![image](https://user-images.githubusercontent.com/16351038/84016934-55b61500-a9c1-11ea-94ce-c50dcaa81b16.png)

Upon Looking at the Developer Tools, I got this.

![image](https://user-images.githubusercontent.com/16351038/84017177-a0d02800-a9c1-11ea-93e4-03d27c6ba38b.png)

## Version

1.0.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Just launch Composer and you will see this. 
2. Press Ctrl + Shift + I and got to know that there's some JSON issue which does not get loaded. 

## Expected behavior

It should open it up correctly.

**Comment by arafattehsin** [comment]
Just to add that I just downloaded the nightly build as well and I get the similar response. 

![image](https://user-images.githubusercontent.com/16351038/84019219-543a1c00-a9c4-11ea-8006-709c45cecbf2.png)

**Comment by cwhitten** [comment]
@arafattehsin are the able to send the bot assets to us?

**Comment by arafattehsin** [comment]
Thanks @cwhitten I managed to fix it by removing one of the line from my .dialog file. Happy to close this ticket right now and will keep an eye if anything happens again, I will take a screenshot of it. The line that was removed from the dialog was at the end, right below this:

![image](https://user-images.githubusercontent.com/16351038/84094395-124ebb80-aa40-11ea-82ca-dfe25e3edfed.png)



}
