### ISSUE TITLE
How to display timestamp

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-Composer#3350]
how to display the dialog conversession start and end timestamp in composer.

**Comment by hibrenda** [comment]
You can reference the prebuilt funciton https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#date-and-time-functions  and use utcNow() in Greeting (conversationUpdate activity)

**Comment by zxyanliu** [comment]
Hey, @madbeher any updates on this? Let us know if it works for you as suggested by @hibrenda. Thanks!

**Comment by zxyanliu** [comment]
Thanks for your report. Closing as this issue has been answered. Feel free to reopen when you think is necessary.
