### ISSUE TITLE
Entity Extraction/Validation in Bot Composer

### ISSUE THREAD

**Issue by Trubzzz** [microsoft/BotFramework-Composer#3352]
![ComposerIssueImg](https://user-images.githubusercontent.com/64170617/84059103-ad339100-a97f-11ea-891d-f295dabb18b9.png)

I have a composer text input task with the following settings. I'm making a bot testing the capabilities of Luis integrations with a bot. The issue I'm facing is not the entity recognition itself; rather the entity validation on the input task for the entity. I only notice this when using a text input task and have the entity validation working for other tasks (specifically datetime). 

To illustrate my issue, here are two current behaviors of the bot:
1) WAI: I say something like "I want to make an appointment and my contact number is (800)-234-5678". This not only triggers my intent model and skips the user input question where I ask for the user's phone number (seeing as they provided one already) and the conversation.phoneNumber variable is (800)-234-5678
2) Not WAI: I say something like "I want to make an appointment and my contact number is abc". This triggers my intent model as desired but skips the user input question where I ask for the user's phone number (because it thinks they provided one already) and the conversation.phoneNumber variable is abc. Ideally, this is where I would think validation would happen and it would ask the question "What is a good phone number for our office..." seeing as abc isn't a phone number. 

For reference, this is the documentation I'm following:
https://docs.microsoft.com/en-us/composer/how-to-define-advanced-intents-entities

**Comment by hibrenda** [comment]
you can define regex for the entity definition.
eg. @ zipcode = /[0-9]{5}/ 
Or you can edit in validation field. https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#isMatch

**Comment by Trubzzz** [comment]
Yeah, I considered a regex validator as an option, but doesn't that undermine the idea of entities as a whole? Because I can see the raw data from the validation when I type in an utterance that no entity is being picked up (so SOMETHING is working in the background). I'm just curious if I can make use of that functionality.

As I said before, this is working fine when validating if a user entered a date/time on a separate task; I'm just curious if there's a feature for this for other built-in entities in the bot composer.

**Comment by hibrenda** [comment]
@KayMKM may help to comment.

**Comment by KayMKM** [comment]
I tried this scenario: use personName entity to validate text input. Hope this can help you.
![image](https://user-images.githubusercontent.com/19773357/84878626-abbf4280-b0bc-11ea-9eef-c2ab3e304873.png)
define prebuilt entity personName:
![image](https://user-images.githubusercontent.com/19773357/84878726-cd202e80-b0bc-11ea-8769-f0500cc264ba.png)
set validation:
![image](https://user-images.githubusercontent.com/19773357/84878782-e3c68580-b0bc-11ea-8721-4eb63fc16933.png)

**Comment by Trubzzz** [comment]
This looks to be working! Adding that validation rule works for this entity and my bot, so thank you very much! Appreciate your efforts and for helping to resolve this issue!
