### ISSUE TITLE
Need to do a pass at toolbar menus and buttons: consistent, context sensitive

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3356]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by a-b-r-o-w-n** [comment]
Duplicate of #3494
