### ISSUE TITLE
Improve Auto Update UX when Explicitly Checking

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Composer#3357]
## Is your feature request related to a problem? Please describe.

In issue #3156, one of our users said that they would like to see feedback -- like the dialog prompts that show when checking for updates **without** the "Auto update" setting checked -- when explicitly checking for updates using the "Help -> Check for updates" menu item.

## Describe the solution you'd like

Show update feedback via dialogs **in all cases** when explicitly checking for updates using the "Help -> Check for updates" menu item.

## Additional context

Currently, if the "Auto update" setting is checked and the user explicitly checks for updates using the "Help -> Check for updates" menu item, no feedback is shown and the update is either downloaded in the background or nothing happens (if there is no update available).

It might be a better user experience to turn on feedback dialogs when explicitly checking for updates regardless of the "Auto update" setting.

**Comment by mewa1024** [comment]
Appears to be working in Composer 2.0. Screenshot shows the dialog that appears when you explicitly select Help > Check for updates while auto-update is also selected:
![image](https://user-images.githubusercontent.com/39317542/124375721-8023e180-dc58-11eb-96db-e2c18f988b63.png)
