### ISSUE TITLE
Issue Starting Bot - Getting .NET SDK error each Time

### ISSUE THREAD

**Issue by rryan738** [microsoft/BotFramework-Composer#3358]
Hi There I tried to install bot framework composer win setup.exe on my windows 8.1 64 bit laptop. It installs fine. I have installed bot framework emulator and Visual Studio 16.5 as well. When I create new project and try to start Bot I get Install Microsoft.Net Core SDK, so I went to the link and installed it.I did some  dotnet commands at the cmd to verify it is installed but each time i get same error. I have emulator and VS open but makes no difference do i need to install something else as well. Sorry if I have missed some steps here. Thanks Rob.

**Comment by luhan2017** [comment]
@rryan738 , this should relate to this issue #3182, we already have a fix on this and it will be available in the next release. 
To mitigate on this, could you please try this:
https://github.com/microsoft/BotFramework-Composer/issues/3182#issuecomment-63453080

1. Go to the settings page, Runtime Config, select use custom runtime. There will be a runtime folder created in your bot folder.
2. Go to that folder and run "dotnet run --project azurewebapp", you will see the detail error messages.

You can share your error message here.

**Comment by rryan738** [comment]
Hi Luhan, Thanks for your help. This is output of error in that folder. Let me know if you need anything further. Thanks 
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Robtos>cd weatherbot2

C:\Users\Robtos\weatherbot2>cd runtime

C:\Users\Robtos\weatherbot2\runtime>dotnet run --project azurewebapp
C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.
WebApp.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' wa
s restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .N
ETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4
.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETC
oreApp,Version=v3.1'. This package may not be fully compatible with your project
.
C:\Users\Robtos\weatherbot2\runtime\core\Microsoft.BotFramework.Composer.Core.cs
proj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restore
d using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramewo
rk,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NE
TFramework,Version=v4.8' instead of the project target framework '.NETStandard,V
ersion=v2.0'. This package may not be fully compatible with your project. [C:\Us
ers\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebAp
p.csproj]
C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.
WebApp.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' wa
s restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .N
ETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4
.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETC
oreApp,Version=v3.1'. This package may not be fully compatible with your project
.
C:\Users\Robtos\weatherbot2\runtime\core\Microsoft.BotFramework.Composer.Core.cs
proj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restore
d using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramewo
rk,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NE
TFramework,Version=v4.8' instead of the project target framework '.NETStandard,V
ersion=v2.0'. This package may not be fully compatible with your project.
Controllers\BotController.cs(6,1): warning SA1200: Using directive should appear
 within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp
\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\BotController.cs(7,1): warning SA1200: Using directive should appear
 within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp
\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\BotController.cs(8,1): warning SA1200: Using directive should appear
 within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp
\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\BotController.cs(9,1): warning SA1200: Using directive should appear
 within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp
\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\BotController.cs(10,1): warning SA1200: Using directive should appea
r within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebap
p\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\BotController.cs(11,1): warning SA1200: Using directive should appea
r within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebap
p\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\SkillController.cs(4,1): warning SA1200: Using directive should appe
ar within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azureweba
pp\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\SkillController.cs(5,1): warning SA1200: Using directive should appe
ar within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azureweba
pp\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\SkillController.cs(6,1): warning SA1200: Using directive should appe
ar within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azureweba
pp\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\SkillController.cs(7,1): warning SA1200: Using directive should appe
ar within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azureweba
pp\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\SkillController.cs(8,1): warning SA1200: Using directive should appe
ar within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azureweba
pp\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\SkillController.cs(9,1): warning SA1200: Using directive should appe
ar within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azureweba
pp\Microsoft.BotFramework.Composer.WebApp.csproj]
Controllers\SkillController.cs(10,1): warning SA1200: Using directive should app
ear within a namespace declaration [C:\Users\Robtos\weatherbot2\runtime\azureweb
app\Microsoft.BotFramework.Composer.WebApp.csproj]
Program.cs(4,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Program.cs(5,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Program.cs(6,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Program.cs(7,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Program.cs(8,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Program.cs(9,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Program.cs(10,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Program.cs(11,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Program.cs(12,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Program.cs(13,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(4,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Startup.cs(5,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Startup.cs(6,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Startup.cs(7,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Startup.cs(8,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Startup.cs(9,1): warning SA1200: Using directive should appear within a namespac
e declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFram
ework.Composer.WebApp.csproj]
Startup.cs(10,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(11,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(12,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(13,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(14,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(15,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(16,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(17,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(18,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(19,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(20,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(21,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(22,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(23,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(24,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(25,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(26,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(27,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(30,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Startup.cs(31,1): warning SA1200: Using directive should appear within a namespa
ce declaration [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFra
mework.Composer.WebApp.csproj]
Controllers\BotController.cs(1,1): warning SA1633: The file header XML is invali
d. [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Compo
ser.WebApp.csproj]
Controllers\SkillController.cs(1,1): warning SA1633: The file header XML is inva
lid. [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Com
poser.WebApp.csproj]
Program.cs(49,21): warning SA1005: Single line comment should begin with a space
. [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Compos
er.WebApp.csproj]
Program.cs(1,1): warning SA1633: The file header XML is invalid. [C:\Users\Robto
s\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]

Startup.cs(29,1): warning SA1005: Single line comment should begin with a space.
 [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Compose
r.WebApp.csproj]
Startup.cs(137,13): warning SA1005: Single line comment should begin with a spac
e. [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Compo
ser.WebApp.csproj]
Startup.cs(46,1): warning SA1028: Code should not contain trailing whitespace [C
:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.W
ebApp.csproj]
Startup.cs(135,1): warning SA1028: Code should not contain trailing whitespace [
C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.
WebApp.csproj]
Startup.cs(1,1): warning SA1633: The file header XML is invalid. [C:\Users\Robto
s\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]

Controllers\BotController.cs(22,51): warning SA1309: Field '_adapter' should not
 begin with an underscore [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Micro
soft.BotFramework.Composer.WebApp.csproj]
Controllers\BotController.cs(24,31): warning SA1309: Field '_bot' should not beg
in with an underscore [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft
.BotFramework.Composer.WebApp.csproj]
Controllers\BotController.cs(38,46): warning SA1101: Prefix local calls with thi
s [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Compos
er.WebApp.csproj]
Controllers\BotController.cs(38,55): warning SA1101: Prefix local calls with thi
s [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Compos
er.WebApp.csproj]
Controllers\BotController.cs(38,65): warning SA1101: Prefix local calls with thi
s [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Compos
er.WebApp.csproj]
Startup.cs(93,64): warning SA1101: Prefix local calls with this [C:\Users\Robtos
\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
Startup.cs(97,13): warning SA1101: Prefix local calls with this [C:\Users\Robtos
\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
Startup.cs(98,13): warning SA1101: Prefix local calls with this [C:\Users\Robtos
\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
Startup.cs(99,13): warning SA1101: Prefix local calls with this [C:\Users\Robtos
\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
Startup.cs(119,13): warning SA1101: Prefix local calls with this [C:\Users\Robto
s\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]

Startup.cs(161,27): warning SA1101: Prefix local calls with this [C:\Users\Robto
s\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]

Startup.cs(172,30): warning SA1101: Prefix local calls with this [C:\Users\Robto
s\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]

Startup.cs(174,33): warning SA1101: Prefix local calls with this [C:\Users\Robto
s\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]

Startup.cs(178,93): warning SA1101: Prefix local calls with this [C:\Users\Robto
s\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]

CSC : warning SA0001: XML comment analysis is disabled due to project configurat
ion [C:\Users\Robtos\weatherbot2\runtime\azurewebapp\Microsoft.BotFramework.Comp
oser.WebApp.csproj]
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:3979
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\Robtos\weatherbot2\runtime\azurewebapp

**Comment by luhan2017** [comment]
@rryan738 , based on this log, though there are so many warnings, you bot is successfully started on http://localhost:3979, could you double check if you still can't Start your bot by composer?

**Comment by rryan738** [comment]
Hi Luhan, It looks like when I go to settings  it has restarted and I can test in emulator and open website on local host 3979, however if I try to restart it I get attached error message. 
![botsettings](https://user-images.githubusercontent.com/63841892/84130308-057b9900-aa3b-11ea-85ac-14697bdc9676.JPG)
![botrestart](https://user-images.githubusercontent.com/63841892/84130362-175d3c00-aa3b-11ea-8d49-c2cb963a200a.JPG)

**Comment by luhan2017** [comment]
Do you use 1.0.0 or 1.0.1? we have a fix of this bad error message issue #3228 , and released in 1.0.1 @rryan738

**Comment by rryan738** [comment]
Hi Luhan, Sorry for delay so I need to use 1.0.1 I tried to get it but it seems to be 1.0.0 is the one I keep pulling down on github would you have link to 1.0.1 ? Thanks for your help Regards Rob.

**Comment by luhan2017** [comment]
@rryan738 , please try to find this in this link: https://github.com/microsoft/BotFramework-Composer/releases

after updating, you may see the detail error while connecting the bot runtime, please let me know if it not works.

**Comment by rryan738** [comment]
Hi Luhan, That worked once I upgraded to 1.0.1 I can start and stop Bot with no errors. Thanks very much for your help with this and assisting me with resolving it.

**Comment by luhan2017** [comment]
@rryan738 thanks for the update, I am closing this issue, please reopen if needed.
