### ISSUE TITLE
property view should correctly display value in number

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#3366]
- set property with value in number as below
![image](https://user-images.githubusercontent.com/43408889/84256857-1285ae80-ab47-11ea-8c79-dd9e40c347b9.png)

- click other node
- click "set property" node again
- property view is not correct
![image](https://user-images.githubusercontent.com/43408889/84256693-d6eae480-ab46-11ea-9556-dbe3d1a2df51.png)
- data is not change in dialog file
![image](https://user-images.githubusercontent.com/43408889/84256745-ea964b00-ab46-11ea-9dc6-dabc8ca5540c.png)

**Comment by beyackle** [comment]
Some notes as I debug this: this also happens in the Value field of "emit a trace event", so it's probably happening anywhere we have a value with a settable type.

**Comment by beyackle** [comment]
Anywhere using "$ref": "#/definitions/valueExpression" in the schema makes this happen, and only on a "number" type.
