### ISSUE TITLE
Composer should write out cross train configuration 

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#3370]
In order to deploy composer generated dialogs via CI/ CD pipeline (using BF-CLI), composer should write out a cross-train.config.json. This can sit as a peer to main.dialog (root dialog) file.

This enables composer customers to use CI/CD pipelines to build and publish their LU/ QnA applications. This also enables right integration of composer generated dialogs with a code based V4 SDK bot. 

Without this, we expect composer users to always use `(re)start bot` button within composer UI to get the LUIS and QnA Maker applications set up correctly.

**Comment by cwhitten** [comment]
Why wouldn't the build process (via core libs) output this file?

**Comment by boydc2014** [comment]
> Why wouldn't the build process (via core libs) output this file?

**Comment by boydc2014** [comment]
> Why wouldn't the build process (via core libs) output this file?

Definitely one valid option, @vishwacsena what do you think?

**Comment by vishwacsena** [comment]
Sure .. as long as it is in a documented location and is also included when the runtime is ejected.

**Comment by boydc2014** [comment]
> Sure .. as long as it is in a documented location and is also included when the runtime is ejected.

One benefit of writing this out by composer is composer could potentially just output this config without doing any actual train or publishing, right? 

If we let the lib output this, will that mean, user have to run a successful pass before integrated into CI/CD? 

@cwhitten @vishwacsena

**Comment by cwhitten** [comment]
Can you share what the shape of this config would look like?

**Comment by hibrenda** [comment]
#4259
