### ISSUE TITLE
EndDialog action missing form editor to configure value property

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#3372]
## Describe the bug

EndDialog action is missing property form editor to configure `Value` property. 

Schema: https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.EndDialog.schema

Current UX: 
![image](https://user-images.githubusercontent.com/20918136/84308581-9cb41f80-ab13-11ea-8040-5a95a28e332a.png)

## Version

1.0.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Add an EndDialog action
2. Click on the action to bring up its form editor

## Expected behavior

Can see form editor for EndDialog action.

**Comment by benbrown** [comment]
@vishwacsena you have selected the End Dialog Turn action, not the "EndDialog" action.

EndDialog does have a value field.

End Dialog Turn does not - is it supposed to?

**Comment by vishwacsena** [comment]
@benbrown I just did not see the difference between `End Dialog` and `End Dialog turn` and it did not even occur to me that I might have added the wrong action .. In any case, may be we could have the UI say `End turn` instead of `End dialog turn` to minimize user error?

**Comment by benbrown** [comment]
Concur!! I will change the title of this issue.
