### ISSUE TITLE
Ejected runtime should use a relative path

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3376]
The path you get when you eject a runtime is an absolute path. This can be problematic when you have multiple people trying to work with the same project. We should be using relative paths:

![image](https://user-images.githubusercontent.com/698939/84333236-0a783f80-ab44-11ea-8dc5-6e9981281bd2.png)

**Comment by benbrown** [comment]
Good point!

**Comment by cwhitten** [comment]
Relative to what, though?

**Comment by benbrown** [comment]
To the project itself, I would assume.

This would assume, however, that the project and the runtime are statically related to one another as they are in the case where it is inside the same folder. This would NOT apply if you completely separate the assets -- however, that is a use case we are mostly assuming and haven't seen in the wild yet.

**Comment by cwhitten** [comment]
This is fixed, closing.
