### ISSUE TITLE
CardAction without Luis interfering

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3377]
I am looking for a possible way to get a menu to work with suggested actions, without Luis interfering and messing up. This is what I want;
![image](https://user-images.githubusercontent.com/49873947/84383583-d3119d80-abec-11ea-8b82-2fbdbeae2da6.png)

Language generation:
[Activity
  Text = ${if(user.props.menuShown, 'What else can I help you with?', 'What can I do for you today?')}
  SuggestedActions = ${postButton('My To-do\'s','MyToDo')} | ${postButton('My Personal Information','MyInfo')} | ${postButton('My Time Off', 'TimeOff')} |  ${postButton('My Team', 'MyTeam')}
]

![image](https://user-images.githubusercontent.com/49873947/84383658-fccac480-abec-11ea-828d-764eb74c4ec7.png)

I have tried many different CardAction types, inlucing imBack, postback, messageBack, but nothing seems to work.

In this menu the user should be able to:

- type -> Luis kicks in

- click a suggested action -> No Luis, the text of the button is added to the conversation and the turn.activity.value can be used to start a new Dialog.

I would expect that when I use the following Card:
![image](https://user-images.githubusercontent.com/49873947/84386298-5d5c0080-abf1-11ea-9e07-e60345103a27.png)

Which results in:
![image](https://user-images.githubusercontent.com/49873947/84386330-6cdb4980-abf1-11ea-94da-6b939586a9b8.png)

That since the text is null, Luis would not kick in. However this still triggers Luis and gives an error:
![image](https://user-images.githubusercontent.com/49873947/84386383-85e3fa80-abf1-11ea-9943-d78a1c43cda1.png)

**Comment by hibrenda** [comment]
@cxbuilders  the error is not introduced by LUIS. this is due to the unexpected format set in Value property.  you should define the value as a json object if the CardAction type is messageback. "text" content will be sent to your bot when the cardaction define the text content .

![image](https://user-images.githubusercontent.com/43408889/84857830-7a367f00-b09c-11ea-8b9a-828832217451.png)


```
# AdaptiveCard
[Activity
  suggestedActions = ${postbutton("hello",json(data()))}
]

#postbutton(text,value)
[CardAction
title = ${text}
type = messageBack
value = ${value}
]

#data
  -```
  {
  "$data": {
        "employee": {
            "name": "Matt",
             "peers": [{
                "name": "Andrew",
                "title":"pm"
            }, 
            { 
                "name": "Lei",
                "title":"lead"
            }
            ]
        }
    }
    }
    ```
```

you can reference the schema definition at: https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.cardaction.-ctor?view=botbuilder-dotnet-stable

**Comment by cxbuilders** [comment]
@hibrenda Yeah, but I just want a button that does not trigger Luis. I was just giving some examples I did try. Luis, always kicks in, I don't want Luis for these buttons at all

**Comment by hibrenda** [comment]
This is due to you set the recognizer type as "Luis"  for this dialog. So each turn will go through recognizer . if you set the recognizer as "none" for this particular dialog, it won't trigger the luis.

**Comment by cxbuilders** [comment]
@hibrenda Yeah but that's exactly what I need. Either have the user type something with NLP or click a button without NLP. This is a fairly typical setup that I have used many times in other platforms.

**Comment by hibrenda** [comment]
@vishwacsena  do you have comments to support NLP toggling for each turn ?

**Comment by vishwacsena** [comment]
@cxbuilders your expectation is right. [This PR][1] addressed the issue where the LuisRecognzier was always returning an intent recognition even if the text was empty. This should be available in composer as part of next release. 

You can use `adaptive cards` if that works for your use cases. This still requires you to set up custom triggers to handle button click actions. 

[cardSample.zip](https://github.com/microsoft/BotFramework-Composer/files/4815900/cardSample.zip)

With this sample, clicking on the card buttons does not run the LUIS recognizer while typing the text does run the recognizer.

Another issue with using `Suggested actions` is that the `text` property on the incoming message activity from the client is likely to contain the `value` which will cause the recognizer to run.

@hibrenda 

[1]:https://github.com/microsoft/botbuilder-dotnet/pull/4129

**Comment by cxbuilders** [comment]
@hibrenda @vishwacsena  Thanks for the update. Good to see this gets picked up

**Comment by peterinnesmsft** [comment]
Will be included within the R10 release in the next few days.
