### ISSUE TITLE
How to best use Authentication in Composer

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3379]
I am struggling a bit with the best way to implement Authentication in the bot I'm building with Composer. The bot should be completely locked without authentication. It can be called both as standalone bot and as a skill bot for PVA.

I have a separate dialog that handles with all the authentication that I currently call from the greeting trigger. There are a couple of issues;

1. When called from PVA I have triggers that call individual dialogs and I don't want to add the authentication check to each trigger in the root dialog
2. The OAuth login is by default set to a turn count of 3. After that the user input is just ran through the other triggers allowing users to access the bot without authentication. Setting that to a real high number feels quite horrible

Is there a way where the Authentication dialog is called before each and any message / activity / event etc  in the root dialog do I can make sure the bot is completely closed without having to add that to each individual trigger in the root dialog?

**Comment by hibrenda** [comment]
@DingmaomaoBJTU may help to answer

**Comment by DingmaomaoBJTU** [comment]
For the second issue, you can add an condition branch after oauth prompt to check whether token had been retrieved. If not, you can send error message back then cancel all dialogs.

For the first issue, do we have a pattern (i.e. a middleware) to check authentication before all the activities/events @vishwacsena ?

**Comment by cxbuilders** [comment]
@hibrenda @DingmaomaoBJTU Any updates on this?

**Comment by hibrenda** [comment]
@cxbuilders  for question 1, may need a sample support from middleware. @cwhitten

**Comment by tdurnford** [comment]
@cwhitten @hibrenda do either of you have any updates?

**Comment by ninggao** [comment]
Close this issue. @cxbuilders, please feel free to reopen it if you have other questions.

**Comment by cxbuilders** [comment]
@ninggao I am under the impression that this question is still outstanding....

**Comment by ninggao** [comment]
@cxbuilders sure, I will ping everyone again.

**Comment by ninggao** [comment]
@cwhitten @hibrenda do you have any updates on this issue?

**Comment by ninggao** [comment]
@cwhitten @hibrenda @DingmaomaoBJTU pinging everyone again... Any updates on this one?

**Comment by luhan2017** [comment]
@cxbuilders , you may need to customize your runtime and build a OAuthMiddleware, which ensure that user is actually logged in in each turn. will this meet your requirement? Please let me know you need further help on this.

**Comment by cxbuilders** [comment]
@luhan2017 Was afraid of that. I would imagine that this would be something nice to have built into Composer, like a Pre & Post trigger for a Turn, where you would be able to do things like this.
Can you consider that as an enhancement request? Then for now I'll dive into C#... :)

**Comment by stevengum** [comment]
@luhan2017 can you write up a spec for the botbuilder-dotnet repository so the team can discuss it?

**Comment by zidaneymar** [comment]
@cxbuilders Hi, I could explain the corresponding functionality. Hope it helps.

Step1: You should write your customized OAuthMiddleware. For example: https://github.com/zidaneymar/CustomizedRuntime/blob/main/azurewebapp/OAuthMiddleware.cs
This middleware do one thing:
On each OnTurnAsync (message comes), pop up an OAuthPrompt dialog to the user, if already signed in, the OAuthPrompt would skip this step automatically. But it would take extra efforts to do this (maybe the responding time would be longer).

Step2: Initialize and load this middleware in Startup.cs
https://github.com/zidaneymar/CustomizedRuntime/blob/3203fca46f2c86a70ab3e9eeefb65af4b5087809/azurewebapp/Startup.cs#L186
https://github.com/zidaneymar/CustomizedRuntime/blob/3203fca46f2c86a70ab3e9eeefb65af4b5087809/azurewebapp/Startup.cs#L103

Step3: Set up your connectionName in Composer settings (or you could hardcode this in your C# file).
![image](https://user-images.githubusercontent.com/9328933/97399622-7b1fcd00-1928-11eb-8e5c-3b7e156dc7e2.png)

Step4: Eject this runtime to your composer.
![image](https://user-images.githubusercontent.com/9328933/97399657-91c62400-1928-11eb-97a1-55bfd07cead3.png)

Step5: Test your bot.

![image](https://user-images.githubusercontent.com/9328933/97399735-b7532d80-1928-11eb-859d-788ff17ab6a0.png)


The bot would try to pop up an OAuth card each turn, but after signing in, the bot would skip this and just echo back the response.

**Comment by luhan2017** [comment]
@stevengum Steve created a AdaptiveMiddleware proposal, please refer to #4283

**Comment by cxbuilders** [comment]
@zidaneymar Thanks for the sample that's appreciated. I have used it to trigger custom events called PreActivity & PostActivity so I am able to implement session logic etc there myself in Composer.

@luhan2017  As mentioned, having the PreActivity & PostActivity implemented in Compsoer OOTB would be really useful, as I prob would be using it for the majority of the bots. Should I create a separate feature request for that?

**Comment by luhan2017** [comment]
@cxbuilders Sure, please just create a feature request for dotnet sdk https://github.com/microsoft/botbuilder-dotnet/tree/main

**Comment by cxbuilders** [comment]
https://github.com/microsoft/botbuilder-dotnet/issues/4928
