### ISSUE TITLE
Skill Manifest experience under par

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3380]
The whole setup of the skill manifest editor feels like it is lacking behind the rest quite a bit. Below my thoughts on this:

**Export as skill**
Having it under the export dropdown and calling it export as skill sounds strange to me. You're actually not exporting anything, you're just creating a manifest which makes it a skill. So I would just expect it to be called something like "edit skill manifests"

**Naming of Manifests**
The naming of the manifests are fixed to {Botname}{schema version}.json
This makes no sense to me, why is the schema version part of the filename? Also having the botname in the filename seems not needed, as the url of the manifest will contain the botname, so it only gets unnecessarily complicated. To me the best way of doing this would be to use the actual version of the manifest itself like so: manifest-v1.0.json
![image](https://user-images.githubusercontent.com/49873947/84427413-24d61a00-ac25-11ea-8213-977c9f588ba8.png)

**Editing Manifests**
It should be possible to manage multiple manifests to allow for different versions. Currently when creating a new one it just overwrites whatever is there..

**Comment by hibrenda** [comment]
Hi @cxbuilders thanks for the feedback. This is on our radar. we have several issues tracking skill manifest experience. @mareekuh  for your awareness.

**Comment by mareekuh** [comment]
Yup, thank you. A more user friendly experience is spec'ed and in the works.
Groetjes,
Marieke

**Comment by cxbuilders** [comment]
Helemaal goed!

Thanks,
Bastiaan

**Comment by sgellock** [comment]
@hibrenda can you provide links to issues so this customer can track our progress and see what work is on the books?  thank you

**Comment by hibrenda** [comment]
@sgellock Sure. attached the issues https://github.com/microsoft/BotFramework-Composer/issues/3355
and related pr https://github.com/microsoft/BotFramework-Composer/pull/3436

**Comment by mareekuh** [comment]
- **Export as skill -**> Add another toolbar item: Create manifest and Leave the 'Export as skill'. [See design here](https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-main-design-spec-UI-library?node-id=1174%3A0)
- **Naming of Manifests** -> Fair request. Is there a reason why the name is not editable? If not, let's add a default name (structured as currently spec'ed) but allow people to change it. @tdurnford 
- **Editing Manifests** -> seems reasonable - @cxbuilders : what is the scenario in which one wants to generate multiple manifests and wants to keep them all? Replacing the existing manifest keeps things simple and tidy (no need to add other UI/functionality to have people manage multiple manifests).

**Comment by cxbuilders** [comment]
@mareekuh Keeping multiple versions was about versioning the bot, however the bot itself represents 1 version, so 1 manifest would do. So I agree you can skip this requirement.
