### ISSUE TITLE
Add "Show Console" option to runtime settings page

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3394]
## Is your feature request related to a problem? Please describe.

Currently, when composer runs an ejected runtime it does so in a hidden console window. While this helps avoid cluttering up the users desktop it means that you can't see any console logging coming from the runtime. And more importantly, should the runtime throw an exception you have no clue what it was. 

## Describe the solution you'd like

It would be nice if there was a "Show Console" option under the runtime configuration tab.

## Describe alternatives you've considered

I've worked around this for now by creating the following `debug.cmd` batch file:

```
start cmd.exe /K "dotnet run --project azurewebapp %1 %2 %3 %4 %5 %6 %7 %8 %9"
```

I run that as my startup command which launches a visible console window.

**Comment by a-b-r-o-w-n** [comment]
I'll evaluate this as a P1/P2 for R11.

**Comment by Stevenic** [comment]
This would still be useful... It's good that you're showing the stack trace when the runtime fails to start but that doesn't help with diagnosing issues on a turn by turn basis.

**Comment by tonyanziano** [comment]
Now that Composer exposes the runtime output in the "Output" tab, is this necessary anymore?

**Comment by Stevenic** [comment]
Closing based on @tonyanziano comment
