### ISSUE TITLE
Bot Framework Composer 1.0.1 not work with LUIS

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#3399]
With sample "ToDoBotWithLuisSample" Azure Luis service not respond.

## Version
Bot Framework composer desktop 1.0.1
## Browser
- [X] Electron distribution
- [ ] Firefox
- [ ] Safari
- [ ] Chrome
- [ ] Edge

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce
Try to run sample: ToDoBotWithLuisSample
## Expected behavior
Contact LUIS in Bot Emulator Log
At least the LUIS trace in the log.

## Screenshots
![image](https://user-images.githubusercontent.com/24985956/84491444-d8322380-aca4-11ea-91fb-94ac1df873c2.png)

Composer create correctly the LUIS app during build.
![image](https://user-images.githubusercontent.com/24985956/84491561-04e63b00-aca5-11ea-9b9a-484a40b1610f.png)

@fathorMB @marcozama

**Comment by hibrenda** [comment]
@andreatosato I could not repro your issues. could you share more info ? I tested with Electron without any issues.
