### ISSUE TITLE
Create how-to guide on hosting Composer as a web app

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3402]
Create a guide with instructions and tips for hosting Composer and extending in various ways.

* How to host Composer in the cloud
* How to set up multi-user authentication via plugins
* How to set up customized storage, make storage multi-user aware
* How to provide an alternate version of the runtime template
* How to change the boilerplate content added to each project

**Comment by zxyanliu** [comment]
Working in progress in [this branch](https://github.com/MicrosoftDocs/composer-docs-pr/blob/yl-host-composer/composer-docs/how-to-host-composer.md).

**Comment by cwhitten** [comment]
Closing this as it's in-review with the docs team
