### ISSUE TITLE
Need docs: best practices for designing conversations in Composer

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3403]
We need to create a set of instructions and tips that serve as an introduction to best practices for achieving common conversational scenarios in Composer.

For example:

* Use of sub-dialogs as "functions" with return values
* How to set up and configure prompts with all the fancy conversational options we have
* How to get the most out of extracted entities
* How to set up and get the most out of interruptions
* Applications for the many various trigger types we have

**Comment by zxyanliu** [comment]
@benbrown I drafted some rough [scope](https://microsoft-my.sharepoint.com/:w:/p/v-liyan/EdivIw6DKDlBlTho9jbtj7UB58-HfgN4e02DWWlmwAZ_Bg?e=Gtvw39) to be covered in this topic.

**Comment by cwhitten** [comment]
Closing this as it's in-review with the docs team
