### ISSUE TITLE
Allow ejected runtime to be updated to latest 

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3406]
As updates are made to the runtime template, developers want to adopt these changes.  Currently, it is required to manually delete the runtime folder before re-ejecting.

We should introduce a feature inside Composer which allows the user to re-eject an updated version of the code OR to switch between versions of the runtime.

See also #3102  - allow updating of boilerplate material only

**Comment by VanyLaw** [comment]
Runtime version is different from runtime type too. I will implement this by adding a getVersion method in runtime plugin after the js runtime PR merged. Then checking the template runtime version with customized runtime version, if the version is different in re-eject, copying the runtime into new folder name runtime-<version> and change the runtime path.

**Comment by benbrown** [comment]
@VanyLaw For the Javascript version of the runtime, we should use the version number in package.json I think. What do you think?

I don't know if there is a C# version of that - perhaps we use a version.txt or something?

We should not do this automatically for the user. It should be implemented in the same way the boilerplate version check happens -- on the runtime settings page.

**Comment by VanyLaw** [comment]
yes, for js runtime, we can simply use the version number in package.json. For c# runtime, the version can be add in <Version> in .csproj file, like
```
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Version>1.2.3</Version>
</PropertyGroup>
```
In that way, we need to parse xml file to get the version of runtime template and compare with the ejected runtime.

Besides, maybe we need to split the webapp version and function version in js runtime.

**Comment by benbrown** [comment]
That makes sense to me. 

Have you seen the code/ui for doing this with the boilerplate material?

Here is the controller:
https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/server/src/controllers/project.ts#L349

The meat of the implementation is in the asset manager:
https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/server/src/models/asset/assetManager.ts#L64

And of course, in the client page:
https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/client/src/pages/setting/runtime-settings/RuntimeSettings.tsx#L48

My only note here would be that the client is using "global" state instead of component level state, which is more complex than it needs to be since this information is only used on the settings page.

**Comment by luhan2017** [comment]
ejected runtime deprecated.
