### ISSUE TITLE
Something went wrong 

### ISSUE THREAD

**Issue by ashritkulkarni** [microsoft/BotFramework-Composer#3409]
Something went wrong immediately after creating the app. I tried to access the trigger and it show that something has went wrong

**Comment by hibrenda** [comment]
Could you share error screenshot ? If you restart the composer app and editing the triggers, could you reproduce it ?

**Comment by ashritkulkarni** [comment]
![image](https://user-images.githubusercontent.com/49915656/84819770-91b33080-afe6-11ea-892e-02282b7e9f6f.png)

**Comment by ashritkulkarni** [comment]
Yes it persists the same way

**Comment by hibrenda** [comment]
@zhixzhan could you check this again

**Comment by zhixzhan** [comment]
Sure, maybe display more error detail instead of `someting went wrong` would be more helpful. I will take a look.

**Comment by yalamarti** [comment]
Same exact issue - tried all - rebooted. restarted. created empty bot . launched as Admin; tried creating an echo bot from template ... same issue ... exact screen shot as shared by @ashritkulkarni .  Is there any specific runtime requirement that I am missing?  

![image](https://user-images.githubusercontent.com/44853062/88721026-c8a35880-d0f3-11ea-9d95-a0b8b849a189.png)

![image](https://user-images.githubusercontent.com/44853062/88721123-f2f51600-d0f3-11ea-9d88-785921d98ea3.png)

**Comment by Acnokal** [comment]
i had this issue and i just restarted it after a while and the issue is gone. Sounds like usual microsoft way of error correction

**Comment by yalamarti** [comment]
@Acnokal Not in my case ... restarted, rebooted. Didn't work for me.

@zhixzhan :

I am behind a proxy server.   Is there any Composer related configuration file where I can specify the proxy server details.  

I am unable even to get to the Settings 'page' to see if it has any proxy related setting feature.

Regards
Athadu
