### ISSUE TITLE
Bot Secrets

### ISSUE THREAD

**Issue by hraz-msft** [microsoft/BotFramework-Composer#3413]
How should the bot hold secrets and use them when sending HTTP Requests?

**Comment by luhan2017** [comment]
@hraz-msft , you can refer to oauthinput dialog in AskingQuestionsSample

1. You can use OAuthInput to get user.token.
2. Then use ${user.token.token} to pass the token in the http header. 

![image](https://user-images.githubusercontent.com/32191031/84639318-ca8dcf80-af2a-11ea-9abb-37bfa2b37214.png)

**Comment by hraz-msft** [comment]
@luhan2017, I'm not sure the OAuth component is what I need. Since I don't need to user token, I need machine-to-machine authentication with POST call to `https://login.microsoftonline.com/common/v2.0/oauth2/token` (accept string body only - only `x-www-form-urlencoded` content type is supported)

**Comment by hraz-msft** [comment]
@luhan2017, I meant, I need for some APIs the Bot App ID and the Bot Secret ID and more secrets to hold. 

Where should I hold them in Composer?

**Comment by luhan2017** [comment]
@hraz-msft , Composer now don't support to help encrypt any of your secrets for now, will this #3315 fulfill your requirement?

**Comment by hraz-msft** [comment]
Not exactly... I talked to Steve (Stevenic) and he said that I can enter secrets to `app config` and then use the `settings` variables to access them. That's more than enough for me :)

**Comment by daronyondem** [comment]
@hraz-msft I have the latest (v.1.3.0) composer and can't figure out where the `bot setting` section is. All I can see is Project Settings, and the fields on that UI are pretty static looking to me. Am I missing something? I'm looking for somewhere to store 3rd party API keys used in HTTP Requests. These are used in multiple places. I'm not really worried in the context of a secret, but more looking for a config repository I can use that hopefully comes out of the box. Any suggestions?

**Comment by hraz-msft** [comment]
@daronyondem in the last version, go to Project Settings and click on the toggle button `Advanced Settings View (json)`

Then you can add fields to the JSON and use them with the `settings` scope variable

**Comment by daronyondem** [comment]
That is pretty user-hostile :) I hope the team has improvements in mind. Including @luhan2017 in case he can pass on the feedback. 

Thanks @hraz-msft 👍
