### ISSUE TITLE
Composer: High CPU and RAM usage it doesn't load the Composer UI

### ISSUE THREAD

**Issue by ramonck** [microsoft/BotFramework-Composer#3414]
I have verified that the compose doesn't run and open the interface if I have a high memory usage or high RAM usage and the process runs in the background with no user inteface loaded.

## Version

![image](https://user-images.githubusercontent.com/5229948/84600153-c475f100-ae4d-11ea-9cba-327b7a1b05fb.png)

## OS

Windows 10

## To Reproduce

Double click on the Compose Icon.

**Comment by boydc2014** [comment]
This is very likely due to electron is not getting enough memory it needs.  I think we can confirm did we catch OOM error and emit a clear message in that case. 

cc @cwhitten  @tonyanziano .

**Comment by tdurnford** [comment]
@tonyanziano thoughts?

**Comment by tonyanziano** [comment]
@ramonck can you reproduce this while running Composer from the command line / terminal?

On Windows: 

1. Navigate to where `Bot Framework Composer.exe` is located on your machine
2. Open a command line or terminal window at that location
3. execute `Bot Framework Composer.exe` 

This will show any output from the Composer process in the command line window. I'd like to know if there is a specific error that we can listen for in this case, such as "insufficient memory" or something similar. Then we can handle it properly and notify the user.

**Comment by ninggao** [comment]
@tonyanziano Any updates?

**Comment by tonyanziano** [comment]
I haven't had time to look at this yet as I'm also working on the PVA integration right now and that is a higher priority. I will investigate afterwards.

**Comment by tonyanziano** [comment]
@ramonck could you please try to reproduce this using [the steps I listed above?](https://github.com/microsoft/BotFramework-Composer/issues/3414#issuecomment-696796749)

I cannot reproduce this, so if you are still experiencing this issue and can paste the output here that would be very helpful. Thanks.

**Comment by ramonck** [comment]
You guys have improved the performance I believe I also changed my HD to SSD in the meanwhile and it just works great with everything so no more issues here on my end.
