### ISSUE TITLE
URL doesn't work: https://aka.ms/att/publishbot

### ISSUE THREAD

**Issue by ramonck** [microsoft/BotFramework-Composer#3415]
As in this youtube video from Microsoft Azure the following url shortcut doesn't work, it needs to be fixed.

The video: https://www.youtube.com/watch?v=XNE43x_JaR4

The url: https://aka.ms/att/publishbot

The target url: https://github.com/microsoft/BotFramework-Composer/blob/stable/docs/deploy-bot.md?WT.mc_id=github-azuredevtipsvideo-micrum

The Screenshot:
![image](https://user-images.githubusercontent.com/5229948/84604232-dc0fa280-ae6a-11ea-8c51-f3f0e3f6f736.png)

**Comment by hibrenda** [comment]
@zxyanliu @cwhitten could you comment on this ?

**Comment by zxyanliu** [comment]
Hey @ramonck Thanks for reporting the issue. If you are looking for instructions on how to publish a bot created using Composer, please refer to this [doc](https://docs.microsoft.com/en-us/composer/how-to-publish-bot). 

@cwhitten I do not have access to this aka link:  https://aka.ms/att/publishbot so I cannot update the target url. The one I have pointing to the [publish article](https://docs.microsoft.com/en-us/composer/how-to-publish-bot) is this one: https://aka.ms/bf-composer-docs-publish-bot

**Comment by zxyanliu** [comment]
Hi @ramonck, I am not sure if we have the permission to update the broken URLs you mentioned. Here are the links:
- Install Bot Framework Composer:  https://docs.microsoft.com/en-us/composer/setup-yarn
- Publish a bot: https://docs.microsoft.com/en-us/composer/how-to-publish-bot

**Comment by zxyanliu** [comment]
Hey, we don't have the permission to update the URL in youtube channel. Closing this issue. Please follow the suggested links to move on. Thanks!
