### ISSUE TITLE
Connecting Bot with Cognitive Search in composer

### ISSUE THREAD

**Issue by mweldingwala** [microsoft/BotFramework-Composer#3418]
I am a beginner programmer and a beginner using bot composer, I will really appreciate a reply in detail. Thank you in advance!!!

I am trying to take a user's input and searching that input in Cognitive Search on my portal using API and then parsing the JSON I receive. 

I was thinking of storing the user's input in a property called dialog.search_input.

1. Now how can I go about making the HTTP request?
2. According to the cognitive search docs I will need to put the api-key somewhere in the header, where exactly do I have to put that?
3. How can I make the right API call relevant to the user input? Do I have to put the user input somewhere in the URL or the header?

Please help. I m new but determined to learn this and create something.

**Comment by hibrenda** [comment]
@DingmaomaoBJTU  may help to answer this.

**Comment by DingmaomaoBJTU** [comment]
You can use HTTP request step to do this:
![image](https://user-images.githubusercontent.com/16643193/84855152-faa5b180-b095-11ea-99ce-6cdd66c2bcf6.png)

Then you can fill your api key like below:
![image](https://user-images.githubusercontent.com/16643193/84855022-b31f2580-b095-11ea-8274-16edf9912c7d.png)

And you can save user input to dialog.search_input then fill url like this:
https://<YourDomain>.search.windows.net/indexes?api-version=2019-05-06&$select=**${dialog.userInput}**

**Comment by mweldingwala** [comment]
@DingmaomaoBJTU  this would seem to  work if my dialog.result is one word and would create a url like so (let us assume dialog.result = 'hello'):

https://YourDomain.search.windows.net/indexes?api-version=2019-05-06&$select=hello


However, it would be an issue if dialog.result is multiple words like 'hello what is your name' cuz the url would look like this:

https://YourDomain.search.windows.net/indexes?api-version=2019-05-06&$select=hello what is your name

when instead it should look like this:
![1](https://user-images.githubusercontent.com/63029134/84866761-c8696500-b03f-11ea-9da3-85931ede19d9.PNG)


Hence my question now is:
1) Do I need to add these %20 things?
2) if yes how do i do it in the composer?
3) if you could tell me what the %20 is that would be awesome.

Thank you
