### ISSUE TITLE
Make it possible to add a comment in the timeline

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3419]
It is common practice to leave comments in code to explain the purpose of the code or the approach used.  We should introduce a similar functionality in Composer where comments can be left in the timeline.

These comments do not need any special functionality other than the ability to type in some text and have it displayed in the timeline in such a way that it can be easily seen and read while looking at the overall shape of the dialog.

Should these be a new "Comment" node type?

Should these be a "comment" field/tab in every node?

What should they look like in the timeline?

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/1055

**Comment by mareekuh** [comment]
Including Sang.

**Comment by sangwoohaan** [comment]
Yeah this is great. I was the log to console node for commenting.. I'll get on this.

**Comment by a-b-r-o-w-n** [comment]
@sangwoohaan What is the status of the design work on this one? Will be we able to start working on this in R10?

**Comment by mareekuh** [comment]
@a-b-r-o-w-n  This is on @vivekkshankar 's plate as he is also working on Skills and therefore will experience the need to collaborate and communicate with devs to improve and edit content and dialog flows as a designer.

@vivekkshankar  - let's check in quickly before you start.
There are 2 existing things within Composer we can build on ;
1. Every node/property currently has a **description field t**hat can contain copy. It is currently hidden (not displayed in the property panel) but was intended for this purpose. Especially if we can **@mention** in this, if we can pull this content into the **'[notifications' page](https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-main-design-spec-UI-library?node-id=3016%3A390)** (as new class of notitications )

**Comment by mareekuh** [comment]
First pass at designs by vivek are here [https://www.figma.com/file/deFhMPBnRWxTYiYDYqYxrc/Composer---Vivek?node-id=6696%3A97661](url)

@benbrown  and @a-b-r-o-w-n  Please leave comments inline in Figma

**Comment by benbrown** [comment]
I don't think this quite captures the right model - comments should all be visible, and readable as part of the flow itself. I do not think they should be hidden by default, and certainly not only visible one at a time.

The visual treatment is nice, but I would suggest that they work more like full nodes than attachments to a node.

**Comment by benbrown** [comment]
Just as a reference, here is what inline code comments look like in _code_ -- as you can hopefully see, the combined comments and code tell a fuller story than one or the other by itself.

![Screen Shot 2020-07-13 at 3 10 33 PM](https://user-images.githubusercontent.com/729873/87348903-1a0bef00-c51b-11ea-9b90-133621400bcd.png)

**Comment by vivekkshankar** [comment]
@a-b-r-o-w-n I have taken a stab at defining the experience for this:
Details here: https://www.figma.com/file/deFhMPBnRWxTYiYDYqYxrc/Composer-Vivek?node-id=6696%3A97661 

Can we discuss this further from a experience and implementation stand-point? Happy to share any additional info neccesary.

**Comment by benbrown** [comment]
@vivekkshankar I think the most recent design in this file - in particular the comment as a node -- gets this just right.

I am going to try to drive this forward!

**Comment by mewa1024** [comment]
Implemented in R14, see #7977 for details.
