### ISSUE TITLE
Make it possible to use Ad Hoc / List values as Skill input in PVA

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3421]
For skills that we are developing and are being consumed by local companies it would be really useful for them to add Ad Hoc values as input for skills in PVA.

Typical use cases are;
- number results in User search. Let user define their own behavior by typing 5 in PVA for the Skill property
- Input to define behavior of a skill's action, like 'POLITE', 'CASUAL'

Additionally having a list option for input properties of an action would make it even more user friendly for local customers. I guess that was useless in the Bot Framework <-> Bot Framework skill usage, but since PVA is in play with Citizen developers at the wheel, this would make consuming skills a much better experience.

I know this is probably not the correct place, but as it this is overlapping functionality I am hoping this could be moved into the right place.

**Comment by hibrenda** [comment]
@cxbuilders Not sure I catch your request correctly. For the scenarios you mentioned, eg. sentiment setting for bot. This may need bot developer to handle it. eg. you can set user.sentimentstate and then use this as a variable in lg file to send different response to user. The first scenario can also follow this in the dialog design.

**Comment by cxbuilders** [comment]
@hibrenda the request is that it should be possible within PVA to actually set those values manually by typing that. Now you can only pass values from variables. Currently I use a power automate flow to just set some ad hoc values that can be sent to the skill.

Additionally having a list property in the manifest would be great.

So basically this is a Bot Framework vs PVA request. Hope it can be picked up from here

**Comment by xieofxie** [comment]
hi @cxbuilders I am not sure if I understand the scenario correctly. Do you want to pass some variables that are set in PVA to the skill when the skill is called in PVA?

Currently you can do so by adding 'event' activities in the manifest like this https://github.com/microsoft/botframework-skills/blob/master/skills/csharp/pointofinterestskill/wwwroot/manifest/manifest-1.0.json

Then you will have skill actions in PVA with input 
![image](https://user-images.githubusercontent.com/2876650/85091801-e5a65b00-b21a-11ea-9356-d0817a5615f4.png)
And fill these input when calling
![image](https://user-images.githubusercontent.com/2876650/85091871-0c649180-b21b-11ea-9151-89430406ac9c.png)

To handle this in a composer skill, use OnEventActivity. The inputs are in the turn.activity.value
https://github.com/microsoft/botframework-skills/blob/3149a66cde2500888164783150824f57099f32f5/skills/declarative/todoskill/ToDoSkill.dialog#L211

Thanks

**Comment by cxbuilders** [comment]
@xieofxie What I want is that in PVA you can just type in a value as parameter:
![image](https://user-images.githubusercontent.com/49873947/86103361-f4afc780-babc-11ea-810e-dfed2506d7f0.png)

As you can see it can only use a variable that already exists in PVA. For config style parameters, you just want to type an Ad Hoc value

**Comment by xieofxie** [comment]
@cxbuilders what do you mean by `type in a value as parameter`? Is it something different from Question in PVA?

For example, you could create a question in PVA to type in value and save it in a variable then use the variable for currentLatitude.
![image](https://user-images.githubusercontent.com/2876650/86108596-ee8a0d00-baf5-11ea-9dcf-f93b81801ee6.png)

**Comment by cxbuilders** [comment]
@xieofxie Yes but this for the developer of the bot to fill in to customize the way the skill operates for their bot. We centrally develop skills that local companies can consume. We make them generic and flexible, so that the local companies can use it in multiple ways (like the limit = 5 property for returning 5 search results)

Currently just for setting a property like that the PVA builder has to create a flow, type in the properties there and then use the output variables of the flow as input variables for the skill.... (that's obviously more than just horrible).

I hope this is clear now.

**Comment by xieofxie** [comment]
@cxbuilders oh.. I finally realize that your `type` here means that developers can type a const value into the Action input instead of users type in values.

I don't know if PVA has a plan for this. Maybe they just want developers to use Power Automate to do this to increase their usage..

**Comment by cxbuilders** [comment]
@xieofxie Could you push this to the PVA issue list? This would make the combination BF / Composer / PVA much more flexible..

**Comment by vishwacsena** [comment]
@Andrea-Orimoto @scheyal @sbacha can you track this as part of the BF-PVA engagement?

**Comment by scheyal** [comment]
@cxbuilders 

Thanks raising the issue.  

From PVA team:

To clarify, you want to either assign values directly to action input variables (Flows or Skills), or to assign values directly to a variable, and pass that to the action.

We do not have this capability today, and the way to accomplish this is through Power Automate flow as the customer is doing. We do have plans for this through our work in variables assignment, but it’s not in our immediate future unfortunately. In short, it’s already in our backlog, but we don’t have a date yet.

Thanks.

**Comment by scheyal** [comment]
Tracking note: PVA #7438122

**Comment by Aavi2105** [comment]
Hi Team - I found this thread relevant to the issue which I am facing, hence asking here. 
Issue is : I built one skill bot using Bot Composer to send adaptive card to PVA. In Skill bot, I am taking input using event activity (SampleAction) trigger from PVA and then binding the data to adaptive card and sending card to PVA as per dialog configured below. I am able to trigger this skill from PVA and getting adaptive card, but after getting the card in PVA, I am seeing skill is not exiting, and any further typing in PVA will giving the below error and going to escalate topic. I tried using end turn / end dialog in composer , but still getting the same error. Please suggest what steps I need to add further to achieve this?

Error  :- Sorry, something went wrong. I am not able to help you at the moment, please check back later. Conversation ID: BtzkQK4eaJKH3hGA9PbAJq-f. Time (UTC): 7/28/2020 12:02:17 AM.


![image](https://user-images.githubusercontent.com/68352642/88604146-69fac200-d094-11ea-9730-fd75b78aaeee.png)

Thanks
Aavi

**Comment by Aavi2105** [comment]
@luhan2017 @scheyal @sbacha :- Hi , Can you please assist on above query?

Thanks
Aavi
