### ISSUE TITLE
Luis model not created if BotSettings LUIS defaultLanguage is not "en-us"

### ISSUE THREAD

**Issue by LuizOVianna** [microsoft/BotFramework-Composer#3426]
## Describe the bug

When you create a bot from a template, change Bot Settings for Luis/defaultLanguage to "pt-br" and click "start bot" it does not create a conversation APP at Luis interface and gives the messgae:

**_Sorry, something went wrong with publishing. Try again or exit out of this task._**
One or more errors occurred. Corresponding activity ID: b3c50378-4638-4fb4-9855-031b78e862cd.

When clicking in"TryAgain" it shows Publish Luis models screen, if You click "Ok" comes the message:

**_Sorry, something went wrong with publishing. Try again or exit out of this task._**
versionId cannot be null or undefined.

## Version

Version: 1.0.1-nightly.138854.830d27b
Electron: 8.0.2
Chrome: 80.0.3987.86
NodeJS: 12.13.0
V8: 8.0.426.16-electron.0

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'New'
2. Click on 'Create from template'
3. Scroll down to 'QnA Maker and LUIS
4. Click in 'QnA Maker and LUIS
5. Click "Next"
6. Choose Any Name
7. Click "ok"
8. Go to "Bot Settings"
9. Find luis configuration
10. Change name to "anyname"
11. Change defaultLanguage to "pt-br"
12. Change "authoringkey" to your Luis authoringkey
13. Click StartBot

It shows the message:
**_Sorry, something went wrong with publishing. Try again or exit out of this task._**
One or more errors occurred. Corresponding activity ID: b3c50378-4638-4fb4-9855-031b78e862cd.

When clicking in"Try Again" it shows Publish Luis models screen, if You do not change anything and click "Ok" comes the message:

**_Sorry, something went wrong with publishing. Try again or exit out of this task._**
versionId cannot be null or undefined.

## Expected behavior

It should create the model in the respective language setting.

## Additional context

The name of the model created uses a notation with special characters like "(" and ")" what makes impossible to handle it on LUIS

**Comment by hibrenda** [comment]
@LuizOVianna Thanks for the comments. This is a known issue and we are working on it now. It will be supported soon.

**Comment by cwhitten** [comment]
@zhixzhan @hibrenda @boydc2014 please consider in validation of the multi-language scenarios

**Comment by zhixzhan** [comment]
In #3398 the implementation is when change bot `settings.defaultLanguage` also sync the change to `settings.luis.defaultLanguage`

app settings.json:
```
{
  ...
  Luis: {
       ...
      defaultLanguage: 'fr-fr'.  // sync the change
  },
  defaultLanguage: 'fr-fr', // when change this 
  languages: [...]
}
