### ISSUE TITLE
Getting Error: spawnSync C:\windows\system32\cmd.exe ENOBUFS

### ISSUE THREAD

**Issue by rudrasingh21** [microsoft/BotFramework-Composer#3429]
Hi Team , 

I installed composer on my windows machine using given steps .

$ git clone https://github.com/microsoft/BotFramework-Composer.git
$ cd BotFramework-Composer
$ cd Composer // switch to Composer folder
$ yarn install // install dependencies
$ yarn build // build extensions and libs
$ yarn startall // start client and server at the same time

I am facing error Error: spawnSync C:\windows\system32\cmd.exe ENOBUFS.

I checked and accessed C:\windows\system32\cmd.exe location and there is no issue .

Could you please let me know the ways I can resolve this issue please

**Comment by rudrasingh21** [comment]
it shows version V1.0.1 when i run this on http://localhost:3000/home

**Comment by hibrenda** [comment]
@liweitian could you have a look ?

**Comment by rudrasingh21** [comment]
Could you please help on this?

**Comment by liweitian** [comment]
> Could you please help on this?

Could paste everything after you type ”yarn startall“ showed on your terminal? It probably an environment setting issue on your PC.

**Comment by rudrasingh21** [comment]
config the PATH = C:\Windows\System32\cmd.exe

present .

”yarn startall“ showed on your terminal:-

PS D:\Study\BOT\BotFramework-Composer-master\composer> yarn startall
yarn run v1.22.4
$ yarn start
$ cross-env NODE_ENV=production PORT=3000 yarn start:server
$ yarn workspace @bfc/server start
$ node build/init.js
express-session deprecated undefined resave option; provide resave option build\server.js:69:17
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option build\server.js:69:17
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.


Composer now running at:

http://localhost:3000

**Comment by rudrasingh21** [comment]
@liweitian  : Could you suggest please.

**Comment by liweitian** [comment]
> @liweitian : Could you suggest please.

@rudrasingh21 I think the problem is solved. Let me know if you meet some other issues.

**Comment by rudrasingh21** [comment]
@liweitian  : no , I just shared logs with you . I am facing the same issue which accessing http://localhost:3000.

In the logs , there is no error message and tha PATH also has this entry PATH = C:\Windows\System32\cmd.exe

but still i am getting the same error.

**Comment by liweitian** [comment]
> @liweitian : no , I just shared logs with you . I am facing the same issue while accessing http://localhost:3000.
> 
> In the logs , there is no error message and tha PATH also has this entry PATH = C:\Windows\System32\cmd.exe
> 
> but still i am getting the same error.

The error is showed in a pop up once you connect localhost rather than the terminal? Sry, I misunderstood that. I will check it.

**Comment by rudrasingh21** [comment]
@liweitian  Right . It comes as a POP up once I click on start BOT.

and the logs from powershell , where i run command "yarn startall" gives me below logs which I have shared with you already.

”yarn startall“ showed on your terminal:-

PS D:\Study\BOT\BotFramework-Composer-master\composer> yarn startall
yarn run v1.22.4
$ yarn start
$ cross-env NODE_ENV=production PORT=3000 yarn start:server
$ yarn workspace @bfc/server start
$ node build/init.js
express-session deprecated undefined resave option; provide resave option build\server.js:69:17
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option build\server.js:69:17
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.

Composer now running at:

http://localhost:3000

GET / 200 65.273 ms - 758
GET /api/projects/recent 200 69.964 ms - 487
GET /api/storages 200 2.989 ms - 130
GET /api/assets/projectTemplates 200 3.299 ms - -
GET /api/storages/default/blobs?path=C:%2FUsers%2FSeema 200 47.615 ms - -
PUT /api/projects/open 200 264.076 ms - -
GET /api/publish/98880.04818858053/status/default 200 24.261 ms - 32
PUT /api/projects/98880.04818858053/files/echobot-0.dialog 200 28.919 ms - 74
POST /api/publish/98880.04818858053/publish/default 400 8903.649 ms - 88
POST /api/publish/98880.04818858053/publish/default 400 5337.972 ms - 88


To tell you which http request returned this error , actually I have no idea how to debug this.

**Comment by liweitian** [comment]
@rudrasingh21 I finally understand your issue. Previously, I thought you cannot even start the web app. But actually it failed during publishing. Our code will spawn some children processes during publishing. The error means it run out of memory of buffer.
My colleague and I discussed on this issue. It should be problem on your local machine settings. But there are a lot of possible may cause this problem. I can only suggest you to try on them like
https://github.com/lerna/lerna/issues/479
https://github.com/lerna/lerna/pull/782
I saw some people solve this by reinstall Node. (Do not forget to delete the Node customer settings file before reinstall) Let me know if this can help or you solve this issue by doing any configuration. Thx!

**Comment by cwhitten** [comment]
@rudrasingh21 is self-hosting the Composer application from source a requirement? Can you use the installable desktop application instead?

**Comment by rudrasingh21** [comment]
Hey @cwhitten 

Yes I tried that too I am also facing some issue there which I reported 

https://github.com/microsoft/BotFramework-Composer/issues/3430

**Comment by rudrasingh21** [comment]
Installed VM on windows , and running it on ubuntu now..
