### ISSUE TITLE
Embed a property within a property/ Access JSON elements dynamically

### ISSUE THREAD

**Issue by mweldingwala** [microsoft/BotFramework-Composer#3433]
Could I embed a property within a property. For example, consider that my bot is calling a bitcoin to currency change API which returns a JSON of the type in the picture:

<img width="1071" alt="Screen Shot 2020-06-17 at 5 32 14 PM" src="https://user-images.githubusercontent.com/63029134/85006075-4486aa00-b11f-11ea-80f7-f01f3eb0cad0.png">

 Let us assume that I saved this response in dialog.api_response. Now Json is in dialog.api_response.content.

  Now if the user is to input: “USD”, (which I will save in user.convert_to) I would do dialog.api_response.content.USD.last

But what if the user asks for AUD, or INR, or BRL? I would have to have an if statement for each one of the conversions!  Is there something like ${dialog.api_response.content.${user.convert_to}.last} ? Otherwise I would just find myself hardcoding every singly currency.

**Comment by Danieladu** [comment]
Try `dialog.api_response.content[user.convert_to].last`
or `getProperty(dialog.api_response.content, user.convert_to).last`

**Comment by hibrenda** [comment]
if this does not work, feel free to open.
