### ISSUE TITLE
Composer User experience - Bot publishing

### ISSUE THREAD

**Issue by SattaRavi** [microsoft/BotFramework-Composer#3438]
HI,

I am using the composer built from source on a windows 10 computer.

i see the composer UI different across documentation examples, screen snips posted by others here on the github issues.

for e.g.

In the case of publishing the bot app built by the composer. The documentation [here](https://docs.microsoft.com/en-us/composer/how-to-publish-bot) explains how to use provisionComposer.js to provision the required resources on Azure. And goes on to explain how to add a publish profile (json) to push it to azure.

Both of which are not doable in my scenario since the only files i see under

>C:\Users\UserName\Documents\Composer\BotName\scripts

are

* create.ps1
* deploy.ps1

And no provision to add publish profile, all it shows is recommendation to run couple of PowerShell commands. (does not cover the pre reqs like az cli must be installed) 

does not allow me to deploy the bot to an existing resource group or bot application. (name requirements on the RG and bot name)

![image](https://user-images.githubusercontent.com/6824787/85081623-4ed99000-b181-11ea-9f41-fad97f87ba04.png)

![image](https://user-images.githubusercontent.com/6824787/85081751-babbf880-b181-11ea-8023-728b2ca62045.png)

### Even if i were to use the create.ps1 to create new resources it goes onto deploy the whole suite including resources that were not used in the project like the below
* LUIS (not used in the project), 
* cosmos(not used in the project)

![image](https://user-images.githubusercontent.com/6824787/85082179-fa371480-b182-11ea-869c-d559a1b02e57.png)

**Comment by zxyanliu** [comment]
@SattaRavi Thanks for your feedback. Can you please tell us what Composer version are you using? 
Our docs are currently aligned with [Electron version 1.0.1](https://github.com/microsoft/BotFramework-Composer/releases) and might be slightly behind the most recent [master](https://github.com/microsoft/BotFramework-Composer) branch.

**Comment by SattaRavi** [comment]
Hi @zxyanliu 

i am building from source code, using the steps listed [here](https://docs.microsoft.com/en-us/composer/setup-yarn#installation-instructions).

And i believe when i **yarn startall** it always checks for version updates and makes sure it on the latest version.

**Comment by SattaRavi** [comment]
Also while trying to make updates and pushing the chnages to the bot does not work too.

![image](https://user-images.githubusercontent.com/6824787/85174344-07f3a500-b22a-11ea-9299-390030cfa3d0.png)

script shows publish success, but cannot see any recent deployments made on the RG or the resource.

**Comment by SattaRavi** [comment]
Ok @zxyanliu 

i guess i understand the issue now, most of the documentation is based off of the Composer client app installed (electron app) which does not apply to the build from source code composer.

Can we please publish a feature support matrix between build from source vs the composer client app(electron).

And also calling it out the documentation, like "Applies only to Composer Electron App or Applies only to built from source"

**Comment by cwhitten** [comment]
Hi @SattaRavi 

The Composer desktop application and web application are the same--there is no matrix of support in terms of features or functionality.

Looking at your screenshots - your version of the application seemed well out of date. We've deprecated the screens you showed entirely.

I hope this helps. I'll close this issue for now. Thank you for trying Composer.
