### ISSUE TITLE
Bot publish issue

### ISSUE THREAD

**Issue by shashank912** [microsoft/BotFramework-Composer#3439]
Could I please know the new process to publish the Bot created via Composer .
I was able to publish the Bot to Azure portal using access token and Microsoft app Id and Password but when I tried testing in web chat it failed
Can I please get help on this

**Comment by hibrenda** [comment]
@shashank912 Just FYI: how to publish bot through composer.
https://docs.microsoft.com/en-us/composer/how-to-publish-bot. 
If you hit any issues after publish, could you share the screenshot ?

**Comment by shashank912** [comment]
I have configured my composer with Luis and QnA and have published it in azure using below steps but I am unable to test it .

Is this because the Bot in azure is not configured with QnA?

Regards
Shashank

**Comment by hibrenda** [comment]
composer support QnA to be called as an action , you need to publish your QnA and provide knowledgeBaseID , hostname and Password in setting. You can reference https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot . More deep integration with QnA is on the way.

**Comment by shashank912** [comment]
are u talking about I need to add in the configuration settings of azure portal?

**Comment by shashank912** [comment]
in composer I am able to add QnA and when I am testing with emulator it is able to connect and give me the desired result.Issue is post publish to azure

**Comment by shashank912** [comment]
Could any one please help
![image](https://user-images.githubusercontent.com/60638224/85259283-66b55a80-b486-11ea-92ff-ab6cd108d38a.png)

**Comment by shashank912** [comment]
Could anyone please help in this

**Comment by hibrenda** [comment]
could you provide the error info ? if everything works fine in local, it should be worked in azure as well. 
So please make sure the provisioning steps are all correct. Then no failures for deploy process. In that case, what failure you are hitting during the test in webchat ?

**Comment by shashank912** [comment]
Resource/BotFrameworkIFrame/BotFrameworkIFrameBlade 29 BotFrameworkIFrameBlade: Failed to check bot endpoint _errorData: message: Cannot read property 'requestedDataType' of undefined
stack: TypeError: Cannot read property 'requestedDataType' of undefined
    at https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:105:5569
    at r (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:26:396)
    at Object.h [as cancelOnDispose] (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:26:877)
    at t._fetchData (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:105:5412)
    at f (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:105:3606)

_sourceErrorLevel: undefined
baseTypes: ["MsPortalFx.Errors.FetchDataError","MsPortalFx.Errors.DataError","MsPortalFx.Errors.Error"]
code: undefined
data: undefined
dataSetName: BotEndpointInfo:DataCache:2:3
errorLevel: 2
extension: Microsoft_Azure_BotService
handled: undefined
innerErrors: []
message: 
name: Error
source: BotEndpointInfo:DataCache:2:3
stack: Error
    at t.r (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:19:790)
    at t (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:19:1563)
    at new t (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:19:1736)
    at wt (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:105:680)
    at https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:105:6525
    at o (https://portal.azure.com/Content/Dynamic/P8kXagqyUZue.js:4:72)
    at https://portal.azure.com/Content/Dynamic/P8kXagqyUZue.js:4:5711
timestamp: 140290.20999989007
type: MsPortalFx.Errors.FetchDataError

r @ sH6na45YNsUu.js:10
sH6na45YNsUu.js:10 [Microsoft_Azure_BotService]  12:45:32 PM MsPortalFx.Base.Diagnostics.ErrorReporter 1 MsPortalFx.Base.Diagnostics.ErrorReporter: _errorData: message: Cannot read property 'requestedDataType' of undefined
stack: TypeError: Cannot read property 'requestedDataType' of undefined
    at https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:105:5569
    at r (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:26:396)
    at Object.h [as cancelOnDispose] (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:26:877)
    at t._fetchData (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:105:5412)
    at f (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:105:3606)

_sourceErrorLevel: undefined
baseTypes: ["MsPortalFx.Errors.FetchDataError","MsPortalFx.Errors.DataError","MsPortalFx.Errors.Error"]
code: undefined
data: undefined
dataSetName: BotEndpointInfo:DataCache:2:3
errorLevel: 2
extension: Microsoft_Azure_BotService
handled: undefined
innerErrors: []
message: 
name: Error
source: BotEndpointInfo:DataCache:2:3
stack: Error
    at t.r (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:19:790)
    at t (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:19:1563)
    at new t (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:19:1736)
    at wt (https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:105:680)
    at https://portal.azure.com/Content/Dynamic/sH6na45YNsUu.js:105:6525
    at o (https://portal.azure.com/Content/Dynamic/P8kXagqyUZue.js:4:72)
    at https://portal.azure.com/Content/Dynamic/P8kXagqyUZue.js:4:5711
timestamp: 140290.20999989007
type: MsPortalFx.Errors.FetchDataError

r @ sH6na45YNsUu.js:10
logger.ts:22 WebChatController: Starting to listen to Azure cross frame messages
dev.botframework.com/az/webchat?id=WCB-EUW1-XLNCARE-ORDERMGMT-01-NP&clientOptimizations=undefined&l=en.en-us&trustedAuthority=https%3A%2F%2Fportal.azure.com&shellVersion=undefined#0ba4848f222546eb9a6cfe52af300285:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://bot-framework.azureedge.net/fonts/SegoeUI-Normal/latest.woff
logger.ts:22 WebChatController: Got Azure Extension version: 1.0
logger.ts:22 WebChatController: Azure sent us Authentication tokens - Refreshing.
logger.ts:22 WebChatController: Got new bot status from Azure: error
Logging.ts:206 Failed to initialize AppInsights JS SDK: Cannot load Application Insights SDK, no instrumentationKey was provided.
r.warnToConsole @ ai.0.js:1
/#@Philips.onmicrosoft.com/resource/subscriptions/d7c254ec-1154-48de-9ad3-9681c4b104fa/resourceGroups/AZ19D1-XLNCARE-OrderMgmt/providers/Microsoft.BotService/botServices/WCB-EUW1-XLNCARE-ORDERMGMT-01-NP/test:1 A cookie associated with a resource at http://dev.botframework.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
logger.ts:22 WebChatController: Getting signed in user.
sH6na45YNsUu.js:10 [Microsoft_Azure_BotService]  12:45:35 PM MsPortalFx/Base/Base.Net 1 Base.Net: readyState: 4
responseText: 
status: 500
statusText: error
 Object
r @ sH6na45YNsUu.js:10
logger.ts:22 WebChatController: Got authenticated user.
logger.ts:22 WebChatController: Got WebChat token
dev.botframework.com/az/webchat?id=WCB-EUW1-XLNCARE-ORDERMGMT-01-NP&clientOptimizations=undefined&l=en.en-us&trustedAuthority=https%3A%2F%2Fportal.azure.com&shellVersion=undefined#0ba4848f222546eb9a6cfe52af300285:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://bot-framework.azureedge.net/fonts/SegoeUI-Semibold/latest.woff
dev.botframework.com/az/webchat?id=WCB-EUW1-XLNCARE-ORDERMGMT-01-NP&clientOptimizations=undefined&l=en.en-us&trustedAuthority=https%3A%2F%2Fportal.azure.com&shellVersion=undefined#0ba4848f222546eb9a6cfe52af300285:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://bot-framework.azureedge.net/fonts/Fabric%20MDL2/FabMDL2.3.09.woff
gemini?b=WCB-EUW1-XLNCARE-ORDERMGMT-01-NP&t=eyJhbGciOiJSUzI1NiIsImtpZCI6InlBVnQ5UHFpNkVyeHZlQktOVndzbURnVkMwayIsIng1dCI6InlBVnQ5UHFpNkVyeHZlQktOVndzbURnVkMwayIsInR5cCI6IkpXVCJ9.eyJib3QiOiJXQ0ItRVVXMS1YTE5DQVJFLU9SREVSTUdNVC0wMS1OUCIsImNvbnYiOiI1OVNZQ0hXdWgxOThEZmd3YWFwM2tkLWMiLCJ1c2VyIjoiYTRjNTRiNTEtNDVjNC00ODVmLWFmMDgtNWY5NzhjZGM5OWNmIiwib3JpZ2luIjoiaHR0cHM6Ly93ZWJjaGF0LmJvdGZyYW1ld29yay5jb20vIiwibmJmIjoxNTkyODEwMTM3LCJleHAiOjE1OTI4MTM3MzcsImlzcyI6Imh0dHBzOi8vZGV2LmJvdGZyYW1ld29yay5jb20vIiwiYXVkIjoiaHR0cHM6Ly93ZWJjaGF0LmJvdGZyYW1ld29yay5jb20vIn0.VaxRZIZgjpnkYOd6iihoNWkdZpjjPPRh_Po2maewlEI8tqr-rSRu_SR0Y_Cv5pvp_LAR1MWE1MhyWyFHYbB87A3nizCmyt3ryr9OKypV_uO4vixqouWBxlFChwVeQDkTbiAHPRgWWubaFj48qU_V1YU38vw3FFANiQLNTFDNmDlP4VkJK2zSNQ-B4YJzRRKLRhDfmfFhMvRI2ZkNdpnKK2gmUAfzG2eE12lm5KQ-eTjEQIDLKM_cnh3WI4poQEAymhpU8q30kq28MiVSIgs_l6WcFDO43epdDswcsd36t0gBRAzYXDrbaky8XCdK1gjBnOu9WYOP_aGNrT564zli7A&l=en.en-us&username=You:2 Web Chat: Selecting version "default" -> "4" -> "4.9" -> "4.9.0".
DevTools failed to load SourceMap: Could not parse content for https://dev.botframework.com/Client/Libs/jquery.min.map: Unexpected token < in JSON at position 2
DevTools failed to load SourceMap: Could not load content for https://bot-framework.azureedge.net/libs/underscore-min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by shashank912** [comment]
unable to send message

**Comment by sandeepreddy0987** [comment]
Hi, Can someone tell me how to get Apppassword while publishing the bot to azure?
![image](https://user-images.githubusercontent.com/33647692/85356122-69866e80-b4cb-11ea-9d0f-defedbbb0aa2.png)

**Comment by shashank912** [comment]
In configuration

**Comment by sandeepreddy0987** [comment]
Hi Shashank,
Do i need to provide app id and password manually or Can you please give me steps to retrieve that?

**Comment by shashank912** [comment]
Microsoft app id and password right?
u need to go to app services in azure portal-->Choose the service --> Once opened In that there is a configuration tab in left there u will get it

**Comment by sandeepreddy0987** [comment]
oh!! do we need to create web bot in azure portal before deploying to azure?

**Comment by shashank912** [comment]
yes

**Comment by sandeepreddy0987** [comment]
Hi @shashank912 
I am still facing an error. Can you please guide me in publishing my bot to azure?
I can share my screen if required

**Comment by shashank912** [comment]
where are u publishing from

**Comment by sandeepreddy0987** [comment]
I am following this link:
https://docs.microsoft.com/en-us/composer/how-to-publish-bot

**Comment by sandeepreddy0987** [comment]
But it is giving me above error while running node composerprovision.js ...... command

**Comment by shashank912** [comment]
no nothing doing in publish settings in composer u will have to fill certain details once  u select publish to web.There u have to give ur access token 

to get access token u will have to run this command az account get-access-token in command prompt once u have installed azure cli

Details to give is account number and microsoft app id and password and host name at last

**Comment by sandeepreddy0987** [comment]
Can you give me the screenshot of something you did and it worked?
