### ISSUE TITLE
(Post-Deployment) Conversation Log Data Quality Issues

### ISSUE THREAD

**Issue by ku222** [microsoft/BotFramework-Composer#3441]
Hi there,
Have a deployed Composer bot on Azure through the CLI shell, already deployed and hooked up to Cosmos DB, Blob Storage, etc.

Most logging + data collection is working fine, but am running into two issues:

1. Actual words typed by the user (transcripts) are being dumped in Blob Storage rather than in Cosmos DB with the rest of the supporting conversation log info. Is there any way to change where transcripts go to by default? Don't want to have to programmatically match them across the two storage instances.

2. All dialog logs on Cosmos DB are unhelpfully just called "(<mybot'sname>).dialog" rather than any unique identifier or the plain english names that we've given in our local Composer setup. How do I fix this?

**Comment by hibrenda** [comment]
@zidaneymar could you comment ?

**Comment by zidaneymar** [comment]
issue 1: Actually we don't provide the transcript logger which supports cosmos db, it needs to implement the corresponding middleware in runtime.
issue2: I need further investigation on this, currently the state looks like this:
![image](https://user-images.githubusercontent.com/9328933/85263525-dedd4980-b4a1-11ea-9c7f-9683cecdfffc.png)
I think the state of a dialog should use the dialog name as id, I'm not sure what kind of unique identifier you configure, @ku222 Could you please provide the screenshot about this? Thanks

**Comment by ku222** [comment]
@zidaneymar - noted on issue 1 - guess we'll have to implement that ourselves.

Issue 2: our Cosmos DB logs look exactly like yours - the only named dialog ID is the **root dialog** file of our bot ("new_bot.dialog" in our case). 

![image](https://user-images.githubusercontent.com/44293915/85266072-38765180-b46b-11ea-9253-f63861f8e06d.png)

However, all of our actual dialogs in the new_bot > dialogs folder have their own .dialog files. But none of the **names** of these individual dialogs get picked up by Cosmos DB (they are simply logged as **id: "AdaptiveDialog"**. 

![image](https://user-images.githubusercontent.com/44293915/85266182-665b9600-b46b-11ea-9d16-a7375f0ea0c9.png)

**Comment by zidaneymar** [comment]
Need more investigation on the cosmos db logging middleware.

**Comment by zidaneymar** [comment]
I think the 'name' you mentioned is the configuration under '$designer' section, actually this field doesn't influence the state logging.
![image](https://user-images.githubusercontent.com/9328933/89506122-37239d00-d7fd-11ea-8667-aaf18e1bc3fa.png)

**Comment by peterinnesmsft** [comment]
We will look into this as part of our upcoming R11 release.

**Comment by zidaneymar** [comment]
It seems this issue has been resolved in the latest sdk (Composer App v1.1.1).

Here are the concrete test steps:
1. Create a dialog named Test Dialog.
2. Use a trigger to begin this 'Test Dialog'
3. Ask a simple question in 'Test Dialog'

Navigate to the cosmos db data explorer:
![image](https://user-images.githubusercontent.com/9328933/92215639-b0c7ad00-eec7-11ea-8f3c-97ef3c00c31c.png)


The sub dialog has its own unique name not the "AdaptvieDialog".

**Comment by luhan2017** [comment]
@ku222，Close this issue since we verified it is already resolved, please reopen it if necessary.
