### ISSUE TITLE
Bot does not initiate conversation through Greeting activity on Web App

### ISSUE THREAD

**Issue by JalalUddin7** [microsoft/BotFramework-Composer#3442]
## Describe the bug

During testing, the bot functioned well. Upon loading the bot on the Emulator, the first welcome message I included is triggered. However, after I published the bot to the web, the bot does not initiate conversation. Only after I input something, does the bot trigger the welcome message - which is not intuitive at all.

## Version

Versions:
BFC: V1.0.1
8.0.2: Electron distribution
80.0.3987.86: Chrome

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to https://nhsmvp-playground.azurewebsites.net/ - 
2. Type in anything.
3. Press enter
4. See welcome message.

## Expected behavior

As soon as the website loads, the welcome message should appear right away, not after entering some text. When I run the bot on the emulator, the welcome message is automatically triggered.

**Comment by tdurnford** [comment]
@JalalUddin7 There are a couple of nuances to the Welcome Message in Web Chat that depend on the user id and how you generate the Direct Line token. Please take a look at the [Web Chat  Welcome Message](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/WELCOME_MESSAGE.md) for more details on how to configure the request correctly.
