### ISSUE TITLE
Something went wrong with connecting bot runtime

### ISSUE THREAD

**Issue by bartbilliet** [microsoft/BotFramework-Composer#3444]
## Describe the bug

Starting the sample EchoBot bot produces error **Sorry, something went wrong with connecting bot runtime**. 

## Version

![image](https://user-images.githubusercontent.com/23324404/85206850-330eef00-b325-11ea-9ee2-ae399862a594.png)

The issue is producing in a nightly build version.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open any of the samples that come with Composer (in my case 'EchoBot')
2. Click **Start Bot**
3. The error is produced as seen in the screenshot. 

## Expected behavior

The bot should load and start running.

## Screenshots

![image](https://user-images.githubusercontent.com/23324404/85206809-cbf13a80-b324-11ea-873f-6c5708c9e6d3.png)

## Additional context

The root cause might be similar to the other issue I filed regarding bot runtime: https://github.com/microsoft/BotFramework-Composer/issues/3443. Although since both produce in different areas and when performing different actions, I logged it as separate issues, just in case they are unrelated after all.

**Comment by manashty** [comment]
I have the same issues and it happens when update the nightly update. It was fixed once I installed the main version again but not that does not help either. The following issue also occurs: #3443 .

**Comment by manashty** [comment]
I just fixed it by Uninstalling the composer from C:\Users\<user>\AppData\Local\Programs\Bot Framework Composer and running the installer of version 1.0.0.1093 and installing it on local user.

**Comment by bartbilliet** [comment]
Downgrading to the latest stable does indeed work around the problem temporary - as long as in settings you deactivate the nightly builds flag.

**Comment by VanyLaw** [comment]
Hi @manashty this issue was fixed in https://github.com/microsoft/BotFramework-Composer/pull/3479
