### ISSUE TITLE
Unable to Test Bot, Keep reloading

### ISSUE THREAD

**Issue by bushdav** [microsoft/BotFramework-Composer#3445]
Can't Test Bot , it keeps reloading over and over

**Comment by hibrenda** [comment]
@bushdav Could you share more info ? eg. the root level directory for dialog files ? 
could you check whether you hit similar issue to https://github.com/microsoft/BotFramework-Composer/issues/3428

**Comment by bushdav** [comment]
It has worked for me After, thanks for the help.
For any documentation about the Bot framework, please share with me.

Regards,
David B.

**Comment by hibrenda** [comment]
so should I close this issue ?

**Comment by bushdav** [comment]
Yes
