### ISSUE TITLE
Tenant Id publishing script must be non optional.

### ISSUE THREAD

**Issue by rubit0** [microsoft/BotFramework-Composer#3446]
## Describe the bug

Prerequisite: The used Azure Account is member of several organizations.

When following the [Create Azure resources](https://docs.microsoft.com/de-de/composer/how-to-publish-bot#create-azure-resources), at step 3 you will get an error about "User not found".

## Version

v 1.0.1

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Follow the [Publish a bot tutorial](https://docs.microsoft.com/de-de/composer/how-to-publish-bot) and at section [Create Azure resources](https://docs.microsoft.com/de-de/composer/how-to-publish-bot#create-azure-resources) where you run the command in step 3 an error about "User not found" will happen.

## Expected behavior

The azure resource should be created without error.

## Possible solution

There are several possible solutions:

A. Mention in the bot publishing tutorial to the user to provide a tenant id in case if it is member of several organizations.

B. The Azure Tenant Id is a required parameter for the build script.

C. The build script checks for the "User not found" error and prompts to specify a tenant id.

**Comment by hibrenda** [comment]
@zxyanliu to be aware of the tenant id updates.

**Comment by luhan2017** [comment]
@rubit0 , we had a fix for this here #3359, which will be available soon in the next patch release. In this PR, we switched to another API to get the tenant id which is bound to this subscription.

**Comment by zxyanliu** [comment]
@luhan2017 Let's sync offline for any updates I should make in the [doc](https://docs.microsoft.com/en-us/composer/how-to-publish-bot).

**Comment by zxyanliu** [comment]
@luhan2017 Do I need to do any updates in the docs? I think this issue was addressed through #3359, which was merged.

**Comment by luhan2017** [comment]
@zxyanliu , we don't need to update the doc, the PR is just fixing a bug and there is no change on user scenario.
