### ISSUE TITLE
Flow Editor zoom in / zoom out

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#3449]
In Flow Edtior, the canvas could be zoomed in / zoomed out by either keyboard shortcuts or a minimap.

1. Use Ctrl + Mouse wheel to zoom in / zoom out;
2. Use Mouse Right Click + drag to move the focus area.

**Comment by yeze322** [comment]
@sangwoohaan @DesignPolice guys do we have a UX design for that?
What's the expected behavior to control the zoom of the action canvas?
Shall we also provide a way to focus on different area such as mouse drag?

**Comment by sangwoohaan** [comment]
I don't think we are ready to move forward with this feature yet.

**Comment by bradrlaw** [comment]
@sangwoohaan Another option could be using the design we have in viso, powerpoint, etc...  Leave the area scrollable as it is now but have a slider for the zoom:

<img width="223" alt="Screen Shot 2020-08-03 at 2 32 49 AM" src="https://user-images.githubusercontent.com/10415799/89152823-c72dc200-d531-11ea-9dae-40d50d556489.png">

As I am building more complex flows this would be very useful.  With decision flows I spend quite a bit of time scrolling left / right.  Having the separate zoom allows for quicker navigation while still keeping the property sheet easy to read.  Could also have buttons to fit the flow to the window or have a full screen view option as well.

**Comment by mareekuh** [comment]
@yeze322 please work with Vivek on this.
@vivekkshankar  Please connect with Thad if there are any updates to what is currently in PVA. If not, enable the following (functionality & look and feel)

![Screen Shot 2020-09-14 at 2 40 34 PM](https://user-images.githubusercontent.com/48503434/93141251-b88e0b00-f698-11ea-969c-719a884abfdb.png)
![Screen Shot 2020-09-14 at 2 40 28 PM](https://user-images.githubusercontent.com/48503434/93141255-b926a180-f698-11ea-9e00-f5dd2c07c4c1.png)
![Screen Shot 2020-09-14 at 2 40 16 PM](https://user-images.githubusercontent.com/48503434/93141258-b9bf3800-f698-11ea-9838-952214d06e71.png)

**Comment by DesignPolice** [comment]
Always nice to be CC’d on things – I can help til Thursday. 😊
m

**Comment by sangwoohaan** [comment]
It's a ghost!!!

**Comment by yeze322** [comment]
cc @alanlong9278

**Comment by vivekkshankar** [comment]
I took a stab at defining this: https://www.figma.com/file/deFhMPBnRWxTYiYDYqYxrc/Composer-Vivek?node-id=8457%3A0

@mareekuh I will connect with Thad but I do feel given that flows in composer tend to be more complex, I feel we need to invest in introducing semantic zoom (to ensure readability at smaller sizes) and not just physical zoom (Like what PVA does).
