### ISSUE TITLE
Flow Editor Action nodes UI refresh

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#3450]
Are they finialized design?

[by Marc] https://www.figma.com/file/Ux0vucOvaLL2xH22WpFgV65X/MarcB_Composer-UI?node-id=3270%3A230
[by Sangwoo] https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19-?node-id=3540%3A621

![image](https://user-images.githubusercontent.com/8528761/85278327-641f2900-b4b7-11ea-81f6-9905fb2abe8a.png)
![image](https://user-images.githubusercontent.com/8528761/85278627-c546fc80-b4b7-11ea-91c6-80bdca481f84.png)

**Comment by zxyanliu** [comment]
@yeze322 Sorry, my finger just slipped. I did not mean it. : -)

**Comment by cwhitten** [comment]
@yeze322 lets hold off on these designs for now

**Comment by cwhitten** [comment]
Closing this, will re-create when direction & design is more crisp
