### ISSUE TITLE
multiple choice prompt is not working in new composer

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-Composer#3451]
[MyBot_PrviewComposer.zip](https://github.com/microsoft/BotFramework-Composer/files/4813792/MyBot_PrviewComposer.zip)
[MybotLuis_NewComposer.zip](https://github.com/microsoft/BotFramework-Composer/files/4813795/MybotLuis_NewComposer.zip)

Hi,
I had created sample bot(with multiple choice prompt) in preview composer and it was working fine when tested. I modified the bot as per the new composer project structure. But when tested in new composer multiple choice prompt not working as expected. After clicking on the button bot is not executing further logic.I have attached the sample project for the reference please give me some solution.

Thanks......

**Comment by hibrenda** [comment]
Hi @madbeher This is introduced by old version of the dialog file.
We changed the bot structure and naming strategy for LU/LG files in early this year.
I checked your sample bot. you need to manually update your dialog file as below.
click showcode for dialog file and update corresponding LG.
![image](https://user-images.githubusercontent.com/43408889/85356024-7b562900-b540-11ea-9c51-81abbcf63a96.png)

**Comment by hibrenda** [comment]
close it . if you hit issues again, feel free to open.
