### ISSUE TITLE
Unable to provision the bot using provisioncomposer.js command

### ISSUE THREAD

**Issue by sandeepreddy0987** [microsoft/BotFramework-Composer#3460]
I am unable to provision the bot. 1)Can someone provide where to find the App password? 
2) Do we need to create a web bot in azure before publishing to azure?
![image](https://user-images.githubusercontent.com/33647692/85358571-4f4f8f00-b4d1-11ea-9887-0d1abebf83c3.png)

**Comment by luhan2017** [comment]
@sandeepreddy0987 , what version of Composer are you using? we had a fix on this #3359 , could you try to use the latest master or you can wait to the next release of the Composer Electron which will be available soon.

**Comment by sandeepreddy0987** [comment]
v1.0.1 is my botcomposer version

**Comment by luhan2017** [comment]
@sandeepreddy0987 , this is a known issue in the v1.0.1, you can mitigate this by referring to this comment to add tenantId as a parameter for provision, https://github.com/microsoft/BotFramework-Composer/issues/3313#issuecomment-639235003, or you can wait for v1.0.2 release which will be available soon.

**Comment by triciasinclair** [comment]
Hi @luhan2017 will this also resolve the below issue?
I've tried the workarount to also include the tenantid but with no success...

{
  "error": {
    "code": "InvalidBotData",
    "message": "Bot is not valid. Errors: The bot name is already registered to another bot application..  See https://aka.ms/bot-requirements for detailed requirements."
  }
}

![error](https://user-images.githubusercontent.com/45111232/86532649-966f5400-bec3-11ea-8a03-123d517ecd6b.JPG)

This was identified as a related issue in #3324 and resolved together. I've tried the workaround you reported above - include the tenantid but with no success..

**Comment by luhan2017** [comment]
@triciasinclair , according to the error message, you already passed the tenant id part, it should fail at the web app provision part, could you try to update your bot name, it looks like you are using an existing bot name which cause the provision failure.

**Comment by luhan2017** [comment]
@triciasinclair @sandeepreddy0987 , is this issue resolved in your side?

**Comment by sandeepreddy0987** [comment]
Resolved. Thank you.
