### ISSUE TITLE
QnA all up view

### ISSUE THREAD

**Issue by liweitian** [microsoft/BotFramework-Composer#3463]
implment all up view . https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-%2F-UI-library?node-id=313%3A15006

Support inline QnA CRUD

QnA errors notification

**Comment by mareekuh** [comment]
@hibrenda and @liweitian  - is it possible to do a quick recording of the QnA experience. Would like to send to people in ABS, VA & solutions and to Lilli so they know QnA is very close to being natively available in Composer

**Comment by liweitian** [comment]
@mareekuh Sure. Will try to apply all changes we talked last Thursday then record it.

**Comment by luhan2017** [comment]
@mareekuh I upload the video in the composer channel. https://microsoft.sharepoint.com/:v:/t/ConversationalAI785/EWdvE0DhKJVPqAJxcVnIWPYBD3Fvpi2Y52-SpWgjZmDHgQ?e=Kezylm
