### ISSUE TITLE
Multi Bot Management Prototype

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#3466]
To decide on an approach for dealing with opening multiple bots inside a single composer instance we are investing in a prototype. This ticket covers both engineering and design work to land a prototype that can be used as an accelerator for our Multi Bot management solution

## Describe the solution you'd like
The prototype is to build multi window approach where each bot is opened in a new Composer browser window but tied to a single Electron instance

## Describe alternatives you've considered
We have considered using a in app tabbed experience for opening multiple bots but feel the best solution at this time is the multi windows model that Microsoft Word follows

**Comment by cwhitten** [comment]
Marking the prototype as complete fo R10
