### ISSUE TITLE
There isn't a way to create a folder when picking location for a bot

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#3468]
## Describe the bug

I am creating a new bot, and want to pick the location.  I can browse folders, but I don't have a way of creating a new folder.

## Version

1.0.1

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. New bot
2. I put all of my bots in c:\scratch\bots.  I navigate there but there is no way to create folder for my bot.

## Expected behavior
There should be a NewFolder button which asks me for the folder name.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/85442937-8e1f2c80-b545-11ea-8217-9d07200b1cab.png)

**Comment by cwhitten** [comment]
tagging @sangwoohaan for investigation
