### ISSUE TITLE
CREATING PROJECT: not clear that the bot will be put in a sub-folder

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#3469]
## Describe the bug

I created a bot called "Foo" .  Since nothing in the UI gave any indication it would put it in a subfolder I put it in a folder called and put it in a sub folder **c:\scratch\bots\Foo**.  I was frustrated when the UI didn't tell me what it was going to do, because putting it in a shared folder could create a mess, so I put it in sub-folder.  Then I was doubly annoyed when I saw it had put it in c:\scratch\bots\foo\foo. 

## Version

1.01

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new bot
2. screen doesn't tell you what is going to happen, causing consternation.

## Expected behavior

UI should have text that says "Bot assets will be put in subfolder named {ProjectName}"

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/85444164-ec004400-b546-11ea-9928-11861d3ff379.png)

**Comment by cwhitten** [comment]
tagging @sangwoohaan for investigation

**Comment by mewa1024** [comment]
(@emivers8, although this bug is old, I think this still applies to the new creation flow)
