### ISSUE TITLE
Composer needs UI for defining None Intent utterances

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#3472]
## Describe the bug
For LUIS models to work you need utterances which are examples of "not the intent".  They are called the **None** intent and the UnknownIntent is based off of None Intent.  The current UI doesn't give you anyplace to do that.

## Version

1.01

## To Reproduce

1. Add UnknownIntent...there is no None intent defined and no UI for adding utterances.
2. Go to LU file, there is no None intent defined and no UI for adding None intent, you have to just "know" about it.

## Expected behavior

None intent to be supported explicitely in the UI.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/85451086-5b2d6680-b54e-11ea-998a-ab48fdbaf937.png)
![image](https://user-images.githubusercontent.com/17789481/85451134-6385a180-b54e-11ea-94ee-a518c34c82d7.png)

**Comment by cwhitten** [comment]
This is by design at the moment. @vishwacsena can you comment?

**Comment by vishwacsena** [comment]
I sync'd with @tomlm last night. If you need to add utterances to `None` intent, you can do so in the all up view for that specific dialog. In fact, you can add any number or intents directly in the all up view (including none or others). 

Note that a `None` intent is not required for adaptive dialogs to fire the `OnUnknownIntent` handler. This will fire if no triggers within your dialog handle the `IntentRecognized` event. Another way of stating this is adaptive dialog fires the `OnUnknownIntent` if no triggers fired on the recognition event.
