### ISSUE TITLE
Code hygiene: Prefer lambda arrow functions

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#3481]
See if eslint can enforce this rule. Update code to use lambda arrow functions

**Comment by GeoffCoxMSFT** [comment]
@beyackle - Do you want to take this one to add the the eslint rules?

**Comment by beyackle** [comment]
Will do. Am I right that you mean the standard `() => { return stuff; }` sort of lambda functions instead of the anonymous `function () { return stuff; }` stype?
