### ISSUE TITLE
Improvement: Abstract localization, remove inline string literals

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#3483]
Provide improved indirection for localization of strings.  Could even provide runtime localization switching (like theming) in the future.

**Comment by a-b-r-o-w-n** [comment]
@GeoffCoxMSFT let's connect before starting this work.

**Comment by GeoffCoxMSFT** [comment]
Ben will pick up the format-message standardization.
