### ISSUE TITLE
Debug/Fix HMR support

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#3486]
HMR seems to have some troubles with different pieces being changed
- Need a module.hot replacement at the index root
- Need to figure out constraints about extension being updated and HMR reloading

**Comment by hatpick** [comment]
@GeoffCoxMSFT

> HMR seems to have some troubles with different pieces being changed
> 
> * Need a module.hot replacement at the index root
What do you mean by the following?
> * Need to figure out constraints about extension being updated and HMR reloading
