### ISSUE TITLE
I have a bot with a single dialog and I can't seem to set "AutoEndDialog" property

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#3492]
## Describe the bug
There is no way for controlling the behavior of the root dialog?

## Version

1.0.1

## To Reproduce

1. create a dialog, try and set AutoEndDialog property.

## Expected behavior

To be able to set AutoEndDialog property to true or false.,

**Comment by cwhitten** [comment]
@tdurnford let's bring back autoEndDialog into the forms for an Adaptive Dialog as a boolean affordance

**Comment by benbrown** [comment]
autoEndDialog is set to true by default.

However, it does not appear that the root dialog ends properly as expected. For example, properties in the `dialog` scope do not expire between executions.

**Comment by benbrown** [comment]
This appears to be part of the problem:
https://github.com/microsoft/BotFramework-Composer/blob/master/runtime/dotnet/core/ComposerBot.cs#L57

**Comment by vishwacsena** [comment]
Per @tomlm @Stevenic @benbrown, we should
1. Expose ability to manage `autoEndDialog` property of adaptive dialog in form editor
2. remove the code in bot runtime that automatically sets autoEndDialog to false.
