### ISSUE TITLE
Toolbar design improvements

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#3494]
As the top toolbar gets crowded, I would take to take some time to improve the experience of it. Currently,
- Too many items in the design view.
- Discoverability issues have been brought up.

**Comment by mareekuh** [comment]
Marc has been working on this and will share his proposal today 6/25

**Comment by mareekuh** [comment]
Attached is the design for the toolbar in the Authoring canvas. We'll be applying a similar approach to the other pages.
https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-master-design-spec-UI-library?node-id=2968%3A27100
