### ISSUE TITLE
[MCS-DE-GO] Provide Composer UI for other languages (German)

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#3499]
As a Composer User I want to have the application available in my language.

@joaollq @sgellock @benbrown

**Comment by cwhitten** [comment]
Follow https://github.com/microsoft/BotFramework-Composer/pull/3398 for updates on this request.

**Comment by krusejan** [comment]
Hi @cwhitten , I think @goergenj request is to have the Composer User Interface available in another language (German). I am getting this requirement as well from more customers. If I understand correctly #3398 is about supporting multiple languages in a bot application itself, so the bot can interact with users in different languages, which is a different requirement.

Does Composer offer any capability today to extend/customize/change the language & texts in the Composer user interface?

**Comment by cwhitten** [comment]
Ah, I understand. Yes we’re working on localization of the app. I’ll update
this ticket when we have more details.

**Comment by goergenj** [comment]
@cwhitten It's now in 1.3.0 and can be closed? Or is there anything open from your side?

**Comment by cwhitten** [comment]
@goergenj yes this has shipped. Closing.
