### ISSUE TITLE
MicrosoftAppId and MicrosoftAppPassword in Composer Bot Settings breaks Test in Emulator

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotFramework-Composer#3504]
## Describe the bug
Adding MicrosoftAppId and MicrosoftAppPassword to Bot Settings breaks Test in Emulator with a 400: "The bot's Microsoft App ID or Microsoft App Password is incorrect."

## Version
latest

## Browser
- [x ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot channel registration and retrieve appid/password
2. Create an echo bot in Composer
3. Add appid/password to bot settings in composer
4. Restart the bot, and click 'test in emulator'
5. See error in emulator

## Expected behavior
Test in emulator should still function as expected while using appid/password in composer.

## Screenshots
![image](https://user-images.githubusercontent.com/11055362/85802243-696bb600-b6f9-11ea-9e84-5476e3c2e4a5.png)

**Comment by cwhitten** [comment]
Can someone from the team confirm this? This is a recent regression is so. @tdurnford ?

**Comment by tdurnford** [comment]
@EricDahlvang I'm not able to reproduce this.  Are you using Electron or the self-hosted version of Composer?

**Comment by EricDahlvang** [comment]
@tdurnford windows install v1.0.1

**Comment by EricDahlvang** [comment]
So, turns out i had the MicrosoftAppId and MicrosoftAppPassword flipped :(  

Unfortunately, i did this multiple times with multiple appid/passwords before filign this issue

In our samples, and templates, the MicrosoftAppId is above the MicrosoftAppPassword ... most people probably read these headings, while I just assume the top one is the appid.

I apologize for the mistake and noise.  Closing the issue.
