### ISSUE TITLE
Publish a bot (not loading on server)

### ISSUE THREAD

**Issue by epsy-me** [microsoft/BotFramework-Composer#3512]
Hello

## Version
Release: 1.0.1

Using template
`
{
"accessToken": "<your access token>",
"hostname": "<your web app name>",  
"settings": {
    "MicrosoftAppId": "<the appid of your bot channel registration>",
    "MicrosoftAppPassword": "<the app password of your bot channel registration>"
     }
}
`

Download never ends

![image](https://user-images.githubusercontent.com/67442521/85947969-a7b1e100-b956-11ea-9c30-d14daf5aeca6.png)

Sorry for my translation.

**Comment by bartbilliet** [comment]
Is the template presented the actual template you inserted when adding a publishing profile? I believe it seems to be missing a few parameters, for instance the `name` parameter which represents the resource group to deploy to, and the `CosmosDB` which is used to store the bot state. Also, did you provision the Azure resources before publishing? 
The following docs page helps explain how to provision the Azure resources upfront. The output of the provisioning command should give you the JSON template to use in the publishing profile:  https://docs.microsoft.com/en-us/composer/how-to-publish-bot

It is correct though that when adding the publishing profile, it seems there is no input validation. This causes the publishing profile to keep trying when publishing with invalid parameters, and there is no way to cancel the publishing.

**Comment by luhan2017** [comment]
@epsy-me , Did you run provisionCompose or you just leverage your existing services? And could you click the See log button and paste your log here? I want to understand what exact step it stuck at.

**Comment by igorpopryadukhin** [comment]
Use ProvisionCompose

**Comment by igorpopryadukhin** [comment]
I managed to publish the resource, but the bot does not work!

**Comment by luhan2017** [comment]
@igorpopryadukhin could you share more information about how it does not work? Could it because you are publishing a empty bot? did you try to test the bot locally and did it works well?

**Comment by igorpopryadukhin** [comment]
![image](https://user-images.githubusercontent.com/48174353/86070348-2147ed00-ba85-11ea-8bff-d7390d181400.png)

Sorry, I just entered the data incorrectly in this field.
I thought this field is filled randomly.
Now everything works and is published!

Thank you!
