### ISSUE TITLE
Adding Translation to Bot Middleware

### ISSUE THREAD

**Issue by ku222** [microsoft/BotFramework-Composer#3514]
Hi there,

Am trying to extend Bot Composer's .NET runtime scripts to add Translation to the Middleware pipeline as shown in https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/17.multilingual-bot.

I've lifted the **Translator** folder in it's entirety from https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/17.multilingual-bot/Translation and adapted all namespaces/references appropriately.

I made additions to the **Startup.cs** file in Composer's **runtime\dotnet\azurewebapp\Startup.cs**:
```csharp
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
using System;
using System.IO;
.....
using Microsoft.BotFramework.Composer.WebAppTemplates.Translation; // <--------------- NEW
....

// This method gets called by the runtime. Use this method to add services to the container.
public void ConfigureServices(IServiceCollection services) 
{
...
            // Create the Microsoft Translator responsible for making calls to the Cognitive Services translation service
            services.AddSingleton<MicrosoftTranslator>(); // <--------------- NEW
            // Create the Translation Middleware that will be added to the middleware pipeline in the AdapterWithErrorHandler
            services.AddSingleton<TranslationMiddleware>();  // <--------------- NEW
...

            var storage = ConfigureStorage(settings);

            services.AddSingleton(storage);
            var userState = new UserState(storage);
            var conversationState = new ConversationState(storage);
            services.AddSingleton(userState);
            services.AddSingleton(conversationState);

            // Add Translation
            var translator = new MicrosoftTranslator(this.Configuration); // <--------------- NEW
            var translationMiddleware = new TranslationMiddleware(translator, userState); // <--------------- NEW

            // Configure bot loading path
            var botDir = settings.Bot;
            var resourceExplorer = new ResourceExplorer().AddFolder(botDir);
            var rootDialog = GetRootDialog(botDir);

            var defaultLocale = Configuration.GetValue<string>("defaultLocale") ?? "en-us";

            services.AddSingleton(resourceExplorer);

            // Add translationMiddleware instance to Adapter
            services.AddSingleton<IBotFrameworkHttpAdapter, BotFrameworkHttpAdapter>((s) => GetBotAdapter(storage, settings, userState, conversationState, s, s.GetService<TelemetryInitializerMiddleware>(), translationMiddleware)); // <--------------- NEW

            // Guessing I should be passing translationMiddleware to this ComposerBot instance too??
            services.AddSingleton<IBot>(s =>
                new ComposerBot(
                    s.GetService<ConversationState>(),
                    s.GetService<UserState>(),
                    s.GetService<ResourceExplorer>(),
                    s.GetService<BotFrameworkClient>(),
                    s.GetService<SkillConversationIdFactoryBase>(),
                    s.GetService<IBotTelemetryClient>(),
                    // Add translationMiddleware here??
                    rootDialog,
                    defaultLocale));
}


```

I'm able to successfully deploy this Composer bot to Azure and interact with it (assuming this means the code above is so far working as intended), though the Translator instance isn't being used by the bot just yet. It's been difficult to lift + shift code from the C# bot github from this point onwards, as Composer's bot logic setup seems a little different.

Wondering if you can provide any guidance on this or give me a sense of just how much work is involved - how much more do I need to configure to add Translation to the bot?

Cheers

**Comment by luhan2017** [comment]
@ku222 , could you try to reference to the telemetryInitializerMiddleware here to add the translation middleware?
```
        public BotFrameworkHttpAdapter GetBotAdapter(IStorage storage, BotSettings settings, UserState userState, ConversationState conversationState, IServiceProvider s, TelemetryInitializerMiddleware telemetryInitializerMiddleware)
        {
            var adapter = new BotFrameworkHttpAdapter(new ConfigurationCredentialProvider(this.Configuration));

            adapter
              .UseStorage(storage)
              .UseBotState(userState, conversationState)
              .Use(new RegisterClassMiddleware<IConfiguration>(Configuration))
              .Use(telemetryInitializerMiddleware);
```

**Comment by ku222** [comment]
Hi @luhan2017, I had added the translationMiddleware to the GetBotAdapter arguments, and added a line to say .Use(translationMiddleware) to the adapter.

Is the below correct? 

```csharp
        // Added translationMiddleware instance to GetBotAdapter args
        public BotFrameworkHttpAdapter GetBotAdapter(IStorage storage, BotSettings settings, UserState userState, ConversationState conversationState, IServiceProvider s, TelemetryInitializerMiddleware telemetryInitializerMiddleware, TranslationMiddleware translationMiddleware) // <------------------- NEW
        {
            var adapter = new BotFrameworkHttpAdapter(new ConfigurationCredentialProvider(this.Configuration));

            adapter
              .UseStorage(storage)
              .UseBotState(userState, conversationState)
              .Use(new RegisterClassMiddleware<IConfiguration>(Configuration))
              .Use(translationMiddleware) // <------------------- NEW
              .Use(telemetryInitializerMiddleware);

            ...
        }
```
Thanks so much

**Comment by luhan2017** [comment]
@ku222 , yes, please let me know if it still not works :)

**Comment by ku222** [comment]
@luhan2017 still not working unfortunately
Bot is still able to deploy and function on Azure, but have just checked our translation resource and no API calls have appeared in the Usage Metrics report after trying to paste Spanish words into the Web Chat with the Bot.

**Comment by ku222** [comment]
@luhan2017 hoping your team might have a working implementation of a composer bot with Translation middleware that I can glance through the code of?

**Comment by luhan2017** [comment]
@ku222 , we don't have a sample for now, I will try to add one in composer and let you know when it is ready.

**Comment by ku222** [comment]
@luhan2017 fantastic - thank you! Will look out for it

**Comment by luhan2017** [comment]
@ku222 , I've take a look on this, and finally make it works. Here are some points you need to pay attention to:

1. update startup.cs
```
public BotFrameworkHttpAdapter GetBotAdapter(IStorage storage, BotSettings settings, UserState userState, ConversationState conversationState, IServiceProvider s, TelemetryInitializerMiddleware telemetryInitializerMiddleware, TranslationMiddleware translationMiddleware)  -------> here
        {
            var adapter = new BotFrameworkHttpAdapter(new ConfigurationCredentialProvider(this.Configuration));

            adapter
              .UseStorage(storage)
              .UseBotState(userState, conversationState)
              .Use(new RegisterClassMiddleware<IConfiguration>(Configuration))
              .Use(telemetryInitializerMiddleware)
              .Use(translationMiddleware);  --------> user tranlation middleware in the adapter.

           // Register telemetry client, initializers and middleware
            services.AddApplicationInsightsTelemetry(settings.ApplicationInsights.InstrumentationKey);
            services.AddSingleton<ITelemetryInitializer, OperationCorrelationTelemetryInitializer>();
            services.AddSingleton<ITelemetryInitializer, TelemetryBotIdInitializer>();
            services.AddSingleton<IBotTelemetryClient, BotTelemetryClient>();     
            services.AddSingleton<MicrosoftTranslator>(); -----------> register MicrosoftTranslator 
            services.AddSingleton<TranslationMiddleware>(); -------------> register TranslationMiddleware

            var translater = new MicrosoftTranslator(this.Configuration);  ------------> Initialize MicrosoftTranslator
            var translationMiddleware = new TranslationMiddleware(translater, userState); -> Initialize translationMiddleware

            services.AddSingleton<IBotFrameworkHttpAdapter, BotFrameworkHttpAdapter>((s) => GetBotAdapter(storage, settings, userState, conversationState, s, s.GetService<TelemetryInitializerMiddleware>(), s.GetService<TranslationMiddleware>())); -----> pass it in the GetBotAdapter
```

2. add TranslationKey in the appsettings.json
3. Set user.LanguagePreference="YourPreferenceValue" in your bot logic, the translation middleware is reading user.LanguagePreference to decide whether translation is needed
```
 private async Task<bool> ShouldTranslateAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
        {
            string userLanguage = await _languageStateProperty.GetAsync(turnContext, () => TranslationSettings.DefaultLanguage, cancellationToken) ?? TranslationSettings.DefaultLanguage;
            return userLanguage != TranslationSettings.DefaultLanguage;
        }
```
4. it should work after you have all the above steps done, if it still not works try to check the region of your translation service, add add one line code in MicrosoftTranslator.cs
```
using (var request = new HttpRequestMessage())
            {
                var uri = Host + Path + UriParams + targetLocale;
                request.Method = HttpMethod.Post;
                request.RequestUri = new Uri(uri);
                request.Content = new StringContent(requestBody, Encoding.UTF8, "application/json");
                request.Headers.Add("Ocp-Apim-Subscription-Key", _key);
                request.Headers.Add("Ocp-Apim-Subscription-Region", "westeurope");  ---> config the region of the service
```
Could you try and let me know the result? 
I've looked into this, and found that the translation middleware implementation is not so generic, so I don't think we will include this in composer soon. Please customized your runtime to enable it.

FYI, this is what I get from the emulator:
my user.LanguagePreference is set to "zh" which means Chinese, here is an echo bot result:

![image](https://user-images.githubusercontent.com/32191031/86880661-98cdea00-c11f-11ea-95ab-82c338649eca.png)

**Comment by ku222** [comment]
@luhan2017 THANK YOU!!! It works now!!
Absolutely amazing - can't thank you enough! This is just great.

Understand that this is something you don't want to put into Composer just yet - but should definitely share this somewhere for people to find more easily!

**Comment by moshe-l** [comment]
@ku222, @luhan2017  Hi, I tried to implement this solution, but unfortunately without success, I did not quite understand how to implement the code above.
Can you share your Startup.cs file? (And additional files that may be needed) 

Thanks!

**Comment by ashokdevlabs** [comment]
@garypretty @luhan2017  Hi, i have tried to add this transilation middleware in Bot Framework Composer Version 2.1 but facing some issues while we are trying with Luis for not supported languages like Indonesia, Polish... etc. 

If possible could you please share some examples to add middlewares in Composer Version 2.1.

Thanks in advance.

**Comment by SuryaKorivipaduPractice** [comment]
@ku222 I'm planning to implement Translation same like you. But I'm getting an error when trying to add package - Microsoft.BotFramework.Composer.WebAppTemplates.Translation

I've described my issue more clearly here in stackoverflow:
https://stackoverflow.com/q/70412469/17716558

Can you please help me where to find that package and how to remove "No package exists" error?
