### ISSUE TITLE
The Visual Editor border does not stay in a fixed position

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-Composer#3527]
## Describe the bug
The Visual Editor's border does not stay in a fixed position when the editor's content extends to the right and the user scrolls the editor to the right. 

## Version
Master 

## To Reproduce

1. Add a new action
2. Add several nested if-statements
3. Scroll to the right
4. Notice the border scrolls with the editor's contents

## Expected behavior
The border should stay in a fixed position

## Screenshots
![image](https://user-images.githubusercontent.com/17039790/86169076-4add3480-bad6-11ea-8992-0166dd346239.png)

**Comment by yeze322** [comment]
The border should fullfill the editor canvas
![image](https://user-images.githubusercontent.com/8528761/86197857-dca57a00-bb88-11ea-9306-4d6b4689215b.png)

**Comment by yeze322** [comment]
addressed in #3605
