### ISSUE TITLE
Error: In i is undefined

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3532]
When making changes to Dialogs in a bot, changing text, removing / adding components, after a while (not sure about the exact trigger point) errors show up that always say:
In i is undefined

I always need to reopen the bot for the error to disappear and nothing seems wrong with the bot. The error happens on any dialog I edit.

![image](https://user-images.githubusercontent.com/49873947/86212740-e8894000-bb78-11ea-8cd9-e6d6b8efd8f2.png)

Version: 2f655bba

**Comment by zhixzhan** [comment]
Hi @cxbuilders , can you give more detail to re-produce this, or the bot file if you don't mind.

**Comment by cxbuilders** [comment]
@zhixzhan In the latest version this bug has disappeared, so I guess we're all good :)
