### ISSUE TITLE
Bot Composer Publishing Stuck 

### ISSUE THREAD

**Issue by TameezAustell** [microsoft/BotFramework-Composer#3533]
## Describe the bug
I have configured all Azure resources as per the documentation. When publishing the bot the with the parameters it just keeps loading without any end. Let it run the entire night
![image](https://user-images.githubusercontent.com/64979561/86213750-7580c900-bb7a-11ea-8117-84aebada0269.png)

## Version

![image](https://user-images.githubusercontent.com/64979561/86213817-8e897a00-bb7a-11ea-96b8-04e48cac4f9b.png)

## Browser

- [ x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Publish the bot as per the guidelines
2. Copy the code into the publish profile
3. Click publish

## Expected behavior
A completed publish or an error

## Additional context
Publish Code

![image](https://user-images.githubusercontent.com/64979561/86236117-d370d900-bb99-11ea-849e-888840f43001.png)

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/3536 may fix the issue

**Comment by zxyanliu** [comment]
Hi @TameezAustell  I just tested using [Composer electron 1.0.2](https://github.com/microsoft/BotFramework-Composer/releases) and I was unable to reproduce the error you mentioned. 
Could you please try again and follow the [doc](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)?

**Comment by zxyanliu** [comment]
Closing since it is addressed.
