### ISSUE TITLE
Greeting not working in Web Channel

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3539]
The standard Greeting Trigger is not working when used in the web Channel. Nothing happens..  I use the standard url defined in the Iframe of the sample code in the bot channels registration channel menu.

**Bot**
![image](https://user-images.githubusercontent.com/49873947/86236502-7b86a200-bb9a-11ea-8038-b29d196d1265.png)

**Emulator**
![image](https://user-images.githubusercontent.com/49873947/86236543-8b9e8180-bb9a-11ea-9cc0-6e52b290620e.png)

**Bot Registration tester**
![image](https://user-images.githubusercontent.com/49873947/86236575-99540700-bb9a-11ea-8722-c7f0880f1ae5.png)

**Web Channel**
![image](https://user-images.githubusercontent.com/49873947/86236602-a53fc900-bb9a-11ea-863c-12a9c3c52735.png)

**Comment by tdurnford** [comment]
@cxbuilders Please take a look at the Web Chat [Welcome Message](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/WELCOME_MESSAGE.md) documentation.
