### ISSUE TITLE
Marieke's test example

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3547]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
Hi @mareekuh - what's this about?

**Comment by mareekuh** [comment]
This is me trying to link issues between repos. 
I've been capturing design work and backlog [here ](https://github.com/microsoft/BotFramework-Composer/projects/28 but needed to make sure I can link to both the Composer as well as the Solutions repo).
It works. Feel free to add new design requests that are not of the level of detail as a gitissue in the Left column (backlog)
