### ISSUE TITLE
Logout - Teams

### ISSUE THREAD

**Issue by andreatosato** [microsoft/BotFramework-Composer#3551]
Hi all, 
We are currently encounter error on Teams channel.
We need to implement SignOut Dialog as mentioned in this issued: https://github.com/microsoft/botframework-sdk/issues/5799
How can I implement this on composer?
Can I execute this [dialog](https://github.com/microsoft/BotBuilder-Samples/blob/8d9d0688ce3d2d28b49a5f0eaf0ff882ed6ac6ff/samples/csharp_dotnetcore/46.teams-auth/Dialogs/LogoutDialog.cs) from composer?

/cc @fathorMB

**Comment by hibrenda** [comment]
@luhan2017 for more comments

**Comment by luhan2017** [comment]
@andreatosato there is a signout action in the sdk side, we will enable it in composer in R10.
