### ISSUE TITLE
Feature: Add Declarative Actions Support

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3560]
The ability to add dialogs is useful but parameterize them is a bit of a pain. We really need the ability to create reusable dialogs which work more like actions so I'm proposing we add the concept of "Declarative Actions" and I'll show some UX mockups for how I think you'd create them within composers current IA.

### New Add Action Option
The first thing we'd add is the ability to add a new custom action:

![image](https://user-images.githubusercontent.com/698939/86500843-dcec7380-bd48-11ea-8bcc-53d510bce74f.png)

This would result in a dialog being added that can have custom parameters defined for it.

### Define Properties
Next we would add a "Properties" editor that lets you define the  properties your action can take as input:

![image](https://user-images.githubusercontent.com/698939/86501144-10300200-bd4b-11ea-8900-589cbadec065.png)

This would result in a "MyAction.schema" file to be created to go along with "MyAction.dialog".  

At runtime, any expressions would be evaluated and the final value of the configured properties would get mapped to "options" passed into the dialog so the internals for your custom action would work exactly the same was as dialogs do today.

### Add To Custom Actions Menu
Once an action has been added it would then show up as an action on the "Custom Actions" menu that can be added to a flow just like any other action.

![image](https://user-images.githubusercontent.com/698939/86501282-605b9400-bd4c-11ea-8002-855b06cd90f6.png)

### Export as Library
I didn't mock this up but I think we could also add an "Export as library" option to the export menu. This would create a package containing the projects actions that could be published to nuget or npm and then imported into other composer projects.   

![image](https://user-images.githubusercontent.com/698939/86501485-09ef5500-bd4e-11ea-97ec-b74d400988b0.png)

### New Library Project Type
We could probably add a new "Library" project type that contain no runtime or root dispatch dialog and just contains dialogs & action assets.

**Comment by Stevenic** [comment]
One question might be, why not just make dialogs work this way? Your project could have hundreds of dialogs and you wouldn't want to clutter up the actions menu with every dialog. Distinguishing Custom Actions from Custom Dialogs let you be selective about which actions get added to the custom actions menu.

**Comment by cwhitten** [comment]
@Stevenic the team has been working this for a bit now and we'll share our direction with you to get feedback.

**Comment by Stevenic** [comment]
Closing because its old
