### ISSUE TITLE
form: improve example resolution

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3565]
Currently, Composer uses the leaf node of the schema to get the placeholder. This isn't useful if a property defines its own `examples` but also includes a $ref with `examples`. We should prefer the `examples` on the property schema and fallback to the $ref's `examples` if there are none defined.

## Is your feature request related to a problem? Please describe.

The example for the `Property` field below is bad because we're expecting a property path not prompt text as in the example. A better example would be `ex. dialog.result`.
 
![image](https://user-images.githubusercontent.com/698939/82127696-75fc0680-976a-11ea-838f-86899aea7f88.png)

**Comment by a-b-r-o-w-n** [comment]
@vishwacsena Composer will use the most specific example for the placeholder. Since the `oneOf` property includes examples in each item, we will use that value instead of the example defined on the `resultProperty` schema.

**Comment by vishwacsena** [comment]
@a-b-r-o-w-n , I was referring to using the more specific example provided by the `resultProperty` in its schema definition which would be this .. "dialog.userName" and if that is missing, fall back to the any examples in the `stringExpression` definition?

**Comment by a-b-r-o-w-n** [comment]
@vishwacsena I see. I'll schedule this in the next release.
