### ISSUE TITLE
storing transcript in blob storage 

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-Composer#3582]
Hi,

How can i store the transcript in blob storage with composer please let me know.

Thanks.....

**Comment by cwhitten** [comment]
hi @madbeher - you should be able to achieve this by providing the appropriate connection information in the Bot settings:
Go to `Settings` -> `Bot Settings`

```json
  "blobStorage": {
    "connectionString": "",
    "container": "transcripts"
  },
```

**Comment by hibrenda** [comment]
@madbeher you could also reference https://github.com/microsoft/BotFramework-Composer/issues/3286 for more detail.
