### ISSUE TITLE
New Publish profile not saved

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#3593]
When creating a new Publish Profile;
![image](https://user-images.githubusercontent.com/49873947/86899637-91e8ac80-c10a-11ea-984d-7d93cb78d55e.png)

Hitting Save. Nothing is created;
![image](https://user-images.githubusercontent.com/49873947/86899666-9b721480-c10a-11ea-8c98-580f9de05d82.png)

Also existing profiles do net get updated when something has been changed in the config. As a workaround I now copied the publishtargets from one bots appsettings into this one, and update all in the appsettings.

Somehow this page is always full of bugs, when one is fixed another one pops up...

Ok, update, the actual publishing also does not work, it just keeps on running and never finishes;
![image](https://user-images.githubusercontent.com/49873947/86901319-be9dc380-c10c-11ea-9586-e13a82c1ce91.png)

version: f9128fbd

**Comment by hibrenda** [comment]
Thanks @cxbuilders This just been fixed in https://github.com/microsoft/BotFramework-Composer/pull/3557

**Comment by cwhitten** [comment]
addressed in 1.0.2
