### ISSUE TITLE
Adaptive cards Submit Actions

### ISSUE THREAD

**Issue by Bernardo08pt** [microsoft/BotFramework-Composer#3606]
I created some adaptive cards with Submit Actions so the user can click on them as an alternative to writing.

Example
![image](https://user-images.githubusercontent.com/7129408/87028633-cd50ad00-c1d6-11ea-8928-a14a1634e163.png)
![image](https://user-images.githubusercontent.com/7129408/87028783-0b4dd100-c1d7-11ea-9076-6bf6bac5bec0.png)

The problems became when I start testing the bot in Microsoft Teams, because when I clicked the buttons the text wasn't being send. 

After some researching on the web I found out that in order for the this behaviour to work ok Teams I had to send a "msteams" object in the data property, like so:
![image](https://user-images.githubusercontent.com/7129408/87028993-5ec01f00-c1d7-11ea-9252-432658dfe358.png)

The issue is that now it only works as expected on Teams and not on the Webchat. Is there some way to get it working on both?

**Comment by UmaPrelude** [comment]
Hi @Bernardo08pt ,

I handled it this way.

  "actions": [
    {
      "type": "Action.Submit",
      "title": "Submit",
      "data":  ${if(toUpper(channelName) == toUpper('msteams') ,'{"msteams": {"type": "messageBack", "value": "Sign Up"},"action": "Sign Up"}' , '{"action": "Sign Up"}')} 
      
    }
  ]

Regards,
UmPrel.

**Comment by Bernardo08pt** [comment]
Hi @UmaPrelude 

thanks for your answer, it makes perfect sense but can you tell how can I access the channel name in composer?

Thanks in advance

**Comment by UmaPrelude** [comment]
Please use turn.activity.channelId
![image](https://user-images.githubusercontent.com/65938026/87140657-7f63a400-c2bf-11ea-89f8-f55dc0f70cc8.png)
![image](https://user-images.githubusercontent.com/65938026/87140926-e3866800-c2bf-11ea-9d01-59d53419f732.png)

Hope this will help. Kindly let me know.

**Comment by Bernardo08pt** [comment]
@UmaPrelude it works!!

thank you so much

**Comment by hibrenda** [comment]
close this issue as the solution provided
