### ISSUE TITLE
Make new Telemetry Track Event action in Composer

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#3614]
A new action, 'Telemetry - Track Event' (adaptive type Microsoft.TelemetryTrackEvent) has been added to the SDK which needs to be available for a user to add within Composer. The related PR for the action in the SDK is https://github.com/microsoft/botbuilder-dotnet/pull/4252.  This will available in the nightly builds from tonight onwards.

The purpose of the action is to allow a user to raise a custom telemetry event, supplying a name for the event and, optionally, properties (key / value string pairs).  The action will use the name / properties and use the existing telemetry client, already passively tracking events, to send the event to Application Insights.

**Comment by tonyanziano** [comment]
@vishwacsena any comment on this?
