### ISSUE TITLE
DCR: add expression support to object editor.

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#3615]
When you use the `BeginDialog` action to start a dialog that takes parameters you almost always need to pull the options from memory. You'd like to be able to author the options object like this:

![image](https://user-images.githubusercontent.com/698939/87090515-fa0fbf00-c1ec-11ea-8540-e41f2f647f73.png)

That matches the way you'd author a JSON object using LG but it's not supported by the Object Editor. Instead you have to use an expression like this:

![image](https://user-images.githubusercontent.com/698939/87090642-29bec700-c1ed-11ea-8359-debc39c6c098.png)

This is a) non intuitive and b) doesn't scale beyond a property or two.  Even adding a second property results in an expression like: `=addProperty(addProperty({}, "answer", dialog.answer), "editable", dialog.isEditable)`

This is a major pain point for using dialogs currently.

**Comment by Stevenic** [comment]
I do realize this would require a change to the underlying adaptive expression but it is a current pain point.

**Comment by Stevenic** [comment]
The other option would be to change the `BeginDialog` skill to take a list of option parameters where each param value can be an expression. The UX would look similar to that of the switch statement.

**Comment by tdurnford** [comment]
@Stevenic The JSON Editor is raising an error because the text you entered is not valid JSON. If you wrap the answer value in double quotes, it should work as expected. 

![87596030-ab5e9b00-c6ac-11ea-83cc-90d1ea7d3733](https://user-images.githubusercontent.com/17039790/87596438-5cfdcc00-c6ad-11ea-9172-b9c5b8acc3a0.png)
