### ISSUE TITLE
Need ux design for error & warning on triggers if switching recognizer types

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#3618]
Switching the recognizer type from Default to regex, composer will show warning if OnQnAMatch or OnChooseIntent exist. Meanwhile if user add OnQnAMatch or OnChooseIntent trigger under regex recognizer, composer will show warning as well.
as these triggers will require the crosstrain feature which not support under Regex Recognizer.

Currently we show warning as following :
![image](https://user-images.githubusercontent.com/43408889/87150326-66211e80-c2e4-11ea-81ef-3d059cff1bf6.png)
But these info has not been roll up to notification page and these are warnings but not errors.

So do we want to show the warning in notification page only or show it for trigger navigation panel as well ?

**Comment by mareekuh** [comment]
@hibrenda 
First pass on designs by Vivek. Please leave comments inline

https://www.figma.com/file/deFhMPBnRWxTYiYDYqYxrc/Composer---Vivek?node-id=6696%3A99621

**Comment by cwhitten** [comment]
Closing as Accepted
