### ISSUE TITLE
version 1.0.2 crash on windows server 2019 Datacenter

### ISSUE THREAD

**Issue by malotho** [microsoft/BotFramework-Composer#3622]
## Describe the bug
After upgrading from version 1.0.0 to 1.0.2 when opening the old bots the Composer app hangs and doesnt start up ever again.

## Version
1.0.2
I cannot paste the SHA because the app does not start up.

## Browser

- [ ] Chrome

## OS

- [ ] Windows

## To Reproduce

1. Install version 1.0.0 
2. Create a bot application test and run in emulator
3. upgrade to version 1.0.2
4. Notice the application does not start up

**Comment by hibrenda** [comment]
@malotho if you could provide more info with bot assets(dialog, lu, lg files), that can help us to deep dive. Thanks

**Comment by malotho** [comment]
> @malotho if you could provide more info with bot assets(dialog, lu, lg files), that can help us to deep dive. Thanks

[botassetsexcludingassets.zip](https://github.com/microsoft/BotFramework-Composer/files/4918575/botassetsexcludingassets.zip)
Let me know if you need anything extra.

**Comment by hibrenda** [comment]
@malotho could you provide the root dialog as well which marked in attached file ?
![image](https://user-images.githubusercontent.com/43408889/87661377-1387ac80-c793-11ea-9bfb-fa6a1bd0489c.png)

**Comment by EricDahlvang** [comment]
@malotho  Please provide the requested info.  We would like to close this out.

**Comment by malotho** [comment]
resolved on later versions
