### ISSUE TITLE
Hand off to live agent documentation

### ISSUE THREAD

**Issue by behram-kn** [microsoft/BotFramework-Composer#3624]
Can we have a step by step guide to 'Hand off to live agent', 'Hand off using MS teams and  D365 Omnichannel" in the documentation, similar to Azure health Bot and Power virtual agent, please.

**Comment by zxyanliu** [comment]
@tonyanziano is this feature available in Composer now? 
@behram-kn are you looking for a doc on this feature in Composer [docs](https://docs.microsoft.com/en-us/composer/)?

**Comment by behram-kn** [comment]
Hi Yan

Thank you for your email.

I am looking for the documentation to be available for hand over and also if this is something we can do within the composer.

The examples similar to what I am requesting are

Microsoft Health Bot:
https://docs.microsoft.com/en-us/healthbot/handoff
https://docs.microsoft.com/en-us/healthbot/handoff-teams
https://docs.microsoft.com/en-us/healthbot/omnichannel

Microsoft Power Virtual Agent.
https://docs.microsoft.com/en-us/power-virtual-agents/advanced-hand-off#:~:text=With%20Power%20Virtual%20Agents%2C%20you%20can%20hand-off%20conversations,%28the%20context%29%20as%20well%20as%20all%20user-defined%20variables.


Kind Regards
Behram

**Comment by zxyanliu** [comment]
Hi @behram-kn I got it! Thanks for your feedback, we really appreciate it!

**Comment by zxyanliu** [comment]
@hibrenda Can we follow up offline and walk through the steps of using the **Handoff activity** in Composer?

**Comment by cwhitten** [comment]
@behram-kn human/live-agent handoff is not modeled in the Bot Framework SDK as a component primitive, but there are plans to do so (cc @arturl )

Achieving the scenario in Composer today would require the use of a [Custom Action](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action)

**Comment by zxyanliu** [comment]
FYI. The custom action topic has been recently updated [here](https://review.docs.microsoft.com/en-us/composer/how-to-add-custom-action?branch=pr-en-us-174#additional-information). The content will go live soon.

**Comment by peterinnesmsft** [comment]
We anticipate this to go live with our R10 release. If there's any further support needed, reactivate and let us know.
