### ISSUE TITLE
Update UX Copy on Home Page

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3625]
[9:56 AM] Scott Gellock
[..] we should change the text that is on the Composer apps "home" age 
we say that Composer is an integrated developement environemtn (IDE) for building bots.
but it's not an IDE.  We don't debug, we don't write C# or JS or Python or Java code.  
Integrated develop,ent Evnironments are heavy weight developer tools.  Eclipse, Visual Studio, JetBrains, XCode are the only 4 IDE tools left in the market place.  

@zxyanliu - Do you have a suggestion for what to replace this with?

**Comment by zxyanliu** [comment]
@mareekuh I have two suggestions: a short one and a long one.

1. "Bot Framework Composer is an open-source visual authoring canvas for developers and multi-disciplinary teams to design and build conversational experiences." 

2. Bot Framework Composer is an open-source visual authoring canvas for developers and multi-disciplinary teams to build bots.  Composer integrates language understanding services such as LUIS and QnA Maker and allows sophisticated composition of bot replies using Language Generation.

**Comment by zxyanliu** [comment]
Hi @mareekuh and @cwhitten, can you guys help pick one of the descriptions / or propose new ones so that I can update this in the UI? thanks.

**Comment by mareekuh** [comment]
Can we use what we have on the website?

Bot Framework Composer is an open-source, visual authoring canvas for developers and multi-disciplinary teams to design and build conversational experiences with Language Understanding, QnA Maker, and sophisticated composition of bot replies (Language Generation).

**Comment by zxyanliu** [comment]
@mareekuh I think the one used on the website is too long and without any breaks. 
I asked @JonathanFingold for help. We came up with the following one: 

Bot Framework Composer is an open-source visual authoring canvas for developers and multi-disciplinary teams to build bots. Composer integrates language understanding services, such as LUIS and QnA Maker, and allows sophisticated composition of bot replies using language generation.

**Comment by mareekuh** [comment]
Looks good to me!
I’ll get the one on the web updated.

**Comment by zxyanliu** [comment]
@mareekuh 
I found another text in Composer which might need to update as well:

![image](https://user-images.githubusercontent.com/32497439/87724889-11145b00-c771-11ea-928b-60cbffb2d85e.png)

**Comment by zxyanliu** [comment]
@mareekuh FYI. 
This is my proposal in PR#3651.

![image](https://user-images.githubusercontent.com/32497439/87729533-76207e80-c77a-11ea-9089-4c564dbb63cf.png)

![image](https://user-images.githubusercontent.com/32497439/87729599-98b29780-c77a-11ea-8615-e7db5bb04f01.png)

**Comment by mareekuh** [comment]
Looks great. If you want to shorten, we can drop the 2nd sentence but this, as is, works for me.
