### ISSUE TITLE
Design -> Create

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3626]
Can we change the label of the 'Authoring Canvas' in the menu bar (grey vertical bar) from 'Design' to 'Create'.
Create is inline with what the Power Tools (flow etc) use to refer to the creation / design canvas.

Marieke

**Comment by zxyanliu** [comment]
@mareekuh works for me. 
I will create a PR to update this in UX, together with a fix to the [Composer description issue](https://github.com/microsoft/BotFramework-Composer/issues/3625). Sounds good?

**Comment by zxyanliu** [comment]
Hey @cwhitten, can you help double-check we should make this update? It's an easy fix, but I wanted to make sure.

**Comment by mareekuh** [comment]
![Screen Shot 2020-07-14 at 12 09 27 PM](https://user-images.githubusercontent.com/48503434/87466677-8a724900-c5cb-11ea-95c9-50ae706a3853.png)
![Screen Shot 2020-07-14 at 12 07 11 PM](https://user-images.githubusercontent.com/48503434/87466684-8cd4a300-c5cb-11ea-8f0b-b756bdff5413.png)

**Comment by zxyanliu** [comment]
Let's close this issue for now since it will be addressed via the R11 project to improve tooltips and help links. 
Feel free to reopen when necessary.
