### ISSUE TITLE
Support GoToAction in composer

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#3627]
## Is your feature request related to a problem? Please describe.
I want to create looping logic similar to a while loop based on a condition to repeat a number of steps in a dialog until the user is done. GoToAction allows me to create this logic simply and fills the feature gap.

## Describe the solution you'd like
Support GoToAction node, and include a dropdown with the actions in the current dialog so I do not have to explicitly create a new id for the node I want to goto.

## Describe alternatives you've considered
I copied the current gotoaction into my custom actions library and verified it works for me, but it does not have a full UI to make the scenario easy to use.

**Comment by yeze322** [comment]
refs #2375
