### ISSUE TITLE
Transcript in composer

### ISSUE THREAD

**Issue by UmaPrelude** [microsoft/BotFramework-Composer#3628]
Hi,

I wish to send an email with the transcript when user wish to schedule a meeting.
Is there any possibility to get the transcript from composer.
Please recommend.

Regards,
UmPrel

**Comment by tonyanziano** [comment]
Hi @UmaPrelude ,

Unfortunately there currently is no way to capture the bot's transcript from Composer other than the currently existing transcript logging middleware which would store the entire transcript in Blob Storage. However, it would then be up to you to process the transcript to grab the appropriate chunk of the transcript related to the conversation.
