### ISSUE TITLE
Bot composer OAuth refresh token

### ISSUE THREAD

**Issue by kshyambabu** [microsoft/BotFramework-Composer#3629]
Hi, I am implementing authentication for Active directory v2. Authentication is going pretty well and recieving the token, But not getting the refresh token. The access token is expiring in 1 hour. 

1. Is there way to get the refresh the token for the Active directory v2 from the bot composer?
2. If we dont get the refresh token, what would be the best way to handle the token expiration in bot composer?

**Comment by DingmaomaoBJTU** [comment]
Yes, the oauth prompt will help you refresh token. Note: please do not store the token by yourself, when you want to use token, get it from oauth prompt. Then it will help you manage your token.

**Comment by kshyambabu** [comment]
I am using the settings as described below, I should not give the user login card every time token expires. Do I need to set extra configuration for OAuth prompt to get the refresh token without prompting to user login again?
![image](https://user-images.githubusercontent.com/66311936/87498158-c1e90000-c674-11ea-8cb9-e40d2a133687.png)

**Comment by SattaRavi** [comment]
@DingmaomaoBJTU can you please  explain a bit further on how to refresh tokens using the oAuth prompt.

i understand the access token can be retrived from the oAuth prompt but, how does one refresh tokens.

our scenario is we authenticate users against AAD and once authenticated the user will be using the bot for an extended period of time.

given the scenario what is the recommended approach to handle token expiration. (asking the user with oauth prompt  often would be a bad experience)

**Comment by DingmaomaoBJTU** [comment]
The logic of [oauth prompt](https://github.com/microsoft/botbuilder-dotnet/blob/71696394f8dc29533c250a359fb39c2c69e0117e/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs#L139) is like this: 1) retrieve token from service  2) if failed, prompt.  When in step 1, the service help you refresh token and always return a useful token if user log in. There is nothing special to set for OAuth prompt (the only thing you need to notice is don't enable the alwaysPrompt flag). If token service does not have a valid token, then the OAuth prompt will prompt. It does not prompt everytime. 

Please have a try, if oauth prompt not work as expect, you can log a bug for us~

Not sure whether I'm fully understand what you required. Please add more comments if there is any.

**Comment by DingmaomaoBJTU** [comment]
And here is the [official doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp#use-an-oauth-prompt-to-sign-the-user-in-and-get-a-token), you can take a look~

**Comment by kshyambabu** [comment]
@DingmaomaoBJTU Thanks. The answer gave us the insight on how to use OAuth prompt and how it is performing internally.
