### ISSUE TITLE
Reopening issue #3629 : Bot composer OAuth refresh token

### ISSUE THREAD

**Issue by kshyambabu** [microsoft/BotFramework-Composer#3632]
Hi, Apologies for reopening the same issue. 
The issue was closed without giving much information. My question was how to get the refresh token for OAuth. User has to stay extended period of time on bot. But, the access token from OAuth prompt is getting expired in 1 hour. The questions remain open,
1) How can we use OAuth prompt to get the refresh token?
2) If it is not possible, then how to handle token expiration?

The closed question is #3629

**Comment by cwhitten** [comment]
Hi @kshyambabu - https://github.com/microsoft/BotFramework-Composer/issues/3629 has been re-opened. Let's use that issue
