### ISSUE TITLE
Replace Dialog Clarification

### ISSUE THREAD

**Issue by Bernardo08pt** [microsoft/BotFramework-Composer#3633]
Hello,

I don't know if I'm misinterpreting the "Replace Dialog" action or not, so I don't know if this is a bug or not.

I expected that when I'm in the middle of a Dialog and used the "Replace Dialog" the current dialog ended and a new dialog started, but instead what happens is that the new Dialog opens and when it is over it comes back to the previous Dialog.

It seems that the "Replace Dialog" is working the same way that the "Begin Dialog"

**Comment by v-kydela** [comment]
@Bernardo08pt - Thank you for the report. Can you provide some sample code that reproduces the issue?

**Comment by v-kydela** [comment]
Looks like this is a bug after all: https://github.com/microsoft/botbuilder-dotnet/issues/3900
