### ISSUE TITLE
The react developer tool introduces an error.

### ISSUE THREAD

**Issue by liweitian** [microsoft/BotFramework-Composer#3634]
## Describe the bug
In the main branch, **open the dev tool with react developer tools extension installed**.
Open localhost:3000. Refresh the page or do anything that may re-render the page.
Then an error appears.
The debug process is influenced.
Not sure whether this bug is from our project since if we disable the extension, the error won't appear.
## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## Screenshots

![QQ图片20200715173300](https://user-images.githubusercontent.com/24380525/87529685-ed460c00-c6c1-11ea-87aa-f740a0be1749.png)

**Comment by hatpick** [comment]
@liweitian What version of react dev tools is causing this?

**Comment by hatpick** [comment]
4.8.0 and 4.8.1 have that issue due to an empty ```<Suspense>``` tag in ```DesignPage.tsx#L462```

4.8.2 solves the issue, please update.

**Comment by liweitian** [comment]
The error is solved on my side now.
