### ISSUE TITLE
Visual update and conceptual refinement of left nav in Authoring canvas

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3638]
@vivekkshankar 
(FYI @sangwoohaan )

Today, the scope of the menu bar is bot-(bot project) focused and provides a user with the ability to switch modes and get a 'canvas'/UI catered to that mode: a visual canvas for authoring, a list based view for editing content etc.

Each of the modes have a sub-nav. For most of them they include an 'all' (aggregated view across all) as well as folders/dialogs to allow the user to 'filter' down to a specific scope : the particular dialog (and in the 'Publish' case: the publish profile).

The issue:
1. In the Authoring canvas, in addition to dialogs, we show 'triggers' or more appropriately: the event handlers that initiate the dialogs. While this is technically accurate (the handlers live at the top level of the dialog, it results in an awkward view for the canvas: the top level dialog is 'empty' and, while reasonably nice looking, basically the 'Select a trigger on the left
navigation to see actions' feels like an error message. **We can and should do better.**

![Screen Shot 2020-07-15 at 9 39 00 AM](https://user-images.githubusercontent.com/48503434/87571516-09748980-c67f-11ea-94e4-584da7a76122.png)

2. While PVA has 'trigger phrases' associate to it's topics, they do not have the concept of trigger, event handler or events (other than user input). The more PVA and Composer will be integrated, the more glaring and problematic this issue will become. Our current nav is learnable for devs, but currently does not easily map to existing mental models of navigation or hierarchical structures that people are familiar with (Windows, websites, Mac OS, iOS, Android etc).
**To increase impact and set ourselves up to scale, we'll want to align to and build upon familiar patterns and metaphors**
![Screen Shot 2020-07-15 at 9 45 21 AM](https://user-images.githubusercontent.com/48503434/87572222-147be980-c680-11ea-9d1e-3601e4e5c9ef.png)

3. Enabling Bot projects that include a bot core with dialogs, KBs and local and remote skills, has led to additional requirements about how to communicate the content of the project in the nav. The functional design was inspired by the 'explorer' view in Visual Studio and Emulator. This functionality is familiar to the MSF developer audience and has not yet been updated to reflect Fluent guidelines and best practices. It would be worth following up with the visual studio team to learn **if and when they plan to apply Fluent** and to **take a look at the workflow of conversation AI development teams**, which likely includes using and switching between multiple apps  (composer, visual studio, emulator, pva, webchat etc.

--

@vivekkshankar  As I know you had comments & thoughts about how to improve the navigation (left panel, not the menu bar (gray panel)) - could you take a pass at the following;

1. - Review the requirements above
2. - Review the history of Composer navigation | [[Sangwoo's figma is here]([url](https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=417%3A0))] | other designs and [explorations are here](https://www.figma.com/file/fALk0GlaFYMB6HGppi4oSw/MI-ARCHIVE?node-id=6%3A1901) 
3. - Collect examples across msft /fluent for (semi) hierarchical navs - which ones we can leverage/build on other than Visual Studio (which is not Fluent-based and is in the process of getting updated)
4. - review most [recent functional designs by Sangwoo](https://www.figma.com/file/04DymSq4xElhOBdAyutvvTbq/Composer-SH-06.19?node-id=6682%3A0)
5. - Create a handful options to improve the interaction model, ease-of-use (aka leverage more familiar concepts and patterns) 
6. - Apply Fluent visuals and design patterns

**Comment by vivekkshankar** [comment]
Love it - I'll take a stab at this :)

**Comment by cwhitten** [comment]
Design has been provided and we're building it out. Closing as complete (the design part)
