### ISSUE TITLE
[MCS-DE] Check number of LUIS versions when publishing and clean-up to avoid hitting the max. 100 versions limit

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#3640]
Any publishing plug-in should always check the number of LUIS versions on all LUIS Apps that they publish to.

If the number of versions per LUIS App is above a threshold the oldest versions need to be deleted to avoid hitting the LUIS version limit per LUIS App.

@benbrown

**Comment by luhan2017** [comment]
@boydc2014 @cwhitten @feich-ms , could you set the default value of deleteOldVersion which is used in luis publish API to true? For now we don't support versioning and fallback.

**Comment by feich-ms** [comment]
Luis builder API has the deleleOldVersion parameter there. Composer can set it to true when calling luis builder.

**Comment by cwhitten** [comment]
@feich-ms @luhan2017 yes let’s go ahead and do that. Thanks

**Comment by boydc2014** [comment]
Hey, @goergenj it's been addressed via #3661, you can check out the latest main branch, or use our daily build electron version which should be out tomorrow

**Comment by goergenj** [comment]
@boydc2014 Will this be part of the Azure Publishing plug-in or a general feature for all publishing plug-ins?

**Comment by goergenj** [comment]
@boysdc2014 See above open question.

@joaollq Can you please check when we have upgraded the Composer?
