### ISSUE TITLE
UX Spec: Commenting in Composer

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3654]
**UX SPEC : Commenting in Composer**
CREATED: 7/17/2020 
LAST UPDATED: 7/17/2020 
  V-TEAM:  Vivek, Andy Brown, Ben Brown, Marieke
 
**Exec summary** 
Provide the ability for commenting in Composer
P0: commenting per node for documentation purposes
P1: Commenting per node for collaboration purposes
P1: Commenting-specific node
P1: Commenting per dialog for documentation purposes

What: Add note to a node to capture functionality and comments or questions for self or others
Why: Devs do this in code often and there is a need for reflecting this in Composer, and initiate this in Composer
How: Show already existing 'Description' field, provide instructions/example and monitor how this is used by our users
Where: inside the authoring canvas and in Properties pane
For whom:   Individual devs (P0), dev teams (P1)

**The situation** 
Devs add comments in their code to document or add notes for themselves or others. They currently cannot do so in Composer.

**The objective** 
< add detail here> 

**IS NOT....** 
< add detail here > 

**SCENARIOS**

**1.1. Create  comment in Properties panel - as part of node**
Add link to design here @vivekkshankar < add detail here > 

**1.2. Create  comment in Authoring panel - as part of existing node**
Add link to design here @vivekkshankar
< add detail here > 

**1.2. Create  comment in Authoring panel - as part of existing node**
Add link to design here @vivekkshankar
< add detail here > 

**2.1 Edit comment**
- Delete
- Change text
- @mention somebody
< add detail here > 

**3.1 Find comments**
- Browse 
- Search 
< add detail here > 

**4.1 Show /Hide comments  **
< add detail here > 

Related issues on github
@a-b-r-o-w-n  - could you connect this to existing issues?

**Comment by vivekkshankar** [comment]
@mareekuh @a-b-r-o-w-n The experiences for the various scenarios called out above can be found here:
https://www.figma.com/file/deFhMPBnRWxTYiYDYqYxrc/Composer-Vivek?node-id=6696%3A97661

**Comment by mareekuh** [comment]
I thought this was being implemented for R11 but may have been cut. I do think it's a very useful and relevant feature.

**Comment by mewa1024** [comment]
correct. It was cut. (don't know the context)
