### ISSUE TITLE
UX Spec - Bot project: Managing multiple bots in Composer

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3655]
UX SPEC : Managing multiple bots in Composer
CREATED: 7/17/2020
LAST UPDATED: 7/17/2020
 V-TEAM: @sangwoohaan @srinaath  @cwhitten  @mareekuh 

**Exec summary**
<add content here > 

What: A bot project is a file that composer will build as the developer adds one or more skills, so that it (composer) can know what to deploy and how to deploy it. 
Why: Allows the devs to create, view, run, test and manage a core bot + skills as a group and individually.
How: the bot project is a file, in the UI it shows the elements that are included: core bot, (remote) skills, KBs
Where: Code: SDK, in UX: the left nav
For whom:  Devs
Wen: R10+

**Definitions:**
@zxyanliu to refine, update below and add to glossary

- **Bot** = collection of dialogs which each contain elements such as: trigger, LU, LG and schema file​
- **Root bot** = core bot = evolution of dialog.main / basic bot template in ABS = bot that includes Help, Greeting, etc.​
- **Skill** = Bot + manifest (the manifest has a property which is the location of the skill, it's endpoint).​
- **Bot project** = Root boot with the one or more skills. A file format that provides a higher level management experiences to create, manage, test, publish a larger application solution, consisting of multiple bots, dialog types and skills ​
- **VA** = virtual assistant = a type of bot project​
- **VA Core** = VA-specific Root Bot, and includes VA specific components and flavors Help, Greeting, language models etc.​
	 
**The situation**
Both customers and internal teams have asked for the ability to able to run more than one instances of Composer, so that they can work on more than one bot at a time, and create bots that consists of multiple bots. 

**The objective**
Composer enables devs to create bots in a composition-manner: start small by creating a single bot or dialog, add sophistication over time and extend capabilities by connecting to other bots or services that have been created 'locally' (self or dev team) as well as by 1st or 3parties, including the dev community. Bot projects consist of a core, which includes the table of contents of the bot, basic capabilities such as help, cancel, confirm, greeting and hand-over-to human. Bot developers can attach local or remote skills to this Core bot. This core-bot and the skills it is connected to together become the bot project which enables the dev to start, stop, test and publish the project as a whole or one at a time.
The bot project is a technical solution to enabling and should not be a key concept for users to understand or manage 

**IS NOT....**
- A front-and-center concept in the user interface of Composer
- The bot project is not something a dev really “works on”. Composer will set the contents of this file. It’s really a file that composer will build as the developer add more local skills so that it (composer) can know what to deploy and how to deploy

**SCENARIOS**

Overall scenario/flow

1. Create new

- new bot - you van pick from VA templates. This automatically creates a bot project (default) and includes a core, orchestrator and basic capabilities such as greeting, handover to human, help etc.
- new skill (basically a bot with a manifest) - this is a plain bot that can be built starting from a sample or a starter skill.

2. Review/update customize

3.  Test skill or bot (depending on which you selected)

4.  Optional: Add skill to a bot by pointing the bot to the skills manifest

5. Publish the bot (VA/Bot project)  
As part of the publish step, the url address of the skill gets assigned.  we can then write that information into a settings file for the Root Bot to retrieve when it launches.  We probably do manifest validation as a pre-deploy step.  Would want to talk with others about this sequencing.

6. 	Discover that there is an issue with one of the skills

7. 	Editing the same bot and skill as above.

8. 	Start at step 3 again (repeat)

	...

**1.1. Create a new bot project and adding local or remote bots as skill to my core bot. I can also visually see what is included in my BotSpace and manage them.  - P0 (see Jas' flow also) **
< add detail here >
Design: https://www.figma.com/file/S6LnI9uqRtuKaoCVxTVJMz/SH-WIP?node-id=335%3A327

**1.2 Create a new bot (aka skill) to be added to Bot project - P0 **
< add detail here >
Design: https://www.figma.com/file/S6LnI9uqRtuKaoCVxTVJMz/SH-WIP?node-id=335%3A1317

**1.3 Turn bot into bot project - P2 **
< add detail here >
< @sangwoohaan  add link to design here> 

**1.4 Turn bot into core bot**

< add detail here >
< @sangwoohaan  add link to design here> 

**2.1 Add local as skill to my bot project  P0**

< add detail here >
Design: https://www.figma.com/file/S6LnI9uqRtuKaoCVxTVJMz/SH-WIP?node-id=335%3A1317

**2.1.1 Add bot to bot project -  P2**

< add detail here >
Design: https://www.figma.com/file/S6LnI9uqRtuKaoCVxTVJMz/SH-WIP?node-id=335%3A1317

**2.1.2 Add local skill to Bot project  - P0**

< add detail here >
Design: https://www.figma.com/file/S6LnI9uqRtuKaoCVxTVJMz/SH-WIP?node-id=335%3A1317

**2.1.3 Add remote skill to Bot project  - P0 (already in QnA flow)**

< add detail here >
Design: https://www.figma.com/file/S6LnI9uqRtuKaoCVxTVJMz/SH-WIP?node-id=335%3A1317

**2.1.4 Add KB to bot project - P0 (already in QnA flow)**

< add detail here >
< @sangwoohaan  add link to design here> 

**2.1.4. Add custom code action from Visual Studio to bot project- P1**

< add detail here >
< @sangwoohaan  add link to design here> 

**2.2 Remove remote bots as skill to my bot project- P1**

< add detail here >
< @sangwoohaan  add link to design here> 

**2.3 Edit remote & local skills- P1**

< add detail here >
< @sangwoohaan  add link to design here> 

**3.1  Run, test and update my bot project in Emulator- P0**
https://www.figma.com/file/S6LnI9uqRtuKaoCVxTVJMz/SH-WIP?node-id=488%3A442

**3.2 Run, test and update individual skills that are part of my bot project in Emulator- P0**
https://www.figma.com/file/S6LnI9uqRtuKaoCVxTVJMz/SH-WIP?node-id=488%3A442

**4.1  Publish my bot project- P0**

< add detail here >
https://www.figma.com/file/S6LnI9uqRtuKaoCVxTVJMz/SH-WIP?node-id=335%3A9159

**4.2 Publish individual skills that are part of my bot project- P0**

< add detail here >
https://www.figma.com/file/S6LnI9uqRtuKaoCVxTVJMz/SH-WIP?node-id=335%3A9159

**5. Switch between bot and bot projectn- P0**

< add detail here >
< @sangwoohaan  add link to design here> 

**6. Copy section of a bot from one project to another bot project - P0 **

< add detail here >
< @sangwoohaan  add link to design here> 

**7. Manage bot project settings  P1  **
 
**7.1  Manage skills settings that are part of bot project**

**7.2  Manage KB settings that are part of bot project**

< add detail here >
https://www.figma.com/file/S6LnI9uqRtuKaoCVxTVJMz/SH-WIP?node-id=335%3A10928

**Responsible AI criteria** 
-
This section includes the detailed description of the experience 
 < add detail here >

 
**Accessibility criteria** 
-
This section includes accessibility criteria 
 < add detail here >

**Related features** 
-
Related features and functionality in and outside the product area that relate to, are dependent on this functionality 
 < add detail here >

**Risks** 
-
< add detail here >

**Dependencies** 
< add detail here >

**Comment by zxyanliu** [comment]
@mareekuh here are my feedback and questions on the definition of terms (please correct me if I am wrong):

|Term | Definition | 
|---|---|
| Bot project | A Bot project is a collection of local and remote bots related as host-skill bots in Composer. Provides higher-level management experiences to create, manage, test, publish a larger application solution consists of multiple bots. See [other proposed terms](https://microsoft-my.sharepoint.com/:x:/p/v-liyan/EaBHkzx9kMdFoPHWF4DlEYgBUQC0JZkKsRK620qiy92Mkg?e=yPcYNa).  | 
| Bot | A bot is a collection of dialogs that each contains a trigger, lu, lg and schema file. | 
| VA | [Virtual Assistant](https://microsoft.github.io/botframework-solutions/overview/virtual-assistant-solution/) | 
|Skill | A skill is a bot that can perform a set of tasks for another bot. |
|Skill manifest | A skill manifest is a JSON file that describes the actions the skill can perform. | 
|Remote skill | A remotely-hosted skill. |
|Local skill | A locally-hosted skill. | 

Questions:
* I don't understand Root bot, Core bot, Bot core in this scenario. If they are the same, should we just pick one of them? 
* I don't understand 

- Root bot = core bot = evolution of dialog.main = bot that includes Help, Greeting, 
- Core Bot = (evolution of Basic bot template in ABS, which includes LUIS and QnA integration)
- Bot Core = Core bot
- VA Core =  Core Bot focused on VA (VA skills : Calendar, etc)

- Skill = Bot + manifest (the manifest has a property which is the location of the skill, it's endpoint).
- Manifest = SON file that describes capabilities (Actions), inputs, outputs and endpoint of a Skill
- Remote skill = 1st party skill = a skill hosted and managed by MSFT or 1st party. Minimal changes possible by Customer
- Local skill = skill that is locally built and may or may not be hosted via SaaS
- 1st party skill = remote skill
- Starter skill = Editable version of VA skills: Calendar, Email, Point of Interest, Weather, Who bot etc.

**Comment by mareekuh** [comment]
Replaced some of the definitions based on input from Composer Leads and Design review with LIli (08.06.2020)-

**Comment by mareekuh** [comment]
@sangwoohaan Could you add links to the scenarios above to ensure we have all of them addressed?

**Comment by sangwoohaan** [comment]
@mareekuh Links added - I'll keep filling in the list as the designs gets finished.

**Comment by zxyanliu** [comment]
@mareekuh terms and definitions:

| Term | Definition | 
| ------| ------------|
| Bot project | Top-level “container” of multiple bots. A _Bot project_ can contain a root bot, 0 or more skills, 0 or more VA bots. |
| Bot | A collection of dialogs that each may contain triggers, actions, lu, lg and schema files. |
| Root bot |  Evolution of `dialog.main` or a basic bot template in Azure Bot Service. It can be a bot that includes Help, Greeting, etc.​ | 
| VA | [Virtual Assistant](https://microsoft.github.io/botframework-solutions/overview/virtual-assistant-solution/). A type of bot that uses [VA templates](https://microsoft.github.io/botframework-solutions/overview/virtual-assistant-template/) to compose a bot. | 
| VA Core | A VA-specific Root Bot which includes VA specific components and flavors Help, Greeting, language models. | ​
| Skill | A bot that can perform a set of tasks for another bot. A skill bot can be reusable components. You can edit one or more dialogs and (re)publish the skill bot such as Weather skill, Point of Interest skill, Payment skill. | 
| A skill manifest | A JSON file that describes the actions the skill can perform. | 
| Remote skill | A skill that is hosted remotely. |
| Local skill | A skill that is hosted locally. |
