### ISSUE TITLE
Customized functions in runtime should pass validation and be allowed to start bot

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#3656]
## Is your feature request related to a problem? Please describe.

Currently, all function calls in an expression is parsed and checked to make sure it's a valid function, otherwise we will throw error and block user from starting bot. 

The issue is for some customers, if they have a customized runtime that have customized functions (using code) built-in and composer isn't aware of that, thus composer will still treat it as an error. 

## Describe the solution you'd like

Add a settings field "customizedFunctions" (or any other name) to allow user to config a list of functions name that is customized and should be ignored in validation phase.

**Comment by vishwacsena** [comment]
@boydc2014 So a workaround for now in composer would be to wrap a custom function in LG until we natively support it? 

```markdown
> !# @Namespace = namespace
> !# @Exports = customFunctionWrapper
# customFunctionWrapper
- ${customFunction()}
```

**Comment by boydc2014** [comment]
> @boydc2014 So a workaround for now in composer would be to wrap a custom function in LG until we natively support it? 
> 
> ```gfm
> > !# @Namespace = namespace
> > !# @Exports = customFunctionWrapper
> # customFunctionWrapper
> - ${customFunction()}
> ```

Unfortunately no, because inside LG, we also validate the functions calls, so your last line "$customFunction()" will also throw. I think we can give this a higher priority, if any customer is asking for this?

**Comment by didaskein** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/3130

**Comment by johnataylor** [comment]
@boydc2014 we have a customer and @didaskein can provide details, but this issue is a priority.

**Comment by cwhitten** [comment]
@garypretty we're taking the linked PR to make this possible, however the long-term approach would be to provide a way to model these functions with schema or extensions to adaptive-expressions.
