### ISSUE TITLE
Error in invoking Skill ID .. ""http://localhost:3980/manifests/EmptyBot-0-2-0-0-manifest.json AND "Value cannot be null. (Parameter 'uriString')"

### ISSUE THREAD

**Issue by rudrasingh21** [microsoft/BotFramework-Composer#3659]
HI Team I am getting error while working with Skill in bot framework Composer .

I tried many combination to make this work, but all the time I am getting different error.

Recent ERROR:--

Error invoking the skill id: “003eedb4-1991-403c-b848-9536ce1b5bb8” at “http://localhost:3980/manifests/EmptyBot-0-2-0-0-manifest.json” (status is 404).

I followed this doc to work with Skill bot :-
https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill

But thinks are not working for me . 

Can you help please? 

Other details :-- Using version V1.02 of composer 
on V1.0.1 , i am facing the same issue

**Comment by rudrasingh21** [comment]
Bot setting at consumer bot--

{
  "feature": {
    "UseShowTypingMiddleware": false,
    "UseInspectionMiddleware": false,
    "RemoveRecipientMention": false
  },
  "MicrosoftAppPassword": "",
  "MicrosoftAppId": "",
  "cosmosDb": {
    "authKey": "",
    "collectionId": "botstate-collection",
    "cosmosDBEndpoint": "",
    "databaseId": "botstate-db"
  },
  "applicationInsights": {
    "InstrumentationKey": ""
  },
  "blobStorage": {
    "connectionString": "",
    "container": "transcripts"
  },
  "luis": {
    "name": "",
    "authoringKey": "",
    "authoringEndpoint": "",
    "endpointKey": "",
    "endpoint": "",
    "authoringRegion": "westus",
    "defaultLanguage": "en-us",
    "environment": "composer"
  },
  "publishTargets": [],
  "qna": {
    "knowledgebaseid": "",
    "endpointkey": "",
    "hostname": ""
  },
  "telemetry": {
    "logPersonalInformation": false,
    "logActivities": true
  },
  "runtime": {
    "customRuntime": false,
    "path": "",
    "command": ""
  },
  "downsampling": {
    "maxImbalanceRatio": 10,
    "maxUtteranceAllowed": 15000
  },
  "skill": [
    {
      "manifestUrl": "http://localhost:3980/manifests/EmptyBot-0-2-0-0-manifest.json",
      "name": "SkillBOT"
    }
  ],
  "botId": "",
  "skillHostEndpoint": "http://localhost:3980/manifests/EmptyBot-0-2-0-0-manifest.json"
}

NOTE:- I tried giving :- "endpointUrl": "http://localhost:3983/api/messages", as well but not worked

**Comment by rudrasingh21** [comment]
at Consumer bot side:-

![image](https://user-images.githubusercontent.com/30667041/87883846-11099a80-c9bf-11ea-88e6-74cb1bc1aa1b.png)

**Comment by rudrasingh21** [comment]
at Consumer Bot side:-

![image](https://user-images.githubusercontent.com/30667041/87883867-41513900-c9bf-11ea-8984-6329ab20d67b.png)

**Comment by rudrasingh21** [comment]
At Skill BOT Side:-

{
"$schema": "https://schemas.botframework.com/schemas/skills/skill-manifest-2.0.0.json",
"$id": "EmptyBot-0",
"name": "EmptyBot-0As-Skill",
"version": "EmptyBot-0As-Skill",
"publisherName": "EmptyBot-0As-Skill",
"endpoints": [
{
"name": "default",
"protocol": "BotFrameworkV4",
"description": "Production endpoint for SkillBot.",
"endpointUrl": "http://localhost:3980/api/messages",
"msAppId": "003eedb4-1991-403c-b848-9536ce1b5bb8"
}
],
"activities": {
"message": {
"type": "message",
"description": "A message activity containing the utterance that the skill will echo back to the user"
}
}
}

**Comment by rudrasingh21** [comment]
Could you please help me on this? I am expecting some quick help , as I know there is some config , I am missing .

**Comment by rudrasingh21** [comment]
Other way , I am getting below error:-

Error invoking the skill id: "003eedb4-1991-403c-b848-9536ce1b5bb8" at "http://localhost:3980/api/messages" (status is 500).

**Comment by rudrasingh21** [comment]
I also want to highlight another error which I am getting with other configuration is: -    

![image](https://user-images.githubusercontent.com/30667041/87884486-5b8d1600-c9c3-11ea-8b93-ecc1ed371ea5.png)

Error:-

![image](https://user-images.githubusercontent.com/30667041/87884529-9ee78480-c9c3-11ea-9977-16990e37b746.png)

**Comment by rudrasingh21** [comment]
Request you to help , please.

**Comment by tdurnford** [comment]
It looks like your 'Skill Host Endpoint' on the Skills page is set incorrectly. It should be something like `http://localhost:<port-number>/api/skills`.

![image](https://user-images.githubusercontent.com/17039790/87894301-9d3bb200-c9ff-11ea-922b-34efc95e0d00.png)

**Comment by rudrasingh21** [comment]
Hi ,

I tried using http://localhost:<port-number>/api/skills too

And getting same error, I share above.

And these both boys Skill and Consumer bot is running locally.


I HAVE NOT GENERATED APP ID AND PASSWORD FOR BOTH BOT BECAUSE I AM RUNNING IS LOCALLY.
I READ ONE MS document that it is not required .
When I used app id and password for consumer bot , it throws error 400 .

I really think it is not required for running both bot locally.

Still, DO YOU THINK , I NEED TO DO THAT IN THIS CASE ?

AND IF YES , can you share a doc for the same which I can follow.

**Comment by luhan2017** [comment]
@rudrasingh21 , you need appid and apppassword for both bots, caller and caller even run it locally, because we are using the appid and password for the authentication part.

**Comment by rudrasingh21** [comment]
Ok , Sure @luhan2017  :  a quick question:-

on --> You also need to generate app ids and passwords for both the parent and skill bots in the Azure portal.

Do i need to register for 2 different bot channel registration ?

Or same appid and apppassword for both bots?

**Comment by rudrasingh21** [comment]
And yes @luhan2017  on issue #3430 , that was not working son my windows machine , So I installed it on VM , Ubuntu machine.

Thanks for your support there.

**Comment by rudrasingh21** [comment]
I have created 2 bot channel registration on Azure . One for Skill bot and other for Consumer Bot.

In the Skill bot:-
In Bot Setting , I provided AppID and Pass which I generated on Azure portal (Bot channel registration)
 
As well , I provided AppID in manifest as well.

Now this Skill bot throws error when I am testing it in emulator

Skill Bot Manifest--->
![image](https://user-images.githubusercontent.com/30667041/87917320-6cf12380-ca92-11ea-9552-c264824e6e67.png)

Skill Bot Settings--->
![image](https://user-images.githubusercontent.com/30667041/87917728-08829400-ca93-11ea-8852-017ba6ff2a29.png)

Now , while testing even Skill bot in emulator , it is throwing Error:-

![image](https://user-images.githubusercontent.com/30667041/87917953-5b5c4b80-ca93-11ea-882c-75c3e4b8e7d1.png)

**Comment by rudrasingh21** [comment]
Kindly Help

**Comment by rudrasingh21** [comment]
Hi Team , Can we connect and resolve this issue .

**Comment by tdurnford** [comment]
@rudrasingh21 Unfortunately, yes. Even though you are running your skill, you still to generate different app ids and passwords for the parent and skill bots. 

In regard to the 400 error in the Emulator you are experiencing, can you try double checking all of your app id and passwords and restarting the conversation in the emulator a few times after you restart the bot? Sometimes it takes a few moments for the bot to start up and the emulator to connect to it correctly.

**Comment by rudrasingh21** [comment]
@tdurnford  :- I generated different app ids and password for Skill and Consumer bot.

Now when I am using AppID and Password in both bots respectively , even without adding up skills , bot is not responding , It is throwing 400 error all the time .

I tried it multiple time , but no luck.

**Comment by luhan2017** [comment]
@rudrasingh21 , could you double check if your bot port is updated after restarting? 400 usually means there is not a bot serving on that endpoint.

**Comment by rudrasingh21** [comment]
@luhan2017 : I have checked and tried multiple times.

Both bot ( using from template empty and echo bot ) individually works fine. As soon as , I use Microsoft app id and password . it starts throwing error 400.


When I am not using Microsoft app id and password and use skill bot in consumer bot , it throws error :-- " error invoking the skill id: “003eedb4-1991-403c-b848-9536ce1b5bb8” at “http://localhost:3980......................."

**Comment by luhan2017** [comment]
@rudrasingh21 , I have tried this locally, it works fine in my side, is there anything special in your environment? I have tried several scenarios which might cause issue, incorrect App password will get  401(unauthorized), querying an other endpoint will get 400. I wonder what is the timezone in your side? could we have a quick call on this?

**Comment by rudrasingh21** [comment]
Yes , Please . A quick call can help to resolve this . How can we connect ?

**Comment by rudrasingh21** [comment]
Even I created a fresh EmptyBot , which works fine when I am not using AppID and password , 

Once I use AppID and Password , It given me 401 error .

I crosschecked , I am using right AppID and Pass.

**Comment by rudrasingh21** [comment]
I would request you or anyone from your team to connect and check for this issue.

**Comment by luhan2017** [comment]
@rudrasingh21 , sorry for the late response, I am in Beijing, what time do you prefer for a call? Can we use Teams? you can setup a meeting with me (luhan@microsoft.com) or let me know your email address, I can try to setup a meeting.

**Comment by rudrasingh21** [comment]
My email address is rudrasingh21@hotmail.com , I don't have account on teams , I can use it if it allows guest.

Let me know your comfortable time , I will join.

**Comment by luhan2017** [comment]
@rudrasingh21 , I've send you a meeting invitation, please let me know if it does not work for you.

**Comment by rudrasingh21** [comment]
Thanks @luhan2017 , I have received meeting Invitation . Let's connect.

**Comment by rudrasingh21** [comment]
Thanks @luhan2017 for quick connect .It is working perfectly now after giving skillHostEndpoint .

A big thanks to you.

**Comment by Aavi2105** [comment]
Hi - I am working on similar above requirement and configured both skill bot and consumer bot , but getting below error when trying to call skill bot from consumer bot locally in emulator. 

Error is : Object reference not set to an instance of an object.

Please suggest if any configuration steps , I am missing. 

Note, I am using different appid/passwd for both skill bot and consumer bot. 

Thanks
Aavi

**Comment by Aavi2105** [comment]
Hi - I found that i did not add "- ${turn.activity.text}" in "connect to a skill" step , after adding this  "object Reference ....." error is gone, but getting below error , which is similar to what error came above. Please suggest what step I am missing in configuration setting. 

Error invoking the skill id: “3616df17-8c17-40b2-8247-968814832a3d” at “http://localhost:3979/api/messages” (status is 500).

Thanks
Aavi

**Comment by luhan2017** [comment]
@Aavi2105 could you double check the skillHostEndpoint in your parent bot ? It should be set to http://parentboturl/api/skills. Please let me know if it still not works.

**Comment by Aavi2105** [comment]
Thanks @luhan2017 for quick response. Yes, I am using the same format as you have mentioned. PFB screen shot.

![image](https://user-images.githubusercontent.com/68352642/88355691-1baf9100-cd2b-11ea-8e95-162c9657fc6a.png)

**Comment by Aavi2105** [comment]
@luhan2017 :- Just realized that skillhostendpoint should be consumer bot url, which I have given the skill bot endpoint url , which was incorrect. Just updated this to consumer bot url and it is triggering now. Thanks for your help.
