### ISSUE TITLE
Get the Job list from www.teamtailor.com API

### ISSUE THREAD

**Issue by shihanlk** [microsoft/BotFramework-Composer#3662]
## I have a problem to get specific values from json file.  
I have tried to resolve it using the method explained on https://github.com/microsoft/BotFramework-Composer/issues/3287 but failed. 

Basically I want to extract the value of "title"  from following format.

{}content
  []data
     {}0
      {}attributes
         title
    {}1
     {}attributes
        title
    {}2
      {}attributes
         title

The number of items under "data" is changing For example, it can be 0, 1 at one time next time it can be 0,1,2,3,4. 

I have tried to set property in several ways as below.

=foreach(dialog.api_response.content.data, x, x.value)
=foreach(dialog.api_response.content.data, x, x.key)
=foreach(dialog.api_response.content.data.attributes.title, x, x.key)
=foreach(dialog.api_response.content.data.attributes.title, x, x.value)
=foreach(dialog.api_response.content.data.attributes, title, title.value)

Nothing is successful.

**Comment by v-kydela** [comment]
Hello @shihanlk 

It's a little hard to understand what your data structure is just by looking at your post. Can you post a sample of some JSON you might be working with?

Also, I see that you've said "Nothing is successful" but that doesn't tell us what the actual observed behavior is. Can you show us what the results are of the 5 options you tried?

**Comment by shihanlk** [comment]
Hi @v-kydela 
1. This is the sample of json file I'm working with.

**Comment by shihanlk** [comment]
This could be resolved by =foreach(dialog.api_response.content.data, x, x.attributes.title)
