### ISSUE TITLE
Error message in modal after project deletion

### ISSUE THREAD

**Issue by nonnontrivial** [microsoft/BotFramework-Composer#3671]
## Describe the bug

If a directory containing a project is deleted and the project is edited afterward, an unclear error message can appear:

```
project 68384.6497895014 not found in cache
```

## Version

1.0.2

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a project
2. Remove the folder from the filesystem
3. Perform some change to the project
4. See modal with unclear error message

**Comment by hibrenda** [comment]
@VanyLaw be aware of the error message during "start bot". we need to provide more detail info.

**Comment by cwhitten** [comment]
@hibrenda moving to R11

**Comment by VanyLaw** [comment]
@hibrenda Seems like this issue happened during opening bot not starting bot. It's the error message popup in home page.

**Comment by EricDahlvang** [comment]
We will have this fixed in R11 (due to be released in November).

**Comment by boydc2014** [comment]
Let's refine the message to "path" doesn't seems to be exists anymore.
