### ISSUE TITLE
Managed LG/LU/Qna for customized actions

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#3673]
## Is your feature request related to a problem? Please describe.

Our managed LG/LU/Qna is built on top of a few assumptions in SDK and not consistently driven by schema. For example, copy\paste\move\undo\redo, or any other side effects can't be performed automatically. 

## Describe the solution you'd like

Revisit the design and implementation, to make sure 
1. How can we leverage schema to driven managed LG/LU/Qna
2. Make sure we consistently leverage the same machanism across every places

## Describe alternatives you've considered

related topics: schema driven, centralized side effects management.

**Comment by yeze322** [comment]
P2 in R12

**Comment by yeze322** [comment]
Dong please triage if it's still necessary and reassign, thanks!
