### ISSUE TITLE
Creating hero card dynamically and showing it as carousel using Composer

### ISSUE THREAD

**Issue by Mrinnaal** [microsoft/BotFramework-Composer#3674]
I am unable to understand or having no clue on how to create hero cards dynamically and show it as carousel. Can anyone tell me how to do it?

**Comment by luhan2017** [comment]
@Mrinnaal you can create a bot from RespondingWithCardsSample. 

Basiclly, you can use LG to generate a carousel as following:

# AllCards
[Activity
    Attachments = ${HeroCard()} | ${ThumbnailCard()} | ${SigninCard()} | ${AnimationCard()} | ${VideoCard()} | ${AudioCard()} | ${json(adaptivecardjson())}
    AttachmentLayout = carousel}
]

**Comment by Mrinnaal** [comment]
Yes! But dynamically i want to add the elements to the attachments variable. This will work, if we already have a static card in place. How to run a loop kind of thing, so that i can add those elements to attachments. Kindly help me on this. And, if you could provide a sample it would be really great.

**Comment by Danieladu** [comment]
hi @Mrinnaal Maybe I can provide a simple solution to see whether it can solve your issue.

```
> Suppose there is such data in memory: dataList
> [
>    {"title": "xxx1", "subTitle": "yyy1", "text": "zzz1", "buttons": ["a1", "b1"]},
>    {"title": "xxx2", "subTitle": "yyy2", "text": "zzz2", "buttons": ["a2", "b2"]}
> ]

# herocardsActivity(dataList)
[Activity
    Attachments = ${heroCards(dataList)}
    AttachmentLayout = carousel
]


# heroCards(dataList)
- ${foreach(dataList, x, herocardTemplate(x.title, x.subTitle, x.text, x.buttons))}

# herocardTemplate(title, subTitle, text, buttons)
[HeroCard 
        title=${coalesce(title, "")}
        subtitle=${coalesce(subTitle, "")}
        text=${coalesce(text, "")}
        buttons=${coalesce(buttons, [])}
]
```

**Comment by Mrinnaal** [comment]
@Danieladu bro! you are the hero 🥇 thank you so much! Was expecting this only!!

**Comment by stevgarcia** [comment]
Hello there, when you suggest to have a datalist, where should create it? in the common file?, can I use a list of images to create a carousel rather than a addaptative card with json?

**Comment by Danieladu** [comment]
hi @stevgarcia  

> when you suggest to have a datalist, where should create it? in the common file?


There are many ways to define/create the data. From Composer actions(like serProperties, HttpRequest, EditArray, SetProperties .etc.), Composer input(TextInput, ChoiceInput, Ask .etc.), Recognizers, or directly define in LG file, or in some json file and import by LG's function 'fromFile'. Define in common file is also ok.

> can I use a list of images to create a carousel rather than a addaptative card with json?

Yes, you can.
Try the code below:
```
> Suppose there is such data in memory: images
> ["http://1.jpg","http://2.jpg","http://3.jpg" ]

# herocardsActivity(images)
[Activity
    Attachments = ${heroCards(images)}
    AttachmentLayout = carousel
]


# heroCards(images)
- ${foreach(images, image, herocardTemplate(image))}

# herocardTemplate(image)
[HeroCard 
        images=${image}
]
```

**Comment by stevgarcia** [comment]
thanks for your answer, I tried something like this:

![image](https://user-images.githubusercontent.com/80296183/111568419-b6535900-876e-11eb-9283-15210017ce8f.png)

and I put this code in the common file, I´m using images from internet for test purpose:

# images
-```
{
  ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvGsxX6UfYEAkmgkIKhNDcHA8uCKLvS1Q2zg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBGR6d-lNhZHPU6jebJVm7DmMK69vgtZZzbQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRImeU7_FXyp3bxAOcMw5bzlElk_UVEhZjuvw&usqp=CAU" ]

}
    ```

# heroCards(images)
- ${foreach(images, image, herocardTemplate(image))}

# herocardTemplate(image)
[HeroCard 
        images=${image}
]

However im getting this error :

getWeather.en-us.lg:‘images’ evaluated to null. [heroCards] Error occurred when evaluating ‘-${foreach(images, image, herocardTemplate(image))}’. [SendActivity_lptRk7] Error occurred when evaluating ‘Attachments=${heroCards(images)}’. [__temp__e23cda8ce5ce4ff5a0af9d70d5d19000] Error occurred when evaluating ‘-${SendActivity_lptRk7()}’., getWeather.en-us.lg:‘images’ evaluated to null. [heroCards] Error occurred when evaluating ‘-${foreach(images, image, herocardTemplate(image))}’. [SendActivity_lptRk7] Error occurred when evaluating ‘Attachments=${heroCards(images)}’. [__temp__7b6c1ebb83f844a6a0b92c33b63b9cf4] Error occurred when evaluating ‘-${SendActivity_lptRk7()}’.

![image](https://user-images.githubusercontent.com/80296183/111568726-3da0cc80-876f-11eb-8a9d-c97ed4c9da10.png)

**Comment by Danieladu** [comment]
```
# images
-```
{
  ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvGsxX6UfYEAkmgkIKhNDcHA8uCKLvS1Q2zg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBGR6d-lNhZHPU6jebJVm7DmMK69vgtZZzbQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRImeU7_FXyp3bxAOcMw5bzlElk_UVEhZjuvw&usqp=CAU" ]

}
    ```
```

This template format is not right in multiline mode.
Replace it with :
```
# images
- ${
  ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvGsxX6UfYEAkmgkIKhNDcHA8uCKLvS1Q2zg&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBGR6d-lNhZHPU6jebJVm7DmMK69vgtZZzbQ&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRImeU7_FXyp3bxAOcMw5bzlElk_UVEhZjuvw&usqp=CAU" ]
}
```

**Comment by stevgarcia** [comment]
thanks for your answer, I tried in both ways, but I´ve got the same error:

![image](https://user-images.githubusercontent.com/80296183/112365558-cd7dd380-8ca5-11eb-95b8-775c7f9633be.png)



the other option:

![image](https://user-images.githubusercontent.com/80296183/112365698-f3a37380-8ca5-11eb-9943-9d80783de329.png)

![image](https://user-images.githubusercontent.com/80296183/112365601-d7073b80-8ca5-11eb-8d8c-6d99c8f90b54.png)

**Comment by Danieladu** [comment]
Change the template heroCards into:
```
# heroCards
- ${foreach(images(), image, herocardTemplate(image))}
```
Because `images` is a template, you should call it like a function, but not a variable directly.

**Comment by stevgarcia** [comment]
Thanks for your help, at the end it works with this code:

# heroCards(images)
-${foreach(images(), image, herocardTemplate(image))}

# herocardTemplate(image)
[HeroCard 
        images=${image}
]

**Comment by Danieladu** [comment]
Cool! actually, you can remove the parameter of `heroCards`,
`# heroCards(images)` => `# heroCards` is ok

**Comment by Samirun** [comment]
@Danieladu  
if each one of the carousel adaptive cards has a submit button can we know which card the user has selected from the carousel?
we have a scenario where the user selects a center currently, it's giving me an object reference error when I hit submit.

**LG used:** 

[Activity
    Attachments = ${json(centercardjson())} | ${json(centercardjson())}
    AttachmentLayout = carousel}
]

![image](https://user-images.githubusercontent.com/46156330/112785907-b444a080-9072-11eb-9be5-4ca6878e6caf.png)

**Comment by NikulDevis** [comment]
If I want to add text alongside the image, how do I change the code?

Also, how can i add buttons for this?

**Comment by raviraushanweb** [comment]
I am trying all of the above suggestions, but nothing is working for me. I am attaching screenshots below. 
<img width="255" alt="iss1" src="https://user-images.githubusercontent.com/41154960/128141776-14e66c2a-6d89-48a9-9427-29da9fa18261.PNG">

I am getting the above error
<img width="418" alt="iss2" src="https://user-images.githubusercontent.com/41154960/128141839-cd74b28b-b4e6-41cd-b0bc-44565383e561.PNG">

<img width="469" alt="iss3" src="https://user-images.githubusercontent.com/41154960/128141860-91ca7fd0-6028-475f-8c75-218491034646.PNG">

I really need help here. Any help is highly appreciated. Thanks

**Comment by Danieladu** [comment]
> If I want to add text alongside the image, what necessary changes are to be done on looping?

Maybe AdaptiveCard is more suitable for this case.

**Comment by raviraushanweb** [comment]
Yes, I will be using adaptive card, I am trying to figure out how this is working. even after copying same as the guys suggested above, it is not working for me. It's saying the images scope is not found.

**Comment by Danieladu** [comment]
@raviraushanweb 
The reason is that the response is not a normal "Text" response but a Card ttachment response.
Two steps:
1. Delete the template `HerocardActivity(image)` in "Bot response" editor.
2. Click here 
![image](https://user-images.githubusercontent.com/7289268/128150622-77437c1d-132a-4dbb-94a7-de4db8fee205.png)
and fill in the template body of your response. Like this:
![image](https://user-images.githubusercontent.com/7289268/128150888-cf6789c7-9f11-4737-b9f4-c7e6711b513e.png)


Or you can directly add the Attachment response here:
![image](https://user-images.githubusercontent.com/7289268/128151079-e8d76612-bbf9-4440-ba40-4662a4aecb94.png)


Thanks! 
Ping me if there still some problems.

**Comment by raviraushanweb** [comment]
Thank you @Danieladu for replying. I am still getting errors
This is template: 
<img width="471" alt="code1" src="https://user-images.githubusercontent.com/41154960/128152957-c59f458d-1504-4bed-bbd5-3fc0b44c795f.PNG">

When i am sending following response: 
<img width="594" alt="err2" src="https://user-images.githubusercontent.com/41154960/128153028-f99e26f4-6b59-4298-9281-0d2de5b2dd1c.PNG">
i am getting this error: 
<img width="247" alt="err2a" src="https://user-images.githubusercontent.com/41154960/128153080-7033ef08-8e0e-433b-8a90-460be3826829.PNG">
when I am sending following response:
<img width="576" alt="err3" src="https://user-images.githubusercontent.com/41154960/128153133-d57814bf-e42d-4557-8dae-e0fabbfd4e26.PNG">
I am getting this error: 
<img width="253" alt="err3a" src="https://user-images.githubusercontent.com/41154960/128153184-17194896-86c6-41c5-b6c1-b01adae55e93.PNG">

**Comment by Danieladu** [comment]
Why you change 
```
# heroCards
- ${foreach(images(), image, herocardTemplate(image))}

```
to

![image](https://user-images.githubusercontent.com/7289268/128155502-1b1ab46b-9ea7-4e7a-bedc-34c5f0ef82a3.png)

?
Keep the original one.

**Comment by Danieladu** [comment]
you could wrap the data with ${} to achieve the data.
For example, the data of "dialog.api_response.content.result" is 
```
[
{k1: 'v1', k2: 'v2'},
{k1: 'v3', k2:'v4'}
]
```

And you want to output the value of "k2" in first item, 
```
[Activity
 text = hi, the value of "k2" in first item is ${dialog.api_response.content.result[0].k2}
]
```

Finally you would get `hi, the value of "k2" in first item is v2`

**Comment by Danieladu** [comment]
You want to assign an array value to "dialog.images", but you could not push a whole array item into "dialog.images".
In the solution by you given, the value of  "dialog.images" is 
```
[
  [
  "image1",
   "image2",
  "image3"
  ]
]
```
But not 
```
  [
  "image1",
   "image2",
  "image3"
  ]
```
it is wrong, because you push all array into the first one.

Here are two ways to assign the array into "dialog.images".
The first way is to push one item each. So you could call three times of the "push array" operator.
The other simple way is to use "SetProperty" Action.
The screenshot:
![image](https://user-images.githubusercontent.com/7289268/128183539-ba8b749c-f22a-4979-a660-24bf2ae4c080.png)

**Comment by raviraushanweb** [comment]
Thank you so much @Danieladu . It is working now.

**Comment by Arthisekaran97** [comment]
Hello,

The bot need to accept all the inputs other than the options which we are choosing on the herocard in bot framework composer... the below img is hero card it's accepting the 1234,test. But it's not accepting the 06/09.2022,7th June dates...Any solution for this

![image](https://user-images.githubusercontent.com/102514342/172803561-59808a70-47ea-47a2-acb1-45bcf5dd74e9.png)

**Comment by KowsikRaviukumar** [comment]
Hi @Danieladu, how to add multiple attachments based on a condition like this and its not working

# getCardList()
- IF: ${ Condition)))}
  - ${getPromptsByCondition(data)}
- ELSE:
  - ${getEmptyOrPrompts(data)}

#getEmptyOrPrompts(prompts)
   - IF: ${Condition}
    - ${json(AdaptiveCard2(data))}
  - ELSE:
    - 

# getPromptsByCondition(prompts)
  - IF: ${Condition}
    - ${json(AdaptiveCard2(data))}|${json(Adaptivecard())}
  - ELSE:
    - ${json(Adaptivecard())}

**Comment by Danieladu** [comment]
> 

Please build the output in [Activity ] structure LG or [xxxCard ] structure LG

**Comment by KowsikRaviukumar** [comment]
> @KowsikRaviukumar
> 
> Please build the output in [Activity ] structure LG or [xxxCard ] structure LG

My response is
[Activity
Attachments= getCardsList()
AttachmentLayout= list
]
But its not working.

**Comment by Danieladu** [comment]
@KowsikRaviukumar 
change 
```
Attachments= getCardsList()
```
to 
```
Attachments= ${getCardsList()}
```

**Comment by HarishDesi** [comment]
Hi @KowsikRaviukumar While I was trying for dynamic carousel for adaptive card i was getting an error for it

# CarouselcardsActivity(dataList)
[Activity
    Attachments = ${foreach(dataList, x, json(x))}
    AttachmentLayout = carousel
]


# CarouselCards(dataList)
- ${foreach(dataList, x, herocardTemplate(x))}

# CarouselcardTemplate(x)
[Activity
Attachments = ${json(x)}
]

**Comment by Danieladu** [comment]
@HarishDesi please use "```" to wrap the lg content, the github would auto render the markdown text and make it unreadable.

And which template are you using, I just see three "not related" templates

**Comment by tixa332** [comment]
@Danieladu  I loved your explication and I need your help to understand how I can create a dinamically carousel with this data.

I have a property named dialog.MyData with this:
{
  "lgType": "Activity",
  "text": {
    "buttonName": [
      "Buy",
      "Buy",
      "Buy"
    ],
    "phone": [
      "Samsung Galaxy S23",
      "Iphone 14",
      "Xiaomi Redmi"
    ],
    "description": [
      "To amazing photos and compatibility with all devices",
      "Quality, speed and high technology of communication",
      "Lightness, design and functionality in the same phone"
    ],
    "images": [
      "https://www.worten.pt/i/7d5c24d3f1a453e0a1ba4311ee3723b9486c0c74.jpg",
      "https://www.worten.pt/i/8e35a20682daba99d4eda8f9e8d8ebece591db9c.jpg",
      "https://www.worten.pt/i/0a981572e19c5f7819a3e9020228abfea7f604e4.jpg"
    ]
  }
}

And eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeenow I tried to use the code below:

# herocardsActivity(MyData)
[Activity
    Attachments = ${heroCards(MyData)}
    AttachmentLayout = carousel
]

# heroCards(MyData)
- ${foreach(MyData, x, herocardTemplate(x.buttonName, x.phone, x.description, x.images))}

# herocardTemplate(button, phone, description, image)
[HeroCard 
        title=${coalesce(phone, "")}
        text=${coalesce(description, "")}
        buttons=${coalesce(button, "")}
	images=${coalesce(image, "")}
]

This doesn´t return an error but also does not present the information. Can you help me, please?
