### ISSUE TITLE
 getBaseUrl() called before serverPort is defined

### ISSUE THREAD

**Issue by iamjenetzler** [microsoft/BotFramework-Composer#3683]
I set the debug variable and tried running the exe from cmdline. And it errors out as seen in the attached screenshot

## Version

1.0.2
1.0.1

## Browser

- [X ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Set debug variable
2. Run the Bot Framework Composer.exe
3. See error

## Screenshots

![Annotation 2020-07-22 154145](https://user-images.githubusercontent.com/20113869/88236431-deb3a380-cc31-11ea-8590-746cacf03c38.jpg)

**Comment by tonyanziano** [comment]
Hi @iamjenetzler ,

Do you happen to already have an instance of Composer running when you are seeing this error?

I looked at the stack trace in your screen shot, and [the line that is throwing is only executed in the scenario in which you already have a running Composer instance, and then the application is opened / invoked a second time](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/electron-server/src/main.ts#L168).

I'm trying to reproduce it on v1.0.2 but can't seem to do it successfully.

**Comment by iamjenetzler** [comment]
Yesterday Srinaath fixed it by creating a %HOME% variable and a data.json file. I am demoing Composer at 4pm today but would be open to breaking it again afterwards so we can reproduce it. You can reach out to me on Teams if you want to try it. From: Tony AnzianoSent: Thursday, July 23, 2020 11:37 AMTo: microsoft/BotFramework-ComposerCc: iamjenetzler; MentionSubject: Re: [microsoft/BotFramework-Composer] getBaseUrl() called before serverPort is defined (#3683) Hi @iamjenetzler ,Do you happen to already have an instance of Composer running when you are seeing this error?I looked at the stack trace in your screen shot, and the line that is throwing is only executed in the scenario in which you already have a running Composer instance, and then the application is opened / invoked a second time.I'm trying to reproduce it on v1.0.2 but can't seem to do it successfully.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tonyanziano** [comment]
I'd be happy to try and debug it tomorrow. I'll send you a message on Teams.

**Comment by tonyanziano** [comment]
We tried to repro this but couldn't, and it seems like it is no longer present after a fresh install. Going to close this issue.
