### ISSUE TITLE
@ shorthand not working as expected in Composer 

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#3684]
## Describe the bug

@x is supposed to be refer to turn.recognized.entities.x, but not working as expected in composer. 

if i explicitly set turn.recognized.entities.x = hello world, then print  turn.recognized.entities.x it works fine, but  @x will throw an error.  like this 

"....en-us.lg:Exception has been thrown by the target of an invocation. [SendActivity_QrEzdV] Error occurred when evaluating ‘-${SendActivity_QrEzdV()}’. "

## Version

latest main

## Browser

- [x] Chrome

## OS

- Windows

## To Reproduce

Create an echo bot, and add two steps in unknown intent trigger,
1 set property to turn.recognized.entities.x
2 send response with ${@x}

## Expected behavior

expected @x works the same as turn.recognized.entities.x

## Screenshots

![image](https://user-images.githubusercontent.com/3829387/88251940-fe7fb180-cc9b-11ea-8a5e-6c1fddd0f05a.png)

the first send response works
the second didn't work

**Comment by zidaneymar** [comment]
Hi dong, according to the AtAtPathResolver.cs in botbuilder dotnet sdk, '@@' is the alias of 'turn.recognized.entities', so use '@@x'.

'@x‘ stands for 'turn.recognized.entities.x[0]' or 'turn.recognized.entities.x.first()'

Here are my test dialogs:
![image](https://user-images.githubusercontent.com/9328933/88260715-847d1600-ccf7-11ea-94cd-d33cbb11037f.png)

![image](https://user-images.githubusercontent.com/9328933/88260726-89da6080-ccf7-11ea-9dd3-7ed86481ef03.png)

**Comment by boydc2014** [comment]
@zidaneymar is there anything we can do to make the error message clear?

**Comment by zidaneymar** [comment]
> @zidaneymar is there anything we can do to make the error message clear?

Yes, I think the error message is not intuitive, I'm not sure if lg has the ability to pop up the details in evaluating the expression. I will confirm with hongyang.
