### ISSUE TITLE
Pointing to nonexistent folder on OS X Catalina versus Windows

### ISSUE THREAD

**Issue by bradrlaw** [microsoft/BotFramework-Composer#3695]
## Describe the bug

On OS X Catalina when setting the location for a project if you point to a non-existent folder and select create new folder, the app loses connection to storage and must be restarted.  On Windows, the app recovers from the error and just uses the previous directory.

The default location on OS X is the user's home folder:

/users/brad

If you change/edit the location to a non-existent folder such as:

/users/brad/composer

And hit create new folder, the app will throw the error "cannot connect to storage" and must be restarted to clear the error and display location information in this dialog window again.

On Windows, this does not throw the error and the application reverts back to the previous folder location.

## Version

Bot Framework Composer
                
                Version:  1.0.2
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS  10.15.6 (19G73)
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Move the application to the Applications folder
2. Open the application
3. Select Echo Bot from examples
4. In dialog window note the location is the user's home directory, append a folder that does not already exist
5. Hit create new folder
6. Observe the error

You can still create the project, but the location field / list never get displayed again until the application is restarted

## Expected behavior

Based on where the the create new folder option is located, I would expect it to create the new folder set in the location if it does not already exist.  I would also expect a button to open a system file browser dialog to navigate / locate an existing folder to select as the location (will make a separate feature request).

**Comment by zhixzhan** [comment]
I tried to reproduce this, but failed, the environment are:
Bot Framework Composer

                Version:  1.1.1
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

macOS 10.15.7

![Untitled](https://user-images.githubusercontent.com/49866537/94397670-e85c0900-0196-11eb-98a8-67c7bb020764.gif)

@bradrlaw Can you try at latest composer@1.1.1 see it still valid ?

**Comment by cwhitten** [comment]
@bradrlaw we'll close as unable to reproduce. let us know if you're still experiencing this.
