### ISSUE TITLE
RespondWithCardsSample example bot has broken link

### ISSUE THREAD

**Issue by bradrlaw** [microsoft/BotFramework-Composer#3698]
## Describe the bug

In the RespondingWithCardsSample the link for the audio card is broken.  The link: https://wavlist.com/wav/father.wav does not resolve and should be https://wavlist.com/wav/father.wav

## Version

Bot Framework Composer
                
                Version:  1.0.2
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0
              
## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Open composer
2. Select example RespondsWithCardsSample
3. Display the audio hero card (option 7)
4. Note no audio can be played

## Expected behavior

Expect a valid audio link. The link to the sample file desired appears to be: https://wavlist.com/wav/father.wav

**Comment by zxyanliu** [comment]
@bradrlaw thanks for reporting the issue. I think you mean
this link: http://www.wavlist.com/movies/004/father.wav
should be this: https://wavlist.com/wav/father.wav
