### ISSUE TITLE
Code view look and act more like a code editor?

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#3709]
## Is your feature request related to a problem? Please describe.
I lose my place when I switch between design view and code view. For example, if I'm in a specific trigger, when I switch to code view, the file is scrolled to the top of the dialog and it's hard to find the trigger in the code.

## Describe the solution you'd like
Can the code view have some things from code editors to make it easier to navigate?
- monospaced font
- collapsible { ... } and [ ... ] sections by clicking on the line numbers

When I switch to the code view, can the trigger I was looking at be scrolled to the top of the view? And if I selected any boxes on the canvas, can the corresponding sections of the code be selected?

**Comment by cwhitten** [comment]
Recommendation:

Have the "code" view connected to the left navigation such that clicking on a Dialog shows the entire dialog file, but clicking on a trigger inside of that dialog shows just the trigger data. This fits into existing IA quite well.

**Comment by mewa1024** [comment]
I think Consolas would be good. These are the fonts used on https://developer.microsoft.com/en-us/fluentui#/ for the monospaced type: 

"Segoe UI Mono", Consolas, "Andale Mono WT", "Andale Mono", "Lucida Console", "Lucida Sans Typewriter", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", "Liberation Mono", "Nimbus Mono L", Monaco, "Courier New", Courier, monospace;

**Comment by hatpick** [comment]
I have the following suggestions for the mono font:
FiraCode https://github.com/tonsky/FiraCode
Monoid https://github.com/larsenwork/monoid

**Comment by mewa1024** [comment]
@hatpick Was your suggestion for FiraCode and Monoid a recommendation because they are nice fonts or because you know of a problem with the font list used on https://developer.microsoft.com/en-us/fluentui#/ ("Segoe UI Mono", Consolas, "Andale Mono WT", "Andale Mono",  etc)?

I think if possible we should follow the fonts in microsoft.com since they been vetted. In any case, the current nightly is using a monospace that is too big and kind of wide:

![image](https://user-images.githubusercontent.com/39317542/108561488-32af6500-72b3-11eb-9a8b-975d20a91d64.png)

Can we also use 12px in both the LG editor and the code view of the .dialog?

**Comment by srinaath** [comment]
The font size needs to be standardized inside the LG editor and "Show Code" editor needs to be 14px.
