### ISSUE TITLE
Edit mode does not resize properly when shrinking window after growing it

### ISSUE THREAD

**Issue by bradrlaw** [microsoft/BotFramework-Composer#3710]
## Describe the bug

If you enlarge the composer window the edit area will grow to fill the space, but when the composer window is resized smaller the edit window stays the same size. If word wrap is enabled it remains stuck at the larger size and you cannot see / edit text that ends up off screen.

In addition Restart Bot / Test In emulator buttons stay off screen and it is impossible to scroll to them.  You have to leave edit mode for the UI to realign properly to make all controls / text visible again.

## Version

Bot Framework Composer
                
                Version:  1.0.2
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Bot Responses
2. Select Edit mode
3. Enlarge window
4. Shrink window
5. Notice controls are clipped and text edit area is off screen / not resized

## Expected behavior

Expect UI elements to resize when composer window is shrunk to remain visible

## Screenshots

![composerResizeBug](https://user-images.githubusercontent.com/10415799/88448226-74555b80-ce09-11ea-9143-53585e5fa857.gif)

**Comment by GeoffCoxMSFT** [comment]
@zhixzhan - My new splitter control should fix this bug, so assigning to myself.

**Comment by zhixzhan** [comment]
@GeoffCoxMSFT Awesome, thanks!
