### ISSUE TITLE
Test in Emulator becomes active before bot is actually ready to accept connections

### ISSUE THREAD

**Issue by bradrlaw** [microsoft/BotFramework-Composer#3728]
## Describe the bug

On OS X, the Test In Emulator button becomes active before the bot is ready to accept connections.  This causes the emulator to throw a Directline error.

## Version

Bot Framework Composer 
                Version:  1.0.2
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0
              
## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS 10.15.6 (19G73)
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot in Composer
2. Start the emulator
3. Press Restart Bot
4. Wait for Test in Emulator to be show
5. Press Test in Emulator after it becomes active quickly
6. Observe Directline error in emulator

## Expected behavior

Expect the emulator to be able to connect to the bot as the Test in Emulator button should not be active until the bot is ready to accept connections.

## Screenshots

<img width="1719" alt="Screen Shot 2020-07-28 at 5 40 44 AM" src="https://user-images.githubusercontent.com/10415799/88649076-9236f080-d095-11ea-89ae-b7c99d89d9cb.png">

**Comment by cwhitten** [comment]
Let's investigate for R11. 

I believe that while the runtime has started and sends a signal to Composer that it is ready, there is some pre-processing and startup logic that takes an amount of time before the runtime is truly ready to accept incoming connections.

**Comment by boydc2014** [comment]
Options:

1. pulling the message from composer side until it returns
2. access the default.html
3. any SDK built health check point

**Comment by cwhitten** [comment]
@luhan2017 can you investigate polling the webserver with an OPTIONS-like request to see if the endpoint is accepting connections yet, or something like this?
