### ISSUE TITLE
Exit Skill Bot while calling from PVA 

### ISSUE THREAD

**Issue by Aavi2105** [microsoft/BotFramework-Composer#3731]
Hi Team - I am facing below issue in skill bot. Please suggest what steps I need to add further to achieve this?

Issue is : I built one skill bot using Bot Composer to send adaptive card to PVA. In Skill bot, I am taking input using event activity (SampleAction) trigger from PVA and then binding the data to adaptive card and sending card to PVA as per dialog configured below. I am able to trigger this skill from PVA and getting adaptive card, but after getting the card in PVA, I am seeing skill is not exiting, and any further typing in PVA will giving the below error and going to escalate topic. I tried using end turn / end dialog in composer , but still getting the same error. 

Error :- Sorry, something went wrong. I am not able to help you at the moment, please check back later. Conversation ID: BtzkQK4eaJKH3hGA9PbAJq-f. Time (UTC): 7/28/2020 12:02:17 AM.

![image](https://user-images.githubusercontent.com/68352642/88681080-ce2e7d80-d0b6-11ea-9b4b-6ea377786551.png)

Thanks
Aavi

**Comment by v-kydela** [comment]
Hello @Aavi2105. I'd like to help and I have a few questions.

1. Would you kindly link to any documentation you've followed?
1. Would you kindly show us the rest of your Composer skill, perhaps by sharing the dialog files?
1. Have you tried using End Conversation instead of End Dialog?

**Comment by Aavi2105** [comment]
Hi Kyle :- Thanks for your response. 

As asked, PFB details .
1) I followed below links to create skill bot and created trigger of type event activity which I am calling from PVA.
https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill 
https://github.com/microsoft/BotFramework-Composer/issues/3421
2) Please find below dialog file. 
[echoskillbot.dialog.txt](https://github.com/microsoft/BotFramework-Composer/files/4990602/echoskillbot.dialog.txt)
3) I used end dialog and I don't see any option in composer for end conversation. Please suggest, how to use this, so that I can try it out.


Thanks
Aavi

**Comment by Aavi2105** [comment]
Hi @v-kydela :- Did you get a chance to look into this ? 

Thanks
Aavi

**Comment by v-kydela** [comment]
@Aavi2105 - Yes, you can read about using `endOfConversation` in a skill [here](https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-skill#to-continue-or-complete-a-conversation).

I am waiting on advice about how to do this in Composer.

@cwhitten - Can you advise?

**Comment by cwhitten** [comment]
The EndOfConversation activity should be sent from the Skill automatically and the caller needs to respond to it (in this case PVA). 

@sbacha does PVA do anything here on this event sent from the Skill?

**Comment by sbacha** [comment]
Hey, so if you have autoEndDialog set to true, the skill will automatically send an endofconversation when it hits the last node in your dialog flow.

If in the manifest you have resultValue set to some expected object, then you need to pass that object as part of the the end of conversation event.
You can do that in composer by going to DialogManagement -> End This Dialog 
End this Dialog has a property value, you need to set that value to the expected object you defined inthe manifest.

To debug this in PVA, in the test canvas check this out : https://docs.microsoft.com/en-us/power-virtual-agents/advanced-flow#troubleshoot-your-bot

The dialog file will give you information on what went wrong in that conversation.
If you have a missing variable that is expected to be returned to the PVA bot from the skill. You will see it that dialog file as expected variable missing.

**Comment by Aavi2105** [comment]
@v-kydela :- Thanks for your response. Yes, I referred this link yesterday and tried out giving multiple expressions in composer to end conversation, but unable to end the conversation. Hope we get updates soon on this.  

@cwhitten

**Comment by Aavi2105** [comment]
Thanks @sbacha for your response. I was setting the value property as setProperty({resultVale},'customerId',dialog.testproperty) in end dialog, which did not work. I just tried this setProperty({},'customerId',dialog.testproperty) and it worked. 
If manifest has resultValue defined, do we need to set the output always like this setProperty({},'propertname',Value) in end dialog property value?

**Comment by v-kydela** [comment]
@Aavi2105 - Are you saying you're putting the `setProperty` function as the value instead of just putting the value? I don't see any values passed to EndDialog in the dialog file you shared. Can you show what it looks like for you?

![image](https://user-images.githubusercontent.com/41968495/88958822-da9d0c80-d255-11ea-85a7-8631e1f8188a.png)

**Comment by Aavi2105** [comment]
@v-kydela , Sorry, I added that after the dialog file shared to you. PFB screenshot.

![image](https://user-images.githubusercontent.com/68352642/88961878-410c4400-d2c3-11ea-8721-2dd81184e553.png)

**Comment by v-kydela** [comment]
@Aavi2105 - What's your desired behavior? Is your skill meant to return a value or are you not trying to return anything? What happens if you just leave the value empty?

**Comment by Aavi2105** [comment]
@v-kydela :- Yes, Skill manifest files has input/output defined which demands output to be returned from Skill bot to PVA. If I set value property as empty then It does not end the skill conversation in PVA and I can see error message in dialog log file for  missing property [customerId] so it looks like if manifest file has output object defined then it is required to return value property in end dialog from Skill Bot.

**Comment by v-kydela** [comment]
@Aavi2105 - So your goal is to have the skill return an object with a `customerId` property?

`=setProperty({},'customerId',dialog.testproperty)` should work fine, but if you don't want to call that function you should be able to just return the object directly like this:

```json
{
  "customerId": "${dialog.testproperty}"
}
```

You can set the type to "object" instead of "expression":

![image](https://user-images.githubusercontent.com/41968495/89059887-df75c500-d316-11ea-8d74-e1052f67614e.png)

Does this resolve your issue?

**Comment by Aavi2105** [comment]
@v-kydela :- I tried above, but returning this "${dialog.testproperty}" instead of its value. I used this (={customerId:dialog.testproperty} and it is working fine.  We can close this ticket now.

Thanks all.
Aavi.
