### ISSUE TITLE
Proposal: Have a clear explicit indication that the bot is running after click "start"

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#3732]
## Suggestion
I click start on echo-bot and started the emulator but it fails.
It would have been useful to have some confidence that the bot is running by having a "running" indicator, maybe with the bot url displayed in the composer. First step in troubleshooting is to ensure the bot is running in this case so indicator would be useful.

**Comment by scheyal** [comment]
(also, I think it is insufficient to have an implicit "if Emulator button is available, then it is running")

**Comment by sangwoohaan** [comment]
This is very timely since I'm working on the start bot today :)  Yes I will include this.

**Comment by sangwoohaan** [comment]
This will be addressed in the upcoming release
