### ISSUE TITLE
NODE CONTEXT MENU: Add actions to Cut, Copy, Move, Delete, and Disable/Enable

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#3734]
## Suggestion
It is more intuitive to right-click context menu or discover actions on the node itself, rather than looking for buttons at a top menu.
For example, I wanted to move a node onto another arm of condition, and I ended up editing the code, didn't associate the top move/cut/copy buttons with the node.

**Comment by tonyanziano** [comment]
@mareekuh any input on this?

**Comment by yeze322** [comment]
For the use case 'discover actions on the node itself', we do have a design but not implemented yet
![image](https://user-images.githubusercontent.com/8528761/88997964-90825c80-d323-11ea-97d8-b0281f893625.png)


This menu is for operating the host action node, it means when clicking on a node's 'Move' menu, only that node will be moved.

**Comment by cwhitten** [comment]
@yeze322 let's hold off on this

**Comment by mareekuh** [comment]
@mewa1024  and @vivekkshankar

**Comment by mewa1024** [comment]
I agree that the actions are more intuitive on the ... menu. Would like to add them to the node (but leave them in command bar). Am changing the name of the issue to reflect this.

**Comment by mewa1024** [comment]
Yes. The context menu should have 
- Cut
- Copy
- Move
- Delet
- Disable (for nodes that are enabled. If the node is disable, the Enable control should be visible)

Same feedback as in #3950 and #4103. Closing those issues.
