### ISSUE TITLE
Composer on OS X creates many zombie helper processes the longer it is running

### ISSUE THREAD

**Issue by bradrlaw** [microsoft/BotFramework-Composer#3735]
## Describe the bug

Using composer on OS X and closing the primary window (but not the app as is the default OS X behavior) appears to cause many zombie Composer Helper processes to linger.  After about a day of on and off again use, over 120 processes were in the background consuming resources.

## Version

Bot Framework Composer     
                Version:  1.0.2
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS 10.15.6 (19G73)
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Start Composer
2. Open / Close / Work on various bots
3. Close window
4. Open composer window and repeat steps 2 and 3 several times
5. Open activity monitor or us ps to see the extra processes and resources being consumer (mostly RAM)

## Expected behavior

Expect processes to be cleaned up after program window close / closing bots.

## Screenshots

<img width="1689" alt="Screen Shot 2020-07-28 at 9 23 43 PM" src="https://user-images.githubusercontent.com/10415799/88746125-c48a3180-d119-11ea-9a27-4118b5eba6de.png">

**Comment by a-b-r-o-w-n** [comment]
@bradrlaw thanks for the issue. I have confirmed that we fail to properly manage a forked process when closing / re-opening the desktop app. I believe a fix will be pretty minor and hopefully we can get this addressed in the next release.
