### ISSUE TITLE
Feature: Support dark mode / custom themes

### ISSUE THREAD

**Issue by bradrlaw** [microsoft/BotFramework-Composer#3737]
## Is your feature request related to a problem? Please describe.

The app doesn't support the theme of the current OS and / or have the ability to change theme to something closer to what a user may prefer.

The Composer (and emulator) really stick out when the rest of the OS / apps are in dark mode.

## Describe the solution you'd like

Enable support for dark mode / user themes or inheriting the current OS theme (probably much harder).  Supporting basic themes or exposing the some CSS in settings for users to change would be great.  Approaches like this appear straightforward to implement and will allow the app to follow the OS theme:
https://medium.com/missive-app/make-your-electron-app-dark-mode-compatible-c23dcfdd0dfa

## Describe alternatives you've considered

Maybe an alternative is having a preferences / config file for the composer that could include CSS overrides.  But then it would have to be a manual switch to match the OS theme.

Only other option I see is users would have to change the source and rebuild the app.

**Comment by tonyanziano** [comment]
We will consider this in a future release due to current resourcing.

**Comment by tonyanziano** [comment]
We need to update the underlying version of ElectronJS before we can hook into the OS theme. After that we need to make sure our Fluent components apply the desired theme.

You can follow the process of upgrading Electron here: https://github.com/microsoft/BotFramework-Composer/pull/9053

**Comment by codyluth** [comment]
Any update on this feature since #9053 was merged?

**Comment by Alwinator** [comment]
Is there any news on this? Being blinded when working in the late hours with the Bot Composer makes me want to spend less money on our Azure deployment.

**Comment by cwhitten** [comment]
Hello @Alwinator & @codyluth - we do not have this change in an official release yet, however you are welcome to use the "nightly" feed and use a pre-release version of Composer: https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.1.2-nightly.326984.a27c3e5

**Comment by Alwinator** [comment]
@cwhitten I have installed the mentioned version and it is still in light theme. My Windows is set to dark theme and I don't find a Theme setting in the settings of Bot Composer.

**Comment by OEvgeny** [comment]
@Alwinator It appears that Composer nightly release mentioned above currently supports the [high contrast theme](https://support.microsoft.com/en-us/windows/turn-high-contrast-mode-on-or-off-in-windows-909e9d89-a0f9-a3a9-b993-7a6dcee85025) specified by the operating system, rather than the dark/light themes implemented in Windows 11. Sorry for any confusion this may have caused.

**Comment by Alwinator** [comment]
@OEvgeny Please since it is not implemented yet. Is there an option in the settings to enable high contrast just for MS Composer? Or can you automatically enable it if Windows is set to the dark theme?

**Comment by OEvgeny** [comment]
@Alwinator, as far as I know, the high contrast mode is only applied when it is turned on through WIndows settings. However, Electron has a feature that allows you to emulate forced-colors through the devtools. You can find more information on this here: https://devtoolstips.org/tips/en/emulate-forced-colors/

**Comment by Alwinator** [comment]
@OEvgeny The forced-color option is not shown (See screenshot). There is prefers color scheme option, but setting it to dark does not do anything. However, my Windows settings offer the option, but for all programs. Can you also enable high contrast if Windows is set to dark mode? Or add a setting to MS Bot Composer?

![image](https://user-images.githubusercontent.com/39517491/209774738-c7f2c699-7b00-46ca-a5f2-5ba4471bfaf1.png)

**Comment by OEvgeny** [comment]
@Alwinator It looks like the support for forced colors emulation was added in a newer version of Electron. Unfortunately, it is not possible to trigger the forced-colors theme from code as it is defined by the user's agent and cannot be adjusted like the dark/light theme.

**Comment by Godrules500** [comment]
It's only been about 3 months since this was updated, but are there any chances in the future? Just starting to use it, and the white is blinding! Even with f.lux and blue block glasses lol.
