### ISSUE TITLE
docs needed: how to build custom actions in an ejected runtime

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3739]
## Is your feature request related to a problem? Please describe.

Our documentation only covers how to turn on the included sample action, and does not cover the process of developing the C# class that implements the action or how these work.

## Describe the solution you'd like

We need to have a clear document about how to build the custom action class and how it works with the schema loading system.

**Comment by benbrown** [comment]
These docs from the SDK are relevant:

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialogs-declarative?view=azure-bot-service-4.0&tabs=csharp#creating-the-schema-file

**Comment by zxyanliu** [comment]
@luhan2017 can you provide some instructions to create a class for the custom action? Thanks! 
@hibrenda please if you have any suggestions on this?

**Comment by benbrown** [comment]
Thanks for the great work on this, @zxyanliu!!

**Comment by benbrown** [comment]
The updated docs can be found here:
https://github.com/MicrosoftDocs/composer-docs-pr/blob/master/composer-docs/how-to-add-custom-action.md

**Comment by zxyanliu** [comment]
The content is live. 
https://docs.microsoft.com/en-us/composer/how-to-add-custom-action
