### ISSUE TITLE
docs needed: what is inside the runtime and how can i use the ejected version

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3740]
## Is your feature request related to a problem? Please describe.

We do not clearly document what capabilities and structure of the runtime. 

## Describe the solution you'd like

We should provide documentation for the runtime such as:

* inline code documentation within the code itself
* A document explaining the configurable options
* A document explaining the build process for use outside of Composer
* Documents explaining the creation of custom actions

**Comment by zxyanliu** [comment]
This will be a separate topic about what it is, how to separately configure it, deploy it, etc.

**Comment by zxyanliu** [comment]
Chime @luhan2017 in to help on this topic.

**Comment by zxyanliu** [comment]
@benbrown Are we still working on this? Should we document the new runtime?
