### ISSUE TITLE
How to disable SDK sampling of Application Insights

### ISSUE THREAD

**Issue by kaiss-samkari** [microsoft/BotFramework-Composer#3742]
I'm using the BotFramework-Composer to build a very basic Bot. I only see a fraction of the events that are being generated by my bot. According to [this reference](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-troubleshoot-no-data) it is probably due to adaptive sampling. 
My question is: Is there a possible way to disable adaptive sampling using the composer, or by adding some code into the generated runtime?

**Comment by tonyanziano** [comment]
@scheyal can you take a look at this and provide some guidance please?

**Comment by dmvtech** [comment]
Take a look at how to enable fixed-rate sampling [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling#configuring-fixed-rate-sampling-for-aspnet-core-applications).


For example, if you're going off of our App Insights sample [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/21.corebot-app-insights), you would add the following 2 lines [in startup](https://github.com/microsoft/BotBuilder-Samples/blob/5954f40f30c71a38c5f1550db50d19b2a9c2427d/samples/csharp_dotnetcore/21.corebot-app-insights/Startup.cs#L29):

```
var aiOptions = new Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions();
aiOptions.EnableAdaptiveSampling = false;
```

And modify the line to pass in those options to the  AddApplicationInsightsTelemetry call:
`services.AddApplicationInsightsTelemetry(aiOptions);`

**Comment by tdurnford** [comment]
@scheyal Do you have any thoughts on this issue?

**Comment by ninggao** [comment]
@scheyal Do you have other thoughts on this?

**Comment by scheyal** [comment]
@garypretty  - more of your expertise.
