### ISSUE TITLE
Automatically overwriting LUIS models when you start a bot causes problems for multi-user scenarios

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#3747]
Following comments comes from the meeting hackathon.

- [x] **User scenario :** User edit the dialog flow in composer , restart the bot and test in emulator. every time with the restart user will get unexpected LUIS results.
same sentence will be pass for this time but may not be recognized for next time. This is painful because user don't know why it is.
**Root cause :** This is introduced by "**down sampling**" feature. Based on the utterance ratio for all the intent, "down sampling" will "random" remove the utterance 
for each intent during the luis publish if the ratio is greater than 1:10 (which is set in the setting page). 
**User's pain point :** 
1. don't aware the setting (document should not be the only way, how we let user know)
2. don't know whether the publish triggered down sampling as composer does not tell user 
   and people may always update their luis modal during development even it is correctly set at the beginning
3. don't like the random utterance drop

[mewa: downsampling was fixed by #5265]

----
- [ ] **User scenario :** Multiple user may work together for the same bot editing with same subscription key. 
User may checkout the code from github to their local environment.
During their local editing in composer and test, sometimes they will hit unexpected luis results.
**Root cause :** This is because lu modal will be override by someone else. 
**User's pain point :**
User use github to mange the bot code. so everyone will get their own local files during bot development.
User may not aware his/her own edit(development) to local luis will impact other's work. 
As the luis modal will be re-published with the same name. so the remote luis modal will be override and 
this will impact others if they are developing the same bot. 
The workaround is changing the luis name for local test or we could think about the luis publish for dev version or production version.

**Comment by sonjakn** [comment]
Thank you for documenting this!

**Comment by mewa1024** [comment]
@hibrenda is this issue still happening? Or did it get fixed in #5265?

**Comment by hibrenda** [comment]
@mewa1024 Downsampling issue fixed in #5256. but "Multiple user may work together for the same bot editing with same subscription key." is not fixed.

**Comment by mewa1024** [comment]
(seems like another workaround could be for each collaborator to use a different subscription. In any case, the underlying issue seems to be that how Composer interacts with LUIS is largely hidden from the user. Instead of being a seamless experience, it is confusing.)
