### ISSUE TITLE
click the send a response action will throw error

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#3749]
## Describe the bug
![bug](https://user-images.githubusercontent.com/39758135/88894127-00d4a380-d27a-11ea-931a-9a22f46d63b8.gif)

## Version
main branch

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. create a new echo-bot from samples
2. go to design page
2. Click on send a response action

**Comment by hibrenda** [comment]
not easy to repro. so may open it if we can repro.
