### ISSUE TITLE
Publish skill failed when skill custom runtime includes projects outside of skill

### ISSUE THREAD

**Issue by bobokids** [microsoft/BotFramework-Composer#3754]
## Describe the bug
Repro steps:
. enlist the who skill code from https://github.com/microsoft/botframework-skills/tree/preview-build2020/skills/declarative/whoskill
.  StartBot and then try to Publish the bot

Result:
Publish failed to build the whoskill\runtime\azurewebapp, as azurewebapp includes a share action project "Microsoft.Bot.Solutions.Extensions" outside of whoskill. This shared project didn't be copied when publish whoskill.
The folder structure of the declarative whoskill
    declarative\
        extentions\Microsoft.Bot.Solutions.Extensions
        whoskill\runtime

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by luhan2017** [comment]
custom runtime is deprecated.
