### ISSUE TITLE
The generated skill manifest should have at least a placeholder for the endpoints field

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3756]
## Describe the solution you'd like

When we generate a skill manifest, it does not include all the required fields. We should include placeholders at a minimum for all the fields necessary to publish a valid skill.

**Comment by tdurnford** [comment]
@benbrown This is being addressed with the changes requested in https://github.com/microsoft/BotFramework-Composer/issues/3380
