### ISSUE TITLE
Question - Get conversation ID

### ISSUE THREAD

**Issue by SattaRavi** [microsoft/BotFramework-Composer#3757]
We are trying to report on the bot usage by conversation's (analytics), i can access the dialog, user, conversation & this objects.

My requirement is to get the conversationID, but unfortunately the conversation object under value does not have the ID.

Any pointers on how to get the conversationID ?

![image](https://user-images.githubusercontent.com/6824787/89065381-64b1a780-d320-11ea-8cb1-6a3bbac0d569.png)

**Comment by luhan2017** [comment]
you can get the conversation id by this : turn.activity.conversation.id
It is here: 
![image](https://user-images.githubusercontent.com/32191031/89153060-bfeccf80-d596-11ea-91cc-2f249a76da01.png)

**Comment by SattaRavi** [comment]
@luhan2017 thanks this helped.
