### ISSUE TITLE
LG card definition and SDK card definition spec 

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#3758]
## Describe the bug

@EricDahlvang filed the issue which I cannot transfer to this repo. 
See: https://github.com/MicrosoftDocs/composer-docs-pr/issues/177

* Card definition in the [RespondingWithCard](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/plugins/samples/assets/projects/RespondingWithCardsSample/language-generation/en-us/common.en-us.lg) sample where the [doc](https://docs.microsoft.com/en-us/composer/how-to-send-cards) references the LG templates.
* The Bot Framework card definition [spec](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-protocol/botframework-channel.json#L1493).

## Additional context
Also impacting docs
- [ ] Composer doc: [Send cards](https://docs.microsoft.com/en-us/composer/how-to-send-cards)
- [ ] SDK doc: [Structured response template](https://docs.microsoft.com/en-us/azure/bot-service/language-generation/language-generation-structured-response-template?view=azure-bot-service-4.0)

**Comment by zxyanliu** [comment]
Asked @Danieladu for help. 
- The card definition schema in LG is slightly different from the card definition in SDK. 
- 'image' and 'images' fields are supported in all card definitions in LG.

**Comment by Danieladu** [comment]
Attach more info here:
I can explain the logic of LG about the image and images properties. In order for users to conveniently add image(s) into card, LG supports both image and images properties for all cards. The detail logic is:
1.if in herocard/thumbnailCard,  image/images would be converted to images array, for other cards the last property win, and the value would assign to 'image' property. 
2.if the value of image or images are plain string, LG would convert it into {url: xxx} structure, if you want to attach more detail info into the image structure, please avoid the plain text image value, instead, a structure value is recommended. For example: {"url": "xxx", "alt":"yyy"}
3.https://github.com/microsoft/BotFramework-WebChat/issues/3371  the templates suppose can work. Please make sure this fix is merged in composer: https://github.com/microsoft/botbuilder-dotnet/pull/4210

**Comment by zxyanliu** [comment]
@Danieladu thanks a lot! How about adding the following content in the docs? 

- LG provides some variability in card definition, which will eventually be converted be aligned with the SDK card definition. 
- For example, both ‘image’ and ‘images’ fields are supported in all the card definitions in LG.
- For HeroCard and Thumbnail cards, the values defined in either ‘image’ or ‘images’ fields will be converted to an images list.
- For the rest of the cards, the last defined value will be assigned to the 'image'/'images' field. 
- The values you assign to the 'image'/'images' field can be one of the following format: string, adaptive expression, or array in the format using `|`. 
	
**Examples:** 
If you define a HeroCard in LG like this: 	
```		
[HeroCard
   image = 1.jpg
   image = 2.lg | 3.lg
   images = 4.lg
   images = 5.lg | 6.lg
]
```
You will get the following:
```
[
  {"url": "1.lg"}, 
  {"url": "2.lg"},
  {"url": "3.lg"},
  {"url": "4.lg"},
  {"url": "5.lg"},
  {"url": "6.lg"}, 
]
```
If you define an AnimationCard in LG like this:
```		
[AnimationCard
   image = 1.jpg
   image = 2.lg | 3.lg
   images = 4.lg
]
```
You will eventually get 
```		
{"url": "4.lg"}
```

**Comment by EricDahlvang** [comment]
can we show other properties?  such as 'alt'?  how would one set that value for an image?

**Comment by Danieladu** [comment]
> can we show other properties? such as 'alt'? how would one set that value for an image?

Yes, sure. you can set 'alt' to image with structure result. 
There are several ways to achieve the result.
For example:

1.  Use Expression
```
[AnimationCard
        Title=Animation Card
        Image= ${{url:'https://xx.png', alt:'yyy '}}
]
```

2. Use `json` method
```
# card
[AnimationCard
        Title=Animation Card
        Image= ${json(imageResult())}
]

# imageResult
- ```{"url":"xxx.png", "alt":"yyy"}```
```

3. Use structure result
```
# card
[AnimationCard
        Title=Animation Card
        Image= ${structureImage()}
]

# structureImage
[MyImage
   url=xxx.png
   alt=yyy
]
```

**Comment by zxyanliu** [comment]
Closing this issue and keep track via: https://github.com/MicrosoftDocs/composer-docs-pr/issues/177
