### ISSUE TITLE
Start Bot has publishing error: applicationPublishObject.isStaging with value [object Map] must be of type boolean.

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/BotFramework-Composer#3759]
## Describe the bug

On a new bot (using ejected runtime with no changes), when I select **Start Bot** it begins the publish process of my LUIS apps but errors with `applicationPublishObject.isStaging with value [object Map] must be of type boolean.`

## Version

Main branch: commit #ba189031
## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot
2. Add simple luis recognizer and dialog
3. Select Start Bot

## Expected behavior

LUIS apps are created and publishes successfully.

**Comment by kellyhopkins** [comment]
I'm having the same issue

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/3764
