### ISSUE TITLE
Bot publish fails with LUIS authoring key: multiRecognizers.has is not a function

### ISSUE THREAD

**Issue by kellyhopkins** [microsoft/BotFramework-Composer#3762]
## Describe the bug
I created an empty bot and it ran fine locally, but once I added my LUIS key I started getting an error that says "multiRecognizers.has is not a function"

## Version

Release: 1.0.2
## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Design page
2. Click on 'Start Bot'
3. Add LUIS key

## Expected behavior

bot running on http://localhost:3979/api/messages
## Screenshots

![image](https://user-images.githubusercontent.com/20249556/89112052-b3983380-d42b-11ea-9a3e-d36ea9a13c47.png)

## Additional context

The publish error prevents the runtime from starting, but the publish creates the LUIS app in my account.
![image](https://user-images.githubusercontent.com/20249556/89112107-4b961d00-d42c-11ea-916b-f5df6133c5b4.png)

**Comment by zidaneymar** [comment]
fixed in pr https://github.com/microsoft/BotFramework-Composer/pull/3764 https://github.com/microsoft/BotFramework-Composer/pull/3785
