### ISSUE TITLE
Something went wrong in editing SendResponse for HeroCard

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#3771]
Reporting per message.
(ver Release: 1.0.2)

```
#StartSurvey
[Herocard
    title = ''
    subtitle = Hello. Help us improve our product. Please take our survey!  
    text = The survey contains 9 questions and should only take a few minutes.
    images = https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
    buttons = Start
]
```

![image](https://user-images.githubusercontent.com/8867670/89236904-b5d2cd00-d5a6-11ea-956e-0fe278697c3b.png)

**Comment by scheyal** [comment]
I know the form is wrong. Message might say something about wrong syntax maybe?

**Comment by yeze322** [comment]
I tried the json, removing the `#StartSurvey` can make it work

**Comment by zhixzhan** [comment]
If the only the syntax is error, it should not throw a pop up error. I'm not sure in this case is server down or not.
Anyway I'm adding error detail in popup window, if this continue happen, we can see more details.
