### ISSUE TITLE
Cross platform consistency audit (Marieke)

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#3794]
Known issues
- trigger icon
- dialog icon
- Publish icon
- bot responses icon
- user input icon
- skills icon

@sangwoo

Project: special forces

**Comment by cwhitten** [comment]
@mareekuh please use other labels to not pollute tracking on the engineering side

**Comment by cwhitten** [comment]
@mareekuh @sangwoohaan is this ticket still necessary? Please close if not
