### ISSUE TITLE
Add ability to add more than one OnIntent trigger for the same intent name

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/BotFramework-Composer#3796]
## Describe the bug

Today composer does not allow creation of more than one OnIntent trigger for the same intent. This is necessary especially when you are looking to add more than one OnIntent trigger with ones that are conditioned on specific entity recognition or a condition based on an expression.

The changes would be for composer to automatically validate intent names and pull in LU utterances if they were already defined rather than try to create a new intent for each Onintent trigger. 

@boydc2014

**Comment by cwhitten** [comment]
@vishwacsena because the triggers are executed in an array and the first trigger wins, the user will also need to re-order the triggers to put the most specific trigger first. we need some additional UX thinking. cc @mareekuh @sangwoohaan

**Comment by vishwacsena** [comment]
@cwhitten unless I'm missing something, we should by default be using the most specific selector which means the trigger with most conditions matching should win immaterial of the order. The selector should be picking up the first trigger only when there is more than one trigger with same level of conditions matching. If you are not seeing this, then there probably is a bug in the SDK.

**Comment by vishwacsena** [comment]
@cwhitten here's the logic - if multiple triggers fire (they have the same set of conditions) then 
a) the one with the highest priority is picked (if priority property is specified. Note 0 is the highest priority, -1 evaluates to false. Higher the number, lower its priority)
b) if no priority property is specified, then the first trigger in the order in which they were added to the adaptive dialog is picked.

Also, my 2c for design team for UX - If there are multiple triggers for the same intent name - 
- just name them IntentName, IntentName (1), IntentName (2) etc by default. 
- render the triggers in the order in which they are found in the dialog file. This will mean the first trigger will fire if all those triggers have the exact same set of condition.
- it should be possible to sort the triggers by `priority` if that property is specified.
- user should be able to update the trigger name.
