### ISSUE TITLE
Array data binding in adaptive card  (little similar to issue #3422)

### ISSUE THREAD

**Issue by sriget** [microsoft/BotFramework-Composer#3798]
Hi,
   This is similar issue related to #3422 , in Bot composer, I'm trying to databind the json array to columnset columns to the .lg file to generate a table structure. It is not working, but working in adaptive designer site. I wish that is supported in Bot composer as it is(since that is the highlighted feature of product). But you mentioned its not supported in native composer and gave some work around. I'm trying to generate a table with dynamic rows.  Is there any code workaround how to achieve that?

########Below is my SCHEMA  ###########:

![image](https://user-images.githubusercontent.com/35751420/89554535-9de09080-d7d4-11ea-8f57-75b5b4824aff.png)

###########JSON Data ########

![image](https://user-images.githubusercontent.com/35751420/89555812-1f84ee00-d7d6-11ea-9cdd-e66bf8391cfe.png)

############ Actual output in BOT emulator ########
![image](https://user-images.githubusercontent.com/35751420/89559817-c8821780-d7db-11ea-8fd9-84dbe3a057a6.png)

####### OUTPUT i need  and its working in Adaptive card designer, but not in composer #############

![image](https://user-images.githubusercontent.com/35751420/89555226-61f9fb00-d7d5-11ea-994a-39fa83d92377.png)

Please help on this or suggest available features in composer to achieve this. we will be using lot of table structures as bot response.

Thanks,
Sri

**Comment by cwhitten** [comment]
@sriget is the `content` parameter the JSON Data in your description?

This seems like it could be a gap in lg/expressions. @vishwacsena or @boydc2014 can you comment?

**Comment by sriget** [comment]
> @sriget is the `content` parameter the JSON Data in your description?
> 
> This seems like it could be a gap in lg/expressions. @vishwacsena or @boydc2014 can you comment?

yes @cwhitten . content parameter is the json data i posted. thanks for taking look on it so quick.

**Comment by vishwacsena** [comment]
@sriget as it was noted in #3422 adaptive card templating preview feature is not supported but you can achieve your desired outcome using language generation. Here is an example.

(remove the backslashes)

```markdown
# adaptiveCardTemplate()
[Activity
    Attachments = ${json(genAdaptiveCard(json(getProperties()).properties))}
]

# genAdaptiveCard (collection)
- ```
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        ${join(foreach(collection, item, getColumnSet(item.defaultPounds, item.variableWeight)), ',')}
    ]
}
\```

# getColumnSet (key, value)
- ```
{
    "type": "ColumnSet",
    "columns": [
        {
            "type": "Column",
            "width": "stretch",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "${key}"
                }
            ]
        },
        {
            "type": "Column",
            "width": "stretch",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "${value}"
                }
            ]
        }
    ]
}
\```

> This would come from your state. For now just emulating it via LG.
# getProperties
- \```
{
    "properties": [
        {
            "defaultPounds": "8000",
            "variableWeight": "0.10"
        },
        {
            "defaultPounds": "45000",
            "variableWeight": "0.15"
        },
        {
            "defaultPounds": "1900000",
            "variableWeight": "0.25"
        },
        {
            "defaultPounds": "45000",
            "variableWeight": "0.35"
        }
    ]
}    
\```
```

![image](https://user-images.githubusercontent.com/20918136/89685679-afe43100-d8b1-11ea-8a70-0c4858406f15.png)

**Comment by sriget** [comment]
Thank you @vishwacsena . This example is excellent to understand better. It works. Appreciate your quick response.

**Comment by zeusari** [comment]
Thank you @vishwacsena . Was struggling for more than a week for this.
