### ISSUE TITLE
How to Overlay bot developer in Composer on a .Net Application running on Production?

### ISSUE THREAD

**Issue by rudrasingh21** [microsoft/BotFramework-Composer#3799]
Hi Team , Can you suggest me how I can deploy ChatBot developed in Composer on my .Nat Application?

**Comment by v-kydela** [comment]
Thank you for the question, @rudrasingh21 

There's a document that explains how to publish in Composer here: https://docs.microsoft.com/en-us/composer/how-to-publish-bot

Closing as resolved.
