### ISSUE TITLE
Telemetry is not working with web based composer

### ISSUE THREAD

**Issue by kshyambabu** [microsoft/BotFramework-Composer#3800]
Hi, I am using the web based bot composer build by steps given in the link.
[https://docs.microsoft.com/en-us/composer/setup-yarn#build-composer-from-source](url)

And configured instrumenation key as per [https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0&tabs=csharp](url) 

But the telemetry is not saving. But, Its working fine if I use bot composer desktop application.

**Comment by zidaneymar** [comment]
Hi @kshyambabu , I can't reproduce this issue, I'm using Composer at commit 66f5d14a0122527714e25205151e9d2017833018.

Have you set your instrumentation key config in your customized settings?
```
"applicationInsights": {
        "InstrumentationKey": "<your key>"
    },
```

If you have set up this config, you could see the concrete activities in your application insights instance on azure.
![image](https://user-images.githubusercontent.com/9328933/89974870-d7af0c80-dc96-11ea-85c3-d7417d451d50.png)

**Comment by kshyambabu** [comment]
The reason is, I was using very old version of web based composer. I migrated the application to latest desktop chatbot composer. Then telemetry is working fine as said.
