### ISSUE TITLE
How to port application developed in web based composer to desktop application composer

### ISSUE THREAD

**Issue by kshyambabu** [microsoft/BotFramework-Composer#3801]
Since I am facing the issue #3800 about telemetry, I am trying to port the application to desktop based composer. But, the file structure is totally different between web based composer and desktop based composer. 
Desktop based composer is not recognizing the file structure of the web based composer.
Is there any tool or any other way to migrate the source to desktop based composer?

**Comment by tonyanziano** [comment]
Hi @kshyambabu ,

Are you trying to migrate a bot you created in the web version of Composer to the desktop version of Composer?

The two versions might differ in where your "default bot location" is, that being the location on disk where Composer stores your bot assets, however, the structure of these bot assets remain the same between the versions.

How are you trying to migrate the bot assets? You should be able to just open up Composer desktop, select "Open" in the top command bar, and point it to one of your bot folders created in Composer web.

**Comment by shyambabu-kolipaka** [comment]
I just found another issue which relates to my problem [here](https://github.com/microsoft/BotFramework-Composer/issues/3746)
