### ISSUE TITLE
Unable to parse sdk.schema in 4.10 preview packages

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#3807]
## Describe the bug

`Definition not found for Microsoft.Ask/properties/activity/oneOf/1/properties/membersAdded/items`

**Comment by QaisAlkhateeb** [comment]
I have the same issue after applying the steps here:
https://docs.microsoft.com/en-us/composer/how-to-add-custom-action

I have 4.9 packages.
![image](https://user-images.githubusercontent.com/25031218/90444359-692edc00-e0e6-11ea-8621-8ab3c34b6de3.png)

**Comment by QaisAlkhateeb** [comment]
I tried also the steps here (uninstall plugins +  install 4.10) and did not work:
https://github.com/microsoft/BotFramework-Composer/tree/main/runtime/dotnet/azurewebapp/Schemas

**Comment by a-b-r-o-w-n** [comment]
@QaisAlkhateeb We are working to address this issue in the CLI as well as looking at ways to mitigate in Composer.

**Comment by srudin** [comment]
Any solution to this?

**Comment by a-b-r-o-w-n** [comment]
@srudin What version of the SDK are you using?
