### ISSUE TITLE
Regression in LSP LG function evaluator & editing

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#3812]
<img width="618" alt="Screen Shot 2020-08-08 at 3 58 19 PM" src="https://user-images.githubusercontent.com/1156704/89721240-1b043500-d990-11ea-9d53-bff25a2cde1a.png">
<img width="861" alt="Screen Shot 2020-08-08 at 3 58 25 PM" src="https://user-images.githubusercontent.com/1156704/89721242-1c356200-d990-11ea-8d72-63575efcea6e.png">
<img width="1114" alt="Screen Shot 2020-08-08 at 4 00 00 PM" src="https://user-images.githubusercontent.com/1156704/89721250-425b0200-d990-11ea-9f4e-837208226db7.png">

**Comment by zhixzhan** [comment]
Addressed via #3816
