### ISSUE TITLE
Skill Response does not added to composer bot conversation in emulator

### ISSUE THREAD

**Issue by UmaPrelude** [microsoft/BotFramework-Composer#3823]
Hi,
I am using a middleware and messagerouter.sendtoconversationasync method, i am able to receive it in skill controller but the same is not listed in the bot response in emulator. 
If anyone can provide me some support, it is great.

**Comment by zidaneymar** [comment]
Hi @UmaPrelude , could you provide more details? You mention that you have set up your middleware, what kind of functionality does your middlerware provide? The bot doesn't reply anything but the message is received by SkillController, could your bot send the response successfully without configuring the middleware?

**Comment by UmaPrelude** [comment]
Hi @zidaneymar, 
Thanks for your response. I am trying to have transfer to human agent as a skill and trying to call from composer bot.
As part of that i am using messagerouter to send messages.
![image](https://user-images.githubusercontent.com/65938026/89893255-a3cfda80-dbf5-11ea-9fdd-8ef47ce9b8f1.png)
![image](https://user-images.githubusercontent.com/65938026/89893516-20fb4f80-dbf6-11ea-96b9-0a75fc037608.png)

I am able to pass an activity from composer bot to skill, able to process the skill and get back the response to skill controller sendtoconversationasync method of bot composer runtime.
But after this method is called nothing is happening. I am not able to see the response in the bot emulator window. 
I

**Comment by zidaneymar** [comment]
> Hi @zidaneymar,
> Thanks for your response. I am trying to have transfer to human agent as a skill and trying to call from composer bot.
> As part of that i am using messagerouter to send messages.
> ![image](https://user-images.githubusercontent.com/65938026/89893255-a3cfda80-dbf5-11ea-9fdd-8ef47ce9b8f1.png)
> ![image](https://user-images.githubusercontent.com/65938026/89893516-20fb4f80-dbf6-11ea-96b9-0a75fc037608.png)
> 
> I am able to pass an activity from composer bot to skill, able to process the skill and get back the response to skill controller sendtoconversationasync method of bot composer runtime.
> But after this method is called nothing is happening. I am not able to see the response in the bot emulator window.
> I

Could you please provide the manifest of your human agent skill? I set up a simple echo bot but can't repro this issue, Is that human agent skill developed by composer?

**Comment by UmaPrelude** [comment]
Hi @zidaneymar ,
The agent skill is not developed using composer. 
My issue is from skillcontroller -sendtoconversationasync method the activity is not added to main bot conversation. I can see the conversation id is different when it is send to this method since it is coming from skill and the skill conversation id is dynamically created by skill factory.

![image](https://user-images.githubusercontent.com/65938026/89987629-011e6700-dc9c-11ea-8c2e-65c2e56c00ac.png)

**Comment by zidaneymar** [comment]
@UmaPrelude , Is this agent skill a sample? Could I have a try on this agent skill, basically composer supports the skill developed by [botframework](https://github.com/microsoft/botbuilder-dotnet/), I'm not sure if composer supports calling other agent.

If you can share the link to this manifest or this skill itself ( set up instructions), it would be helpful for figuring out the reason.

**Comment by zidaneymar** [comment]
I debugged this on my machine with an simple echo bot sample as a skill, the response from the echo bot triggered this method (ReplyToActivityAsync).

![image](https://user-images.githubusercontent.com/9328933/89993067-c1b24380-dcb8-11ea-9f2e-600590b0a6f2.png)

**Comment by UmaPrelude** [comment]
> @UmaPrelude , Is this agent skill a sample? Could I have a try on this agent skill, basically composer supports the skill developed by [botframework](https://github.com/microsoft/botbuilder-dotnet/), I'm not sure if composer supports calling other agent.
> 
> If you can share the link to this manifest or this skill itself ( set up instructions), it would be helpful for figuring out the reason.

This skill is developed using bot framework, but not composer.
Since i am using sendtoconversation in message router it comes to sendtoconversation of skillcontroller, which is fine, but after that it is not working.

**Comment by zidaneymar** [comment]
> > @UmaPrelude , Is this agent skill a sample? Could I have a try on this agent skill, basically composer supports the skill developed by [botframework](https://github.com/microsoft/botbuilder-dotnet/), I'm not sure if composer supports calling other agent.
> > If you can share the link to this manifest or this skill itself ( set up instructions), it would be helpful for figuring out the reason.
> 
> This skill is developed using bot framework, but not composer.
> Since i am using sendtoconversation in message router it comes to sendtoconversation of skillcontroller, which is fine, but after that it is not working.

Not sure about the reason, maybe the skill is developed under an old version of bot framework.
I suggest to debug under botbuilder sdk and figure out what exactly happens after calling 'sendtoconversation '.

Here are the concrete steps:
1. Clone [botbuilder dotnet](https://github.com/microsoft/botbuilder-dotnet) repo.
2. Open Microsoft.Bot.Builder.sln
3. Click 'File' -> 'Add' -> 'Existing Project', and add 'Microsoft.BotFramework.Composer.Core' 'Microsoft.BotFramework.Composer.WebApp'
4. Remove the package dependencies of those two composer projects, then add 'Project Reference' to the botbuilder-sdk projects, this allow you to set breaking point in botuilder sdk and see what happens

The reference would look like this:
![image](https://user-images.githubusercontent.com/9328933/90087668-ead1e300-dd4f-11ea-9319-d4d504aa1159.png)

**Comment by UmaPrelude** [comment]
Thanks for your recommendation. I will check it.
