### ISSUE TITLE
Welcome greeting message not showing On load - composer bot hosted in Web chat channel

### ISSUE THREAD

**Issue by sriget** [microsoft/BotFramework-Composer#3826]
Hi
  This might be related to #1780 
  When I host the composer bot hosted in web chat channel directline, welcome greeting is not showing on load. But it shows in bot emulator. I'm using the latest composer v1.0.2  and below is the welcome dialog flow. 

![image](https://user-images.githubusercontent.com/35751420/89857325-602b9100-db61-11ea-9e2b-b28380fffe06.png)

If i remove that if/else branch , greeting is displayed twice, i see thats the fix in #1780 .  But is there any workaround to show the welcome greeting on load in web chat channel and in emulator both?  
 Any guidance will be appreciated.

Thanks,
Sri

**Comment by luhan2017** [comment]
@sriget, did you use secret or token to connect to web chat channel? This is by design that, if you are using the secret to connect to web chat channel, the OnConversationUpdate will be fired twice separately and the first one is when you open webchat, and MembersAdded is bot, the second one is then user first talk to bot, the MemberAdded is user. 

You could work around this by using token to connect to web chat instead of secret.

**Comment by eluchsinger** [comment]
@luhan2017 wow... do you have further documentation or How To's to use the token instead of the secret?

**Comment by eluchsinger** [comment]
Looks like I am using the token already, but the Bot still doesn't start the conversation when it's hosted in the Web Chat channel.

![image](https://user-images.githubusercontent.com/12324017/89885256-137ca000-dbcb-11ea-98b6-b852c23a9106.png)

**Comment by luhan2017** [comment]
@eluchsinger , did you run this step to get token by secret? https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0#generate-token  I am not sure the token you add here is secret or token? could you please double check?

**Comment by sriget** [comment]
> @sriget, did you use secret or token to connect to web chat channel? This is by design that, if you are using the secret to connect to web chat channel, the OnConversationUpdate will be fired twice separately and the first one is when you open webchat, and MembersAdded is bot, the second one is then user first talk to bot, the MemberAdded is user.
> 
> You could work around this by using token to connect to web chat instead of secret.

Hi @luhan2017 . I used directline secret key only.  let me try with access token and see. thanks for suggestion. !

**Comment by eluchsinger** [comment]
@luhan2017 I'm getting the token from that API endpoint dynamically. The bot does not start the conversation. Only after the user writes a message, the bot starts to text back...

![image](https://user-images.githubusercontent.com/12324017/89984872-65c8ca00-dc7a-11ea-8ca4-a0744aeeddb5.png)

**Comment by tdurnford** [comment]
@eluchsinger Please take a look at the Web Chat [Welcome Message](https://github.com/microsoft/BotFramework-WebChat/blob/master/docs/WELCOME_MESSAGE.md) documentation. It looks like you need to add a user id to the token request.

**Comment by gary-x0pa** [comment]
Looks like im facing this issue too. May i know how was it resolved?
