### ISSUE TITLE
Composer silently fails to bind to port for local testing

### ISSUE THREAD

**Issue by jgbolger** [microsoft/BotFramework-Composer#3836]
## Describe the bug
Composer is not starting the bot on the indicated port and is not providing any indication that a) there was a problem (it indicates success) and b) what the problem is

I can also see that there is no service bound to port 3979. I imagine this is Windows Defender possibly blocking the app from binding to the port but I have two issues here:

1. I don't know what process I need to unblock
2. I don't think Composer should silently fail in this manner, with no logging of the error

Can someone assist, please?

Thanks,
John

## Version
1.0.2

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce
1. Go to 'Composer'
2. Click on 'Start Bot'
3. Open Bot in emulator

## Expected behavior
If there is an issue binding the bot to a port, I would expect for that to be reported via Composer

## Screenshots
N/A

## Additional context
When I click "Start Bot", Composer appears to start up normally as developer console shows the API request completes successfully:
**{"id":"b49ca83f-62a2-4d00-8228-34fd35ad0c34","endpointURL":"http://localhost:3979","message":"Local publish success.","status":200}**

It then indicates that I can "Test in Emulator" on http://localhost:3979/api/messages

However, when I open the emulator, I get the following error
**[10:06:21]POST400directline/conversations/<conversationId>/activities**
{
  "error": {
    "code": "ServiceError",
    "message": "request to http://localhost:3979/api/messages failed, reason: connect ECONNREFUSED 127.0.0.1:3979"
  }
}

**Comment by cwhitten** [comment]
hi @jgbolger, when you see this in the Emulator, does clicking "Restart Conversation" in the Emulator after a few seconds successfully connect to the bot?

**Comment by jgbolger** [comment]
> 
> 
> hi @jgbolger, when you see this in the Emulator, does clicking "Restart Conversation" in the Emulator after a few seconds successfully connect to the bot?

Hi. No, this does not make a difference, as I can see using netstat that Composer does not actually bind to the port.

**Comment by cwhitten** [comment]
@jgbolger the team will investigate this in our upcoming sprint. Until then what Composer is attempting to do is fire up a `dotnet` process on your machine that starts a webserver on the the first port it sees as available. Why this mechanism is returning success with a 200 status we do not know at the moment.

**Comment by jgbolger** [comment]
Hi @cwhitten . OK, thanks for clarifying. If I gain any further insight, I will let you know.

**Comment by jgbolger** [comment]
Hi @benbrown, no unfortunately I wasn't able to resolve. I since had to exchange work laptop so this issue is no longer occurring for me. Cheers, John

**Comment by cwhitten** [comment]
This will be addressed in our upcoming release.
