### ISSUE TITLE
Data Binding doesn't work with array in FactSet

### ISSUE THREAD

**Issue by NinjaCookie03** [microsoft/BotFramework-Composer#3838]
I have a JSON Object where I restructure in the BotFramework Composer. 
![Dialog](https://user-images.githubusercontent.com/44618760/90136522-91c87600-dd74-11ea-8f97-759ca035abd4.jpg)

In the Adaptive Card I set the array dialog.carddata to "$data:".
![AdaptiveCardView](https://user-images.githubusercontent.com/44618760/90136542-9ee56500-dd74-11ea-965b-f4801e15773a.jpg)

But I get this error message in the Bot Framework Emulator due to the FactSet in the Adaptive Card.
![Error-Message](https://user-images.githubusercontent.com/44618760/90136554-a3118280-dd74-11ea-9243-fe08dd36c7fe.jpg)

Does anyone know how to fix this problem and can help, please?

**Comment by cwhitten** [comment]
@NinjaCookie03 where are `key` and `val` coming from? Please see https://github.com/microsoft/BotFramework-Composer/issues/3798 for additional support and let us know if you are still having trouble.
