### ISSUE TITLE
Value cannot be null. (Parameter ‘uriString’) upon calling a Skill

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/BotFramework-Composer#3840]
## Describe the bug

I created a Skill using Composer and it gets successfully added to the Consumer bot (created by Composer as well). However, I am not able to connect as it gives me an error as soon as it hits the Skill caller. 

## Version

1.0.2

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Add a Skill
2. Call a Skill from Consumer

## Expected behavior

It should work and call my Skill and Skill should respond back

## Screenshots

**Skills Manifest**

![image](https://user-images.githubusercontent.com/16351038/90141564-9dd92580-ddbe-11ea-99ba-4d4e8b9b0898.png)

**Consumer Bot**

![image](https://user-images.githubusercontent.com/16351038/90141736-e0026700-ddbe-11ea-8e94-62d50aa68c97.png)

**Error in Emulator**

![image](https://user-images.githubusercontent.com/16351038/90141800-f14b7380-ddbe-11ea-84dd-20bdd370acaf.png)

What am I doing wrong?

**Comment by cwhitten** [comment]
@arafattehsin Testing Skills locally requires registering both the calling bot and the skill with the Azure Bot Service channelge registration, and requires both the msAppId and the msAppPassword to be set locally in the Bot's settings. It also requires ngrok to be running locally, as communication goes through the channel service in this scenario. Have you done all these things and still are seeing the issue?

**Comment by arafattehsin** [comment]
Hi @cwhitten thanks for the prompt response. 

I have not done this at all. I thought local skill would work fine (as seen in one of your demos during Build) but happy to try this way. I do have one Skill hosted on Azure which I can try to connect using ngrok.

**Comment by cwhitten** [comment]
Ok. Scope this document for what is needed currently: https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill

Testing Skills locally is a pain point that we're working to improve in the SDK. We aim to reduce this friction significantly in an upcoming Bot Framework release.

**Comment by arafattehsin** [comment]
Thanks! I'll definitely consider this.

**Comment by arafattehsin** [comment]
@cwhitten Thank you for the pointer, I managed to get it working. Although, I'm preparing some improvements to the existing docs and will submit a PR (they need an update ;))
