### ISSUE TITLE
[electron][mac] unable to copy/paste in desktop Composer

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#3842]
## Describe the bug

On Mac, I am unable to copy or paste in the desktop window.

## Version

`1.0.2-nightly.156397.5ebecd7`

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by zhixzhan** [comment]
I can repro this, when use keyboard `cmd-c` + `cmd-v` :
<img width="1692" alt="image" src="https://user-images.githubusercontent.com/49866537/90206530-76ae4280-de16-11ea-8fa3-3f0bb75a6163.png">

ps: toolbar `copy`-`paste` works fine.

**Comment by a-b-r-o-w-n** [comment]
Good catch @zhixzhan. I didn't think to try the menu, just using cmd.

**Comment by tdurnford** [comment]
Related to https://github.com/microsoft/BotFramework-Composer/issues/3844
