### ISSUE TITLE
Upgrade from 1.02 to latest shows warnings that seem benign or misleading

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#3853]
## Describe the bug
Upgraded to nightly build. Using a composer bot pointing to skills.

## Version
Daily build (8/14)

## Browser
- [ X] Electron distribution

## OS
- [ X] Windows

## To Reproduce

Upgrade to latest with a bot using skills.

## Screenshots

![composerwarn2](https://user-images.githubusercontent.com/8867670/90429390-7dd58a80-e07a-11ea-8df8-b241e8bd545b.png)

![composerwarn](https://user-images.githubusercontent.com/8867670/90429379-77dfa980-e07a-11ea-88a3-452d9742b8e6.png)

---

{
  "feature": {
    "UseShowTypingMiddleware": false,
    "UseInspectionMiddleware": false,
    "RemoveRecipientMention": false
  },
  "MicrosoftAppPassword": "asdf",
  "MicrosoftAppId": "000ad8f3-asdf-asdf-asdf-asdfasdfasdf",
  "cosmosDb": {
    "authKey": "",
    "collectionId": "botstate-collection",
    "cosmosDBEndpoint": "",
    "databaseId": "botstate-db"
  },
  "applicationInsights": {
    "InstrumentationKey": ""
  },
  "blobStorage": {
    "connectionString": "",
    "container": "transcripts"
  },
  "luis": {
    "name": "",
    "authoringKey": "",
    "authoringEndpoint": "",
    "endpointKey": "",
    "endpoint": "",
    "authoringRegion": "westus",
    "defaultLanguage": "en-us",
    "environment": "composer"
  },
  "publishTargets": [],
  "qna": {
    "knowledgebaseid": "",
    "endpointkey": "",
    "hostname": ""
  },
  "telemetry": {
    "logPersonalInformation": false,
    "logActivities": true
  },
  "runtime": {
    "customRuntime": false,
    "path": "",
    "command": ""
  },
  "downsampling": {
    "maxImbalanceRatio": 10,
    "maxUtteranceAllowed": 15000
  },
  "botId": "",
  "skillHostEndpoint": "http://asdfasdf.ngrok.io/api/skills",
  "skill": [
    {
      "manifestUrl": "http://localhost:3979/manifests/SurveyBot-2-1-preview-1-manifest.json",
      "name": "SurveyBotSkill"
    },
    {
      "manifestUrl": "https://asdfasdf.azurewebsites.net/wwwroot/echo-bot-manifest.json",
      "name": "EricEchoSkill"
    }
  ],
  "defaultLanguage": "en-us",
  "languages": [
    "en-us"
  ]
}

**Comment by hibrenda** [comment]
This may related to https://github.com/microsoft/BotFramework-Composer/issues/3849
