### ISSUE TITLE
Input only works through entity

### ISSUE THREAD

**Issue by michael0ren** [microsoft/BotFramework-Composer#3855]
I was trying to make a variable that was set through a previous entity, and if not, set by the user.
I made user input and set value to be the entity.
When the entity is provided, it automatically sets it, but when the entity is not, it asks the user until the max turn count is reached and then returns null, regardless of the input sent by the user.

**Comment by zxyanliu** [comment]
What version of Composer did you use?

**Comment by michael0ren** [comment]
I used the mac version 1.0.2

**Comment by cwhitten** [comment]
Hi @michael0ren 

Please visit https://www.youtube.com/watch?v=dUT8L4_bVrk for an explanation on extracting entities from prompts.
