### ISSUE TITLE
MICROSOFT BOT COMPOSER: Bug while loading an existing bot

### ISSUE THREAD

**Issue by anemit** [microsoft/BotFramework-Composer#3863]
I get a white screen when I try to load an existing bot in Microsoft bot composer. I re-installed the framework but nothing changed.

**Comment by anemit** [comment]
I tried other bots and works fine, but I still get the "white screen" with the first one.

**Comment by cwhitten** [comment]
Hi @anemit - this is unexpected and we cannot reproduce. Are you able to upload your bot assets of the bot that won't load to this issue?

**Comment by pavolum** [comment]
Closing this as it is stale. Feel free to reopen if your issue persists.
