### ISSUE TITLE
Can't add a flow with Adaptive card submit event.

### ISSUE THREAD

**Issue by GowthamDisys** [microsoft/BotFramework-Composer#3875]
I am currently using bot composer for my chatbot. When I tried to get the value from Adaptive card input value on clicking submit, I am unable to get the response data back. Can you guys add the flow in bot composer for getting the response back from Adaptive card input.

**Comment by GowthamDisys** [comment]
> There is a second approach which doesn't require a bogus intent handler. You can map the submitted card to a custom event.  Instead of a hidden `intent` field add a hidden `event` field with the name of the custom event you want triggered.  Then in your bot you'll want to add a "Message Received" trigger:
> 
> ![](https://user-images.githubusercontent.com/698939/90924387-33b71680-e3a4-11ea-8c02-747fc748fc2a.png)
> 
> You'll need to add a condition to your trigger that prevents it from firing unless the message has a value with an event name:
> 
> ![](https://user-images.githubusercontent.com/698939/90924523-7b3da280-e3a4-11ea-9872-887ec7b1db0f.png)
> 
>  Then just add a "emit a custom event" action to trigger the event.  
> 
> ![](https://user-images.githubusercontent.com/698939/90924605-a2946f80-e3a4-11ea-8f02-df13c64b775a.png)
> 
> Your event will trigger and you can get the submitted fields from `turn.activity.value`.

Hi @Stevenic ,

This method works fine.  Thanks!

**Comment by GowthamDisys** [comment]
> Thank you for the question, @GowthamDisys. I would like to help, but I need some more information.
> 
> 1. Please post your Adaptive Card JSON
> 2. What channel are you using?
> 3. What do you mean by "add the flow"?

Hi @v-kydela ,

1. I have added the JSON below.
[sampleAdaptiveCard.txt](https://github.com/microsoft/BotFramework-Composer/files/5117150/sampleAdaptiveCard.txt)

2. I am using WebChat Channel.

3. I mean to say, I have added the adaptive card by adding "Send a response".
![image](https://user-images.githubusercontent.com/62953969/91033130-86046b80-e620-11ea-8810-e57384d10aef.png)

I need to wait for the user submit event in adaptive card to get their input, So, Can you add a flow in composer like, ask a question-> Adaptive submit -> Finally get response from the user.

![image](https://user-images.githubusercontent.com/62953969/91033332-d24fab80-e620-11ea-8cc4-1ac4084f6c8a.png)

The method that @Stevenic told above, seems to be working, but it is a kind of workaround for this issue. It will be better if you could add the functionality within the existing flow. (Ask a question)

Thanks,
Gowtham

**Comment by v-kydela** [comment]
@GowthamDisys - It may be possible to get your desired behavior to work using existing inputs (like a text input) if you use custom validation rules. It would still likely be considered a workaround since you'd have to intercept the incoming message with a Message Received trigger and modify it so that the input would recognize it.

**Comment by v-kydela** [comment]
@GowthamDisys - We appreciate the feature request, but it looks like this isn't going to be built into Composer anytime soon. The team may reconsider if more customers express interest in it. For now you can use a workaround.
