### ISSUE TITLE
storage.ts compilation error

### ISSUE THREAD

**Issue by pcreehan** [microsoft/BotFramework-Composer#3877]
There's a compilation error I'm getting in Composer\packages\server\src\controllers\storage.ts on line 54:
`    const reqpath = decodeURI(req.query.path);`

Argument of type 'string | ParsedQs | string[] | ParsedQs[]' is not assignable to parameter of type 'string'.
  Type 'ParsedQs' is not assignable to type 'string'.ts(2345)

Potential fix:
`    const reqpath = decodeURI(req.query.path as string);`

**Comment by pcreehan** [comment]
Looks like one from 45 days ago: https://github.com/microsoft/BotFramework-Composer/commit/2cedeac2286e75f0ad86d417a57e6a1a4fe5e332 
but that appears to be the latest for master. Should I be using main instead?

**Comment by cwhitten** [comment]
Yes, we've changed the main branch to be `main` instead of `master`. This shouldn't be your issue, though.  Let me know you findings.

**Comment by pcreehan** [comment]
Switching to main resolved it. The code looks the same and it still gets red underlined, but it doesn't block the build. Thanks.
