### ISSUE TITLE
syntax check for inline lg editing and common.lg 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#3884]
- Use new LG Template(not defined in LG file)  in SendActivity
- Notification will complain error (expected)
- Add this new LG Template in All ( in common.lg) 
- Notification status won't change

Workaround: manually edit in corresponding LG file can fix the notification sync. 
Root cause : common.lg has been referenced in each dialog.lg file. But update in common.lg will not trigger lg parse.

**Comment by benbrown** [comment]
Another way this occurs:

* Add new rules in the common.lg file
* Use them in sendactivity - they will be marked as invalid even though they already exist
* Error notifications will only go away if the project is reloaded from disk
