### ISSUE TITLE
Edit Publish Profile triggers error 'e.types.map is not a function'

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/BotFramework-Composer#3888]
## Describe the bug

When a publishing operation fails due to an expired access token, attempting to edit the corresponding publish profile initially causes an error modal to pop up, indicating an 'e.types.map is not a function' exception. Closing the modal and attempting to edit the same publishing profile then successfully displays the 'Edit a publish profile' modal.

## Version

v1.0.2-nightly.159851.f01f6db

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a project in Composer that contains a publish profile with an expired access token.
2. Navigate to the Publish tab, select the publish profile with the expired access token, and click 'Publish to selected profile'.
3. Wait for the publish operation to fail with the following message: "Type: BadArgument, Message: Failed to use the access token provided: The access token expiry UTC time '8/24/2020 12:02:22 AM' is earlier than current UTC time '8/24/2020 5:49:21 PM'., run az account get-access-token, then replace the accessToken in your configuration"
4. Open the publish profile's context menu, then select Edit.

## Expected behavior

The 'Edit a publish profile' modal is successfully rendered.

## Screenshots

![image](https://user-images.githubusercontent.com/53846082/91079817-6ad23580-e5f9-11ea-8a97-d0daf8ceea00.png)

## Additional context

None.

**Comment by VanyLaw** [comment]
I think it was fixed in this PR. https://github.com/microsoft/BotFramework-Composer/pull/3885. @peterinnesmsft could you have a try?

**Comment by hibrenda** [comment]
Close is as it has been addressed. @peterinnesmsft if you hit it later, feel free to open it.
