### ISSUE TITLE
there is no locale fallback for en-us

### ISSUE THREAD

**Issue by cdonke** [microsoft/BotFramework-Composer#3902]
## Describe the bug

Trying to run bot composer via docker. 
cloned the main branch, ran docker-compose build, then docker-compose-up.

Created an echo bot, no modifications done. when connected via bot emulator (4.10.0), it responds with

> echobot-0.en-us.lg:[Error] line 1:0 - line 1:21: there is no locale fallback for en-us

## Version
Version 1.0.2, built from the master branch,
commit 8c03c1e1ec5a8102fc1494cf29e53fca920cebb0 (HEAD -> master, tag: v1.0.2)

## Browser
MS Edge Version 84.0.522.63 (Official build) (64-bit)

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ X ] Ubuntu **20.04 - docker running under WSL2 + Docker for Windows**

## To Reproduce

1. docker-compose build
2. docker-compose up
3. Open //127.0.0.1
4. Create a new EchoBot - doesn't matter the path
5. Start Bot and Run on emulator (ngrok required)

## Expected behavior
Welcome user message sent.

## Screenshots
![image](https://user-images.githubusercontent.com/4707327/91313431-c2080f80-e78b-11ea-96a9-ed3f15e397ea.png)
![image](https://user-images.githubusercontent.com/4707327/91313774-275c0080-e78c-11ea-9881-6a04a3464eb2.png)

## Additional context
Had to twerk a little with docker-compose.yaml to make it work... Mainly to the runtime volumes mapping...

```version: "3"
services:
  composer:
    build: Composer
    ports:
      - "3000:3000"
      - "3979-5000:3979-5000"
    volumes:
      - ~/Documents/Composer:/Bots
      - ./runtime:/runtime      ##### HAD TO CHANGE HERE
      - ./runtime:/app/Composer/runtime   #### AND HERE
      - ./.appdata:/appdata
      - ./Composer/plugins/localPublish/hostedBots:/app/Composer/plugins/localPublish/hostedBots
    environment:
      COMPOSER_BOTS_FOLDER: /Bots
      COMPOSER_RUNTIME_FOLDER: /runtime
      COMPOSER_APP_DATA: /appdata/data.json
      PORT: 3000
      BOT_ENDPOINT: http://0.0.0.0:3979
```

**Comment by cwhitten** [comment]
@cdonke is this issue fixed by making those changes to docker-composer.yaml?

**Comment by cdonke** [comment]
the docker-compose fixed the emulator not starting when in dockers

**Comment by cdonke** [comment]
i just figured out that when published I have only:
- common.en-us.lg
- echobot-0.en-us.lg

I manually copied the files without the locale:
- common.lg
- echobot-0.lg

And it worked...
Now I'm a bit lost where should I touch to fix this...
Not sure if related to the creation of the project or the localPublish plugin...

Still investigating.

**Comment by cwhitten** [comment]
@cdonke any updates?

**Comment by cdonke** [comment]
Closing as not reproduceable anymore...
