### ISSUE TITLE
Unable to use bots built with LUIS (401 or 403 status)

### ISSUE THREAD

**Issue by nitroin** [microsoft/BotFramework-Composer#3904]
# Describe the bug

Unable to use bots built with LUIS.

## Version

v1.0.2-nightly.160791.78429de

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

Appendix:
a. Create a Languange Understanding service from Azure, West Europe region.

1. Go to 'New'
2. Click on 'Create from template'
3. Select 'Todo with LUIS'
4. Click 'Next'
5. Click 'Ok'
6. Click 'Start Bot'
7. Provide the mandatory 'LUIS Authoring key' (previously created in West Europe)
8. Select the proper 'Luis Authoring key'
9. Click 'Ok'
10. Wait for publish to finish
11. Click 'Test in Emulator'
12. When conversation starts in Emulator you should see 'Hi, how can I help today?'
13. Click 'Add'
14. See the unexpected Bot answer "Response status code does not indicate success: 401 (PermissionDenied)."

## Expected behavior

Bot should understand and correctly answer, without erroring out.

## Additional context

LUIS Authoring seems to work just fine. I can correctly see all the models and intents created by Composer.

If a try to overload `authoringEndpoint` or `endpoint` under 'Settings' > 'Bot settings' the error change to: "Response status code does not indicate success: 403 (Forbidden).".

Also setting `endpointKey` with a valid LUIS key seems to not be beneficial.

**Comment by v-kydela** [comment]
@nitroin - Thank you for the detailed repro steps. I tried your steps exactly but I could not reproduce the problem:

![image](https://user-images.githubusercontent.com/41968495/91338326-9be17000-e789-11ea-9349-dd646cc19aa2.png)

We will need more information in order to determine why it's not working for you. What is your authoring region? Are you using the en-us locale?

**Comment by nitroin** [comment]
Thank you.

All my tests were done from a Luis instance created from Azure, West Europe region.

I have now tested with a Luis created from Azure but WestUS region. The bot is working as expected.

I'll update the issue accordingly!

**Comment by v-kydela** [comment]
I'm unable to start the bot at all when providing a West Europe authoring key. However, when I change the region to westeurope in the bot's settings it starts correctly and then works correctly in Emulator:

![image](https://user-images.githubusercontent.com/41968495/91351976-013f5c00-e79e-11ea-9aea-91bd87ccc628.png)

Could there be any extra steps you're performing to make Composer recognize your West Europe authoring key as valid when the region is still set to westus?

**Comment by nitroin** [comment]
I was able to select the correct region at the first start of the bot, while providing the authoring key.

I will try from scratch and report back.

Thanks!

**Comment by nitroin** [comment]
Hello again. I'm able to repro the issue.

Updated steps:

8 bis. From the combobox select 'westeurope'.

<img width="1323" alt="Screenshot 2020-08-27 at 3 57 02 PM" src="https://user-images.githubusercontent.com/14164969/91452296-b34e5500-e87e-11ea-94ed-0a5d4cf34a0d.png">

 
<img width="1325" alt="Screenshot 2020-08-27 at 3 58 06 PM" src="https://user-images.githubusercontent.com/14164969/91452333-bba69000-e87e-11ea-9443-4cce7555f3ef.png">

I can provide a video if preferred.
Do not panic for the included Authoring key in the screenshot, is invalidated already. Thank you!

**Comment by nitroin** [comment]
Here a video repro.

Setting up the bot.

![output-2](https://user-images.githubusercontent.com/14164969/91461105-e695e180-e888-11ea-8bae-87e9149b09ba.gif)

(20 sec cut)

![output-3](https://user-images.githubusercontent.com/14164969/91461169-f6152a80-e888-11ea-9715-5c851fa83b6d.gif)

**Comment by v-kydela** [comment]
@nitroin - So it looks like the problem is that LUIS isn't working for you with a westeurope key but is working for you with a westus key. It seems like the problem is not that you've configured the wrong region in your bot settings, but can you check the settings after you've started your bot to make sure anyway? I posted a screenshot earlier of what the LUIS endpoint looks like in the settings.

My thought is that seeing what you've done in the LUIS portal would be more helpful than seeing what you've done in Composer. But if you'd like to help determine if Composer really is the cause of the discrepancy, you could try seeing if you can reproduce the problem in [other versions](https://github.com/microsoft/BotFramework-Composer/releases) of Composer. I still cannot reproduce the problem on my end.

@cwhitten - Do you know why the Authoring Region and Default Language input boxes are disabled for me?

![image](https://user-images.githubusercontent.com/41968495/91462679-4cf61200-e83f-11ea-8f8c-212a3a33e476.png)

**Comment by nitroin** [comment]
@v-kydela I've tried Bot Composer ver 1.0.2 (not Beta/Insiders) and I'm able to use the Luis services from West Europe.

This looks like a regression from pre-release ver.

Thanks.

**Comment by v-kydela** [comment]
@nitroin - Thank you for testing that. I guess the Composer version is the culprit after all. Previews are certainly not guaranteed to be bug-free but I suppose it's nice to have this bug report anyway. I'll unassign myself so this can be triaged.

**Comment by nitroin** [comment]
Super! Thank you @v-kydela.

**Comment by cwhitten** [comment]
@nitroin you can modify the region settings by navigating to Settings -> Bot Settings and look for the "luis" key.

In an upcoming release we're enable modification of these fields

**Comment by nitroin** [comment]
> @nitroin you can modify the region settings by navigating to Settings -> Bot Settings and look for the "luis" key.
> 
> In an upcoming release we're enable modification of these fields

Thank you @cwhitten - the problem is not changing the Luis region (by hand on Bot settings or by ComboBox at the first start) or deploy models (with Intents definitions).

The problem is the Luis model unavailability when choosing said region while into bot conversation.
The regression seems to be there also in version v1.0.2-nightly-161168.62bd41.

**Comment by hibrenda** [comment]
@nitroin Could you help to check the default endpoint setting in LUIS and updated in bot settings?

-  Check the luis endpoint and updated in Settings->Bot settings ("luis" :   "authoringEndpoint": "xxx")
![image](https://user-images.githubusercontent.com/43408889/91511855-41741b00-e913-11ea-9626-98bd160cbda5.png)

**Comment by nitroin** [comment]
Thank you @hibrenda.

I tried to manually popolate `authoringKey` and `endpoint` **only** and this seems to fix the issue!

My confusion in previous tests was that I was providing all `endpointKey`, `endpoint` and `authoringEndpoint` values.
This result in in 403 Forbidden.

Thank you all. I hope this debug session is beneficial to other users too.

We're really liking Composer workflow. Thanks.

_(this can be close, dunno if I'm supposed to do that or is best if done by one of the team)_

**Comment by hibrenda** [comment]
Thanks for the verification.  Actually there are 2 ways to make it work.
1. Manually add **authoring** key/endpoint to all the endpointkey, endpoint, authoringendpoint and authoringkey if your luis service is not default like “https://{region}.xxxx". 
2. Based on the luis doc :  https://docs.microsoft.com/en-us/azure/cognitive-services/luis/get-started-portal-deploy-app#assign-the-resource-key-to-the-luis-app-in-the-luis-portal (manually assign prediction resource to all the corresponding luis app which published by composer) . Then you can use prediction key/endpoint in Bot setting .

@zxyanliu  Let's document this part later.
