### ISSUE TITLE
Need docs: expand information about using max turn count, default value and default value response

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3907]
We should explain in more detail how these three properties inter-relate.

Max turn count is used to determine how many attempts a user will have to answer a prompt.  It is important to call out to users that if this is reached, the property will end up being set to NULL unless a default value is specified. Since the default value of this is *3*, it is highly likely that a user will hit this limit.

If the dialog is not designed to handle a null value, it may crash the bot.

When a default value is specified, you should also specify the default value response. This will be sent to the user after the last failed attempt.  If not specified, the prompt will simply end and move on without telling the user a default value has been selected.  In order for teh default value response to be used, you must specify BOTH the `default value` and the `default value response` field.

**Comment by zxyanliu** [comment]
The doc is updated and in-review. The content will go live soon. 
Closing this issue. Thanks again for the feedback. 👍
