### ISSUE TITLE
Validation rule field should include a placeholder tip

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3908]
## Is your feature request related to a problem? Please describe.

The validation rule input has no placeholder. We should put a tip in this field as is present in many others that explains to the user what a valid value would look like, such as `this.value > 0 && this.value <= 10`

In addition, we should update the tooltip value for this field to link to relevant documents -- hopefully one created as a result of #3906

**Comment by cwhitten** [comment]
@LouisEugeneMSFT can you look to wire in examples into the validation fields as part of your type selection and example work
