### ISSUE TITLE
Consider: should we autosave validation rule even if enter is not pressed?

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3909]
## Is your feature request related to a problem? Please describe.

Currently, a user must type a validation rule, then hit ENTER to add it to the prompt.  If the user does not hit enter, the value is discarded.

This is because of the inherited behavior from the list input type. However, this is very easy to miss.

## Describe the solution you'd like

I propose that we make the validation rules behave more like the normal fields which save automatically without extra actions

**Comment by cwhitten** [comment]
@sangwoohaan has this updated this is form design tweaks

**Comment by sangwoohaan** [comment]
This one has a new design but haven't been implemented yet. https://www.figma.com/file/oyUckdH5xVFEpyM97Mb8iy/Composer-main-design-spec-UI-library-Copy?node-id=2615%3A21799

Marc was in the middle of doing visual polishment. I will have to pick up this after the bot project is dine.

**Comment by cwhitten** [comment]
This has now been implemented. Closing
