### ISSUE TITLE
Need docs: how to use LUIS entities to support synonyms in a multi-choice prompt

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3910]
It is possible to use LUIS entities as part of a multi-choice prompt so that the bot can understand a wider set of replies.

This can be achieved using list entities. @vishwacsena can provide more info around doing this!

This would make a good tip or best practice!

**Comment by luhan2017** [comment]
@benbrown , do you happen to know the detail of this solution? I can work with Yan to doc on this.

**Comment by benbrown** [comment]
No, I don't. This is something @vishwacsena had mentioned being able to do.

**Comment by zxyanliu** [comment]
Closing this issue since the PR gets approved, the content will be merged and go live soon. 
Also tracking in the docs' repo: https://github.com/MicrosoftDocs/composer-docs-pr/issues/208
