### ISSUE TITLE
How to enable Electron users to set QnA subscription key

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#3912]
## Describe the bug

Current QnA implementation requires users to set QnA subscription key by running `set QNA_SUBSCRIPTION_KEY=<Your_QnA_Subscription_Key>` and restart Composer, otherwise, you will see the following error message and your KB creation will not be successful:

![image](https://user-images.githubusercontent.com/32497439/91363763-2b9b1480-e7b2-11ea-853a-e7c694ef0fd1.png)

We might need a solution for electron users to set their QnA subscription key since we do not expect them to make things work by running commands.

## Version

The [main](https://github.com/microsoft/BotFramework-Composer) branch as of August 26, 2020. 

## Browser

- [x] Chrome

## OS

- [x] Windows

## To Reproduce

1. Build from source using the [main](https://github.com/microsoft/BotFramework-Composer) branch.
2. Select **+ New** from the home screen.
3. On the pop-up window select **Create from knowledge base (QnA Maker)** from the **Choose how to create your bot** field. Select **Next**. 
4. Enter a name for your bot, add a Description (optional), and specify a location to store the bot. Select **Next**.
5. On the pop-up window, enter a URL in the **URL** field. Select **Create knowledge base**. 
6. See the error message. 
7. Run `set QNA_SUBSCRIPTION_KEY=<Your_QnA_Subscription_Key>` and restart Composer fixes the issue. 

## Expected behavior

Electron users may not be able to run `set QNA_SUBSCRIPTION_KEY=<Your_QnA_Subscription_Key>` and restart Composer to fix the issue.

## Additional context

We need a solution for electron users for this particular issue in regard to the QnA implementation.

**Comment by lei9444** [comment]
Hi, @zxyanliu, for web app, now we need to set QNA_SUBSCRIPTION_KEY=xxx before yarn start if we want to use qna url import. For electron, I updated the pipelines and add a env variable to save the key when build the server. So electron can use the qna url import feature directly

**Comment by zxyanliu** [comment]
@lei9444 thanks. Do you have a suggested nightly build so that I can verify this?

**Comment by lei9444** [comment]
> @lei9444 thanks. Used nightly build to test. Yes, no need to set QnA subscription key.
> However, I got this error after publish the bot to QnA and enter a sample question in Emulator:
> 
> ![image](https://user-images.githubusercontent.com/32497439/91387396-0d510b00-e7ea-11ea-8f64-0d0959acbc49.png)

This is another issue. The key in environment is only used to import the qna from url. We can file a new issue to track.
