### ISSUE TITLE
Composer on docker cannot find runtimes folder, therefore, cannot start bot

### ISSUE THREAD

**Issue by cdonke** [microsoft/BotFramework-Composer#3925]
## Describe the bug
When running from docker, clicking to start bot runs really quick... But emulator cannot reach the API.

Running _ ps aux_ from inside the container, it shows no _dotnet process_ running.
Checking the _/hostedBots/XXX/runtime_ folder, it's empty.
Checking the _localPublish/src/index.ts_ file, it copies the runtimes from _../../../../runtime_ folder,which falls to _/app/Composer/runtime_, and not _/runime_.

## Version
1.0.2

## Browser
- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X ] Edge

## OS

- [ ] macOS
- [ X ] Windows
- [ ] Ubuntu

## To Reproduce

1. docker-compose build
2. docker-compose up
3. Open //127.0.0.1:3000
4. Create a new EchoBot - doesn't matter the path
5. Start Bot and Run on emulator (ngrok required)

## Expected behavior
1. Bot to start up
2. Bot emulator to successfully send the first _conversationUpdate_ message (HTTP Status 200)

**Comment by cwhitten** [comment]
@cdonke thank you for submitting changes to address this! tangentially--can you share more information about your scenarios and use of dockers and containers with Composer?
