### ISSUE TITLE
Consider: should expression fields auto-expand so they can fit long expressions?

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3926]
The current expression field is a single line that does not expand to fit the content of the field.  This makes it difficult to edit (frequently) complex and long expressions, for example:

![qaN03E30BJ](https://user-images.githubusercontent.com/729873/91469418-fc8bae00-e858-11ea-8510-fe681d0a261e.gif)

It would be great if this field would expand so I can see and more freely edit the full text of the expression.

**Comment by cwhitten** [comment]
@sangwoohaan does this scenario apply to your updated field UX that is ready to go?

**Comment by sangwoohaan** [comment]
Yes it does!

**Comment by mewa1024** [comment]
Looks like Sang's fix was never implemented. Screenshot from Composer 2.0:
![image](https://user-images.githubusercontent.com/39317542/124335496-55019b00-db4f-11eb-9f44-81f7dd627cba.png)
