### ISSUE TITLE
Instrument key features and events in Composer with app analytics

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3936]
We need to track some key usage metrics in Composer so the project can evolve to support our growing user base.

## Describe the solution you'd like

We should instrument Composer with an app analytics tool with an MVP set of events that help us understand real user behavior in the app.

**Comment by benbrown** [comment]
@michielpr can help us define these

**Comment by michielpr** [comment]
We'd like to track the following moments: 
- Signal when someone installs composer successfully 
- Signal when someone clicks on create new (start bot creation flow) 
- Signal when a new bot gets created locally (end of create new flow) 
- Signal when user creates a new publishing profile 
- Signal when user created a new publishing profile 
- Signal when a bot gets published 
- An environment marker in the Bot ABS resource stating this particular BotID was created in Composer

**Comment by cwhitten** [comment]
We need to run through a privacy review before we can build a work plan for this. 

Something to consider is that if we collect any personally identifiable information we have to go through a significant amount of work for GDPR reasons. @michielpr all the information you want "Per BotID" is considered PII.

**Comment by michielpr** [comment]
Thanks! Would you recommend I start a thread with CELA/Privacy, Ben, you and myself to get this started? 

Also, do you think we should split this issue in two: 
- one for non-PII type 
- one for PII-type information

Should that be the way forward?

**Comment by benbrown** [comment]
@michielpr @cwhitten can we close this since we shipped telemetry?

**Comment by cwhitten** [comment]
Yes! Closing.
