### ISSUE TITLE
Cannot open a folder from local drive using composer

### ISSUE THREAD

**Issue by Michelle-Deve** [microsoft/BotFramework-Composer#3943]
![Capture](https://user-images.githubusercontent.com/65315409/91697380-50f09f80-eb71-11ea-9dd5-3b480ea08c45.JPG)

**Comment by dmvtech** [comment]
Hi @Michelle-Deve What OS are you running?

**Comment by Michelle-Deve** [comment]
@dmvtech windows 10

**Comment by cwhitten** [comment]
@Michelle-Deve where on your file system are you storing your bot projects?

**Comment by dmvtech** [comment]
Hi @Michelle-Deve Can you let us know where on the file system you are storing your bot projects? Also; what version of composer are you running ([1.1.1](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.1.1) is the most recent).

**Comment by Michelle-Deve** [comment]
@cwhitten and @dmvtech all my projects are stored in C:/Repos/ but the issue started when I was trying to open a project from this path C:\Users\michellem\Downloads\PROJECT_SoleCheque. @dmvtech I did update to the latest version and still have the same issue

**Comment by dmvtech** [comment]
I'll try similar and see if I have any issues with it.

**Comment by dmvtech** [comment]
I'm unable to reproduce this. Are you able to share a (private is fine) Github repository (sanitized for personal/sensitive info) of the bot with me? Or let me know if you can get me the bot in another way so that I can see if I can reproduce.

**Comment by dmvtech** [comment]
Hi @Michelle-Deve Just touching base again. Can you share your sanitized composer files so that I can see if I can try and reproduce?

**Comment by Michelle-Deve** [comment]
@dmvtech I have managed to fix the issue. I had to uninstall composer version 1.1.1, run the composer that uses yarn and locate the storage after that I install composer version 1.1.1 again and I was able to connect to storage. I had to restart in between the steps

**Comment by dmvtech** [comment]
Ok! Interesting. Glad you got it worked out and thank you for letting us know what you did to resolve it. 🌟
