### ISSUE TITLE
max limit 100 app versions when publish bot to azure

### ISSUE THREAD

**Issue by GavinHarbus** [microsoft/BotFramework-Composer#3944]
## Describe the bug

When I publish my bot to my azure app service, I met this error - The number of application versions cannot exceed the limit of 100. But I can publish luis app by click start bot ot restart bot, and the app.versionId in my .lu file is just 0.1. And I have deleted all extra luis versions, but it didn't work for this issue.

## Screenshots

![image](https://user-images.githubusercontent.com/23392860/91703697-2cb2b400-ebad-11ea-806b-188d0061c30d.png)
![image](https://user-images.githubusercontent.com/23392860/91704286-fe81a400-ebad-11ea-83fd-ad9080ffd696.png)

**Comment by VanyLaw** [comment]
Using nightly build version electron can solve this problem. because we fixed the relative problem in https://github.com/microsoft/BotFramework-Composer/pull/3661.
