### ISSUE TITLE
eslint-plugin-bfcomposer not-found when build on the composer image on ACR

### ISSUE THREAD

**Issue by kunigagon** [microsoft/BotFramework-Composer#3945]
## Describe the bug

i use the master branch for build.
on the Composer path : "az acr build --registry xxxxx --image xxxxxxx ."

result:
2020/08/31 09:12:44 Downloading source code...
2020/08/31 09:12:46 Finished downloading source code
2020/08/31 09:12:46 Using acb_vol_7e9ea94670692 as the home volume
2020/08/31 09:12:46 Setting up Docker configuration...
2020/08/31 09:12:47 Successfully set up Docker configuration
2020/08/31 09:12:47 Logging in to registry: xxxx
2020/08/31 09:12:48 Successfully logged into xxxxxxx
2020/08/31 09:12:48 Executing step ID: build. Timeout(sec): 28800, Working directory: '', Network: ''
2020/08/31 09:12:48 Scanning for dependencies...
2020/08/31 09:12:49 Successfully scanned dependencies
2020/08/31 09:12:49 Launching container with name: build
Sending build context to Docker daemon  1.307MB
Step 1/29 : FROM node:12-alpine as build
12-alpine: Pulling from library/node
cbdbe7a5bc2a: Pulling fs layer
091983d60f65: Pulling fs layer
7bacc183740f: Pulling fs layer
c4a5a5d270d4: Pulling fs layer
c4a5a5d270d4: Waiting
cbdbe7a5bc2a: Verifying Checksum
cbdbe7a5bc2a: Download complete
7bacc183740f: Verifying Checksum
7bacc183740f: Download complete
091983d60f65: Download complete
cbdbe7a5bc2a: Pull complete
c4a5a5d270d4: Verifying Checksum
c4a5a5d270d4: Download complete
091983d60f65: Pull complete
7bacc183740f: Pull complete
c4a5a5d270d4: Pull complete
Digest: sha256:9623cd396644f9b2e595d833dc0188a880333674488d939338ab5fde10ef7c43
Status: Downloaded newer image for node:12-alpine
 ---> 18f4bc975732
Step 2/29 : WORKDIR /src/Composer
 ---> Running in fcaecf99f14f
Removing intermediate container fcaecf99f14f
 ---> c7c18e20bb9b
Step 3/29 : COPY . .
 ---> de9c4acfc7cc
Step 4/29 : RUN yarn install --frozen-lock-file
 ---> Running in 2ca866bf7ce4
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@bfc%2feslint-plugin-bfcomposer: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/src/Composer/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install --frozen-lock-file' returned a non-zero code: 1
2020/08/31 09:12:59 Container failed during run: build. No retries remaining.
failed to run step ID: build: exit status 1

Run ID: cbxx failed after 15s. Error: failed during run, err: exit status 1
Run failed

## Version
Master branch
Releases 7
1.0.2
Latest
on Jul 9

## OS

Develop on Winndow 10 pro: WSL 

## To Reproduce

i use the master branch for build.
on the Composer path : "az acr build --registry xxxxx --image xxxxxxx ."

## Screenshots
![image](https://user-images.githubusercontent.com/47618641/91705609-6680bc00-eba7-11ea-93ec-f83464ea224b.png)

**Comment by cwhitten** [comment]
@kunigagon please use the `main` branch and try again?

**Comment by kunigagon** [comment]
Hi @cwhitten  @a-b-r-o-w-n  i have tried. it change error but still not work.
![image](https://user-images.githubusercontent.com/47618641/91937918-2b07fe00-ed1d-11ea-8b59-494be7b3aa56.png)

**Comment by kunigagon** [comment]
> @kunigagon please use the `main` branch and try again

Hi @cwhitten @a-b-r-o-w-n i have tried. it change error but still not work.
![image](https://user-images.githubusercontent.com/47618641/91937965-4541dc00-ed1d-11ea-811b-cc605d9c397a.png)

**Comment by a-b-r-o-w-n** [comment]
I found that the issue was with our `.dockerignore` file. I have pushed a fix on #3986 for you to test.

**Comment by kunigagon** [comment]
@a-b-r-o-w-n  @cwhitten  Thank you. solved.
