### ISSUE TITLE
BUG: secondary qna endpointkey field being added to projects, causes crash

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3948]
## Describe the bug

Opening a slightly older project causes duplicate configuration keys to be added to the appsettings file, causing the dotnet runtime to crash.  This is related to the qna endpointKey field which now appears in 2 forms "endpointkey" and "endpointKey".

No action is necessary to cause this error - simply opening the project will corrupt it.

This corruption breaks previously working projects and causes them to crash with an unhandled exception. To fix them, the keys have to be removed manually from the settings.

## Version

`main` branch as of Aug 31

**Comment by benbrown** [comment]
![Screen Shot 2020-08-31 at 11 00 08 AM](https://user-images.githubusercontent.com/729873/91740609-29053a00-eb79-11ea-984b-da45cb7b4696.png)

**Comment by zxyanliu** [comment]
Creating a new bot does not generate this error. 

![qna1](https://user-images.githubusercontent.com/32497439/91748403-c873fe00-eb74-11ea-92a5-f9a8c51aa5e4.png)
