### ISSUE TITLE
The placeholder for the BeginDialogs options has a typo

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3951]
## Describe the bug

If "Expression" is selected as the type for the begin dialog options field, it says "ex. [Object object]"

## Version

 1.1.0

![Screen Shot 2020-08-31 at 4 06 17 PM](https://user-images.githubusercontent.com/729873/91768999-2835cd80-eba4-11ea-8ae4-d9ff20b8edda.png)

**Comment by cwhitten** [comment]
@LouisEugeneMSFT we discussed this a couple weeks ago -- can you include as part of your proposals to update examples/type selections?
