### ISSUE TITLE
Update title of "new bot" dialog

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#3952]
## Is your feature request related to a problem? Please describe.

The 2nd step of the "new bot" flow currently has a modal where the project name and location are selected. However, the title of this modal is "define conversation objective" which is a legacy title from when this modal was shared with other parts of the app.

## Describe the solution you'd like

The title and description of this modal should be updated.  Consider removing "description" field which is not currently displayed anywhere.

Title: New Bot Project
Description: Specify a name and location for your new bot project. 

![Screen Shot 2020-08-31 at 4 08 30 PM](https://user-images.githubusercontent.com/729873/91769189-81056600-eba4-11ea-8bec-758272b7f962.png)

**Comment by zxyanliu** [comment]
Can we do the following?

 * For the new bot project form:
	Create a bot project 
	Specify a name, description, and location for your new bot project.
	
* For the new dialog form:
	Create a dialog
	Specify a name and description for your new dialog.

**Comment by zxyanliu** [comment]
e2e test in a draft PR:

![image](https://user-images.githubusercontent.com/32497439/92292705-7106c280-eed3-11ea-9963-a7011c32babb.png)

![image](https://user-images.githubusercontent.com/32497439/92292752-aad7c900-eed3-11ea-8003-d91ffa5ced62.png)

**Comment by zxyanliu** [comment]
Thanks!!!
