### ISSUE TITLE
Start Runtimes locally

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#3957]
This ticket involves Platform and Authoring work.

- [x] ability to start a single bot within a project
- [x] make the root bot refer to running skills
- [x] ability to stop a single bot within a project
- [x] start/stop all
- [ ] propagate error states to runtime Notification window
- [ ] generate runtime warnings

This ticket involves starting up runtimes and surfacing validation errors that require starting up runtimes of the root bot and its skills inside the botproject

Multi-bot testing - https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-main-design-spec-UI-library?node-id=5204%3A3

**Comment by sangwoohaan** [comment]
Updated the design as new notification designs came in. Removed the console, merged it with other notification. The validation badge design will remain as it is in the current build since Vivek is tackling that experience as a whole.
