### ISSUE TITLE
COMPOSER: the  former connections of  a trigger  get  broken when you Switch  between LUIS and REGEX 

### ISSUE THREAD

**Issue by soniaang** [microsoft/BotFramework-Composer#3966]
## Describe the bug

These connections that  were working for intents/ or  triggers  like Help cancel etc al get broken when switch between modes . i have tp REDO again! 

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
hi @soniaang - switching recognizers may require updating the existing triggers configured in order to work with the newly selected recognizer. If Composer had a warning when this operation was done, would this be helpful?
