### ISSUE TITLE
Inline editor doesn't update the content if create a new intent from design page

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#3970]
## Describe the bug

![update](https://user-images.githubusercontent.com/39758135/91826579-5f71b080-ec70-11ea-9e7e-4117ac4895b2.gif)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by boydc2014** [comment]
dup to #3971
