### ISSUE TITLE
Got error of MicrosoftPassword incorrect for the new provisioned web app bot. (both creation from script and portal)

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#3975]
## Describe the bug

- create an echo bot
- run provision script
- deploy the bot. deployment will success.
- query the bot from the azure portal, there is no response.
- query it from the emulator, got an error: The bot's Microsoft App Password is incorrect. 
- The publish profile provisioned before works well.
- I tried to create a new azure web bot in azure portal, and query it from the emulator and got the same error. 
![image](https://user-images.githubusercontent.com/32191031/91844790-a7053600-ec8a-11ea-9de4-16d2bbe6b999.png)
![image](https://user-images.githubusercontent.com/32191031/91844807-aec4da80-ec8a-11ea-9e45-061cd5d932cb.png)
![image](https://user-images.githubusercontent.com/32191031/91844712-8341f000-ec8a-11ea-8905-ebbca253c6ca.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by luhan2017** [comment]
Got this error in the webchat

![image](https://user-images.githubusercontent.com/32191031/91859799-724eaa00-ec9d-11ea-9b35-b7dfccf19e44.png)

**Comment by zxyanliu** [comment]
Lu, thanks for reporting this. In addition to this, I got this error as well. 
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/32497439/91874748-73e18900-ec2f-11ea-9214-2474bad99be6.png)

**Comment by Andrea-Orimoto** [comment]
This is an internal only problem, by design due to compliance. Please see my email on this subject. Thanks for reporting!
