### ISSUE TITLE
Users are prompted when starting composer or opening a bot if they have uninstalled extensions

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#3998]
An in app alert modal that has a link to the extensions page where users can manually install each missing extension.

**Comment by cwhitten** [comment]
@a-b-r-o-w-n how does Composer know which extensions are missing?

**Comment by a-b-r-o-w-n** [comment]
This would be extensions that exist in the manifest database, but are not installed. This scenario supports custom flavors of composer by launching a bot with certain extensions enabled & configured. I imagine PVA would want to do this for bots opened using the protocol handler.
