### ISSUE TITLE
The toolbar is intended to be context sensitive. This means that actions that require a selection do not show unless an item is selecfted

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#4008]
the toolbar is intended to be context sensitive: buttons that require a selection to be applicable therefore do not show up unless something is selected. This means that 'disable' would only be shown when an item that can be disabled is selected.
And once a disabled item is selected, 'enable' should show.

- Today: Disable is shown as a menu (vs button) in the toolbar even when nothing is selected. 
- Expected: disable button should not be visible

![Screen Shot 2020-09-02 at 4 26 51 PM](https://user-images.githubusercontent.com/48503434/92047118-22252580-ed39-11ea-84c1-5989973ce134.png)

Today: Disable shows as menu when item is selected, requiring user to click the dropdown and see only 1 item in the menu enabled: 'disable'
Expected: Disable should show as a button upon selecting an node that. can be diasbled (but is not disabled yet)
![Screen Shot 2020-09-02 at 4 29 32 PM](https://user-images.githubusercontent.com/48503434/92047261-85af5300-ed39-11ea-9093-0e13f874dadc.png)

Today: Once an item is disabled, but not selected, 'Disable' shows up in the toolbar menu, tho not active
Expected: as nothing is selected, no node can be enabled or disabled. Dont show the button.

Today: Once a disabled item is selected, the 'disable' option is shown on the toolbar, active, even though the selected node cannot be disabled-  it already is disabled
Expected: as the node is alerady disabled, the appropriate action is to 'enable' - make the button say this and do not require the user to hit disable to get access to 'enable'

![Screen Shot 2020-09-02 at 2 41 58 PM](https://user-images.githubusercontent.com/48503434/92047501-2140c380-ed3a-11ea-811a-cb9563c4e0a6.png)

**Comment by cwhitten** [comment]
@mareekuh "Disable" as a menu and not a button is by design and in the figma--we discussed this recently. https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-main-design-spec-%2F-UI-library?node-id=2968%3A26994

**Comment by garypretty** [comment]
I agree that this feels odd UX.  If it is going to be a drop down menu, then the top menu should be 'Enable / Disable'.  If we can toggle the button text depending on the status of the selected object then it should switch depending on the context.

I can't see the commentary linked to - @cwhitten is this something we can address?

**Comment by mareekuh** [comment]
@cwhitten - We need to revise what is implemented based on user feedback. 
@JaskeeratBedi-cmk  can you take a pass at this and run it by me/vivek?

**Comment by mareekuh** [comment]
@vivekkshankar - can you take this on moving forward? I know you are already looking at this (and have so in the past).

**Comment by mewa1024** [comment]
Unless anyone objects, can we just do this?
- nothing selected = show "Disable" button in the disabled state
- node selected and the node is enabled = show "Disable"  button in the rest state
- node selected and the node is disabled = hide "Disable" button, in its place, show an "Enable" button in the rest state
- mix of nodes that are disabled and enabled = hide "Disable" button, in its place, show an "Enable" button in the rest state; when pressed, all the selected nodes should be enabled
