### ISSUE TITLE
Copy /paste placeholder text in fields

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#4009]
Composer has detailed examples inside the properties fields, but they cannot be selected (copy paste to use as a starting point) and once anything has been typed in there, the original suggested text cannot be brought back

Expected: ability to use placeholder text from the property fields as a starting point that can be edited (and or copied/pasted)

**Comment by a-b-r-o-w-n** [comment]
@mareekuh we are using the placeholder property from the HTML5 specification. I would assume that all browsers do not allow copying these values, but it is not something we can control.

We could use those values as default values, but that wouldn't be helpful in most cases. Some other options to consider are adding the examples to the field intellisense (they would show up as suggestions when editing the field) or adding the examples to the field tooltip where user's can copy them.

**Comment by cwhitten** [comment]
Closing as designed
