### ISSUE TITLE
Expression parsing for object

### ISSUE THREAD

**Issue by Olakhrisat** [microsoft/BotFramework-Composer#4016]
Hello,

I need a help with this issue in bot composer (release 1.0.1):
when I try to build an object like this:
![image](https://user-images.githubusercontent.com/59798587/92089053-5569c200-edd6-11ea-97fb-09a69a20a1ff.png)
it works fine and it returns an object but when I use this object in http post and assign it to body 
![image](https://user-images.githubusercontent.com/59798587/92089149-70d4cd00-edd6-11ea-9d72-1bb24e2e28d2.png)
it returns an error so I tried to debug and I figured it out that the parsing treated it as string (Bot.Builder.Dialogs.Adaptive.Acttions.HttpRequest - ReplaceJTokenRecursivelyAsync)
![image](https://user-images.githubusercontent.com/59798587/92089588-08d2b680-edd7-11ea-92a8-538ff6918a19.png)

the error is:
![image](https://user-images.githubusercontent.com/59798587/92089875-65ce6c80-edd7-11ea-9c80-0ef4121b47da.png)

any idea?

**Comment by a-b-r-o-w-n** [comment]
@Olakhrisat can you try `=Conversation.Body` instead? Using the `${}` automatically casts that value to a string.

**Comment by Olakhrisat** [comment]
@a-b-r-o-w-n thank you, it works for me
