### ISSUE TITLE
Show dialog interface in BeginDialog form

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#4022]
If a dialog has an interface defined and is selected in the BeginDialog, render the form fields for the dialog's interface.

**Comment by cdonke** [comment]
I am trying to work on it...
I already retrieved the interface, and added it to the "options" list of the BeginDialog component...

But, when I change the selected dialog, I cannot update the layout (render the new fields)...
Ay hint on how to trigger this?
