### ISSUE TITLE
Release plan for Bot Framework Composer

### ISSUE THREAD

**Issue by eluchsinger** [microsoft/BotFramework-Composer#4027]
Is there a release plan for the Bot Framework Composer? Like do releases once a month or how do you handle bugfixes, do they get released more often or do we have to wait until the next release?

**Comment by cwhitten** [comment]
Hi @eluchsinger 

We typically ship new stable versions along with the Bot Framework SDK release schedule. This is distributed across the calendar year and ends up being around 4-5 releases. Between those stable releases Composer will at times release patches that include bugfixing, ui/ux improvements, or a small new feature. This happens on an as-needed basis.
