### ISSUE TITLE
Result property the return type does not match while setting property name via an expression

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#4028]
#  Describe the bug

The issue is somewhat new with v1.1.1 I guess, as it was working already. I have created a for each loop in which I send HTTP requests and want to store the result in a property in the format `user.orderCardX` (where X is the dialog.foreach.index of the loop) so that I create let's say 3 variables if the loop is run through 3 times:
- user.orderCard0
- user.orderCard1
- user.orderCard2

But all of a sudden I get this error:

`Result property the return type does not match`:
![image](https://user-images.githubusercontent.com/29750798/92229497-e362ad00-eea9-11ea-899c-f97444df8f88.png)

## Version

v1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

You can also create a new property and name it for example `=concat('user.','test')` which will give the same error

## Expected behavior

It should be possible to dynamically assign variable/property names within loops via an expression using the concat() function

**Comment by a-b-r-o-w-n** [comment]
@stephanbisser This is a known issue. The `concat` method can now be used on lists as well as strings, which is breaking Composer's validation. A temporary workaround is to use the `string` function.

```
=string(concat('user.', 'test'))
```

**Comment by stephanbisser** [comment]
Thanks @a-b-r-o-w-n that did the trick for me and solved the issue!

**Comment by silviofx2** [comment]
Hi, this question mentions how to assign a value to a dynamically named variable. Now, I am interested in knowing how to get the value of that variable, for example, to pass it to a custom action or to display it in a response. With concat I can correctly generate the name, but how do I tell the Composer that this text corresponds to a variable? I try to display with 
`- Answer: ${concat("dialog.answer_", string(dialog.foreach.index))}`
but it shows me the name of the variable, but not its content.
Thanks
