### ISSUE TITLE
Should have luis authoringKey and authoringRegion when lu file not empty

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#4029]
## Describe the bug

When trying to publish a bot which is not using LUIS at all, I get the following error:

`Should have luis authoringKey and authoringRegion when lu file not empty`

## Version

v1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior

It should be possible to publish a bot which is not using LUIS at all (all .lu files are empty) without providing LUIS information

**Comment by sandeepreddy0987** [comment]
![image](https://user-images.githubusercontent.com/33647692/92335660-1f3a7580-f056-11ea-8a4e-389ff1bcedfc.png)
Hi, I am getting this error while publishing my bot. I can publish my bot using v1.0.2. Is there any changes in the new version of bot composer?
please let me know how to resolve this issue. I have given all keys and endpoint URL in the settings

**Comment by sandeepreddy0987** [comment]
In the new version of bot composer, we should provide one more field called "authoringRegion":"westus" to resolve this error.

issue solved.

**Comment by stephanbisser** [comment]
Issue is not solved IMHO as I'm not using LUIS in my bot at all...

**Comment by luhan2017** [comment]
@stephanbisser , could you zip your bot and share with us? We can help to debug it.

**Comment by stephanbisser** [comment]
I fixed this issue after removing the "luisResource" key from the bot's settings @luhan2017
