### ISSUE TITLE
Azure Login Experience

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/BotFramework-Composer#4041]
## User story
**As a** bot creator,
**I want to** sign in to an existing or create a new Azure account from within the Composer UI,
**so that** I can easily perform Azure-related operations without needing to retrieve an access token from an external source, such as through the Azure CLI.

## Description

Within both the Virtual Assistant creation wizard, as well as when initiated from the Publish view within the UI, an Azure sign-in modal should be presented to users to allow them to sign in with their Azure credentials. This should be enabled using standard functionality offered through the Azure JS libraries.

Until such a point that the necessary AAD application to enable login has been set up, we should use a stub modal that enables users to manually enter an access token as acquired from the CLI.

## Acceptance criteria

- [ ] TBD

**Comment by benbrown** [comment]
See #3384

**Comment by peterinnesmsft** [comment]
Closing as duplicate.
