### ISSUE TITLE
documentation Install link points to old version of composer

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#4046]
## Describe the bug

When coming from the docs page it links to a aka.ms link which points to the old version of composer.
https://docs.microsoft.com/en-us/composer/setup-yarn

## Version

None

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

go to:
https://docs.microsoft.com/en-us/composer/setup-yarn

Click the windows install link and it installs the 1.02 version of composer.  

## Expected behavior

It should link to latest stable release.

**Comment by zxyanliu** [comment]
Hi @tomlm 

Thanks for reporting the issue. 

@cwhitten could you please update the following aka links for the desktop executables? Thanks!
* https://aka.ms/bf-composer-download-win
* https://aka.ms/bf-composer-download-mac
* https://aka.ms/bf-composer-download-linux

**Comment by cwhitten** [comment]
This is done @zxyanliu - given the 1.1.0 -> 1.1.1 we wanted to let the release settle just a bit.
