### ISSUE TITLE
Composer needs a splash screen which shows immediately.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#4047]
## Describe the bug

It takes way too long to load the composer.  I click on the icon and there is zero feedback that the app is loading until almost a minute, when the splash screen shows for a second then the app shows.  

The point of splash screens is to solve this problem.  If we can't get a display immediately because of the electron app we should create a tiny launcher app which shows the splash screen and then launches the real electron app.  Once the electron app has loaded it signals back to the splash screen so that the splash screen can go away.

## Version

1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

start the app

## Expected behavior

It should show the splash screen with 1-2 seconds, certainly no longer then 5 seconds.

**Comment by cwhitten** [comment]
@mareekuh can you please route this to a designer who can provide this asset for us?

Thanks.

**Comment by hatpick** [comment]
@mareekuh I have created the following based on what Office is doing in their latest version, what do you think?

![com splash screen](https://user-images.githubusercontent.com/1483492/92827373-a35a6900-f386-11ea-9741-d377544f1ee4.PNG)
