### ISSUE TITLE
Installing new composer blew away my runtime settings.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#4048]
## Describe the bug

Runtime settings need to be persisted to disk and be part of the source code.  When I uninstalled composer and reinstalled it I lost my bot runtime settings.

## Version

1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. eject runtime
2. uninstall composer
3. install composer
ejected runtime configuration is lost.

## Expected behavior

The ejected runtime configuration to be part of my source code, not my environment.

**Comment by luhan2017** [comment]
@tomlm , Which version of composer are you using? We did persist the eject runtime settings in the botfolder/settings/appsettings.json and I could not reproduce this issue. 
v1.1.1 before
```
  "runtime": {
    "path": "C:\\Users\\luhan\\Documents\\Composer\\EchoBot-13\\runtime",
    "command": "dotnet run --project azurewebapp",
    "customRuntime": true
  },
```

in v 1.1.1 we added name and key field to support js runtime ejection and switching between C# and js. 
```
  "runtime": {
    "key": "csharp-azurewebapp",
    "name": "C#",
    "path": "C:\\Users\\luhan\\Documents\\Composer\\EmptyBot-0\\runtime",
    "command": "dotnet run --project azurewebapp",
    "customRuntime": true
  },
```

**Comment by cwhitten** [comment]
ping @tomlm please help us with a repro

**Comment by cwhitten** [comment]
I believe this issue existed on 1.1.0 but not 1.1.1 (and was the reason we submitted the 1.1.1 patch)

context: https://github.com/microsoft/BotFramework-Composer/pull/4015

**Comment by cwhitten** [comment]
This has been addressed
