### ISSUE TITLE
Issues with azure webapp deployment script

### ISSUE THREAD

**Issue by ltwlf** [microsoft/BotFramework-Composer#4049]
## Describe the bug

The azure webapp deployment script has various issues e.g. bf luis:build has wrong --dialog argument. 
appsettings.deployment.json will never be used by the published bot and exposes local secrets to the remote folder. 

I'll prepare a pull request to fix these issues.

Best wishes,
Christian

## Version
Current main branch build

**Comment by luhan2017** [comment]
@ltwlf , we are deprecating this scripts, and use the scripts generated in your bot folder instead, could you please try that one? sorry for the confusion.

**Comment by ltwlf** [comment]
@luhan2017 where can I find this script in my bot folder? I used ...bot/runtime/dotnet/azurewebapp/scripts/deploy.ps1 Did I may fix the wrong one in the composer project? I uses the above mention script as a base for this fix

**Comment by ltwlf** [comment]
@luhan2017 I optimized the deploy script for CI/CD deployment and updated the readme with how to use it. And I deleted the obsolete scripts.

**Comment by luhan2017** [comment]
@ltwlf, Since we have new crosstrain, lubuild and qnabuild logic in the latest composer, if you want to keep that script, more changes are needed, call lubuild itself is not enough. Are you aware of this?

**Comment by ltwlf** [comment]
@luhan2017 I must keep it, we will use it in production :)
Crosstrain should be done already. Which branch should I check so that I can adjust the script accordingly?

**Comment by ltwlf** [comment]
Whatever you do, I have to check that it works in CI/CD pipeline.

**Comment by ltwlf** [comment]
My script works for the current main branch for Luis, but I didn’t use QnA. I guess this is my do to then.
