### ISSUE TITLE
LUIS Not available as a Recognizer type after upgrading to version 1.1.1

### ISSUE THREAD

**Issue by Jcardif** [microsoft/BotFramework-Composer#4051]
## Bug Description
After updating to version 1.1.1 yesterday I cannot find LUIS as a recognizer in the drop-down menu. 

## Version
![image](https://user-images.githubusercontent.com/29174946/92330956-99c9bc00-f07b-11ea-9190-9b79f1163063.png)

## OS
- [ ] Windows

## Screenshots
![image](https://user-images.githubusercontent.com/29174946/92330891-26c04580-f07b-11ea-981e-30960f2ceb48.png)

**Comment by luhan2017** [comment]
@Jcardif  The Luis recognizer is by-default enabled in the Default recognizer type. In 1.1.1, we released new recognizer types:
Default Recognizer maps to None, Luis, QnA, Luis+QnA Recognizer types. You can just use Default recognizer for luis.
