### ISSUE TITLE
[Run Time] Custom runtime test project need to clean up

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#4054]
## Describe the bug
When user create a copy of runtime, a branch of invalid test appears on test project (i.e. todo bot test) which cannot pass successfully also. Please help clean up them~

## Version
Latest main

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Create a new bot with QNA template
2. Go to setting, select use custom runtime, then generate a new copy of runtime code
3. Check the test project and run

## Expected behavior
All tests should be valid and functional. Things like "ToDoBotTests" should not appear because current bot has nothing to do with ToDo Bot.

## Screenshots

![image](https://user-images.githubusercontent.com/16643193/92356540-e1eaec00-f118-11ea-922a-6b43a9d405ca.png)

![image](https://user-images.githubusercontent.com/16643193/92356769-3b531b00-f119-11ea-9cd9-bcfab4125312.png)

**Comment by cwhitten** [comment]
Removing from R12

**Comment by carlosscastro** [comment]
@zidaneymar where are we with this? Are we addressing it or leaving it in favor of the upcoming runtime?

**Comment by msomanathan** [comment]
@cwhitten will this be addressed in R13, or, in future milestone?

**Comment by msomanathan** [comment]
@DingmaomaoBJTU this issue should be addressed with the release of R13 runtime.

**Comment by luhan2017** [comment]
custom runtime deprecated.
