### ISSUE TITLE
[Question] Will Qna support upload from file?

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#4058]
Will Qna support upload from file? What is the best way to add a chitchat qna from composer?

**Comment by hibrenda** [comment]
chitchat content can be imported from https://github.com/Microsoft/BotBuilder-PersonalityChat/tree/master/CSharp/Datasets .

**Comment by DingmaomaoBJTU** [comment]
Thanks!
