### ISSUE TITLE
Qna dialog code keep dup when click "Create Kb from scratch"

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#4059]
## Describe the bug

Qna dialog code keep dup when click "Create Kb from scratch"

## Version

latest main

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. 
![image](https://user-images.githubusercontent.com/16643193/92390237-0e206000-f14d-11ea-9f4d-d5ebfd80abe8.png)

2. 
![image](https://user-images.githubusercontent.com/16643193/92390287-26907a80-f14d-11ea-8a8f-b95160adb38d.png)

3. 
![image](https://user-images.githubusercontent.com/16643193/92390315-360fc380-f14d-11ea-8dbf-1604e1f40533.png)

keep operate like this, you will have the adaptive dialog dup with the same code

## Expected behavior

do not dup

**Comment by hibrenda** [comment]
For this scenario, we should only add one QnA recognized trigger to the specific dialog.
