### ISSUE TITLE
Unable to continue adaptive dialog flow once skill dialog ends

### ISSUE THREAD

**Issue by shefalikuk** [microsoft/BotFramework-Composer#4062]
I have created a skill consumer bot using Microsoft bot framework composer, which calls a skill when a specific intent is identified.

To reproduce the issue, consider I have got a flight booking bot (consumer bot) which has 2 intents, BookFlight and GetWeather. Suppose user is having conversation with consumer bot and is in middle of flight booking dialog. But now user doesn't want to continue this dialog and rather says something out of the context. Thus, LUIS identifies this input as None intent and goes to Skill bot which gets trigger when None intent is identified. 

Skill bot is simply an echo bot which replies which whatever user says. Now once my skill bot sends the reply or skill ends, ideally my adaptive dialog flow should continue (Flight Booking dialog). Since as per current SDK implementation, when a dialog ends, previous dialog in the stack continues. But in this scenario, once skill bot ends, bot does not continue the Flight booking dialog. 

Expected:
Previous dialog (Flight Booking dialog) should continue once skill ends.

**Comment by v-kydela** [comment]
@a-b-r-o-w-n - Can anyone on the Composer team clarify whether skill dialogs are meant to cancel existing dialogs on the stack?

**Comment by hibrenda** [comment]
@luhan2017 to be aware of this .

**Comment by GeoffCoxMSFT** [comment]
@vishwacsena - can you answer Kyle's question?

**Comment by vishwacsena** [comment]
I have no idea if/ what makes `BeginSkill` action behave differently. @Stevenic thoughts/ comment?

**Comment by EricDahlvang** [comment]
Hi @shefalikuk 

Would you be able to provide us with a repro project?  One way to do this is to export the composer project's assets to .zip:
![image](https://user-images.githubusercontent.com/11055362/93265268-374c7c00-f75d-11ea-9a6c-fee4fa743ba0.png)

Make sure to remove any passwords from the appsettings.json before sharing:
![image](https://user-images.githubusercontent.com/11055362/93265352-606d0c80-f75d-11ea-932a-ce7da148efe6.png)

**Comment by v-kydela** [comment]
I'm now thinking that this probably has nothing to do with skills. I've had a look at the source code and didn't see anything that would indicate skill dialogs being a special case that cancels all dialogs. I suspect the LUIS trigger is what's cancelling all dialogs on the stack or just replacing the active dialog with the skill dialog instead of adding it on top.

@shefalikuk - We'll need to see how your recognizers and triggers are set up. Please provide the information that Eric requested.

**Comment by v-kydela** [comment]
@shefalikuk - Are you still working on this?

**Comment by cleemullins** [comment]
Closing due to Eric's response.
