### ISSUE TITLE
Publishing Composer Bot to Azure results `HTTP Error 500.30 - ANCM In-Process Start Failure` error

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#4064]
## Describe the bug

Publishing a new Composer based Bot to Azure results in an App-Service instance that reports the following error when you browse to it:

`HTTP Error 500.30 - ANCM In-Process Start Failure`

## Version

1.02

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Publish a Composer Bot to Azure following the docs including pasting in a new publish profile created using the command line steps.
2. Browse to the app service in the browser
3. Observe the `HTTP Error 500.30 - ANCM In-Process Start Failure` error

## Expected behavior

Publishing to result in a working Bot.

## Additional context

Fix is to update the App Service to be .NET Core not .NET 4.7

![image](https://user-images.githubusercontent.com/33519520/92437442-d4784500-f19e-11ea-8461-1929d66ebdb6.png)

**Comment by zidaneymar** [comment]
Hi @darrenj , previously I tried to add directline extension and met with the same error, I changed the hosting mode to outofprocess fixing this problem.
![image](https://user-images.githubusercontent.com/9328933/92440460-204ade80-f1df-11ea-8aaa-84481a135d03.png)

**Comment by luhan2017** [comment]
@darrenj , I checked all my provisioned resources, they are all configured to ASP.NET V4.7, and it works well for deployed composer bot. Did you have anything special in your bot? or did you try to use it in directline channel as @zidaneymar mentioned?

**Comment by eluchsinger** [comment]
That error sometimes happens, when you don't have the required .NET SDK installed. For example, it happens when I try to run a .NET Core 5 application on Azure and Azure does not have the .NET Core 5 SDK installed. Maybe this helps.
