### ISSUE TITLE
[Settings] Runtime path should be relative

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#4066]
## Describe the bug
Runtime path should be a relative file path instead of an absolute file path. Otherwise, developers using github to cooperate with each other need to modify the runtime path everytime they pull.

## Version
latest

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to settings
2. Enable custom runtime
3. Check the settings, the file path is an absolute path

## Expected behavior

custom runtime is a relative path

## Screenshots
![image](https://user-images.githubusercontent.com/16643193/92552745-eab3fd00-f293-11ea-96e0-079217ae6527.png)

**Comment by VanyLaw** [comment]
Hi @DingmaomaoBJTU , I am not exactly sure what's you means, do you means you guys are sharing the same bot(dialog files) and each has their only runtime placed in different place? you can change the path to relative before shared and the path won't change  everytime they pull.

**Comment by DingmaomaoBJTU** [comment]
@VanyLaw What I mean is I generate a default runtime but the config record a absolute file path. There is only one runtime and all its setting is by default.
Yes I can change it by my self, but I think this can be a system behavior to set a relative path otherwise I need to figure out why I pull to another disk but it is not work...
