### ISSUE TITLE
How can I send an HTTPS request with the given CA cert?

### ISSUE THREAD

**Issue by weiZhenkun** [microsoft/BotFramework-Composer#4068]
**How can I send an HTTPS request with the given CA cert?
Where is the location for me to save the cert files?**

**Comment by dmvtech** [comment]
Hi @weiZhenkun Can you please give more information on what you are attempting to do? Give more steps/details on what you trying to accomplish and what you have tried. Which HTTPS request are you referring to and which certificate?

**Comment by weiZhenkun** [comment]
I meet an error when use the "Send an HTTP request"  stepper.

> timestamp: "2020-09-11T06:24:41.076Z"
> type: "trace"
> value: "FetchError: request to https://myhostname/api/getId failed, reason: unable to verify the first certificate"
> valueType: "https://www.botframework.com/schemas/error"

I want to get the response from the https://myhostname/api/getId, and the cert of myhostname is a selfsigned certificate.

**Comment by dmvtech** [comment]
> I want to get the response from the ”https://myhostname/api/getId“, and the cert of myhostname is a selfsigned certificate.
> what should I do next?

Ah, gotcha. I'm not sure on that. Let look into it.

Is `myhostname `local to the same machine that Composer is running on? What OS is it?

**Comment by weiZhenkun** [comment]
Composer is running on ```windows 10 with node runtime```, and the ```myhostname``` is my other ```CentOS```. The CentOS server is running with a selfsigned certificate.

I can send the https request to the service by using Postman.

By the way, I want use the One-way authentication in my case, and I think I should put the root cert into the Composer to verdify the server. But I don't find any case to insert the root cert into the Composer to test my case. I think there will be some ways to configure this cert.

Can you help me?  Thank you very much.

**Comment by weiZhenkun** [comment]
Here are the pictures.
![screenshot1](https://user-images.githubusercontent.com/27683687/93288612-d54c4f00-f80e-11ea-9a33-af815df9cbff.png)
![screenshot2](https://user-images.githubusercontent.com/27683687/93288619-dda48a00-f80e-11ea-90e0-6aafe70aeab7.png)

**Comment by weiZhenkun** [comment]
@dmvtech any idea?

**Comment by dmvtech** [comment]
Hi @weiZhenkun I apologize for the delay. I tried to get this reproduced on my end, but I haven't been able to complete that.

Have you tried adding the cert to the Windows 10 machine that composer runs on? Under Trusted Root Certification Authorities

![image](https://user-images.githubusercontent.com/43397658/94085001-c8ee6600-fdbb-11ea-8de9-f21630b6065c.png)

**Comment by dmvtech** [comment]
Hi @weiZhenkun Were you able to try that? Any success?

**Comment by dmvtech** [comment]
Closing due to lack of response. If you continue to have this issue, please comment and we can reopen.
