### ISSUE TITLE
Bots using LUIS getting 401 error after upgrade to V1.1.1

### ISSUE THREAD

**Issue by paul-maher** [microsoft/BotFramework-Composer#4072]
## Describe the bug
I've recently upgraded the Framework Composer to 1.1.1 and now none of my bots which use the LUIS recognizer will work. 

## Version
Version 1.1.1 (from the about dialog)

## Browser
Not using browser, I am using the Bot Framework Emulator

## OS
Windows

## To Reproduce

1. In framework composer use the template to create 'ToDoBotWithLuisSample' sample
2. Enter details of LUIS endpoint in Azure (westeurope + end point key)
3. Click start bot
4. Wait until publish is completed
5. Click test bot in emulator
6. In emulator type 'hi'

> Response is 401 permission denied

## Expected behavior
I expected by utterance to go to my LUIS instance to be classified, instead I get a 401 error

## Screenshots
![image](https://user-images.githubusercontent.com/36451678/92589659-6741de00-f28a-11ea-8c23-53fc9e88446f.png)

## Additional context
I checked in my LUIS authoring instance and the intents were all created, so the publishing aspect seems to work just fine. Its only the subsequent queries of the LUIS instance that fail with a 401

Note also that this was all working 100% last Thursday, then I took the upgrade to version 1.1.1 on Friday and since then it has started behaving like this.

**Comment by cdonke** [comment]
@paul-maher ... usually, this message comes from Bot Channel...
Have you checked if the upgrade cleared the MicrosoftAppId and Secret from the appsettings file?

I have similar issue as well.

**Comment by hibrenda** [comment]
Please check out #4026 and #3904

**Comment by GeoffCoxMSFT** [comment]
Tracking issue in one location - https://github.com/microsoft/BotFramework-Composer/issues/4026
