### ISSUE TITLE
Bot does not work on the direct line channel

### ISSUE THREAD

**Issue by positivo-csena** [microsoft/BotFramework-Composer#4073]
## Describe the bug

Chatbot does not work on the DirectLine channel. The answer to any interaction is "Object reference not defined for an instance of an object."
In web chat it works normally.

## Version

Release 1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. create EchoBot
2. perform deploy
3. publish directline channel

**Comment by luhan2017** [comment]
There is a fix in the SDK side:  https://github.com/microsoft/botbuilder-dotnet/issues/4599

**Comment by cwhitten** [comment]
@positivo-csena as mentioned in https://github.com/microsoft/BotFramework-Composer/issues/4073#issuecomment-689932353, the bug exists in a Composer dependency and is set to be addressed in an upcoming release. We'll keep this open for tracking purposes.

**Comment by crebstock** [comment]
Would this also be the case for interactions within Twilio/Facebook channels?

**Comment by cwhitten** [comment]
@crebstock likely not exactly as the channels behave a bit differently when it comes to locales.

**Comment by luhan2017** [comment]
This should also relate to the local issue which is already fixed in composer main branch. Close this issue, please reopen it if this issue still exists.

**Comment by kdubious** [comment]
@luhan2017 How do I do this: "To mitigate on this, could you try to set the locale for direct line channel?"
