### ISSUE TITLE
Response status code does not indicate success: 401 (PermissionDenied).

### ISSUE THREAD

**Issue by geoffsoper** [microsoft/BotFramework-Composer#4081]
## Describe the bug

When I change the LUIS parameters in the Bot Settings, I start to get the error "Response status code does not indicate success: 401 (PermissionDenied)." in the Bot Emulator

## Version

v1.1.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [X] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1.  Go to Bot Setting
2.  Update luis - > authoringKey with the Primary Key taken from an Authoring Resource at https://eu.luis.ai/user/settings (westeurope)
3.  Update luis - > authoringRegion with the Location taken from the same Authoring Resource at https://eu.luis.ai/user/settings
4.  Restart Bot
5.  Type intent into Bot
6.  Observe error response: "Response status code does not indicate success: 401 (PermissionDenied)."
7.  Restoring authoringRegion to "westus" and authoringKey  to the appropriate Primary Key restores normal operation.

## Expected behavior

User intent should be recognised and bot responds appropriately

## Screenshots

![image](https://user-images.githubusercontent.com/38555263/92728655-09d08e80-f369-11ea-9f2a-e9aa13acd3a1.png)
![image](https://user-images.githubusercontent.com/38555263/92728701-253b9980-f369-11ea-9892-45bf6bc099e4.png)
![image](https://user-images.githubusercontent.com/38555263/92728717-2cfb3e00-f369-11ea-8a16-852856824c08.png)

**Comment by geoffsoper** [comment]
Following a colleague's suggestion, I changed the LUIS details in Bot Settings to the following:
```
  "luis": {
    "name": "HousingPoC",
    "authoringKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "endpointKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "authoringRegion": "westeurope",
    "defaultLanguage": "en-us",
    "environment": "composer",
    "endpoint": "https://uksouth.api.cognitive.microsoft.com",
    "authoringEndpoint": ""
  },
```

Apart from name, these are the same details as he's successfully using. This changes the error to "Response status code does not indicate success: 403 (Forbidden)."

**Comment by luhan2017** [comment]
@geoffsoper So is your authoring resource located in westeurope, but prediction resource located in uksouth?
The composer local publish logic is that:
If endpointKey is missing, which means you didn't bind you luis app with a prediction resource yet. We will use your authoringKey directly. But if endpointKey does exist, you should make sure the prediction resource is bond with the authoring resource.

**Comment by geoffsoper** [comment]
@luhan2017 My (more-technical) colleague has assisted me with binding the prediction resource and authoring resource which seem to have fixed my issue. However, we're both of the opinion that the publishing dialog which requires only the LUIS Authoring key and Luis Authoring Region is insufficient to get someone started with Composer when they're in my position. Can the publishing experience possibly be improved?

**Comment by luhan2017** [comment]
@geoffsoper , Sure, we do have a plan to improve this in R11 #3639

**Comment by tamasschmolcz** [comment]
I face the same issue. AuthoringKey is set and the region is Westeurope. Based on the comment I also added a prediction resource also based in Westeurope. My bot is published to Luis and I can see it in the listing. However, error still appears. Do you have any further idea?

Thanks
