### ISSUE TITLE
BUG: The given key ‘de’ was not present in the dictionary

### ISSUE THREAD

**Issue by eluchsinger** [microsoft/BotFramework-Composer#4094]
## Describe the bug

When I run the bot in the WebChat (in the Browser), I get the error `The given key ‘de’ was not present in the dictionary`. This error did not happen when I used the Bot Framework Emulator.

Turns out, it happens every time the bot asks for example for a confirmation (I don't know if it happens with the other questions, but with suggestions it didn't happen). And my browser is set to a language the bot does not support. In this case it was german. When I switched the Browser's langauge to English (US), the stopped popping up.

## Version

Version 1.1.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge (Chromium)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Make sure the browser is set on a language your bot does not support.
2. Open the bot using a WebChat.
3. Navigate the bot into a question (type: suggestion).
5. See error "The key xxx was not present in the dictionary [...]"

## Expected behavior

I am not sure what to expect. There must be a better way to handle this case. Maybe don't write the error message into the chat, but fallback to the language my bot uses as a default and log the error into the console.

**Comment by v-kydela** [comment]
Thank you for the report, @eluchsinger 

This appears to be related to ongoing efforts to improve localization in the SDK's, as seen in this pending PR for JS: https://github.com/microsoft/botbuilder-js/pull/2534

Composer bots use the C# SDK, and the problem can be seen in [`ConfirmInput`](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs). While [German is supported](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs#L32), the confirm input expects an exact match for "de-de" so just "de" won't work. If [`ConfirmInput.GetCulture`](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs#L157-L170) used [`MapToNearestLanguage`](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptCultureModels.cs#L227-L264) like confirm *prompts* do then that should fix this problem.

Hopefully my JS PR will be merged soon so it can be ported to C#. I don't think there's anything you can do on your end to fix this (except for, say, abandoning confirm inputs or always making sure the client sends a supported locale string). I'll leave this bug open so it can be triaged.

**Comment by eluchsinger** [comment]
@v-kydela thanks for your answer. I fixed the locale on the WebChat Javascript code. Now it always sends `en`, so the language of the browser does not send unexpected locale  strings..

**Comment by cwhitten** [comment]
Seems like we can close this as an issue with the SDK that is being addressed and will show up in an updated version of the runtime template.
