### ISSUE TITLE
Cannot use turn or dialog in validation rules. 

### ISSUE THREAD

**Issue by Reeso1983** [microsoft/BotFramework-Composer#4095]
## Describe the bug

Using a Text Prompt with a simpe LUIS recognizer that has 4 intents (Confirm/Deny/Uncertain/None), I'm trying to validate that either a Confirm, Deny or Uncertain intent was detected (i.e. not None) and if not ask the use to try again (via the invalid prompt). However, both dialog.lastIntent and turn.recognized.intent don't seem to be usable in a validation rule - no matter what i set in the rule if it involves one of those two properties it always evaluates to false and shows the invalid prompt.

As an added "bonus", i can use these properties in the invalid prompt message and they evaluate as expected. So really can't see why i can't access them in the validation rule.

## Version

![image](https://user-images.githubusercontent.com/66425585/92940355-f0057900-f446-11ea-9243-cffa730b6b42.png)

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to a Text Prompt that uses LUIS with multiple intents
2. Click on Other
3. Scroll down to Validation Rules
4. Add a validation rule that uses dialog.lastIntent or turn.recognized.intent
5. Add an Invalid prompt
5. Start Bot
6. Use emulator and get to that part of conversation and observe that the invalid prompt is always displayed.

## Expected behavior

Only when LUIS returns the None intent does it show the invalid prompt.

## Screenshots

![image](https://user-images.githubusercontent.com/66425585/92941333-25f72d00-f448-11ea-83e8-ac2fd08f3de3.png)
![image](https://user-images.githubusercontent.com/66425585/92942200-322fba00-f449-11ea-8073-70a09a1d1b90.png)
![image](https://user-images.githubusercontent.com/66425585/92942340-4ffd1f00-f449-11ea-9c6a-1a8b20cdae96.png)

## Additional context

Note that using another dialog.property that you've set manually beforehand does correctly evaluate.

**Comment by cwhitten** [comment]
@vishwacsena is recognition not run here? would enabling interruptions fix this?

**Comment by vishwacsena** [comment]
@Reeso1983 see here for a working sample using `turn.recognized.intent` in validations. Do you have additional properties configured on the text input? 

@cwhitten if a recognizer is configured on the active dialog, it is run even if `AllowInterruptions` is not set. 

[intentInValidation.zip](https://github.com/microsoft/BotFramework-Composer/files/5212959/intentInValidation.zip)

**Comment by Reeso1983** [comment]
@cwhitten Oddly, if i turn interruptions on. The invalid message generates "Invalid None Confirm".

@vishwacsena I have tried your sample and it does seem to work. The differences between mine and yours are:
- i'm not using an intent trigger to start the dialog initially, but a begin dialog event
- i'm not using suggested actions

**Comment by vishwacsena** [comment]
@Reeso1983 with adaptive dialogs, you need to have a recognizer configured on the dialog that holds the input that is able to classify user input to an appropriate intent. 

Here is an updated sample. 

In this case, I added a new child dialog and added example utterances to None intent via the `User Input` view.

If you wish to have the parent dialog's `OnIntent` triggers to be evaluated while the user is being prompted for information, then you can set `AllowInterruption` to boolean `true` or provide an expression to decide when to allow interruption.

[intentInValidation.zip](https://github.com/microsoft/BotFramework-Composer/files/5220578/intentInValidation.zip)

**Comment by Reeso1983** [comment]
@vishwacsena I think i have found the difference based on your comments. I was sandpitting with the echo bot and the initial parent dialog has no intent triggers. Just the unknown intent:
![image](https://user-images.githubusercontent.com/66425585/93180066-816a3900-f72e-11ea-8439-21fd7dd1797c.png)

Another difference was that your examples create two LUIS Apps. Mine doesn't create one at all for the parent dialog (because the echo bot has no intents) and neither does it for the child one. However, i think this was because i'm referencing an existing LUIS App by including LUIS application information. e.g.

```
> LUIS application information
> !# @app.name = <some-exisiting app name>
> !# @app.versionId = 13.9
> !# @app.culture = en-us
> !# @app.luis_schema_version = 7.0.0
> !# @app.tokenizerVersion = 1.0.0
```
I did this without realising because i'm trying to mimic something in composer that we have already done in code and have a LUIS app for.

Applying my child dialog changes to your sample and replacing your intents with mine, the validation is now working perfectly.

However, is still think there is a bug or two here, as i shouldn't have to add parent dialog intents just to get the child dialog intents usable in validation and the behaviour when i turn on interruptions.

**Comment by vishwacsena** [comment]
Here is a sample that starts with echo bot and shows validation working. There are no known gaps here. You do not have to add intents in the parent dialog in order for this to work. Also you do not need to set anything with allow interruptions. Those are only required if 
- you have multiple user intents that your parent dialog can fulfill
- you would like for specific points in the conversation be interruptable by the user (they can express desire to do something else than answer the current question from the bot).

[EchoBot-0.zip](https://github.com/microsoft/BotFramework-Composer/files/5234312/EchoBot-0.zip)

**Comment by Reeso1983** [comment]
I've taken your example and it works, until I set Allow Interruptions to true. Even if I then add a main dialog intent trigger of help, interruptions still don't work. Is it incorrect of me to expect this to work?

![image](https://user-images.githubusercontent.com/66425585/93455269-08a4e180-f8d4-11ea-90de-091fd1246d3e.png)

**Comment by vishwacsena** [comment]
See attached sample for `allow interruption`. Without seeing your actual bot its hard to tell why it is not working but hopefully you can deduce based on this sample.

[EchoBot-0.zip](https://github.com/microsoft/BotFramework-Composer/files/5239811/EchoBot-0.zip)

**Comment by Reeso1983** [comment]
@vishwacsena I've used your latest attached, you have made the exact change i did to your previous example and it unfortunately doesn't work. Behaves exactly as mine does. When you turn allow interuptions to true the latest luis result is unfortunately the interruption check. See below, there are 3 luis traces. The first two are identical (first image) (And i'm not sure why there are two either) and the 3rd is the luis result for the 'yes' text on the parent dialog (second image).

![image](https://user-images.githubusercontent.com/66425585/93512252-f3ec3c00-f91b-11ea-9fdf-1051cdcc6e79.png)

![image](https://user-images.githubusercontent.com/66425585/93511863-555fdb00-f91b-11ea-99ea-bd4e1c61c595.png)

This is just your example running, i have not changed it.

**Comment by Reeso1983** [comment]
@vishwacsena @cwhitten Can we please re-open this as it has not been resolved? I have updated the title slightly now that we better understand the issue.
