### ISSUE TITLE
There is no way to delete an orphaned intent without using edit code.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#4096]
## Describe the bug

I have an intent which I no longer want and which is not referenced.  The UI does not allow me to delete it.  If I go to the intent, it only lets met edit the content of the intent, not delete it.

I had to edit the whole lu file, find the intent and remove the text.

## Version

1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. try to delete an intent

## Expected behavior

1. I expected the ... to give me a menu with "delete" action on the intent (With a nice fat warning.)
![image](https://user-images.githubusercontent.com/17789481/92943255-697d7700-f407-11ea-89a4-3216b8006717.png)

**Comment by mewa1024** [comment]
related to #4097
