### ISSUE TITLE
Bot Composer ARM Template deploy fail - "Bot name already exists"

### ISSUE THREAD

**Issue by timoleo23** [microsoft/BotFramework-Composer#4098]
## Description

My bot is working all fine in the emulator and I want to deploy it to Azure (following the Readme.md info)
However my deployment fails every time for the same reason : "bot name already registered."
I tried to use the script bot with and without the --app option but I get the same result.
I don’t get why the Bot service sees the app registration already used as it is create as part of the deployment process in the script provided.

```
PS C:\GitHub-local\Bot-Composer\Responding-Cards\WeatherBot\scripts> node provisionComposer.js --subscriptionId=bc49d0e6-XXX-YYYY-ZZZZ-3a1f32b7c6ef --name=BotComposer --appPassword=[MY_PASSWORD] --environment=devyo --createAppInsights=false --createLuisResource=false --createLuisAuthoringResource=false --createCosmosDb=false
Login to Azure:
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DE98PGM9K to authenticate.
> Using Tenant ID: 72f988bf-XXXX-YYYY-ZZZZ-2d7cd011db47
> Creating App Registration ...
> Create App Id Success! ID: 18105099-WWW-UUUU-VVVV-4ac78beae708
> Creating resource group ...
> Validating Azure deployment ...
> Deploying Azure services (this could take a while)...
×
{
  "error": {
    "code": "InvalidBotData",
    "message": "Bot is not valid. Errors: The bot name is already registered to another bot application..  See https://aka.ms/bot-requirements for detailed requirements."
  }
}
** Provision failed **
```

## Version
1.0.2
## Browser
Not relevant here

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. From the Bot Composer, create a new project using the "Echo Bot" template
2. Go under the script floder
3. Run `npm install`
4. Run `node provisionComposer.js --subscriptionId=<YOUR AZURE SUBSCRIPTION ID> --name=<NAME OF YOUR RESOURCE GROUP> --appPassword=<APP PASSWORD> --environment=<NAME FOR ENVIRONMENT DEFAULT to dev>`
5. I get the abov error message during the deployment of the ARM template

## Expected behavior
Successful ARM template deployment

**Comment by benbrown** [comment]
Have you already created an Azure Bot Service registration that you are using?

When using the provisioning script, it will create a NEW registration for you to use in this evironment. Each bot registration has to have a globally unique name - hence `BotComposer` is causing a naming collision because it already exists.

**Comment by timoleo23** [comment]
The app registration and creation of a new app is part of the script by default - I deleted all app registration generated by the bot composer script.

The script fails when the bot service tries to register the app. This app being created as part of the deployment, I don't get how it could be already used.

**Comment by benbrown** [comment]
Are you using the actual name "BotComposer" ?

I believe this is the source of the issue.

**Comment by timoleo23** [comment]
Same issue with "EchoBot"

**Comment by benbrown** [comment]
@timoleo23 Try a name like echobot-timoleo23

**Comment by timoleo23** [comment]
You were right @benbrown, using name "EchoBot2345" solved the issue - I should have check the error more closely.
