### ISSUE TITLE
Help/Check for updates should give some indication when clicked

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#4099]
When I click on check for updates, nothing happens (visually).
Using Release: 1.1.1

Auto update - ON

Early adopters - ON

**Comment by cwhitten** [comment]
@sangwoohaan @hatpick can you check in with @scheyal to see this and consider improvements?

**Comment by hatpick** [comment]
@scheyal Would you please tell us what OS you are running the 1.1.1 release on?
On windows 10 I see the following when I click the "Help/Check for Updates"

![check for updates](https://user-images.githubusercontent.com/1483492/93386527-b05ed880-f81c-11ea-9e5e-72944b8c180b.PNG)

**Comment by hatpick** [comment]
@scheyal I see it now, with "early adapters" off it's showing the issue you are describing.
