### ISSUE TITLE
A way to pass value via querystring to the bot

### ISSUE THREAD

**Issue by johnNarula** [microsoft/BotFramework-Composer#4100]
[https://stackoverflow.com/questions/63318600/how-to-retrieve-query-string-from-microsoft-bot-framework-composer](https://stackoverflow.com/questions/63318600/how-to-retrieve-query-string-from-microsoft-bot-framework-composer)

**Comment by cwhitten** [comment]
Hi @johnNarula - StackOverflow is the correct location to troubleshoot your issue. Closing, and thanks for using Composer!

**Comment by johnNarula** [comment]
It is actually a feature request and I was asked by Vishwac to add it here...
  
  
  
  
  
  
 jN         
  

  
  
>

**Comment by cwhitten** [comment]
Unless I'm misunderstanding the [following SO response](https://stackoverflow.com/a/63853350) is the correct way to achieve your scenario. You use the channelData property send with the Activity coming from the client, and you can access this field in the authoring environment.
