### ISSUE TITLE
Typing too fast in composer results in dropped characters

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4102]
## Describe the bug

I'm on windows and I found that typing in the expression editors is both laggy and buggy. Below is a screenshot of an expression I was just trying to update.  I deleted the characters to the right of "taskId" leaving the string `{"taskId": }` in the editor. I then typed in `skill.tasks.cardTaskId` but ended up with the string below. Every time I type in a reasonably long property path or expression I have to double check it because its either dropped a character or done something wacky like below.

![image](https://user-images.githubusercontent.com/698939/92973056-2f789900-f438-11ea-9f76-4aaca3758114.png)

## Version

1.1.1

**Comment by Stevenic** [comment]
I should add that it's actually not even speed related. I've had it drop an individual keystroke when trying to add in a keystroke it missed. :(

**Comment by Stevenic** [comment]
The bug in the screen shot is worse then i thought. I was just trying to change a variable name in the middle of an expression and it moved one of my characters and the cursor to the end of the expression.

**Comment by LouisEugeneMSFT** [comment]
fyi, I was also able to repro on any type of fields, so this is not specific to expressions
![ezgif com-resize](https://user-images.githubusercontent.com/66701106/92983328-9e191f00-f457-11ea-9c56-03b3bb70f8b8.gif)

**Comment by Stevenic** [comment]
There's actually two separate bugs here that could have the same source...

1.  Characters "often" get dropped. For me its like every other property I type in. I'm having to type super slow so I can catch this as its happening and make corrections.
2.  The cursor "often" jumps to the end of the string when editing text in the middle of an expression or property path. This ones even more annoying then the first bug.

**Comment by Stevenic** [comment]
This seems resolved in the latest private build I'm running... Great job team!
