### ISSUE TITLE
NODE CONTEXT MENU: Add Cut, Copy, and Disable/Enable

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4103]
## Is your feature request related to a problem? Please describe.

Can we get "cut" and "copy" added to this menu? It sucks to have to keep going up to "Edit" every time:

![image](https://user-images.githubusercontent.com/698939/92974055-330d1f80-f43a-11ea-81aa-c7d5b4a2b60a.png)

--
copied from #3950
Currently, to disable actions in the visual editor, user's have to focus on the actions they want to disable and then click the disable button in the editor menu. We should consider adding the enable and disable options to the node's menu options.

![image](https://user-images.githubusercontent.com/39317542/124335007-b7599c00-db4d-11eb-8bb7-3d394b78b884.png)

**Comment by tdurnford** [comment]
Similar ask to https://github.com/microsoft/BotFramework-Composer/issues/3950

**Comment by Stevenic** [comment]
Those would be good adds as well

**Comment by cwhitten** [comment]
@Stevenic why not use the keyboard commands? `ctrl+c`

**Comment by Stevenic** [comment]
@cwhitten  because I didn't know they were supported :)

You should list them on the menu...

**Comment by JaskeeratBedi-cmk** [comment]
great point. Design is working on improving the contextual menu..

**Comment by mewa1024** [comment]
Combined #3950 with this one. Design solution should address both.

**Comment by mewa1024** [comment]
Captured in NODE CONTEXT MENU: Add actions to Cut, Copy, Move, Delete, and Disable/Enable #3734, so closing.
