### ISSUE TITLE
C# runtime no longer registers BotCallbackHandler

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4104]
## Describe the bug

The latest version of the composer runtime removed from the `ComposerBot` constructor, the last line of the initialization code below which registers the callback handler for the bot.  This broke several custom actions I created which depend on this callback being registered. I can manually add the line back into all my new runtimes but I'm just curious why this was removed? That's technically a breaking change...

```C#
            this.dialogManager.InitialTurnState.Set(skillClient);
            this.dialogManager.InitialTurnState.Set(conversationIdFactory);
            this.dialogManager.InitialTurnState.Set<BotCallbackHandler>("BotCallbackHandler", this.OnTurnAsync);
```
## Version

1.1.1

**Comment by cwhitten** [comment]
@luhan2017 can you take a look at this?

**Comment by tracyboehrer** [comment]
Moving to https://github.com/microsoft/botframework-core/issues/42, closing this issue.
