### ISSUE TITLE
Bot shows loading but never opens

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/BotFramework-Composer#4108]
## Describe the bug

Upon opening Bot Framework Composer, I launch my bot via the "Recent Bots" list, and it shows a loading (show below) but never opens. I tried opening from the open dialog as well and the same issue. 
![image](https://user-images.githubusercontent.com/23587151/93041900-4cb58f00-f613-11ea-9322-61781714693e.png)

## Version

Bot Framework Composer

                Version:  1.1.1
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

I am using the Mac Desktop application.

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

I was able to load my bot in the previous version, but now It doesn't load and I have no errors/warnings to indicate what could be the issue.

**Comment by cwhitten** [comment]
@VasuBhog I've reached out in MS Teams to follow up here..

**Comment by cwhitten** [comment]
Resolved offline. There were malformed .dialogs that caused the loading issue.
