### ISSUE TITLE
Provisioning of Azure resources in SouthAfricaNorth fails

### ISSUE THREAD

**Issue by gbelenky** [microsoft/BotFramework-Composer#4114]
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. node provisionComposer.js --location=SouthAfricaNorth --subscriptionId=mysubscriptionid --name=mybotnamegb3 --location=SouthAfricaNorth --createLuisAuthoringResource=false --appPassword=mypassword --environment=PREPROD --createLuisResource=false --createLuisAuthoringResource=false --createQnAResource=false 

2. see error:
Login to Azure:
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXX to authenticate.
> Using Tenant ID: XXXXXXXXX
> Creating App Registration ...
> Create App Id Success! ID: XXXXXXXXXXXXXXXXXXX
> Creating resource group ...
> Validating Azure deployment ...
! Error: Deployment template validation failed: 'The template resource 'Microsoft.CognitiveServices/accounts/mybotnamegb3-PREPROD-qna' reference to 'Microsoft.Web/sites/mybotnamegb3-PREPROD-qnahost' requires an API version. Please see https://aka.ms/arm-template for usage details.'.
+ To delete this resource group, run 'az group delete -g mybotnamegb3-PREPROD --no-wait'
** Provision failed **

**Comment by cwhitten** [comment]
@luhan2017 can you please take a look at this?

**Comment by zidaneymar** [comment]
Hi, @gbelenky , this is a [known issue](https://github.com/Azure/azure-sdk-for-js/issues/10186) for arm template, I have reported it to the Azure team. Currently a simple workaround is **setting the createQnAResource to true** (then the script will create several qna resources on Azure, if you don't need qna, you could delete them on Azure portal manually).

I'm still working on fixing this issue by splitting the arm template to two different parts.
