### ISSUE TITLE
Object reference not set to an instance of an object on Facebook/Twilio channels

### ISSUE THREAD

**Issue by crebstock** [microsoft/BotFramework-Composer#4118]
A bot created in composer which only replies to an unknown intent and greets a user runs just fine via facebook and Twilio.  However if you add any complexity to it such as prompting for a question or adding QnA, it reponds once with Object reference not set to an instance of an object and then never responds again.  I'm using the azure web app option for publishing.  Even publishing the default echo bot creates this issue over Facebook and Twilio.  The bot still works just fine doing a web chat test as well as locally testing.

I asked on this issue: https://github.com/microsoft/BotFramework-Composer/issues/4073 whether it was related and it just effects channels other than the direct line channel.

I'm using composer 1.1.1 which is using 4.10.2 SDK on macOS

**Comment by cwhitten** [comment]
@luhan2017 can you please take a look at this?

**Comment by luhan2017** [comment]
@crebstock，could you please check if the locale is set in the facebook and Twilio channels? it could relate to this issue #4073, and we already have a fix on the sdk side. You can try to set the locale to mitigate it for now.

**Comment by cwhitten** [comment]
> @crebstock，could you please check if the locale is set in the facebook and Twilio channels? it could relate to this issue #4073, and we already have a fix on the sdk side. You can try to set the locale to mitigate it for now.

Sorry @crebstock, if this is the case I was incorrect on https://github.com/microsoft/BotFramework-Composer/issues/4073

**Comment by crebstock** [comment]
Where would you edit locale specific to the channel?  I don't see those settings either in the channel registration?  Would this be done in composer or is it a setting on facebook/twilio?

**Comment by nitroin** [comment]
Just an head up as we're experiencing the exact same issue.

**Comment by nitroin** [comment]
Today we tried Telegram channel as a fallback. The same issue arise.

To repro the issue you can try to deploy the template "Todo with LUIS".

**Comment by luhan2017** [comment]
> Where would you edit locale specific to the channel? I don't see those settings in the channel registration. Would this be done in composer or is it a setting on facebook/twilio?

It should be a setting on facebook/twilio.

**Comment by luhan2017** [comment]
> Telegram

Did you set the locale for Telegram channel? you can do this to mitigate this issue. We will have a patch release for this soon.

**Comment by nitroin** [comment]
@luhan2017 thank you for your feedback. Can you please elaborate how to set the locale and on which entity?

I was unable to find any setting that reseamble what you indicate on Bot Composer or in the Azure Portal. Thank you!

**Comment by nitroin** [comment]
Seeing this as a stale issue, is there something we (the community) can actionate to progress this issue?

We we'll be keen to arrange a PR if any hints or insights are provided.

**Comment by cwhitten** [comment]
Hi @nitroin - @luhan2017  has been on holiday and returning tomorrow. Thank you for your patience.
