### ISSUE TITLE
Cannot connect to storage

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#4123]
installed Mac build 1.1.1 release.
Installed, Cannot open or save bots as it cannot find  storage location.

![Screen Shot 2020-09-14 at 3 29 04 PM](https://user-images.githubusercontent.com/48503434/93144597-381ed880-f69f-11ea-9b2a-74f70dce3a39.png)

How do I fix this?

![Screen Shot 2020-09-14 at 2 59 22 PM](https://user-images.githubusercontent.com/48503434/93144674-66041d00-f69f-11ea-99fd-b4c0c40f05a2.png)

**Comment by cwhitten** [comment]
@mareekuh did you drag the executable from the `Downloads` directory to `Applications`? This is important for access to the filesystem.

**Comment by mareekuh** [comment]
Ugh it’s this old bug… so sorry I knew this was an issue )=
