### ISSUE TITLE
Composer throws extensions.reduce is not a function

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-Composer#4124]
## Describe the bug
The `useLinks` hook is causing an error because the value returned from `useRecoilValue(extensionsState)` appears to be a string instead of an array.

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Pull latest changes from Main
1. Run `yarn` && `yarn build`
1. Run `yarn start:dev` - `yarn start` didn't result in the same behavior..?
1. Observe error when navigating to Composer in Browser

## Screenshots

![image](https://user-images.githubusercontent.com/17039790/93146942-d43ee480-f68b-11ea-93da-38f94aa8cd79.png)

## Additional context
https://github.com/microsoft/BotFramework-Composer/blob/673f961ac3c6765b6598624215c909699188e2f8/Composer/packages/client/src/utils/hooks.ts#L31

**Comment by a-b-r-o-w-n** [comment]
@tdurnford I am unable to reproduce this. What is the value of `useRecoilValue(extensionsState)`?

**Comment by tdurnford** [comment]
It's not reproing for me either now. Previously, `useRecoilValue(extensionsState)` was resolving to a `string`. Not sure what changed. I'll close the issue for now, and if it happens again I'll reopen it.
