### ISSUE TITLE
Composer cannot access HD to retrieve or save bugs

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#4139]
Installed 1.1.1 on Mac w Catalina.
Composer is installed to and run from 'apps' folder
Upon running composer, it shows an error that it cannot 'auto-update'
Upon open new or start from template, it cannot find the file location for bots on my harddrive

Result:
- cannot open from HD
- cannot open and from template (As it requires saving to new file)

![Screen Shot 2020-09-14 at 3 29 04 PM](https://user-images.githubusercontent.com/48503434/93240642-3c97cf80-f739-11ea-9a22-969ff3ac47f5.png)
![Screen Shot 2020-09-14 at 2 59 22 PM](https://user-images.githubusercontent.com/48503434/93240645-3dc8fc80-f739-11ea-806c-526d07b4c89e.png)

**Comment by cwhitten** [comment]
Issue was resolved offline by deleting an old BotFrameworkComposer/ folder providing stale data.
