### ISSUE TITLE
Update composer support for form dialog triggers and actions

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#4149]
This is to add the necessary hard-coded groupings and configuration to support the newly used action and trigger types from form dialogs.

**Comment by yeze322** [comment]
I'm working on https://github.com/microsoft/BotFramework-Composer/pull/4079 which is related to this issue.
Here is the draft definition of Trigger's uischema https://github.com/microsoft/BotFramework-Composer/pull/4014.
