### ISSUE TITLE
Provisioning bot resources fails

### ISSUE THREAD

**Issue by knightmeister** [microsoft/BotFramework-Composer#4154]
## Describe the bug

I am attempting to follow the instructions [on docs](https://docs.microsoft.com/en-us/composer/how-to-publish-bot) to create the resources and get the JSON publish profile.

This is failing, first with `User not found` and then after I append the tenant ID it fails with `Insufficient privileges to complete the operation`.

## Version

Composer 1.1.1
Node 12.16.3

## OS

- [ ] Windows

## To Reproduce

1. Open Composer
2. Create a new EchoBot project
3. Open terminal/powershell/whatever and `cd` to the EchoBot directory and then cd into `scripts`
4. Run `npm install`
5. Run, per the documentation `node provisionComposer.js --subscriptionId=<YOUR AZURE SUBSCRIPTION ID> --name=<NAME OF YOUR RESOURCE GROUP> --appPassword=<APP PASSWORD> --environment=<NAME FOR ENVIRONMENT DEFAULT to dev>`

I am using the following values:
subscriptionId: The value as seen in the Subscription ID column in the Subscriptions [page of Azure](https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade)
name: EchoBotTest
appPassword: 8 random characters
environment: dev

When using this command, I get the following output:
````
> Using Tenant ID: [guid of tenant id]
> Creating App Registration ...
User was not found.
** Provision failed **
`````

Interestingly, this is not the tenant ID I get from `az login`.

When I execute the command with `--tenantId=[tenant id from az login]` I get the following output:
````
> Creating App Registration ...
Insufficient privileges to complete the operation.
** Provision failed **
````

For background: I am using my own Microsoft account, which has been made owner of a colleagues (MSDN) Azure account.

## Expected behavior

I would expect the provisioning to succeed and to get the publishing JSON document.

**Comment by knightmeister** [comment]
I just thought I would provide an update to assist in diagnosing this issue.

I was trying to provision the resources in a colleagues Azure account, for which I had the permissions as an account owner - this was failing.

I activated my MSDN Azure Benefits and was able to create it in my own Azure account.

**Comment by dmvtech** [comment]
Thanks for the follow up @knightmeister. Glad you got it working.

**Comment by knightmeister** [comment]
> Thanks for the follow up @knightmeister. Glad you got it working.

No worries. To be clear though, there is a bug here that should probably be investigated at some point; I don't expect everyone using Composer is going to have their own Azure account.
