### ISSUE TITLE
Enforced autoEndDialog for skills

### ISSUE THREAD

**Issue by ltwlf** [microsoft/BotFramework-Composer#4157]
Hi there,

in a project (current main branch), I have the issue that the autoEndDialog prop gets hard overwritten for the root dialog when I use the composer bot as a skill.  I rather would prefer to use the explicit user configured setting. Should I submit a PR to change this?

Reference:
https://github.com/microsoft/BotFramework-Composer/blob/5668e0b8f683b5cef370aad53558c0621e41148a/runtime/dotnet/core/ComposerBot.cs#L51

Best wishes,
Christian

**Comment by luhan2017** [comment]
@ltwlf We need this to be true, when it is skill mode. otherwise the conversation will always stay in skill bot, and will never end. 
Could you explain more on how to you want to change this?

**Comment by tdurnford** [comment]
@Itwlf thank you for the input and the contributions. I'm closing this issue in favor of https://github.com/microsoft/BotFramework-Composer/issues/4222.

**Comment by ltwlf** [comment]
@luhan2017 

> We need this to be true, when it is skill mode. otherwise the conversation will always stay in skill bot, and will never end.
> Could you explain more on how to you want to change this?

This exactly what I want. I want the control when a skill ends when I set in the UI autoEndDialog to false. 

The requirement is based on a real project. We have a dispatcher bot and call this composer skill. The skill can show market analytics for different brands. We remember some context information and the user can do many queries, Currently the skill after the first report. When the user then ask for second market the dispatcher will not route him to the skill because some conext is missing. We want to end the skill when we see I high evidence in the dispatcher model for an intent switch. We will cancel the dialog then in the consumer or when we recognize a cancel intent in the skill.

**Comment by lzc850612** [comment]
@carlosscastro can you keep this in mind as you look at the implementation of IsSkill function work? Thanks.

**Comment by zhnbss** [comment]
I am also having difficulty in my project with "autoEndDialog". This control is essential for the execution of the project I am currently doing. Is there any way around?

**Comment by stevengum** [comment]
@carlosscastro do you have any updates on this issue?

**Comment by ltwlf** [comment]
We are just testing a fix. If it works like expected, I’m going to start a pull request.

**Comment by ltwlf** [comment]
@stevengum @carlosscastro I create a PR #4440 for this issue. 
@zhnbss can you please confirm the desired behavior?

**Comment by zhnbss** [comment]
@ltwlf the fix looks great by me. Works as expected. Thanks

**Comment by sgellock** [comment]
@gabog can you drive this while Carlos is out?
