### ISSUE TITLE
Error Code 500 when Bot has multiple dialogs (POST 500 directline/conversations/<conversationId>/activities)

### ISSUE THREAD

**Issue by JonasBergholz** [microsoft/BotFramework-Composer#4159]
Hello,

I have the issue, that my new bot doesn't want to start properly, when I have multiple dialogs and program the ability to change them. The LUIS itself seems to work fine, so the triggers doesn't seem to be the problem. But when I set the trigger to change to a different dialog, it gives me the error 500 when it starts, even before the welcome message. When I remove the dialog change and just say that it should send a response in that trigger, it works fine again. I've built a different bot, that seems to work just fine with that dialog change with trigger usage.

It gives me this Post message with this JSON in the response:
POST 500 directline/conversations/<conversationId>/activities
![image](https://user-images.githubusercontent.com/61690258/93363589-c46bff80-f847-11ea-90dd-76ecfee43c85.png)

Thanks in advance, for all who have or try to find a solution to this problem.

**Comment by cwhitten** [comment]
Hi @JonasBergholz 

Something is likely broken in your bot, likely within the configuration of the Dialog that is causing the different in behavior. What you say the LUIS itself seems to work fine, what do you mean? Are you seeing LuisTrace logs when using the Emulator?

**Comment by dmvtech** [comment]
Hi @JonasBergholz 

Checking in. Can you please give us more information per Chris's questions?

**Comment by dmvtech** [comment]
Hi @JonasBergholz Just touching base once again. Can you please give us some more info? Or is this resolved for you?

**Comment by dmvtech** [comment]
Hi @JonasBergholz I'm closing this one as we haven't heard from you in some time and we still need further information to proceed. Please reopen or let us know if you are still having issues and need assistance.

**Comment by df9723** [comment]
I am also having the same issue, with receiving an error 500 when I start the bot Emulator from Framework Composer.
My bot also has multiple dialogs. My configurations for LUIS and QnA maker appear to be correct. Not sure where to troubleshoot. Any help is greatly appreciated. 
Thank you

![image](https://user-images.githubusercontent.com/63733786/97202264-c485e600-1789-11eb-8bf7-17bc01edc525.png)

**Comment by dmvtech** [comment]
@df9723 Are you supplying appid/apppassword in either the Bot/Composer or Emulator? If you have them set in the bot/app settings, then they need to be supplied in the Emulator (which should be done by default). Additionally, makes you have the right values in the correct settings, if so. (In settings, `MicrosoftAppPassword` is listed first, `MicrosoftAppId` second).

Does this only happen with multiple dialogs? Are you able to share a repo (sanitized of personal/sensitive info) of your bot so that we can attempt to reproduce?

**Comment by JonasBergholz** [comment]
I'm sorry that I didn't answer. Moved on to another project. It is the same
problem that df9723 has. I have checked my settings and I have provided an
AppId and AppPassword. I'm able to publish, but it only works, if I have a
single dialog. Can't share my repo or anything like that.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Di., 27. Okt. 2020 um 23:37 Uhr schrieb Dana V <notifications@github.com

**Comment by df9723** [comment]
I do have appid/apppassword setup in the Bot/Composer and verified that I am using the correct values setup in the Azure App Registration. Along with multiple dialogs, I am making calls to multiple QnA knowledge bases. Not sure if that would cause an issue. Also unfortunately I am unable to share my bot configuration.  Thanks again for your help.

**Comment by dmvtech** [comment]
Hi @JonasBergholz and @df9723 

We're going to need a bit more to go on unfortunately. Can you give me explicit and simple instructions on how to reproduce? @df9723 Are you able to share a repo of a reproduction of the issue? 

If you can give me the simplest repro steps, that will go a long way to determine what is going on.

**Comment by df9723** [comment]
Hi dmvtech,

I have attached some details on how we are structuring our bot. 
Thanks

[500error.pdf](https://github.com/microsoft/BotFramework-Composer/files/5465841/500error.pdf)

**Comment by df9723** [comment]
SOLVED: I no longer receive the error 500 message within Emulator, once I removed all routes back to the main dialog from a child dialog and any repeat of the main dialog, while in the main dialog. 
Hope this helps.

**Comment by dmvtech** [comment]
Ah, thank you @df9723 Yeah, as you have found, you don't want to do that. Assuming your FAQ dialog has `Auto end dialog` set to true, you shouldn't need to do much else as it will just bubble up to the calling dialog. You could, of course, specifically add an `End dialog` action in place of where you were calling the Main dialog, but it's not needed if `Auto end dialog` is set. Optionally, you could also use an if branch and check on a value (like `user.foundallaswers` or something), and then have your FAQ logic inside that. Lots of options actually.

@JonasBergholz is your logic anything like this above? (are you calling the main dialog from another dialog?)

**Comment by df9723** [comment]
Hi dmvtech,
Yes I was calling the main dialog from another dialog. To mitigate the issue, I call a hero card with selections. But I appreciate the additional info. I am new to using the Framework Composer.
Thanks again.

**Comment by dmvtech** [comment]
@JonasBergholz I'm closing this. If the solution wasn't the same for you, please let us know.
