### ISSUE TITLE
Why does the provisioning process create an Azure Search client & qnahost app service

### ISSUE THREAD

**Issue by knightmeister** [microsoft/BotFramework-Composer#4165]
Running the provisionComposer.js command as recommended in the [docs](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)

````
node provisionComposer.js --subscriptionId=[guid] --name=[name] --appPassword=[Pwd] --environment=dev
````

Creates many resources. These are all self explanatory with the exception of the `[name]-dev-qnahost` and `[name]-dev-search` resources. 

I'm particularly curious about the search service given the high cost of the service.

**Comment by dmvtech** [comment]
@knightmeister  QnAMaker resources require both of these. If you create a QnAMaker resource outside of a bot or Composer, you will see these created as well. I'm not familiar with the intricacies of these resources and why they're needed for QnAMaker (it's not really in our Bot wheelhouse), but you may find some more information [here](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/set-up-qnamaker-service-azure). I know you can configure the search to be a free plan, but that will come with some limitations on how many indexes (read [published] knowledgebases) you can have. and of course the host web site can be (re)configured as well, as any app service can be.

**Comment by dmvtech** [comment]
Closing as it seems this is answered.

**Comment by crebstock** [comment]
@dmvtech I just came across this after going through billing support.  Isn't there limits to how many free tier search services you can have?  This could be a real problem for anyone who would want to have multiple bots running.  Even low use bots have a significant monthly spend because of that search service.

**Comment by dmvtech** [comment]
Hi @crebstock I don't know about Free search services per subscription, but [there is](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/limits#knowledge-bases) a limit on how many indexes you can have for a Free one. I think the key would be consolidating production QnA resources into one or more  (obviously not free) resource, and just using the free one for a development QnA kb.
