### ISSUE TITLE
server/src/locales/en-US.json will be updated every time composer build & run.

### ISSUE THREAD

**Issue by VanyLaw** [microsoft/BotFramework-Composer#4166]
## Describe the bug
After I pull the main and build and run it. the en-Us will be updated. Are these changes need to be checked into main branch?

FYI.
![image](https://user-images.githubusercontent.com/21174180/93415129-5f5eeb00-f8d5-11ea-9f4a-c3c784f77c66.png)
![image](https://user-images.githubusercontent.com/21174180/93415146-684fbc80-f8d5-11ea-8b7e-7fdc8fb63a0e.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
@beyackle can you comment here?

**Comment by boydc2014** [comment]
related in https://github.com/microsoft/BotFramework-Composer/pull/4225
