### ISSUE TITLE
Allow deep-linking to support $designer.id based lookup

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#4170]
Currently we use an index-based deep-linking system, like:

` /bot/37059.088861680364/dialogs/deleteitem?selected=triggers[0]&focused=triggers[0].actions[2].elseActions[1].elseActions[0]`

where you can see the index of the triggers and actions clearly in query parameter.

PVA has asked that we also support ID based lookups, as their storage layer breaks apart the triggers configured on a dialog and stores them in different database records, so programmatically understanding what index to provide in a deep-link is more work than they would like it to be. They do however have and use `$designer.id` for these types of lookups and have requested that we support this in the deep-linking mechanism, like so:

`
 /bot/37059.088861680364/dialogs/deleteitem?selected=triggers["479346"]&focused=triggers["479346"].actions["419199"].elseActions["803801"].elseActions["747071"]`

**Comment by yeze322** [comment]
@cwhitten Does it mean that we will support two kinds of URI format and can switch between them via composer settings?
