### ISSUE TITLE
[UI Plugin] support multiple publishes and pages in one plugin

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#4174]
## Is your feature request related to a problem? Please describe.

Currently in our definition https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/plugins/sample-ui-plugin/package.json, publish and page are keys which means we could only add one for each in one plugin.

## Describe the solution you'd like

Change it to array so we could add multiple publishes and pages in one plugin

**Comment by cwhitten** [comment]
@xieofxie what are you trying to do?

**Comment by xieofxie** [comment]
Hi @cwhitten I may implement a test page plugin as what I did before (without any schedule).
But this does not block me. I just found this design limitation and bring it up.

**Comment by xieofxie** [comment]
Changed to array now.
