### ISSUE TITLE
[Plugin] how to get current project id?

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#4175]
## Is your feature request related to a problem? Please describe.

Our apis are based on project id https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/server/src/router/api.ts. However, I don't find a way to get current project id (like here https://github.com/microsoft/BotFramework-Composer/tree/main/Composer/plugins)

## Describe the solution you'd like

Provide a function so in plugin (especially ui-plugin, web route plugin), we could do actions based on current project.

**Comment by boydc2014** [comment]
@xieofxie can you tell us more about which type of plugin you are trying to build and the scenarios you are facing? 

the project id is in the "BotProject" object, which we exposed in the publish method in the publishing protocol , see here https://github.com/microsoft/BotFramework-Composer/blob/9ba5e8412eb81852fdd140b692ad46528f9c7b1b/Composer/plugins/localPublish/src/index.ts#L61, so if it's a publishing plugin, you should be able to access that id.

**Comment by xieofxie** [comment]
Hi @boydc2014 I have thought about ui-plugin, web route plugin.

But later I think web route is not related as I could build one like `/custom_api/:project_id` (do we support this in web route plugin? I don't check it)

For ui-plugin, it should be provided as a function/property. Suppose I want to add a test page with a button **Add New Test Dialog File**. If I don't know current project, I couldn't find a place to store the file.

Thanks~

**Comment by xieofxie** [comment]
I could use `/custom_api/:project_id` in web route plugin, so it is not an issue for web route. But I think it is still an issue for ui plugin.

**Comment by xieofxie** [comment]
useProjectApi from "@bfc/extension-client" has projectId now
