### ISSUE TITLE
Microsoft.Bot.Builder.Dialogs.Adaptive.Recognizers.MultiLanguageRecognizer - Value cannot be null

### ISSUE THREAD

**Issue by UmaPrelude** [microsoft/BotFramework-Composer#4180]
Hi,

I am facing the below issue in email channel, I have set all the required LUIS settings in bot settings, i am not sure what i am missing, if i get some clue, it will help me a lot.

![image](https://user-images.githubusercontent.com/65938026/93601769-4cd0d880-f9df-11ea-8d18-e8cc0be47804.png)
![image](https://user-images.githubusercontent.com/65938026/93602530-57d83880-f9e0-11ea-8288-28c19bff6e3d.png)

**Comment by v-kydela** [comment]
@cwhitten - This looks like it could be another case of adaptive dialogs not knowing how to handle missing or unrecognized locales in incoming activities.

@UmaPrelude - Please provide the following:

1. Repro steps
1. Your relevant dialog files
1. Links to documentation/samples you've been following

**Comment by luhan2017** [comment]
I saw the fix was cherry-picked in 4.10 branch(https://github.com/microsoft/botbuilder-dotnet/commits/4.10), but I didn't find a patch release package, could we ask the sdk team to have a new patch release(4.10.4) on this and include that fix in composer. We have received several issues related to this already. @cwhitten @v-kydela

**Comment by UmaPrelude** [comment]
> @cwhitten - This looks like it could be another case of adaptive dialogs not knowing how to handle missing or unrecognized locales in incoming activities.
> 
> @UmaPrelude - Please provide the following:
> 
> 1. Repro steps
> 2. Your relevant dialog files
> 3. Links to documentation/samples you've been following

Steps :
1. Created Composer Bot with Recognizer type as LUIS
2. created an intent and checking the channelid as email in the flow to populated an adaptive card.
3. Generated the custom runtime as well. 
4. published it and configured the email channel 
5. sent the relevant utterance to trigger the intent, but when it comes to custom runtime 
"        await this.dialogManager.OnTurnAsync(turnContext, cancellationToken: cancellationToken)" , it throws the mentioned error.

Dialog file looks like 
![image](https://user-images.githubusercontent.com/65938026/93896309-668b5c00-fd0e-11ea-9a35-0fdb3f7706cb.png)

One of the reference used for entity extraction
https://docs.microsoft.com/en-us/composer/how-to-define-advanced-intents-entities

Please send your responses/patches to fix this issue at the earliest.

**Comment by benbrown** [comment]
A fix for this issue is going to be in an upcoming patch to be released next week.

**Comment by UmaPrelude** [comment]
Thanks ben, expecting to get the update once released.

**Comment by cwhitten** [comment]
@UmaPrelude this will be addressed in an upcoming release. For now, you can eject your runtime and change your botframework libraries to the preview versions, which will have the fix. https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder

**Comment by UmaPrelude** [comment]
Hi Chris, 
When i tried to install with the command 
Install-Package Microsoft.Bot.Builder -Version 4.10.0-preview-200707-143948 -Source https://botbuilder.myget.org/F/botbuilder-v4-dotnet-daily/api/v3/index.json

I am getting the below error and trying to solve.

**Comment by UmaPrelude** [comment]
> @UmaPrelude this will be addressed in an upcoming release. For now, you can eject your runtime and change your botframework libraries to the preview versions, which will have the fix. https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder

Installed couple of updates and now it is working. Thanks.

**Comment by stevengum** [comment]
Closing as @UmaPrelude has been unblocked. The fix will be made mainstream in the 4.11 release of the SDK and composer.
