### ISSUE TITLE
Update the uiSchema, adding the mapping between components and Intellisense options.

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#4187]
Part of updating schema to support better intellisense

**Comment by GeoffCoxMSFT** [comment]
Following up with Andy to see if we need to regen uischema from the SDK.

**Comment by cwhitten** [comment]
> Following up with Andy to see if we need to regen uischema from the SDK.

@GeoffCoxMSFT when we take new runtime packages that include those changes the generated uischema should include it.
