### ISSUE TITLE
Build a graph of components <-> variables to be able to know if a variable can be reached from a specific component

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#4200]
Part of investigating how to make intellisense variables context specific

**Comment by cwhitten** [comment]
I seeded Louis with this problem back in R10 discussing it at length with him, and I haven't seen a proposed solution, yet. Is this actually happening?

**Comment by LouisEugeneMSFT** [comment]
Hi @cwhitten . I see this as a stretch deliverable, probably not making the cut for R11. But if we consider this important, happy to revisit priorities.

**Comment by GeoffCoxMSFT** [comment]
This work is no longer applicable as it is handled under other feature work for R12.
