### ISSUE TITLE
Fix current validation which is not working correctly (such as expressions) 

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#4202]
@LouisEugeneMSFT - we need to call out the specific instances here if you plan on fixing all at once, or you can file individual bugs per instance.

**Comment by LouisEugeneMSFT** [comment]
This should be fixed.
Below is an example.

Before:
![image](https://user-images.githubusercontent.com/66701106/97914969-8c405380-1d05-11eb-804b-6dcb3ed2e7aa.png)

Now:
![image](https://user-images.githubusercontent.com/66701106/97915022-a11ce700-1d05-11eb-8322-688d77aadc94.png)

I will reopen issues with specific examples if I see new problems.
