### ISSUE TITLE
Composer overwrites recognizer settings

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#4205]
## Describe the bug

Recognizers have settings, in particular LUIS Recognizer has settings.  Composer overwrites the .lu.dialog file instead of maintaining the settings.

## Version

1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a LU file
2. Change the settings on the lu file
3. starting the bot will blow away your settings
```
{
    "$kind": "Microsoft.LuisRecognizer",
    "id": "LUIS_msmeeting-actions",
    "applicationId": "=settings.luis.msmeeting_actions_en_us_lu",
    "endpoint": "=settings.luis.endpoint",
    "endpointKey": "=settings.luis.endpointKey",
    "predictionOptions": {
        "includeInstanceData": true
    },
}
```

THIS IS WHAT THE COMPOSER GENERATES:
```
{
    "$kind": "Microsoft.LuisRecognizer",
    "id": "LUIS_msmeeting-actions",
    "applicationId": "=settings.luis.msmeeting_actions_en_us_lu",
    "endpoint": "=settings.luis.endpoint",
    "endpointKey": "=settings.luis.endpointKey"
}
```
## Expected
1. It should not rewrite the file if it doesn't need to
2. It should maintain settings if it does.

**Comment by boydc2014** [comment]
@tomlm did you manually edited the generated .lu.dialogs?


the context, we don't support luis-predication options in bf-cli (which we previously support then reverted the support), because of predication options is not expression
https://github.com/microsoft/botbuilder-dotnet/issues/4149
