### ISSUE TITLE
Consider adding additional fields to ui schema

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-Composer#4208]
## Description
Currently, to add additional fields to the Property Editor, you have to override the root field with a component that renders the additional fields and the `<ObjectField />` that renders the rest of the form. For example, the Select Skill Dialog's plugin config overrides the root field with the `<BeginSkillDialogField />` component, which renders an additional field - `<SelectSkillDialog />` - and the `<ObjectField />` to render the rest of the form.  

There is also currently no way to add additional fields in the middle of the form - the additional fields either have to be at the beginning or the end of the form.

#### PluginConfig
```js
const config: PluginConfig = {
  uiSchema: {
    [SDKKinds.BeginSkill]: {
      form: {
        field: BeginSkillDialogField,
      },
    },
  },
};
```

#### Field Override 
```jsx
export const BeginSkillDialogField: React.FC<FieldProps> = (props) => {
  const { value, onChange } = props;

  return (
    <React.Fragment>
      <SelectSkillDialog value={value} onChange={onChange} />
      <ObjectField {...props} />
    </React.Fragment>
  );
};
```
## Proposed solution
We should consider adding an `additionalFields` option to the the `UIOptions`. This would allow us to easily add additional fields and custom behavior to the form without having to override the root field. Additionally, we could have some mechanism to add the `additionalFields` to the `order` UI Option -  `order: ['skillAppId', 'additionalFields[0]', '*', 'activityProcessed']` - so we can add fields anywhere in the form. 
#### UIOptions
```js
export interface UIOptions {
...
  // Custom fields added to the form
  additionalFields: FieldWidget[],
...
}
```

## Additional Context
https://github.com/microsoft/BotFramework-Composer/blob/9ba5e8412eb81852fdd140b692ad46528f9c7b1b/Composer/packages/ui-plugins/select-skill-dialog/src/index.ts#L15

https://github.com/microsoft/BotFramework-Composer/blob/9ba5e8412eb81852fdd140b692ad46528f9c7b1b/Composer/packages/ui-plugins/schema-editor/src/formSchema.ts#L12
@a-b-r-o-w-n thoughts?

**Comment by a-b-r-o-w-n** [comment]
Should the `additionalFields` type be expanded to allow the form builder to render default fields as well?

Maybe something like:
```ts
type AdditionalField = JSONSchema6 | { name: string; field: FieldWidget };
type AdditionalFields = AdditionalField[];
```

This would also allow users to reference the field name in other ui schema properties.

**Comment by tdurnford** [comment]
Yea, I think supporting JSONSchema7 in the `additionalFields` is a great idea.

**Comment by a-b-r-o-w-n** [comment]
Another thing to think about though is handling the `onChange`. What would be the behavior of an additional field defined with a json schema?

**Comment by tdurnford** [comment]
Yea, that's a good question. The `select-skill-dialog` ui-plugin passes the object's `value` and `onChange` handler to the additional field because it needs to set multiple multiple fields in the object when the user selects a skill - `skillEndpoint` and `skillAppId`. However, that may not be ideal for JSONSchema7 additional fields.

```jsx
export const BeginSkillDialogField: React.FC<FieldProps> = (props) => {
  const { value, onChange } = props;

  return (
    <React.Fragment>
      <SelectSkillDialog value={value} onChange={onChange} />
      <ObjectField {...props} />
    </React.Fragment>
  );
};
```
