### ISSUE TITLE
Error: Cannot read property 'utterances' of undefined

### ISSUE THREAD

**Issue by beginnerUserChris** [microsoft/BotFramework-Composer#4211]
Hello,

I am new to Bot Framework Composer and I have been developing a chat bot. I am currently receiving the message: 
"Sorry, something went wrong with publishing. Try again or exit out of this task. 
Cannot read property 'utterances' of undefined"

I am not sure how this error happened or how to resolve it. Unfortunately, after hours of looking at each part of my project I still have been unable to figure out what the 'utterances' of 'undefined' are or where they are located. How do I determine what is causing the error? Is there a way to recover previous versions of the bot in bot framework composer, and roll mine back prior to the error?

Prior to the error I added in the 'Unknown intent' and 'Duplicate intents recognized' triggers. I have since deleted them and the error persists.

I have never posted here before so please feel free to direct me as necessary

![Capture](https://user-images.githubusercontent.com/70126775/93741565-058d5680-fc30-11ea-9bbf-2b28dfbfa5f7.PNG)

**Comment by boydc2014** [comment]
@beginnerUserChris from a first glance, the luis app setup looks to be expected, and this appears to be an internal null object reference issue. Can you zip you bot assets and attach here ?

**Comment by beginnerUserChris** [comment]
Hi @boydc2014 ! After removing the associated files in LUIS that allowed me to resolve the error I unfortunately did not have a copy of the bot which has the error. I attempted to recreate the error today however I was unsuccessful. If I am able to recreate it I will post it back in this issue and reopen it.

I apologise for the inconvenience!

**Comment by neganov** [comment]
I've hit the same issue with Bot Framework Composer 1.1.1. The error "TypeError: Cannot read property 'utterances' of undefined" is thrown on line 492 in the file:

%LocalAppData%\Programs\Bot Framework Composer\resources\app.asar.unpacked\build\plugins\azurePublish\node_modules\@microsoft\bf-lu\lib\parser\luis\luConverter.js

When I publish it apparently compares already published LUIS apps against my local apps, and in doing so hits an unexpected undefined value on line 492. I've only started getting this error after I have done some labeling and training directly in luis.ai portal. Once I deleted my LUIS apps from there, I was able to re-publish without an issue.

![Capture](https://user-images.githubusercontent.com/18127383/99839266-69e96b00-2b38-11eb-9857-7ee32c963192.PNG)

**Comment by dinobrago** [comment]
I also have this issue working in Composer 1.3. I have a working bot. When I deleted a trigger, I could no longer start the bot locally getting the error Luis build failed: Cannot read property 'utterances' of undefined. How do I track this down and resolve the issue? It clearly stems from deleting a trigger.

**Comment by cpolanish** [comment]
I just ran into this issue myself. I'm new to Bot Framework and LUIS and am just trying to get up to speed on things. In my scenario, I've figured out that what I did to cause this error was I went to LUIS.ai and trained the bot. After training I started getting this error in composer when trying to either publish or just start the bot locally, and don't know where to look to correct it. Like the others above, deleting the app out of LUIS.ai resolves the issue, but if I go in and train again it comes back.

**Comment by dinobrago** [comment]
For me, this is a bug associated with deleting existing triggers. I'm developing bots in Composer v1.3.1 and every time I delete a trigger, I get this error when I try to subsequently run the bot. I have to manually go to LUIS.AI and delete the entire LUIS application.

**Comment by victorlamana** [comment]
I'm having the same issue...started happening right after I trained a model on LUIS

**Comment by someonelikeTIM** [comment]
Same issue in v2.0

**Comment by deependra-khangarot** [comment]
Same issue in v2.1.1

**Comment by Kirill-Ovc** [comment]
I had the same issue when I trained a model on LUIS. I have solved it this way - I have exported the LU model in the LUIS portal  after training and publishing, and pasted it into Composer bot's LU model in Bot Responses tab.

**Comment by gerald560** [comment]
> 

this worked for me! thank you
