### ISSUE TITLE
bug: OAuth card on Teams not working

### ISSUE THREAD

**Issue by cdonke** [microsoft/BotFramework-Composer#4216]
## Describe the bug
Trying to authenticate on Teams... Added the OAuth SignIn Card, but nothing happens when clicked.
Authentication works on other channels.

## Version
![image](https://user-images.githubusercontent.com/4707327/93766206-71e66680-fbec-11ea-857c-adb5f00335b3.png)

## Browser
- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X ] Edge

## OS
- [ ] macOS
- [ X ] Windows
- [ ] Ubuntu

## To Reproduce

![image](https://user-images.githubusercontent.com/4707327/93766240-8460a000-fbec-11ea-9860-f5c5b11936d7.png)
![image](https://user-images.githubusercontent.com/4707327/93766265-8aef1780-fbec-11ea-941f-cadd97c94bb0.png)
![image](https://user-images.githubusercontent.com/4707327/93766292-94787f80-fbec-11ea-9c27-5a9f9798cf8c.png)

## Expected behavior
Somehow authenticating.. New window, passive, implict... I don't know.

## Screenshot
![image](https://user-images.githubusercontent.com/4707327/93766424-c4c01e00-fbec-11ea-8db6-70d762d8d979.png)

## Additional information
Tried changing ComposerBot class from AcitivtyHandler to TeamsActivityHandler, but no changes

**Comment by v-kydela** [comment]
@cdonke - Did you add token.botframework.com to your Teams app manifest's `validDomains` property as documented [here](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication#install-and-test-the-bot-in-teams) and [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication#adding-teams-authentication)?

**Comment by cdonke** [comment]
Yes...
With and without *.ngrok.io as well...

**Comment by cwhitten** [comment]
@cdonke we believe the following PR is related https://github.com/microsoft/botbuilder-dotnet/pull/4677

This will be in the next set of SDK nightly packages for you to use and verify.

**Comment by cdonke** [comment]
Thanks @cwhitten ...
I'll follow this PR to see when it's merged...

Question... I need to update the Composer, Runtime, BotBuilder lib, all of the above??

**Comment by cxbuilders** [comment]
Any progress on this? I just hit this blocking issue as well....

**Comment by GPHNKN** [comment]
Same here .... can you updates on this?

**Comment by cxbuilders** [comment]
ok, switched to the latest main version and there it is working.

**Comment by cdonke** [comment]
@GPHNKN sorry.. I haven't tested it in a long time.
@cxbuilders tks for the update.

Christopher replied on Sep ([here](https://github.com/microsoft/BotFramework-Composer/issues/4216#issuecomment-696287121)) saying that it was on another package... by now, it should be solved.

I'll test it again and close the issue if solved.

**Comment by rahul-8437008949** [comment]
![Screenshot (173)](https://user-images.githubusercontent.com/54345729/112515553-5c7d0f80-8dbc-11eb-902f-21cc05a1688e.png)

![Screenshot (175)](https://user-images.githubusercontent.com/54345729/112515560-5e46d300-8dbc-11eb-8eb3-81ae1f0e2333.png)

![WhatsApp Image 2021-03-25 at 10 45 15 PM (2)](https://user-images.githubusercontent.com/54345729/112515588-669f0e00-8dbc-11eb-9f02-964a23392de8.jpeg)


@cwhitten @v-kydela i am facing a similar issue.My Oauth card is rendering,it has a link attached with it but it doesnt open upon clicking. Can you please help me with this
