### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by nitroin** [microsoft/BotFramework-Composer#4218]
# Describe the bug

Unable to use bots built with LUIS on any channel (Facebook, Twilio or Telegram - maybe others too).

## Version

v1.1.1-nightly.167623.9ba5e84

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

Appendix:
a. Create a Languange Understanding service from Azure, West Europe region.

1. Go to 'New'
2. Click on 'Create from template'
3. Select 'Todo with LUIS'
4. Click 'Next'
5. Click 'Ok'
6. Click 'Publish'
7. Click 'Add new profile'
8. Provide a profile name and select 'Publish bot to Azure Web App (Preview)'
9. Paste the needed configuration manifest
10. Click 'Publish to selected profile'
11. Wait to the publish to finish
12. Go to Azure portal
13. Navigate to 'Bot Channels Registration' for the bot
14. Click 'Channel'
15. Provide a valid channel configuration (Telegram the fastest)
16. Try to the bot on the configured channel
17. Bot answer with 'Object reference not set to an instance of an object.'

## Expected behavior

The bot answer questions in a similar way as in the Bot Emulator.

## Additional context

Similar issues #4118 #4073.

**Comment by cwhitten** [comment]
Hi @nitroin. You are correct that this is is a duplicate issue. I'm going to close this and ask that you follow https://github.com/microsoft/BotFramework-Composer/issues/4118 for updates. Thank you.
