### ISSUE TITLE
New UI on Skills page for enabling / disabling skill and managing allowed callers list

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#4222]
## Is your feature request related to a problem? Please describe.

We need to provide users of Composer the ability to manage the following via the UI.

- The new IsSkill setting introduced into the SDK, to indicate if a bot should allow itself to be consumed as a skill.
- The AllowedCallers list

The runtime changes related to this are currently in PR https://github.com/microsoft/BotFramework-Composer/pull/4086

## Describe the solution you'd like

The agreement amongst the team who met to discuss this was that the existing skills page within Composer would be altered to include both the IsSkill toggle and UI to allow a user to manage the Allowed Callers list.  

By default the IsSkill toggle will be set to false.  A user should be able to enable this toggle on the skills page, or have this turned on automatically if the user creates a skill manifest.

The Allowed Callers UI should allow a user to indicate all callers should be allowed (this should be the default) or that a specified list of app Ids should be allowed.

**Comment by cwhitten** [comment]
A couple quick questions:

1. are we introducing two new fields in appsettings? `isSkill` and `AllowedCallers`?
2. is there an accompanying runtime issue to consume these new fields?

cc @carlosscastro

**Comment by garypretty** [comment]
@cwhitten Allowed Callers is existing configuration within appsettings.json for C#.  It is an array of strings, either * for all or an array of app IDs for the allowed calling bots. You can see more about this setting at https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-skill?view=azure-bot-service-4.0&tabs=cs#application-configuration.

@carlosscastro can provide details of the new IsSkill setting - this is new all up in SDK this cycle and just completed.

**Comment by tdurnford** [comment]
Adding @sangwoohaan for design input

**Comment by ltwlf** [comment]
Here is my draft for the non UI part of the skill settings #4086 
cc @carlosscastro

**Comment by ltwlf** [comment]
@tdurnford This feature doesn't seem to handle the "enforced end of skill dialog" #4157 but for sure it is related to skills. You want to discuss this here? Or should I reopen the issue?

**Comment by tdurnford** [comment]
@ltwlf I’ll go ahead and reopen the other issue. Thanks for pointing that out.

**Comment by cwhitten** [comment]
@sangwoohaan do we have completed designs for this?

**Comment by cwhitten** [comment]
Removing from the milestone. Missing UX

**Comment by beyackle** [comment]
This looks like something I can handle writing, but not until we have a solid and nailed-down UI for it.

**Comment by tdurnford** [comment]
I merged a PR a few weeks that added the allowed callers list and the is skill toggle. However, it looks like it got removed in the latest Settings page changes. Note, we no longer need the is skill toggle since the adaptive runtime no longer uses that setting.

https://github.com/microsoft/BotFramework-Composer/pull/6522
https://github.com/microsoft/BotFramework-Composer/pull/6620
https://github.com/microsoft/BotFramework-Composer/pull/6622
