### ISSUE TITLE
Upgrade to recoil to version 0.0.13

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#4223]
This will help improve typing and fix several runtime warnings.
It may affect some of the dispatch calls and require a little refactoring.

@boydc2014 and @srinaath - @hatpick has been looking into this. @cwhitten mentioned that upgrades should generally be considered  platform work so to include you, but that recoil is the area where platform and authoring meet :-)  We could set up a feature branch to work through the upgrade together.

**Comment by srinaath** [comment]
@GeoffCoxMSFT Do we know the date for the 0.0.13 release? Recoil released 0.0.12 5 days ago.

**Comment by hatpick** [comment]
@srinaath it's already released https://www.npmjs.com/package/recoil
Their github releases page seems outdated

**Comment by boydc2014** [comment]
Thanks @GeoffCoxMSFT, i think we can an assessment and assignment in tomorrow's sync up

**Comment by boydc2014** [comment]
I put Leilei and Srinaath for now.
