### ISSUE TITLE
New LUIS apps do not have the prediction resource assigned

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#4226]
## Describe the bug
I have created all my Azure resources and have separate a LUIS Authoring and Prediction resource, with the keys/endpoints configured in the bot settings. When I add a new dialog with a LUIS recognizer, composer doesn't configure the prediction resource on the new LUIS app and I get a 403 until I go into the portal and manually assign.

 ## Version

Release: 1.0.2
## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
I'd expect once I configure the LUIS settings in bot settings, that those would be applied to any new apps that are created without the need for manual intervention.

**Comment by luhan2017** [comment]
@lauren-mills , thanks for reporting, this is a known issue #3639 , and we will fix this in R11.

**Comment by lauren-mills** [comment]
Added the bugbash label since this is still an open issue

**Comment by peterbozso** [comment]
I've just tried this with 1.3.1. Seems to be working fine, the prediction resource is being assigned after publishing a LUIS-integrated bot from the Composer.

**Comment by lauren-mills** [comment]
Related #6312
