### ISSUE TITLE
Composer doesn't expose all of the adaptive and dialog events thrown by the SDK

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#4227]
## Describe the bug
The Dialog Events trigger in composer doesn't show all of the available default events thrown by the SDK. Missing ones include "intentRecognized", "activityReceived", and "endOfActions". These are useful for certain initialization logic and end of dialog logic. I can use them by providing the name in the custom event action, but it would be more useful to see them in the dropdown.

**Comment by benbrown** [comment]
ActivityReceived should be in the "Activities" sub-dropdown.

Intent Recognized is a top level selection.

We will be adding endOfActions as part of form dialogs.

Are there any other events that you've found that are missing?

![Screen Shot 2020-09-22 at 11 46 14 AM](https://user-images.githubusercontent.com/729873/93912380-4f764b00-fcc9-11ea-96c9-8633d3814985.png)
![Screen Shot 2020-09-22 at 11 46 05 AM](https://user-images.githubusercontent.com/729873/93912386-543aff00-fcc9-11ea-9320-3fff3282e6c7.png)

**Comment by yeze322** [comment]
I have a WIP PR which aims at solving this problem https://github.com/microsoft/BotFramework-Composer/pull/4079.
Also related to https://github.com/microsoft/BotFramework-Composer/pull/4014.

**Comment by benbrown** [comment]
@lauren-mills @yeze322 is this ticket still relevant?

**Comment by lauren-mills** [comment]
There is still a bit of confusion in the UI here for me I guess, because when I create Triggers I see the list separated into subsections with different names but when I emit an event I see the actual event name. I personally know how that map to one another but our developers may not: 

![image](https://user-images.githubusercontent.com/27976702/119546133-6bdef180-bd48-11eb-8c83-e5e3629da6f0.png)

Also, for something like intent recognized, it is possible to want an action to take place every time an intent is recognized (entity extraction for example) but not tie the action to a specific intent as the Intent Recognized trigger UI does. 

So by that logic, I'll remove the bug label, but still consider it a feature request to refine this UI to be more consistent.

**Comment by benbrown** [comment]
That is great feedback, @lauren-mills. These two related menus should definitely be in harmony. @mewa1024 can you consider this?

I think what you are talking about with the intent recognized is different though -- how would you achieve this? I think this may be a separate feature request.

**Comment by lauren-mills** [comment]
We don't do it today, but I have considered before having a generic event trigger for intentRecognized that catches the event, then extracts entities, then fires then does the intent trigger. 

I think it is possible today actually depending on how you configure your trigger priorities, but it was more of an example than anything 😊

I think if the dialog event/custom event triggers used the same language and options provided in the emit event action, that would help reduce the slightly disjointed feel here today.

**Comment by mewa1024** [comment]
this is super useful feedback. I'm adding @vivekkshankar since he has been exploring trigger UI.
