### ISSUE TITLE
Migration to '.lu.qna' will break ejected bot runtime instances without QnARecognizer

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#4229]
## Describe the bug

In QnA Recognizer PR, we brought [a migration mechanism](https://github.com/microsoft/BotFramework-Composer/blob/4769cd30f63c3e8a81dafd53e1fe2b1416064251/Composer/packages/adaptive-form/src/components/fields/RecognizerField/useMigrationEffect.ts) which renames `*.lu` files to `*.lu.qna` automatically.

For existing bots, there are 2 cases:
1. Old bots **without** an ejected runtime - No problem since they use Composer's runtime template which is always updated.
2. Old bots **with** ejected runtime - Migration to qna will break them since QnA hadn't been supported in their old version's ejected runtime.

As a result, though there is no bug reports from users, the auto migration to `*.lu.qna` file do break some existing bot projects with ejected runtime.

**To fix that**: User needs to re-eject the runtime

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Switch to an old version of Composer without QnA
2. Create a bot, eject runtime
3. Load the bot with current Composer version with QnA
4. The bot will be broken due to all .lu files are renamed to .lu.qna

**Comment by benbrown** [comment]
@alanlong9278 @liweitian can you take a look into this issue?

**Comment by mewa1024** [comment]
Do we know when this will be fixed?
Switching from `*.lu` to `*.lu.qna` breaks dialogs created through form dialogs (aka [Dialog Generation](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/generation)). I used to run a form dialog using [runBot](https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/generation/runbot) and then open it in Composer to view the flow diagram, but now opening it in Composer breaks the bot.

**Comment by yeze322** [comment]
@mewa1024 does it mean that form dialog relies on *.lu file rather *.lu.qna file?
If so, the migration logic should be updated, when it's form dialog don't rename lu files.

**Comment by mewa1024** [comment]
Can we show a message to the user that we've detected they are using an older recognizer and give them options to continue with migration, cancel, or save as a copy? That would cover multiple cases.
