### ISSUE TITLE
Centralize side effect management 

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#4232]
Leave the side effect (lu/lg/qna) management into the caller side (form\visual) is an architecture is fragile and very error-prone architecture. In the past, we've fixed many issues, regressions on those operations. See blow of the list.

Letting shell take control the side effect management will lead us to a more stable, testable architecture which have a higher level guarantee of correctness of the application. 

This would include a generic change detection mechanism in shell and a pub-sub mechanism to call certain actions under certain changes. This would also make the application more extensible for further customization. 

Note: this ticket is a pure refactoring, only cover the centralization part, without creating any new v property.

**Comment by zhixzhan** [comment]
FYI, some previous issue on areas that generate side effect.

#### undo/redo

- undo / redo support for nodes with lu and lg https://github.com/microsoft/BotFramework-Composer/issues/2212

#### copy/paste

- Cross-file copy of LU / LG resources https://github.com/microsoft/BotFramework-Composer/issues/2207
- Unable to copy actions across dialog files https://github.com/microsoft/BotFramework-Composer/issues/2199

#### concurrency
- Shell - debouncedUpdateLg cannot handle paralleled lg update requests https://github.com/microsoft/BotFramework-Composer/issues/2247

#### other entrance

- Manually added json node doesn't have designer id and cannot edit lg text https://github.com/microsoft/BotFramework-Composer/issues/1776
- Delete trigger should also delete LU intents and LG templates https://github.com/microsoft/BotFramework-Composer/issues/2209
- Auto-generated Bot Response templates are not removed when entire dialog (trigger) is deleted https://github.com/microsoft/BotFramework-Composer/issues/2150
- Multi nodes deletion should also delete the lg template https://github.com/microsoft/BotFramework-Composer/issues/2210

**Comment by boydc2014** [comment]
Close this for now, since it's out of date.
