### ISSUE TITLE
Have both trigger for Greeting & BeginDialog in Main Dialog

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4234]
I need to have two triggers in my main dialog;
- ConversationUpdate Activity
- BeginDialog

The idea is that when the conversation is initiated the ConversationUpdate is triggered and otherwise the BeginDialog is triggered.

However the BeginDialog always takes precedence, no matter what. Changing the priority does not make any difference, except when I set BeginDialog to -1, but then it never runs anymore.

Ideally I want them to run both, first ConversationUpdate, then the BeginDialog, which would make sense, otherwise just ConversationUpdate on chat start and for any subsequent dialog starts the BeginDialog one

How can I set this up?

Bastiaan

**Comment by benbrown** [comment]
The normal behavior of adaptive dialogs is that only one trigger will fire.  BeginDialog always happens first and takes precedent over everything else. 

You could fire a custom event at the end of your conversationUpdate handler to chain it to another trigger.

What circumstance would you be in the root dialog but _not_ responding to a conversationUpdate event?

**Comment by cxbuilders** [comment]
@benbrown I have my mainMenu with a repeat dialog in the root dialog. Basically from there other dialogs are called and the user always returns back to the mainMenu eventually. There all main intenets are living as well and I can handle continuos security checks through the main menu.

I wanted to trigger the conversationUpdate to say a greeting and then call the mainMenu using a custom Event. I am actually not sure if then there would be ever a situation where beginDialog would be triggered from the root dialog, since either the user is new -> conversationUpdate or the user is in an infinite loop from the mainMenu.

Given the fact that I had nothing but trouble with the conversationUpdate event, I now changed it around and only use beginDialog and check if the user already has some properties set, so I can greet him based on that.

That seems to be working fine and I don't have different behavior with Web and other channels for the conversationUpdate event.

I know I am gibbering here, the thing is that I look for the best setup and would appreciate some confirmation / advice here on the following;
- Does this seem like a good setup?
    - Main Menu in continuous loop with a custom Event trigger
    - One beginDialog with check on existing user to say hi and start the main menu

**Comment by lzc850612** [comment]
@benbrown  do you have any update for this issue? Thanks.

**Comment by benbrown** [comment]
This seems like a reasonable approach @cxbuilders, particularly given the channel differences.
