### ISSUE TITLE
Clicking 'Open skills page for configuration details' disables menu options

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotFramework-Composer#4239]
## Describe the bug
![image](https://user-images.githubusercontent.com/11055362/93946259-a3932680-fced-11ea-9ee9-ddfe663a5a99.png)

This loads the skill configuration page, but i cannot figure out how to get out of it without restarting Composer. Menu options are disabled:
![image](https://user-images.githubusercontent.com/11055362/93946312-c7566c80-fced-11ea-8fb3-43fce337bd80.png)

## Version
nightly

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Additional context

Navigating to skills settings directly, works fine.

**Comment by tdurnford** [comment]
@EricDahlvang Thanks for reporting! As part of the Multibot expansion work we are doing in R11, we are planning to remove the skills page. Subsequently that link to the skills page was recently removed in #4207.

https://github.com/microsoft/BotFramework-Composer/pull/4207/files#diff-709a57c1f9ba4c513dd93b40c9620ecaL142.
