### ISSUE TITLE
Improve electron start up perf

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#4241]
Our electron distribution's start up perf isn't good, especially in Windows and we've heard customer complaining about it. Use this ticket to trach the investigation on it.

**Comment by boydc2014** [comment]
Put @liweitian on this to investigate. @liweitian please reach out to @tonyanziano if you need anything.

**Comment by v-kydela** [comment]
In addition to any performance improvements, would the team consider giving Composer a splash screen like Emulator has?
