### ISSUE TITLE
Unable to execute the bot on Azure functions

### ISSUE THREAD

**Issue by saikumaru** [microsoft/BotFramework-Composer#4243]
## Describe the bug
Upon publishing the bot to Azure function, the Azure function goes down and doesnt respond to any request

I have followed the steps for publishing bot to Azure Function with resources created through the command line script

The Function App shows up the below error
![image](https://user-images.githubusercontent.com/44021002/94023738-30b0ab00-fdd4-11ea-9d73-1818910fa154.png)

And the status of the runtime shows as error
![image](https://user-images.githubusercontent.com/44021002/94023816-48882f00-fdd4-11ea-99e5-ac82a7caf89c.png)

And the diagnosis says
![image](https://user-images.githubusercontent.com/44021002/94023986-7bcabe00-fdd4-11ea-9e47-2963951bc164.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3462131-c17c-c9e1-106c-390e0bdb523d
* Version Independent ID: bd203f82-3725-6df6-1aef-9ffad92fa7fa
* Content: [Publish a bot to Azure - Bot Composer](https://docs.microsoft.com/en-us/composer/how-to-publish-bot)
* Content Source: [composer-docs/how-to-publish-bot.md](https://github.com/MicrosoftDocs/composer-docs-pr/blob/live/composer-docs/how-to-publish-bot.md)
* Service: **bot-composer**
* GitHub Login: @zxyanliu
* Microsoft Alias: **kamrani**

## Version
1.1.1

## Browser
Chrome

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Follow steps for Azure function as provided here
https://docs.microsoft.com/en-us/composer/how-to-publish-bot

## Expected behavior
The function should not error and the bot should reply over the bot channel registration test panel

## Screenshots
Added above at relevant place

## Additional context
The function apps were created through the commandline script as provided in the documentation

**Comment by tdurnford** [comment]
@carlosscastro Can you take a look at this?

**Comment by saikumaru** [comment]
Any update please?

**Comment by ninggao** [comment]
@carlosscastro Any update on this?

**Comment by jwiley84** [comment]
@saikumaru 

Apologies for the delay in answering this. Azure Functions Bots are no longer supported. The architecture for putting bots on functions was for v3, not v4.

**Comment by saikumaru** [comment]
Pardon me but the documents says Azure Function is in **Preview** rather than **Depreciated**.

Are we referring to the same piece, if so would you please mind correcting the document so that we aren't misled?
https://docs.microsoft.com/en-us/composer/how-to-publish-bot

`Enter a name for your publish file and select where you would like to publish your bot: Publish bot to Azure Web App (Preview), or Publish bot to Azure Functions (Preview).`

**Comment by jwiley84** [comment]
My apologies. I didn't realize Composer was adding that functionality. I'll go ahead and reopen this issue, and reach out to a member of the composer team.

**Comment by zxyanliu** [comment]
@saikumaru I also tracked the issue here if it has to do with the docs. 
https://github.com/MicrosoftDocs/composer-docs/issues/11

**Comment by saikumaru** [comment]
team, would you have an update here please?
If we need to offer composer to our clients with Azure function as a PAYG option, this is just holding us down.

**Comment by jwiley84** [comment]
Assigning to @v-kydela as I'm unable to run composer at the moment.

**Comment by v-kydela** [comment]
@saikumaru - Have you tried this with an out-of-the-box echo bot?

**Comment by saikumaru** [comment]
Yes, that is exactly what I have tried to start off with.

**Comment by v-kydela** [comment]
@saikumaru - I get the same error from the function app: `System.IO.FileSystem.Watcher: Error reading the D:\home\site\wwwroot\. directory.`

I also notice that it says the function host is not running:

![image](https://user-images.githubusercontent.com/41968495/95625894-20343d80-0a2e-11eb-9661-e010d2a7689b.png)

It appears that the Composer script does not deploy the function correctly

**Comment by saikumaru** [comment]
That is correct and glad that you can replicate. Also, I have no way to debug and see what the issue could be even if I try to download that code from functions and test.

Can you also advise when this can be resolved?

**Comment by saikumaru** [comment]
Any update team?

**Comment by carlosscastro** [comment]
Hello, sorry I missed this thread. I'll follow the steps and troubleshoot tonight.

**Comment by carlosscastro** [comment]
Was able to reproduce the bug. I'll work on a fix, most likely will go out on the next release of composer in early Nov. However once the change hits main, you could use composer from nightly build or from source. If the change only affects the runtime, then you could just update your runtime without updating composer. I won't be sure of the exact scope of the fix until I finish it. I'll update with details on how to get access when that happens.

**Comment by joeliir** [comment]
This is an issue we are having as well with a bot we were hoping to put into production soon.

**Comment by carlosscastro** [comment]
If you check PR #4570 , it captures the fix to make functions work again and some improvements to have it work in more environemnts. Options to get this fix are 1) wait for the next composer release or 2) eject your runtime and apply that fix to unblock right away.
