### ISSUE TITLE
Popout for small editors

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4245]
![image](https://user-images.githubusercontent.com/49873947/94028819-7f524b00-fdbc-11ea-8265-6f8640f83573.png)

When developing bots with lots of integrations, menu's etc, one gets fed up with the small editor quite fast. The following ones that I typically have much more code than editor space;
- Send Response
- Set Property / properties (whole code blocks in one small input!)
- Body of Http Requests

Having the possibility to popout an editor that can be scaled as well, would be a huge workflow improvement. At a later stage I can imagine some more code editing tools in this popout coming in handy, but for now just having some overview would be a huge improvement

**Comment by dmvtech** [comment]
This isn't directly addressing the change you are suggesting, but just FYI; you can get a much better editor/field from the _Bot Responses_ portion of Composer. The field is resizable to accommodate more data, etc.

![image](https://user-images.githubusercontent.com/43397658/94044168-a2f89f80-fd82-11ea-9ed1-c5dffa32c346.png)

**Comment by cxbuilders** [comment]
@dmvtech Yeah but switching between the dialog you're editing and the lg files all the time is probably even worse...

**Comment by cwhitten** [comment]
@sangwoohaan @vivekkshankar this is pertinent to the recent discussions around the splitter control Geoff was demonstrating.

**Comment by sangwoohaan** [comment]
Working on this as part of the LG revisit

**Comment by sangwoohaan** [comment]
Coming in for R13
