### ISSUE TITLE
Dialogs with name starting with numbers cause "extraneous input ‘01’ expecting IDENTIFIER"

### ISSUE THREAD

**Issue by leopuleo** [microsoft/BotFramework-Composer#4246]
## Describe the bug
Using LUIS to extract data from user responses cause "extraneous input ‘01’ expecting IDENTIFIER" in case of Dialog name starting with a number, eg: `01-my-dialog`

## Version

1.1.1-nightly.168593.d361ddb
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot selecting template "Todo with LUIS"
2. Create a new dialog and name it `01-new-dialog`
3. Copy and paste `userprofile` -> `BeginDialog` content into `01-new-dialog` -> `BeginDialog`
4. Add a new trigger to the main dialog: 
  -- name = 01-new-dialog, 
  -- type = Intent recognized
5. Add `Begin a new dialog` action and link to `01-new-dialog`dialog
6. Add any trigger phrase eg: `start dialog`
7. Start bot and open emulator

In the emulator
1. Type `01-new-dialog` trigger phrase
2. Type `my name is anyName`
3. Error: "extraneous input ‘01’ expecting IDENTIFIER"

## Screenshots

![Screenshot 2020-09-23 at 19 03 58](https://user-images.githubusercontent.com/2866531/94045346-9fd7d080-fdcf-11ea-9a7b-43832671cc15.png)

![Screenshot 2020-09-23 at 19 04 07](https://user-images.githubusercontent.com/2866531/94045382-acf4bf80-fdcf-11ea-80a2-121a03c58313.png)

![Screenshot 2020-09-23 at 18 58 52](https://user-images.githubusercontent.com/2866531/94045418-b847eb00-fdcf-11ea-9859-3b5e146aae22.png)

**Comment by tdurnford** [comment]
@luhan2017 Can we confirm that this isn't a bug in adaptive? Once we establish that, we can route it to the right person.

**Comment by luhan2017** [comment]
This should be a AdaptiveExpression issue. I've debuged this in the SDK side, it turns out that an error thrown when AdaptiveExpression evaluate "settings.01_new_en_us_lu" which is the applicationId auto generated by lubuild.

I will sync up with @Danieladu and @boydc2014  for more details. 
```
{
    "$kind": "Microsoft.LuisRecognizer",
    "id": "LUIS_01-new",
    "applicationId": "=settings.luis.01_new_en_us_lu",
    "endpoint": "=settings.luis.endpoint",
    "endpointKey": "=settings.luis.endpointKey"
}
```

**Comment by Danieladu** [comment]
The variable name in Expression can not start with number. Maybe there should add some validations on the dialog name in Composer?

**Comment by lzc850612** [comment]
@leopuleo could you see if the workaround in the previous comment would help with your issue? We'll continue the fix for the issue on our side. Thanks.

**Comment by leopuleo** [comment]
Hi @lzc850612, 
Yes, in case of variable name not starting with number everything works fine.

**Comment by luhan2017** [comment]
@boydc2014 , can you take a look at this issue? we should add one validation rule for the dialog name.

**Comment by boydc2014** [comment]
Sure, @luhan2017 i will take this.
