### ISSUE TITLE
Auto Generate Skill Intent Triggers when adding a skill

### ISSUE THREAD

**Issue by lzc850612** [microsoft/BotFramework-Composer#4249]
When creating a skill, we need to auto create an intent trigger based on the skill so that the Orchestrator can route activities to that skill based on user intent

**Comment by sgellock** [comment]
moving this off of Ted's plate.  Can you own or find the appropriate owner

**Comment by boydc2014** [comment]
@taicchoumsft can you help clarify the intention here

**Comment by cwhitten** [comment]
@taicchoumsft @boydc2014 @tsuwandy I'd like to discuss this behavior being housed inside the bf-cli.

In keeping with our principles of Composer providing parity behaviors with the cli tools, we should be able to add a skill's lu data into the orchestrator model and wire up the dialog logic to configure the intent triggers. Form Dialogs does something like this already, and it sits inside the `bf generate` api.

By not doing this in the CLI, the user experience using the bf cli process will be incomplete. A core value proposition of dispatch is that the intent routing to the skill is done automatically.

**Comment by sgellock** [comment]
+1 on Chris' feedback regarding Composer and Bf-CLI feature parity

**Comment by scheyal** [comment]
@vivekkshankar - need also design.

**Comment by luhan2017** [comment]
closed by this PR #6640
