### ISSUE TITLE
Folder paths containing "%20" break open project window

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4250]
## Describe the bug

Unfortunately I didn't catch a screenshot of this but we recently moved the Meeting Assistant from Github to Azure DevOps. The new folder name for the project is "Meeting%20Assistant".  The moment I stepped into the folder within the project open dialog the dialog went blank and said something like "Error connecting to file system".  I was completely stuck until I renamed my projects folder to "Meeting-Assistant".

## Version

1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by liweitian** [comment]
I think this is the same as #4236. A fixing pr is opened.
