### ISSUE TITLE
Error when clicking open for a project thats moved

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4252]
## Describe the bug

We moved our repo so all of projects now have new folder paths.  Anytime I click on one of the old projects in the history list I get the error below:

![image](https://user-images.githubusercontent.com/698939/94067640-04306b00-fda3-11ea-8b9a-21257f68a440.png)

## Version

1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by Stevenic** [comment]
On the plus side it removes the bad link from the list so it's a one time issue for each project. Still I think we could show a better error message like "Project not found"

**Comment by cwhitten** [comment]
This has been addressed in https://github.com/microsoft/BotFramework-Composer/pull/4260
