### ISSUE TITLE
Glossary terms to add: Publish profile, Publish target, Publishing, Environment, Resources

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#4253]
We need to add some terms & definitions to the Glossary.
Please check out the PVA glossary also: https://styleguides.azurewebsites.net/StyleGuide/Read?id=2696&topicid=27964

- Publish profile, 

- Publish target - is this the same as profile? If so we should use that instead. PVA uses this https://styleguides.azurewebsites.net/Search/Index
- 
- Publishing

- Environment

- Resources

**Comment by zxyanliu** [comment]
Checked references from [Microsoft Cloud Style Guide](https://styleguides.azurewebsites.net/StyleGuide/Search) and added the following: 

* Publish 
  To deploy a software package as a cloud service to the staging or production environment.

* Publish profile 
  A downloadable package that provides the secure connectivity required to publish (upload and deploy) websites and cloud services from a local development environment. 

* Publish target
  The deployment environment to which a service is to be deployed to a cloud service.
  
* Environment 
  A space to store, manage, and share an organization's business data, apps, and flows.

* Resources 
  A resource is a specific instance of a service: for example, a flow, a virtual machine, a web app, or a SQL database.

**Comment by zxyanliu** [comment]
@mareekuh 
Do we have a specific project for these terms? Authoring? Runtime? Platform? 
I am going to add them in the [spreadsheet](https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B73AE9B1E-6E4F-4393-BE3B-F82111ACBE79%7D&file=R11%20Terminology.xlsx&action=default&mobileredirect=true) first and then to the docs glossary when the projects are delivered.

**Comment by zxyanliu** [comment]
Close this issue as the terms were added.
