### ISSUE TITLE
Microsoft Team Bot as a contact not as an App

### ISSUE THREAD

**Issue by jintu123** [microsoft/BotFramework-Composer#4255]
I am Looking for a solution of how to make a bot available to my organization, without publishing the bot as an App using App studio. But to Make it available to everyone in the organization as a Contact In Microsoft Teams.

To my understanding we need to install the Bot App to get it as a contact. But in organization level, how can that be achieved without installing the bot app for everyone, but make the bot available as a contact to everyone in the organization, in Microsoft Teams.

Please let me know if you want anymore inputs from me.

**Comment by cwhitten** [comment]
@clearab assigned to you for initial routing.

**Comment by clearab** [comment]
Hi - thank you for your feedback. Currently, to install your app globally for an organization we recommend you use your organization's app setup policies. You can find more information about that here - https://docs.microsoft.com/en-us/MicrosoftTeams/teams-app-setup-policies.

There are currently no plans to make bots in Teams available outside of Teams apps. If that is a feature you'd like to see in the future please create and vote for it on UserVoice - https://microsoftteams.uservoice.com/
