### ISSUE TITLE
Bot Composer beautification

### ISSUE THREAD

**Issue by jintu123** [microsoft/BotFramework-Composer#4256]
I have a requirement to change the font, make it bold, hyperlink a text, change font size.
How can I achieve it in the bot composer?
Can it be achieved without using adaptive cards?
I also want to change the Appearance of the bot like, soft edges, change name of the Chat box and color of the Chat Box.
How can I achieve the above things? 

Any help is appreciated!

Currently My bot looks like this:
![image](https://user-images.githubusercontent.com/15074288/94102741-757a2780-fe50-11ea-83d6-d254c407f62d.png)

Trying to achieve something like this:
![image](https://user-images.githubusercontent.com/15074288/94102858-bffba400-fe50-11ea-968b-f38f4fa581d0.png)

**Comment by cwhitten** [comment]
Hi @jintu123, what you are looking is the ways to customize the Bot Framework Web Chat control. The documentation on how to do this is over here: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/02.branding-styling-and-customization

Please take a look at these resources to achieve your use case. Closing.

**Comment by jintu123** [comment]
Where is the index.htm is located as per the samples shared by you?
Where can I edit them can You help me with a little more insight?
