### ISSUE TITLE
Orphaned Language Generation Code

### ISSUE THREAD

**Issue by marktab** [microsoft/BotFramework-Composer#4262]
## Describe the bug

LG code is orphaned when a "send response" widget is deleted.  That process may result in having (for example) errors such as unbalanced multi-line quotations.

## Version

Version 1.1.1

## Browser

Chrome 80.0.3987.165

## OS

Windows

## To Reproduce

1. create an empty bot
2. create a "send response" with something like - ``` (don't close the multi-line quote)
3. delete the widget
4. note that the lg code persists, even though an uncompleted multi-line should throw an error

## Expected behavior

Deleting the "send response" widget should delete the code

## Workaround

Use edit mode in the LG script to remove orphaned code

**Comment by a-b-r-o-w-n** [comment]
@boydc2014 can someone on your team look into this?

**Comment by boydc2014** [comment]
Sure, assigning @zhixzhan  on this.

**Comment by Danieladu** [comment]
Hi @marktab. Sorry for the blocking. This is indeed a LG bug. I have a PR to fix it in dotnet library and would have a fix in js library soon.  Before the update is merged into main and Composer, I suggest that you can add a newline after "```" to skip this issue as the workaround. Thanks.

**Comment by Danieladu** [comment]
This issue has been fixed on SDK side. It supposed to work when update LG version in Composer to the latest.

**Comment by marktab** [comment]
Thanks @Danieladu

**Comment by Danieladu** [comment]
Close it for it has been fixed in the latest sdk
