### ISSUE TITLE
In the luis hoist view, Keep getting error: Can't read property "start" of undefined 

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#4266]
## Describe the bug

Electron 1.1.1

When I edit the luis hoist view, 

Input this: 
- my name is {@userName=luhan}
@ prebuilt personName hasRoles userName

I keep getting this error, and it can't be fixed whatever I type. 
![image](https://user-images.githubusercontent.com/32191031/94213169-c4839380-ff08-11ea-84fb-4a756f98a670.png)

Then my bot is totally broken. 

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by zhixzhan** [comment]
Tracked & fixed in CLI via https://github.com/microsoft/botframework-cli/issues/989
LU package update in composer  via #4610
