### ISSUE TITLE
Unable to add Bot custom action

### ISSUE THREAD

**Issue by jintu123** [microsoft/BotFramework-Composer#4268]
I am trying to add Bot composer custom action on a echo bot template.
I am using the Guide as per: https://docs.microsoft.com/en-us/composer/how-to-add-custom-action
##ERROR
![image](https://user-images.githubusercontent.com/15074288/94235822-cb6ece00-ff29-11ea-8a2d-184cca9ab38a.png)

## Version
![image](https://user-images.githubusercontent.com/15074288/94235767-b003c300-ff29-11ea-8f12-860501f2b03c.png)
![image](https://user-images.githubusercontent.com/15074288/94235884-e8a39c80-ff29-11ea-9c6f-e0ab09a9f11b.png)

## To Reproduce

1. Go to 'https://docs.microsoft.com/en-us/composer/how-to-add-custom-action'
2. Follow the guide to eject the runtime
3. after ejecting also it is still working
4. No changes in the Multiply dialog and schema.
5. After changing the Customize your exported runtime and Update the schema file, its not working any more

## Expected behavior
I was expecting a Custom action will be added in the drop down list.

**Comment by luhan2017** [comment]
@jintu123 , could you try to update your cli to the latest version, there is a known issue for the dialog merge tool, and we had a fix in the August.

**Comment by jintu123** [comment]
Its latest only! I installed it yesterday

**Comment by luhan2017** [comment]
But it is not the latest, it is the 20200730 version. check this link https://www.npmjs.com/package/@microsoft/botframework-cli
try to install any version after 4.10.1.

**Comment by jintu123** [comment]
I installed the latest version as you mentioned but still I am facing the same Issue.
![image](https://user-images.githubusercontent.com/15074288/94250647-1f37e200-ff3f-11ea-905a-604e2c3af126.png)

**Comment by cwhitten** [comment]
@luhan2017 it has been brought to my attention that updating Composer's runtime template to the latest runtime packages to 4.10.3 as well. Can you confirm?

**Comment by luhan2017** [comment]
@cwhitten, the current runtime version is 4.10.2, do you know when the sdk team will release the 4.10.4？There are several composer issues depending on this. for example #4218 #4030 #4118 , we can update to 4.10.4 directly after it is ready. 

![image](https://user-images.githubusercontent.com/32191031/94361021-f866e080-00e3-11eb-9b89-ff5f1f0379fc.png)

**Comment by luhan2017** [comment]
@jintu123 , I didn't reproduce this on my side. could you uninstall the bf-dialog package and try that again?
bf plugins:uninstall @microsoft/bf-dialog

**Comment by jintu123** [comment]
@luhan2017 After uninstalling also, I am getting the same error. But now if I ignore the error I am able to work with the custom action. And its working in the Emulator also.

**Comment by lzc850612** [comment]
@luhan2017 do you have any update for this issue? Thanks.

**Comment by luhan2017** [comment]
@jintu123 , did you still meet this issue? Could you also share me the runtime package version?
Go to your bot/runtime/azurewebapp folder, open Microsoft.BotFramework.Composer.WebApp.csproj and share the content in this thread. Thanks

**Comment by luhan2017** [comment]
@jintu123 , any update from your side? do you still see this error?

**Comment by luhan2017** [comment]
@jintu123 , we just found out this is a doc issue, please follow this comment to fix this https://github.com/microsoft/BotFramework-Composer/issues/4715#issuecomment-725820854
