### ISSUE TITLE
Call CodeAction from declarative code

### ISSUE THREAD

**Issue by guru98** [microsoft/BotFramework-Composer#4275]
I understand that is possible use declarative dialogs and code base dialog in the same bot, there are also some example but in the composer you can't add call to CodeAction. This should be possible at least for this scenarius as i think that could be interesting design bot using composer and than inject in the bot and have the possibility to call our own code

**Comment by cwhitten** [comment]
@guru98 Composer allows you the do this by creating Custom Actions. Please see this doc: https://docs.microsoft.com/en-us/composer/how-to-add-custom-action

**Comment by guru98** [comment]
I'm looking for support for CodeAction not CustomActions. CustomActions require an effort to insert and let me say are intended for actions you want to reuse in many bots. CodeActions allow to inject a sort of functions in your code that are different conditional set variables and so on. I could call external code using Http like azure functions but in many cases there are functions you want to call inse the bot code

**Comment by guru98** [comment]
Hi again, could someone comment on this? It's clear that developing code we need to call functions to to specific actions and computations. CustomActions is a good starting point but, in my mind, is intended for generic functions that can be reused in different bots and solutions. We can call rest, http, external functions but not always is a good solution. CodeActions are part of Adaptive Dialog and the composer can be used to design flows that, than, can be used in a bot with declarative and not declarative dialog. I understand that a call to CodeAction cannot be tested and could call a stubbed function but this is, in my mind, a limitation that doesn't allow use composer in bots that require internal computation
