### ISSUE TITLE
Property page for new action not displayed

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4276]
## Describe the bug

This probably isn't an easy repo as I think it's the first time I've ever seen it happen but I just added a new `SetProperties` action and composer is still showing the previous actions property editor. Clicking to another action and back resolved the issue:

![image](https://user-images.githubusercontent.com/698939/94305591-4504bd00-ff26-11ea-9499-91da9706a1e6.png)

## Version

1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by tdurnford** [comment]
I'm able to consistently repro this. 

**Steps to reproduce**
1. Add a Set Properties action
1. Add a new property with a value to the action
1. Keep focus on the Set Properties action you just added
1. Add a second Set Properties action *above* the first Set Properties action you added in the visual editor

Interestingly enough, the behavior doesn't repro if you add the second Set Properties action below the first one.

**Comment by a-b-r-o-w-n** [comment]
@LouisEugeneMSFT can you investigate this?

**Comment by tdurnford** [comment]
The previous fix is causing issues with toggling between expressions.
