### ISSUE TITLE
Change the color of memory paths only referenced in one place

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4277]
## Is your feature request related to a problem? Please describe.

The new intelisense feature of showing previously used memory variables is helpful but still needs a bit more bake time.  What could be even more useful would be to render memory paths that are only ever referenced once using a different color.  Yes there are some complexities with this like "a.b.c" could be referenced as "b.c" when "a" is passed as an argument to a dialog, but even without that level of analysis I think this could be a super useful feature for catching typos and such at a glance.  Especially when refactoring code...

**Comment by a-b-r-o-w-n** [comment]
@mewa1024 Are you currently looking at colors for lg/expressions in other places? Maybe you can assess this?

@LouisEugeneMSFT do you have any thoughts about the implementation of @Stevenic suggestion?

**Comment by mewa1024** [comment]
@sangwoohaan is working on LG and expressions.

**Comment by sangwoohaan** [comment]
I will take this!
