### ISSUE TITLE
Copy for provisioning

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#4279]
A copy pass is needed for new provisioning feature due in R11, which includes a wizard to create or import Azure resources within Composer.

Designer: @JaskeeratBedi-cmk 

Figma file: https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-main-design-spec-UI-library?node-id=5477%3A34879

**Comment by JaskeeratBedi-cmk** [comment]
Marieke, Yan and Jaskeerat met and walked through the Figma files on 9/28. Yan left comments on the Figma file for copy suggestions and the design team has updated these in the attached Figma file.
