### ISSUE TITLE
Renaming an action doesn't show up in flow

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4281]
## Describe the bug

The UX lets you rename your actions but this doesn't always (if ever) translate to the action being renamed within the flow. Given this is a super simple way of commenting we should honor name changes by the developer and show them in the flow:

![image](https://user-images.githubusercontent.com/698939/94337390-e596c380-ff9e-11ea-8173-8a96ce474c8c.png)

## Version

1.1.1

**Comment by yeze322** [comment]
This is a bug introduced 14 days ago in #3913. The title resolver's priority was changed unexpectedly.

@beyackle Ben do you remember why we changed the priority to not putting $designer title at first place?
![image](https://user-images.githubusercontent.com/8528761/94356238-9e075900-00be-11eb-8993-93c85e705e83.png)

**Comment by yeze322** [comment]
This is a bug, refs #4405
