### ISSUE TITLE
[Plugin] useShellApi returns empty object in ui plugin

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#4285]
## Is your feature request related to a problem? Please describe.

As stated in the plugin document: 
https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/plugins/README.md
> though nothing prevents them from making calls to the Composer server APIs.

But I don't find any example/document about how to call Composer server API.
(I suppose we shouldn't call it from scratch as its port is mutable, it may have authentication etc.)

## Describe the solution you'd like

Provide an API for calling API or document it if already exists.

**Comment by a-b-r-o-w-n** [comment]
@xieofxie what server endpoints are you wanting to call? We have exposed a shell api that wraps much of our server apis that frontend plugins can utilize.

**Comment by xieofxie** [comment]
@a-b-r-o-w-n I am calling apis from this code: https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/server/src/router/api.ts

For example, I will call `/projects/:projectId` within my custom web route `/testplugin/:projectId/info`

Could you show me how to use shell api within plugin? Thank you very much~

**Comment by boydc2014** [comment]
@yeze322 can you follow up with @xieofxie  to get the scenario and requirements clarified? If it's anything the plugin API is not able to provide and the scenario is valid, let's create a new ticket for that

**Comment by yeze322** [comment]
I will follow up. Here is an example of how to consume shellAPI
<img src="https://user-images.githubusercontent.com/8528761/95536410-99776480-0a1d-11eb-8e5f-bf1541351e8c.png" width="300" />

**Comment by xieofxie** [comment]
@yeze322  After discussion, we will focus on fixing using useShellApi in ui plugin and provide more documents for shell api functions.
My changes are here https://github.com/xieofxie/BotFramework-Composer/pull/1/files

**Comment by xieofxie** [comment]
Worked now
