### ISSUE TITLE
Refresh page, client state are lost, navigation become disabled

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#4286]
## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Bot Responses'
2. Click on browser 'Refresh page'
3. See left navigation become disabled

## Screenshots
<img width="742" alt="image" src="https://user-images.githubusercontent.com/49866537/94400801-43442f00-019c-11eb-88f1-906ac4393953.png">

**Comment by srinaath** [comment]
This was fixed with https://github.com/microsoft/BotFramework-Composer/pull/4316
