### ISSUE TITLE
"I want to feed cats and dogs" so this is an intent in which dogs and cats belong to same entity <Animals> but when i extract the entity i only get dogs and not cats so how can I extract both can you please help me with the same

### ISSUE THREAD

**Issue by likith3611** [microsoft/BotFramework-Composer#4289]
"I want to feed cats and dogs" so this is an intent in which dogs and cats belong to same entity <Animals> but when i extract the entity i only get dogs and not cats so how can I extract both can you please help me with the same

**Comment by dmvtech** [comment]
Hi @likith3611 Have you tried seeing if the same behavior happens in the Test panel inside the LUIS portal? Is it a machine learned entity or a list? (or something else?)

**Comment by likith3611** [comment]
It is machine learning entity itself and in Luis portal when I test, I am able to see both cats and dogs detected under ML entities category

**Comment by likith3611** [comment]
![image](https://user-images.githubusercontent.com/49705166/94645406-65a78b00-0309-11eb-999d-2aafc57287bf.png)
Random example doing the same

**Comment by likith3611** [comment]
Is there a solution for this?

**Comment by likith3611** [comment]
Is there a possibility of getting the luis output json?

**Comment by likith3611** [comment]
Hi it would be really great if I could get some quick response
Thanks in advance. I just need to extract the content of entities completely or get the Luis json without doing another API call

Please help me out here

**Comment by dmvtech** [comment]
Hi @likith3611 I'm investigating. I'll get back to you today.

**Comment by dmvtech** [comment]
Hi @likith3611 

Thank you for your patience.

> when i extract the entity i only get dogs and not cats so how can I extract both 

I forgot to mention earlier; can you share _how_ you are extracting the entity?

Here is a portion of my .lu:
```
@ list VehicleTravel = 
	- Car :
		- SUV
		- Truck
		- Automobile
	- Bus :
	- Boat :
		- ship
	- Spaceship :
		- Shuttle
	- Airplane :
		- airplanes
		- plane
	- Jet :
		- Jetplane
	- Motorcycle :
		- Chopper
	- Bicycle :
	- Jetpack :
	- Train :
		- Locomotive
```

Using the following LG:

`- The entities: ${turn.recognized.entities}`



And the utterance `"i want to travel by car and truck"` (truck is a synonym of car as you can see), gave me:


```
The entities: {
  "$instance": {},
  "VehicleTravel": [
    [
      "Car"
    ],
    [
      "Car"
    ]
  ]
}
```

Which is _strange_ (in my opinion).

> Is there a possibility of getting the luis output json?

You can get the whole LUIS response by using `${turn.recognized}`, but that won't help if you're only getting the normalized value for both and not the normal and synonym.

I'll continue to look into this to see if there is a more elegant way to retrieve each entity, as uttered.

**Comment by likith3611** [comment]
within set property i would do something like user.entities:=@VehicleTravel, this way i was storing the values in a variable
