### ISSUE TITLE
Publishing to existing azure resource

### ISSUE THREAD

**Issue by prakashclt** [microsoft/BotFramework-Composer#4302]
I followed the steps specified in [microsoft docs](https://docs.microsoft.com/en-us/composer/how-to-publish-bot) which has the following format -
{
"accessToken": "<your access token>",
"hostname": "<your web app name>",
"luisResource": "<your luis service name>", 
"settings": {
    "luis": {
    "endpointKey": "<your luis endpointKey>",
    "authoringKey": "<your luis authoringKey>",
    "region": "<your luis region, for example westus>"
        },
    "MicrosoftAppId": "<the appid of your bot channel registration>",
    "MicrosoftAppPassword": "<the app password of your bot channel registration>"
    }
}

But can someone please tell me where to find luis resource, authoring key, endpoint key ?

**Comment by anusharavindrar** [comment]
@prakashclt, if you want to enable LUIS with your Composer bot, then you will need to provide the values for luisResource, endpoint key, authoring key, and region. 

- If you have followed the [steps](https://docs.microsoft.com/en-us/composer/how-to-publish-bot#create-azure-resources) for 'Create Azure resources', then towards the end, you will see a generated JSON file in the command line which is similar to this:

![image](https://user-images.githubusercontent.com/48731427/94723994-70185380-030e-11eb-9a44-913b3f35a020.png)

This JSON will contain the values for luisResource, authoring key, endpoint key, and region.

- If you are not using the provisioning script, then you will need to manually create your own resources in the Azure portal.

`luisResource` - this is the hostname of your LUIS endpoint prediction resource
`authoringKey` - this is the primary key of LUIS Authoring resource
`endpointKey` - this is the primary key of LUIS Prediction resource

You will get all the values from the [LUIS portal](www.luis.ai), where you have created the app. Click on the LUIS app you want to make use of, then navigate to Manage>Azure Resources. **You will also need to make sure that you already have attached the Authoring resource with this LUIS app. You also should author and publish it in the same region.** Please refer to [this](https://github.com/microsoft/BotFramework-Composer/issues/3338#issuecomment-641920784) comment and [this](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-regions) documentation for the same.

If you haven't created a LUIS app yet, then follow [this](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/get-started-portal-deploy-app) documentation which provides the detailed steps.

**Comment by prakashclt** [comment]
Thanks for the help !
