### ISSUE TITLE
Currently Deployment script uses west by default

### ISSUE THREAD

**Issue by CopenhagenJames** [microsoft/BotFramework-Composer#4306]
## Describe the bug

When you use the specify a location to publish new resources and specify a location other than westus, the deployment fails because Luis is not available if you select eastus for location.

## Version

Version 1.1.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Follow the publish steps for new resources and add parameter --location eastus
2. Leave all other defaults and you will get a deployment error because Luis is not available in eastus

## Expected behavior

I would expect when using the --location eastus that the Luis location be set to westus or a parameter just for Luis location be available.

**Comment by cwhitten** [comment]
Hi @CopenhagenJames this is expected behavior. LUIS has available authoring regions for `westus`, `westeurope`, and `australia`. To use our provisioning script you could exclude LUIS from the provision and manually create the resource from the LUIS portal, then amending the publishing profile in Composer with the LUIS keys associated with the application created from the LUIS portal yielding a set of infrastructure in `eastus` and the LUIS infrastructure in a LUIS supported region.

**Comment by CopenhagenJames** [comment]
Agree, but you give the individual the capability to specify location and if they don’t do createluis=false then the script fails 10 minutes in.  Why not short circuit so it can be caught and do something earlier.



Thank You,


James D. Lawrence
PMP® Senior Cloud Solutions Architect | Azure Platform Evangelist
520 686-4303 (m)
MBA | MS Computer Science | MS Cyber Security | MCSD | MCAD
Email: james.lawrence@microsoft.com<mailto:james.lawrence@microsoft.com>

Interested in Obtaining Azure Certifications?  Ask me about how to get training…

[microsoft-certified-trainer-2019-2020]<https://www.youracclaim.com/badges/60909be4-283c-44a2-a5ea-dfec024b71a5/public_url> [cid:image018.png@01D697F2.A5138CD0] <https://www.youracclaim.com/badges/bbc871a3-66b8-486b-9449-d4239405fcb0/public_url>   [cid:image019.png@01D697F2.A5138CD0] <https://www.youracclaim.com/badges/32b833f0-7a48-4abd-bd86-855e39d7ba5e/public_url>   [story-impact-learning-to-connect-and-compel] <https://www.youracclaim.com/badges/321aa97e-f50c-4053-8352-d46b1d705f96/public_url>   [cid:image021.png@01D697F2.A5138CD0] <https://www.youracclaim.com/badges/0d3e0fba-4974-4126-8c41-4071c013eab8/public_url>
[microsoft-certified-azure-fundamentals (1)]<https://www.youracclaim.com/badges/737b36e0-eed3-47d7-8f7e-540849f81000/public_url>  [cid:image023.png@01D697F2.A5138CD0] <https://www.youracclaim.com/badges/c333efd2-47a7-4e74-93d1-f6d76aa31641/public_url>   [cid:image024.png@01D697F2.A5138CD0] <https://www.youracclaim.com/badges/8ebc416e-ed18-49ba-8750-a0f743e5b93a/linked_in_profile>   [microsoft-certified-azure-administrator-associate] <https://www.youracclaim.com/badges/516a1404-f296-4428-b40b-81727a60eb6f/linked_in_profile>   [cid:image026.png@01D697F2.A5138CD0] <https://www.youracclaim.com/badges/6574aeb3-bc97-4650-96d0-db279d2ea51f/public_url>   [microsoft-certified-azure-developer-associate] <https://www.youracclaim.com/badges/0f817590-ba82-4389-a558-ba0b29efe488/linked_in_profile>   [cid:image028.png@01D697F2.A5138CD0] <https://www.youracclaim.com/badges/28633103-910c-47f1-b720-9eb1e367f1ea/public_url>   [microsoft-certified-azure-devops-engineer-expert] <https://www.youracclaim.com/badges/ba63ab91-ad0f-4b0f-9cd1-967ba4f0a6d1/public_url>

  [cid:image030.png@01D697F2.A5138CD0]   [cid:image031.png@01D697F2.A5138CD0]   [comptia-security-ce-certification] <https://www.youracclaim.com/badges/c6ddbca1-8aab-4ff2-8932-c205ff64e78d/public_url>

**Comment by cwhitten** [comment]
Hi @CopenhagenJames - the team will take your scenario and look to prioritize a change in an upcoming release. Thank you

**Comment by cwhitten** [comment]
As part of the new provisioning UX, we now have a field to supply the LUIS region when there is a conflict. Closing as addressed.
