### ISSUE TITLE
Publish History does not scroll

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Composer#4311]
## Describe the bug

When showing publish history on the Publish page, whenever there are a lot of entries, they are truncated and I cannot scroll the view to see the rest of the history.

## Version

`main` branch on 10/1/2020

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Expected behavior

Allow me to scroll through the history.

## Screenshots

![image](https://user-images.githubusercontent.com/3452012/94859467-6c0d3400-03e9-11eb-8691-feac9844c8a1.png)

**Comment by VanyLaw** [comment]
design for publish page was changed. so I close it.
