### ISSUE TITLE
Microsoft Bot Composer: Hero Cards

### ISSUE THREAD

**Issue by anemit** [microsoft/BotFramework-Composer#4317]
I'm new to Microsoft Bot Composer and I am experimenting with card responses. When I create a HeroCard with name
#HeroCard everything is fine. But I can't create another one with another name like #HeroCard2 because an error appears  in "Send a response". 
![Screenshot_2](https://user-images.githubusercontent.com/48094685/94962973-0e1f4000-0500-11eb-8b51-0862788c7af0.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/48094685/94963021-1f684c80-0500-11eb-94da-1b5613f8fb7e.jpg)

**Comment by anemit** [comment]
The error: 
![Uploading Screenshot_4.jpg…]()

**Comment by anemit** [comment]
The error:
![Screenshot_4](https://user-images.githubusercontent.com/48094685/94963290-91409600-0500-11eb-800b-17a1e3e0e2b1.jpg)

**Comment by zxyanliu** [comment]
FYI. I reproduced the error as @anemit described. 
The error was gone after I opened another bot and then came back to the card bot. 

![image](https://user-images.githubusercontent.com/32497439/94977543-15c5f100-04ce-11eb-8f4f-6f34c6b76879.png)

![image](https://user-images.githubusercontent.com/32497439/94977553-21191c80-04ce-11eb-8245-9a1437571135.png)
