### ISSUE TITLE
UX - Conflict resolution UX PVA/Composer

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#4324]
Design high-level conflict resolution UX when publishing a bot to PVA while in the mean time changes have been made to the topic or trigger phrases in PVA.

(pri 1)

**Comment by cwhitten** [comment]
Closing. No plans to do this.

**Comment by mareekuh** [comment]
Oh I thought this was on the list?

**Comment by cwhitten** [comment]
I know it's not on the GA list. Perhaps a backlog item. I'll leave it open until we can discuss.
