### ISSUE TITLE
Remember PVA recognizer

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#4326]
When coming from PVA and opening a topic in composer, initially we set the recognizer to PVA NLU.
When creating another dialog/trigger as part of the same bot/dialog, can we pre-set the recogizer to the PVA NLU again?

**Comment by cwhitten** [comment]
@mareekuh as designed, it will say "Default Recognizer" by default, not "PVA NLU". What was demo'd yesterday wasn't quite where we are ending up. Reach out to me if you have further questions

**Comment by mareekuh** [comment]
Ah i see - @cwhitten where do you expect we'll be ending up instead?
