### ISSUE TITLE
null value while reading the http action response

### ISSUE THREAD

**Issue by LakshmanRaja209** [microsoft/BotFramework-Composer#4330]
Hi, 
I have added a Http Request action in Bot Composer my request is getting success.
While I am reading the response I am getting null value, where my property name is like "caller_id.name"

getting null for properties included . in name, for example :
opened_by.user_name
cmdb_ci.name
u_location.name

here is my response
{
  "channelId": "emulator",
  "conversation": {
    "id": "099928c0-07cb-11eb-bbd9-2b5c818c414f|livechat"
  },
  "from": {
    "id": "bea04ae0-0731-11eb-bbd9-2b5c818c414f",
    "name": "Bot",
    "role": "bot"
  },
  "id": "41bb1fb0-07cb-11eb-801a-670731f128aa",
  "label": "",
  "localTimestamp": "2020-10-06T11:58:32+00:00",
  "locale": "en-US",
  "name": "HttpRequest",
  "recipient": {
    "id": "8e1b85b1-bb34-4d69-aa2a-4f9f965048aa",
    "role": "user"
  },
  "replyToId": "417f7640-07cb-11eb-801a-670731f128aa",
  "serviceUrl": "http://localhost:56871",
  "timestamp": "2020-10-06T11:58:32.747Z",
  "type": "trace",
  "value": {
    "request": {
      "method": "GET",
      "url": "{url}"
    },
    "response": {
      "content": {
        "result": [
          {
            "actions_taken": "",
            "assigned_to.user_name": "",
            "assignment_group.name": "",
            "business_service.name": "",
            "caller_id.user_name": "",
            "close_code": "",
            "close_notes": "",
            "cmdb_ci.name": "",
            "comments": "",
            "contact_type": "",
            "description": "",
            "escalation": null,
            "hold_reason": null,
            "major_incident_state": "accepted",
            "number": "",
            "opened_by.user_name": "",
            "priority": "2",
            "problem_id.number": "",
            "resolved_at": "",
            "resolved_by.user_name": "",
            "short_description": "",
            "state": "7",
            "u_add_fields": "0",
            "u_bau_lead.user_name": "",
            "u_bst_leader.user_name": "",
            "u_client_contact_1": "0",
            "u_client_contact_2": "0",
            "u_client_contact_3": "0",
            "u_comments": null,
            "u_comments_2": null,
            "u_comments_3": null,
            "u_communications_advisor.user_name": "",
            "u_configuration_item_id": "",
            "u_crisis": "0",
            "u_crisis_processlead.user_name": "",
            "u_current_location.name": "",
            "u_datamgmt_lead.user_name": "",
            "u_deactivation_restriction_reason": null,
            "u_deputy_bst_lead.user_name": "",
            "u_documentation_lead.user_name": "",
            "u_escalation_mgmt": null,
            "u_escalationt": "0",
            "u_ext_company_name": null,
            "u_ext_external_company_id": null,
            "u_ext_external_company_reference.name": "",
            "u_external_company.name": "noc.ops",
            "u_external_ticket_number": null,
            "u_finance_lead.user_name": "",
            "u_financial_impact_statement": "",
            "u_hr_coordinator.user_name": "",
            "u_incident_commander.user_name": "",
            "u_incident_restrictor.user_name": "",
            "u_information_officer.user_name": "",
            "u_lead_resolution_manager.user_name": "",
            "u_legal_officer.user_name": "",
            "u_location.name": "Test",
            "u_major_incident_manager.user_name": "",
            "u_mi_candidate_justf": "",
            "u_mi_impact_type": "financial",
            "u_non_business_impact_statement": null,
            "u_operations_section_chief.user_name": "",
            "u_ops_manager.user_name": "",
            "u_planningsection_chief.user_name": "",
            "u_reputational_impact_including_hsse_statement": null,
            "u_req_info": null,
            "u_requested_information": null,
            "u_resource_unit_lead.user_name": "",
            "u_restricted_incident": "0",
            "u_restricted_to": null,
            "u_restriction_reason": null,
            "u_safety_officer.user_name": "",
            "u_security_officer.user_name": "",
            "u_situation_unit_leader.user_name": "",
            "u_vulnerability_impact_statement": null,
            "watch_list": null,
            "work_notes": "",
            "work_notes_list": null
          }
        ]
      },
      "headers": {
        "Cache-Control": "no-cache,no-store,must-revalidate,max-age=-1",
        "Date": "Tue, 06 Oct 2020 11:58:32 GMT",
        "Link": "",
        "Pragma": "no-store",
      },
      "reasonPhrase": "OK",
      "statusCode": 200
    }
  },
  "valueType": "Microsoft.HttpRequest"
}

**Comment by ryanlengel** [comment]
Thank you for your submission @LakshmanRaja209. @cwhitten can you take a look and route appropriately?

**Comment by zxyanliu** [comment]
FYI. We have two docs regarding how to use the **Send an HTTP request** action:
* [Send an HTTP request](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather#add-an-http-request) in the weather tutorials.
* [Send an HTTP request](https://docs.microsoft.com/en-us/composer/how-to-send-http-request#add-a-send-an-http-request-action) in the how-to guides.

**Comment by LakshmanRaja209** [comment]
you can access the property like **dialog.apiresult.content.result[0]['location.name']**
