### ISSUE TITLE
Removing the value of "output format" causes a zero length string to be serialized to the JSON which causes errors

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#4332]
## Describe the bug

If I set the output format of a prompt, then remove that value, a zero length string ends up in the JSON.

This causes the SDK to reformat the prompt value to "", which causes the "unrecognized prompt" to fire every single time.

## Version

1.1.1

## Browser

- [x] Electron distribution

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1.  create a prompt
2. set the unrecognized prompt to something like "UNRECOGNIZED"
3. set a value in output format.
4. remove the value from output format
5. run the bot

You will see that the prompt loops and displays the unrecognized prompt without ever capturing the user's input.

## Expected behavior

I would expect a blank value in the output format to have no effect on the bot's behavior.  Perhaps a blank value for this should result in the key being removed completely from the output.

## Additional context

I opened a ticket in the dotnet repo for this as well.

https://github.com/microsoft/botbuilder-dotnet/issues/4758

**Comment by cwhitten** [comment]
@boydc2014 don't let us forget to discuss this in the platform standup this evening

**Comment by benbrown** [comment]
Fixed in the SDK.
