### ISSUE TITLE
Start Bot Failed Messages When Trying To Launch The Bot Using Bot Framework Composer

### ISSUE THREAD

**Issue by smynam** [microsoft/BotFramework-Composer#4339]
Start bot failed

Error: Command failed: dotnet user-secrets init --project azurewebapp /bin/sh: dotnet: command not found

## Version

version : 1.1.1 <> Elsctron 8.2.4 <>NOdeJS:12.13.0

## Browser

- [ ] Electron distribution
- [ ] Chrome [X]
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS [X]
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to '...'Bot Framework Composer
2. Click on '....'Add New Bot From Scratch, once added, add the greetings action and now click "Start Bot"

## Expected behavior

The Bot should have launched as an simulator
<img width="1016" alt="Screen Shot 2020-10-08 at 1 22 31 AM" src="https://user-images.githubusercontent.com/22480033/95414676-6a1d0680-08fc-11eb-976d-0ba719a6fa55.png">

## Additional context

na

**Comment by nitroin** [comment]
Have you installed the .NET Core SDK?

Quoting the [docs](https://docs.microsoft.com/en-us/composer/setup-yarn#prerequisites):

### Prerequisites
* The Bot Framework Emulator.
* The .NET Core SDK 3.1 and above.
* Download and use Composer: Windows | macOS | Linux.

**Comment by cwhitten** [comment]
As @nitroin explained, it looks like you may need to install the dotnet dependencies.

**Comment by jeffhagins** [comment]
I'm having the same issue. It was working fine last night. This morning I quit Composer and the Emulator and re-launched them and now I'm seeing this error.
