### ISSUE TITLE
how to compare two dates in composer

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#4346]
Hi,

I want to compare two dates in a if else condition can anybody please tell me how do I achieve this because I am getting the wrong output(failure). Below is my screenshot.

<img width="716" alt="condition-test" src="https://user-images.githubusercontent.com/70739031/95583689-20e2c900-0a5a-11eb-9ef6-dad8fcc15a9e.PNG">

Thanks,
Madan

**Comment by benbrown** [comment]
Use the `ticks()` expression to convert the date into a number - so,

`ticks(formatDateTime(dateProperty))`

**Comment by lzc850612** [comment]
@BeheraMadan does the above comment answer your question? Thanks.

**Comment by BeheraMadan** [comment]
Thanks for quick response it works.
