### ISSUE TITLE
Bot App deployed by Composer cannot start

### ISSUE THREAD

**Issue by kuacci** [microsoft/BotFramework-Composer#4348]
## Deploy to existing web app on azure not work

We followed below document of composer to publish bot to an existing web app instance running on azure. The publish output prompt success, but we got 502.5 response.
* https://docs.microsoft.com/en-us/composer/how-to-publish-bot#deploy-to-existing-azure-resources

The error of 502.5
![image](https://user-images.githubusercontent.com/5857515/95648847-e5ed9d80-0b0c-11eb-92e1-2f9eef1e986a.png)

The error we got from stdout log:
```
 A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in  'D:\home\site\wwwroot\'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the D:\home\site\wwwroot\Microsoft.BotFramework.Composer.WebApp.runtimeconfig.json file specifying the appropriate framework. 
```

After investigate further, we noticed that bot was set to OutOfProcess mode and the process of dotnet.exe didn't startup because the file deployed by composer missed **\<entry-dll\>.runtimeconfig.json.**

we can find EchoBot.runtimeconfig.json, but the the entry was set to **Microsoft.BotFramework.Composer.WebApp.dll** instead of **EchoBot.dll** in web.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\Microsoft.BotFramework.Composer.WebApp.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="OutOfProcess" />
    </system.webServer>
  </location>
</configuration>
```

After we uploaded file Microsoft.BotFramework.Composer.WebApp.runtimeconfig.json then it works.

It's all good if we deploy bot to a new azure resource.
> https://docs.microsoft.com/en-us/composer/how-to-publish-bot#deploy-to-new-azure-resources 

## Version

We pulled the latest code from composer repo and build it in azure vm. The document link as below:
> https://docs.microsoft.com/en-us/composer/how-to-host-composer

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [ ] Windows
- [x] Ubuntu

## To Reproduce

1. Go to publish tab of composer
2. Edit the profile and set the name of existing web app to hostname field, and other required fields like appId, appPassword and access token.
3. Run publish and prompt success.
4. Go to the existing web app and access its page or **https://\<app-name\>/api/messages** then see the error

## Expected behavior

Please help to point out anything we are missing to config composer if this is not an issue of composer.

Otherwise, we expected that app published by composer should be qualified for app service requirement, like the dotnet runtime configuration file for entry assembly should be deployed to app service as well if it is self-contained.

**Comment by ryanlengel** [comment]
@benbrown please assign to the appropriate resource, thank you!

**Comment by benbrown** [comment]
@kuacci - are you using the standard runtime code that is packaged with Composer? I am not familiar with the runtime config file.

**Comment by luhan2017** [comment]
@kuacci The Microsoft.BotFramework.Composer.WebApp.runtimeconfig.json should be auto-generated when you build your runtime, Could it be an Ubuntu specific issue? Let's sync through Teams for more details on this issue?

**Comment by kuacci** [comment]
Here is the runtimeconfig I uploaded to make it work:
```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "3.1.0"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```

**Comment by zidaneymar** [comment]
I could repro this issue under ubuntu environment (same code work for windows but not work for linux), need further investigation.

**Comment by zidaneymar** [comment]
https://github.com/microsoft/BotFramework-Composer/blob/bbb65c830d1f0e21fc23f5b05760726c06e778cd/Composer/plugins/runtimes/src/index.ts#L68

Change this line to 
```
          `dotnet publish "${dotnetProjectPath}" -c release -o "${publishFolder}" -v q --self-contained true -r win10-x86`,
```
could resolve this issue.

**Comment by kuacci** [comment]
Thank you @zidaneymar . 

Seems like `-r win10-x86` only makes bot app works for windows environment, like windows based app service. How about the linux container based app service instance, or even linux vm? Is it possible to make this option open to user on Composer UI?

-Thanks

**Comment by luhan2017** [comment]
We should make this as an optional parameter in deployment process and default to windows, currently our two supported targets are azure web app and azure functions, they both use windows by default. If user want to deploy to a Linux system, they can set that optional parameter to linux.

**Comment by kuacci** [comment]
Sounds good and thanks for your work on this.
