### ISSUE TITLE
[Plugin] get server's address and port in plugin

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Composer#4349]
## Is your feature request related to a problem? Please describe.

When I add one ui plugin and one webroute plugin, I don't know the server's address and port in ui plugin when calling webroute plugin's apis.

## Describe the solution you'd like

Provide this info somewhere.

**Comment by cwhitten** [comment]
@xieofxie you can access the backend without knowing the port that the webserver is listening on by using relative paths in your api calls

**Comment by xieofxie** [comment]
@cwhitten I think I still need the port in this case. For example, when I run Composer locally, custom ui plugin will be under `http://localhost:3000/plugin/sample-ui-plugin/page` while webroute plugin is `http://localhost:5000/testplugin/75985.4504651456/files`. If I call webroute via relative path in ui plugin, it will be `http://localhost:3000/testplugin/75985.4504651456/files` which is 404.
