### ISSUE TITLE
Stop ConversationUpdate trigger when Activity Event is triggered

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4352]
We have a chatbot that is placed on different sites. One of the sites sends init data in the client using an event called WebInit. This event is picked up at the root dialog and the data is stored in the user object and used to welcome the user personally. However for the other sites there is no WebInit event thus the same bot starts the conversation also on ConversationUpdate activity, starting the welcome message / menu twice on the bot that has the WebInit event.

When trying to set a flag in the WebInit trigger to stop the ConversationUpdate from triggering seems not to work, this is not set in time. 

How can I determine that there is a WebInit event and stop the ConversationUpdate trigger?

**Comment by luhan2017** [comment]
@cxbuilders , can you try to add a condition to the OnConversationUpdate trigger?
For example, OnConversationUpdate (condition: isAlreadyTriggered=false)

**Comment by cxbuilders** [comment]
@luhan2017 I have been doing more testing and the OnConversationUpdate trigger is just not something to be relied upon. Also reading this doc: https://blog.botframework.com/2018/07/12/how-to-properly-send-a-greeting-message-and-common-issues-from-customers/

Additionally I found out that there is even a difference when using a secret directly or use the secret to get a token to start the chat, whereby the first only adds the bot to the conversation and the second adds both in the same convUpdate activity.

So I am going to use a WebInit event regardless for web and optionally sent data with it, so that this will always be the single starting point for the conversation.

Thanks for looking into this, closing this now.

**Comment by luhan2017** [comment]
@cxbuilders , Thanks for reporting this, your concern is fully understood, for the conversationUpdate event issue, the abs team will release a fix to this in R11, the OnConversationUpdate trigger will work as expected then, we don't have a better solution for that right now expect customizing on that. I will close this for now. Feel free to reopen if you are still blocked by this.
