### ISSUE TITLE
LG Fails on Variables with Whitespace

### ISSUE THREAD

**Issue by Beeez** [microsoft/BotFramework-Composer#4359]
When using "Send a response", I get errors when attempting to get JSON content that has a space in it. 
![image](https://user-images.githubusercontent.com/46723579/95902176-6c4eed00-0d62-11eb-82e7-6e758da7679d.png)

I set a property here called dialog.AppConcat, and a value of ${dialog.appInfo.content.${user.AppChoice}}.

If my selection includes a space, it fails. If it does not include a space, it gets the correct data. 

I tried wrapping the variable in quotes and escaping them but it all failed.

If I was to type out a selection manually...
![image](https://user-images.githubusercontent.com/46723579/95901423-4f65ea00-0d61-11eb-8d2e-f3a291d5cc1c.png)

When running in Emulator with ${dialog.appInfo.content${user.AppChoice}}
![image](https://user-images.githubusercontent.com/46723579/95902263-8dafd900-0d62-11eb-9e04-797d97ad088a.png)
![image](https://user-images.githubusercontent.com/46723579/95901549-850ad300-0d61-11eb-97c4-aea64a992a6e.png)

When selecting an app with no spaces it works. 
![image](https://user-images.githubusercontent.com/46723579/95901697-b7b4cb80-0d61-11eb-9abc-b2523dcc5b97.png)

1.1.1

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Get Keyed JSON with objects that have whitespaces
2. Create User Input Choice from list
3. Send a response that includes the objects from the selection that has a space

## Expected behavior

I would expect to be able to escape or use quotes in some fashion to allow accessing of JSON objects that include spaces.

**Comment by cosmicshuai** [comment]
@Beeez 
In this scenario, you can accessing a property by `SomeObj[propName]`. This ensures you can get the right results even there are whitespaces in the property name.
![image](https://user-images.githubusercontent.com/17074777/95961564-ca99cf80-0e37-11eb-9aca-60c16d581a84.png)
You should accessing the property by ` ${dialog.appInfo.content[user.AppChoice]}.` in the value field.

In the LG editing field, it should be written as:
```
- ${dialog.appInfo.content["Barrucuda Email Security Gateway"]}
```

**Comment by Beeez** [comment]
@cosmicshuai 
That worked perfectly. Not sure why I didn't see that at all in the docs. 

Thank you
