### ISSUE TITLE
Error publishing in new profile

### ISSUE THREAD

**Issue by kdubious** [microsoft/BotFramework-Composer#4376]
{"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}}

I just created a profile, then went to publish, and got this error.

**Comment by kdubious** [comment]
Interestingly, I think it may have published, though.

**Comment by kdubious** [comment]
Actually... nope, something is not right.

**Comment by kdubious** [comment]
I filled in some details in the settings (not just in publish profile) and now I get this error:

400 - "{\r\n \"error\": {\r\n \"code\": \"BadArgument\",\r\n \"message\": \"The source completed without providing data to receive.\"\r\n }\r\n}"

**Comment by kdubious** [comment]
Start bot seems to work, but outputs this:

Unhandled exception. System.ArgumentException: ContainerId is required. (Parameter 'cosmosDbStorageOptions') at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage..ctor(CosmosDbPartitionedStorageOptions cosmosDbStorageOptions) at Microsoft.BotFramework.Composer.WebAppTemplates.Startup.ConfigureStorage(BotSettings settings) in C:\Users\kdubi\AppData\Roaming\BotFrameworkComposer\hostedBots\70228.45976941696\runtime\azurewebapp\Startup.cs:line 77 at Microsoft.BotFramework.Composer.WebAppTemplates.Startup.ConfigureServices(IServiceCollection services) in C:\Users\kdubi\AppData\Roaming\BotFrameworkComposer\hostedBots\70228.45976941696\runtime\azurewebapp\Startup.cs:line 163 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services) at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services) at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services) at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services) at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider() at Microsoft.Extensions.Hosting.HostBuilder.Build() at Microsoft.BotFramework.Composer.WebAppTemplates.Program.Main(String[] args) in C:\Users\kdubi\AppData\Roaming\BotFrameworkComposer\hostedBots\70228.45976941696\runtime\azurewebapp\Program.cs:line 16

**Comment by ryanlengel** [comment]
@luhan2017 can you please take a look at this issue? Thank you!

**Comment by kdubious** [comment]
@luhan2017 and @ryanlengel : Unfortunately, I blew away the resources in my Azure and ran the 'provisionComposer.js' command all over again. So I can't help with this issue any more.

**Comment by ryanlengel** [comment]
Ok @kdubious in that case I will close this - feel free to reopen if this occurs again.
