### ISSUE TITLE
Please sort bot settings properties

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#4377]
## Describe the bug

The properties in the bot settings don't seem to be arranged in any meaningful order. This has led to some considerable work hours being wasted because of the app password breaking tradition by preceding the app ID. At least two people have run into this problem already: https://github.com/microsoft/BotFramework-Composer/issues/3504

At a minimum, the app password should follow the app ID in accordance with the principle of least surprise. It may be worthwhile to rearrange the rest of the properties as well so that they're grouped in some logical way. It's also worth considering just arranging them all in alphabetical order, since JSON properties aren't ordered when parsed and are likely to be displayed in alphabetical order afterwards.

## Version

v1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Settings'
2. Click on 'Bot Settings'
3. Scroll down to the raw JSON panel
4. See the order of properties

## Expected behavior

The `MicrosoftAppId` property should come before the `MicrosoftAppPassword` property and not after.

## Screenshots

![image](https://user-images.githubusercontent.com/41968495/96034517-7df1cc80-0e16-11eb-80be-3b656be75bb6.png)

**Comment by cwhitten** [comment]
@v-kydela AppId & AppPassword are serialized next to each other. Are you not seeing this behavior on 1.1.1?

**Comment by v-kydela** [comment]
@cwhitten - I'm sorry if I wasn't clear. AppId & AppPassword are indeed serialized next to each other. The problem is not that they are separated from each other. The problem is the order.

Expected: AppId then AppPassword
Actual: AppPassword then AppId

The reason that this is important is because it results in users entering their app password as the app ID and the app ID as the app password. I know of at least three engineers who have done this so far. Hours have spent trying to figure out what went wrong, and I suspect more hours will be wasted if the order is not fixed.

**Comment by dmvtech** [comment]
Looks like we have it the standard/alphabetical way in the publishing:
![image](https://user-images.githubusercontent.com/43397658/97481064-81ef1580-1911-11eb-8fdb-573c0343371d.png)

It's just the settings that are different, as @v-kydela showed above.
