### ISSUE TITLE
QnA files are sometimes added to project in the wrong place

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#4378]
## Describe the bug

When a project is opened, for each dialog that DOES NOT ALREADY include a .qna file, one is added. However, these files are always added at the /dialogs/nameOfDialog folder.

If the dialogs in question are not in the /dialogs folder, or are in a subfolder of the dialogs folder, the related .qna files should be placed in the existing folder, not in a new one.

For example, if /dialogs/imported/getEmail is added to the project, the .qna file should be in /dialogs/imported/getEmail, not in /dialogs/getEmail as currently happens, resulting in 2 folders.

Whatever code is creating these .qna files should NOT be opinionated about the location of the dialogs, as they can technically exist in any folder or subfolder of the project.

## Version

1.1.1

# Steps to reproduce the behavior:

1. Create a project
2. Open it in the file system and copy an existing dialog into /dialogs/imported/someFolderName
3. Open the project in Composer
4. Look at the file system again - you will see /dialogs/someFolderName has been erroneously created with an empty qna file.

## Expected behavior

The new qna file will be created inside the existing folder.

**Comment by srinaath** [comment]
@liweitian  i remember u writing the piece for migration on the Composer server. Seems like the .qna files are getting created at the wrong path

**Comment by cwhitten** [comment]
@liweitian @zhixzhan I've added this into R11 as something we want to address before our next release.

**Comment by liweitian** [comment]
@cwhitten will have a look.

**Comment by zhixzhan** [comment]
I'm looking into this.
