### ISSUE TITLE
docs: how to use updateActivity and deleteActivity

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#4379]
The option to update an existing message or delete one that has already been sent was added in 1.1.1. We need to document how these can be used.

Key information can be found here:
https://github.com/microsoft/BotFramework-Composer/issues/4233

* The necessary activity ID can be retrieved using `turn.lastresult.id`
* This feature does NOT work in Emulator or webchat - it only works when running in Teams or another channel that supports update/delete.

**Comment by zxyanliu** [comment]
It seems that only Teams support this feature. 
See: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#summary-table-all-activities-to-all-channels

**Comment by benbrown** [comment]
Some of the adapters also support these mechanisms.

**Comment by zxyanliu** [comment]
@dmvtech Helped a lot on this, the [PR](https://github.com/MicrosoftDocs/composer-docs-pr/pull/242) is pending review now.

**Comment by zxyanliu** [comment]
Closing this issue since it is addressed. 
The content was merged and will go live soon. 
Thanks! : -)
