### ISSUE TITLE
Code editor view when read-only does not pass accessibility

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#4382]
## Describe the bug

Any places where the code editor is showing a filed that is read-only, read-only is indicated by reducing the opacity. This makes the text difficult to read and does not pass contrast requirements needed for accessibility

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

Here's one way to view a text file in read-only mode:
1. Go to 'Settings > Bot settings'
2. Click on 'Create copy to transate bot content'
3. In the 'Copy content for translation', pick a new language.
4. Back in the bot settings, in the 'Bot language (active)' dropdown, select the new language.
5. Click on the Bot Responses icon in the top-level nav.
6. Select a dialog.
7. Click the Edit mode toggle.

You'll see a code editor in editable and read-only modes side by side:

![image](https://user-images.githubusercontent.com/39317542/96054200-fb790500-0e35-11eb-9941-a67c0b2455a8.png)

## Expected behavior

Some other indicator that the file is read-only. Is there a different read-only behavior already in place with the Monaco editor that we could follow that is accessible?

## Screenshots
See above.

**Comment by cwhitten** [comment]
@sangwoohaan please take a look at this
