### ISSUE TITLE
Orchestrator UX integration 

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#4390]
1. Provide new choice in recognizer (orchestrator) with the designed tooltip and help link. 
   * after user choose orchestrator the downloading will starting by default, before downloaded, the start bot is not allowed
   * before https://github.com/microsoft/botbuilder-dotnet/issues/4651 is addressed, after user choose orchestrator, we will have to user $designer.id to mark this is orchestrator instead of LUIS

2. Create a new filed in settings page for the base model selection (by default is the least layer bert-3layers)
3. Download the base model to a shared location. Consider both web scenario and electron scenario. 
4. Generate the recognizer dialogs once user choose Orchestrator, related PR: https://github.com/microsoft/BotFramework-Composer/pull/435
5. Do the orchestrator:build + luis:build based on the dialog choices (@lei9444)
6. Verify it works locally (at this time, remote deploy should not work, because base model missing in remote)

**Comment by luhan2017** [comment]
Will this impact the qna scenario? Based on my understanding, if use selects Orchestrator, it means he/she selects Ochestrator+QnA, and a CrossTrainedRecognizer will be generated?
