### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by kdubious** [microsoft/BotFramework-Composer#4393]
## Describe the bug
Switched the app settings to use Early Adopters = true

## Version
V 1.1.1

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Composer

Couldn't complete the update: Error: 404 Not Found "method: GET url: https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/download/v1.1.1-nightly.174189.68cb8bb/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n" Headers: { "server": "GitHub.com", "date": "Thu, 15 Oct 2020 15:50:43 GMT", "content-type": "text/plain; charset=utf-8", "status": "404 Not Found", "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With", "cache-control": "no-cache", "strict-transport-security": "max-age=31536000; includeSubdomains; preload", "x-frame-options": "deny", "x-content-type-options": "nosniff", "x-xss-protection": "1; mode=block", "referrer-policy": "no-referrer-when-downgrade", "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"", "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'", "content-encoding": "gzip", "set-cookie": [ "_gh_sess=qTRpHGi%2B3u92sDdLCTEtREOs9mG%2FryL5mbeyxEckXViFheQ0bWON96ixgydJ%2BPhiNUnZpDTYLZRFaeIpcMQBvZ85BEpeHmoIEo17FQu0fgMJ0iq8dB7VQlEJtK%2FOauqYXFg2kTC43S1F9OS9nnMJJUGndc5lXMIOZGAtyCxCLaU%2FDyMTlAlgIUMkdINjkGo%2BGE1yLumL0zbqts0zRtNFpW%2BXq8zgPKxlwOS2tCYQDV5gJ3%2BC2keBgbcUBpEBchvA%2FW1Jtk0jCDiovz4gZ8tO1w%3D%3D--xzI7bE%2Betln44bP5--sVFY%2FxssKk4uhYUnfV66Dw%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax", "_octo=GH1.1.1746991414.1602777043; Path=/; Domain=github.com; Expires=Fri, 15 Oct 2021 15:50:43 GMT; Secure; SameSite=Lax", "logged_in=no; Path=/; Domain=github.com; Expires=Fri, 15 Oct 2021 15:50:43 GMT; HttpOnly; Secure; SameSite=Lax" ], "content-length": "40", "x-github-request-id": "CA60:2257:A121D:1418A6:5F886FD3" }

**Comment by cwhitten** [comment]
@kdubious this has been addressed. Closing for now but please comment if the issue is not resolved for you.

**Comment by kdubious** [comment]
I still have the issue, just tripped over it. I hoped using the latest would solve that I can't publish due to rate limits in LUIS

**Comment by kdubious** [comment]
Restarted and it updated. Thanks!
