### ISSUE TITLE
"Publish bot to Azure" choice has no text

### ISSUE THREAD

**Issue by kdubious** [microsoft/BotFramework-Composer#4394]
## Describe the bug
No text for the first entry in the dropdown

![image](https://user-images.githubusercontent.com/9756166/96171066-64be4e00-0ef2-11eb-8875-706e40884e66.png)

## Version
Version:  1.1.1-nightly.172371.8d1fc5a

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Publish'
2. Click on 'Add new Profile'
3. See the value is missing

## Expected behavior
Should show something like "Publish bot to Azure"

## Screenshots
![image](https://user-images.githubusercontent.com/9756166/96171066-64be4e00-0ef2-11eb-8875-706e40884e66.png)

**Comment by ryanlengel** [comment]
@tonyanziano can you please take a look at this issue? Thank you!

**Comment by tonyanziano** [comment]
This is something @a-b-r-o-w-n and I overlooked and we plan to fix this by supporting multiple publish extensions from one extension source.

**Comment by a-b-r-o-w-n** [comment]
No, but I can address today.
