### ISSUE TITLE
Publish to Azure Fails

### ISSUE THREAD

**Issue by kdubious** [microsoft/BotFramework-Composer#4395]
## Describe the bug
Publish to Azure using a project I have published several times before. It fails with a 400 error.

400 - "{\r\n \"error\": {\r\n \"code\": \"BadArgument\",\r\n \"message\": \"The source completed without providing data to receive.\"\r\n }\r\n}"

## Version
Version:  1.1.1-nightly.172371.8d1fc5a
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0
## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Publish'
2. Click on 'Publish to selected profile'
3. See error

## Expected behavior

Publish should complete with no error.

## Screenshots

![image](https://user-images.githubusercontent.com/9756166/96185638-321f5000-0f08-11eb-998c-3472b05d3cbd.png)

## Additional context

I started with the EchoBot template. I made several changes, and added several intents. I was able to publish many times. Now it fails.

**Comment by kdubious** [comment]
From the publish log:

`{
  "status": "DEPLOY_INFO",
  "message": "start publish luis"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - \\\"{\\\\r\\\\n  \\\\\\\"error\\\\\\\": {\\\\r\\\\n    \\\\\\\"code\\\\\\\": \\\\\\\"BadArgument\\\\\\\",\\\\r\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"The source completed without providing data to receive.\\\\\\\"\\\\r\\\\n  }\\\\r\\\\n}\\\"\",\"error\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"BadArgument\\\",\\r\\n    \\\"message\\\": \\\"The source completed without providing data to receive.\\\"\\r\\n  }\\r\\n}\",\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - \\\"{\\\\r\\\\n  \\\\\\\"error\\\\\\\": {\\\\r\\\\n    \\\\\\\"code\\\\\\\": \\\\\\\"BadArgument\\\\\\\",\\\\r\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"The source completed without providing data to receive.\\\\\\\"\\\\r\\\\n  }\\\\r\\\\n}\\\"\\n    at new StatusCodeError (C:\\\\Users\\\\kdubi\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\errors.js:32:15)\\n    at Request.plumbing.callback (C:\\\\Users\\\\kdubi\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\plumbing.js:104:33)\\n    at Request.RP$callback [as _callback] (C:\\\\Users\\\\kdubi\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\plumbing.js:46:31)\\n    at Request.self.callback (C:\\\\Users\\\\kdubi\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:185:22)\\n    at Request.emit (events.js:210:5)\\n    at Request.<anonymous> (C:\\\\Users\\\\kdubi\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:1154:10)\\n    at Request.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Users\\\\kdubi\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:1076:12)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
}
400 - "{\r\n  \"error\": {\r\n    \"code\": \"BadArgument\",\r\n    \"message\": \"The source completed without providing data to receive.\"\r\n  }\r\n}"`

**Comment by kdubious** [comment]
I deleted the app from LUIS, and published again.
The app was back in LUIS, but same failure error in Composer.
--
I then connected the app in LUIS to the Prediction Resource and published again. Same error.

**Comment by luhan2017** [comment]
@kdubious This seems like a luis account issue, https://github.com/microsoft/BotFramework-Composer/issues/3321#issuecomment-644619986. Is there anything changed for your luis account?

**Comment by kdubious** [comment]
@luhan2017 Interesting! The Azure CLI seems to have jumped to another tenant. When I ran the command to get an updated token, it pulled one from another tenant to which I have access, but to whom i did not connect in that terminal session.

**Comment by jpd21122012** [comment]
I have the same problem, when trying to publish with LUIS Service fails, my token is working good, any idea?

**Comment by jpd21122012** [comment]
> I have the same problem, when trying to publish with LUIS Service fails, my token is working good, any idea?

Here's the log 

Publish starting...
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\slipk\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\e6919890eb277b4044adbbd03678093c\\azurewebapp\\ComposerDialogs\\generated\\interuption\\enigmamxbot.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\slipk\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\e6919890eb277b4044adbbd03678093c\\azurewebapp\\ComposerDialogs\\generated\\interuption\\enigmamxbot.en-us.lu no changes\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\slipk\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\e6919890eb277b4044adbbd03678093c\\azurewebapp\\ComposerDialogs\\generated\\enigmamxbot.en-us.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\slipk\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\e6919890eb277b4044adbbd03678093c\\azurewebapp\\ComposerDialogs\\generated\\enigmamxbot.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\slipk\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\e6919890eb277b4044adbbd03678093c\\azurewebapp\\ComposerDialogs\\generated\\enigmamxbot.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\slipk\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\e6919890eb277b4044adbbd03678093c\\azurewebapp\\ComposerDialogs\\generated\\luis.settings.aeba.westus.json\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "lubuild succeed"
}
{
  "status": "DEPLOY_INFO",
  "message": "start publish luis"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - \\\"{\\\\r\\\\n  \\\\\\\"error\\\\\\\": {\\\\r\\\\n    \\\\\\\"code\\\\\\\": \\\\\\\"BadArgument\\\\\\\",\\\\r\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"The source completed without providing data to receive.\\\\\\\"\\\\r\\\\n  }\\\\r\\\\n}\\\"\",\"error\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"BadArgument\\\",\\r\\n    \\\"message\\\": \\\"The source completed without providing data to receive.\\\"\\r\\n  }\\r\\n}\",\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - \\\"{\\\\r\\\\n  \\\\\\\"error\\\\\\\": {\\\\r\\\\n    \\\\\\\"code\\\\\\\": \\\\\\\"BadArgument\\\\\\\",\\\\r\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"The source completed without providing data to receive.\\\\\\\"\\\\r\\\\n  }\\\\r\\\\n}\\\"\\n    at new StatusCodeError (C:\\\\Users\\\\slipk\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\errors.js:32:15)\\n    at Request.plumbing.callback (C:\\\\Users\\\\slipk\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\plumbing.js:104:33)\\n    at Request.RP$callback [as _callback] (C:\\\\Users\\\\slipk\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\plumbing.js:46:31)\\n    at Request.self.callback (C:\\\\Users\\\\slipk\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:185:22)\\n    at Request.emit (events.js:210:5)\\n    at Request.<anonymous> (C:\\\\Users\\\\slipk\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:1154:10)\\n    at Request.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Users\\\\slipk\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:1076:12)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
}
400 - "{\r\n  \"error\": {\r\n    \"code\": \"BadArgument\",\r\n    \"message\": \"The source completed without providing data to receive.\"\r\n  }\r\n}"

**Comment by kdubious** [comment]
@jpd21122012 did you make sure the token is from the correct tenant?

**Comment by jpd21122012** [comment]
> @jpd21122012 did you make sure the token is from the correct tenant?

Yes, totally sure, I've also created a token from Azure Cloud Shell, selecting the correct subscription, and it's the same.

**Comment by philip-mc** [comment]
Hello there, my partner and I have also run into the same issue as above. 
After following the tutorial on Microsoft's web page (to make a weather bot) we have been unable to get it to publish. the Luis account works in composers emulator, but when we try to push in publishing it comes up with the error.

The log shows the same (or similar) error:

`Publish starting...
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\interuption\\Cancel.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\interuption\\GetWeather.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\interuption\\help.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\interuption\\weatherbot.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\interuption\\weatherbot.en-us.lu no changes\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\weatherbot.en-us.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\weatherbot.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\Cancel.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\GetWeather.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\help.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\weatherbot.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\Otter\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\5fc68681cb5057b653b63f12dd99d431\\azurefunctions\\ComposerDialogs\\generated\\luis.settings..westus.json\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "lubuild succeed"
}
{
  "status": "DEPLOY_INFO",
  "message": "start publish luis"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - \\\"{\\\\r\\\\n  \\\\\\\"error\\\\\\\": {\\\\r\\\\n    \\\\\\\"code\\\\\\\": \\\\\\\"BadArgument\\\\\\\",\\\\r\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"The source completed without providing data to receive.\\\\\\\"\\\\r\\\\n  }\\\\r\\\\n}\\\"\",\"error\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"BadArgument\\\",\\r\\n    \\\"message\\\": \\\"The source completed without providing data to receive.\\\"\\r\\n  }\\r\\n}\",\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - \\\"{\\\\r\\\\n  \\\\\\\"error\\\\\\\": {\\\\r\\\\n    \\\\\\\"code\\\\\\\": \\\\\\\"BadArgument\\\\\\\",\\\\r\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"The source completed without providing data to receive.\\\\\\\"\\\\r\\\\n  }\\\\r\\\\n}\\\"\\n    at new StatusCodeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\errors.js:32:15)\\n    at Request.plumbing.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\plumbing.js:104:33)\\n    at Request.RP$callback [as _callback] (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request-promise-core\\\\lib\\\\plumbing.js:46:31)\\n    at Request.self.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:185:22)\\n    at Request.emit (events.js:210:5)\\n    at Request.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:1154:10)\\n    at Request.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\build\\\\plugins\\\\azurePublish\\\\node_modules\\\\request\\\\request.js:1076:12)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
}
400 - "{\r\n  \"error\": {\r\n    \"code\": \"BadArgument\",\r\n    \"message\": \"The source completed without providing data to receive.\"\r\n  `}\r\n}"`

We figured this may be some sort of access issue to azure, but have tried from different access tokens (both generated in azure CLI and Azure Cloud Shell) and from both users (both have owner privileges) but this is an error we receive if we try to provision new resources, or use existing ones. 
We have managed to publish bots using regex with no issues, it seem to be any we do with LUIS any help to shed light on this matter would be greatly appreciated!

**Comment by luhan2017** [comment]
@philip-mc, this issue usually happens at this step: after we use the authoring key to create luis applications, we need to **bind the luis applications to a prediction resource** ， Could you please try this api directly in this web page, if you get the same error, that means there are some issues for the luis account. 
https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5be313cec181ae720aa2b26c/console

![image](https://user-images.githubusercontent.com/32191031/97147767-fc4e5700-17a4-11eb-80d8-0778ae30dd4b.png)

Please let me know the result, we can schedule a call for this if needed. Thanks :)

**Comment by philip-mc** [comment]
hello and thanks for getting back, it does appear we have an error!
![Capture](https://user-images.githubusercontent.com/73343537/97158244-12422480-1771-11eb-8728-e66cd2ceeb13.PNG)

This was the results from the publish generated app id and luis auth key

**Comment by philip-mc** [comment]
@luhan2017  Forgive me, it appears that was a lack of bearer in the authorisation box, the new error - 
![capture 2](https://user-images.githubusercontent.com/73343537/97166809-c184f880-177d-11eb-87cd-17dc95b6ebf9.PNG)
the same as in publisher

**Comment by luhan2017** [comment]
@philip-mc , This error usually happens when the arm token and authoring service is not under the same tenant. But you already confirmed that right?  Several similar issues have been reported recently, I will try to connect with luis team to understand if there are any authentication update in their side.

**Comment by philip-mc** [comment]
Thanks for the quick reply, here are a few screens of the current set up, the tenant and subscription match the token and they both match the Luis resource

Tenant:
![tennant](https://user-images.githubusercontent.com/73343537/97262232-5ccaac00-1818-11eb-9aff-125908ecfda1.PNG)

Subscription:
![subscription](https://user-images.githubusercontent.com/73343537/97262268-6c49f500-1818-11eb-84d7-2c37df40cdae.PNG)

Luis Authoring:
![luis1](https://user-images.githubusercontent.com/73343537/97262526-ec705a80-1818-11eb-9a2e-ea2ddefd6e6f.PNG)


Token Generation:
![access token](https://user-images.githubusercontent.com/73343537/97262331-84217900-1818-11eb-970b-83f2b8d506bc.PNG)

Again, thank you for help in this matter

**Comment by luhan2017** [comment]
@philip-mc , could you please submit a ICM ticket to luis team referring to this doc? https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request. It is the best way to get their attention and have them prioritized for this.
