### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by tekram** [microsoft/BotFramework-Composer#4396]
## Describe the bug

Using the provisioncomposer.js to deploy new resources I get the below error:

Login to Azure:
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FX4PU32FB to authenticate.
> Creating App Registration ...
> Create App Id Success! ID: d5533a00-475a-46e7-9104-84b3a87ca691
> Creating resource group ...
> Validating Azure deployment ...
> Deploying Azure services (this could take a while)...
| > Validating QnA deployment ...
[Error: ENOENT: no such file or directory, open 'C:\Users\TE\bots\VirtualAssistant\scripts\DeploymentTemplates\qna-template.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\TE\\bots\\VirtualAssistant\\scripts\\DeploymentTemplates\\qna-template.json'
}
## Version

1.1.1

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## Expected behavior

After it fails, it does not give me the JSON to populate the publishing component on the composer. It just gets stuck.

**Comment by tekram** [comment]
node provisionComposer.js --subscriptionId=xxx --name=lh-john --appPassword=xxx --tenantId=xxx --environment=dev --customArmTemplate=DeploymentTemplates/function-template-with-preexisting-rg.json

That is the command I used.

**Comment by ryanlengel** [comment]
@luhan2017 can you please take a look at this issue? Thank you!

**Comment by zidaneymar** [comment]
@tekram  Hi, could you please try copy this [qna template file](https://github.com/microsoft/BotFramework-Composer/blob/2b224daf513ad46c57c98403a23fcea4fd5436f3/extensions/samples/assets/shared/scripts/DeploymentTemplates/qna-template.json)to your target folder (C:\Users\TE\bots\VirtualAssistant\scripts\DeploymentTemplates\)?

**Comment by luhan2017** [comment]
@tekram did you tried to copy the qna-template.json as well? If your bot is created from an old version of composer, you should copy both provisionComposer.js and qna-template.json to your bot to make it work.  Or you can add a param  -createQnAResource false.

**Comment by CezaryMarcjan** [comment]
Assuming resolved. Please reactivate in case it's not the case.
