### ISSUE TITLE
Was this ever resolved? I am getting the same error now

### ISSUE THREAD

**Issue by tekram** [microsoft/BotFramework-Composer#4397]
Was this ever resolved? I am getting the same error now

_Originally posted by @tekram in https://github.com/microsoft/BotFramework-Composer/issue_comments/709604780_

**Comment by kdubious** [comment]
your link is dead.

**Comment by jwiley84** [comment]
@tekram Can you post the link to the actual issue, not to your comment on it? The link you provided routes to a 404 error page.

**Comment by tekram** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/3561#issuecomment-709606431

**Comment by tekram** [comment]
Also, in the meantime, it would be great to have manual ways to deploy the bot when the built in functionality seems to break. Just can not figure out how to manually deploy it.

**Comment by tekram** [comment]
@kdubious Any suggestions on alternative deployment strategies? You seem to be using the composer and quite active here. :)

**Comment by kdubious** [comment]
@tekram I had an issue where the AZ command to get a new token was actually pulling a token from another tenant. I had to have it forget all other tenants, and just use my subscription, then I got a good token and things started to work. Do you have Teams?

**Comment by kdubious** [comment]
@tekram 

![image](https://user-images.githubusercontent.com/9756166/96320017-26528d00-0fdf-11eb-9760-cb6800a93e6c.png)

LINE 2: comes from `az account get-access-token`. I had issues here being in the wrong subscription, even though I DID NOT SWITCH SUBSCRIPTIONS.

`<<NAME>>` and `<<ENV>>` can be found by looking at the App Service Plan in Azure.
![image](https://user-images.githubusercontent.com/9756166/96320384-3cad1880-0fe0-11eb-9edf-2ff97ab65298.png)

LUIS Values: In Azure `<<NAME>>-<<ENV>>-luis` and  `<<NAME>>-<<ENV>>-luis-Authoring` blades will get you the related key and endpoint.
![image](https://user-images.githubusercontent.com/9756166/96320476-7b42d300-0fe0-11eb-92ca-0d2cafa17954.png)

App ID & Password: In Azure go to Azure Active Directory > App Registrations > All Applications > <<NAME>>
On Overview you can get the ID
![image](https://user-images.githubusercontent.com/9756166/96320572-bcd37e00-0fe0-11eb-8314-da3ab424463d.png)

On Certificates and secrets you can create a new password, you can't look up the old one.
![image](https://user-images.githubusercontent.com/9756166/96320601-d70d5c00-0fe0-11eb-8c2f-780a10c9a91e.png)

**Comment by tekram** [comment]
Thanks @kdubious. 

I am not able to get success on the deployment! However, it looks like the actual bot on Azure is not updating. I get a success response in the publishing section of the bot. However, the actual bot is not updating. Any options to push bot to Azure outside fo the composer? Or have you ever run into this?

**Comment by tekram** [comment]
I also tried just deploying the echo bot that comes with composer. No luck but the console still says "Success" 

Publish starting...
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\getUserInfo.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\help.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\labs.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\medication.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\message.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\schedule.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\virtualassistant.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\virtualassistant.en-us.lu no changes\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\virtualassistant.en-us.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\virtualassistant.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\getUserInfo.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\help.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\labs.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\medication.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\message.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\schedule.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\virtualassistant.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\luis.settings.dev.westus.json\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "lubuild succeed"
}
{
  "status": "DEPLOY_INFO",
  "message": "start publish luis"
}
{
  "status": "DEPLOY_INFO",
  "message": "Assigning to luis app id: 9169dd57-8a7d-4f0d-9bec-2fedd677acf5"
}
{
  "status": "DEPLOY_INFO",
  "message": {
    "code": "Success",
    "message": "Operation Successful"
  }
}
{
  "status": "DEPLOY_INFO",
  "message": "Luis Publish Success! ..."
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\getUserInfo.en-us.qna loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\help.en-us.qna loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\labs.en-us.qna loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\medication.en-us.qna loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\message.en-us.qna loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\schedule.en-us.qna loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\interuption\\virtualassistant.en-us.qna loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\getUserInfo.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\help.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\labs.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\medication.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\message.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\schedule.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to C:\\Users\\TE\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4e22baa1759c48a914936665c523e927\\azurefunctions\\ComposerDialogs\\generated\\virtualassistant.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "qnabuild succeed"
}
{
  "status": "DEPLOY_INFO",
  "message": "Packing up the bot service ..."
}
{
  "status": "DEPLOY_INFO",
  "message": "Packing Service Success!"
}
{
  "status": "DEPLOY_INFO",
  "message": "Publishing to Azure ..."
}
{
  "status": "DEPLOY_INFO",
  "message": "Retrieve publishing details ..."
}
{
  "status": "DEPLOY_INFO",
  "message": ""
}
{
  "status": "DEPLOY_SUCCESS",
  "message": "Publish To Azure Success!"
}

**Comment by kdubious** [comment]
>> However, the actual bot is not updating.
What do you mean? How do you know it's not updating? How are you testing? Have you tried Composer to connect to Emulator to test the bot itself? Make sure things work as expected.... then test in Azure from Bot Channels Registration `<<Name>> > Test in Web Chat`
![image](https://user-images.githubusercontent.com/9756166/96322562-9a912e80-0fe7-11eb-995b-edd9c833fe85.png)

**Comment by kdubious** [comment]
I have not tried publishing without using the feature in Composer. Here's what's in my App Service after publishing:

![image](https://user-images.githubusercontent.com/9756166/96322620-d1674480-0fe7-11eb-948a-ba3112d2ee82.png)

You may be able to get FTP credentials and publish it up there.

**Comment by tekram** [comment]
Thanks.

Have you ever seen it such that after successful push that the bot doesn't
update?

**Comment by tekram** [comment]
It seems like you probably always had success in pushing bots if you got the success message. 

Thanks for your help!

**Comment by tekram** [comment]
> > > However, the actual bot is not updating.
> > > What do you mean? How do you know it's not updating? How are you testing? Have you tried Composer to connect to Emulator to test the bot itself? Make sure things work as expected.... then test in Azure from Bot Channels Registration `<<Name>> > Test in Web Chat`
> > > ![image](https://user-images.githubusercontent.com/9756166/96322562-9a912e80-0fe7-11eb-995b-edd9c833fe85.png)

Yes. When I connect to the bot locally in the Emulator, it works fine. When I use the built in functionality of testing it through Azure (Test in Web Chat). It does not work. I also tried it with the Echo bot and not luck. Let try updating the JSON object from scratch again.

**Comment by kdubious** [comment]
@tekram sometimes I feel like the web emulator does not send the welcome message. Does nothing about the bot work? (No reply ever) Does it work as though running an old version?

If you look at the files in Azure in the App Service, are they getting updated?

**Comment by EricDahlvang** [comment]
Have you tried exporting the runtime, and publishing that from visual studio (or some other 'external to composer' method)?  https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#export-runtime

**Comment by tekram** [comment]
I had previously been trying to deploy it to an Azure Function. I tried to do it from scratch and deploy to Azure Web Application. It started to work! Not sure what exactly what was going on previously. I will try to deploy it a Function to see if it it was something wrong on my end. I do recall though seeing something about not allowing bots to run on Functions anymore?
