### ISSUE TITLE
LUIS intent recognition does not work for child dialogs

### ISSUE THREAD

**Issue by knightmeister** [microsoft/BotFramework-Composer#4400]
## Describe the bug

I am using the terms as defined on [Composer Docs](https://docs.microsoft.com/en-us/composer/concept-dialog). My main dialog has an intent, called DeveloperMode. The only string associated with it is `Developer Mode`. This intent is correctly inferred when the user types in `developer mode`. The intent starts a child dialog called `Developer`. 

`BeginDialog` for `Developer` returns a message indicating that the user is in the developer dialog. There is an intent called `SampleApiConnection` with in the `Developer` child dialog. The only LUIS string attached is `connect to an api`. 

When I type `connect to an api` into Composer, after first typing `developer mode` to be in the `Developer` child dialog, I get the message for `BeginDialog` for the `Developer` child dialog. I would expect to see the message for the intent `SampleApiConnection`.

This is the JSON as shown in the Bot Framework emulator:

````
{
  "recognizerResult": {
    "alteredText": null,
    "entities": {},
    "intents": {
      "Developer": {
        "score": 0.282138944
      }
    },
    "text": "connect to an api"
  }
}
````

## Version

1.1.1

## OS

Windows

## To Reproduce

1. Create a child dialog called Developer
2. In the main dialog, add an intent called DeveloperMode, triggered by the phrase "developer mode"
3. In the DeveloperMode intent, add an action to start the child dialog Developer
4. Add a message in the BeginDialog event for the Developer child dialog
5. Add an intent to the Developer child dialog triggered by the phrase "connect to an api"
6. Add a message to the intent

Start the bot framework emulator and type developer mode followed by connect to an api. Observe that you get the message entered in step four twice.

## Expected behavior

After typing "connect to an api" you should get the message entered in step 6.

**Comment by kdubious** [comment]
@knightmeister I think I solved your issue.. and one of mine.
There's a property on your Developer Child Dialog called "Auto end dialog." Set that to false and retest.
![image](https://user-images.githubusercontent.com/9756166/96285025-63515c00-0fac-11eb-82a2-9b26e0fbd5c1.png)

**Comment by dmvtech** [comment]
@kdubious is correct; this is a simple way if you want to keep the user in this dialog until logic follows a flow to let them exit (like a global cancel, etc).

**Comment by knightmeister** [comment]
Thanks @kdubious , this is exactly what I was after.

Now I need to figure out how to get back to the initial/parent dialog. If I add a "End this dialog" block, it does not return back to the initial dialog. 

The above does not relate to the issue that I originally raised so please feel free to close this issue.

**Comment by kdubious** [comment]
@knightmeister, returning to the initial dialog worked for me:
![image](https://user-images.githubusercontent.com/9756166/96392333-bdf3df00-1189-11eb-89d6-23bf6af7601a.png)

![image](https://user-images.githubusercontent.com/9756166/96392351-c815dd80-1189-11eb-8405-7b704929bf6d.png)

![image](https://user-images.githubusercontent.com/9756166/96392378-de239e00-1189-11eb-8664-8839429a9ea3.png)

**Comment by knightmeister** [comment]
Thanks @kdubious. I had more or less the same flow, my problem was the intent recognizing developer mode didn't have a condition set so it was never not entering that intent (it was the only one). Now I have added the condition the unknown intent is firing as I would expect.

**Comment by kdubious** [comment]
@knightmeister sure thing, learning as I go here, too. Hoping to tackle the "human handoff" this week. I see that interests you, too?

**Comment by knightmeister** [comment]
> @knightmeister sure thing, learning as I go here, too. Hoping to tackle the "human handoff" this week. I see that interests you, too?

Indeed it does. I don't think we can support the design pattern Microsoft have documented (although hope I'm wrong), but I have an idea as to how we can do our own ad-hoc hand-off. Be interested to see how #4404 goes.

**Comment by kdubious** [comment]
@knightmeister shoot me an email if you want to collaborate on this a bit. I've picked up a little insight on this topic, but I'm not entirely sure the best / easiest / highest value path forward.

**Comment by knightmeister** [comment]
> @knightmeister shoot me an email if you want to collaborate on this a bit. I've picked up a little insight on this topic, but I'm not entirely sure the best / easiest / highest value path forward.

Will do
