### ISSUE TITLE
Duplicate File Found

### ISSUE THREAD

**Issue by tekram** [microsoft/BotFramework-Composer#4407]
## Describe the bug

Opening a bot created with previous stable version of Bot Composer. 

## Version

Latest nightly build 

## Browser

- [x ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create Bot in prior stable composer 1.1.1.
2. Update Composer to latest nightly build
3. Open prior bot 

![image](https://user-images.githubusercontent.com/79664/96284511-84a54e80-0f92-11eb-9252-fea2bbfe1146.png)

## Screenshots

See above

## Additional context

I only see one copy of the file.

**Comment by tdurnford** [comment]
We need to filter out JSON files from node_module directories.

**Comment by cwhitten** [comment]
Hello @tekram, this has been addressed in https://github.com/microsoft/BotFramework-Composer/pull/4444
