### ISSUE TITLE
Publishing Bot Gets Stuck

### ISSUE THREAD

**Issue by jpd21122012** [microsoft/BotFramework-Composer#4409]
## Describe the bug

I've already done my bot, I tried to publish it in the right section and filling the parameters with right keys, so then I clicked in Publish selected profile, and It doesn't give any error, just the loading icon, I've been waiting more than 4 hours and nothing happens, when I close and Open the Composer, The Log doesn't appear.

I'm filling the profile with an existing resource on Azure.

## Version

The version is the 1.1.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Open an existing Bot
2. Click on Publish, in the right menu
3. Fill the profile with an existing Azure resource
4. Click  on Publish to selected Profile
5. Error must appear

## Expected behavior

The error consists in the status, it doesn't change from "loading"

## Screenshots

![image](https://user-images.githubusercontent.com/25286017/96296595-22aa1080-0fb5-11eb-938a-0aa517d8745d.png)

**Comment by luhan2017** [comment]
@jpd21122012 , could you please share more information on this? For example, does your bot use luis/qna.
What exact field did you fill in the publish profile? I tried several scenarios from my side but I can't reproduce this yet.

**Comment by jpd21122012** [comment]
@luhan2017 , thanks for replying, today I was able to publish the bot, but just without luis services, if I add LUIS credentials and some dialogs it fails

**Comment by luhan2017** [comment]
@jpd21122012 , thanks for the reply. Could you double check if the luis settings are following the below instructions?
```
{
  "accessToken": "eyJ0eXAiOiJKV1QiL",  --------------> you need to make sure luis and other services belongs to the same tenant. 
  "name": "Luhan0603",
  "environment": "dev",
  "hostname": "Luhan0603-dev",
  "luisResource": "Luhan0603-dev-luis",  ---------------> this should be your luis prediction resource name. 
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "f43e1147"
    },
    "luis": {
      "endpointKey": "172773",    -------------------> this should be your luis prediction key
      "authoringKey": "516b51",  --------------------> this should be your luis authoring key
      "region": "westus"
    }
    "MicrosoftAppId": "d41",
    "MicrosoftAppPassword": "qwer"
  }
}
```
![image](https://user-images.githubusercontent.com/32191031/96672632-51e6c600-1397-11eb-96c6-ea25620343f5.png)

**Comment by jpd21122012** [comment]
@luhan2017 Thanks for the response, in fact the resource that I've created has no "environment", I'm gonna create the luis services as yours and I'll comment what happened, It was the same problem at publishing for first time on Web App, I had "SomethingOfBot", and then I create a new web app as "SomethingOfBot-xname" and the xname was giving the error because environment wasn't there.

**Comment by luhan2017** [comment]
@jpd21122012 Let me explain a little bit more about the naming logic.

for azure web app:
If hostname is set, composer will use hostname to identify the azure web app name, otherwise, composer will use "name-environment".
Similar, if luisResource is set, composer will use luisResource to identify the luis prediction resource, otherwise, composer will use "name-environment-luis".

If you are using existing services, you'd better set hostname and luisResource to identify the existing resources.

**Comment by jpd21122012** [comment]
@luhan2017 now it says this: 
The apps - Get applications list Operation under LUIS Programmatic APIs v3.0-preview is not supported with the current subscription key and pricing tier LUIS.S0.

I've changed the S0 for F0 and it's the same, I don't know what I'm doing wrong, please if you can help me with that

**Comment by luhan2017** [comment]
@jpd21122012 Could you double check your luis settings, did you set the correct authoringKey and endpointKey?  the authoringKey should be the key from a luis authoring service(API type: Language Understanding Authoring(LUIS)), and the endpointKey should be the key from a luis prediction service(API type: Language Understanding(LUIS)). See the following example: 

![image](https://user-images.githubusercontent.com/32191031/96827741-cd647800-1468-11eb-91f7-422c2b910286.png)

**Comment by jpd21122012** [comment]
@luhan2017 yes, I've set the correct Keys and endpoints

**Comment by feich-ms** [comment]
Hi @jpd21122012, this error usually comes from incorrect authoringKey. Could you please double confirm that the key is LUIS authoringKey instead of any other subscription key or prediction key. You can also find the authoring key in LUIS portal https://www.luis.ai/. Below is the screenshot showing where to get the authoringKey from luis portal. You can open any existing LUIS application or create a new one manually via portal to check the key. 

![image](https://user-images.githubusercontent.com/43032123/96968184-302a4200-1543-11eb-82f6-571eebbbefc9.png)

**Comment by jpd21122012** [comment]
@feich-ms I'm using that authoring key, in fact I don't have other LUIS Services in my Azure Account and other subscriptions, just one that I'm using as test for the bot.

**Comment by luhan2017** [comment]
@jpd21122012, Are you convenient to have a call with us(We are in Beijing GMT+8)? We can help debug more on this.

**Comment by jpd21122012** [comment]
Yes, I'm able to take a call

**Comment by luhan2017** [comment]
@jpd21122012 , what timezone are you in? and which time do you prefer, where should I send the invitation, slipknot_jpd@hotmail.com?

**Comment by jpd21122012** [comment]
> @jpd21122012 , what timezone are you in? and which time do you prefer, where should I send the invitation, [slipknot_jpd@hotmail.com](mailto:slipknot_jpd@hotmail.com)?

I'm in GMT -6, right now are 8:38 AM, so You must be 10:38 pm, ir You prefer se can have a call between 6 AM to 1 pm ir tour time.

**Comment by luhan2017** [comment]
@jpd21122012 As we synced last time, the token and authoringKey are all correct, but you can't get the correct response from this API. https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5be313cec181ae720aa2b26c/console

could you please submit an ICM ticket to luis team referring to this doc? https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request. It is the best way to get their attention and have them prioritized for this.

**Comment by luhan2017** [comment]
@jpd21122012 , any update from your side? does the issue still exist？

**Comment by jpd21122012** [comment]
The API is saying the same, the issue is still alive

**Comment by luhan2017** [comment]
@jpd21122012 , this should be luis issue, did you submit a ICM ticket to luis team? https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request.

**Comment by jpd21122012** [comment]
> @jpd21122012 , this should be luis issue, did you submit a ICM ticket to luis team? https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request.

I don't have the tech support in my subscription

**Comment by drfbwilliams** [comment]
Im also seeing this issue - I do not have a LUIS service and just trying to deploy an echo test bot to an existing service provision in Azure

To clarify the "hostname" property - should this just be the webapp name or the entire endpoint?

Many thanks

**Comment by luhan2017** [comment]
Yes, should be the webapp name, for example, it should be
  "hostname": "Luhan0603-dev",
  "luisResource": "Luhan0603-dev-luis"
![image](https://user-images.githubusercontent.com/32191031/98889445-ecd54a80-24d4-11eb-9572-69c42b3334ad.png)

**Comment by axelsrz** [comment]
Hello @jpd21122012, looks like this is a Luis issue, I would recommend submiting this through their tool at https://cognitive.uservoice.com/forums/551524-luis

**Comment by drfbwilliams** [comment]
Hi @axelsrz - I don't see anywhere stating that LUIS is a pre-requisite. I don't have a LUIS service, so I should be able to exclude this and still publish - therefore, this isn't a LUIS issue.

Thanks,

**Comment by jpd21122012** [comment]
@drfbwilliams you don't need to fill LUIS fields if you're not using it.

**Comment by drfbwilliams** [comment]
Correct - I believe this is related to this issue #4746 

I do not believe this has been fixed yet, so the issue should not be handed off and closed. I don't believe that it is LUIS specific as this occurs on non-LUIS solutions such as the one mentioned in the previous issue.

@zxyanliu - thoughts if these are connected?

**Comment by jpd21122012** [comment]
@drfbwilliams I had that problem, but it was my fault by Web App Name and HostName Keys of settings, please double check it. Issue [#4746 ](https://github.com/microsoft/BotFramework-Composer/issues/4746) shows when publishing bot the loading status never ends.

**Comment by drfbwilliams** [comment]
I can confirm I spend 4 days on it and it exists

As mentioned in that issue, @zxyanliu was also able to repro the issue on and existing deployment

"The error was reproduced when I tested publishing a bot to existing Azure resources (manually created)."

I can confirm that a newly provisioned bot with scripts that include LUIS and full stack does deploy correctly.

You can close this if you wish, I just think they are connected due to the same user experience.
I still cant create a new bot in composer and deploy to an existing Azure provision that wasnt created using the scripts (that also doesnt have LUIS).
