### ISSUE TITLE
Bot business logic in composer

### ISSUE THREAD

**Issue by guru98** [microsoft/BotFramework-Composer#4414]
## Is your feature request related to a problem? Please describe.

Composer is an amazin tool but, in my mind there is a big limitation: there is a clear way to add businss logic to the flow.
It's extremally easy to design the flow and i can call rest api or azure functions but still there are limitation if i need a specific piece of code that have to be execute inside the bot. I can use custon actions but are complex to add to the composer interface and, in my mind, are helpful when you write something that can be reused in different bots many and many times.
Using bot framework sdk and adaptive dialog we can use codeactions and inside codeactions we can call any function and methods. But this is not available in composer

## Describe the solution you'd like

Make possible to call external functionsfrom the composer at least in scenarious where we conbind declarative dialogs with code developed using bot framework sdk. We could use a sort of stub functions where we specificy the function we want to casll and the Activitity we pass to the options

**Comment by EricDahlvang** [comment]
HI @guru98 

This seems like a valid feature to consider.  I tried implementing something which might cover the description you've provided.

Custom CodeActions to call:
```cs
namespace Microsoft.BotFramework.Composer.CustomAction
{
    public static class CustomCodeActionMethods
    {
        public static async Task<DialogTurnResult> TestMethod(DialogContext dc, System.Object options)
        {
            await dc.Context.SendActivityAsync("Hi from CustomCodeActionMethod.TestMethod");

            //return new DialogTurnResult(DialogTurnStatus.Complete);
            return await dc.EndDialogAsync(options);
        }

        public static async Task<DialogTurnResult> TestMethod2(DialogContext dc, System.Object options)
        {
            await dc.Context.SendActivityAsync("Hi from CustomCodeActionMethod.TestMethod2");

            //return new DialogTurnResult(DialogTurnStatus.Complete);
            return await dc.EndDialogAsync(options);
        }
    }
}
```

**Custom Dialog** to load and call the CodeAction methods:
```cs
    /// <summary>
    /// Custom command which executes a method, sending it turncontext and expecting a reply of DialogTrnResult.
    /// </summary>
    public class CallCustomCodeAction : Dialog
    {
        [JsonConstructor]
        public CallCustomCodeAction([CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0)
            : base()
        {
            // enable instances of this command as debug break point
            this.RegisterSourceLocation(sourceFilePath, sourceLineNumber);
        }

        [JsonProperty("$kind")]
        public const string Kind = "CallCustomCodeAction";

        /// <summary>
        /// Gets or sets memory path to bind to for the name of the method to call.
        /// </summary>
        /// <value>
        /// Memory path to bind to for the method name to call.
        /// </value>
        [JsonProperty("methodName")]
        public StringExpression MethodName { get; set; }

        /// <summary>
        /// Gets or sets memory path to bind to for the name of the class type continaing method to call, including namespace.
        /// </summary>
        /// <value>
        /// Memory path to bind to for the method name to call.
        /// </value>
        [JsonProperty("classTypeName")]
        public StringExpression ClassTypeName { get; set; } = "Microsoft.BotFramework.Composer.CustomAction.CustomCodeActionMethods";

        public async override Task<DialogTurnResult> BeginDialogAsync(DialogContext dc, object options = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            // could potentially be improved, to provide an assembly path to load
            //var domainAssembly = Assembly.LoadFrom(pathToDomain);
            //Type type = Type.GetType(fullTypeNamespace);

            string methodName = MethodName.GetValue(dc.State);
            string classTypeName = ClassTypeName.GetValue(dc.State);

            // Using the current assembly for now
            Type customerType = Assembly.GetExecutingAssembly().GetType(classTypeName);
            MethodInfo staticMethodInfo = customerType.GetMethod(methodName);
            var methodTask = (Task)staticMethodInfo.Invoke(null, new object[] { dc, options });
            await methodTask.ConfigureAwait(false);
            var resultProperty = methodTask.GetType().GetProperty("Result");
            return resultProperty.GetValue(methodTask) as DialogTurnResult;
        }
    }
```

**Schema**:
```json
{
    "$schema": "https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/component/component.schema",
    "$role": "implements(Microsoft.IDialog)",
    "title": "Call Custom Code Action",
    "description": "This dialog will dynamically call the defined custom code action.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "methodName": {
            "$ref": "schema:#/definitions/stringExpression",
            "title": "Method Name",
            "description": "Method name of tthe code action to call."
        },
      "classTypeName": {
        "$ref": "schema:#/definitions/stringExpression",
        "title": "Class type name",
        "description": "Class which should be loaded in order to call the Method. Default: 'Microsoft.BotFramework.Composer.CustomAction.CustomCodeActionMethods'"
      },
    }
}
``` 

From Composer, custom code action 1:
![image](https://user-images.githubusercontent.com/11055362/96396982-5899f100-117d-11eb-91a1-4814c9df41ee.png)

Tested with the emulator:
![image](https://user-images.githubusercontent.com/11055362/96397131-ae6e9900-117d-11eb-9705-768cea84b252.png)

**Comment by guru98** [comment]
Interesting. Still we have to add all the custom code in CustomAction so everytime all the business logic must be added to the bot changing the hosting bot. Now could we expose directly a codeaction from the adaptive dialogs?
If you look here https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/CodeAction.cs you see that it call a system.Func and pass the parameters in the options parameter. With this approach we could have a generic action that call any code you expose in your bot solution. Let me know if it's clear what i mean

**Comment by cwhitten** [comment]
Hi @guru98 - we understand that the CodeAction is a component in the SDK and are working to bring this into Composer when we have the right design and set of best practices for the customer. We'll take this as a feature request for now. Thank you.

**Comment by guru98** [comment]
Fine. Have you any best practice to handle business logic in the meantime? Write a Custom Action for every business funct seems to complex.
Thanks

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: Chris Whitten<mailto:notifications@github.com>
Inviato: mercoledì 21 ottobre 2020 18:20
A: microsoft/BotFramework-Composer<mailto:BotFramework-Composer@noreply.github.com>
Cc: Ugo Castellani<mailto:ugoc@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Oggetto: Re: [microsoft/BotFramework-Composer] Bot business logic in composer (#4414)


Hi @guru98<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fguru98&data=04%7C01%7C%7C73743f80ab704871100208d875dd367c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637388940237025555%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Pl%2BOOIBUPaK%2Bxw38SVfEtlpf3Fn4AnFn8WhryNPj6a4%3D&reserved=0> - we understand that the CodeAction is a component in the SDK and are working to bring this into Composer when we have the right design and set of best practices for the customer. We'll take this as a feature request for now. Thank you.

**Comment by cwhitten** [comment]
@guru98 our recommendation is to use Custom Action to encapsulate your business logic. No roadmap at the moment to support CodeAction.
