### ISSUE TITLE
 Publish failed in main branch

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#4415]
## Describe the bug

![image](https://user-images.githubusercontent.com/39758135/96397159-7c038100-11fb-11eb-9cab-44a414580b95.png)

## Version
main branch

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'home page'
2. create a new bot
3. click the start bot

## Additional context
the #4399 changed the plugin folder location, but some plugins use the old folder path to find the target.

**Comment by EricDahlvang** [comment]
I downloaded the main branch, built and ran it.  Then, attempted to export the runtime and hit this:
![image](https://user-images.githubusercontent.com/11055362/96397707-ee824b80-117e-11eb-89cf-eae7014a770e.png)

But, i'm running composer from: 'C:\work\BotFramework-Composer\Composer'

It seems maybe the relative paths are off?  (could be related to this issue with publishing)

**Comment by lei9444** [comment]
> I downloaded the main branch, built and ran it. Then, attempted to export the runtime and hit this:
> ![image](https://user-images.githubusercontent.com/11055362/96397707-ee824b80-117e-11eb-89cf-eae7014a770e.png)
> 
> But, i'm running composer from: 'C:\work\BotFramework-Composer\Composer'
> 
> It seems maybe the relative paths are off? (could be related to this issue with publishing)

**Comment by lei9444** [comment]
> I downloaded the main branch, built and ran it. Then, attempted to export the runtime and hit this:
> ![image](https://user-images.githubusercontent.com/11055362/96397707-ee824b80-117e-11eb-89cf-eae7014a770e.png)
> 
> But, i'm running composer from: 'C:\work\BotFramework-Composer\Composer'
> 
> It seems maybe the relative paths are off? (could be related to this issue with publishing)

I think the runtime path should be C:\work\BotFramework-Composer\runtime. Maybe it is the same issue

**Comment by hibrenda** [comment]
![image](https://user-images.githubusercontent.com/43408889/96399829-e6b7bb00-1201-11eb-9ee0-cea2a098ae73.png)
