### ISSUE TITLE
Form editor 'Auto end dialog' dropdown has an empty option

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#4434]
## Describe the bug
![image](https://user-images.githubusercontent.com/8528761/96583197-eeb15100-130e-11eb-86ee-fff5cbbb2ec9.png)
The same promlem with other `y/n` fields.
![image](https://user-images.githubusercontent.com/8528761/96583274-0983c580-130f-11eb-871f-cac6b96b1114.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by tdurnford** [comment]
@LouisEugeneMSFT Can you chime in on this? I think it is by design.

**Comment by LouisEugeneMSFT** [comment]
This is by design. This is saying "no value". Below is a screenshot of the previous version of Composer:

![image](https://user-images.githubusercontent.com/66701106/96626169-f8fa2d80-12c3-11eb-8da8-5fd19b29a346.png)
