### ISSUE TITLE
Docker not building

### ISSUE THREAD

**Issue by cdonke** [microsoft/BotFramework-Composer#4435]
## Describe the bug
Using Docker to run Composer.
Several issues started happening after moving Extensions folder from Composer into root.

Most of them, during build process..

Wrong path:
![image](https://user-images.githubusercontent.com/4707327/96584844-2e4b4f00-12b5-11eb-997d-0bb474bd24a4.png)
![image](https://user-images.githubusercontent.com/4707327/96585907-9e0e0980-12b6-11eb-974b-4cf2bb7ac498.png)

Git is now required for some module, but it's not present on container.

Timeouts:
![image](https://user-images.githubusercontent.com/4707327/96585992-b716ba80-12b6-11eb-80ef-6498f2d9de24.png)

## Version

Latest merge - [00df46c](https://github.com/cdonke/BotFramework-Composer/commit/00df46ceaa6ef7abbd02c75fe677a190dba4ea7e)

## OS

- [ ] macOS
- [ ] Windows
- [ X ] Ubuntu

## To Reproduce

> cd ~/
> ~/BotFramework-Composer
> docker build -t bot-composer -f ./Composer/Dockerfile .

## Expected behavior

Container image is created.

**Comment by cdonke** [comment]
Already investigating.

**Comment by a-b-r-o-w-n** [comment]
Hi @cdonke. Sorry for the breaking change! I am working on a fix for this. Do you usually build the docker image from the root directory or were you trying that because the extensions directory was moved up?

In my investigation, I've found that we will need to send the entire repository as context to the docker build, along with copying the correct files during the build process. I think in order to facilitate this, moving the Dockerfile up to the root would make sense. Do you have any concerns about doing this?

**Comment by cdonke** [comment]
Hi @a-b-r-o-w-n ...

I'm building from the root...
Already made some changes for the dockerfile (making better use of docker cache, moving some things around to improve)...

Now, I'm stuck here:

![image](https://user-images.githubusercontent.com/4707327/96649757-181aae80-1308-11eb-8125-2bed4df27996.png)

Should I stop, or can I help you somehow?

tks,

**Comment by cdonke** [comment]
@a-b-r-o-w-n , Here is the repo I'm working on:

https://github.com/cdonke/BotFramework-Composer/tree/fix/dockerbuild

I took the opportunity to write a GitHub Action to build the containers to test it on PR as well...
It's there too..

**Comment by a-b-r-o-w-n** [comment]
I'd say continue with your work as well. It looks like you are more experienced with docker than our team is. I will continue working on it as well and tag you are a reviewer on a PR. At that point, feel free to make suggestions with the things you've done to improve the docker build. We can integrate it into the PR.
