### ISSUE TITLE
CreationFlow does not validate name passed in via URL params

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Composer#4441]
## Describe the bug

Navigating to the creation wizard with a url such as:

`http://localhost:3000/projects/create/<template>?name=somename`

will cause the `name` field to be prepopulated with `somename` from the URL params.

However, the filename validation does not run in this scenario until you start typing something, so this initial value never gets validated and can result in trying to create a duplicate bot project.

## Version

`main` as of 10/20/2020

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Dev Tools
2. enter into console: `location.href ="http://localhost:3000/projects/create/<template-name>?name=<duplicate-bot-name>"`
3. Observer no duplicate error

## Expected behavior

The initial value from the URL params should be validated when the field is populated.

## Screenshots

![image](https://user-images.githubusercontent.com/3452012/96630584-13cfa080-12ca-11eb-91f6-7a3b55b456e0.png)

**Comment by boydc2014** [comment]
@a-b-r-o-w-n can you take a look at this, see our useForm hook can do a pre-validation?

**Comment by a-b-r-o-w-n** [comment]
@boydc2014 I don't think I can look at this soon, so un-assigning myself.
