### ISSUE TITLE
Trying to update already published bot. Keep getting 400 - {"error":{"code":"BadArgument","message":"Failed to parse azure account information object object."}}

### ISSUE THREAD

**Issue by juanpmendoza** [microsoft/BotFramework-Composer#4443]
I had already published a working bot to Azure. However I had to update it and I am now trying to publish it again to the same resource group in which it already exists. As expected, my access token had expired, so I generated a new one, pasted it on the bot's profile (after clicking on "Edit") and tried to publish the bot again. 

I tried following this documentation: https://docs.microsoft.com/en-us/composer/how-to-publish-bot
I also tried using the JSON structure that appears on the "README" of the bot files, and tried just modifying the values of the previous JSON that I used when I first uploaded this file. But I keep getting the same error 400.

I made sure to use a valid access token on each attempt. 

Any help would be greatly appreciated.

## Version

I'm using the Composer v1.1.1

## Browser

- [X] Chrome

## OS

- [X] Windows

## To Reproduce

1. Published a working bot
2. Edited the bot
3. Tried to publish it again on its existing resource group with a new access token
4. Error shows up everytime I try to publish the bot

## Expected behavior
I expected the bot to be published normally, as it had worked before, with the new updates.

## Screenshots

![image](https://user-images.githubusercontent.com/49325120/96638777-4d160980-12e6-11eb-8af1-b23d7d1054ca.png)

**Comment by juanpmendoza** [comment]
This is the JSON that I followed from the Readmefile

![image](https://user-images.githubusercontent.com/49325120/96639938-0b865e00-12e8-11eb-8dc0-2da87ed2b548.png)

And this is the one that I used following the structure in the "Edit" of the profile:

![image](https://user-images.githubusercontent.com/49325120/96640113-530cea00-12e8-11eb-8f61-caf857167377.png)

**Comment by boydc2014** [comment]
It should be fixed in main per @lei9444 , @luhan2017 will help verify this

**Comment by luhan2017** [comment]
@juanpmendoza , I suspect the az cli subscription does not match with your subscription in publish profile, could you please double check? could you try to run this command "az account show", it will show your current subscription info and check whether the services you used in the publish profile belongs to this subscription.

**Comment by juanpmendoza** [comment]
@luhan2017 I checked and you're right! I should set the right one using "az account set" right? Which Json schema should I use to edit the bot? Thanks!

**Comment by juanpmendoza** [comment]
@luhan2017 I used az login and then the JSON from the Readme file and it worked! Thanks for the help!

**Comment by stevengum** [comment]
Awesome, thanks for reporting back that @luhan2017's solution worked. I'm closing this issue as it sounds like it has been resolved, if there are any questions related to this please reply here and @mention a team member or open a new issue.

**Comment by Afranzio** [comment]
@luhan2017 I tried with Json in the Readme file. But still, I'm facing the same error.
