### ISSUE TITLE
Unable to create QnA Maker KB with new bot creation flow

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#4447]
## Describe the bug

Unable to create QnA Maker knowledge base in new bot creation flow.

## Version

The [main](https://github.com/microsoft/BotFramework-Composer) branch as of October 20, 2020.

## Browser

- [x] Chrome

## OS

- [x] Windows

## To Reproduce

1. Go to Composer **Home** page and select **+ New**
2. Select **Create from knowledge base (QnA Maker)**, then select **Next**
3. Enter values for **Name**, **Description**, and **Location**, then select **Next**
4. Was unable to see the **Create new knowledge base** form

## Expected behavior

After step 3, users should be able to see the following QnA Maker KB creation form. Then users should be able to enter some values in the form and create their QnA Maker knowledge base. 

![image](https://user-images.githubusercontent.com/32497439/96657507-3e841e00-12f7-11eb-8a73-a229e28fb57c.png)

## Screenshots

![qna-not-working](https://user-images.githubusercontent.com/32497439/96657037-fc0e1180-12f5-11eb-998a-b7fad83a4d7f.gif)

**Comment by hibrenda** [comment]
I can repro the issue as well. and after the QnA bot creation failure, new bot can not be created as well.
![Uploading image.png…]()
