### ISSUE TITLE
Suggested refinement of the validation error messages

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#4448]
### 1. Error message in the **Knowledge base name** field.
* Spaces are not allowed. This should be mentioned in the error message.
* Letters, numbers, -, and _ are allowed. This should be mentioned in the error message.

  ![image](https://user-images.githubusercontent.com/32497439/96655656-e1866900-12f2-11eb-8a6b-dd4e325279ae.png)
   
 #### Suggested change

   Spaces and special characters are not allowed. Use letters, numbers, -, or _.

### 2. Error message in the **Knowledge source** field. 

   ![image](https://user-images.githubusercontent.com/32497439/96658683-04684b80-12fa-11eb-8692-57e9d2ca651e.png)

   ![image](https://user-images.githubusercontent.com/32497439/96658811-5d37e400-12fa-11eb-9224-a5a6039cfb05.png)

  #### Suggested change

   A valid URL should start with http:// or https://.
   A valid URL is required.

### 3. Watermark message in the **Knowledge source** field. 

   ![image](https://user-images.githubusercontent.com/32497439/96659469-dd127e00-12fb-11eb-9670-0441d62e4460.png)
    
  #### Suggested change (if "browse to upload a file" is not supported)
  Enter a valid URL

**Comment by zxyanliu** [comment]
@mareekuh I need your feedback on this so that I can proceed to update. 
cc: @hibrenda

**Comment by mareekuh** [comment]
1. Error message in the Knowledge base name field.
Watermark text : QnA-Maker_KB_1
Error text : A Knowledge base name cannot contain spaces or special characters. Use letters, numbers, -, or _.

2. Error message in the Knowledge source field.
Watermark text : Upload a .pdf file or type a URL starting with http:// or https://
or
Watermark text : Upload a .pdf file or type a URL
Error text : A knowledge base URL should start with http:// or https://.
