### ISSUE TITLE
Passing information from the client to Composer bot

### ISSUE THREAD

**Issue by knightmeister** [microsoft/BotFramework-Composer#4451]
I am trying to post a custom event via Direct Line to my Composer-based bot.

I found a [page for the Bot Framework SDK v3](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-backchannel?view=azure-bot-service-3.0) showing how to send a custom activity, however this page is not present in the v4 docs. 

This is my code, I'm utilising the Web Chat control:

````
 var dl = window.WebChat.createDirectLine({
        token: '[token]'
    });
    
    window.WebChat.renderWebChat(
        {
            directLine: dl,
            userID: 'YOUR_USER_ID',
            username: 'Web Chat User',
            locale: 'en-US',
            botAvatarInitials: 'WC',
            userAvatarInitials: 'WW'
        },
        document.getElementById('webchat')
    );

    window.setTimeout(function () {
        dl.postActivity({ type: "event", value: "hello", from: { id: "me" }, name: "PageLoaded" })
            .subscribe(id => console.log("success"));
    }, 5000);
````

I have a 5 second delay before posting the activity to make sure everything loads.

This works in as much as that when the activity is posted, I get my welcome text back from the bot, however the custom event is never fired on the Composer side.

I created the event in Composer by 

1. Adding a new Trigger
2. Selected Custom events and provided the name PageLoaded
3. Added "Send a response" to say "Got page loaded event"

I need to know how to be able to pull the value from the event, in this case the value "hello".

**Comment by stevengum** [comment]
@v-kydela can you investigate this and assist? Thanks!

**Comment by benbrown** [comment]
You should be able to access the value as `turn.activity.value`

**Comment by stevkan** [comment]
@benbrown, does this need to be coupled with the `OnEventActivity` handler or is it enough to simply detect by `turn.activity.value` or turn.activity.name` (or similar)?

**Comment by benbrown** [comment]
Yes, the event should trigger the OnEventActivity handler, and then you can further inspect the event.

**Comment by cleemullins** [comment]
Closing per @benbrown answer.

**Comment by knightmeister** [comment]
@cleemullins @benbrown the principal issue is that the event does not fire - please read my original post. As I see it, you guys have shown me how to access the variable, but not confirmed I am calling the event correctly, or confirmed that the event is correctly defined in Composer.

**Comment by benjaminsommerfeld** [comment]
@knightmeister Maybe this can help you, we are sending an activity event from Webchat to Composer like this:


const token = 'TuycRUr0E-M.HyVBYkL03Dp4AKn3-ZI9YfFRLcGv5HEo5PnaD6n-eU0';
            const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
                if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
                    dispatch({
                        type: 'WEB_CHAT/SEND_EVENT',
                        payload: {
                            name: 'loginevent',
                            value: { prename: 'Stefan', surname:'Lauf' }
                        }
                    });
                }

                return next(action);
            });

window.WebChat.renderWebChat(
                {
                    directLine: window.WebChat.createDirectLine({ token }),
                    store
                },
                document.getElementById('webchat')
            );




---> when loading this webchat html page, it directly sends the  "loginevent" in store.

The composer then receives it with an "Activity Event" trigger

![Screenshot 2020-10-26 at 12 23 44](https://user-images.githubusercontent.com/8789284/97166791-19276200-1786-11eb-9cec-16775efd1a81.png)

![Screenshot 2020-10-26 at 12 24 36](https://user-images.githubusercontent.com/8789284/97166869-378d5d80-1786-11eb-821e-4db680a659d4.png)


This way it works for us. Hope this can help you.

**Comment by knightmeister** [comment]
> @knightmeister Maybe this can help you, we are sending an activity event from Webchat to Composer like this:
> 
> ```
>         const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
>             if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
>                 dispatch({
>                     type: 'WEB_CHAT/SEND_EVENT',
>                     payload: {
>                         name: 'loginevent',
>                         value: { prename: 'Stefan', surname:'Lauf' }
>                     }
>                 });
>             }
> 
>             return next(action);
>         });
> ```
> 
> window.WebChat.renderWebChat(
> {
> directLine: window.WebChat.createDirectLine({ token }),
> store
> },
> document.getElementById('webchat')
> );
> 
> ---> when loading this webchat html page, it directly sends the "loginevent" in store.
> 
> The webchat code is inspired by this sample:
> https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/a.welcome-event
> 
> The composer then receives it with an "Activity Event" trigger
> 
> ![Screenshot 2020-10-26 at 12 23 44](https://user-images.githubusercontent.com/8789284/97166791-19276200-1786-11eb-9cec-16775efd1a81.png)
> 
> ![Screenshot 2020-10-26 at 12 24 36](https://user-images.githubusercontent.com/8789284/97166869-378d5d80-1786-11eb-821e-4db680a659d4.png)
> 
> This way it works for us. Hope this can help you.

Many thanks @benjaminsommerfeld, this allowed me to determine where I was wrong. My JavaScript works, but the issue was I was using a dialog event, rather than an activity event.

**Comment by VyasK17** [comment]
> @knightmeister Maybe this can help you, we are sending an activity event from Webchat to Composer like this:
> 
> ```
>         const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
>             if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
>                 dispatch({
>                     type: 'WEB_CHAT/SEND_EVENT',
>                     payload: {
>                         name: 'loginevent',
>                         value: { prename: 'Stefan', surname:'Lauf' }
>                     }
>                 });
>             }
> 
>             return next(action);
>         });
> ```
> 
> window.WebChat.renderWebChat( { directLine: window.WebChat.createDirectLine({ token }), store }, document.getElementById('webchat') );
> 
> ---> when loading this webchat html page, it directly sends the "loginevent" in store.
> 
> The webchat code is inspired by this sample: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/04.api/a.welcome-event
> 
> The composer then receives it with an "Activity Event" trigger
> 
> ![Screenshot 2020-10-26 at 12 23 44](https://user-images.githubusercontent.com/8789284/97166791-19276200-1786-11eb-9cec-16775efd1a81.png)
> 
> ![Screenshot 2020-10-26 at 12 24 36](https://user-images.githubusercontent.com/8789284/97166869-378d5d80-1786-11eb-821e-4db680a659d4.png)
> 
> This way it works for us. Hope this can help you.

Many thanks from this reference i implemented trigger event when click on button in webchat.

**Comment by knightmeister** [comment]
> > @knightmeister Maybe this can help you, we are sending an activity event from Webchat to Composer like this:

Appreciate the comment, but I haven't looked at Bot Framework for at least a few years now, and I don't have an environment set up to test. Hope it helps someone else though!
