### ISSUE TITLE
[v1.1.1] - Error Start Bot in Composer with Luis

### ISSUE THREAD

**Issue by SantiagoMadeira** [microsoft/BotFramework-Composer#4458]
When using Composer v1.1.1 in Win10 and using Luis in ToDoBotWithLuisSample always having this error:

_Sorry, something went wrong with publishing. Try again or exit out of this task.
request to https://westus.api.cognitive.microsoft.com/luis/authoring/v3.0-preview/apps/***/versions/0.3/ failed, 
reason: connect ETIMEDOUT 40.112.254.71:443_

My  authoring resource is in westus.

Using the same sample with the same LUIS Authoring key, but in mac OS, everything runs ok!

System: Win10
Composer: v1.1.1
Donet: 3.1.402

-----

**update:** making the sample:

**Composer > new > using template > QnAMakerLUISSample**

with the same authoringKey everything runs ok!

can't understand...

**Comment by luhan2017** [comment]
@SantiagoMadeira , there might be something wrong with your previous deployment and the version 0.3 of your luis application is actually broken. Could you check in your luis portal as the following, try to delete version 0.3 or even delete the luis app itself and try again?

![image](https://user-images.githubusercontent.com/32191031/96822558-eff09400-145c-11eb-92ef-afffd536ecbb.png)

**Comment by SantiagoMadeira** [comment]
@luhan2017 thanks for your response.

one thing i noticed was that whenever i do **Start Bot** on the composer, it creates a new version of each app in Luis.ai even without any changes in LUIS phrases of Composer. Went to see the status of Apps on Luis.ai and some of the new versions that are created (each time i run Start Bot) are not in the Active & Production state only in the Active state.

What makes me confused is that my co-worker is working on a MacOS, and when we change the authorization keys, my Luis apps work well in Composer on MacOS, but this error occurs in my composer in Win10. If I use his keys in Composer Win10 I have the same error :(

I even tried to compile the composer on Win10 and use the Composer web application, but the error remains.

With the example of LuisAndQnA, everything works fine in Win10. Will the fact that the TodoWithLuis example generates 4 apps on Luis.ai and the LuisAndQnA example generates only 1 app, will influence this error?

**Note:** Also tried to use the microsoft virtual machine for Edge on virtual-box, installed the necessary software for Composer and had the same error :(

**Comment by luhan2017** [comment]
@SantiagoMadeira thanks for the reply, we will investigate more based on the information you provided. 

For multiple luis apps, we just create one luis app for each dialog. 

- in TodoWithLuis sample, we have 5 dialogs which enable luis.
- in LuisAndQnA sample, we just have 1 dialog which enables luis. 

If you want to have fewer luis apps created within a bot, just reduce your dialog count :)

**Comment by gbelenky** [comment]
I have the same issue - on both browser based and desktop version of the Composer when running on Win10. It seems that bad request is coming from http://localhost:5000 and not from LUIS. I tested the LUIS POST request in Postman and it worked fine. It seems that localhost:5000 (Composer backend process) has a bug when waiting for LUIS response and returns Bad Request. It happens not only on **"/train"** LUIS request but also **"versions/import?versionId=0.7"**
 
I add additional fiddler traces here (desktop app)
**_REQUEST:_**

POST http://localhost:5000/api/projects/79345.4352583862/build HTTP/1.1
Host: localhost:5000
Connection: keep-alive
Content-Length: 923
Accept: application/json, text/plain, */*
Origin: http://localhost:5000
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) @bfc/electron-server/1.1.1 Chrome/80.0.3987.165 Electron/8.2.4 Safari/537.36
Content-Type: application/json;charset=UTF-8
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: http://localhost:5000/bot/79345.4352583862/dialogs/collabbot64
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
Cookie: connect.sid=xxxxxx%3AQEOIU3PLMv3XT7Tgv9_.%2BmEpLyZLNsxxxxcSKYILNggsklDWqqGn27ShaxAFWXI

{"luisConfig":{"name":"CollabBot64","authoringKey":"MYKEYHERE","endpointKey":"","authoringRegion":"westus","defaultLanguage":"en-us","environment":"composer","endpoint":"","authoringEndpoint":""},"qnaConfig":{"subscriptionKey":"","qnaRegion":"westus","endpointKey":""},"projectId":"79345.4352583862","crossTrainConfig":{"rootIds":["collabbot64.en-us.lu"],"triggerRules":{"collabbot64.en-us.lu":{"Add":"additem.en-us.lu","Delete":"deleteitem.en-us.lu","View":"viewitem.en-us.lu","UserProfile":"userprofile.en-us.lu","whatCanYouDo":"","cancel":""},"userprofile.en-us.lu":{"Cancel":"","Why":"","NoValue":""}},"intentName":"_Interruption","verbose":true},"luFiles":["additem.en-us","deleteitem.en-us","userprofile.en-us","viewitem.en-us","collabbot64.en-us"],"qnaFiles":["additem.en-us","deleteitem.en-us","help.en-us","userprofile.en-us","viewitem.en-us","collabbot64.en-us","collabbot64.lu.qna.en-us"]}
 
_**RESPONSE:**_

HTTP/1.1 400 Bad Request
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Content-Type: application/json; charset=utf-8
Content-Length: 208
ETag: W/"d0-5XDfGKfQzLxxxxxlBN2Ybn9WDKY"
Vary: Accept-Encoding
Date: Fri, 30 Oct 2020 21:13:04 GMT
Connection: keep-alive

{"message":"request to **https://westus.api.cognitive.microsoft.com/luis/authoring/v3.0-preview/apps/xxxx7797-xxxxc-405d-be3f-52ba70fd0a4c/versions/0.2/train** failed, reason: connect ETIMEDOUT 40.112.254.71:443"}

**Comment by feich-ms** [comment]
Here is the dev for the luis publishing module, I'm trying to reproduce and figure out the cause, will keep you posted when there are any foundings. Thank you.

**Comment by feich-ms** [comment]
Hi @SantiagoMadeira @gbelenky, I was not able to reproduce this error in my windows 10 os with 1.1.1 Composer. Is this issue reproduced stablely or occasionally? Per my observation, this is maybe caused by the network delay or some other network issue of window os. If this is stabely reproduced, I will sync with the luis team to have it investigated.

**Comment by gbelenky** [comment]
Hi @feich-ms! This stably reproduced on my Win 10 machine when publishing "To Do With LUIS" sample . I can also stably reproduce it when connecting my machine to a different network bypassing home wifi router - in my case it was mobile internet. Composer works fine with my Mac. Is there a way to get Composer logs?
**Update:**
If I use a different LUIS bot with a smaller number of dialogs, it works fine.

**Comment by feich-ms** [comment]
@gbelenky thanks for the investigation. Your findings help a lot. As you may know luis service allows [5 transactions per second](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/language-understanding-intelligent-services/), so to make full use of such capability, composer is calling luis api with a concurrency rate of 5, this is implemented [here](https://github.com/microsoft/botframework-cli/blob/main/packages/lu/src/parser/lubuild/builder.ts#L223) in @microsoft/bf-lu package which is consumed by composer. We guaranteed not hitting the rate limit exception of luis api by waiting a time bucket after the last returned call of the concurrent 5 calls. This may be the confused executing behaviour you observed, but I'm not sure why timeout exception thrown among these calls.

**Comment by feich-ms** [comment]
@gbelenky can I know which region are you specifying when doing publishing? Can you share the appsetting you are using when publishing. You can remove any sensitive keys and ids. We can have a debug session, but before that I hope I can reproduce it in some way.

Below screenshot is what appsettings look like
![image](https://user-images.githubusercontent.com/43032123/97968083-233a0800-1df9-11eb-9487-fd4cb4b951c9.png)

**Comment by gbelenky** [comment]
@feich-ms This time I selected a much simpler sample https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis.
But even here I get random errors to the one above when I Restart Bot and publish my model to LUIS. But even when I am sometimes lucky and there are no errors, composer seems to forget to train the model and also to publish it into the production slot. Here is an example - I restarted the bot I am wondering why the "weather" trigger not getting fired. Emulator says: 
![emulator-luis-not-trained](https://user-images.githubusercontent.com/26817885/97980015-6cc22d00-1dd0-11eb-9484-50d77645a741.jpg)

I go to the LUIS portal, train and publish the model and this is what I get without restarting the bot:
![emulator-luis-trained and published](https://user-images.githubusercontent.com/26817885/97980034-72b80e00-1dd0-11eb-8b5a-4fb9fe402a1e.jpg)

**Comment by gbelenky** [comment]
@feich-ms - the same error happens in both regions where I have my authoring keys - westus and also westeurope

**Comment by feich-ms** [comment]
Synced with @gbelenky offline, he can make it with his Mac or VM but failed with his window device. I'm not able to reproduce it with my window device(both work station and laptop) and other windows devices from colleagues. I also tried a VM in azure that located in west europe, still no reproducing. It seems this issue only happened on specific devices. If we have a chance to reproduce it with some machines, we can dig into it to figure out the cause. The only workaround solution I can think of is to use cli tool to process language models. In composer next official release, it will provide users the capability of processing language models outside composer. In this way, users can process models with cli tool and overcome the issue by publishing models more times and with less concurrency.

**Comment by SantiagoMadeira** [comment]
hi,

I think I found a common factor between this issue and another one I reported #4584

Was using PT-BR as the defaultLanguage in Composer settings, and whenever I use that configuration I have these errors. When changing to defaultLanguage = 'en-us' everything works fine!

The final test I did was: 

1. configure Composer with only defaultLanguage = 'en-us', both issues work well. 
2. added PT-BR in Composer, rebuild bot in Composer. After that in LUIS a new APP was created for PT-BR.  
3. Without changing defaultLanguage in Composer it continued to work correctly.
4. In Composer remove language 'en-us' and set PT-BR as default, rebuild,  both issues work well (in this point have two Apps in Luis)
5. In LUIS I removed APP for language 'en-us' (well, at this point i'm not using that language in Composer) and just stayed with APP for PT-BR, and without rebuilding Composer and without Deploy for Azure... KABOOM! The error reappeared. 
6. I added APP for language 'en-us' in LUIS, everything worked fine again.

I think there is a problem when defining a default language other than 'en-us'

Now i'm working only with defaultLanguage='en-us' in Composer and everithing runs smooth

**Comment by feich-ms** [comment]
Hi @SantiagoMadeira, what is the exact error message in your above steps? Is it related with the error `reason: connect ETIMEDOUT 40.112.254.71:443` this issue is tracking?

Besides, I followed your steps above to try composer, but didn't hit any exceptions when publishing and testing with emulator.

For the luis api call timeout issue, I think we will include luis team for further investigation.

**Comment by SantiagoMadeira** [comment]
Hi @feich-ms,

most of the time the error is **404 (Not Found)**
also happens but less frequently **401 (PermissionDenied)** and **403 (Forbidden)**

**Comment by feich-ms** [comment]
@SantiagoMadeira, so they are different exceptions I think. For this ticket, it's reporting error `reason: connect ETIMEDOUT 40.112.254.71:443` and for your issues of above steps, could you please open another ticket to track? And we can provide supports for that case there.

**Comment by johnataylor** [comment]
please go ahead and open a new issue to track https://github.com/microsoft/BotFramework-Composer/issues/4458#issuecomment-723160504

**Comment by gbelenky** [comment]
@feich-ms -  it seems to be an issue with my home WIFI router firmware + my PC. I have the same issue when publishing Azure Functions on the same WIFI. I used a different WIFI network and could not reproduce the issue. Around one month ago I  had a firmware update of my WIFI router - that probably causes the issue with my PC. My Mac has no problems though.

**Comment by gbelenky** [comment]
@feich-ms - might be related, but the web version works fine (except of the publishing issue above)

**Comment by gbelenky** [comment]
@feich-ms - not related - I double checked with my mobile internet

**Comment by feich-ms** [comment]
@gbelenky thank you. Then that's totally another issue.

**Comment by Khanh-Ngy** [comment]
@gbelenky, @feich-ms 
I got a problem related to the company network.
When I used public network, it worked fine.
How can I config the proxy for Bot Framework Composer ?
![image](https://user-images.githubusercontent.com/71876037/103616179-844b9c80-4f5e-11eb-949d-24253bb385e0.png)

**Comment by luhan2017** [comment]
@Khanh-Ngy we don't support proxy officially, but we do have a prototype which enables proxy for luis/qna and azure publish. Do you want to try our private version? it is based on composer v1.2.2.

**Comment by Khanh-Ngy** [comment]
> @Khanh-Ngy we don't support proxy officially, but we do have a prototype which enables proxy for luis/qna and azure publish. Do you want to try our private version? it is based on composer v1.2.2.

Can you send me a link for researching ?
