### ISSUE TITLE
How to simulate Typing in Bot Framework Composer befor every bot message?

### ISSUE THREAD

**Issue by MarcoWirtl** [microsoft/BotFramework-Composer#4471]
how to get the typing activitie from the bot before he sends a message?
I would like that the bot is typing a few seconds before he is sending an response to get more "humanity" in it.

I tried: 
![image](https://user-images.githubusercontent.com/58036042/96842236-127ab100-144d-11eb-9c69-1f772a6813d2.png)

It doesnt work.

Also read something about the bools in the app settings, there look like this now:

![image](https://user-images.githubusercontent.com/58036042/96842304-2aeacb80-144d-11eb-89b0-dfa7e9e31f7a.png)

How to get it to work?

**Comment by benbrown** [comment]
@MarcoWirtl  What channel are you deploying your bot into?  Web chat? Teams? 

The appropriate way to do this is to use the ShowTypingMiddleware, which should be enabled if you set that boolean to true. This is built into the default C# runtime.

**Comment by MarcoWirtl** [comment]
@benbrown im Not that far now. Just tested in the Emulator. Does it not appear there?
So its enough just to set the boolean? So i habe Not to add the „typing“ and the „Delay“ response?

**Comment by benbrown** [comment]
Correct, you just have to use the boolean.
It does not appear that the typing indicators show up in Emulator, however you can see them being sent in the network activity.  These should work in the web chat and other channels where supported.

![Uploading Screen Shot 2020-10-22 at 11.53.56 AM.png…]()

**Comment by dmvtech** [comment]
To be able to trigger the typing so you actually _witness it_, you need to simulate something that will take long enough to have the typing indicator displayed. [The default](https://github.com/microsoft/botbuilder-dotnet/blob/17de9c1b05ec38d405422d4ed02ca5c0cdacdad3/libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs#L31) is longer than 500ms. 1-2 seconds should be enough.

This could be done with either using the `Send an HTTP request` activity and call some endpoint that takes a while, or you can [create your own custom activity](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action).

**Comment by dmvtech** [comment]
Alternatively, you could always [modify the runtime](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#export-runtime) and sleep the thread where you wish.

**Comment by owenpww** [comment]
Hello @dmvtech, I tried to modify the runtime but it seems to make the bot crash when deployed on Azure. It works fine locally but crashes when deployed. Could you help with this?
