### ISSUE TITLE
Composer skill scope is not retained

### ISSUE THREAD

**Issue by UmaPrelude** [microsoft/BotFramework-Composer#4495]
Hi All,
We have a problem in using the skill from composer bot.
When we connect to a skill, the scope is not inside the skill dialog, it comes to main bot each time and goes to different intents based on the utterances we provide instead of continuing the skill flow.
I am not sure how to fix the problem.
If we get some support it will help.
For your information we are trying with the calendar skill provided by microsoft.
The below is the activity settings we are using. 
![image](https://user-images.githubusercontent.com/65938026/96987391-906bb480-1540-11eb-8faf-bf818d464825.png)

**Comment by stevengum** [comment]
@dmvtech can you investigate this?

**Comment by cwhitten** [comment]
@UmaPrelude, do you have the `autoEndDialog` property set to `true` in the Skill bot?

Also, is your Skill also operating as a normal bot as well?

**Comment by dmvtech** [comment]
Aside from what Chris has suggested checking, you can share your .dialog (sanitized of any personal/sensitive info).

**Comment by UmaPrelude** [comment]
> @UmaPrelude, do you have the `autoEndDialog` property set to `true` in the Skill bot?
> 
> Also, is your Skill also operating as a normal bot as well?

Hi Chris, 

As mentioned earlier, I am using the calendar skill which is part of virtual assistant.
https://microsoft.github.io/botframework-solutions/skills/samples/calendar/
It is not developed in composer so i am not sure if we have a property of "autoEndDialog" in Bot framework.
As a individual bot it continues the flow, but when i call from composer bot, i face the mentioned problem.

**Comment by UmaPrelude** [comment]
> Aside from what Chris has suggested checking, you can share your .dialog (sanitized of any personal/sensitive info).
I believe you are asking for the dialog which calls the skill, below is the same.
{
  "$kind": "Microsoft.AdaptiveDialog",
  "$designer": {
    "id": "",
    "name": "CalendarSkillDialog"
  },
  "autoEndDialog": false,
  "defaultResultProperty": "dialog.result",
  "triggers": [
    {
      "$kind": "Microsoft.OnBeginDialog",
      "$designer": {
        "name": "BeginDialog",
        "id": ""
      },
      "actions": [
        {
          "$kind": "Microsoft.BeginSkill",
          "$designer": {
            "id": ""
          },
          "activityProcessed": true,
          "botId": "=settings.MicrosoftAppId",
          "skillHostEndpoint": "=settings.skillHostEndpoint",
          "connectionName": "AnthemBot",
          "id": "https://localhost:3979/manifest/manifest-1.1.json",
          "resultProperty": "dialog.result",
          "activity": "${BeginSkill_Activity_0JPj()}",
          "skillEndpoint": "https://localhost:3979/api/messages",
          "skillAppId": ""
        },
        {
          "$kind": "Microsoft.EndTurn",
          "$designer": {
            "id": ""
          }
        }
      ]
    }
  ],
  "generator": "CalendarSkillDialog.lg",
  "id": "CalendarSkillDialog"
}

**Comment by UmaPrelude** [comment]
I believe in below thread, the same thing is discussed, but i am not sure, how to get the updates of this fix.
I mean the url to download the fix or the updates

https://github.com/microsoft/BotFramework-Composer/issues/3848

**Comment by UmaPrelude** [comment]
Any support will help me to proceed further. Please suggest.

**Comment by dmvtech** [comment]
@UmaPrelude In your `Connect to a Skill` action, do you have `Allow Interruptions` set to false?

![image](https://user-images.githubusercontent.com/43397658/97766839-8b28df80-1ad5-11eb-9808-e530a4cca0c2.png)

**Comment by UmaPrelude** [comment]
I am using a old version of the composer, can i get a package/patch on this update. As i don't see this property.

**Comment by dmvtech** [comment]
1.1.1. is the newest release. If you are building Composer yourself from source, you might want to just try [the download](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.1.1) for the appropriate OS you are using. Just to make sure it works. Then (_if needed_), you can build a 1.1.1. version.

**Comment by UmaPrelude** [comment]
Thanks for the responses, it is working as expected.

**Comment by UmaPrelude** [comment]
Hi, 
When i try to open a project which is developed in previous version of composer in the composer 1.1.1. It still not showing the "allow interuption" property. Please help me to fix this.

**Comment by cwhitten** [comment]
@UmaPrelude if you create a new BeginSkill action, do you see the allowInterruptions property?

**Comment by UmaPrelude** [comment]
> @UmaPrelude if you create a new BeginSkill action, do you see the allowInterruptions property?

No Chris, I don't see even then.

**Comment by dmvtech** [comment]
@UmaPrelude I assume you made sure to scroll down far enough. If you create a brand new bot in Composer, and add Connect to a Skill action, do you see it then?

**Comment by UmaPrelude** [comment]
> @UmaPrelude I assume you made sure to scroll down far enough. If you create a brand new bot in Composer, and add Connect to a Skill action, do you see it then?

Yes, i scrolled till end, but i couldn't see in the old project. But is showing in new project.

**Comment by dmvtech** [comment]
Hi @UmaPrelude I assume you have exported the runtime. You will need to update the runtime to one of the newer packages (4.11 was released yesterday), update the schema. Optionally if you don't need the exported/custom runtime, you can remove that or create a new bot and use your existing declarative files (.dialog, .lg, etc) or portions of them.

**Comment by UmaPrelude** [comment]
> Hi @UmaPrelude I assume you have exported the runtime. You will need to update the runtime to one of the newer packages (4.11 was released yesterday), update the schema. Optionally if you don't need the exported/custom runtime, you can remove that or create a new bot and use your existing declarative files (.dialog, .lg, etc) or portions of them.

Yes it worked. After updating  the schema, i am able to see the property.
Thanks Dana.
