### ISSUE TITLE
0 based array transformed to 1 based array

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4503]
![image](https://user-images.githubusercontent.com/49873947/97042198-f2441280-1570-11eb-8884-61cfb613af83.png)

Click away and back again and voila the 0 is gone;

![image](https://user-images.githubusercontent.com/49873947/97042251-06880f80-1571-11eb-93b8-e20d49ad7d16.png)

**Comment by luhan2017** [comment]
@cxbuilders I can't reproduce this in Electron 1.1.1, which version did you use?

**Comment by cxbuilders** [comment]
nope, neither can I when updating to latest version, sorry for that, closing...
