### ISSUE TITLE
Remove dialog is broken

### ISSUE THREAD

**Issue by hatpick** [microsoft/BotFramework-Composer#4511]
## Describe the bug

Deleting a dialog crashes the app.

## Version

Latest on main.

## Browser

All browsers.

## OS

All platforms.

## To Reproduce

1. Open a bot project that has a dialog or create a new one.
2. Navigate to design page and delete a dialog.
3. Observe the crash.

## Expected behavior

Dialog to be deleted.

## Screenshots
![delete dialog error](https://user-images.githubusercontent.com/1483492/97055418-a165f700-153b-11eb-9f27-e247180badfa.PNG)

**Comment by boydc2014** [comment]
Thanks @hatpick , @liweitian is looking at this.
