### ISSUE TITLE
Publish bot manually

### ISSUE THREAD

**Issue by nitroin** [microsoft/BotFramework-Composer#4528]
Since many issues with the publication are present within Composer.

Is there any way to publish it manually? With CLI or manual steps?

Thank you!

**Comment by anusharavindrar** [comment]
@nitroin, what issues are you facing when you are trying to publish through Composer? As of now, the documentation to be followed for publishing a bot through Composer is https://docs.microsoft.com/en-us/composer/how-to-publish-bot.

**Comment by nitroin** [comment]
We're finding the publishing task not realiable. See [#4527](https://github.com/microsoft/BotFramework-Composer/issues/4527) for example.

Today, to accomplish a deploy we were requested to delete all the resources within the resource group, and thus downtime.
Also, providing a "manual" way to deploy opens to various possibilities, for example automatic CI/CD.

**Comment by cwhitten** [comment]
@zxyanliu can we take a docs item to demonstrate how to publish the runtime + assets outside of Composer as well? This is the same efforts needed for the CI/CD documentation.

@nitroin we will work on this in an upcoming release.

**Comment by zxyanliu** [comment]
@cwhitten Sure. I added the runtime + assets topic to [R11](https://github.com/MicrosoftDocs/composer-docs/projects/1) doc work item.

**Comment by zxyanliu** [comment]
Related to: https://github.com/microsoft/BotFramework-Composer/pull/4522

**Comment by zxyanliu** [comment]
FYI. @luhan2017 and @yeze322 are working on some scripts to make this process easier.

**Comment by nitroin** [comment]
That's great! Thank you!

**Comment by johnataylor** [comment]
@zxyanliu any update on this?

**Comment by zxyanliu** [comment]
@johnataylor Thanks for asking. This topic is WIP. 
I am asking @cwhitten for more direction on this doc and there is coordination b/w @luhan2017 @yeze322.

**Comment by tonyanziano** [comment]
@zxyanliu is this still in progress / is it confirmed for the R12 release?

**Comment by zxyanliu** [comment]
@tonyanziano It is in progress but I do not have enough context/materials to document at this point. 
@cwhitten I think you said it is an R12 work item of docs, right?

**Comment by luhan2017** [comment]
This is the PR to resolve this issue, @zxyanliu , please follow the readme for more details.
