### ISSUE TITLE
yarn start:dev will throw error in main branch

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#4529]
## Describe the bug
![db5134f5-9320-4eb0-aaee-cfedf9e12c26](https://user-images.githubusercontent.com/39758135/97159047-40e1ee80-17b5-11eb-8efa-95d1c62f0dc6.jpg)

If I drop #4384 , all works.

## Version
main branch

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by taicchoumsft** [comment]
Hi @lei9444, can you try installing the Visual C++ redist package and try again? [vcredist](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

**Comment by lei9444** [comment]
@taicchoumsft Thanks It works now.
