### ISSUE TITLE
In trigger selector, "Greeting (ConversationalUpdate activity)" should be renamed as Conversational Update

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4530]
This has been bugging me for a while and at the very start threw me off guard as well. All activities are named after the actual activity itself and have no implementation. The only difference is the ConversationUpdate activity. Somehow that's called Greeting, so the name is not based on the activity but somehow what you **could** do with it and it has an implementation, which could be set up differently as well using the condition for example.

I should think this should just as well be called Conversation Update and have no implementation. This could be used for many other things like storing conversation references etc, besides a greeting.

The documentation should be used to suggest implementations, like a greeting **using** the Conversation Update activity, or a custom event for that matter. And of course the templates could have this as well, as a quick start.

![image](https://user-images.githubusercontent.com/49873947/97165782-8639f800-1784-11eb-93e9-118b533baa3a.png)

**Comment by cwhitten** [comment]
This is by design. Assigning owners to look into if we wanted to make a change

**Comment by cwhitten** [comment]
hi @cxbuilders, we'll take this as a feature-request and seek to prioritize in our upcoming release
