### ISSUE TITLE
Trouble Implementing Custom MultiplyDialog Action Sample

### ISSUE THREAD

**Issue by nitewulf** [microsoft/BotFramework-Composer#4531]
I followed along with the instructions here:

https://docs.microsoft.com/en-us/composer/how-to-add-custom-action

I started with an empty bot.  I added the project reference, uncommented the two lines built the solution and ran the powershell script to merge the schema.  I verified the root schema file was updated.  When I open up the bot again in Composer I get the following error

Title: Error Processing Schema
Message: Definition not found for Microsoft.Ask/properties/activity/oneOf/1/properties/membersAdded/items

The MultiplyDialog Action is available and I added it to be called after the $WelcomeUser message.  When the bot tries to call it there is a null reference error:

{
  "channelId": "emulator",
  "conversation": {
    "id": "3d56fd60-1791-11eb-a059-1d88e66280b8|livechat"
  },
  "from": {
    "id": "3d3878e0-1791-11eb-b10e-0d8dc4378063",
    "name": "Bot",
    "role": "bot"
  },
  "id": "3e040640-1791-11eb-a059-1d88e66280b8",
  "inputHint": "acceptingInput",
  "localTimestamp": "2020-10-26T09:43:34-04:00",
  "locale": "en-US",
  "recipient": {
    "id": "c209be46-38e3-41d0-b523-6e43e972f19d",
    "role": "user"
  },
  "replyToId": "3d6c8130-1791-11eb-a059-1d88e66280b8",
  "serviceUrl": "http://localhost:63878",
  "text": "Object reference not set to an instance of an object.",
  "timestamp": "2020-10-26T13:43:34.308Z",
  "type": "message"
}

How can I debug this?

## Version

Version: 1.1.1
Electron 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

Edge

## OS

Windows

## Expected behavior

I'm expecting the bot to show the MultiplyDialog in the emulator.

## Screenshots
![Screenshot 2020-10-26 095026](https://user-images.githubusercontent.com/8270448/97180680-be374000-1770-11eb-8f9d-de6c7f514a4c.png)
![Screenshot 2020-10-26 094941](https://user-images.githubusercontent.com/8270448/97180682-be374000-1770-11eb-8409-d42c20dfd936.png)

**Comment by zxyanliu** [comment]
FYI. This is a known issue: https://github.com/microsoft/BotFramework-Composer/issues/4416
