### ISSUE TITLE
project tree state is not synced with global state

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#4543]
## Describe the bug

The current selection item in project tree is out of sync with Composer global state after
1. creating a new trigger
2. jumping to another dialog by clicking on BeginDialog

![image](https://user-images.githubusercontent.com/8528761/97256782-f319c480-184e-11eb-8f92-8f318a5d83ad.png)

![image](https://user-images.githubusercontent.com/8528761/97256760-e39a7b80-184e-11eb-9648-e0b39c3184f8.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
cc Ben @beyackle

**Comment by cwhitten** [comment]
@beyackle can you please include this fix in your current ProjectTree work? Thanks.

**Comment by beyackle** [comment]
These issues are now fixed by the PR I'm working on (#4466), so I'll make sure to reference that it closes this issue.
