### ISSUE TITLE
[MCS-DE-GO] -- Configurable timeout value for calls to Skill bots

### ISSUE THREAD

**Issue by joaollq** [microsoft/BotFramework-Composer#4546]
When calling a skill bot we noticed that we have the 15s timeout limitation.

Is there any easy way of making this timeout configurable? Do we need to have our custom Skill Connector class?
We might have situations in the future where the skill bot is handling long running processes (e.g. calculating the quotation for a new insurance proposal or aggregating history data from the user).

@goergenj @benbrown @sgellock

**Comment by sgellock** [comment]
@benbrown triage appropriately. I have it in R11, given it's a customer issue

**Comment by cwhitten** [comment]
@luhan2017 can you look at the SkillController class in Composer's runtime template to see if this is configurable via that hierarchy, or if we need to move this to an ask for the SDK? Thanks

**Comment by gabog** [comment]
Hi, do you want to set a timeout when the Bot calls a Skill or when the skill responds to the parent bot?

For the first one the [SkllHttpClient class](https://github.com/microsoft/botbuilder-dotnet/blob/3a0dcfee003a7fcd0271c6336ab2c166f9a74313/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/Skills/SkillHttpClient.cs) takes an HttpClient instance in the constructor where you can set your own [timeout](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=netcore-3.1)

**Comment by luhan2017** [comment]
@joaollq , did you try on @gabog 's suggestion to see whether it meets your requirement? We will support this in the upcoming release.

**Comment by goergenj** [comment]
@joaollq Can you comment?
