### ISSUE TITLE
Wait time for user input

### ISSUE THREAD

**Issue by thakursarvesh** [microsoft/BotFramework-Composer#4560]
I want to implement a wait time for the user input functionality of bot composer such that I can send a warning if user does not responds to the question for a specified time. I saw proactive notification available in sdk but not sure on how to implement in Bot Composer.

**Comment by dmvtech** [comment]
Hi @thakursarvesh 

You will definitely have to [modify the runtime](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#export-runtime), as there's no way to do this OOB with Composer currently. 

You could also add a custom action and do all of this (the proactive message, warning, etc) inside that custom action. You will still need to export the runtime and create that action to do that. More info [here](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action).

Additionally, if appropriate and not overkill for your scenario, you could create your own skill. There [are issues](https://github.com/microsoft/BotFramework-Composer/issues/4546) around that too, but it truly depends on how you might architect it all.

**Comment by dmvtech** [comment]
Hi @thakursarvesh any questions before I close this one?

**Comment by thakursarvesh** [comment]
Can you provide some link or some of the users who already have implemented this. It would be really helpful. I tried multiple custom codes but of no use.
