### ISSUE TITLE
LUIS bot not working on Azure Portal Web Chat or iframe

### ISSUE THREAD

**Issue by leopuleo** [microsoft/BotFramework-Composer#4563]
## Describe the bug

After deploying ToDoBotWithLuis I cannot test it in Azure Portal Web Chat or iframe in web page. 

## Version

Version:  1.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot
2. Choose Todo with LUIS template
3. Start bot locally, enter the LUIS authoringKey and select westeurope region
4. Open Bot Framework Emulator - IT WORKS, the bot shows "Hi, how can I help today?" response + buttons
5. Navigate to "Publish" page and publish the bot
6. Open Azure portal and navigate to the target Bot Service
7. Open "Test in Web Chat" page
8. No response from the bot 
9. Type "help" - No response from the bot

## Expected behavior

I expect to see "Hi, how can I help today?" response. The bot isn't working. 

## Screenshots

<img width="1207" alt="Screenshot 2020-10-28 at 11 03 03" src="https://user-images.githubusercontent.com/2866531/97421774-2e7ac880-190d-11eb-838a-e092c5316782.png">

## Additional context

Opening browser console inside Azure Portal Test Chat I notice several errors.

One of them is a failed network request to `https://webchat.botframework.com/v3/directline/conversations/any-string/activities`

Response body: 
```
{
  "error": {
    "code": "BotError",
    "message": "Failed to send activity: bot returned an error"
  },
  "httpStatusCode": 401
}
```

I experience the same issue when I try to embed the bot as an iframe in an HTML page

**Comment by dmvtech** [comment]
Hi @leopuleo 401 errors _typically_ (not always) means some sort of misconfiguration with the appId and/or appPassword. Did you configure these values in the Composer settings? Or just in the publishing profile? Additionally, are they configured in the Web App/App Service's. If you can check all three, that would be a good start.

**Comment by dmvtech** [comment]
Also; are you publishing to an existing resource or a new one?

**Comment by dmvtech** [comment]
I am closing this issue as it doesn't seem to be a blocking issue. Feel free to reopen or comment, if you still need to get this resolved.
