### ISSUE TITLE
handling  interruption in Bot Composer

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#4583]
Hi,

Please consider below scenario.

Suppose there are two Intents in the bot 'intent1' and 'intent2'. Corresponding dialog flows are there for each intent 'flow1' and 'flow2'  respectively. If an user starts flow1 and inside this flow (before completing this flow) if he enters utterance for 'intent2' then immediately 'flow2' should get started and after executing 'flow2' it should resume back inside the 'flow1' and continue executing flow1.

 Would you please help us in  implementing above scenario in Bot Composer.

Thanks,
Madan

**Comment by cwhitten** [comment]
Hi @BeheraMadan, see the following for an example of modeling interruptions using Adaptive Dialogs https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-help#allowing-interruptions

Closing as a how-to
