### ISSUE TITLE
After deploy Bot with composer, Luis has no endpoints hits not even is possible to Review Endpoint Utterances

### ISSUE THREAD

**Issue by SantiagoMadeira** [microsoft/BotFramework-Composer#4584]
After deploy Bot with composer, Luis has no endpoints hits not even is possible to Review Endpoint Utterances

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Composer
2. Create a new Bot
3. Create intents with LUIS (Language Understanding)
4. Add QnA
5. Change Language of bot to Pt-Br
6. Buil Bot and test em Bot Emulator
7. See hit-points in Luis in development Authoring resource
8. Click on Deploy
9. Follow steps explained in https://docs.microsoft.com/en-us/composer/how-to-publish-bot
10. Check that a new Authoring resource is created for LUIS
11. Test your bot in Web Page using token of Bot Channel created automaticaly in deploy
12. Check if Luis in Authoring resource generated by deploy have hits

## Expected behavior

Luis - Language Understanding in Authoring resource generated automaticaly in deploy have hits and possibility to Review Endpoint Utterances

## Screenshots

**1. Luis with Authoring resource used in Bot Framework Composer has hits after testing in emulator**

![image](https://user-images.githubusercontent.com/15849853/97593251-6c551b00-19f9-11eb-8c95-60f682107682.png)

**2. After deploy with composer, a new Luis a new Authoring resource is created but never gets hit when using web channel token**
![image](https://user-images.githubusercontent.com/15849853/97593044-33b54180-19f9-11eb-9528-11f3cd858411.png)

## Additional context

Language used is PT-BR

**Comment by anusharavindrar** [comment]
@SantiagoMadeira, thanks for reporting this. I will attempt a repro on my end and update the thread accordingly

**Comment by SantiagoMadeira** [comment]
hi,

I think I found a common factor between this issue and another one I reported #4458

Was using PT-BR as the defaultLanguage in Composer settings, and whenever I use that configuration I have these errors. When changing to defaultLanguage = 'en-us' everything works fine!

The final test I did was: 

1. configure Composer with only defaultLanguage = 'en-us', both issues work well. 
2. added PT-BR in Composer, rebuild bot in Composer. After that in LUIS a new APP was created for PT-BR.  
3. Without changing defaultLanguage in Composer it continued to work correctly.
4. In Composer remove language 'en-us' and set PT-BR as default, rebuild,  both issues work well (in this point have two Apps in Luis)
5. In LUIS I removed APP for language 'en-us' (well, at this point i'm not using that language in Composer) and just stayed with APP for PT-BR, and without rebuilding Composer and without Deploy for Azure... KABOOM! The error reappeared. 
6. I added APP for language 'en-us' in LUIS, everything worked fine again.

I think there is a problem when defining a default language other than 'en-us'

Now i'm working only with defaultLanguage='en-us' in Composer and everithing runs smooth

**Comment by anusharavindrar** [comment]
Adding @feich-ms for pointers

**Comment by feich-ms** [comment]
Hi @SantiagoMadeira, from my observations, there are some delays for the hits data in luis.ai portal even for local tests. Can you verify again that the hit counts is still 0 after a period of time?

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to reopen if the issue persists.
