### ISSUE TITLE
Get the user information from teams using Bot framework composer

### ISSUE THREAD

**Issue by Laxmi30** [microsoft/BotFramework-Composer#4587]
I had created a bot using bot framework composer and integrated it with MS Teams with help of the azure web app. Now I need to get the login user(MS Team) information i.e. the user who using the bot. I need to get the user information and log it in the azure application insights using Bot Framework Composer.

Can I use the component shown below of Bot Framework Composer,
![image](https://user-images.githubusercontent.com/46951085/97620787-080d7800-1a48-11eb-8e6a-b6f10015a2d4.png)
If yes than how can I implement it.

Can anyone help me with it.

**Comment by dmvtech** [comment]
Hi @Laxmi30 How much user info do you need? Do you need just the name/username, or more?

**Comment by dmvtech** [comment]
If you just need the name of the user, you can get that with `${turn.activity.from.name}`. Then, you can use the `Emit a telemetry track event` action to log that into Application Insights. If you want other user properties, you might have to do additional steps depending on what information you are looking for.

**Comment by Laxmi30** [comment]
Yes the user name and user email id, but if its possible to get complete user info then it will be good.

**Comment by Laxmi30** [comment]
> If you just need the name of the user, you can get that with `${turn.activity.from.name}`. Then, you can use the `Emit a telemetry track event` action to log that into Application Insights. If you want other user properties, you might have to do additional steps depending on what information you are looking for.

Thank you for your time. I hope the below I implemented is proper.
![image](https://user-images.githubusercontent.com/46951085/98074265-10bedd80-1e90-11eb-9103-91ac0b825757.png)

**Comment by dmvtech** [comment]
That should be it. You could also use `expression` instead of `string` and supply `=turn.activity.from.name` if you wish (they're both equivalent).

Were you able to test? Did it work for you?

**Comment by Laxmi30** [comment]
No its not working on emulator its giving error.

![image](https://user-images.githubusercontent.com/46951085/98206859-b04ba100-1f60-11eb-9607-62bb924a3af1.png)

**Comment by dmvtech** [comment]
Ok, let me test a couple of things.

**Comment by dmvtech** [comment]
I am able to reproduce this. I'm not sure what is happening. Stand by.

**Comment by dmvtech** [comment]
This is the same bug as identified here: https://github.com/microsoft/BotFramework-Composer/issues/4305

Essentially a mismatch with the schema. You can use the fix/workaround there by updating the kind in the dialog (code view) to be `Microsoft.TelemetryTrackEventAction` instead of `Microsoft.TelemetryTrackEvent`

**Comment by Laxmi30** [comment]
I didn't understand could you please explain to me.

**Comment by dmvtech** [comment]
Hi @Laxmi30 Just checking in. Were you able to get it working?

**Comment by Laxmi30** [comment]
Yes its working fine.
Thanks a lot.

**Comment by Laxmi30** [comment]
Hi,
I am unable to retrieve the user info from the team to store it in application insights.
I had tried with **${turn.activity.from.name}** in bot  framework composer. But it's only working for emulator and not in ms teams.

Could u please help me with it?

**Comment by dmvtech** [comment]
That should work. It works for me in MS Teams. Does it not even work in a simple send activity? Can you share more about your dialog and how you are using it?

**Comment by Laxmi30** [comment]
Please find below,
![image](https://user-images.githubusercontent.com/46951085/100714764-38945900-33dc-11eb-9e0a-3c0f224586aa.png)

And also the bot is not getting published as expected.
Could you please help me?

**Comment by dmvtech** [comment]
Hi @Laxmi30 My apologies! If you are doing that in the Greeting, that is a ConversationUpdate activity. And in **MS Teams**, this _only ever gets fired once_ for every user. See more info here:

- https://stackoverflow.com/a/55525014/13991249
- https://stackoverflow.com/a/64174799/13991249

You can easily test that that string interpolation/expression works is in another dialog (say in unknown intent). If you want to ensure it works in Greeting/ConversationUpdate, you can could create another test user in Teams (the other option is to create a brand new bot [bot registration], but that is a pain).

> And also the bot is not getting published as expected.

Please take a look [here](https://github.com/microsoft/BotFramework-Composer/issues?q=is%3Aissue+publish) and [here](https://stackoverflow.com/search?q=%5Bbotframework%5D+composer+publish) for common (or uncommon) publishing issues related to publishing from Composer. If you don't find the answer there, please open a new issue or question with all the pertinent information.

**Comment by mukdenchild** [comment]
Here is my test results:
In composer,  ${turn.activity.from.name} works in Greeting, not in intent triggers
In MS Team,  ${turn.activity.from.name} works in intent triggers, not Greeting (because it is not fired after 1st time).

**Comment by karthik22920** [comment]
Can Anyone @mukdenchild  @dmvtech  @Laxmi30  @mchelen  walk me through entire process please i am new to bot composer . 
Requirement :
1 To get user name and user id(email) without authenticating user(without using graph api ) i need to get user name .For now we are planning to deploy it to our SharePoint list/teams i need a way to make it work in both the  channels ???
2 to greet user with user name Irrespective of channel i may publish
Example: Hello (name of the user)
