### ISSUE TITLE
Cannot enable multiturn extraction in QnA

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#4590]
## Describe the bug

It seems that multiturn is not supported by importing URL when creating a QnA kb in Composer. It is supported when creating a KB from scratch and after edits to its .qna file. We should consider removing the multiturn extraction checkbox to avoid customer confusion and anxiety in the KB creation flow.

![image](https://user-images.githubusercontent.com/32497439/97633223-ff3d8780-19f0-11eb-818d-4fe3950b8421.png)

## Version

The main branch as of October 29, 2020

## Browser
- [x] Chrome

## OS

- [x] Windows

## Expected behavior

We can bring back the multiturn extraction checkbox when multiturn qna is supported by importing URL when creating a QnA kb in Composer.

## Screenshots

Importing URL with multiturn extraction checked in Composer: There is no hierarchy and tested multiturn did not work.

![image](https://user-images.githubusercontent.com/32497439/97633296-209e7380-19f1-11eb-941a-402deb07ec7d.png)

![image](https://user-images.githubusercontent.com/32497439/97633896-0dd86e80-19f2-11eb-88c1-c24331a1a2d3.png)

Importing URL with multiturn extraction checked in QnA portal: See the hierarchy and tested multiturn worked.

![image](https://user-images.githubusercontent.com/32497439/97633388-462b7d00-19f1-11eb-81b5-387d5a924d7d.png)

![image](https://user-images.githubusercontent.com/32497439/97633934-1fba1180-19f2-11eb-901e-efb2bac435fe.png)

## Additional context

Additional description and clarification of how to use multiturn qna will be covered in the docs.

**Comment by zhixzhan** [comment]
This is a regression bug  in bf-lu package, I'm following up with @feich-ms .
