### ISSUE TITLE
Running yarn install and getting Request failed \"503 Service Unavailable

### ISSUE THREAD

**Issue by obagaar** [microsoft/BotFramework-Composer#4594]
At the point of running yarn install and getting this error:

[3/5] Fetching packages...
error An unexpected error occurred: "https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/kind-of/-/kind-of-6.0.3.tg
z: Request failed \"503 Service Unavailable\"".
info If you think this is a bug, please open a bug report with the information provided in "C:\\users\\ashley.harper\\Doc
uments\\BotFramework-Composer\\Composer\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

An older issue mentions this being due to a feed being made private:

https://github.com/microsoft/BotFramework-Composer/issues/1525

**Comment by CezaryMarcjan** [comment]
Service issues which has been addressed since.
