### ISSUE TITLE
Resize causes expandos to clip

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4605]
## Describe the bug
Resizing the dialog explorer causes the expandos to sometimes clip:

![resize-issue](https://user-images.githubusercontent.com/698939/97817375-e7fcd500-1c50-11eb-8670-07ba9cc028c0.gif)

## Version

https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.178300.83c0804

**Comment by tonyanziano** [comment]
@beyackle can you please take a look at this issue with the other project tree issues?

**Comment by beyackle** [comment]
I'll take a look. I think it's a CSS problem.
