### ISSUE TITLE
Can't edit per/dialog settings

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4606]
## Describe the bug
If you try to click on a root dialog, within the design explorer, it always jumps you up to the root dialog. This means you have no way of changing the settings for a given dialog without editing the file directly.

![cant-select-dialog-root](https://user-images.githubusercontent.com/698939/97817603-51c9ae80-1c52-11eb-94fa-9e8e7d1c5a5d.gif)
 

## Version

https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.178300.83c0804

**Comment by beyackle** [comment]
I've verified that the PR I have in review fixes this bug as well.
