### ISSUE TITLE
Can't add new properties to SetProperties action

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#4608]
## Describe the bug
You can't add new properties to the `SetProperties` action in the nightly build. You can click add and the new fields show up but the moment you click into them they disappear.

![cant-add-properties](https://user-images.githubusercontent.com/698939/97817828-b8030100-1c53-11eb-92ed-90aa49448f23.gif)

## Version

https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.178300.83c0804

**Comment by nitewulf** [comment]
I can confirm this.  I had to switch to code view and manually add properties on Friday.

**Comment by cwhitten** [comment]
This is addressed on the `main` branch. Closing
