### ISSUE TITLE
When an action node is newly created, it is supposed to be focused immediately

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#4616]
## Is your feature request related to a problem? Please describe.

Currently, when you create a new action node in the authoring canvas, the focus goes to the action node below the newly created. 

![Screen Shot 2020-11-02 at 12 56 23 PM](https://user-images.githubusercontent.com/50963385/97918622-41293f00-1d0b-11eb-9696-b8b289ed8d7d.png)
1. Creating a new Send a response node

![Screen Shot 2020-11-02 at 12 56 37 PM](https://user-images.githubusercontent.com/50963385/97918682-5736ff80-1d0b-11eb-90f6-66def41eaacd.png)
2. I would expect the Send a response node to be in the focus state, not the node below.

## Describe the solution you'd like

The newly created action node is supposed to be in the focus state immediately after it has been created so that the user can seamlessly continue authoring that node without having to click on it.

**Comment by tonyanziano** [comment]
@yeze322 can you please take a look at this?

**Comment by yeze322** [comment]
got it, WIP
