### ISSUE TITLE
Empty QnA files generated for form dialog generated dialogs upon opening a project

### ISSUE THREAD

**Issue by hatpick** [microsoft/BotFramework-Composer#4617]
## Describe the bug

Composer creates empty QnA files for generated dialogs (form dialogs) when a project containing one is loaded (opened).

## Version

Latest on main.

## Browser

- [x] Electron distribution
- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

## OS

- [x] macOS
- [x] Windows
- [x] Ubuntu

## To Reproduce

1. Turn on form dialog feature flag from settings.
2. Navigate to forms (table icon on the main left nabvigation)
3. Create an schema and add one property of type "any string"
4. Click generate dialog.
5. Once the generation is complete, navigate to design page to see the generated dialog.
6. Open explorer to your bot, look at under dialogs, you should see a folder with the same name as the schema from step 3.
7. Now refresh the Composer app and check your explorer again.
8. You can now see the generated files next to the directory from step 6.

## Expected behavior

Don't generated empty QnA files for generated form dialogs. This can break the ProjectTree as you can see in the attached screenshot.

## Screenshots

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/1483492/97924383-6b332f00-1d14-11eb-8a40-e37095eb6377.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/1483492/97924386-6c645c00-1d14-11eb-9960-45d4d5e3029a.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/1483492/97924390-6c645c00-1d14-11eb-987a-22f0113d7b2f.png)

## Additional context

Check this PR:
https://github.com/microsoft/BotFramework-Composer/commit/72e5700746c29831ce3401020905285d0bde2473
separateDialogsAndRecognizers detects recognizers from generated dialogs and causes Composer to create those files.

**Comment by tonyanziano** [comment]
Assigned to @zhixzhan pending #4612
