### ISSUE TITLE
Set properties input fields keep disappearing on any mouse action

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#4618]
## Describe the bug

In the Set properties action, when you create an entry by clicking the Add button, any mouse action - clicking on one of the fields or anywhere else on the screen - makes the entry disappear.

![ezgif-5-1cf187f211d5](https://user-images.githubusercontent.com/50963385/97930323-f4039800-1d1f-11eb-84fa-bd4d2fb9d696.gif)

**Comment by LouisEugeneMSFT** [comment]
This was fixed in https://github.com/microsoft/BotFramework-Composer/pull/4572
