### ISSUE TITLE
Broken link for trace activity node

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#4623]
## Describe the bug

The "Learn more" link in the details pane for "Emit a trace event" is broken.

## Version

v.1.1.1

## Browser

- [x] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to the Design to any trigger.
2. Press the + button to add a node.
3. Select the "Debugging options" > "Emit a trace event"
4. Click on "Learn more" in the details pan.

## Expected behavior

The link should go to a doc that explains how to use trace events.

## Screenshots
![image](https://user-images.githubusercontent.com/39317542/97944949-ec052180-1d3a-11eb-8712-a596b65b6319.png)

**Comment by tonyanziano** [comment]
@zxyanliu can you please provide the correct docs link for this? Or update the aka.ms link if needed. Thanks.

**Comment by zxyanliu** [comment]
Hi @tonyanziano 
I think the best link for this action is this article: https://aka.ms/composer-telemetry

**Comment by tonyanziano** [comment]
Thanks @zxyanliu !

**Comment by zxyanliu** [comment]
All the following learn more links are broken, I can fix them: 

![image](https://user-images.githubusercontent.com/32497439/98026108-7d1ddc00-1dbf-11eb-9380-148f5e8e090b.png)

**Comment by zxyanliu** [comment]
@tonyanziano The fixes are in the [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Schema) repo. Do you want me to fix them?

**Comment by tonyanziano** [comment]
@zxyanliu if you can that would be much appreciated. Otherwise we can assign someone to fix them.

**Comment by zxyanliu** [comment]
@tonyanziano It's a quick fix. I can help.

**Comment by zxyanliu** [comment]
The PR to fix this issue was merged. We can close this issue for now. 
The bits will be available in Composer for 1.2 release.
