### ISSUE TITLE
Delete a main dialog will raise 500 server error

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#4626]
## Describe the bug
**Problem**:
After deleting the main dialog, Composer poped up a 500 error and the project folder was deleted. User won't have a chance to undo this change.

The error always happens even main dialog is not the only existing dialog.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/8528761/97949477-b3168c80-1dce-11eb-8b18-30277c60812d.gif)

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new project
2. Delete the main dialog
3. There will be a 500 server error
4. Reopen this project, it will raise another 500 error
5. The project then disappers

## Expected behavior

If deleting main dialog raises errors, we should forbid that behavior.

**Comment by boydc2014** [comment]
@liweitian we should not allow delete the main dialog
