### ISSUE TITLE
Should hide the 'actions' part of the 'Duplicated intents recognized' trigger

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#4628]
## Describe the bug
![image](https://user-images.githubusercontent.com/8528761/97958523-5758fd00-1de8-11eb-95d3-fbecc108a7ff.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
@a-b-r-o-w-n we need uischema for this component. Can you take a look?

**Comment by a-b-r-o-w-n** [comment]
@cwhitten should we try to get this into the sdk release?

**Comment by cwhitten** [comment]
> @cwhitten should we try to get this into the sdk release?

we can try, but i doubt that they will take it.
