### ISSUE TITLE
Breadcrumb text is foced to be capitalized

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#4631]
## Describe the bug
![image](https://user-images.githubusercontent.com/8528761/97959199-c5ea8a80-1de9-11eb-894b-fca52d46b2ea.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by tonyanziano** [comment]
@beyackle can you please take a look at this?

**Comment by beyackle** [comment]
Looks like the PR I have out for breadcrumbs is already fixing this.
![image](https://user-images.githubusercontent.com/61990921/98025918-303a0580-1dbf-11eb-9444-914af509c660.png)
