### ISSUE TITLE
Project Tree generates duplicated dialog name path

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#4632]
## Describe the bug
Duplicated dialog names in breadcrumb
![image](https://user-images.githubusercontent.com/8528761/97959301-06e29f00-1dea-11eb-9163-d9b765f0647f.png)
And inconsistent breadcrumb path
![image](https://user-images.githubusercontent.com/8528761/97959679-d51e0800-1dea-11eb-8f48-739d68a2d7ee.png)
![image](https://user-images.githubusercontent.com/8528761/97959718-e8c96e80-1dea-11eb-96df-19dd3dc68e5d.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
Related to and may have been fixed by #4604.  cc @beyackle

**Comment by beyackle** [comment]
That PR is a rewrite of how breadcrumbs work, and I agree that it should fix this bug. I'll add this issue to its description.
