### ISSUE TITLE
perf: feels slow in the bot project name input box

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#4633]
## Describe the bug

When inputting a bot name, I can feel the latency between key pressed - char appeared.

To repro this, try holding a key in the 'Name' field
![bug-botnameperf](https://user-images.githubusercontent.com/8528761/97960013-86bd3900-1deb-11eb-8405-02471e34faf2.gif)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by liweitian** [comment]
![a](https://user-images.githubusercontent.com/24380525/98217134-07636d00-1f85-11eb-8640-4aeae297472b.gif)
LGTM. Does anyone else feel it laggy?

**Comment by yeze322** [comment]
@liweitian Try creating at least 10 bot projects under your current folder and the delay will be more obvious
