### ISSUE TITLE
value of multiple input choice action is not getting stored in the input property if user doesn't click on the options provided

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#4634]
Hi,

In composer bot we are providing a multiple input choice action to the user for selecting the choice from the list  as shown below. If user click on the button value is getting stored in the property. But instead of clicking on the button if user types something then the user typed phrase is not getting stored in the property and value in the property showing as null. Is there any way to store this user typed phrase in the property ? 

![image](https://user-images.githubusercontent.com/70739031/97959981-81092880-1dd6-11eb-8171-fca0dc68919e.png)

![image](https://user-images.githubusercontent.com/70739031/97960026-97af7f80-1dd6-11eb-919b-ef95ecd16785.png)

Thanks,
Madan

**Comment by tonyanziano** [comment]
@stevengum is this scenario supported? Is it possible to capture the user's input if it does not match one of the choice input options?

**Comment by stevengum** [comment]
If it doesn’t match one of the input actions they developer would need to write custom code, and would probably be better off with a TextInput or something similar if the bot is storing all responses for the prompt.

That said, I’m not sure @BeheraMadan’s above scenario depends on a non-matching input.

It seems more like a basic functionality issue in Adaptive SDKs or the Composer.

If it’s the SDKs, it seems straightforward to fix but we will probably need more information from the customer. For Composer, it might be a configuration in the runtime that needs to be tweaked and might be tied to the runtime’s behavior to the response from said card action. 

@EricDahlvang can you chime in? What do you think?

P.S. This issue would also affect headless (speech, no GUI) bots as it seems that only the buttons are valid user inputs.

**Comment by dmvtech** [comment]
@BeheraMadan There are a couple of approaches @BeheraMadan could do. One simple one is to follow up the choice with some sort of check. For example an if/else branch. Check for the value, then determine how to proceed from there. The better might approach be to use an adaptive expression and/or checking for value of `turn.lastresult`. The contains and coalesce prebuilt functions come to mind.


https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0

v

**Comment by dmvtech** [comment]
Ok, I did get a workaround working by setting the `Default value` of the choice prompt to be `=this.value`

@BeheraMadan can you test and see if that works for you?

**Comment by BeheraMadan** [comment]
Thanks above solution  working fine for me.
