### ISSUE TITLE
click notification page item can't navigation to the error position

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#4638]
## Describe the bug
![navigation](https://user-images.githubusercontent.com/39758135/97964357-9b9dca80-1df3-11eb-87f0-f62c6345b867.gif)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by liweitian** [comment]
need to update this test case #4592
