### ISSUE TITLE
click setting page will show "data loading" 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#4639]
## Describe the bug

Open bot from homepage "history", and then click bot setting. it will show error.
But if you click  each tab in bot setting, it can load appsetting.json correctly.

![image](https://user-images.githubusercontent.com/43408889/97966118-5af38080-1df6-11eb-90fd-2dd2cef6fd89.png)

## Version
latest main

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

**Comment by boydc2014** [comment]
@liweitian can you check this?

**Comment by boydc2014** [comment]
I actually can't repro this.

**Comment by liweitian** [comment]
> I actually can't repro this.

It seems some old bots get influenced. For new created ones, they are all good.
