### ISSUE TITLE
QnA knowledge base cannot be created from authoring canvas

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#4643]
## Describe the bug
On Electron, 
1. created QnA not be imported by dialog
2. design page create met error

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Screenshots

![Untitled1](https://user-images.githubusercontent.com/49866537/97971470-14a21f80-1dfe-11eb-9a50-bfeecbd401ef.gif)
![Untitled2](https://user-images.githubusercontent.com/49866537/97971481-19ff6a00-1dfe-11eb-85e7-5715e905c6cb.gif)

**Comment by boydc2014** [comment]
Can't repro. Close it for now
