### ISSUE TITLE
Test in Emulator / start bot button can not be hover/click

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/BotFramework-Composer#4644]
## Describe the bug
when hover on the button, it flip, can't be clicked.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## Screenshots
![Untitled3](https://user-images.githubusercontent.com/49866537/97972241-2f28c880-1dff-11eb-9960-acbe7af9ecb5.gif)

**Comment by cwhitten** [comment]
@srinaath and I cannot reproduce this @zhixzhan

**Comment by lei9444** [comment]
@cwhitten @srinaath @zhixzhan I can reproduce it, I think it is the issue about 
![test](https://user-images.githubusercontent.com/39758135/98064877-52e71f80-1e8e-11eb-8de9-7904508cd1a3.gif)
the notification panel cover the button component

**Comment by zhixzhan** [comment]
@lei9444 Yes, the key repro step is "let the notification panel auto dismiss, do not close it manually"
