### ISSUE TITLE
Dev env issues: Caching hostedbots with source code causes errors if composer run from two different locations.

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#4645]
## Describe the bug

Developers may have two enlistments of the composer source code (or run the web app from different locations).  When publishing a bot, the localpublish extension published to a hostedbots folder under localpublish.  However, Composer saves the recent published name (e.g. 21573.519693286446) in session storage.

This means if Composer runs from another location, the app will put up an error that it couldn't find that published bot and won't let the user continue.  

I don't think Composer should error if a most recently used hostedbot can't be found, as well, the key for session storage should probably have more information about the root composer location or not be used.

Note: I think in electron, the hostedbots ends up in %appdata%, so I don't think this is an issue for electron.

## Version

main/ lasted on 11/3/2020

## Browser

- [ ] Electron distribution
- [ X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create two enlistments of Composer (A and B)
2. Build and run A
3. Create a bot project and publish it (verify it working in emulator)
4. Close A
5. Build and run B
6. Error appears saying that the hostedbot project cannot be found

## Expected behavior

No error, or ability to wipe our the MRU hostedbot project from session storage.

**Comment by Clooney24** [comment]
Just deleted all my content in hostedBots folder by accident - bot doesn't start anymore - how can I fix this?

**Comment by Clooney24** [comment]
Just re-installed composer and it could be started again

**Comment by benbrown** [comment]
This functionality is no longer present in 2.0
