### ISSUE TITLE
Disabling a node causes a validation error and the bot cannot be started.

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#4651]
## Describe the bug

Disabling a node causes a validation error and the bot cannot be started.

http://g.recordit.co/5bcl5DM0iN.gif

![5bcl5DM0iN](https://user-images.githubusercontent.com/729873/98041600-d13cb680-1de7-11eb-9d4a-aa788ea783aa.gif)

## Version

nightly build

## Browser

- [x] Chrome

## OS

- [x] macOS
## To Reproduce

1. Create a dialog
2. insert a send activity as the first node
3. disable the node
4. See a validation error appear in the upper right, " end a response: disabled the return type does not match"

## Expected behavior

This should not show a validation error.

**Comment by luhan2017** [comment]
This is because the disable field is defined as stringExpression for Microsoft.SendActivity type, others are all defined as booleanExpression.
I will submit two PRs in both composer and sdk side.
