### ISSUE TITLE
Inconsistencies on publish page when using PVA extension

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#4659]
## Describe the bug

publish to pva error if add more triggers in main dialog. meanwhile I can not export to.zip for pva bot.
![image](https://user-images.githubusercontent.com/43408889/98069738-7912bc80-1e9a-11eb-9bb5-3d37065fb020.png)

And after the spin, the publish failed, no results showed on publish page and check for pva bot asset. It does not updat as well.
![image](https://user-images.githubusercontent.com/43408889/98069990-343b5580-1e9b-11eb-8733-3e71ae182227.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. add more triggers as below 
![image](https://user-images.githubusercontent.com/43408889/98069903-f5a59b00-1e9a-11eb-9aea-c145f3dab655.png)

2. add only one action "BeginDialog" for each trigger

3. publish to pva

**Comment by tonyanziano** [comment]
Brenda reported that the publish history / status is flakey and sometimes either disappears altogether or spins indefinitely.
