### ISSUE TITLE
Provisioning: Offer separate toggle and/or notification about luis and qna region

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#4693]
## Is your feature request related to a problem? Please describe.

LUIS and QNA have a more restricted list of regions they are available in.  Currently, if the user selects a region tht is not supported, the provisioning tool will default to the `westus` region.

We should allow the user to select this region separately.

## Describe the solution you'd like

Offer a separate dropdown for LUIS/QNA region in the provisioning flow.

## Describe alternatives you've considered

Alternatively, we could pop up a notification if the user selects an unsupported region, and continue to default to `westus` in this case.

**Comment by benbrown** [comment]
We discussed this, and @JaskeeratBedi-cmk will provide some updated designs.

The proposed design is to add a checkmark style toggle to each item in the list on the "review" page.

**Comment by JaskeeratBedi-cmk** [comment]
- **For Region** Design presented 2 options ( See attached screenshot)

![In progress _ Region](https://user-images.githubusercontent.com/67944302/98426585-3a256800-204e-11eb-999b-977338414a00.jpg)

@benbrown @emivers8 @JaskeeratBedi-cmk evaluated both the options and agreed that while Solution 1 offers most flexibility it may not work for all user archetypes. Solution 2 maybe more suited for this context however needs a deep dive on the Region mapping complexity.

- **For Review & Create** Design has proposed the following UI iteration ( See screenshot)
![provisioning_review   create](https://user-images.githubusercontent.com/67944302/98426716-d485ab80-204e-11eb-825c-9aa300837d2c.jpg)

Figma file here- https://www.figma.com/file/J3oIdXDmeBQbAe4a4PYbQc/Jaskeerat-Bedi?node-id=3746%3A3600

**Comment by benbrown** [comment]
@VanyLaw Please implement "solution 1" as pictured above.  

If user selects a region that is not supported by luis and/or qna, offer the option to select from the valid options.
