### ISSUE TITLE
Ibiza bot templates aren't compatible with Composer

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#4695]
## Describe the bug

Currently when I create a web app bot in Azure, I choose between echo bot or basic bot templates and then I'm given bot files to download. However, I can't open them in Composer because these templates are not declarative. (This means it's also misleading to try to drive users to Composer from the resource page in Ibiza, which we would like to do.)

## Expected behavior

Provide me with bot files I can open in Composer, or at least a way to create the resource then download a config file I can input into Composer.

## Additional context

There's a strong business need to improve the flow from Ibiza to Composer.

**Comment by benbrown** [comment]
Another thing to consider --

Once a bot is created via Ibiza, the portal could provide a downloadable or copy-pasteable "publishing profile" that can easily be imported to ANY COMPOSER PROJECT.  This would allow that project to publish back to the pre-created host, replacing whatever content was originally there.

**Comment by benbrown** [comment]
Just a for example here, the portal would provide at a minimum something like:

```
{
"MicrosoftAppId": "The bot registration id",
"microsfotAppSecret": "The bot secret",
"hostname": "some-web-server-name",
}
```

These are already known values in the portal.

In addition, it could provide the app insights if already created, luis, cosmos, etc - any of the key resources we use.

**Comment by cwhitten** [comment]
We will follow the same mechanisms that are utilized when going from PVA -> Composer

**Comment by benbrown** [comment]
I believe this has been handled by the new ABS handoff.  Is there work still to be done for this?

**Comment by cwhitten** [comment]
Yup! Closing. Nice work team!
