### ISSUE TITLE
Cannot deployed bot run from Azure

### ISSUE THREAD

**Issue by soutchilin** [microsoft/BotFramework-Composer#4716]
## Describe the bug
I've used https://docs.microsoft.com/en-us/composer/tutorial/tutorial-create-bot tutorial and configured all chapters 0-7 to work locally (and in the last one with LUIS). 
I've used the latest Bot Composer.

Then I deployed as described in https://docs.microsoft.com/en-us/composer/how-to-publish-bot.
I did it utilizing Azure Functions Bot deployment template, creating everything fresh into an empty resource group. This succeeded, but the bot don't run because the Azure Function doesn't run (it brings Internal Server Error)

Afterthat I tried out deployment to a Web App. I used the Web App bot deployment template and deployed it to another empty resource group. The deployment succeeded, but the bot doesn't run because the web app doesn't run and complains about a need to upgrade to websocket.

I don't write here a roman about what I've tried out in last 3 hours because I think that you can reproduce this simple steps: Configure the bot locally as described in the mentioned documentation and deploy it. If you need more information, let us setup a meeting with screensharing.

## Version

![image](https://user-images.githubusercontent.com/3247085/98482331-00e12980-2201-11eb-87f5-bacfa4fd58af.png)

**Comment by luhan2017** [comment]
It will be very helpful if we can have a meeting with screensharing.  I am in Beijing, UTC+8, please let me know when do you prefer and your email address. @soutchilin

**Comment by soutchilin** [comment]
Hi Lu,

Cool, let's have a session on 11. November at UTC 8am.

Regards,
Alexander
________________________________
Von: Lu Han <notifications@github.com>
Gesendet: Montag, 9. November 2020 10:53
An: microsoft/BotFramework-Composer <BotFramework-Composer@noreply.github.com>
Cc: soutchilin <fbsouSh@outlook.de>; Mention <mention@noreply.github.com>
Betreff: Re: [microsoft/BotFramework-Composer] Cannot deployed bot run from Azure (#4716)


It will be very helpful if we can have a meeting with screensharing. I am in Beijing, UTC+8, please let me know when do you prefer and your email address. @soutchilin<https://github.com/soutchilin>

**Comment by luhan2017** [comment]
@soutchilin , meeting request sent, please confirm if you see that.

**Comment by soutchilin** [comment]
Thanks, I confirm.

Alexander
________________________________
Von: Lu Han <notifications@github.com>
Gesendet: Dienstag, 10. November 2020 02:43
An: microsoft/BotFramework-Composer <BotFramework-Composer@noreply.github.com>
Cc: soutchilin <fbsouSh@outlook.de>; Mention <mention@noreply.github.com>
Betreff: Re: [microsoft/BotFramework-Composer] Cannot deployed bot run from Azure (#4716)


@soutchilin<https://github.com/soutchilin> , meeting request sent, please confirm if you see that.

**Comment by soutchilin** [comment]
Hi Lu,

I've created a fresh Azure resources for the "azure function app" template in an empty resouce group. The attempt to deploy ended with an error somewhere inside of a javascirpt ("o is not a function"). Please find the log:
===================
Publish starting...
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\a.soutchilin\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4acb59b43b15afc4f723cfb7a1e4f11d\\azurefunctions\\ComposerDialogs\\generated\\interruption\\Cancel.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\a.soutchilin\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4acb59b43b15afc4f723cfb7a1e4f11d\\azurefunctions\\ComposerDialogs\\generated\\interruption\\CancelAll.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\a.soutchilin\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4acb59b43b15afc4f723cfb7a1e4f11d\\azurefunctions\\ComposerDialogs\\generated\\interruption\\getWeather.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\a.soutchilin\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4acb59b43b15afc4f723cfb7a1e4f11d\\azurefunctions\\ComposerDialogs\\generated\\interruption\\Help.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\a.soutchilin\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\4acb59b43b15afc4f723cfb7a1e4f11d\\azurefunctions\\ComposerDialogs\\generated\\interruption\\weatherbot.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"stack\":\"TypeError: o is not a function\\n    at global.fetch (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:865268)\\n    at t.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:160552)\\n    at C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3944077\\n    at Object.next (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3944182)\\n    at C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3943119\\n    at new Promise (<anonymous>)\\n    at l (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3942864)\\n    at t.fetch (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:160469)\\n    at t.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:153246)\\n    at C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3944077\\n    at Object.next (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3944182)\\n    at s (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3942921)\",\"message\":\"o is not a function\"}"
}
o is not a function

==============


Any ideas?

Regards,
Alexander
________________________________
Von: Alexander Soutchilin <fbsouSh@outlook.de>
Gesendet: Dienstag, 10. November 2020 22:37
An: microsoft/BotFramework-Composer <BotFramework-Composer@noreply.github.com>; microsoft/BotFramework-Composer <reply@reply.github.com>
Cc: Mention <mention@noreply.github.com>
Betreff: AW: [microsoft/BotFramework-Composer] Cannot deployed bot run from Azure (#4716)

Thanks, I confirm.

Alexander
________________________________
Von: Lu Han <notifications@github.com>
Gesendet: Dienstag, 10. November 2020 02:43
An: microsoft/BotFramework-Composer <BotFramework-Composer@noreply.github.com>
Cc: soutchilin <fbsouSh@outlook.de>; Mention <mention@noreply.github.com>
Betreff: Re: [microsoft/BotFramework-Composer] Cannot deployed bot run from Azure (#4716)


@soutchilin<https://github.com/soutchilin> , meeting request sent, please confirm if you see that.

**Comment by luhan2017** [comment]
@soutchilin sorry it is my fault, the issue you pasted is a known issue in our nightly builds which is unrelated. could you please try this one? https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/download/v1.1.1-nightly.184477.e4c4f36/BotFramework-Composer-1.1.1-nightly.184477.e4c4f36-windows-setup.exe I've tested on my side, it is working well:

![image](https://user-images.githubusercontent.com/32191031/98891706-b221e100-24d9-11eb-9fe3-c6ee7decf199.png)
![image](https://user-images.githubusercontent.com/32191031/98891736-c2d25700-24d9-11eb-9bf7-26c178a720f8.png)

**Comment by soutchilin** [comment]
Hi Lu,

Thanks, I've tried out.

Publish starting...
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\a.soutchilin\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\c0ae49610001e8a11d15c5ff58c30dd3\\azurefunctions\\ComposerDialogs\\generated\\interruption\\Cancel.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\a.soutchilin\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\c0ae49610001e8a11d15c5ff58c30dd3\\azurefunctions\\ComposerDialogs\\generated\\interruption\\CancelAll.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\a.soutchilin\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\c0ae49610001e8a11d15c5ff58c30dd3\\azurefunctions\\ComposerDialogs\\generated\\interruption\\getWeather.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\a.soutchilin\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\c0ae49610001e8a11d15c5ff58c30dd3\\azurefunctions\\ComposerDialogs\\generated\\interruption\\Help.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "C:\\Users\\a.soutchilin\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\c0ae49610001e8a11d15c5ff58c30dd3\\azurefunctions\\ComposerDialogs\\generated\\interruption\\weatherbot.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"stack\":\"TypeError: Expected signal to be an instanceof AbortSignal\\n    at new W (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3513893)\\n    at C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3515216\\n    at new Promise (<anonymous>)\\n    at G (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3515179)\\n    at global.fetch (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:876716)\\n    at t.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:171029)\\n    at C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3950367\\n    at Object.next (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3950472)\\n    at C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3949408\\n    at new Promise (<anonymous>)\\n    at Object.u [as __awaiter] (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3949153)\\n    at t.fetch (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:170940)\\n    at t.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:163724)\\n    at C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3950367\\n    at Object.next (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3950472)\\n    at s (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3949210)\",\"message\":\"Expected signal to be an instanceof AbortSignal\"}"
}
Expected signal to be an instanceof AbortSignal



--------

One thing more, not sure, if it is ok. The call to create the infrastructure was:
node provisionComposer.js --subscriptionId=7f2085b5-6bba-48eb-9b4a-c35487e38749 --name=rg-bots --appPassword=LqZOcxF0YMV2mU!z5CLUR --environment=dev --location=westeurope --customArmTemplate=DeploymentTemplates/function-template-with-preexisting-rg.json

and the Azure function shows:

[cid:c74752ab-4a72-4838-b481-7b9e5525637f]


Regards,
Alexander
________________________________
Von: Lu Han <notifications@github.com>
Gesendet: Donnerstag, 12. November 2020 04:25
An: microsoft/BotFramework-Composer <BotFramework-Composer@noreply.github.com>
Cc: soutchilin <fbsouSh@outlook.de>; Mention <mention@noreply.github.com>
Betreff: Re: [microsoft/BotFramework-Composer] Cannot deployed bot run from Azure (#4716)


@soutchilin<https://github.com/soutchilin> sorry it is my fault, the issue you pasted is a known issue in our nightly builds which is unrelated. could you please try this one? https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/download/v1.1.1-nightly.184477.e4c4f36/BotFramework-Composer-1.1.1-nightly.184477.e4c4f36-windows-setup.exe I've tested on my side, it is working well:

[image]<https://user-images.githubusercontent.com/32191031/98891706-b221e100-24d9-11eb-9fe3-c6ee7decf199.png>
[image]<https://user-images.githubusercontent.com/32191031/98891736-c2d25700-24d9-11eb-9bf7-26c178a720f8.png>

**Comment by ClarkYin** [comment]
I am also getting the same error but on the new 1.2.0 
 when i'm publishing this. i've tried many variables now and i'm not sure how to get this to work.

Publish starting...
{
  "status": "DEPLOY_INFO",
  "message": "/Users/clarkyin/BotFrameworkComposer/publishBots/773fac7175f46b5db80dd64549a2a73f/azurewebapp/ComposerDialogs/generated/interruption/Order_Cash_Withdrawl.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/clarkyin/BotFrameworkComposer/publishBots/773fac7175f46b5db80dd64549a2a73f/azurewebapp/ComposerDialogs/generated/interruption/Request-Change-Cancel-SSV.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/clarkyin/BotFrameworkComposer/publishBots/773fac7175f46b5db80dd64549a2a73f/azurewebapp/ComposerDialogs/generated/interruption/SST.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/clarkyin/BotFrameworkComposer/publishBots/773fac7175f46b5db80dd64549a2a73f/azurewebapp/ComposerDialogs/generated/interruption/SSTFlow.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/clarkyin/BotFrameworkComposer/publishBots/773fac7175f46b5db80dd64549a2a73f/azurewebapp/ComposerDialogs/generated/interruption/Setup-SSV.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/clarkyin/BotFrameworkComposer/publishBots/773fac7175f46b5db80dd64549a2a73f/azurewebapp/ComposerDialogs/generated/interruption/Starbucks.en-us.lu loaded\n"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"stack\":\"TypeError: Expected signal to be an instanceof AbortSignal\\n    at new W (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3513893)\\n    at /Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3515216\\n    at new Promise (<anonymous>)\\n    at G (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3515179)\\n    at global.fetch (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:876716)\\n    at t.<anonymous> (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:171029)\\n    at /Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3950979\\n    at Object.next (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3951084)\\n    at /Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3950020\\n    at new Promise (<anonymous>)\\n    at Object.u [as __awaiter] (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3949765)\\n    at t.fetch (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:170940)\\n    at t.<anonymous> (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:163724)\\n    at /Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3950979\\n    at Object.next (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3951084)\\n    at s (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3949822)\",\"message\":\"Expected signal to be an instanceof AbortSignal\"}"
}
Expected signal to be an instanceof AbortSignal

**Comment by ferrarirosso** [comment]
Same problem here
Started after upgrading to Bot Composer 1.2.0
Deleted everything from Azure and recreated according to the docs but I am not able to publish from the bot composer and getting "Expected signal to be an instanceof AbortSignal"
Switching to ngrok for my demo...

**Comment by eedwards36** [comment]
I am also experiencing this issue after upgrading to Bot Composer 1.2.0 and getting the error message "Expected signal to be an instanceof AbortSignal" when trying to publish from the composer.

Is there a workaround for this?

**Comment by ferrarirosso** [comment]
> I am also experiencing this issue after upgrading to Bot Composer 1.2.0 and getting the error message "Expected signal to be an instanceof AbortSignal" when trying to publish from the composer.
> 
> Is there a workaround for this?
If you are on windows, I have edited the file ...\azurepublish\lib\index.js and replaced the 
throw Exception ... "Expected signal to be an instanceof AbortSignal"
with
console.log "Expected signal to be an instanceof AbortSignal"
After that I could publish, but it's a dirty workaround
