### ISSUE TITLE
Pass bot settings to custom action

### ISSUE THREAD

**Issue by UmaPrelude** [microsoft/BotFramework-Composer#4723]
Hi,

I have a custom action/dialog for sending email.
I want to have something in appsettings like smtp details and use it in custom action dialog.
Please help me to pass iconfiguration to custom dialog. or any other solution.

Regards,
Umprel

**Comment by luhan2017** [comment]
@UmaPrelude , you can just use the settings scope memory. for example "settings.yourSettings". 
Please refer to the custom action sample: 

 StringExpression yourSettings = "settings.yoursettings"
 var yourSettingsValue = yourSettings.GetValue(dc.State);

**Comment by UmaPrelude** [comment]
> @UmaPrelude , you can just use the settings scope memory. for example "settings.yourSettings".
> Please refer to the custom action sample:
> 
> StringExpression yourSettings = "settings.yoursettings"
> var yourSettingsValue = yourSettings.GetValue(dc.State);

Thanks for your response Luhan.
I got the values from custom action dialog context.

 var botSettings = dc.Parent.State.GetValue<BotSettings>("settings");
