### ISSUE TITLE
Ability to Copy / Paste between bots

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4758]
This used to work but does not anymore, and that has quite an impact on my workflow I have to say. Not being able to Copy from Bot A and past to Bot B in two separate tabs is a huge miss now..

**Comment by dmvtech** [comment]
I just tested this and it worked for me. I selected a send response in one bot, used the edit menu at the top, went to another bot and then clicked on a plus sign in the designer canvas and was able to select paste. I'm using the electron app running on Windows. v1.1.1. Any differences in that and how you are able to reproduce the issue?

**Comment by cxbuilders** [comment]
@dmvtech I am running two separate bots in two windows / tabs, whereby I copy components / flows from one to the other. Typically for a new bot this saves a lot of time to copy over common functionality and adjust on the fly for the new bot.

**Comment by a-b-r-o-w-n** [comment]
@cxbuilders If this was working before, it was unintended. Our current guidance is to re-use the same tab to copy and paste actions. 

That being said, we will put this in our product backlog and may work on it in the upcoming releases.

**Comment by cxbuilders** [comment]
It would speed up development a lot. I guess simply using localstorage for this would be sufficient

**Comment by garypretty** [comment]
Added to the backlog for future consideration.

**Comment by hcyang** [comment]
Hi @garypretty, can this issue be closed with more info replying to @cxbuilders ? Thanks.

**Comment by garypretty** [comment]
@hcyang no, this will stay open as a backlog item for future planning consideration.
