### ISSUE TITLE
Implementing a for loop scenario

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#4761]
Hi,

We are providing a multiple input choice action prompt to the user for selecting an option. After user select one of the option from the list we are asking for confirmation whether the option selected is correct or not. If user says no we want to again display the original  multiple input choice action prompt to the user for selecting an option. This can happen multiple time. How can we implement the scenario in bot composer?
Please find the attached zip folder containing the bot sample.
[testing_export.zip](https://github.com/microsoft/BotFramework-Composer/files/5524264/testing_export.zip)

Thanks,
Madan

**Comment by dmvtech** [comment]
@BeheraMadan Thanks for the sample. I'm working on coming up with solutions.

**Comment by dmvtech** [comment]
hi @BeheraMadan I'm still working on this. Thanks for your patience.

**Comment by axelsrz** [comment]
Hey here is an in-progress sample for a similar scenario https://github.com/EricDahlvang/BotFramework-Composer/pull/3 is this helpful @BeheraMadan ?

**Comment by BeheraMadan** [comment]
Hi @axelsrz I have gone through below link you have given and  I saw there is a do while loop screenshot but the I wanted to
try in composer but I don't see any do while loop in composer. Could you please let me know where is do while loop available in composer.

https://github.com/EricDahlvang/AdaptiveDoWhile

![image](https://user-images.githubusercontent.com/70739031/100216244-0eecb500-2f38-11eb-9441-36b798adbdb7.png)

Thanks

**Comment by dmvtech** [comment]
Hi @BeheraMadan 

This is a pull request that has not be merged yet. So you won't see it at this point. You can either implement similar approach yourself with your own custom code/runtime, or you can wait for it to be available in a release. I've exhausted any other out-of-box options.

**Comment by EricDahlvang** [comment]
This is a valid request. However, i'm not sure we will be adding a DoWhile action to the sdk's default actions.  Unfortunately, i also do not know how to add an iterative custom action to Composer.  The .uischema pieces do not seem to be exposed, or this requires a custom ui package?

Please follow along here, where this is currently being discussed:
 https://github.com/microsoft/botbuilder-dotnet/issues/4862

**Comment by BeheraMadan** [comment]
Hi,

For loop &  dowhile loop  not available in the latest composer version. Can we know when will  it be available?

Thanks...

**Comment by EricDahlvang** [comment]
Hi @BeheraMadan 

An example of a Custom Action DoWhile can be found in this draft PR: https://github.com/microsoft/BotBuilder-Samples/pull/3114
