### ISSUE TITLE
Publish bot by CLI

### ISSUE THREAD

**Issue by tannguyen3** [microsoft/BotFramework-Composer#4763]
## Describe the bug

I'm following the document at https://github.com/microsoft/BotFramework-Composer/blob/v1.1.1/docs/archived%20docs/how-to-publish-bot.md 
But on both Web and Desktop version 1.1.1 there is no way I can get the command as shown in the document.

## Version

1.1.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by a-b-r-o-w-n** [comment]
Hello @tannguyen3, those docs have been archived and are not kept up-to-date. Here is the best source of documentation for publishing via the CLI: https://docs.microsoft.com/en-us/composer/how-to-publish-bot

**Comment by dmvtech** [comment]
@tannguyen3 Were you able to get your bot published?

**Comment by tannguyen3** [comment]
in the the article you suggested, there is no CLI to publish the bot.

**Comment by dmvtech** [comment]
hi @tannguyen3 That is correct. Publishing is done from _within Composer itself_. Are you able to follow the steps in that newer document to get it published?

**Comment by tannguyen3** [comment]
Yes, i am. Do we have any plan to support CICD for bot composer?

**Comment by dmvtech** [comment]
I don't believe so, how would you desire/expect this to work? Maybe if you can give more explanation on what you are desiring, we can give better guidance. 

If you are wanting the the declarative resources (.dialog, .lg, .lu, etc) that composer creates, to then be ushered into CICD/bot's pipeline; you should be able to do that. Everything there can be published to the `Composer Dialogs` directory (or whereever appropriate for your actual bot) of your bot. You can have a separate pipeline for your runtime, if that's even needed.

For example, here is my bot folder:
![image](https://user-images.githubusercontent.com/43397658/99419639-2d580e00-28b1-11eb-9ff6-3c394cd6f790.png)

And here is what I have in the azure web app:
![image](https://user-images.githubusercontent.com/43397658/99419749-4cef3680-28b1-11eb-8781-6bc4c36753fd.png)

You can do this publishing in any of the typical approaches; az cli, PowerShell, REST or more. It really depends on your needs.

**Comment by tannguyen3** [comment]
Thanks @dmvtech. Basically I want to setup a CICD pipeline on Azure DevOps to automatically build, deploy and run test for any new changes my team made on bot composer. I'll take a look on the Az Web App to see what we have in there.

**Comment by ruifelixpereira** [comment]
Hi @tannguyen3, did you manage to have a CI/CD pipeline in Azure DevOps for this?

**Comment by peterbozso** [comment]
@ruifelixpereira how about this? https://github.com/microsoft/BotFramework-Composer/tree/main/runtime/dotnet/azurewebapp/Scripts
