### ISSUE TITLE
Repeating a dialog where the only input comes from an AdaptiveCard doesn't work

### ISSUE THREAD

**Issue by nitewulf** [microsoft/BotFramework-Composer#4772]
## Describe the bug

Unless another question is asked to pause the turn before using an AdaptiveCard to collect informaion, Composer will get into a recursive loop: "Recursive loop detected, CollectUserDetails cannot be repeated twice in one turn."

## Version

1.1.1

## Browser

- [x ] Edge

## OS

- [x ] Windows

## To Reproduce

1. Create an adaptive card that looks like this:
# CollectCurrentUserInfo()
[Activity
Attachments = ${json(currentuserinfocardjson())}
]
# currentuserinfocardjson()
- ```{
    "type": "AdaptiveCard",
    "body": [
        {            
            "type": "TextBlock",
            "size": "Medium",
            "weight": "Bolder",
            "text": "Current user information"
        },
        {
            "type": "Input.Text",
            "placeholder": "First Name",
            "id": "firstName"
        },
        {
            "type": "Input.Text",
            "placeholder": "Last Name",
            "id": "lastName"
        },
        {
            "type": "Input.Text",
            "placeholder": "Email",
            "id": "email"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit"
        }
    ]
}```
2. Create a dialog that calls it like the attached screenshot
3. enter anything for the First Name and Last Name.  Leave email empty.  Press 'Submit'

## Expected behavior

I expect the AdaptiveCard to be shown again after pressing submit when the email is missing.

## Screenshots
![image](https://user-images.githubusercontent.com/8270448/98865334-3b350b80-2439-11eb-8e93-802bcbc2028d.png)
![image](https://user-images.githubusercontent.com/8270448/98865394-4f790880-2439-11eb-8deb-03fbffa4f159.png)

## Additional context

If you insert another "Ask a question" before showing the AdaptiveCard the dialog will be repeated correctly. Like this:
![image](https://user-images.githubusercontent.com/8270448/98865594-9ff06600-2439-11eb-8e46-b0aa834a8ce4.png)
![image](https://user-images.githubusercontent.com/8270448/98865620-ad0d5500-2439-11eb-8e04-fd10df1aff5d.png)

**Comment by v-kydela** [comment]
Thank you for the report, @nitewulf 

It looks like you're using a text input to make the dialog end the turn in anticipation of the user filling out the Adaptive Card. I wonder if what's happening is that the text input is skipped because it's prompting for the first name, which the bot already has on subsequent iterations. You should make sure the input is set to always prompt:

![image](https://user-images.githubusercontent.com/41968495/98990241-07142600-24df-11eb-8601-40de669d365d.png)

Because you don't actually want to prompt for text at that point, you might consider using the "End turn" action instead:

![image](https://user-images.githubusercontent.com/41968495/98990365-37f45b00-24df-11eb-9a70-2f8a18058ccd.png)

You'll want some way of making the user click on the Adaptive Card instead of just entering text to continue the dialog. It might be a good idea to just create a loop within the dialog to validate the user's input, rather than repeating the whole dialog.

Does this resolve your issue?

**Comment by nitewulf** [comment]
Thanks for the suggestions.

enabling Always prompt does work.  That's the most direct solution to the weirdness I found and I'll use it.

I thought about a loop, but couldn't figure out how to implement that with the constraints of Composer because the loop has to iterate through an array or values.  There didn't seem to be a way to iterate through an object such as
{
"firstName" : "",
"lastName: " : "",
"email" : ""
}

Maybe I just need to think about how to implement validation with an array some more.

Honestly what would be ideal would be (as you pointed out the text input is collecting in 'firstName') would be if Adaptive Cards were just better integrated like : Ask a question -> Adaptive Card.  Which would store the returned object (turn.activity.value) into whatever property you want.  Currently if you try that you get an error from Composer saying it can't convert an object into a string.

That would also take care of needing "End turn" because Composer would understand it's waiting for the card to be submitted and not waiting for text input.

I also ideally would like to prevent text input but don't see where to insert 'End turn'.  If it goes after the "ask a question (where the card is shown) it's too late because input is paused until a response- either a submit click or a return is detected.  Right?

**Comment by v-kydela** [comment]
@nitewulf - You would use 'End turn' instead of an input

**Comment by nitewulf** [comment]
Fantastic!  Thanks for the tip.  It still doesn't stop me from typing something in and hitting enter.  But at least execution of the logic in the dialog pauses.  Still, this looks like the best way to use an adaptive card at the moment for input.

![image](https://user-images.githubusercontent.com/8270448/99071882-f9af7800-2580-11eb-84a0-2263c0bf0721.png)
