### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Guruji752** [microsoft/BotFramework-Composer#4783]
While Trying to deploy bot to azure through bot composer every time i'm getting same error :
Cannot read property 'name' of undefined
![Screenshot from 2020-11-12 13-31-56](https://user-images.githubusercontent.com/57290099/98912241-d38bc880-24eb-11eb-96b7-7528c817a732.png)

**Comment by a-b-r-o-w-n** [comment]
@Guruji752 what version of Composer are you using?
