### ISSUE TITLE
'Initialize' not working as custom event name

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4784]
Probably a reserved name, but using Initialize as a custom event name does not work. 
![image](https://user-images.githubusercontent.com/49873947/98923477-fca05f00-24d3-11eb-9533-3c2092151f8f.png)

**Comment by a-b-r-o-w-n** [comment]
@cxbuilders are you running into an error when emitting this event? Or when trying to trigger off of this event?

**Comment by cxbuilders** [comment]
@a-b-r-o-w-n nothing happens at all. When changing to anything else it works

**Comment by a-b-r-o-w-n** [comment]
What is the json output of this specific action? I will share with our SDK team to investigate.

**Comment by mrivera-ms** [comment]
@cxbuilders, could you please look at the question above? Thank you.

**Comment by cxbuilders** [comment]
@a-b-r-o-w-n, @mrivera-ms  I cannot reproduce this anymore. At the time I filed this request I was using V1.1.1 
On both 1.2.0 & 1.2.1 the Initialize as event name is working fine. So I guess this is not an issue anymore 👍
