### ISSUE TITLE
Telemetry - Track Event Throw error "Object reference not set to an instance of an objec"

### ISSUE THREAD

**Issue by tannguyen3** [microsoft/BotFramework-Composer#4794]
## Describe the bug
I've added the Telemetry - Track Event to track a customer event to App Insight but the bot throw ""Object reference not set to an instance of an objec" message when it comes to this action. 
This is action info
![image](https://user-images.githubusercontent.com/10743872/98999072-c1665600-24fc-11eb-9f04-84a42bc3a8e8.png)

## Version

Composer 1.1.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
Have you configured your App Insights instrumentation key in the bots settings? Also; you might hit [this issue](https://github.com/microsoft/BotFramework-Composer/issues/4305), so be aware of that (if so, you need to update the `type` in the .dialog file).

**Comment by tannguyen3** [comment]
thank you, @dmvtech. Different messages but same fix. It works now.
