### ISSUE TITLE
Composer persists skills URLs in .dialog files

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#4802]
## Describe the bug

I am simultaneously developing a skill consumer in composer and a skill using code first. 

While developing, I want my consumer to use my local version of the skill on http://localhost:39800/api/messages, but when I deploy the consumer and the skill bots to azure, I want the consumer to use the deployed URL for the skill (e.g.: https://myskill.contoso.com/api/messages) but I don't seem to be able to change my skill URL through configuration and my deployed consumer keeps trying to access my skill using http://localhost:39800/api/messages and not the deployed URL of the skill.

From looking at the code behind of connect to a skill I see that the URL of my skill is persisted in the dialog file and not taken from config:

![image](https://user-images.githubusercontent.com/12264946/99078400-55cbc980-258c-11eb-81f9-2e7d75b28a9b.png)

I also looked at bot settings in composer and I see that the manifest URL is stored there but not the skill URL and I have no way of overriding it.

![image](https://user-images.githubusercontent.com/12264946/99079470-02f31180-258e-11eb-93ce-04497b8a90c5.png)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior

In my scenario, I would like to be able to change the URL of the skill through configuration (in appsettings.json maybe) so I can override this when the bot is deployed. 

Possibly, I would like to be able to set the skillAppId on the UI to something like `=settings.skills['MySkillId'].AppId` and the URL to something like `=settings.skills['MySkillId'].skillEndpoint` so these values can be taken from config.

Let me know if you need more details.

## Additional context

In code first consumers, we normally store the skill information in appsettings.json: and then we use the information there to initialize the beingskill dialog instance:

![image](https://user-images.githubusercontent.com/12264946/99079076-6af52800-258d-11eb-92aa-20a97f8af037.png)

**Comment by srinaath** [comment]
@gabog The latest release of Composer (1.2) will follow the pattern you have mentioned above.

This is the ticket and the PR that did the change. #4032

**Comment by gabog** [comment]
This is great news @srinaath, I will close this one and give 1.2 a try.

Thanks
