### ISSUE TITLE
Popup tooltip text truncation

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#4811]
![Screen Shot 2020-11-13 at 12 01 31 PM](https://user-images.githubusercontent.com/13004779/99129876-a7dc1180-25c3-11eb-8cee-6e16a3410340.png)

  
 

![Screen Shot 2020-11-13 at 12 01 35 PM](https://user-images.githubusercontent.com/13004779/99129879-a90d3e80-25c3-11eb-9407-7af39bb8350b.png)

![](https://user-images.githubusercontent.com/13004779/99434422-a1031680-28c3-11eb-9782-c665be7fb220.png)

All tooltips are being truncated here. After speaking to @sangwoohaan it looks like the text needs to wrap to the next line rather than getting truncated.

**Comment by srinaath** [comment]
@zhixzhan  can u take a look at this?

**Comment by zhixzhan** [comment]
@srinaath Sure, I'm fixing this with some other issue, will update it today.
