### ISSUE TITLE
Error: Command failed: dotnet build

### ISSUE THREAD

**Issue by Guruji752** [microsoft/BotFramework-Composer#4812]
i'm  trying to run simple echobot but everytime it giving **Error: Command failed: dotnet build** 
![Screenshot from 2020-11-14 11-23-56](https://user-images.githubusercontent.com/57290099/99140941-11175f80-266c-11eb-9c59-5642fdf929d3.png)
![Screenshot from 2020-11-14 11-24-57](https://user-images.githubusercontent.com/57290099/99140944-14aae680-266c-11eb-8804-8c696d52afc3.png)

But it was working fine yesterday. I tried everything even reset by ubuntu and install everything again , but issue is still there

**Comment by mrivera-ms** [comment]
@Guruji752 what version of Composer are you using? Could you upload your bot assets?

**Comment by luhan2017** [comment]
@Guruji752  Is it possible that you reset your NugetPackages sources? which cause failure for the package update? Could you try to run dotnet build under your BotFramework-Composer\runtime\azurewebapp folder?

**Comment by Guruji752** [comment]
> @Guruji752 Is it possible that you reset your NugetPackages sources? which cause failure for the package update? Could you try to run dotnet build under your BotFramework-Composer\runtime\azurewebapp folder?

i run dotnet build but it's not working still giving same error

**Comment by Guruji752** [comment]
> @Guruji752 what version of Composer are you using? Could you upload your bot assets?

the latest one

**Comment by Guruji752** [comment]
i run sudo apt install in my machine , actually it was problem , npm install and npm install --only was not able to run

**Comment by mgbadebo** [comment]
I am getting the same issue. How did you reseolve this?

**Comment by Guruji752** [comment]
step1 : open your bot in bot composer then go to settings (in bottom left) then to go to run config 
step2 : In run config turn on Use custom runtime and  click on Get a new copy of the runtime code we will get option to select c# and js(preview) .
step3 : select js(preview) and run the bot ,it would give the cause of your error 

in my case 'npm'' was missing which were creating problem to run npm install or npm install --only command.
if it is the same error at your end too then run the command 'sudo apt install npm'.

**Comment by mgbadebo** [comment]
Thank you.

I had to uninstall .Net 5, reboot and install to .Net 3.41

________________________________

**Comment by TheBestBirth** [comment]
Hi @Guruji752 
for some reason i do not have "Run Config" in setting (i am using Composer ver. 1.3.0) is it possible or i am doing something wrong here ?

**Comment by Guruji752** [comment]
not sure but it might be the problem of version , could you share the screenshot of your settings

**Comment by fredcsfaria** [comment]
I have the same issue.   The JS runtime message in Bot framework  is:
Command failed: npm install && npm install --only=dev npm WARN deprecated @types/moment-timezone@0.5.30: This is a stub types definition. moment-timezone provides its own type definitions, so you do not need this installed. npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410.  

But if I run "dotnet build"  in  C# runtime in runtime\azurewebapp folder  I get only warnings and none error. But from Bot Framework GUI I get the message:  "Command failed: dotnet build"

**Comment by ShrijithR** [comment]
@Guruji752 
This is what I get after installing npm latest version for Windows. 
Start bot failed

Command failed: npm run build 'tsc' is not recognized as an internal or external command, operable program or batch file. npm ERR! code 1 npm ERR! path D:\Python\ThinkBridge\Empty\EchoBot-0\runtime npm ERR! command failed npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tsc npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\shrij_74k4zjf\AppData\Local\npm-cache\_logs\2021-02-17T13_25_18_568Z-debug.log

**Comment by Shameeritc** [comment]
This worked for me
