### ISSUE TITLE
Unable to publish my Bot to PVA 

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/BotFramework-Composer#4813]
## Describe the bug

After creating a profile, I couldn't publish my Bot to Power Virtual Agents. 

## Version

1.2.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Publish
2. Select Publish Profile
3. Publish to Selected Profile
4. It keeps on progressing... with no luck!

## Expected behavior

The bot should have published.

## Screenshots

![image](https://user-images.githubusercontent.com/16351038/99141982-b64e2a00-26a4-11eb-9536-49c4a66dfe9d.png)

**Comment by arafattehsin** [comment]
Further more, I created a new PVA Bot and try to integrate with that. It showed me the data but failed with the below screenshots;

![image](https://user-images.githubusercontent.com/16351038/99312715-8e341600-28b2-11eb-98ab-3d7d2e2340e5.png)

Logs;

---
{
  "code": "FileIsIgnored",
  "range": null,
  "severity": "Warning",
  "source": "settings/cross-train.config.json",
  "message": "File 'cross-train.config.json' is unknown for the system and was ignored during the import."
}
---

---
{
  "code": "FileIsIgnored",
  "range": null,
  "severity": "Warning",
  "source": "generated/interruption/AMATransferBot.en-us.qna",
  "message": "File 'AMATransferBot.en-us.qna' is unknown for the system and was ignored during the import."
}
---

---
{
  "code": "FileIsIgnored",
  "range": null,
  "severity": "Warning",
  "source": "dialogs/CheckBalanceDialog/knowledge-base/en-us/CheckBalanceDialog.en-us.qna",
  "message": "File 'CheckBalanceDialog.en-us.qna' is unknown for the system and was ignored during the import."
}
---

---
{
  "code": "FileIsIgnored",
  "range": null,
  "severity": "Warning",
  "source": "generated/interruption/CheckBalanceDialog.en-us.qna",
  "message": "File 'CheckBalanceDialog.en-us.qna' is unknown for the system and was ignored during the import."
}
---

---
{
  "code": "FileIsIgnored",
  "range": null,
  "severity": "Warning",
  "source": "generated/luis.settings.composer.westus.json",
  "message": "File 'luis.settings.composer.westus.json' is unknown for the system and was ignored during the import."
}
---

---
{
  "code": "DialogDoesNotMatchAppSchema",
  "range": null,
  "severity": "Error",
  "source": "AMATransferBot.dialog",
  "message": "Dialog 'AMATransferBot.dialog' does not match the app.schema. Details: 'JSON is valid against no schemas from 'oneOf'. Path 'recognizer', line 71, position 39. Inner errors:\r\n  Invalid type. Expected Object but got String. Path 'recognizer', line 71, position 39.'"
}
---

---
{
  "code": "RecognizerTypeIsNotSupported",
  "range": null,
  "severity": "Error",
  "source": "dialogs/CheckBalanceDialog/CheckBalanceDialog.dialog",
  "message": "The recognizer type 'Microsoft.CrossTrainedRecognizerSet' is not supported."
}
---

---
{
  "code": "DialogDoesNotMatchAppSchema",
  "range": null,
  "severity": "Error",
  "source": "dialogs/CheckBalanceDialog/recognizers/CheckBalanceDialog.lu.qna.dialog",
  "message": "Dialog 'dialogs/CheckBalanceDialog/recognizers/CheckBalanceDialog.lu.qna.dialog' does not match the app.schema. Details: '$kind should be Microsoft.AdaptiveDialog'"
}
---

**Comment by cwhitten** [comment]
@arafattehsin the default schema used in Composer is not entirely compatible with Power Virtual Agents. They have their own schema that they provide and validate against when you publish. See the following blogpost for explanation and tutorials on how to publish. https://powervirtualagents.microsoft.com/en-us/blog/power-virtual-agents-integration-with-bot-framework-composer-is-available-in-public-preview/

**Comment by arafattehsin** [comment]
Hi @cwhitten - I would delightfully close this issue as I have got the way to make it working. Blog post coming 🔜

![image](https://user-images.githubusercontent.com/16351038/99315755-3f3caf80-28b7-11eb-8eb7-7064e25b47d9.png)
