### ISSUE TITLE
ReplaceDialog on child dialog error: Value cannot be null. (Parameter ‘dialogId’)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#4816]
## Scenario:
Top dialog calls child dialog
Child dialog replaces itself with top dialog
- Cannot zip sample cause export is broken.

## repro images

![image](https://user-images.githubusercontent.com/8867670/99161249-28267380-26a5-11eb-8dd7-fb35133a3730.png)

![image](https://user-images.githubusercontent.com/8867670/99161254-3a081680-26a5-11eb-9802-d41604addf22.png)

![image](https://user-images.githubusercontent.com/8867670/99161257-45f3d880-26a5-11eb-8370-6e3905166063.png)

**Comment by cwhitten** [comment]
@scheyal how different is is your setup compared to the "Dialog Actions" sample, which exercises Replace Dialog a bit, and is working fine for me on the 4.11.0 runtime packages.

**Comment by scheyal** [comment]
It repros once you go through ~2 cycles. 
Also, repos with all variations of using begin dialog in place of replace dialog.
Repro shared with provided private bits (with fixed zip packaging).

**Comment by tonyanziano** [comment]
@scheyal can you add the zipped assets to this issue or upload it somewhere where we can access it to repro & debug?

**Comment by scheyal** [comment]
Another scenario that illustrates this:

* Setup Topdialog, child dialog A, child dialog B
* On prompt child dialog A replaces itself with child dialog B
* On promopt child dialog B replaces itself with child dialog A

**Comment by scheyal** [comment]
zip export is (was) broken - here's a manual zip.
[bugtest.zip](https://github.com/microsoft/BotFramework-Composer/files/5563983/bugtest.zip)

**Comment by garypretty** [comment]
Adding comments here that I shared with @scheyal offline that might help.  You probably want to update the scenario and retest using the following points.

From my initial glance over the pattern, I would need to validate but I think what you need is.

•	You top dialog should have a call to RestartDialog once you call whichever child dialog the user chooses, so that when the child dialog returns, it shows the menu again.
•	If you are in a child dialog (LUIS or Orchestrator in your case) and you want to show the menu again, you just call EndDialog.  This will pop the dialog off the stack and return back to root, which will loop to show the menu.
•	Only call ReplaceDialog if you want to replace with a sibling – if you call ReplaceDialog for the TopDialog, you essentially end up with TopDialog being a child of itself.

**Comment by scheyal** [comment]
(FYI no variation per above worked)

**Comment by venegasmi** [comment]
Hello, I'm having this exact issue when restarting the dialog as well. 

I have tried the actions suggested in this thread but none have solved the problem yet.
Once it goes through 2 cycles, I get an error: Value cannot be null (Parameter 'dialogId')

Is there any fix for this yet?

**Comment by ShwetaTemkar-10** [comment]
@venegasmi did you find any solution to this problem? even I am facing the same problem after 2 cycles

**Comment by ShwetaTemkar-10** [comment]
@scheyal and @venegasmi did you'll find any solution to this issue? Even I am facing the same error after 2 cycles

**Comment by Samirun** [comment]
Hello, I had got this one too. any solution?

**Comment by ashokdevlabs** [comment]
Hello, I got this issue too, while calling dialog 2nd time.
Has anyone got any solution yet?

**Comment by michaelstiben** [comment]
Hi. I got this issue too. I tried using "replace dialog", "begin new dialog" and "cancel dialog" but any of this function for me.
Is there any workaround about this?

**Comment by kalebk** [comment]
I am having the same issue.. was thinking "replace this dialog" should end the current dialog and start a new one which is specified. Is that not correct?

**Comment by kalebk** [comment]
I was able to work around in my scenario by setting a variable `user.tryAgain` in the child dialog, then ending the child dialog and using the variable in the parent dialog to either start over or move on.

**Comment by garypretty** [comment]
@EricDahlvang @mrivera-ms can we take a look at this issue, once we have our priority R12 items out of the door, please?

**Comment by praneeth1987** [comment]
@kalebk  could you please elaborate your workaround? I am facing same issue but could not get thru your WA.

**Comment by anmolgandhi007** [comment]
Is there any update when can we expect the fix to come up? I am facing similar issue with replace dialog. Its impacting the process/timeline of development and the bot to move to production. Please provide an update. Thanks!

**Comment by tamasschmolcz** [comment]
Is there any update?

**Comment by Danieladu** [comment]
hi @scheyal , sorry for the delay reply. This issue has been fixed by this PR: https://github.com/microsoft/botbuilder-dotnet/pull/5072
Please update your SDK to >= 4.12 version to achieve the fix.
Thanks!

**Comment by boydc2014** [comment]
> hi @scheyal , sorry for the delay reply. This issue has been fixed by this PR: [microsoft/botbuilder-dotnet#5072](https://github.com/microsoft/botbuilder-dotnet/pull/5072)
> Please update your SDK to >= 4.12 version to achieve the fix.
> Thanks!

Thanks @Danieladu helping investigating this.  @tamasschmolcz Please try the latest composer version. Closing this for now, free feel to reopen if this hasn't solve this issue.

**Comment by ambuj74** [comment]
Hi @boydc2014 ,  I am using botframework composer version 2.1 stilll i am facing the same issue if trying to call the same dialog after the second time, could you pplease help me on this.
