### ISSUE TITLE
Create dialog will show alert

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#4821]
## Describe the bug
![alert](https://user-images.githubusercontent.com/39758135/99225869-b9235900-2823-11eb-96fb-8b642d167715.gif)

## Version
main

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Create a new locale. Set it as the default. Try adding a dialog now.

**Comment by tonyanziano** [comment]
@beyackle can you please take a look at this?

**Comment by beyackle** [comment]
I'll take a look. It does successfully create the dialog, and that's not the usual kind of alert we use.
