### ISSUE TITLE
Updated composer does not create "project file"

### ISSUE THREAD

**Issue by isakalmq** [microsoft/BotFramework-Composer#4823]
## Describe the bug

When visiting an old project from a previous version of composer I get the error 

"Error
If this problem persists, please file an issue on GitHub
Details
Bot project file does not exist"

## Version

1.2 (4205387) with 1.1(065d065) being the previous verison.
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [x] Ubuntu

## To Reproduce

1. Open version 1.1
2. Create any new project.
3. Close 1.1
4. Open version 1.2
5. Open said project
6. Get error

## Expected behavior

I expect it to create the necessary files in this new update

**Comment by cwhitten** [comment]
Hi @isakalmq. This is unexpected. Can you share your project with me privately by emailing the directory to christopher(dot)whitten(at)microsoft.com?

**Comment by isakalmq** [comment]
This bug exists for all projects created in 1.1 for me, it doesn't seem to be project specific. I'll email you a project anyways if you want me to

**Comment by flaviobogila** [comment]
Delete directory **AppData\Roaming\BotFrameworkComposer** and try again, it works for me!

**Comment by viivalerio** [comment]
Had the same issue this morning. Big thanks to @flaviobogila it also worked here! 👏 👏

**Comment by johnataylor** [comment]
@cwhitten any update on this?

**Comment by johnataylor** [comment]
closing with workaround https://github.com/microsoft/BotFramework-Composer/issues/4823#issuecomment-729090439
