### ISSUE TITLE
editing issue (accessibility) in LU/LG table view

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#4825]
## Describe the bug
In LG table view, I can not hit "enter" if the focus is in the response for the LG template
![image](https://user-images.githubusercontent.com/43408889/99257245-afb0e580-2851-11eb-80a3-664444c90579.png)

In LU table view, when I hit the  "up arrow" inside the table view for one luis intent, it will go to other component instead of the upper line in Manaco editor.  
![image](https://user-images.githubusercontent.com/43408889/99257679-5dbc8f80-2852-11eb-9f17-68dfd38c7120.png)

## Version

Composer 1.2

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

**Comment by tonyanziano** [comment]
@lei9444 can you please take a look at this?

**Comment by zhixzhan** [comment]
> In LU table view, when I hit the "up arrow" inside the table view for one luis intent, it will go to other component instead of the upper line in Manaco editor.

For item 2 there is a fluentui issue track

https://github.com/microsoft/fluentui/issues/12177
