### ISSUE TITLE
Change nomenclature of "Trigger" to "Topic" 

### ISSUE THREAD

**Issue by managedcoder** [microsoft/BotFramework-Composer#4832]
## Nomenclature Change

I'd like to suggest that "Trigger" be changed to "Topic".  IMHO, the word "Trigger" in the context of how its used and applied in Composer speaks more to its implementation than it does to semantically what it is.  Trigger is a reference to how a flow is actuated rather than what the flow represents.  In the real world, dialogs are conversations and humans in a conversation will discussion various topics and using those terms in that ways in Composer will model the real world better.  

If "Topic" were substituted for "Trigger", Dialogs could be said to represent a grouping Topics that collectively engender the sematic of the name chosen for that Dialog.  You would talk about build bots to handle conversations that address the various topics that are important in a given business scenario.  The word "Trigger" does not map well to the mental model of how people think about bots and what their bot needs do in a given solution which creates unnecessary cognitive distance.  I think that beginners will end up having to mentally map this like, "Triggers are what I've come to understand are topics (or whatever their target word is which I convinced won't be "Trigger").  Why not switch to a nomenclature that does not require this mapping to be learned.

Even for the events that are part of a Dialog, like "Conversation Update" for example, you can still think about it as a "Topic"... so I'd have a Greeting topic, for example.  Now I can say that Topics have different ways of being triggered... they can trigger by conversations events or be triggered when certain Intents are recognized.  In the case of Greeting... its a topic that just happens to be triggered by an event but it addresses the topic of how to greet a user in that conversation.

Example:  If I am building a bot to take pizza orders so my employees can focus on pizza production, I want my bot to be able to handle conversations about ordering pizza which can be multifaceted.  Now I can start to think about the various topics that my bot needs to be able to handle and I can mentally group them into conversations.  So I'll have a number of topics that can be grouped into a dialog about ordering pizza and other topics will group into a dialog about methods of delivery, or about my current promotional offers, etc.

## Solution

Change the nomenclature of "Trigger" to "Topic" in both the Composer tooling and in the doc

**Comment by mareekuh** [comment]
Hello Russ,

A trigger in Composer and the Bot Framework SDK has 2 parts: the event and the event handler.

The event is the 'signal' that initiates a dialog. For example, the user says something (user input/intent).
For a dialog to execute the designed actions, it needs to to ‘receive’ that signal it needs an event handler (trigger type) to capture and respond to the event.
For example, the user said something. The recognizer maps what the user said to an intent (event), and the dialog that can receive this event (eg: has an event handler for this intent (‘intent recognized’), it fires will execute the designed actions.

When suggesting to replace the term ‘trigger’ with topic I think you are referring to the 'event' part of the trigger (vs the event handler). This is what our sister app, Power Virtual Agents does as well: A topic in PowerVA has trigger phrases—phrases, keywords, or questions that a user is likely to type that is related to a specific issue —and conversation nodes. The nodes define how a bot should respond and what it should do.

While ‘Topic’ as a term might work for user-input based events, it would not be a good fit to describe events/triggers that occur internal to the dialog such as dialog events or activities internal to the dialog (dialog started, cancelled, conversation ended, user is typing etc).

Hope this helps. Thank you for your suggestion and taking the time and effort to share your feedback!

Regards,
Marieke
