### ISSUE TITLE
Publish Fails after Upgrade to 1.2.0

### ISSUE THREAD

**Issue by CopenhagenJames** [microsoft/BotFramework-Composer#4836]
Publish Now Fails after Upgrade.

## Describe the bug

After upgrading to the new version 1.2.0 when I attempt to publish I get an error: "Expected signal to be an instanceof AbortSignal"

## Version

1.2.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Publish'
2. Click on 'Publish profile'
3. Publish errors out

## Expected behavior

As before successful publish before upgrading to v1.2.0

## Screenshots
![Capture](https://user-images.githubusercontent.com/35306898/99315053-0ad1e080-2830-11eb-84f2-49adb040073d.PNG)

## Additional context

This was working in the previous version.  Once I upgraded to v1.2.0 the publish with no changes now fails.

**Comment by cwhitten** [comment]
this has been addressed in 1.2.1
