### ISSUE TITLE
Form dialogs: Composer goes blank when "Dialog begins" trigger is selected from dialog tree

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#4838]
## Describe the bug

After the form dialog has been generated, all the triggers are visible from the tree except for "Dialog begins". This trigger makes the entire Composer screen go blank, including navigation. 

## Version

Using the feature/form-dialogs branch, built locally 11/16.

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. **Install Form Dialogs** by going to gear icon at the bottom the left nav, clicking Application Settings, and under Preview Features, check "Form Dialogs".
 
2. This should add the "Forms" section to the end of the side nav shown by an icon that looks like a table. **Click on the Form section.**

3. **Create a new form schema** by pressing the + icon under "Schemas" and giving the schema a name.

4. **Add or Import a schema**. I got this error both when I created a schema by hand and when I imported the schema from the samples here: https://github.com/microsoft/BotBuilder-Samples/blob/main/experimental/generation/docs/example-schemas/sandwich.schema

5. **Generate the form dialog dialog** by pressing the Genereate dialog button.

6. When the progress indicator goes away, **navigate to the Design section and select the form dialog** (it will have the same name as your form schema). 

> If you click on a trigger, the flow diagram should appear on the right, like this:

> ![image](https://user-images.githubusercontent.com/39317542/99320352-4d8bbc80-2820-11eb-90f8-49c016db103a.png)`

7. **Select the "Dialog begins" trigger. The Composer screen goes blank:**
![Screenshot (656)](https://user-images.githubusercontent.com/39317542/99320453-8461d280-2820-11eb-90c7-5390ea7dc2ce.png)

## Expected behavior

You should be able to the see the triggers and actions on the canvas as with any other trigger. Or, if there is an error that makes this impossible, an error message should appear, but the navigation should not disappear. Without the navigation, there was no way to get of this state but to edit the URL in the browser window directly.

**Comment by hatpick** [comment]
This issue is fixed in the main branch.
