### ISSUE TITLE
Can't publish my Bot after the Update

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/BotFramework-Composer#4843]
## Describe the bug

I was able to publish my bot using existing Azure resources but after the update 1.2.0, I am not able to do so. 

## Version

1.2.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Publish
2. Click on Publish Profile
3. Select Publish to selected Profile.
4. It gives an error as described below in the screenshot.

## Expected behavior

It should have been published without any issues.

## Screenshots

![image](https://user-images.githubusercontent.com/16351038/99340731-b173bb00-28dc-11eb-9fb7-9572201e94c5.png)

## Additional context

This is my publish profile;

`{
  "accessToken": "",
  "hostname": "<my web app's name>",
  "luisResource": "<LUIS prediction resource name in Azure>",
  "settings": {
    "luis": {
      "endpointKey": "<LUIS authoring key from Azure>",
      "authoringKey": "<LUIS prediction key from Azure>",
      "region": "westus"
    },
    "qna": {
      "subscriptionKey": "<sub id>",
      "knowledgebaseid": "<kbid>",
      "endpointKey": "<qnaendpoint>",
      "hostname": "https://myqnaurl.azurewebsites.net/qnamaker",
      "qnaRegion": "westus"
    },
     "MicrosoftAppId": "<app Id>",
    "MicrosoftAppPassword": "<app password>"
  }
}`

**Comment by cwhitten** [comment]
@arafattehsin we just published 1.2.1 that should fix this. can you try again?

**Comment by arafattehsin** [comment]
This is sweet! Fixed. Thank you @cwhitten and the team for a quick fix. 
![image](https://user-images.githubusercontent.com/16351038/99348345-804fb680-28ed-11eb-806b-66694c5fcbc4.png)
