### ISSUE TITLE
The Luis key error in Project tree incorrect after refresh the page

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#4845]
## Describe the bug
![skillerror](https://user-images.githubusercontent.com/39758135/99349247-7a9aa680-28d6-11eb-9d13-ab9c53b011b2.gif)

## Version
bot project branch

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Additional context
I think we need to merge settings in selector. So other components can get the whole settings from selector

**Comment by srinaath** [comment]
@liweitian  can u take a look at this?

**Comment by liweitian** [comment]
@srinaath The storage of the structure of luis/qna key in browser localStorage is changed. Will have a look.
