### ISSUE TITLE
Form dialogs, schema editor, list property type field: accept a comma-separated list?

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#4846]
## Describe the bug

In form scheme editor, under the property type list, the "Accepted values" field requires that you manually type each item and hitting Enter. Can it be enabled to accept pasting (or typing) a comma-separated list or tab separated list?

## Version

form dialogs

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Forms'
2. Click on 'Add property'
3. In Property type, choose "list".
4. The "Accepted values" field appears. You must type in each item and hit Enter, which is a lot of typing for a long list. Example:
![image](https://user-images.githubusercontent.com/39317542/99350490-5fd31e00-2853-11eb-8385-5126cd5ed9a4.png)

## Expected behavior

Can we allow the user to paste or upload a list separated by commas, tabs, or newlines?

**Comment by mewa1024** [comment]
In the four user studies so far, all participants expected to use a comma separated list. Either they expected that typing a comma would convert the words separated by commas into pills or they expected it to happen when they were done typing. Can we change the help text to "Type one item or a comma-separated list of items and press Enter".

(@xiyangdesign what do you think?)

**Comment by mewa1024** [comment]
Adding labels "Type: Bug" and "R12" since this has come up consistently in user studies.

**Comment by xiyangdesign** [comment]
Yes, this help info would be great. It also appears that users sometimes don't see the placeholder help text:) 
- but yes, for now, let's change the placeholder text
- in the long run, maybe we could introduce this in onboarding? like the teaching bubbles for newly released features? :-)
