### ISSUE TITLE
Response options are duplicated and/or end up under the wrong response

### ISSUE THREAD

**Issue by ivo-ranj** [microsoft/BotFramework-Composer#4848]
When adding response options in Composer, they may under certain circumstances end up duplicated, and/or listed under a different response.

## Version

1.2.1

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Steps to reproduce the behavior (symptoms may vary per execution):

1. Create a new empty project in Composer
3. Create four responses after each other, all with a single response (I used 1, 2, 3, 4 so it's clear when something breaks).
4. Save and re-open dialog
5. Add a second option to the four responses (added 11, 22, 33, 44)
6. Save and re-open dialog
7. Number 4 now has an extra option, e.g. the number 3 or 4. It looks like they are duplicated from the first row or copied from another response.
9. Add a third set of options for the responses (added 111, 222, 333, 444)
10. Save and re-open dialog
11. Nothing changed, the only anomaly is still the extra 4 from step 7
12. Remove all but the first option from all dialogs. Now left with the same as step 1.
13. re open project
14. Response 4 now has an extra line, 444 is still there.

## Expected behavior

The options remain intact and as entered.

## Screenshots

![2020-11-17 10_28_53-Bot Framework Composer (v1 2 1)](https://user-images.githubusercontent.com/10220878/99371935-d574d380-28bf-11eb-85b9-c524bf726bcd.png)
![2020-11-17 10_31_56-Bot Framework Composer (v1 2 1)](https://user-images.githubusercontent.com/10220878/99372315-4320ff80-28c0-11eb-8cc6-0ec562c05c13.png)

## Additional context

- Doing this multiple times gives different results.
- Sometimes there are duplicate id's in the `.lg` file of the dialog, this gives an error in Composer.
- The test described above has also been done with 3, 5 and 6 different responses. All showed some form of copied content after a few edits/re-opens.
- There also have been instances where text was copied from one cell to another.
- The re-opening of the project _shows_ the errors, but the errors already occur when editing the dialogs. This can be verified in the Bot Responses tab.
- Fixing the `.lg` of the dialog does not stop it from breaking again in the future.

**Comment by cwhitten** [comment]
thank you @ivo-ranj for the report. @lei9444 can you look at this?

**Comment by boydc2014** [comment]
Thanks @ivo-ranj.  After several tries, we did get a stable repro of this. We are narrowing down to a particular LG api call now, seems like in certain case, LG api is updating the wrong offset on the original file. We are working with LG member to investigate this.  We expect to get a fix very soon.  cc @cwhitten.
