### ISSUE TITLE
Composer is very slow with 2 chit-chats Q&A

### ISSUE THREAD

**Issue by obayani** [microsoft/BotFramework-Composer#4849]
## Describe the bug
I created a KB using 2 chit-chats (pro and friendly) and when I try to access Q&A menu in the Bot Framework Composer (using v1.2.1) it is extremely slow. Composer hangs for 1 min before I can do anything. It seems that long list of Q&A pairs degrades the performance.

Before v1.2.0 it was working fine.

## Browser

- [ ] Electron distribution
- [x] **Chrome**
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] **Windows**
- [ ] Ubuntu

## To Reproduce

1. Import a KB with at least 2 chit-chats from https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/concepts/best-practices?tabs=v1
2. Click on 'QnA' menu in the left pane of Bot Framework Composer
3. App will hang for at least 30 to 45 seconds

## Expected behavior

App should be responsive even with long list of Q&A pairs.

**Comment by cwhitten** [comment]
thank you @obayani for the report. we'll look into this. @zhixzhan can you please investigate?

**Comment by zhixzhan** [comment]
@cwhitten Sure, will take a look soon.
