### ISSUE TITLE
Invalid warning and errors notifications showing up

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#4854]
![Screen Shot 2020-11-17 at 10 46 45 AM](https://user-images.githubusercontent.com/13004779/99435957-b1b48c00-28c5-11eb-9d04-c2220d6ade98.png)

![Screen Shot 2020-11-17 at 11 11 22 AM](https://user-images.githubusercontent.com/13004779/99436083-db6db300-28c5-11eb-9f4d-8f11a08f5964.png)

1. With the new skills workflow if the "Composer Local" endpoint is chosen we dont need to check for an empty endpoint url in the settings.
2. Missing skill manifest should not be a warning shown on the Root Bot
3. A warning for missing MsAppID is shown. This warning is not required. An MSAppID or AppPassword is no longer required to call skills

**Comment by zhixzhan** [comment]
I already fixed the 2rd item.
```
2. Missing skill manifest should not be a warning shown on the Root Bot
```

Will sync with @lei9444 see how to address them all.
