### ISSUE TITLE
UI: "Run once" in the trigger details --what's the default value when blank?

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#4863]
## Describe the bug

When you select a trigger, in the details pane there is a setting for "Run once" that looks like a boolean that is blank. Is the default true or false? (and what does this setting do?)

## Version

local build, main branch from 11/17

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to the Design section.
2. Select any trigger in the tree. 
3. Look in the details pane on the far right side:
![image](https://user-images.githubusercontent.com/39317542/99463566-e850cd80-28ea-11eb-840b-f665f8aba9e7.png)

## Expected behavior

**If this is a boolean**, I'd expect the default is either true or false, but the field is blank. Then I'd expect the tooltip to tell me what run once means (once per conversation? once per user?) and what the default value is and ideally a link to documentation about this setting.

**If this *not* a boolean**, then I would expect the type in the input field to be something other than **"y/n"**.

## Screenshots
Here's the input, showing the "y/n" type:
![image](https://user-images.githubusercontent.com/39317542/99463957-cc016080-28eb-11eb-832e-445a906f44f9.png)

Here's the tooltip:
![image](https://user-images.githubusercontent.com/39317542/99463710-3960c180-28eb-11eb-8ed3-5fa03ed65d39.png)

**Comment by mewa1024** [comment]
The "Condition" field also has "y/n" as the type in the UI--is it supposed to be a boolean?

**Comment by luhan2017** [comment]
@mewa1024 , condition and runOnce are both optional fields, if you leave them empty, you won't see them in the dialog file.

**Comment by mewa1024** [comment]
So for Run Once, does that mean if it is not specified (doesn't appear in the .dialog file) that the default is that the trigger does not run once? Can that be added to the tooltip?

**Comment by luhan2017** [comment]
@mewa1024 , sure, thanks for the feedback, will follow up with @zxyanliu on this.

**Comment by tdurnford** [comment]
@cwhitten Should we handle this change in the SDK?
