### ISSUE TITLE
Style seems off when a target is selected and the context menu is opened in the ProjectTree

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#4882]
Actual
![Screen Shot 2020-11-18 at 2 44 33 PM](https://user-images.githubusercontent.com/13004779/99597633-21ea0d00-29ad-11eb-9083-fa59c0e98e63.png)

Expected:
![Screen Shot 2020-11-18 at 2 43 53 PM](https://user-images.githubusercontent.com/13004779/99597717-434af900-29ad-11eb-9333-f97f4ec538f3.png)

The hover, pressed style on the ellipsis seems to be wrong too

@sangwoohaan

**Comment by beyackle** [comment]
This is my fault, and a one-line fix I'll get to shortly (after I fix the breadcrumb regression).
