### ISSUE TITLE
Publishing issue: lingering .lu content produces side-effects when not in active use

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#4884]
If a user authors .lu and then switches the recognizer for the dialog to something non .lu based like regex, the inference logic sees the .lu content and includes it in its publishing mechanism even when the dialog is not currently configured to use it. 

The build/publishing process should only include .lu and .qna content when the dialogs they are associated with actively depend on it.

**Comment by cwhitten** [comment]
@lei9444 this has been addressed, right? please close if so.

**Comment by cwhitten** [comment]
ping @lei9444

**Comment by lei9444** [comment]
I have a PR #5674 to fix the qna publish, and the lu publish already support this mechanism
