### ISSUE TITLE
Form dialog recognizer type (.lu) is overwritten when you make any changes in Composer to *.lu.qna

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#4888]
## Describe the bug

A form dialog is generated with the recognizer of type **.lu**, but editing the dialog in Composer seems to change the recognizer to **.lu.qna** causing the bot to give an "Object reference not set to an instance of an object" error.

## Version

main branch, pulled November 18

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Turn on the form dialog UI by going to **Settings > App settings > Preview features** and checking **"Form dialogs."**
2. Create a new bot *(I used the the EchoBot template).*
3. Create a form by clicking on the table-looking icon in the side nav, pressing the **+** button in the Schema pane, and adding a name. Add properties *(or you can import a sample form schema form here: https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/generation/docs/example-schemas)*
4. Generate the dialog by pressing the **"Generate dialog"** button.
5. Connect the form dialog to the main dialog *(I added a new trigger that used a Begin Dialog node to start the form dialog)*.
6. Start the bot. The bot should work fine.
![image](https://user-images.githubusercontent.com/39317542/99617716-ba47b800-29d4-11eb-8aaf-b2b01ddbfa60.png)

7. Edit the form dialog *(I added a trace event to the Dialog started trigger)*.
8. Restart the bot. Now there is an error:
![Screenshot (742)](https://user-images.githubusercontent.com/39317542/99618129-a2246880-29d5-11eb-813b-288666788781.png)

I removed the trace event from the Dialog started trigger and restarted the bot, and the error still appeared. Then I compared the .dialog file with a copy I made before making any changes to it, and only the recognizer line was different:

> ![Screenshot (743)](https://user-images.githubusercontent.com/39317542/99617975-4e198400-29d5-11eb-9ac8-9b160a0f3e39.png)

Removing the .qna and restarting the bot removed the error.

> ![Screenshot (747)](https://user-images.githubusercontent.com/39317542/99618054-80c37c80-29d5-11eb-9944-6c1945e765dd.png)

## Expected behavior

Either the recognizer for the form dialog should start off as .lu.qna or Composer should not change it.

**Comment by mewa1024** [comment]
@boydc2014

**Comment by boydc2014** [comment]
> @boydc2014 Chris suggested you might have more context for this.

Yes. The conversation to .lu.qna is expected, because the convention used in Composer is CrossTrainedRecoginzerSet(.lu.qna.dialog).

So i guess this issue is not because .lu => .lu.qna, is more because the correct structure .lu.qna isn't correctly generated. 

I will ask @zhixzhan to look at this soon.

**Comment by mewa1024** [comment]
@chrimc62 adding you for visibility.
