### ISSUE TITLE
multiple choice action prompt is not working properly after updating to latest composer version

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#4890]
Hi,
We have a bot solution created using composer version 1.0.2. We updated composer version to 1.2.1.
But while implementing the new logic in our updated bot solution(latest composer version) we found an issue. We are
trying to create a new multiple input choice action with some choices for selection. But when we run the bot and click on any of the choice, bot is giving error "Sequence contains no elements"

![image](https://user-images.githubusercontent.com/70739031/99629191-8fee0d00-2a5d-11eb-8573-2b6e1c755da4.png)

![image](https://user-images.githubusercontent.com/70739031/99629232-a7c59100-2a5d-11eb-9536-ab5dc966ea8c.png)

We can see that folder structure for  newly created dialog is like below.

![image](https://user-images.githubusercontent.com/70739031/99629391-ee1af000-2a5d-11eb-8854-68fd8360de9b.png)

From the .dialog file, if we remove recognizer line ("recognizer": "Testing.lu.qna"), multiple choice input prompt is working fine and not giving any error.

![image](https://user-images.githubusercontent.com/70739031/99629563-32a68b80-2a5e-11eb-8139-e73faf327ed9.png)

What is that recognizer for because if we keep that it is giving error for multiple input choice prompt in that dialog.

**Comment by dmvtech** [comment]
Hi @BeheraMadan I'm sorry you're still having trouble. 

> What is that recognizer for because if we keep that it is giving error for multiple input choice prompt in that dialog.

That is the recognizer for this dialog. Is the contents of your screen shot the entirety of this dialog? Or is it much bigger/involved?

Can you check the dialog in the recognizers folder? (Should be `recognizers\Testing.lu.qna.dialog`) and see what the contents of that look like? I don't have much in mine (as it is just it's own dialog that gets called explicitly from the Greeting trigger):
```
{
  "$kind": "Microsoft.CrossTrainedRecognizerSet",
  "recognizers": []
}
```

[Here ](https://github.com/dmvtech/randomstuff/tree/master/Choices)is a dialog that is working for me. Are you able to add that and test? Or at the very least, use to compare.

**Comment by BeheraMadan** [comment]
Hi,

The dialog in the recognizer folder has the same content that you provided in the screenshot. But even though we are getting the error "sequence contains no element"

One thing is that earlier we were using composer version 1.0.2 and the runtime was taken from that version.
But now when we updated the composer to latest version 1.2.1 but runtime is still from older version. Is it possible that the issue may be because of older runtime  ? 
We will update the runtime corresponding to latest composer version and will check.

**Comment by dmvtech** [comment]
Oh, good point. It may! I'll see if I have a 1.0.2 runtime I can easily try myself as well. Let me know what you find.

**Comment by BeheraMadan** [comment]
Hi @dmvtech 
After updating custom runtime as per latest composer version issue got resolved.

Thank you for support.
