### ISSUE TITLE
Composer doesn't use port in launchsettings.json when bot is launched from composer

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#4896]
## Describe the bug

I have a bot where I ejected the runtime and set a specific port in launchsettings.json to start the bot on a particular port so it doesn't collide with other skills I am testing locally. 
![image](https://user-images.githubusercontent.com/12264946/99687173-58c62e80-2a52-11eb-988c-8eb152cbfb1a.png)

When I start the bot from visual studio using ComposerRuntime.sln the bot starts at the configured port.

When I start the bot from composer, the bot starts at 3979 

![image](https://user-images.githubusercontent.com/12264946/99687360-91660800-2a52-11eb-99b2-d81cf13db0e9.png)

## Version

1.2.1

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a simple bot and eject the runtime.
2. Go to runtime\azurewebapp\Properties\launchsettings.json and speficy a custom port (e.g.: 35010)
3. Run the bot composer and try to launch it in emulator, the bot will launch on 3979.

## Expected behavior

I would like it if the bot would use my launchsettings port when launched from composer or VS. 

## Additional context

This also complicates testing skills where I need to configure the skill host endpoint and I can't if that's decide by composer:
![image](https://user-images.githubusercontent.com/12264946/99688067-5f08da80-2a53-11eb-979e-50a28f4e4a5d.png)

**Comment by luhan2017** [comment]
@gabog , yes, this is by design because composer can starts multiple bots with different ports. So when use composer to start a bot, composer passes the port as a parameter to start the bot, instead of using the port from launchsettings.json. 
We are working on a new botproject feature, which will help automatically fill in the skillHostEndpoint value, stay tuned.

**Comment by gabog** [comment]
I test this on 1.2.1-nightly.191833.ff9c593 but having composer automatically set the port complicates advanced scenarios where I want to test combinations of composer created bots and code first bot. 

If possible, I'd like to have an option to set the bot port in the settings window and have this applied to launchsettings.json if I ejected the runtime so things are consistent. 

This could be implemented as a checkbox (automatic port assignment or custom), so developers don't have to worry about ports in simple scenarios but can control that if they want to.

**Comment by luhan2017** [comment]
@gabog , Thanks for the feedback, we will follow up on this in R12.
