### ISSUE TITLE
Please add a confirmation modal, with a red X notice, on 'Pull from selected profile'

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotFramework-Composer#4905]
## Is your feature request related to a problem? Please describe.
I accidentally thought i was publishing, and clicked 'Pull from selected profile'.  I did see a 'backup was made' message, but not sure how to retrieve that backup, so i lost my work.

## Describe the solution you'd like
A confirmation before downloading.

## Additional context

![image](https://user-images.githubusercontent.com/11055362/99725124-7ce13a00-2a69-11eb-807b-c41cf5eab34c.png)

**Comment by JaskeeratBedi-cmk** [comment]
I don't know what this is?! What does it mean to pull from a selected profile? Saw this in the lates Version and it needs more clarity .. @benbrown help?

**Comment by mareekuh** [comment]
Assigning to @sangwoohaan - @sangwoohaan  please explain to @JaskeeratBedi-cmk  so she can add this to the menu UI architecture.

**Comment by tonyanziano** [comment]
@sangwoohaan Here is a screen recording of how the UX works for the feature:

https://www.loom.com/share/fd734395c7e14d0fb371b434e45f40ed

1. If you are not logged in yet, you must log in, and then it will pull (shown in the first run through)
2. If you are logged in, it will just display the status dialogs and pull (shown in the second run through)

**Comment by tonyanziano** [comment]
@EricDahlvang FYI pulling will create a backup folder containing your bot content before you pulled. This is located at the following location for Windows:

`%APPDATA%/Bot Framework Composer/backup/<bot-name>.<timestamp>/`
