### ISSUE TITLE
Can the bot runtime generated by Composer be run locally independent of Composer?

### ISSUE THREAD

**Issue by cs-sd** [microsoft/BotFramework-Composer#4910]
Composer documentation only seems to provide the option to deploy the bot to Azure. In our environment, we would like to deploy the bot locally (on-premise), not in the cloud.

The question is not about testing - I understand that the bot can be run and tested locally under the Composer. This is for a production environment - we would like to be able to just get the bot runtime generated by Composer and run it on our VM (ideally Linux, not Windows) or in a docker container, without the Composer also being present.

Is this possible?

Thank you for any clarification.

**Comment by cwhitten** [comment]
Hi @cs-sd, it sure can! You can eject the runtime and run it as a regular bot in whatever environment existing Bot Framework bots can run in. See the following doc getting started with this: https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#export-runtime
