### ISSUE TITLE
create trigger for skill from toolbar will throw error

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#4917]
## Describe the bug
![triggererror](https://user-images.githubusercontent.com/39758135/99775626-8c847f80-2b4a-11eb-8045-5a13a3b5fdfa.gif)
![qna](https://user-images.githubusercontent.com/39758135/99776223-6a3f3180-2b4b-11eb-8198-e7c89d0577fe.gif)

## Version
bot-project

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by srinaath** [comment]
Fixed in #4934
