### ISSUE TITLE
The bot content can be copied from one bot to another

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#4921]
## Describe the bug
![paste](https://user-images.githubusercontent.com/39758135/99778314-80022600-2b4e-11eb-917c-6e38d5771e44.gif)

## Version
bot-project

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by a-b-r-o-w-n** [comment]
@lei9444 Can you provide more details about this? What is the current behavior? What is the expected behavior?

**Comment by a-b-r-o-w-n** [comment]
@lei9444 also, please delete any section in the description that you do not use to reduce the noise. Thanks.
