### ISSUE TITLE
Unable to set input hint in composer responses

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#4933]
## Is your feature request related to a problem? Please describe.

I need to be able to set the InputHint property of an activity sent back to the user so webchat and other voice enabled channels would know if they need to open the mic or not. 

## Describe the solution you'd like

I'd like to have a dropdown in the Send Activity action that allows me to set the inputhint I want (possible inputhint values are defined in [InputHints.cs](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/InputHints.cs). 

## Describe alternatives you've considered

I guess I could probably create the entire activity by hand in LG but I'm not sure how to do that. 

## Additional context

See [Add input hints to messages with the Bot Connector API](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-input-hints?view=azure-bot-service-4.0) for additional context on inputhints.

**Comment by cwhitten** [comment]
@gabog hand-crafting the Activity in LG is the recommended way to do this. See https://docs.microsoft.com/en-us/azure/bot-service/language-generation/language-generation-structured-response-template?view=azure-bot-service-4.0#definition

**Comment by garypretty** [comment]
@gabog We are adding a new LG Editor in 1.4 (available in nightly builds now) where you can now add a Speech response, including setting an InputHint.  Great to get your feedback if you have chance to check it out - closing this out.
