### ISSUE TITLE
Menu Component

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4935]
In a typical bot I have lots of instances of the following;
![image](https://user-images.githubusercontent.com/49873947/99898919-a25a8780-2ca5-11eb-866d-d630e6bd3421.png)

Having the ability to create a custom Menu action for this that allows to define;
- style (buttons / suggestedActions),
- menuOptions [text, name, type (url / post), data]

Then having a built in EndTurn & Switch on the defined  menuOptions would make the flow much cleaner and remove some of the core logic from the initial send response lg content back into the flow.

**Comment by yeze322** [comment]
Seems you need a custom Action here which performs as a combination of those Actions in the screenshot.
I suppose this new Action block does several things:
1. Post a message to the channel and show a menu.
2. Wait for user to choose an option.
3. Handle the logic of the chosen option.

I'm not sure if we planned to add this Action as built-in, but hopefully it can be achieved by our 'Custom Action' feature.
You can implement your own runtime to composite those logic together and expose it as one Action block to Composer by defining the sdk.schema.

Additionally, I know that our VA Skill team is using another practice to overcome that. Usually, their practice is:
1. Define a new 'Custom Event' Trigger.
2. Put your Actions inside that Trigger, imagine it as a function, expose some parameters in the Menu text.
3. Whenver you want to use the Menu, emit an Event with your parameters to invoke that Trigger

**Comment by yeze322** [comment]
I tend to use use first approach since we are going to support it more in the future versions (UI Schema, Asset Library).

For now, I think it's possible to achieve that with several steps:
1. (in runtime) Implement a new $kind "SwitchMenu" which inherits from the SwitchCondition
2. (in runtime) Defines the sdk.schema.
3. (in Composer) Edit the sdk.uischema to expose that new Action block to Composer.
4. (in Composer, Experimental) Implement a custom React Component to show the Action as a branching node.

Let me try first, if any update I will post here.
@cwhitten Chris what do you think?

**Comment by cxbuilders** [comment]
@yeze322 Having the menu in a custom trigger that can be reused would reduce the overview in a dialog quite a bit.

It would be great to have the possibility in Composer to create Custom Actions with custom UI like switch, loop etc. This would also allow me to build a For Loop myself as requested in #4862
I have more things where I could be using that fir, like Async loading of data etc...

**Comment by yeze322** [comment]
@cxbuilders I'm actively working on an example which wraps your logic as a new $kind `SwitchCaseMenu`.
I'll post an update soon once it's ready.

**Comment by cxbuilders** [comment]
@yeze322 that's great to hear ! If you need me to check it out, let me know

**Comment by yeze322** [comment]
@cxbuilders Below is the gif on how to use the customized Action `SwitchCaseMenu`. (For the instructions, see my next comment)

#### Authoring Flow
![use-of-switchcasemenu](https://user-images.githubusercontent.com/8528761/102598647-4d504b00-4157-11eb-90bd-2152002efd1d.gif)

#### Chat Flow
![bot-of-switchcasemenu](https://user-images.githubusercontent.com/8528761/102598691-5a6d3a00-4157-11eb-8f03-23e061055266.gif)

**Comment by yeze322** [comment]
Instructions on how to define the `SwitchCaseMenu`:
1. Follow the doc ['Custom Action'](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action) to make sure `MultiplyDialog` is avaible
2. After that, let's implement the `SwitchCaseMenu`
    - I attached 3 files here, `SwitchCaseMenu.cs`, `SwitchCaseMenu.schema` and `SwitchCaseMenu.uischema`
    - Similar to `MultiplyDialog`, put two schema files under `Schemas` folder, put the cs file under `Action` folder.
3. Run the `updateSchema.sh` script again to regenerate the schema
4. The `SwitchCaseMenu` should be available in Composer now.
5. One more step, copy the `sdk.override.uischema` file to the folder `BOT_NAME\schemas` (where the update-schema script lives in)
6. Refresh Composer, everything should be the same as the gif.

Actually implementing a customized Action with multi-turn input is not that easy, you need to be very familiar with the bot runtime to write correct code. Those are still experimental features, as an alternation, wrap your action flow to a `Custom Event` trigger is still a considerable solution.

**Comment by yeze322** [comment]
Supported in the latest release. Refs: #5999 , https://github.com/microsoft/botbuilder-dotnet/pull/5099
