### ISSUE TITLE
Form dialog: "Choose"  triggers show all expressions in details pane expanded

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#4947]
If you create a form dialog, when you select a trigger for a "choose" operation (i.e.g, a trigger named "<propertyName>Entity - Choose()", the expression fields in the details pane all appear expanded (with Intellisense visible).

## Version

main branch, pulled November 23 
(but I first saw this error in the main branch from November 16)

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Steps to reproduce the behavior _(steps 1-4 create a form dialog)_:

1. Turn on the form dialog UI by going to Settings > App settings > Preview features and checking "Form dialogs."
2. Create a new bot (I used the the EchoBot template).
3. Create a form by clicking on the table-looking icon in the side nav, pressing the + button in the Schema pane, and adding a name. Add properties (or you can import a sample form schema form here: [https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/generation/docs/example-schemas](url)
4. Generate the dialog by pressing the "Generate dialog" button.

5. Go to the "Design" section.
6. Select any trigger in the form dialog that ends with "Choose ()". You will see the UI for the expressions in the details pane expanded:
![image](https://user-images.githubusercontent.com/39317542/100016383-2daf4800-2d8e-11eb-9535-396de954bdeb.png)

## Expected behavior

Would expect the helper UI to appear only after the field is selected:
![image](https://user-images.githubusercontent.com/39317542/100016603-85e64a00-2d8e-11eb-9388-c394bc39a5a9.png)

**Comment by cwhitten** [comment]
We need to hide the `actions` field from the component schema for OnChooseEntity. @LouisEugeneMSFT can you look at this?
