### ISSUE TITLE
LUIS key error is not reverted in Project tree

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#4950]
- Create an echo bot
- Create a new dialog and add a trigger. Update the name of trigger and add a trigger phrase
- The ProjectTree gives an error warning of a missing LUIS key correctly.
- Remove the dialog to which we added this trigger

Expected: The LUIS error on the project tree should disappear as the bot does not need LUIS anymore
Actual: The LUIS error still shows up even after deleting the dialog

**Comment by boydc2014** [comment]
@srinaath 
1. we could not repro the case that deleting dialog still need LUIS key. 
2. for deleting triggers, the current design is not considering the triggers to tell whether LUIS key needed. The current design is looking for LUISRecoginzer+.lu file not empty. 

So i'm taking down the bug label here.

**Comment by liweitian** [comment]
@boydc2014 Deleting  dialog works as expected. I think @srinaath is referring deleting triggers. The last time when I worked on this problem. The logic is what you said above. I checked code and sync with @luhan2017 today. Deleting a onIntent trigger should also deleting corresponding lu intent. The code is already there. But the parameter is not correct. I opened PR for it.
