### ISSUE TITLE
Dead link in Releases documentation

### ISSUE THREAD

**Issue by vkacherov** [microsoft/BotFramework-Composer#4951]
## Describe the bug
The link to the https://github.com/microsoft/BotFramework-Composer/blob/main/releases/1.2.1.md is dead, there is no 1.2.1.md in the repo.

## Browser

- [ ] Electron distribution
- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

## OS

- [x] macOS
- [x] Windows
- [x] Ubuntu

## To Reproduce

1. Go to 'https://github.com/microsoft/BotFramework-Composer/releases'
3. Scroll down to '1.2.1 Release'
4. Click on the https://github.com/microsoft/BotFramework-Composer/blob/main/releases/1.2.1.md link

**Comment by zxyanliu** [comment]
Yeah, it is a broken link.
I think you can read the following for your reference. 
https://github.com/microsoft/BotFramework-Composer/blob/main/releases/1.2.0.md
https://docs.microsoft.com/en-us/composer/what-is-new

**Comment by cwhitten** [comment]
this has been fixed. thanks for reporting
