### ISSUE TITLE
If the recognizer type is Orcherstrator we don't need the luis key

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#4953]
## Describe the bug
![image](https://user-images.githubusercontent.com/39758135/100057907-535a5100-2e63-11eb-8632-995d9ef9b1e4.png)
![image](https://user-images.githubusercontent.com/39758135/100057989-771d9700-2e63-11eb-851f-045f5f282fd2.png)

## Version
bot-projects

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
@taicchoumsft can you take a stab at this on the feature/bot-projects branch?

**Comment by taicchoumsft** [comment]
Will do, investigating now.
