### ISSUE TITLE
Generated dialog of 'any string' not openable in Composer

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#4954]
#### Problem:
In Form Dialog, when the property type is chosen as `Any string`, the generated dialog is not openable in Composer.
    - In dev env (yarn start:dev), Composer will raise an error (Invalid Expression error raised by Project Tree) when opening the generated dialog;
    - In prod env (yarn start), Composer will show a blank design page and exhausts all your PC memeory.

#### Suggested solutions
1. Temporarily, need to capture the error in `getPropertyReferences()` which is used to generate Trigger names in Project Tree.
![image](https://user-images.githubusercontent.com/8528761/100075518-02565700-2e7b-11eb-9631-e1248a13ed49.png)
2. cli-generator is already aware of this isse and will fix it on cli side.

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

#### Schema:
![image](https://user-images.githubusercontent.com/8528761/100067538-5bb98880-2e71-11eb-8e75-4b71a6698c1e.png)

**Comment by boydc2014** [comment]
@yeze322 let's open a new focused issue in Cli to track the changes there

**Comment by yeze322** [comment]
https://github.com/microsoft/BotBuilder-Samples/issues/2956
