### ISSUE TITLE
Please clarify - Error icon on Author canvas??

### ISSUE THREAD

**Issue by narulasrinivas** [microsoft/BotFramework-Composer#4964]
I've a query related to below image where it is highlighted with red colour circle.

Can someone explain or point me to right direction, why it is having error related symbol?

![image](https://user-images.githubusercontent.com/2491903/100103902-679b4f80-2e5d-11eb-9f5c-86107bfa3402.png)

**Comment by cwhitten** [comment]
@narulasrinivas this is nothing indicating an issue with your bot, and that you can click on that ui element to load the _configuration_ for the prompt to handle validation/error/retry scenarios for the user

**Comment by narulasrinivas** [comment]
Thank You. I'll try that out.
