### ISSUE TITLE
Dragging Dividers in Flow View throws error

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#4965]
When dragging either the left divider between the Dialog tree and the canvas or the right divider between the canvas and the properties pane throws an error in V1.2.1

![image](https://user-images.githubusercontent.com/49873947/100111545-7d654080-2e6e-11eb-9666-c4f2f2a7129e.png)

**Comment by yeze322** [comment]
transfer to @alanlong9278. we are aware of this issue
