### ISSUE TITLE
Publish targets in Publish Page

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#4974]
![Screen Shot 2020-11-24 at 4 43 21 PM](https://user-images.githubusercontent.com/13004779/100167579-3e39ee00-2e74-11eb-86d2-eee106485b75.png)
When "Manage Profiles" is clicked it needs to route to the appropriate settings page and scroll to the publish target section in Settings page. Currently, we just guide them to the settings page. It is hard for the user to know where to add the publishing profile.

**Comment by hibrenda** [comment]
addressed in #4983
