### ISSUE TITLE
date substaraction is not working in composer

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#4981]
Hi,

We have below url related to date and time functions. In that there are some functions such as  "dateTimeDiff" and "ticksToDays".

https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#date-and-time-functions

When we try to use above function we are getting error in composer as shown in below screenshot.

![image](https://user-images.githubusercontent.com/70739031/100222297-e5d02280-2f3f-11eb-8a96-243969f7b16b.png)

![image](https://user-images.githubusercontent.com/70739031/100222368-fb454c80-2f3f-11eb-8378-90e68b072e65.png)

![image](https://user-images.githubusercontent.com/70739031/100222640-65f68800-2f40-11eb-9d2a-08de567734c5.png)

![image](https://user-images.githubusercontent.com/70739031/100222685-79a1ee80-2f40-11eb-8e65-c2903b9856a7.png)

Are we missing something here regarding the use of above function.

Our requirement is that we want to substract two different date values.
For eg. consider two dates date1 = '2020-11-26T00:00:00.000Z' and date2 = '2020-11-24T00:00:00.000Z'.

So after substracting two dates we should get output 2 (number of days).

would you please provide any solution to achieve this in composer?

Thanks..

**Comment by dmvtech** [comment]
hi @BeheraMadan 

That is strange. I'm not getting that error at all.

My actions in .dialog:
```
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "cv8nqS"
          },
          "activity": "${SendActivity_cv8nqS()}"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "zZ1rtb"
          },
          "activity": "${SendActivity_zZ1rtb()}"
        }
```

My .lg:
```
# SendActivity_cv8nqS()
- ${dateTimeDiff('2020-11-26T00:00:00.000Z','2020-11-24T00:00:00.000Z')}
# SendActivity_zZ1rtb()
- ${ticksToDays(1728000000000)}
```

Is this using version 1.2.x, or an earlier version? Does this reproduce in a brand-new echo bot within composer? Double-check the activity IDs in both .dialog and .lg.

**Comment by BeheraMadan** [comment]
Hi,

We were using latest composer version 1.2.1 but custom runtime was taken from older version 1.0.2.
After updating the custom runtime as per latest composer version issue got resolved.

Thank you for quick support.
