### ISSUE TITLE
Form dialog: re-generating form schema causes error in .lu files

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#4987]
## Describe the bug

Using form dialogs, I re-generated a form dialog (without any changes) and tried to start the bot. I got an error that an .lu file was missing and 3 warnings.

## Version

main branch, pulled Nov 25

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. **Turn on the form dialog UI** by going to Settings > App settings > Preview features and selecting "Form dialogs."

2. **Create a form** by clicking on the table-looking icon in the side nav, pressing the + button in the Schema pane, and adding a name. 

3. **Import a sample form schema** from here: https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/generation/docs/example-schemas

4. **Generate the dialog** by pressing the "Generate dialog" button.

5. **Connect the form dialog to the main dialog** (I added a new trigger that used a Begin Dialog node to start the form dialog).

6. **Start the bot** with the "Start bot" button, then test in Emulator. The bot should work fine.

7. **Regenerate the form dialog** by going back to Composer, clicking on the Form icon (the table-looking icon), and pressing the **"Generate dialog"** button.

8. Once the progress indicators have cleared, go to the Design tab. **A number of warnings appeared.**

10. **Go to the Notifications to view warnings:**
![image](https://user-images.githubusercontent.com/39317542/100299222-fbe1e100-2f47-11eb-82b8-e00a6d737037.png)

11. Press **Start bot**. **Another error appears:**
![image](https://user-images.githubusercontent.com/39317542/100299193-e66cb700-2f47-11eb-9d3c-61b691ce75fa.png)

**Variations:**

- I was wondering if the problem was that my bot was running while I regenerated, so I made a copy (via Save As) and regenerated the form in that copy and had the same problem.

- I made a minor change to the form before re-generating and got these errors:
![image](https://user-images.githubusercontent.com/39317542/100299865-8b3bc400-2f49-11eb-8512-9db2ae98f3b4.png)
I was able to publish, build, and start the bot, but when testing the bot in Emulator, when it should have started the form dialog I got an "Object reference..." error:
![image](https://user-images.githubusercontent.com/39317542/100300109-2339ad80-2f4a-11eb-8432-0d4a1188be3f.png)

## Expected behavior

I would expect to be able to re-generate my form without errors. (I would also expect the "Generate dialog" button to be disabled if I have made no changes to my form.)

**Comment by cwhitten** [comment]
@GeoffCoxMSFT FYI for you
