### ISSUE TITLE
Show lg parameters in Form Editor

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#4995]
## Is your feature request related to a problem? Please describe.

In Form Dialog's scenario, the generated "activity" field is a lg template with fixed parameters (related to form schema).
![image](https://user-images.githubusercontent.com/8528761/100336407-1b910c00-3011-11eb-81a3-26a529d18f19.png)

In this case, if we hoist (dereference) the lg template's content to Form, it will be shown as below:
![image](https://user-images.githubusercontent.com/8528761/100336424-2186ed00-3011-11eb-8f2a-399d7037f05e.png)

The problem here is the parameters `'arrivalDate'`, `@datetimeV2` in the raw activity content `${confirmationText('arrivalDate', @datetimeV2)}` were lost in UI and can never be visible again unless opening the 'show code' editor.

In traditional Adaptive projects, we don't support direct parameters in .dialog file, we wrap the raw value again to a new template, for example `'${SendActivity_FRI42w()}`. However, in Form Dialog projects, those parameters seems necessary to be shown.

## Describe the solution you'd like

So I propose a solution that we show some extra content in Form Editor to make sure we keep all the information.

Either we show the raw value on top of LgEditor:
![imgpsh_mobile_save](https://user-images.githubusercontent.com/8528761/100337232-17192300-3012-11eb-94ff-38cc8c671978.jpg)

Or show the parameter list:
![imgpsh_mobile_save](https://user-images.githubusercontent.com/8528761/100337265-2009f480-3012-11eb-986d-7db4a75dbfa1.jpg)

This feature will only work in Form Generated Dialog's scenario since Composer-generated lg templates have zero params, so it can even be read-only to meet FormDialog's need.

In non-generated authoring experience, user won't be aware of this change since Composer always wraps lg content in a new template with special format we defined.

**Comment by cwhitten** [comment]
@GeoffCoxMSFT let's discuss

**Comment by mewa1024** [comment]
(fyi @sangwoohaan - this is an LG/property pane question, rather form dialog-specific question)

**Comment by sangwoohaan** [comment]
Interesting angle - I'll count this scenario in the ongoing LG redesign works

**Comment by mewa1024** [comment]
I think we should leave this as is for R11/Composer 1.3 for two reasons:

1. Even if we show the raw values, the user has to infer that the first (param 1) refers to `property` and the second refers to `val` param 2. In the template name with the parameters, it is spelled out: `# confirmUpdate(property, val)`.

2. But I think the bigger reason is that even if this first template was understandable, it's only the root in a trail of references 4 or 5 levels deep. The templates that are specific to the property are the ones with the the actual text that the user is interested in. This is why we group the leaf templates for each property in the LG (Bot Responses) page.

For example, here's what the path of template references looks like:

![image](https://user-images.githubusercontent.com/39317542/101437147-6b4ebd80-38c4-11eb-9962-0479bab6ec3d.png)

			
Even if we solve the parameter issue, showing the parameters won't be enough to navigate the user to the property-specific templates. I think we should come up with something more thorough for R12.
