### ISSUE TITLE
needs to put lg comments below lg name declaration in form dialog generated lg files

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#4996]
## Describe the bug
Related to https://github.com/microsoft/BotFramework-Composer/issues/4822 .
![image](https://user-images.githubusercontent.com/8528761/100339254-99a2e200-3014-11eb-97ca-74b110aecdc0.png)

Before the fix, we need to make sure form dialog cli put lg comments below lg name declarations.
```
# arrivalDate_Show
>> Show value of 'arrivalDate' property
- ${arrivalDate_Name()}: ${arrivalDate_Value($arrivalDate)}
```
Rather than
```
>> Show value of 'arrivalDate' property
# arrivalDate_Show
- ${arrivalDate_Name()}: ${arrivalDate_Value($arrivalDate)}
```

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Additional context

We can transfer this issue to Botbuilder-Samples repo after it's triaged.

**Comment by hatpick** [comment]
What do you think @chrimc62
