### ISSUE TITLE
Error: getaddrinfo ENOTFOUND *.scm.azurewebsites.net, environment variable error

### ISSUE THREAD

**Issue by saiteja21** [microsoft/BotFramework-Composer#5003]
I have manually created the resources needed for my Bot to run. And built publishing profile.

My resource group name is "bottested-rg", and my app service name is "bottested-webapp", so ideally my Kudu console or publishing endpoint will be bottested-webapp.scm.azurewebsites.net

Now, while publishing my Composer Bot to Azure it gives below error  

**ISSUE:**

![image](https://user-images.githubusercontent.com/11377131/100431610-67ba6b80-3066-11eb-8292-300d23f2ddaf.png)

What it is doing is appending "environment" value to resource group name or name value like this "bottested-rg-dev" and looking for "scm" - bottested-rg-dev.scm.azurewebsites.net which obviously will not present. 

How can I make it publish to "bottested-webapp.scm.azurewebsites.net"? 

**Note:** Azure App service name is globally unique value so I did not get to use "bottested-rg". So I created an App Service  under the name "bottested-webapp". 

**Things I tried:** 

Changed environment value to something like this "environment": "webapp", but it's still looking for "bottested-rg-webapp.scm.azurewebsites.net" which is not present and gives the same error as expected. 

So the real question is how to bypass this environment value getting attached to RG or Bot name? 
Or How can I make it to publish to an App Service that I created manually?

**Comment by luhan2017** [comment]
@saiteja21 you can add another field in your publish profile:

{
   "hostname": "bottested-webapp"
}

The logic is:
if hostname is null or empty, we use "name-environment, otherwise just use hostname. 

btw, if you use luis services, use luisResourse to override "name-environment-luis"

**Comment by saiteja21** [comment]
@luhan2017  Thank you this could resolve the issue, I have not tested it yet. But your explanation helps and makes sense.

**Comment by cwhitten** [comment]
@saiteja21 I'll close this as a how-to question. Please create a new issue if you are seeing errors
