### ISSUE TITLE
[MCS-DE-GO] Dialog creation error in qna-filename when language is not "en-us"

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5004]
When selecting a Bot with a default language (set as only language) which is not "en-us", the .qna-Files are still created with the "en-us"-extension which causes Composer to produce an error that it could not find the .qna-File.

@joaollq @goergenj @sgellock @benbrown @Bindsi @cwhitten

**Comment by cwhitten** [comment]
@zhixzhan @luhan2017 can you please take a look at this?
