### ISSUE TITLE
[MCS-DE-GO] QnAMaker multi-language settings

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5005]
QnAMaker Publishing does not allow setting a region other than "westus" and language other than "en-us". For language it seems it uses the Bot language default language at least. However multi-language settings are also missing. "qna":"en-us":..., "qna":"de-de":...

![image](https://user-images.githubusercontent.com/31212469/100441562-f7800a00-30a6-11eb-9c5c-de2112a1e1c4.png)

@joaollq @goergenj @sgellock @benbrown @Bindsi @cwhitten

**Comment by hibrenda** [comment]
Yes. This is by design . No multi-lang support for QnA at this moment.

**Comment by cwhitten** [comment]
cc @vivekkshankar - for R12 planning let's check in on the rev of multi-language authoring you've been looking into for QnA.

**Comment by goergenj** [comment]
@cwhitten Any timeline update on this?

**Comment by cwhitten** [comment]
I'm going to take this out of R12 as it seems we're not locked on the experience just yet. We're very close on the UX/design side.

**Comment by goergenj** [comment]
Any update on this?
