### ISSUE TITLE
LUIS Intent deployment activity not getting updated

### ISSUE THREAD

**Issue by narulasrinivas** [microsoft/BotFramework-Composer#5008]
## Describe the bug
I'm using BOT Composer v1.2.1 and created a project with **QnAMakerLUIS** template. 

I was able to publish OOB template without any changes. 

## Version

BOT Composer v1.2.1
BOT Framework Emulator 4.11.0
![image](https://user-images.githubusercontent.com/2491903/100485013-751f3680-30f6-11eb-9439-f9d4d887449d.png)

## OS

Windows 10

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Once after published, 

1. Opened application in Emulator 
2. It prompted **Welcome. You can type ‘help’ to learn more.** 
3. I typed **help** and enter
4. Then I'm getting **"" is not a valid LUIS application id.**

Then I checked LUIS intents in BOT Composer 
1. Go to composer and select **User Input** tab
2. Select **All**
3. It will display all the intents, sample phrases and Activity.
4. In the Activity section, it is still showing **Not yet published**

## Expected behavior

1. LUIS Intents has to show as **Published** 
2. When I type **help**, it should trigger **help** dialog in BOT composer.

## Screenshots

LUIS Intent Activity status
![image](https://user-images.githubusercontent.com/2491903/100470146-94ef3400-30cf-11eb-9db6-8c1e1d5a1753.png)

LUIS error in BOT Composer 
![image](https://user-images.githubusercontent.com/2491903/100470085-6ffac100-30cf-11eb-9733-607f56a7fd55.png)

**Comment by dmvtech** [comment]
Hi @narulasrinivas 

Can you confirm that you are using your LUIS **authoring** key and matches this section from Azure portal?:
![image](https://user-images.githubusercontent.com/43397658/100788465-f4985880-33c9-11eb-91e5-cd49cd90d366.png)

Also; have you configured any of the settings for LUIS in bot settings yet?:

![image](https://user-images.githubusercontent.com/43397658/100788332-c87cd780-33c9-11eb-80a0-de1a85cffea8.png)

**Comment by negativeeddy** [comment]
I had the same issue when adding intents to an empty bot. My keys in the Composer's Bot Settings UI were correct (even after restarting composer), but when I looked at the file [bot]/settings/appsettings.json  it was missing the keys.

I can set the keys manually in the file (and the bot works!), but if I change any of bot settings in the UI, they keys disappear from the file again.

**Comment by narulasrinivas** [comment]
@dmvtech - Thanks for responding. I checked keys and everything looks good to me. After spending lot of hours to understand and resolve it, none of the solution worked for me.

I did same steps on another laptop, it worked fine.

**Comment by narulasrinivas** [comment]
@negativeeddy - Even I'm experiencing same issue along with above issue.

**Comment by dmvtech** [comment]
Hi @narulasrinivas and @negativeeddy,

Can you update to [v1.3.1](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.3.0) and see if this still reproduces for you?

**Comment by narulasrinivas** [comment]
@dmvtech - Installed v1.3.1 BOT composer and deployed **QnAMakerLUIS** OOB sample and tested but still the same :(

![image](https://user-images.githubusercontent.com/2491903/102699987-2bcb8e00-4241-11eb-9d3b-d14f121e301c.png)

**Comment by dmvtech** [comment]
Hi @narulasrinivas and @negativeeddy Apologies for the delay.

Can you please try clearing the local storage and then trying again? The steps to do this are:

1. Go to `View->Toggle Developer Tools` in Composer.
2. Go to the `Application` tab
3. Under the left nav `Local Storage`, select the localhost node and then hit the `Clear all` button 🚫.
4. Close Composer and then restart.
5. Re-add your authoring key
6. Run and test (see if they are published, etc)

You may also want to go to your [LUIS authoring resource](www.luis.ai) and see if you need/want to clean up any apps (with title containing `(composer)` in them) that are there already. Before step 6.

@negativeeddy  when you set the authoring key for Composer, it will not save it to a file (along with things like app password. For security reasons). I'm thinking something is off between the local storage and what is set in `recognizers\QnAMakerLUISSample-0.en-us.lu.dialog` file. Clearing the local storage should hopefully help.

**Comment by negativeeddy** [comment]
after updating to v1.3.0 LUIS is working for me again

**Comment by dmvtech** [comment]
@narulasrinivas Were you able to clear the local storage and try again?

**Comment by dmvtech** [comment]
Closing as issue is now being tracked in #5451
