### ISSUE TITLE
BeginDialog should allow an expression for the dialog id to begin

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/BotFramework-Composer#5009]
## Is your feature request related to a problem? Please describe.
I would like to provide an expression, or a string, for the dialog to start with BeginDialog.

## Describe the solution you'd like
Three options:
1) choose from dropdown (like now)
2) enter a string (dialog id)
3) enter an expression, from where the dialogId should be retrieved

## Additional context

BeginDialog currently has the following property in the schema, and should work with an expression:
```json
        "dialog": {
          "oneOf": [
            {
              "$kind": "Microsoft.IDialog",
              "pattern": "^(?!(=)).*",
              "title": "Dialog",
              "$ref": "#/definitions/Microsoft.IDialog"
            },
            {
              "$ref": "#/definitions/equalsExpression",
              "examples": [
                "=settings.dialogId"
              ]
            }
          ],
          "title": "Dialog name",
          "description": "Name of the dialog to call."
        },
```		
In code the property is defined as: 
```cs
public DialogExpression Dialog { get; set; } 
```

A method which is used to resolve the dialog to begin is defined as:
```cs
        protected virtual Dialog ResolveDialog(DialogContext dc)
        {
            if (this.Dialog?.Value != null)
            {
                return this.Dialog.Value;
            }

            // NOTE: we want the result of the expression as a string so we can look up the string using external FindDialog().
            var se = new StringExpression($"={this.Dialog.ExpressionText}");
            var dialogId = se.GetValue(dc.State);
            return dc.FindDialog(dialogId ?? throw new InvalidOperationException($"{this.Dialog.ToString()} not found."));
        }
```		
		
![image](https://user-images.githubusercontent.com/11055362/100554534-1ff43980-324a-11eb-8f9c-1de31fe62e36.png)

**Comment by EricDahlvang** [comment]
Note:
https://github.com/microsoft/botbuilder-dotnet/pull/4880

**Comment by cwhitten** [comment]
This is blocked on https://github.com/microsoft/botbuilder-dotnet/pull/4880

**Comment by cwhitten** [comment]
@sangwoohaan can you provide UX guidance? I assume we would add a "Write an expression" option like we do other fields that support it but want to confirm and have clarity for the implementor.

**Comment by JohnRobertGreen** [comment]
I have the same issue as @Clooney24 . Oddly, it works in the Emulator but not via Web Chat.

**Comment by mewa1024** [comment]
Looks like this has been fixed:
![image](https://user-images.githubusercontent.com/39317542/124332390-3a76f400-db46-11eb-8eab-a3a9e8bbf5ea.png)
