### ISSUE TITLE
Integration with Git

### ISSUE THREAD

**Issue by CopenhagenJames** [microsoft/BotFramework-Composer#5013]
## Ability to integrate with Source Control

Currently you can manually add to source control.  It would be great to have the product integrate with our source control such as Git.

**Comment by cwhitten** [comment]
Hello @CopenhagenJames. We're happy to take this as a feature request to add to the backlog. What do you refer to as "source"? Dialog assets (lu, lg, dialog)? Runtime code? What type of a git experience are you looking for?

**Comment by CopenhagenJames** [comment]
For the GitHub experience it would be nice to be able to add the project to GitHub along with any supporting files that are required to successfully publish and run the project.

As it sits now, one has to manually checkout and check-in the entire folder’s contents to ensure all files are source controlled.

To have a menu option like Visual Studio to add project or solution to source control would be a great feature.  As files are edited they could be automatically checked out and on the footer or status bar you could have an option to commit changes to the local git repository and then a push to the remote repository.

Take a look at how VS Code or Visual Studio provide source control and this type of feature would be extremely beneficial.


Thank You,


James D. Lawrence
PMP® Senior Cloud Solutions Architect | Azure Platform Evangelist
520 686-4303 (m)
MBA | MS Computer Science | MS Cyber Security | MCSD | MCAD
Email: james.lawrence@microsoft.com<mailto:james.lawrence@microsoft.com>

Interested in Obtaining Azure Certifications?  Ask me about how to get training…

[microsoft-certified-trainer-2019-2020]<https://www.youracclaim.com/badges/60909be4-283c-44a2-a5ea-dfec024b71a5/public_url> [cid:image018.png@01D6C7E3.477371A0] <https://www.youracclaim.com/badges/bbc871a3-66b8-486b-9449-d4239405fcb0/public_url>   [cid:image019.png@01D6C7E3.477371A0] <https://www.youracclaim.com/badges/32b833f0-7a48-4abd-bd86-855e39d7ba5e/public_url>   [story-impact-learning-to-connect-and-compel] <https://www.youracclaim.com/badges/321aa97e-f50c-4053-8352-d46b1d705f96/public_url>   [cid:image021.png@01D6C7E3.477371A0] <https://www.youracclaim.com/badges/0d3e0fba-4974-4126-8c41-4071c013eab8/public_url>
[microsoft-certified-azure-fundamentals (1)]<https://www.youracclaim.com/badges/737b36e0-eed3-47d7-8f7e-540849f81000/public_url>  [cid:image023.png@01D6C7E3.477371A0] <https://www.youracclaim.com/badges/c333efd2-47a7-4e74-93d1-f6d76aa31641/public_url>   [cid:image024.png@01D6C7E3.477371A0] <https://www.youracclaim.com/badges/8ebc416e-ed18-49ba-8750-a0f743e5b93a/linked_in_profile>   [microsoft-certified-azure-administrator-associate] <https://www.youracclaim.com/badges/516a1404-f296-4428-b40b-81727a60eb6f/linked_in_profile>   [cid:image026.png@01D6C7E3.477371A0] <https://www.youracclaim.com/badges/6574aeb3-bc97-4650-96d0-db279d2ea51f/public_url>   [microsoft-certified-azure-developer-associate] <https://www.youracclaim.com/badges/0f817590-ba82-4389-a558-ba0b29efe488/linked_in_profile>   [cid:image028.png@01D6C7E3.477371A0] <https://www.youracclaim.com/badges/28633103-910c-47f1-b720-9eb1e367f1ea/public_url>   [microsoft-certified-azure-devops-engineer-expert] <https://www.youracclaim.com/badges/ba63ab91-ad0f-4b0f-9cd1-967ba4f0a6d1/public_url>

  [cid:image030.png@01D6C7E3.477371A0]   [cid:image031.png@01D6C7E3.477371A0]   [comptia-security-ce-certification] <https://www.youracclaim.com/badges/c6ddbca1-8aab-4ff2-8932-c205ff64e78d/public_url>

**Comment by garypretty** [comment]
Thanks for the additional info @CopenhagenJames.  We will include this as part of future planning consideration.

**Comment by liyubupt** [comment]
@cwhitten @garypretty dear both, I saw this feature closed. however I can not see the feature regarding git integration on bot composer. Do you knowhow I can find this feature?
