### ISSUE TITLE
Indicate trigger type in the navigation pane

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#5033]
## Is your feature request related to a problem? Please describe.

When I create multiple triggers on a dialog of different types, there is no way to tell the different types apart without clicking on them. 

For instance, if I create an OnIntent trigger and an OnEvent trigger they visually look exactly the same. 
 
## Describe the solution you'd like
It would be nice if the default name of the action included its type or if they were categorized into nested dropdowns based on type. Right now, I am editing the default labels once they are created following this pattern:
- OnIntent (MyIntent)
- OnEvent (MyEvent)

But it's a bit of a hassle to do each time I create a new trigger.

**Comment by cwhitten** [comment]
@vivekkshankar can you look at this? do you have existing UI in the updated project tree to emphasize what @lauren-mills is looking for?
