### ISSUE TITLE
Remove the Monaco editor smart scroll bar for small property fields

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#5035]
## Is your feature request related to a problem? Please describe.

The Monaco editor used for LG/LU/etc. inputs has a smart scroll ability that can show a preview of the text and error/modification/selection indicators in within the scroll bar.  Very useful when in a full screen editing of a lot of text, but near useless in small input fields.

## Describe the solution you'd like

Remove smart scroll and use the standard scroll for small input fields.

## Describe alternatives you've considered

N/A

**Comment by LouisEugeneMSFT** [comment]
[By design] It matches user's settings:

![image](https://user-images.githubusercontent.com/66701106/100943947-14577b80-34b3-11eb-881b-05b23216913e.png)
