### ISSUE TITLE
File persistence currently happening for all bots

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#5043]
## Describe the bug
https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/client/src/recoilModel/DispatcherWrapper.tsx#L107

Currently we are checking for updates on all projects in the BotProject. We need to be using the currentProjectIdState which needs to be set based on the URL. This could improve our performance slightly

**Comment by boydc2014** [comment]
Close this based on the discussion on platform chat. 

Our gain is to save a few equality checks, our risk is potential data loss, really not balanced here.
