### ISSUE TITLE
Form dialogs: "skip" is not understood

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5057]
## Describe the bug

In a form dialog, when the bot asks for a property, the user should be able to say "skip" to skip to the next step. The bot is not understanding skip in this version.

## Version

"bot-project" branch, pulled Dec 2

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Create a bot that uses a form dialog. You can do this by:

1. Turn on the form dialog UI by going to Settings > App settings > Preview features and selecting "Form dialogs."
2. Create a form by clicking on the table-looking icon in the side nav, pressing the + button in the Schema pane, and adding a name.
3. Import a sample form schema from here: [https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/generation/docs/example-schemas](url)
4. Generate the dialog by pressing the "Generate dialog" button.
5. Connect the form dialog to the main dialog (I added a new trigger that used a Begin Dialog node to start the form dialog).
6. Start the bot with the Start all bots button, then test in Emulator. The bot should work fine.
7. Start talking to the bot. When it asks for a property (aside from "Name" which accepts any input), say "skip".

The bot does not understand:
![image](https://user-images.githubusercontent.com/39317542/100923898-bddb4480-3494-11eb-8907-87ee5089e02f.png)

## Expected behavior

The bot should move to the next prompt when the user says "skip".

## Additional context
Not sure if this is significant, but when I tried this yesterday (using the "main" branch pulled Dec 1), "skip" worked in that it moved to the next prompt, but first it showed the help message for the property I was trying to skip:
![image](https://user-images.githubusercontent.com/39317542/100925468-e401e400-3496-11eb-9743-18bbee8dacf3.png)

**Comment by chrimc62** [comment]
This should largely work now except in the case of string entities where it requires an update to the runtime.
