### ISSUE TITLE
Form dialog: property to change asks for property name but only understands property values

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5059]
## Describe the bug

After the form dialog has collected all the values for the required properties, it shows a card and asks the user if there are any properties they'd like to change. At this point, it only understands property values, not property names. For example, the bot would understand "turkey", but not "meat".

## Version

"bot-project" branch, pulled Dec 2

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Create a bot that uses a form dialog. You can do this by:

1. Turn on the form dialog UI by going to Settings > App settings > Preview features and selecting "Form dialogs."
2. Create a form by clicking on the table-looking icon in the side nav, pressing the + button in the Schema pane, and adding a name.
3. Import a sample form schema from here: https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/generation/docs/example-schemas
4. Generate the dialog by pressing the "Generate dialog" button.
5. Connect the form dialog to the main dialog (I added a new trigger that used a Begin Dialog node to start the form dialog).
6. Start the bot with the Start all bots button, then test in Emulator.
7. Start talking to the bot and answer all its prompts.
8. When the bot asks "Is there any property you want to change? (no or the property name)", answer with a property name. The bot will get confused. If you answer with a property value, the bot will use that value to replace the existing value. 

![image](https://user-images.githubusercontent.com/39317542/100929051-e450ae00-349b-11eb-9e7d-cf30b3ef47ce.png)

Also, if you choose a value for a property that can accept multiple values, the bot adds the new value rather than uses the new value to replace the old one:

![image](https://user-images.githubusercontent.com/39317542/100929451-82447880-349c-11eb-82d8-d9c28ee1dfc3.png)

## Expected behavior

The bot should understand a property name, so the user could change their bread option by saying "bread", rather than by saying "rye". If this isn't possible, the prompt should be reworded: "Is there any selection you want to change? (Type "no" or enter your new selection.)"

**Comment by mewa1024** [comment]
also effects when the user says "change <propertyname>" anywhere in the conversation. Bot expects "change <propertyvalue>". Example of saying "change toppings" with LUIS trace shown here:

![image](https://user-images.githubusercontent.com/39317542/101530748-2ddf4400-3947-11eb-85fc-bb597eac4cc5.png)

**Comment by mewa1024** [comment]
Sorry--the plot keeps thickening. With the same bot as above (and running it in the same instance, but in different Emulator conversation), "change whole wheat to rye" **does** work. Here are screenshots of both LUIS traces for "change whole wheat to rye":
![image](https://user-images.githubusercontent.com/39317542/101534169-a2b47d00-394b-11eb-92b8-4cb13366dd30.png)
![image](https://user-images.githubusercontent.com/39317542/101534237-b65fe380-394b-11eb-9f0c-c1151fca99e8.png)

**Comment by chrimc62** [comment]
This should be fixed.
