### ISSUE TITLE
Cannot start Composer 1.2.1 desktop version

### ISSUE THREAD

**Issue by gbelenky** [microsoft/BotFramework-Composer#5073]
## Describe the bug

Cannot start Composer

## Version
BotFramework-Composer-1.2.1-windows-setup.exe

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Start Composer and see the frozen Welcome screen 
![Screenshot 2020-12-03 110021](https://user-images.githubusercontent.com/26817885/100995965-cd23c600-3558-11eb-8cc0-4a3a560054b9.jpg)

## Expected behavior

Composer started after the Welcome screen, the Welcome screen disappears

**Comment by cwhitten** [comment]
tagging https://github.com/microsoft/BotFramework-Composer/pull/5068 to see if this is related at all

**Comment by boydc2014** [comment]
> tagging #5068 to see if this is related at all

No, this is is not related to the orchestrator, but to the md5 package.

**Comment by feich-ms** [comment]
Hi @gbelenky, could you try to use cmd to open your installed composer that has such issue. Follow below steps:
1. Open cmd and go to your composer installed folder. Usually the folder locates here if you don't change it C:\Users\{your user name}\AppData\Local\Programs\Bot Framework Composer. 
2. In cmd, type `"Bot Framework Composer.exe"` to launch composer
3. You will see the exception in the cmd window. Below screenshot is a successful launch example. 
![image](https://user-images.githubusercontent.com/43032123/101131426-3b8f8380-3640-11eb-8566-ba1f1810a967.png)

Could you please try above steps and paste the exception information here for us to investigate.

Thank you.

**Comment by gbelenky** [comment]
adding screenshot 
![composerstart](https://user-images.githubusercontent.com/26817885/101142743-4e8d5e00-3616-11eb-81c1-d4e956ed0e50.jpg)
 and log `C:\Program Files\Bot Framework Composer>
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:11720) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (node:11720) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (node:11720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by feich-ms** [comment]
@gbelenky thanks for the message. Are these all the messages the exception throws? Can we get more logs?
Besides, could you try to reinstall the 1.2.1 composer downloaded from here https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.2.1 to see if it works. I installed this version and all work as exptected.

**Comment by gbelenky** [comment]
@feich-ms -  yes, that's it. I just re-installed the Composer. The same experience 
![composerstart2](https://user-images.githubusercontent.com/26817885/101156747-586c8c80-3629-11eb-8727-26af7c16edc9.jpg)

**Comment by gbelenky** [comment]
@feich-ms - how can I get more verbose logging data?

**Comment by feich-ms** [comment]
@boydc2014 @cwhitten do you have more insights about how to get more logs?

**Comment by cwhitten** [comment]
@gbelenky @feich-ms 

in the shell, set the following environment variable:

`DEBUG=composer*`

On windows this should be: `SET DEBUG=composer*`

**Comment by gbelenky** [comment]
this is what I see (skipping my env variables)
2020-12-04T15:33:49.444Z composer:electron production environment detected.
2020-12-04T15:33:49.454Z composer:electron Run completed
2020-12-04T15:33:49.505Z composer:electron App ready
2020-12-04T15:33:49.505Z composer:electron Loading latest known locale
2020-12-04T15:33:49.510Z composer:electron:electron-window Raw screen dimensions: 1040 x 1920
2020-12-04T15:33:49.510Z composer:electron:electron-window Electron window dimensions: 936 x 1248
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
2020-12-04T15:33:49.541Z composer:electron:electron-window Rendered Electron window dimensions:  [ 1248, 936 ]
2020-12-04T15:33:49.981Z composer:electron Creating app data directory...
2020-12-04T15:33:49.982Z composer:electron creating composer app data path at:  C:\Users\gbelenky\AppData\Roaming\BotFrameworkComposer
2020-12-04T15:33:49.984Z composer:electron creating local bot runtime publish path:  C:\Users\gbelenky\AppData\Roaming\BotFrameworkComposer\hostedBots
2020-12-04T15:33:49.987Z composer:electron Created app data directory.
2020-12-04T15:33:49.987Z composer:electron Starting server...
2020-12-04T15:33:52.339Z composer App Settings: {
  botAdminEndpoint: 'http://localhost:3979',
  botEndpoint: 'http://localhost:3979',
  botsFolder: 'C:\\Users\\gbelenky',
  runtimeFrameworkVersion: 'netcoreapp3.1',
  appDataPath: 'C:\\Users\\gbelenky\\AppData\\Roaming\\BotFrameworkComposer\\data.json',
  platform: 'win32',
  diskNames: [ 'C:/' ]
}
(node:2652) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (node:2652) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (node:2652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2652) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by feich-ms** [comment]
I checked my logs of successful launch(See below), it seems above exception was thrown from here **composer:electron-auth-provider Initialized** because this message was not logged above. We will find some guys who are familar with this area to investigate it. Will keep it posted when there are any findings. Thanks for your patience. BTW, @gbelenky it would be helpful if you have another machine or VM to verify the installation failure again.

...(skipped)
2020-12-07T06:02:27.494Z composer:electron Starting server...
2020-12-07T06:02:29.545Z composer App Settings: {
  botAdminEndpoint: 'http://localhost:3979',
  botEndpoint: 'http://localhost:3979',
  botsFolder: 'C:\\Users\\feich',
  runtimeFrameworkVersion: 'netcoreapp3.1',
  appDataPath: 'C:\\Users\\feich\\AppData\\Roaming\\BotFrameworkComposer\\data.json',
  platform: 'win32',
  diskNames: [ 'C:/', 'D:/' ]
}
**2020-12-07T06:02:29.961Z composer:electron-auth-provider Initialized.**
2020-12-07T06:02:29.962Z composer:auth-service Initialized in Electron context.
2020-12-07T06:02:29.964Z composer:auth-service Production environment detected. Generating CSRF token.
...(skipped)

**Comment by feich-ms** [comment]
I went through the code and the exception should be thrown when getting the OneAuth token. @gbelenky have you ever set any azure authoring stuff for composer before installing 1.2.1 version? If so, It would be helpful for us investigation if you have another machine or VM that is not setting any composer auth staff before to double confirm the launch failure. Thank you very much.

**Comment by gbelenky** [comment]
Hello @feich-ms ! Yes, I probably did. How do I solve the issue for this PC?
Thanks!

**Comment by feich-ms** [comment]
@luhan2017 I don't have enough experience to figure out the fix here. Could you guide this issue to someone who is familar with the Electron auth part? 

BTW, @gbelenky is it possible to be related with your route just like you mentioned here https://github.com/microsoft/BotFramework-Composer/issues/4458#issuecomment-741008617

**Comment by feich-ms** [comment]
@gbelenky, have you ever followed this README https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/electron-server/AUTH.md to configure the auth? If so, could you try to uninstall these installation? Besides, could you also try another machine or another WIFI route? Sorry for the inconvenience.

**Comment by gbelenky** [comment]
@feich-ms - I set the variables as described in the article above, but was not able to find the installOneAuth.js on my machine. Where do I find it?
I also tried other WIFIs and it did not work.

**Comment by luhan2017** [comment]
@tonyanziano , could you please help take a look.

**Comment by tonyanziano** [comment]
The auth readme is only intended for local development of Composer, it is irrelevant to the production version of Composer. You do not need to run the `installOneAuth.js` script.

It is odd that we see the exception before we see the `composer:electron-auth-provider Initialized.` entry, however, this does not mean that the exception happened within that code path (which is just initializing a class with a config object), as the exception could have happened at any point in between printing out the app settings and initializing that class.

It seems strange to me that there is no stack trace or file name within the exception message that is in your logs @gbelenky . It is very hard to diagnose the issue without knowing where the error originated from. All we know right now is that it happens at some point during the startup process.

For now, could you please [try the latest Composer nightly build here](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.0-rc2-nightly.193532.e4bbbdf) and let me know if you still see the same issue?

If you do, we can try to debug the issue further.

**Comment by gbelenky** [comment]
@tonyanziano - no change after installing the nightly build
![composernightly](https://user-images.githubusercontent.com/26817885/101933236-3308f100-3bdc-11eb-935e-667c8a386590.jpg)

**Comment by tonyanziano** [comment]
Ok, if you're around next week I'd be happy to jump on a call and take a shot at debugging this.

**Comment by tonyanziano** [comment]
After hopping on a call and debugging with @gbelenky , we figured out that there is an exception being thrown when Composer tries to read the JSON store (`data.json`).

Here is the exception:

```
SyntaxError: Unexpected token in JSON at position 0 at JSON.parse (<anonymous>) at JsonStore.readStore (C:\Users\gbelenky\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\@bfc\server\build\store\store.js:67:26) at JsonStore.get (C:\Users\gbelenky\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\@bfc\server\build\store\store.js:37:14) at ExtensionManagerImp.<anonymous> (C:\Users\gbelenky\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\@bfc\server\build\services\extensionManager.js:84:40) at Generator.next (<anonymous>) at fulfilled (C:\Users\gbelenky\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\tslib\tslib.js:111:62)
```

We checked the `data.json` file and it looks to be valid JSON. My hunch is that at some point, when we are writing the JSON to disk, it is prepending a byte order mark (BOM) to the front of the JSON file, which is causing `JSON.parse()` to throw. We faced a similar problem in the Emulator at one point.

**Comment by tonyanziano** [comment]
Turns out that it was a malformed `extensions.json` file in the `%APPDATA%/Roaming/BotFrameworkComposer/` app data folder.

Adding valid JSON to this file -- `{}` -- fixed the issue and @gbelenky is now able to start Composer.

We should consider writing some documentation on how to completely wipe the Composer installation to troubleshoot these issues.
