### ISSUE TITLE
"Create New Knowledgebase" wont allow browsing to upload a local file

### ISSUE THREAD

**Issue by Markyboy944** [microsoft/BotFramework-Composer#5076]
The "Knowledge Source" field says "Enter a URL or browse to upload a file" - but there is no way to browse. 

![image](https://user-images.githubusercontent.com/5471850/101060410-4b975c80-3587-11eb-9ed6-149eced9e078.png)

**Comment by cwhitten** [comment]
hi @Markyboy944 - this is a bug in the placeholder text. We don't yet support local file uploads for this scenario. cc @hibrenda @luhan2017

**Comment by Markyboy944** [comment]
Ah - ok thanks Chris @cwhitten

**Comment by cwhitten** [comment]
Yan sez "Enter a URL"
