### ISSUE TITLE
UX: Header language button affordance

### ISSUE THREAD

**Issue by hatpick** [microsoft/BotFramework-Composer#5081]
## Describe the bug

The "button" is lacking the affordance to cue that it's clickable.

(it also has css issues, I think the text is too big for the container and it's not aligned)

## Version
Latest on main.

## Screenshots
![Screen Shot 2020-12-03 at 10 48 47 AM](https://user-images.githubusercontent.com/1483492/101078670-53410c00-355b-11eb-93e3-0177e381a080.png)

## Proposed solution
I don't know why the app name should appear next to the current locale either, I propose a button with the locale text that opens a menu to change the language. Hint text can appear next to the button via a (?) pattern we are using in other places. Once a user reads the hint they wont need to read it every time, so I think it should be on demand vs. forced content on every click.

**Comment by mewa1024** [comment]
Related to #7116, #7733, #7582

Added to epic #8108
