### ISSUE TITLE
Need guidance for debuggability support

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5084]
I hit this error (see image). I know my network is good (you can see I'm in teams chat). The solution used to work.
It may be related to large LUIS model (just a suspicion) but I don' t know for sure.
 
* **The bug is**: Need guidance for debuggging and more detailed error messages that can lead to corrective action.
* In this specific case I tried multiple times, restarted the app but it didn't help. 
* Also, what does it mean to "exit out of this task?" I just clicked the start bot. An app restart did not fix the problem.

![image](https://user-images.githubusercontent.com/8867670/101086165-52ad7300-3565-11eb-9b05-e50fab32ca78.png)

**Comment by scheyal** [comment]
FYI, once I shrunk my LU file, it started working again. (though issue is around debugging/messaging)

**Comment by cwhitten** [comment]
@scheyal we're bound to the errors that LUIS sends us. If you can provide the offending LU file we can see what LUIS is returning we can look for improvements to be made
