### ISSUE TITLE
Loss of data due to cutting (for pasting) of switch area

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5086]
## Describe the bug
* Working small bot - need to change logic slightly
* Small bot with a few dialogs.
* Cut a region to paste elsewhere with switch case, 2 dialog invokes, welcome message
* Screen turns blank, loss of work. Need to restart. See image.

![image](https://user-images.githubusercontent.com/8867670/101092132-031f7500-356e-11eb-93b8-fd451d26f99d.png)

## Version 
1.1.1-nightly

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce
*Unknown reproducability*
1. Cut a region of switch  logic, welcome message etc.
2. Screen turns blank. Data lost, got to re-write it.

**Comment by scheyal** [comment]
Debug info:

![image](https://user-images.githubusercontent.com/8867670/101092388-6f9a7400-356e-11eb-8ea5-b85403836812.png)

**Comment by cwhitten** [comment]
@scheyal is there a reason you're on a 1.1.x nightly and not the latest nightly?

**Comment by scheyal** [comment]
Yes - Used Tai's build for Orchestrator.

See also -  https://microsoft-my.sharepoint-df.com/:v:/p/eyals/EXkJaGfFT9hKulRK0SjYuuIBggtSbHISDPWtx24yvp63DQ?e=yndbEp

**Comment by scheyal** [comment]
Will try to repro with latest build in bugbash.

**Comment by scheyal** [comment]
No repro in bugbash bits.
