### ISSUE TITLE
Form not showing as preview feature 

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#5102]
## Describe the bug

![image](https://user-images.githubusercontent.com/3829387/101141170-dee79500-364e-11eb-8e12-d97c702be60d.png)

## Version

Latest main. You can see from the title bar. 

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by hatpick** [comment]
@boydc2014 That's because the previous release had this feature flag as hidden and it's persisted under your: %APPDATA%\BotFrameworkComposer\data.json file.

We need to reset the flags to default settings.

**Comment by cwhitten** [comment]
I'm looking at this. What I have working in the fix is to allow the `isHidden` default value to override the current value and persist into data.json.

**Comment by cwhitten** [comment]
re-opening. it worked fine on my machine!

**Comment by boydc2014** [comment]
> re-opening. it worked fine on my machine!

I will verify this soon.

**Comment by boydc2014** [comment]
> @boydc2014 That's because the previous release had this feature flag as hidden and it's persisted under your: %APPDATA%\BotFrameworkComposer\data.json file.
> 
> We need to reset the flags to default settings.

Yes, I guess something wrong with my previous settings.
