### ISSUE TITLE
QnA pairs are being duplicated in the QnA knowledge base

### ISSUE THREAD

**Issue by Markyboy944** [microsoft/BotFramework-Composer#5104]
QnA pairs are being duplicated in the QnA knowledge base (Composer V 1.2.1)

Windows 10 os

Add a question/answer pair in the composer
Go to 'Restart bot'
Go to QnA maker (in cloud) to see knowledge base
Click on knowledge base
There are 2 instance of each pair rather than 1 instance or each pair
![image](https://user-images.githubusercontent.com/5471850/101144865-dd977780-3610-11eb-95b8-7c744e149b81.png)

**Comment by hcyang** [comment]
Hi @Zerryth, any update?

**Comment by tonyanziano** [comment]
@Zerryth were you able to get a repro on this?

**Comment by Zerryth** [comment]
Confirmed! I get the same results as @Markyboy944 when adding a QnA pair to KB via Composer.

![image](https://user-images.githubusercontent.com/35248895/101397233-45ec9000-3881-11eb-98ac-51203803c80e.png)

**Comment by hibrenda** [comment]
@lei9444 be aware of this issue.
