### ISSUE TITLE
Grouping Dialogs

### ISSUE THREAD

**Issue by Laktos** [microsoft/BotFramework-Composer#5107]
## Is your feature request related to a problem? Please describe.

We have 30 dialogs and even more triggers, which are related to different kinds of conversation flows. A lot of these aren't related to each other, but we still end up looking through the list to find our dialogs when we go between them to write references etc. 

Another problem, somewhat related is that we have to copy the code of each adaptive card we want to reuse on multiple dialogs, will bring this up in additional context. 

## Describe the solution you'd like

I'd like to be able to create categories that can be expanded and collapsed, created on the same "Add" menu as the triggers/dialogs. This would greatly reduce the time for us looking for the dialogs we want to edit. We felt like the ability to create a lot of dialogs feels a bit like object oriented programming, and makes reusing certain dialogs easier. 

## Describe alternatives you've considered

Maybe "parent-dialogs". This would also be great for keeping adaptive cards separate for an entire group of dialogs. 

## Additional context

The last idea of having a parent dialog brings me to another problem we've had, and that's that we have had to copy the code of each adaptive card that we want to use on multiple dialogs, it would be neat if we could save those as "global cards". This would reduce the amount of having to change values of multiple cards, and reduces the chance of bugs.

**Comment by garypretty** [comment]
Thanks @Laktos.  We will add this to our backlog to be considered in future planning phases.

**Comment by hibrenda** [comment]
@Laktos , you can store the adaptive card in LG common file, so the entire dialog can reuse it. 
![image](https://user-images.githubusercontent.com/43408889/101437872-19517a80-394c-11eb-8891-ca82c8dd8d90.png)
