### ISSUE TITLE
Carousel card layout does not work with foreach function

### ISSUE THREAD

**Issue by tannguyen3** [microsoft/BotFramework-Composer#5111]
## Describe the bug
I'm trying to display a Carousel cards for my api result. the result is an array. So I tried to use below code to do so.
But it seems Carousel card layout does not work with foreach function see the TestAdaptiveCard2.
It does work with normal array object. 
Please help.

## Version

Bot Composer 1.2.1

## To Reproduce
This is bot response in lg file:
```
# TestAdaptiveCard()
[Activity
    Text = Welcome
    Attachments = ${PrepareCards()}
    AttachmentLayout = carousel
]

# TestAdaptiveCard2()
[Activity
    Text = Welcome2
    Attachments = ${PrepareCards2()}
    AttachmentLayout = carousel
]

# PrepareCards2()
- ${foreach(createArray(1,2,3), u, json(WelcomeCard('foreach')))} 

# PrepareCards()
- ${createArray(json(WelcomeCard('array')), json(WelcomeCard('array')), json(WelcomeCard('array')))}

# WelcomeCard(text)
-```
{
  "type": "AdaptiveCard",
  "body": [
    {
        "type": "TextBlock",
        "text": "Adaptive Card with ${text}"
    },
    {
      "type": "Image",
      "url": "https://adaptivecards.io/content/cats/1.png"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2"
}
    ```
```


## Browser

<!-- What browser are you using? -->

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

<!-- What operating system are you using? -->

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by hcyang** [comment]
Hi @jwiley84, it looks like @tannguyen3 needs help iterating a Carousel object.

**Comment by dmvtech** [comment]
Thank you for reporting @tannguyen3. I'm investigating.

**Comment by dmvtech** [comment]
Able to reproduce. Not sure why passing a array in works:
```
# PrepareCards2()
- ${foreach(dialog.myarray, u, json(WelcomeCard(u)))}
```

But in-place doesn't. 
```
# PrepareCards2()
- ${foreach(createArray(1,2,3), u, json(WelcomeCard(u)))} 
```

@boydc2014 Any pointers here? is this a bug, or is there some other approach that needs to be done.

**Comment by dmvtech** [comment]
Also @Danieladu for input.

This is similar to: https://github.com/microsoft/BotFramework-Composer/issues/4613

**Comment by Danieladu** [comment]
There is an extra whitespace at the end... It would make the expression as a concatenation operator of an array and a string ' ', and output such format: "[Array] ".

**Comment by tannguyen3** [comment]
thank you @Danieladu. It works now. it's just crazy
