### ISSUE TITLE
Restart Composer automatically or prompt for restart when 'Early Adopters' in Application Settings is selected

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/BotFramework-Composer#5114]
## Is your feature request related to a problem? Please describe.
Not sure what's the expected behavior after enabling Early Adopters or the Preview Features.   

## Describe the solution you'd like
Perhaps, some message to tell user to restart Composer?

**Comment by cwhitten** [comment]
@tsuwandy can you fill out the description a bit more with your ask? Screenshots, expected behavior, etc. Thanks!

**Comment by mewa1024** [comment]
Similarly, turning off early adopters to revert back to a major release gives the user no feedback or confirmation. A message in either telling the user that closing and reopening Composer will update/revert would be useful.
