### ISSUE TITLE
[R11 Bugbash] UI for single bot: Launch emulator with top menu single click

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5115]
Proposal: Have the launch emulator button for single bot solutions right up in the front. 
With earlier versions the "start emulator" button was right there. Now it is 2 clicks away. The earlier experience for single bot solution was better (not two hops away). Also, if we assume that most bot solutions would be a single bot in composer this would be the main path (something we don't know yet, but is reasonable).

**Comment by scheyal** [comment]
And Restart has now disapeared (again 2 clicks away)?

**Comment by cwhitten** [comment]
We're going to bring back the restart button in the top nav, and as soon as one of the bots are online we will automate opening the runtime manager so the Test in Emulator link is visible.

**Comment by srinaath** [comment]
We added a restart all bots button. In addition, when the operation is complete the panel opens up automatically.
