### ISSUE TITLE
bug: sample multiplydialog causes an error with the dialog merge required for package manager

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#5122]
## Describe the bug

When using the Javascript runtime, the package manager fails the "dialog merge" command scans the project for schema files.   This seems to be related to the sample multiply dialog code.

## Version

current main

## To Reproduce

1. Create a new bot
2. Navigate to project settings
3. Enable custom runtime
4. Get a new copy of the runtime. Choose Javascript.
5. Navigate to the package manager tab. (enable feature flag in settings if necessary)
6. PROBLEM! You will see the following error dialog:

![Screen Shot 2020-12-04 at 2 20 48 PM](https://user-images.githubusercontent.com/729873/101210937-f0737180-363b-11eb-989a-d2295b09a83c.png)

```
Error MultiplyDialog: Interface Microsoft.IDialog is not defined
```

This is because the dialog merge command sees the `MultiplyDialog.schema` file.

INTERESTING NOTE ---

This does NOT happen if I first start the bot.  Something must happen during the start local process (perhaps the schema is updated?) that prevents this issue from happening.

## Expected behavior

The disabled sample multiplydialog should not interfere with the schema merge process. This should be ignored until enabled.

## Suggested fix

rename `MultipleDialog.schema` to `MultiplyDialog.schema.sample`

**Comment by luhan2017** [comment]
@benbrown , I don't know how to reproduce this issue, but I assume the fix is, 
1. rename MultipleDialog.schema to MultiplyDialog.schema.sample
2. ask user to rename back it they want to enable custom schema in the doc
Is this your expected fix? 
I am not quite understand this: "This does NOT happen if I first start the bot." How can I reproduce this issue?

**Comment by benbrown** [comment]
@luhan2017 correct this should fix it.

Regarding my other comment -- I believe what happens is that when you start the bot the first time,he local publish process merges in the multiply dialog schema automatically. As a result, the multiplydialog schema is present in the main schemas/sdk.schema when the package manager goes to re-process the schema files, and does not cause this error.
