### ISSUE TITLE
[R11 bugbash] shift selection in property box doesn't work from right to left (only left to right)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5125]
## Repro
* create an object that needs Property filling
* add text to property
* Try to shift-left-arrow select text in the property. --> no selection
* (do the same from left to right and it works)

![image](https://user-images.githubusercontent.com/8867670/101213018-94562080-362e-11eb-8c3c-051f703e8a6c.png)

**Comment by yeze322** [comment]
MarqueeSelection
