### ISSUE TITLE
Package Manager - "Eject runtime" button at top of the page navigates to wrong window

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#5128]
## Describe the bug
In a new project, when I go to the Package Manager tab before ejecting the runtime, there is a message and button at the top that prompts me to eject, but it redirects to the wrong page.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Screenshots

![image](https://user-images.githubusercontent.com/27976702/101214289-a638c300-3630-11eb-9235-742bf79f622d.png)

**Comment by benbrown** [comment]
This has been resolved in #5088
