### ISSUE TITLE
[R11 Bug bash] "Common" links have vanished from the LG page

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#5131]
## Describe the bug

The LG page is supposed to have links in each bot to a "Common" dialog.

## Version

nightly 827857c

## Browser

- [X ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [X ] Ubuntu

## To Reproduce

1. Create a new EmptyBot
2. Navigate to LG page

## Expected behavior

There should be one "Common" dialog with WelcomeUser and one "EmptyBot-#" dialog with a Greeting of `${WelcomeUser()}`.

**Comment by thomas-chung** [comment]
To add, this ended up hiding the "WelcomeUser()" response for the EchoBot since that response is in the common.lg but is referenced by the individual dialog.lgs.

**Comment by beyackle** [comment]
I've got a fix for this I'll be putting into a PR soon.
