### ISSUE TITLE
When removing skills from project that's referenced, it should either cleanup the skill referenced in appsettings.json or show more meaningful error

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/BotFramework-Composer#5132]
## Description

When removing a connected skill from the bot project, any references in the root or other bot would error out with an error like this at the top level:

_"The skill 'dumbBot0' does not exist in in appsettings.jsonEchoBot-2"_

We can probably streamline this experience a bit by either doing:

1. Cleanup the project of any reference to the skill
2. Show more precisely inside the bot where things need to be fixed up, and maybe better phrasing because appsettings.json isn't something exposed readily in the Composer for people to edit nor is it actually what's required to fix the problem. Right now the error is top level, and in a large bot project this might be referenced in dozens of places. To fix, one simply has to delete the reference from the dialog, but it would help tremendously if the user knows where to go fix. 

## Version

                Bot Framework Composer

                Version:  1.2.1-nightly.191674.827857c
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0
              
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. From the main bot, connect to a new skill
2. Inside a dialog add reference to a skill (remote/local, doesn't matter)
3. Delete the skill

## Expected behavior

Either clear and concise way to tell the user how to resolve the problem and where to resolve the problem. Or
remove the skill from the dialog on behalf of the user.

**Comment by cwhitten** [comment]
We want to add a confirmation dialog similar to when we are deleting a dialog referenced somewhere else in the conversation like below:

![Screen Shot 2020-12-08 at 9 21 18 AM](https://user-images.githubusercontent.com/1156704/101521026-1a79ac00-393a-11eb-8eb4-797d9e44743e.png)

**Comment by sangwoohaan** [comment]
![Skill bots](https://user-images.githubusercontent.com/50963385/101555947-8c6be880-396e-11eb-954b-f4bd9a6387a4.png)

This would do.

https://www.figma.com/file/LlTlh5vXwq91zjGnFtrUUR6l/Composer-main-design-spec-UI-library?node-id=7576%3A211

**Comment by cwhitten** [comment]
@srinaath this needs an owner. At the next authoring standup lets go through unassigned issues

**Comment by srinaath** [comment]
@cwhitten  Will find an owner for this ticket.
