### ISSUE TITLE
being able to cancel "starting bot"

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#5135]
## Is your feature request related to a problem? Please describe.

The "starting bots" is taking too long. I want to cancel it. see screenshot below.

![Screenshot 2020-12-04 at 13 16 11](https://user-images.githubusercontent.com/74994573/101215673-15171b80-3633-11eb-8cff-58f401d09564.png)

**Comment by xiyangdesign** [comment]
Also applies to other ...ing, e.g. "generating dialog", "publishing", etc. Sometimes it takes time, other times, it's broken. Users shouldn't need to wait for so long to get the results.

**Comment by mewa1024** [comment]
Similar feedback in discussion #7183. Adding this to fit-and-finish EPIC #8107.
