### ISSUE TITLE
Minor: Add tooltip documentation for properties of type 'list'

### ISSUE THREAD

**Issue by pavolum** [microsoft/BotFramework-Composer#5138]
## Is your feature request related to a problem? Please describe.
Minor issue when entering multiple values for a property with property type list. Intuitively I separate list values by a comma which leads to the red error border to appear around the property. Nothing in the UI indicates why the comma seperated list is erroneous or tell the user to add each item and click 'enter' to indicate a new entry as opposed to a comma.

## Describe the solution you'd like

It makes sense to not use a comma as a separator as an individual list item may want to contain a comma, so perhaps adding to the tool tip for Accepted Values some documentation on how to separate list items or a more specific error when the red border is rendered beyond 'property has error(s)'

## Additional context

![image](https://user-images.githubusercontent.com/22845013/101216381-a343cf80-363c-11eb-8e33-07fd5494ef92.png)

**Comment by mewa1024** [comment]
@hatpick Can this be changed so that typing a comma acts like pressing Enter? Could users escape a comma, for example like "New York\, NY"?
