### ISSUE TITLE
[R11 Bugbash] Tree expand suggest expansion for bottom level items when it doesn't exist in Bot Responses and User Inputs panes

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/BotFramework-Composer#5140]
## Description

When navigating the tree structure under the following pages:

- Bot Responses
- User Input

The individual dialogs in the tree suggest that it can be expanded/hidden and some nested organization can happen. However, when clicking on the item it does nothing except moving the arrow sideway/down.

Instead I think it should look more like what we show in QnA since right now it's more a 2-level tree.

## Version

                Bot Framework Composer

                Version:  1.2.1-nightly.191674.827857c
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to either Bot Response or User Input
2. Navigate the side pane for the dialogs
3. Click on the little arrow on the left of the dialog name

## Expected behavior

Should just be the logo for the dialog

## Actual behavior
It expands/contracts but nothing new shows.

## Screenshots

![image](https://user-images.githubusercontent.com/9922190/101216985-58728980-3635-11eb-89bf-2a5ddd3b964a.png)
![image](https://user-images.githubusercontent.com/9922190/101216993-5e686a80-3635-11eb-8c9e-b7281f9a9d83.png)

**Comment by cwhitten** [comment]
This is addressed in the latest nightly
