### ISSUE TITLE
Need more guidance on creating a form dialog

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#5141]
![Screenshot 2020-12-04 at 13 30 40](https://user-images.githubusercontent.com/74994573/101217050-80fa8380-3635-11eb-9251-9c41cdce9f4c.png)

**Comment by mewa1024** [comment]
will dig deeper for 1.4.

**Comment by mewa1024** [comment]
Hi @xiyangdesign! As a stop-gap measure, do the instructions at [https://github.com/microsoft/BotFramework-Composer/blob/main/docs/preview%20features/form-dialogs.md](url) help?
