### ISSUE TITLE
FORM DIALOGS, schema UI: what does "priority" mean and how does it work

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#5144]
![Screenshot 2020-12-04 at 12 52 47](https://user-images.githubusercontent.com/74994573/101217761-bbb0eb80-3636-11eb-8cae-16dfbd2898f9.png)

**Comment by mewa1024** [comment]
Leaving this as is for 1.3 since this is described in the "Learn more" doc in GitHub, but will include in user tests for 1.4 (assigned to self.)

**Comment by mewa1024** [comment]
@xiyangdesign, similar to bug #5141, do the instructions at [https://github.com/microsoft/BotFramework-Composer/blob/main/docs/preview%20features/form-dialogs.md](url) help (as a temporary measure)?
