### ISSUE TITLE
Can't upload PDF to make knowledge base

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#5145]
## Describe the bug

I downloaded a PDF and tried to make a QnA knowledge base from it, but despite the "Enter a URL or browse to upload a file" placeholder in the box, there's nowhere (e.g. a 'Browse...' button) to start browsing for a file.

## Version

nightly 191674-827857c

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [X] Ubuntu

## To Reproduce

1. Enter a bot and choose "QnA" from the sidebar.
2. Click on a dialog
3. Click "Create new KB"
4. Observe the dialog - there appears to be nowhere to browse for local files.

## Expected behavior

There should be a way for me to browse my local filesystem and upload a file.

**Comment by zxyanliu** [comment]
I don't think it's supported.
See: https://github.com/microsoft/BotFramework-Composer/issues/5076

**Comment by srinaath** [comment]
@beyackle  thats a bad placeholder we have. It just supports from a URL

**Comment by cwhitten** [comment]
closing in lieu of #5076
