### ISSUE TITLE
In Bot Project, root bot appears at the same level as the skills bots

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5150]
## Describe the bug

In the flow of creating a bot project and adding skills/bots, the hierarchy between the bot project, the root bot, and the skills/bots is unclear. I can't tell if the bot project is a thing, or if it's just UI concept for grouping of one bot and the other bots it calls. The tree UI makes it appear that the bot project is a thing that contains multiple bots, but the flow of creating a new bot/bot project has no options to name or save the bot project separately from the root bot, so it kind of implies the bot project is not a separate thing from the root bot.

## Version

v1.2.1-nightly.191674.827857c

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. From home page, click **New**. This opens the modal that has the heading "Create a skill in your bot". Am I creating a skill, a bot, or a bot project?
![image](https://user-images.githubusercontent.com/39317542/101215234-51964780-3632-11eb-84ff-d77218c04c66.png)

2. Choose a template. 
This modal appears for you to name and describe the thing you are creating (is this the root bot or the bot project? or are they one and the same?):
![image](https://user-images.githubusercontent.com/39317542/101215345-899d8a80-3632-11eb-8913-cb9fe8be5285.png)

3. Clicking okay closes the modal and lands you on the Design page with the root bot open and the first trigger selected and all triggers expanded:
![image](https://user-images.githubusercontent.com/39317542/101216146-ddf53a00-3633-11eb-9ba1-c0ad8f22e85b.png)

4. Add a local skill. The skills appear in the tree with the same appearance as the root bot, so they look like they are peers, rather than one calls the other:
![image](https://user-images.githubusercontent.com/39317542/101216214-f6fdeb00-3633-11eb-8284-3561696307c6.png)

## Expected behavior

Overall, what is a bot project versus a root bot versus a skill/bot is not clear. For example, in the creation flow, if it was organized from biggest container inward, I could name and choose a location for my bot project first (currently step 2) and then choose a template for my root bot (step 1). For the bot project tree, the root bot should look more prominent than the skills. If the Bot Project is not a separate thing, maybe the tree UI doesn't need a "Your project" section.

**Comment by beyackle** [comment]
It looks like this was addressed in #5242 by adding `(Root Bot)` or `(Skill)` to the names of the bots in the tree.
