### ISSUE TITLE
Forms UI clipping

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#5151]
## Describe the bug

The forms UI layers over the "Required properties" label depending on screen size. See screenshot.

![FormsUI](https://user-images.githubusercontent.com/1139814/101218851-a50b9400-3638-11eb-8e61-b45b786215ae.PNG)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by hatpick** [comment]
Fixed in the branch, to be merged with main.
