### ISSUE TITLE
The Welcome bot creation journey tip is a bit overwhelming for new user

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/BotFramework-Composer#5152]
## Is your feature request related to a problem? Please describe.
 
![image](https://user-images.githubusercontent.com/10739108/101219510-fe73c300-3638-11eb-8b58-207dca8441c4.png)

For each tip, there are multiple steps user has to remember.    Not sure if user can remember all 5 tips.   Also once onboarding is closed, can't remember where to access it back.  :-)

## Describe the solution you'd like
Make onboarding less overwhelming for new users.

**Comment by mewa1024** [comment]
resolved by redesign for Composer 2.0.
