### ISSUE TITLE
[R11 Bugbash] Where is the export schema?

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/BotFramework-Composer#5153]
## Describe the bug

There is import schema on the form dialog UI, but where is the export so I can import?

## Version

                Bot Framework Composer

                Version:  1.2.1-nightly.191674.827857c
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to "Forms (Preview)" UI
2. Click "+" button to create new form dialog
3. Give it a name
4. Click "Import schema"

## Expected behavior

Able to find something to import. If the form is already there for my project, why do I need to import it? If I am sharing it with someone then how do I export and share it?

**Comment by mewa1024** [comment]
@hatpick Can we get this change in?
