### ISSUE TITLE
Use common file selection dialog between "Import Schema" and "Open" project

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/BotFramework-Composer#5155]
## Describe the bug

Opening a project gives us this beautiful UI where we can navigate the directory. However, "Import Schema" in Forms takes us to the OS native file picker. Perhaps we should align them to give user better experience.

## Version

                Bot Framework Composer

                Version:  1.2.1-nightly.191674.827857c
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to "Forms (Preview)"
2. Click "+" to create a new form
3. Give it a name
4. Click "Import Schema"

## Expected behavior

The same pretty UI file picker as the rest of the application.

## Actual behavior

The native OS file picker is used.

## Screenshots

![image](https://user-images.githubusercontent.com/9922190/101220970-89ee5380-363b-11eb-96e5-b14d14dd9427.png)

![image](https://user-images.githubusercontent.com/9922190/101220994-996d9c80-363b-11eb-80a7-1fe701d534a0.png)

**Comment by mewa1024** [comment]
Will revisit for Composer 1.4.

**Comment by mewa1024** [comment]
(pro of OS file picker over custom one: built in searching and sorting)
