### ISSUE TITLE
[R11 Bugbash] "Generate dialog" is available in actions menu before main button is enabled

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#5157]
## Describe the bug

When creating a form dialog, you are unable to generate the dialog from a form until the form is in a valid state. However, there are two ways to generate the dialog, and they each have a different idea of when the form is valid.

## Version

BotFramework-Composer-1.2.1-nightly.191674.827857c

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a form
1. Observe that "Generate dialog" is disabled in both the actions menu and the editor
1. Add a new property but don't name it
1. Observe that "Generate dialog" is still disabled in the editor but is now enabled in the actions menu
1. Name the property, bringing the form into a valid state
1. Observe that "Generate dialog" is now enabled in the editor
1. Delete the property, returning the form to its starting state
1. Observe that "Generate dialog" has become disabled again in the editor but is still enabled in the actions menu

## Expected behavior

"Generate dialog" should behave the same in both places, becoming enabled at the same time for both and becoming disabled again at the same time for both

## Screenshots

![image](https://user-images.githubusercontent.com/41968495/101221879-77751980-363d-11eb-8593-da682401597f.png)

**Comment by benbrown** [comment]
This has been fixed!
