### ISSUE TITLE
Intro help tour bubble placements

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#5160]
Low Pri:
- Just installed Composer, and really liked the tour intro.
- I like it went over major concepts and how they related.

- It states "Add a welcome message" and then gives detailed steps on how to do this.  It would be good to be able to have a link, so you could open up the instructions in a separate window.  In the tour, you click next and you kind of lost your guidance. 

![image](https://user-images.githubusercontent.com/6182197/101223279-890bf080-3640-11eb-96d1-76a2d8fe3ef4.png)
- The bubble shows you click on toolbar Add.  The bubble comes out of the "Edit" menu.  However Edit doesn't have add.  This is what I see:
![image](https://user-images.githubusercontent.com/6182197/101223402-d4be9a00-3640-11eb-9d08-e93adf8b4860.png)

I'm not sure where this toolbar "Add" button is..

**Comment by mewa1024** [comment]
Fixed in Composer 2.0.
