### ISSUE TITLE
Can we create a root bot from a QnA maker knowledge base template? 

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#5164]
## Describe the bug

Not sure if my understanding is accurate. This might be a bug.
Can we create a root bot from a QnA maker knowledge base template? If we can, what are the instructions?

## To Reproduce

1. Select **New**
2. Select **Create from knowledge base (QnA Maker)**
3. Enter a name and select **Next**
4. Can get an empty bot named QnASample but what am I suppose to do next?

## Screenshots

![image](https://user-images.githubusercontent.com/32497439/101228430-8a451980-3650-11eb-9471-3b20f93f3309.png)

![image](https://user-images.githubusercontent.com/32497439/101228446-9af58f80-3650-11eb-99d9-7813121eb4ff.png)

**Comment by zhixzhan** [comment]
My understanding is yes. 
Like other bot created from template, it can be a root bot of several skill bot, or a single bot enabled QnA.

**Comment by zxyanliu** [comment]
Yes, it worked using the most recent main.

![image](https://user-images.githubusercontent.com/32497439/101419927-f2406d80-38a5-11eb-972c-67167bec42fd.png)
