### ISSUE TITLE
Icon over crowding in Bot menu

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5168]
The error icons that appear on Bot navigation hide the **more** icon.

<img width="207" alt="Screen Shot 2020-12-04 at 5 14 56 PM" src="https://user-images.githubusercontent.com/67944302/101229298-64ba0f00-3654-11eb-9305-faca281a083e.png">

## Browser

- [ ] Electron distribution

## OS

- [ ] macOS

## To Reproduce

1. Add a new skill to the bot project
2. Choose a skill with Luis
3. See the error icons appear in front of the Skill name

## Expected behavior

I do not expect 2 error icons to appear. Showing me just one icon is enough to indicate that I need to take more action to activate this skill.

I also expect core 'actions' of the menu to be visible on hover.

**Comment by mewa1024** [comment]
Looks like this has been fixed:
![image](https://user-images.githubusercontent.com/39317542/124310142-9f1f5800-db20-11eb-9095-7fa062abb418.png)
 
Name truncates to make room for error/warning icon and ... (more button) remains visible at rest when this happens.
