### ISSUE TITLE
Copy:: Bot or Skill???

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5169]
## Describe the bug
<img width="500" alt="Screen Shot 2020-12-04 at 5 22 49 PM" src="https://user-images.githubusercontent.com/67944302/101229494-6506da00-3655-11eb-9afd-a9ec3e9b82bf.png">

The fly out modal should have consistent messaging. If we are calling this a skill, we should make sure we do not interchange the terminology with bot. Also the copy can be improved in general.

Also, when I select new project > Open a new skill
<img width="375" alt="Screen Shot 2020-12-04 at 5 37 50 PM" src="https://user-images.githubusercontent.com/67944302/101229920-70f39b80-3657-11eb-8448-504967af1cd9.png">

I get the following model.. that asks me to open a bot..

<img width="982" alt="Screen Shot 2020-12-04 at 5 35 50 PM" src="https://user-images.githubusercontent.com/67944302/101229879-46094780-3657-11eb-81a0-c26ff37b05ee.png">

- [ ] Electron distribution

## OS

- [ ] macOS

## To Reproduce

1. Click on "..." of a skill
2. See the fly out menu

**Comment by mewa1024** [comment]
Closing this. (The Composer 2.0 UI uses "Add a bot" instead of "Create a new skill" and "Connect to an existing skill")
