### ISSUE TITLE
QNA File missing

### ISSUE THREAD

**Issue by BartH2020** [microsoft/BotFramework-Composer#5175]
When you set another default language e.g. nl-nl no QNA file are generated in the knowledgebase folder.
This results in an error message when you add for example a new dialogue.

To reproduce the bug do the following.
- Add a new language in settings.
- Make the new language the default language.
- Remove English as a language
- Go to the designer and add a new dialogue
- Name the new dialogue and click on submit.
- An error message appears.

Composer v 1.2.1
Browser = Firefox
OS = Windows 10

**Comment by hcyang** [comment]
Chris, by default en-us language, an empty QnA file is generated under a bot's knowledge-base\en-us folder, but the user expect to see a similar empty file when the language setting is changed to something else. Please reassign to a dev for further investigation.

**Comment by tonyanziano** [comment]
Hi @BartH2020 

Currently, multi-language QnA is not supported, but will be in an upcoming release. Stay tuned.

**Comment by compulim** [comment]
@tonyanziano can you bring it to the planning of R13?

**Comment by tonyanziano** [comment]
@compulim Sure I will mention this to the team.

**Comment by hibrenda** [comment]
addressed in #5822
