### ISSUE TITLE
Unable to edit a skill manifest 

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#5178]
## Describe the bug

Select to edit a skill manifest, but cannot edit the manifest.

R11 bugbash electron / Windows 

## To Reproduce

1. Select the hamburger menu of a skill bot
2. Choose **Create/edit skill manifest**
3. Attempted to edit the skill manifest file but cannot

## Screenshots

![image](https://user-images.githubusercontent.com/32497439/101263120-cb443900-36f7-11eb-9d19-cd789c9b9678.png)

![image](https://user-images.githubusercontent.com/32497439/101263174-2c6c0c80-36f8-11eb-8243-c574e08327c9.png)

**Comment by zhixzhan** [comment]
@zxyanliu this modal looks like hook up with `Show skill manifest` from property editor. `Create/edit skill manifest` works at my side (latest main)

![Untitled6](https://user-images.githubusercontent.com/49866537/101328960-b1e3ee00-38ab-11eb-800d-523987f83ddd.gif)
