### ISSUE TITLE
Bot name shows in the LUIS name field

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#5179]
## Describe the bug

The bot/skill names are shown in the **LUIS name** fields of the **Project Settings** page.

## To Reproduce

1. Create a bot from the template
2. Navigate to the **Project Settings** page
3. Under **External services** section, see the name was auto-filled in the **LUIS name** field.

## Screenshots

![image](https://user-images.githubusercontent.com/32497439/101264020-478b4c00-36f9-11eb-836d-a4db1bc33972.png)

## Additional context
This issue will cause customer confusion.

## Suggestion
Consider changing the text **LUIS name** to **Bot name**

**Comment by narulasrinivas** [comment]
@zxyanliu  - Which version of BOT composer you're using? I'm on v1.2.1

**Comment by cwhitten** [comment]
@zxyanliu this is by design, but to avoid the confusion lets change the label to say "LUIS application name" instead of "LUIS name". This allows a user to configure the application information Composer creates in the LUIS portal. cc @liweitian

**Comment by zxyanliu** [comment]
I see, thanks for the clarification.
"LUIS application name" makes more sense.

**Comment by zxyanliu** [comment]
> @zxyanliu - Which version of BOT composer you're using? I'm on v1.2.1

Hi, FYI. I used [v1.2.1-nightly.191866.90ec7cc](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.2.1-nightly.191866.90ec7cc)
