### ISSUE TITLE
[lu file] Failed to tie phaselist as a feature for an intent

### ISSUE THREAD

**Issue by tannguyen3** [microsoft/BotFramework-Composer#5181]
## Describe the bug
I've follow this article to [use phaseList as a feature for an intent](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lu-file-format?view=azure-bot-service-4.0#tie-features-to-a-specific-model).
But the bot can start with below error:
This is content of .lu file:
```
> add some example phrases to trigger this intent:
- view my ticket

@ phraseList  ticket(interchangeable) =
    - tickets, request, requests, incident, incidents
@ intent IT_Ticket usesFeature ticket
```

![image](https://user-images.githubusercontent.com/10743872/101295620-5f8bca00-37e4-11eb-8a86-4b86de7f9935.png)

## Version

1.2.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by feich-ms** [comment]
Hi @tannguyen3, thanks for your feedback. I just checked your case, there is indeed an issue here. But the work-around solution is also simple, just change your `phraseList` to `phraselist` in your definition line of `@ phraseList  ticket(interchangeable) =`. In the future, we will make it case insensitive, created a ticket to track this https://github.com/microsoft/botframework-cli/issues/1068.

**Comment by feich-ms** [comment]
I think we can close this ticket in composer side since it has an easy and efficient work-around solution for users.

**Comment by tannguyen3** [comment]
I got it. thank you @feich-ms
