### ISSUE TITLE
need to restart several times to start bot and error string is truncated on the pop up 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#5182]
## Describe the bug

- create a luis+qna bot (1 luis intent trigger + two qna kbs)
- click start bot can still hit following error 
![image](https://user-images.githubusercontent.com/43408889/101313271-ce266180-3890-11eb-84f7-86db70e59174.png)

- Workaround: restart 3 times can finally be successful
- Issue need to be fix : error message showed on the pop up window is truncated . 
- Expected results: need to show the full error string. 

## Version

Main (webhost)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
@srinaath for visibility

**Comment by liweitian** [comment]
Synced with @hibrenda.  The error cannot be reproduced. So this Pr only fixed the error message got truncated bug.
