### ISSUE TITLE
Use relative paths for bot projects

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#5193]
## Is your feature request related to a problem? Please describe.

Currently, adding new or existing skills to a bot project uses absolute paths rather than relative paths. This will be problematic in a team environment where developers organize their files differently.

![image](https://user-images.githubusercontent.com/12264946/101370480-8ba45b00-3877-11eb-811a-b2a239d0d71f.png)

## Describe the solution you'd like

I'd like to have the child projects be referenced using a relative path to the root project, for example

![image](https://user-images.githubusercontent.com/12264946/101370607-b1c9fb00-3877-11eb-80f4-4dd141f09d93.png)

## Describe alternatives you've considered

I manually edited the botproj file based on the screenshot above and was able to get this to work but it would be good if this would work out of the box.

## Additional context

From the UI perspective, it is not clear which one is the "root" bot and which ones are the child ones. It would be good to use a different icon or some UI hint that would let me know which one is the one that has the references. 

This is should also be clear in the open bot window so I can clearly see which one is the root and which ones is are the child ones:

In the screenshot below, ComplexComposerHostBot is the one with the external references and the ones above are the skills but it is not obvious from looking at it.

![image](https://user-images.githubusercontent.com/12264946/101371122-649a5900-3878-11eb-9187-2f326d00fcd0.png)

Consider introducing a botsln file (sort of like Visual Studio files) that allows you to organize projects in a solution without having to modify the botproj files.

**Comment by cwhitten** [comment]
cc @srinaath, relative paths for the bot projects were in the initial design -- is this still the case?

**Comment by srinaath** [comment]
@gabog Is this happening on the installer for the bug bash? The way we have designed is like how you have stated. All paths that connect a skill to the root bot are serialized relative to the root bot inside the .botproj file. I wonder if this was an intermediary nightly that created this file path wrongly. Could u delete the botproject file and reopen the bot and try connecting the skills. Let us know if it still creates an absolute path to the skill.

![](https://user-images.githubusercontent.com/13004779/101382075-62ca9880-386c-11eb-9405-83cb14ad523d.png)

**Comment by srinaath** [comment]
@sangwoohaan the differentiator in UI between a root bot and skill has been spotted by a few folks during the bug bash. Adding you for any UX update we could do.

**Comment by gabog** [comment]
Strange, I am not able to repro right now, but my first screenshot belongs to bots I tried to create using the bugbash build.

I'll try to continue to repro this but you can close it in a couple of days if I can't find a way to repro this.

**Comment by gabog** [comment]
Here are the steps to repro the issue:

1. Create a folder on your hard drive (R11Repro in my case)
2. Open composer and create a new bot in that folder:
![image](https://user-images.githubusercontent.com/12264946/101410366-371bd280-38ad-11eb-82e0-2fc6c4fef2bd.png)
3. Add a new skill to the bot
![image](https://user-images.githubusercontent.com/12264946/101410483-692d3480-38ad-11eb-8ba2-736cab502dba.png)
![image](https://user-images.githubusercontent.com/12264946/101410497-70544280-38ad-11eb-92e7-f1d5631cf8fd.png)
4. Open EmptyBot-0.botproj and note that it used the full path for the skill:
![image](https://user-images.githubusercontent.com/12264946/101410579-8d891100-38ad-11eb-8ebb-ad34b178c5b7.png)

**Comment by srinaath** [comment]
thanks @gabog  for the repro. looking into it now.
