### ISSUE TITLE
SKILLS UX: Add IsSkill checkbox to Project Settings

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#5194]
Right now all bots are created with IsSkill = true and I need to go to the Advanced Settings view in settings to change this. 

I would like to see a differernt icon (or different UI hint) in the project pane for bots that are root bots or bots that can be also called as skills

I would like to see an IsSkill checkbox in bot settings and not have to go and change this manually in advanced settings.

**Comment by srinaath** [comment]
@sangwoohaan

**Comment by mewa1024** [comment]
(@vivekkshankar is this still relevant in the new flow?)
