### ISSUE TITLE
Bot Response page, default view is difficult to edit template with multiple lines

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5207]
## Version

v1.2.1-nightly.192397.d88f6af

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Bot Responses.
2. Find a template that has multiple lines (either multiple response variations or a multi-line response), and select the responses:
![image](https://user-images.githubusercontent.com/39317542/101417416-890a2b80-38a0-11eb-95fd-634612291274.png)

3. If you try to use the arrow keys to move up or down a line, you select the previous or next template instead.

Conversely, if you try to add newlines to a single-line template, it deselects the text input. 
To get around this, you can edit in the "Show code" view:
![image](https://user-images.githubusercontent.com/39317542/101417640-e69e7800-38a0-11eb-8723-ed09860adc14.png)

but then if you switch back to the default view, the responses all appear on one line:
![image](https://user-images.githubusercontent.com/39317542/101417599-d4bcd500-38a0-11eb-8568-386a9d02a775.png)

## Expected behavior

In the default view, when a response template is selected, I'd expect to be able to use arrow keys to navigate within the field, like any text input. I'd also expect to be able use the Enter key to add new lines.

**Comment by zhixzhan** [comment]
Hi @mewa1024 , as you described above there are 3 items in this issue
1. Unable to use arrow keys to move up/down. 
There is a fluentui issue track this bug https://github.com/microsoft/fluentui/issues/12177

2. Press `Enter` key to add a new line.
Currently, you can `Enter` is submit, `Shift + Enter` is add a new line.

For single line switch to multi line case, you may need 
- 2.1 `Shift + Enter` switch current filed to multi line
- 2.2 Click active current filed
- 2.3 `Shift + Enter` add a new line


3. multi line template is not show up as multi line.
current detecting is template character's number, did not look for `NEWLINE`, I will fix it soon.
