### ISSUE TITLE
UX feedbacks of bot project publish

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#5219]
## Is your feature request related to a problem? Please describe.

The 'bot project' feature is awesome, however, when I was playing with the publish feature, I found several inconveniences:

1. Can delete a publish profile.
  ![image](https://user-images.githubusercontent.com/8528761/101456019-67777580-396e-11eb-95ac-4f5e647ffad2.png)
2. Can set a publish profile as default and make it appear at the first place in the dropdown:
  ![image](https://user-images.githubusercontent.com/8528761/101455567-c12b7000-396d-11eb-9a51-2ca81bceaf94.png)
  Alternatively, we can also consider auto-selecting the last published profile when entering the publish page instead of always selecting the first profile which might have been abandoned for a while.
3. Can publish bots separately instead of having only 1 process to publish all 'selected bots'.
    The consideration is, publish to Azure is time costing, user has to wait until an active publish task 'Bot_A' terminated before starting a new incremental publish task 'Bot_B'. There is neither a cancel button for existing tasks nor a single publish button for creating new tasks.

**Comment by yeze322** [comment]
@sangwoohaan Sangwoo are you interested in this scenario？

**Comment by sangwoohaan** [comment]
The default publish target thing seems interesting, we may want to hold onto it for now though. I can see we can connect the idea of it to publish environment settings in the future so I want to take a bit more time to tackle.
How about the dropdown remembering the target that was just used previously?
