### ISSUE TITLE
[MCS-DE-GO] Access to Skill Manifest Warning causes uncaught error type

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5222]
When clicking on the Warning on the "Notifications" page for the following warning
![image](https://user-images.githubusercontent.com/31212469/101462203-3a11d400-393c-11eb-85c5-475904dbe33b.png)

We receive the following error:
![image](https://user-images.githubusercontent.com/31212469/101462190-32eac600-393c-11eb-9c97-32974a1da51f.png)

@joaollq @goergenj @garypretty @benbrown @cwhitten

**Comment by cwhitten** [comment]
@goergenj can you provide a bit more information? What version of Composer, repro steps, etc. Thank you!

**Comment by goergenj** [comment]
@joaollq Please provide a quick update on the issue,

**Comment by joaollq** [comment]
Hi all, we found what was causing the issue.

The skill manifest URLs on our customer's environment require authentication.
We changed the getSkillManifest method to add a Bearer token to the HTTP request and we lost that code when merging to the newest version.

After adding again the Authorization header, the error disappeared.

**Comment by goergenj** [comment]
@cwhitten @garypretty Can you please add the support for authenticaiton as a feature request please.

@joaollq Please create a pull request for our solution for the team to review.

**Comment by cwhitten** [comment]
> @joaollq Please create a pull request for our solution for the team to review.

@joaollq is this on your plate? If/when please make sure to link the PR to this issue so we can track it correctly. Thanks
