### ISSUE TITLE
"new template“ in lg all up view will mess the lg format

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#5224]
## Describe the bug

1. create a todoluis bot
2. go to lg page
3. click "new template" in common lg 
4. input template name "welcome" and lg content "welcome"
![image](https://user-images.githubusercontent.com/43408889/101480685-feecc080-398e-11eb-9d82-5109307b85e0.png)
5. start bot will hit issues.
![image](https://user-images.githubusercontent.com/43408889/101480768-1c218f00-398f-11eb-9e82-8ef259857309.png)

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

**Comment by zhixzhan** [comment]
The correct LG template body should start with '-', but here inline editing filed component unable to show up the error.
