### ISSUE TITLE
[MCS-DE-GO] Syntax highlighting error "-"

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5225]
When adding a new Intent-trigger and adding new utterances, the syntax highlighing reports the leading "-" as an error.

![image](https://user-images.githubusercontent.com/31212469/101498435-62b1c200-396c-11eb-9724-0db7255696f9.png)

@joaollq @goergenj @garypretty @benbrown @cwhitten

**Comment by cwhitten** [comment]
@goergenj please provide more information, like which version of Composer you are seeing this on. Thanks.

**Comment by goergenj** [comment]
@cwhitten We have this on the Composer 1.2.2 hosted on a VM and on the Electron App as well. Cannot test with 1.3.0 because opening a Bot currently fails (#5356)

**Comment by cwhitten** [comment]
This is fixed in the latest version of Composer (1.3.1)
