### ISSUE TITLE
Need indication or handling of trailing whitespace in expressions

### ISSUE THREAD

**Issue by dmvtech** [microsoft/BotFramework-Composer#5227]
## Is your feature request related to a problem? Please describe.

This is relate to the issue [here](https://github.com/microsoft/BotFramework-Composer/issues/5111#issuecomment-740259962). Specifically if you have an expression that ends in whitespace, the end result will be a concatenation of whatever the expression should be with that whitespace. This can be very hard to troubleshoot if you don't know what to look for.
```
# template1
- ${​​​​​​​1}​​​​​​​ // LG return an number
- ${​​​​​​​1}​​​​​​​abc // LG is concatenating the number with the string abc
- ${​​​​​​​1}​​​​​​​(space character)    // LG is concatenating the number with as space, and turns into string
```

## Describe the solution you'd like

Need some sort of warning, glyph, color, Intellisense or other indication that this is happening.

**Comment by dmvtech** [comment]
@boydc2014

**Comment by dmvtech** [comment]
#5111

**Comment by benbrown** [comment]
@lei9444 can you investigate whether it is possible to turn on visible whitespace characters in order to highlight trailing whitespace chars that could interfere with LG and expressions?

**Comment by hatpick** [comment]
https://github.com/microsoft/monaco-editor/issues/1932

**Comment by boydc2014** [comment]
> @lei9444 can you investigate whether it is possible to turn on visible whitespace characters in order to highlight trailing whitespace chars that could interfere with LG and expressions?

Agree, @benbrown that's also what i was talking with Dana. We should give good indicator in Monaco editor for trailing space. I'm re-assigning this to @zhixzhan, who was primarily working on Manaco and LSP integration. 

And, thanks @hatpick for the information. 

@zhixzhan can you follow up see what's the options here.

**Comment by zhixzhan** [comment]
> > @lei9444 can you investigate whether it is possible to turn on visible whitespace characters in order to highlight trailing whitespace chars that could interfere with LG and expressions?
> 
> Agree, @benbrown that's also what i was talking with Dana. We should give good indicator in Monaco editor for trailing space. I'm re-assigning this to @zhixzhan, who was primarily working on Manaco and LSP integration.
> 
> And, thanks @hatpick for the information.
> 
> @zhixzhan can you follow up see what's the options here.

Sure, I will fellow this.
