### ISSUE TITLE
FORM DIALOGS: Confusion over two "date-time" field types

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#5232]
## Describe the bug

There are two field types that both seem to be a date/time (`date-time` and `datetime.schema`). The difference is unclear.

## Version

192805.f738895

## Expected behavior

Either clarify the difference between `date-time` and `datetime.schema` or remove one.

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/101525683-7a735100-3940-11eb-9be8-9a08e8479141.png)
![image](https://user-images.githubusercontent.com/61990921/101525913-d211bc80-3940-11eb-8b7b-9117ed55b550.png)

**Comment by hatpick** [comment]
@mewa1024 as you know, one is coming from templates and one is JSON schema valid format for string values, what do you think?

**Comment by mewa1024** [comment]
Yes, I think Chris described that for most cases "datetime.schema" is the better one for most situations. Let's address it in the GitHub doc for now.
