### ISSUE TITLE
Start bot error window cuts off long messages

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5233]
## Describe the bug

Minor thing: when my bot fails to start, the window that shows the error is too narrow for me to see the full message.

## Version

1.2.1-nightly.192562.25b5869

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create and start a bot.
2. If you're bot fails, expand the message window by pressing the button to the right of the start button:
![image](https://user-images.githubusercontent.com/39317542/101527500-efe02100-3942-11eb-8580-7a272f610c60.png)

3. Click on "See Details". Another callout appears that is too narrow for a line of text to appear:
![image](https://user-images.githubusercontent.com/39317542/101527573-0ab29580-3943-11eb-9fd1-22b0eaf244d5.png)

## Expected behavior
Some way to see that text, possibly one of these:
- allow text wrap
- add scrollbar
- allow for scrolling if I click into the text

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/5182
