### ISSUE TITLE
Document cross-training parameters

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5235]
## Describe the bug
Customer asked how to configure downsampling parameters?
What are these values, range, and how to tune up with those values?

```
"downsampling": {
"maxImbalanceRatio": 10,
"maxUtteranceAllowed": 15000
},
```

## Browser

- [X ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Set up a qnamaker/luis dispatched Composer solution
2. Finetune routing - when hitting misroutes, try to fix using downsampling parameters

## Additional context
Sample instructions for cx from another thread(need more info):

...
So here are some suggestions for the customer to improve the models:
1. Add more luis utterances for each lu intent in LeavesBot.lu
2. Increase the down-sampling maxImbalanceRatio parameter in bot settings to make the DeferToQnA include more utterances
3. Avoid adding similar utterances to luis and qna models

--> Cx: how do I modify downsampling parameters? What're the ranges, and impacts of changes?

**Comment by scheyal** [comment]
Also, lots of articles on the subject, none of which really explains this section (need composer specific config explanation).

* https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-cross-train?view=azure-bot-service-4.0
* https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-cross-train?view=azure-bot-service-4.0

**Comment by hibrenda** [comment]
I have such discussion with @zxyanliu before for setting document.

**Comment by scheyal** [comment]
(also from Fei...)

maxImbalanceRatio is used to specify the sampling ratio when utterance amounts of each intent are significantly biased. For example, if we have a lu file in which intent A has 2 utterances and intent B has 100 utterances, the maxImbalanceRatio is set to 10, then the down-sampling mechanism in composer will sample intent B utterances amount to 2*maxImbalanceRatio = 20. But if we set maxImbalanceRatio to a larger number such as 30, then it will be sampled to 2*30 = 60. If we don't want sampling take effects on intent B, we can set this ratio to a much larger number  and make sure the least amount utterances intent * ratio >= the largest amount utterances intent. In this case, we can set ratio more than 50, then 2*50 >= 100.
...
