### ISSUE TITLE
Descriptions for Missing() and Change() seem switched

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#5236]
## Describe the bug

After a form dialog is generated, the descriptions of the Missing() and Change() action seem to refer to what the other should do. "Missing" currently says "has a value but is being changed", while "Change" says "adding expected value to empty property".

## Version

192805.f738895

## Expected behavior

Comments should correctly describe the actions they belong to.

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/101532683-bf4fb580-3949-11eb-8065-12f48b9a9b0f.png)
![image](https://user-images.githubusercontent.com/61990921/101532700-c4ad0000-3949-11eb-85b5-7ce16d190d36.png)

**Comment by mewa1024** [comment]
Should the nodes on the canvas not be showing comments anyway? (@sangwoohaan?)

**Comment by hatpick** [comment]
Fixed in the latest generate library.
