### ISSUE TITLE
Exported solution with QnAMaker configuration is not fully functional due to missing KB Id

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5244]
## Describe the bug
Export a bot with a few (1+?) QnAMaker KBs. Fill in new KB Id in settings. Start bot, and KB queries will show up in trace with error messages:
```
Unable to find a QnA Maker service with Knowledge Base ID ...ea60a... Please add a QnA Maker service to your bot.
```

Bot configuration is correct (and data shows up in the portal):

```
 "qna": {
    "subscriptionKey": "...",
    "knowledgebaseid": "",
    "endpointKey": "...",
    "hostname": "",
    "qnaRegion": "westus"
  },

Also,

>findstr /sip *...60a544 *
generated\qnamaker.settings.composer.westus.json:        "Obfuscated": "...60a544",
generated\qnamaker.settings.composer.westus.json:        "Obfuscated": "...60a544",
generated\qnamaker.settings.composer.westus.json:        "Obfuscated": "...60a544",
...

{
    "qna": {
        "Obfuscated": "...60a544",
        "hostname": ".../qnamaker",
        "Global_source_en_us_qna": "...60a544",
        "Obfuscated_en_us_qna": "...60a544",
        "Obfuscated_source_en_us_qna": "...60a544",
        "Obfuscated_source_en_us_qna": "...60a544",
        "Obfuscated_source_en_us_qna": "...60a544"
    }
}




```

## Version

V1.2.1-nighly.192805.f738895

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Export bot solution created by GA version with LUIS & QnAMaker KB
2. Load bot solution into latest nightly (as of 12/8)
3. Fix settings error and fill in valid QnAMaker & LUIS Keys, endpoint
4. Start, run

## Expected behavior

No errors, newly KB Id's are used.

## Screenshots

![image](https://user-images.githubusercontent.com/8867670/101553909-74926580-396a-11eb-8c33-135634aa082e.png)

## Additional context

* Also inspected portals and LUIS and QnAMaker data looks good on the portal.

**Comment by scheyal** [comment]
KB does exist on portal as was published by Composer engine.

```
POST /knowledgebases/....60a544/generateAnswer
Host: https://qnaexamples.azurewebsites.net/qnamaker
Authorization: EndpointKey <obfuscated>
Content-Type: application/json
{"question":"<Your question>"}
```

**Comment by cwhitten** [comment]
@scheyal this by-design in the Emulator. You need to create a .bot file in the Emulator and add your QnA service to make the error go away if you want to see the trace information.
