### ISSUE TITLE
Publish page issues

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#5246]
![Screen Shot 2020-12-08 at 4 26 52 PM](https://user-images.githubusercontent.com/1156704/101557708-65afb100-3972-11eb-90ea-03a597c18e17.png)

![Screen Shot 2020-12-08 at 4 25 29 PM](https://user-images.githubusercontent.com/1156704/101557730-706a4600-3972-11eb-9427-c1250f0d3c41.png)

![Screen Shot 2020-12-08 at 4 27 18 PM](https://user-images.githubusercontent.com/1156704/101557713-66484780-3972-11eb-844c-206bfedad89a.png)

![Screen Shot 2020-12-08 at 4 27 51 PM](https://user-images.githubusercontent.com/1156704/101557715-66484780-3972-11eb-986b-e2155877a972.png)

**Comment by boydc2014** [comment]
Note: column should be wider and text should truncate instead of overflow
