### ISSUE TITLE
Publish page UI issues

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#5262]
![Screen Shot 2020-12-09 at 10 38 26 AM](https://user-images.githubusercontent.com/1156704/101678939-80863200-3a13-11eb-9bc9-dd78b4288d7b.png)
![Screen Shot 2020-12-09 at 10 38 56 AM](https://user-images.githubusercontent.com/1156704/101678942-811ec880-3a13-11eb-9397-7895be270fde.png)
![Screen Shot 2020-12-09 at 10 37 41 AM](https://user-images.githubusercontent.com/1156704/101678943-81b75f00-3a13-11eb-91fc-018c688c31c1.png)
![Screen Shot 2020-12-09 at 3 30 47 PM](https://user-images.githubusercontent.com/1156704/101701352-9d326200-3a33-11eb-9111-ea438f9cdb7f.png)

**Comment by benbrown** [comment]
The status message that says "Retrieve publishing details ..." should really say "Deploying updates" as it occurs directly before the zip upload step.

**Comment by benbrown** [comment]
The notification does not always close when the publish completes.  This also seems to cause the polling process to continue after it has completed.

**Comment by alanlong9278** [comment]
@cwhitten The reason for interactible chevron miss is column width can be resize in detail List. I have checked with demo in fabric detailList component. So I think we can forbidden the resize function for column to fix the bug.
![detailList](https://user-images.githubusercontent.com/5860999/101756408-f3290780-3b10-11eb-9604-2b283c3c0dc2.gif)

**Comment by alanlong9278** [comment]
> The notification does not always close when the publish completes. This also seems to cause the polling process to continue after it has completed.

Add function to cancel notification after 5s. The polling process to continue after completed is because the clear logic is wrong. Have fixed it too. @benbrown
