### ISSUE TITLE
[when testing] object reference not set to an instane of an object

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#5269]
## Describe the bug

![Screen Shot 2020-12-09 at 4 40 46 PM](https://user-images.githubusercontent.com/74994573/101706580-42eace80-3a3e-11eb-88c4-2039ff5ecae4.png)

## Version

![Screen Shot 2020-12-09 at 4 48 01 PM](https://user-images.githubusercontent.com/74994573/101706600-5007bd80-3a3e-11eb-80ae-82ce3c3c98ef.png)

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Generate a dialog from 'forms editor' 
2. Add a trigger 'bookFlight', and link this trigger to the generated dialog.
3. Edit trigger phraeses, e.g. 'book a flight'
4. Test bot in Emulator
5. See error

**Comment by chrimc62** [comment]
Can you share your schema and bot?

**Comment by xiyangdesign** [comment]
I used the ToDoBotWithLUIS shown on the Composer homepage. I tried again just now using the latest nightly version. The error was gone!

Just FYI, in case it appears in the future:
schema: 
1. property name: origin (any string)
2. property name: dest (any string)
3. property name: date (any string - just to simplify the case)

Bot:
ToDoBotWithLUIS - the template
