### ISSUE TITLE
Generated form dialogs not grouping correctly

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#5271]
## Describe the bug

see screenshot below: generated form dialogs not grouping correctly

![Screen Shot 2020-12-09 at 4 31 02 PM](https://user-images.githubusercontent.com/74994573/101706939-0ff50a80-3a3f-11eb-8e55-5b400952681a.png)

## Version
![Screen Shot 2020-12-09 at 4 53 43 PM](https://user-images.githubusercontent.com/74994573/101706973-1c796300-3a3f-11eb-8a73-afd3c427ef50.png)

**Comment by beyackle** [comment]
This looks like it's been fixed in 193817.48689d3.
![image](https://user-images.githubusercontent.com/61990921/101813916-344df700-3ad2-11eb-87d4-f526f310ebb3.png)

**Comment by xiyangdesign** [comment]
Great!

**Comment by hatpick** [comment]
@xiyangdesign would you please share your schema (.form file under your bot files, form-dialogs folder)
