### ISSUE TITLE
FORM DIALOGS: be able to enter utterances/examples when collecting data through forms?

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#5272]
## Is your feature request related to a problem? Please describe.

When 'add property', would it be possible to enter examples of the property, e.g. "Paris", "New York" in the case of "origin" (the property name)

![Screen Shot 2020-12-09 at 4 37 36 PM](https://user-images.githubusercontent.com/74994573/101707122-6c582a00-3a3f-11eb-8ea9-299b86f68d8a.png)

**Comment by mewa1024** [comment]
(assigning back to you, @xiyangdesign, as the forms expert! :) )
