### ISSUE TITLE
page not found when click learn more for .net core install

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#5273]
## Describe the bug
I use my new pc to run composer, click start bot
<img width="1298" alt="WeChat256633f0e72d0ad1821e6dbcbf318231" src="https://user-images.githubusercontent.com/39758135/101712740-2b105a80-3ad1-11eb-8315-28b0da4ba635.png">

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by benbrown** [comment]
@zxyanliu can you help us track down the correct link for this?

**Comment by zxyanliu** [comment]
@benbrown I suggest the following link: 
https://aka.ms/install-composer
