### ISSUE TITLE
Recognized intents sometimes do not fire although recognized correctly.

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5286]
## Describe the bug
A recognized intent with high confidence (> 0.9) only is only activated for some utterences even if recognition score is very high. 
Repro is consistent (for specific bot).

## Version 
1.2.1-nightly.192805.f738895

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot (imported from customer scenario
2. run it
3. Try different utterances within the same intent/trigger

## Expected behavior
all recognized intents are handled by corresponding trigger

## Screenshots
Shows recognized intent with high score, specified in trigger going to unknown intent.
![image](https://user-images.githubusercontent.com/8867670/101821082-52205980-3adc-11eb-9304-2f2ea28a36d7.png)

**Comment by scheyal** [comment]
Filed on behalf of customer

**Comment by a-b-r-o-w-n** [comment]
@scheyal can we see the bot assets for this so we can investigate?

**Comment by cwhitten** [comment]
ping @scheyal
