### ISSUE TITLE
Keyboard focus is invisible on the "Add" circle and the zoom in/out/center buttons

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#5292]
## Describe the bug

Tab navigation across the Design View buttons is difficult when the visible focus vanishes.

## Version

 1.3.0-rc3

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open the Design view and make a new Trigger somewhere (just to keep the design view clean)
2. Press Tab until you go past the "Show code" button
3. Focus is on the "Add" thing, but it's invisible. If you stay there, the callout happens, but it's not immediate.
4. Hit Tab three more times - focus travels to Zoom In, Zoom Out, and Recenter, but it's still invisible
5. Hit Tab again and now it's visible in the property editor.

## Expected behavior

Buttons should have a distinctive appearance when focused.

## Screenshots

You can't see it, but focus is on the "zoom out" button here. If I hit Enter, it does the right thing.
![image](https://user-images.githubusercontent.com/61990921/101833876-6f5e2380-3aee-11eb-8df7-1217c6a6f819.png)

**Comment by alanlong9278** [comment]
@vivekkshankar  `Zoom toolbar`  dose not have the behavior for `focus` & `hover` status. Should we design behavior for it.
