### ISSUE TITLE
Expression dropdown doesn't work with KB nav

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#5294]
## Describe the bug

The dropdown menu of functions that comes up when you type `=` into an expression field can be navigated using the keyboard, but won't insert a function when selected.

## Version

1.3.0-rc3

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to the property editor for an action that can take an expression
2. Type an = into the box, and let the autocomplete menu come up
3. Navigate using the keyboard to pick out a function (this part, at least, works just fine)
4. Use Space or Enter to select the function
5. The field still has an = in it, and often the keyboard focus will be sent back to the beginning of the window (so hitting Tab takes you to the skill/locale indicator on top)

## Expected behavior

Hitting Enter should insert the function and, better yet, leave the first argument to the function selected so it can be directly filled in right there. The focus should at least stay inside the same field.

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/101837626-2f9a3a80-3af4-11eb-89e1-8b54e7f8a5b6.png)

**Comment by tdurnford** [comment]
This component was removed #6573
