### ISSUE TITLE
publishing JS runtime to azure functions results in a misconfiguration

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#5300]
## Describe the bug

When I publish a Javascript runtime to the Azure Functions target, I get an error in Azure:

![Screen Shot 2020-12-10 at 5 08 37 PM](https://user-images.githubusercontent.com/729873/101841726-1ef5be80-3b0c-11eb-88ee-1f43cd0472c6.png)

This may be related to the `FUNCTIONS_WORKER_RUNTIME` setting, which is always set to `dotnet`

![Screen Shot 2020-12-10 at 5 21 40 PM](https://user-images.githubusercontent.com/729873/101841767-392f9c80-3b0c-11eb-90b9-237b881da43c.png)

## Version

`wenyluo/provision` branch

## To Reproduce

1. Create an azure functions environment
2. Eject runtime and select JS
3. Publish to azure functions
4. Navigate to the azure portal and look at the "overview" tab - you will see an error.

## Expected Behavior

The publishing tool should set the necessary configuration to run the language I am using.

**Comment by a-b-r-o-w-n** [comment]
@luhan2017 was this addressed in the recent provisioning work that is in v1.3?

**Comment by luhan2017** [comment]
@a-b-r-o-w-n not yet... we are still investigating on this. will update later.

**Comment by benbrown** [comment]
This has been fixed in v2
