### ISSUE TITLE
KB navigation in Forms screen: Accept multiple values

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#5303]
## Describe the bug

When the "Property name/type" box is open, trying to toggle "Accept multiple values" with the keyboard results in the card collapsing instead.

## Version

1.3.0-rc3

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Enable Forms and go to the Forms page
2. Use the keyboard to navigate to the Add Property button (using Tab). Enter the contents of the card and navigate to the Allows Multiple Values box (this is a little clumsy, but not worth writing up as a bug)
3. Hit Space or Enter to check the box
4. The card collapses down to a single row instead, and the box is still unchecked

## Expected behavior

The Allows Multiple Values box should intercept confirmation events instead of letting them bubble out to the container.

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/101845496-aab71d00-3b03-11eb-8ce9-1899bb94a02b.png)

**Comment by GeoffCoxMSFT** [comment]
@hatpick I suspect this is no longer an issue, can you verify?
