### ISSUE TITLE
"Set a property" and "Set properties" -- do we need both? Can we just have "Set properties"?

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5317]
## Is your feature request related to a problem? Please describe.

If I add "Set a property" and then later realize I want to set more than one property, I have to go back and add a "Set properties" action.

## Describe the solution you'd like

Can we have just the "Set Properties" action, which allows for one or more propertes?
## Additional context

![image](https://user-images.githubusercontent.com/39317542/101938971-2616de00-3b99-11eb-8069-173a56149c83.png)

**Comment by a-b-r-o-w-n** [comment]
@mewa1024 I doubt that we will be able to remove this since it already exists in the SDK without causing breaking changes for customers. Please sync with @tomlm to discuss.
