### ISSUE TITLE
"HTTP request" dynamic parameters

### ISSUE THREAD

**Issue by DanieleS82** [microsoft/BotFramework-Composer#5328]
Hi, there is a way to set dynamically the fields "method" and "headers" of the component?
My idea is to use some inputs of a dialog, as value for these fields, something like:
`"method":"${dialog.httpMethod}"`

Similarly, for "headers", could be necessary to expand the input writing one row for each "key:value" pairs I want add to the section.

These changes could improve the flexibility of the component.

Thanks.

**Comment by dmvtech** [comment]
Hi @DanieleS82 There's not a way to do that within the **Http request** action itself. You could create a switch branch that switched on some property (say `dialog.httpmethod`) and each branch could have a different http request action with a set http method.

For headers, the values can be retrieved from an expression and set dynamically (from an array, etc), but the header key must be set explicitly. If your headers won't change per http method, I think this might be a decent approach.

If you would like these two features to be set via an expression|template, then we can label this as feature-request to see if it is something that would be possible to change.

**Comment by DanieleS82** [comment]
Hi @dmvtech, about the _method_ field, the branch to select which http request execute, is exactly the solution that I'm following now, but it's not an efficient solution.

About header field, have the possibility to dynamically set the key, would be the value add that would provide flexibilities at the component.

So yes, if it's possible, mark this as feature-request.

Thanks.

**Comment by dmvtech** [comment]
Hi @DanieleS82. This will have to start in the SDK before this can be implemented in Composer. Would you mind creating a new feature request [here](https://github.com/microsoft/botframework-sdk/issues/new?assignees=&labels=needs-triage%2C+feature-request&template=bot-framework-feature-request.md&title=) please?
