### ISSUE TITLE
Error during Quickstart 

### ISSUE THREAD

**Issue by balytca** [microsoft/BotFramework-Composer#5329]
Hi
Getting started with Azure bot composer but during  quckstart tutorial keep getting an error when i try to start the bot.
Error: Command failed: dotnet user-secrets init --project azurewebapp �� ������ �ᯮ��塞� 䠩�, ᮮ⢥�����騩 ������� "dotnet-user-secrets".
i'm using win10 pro, not sure what esle could be useful for this case.

**Comment by anusharavindrar** [comment]
Similar to #4339.
@balytca, what version of the composer and .NET Core SDK are you using? It is advisable to use .NET Core SDK 3.1 and above.

**Comment by balytca** [comment]
@anusharavindrar, thank you!
I didn't notice that my .NET Core SDK was outdated which caused this problem
