### ISSUE TITLE
Improve composer cleanup

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#5331]
Composer doesn't seem to cleanup temporary files that generates. 

I wanted to do a clean install of composer so I went to my machine's C:\Users\MyName\AppData\Roaming\BotFrameworkComposer folder and notice that I had 20 GB of files in the composer folder:

![image](https://user-images.githubusercontent.com/12264946/102138763-dc452680-3e2a-11eb-95f2-53f8192b83b0.png)

## Describe the solution you'd like

I'd like composer to cleanup after itself and keep the temp files to a minimum.

## Describe alternatives you've considered

I manually deleted the folder.

## Additional context

I kept a copy of the composer folder instead of deleting it, let me know if you want to take a closer look at it if you want. 

I looked at wat is in folder and each runtime for the bots seems to be using around 1.7 Gb, this issue may go away in the next version of composer when the runtime is in the same folder as the bot files, at least there I will be sure the runtime files are deleted when I delete my test bots, that said, it may it may be good to add a "clean" for each project.

**Comment by a-b-r-o-w-n** [comment]
@boydc2014 Can you investigate this? I have recently noticed this as well. 

I found that the `hostedBots` folder was the culprit. It would be worth looking into if we can periodically remove these files.

**Comment by gabog** [comment]
Also, as an alternative, consider putting temporary files in the user's temp folder, the OS will clean this up periodically.

**Comment by cwhitten** [comment]
Adding to R13

**Comment by boydc2014** [comment]
Thanks, @a-b-r-o-w-n and @gabog. 

It's mainly because the hostBots folder which contains runtime that can be large, and we didn't properly cleaned that up. So the proper fix to me is
* when deleting a bot, we clean the hostedBots/botid folder 
* we should clean the hostedBots folder periodically or in a certain timing (app close, maybe)

**Comment by gabog** [comment]
Hi, I think this may not be a big issue once we move the new creation experience since the runtime will be ejected by default and everything the bot needs locally will be in the working folder, right?

**Comment by boydc2014** [comment]
> Hi, I think this may not be a big issue once we move the new creation experience since the runtime will be ejected by default and everything the bot needs locally will be in the working folder, right?

Yes, agree.  So, probably a hotfix to delete extension content when deleting bot would be good enough, not necessary for a complete design of clean up.
