### ISSUE TITLE
Enhancement of LG and LU editing experience

### ISSUE THREAD

**Issue by cosmicshuai** [microsoft/BotFramework-Composer#5332]
# More comprehensive auto-completion
- [ ] Auto suggest entities from QnA and Luis recognizers results
Users can use entities from QnA and Luis recognizers, such as `@answer`(from QnA) or `@itemList`(from Luis), in LG, so the LG language server should be able to suggest these entities once user hit `@` in inline editor or all up view editor.

- [x] Dynamic property auto-completion
LSP should be able to complete the property user-defined via certain actions like Inputs, and SetPropertiy(s)

- [x] Support more static memory variables in LG language server auto suggestion. 
Currently, the static memory variables are missing some members, like class.xxx variables. Those variables can be found in the turnContext of a bot. We should add those missed ones to our static memory variables. 

# Correct return type info in hover
- [x] Hover on pre-built functions displays incorrect return type.

Decription: As shown in the image, the return type in hover actions is incorrect. It should display the correct type string instead of a integer. 
![image](https://user-images.githubusercontent.com/17074777/102450289-0556f880-4071-11eb-9b14-7f78d5143654.png)
The mapping between an actual type and an integer is:
    Boolean = 1,
    Number = 2,
    Object = 4,
    String = 8,
    Array = 16

# Supporting folding templates in LG and folding utterance LU.
- [x] Add folding range actions for LG and LU language servers.

Description: As we did in the adaptive tool for VSCode extension. We should support folding range actions in Composer.
LG folding should based on the templates:
![image](https://user-images.githubusercontent.com/28599459/92359834-760b8200-f11e-11ea-805d-2bf2223e7b59.gif)

Lu should based on the utterances:
![image](https://user-images.githubusercontent.com/28599459/92359834-760b8200-f11e-11ea-805d-2bf2223e7b59.gif)

**Comment by boydc2014** [comment]
@cosmicshuai please enrich this ticket with more information, for each item, please describe
* What is the current behavior
* What is wrong or not good in current behavior
* What is the changes proposal and why it's an effective change

**Comment by mewa1024** [comment]
@sangwoohaan for visibility

**Comment by sangwoohaan** [comment]
These look good to me.

**Comment by cwhitten** [comment]
@cosmicshuai what work is remaining here?

**Comment by cosmicshuai** [comment]
@cwhitten ReturnType display error has been fixed. LG & LU folding ranges are in PR now. I am working on LG definition and more suggestions about LG & LU

**Comment by cosmicshuai** [comment]
Verified The second item `Dynamic property auto-completion` works. No need to fix.
