### ISSUE TITLE
how to export and connect to a skill from consumer bot/documentation not updated

### ISSUE THREAD

**Issue by Samirun** [microsoft/BotFramework-Composer#5334]
**## Describe the bug**
new release of bot composer 1.3.0 is done due to which few things have changed.
I was trying to export a skill bot and connect to that bot within another bot 
by following documentation https://docs.microsoft.com/en-us/composer/how-to-export-a-skill.
Problem: how to connect to a skill ? and what is the difference between  skill endpoint and skill host end points?

**Changes observed** : 
1)skill host endpoint  previously used to be like  http://localhost:3983/api/messages now changed to  http://localhost:3980/api/skills
2) there used to be a skill section in UI where we can connect to another skill  using skill manifest json file of a sill bot as mentioned in the documentation
https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill
now how do i proceed further?

## Version : bot composer **1.3.0** (released yesterday)
# OS
- [ ] Windows

## To Reproduce
i have created 2 bots and generated manifest for skill bot and tried to use it in the consumer bot 
with recent changes i don't find any place where i could use skill manifest json of a bot  as a skill in any  consumer bot.
documentation https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill  says : Still on the Skills page, select + Connect to a new skill on the upper left corner of the toolbar to show the Add a skill windows."
now the problem is how to move forward from this step within bot composer 1.3.0?  i am unable to select " skill dialog name" and  "skill end point".
![image](https://user-images.githubusercontent.com/46156330/102181777-3993b300-3ed1-11eb-90cd-5d03d312a85a.png)
![image](https://user-images.githubusercontent.com/46156330/102181839-4a442900-3ed1-11eb-8e08-302fefe0dcbd.png)
skills section in the left panel has been replaced with project settings 

**QUESTIONS** : 
1)as the 1.3.0 release is few hours old  i  would highly appreciate  some quick guidance  over here how to use a skill bot in another consumer bot.
2)is there any alternative to export skill as a manifest  for bot to bot conversation?  we need some quick solution to this problem
can anyone of the team help us in this regard?

@zhixzhan

**Comment by zxyanliu** [comment]
Hi, FYI. The docs for [Composer 1.3](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.3.0) release will be updated and published soon.

**Comment by zxyanliu** [comment]
FYI. Composer docs just got published to live: https://docs.microsoft.com/en-us/composer/
Thanks!

**Comment by zhixzhan** [comment]
Thanks @zxyanliu.
@Samirun most skill related UX are moving to this contextual menu, please try it and feel free to ping me.
![image](https://user-images.githubusercontent.com/49866537/102301560-f9e0d000-3f91-11eb-9957-49bc61725a8a.png)

**Comment by zxyanliu** [comment]
@Samirun FYI. These are the skill-related docs you may find helpful: 
https://docs.microsoft.com/en-us/composer/how-to-export-a-skill
https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill

To provide accurate content, we will do docs patch releases in the coming few days. 

Thanks again for your feedback!

**Comment by Samirun** [comment]
great! really appreciate for the shared docs. thanks for the quick support.

**Comment by zxyanliu** [comment]
@Samirun Thank you for using Composer! We really appreciate your feedback.

**Comment by Samirun** [comment]
@zxyanliu  how to get manifest url for a  remote skill? or at least how to construct it? i think we also need documentation for this.

**Comment by zxyanliu** [comment]
Hi, FYI. I am working on the content you guys requested on the docs patch releases.

**Comment by zxyanliu** [comment]
FYI. I replied in another thread with content you may find helpful.
https://github.com/microsoft/BotFramework-Composer/issues/5350#issuecomment-747834390

**Comment by zxyanliu** [comment]
Hi @Samirun Did you get it to work? Please let us know if you have further issues with this.

**Comment by Samirun** [comment]
yeah it worked.No issues as of now. thanks

**Comment by zxyanliu** [comment]
Thanks for the update and thanks again for your feedback! 
I am closing this issue now because it has been addressed with updates to the [documentation](https://docs.microsoft.com/en-us/composer/). 
Thank you!
