### ISSUE TITLE
Provision issue with large arm token

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#5335]
## Describe the bug

Was unable to provision Azure resources from Composer.

![image](https://user-images.githubusercontent.com/32497439/102186121-fe5c9a00-3e66-11eb-9136-3b44826a762e.png)

## Version

[Composer 1.3](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.3.0)

## Browser

- [x] Electron distribution

## OS

- [x] Windows

## Additional text
arm token too large

**Comment by zxyanliu** [comment]
@VanyLaw @luhan2017 Do you guys plan to merge the PR to fix this error? I found another one complaining the same issue: #5377

**Comment by tiagonmas** [comment]
any news on solving this ?

**Comment by luhan2017** [comment]
@tiagonmas #5521  we had a PR to fix this issue, should be merged soon. will keep you posted.

**Comment by tiagonmas** [comment]
Issue is still present in v1.3.1-nightly.209116.285a040. Should this be closed before it's fixed in production ? @luhan2017 @zxyanliu

**Comment by orcelik** [comment]
Issue still persists with version 1.4.0 . I see this is closed. Do we need to open a new github issue for the same issue?

**Comment by SanUttarwar** [comment]
I am facing same issue.. I have upgrade Bot composer to 1.4 but issue still persist. Is there any fix for this ??

**Comment by Benjiiim** [comment]
I can reproduce the issue with 1.4.0 as well.
