### ISSUE TITLE
getting dotnet publish error after updating composer version

### ISSUE THREAD

**Issue by thakursarvesh** [microsoft/BotFramework-Composer#5337]
Hi Team, I was able to publish my code previously. Today I got update request in bot composer and I update the version to 1.3. Now I am getting the below error

"Error - Command failed: dotnet publish \"C:\\Users\\{UserName}\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\9e36815d717e993596f41ff12fdc9b76\\azurewebapp\\Microsoft.BotFramework.Composer.WebApp.csproj\" -c release -o \"C:\\Users\\{UserName}\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\9e36815d717e993596f41ff12fdc9b76\\azurewebapp\\bin\\release\\publishTarget\" -v q --self-contained true -r win-x64\n"

On checking the logs I found below issue -

```json
{
  "stack": "Error: Command failed: dotnet publish \"C:\\Users\\{UserName}\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\9e36815d717e993596f41ff12fdc9b76\\azurewebapp\\Microsoft.BotFramework.Composer.WebApp.csproj\" -c release -o \"C:\\Users\\{UserName}\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\9e36815d717e993596f41ff12fdc9b76\\azurewebapp\\bin\\release\\publishTarget\" -v q --self-contained true -r win-x64\n\n    at ChildProcess.exithandler (child_process.js:308:12)\n    at ChildProcess.emit (events.js:210:5)\n    at maybeClose (internal/child_process.js:1021:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)",
  "message": "Command failed: dotnet publish \"C:\\Users\\{UserName}\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\9e36815d717e993596f41ff12fdc9b76\\azurewebapp\\Microsoft.BotFramework.Composer.WebApp.csproj\" -c release -o \"C:\\Users\\{UserName}\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\9e36815d717e993596f41ff12fdc9b76\\azurewebapp\\bin\\release\\publishTarget\" -v q --self-contained true -r win-x64\n",
  "killed": false,
  "code": 1,
  "signal": null,
  "cmd": "dotnet publish \"C:\\Users\\{UserName}\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\9e36815d717e993596f41ff12fdc9b76\\azurewebapp\\Microsoft.BotFramework.Composer.WebApp.csproj\" -c release -o \"C:\\Users\\{UserName}\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\9e36815d717e993596f41ff12fdc9b76\\azurewebapp\\bin\\release\\publishTarget\" -v q --self-contained true -r win-x64",
  "stdout": "Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nC:\\Users\\{UserName}\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\9e36815d717e993596f41ff12fdc9b76\\core\\Microsoft.BotFramework.Composer.Core.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [C:\\Users\\{UserName}\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\9e36815d717e993596f41ff12fdc9b76\\azurewebapp\\Microsoft.BotFramework.Composer.WebApp.csproj]\r\nC:\\Program Files\\dotnet\\sdk\\3.1.403\\NuGet.targets(128,5): error : The process cannot access the file 'C:\\Users\\{UserName}\\.nuget\\packages\\microsoft.windowsdesktop.app.runtime.win-x64\\3.1.9\\runtimes\\win-x64\\lib\\netcoreapp3.1\\zh-Hant\\ReachFramework.resources.dll' because it is being used by another process. [C:\\Users\\{UserName}\\AppData\\Roaming\\BotFrameworkComposer\\publishBots\\9e36815d717e993596f41ff12fdc9b76\\azurewebapp\\Microsoft.BotFramework.Composer.WebApp.csproj]\r\n",
  "stderr": ""
}
```

It was working expected in previous version

**Comment by zidaneymar** [comment]
Hi @thakursarvesh , I think the error is mainly:
```
The process cannot access the file 'C:\\Users\\{UserName}\\.nuget\\packages\\microsoft.windowsdesktop.app.runtime.win-x64\\3.1.9\\runtimes\\win-x64\\lib\\netcoreapp3.1\\zh-Hant\\ReachFramework.resources.dll' because it is being used by another process.
```
This file is busy. Have you tried to restart your machine

**Comment by thakursarvesh** [comment]
Yes, before restarting it gave different file name and after restart this file name came. I tried again now and now I got this System.Design.dll' because it is being used by another process.

**Comment by zidaneymar** [comment]
@thakursarvesh, I think restarting your machine other than composer app, could help. I'm not sure what the problem is, I could not repro on my side. Could you try restart your machine and publish again?

**Comment by thakursarvesh** [comment]
@zidaneymar  Yes I restarted my machine itself.

**Comment by luhan2017** [comment]
Are they always coming from this folder? C:\\Users\\{UserName}\\.nuget\\packages\\microsoft.windowsdesktop.app.runtime.win-x64\\3.1.9\\runtimes\\win-x64\\lib\\netcoreapp3.1, could you please try to remove this package and try again?

**Comment by thakursarvesh** [comment]
I can only see till here "C:\Users\{UserName}\.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\3.1.9\runtimes" and it shows empty in my machine.

In the new version of composer I can see an extra attribute added in publish profile "runtimeIdentifier": "win-x64"  . Is this causing an issue?

**Comment by luhan2017** [comment]
> @zidaneymar @luhan2017 I can only see till here "C:\Users{UserName}.nuget\packages\microsoft.windowsdesktop.app.runtime.win-x64\3.1.9\runtimes" and it shows empty in my machine.
> 
> In the new version of composer I can see an extra attribute added in publish profile "runtimeIdentifier": "win-x64" . Is this causing an issue?

Maybe, could you set the runtimeIdentifier to win-x86 and retry? just to verify if it relates to win-x64 setting.

**Comment by thakursarvesh** [comment]
@luhan2017  I tried it but unfortunately this also didn't worked. Always getting same error as the file is already in use..

**Comment by luhan2017** [comment]
@thakursarvesh, could you confirm if this issue happens for v1.3 only? are you convenient to have a live debug session with us?

**Comment by thakursarvesh** [comment]
@luhan2017 Yes it started happening in v1.3 . Please let me know when we can connect for a live debug session. I am in IST time zone.

**Comment by luhan2017** [comment]
I am in Beijing, I am available at tomorrow 13-14pm, 15:30-16:30pm. which should maps to 11:30-12:30 and 13:00-14:00 on your side? Which one do you prefer? And could you please share your email account so that I can send a meeting request to you.

**Comment by gabog** [comment]
Close due to inactivity.

**Comment by MarcoWirtl** [comment]
@thakursarvesh @luhan2017  Whats the solution? Got the same error. Updated Bot Framework Composer, published to the same profile like before (last Publish: October 2020), just changed the access token.

**Comment by SandeepBhagoji202** [comment]
@thakursarvesh @luhan2017 . If Possible ,Can you please update what resolved this issue. I'm facing exactly the same error and have tried out every step here to resolve But Nothing's worked out.
