### ISSUE TITLE
Composer 1.3.0 Publishing to Azure Conditional access policy block

### ISSUE THREAD

**Issue by kallejar** [microsoft/BotFramework-Composer#5345]
## Describe the bug

With the new 1.3.0 version you have the nice publishing where you need to pass the credentials in the AAD form to get the token for publishing. This however doesn't work in our company we have Azure AD conditional access policies which now prevent me login in and publishing the bot.

e.g. case we might have external developers who use own device to access the services or like me who uses for developing personal computer (with more tools/resources available).

## Version

1.3.0

## To Reproduce

1. Publish bot to correct profile
2. Get Azure AD login prompt
3. Conditional access policy blocks login --> cannot publish to Azure (even as I have valid token configured to the config file manually/like in version 1.2.x)

## Expected behavior

I want to be able to
Get access token as until 1.2.x versions and configure that to the bot config json

OR

Have some toggle in the bot config(json) to tell how I want to authenticate e.g. use the token in config or use the Azure login the generate the token.

**Comment by luhan2017** [comment]
@kallejar thanks for your feedback, is this a blocking issue for you currently? we will prioritize this as a feature request in our next release.

**Comment by kallejar** [comment]
I downgraded back to 1.2.2, so I can work with that just fine :) Let me know when there is something I can test.

**Comment by taicchoumsft** [comment]
@garypretty , this appears to be a feature request, can you chime in as to prioritization?

**Comment by tannguyen3** [comment]
Same issue for me. please implement this feature.

**Comment by garypretty** [comment]
Suggest we address this in 1.4 - I have marked it as a P1 given 1.2 works right now.

@cwhitten can you assign as needed?

**Comment by cwhitten** [comment]
@kallejar and @tannguyen3 can you help clarify your needs?

I'm to understand that your company AAD policy has configured conditional access, requiring additional security measures in order to access Azure resources but you wish to workaround this constraint?

I'm happy to continue discussion, but as we see it now what was possible in 1.2.2 that you utilized wasn't a supported core scenario, and the behavior in 1.3 is more correct and expected.

**Comment by tannguyen3** [comment]
For me, my company has policy to grant publish permission for a special account which its password will be rotated every one hour, we need to sign in to a system to get the new password then with 1.2.1 I use 'az account get-access-token" to get the token for deployment.
With 1.3.0, I was able to login using the account, then few hours later it asked me to login again but keep throwing below error. I haven't been able to deploy since
![image](https://user-images.githubusercontent.com/10743872/103820854-a6165380-5032-11eb-9ead-675d211c7f04.png)

**Comment by cwhitten** [comment]
@tannguyen3 to debug this, can you do the following:

1. Start the application from a terminal with the following environment variable setting: `DEBUG=composer*`
2. Step through the authentication scenarios running into the error
3. Copy/paste `stdout` from the terminal to this issue

**Comment by luhan2017** [comment]
@tannguyen3 There is a logout button in the provision wizard as the following. Could you try to logout and login again as a work around?
![image](https://user-images.githubusercontent.com/32191031/103839544-964a4e00-50ca-11eb-94dd-d87189044b53.png)

@cwhitten, I think we may need to redesign on the logout feature, move from provision wizard to somewhere else in composer.

**Comment by tannguyen3** [comment]
@luhan2017 I dont see the logout.
![image](https://user-images.githubusercontent.com/10743872/103910818-e32e2480-50ca-11eb-8520-1d7af0fb2b56.png)

**Comment by tannguyen3** [comment]
@cwhitten this is the stdout after the login failed above.
![image](https://user-images.githubusercontent.com/10743872/103911282-6f404c00-50cb-11eb-8b5c-2f2e179144ad.png)

**Comment by cwhitten** [comment]
Thanks @tannguyen3.  cc @tonyanziano & @carlosscastro. This could be an edge case we aren't covering nicely.

**Comment by kallejar** [comment]
@cwhitten Sorry for the long delay in response (vacation and and tons of other things to run). 

So I had some discussion with our Infra team to check, if we could change our conditional access policy for the Bot Framework Composer and end result was that we are not making any changes there (too many rules that needs changing was the response). So I am fine moving this project work on other workstation which works or then I'll setup this in our Azure. 

However leaving final comments that maybe other authentication options could be still left there in the tool, but otherwise from my side you can close this or continue adding alternative login option to the tool.

Thanks for the great and easy tool to create bots :)

**Comment by srinaath** [comment]
@benbrown @luhan2017 Any update on this ticket?

**Comment by compulim** [comment]
@cwhitten do you think there are more to do in this issue or prefer to close it? Quoting from @kallejar so you can quickly decide:

> However leaving final comments that maybe other authentication options could be still left there in the tool, but otherwise from my side you can close this or continue adding alternative login option to the tool.
