### ISSUE TITLE
LG navigation pane shows all markdown links as imported LG files

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#5347]
## Describe the bug
When an LG file has a markdown link using the `"[]()"` syntax, it is shown in the left navigation pane. 
## Version
1.3

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
It should only show the imported LG files, not all the links.

## Screenshots
Here is the link in the LG template:
![image](https://user-images.githubusercontent.com/27976702/102285055-440e7680-3eea-11eb-9d67-396f6bce9b78.png)

Here is what shows up in the nav:
![image](https://user-images.githubusercontent.com/27976702/102285001-2b05c580-3eea-11eb-95be-acb2e3be769b.png)

**Comment by boydc2014** [comment]
Looks like we are using regex to match [](), we should use the parser result to get the exact result. @zhixzhan can you take a look at this and ask @hatpick for review.

cc @GeoffCoxMSFT
