### ISSUE TITLE
generated dialog is not updating after changes made to property type

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#5349]
## Describe the bug

When I made changes to the property type in schema, hit "generate dialog" again, the dialogs were not updating. 

## Version

![Screen Shot 2020-12-15 at 4 20 55 PM](https://user-images.githubusercontent.com/74994573/102288520-84252780-3ef1-11eb-92bc-b5c0e4f9d0f2.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [X] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Forms'
2. Click on a [property name], change the type from 'number' to 'any string'
3. Click 'generate dialog'
4. Click 'view dialog'
5. See error, the dialog remains the same.
6. Click 'restart bot'
7. See error 2, the bot is still saying: enter a number for [property name].  

## Expected behavior

- the generated dialog should have switched from asking for 'number' to asking for 'any string'.

## Screenshots

![Screen Shot 2020-12-15 at 4 24 44 PM](https://user-images.githubusercontent.com/74994573/102288776-0ca3c800-3ef2-11eb-8f6d-8b1f3698e4bf.png)
![Screen Shot 2020-12-15 at 4 24 56 PM](https://user-images.githubusercontent.com/74994573/102288789-13323f80-3ef2-11eb-8c7a-ad249fd44e8a.png)
![Screen Shot 2020-12-15 at 4 25 13 PM](https://user-images.githubusercontent.com/74994573/102288814-1d543e00-3ef2-11eb-91e1-4ee930cac49f.png)

**Comment by xiyangdesign** [comment]
@mewa1024

**Comment by mewa1024** [comment]
@hatpick Do you know what could be going wrong here?

**Comment by hatpick** [comment]
@chrimc62 @coldplaying42 this seems to be a merge issue. can you confirm?

**Comment by hatpick** [comment]
@xiyangdesign there has been a couple of updates to the generate library ever since you reported this, is it still happening?

**Comment by xiyangdesign** [comment]
@hatpick Currently I have issue opening Composer (electron, nightly build; stuck at the loading screen). With the 1.3.1 version, I can open Composer, but failed to generate dialogs (a known issue). So I wasn't able to test this issue (reported here) for now. Would it be ok if I test this again when I'm able to do this?
