### ISSUE TITLE
[MCS-DE] 1.3.0 Opening a Bot freezes Composer

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5356]
When opening an existing Bot or creating a new Bot in v1.3.0 the Bot does not open and the loading never finishes but crashes the app.

@joaollq @goergenj @garypretty @benbrown @cwhitten

**Comment by cwhitten** [comment]
@goergenj  the team will need more information on desktop or web based use and the bot in question causing the issue. Please reach out to me on Teams

**Comment by garypretty** [comment]
@goergenj  is this still an issue?

**Comment by goergenj** [comment]
@garypretty @cwhitten Yes. It is will "all" bots. On Windows Electron App. Please reach out via Teams for follow-up, if needed.

**Comment by cwhitten** [comment]
This has been addressed in 1.3.1 due to a malformed language file received from our translation team.
