### ISSUE TITLE
No UI for imported/preexisting intent

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#5358]
## Is your feature request related to a problem? Please describe.
I'm importing intents from predefined .LU files (e.g. General LU with cancel, help, etc). This works well, and I think will help as we deliver templates and samples that use LU to customers, but there is no UI support in the main window for using these intents.

## Describe the solution you'd like
There are two things that I think would be helpful in the UI for this scenario:

1. When I create a new intent trigger for the dialog, I would like to be able to select from any intents that are already present or imported into the .lu file for the recognizer, rather than always having to type in the existing intent name and skip the utterances input.
![image](https://user-images.githubusercontent.com/27976702/102361056-a6f22300-3f67-11eb-98c7-cb8e59ae0025.png)

2. In the settings for the trigger, I would like to see some indication that it is using an imported intent or a link to the intent. Right now, I see an empty "Trigger Phrases" box and have to open the LU tab manually to find the imported intent. If I could see the utterances there it would help me know its already configured.

![image](https://user-images.githubusercontent.com/27976702/102361319-f9334400-3f67-11eb-990b-cc12a208f5f4.png)

![image](https://user-images.githubusercontent.com/27976702/102361260-e3258380-3f67-11eb-8072-1df7cb53352c.png)

**Comment by mewa1024** [comment]
(Added tag of "Type: Bug" since with the new templates many users will encounter this)

**Comment by mewa1024** [comment]
(@vivekkshankar tagging you as fyi. you might have already considered this case in your trigger redesign explorations.)
