### ISSUE TITLE
Can't use full LU import syntax

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#5359]
## Describe the bug
I'm importing intents and utterances from linked LU files, but I can't use the full syntax as listed here: https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lu-file-format?view=azure-bot-service-4.0#local-file-references. 

I want to be able to use this pattern to pull only the utterances from a linked file by intent: 
```
# Cancel
- [Cancel](./general.en-us.lu#Cancel)
```

But I get the following error: "L0:0 - L0:0 Cannot read property 'segment' of undefinedRefer to the syntax documentation here."

I think it may be related to the link not being a valid file path for the navigation window.

## Version
1.3

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by feich-ms** [comment]
@zhixzhan CLI fix is merged. You can switch to the new nightly build of bf-cli to resolve this issue in composer.

**Comment by zhixzhan** [comment]
Addressed in #5639
