### ISSUE TITLE
Form dialogs: "Newtonsoft.jsonLinq" error appears in Emulator when changing a property

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5360]
## Describe the bug

In a form dialog, when the form is complete, the bot asks the user if there is anything they'd like to change. When I ask to change a specific property, I get an error that says "Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken." and it kicks me out of the dialog.

## Version

1.3.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a form dialog with these properties:
* type: americano, cappuccino, french press, drip, espresso, latte, mocha
* size: small, medium, large, extra large
* milk (optional): none, skim, whole, almond milk, oat milk
* addOn(optional): vanilla syrup, caramel syrup, chocolate syrup, hazelnut syrup, almond syrup, whipped cream
* shots (optional): 1 shot, 2 shots
* special instructions: (any string)

2. Connect to your bot by adding a new trigger that starts the form dialog.
3. Run the bot in Emulator and answer all the prompts, until the summary message.
4. When the bot asks "Is there any property you want to change? (no or the property name)", type "change milk to skim".
5. The error appears, and you have been kicked out of the form dialog back to the main dialog (in this case, an echo bot):

![image](https://user-images.githubusercontent.com/39317542/102421413-383db580-3fb9-11eb-9050-e8acc5da6e94.png)

The same error appears with these phrases:
- "change milk to almond milk"
- "change milk to oat milk"

But it error does ***not*** appear with these phrases:
- "change milk"
- "change type to americano"
- "change shots to 1"
- "change addons to caramel syrup".

Here is the LUIS trace for "change milk to skim" compared to the LUIS trace for "change addons to caramel syrup":
![image](https://user-images.githubusercontent.com/39317542/102422160-00377200-3fbb-11eb-85ab-b0d4f3a51e6d.png)

## Expected behavior

The bot should reply with "Changed milk from none to skim" or "Set milk to skim".

**Comment by mewa1024** [comment]
@chrimc62 Have you seen an error like this?

**Comment by mewa1024** [comment]
[EchoBot-coffee-1216.zip](https://github.com/microsoft/BotFramework-Composer/files/5706311/EchoBot-coffee-1216.zip)

**Comment by mewa1024** [comment]
I'm also getting this error when I add two values for a property that only accepts one, "latte and cappuccino" in this example:
![image](https://user-images.githubusercontent.com/39317542/102424477-0e3bc180-3fc0-11eb-8ab3-17ec8e1efd07.png)

**Comment by zhixzhan** [comment]
@mewa1024 I tried your bot, it is an error when I response "change milk to skim", but if I response "milk" "skim", it would work as expected.
![image](https://user-images.githubusercontent.com/49866537/104280850-83c77e80-54e7-11eb-8012-accc4ecc43fb.png)

> I'm also getting this error when I add two values for a property that only accepts one, "latte and cappuccino" in this example:
I guess for this, the same reason is our response triggered incompatible data type.

**Comment by mewa1024** [comment]
@zhixzhan Thanks for looking into this! Is the "**Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken**" error a common thing that a more frequent user of Composer would understand? I think the biggest problem here is that the dialog ends and the user would have to start all over. It would better if at this point the dialog did not end, but replied that it didn't understand.

**Comment by mewa1024** [comment]
(@xiyangdesign fyi)
