### ISSUE TITLE
[MCS-DE-GO] Unknown Intent in Child Dialogs override by Parent

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5362]
When we are in a child dialog and configure an "Unknown Intent" within the child, whenever the "Unknown Intent" is hit, it calls the Unknown Intent of the parent, if it exists.

**Comment by dmvtech** [comment]
Hi @goergenj By default, dialogs are set to auto end (`"autoEndDialog": false,`). So, if you are getting into your child dialog, depending on how you have that configured, it might be exiting back to the parent. If you will be handling unknown intents at both places, you should set your child dialog to not automatically end. If you can share more details or an example, that might help confirm the behavior. 

Feel free to see my example here:
https://github.com/dmvtech/UnknownInParentAndChild

Use `tc` to trigger the child dialog and `hi` to trigger a message and then end the child dialog.

**Comment by dmvtech** [comment]
Hi @goergenj Any luck here? Did my sample help understand the behavior? Or did _I_ misunderstand your scenario?

**Comment by dmvtech** [comment]
Hi @goergenj I am closing this as I believe this has a correct approach/answer to your issue. If you do not believe this is the case, please comment and we can reopen.
