### ISSUE TITLE
[MCS-DE-GO] Intent based confirmation prompt

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5363]
Confirmation prompt should allow mapping true / false to intents

**Comment by srinaath** [comment]
@goergenj Could you elaborate on this. Essentially, we would just call a dialog based on the response to the confirmation prompt correct?

**Comment by goergenj** [comment]
Hi srinaath, I can show you a Bot design that clarifies this very detailes. Please reach out to me via Teams alias is "jagoerge".

**Comment by goergenj** [comment]
@srinaath See attachment for details. 
[20210312 Best Practice Intent-based User Input-Design in Composer.pdf](https://github.com/microsoft/BotFramework-Composer/files/6130445/20210312.Best.Practice.Intent-based.User.Input-Design.in.Composer.pdf)

**Comment by goergenj** [comment]
Any update on this? We solved this with the Multi-Choice now but still would like to get clarity on how the "Confirmation"-Action can be used properly.
