### ISSUE TITLE
[MCS-DE-GO] Ability to rename the auto-generated LG template names

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5367]
Ability to rename Outputs in LG-files.

Currently the naming of the text output is not customizable but randomly generated and we can’t tell what it does if we don’t explicitly look into the output list.

A change needs to be reflected the related LG-file as well as Actions which use this text output.

Currently setting self-defined names is only possible in the LG-Templates “common.lg”

@joaollq @goergenj @garypretty

**Comment by bgeissler** [comment]
+1
