### ISSUE TITLE
[MCS-DE-GO] Add webchat to bot runtime as client and for testing

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5369]
For customers which cannot use Emulator in combination with ngrok or even in a local setup, we need to have a Web-based testing client.

Ideally the Testing-WebChat should have all capabilities to display the same information as the Emulator during testing.

Further a WebChat should be added as a default client which. 

Design should be customizable via Composer UI to edit css-Files. Select colors for Elements as drop-downs; Add Logo. Enable/Disable Attachment Upload and Speech Input via WebChat (needs to consider Speech Endpoints may be switched during dialog).

Below an example of the Testing-WebChat we have created as a first version for Gothaer:
![image](https://user-images.githubusercontent.com/31212469/102481363-ea30bc80-4061-11eb-92b9-996842668037.png)

@joaollq @goergenj @garypretty

**Comment by srinaath** [comment]
@goergenj This feature is in our backlog for the next semester.

**Comment by garypretty** [comment]
To be clear - we are adding chat based testing (similar to emulator) within the next semester.  This will not include all of the features on this feature request. e.g. having a web chat client in the runtime or the ability to configure web chat.

**Comment by garypretty** [comment]
@clearab assigning to you as a feature request for the runtime.

**Comment by goergenj** [comment]
@garypretty Can you send more details on the chat based testing you are already planning to add? "Next semester" is what timeframe?

**Comment by clearab** [comment]
If I'm understanding the ask correctly, the suggestion is to add a web client to the creation flow for each new bot, then deploy that client automatically whenever a bot is deployed from Composer?

**Comment by goergenj** [comment]
@clearab / @garypretty First priority is to have a testing webchat to use with Composer instead of Emulator for Enterprise scenarios that do not allow the use of Emulator.
Second priority could be to provide an easy to customize (change css, images) WebChat to use as a client channel which can also be deployed automatically from Composer. TBD whether this should be part of the Bot WebAPP or deployed to a separate WebApp to enable different security/authentication sceanrios.

I believe @garypretty there is already a plan for the first priority, correct? We can provide what we have build for Gothaer which we are currently doing a small extension on as well, if you guys are interested.

**Comment by goergenj** [comment]
@clearab I added a note to the other issue you are already working on.

@garypretty @Dewain27 For the WebChat client for deployment, it would be great, if there was a way to add a WebChat client for deployment that can be customized via a simple UI in Composer regarding colors, Avatar-Images and whether you want to allow attachments and to configure optional Speech. For the publish it should ideally provide a way to export the package for manual deployment to a WebApp/Webserver or a Publish to Azure WebApp.
This is not as high a priority as the testing webchat, however would be a good addition to make the whole design / deploy of a Bot even easier by covering the basic webchat client as well.

**Comment by cwhitten** [comment]
@goergenj take a look at a prototype we're working on: https://webchateditor.azurewebsites.net

**Comment by goergenj** [comment]
@cwhitten Thanks. This looks good for the second priority. Is the idea to add this as a page within Composer with a publishing option? Or keep it stand-alone?

@joaollq

**Comment by cwhitten** [comment]
We're a ways off before we can say what this will look like integrated into the product. This is not production ready nor will be supported in any capacity.
