### ISSUE TITLE
[MCS-DE-GO] Ability to sync with LUIS Portal changes

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5372]
For a productive setup it is required that changes to LUIS models that were done outside of the Composer, e.g. by Data Scientists via LUIS Portal or scripts or by automated testing/training/active learning pipelines, can be synced back into composer.

Possible solution could be an automatic pull of the current LUIS model when opening the Bot or a specific Button "Sync LUIS".

@joaollq @goergenj @garypretty

**Comment by garypretty** [comment]
We won't be implementing this feature within the 1st half of 2021, but we plan to revisit this in the 2nd half of the year. Adding to the backlog for review.

**Comment by rodriguesnich** [comment]
Any update for the topic? 
Or if anyway could indicate some materials to handle LUIS active improvements review and LUIS versions, when composer pulls a new version to LUIS, all the HTTPS endpoint utterances reviews stay in the last version

**Comment by goergenj** [comment]
@rodriguesnich As a work around for my customer I wrote a short How-to-Guide on how to handle this. Maybe this will also be helpful for you!?

[[_TOC_]]

# Introduction
To optimize Natual Language Understanding Models, these can be optimized using the LUIS user interface directly. This provides more opportunities to optimize and test the LUIS models independently from the Bot Design process.

Composer currently does not provide an automatic synchronization/import functionality to pull changes what were made inside the LUIS applications directly back to the Bots design.

In order to include the changes into the Bot design you need to manually export them als *.LU-file* and then add them to the *User Input* section of your Bot in Composer.

#Exporting LUIS models
The LUIS applications can be found on the [LUIS Portal](https://www.luis.ai/applications)
![image.png](/.attachments/image-995efeff-14e0-4650-a381-f52c8c157db6.png)

To export the latest version of the LUIS model, you can select **Export** after selecting the LUIS application you want to export:
![image.png](/.attachments/image-ef77d779-4dbd-43dd-993d-f731c559cf09.png)

You can also export a specific version of your LUIS application when you open your LUIS application and go to the *Manage* sheet into the *Versions* section:
![image.png](/.attachments/image-2b9a491f-fd78-424b-8e49-dc9c70302945.png)

In both cases you must select **Export as LU** to get the proper file-format which can be easily added into the Bot design in Composer.

#Copying the *.LU-file* content
After exporting the *.LU-file* will look similar to this:
```
> LUIS application information
> !# @app.name = BaseBotNew(local)-InsuranceIncident.de-de.lu
> !# @app.desc = Model for BaseBotNew app, targetting local
> !# @app.versionId = 0.6
> !# @app.culture = de-de
> !# @app.luis_schema_version = 7.0.0
> !# @app.tokenizerVersion = 1.0.0


> # Intent definitions

# ChoiceInput_Response_6NSdjY
- es geht um einen sachschaden
- es handelt sich um einen personenschaden
- ich hatte einen unfall
- personenschaden
- sachschaden
- unfall


# None


> # Entity definitions


> # PREBUILT Entity definitions


> # Phrase list definitions


> # List entities

@ list IncidentType = 
	- Sachschaden :
		- sach schaden
		- Ding
		- Gegenstand
		- Telefon
	- Personenschaden :
		- personen schaden
		- personen
		- person
		- Hand
	- Unfall :
		- unfall
		- auto
		- fahrzeug
		- pkw
		- lkw
		- autounfall


> # RegEx entities

```

The following part of the exported *.LU-file* should be deleted:
```
> LUIS application information
> !# @app.name = BaseBotNew(local)-InsuranceIncident.de-de.lu
> !# @app.desc = Model for BaseBotNew app, targetting local
> !# @app.versionId = 0.6
> !# @app.culture = de-de
> !# @app.luis_schema_version = 7.0.0
> !# @app.tokenizerVersion = 1.0.0
```

**Select and copy the content you want to add to your Bot design in Composer.**

#Adding the *.LU-file* data to Composer
Inside the Composer go into the *User Input* section of your Bot and select the dialog you want to add the changes into:
![image.png](/.attachments/image-9d5ad227-b3f8-45bf-a565-f6a0f8c282bc.png)

You need to switch to **Show code** to paste the content of the *.LU-file* you exported from LUIS into Composer.

Usually you will replace the full content with the new content from your exported *.LU-file*.
However you can also choose to only add content selectively which is useful when adding new Intents from LU-templates for example.

**If you add completely new Intents you must ensure that you also add *Dialog Triggers* to the dialog you have made the changes for!**
