### ISSUE TITLE
[MCS-DE-GO] Ability to sync with QnAMaker Portal changes

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5373]
For a productive setup it is required that changes to QnA Maker KBs that were done outside of the Composer, e.g. by Data Scientists via QnA Maker Portal or scripts or by automated testing/training/active learning pipelines, can be synced back into composer.

Possible solution could be an automatic pull of the current QnA Maker KBs when opening the Bot or a specific Button "Sync QnA".

@joaollq @goergenj @garypretty

**Comment by garypretty** [comment]
This work is depends on some required changes from the QnA Maker team, which we hope to see in the 1st half of this year.  Ideally we will address this 2nd half of 2021.
