### ISSUE TITLE
unable to add remote skill to a bot getting 500 error

### ISSUE THREAD

**Issue by Samirun** [microsoft/BotFramework-Composer#5376]
## Describe the bug

following the docs 
https://docs.microsoft.com/en-us/composer/how-to-export-a-skill
https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill

we were trying to connect a remote skill (through manifest generated by composer for a simple echo bot)
steps:

1. - we created a echobot consumer bot,  and added a skill bot to it,
2. - for the skill bot we have generated a manifest json file using create/edit manifest in composer.
end point we have given below is the root bot's endpoint.
![image](https://user-images.githubusercontent.com/46156330/102492363-93de7080-4097-11eb-8368-cc4f62d00a85.png)
3. i placed manifest file in localhost server  to be able to  use this as manifest url http://localhost:3000/manifests/skillmanifest.json

4. - connected to the manifest skill by adding it as access external resources/connect to a skill(which is remote skill)
5. followed ngrok part too.
6. we were getting error something like this 
![image](https://user-images.githubusercontent.com/46156330/102493109-b02edd00-4098-11eb-940f-90b2f67815d7.png)

we have tried providing aap id and passwords to both skill and consumer

below is the project settings:
```
{
  "feature": {
    "UseShowTypingMiddleware": false,
    "UseInspectionMiddleware": false,
    "RemoveRecipientMention": false
  },
  "MicrosoftAppPassword": "our password",
  "MicrosoftAppId": "aap id",
  "cosmosDb": {
    "authKey": "",
    "containerId": "botstate-container",
    "cosmosDBEndpoint": "",
    "databaseId": "botstate-db"
  },
  "applicationInsights": {
    "InstrumentationKey": ""
  },
  "blobStorage": {
    "connectionString": "",
    "container": "transcripts"
  },
  "luis": {
    "name": "samirun1",
    "authoringKey": "",
    "authoringEndpoint": "",
    "endpointKey": "",
    "endpoint": "",
    "authoringRegion": "westus",
    "defaultLanguage": "en-us",
    "environment": "composer"
  },
  "luFeatures": {
    "enablePattern": true,
    "enableMLEntities": true,
    "enableListEntities": true,
    "enableCompositeEntities": true,
    "enablePrebuiltEntities": true,
    "enableRegexEntities": true,
    "enablePhraseLists": true
  },
  "publishTargets": [],
  "qna": {
    "subscriptionKey": "",
    "knowledgebaseid": "",
    "endpointKey": "",
    "hostname": "",
    "qnaRegion": "westus"
  },
  "telemetry": {
    "logPersonalInformation": false,
    "logActivities": true
  },
  "runtime": {
    "customRuntime": false,
    "path": "",
    "command": "",
    "key": ""
  },
  "downsampling": {
    "maxImbalanceRatio": -1
  },
  "skillConfiguration": {
    "isSkill": true,
    "allowedCallers": [
      "*"
    ]
  },
  "skill": {
    "saemptybot": {
      "endpointUrl": "http://localhost:3980/api/messages",
      "msAppId": "00c29ae4-6d35-4c94-80a0-b827cc79455a"
    },
    "saemptybot-1": {
      "endpointUrl": "http://localhost:3980/api/messages",
      "msAppId": "00c29ae4-6d35-4c94-80a0-b827cc79455a"
    }
  },
  "defaultLanguage": "en-us",
  "languages": [
    "en-us"
  ],
  "customFunctions": [],
  "importedLibraries": [],
  "skillHostEndpoint": "https://d816d0e39ebd.ngrok.io/api/skills"
}
```

this is our manifest json   :  
```
{
  $schema:
    'https://schemas.botframework.com/schemas/skills/skill-manifest-2.1.preview-1.json',
    $id: 'saemptybot-43be1538-313e-4ed3-8104-e149f7f31d1e',
    endpoints: [
      {
        protocol: 'BotFrameworkV3',
        endpointUrl: 'http://localhost:3980/api/messages',
        msAppId: 'MY AAP ID',
        name: 'manifestpub',
        description: 'i am a manifest skill'
      }
    ],
    name: 'saemptybot',
    version: '1.1',
    publisherName: 'testpub',
    activities: {
      saemptybot: {
        type: 'event',
        name: 'saemptybot'
      },
      conversationUpdate: {
        type: 'conversationUpdate'
    }
  }
}
```

@zxyanliu 

## Version
1.3.0

## Browser

CHROME

## OS

WINDOWS

**Comment by stevkan** [comment]
@Samirun, I'm having some minor issues attempting to repro the error. I hope to have a response on this by EOD.

**Comment by zxyanliu** [comment]
@Samirun FYI. 
We just published the docs with updated details of the [skills topic](https://docs.microsoft.com/en-us/composer/how-to-export-a-skill). 

Could you please show your remote skill manifest? Read [this article](https://docs.microsoft.com/en-us/composer/faq/composer-faq#how-do-i-find-my-remote-skill-manifest-url) and learn how to find your remote skill's manifest URL and how to find your remote skill manifest in JSON?

**Comment by v-kydela** [comment]
@Samirun - Are you still working on this?

**Comment by Samirun** [comment]
@zxyanliu  we moved forward with our work with updated documentation. Thanks for the support. You may close this issue for now.

**Comment by zxyanliu** [comment]
@Samirun Thanks for the update and thanks again for your feedback! I am closing this issue as you requested now.
