### ISSUE TITLE
Bot Emulator shows 403 Quota Exceeded error

### ISSUE THREAD

**Issue by tannguyen3** [microsoft/BotFramework-Composer#5379]
## Describe the bug
Hi, I'm using a bot with LUIS and QnA. The bot is running well after deploying to MS Teams.

But when use in Bot Emulator, it keeps saying "Response status code does not indicate success: 403 (Quota Exceeded).". See picture below

![image](https://user-images.githubusercontent.com/10743872/102518381-d469ca00-4056-11eb-95ca-3578f58183c1.png)

## Version

Bot Composer 1.2

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
Hi @tannguyen3 

- If you click on that error message in the right pane in Emulator, does it give you more info that might be helpful?
- Do you know if it is QnA or LUIS where you are hitting the quota?
- I'm assuming when testing in emulator, you are running the bot locally from Composer as well? 
- What about the case with the success in Teams? Is the bot deployed to Azure and you are using Teams against _that_, or are you using NGROK, and using Teams against the locally running bot in Composer?
- If the bot is deployed to Azure, what about other channels like the built in **Test in Web Chat**?
- Do you have separate prediction and authoring resources for LUIS, or do you use one that is both? One thought is that when running in Composer, you will be using the authoring resource versus a prediction resource when deployed (typically. this really depends on how you have it set up. but that's the default). 
- What pricing tiers are you using for each of these resources?

Can you check the LUIS and QnA resources in Azure portal under metrics to see if you can find more useful info there (I _think_ Blocked Calls metric should show for this issue).

Some more info on limits and tiers:
[Luis resource limits](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-limits#resource-usage-and-limits)
[QnA pricing tier](https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/how-to/set-up-qnamaker-service-azure?tabs=v1#upgrade-qna-maker-sku)

**Comment by tannguyen3** [comment]
Thanks, @dmvtech. I don't know what is the root cause yet. But I'm able to make it work by explicitly adding a prediction resource to the LUIS app I'm using in Bot Emulator and then add the prediction endpoint to my bot configuration.
I didn't need to do it before. 

My bot LUIS configuration before (no endpoint configrution)
```
"name": "dev-luis",
    "authoringKey": "",    
    "authoringRegion": "westus",
    "region": "westus",    
    "defaultLanguage": "en-us",
    "environment": "dev",
    "authoringEndpoint": "https://westus.api.cognitive.microsoft.com/"
```

and now
```
 "name": "dev-luis",
    "authoringKey": "",    
    "authoringRegion": "westus",
    "region": "westus",    
    "defaultLanguage": "en-us",
    "environment": "dev",
    "authoringEndpoint": "https://westus.api.cognitive.microsoft.com/" ,
    "endpointKey": "",
    "endpoint": "https://westus.api.cognitive.microsoft.com/"
```

**Comment by dmvtech** [comment]
Hi @tannguyen3 

 I'm _assuming_ that you might have hit too many authoring transactions per second, but not sure. I'm not able to reproduce this. If you want to try and share a repository of a bot (with sensitive/personal info removed. i.e. keys and such) that reproduces this behavior for you, I'd be happy to try that.

**Comment by dmvtech** [comment]
hi @tannguyen3 Just checking in. Are you able to share your bot so that I can see if I can reproduce? Also; did you check the Azure portal, under _metrics_ to see if you could find any more info?

**Comment by tannguyen3** [comment]
@dmvtech I think we can close the issue. I cannot share the bot.
