### ISSUE TITLE
Add documentation on how to do a complete wipe of Composer app data

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Composer#5380]
## Is your feature request related to a problem? Please describe.

When we add new logic to Composer that deals with handling older implementations of files we store on disk, there is a chance that the data becomes malformed and then throws an exception when trying to be read in a newer version. This can cause a host of errors that could potentially stop Composer from starting.

## Describe the solution you'd like

We should add some form of documentation (can be markdown inside the repository) that explains where Composer stores app data on each platform and how to do a clean wipe of all the data so that a user can try a fresh install of Composer to fix these issues.

## Additional context

Please see the following issue #5073 for an example of a problem that could've been resolved with such documentation.

**Comment by hatpick** [comment]
@tonyanziano how about adding a "factory reset" option to electron menus?

**Comment by tonyanziano** [comment]
@hatpick I think this is a good idea as well. However, we also need docs on how to do this manually, because in the case of #5073 the user wasn't able to start Composer due to malformed files in the app data folder, so they would not be able to reach this "Factory reset" functionality.
