### ISSUE TITLE
Docker Compose file doesn't work

### ISSUE THREAD

**Issue by peterbozso** [microsoft/BotFramework-Composer#5381]
If you clone the repo, go to it's root and issue the command `docker-compose up`, it will fail with the following error:
`Cannot locate specified Dockerfile: Dockerfile`
It's because the `docker-compose.yml` file defines the `composer` service's build context as: `Composer`, which is incorrect, since the Dockerfile is located in the repo's root.

**Comment by srinaath** [comment]
Thanks @peterbozso for the fix. We will review your PR shortly.
