### ISSUE TITLE
Publishing & provisioning Luis from bot template

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5385]
Flow to provision new resources is unclear.

1. As a user when I open a bot template with external services (Luis, Q&A..), I see an error in the navigation. When I click the notification, I am told to fix this in bot settings- 
![Screen Shot 2020-12-17 at 4 17 40 PM](https://user-images.githubusercontent.com/67944302/102558930-78696a80-4083-11eb-8798-aafc911c5e7e.png)

2. When I go to the **bot settings page**, I see error messages on Luis keys but do not  have enough information about what my options are-  
![Screen Shot 2020-12-17 at 4 10 57 PM](https://user-images.githubusercontent.com/67944302/102559000-a8b10900-4083-11eb-9fff-57e8251dd648.png)

**As a user, make it easier for me to go to fetch my keys and/or tell me clearly what to do if I want to create new.**

3. If I choose to create new resources and go through the entire publishing and provisioning wizard flow. I get dropped back to the bot project, while my provisioning has started. At this point, I still have the option for creating new profiles. Is this desirable? When I do so, I get double notifications but do not know if 2 profiles are being created.

![Screen Shot 2020-12-17 at 4 29 29 PM](https://user-images.githubusercontent.com/67944302/102559589-0f82f200-4085-11eb-8ddc-b7fbd7c0fc44.png)

4. After waiting for 15 mins, when finally my resources are provisioned, in the bot settings page, I have to manually add the keys in the input screen.

![Screen Shot 2020-12-17 at 4 32 30 PM](https://user-images.githubusercontent.com/67944302/102559751-79030080-4085-11eb-9ff5-4df5d6628740.png)

## Release: 1.3.0

- [ ] Electron distribution

## OS

- [ ] macOS

## To Reproduce

1. Open a bot with Luis. For eg-_ToDoBotWithLuisSample_
2. Click on 'error notification in the navigation'
3. Click on the "Fix it in bot settings' or go to Bot settings page
4. See error notifications.
5. Then scroll down and click on add new publishing profile in "Publish Target"
6. Go through the flow and see the flow.
## Expected behavior

1. In the Bot Settings > External Services give the user clear messaging on what these services are and how to create new if they do not have these services.
2. In the Error notification, give link to Azure Language Understanding so that it is easier for the user to fetch the keys.
![Screen Shot 2020-12-17 at 4 38 58 PM](https://user-images.githubusercontent.com/67944302/102560144-61784780-4086-11eb-8133-4237f94f9648.png)

3. Once provisioning has triggered, disable features so that user does not create duplicate provisioning profile...
![Screen Shot 2020-12-17 at 4 43 34 PM](https://user-images.githubusercontent.com/67944302/102560395-02ff9900-4087-11eb-80b2-90c2379eeb6f.png)

4.  Auto-fill the keys for me, once I have provided information through the wizard. 
![Screen Shot 2020-12-17 at 4 45 16 PM](https://user-images.githubusercontent.com/67944302/102560510-40fcbd00-4087-11eb-8522-5c99c02a24e5.png)

**Comment by tonyanziano** [comment]
@sangwoohaan any update on this?

**Comment by sangwoohaan** [comment]
I had spoken with Jas – will work on this later. This needs more investigation on user flows.

**Comment by mewa1024** [comment]
@JaskeeratBedi-cmk Closing this since I think the new flow addresses these issues. (Feel free to re-open with a new comment if there is something specific you'd like to track.)
