### ISSUE TITLE
Copy and visual formatting in the provisioning wizard..

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5392]
## Needs copy updates based on approved designs here- https://www.figma.com/file/J3oIdXDmeBQbAe4a4PYbQc/Jaskeerat-Bedi?node-id=2200%3A70869

I think some of the copy did not get updated as per the designs. Also the "Review & create" wizard has content that is getting cut..

## 1.30

- [ ] Electron distribution

## OS

- [ ] macOS

**Comment by luhan2017** [comment]
@JaskeeratBedi-cmk Wenyi is OOF this week, let's sync through Teams at sometime next week to discuss more details.
