### ISSUE TITLE
Declarative UI widgets in Custom Actions

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#5395]
Sometimes one needs to ask the customer for a list of options, eg which products would you like to add. The user would be able to add products / text until they are ready and hit the I'm done button. So this is basically a loop that keeps on running, asking a value, adding value to array and repeat. Repeating the dialog / re-submitting events is in this case to coarse and would make the dialog structure quite bad.

Currently I fix this using a foreach loop with a dummy array as loop value, like the image below.

This is ofocurse a bit of a poormans solution. Having a Do While loop with a condition and as bonus an internal counter for first iteration behavior etc, would be a real clean approach for this. The condition could be falsified by the activity.value of the button (or any other of the million usecases).

![image](https://user-images.githubusercontent.com/49873947/97041905-86fa4080-1570-11eb-96d2-1be584a14a1b.png)

**Comment by EricDahlvang** [comment]
Transferring to Composer repository.  Apparently there's a way to do this with custom actions only?  

This would be a great sample or community contribution.

**Comment by cwhitten** [comment]
@yeze322 putting this on your radar as we look to provide examples/materials/changes to support these scenarios.

**Comment by yeze322** [comment]
@cwhitten thanks for reminding! I went through this scenario and figured out our gap. Here is another similar issue with my temporary solution: https://github.com/microsoft/BotFramework-Composer/issues/4935#issuecomment-747991536

I'm working on several things to simplify the workflow to define custom widget (target to be finished next sprint)
1. Merge Action widget's UI Schema with Form's (to the botbuilder repo).
2. More convenient experience to consume flow editor built-in widgets

After that, I'll provide examples somewhere.

**Comment by yeze322** [comment]
Stage 1 - port uischema to sdk repo WIP:
https://github.com/microsoft/botframework-sdk/pull/6163
https://github.com/microsoft/botbuilder-dotnet/pull/5099

**Comment by yeze322** [comment]
Only one remaining work to do to close this issue - make Flow Editor layouter compatible with customized Action

**Comment by yeze322** [comment]
addressed in #5999

**Comment by EricDahlvang** [comment]
Hi @cxbuilders 

An example of a Custom Action DoWhile can be found in this draft PR: https://github.com/microsoft/BotBuilder-Samples/pull/3114
