### ISSUE TITLE
Composer nearly unusably slow for editing dialogs after updating to 1.3.0 

### ISSUE THREAD

**Issue by ttur** [microsoft/BotFramework-Composer#5396]
## Describe the bug

After updating the composer from 1.1.1 to 1.3.0 editing a complicated bot is so slow that actions (such as editing a sendresponse) take 5-10 seconds, and occasionally fail. 

Simpler dialogs can be edited okay, more complicated ones not at all. 

We have been building an advisory bot since composer early betas. Our bot has 30+ dialogs. Simple dialogs have a few activities. Complex dialogs have a few hundred. We support three languages. 

Most recently we were using version 1.1.1 and that worked quite well for this. 

## Version

Release: 1.3.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [X] Windows
- [ ] Ubuntu

## Screenshots

Here is an example of the edit operation failing (editing Finnish version of the dialog that hasn't yet been properly translated from English): 

![image](https://user-images.githubusercontent.com/996293/102791359-93075080-43af-11eb-8843-740fbe0d2f77.png)

## Additional context

The process is taking just under 1G of memory on my laptop. I would be happy to give it more, if that helps, if I knew how.

It does not seem to matter whether the local bot is running or not. Editing is very slow and occasionally fails regardless.

**Comment by ttur** [comment]
Some testing results:

- Release 1.2.1 is a bit faster than 1.3.0, but still way slower than 1.1.1 (tested on Windows and MacOS, same bot)
- Removing our extra languages (Finnish and Swedish) – leaving only English – does not make 1.3.0 much faster; maybe a little

**Comment by gabog** [comment]
Thank you @ttur, we will address this issue in an upcoming release.

**Comment by cwhitten** [comment]
This will be addressed in an upcoming patch (1.3.1)
