### ISSUE TITLE
Feature Request: Timeout Trigger

### ISSUE THREAD

**Issue by hrazmsft** [microsoft/BotFramework-Composer#5397]
## Is your feature request related to a problem? Please describe.

I have some troubles to end dialog after period of time of inactivity.
Say I have a bot that supports several complex dialogs with multiple intents. When the user starts one dialog and leave the chat open for a while and come back, he is still on the dialog instead of moving to the main state.

## Describe the solution you'd like

I want to have a timeout trigger that can trigger after X times of inactivity. This can be useful for asking the user "Are you still there?" or just end the dialog and return to the main flow.

## Describe alternatives you've considered

I tried to add a custom C# code for that. But since it is Composer and it seems to be common thing it feels overkill. Since all the other logic is in Composer.

## Additional context

No

**Comment by EricDahlvang** [comment]
@garypretty  can you help with prioritizing this feature request?

**Comment by tonyanziano** [comment]
@garypretty can you comment on this?

**Comment by garypretty** [comment]
@hraz-msft just to clarify, are you specifically looking to check the last time seen when the user sends another message, as opposed to having some form of background job checking for you?  If so then you can do this today by adding the Activity received trigger and setting a condition on the trigger to only fire if a certain amount of time has elapsed.  If it has and the trigger fires then you could use the End All Dialogs action to reset the user.

**Comment by hraz-msft** [comment]
No, what I meant is, like the intent trigger, "unrecognized intent" and all other triggers. It will be useful if Composer add a "Stale Trigger" or "Timeout Trigger, that will be called after a certain amount of time (the timeout can be configured in the trigger props).

I know it is possible, but I honestly think that adding custom adding manual Activity is overkill and Composer can easily add this useful feature.

A useful usecase is to use the "Stale Trigger"/"Timeout Trigger" to send a response to the user, like "Are you still there?" or "The conversation has ended." with end all dialogs.
________________________________

**Comment by garypretty** [comment]
@hraz-msft Thank you for the clarification.  At this time we have no plans to implement this feature in the way you describe.  The requirements for such a feature are made more complicated by the need for a job in the background and potentially for persistent storage of conversation references and last seen timestamps.  This can likely be further complicated by running multiple instances of the bot in a load balanced environment.  The recommendation today if you need this is to implement the job yourself, likely using middleware / background job and emitting a custom event which you can add a trigger for.

@EricDahlvang one thought - did you have documentation pointing to implementing this for code first bots?  If so, maybe we could extend that documentation to cover the Composer scenario?

**Comment by EricDahlvang** [comment]
This doc demonstrates using an Azure Queues service: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance an earlier example version of this (not identical to the doc anymore) can be found here: https://github.com/EricDahlvang/LongOperationsBot

Also, here is a Cosmosdb example using an Azure Timer Function: https://github.com/EricDahlvang/TimeoutConversation

These are in my personal GitHub repository, and not official Microsoft samples, but they might help provide some alternative approaches for how to store and use a ConversationReference to proactively restart a conversation without using a local dictionary.

@garypretty  What we do not currently have, is a declarative or Composer sample demonstrating this type of proactive scenario.  A sample would most likely involve Microsoft.Bot.Builder.Azure.Queues and preferably this PR would also be merged, and utilized: https://github.com/microsoft/botbuilder-dotnet/pull/4974

**Comment by Jenny0932** [comment]
> @hraz-msft just to clarify, are you specifically looking to check the last time seen when the user sends another message, as opposed to having some form of background job checking for you? If so then you can do this today by adding the Activity received trigger and setting a condition on the trigger to only fire if a certain amount of time has elapsed. If it has and the trigger fires then you could use the End All Dialogs action to reset the user.

**Comment by Jenny0932** [comment]
> @hraz-msft just to clarify, are you specifically looking to check the last time seen when the user sends another message, as opposed to having some form of background job checking for you? If so then you can do this today by adding the Activity received trigger and setting a condition on the trigger to only fire if a certain amount of time has elapsed. If it has and the trigger fires then you could use the End All Dialogs action to reset the user.

Hi Gary,
I had the similar issue and followed your suggestion here.l, adding conditions on the trigger itself. How to define the time has elapsed? I am using the desktop bot composer and set properties in some points of my dialog. I’d the dateTimeDiff() is larger than a value and the. Cancel all dialog. But the activities never been triggered. Could you help me on how to setup the conditions for trigger about timeout?

**Comment by EricDahlvang** [comment]
Hi @Jenny0932 

The DialogManager.ExpireAfter property can be to clear conversation state if the user's previous reply was greater than a certain time period:
  
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs#L173

**Comment by neetgupta7** [comment]
@EricDahlvang - do you have any samples for how to do this in composer? We have tried to use middleware but this works only when user sends a message after the expiry time. We want the message to go out after expiry time irrespective of any user input. We tried to put some timer but they run into null ref errors because of missing turn context.
