### ISSUE TITLE
Nightly Build e678bd7 - cannot choose Profiles to Publish to

### ISSUE THREAD

**Issue by DS2019** [microsoft/BotFramework-Composer#5398]
Hi @tonyanziano 

I've installed the latest nightly build and got further than I have before with trying to Publish to PVA from the Bot Framework Composer. However, it is not allowing me to choose a profile to publish to. 
I had a publish profile of "Publish Bot to Azure" and added one to "Publish to PVA" - this time it found all 4 bots in my test tenant environment. However, when I go to the screen "Publish your bots" I cannot actually choose "Publish to PVA" as so:
![CannotPublishtoPVAProfile](https://user-images.githubusercontent.com/44073678/102807909-641fb900-4374-11eb-9a35-966237184538.jpg)
When I click the "Publish to PVA" profile, it defaults to the "Publish to Azure" Profile so I can't actually publish it. 
Thanks!

**Comment by tonyanziano** [comment]
Hi @DS2019 ,

I've transferred this issue to the official Composer repository as we do not track issues on the nightly repository.

Sorry to hear you are still having trouble publishing. This sounds like a UI bug so we will take a look and update the ticket.

@luhan2017 any ideas off the top of your head? Or maybe Wenyi has thoughts on this? (I don't know wenyi's github username)

**Comment by tonyanziano** [comment]
If you press "Ctrl + Shift + I" to open the Developer Tools and try selecting the PVA publish profile again, do you see any errors in the console?

**Comment by DS2019** [comment]
I don't think so. I choose "Publish to PVA" and it defaults right back to the Azure Profile:
![BacktoAzure](https://user-images.githubusercontent.com/44073678/102809784-751df980-4377-11eb-81e7-9b6c45d7eb5d.jpg)

**Comment by DS2019** [comment]
Oops, I missed this:
![NotValid](https://user-images.githubusercontent.com/44073678/102810840-47d24b00-4379-11eb-9aab-6c2756605110.jpg)

**Comment by tonyanziano** [comment]
Awesome, this is very helpful. Let me take a look at the code. I might have an idea of what's going on.

**Comment by tonyanziano** [comment]
Found the issue. There was a recent PR #4924 that changed the publish extension history API and broke the PVA extension's ability to gather publish history. This causes it to error out which prevents you from selecting it as a publishing target.

I will have a fix out for this today.

**Comment by DS2019** [comment]
Hi @tonyanziano - I've tried a few of the nightly versions, the latest being: da63bc9 and I still have the UI bug for Publishing to PVA:
![FailPublish](https://user-images.githubusercontent.com/44073678/103372151-1d257800-4a86-11eb-8b41-c76036a1d6b8.jpg)

**Comment by tonyanziano** [comment]
Hey @DS2019 ,

Thanks for the reminder! This is totally my bad. My PR got approved yesterday for the fix and still hasn't made it into the nightly builds. I will merge it in the next hour and I'll kick off a nightly build for you.

**Comment by DS2019** [comment]
@tonyanziano - sweet! Appreciate it!

**Comment by tonyanziano** [comment]
Go ahead and try the following release: https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.0-nightly.198726.32a4899

@DS2019
