### ISSUE TITLE
Bot fails to start after adding a new action, 'Telemetry - Track Event'

### ISSUE THREAD

**Issue by anusharavindrar** [microsoft/BotFramework-Composer#5400]
## Describe the bug
When I add a new action, 'Telemetry - Track Event' to my bot and try starting the bot, it fails with the following error:
![image](https://user-images.githubusercontent.com/48731427/102833049-e58f3f80-43a4-11eb-8221-d8bf4b9e0840.png)

## Version

![image](https://user-images.githubusercontent.com/48731427/102833075-fc359680-43a4-11eb-90fe-b071f6901819.png)

## To Reproduce

1. Create an Echo bot using the template on Composer.
2. Go to Greeting and click on '+', select Debugging options --> emit a telemetry track event
3. Fill in the Event name, Key and value.
4. Start the bot.
5. See error.
![image](https://user-images.githubusercontent.com/48731427/102833370-c1802e00-43a5-11eb-80fe-7b0f258bdd6b.png)

## Expected behavior

the bot should start up and the status should be "running"

**Comment by luhan2017** [comment]
@anusharavindrar this is a known issue in the sdk side, which I had a fix already merged, but it is not included in 4.11, so we didn't take it in composer yet. You can simply mitigate this issue by 

Click show code on the upper right corner of you dialog, and 
Update this 
 "$kind": "Microsoft.TelemetryTrackEvent", 
To 
 "$kind": "Microsoft.TelemetryTrackEventAction"
