### ISSUE TITLE
Integrating/Mounting composer web component in a different project

### ISSUE THREAD

**Issue by kranthicodes** [microsoft/BotFramework-Composer#5405]
### Problem

I was wondering if there is a way for us to use composer(react web app) as a component in a different react project. 

We started by exporting the App with RecoilRoot as we just needed the component which can be mounted.

<img src="https://user-images.githubusercontent.com/57343520/102878459-4b93c980-446e-11eb-848b-d84ce266c408.png" width="500" />
 
After this we just built the react app and moved the generated files to main react project. 

Now we wanted to import main chunk from js files into our project and render the component. Upon trying that project took forever to compile and after long wait it crashed with heap out of memory error.

<img src="https://user-images.githubusercontent.com/57343520/102879452-c4dfec00-446f-11eb-94b3-cd391f301a9b.png" width="600" />

Another idea that we were considering was to use composer on a different html page(running my project on index.html and composer on composer.html) and use iframe to show it on a specific route or assess it as it is on a different page. 

If someone has to achieve what has been described above, what could be the possibilities or ideas to do this? 

@cwhitten  /anyone could you please point us in the right direction to solve this problem?

**Comment by EricDahlvang** [comment]
@cwhitten or @garypretty  would you please chime in here?  Is this something we support?

**Comment by cwhitten** [comment]
Hi @kranthicodes. We have no prioritized the scenario to natively embed the Composer client app into an existing client app.

I'd recommend hosting the apps independently and consuming the Composer application over an iframe. This will allow the applications to operate independently of each other on the page. 

We have no plans to invest in supporting this scenario at the moment.

**Comment by garypretty** [comment]
Closing this as per Chris' comments above.
