### ISSUE TITLE
Bot Framework Composer is slow since 1.3.0 update

### ISSUE THREAD

**Issue by djsbur** [microsoft/BotFramework-Composer#5411]
## Describe the bug
I'm creating a bot structure.  When I go through the process of adding a dialog, this takes about a minute beginning to end.  i.e. Click add dialog, wait for window to show, enter name, click ok and wait for dialog to be added.  This did not happen prior to update.  I'm on a high spec Surface Pro 7.  

## Version
This was an auto-update.  Details in Help>About are 
Version 1.3.0
Electron 8.2.4
Chrome 80.03987.165
NodeJS 12.13.0
V8 8.0.426.27-electron-0

## Browser
Latest Edge.  However using actual standalone Bot Framework Composer desktop application.  

## OS

Windows 10

## To Reproduce

1. Open my bot
2. Click on bot root and choose "Add a dialog"
3. Enter dialog title name and click "OK"
4. Wait for dialog to be created and shown in menu
Total time ~60 sec

## Expected behavior

I expect this process to execute much quick as before the auto update

**Comment by hibrenda** [comment]
This might be the same issue #5396 @lei9444 for awareness

**Comment by djsbur** [comment]
Thank you for following up on this.

Yes, it does look like a similar issue.

I’m also building a bot for my company that we wish to release on the Microsoft Teams app store in January and this update issue has stopped any further development as the Composer is basically unusable.


Thanks,


[cid:image003.png@01D6DDE8.76BE9140]<https://moderncollab.co.uk>
Dan Burling
Modern Collaboration and Digital Adoption Specialist

Get in touch
+44 7950 90 80 85
linkedin.com/in/danburling

**Comment by cwhitten** [comment]
@djsbur while the team works through this issue, can you please use a previous version to unblock your development?

**Comment by djsbur** [comment]
Hi @cwhitten 

I have reinstalled v1.2.0.  However I have also had to revert to an older backup of the bot that was not amended using v1.3.0 as the bot file makes v1.2.0 hang.  I've lost a lot of work, but at least there's a speedy way forward now.  

Looking forward to see what the analysis turns out :) 

FYI I do love the Bot Framework Composer (as a non-dev).  Great work to all of your team!

**Comment by cwhitten** [comment]
We’ve been looking into this for a few days now. I expect us to have an update on 1.3 that will allow you to re-update soon.

I’m glad you’re finding value in the product!

**Comment by gabog** [comment]
this one is duplicated, closing it so we can track it in #5396
