### ISSUE TITLE
Desktop Composer's publish function isn't able to recognize my azure login email address 

### ISSUE THREAD

**Issue by MIkey007007** [microsoft/BotFramework-Composer#5418]
## Describe the bug

I am using the publish function of the desktop composer to publish my bot to the Azure web service.
After I invoke the "publish the selected profile", the composer simply keeps prompting me for azure login in the account. 
Regardless I repeated input my valid azure login email address,  composer will keep repeating the following error message:

    " we could not find a work or school account with the email address"

After I resetting my azure login email address, nothing change and the error persists. 
The desktop composer version number: V1.3.0

The same login email address works perfectly for the composer built from the source code. (although the composer cease to work today as a result of some kind of code conflict

After 

## Version

V1.3.0

## Browser

Microsoft edge, Chrome

- [ ] Electron distribution
- [X ] Chrome
- [ ] Safari
- [X ] Firefox
- [X ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## Expected behavior

Composer should recognize my azure login email, as it has been working without any trouble on the azure portal

**Comment by ivatilca** [comment]
Same problem over here.... I dont have option to sign in with personal account.

**Comment by ivatilca** [comment]
Related bug https://github.com/microsoft/BotFramework-Composer/issues/5393

**Comment by MIkey007007** [comment]
Let's hope we can get some attention here.  What is the point to use the composer if it wouldn't let you publish ??

**Comment by joshgummersall** [comment]
It looks like the team is actively working to resolve this issue, though updates are happening primarily on https://github.com/microsoft/BotFramework-Composer/issues/5393.

**Comment by MIkey007007** [comment]
Agree.
