### ISSUE TITLE
.lu file format gets confused by @-sign in email addresses?

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5419]
## Describe the bug

In .lu files, entity labels around email addresses are discarded.

## Version

1.3.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

I ran into this when using form dialogs and had a property of type **email**, but this would probably happen with any utterance that had an entity label around an email. 

1. Edit user responses to have an email address and label the email address. You will see that the color coding for entities is not applied.

![image](https://user-images.githubusercontent.com/39317542/103322851-cae84680-49f4-11eb-87ff-3265c39ad2e3.png)

If you remove the "@" sign, the entity label color coding is applied:
![image](https://user-images.githubusercontent.com/39317542/103322876-f79c5e00-49f4-11eb-862a-3481fd4996d9.png)

2. Start your bot to publish to LUIS.
3. Go to the LUIS portal and look for the labeled utterances. This screenshot has the same utterances as the screenshot in Composer. None of the entity labels that contained the email were applied:

![image](https://user-images.githubusercontent.com/39317542/103322945-46e28e80-49f5-11eb-96ab-8dd533f1ae1a.png)

## Expected behavior

I'd expect to be able to label email addresses or see a validation error instead of the label to be ignored.

**Comment by tonyanziano** [comment]
@cosmicshuai can you please take a look at this?

**Comment by cosmicshuai** [comment]
@tonyanziano  Sure. I will look into this issue. Looks like I should update the regex pattern for entities.
