### ISSUE TITLE
Two buttons not diplaying in herocard

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#5422]
Hi,

I used below template but two buttons not displaying only one button visible could you please suggest some solution.

[HeroCard
    title = Big Buck Bunny
    subtitle = by the Blender Institute
    text = Big Buck Bunny (code-named Peach) is a short computer-animated comedy film by the Blender Institute
    buttons = ${cardActionTemplate('openUrl', 'Study more', 'https://docs.microsoft.com/en-us/composer/how-to-send-cards#videocard')}
    buttons = ${cardActionTemplate('openUrl', 'media', 'https://docs.microsoft.com/en-us/composer/how-to-send-cards#videocard')}
]

![image](https://user-images.githubusercontent.com/70739031/103351026-dce6e980-4ac7-11eb-809b-9ef95259d447.png)

Thanks.....

**Comment by joshgummersall** [comment]
You need to create an [array](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0#arrays-and-objects). Try this:

```
[HeroCard
  title = Big Buck Bunny
  subtitle = by the Blender Institute
  text = Big Buck Bunny (code-named Peach) is a short computer-animated comedy film by the Blender Institute
  buttons = ${[ cardActionTemplate('openUrl', 'Study more', 'https://docs.microsoft.com/en-us/composer/how-to-send-cards#videocard'), cardActionTemplate('openUrl', 'media', 'https://docs.microsoft.com/en-us/composer/how-to-send-cards#videocard') ]}
][
```

This renders:

![Screen Shot 2020-12-30 at 10 03 19 AM](https://user-images.githubusercontent.com/1235378/103372217-447c4500-4a86-11eb-8e3b-68516673ccbe.png)

**Comment by BeheraMadan** [comment]
Thanks its working......
