### ISSUE TITLE
Dialog name display wrong in Right side panel

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#5427]
## Describe the bug

Dialog name display wrong in Right side panel

**No idea is a bug or purposely display as “Adaptive dialog”**

## Version

1.3.0

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Create a new bot project and select the parent dialog 
Ex : parent dialog "WeatherBot"  right side panel display name as "Adaptive dialog"

## Expected behavior

Ex : parent dialog "WeatherBot"  right side panel display name as "WeatherBot"

## Screenshots

![image](https://user-images.githubusercontent.com/16264167/103420578-40404c80-4b98-11eb-8605-6db93351207b.png)

**Comment by tonyanziano** [comment]
Thanks for pointing this out. We plan to fix this in the upcoming release.

**Comment by mewa1024** [comment]
Is this related to bug #5383?

**Comment by alanlong9278** [comment]
> Is this related to bug #5383?

Yes, this error is involved in #5383

**Comment by yeze322** [comment]
duplicated, close this one and track the problem in #5383.
