### ISSUE TITLE
Cosmos vs Storage -> State vs Transcripts

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#5430]
I am trying to understand what the reason is for storing the state in Cosmos and the transcripts in Storage? Why not have both in Storage? The reason I am asking is that Cosmos just takes a long time to create in the Pipeline and it would also just simplify things. Additionally the cost of Cosmos also is quite high if usage is low (for dev and acc).

**Comment by luhan2017** [comment]
@cxbuilders Thanks for the feedback, we will support this in the next release.

**Comment by cwhitten** [comment]
@luhan2017 if I understand correctly, this is a runtime feature request, which should funnel into the adaptive runtime project. Do you agree?

**Comment by luhan2017** [comment]
@cwhitten, Yes, per the discussion in our last standup, all the runtime related new features should funnel into the adaptive runtime project.

**Comment by srinaath** [comment]
@tracyboehrer Is this request considered in the latest runtime to be integrated in Composer?

**Comment by tracyboehrer** [comment]
We will now.  Will copy or transfer this issue to the new Runtime issue list.

**Comment by tracyboehrer** [comment]
Runtime issue: https://github.com/microsoft/botframework-core/issues/73

**Comment by compulim** [comment]
@cwhitten @luhan2017 Since we copied/transferred the issue to `botframework-core`, should we close this one or keep this one open as tracking?

**Comment by cwhitten** [comment]
Closing as a dupe - follow https://github.com/microsoft/botframework-core/issues/73 for updates on this issue.
