### ISSUE TITLE
Azure Resources Recommendations

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#5431]
I have been searching a lot for the recommended settings for Azure Resources for Bot Framework Bots (namely the WebApp).
For example the WebApp that gets created by Composer has the S1 SKU but not the always on flag, which I find surprising. Is this intentional or just never looked at?

It would be great to have a list of recommended settings for the resources.

Now I am just setting whichever I think is good, but well, I am sure there are expert people that know exactly which settings play best with Composer Bots...

**Comment by luhan2017** [comment]
@cxbuilders Thanks for your feedback, we just used the default value and didn't set any configuration values in the provision process, we will consult experts to have a good recommendations on this in the next release.

**Comment by cwhitten** [comment]
Pulling out of R12 as it doesn't seem like we have clear requirements or guidance on this yet.

**Comment by Virtual-Josh** [comment]
Hey @cwhitten,

If you're going to take this can you update the tags to reflect that? If not can you close it?

**Comment by compulim** [comment]
When planning for R13, please update this ticket.

**Comment by cwhitten** [comment]
@Dewain27 adding you to follow up or provide guidance here as part of the provisioning work stream.

**Comment by carlosscastro** [comment]
Thanks @cxbuilders. @GeoffCoxMSFT In addition to the documentation point, I think AlwaysOn should be evaluated as a setting to be enabled by default or exposed in the configuration.

**Comment by cxbuilders** [comment]
@carlosscastro In our pipelines we use this automatically based on the SKU, would not know why with anything besides F1 you would not want to turn it on.
$alwaysOn = $webappSku -ne 'F1'

**Comment by Dewain27** [comment]
@cxbuilders I am putting this into our backlog to get engineering to determine if we can address this by making the change.
