### ISSUE TITLE
CPU usage getting increased to 100% and bot is getting stopped

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#5434]
When we are continuously chatting with bot which have composer dialogs and hosted in Azure webappbot the CPU usage of App service getting increased to 100% with in short period of  time and bot is stopped to respond.

**Comment by luhan2017** [comment]
@KoradaRajesh Could you share your bot? Or at least check if there is loop in your bot? for example: dialogA calls dialogB and dialogB calls dialogA.

**Comment by KoradaRajesh** [comment]
There is no such looping dialogs. I can't share bot files here Please provide your Mail id

**Comment by luhan2017** [comment]
@KoradaRajesh luhan@microsoft.com

**Comment by KoradaRajesh** [comment]
@luhan2017  I'm reading composer files on every bot hit this causing high memory usage and bot getting stopped to respond

**Comment by gabog** [comment]
Taken offline.
