### ISSUE TITLE
Cannot build composer from source

### ISSUE THREAD

**Issue by Khanh-Ngy** [microsoft/BotFramework-Composer#5435]
I tried this : https://docs.microsoft.com/en-us/composer/install-composer#build-composer-from-source

But got problems when run **yarn**  at terminal in ...\BotFramework-Composer\Composer
![image](https://user-images.githubusercontent.com/71876037/103506824-3ff1cb00-4e90-11eb-8ec8-bb0563d940ef.png)
It didn't run anymore...

Then , I tried other way with running **yarn install** && **yarn build**
![image](https://user-images.githubusercontent.com/71876037/103507063-d625f100-4e90-11eb-931b-d5393466f497.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by tdurnford** [comment]
@Khanh-Ngy What version of Node and what operating system are you using? I ran into a similar issue when I was using Node v15. Reverting to Node v14 resolved the issue.

**Comment by taicchoumsft** [comment]
Hi @Khanh-Ngy , reinforcing what @tdurnford said, right now we only support compiling and running on LTS versions of Node (v10, v12, v14 are [ok](https://github.com/microsoft/BotFramework-Composer/blob/main/docs/1.3-supported-os.md)).  Can you revert to an LTS version and try compiling again?

**Comment by zxyanliu** [comment]
@taicchoumsft thanks for the clarification.

From the docs side, I am going to: 
- update the wording of the Node.js versions and specify the following: LTS versions of Node (v10, v12, v14).
- add [a supported OS](https://github.com/microsoft/BotFramework-Composer/blob/main/docs/1.3-supported-os.md) link in the prerequisite section for building Composer from source.

**Comment by Khanh-Ngy** [comment]
> @Khanh-Ngy What version of Node and what operating system are you using? I ran into a similar issue when I was using Node v15. Reverting to Node v14 resolved the issue.

So many tks bro !! 
I changed node version 15 to 14 && it worked fine <3
