### ISSUE TITLE
I got a problem "  Sorry, something went wrong with publishing. Try again or exit out of this task. "

### ISSUE THREAD

**Issue by Khanh-Ngy** [microsoft/BotFramework-Composer#5439]
I tried this tutorial : https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis

I got a problem related to the **company network**.

When I used **public network**, it worked fine.

How can I config the proxy for Bot Framework Composer ?

![image](https://user-images.githubusercontent.com/71876037/103616179-844b9c80-4f5e-11eb-949d-24253bb385e0.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by tonyanziano** [comment]
Hello @Khanh-Ngy ,

I believe this is the same issue as https://github.com/microsoft/BotFramework-Composer/issues/4091.

Please try following the steps in that issue to see if it resolves your problem. Try setting the proxy environment variables listed.
