### ISSUE TITLE
New bot created with 1.3 fails to build - BadImageFormatException (Orchestrator not found)

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#5447]
## Describe the bug

A colleague in Cloud Advocacy is experiencing an issue that I think could likely affect multiple users.

Upgraded to 1.3 via automatic upgrade prompt.  Created a new bot (no ejected runtime) and made a simple change to the welcome message LG.  

Tried to run the bot from Composer and got the below error.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/3900649/103640347-be5d7400-4f47-11eb-8b52-b19654850f7e.png)

## Version

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/3900649/103640368-c4535500-4f47-11eb-917c-95ec40af1d4c.png)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by boydc2014** [comment]
Looks like a typical binary loading issue, are you operating in x64 or x86?

**Comment by garypretty** [comment]
Closing as this looks like a weird environment issue on their machine, given that dotnet --version is showing the x86 version installed but not the more up to date x64 version.  I am going to close the issue and I have asked them to uninstall / re-install their SDKs / runtimes and we will see if it persists.
