### ISSUE TITLE
Issue warning to user if provisioning is ended abruptly

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5449]
- As a user, if I close or exit user, show me a warning informing me that my provisioning flow will get cancelled.
- Give me option to either resume provisioning or continue to exit from Composer

**Comment by tonyanziano** [comment]
@JaskeeratBedi-cmk do you mean exiting the Composer application?

**Comment by JaskeeratBedi-cmk** [comment]
@tonyanziano created this issue after discussing with @luhan2017 & @Wenyi Luo. The idea is to have a modal pop-up whenever user tries to exit Composer, if the provisioning is in progress.

Will have to think about the right interaction if Composer is being used in browser, application...
