### ISSUE TITLE
Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by MoesLab** [microsoft/BotFramework-Composer#5453]
## After creating a Weather sample chatbot and going through creating resources in Azure I copied the Authoring key and prediction key from Azure and filled them onto LUIS authoring key and LUIS endpoint key in Bot framework Composer Project Settings,  and restart the bot and test in the emulator. the welcome message shows up but when I type Hi and press enter I will get a message like
Response status code does not indicate success: 403 (Forbidden). or some other form of 4xx error

## Version
V1.3.0 GUI

## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
Windows 7

- [ ] macOS
- [ x
<img width="1049" alt="weatherbot error" src="https://user-images.githubusercontent.com/5963372/103709280-321b7300-4f80-11eb-99d5-c957bfaef39e.PNG">
] Windows
- [ ] Ubuntu

## To Reproduce

4. See an error

**Comment by MoesLab** [comment]
<img width="929" alt="LUIS keys" src="https://user-images.githubusercontent.com/5963372/103709536-bf5ec780-4f80-11eb-9a52-5d2c671ef4f2.PNG">

can anybody tell me where I should get LUIS authoring key and LUIS endpoint key in the context of the pic?

**Comment by anusharavindrar** [comment]
@MoesLab, you can follow the steps from step 7 onwards in [this](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis#add-language-understanding-data-and-conditions) documentation which specifies how to add the authoring key and location. The endpoint key is optional.

**Comment by MoesLab** [comment]
Thanks, I regenerated 1st key and update the Composer. and wow starts working.

**Comment by benbrown** [comment]
Glad to hear it was resolved, @MoesLab. Let us know if you need further assistance.

**Comment by SupriyaBhogi** [comment]
After creating a sample bot in composer and  I copied the Authoring key and prediction key from Azure and filled them onto LUIS authoring key and LUIS endpoint key in Bot framework Composer Project Settings, and restart the bot and test in the emulator. the welcome message shows up but when I type Hi and press enter I will get a message like
Response status code does not indicate success: 403 (Forbidden)
can any help me with this?
