### ISSUE TITLE
Cannot open bot, "Could not connect to storage"

### ISSUE THREAD

**Issue by arturl** [microsoft/BotFramework-Composer#5454]
## Describe the bug

"Open" button to open existing bots is broken

## Version
1.3

## Browser

- [x ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

Install Composer
Click Open button

## Actual behavior

Error: "Could not connect to storage"

## Expected behavior

Must prompt for botfile directory/file

## Screenshots

![image](https://user-images.githubusercontent.com/1875734/103716685-828ed280-4f78-11eb-81bd-051d78c94a40.png)

**Comment by arturl** [comment]
More info: restarting the Composer app or even reinstalling it did not help

**Comment by arturl** [comment]
Found a similar issue: https://github.com/microsoft/BotFramework-Composer/issues/3552

Developer tools has these errors (if it helps):

Error fetching focussed storage folder: TypeError: Cannot read property 'reduce' of undefined
s @ shared.ts:28
moment.js:270 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Tue Jan 05 2021 16:57:16 GMT-0800 (Pacific Standard Time), _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://localhost:5000/static/js/11.701c08f7.chunk.js:2:171122)
    at http://localhost:5000/static/js/11.701c08f7.chunk.js:2:191417
    at http://localhost:5000/static/js/11.701c08f7.chunk.js:2:191468
    at At (http://localhost:5000/static/js/11.701c08f7.chunk.js:2:191780)
    at http://localhost:5000/static/js/11.701c08f7.chunk.js:2:192054
    at St (http://localhost:5000/static/js/11.701c08f7.chunk.js:2:192116)
    at Et (http://localhost:5000/static/js/11.701c08f7.chunk.js:2:192148)
    at r (http://localhost:5000/static/js/11.701c08f7.chunk.js:2:168041)
    at O (http://localhost:5000/static/js/main.b65e86ec.chunk.js:1:280715)
    at onRender (http://localhost:5000/static/js/15.dae53a9c.chunk.js:1:35907)

**Comment by cwhitten** [comment]
@arturl is it possible you installed Composer for only your user instead of for all users on your machine, or it was installed to a directory with limited file system access?

**Comment by arturl** [comment]
> installed Composer for only your user

@cwhitten, yes, since that's the default option. Will try to reinstall for all and report back

**Comment by arturl** [comment]
Nope, installing to "C:\Program Files\Bot Framework Composer" did not help

**Comment by cwhitten** [comment]
Hmm. Could your machine possibly be in a similar issue as this comment? https://github.com/microsoft/BotFramework-Composer/issues/3552#issuecomment-660569235

**Comment by arturl** [comment]
My machine has no white spaces in paths that are relevant to Composer.

**Comment by arturl** [comment]
Found a solution: in ` %userprofile%\AppData\Roaming\BotFrameworkComposer\data.json`, inspect the `storageConnections` section. Both `path` and `defaultPath` must point to an exiting folder. 
In my case, `path` pointed to a full pathname of a botproj file (maybe a bug in an older composer version). Deleting that line solved the problem.
Hopefully this will help the next person who runs into this problem.
@cwhitten, this can be fixed by making the bot folder selection logic in Composer\packages\server\src\services\storage.ts more robust.
Feel free to close this issue now.
