### ISSUE TITLE
Can't publish with a subscription from another Azure directory

### ISSUE THREAD

**Issue by pedro-ramirez-suarez** [microsoft/BotFramework-Composer#5459]
Hi,

My azure account it's managed by my company, one of our clients assigned a subscription for me on their directory, I am able to switch directories and create resources on both directories inside the Azure portal, but on Composer, I can only create resources on my default directory because I can only see and select the subscription from my default Azure directory.
Since I can't publish from Composer, is there any documentation on how to manually create the resources needed on the Azure portal and then select the existing resources on Composer?

**Comment by dmvtech** [comment]
Hi @pedro-ramirez-suarez There is no documentation or exact steps on how to do this for Composer bots specifically. But yes; you can provision the Azure resources outside of Composer. You can create the resources through the Azure portal (one of the easiest ways is to just create a `Web App Bot`), or they can be created from [command line](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#3-create-the-application-registration) scripts using `az` cli or PowerShell. This doesn't include LUIS resources or other things. Be aware of the provisioning templates and what they do. 

With your scenario, I'm not sure if you would be able to import and the publish after from Composer provisioning in this manner, but it might be worth a try. If not, you can publish in the other methods (az cli, etc) but you will need to [export the runtime](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action#export-runtime) and provision that as well (might be worth creating+publishing+comparing a basic echo bot on your tenant to see how the file hierarchy is configured).

The older way of provisioning/deploying is still available, using the `scripts\provisionComposer.js` script. In using this, you have more flexibility and should be able to specify which subscriptions, credentials, etc. to use and you should be able to use the subscription to your client's (assuming you have appropriate permissions).

**Comment by pedro-ramirez-suarez** [comment]
Thanks, I tried using the scripts but I was getting the following error:
```
{
  "code": "InvalidAuthenticationTokenTenant",
  "message": "The access token is from the wrong issuer 'https://sts.windows.net/52ac55fa-3887-4c09-98c8-49fd995cafc3/'. It must match the tenant 'https://sts.windows.net/31e14793-1820-4e78-bb77-295ff38db016/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/31e14793-1820-4e78-bb77-295ff38db016' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."
}
** Provision failed **
```

**Comment by luhan2017** [comment]
@pedro-ramirez-suarez there should be a tenant parameter in the script which is optional, could you please to try to set it explicitly? 
```
['tenantId', 'ID of your tenant if required (will choose first in list by default)'],
```

**Comment by pedro-ramirez-suarez** [comment]
Thanks @luhan2017, I tried that before and it didn't work. In the end the client created a domain account for me.

**Comment by dmvtech** [comment]
Thanks for the update @pedro-ramirez-suarez. I will go ahead and close this. Let us know if you have further issues.

**Comment by lafe** [comment]
@dmvtech In my opinion, this issue should not have been closed, as this is - at least - a feature request for the Bot Framework Composer itself. I have the same issue right now and I imagine that is a frequent issue for consultants that are member of multiple Azure tenants.

**Comment by luhan2017** [comment]
Reopen this issue and we will work on this in the next release.

**Comment by luhan2017** [comment]
@zidaneymar please help investigate if we can do this through azure API, after we understand this, we may need @JaskeeratBedi-cmk 's help on the design.

**Comment by Dewain27** [comment]
I have tagged this as a feature request and will put into planning discussions and determine when we can address this issue.

**Comment by luhan2017** [comment]
The switch tenant feature is already supported in our latest nightly bits by this PR #6542.

**Comment by CharingJC** [comment]
Dear Team:

After using the latest nightly release, we still come up with the following issue
https://github.com/microsoft/BotFramework-Composer-Nightlies/issues/2
