### ISSUE TITLE
Add tooling to QnA blade in Composer to support Follow-up prompt authoring

### ISSUE THREAD

**Issue by managedcoder** [microsoft/BotFramework-Composer#5460]
## Feature Request
Currently, the tooling on the QnA blade in Composer only supports the authoring of alternate phrases but not the ability to author follow-up prompts.

## Describe the solution you'd like
The [.qna file format](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-qna-file-format?view=azure-bot-service-4.0) does currently support follow-up expressions and I've hand-jammed them into my local .qna file in my Composer project folder as a test and they do render correctly in the emulator so the only thing missing is the tooling in Composer that would allow me to enter the follow-up prompt particulars for a given qna pair and then persist those values in the correct format in the local .qna profile file.  As I said, I've manually inject follow-up prompts and tested it and everything would work from that point on if there were tooling that allowed me enter a follow-up prompt and persist it in the local .qna file.

Follow-up prompts could be tooled and launched in the same way alternate phrases are currently where a link becomes visible as I fly over qna entries 

-Russ

**Comment by hibrenda** [comment]
@vivekkshankar @cwhitten be aware of this
