### ISSUE TITLE
Adding C#/JS custom action issue - reloading bot project to get the action added

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#5464]
## Describe the bug

The reloading issue happened in both C# and JS custom action implementation.

After I ejected and customized the C#/JavaScript custom action, 
* I was **unable** to see the custom action added by reopening the bot project from the Composer **Home** page. 
* I was **able** to see the custom action added by opening another bot project and then reopening the one with the custom action. 

## Version

v1.3

## Browser

- Electron distribution

## OS

- Windows

## To Reproduce

[C# implementation](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action)
[JavaScript implementation](https://github.com/microsoft/BotFramework-Composer/blob/main/runtime/node/schemas/readme.md#adding-custom-actions-to-your-composer-bot-for-nodejs)

## Expected behavior

Should have an easier way to reload the bot project after customizing the runtime.

## Additional context

Related to this doc work item: https://github.com/MicrosoftDocs/composer-docs/issues/59

**Comment by yeze322** [comment]
I tried the C# flow, it's not working as well.

To keep schema files updated, the `/open` api should be fired when user manually reopen the project. However, according to current behaviour, only the first time you open a bot project will the `/open` api be fired. As a result, it broke the experience of using custom runtime in Electron.
![image](https://user-images.githubusercontent.com/8528761/103859329-d8888500-50f4-11eb-860f-6f0a35018b07.png)

**Comment by srinaath** [comment]
@yeze322  investigating it now

**Comment by yeze322** [comment]
@srinaath Tried on my side, it's loaded

**Comment by srinaath** [comment]
@yeze322  I'll revert that piece of code for now. 

It seems a bit of work to keep tracking the last updated state for a project in composer client side. Then we can use fs stat to get lastUpdatedTimestamp for the project folder(changes made outside composer) and then see if the two timestamps are different. As a result, lets just reload it again. Let me know if u see a better solution.

**Comment by zxyanliu** [comment]
>@zxyanliu just to make sure if you open a different project and then open this project containing the custom action does the action load?

@srinaath Yes. The bot project will get reloaded after I open a different project and then open this project containing the custom action.

**Comment by zxyanliu** [comment]
>I tried the C# flow, it's not working as well.

@yeze322 

Yes, the reloading issue also happens when adding a C# custom action.

**Comment by yeze322** [comment]
@srinaath If it's possible to trace the last modified date of a project folder, we can leverage standard http features to optimize our flow. Generally, we can maintain `If-Modified-Since` on client side and `Last-Modified` on server side to avoid uncecessary content transfer.

One concern is the efficiency of getting lastUpdatedTimestamp for the project folder, it needs to check the whole project recursively. If it's time costly, we can only include those content folders Composer cares about (Dialogs, LU/LG, Schemas) meanwhile exclude those non-content folders (runtime, scripts).

**Comment by zxyanliu** [comment]
FYI. I just tested with Composer v1.3.1 release candidate.
The reloading issue was resolved for C#. 
The reloading issue persists for JS.
