### ISSUE TITLE
Trying to Add new publish profile in Composer asking for Microsoft login e-mail and it does not accept it, Why?

### ISSUE THREAD

**Issue by MoesLab** [microsoft/BotFramework-Composer#5465]
## Describe the bug
Trying to Add a new publish profile in Composer asking for Microsoft login e-mail and it does not accept it, Why?

## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ x] Windows 7 professional
<img width="489" alt="Azure Bot login" src="https://user-images.githubusercontent.com/5963372/103868789-5f0e7980-5097-11eb-9865-de535b18eb43.PNG">
<img width="675" alt="Publish email error" src="https://user-images.githubusercontent.com/5963372/103868816-6cc3ff00-5097-11eb-9c11-922a1a153ad0.PNG">

- [ ] Ubuntu

**Comment by dmvtech** [comment]
Are you using a personal Microsoft account or a Work/School one? 

See here: #5456

**Comment by benbrown** [comment]
See also: #5393

**Comment by dmvtech** [comment]
Closing as this is a known issue and being tracked in above linked issues.
