### ISSUE TITLE
Problem publishing

### ISSUE THREAD

**Issue by kalebk** [microsoft/BotFramework-Composer#5467]
## Describe the bug

Unable to publish bot to azure using bot composer. It spins indefinitely with no status update and no error in the application... There is only an error in the console.. HTTP status code 431 Request Header Fields Too Large.

I tried using newer nightly build.. but I am also unable to uninstall bot composer.. When I launch the uninstaller it comes with NSIS error

## Version

Bot composer V 1.3

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Publish menu within Bot Framework Composer
2. Click on Publish Bot
3. Bot is never published
4. Error is in the console in developer tools

## Expected behavior

Expected the bot to be published as an azure web app

## Screenshots

![image](https://user-images.githubusercontent.com/27185349/103926947-3f02a880-50df-11eb-9864-4b1f8293a2d3.png)

![image](https://user-images.githubusercontent.com/27185349/103927187-90ab3300-50df-11eb-914a-3cf90adcc727.png)

**Comment by ryan-daly-AgFCS** [comment]
Watching this. New to Bots and the Composer application. I'm receiving same problem, and now looking for a way to downgrade if possible. After many attempts for trying to figure out what I did wrong, I'm seeing this 431 err too.

![image](https://user-images.githubusercontent.com/55713746/104061704-b5c2a300-51be-11eb-8248-82ad3b68332e.png)

**Comment by ryan-daly-AgFCS** [comment]
Managed to downgrade to 1.2.1 and can successfully publish to Azure. Unfortunate as I really like the features and organization of 1.3 (plus documentation is updated for it too).

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/5335 got fixed. @ryan-daly-AgFCS you can try out latest nightly.

**Comment by ryan-daly-AgFCS** [comment]
Thanks @hibrenda - I gave that a try, but I'm still receiving the 431 error, then subsequent 404. Composer doesn't update to indicate it is accepted for publishing like 1.2.1 does.

![image](https://user-images.githubusercontent.com/55713746/104197373-8a240080-53ea-11eb-8be1-59c43fe8be94.png)

**Comment by ryan-daly-AgFCS** [comment]
Here is the results when I uninstalled the nightly, then reinstalled 1.2.1 on the same bot files:

![image](https://user-images.githubusercontent.com/55713746/104198267-a4aaa980-53eb-11eb-840f-504adce641aa.png)

**Comment by GeoffCoxMSFT** [comment]
@hibrenda @luhan2017 Could you follow up please?

**Comment by zxyanliu** [comment]
We have a similar issue here. FYI.
https://github.com/MicrosoftDocs/composer-docs/issues/73#issuecomment-758924520

**Comment by kalebk** [comment]
Yes I also tried installing latest nightly and still received the same 431 and 404 errors..

**Comment by VanyLaw** [comment]
It seems like the accessToken is too large to set in the http header, @kalebk could you give us your arm token(even an expired one is ok) for testing, so that we can see how large it would be?

**Comment by VanyLaw** [comment]
And there is another issue. frontend should show error when accept 431 or 404 instead of loading, @alanlong9278 could you help to take a look?

**Comment by kalebk** [comment]
I don't have access to get it quickly right now, but I see in a previous message that I sent my teammate that it's 9,538 characters. I can try to provide tomorrow if needed

**Comment by alanlong9278** [comment]
Sure, I will cover 202, 200, 404, 431, 500 http status in frontend in #5375

**Comment by tiagonmas** [comment]
You closed the issue but I still see the error on the nightly build [df53a98](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.1-nightly.204049.df53a98)
![image](https://user-images.githubusercontent.com/42462/105159305-d831b600-5b06-11eb-8fee-cfa9cd80408e.png)

**Comment by tiagonmas** [comment]
Still getting HTTP 431 when publishing
![image](https://user-images.githubusercontent.com/42462/105161510-5e4efc00-5b09-11eb-9702-362e013d8e2a.png)

**Comment by luhan2017** [comment]
@tiagonmas we just found the change on this PR will not take effect in electron app. could you try to set this environment variable before start the nightly composer build, and try again?
```
NODE_OPTIONS="--max-http-header-size=16000"
```

**Comment by tiagonmas** [comment]
@luhan2017 it worked with that setting! :)

**Comment by ryan-daly-AgFCS** [comment]
Just want to note for the record that this issue is resolved on my end with version 1.3.1 that was just published a few days ago.
