### ISSUE TITLE
Bot Composer deployed to Azure always get "Object reference not set to an instance of an object." when asking for any input (text, files, etc...))

### ISSUE THREAD

**Issue by lopejum** [microsoft/BotFramework-Composer#5477]
I have Bot Composer web version:

<img width="322" alt="imagen" src="https://user-images.githubusercontent.com/28530984/104060560-5fbe2180-51f7-11eb-8ce5-219741299b4d.png">

And:

<img width="575" alt="imagen" src="https://user-images.githubusercontent.com/28530984/104060618-72d0f180-51f7-11eb-8429-75e6bf732f70.png">

I have a very simple bot dialog, where I ask for a picture and then, I send the result of the image process:

<img width="1087" alt="imagen" src="https://user-images.githubusercontent.com/28530984/104060957-fe4a8280-51f7-11eb-8a7f-dc1c9d9bb1ae.png">
<img width="1087" alt="imagen" src="https://user-images.githubusercontent.com/28530984/104061039-20440500-51f8-11eb-8de5-91e5f3955e98.png">

It works with no problems into the Bot Emulator on local machine. When I deploy the bot to Azure, to a Web App:

<img width="1062" alt="imagen" src="https://user-images.githubusercontent.com/28530984/104062298-7e71e780-51fa-11eb-9eee-96438c2a2ceb.png">

However, when I try to start the dialog into Azure Test in Web Chat, ALWAYS I get the same error:

<img width="857" alt="imagen" src="https://user-images.githubusercontent.com/28530984/104062689-34d5cc80-51fb-11eb-9f12-863fc0c7bc2b.png">

What is happening here?? How can I fix this problem?

Thanks in advance!!

Best regards

**Comment by zidaneymar** [comment]
@lopejum, Hi, I think you could download the web server to local and debug it locally to see the call stack of the runtime when this exception (Object reference not set to an instance of an object) is thrown.
You could download the whole wwwroot folder through kudu portal and run Microsoft.BotFramework.Composer.WebApp.exe locally to view the log details.
![image](https://user-images.githubusercontent.com/9328933/104144831-db8aba80-53ff-11eb-8fc4-1e704f0fc219.png)
![image](https://user-images.githubusercontent.com/9328933/104144874-fe1cd380-53ff-11eb-849e-c1127efcf4a8.png)

**Comment by luhan2017** [comment]
@lopejum , could you try to put your logic under anther trigger, for example OnDialogStarted trigger and test if you still see the error? This probably because of  the OnConvesationUpdate trigger issue for webchat. 

![image](https://user-images.githubusercontent.com/32191031/104157225-b14bf380-5425-11eb-861a-8b8c4397fa9c.png)

**Comment by lopejum** [comment]
Dear @luhan2017, I followed your suggestions. Everything is working now and I can publish my bot from Composer to Azure and get the dialogue with WebChat, Teams, Telegram...

Thanks a lot
