### ISSUE TITLE
I could't publish bot when I configured koreacentral luis resource with westus luis authoring

### ISSUE THREAD

**Issue by keunoklim** [microsoft/BotFramework-Composer#5480]
## Describe the bug

When I configued publish profile as luis authoring is westus and luis prediction is koreacentral, I got error during publishing
## Version

bot framecomposer v1.2.1
## Browser

- [v ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [v] Windows
- [ ] Ubuntu

## To Reproduce
1. I've created azure resouce as the below command. I didn't make luis authoring becasue I selected resource region as koreacentral
node provisionComposer.js --subscriptionId=xxxxxxx --name=AICC-TEST --appPassword=xxxxxxxx --location=koreacentral --createLuisAuthoringResource=false --createCosmosDb=false --createStorage=false
2. I've copied output from console to make publish profile in composer.
3. I've created bot using "QnA maker and LUIS" template.
4. I've created publish profile and copied output from 2step
5. I've created luis authoring in resource which I created 1step with azure portal
6. I've modifed authoringkey and authoringendpoint value with luis authoring which I've created in 5 step.
7. I pulished and I've got the below error
{
  "status": "DEPLOY_INFO",
  "message": "lubuild succeed"
}
{
  "status": "DEPLOY_INFO",
  "message": "start publish luis"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"name\":\"StatusCodeError\",\"statusCode\":401,\"message\":\"401 - \\\"{ \\\\\\\"statusCode\\\\\\\": 401, \\\\\\\"message\\\\\\\": \\\\\\\"Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.\\\\\\\" }\\\"\",\"error\":\"{ \\\"statusCode\\\": 401, \\\"message\\\": \\\"Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.\\\" }\",\"options\":{},\"response\":{\"statusCode\":401},\"stack\":\"StatusCodeError: 401 - \\\"{ \\\\\\\"statusCode\\\\\\\": 401, \\\\\\\"message\\\\\\\": \\\\\\\"Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.\\\\\\\" }\\\"\\n    at new r (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3724051)\\n    at q.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3726040)\\n    at q.e.callback.t.callback [as _callback] (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3725088)\\n    at q.t._callback.t.callback.t.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3755134)\\n    at q.emit (events.js:210:5)\\n    at q.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3767714)\\n    at q.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\index.js:2:3766546)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
}
401 - "{ \"statusCode\": 401, \"message\": \"Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.\" }"

## Expected behavior

I could publish bot 
## Additional context
If I made "endpointKey" and  "endpoint" as empty, then publish succeed.
But when I tested bot in bot channel registration, error happened as the below picture due there was no information about endpointkey and endpoint.
![image](https://user-images.githubusercontent.com/27936106/104123193-f96b0780-538c-11eb-931d-65441043129d.png)

**Comment by hibrenda** [comment]
@keunoklim can you provide the **publish profile** luis setting ? which item you have value and which is empty. especially how you input the endpoint & authoring endpoint. what value for "region" ?
    "luis": {
      "endpointKey": "",
      "authoringKey": "",
      "region": "westus",
      "endpoint": "",
      "authoringEndpoint": ""
    },

**Comment by keunoklim** [comment]
Hi hibrenda
The below are my publish profile luis setting which I got error.
    "luis": {
      "authoringKey": "32c53caa0e854a01831f8bd35cexabfxxx",
      "authoringEndpoint": "https://aicc-homenshopping-dev-luis-author.cognitiveservices.azure.com/",
      "endpointKey": "153a9543e896469a9cbdb26588d7c9exxxx",
      "endpoint": "https://koreacentral.api.cognitive.microsoft.com/",
      "region": "westus"
    },

But after I made empty endpointKey and endpoint as the below , I could publish . But it is useless becauce of the above reason.
    "luis": {
      "authoringKey": "32c53caa0e854a01831f8bd35cexabfxxx",
      "authoringEndpoint": "https://aicc-homenshopping-dev-luis-author.cognitiveservices.azure.com/",
      "endpointKey": "",
      "endpoint": "",
      "region": "westus"
    },

For region , I tried "westus" region and "koreacenral" region. But publish error happened.

**Comment by keunoklim** [comment]
I modified The authoringkey and endpointKey for secuitry. These are examples

**Comment by hibrenda** [comment]
The second setting does not work for our publish process. could you double check for how you input "luisResource": "<luis-resource-name>" in publish profile. you need to provide the luis resource name . eg. "composer-xxx-dev"

**Comment by keunoklim** [comment]
I inputed name whose I created for luis. For example, If I created Composer-xxx-dev-luis, then I inputed the same name in "luisResource"

**Comment by zidaneymar** [comment]
Hi @keunoklim , are these two resources (luis authoring resource and luis prediction resource) under the same subscription?

**Comment by keunoklim** [comment]
Yes. these are under subscription. you can really easy reproduce this issue just westus region author and other region luis predcition except westus. For experiment, I triey japan region for luis prediction. I also reproduced this issue.

**Comment by zidaneymar** [comment]
@hibrenda , this is an issue of authoring endpoint and endpoint, currently the code is not correct.
