### ISSUE TITLE
Form dialogs scheme property and "bot asks" doesn't match

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#5494]
## Describe the bug

In schema: the property "size" is a LIST type: [small, medium, large, extra large]
In emulator, when the bot asks for a value for size, it's prompting with: Please choose a value for size from [large, extra large] to add

## Version

![Screen Shot 2021-01-11 at 4 53 45 PM](https://user-images.githubusercontent.com/74994573/104255290-94b3b980-542d-11eb-9765-d4ff23f1e094.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [X] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## Additional context
https://user-images.githubusercontent.com/74994573/104255373-c3ca2b00-542d-11eb-9e05-aba37afd2312.mov

**Comment by GeoffCoxMSFT** [comment]
This is fixed in the latest SDK and bf-generate library (as of 01/13).  It will ship as part of 1.4 (R12)
