### ISSUE TITLE
[MCS-DE] Electron App freezes when opening a bot

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5496]
Whenever I try to open a Bot with the Composer Electron App v1.3.0 on Windows (BotFramework-Composer-1.3.0-windows-setup.exe) the application freezes.

Switching to any areas in the left navigation incl. "Home" is not possible.

This happens with an existing Bot as well as when creating a new empty bot.

Switching the Composer Application language to English (US), opening the bit and then switchint the Composer langague back to German solves this issue. But it needs to be done before opening a bot every time.

@cwhitten @benbrown

**Comment by tonyanziano** [comment]
I am able to reproduce this using the following steps:

1. Open Composer
2. Switch language to Deutsch
3. Close Composer
4. Open Composer
5. Try to open a bot

Composer then freezes.

I opened the dev tools console during all this and was able to capture the following error output:

```
react-dom.production.min.js:5058 v {name: "SyntaxError", message: "Expected placeholder id but found ' in > Fügen Sie…ty=Seattle'}↵↵> Entitätsdefinitionen:↵> @ ml city", expected: "placeholder id", found: "'", offset: 147, …}
es @ react-dom.production.min.js:5058
o.componentDidCatch.n.callback @ react-dom.production.min.js:5590
fo @ react-dom.production.min.js:3108
os @ react-dom.production.min.js:5166
hc @ react-dom.production.min.js:6408
t.unstable_runWithPriority @ scheduler.production.min.js:309
Wi @ react-dom.production.min.js:2816
dc @ react-dom.production.min.js:6204
$s @ react-dom.production.min.js:5895
(anonymous) @ react-dom.production.min.js:2851
t.unstable_runWithPriority @ scheduler.production.min.js:309
Wi @ react-dom.production.min.js:2816
Gi @ react-dom.production.min.js:2846
Xi @ react-dom.production.min.js:2836
z @ react-dom.production.min.js:7280
j @ react-dom.production.min.js:200
Jt @ react-dom.production.min.js:1378
Zt @ react-dom.production.min.js:1341
t.unstable_runWithPriority @ scheduler.production.min.js:309
Qt @ react-dom.production.min.js:1336
react-dom.production.min.js:5058 v {name: "SyntaxError", message: "Expected placeholder id but found ' in > Fügen Sie…ty=Seattle'}↵↵> Entitätsdefinitionen:↵> @ ml city", expected: "placeholder id", found: "'", offset: 147, …}
es @ react-dom.production.min.js:5058
```

It looks like there is some sort of localization error with `format-message` and the German translations.

@beyackle could you take a look at this? We had a similar issue right before releasing 1.3.0 and we disabled language switching as a workaround.

**Comment by beyackle** [comment]
Oh, this again. I remeber what that was (improper quoting in strings). It's even the same example as before.

**Comment by zhixzhan** [comment]
I can still re-produce it
![preview](https://user-images.githubusercontent.com/49866537/109936993-75d4f380-7d09-11eb-84e1-5bf14215a80e.gif)

**Comment by beyackle** [comment]
I'm looking into this now.
