### ISSUE TITLE
Full knowledgebase creation support in Composer

### ISSUE THREAD

**Issue by managedcoder** [microsoft/BotFramework-Composer#5497]
## Is your feature request related to a problem? Please describe.

Currently, developers are required to create the actual Azure QnA Maker Cognitive Service before they use the **QnA Maker Sample** template or the **QnA Maker and LUIS** template.  It would be better if Composer created the service automatically and then also properly configured the bot (see #4873)

## Describe the solution you'd like

The integration of LUIS and QnA Maker both require developers to perform required configure which is totally fair.  The solution I would like to see is for the service creation to be part of that "configuration" process since the proximity of side effects (i.e. the creation of the service) makes the most sense to happen at that point.  I know it takes forever for the service to be provisioned and it can take another 10 minutes or so for the QnA Maker endpoints to be accessible even after successful creation of the QnA Maker resource so if all that activity were part of the config process it would make the most sense and you could provide some UX that informs the developer that the bot won't run correctly until the service is created and endpoints become available.  Perhaps show a warning that explains this that goes away once the service is ready to go.

Currently, I have to create the QnA Maker service (I usually do this in the portal) and then I go to QnA Maker portal and attempt to create a new KB just so I can use Step 2 in the creation steps in the QnA Maker portal to check if the endpoints are accessible (Step 2 tells you when the endpoints are not ready and tells you to check back in 10 minutes).  When I get the green light from the QnA Maker portal then I go back to the Azure portal and get the subscription key and then I am ready to create a QnA Maker Sample template bot.  Even armed with the subscription key, its not enough to get the bot fully working since you have to deal with issue #4873 and I made a comment on that issue that explains what else is required.

## Describe alternatives you've considered

The alternative "workaround" is a very painful double "chicken and egg" scenario where I have to first create the service so I can get the subscription key ("chicken and egg" number 1).  Then I can use Composer to create the bot and "half configure" it since I then have the second "chicken and egg" situation where I have to have the Composer first create the KB so I can then go to the QnA Maker portal to get the remaining config (that config is only available after the KB has been created).  Finally, I have to know enough to switch to the Advanced View to be able to set the proper config and its only at that point I am ready to run the bot successfully.

**Comment by GeoffCoxMSFT** [comment]
@hibrenda - Can you take a look at this in relation to the other provisioning work planned?

**Comment by hibrenda** [comment]
Yes. would like to hear more feedback and supported in later release.
