### ISSUE TITLE
Invoke skills from a skill. 

### ISSUE THREAD

**Issue by pedro-ramirez-suarez** [microsoft/BotFramework-Composer#5499]
## Is your feature request related to a problem? Please describe.

I am building a bot for a big enterprise, the bot will consume multiple APIs and services, the bot is being split into different skills not only to have a clean implementation with a clear separation of responsibilities but also to be able to split the work more easily and to be able to reuse as much code as possible. There are a few things that are repeated across the main bot and the skills, like confirmation messages where the bot asks if some information is correct or incorrect or data input validation, my plan was to create small skills for each functionality that was repeated across the main bot and the main skills but it's not possible to invoke a skill inside a skill. This is frustrating because you can't develop truly reusable components, it's also frustrating because most of those dialogs use Luis to interpret the user's input and it's hard to maintain the same functionality everywhere when multiple team members maintain and develop the code.

## Describe the solution you'd like
I would like to be able to invoke skills within skills, this way I can treat skills as components that can be reused everywhere and not having to implement the same solution in the main bot and each one of the skills.

## Describe alternatives you've considered
The only alternative that we found was to repeat the dialogs. 

## Additional context
What I am asking it's only needed when you are building complex bots with a lot of user interaction and interaction with internal and external services.

**Comment by srinaath** [comment]
@pedro-ramirez-suarez 

[https://github.com/microsoft/BotFramework-Composer/tree/main/extensions/packageManager#readme](https://github.com/microsoft/BotFramework-Composer/tree/main/extensions/packageManager#readme)

We have this new functionality in Preview. Essentially, you can wrap all of your common code (dialog,triggers) and push it to a package. The package can be imported into your bots

**Comment by pedro-ramirez-suarez** [comment]
Hi @srinaath 
That solves our problem! any idea on when this will move out of preview?

**Comment by srinaath** [comment]
![](https://user-images.githubusercontent.com/13004779/104768860-2ddf1a80-5723-11eb-9b98-d041d5145a87.png)

We have a quite a few preview features you can enable and use. We dont have a set date yet on when we would GA all of them. But, you can start adopting these features in your app early if you wish.

@benbrown
