### ISSUE TITLE
Confusing texts in the app's UI - not helpful enough

### ISSUE THREAD

**Issue by nightmareCoder123** [microsoft/BotFramework-Composer#5503]
## Describe the bug

I started to use Composer a while ago and I love this app because it makes building a bot so fast and easy. 
However, I found a lot of texts in the UI confusing and not very helpful. The following is just one example:

<img width="372" alt="tooltip" src="https://user-images.githubusercontent.com/76134026/104369104-ce3e0080-54d1-11eb-85d2-1786ffc10cc2.png">

1. I understand what Unknown intent is. This is the doc link: https://docs.microsoft.com/en-us/composer/concept-events-and-triggers#intent-triggers
   However, what is "Unknown intent recognized" under "Unknown intent"? What does that mean and why it's there?

2. "Action to perform when user input is unrecognized or if non of the 'on intent recognition' triggers match recognized intent."
   This sentence is not very helpful and what is this "on intent recognition"? 

3. Condition (expression)/ 4. Priority / 5. Run Once
   Seriously, what do those properties mean and what are they used for? I cannot tell from the explanation. Do you have documentation links to these properties? 

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Start Composer
2. Create an Echobot from the template
3. See the Unknown intent trigger

## Expected behavior

Should contain standard, comprehensible, and contextual content in the UI to truly help users better understand this app and use it. This is very important for user experience and customer retention.

**Comment by a-b-r-o-w-n** [comment]
@sangwoohaan can you work with @garypretty to understand this request and make suggestions on improvement?

**Comment by sangwoohaan** [comment]
I've done some design explorations on this already. It's on hold currently but I'd be happy to continue making progress.

**Comment by garypretty** [comment]
@sangwoohaan let's discuss this when I am back from leave in our next sync. I would like to understand your current explorations and see how they play with the fact that the text being shown is defined in the SDK today.

Thanks @nightmareCoder123.
