### ISSUE TITLE
Update Activity on a message ( Adaptive dialog )

### ISSUE THREAD

**Issue by Khanh-Ngy** [microsoft/BotFramework-Composer#5508]
## Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/71876037/104425526-5fd16f00-55b3-11eb-81b0-0c23d526f463.png)

All I need is : 
When I click button ONE  >>  the content will show : user 1 - user 5
When I click button TWO  >>  call API again  >>   the content will update && show : user 6  - user 10

**Comment by anusharavindrar** [comment]
@Khanh-Ngy, can you elaborate more on what you are trying to do? Maybe the steps to repro and what channel are you on?

**Comment by Khanh-Ngy** [comment]
> @Khanh-Ngy, can you elaborate more on what you are trying to do? Can you specify the steps to repro and what channel are you on?

## My design : 
![image](https://user-images.githubusercontent.com/71876037/104671554-9ffa3400-5710-11eb-99d8-424262d1d086.png)

## My code for button " ONE " && " TWO: 

![image](https://user-images.githubusercontent.com/71876037/104671973-742b7e00-5711-11eb-80d6-ebd14c91a8c5.png)

## What I need : 

API pagination && update the message ( don't create new message )

For example : 
Click button "ONE" -> request API http://example.org/api/user?page=1 -> Message content shows user 1, user 2
Click button "TWO" -> request API http://example.org/api/user?page=2 -> Message content shows user 2, user 3

These things happen on a message, don't create a new message. 
It means the content of message updated when clicking its buttons.

## I also researched the document but maybe nothing worked
AdaptiveCard don't support my event I want

-   https://adaptivecards.io/explorer/
-   ![image](https://user-images.githubusercontent.com/71876037/104672771-ff594380-5712-11eb-9b55-362d28e1edef.png)

Bot Framework Composer document 

- https://docs.microsoft.com/en-us/composer/concept-memory#update-activity
- ![image](https://user-images.githubusercontent.com/71876037/104673037-85758a00-5713-11eb-8698-b821db413afb.png)

**Comment by anusharavindrar** [comment]
@Khanh-Ngy, the Update activity action is not currently supported in Web Chat or Emulator. If you want the update activity to work, then I would suggest you file for a feature request in the [SDK](https://github.com/microsoft/botframework-sdk/issues) or the [services](https://github.com/microsoft/botframework-services/issues) repo and the team will take a look.
