### ISSUE TITLE
Facing issue while showing hero card for second time using existing object in composer

### ISSUE THREAD

**Issue by ashokdevlabs** [microsoft/BotFramework-Composer#5511]
1.	We are designing the flow using bot composer
2.	As per the requirement we need to show product with images so we are using Hero card(Carousal).
3.	For the first time the card gets displayed properly.
4.	2nd when we are showing the card for adding more items that time it wont display anything.

1st time when we call the cards - 

![image](https://user-images.githubusercontent.com/71652470/104474465-0a618600-55e4-11eb-8ec8-23891ec5d013.png)

2nd time it look like this -

![image](https://user-images.githubusercontent.com/71652470/104474536-1e0cec80-55e4-11eb-9c20-d4f91185b9e3.png)

**Comment by dmvtech** [comment]
I'm checking to see if I can reproduce.

**Comment by ashokdevlabs** [comment]
we figured it out.
when we use the same dialog without clearing the user state variables at that time this issue occurs.
I tried deleting all the user state variables then it worked 2nd time as well.
