### ISSUE TITLE
Support LG template navigation

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#5522]
As a user, when I hover to the template name, I can use “go to definition” to navigate to the corresponding template 
- for in line view in sendactivity, if the template has already defined , user can navigate to the all up view 
- for LG all up view (manaco editor), user can navigate to the right definition no matter template is defined in the same file or in the imported file

**Comment by mewa1024** [comment]
Can we navigate when you click the template reference? @sangwoohaan would that work? also are there specs for hover callout? This:
![image](https://user-images.githubusercontent.com/39317542/105436628-621b7500-5c14-11eb-8788-3b6ed7549b7d.png)

**Comment by sangwoohaan** [comment]
There's no spec for hover call out. I remember this Go to Declaration was going to be the right-click action?
