### ISSUE TITLE
Using Telemetry - track event -> Fails to start bot

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#5525]
**Version: 1.3.0**

When using the Telemetry - track event action the bot fails to start (both a fresh bot and one with custom runtime) throwing the error:

Unhandled exception. System.Exception: hrempower.dialog error: Type Microsoft.TelemetryTrackEvent not registered in factory. ---> System.ArgumentException: Type Microsoft.TelemetryTrackEvent not registered in factory

**Comment by dmvtech** [comment]
Known issue: https://github.com/microsoft/BotFramework-Composer/issues/4305 https://github.com/microsoft/BotFramework-Composer/issues/5400

Workaround:
Change
`"$kind": "Microsoft.TelemetryTrackEvent",`
To
`"$kind": "Microsoft.TelemetryTrackEventAction"`

This should have been fixed though: https://github.com/microsoft/botbuilder-dotnet/pull/4778

@luhan2017 Any insight?

**Comment by dmvtech** [comment]
Sorry didn't read[ the comment ](https://github.com/microsoft/BotFramework-Composer/issues/5400#issuecomment-749286075)fully. This is not included in 4.11.0.

**Comment by cxbuilders** [comment]
@dmvtech ahh, I searched for an issue first, but see the other ones are closed already? For next time, when are bugs actually closed?

**Comment by dmvtech** [comment]
@cxbuilders I'll defer to @cwhitten 

But I think the issues opened in this repo were closed as the issue was found to be in the dotnet library and bug opened there for tracking alone.
