### ISSUE TITLE
Fresh 'yarn install' composer will hit error

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#5531]
Git clone the composer main branch, fresh "yarn install"  will hit following error 
![image](https://user-images.githubusercontent.com/43408889/104699952-6fd18600-574e-11eb-8a49-842649a58610.png)

orchestrator related module is missing 
https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.11.2-dev.20201208.c620747-node-v88-win32-x64.tar.gz

**Comment by boydc2014** [comment]
I also get a 404 by directly visit the above url https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.11.2-dev.20201208.c620747-node-v88-win32-x64.tar.gz. 

@taicchoumsft can you help take a look at this one, maybe our orchestrator js lib is out of date?

**Comment by taicchoumsft** [comment]
Hi @hibrenda , can you try downgrading to Node14 and try?  The `node-v88` portion of the download string is probably causing this.

**Comment by hibrenda** [comment]
@taicchoumsft  yes. It works for node 14.15.4 .

**Comment by taicchoumsft** [comment]
Ok Thanks @hibrenda  closing this issue (please re-open if you really need Node V15 support, we will escalate to Orchestrator core team)
