### ISSUE TITLE
Each dialog in botcomposer needs an Luis app

### ISSUE THREAD

**Issue by arjunDhanAi** [microsoft/BotFramework-Composer#5532]
Hi does each dialog in bot-composer need a Luis app. Can we not have the same app work with multiple dialogs?

**Comment by cwhitten** [comment]
Hi @arjunDhanAi - a recognizer such as LUIS is bound to a Dialog, and no, the same app is not designed to work with multiple dialogs.

An approach to only use one LUIS application would be to have your root dialog be the place where all intent recognition is defined and run and your dialog logic would route from your root dialog to your child dialogs. Any logic inside your child dialogs that may require intent recognition like input dialogs would need to be configured to allow interruptions to get up to the parent dialog with the LUIS application.

Hope this helps

**Comment by Samirun** [comment]
@cwhitten  could you follow these comments which @arjunDhanAi  mentioned above  and let us know the best possible way? let us know if the issue is still unclear.
https://github.com/dhan2018/dhan/issues/769

**Comment by Samirun** [comment]
my simple question is : if i have dialog A and dialog B , and have 10 input prompts  of type yes or no in each dialog,  if I go from dialog A to dialog B through input  interruptions. how would I end dialog A and move to dialog B.
 these 2 dialogs should be able to use a common Luis trigger "yes".
