### ISSUE TITLE
Get Channel info inside composer

### ISSUE THREAD

**Issue by hsachinraj** [microsoft/BotFramework-Composer#5540]
Is it possible to capture channel information like the source inside the composer? I want to capture what channel (Teams, Telegram, Line) the user is using to interact with the bot and based on that capture details like user name/email, etc. Possible?

**Comment by mdrichardson** [comment]
@hsachinraj You can access all of that via the `turn` memory scope with something like `${turn.activity}`. Channel can be found with `${turn.activity.channelId}`. Everything else varies by channel and is likely in either `${turn.activity.from}` or `${turn.activity.channelData}`
