### ISSUE TITLE
Issues with LUIS

### ISSUE THREAD

**Issue by pedro-ramirez-suarez** [microsoft/BotFramework-Composer#5548]
Hello,
We are building a bot that is split into multiple skills, 6 so far and more to come; This is how we are using LUIS:

- We have a different LUIS key for the main/root Bot and for each skill.  LUIS quota is being exhausted frequently for the main bot.
- We are sharing a key for all the developers and QAs, that key is also being exhausted frequently.

I tried to upgrade the pricing tier on the LUIS portal but I get the following error: `"Updating resource failed.
8:34 AM
SpecialFeatureOrQuotaIdRequired: The subscription does not have QuotaId/Feature required by SKU 'S1'." `
On the Azure portal, only the Free tier is available (visible).

 These are my questions:
1. What needs to be done by the Admin so I can upgrade the pricing tier for the LUIS resource?
2. Our environment has 6 skills plus the main bot and each one has it's own LUIS resource, according to the documentation, we can't have more than 10 LUIS resources per region, per account, so we can't have environments for PROD, Staging and DEV in the same account; what's the best practice in this case? can we have the LUIS conversation apps from the main bot and all the skills in a single LUIS resource and have one LUIS resource for each environment? or should we have one account for each environment? 

What's critical for us at this point is to be able to change the pricing tier for a LUIS resource since we also need more that than the 5TPS allowed by the Free tier.

Thanks.

**Comment by dmvtech** [comment]
Hello @pedro-ramirez-suarez 

> We are sharing a key for all the developers and QAs, that key is also being exhausted frequently.

Is this the authoring key or prediction key?

>What needs to be done by the Admin so I can upgrade the pricing tier for the LUIS resource?

I'm not sure on this as this is more of a LUIS/portal question (as well as a billing/portal question) more than a bot/Composer question. I would recommend checking documentation or creating a support issue here:

- https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-limits#resource-usage-and-limits
- https://cognitive.uservoice.com/forums/551524-luis
- https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest

If these are authoring resources (as my assumption is why you can't change the tier), they do have some limits: `Transactions per second: 1 million/month, 5/second`

>Our environment has 6 skills plus the main bot and each one has it's own LUIS resource, according to the documentation, we can't have more than 10 LUIS resources per region, per account, so we can't have environments for PROD, Staging and DEV in the same account; what's the best practice in this case? can we have the LUIS conversation apps from the main bot and all the skills in a single LUIS resource and have one LUIS resource for each environment? or should we have one account for each environment?

Again, this is more of a question for the LUIS experts. You should definitely be using authoring resources for development as that should give you enough wiggle room to develop. But once things are in production/release and you need more resources. But that being said, as far as I know, you should be able to switch to any of the tiers for prediction resources.

**Comment by dmvtech** [comment]
Hi @pedro-ramirez-suarez I'm going to close this as answered. Hopefully you got the issue resolved or were able to get more/better answers from more expert sources.
