### ISSUE TITLE
Unable to update Composer

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/BotFramework-Composer#5549]
## Describe the bug

I have attached the gif that'd give an overview of what's happening. This issue popped up in earlier versions as well [4813](https://github.com/microsoft/BotFramework-Composer/issues/4813)

For the context, I tried both options *Only me (user) or Everyone* while installing Composer. I am also the administrator of this new machine. 

## Version

1.3

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Help'
2. Click on 'Check for Updates'
3. See error

## Expected behavior

It should have updated the Composer.

## Screenshots

![2021-01-19_9-39-17](https://user-images.githubusercontent.com/16351038/104968757-dac6d980-5a3a-11eb-869e-256367bdca55.gif)

After this, I got this error:

![image](https://user-images.githubusercontent.com/16351038/104968707-b10db280-5a3a-11eb-831b-d6000b223bb3.png)

**Comment by cwhitten** [comment]
Hmm. Sorry to hear about your troubles @arafattehsin. I just picked up the latest nightly on Mac and it worked fine.

<img width="575" alt="Screen Shot 2021-01-18 at 4 01 44 PM" src="https://user-images.githubusercontent.com/1156704/104972383-7a865800-59a6-11eb-8100-80828d4ce4c5.png">

On Windows we ask users install the application for all users. 

The following is a heavier operation but should put you in a clean install state:

1. Uninstall Composer (you won't lose any Bot Projects)
2. Delete your entire `@bfc` directory under `C:\Users\AT\AppData\Local\`. Composer will recreate this for you.
3. Reinstall Composer 1.3.0 [here](https://aka.ms/bf-composer-download-win) and turn on Early adopters to pick up the latest nightly

**Comment by hibrenda** [comment]
@cwhitten I can repro this on windows after delete entire @bfc and old composer as well.
![image](https://user-images.githubusercontent.com/43408889/104976372-098f8080-5a38-11eb-90ec-cfef3b71e0ab.png)

**Comment by hibrenda** [comment]
![image](https://user-images.githubusercontent.com/43408889/104979845-32b40f00-5a40-11eb-9be8-3416392f142a.png)

**Comment by boydc2014** [comment]
Update: this is largely related to somehow the permission to the disk is not correctly setup or the folder is occupied by another process somehow, still in the processing of understanding the exact cause. But at this moment, we don't think this is a ship blocker, because we are using the default setup for electron auto-update mechanism without doing any specific thing here, and it works well for all the cases i saw except @hibrenda's.

**Comment by boydc2014** [comment]
We figured out it's a race condition when autoUpdate = true in Brenda's case. @arafattehsin can you check if set autoUpdate = true, if yes, can you try turn if off?

**Comment by arafattehsin** [comment]
@boydc2014  It's still the same re: autoUpdate = false.

**Comment by boydc2014** [comment]
> @boydc2014 It's still the same re: autoUpdate = false.

Can you try the following
1. start composer, assuming 1.3.0
2. turn off Composer's auto update in settings page
3. **quit composer** // this is necessary, because in step 1, the auto update already started working
4. start composer, and check auto update is off or not, if it's off, click "check for updates"

**Comment by arafattehsin** [comment]
Thanks @boydc2014 - your series of steps were super helpful! 

![2021-01-20_0-29-09](https://user-images.githubusercontent.com/16351038/105041021-9c6f0000-5ab6-11eb-9e54-bfe5d29c7d13.gif) - I have made a clip for your reference, there was some error which I think should be handled.

**Comment by arafattehsin** [comment]
Happy to close this issue as it has resolved my problem though! Thanks team. 🤘

**Comment by boydc2014** [comment]
> Happy to close this issue as it has resolved my problem though! Thanks team. 🤘

Thanks, yes, we are aware of this issue, so i opened up #5551 to track the issue. Once that been resolved, it should deliver the expected and hopefully users won't have to do the above steps to work around that.
