### ISSUE TITLE
Waterfall dialog in custom action project

### ISSUE THREAD

**Issue by UmaPrelude** [microsoft/BotFramework-Composer#5550]
Hi,

I want to use waterfall dialog as part of custom action from composer.
I am not able to do it.
If i get any reference it would be great.

**Comment by v-kydela** [comment]
Hi @UmaPrelude 

Composer uses adaptive dialogs, and adaptive dialogs don't generally mix well with waterfall dialogs. If you want to attempt this anyway, I have a few questions.

1. What are you trying to accomplish with waterfall dialogs?
2. Could it be accomplished with adaptive dialogs?
3. Is the action meant to last for multiple turns?
1. What have you tried so far?
2. Can you link to any samples or documentation you've followed?

**Comment by v-kydela** [comment]
@UmaPrelude - Are you still working on this?

**Comment by UmaPrelude** [comment]
Hi @v-kydela,
The requirement we are having is to reuse the dialogs we created in bot framework 4 into composer, so i was trying to have those dialogs[waterfall] as part of custom action and call it from composer.
But we had some problem in it.
That's why i want to know if that is possible from custom action.

**Comment by v-kydela** [comment]
Hi @UmaPrelude

Please go ahead and answer my 5 questions to the best of your ability

**Comment by UmaPrelude** [comment]
> Hi @UmaPrelude
> 
> Composer uses adaptive dialogs, and adaptive dialogs don't generally mix well with waterfall dialogs. If you want to attempt this anyway, I have a few questions.
> 
> 1. What are you trying to accomplish with waterfall dialogs? trying to get couple of inputs from user step by step and process the response in card format, which is already available want to reuse it.
> 2. Could it be accomplished with adaptive dialogs? yes
> 3. Is the action meant to last for multiple turns? yes
> 4. What have you tried so far? As part of actions folder we tried adding the waterfall dialog which we developed already and register the same in custom action and called from composer, got some errors during runtime.
> 5. Can you link to any samples or documentation you've followed? no such sample available.

**Comment by v-kydela** [comment]
@UmaPrelude - Thank you for the information. Based on what you've told me, I don't see a need for custom actions or even an ejected runtime. You can use Composer to create actions that work much like waterfall steps, so my recommendation is to just recreate your bot's logic in Composer. Would that be acceptable to you?

If you still want to incorporate a waterfall into a custom action, you will need to provide your code so I can work with it.

**Comment by UmaPrelude** [comment]
Hi @v-kydela, 
This can be recreated, but in general i want to know if there is a way to use waterfall dialog in custom action.

**Comment by v-kydela** [comment]
@UmaPrelude - It might be possible. Can you show me some sample code?

**Comment by UmaPrelude** [comment]
Thanks @v-kydela, if that is possible i will try once again with a sample waterfall dialog and reopen the ticket if required. For now I am closing this ticket.
As you mentioned, for our current project we have recreated the dialog in composer.
