### ISSUE TITLE
Data race in auto updating vs manual updating

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#5551]
## Describe the bug

We have a data race when user click "check for updates" with auto-update set to true, causing the updating fail (#5549). 

The reason is when auto-update is set to true
1. when composer starts up, we are checking the updates at backend and starts the downloading process, a temp file is created for the
2. when user click check for updates, we are trying to write a same temp file at the same location, then this operation fails because the permission is not allowed, since this file is already created and been actively used. 
3. when the operation in 2 fails, the clean process is trigger, and this file is totally removed, causing composer to be in a bad state where any other following auto & manual update won't work

## Version

lastest main
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Install 1.3.0, turn on auto update
2. Run composer, click "help" => "check for updates"
3. See error

## Expected behavior

1. When auto update is on and is downloading, and when user click manual update, we should prompting user to show we are already doing a downloading now.
2. When auto update finished it's downloading, and user should get a notification to ask user to update or not
3. If user choose to ignore the notification. Then when user click manual update, we will show the same notification again asking for update, without have to download again (if there is not new version).

**Comment by tonyanziano** [comment]
@boydc2014 I'm a little confused about the repro steps.

You say that **we should turn off auto update** and then manually check for updates, but the expected behavior talks about **having auto update enabled** when manually checking for updates.

Due to the nature of the problem, I would assume that you want auto update enabled, so that there is actually a file downloading when you go to manually check for updates. However, I've looked at the code, and we have `checkingForUpdate` and `downloadingUpdate` flags that we flip on when it tries to check for / download an update that should prevent a second update from happening.

If you can reliably reproduce this issue, can you please start up Composer with the `set DEBUG=composer:electron:app-updater` environment variable set, so that we can see the output from the app updater?

We should be able to see any duplicate calls.

**Comment by boydc2014** [comment]
> @boydc2014 I'm a little confused about the repro steps.
> 
> You say that **we should turn off auto update** and then manually check for updates, but the expected behavior talks about **having auto update enabled** when manually checking for updates.
> 
> Due to the nature of the problem, I would assume that you want auto update enabled, so that there is actually a file downloading when you go to manually check for updates. However, I've looked at the code, and we have `checkingForUpdate` and `downloadingUpdate` flags that we flip on when it tries to check for / download an update that should prevent a second update from happening.
> 
> If you can reliably reproduce this issue, can you please start up Composer with the `set DEBUG=composer:electron:app-updater` environment variable set, so that we can see the output from the app updater?
> 
> We should be able to see any duplicate calls.

Sorry, my typo, i mean turn on autoUpdate. 

A more accruate repro, is watch the folder and file been created, and then click check for updates, you will see a surely conflict

**Comment by boydc2014** [comment]
[auto update log.txt](https://github.com/microsoft/BotFramework-Composer/files/5839697/auto.update.log.txt)

**Comment by boydc2014** [comment]
> @boydc2014 Regarding the `needs verify` tag, I just ran into this as part of the bugbash. Repro steps:
> 
> 1. Download Composer
> 2. Settings > Early Adopters: On
> 3. Settings > Auto Update: On
> 4. Help > Check for Updates
> 
> Gets stuck at Downloading: 100%..." with no errors or messages in Networking or Console tabs of the Dev console. Disabling Auto-Update and then again running "Check for Updates" fixes it.

Thanks, we are re-opening this for investigation. @tonyanziano can you help take a look?

**Comment by zhixzhan** [comment]
The fix https://github.com/microsoft/BotFramework-Composer/pull/5573 has been checked in main on 22 Jan
but 1.3.1 released on 14 Jan, so it suppose to be included at next release.

I checked recent nightly build, it works well.

**Comment by boydc2014** [comment]
ok, close it for now.
