### ISSUE TITLE
Refactor ProjectTree

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#5560]
ProjectTree is one critical component that is used in many pages, like design, lg, lu, qna, etc. Current projectTree carries the requirements from all pages and becomes a relatively large component, which renders slow(100~200ms in many cases) and renders too often (listening too much states, and internal states changes very often then re-render again).

By breaking down ProjectTree or refactor ProjectTree in other ways, we are expected to have a more modular structure with a more cleaner data flow, leading us to less render time and less often render frequency.

**Comment by GeoffCoxMSFT** [comment]
I'm focused on the provisioning/publish stuff, so probably won't have time for this task in the near future.
