### ISSUE TITLE
Webchat UI Integration

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#5565]
This ticket encapsulates all the UI work to incorporate Webchat implementation in Composer.

Figma: https://www.figma.com/file/HwYEQoCmWbNrIDdCOmGvzN/bot-testing-BRAINS-storm?node-id=931%3A9852

*   [ ] Restart conversation with the same user ID/different user ID. 
*   [ ] Saving a conversation as a transcript. 
*   [ ] Allow uploads and attachments to a conversation

**Comment by goergenj** [comment]
Based on #5369 and our experience from having a custom version for this, it would be great to add two features:

1. Speech Support
2. Display Backend Messages for better debugging
![image](https://user-images.githubusercontent.com/31212469/107475970-46512200-6b75-11eb-836d-6c9dda357be3.png)

**Comment by mewa1024** [comment]
(@srinaath The link to the figma file above was defaulting to the wrong part of the file. I just updated the link to point to specifically to the part of the file with the details for 1.4. Hope that's okay.)
