### ISSUE TITLE
error Couldn't find package "@microsoft/bf-generate-library@^4.10.0-daily.20210113.202382" 

### ISSUE THREAD

**Issue by Heinzfb** [microsoft/BotFramework-Composer#5567]
## Describe the bug
Hi there,

error Couldn't find package "@microsoft/bf-generate-library@^4.10.0-daily.20210113.202382" required by "@bfc/server@1.0.0" on the "npm" registry.
Try to figure out everything ,node version, looking for this package, ...
Clone it several times, updated net sdk and all other packages
I have no idear :(. Help! Need this for university.

## Version

master version -> via git clone

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. yarn install
2. yarn build
2. Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
3. open 2cnd cli -> cd Composer
4. run yarn ungrade

## Expected behavior
-build the Composer

## Screenshots
![image](https://user-images.githubusercontent.com/67108766/105227691-e4972c80-5b61-11eb-8c84-3996c1cb6bb0.png)

Thank you for your help :)
Kind regards,
Heinz

**Comment by GeoffCoxMSFT** [comment]
The error message indicates yarn is looking on NPM for this package, but the package is sourced on botbuilder.myget.org.  The yarn.lock file helps to ensure it gets resolved from the right package location.

Could you check your Composer/yarn.lock file for bf-generate?  It should read like this:

```
"@microsoft/bf-generate-library@^4.10.0-daily.20210113.202382":
  version "4.10.0-daily.20210113.202382"
  resolved "https://botbuilder.myget.org/F/botframework-cli/npm/@microsoft/bf-generate-library/-/@microsoft/bf-generate-library-4.10.0-daily.20210113.202382.tgz#4e5fc90c53841473138da13d559063adeeddaf5d"
  integrity sha1-Tl/JDFOEFHMTjaE9VZBjre7dr10=
```

In the case where you need to install new packages (or restore them when yarn.lock is missing) from myget, you can add this to your user .npmrc (found in your root user folder):

`@microsoft:registry=https://botbuilder.myget.org/F/botframework-cli/npm/`

**Comment by Heinzfb** [comment]
Thanks for the real fast reply ! 
It is where it should be, I think (see below). 
I forgot closing the cli after the error. I don't know how long it took but I would estimate about 20 min. It create a build but reeaaaal slow. It's working but I don't know if its normal. Enhanced you find the cli, maybe it help. 
[buildAndStartCli.txt](https://github.com/microsoft/BotFramework-Composer/files/5845785/buildAndStartCli.txt)
[upradeCli.txt](https://github.com/microsoft/BotFramework-Composer/files/5845787/upradeCli.txt)



"@microsoft/bf-generate-library@^4.10.0-daily.20210113.202382":
  version "4.10.0-daily.20210113.202382"
  resolved "https://botbuilder.myget.org/F/botframework-cli/npm/@microsoft/bf-generate-library/-/@microsoft/bf-generate-library-4.10.0-daily.20210113.202382.tgz#4e5fc90c53841473138da13d559063adeeddaf5d"
  integrity sha1-Tl/JDFOEFHMTjaE9VZBjre7dr10=
  dependencies:
    "@microsoft/bf-lu" rc
    adaptive-expressions "^4.11.0"
    ajv "^6.9.1"
    botbuilder-lg "^4.11.0-rc0"
    clone "^2.1.2"
    fs-extra "^8.1.0"
    globby "^11.0.1"
    json-schema-merge-allof "^0.6.0"
    json-schema-ref-parser "^7.1.0"
    openapi-types "^1.3.5"
    seedrandom "~3.0.5"
    swagger-parser "^8.0.4"

Thank you :)!
