### ISSUE TITLE
Add LG response editor (Part 1) - basic

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#5570]
Per UX design: https://www.figma.com/file/q76DseJ7PK0g7zI1gXLzlD/SH_Language-Generation?node-id=607%3A1468

- [x] Add   ability to switch between response and code editor     
- [x] Add response editor text area

**Comment by mewa1024** [comment]
@sangwoohaan can we add the template name and params the code view like we discussed the other day? (addresses the parameter issue described in bug #4995
