### ISSUE TITLE
starting conversession from chat history

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#5574]
Hi,

Consider below scenario in the sample bot 
![image](https://user-images.githubusercontent.com/70739031/105284952-742bf200-5bd9-11eb-8fb7-6ef567a272e1.png)

![image](https://user-images.githubusercontent.com/70739031/105285057-9de51900-5bd9-11eb-8633-5229badf1fc3.png)

![image](https://user-images.githubusercontent.com/70739031/105314913-8fe8c580-5be4-11eb-93fa-f592339b717a.png)

After running above bot below is the screenshot of bot execution

![image](https://user-images.githubusercontent.com/70739031/105286227-e1408700-5bdb-11eb-9027-26f6824ca683.png)

![image](https://user-images.githubusercontent.com/70739031/105285855-3760fa80-5bdb-11eb-8a98-e540fe226638.png)

![image](https://user-images.githubusercontent.com/70739031/105285926-5bbcd700-5bdb-11eb-8e29-137a3f296dfc.png)

As shown in above screenshot when we click on any of a button it will display corresponding message plus thank you message and greeting dialog will end. Now if we click again  on any one of the multiple choice button it is not starting the corresponding flow  based on button selected and instead of that it is going to unknown intent. 

Is there any way to start the flow again based on button selected from chat history.

Thanks...

**Comment by ismendes** [comment]
Giving more context to this issue: This is a common complaint that we identified during UX research with the Partner Bot. We have multiple scenarios that fall under this scenario explained by @BeheraMadan, and users don't like the fact that they can't go back in the history and access the content from those points of the dialog again.

**Comment by anusharavindrar** [comment]
@BeheraMadan, the behavior is expected based on how you have designed it. It is not going to start the corresponding flow based on the button selected as the welcome intent has already been done and it will go to the unknown intent and when you click again on any of the multiple choice button, it will say unknown intent. What you can do is to put all this prompt in it's own dialog and call that dialog from the welcome.  Attaching the screenshots of what I tried:

- I made use of the Echo Bot template and then created an options dialog and then called the options dialog from my greetings trigger

![image](https://user-images.githubusercontent.com/48731427/105563027-49799080-5ce2-11eb-80b6-d262e7aa3e6c.png)

![image](https://user-images.githubusercontent.com/48731427/105563181-bbea7080-5ce2-11eb-838e-31900ad0283b.png)

![image](https://user-images.githubusercontent.com/48731427/105563357-69f61a80-5ce3-11eb-9311-85f386edf814.png)

- When I run the bot and open it in the Emulator, the response is:

![image](https://user-images.githubusercontent.com/48731427/105563458-bfcac280-5ce3-11eb-8874-98628f38ed84.png)

- After the thank you message, I click on the flow 3 button and the prompt appears again for me to select from the multiple choice buttons.

![image](https://user-images.githubusercontent.com/48731427/105563478-d113cf00-5ce3-11eb-9924-018c208cbbae.png)

Please let me know if this is works for you.
