### ISSUE TITLE
Cannot run 'update-schema' after runtime updating to '4.12.0-daily*'

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#5576]
#### Problem
Cannot run the `update-schema` script under the `schemas/` folder after ejected the runtime instance.
It will fail silently:
![image](https://user-images.githubusercontent.com/8528761/105344277-b1b26e80-5c1d-11eb-88b3-e9fe8bc23d19.png)

#### Cause
In #5529 , runtime's dependencies were updated to `4.12.0-daily*`, it caused the `update-schema.sh` script cannot reference the exact pacakge given the asterisk wildcard.

#### Workaround
Replace all appearances of `4.12.0-daily*` to `4.12.0-daily` (without `*`) accross all csproj files can bypass this issue.
![image](https://user-images.githubusercontent.com/8528761/105347541-06f07f00-5c22-11eb-9f3d-7247b2fcbfb6.png)

For a long term fix, we may need to update the source code bf dialog:merge command to match package names with asterisk.

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by GeoffCoxMSFT** [comment]
I tried putting the references without the wildcard, but a nuget restore will mismatch and try to resolve its "best guess" which happens to be an ancient version from back in Oct. 2020.  I'll go look at the bf-merge code.

**Comment by chrimc62** [comment]
Resolved by https://github.com/microsoft/botframework-cli/pull/1096
