### ISSUE TITLE
Collect the Azure subscription ID as part of the publishing profile

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#5577]
The subscription id is needed to take follow-up actions on the bot registration and other resources.  For example, managing channels on ABS will require this value, and if not present, we will have to prompt the user.

This field should be added to the publishing profile at the root level of the object.

- [ ] In Composer
- [ ] In azureProvision.js cli tool

**Comment by luhan2017** [comment]
@zidaneymar, let's get a design on the new schema of publish profile. (with ABS scenario, we may need more info than subscription). And let's paste the design here.

**Comment by zidaneymar** [comment]
```
{
  "accessToken": "",
  "name": "",
  "environment": "",
  "runtimeIdentifier": "win-x64",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": ""
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "",
      "authKey": "",
      "databaseId": "",
      "collectionId": "",
      "containerId": ""
    },
    "blobStorage": {
      "connectionString": "",
      "container": ""
    },
    "luis": {
      "authoringKey": "",
      "authoringEndpoint": "",
      "endpointKey": "",
      "endpoint": "",
      "region": ""
    },
    "MicrosoftAppId": "",
    "MicrosoftAppPassword": "",
    "qna": {
      "endpoint": "",
      "subscriptionKey": ""
    }
  },
  "hostname": "",
  "luisResource": "",
  "abs": {
    "botId": "",
    "botName": "",
    "appPasswordHint": "",
    "subscriptionId": "",
    "resourceGroup": "",
    "resourceId": "",
    "armEndpoint": ""
  }
}
```
@luhan2017  This is the concrete publishing profile for abs scenarios, do we need to move 'abs' section to root level?

**Comment by luhan2017** [comment]
@zidaneymar  let's remove the abs group and we have two options to support abs scenario:
1. appPasswordHint and resounrceId, the resourceId is the abs resourceId like this, we can parse the subscriptionId, resourceGroup and botServiceName from this resourceId. 
```
/subscriptions/3e71927d-2914-4c36-bc5d-6369d1f42457/resourceGroups/composerTest0518-dev/providers/Microsoft.BotService/botServices/composerTest0518
```
2. 
- appPasswordHint
- subscriptionId  // we are assuming all the services in one publish profile are under the same subscription id? If yes, we can update provision v2's design to remove the subscriptionid. 
- resourceGroup // we can only guarantee the resource group is the resource group of abs.
- botName // We will use subscriptionId + resourceGroup + botName to generate the resourceId, need to check with Hai if this is reliable, will user update the botName to a different value?

@benbrown, We want to make the publish profile as simple as we can, but we do want to make it extensible. Which option do you prefer or do you have other ideas on this?

**Comment by benbrown** [comment]
Note: We need to make sure that any changes we make to this to support the new ABS fields do not break existing profiles.

We will need to capture the subscriptionId *regardless* of whether the bot was imported from ABS or not.  I think it would make sense to be at the root.
