### ISSUE TITLE
Increase Electron `max-header-size` by default

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Composer#5579]
Trying to provision / publish to Azure sometimes fails with a 431 if the token in the header is too large.

See #5377 for reference

Currently there is a workaround by setting the following environment variable before starting Composer:

`set NODE_OPTIONS="--max-http-header-size=<some size in bytes>"`

Ex: `set NODE_OPTIONS="--max-http-header-size=16000"`

## Version

1.3.x

## Expected behavior

It would be nice if the user did not have to set this explicitly _after_ running into the error, and if we could just set this at the time of invoking Composer.

However, I was experimenting with this the other day, and it seems like this cannot be set at runtime in the application code, but must be set when / before invoking the Electron binary to start our app.

**Comment by tonyanziano** [comment]
Notes about the issue:

- Might be worth trying to use `app.appendCommandLineSwitch()` to provide this default
- Since Node 13, this default value has been increased from 8 KB to 16 KB ([source](https://github.com/nodejs/node/commit/bd9f4d295495b11d2e460b320681e18a11524bb8))
  - Electron v11 is only at Node v12.8.3 right now, so we would have to wait for a newer version with Node v13.x, and then maybe bumping to the newer version would resolve this
 - Could possibly try bumping up the limit on a per-request basis using the Node `http.request` options property `maxHeaderSize` ([docs](https://nodejs.org/api/http.html#http_http_request_options_callback)]

**Comment by franctum5** [comment]
hi @tonyanziano , does the workaround with setting the environment variable works also with the pre compiled version of Composer?

I'm setting the variable before opening it but I still get the same error.

Thanks!
