### ISSUE TITLE
Impossible to use imported resource to deploy new bot

### ISSUE THREAD

**Issue by MIkey007007** [microsoft/BotFramework-Composer#5580]
## Describe the bug

I am using the bot composer created from the latest release of the source (yarn startall). In another word, I am not using the desktop version's composer (see this https://docs.microsoft.com/en-us/composer/install-composer) to publish a new bot. Instead of creating new resources, I am importing existing resources (web app and the channel) to publish the new bot.  In another word, I want to use a bot channel created previously (It was working) to publish the new bot to a web app hosted by the azure cloud. So I follow the displayed instructions step by step.  I follow the instruction to specify the access token. Yet, it failed.  I am getting the following error messages:

DEPLOY_ZIP_ERROR

Please see the attached snipped screenshot to see the detailed error message. 
![composer-error](https://user-images.githubusercontent.com/2760820/105400024-3cbd4580-5bd9-11eb-9087-06f2c1cc79d5.png)

## Browser

Chrome 

- [ ] Electron distribution
- [X ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
Hi @MIkey007007 Are you configuring the hostname correctly in your publishing settings? In the screenshot above, it is showing the default/sample value `<unique name in your subscription>`. 

![image](https://user-images.githubusercontent.com/43397658/106073870-afd62880-60bf-11eb-8e19-ec509a1940de.png)

**Comment by MIkey007007** [comment]
@ dmvtech: thanks for following up. It has been resolve. It turns out that the channel password was incorrect.

**Comment by MIkey007007** [comment]
Thanks for following up. Asher
