### ISSUE TITLE
Qna Madaptive card responses not rendering in emulator and webchat/botcomposer

### ISSUE THREAD

**Issue by Samirun** [microsoft/BotFramework-Composer#5587]
## Describe the bug
qna maker returns adaptive card response as a string. because of which we had to extend qna maker dialog through code but our main aim is to just use composer, add qna maker to it and get adaptive card response rendered correctly.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/46156330/105447671-a7828580-5c9a-11eb-931a-2e2e3152f93c.png)

## Additional context
if the above is not possible. what is the best way to do it with code.

**Comment by stevkan** [comment]
You can achieve rendering an adaptive card passed from QnA by utilizing the LG adaptive card syntax, referenced [here](https://docs.microsoft.com/en-us/composer/how-to-send-cards#adaptivecard). In this scenario, I am using the QnA Sample found in Composer. I update the "Send a response" action by replacing the `expandText` function with the `json` function. I then wrap it in the "Activity" structured response and assign the json parsed QnA answer to the "Attachments" property. My "Send a response" code changed from

```
- ${expandText(@answer)}
```

to

```
[Activity
  Attachments=${json(@answer)}
]
```

**Composer:**
![image](https://user-images.githubusercontent.com/18403946/105542599-5086ab80-5cae-11eb-85d9-e66cdb114bcc.png)

**Emulator result:**
![image](https://user-images.githubusercontent.com/18403946/105542649-53819c00-5cae-11eb-9b29-18b1e3218fbb.png)

This should resolve your issue.
Hope of help!

**Comment by Samirun** [comment]
@stevkan thanks for the quick reply but   this way a new kb is being created in qna maker. we already have a kb created in qna maker with adaptive cards,  we just want to use it directly in composer as a response.

![image](https://user-images.githubusercontent.com/46156330/105568509-e0d0f900-5d5f-11eb-90f9-464e13722ef8.png)

using this we are getting answers but no clue how do we convert that answer to json.

we have  a kb with adaptive cards already built in qna maker.how do convert that response to json? or is there any feature.
