### ISSUE TITLE
FORM DIALOGS: schema editor: maybe do not generate empty property rows onClick "add property"? 

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#5593]
## Describe the bug

In the forms schema UI, the user clicks "add property", a new line is created. 
In many cases, the user doesn't input any data to the property, the UI ended up having an error.
For first time users, the errors are confusing; for other users, they have to delete the empty rows to clear the error.
![Screen Shot 2021-01-24 at 2 43 56 PM](https://user-images.githubusercontent.com/74994573/105646072-98463800-5e52-11eb-8a35-c907bfe5abe0.png)
## Version

v1.3.1 - nightly.203676.66f6854

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [X] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'forms tab'
2. Click on 'add property'
3. Click anywhere outside the "add property" modal

## Expected behavior

- Do not generate a new line if it's empty.

**Comment by xiyangdesign** [comment]
@mewa1024 do you think we could also address this issue in R12? This also come commonly in user studies.

**Comment by mewa1024** [comment]
yes, I'd like to test the card UI against the table UI and if users prefer the card UI, then make improvements like this.

**Comment by xiyangdesign** [comment]
good point! the table UI solves this issue automatically!
