### ISSUE TITLE
formatDateTime not allowed with extra locale settings

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#5595]
In the [adaptive expressions documentation](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#formatDateTime) it shows that formatDateTime can accept an additional locale parameter:
![image](https://user-images.githubusercontent.com/49873947/100988865-787c4d00-3550-11eb-8786-1a8d8a1b36ca.png)

The validation in Composer however does not allow that:
![image](https://user-images.githubusercontent.com/49873947/100989157-d01ab880-3550-11eb-8144-541da53be529.png)

**Comment by cosmicshuai** [comment]
@LeeParrishMSFT 
I just opened a new PR for updating the adaptive-expression version. This solved the intellesence problem for locale parameter. Also, I updated the built-in function map to make sure, the language server can auto-suggest all available functions we have in Expressions.

**Comment by srinaath** [comment]
@cosmicshuai I see a linked PR. Can we drive this ticket to closure?
