### ISSUE TITLE
Extension API for Webchat scenarios

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#5604]
This ticket encapsulates Composer Extension API's work to incorporate Webchat as an standalone extension in Composer.

In webchat scenario, we will have 2 more extension contribution points:
- The right pane (as chat pane) - for the webchat control
- The bottom pane (as debug pane) - for containing the 'Errors and warnings'/ 'Emulator logs' and future tabs

It requires Composer Extension API to support:
- [ ] Extension API for chat pane on the right
- [x] Extension API for debug pane on the bottom
- [x] ~~A new mechanism to communicate between two extensions (be able to share state)~~ (covered in #5589)

**Comment by yeze322** [comment]
refs #5686 - Debug pane on the bottome
refs #5589 - Extension event API by Andy

**Comment by a-b-r-o-w-n** [comment]
@yeze322 Can you elaborate on how you see two extensions sharing their state via event emitting? Just want to make sure we are aligned.

**Comment by yeze322** [comment]
@a-b-r-o-w-n Andy as we discussed, in R12 webchat is not implemeneted as an Extension considering development efficiency, so I'll close this issue.

It's these two extensions will share some states:
![image](https://user-images.githubusercontent.com/8528761/108650659-038b3480-74fb-11eb-9980-ae4d42b1a16e.png)
Webchat window emits log events, the debug panel subscribes to that.

Currently, they are implemented as built-in components, states are sharing via a recoild state directly.
