### ISSUE TITLE
Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by kayodeAjayi** [microsoft/BotFramework-Composer#5605]

**Comment by v-kydela** [comment]
Thank you for the report, @kayodeAjayi. It sounds like you might be getting an error message. If you would like some help with that, can you please provide some screenshots and repro steps?

**Comment by kayodeAjayi** [comment]
I was publishing my bot to azure portal when my system crashed. The file is
no longer opening on my computer. Giving me the above error.

Unexpected token in JSON at position 0.

Everything was working fine before the crash happened.

**Comment by v-kydela** [comment]
@kayodeAjayi - I'm sorry to hear that. If you would like some help with that, could you please provide some screenshots and repro steps?

**Comment by v-kydela** [comment]
@kayodeAjayi - Are you still working on this?

**Comment by kayodeAjayi** [comment]
I actually started again and I'm done. I was careful to plug my pc in while
publishing to avoid a reoccurence

**Comment by v-kydela** [comment]
@kayodeAjayi - I'm glad to hear it. I'll go ahead and close this as resolved for you.
