### ISSUE TITLE
Enable LUIS vNext Train API via env variable

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#5608]
We need to enable a way for Composer users who are in the LUIS vNext preview to use the new API.

Implement a private environmental variable, set before launching Composer, to determine if the preview LUIS vNext API is used.  This ensures that users can enable / disable the feature (given they will still have a need to call the Production API) and also means we avoid making any changes to the Composer UI until a broader rollout of the preview. 

If the flag is enable then an additional query parameter is needed when calling the Train API - the new parameter is called 'mode' and the value should be 

- 'Standard' when the preview is disabled
- 'Neural' when the preview is enabled

**Comment by cwhitten** [comment]
@feich-ms @boydc2014 sync with @garypretty and myself to discuss this in more detail if needed.

**Comment by feich-ms** [comment]
I will take a look. This looks like the similar solution as the userAgent setting before. bf-lu will consume a env variable to decide call preview or not. Will prepare a PR soon.

**Comment by cwhitten** [comment]
Thanks Fei!

**Comment by feich-ms** [comment]
Prepared a fix here https://github.com/microsoft/botframework-cli/pull/1099. I manually verified that train will take neural model once set LUIS_TRAIN_MODE=Neural. Composer can also take changes in its luis build api interface to enable this by setting trainMode to Neural.
