### ISSUE TITLE
Documentation/Bot Runtime update needed for Composer bots in US Government data center

### ISSUE THREAD

**Issue by p-nagpal** [microsoft/BotFramework-Composer#5613]
## Describe the bug

The documentation to modify a bot for US Government data centers needs to be updated for composer bots (or if possible the bot runtime can support this out of the box). Docs: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-faq-ecosystem?view=azure-bot-service-4.0#how-do-i-create-a-bot-that-uses-the-us-government-data-center

In addition to the steps mentioned in the docs, BotFrameworkHttpAdapter creation had to be modified to take channelProvider  in startup.cs as follows.
	var adapter = IsSkill(settings)  ? new BotFrameworkHttpAdapter(new ConfigurationCredentialProvider(this.Configuration), s.GetService<AuthenticationConfiguration>()**, channelProvider: s.GetService<IChannelProvider>()**)  : new BotFrameworkHttpAdapter(new ConfigurationCredentialProvider(this.Configuration), **channelProvider: s.GetService<IChannelProvider>()**);

Without this change, the bot runtime does not pick up the ChannelService setting pointing to the US Government Data Center.

## Version
v1.3.0

**Comment by ParagHurkat** [comment]
I investigated a similar issue and I created a document about the same.

Here is the link for the same in case it helps : https://techcommunity.microsoft.com/t5/iis-support-blog/azure-government-bot-through-bot-composer/ba-p/2083898

**Comment by zxyanliu** [comment]
@p-nagpal @ParagHurkat Thanks for the feedback and apologies for the late reply. 
We will consider adding this content to the upcoming Composer docs release.

**Comment by zxyanliu** [comment]
Hi @p-nagpal 
I am wondering if there is an account/subscription requirement to deploy a bot to Azure Gov cloud? 
I tried to create a web app bot and channels registration resources and I got 404. 

![image](https://user-images.githubusercontent.com/32497439/106561380-6a5d9500-64dd-11eb-95bd-bd4df94ab740.png)

**Comment by zxyanliu** [comment]
@p-nagpal Thanks again for troubleshooting this for me. Now the Web App Bot worked on my end. :-)

**Comment by zxyanliu** [comment]
FYI. I tried using an Azure Gov account to login to Azure Gov from Composer and failed. 
@tonyanziano do we support in-app login to Azure Gov from Composer?
