### ISSUE TITLE
Add telemetry for lg templates and expression

### ISSUE THREAD

**Issue by feich-ms** [microsoft/BotFramework-Composer#5618]
**What**: LG authoring experience improvements  

**Why**: Based on current dashboard, sendactivity is one of the most often used actions in composer bot authoring.  So the usage and engagement metrics with more drill down of LG in composer can help accurately indicate LG performance trends and also provide better authoring investment for LG editor 

Current prebuilt function is auto-hint by alphabetical order but user could gain more by “often used” function or “most popular” expression.  

Card utilization or speech adoption are also the key metrics  

**For  Who**: This could reduce the learning curve for new users and also provide more intuitive authoring for existing and experienced developers.

Pri | Item | Area | Properties to capture | Notes
-- | -- | -- | -- | --
P0 | LG template with plain text response. This includes simple response and condition response (starting with “-“) | LG | The number of LG plain text |  
P0 | LG template with structured response for activity template and activity with speech | LG | [Activity] response usage [Activity] with speak usage [Activity] with attachment (card) usage |  
P0 | LG template with card response | LG  | Card usage HeroCard ThumbnailCard SigninCard AnimationCard VideoCard AudioCard AdaptiveCard |  
P0 | Adaptive Expression usage | Expression  | prebuilt function usage   defined in one template |  
P1 | LG features using namespace/export option |   | namespace/export option usage |  
P1 | LG with multi-lang |   | Language usage |  
  |   |   |   |

**Comment by garypretty** [comment]
Removing the R12 milestone from this issue as we will not progress this until we have data regarding how the new LG authoring experience is being used once that has been delivered.
