### ISSUE TITLE
Azure publishing - type of Azure account

### ISSUE THREAD

**Issue by dbfr1** [microsoft/BotFramework-Composer#5621]
Hi,
I'm trying to deploy my Bot project to Azure but I just get this information: This type of account doesn't work with this particular service. Please enter an email address or phone number associated with a different account.

Can someone tell me please what should I do? It will be perfect to use this Azure account because I have everything else there.

Thanks for help!

**Comment by operatedcoin** [comment]
Thread here has more on this problem with resolution still outstanding: https://github.com/microsoft/BotFramework-Composer/issues/5393

**Comment by dbfr1** [comment]
thanks!

**Comment by srinaath** [comment]
Details on the #5393 . Closing the ticket.
