### ISSUE TITLE
LUIS returns 404 error when used through recognizer

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#5622]
## Describe the bug

Publishing to LUIS or something about the LUIS recognizer has broken recently.  In the nightly build, publishing to LUIS results in a bot that returns a 404 error whenever it consults a LUIS model --- though the publish seems to work as expected.

Attached below are a screenshot of the request and response from the LUIS recognizer call.

## Version

Currently nightly build

## To Reproduce

1. Create a new bot based on the luis todo template
2. Set your luis key and region
3. Start the bot
4. Open in emulator and type any message
5. LUIS will return a 404 error, and the bot will say:

"Response status code does not indicate success: 404 (Not Found)."

## Screenshots

![Screen Shot 2021-01-26 at 3 54 14 PM](https://user-images.githubusercontent.com/729873/105910594-c6607f00-5fee-11eb-9a81-de3443795852.png)
![Screen Shot 2021-01-26 at 3 54 55 PM](https://user-images.githubusercontent.com/729873/105910663-e09a5d00-5fee-11eb-8833-80dc5abb75be.png)
![Screen Shot 2021-01-26 at 3 55 01 PM](https://user-images.githubusercontent.com/729873/105910669-e2642080-5fee-11eb-93d8-b9dc5dc2be93.png)

**Comment by chrimc62** [comment]
It is exactly these kinds of issues that are caught by having composer dailies use the latest SDK.  Otherwise we end up with a scramble at the end when the composer or SDK have a bug or mismatch.  The LUIS version API definitely did work, so this may be a recent regression on their side as well.

**Comment by luhan2017** [comment]
@zidaneymar We should support the directVersionPublish for the deployment script.
