### ISSUE TITLE
Azure publishing hangs when no publishing profile exists

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#5624]
## Describe the bug

Created a simple ToDo bot and tried to publish to Azure. Composer reports "Publishing 1 bots" constantly and hasn't actually created any resources in Azure. This is due to a publish profile not being created yet the Publish to Azure functionality lets me proceed to publishing.

## Version

1.3.1-nightly.204896.1ed31e1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. New
2. Create from Template
3. Todo with LUIS
4. Publish tab
5. Publish selected bots

## Expected behavior

If no publish profile exists (new bot) then put me directly into the "new publish profile" flow and guide me through.
Also - no error is shown?

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/105996157-dedda180-60a1-11eb-8b4a-40043a35bd41.png)

**Comment by VanyLaw** [comment]
@alanlong9278 Could you take a look

**Comment by alanlong9278** [comment]
Like the below image show, the publish button can not be clicked if the selected bot has no publish profile currently.
![image](https://user-images.githubusercontent.com/5860999/106109198-32282080-6184-11eb-93c8-198bd30caf7e.png)
Should we have a guide flow like poping up a notice say `U should create a publish profile` when clicking or hovering in the publish button?

**Comment by srinaath** [comment]
@alanlong9278 So, why do we let publishing to happen when there is not publishing profile?

**Comment by alanlong9278** [comment]
Publish button is disabled when there is no publish profile. But I have checked that the code is just merged into main branch not for release branch. So maybe we should wait a while for release new version. @srinaath

**Comment by luhan2017** [comment]
Close this issue because this is already fixed in the latest main branch. @darrenj please try the latest nightly build.
