### ISSUE TITLE
Load any projects fails

### ISSUE THREAD

**Issue by fabrizioregio** [microsoft/BotFramework-Composer#5626]
I don't see Navigation pane on the left, the Authoring canvas in the middle, and the Properties panel (Adaptive dialog) on the right after load a project.

The tool remaining freezed.

1.3.0

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

Change a default language  for the bot.

**Comment by srinaath** [comment]
Closing this issue. As we have a fix for it in R12.

#5634
