### ISSUE TITLE
DEPLOY_ZIP_ERROR - RequestError - Error: getaddrinfo ENOTFOUND microsoft

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/BotFramework-Composer#5628]
## Describe the bug
Installed Bot Composer. 
Created a New Bot from the EchoBot Template.
Created a publishing Profile to an existing set of Azure Resource
Publish unmodified Echo bot to profile
Get:
DEPLOY_ZIP_ERROR - RequestError - Error: getaddrinfo ENOTFOUND microsoft

## Version

v1.3.0

## OS

Windows

## To Reproduce

Install Bot Composer. 
Create a New Bot from the EchoBot Template.
Create a publishing Profile to an existing set of Azure Resources
Publish unmodified Echo bot to profile
Get:
DEPLOY_ZIP_ERROR - RequestError - Error: getaddrinfo ENOTFOUND microsoft

## Expected behavior

Expecteed Bot to Publish to designated Azure environment

## Screenshots

![image](https://user-images.githubusercontent.com/12382552/106053752-c6c14e80-60b0-11eb-9c4c-94ad2e0090b1.png)

**Comment by DavidStrickland0** [comment]
Wouldn't qualify this as a fix but reviewing #5354 may lead to a better understanding of the problem and a work around.
Beyond the completely obtuse error message which in and of its self is a bug.
I believe it has to do with the fact that the default template for publishing doesn't contain the hostname property.

IE:
`{
  "name": "Luhan0603AF",
  "environment": "dev",
  "hostname": "Luhan0603AF-dev",   ------------------> This is the name of your webapp.`

After creating and then setting this property to the name of my app server I was able to publish.

Note: For the next poor dev that charges this windmill if you create / set and save this property and then go back in and try to look at it. It's not missing. Composer has just taken the liberty of reorganizing your config and it's now all the way on the bottom. Likely another "bug" but meh.

**Comment by srinaath** [comment]
@DavidStrickland0  Several updates are being made to this workflow in the upcoming release. This bug would be resolved.

**Comment by srinaath** [comment]
@luhan2017 The error message still needs to be more descriptive.

**Comment by luhan2017** [comment]
@VanyLaw @alanlong9278 let's update this error message a little bit. The error message could be something like: The hostname: {hostname} is invalid, please check if hostname/name-environment matches your target resource(webapp/function) name.

**Comment by Andres-Coronado** [comment]
I am having the same error Does anyone has find the solution? 
![err](https://user-images.githubusercontent.com/53791842/117719237-c3a32780-b1a2-11eb-86b1-98bf869bea77.PNG)
