### ISSUE TITLE
Orchestrator: Multi-Language Model Support

### ISSUE THREAD

**Issue by taicchoumsft** [microsoft/BotFramework-Composer#5629]
Dependencies:
- Pending Orchestrator Recognizer (SDK) work completion
- Pending size reduction from Orchestrator Core (current multilang model is 1GB)

Requirements:
- At a high level, must be able to support Multi-Lang the same way LUIS does in Composer
- Download multi-lang model and set it up correctly in orchestrator settings when user has enabled multiple languages
- Generate snapshots correctly in multiple languages

**Comment by dubey20siddharth** [comment]
Hoe can we increase prediction score of multilingual detection in LUIS ?
