### ISSUE TITLE
Wide switch statements don't show last condition

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#5637]
## Describe the bug
If I have a switch statement with many conditions the UI doesn't display the last condition.

## Version
1.3

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a switch statement with several conditions (6 or more)

![image](https://user-images.githubusercontent.com/12264946/106101018-4845ca80-610b-11eb-9bc5-023d0e64b517.png)

2. The last condition won't show on the design surface and you can't scroll to see it.

It will show once you add an action to it but you won't know the condition unless you read the switch statement or until you add that action. 

![image](https://user-images.githubusercontent.com/12264946/106101259-a2469000-610b-11eb-85da-0ca29d5e0e53.png)

## Expected behavior

I would expect to be able to scroll and see the condition without having to add an action.

**Comment by srinaath** [comment]
@yeze322 It looks like the last condition is cut off. Can you check if this is a small fix to get it into R12?

**Comment by yeze322** [comment]
@srinaath yes we can, adding a 50px padding to the canvas container will work

**Comment by yeze322** [comment]
addressed in #5693
