### ISSUE TITLE
Luis Recognizer in TextInput Prompt

### ISSUE THREAD

**Issue by irwinwilliams** [microsoft/BotFramework-Composer#5641]
## Describe the bug
It's my understanding that when you're in a child dialog, the responses get processed by that dialog first and then get bubble up to the parent dialog, either because of the automatic conclusion of the child dialog, or because the child deliberately invoked the parent dialog before its own conclusion.
I have created a sample based on this tutorial, https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis.
It's available here: https://github.com/irwinwilliams/nurse-carter-luis-example

While I've gotten the bot to use its LUIS recognizer to successfully invoke the child dialogs, when I try to get input, the default behavior is to invoke the LUIS recognizer again, which triggers the dialog at the parent level and don't result in the Text Input getting a result.

## Version
          Bot Framework Composer

                Version:  1.3.0
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0
              
## Browser
- [ ] Electron distribution
- [* ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [* ] Windows
- [ ] Ubuntu

## To Reproduce

See provided sample

**Comment by dmvtech** [comment]
@irwinwilliams I've got your bot and am taking a look.

**Comment by dmvtech** [comment]
I think the crux of the issue is that you have duplicate triggers for `facility`, `help` and `cancel`. have a 

```
{
  "triggers": [
    {
      "$kind": "Microsoft.OnConversationUpdateActivity"
    },
    {
      "$kind": "Microsoft.OnIntent",
      "intent": "facility",
      "actions": [
        {
          "$kind": "Microsoft.BeginDialog",
          "dialog": "getFacility"
        }
      ]
    },
    {
      "$kind": "Microsoft.OnIntent",
      "intent": "help",
      "actions": [
        {
          "$kind": "Microsoft.BeginDialog",
          "dialog": "getHelp"
        }
      ]
    },
    {
      "$kind": "Microsoft.OnIntent",
      "intent": "cancel",
      "actions": [
        {
          "$kind": "Microsoft.BeginDialog",
          "dialog": "cancel"
        }
      ]
    },
    {
      "$kind": "Microsoft.OnIntent",
      "intent": "cancel",
      "condition": "=#Cancel.Score >= 0.8",
      "actions": [
        {
          "$kind": "Microsoft.BeginDialog",
          "dialog": "cancel"
        }
      ]
    },
    {
      "$kind": "Microsoft.OnIntent",
      "intent": "help",
      "condition": "=#Help.Score > 0.5",
      "actions": [
        {
          "$kind": "Microsoft.BeginDialog",
          "dialog": "getHelp"
        }
      ]
    },
    {
      "$kind": "Microsoft.OnIntent",
      "intent": "facility",
      "condition": "=#Facility.Score >= 0.8",
      "actions": [
        {
          "$kind": "Microsoft.BeginDialog",
          "dialog": "getFacility"
        }
      ]
    }
  ]
}
```

I removed the ones that did not have a condition, ensured their LU was matched up correctly and then was able to run and test and it seems to be working as expected. Please give that a try and let me know if that works for you. I am also able to share the bot with changes, if needed.

**Comment by irwinwilliams** [comment]
Thank you very much, I removed the regex-based ones, had to recreate the trigger words for the ones that remained and it worked!
