### ISSUE TITLE
Can't Delete Publish Target

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/BotFramework-Composer#5642]
## Describe the bug

There is no way to delete a Publish Target short of editing the json file.

## Version

v1.3.0

## OS
- [ ] Windows

## To Reproduce

1. Create a Publish Profile
2. Attempt to Delete it

## Screenshots
![image](https://user-images.githubusercontent.com/12382552/106158347-3f73e980-6149-11eb-861a-8e55066aadd7.png)

**Comment by srinaath** [comment]
@DavidStrickland0  This is definitely in our plans.
