### ISSUE TITLE
Ensure the arm templates include a clientID or some guid that can be used for telemetry

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#5643]
We need to make sure the arm templates use the most recent mechanisms for identifiying themselves as the source of a provision action.

**Comment by luhan2017** [comment]
@benbrown do you mean this, we do have this in provision script, also in composer provision flow. We can view the provision data from the armprod. 

![image](https://user-images.githubusercontent.com/32191031/106246099-87c60100-6248-11eb-950e-4837c76ae689.png)

**Comment by luhan2017** [comment]
But I found the armprod only save the data about 1~2 month, the old data are all gone... I am not sure if we can get it back.

**Comment by luhan2017** [comment]
https://github.com/microsoft/BotFramework-Composer/blob/5af3f50ef41e3ef471771deb141437b3c3ae6e92/extensions/samples/assets/shared/scripts/DeploymentTemplates/template-with-preexisting-rg.json#L150

I just found that this function has been commented out, we should get it back to collect the data.  
https://github.com/microsoft/BotFramework-Composer/blob/d79ef62f1c36242260c1db29f607c87482cadce6/extensions/azurePublish/src/node/provision.ts#L371

**Comment by benbrown** [comment]
Thanks to everyone who contributed to this effort!
 
Our PM team confirms that this data is what we need for now.
