### ISSUE TITLE
Adding Mouseover to Adaptive Card Button

### ISSUE THREAD

**Issue by thakursarvesh** [microsoft/BotFramework-Composer#5645]
Hi Team, Do we have a way to add tooltip or mouseover text to the Submit buttons in adaptive card. I know we can do it from the webchat frontend but that will fail in teams. I want something which we can implement directly in Adaptive cards.

**Comment by v-kydela** [comment]
@thakursarvesh - It is not currently possible to add tooltips to cards in Teams, but there's a tooltip feature proposed here: https://github.com/microsoft/AdaptiveCards/issues/1788

I will close this as unrelated to Composer
