### ISSUE TITLE
Provision Failure Error When Attempting to Create a Publishing Profile

### ISSUE THREAD

**Issue by godlikesme** [microsoft/BotFramework-Composer#5650]
## Version

1.3

## Browser

N/A

## Operating System

- [X] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to "Bot Management and Configuration".
2. Scroll to the "Publish Targets" section at the bottom of the screen.
3. Click "Add new publish profile" link.
4. Enter profile name and select "Publish bot to Azure Web App" for the "Publish Target".
5. Accept the default "Create new Azure Resources" option.
6. Select Azure subscription.
7. Enter name of resource group.
8. Enter location.
9. Accept default values on the "Review + Create" screen.
10. See error

## Expected behavior

I expected to have each of the selected resources (resource group and accompanying required services) provisioned in Azure.

## Screenshots

![Screen Shot 2021-01-28 at 3 53 53 PM](https://user-images.githubusercontent.com/76570480/106197949-546c6f00-6181-11eb-83aa-e3fc4074ebc9.png)

![Screen Shot 2021-01-28 at 3 55 35 PM](https://user-images.githubusercontent.com/76570480/106197959-57fff600-6181-11eb-8a75-43c4dce163db.png)

![Screen Shot 2021-01-28 at 3 58 09 PM](https://user-images.githubusercontent.com/76570480/106198132-a4e3cc80-6181-11eb-9b22-fcb6dec587a1.png)

![3C9B2A94-E2FE-4942-9434-25CF45437DB2_4_5005_c](https://user-images.githubusercontent.com/76570480/106197536-d90abd80-6180-11eb-8dcc-e23b577cb984.jpeg)

**Comment by luhan2017** [comment]
@godlikesme This is a duplicate issue with #5467 , could you mitigate this by:

**Comment by saleung** [comment]
> @godlikesme This is a duplicate issue with #5467 , the root cause is token too large which causes 431 request header too large error. could you mitigate this by:
> 
> * Open cmdline, navigate to the Bot Framework exe folder.
> * set NODE_OPTIONS="--max-http-header-size=16000"
> * and start Bot Framework Composer

I am still getting the same error after running > set NODE_OPTIONS="--max-http-header-size=16000" within \Bot Framework Composer-1.3.0 I have also tried the same in nightly build 73c0bce with the same result. Any advice as to what I'm doing wrong?

**Comment by luhan2017** [comment]
@saleung, did you still have this issue in the latest nightly?

**Comment by saleung** [comment]
> @saleung, did you still have this issue in the latest nightly?

I have not had the chance to test this on nightly but the 1.3.1 release still has the same behavior described in this issue. I will still need to try modifying NODE_OPTIONS to see if it resolves the issue...

**Comment by orcelik** [comment]
@saleung, I see this issue still persists in version 1.4.0. Do we have an expected time for resolution?

**Comment by saleung** [comment]
> @saleung, I see this issue still persists in version 1.4.0. Do we have an expected time for resolution?

Ditto
