### ISSUE TITLE
Problem with Publish

### ISSUE THREAD

**Issue by naicud** [microsoft/BotFramework-Composer#5658]
I have a problem with deploy my bot from composer V1.3.0:

Error:
![image](https://user-images.githubusercontent.com/55764723/106298162-db8a1780-6253-11eb-96cc-56f2ea2908de.png)

My publish profile:
![image](https://user-images.githubusercontent.com/55764723/106298479-3a4f9100-6254-11eb-9fe0-d658d47c8f01.png)

Can you help me ?? thanks :)

**Comment by anusharavindrar** [comment]
@naicud, can you elaborate more on how you generated the accessToken for the above step? Are you using the az cli?

**Comment by naicud** [comment]
> @naicud, can you elaborate more on how you generated the accessToken for the above step? Are you using the az cli?

Hi, I have used az cli to generate the token:
![image](https://user-images.githubusercontent.com/55764723/106571670-b89f8200-6537-11eb-8017-e3c5869c2781.png)

**Comment by anusharavindrar** [comment]
@naicud, have you tried generating a new access token and paste it to the publishing profile to see if you still get the same "accessToken is missing" error?
@luhan2017, any pointers on what might be causing the above error?

**Comment by luhan2017** [comment]
@naicud I saw you are using composer Electron app to deploy your bot. is there a login window pop up when you try to publish your bot? In composer 1.3.0, we switched from manually inputting token to azure login, we don't support manually paste your token in electron app now. 

If you still want to use az cli to get accesstoken, you can try to download composer code, and start the webapp.

**Comment by naicud** [comment]
@anusharavindrar :i have tried many times but i get the same error :(

@luhan2017: If I want publish the bot on existing azure resources with the option "Import existing Azure Resources" i must to import publish profile, so in this profile i need to generate accessToken with the cli command. The solution fordeploy on Existing Azure resources is use de webapp on visual studio ?

**Comment by compulim** [comment]
@luhan2017 Ping.

**Comment by luhan2017** [comment]
@naicud sorry for the late response, you don't need to generate accessToken in composer 1.3.0, composer will pop up a login window for you to login if you want to deploy your bot.  Could you try the following steps to get more information here? 

1. Open commnd line tool and Go to the composer exe folder, usually located here: 
C:\Users{YourUserName}\AppData\Local\Programs\Bot Framework Composer
2. run set debug=composer*
3. start Bot Framework Composer from the command line
4. try to deploy your bot to the current publish profile. 
5. Check the command line tool log, if you can see the token like the following, go to jwt.ms and decode the token, otherwise, please help paste the logs here.
![image](https://user-images.githubusercontent.com/32191031/108298322-b7c54c00-71d7-11eb-91a9-98c3b4d7140f.png)

**Comment by naicud** [comment]
@luhan2017 I have followed the steps but the debugger isn't started, and i have got the same error:
Commands:
![image](https://user-images.githubusercontent.com/55764723/108487118-2e794c80-729f-11eb-8cde-c0aefc89c0c3.png)
Result:
![image](https://user-images.githubusercontent.com/55764723/108487193-46e96700-729f-11eb-85c0-b02a384a2fd6.png)
Error:
![image](https://user-images.githubusercontent.com/55764723/108487320-6aacad00-729f-11eb-857b-4dea12461829.png)

So I have tried using localhost:5000 to run Composer into chrome web browser, now i get this other error :
![image](https://user-images.githubusercontent.com/55764723/108487913-10601c00-72a0-11eb-91d6-dd6d48419d62.png)

Logs:
---
"Accepted for publishing..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"Assigning to luis app id: 01e44ae4-8937-404f-adf8-dce940a6dc0a"
---

---
"{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\",\"error\":{\"error\":{\"message\":\"Failed to parse azure account information object object.\"}},\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\\n    at new i (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:110597)\\n    at F.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:109440)\\n    at F.e.callback.t.callback [as _callback] (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:108488)\\n    at F.t._callback.t.callback.t.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:4017)\\n    at F.emit (events.js:210:5)\\n    at F.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:16714)\\n    at F.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:15546)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
---

---
"{\"stack\":\"SyntaxError: Unexpected token o in JSON at position 1\\n    at JSON.parse (<anonymous>)\\n    at Object.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:115579)\\n    at C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:112703\\n    at Object.throw (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:112808)\\n    at s (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:111573)\",\"message\":\"Unexpected token o in JSON at position 1\"}"
---

---
"SyntaxError - Unexpected token o in JSON at position 1"
---

Decoded token:

This token was issued by Azure Active Directory.
Decoded Token
Claims
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "nOo3ZDrODXEK1jKWhXslHR_KXEg",
  "kid": "nOo3ZDrODXEK1jKWhXslHR_KXEg"
}.{
  "aud": "https://management.core.windows.net/",
  "iss": "https://sts.windows.net/cf36141c-ddd7-45a7-b073-111f66d0b30c/",
  "iat": 1613725859,
  "nbf": 1613725859,
  "exp": 1613729759,
  "acr": "1",
  "aio": "AUQAu/8TAAAAFXf5dg0f85O2SP5gYRN5E9s7IPF3k9hELK/kMrxkgAA1KjsL3UrW9pnUyEdXpMC0eMuv1rz7/Lei3iQTKM04Ew==",
  "amr": [
    "pwd",
    "wia",
    "mfa"
  ],
  "appid": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
  "appidacr": "0",
  "family_name": "Naicu",
  "given_name": "Daniel Nicusor",
  "groups": [
    "675a7a37-858b-4636-a4e7-79438cbaf2fd",
    "f39f3258-6d03-4ef2-ab9a-2fa5ffac8b4a",
    "9b82e309-22bc-4cba-b2b1-60adab285d61",
    "b8a79592-8247-43a7-891e-45ff66331090",
    "c8b56112-7b89-46bb-b7b9-65a9975e479d",
    "998514ec-e26b-4220-80b6-b49211f1e4d4",
    "6970c9ef-5507-43b4-99aa-79d8d8fa4276",
    "c6403ac6-4f4c-434c-baee-ca6777b304a6",
    "8816afc4-322d-468a-a110-52a799891f39",
    "24506a68-ce6c-49e1-8198-db5f8c575cd4",
    "a7ba9442-d893-45ea-889f-8592fdc9948a",
    "3702991c-4738-456f-beab-69901285f036",
    "7b177446-c4e7-4d52-8d1c-3dcb8c03e286",
    "5dd76468-a97f-4acc-9474-fbd2895edf9d",
    "ce5308eb-99ec-40dc-940c-5731a81906c6",
    "e9ff11c3-b08a-4863-842b-c693a7979109",
    "516481bd-1260-4dda-aef3-6ba6342fd8fe",
    "8767d67e-937a-4f1d-ab63-81de32767c37",
    "789dbe39-41dc-4b05-8fbd-8c2bfd6f97f0",
    "bc70ec69-5bf6-41c2-a32a-7e75bf4a16a6",
    "6fb75241-9e68-445c-96c9-4c02be7f4c0c",
    "222d8b1d-f560-4957-a98f-4ce61e5ce629",
    "5569b00f-e792-496f-9609-9fe98ff4ebbc",
    "e57f52f7-7b45-46e2-822a-b031ca912cdb",
    "a1217891-8f03-4eb6-999c-9a432277f1ec",
    "daf04184-fafc-4b8f-8b88-5254f4b3600f",
    "ec5e2be9-61af-4b97-82e5-adb3ef00571a",
    "25f6791d-51e3-49ea-9464-c5b5e8932b1f",
    "15a00261-f3f9-4793-b9f4-18053e6b6569",
    "fea996b8-18f4-418b-850c-3b239b5a672a",
    "65c05509-4703-4c5e-a350-55f84da216c9",
    "0a420a46-b8b9-43bf-b407-eaa4990d80fe",
    "e56d46e1-51be-4366-979f-926cd2977750",
    "afab9a59-28c7-40fc-84b9-4692dfc23757",
    "5f7b5585-ef42-439b-b11a-812a062a72bc",
    "5d930b67-3ffd-4141-a24a-36e7e7158b71",
    "856e3d36-44f3-4c85-9fc7-9647a2e36867",
    "a2cb89a9-d8ce-4035-822f-85720a987c07",
    "b638b7f7-c8b1-4c42-a0dc-c29c00cd8482",
    "147fc800-2fa3-4654-8aa4-f0b3fecd93e1",
    "d4f037c9-242c-40d0-a02a-a411284d4102",
    "c5abbf1c-8cc2-4214-b4a5-7677d097d7e1",
    "53c97924-e308-47f0-9b08-00be6d0f690b",
    "62c6a20b-7cdf-4b78-8522-befe4555b733",
    "4ae2eb36-e569-4ae1-82fd-01e0c6e63017",
    "191fb330-6ac2-49db-a47a-626cd3920e9b",
    "cea8bdae-3913-4cae-9b55-f43ef5b898c2",
    "efbb8076-53b5-48a0-97b2-d288ba368d17",
    "436a14c2-5acd-4a5c-8b06-2c18b9f4f4be",
    "cc578d5b-a7a0-4bc5-88f8-3e8605973311",
    "ab917c3e-ce15-4c12-a5dd-2a1816322c94",
    "e699e305-1ced-4e96-90bd-a687b87a2a61",
    "5ea34080-1261-4f38-a0c1-09c44cf1c553",
    "aa85b657-90bc-4923-a353-ebccf84b6b45",
    "58509615-e4de-4f3e-b1cc-afdcad01c8af",
    "8fc82bf3-6fbe-4f52-873a-94ed13c203c0"
  ],
  "ipaddr": "93.37.133.86",
  "name": "Daniel Nicusor Naicu",
  "oid": "5b296a5b-4442-4d75-a5a7-6db186dcad7a",
  "onprem_sid": "S-1-5-21-1482476501-2139871995-682003330-561361",
  "puid": "100320006765EB41",
  "rh": "0.ARsAHBQ2z9fdp0WwcxEfZtCzDJV3sATbjRpGu-4C-eG_e0YbACQ.",
  "scp": "user_impersonation",
  "sub": "b6HM6QAnT-bscJZltJ22O3dRozGHkzwF-asv3A1QqO8",
  "tid": "cf36141c-ddd7-45a7-b073-111f66d0b30c",
  "unique_name": "daniel.nicusor.naicu@avanade.com",
  "upn": "daniel.nicusor.naicu@avanade.com",
  "uti": "beG_9HljW0qEZcM4qK9UAA",
  "ver": "1.0",
  "wids": [
    "b79fbf4d-3ef9-4689-8143-76b194e85509"
  ],
  "xms_tcdt": 1298333596
}.[Signature]

**Comment by luhan2017** [comment]
@naicud , This error happens when we try to bind your published luis apps with luis prediction resource. Please follow this step to fix this issue https://github.com/microsoft/BotFramework-Composer/issues/5354#issuecomment-747150353

**Comment by naicud** [comment]
@luhan2017 Thanks so much for the assistence. You can close the Issue. :)
![image](https://user-images.githubusercontent.com/55764723/108831366-4f58df00-75ca-11eb-9965-b043212b0137.png)
