### ISSUE TITLE
AC input Form using BFC in PVA

### ISSUE THREAD

**Issue by MrFearLess98** [microsoft/BotFramework-Composer#5664]
Hello,

I have a PVA where the users are going to fill an input form that is sent from Bot Framework Composer. After they submit the form, I want to trigger a flow to get the values entered by the users and store them in my SharePoint List.

I am struggling with the following points using the bot framework composer:

1. How can I invoke the flow after the user pushes the submit button from the AC in the PVA? (It's invoking the flow without waiting for the user to fill the AC form)
2. After the user submits the AC form in the PVA, how can I update the AC and show a success message to avoid the user from filling in another form?
3. How can I pass the AC values coming from the form of the user in the body of the POST request in the composer?

I have found the below document but it's not similar to my scenario:
[BFA - Show an AC](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer#example-1--show-an-adaptive-card-in-power-virtual-agents)

Can someone please explain get back to me (in detail if possible please), and provide an example to achieve/solve the above mentioned?

Please find attached the AC form example and Bot Framework composer actions.
![Capture1](https://user-images.githubusercontent.com/52073639/106395594-ade7ce80-640b-11eb-9d52-8433d46e392b.PNG)
![Capture](https://user-images.githubusercontent.com/52073639/106395591-acb6a180-640b-11eb-8937-19f67f088fe1.PNG)

Any help will be highly appreciated.

Thank you!

**Comment by srinaath** [comment]
@cwhitten Can you take a look at this ticket?

**Comment by cwhitten** [comment]
Hi @MrFearLess98 and thanks for the question. This is possible by setting special properties in the adaptive card form that match with intent triggers in your bot. Please see this comment for an example: https://github.com/microsoft/BotFramework-Composer/issues/1820#issuecomment-571276631
