### ISSUE TITLE
Upgrade to WebSocket is required.

### ISSUE THREAD

**Issue by tiagonmas** [microsoft/BotFramework-Composer#5665]
## Describe the bug
Created a sample bot that works locally and then I deployed to newly crated resource. When browsing to the endpoint https://XXXXX.azurewebsites.net/api/messages e get   "Upgrade to WebSocket is required."

"Test in Web Chat" is also not working.

Similar issue to [this one.](https://social.msdn.microsoft.com/Forums/en-US/f8928490-254b-4190-a0e3-c1a8ade703c9/http-status-code-unauthorizced-on-bot?forum=AzureCognitiveService)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
Hi @tiagonmas Do you see any messages/issues/warnings in the WebChat channel health section (`../Microsoft.BotService/botServices/<yourbotname>/channels`)?

**Comment by Junenursyaiddah** [comment]
Hi , 

I'm using mac and have same issue when i start test demo - Bot Framework Composer
when i open http://localhost:3980/api/messages, showing this error,  " Upgrade to WebSocket is required. can you help me?

**Comment by tiagonmas** [comment]
Mine works fine locally. The issue is only when deployed to Azure. My current endpoint giving the error is https://tiagonmasbotalamo.azurewebsites.net/api/messages. 
Yes, the health section does show many warnings, as it cannot communicate with the API.
![image](https://user-images.githubusercontent.com/42462/106577895-d1f3fe80-6536-11eb-8121-4e6927a1e99c.png)

**Comment by dmvtech** [comment]
Hi @tiagonmas Is the application ID/password setup only in the appsettings.json or in the Web App configuration as well?

**Comment by tiagonmas** [comment]
(Documentation)[https://docs.microsoft.com/en-us/composer/how-to-publish-bot] does not state that I need to add the ID/password to anywhere. But I did add them to the settings page (copying them from the App Services configuration page), confirmed they were written to settings/appsettings.json file, and I republished the Bot. Now when I try the Web Chat I get a 502 error
![image](https://user-images.githubusercontent.com/42462/106645496-5620a300-6584-11eb-8c06-a63d29937b65.png)

**Comment by dmvtech** [comment]
> (Documentation)[https://docs.microsoft.com/en-us/composer/how-to-publish-bot] does not state that I need to add the ID/password to anywhere. But I did add them to the settings page (copying them from the App Services configuration page),

Yeah, you shouldn't have to. I was just checking/confirming. Thank you for trying that. 

Can you please try one thing as a test? Can you create a new client secret (no need to remove the old one) [for that AAD app](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade), then configure that in the App Service settings, then try the _Test in Web Chat_ again?

**Comment by tiagonmas** [comment]
Created second secret and updates the password in AppServices configuration.
Webchat still gives an error. Per F12 tools  "{error: {code: "BotError", message: "Failed to send activity: bot returned an error"},…}
error: {code: "BotError", message: "Failed to send activity: bot returned an error"}
httpStatusCode: 401"

**Comment by tiagonmas** [comment]
I understood why I was getting permission errors. The issue was that, for some reason, the Bot Channel Registration was pointing to a wrong Microsoft App Id. When I navigate to my Registration channel, and then settings, the "Microsoft App ID (manage)" setting was using a App Id that is not the same that was registered. Not sure how this happened in the first place.

As a workaround, I created a new Bot Channel Registration" that pointed at a new App Id, configured the App to use that ID and secret and things started to work!

**Comment by dmvtech** [comment]
Ok, thanks for the follow up. Yeah, that would do it 😂

That's really interesting though. If you are able to give specific steps on how to reproduce this issue (creating/provisioning with Composer, where it creates the wrong app registration), we would be interested in investigating further.

**Comment by tiagonmas** [comment]
Tomorrow I'll create a new profile and publish it again to see if I can repro.

**Comment by tiagonmas** [comment]
Just created a new Publishing profile, removed CosmosDB and QNA from the resources to be deployed, publish and it worked. not sure what happened before.

**Comment by dmvtech** [comment]
Gotcha. Ok, I'll go ahead and close. If it reoccurs or you are able to determine the exact steps, please comment or open a new bug. Thanks!
