### ISSUE TITLE
Can publishing only be done with non-live accounts?

### ISSUE THREAD

**Issue by irwinwilliams** [microsoft/BotFramework-Composer#5666]
## Describe the bug
I tried to publish using an outlook.com account that I used to sign up with for an Azure subscription and it seems to be that it won't let me proceed.
<img src="https://user-images.githubusercontent.com/1428703/106402697-19786e80-6401-11eb-93bb-df363f34b1cf.png" width="300"  />

## Version
               Bot Framework Composer

                Version:  1.3.0
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0
              

## Browser

- [ ] Electron distribution
- [*] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [* ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Publish'
2. Click on 'Manage Profiles'
3. Scroll down to 'Add new publish profile'
4. See error:
![image](https://user-images.githubusercontent.com/1428703/106402744-60666400-6401-11eb-976c-c36e00b0fa1a.png)

## Expected behavior

I should be able to use an actual Azure-based account to publish the bot

## Additional context

I went to the active directory, made a new user there and that worked.
![image](https://user-images.githubusercontent.com/1428703/106402796-b4714880-6401-11eb-991c-319319f4be93.png)

**Comment by dmvtech** [comment]
Yes. Please follow the issue here: https://github.com/microsoft/BotFramework-Composer/issues/5393

Fix is in progress and coming soon.
