### ISSUE TITLE
Impossible to publish to Power Virtual Agents

### ISSUE THREAD

**Issue by AlbertJDurango** [microsoft/BotFramework-Composer#5668]
## When I tried to add a  new profile for publishing to Power Virtual Agent nothing happens

Publishing to Power Virtual Agents doesn't work
## Version

![image](https://user-images.githubusercontent.com/16806741/106412392-adeccc00-6415-11eb-9f64-0e2a092d521f.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Project Settings
2. Click on Add new publish profile
3. Click on Next
4. Nothing happens. You will see only a text.

## Expected behavior

The system should be able to show the authentication screen

## Screenshots
1. Add a publish profile
![image](https://user-images.githubusercontent.com/16806741/106412179-138c8880-6415-11eb-9613-afdcf8afb128.png)

2.  Empty screen
![image](https://user-images.githubusercontent.com/16806741/106412272-5ea69b80-6415-11eb-8ea6-4ed6fa78efec.png)

3.Notes: I don't have problems publishing to Azure.

**Comment by cwhitten** [comment]
@AlbertJDurango can try opening Composer from Power Virtual Agents? This way you won't need to create a publishing profile manually. There is a button in their app that will launch Composer with the right information needed to publish back to PVA.

**Comment by AlbertJDurango** [comment]
I see. @cwhitten Thank you. I will test that.

**Comment by AlbertJDurango** [comment]
Hi  @cwhitten I tested it, But now I get another error from the composer when I tried to add a new trigger
![image](https://user-images.githubusercontent.com/16806741/106536220-fa8fe000-64c5-11eb-8b02-0d41b480b108.png)

**Comment by cwhitten** [comment]
Hi @AlbertJDurango. This is a known issue that we will be addressing in am upcoming release. The tracking issue is here: https://github.com/microsoft/BotFramework-Composer/issues/5728

Closing this as a dupe.
