### ISSUE TITLE
Webchat integration telemetry events

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#5676]
**User opens / closes the webchat pane**  
Suggested event name: WebChatPaneOpened / WebChatPaneClosed

**User clicks button to launch the emulator**  
Suggested event name: EmulatorButtonClicked. Note: This is an existing event that we use to track emulator launches from the 'Start all Bots' panel. Let's use the same event name, but add a property 'Location' set to 'WebChatPane'.

**User clicks button to restart conversation**  
Suggested event name: WebChatConversationRestarted  
Event properties to include: RestartType (either SameUserId or NewUserId)

**User opens / closes the drawer pane**  
Suggested event name: DrawerPaneOpened / DrawerPaneClosed

**User clicks into a tab within the drawer pane**  
Suggested event name: DrawerPaneTabOpened  
Event properties to include: Tab (e.g. errors / warnings etc.)

**Comment by srinaath** [comment]
@garypretty we need to add an event for Saving a transcript. I will go ahead and add an event `SaveTranscriptClicked`.
