### ISSUE TITLE
Design + Feature Request: Orchestrator package pane

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5678]
We need to start design thinking around how Orchestrator package (or language) pane should look like. For example, for Orchestrator we would need the following areas (not exhaustive):

* Configuration: select different base models, potential tuning parameters
* Specify LU test set for each Orchestrator LU
* Generate & view report for language recognition quality
* Apply correctiont o LU from within report experience (e.g. test sample is duplicated --> remove from intent label, or sample is misclassified --> add to target label

**Comment by mewa1024** [comment]
(@JaskeeratBedi-cmk fyi, although not sure if this is still up to date)
