### ISSUE TITLE
Composer nav + button discoverability

### ISSUE THREAD

**Issue by vivekkshankar** [microsoft/BotFramework-Composer#5680]
The + button in the composer nav is not discoverable and is creating friction while trying to add skills.
the create dialog and trigger icons in the three dot menu though contextual is hard to discover 

![image](https://user-images.githubusercontent.com/67671676/106655114-f4c9f580-65be-11eb-8f11-ac7792bce79b.png)

Suggested fix:

![image](https://user-images.githubusercontent.com/67671676/106655139-ff848a80-65be-11eb-8c5f-b504696addb3.png)

**Comment by vivekkshankar** [comment]
@liweitian https://www.figma.com/file/deFhMPBnRWxTYiYDYqYxrc/Composer-Vivek?node-id=10809%3A0

**Comment by mareekuh** [comment]
@vivekkshankar please move the '+ add' button out of the filter bar into the toolbar.

**Comment by mareekuh** [comment]
See above

**Comment by cwhitten** [comment]
@mareekuh this was implemented with the understanding that the design team had signed off on the change. Further updates to this will need to come in a future milestone. Removing from R12

**Comment by mareekuh** [comment]
Sounds like it slipped through the cracks. Please re-open.

**Comment by mareekuh** [comment]
@vivekkshankar  - what's the status on this?
Are we able to make updates?

**Comment by mewa1024** [comment]
No longer relevant.
