### ISSUE TITLE
 Nav overlaps with three dot menus - Critical create actions inaccessible 

### ISSUE THREAD

**Issue by vivekkshankar** [microsoft/BotFramework-Composer#5681]
![image](https://user-images.githubusercontent.com/67671676/106655306-2e026580-65bf-11eb-8a22-d818a92f8af7.png)
This is making critical action in inaccessible

Suggested fix - Increase padding from right side.

**Comment by boydc2014** [comment]
Per @srinaath suggestion, this should be a easy fix and we can take this into R12, @liweitian  can you follow up with Vivek for the accurate fix needed here.

**Comment by vivekkshankar** [comment]
@liweitian  https://www.figma.com/file/deFhMPBnRWxTYiYDYqYxrc/Composer-Vivek?node-id=10809%3A0
