### ISSUE TITLE
Document CMK usage in Composer

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#5682]
Document how CMK works from Composer.

**Comment by benbrown** [comment]
The ABS team has requested we consider this for R13 @garypretty

**Comment by garypretty** [comment]
@Dewain27 This is something we would need to hand as part of the provisioning process. Adding this would bring us in line with the resources created from an ABS handoff scenario, so ideally we should aim to do this in R13.

**Comment by cwhitten** [comment]
Adding @GeoffCoxMSFT as FYI

**Comment by benbrown** [comment]
@garypretty and @Dewain27  - we need to get more detailed requirements on this if we want to do it in r14

**Comment by benbrown** [comment]
Further details from call on June 8 with @RustyDes  @GeoffCoxMSFT  @Dewain27 @emivers8:

When creating an ABS bot (during provision), we would want to ask a user if they want to use CMK or not.

If YES, user has to specify a keyvault, key name and version.  This can be done by pasting in a keyvault URL.  In Azure, you can also select or create a keyvault (or paste a URL), select or create a key from that keyvault.   After this happens, those parameters would be passed into the call to create the ABS bot registration to enable CMK.

Composer does NOT need to store the keyvault value. It can be retrieved from Azure as necessary.

Do we also also need some UX to change these settings post-creation? We don't think this is required right now - this setting can be updated in the Azure portal. It *is* possible to update these post-creation in the portal and via the API.

There are some users whose tenant policy will REJECT new bot registrations if the CMK is *not* enabled, so we need to capture that error and make sure the user is directed to enable CMK.

**Comment by clearab** [comment]
@benbrown I'm assuming this is not getting done in R14, so I added it to the R15 milestone - does that align with your expectations?

**Comment by elliottperry** [comment]
The ask here is to have additional to help-articles to explain when user encounters problems due to CMK when publishing from Composer. 

Elliott & Rusty to help here. Elliott to set up a meeting to progress.
