### ISSUE TITLE
Add configuration to disable cross-training

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5684]
For some (cross-domain) scenarios cross-training isn't as beneficial and may not worth the added complexity.

Request: Have a configuraiton flag to disable cross trainig.

**Comment by cwhitten** [comment]
We'll seek to add this in R13

**Comment by scheyal** [comment]
Is this still on schedule?

**Comment by cwhitten** [comment]
@scheyal we don't have designs for this, and should before implementing. Taking out of R13 but we can continue discussing.

**Comment by sangwoohaan** [comment]
@vivekkshankar could you take a look at this?

**Comment by boydc2014** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/6549 gives the capability to control cross-train via config. 

I'm not sure we even need UX change here. 

What do you guys think? @sangwoohaan  @cwhitten

**Comment by mewa1024** [comment]
@boydc2014 is this issue still relevant? Do we need UX in the Configure page (or elsewhere) to reflect the change in #6549?
