### ISSUE TITLE
starting conversession from chat history : for multiple dialog scenario

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#5687]
Hi,
This is related to below issue
https://github.com/microsoft/BotFramework-Composer/issues/5574

We have applied the steps as mentioned in the above issue. But now we have added more dialogs to the bot and there are 3 multiple choice prompt separately in three different dialogs we have attached corresponding zip folder of the sample bot for reference.

As in the sample bot, dialog with name 'options'  is being called in greeting trigger. Similarly  dialog with name 'options'  is calling dialog 'options2' and 'options2' is calling 'option3'.

After running the bot:
Until dialog 'options' is executed completely till the end, user can't go back in the history and access the content from those points of the dialog again based on the button selected in the history.
Before completing the 'options' dialog till the end, if user goes back in the history and tries to access the content by clicking any of the multiple choice button, corresponding flow/dialog is not getting called. This scenario works only if user executes the 'options' dialog till the end and then goes back in the chat history.

Please find below screenshot for reference.

![image](https://user-images.githubusercontent.com/70739031/106741329-88dca100-6641-11eb-82a0-d01fc9ee6a5e.png)

After starting the bot in the emulator:

![image](https://user-images.githubusercontent.com/70739031/106741532-d0fbc380-6641-11eb-82f0-eb44e0bdc686.png)

![image](https://user-images.githubusercontent.com/70739031/106741610-eec92880-6641-11eb-9a15-bee3fa402026.png)

Now if we go back in the chat history and click on button flow2, corresponding dialog is not getting started.

![image](https://user-images.githubusercontent.com/70739031/106741804-3485f100-6642-11eb-9a83-ec8e3d2df259.png)

![image](https://user-images.githubusercontent.com/70739031/106741934-5ed7ae80-6642-11eb-8e30-b91e7549bad0.png)

Now if we go back in the chat history and click on button flow5, corresponding dialog is not getting started.

![image](https://user-images.githubusercontent.com/70739031/106742084-8a5a9900-6642-11eb-865b-972bcad7c28f.png)

Now 'options' dialog  is executed completely till the end. Now if we go back in the chat history and click any button corresponding flow will start.

![image](https://user-images.githubusercontent.com/70739031/106742317-e6252200-6642-11eb-9b0f-da78a8d3457b.png)

But the thing is that before completing the 'options' dialog till the end, if user goes back in the history and tries to access the content by clicking any of the multiple choice button, corresponding flow/dialog is not getting called.
Is there any way 
[Testbot1.zip](https://github.com/microsoft/BotFramework-Composer/files/5918149/Testbot1.zip)
to resolve above issue.

Thanks..

**Comment by dmvtech** [comment]
Hi @BeheraMadan I am taking a look. I'll let you know if I have any questions or information to share.

**Comment by BeheraMadan** [comment]
Do we have any update?

Thanks.....

**Comment by ismendes** [comment]
Just came here to share this extra piece of information:
This issue is related to one of the biggest complaints we've heard from many users in UX research performed for the Partner Bot. :) 
All help is very appreciated, thanks!

**Comment by BeheraMadan** [comment]
Do we have any update on above issue?

Thanks.....

**Comment by dmvtech** [comment]
Hi @BeheraMadan Sincerest apologies for the delay. Thank you for posting your bot, that helped.

The issue here is that the prompts are not to allow to accept interruptions. So, once a prompt gets sent (for example your `xZ6Zkd` ChoiceInput), then it will not allow anything but a selection from those options. It will continue to prompt for valid responses until the max turn (3 in your case). You have options like Unrecognized Prompt to give some insight to yourself or users. If you do want the prompt to be interrupted, then you need to set allow interruptions to be set to true.


When I set it to true for your bot, I then get the following:
![image](https://user-images.githubusercontent.com/43397658/109049176-cbb3f680-768c-11eb-9685-3e2f7503267f.png)

Now, the _prompting_ for the first choice set is happening again (flow1, flow2, flow3) in it's entirety. This is because the properties are set to **dialog** [scoped properties.](https://docs.microsoft.com/en-us/composer/concept-memory) Dialog properties should be set for the scope of the dialog, then either populated into other properties (`user.` or `conversation.`) or otherwise converted/used. This should be used in consideration with the 'always prompt' option as well. 

I hope that makes sense. Please let me know if I can further clarify or answer anything else.

**Comment by dmvtech** [comment]
@ismendes Let me know if that addresses your concerns as well. If designed in the right way, interruptions and letting users go back and change answers should be possible.

**Comment by BeheraMadan** [comment]
Hi,

Thank you for providing the solution. We will try the solution in our bot and let you know shortly.


Thanks...

**Comment by ismendes** [comment]
@dmvtech, this is great, thanks for the support. I am trying to understand how to correct the technical gap from my team. 
For me this statement _"If designed in the right way, interruptions and letting users go back and change answers should be possible"_ makes a lot of sense, but I am not clear about which docs they need to understand to get this done in the right way without increasing the number of opened issues here. Any insights on this would be appreciated.

**Comment by BeheraMadan** [comment]
@ismendes you are absolutely correct . @dmvtech Would you please provide more detailed steps for the solution you mentioned. As per our understanding we tried to implement the solution in our sample test bot but it is not working as expected. For us , the prompting for the first choice set is happening again (flow1, flow2, flow3)  repeatedly in it's entirety. We tried to change the value of always prompt property as well along with 'allow interruption property' but output is not as expected. Also it would be helpful if you could provide zip file of the bot with solution applied.

Thanks..

**Comment by cwhitten** [comment]
@BeheraMadan are you still seeking assistance on this?

**Comment by BeheraMadan** [comment]
Yes I need assistance........

**Comment by ismendes** [comment]
@cwhitten, what would you recommend as next steps from my team to help you to help us to fix this issue?
According to @dmvtech, 
_If designed in the right way, interruptions and letting users go back and change answers should be possible._

Do you have docs, or an example to point where they can check the correct technical design?

Thanks!

**Comment by ismendes** [comment]
@BeheraMadan, can you provide screenshots of the current technical design?

**Comment by BeheraMadan** [comment]
Hi,
Would you please provide more detailed steps for the solution you mentioned. As per our understanding we tried to implement the solution in our sample test bot but it is not working as expected. For us , the prompting for the first choice set is happening again (flow1, flow2, flow3) repeatedly in it's entirety. We tried to change the value of always prompt property as well along with 'allow interruption property' but output is not as expected. 

Please find attached sample bot with our current technical design in which we tried to implement the solution you mentioned.
Also it would be helpful if you could provide zip file of the bot with solution applied.

Thanks....
[BotSample.zip](https://github.com/microsoft/BotFramework-Composer/files/6188415/BotSample.zip)

**Comment by peterinnesmsft** [comment]
@BeheraMadan, as there isn't an active issue beyond just seeking general guidance, we are going to close this issue. For general purpose questions seeking guidance on this issue, we recommend you visit our StackOverflow: https://stackoverflow.com/search?q=bot+framework

If you have any further concerns or questions, let us know. Thank you!
