### ISSUE TITLE
"Add a trigger" UI is missing trigger types "OnAssignEntity", OnChooseProperty", "OnChooseEntity"

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5691]
## Describe the bug

The form dialogs feature creates a dialog for the user with one button press. The resulting dialog uses 3 trigger types that are not yet in the "Add a trigger" menu. Although this isn't preventing users from using the dialog, it does prevent them from adding new triggers of those types. The types are "OnAssignEntity", OnChooseProperty", and "OnChooseEntity".

## Version

1.3.1-nightluy-208618.73c0bce

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot.
2. From a dialog, select the vertical 3-dot menu, and select "Add a trigger"
3. The "Create a trigger" modal appears.
4. There is no menu item for ""OnAssignEntity", OnChooseProperty", "OnChooseEntity".

## Expected behavior

The trigger types should appear in the "Dialog events" grouping.

![image](https://user-images.githubusercontent.com/39317542/106813826-5ec9b580-6626-11eb-9ce6-54113221593c.png)

To match the pattern of friendly name followed by SDK name in parenthesis, can we they appear with this text?
- Entity assigned (Assign entity event)
- Duplicated entities recognized (Choose entity event)
- Duplicated properties recognized (Choose property event)

## Additional context

This is how the triggers appear in Composer if they have been included in a dialog.

**Comment by cwhitten** [comment]
We'll add these in a future release as part of the Trigger Wizard UI update

**Comment by mewa1024** [comment]
sounds good. (@vivekkshankar fyi)
