### ISSUE TITLE
is there anyway for me to embedded my python(or js) code logic with composer?

### ISSUE THREAD

**Issue by mxmore** [microsoft/BotFramework-Composer#5694]
I just ask the question that if in future, I would like make some personal bot code logic into the bot that I published by composer. Is there any way to do that.

**Comment by cwhitten** [comment]
hello @mxmore and thanks for your question. support for Node.js/JavaScript is in preview, where you can test this today by creating a bot project and ejecting your runtime and selecting JS as a target language. You can then customize this runtime by adding additional JS where necessary. It is preview though and is subject to change. 

For Python support, this is on the backlog and being considered in a future release. No preview or GA date at this time. Please add your request to https://github.com/microsoft/BotFramework-Composer/issues/1993 to support this.
