### ISSUE TITLE
"insert template" for default send response action will mess up the format

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#5701]
- add "send response"
- click "insert template" button 
- hit following error. 
![image](https://user-images.githubusercontent.com/43408889/107006591-5317f380-67cc-11eb-8c87-7051ae899623.png)
The default "send response" action starting with "-", so the insert the template need to take care this as well.

**Comment by hatpick** [comment]
Insert template (same for variables and built in functions) will insert the text for the selected item at the current cursor position of the monaco editor. From your steps to repro, it seems like you did not select any specific position by clicking, so it will insert the selected item at the default position (which is first line, first character)
