### ISSUE TITLE
QnAMaker trace/call shows up in log after intent was recognized correctly.

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5705]
Setup a bot with Orchestrator recoginzer (could be LUIS) and QnAMaker. Notice how QnAMaker trace shows up after intent was correctly recognized. See images:

![but1](https://user-images.githubusercontent.com/8867670/107103013-04208d00-67d1-11eb-8c35-ff867b73b167.png)

![bug2](https://user-images.githubusercontent.com/8867670/107103021-084caa80-67d1-11eb-9e8b-0ee55eb3aefd.png)

**Comment by cwhitten** [comment]
@scheyal do you have a question about this? the behavior seems correct.
