### ISSUE TITLE
Improve the bot loading performance

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#5708]
## Describe the bug

Composer is taking too much time to load a big bot. For example, in Calendar bot, it's taking up to 30-60s to see the first screen.

## Version

Lastest main

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. open a big bot
2. wait the design page to show up

## Expected behavior

Expect the first screen will show up very soon, within a few second, even the bot is considered as big. 

## Additional context

We had a proposal for hot/cold splitting which we can leverage the idea to break down the processing when loading.

**Comment by hibrenda** [comment]
addressed in #5853
