### ISSUE TITLE
Publishing while new (to Azure)

### ISSUE THREAD

**Issue by irwinwilliams** [microsoft/BotFramework-Composer#5709]
## Describe the bug
When publishing to a newly minted Azure subscription, the user may run into scenarios that seem related to first-time user of various Azure services

## Version
                Bot Framework Composer

                Version:  1.3.0
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0
              
## Browser

- [ ] Electron distribution
- [* ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ *] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Azure subscription
2. [Never user it for anything else in the portal, save a Cognitive services resource for LUIS]
3. Go to 'Publish'
4. Create a new publish profile
5. Sign in
6. Attempt to publish

## Expected behavior

Bot and associated resources get created in Azure

## Screenshots
"The subscription is not registered to use namespace 'Microsoft.Web'"
![image](https://user-images.githubusercontent.com/1428703/107137789-530c1680-68e6-11eb-9e43-c3b6d8f7a70f.png)

Workaround: 

Execute: **az provider register --namespace Microsoft.Web** in cloud shell 

"The subscription is not registered to user namespace 'Microsoft.BotService"
![image](https://user-images.githubusercontent.com/1428703/107137850-c6ae2380-68e6-11eb-9e55-dc561850366d.png)

Workaround:

Execute: **az provider register --namespace Microsoft.BotService** in cloud shell 

"The subscription is not registered to user namespace 'Microsoft.DocumentDB"
![image](https://user-images.githubusercontent.com/1428703/107137862-e2192e80-68e6-11eb-82ba-38c7867caeae.png)

Execute: **az provider register --namespace Microsoft.DocumentDB** in cloud shell 

"The subscription is not registered to user namespace 'Microsoft.Insights"
![image](https://user-images.githubusercontent.com/1428703/107137881-037a1a80-68e7-11eb-88d2-e80c118c2a37.png)

Execute: **az provider register --namespace Microsoft.Insights** in cloud shell 

"The subscription is not registered to user namespace 'Microsoft.Search"
![image](https://user-images.githubusercontent.com/1428703/107137893-1bea3500-68e7-11eb-9a4a-372e2c252ace.png)

Execute: **az provider register --namespace Microsoft.Search** in cloud shell 

## Additional context

Having run all the service registrations manually, the bot was successfully published.

**Comment by Virtual-Josh** [comment]
@dmvtech Can you help the customer here?

**Comment by dmvtech** [comment]
hi @irwinwilliams I am attempting to reproduce this. Thank you for sharing, I'll let you know if I have any questions.

**Comment by dmvtech** [comment]
I was able to reproduce this. 

Interestingly, after getting the failure in Composer, I tried creating a simple `Web App Bot` in the portal, and got the following:
![image](https://user-images.githubusercontent.com/43397658/108436296-fec73780-71ff-11eb-84d8-3c82b90c8dc0.png)

I then created a basic Web App (not a bot) in the Azure portal. That was successful. Then I was able to finish/continue creating the `Web App Bot` in the portal. 

After doing that, I re-ran the publish and then failed on DocumentDB and Search. After creating those in the portal (which obviously sets up the providers), then I could publish.

@cwhitten I can share more thoughts/findings with you and the team.

**Comment by cwhitten** [comment]
Let's look to address in R13.

Questions to understand, and we need to connect with ABS to understand:

1. Why are these registrations not happening at the outset?
2. Can we do this registration for users on their behalf without introducing unnecessary side-affects
3. Are the operations idempotent? Will we need to infer the need to do this registration? Do we have the heuristic to do the correct inference?

**Comment by Dewain27** [comment]
To be resolved with #7257
