### ISSUE TITLE
Css error when clicking node in visual editor

### ISSUE THREAD

**Issue by alanlong9278** [microsoft/BotFramework-Composer#5712]
## Describe the bug

Click node in visual ediotr, the node border css is wrong.
![image](https://user-images.githubusercontent.com/5860999/107143563-b80c4e80-6970-11eb-82f5-b416fee019ee.png)

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cosmicshuai** [comment]
verified
