### ISSUE TITLE
Transcript Storage Retention Policy

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#5719]
As the native pipeline is being built / designed for Composer, I though I ask for the implementation purging of Transcripts from Storage. As I have noticed the size of Storage can skyrocket with a bot with some decent usage.

I wanted to double check if this is being considered / will be considered as otherwise I will built it myself in our current pipelines. I would imagine a settings in days that gets picked up by the publisher / pipeline and will create a retention policy for the transcript container so anything older than the # of days gets purged by Storage itself.

**Comment by cwhitten** [comment]
@cxbuilders at the moment we don't have the ability to configure retention policies for your transcript storage. Are you using CosmosDB to store transcripts? You may need to go into the DB configuration to set retention policies on the transcript collections.

**Comment by cxbuilders** [comment]
@cwhitten No just the storage for transcript. Using the retention policies in Blob Storage. Thought to put it out there as a feauture request to be part of the pipeline. Will build it myself now in our current pipeline.

**Comment by congysu** [comment]
@garypretty could you please take a look at this ask from our customer?  Thanks.

**Comment by garypretty** [comment]
Hi @cxbuilders. Right now we have no plans to implement anything surrounding this.  If we were to, it would be something we would need to implement at the SDK level and out policy there right now is to have users configure additional settings on the related services, such as retention policies, themselves. These sort of settings will obviously vary from customer to customer and you say you are able to implement something aligned with your needs here.  Closing this issue for now, but will keep this in mind if we receive any further signals. Thanks for the feature request.
