### ISSUE TITLE
QnA editor flow is broken-can't edit extracted pairs

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#5723]
## Describe the bug
When I create a KB which is built from a url source I can't edit any of QnA Pairs.

## Version
![image](https://user-images.githubusercontent.com/17789481/107256028-cfd5e800-69ed-11eb-86ac-fe999a8c135f.png)

## Browser
- [x] Electron distribution

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create dialog
2. Create KB pointing it to a source  (I used https://support.keurig.com/k_cup_brewers)
3. there are no pairs show in the UI.
4. When I go to code all I see is 
```
[import](KeurigSkill-manual.source.qna)
``` 
but I can't edit it.

## Expected behavior

* When I import, I should see all of the qna pairs in the .qna file, not in a seperate file which I can't see or edit.
* When I edit qna it should get saved to the .qna file, not in a seperate file which I can't see or edit
* There should be a refresh button which runs import again and *merges* content with my content.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/107259564-fdbd2b80-69f1-11eb-9200-64bfb3bb578a.png)
Why do I only see an import, and not the qna pairs?

**Comment by cwhitten** [comment]
@vivekkshankar can you comment on the current or planned design for this? "Show code" at the top level to expose the source import doesn't give a lot of utility to the user.
