### ISSUE TITLE
Composer keeps adding WelcomeUser LG template even though I have one in my common.lg file.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#5724]
## Describe the bug

I have a WelcomeUser in common.lg, when I load my project I get an error because it keeps adding one in the root dialog en-us.lg file

## Version

![image](https://user-images.githubusercontent.com/17789481/107265239-e0d82680-69f8-11eb-9956-5bbc562b527c.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Add WelcomeUser to common.lg
2. Edit dialog, it modifies to add empty WelcomeUser.

## Expected behavior
Dont' auto add templates that are defined.

**Comment by cwhitten** [comment]
@zhixzhan could this have been a side-affect of https://github.com/microsoft/BotFramework-Composer/commit/4de92c4a77c12cd390aa841967a3b03e03ccc7c9 ?

**Comment by srinaath** [comment]
@tomlm Im not able to recreate this ticket. Essentially,

1.  I created an echo bot. It by default has a WelcomeUser template in the common.lg
2.  I created a new dialog and added a sendResponse action referring to the Welcome template
3.  I checked the lg file for both the root dialog and this new dialog. They both continue to refer to the welcome lg template from common and dont have a duplicate empty Welcome template inside them

Could you check if you are able to see this error on latest nightly.

**Comment by zhixzhan** [comment]
> @zhixzhan could this have been a side-affect of [4de92c4](https://github.com/microsoft/BotFramework-Composer/commit/4de92c4a77c12cd390aa841967a3b03e03ccc7c9) ?

@cwhitten @srinaath Yes this is a bug introduced in #5654 
without considering dialog may could directly use templates in imported lg files. Fixed in #5823

**Comment by cosmicshuai** [comment]
Verified
