### ISSUE TITLE
Clicking on root dialog across/bot skill loads the root dialog for active project, not the clicked on one

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#5727]
## Describe the bug

When I have a bot and a skill loaded.
```
Bot
    bot.dialog
Skill
    skill.dialog
```
When click on skill.dialog, and click on bot.dialog, it flashes, and stays on skill.dialog.

## Version
![image](https://user-images.githubusercontent.com/17789481/107291958-e005bb80-6a1d-11eb-9548-67ca1ba186e5.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. load project with bot and skill.
2. Click on any dialog for the skill
3. click on any dialog for the bot
The root dialog for the skill will be selected, not the dialog you click on in #3.

## Expected behavior

To show the dialog I click on.

**Comment by cosmicshuai** [comment]
verified
