### ISSUE TITLE
Update bf-lu package version to resolve the app settings missing issue

### ISSUE THREAD

**Issue by feich-ms** [microsoft/BotFramework-Composer#5732]
## Describe the bug

Current bf-lu has a bug that app settings defined in lu files may be lost when doing luis publishing. There was a fix in bf-cli side https://github.com/microsoft/botframework-cli/pull/1108 to resolve the issue. Composer need to upgrade the bf-lu version to overcome this issue.

## Version

Latest main

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Add a lu file and add app settings in the header and then import another lu file
2. Publish this lu file
3. You will see app settings didn't take effect in luis portal

## Expected behavior

App settings should work for luis publishing

**Comment by cosmicshuai** [comment]
verified
