### ISSUE TITLE
Publishing Error : SyntaxError - Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by LakshmanRaja209** [microsoft/BotFramework-Composer#5735]
## Describe the bug
In Bot Composer we are trying to deploy the Bot with Luis Configuration getting the below error 

"SyntaxError - Unexpected token o in JSON at position 1"
"Assigning to luis app id: 14f20582-85fe-4d5b-8823-25e016ce719e"
---

---
"{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\",\"error\":{\"error\":{\"message\":\"Failed to parse azure account information object object.\"}},\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\\n    at new i (C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:488:110568)\\n    at F.callback (C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:488:109411)\\n    at F.e.callback.t.callback [as _callback] (C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:488:108459)\\n    at F.t._callback.t.callback.t.callback (C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:518:4015)\\n    at F.emit (events.js:210:5)\\n    at F.<anonymous> (C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:518:16712)\\n    at F.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:518:15544)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
---

1. Resources was chosen existing one in Azure resides in same region.
2. Other issue is I am not able to choose the different subscriptions in Bot Composer
3. Same Settings with Echo bot was able to deploy and run
4. with Luis settings in Bot Composer we are able to run in locally but while deploying in to Azure finding difficulties.
We are already opened an Microsoft ticket but still no resolution for us .

Resources used to in the Project :
Luis Prediction and Authoring
QnAMaker
Web App Bot
App Insight
 
## Version
Bot Composer 1.3.0

## Browser

- [ ] Electron distribution
- [ x] Chrome
- [ ] Safari
- [ ] Firefox
- [x ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Bot Composer'
2. Create a Bot with Luis settings
3. Settings and Add the Publishing Profile -> Login to Azure -> Choose existing resources -> Add required keys and details
4. Go to Publishing -> Choose Profile -> Publish

## Additional context

Added publishing profile and detail log

details log 
---
"Accepted for publishing..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"Assigning to luis app id: 14f20582-85fe-4d5b-8823-25e016ce719e"
---

---
"{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\",\"error\":{\"error\":{\"message\":\"Failed to parse azure account information object object.\"}},\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\\n    at new i (C:\\\\Users\\\\DemoUser\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:488:110568)\\n    at F.callback (C:\\\\Users\\\\DemoUser\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:488:109411)\\n    at F.e.callback.t.callback [as _callback] (C:\\\\Users\\\\DemoUser\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:488:108459)\\n    at F.t._callback.t.callback.t.callback (C:\\\\Users\\\\DemoUser\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:518:4015)\\n    at F.emit (events.js:210:5)\\n    at F.<anonymous> (C:\\\\Users\\\\DemoUser\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:518:16712)\\n    at F.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Users\\\\DemoUser\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:518:15544)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
---

---
"{\"stack\":\"SyntaxError: Unexpected token o in JSON at position 1\\n    at JSON.parse (<anonymous>)\\n    at Object.<anonymous> (C:\\\\Users\\\\DemoUser\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:542:114757)\\n    at C:\\\\Users\\\\DemoUser\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:542:111883\\n    at Object.throw (C:\\\\Users\\\\DemoUser\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:542:111988)\\n    at s (C:\\\\Users\\\\DemoUser\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:542:110753)\",\"message\":\"Unexpected token o in JSON at position 1\"}"
---

---
"SyntaxError - Unexpected token o in JSON at position 1"
---

Profile Details

```json
{
  "name": "botcomposer130-dev",
  "environment": "dev",
  "runtimeIdentifier": "win-x64",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": ""
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "<endpoint url>",
      "authKey": "<auth key>",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "<connection string>",
      "container": "<container>"
    },
    "luis": {
      "authoringKey": "",
      "authoringEndpoint": "",
      "endpointKey": "",
      "endpoint": "",
      "region": "westeurope"
    },
    "MicrosoftAppId": "",
    "MicrosoftAppPassword": ""
  },
  "hostname": "botcomposer130-dev",
  "luisResource": "BotComposer130-dev-Luis"
}
```

**Comment by Virtual-Josh** [comment]
Hey @anusharavindrar can you take a look at this ticket?

**Comment by anusharavindrar** [comment]
@LakshmanRaja209, are you using a work/school account or a personal account? This looks similar to the issues #5344 and #5354. Is your luis resource provisioned through composer? Also, is the luisResource in your publish profile pointing to your luis prediction resource? Please refer to the details [here](https://github.com/microsoft/BotFramework-Composer/issues/5354#issuecomment-747150353).

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to re-open if issue persists.

**Comment by Jenny0932** [comment]
Hi, same issuer here. Is that the error with LUIS server?
View using the debugger view:
    at onRender (http://localhost:5000/static/js/15.e90e2d8f.chunk.js:1:36028)
S @ moment.js:270
:5000/api/publish/32003.495850502793/status/default:1 Failed to load resource: the server responded with a status of 404 (Not Found)
warn.js:13 The Button component has been deprecated. Use specific variants instead. (PrimaryButton, DefaultButton, IconButton, ActionButton, etc.)
r @ warn.js:13
:5000/api/publish/9119.689373010975/status/default:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:5000/api/publish/9119.689373010975/status/Nwow:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:5000/api/publish/9119.689373010975/status/Nwow:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:5000/api/publish/32003.495850502793/status/default:1 Failed to load resource: the server responded with a status of 404 (Not Found)
warn.js:13 The Button component has been deprecated. Use specific variants instead. (PrimaryButton, DefaultButton, IconButton, ActionButton, etc.)
r @ warn.js:13
:5000/api/publish/32003.495850502793/status/Nwow:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:5000/api/publish/32003.495850502793/status/Nwow:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by danielallen73** [comment]
Also logged on #5354 

I am reporting the same issue. Have followed all of the advice in all the threads. I'm on 1.3.1. Was working the other day after working around it, now I can get past the dreaded "SyntaxError - Unexpected token o in JSON at position 1"

All resources created in westus.
Using a work account.

Publish Profile as follows:
{
"name": "REDACTED",
"environment": "dev",
"runtimeIdentifier": "win-x64",
"settings": {
"applicationInsights": {
"InstrumentationKey": "REDACTED"
},
"cosmosDb": {
"cosmosDBEndpoint": "REDACTED",
"authKey": "REDACTED",
"databaseId": "botstate-db",
"containerId": "botstate-container",
"collectionId": "botstate-collection"
},
"blobStorage": {
"connectionString": "REDACTED",
"container": "transcripts"
},
"luis": {
"authoringKey": "REDACTED",
"authoringEndpoint": "https://westus.api.cognitive.microsoft.com/",
"endpointKey": "REDACTED",
"endpoint": "https://westus.api.cognitive.microsoft.com/",
"region": "westus"
},
"MicrosoftAppId": "REDACTED",
"MicrosoftAppPassword": "REDACTED",
"qna": {
"endpoint": "https://REDACTED-qnahost.azurewebsites.net",
"subscriptionKey": "REDACTED"
}
},
"accessToken": "REDACTED",
"hostname": "REDACTED",
"luisResource": "REDACTED"
}

Debug...
2021-03-05T01:19:07.665Z composer:extensions:azurePublish { status: 'DEPLOY_INFO', message: 'Build succeeded!' }
2021-03-05T01:19:07.704Z composer:extensions:azurePublish { status: 'DEPLOY_INFO', message: 'start publish luis' }
2021-03-05T01:19:09.041Z composer:extensions:azurePublish {
status: 'DEPLOY_INFO',
message: 'Assigning to luis app id: a3171f17-a364-4e5a-b7b9-9d9809d0519f'
}
2021-03-05T01:19:10.473Z composer:extensions:azurePublish {
status: 'LUIS_PUBLISH_ERROR',
message: '{"name":"StatusCodeError","statusCode":400,"message":"400 - {\"error\":{\"code\":\"BadArgument\",\"message\":\"Failed to parse azure account information object object.\"}}","error":{"error":{"message":"Failed to parse azure account information object object."}},"options":{},"response":{"statusCode":400},"stack":"StatusCodeError: 400 - {\"error\":{\"code\":\"BadArgument\",\"message\":\"Failed to parse azure account information object object.\"}}\n at new i (C:\\Users\\dtall\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\lib\\node\\index.js:338:110597)\n at F.callback (C:\\Users\\dtall\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\lib\\node\\index.js:338:109440)\n at F.e.callback.t.callback [as _callback] (C:\\Users\\dtall\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\lib\\node\\index.js:338:108488)\n at F.t._callback.t.callback.t.callback (C:\\Users\\dtall\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\lib\\node\\index.js:368:4017)\n at F.emit (events.js:210:5)\n at F. (C:\\Users\\dtall\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\lib\\node\\index.js:368:16714)\n at F.emit (events.js:210:5)\n at IncomingMessage. (C:\\Users\\dtall\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\lib\\node\\index.js:368:15546)\n at Object.onceWrapper (events.js:299:28)\n at IncomingMessage.emit (events.js:215:7)\n at endReadableNT (_stream_readable.js:1183:12)\n at processTicksAndRejections (internal/process/task_queues.js:80:21)"}'
}
2021-03-05T01:19:11.684Z composer:extensions:azurePublish {
status: 'DEPLOY_ERROR',
message: '{"stack":"SyntaxError: Unexpected token o in JSON at position 1\n at JSON.parse ()\n at Object. (C:\\Users\\dtall\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\lib\\node\\index.js:392:115579)\n at C:\\Users\\dtall\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\lib\\node\\index.js:392:112703\n at Object.throw (C:\\Users\\dtall\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\lib\\node\\index.js:392:112808)\n at s (C:\\Users\\dtall\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\lib\\node\\index.js:392:111573)","message":"Unexpected token o in JSON at position 1"}'
}
2021-03-05T01:19:11.687Z composer:extensions:azurePublish SyntaxError: Unexpected token o in JSON at position 1
at JSON.parse ()
at Object. (C:\Users\dtall\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\lib\node\index.js:392:115579)
at C:\Users\dtall\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\lib\node\index.js:392:112703
at Object.throw (C:\Users\dtall\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\lib\node\index.js:392:112808)
at s (C:\Users\dtall\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\lib\node\index.js:392:111573)
2021-03-05T01:19:12.863Z composer:bot-project No schemas directory found.
GET /api/publish/56237.44182596713/status/Test4 500 1794.387 ms - -

**Comment by kcsureshgowda** [comment]
I think, this is the known open issue in Composer version 1.3 & 1.3.1.  One of our initially asked to use the composer. However, after this issue with latest version 1.3 & 1.3.1, customer strongly comeback & asked not to use the composer anymore. Not satisfactory response from Microsoft on this issue.

**Comment by humak** [comment]
Experiencing the same issue while trying to publish:  SyntaxError: Unexpected token u in JSON at position 0
It fails at LUIS state. 
I filled every place in Publish Profile:
![image](https://user-images.githubusercontent.com/14835957/129838310-98ee96a3-c732-4f72-a3b0-16e71f808bf9.png)

![image](https://user-images.githubusercontent.com/14835957/129838525-98c38316-8ccf-45ac-b8ca-93966b5796f7.png)

Also in the bot settings:
![image](https://user-images.githubusercontent.com/14835957/129838433-e8891d79-a7fa-4da7-9cbc-d49a9bb40d97.png)

Composer Release: 2.1.0-nightly.262125.19cdc4
