### ISSUE TITLE
Bot Framework Composer is not responding

### ISSUE THREAD

**Issue by amesquitaACD** [microsoft/BotFramework-Composer#5738]
## Describe the bug
In Bot Framework Composer, after importing my bot, all buttons are inaccessible. The program freezes.
I have tried this on different machines.
I use Bot Framework Composer in France.
https://powerusers.microsoft.com/t5/General/Bot-Framework-Composer-cannot-be-used/m-p/820707#M2018

## Version
1.3.0, but I tried with version 1.2.1 and 1.2.0.

## Screenshot
![image](https://user-images.githubusercontent.com/78791585/107344540-dc784000-6ac2-11eb-9caa-c168833bca43.png)

## OS
- Windows

## To Reproduce
1. Click Bot Framework in Power Virtual Agent
2. Import project into Bot Framework Composer
3. All buttons do not respond.

**Comment by dmvtech** [comment]
Did you get the pop-up to allow through the Windows firewall?

**Comment by cwhitten** [comment]
@amesquitaACD can you please install the latest nightly here: https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.1-nightly.210994.30d3ec2 and see if you still have the issue? thanks.

**Comment by amesquitaACD** [comment]
> @amesquitaACD can you please install the latest nightly here: https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.1-nightly.210994.30d3ec2 and see if you still have the issue? thanks.

**Comment by amesquitaACD** [comment]
@cwhitten this new version fixes the bug.
Thank you so much.
