### ISSUE TITLE
opening composer bot in Power Virtual Agent

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#5739]
Hi,

I am able to open a PVA bot inside Composer but could you please let me know the steps how to open a composer bot in PVA.
In Pva there is option to open composer with in PVA platform

![image](https://user-images.githubusercontent.com/70739031/107351586-caad9180-6af0-11eb-928f-aed3d3f47bcb.png)

But if  I create a bot directly in composer, there is no option to open it in PVA.

Thanks....

**Comment by cwhitten** [comment]
@BeheraMadan PVA applies some constraints to the functionality available to a bot created in Composer. When attempting to publish a bot directly to PVA it may return validation errors or other issues.

The recommendation is to start in PVA and click that button that you highlighted and it will start a Composer project with these constraints applied and should allow you to publish back to the bot. 

Closing as a how-to
