### ISSUE TITLE
Integrating Power virtual bot with composer bot

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#5750]
Hi,

We have a bot created using bot composer tool and an another bot created using PVA platform. How can we integrate PVA bot 
inside composer bot (is it possible with the help of 'connect to a skill' action ?). 

Thanks..

**Comment by Virtual-Josh** [comment]
@anusharavindrar  can you take a look at this?

**Comment by cwhitten** [comment]
Hi @BeheraMadan. As explained on https://github.com/microsoft/BotFramework-Composer/issues/5739, PVA has limitations to the types of Bots can you use. Currently they do not support adding skills to your bot from Composer. 

See https://powervirtualagents.microsoft.com/en-us/blog/power-virtual-agents-integration-with-bot-framework-composer-is-available-in-public-preview/ for more information.
