### ISSUE TITLE
Cannot Add Structured Choice in Prompt For Confirmation 

### ISSUE THREAD

**Issue by Uggi** [microsoft/BotFramework-Composer#5751]
Its impossible to add structured choice inputs with a defined action when configuring a Prompt for Confirmation.
the whole choice disappears when clicking out of the Action Json field.  

## Version

V1.3.0
![image](https://user-images.githubusercontent.com/4349731/107497525-9c7c9000-6b8a-11eb-870b-da20360d92b3.png)

## OS

Windows 10

## To Reproduce

1. Add a prompt for confirmation, 
2. go to user input
3. add a confirm choice of type structured choice
4. Then add data to an "Action" field
5. click anywhere else.

Results in the whole structured choice disappearing

## Expected behavior

Structured Choice should be Added

## Screenshots
Please see Gif of the Issue which clearly shows the problem.

![ConfirmChoice-StructuredInput Bug](https://user-images.githubusercontent.com/4349731/107498971-50cae600-6b8c-11eb-8ae2-0dc6b070d7da.gif)
)

**Comment by Virtual-Josh** [comment]
@anusharavindrar  can you repo this?

**Comment by srinaath** [comment]
@v-kydela It looks like a serialization bug and we can take a look at the bug

**Comment by cwhitten** [comment]
Hi @Uggi -- thanks for the bug report. We'll address this in an upcoming release.

**Comment by congysu** [comment]
Hi @cwhitten -- can you please advise which milestone shall we set for this item?  Thanks.

**Comment by cosmicshuai** [comment]
verified
