### ISSUE TITLE
Enable Microsoft Teams types

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#5752]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
As a team wise decision, remove it from R12 scope

**Comment by srinaath** [comment]
@yeze322  Can we close this ticket?

**Comment by yeze322** [comment]
> @yeze322  Can we close this ticket?

Yes we do. It's published as Nuget package.
