### ISSUE TITLE
Cannot delete card type lg templates automatically 

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#5753]
## Describe the bug

In Teams actions, lg templates are in 'Card' type, they cannot be discovered by removeLgTemplates api.
![image](https://user-images.githubusercontent.com/8528761/107507758-02910380-6bdb-11eb-8331-4eb3e6de5bcf.png)
LG server can recognize card type template.

related to #3673 

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by srinaath** [comment]
@boydc2014  can u take a pass at this ticket?
