### ISSUE TITLE
Remove Composer builtin uischema

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#5754]
## Describe the bug
~~Since we already port uischema to sdk repo, we don't need those built-in uischema any more.~~

Considering the migration problem, for those old bots without a re-generated uischema, they will still rely on builtin uischemas.

So I suggest that let sdk.uischema takes priority over builtin uischema js files. @a-b-r-o-w-n 

refs #4177 

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by yeze322** [comment]
I had a sync with Chris, there will be migration issues if we remove them entirely, so let's still keep it in R13, after we have a more robust diagnostic pipeline to defense potential schema breaking changes, we can then remove them.

**Comment by boydc2014** [comment]
> I had a sync with Chris weeks ago, there will be migration issues if we remove built-in uischema entirely, so let's still keep it in R13.
> After we have done two things, we can then remove those builtin uischema:
> 
> 1. A more robust diagnostic pipeline to defense potential schema failures. (WIP)
> 2. A better UI Schema merge strategy to deal with migration problem. (planned #4177)

I suppose you mean leave this out of R13, right?

**Comment by yeze322** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/4177#issuecomment-819269430

New plan combines with 4177:
1. [runtime-dotnet, js] Check-in all necessary sdk.uischema definitions to dotnet repo
2. [Composer] Split Composer built-in plugin schema into two parts - built-in.required, built-in.fallback
3. [Composer] Update the merge strategy to `built-in.required < (sdk.uischema ?? built-in.fallback) < sdk.override.uischema`. (keyword: `mergePluginConfigs`)

Considerations:
1. migration problems, we don't want to break old bots.
2. instead of removing old uischema, turning them into fallback uischema seems more reasonable.
