### ISSUE TITLE
Http Request  (application/x-www-form-urlencoded) does not percent encode the body

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#5755]
When using a Post Request with the Content Type == "application/x-www-form-urlencoded" the body does not get percent encoded and therefore fails.

What I actually expect from this is that you could just pass in an object and when Content Type is set to application/x-www-form-urlencoded it will convert the regular object to  `var1=x&var2=y&var3=%20something` for you?

**Comment by srinaath** [comment]
For reference microsoft/botbuilder-dotnet#3231. It looks like the issue should have resolved in the linked PR.

**Comment by Virtual-Josh** [comment]
@anusharavindrar Can you confirm this issue is resolved?

**Comment by anusharavindrar** [comment]
@cxbuilders, thanks for reporting this. Let me attempt a repro on my end to see if the issue got resolved.

**Comment by anusharavindrar** [comment]
@cxbuilders, can you attach a screenshot of the POST request? Also, what version of the composer are you on?
