### ISSUE TITLE
Add a "Reveal in File Explorer" option to the Recent Bots list on the home page

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#5764]
If I want to delete a bot or change a resource outside of Composer, being able to quickly open the associated folder would be useful.

See also: #5526.

**Comment by mewa1024** [comment]
Design referenced in #5526 addresses this:
![image](https://user-images.githubusercontent.com/39317542/124209390-4c9d5780-da9e-11eb-801b-14dfb3596a8c.png)

Closing this as dupe.
