### ISSUE TITLE
Problem using the deploy script in already provisioned environments

### ISSUE THREAD

**Issue by nickthewitcher** [microsoft/BotFramework-Composer#5773]
https://github.com/microsoft/BotFramework-Composer/blob/ea04f990e0b675b8ce35f315d5a6c1d6264ae525/runtime/dotnet/azurewebapp/Scripts/deploy.ps1#L316

I have an issue using the deploy script located in .\MyBot\runtime\azurewebapp\Scripts\deploy.ps1. 
I have a production environment and i have already provision all my resources so i just need to pass the parameters to this script to work, but the problem is in this line: 
$resourceGroup = "$name-$environment"
Why did you assume that the name of the resource group is a concatenation of the name and the environment? And more important, why i cant pass the name of the resource group as a parameter?. Please check this script using already provisioned environments. In my organization we are using this tool as an standard for bots but this is a main problem for dev/ops purposes,   so it's critical.
I already get an error from here:

WARNING: Getting scm site credentials for zip deployment
ERROR: ResourceNotFoundError: ResourceGroupNotFound: Resource group 'azbseu2vbccd02-dev' could not be found.

I have generated this runtime folder from the Composer Custom runtime Option: "Get a new copy of the runtime code"

**Comment by zxyanliu** [comment]
Hi, this is a known issue under investigation and we already started revising the existing readme files regarding both the provision and the deploy scripts. Will get back to you as soon as we get some updates on this. Thanks!

**Comment by congysu** [comment]
@zxyanliu can you please set a milestone for this issue?  Thanks.

**Comment by zxyanliu** [comment]
@congysu I tentatively set it to R12 milestone. FYI.

**Comment by zxyanliu** [comment]
@zidaneymar Please update the deploy scripts to include resource group.

**Comment by rflores0905** [comment]
> @zidaneymar Please update the deploy scripts to include resource group.

Hello, was the issue resolved?
