### ISSUE TITLE
Unable to switch bot language in Composer 1.3.1

### ISSUE THREAD

**Issue by ttur** [microsoft/BotFramework-Composer#5777]
With Composer 1.3.1 that has three languages (English, Swedish, Finnish) we are unable to switch the language we are using to edit. Clicking the language selection button at the top of the window flashes the selection and immediately closes. 

![image](https://user-images.githubusercontent.com/996293/107781569-b1a31b80-6d50-11eb-9f68-7b8ebb4f7db6.png)

A quick test with a new bot with two languages implies that the problem is not with our older, migrated bot, but can be reproduced with a fresh bot on the Composer.

## Version

Bot Framework Composer

                Version:  1.3.1
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution

## OS

- [X] macOS
- [X] Windows

## To Reproduce

Create a bot with more than one language. Try to select some other than the default language to be edited. 

## Expected behavior

New language would be selected and we could edit the content for it.

**Comment by ttur** [comment]
https://user-images.githubusercontent.com/996293/107786614-c84c7100-6d56-11eb-8922-54597e2175b0.mp4

Here's a vid of this occurring with a fresh bot

**Comment by ttur** [comment]
If there's only en-us as language the menu opens (of course, not very useful then...)

**Comment by cwhitten** [comment]
@ttur if you author different languages for your bot, you will see them as selectable options in this list. See the following doc for explanation on how to do this: https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language

Closing as a how-to

**Comment by ttur** [comment]
Thank you for the response.

Our bot is a year old already and we have been using the Composer since the beginning, from early beta. We have had the multi-language support since June. Our bot does not work now, on 1.3.1, at all. I studied the documentation linked, but it did not help, at all. 

I will try to create a new bot with this composer to see if I get multiple languages working and figure out what has changed. But if you have done a breaking change to language support since version 1.1.1 – that means we have to re-create the bot for multiple languages – it would be appreciated if this was told to us now, since this is all very time-consuming.

**Comment by ttur** [comment]
You might also want to take a look at this issue which was verified earlier: https://github.com/microsoft/BotFramework-Composer/issues/5441

**Comment by cwhitten** [comment]
@ttur there have been no known breaking changes around multi-language authoring. Are you able to send us the solution to look at and troubleshoot?

The issue you linked has not been addressed in 1.3.1, however if you subscribe to the early adopters feed you would see the change. Perhaps try this as well. Note: this commit in particular has introduced some unwanted side-effects and we may revert and reimplement with a different approach.

**Comment by negativeeddy** [comment]
I'm seeing the same issue. To repro
1) Create an empty bot
2) Add a language
3) See the language switch in the dropdown UI and cant change it
[EmptyBot-8-Repro.zip](https://github.com/microsoft/BotFramework-Composer/files/6149064/EmptyBot-8-Repro.zip)

As mentioned, if I change the default language in the settings, the UI dropdown will switch to that language. I just cant use the dropdown itself.
