### ISSUE TITLE
Add issue/warning indicators in the Diagnostics view

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#5782]
When working with multiple bots in the same project, it would be helpful to know which bots have issues.

## Issue

When you click the warning icon, Composer displays the Diagnostics view, but doesn't indicate which of your projects is generating the warnings.

![screenshot](https://user-images.githubusercontent.com/35047199/107812279-4f342600-6d24-11eb-8905-2cea82c2f191.png)

## Suggestion

Any of the following would be helpful:

- Include the warning count next to each bot that has warnings.
- In the details pane, include a column that indicates which bot the warning is associated with, and just list all warnings here.
- Auto-select the first bot that has warnings, when opening this view by selecting the warning icon, so as not to display an empty list when a populated list is expected.
- In the bots pane, include the ability to display warnings from all bots, not just one at a time.

## Related issues

#5130 - note: perhaps adding _information_ level alerts (along with warning and error) to the mix would be appropriate for some scenarios, such as skill bots that are missing a manifest. For testing, this is not a problem and you probably don't want to create the manifest until the skill is close to ready. So, an informational alert would remind devs there's another step needed before deployment.

**Comment by JonathanFingold** [comment]
The project pane does show a warning sign next to [presumably] any bot that has warnings, but that icon is not clickable.

Perhaps, make that one clickable too, and have it open the diagnostics view and auto-select the dialog the clickec icon was next to.

![image](https://user-images.githubusercontent.com/35047199/107814903-7a6c4480-6d27-11eb-8ae5-d512b8ccb91e.png)

**Comment by zxyanliu** [comment]
@JonathanFingold the error is associated with the WeatherSkill, meaning that you should choose WeatherSkill to see the error message. Hope it's helpfu.

**Comment by zxyanliu** [comment]
![image](https://user-images.githubusercontent.com/32497439/107830889-9d0b5700-6d41-11eb-86a9-289a32898e56.png)

**Comment by JonathanFingold** [comment]
This is more a usability issue. If I have a bunch of skills and only one or two issues, I don't want to click through all bots and skills in this view until I find all the issues.

**Comment by zxyanliu** [comment]
There are also cases when you have a bunch of skills/bots and a couple of warnings/errors, which error should be navigated to then? I personally think the current design makes more sense, especially with multiple errors/issues scenarios. Maybe I should add more description on this in our existing [validation](https://docs.microsoft.com/en-us/composer/how-to-validate) article.

**Comment by JonathanFingold** [comment]
This is what we have currently. I can't tell which bot or skill has issues.
![composer-issues-current](https://user-images.githubusercontent.com/35047199/108549980-c4fb3d00-72a2-11eb-8889-4e4720458068.png)

This is more of what I'd like to see. I can tell where to look for the issues without having to click through every bot or skill.
![composer-issues-proposed](https://user-images.githubusercontent.com/35047199/108549979-c462a680-72a2-11eb-891b-06367430380d.png)
