### ISSUE TITLE
Authentication error when deploy

### ISSUE THREAD

**Issue by pedro-ramirez-suarez** [microsoft/BotFramework-Composer#5784]
## Describe the bug

Since yesterday I can't deploy my bots, I have tried on different machines and OSs, I  can login into the azure portal and manage all the resources but when I try to deploy I get the error below(screenshots section):

## Version
1.3.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
Open my project, to the publish tab, select the bots to publish, click on "Publish selected bots", a new popup comes up to enter my credentials and after entering my email and password I get the error below.

## Expected behavior
I should be able to publish my bot.

## Screenshots

![image](https://user-images.githubusercontent.com/1943439/107821902-19963980-6d32-11eb-8ea0-85d3db67791e.png)

## Additional context
By mistake my AD account was deleted a couple of days back, the sysadmin recreated my account yesterday so I am not sure if it's related. I can login into any other service that uses my domain account (Azure, Outlook, etc)

**Comment by cwhitten** [comment]
@pedro-ramirez-suarez the context looks related:

> By mistake my AD account was deleted a couple of days back, the sysadmin recreated my account yesterday so I am not sure if it's related. I can login into any other service that uses my domain account (Azure, Outlook, etc)

Can you make sure you have your account and subscriptions properly set up?

**Comment by pedro-ramirez-suarez** [comment]
Hi @cwhitten,

I can login into Azure without any issues and even manage all the bots that I already deployed, I can see my subscriptions, the only thing that I can't do is deploy from composer. Do you have any idea of what settings could be wrong that prevents me to deploy?

**Comment by dmvtech** [comment]
Hi @pedro-ramirez-suarez Let me check some things and get back to you.

**Comment by dmvtech** [comment]
Hi @pedro-ramirez-suarez I tested by trying to do the same thing (creating an account that I then removed and re-added), but was unable to reproduce this.

Are you able to create a new bot and new publishing profile and log in successfully with that?

If so, can you try creating a new publishing profile on the existing bot and try?

**Comment by pedro-ramirez-suarez** [comment]
I can't either create new a publish profile or publish to an existing profile, maybe the problem is on the authentication service not in composer?

**Comment by dmvtech** [comment]
It might be. If you have the [az cli tools](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) (or can install them), are you able to log in with the same creds?

`az login`

And to clarify; this is a Work/School account, not a personal MSA, correct?

**Comment by daveta** [comment]
Closed due to inactivity.
