### ISSUE TITLE
The runtime settings section of the settings page is incorrectly tied to the root bot

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#5785]
## Describe the bug

When editing or viewing the runtime settings, only the root bot's settings are ever displayed, regardless of what bot is selected on the sidebar.

## Version

Current main

## To Reproduce

1. open a multibot project
2. navigate to settings
3. switch to the child bot
4. change runtime settings
5. change back to root bot, note that the settings were actually changed there and not in child bot.

## Expected behavior

i should be able to edit the settings for each bot.

## Screenshots

![kXJFkfYNLt](https://user-images.githubusercontent.com/729873/107824785-adbecb80-6d47-11eb-9647-c98892a53f6c.gif)

## Additional context

this was introduced recently.

**Comment by beyackle** [comment]
Some notes as I continue working on this. The values are stored correctly in the settings; this page just doesn't change the text boxes over when the in-focus projectId changes, so if you focus then unfocus a box, those values will get propagated into the wrong bot.

**Comment by beyackle** [comment]
Okay, I figured it out. PR coming soon.

**Comment by hibrenda** [comment]
if I delete the content in root bot setting, error also populated into child bot setting 
![image](https://user-images.githubusercontent.com/43408889/109938721-5343da00-7d0b-11eb-9149-b079257a3695.png)

![image](https://user-images.githubusercontent.com/43408889/109938643-39a29280-7d0b-11eb-9ad1-53ccee14044b.png)
