### ISSUE TITLE
Composer translates relative paths in runtime settings to absolute paths

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#5786]
## Describe the bug

Composer incorrectly changes relative paths to absolute paths. This defeats the purpose of allowing relative paths since if a project folder moves, the path breaks.  

## Version

Current main

## To Reproduce

1. navigate to settings
2. change the runtime path to "../"
3. reload the page. the path will be replaced with an absolute path

## Expected behavior

The relative path should remain unmodified.

## Screenshots
![sRmGK578RD](https://user-images.githubusercontent.com/729873/107825094-23c33280-6d48-11eb-8b34-70fff80d792f.gif)

**Comment by luhan2017** [comment]
@alanlong9278, could you please take a look at this issue since @VanyLaw is OOF this week.

**Comment by luhan2017** [comment]
@benbrown,  Per Alan's PR, that logic is commented out. Maybe we don't need a runtime folder any longer because the runtime folder should exactly be the bot folder for the new adaptive runtime? @pavolum to comment on this.

**Comment by benbrown** [comment]
The runtime path will continue to be relevant for the new version of the runtime as well! We will need to keep it for the foreseeable future to enable customizations, and legacy support.
