### ISSUE TITLE
Publishing Bot into diffrent Azure Directories

### ISSUE THREAD

**Issue by bennimoser** [microsoft/BotFramework-Composer#5792]
Currently its not possible to choose from available AAD's. Would be good if that could be added to the composer

**Comment by cwhitten** [comment]
Hi @bennimoser - we'll look to support this functionality in an upcoming release. Thank you for the feature-request.

**Comment by cwhitten** [comment]
@bennimoser tenant/directory selection will be available in our upcoming stable release (May 2021). The early adopters feed has this functionality now if you wanted to try it out. You'll need to recreate your provisioning profile.
