### ISSUE TITLE
Please provide the equivalent of visual studios "Navigate forward/back" (and/or multi-tab support)

### ISSUE THREAD

**Issue by Uggi** [microsoft/BotFramework-Composer#5800]
## Navigation in the bot composer desktop app is a frustrating experience.

Navigation in the Bot Composer Desktop App is painful when you have a lot of dialogs & lg files..

The moment you move away from a page, regardless of type (dialog/bot response/qna etc) you lose all context of where you have been. There isn't even a back button! You then have to hunt around in whichever area you came from to find the relevant section.

This pain point is really very obvious if you have a shared dialogs that are called from multiple places and you are following a path through them. there is no way to navigate back. 

One of the biggest problems with moving through multiple dialogs is that re-opening a previous dialog always moves me to the top of the dialog. if the path I`m following is much further down the page then it gets really frustrating to navigate with any real depth. 

## "Navigate forward/back".

Please provide the equivalent of visual studios "Navigate forward/back".

![image](https://user-images.githubusercontent.com/4349731/108135832-b9482480-70b0-11eb-97c7-46ac0e2eaaa1.png)

This would allow users to easily move back to earlier open areas (dialog or lg) without having to go digging for it. 

## Alternative: Add a Multi-Tab Experience 
Allow users to open multiple tabs at the same time. so that I can simply switch tabs to get back to the last location. 
Assuming i have scrolled down at least a full page, When I click on a dialog to follow it  , it should open a new second tab automatically and I can then maintain the first tabs scroll location and easily return to where I was. 

## (or Do both!)
"Multi-tab support" & "forward/back navigation" together would make navigating Desktop Bot Composer App so much better.

![image](https://user-images.githubusercontent.com/4349731/108137225-615eed00-70b3-11eb-90b6-a135a8ed1d11.png)

**Comment by cwhitten** [comment]
Adding to backlog for prioritization - thank you for the feature request

**Comment by Uggi** [comment]
@cwhitten Any chance this may get prioritised anytime soon?

**Comment by Uggi** [comment]
Hi @cwhitten, given the issue is closed, is there a UX task on the way which delivers this in some form? Thanks

**Comment by cwhitten** [comment]
Hi @Uggi 

Thanks for the note. The product team has no plans to prioritize this functionality at the moment.
