### ISSUE TITLE
Can't install package with custom runtime

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#5803]
## Describe the bug

I am attempting to add a package and it gives me unactionable error.

## Version

![image](https://user-images.githubusercontent.com/17789481/108143735-24780380-707d-11eb-81fe-3d2c57096cf6.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. ```dotnet new -i Iciclecreek.Bot.Templates```
2. md foo
3. cd foo
4. ```dotnet new LucyBot```
5. Load **foo\foo** in composer
6. Add package **Iciclecreek.Bot.Builder.Dialogs.Database.Cosmos**

## Expected behavior
1. should be able to add nuget package with custom runtim/
2. Error message needs to be more descriptive so I can try to resolve the issue
3. Color schema is unreadable.

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/108143487-b8959b00-707c-11eb-9971-6f99233c1edd.png)

**Comment by benbrown** [comment]
@tomlm  did you create a runtime definition that tells Composer how to deal with your customized runtime?

**Comment by tomlm** [comment]
the path to my csproj is in the configuration, I am building and running the bot externally
