### ISSUE TITLE
Can't start custom project from composer

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#5804]
## Describe the bug
Can't start a custom project from composer.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. ```dotnet new -i iciclecreek.bot.templates```
2. md foo
3. cd foo
4. ```dotnet new LucyBot```
5. Load **foo/foo** in composer
6. Check runtime configuration, should be custom with **func run**  in foo folder.
7. Run bot, it fails
8. See Details shows incorrect message 
 
## Expected behavior
* Should run my project
* Error message should be correct (I definitely have dotnet installed)

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/108144069-c13aa100-707d-11eb-9957-c63f307b07b3.png)

![image](https://user-images.githubusercontent.com/17789481/108144086-c992dc00-707d-11eb-8f62-5c677f8f8d26.png)

**Comment by cwhitten** [comment]
@tomlm can you send me the settings file used in the project? Composer expects some fields to be shaped a certain way when using a custom runtime,
