### ISSUE TITLE
Composer overwrites AND deletes files on project load, causing data loss

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#5805]
[qlucene.zip](https://github.com/microsoft/BotFramework-Composer/files/5992726/qlucene.zip)
## Describe the bug
If composer discovers a .qna file it will blow away other files in the same folder.

## Version

![image](https://user-images.githubusercontent.com/17789481/108144193-065ed300-707e-11eb-84ea-694d447e5b7b.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. ```dotnet new -i iciclecreek.bot.templates```
2. md foo
3. cd foo
4. ```dotnet new LucyBot```
5. cd foo
6. unzip attached zip file -> qlucene folder 
7. cd qlucene
7. ```dir /s *``` 
it looks like this:
```
C:\scratch\foo\foo\qlucene>dir /s *
 Volume in drive C is OSDisk
 Volume Serial Number is 42E5-5CBB

 Directory of C:\scratch\foo\foo\qlucene

02/16/2021  05:52 PM    <DIR>          .
02/16/2021  05:52 PM    <DIR>          ..
02/16/2021  05:52 PM            32,214 KeurigSkill.en-us.qna
02/10/2021  12:59 PM    <DIR>          KeurigSkill.en-us.qna.catalog
02/10/2021  10:18 AM               127 KeurigSkill.en-us.qna.dialog
02/10/2021  10:24 AM            52,874 KeurigSkill.json
02/10/2021  10:18 AM               116 KeurigSkill.qna.dialog
               4 File(s)         85,331 bytes

 Directory of C:\scratch\foo\foo\qlucene\KeurigSkill.en-us.qna.catalog

02/10/2021  12:59 PM    <DIR>          .
02/10/2021  12:59 PM    <DIR>          ..
02/10/2021  10:18 AM                36 segments.gen
02/10/2021  10:18 AM                89 segments_1
02/10/2021  10:18 AM               284 _0.cfe
02/10/2021  10:18 AM            50,186 _0.cfs
02/10/2021  10:18 AM               254 _0.si
               5 File(s)         50,849 bytes
```
* **KeurigSkill.en-us.qna** is 32k file. 
* There are **two .dialog** files in this folder.
7. Load **foo/foo** in composer
8. ```dir /s *``` 
It now looks like this:
```
C:\scratch\foo\foo\qlucene>dir /s *
 Volume in drive C is OSDisk
 Volume Serial Number is 42E5-5CBB

 Directory of C:\scratch\foo\foo\qlucene

02/16/2021  05:55 PM    <DIR>          .
02/16/2021  05:55 PM    <DIR>          ..
02/16/2021  05:55 PM                56 KeurigSkill.en-us.qna
02/10/2021  12:59 PM    <DIR>          KeurigSkill.en-us.qna.catalog
02/10/2021  10:24 AM            52,874 KeurigSkill.json
               2 File(s)         52,930 bytes

 Directory of C:\scratch\foo\foo\qlucene\KeurigSkill.en-us.qna.catalog

02/10/2021  12:59 PM    <DIR>          .
02/10/2021  12:59 PM    <DIR>          ..
02/10/2021  10:18 AM                36 segments.gen
02/10/2021  10:18 AM                89 segments_1
02/10/2021  10:18 AM               284 _0.cfe
02/10/2021  10:18 AM            50,186 _0.cfs
02/10/2021  10:18 AM               254 _0.si
               5 File(s)         50,849 bytes
```
* **KeurigSkill.en-us.qna** is now **56 bytes !!!!!!!**
* **all of the .dialog files were deleted!!!!!!!**

My content file was overwritten with 
```
> # QnA pairs

[import](KeurigSkill-manual.source.qna)
``` 

## Expected behavior
1. I should not have content files deleted by composer because I loaded the project.
2. Content files should never be overwritten by composer because I loaded the project.
3. Composer should NOT be assuming I am using QnAMaker
4. **KnowledgeBase folder** There should not be a **source** folder created. That's just wrong.  **The content for en-us.qna should be in the en-us folder.**
5. **KnowledgeBase folder** There **should not** be a **source.qna** file with an import from the en-us, that's just wrong.  **The contents for en-us.qna should be in the en-us folder.**

**Comment by boydc2014** [comment]
@tomlm can you attach top level folder, i mean the foo/foo folder? 

or do you have any instructions of how to setup "iciclecreek.bot.templates"

**Comment by tomlm** [comment]
This sets up the templates:

1.  `dotnet new -i iciclecreek.bot.templates`

**Comment by cosmicshuai** [comment]
verified
