### ISSUE TITLE
[MCS-DE] Publishing fails due to Azure Login error

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#5807]
When I try to Publish a Bot, the Azure Login fails. My account has access to multiple tenantes and subscriptions.

Ideally the settings in the publishing profile should contain settings for tenantID and subscriptionID to be passed with the login to ensure the approriate subscription is accessed.

![image](https://user-images.githubusercontent.com/31212469/108189470-11af0e80-7111-11eb-99c4-8b0bb50265aa.png)

![image](https://user-images.githubusercontent.com/31212469/108189480-14a9ff00-7111-11eb-9249-b9f4ab5719cb.png)

![image](https://user-images.githubusercontent.com/31212469/108189487-170c5900-7111-11eb-9075-6f6539f77e60.png)

![image](https://user-images.githubusercontent.com/31212469/108189495-183d8600-7111-11eb-829f-bbb8e894bf8e.png)

***Publishing Log below:***

---
"Accepted for publishing..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"Assigning to luis app id: 1a0cde94-1f5c-4275-ac92-87f08a5e86cb"
---

---
"{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\",\"error\":{\"error\":{\"message\":\"Failed to parse azure account information object object.\"}},\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\\n    at new i (C:\\\\Users\\\\jagoerge\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:110597)\\n    at F.callback (C:\\\\Users\\\\jagoerge\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:109440)\\n    at F.e.callback.t.callback [as _callback] (C:\\\\Users\\\\jagoerge\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:108488)\\n    at F.t._callback.t.callback.t.callback (C:\\\\Users\\\\jagoerge\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:4017)\\n    at F.emit (events.js:210:5)\\n    at F.<anonymous> (C:\\\\Users\\\\jagoerge\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:16714)\\n    at F.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Users\\\\jagoerge\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:15546)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
---

---
"{\"stack\":\"SyntaxError: Unexpected token o in JSON at position 1\\n    at JSON.parse (<anonymous>)\\n    at Object.<anonymous> (C:\\\\Users\\\\jagoerge\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:115579)\\n    at C:\\\\Users\\\\jagoerge\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:112703\\n    at Object.throw (C:\\\\Users\\\\jagoerge\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:112808)\\n    at s (C:\\\\Users\\\\jagoerge\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:111573)\",\"message\":\"Unexpected token o in JSON at position 1\"}"
---

---
"SyntaxError - Unexpected token o in JSON at position 1"
---

**Comment by luhan2017** [comment]
@goergenj , this is a known issue in composer now. We don't support switch tenant in composer yet, we will prioritize on this.

**Comment by Dewain27** [comment]
We will track this in #5459 
@cwhitten do we need to continue to track this here or can we just track it under the #5459 issue?

**Comment by cwhitten** [comment]
We only need one. See #5459 for updates on this feature request. Thank you

**Comment by goergenj** [comment]
@cwhitten  Just to make sure we have the correct understanding. This is not just croos-tenant. Currently I cannot publish in ANY tenant. Not even within the same tenant that hosts my account. If there is a configuration or other issue, happy to take your advise on how to solve this. If I could at least publish inside the tenant of my account, this would already unblock short-term.

**Comment by luhan2017** [comment]
@goergenj , your error message shows that the publish failed in the luis app binding with luis prediction service step. Please follow this comment to fix this issue. https://github.com/microsoft/BotFramework-Composer/issues/5354#issuecomment-747150353
