### ISSUE TITLE
Node runtime unable to send trace and customEvent to application insights

### ISSUE THREAD

**Issue by Dan-Bai** [microsoft/BotFramework-Composer#5808]
## Describe the bug

Logs not sent to application insight after providing instrumentation key

## Version

Version: 1.3.0
NodeJS: 12.13.0

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

Create new bot composer project
Add 'Emit a telemetry track event'
Add instrumentation key in advanced settings view
Use custom runtime with location 'runtime' and start command 'node ./lib/webapp.js'
Run dialog to hit emit event

## Expected behavior

Expected log to appear in application insights

## Additional context

Noticed that the .NET version of runtime has code where application insights is added to dialog manager, similar code is missing in the Node runtime.
Was able to send telemetry by adding useTelemetry() inside loadRootDialog()

**Comment by v-kydela** [comment]
@compulim - I can see that you assigned me to this. What would you like me to do?

**Comment by cwhitten** [comment]
@v-kydela are you able to jump in and get a repro of this or work with the customer to understand the issue?

**Comment by v-kydela** [comment]
@cwhitten - Yes, I'll do that

**Comment by v-kydela** [comment]
@Dan-Bai - I followed your instructions and I'm getting this error:

![image](https://user-images.githubusercontent.com/41968495/108920316-4fb4a280-75e9-11eb-9456-ae7fe6f41037.png)

Is there anything you left out from your repro steps? Did you export the runtime first? Can you link to any documentation you've followed?

**Comment by Dan-Bai** [comment]
@v-kydela Sorry, I did export the runtime first. Didn't explicitly follow any documentation.

**Comment by v-kydela** [comment]
@Dan-Bai - How did you export the runtime?

**Comment by Dan-Bai** [comment]
@v-kydela From the Bot Composer UI under settings/custom runtime

**Comment by v-kydela** [comment]
@cwhitten - The problem appears to be exactly as the customer described. The Node runtime doesn't do anything with the instrumentation key provided in the settings. Is there anything else that needs to be understood about this issue?

**Comment by v-kydela** [comment]
I will unassign myself so this can be triaged again

**Comment by tonyanziano** [comment]
@luhan2017 can you take a look at this?

**Comment by carlosscastro** [comment]
@chon219 @luhan2017 let's get more traction on this related PR so we can close this soon. Thanks!
