### ISSUE TITLE
BeginDialog.Dialog should allow you type in a arbitrary dialog.id.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#5820]
## Describe the bug
BeginDialog does not let me begin a dialog by id, it only shows a list of adaptive dialogs.  

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior

**BeginDialog** action is designed to pass options to 
* An **AdaptiveDialog** by **resourceId**
* A **"legacy" dialog** by the **dialog.id** a dialog is registered.
The LegacyDialog is added to a a DialogContainer in the parent (such as AdaptiveDialog or root DialogManager).  When it is added it is given a unique id by the developer adding it, which can then be used to invoke it with **BeginDialog** action

startup.cs
```C#
   DialogManager dm = new DialogManager();
   dm.Dialogs.Add(new FooDialog(...) { Id = "DoFoo3", ....}
```

MyDialog.dialog
```json
    {
       "$kind":"Microsoft.BeginDialog",
        "dialog":"DoFoo3"
         "options": {
              "name":"=user.name"
         }
     }
```
It is fine to have a drop down of the known AdaptiveDialogs, but the UI should let me type in an dialog id or expression to a dialog id. **If we don't have this people customers cannot access dialogs they have written in code.** 
```json
    {
       "$kind":"Microsoft.BeginDialog",
        "dialog":"=conversation.somevar"
         "options": {
              "name":"=user.name"
         }
     }
```

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/108294408-b994fe00-714a-11eb-9752-f73e581f88a6.png)

**Comment by cosmicshuai** [comment]
verified
