### ISSUE TITLE
BeginDialog.Options is ignoring the schema definition for the value 

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#5821]
## Describe the bug

The UI treats the Value property as a string, and not an AnyExpression

**BeginDialog.Options** is meant to allow people to invoke an aribtrary dialog. It does this by having an Options property which is technically
    "name": valueExpression

Where value expression is any type or an expression which binds to that.

```json
 {
    "$kind":"Microsoft.BeginDialog",
    "options": {
           "var1": 13, 
           "var2": "some text",
           "var3": "=user.age",
           "var4": "=user.name"
     }
}
```

The UI treats the value part of the name/value pair as a STRING, not an expression and not at typed property at all. 

## Version
![image](https://user-images.githubusercontent.com/17789481/108297350-f8798280-714f-11eb-9cac-b8ff3b082f28.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Add BeginDialog.action
2. Value editor should show the expression editor as an option.

## Expected behavior
It should show the Any Expression property editor
![image](https://user-images.githubusercontent.com/17789481/108297557-4b533a00-7150-11eb-971c-4a4e11d426b7.png)
(See **HttpAction**)
## Screenshots

![image](https://user-images.githubusercontent.com/17789481/108297474-28c12100-7150-11eb-81a1-a02a3e08415f.png)

**Comment by cwhitten** [comment]
Adding @tdurnford to make the options field for BeginDialog schema aware to prefill the form
