### ISSUE TITLE
How to use translator service in bot composer 

### ISSUE THREAD

**Issue by UmaPrelude** [microsoft/BotFramework-Composer#5826]
Hi,
I want my bot to support multi language with qna maker, so while exploring I came to know we can use translator service to achieve this with out creating multiple knowledge bases. 
So I wish to know how to use translator service from bot composer.
Please suggest the way to handle at the early, thanks so much.

**Comment by cwhitten** [comment]
Hi @UmaPrelude -- this is not possible in Composer today. Adding @garypretty for additional discovery and prioritization

**Comment by UmaPrelude** [comment]
Thanks @cwhitten. 

Hi @garypretty, Please let me know if there is any plan for this.
