### ISSUE TITLE
runtime location and start script does not populate when ejecting runtime

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#5832]
## Describe the bug

A refresh is required in order to see the custom runtime location as well as the start script after ejecting the runtime.

## Version

1.3.1-nightly.214892.a16c00c

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to settings and toggle "Use custom runtime"
2. Select any language
3. Notice no runtime location or script show
4. Refresh the page (or open the bot agian)
5. The runtime path and script are now present

## Expected behavior

After selecting a runtime template, the runtime path and start script should immediately show in the UI.

## Screenshots

https://user-images.githubusercontent.com/3619060/108433900-9a09de00-71fb-11eb-9fcc-2f747115c8c6.mov

## Additional Information
Related to #5828

**Comment by cwhitten** [comment]
cc @VanyLaw please take a look at this - thanks!
