### ISSUE TITLE
Duplicated choices of C# show up when adding custom runtime

### ISSUE THREAD

**Issue by feich-ms** [microsoft/BotFramework-Composer#5836]
## Describe the bug

Duplicated choices of C# runtime occurred when adding custom runtime

## Version

Main branch

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot
2. Use custom runtime

## Expected behavior

No duplicated C# choices

## Screenshots

![image](https://user-images.githubusercontent.com/43032123/108467417-2251b700-72c0-11eb-96ac-287df1e0f52f.png)

**Comment by VanyLaw** [comment]
I found it's the change from https://github.com/microsoft/BotFramework-Composer/pull/5029/files#diff-86151e8730a0d14739196048967f7132728568334acb3f86319ef353c914ded2 this PR. but I see that's a different key, so I am not sure if it's an issue. @pavolum could you help to take a look?

**Comment by VanyLaw** [comment]
maybe we can give different names, like C#(normal) and C#(new).

**Comment by cwhitten** [comment]
@VanyLaw I don't believe we want to allow the C#(new) ejection option. cc @benbrown

**Comment by benbrown** [comment]
Concur with @cwhitten. I will try to address this if @pavolum doen't get to it first.

**Comment by benbrown** [comment]
This was fixed.
