### ISSUE TITLE
Ejected js runtime throw exceptions when starting bot

### ISSUE THREAD

**Issue by feich-ms** [microsoft/BotFramework-Composer#5839]
## Describe the bug
Node version: v14.15.5

Eject js runtime and start the bot will throw exceptions like below:

Start bot failed

{"stack":"Error: npm WARN npm npm does not support Node.js v14.15.5\nnpm WARN npm You should probably upgrade to a newer version of node as we\nnpm WARN npm can't make any promises that npm will work with this version.\nnpm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12, 13.\nnpm WARN npm You can find the latest version at https://nodejs.org/\n\n at D:\\code\\BotFramework\\BotFramework-Composer\\extensions\\runtimes\\lib\\index.js:1:71140\n at Generator.next (<anonymous>)\n at s (D:\\code\\BotFramework\\BotFramework-Composer\\extensions\\runtimes\\lib\\index.js:1:66940)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:93:5)","message":"npm WARN npm npm does not support Node.js v14.15.5\nnpm WARN npm You should probably upgrade to a newer version of node as we\nnpm WARN npm can't make any promises that npm will work with this version.\nnpm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12, 13.\nnpm WARN npm You can find the latest version at https://nodejs.org/\n"}

## Version

Main branch

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Eject js runtime
2. Start the bot
3. You will find the exception

## Expected behavior

No exception

## Screenshots

![image](https://user-images.githubusercontent.com/43032123/108480309-c1cb7580-72d1-11eb-83b8-d6f9ae957450.png)

**Comment by feich-ms** [comment]
Just figured out that this was because the npm version is not upgraded to the latest one. After I `npm install -g npm@latest`, the error will go away.

**Comment by luhan2017** [comment]
ejected runtime deprecated.
