### ISSUE TITLE
Sometimes I cannot add a structured choice

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#5844]
## Describe the bug

This issue happens sometimes. 

## Version

https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.3.1

## Browser

- [x] Electron distribution

## OS

- [x] Windows

## To Reproduce

1. Go to **Action** menu-> **Ask a question** -> **Multi-choice**
2. Click on **User Input** in the **Properties** panel.
3. Scroll down to **Array of choices** -> select **structured choices**
4. Select **Add**. After enter the **Choice name**, **Synonyms**. Select **Add**.
5. See error.

## Expected behavior

Should be able to add a structured choice.

## Screenshots

![multi-choice-prompt](https://user-images.githubusercontent.com/32497439/108542984-44840e80-7299-11eb-89d1-9134a69dbf88.gif)

## Additional context

Related to this issue: https://github.com/MicrosoftDocs/composer-docs/issues/98

**Open questions:** 
1. What are structured choices? 
2. Among the three properties of a structured choice: `Choice Name`, `Synonyms(Optional)`, and `Action`, what does an `Action` mean? How do define an `Action`?

**Comment by garypretty** [comment]
@cwhitten can we have someone look at this please?  This is one of the most used actions, so would be good to get to the bottom of this.

**Comment by cwhitten** [comment]
putting this on you initially, @tdurnford

**Comment by tdurnford** [comment]
Closing in favor of https://github.com/microsoft/BotFramework-Composer/issues/5751
