### ISSUE TITLE
Bot homepage lists the wrong port

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5846]
It is better to list no port than the wrong port.

See image:

![image](https://user-images.githubusercontent.com/8867670/108555879-f11abc00-72aa-11eb-8102-1035114de677.png)

**Comment by cwhitten** [comment]
@scheyal we think this came from the samples when we copied it over.

**Comment by cwhitten** [comment]
cc @ryanlengel @tracyboehrer keep in mind with new runtime assets sitting in `wwwroot`

**Comment by cwhitten** [comment]
Closing as a dupe of https://github.com/microsoft/botframework-components/issues/946
