### ISSUE TITLE
Error merging component schema in custom action: Interface Microsoft.IDialog is not defined

### ISSUE THREAD

**Issue by Rekeyea** [microsoft/BotFramework-Composer#5856]
## Describe the bug

When using the update-schema.ps1 script, there is an error as follows:

``` powershell
Error SearchMessageComposition: Interface Microsoft.IDialog is not defined

*** Could not merge components ***
```

This is with the following schema:

``` JSON
{
  "$schema": "https://schemas.botframework.com/schemas/component/v1.0/component.schema",
  "$role": "implements(Microsoft.IDialog)",
  "title": "SearchMessageComposition",
  "description": "This will build the message string which will be sent to the user to describe what will be search.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "resultProperty": {
      "$ref": "schema:#/definitions/stringExpression",
      "title": "SearchMessage",
      "description": "Value from callers memory to store the result"
    }
  }
}
```

The same error happens when using the [sample MultiplyDialog schema](https://github.com/microsoft/BotFramework-Composer/blob/main/runtime/dotnet/customaction/Schemas/MultiplyDialog.schema)

## Version

![image](https://user-images.githubusercontent.com/8574490/108643147-f5e89700-7487-11eb-95c0-3ac1e15fd56d.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Eject the runtime
2. Move to the schemas folder inside the bot folder
3. Open powershell and run ./update-schema.ps1

## Expected behavior

Schemas should be merged correctly.

## Screenshots

![image](https://user-images.githubusercontent.com/8574490/108643191-31836100-7488-11eb-8a27-b13019ce2440.png)

**Comment by cwhitten** [comment]
@luhan2017 can you take a look at this?

**Comment by dmvtech** [comment]
Reproduced with `v1.3.1-nightly.216473.93194e8` and bf cli version `4.10.0-dev20200730.3786d10`

Attempting to update BF cli and try again.

**Comment by yeze322** [comment]
what is the version of your bf-cli? It needs to be updated to 4.12
Try running `npm i -g @microsoft/botframework-cli@next`

**Comment by dmvtech** [comment]
That worked for me. @Rekeyea please try that and let us know if you have any issues with that.

**Comment by jobpool** [comment]
I have the same issue. I have updated bf-cli to 4.12, but the issue remains, any other ideas?

**Comment by luhan2017** [comment]
@jobpool did you install the bf-dialogs through bf plugins before, could you try to 
- bf plugins:uninstall @microsoft/bf-dialog 
and install bf-cli again?

**Comment by Rekeyea** [comment]
> What is the version of your bf-cli? It needs to be updated to 4.12 since the sdk.schema was updated during R12.
> Try running `npm i -g @microsoft/botframework-cli@rc`

Awesome! It worked! 
Thank you all.
