### ISSUE TITLE
index.js file has been deleted accidently

### ISSUE THREAD

**Issue by mn-invia** [microsoft/BotFramework-Composer#5859]
Hi,

One of team members has **accidently deleted the index.js** file in the below two directories:

C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\lib\node
C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\lib\ui

Because of this the MicroSoft Composer is not starting up.......Do we need to:
1. Re-install the Composer  or
2. Re-install node.js or
3. Any other way around without doing any of the above re-installs....?

Note: I have found the errors by running the composer via the command line.

Please, can somebody provide a quick response please?  Much appreciated. 

Thanks.

**Comment by dmvtech** [comment]
Hi @mn-invia You can reinstall Composer, or copy that file over from somewhere else (another machine, etc). Assuming the right/same/correct version of the file. Re-installing Composer is probably the easiest, quickest and best way to ensure it's correct.

**Comment by dmvtech** [comment]
Closing as answered. Please let us know if you need further assistance.
