### ISSUE TITLE
Adding a remote skill breaks the app - nightly build

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#5863]
## Describe the bug

When adding a remote skill, the app breaks.

## Version

https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.1-nightly.214892.a16c00c

## Browser

- [x] Electron distribution

## OS

- [x] Windows

## To Reproduce

See the screenshots below.

## Expected behavior
Should not show a blank page. The app should not break.

## Screenshots

1. 
![image](https://user-images.githubusercontent.com/32497439/108751597-4945fe00-74f7-11eb-9061-dc5bdf9054ad.png)

2. 
![image](https://user-images.githubusercontent.com/32497439/108751615-4f3bdf00-74f7-11eb-91b6-a28f501778d1.png)

**Comment by cosmicshuai** [comment]
verified
