### ISSUE TITLE
T&Cs acceptance for enablement of Teams Connection

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#5866]
## Is your feature request related to a problem? Please describe.

When enabling the Teams Connection, you will need to verify that the user has accepted the T&Cs associated to enabling this connection.  If a user has already accepted the T&Cs in ABS or CLI, then we need to not prompt the user again.

## Describe the solution you'd like

In Composer, when a user enables the connection to Teams, we should check to see if they have already accepted T&Cs and if not, then prompt them to accept them in the Composer UI.  This should be done only once per Azure Account no matter the interface in which the acceptance is gained.  This will only be for the Teams Connection and if not accepted, the user should not be able to enable the Teams Connection.

**Comment by emivers8** [comment]
Design needs to be verified with actual content. I couldn't find a reference for this, so send my way if you have one. (Do we have the version of this from Ibiza handy? @Dewain27)

Figma: https://www.figma.com/file/tvENftrexoAYJngzsJxUbv/EmFig?node-id=3244%3A1007

![image](https://user-images.githubusercontent.com/55601267/112234965-eed5b580-8bfa-11eb-8818-b43b65cc5ba9.png)

**Comment by benbrown** [comment]
There is a PR open for this functionality, but we need to carefully coordinate this with the ABS team so that it launches at the same time or AFTER the ABS api change ships --- otherwise, the T&C acceptance will never be stored and users won't be able to enable teams.

**Comment by cwhitten** [comment]
Moving to R14

**Comment by cwhitten** [comment]
@benbrown are you on point for the following?

>  we need to carefully coordinate this with the ABS team so that it launches at the same time or AFTER the ABS api change ships --- otherwise, the T&C acceptance will never be stored and users won't be able to enable teams.

**Comment by benbrown** [comment]
@cwhitten the change on the ABS side has shipped. We are good to go on this from the Composer side. When we ship this feature, the (already in existence) TOS acceptance flag will be used.
