### ISSUE TITLE
LG Editor: Ensure tabs remain in a consistent order

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#5867]
On the LG editor, if I start with a Text tab, add a Speech tab, I have the tabs in the order Text -> Speech. 

If I then remove the Text tab and re-add a Text tab, my tabs are then in the order Speech -> Text.

Ideally we should try and ensure that tabs are shown in the order Text -> Speech -> Attachments -> Suggested Actions.

**Comment by hatpick** [comment]
I dont agree, I think ideally we should keep the order in which user modified them.

**Comment by garypretty** [comment]
@hatpick @sangwoohaan I think allowing the tabs to appear in the order they are created could lead to a very inconsistent experience over time. For example, I create a bot today and add 10 actions, each with multiple tabs and all of them end up in different orders.  Then I come back to the bot the next day / month etc and all of the tabs on all my actions are all in an inconsistent order. I think this would be a pretty poor experience.

**Comment by hatpick** [comment]
That's a great argument for a static tab list. However, for a dynamic tab view such as this the behavior is that they appear in the order that they get added. For example look how Edge or vscode work.

**Comment by sangwoohaan** [comment]
I think for a future milestone this can be customizable in a way that it serves the user's intention for what the main modalities of your bot would be(i.e. if you decided to build an Alexa skill, you would want the speech tab to come first). But still, the tab order should be consistent across the board. I think giving too much control to users to individually determine the order of the tabs would eventually lead them to inconsistent UX.
