### ISSUE TITLE
LG Editor: Tabbing from a variation input box selects an invisible delete icon

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#5869]
Tabbing out of a variation input box navigates to the invisible delete icon for the next item. Continuing to tab moves to the next invisible delete icon. 

Assuming this might also affect the use of the same control in the QnA KB section?

**Comment by hatpick** [comment]
@sangwoohaan what should happen here? (what's happening is not implemented, it's what Fabric decides to do)

**Comment by garypretty** [comment]
@hatpick @sangwoohaan I don't consider this to be high priority.  Indeed, having looked at the behavior again, it could be that this is working as intended for accessibility. 

@sangwoohaan if you don't see an issue then we can close.
