### ISSUE TITLE
LG Editor: Adaptive Card template comment causes LG errors.

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#5872]
Use the LG Editor to add an Attachments tab to a response and then create an attachment, selecting the Adaptive Card template.  At this point, if a user does not replace the template content with an adaptive card JSON they have multiple LG errors.  

Is there a way we can have the Adaptive Card template either be valid at the outset or maybe some form of placeholder instead?

**Comment by hatpick** [comment]
@tdurnford can you look into this?
