### ISSUE TITLE
LG Editor: Pre-Built functions should be shown alphabetically

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#5873]
The pre-built functions list shown when you choose the functions helper on the LG editor shows a long list of functions.  Currently they don't appear to be in any sort of order, making them potentially hard to locate.  We should re-order the main and sub menus to be displayed alphabetically.

Note, if we take this then we should also update the functions list shown as a dropdown when editing conditions.

**Comment by hatpick** [comment]
The list of functions was not created for this feature, it exists as a separate package and there are some other consumers of this package. The order in which the functions appear in that list is provided by that package (@bfc/built-in-functions) and I'm not sure if we have to sort them alphabetically.

**Comment by garypretty** [comment]
@hatpick as discussed can we find out if there is a specific reason they are in the order they exist in today.  If not then I believe we should update the package to list them alphabetically.

**Comment by hatpick** [comment]
@garypretty I did and it turns out the order is somewhat random, so I sorted them alphabetically.
