### ISSUE TITLE
LG Editor: Update Break and Prosody SSML snippets to contain default values

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#5876]
Update the inserted SSML for Break and Prosody snippets to contain default values. I have agreed this approach with @Quirinevwm 

**Break tag:** <break strength="medium" />
**Prosody tag:** <prosody pitch="medium"></prosody>

**Rationale for change:** Break tag in many cases will be left at medium, this reduces effort for the user. The time attribute currently added is optional, so let's remove it. For prosody, the above will leave the pitch at the default level, but adding a default value improves discoverability of the type of value required and also means we insert valid SSML from the get go.

**Comment by hatpick** [comment]
Currently, here's what is inserted for each SSML tag from menu:
Break: <break strength="medium"/>
Prosody: <prosody pitch="medium" rate="medium" volume="medium"></prosody>
Audio: <audio src="url"/>
I dont understand the issue, can you elaborate?

**Comment by garypretty** [comment]
@hatpick I must have been using an older build when I made a note of this issue. Closing out.
