### ISSUE TITLE
UX issues / observations for integrated webchat and debug panel

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#5877]
Below are a list of UX issues / observations following my initial round of testing of integrated web chat / debug panel.

**Integrated web chat**

1. Bot Manager still only contains a link to emulator, Given that folks likely visit here today to open the emulator, there should be a link here to open the integrated web chat for the root bot.

2. We should disable the text input at the bottom of the integrated web chat panel when the root bot is not running.

3. More of a general point - the bot manager describes itself as a place where you can start / stop your bots, but the statuses we show are 'Running' and 'Inactive'.  If a bot is not running, we should rename the status 'Inactive' to 'Stopped' to be more consistent and explicit about the current state of the application.

**Debug panel**

1. Debug panel should be vertically re-sizable.

2. We currently have an Issues tab on the left of the debug panel.  When the panel is open we show an X to allow the user to collapse it.  Can we add an up arrow icon to the far right of the panel when collapsed to allow the user to open it (and also potentially make it more discoverable that it does open?  Additionally if a user clicks / double clicks the panel outside of a specific tab we should open it to the first / last open (if possible) tab.

3.  I don't think it is immediately obvious that the Issue tab when the panel is collapsed is clickable.

4. The icons showing counts of Errors / Warnings in the top right hand corner are bright and pretty distracting when editing and you have no errors, meaning they can also fade into the background when you do have errors and need to spot them.  Can we hide the counts / icons if you have no errors / warnings?  I know that in the next milestone we will likely move these down to a status bar, but I think making this small change would be beneficial even just for R12.

**Comment by srinaath** [comment]
Bot Manager still only contains a link to emulator, Given that folks likely visit here today to open the emulator, there should be a link here to open the integrated web chat for the root bot. - Malanie's design awaitng

**Comment by yeze322** [comment]
The debug panel part is tracked in #5928
