### ISSUE TITLE
nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by zhnbss** [microsoft/BotFramework-Composer#5891]
## Version

**BotFramework Composer: 1.3.1 (also 1.3.0)
Bot Framework Emulator: 4.11.0**

## Browser

- [x] Chrome
- [x] Firefox

## OS

- [x] macOS
- [x] Windows

## To Reproduce

1. Fire up BotFramework Composer with _yarn startall_
2. Open the bot from BotFramework Composer
3. Start the bot and open in Bot Framework Emulator
4. Observe instead of showing greeting message, it shows - "**nodename nor servname provided, or not known**"

## Screenshots

![image](https://user-images.githubusercontent.com/6408481/108824734-5c71d000-75c2-11eb-99e2-71d0351e5091.png)

## Message JSON

```json
{
  "channelId": "emulator",
  "conversation": {
    "id": "d64185f0-75b9-11eb-aba4-3b893e2b136f|livechat"
  },
  "from": {
    "id": "bee9bd70-75b2-11eb-aba4-3b893e2b136f",
    "name": "Bot",
    "role": "bot"
  },
  "id": "d6c5aa10-75b9-11eb-8ca6-f76c2ea61a34",
  "inputHint": "acceptingInput",
  "localTimestamp": "2021-02-23T10:30:59+01:00",
  "locale": "en-US",
  "recipient": {
    "id": "0d645ce4-0aea-4efd-a619-3674213f8af0",
    "role": "user"
  },
  "replyToId": "d64be630-75b9-11eb-8ca6-f76c2ea61a34",
  "serviceUrl": "https://2f032398282e.ngrok.io",
  "text": "nodename nor servname provided, or not known",
  "timestamp": "2021-02-23T09:30:59.761Z",
  "type": "message"
}
```

**Comment by cwhitten** [comment]
@zhnbss are you trying to build and run Composer from source, or use the desktop application? If the later, please follow the instructions here: https://docs.microsoft.com/en-us/composer/install-composer#install-composer-as-a-desktop-application

If the former, can you send any stdout information in your Composer server process in the terminal where you executed `yarn startall` ?

**Comment by zhnbss** [comment]
Found the error. It was an internal issue where the CosmosDB was wrongly configured.
Because of the dubious error message, it took a long time to find the error
