### ISSUE TITLE
Can't set hostname on Configure Resources in Publishing

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#5893]
## Describe the bug

Can't set hostname on the Configure Resources screen in publishing process.  You get the error below no matter what text you enter.
![image](https://user-images.githubusercontent.com/18688053/108866929-4b24c580-75ba-11eb-9e03-edc0de5c6484.png)

## Version

Version:  1.3.1-nightly.216473.93194e8

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Try to create a publishing profile
2. When you get to the Configure Resources screen you will not be able to set a hostname that will allow you to go to the next step.

## Expected behavior

Ability to set hostname and move forward through the process

**Comment by darrenj** [comment]
Reproed on Windows too

![image](https://user-images.githubusercontent.com/33519520/108911064-a7213580-761e-11eb-96a5-a69b8f9178a5.png)

**Comment by darrenj** [comment]
I think we should explore this further, why would we not provide an auto-generated prefix (we did this with VA) but of course provide the ability for a customer to modify as they see fit? (@emivers8)

**Comment by luhan2017** [comment]
This hostname bug is fixed in #5741
