### ISSUE TITLE
Check boxes disappear when unchecked

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#5894]
## Describe the bug

Currently, today when you are selecting resources to be provisioned, if you uncheck an item the checkbox disappears.  This is confusing and if you unselect all it is hard to tell that you have the option to check the box to make them get provisioned.  We need to make this more clear.
![image](https://user-images.githubusercontent.com/18688053/108864701-1152bf80-75b8-11eb-9ea0-14b92c745ae1.png)

## Version
1.4

## Browser

- [X] Electron distribution
- [X] Chrome
- [X] Safari
- [X] Firefox
- [X] Edge

## OS
- [X] macOS
- [X] Windows
- [X] Ubuntu

## To Reproduce

1. Open Bot Project
2. Click on Publish on the left menu
3. Click dropdown under Publish Target for you Bot
4. Select Manage
5. Under Publish Profiles Click Add new
6. Enter Name and select Web App option
7. Click Next: Configure Resources
8. Authenticate to Azure (if needed)
9. Select Create new Azure Resources
10. Select Subscription
11. Fill in Resource Group name, Hostname, select region
12. Click Next: Review
13. Proceed to the Resources that you want to select and unselect all.
14. All check boxes disappear

## Expected behavior

It should be more apparent that I see what is selected and not selected.  As well as I should be able to easily see that I can re-select items.

**Comment by Dewain27** [comment]
According to @emivers8 this is just a setting that needs to be changed in the component.

**Comment by JaskeeratBedi-cmk** [comment]
![Screen Shot 2021-02-24 at 3 38 20 PM](https://user-images.githubusercontent.com/67944302/109080980-5a893900-76b6-11eb-8897-3a740163c130.png)

@Dewain27 we already pre-select the resources that are optional to the user, so that the check boxes in the list are visible. This is the list pattern that Fluent uses, wherein if the user selects out the check box becomes invisible, but appears when user hovers back on the list.

**Comment by emivers8** [comment]
There IS however an option to always show the checkboxes on the existing component. This is not considered custom, it's an allowed variation.

This is the relevant attribute:
![image](https://user-images.githubusercontent.com/55601267/109370928-46c90880-7857-11eb-8322-ffb7f7f9dd34.png)

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist

(@benbrown implemented this variation on a previous version of package manager so he might be able to provide more details.)
