### ISSUE TITLE
Publish to PVA is successful however a failure is being reported in the notifications panel

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#5899]
## Describe the bug

Publishes to PVA are successful however an error is being send to the global notifications panel.

## Version

1.3.1-nightly.214464.b82bb3b

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Publish to PVA
2. See error in panel
3. See publish was successful

## Expected behavior

If the publish is successful it shouldn't show an error.

## Screenshots

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1156704/108896636-07d25300-75ca-11eb-81b8-c1083280e426.png)

**Comment by tonyanziano** [comment]
I was able to reproduce this issue locally. I will investigate

**Comment by hibrenda** [comment]
Actually I hit this before. no matter the publish target (even for webapp), I got the error but publish process is success
