### ISSUE TITLE
Clicking on an orphaned skill in the project tree returns a blank screen

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#5900]
## Version

1.3.1-nightly.216473.93194e8

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Connect a skill
2. Move the solution around
3. See opacity and red icon
4. Click on the element
5. See error

## Expected behavior

It shouldn't be intractable beyond the warning icon that explains the issue.

## Screenshots

<img width="834" alt="Screen Shot 2021-02-23 at 11 43 10 AM" src="https://user-images.githubusercontent.com/1156704/108898913-a65fb380-75cc-11eb-9e7b-e3ea3ccc7f71.png">

**Comment by cosmicshuai** [comment]
verified
