### ISSUE TITLE
Hide Custom Recognizer as an option in the Recognizer dropdown in PVA mode

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#5901]
![Screen Shot 2021-02-23 at 11 53 30 AM](https://user-images.githubusercontent.com/1156704/108899878-cb085b00-75cd-11eb-80bb-25c251fe3439.png)

**Comment by yeze322** [comment]
@cwhitten The `Custom Recognizer` is not a SDK $kind, it's a preserved option for creating arbitrary Recognizer by inputting json.

Do you think we can remove it in both Composer and PVA since we already have the 'recognizer' uischema?
