### ISSUE TITLE
Problems/webchat panel shows up on top of some pages

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#5902]
## Describe the bug

See the screenshot; the Project and App Settings pages cause the "Problems/Webchat Inspector" pane to detach from the bottom of the window and float along with part of the page itself, getting in the way of other elements.

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Start up Composer
2. Open a bot
3. Look in the Project Setting or App Settings pages.

## Expected behavior

These tabs should show up at the bottom of the screen in all of the pages; this works fine in the Design, LG, and LU pages. 

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/108902821-6cdd7700-75d1-11eb-8efd-11e4f3dac03d.png)

**Comment by srinaath** [comment]
This is fixed on the latest main.
