### ISSUE TITLE
None of the properties in the Advanced Settings View are allowed

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#5905]
## Describe the bug

In the Advanced Settings View, all the properties at the root level are underlined in yellow and the tooltip says the properties aren't allowed.

## Version

1.3.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Project Settings'
2. Click on 'Advanced Settings View (json)'
3. Mouse over the properties underlined in yellow

## Expected behavior

Composer should recognize the properties as valid

## Screenshots

![image](https://user-images.githubusercontent.com/41968495/108909019-d9a83f80-75d8-11eb-8d3c-c484363ff638.png)

**Comment by srinaath** [comment]
@boydc2014 

At a minimum we need to resolve a bug here as the entire SDK schema is supplied to the Settings component. 

What do we think about supplying a schema for the settings or pushing a change to create one as the right fix for the ticket.

![](https://user-images.githubusercontent.com/13004779/109195263-27df4f00-774f-11eb-8200-980548028dc7.png)
