### ISSUE TITLE
There does not appear to be a way to cancel a skill from the root bot

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#5911]
## Describe the bug

There should be an action for canceling the current skill.
- This should send an `endOfConversation` activity to the skill.
- Allow the bot developer to set the `code` and `value` properties on the outbound activity.
- Upon acknowledgement from the skill, clear the _active skill_.

## Version

                Bot Framework Composer

                Version:  1.3.1-nightly.216473.93194e8
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a root bot and a skill.
1. In the root bot, create a _cancel_ trigger. (You should be able to do this cleanly by adding a prompt to the skill where the prompt allows interruptions.)
1. Error: Try to find an appropriate action to add to the trigger for canceling the skill. Neither **End this dialog** nor **Cancel all active dialogs** does the right thing here.
    - If you start a multi-step skill and try to cancel it with either of these actions and then start what should be a new conversation with the skill:
      1. ~~No `conversationUpdate` activity is sent to the skill.~~ ([jf] Irrelevant to this issue.)
      2. The skill continues from whichever step it was at when you tried to cancel it.
    - This appears to indicate the the old root-skill conversation never ended and is resuming when you _start_ the skill after canceling it.

## Expected behavior

- You should be able to cancel a skill from the root, which should terminate the existing root-skill conversation, losing (by design) any associated conversation state.
- When you start a new conversation with the skill, it should be in a new, clean root-skill conversation.

## Screenshots

![image](https://user-images.githubusercontent.com/35047199/108916731-84bdf680-75e3-11eb-98ec-55c1d259b6fd.png)
![image](https://user-images.githubusercontent.com/35047199/108916756-8edff500-75e3-11eb-8310-e32724989b7c.png)

## Additional context

I would expect the the cancel or end skill action to be under the **Access external resources** menu, as that is where the _connect to a skill_ action appears.

**Comment by luhan2017** [comment]
@JonathanFingold did you try to cancel a skill by sending a cancel message/event to the skill, and add a trigger in the skill dialog to end Conversation.

**Comment by JonathanFingold** [comment]
@luhan2017 - I have not, but that seems like extra work, as this is already part of the SDK implementation, through the SkillDialog. Following up "offline" via email.

**Comment by JonathanFingold** [comment]
@luhan2017 - The only way I've discovered so far for canceling the skill from the root bot is to use a **Cancel all dialogs** action, which has a lot of unwanted side effects. I can't figure out how to send an arbitrary action to the skill from the root bot after the skill is started.

**Comment by luhan2017** [comment]
@JonathanFingold this seems like a SDK issue, @srinaath, should we transfer this issue to SDK?

**Comment by JonathanFingold** [comment]
This really depends on how the conversational core handles conversations between a skill consumer and a skill.
- If it does so through a SkillDialog instance, which I would expect to be the preferred way, then this is an implementation issue in Composer or the conversational core.
- Otherwise, you may need the SDK to surface a separate activity for cancelling the active skill.

@gabog Do you have any insight into this?
