### ISSUE TITLE
LG content update doesn't accept empty string for existing template

### ISSUE THREAD

**Issue by hatpick** [microsoft/BotFramework-Composer#5913]
When updating an existing template, the updater replaces passed empty string body with the current body of the template leading to not being able to update the body to an empty string.

in:
```packages/lib/indexers/src/utils/lgUtil.ts#L101```
the following line replaces the empty string value:
```body: body || originTemplate?.body || '',```

**Comment by hatpick** [comment]
@lei9444 can you help me with this? Is this something intentional?

**Comment by boydc2014** [comment]
@zhixzhan can you review the intention and see if it still works

**Comment by zhixzhan** [comment]
@boydc2014 @hatpick I checked again, this line is originally added to all do partial update on a template,
for example,if call this method with parameter `{ name }`, will do update template with name and origin body.

but it should be more precisely like：
```
body: typeof body === undefined ? originTemplate?.body || '' : body,
```
