### ISSUE TITLE
Documentation / sample: Show how to invoke skills with different type calls in LG

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5914]
Need to document how to set up LG to call skills passing different payload using Invoke, Event, or message.

e.g.

```
# Skill_Invoke
[Activity
  description = Skill Invoke Test (description)
  name = IntentTest
  type = invoke
]

# Skill_Event
[Activity
  description = Skill Event Test (description)
  name = IntentTest
  type = event
]

# Skill_Message
- Simple message 
```

This is a combination of [skills](https://docs.microsoft.com/en-us/azure/bot-service/skills-write-manifest-2-1?view=azure-bot-service-4.0), and [structured response](https://docs.microsoft.com/en-us/azure/bot-service/language-generation/language-generation-structured-response-template?view=azure-bot-service-4.0) in context of Composer.

**Comment by JonathanFingold** [comment]
@scheyal , @zxyanliu , I don't think this is a doc issue. As far as I can tell, **type** cannot be specified (currently) and is always assumed to be "message".
