### ISSUE TITLE
Debug Panel UX improvements

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotFramework-Composer#5918]
## Describe the bug
This issue is for tracking todo items of Debug Panel according to feedbacks.

#### Bugs @alanlong9278 
- [x] https://github.com/microsoft/BotFramework-Composer/issues/5916 Debug panel resize breaks the hide/show behaviour
- [x] https://github.com/microsoft/BotFramework-Composer/issues/5915 Debug panel resize interaction selects texts in the rest of the UI 
- [x] [Diagnostics Table] 'Location' column will be truncated if the path is too long
- [ ] The "problems" pane is floating incorrectly on the app settings page and maybe others
- [x] 'Settings' with Debug Panel
- [x] Diagnostics List - 'Bot' column's header is not queried from projectId - it's always current project name

#### UX
- [x] Adding a chevron instead of X mark to expand, contract debug panel. (^ and V)
- [ ] Single clicking on the Debug panel header should set the Debug Panel in an expanded state
- [ ] The font needs to the same font size as the font used in LG editor, Show Code
- [ ] with the ability to sort ascending/descending order by bot name
- [x] Font sizes of severity filter / tab header -> 12px
- [x] Hide the widget if errors count =0 and warnings = 0. Embed the widget in all pages that contain the Debug Panel. 
<img width="243" alt="Screen Shot 2021-02-23 at 8 13 27 PM" src="https://user-images.githubusercontent.com/13004779/108947150-bc916200-7614-11eb-984a-73b2b401b02f.png">

#### State management @yeze322 
- [x] Diagnostics tab shows all projects' errors
- [x] The error indicator inside the debug panel tab header needs to be (10px * 10px). 
- [ ] Error indicator on panel tab header needs to vanish when new erros are read. Similar to 'Unread message' UX.

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by srinaath** [comment]
@zhixzhan  can u make sure as a part of the font changes u apply this font inside the Webchat Inspector panel

**Comment by garypretty** [comment]
@yeze322 Just to check, if there are no errors, but 1 or more warnings, we will only show the warning icon / count in the top right?

**Comment by srinaath** [comment]
@garypretty  thats correct. If warning ct > 0 it shows that button. If errorCt>0 the same way.

[fix: debug panel UX improvements by alanlong9278 · Pull Request #5928 · microsoft/BotFramework-Composer (github.com)](https://github.com/microsoft/BotFramework-Composer/pull/5928/commits/be576eb4c0b90003e75db7f9ae1a7d3914aa51bf)

**Comment by yeze322** [comment]
@garypretty @srinaath it will show both Error and Warning button.
For example 1 Error, 0 Warning

**Comment by zhixzhan** [comment]
> @zhixzhan  can u make sure as a part of the font changes u apply this font inside the Webchat Inspector panel. [fix: debug panel UX improvements by alanlong9278 · Pull Request #5928 · microsoft/BotFramework-Composer (github.com)](https://github.com/microsoft/BotFramework-Composer/pull/5928/files#diff-a1a2955d26ab3b92cdcd82be7ad48c19c89056515ae23c9b28a47a491729e7ddR18)

font applied in #5926
