### ISSUE TITLE
Empty screen for editing resources

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5921]
## Describe the bug
I get an empty screen when I try to edit a publishing profile
![Kapture 2021-02-23 at 20 19 47](https://user-images.githubusercontent.com/67944302/108947100-a7b4ce80-7614-11eb-9d6f-396150c32b72.gif)

## Version

Release: 1.3.1
## Browser

- [ ] Electron distribution

## OS

- [ ] macOS

## To Reproduce

1. Click on edit button next to existing publishing profile
2. Click Next button: Configure resources
3. Empty screen

**Comment by luhan2017** [comment]
@JaskeeratBedi-cmk which electron version are you using? we already fixed this issue in the latest version, could you try this? https://fuselabs.visualstudio.com/Composer/_build/results?buildId=216835&view=results

**Comment by luhan2017** [comment]
fixed in #5741.
