### ISSUE TITLE
Add resource page missing information

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5922]
## Describe the bug

![Select resources](https://user-images.githubusercontent.com/67944302/108948783-fdd74100-7617-11eb-8e7b-dd85f2091ed6.jpg)

## Version
 R1.3.1

## Browser

- [ ] Electron distribution

## OS

- [ ] macOS

## Expected behavior

Discrepancy in design file and executed screen.
Design file here: 
https://www.figma.com/file/J3oIdXDmeBQbAe4a4PYbQc/Jaskeerat-s-files?node-id=4934%3A77186

**Comment by VanyLaw** [comment]
fix in https://github.com/microsoft/BotFramework-Composer/pull/5741
