### ISSUE TITLE
Review & create page missing information and visual formatting

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5923]
## Describe the bug

![Review   create](https://user-images.githubusercontent.com/67944302/108949281-f82e2b00-7618-11eb-8b4d-d6a21f427475.jpg)

## Version

R 1.3.1
## Browser

- [ ] Electron distribution

## OS

- [ ] macOS

**Comment by luhan2017** [comment]
@JaskeeratBedi-cmk , here is the Review&Create page in the latest main branch. I saw two differences
- in the design, the subscription is listed there, do we still want to show that, it will take extra space. 
- The resource type name is different with the design, but I think it is the official name 
Do you think the current UX is fine? Anything else needs to be updated? 

![image](https://user-images.githubusercontent.com/32191031/110261972-1dde0b80-7fed-11eb-8eb5-6df897563135.png)

**Comment by JaskeeratBedi-cmk** [comment]
We can leave out the subscription.
The body copy is still missing, under the header "Review & create". Other than that, looks good.
