### ISSUE TITLE
Provisioning failed: Bot Registration Error_Bot name exists?

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5924]
<img width="1162" alt="Screen Shot 2021-02-23 at 8 53 54 PM" src="https://user-images.githubusercontent.com/67944302/108949456-4cd1a600-7619-11eb-9b97-15fd99b4f7f1.png">

## Describe the bug

Got this error when I tried to add a new provisioning profile and add new resources

## Version

R 1.3.1

## Browser

- [ ] Electron distribution

## OS

- [ ] macOS

## To Reproduce

Steps to add a new publishing profile & create new resources. Not sure why this error is triggered.

## Expected behavior

The error message is long and unhelpful. The copy needs to be updated. Also, the message says that bot name is already registered to another bot application. Is this referring to Resource group name, bot project name, Publishing profile name or Hostname?

The link in the error message is not clickable and not relevant to the error. The link takes user a generic FAQ (https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-bot-framework-faq?view=azure-bot-service-4.0) that does not tell the user what to do!

**Comment by VanyLaw** [comment]
It's failed when creating bot registration, I think that's because hostName is already had. Fix name checking in here https://github.com/microsoft/BotFramework-Composer/pull/5741.
