### ISSUE TITLE
ApplicationID and Password not populated post provisioning

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#5930]
AppId and Password are key to successful Bot development. As part of provisioning we create the AppId and Password as a required resource but after provisioning we don't set the AppId or Password in the Bot settings. This then requires the user to go find the provisioned Application, generate a new password (as you can't "see" an existing password) and then transpose into configuration.

Not having the AppId will cause problems down-stream too, for example if I want to convert my Bot to a skill I need an AppId and having this available to pre-fill would resolve skill related issues too. Bottom line Skill connection and make a skill require an AppId so if not present we need to trigger provisioning flow. (They may be other scenarios too)

## Version

1.3.1-nightly.216845.fdbc418

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new Echo Bot
2. Provision basic (required) resources (including app registration)
3. Observe that Bot configuration has blank entries for AppId and Password

## Expected behavior

- AppId and Password
- Also, features that require an AppId (e.g. Add Skill, or Create Skill manifest) should trigger provisioning of the Application Registration otherwise block use

**Comment by Dewain27** [comment]
![image](https://user-images.githubusercontent.com/18688053/112393523-388cd180-8cc9-11eb-84e4-4df5e1cbfa7a.png)

**Comment by Dewain27** [comment]
AppID is located in publishing profile properly, however in this area it seems that this either should have details as to why you would populate or removed.

**Comment by Dewain27** [comment]
Looking to resolve with R14 Bot Setting redesign as this setting is for the local development environment.  Confirmed that the Publishing profiles are populated with the proper content.
