### ISSUE TITLE
Package manager: add feed usability improvement

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/BotFramework-Composer#5934]
When I add a local feed, I enter a name and a url but don't hit the 'check mark' on the right. When I click close, my feed doesn't get added but I'm not notified, so me and a lot of bug bashers thought we'd added the custom feed but we needed to go back to 'add feed' and click the check mark on the right. Maybe the close button should check if there are unsaved changes and ask whether to apply / discard?

**Comment by benbrown** [comment]
![u7O59GTAEj](https://user-images.githubusercontent.com/729873/109225116-76f2a780-7782-11eb-9745-6d28662cd31a.gif)

for you
