### ISSUE TITLE
The reloadProject method does not properly reload the settings from the server

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/BotFramework-Composer#5935]
Repro steps in feature/adapters branch:

- Turn on package manager and new creation flow flags
- Create an empty bot with the template called 'Empty'
- Install a package with a bot plugin from a local nuget source (attached one example package, unzip in a folder and then make the local nuget source url be the absolute path to where you unzipped the attached file)
- Verify that plugin gets written to runtimesettings:plugins in the runtime app settings (<runtime dir>/settings/appsettings.json)
- Do not refresh the page, just go to bot configuration and configure the adapter + save
- bug: plugin was erased from app settings
[localnuget (4).zip](https://github.com/microsoft/BotFramework-Composer/files/6037842/localnuget.4.zip)

Expected:
```json
    "plugins": [
      {
        "name": "Bot.Builder.Community.Adapters.Alexa",
        "settingsPrefix": "Bot.Builder.Community.Adapters.Alexa"
      }
    ],
    "adapters": [
      {
        "name": "Bot.Builder.Community.Adapters.Alexa.AlexaAdapter",
        "enabled": true,
        "route": "alexatest"
      }
```
Observed:

```json
    "plugins": [    ],
    "adapters": [
      {
        "name": "Bot.Builder.Community.Adapters.Alexa.AlexaAdapter",
        "enabled": true,
        "route": "alexatest"
      }
```

**Comment by benbrown** [comment]
The root cause of the issue described by Carlos above is that the `reloadProject` method does not properly use the latest settings provided by the server.

@srinaath can point to the specific error in the code.

**Comment by srinaath** [comment]
[https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/client/src/recoilModel/dispatchers/project.ts#L468](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/client/src/recoilModel/dispatchers/project.ts#L468)

Essentially the fix that needs to be made is it continues to use the settings fetched from the server project data. Merge the sensitive settings that are present on the client for the project that got reloaded
