### ISSUE TITLE
Telemetry: Track Handoff from ABS / PVA

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#5937]
We need a way of tracking a telemetry event when Composer is opened from ABS or PVA (or any other source in the future).  Ideally when opened we would either

- add an additional property onto the existing session started / Composer opened event indicating the referrer if any
or
- we add a new event (named something like HandoffToComposerCompleted) where we add properties to indicate the referrer

For each referrer we may want to track additional properties from the data payload sent from the referrer.

**Comment by tdurnford** [comment]
@tonyanziano Is there anyway to determine if the user opened Composer from ABS or PVA in either the client or Composer's server?

**Comment by tonyanziano** [comment]
You could fire the event off [here in the `import` deep link handler](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/electron-server/src/utility/url.ts#L45), and use the `source` embedded in the URL to determine where it came from.
