### ISSUE TITLE
GET 500 when creating "Conversational Core" bot (new creation)

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/BotFramework-Composer#5938]
Using new creation experience, select "Conversation Core".  Eventually get a "500" error in Composer.  In the command prompt, it's from one of the GETS.

Looks like: 
```GET /api/status/6ec66669-0c29-49e1-acb9-1a923f13b15b 500 1.124 ms - -```

## Version

Latest from main.  Running local build.

Commit: ca41b20

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by sangwoohaan** [comment]
I also get this on Mac
GET /api/status/85baaa02-c76d-4b13-a732-df91a9dc9072 500 0.675 ms - -

**Comment by mewa1024** [comment]
I'm also getting this on Mac running Version:  1.3.1-nightly.217012.67a05de

**Comment by benbrown** [comment]
This is due to the fact that the conversational core packages required by this module are published in a private feed that Composer cannot access.

Once they are published publicly, this should work.

**Comment by benbrown** [comment]
@tracyboehrer @mewa1024 @sangwoohaan as these components are now all public,  this should now be fixed.  can you please give it another try?

**Comment by benbrown** [comment]
@tracyboehrer  can you confirm this is working in the nightly build?

**Comment by tracyboehrer** [comment]
@benbrown I can confirm that as of Friday with a build from main this now works.  I assume because the packages were published.

**Comment by benbrown** [comment]
thanks!
