### ISSUE TITLE
Provision failure: Resource group name 

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5949]
![Screen Shot 2021-02-24 at 3 21 28 PM](https://user-images.githubusercontent.com/67944302/109079766-447a7900-76b4-11eb-8178-ba6eced2cdbf.png)

## Describe the bug

I get this error after I have entered all details for creating a new publishing profile. While entering the 'Resource Group name' I do not get any error validation. Therefore, I do not know that in the future my provisioning will fail

## Version

R1.3.1

## Browser

- [ ] Electron distribution

## OS

- [ ] macOS

## To Reproduce

1. Go to project settings, click on add new publishing profile
2. Enter this in resource group name input filed - " Contoso app"
3. Fill the other inputs, hit done
4. You will get the error

**Comment by luhan2017** [comment]
This is already fixed in the latest main branch, just close it. 
![image](https://user-images.githubusercontent.com/32191031/110261816-a7410e00-7fec-11eb-9cec-eddc5a9c7d1a.png)
