### ISSUE TITLE
Blue text buttons' inconsistent hover states in LG Response editor

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#5952]
## Describe the bug

![Screen Shot 2021-02-24 at 4 23 10 PM](https://user-images.githubusercontent.com/50963385/109084814-5876a880-76bd-11eb-802d-178333e39dc8.png)
![Screen Shot 2021-02-24 at 4 23 13 PM](https://user-images.githubusercontent.com/50963385/109084879-78a66780-76bd-11eb-9499-f35476ea619f.png)

The blue input hint button's hover state is dark gray

![Screen Shot 2021-02-24 at 4 23 20 PM](https://user-images.githubusercontent.com/50963385/109084887-7cd28500-76bd-11eb-9912-b4e43cf64fcd.png)
The layout button in the Attachment tab is also dary gray

![Screen Shot 2021-02-24 at 4 23 13 PM](https://user-images.githubusercontent.com/50963385/109084939-91168200-76bd-11eb-94ca-332bb8c9f611.png)
![Screen Shot 2021-02-24 at 4 23 16 PM](https://user-images.githubusercontent.com/50963385/109084945-9378dc00-76bd-11eb-9165-7f4cbf83f133.png)
However, the 'switch to code editor' button's hover state's got a different color (245F8B) 

![Screen Shot 2021-02-24 at 4 24 46 PM](https://user-images.githubusercontent.com/50963385/109085003-b2776e00-76bd-11eb-8808-6c6483c39991.png)
And the 'Add new variation', 'Add an attachment', 'Add an action' buttons don't have a hover state.

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior

Let's unify the hover state color to 245F8B.

**Comment by hatpick** [comment]
@sangwoohaan 
We can add custom coloring to it but FYI they are different component from Fabric with their default hover state colors.
