### ISSUE TITLE
Debug panel issue

### ISSUE THREAD

**Issue by Danieladu** [microsoft/BotFramework-Composer#5958]
1. Overlay of the debug panel
![bug1](https://user-images.githubusercontent.com/7289268/109128429-75c57880-778a-11eb-9264-f602c50b405b.gif)

2.  Can not minimize the debug panel. Does it by design?
![bug2](https://user-images.githubusercontent.com/7289268/109128436-765e0f00-778a-11eb-9581-0375b99fa8ef.gif)

**Comment by srinaath** [comment]
@Danieladu  this will be resolved once [fix: debug panel UX improvements by alanlong9278 · Pull Request #5928 · microsoft/BotFramework-Composer (github.com)](https://github.com/microsoft/BotFramework-Composer/pull/5928) is merged. Most likely tomorrow's nightly.

**Comment by yeze322** [comment]
closed by #5928
