### ISSUE TITLE
Unclear which C# runtime to get

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/BotFramework-Composer#5966]
## Describe the bug

When obtaining the custom runtime via the settings page. There are two C# runtime available to choose from without detail. It's unclear which to choose from

## Version

                Bot Framework Composer

                Version:  1.3.1-nightly.217293.c1e5de3
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to "Project Settings"
2. Go to "Custom Runtime" section
3. Enable "Use custom runtime"
4. Click "Get a new copy of the runtime code"

## Expected behavior

Clear about which C# runtime is available

## Screenshots

![image](https://user-images.githubusercontent.com/9922190/109199690-9a066280-7754-11eb-8bad-b72121bc127b.png)

**Comment by yeze322** [comment]
@luhan2017 @VanyLaw @benbrown

**Comment by luhan2017** [comment]
@pavolumMsft，this seems be introduced by the new adaptive runtime. is this expected?

**Comment by benbrown** [comment]
This should have been resolved by #6020 - @thomas-chung if you experience this using the most recent nightly, please re-open this.
