### ISSUE TITLE
1 pixel gaps in many places

### ISSUE THREAD

**Issue by sangwoohaan** [microsoft/BotFramework-Composer#5967]
## Describe the bug

There are 1 pixel gaps and stroke misalignments in various places.

**In the Design view**
![Frame 616431](https://user-images.githubusercontent.com/50963385/109212377-4bf95b00-7764-11eb-85ea-e1b1e889145f.png)

**In the project tree**
![Frame 616441](https://user-images.githubusercontent.com/50963385/109212421-5c113a80-7764-11eb-84b5-0fdae4969893.png)

**In the left navigation in other views**
![Frame 61646](https://user-images.githubusercontent.com/50963385/109212461-69c6c000-7764-11eb-85ed-9ed06bb65caa.png)

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior

Let's close the gaps!

**Comment by tonyanziano** [comment]
@GeoffCoxMSFT can you take a look at the gaps being caused by the resizer component's hit target?

**Comment by GeoffCoxMSFT** [comment]
@tonyanziano This is by design with the default splitter.  If Composer shouldn't have a line thinner than the splitter hit area, then a solid splitter needs to be substituted in.
