### ISSUE TITLE
Error and warning counter at top of page should be for all bots in the project

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5971]
## Describe the bug

The error and warnings counter in the upper right corner should be global, rather than scoped to the bot that is selected in the project tree. If it is scoped, it hides errors that are in other bots/skills.

## Version

Version:  1.3.1-nightly.217293.c1e5de3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot project with multiple bots.
2. Create some kind of error in a non-root bot.
3. Select the non-root bot.

The error counter will be 0, but the Start button is disabled because a bot that is not selected contains an error:

Error is not appearing in the counter (because it is not in the currently selected bot)
<img width="1920" alt="Screen Shot 2021-02-25 at 1 00 35 PM" src="https://user-images.githubusercontent.com/39317542/109219052-0b054480-776c-11eb-85e9-a7384e42730a.png">

When I select the right bot, I see that there is an error.
<img width="1920" alt="Screen Shot 2021-02-25 at 1 01 32 PM" src="https://user-images.githubusercontent.com/39317542/109219194-23755f00-776c-11eb-9049-232fb08d5444.png">

## Expected behavior

The counter should count all the errors and warnings in the project.

**Comment by yeze322** [comment]
The new bug fix branch is not included in this build, it will be updated in #5918
