### ISSUE TITLE
Design change request: Remove error/warning indicators when none present (don't show 0)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5972]
I think this UI is unecessarily alarming about nothing. If no errors or warnings, why present alarming icons?

![image](https://user-images.githubusercontent.com/8867670/109222993-de066100-776e-11eb-8a75-efd40c41890f.png)

**Comment by yeze322** [comment]
yes, we do have a design update on that.Addressed in #5928
