### ISSUE TITLE
Bot Manager is missing link to Learn more when a bot fail to run

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5973]
## Describe the bug

The Bot Manager drawer does not provide a link for more information when your bot fails. Previous versions did include a link.

## Version

Version:  1.3.1-nightly.217293.c1e5de3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot project.
2. Start all bots.
I get this message in the bot manager when the bot has fails to start:
![image](https://user-images.githubusercontent.com/39317542/109223240-32a9dc00-776f-11eb-99ef-51b2773c3249.png)

Previously, the bot manager would provide a link to show the error details and clicking on the link would show more information about the error:

![image](https://user-images.githubusercontent.com/39317542/109223622-b19f1480-776f-11eb-93c8-4ac8caba913b.png)

## Expected behavior

I expected there to still be a link for more information about the error. (The formatting and content of the details might still need work, but I think it was better than no information at all.)

**Comment by srinaath** [comment]
Great catch @mewa1024 . Minor regression introduced in my PR before.
