### ISSUE TITLE
Bugbash (private): Eject runtime, eject again - prompt ask to stop runtime but runtime not started

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5974]
If you click to eject runtime, then uneject, re-eject you get a prompt suggesting to stop runtime. But I'm not aware of runtime starting (what does it mean for a runtime to start other than the bot running)? Bot was never run at this point.

![image](https://user-images.githubusercontent.com/8867670/109223605-aa780680-776f-11eb-9d22-9048eeaa40c8.png)

**Comment by tonyanziano** [comment]
@sangwoohaan could you help polish the copy for this? Stop / starting the runtime might be misleading, since it is more like deleting and replacing the runtime.

**Comment by mewa1024** [comment]
Closing since no longer relevant in Composer 2.
