### ISSUE TITLE
Bug Bash v1.3.1 - restart bot fails - no detailed errors

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#5981]
## Describe the bug

Using ToDoLuisSample with multilingual, it worked.  However, when adding Orchestrator recognizer, I restarted bot and it fails.
Building the `azurewebapp` manually works:
```
cd ToDoBotWithLuisSample-Multilang\runtime\azurewebapp
dotnet build
```
Also, `dotnet run` also works (and I can hit the bot in the emulator).

## Version

v1.3.1 

## Browser

- [X ] Electron distribution

## OS
- [X] Windows

![image](https://user-images.githubusercontent.com/6182197/109229086-acde5e80-7777-11eb-9857-927082b4ca36.png)
![image](https://user-images.githubusercontent.com/6182197/109229140-be276b00-7777-11eb-9052-e194d3e8aecc.png)

**Comment by srinaath** [comment]
Fixed by #6000
