### ISSUE TITLE
Bugbash(private): common.lu is not showing up in editor or triggers, but it is on disk

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#5982]
Build: Private daily (Tai)

Scenario: 
* Use & import common.lu in dialog \[import]\(.language-understanding/en-us/common.lu)
* Import entry shows empty in editor, triggers are also empty
* File on disk looks good.
* This worked on 1.3.1 (no change in bot, just updated composer build).

![image](https://user-images.githubusercontent.com/8867670/109229048-a18b3300-7777-11eb-8bab-9babc817d1f8.png)

![image](https://user-images.githubusercontent.com/8867670/109229125-b962b700-7777-11eb-9cb4-afa6ac154282.png)

![image](https://user-images.githubusercontent.com/8867670/109229227-da2b0c80-7777-11eb-8c73-acead5ea495a.png)

**Comment by boydc2014** [comment]
@scheyal is this common.lu added manually by you, or generated by composer? 

We will fix the file discovery issue, while at the same time can you try rename to common.en-us.lu? since it's in en-us folder?
