### ISSUE TITLE
v1.3.1- Publish bot to PVA not working

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#5985]
![publish to PVA](https://user-images.githubusercontent.com/67944302/109230598-f760da80-7779-11eb-8203-85d36155ee27.gif)

## Describe the bug

When I select Publish target as PVA and hit next I get an blank screen with a loader but nothing happens.

## Version

v.1.3.1

## Browser

- [ ] Electron distribution

## OS

- [ ] macOS

**Comment by luhan2017** [comment]
@tonyanziano, this issue also happens in the main branch before we merge the abs and provision v2 feature. Could you please help take a look?

**Comment by tonyanziano** [comment]
I can reproduce this locally. It looks like there was a regression, and it might be due to the new extension build updates. Investigating.
