### ISSUE TITLE
Bugbash v1.3.1 - can we have a way to cancel bot startup (cancel/stop button)?

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/BotFramework-Composer#5986]
For orchestrator based bot with large language model size, it takes quite a while to start a bot, while this is happening, Composer is basically stuck in that state and there is no way to cancel it to pick a different bot or change settings, etc.

Would be nice to have a way to cancel bot starting process.

**Comment by boydc2014** [comment]
@sangwoohaan can you comment on the UX, whether we want to make bot start cancelable or make bot start not blocking UI

**Comment by sangwoohaan** [comment]
Is possible / okay to abort the bot starting process? If that's so I can take a look into this.
