### ISSUE TITLE
Copy updates for creation modal

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#5987]
## Describe the bug

1) Should say "Select a template" rather than "Choose a template for your bot".
2) Description copy should have a period at the end.

## Version

v1.3.1 special creation release

## Browser

- [ ] Electron distribution

## OS

- [ ] macOS

## Screenshots

![image](https://user-images.githubusercontent.com/55601267/109232698-91765200-777d-11eb-9cbc-1744709cee66.png)

**Comment by benbrown** [comment]
good eye, @emivers8! fixed as part of #5983
