### ISSUE TITLE
"Start bot" buttons says "Restart bot" even when all bots have failed

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#5989]
## Describe the bug

When I have a bot project that has multiple bots, the start bot says "Start all bots". If all my bots fail, the button changes to "Restart all bots (0/x running)". At a glance, this implies that some bots in my project are running.

## Version

Bot Framework Composer

Version:  1.3.1-nightly.217293.c1e5de3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open any bot with multiple bots.
2. Click on 'Start all bots'.

If all my bots have failed, the Bot manager opens and the button changes to say "Restart all bots (0/x running)"
![image](https://user-images.githubusercontent.com/39317542/109234754-20389e00-7781-11eb-99cf-a794bfd0b8c8.png)

Since no bots are running, it would be clearer to leave the "Start all bots" button as "Start all bots.

**Comment by mewa1024** [comment]
Sorry--I just noticed that it happens with single bots too:
![image](https://user-images.githubusercontent.com/39317542/109234982-a0f79a00-7781-11eb-96ff-365b9892e6c1.png)

When I close the bot manager, the button still says "Restart bot" implying that the bot is running, but it is not.

**Comment by srinaath** [comment]
Fixed by [fix: Bot Controller style fixes by srinaath · Pull Request #6000 · microsoft/BotFramework-Composer (github.com)](https://github.com/microsoft/BotFramework-Composer/pull/6000/files)
