### ISSUE TITLE
Bugbash V1.3.1 pass Composer debug flag to Orchestrator lib

### ISSUE THREAD

**Issue by hcyang** [microsoft/BotFramework-Composer#5990]
Composer can enable debugging mode. Expect that flag passing to underneath bf-orchestrator library.
Currently that can be done by the statement below. bf-orchestrator should expose a method for that instead of a variable flag.

Utility.toPrintDebuggingLogToConsole = true;

**Comment by cwhitten** [comment]
See https://github.com/microsoft/BotFramework-Composer/issues/5461 for another ask
