### ISSUE TITLE
Bugbash v1.3.1 Composer UI will become frozen if it runs some long, intense task, such as calling bf-orchestrator to create a large snapshot file

### ISSUE THREAD

**Issue by hcyang** [microsoft/BotFramework-Composer#5993]
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by boydc2014** [comment]
dup to #5986
