### ISSUE TITLE
Bugbash v1.3.1 Composer cache Orchestrator base models to a default C: drive location. Please make the location configurable to other drive as C: drive can be small and valuable.

### ISSUE THREAD

**Issue by hcyang** [microsoft/BotFramework-Composer#5994]
Composer cache Orchestrator base models to the location below, which is usually in the C: drive. Please make the location configurable to other drive as C: drive can be small and valuable.

%APPDATA%\BotFrameworkComposer\models

**Comment by mewa1024** [comment]
@hcyang is this still an issue? Is the Orchestrator model still being saved to %APPDATA%\BotFrameworkComposer\models?

**Comment by hcyang** [comment]
> @hcyang is this still an issue? Is the Orchestrator model still being saved to %APPDATA%\BotFrameworkComposer\models?

@taicchoumsft, please comment.

**Comment by taicchoumsft** [comment]
Yes this is still an issue, should be easy to add this.  Will add this to R15.
