### ISSUE TITLE
Unable to send response as well as use many other features 

### ISSUE THREAD

**Issue by rahul-8437008949** [microsoft/BotFramework-Composer#5998]
## Describe the bug
Whenever i try to write anything in the send response dialog or bot responses a message comes to screen whuch says (Something went wrong)
![Screenshot 2021-02-26 095638](https://user-images.githubusercontent.com/54345729/109256499-1dd75200-781c-11eb-84e0-1ac80b031cf2.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Screenshots
Added screenshot

**Comment by congysu** [comment]
Thanks @taicchoumsft to take a look first.

**Comment by taicchoumsft** [comment]
@rahul-8437008949 , thanks for the bug report.  Can you help us collect some logs? This would really help.

1) Open a `CMD.exe` command prompt
1) Navigate to the install location and run Composer directly. On windows:
      - `cd %USERPROFILE%\AppData\Local\Programs\Bot Framework Composer\`
      - Set debugging log on for Composer: `set DEBUG=composer*`
      - run Composer: `./Bot Framework Composer.exe`
      - Trigger the bug and paste the exception logs here

Thanks again @rahul-8437008949

**Comment by congysu** [comment]
@cwhitten @taicchoumsft please feel free to re-assign this issue.  Thank you both.

**Comment by EricDahlvang** [comment]
Hi @rahul-8437008949 

Have you been able to collect the logs requested by @taicchoumsft ?

**Comment by rahul-8437008949** [comment]
Hi
I am unable to run the following command:

   - run Composer: ./Bot Framework Composer.exe

**Comment by rahul-8437008949** [comment]
Hi ,
I wanted to tell that i am running composer on microsoft virtual
machine.all my friends using vm are not able to run composer.Can you check
what can be done in this case.

Regards
Rahul G.
