### ISSUE TITLE
Form input is blocked by auto suggestion view

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#6001]
## Describe the bug

![image](https://user-images.githubusercontent.com/3829387/109267389-76bae080-7844-11eb-8273-95dd0077c5dc.png)

## Version

lastest main

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

In any expression field, if the form input is close to the bottom, whenever a = is typed, the auto suggestion view is float up and block the input field.

**Comment by garypretty** [comment]
For consistency, I am proposing that we replace this dropdown list with the new UX on the LG Editor, where the user gets a button to insert a pre-built function.  This would resolve this issue I believe.

![image](https://user-images.githubusercontent.com/3900649/109309411-29864100-783b-11eb-8a48-ac55c93ee327.png)
