### ISSUE TITLE
Can't create Azure resources by provisionComposer.js

### ISSUE THREAD

**Issue by craighsu** [microsoft/BotFramework-Composer#6008]
![image](https://user-images.githubusercontent.com/354679/109301972-a503e480-7873-11eb-8c05-86518ac4780a.png)

Hi there, I have a trouble with deploy bot.
I have tried to add "const tenantId = 'beibeicoffeegmail.onmicrosoft.com';" into the provisionComposer.js but get the error occured like above picture

Please help me to fix this error, thanks.

For your reference, I've executed the command below
node provisionComposer.js --subscriptionId=Azure subscriptionId --name=BeiBOT241 --appPassword=16 character password --environment=dev --tenantId =beibeicoffeegmail.onmicrosoft.com

**Comment by congysu** [comment]
Thanks @taicchoumsft to take a look first.

**Comment by taicchoumsft** [comment]
Hi @craighsu , can you try first to run `az logout` in a terminal, close the terminal, then re-open and `az login`, and login with the credentials associated with your organization, and try again?

**Comment by congysu** [comment]
@cwhitten @taicchoumsft please feel free to re-assign.  Thank you both.

**Comment by craighsu** [comment]
@taicchoumsft I've tried to run az logout and login, but still got the same error as below

![image](https://user-images.githubusercontent.com/354679/109370583-e203c180-78db-11eb-8080-555032361173.png)

**Comment by craighsu** [comment]
@taicchoumsft I've resolved the issue by creating a new user in the Azure subscription's AD and assigned a co-admin role in   Azure subscription.
