### ISSUE TITLE
LG Editor: input hints content default & placement

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#6009]
## Describe the bug
 - ~~Content: input hint default shows "_none_", should be "_accepting_".~~ (already done in the latest nightly)
 - Can we position this underneath Tab of Speech instead of right next to triple dot sub menu. (same for Attachments tab > Layout:Lists in that position)

Link for InputHint tooltip https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-input-hints?view=azure-bot-service-4.0 
 
## Version
v1.3.1-nightly.217012.67a05de

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/109305693-656ed580-783e-11eb-8c81-c6fbf81e9ead.png)

Attachments placement List layout
![image](https://user-images.githubusercontent.com/43533472/109305887-af57bb80-783e-11eb-96c7-c550744b2104.png)

**Comment by sangwoohaan** [comment]
We've actually explored an iteration that those dropdowns are under the label and that design didn't work very well. We'll leave them as they are for now, and get back to this in the near future
