### ISSUE TITLE
LG Editor: input hints support with tooltip to speech doc

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#6010]
## Describe the bug
Support for users to understand what input hints are, and default "accepting" (#6009). 

## Version
v1.3.1-nightly.217012.67a05de

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
Input hints needs explanation doc - tooltip preferable (works when we position this dropdown in recommended place issue #6009 

Add input hints to messages - Bot Service | Microsoft Docs (https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-add-input-hints?view=azure-bot-service-4.0)

**Comment by garypretty** [comment]
Merging with #6009
