### ISSUE TITLE
LG Editor: delete attachment messaging & design

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#6011]
## Describe the bug
When a user deletes attachment, the messaging / button order is confusing plus no support with doc links (learn more).

## Version
v1.3.1-nightly.217012.67a05de

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
Current: 
![image](https://user-images.githubusercontent.com/43533472/109306592-ab786900-783f-11eb-9fb5-8efccfe486d6.png)

Proposal:
![image](https://user-images.githubusercontent.com/43533472/109306618-b4693a80-783f-11eb-82cf-e32d0c28a82e.png)

Why?
- Update copy (including checkbox, hint, learn more(https://docs.microsoft.com/en-us/composer/concept-language-generation)) to proposed design (@garypretty), 
- Leverage a checkbox for the user to still keep the LG content for re-use. 
- Button order: 'cancel' should be left from 'confirm' main action, is positioned right side of the pop up. If the buttons are positioned left in pop up the order is correct. 
- Button content: 'confirm' should be 'delete'
- Include "Learn more" to docs.

**Comment by tdurnford** [comment]
@sangwoohaan Can you weigh in?

**Comment by hatpick** [comment]
@Quirinevwm order of the buttons is coming from Fabric lib which is by Microsoft, traditionally Microsoft does this ordering (positive action left, negative action right) vs. Mac that does the reverse. However, I've discussed this with Sang as well, we are using both ordering in different parts of the app, we need to be consistent.
https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog

https://jsbin.com/gufekenake/edit?html,js,output

**Comment by Quirinevwm** [comment]
@hatpick great to hear that button placement will be consistent across Composer. Indeed Fluent advises other order than Mac, it's just the action boxes are typically aligned from the left in the canvas. 

Just to make sure this issue is not really about the button placement. It's more on the confusing actions the users need to take in this pop-up; so updating content and the radio button (shift to 1 checkbox) would be advisable. I found a nice example from Azure Portal pop up, that relies on Fluent/Fabric:
![image](https://user-images.githubusercontent.com/43533472/109505508-f4792900-7a9c-11eb-824b-19d6fd847cfe.png)
