### ISSUE TITLE
LG Editor: static order text, speech, attachments, SA

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#6012]
## Describe the bug
I was able to change around the order by adding/deleting: attachments, speech first for example then text appeared later in the order of tabs. 

## Version
v1.3.1-nightly.217012.67a05de

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
My understanding of UX principle would be static adds, so always in the order of:
1. Text, 2. Speech, 3. Attachments, 4. SA's

Based on the workflow, that a user can add 'tabs' that fit their needs for the bot in an order that is consistent. So in a dialogue with multiple 'bot asks prompts' the order in the details pane is set. Otherwise in 1 dialogue flow, in one 'bot asks' component a dev could have "speech" tab first and in another "text" tab which can bring a lot of confusion and not preferable for consistency.

For clarity, if it's a speech only channel only speech would appear in the 'Bot asks' tabs., if a dev then adds text tab this would (become 1) and speech (2).
(If we start with this, we can enhance later to re-order (will bring in complexity for dev/design when updating LG in the details pane)

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/109308043-ce0b8180-7841-11eb-85e8-efd2516a65c4.png)

**Comment by garypretty** [comment]
@Quirinevwm this is now resolved in the latest nightly build and order is preserved.
