### ISSUE TITLE
LG Editor: missing doc link that explains DLS channel config

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#6013]
## Describe the bug
Composer provides flexibility that once a dev sets up a textual bot, they can add 'speech' tab for their voice content. This does not mean however their speech channel is configured, or will work when they test in emulator their voice experience. Could give the user a broken experience. In create (1.5) we will facilitate voice font selection, dls channel set up, but what is a dev adds their speech content later?

Propose as bare minimum to include guidance for speech in 'Learn more' in details pane (additional link)

## Version
v1.3.1-nightly.217012.67a05de

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
Better explanation in docs for LG editor, that reference to DLS & Telephony channel set ups (@garypretty has latest on where to link with)
- Learn more/or tooltip in screenshot does not explain how to set up DLS etc. 

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/109309281-58081a00-7843-11eb-843c-67f4d0096427.png)

**Comment by garypretty** [comment]
@zxyanliu @emgrol we need to ensure that we call out and cross reference the appropriate DLS docs when we document the LG editor.

**Comment by sangwoohaan** [comment]
The speech content isn't only for DLS and telephony though, it's a lower-level concept. You could have added the speech content for something else. Do we want to directly relate that to DLS/Telephony?

**Comment by garypretty** [comment]
@sangwoohaan I agree.  I don't think we should make any explicit changes in the UI at this point for telephony / speech in relation to the editor.  My suggestion above is simply that, when we talk about the editor in the speech tab in the docs, that we at least link to our first party docs for DLS / telephony, given they will be the most common use cases.  As you say speech is more pervasive, being used on channels like Alexa etc. 

I think broader references to telephony / DLS can be made within the creation experience / channel enablement, given we do pay special attention there to 1st party.

**Comment by Quirinevwm** [comment]
Guidance here was to make sure there is some route to documentation from either LG editor/emulator in Composer too, to explain what you need to think of for setting up speech experiences (indeed not just DLS/telephony, they are great ways to start). Especially is you have not done so in creation/channel enablement... Since in Composer you will be able to test in the product, and if you do have speech content (LG) set up but not DLS you won't be able to test your speech experience in Composer (that might feel odd).

**Comment by garypretty** [comment]
@Quirinevwm you can't test speech in Composer today - this is something you still need emulator for. Medium / long term we hope to change this, but there are technical hurdles in the way right now. I agree on the route to docs and the way I think we should surface that initially is via the article that the Learn More link points to on the Send Activity action. These articles are being updated based on the new editor and we will call out to appropriate docs from there. I am going to close this issue for now and I will pick up with @emgrol @zxyanliu when we update those docs shortly.
