### ISSUE TITLE
Creation modal readme formatting is inconsistent and needs improved copy + fix link

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#6021]
## Describe the bug

**Formatting**
When selecting a template, the readme section displays content with inconsistent formatting, ie title font size change, presence of sub-headers, links as text or URL.

Each readme should follow the same formatting. Follow the formatting convention being used for Conversational Core, Empty, and QnA. Smaller header. Sub-headers for Packages, Languages, and Azure Resource Deployment. Links as text. 

**Missing elements**
Each template should also include a icon/logo (align with package manager), version number, and link to documentation (and github?). Additionally, between the list and the readme section there should be a light grey line (see design below).

**External link**
Ensure each link in the readme triggers a new tab, otherwise the Composer window is hijacked and it's impossible to go back. External links should have external link icon (see below).

**Copy**
Description copy for each template needs improvement--Em, Ben, and Dewain will work together on that.

## Version

v1.3.1 special creation release

## Browser

- [x] Electron distribution

## OS

- [x] macOS

## To Reproduce

For external link specifically:
1. Go to create modal
2. Click on 'component model'
3. Land in github, can't get back to composer

## Screenshots
**Formatting No:**
![image](https://user-images.githubusercontent.com/55601267/109234312-4c075400-7780-11eb-8be8-b6642d3009c9.png)
![image](https://user-images.githubusercontent.com/55601267/109234325-54f82580-7780-11eb-9549-91aecf8c78f8.png)

**Formatting Yes:**
![image](https://user-images.githubusercontent.com/55601267/109234358-66413200-7780-11eb-8f19-f92e69957791.png)
![image](https://user-images.githubusercontent.com/55601267/109234366-6ccfa980-7780-11eb-87bf-a2eabca1f1e9.png)
![image](https://user-images.githubusercontent.com/55601267/109234531-bb7d4380-7780-11eb-895c-5e5b3d373d88.png)

**Icons etc**
![image](https://user-images.githubusercontent.com/55601267/109368572-660f6800-784e-11eb-8f38-038ee8fb3530.png)

**Naughty link**
Click on component model:
![image](https://user-images.githubusercontent.com/55601267/109235794-36475e00-7783-11eb-9458-f2c88491964b.png)

App turns into Github and no back button (wahhhh)
so it needs to open in a new tab, and have an external link icon
![image](https://user-images.githubusercontent.com/55601267/109236051-b5d52d00-7783-11eb-8703-45285a30f14d.png)

**Comment by Quirinevwm** [comment]
Adding on, documentation link [https://github.com/microsoft/botframework-components#bot-framework-components](url)
Add a banner: https://www.figma.com/file/AX6pIlB1lsyyLaIO8USkUO/UI-Overview-Conversational-AI?node-id=1%3A3001
Plus the content for skills should be updated: old versions skills etc, placed in archive etc?
[https://github.com/microsoft/botframework-components#skills](url)
