### ISSUE TITLE
package manager: the install buttons wrap with long version numbers

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#6022]
## Describe the bug

with our long 1.0.0-preview.GUID versions, we get a ugly text wrapping in the button.

![Screen Shot 2021-02-26 at 4 36 13 PM](https://user-images.githubusercontent.com/729873/109362553-dae3a180-7850-11eb-87c0-cee4157b0999.png)

**Comment by emivers8** [comment]
I forgot, did we already try truncating like this?

![image](https://user-images.githubusercontent.com/55601267/109371082-0453fb80-7858-11eb-8ac3-943d8e18af13.png)
