### ISSUE TITLE
Design bugs on Getting Started

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#6023]
## Describe the bug

Spacing, etc, UI issues.

Figma: https://www.figma.com/file/tvENftrexoAYJngzsJxUbv/EmFig?node-id=2981%3A17

## Screenshots

![image](https://user-images.githubusercontent.com/55601267/109362845-b7185f80-7840-11eb-9ae2-302751828f33.png)

**Comment by benbrown** [comment]
Fixed! I think!  Double check!

![Screen Shot 2021-03-01 at 11 28 38 AM](https://user-images.githubusercontent.com/729873/109534872-7196a500-7a81-11eb-97a4-325ed1b75381.png)

**Comment by emivers8** [comment]
"File location" "Customize" and "Publish" should be semibold weight.

Let's also tighten the line height on those link lists just by 1-2 px (send me a screenshot over teams).
