### ISSUE TITLE
Create modal - Template naming and list order

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#6026]
## Describe the bug

The list of templates in the create modal should be arranged intentionally, potentially from simple to more complex for R12 release, and the names themselves should be revised. @Dewain27 @emivers8 @benbrown and @mareekuh to agree on naming. Initial recommendations below, but final TBD.

Initial recommendations:
1. Blank bot (empty bot)
2. Basic conversational bot (conversational core)
3. QnAMaker bot (generator-qna-bot)

(Is multibot or calendar part of release for R12?)

## Screenshots

![image](https://user-images.githubusercontent.com/55601267/109367970-6dce0d00-784c-11eb-89b5-e17082f061ab.png)

**Comment by benbrown** [comment]
No the multibot "Calendar assistant" and the "Calendar" bot are not going to be publicly released.

It is quite difficult for us to sort these in a different order than they come in from the API without building making things quite brittle. We'll need to discuss a method for achieving this.
