### ISSUE TITLE
Onboarding conflicts with new creation

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#6039]
If you have the onboarding stuff on and create a bot, the popup next to the ToDo with LUIS bot it creates for you doesn't fade during the loading creation screen. This makes it look like you can click on it, and if you do, Windows will probably grey out all of Composer with the normal "Not Responding" look. That popup should close as soon as I start creating a bot.

![image](https://user-images.githubusercontent.com/1139814/109438538-5d01d080-79df-11eb-9350-bf1ab9216acd.png)

After creation finishes (finally), Composer still tries to give the rest of the tutorial popups, but they don't align to the UI anymore, and a bunch of them are referencing items that aren't there, or UI that has been changed/renamed.

**Comment by boydc2014** [comment]
@yeze322 can you help check this one?

**Comment by mewa1024** [comment]
(@xiyangdesign is working on this for R13.)

**Comment by srinaath** [comment]
@boydc2014 @yeze322  This concern may no longer be required due to #6343

**Comment by yeze322** [comment]
I saw TJ's PR #6344 , transfer this issue to TJ for further improvements

**Comment by mareekuh** [comment]
Product tour updated design is here:  https://www.figma.com/file/pghEVhZEtMsXae9IHybdYo/Composer-Xi-s-workspace?node-id=463%3A46476
