### ISSUE TITLE
Possibility of importing/mapping LUIS App into Composer

### ISSUE THREAD

**Issue by UmaPrelude** [microsoft/BotFramework-Composer#6045]
Hi,

I want to know if there is any possibility that i can create the LUIS App in the portal and import/map into composer, so that any time the utterances can be uploaded to LUIS portal and composer can import it from there.  So that this uploading activity can be handled by someone who is non technical as well.

Please recommend.

**Comment by cwhitten** [comment]
Hi @UmaPrelude. Bi-directional syncing between the LUIS Portal and Composer is not something we support or have short term plans to support. In the LUIS Portal you can export your LUIS application data into the .lu file format and migrate it into Composer, but this is currently a manual process.

**Comment by UmaPrelude** [comment]
> Hi @UmaPrelude. Bi-directional syncing between the LUIS Portal and Composer is not something we support or have short term plans to support. In the LUIS Portal you can export your LUIS application data into the .lu file format and migrate it into Composer, but this is currently a manual process.

@cwhitten, thanks for your response.
