### ISSUE TITLE
Redirect to Power Virtual Agents Topic from Composer Dialog

### ISSUE THREAD

**Issue by iMicknl** [microsoft/BotFramework-Composer#6047]
## Is your feature request related to a problem? Please describe.

Currently you can use Bot Framework Composer to build your more advanced dialogs for Power Virtual Agents. In many scenario's, Power Virtual Agents contains topics where you would like to redirect to. For example if you have an Adaptive Card with multiple options, to redirect back to a topic modelled in PVA.

## Describe the solution you'd like

A way to utilize `Dialog Management -> Begin a new dialog` to redirect to a topic in PVA.

## Describe alternatives you've considered

Open for suggestions. Modelling all PVA topics/responses in Composer is not a feasible solution.

## Additional context

Composer is used to overcome limitations of PVA, for example the use of HeroCards or Adaptive Cards. I would like to only model a few steps in a dialog in Composer, where the majority is still handled by PVA.

**Comment by cwhitten** [comment]
hello @iMicknl - this is on our short-term roadmap as new functionality as part of the integration. You should see this soon in an upcoming release

**Comment by cwhitten** [comment]
Will ship with the next release. Closing
