### ISSUE TITLE
Call Power Virtual Agents NLU via Composer

### ISSUE THREAD

**Issue by iMicknl** [microsoft/BotFramework-Composer#6048]
## Is your feature request related to a problem? Please describe.

When modelling advanced prompts in Composer, I would like to use PVA NLU. For example when you prompt with `Yes` / `No`, but want to handle all variations of this boolean. This is very easy to model in PVA and would be nice to reuse this NLU.

## Describe the solution you'd like

Use the Power Virtual Agents NLU for (multi)choice prompts.

## Describe alternatives you've considered

Using LUIS in Composer prompts, but I haven't been able to get this working.

## Additional context

Composer is used to overcome limitations of PVA, for example the use of HeroCards or Adaptive Cards. Since #6047 is not possible, we would need to handle user responses in Composer. 

Looking at [this video from Ignite](https://www.youtube.com/watch?v=I04xGaGBct4&ab_channel=MicrosoftIgnite
), this should be possible:

![image](https://user-images.githubusercontent.com/1424596/114390056-0d91f100-9b96-11eb-910a-a0e691022266.png)

**Comment by cwhitten** [comment]
Hi @iMicknl. Thanks for the feature request. We'll bring this up with PVA, however we have no plans or roadmap to support this at the moment.

**Comment by iMicknl** [comment]
Apparently, it is already possible to use the results of Power Virtual Agents NLU, but it is a bit complicated. (and not supported).

On every turn, PVA NLU will be called and the results can be found in `turn.recognized`. For example, to extract a custom entity defined in Power Virtual Agents can be done with the following definition: `turn.recognized.text.entities.$instance.new_customtype_bb3151406b884e95a83fc3f0dba9f597`

Example entity result:

```json
"entities": {
    "$instance": {
        "POI": [
            {
                "Name": "POI",
                "Value": "Home Goods Store",
                "Start": 26,
                "End": 32,
                "Text": "at home"
            }
        ],
        "new_customtype_bb3151406b884e95a83fc3f0dba9f597": [
            {
                "Name": "new_customtype_bb3151406b884e95a83fc3f0dba9f597",
                "Value": "At the general practitioner",
                "Start": 24,
                "End": 31,
                "Text": "hospital"
            }
        ]
    }
},
```

You could use this result to check if there are results for your custom entity and otherwise prompt again. This is not easy and probably unsupported, but could be a workaround for people facing the same limitation.
