### ISSUE TITLE
uploading zip file forever when publishing a bot to azure web app

### ISSUE THREAD

**Issue by afahmy11** [microsoft/BotFramework-Composer#6050]
hi

i am trying to publish my first bot to my azure subscription. the publishing job is stuck forever at uploading zip file step.

how can i troubleshoot this issue?
bot framework composer version 1.3.1 on mac Big Sur v11.2.2

![Bot-uploadingZIP](https://user-images.githubusercontent.com/49028761/109513112-6e191300-7aad-11eb-8a4d-3d7113e24ba6.jpeg)

**Comment by cwhitten** [comment]
@stevkan @dmvtech can someone from Support Engineering look at this?

**Comment by dmvtech** [comment]
Hi @afahmy11 

- If you delete the publishing profile and try again does it still behave the same? 
- What about with a new/simple echo bot? 
- Are you publishing to existing resources or new ones?

**Comment by afahmy11** [comment]
thanks dmvtech

i have created a new profile and now it is uploaded successfully

![image](https://user-images.githubusercontent.com/49028761/109949106-a99d2280-7ce3-11eb-8b21-0702371ebf2b.png)
