### ISSUE TITLE
Content in Error modal is not wrapped

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#6056]
![error modal](https://user-images.githubusercontent.com/67944302/109545150-52961400-7a7d-11eb-90e7-1f2a733cc6b9.gif)

## Describe the bug

Not sure what triggered the error, but the modal does not constrain the text.

## Version

1.3.1

## Browser

- [ ] Electron distribution

## OS

- [ ] macOS

**Comment by alanlong9278** [comment]
I can not reproduce the error. Could u give me the detail steps for the issue, thanks. @JaskeeratBedi-cmk
