### ISSUE TITLE
Create modal - hyphens not allowed in bot project name

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#6070]
## Describe the bug

In previous versions, hyphens were allowed in the bot project name. Now they seem to have been disallowed. Unless there's a compelling reason for this, we should maintain support of the same naming conventions.

## Version

1.3.1-nightly.218556.7416cb6
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Screenshots

![image](https://user-images.githubusercontent.com/55601267/109574701-49b93880-7aa5-11eb-81e8-4154b0e4684c.png)

**Comment by pavolum** [comment]
Naming constraint will remain in R12, in R13 we will implement naming sanitization at the generator level to allow for less invalid characters in the overall proj name while resulting in valid projName in the generated C# code.

**Comment by Dan-Bai** [comment]
Seeing this same issue in V2.0.0
Is this the intended convention from now on?

Can someone tell me what does this naming convention impact? (Filename, variable name, etc.)
