### ISSUE TITLE
accessing qnamaker trace and fetching qnamaker answer received from qnamaker dialog using memory object

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#6080]
Hi,

This is related to below query.

https://github.com/microsoft/BotFramework-Composer/issues/4926

We have some triggers(Intent Recognized) and an 'unknown intent'(none) trigger. If no intent is matched it will go to unknown intent trigger and in that unknown intent trigger we are using Qnamaker dialog action to connect to Qna knowledge base as shown in below screen shot.
![image](https://user-images.githubusercontent.com/70739031/109628434-bf3a0d00-7b68-11eb-9ab3-d08d828256a6.png)

![image](https://user-images.githubusercontent.com/70739031/109628548-e09af900-7b68-11eb-89fd-53ad1f4b3e9d.png)

Now the thing is that we are getting qna answer from qnamaker dialog. But we are unable to trace the parameters such as qna confidence score, qna matched question etc. We want to store this parameter in the bot. Also how can we trace the qnamaker answer received from qnamaker dialog using memory object( in Emulator). We are able to trace the question asked by user using "turn.activity.text" but is there any way in composer to trace & store the qnamaker answer which bot is sending to the user. In qnamaker trace there is nothing available to capture the data we want. We want to trace and store qnamaker answer received from qnamaker dialog using memory object so that we can implement different flow based on the different answers received from qnamaker dialog.

![image](https://user-images.githubusercontent.com/70739031/109628667-032d1200-7b69-11eb-8b54-631eab4009dd.png)

You had mentioned that: Within a QnA Intentet recognized trigger, we can use something like the following:
turn.recognized.answers[0].questions

'QnA Intentet recognized trigger' can we use to create QnAKnowledge base within the composer.
But we are not creating QnAKnowledge base within the composer. We have already created QnAKnowledge base manually on the QnAMaker.ai portal and we want to connect to this knowledgebase in the composer.

As part of our project requirement, now we must use 'QnAMaker dialog' in composer to configure QnAKnowledge base in the bot.
So, by using 'QnAMaker dialog' can we trace what answer bot is displaying to the user for QnA question. If answer is 'Sorry I did not find an answer', we want to implement some different flow based on requirement. So we want to trace whether the answer from QnA Knowledge base is 'Sorry I did not find an answer' or something different if we are using 'QnAMaker dialog' in composer.

Thanks.

**Comment by cwhitten** [comment]
Hi @BeheraMadan - Composer doesn't support the expressive scenarios you are looking for using QnAMaker when called with an Action like you have implemented. To achieve these scenarios we recommend authoring the knowledgebase in Composer and publishing to QnA.
