### ISSUE TITLE
Getting Started - Bot Info exceeds its cell width in UI

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6084]
## Describe the bug

The Bot Info if text exceeds the length of the cell for the Bot Name and file location does not stay within cell boundries.

![image](https://user-images.githubusercontent.com/18688053/109666796-250ca180-7b35-11eb-9336-aadf05935367.png)

## Version

![image](https://user-images.githubusercontent.com/18688053/109666891-3d7cbc00-7b35-11eb-8dcb-f02af2d23dfc.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create Bot with a really long name and long path
2. Go to Bot Settings page and look in Bot Info Section

## Expected behavior

Text is contained within cell / wrapped or concatenated

**Comment by benbrown** [comment]
here's a shot in action

![F2P16JUHVR](https://user-images.githubusercontent.com/729873/109685881-4f675a80-7b47-11eb-98a1-acf4f8255d79.gif)
