### ISSUE TITLE
On smaller resolution screens the Getting Started Experience takes most of the Canvas

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6085]
## Describe the bug

When using a screen size like 1080p you will be presented the Getting Started on the Bot Settings page.  There is no way to collapse and/or scroll the area that has bot info / Next steps / Guides and References. making a very small area to perform bot settings.  It should either be collapsible by the user and/or scrollable to allow for better use of the screen.

## Version

![image](https://user-images.githubusercontent.com/18688053/109668074-6782ae00-7b36-11eb-8bb6-f3dc6e754519.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a Bot Project
2. Go to the Bot Settings page (Issue)

## Expected behavior

Should have the area below the action menu to scroll and possibly allow the collapse of the bot info and getting started section.

## Screenshots

![image](https://user-images.githubusercontent.com/18688053/109668274-a0bb1e00-7b36-11eb-81c4-65da87049100.png)

**Comment by benbrown** [comment]
![F2P16JUHVR](https://user-images.githubusercontent.com/729873/109686498-f3e99c80-7b47-11eb-9822-9cd7d133c823.gif)

**Comment by garypretty** [comment]
Small experience point of view from me on the above - at least today (I know we have other aspirations for the future) the information shown above is relevant for less experienced developers.  If I am a regular user of Composer and this is always shown in it's expanded form, then I am likely to get frustrated that it is in my way when I am trying to get to my settings.  We should consider allowing the user to opt to collapse the panel to a shallower form (still showing the toolbar and the key info such as bot name and file location?) and have Composer remember that choice.
