### ISSUE TITLE
bug: publish profile json editor cropped in "Review" screen

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#6087]
## Describe the bug

The JSON editor that is displayed in the modal if a user has already provisioned all available resources is slightly cropped at the bottom, preventing the user from seeing the entire JSON file.

![Screen Shot 2021-03-02 at 10 44 55 AM](https://user-images.githubusercontent.com/729873/109683212-c0594300-7b44-11eb-8933-234ba815e990.png)

## Version

nightly

## To Reproduce

1. create a proviosning profile with EVERYTHING turned on
2. after it succeeds, click edit
3. click "next: review"
4. the json editor will be cropped

**Comment by hibrenda** [comment]
![image](https://user-images.githubusercontent.com/43408889/109932833-aa46b080-7d05-11eb-9d7e-ed1c00608ab5.png)

It is still cropped for "Cancel" button and the bottom line of the json file. Meanwhile there is no scroll bar for json editor if the line is too long
