### ISSUE TITLE
Project Settings Page Advanced JSON View is Cropped with new task bar on top

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/BotFramework-Composer#6094]
## Describe the bug

Now with a task/help bar at the top of the Project Settings page the rest of the advanced json view is cropped

## Version

                Bot Framework Composer

                Version:  1.3.1-nightly.218992.794e78c
                Electron: 8.2.4
                Chrome: 80.0.3987.165
                NodeJS: 12.13.0
                V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to project settings
2. Toggle "Advanced Settings View (JSON)"

## Expected behavior

Can scroll to the bottom of the json

## Screenshots

![image](https://user-images.githubusercontent.com/9922190/109719917-36b66f00-7b5e-11eb-91ca-a704b29960c4.png)

**Comment by benbrown** [comment]
We are going to redesign that top bar to cause less issues!

This problem should be resolved by that redesign, unless otherwise noted!

**Comment by tonyanziano** [comment]
Related to #6121

**Comment by benbrown** [comment]
This was fixed a while back.
