### ISSUE TITLE
Check boxes not showing next to be installed items in Required

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6095]
## Describe the bug

Check boxes in Resource selection screen for publishing profile should indicate that it will be installed.  Required resources should show as checked and you should not be able to unselect them.

## Version

![image](https://user-images.githubusercontent.com/18688053/109722456-52c40b80-7b72-11eb-9934-78d73fa0cebd.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Publishing Profile and get to Add Resources page
2. Check boxes for required resources not checked and is confusing as it looks like nothing will be installed if you uncheck optional items

## Expected behavior

Things that are going to be installed should be indicated in the UI for Required items.  Otherwise it is very confusing what will and will not be installed.  Check boxes should be checked next to resources but are in not uncheckable.

## Screenshots

![image](https://user-images.githubusercontent.com/18688053/109722237-0d074300-7b72-11eb-80c9-00a00f1d1fe0.png)

**Comment by cwhitten** [comment]
@luhan2017 @VanyLaw @hibrenda this is a regression if correct. adding to RC board if so.

**Comment by luhan2017** [comment]
@cwhitten @cwhitten @Dewain27 This is not a regression, we don't add the checkbox besides the required services because

![image](https://user-images.githubusercontent.com/32191031/110262429-9c877880-7fee-11eb-8191-3879df6836d6.png)

**Comment by JaskeeratBedi-cmk** [comment]
I suggest we replace the default round selection box that we get from list to **checkboxes**. Checkbox gives us different states such as disabled, unchecked and checked and will give more explicit user feedback, which is of the essence in this case. ( See attached) 
![checkboxes](https://user-images.githubusercontent.com/67944302/110275125-4d592d80-7f85-11eb-8e92-2253adeed927.png)

**Comment by benbrown** [comment]
See related: #5894
