### ISSUE TITLE
NPM and Node.js not installed needs to prompt you to install Node.js and NPM

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6097]
## Problem

Currently, Composer doesn't tell the user during install to install NPM.  We need a way to communicate and/or install Node.js and NPM as part of Composer.

## Describe the solution you'd like

When Composer installs or runs the first time, that it looks for NPM and Node.js and if not installed it installs it kicks off the install for the user.

## Describe alternatives you've considered

If you start Composer and NPM and Node.js are not installed at the proper versions or at all... Composer communicates with a link to the installer for Node.js and NPM.  A warning should continue to be on your Composer interface until the issue is resolved.

**Comment by pavolum** [comment]
Other alternatives to consider and see if possible:
- piggybacking on the node version used by the electron app itself for node processes
- Installing node as part of the Composer installation (may not work with mac as there is no installer in mac)
- Adding documentation that the user needs to manually install node as they need to manually install dotnet prior to installing Composer
