### ISSUE TITLE
Make publishing/provisioning a bot less painful

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#6102]
## Is your feature request related to a problem? Please describe.

I hit a provision failure when trying to publish my bot. Now I need to start the publish process from scratch, instead of just being able to fix the one value that caused the issue. Very frustrating.

## Describe the solution you'd like

I'd like to not lose all the work I put into filling in the original publishing profile. I'd rather just change **west US 3** to **west US 2** and try again, instead of spending another however many minutes on this.

## Describe alternatives you've considered

Bonus (actually the root of this particular problem):

1. Filter out the _regions_ that don't support publishing to begin with
2. Please sort regions in alpha order.

## Additional context

Provision failure message:
![image](https://user-images.githubusercontent.com/35047199/109732204-966a4580-7b71-11eb-9d44-2475c024c73d.png)

**Comment by zxyanliu** [comment]
You should use the stable version of Composer. 
https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.3.1

**Comment by luhan2017** [comment]
@zidaneymar, please help investigate how we get the available region list.

**Comment by benbrown** [comment]
We have several improvements planned for R13 along the lines of what you've asked for @JonathanFingold

* An update will store any successfully created resources, and allow you to do a second pass on those that failed
* Additional updates to the error handling and messages available during and after the process so you can more easily determine where the problem occured

**Comment by zidaneymar** [comment]
@luhan2017 Maybe we need to iterate all resource providers and merge the supported regions together, which is a subset of all regions.

Currently we have following resource providers:
```
export enum AzureResourceProviderType {
  QnA = 'Microsoft.CognitiveServices',
  Luis = 'Microsoft.CognitiveServices',
  CosmosDB = 'Microsoft.DocumentDB',
  BlobStorage = 'Microsoft.Storage',
  ApplicationInsights = 'Microsoft.Insights',
  WebApp = 'Microsoft.Web',
  Bot = 'Microsoft.BotService',
}
```

**Comment by luhan2017** [comment]
@zidaneymar Could you try to get this list manually, I want to have a basic understanding on those regions, then we can decide.

**Comment by zidaneymar** [comment]
> @zidaneymar Could you try to get this list manually, I want to have a basic understanding on those regions, then we can decide.

![image](https://user-images.githubusercontent.com/9328933/110299814-1dfffa80-8031-11eb-8941-8c79ccc19fa1.png)

It seems that we could merge the allowing regions except bot service.

**Comment by zidaneymar** [comment]
@luhan2017 This is the merged results for all supported resource types:
```
Australia East, Brazil South, West US, West US 2, West Europe, North Europe, Southeast Asia, East Asia, South Central US, East US, East US 2, Canada Central, Japan East, Central India, UK South, Japan West, Korea Central, France Central, North Central US, Central US, South Africa North, UAE North, Switzerland North, Germany West Central
```

I think we should use this as the regions we support.
