### ISSUE TITLE
Header is broken when Composer is resized.

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#6108]
At the exteme end of the spectrum it looks like this:

![image](https://user-images.githubusercontent.com/1139814/109767679-c2ef8300-7bac-11eb-87c5-c402e1cf97c8.png)

At a medium width (typical if docking two windows side-by-side)

![image](https://user-images.githubusercontent.com/1139814/109767759-e286ab80-7bac-11eb-978d-4ce8fde17ab3.png)

**Comment by cwhitten** [comment]
@sangwoohaan the team will need responsive designs for this header to properly address this.

**Comment by mewa1024** [comment]
Looks this has been fixed. On Windows:
![image](https://user-images.githubusercontent.com/39317542/124207462-6dfc4480-da9a-11eb-89ac-e2c441f60edc.png)
