### ISSUE TITLE
'QnAMaker Dialog' action component vs  QnAMaker  GenerateAnswer API

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#6109]
Hi,

we can configure Qnamaker in composer bot by using 'QnAMaker Dialog' action component(https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot) or by using QnAMaker  GenerateAnswer API(https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/metadata-generateanswer-usage?tabs=v1).

When we use API call we are able to trace the Qna Parameters such as qna confidence score, qna matched question, qna answer, source file etc with the help of Json response of the api.

For eg. If we ask a question 'hi' using API call we get below api response

```json
{
    "answers": [
        {
            "questions": [
                "Aloha",
                "Aloha bot",
                "Bonjour",
                "G'day",
                "Good day",
                "Greetings",
                "Greetings and salutations",
                "Greetings bot",
                "Greetings friend",
                "Hello",
                "hello bot",
                "Hello my friend",
                "Hello there",
                "Hey pal",
                "Hey there",
                "Hey there bot",
                "Hey you",
                "Heya",
                "Hey-hey",
                "Hi",
                "Hi bot",
                "Hi there!",
                "Hiya",
                "Hi-ya",
                "Howdy",
                "Oh hey there"
                "Oh hey, it's you",
                "Oh howdy there",
                "Oh, hello",
                "Shalom",
                "Yo"
            ],
            "answer": "Hello.",
            "score": 100.0,
            "id": 146,
            "source": "qna_chitchat_professional.tsv",
            "isDocumentText": false,
            "metadata": [
                {
                    "name": "editorial",
                    "value": "chitchat"
                }
            ],
            "context": {
                "isContextOnly": false,
                "prompts": []
            }
        }
    ],
    "activeLearningEnabled": true
}
```

With the above api response we can know what answer we are getting from the api i.e we can trace qna parameters whatever required.

But when we use 'QnAMaker Dialog' action to configure qnamaker in bot, we are unable to trace qna parameters mentioned above. We are unable to capture what answer qna sending to the user from the memory. Based on the qna answer we want to implement different scenario in the bot. Suppose qna send default answer i.e 'No good match found in KB' then we want to implement some different flow in bot. But with 'QnAMaker Dialog' action there is no way to capture what answer bot is sending to the user whether it is 'No good match found in KB' or something different.

![image](https://user-images.githubusercontent.com/70739031/109779872-6764da00-7c2c-11eb-9e74-0fb64e4342bc.png)

'QnAMaker Dialog' action should have features similar to GenerateAnswer API so that qna parameters  can be traced  with 'QnAMaker Dialog' action. We need to use 'QnAMaker Dialog' action as per requirement.

Thanks..

**Comment by BeheraMadan** [comment]
Hi,

We have one below major issue associated with UX research. We have configured qnamaker using 'QnAMaker Dialog' action in composer as shown below.
![image](https://user-images.githubusercontent.com/70739031/109914834-caab4680-7cd6-11eb-8c0f-433c9e0a4ba5.png)

We are asking for feedback(using adaptive card) to the user immediately after 'QnAMaker Dialog' action. 
![image](https://user-images.githubusercontent.com/70739031/109915066-2fff3780-7cd7-11eb-9a56-93b056d2dc04.png)

Now the problem is there is no way to trace Qna Parameters such as qna confidence score, qna matched question, qna answer, source file etc for the 'QnAMaker Dialog' action. So bot is asking for feedback to the user for each qna answer even if the answer is 'Sorry, I did not find an answer.' as shown below.
![image](https://user-images.githubusercontent.com/70739031/109915561-0bf02600-7cd8-11eb-940f-8b3fe3c1ce87.png)
![image](https://user-images.githubusercontent.com/70739031/109915777-6a1d0900-7cd8-11eb-8017-db00a2362742.png)

This scenario is very annoying for the end users. 
We want to remove feedback card if the bot answer is 'Sorry, I did not find an answer.'. But the problem is that there is no way to trace what is  the bot answer, whether it is 'Sorry, I did not find an answer.' or something different.

Thanks..

**Comment by cwhitten** [comment]
@BeheraMadan as stated in other tickets, when you are using the QnA Action to call a Knowledgebase you should see the behavior as a black box -- you don't have the kind of control to dig into the internals of the QnA processing like you would if you authored the knowledgeable in Composer directly. 

When calling QnA like you are, you will need to go into the QnAMaker portal and utilize the functionality that it provides to better understand the behavior of the knowledgebase.
