### ISSUE TITLE
Cannot Start Bot

### ISSUE THREAD

**Issue by Rekeyea** [microsoft/BotFramework-Composer#6113]
## Describe the bug

Cannot start bot. It fails with the following message:

`{"stack":"Error: spawn C:\\Windows\\system32\\cmd.exe ENOENT\n at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)\n at onErrorNT (internal/child_process.js:456:16)\n at processTicksAndRejections (internal/process/task_queues.js:80:21)","message":"spawn C:\\Windows\\system32\\cmd.exe ENOENT","errno":"ENOENT","code":"ENOENT","syscall":"spawn C:\\Windows\\system32\\cmd.exe","path":"C:\\Windows\\system32\\cmd.exe","spawnargs":["/d","/s","/c","\"dotnet user-secrets init --project azurewebapp\""],"cmd":"dotnet user-secrets init --project azurewebapp","stdout":"","stderr":""}`

## Version

![image](https://user-images.githubusercontent.com/8574490/109809386-ffe86380-7c06-11eb-9167-87b794e38a25.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1.Click on Start Bot Button
2. Wait for it to fail

## Expected behavior

The bot starts

## Screenshots

![image](https://user-images.githubusercontent.com/8574490/109809574-345c1f80-7c07-11eb-9306-1b4a578ed6fd.png)

**Comment by tonyanziano** [comment]
@anusharavindrar can you please take a look at this?

**Comment by anusharavindrar** [comment]
@Rekeyea, thanks for reporting this error. To understand further,

- Was the bot starting up or running as expected in the previous version(1.3.1 or earlier)?
- Are you getting this error for a specific bot or all the bots in this nightly build version of the composer do not start up? 

Also, it does look like you might have to set the PATH environment variable to **C:\Windows\System32**. Can you check the current value of PATH in the environment variable?

**Comment by Rekeyea** [comment]
> @Rekeyea, thanks for reporting this error. To understand further,
> 
> * Was the bot starting up and running as expected in the previous version(1.3.1 or earlier)?
> * Are you getting this error for a specific bot or all the bots in this nightly build version of the composer do not start up?
> 
> Also, it does look like you might have to set the PATH environment variable to **C:\Windows\System32**. Can you check the current value of PATH in the environment variable?

Yes, it was working before. The Composer updated and it stopped working.
The Path env variable is correctly set:

![image](https://user-images.githubusercontent.com/8574490/110113740-4a4a1b80-7d92-11eb-90a4-9c306697d4cf.png)

**Comment by Rekeyea** [comment]
Adding more details, it happens when using a custom runtime. When going back to the default runtime this does not happen.

**Comment by Rekeyea** [comment]
I used the "Get a new copy of the runtime code" functionality. Had to rerun the schemas, but it apparently is working again.
What I saw is that before the update, my **Runtime code location** was _runtime_ but when I got the new copy it was automatically set for _../runtime_. So I guess that was the issue.

I think this can be closed. Thanks for all your help.
