### ISSUE TITLE
Manage Connections button does nothing

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6116]
## Describe the bug

When you click the Manage Connections button on the Action Bar in Getting Started experience, nothing happens.

## Version

![image](https://user-images.githubusercontent.com/18688053/109821336-7d0ddb80-7bfb-11eb-9fcf-c4837350b0a8.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Bot Settings Page
2. Click on Manage Connections and nothing happens

## Expected behavior

I should be taken to the place in bot settings to add adapters and channels

## Screenshots

![image](https://user-images.githubusercontent.com/18688053/109821656-d0802980-7bfb-11eb-93cb-c1278e2515fe.png)

**Comment by benbrown** [comment]
Will be fixed by #6118!
