### ISSUE TITLE
Package Manager Interface delays in showing bot selection UI

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6117]
## Describe the bug

When using a multi-bot project and navigating to the package manager, there can be a long delay in getting the bot navigation to load and show in the UI.  There is no communication that it is still loading, it just pops up after about 30 seconds. 

## Version

![image](https://user-images.githubusercontent.com/18688053/109822241-6451f580-7bfc-11eb-8f07-2ebf52cf7120.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a multi-bot project using the Calendar Assistant template
2. Click on Package Manger
3. Wait for all UI to load

## Expected behavior

I would expect that the navigation of multi-bot to be loaded before the NPM feed finishes, this seems to be done after it loads the package list, which seems odd.

## Screenshots

![image](https://user-images.githubusercontent.com/18688053/109822653-c6125f80-7bfc-11eb-9334-042b8d186fc3.png)

**Comment by benbrown** [comment]
This is the same issue as the main nav - it takes a long time for calendar to load and appear in the application state.

We hide this nav if there is only 1 bot, and we don't know there are more than 1 bot until they load...

I think this will be solved by a redesign of the multi-bot nav and optimizations around loading.

**Comment by clearab** [comment]
Closing
