### ISSUE TITLE
Cannot open composer, hangs on 'starting server'

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/BotFramework-Composer#6119]
Tried uninstalling, reinstalling GA version, reinstalling nightly, and always end in the same: when I start composer the blue screen at the beginning stays there forever.

![image](https://user-images.githubusercontent.com/21318528/109840503-0b369180-7bfd-11eb-99a2-ec6b3bc8f550.png)

Any workarounds or suggestions on how to gather error information / logs? The same installers worked in other computers.

**Comment by a-b-r-o-w-n** [comment]
@carlosscastro you can set the environment variable `DEBUG=composer*` and start the app from the command line.

**Comment by cwhitten** [comment]
@carlosscastro assigning to you to get the team some debugging logs. I expect you will see an error
