### ISSUE TITLE
Composer not trusted app when uninstalling: Should appear as published by microsoft but it does not.

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/BotFramework-Composer#6120]
I installed composer for all users as administrator. Then uninstalled, and was prompted for admin approval however the app appeared as non-trusted, which points to some signing or cert issue.

REcommend testing the following scenarios in Windows:

1. Install for current user, verify that the app is trusted and published by microsoft
2. Install for all users, verify that the app is trusted and published by microsoft
3. Uninstall for current user, verify that the app is trusted and published by microsoft
4. Uninstall for all users, verify that the app is trusted and published by microsoft

**Comment by boydc2014** [comment]
@tonyanziano did you get a chance to take a look at this, or I can help verify the scenario?

**Comment by tonyanziano** [comment]
@boydc2014 I have not looked at this yet. I plan on investigating once I wrap up the Web Chat inspection P0's

**Comment by boydc2014** [comment]
I can't repro this in my end, with install\uninstall for current and for all user. I do see some similar issue in nightly build that is not correct signed. @carlosscastro  in which version you saw this issue? 

Closing this for now till we get a second repro.
