### ISSUE TITLE
New LG template has awkward focus

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotFramework-Composer#6122]
## Describe the bug

When you create a new template the focus is not on the template name.  Even when you select it, you need to manually delete the auto generated name.  Better would be if you focused on the template name with it selected so you could just start typing.  The awkwardness continues that when you hit enter or tab it does not go to the template value, but on to creating a new template.  This means instead of create, type name, enter/tab, type value you need to do: create, click template, delete template, type name, click value, type values which requires removing your hands from the keyboard.  Even worse as far as I can tell the Responses field is useless--I can't figure out how to enter template alternatives--I hit enter and it goes onto the next template.  The only alternative is code view.

![image](https://user-images.githubusercontent.com/17637681/109856415-50af8a80-7c0e-11eb-9ea1-e6fa763cc825.png)

**Comment by garypretty** [comment]
@sangwoohaan when you're considering any iterations in the all up view, worth taking this into account.
