### ISSUE TITLE
More complex templates are too intimidating

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotFramework-Composer#6125]
## Is your feature request related to a problem? Please describe.

When you try out the Calendar skill after it installs everything you are faced with this page.
![image](https://user-images.githubusercontent.com/17637681/109858271-7473d000-7c10-11eb-8fe6-d9b49948f20c.png)
This requires me to understand and setup a bunch of services.  I suspect the top will eventually have step by step directions, but this page is very intimidating when you just want to explore the skill.  Am I defining an endpoint or do I need to find one?  Do I need to go create a bunch of keys for services I haven't used before and how do I do that?  Where does the appid/password come from?

## Describe the solution you'd like
In an ideal world this would not be front and center and I could experiment without this information.  Next best would be to have defaults for services from my own config like in #6123.  And only as a last resort clear step by step instructions for the parts we can't automate.

**Comment by cwhitten** [comment]
@chrimc62 this header has been entirely redesigned and the Creation team is evaluating the right getting started experience with new creation. Will leave open for discussion.
