### ISSUE TITLE
Cleanup feature flag

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#6126]
The feature flag needs to be reworked to 

Name:
The Component Model

Description:
Enable the Component Model including the new creation experience, the Adaptive Runtime, and Package Manager. [Learn More](https://github.com/microsoft/botframework-components).

**Comment by sgellock** [comment]
going forward, @clearab, I would like feature flag text changes to be more broadly reviewed.  I'm not aligned to this framing as  it's not how the new creation experience should be presented to the developer.

**Comment by sgellock** [comment]
Name:
New Creation Experience.

Description:
Preview the new bot creation experience.  Create new bots that use the Adaptive Runtime, and can be enhanced using Package Manager. Learn More.
