### ISSUE TITLE
bug: Audio Cards don't work in new "Open Web Chat" feature

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/BotFramework-Composer#6128]
## Describe the bug

When using the new/preview "Open Web Chat" feature, audio cards throw an error as soon as the card is rendered.

Note: This worked fine if I tested directly in Emulator.

## Version

1.3.1-nightly.219396.61c994a

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Get nightly version of Composer
2. Open RespondingWithCardsSample
3. Run the bot
4. use "Open Web Chat"
5. Use option 7 for the audio card
6. Receive error message. The card also will not play the audio

## Expected behavior

Card to play the audio.

## Screenshots

![image](https://user-images.githubusercontent.com/40401643/109863590-aab44e00-7c16-11eb-9242-a2dd5129870a.png)

![image](https://user-images.githubusercontent.com/40401643/109863772-e51deb00-7c16-11eb-92c4-469b6fcf9cf4.png)

**Comment by tonyanziano** [comment]
Some findings:

This works in Emulator when run from source, but **does not** work in a production build.

**Comment by tonyanziano** [comment]
We think that this might have something to do with the internal Electron build that we use in the production app of both Emulator and Composer.

The internal build we use might be missing codecs used for certain audio / video playback such as .wav files.

**Comment by srinaath** [comment]
For reference https://microsoft.sharepoint.com/teams/ElectronInMicrosoft/Wiki/Electron-11.2.3.aspx. We currently use the electron version with no FFmpeg codecs. Production support for playing audio files/video files inside Webchat can be supported only if we use a media flavor of the Electron in our build pipelines.
