### ISSUE TITLE
feat: Restarting bot should clear Web Chat?

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/BotFramework-Composer#6129]
1. Chat with bot in integrated Web Chat
2. Restart the bot
3. Re-open the integrated Web Chat and your previous conversation will still be there

## Describe the solution you'd like

Clear the Web Chat history on bot restart.

## Describe alternatives you've considered

Keep things as-is. I personally understand what's going on and the behavior is expected. However, I could see this maybe confusing a new user. Maybe add a "bot restarted" message.

I'm completely fine if no changes get made, but I think this warrants discussion.

## Additional context

![image](https://user-images.githubusercontent.com/40401643/109864861-35e21380-7c18-11eb-8fd6-21380db4e7fe.png)

**Comment by garypretty** [comment]
Thanks @mdrichardson. We may end up taking this change for this and other reasons. 

Closing. Tracking if we will make this change in #6133 .
