### ISSUE TITLE
Link for Delete Bot in Action Menu does not initiate the modal

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6131]
## Describe the bug

Currently, the link for Delete Bot in the Action Menu in Bot Settings does not launch the delete modal. 

## Version

![image](https://user-images.githubusercontent.com/18688053/109865319-84e47480-7c29-11eb-98c5-3f8b158b7b81.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Bot Settings
2. Click on Delete Bot in the Action Bar
3. Needs to launch modal for delete, not scroll to the delete button below

## Expected behavior

Clicking on the delete bot button should launch this modal
![image](https://user-images.githubusercontent.com/18688053/109865662-f15f7380-7c29-11eb-8b52-0d7c7ff8b04a.png)

## Additional context

The design of the modal for delete should be updated to proper design as well.

**Comment by Dewain27** [comment]
@emivers8 has asked that the modal look and behave this way as well...
![image](https://user-images.githubusercontent.com/18688053/109865926-4b603900-7c2a-11eb-8a6a-2bcfa6b84ad3.png)

**Comment by emivers8** [comment]
And actually, missed just a bit of copy on my first pass--

![image](https://user-images.githubusercontent.com/55601267/109876141-413c3b80-7c26-11eb-800d-dbc4074df590.png)
