### ISSUE TITLE
Webchat opens onto skill, not root bot

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#6133]
## Describe the bug

Web chat opens onto skill, not root bot

## Version

1.3.1-nightly.219396

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1, Create a new bot (an empty one, in my sample)
2. Add a skill (I used the standard EchoBot)
3. Start the bots; both of them should start (so you'll see "2/2 running" in the status bar)
4. Open chat
5. The chat will open to the skill, not the root bot (although the title retains the root bot's name)

## Expected behavior

Connecting to webchat should start in the root bot, not a skill.

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/109865909-81e18800-7c19-11eb-880d-20395725f963.png)

**Comment by srinaath** [comment]
@beyackle This is by design for R12. We explored the option but it required more sophisticated UI with multiple tabs in the webchat pane each tab corresponding to a conversation id that could be tied to root bot or skill. This is definitely on the cards once we implement the popout pane for webchat control.

**Comment by garypretty** [comment]
@srinaath Looking at the comments above it appears that webchat is talking to the skill and not the root bot? We should be just surfacing the root bot in R12.  @beyackle can you clarify here?  Were you able to interact with the skill?

**Comment by srinaath** [comment]
I see. Nice catch @beyackle. I will try to get a repro.
