### ISSUE TITLE
Orchestrator fails to install (after successfully installed in another bot)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6134]
Scenario:
1. Create bot, install orchestrator, use orchestrator
2. Create a new bot, try to install orchestrator: no failure code but package do not show up.

See video clip

https://user-images.githubusercontent.com/8867670/109866460-249a0680-7c1a-11eb-92a9-f251ee986a49.mp4

**Comment by scheyal** [comment]
Update. No packages install (not only Orchestrator)

**Comment by a-b-r-o-w-n** [comment]
@scheyal are you only verifying this through the package manager UI? Have you checked to see if they do get installed but the UI doesn't update for some reason? It's possible they are getting installed to the last opened bot as well. Can you check there too?

**Comment by scheyal** [comment]
Update: Issue has to do with path name. Logs show successful install but the UI is not showing the installed packages. Note this is package manager - NOT Orchestrator specific (same with calendar, welcome packages).

...experimental\orchestrator\Composer\SchoolNavigator2 --> Works
...experimental\orchestrator\Composer\01.school-skill-navigator(v1.4)  --> fails

note that we already have samples with bots in folders with numbers and dots, e.g. 01.school-skill-navigator.

**Comment by benbrown** [comment]
@scheyal are you experiencing this issue with the latest builds?

**Comment by benbrown** [comment]
@scheyal This should all be working as expected now. Can you confirm?
