### ISSUE TITLE
Web Chat - after restart conversation, put the cursor in the input box

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#6135]
## Is your feature request related to a problem? Please describe.

No, just related to an extra, annoying step.

## Describe the solution you'd like

After selecting **Restart Conversation - new user ID**, I'd like to just start typing, without having to move the cursor to the input box.

## Describe alternatives you've considered

I can't think of any, unless you add a configuration setting to Composer for this.

## Additional context
Would like the cursor to end up here, after restarting the conversation:
![image](https://user-images.githubusercontent.com/35047199/109866765-8e1a1500-7c1a-11eb-9b48-2e967bcc1f3e.png)

**Comment by a-b-r-o-w-n** [comment]
@JonathanFingold This is a good suggestion, but we would need to get some a11y feedback about this. @beyackle can you think of a reason we may not want to change the focus after starting a new conversation?
