### ISSUE TITLE
ui nitpick: the LG editor should expand so I can see my entire message. 

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#6136]
## Describe the bug

It is quite awkward to edit long messages in the single row LG editor.

This should expand to show my entire message. 

The text of the message is the life and breath of the bot application, it should be front and center.

**Comment by benbrown** [comment]
![Screen Shot 2021-03-03 at 2 22 06 PM](https://user-images.githubusercontent.com/729873/109867389-0b01ba80-7c2c-11eb-9572-28fa3d92ad45.png)

**Comment by iMicknl** [comment]
Faced this myself as well today. As an addition, not just for text messages, but also for conditions. It is hard to write them in such a small textfield. Would be great if it could expand when open.

![image](https://user-images.githubusercontent.com/1424596/109868670-3904f000-7c68-11eb-9e43-fbb77085b983.png)

**Comment by tonyanziano** [comment]
@sangwoohaan is it possible to reassess the height of this control?

**Comment by tonyanziano** [comment]
Possible example: https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield

![Uploading image.png…]()
