### ISSUE TITLE
Bot Responses LG editor should let you use line breaks for multi-line responses

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#6140]
## Is your feature request related to a problem? Please describe.

I'm trying to fix a multi-line template:
- The default has the code hidden.
- When I select a response, the cursor appear where I clicked in the template.
- When I try to enter a return, the pane decides I'm done editing the response.
- Error: I'm surprised and annoyed the first few times this happens.

## Describe the solution you'd like

The editor should be intelligent enough to do one of the following:
1. Not pretend to let me edit a multi-line template without first switching to code view.
2. Let me edit a multi-line template with code hidden, but take a carriage return as part of the template (as opposed to thinking that I'm now done editing the thing.
3. Pop up a warning message that I need to use a ctrl+Enter instead of just Enter to get a line break.

## Describe alternatives you've considered

See the list above.

**Comment by garypretty** [comment]
@sangwoohaan We are not taking this for R12, we will go with the current behavior, but we should consider if there is anything we want to do for R13. Let's discuss on our next sync.

**Comment by mewa1024** [comment]
The response editor does accept Shift-Enter for line breaks. The UI shows this hint when there is no response like this:
![image](https://user-images.githubusercontent.com/39317542/122619544-881f3700-d045-11eb-8da1-9571f283f868.png)

but it doesn't show if you are editing an existing response.

@JonathanFingold sound like you'd like a better hint that you can use Shift-Enter for line breaks?

**Comment by JonathanFingold** [comment]
@mewa1024 I first noticed this in the Bot Responses view:
![image](https://user-images.githubusercontent.com/35047199/122955794-476d3980-d335-11eb-89da-0723c85cd8a5.png)
If you're starting here and editing an existing template, there is no initial hint.
