### ISSUE TITLE
Getting started experience UI issues

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#6142]
## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## Issues

1. UI is not right if file location is long (see below)
<img width="799" alt="image" src="https://user-images.githubusercontent.com/74994573/109870954-8872fe00-7c1f-11eb-9c5b-b73437d6f091.png">

2. After click "add a package", it brings me to another page (package manager),  could it be possible to "go back" to "getting started page" -  since I may not want to install any package, just thought to click around? 

3. "Manage connections" link is not working - if this is intended behaviour, should we disable it (or link to doc) until it can take the user somewhere?
<img width="678" alt="image" src="https://user-images.githubusercontent.com/74994573/109871766-5f9f3880-7c20-11eb-81a5-157f919cef8a.png">

**Comment by cwhitten** [comment]
Closing as this has been completely redone
