### ISSUE TITLE
Bot Responses - add ability to accordion for longer multi-line templates in the non-code view

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#6143]
## Is your feature request related to a problem? Please describe.

It's hard to visually parse longer multi-line templates when you only see three lines at a time.

## Describe the solution you'd like

Either automatically resize the entry for the response up to some reasonable limit (perhaps 7-10 lines), or add a handle so the user can resize it on their own.

## Describe alternatives you've considered

Add ability for an entry in the list to have focus, and then expand the row for the entry to have more space for the multi-line template. (3 lines is not enough.)

## Additional context

This is just enough to be confusing in this view:
![image](https://user-images.githubusercontent.com/35047199/109872586-798d4b00-7c21-11eb-85c0-ba2e820e6156.png)

**Comment by mewa1024** [comment]
Yes, agree with this feedback.
