### ISSUE TITLE
Package install error

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#6144]
## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot using "empty" template
2. Go to 'getting started page'
3. Click on 'add package'
4. Click on 'Bot.Builder.Community.Components.CallDialogs', then 'install'
5. See error.

## Screenshots

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/74994573/109872490-5793c880-7c21-11eb-9bd4-45fe63f4bef3.png">

**Comment by benbrown** [comment]
I believe this is due to an old value in your .composer/extension-data/package-manager.json file. Removing this file and trying again should resolve it.

**Comment by xiyangdesign** [comment]
Thanks. was able to install the package. Although it's not showing in the dialog tree. I assume it takes some time? if so, could we let user know in the UI? (something like: it takes a few minutes to show up?)

Correct me if I'm wrong. It's just that, after the installation, the user doesn't see the changes and don't know where and how to use the package:-)

**Comment by benbrown** [comment]
the results of your install should appear immediately.

in this case, you installed a package of custom actions, which appear in the "+" menu of the dialog editor.
