### ISSUE TITLE
new activities should always have a single response line available

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#6145]
![Screen Shot 2021-03-03 at 3 06 38 PM](https://user-images.githubusercontent.com/729873/109872498-1eb01f80-7c32-11eb-9ce8-88ef650e29f3.png)

if i add a sendactivity or any other type of action that has an LG field, there should always be a text field available by default.

Requiring the user to click "Add a new variation" first seems wrong.

**Comment by garypretty** [comment]
Closing and tracking in #6147
