### ISSUE TITLE
Incorrect autocomplete options inside adaptive card

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#6146]
## Version

1.3.1-nightly.219396.61c944a

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to a Send a Response action
2. Start writing a new response in the code editor, starting with `[AdaptiveCard`, and notice how it helpfully brings up slots for title, subtitle, and so on
3. Write in a value that depends on a variable, like `${turn.activity.text}`.
4. Notice how the suggestions are still the card slots, not autocomplete for the `turn` object.

## Expected behavior

Autocomplete should pay attention to the context it's being used in.

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/109872369-3337ec00-7c21-11eb-91ff-59b53b51f3f6.png)

**Comment by hibrenda** [comment]
@cosmicshuai be aware of this issue.
