### ISSUE TITLE
Show text editor (to add new variation) by default?

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#6147]
## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior

1. Go to 'LG response editor'
2. Click on 'add new variation'
3. The editor shows up, then I was able to add the variation - would it be possible to show the editor by default?

## Screenshots

<img width="367" alt="image" src="https://user-images.githubusercontent.com/74994573/109873502-ae4dd200-7c22-11eb-8e26-f62380c2c3e0.png">

**Comment by garypretty** [comment]
I like this idea and think it makes sense. It was raised by a couple of folks (@benbrown raised in #6145 which I closed to track here).  Is it possible for us to add an empty text box and apply focus there when you first add this action to the canvas?

**Comment by garypretty** [comment]
@srinaath I have spoken with @sangwoohaan and we will take this one.

**Comment by sangwoohaan** [comment]
Here's what we discussed :
The LG editor exists in Send Activity and all the prompt action nodes, and we want the experience to be consistent throughout these. 

1. When you just created a node, the text box appears.
2. When you deselect the node and select again, the text box does not appear, you see 'add variation' button. (Alternative : text box appears when the tab has no content)
3. Adding a new tab would have the same behavior.
4. Pressing the enter key with the text box focused will commit the content, and immediately move onto another text box focused state.

Although as Soroushi pointed out, there's a potential accessibility issue related to the text reader. I will check in with Corina.
