### ISSUE TITLE
Package Manager error on Calendar Assistant

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#6148]
## Describe the bug
Clicking on Package Manager for calendar bot (installed with Calendar Assistant) fails.

## Version

`1.3.1-nightly.219396.61c944a`

## Browser

- [X] Electron distribution

## OS
- [X] Windows

## To Reproduce

- Installed "Calendar Assistant" in Setup.
- After some time, I landed on some page prompting for LUIS keys.  I exited out of that (went to overall Home).
- The "Calendar Assistant" appears to have set up 2 bots - I loaded "calendar" (as opposed to "calendar_assistant").
- I clicked on the Package Manager icon on the left and it fails..

## Screenshots

![image](https://user-images.githubusercontent.com/6182197/109873917-477ce880-7c23-11eb-9ef2-cfb2c2d70346.png)

## Additional context

Probably not Orchestrator related - just following Setup portion of bugbash..

**Comment by benbrown** [comment]
@daveta  I believe this was a point in time error with the packages. Can you try again with a newer build?
