### ISSUE TITLE
Composer built bot with adaptive card greet does not show the card when embedded WebChat is launched

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6152]
## Describe the bug
I think I understand why this is, though the behavior isn't what I believe the user would expect.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer
2. Open a bot that has a greeting and that greeting sends an adaptive card.  
3. Start the bot
4. From the notification windows presented when the bot has been started, click the "Open in WebChat" link

## Expected behavior
I would expect to see my greeting card how up once WebChat is connected for the first time.
I can get the welcome card to show if I click the "Restart Conversation" from the WebChat embedded window

**Comment by srinaath** [comment]
Closing after trying a repro with @sgellock . The Webchat control is able to handle adaptive card greetings.
