### ISSUE TITLE
Visual glitch: wrong background for new Bot Settings header notification

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#6154]
## Version

1.3.1-nightly.219396.61c944a

## To Reproduce

1. Go to the new bot settings page while a notification is active (with a ⚠ or 🛑 icon)

## Expected behavior

The notification icon/number should get the same "dark mode" treatment as the rest of that new header block and toolbar.

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/109877608-1521ba00-7c28-11eb-937e-da4e68c1cdec.png)

**Comment by cwhitten** [comment]
Closing as the UI has been completely redone
