### ISSUE TITLE
can't really see the error/warning

### ISSUE THREAD

**Issue by tsuwandy** [microsoft/BotFramework-Composer#6155]
## Describe the bug
Created new bot using the Calendar assistant template.  Once it's loaded, I see the 2 errors and 1 warning BUT it's not possible to see what those errors and warning are due to the section in the UX, see screenshot.  From previous experience using Composer, I know that it's missing LUIS key but it'd be much more helpful to be able to see the errors and warning.

## Version
v 1.3.1 nightly

![image](https://user-images.githubusercontent.com/10739108/109879087-fc1a0880-7c29-11eb-9413-3e0cf2967dc5.png)

![image](https://user-images.githubusercontent.com/10739108/109879027-ec022900-7c29-11eb-9ae6-015103389701.png)

**Comment by tonyanziano** [comment]
Related to #6121
