### ISSUE TITLE
Links from project settings page are slow to load (slower than using Composer's main menu)

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#6161]
The "Next Steps" links at the top of the project settings page are slow to load and are slower than navigating to the page with Composer's main menu.

## Version

Version:  1.3.1-nightly.219396.61c944a
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot. In this case I chose "Calendar"
2. When the project settings page loads, click on any of the links in the "Next steps" section here:
![image](https://user-images.githubusercontent.com/39317542/109881506-45b82280-7c2d-11eb-9cc2-f87a40417785.png)
3. The section takes several seconds to load, whereas when you click on the same section in the main menu, it loads in less than a second. 

https://user-images.githubusercontent.com/39317542/109882412-adbb3880-7c2e-11eb-8518-5d36a5924eb8.mov

## Expected behavior

If the links are just navigating, I'd expect the load time to be the save as using the main menu.

**Comment by benbrown** [comment]
WEIRD. It must be calling a different navigation method. I'll investigate!
