### ISSUE TITLE
Publish & Provision: Option to populate App Id/Pw and LUIS keys from the provisioned resources

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#6162]
## Describe the solution you'd like
When I'm starting with a template that requires LUIS and auth, I need to provision resources before I can run the bot. When I provision the app id and luis resources I may want those to be used as the primary settings in appsettings so a checkbox to copy those values over would help me get up and running faster

**Comment by GeoffCoxMSFT** [comment]
I think we should close this.  Em and Jas have plans for the revamped UI and Dewain is aware of the need to reconcile local app settings and publishing profiles.
