### ISSUE TITLE
Provision of Speech Service should happen as part of the Connection Activation

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6166]
## Issue

When you are enabling the Speech Channel, it requires that you have provisioned a Speech Service ahead of the enablement.  

## Describe the solution you'd like

The flip of the switch in the Composer UI should provision the Speech Service ahead of the process of enabling the channel.  This should be done by asking the publishing profile and verifying if the profile already has a speech service or if one is needed to be provisioned.  We should also support the ability for a user to say that they want to re-use an existing speech service, however we should warn that there can only be one default service for a speech service.

**Comment by Dewain27** [comment]
@emivers8 we will need to get the process mocked up to make sure that the development team has the right UX for this experience and it needs to align to the new UX for Connections.

**Comment by benbrown** [comment]
For context this would touch:

* Adding speech as a provisionable service in the provisioning system (medium LOE)
* Changing provisioning modal system to accept parameters - ie, open provisioning to the "add a speech service" screen (small)
* Allow selection of previous of existing speech services in this AND make that work alongside the other provisioning behaviors (large)
