### ISSUE TITLE
Publish Configure resources modal apparently hangs on failed login

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#6170]
## Version

1.3.1-nightly.219396.61c944a

## To Reproduce

1. Go to the bot settings page
2. Add a new publishing profile
3. Fill in a name and type, and hit "Next"
3. Close the sign-in modal that appears
4. See the spinner keep going
5. You can also try selecting Import and then Create again; instead of letting the user try to log in again, there's just the spinner there.

## Expected behavior

The flow through the modal should be redesigned to allow for a failed login to do something useful (go back to try again? cancel the whole thing? I don't know what the right call here is)

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/109891201-8455d900-7c3d-11eb-8a41-4a1e3a3df379.png)

**Comment by benbrown** [comment]
same as #6171

**Comment by cwhitten** [comment]
Closing as a dupe
