### ISSUE TITLE
LG template auto-created ID name does not sync

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#6173]
1. Open TodoforLUIS
2. Go to 'User profile' dialog
3. Click first action node : Send a reponse
4. Notice template name = Template name: #TextInput_Prompt_267073() at bottom of edit field).
5. Click template name
6. Notice this results in a navigate to 'bot responses > UserProfile'
7. Figure out which template name you actually clicked (#textInput_Prompt_267073)
8. Change template name to 'AskUserName'
9. Figure out how to get back to the dialog flow you came from
10. In Design view, click User profile dialog > begin dialog > 
11. Notice that first action node now has the name 'AskUserName' in the action node, at the top of the property panel but NOT in the template name below the monaco editor.

Expected:
1. Open TodoforLUIS

2. Go to 'User profile' dialog

3. Click first action node titled: (WAS: Send a reponse) - **Expected: #TextInput_Prompt_267073**

4. Notice template name = Template name: #TextInput_Prompt_267073() at bottom of edit field).

5. Click template name

6. Notice this results in a navigate to  (WAS: 'bot responses > UserProfile' ) **Expected: bot responses > UserProfile > #TextInput_Prompt_267073 (selected)**

7. Was: Figure out which template name you actually clicked (#textInput_Prompt_267073) **Expected: this template should be selected to correspond with what you clicked'**

8. Change template name to 'AskUserName'

9. Figure out how to get back to the dialog flow you came from - Expected: **In the column called 'used in' (today called: 'been used'), click on 'user profile, begin dialog'  and navigate to 'Design view' with that node selected.**

10. Was: In Design view, click User profile dialog > begin dialog > Expected: you're already in the right dialog with the right action node selected.

12. Notice that first action node now has the name 'AskUserName' in the action node, at the top of the property panel  
WAS: but NOT in the template name below the monaco editor.
**Expected: template name is also renamed**

![Screen Shot 2021-03-03 at 4 38 22 PM](https://user-images.githubusercontent.com/48503434/109894151-d1d44500-7c41-11eb-9da0-dd78dd5feab8.png)
![Screen Shot 2021-03-03 at 4 37 12 PM](https://user-images.githubusercontent.com/48503434/109894154-d3057200-7c41-11eb-95bc-76bd2c4fb95a.png)
![Screen Shot 2021-03-03 at 4 41 39 PM](https://user-images.githubusercontent.com/48503434/109894162-d6006280-7c41-11eb-8f46-f9e3380af8fe.png)

**Comment by tonyanziano** [comment]
We would classify this as Composer missing some refactoring tools for LG and not necessarily a bug as nothing is broken. @garypretty maybe you could work with @mareekuh on this.

**Comment by sangwoohaan** [comment]
Changing the template name there should pop-up a dialog asking if you want to update the template name reference in the activity.

**Comment by mareekuh** [comment]
Sending it back to you, @sangwoohaan  (and Melanie) - I think we need to simplify. 
Please reconsider Tom's observations and my suggestions above.

**Comment by sangwoohaan** [comment]
Yeah this is supposed to be what you are describing above. Do we want this to be in by BUILD?

**Comment by mareekuh** [comment]
by now the door to Build has closed but yes would be great to address this.

**Comment by mewa1024** [comment]
(@sangwoohaan can you keep me in the loop? it sounds like an implementation gap rather than change to the design.)
