### ISSUE TITLE
New Creation Experience preview feature is missing a "Learn More" link

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6174]
## Describe the bug
Every preview feature in composer must follow a format that is a "title" a "description" and a "Learn More" link.  the Learn More link navigates to an external link that describes what the preview feature does and why you might want to enable it and try it out.

## Version
1.3.x the R12 bug bash build

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer
2. Click on the Composer Settings icon in the lefthand nav to launch the Application Settings page
3. Scroll down to the Preview features section
4. Note that the "New Creation Experience" feature has a title and a description, but is missing the Learn More link

## Expected behavior
working or at least a stubbed Learn More link

**Comment by benbrown** [comment]
@Dewain27  we need to create some doc that describes what this new creation flow is!
