### ISSUE TITLE
Default for 'condition' should be 'expression' and gray area (y/n) should be clickable

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#6176]
![Screen Shot 2021-03-03 at 5 01 57 PM](https://user-images.githubusercontent.com/48503434/109894545-8b331a80-7c42-11eb-961c-5ef565664ab8.png)

Go to todobotwithLUIS - click 'Welcome User' trigger 
Notice 'condition' field at top in Property panel
Notice the type is set to y/n 
Click on gray area y/n in field to change it to expresion - Notice nothing happens
Click dropdown to change setting to 'Expression' (vs boolean)

EXPECTED:  Default for 'condition' is set to Expression
EXPECTED: Click on dropdown or click on the gray y/n area within the field  - both display dropdown

**Comment by tonyanziano** [comment]
@sangwoohaan can you please take a look at this?

**Comment by sangwoohaan** [comment]
@garypretty and I just talked about this actually. I'll handle this – the header isn't a clickable UI element anymore so the plan is to have it default to expression according to our current experience.

**Comment by mewa1024** [comment]
Not sure if this was fixed, but this is the current dropdown:
![image](https://user-images.githubusercontent.com/39317542/124072645-e4933680-d9f5-11eb-86ff-680176a03639.png)
