### ISSUE TITLE
Getting Started link on Home page should nav to Composer docs, not our GH repo

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6177]
## Describe the bug
At least for the Electron distro, I would expect getting started to take me to the same page that Help -> Documentation from the top-level app menu take me.

We have a Help -> Composer on GitHub link in that top level Help menu, so we are providing an option to get to the repo.

I would assert that if I have composer installed and I click the Getting started, I would expect to get started building bots with composer, not building and modifying composer itself.

## Version
1.3.x R12 bug bash
## Browser
- [X ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer
2. Click on 'Getting Started' link found on the Composer home page

## Expected behavior
I would have expected to have the following URL open in my browser:
https://docs.microsoft.com/en-us/composer/

**Comment by beyackle** [comment]
The URL in Composer points to an `aka.ms` link (https://aka.ms/BF-Composer-Getting-Started), so we don't need a code change here, just a reroute from that URL to the docs.

**Comment by sgellock** [comment]
Makes sense Doc.  Thanks!

**Comment by cwhitten** [comment]
@Kaiqb can you please address this? Thanks.
