### ISSUE TITLE
Show code for selected item

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#6178]
Go to TodobotwithLUIS
Go to 'welcome user'
Select 'Set properties' node
Click 'Show code'
Notice: the entire JSON is shown

Expected: jump to the right place in the code (selected node)
![Screen Shot 2021-03-03 at 5 22 05 PM](https://user-images.githubusercontent.com/48503434/109895978-04cc0800-7c45-11eb-80c4-1764149e8ca5.png)

**Comment by tonyanziano** [comment]
Related to #6110
