### ISSUE TITLE
"Problem" drawer disappears on the Project Settings page when you collapse it

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#6180]
## Describe the bug

Problems drawer disappears instead of collapses on the Bot Projects settings page. It also seems to return to the default height when you navigate from page to page.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Collapse the Problems drawer by clicking on the down chevron. Here's the drawer open
![image](https://user-images.githubusercontent.com/39317542/109898229-ba4c8a80-7c48-11eb-9faf-a182bbc69cde.png)

2. When it is closed, it disappears altogether:
![image](https://user-images.githubusercontent.com/39317542/109898654-727a3300-7c49-11eb-9b3b-ece6b22bfc18.png)

For the drawer height, on the other pages, it seems to return to the default height.
1. Go to the design page. 
2. Expand the drawer:
![image](https://user-images.githubusercontent.com/39317542/109898957-ef0d1180-7c49-11eb-9755-0c51c79f0d35.png)

3. Drag the top bar down to reduce its height:
![image](https://user-images.githubusercontent.com/39317542/109898995-fdf3c400-7c49-11eb-99ed-75cda4e724a4.png)

4. Navigate to another page. The drawer seems to return to its default height:
![image](https://user-images.githubusercontent.com/39317542/109899045-15cb4800-7c4a-11eb-8211-481d336fdf55.png)

## Expected behavior

I expected the drawer height to persist across pages.

**Comment by mewa1024** [comment]
Version:  1.3.1-nightly.219396.61c944a
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by srinaath** [comment]
Assigning to @benbrown as its going to be resolved with the dashboard refactor.

**Comment by benbrown** [comment]
Resolved by #6121
