### ISSUE TITLE
Project tree is missing the expand/collapse at the root bot

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#6181]
## Describe the bug

In the Design page, the arrow that collapses and expands the root bot disappears sometimes.

## Version

Version:  1.3.1-nightly.219396.61c944a
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot.
2. Go to the design page. Look at the project tree. The arrow by the root bot is missing:
![image](https://user-images.githubusercontent.com/39317542/109906235-f7b71500-7c54-11eb-8451-850d85fd22e0.png)

## Expected behavior

Should look like this (seems to work in either older bots or projects with only one bot):
![image](https://user-images.githubusercontent.com/39317542/109906421-4ebcea00-7c55-11eb-82b9-5b7484884f83.png)

**Comment by mewa1024** [comment]
also, the arrow only disappears after the skill is loaded. Before the skill loads, the arrow is there:
![image](https://user-images.githubusercontent.com/39317542/109906620-ad826380-7c55-11eb-97c2-f692a425f385.png)

**Comment by beyackle** [comment]
I'm working on this one and I've been having trouble reproducing it. I'll keep looking, but the cases reported here seem to work fine for me. 
![image](https://user-images.githubusercontent.com/61990921/110036727-4ff02480-7cf2-11eb-83bb-10a1c327378c.png)

**Comment by mewa1024** [comment]
I can check and again and screen record, if that is helpful.

**Comment by mewa1024** [comment]
Screen recording of the issue. 
Version:  1.3.1-nightly.221407.6d6cbe2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0


https://user-images.githubusercontent.com/39317542/110676347-b52b9600-8188-11eb-98ca-738fe943f911.mov
