### ISSUE TITLE
The progress bar for check updates always show 0%

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#6182]
- Install composer electron 1.3.1
- click check updates
- the status bar always show 0% 
![image](https://user-images.githubusercontent.com/43408889/109907891-3fce4a00-7cde-11eb-939a-c63645470bcb.png)

**Comment by cwhitten** [comment]
I think this may be a Windows only issue.

**Comment by boydc2014** [comment]
@zhixzhan can you help check this one?

**Comment by zhixzhan** [comment]
> @zhixzhan can you help check this one?

OK, I can take this

**Comment by zhixzhan** [comment]
dulplicated to https://github.com/microsoft/BotFramework-Composer/issues/5551

1.3.1 released on 14 Jan, 
The fix https://github.com/microsoft/BotFramework-Composer/pull/5573 is checked in main on 22 Jan

and I checked recent nightly build, works well
