### ISSUE TITLE
new created template in common.lg should be visible in lg manaco editor 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#6183]
- create new template in LG all up view common.lg
 
![image](https://user-images.githubusercontent.com/43408889/109908512-6345c480-7cdf-11eb-9dc2-2b2fcf84bd28.png)

- in send response, the new added template could not be visible 
![image](https://user-images.githubusercontent.com/43408889/109908625-92f4cc80-7cdf-11eb-92ea-48866adabc7b.png)

**Comment by liweitian** [comment]
Hi @hibrenda  @boydc2014 @lei9444 @zhixzhan, this is not a "bug". 
Once we update on common.lg, we will reparse all other lg files. We put the parse process into a worker, so we need wait several seconds for the data refresh.

**Comment by boydc2014** [comment]
Close this due to by design, we will continue optimize the performance here.
