### ISSUE TITLE
Bot capturing the default intent Always

### ISSUE THREAD

**Issue by mn-invia** [microsoft/BotFramework-Composer#6184]
Hi There,

I am in the process of building a bot to perform task based on CANCEL as the Intent. That's the ONLY intent that's been built-in so far. The Bot behaves perfectly when I chat and input queries.

But when I cut and paste messages from email, IRRESPECTIVE of the content in the email, LUIS always gives a score of more than 99% and sends it over to the Cancel Intent.

Examples of email that I am cutting and pasting:
**The First email is clearly for Suspension and not Cancellation**
1. Can you please suspend the following services:
- Zoltan Power 04XXXXXXXX – no longer in business (04/09/2019) - last activity 21/1/2021 voicemail from 02XXXXXXX
- Greg Campbell 04XXXXXXXX (left in 2018) – no longer in business (30/04/2019) - last activity 26/1/2021 voicemail from 02XXXXXXXX 
 
The Second email is just a Normal Conversational text
2. Very Good Morning.
Don’t you worry……It’s all Good. I will explain some time later what I was looking for….but for now, it’s all Good. Take care.

**Why is Luis not capturing the intent when I paste the email text as Input?  Can you help me please?**

Attached is the screen shot and Luis Trace. Many Thanks.

![MicrosoftEmulatorScreenShot](https://user-images.githubusercontent.com/79118685/109911353-073e6880-7cfe-11eb-937f-0cf206f48964.png)

**Luis Trace:**

```json
{
  "recognizerResult": {
    "alteredText": null,
    "entities": {},
    "intents": {
      "CancelPhoneService": {
        "score": 0.992894769
      }
    },
    "text": "Very Good Morning.  Don’t you worry……It’s all Good. I will explain some time later what I was looking for….but for now, it’s all Good. Take care."
  }
}
```

**Comment by dmvtech** [comment]
Hi @mn-invia Do you have an unknown intent trigger setup as well (what all triggers do you have)? Do you have other dialogs but only the Cancel intent? Are you able to share your bot?

**Comment by mn-invia** [comment]
Hi Dana,

Yes I do have an UNKNOWN Intent Trigger setup as well. There are currently ONLY 2 triggers, One is CANCEL and other one is UNKNOWN. Let me know how I can share my bot with you? Many Thanks.

**Comment by dmvtech** [comment]
@mn-invia The easiest way is to put your bot in a repository here on github. You can either make it public (removing any personal sensitive information) or private and then invite me to use it. You can also zip it up and send me a link.

**Comment by carlosscastro** [comment]
@mn-invia have you shared the bot with us? Closing the issue but feel free to re-activate and share the bot.
