### ISSUE TITLE
Package Manager page does not list Orchestrator

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#6187]
## Describe the bug

In the Package Manager section, the Orchestrator package does not appear/

## Version

Version:  1.3.1-nightly.219396.61c944a
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. I was following this step in the Orchestrator bug bash instructions:
![image](https://user-images.githubusercontent.com/39317542/109914045-f9d4a000-7c63-11eb-8a77-9485c806b33f.png)

2. In Package Manager, under the Browse tab, I only see two packages:
![image](https://user-images.githubusercontent.com/39317542/109914089-11138d80-7c64-11eb-9682-2480003e6073.png)

and only one installed:
![image](https://user-images.githubusercontent.com/39317542/109914107-1cff4f80-7c64-11eb-9adb-33043b255cdf.png)

Do I need to edit my feeds? Do I need to reset my feeds to default?

## Expected behavior
I expected to see more packages. I'd also expect the package manager feeds to be in Composer settings, if they effect all my bots, instead of in the package manager.

**Comment by benbrown** [comment]
I believe this is due to the feed being out of date in your composer settings.

You should see 4 packages, including orchestrator.

**Comment by mewa1024** [comment]
Is the feeds surfaced in the UI on the Composer Settings page? (I didn't see anything there.)

**Comment by benbrown** [comment]
click edit feeds at top

**Comment by benbrown** [comment]
@mewa1024 have you been able to rectify this issue?

if not i can jump on a chat..

**Comment by mewa1024** [comment]
no, Orchestrator still doesn't show up--but what feeds should I be using? This is what I have:
![image](https://user-images.githubusercontent.com/39317542/110157739-6606ef00-7d9d-11eb-871c-6533fc7dbe8e.png)

**Comment by benbrown** [comment]
This is the old feed. 

The new one is:
https://api.nuget.org/v3/index.json

**Comment by mewa1024** [comment]
That worked. Is there anywhere in the UI where the user can get the latest feeds? Like "Restore to defaults" or something? I could not find it anywhere.

**Comment by mewa1024** [comment]
Also, your list of feeds are Composer-wide, not project-specific, right?

**Comment by boydc2014** [comment]
@taicchoumsft can you comment on this one?

**Comment by mewa1024** [comment]
Changing the feed manually as Ben described above worked, so I can close this bug. Thanks!
