### ISSUE TITLE
"SyntaxError - Unexpected token o in JSON at position 1" when publishing from bot framework composer Windows

### ISSUE THREAD

**Issue by Jenny0932** [microsoft/BotFramework-Composer#6191]
I attached the following log.
I am using bot framework composer 1.3.1 desktop version on Windows. I have tried adding luisResource and hostname. It's still the same error.

"Accepted for publishing..."

"Building the bot app..."

"Build succeeded!"

"start publish luis"

"Assigning to luis app id: 6ffff2f4-1e4a-48db-bb6b-3b7bb4941a0a"

"{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\",\"error\":{\"error\":{\"message\":\"Failed to parse azure account information object object.\"}},\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - {\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"Failed to parse azure account information object object.\\\"}}\\n    at new i (C:\\\\Users\\\\jenny.xue.wei\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:110597)\\n    at F.callback (C:\\\\Users\\\\jenny.xue.wei\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:109440)\\n    at F.e.callback.t.callback [as _callback] (C:\\\\Users\\\\jenny.xue.wei\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:338:108488)\\n    at F.t._callback.t.callback.t.callback (C:\\\\Users\\\\jenny.xue.wei\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:4017)\\n    at F.emit (events.js:210:5)\\n    at F.<anonymous> (C:\\\\Users\\\\jenny.xue.wei\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:16714)\\n    at F.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Users\\\\jenny.xue.wei\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:368:15546)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"

"{\"stack\":\"SyntaxError: Unexpected token o in JSON at position 1\\n    at JSON.parse (<anonymous>)\\n    at Object.<anonymous> (C:\\\\Users\\\\jenny.xue.wei\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:115579)\\n    at C:\\\\Users\\\\jenny.xue.wei\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:112703\\n    at Object.throw (C:\\\\Users\\\\jenny.xue.wei\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:112808)\\n    at s (C:\\\\Users\\\\jenny.xue.wei\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:392:111573)\",\"message\":\"Unexpected token o in JSON at position 1\"}"

"SyntaxError - Unexpected token o in JSON at position 1"

**Comment by Rekeyea** [comment]
I think this is still an unresolved issue. A workaround for me was to use the web version to publish.

**Comment by tonyanziano** [comment]
@luhan2017 can you please investigate?

**Comment by Jenny0932** [comment]
Does it related to LUIS server issue?
![image](https://user-images.githubusercontent.com/21092475/110044450-4243a900-7d9d-11eb-8f24-b4f6161f1f4c.png)

**Comment by daveta** [comment]
@luhan2017 : Any updates?

**Comment by luhan2017** [comment]
@Jenny0932, sorry for the late response, I heard some similar issues about this, they confirmed that it is a luis server issue and it is working well now, could you please try again to see if the issue still exists? Thanks.

**Comment by carlosscastro** [comment]
@Jenny0932 we tried on our side and confirmed that this is working for us. Closing for now, but please reactivate if you are still experiencing this issue.
