### ISSUE TITLE
Install of package fails in Package Manager for Storage Components

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6201]
## Describe the bug

When trying to install the nuget package for Bot.Builder.Community.Components.Storage and installing 1.0.2-preview, get install Error Command failed: dotnet add empty.csproj package

## Version

![image](https://user-images.githubusercontent.com/18688053/109972666-3385c500-7cbd-11eb-9c69-a672ff1e9a85.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Empty bot template project
2. Go to Package Manager
3. Select nuget for package type
4. Try to install Bot.Builder.Community.Components.Storage package at 1.0.2-preview
5. Get Error
![image](https://user-images.githubusercontent.com/18688053/109972483-f4f00a80-7cbc-11eb-88ff-cde249b13dd4.png)

## Expected behavior

Package Installs successfully

**Comment by carlosscastro** [comment]
@Dewain27 could you try one thing for us: Could you please add a new feed with this url `https://api.nuget.org/v3/index.json`?

And if it fails, could you navigate in command line to the directory where your runtime csproj file is, and run the command that you get in the error message (i.e. dotnet add ...) and copy the output? That would all be incredibly helpful.

+ @benbrown  FYI

**Comment by benbrown** [comment]
If you delete the .composer/extension-data/package-manager.json file, this problem will go away. this will reset package manager to the new default settings for the feed URLs.

OR, you can do as carlos described above and add a new feed.
