### ISSUE TITLE
[when authoring a bot] trigger configuration needs more clarification?

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#6204]
1. the user creates a new bot
2. the user clicks on the trigger, the configuration shows
3. it's not clear what the three settings are and how to use them.
![TriggerSettingNeedsMoreClarification](https://user-images.githubusercontent.com/74994573/110005867-ccbcd780-7ccd-11eb-8342-9cb056501732.png)

**Comment by cwhitten** [comment]
@xiyangdesign do the ? tooltips help at all on these fields?

**Comment by xiyangdesign** [comment]
Not really. See the tooltips below.

![image](https://user-images.githubusercontent.com/74994573/110049303-715b0b80-7d06-11eb-8723-f78b9b2c5973.png)
![image](https://user-images.githubusercontent.com/74994573/110049316-76b85600-7d06-11eb-8b22-b36b44747f92.png)
![image](https://user-images.githubusercontent.com/74994573/110049327-7cae3700-7d06-11eb-987e-1aeb819af910.png)
