### ISSUE TITLE
Bot Framework Composer won't store conversation transcripts.

### ISSUE THREAD

**Issue by marvin-garcia** [microsoft/BotFramework-Composer#6206]
I created a bot, created a publish target (using Azure Web App option) and made sure all the optional services were checked. After the publish profile creation succeeded, an empty (no containers) storage account was in the bot's resource group. Then I successfully published my bot, but when I started using it no conversation transcripts were created. I looked into the appsettings.json file; copied the blobStorage.container name and created a container in the storage account with it, but even after that the container is empty.

## Version
Bot Framework Composer
Version:  1.3.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Channels
Bot Framework Emulator
Microsoft Teams

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot
2. Create a publish profile, ensuring the storage account resource is selected
3. Publish the bot
4. Chat with the bot through the channel of your preference
5. Go to the Azure portal, find the created storage account, see its containers and their content

## Expected behavior
Not a single container or an empty container called 'transcripts'.

**Comment by dmvtech** [comment]
@marvin-garcia I am looking into this. Aside from the steps above, you are not using a node or customized runtime, correct?

**Comment by marvin-garcia** [comment]
@dmvtech I'm not using any customized runtime. Let me know if you need specific screenshots of log info from the composer.

**Comment by dmvtech** [comment]
Thanks @marvin-garcia Are you able to update Composer to v1.4.0 and try?

**Comment by dmvtech** [comment]
Hi @marvin-garcia Just checking in. Can you test with 1.4.0?

**Comment by dmvtech** [comment]
Closing due to lack of response. Please comment if assistance is still needed on this.

**Comment by marvin-garcia** [comment]
Hi,

I have not had a chance to test it again, I will have time to run it next
week and will let you know.
Marvin Garcia
Tel: +1 214.668.9916
