### ISSUE TITLE
Icon crowding when update available

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#6215]
## Describe the bug
The icons on the header appear really crowded when a Composer update is available.

Expected:
Fix to make sure icons are evenly spaced when update is avaiable

![Screen Shot 2021-03-04 at 1 21 59 PM](https://user-images.githubusercontent.com/13004779/110032132-a5293780-7cec-11eb-87ea-6709168f971d.png)

**Comment by mewa1024** [comment]
Do we need to have this icon here? It is crowded and it is less directly related to the Start bots button than Webchat.

**Comment by mewa1024** [comment]
(@sangwoohaan fyi, we are moving the "updates available" icon to the left of the bell to keep the Web Chat icon closer to the Start button. Also, adding padding between the icons.)

**Comment by sangwoohaan** [comment]
What is the icon between the runtime manager icon and the webchat icon?

**Comment by srinaath** [comment]
@sangwoohaan  its the app updater icon. In addition, i feel like that icon doesn't match for app update available. Do you think we need a different icon?
