### ISSUE TITLE
Remove dialog error

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6223]
Several issues showed up, one captured here.

Repro:
1. Create new dialog
2. Rename dialog
3. Remove dialog
--> the error below.

ENOENT: no such file or directory, scandir 'c:\workspace\botroot\TempPlay\MultilingualOrchestrator\MultilingualOrchestrator\dialogs\TestDialog\recognizers'

**Comment by cwhitten** [comment]
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/1741
