### ISSUE TITLE
Bot Creation experience needs to communicate more during creation process

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6224]
## Is your feature request related to a problem? Please describe.

The creation flow shows this
![image](https://user-images.githubusercontent.com/17789481/110052250-217f4300-7d0c-11eb-92ed-23f75f75bd9d.png)
for a VERY long time.  (3-4 minutes?) 

We need to have a progress indicator that is more granular, because it feels like it's hung.

## Describe the solution you'd like

a progress bar with % visualization
![image](https://user-images.githubusercontent.com/17789481/110052334-4ecbf100-7d0c-11eb-9a86-9719f47a3cc3.png)

## Describe alternatives you've considered

Don't take so long :)

**Comment by hatpick** [comment]
#6323 moves the creation to worker thread

**Comment by xiyangdesign** [comment]
Proposed design here: https://www.figma.com/file/pghEVhZEtMsXae9IHybdYo/Composer-Xi-s-workspace?node-id=595%3A2114

Let me know if you have any questions.
