### ISSUE TITLE
nonstandard button for saving new feed is super confusing

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6226]
## Describe the bug

I tried to add a new feed.  The Green check box doesn't communicate that you need to push it to commit the change. 

I couldn't figure out why it wasn't saving my change.  It said "you haven't saved it" and I STILL didn't realize the green check mark was to save the change. 

We should use an industry standard icon for saving.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Packagemanager add feeds
2. add a feed "c:\nuget"  This green check box totally failed to communicate what it was for.  I thought it was telling me that I had typed in a valid path.  It didn't look like a button and it didn't communicate that it was required to save. 
![image](https://user-images.githubusercontent.com/17789481/110053268-ebdb5980-7d0d-11eb-8f1a-f0971a3e5a60.png)

## Expected behavior
I think a button with "SAVE" or standard SAVE icon should be used.
![image](https://user-images.githubusercontent.com/17789481/110058190-c737af80-7d16-11eb-8b34-5c9796df8a74.png)

## Screenshots
Once I save we use industry standard icons for edit and delete, and it's completely clear.
![image](https://user-images.githubusercontent.com/17789481/110053376-25ac6000-7d0e-11eb-8e99-38818a6fe91a.png)

Also, look at the usage of green checkmark on this page, where it's not a button for saving at all.  
![image](https://user-images.githubusercontent.com/17789481/110056970-93f42100-7d14-11eb-985f-c156b7b9a6e7.png)

**Comment by benbrown** [comment]
There is actually a PR open that includes a revision of this UI that and does away with the need to click a save button at all. (updates are saved when you click done)

Should be fixed in #6219
