### ISSUE TITLE
Microsoft.Bot.Builder.Integration.Runtime doesn't have Bot Framework ICON

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6227]
## Describe the bug
There should be an icon

![image](https://user-images.githubusercontent.com/17789481/110053480-5a201c00-7d0e-11eb-90d1-5406323eb018.png)

## Version
![image](https://user-images.githubusercontent.com/17789481/110053494-61472a00-7d0e-11eb-88b4-1332b95926e2.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

go to packagemanager and view

## Expected behavior

The bot framework icon

**Comment by hatpick** [comment]
@benbrown can you check this?

**Comment by benbrown** [comment]
resovled.
