### ISSUE TITLE
Packagemanager doesn't handle local folder nuget feed

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6228]
## Describe the bug

Nuget toolchain supports a local folder with nupkgs in it as a valid feed. Composer doesn't list any packages from taht.

## Version

![image](https://user-images.githubusercontent.com/17789481/110053762-d286dd00-7d0e-11eb-8bda-292f10215d78.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to package manager
2. add c:\nuget folder with valid .nupkgs in it.
3. Try to browse using composer, it shows no packages.
If you use file://c:/nuget  you get

![image](https://user-images.githubusercontent.com/17789481/110054003-30b3c000-7d0f-11eb-982b-100ce7ee58b3.png)

## Expected behavior

You should be able to use a local folder with nupkgs for local developmenet and consumption. 

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/110053899-fe09c780-7d0e-11eb-858f-82fc21106b40.png)

**Comment by benbrown** [comment]
We currently support this style of local feed, which requires the packages to be "added" to a feed:
https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds

We'll look into also supporting the "folder full of nupkgs" approach.
