### ISSUE TITLE
packagemanager Doesn't update the UI after editing a url

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6229]
## Describe the bug

I tried to add a package url and failed.  Then I tried to edit it, and I can't edit it, it silently doesn't save.

## Version

1.3.1-nightly.218992

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to package manager and add feed http://127.0.0.1:1000/xy/z
2. it fails with error, now try to put correct value it https://localhost:5001
3. hit checkbox, it doesn't update the url in the display. If you hit Edit again, you see the https://localhost:5001 url which is correc.t
4. if I hit DELETE icon, it doesn't delete it either. I have zombie feed entry :(

## Expected behavior

to update the display

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/110054852-b8e69500-7d10-11eb-8db1-3a6b9c0f807f.png)
![image](https://user-images.githubusercontent.com/17789481/110054865-bd12b280-7d10-11eb-94df-aa8446af3870.png)

**Comment by hatpick** [comment]
#6219 Does this address the issue above? @benbrown if yes, please tag this issue under that PR.

**Comment by benbrown** [comment]
This has been resolved with some different UI elements in the feed editor.
