### ISSUE TITLE
PackageManager doesn't show my package icon

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6230]
## Describe the bug
The icon for a package is part of the identity for a package.  PAckageManager is ignoring my nupkg icons.

## Version

1.3.1-nightly.219713

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to packagemanager 
2. add feed for https://www.myget.org/F/iciclecreek/api/v3/index.json
3. View feed, all of the icons are giant verticle white bars

## Expected behavior

It should show my package icon (aka, my product brand)

## Screenshots
Here's what you get on nuget
![image](https://user-images.githubusercontent.com/17789481/110055903-aec59600-7d12-11eb-868a-81b3f0837e44.png)

Here's what you get on composer:
![image](https://user-images.githubusercontent.com/17789481/110055925-bab15800-7d12-11eb-8047-849d8ca55a2c.png)

**Comment by benbrown** [comment]
Should be resolved in the latest, @tomlm  can you confirm?
