### ISSUE TITLE
LUIS warnings even if not using LUIS. Language code warnings OOB

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6232]
Two related issues here:

1. I'm not using LUIS, but I get the LUIS warnings.
2. I am warned about unsupported codes, but I didn't set them up - that's what was configured out of the box.

![image](https://user-images.githubusercontent.com/8867670/110059352-e59eaa80-7d18-11eb-8a7d-2c3f2143cc3f.png)

**Comment by taicchoumsft** [comment]
Hey @scheyal , can you check if this still repros for you on a multilingual bot using Orchestrator? It should not, this should have been closed with #6370.

**Comment by taicchoumsft** [comment]
Closing this, I believe this was closed out with #6370.  Please re-open if necessary.
