### ISSUE TITLE
New creation experience: 'generator-qna-bot' fails and leaves empty bot folder behind

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#6234]
## Describe the bug

With the new creation experience, when I chose the "generator-qna-bot" template, creation failed and the empty bot folder was left behind (preventing me from re-using the bot name).

## Version

Version:  1.3.1-nightly.219713.cd7e483
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

Steps to reproduce the behavior (with the new creation experience preview on):

1. From home page, click New.
2. From "Select a template" modal, select "generator-qna-bot" template.
3. Give the bot a name and choose a location.
4. This error appears:
![image](https://user-images.githubusercontent.com/39317542/110063282-b17ab800-7d1f-11eb-9454-5c67a69b5707.png)

5. Try again with the same template and giving the bot the same name. A validation error appears that this name is a duplicate:
![image](https://user-images.githubusercontent.com/39317542/110063367-de2ecf80-7d1f-11eb-8f14-4343dc5275c4.png)

But no bot of that name appears in the bot list on the home page or in the modal that appears I choose to open an existing bot:
![image](https://user-images.githubusercontent.com/39317542/110063481-16361280-7d20-11eb-9dc7-e4a978f3f26f.png)

But it looks like an empty bot folder was created:
![image](https://user-images.githubusercontent.com/39317542/110063544-36fe6800-7d20-11eb-8f91-e040af4d6979.png)

## Expected behavior

If creating the bot fails, I expected the error message to be a little more informative, and I also expected any folders created in the process of trying to create the bot to be removed when creation failed.

**Comment by benbrown** [comment]
@pavolum can you please take a look at this

**Comment by pavolum** [comment]
Excuse the delay, can you please try again with the latest nightly build of Composer? If you still have an error:
1. Ensure you have Node installed on your machine
2. If you have node and the error is still present, please send over the response from the erroneous server call. You can do this by running fiddler while you repro the bug, selecting the 500 server call and looking for the additional error info from that call. 

I will work on surfacing more informative error messages in the modal so future errors display the full issue for quicker debugging.

**Comment by pavolum** [comment]
I am closing this as it was likely due to bugs that have since been resolved in newer releases. @mewa1024 please reopen if you experience this issues in the latest version of Composer.

**Comment by mewa1024** [comment]
will do, and sorry I missed your comment from a couple weeks ago!
