### ISSUE TITLE
OAuth - how can we retrieve username

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#6241]
I have used OAuth - Azure AD V2 in Bot Composer Dialog, User is getting successfully authenticated and dialog.token has value. 
Is there a way we can retrieve user name, / email/ id from AD into the bot, so that we need not prompt for the name  and use the name/ id in subsequent dialogs/flow of the bot

**Comment by jwiley84** [comment]
Hi @aparnaji !

I know this is possible from a non-composer bot using the Graph API; let me dig into a composer a bit and see if it's possible on their side as well! If it isn't, I'll raise a feature request; this is a really useful ability to have!

**Comment by jwiley84** [comment]
Thank you for your patience; i should have an update for you by this afternoon.

**Comment by msomanathan** [comment]
@aparnaji we are working on a major release, so apologies for the delay in getting to this issue. We will respond back with a resolution as soon as we can.

**Comment by peterinnesmsft** [comment]
Transfer to StackOverflow.

**Comment by peterinnesmsft** [comment]
@aparnaji , thank you for opening this issue.  For product behavior, how-to, or general understanding questions, please use Stackoverflow: https://stackoverflow.com/search?q=bot+framework
