### ISSUE TITLE
Components : getting started experience UX alignment

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#6245]
## Describe the bug
Tweaking on recognition from command bar in 'publishing' the icon represent the nav icon:
- Add a package (in packagemanager) 

Space rocket & error messaging:
- alignment in middle
- white space, line is broken between 

Delete bot:
- header for accordion
Plus why can't you just delete the bot from the command bar? Does it need to be a separate action at the bottom of a scrollable project setting page. 

In create - the create new folder is floating

## Version
![image](https://user-images.githubusercontent.com/43533472/110153645-9ffae400-7de3-11eb-8a93-7e1a2e1633a5.png)

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Screenshots
Spacing rocket/error message
![image](https://user-images.githubusercontent.com/43533472/110153815-d20c4600-7de3-11eb-9ea5-7ce70f73c4ea.png)

Package manager icon match
![image](https://user-images.githubusercontent.com/43533472/110153789-ca4ca180-7de3-11eb-8743-b6c9377b8d49.png)

Delete Bot
![image](https://user-images.githubusercontent.com/43533472/110153755-be60df80-7de3-11eb-94c4-4b32221475b2.png)

Create new folder
![image](https://user-images.githubusercontent.com/43533472/110155352-c883dd80-7de5-11eb-93d4-458eb121d1bb.png)

**Comment by benbrown** [comment]
These items have been addressed.
