### ISSUE TITLE
Components: description where does it show

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#6246]
## Describe the bug
I've added a description to my bot, I'm not able to see it again anywhere that makes sense to me when I have created a new project.

## Version
![image](https://user-images.githubusercontent.com/43533472/110154435-85753a80-7de4-11eb-986a-6b50b2f5ba04.png)

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior
It's not required, but I would expect my description to pop up somewhere > near name, file location.

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/110155253-a5592e00-7de5-11eb-904f-dff1c7ab5447.png)
![image](https://user-images.githubusercontent.com/43533472/110154854-0df3db00-7de5-11eb-927a-db7716c3ef4d.png)

**Comment by mewa1024** [comment]
Can we add a column to the home page for the description? In the area outlined in the purple box:
![image](https://user-images.githubusercontent.com/39317542/124071435-27540f00-d9f4-11eb-8103-8e0e82ab108d.png)

(@emivers8 should this also appear on the Configure page?)
