### ISSUE TITLE
When adding a Package / Template / Authored Dialog that requires an optional component, Provisioning is aware

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6253]
## Is your feature request related to a problem? Please describe.

Composer today does not give insight into your bot project and if you need to provision certain optional components based on your bot project.  This can cause a user to not provision all necessary resources needed to be able to make their bot project work after publishing or publishing errors.

## Describe the solution you'd like

When adding a Package / Template / or Authoring a Dialog, if you require an optional resource to be provisioned, Composer should notify you that you need to provision those resources to publish successfully.

## Additional context

Provision Functional Spec 1.10

**Comment by benbrown** [comment]
See also:

#7739 
#7740

**Comment by benbrown** [comment]
This is a dupe of #6775 - closing in deference to that request.
