### ISSUE TITLE
Composer will close even if a publishing / provisioning process is running with no error / warning

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6254]
## Is your feature request related to a problem? Please describe.

Composer can be in the middle of a provisioning / publishing action and if you chose to close the application while the process is running it will do so without warning the user that there is a process running that could be affected by this action.

## Describe the solution you'd like

If there is a publishing / provisioning action actively running Composer should provide a modal warning that closing could cause an issue with that process.  The user should then have to confirm that they understand and be able to close, but the backend process as part of the close should pause and or stop gracefully.

## Additional context

Provision Functional Spec 1.24

**Comment by benbrown** [comment]
See:

https://www.electronjs.org/docs/api/app#event-before-quit
