### ISSUE TITLE
Documentation for for IT Pro / Admin to complete provisioning handoff process

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6258]
## Is your feature request related to a problem? Please describe.

As a IT Pro / Admin, I want to have the appropriate level of documentation on how to complete the provisioning process on the behalf of a developer, so that I can understand the provisioning process and the steps required to complete the action.

## Describe the solution you'd like

Document the provisioning handoff process for the IT Pro / Admin side of the provisioning handoff process and make this document be referenceable as part of the communication to the IT Pro / Admin when the handoff request is generated.

## Additional context

Provisioning Functional Spec 1.20

**Comment by Dewain27** [comment]
Blocked awaiting implementation for Handoff Provisioning

**Comment by Dewain27** [comment]
Implementation design for the Handoff process is complete documentation is ready for creation.

**Comment by GeoffCoxMSFT** [comment]
Looks like Yan Liu isn't available for docs, so we will need to find a doc writer for this.

**Comment by emgrol** [comment]
Admin handoff docs were published for Build. Let's coordinate on any docs re: this for future releases @Dewain27.
