### ISSUE TITLE
Post creation process, Composer needs to inform the user that it is done loading the project template

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6260]
## Is your feature request related to a problem? Please describe.

In Composer today, it is unclear when your bot project template is fully loaded (especially in mulit-bot projects).

## Describe the solution you'd like

Composer should have some way to inform the user that their bot project template is still being loaded and when the process is fully complete.

## Additional context

Creation Functional Spec 1.3

**Comment by benbrown** [comment]
I think this is done?

**Comment by emivers8** [comment]
Yeah, when I test this with Enterprise assistant it loads everything while the spinner is being displayed, including all skills. Took a minute, but that's acceptable. I say done @Dewain27.

**Comment by Dewain27** [comment]
Solved in other issue.  Confirmed fix.
