### ISSUE TITLE
Export bot project to allow import from another user using Composer

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6265]
## Is your feature request related to a problem? Please describe.

Composer should have a way to package up the project that I have made and allow me to provide it to another developer.

## Describe the solution you'd like

Composer should have an Export button or Save as should offer to same my project to a .zip file or similar to allow for easy sharing of my project with others.  An import or open ability to be able to open and/or import the file as well.

## Additional context

Creation Functional Spec 1.18

**Comment by darrenj** [comment]
Possible today?
![image](https://user-images.githubusercontent.com/33519520/111459110-2e3f6600-8712-11eb-9299-c1f2aa2bc95e.png)
