### ISSUE TITLE
Guided experience in Composer for connecting / disabling skills

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6267]
## Is your feature request related to a problem? Please describe.

Composer should have a guided experience for teaching users how to connect / disable skills

## Describe the solution you'd like

Getting started / post creation experience should provide guidance on how to get existing skills / connect them and disable them.

## Additional context

Creation Functional Spec 2.3

**Comment by benbrown** [comment]
I think this has been handled by the new skill connection experience? @Dewain27 is there work yet to be done for us here?
