### ISSUE TITLE
Post creation guided experience for Orchestrator reports

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6272]
## Is your feature request related to a problem? Please describe.

If I have enabled Orchestrator, then a guided experience should inform me on how to generate orchestrator reports.

## Describe the solution you'd like

Documentation on how to generate Orchestrator reports should be exposed to the user if they have implemented Orchestrator in their Bot Project.  This should be triggered if the Orchestrator package is ever installed.

## Additional context

Creation Functional Spec 3.12

**Comment by scheyal** [comment]
@vivekkshankar - please take a look.
