### ISSUE TITLE
Composer guides user on how to enable Teams as a connection

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6275]
## Is your feature request related to a problem? Please describe.

Teams should be easy to enable as a connection for a user's bot project.  Composer should guide the user on how to enable this in Composer and in Teams.

## Describe the solution you'd like

There should be a connection enable experience that allows a user to be able to turn on Teams connection and it should generate a manifest file with instructions on how to enable this in App Studio.  The Teams channel in ABS should be enable and configured.  ABS bot registration should also be verified.

## Additional context

Creation Functional Requirement 4.0

**Comment by Dewain27** [comment]
Currently blocked due to need for agreement on R13 interface for Channel / Adapter / Connection

**Comment by benbrown** [comment]
@Dewain27 is anything else needed here for Teams?
