### ISSUE TITLE
Installing multiple packages only shows one package in the Installed

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6277]
## Describe the bug

I added multiple packages from a custom source.  The installed only shows 1 of the custom packages in the UI.

## Version

1.3.1-nightly.220254

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to package manager
2. Add a custom feed **\\fusebox\public\feed** 
3. Add a Humanizer  package from the custom feed
4. click on installed, the package is not listed.
5. Add javascript package, go to installed, the package is not listed
6. add Recognizer package, go tinstalled, the package IS listed.

## Expected behavior
Installed should show all packages which are installed.  I suspect the issue is that you are assuming that components have to a .schema file, and that is a false assumption. 

These are components which extend the adaptiveexpression functions with custom functions.  There is not a schema file for these components.  The fact that they have the bf-component tag in the metadata is the signal to say that this is a component.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/110177850-6eb9ee00-7dba-11eb-8f73-77fc1296be5a.png)

**Comment by benbrown** [comment]
This was related to the selection criteria requiring that a package contain schema to be displayed.  It now uses the `msbot-` tags to determine if a package should be displayed here.
