### ISSUE TITLE
Composer guides user on how to enable Web Chat as a connection

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6278]
## Is your feature request related to a problem? Please describe.

Web Chat should be easy to enable as a connection for a user's bot project. Composer should guide the user on how to enable this in Composer

## Describe the solution you'd like

There should be a connection enable experience that allows a user to be able to turn on Web Chat connection and it ensure that proper project code for Web Chat is part of your publishing / provisioning process. The Web Chat channel in ABS should be enable and configured. ABS bot registration should also be verified.

## Additional context

Creation Functional Spec 4.2

**Comment by Dewain27** [comment]
Currently blocked due to need for agreement on R13 interface for Channel / Adapter / Connection

**Comment by darrenj** [comment]
I've flagged this a few times, the channel to provision under the covers is Directline *not* WebChat otherwise magic codes/etc. can't be avoided.

**Comment by benbrown** [comment]
@darrenj I don't know what you mean by this
