### ISSUE TITLE
Custom functions provided by components are flagged as invalid by composer

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6279]
## Describe the bug

When an custom component is added which adds new functions composer is flagging them as invalid. 

## Version

1.3.1-nightly.220254

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu
## To Reproduce

1. Go to packagemanager
2. add custom feed \\fusebox\public\feed
3. Add humanizer package 
4. Now edit a LG template to pluralize dog, like this:
```- ${humanizer.pluralize('dog')}```

## Expected behavior
This is a valid function and it should work, even if it doesn't know that the function is there.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/110178093-cfe1c180-7dba-11eb-9f77-ba11b0dbcad1.png)

**Comment by boydc2014** [comment]
Close this since we now by default mark unknown functions as warnings
