### ISSUE TITLE
There is no way to add a custom trigger via the UI.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6281]
## Describe the bug

When a component adds schema for new triggers the UI does not show them.  

## Version

1.3.1-nightly.220254

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to package manager
2. add feed \\fusebox\public\feed 
3. install github package
4. go to Create Trigger UI 

## Expected behavior
It's great that we have well-known triggers in a useful groupings, but a drop down with all of the known triggers in the .schema should always be available.  I cannot use custom triggers without having to go to the raw .json

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/110180248-46cc8980-7dbe-11eb-8c99-7c0469471cf5.png)

**Comment by mewa1024** [comment]
(@vivekkshankar related to both the trigger workflow and the custom actions?)
