### ISSUE TITLE
Composer Action menu should group custom actions by dotted paths.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6282]
## Describe the bug

When adding custom actions the convention is to namespace them with dots, and if you have a lot of them, further namespace
the name of the action with dots. 

For example:
 Github.Activity.Feeds.GetFeeds

Composer treats it as a flat list, we should default to using dots as grouping, and group in the menu hierarchy.

## Version

1.3.1-nightly.220254

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to package manager
2. add \\fusebox\public\feed as a custom feed
3. install github package
4. Go to add a custom action, see how all of these 400+ actions are listed flat.  
## Expected behavior

They should be listed grouped by each name
Github
     Activity
          Feeds
              GetFeeds

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/110182448-a0828300-7dc1-11eb-8c86-725c8c69737c.png)

**Comment by yeze322** [comment]
@hatpick Soroush what kind of UX design do we need for this? I saw you add a 'UX design' label.

**Comment by hatpick** [comment]
> @hatpick Soroush what kind of UX design do we need for this? I saw you add a 'UX design' label.

Hey, please consult Sangwoo and get his thoughts on the matter
