### ISSUE TITLE
Compose tries to render Actions array in the property pane with custom triggers

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6283]
## Describe the bug

When you load a .dialog with a valid custom trigger in it, the UI for the trigger will attempt to render the actions array.

## Version

1.3.1-nightly.220254

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to package manager
2. Add \\fusebox\public\feed as a custom feed
3. add github package
4. Edit your main dialog in json mode
5. add custom trigger **Github.OnContentReferencedEvent** for example
6. Switch back to UI mode.  You will see that the UI on the right shows the action array. 

## Expected behavior

Actions should not show up in the property pane, just in the UI in the middle.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/110182665-11c23600-7dc2-11eb-85fa-04595ec50a74.png)

**Comment by tomlm** [comment]
I suspect I can fix this with a custom .uischema, but do I really need to do that?  What's the scenario where we would edit actions in the property pane ever?

**Comment by cwhitten** [comment]
This is an example of the system working correctly. If it's in your component schema, it gets rendered. You can hide this with uischema if you do not want it rendered. Why would you want Composer to apply these sorts of opinions. Seems orthogonal to our principles.
