### ISSUE TITLE
Remote Skills Not Working

### ISSUE THREAD

**Issue by mmarzillo** [microsoft/BotFramework-Composer#6287]
I have successfully deployed a simple remote skill, but when I attempt to access it from a consumer bot, the remote skill never works. 

When I test the consumer bot locally on the emulator the consumer bot will work but when the remote skill either errors out with a 40x code or just doesn't work. The remote skill works fine on portal but not when connected to the consumer. I've spent considerable amount of time checking the app ids, passwords and urls and I think I have it right, but it's still not working.

 I've spent several hours on this issue and I'm not sure if it's a bug in composer or something missing from our docs.

**Comment by zxyanliu** [comment]
Thanks @mmarzillo 
The issue was reproduced on my end as well. I was able to connect to an example remote skill, but I was unable to connect to a remote skill I published to Azure. 

Composer version: 


I got 401 in the Emulator:

![1](https://user-images.githubusercontent.com/32497439/110190962-e7c93d80-7dda-11eb-8890-598b417fcaa3.png)

**Comment by mmarzillo** [comment]
Worth adding, that when I go to the url for the skill this is what I get.

![image](https://user-images.githubusercontent.com/6752474/110207518-94da9f00-7e49-11eb-901d-4a4acc10d9c8.png)

**Comment by EricDahlvang** [comment]
This looks like an appid/password config or ngrok issue.  Could someone from support assist please?

**Comment by mmarzillo** [comment]
Thanks @EricDahlvang I don't think it's ngrok because I was able to access other remote skills that were published by other people, but it may be something with the appid/pw. Would love to speak with someone in support as soon as we have someone. Thanks!

**Comment by v-kydela** [comment]
@mmarzillo - When you say remote skill, do you mean a skill that's running on a remote server? Can you get that skill to work when you run the skill locally? If you encounter the same problem when the skill is running locally then that will help us debug it.

Also, please provide the following:

1. Repro steps
2. Screenshots
3. Links to any documentation or samples you're following

**Comment by mmarzillo** [comment]
Hi @v-kydela following the steps here https://docs.microsoft.com/en-us/composer/how-to-export-a-skill#prepare-a-local-skill to deploy and access a local skill
![image](https://user-images.githubusercontent.com/6752474/110388783-3bc96180-8029-11eb-91d9-474019bcb763.png)

I wind up getting no response when testing in the emulator (skill should trigger with an unknown intent and ask a question)
![image](https://user-images.githubusercontent.com/6752474/110389228-d6c23b80-8029-11eb-8ded-2bb3eda7e85c.png)

**Comment by mmarzillo** [comment]
Also, I'm using v1.3.1 of Composer.

**Comment by zxyanliu** [comment]
There was a schema change b/w 1.2 release and 1.3 release. This might be the cause of the failed connection to the remote skill.
This is what I did that solved the issue: 

After publishing the skill, try updating the schema to:
`"$schema": "https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/skills/skill-manifest-2.0.0.json"` in Azure App Service editor. 

![image](https://user-images.githubusercontent.com/32497439/110499462-1c741800-80ad-11eb-9ae9-7fc5e44e25ae.png)

Then start your bot and try to connect to the remote skill again. You should be able to see your local consumer bot be able to call the published remote skill with success.

**Comment by JonathanFingold** [comment]
@EricDahlvang , @v-kydela , @zxyanliu , To be clear, the skill manifest schema itself (v2.0.0 or v2.1.0) hasn't changed. This must have been a change in how Composer is consuming the manifest.

**Comment by mmarzillo** [comment]
@zxyanliu , updating that $schema value is still leaving me with a 401 error.

![image](https://user-images.githubusercontent.com/6752474/110525230-f6b13800-80d9-11eb-8b68-124d60fbd337.png)

**Comment by v-kydela** [comment]
@mmarzillo - I can see there's a warning in your Composer screenshot indicated by the yellow triangle. What is the warning?

**Comment by v-kydela** [comment]
@mmarzillo - I suppose you don't need it but you might as well try having one for the sake of experimentation.

I'm also noticing that you say your expected behavior is for the skill to trigger an unknown intent and ask a question, but there's no unknown intent in the skill in your screenshot. There's just a greeting. Is it possible that the skill didn't respond because there was no unknown intent trigger?

**Comment by mmarzillo** [comment]
thanks, @v-kydela I recreated a local skill to say "you're speaking gibberish" with an unknown intent and still now response.

![image](https://user-images.githubusercontent.com/6752474/110659473-3a627b00-8188-11eb-9f5a-923cc7783f9c.png)

**Comment by v-kydela** [comment]
@cwhitten - I've been asked to escalate this issue. Please assign an engineer from your team.

**Comment by cwhitten** [comment]
@v-kydela, do you have reproduction steps for the team?

**Comment by v-kydela** [comment]
@cwhitten - Matthew says he's just following the steps here: https://docs.microsoft.com/en-us/composer/how-to-export-a-skill#prepare-a-local-skill

**Comment by tdurnford** [comment]
@mmarzillo if you aren't using Ngrok, what do you have the 'Skill host endpoint' in the bot settings set to?

**Comment by tdurnford** [comment]
@mmarzillo Can you check if you have the skill settings configured properly in the advanced bot settings?

Bot Settings > Toggle Advanced Settings > Scroll down to 'skillConfiguration'

`allowedCallers` should be set to `["*"]` and `isSkill` should be `true`

![image](https://user-images.githubusercontent.com/17039790/110855058-1a5bb600-8273-11eb-9dc5-5164ce39ed26.png)

**Comment by zxyanliu** [comment]
FYI. The issue was not reproduced with https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.3.1-nightly.222354.54a8de7 on my side. 
I have a plan to restructure the content to make it easier to follow. 

@mmarzillo Thanks for filing this issue. We appreciated it!

**Comment by mmarzillo** [comment]
@zxyanliu was able to walk me through publishing and connecting to a remote skill. Thanks all!

**Comment by zxyanliu** [comment]
This is [the PR](https://github.com/MicrosoftDocs/composer-docs-pr/pull/405) to improve the flow.
