### ISSUE TITLE
show ms graph user photo in an adaptive card

### ISSUE THREAD

**Issue by afahmy11** [microsoft/BotFramework-Composer#6290]
hi

i am getting the user photo using an api call to https://graph.microsoft.com/v1.0/users/{id}/photo/$value .  and i want to display it in an adaptive card that accepts a url. how can i do that

**Comment by v-kydela** [comment]
Thank you for the question, @afahmy11 

Adaptive Cards can only display public images. They cannot access URL's that require authorization, though [Matt Hidinger says they have plans to solve that problem](https://github.com/Microsoft/AdaptiveCards/issues/2170#issuecomment-733115350).

In the meantime you have two options, though both are somewhat undesirable.

1. You can reupload the image to a public URL, which may be considered a security breach if the image is meant to be private.
2. If the image is *very* small, you can embed the image in the card. If you don't know how to do that, you should be able to find plenty of [posts](https://github.com/microsoft/AdaptiveCards/issues/2164) explaining how to use data URI's. Be warned that embedding images that aren't small enough will make the activity too large to be sent through the Bot Framework, and you'll see errors in that case.

I will close this issue as resolved.

**Comment by afahmy11** [comment]
i tried "url": "data:image/png;base64,${user.photo}", but it is not working
