### ISSUE TITLE
Teams package displays bogus menus

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6293]
## Describe the bug

Teams triggers show up distored in menu

## Version

1.3.1-nightly202254

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to to add trigger
2. Select Team triggers

## Expected behavior

The menus shouldn't look like that.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/110224233-a8f4bf80-7e8e-11eb-9643-e77ecd262196.png)

**Comment by tomlm** [comment]
@EricDahlvang , this might be a bug on the package side.

**Comment by hatpick** [comment]
#5710 is resolving this.
duplicate #6014
