### ISSUE TITLE
When I add a custom recognizer it doesn't show up in the drop down

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6294]
## Describe the bug

adding a custom recognizer doesn't show up in the drop down, even though there is a .schema file registering it.

## Version

1.3.1-nightly 20254

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to package manager
2. install \\fusebox\public\feed as a feed
3. Install any of the recognizer packages (Lucene, Lucy, Recognizers) they all add recgonizer components.
4. Go to recognizer for a dialog, it does not show the installed recognizers.

## Expected behavior

Installed components should show up in the UI.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/110224402-2967f000-7e90-11eb-8a12-026e65a61305.png)

**Comment by hatpick** [comment]
@clearab what do you think? This is currently not supported but we need to prioritize it.
