### ISSUE TITLE
Azure resources should be sorted by name, not guids

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6298]
## Describe the bug

When enumerating resources you should sort alphabetically not by guid

## Version

1.3.1-nightly20254

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. To to manage profiles
2. Add a azure webapp profile
3. Click on subscription, this is sorted by GUID not alpha
![image](https://user-images.githubusercontent.com/17789481/110225600-f7f52180-7e9b-11eb-8097-b787fb581c29.png)
Regions are not alpha either
![image](https://user-images.githubusercontent.com/17789481/110225611-13f8c300-7e9c-11eb-99c1-ae3f41e91d55.png)

## Expected behavior

To be able to quickly find my resources because they are presented in order.

## Screenshots
See above

**Comment by VamsiModem** [comment]
Looks like this issue is fixed
![image](https://user-images.githubusercontent.com/12182973/115784816-79811000-a373-11eb-9af6-e22810fed9d7.png)
