### ISSUE TITLE
Publishing (Legacy Runtime): Publishing to Azure likely broken for legacy runtime if using LUIS/Orchestrator/QNA

### ISSUE THREAD

**Issue by taicchoumsft** [microsoft/BotFramework-Composer#6305]
## Describe the bug
Change introduced [here](https://github.com/microsoft/BotFramework-Composer/commit/b64b438edd22cdcc837722517994692f948858c7) definitely breaks Orchestrator publishing on the legacy runtime, and likely also breaks Luis/QNA.

The change is in `LuisAndQna.ts` - `ComposerDialogs`  was removed from path.

When publishing using the legacy runtime, the generated folder is a child of `ComposerDialogs` (i.e. `generated` folder is in `<BotFolder>/ComposerDialogs/generated`.  The C# runtime then picks up the settings from the generated folder, which would be `<BotFolder/ComposerDialogs/generated/orchestrator.settings.json`, `<BotFolder/ComposerDialogs/generated/luis.westus.settings.json`  etc.

With this change, the `generated` folder is now in `<BotFolder>/generated`, but the bot root is still `<BotFolder>/ComposerDialogs`.   So any artifact in the generated folder will not be found by the legacy runtime. 

## Version
Post 1.3.1 nightlies

## Browser
All

## OS
All 

## To Reproduce
1.  Create a bot using the legacy runtime
2.  Enable LUIS and/or Orchestrator
3. Eject the runtime
4.  Publish the bot to Azure using the Composer Publishing flow
 
## Expected behavior
Luis/Orchestrator/Qna should work normally.  With Orchestrator, you should not see the `"ModelFolder" cannot be null` message

**Comment by boydc2014** [comment]
The breaking change is this path change
![image](https://user-images.githubusercontent.com/3829387/110281298-69a5aa80-8017-11eb-9084-af3780514ba6.png)

This path is later used by "builder" to build luis/qna/orch models and putting resulting to a generated folder. This is a shared builder by both local publisher and azure publisher. 

So, @taicchoumsft and @lei9444  how about we added the 'ComposerDialogs' path when passing the path to builder. And ask @benbrown to try, see it breaks anything in new AdaptiveRuntime.

**Comment by benbrown** [comment]
Yes I believe this will break the new runtime. We need to figure out a way to have this path be different for these different circumstances. I'll work with @taicchoumsft
