### ISSUE TITLE
Reprompt Adaptive card with Validations in Bot Composer

### ISSUE THREAD

**Issue by LakshummaC** [microsoft/BotFramework-Composer#6310]
Hi Team, 

As part of requirement in Bot Composer, we need to prompt a input text adaptive card which satisfies no blanks and only numbers regex validation. If input is blank or alphabets then adaptive card has to be repromoted for 3 times. Below is screen shot of adaptive card. Tried with validation rules but still it is not working.

![image](https://user-images.githubusercontent.com/76558423/110317965-e5f9b700-8032-11eb-8262-a66f86aec214.png)

**Comment by dmvtech** [comment]
Hi @LakshummaC I'm investigating this. Would you be able to share your bot as it is currently so I can see how you've got things designed?

**Comment by dmvtech** [comment]
I actually don't think I need your bot. But you can share the `"validations": []` section of your dialog/prompt (show code). 

But I am curious; what is the actual behavior? is it just not validating? is it not behaving as expected?

**Comment by dmvtech** [comment]
@LakshummaC 

It should work. 

I used the card:
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.2",
    "body": [
        {
            "type": "TextBlock",
            "wrap": true,
            "text": "What is your age?"
        },
        {
            "type": "Input.Text",
            "id": "question",
            "placeholder": "Enter your age here"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Enter to submit age",
            "id": "submitactionid"
        }
    ]
}
```

Saving the value  `=turn.activity.value.question` into the property and then setting the validation to: 
`isMatch(turn.activity.value.question, '(^[\d]+$){1}')`

**Comment by LakshummaC** [comment]
> @LakshummaC
> 
> It should work.
> 
> I used the card:
> 
> ```
> {
>     "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
>     "type": "AdaptiveCard",
>     "version": "1.2",
>     "body": [
>         {
>             "type": "TextBlock",
>             "wrap": true,
>             "text": "What is your age?"
>         },
>         {
>             "type": "Input.Text",
>             "id": "question",
>             "placeholder": "Enter your age here"
>         }
>     ],
>     "actions": [
>         {
>             "type": "Action.Submit",
>             "title": "Enter to submit age",
>             "id": "submitactionid"
>         }
>     ]
> }
> ```
> 
> Saving the value `=turn.activity.value.question` into the property and then setting the validation to:
> `isMatch(turn.activity.value.question, '(^[\d]+$){1}')`

It is not re-prompting along with adaptive card. Do I need to make 'AllowInterruptions','AlwaysPrompt' flags as True?

**Comment by LakshummaC** [comment]
I want to re-prompt the same above adaptive card when it is blank or if Regular expression fails.

Like below
Example:

Validation failed
![image](https://user-images.githubusercontent.com/76558423/112128263-40c30f00-8bec-11eb-8876-a39028e3ae11.png)

**Comment by LakshummaC** [comment]
Issue is solved. I found a way to reprompt
