### ISSUE TITLE
Add ability to add User Input (Choice) powered by LUIS intents

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6313]
## Is your feature request related to a problem? Please describe.

As a user, I would like to be able to provide a User Input (Choice) powered by LUIS, so that I can use the power of LUIS to catch intents to do things like confirmations natively in composer.

## Describe the solution you'd like

When creating a User Input (Choice) being able to select an intent as an option in the choice matrix.

## Additional context

Use the Synonyms option to allow selection of LUIS intent:
![image](https://user-images.githubusercontent.com/18688053/110346695-6b5e7680-7ff5-11eb-9fbf-c948710ace19.png)

Other options may be other choices that may have multiple ways of saying the same thing. Example:

**How would you like to get notified:**
_Choice Prompt: (Text / Email / None)_
  - Support of "Send it to me in mail" = Email
  - Support of "SMS works for me" = Text
  - Support of "I don't want to get any notifications please." = None

By supporting this mechanism, a user could define the intent selections once and not have to manage the details of synonyms in ever dialog, but just reuse them and update training as necessary without having to touch every place in the dialog where that Choice is defined.

**Comment by tobias-correia** [comment]
@cwhitten I'd like to implement this exact behaviour as well but I see that this ticket got closed without any comment. Is there already a way to do this?

**Comment by cwhitten** [comment]
Hi @tobias-correia. No, this request was not implemented. We have no plans to prioritize supporting this scenario.

**Comment by Clooney24** [comment]
Hi @cwhitten I would also appreciate that feature. But closing doesn't mean not to prioritize, it means not to support it at all, as I understand.

In a real-life-bot-scenario with LUIS (in our case, it's a recruiting bot) this is a must-have feature as users won't answer just with the given options the control is expecting. I built a quite ugly workaround for this, but it would be much better to at least be able to relate the options with intents.
