### ISSUE TITLE
Improve authoring canvas layout and queues for composite actions like switch

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#6327]
## Is your feature request related to a problem? Please describe.

1. I find it hard to navigate through relatively simple triggers.
2. The visual queues for determining what is a part of a composite action are minimal.

## Describe the solution you'd like

1. Draw a border around the composite action, at least for the selected action.
    - If I choose to delete at the "root" of the composite action, all contained elements will be deleted, too. It would be nice if this were not a surprise.
    - If I'm editing one child of a composite action, it would be nice to easily identify the parent (and siblings).
2. Be able to expand or collapse a composite action.
3. Be able to toggle some composite actions, particularly the switch action, between vertical and horizontal layout.
4. As applicable, enable some accordioning within a composite action.
    - For a switch action, accordion based on which case you are editing.

## Describe alternatives you've considered

The current guidance is to create sub dialogs whenever the current trigger logic becomes hard to read. This has other issues, as there is a balance between trigger size (breadth) and number of nested dialogs (depth). Treating triggers like methods has some merit, but the style guidance there for traditional programming languages is not to create more classes, necessarily, but to break the methods up into smaller methods.

## Additional context

This is a relatively benign size for a trigger, but it is hard to view and edit on the authoring canvas:

![authoringCanvas](https://user-images.githubusercontent.com/35047199/110399778-471d8c80-802b-11eb-8966-570673e75c16.png)

**Comment by mewa1024** [comment]
Good feedback and we should consider this. As reference PVA's branching looks like this:

![image](https://user-images.githubusercontent.com/39317542/124069382-ee666b00-d9f0-11eb-80d6-70ea7f0486ae.png)
