### ISSUE TITLE
Instrumentation for Orchestrator

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6340]
Request for instrumentation of Language & Orchestrator in Composer for Opt-In users (assuming privacy, legal approval).  (@garypretty)

Metric | Type | P | Comment
-- | -- | -- | --
Orchestrator   package is installed | Count | 0 |  
Orchestrator is   used as recognizer | Count | 0 |  
Plus Context: Root or not Root dialog | Count | 0 |  
No. of intents per   LU | Count | 0 |  
No. of entities per   LU | Count | 0 | Even if ignored in   Orch. it is a good to identify import use patterns & future use
No. of examples per   LU | Count | 0 |  
Skills used | Count | 0 | Dispatch children   profile
LUIS dialogs | Count | 0 | Dispatch children   profile
QnAMaker dialogs | Count | 0 | Dispatch children   profile
Basemodel used | Value | 0 |  
Basemodel download   time | Timespan | 0 |  
Build time: first | Timespan | 0 |  
Buildtime:   not-first | Timespan | 0 |  
Prediction time | Timespan | 0 |  
CPU | Value | 2 | Computer Hardware.   Should be interesting beyond Orchestrator.
Memory | Value | 2 | Computer Hardware.   Should be interesting beyond Orchestrator.
Architecture | Value | 2 | Computer Hardware.   Should be interesting beyond Orchestrator.
OS | Value | 1 | Linux, Mac,   Windows
Runtime Env. | Value | 1 | Dotnet, nodejs +   version info
Hosting Env. | Value | 3 | Azure, AWS…Should   be interesting beyond Orchestrator.

**Comment by garypretty** [comment]
We met and discussed the above requirements.  Some are already in place, some we will push out and some we will tackle as part of R13.  Here is my summary.

**To implement in R13**

- Add two events ***OrchestratorDownloadStarted*** and ***OrchestratorDownloadCompleted***.

- Add two events ***OrchestratorBuildStarted*** and ***OrchestratorBuildCompleted***. These events should have two additional custom properties added to them, 'basemodel' (name of the model used) and 'firstbuild' (true / false).

Regarding additional properties around CPU / Memory / Architecture - @tdurnford is confirming if it is even possible for us to capture these.  If it is then we would add these to the global properties attached to all events or to the session started event.

**Already in place**

- Orchestrator package installed should be captured from the telemetry within the package manager.

**Pushing to a future milestone**

- Any stats surrounding the LU used. e.g. intent / entity / utterance count will not be implemented in R13.  We will plan to add telemetry for these alongside telemetry for LG in R14 (cc @hibrenda).  We need to carefully consider at which points we capture events for LG counts (e.g. number of functions / variations) and LU counts, so pushing this out makes sense given the current timescales.

**Comment by taicchoumsft** [comment]
The `OrchestratorDownloadStarted`, `OrchestratorDownloadCompleted`, `OrchestratorBuildStarted`, `OrchestratorBuildCompleted` have been added as part of R13.

Leaving this ticket open for tackling whatever is needed for R14.
