### ISSUE TITLE
Support package prefixes in resource ids

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotFramework-Composer#6348]
This issue describes the SDK changes to support package prefixes like `MyPackage#CoolStuff.en-us.lg` in resource ids for dialog, LU, QNA and LG files including a new `import` statement.  https://github.com/microsoft/botbuilder-dotnet/issues/5298

This work item is to ensure that composer is updated to support the new features. We need to ensure that the UI and verification understand the new id and import syntax.

**Comment by garypretty** [comment]
Clearing the R13 milestone and adding @carlosscastro to the assignees.
