### ISSUE TITLE
Imported package's sub-dialogs do not render in UI, but work in the bot

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/BotFramework-Composer#6350]
## Describe the bug

A component with multiple dialogs is not rendering all of them in Composer when installing. HelpAndCancel package version v1.0.0-preview.20210309.c0ed425 has exported assets at https://github.com/microsoft/botframework-components/tree/ryanlengel/helpandcancel_bugbash/packages/HelpAndCancel/exported that are installed in the Conversational Core template or independently through Package Manager.

This version of the package contains 3 dialogs:
1. Root with LU triggers
2. Cancel with BeginDialog trigger of cancel dialog
3. Help with BeginDialog trigger of help dialog
![image](https://user-images.githubusercontent.com/43043272/110559073-6f26f180-80f8-11eb-9fa6-032a116bac40.png)

After installing the package only the root dialog appears in the Composer UI, but when starting bot and testing the conversations the other dialogs work as expected. This may be a bug with the contents of my package but could also be something with how Composer is ingesting/rendering the imported dialogs.

**Imported root dialog is the only one that shows up**
![image](https://user-images.githubusercontent.com/43043272/110558082-b8764180-80f6-11eb-92c0-48dc56ecb6c7.png)

**Responses from the package are successful**
![image](https://user-images.githubusercontent.com/43043272/110558390-4520ff80-80f7-11eb-9665-ec7c9f32be70.png)

## Version

Commit 823d4e08 

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Use latest with Component Model feature enabled
2. Create an EmptyBot project
3. Go to Package Manager, install `Microsoft.Bot.Components.HelpAndCancel v1.0.0-preview.20210309.c0ed425`
4. Manually copy the triggers/dialogs provided in the HelpAndCancel dialog into the root dialog.
5. Run the both and test Help/Cancel triggers.

## Expected behavior

All dialogs imported should show up.

**Comment by cwhitten** [comment]
@ryanlengel when you click on the "Help" element in the Begin Dialog node under the Help trigger, what happens?

**Comment by ryanlengel** [comment]
@cwhitten it refreshes and goes back to the emptyBot root dialog. Attached gif 
![composer_issue_6350](https://user-images.githubusercontent.com/43043272/110702511-7527db80-81a7-11eb-8a48-1a9700561544.gif)

**Comment by srinaath** [comment]
@ryanlengel What happens if you go back to the Home screen and open it again (reloading it)? In addition, could you attach the bot assets to this ticket for us to get a repro.

**Comment by benbrown** [comment]
I believe this is happening because the child dialogs are themselves inside another `dialogs/` subfolder inside the component.

Those should all be moved up into the root `exported/` folder @ryanlengel

**Comment by benbrown** [comment]
Currently, Composer limits the paths folders and depth of searching when indexing the project.

**Comment by ryanlengel** [comment]
Got it that makes sense, @gabog is going to take a look at this package and can let us know. If Composer intends to limit the searching depth, we may benefit from an "Export as package" option that flattens an exported bot and cleans up to only necessary files?

**Comment by ryanlengel** [comment]
If you go back and reload from the home screen, the behavior is the same. Here's the bot attached (haven't made Ben's suggestion on it)
[issue_6350.zip](https://github.com/microsoft/BotFramework-Composer/files/6126163/issue_6350.zip)

**Comment by benbrown** [comment]
I believe we have resolved this. @ryanlengel is that correct?

**Comment by ryanlengel** [comment]
Yes this is resolved - closing.
