### ISSUE TITLE
race conditions

### ISSUE THREAD

**Issue by liweitian** [microsoft/BotFramework-Composer#6355]
rename a KB several times util the error shows up.
Here is the root cause:

when we rename a qna file, we actually create one and delete one.
The two requests are sent almost at the same time.

In delete method, if we only have one single qna source file, we will also delete the source folder after that
await this._cleanUp(file.relativePath);

In create method, although we will ensure the source folder exist (if not we create it), the check method 
await this.ensureDirExists(Path.dirname(absolutePath)) can happen before the cleanUp method. So we cannot write file to an unexisting folder.

some other race condition found: for example, when removing a locale, it triggered a lot delete operations. And in most CRUD operations, we need to getProjectById first which is to read data from hard disk. It needs to scan files on directory (glob) and then read file info. So scan files => delete files =>  read a deleted file will cause a bug.

After fixing the above bugs, we can go on to add and delete locales. The last bug is, when it is reading and writing the same file, appsettings.json in our project. The read function may return an empty string, then json.parse will return an error. This problem should exist in Node, same issues may be found online. Some people online say they will read another time if the first time return an empty string. Or we should use synchronous write method to prevent reading and writing at the same time.

**Comment by boydc2014** [comment]
After discussion with @liweitian and @lei9444, the correct fix is to make those critical operation in sync, this should already been fixed in qna multi-lang branch, right? can you add the PR link here?

**Comment by a-b-r-o-w-n** [comment]
@boydc2014 
> the correct fix is to make those critical operation in sync

I would like to discuss this a bit more. Using the sync/async methods should not result in race conditions- there has to be some other thing leading to this (ex. a missing `await`). What #5822 has done is allowed the main thread to be blocked for ALL operations for I/O in `botProject.ts`. This change has the potential to introduce more performance issues for larger projects.

@cwhitten do you have any thoughts about this as well? Does using async I/O methods inherently introduce race conditions?

**Comment by boydc2014** [comment]
> @boydc2014
> 
> > the correct fix is to make those critical operation in sync
> 
> I would like to discuss this a bit more. Using the sync/async methods should not result in race conditions- there has to be some other thing leading to this (ex. a missing `await`). What #5822 has done is allowed the main thread to be blocked for ALL operations for I/O in `botProject.ts`. This change has the potential to introduce more performance issues for larger projects.
> 
> @cwhitten do you have any thoughts about this as well? Does using async I/O methods inherently introduce race conditions?

Thanks for raising the concerns. Let's chat about this in details, i've sent you an meeting early next week. 

In short summary, what #5822 does is not making all IO sync, it just make certain critical io sync. Yes, the main thread will be blocked. But given our decoupled persistent layer design, in client's view, the IO operation is already complete, thus the perf impact on the client is minimal. 

And for sure, this is not the single way and not the best way to handle this. We just did this a temp fix to unblock the scenario. We have some other better options evaluating,  like a dedicated IO thread (which is a common pattern in many distributed system), let's follow up on that.
