### ISSUE TITLE
Import a knowledge base from existing QnA Maker KB

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6357]
## Is your feature request related to a problem? Please describe.

As a Composer user, I want to be able to import my existing knowledge base data from an existing QnA Maker instance.

## Describe the solution you'd like

In Composer, I want to be able to click Create new KB:
![image](https://user-images.githubusercontent.com/18688053/110636149-8c4bd680-8171-11eb-8603-4409511d1842.png)

I want to be able to import from existing QnA Maker instance on this page without the need to go to QnA Maker and extract it to a .tsv file.  Also it is not clear on this page if you have to put the file somewhere on a web server to consume it vs. import here.
![image](https://user-images.githubusercontent.com/18688053/110636331-c2895600-8171-11eb-9a4a-35aca8b9f3a5.png)

## Additional context

Currently, today we have documented how to take a QnA Maker that already exists and plug it into your project, but the process of doing this makes it where all publish profiles will use the same instance.  For appropriate environmental separation, I don't want to ever have multiple environments using the same instance of QnA Maker as that defeats the purpose of QA / Dev / Prod environments.  That is an advanced feature and something that we should not showcase as the way to do it and then find out that I am not able to edit the QnA in the QnA interface on Composer.  This should be the recommended approach vs. the current solution documented here:
https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot

**Comment by vhugogarcia** [comment]
I would like to see this feature as well. 👍🏻
