### ISSUE TITLE
Unable to get a value for KnowledgeBaseId from state

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#6358]
Created QnA for one dialog, able to publish successfully and copied the knowledgebaseid to appsettings. At runtime in the particular dialog has thrown error "Unable to get a value for KnowledgeBaseId from state"

**Comment by srinaath** [comment]
@aparnaji Could you follow the Github issue template we have to indicate version, platform etc

**Comment by aparnaji** [comment]
Hi @srinaath 

I gave more details in the isse #6392 as you suggested.

**Comment by aparnaji** [comment]
Finally after clearing the browser cache it worked.
