### ISSUE TITLE
if access token is invalid, provision process fails silently when loading subscriptions

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#6359]
## Describe the bug

An invalid access token, such as one pasted in manually, causes the call to load azure subscriptions to fail silently.

Errors in this API should be caught and messaged to the user or handled appropriately rather than silently failing.

When this happens, an incorrect error message about an empty subscription list is displayed.

See this line:
https://github.com/microsoft/BotFramework-Composer/blob/9215e4f79581193ca8050c2d7e0590738c758780/extensions/azurePublish/src/components/api.tsx#L44

**Comment by GeoffCoxMSFT** [comment]
Working on diagnosing the cause: tTe yield subscriptionClient.subscriptions.list() is throwing before the subscriptionsResult._response.status is even inspected.
