### ISSUE TITLE
Can't open project - Duplicate File Found: node_modules/@azure/ms-rest-js/node_modules/sax/package.json

### ISSUE THREAD

**Issue by Hacwikir** [microsoft/BotFramework-Composer#6371]
## Describe the bug

Trying to open my bot an get a duplicate file error message

## Version

v1.3.1

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Created a bot in the Bot Framework Composer
2. Click on the bot to open it.
3. See error
4. ![image](https://user-images.githubusercontent.com/22629805/110721288-1709f100-81c5-11eb-8b60-1c215dae9999.png)

## Expected behavior

Be able to open it and update the design.

## Screenshots

See above

## Additional context

One thing I tried is to look for the file in the error code and delete it. When I re-open the project then I get the same error with a different file. I've tried this 4 or 5 times until I gave up.

**Comment by dmvtech** [comment]
Hi @Hacwikir This happens when you are attempting to reopen a previously created bot? If you create new bots does it have the issue? Did you export the runtime on this particular bot?

**Comment by Hacwikir** [comment]
> Hi @Hacwikir This happens when you are attempting to reopen a previously created bot?

Hello! Yes, it only happens when I try to open a specific previously created bot. I created 3 bots long time ago and just one of them has that issue. 

> If you create new bots does it have the issue? 

I am able to create a new bot and open it just fine.

> Did you export the runtime on this particular bot?

I am not sure. I doubt it. I only found one related option which I did not select.
![image](https://user-images.githubusercontent.com/22629805/110866093-775a6a80-8279-11eb-9f8f-0f577dd58396.png)

**Comment by dmvtech** [comment]
@Hacwikir Can you please try closing Composer, deleting everything underneath `%USERPROFILE%\AppData\Roaming\BotFrameworkComposer\hostedBots` and then running the bot again?

**Comment by Hacwikir** [comment]
> @Hacwikir Can you please try closing Composer, deleting everything underneath `%USERPROFILE%\AppData\Roaming\BotFrameworkComposer\hostedBots` and then running the bot again?

Hello @dmvtech, I followed the instructions, unfortunately I still see the same error when traying to run my bot.

**Comment by dmvtech** [comment]
Interesting. For the one problematic bot, can you check the folder and see if there is a `runtime` folder (even though that option is not enabled in the UI)?

**Comment by Hacwikir** [comment]
> Interesting. For the one problematic bot, can you check the folder and see if there is a `runtime` folder (even though that option is not enabled in the UI)?

Hello, I only see these at the top level:
![image](https://user-images.githubusercontent.com/22629805/111393808-b6702d80-8676-11eb-8a70-e29f5de4f341.png)

I don't see any runtime folder at all:
![image](https://user-images.githubusercontent.com/22629805/111393847-c851d080-8676-11eb-966e-f68eb7d329c5.png)

**Comment by dmvtech** [comment]
Go head and remove the `node_modules` folder and `package-lock.json` file. Then reopen Composer and try again.

**Comment by Hacwikir** [comment]
> Go head and remove the `node_modules` folder and `package-lock.json` file. Then reopen Composer and try again.

Great! It worked. Thank you :)
