### ISSUE TITLE
Problems when inserting prebuilt functions in the LG inline editor

### ISSUE THREAD

**Issue by WashingtonKayaker** [microsoft/BotFramework-Composer#6379]
## Describe the bug

The drop down lists to insert items into the LG inline editor moves to the top left side of the Composer window from the Properties panel once an item is selected from the pre-built functions list. I have not noticed that happening when selecting items from the previous two lists.

## Version

v1.3.1-nightly.221713.7f02df0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a _Send a response_ action.
2. Select the _Send a response_ action in the Authoring Canvas.
3. Select **Add new variation** in the Properties panel.
4. Select the _Insert prebuilt functions_ drop down list, then select the If statement.

## Expected behavior

The function appears in the Authoring Canvas inside the _Send a response_ action, but it does not appear in the LG inline editor located in the Properties panel, and the three drop down list move to the upper left part of the Composer screen - See animated GIF below.

## Screenshot

![drop-down-lists-move](https://user-images.githubusercontent.com/52054121/110857883-3b6dd800-826e-11eb-9294-80cac58c84cb.gif)

**Comment by tdurnford** [comment]
@boydc2014 We have a PR open to fix this issue.

https://github.com/microsoft/BotFramework-Composer/pull/6388

**Comment by boydc2014** [comment]
> @boydc2014 We have a PR open to fix this issue.
> 
> #6388

Great, thanks
