### ISSUE TITLE
Project settings page moderate refactoring

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#6384]
The current project settings page has usability issues and has become rather cluttered. The solution is to introduce tabs to the page to sort the content, as well as to address some problematic tool tip, introduce some improved explainer text (or at least provide a location for that), and move some items to other pages (publish to publishing page, and other items to app settings page (re: Gabo)).

New UX is rough, but can be cleaned up quickly once the issue is prioritized.

![image](https://user-images.githubusercontent.com/55601267/110868369-53992380-827d-11eb-8454-307e26bc1383.png)

**Comment by benbrown** [comment]
Closed by #6592
