### ISSUE TITLE
Cannot delete dialog in Power Virtual Agents context

### ISSUE THREAD

**Issue by iMicknl** [microsoft/BotFramework-Composer#6385]
## Describe the bug

When you are working on a (Dutch) PVA project, removing a dialog will result in an unhandled error which does crash the application. See video.

https://user-images.githubusercontent.com/1424596/110869457-cd0b3300-82ca-11eb-9988-d1206ac259d9.mp4

After a restart, the dialog is removed from the project tree, but the folder is still there.

![image](https://user-images.githubusercontent.com/1424596/110869542-f4620000-82ca-11eb-9a5c-0d476e2bf4cb.png)

![image](https://user-images.githubusercontent.com/1424596/110869575-02178580-82cb-11eb-90df-5ffb5b3ab972.png)

I have to remove this folder manually prior to publish

## Version

Version:  1.3.1-nightly.222354.54a8de7
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

See above.

**Comment by boydc2014** [comment]
close this one duplicate with https://github.com/microsoft/BotFramework-Composer/issues/5728

**Comment by iMicknl** [comment]
@boydc2014 are you sure these are related? I had seen that issue, but in my case it is on removing a trigger for an already Dutch dialog. (the language has been set correctly and the error is not even handled).

Just want to make sure that this one is properly logged as well, since it is a bug where you have to hard restart the application.
