### ISSUE TITLE
yarn start:dev failed to compile

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#6389]
## Describe the bug
run yarn start:dev failed
![image](https://user-images.githubusercontent.com/39758135/110885340-a4625800-8321-11eb-9b8c-e883d237cebc.png)
Then I update the start scripts 
![image](https://user-images.githubusercontent.com/39758135/110885408-c1972680-8321-11eb-8f95-50459c22d7a0.png)
the compile passed but still can't open the composer
![image](https://user-images.githubusercontent.com/39758135/110885498-ea1f2080-8321-11eb-9b95-0eb1070b3c3e.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by hatpick** [comment]
This is happening due to react-dev-utils update
