### ISSUE TITLE
Unable to get a value for KnowledgeBaseId from state.

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#6392]
## Describe the bug
Unable to get a value for KnowledgeBaseId from state. 

## Version

![image](https://user-images.githubusercontent.com/26645750/110900651-ff348900-82fa-11eb-809e-ff8bb31833b7.png)

## Browser

- [ ] Emulator

## OS

- [ ] Windows

## To Reproduce

1. Go to Bot Composer
2. Add trigger - > Add Qna Maker Dialog 
3. Add appsettings
  "qna": {
    "knowledgebaseid": "xxxxxx",
    "hostname": "https://xxxxxx/xxx",
    "qnaRegion": "xxxx",
    "environment": "composer",
    "endpointKey": "xxxxxx",
    "subscriptionKey": "0xxxxxx"
  },
4. Test in Emulator

## Expected behavior

QnAMaker Trace should be invoked

## Screenshots

![image](https://user-images.githubusercontent.com/26645750/110901605-7ae30580-82fc-11eb-8de9-be642a256d54.png)

**Comment by aparnaji** [comment]
Finally after clearing browser cache it worked

**Comment by jnair7291** [comment]
you are testing your bot on emulator? how come clearing browser cache solved this issue?

**Comment by jnair7291** [comment]
> Finally after clearing browser cache it worked

you are testing your bot on emulator? how come clearing browser cache solved this issue?
