### ISSUE TITLE
wildcard in Branch: Switch (multiple options) cases

### ISSUE THREAD

**Issue by afahmy11** [microsoft/BotFramework-Composer#6399]
hi

is it possible to use wildcard `*` in Branch: Switch (multiple options) cases? for example create one case `Hardware*` instead of the 3 cases in the screenshot below?

![image](https://user-images.githubusercontent.com/49028761/110983422-66415480-8372-11eb-8b1e-6e999a9c078f.png)

**Comment by boydc2014** [comment]
We don't support wildchar in swich's cases, but there is some alternatives to do a fuzzy match like, using an if condition with expression (functions that allow you to do processing), for example you can do startsWith(dialog.deviceType, 'Hardware') to achieve the same result
![image](https://user-images.githubusercontent.com/3829387/111152073-49538e00-85cb-11eb-8eea-d504f67bb5ff.png)
