### ISSUE TITLE
Specify alternate models in advanced appsettings (no UI) to use in Orchestrator

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6400]
For parity with CLI, one should be able to direct Composer to use alternate Orchestrator basemodels instead of default ones.

**Comment by boydc2014** [comment]
I guess we are not going to do this in R13, is that correct @taicchoumsft? If so, let's clear the milestone.

**Comment by taicchoumsft** [comment]
Hi @boydc2014 , I expect a PR today or tomorrow for this, sorry for late arrival on this.  Found some interesting bugs in the downloader and wanted to fix it as part of this PR.
