### ISSUE TITLE
DEPLOY_ZIP_ERROR - RequestError - Error: getaddrinfo ENOTFOUND <resource>.scm.azurewebsites.net

### ISSUE THREAD

**Issue by danielallen73** [microsoft/BotFramework-Composer#6406]
TO REPRODUCE

**Azure Portal**
- Create a Bot Channels Registration in existing resource Group
- Copied App Id and Password
**Launched Bot Composer**
- Created a New Skills Bot from scratch. (as per Prepare a Skill https://docs.microsoft.com/en-us/composer/how-to-export-a-skill)
- Created a publishing Profile to an existing set of Azure Resources
- Publish Skills bot using publish profile
- Get:
- DEPLOY_ZIP_ERROR - RequestError - Error: getaddrinfo ENOTFOUND <resource>.scm.azurewebsites.net

**Version**
v1.3.1

**OS**
Windows

**Expected behavior**
Expecteed Skills Bot to Publish to designated Azure Resource Group and Bot Registration 

**Screenshots**
![image](https://user-images.githubusercontent.com/61698055/111039899-79166080-8428-11eb-8802-f7d9a1742dd8.png)

**Publish profile:**

```json
{
  "name": "REDACTED",
  "environment": "composer",
  "runtimeIdentifier": "win-x64",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "<Instrumentation Key>"
    },
    "cosmosDb": null,
    "blobStorage": null,
    "luis": {
      "authoringKey": "REDACTED",
      "authoringEndpoint": "https://westus.api.cognitive.microsoft.com/",
      "endpointKey": "REDACTED",
      "endpoint": "https://westus.api.cognitive.microsoft.com/",
      "region": "westus"
    },
    "MicrosoftAppId": "REDACTED",
    "MicrosoftAppPassword": "REDACTED"
  },
  "hostname": "<Name of Bot Channel Registration",
  "luisResource": "REDACTED"
}
```

**Comment by boydc2014** [comment]
@luhan2017 @VanyLaw looks like the name of the app is not properly populated?

**Comment by luhan2017** [comment]
@danielallen73 , could you double check if your hostname is set correctly? it should be the name of your webapp.

**Comment by danielallen73** [comment]
Thank you @luhan2017. Probably a silly newbie mistake by me.

I was literally following the guidance in preparing a local skill and then create a bot channels registration so that I could connect to it remotely from my consumer (root)bot.

I hadn't appreciated that I would need a webapp to host my skill bot.

My root bot and skill bot share the same cognitive services. Do they therefore need to be within the same resource group?

When creating and publishing a bot from composer I was looking to have my root and skill bot within the same resource group. What is the recommendation here. Do I need to manually create my WebApp in Azure Portal for the skill bot and then get the Hostname and AppId to use in my publish profile?

**Comment by luhan2017** [comment]
@danielallen73 for the cognitive services or any other services, they don't necessarily be within the same resource group. For now, to create two set of webapp and bot channel registration under the same resource group, you need to manually create one. But soon maybe within this week, we will release a new version composer(or you could try to use nightly), in the new version, we decouple the resource group and resources, you can create multiple webapp under the same resource group.

**Comment by danielallen73** [comment]
Thanks for the response @luhan2017. I look forward to that updated version.

The issue I'm facing now is as follows:
![image](https://user-images.githubusercontent.com/61698055/111771476-a8ebbb00-88a3-11eb-94d4-7c03c9c4defc.png)


TO REPRODUCE

Azure Portal

Created a New Skills Bot from scratch. 
Publish to create Web App Bot
Create a Bot Channels Registration in existing resource Group
Create new App registration
Copied App Id and Password and pasted to Bot Channel Registration

Launched Bot Composer
Created a publishing Profile using details above to an existing set of Azure Resources
Publish Skills bot using publish profile
Bot Channels Registration - Test in Web Chat - no response
Click Channels to to view Issues reported against Web Chat channel

Get:
There was an error sending this message to your bot: HTTP status code Unauthorized

Inspect via Dev Tools

**Comment by danielallen73** [comment]
![image](https://user-images.githubusercontent.com/61698055/111774539-822f8380-88a7-11eb-88ce-a852a29ef1c6.png)

**Comment by danielallen73** [comment]
Have followed this
https://docs.microsoft.com/en-us/composer/how-to-export-a-skill
endpointUrl	This should no longer point to the localhost. This should point to the messaging endpoint of the skill-associated Bot Channel Registration resource. e.g. https://composer-skill.azurewebsites.net/api/messages
msAppId	This should be updated to the Microsoft appId of the skill-associated Bot Channel Registration resource.

Does the above literally mean the messaging end point of the Web App Bot that I have now assigned to Bot Channel Registration

And the msAppId is now that of the Bot Channel Registration (rather than the Web App Bot and App Service)?

https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill
Set configurations in a consumer bot


Please can someone talk me through this and remove any ambiquity from the instructions.

**Comment by carlosscastro** [comment]
@luhan2017 could you please walk @danielallen73 on seeing this through? Thanks!

**Comment by luhan2017** [comment]
@danielallen73 the unauthorized the error usually happens when the MicrosoftAppId and MicrosoftAppPassword mismatch. Could you check if the settings in your publish profile and your bot channel registration are matched? 

@zxyanliu or me can help you with more details, let's schedule a call to resolve this.

**Comment by danielallen73** [comment]
Thanks for the advice and getting back to me @luhan2017.
I have checked that the AppId and Pwd in my publish profile match my bot channel registration but I still have this issue/

I'll provide more details and hopefully we can arrange a call. Many thanks

**Comment by danielallen73** [comment]
Publishing Profile:
{
  "name": "NAME",
  "environment": "composer",
  "runtimeIdentifier": "win-x64",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": ""
    },
    "cosmosDb": null,
    "blobStorage": null,
    "luis": {
      "authoringKey": "REDACTED",
      "authoringEndpoint": "https://westus.api.cognitive.microsoft.com/",
      "endpointKey": "REDACTED",
      "endpoint": "https://westus.api.cognitive.microsoft.com/",
      "region": "westus"
    },
    "MicrosoftAppId": "BOT CHANNEL REG APPID",
    "MicrosoftAppPassword": "BOT CHANNEL REG PASSWORD",
    "qna": {
      "endpoint": "https://QNAENDPOINT.azurewebsites.net",
      "subscriptionKey": "REDACTED"
    }
  },
  "hostname": "NAME OF WEB APP BOT",
  "luisResource": "REDACTED"
}

Bot Management config
![image](https://user-images.githubusercontent.com/61698055/112167872-b5944a00-8be8-11eb-97fb-d306d3f5eeb3.png)


Manifest:
![image](https://user-images.githubusercontent.com/61698055/112168504-43703500-8be9-11eb-91db-9b23e7f37294.png)

appSettings.json
{
 .
.
.

  },
  "MicrosoftAppId": "Bot Channel Registration AppId",
.
.
.  "skillConfiguration": {
    "isSkill": true,
    "allowedCallers": [
      "*"
    ]
  },
.
.
.

  "MicrosoftAppPassword": "Bot Channel Registration Password",
.
.
.

**Comment by danielallen73** [comment]
Hi @carlosscastro @luhan2017 @zxyanliu have I provided sufficient detail of my lastest issue regarding "HTTP status code Unauthorized".
I can see in emulator is suggests that my AppId and Password are incorrect, however you will see above what I have applied and now I need urgent advice as to whether this is correct.
At the moment I am paying for services that I cannot fully utilise in the way I required.
Essentially Bot to Bot communication between Root Boot and Skills Bot.
Thank you

**Comment by luhan2017** [comment]
@danielallen73 The above info you shared is root bot or skill bot? I assume your scenario is root (local) -> skill (remote).
Could you double check root bot and skill bot are assigned with different appid and password. if the issue is still there, could we set up a call to discuss more details on this? luhan@microsoft.com

**Comment by danielallen73** [comment]
Hi @luhan2017. The above info is for Skill bot. My scenario will be root (local) to skill (remote) initially before I deploy my root bot as well. 
As I was having issues before I was expecting to be able to test my skills bot from Bot Channels Registration "Test in Web Chat"

Please advise if I'm going about this the wrong way and whether I should only connect local root to remote skill using Ngrok url within the root (skill consumer) bot's configuration of the skill host end point.

Thank you for email, I'll send a meeting invite. Please note I am on GMT.

**Comment by peterinnesmsft** [comment]
@luhan2017 can you please review the customer ask above and respond accordingly? Thank you!

**Comment by luhan2017** [comment]
I've synced with customer offline through Teams. But the issue is not resolved yet, we will schedule further meetings and I will update this issue later.

**Comment by pavolum** [comment]
May be duplicate #6594

**Comment by tsuwandy** [comment]
@luhan2017, has this issue been resolved offline?

**Comment by luhan2017** [comment]
Not yet, @danielallen73 you didn't reply my email. Please email me if the issue still exists.
