### ISSUE TITLE
error on creating dialog

### ISSUE THREAD

**Issue by liweitian** [microsoft/BotFramework-Composer#6409]
## Describe the bug
The main operation is not affected. Only a weird error shows up.
1. create a new bot.
2. add more languages.
3. create a new dialog.

It seems that it is trying to create a .lg (without a name) file and then to delete it. 

![微信图片_20210315161724](https://user-images.githubusercontent.com/24380525/111123180-fa493100-85a9-11eb-891f-db79fc8afc29.png)

**Comment by boydc2014** [comment]
@liweitian or @lei9444 can you help check this one ?

**Comment by boydc2014** [comment]
is it possible, something happening in the persistence layer?
