### ISSUE TITLE
bug: composer doesn't see component dialogs that are in subfolders

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#6417]
## Describe the bug

If a component exports multiple dialogs, some of them will live inside subfolders, resulting in an imported structure like:

/dialogs/imported/{Component}/{Dialog}/{Dialog}.dialog

These are currently invisible to composer because the botStructure is only looking 1 folder deep.

See here: https://github.com/microsoft/BotFramework-Composer/blob/00f292a10a7537bc68cf6ebd2a34e1cb264385cf/Composer/packages/server/src/models/bot/botStructure.ts#L30

## Version

1.4.x

## To Reproduce

1. Simulate a component that has some dialogs in a subfolder by moving some dialogs into an imported folder, such as imported/fakepackage/mydialog/mydialog.dialog
2. open in composer - you will not see mydialog

## Expected behavior

All exported dialogs will be visible to composer

**Comment by benbrown** [comment]
We need to be able to support BOTH:

(root dialog style)
`/dialogs/imported/MY-COMPONENT/mydialog.dialog`

AND

(child dialog style)
`/dialogs/imported/MY-COMPONENT/mydialog/mydialog.dialog`

**Comment by benbrown** [comment]
I am not sure how to do this with a glob in such a way that does not result in Composer finding the same file multiple times, causing errors.

**Comment by benbrown** [comment]
@zhixzhan Can you take a look at this please?

**Comment by boydc2014** [comment]
@zhixzhan is out this week, I will take a look at this today
