### ISSUE TITLE
Imported package adds blank response to the bottom of the last lg (before comment) 

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#6419]
When adding a package with package manager, the import process generates a blank response after the last response in the lg file and before the import comment:

![image](https://user-images.githubusercontent.com/12264946/111252103-cf310280-85e6-11eb-8b85-db50cc42bd97.png)

The blank line goes away after clicking on the sendactivity action but it shouldn't have been there during the import.

## Version

![image](https://user-images.githubusercontent.com/12264946/111252187-f2f44880-85e6-11eb-84ce-ead1b05b606d.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Import a package that has lg.
2. Open one of the dialogs with lg
3. Click on the SendActivity action that has the > imported XYZ comment and you'll see the blank line between the last utterance and the imported comment.
4. Click away from the action and come back and you'll see that composer removed the blank line

**Comment by a-b-r-o-w-n** [comment]
This `> Imported: ...` comment is added as part of the dialog merge process. It should not be visible in the UI at all. @garypretty assigning this to you because @benbrown mentioned that there is still some discussion happening about this comment and we still need to get alignment on how to address.

**Comment by gabog** [comment]
In addition to the issue above, that imported line ends up being picked up as a possible response:
![image](https://user-images.githubusercontent.com/12264946/111412688-416f1900-86b3-11eb-89fa-2969f3396bb4.png)

**Comment by benbrown** [comment]
> In addition to the issue above, that imported line ends up being picked up as a possible response:
> ![image](https://user-images.githubusercontent.com/12264946/111412688-416f1900-86b3-11eb-89fa-2969f3396bb4.png)

This is NOT EXPECTED, as that line should be interpreted as a comment.

@chrimc62 Do you know anything about the LG comment syntax changing?
