### ISSUE TITLE
calling adaptive card inside multichoice prompt

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-Composer#6421]
Hi,

I have  called a adaptive card(contains a text message) from a multichoice prompt  but it is not working.
Is there any way to resolve the issue.

![image](https://user-images.githubusercontent.com/36945600/111261983-64fd7980-8649-11eb-8c3a-f230c28763c0.png)

The message should come from the adaptive card on below highlighted area.

![image](https://user-images.githubusercontent.com/36945600/111262872-f6212000-864a-11eb-93ba-bd642b8d02fe.png)
[newbot.zip](https://github.com/microsoft/BotFramework-Composer/files/6146471/newbot.zip)

Thanks...

**Comment by Danieladu** [comment]
Change `"height": "1px",` to `"height": "1px"`, (remove the trailing comma). because the comma would make the json invalid.
Have a try.

**Comment by madbeher** [comment]
Tried above solution its not working.

**Comment by Danieladu** [comment]
You may also should change the "list style". 
![image](https://user-images.githubusercontent.com/7289268/111424270-7d929000-872c-11eb-86f8-2b8e2170b466.png)
to set the ListStyle to control how choices are rendered.
Here is the reference:
https://docs.microsoft.com/en-us/javascript/api/botbuilder-dialogs/liststyle?view=botbuilder-ts-latest
Maybe "SuggestedAction" is more suitable. heroCard mode would override the messages's attachment with herocard.

**Comment by madbeher** [comment]
Thanks its working.
