### ISSUE TITLE
Multiple Luis Apps for Each Dialog

### ISSUE THREAD

**Issue by philip-mc** [microsoft/BotFramework-Composer#6423]
## Describe the bug

This may or may not be a bug however I feel as if the system is not working as expected. 

I am using bot composer to handle dialog flow and have just added Luis in. I would expect to have one Luis app for my whole project that covers a list of intents and entities. When I check in Luis I see a new app for each dialog. 

I really do not wish to maintain several duplicate lists of intent/entities across multiple dialogs. There is significant cross over of language use between the dialogs. 

## Version

1.3.1

## OS

- [ ] Windows

## To Reproduce

Add the default recognizer to two dialogs in a wider bot composer project. When you add intents and start the bot multiple apps appear in luis. 

## Expected behavior

I would expect one app to cover the entire bot composer project. 

## Screenshots

![image](https://user-images.githubusercontent.com/73343537/111307386-44d1b880-8651-11eb-8b53-845c3602e74f.png)

**Comment by a-b-r-o-w-n** [comment]
@philip-mc #6244 describes a way to share intents and entities across multiple lu files. I hope that is a solution for your use-case. I will defer to my colleague to explain why Composer creates a new Luis application for each dialog.

**Comment by philip-mc** [comment]
Really struggling with this implementation and workaround. As I have 2 apps luis one for the parent dialog and one for the child I end up with a 403 error. 

I can only add the keys for the parent to the app setting json so once in the child it just breaks......

Is there a way to only use the parent lu app even when in the child?

**Comment by lauren-mills** [comment]
@philip-mc - Are you using different LUIS authoring and prediction resources for your child dialog LUIS model than your root dialog?

**Comment by philip-mc** [comment]
Ok i have got to the bottom of the issue now. 

Firstly - sharing common entities works a treat once I figured it out so thanks for that bit. 

The second issue is we use a c sharp bot blended with composer dialogs. The way the c sharp bot references the settings means I constantly get a message ("" is not a valid luis application id ) - it doesnt read the files in the generated folder instead I need to copy each of the luis appid's into the root settings file for it to work. If I boost into emulator via composer the dialogs and luis work find however when debugging using visual basic this is where it breaks. There was a fix listed here - https://github.com/microsoft/BotFramework-Composer/issues/2751 - however it still seems to be broken on my end.

**Comment by lauren-mills** [comment]
@philip-mc - Can you elaborate on how you are combining your C# code with your declarative files in Composer? We do not recommend combining the two approaches in the same bot (for these exact sorts of issues). Our recommended approach to using both would be to use the skills architecture to handle communication between C# bots and declarative bots. But it would be good to understand your scenario.

In a composer-built declarative bot, the underlying startup code helps register all the locations of settings files including the LUIS settings in the generated folder. Have you modified this code? It would help us to know what changes you needed to make here and what scenarios you are trying to enable.

**Comment by tdurnford** [comment]
@philip-mc can you provide more information regarding your bot architecture?

**Comment by chrimc62** [comment]
@philip-mc sounds like you have solved your problem.  If you still have an issue, please reopen this item.  Sorry for the difficulties you have had--we are always trying to figure out how to make things simpler and clearer, but this is a complex area.
