### ISSUE TITLE
Teams SSO not working (anymore)

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#6424]
This is a real strange issue...:

We have a bot in production that uses Teams SSO and is working fine. I remember that setting this up was quite the hassle and documentation was pretty poor. However I simply cannot get another bot to work with SSO anymore, no matter what I try. I know that there has been an update on Bot Channels Registration in the meantime and also that BCR is as buggy as it gets (creating channels, connections etc via Arm / CLI).

I have exactly replicated the setup of the new bot with the one in production, but no matter what it won't work and always throws a 412 Precondition Failed response.

This is what happens:
- Teams responds to the OAuthCard with a signin/tokenExchange invoke activity containing the token in the value
- The bot responds with a 412 Precondition Failed response, with failure detail: "The bot is unable to exchange token. Proceed with regular login."

This indicates to me that the exchange of the token to an accessCode fails. When I then clear the Token Exchange URL in the Bot Channels Registration Connection, the OAuth Card is shown in teams and logging in works fine.

I have compared the OAuth connections via the Azure CLI  (as there is always some confusing overlap in properties & parameters (scopes, clientId & Secret can exist in both, but if that's required or not...?)

To me this either seems I am overlooking something really stupid or there has been a bug introduced in between the previous bot and this one.

**Comment by a-b-r-o-w-n** [comment]
@cxbuilders There was a service outage yesterday affecting AAD. Perhaps your testing was impacted? Can you try again?

**Comment by cxbuilders** [comment]
@a-b-r-o-w-n Hey Andy, tried this last week and again today to see if I missed anything. All same results. Also two different tenants

**Comment by EricDahlvang** [comment]
Hi @cxbuilders 

If the user has never consented to this app, PreconditionFailed is the correct response.  Teams client should then be popping up a little notice, enabling the user to provide consent (i do not have a screenshot right now, but can provide one if needed).  Subsequent sso flows should properly exchange the token.

**Comment by cxbuilders** [comment]
@EricDahlvang Teams and the App registration is in the same tenant and the api permissions are admin consented, hence it should not ask for additional user consent. This is per documentation and also how the current bot in production behaves (the business would have never accepted the user consent question anyway).

Forgot to mention that the 412 is spit out 3 times everytime and then the consent message at the bottom pops up. Consenting it in Teams does not do anything, when trying to login again, the same 3 invalid prompts are displayed with the consent message (3* prop the max try in the oauth card)

**Comment by cxbuilders** [comment]
@EricDahlvang I can mail you more details with the Teams App Manifest, screenshots of the App Registration / OAuth Connection etc. Let me know.

**Comment by EricDahlvang** [comment]
Please do email me @ the address on my github profile.

**Comment by cwhitten** [comment]
@EricDahlvang / @cxbuilders were you able to connect?

**Comment by EricDahlvang** [comment]
@cwhitten i did receive an email from @cxbuilders last Thursday, but have not had time to go over it just yet.  I'll close this, and we can resolve it offline.
