### ISSUE TITLE
No way to start a new line in multiline text boxes in LG editor

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#6430]
## Describe the bug

When using the multiline text boxes for variations in the LG editor, I cannot use Alt+Enter (on Windows) to start a new line.  When I try this a new variation is created as if I just hit enter.

We need to provide the expected behavior for a user to move to a new line.

**Comment by hatpick** [comment]
It's shift+Enter, why are you trying alt+enter I'm curious

**Comment by hatpick** [comment]
It's shift+Enter, why are you trying alt+enter? I'm curious if that's a key combination that more users are familiar with, otherwise in LG all up view, template editors (not monaco) use shift+Enter for new line as well.

(Latest on main has this implemented, it also shows new line chars)
#6394

**Comment by garypretty** [comment]
@hatpick Sorry, shift + enter is fine.  Had it in my head that alt + enter was the combo.  Just tested and shift + enter works for one line, but if I try and add more than one additional line and try shift + enter again, it starts a new box instead of adding another line.  Can you repro that your side?

**Comment by hatpick** [comment]
@garypretty It works fine on my end, the PR I've referenced above has a video in it, it's supposed to work like that, here's another one:

https://user-images.githubusercontent.com/1483492/111424466-0bc83100-86af-11eb-8811-8b6ff13449b5.mp4

**Comment by garypretty** [comment]
Weird. I don't see the same behavior. I can only ever do one line initially.  If I try and add a line to an existing box that fails too. 

![LG Shift Enter Error](https://user-images.githubusercontent.com/3900649/111453846-eb7a8f80-870b-11eb-8b38-14eaa2ebfc46.gif)

**Comment by hatpick** [comment]
@garypretty what composer are you using?

**Comment by garypretty** [comment]
@hatpick Latest nightly electron. v1.4.0-rc2-nightly.2021317.224525.830559e

**Comment by hatpick** [comment]
@garypretty RC2 does not have that PR in it, it is off of a rc branch before the PR was merged to main, try latest on main.
