### ISSUE TITLE
Utterance is not passed to skill if disambiguation kicks in at parent

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6431]
Filed for tracking (along with conversation)

Before I file it, I want to make sure I got it right.

Scenario:
•	Root bot with Orchestrator
•	Child bot with LUIS
•	Routing works correctly.
•	Without disambiguation child get’s utterance (turn.text?) and is able to trigger on it.
•	Issue: With disambiguation: I suspect that utterance is not passed to skill, so skill cannot trigger on recognition.

Failure case (with disambiguation):

![pic1](https://user-images.githubusercontent.com/8867670/108273736-d3254e00-7128-11eb-8835-10e8071043d5.png)

Repeated without disambiguation:

![pic2](https://user-images.githubusercontent.com/8867670/108273780-e46e5a80-7128-11eb-88ab-50f9d304155b.png)

**Comment by ryanlengel** [comment]
Added tags, I'm assuming that the dialog provided when adding the `Microsoft.OnChooseIntent` trigger is provided by the SDK (having difficulty tracking down it's source).

**Comment by cwhitten** [comment]
@cleemullins @ryanlengel why was this transferred to the Composer project? Seems like it should to go the SDK

**Comment by scheyal** [comment]
@cwhitten  (I asked.) 

The issue is in the specific choose intent trigger flow in Composer. It loses the turn.activity.text, hence once have to cache it. I think the solution is to fix the choose intent flow in Composer.

**Comment by ryanlengel** [comment]
@cwhitten, this is feedback for the predefined dialog that Composer adds in the [dialogFactory.ts](https://github.com/microsoft/BotFramework-Composer/blob/294514fbf2a5a3b5110889bd4f4dba04567c90d0/Composer/packages/lib/shared/src/dialogFactory.ts#L177). I'm not sure what area to label this under, assigning to you for triage.
