### ISSUE TITLE
Mismatched Azure resource types in the existing provisioning flow

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/BotFramework-Composer#6439]
## Describe the bug

1. On the **Add resources** and **Review & create** pages, these are the required resources I am creating:

   ![2](https://user-images.githubusercontent.com/32497439/111399735-300e1880-8683-11eb-8293-1a9d02f7e94e.png)
   
   ![3](https://user-images.githubusercontent.com/32497439/111399937-92ffaf80-8683-11eb-87c5-4751908d3836.png)

2. After the provisioning is completed, I found these are the resources in the Azure portal:

   ![4](https://user-images.githubusercontent.com/32497439/111400144-f25dbf80-8683-11eb-8b25-d26074d611cd.png)

## Version

https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.4.0-rc1-nightly.20210316.223882.e40f9bf

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Follow this [doc](https://docs.microsoft.com/en-us/composer/how-to-publish-bot) to provision new resources.

## Expected behavior

Should have consistent resource types b/w Composer UI and Azure portal.

**Comment by mareekuh** [comment]
@Andrea-Orimoto  - are these the actual resource names in ABS ?

**Comment by boydc2014** [comment]
This looks expected, there is usually a difference in the preview resource type and final resource type, but usually it's hard to notice. But in bot service's case, this difference is big enough to notice. 

I expect this should function well.

**Comment by zxyanliu** [comment]
Yes, it's functional.

**Comment by zxyanliu** [comment]
I am closing this issue for now as it is functional and some of the content will be covered in the documentation.
