### ISSUE TITLE
Form dialog LU editing in LU all up view

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#6440]
- Generate form dialog based on form schema
- go to LU all up view
- LU authoring hit issues
** click 3 dot to edit the LU content for each item, it will show as following
![image](https://user-images.githubusercontent.com/43408889/111432289-c865d500-8737-11eb-9b34-6814a457a636.png)

** no showcode button
![image](https://user-images.githubusercontent.com/43408889/111432132-981e3680-8737-11eb-9438-ed4b3f2cf064.png)

**Comment by alanlong9278** [comment]
Hi, @sorgh  I see there is a limit that do not show `show code` button when `isRoot`  in lu/qna page, but not in lg page. Like below shows
```
const isRoot = dialogId === 'all';  // dialogId is the dialogId in url
if (!isRoot) {
      return (
        <ActionButton data-testid="showcode" onClick={onToggleEditMode}>
          {edit ? formatMessage('Hide code') : formatMessage('Show code')}
        </ActionButton>
      );
    }
```
Is the limit  expected and should we keep the three pages consistant?

**Comment by alanlong9278** [comment]
@hibrenda  I have checked the edit action. Is the action gif showed expected.
![luEdit](https://user-images.githubusercontent.com/5860999/111438318-116d5780-873f-11eb-9bdb-e9b4ad470a2d.gif)
