### ISSUE TITLE
default Common.lg import statement is wrong and will never work for multi-lingual bots

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6449]
## Describe the bug
Currently when a .lg file is created it includes a reference to common.lg.  Common.lg is shared for ALL languages, and so it is the wrong pattern for defining shared language assets.

## Version

1.4.rc2

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Create new package, look at the default LG file which is created when you create a new dialog. 

common.en-us.lg
mydialog.en-us.lg
```md
   [import](common.lg)
``` 
The import statement should be 
```md
[import](common.en-us.lg)
```

## Expected behavior
Imports need to be the same language as the source file, so if you have
foo.**{lang}**.lg 
the import needs to be
importedfile.**{lang}**.lg

If you don't do this, the language binding for multi-lingual WILL NOT WORK.

This is exactly the situation that HP was having that we just walked them through. 

Composer needs to correctly do the right import statement if it's going to model imports.

**Comment by boydc2014** [comment]
@tomlm the import statement doesn't matter, we use the import resolver to correctly resolve the right common.{locale}.lg file. 

I will double confirm the case, do you have a case that it is not working?

**Comment by boydc2014** [comment]
I just confirmed in 1.4.0-rc2 it's working as expected. 

Here is my simple bot that have two locale, can you try this?
[EchoBot-1.zip](https://github.com/microsoft/BotFramework-Composer/files/6160793/EchoBot-1.zip)

**Comment by boydc2014** [comment]
@tomlm can you attach the case that is not working?

**Comment by cwhitten** [comment]
Team cannot reproduce this behavior. Need more information from the customer
