### ISSUE TITLE
Settings is showing SkillHostEndpoint as the first setting, and that's wrong

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#6450]
## Describe the bug

The SkillHostEndpoint is an adanced concept and is related to the *published* profile.  This should not be first in the UI.

## Version

1.4.rc2
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Create new bot.

## Expected behavior

Look at screen shot, this should be way down below the fold and probably be part of the publish profile (because this value changes for each publish target.)

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/111525810-3b148780-871b-11eb-99ff-ca07f87dd58f.png)

**Comment by cwhitten** [comment]
@benbrown is this tracked somewhere else in the creation work? please close if so
