### ISSUE TITLE
Provision failure - When adding a publish profile

### ISSUE THREAD

**Issue by blakehoughton** [microsoft/BotFramework-Composer#6468]
## Describe the bug/Steps

1. Created Bot
2. Set up bot with intents
3. Wanting to publish to my azure account
4. Click on the spanner - Add new publish profile
5. Created profile name and entered Publish bot to azure web app
6. Created new Azure resources, entered subscription, Host name and Location as Australia East
7. Hit done
8. After a few seconds the error below comes up:
CREATE_RESOURCES_ERROR - Error - detail message can see provision.(Profile Name).log in your bot folder

## Version
v1.3.1

**Comment by blakehoughton** [comment]
@anusharavindrar any suggestions?

**Comment by anusharavindrar** [comment]
@blakehoughton, can you double-check in case you missed out on any step in this [documentation]( https://docs.microsoft.com/en-us/composer/how-to-publish-bot) ? Also, can you attach a screenshot of the error you are getting?
