### ISSUE TITLE
Bot Framework Composer doesn't recognize custom function

### ISSUE THREAD

**Issue by hebaelfadly** [microsoft/BotFramework-Composer#6473]
## Describe the bug
I'm trying to access custom function inside the composer UI but Bot Framework Composer doesn't recognize custom function.

## Version

![image](https://user-images.githubusercontent.com/61690067/111609232-c3119480-87e2-11eb-8be0-eea292634357.png)

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Register the function in the runtime. I followed the instructions [here](https://docs.microsoft.com/en-us/azure/bot-service/language-generation/bot-builder-howto-use-lg-custom-functions?view=azure-bot-service-4.0&tabs=cs) to 
The ComposerBot constructor is as below
![image](https://user-images.githubusercontent.com/61690067/111608970-7b8b0880-87e2-11eb-8e46-ea827060bcb4.png)

2. Add the function name into the settings like it's indicated [here](https://docs.microsoft.com/en-us/composer/how-to-validate#custom-functions) 
The bot settings is as below
![image](https://user-images.githubusercontent.com/61690067/111609046-8fcf0580-87e2-11eb-8a73-37420b80c67a.png)

## Screenshots

The composer still not recognizing it showing this error
![image](https://user-images.githubusercontent.com/61690067/111610025-93af5780-87e3-11eb-8be4-fb3d80b274e6.png)

**Comment by cwhitten** [comment]
@hebaelfadly if you switch to the early adopters feed, this should be a warning instead of an error. Can you try this? This should unblock you as we revisit the `customFunctions` property in appsettings.

**Comment by hebaelfadly** [comment]
@cwhitten enabled it, still having an error
![image](https://user-images.githubusercontent.com/61690067/111900823-547c4300-8a3d-11eb-9bde-08bebb35259c.png)

![image](https://user-images.githubusercontent.com/61690067/111900844-6e1d8a80-8a3d-11eb-8016-0d562eaa3f7c.png)

**Comment by hebaelfadly** [comment]
@cwhitten ok it's working now

**Comment by cwhitten** [comment]
Great. I'll close this on then.
