### ISSUE TITLE
Error validations in provisioning & publishing

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#6477]
As a bot developer when I have to provision resources from Composer, I want to be given good error validation when creating new resource group names:

- Error validation when a resource group name already exists
- Error validation if the naming structure does not meet the criteria

**Proposed design solution >** 

![error validation_01](https://user-images.githubusercontent.com/67944302/111683315-8b0a5180-87e2-11eb-923c-7439e2265760.png)
![error validation_02](https://user-images.githubusercontent.com/67944302/111683323-8d6cab80-87e2-11eb-9ef5-647a2cc13462.png)

**Comment by mareekuh** [comment]
Captured in XLS - will get to asap.
