### ISSUE TITLE
slack-adapter taking to long to acknowledge message from Slack API

### ISSUE THREAD

**Issue by martinlarosa** [microsoft/BotFramework-Composer#6484]
I'm trying to use the slack-adapter and I run into a couple of issues that are not mentioned in the documentation.

1. I'm getting all messages from slack, even the ones the bot sends. I think this is expected but none of the sample code takes this into account, am I doing something wrong or are the samples wrong?
2. This is my main issue, the bot is taking longer than 3 seconds to acknowledge the request to the slack API, thus I'm getting a lot of duplicated messages. Shouldn't the adapter acknowledge the message to the slack api before running the pipeline? Or what's the suggested approach?

**Comment by martinlarosa** [comment]
Thanks! @stevkan 
Just to clarify, as I stated in this comment I was able to reproduce the problem with the sample code not related to Composer.

> You can reproduce it with this code: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/60.slack-adapter
> 
> Add this line to OnMessageActivityAsync in EchoBot.cs
> `Task.Delay(3000);`

**Comment by stevkan** [comment]
@martinlarosa, thank you for your patience. It took me a while to repro due to an unrelated issue, but I was finally able to do so. As a feature request, I will get this routed to the appropriate team for consideration.

**Comment by martinlarosa** [comment]
No problem @stevkan, glad you were able to reproduce it. 
Let me know if I can assist in any way.

**Comment by martinlarosa** [comment]
@stevkan I created a draft PR to help on this. Can we move this issue back to the botbuilder-dotnet repo so I can link it?

**Comment by stevkan** [comment]
Hi @martinlarosa, I spoke with the team regarding this and the strong suggestion was that this should be implemented at the developer level vs. a change to the SDK. That is, if an acknowledgment needs to be returned to Slack immediately, then this should be implemented on an individual basis.

Given that response, I am closing this issue.

**Comment by martinlarosa** [comment]
@stevkan thanks for your reply. 
I understand the decision but did the team discussed the possibility of adding an extensibility point into the code so that we can add this modification without having to fork the code and then need to do maintenance after every new version?
