### ISSUE TITLE
inline lu editor did not show as expected for reference intent

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#6489]
- Enable new creation experience
- create calendar bot
- Reference intent in LU file
![image](https://user-images.githubusercontent.com/43408889/111966537-fda46580-8b31-11eb-861c-f355cde52cb9.png)
- Inline lu content did not show correctly
![image](https://user-images.githubusercontent.com/43408889/111966361-c9c94000-8b31-11eb-8d1c-ecdb0f682507.png)
- LU all up view show as expected
![image](https://user-images.githubusercontent.com/43408889/111966498-f2513a00-8b31-11eb-95b3-c2de3404efd8.png)

**Comment by mewa1024** [comment]
@sangwoohaan fyi
