### ISSUE TITLE
Calling skills in teams app

### ISSUE THREAD

**Issue by rahul-8437008949** [microsoft/BotFramework-Composer#6494]
Hi, I am able to call the skill through web app ,but I am not able to call skill from the same bot when deployed on teams. Can anyone suggest a way to call skill through bot deployed on teams.

**Comment by v-kydela** [comment]
Thank you for the question, @rahul-8437008949 

Can you show us some screenshots so we can get a better understanding of what's happening? What do you mean when you say you're not able to call the skill? What happens when you try?

**Comment by rahul-8437008949** [comment]
Hi @v-kydela .I was able to rectify the issue .The problem i am facing is authentication. I am not able to add Oauth authentication to bot deployed on teams. The hero card for authentication is not displayed in teams app.

**Comment by rahul-8437008949** [comment]
![Screenshot (157)](https://user-images.githubusercontent.com/54345729/112044375-c5237c80-8b6f-11eb-8246-db85932d06d3.png)
![Screenshot (159)](https://user-images.githubusercontent.com/54345729/112044381-c5bc1300-8b6f-11eb-936e-090e37e68655.png)


As you can see in emulator ,Authentication works fine but in teams app authentication doesnt work.

**Comment by v-kydela** [comment]
@rahul-8437008949 - Can you show us the relevant bot code?

**Comment by rahul-8437008949** [comment]
![Screenshot (162)](https://user-images.githubusercontent.com/54345729/112048915-ec307d00-8b74-11eb-882f-4c84f633b6ad.png)

**Comment by v-kydela** [comment]
@rahul-8437008949 - When you test on Emulator you're using a local bot and when you test in Teams you're using a remote bot, right? What happens when you test your remote bot in Emulator? Also what happens when you test your local bot in Teams using a tunneling service like ngrok?

**Comment by rahul-8437008949** [comment]
@v-kydela , The screenshot for emulator is for a remote bot only. In both teams and emulator Remote bot is used.

**Comment by rahul-8437008949** [comment]
![Screenshot (166)](https://user-images.githubusercontent.com/54345729/112106076-32b4c480-8bd3-11eb-8796-5854bba3eeab.png)

![Screenshot (168)](https://user-images.githubusercontent.com/54345729/112106083-33e5f180-8bd3-11eb-877c-2176e13fff0e.png)

Here ,i am able to call an external api in teams but not able to Call Oauth login.Invalid prompt gets triggered.

**Comment by rahul-8437008949** [comment]
@v-kydela ,can you please help me out

**Comment by v-kydela** [comment]
@tdurnford - Why did you remove the Bot Services label?

@rahul-8437008949 - What happens when you try running the bot locally?

**Comment by rahul-8437008949** [comment]
> @tdurnford - Why did you remove the Bot Services label?
> 
> @rahul-8437008949 - What happens when you try running the bot locally?

It works fine in the emulator.I am able to authenticate user using local bot by tunneling ngrok.

**Comment by rahul-8437008949** [comment]
I am able to make http requests in teams. Is there any way i can authenticate user using send an http request feature?

**Comment by v-kydela** [comment]
@rahul-8437008949 - What sort of HTTP request are you imagining? You should not get the username and password from the user directly (basic auth) because that would be a security breach. In order to use OAuth, you need to have the user open a URL on their end rather than having the bot access a URL on its end. You could potentially get OAuth to work by sending a hero card to the user with an open-URL action for them to click, but the URL wouldn't be able to complete the OAuth transaction automatically in that case and so it would need to give the user a magic code that they'd need to enter into the Teams chat. It would be better to use a signin action in a signin card or an OAuth card, which is what an OAuth input dialog generates.

**Comment by rahul-8437008949** [comment]
Ya , Oauth is definitely better method ,but it isn't running in the teams app so i was looking for alternates.

**Comment by rahul-8437008949** [comment]
![Screenshot (170)](https://user-images.githubusercontent.com/54345729/112198564-409a3200-8c33-11eb-851a-8dd9d93a05fc.png)


This is my connection string, Should I make any edits in this so that Oauth card rendered in MS-Teams

**Comment by tdurnford** [comment]
@v-kydela Unintentionally removed Bot Service

**Comment by v-kydela** [comment]
@rahul-8437008949 - Have you read this? https://docs.microsoft.com/azure/bot-service/bot-builder-authentication

You may notice that it says to leave the Token Exchange URL field blank. You may have been confused by the part that says to put "common" as the tenant ID. Try following the instructions and see if that fixes your problem.

**Comment by rahul-8437008949** [comment]
@v-kydela , Thanks a lot it worked. Don't know how I confused the 2 things. Thanks a million.
