### ISSUE TITLE
Refresh the microsoft teams chat with bot embedded code

### ISSUE THREAD

**Issue by praneeth1987** [microsoft/BotFramework-Composer#6498]
I have created a bot using bot composer and I have generated bot embed URL. I have accessed the same URL in browser and it got opened successfully in Microsoft teams

Now when I have updated the bot and published in azure, I am not finding an option to refresh this same in Microsoft teams
Is there any way to refresh the session and start the chat again with new modified bot????

**Comment by clearab** [comment]
Are you installing the bot as an app in Teams, or just connecting directly using the bot ID (not recommended)?

1-1 conversations in Teams are persistent between a bot ID and a user, there is no way to force the Teams client/backend to recycle that conversation ID.

**Comment by praneeth1987** [comment]
I am running with the URL generated from **Get Bot Embed Codes** in teams.
We haven't published  the bot as **app** in teams as of now as we are currently in testing phase

![image](https://user-images.githubusercontent.com/53040756/112100725-9509c700-8bcb-11eb-9259-4a414446bac6.png)

**Comment by jwiley84** [comment]
Closing as a duplicate of https://stackoverflow.com/questions/66751112/refresh-the-microsoft-teams-chat-with-bot-embedded-code
