### ISSUE TITLE
Error publishing in new profile - Access denied due to invalid subscription key or wrong API endpoint

### ISSUE THREAD

**Issue by dinobrago** [microsoft/BotFramework-Composer#6501]
## Describe the bug

In Composer v 1.3.1, I have a bot and I created a new publishing profile. Upon publishing, I get the error: 
Access denied due to invalid subscription key or wrong API endpoint.

The script then goes on to complete publishing successfully although the published bot often has problems. 

## Version

Composer v 1.3.1, v1.40

## OS

Windows 10

## To Reproduce

1. In composer, project setting, click "Add new publish profile"
2. Entered a name and selected the publish target of "Publish bot to Azure Web App (Preview)"
3. Configure resources: select Create new Azure resources
4. Selected my subscription, Hostname and location (WestUS)
5. Review & Create, accepted defaults except removed Cosmos DB and QnAMaker
6. Azure gets provisioned successfully. 
7. In Azure portal, Edit web app service configuration>General settings> .NET Version = .NetCore and Always On
8. In Composer, Publish, select the new publish profile, select the bot, Click on Publish selected bots
9. Popup window appears: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
10. Click Ok, publishing continues
11. Bot successfully publishes. However, while publishing appears to be successful, there are situations where the bot doesn't start or the published bot does not reflect changes made in the local bot. 

## Expected behavior

Successful publishing with no errors, reflecting changes made to local bot. 

{
  "name": "JuryBot210322X",
  "environment": "composer",
  "runtimeIdentifier": "win-x64",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "xxxxxxx"
    },
    "cosmosDb": null,
    "blobStorage": {
      "connectionString": "xxxxxxxx",
      "container": "transcripts",
      "name": "jurybot210322x"
    },
    "luis": {
      "authoringKey": "xxxxxxxxx",
      "authoringEndpoint": "https://westus.api.cognitive.microsoft.com/",
      "endpointKey": "xxxxxxx",
      "endpoint": "https://westus.api.cognitive.microsoft.com/",
      "region": "westus"
    },
    "MicrosoftAppId": "xxxxxxxx",
    "MicrosoftAppPassword": "xxxxxxx"
  },
  "hostname": "JuryBot210322X",
  "luisResource": "JuryBot210322X-luis"
}

**Comment by praneeth1987** [comment]
Please refer to https://www.arafattehsin.com/bot-framework-composer-publish-azure-resources/ for publishing information with LUIS end point and authoring keys

**Comment by tdurnford** [comment]
@dinobrago Can you confirm what version you are using? We just released 1.4 the other day. Can you try publishing with the latest version?

**Comment by dinobrago** [comment]
I updated to 1.4 yesterday and I see the same error.

**Comment by dinobrago** [comment]
We reviewed the article that @praneeth1987 posted.  We didn't see any discrepancies except that we are publishing to a new resource group from scratch. There is no entry for an access token in the Composer publish profile. We assume that Composer get this programmatically.

**Comment by GeoffCoxMSFT** [comment]
@dinobrago Are you in a single tenant in your subscription?  We have other reports that folks with multiple tenants have issues.  Our nightly builds now support handling of multiple tenants.

**Comment by dinobrago** [comment]
Geoff,

It’s single tenant.

However, the problem seems to have resolved itself through no specific action of our own. At least, despite our efforts, we don’t know what change resolved the issue.

I know that this is frustrating, we would have preferred to understand the source of the issue but for now, it has gone away.

We can close this until / if it appears again.

Dean

---
Dean Goddette, Ph.D.
Project Manager
Sonant Corp.
858-864-1455

**Comment by GeoffCoxMSFT** [comment]
@dinobrago We made several fixes and improvements to our auth over the past couple of weeks.  Let's hope we've fixed it :)
