### ISSUE TITLE
Documentation on how to publish a Composer Bot to a Dev Ops pipeline

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6507]

**Comment by cwhitten** [comment]
@Dewain27 I've removed @luhan2017 's assignment and her team is focusing on other areas.

**Comment by Dewain27** [comment]
Team, please use this aka.ms link:
https://aka.ms/bfcomposercicd

**Comment by luzeunice** [comment]
Actually We are trying to deploy a bot throw some pipelines with DevOps , It will help me a lot !
