### ISSUE TITLE
Support activity and bot state inspection in the embedded Web Chat control

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#6511]
- [x] Capture message / trace / event activities (P0)
- [x] Capture network activity (P0)
- [x] Show selected item in inspector (P0)
- [ ] Fix layout so that Web Chat panel **does not** overlap with inspector pane (P2)
- [x] Expose runtime messages in "Output" tab (P0)
- [ ]~~Add different inspector experience for LUIS traces (P1)~~
- [ ] Selected inspected state in log -- link log item to item shown in inspector pane (P1)
- [ ] On initial load, select most recent activity (P1)

**Comment by tonyanziano** [comment]
@boydc2014 Yup, I have filled out the ticket with some of the work items needed to complete the task.
