### ISSUE TITLE
Support referenced LU authoring when adding a trigger 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#6512]
Based on the context of https://github.com/microsoft/BotFramework-Composer/issues/6489 , the calendar bot is using the referenced LU content for trigger phrases, so we need to support how to add trigger for referenced LU content from UX .

Option A : Auto attached trigger phrases if trigger name match with the intent name defined in lu (current or imported) file. 
Option B : Drop down list for user to choose to bind them together. 

Similarly what should be showed in the LU editor & inline LU view should be aligned with the action.
eg. for choosing from drop down list, we may display the referenced file path ?
      for auto attached trigger phrases we may extract the trigger phrase from corresponding lu file ?

@mewa1024 @sangwoohaan  @boydc2014 @zhixzhan

**Comment by sangwoohaan** [comment]
This is new to me – didn't know you can import lu files and reference them from activities. Instead of coming up short-term solution, I'd like to take some more time to investigate. Could this be an item for R14?

**Comment by mewa1024** [comment]
yes, I agree with @sangwoohaan. For R13, the new creation experience (with templates that import LU) is a preview experience.

**Comment by mewa1024** [comment]
@hibrenda, @sangwoohaan, I'm so sorry--I got R13 mixed up with R12 in my previous comment. I think we should consider this for R13 since many of the new templates will encounter this. Related issue filed by Lauren: #5358

**Comment by sangwoohaan** [comment]
As a temporary solution for R13, the solution would be as simple as this 
![Frame 53156](https://user-images.githubusercontent.com/50963385/112387784-6c5afd80-8caf-11eb-9948-425edfcc5454.png)

**Comment by zhixzhan** [comment]
Hi @hibrenda @sangwoohaan , before this new design, I figure out a solution to support display/edit referenced intent as well as it is in current file inside, no matter where actually the intent is, it behavior same. Do you think it's reasonable or we should take this new design? 
This is the PR 
https://github.com/microsoft/BotFramework-Composer/pull/6536

**Comment by mewa1024** [comment]
Hi @zhixzhan yes, I think we should go with your solution.

**Comment by mewa1024** [comment]
For the new trigger dialog, I think we should go with Option A for now. While Option B would make it easier to reuse trigger intents, I think it might confuse non-advanced users.

**Comment by mewa1024** [comment]
@srinaath okay to move this to R15 milestone?
