### ISSUE TITLE
Yarn install failed in windows

### ISSUE THREAD

**Issue by lei9444** [microsoft/BotFramework-Composer#6515]
## Describe the bug
![image](https://user-images.githubusercontent.com/39758135/112111048-a4e6d280-8bee-11eb-8bf5-33b8ee54bf80.png)

## Version
main branch

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by lei9444** [comment]
remove the old node-modules can solve this issue

**Comment by tdurnford** [comment]
@a-b-r-o-w-n  Can you take a look at this?

**Comment by lei9444** [comment]
remove the old node-modules can solve this issue
