### ISSUE TITLE
Prevent composer from updating LUIS intents

### ISSUE THREAD

**Issue by hebaelfadly** [microsoft/BotFramework-Composer#6518]
I need to access already existing LUIS app so I followed @cwhitten comment here #2893 and it ended up using the same LUIS app that I exported and imported not creating a new one, and that's great. But when I add any intent from the LUIS portal without adding it in the composer user input and restart the bot the added intent is removed from the portal.

Is there a way to access the LUIS app with read-only mode?

**Comment by anusharavindrar** [comment]
@hebaelfadly, thanks for the above info. Let me attempt a repro on my end.
@feich-ms, is it possible that based on the above scenario that if they go and add the intent from the portal and restart the bot from composer, it is overwriting the intent in the portal as it isn't added in the composer user input?

**Comment by feich-ms** [comment]
@anusharavindrar AFAK, there is no way currently. Composer is designed to always update luis models if the contents are not aligned with that in luis portal.

**Comment by anusharavindrar** [comment]
@hebaelfadly, let me attempt a repro on my end. Thanks for your patience.

**Comment by anusharavindrar** [comment]
@hebaelfadly, what version of the composer are you on?

**Comment by hebaelfadly** [comment]
@anusharavindrar 
![image](https://user-images.githubusercontent.com/61690067/113946554-fb682980-9808-11eb-8bad-6d67a8b092d3.png)

**Comment by anusharavindrar** [comment]
@hebaelfadly, apologize for the delay in response. I am currently resolving issues with my Luis/Azure portal and will have an update for you soon. Thanks for your patience.

**Comment by v-kydela** [comment]
@hebaelfadly - Like @feich-ms said, the answer to your question is no. I will close this issue as resolved.
