### ISSUE TITLE
Start bot failed - Upgrade to composer 4.0

### ISSUE THREAD

**Issue by KarlXOL** [microsoft/BotFramework-Composer#6519]
After upgrading composer I get this error when starting the bot. I use custom runtime which worked well until the upgrade.
runtime build/run are also working without giving an error message

![grafik](https://user-images.githubusercontent.com/21153915/112140248-11080d00-8bd4-11eb-8824-d5b4cfdea763.png)

## Composer Version
1.4.0

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows 10
- [ ] Ubuntu

Appreciate any help

Thanks
Karl

**Comment by carlosscastro** [comment]
We have a PR for this issue, once it gets in, it will be fixed in the next release. Also, once it gets merged, you can try from our nightly releases to confirm that it fixes the issue before we release.
