### ISSUE TITLE
QnA Maker is using the LUIS region

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#6521]
## Describe the bug

Composer is using the LUIS region in settings when communicating with QnA Maker, which causes an error when starting a bot.

## Version

Version:  1.4.0-rc4-nightly.226081.b0a126
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce

1. Create a basic bot
2. Create a LUIS resource in West Europe and set authoring key / westeurope as region in bot settings
3. Create a QnA Maker resource in WestUS and set the subscription key in bot settings
4. Try and start the bot and the following error will be shown.

***Qnamaker build failed: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.***

Then, change the LUIS settings to use a West US resource and change region to West US - the bot will start correctly.

## Expected behavior

There should be a separate setting shown for QnA region and this should be used for QnA Maker.

**Comment by tdurnford** [comment]
@hibrenda Can you have someone take a look at this?

**Comment by hibrenda** [comment]
@garypretty  I could not repro on my side. I use westeurope for luis and westus for qna to the same bot.

**Comment by garypretty** [comment]
@tdurnford @hibrenda - ok, thanks for the testing.  I have found the issue. If I create a bot using the new Conversational Core template (i.e. the new runtime), the settings are missing the QnA Region setting.  It appears, because that is missing in my case, that the QnA is falling back to the LUIS region.

![image](https://user-images.githubusercontent.com/3900649/112284797-85e55080-8c81-11eb-9d1f-33f929bfcb13.png)

**Comment by garypretty** [comment]
I will raise an issue in the Components repo.
