### ISSUE TITLE
Start Bot error Composer 1.4.0 

### ISSUE THREAD

**Issue by naicud** [microsoft/BotFramework-Composer#6523]
Hi, I have installed the new version of MS BF Composer and i get this error when i try to start the bot :
![image](https://user-images.githubusercontent.com/55764723/112177677-6c002b00-8bf9-11eb-81fc-778aa81f5e53.png)

**Comment by naicud** [comment]
with the new version of composer the runtime path was modified so i have make this change:
It Works :) 
Before:
![image](https://user-images.githubusercontent.com/55764723/112186192-32332280-8c01-11eb-9275-10995524c5b7.png)

After:
![image](https://user-images.githubusercontent.com/55764723/112186262-3f501180-8c01-11eb-9db9-c02b8ff55f97.png)

**Comment by KarlXOL** [comment]
ok, thanks. I've checked the fix info already
I've created runtime,  bot creation and publishing is working again.
Thanks for quick response. Very helpful!
Karl
