### ISSUE TITLE
Cannot Create Bot From Conversational Core  Template - v1.4.0

### ISSUE THREAD

**Issue by anniexudan** [microsoft/BotFramework-Composer#6525]
## Describe the bug
In the latest version of v.1.4.0. Creating a bot from the template. Conversational Core template
Details
Error hit when instantiating remote template: error hit when installing the remote template

## Version

1.4.0

## OS
- [V ] Windows

## To Reproduce

1. Create a new bot from Template - Conversational Core 

## Expected behavior

No error

**Comment by cwhitten** [comment]
@pavolumMsft can you look into this?

**Comment by adiazcan** [comment]
Hello!  I have the same issue with the following version 1.4.0-nightly.229963.f72f063 of composer. 

![image](https://user-images.githubusercontent.com/6652046/113302770-adcb5880-9300-11eb-9848-b5466e892d7f.png)

**Comment by pavolum** [comment]
Excuse the delay, can you please try again with the latest nightly build of Composer? If you still have an error:
1. Ensure you have Node installed on your machine
2. If you have node and the error is still present, please send over the response from the erroneous server call. You can do this by running fiddler while you repro the bug, selecting the 500 server call and looking for the additional error info from that call. 

I will work on surfacing more informative error messages in the modal so future errors display the full issue for quicker debugging.

**Comment by pavolum** [comment]
I am closing this as it was likely due to bugs that have since been resolved in newer releases. @anniexudan please reopen if you experience these issues in the newer nightly versions of Composer.
