### ISSUE TITLE
Value cannot be null (DialogID) problem in Composer

### ISSUE THREAD

**Issue by formore5points** [microsoft/BotFramework-Composer#6552]
Is anyone getting that error after using a dialog for second time ? I'll upload the screenshots when I have access to my pc.
Briefly, I think that its about the dialog management. I have read this article : "https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0 " and didnt get a solution.

OS:Windows
Platform:Bot Framework Composer 1.4.0

**Comment by dmvtech** [comment]
HI @formore5points Yeah, screen shots or more steps to reproduce what you are experiencing would be good. Are you able to reproduce using one of the built in templates?

**Comment by formore5points** [comment]
Hi @dmvtech,
Thank you for your attention. I solved my problem and would love to share with you. When we want to make a flow like the one I have sent below, the dialogue A becomes the beginning, the dialogue B is a dialogue containing the term "end this dialogue" and the dialogue c is the key dialogue. If we want to go from the C dialog to the A dialog, when we go to the "Begin new Dialog" and create a new dialog, the rest of the dialog is wrong. Instead of saying "Begin new dialog", we need to use the term "end this dialog" to close all existing dialogs and reach the old A dialog. You can think of it as a recursive function structure. Thank you so much. 
![Dialog](https://user-images.githubusercontent.com/50989796/112591275-2fa91680-8e15-11eb-9f46-03a58453c889.png)

**Comment by praneeth1987** [comment]
@formore5points I am facing same issue, i could not clearly understand your solution. can you please share a sample bot with solution?

As per my bot, 

1. I have welcome dialog where I have multiple choice option ( 2 options)
2.  Based on multiple choice selection, I have created 2 different dialogs and in this we are connecting to QnA to fetch the response. (I have added repeat this dialog as I want to query for multiple questions in same QnA)
3. Once query is fetched, user shall be asked to continue in same dialog or not
4. if user does not continue, we ask again whether to cancel session or go to home. 
5. After 2 or 3 times repeat of above we value cannot be null issue.

**Comment by formore5points** [comment]
@praneeth1987 sorry for late answer. I was kinda busy. I will try to creating a new bot to see this error. Until I share the bot, the advice I can give you is, instead of using begin new dialog, use end this dialog.

**Comment by praneeth1987** [comment]
I have tried using end this dialog. After ending the dialog, i should immediately start a new dialog which is not happening and ending up with Value cannot be null(Dialog ID) error.

Please share your bot when you have time

**Comment by formore5points** [comment]
@praneeth1987 I couldn't create the error again. If you can, please send the bot as zip and I will try to figure it out.

**Comment by praneeth1987** [comment]
@formore5points : I have attached my bot here. I have removed my qna stuff and just added dummy text.
Can you please help me in checking here?
[BIHelpDesk-Final.zip](https://github.com/microsoft/BotFramework-Composer/files/6221714/BIHelpDesk-Final.zip)

**Comment by dmvtech** [comment]
Hi @formore5points You are no longer able to reproduce the error? I wasn't able to reproduce it myself.

@praneeth1987 

I am running your test bot, but I am also not able to reproduce the error. Can you let me know what the flow/path/choices I should be using to reproduce? I don't think i'm understanding the correct flow.

**Comment by formore5points** [comment]
@praneeth1987 Sorry I forgot, I was a little busy. I did not observe the error yet by running the bot, but even when I saw it, I understood where the error was If you are still interested I can help. I don't know how much our time difference is, but if you return within an average of 12 hours, I can solve your problem. 

@dmvtech Yes I am not but praneeth had give the path in his previous comments.I didn't try yet but It looks wrong anyway.

**Comment by formore5points** [comment]
@praneeth1987 Can you give a exact path that the where error occurs ?

**Comment by formore5points** [comment]
@praneeth1987 I attached the bot and transcripts as zip. You can check it out. You may need to go through these processes where necessary in the dialogue. I have drawn a flow to help you understand the error better. While you have to follow the A path, there is a problem in the dialogue flow because you are going the B path. I recommend you to read the dialogID and Dialog Stack sections in the link I gave. 

Link: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog?view=azure-bot-service-4.0

Screenshot:

![WhatsApp Image 2021-03-31 at 12 24 53](https://user-images.githubusercontent.com/50989796/113123084-ec87e280-921c-11eb-819d-bd727138cc49.jpeg)

[BIHelpDesk-Final_export.zip](https://github.com/microsoft/BotFramework-Composer/files/6235486/BIHelpDesk-Final_export.zip)

[transcripts.zip](https://github.com/microsoft/BotFramework-Composer/files/6235490/transcripts.zip)

**Comment by praneeth1987** [comment]
@formore5points  ; thanks for your explanation, do you have any working example on for loops in handy.I  just want to see the logic

**Comment by dmvtech** [comment]
> Also after completing 2 iterations and if I select home and then select any option in your bot, it is not prompting to enter the query. Instead it is taking the input as per selection button

Be sure you're aware of [memory scopes](https://docs.microsoft.com/en-us/composer/concept-memory) and how they work. For `user.`, it will store per-user and won't prompt if that is already populated and `always prompt` is set to `false` (as it is). You an change to always prompt: true, or you can delete the property at the begging of the dialog. You can also store the response into a `dialog.` memory variable and then only populate into `user.` if certain criteria are met. Really depends on the need and how you choose to design it.

A few points for clarity:

- Composer uses adaptive dialogs, and the dialog sections you have linked @formore5points aren't as applicable (straight over). [This documentation](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-adaptive-dialog-introduction?view=azure-bot-service-4.0) is more appropriate. 
- `End this dialog` [isn't needed](https://docs.microsoft.com/en-us/composer/how-to-control-conversation-flow#ending-dialogs) if the dialog itself is set to auto end (as is the case with all the ones in linked example). Although I understand this is a simple example, and you may want that in a more realistic scenario.
- Use of [interruptions](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-dialog-interruptions?view=azure-bot-service-4.0) is good practice and might be utilized to better design.
-

**Comment by dmvtech** [comment]
@formore5points Is there anything further needed? It is resolved for you, correct?

**Comment by formore5points** [comment]
Yes it is resolved, thanks
