### ISSUE TITLE
Add Items to Optional Next Steps

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6555]
## Is your feature request related to a problem? Please describe.

Need to add the following items to Next Steps as Optional:

- [x] Provision a Publishing Profile > Takes you to interface to add a publishing profile
- [x] Publish to a Publishing Profile > Takes you to Publish page
- [x] Enable Insights
Text:
Collect Service-level and Conversation-level data to help gauge the performance and efficacy of your bot
Akams url:
http://aka.ms/botinsights
linking to:
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics?view=azure-bot-service-4.0
- [x] Publish to Dev Ops > Take you to Documentation that should be created as part of Issue # 6257
Text:
Publishing to a Dev Ops pipeline using CI / CD.
Akams url:
https://aka.ms/bfcomposercicd

## Additional context

![image](https://user-images.githubusercontent.com/18688053/112502206-e0e97700-8d57-11eb-93a2-2619771f279e.png)

**Comment by Dewain27** [comment]
It would be best if we could be able to show "Add Connections" and "Publish to a profile" only if you have created a publishing profile.  Also hiding "Provision a Publishing Profile" if you have created a publishing profile.

**Comment by Dewain27** [comment]
@Dewain27  please review all learn more links

**Comment by Dewain27** [comment]
Blocked by #6507

**Comment by Dewain27** [comment]
Unblocked by generation of the aka.ms link and documentation will be updated to this link.
https://aka.ms/bfcomposercicd

**Comment by Dewain27** [comment]
Publish your bot is missing and should show up after you have created at least one publishing profile.  It used to be there, but has regressed:
![image](https://user-images.githubusercontent.com/18688053/116305061-dfe9a200-a768-11eb-8bb5-339283ef6f4d.png)

**Comment by benbrown** [comment]
The publish button is back here:

https://github.com/microsoft/BotFramework-Composer/pull/7484

**Comment by sgellock** [comment]
Shiproom - approved
