### ISSUE TITLE
Provision failure when creating azure resources

### ISSUE THREAD

**Issue by orcelik** [microsoft/BotFramework-Composer#6558]
## Describe the bug

Following the documentation to publish my bot. After loging in to my work account, selecting the options to Publish Bot ao Azure Web App, Create New Resource, adding the requested information and accepting the default options, when I click "Done" I get an error saying "Provision Failure - Error when provision target".

## Version

Version:  1.4.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Follow the guidance in documentation https://docs.microsoft.com/en-us/composer/how-to-publish-bot on a Bot Framework Composer v1.4.0

## Expected behavior

To publish bot, creating required resources as explained in documentation

## Screenshots

![publish-error](https://user-images.githubusercontent.com/42545856/112515185-b7077300-8d9e-11eb-95cd-8c3e25b67919.png)

**Comment by anusharavindrar** [comment]
@orcelik, this looks similar to the one in https://github.com/microsoft/BotFramework-Composer/issues/5650. Are you still getting the provision failure error after setting NODE_OPTIONS? Also, do you get any additional error on the dev console?

**Comment by orcelik** [comment]
@anusharavindrar, Yes, setting node_options did not change result. In dev console, I receive the error 
"... 
POST http://localhost:5000/api/provision/27109.469032035417/azurePublish 431 (Request Header Fields Too Large)"
even though I set NODE_OPTIONS="--max-http-header-size=16000"

I am attaching a screenshot below. Did you try to publish in v.1.4.0? Did you manage to publish yourselves?
![publish-error-2](https://user-images.githubusercontent.com/42545856/112714923-7bc38c00-8ee5-11eb-802b-12afb5fe73c7.png)

**Comment by Dewain27** [comment]
Should be fixed in the next release, please reopen if issue persists.  You can try the nightly to see if you can repro as well.
