### ISSUE TITLE
Unable to use Oauth card in teams app

### ISSUE THREAD

**Issue by rahul-8437008949** [microsoft/BotFramework-Composer#6560]
@cwhitten @v-kydela ,Oauth card renders in teams, a  link is also linked with the card but it goes nowhere on clicking ,It works fine in web chat.Can you please help me with it
![WhatsApp Image 2021-03-25 at 10 45 15 PM (2)](https://user-images.githubusercontent.com/54345729/112517793-c0083c80-8dbe-11eb-9643-827055b2ac78.jpeg)
![Screenshot (173)](https://user-images.githubusercontent.com/54345729/112517831-cdbdc200-8dbe-11eb-880a-b957c5a0f0cc.png)
![Screenshot (175)](https://user-images.githubusercontent.com/54345729/112517835-ce565880-8dbe-11eb-981a-f8aff7c77c7c.png)

**Comment by rahul-8437008949** [comment]
@v-kydela @cwhitten can you please help me out

**Comment by v-kydela** [comment]
@rahul-8437008949 - Did you include a valid domain in your app manifest according to these instructions? https://docs.microsoft.com/microsoftteams/platform/bots/how-to/authentication/add-authentication#install-and-test-the-bot-in-teams

**Comment by rahul-8437008949** [comment]
Yes i did

**Comment by v-kydela** [comment]
@rahul-8437008949 - May we see your app manifest?

**Comment by rahul-8437008949** [comment]
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.schema.json",
  "manifestVersion": "1.9",
  "version": "1.0.0",
  "id": "130545dd-fe94-4d16-ae84-6926383b4f6e",
  "packageName": "com.teams.auth.bot",
  "developer": {
    "name": "Rahul",
    "websiteUrl": "https://www.microsoft.com",
    "privacyUrl": "https://www.teams.com/privacy",
    "termsOfUseUrl": "https://www.teams.com/termsofuse"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Echobot",
    "full": "echobotcomposer"
  },
  "description": {
    "short": "bot trial",
    "full": "I will try to make an app of bot"
  },
  "accentColor": "#DA2DF0",
  "staticTabs": [
    {
      "entityId": "conversations",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "about",
      "scopes": [
        "personal"
      ]
    }
  ],
  "bots": [
    {
      "botId": "95c3c31e-88b5-4999-bc49-5f3b197d8c3c",
      "scopes": [
        "personal",
        "team",
        "groupchat"
      ],
      "supportsFiles": false,
      "isNotificationOnly": false
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "token.botframework.com",
    "login.microsoftonline.com"
  ]
}

**Comment by v-kydela** [comment]
@rahul-8437008949 - I can reproduce the problem. I've tried your app manifest, my app manifest, Composer bots, regular bots... I can't seem to get signin actions to work in Teams under any circumstances.

@cwhitten - Who should we ask for help with this issue?

**Comment by v-kydela** [comment]
@rahul-8437008949 - I've done a bit more testing by creating new Azure resources and now I've finally gotten OAuth to work. Let's say I have two bot resources:

- Resource A: Can reproduce the problem (Teams OAuth doesn't work)
- Resource B: Cannot reproduce the problem (Teams OAuth does work)

The bot code doesn't make a difference, so it doesn't matter if the bot is made with Composer or not. The Teams app manifest also doesn't make a difference. It seems like it all comes down to the Azure resource you use. I tried the same bot with the same app manifest and it works with one Azure resource and doesn't work with the other. I'm still unsure what makes the two resources different, but can you try creating a new Bot Channels Registration to see if that fixes your problem?

**Comment by rahul-8437008949** [comment]
Hi @v-kydela .I tried to deploy it using 2 -3 resources ,it didnt work for any. Also i cant rely on this for the app i am building. As in working for one resource and not working for other wont be accepted by my seniors. Can something concrete be worked upon?

**Comment by rahul-8437008949** [comment]
Thanks @v-kydela working for me now.

**Comment by v-kydela** [comment]
That's good to hear, @rahul-8437008949 

Can you tell us what you did to fix the problem?

**Comment by rahul-8437008949** [comment]
It was mistake from my end.I was directly opening teams bot from azure due to which manifest was not getting used.
