### ISSUE TITLE
Can't sign out from my azure account in Bot Composer

### ISSUE THREAD

**Issue by lusk33** [microsoft/BotFramework-Composer#6561]
I tried to deploy a bot to an Azure Account and it failed because of "Insufficient privileges to complete the operation".
So i decided to try on a different account. The problem is that i can't logout from the first account.
When i click sign out in the deploy page, the window closes and i'm still logged in.

![image](https://user-images.githubusercontent.com/68569843/112521225-09369d00-8d7b-11eb-8dd6-e4514b086c09.png)

To replicate it:
Create a bot in BotFramework Composer
Go through the deployment process
Try to sign out the account

Thanks for the support.

**Comment by boydc2014** [comment]
@lusk33 can you share us with the version and platform you are in? 

I'm testing 1.4.0 in Win10, sign out works as expected. @luhan2017 did you see anything like this before?

**Comment by lusk33** [comment]
After some time it automatically logged out, but when I inserted the ARM and graph tokens it happened again.
I'm also using the 1.4.0 in Win10.

**Comment by cwhitten** [comment]
@lusk33 how are you inserting the arm and graph tokens?

**Comment by luhan2017** [comment]
I verified the composer webapp, I can reproduce this issue. The logout button did not work. We should clear arm and graph tokens in cache when user click logout.

**Comment by boydc2014** [comment]
> I verified the composer webapp, I can reproduce this issue. The logout button did not work. We should clear arm and graph tokens in cache when user click logout.

Thanks, so, this is a web app issue, right? I tried electron version and it's working as expected.

**Comment by lauren-mills** [comment]
@luhan2017 - is this resolved? If not, can we get it added to the backlog?

**Comment by luhan2017** [comment]
@GeoffCoxMSFT could you please help follow up on this?
