### ISSUE TITLE
Create Copy for Import Modal

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6564]
The Copy on the Import existing resources modal needs to be determined and created

## Additional context

![image](https://user-images.githubusercontent.com/18688053/112528729-7d207780-8d72-11eb-850f-c0a03f9bbdfb.png)

**Comment by JaskeeratBedi-cmk** [comment]
Updated copy after reviewing with @zxyanliu 

![import existing](https://user-images.githubusercontent.com/67944302/113186742-e2f67e80-920c-11eb-8037-6aeb119f12fe.png)

Learn more link : https://aka.ms/composer-publish-bot#import-existing-azure-resources

**Comment by Dewain27** [comment]
Registration I think is misspelled.

**Comment by JaskeeratBedi-cmk** [comment]
Updated copy/ typos.
