### ISSUE TITLE
Create Copy for Generate Resources Request Modal

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6565]
## Is your feature request related to a problem? Please describe.

The Copy on the Generate Resources Request modal needs to be determined and created

## Additional context

![image](https://user-images.githubusercontent.com/18688053/112542732-ea3c0900-8d82-11eb-9fbf-642d5169fc9b.png)

**Comment by JaskeeratBedi-cmk** [comment]
Updated copy after reviewing with @zxyanliu 

![hand off to admin](https://user-images.githubusercontent.com/67944302/113187339-96f80980-920d-11eb-8296-1aa5fd7c3be0.png)

Learn more: https://aka.ms/composer-publish-bot#handoff-to-admin

**Comment by JaskeeratBedi-cmk** [comment]
Updated copy to add example scenarios.
