### ISSUE TITLE
Once click active language button to switch language, the content in dialog nodes lost

### ISSUE THREAD

**Issue by cosmicshuai** [microsoft/BotFramework-Composer#6569]
Here is a gif of reproduce this bug.
![clickMultiLangLostContent](https://user-images.githubusercontent.com/17074777/112600352-0d7ebb00-8e4c-11eb-900d-c20325b0690c.gif)

**Comment by zhixzhan** [comment]
I think this behavior is by design, cause when add a lg template in one language, composer will not translate or copy to another language, so it looks like empty.

**Comment by cosmicshuai** [comment]
Get it!
