### ISSUE TITLE
adaptive card carousel view with buttons giving object reference error on select

### ISSUE THREAD

**Issue by Samirun** [microsoft/BotFramework-Composer#6584]
we have a scenario where the user selects a particular center from the carousel view, it's giving me an object reference error when I hit submit.

if each one of the carousel adaptive cards has a submit button can we know which card the user has selected from the carousel?

**LG used:** 
https://github.com/microsoft/BotFramework-Composer/issues/3674
[Activity
    Attachments = ${json(centercardjson())} | ${json(centercardjson())}
    AttachmentLayout = carousel}
]

![image](https://user-images.githubusercontent.com/46156330/112785907-b444a080-9072-11eb-9be5-4ca6878e6caf.png)

## Browser

- [ ] Chrome

## OS

- [ ]  Windows

@Danieladu

**Comment by Danieladu** [comment]
1. For first question, could you provide the template content of `centercardjson`? That may help a lot to find out where is the error point.
2. About how to get the cardIndex, you can give a unique id to each card when call back. For example, Suppose your card is an adaptivecard.

 Here is the bot:
[EchoBot-1.zip](https://github.com/microsoft/BotFramework-Composer/files/6219777/EchoBot-1.zip)

Gif screenshot:
![sc](https://user-images.githubusercontent.com/7289268/112797513-149d0780-909e-11eb-8963-ca471ea6b30e.gif)

**Comment by Samirun** [comment]
@Danieladu  can we change the contents of the card dynamically? if so? how to do it? is there any doc awailable?

**Comment by Danieladu** [comment]
Sure. You can concat a card content with template.
For the above example, if you want to make the card body dynamically with given list, try such LG file:
```
# myDataList
- ${["CenterName", "Bob", "PhoneNumber"]}

# TextBlock(text)
- ```{
    "type": "TextBlock",
    "text": "${text}",
    "wrap": true
}```

# adaptivecardjson(index)
- ```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "type": "AdaptiveCard",
    "body": [
        ${join(foreach(myDataList(), text, TextBlock(text)), ',')}
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Select",
            "style": "positive",
            "data": {
              "index": ${index},
              "intent": "SelectItem"
            }
        }
    ]
}```
```

**Comment by Samirun** [comment]
@Danieladu this is not how i wanted. i want the card contents to be changed for each card. card fields should be varied. i could not get it to work

**Comment by Danieladu** [comment]
you mean the cards should rendered with different data? Do it like this screenshot:
![image](https://user-images.githubusercontent.com/7289268/112973492-f8739600-9183-11eb-9a8f-2fd4a9621958.png)

If so, you can check the below LG file:
```

# myDataList
- ${[{"index": 0, "centerName":"name1", "Bob":"bob1", "phoneNumber": "111"}, {"index":1, "centerName":"name2", "Bob":"bob2", "phoneNumber": "222"}]}

# activity
[Activity
   Attachments = ${foreach(myDataList(), item, json(adaptivecardjson(item)))}
    AttachmentLayout = carousel
]


# adaptivecardjson(item)
- ```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "CenterName: ${item.centerName}",
            "wrap": true
        },
        {
            "type": "TextBlock",
            "text": "Bob: ${item.Bob}",
            "wrap": true
        },
        {
            "type": "TextBlock",
            "text": "PhoneNumber: ${item.phoneNumber}",
            "wrap": true
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Select",
            "style": "positive",
            "data": {
              "index": ${item.index},
              "intent": "SelectItem"
            }
        }
    ]
}```
```

the card would be rendered with `myDataList`

**Comment by pavolum** [comment]
Going to close due to inactivity. Feel free to reopen if above comments did not resolve.
