### ISSUE TITLE
Azure provision in webapp is broken

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#6595]
## Describe the bug

main branch start composer webapp

1. add a new publish profile.
2. input arm token and graph token.
3. the provision page is blank.

![image](https://user-images.githubusercontent.com/32191031/112969862-3a9ad880-9180-11eb-815c-c47cbc7e9e75.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
@luhan2017 this is web only?

**Comment by cwhitten** [comment]
@a-b-r-o-w-n FYI in case the tenant selection changes may have caused this

**Comment by benbrown** [comment]
The publishing is also broken in the web client.

![Screen Shot 2021-03-30 at 11 50 16 AM](https://user-images.githubusercontent.com/729873/113026025-3950b800-914e-11eb-80bd-3f22003df523.png)

**Comment by luhan2017** [comment]
@cwhitten @a-b-r-o-w-n , Yes, this is web only, electron works well. That may caused by the tenant switch feature, user don't need to select tenant for the web case, we may just show them the tenant associated with that token.  

![image](https://user-images.githubusercontent.com/32191031/113071498-6d33e800-91f7-11eb-88f5-d8edb7b85b60.png)

**Comment by a-b-r-o-w-n** [comment]
@luhan2017 This is good to know. I have started to serialize the tenant id into the publish profile and will look into getting this from the token as well.

**Comment by hibrenda** [comment]
![image](https://user-images.githubusercontent.com/43408889/113690591-2d409980-96fe-11eb-8e67-613e629357a1.png)
I still hit the arm token issue with latest main run on local host. any step missed ?

**Comment by a-b-r-o-w-n** [comment]
There is a known issue that @GeoffCoxMSFT is working on. This looks related.
