### ISSUE TITLE
Error while Provisioning Bot - Insufficient Privileges

### ISSUE THREAD

**Issue by lusk33** [microsoft/BotFramework-Composer#6596]
I'm trying to provision a bot in a friend's account wich my role is owner.
The provisioning starts but it sends an error:

![image](https://user-images.githubusercontent.com/68569843/112990511-87f55680-913c-11eb-8b4b-b7c6a0289300.png)

The error inside the file:
```
{
  "profileName": "bot",
  "jobId": "7d301da2-e90c-4b83-824f-ec0c11accfc3",
  "projectId": "42887.07721817835",
  "time": "2021-03-30T12:32:10.957Z",
  "log": [
    "Creating Azure resources...",
    "Checking the Existence of the Resource Group ...",
    "Use the Resource Group: teste-temperamento at westus",
    "> c...",
    "App create failed: {\n    \"name\": \"StatusCodeError\",\n    \"statusCode\": 403,\n    \"message\": \"403 - {\\\"error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":\\\"**Insufficient privileges to complete the operation.**\\\",\\\"innerError\\\":{\\\"date\\\":\\\"2021-03-30T12:32:16\\\",\\\"request-id\\\":\\\"fd86ddfa-f294-4413-b616-a34303f96f05\\\",\\\"client-request-id\\\":\\\"fd86ddfa-f294-4413-b616-a34303f96f05\\\"}}}\",\n    \"error\": {\n        \"error\": {\n            \"code\": \"Authorization_RequestDenied\",\n            \"message\": \"Insufficient privileges to complete the operation.\",\n            \"innerError\": {\n                \"date\": \"2021-03-30T12:32:16\",\n                \"request-id\": \"fd86ddfa-f294-4413-b616-a34303f96f05\",\n                \"client-request-id\": \"fd86ddfa-f294-4413-b616-a34303f96f05\"\n            }\n        }\n    },\n    \"options\": {\n        \"body\": {\n            \"displayName\": \"temperamento\"\n        },\n        \"json\": true,\n        \"headers\": {\n            \"Authorization\": \"Bearer 
```

Edit:
I searched the web and found out that most of these problems are caused by the User App Registration being inactive.
It's not my case, it IS ACTIVE.
![image](https://user-images.githubusercontent.com/68569843/112994364-8ded3680-9140-11eb-88d9-2237acd59bd6.png)

## Version
BotFramework Composer 
Release: 1.4.0
SDK runtime packages 4.12.2

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an echo bot
2. Try to publish it on an account wich you are Owner (but not your own account)

## Expected behavior

It will show the error that i mentioned

**Comment by anusharavindrar** [comment]
@lusk33, this looks similar to the one reported in https://github.com/microsoft/BotFramework-Composer/issues/4154. Do you get any additional error on the dev console? Investigating further and will update the thread once I have more info to share.

**Comment by lusk33** [comment]
Hey, sorry for the late response.
As I said, i'm using a friend's account to deploy the bot. I figured it's a problem with the Azure Roles.
As an Owner, i was not able to create an app registration. We had to work around that. He had to create a custom role by following this tutorial:

https://docs.microsoft.com/en-us/azure/active-directory/roles/quickstart-app-registration-limits

**It would be interesting if you guys could show us what permissions the users SHOULD have to create a bot on azure**.

We had to create an AzureAD Premium P2 to be able to solve that problem and i'm still getting a permissioning error as shown below. I don't really think people should create AzureAD P2 for that, it's an expensive feature.

"log": [
    "Creating Azure resources...",
    "Checking the Existence of the Resource Group ...",
    "Use the Resource Group: teste-temperamento at westus",
    "> Creating App Registration ...",
    "Start to add password for App, Id : 4d561dcb-e5d0-440d-b320-b6bc80bd9e38",
    "**Add application password failed**: {\n    \"name\": \"StatusCodeError\",\n    \"statusCode\": 403,\n    \"message\": \"403 - {\\\"error\\\":{\\\"code\\\":\\\"Authorization_RequestDenied\\\",\\\"message\\\":\\\"**Insufficient privileges to complete the operation.**

**Comment by anusharavindrar** [comment]
@lusk33, are you using the composer desktop application or the web-based component?
@hibrenda, any pointers on what permissions the user needs to have if he is using his friend's account to deploy the bot and his friend has created a custom role for him?

**Comment by anusharavindrar** [comment]
@lusk33, do you still need help?
