### ISSUE TITLE
v1.4.0 nightly wrong property reference in memory

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/BotFramework-Composer#6598]
## Describe the bug

In v1.4.0 (nightly, haven't checked the public version yet) if you want to refer to the recognized entities by LUIS, there is the option to insert a property reference from the context menu within the "Send a response" action, but unfortunately this inserts the reference wrong as it adds `turn.recognizedEntities` which does not refer to properties/entities in memory as it should be `turn.recognized.entities` to refer to the entites recognized from LUIS correctly.

## Version

1.4.0-nightly

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Screenshots

![image](https://user-images.githubusercontent.com/29750798/113011899-89457400-917a-11eb-94a5-0a4f9320c511.png)

**Comment by hatpick** [comment]
@cosmicshuai 
https://github.com/microsoft/BotFramework-Composer/blob/d0ce8fee175cce3edefca52102bcc74a2c9cae41/Composer/packages/server/src/services/project.ts#L95

Can you revisit the list of default variables and fix them?

**Comment by cosmicshuai** [comment]
@stephanbisser @hatpick 
I double checked the TurnPath in SDK, https://github.com/microsoft/botbuilder-dotnet/blob/d299138cdc41aa4782bc0918fffdba2ab13d664a/libraries/Microsoft.Bot.Builder.Dialogs/Memory/TurnPath.cs#L53
I think `turn.recognizedEntities` is right.

**Comment by boydc2014** [comment]
> @stephanbisser @hatpick
> I double checked the TurnPath in SDK, https://github.com/microsoft/botbuilder-dotnet/blob/d299138cdc41aa4782bc0918fffdba2ab13d664a/libraries/Microsoft.Bot.Builder.Dialogs/Memory/TurnPath.cs#L53
> I think `turn.recognizedEntities` is right.

Can we confirm this with a real case? At least turn.recognized.entities is the long using format. Maybe turn.recognizedEntities is an alias, or even an unimplemented alias.

**Comment by cosmicshuai** [comment]
After digging the source code, there are some differences between `turn.recognizedEntities` and `turn.recognized.entities` 
Here is an example:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/17074777/113120726-77300800-9244-11eb-9182-fa70ab98a349.png)

1. `turn.recognizedEntities` is an array of EntityInfo,  `turn.recognized.entities` is a JObject. 
     If you want to analyze the entities from recognizer result. It is more easy to do some manipulations over the array of `turn.recognizedEntities`, like `count(turn.recognizedEntities) >= 1`

     If you want to get the exact matched entity from recognizer result, like `personName`, you can use an expression like `turn.recognized.entities.personName[0]`. For this scenario, user can just use an at expression `@personName`. In Composer, the editor supports to suggest all user defined entities after typed `@`. 

I can added `turn.recognized.entities` to the editor.

**Comment by stephanbisser** [comment]
Is this anywhere documented as well as I couldn't find anything in the docs and as the names are quite similar there should be at least documentation to distinguish between them

**Comment by cosmicshuai** [comment]
@stephanbisser 
I found some documents for `TurnPath` and `dialogPath`, which corresponding to `turn.sth` and `dialog.sth`
[TurnPath](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.turnpath?view=botbuilder-dotnet-stable)
[DialogPath](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.dialogpath?view=botbuilder-dotnet-stable)
