### ISSUE TITLE
[3/29 bugbash] App settings not populated when I "open in composer" to an existing bot

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#6602]
From Nick Ericson https://fuselabs.visualstudio.com/BotFramework/_queries/edit/58575/?triage=true

![image](https://user-images.githubusercontent.com/17152540/113048320-41f9bc00-9157-11eb-94f4-9b495cc11e40.png)

Should they be? What if the old bot was already published somewhere - does it overwrite the values or warn that there are already values or ???

## Version
v1.4.0-nightly.228616.da1ac55

**Comment by cwhitten** [comment]
@luhan2017 here is another one to look at.

**Comment by luhan2017** [comment]
That is by design, the appid and password are only used for local start bots. the abs appid and passwords are in the new created publish profile. Are we expecting to also fill in the local appid and passwords? That is only needed when local bot call a remote skill. @Andrea-Orimoto @NickEricson

**Comment by mewa1024** [comment]
(@vivekkshankar fyi for the remote skills flow)

**Comment by luhan2017** [comment]
There is a Retrieve App ID button to retrieve the appid and password from a publish profile. 
![image](https://user-images.githubusercontent.com/32191031/117930527-b0be5d80-b330-11eb-8720-73343183267f.png)
