### ISSUE TITLE
[3/29 bugbash] Renaming local folder then back again breaks connection

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#6604]
From Jordan Berger https://fuselabs.visualstudio.com/BotFramework/_queries/edit/58577/?triage=true

1. Open in Composer
2. Create a bot from scratch (EmptyBot-0)
3. Close Composer
4. Open in Composer - works
5. Rename the local bot project folder (EmptyBot-0 -> EmptyBot-1)
6. Open in Composer - doesn't work (expected)
7. Rename folder back to original (EmptyBot-1 -> EmptyBot-0)
8. Open in Composer - doesn't work (unexpected)

In these repro steps, I would expect that renaming the folder back to the original would retain the connection between Azure and Composer, but it looks like once the bot is opened with the wrong folder name, the connection breaks. This would be an issue if for example the user had to reimage their PC, and I don't have the option to connect it to an existing bot folder (different bug?)

## Version
v1.4.0-nightly.228616.da1ac55

**Comment by alanlong9278** [comment]
I can not reproduce the bug. Like the gif shows, it works well in v1.4.0-nightly.228616.da1ac55. @Andrea-Orimoto 
![renam](https://user-images.githubusercontent.com/5860999/113690433-f8344700-96fd-11eb-8ae5-c869a2758dbe.gif)

**Comment by boydc2014** [comment]
Close due to unable to repro
