### ISSUE TITLE
[3/29 bugbash] Unclear what template "name of your services" should be

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#6606]
from nick ericson https://fuselabs.visualstudio.com/BotFramework/_queries/edit/58586/?triage=true

Is this a predicate that is added in from of some other string(s)?

![image](https://user-images.githubusercontent.com/17152540/113049407-7457e900-9158-11eb-8976-10a777ec5078.png)

What resources are created?

## Version
v1.4.0-nightly.228616.da1ac55

**Comment by Andrea-Orimoto** [comment]
This is especially true when coming from ABS and completing an incomplete provisioning profile. It is not clear that the dialog is asking for the name of the app service.

**Comment by cwhitten** [comment]
@JaskeeratBedi-cmk FYI

Is this the intended placeholder text?

**Comment by JaskeeratBedi-cmk** [comment]
hmm... I think this is a bug, there is nothing specified as a placeholder, however tooltip should say this information. In essence this is the name we will assign to all the new resources that will get created in the publishing profile.

![Screen Shot 2021-04-01 at 4 42 38 PM](https://user-images.githubusercontent.com/67944302/113364831-5e3d5a80-9309-11eb-9749-6b281531ec2e.png)

**Comment by JaskeeratBedi-cmk** [comment]
Hmm.. the placeholder copy does not look right. This is what was proposed in the design.

![Screen Shot 2021-04-01 at 4 44 43 PM](https://user-images.githubusercontent.com/67944302/113364980-c2f8b500-9309-11eb-9add-07122f2e4db1.png)

**Comment by JaskeeratBedi-cmk** [comment]
The UI for this modal has been updated to:

![MicrosoftTeams-image (49)](https://user-images.githubusercontent.com/67944302/115920537-31272800-a42f-11eb-9f24-51eec89cf641.png)
