### ISSUE TITLE
[3/29 bugbash] Publishing a bot with App Insights doesn't hook up app insights

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#6607]
From nick ericson https://fuselabs.visualstudio.com/BotFramework/_queries/edit/58592/?triage=true

1. Create bot
2. Open in composer, edit publish profile
3. See app insights... add it
4. (notice app insights is not listed in the Project Settings... maybe those are "local settings" vs "published bot settings")
5. Go to Azure
6. (notice the settings is not updated)

![image](https://user-images.githubusercontent.com/17152540/113049746-dc0e3400-9158-11eb-885d-a720b3fd44b0.png)

## Version
v1.4.0-nightly.228616.da1ac55

**Comment by cwhitten** [comment]
@NickEricson were you able to verify if app insights were collected and working as intended? we may need to hit and endpoint in the service to populate this field. We don't know of anything functionally broken for app insights.

**Comment by NickEricson** [comment]
Without those values populated app insights won't be collected.
