### ISSUE TITLE
[3/29 bugbash] [Composer publishing profile] Required to have at least one optional resource

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#6609]
from Mike Bennet https://fuselabs.visualstudio.com/BotFramework/_queries/edit/58609/?triage=true

When trying to edit my publishing profile, I can't proceed past this step without adding a supposedly optional resource. Any one will do, but one is required.
![image](https://user-images.githubusercontent.com/17152540/113050126-5a6ad600-9159-11eb-89a4-f0e68165d56b.png)

## Version
v1.4.0-nightly.228616.da1ac55

**Comment by cwhitten** [comment]
This is by design and intended, but the UX may be unclear. The required resources have already been provisioned, so when editing a publishing profile to add more renders the list of optional resources.
