### ISSUE TITLE
[3/29 bugbash] Is the bot warmed up when published?

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#6615]
from nick ericson https://fuselabs.visualstudio.com/BotFramework/_queries/edit/58596/?triage=true

It seems to take a while to respond to the 1st message. Is the bot warmed after deploy?

If not it would be nice to so JIT, etc are done.

## Version
v1.4.0-nightly.228616.da1ac55

**Comment by cwhitten** [comment]
@garypretty FYI - there are a few scenarios where Composer publishes the bot successfully and it all looks good, but the bot is not ready to accept messages.
