### ISSUE TITLE
[3/29 bugbash] Not able to open an Azure Bot in Composer

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#6616]
from melanie https://fuselabs.visualstudio.com/BotFramework/_queries/edit/58635/?triage=true

note: the ADO bug contains videos! please refer to those above.

Updated Composer to 1.4.0-nightly.228616.da1ac55 and checked on New Creation Experience. 
Visit this link https://ms.portal.azure.com/?microsoft_azure_marketplace_ItemHideKey=BotWithComposer&Microsoft_Azure_BotService=friendName&Microsoft_Azure_BotService_deprecationWarnings=true#create/hub 
Search for "bot" and select "Azure Bot (Preview)" and created bot.
Once the resource was created, clicked on "Open in Composer".
(I tried this a couple times to see if it made a difference whether Composer was already open.)
Composer opens, and lands on the home page. The "Open Azure Bot Resource" modal dialog does not appear.

(Steps 4 and 5 are in movie clip 1.)

I open an existing bot in Composer.
Go back to Azure, and click "Open in Composer" again.
The "Open in Azure Bot Resource" modal appears.
Select create a new bot, and select the blank bot template, and name the bot "empty_1".
Get what looks like an error message.
Got back to Azure, click "Open in Composer again.
Composer opens to "empty_1".
Go to Publish page to see if there is a publishing profile, and there isn't any.

(Steps 6-13 are in movie clip 2.)

Add publish profile (signs me into to Azure.
Provisioning fails.

(Steps 14 and 15 are in movie clip 3.)

## Version
v1.4.0-nightly.228616.da1ac55

**Comment by luhan2017** [comment]
@Andrea-Orimoto @mewa1024 where can I find the video?

**Comment by luhan2017** [comment]
@mewa1024 could you please help share your data.json file with me? It is most likely located here: C:\Users\{username}\AppData\Roaming\BotFrameworkComposer

**Comment by mewa1024** [comment]
Surely. It has a modified date of yesterday though, so I don't know if it's been changed since the bug bash.
[data.json.zip](https://github.com/microsoft/BotFramework-Composer/files/6245237/data.json.zip)

**Comment by mewa1024** [comment]
Oh, and the movie clips are attached to the original issue:
[https://fuselabs.visualstudio.com/BotFramework/_workitems/edit/58635/?triage=true](url)

**Comment by luhan2017** [comment]
@mewa1024 
- I can't see the first video.
![image](https://user-images.githubusercontent.com/32191031/113424416-b310cc00-9402-11eb-9ff7-6f806c94df8b.png)

The other two are not specific to abs scenario
- The second video shows the dotnet build empty_1.csproj error. @benbrown  any ideas? 
- The third video shows add app password error during the provision process, is this error consistently reproduce-able?

**Comment by mewa1024** [comment]
Hi @luhan2017 the video just shows that I click on the "Open in Composer" button and then Composer opens and does nothing else. 

https://user-images.githubusercontent.com/39317542/113458883-acfdf980-93c8-11eb-9841-4da6603ecc1e.mov

for the 3rd video, it was consistently reproduce-able for me during the bug bash--I was not able to get past the provision failure and couldn't complete the other tasks in the bug bash. I have not tried it recently.

**Comment by luhan2017** [comment]
I can't reproduce this issue and I asked @cosmicshuai and @zhixzhan's help to test on Mac. We found that on Mac, if you didn't open Composer before click button "open in Composer" it consistently not works. We found that in the code logic, it only handles windows, is this expected not work for Mac? @tonyanziano , could you please help take a look on this? 

![image](https://user-images.githubusercontent.com/32191031/113673572-c0bc9f00-96eb-11eb-90b2-05b2f1f899f4.png)

**Comment by tonyanziano** [comment]
@luhan2017 My understanding is that Mac and Windows handle protocol URLs in different ways. In Windows, this URL is forwarded as an argument to the main process during startup, and on Mac, this is handled in the [`open-url`](https://www.electronjs.org/docs/api/app#event-open-url-macos) event handler.

Unfortunately I cannot test this flow on Mac because I do not own one, so my ability to debug this is limited.

Maybe I can work with @srinaath or @a-b-r-o-w-n on this.

**Comment by a-b-r-o-w-n** [comment]
@luhan2017 I can confirm that deep links don't seem to work when composer is not already open. It would be worth consolidating the deeplink logic into a single unit that handles both windows and mac.
