### ISSUE TITLE
[3/29 bugbash] Add a link back to the Azure portal somewhere

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#6617]
from nick ericson https://fuselabs.visualstudio.com/BotFramework/_workitems/edit/58595/?triage=true

You come from azure, get to composer, then I publish... but I want to configure channels, check online webchat, see if the app restarted, check logging, etc. Would be nice to have a link back.

**Comment by cwhitten** [comment]
The PVA Publishing extension does this. We should do the same for Azure publishing!
