### ISSUE TITLE
Package Manager default feeds

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#6619]
I need to be able to restore the default package feeds in Composer if I edit them. Currently, the correct URLs to include for NuGet/npm are obscure.

Also, if you delete the NuGet feed currently, Composer displays an obscure error. It should:

- remember the last feed I selected, and display that first
- If the feed it is trying to load doesn't exist, load the first valid feed in the list
- If no feeds exist (they have all been deleted) display a CTA to click on the Edit feeds button

**Comment by carlosscastro** [comment]
Likely or partially getting fixed here: https://github.com/microsoft/BotFramework-Composer/pull/6579
