### ISSUE TITLE
Update copy of "Add resource modal"

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#6625]
Resource description within Add resource modal is long and needs better emphasis on the value of resource for the bot.

![Screen Shot 2021-03-31 at 10 46 37 AM](https://user-images.githubusercontent.com/67944302/113188259-ab88d180-920e-11eb-8dd8-60681f221215.png)

**Comment by mareekuh** [comment]
Captured in xls. - will get to as soon as possible 
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea
