### ISSUE TITLE
[3/29 bug bash] Publishing profile error not clear/progress message suggestion

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#6627]
From Jordan Berger https://fuselabs.visualstudio.com/BotFramework/_workitems/edit/58566/?triage=true
(6 more identical bugs filed for this, see the linked items in the bug above if needed)

Repro steps:

1. Create a new bot from "Open with composer"
2. Immediately try to publish it

It wasn't clear to me that I had to provision a web app within my publishing profile when first trying to publish my bot. The error shown says "Required field `name` or `hostname` is missing from publishing profile", but if I go to my publishing profile, the name field is filled in. The "Publishing 1 bots" notification also just stays active instead of going away; I had to go into the Publish tab to see the error. I think it could be clearer to state that the web app is missing and reset the "Publishing" notification to show an error. The messages in the publishing tab (Build succeeded, uploading zip file, etc.) could be displayed on the ongoing notification to better show progress.

![image](https://user-images.githubusercontent.com/17152540/113205067-b64d6180-9222-11eb-87a4-2c2c1835c707.png)

![image](https://user-images.githubusercontent.com/17152540/113205083-ba797f00-9222-11eb-8acf-b038aefbbe21.png)

**Comment by Dewain27** [comment]
@GeoffCoxMSFT spoke with Darren this morning and we want to not show the issue as an Error with a red X like below.  We think this should be more of a informational item that is more like an informational item telling you that you haven't completed your publishing profile setup.

![image](https://user-images.githubusercontent.com/18688053/113303689-f403c600-92c6-11eb-90ea-229a9b180e42.png)

I think it needs to be more like:
![image](https://user-images.githubusercontent.com/18688053/113304412-a0de4300-92c7-11eb-8135-b7c4004ca255.png)
