### ISSUE TITLE
Ensure Creation / Publishing Telemetry is being captured

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6635]
## Is your feature request related to a problem? Please describe.

Ensure that Creation / Publishing Telemetry is being captured properly.

**Comment by garypretty** [comment]
Here is a set of events I think we should capture for the Get LUIS Keys / Get QnA Keys.  I am suggesting generic events that allow us to capture the resource type on the properties, in order for this to scale to include other resource types in the future, such as Application Insights.

Event: SettingsGetKeysExistingResourceSelected
Fires: When a user chooses an existing resource and clicks 'Next'
Properties: SubscriptionId, ResourceType (LUIS / QnA)

Event: SettingsGetKeysCreateNewResourceStarted
Fires: When a user chooses to create a new resource, has populated resource group, region and resource name and clicks 'Next'
Properties: SubscriptionId, CreateNewResourceGroup (true / false), Region, ResourceType (LUIS / QnA)

![image](https://user-images.githubusercontent.com/3900649/114171292-fc45ac00-992b-11eb-95ea-3bfeec7f0084.png)

Event: SettingsGetKeysCreateNewResourceCompleted
Fires: When resource creation has completed.
Properties: SubscriptionId, CreateNewResourceGroup (true / false), Region, ResourceType (LUIS / QnA)

Event: SettingsGetKeysResourceRequestSelected
Fires: When a user chooses to create a resource request and clicks 'Next'
Properties: SubscriptionId, ResourceType (LUIS / QnA)
