### ISSUE TITLE
Slack events cause the bot to try to respond to its own messages

### ISSUE THREAD

**Issue by martinlarosa** [microsoft/BotFramework-Composer#6643]
## Describe the bug

The slack api will also sent requests to the bot for the messages that the bot is sending. That's well known and it's on purpose.  The problem is that since the composer runtime is calling the dialog manager from the OnTurnAsync, all those events get to the bot and it will start replying to them as if the messages were coming from the user.

Should we prevent this by setting some event handling specific for slack in the composer bot or should these events be discarded at the adapter level?

## Version

1.4.0

## To Reproduce
Just run a composer bot using the slack-adapter and talk to the bot.

## Expected behavior

Only answer the users messages

**Comment by cwhitten** [comment]
We've got some ideas on how to improve this, but it will require some changes across the stack. @carlosscastro & @EricDahlvang I'll assign to you for now. 

Fundamentally, configured adapters need to the ability to drive the dialog system behavior. But this is something not supported today.

**Comment by martinlarosa** [comment]
What would you suggest is a good workaround for now?
I moved the execution of the composer dialog to OnActivityMessageAsync but that prevents me from greeting new users in Teams and Web.
Another option I used was leaving it in OnTurnAsync and checking for slack channelId and then if the From.Id is the same as recipient then I would ignore it. 

Both involve changing the runtime so not helping anyone that wants to use the default runtime. I'd go with option 2 if it is not solvable in the composer UI.

**Comment by martinlarosa** [comment]
@cwhitten can you elaborate a bit more on this? 

>  configured adapters need to the ability to drive the dialog system behavior.

**Comment by benbrown** [comment]
@martinlarosa I would suggest you introduce a middleware that tests if the incoming message has a subtype of 'bot_message' or the 'bot_id' field is present, and if so, ignore it. This will tell your bot to ignore any message from any bot.

Alternatively, you can compare the incoming user against the bot's own user ID - however, this requires you to go fetch the bot's user id using one of Slack's APIs, or store it when your bot user is first created.

**Comment by tsuwandy** [comment]
@martinlarosa, did you have a chance to try out @benbrown's suggestion?

**Comment by martinlarosa** [comment]
I don't have the time to test that right now. I went with my  option two since I need to handle some events outside of composer, at least with the current version.
So I'm triggering the composer dialog from `OnMessageActivityAsync`
then in `OnConversationUpdateActivityAsync` I'm triggering it only if it's not from slack. 

Not elegant and probably not a definitive solution, but since I don't need to handle other conversation updates for slack for now, it works. 

With current work priorities I'll probably will wait till the next version of composer comes out and see what new options brings along.
