### ISSUE TITLE
Publishing profile Subscription Dropdown not correct in multiple ways

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#6646]
The subscription dropdown just shows one subscription out of multiple available to the logged in account. Furthermore the one it does show is not the default one and in the end it does create the resources with the default subscription and not the one it only showed and was selected.

Small update, it only created the app registration in the default tenant and the rest in the selected tenant

![image](https://user-images.githubusercontent.com/49873947/113300497-43b1b400-92fe-11eb-8cb9-df8c2370e7dd.png)

**Comment by cwhitten** [comment]
Hi @cxbuilders - you're using 1.4.0 right?

When you say default subscription, could you mean the default _tenant_? You currently cannot select a tenant when creating a publishing profile, but this will be possible in our next release.

> Small update, it only created the app registration in the default tenant and the rest in the selected tenant

Can you expand on this a bit? What are the tenant and/or subscription mismatches that you are seeing?

**Comment by cxbuilders** [comment]
Hey Chris,

for this specific account I have two different subscriptions in two different tenants, something like;

TenantA -> SubscriptionA
TenantB -> SubscriptionB

Yesterday it only showed SubscriptionA in the dropdown, which was not the one I actually wanted but I used that one. Then it went on and created the App Registration in TenantB and the rest of the resources in TenantA

**Comment by lauren-mills** [comment]
@cwhitten - can you comment on when this feature will be supported?

**Comment by dmvtech** [comment]
I'm using the nightly build (where Create new selection is separate from tenant/subscription selecton).

I am able to see more than my default, and able to select others. 
![image](https://user-images.githubusercontent.com/43397658/114788217-ea05ac80-9d35-11eb-8a93-c386890cb199.png)

This is only for one tenant though with one account. As that is all that is available until I sign out and sign in as other user (into other tenant). I'll try and see if I can add this user to another subscription to see if I can see any similar behavior with this build. 
![image](https://user-images.githubusercontent.com/43397658/114788389-36e98300-9d36-11eb-9ef4-26488f5cd94e.png)

**Comment by tsuwandy** [comment]
@cwhitten, is this feature supported now (different subscriptions in different tenants)?

**Comment by dmvtech** [comment]
@cxbuilders The expereince in `2.0.0` is revamped. You have the option to select both Directory (tenant) and Subscription.
![image](https://user-images.githubusercontent.com/43397658/119550005-b1052280-bd4c-11eb-8498-5e7ac874739e.png)

Can you test with 2.0 and make sure you no longer have the same problem/experience as before?

**Comment by dmvtech** [comment]
Closing as no longer a possible issue in 2.0
