### ISSUE TITLE
Text is hard to read when creating a new bot

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6663]
## Describe the bug

When creating a new bot the post selecting a template, you have a series of informational items that are gone through, however the text is really hard to read on top of the text of the existing screen.  See screenshot example below:

![image](https://user-images.githubusercontent.com/18688053/113446131-cc8f2500-93bc-11eb-9d58-3563bd6fbe4a.png)

## Version

Version:  1.4.0-nightly.230410.31d4ca5
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior

Text on screen should be easily readable.  I would expect this to be in a box without transparent background to ensure that it is easily readable.

**Comment by benbrown** [comment]
We should put the spinner and text inside a modal at the very least -- for example, similar to the package manager installing progress indicator.
