### ISSUE TITLE
fetching qnaKnowledge base answer using qnaId in composer

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-Composer#6670]
Hi,

We know that for each QnA question and answer, there's an ID associated. In postman using below steps I am getting the answer from knowledgebase.
![image](https://user-images.githubusercontent.com/36945600/113469725-9362bd80-946d-11eb-8e00-09923af9ab3e.png)
![image](https://user-images.githubusercontent.com/36945600/113469802-2ef42e00-946e-11eb-8849-aedfd8eb5ddc.png)

The same I want to achieve in composer could you please suggest the steps on achieving above it will be very helpful .
By typing the qid on chat window I want the answer corresponding to that Qid in response. 

![image](https://user-images.githubusercontent.com/36945600/113470433-441f8b80-9473-11eb-8760-0babaa7e0779.png)

**Comment by dmvtech** [comment]
Hi @madbeher

Sorry if I'm not following what you're asking 100%, but if I think I understand correctly; you could do this by using using the HTTP request action to post to the QnA service with a body of:
```
{
    "qnaId": "${Qna}"
}
```

Then parse the response for the answer.

**Comment by dmvtech** [comment]
Hi @madbeher I'm going to close this as it seems this has been answered. If not, or I have misunderstood the requirement/problem, please let me know and I will reopen.

**Comment by dmvtech** [comment]
Updating this to point to the answer: 
https://stackoverflow.com/questions/67118890/http-post-request-in-microsoft-bot-composer

Sorry that I missed it earlier, but `$Qna` is not a valid memory scope. You should use `dialog.Qna` or something similar.
