### ISSUE TITLE
Composer Version in appsettings.json

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/BotFramework-Composer#6671]
In order for a pipeline to retrieve the correct Composer Runtime version we would need the Composer Version somewhere exposed that can be used to get the correct runtime version from this github project. Currently there seems to be no way to get this info so only the latest can be retrieved causing the danger of having a mismatch.

**Comment by benbrown** [comment]
@cxbuilders in the next release of Composer, the way the runtime is managed will be very different.  Each project will include the base scaffolding, and the core functionality of the runtime will be explicitly versioned as a dependency.
