### ISSUE TITLE
Skills documentation updates

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6675]
## Describe the bug
The docs we have for skills have a couple of things I think we need to modify.  

First off, it would be good to have Publishing a skill be under the "Publish" top-level documentation topic tree.  the Publish topic just links to general azure publishing.  which is fine, however skills publishing has additional requirements, and we should have another article in the publish node to address that.

Where do have skills publishing document, we call is "export a skill."  We don't 'export' anything really.  What happens is actually a 'publish' activity.  So we should clean up this language as it's confusing and a bit misleading.

## Additional context
https://docs.microsoft.com/en-us/composer/how-to-export-a-skill

<img width="350" alt="Screen Shot 2021-04-04 at 1 25 43 PM" src="https://user-images.githubusercontent.com/733559/113520642-4d7b2780-9549-11eb-9307-cc68982cc614.png">

**Comment by zxyanliu** [comment]
Hi, @sgellock Thanks for your valuable feedback! Here is a rough proposal and let me know if I understand your request correctly:

* Adding a node (_Publish a skill to Azure_) in the publish section of the TOC and documenting the publish flow specific to skills (publish, generate skills manifest, republish).

  **Publish** 
  - Publish a bot to Azure
  - _Publish a skill to Azure_

* Fixing both the title and TOC entry of "export a skill" to "create a skill" to avoid any possible confusion. 

   **Skill** 
  - Create a skill (create a local skill, publish a skill pointing to the "publish a skill" topic)
  - Connect to a remote skill

Thanks again for your feedback. We appreciate it.

**Comment by sgellock** [comment]
@zxyanliu your proposal is perfect.  thank you.  that captures what I was asking for.

**Comment by zxyanliu** [comment]
FYI. The docs have been updated as proposed and merged to master. 
The content will go live soon. Closing this issue for now.
Again, thanks for your valuable feedback! We appreciate it!
