### ISSUE TITLE
Creation: Bot's default name should pass validation on instantiation

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/BotFramework-Composer#6681]
## Describe the bug

When creating a bot using the old experience, users would be provided a default name ("EmptyBot-0") that allowed them to click through and instantiate the project without making any changes. Using the new creation experience with the adaptive runtime, the default name appears to come from the generator ("@microsoft/generator_bot-empty") but it is invalid and an error is highlighted right away.

I believe we should do a couple of things:
1. Provide a friendly name for each of the template generators that won't break validation OOB. Remove the generator reference as it is irrelevant to users.
2. Reintroduce the autoincremented names that the previous experience had so it doesn't conflict with other bots of the same name

### Old experience
![image](https://user-images.githubusercontent.com/43043272/113598872-a18e1680-95f2-11eb-9c02-696dbc7c53c1.png)

### New experience
![image](https://user-images.githubusercontent.com/43043272/113598537-1e6cc080-95f2-11eb-94c6-a9fc12083d19.png)

## Version
v1.4.0-nightly.230307.ec9040

## Browser
- [x] Electron distribution

## OS
- [x] Windows

## To Reproduce
1. Create a new bot

**Comment by pavolum** [comment]
This was resolved in a past PR so going to close this issue out.
