### ISSUE TITLE
Composer pins tenant id during publish profile creation; keeps alt account from publishing

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#6688]
## Describe the bug

Currently, during publish profile creation, composer caches tenant id after successful login.  Trying then to publish to an account in a different tenant fails as composer tries to use the cached first tenantid.

## Version

Version:  1.4.0-nightly.230964.e5e5020
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1) Create a bot in composer
2) Try to create a publish profile with MSIT creds and fail before completion
3) Try to create a publish profile with non MSIT creds (in my case, personal tenant)

Experience: cannot create publish profile as new ID is not in the tenant cached in step 2. No way also to log out of tenant in step 2 as you're not "logged in".

## Expected behavior

I can switch accounts freely, or explicitly "sign out" to clear cached tenant info.

## Screenshots

![image](https://user-images.githubusercontent.com/5997512/113621092-10c63380-9610-11eb-96f3-6ac0aef24ce5.png)

**Comment by hibrenda** [comment]
hit https://github.com/microsoft/BotFramework-Composer/issues/6707 during the verification.
