### ISSUE TITLE
Bot that doesn't depend on QnA is getting a warning that QnAKey is missing (composer nightly)

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#6690]
## Describe the bug

I've created a bot that doesn't depend on QnA or LUIS, however validation says that the bot has an error due to missing QnAKey in appsettings.json

## Version

Version:  1.4.0-nightly.230964.e5e5020
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an echo bot 
2. Run and save the bot
3. Attempt to publish it without LUIS/QnA (uncheck the boxes during publish)
4. Reload bot later: get error in notifications and in debug pane:

## Expected behavior

QnA/LUIS should not be required to create a bot.

## Screenshots

![image](https://user-images.githubusercontent.com/5997512/113622113-60592f00-9611-11eb-9d54-59d51ebbee0a.png)

**Comment by boydc2014** [comment]
@liweitian  can you help take a look at this?

**Comment by hibrenda** [comment]
I could not repro the issue with latest electron nightly. 
As I hit creation failure for latest nightly, so I have to open an existing bot.
- open an empty bot (en-us) only (only greeting in welcome)
- start bot (run locally) and test in integrated webchat (worked as expected)
- provision and publish to abs (uncheck luis/qna, worked as expected)
- reload the bot (no error display in debug pane)
![image](https://user-images.githubusercontent.com/43408889/113672208-ff515a00-96e9-11eb-921e-9fdad63be319.png)
