### ISSUE TITLE
Typing indicator before text messages 

### ISSUE THREAD

**Issue by gabrielguarisa** [microsoft/BotFramework-Composer#6701]
Is there a better way to indicate that the bot is typing without having to place these activities before each message? 

![Captura de Tela (104)](https://user-images.githubusercontent.com/11513141/113638207-b3040c80-964c-11eb-9bc6-754e9da625c0.png)

I am aware that this issue has already been raised in #4471 and it was partially answered [here](https://stackoverflow.com/questions/61602436/simulating-typing-activity-bot-framework-composer) and in #4509.

I did not find a suitable solution in which it is not necessary to repeat the two activities (typing and delay) before each text message in the links that I mentioned.

Additional information: ShowTypingMiddleware is already set to true and I'm using the direct line as my main channel.

**Comment by dmvtech** [comment]
Hi @gabrielguarisa 

Please help me understand your requirement/need. Are you just wanting the bot to send typing activities whenever it is 'thinking'?  Are you wanting to show the typing activity with less of a wait (less time between when bot receives message and sends typing activity)? 

The typing middleware should send typing activities if the activity on the bot side takes longer than half a second, and will keep sending them every 2 seconds until an 'actual' response is sent from the bot. You can see more info [here](https://github.com/microsoft/botbuilder-dotnet/blob/03110e331220592f142bee4d58bdbb395051403e/libraries/Microsoft.Bot.Builder/ShowTypingMiddleware.cs#L31).

Sending a typing activity **explicitly** should be used for specific scenarios. Either where you don't want typing middleware enabled across-the-board, or when you need it for a very certain situation(s). 

- Are you sending the delay to trigger/test for a delay type scenario? 
- If you want to decrease the wait between bot receiving the message and sending typing activity; you can customize your runtime, override the `ShowTypingMiddleware` class and specify something less than 500ms.

**Comment by gabrielguarisa** [comment]
Hello @dmvtech. Thanks for the reply.

From what you told me, I believe there are two different questions then:
1. Typing activity is not occurring on the direct line channel (and in azure web chat) if I do not explicitly place the typing activity on the composer (as shown in the image above).
2. Is there a way to put a delay on all messages, without explicitly sending the delay activity?

**Comment by dmvtech** [comment]
> Typing activity is not occurring on the direct line channel (and in azure web chat) if I do not explicitly place the typing activity on the composer (as shown in the image above).

I am assuming this is because the bot is responsive enough (no real delay) so that it doesn't trigger a typing activity (response is happening less than half a second).

> Is there a way to put a delay on all messages, without explicitly sending the delay activity?

You can [extract the runtime](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action?tabs=csharp#export-the-bot-runtime) and then modify it.

**Comment by gabrielguarisa** [comment]
I had not thought about modifying the runtime. Thanks for the suggestion and attention. I'm closing this issue.

**Comment by owenpww** [comment]
Hello @dmvtech how exactly do you modify the runtime? I tried creating a new project with a bot component that's supposed to send a delay activity on every message activity the bot receives. I then created a reference in my bot project to this new bot component and included it in the `appsettings.json` in the `components` array It seems to work well locally but when I deploy to Azure it keeps returning a bot encountered an error whenever it tries to webchat/join causing the entire conversation to crash.
