### ISSUE TITLE
Cannot create a bot after disabling app insights during publish

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#6702]
## Describe the bug

When I create a publish profile, I'm given the option of disabling several resources.  If I disable App Insights, the logic seems to try to do something with app insights anyway and then fails.

## Version

Version:  1.4.0-nightly.230964.e5e5020
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create bot in composer
2. Create new publish profile for bot
3. Uncheck all the optional services
4. Proceed with publish - get error

## Expected behavior

Publish to be successful with optional resources unchecked.

## Screenshots

![image](https://user-images.githubusercontent.com/5997512/113639134-580eed00-962d-11eb-9265-af385ccb4760.png)

**Comment by hibrenda** [comment]
not repro this issue with latest electron nightly.
