### ISSUE TITLE
can not create bot with latest electron nightly

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#6704]
Can not create a bot with latest electron nightly .(new adaptive runtime)

Try to create a new blank bot but hit following issue. 

![image](https://user-images.githubusercontent.com/43408889/113673484-a08ce000-96eb-11eb-9be2-b77d1cfe3fd0.png)

**Comment by hatpick** [comment]
Fixed by https://github.com/microsoft/BotFramework-Composer/pull/6714
