### ISSUE TITLE
Fail to create bot

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#6705]
Latest electron nightly can't create a blank bot

![image](https://user-images.githubusercontent.com/3829387/113673994-3de81400-96ec-11eb-8091-41a8af198889.png)

Repro:
- New
- Select blank bot
- Create
- See error, "dotnet build" fails

**Comment by LiorArmiev** [comment]
same problem with the new version of composer:

> Command failed: dotnet build empty.csproj

**Comment by rvinothrajendran** [comment]
updated new build ...still same problem

![image](https://user-images.githubusercontent.com/16264167/114191674-f57b6100-994c-11eb-8ff6-43d53f673e98.png)

**Comment by rvinothrajendran** [comment]
@cwhitten steps to reproduce

Select the blank bot -> create a project with default name -> its works

**Select the blank bot -> change default project name -> ex : 01Message** 
![image](https://user-images.githubusercontent.com/16264167/114194879-388b0380-9950-11eb-913f-af3ea92ecbb7.png)
