### ISSUE TITLE
Errors still showing vs Teaching bubble popping up with teaching bubble

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6709]
## Describe the bug

When you add LUIS and/or QNA maker to your bot project, you get an error still for not having the resources configured/provisioned.  This was supposed to be replaced with the Next Steps being highlighted with a teaching bubble and the errors removed.

![image](https://user-images.githubusercontent.com/18688053/113714066-9e0b9580-96ad-11eb-8702-c79f421caf13.png)

## Version

Version:  1.4.0-nightly.231404.da58480
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create Empty Bot
2. Add QnA Maker and/or LUIS to your Bot Project
3. Errors pop up with icons all over the screen vs the Next Steps being shown with teaching bubble to say you need to do the actions.
![image](https://user-images.githubusercontent.com/18688053/113714582-29852680-96ae-11eb-8243-6f5cd21c3286.png)

## Expected behavior

Next Steps should be exposed and teaching bubble should be provided to explain that you need to provision or configure the resources.

**Comment by benbrown** [comment]
This will now navigate the user to the appropriate place in the settings where they can resolve the problem.
