### ISSUE TITLE
Composer update to v1.4

### ISSUE THREAD

**Issue by ctharmon722** [microsoft/BotFramework-Composer#6713]
Since updating to version 1.4, I can not start my bot. Here is the error I am getting.

Start bot failed

Message:
spawn C:\WINDOWS\system32\cmd.exe ENOENT
Command:
dotnet user-secrets init --project azurewebapp
Stack Trace:
Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Output:
Errno:
ENOENT
Code:
ENOENT
Syscall:
spawn C:\WINDOWS\system32\cmd.exe
Path:
C:\WINDOWS\system32\cmd.exe
Spawnargs:
/d/s/c"dotnet user-secrets init --project azurewebapp"

**Comment by cwhitten** [comment]
@ctharmon722 you are using a custom ejected runtime, correct?

assuming so, you'll need to either update to the Early adopters feed or make a small change in your runtime settings.

Runtime code location needs to change from "runtime" to "../runtime".

![image003](https://user-images.githubusercontent.com/1156704/113772736-f35d9c00-96d9-11eb-93b4-4436009c50af.png)

**Comment by cwhitten** [comment]
I'll preemptively close this, but please do let me know if this does not solve the issue for you.

**Comment by ctharmon722** [comment]
Can you give me more feedback on the early adopter feed?

**Comment by cwhitten** [comment]
Sure. If you navigate to the Settings page you can toggle it and then from the Help menu select "Check for updates". This will put you on the daily build of the application, so it is unstable and has features in development.

Taking the approach of updating your runtime code location may be a more stable choice.

<img width="1050" alt="Screen Shot 2021-04-06 at 1 18 50 PM" src="https://user-images.githubusercontent.com/1156704/113773311-b80f9d00-96da-11eb-9d2a-9826ec48929b.png">

**Comment by ctharmon722** [comment]
Thanks. that is really helpful. Just an FYI, changing the runtime code worked perfectly. And based on that advice, I will stick with that
