### ISSUE TITLE
If the Creation process fails, we're not cleaning up properly

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6726]
## Describe the bug
I'm using a nightly build.  so what's nice about this is that there is some fragility in the Creation flow.  As a result of that, failure cases during creation are easier to produce than when we'll be working against release candidates and GA release builds.

When the creation process fails, we don't clean up the new folder.  So, when you try and create the bot again, the name is taken, though the bot was never actually created during the first attempt.

## Version
Version:  1.4.0-nightly.231667.d104286
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Using the above nightly, launch composer.  This nightly has the new creation flow enabled by default.
2. From the Composer Home Screen, click on '+' to create a new bot
3. Select a template from the list of templates.  I chose 'Basic Conversational Bot'
4. Click 'Next' to display the "Create a bot project" modal.
5. Name you bot with a legal name.  e.g. basic_x
6. Wait for the NPM error dialog to pop.  
<img width="895" alt="Screen Shot 2021-04-06 at 2 22 43 PM" src="https://user-images.githubusercontent.com/733559/113780112-95ce4d00-96e3-11eb-9c8f-5c675926d3b4.png">
7.  Dismiss the error dialog
8. Repeat steps 2, 2, 4, & 5 from above
9. Note that in step 5 when you try to name your bot 'basic_x', you'll be informed that bot name is in use

if you open a terminal window and browser the folder where you have Composer create new bots you'll see an empty folder named 'basic_x'.  The existence of this folder prevents the name reuse.

## Expected behavior
Given that the bot creation failed, and in fact failed early on, it would be nice that the failure case here actually cleans up.

**Comment by adiazcan** [comment]
I am trying to fix this problem in my environmente without any success ;( 

I found in the "Select template" window a command-line to create the project and I had a permission problem downloading the npm package from yeoman template generator. 

![image](https://user-images.githubusercontent.com/6652046/113837449-25303a80-978e-11eb-8fd2-ea25c3b98096.png)

any help?

**Comment by adiazcan** [comment]
ok, I don't know why but I need to fix my home .npmrc and now, I can install the yeoman template generator but I found a new bug trying to create the project from command line

![image](https://user-images.githubusercontent.com/6652046/113838204-d7680200-978e-11eb-9739-c7f94474ba45.png)

**Comment by adiazcan** [comment]
If I use the Composer creation experience, I have the following error: 

![image](https://user-images.githubusercontent.com/6652046/113838454-10a07200-978f-11eb-9fc0-994b505ed622.png)
