### ISSUE TITLE
Error dialog clips error message text

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6727]
## Describe the bug

I'm using a nightly build of Composer where I can consistent cause the creation process to fail.  When I get an error message, and view the details of that message, the error text is clipped.  See attached screenshot

## Version
Version:  1.4.0-nightly.231667.d104286
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Figure out how to cause an error.  
2. view the details of the error from the error modal.  see attachment

## Expected behavior
The text of the error shouldn't be clipped.

## Screenshots
<img width="798" alt="Screen Shot 2021-04-06 at 2 50 28 PM" src="https://user-images.githubusercontent.com/733559/113783039-fb243d00-96e7-11eb-857b-b2f263520d6d.png">

## Additional context
I've selected the entire text in the error dialog as that makes it a bit easier to see the text formatting issue.

**Comment by chrimc62** [comment]
I also had an error dialog where I got a scroll bar, but it scrolled only over white space.

**Comment by srinaath** [comment]
We need to see if we can prioritize it for R13.

**Comment by emivers8** [comment]
By golly, that second one is a doozy. So is the ask to just improve these error dialogs? Not a problem for the first one, but I'll need more details for the second.

**Comment by emivers8** [comment]
Aaaaand here's a design:

![image](https://user-images.githubusercontent.com/55601267/114072957-9e479480-9857-11eb-824c-05bab8c6353e.png)

Figma: https://www.figma.com/file/tvENftrexoAYJngzsJxUbv/EmFig?node-id=3479%3A17189

**Comment by srinaath** [comment]
@benbrown  Are we looking to handle this in a different way by plumbing through the creation errors into the Outputs tab in the Debug Pane?

**Comment by srinaath** [comment]
@benbrown This looks to be part of the creation work stream. @emivers8 has the design to show the creation errors in the \<ErrorBoundary /> component which needs some styling changes to accomodate this new design.

**Comment by srinaath** [comment]
I think we need to build a contract for the ErrorBoundary component to accept a title, message and different schemas for the error body (one for creation, one for unhandled exception etc). I can work with you on this @benbrown next week after our p0's
