### ISSUE TITLE
Channels is confusing resourceName and resourceGroup in validation

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#6731]
When attempting to add a channel to my newly created bot, I received the error below:

![image](https://user-images.githubusercontent.com/1139814/113830235-4451ac80-973b-11eb-9cd2-859d860c9600.png)

However, the resource group in my publishing profile is "ac-test-deleteme", and the resource name is "BobTeams". I believe Composer is attempting to validate the wrong field.

![image](https://user-images.githubusercontent.com/1139814/113830211-3bf97180-973b-11eb-8103-1f5b5e423749.png)

## To repro

1. Create a new empty/blank bot
2. Create a new publishing profile. Make sure the resource name and the resource group name are different
3. Provision your resources
4. Attempt to configure a channel
5. Observe error.

**Comment by benbrown** [comment]
OK this should be fixed by #6872.  The connections widget had not yet been updated for the reality that the resource group name can be different than the resource name.
