### ISSUE TITLE
LUIS 403 error when prediction key assigned / provisioned in settings

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#6735]
## Describe the bug

When you use Composer to provision / assign existing LUIS resources for local dev / testing, it sets a prediction key.  Once this is set, you will get an error when you try and test your bot, "Response status code does not indicate success: 403 (Forbidden).", which I believe is due to the fact that the resource has not been associated with your LUIS app that Composer is creating / updating when you start your bot.

## Version

Version:  1.4.0-nightly.231667.d104286
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Expected behavior

If you have set a LUIS prediction key locally, we should associate the LUIS app with the prediction resource when your bot is started. 

@Dewain27

**Comment by Dewain27** [comment]
When we initiate the process to create the LUIS instance for the Developer Environment for Composer, we are creating an Endpoint / Prediction key.  This is not needed for the developer instance.  We will need to make the following changes:

### **Changes Needed**

- [ ] Remove the generation of a LUIS Prediction / Endpoint key from the provisioning process.
- [ ] Remove the LUIS prediction / endpoint key fields from the following UIs
![image](https://user-images.githubusercontent.com/18688053/114074891-81688c80-986a-11eb-90ae-020ceed70365.png)
![image](https://user-images.githubusercontent.com/18688053/114074997-a65cff80-986a-11eb-85f1-720bf7489417.png)

### **What needs to remain**

- [ ] Advanced Settings View retains the setting for endpointKey
![image](https://user-images.githubusercontent.com/18688053/114075394-1c616680-986b-11eb-9d19-c29d51130d7c.png)
