### ISSUE TITLE
Additional Web Chat Integration P1 / P2's

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Composer#6749]
This is a continuation of #6511 to represent the remaining P1 and P2 work items to be done for the Web Chat integration.

### P1's

- [x] Implement a selected state indicator for the log message currently being shown in the inspector pane
- [x] Auto-inspect the latest message in the log pane if there is no message currently inspected

### P2's

- [x] Extend debug panel outside of the authoring canvas -- it should be at the same level as the project tree
- [ ] Make the Web Chat panel float above / respect the debug panel
- [ ] ~~Implement status bar (Needs investigation)~~

**Comment by mewa1024** [comment]
Can we add another P1? "Enable selecting a message Web Chat to select the corresponding Web Chat log item" like this:

![image](https://user-images.githubusercontent.com/39317542/114102737-b978cb00-987c-11eb-8b43-6a2d1162e03f.png)

Emulator has this behavior.

**Comment by tonyanziano** [comment]
@mewa1024 is there a selected state in Web Chat as well for the activity, or does clicking on an activity just highlight its associated log entry and populate the inspector tab?

**Comment by mewa1024** [comment]
@tonyanziano I think the answer to both is yes. I thought Web Chat already had a selected state--clicking a message in the Web Chat pane in Composer looks like this:
![image](https://user-images.githubusercontent.com/39317542/114429766-96973100-9b72-11eb-9f1e-4da6a85e0bac.png)

If the Web Chat pane is not open, is it possible to still select the message so that if the user opens Web Chat, the message will appear in the selected state?

**Comment by tonyanziano** [comment]
@mewa1024 , I think it should be possible, but I'd have to dive into the code a little bit to make sure.

**Comment by mewa1024** [comment]
Hi, this last part (selected a log message selects the corresponding bubble in Web Chat and vice versa) didn't get in (or reverted back?). Attached is a screen recording showing that selecting the log doesn't not change the selection in Web Chat or vice versa.

https://user-images.githubusercontent.com/39317542/120252893-be357c00-c23a-11eb-8355-624bbd2848fa.mov

@tonyanziano @srinaath Can we get this in R14?
