### ISSUE TITLE
Get LUIS keys does not copy keys/region

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotFramework-Composer#6753]
## Describe the bug
I can use "Get LUIS Keys" to get the keys, but when I get them they are not copied properly and I get errors.

![image](https://user-images.githubusercontent.com/17637681/113942013-03967980-97b5-11eb-8014-c5fddbfb0095.png)
![image](https://user-images.githubusercontent.com/17637681/113941949-e9f53200-97b4-11eb-9044-ad95fd38cb4b.png)

## Version

Version:  1.4.0-nightly.231667.d104286
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce

1. Click on "Get LUIS Keys"
2. Select the keys you want
3. Click next

## Expected behavior

The keys and region are properly copied to the UI.

**Comment by benbrown** [comment]
I believe this is actually a UI issue - the values ARE set, but the UI in the settings page does not accurately update.

**Comment by pavolum** [comment]
closing as this is a copy of #6822
