### ISSUE TITLE
Upgrade story for ejected runtime project when upgrading composer to a newer version?

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#6761]
Hi Composer team, this is a general question regarding to ejected runtime. 
If we have an ejected and customized runtime from the past, is there some guidance or procedure for upgrade story?

e.g., how to make the ejected runtime up to date after we upgrade the composer to a new version which might have updated runtime code throughout the infrastructure?

**Comment by peterinnesmsft** [comment]
Hi @dawwa,

Let me follow up with @darrenj and @garypretty here and we can get you some clarity on this scenario.

**Comment by peterinnesmsft** [comment]
Taking offline.
