### ISSUE TITLE
Publishing Bot Composer v1.4.0 Project throwing different kind of Issues

### ISSUE THREAD

**Issue by LakshummaC** [microsoft/BotFramework-Composer#6764]
Hi Team,

When we are trying to publish the Bot Composer to Azure, it is throwing 2 kind of errors.

1.A popup says to raise issue in github.
2.As page wrong as shown below. Same while opened in desktop or using localhost:5000/

![image](https://user-images.githubusercontent.com/76558423/114026434-dec50380-9893-11eb-969b-694fe2f66d2c.png)

**Comment by anusharavindrar** [comment]
@LakshummaC,  do you get any error in the provisioning step or just this above error in the publish step after importing the Azure resources? Also, does this happen to a specific bot? Do you get any additional error on the dev console?

**Comment by LakshummaC** [comment]
> @LakshummaC, do you get any error in the provisioning step or just this above error in the publish step after importing the Azure resources? Also, does this happen to a specific bot? Do you get any additional error on the dev console?

Hi Anusha,

Initially with localhost:5000 and then opened our designed Bot and tried publishing. Till Import from existing resource it worked fine for the first time. After a min we started getting above screenshot error. 

There is no additional error on dev console and browser goes to not responding stage and throws above snapshot error.

**Comment by LakshummaC** [comment]
After multiple retries in local desktop Bot composer it is throwing below error:

![image](https://user-images.githubusercontent.com/76558423/114152256-ae38a480-993b-11eb-9f0f-8bad46103c06.png)

**Comment by LakshummaC** [comment]
{
  "name": "<unique name in your subscription>",
  "environment": "dev",
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "<name of your resource group>",
  "botName": "<name of your bot channel registration>",
  "subscriptionId": "<id of your subscription>",
  "region": "<region of your resource group>",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "<Instrumentation Key>"
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "<endpoint url>",
      "authKey": "<auth key>",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "<connection string>",
      "container": "<container>"
    },
    "luis": {
      "authoringKey": "",
      "authoringEndpoint": "",
      "endpointKey": "",
      "endpoint": "",
      "region": "westus"
    },
    "qna": {
      "subscriptionKey": "<subscription key>",
      "endpoint": "<endpoint>"
    },
    "MicrosoftAppId": "<app id from Bot Framework registration>",
    "MicrosoftAppPassword": "<app password from Bot Framework registration>"
  }
}

on a safe note, can you explain the starting 5 fields what I have to put?

**Comment by LakshummaC** [comment]
any update on this? I need it ASAP

**Comment by LakshummaC** [comment]
Issue Resolved, you can close this ticket
