### ISSUE TITLE
Example value for OAuth login's Token property should be in turn scope

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#6767]
## Describe the bug

The example value for the OAuth action's Token property is `ex. @token`, which would be shorthand for `turn.recognized.entities.token`, which doesn't make any sense.

## Version

Version:  1.4.0-rc4-nightly.226081.b0a126
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot and add an OAuth login action.
1. See error: The example value targets entity recognized scope, `@token`.

## Expected behavior

According to Andrew, (composer-docs [issue 121](https://github.com/MicrosoftDocs/composer-docs/issues/121)), tokens should be stored in turn scope. The example value should reflect this.

## Screenshots

![image](https://user-images.githubusercontent.com/35047199/114056142-350b5580-9846-11eb-89c7-e8d19e722c6a.png)

## Additional context

composer-docs [issue 121](https://github.com/MicrosoftDocs/composer-docs/issues/121)

**Comment by srinaath** [comment]
@sangwoohaan Is this something you can provide inputs on?

**Comment by mewa1024** [comment]
Does this issue refer to the "Token property" field or the "Default value" field? 
![image](https://user-images.githubusercontent.com/39317542/124068614-ad218b80-d9ef-11eb-9bbf-958e0c439af5.png)

It looks like the ports referenced above affect the "Token property" field. Is the "Default value" example still incorrect? If so, what should it say?

**Comment by JonathanFingold** [comment]
@mewa1024 - The issue was opened for the **Token** property's example value, which become visible once you edit and delete its default value:
**Token** default value:
![image](https://user-images.githubusercontent.com/35047199/124506989-ae511080-dd81-11eb-98f7-90b62a289a6a.png)
**Token** example value:
![image](https://user-images.githubusercontent.com/35047199/124507017-bf9a1d00-dd81-11eb-9d87-4709ae29e5de.png)

Bruce's PR was meant to fix this, but due to how .schema files from the nightly SDK builds are ingested into the Composer nightly builds, the fix has not made it into Composer yet. I talked to @tonyanziano about this, and he can fill you in on the details.

All that said, you are correct that the **Default value** property's example value is also not right, and a fix similar to Bruce's PR needs to be made in the SDK for this one, too. I don't know what a good example for this would be. Perhaps @lauren-mills or @clearab can say.
![image](https://user-images.githubusercontent.com/35047199/124507343-772f2f00-dd82-11eb-8f52-980c4229aa8a.png)

**Comment by tonyanziano** [comment]
@JonathanFingold I brought this issue up in our triage meeting today.

Once the desired changes make it into the SDK repo, which you have done already with Bruce's PR, **the limiting factor is the version of the SDK that the templates in the components repo are published with.**

I took a quick look and it seems like [the SDK version in the components repo is still using the older schema](https://github.com/microsoft/botframework-components/blob/main/generators/generator-bot-adaptive/generators/app/templates/assets/schemas/sdk.schema#L5732). However, there might be a way to set a flag within Composer that allows you to create bots using pre-release versions of the templates that may contain the new SDK bits.

@benbrown or @pavolum might be able to help you there.

**Comment by lauren-mills** [comment]
Looks like this is resolved.
