### ISSUE TITLE
Creation interstitial UX blends into the new home screen UX and unreadable

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#6768]
## Describe the bug

Creation interstitial UX blends into the new home screen UX and is unreadable also leading to confusion around if composer is doing something.

## Version

1.4.0-nightly-232669

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot 
2. Choose a template (assistant core)
3. Observe the interstitial UX talking about download package, merging packages, creating, etc..

## Expected behavior

- Clearer Modal dialog UX so it's clear Composer is doing something!

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/114056101-3ca01e00-9889-11eb-80b9-705de88abe76.png)

**Comment by Dewain27** [comment]
Duplicate #6663 in PR
