### ISSUE TITLE
ChitChat and LUIS not working in a new Assistant Core template project (existing qna/luis resources)

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#6772]
## Describe the bug

Creating a new Assistant Core template, choosing existing LUIS and QNA Azure resources and clicking start results in a conversational experience that doesn't seem to work. Both LU triggers (e.g. Help) and QnA/ChitChat ("hello") don't seem to be processed correctly.

## Version

1.4.0-nightly.232669

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new Assistant Core template
2. Using "rocket ship" UX, select existing QnA and LUIS resources already provisioned in Azure
3. Start Bot
4. Test in webchat - "help" and "hello"

No errors/warnings surfaced in Composer output/trace windows

## Expected behavior

The assistant core functionality (LU and QNA) to work.

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/114058229-2eeb9800-988b-11eb-8072-7cad0662a49f.png)

**Comment by darrenj** [comment]
In the latest build (1.4.0-nightly.234518) LUIS does now appear to work however QnA is still causing an issue. I do now see in Composer trace this error : `Unable to get a value for EndpointKey from state.`

![image](https://user-images.githubusercontent.com/33519520/114550256-e4d32f80-9c59-11eb-97e3-e16aaf47764d.png)

**Comment by benbrown** [comment]
@darrenj Should be resolved by #6881 please re-open if you still experience this!

**Comment by darrenj** [comment]
Now getting a qnamaker runtime error when starting the Bot (new project using the basic assistant template) on 1.4.0-nightly.236490. Selected existing QnA and LUIS keys in my Azure subscription.

![image](https://user-images.githubusercontent.com/33519520/115268806-8fec5900-a132-11eb-973f-856cd084e995.png)

**Comment by darrenj** [comment]
I've tested with the latest nightly have have the same qnamaker build error:
1.4.0-nightly.237504.  I created a brand new basic assistant inside Composer, selected an existing LUIS and QnAMaker key and hit start...

**Comment by darrenj** [comment]
Resolved in latest nightly. There is another issue relating to QnAMaker resources that have exceeded azure index quotas which leads to an obscure runtime error inside Composer, opening another bug to track
