### ISSUE TITLE
QnA Maker and LUIS should be listed in required resources if needed in Publishing Profile

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6775]
## Is your feature request related to a problem? Please describe.

Today, we identify and help you provision LUIS and QnA Maker when you open your bot project, however when you have publishing profiles already created and / or you create a new one you should be told that these are required resources on the Add resources modal.
![image](https://user-images.githubusercontent.com/18688053/114064728-896eff00-985f-11eb-8580-6151c844023f.png)

## Describe the solution you'd like

By intelligently adding the required resources based off of your project, this will make it where you don't get an error message when you go to publish.

## Describe alternatives you've considered

Using the Next Steps menu to provide details that you should add the required resources to your publishing profiles to ensure that you give the user a heads up that all publishing profiles will now require this to be added and walk them through getting this done.  Maybe even disable publishing until these issues are addressed.

**Comment by GeoffCoxMSFT** [comment]
Discovered we need to filter by project ID for the required LUIS or QnA so reactivating this as the issue for making and update PR.
