### ISSUE TITLE
Copy/paste dialog contents to another dialog results with data loss of LG in target

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6777]
Copy and paste contents of one dialog (with more complex logic, not just a hello world box) to another dialog. The resulting dialog is missing all contents. LG on disk is empty. 
When using in PVA Composer, no errors are showing up until failures in PVA.

**Comment by boydc2014** [comment]
close due to dup with https://github.com/microsoft/BotFramework-Composer/issues/7045
