### ISSUE TITLE
Open some bot (from new RT) results with blank canvas composer

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6779]
Tried to open a bot from ~2-3 weeks ago with the new RT. 
Results: blank canvas in Composer, bot is not openning.
Expected: Even malformed bot solutions should never result with empty canvas. Have a graceful error message with some diagnostics capabilities.

(specific bot for repro is available on request - it is a large zip).

![image](https://user-images.githubusercontent.com/8867670/114068234-8cafbe00-9852-11eb-8a08-551070e9c9e5.png)

**Comment by srinaath** [comment]
@scheyal The Runtime bits have changed quite a bit over 2-3 weeks. We expect bots created in that timeframe to be broken as a lot were preview bits. Do you see a specific bug that we need to address with the new runtime though that might cause issues with compatibility.

**Comment by scheyal** [comment]
All I get is a blank page. It is best if we never get to this situation regardless of the underlying bug. Apparently there are a few repros, maybe all stemming from bots that were created in the past month but there's no way to find anything about it that I know of. At minimum we should catch it and render an error message.

**Comment by scheyal** [comment]
Also, we need a recovery plan for those who spent time building those bots.

**Comment by Dewain27** [comment]
@scheyal we need to get a copy of the bot to repro this issue.  We need additional information to repro.
