### ISSUE TITLE
Publish modal's comment text box needs some ux love

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6789]
## Describe the bug
When you publish a bot using an existing publishing profile, you'll be prompted with a "Publish" modal where the profile name, publishing target and publishing comment can be added before invoking the actual publish action.

The comments text field is oddly small.  See screen shot.

## Version
Version:  1.4.0-nightly.232669.4daad5c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open an existing bot project.  
2. Create a publishing profile, if the project doesn't yet have one.  This will perform the necessary provision and deployment steps.
3. With a fully functioning publishing profile, nav to the Publish your bots page.
4. Select the bot to publish, ensure you have your publishing target selected (should already be selected)
5. Click the "Publish selected bots" top-level menu item to invoke the publishing flow.  This will display the Publish modal.
6. Notice the comments edit box.  

## Expected behavior
In general, we seem to have overly narrow dialogs in Composer.  In this particular modal, the edit box doesn't even show the full help text.  

## Screenshots
<img width="599" alt="Screen_Shot_2021-04-08_at_11_39_54_AM" src="https://user-images.githubusercontent.com/733559/114080499-537e4a80-9860-11eb-930d-845bd7f9d83b.png">

**Comment by pavolum** [comment]
May be preferred to remove border when not selected

**Comment by sgellock** [comment]
@pavolum can you give me something larger than 6 characters?  that's the real issue I'm raising, not really the border issue.

**Comment by pavolum** [comment]
Yes that change is already in, what I was noting was a UI request from Marieke
