### ISSUE TITLE
e2e Testing: Unable to create a bot using Conversational Core template

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/BotFramework-Composer#6797]
## Describe the bug
Unable to create a bot using Conversational Core template. 

## Version
Composer build used for testing: https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.4.0-nightly.232669.4daad5c

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Start Composer
2. Click 'New' on the page
3. Select 'Create from Template'
4. Scroll down to select 'Conversational Core' template.
5. Click 'Next'
6. Click 'OK'

## Expected behavior
A bot is created based on the conversational core template

## Screenshots
![image](https://user-images.githubusercontent.com/29185255/114088318-c17b3f80-9869-11eb-92d1-680f345a7f20.png)

**Comment by Dewain27** [comment]
Verified that this is fixed in new nightly as of:
Version:  1.4.0-nightly.233315.683520a
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
