### ISSUE TITLE
Contextual menu for labeling entities sits on top of Web Chat pane

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#6799]
## Describe the bug

Contextual menu for labeling entities sits on top of Web Chat instead of underneath it.

## Version

Version:  1.4.0-nightly.232669.4daad5c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot
2. Select a trigger that uses an intent.
3. Double-click a token to bring up the "Tag entity" menu:
![image](https://user-images.githubusercontent.com/39317542/114092309-934c2e80-986e-11eb-8d1e-1244b9c3c562.png)
4. Open Web Chat. The "Tag entity" menu sits on top of Web Chat, instead of below it:
![image](https://user-images.githubusercontent.com/39317542/114092367-a828c200-986e-11eb-8f7f-aa5711a56490.png)

## Expected behavior

The Web Chat pane should sit on top of details pane/property panel, including its context menus.

## Screenshots

fwiw:
The context does sit below the Getting Stared (rocket ship) menu, which is correct:
![image](https://user-images.githubusercontent.com/39317542/114092878-3f8e1500-986f-11eb-83c9-62315261e08d.png)

**Comment by srinaath** [comment]
@hatpick Could you take a look at this ticket with the enitity labeller positioning?

**Comment by hatpick** [comment]
@srinaath it's up to the **order** that they appear in the DOM, since fabric Callouts use portals, they always get appended to the end so they appear over things. From what I understand, user has a panel open, then they try to tag an entity from underneath, so it only makes sense that they should be able to see the tagging menu, right?

**Comment by mewa1024** [comment]
> @srinaath it's up to the **order** that they appear in the DOM, since fabric Callouts use portals, they always get appended to the end so they appear over things. From what I understand, user has a panel open, then they try to tag an entity from underneath, so it only makes sense that they should be able to see the tagging menu, right?

Hmm. I don't think it always make sense for the tagging menu to appear over everything else. For example, in the repro steps above, I was in the entity labeler and then decided to open Web Chat and test the bot. So I would expect Web Chat to appear over the LU editor and over the LU entity contextual menu. It's unusual that the Web Chat appears sandwiched between the LU editor and the entity menu. What I would expect is what the rocket ship menu is doing: covers the property pane, including the LU editor and the context menu.

**Comment by mewa1024** [comment]
Screen recording of the overlapping:

https://user-images.githubusercontent.com/39317542/115468756-6261e700-a1e8-11eb-8bf4-b9958748b194.mov

**Comment by tdurnford** [comment]
@mewa1024  I agree, I think we should close the context menu when the LU Editor loses focus. I can make the update.

**Comment by tdurnford** [comment]
@mewa1024 Are you suggesting we should hide the entity labeler when the Lu Editor loses focus? If so, I can make that change.

**Comment by mewa1024** [comment]
yes! thanks!

**Comment by hatpick** [comment]
@mewa1024 what if one of those panels are open and user selects a text underneath?

![Screen Shot 2021-04-22 at 11 59 19 PM](https://user-images.githubusercontent.com/1483492/115831767-e2de3e80-a3c6-11eb-875e-1473abb8fa33.png)

**Comment by mewa1024** [comment]
context menu should open below rocket ship.
