### ISSUE TITLE
LU editor: "Tag entity" menu redundant with the context menu

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#6802]
## Describe the bug

In the UI for trigger phrases, when you select one or more words, a context menu opens for tagging the entity and the "Insert entity" menu in the command changes to "Tag entity". Can we not change the "Insert entity" menu so there is only one control for labeling entities?

## Version

Version:  1.4.0-nightly.232669.4daad5c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot.
2. Select a trigger that uses LU:
![image](https://user-images.githubusercontent.com/39317542/114093683-45d0c100-9870-11eb-9d53-ccff17570930.png)

3. In the trigger phrases, select a word. Two things happen: A "Tag entity" contextual menu appears:
![image](https://user-images.githubusercontent.com/39317542/114093722-4ff2bf80-9870-11eb-9be2-bd4834ff215c.png)

The "insert entity" menu also changes to "Tag entity". 
![image](https://user-images.githubusercontent.com/39317542/114093797-66991680-9870-11eb-8051-aaa912a2c367.png)

Can we remove that behavior? (What is the use case where the toolbar "Tag entity" menu would be more useful than the context menu?)

The "Tag entity" command in the toolbar seems redundant (and also inconsistent--prebuilt entities don't appear in the contextual Tag entity menu, but they appear disabled in the toolbar Tag entity menu:
![image](https://user-images.githubusercontent.com/39317542/114094018-a65ffe00-9870-11eb-8d6a-05f9b022ac86.png)

Also if the "Insert entity" menu did not switch modes, could we remove the "Insert defined entity" subhead in the Insert entity menu:

![image](https://user-images.githubusercontent.com/39317542/114094487-39993380-9871-11eb-83d6-b58be25e013a.png)

## Expected behavior

I'd expect the "Insert entity" to stay the same and not be replaced with the "Tag entity" menu:
![image](https://user-images.githubusercontent.com/39317542/114096009-05267700-9873-11eb-93ea-13cf1ee6a195.png)

This could follow the behavior of inserting a hyperlink in Word. If text is selected, it is tagged. If there is not text select, an empty entity is inserted.

**Comment by cwhitten** [comment]
adding @sangwoohaan for comment

**Comment by sangwoohaan** [comment]
For this, leaving the insert entity button as-is when you have highlighted a word would cause a problem, since the insert is supposed to happen where the cursor is. Unless we want the highlighted word to be replaced with an inserted entity, we either want this also to be tagging experience(current build), or deactivate the insert entity button like this :


![Globalframe](https://user-images.githubusercontent.com/50963385/115087951-0fc0bc00-9ec4-11eb-8cdc-c0150b33d337.png)

I do agree with Melanie's feedback – let's make this button inactive when you highlighted something @tdurnford

**Comment by mewa1024** [comment]
Can we also change "tag" to "label"? LUIS (and I think the other cognitive services/Azure AI) use the term labeling for machine learning, rather than "tagging". (sorry--forgot to mention that earlier.)
