### ISSUE TITLE
Web Chat inspector pane, show LUIS traces in the log text

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#6807]
## Describe the bug

The Web Chat inspector shows LUIS traces like any other trace. Can we show "LUIS trace" in log?

## Version

Version:  1.4.0-nightly.232669.4daad5c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Start a bot in Composer.
2. Talk to the bot in Web Chat in Composer.
3. Open the bot in Emulator and use the same utterances.
4. Compare logs. The Web Chat inspector shows the LUIS trace as any other trace:

![image](https://user-images.githubusercontent.com/39317542/114103985-eaf29600-987e-11eb-92d3-7fc8b692956c.png)

## Expected behavior

I'd expect trace events caused by LUIS should be called "LUIS traces" in the log to match Emulator.

**Comment by mewa1024** [comment]
Also add trace for "Bot State" and the "Qna trace", if possible.

**Comment by tonyanziano** [comment]
Closed by #6846
