### ISSUE TITLE
New lg editor does not work well in multi-lang.

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#6811]
New lg editor does not work well in multi-lang.

- Create a bot
- add another language
- Add "send activity"
- switch to the new language
- editing in new lg editor for send activity 
- some time will hit following error (not everytime)
![image](https://user-images.githubusercontent.com/43408889/114109114-2c2e8880-9907-11eb-879b-d8b257bd94ac.png)
- go to all up view, the LG template created across the language

But following step will hit error
- Switch the authoring language to "new locale"
- editing in LG new editor 
- add text as below
![image](https://user-images.githubusercontent.com/43408889/114109360-b37bfc00-9907-11eb-8bb1-484372475d45.png)
- navigate to other page 
- switch the authoring language back to "default language
- start to edit "send activity" again 
![image](https://user-images.githubusercontent.com/43408889/114109434-d73f4200-9907-11eb-89f3-1c16c94e2477.png)
- switch back to the original local
- the LG content is gone
![image](https://user-images.githubusercontent.com/43408889/114109596-25ecdc00-9908-11eb-956e-83cc775a4d00.png)

**Comment by boydc2014** [comment]
@zhixzhan can you help take a look at this, i expect some code paths in new LG editor that are not creating templates in all locales.

**Comment by zhixzhan** [comment]
I will take a look today

**Comment by hibrenda** [comment]
When you add "sendactivity" , the LG editor placeholder is correct. 
But when you edit the "sendactivity" for specific language with the new lg editor, it will break something.
