### ISSUE TITLE
add  existing skill hit error

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#6813]
- create a bot (adaptive runtime)
- add existing bot (legacy runtime)
- will hit following error 
![image](https://user-images.githubusercontent.com/43408889/114111011-7fa2d580-990b-11eb-9aac-edaee5ace764.png)

**Comment by srinaath** [comment]
closing as fixed in https://github.com/microsoft/BotFramework-Composer/pull/6800
