### ISSUE TITLE
New Bot Creation progress design feedback 

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6814]
## Describe the bug
It would be good to have @emivers8 provide some feedback on how we are doing publishing progress.

At the very least, I would off two changes that could improve upon the current experience.

1. The progress spinner and the status text is very small, compared to what is happening.  See the screen shot below.
2. I would be good to provide some sort of task total count experience.  

e.g.  
1 of 6 Provisioning 
2 of 6 Doing whatever is next
3 of 6 Doing the next thing in the process

## Version
Version:  1.4.0-nightly.232669.4daad5c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer
2. Click the '+' to create a new bot
3. Select any bot template, empty or whatever we're calling basic bot these days is good enough
4. Fill in the required data
5. Once the creation experience starts to template download, we display a spinner and update the text of that spinner ui

## Expected behavior
Give that UX a little design love

## Screenshots
<img width="1784" alt="Screen Shot 2021-04-08 at 9 16 23 AM" src="https://user-images.githubusercontent.com/733559/114114590-0321df80-9896-11eb-874f-1bcf46924192.png">

**Comment by Dewain27** [comment]
Duplicate already completed in latest build
