### ISSUE TITLE
Unable to read LUIS settings in the latest version of composer 1.4.0

### ISSUE THREAD

**Issue by vidyakdil** [microsoft/BotFramework-Composer#6819]
## Describe the bug

In our existing bot solution we upgraded the packages required for the Composer. When we have the dialogs with the recognizer as regex, the bot solution is running fine. If we set it to default recognizer, we are getting the following exception
**"\"\" is not a valid LUIS application id.**

## Version
1.4.0

## Steps to reproduce the behavior:

1. Create an echo bot solution
2. Add the bot builder packages required for processing adaptive dialogs
3. In onmessage activity, add the code to process the adaptive dialog
4. Create dialogs in composer using the default recognizer
5. Copy the dialog files to the folder and copy paste the appsettings,json
6. Make changes in Program.cs as provided in the code sample to read the LUIS settings
7. Run the solution and trigger any dialog
8. You'll get the exception
9. At the same time, bot with regex as recognizer will continue to work

**Comment by lauren-mills** [comment]
@vidyakdil - can you confirm that you are taking a C# project and trying to convert it to use composer? Can you share the instructions you are following?

Also, are you adding the luis config to your appsettings? There is a secondary set of settings you may need to provide which is the mapping of the luis appId to the dialog. Composer generates this automatically, but if you are wiring a C# bot to use declarative files, you may need to add it yourself:

```
"luis": {
    "name": "",
    "authoringKey": "00000000000000000000000000000000",
    "endpointKey": "00000000000000000000000000000000",
    "authoringRegion": "westus",
    "defaultLanguage": "en-us",
    "environment": "composer",
    "endpoint": "https://westus.api.cognitive.microsoft.com",
    "authoringEndpoint": "https://westus.api.cognitive.microsoft.com",
    "GetEventsDialog_en_us_lu": {
      "appId": "00000000-0000-0000-0000-000000000000",
      "version": "0.1"
    },
    "<Your-Dialog-1>_en_us_lu": {
      "appId": "00000000-0000-0000-0000-000000000000",
      "version": "0.1"
    },
    "<Your-Dialog-2>_en_us_lu": {
      "appId": "00000000-0000-0000-0000-000000000000",
      "version": "0.1"
    },   
    ...
  },
```

**Comment by vidyakdil** [comment]
Yes we added the LUIS details to the appsettings.json. But this didn't work

**Comment by vidyakdil** [comment]
As this issue is continuing, we degraded the Composer version to 1.3.1 and this is working. Can you please help us to understand the issue here.

**Comment by tsuwandy** [comment]
@vidyakdil, instead of following the repro steps above, could you create  a bot from Composer template?  There is an Echo bot template or Todo with LUIS template.  No need to update code or copy/paste appsettings.json as Composer generated code already does this.  

![image](https://user-images.githubusercontent.com/10739108/117245737-28036700-adf0-11eb-88b6-f215f040dc43.png)

Update the required LUIS settings in the bot project settings:

![image](https://user-images.githubusercontent.com/10739108/117246107-d8716b00-adf0-11eb-9917-16e143db9e3c.png)

Hope this helps with creating a bot with the latest Composer build.  Let us know otherwise.
