### ISSUE TITLE
Create New Resources dialog text is laid out oddly

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#6825]
## Describe the bug

Description text (screenshot) is poorly formatted.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a publishing profile

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/114167315-b1756580-9926-11eb-8e40-0872f00e4112.png)

**Comment by sgellock** [comment]
This is a dup of #6780
