### ISSUE TITLE
Can't publish despite publishing profile existing

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#6826]
## Describe the bug

Publish profile doesn't show up on Publish drop-down list despite being created

## Version

1.4.0.nightly-233315

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new project
2. Create publishing profile and complete publishing
3. Go to publish UX and observe profile doesn't show up

## Expected behavior

Publishing profile shows up to enable publishing

## Screenshots

**Publishing profile is created**
![image](https://user-images.githubusercontent.com/33519520/114169368-5e50e200-9929-11eb-8e44-f89f721e5e01.png)

**However, when on Publish it doesn't show up in drop-down list, only manage profiles **
![image](https://user-images.githubusercontent.com/33519520/114169636-b851a780-9929-11eb-8d89-0e7f418d5170.png)

**Comment by benbrown** [comment]
This looks like a state problem - the profile list hasn't been updated for some reason

**Comment by pavolum** [comment]
Yeah it is a state problem. If you nav away and back then the dropdown populates with latest. 

To repro you need to...
- provision a new profile in the provision tab
- wait for it to complete provisioning without naving around the app
- Once it is finished provisioning you go to publish and the dropdown will not be updated with just created provision profile

At initial glance it seems that the botStatusList should update when provision s complete which should propogate down to the dropdown component but that does not seem to be happening as expected. 

Testing is rather cumbersome as you have to provision a new profile each time to repro the state error but it does seem to be a rather simple state bug.
