### ISSUE TITLE
Form Dialog issue with repeated prompt of field of string type

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#6828]
## Describe the bug
Form Dialog , String attribute is repeatedly asking the user the same question

## Version

![image](https://user-images.githubusercontent.com/26645750/114179904-1c2a9f00-992f-11eb-9a3a-6f5f65a3e9db.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
Chrome
## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu
Windows
## To Reproduce

1. Go to Form Dialog, Upload Schema
2. generate dialog
3. run emulator 
4. suppose we have address field, as string, the same comes repeatedly.
5. 5. This  started happening with the new composer build that I have taken today.

**Comment by chrimc62** [comment]
@aparnaji can you share your form and your transcript?  I created a form with a string property using the nightly and it worked fine.

**Comment by aparnaji** [comment]
Attached the file , pls check in zip
[Form1.zip](https://github.com/microsoft/BotFramework-Composer/files/6289513/Form1.zip)
I have used the below build 
![image](https://user-images.githubusercontent.com/26645750/114264015-fc9b8100-99d7-11eb-8fe5-f9489f72be75.png)
Let me know the build that you have used

**Comment by lauren-mills** [comment]
@chrimc62 - can you take a look at the project that was shared and update this issue?

**Comment by chrimc62** [comment]
I am still unable to repro your issue.  I'm using 
```
Version:  1.4.0-nightly.233776.7019ef0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```
Here is a transcript against your form. 


[repeateString.zip](https://github.com/microsoft/BotFramework-Composer/files/6299018/repeateString.zip)

**Comment by aparnaji** [comment]
I recreated the entire project and now it works, but intermittently I sometimes see this issue.

**Comment by chrimc62** [comment]
Usually this is caused by LUIS not recognizing entities.  Next time it happens, check the LUIS return data to see if it has the expected entities in it.
