### ISSUE TITLE
When creating a QnA Maker Bot from template get Start bot failed

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6831]
## Describe the bug

When you create a bot using the QnA Maker bot template, you get Start Bot failed when you try to start bot.
![image](https://user-images.githubusercontent.com/18688053/114201326-b08b0680-991b-11eb-8610-555719cdb2d0.png)

## Version

Version:  1.4.0-nightly.233315.683520a
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create New Bot
2. Select QnAMaker Bot template
3. Generate or populate your QnA Maker resource key
4. Start Bot
5. See Error

## Expected behavior

Should be able to start the bot and test your bot experience

**Comment by benbrown** [comment]
This was not QNA specific - the build included a broken start bot function.

Fixed by #6816
