### ISSUE TITLE
Not able to create a new project

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#6832]
## Describe the bug

Duplicate name 

## Version

Release: 1.4.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1.	Create a new project ex: 01Message
2.	Switch to Home menu (In the composer)
3.	Delete the folder (step 1) in the drive
4.	Create a new project (Click the new menu and select the option Create from scratch)
5.	Enter the same name ex: 01Message
6.	Not able to create a project showing the message “Duplicate name”

## Expected behavior

New project should be create.

## Screenshots

![image](https://user-images.githubusercontent.com/16264167/114201663-be11b200-9956-11eb-885c-a0ee8ab0610e.png)

**Comment by benbrown** [comment]
Thanks for the report @rvinothrajendran. We're tracking a fix for this in the upcoming release.

**Comment by pavolum** [comment]
Initial triage notes:

Delete bot deletes the bot but not the full bot proj Dir. So when Composer indexes the file system it still sees the bot proj dir and does not allow the user to create a bot with the same name.

Naive solution is to change the delete logic to delete the whole bot dir but this is not an ideal solution on its own. When users select 'Delete Bot' in the settings page they may only be trying to delete that bot and not the whole bot proj. This flow needs to be rethought a bit.
