### ISSUE TITLE
The "provision completed" notification should include a deep link to the publishing action for that newly created environment

### ISSUE THREAD

**Issue by pavolum** [microsoft/BotFramework-Composer#6836]

**Comment by darrenj** [comment]
@emivers8, @Dewain27 Worth taking a look at this and my original issue. A deep link doesn't feel at first glance the right approach. If I choose to provision through a new publishing profile I would expect publishing of the bot to happen, if we think a user should choose, an up-front "publish my bot when finished" checkbox might be better than a deep link?
