### ISSUE TITLE
No "cancel" button to cancel a lengthy package installation process.

### ISSUE THREAD

**Issue by hcyang** [microsoft/BotFramework-Composer#6839]
## Describe the bug

It can be a lengthy process installing a new package and sometimes it's a indefinite wait, but there is no "cancel" button to stop the installing process. The only remedy is to close the whole Composer app or use Task Manager.

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by clearab** [comment]
Is this for installing a package, or for creating a new bot from a template?

**Comment by clearab** [comment]
In either case, if we provide a cancel option, we'd need to determine how/what to rollback. For packages, if the nuget/npm install command succeeds, but the dialog:merge command hasn't completed yet, what do we do if the user cancels? Do we uninstall the package? How do we recover if the user nukes Composer in the middle of dialog:merge running?

**Comment by hcyang** [comment]
The bug was about installing a package for an opened bot in Composer. Sometimes the installation process can keep going on without much feedback for the user whether the process has hung or not (it happens). Without any progress feedback nor a "cancel" button", the user can still kill the Composer process and create a half-done package installation situation as @clearab mentioned. It looks like Composer needs to have some "transaction" management logic to check the health of a bot codebase and maybe support roll-back. A "cancel" button can at least give Composer a chance to gracefully exit without render the bot in an messy state.
