### ISSUE TITLE
Azure Functions Deployment Misconfiguration

### ISSUE THREAD

**Issue by joshgummersall** [microsoft/BotFramework-Composer#6851]
## Describe the bug

Deploying a JS functions app to Azure does not currently work. Several settings are missing or misconfigured - see "Expected behavior" section below.

## Version

Built and run from `main` today (`ddc2a6784b362bf54f62a65f48886eb2eb8688f1`).

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Generate a new JS Blank bot using the Azure Functions variant
2. Publish bot to Azure

## Expected behavior

- `FUNCTIONS_WORKER_RUNTIME` should be `node` instead of `js`
- `AzureWebJobsStorage` is missing, should be a connection string for the Storage Account used to deploy the function, this leads to warnings about auto-scaling
- `WEBSITE_NODE_DEFAULT_VERSION` should possibly be set?

**Comment by GeoffCoxMSFT** [comment]
@joshgummersall 

- I am happy to set WEBSITE_NODE_DEFAULT_VERSION, but I have not idea what value to use.  Is there a way to determine this from the JS runtime?
- Can you tell me more about AzureWebJobsStorage? Is this meant to be a connection string to Cosmos DB or some other storage?
- FUNCTIONS_WORKER_RUNTIME we pull the runtime from the adaptive runtime key (e.g. adaptive-runtime-node-functions), so if it is being set to js then I think we have a bug in the runtime key value we are using.  @benbrown How is the runtime key set in the JS templates?

**Comment by joshgummersall** [comment]
* It's possible that the node default version is not required, though I think the default is something like Node v10 which is very old. https://github.com/projectkudu/kudu/wiki/Node-versioning explains the setting, the SDK is going to EOL v10 support at some point and it isn't supported by the Node maintainers anymore so it should like be 12+, ideally 14+.
* Docs for WebJobStorage: https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsstorage, this is a setting that is automatically configured when you create a function app in the Azure portal
* I used the runtime key that @benbrown suggested so hopefully it's not too tricky to add support for aliases or something. That key is set in the [generator code](https://github.com/microsoft/botframework-components/blob/main/generators/generator-bot-adaptive/generators/app/index.js#L188)
