### ISSUE TITLE
In Microsoft Bot Framework Composer, I can't publish back to PVA a bot that includes carousel layout for cards. Is this a defect ?

### ISSUE THREAD

**Issue by davidfischl** [microsoft/BotFramework-Composer#6852]

**Comment by lauren-mills** [comment]
@cwhitten - can you help assign the right person to investigate this?

**Comment by cwhitten** [comment]
@davidfischl can you please update the description with a bit more information? How to reproduce, perhaps the card payload itself, etc. 

There are no known issues publishing Adaptive Cards back to PVA.

**Comment by cwhitten** [comment]
Closing
