### ISSUE TITLE
Default package manager feeds

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#6854]
The split between the default feeds is confusing. We need to change the default feeds to just "NuGet" and "npm", and sort the search results by # of downloads. Having the extra search feeds is going to discourage use of community packages, and discourage their creation.

**Comment by clearab** [comment]
@benbrown we are good to move forward on this one.

**Comment by iMicknl** [comment]
@clearab would it be an idea to have a publisher column or an icon to indicate that a package has been published (and is governed) by Microsoft? Last time I had a look, it did only show the namespace and I am not sure if this will allow to distinguish official packages vs community packages. 

You can see the Publisher when you click on an item, but for NPM official packages seem to be published under 'BotFramework' where for 'Microsoft' is used on NuGet. A simple icon in the list with 'verified' or something else could help perhaps.

**Comment by clearab** [comment]
I agree that would be ideal - we've been working on designs for the next version of these screens and adding additional package data (and clearly displaying the publisher & if the publisher is verified) will be part of them.

**Comment by clearab** [comment]
NPM is a bit more difficult, as their search APIs are more limiting, but we definitely want to move in that direction.

**Comment by clearab** [comment]
Bumping to P0 - Orchestrator is taking a dependency on this - their package doesn't show up in the default feed currently (namespace issue)

**Comment by benbrown** [comment]
This is done in #7243
