### ISSUE TITLE
Extra /generated/interruption folder causing dialog:merge error

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#6855]
On a fresh empty bot, starting the bot in Composer creates a generated/interruption folder with a blank .lu and blank .qna file in it. Seems to be extraneous, and should not be creating these. Files then create a dialog:merge error.

## To repro

1. Create a new empty bot
2. Open the folders/files created on disk, notice no generated/interruption folder
3. Start the bot in Composer
4. Observe the created folders and files
5. Go to Package Manager
6. Click between Browse and Installed tabs, observe error given below (alternatively, attempt to install any package)

```
Could not load component list:Error multiple definitions of empty_5.en-us.lu in d:\trash\empty_5\empty_5\generated\interruption\empty_5.en-us.lu d:\trash\empty_5\empty_5\language-understanding\en-us\empty_5.en-us.lu Error multiple definitions of empty_5.en-us.qna in d:\trash\empty_5\empty_5\generated\interruption\empty_5.en-us.qna d:\trash\empty_5\empty_5\knowledge-base\en-us\empty_5.en-us.qna Error must have a merged .schema to merge .uischema files *** Could not merge components ***
```

**Comment by benbrown** [comment]
This should be fixed by the latest bf-dialog package:

see here: https://github.com/microsoft/BotFramework-Composer/pull/6849

**Comment by benbrown** [comment]
Confirmed resolved by @clearab
