### ISSUE TITLE
Create new resource instructions step 1 already completed

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#6860]
## Describe the bug

When creating new resources, it has a 3 step process detailed, but step 1 - "Sign in to Azure" - has already been done at this point.  

These instructions can be simplified to just show the last 2 steps - or sign in should not occur until the user hits next.

![image](https://user-images.githubusercontent.com/3900649/114368499-5eddb880-9b75-11eb-9fdb-73e6f482c249.png)

cc @Dewain27

**Comment by GeoffCoxMSFT** [comment]
Fixed by resolving #6562 since we have deferred sign in until the next step.
