### ISSUE TITLE
Copy - Test in Emulator, Open in WebChat

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#6864]
## Describe the bug

We should review the copy in the local bot runtime manager dialog. We have:

- Open Web Chat
- Test in Emulator

You test in WebChat too, perhaps align the two and have "Test in Emulator", "Test in Web Chat" ? @emivers8 ?

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/114381971-b08d3f80-9b83-11eb-9395-078703c52c1a.png)

**Comment by srinaath** [comment]
@mewa1024 Comment here?

**Comment by mewa1024** [comment]
@mareekuh another UI for the list (fwiw "Test" for both is fine with me)
