### ISSUE TITLE
Cannot install package - error related to conflicting packages

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#6865]
## Describe the bug

Attempted to install a package containing a dialog / schema.  The following error is shown and the dialog merge fails.

![image](https://user-images.githubusercontent.com/3900649/114382133-eaf6dc80-9b83-11eb-90e1-76730e4a5cdf.png)

**Full error text**

A problem occured during the install of this Component: Error conflicting definitions of Microsoft.IAdapter.schema Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime: C:\Users\gapretty\.nuget\packages\microsoft.bot.builder.dialogs.adaptive.runtime\4.13.0-rc4\content\Schemas\Microsoft.IAdapter.schema Microsoft.Bot.Builder.Integration.Runtime: C:\Users\gapretty\.nuget\packages\microsoft.bot.builder.integration.runtime\4.12.1-preview\content\Schemas\Microsoft.IAdapter.schema Error must have a merged .schema to merge .uischema files *** Could not merge components ***

## Version

Version:  1.4.0-nightly.233776.7019ef0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

cc @benbrown @carlosscastro

**Comment by benbrown** [comment]
This should be resolved by the latest version of the bf-dialog package. See here:

https://github.com/microsoft/BotFramework-Composer/pull/6849

**Comment by clearab** [comment]
Closing, long-term fix for this issue is being tracked here https://github.com/microsoft/botframework-components/issues/1016
