### ISSUE TITLE
QnAMaker creation experience is fixed to free tier

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#6866]
# Describe the bug

After creating a new bot you are prompted where needed to select/create QnAMaker/LUIS keys. When creating a new Qnamaker key it doesn't prompt you for pricing tier, it seems to default to free meaning that if you have exceeded your quota of free keys the feature doesn't work for you.

**Suspect the same issue applies to LUIS resources too.**

## Version

1.4.0-nightly.233776

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot (e.g. basic assistant)
2. In rocket ship UX select create a new key
3. Observe no pricing tier option shown
4. If your azure sub has more than 1? free tier qnamaker it will fail to create.

## Expected behavior

1. Pricing tier to be prompted for and used instead of hardcoded (?)

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/114382855-c9e2bb80-9b84-11eb-95c9-9e300b668840.png)

**Comment by Dewain27** [comment]
Free should provision:
QnA Maker - F0
Azure Search - F
App Service - F1
App Insights - Disabled

Paid should provision:
Same as what we do when we provision for Publishing Profile.

**Comment by cleemullins** [comment]
@Dewain27 If this is "By Design" we should reconsider the design. This is something everyone will hit, and it's not an optimal user experience.
