### ISSUE TITLE
"Network Error" when starting a bot with LUIS/QnA/skills

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6869]
Tried to run a bot that used to work with LUIS/QnA/Skills. Followed prompts to re-add LUIS/QnA keys. Started a build and hit the following.
Errors need more information. One cannot troubleshoot with this. I know my network is good. (streaming music, filing bugs, reading email...).

![image](https://user-images.githubusercontent.com/8867670/114429774-972fc780-9b72-11eb-93b5-d328d75eb428.png)

**Comment by scheyal** [comment]
Second time it worked, so cannot repro, but it'd be good to find where's the error and add more details.

**Comment by cwhitten** [comment]
@scheyal the next time this happens can you please start Composer in debug mode?

Set an environment variable in a shell: `DEBUG=composer*` and start the application from the shell. This will give more information.

**Comment by scheyal** [comment]
No repro since. 
Closing
