### ISSUE TITLE
Create QnA Maker bot Template configuration screen disappears when you leave composer and come back

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6871]
## Describe the bug

When you are creating a new bot from the QnA Maker template the post configuration screen disappears when you click away from composer and clicks back into composer.  There is no other way to get that configuration screen back either.

## Version

Version:  1.4.0-nightly.233776.7019ef0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

![SmallQnADisapperBug](https://user-images.githubusercontent.com/18688053/114432932-d700aa00-9b86-11eb-8b00-1dfd38f595f9.gif)

**Comment by benbrown** [comment]
I think what happened here is that you clicked "behind" the modal when clicking back on Composer, and thus dismissed that modal.

You can get back to it via the "Add new knowledge base" link in the navigation menu, as seen here:

![Uploading aQHvzpc3lL.gif…]()
