### ISSUE TITLE
Look into magic numbers in styles

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#6873]
There are quite a few places in which we have hardcoded numbers in styles ex Page component. It makes sense to move them into variables to understand why those static numbers came into the styling. This would help with readability and reusability (same heights are used across components. Same change as a result needs to be done in multiple places)

**Comment by beyackle** [comment]
This fits in nicely with the same complaint I had about colors, so I'd like to tackle those both as a single project.
