### ISSUE TITLE
Creating QnAMaker resource taking up to 20+ minutes

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6874]
## Describe the bug

Creating a QnA Maker resource through Composer is taking in excess of 20+ minutes.

## Version

Version:  1.4.0-nightly.233776.7019ef0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Bot
2. Add Knowledge Base
3. Generate QnA Maker instance
4. Process takes 20 minutes even to fail and tell you that you have too many free instances

## Expected behavior

Process completes quicker or is ASync to allow me to do other things.

## Screenshots

![image](https://user-images.githubusercontent.com/18688053/114440092-58f4d100-9b8f-11eb-8d9f-823fee8168d6.png)

**Comment by benbrown** [comment]
This is true, but it eventually succeeds. This seems due to the fact that the search resource takes a long time to be created.

What is the bug?
