### ISSUE TITLE
The /generated folder should be in /bin

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#6879]
If Composer is re-generating the files in this folder with every build, it seems like this artifact should be created in /bin or similar so that it doesn't appear to be a set of files I should be checking into source control (and showing up in the root of my bot project on disk).

**Comment by cwhitten** [comment]
The runtime template should instead provide a .gitignore that includes /generated.

Using something like `/bin` is a misnomer, even in the dotnet ecosystem, as it traditionally holds executable files. `obj` makes a bit more sense in this context, but it's a bikeshed argument to me. It only natural to dotnet developers.

**Comment by clearab** [comment]
@johnataylor, @tomlm or @peterinnesmsft I'm curious to what y'all think. If Composer is generating files as part of it's build process, where should they live on disk?

**Comment by thomas-chung** [comment]
Anecdotally - the /generated folder is one of the first thing I clean up when debugging issues with a locally deployed bot besides obj/ and bin/

The goal of the folder is not that immediate, and the appearance of the folder in the main bot project folder itself causes git to think that this is something that needs to be checked in. I was told by different folks on this team that the file doesn't need to be checked in. Thus in turn I just make sure I don't accidentally stage the files in generated/. We do actually have a .gitignore setup for the files in generated/* now so it doesn't always appear in our change lists. From a developer experience perspective, this seems sub-optimal to have a bunch of files generated not knowing what they are and what to do with it.

Personally this feels like a build artifact that should go into bin/ or obj/. I'd too be interested in knowing why the generated folder needs to be at the bot project folder level.

As a side note - the composer is also rather greedy in the files it touches. For example, when we open the Calendar and People skill sometimes it would for no reason end up touching a bunch of files that ends up showing in the change list. The diff shows blank line difference so it is not the most critical. However, this issue and the generated folder can really balloon someone PR check-ins, and feels somewhat less-than-ideal.
