### ISSUE TITLE
Composer Publish Flow Indicates region for channels registration, should be global

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#6880]
## Describe the bug

When creating a publish profile on one step we enumerate the resources being created.  If I choose brazilsouth, most resources, where valid were created in that region.  The Bot SErvice resource however is global and while you're choosing a region for the resource group you're not actually choosing one for the bot Service.

## Version

Version:  1.4.0-nightly.234246.528ea3e
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1) Create a bot publish profile for your bot in composer
2) Walk through to the review and create page
3) Note that the Microsoft Bot Channels Registration  has a region and should be global

## Screenshots

![image](https://user-images.githubusercontent.com/5997512/114460800-8bee9300-9b96-11eb-97cc-af816c5eb222.png)

**Comment by GeoffCoxMSFT** [comment]
@Dewain27 Can you specify what the behavior should be here? Given that we shipped this is R12 (1.4) and the wizard has a region drop down, what resources should have that region and which resources shouldn't?

**Comment by jameslew** [comment]
@GeoffCoxMSFT In this case it's just Azure Bot Service is a "global" resource rather than a regional resource.  That's the only change from what I see in the content.

**Comment by VamsiModem** [comment]
#7270
