### ISSUE TITLE
No warning/error if you don't have a subscription and try to create a publishing profile

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#6883]
## Describe the bug

When you sign in with an Azure account that doesn't have any directories or subscriptions, you can't select those drop downs. It doesn't give you a warning or error, you're just stuck and it's unclear what the problem is. 

Some new users, especially those who found their way to Azure via Composer (rather than the other way around) may not have created a subscription yet. Similarly, users who haven't used Azure for a while may have had their subscriptions deleted but aren't aware of this. And many users may not have a directory, which is not required, but the drop down appearing not to work is still confusing.

## Version

Version:  1.4.0-nightly.233776.7019ef0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
macOS

## To Reproduce

1. Go to add new publishing profile
2. Add name and target and click next
3. Login to Azure with an account that doesn't have active subscriptions or directories
4. Select create new resources, click next
5. Click on subscription or directory drop downs
6. Nothing happens, the drop downs acts like they have no contents

## Expected behavior

If the scibscription drop down doesn't populate the user should receive an error telling them to go to Azure and create a subscription. For the directory, that's not a require field but the user should get a message in the drop down like "_no directories found_". We need to provide recourse rather than leaving them hanging.

## Screenshots

![image](https://user-images.githubusercontent.com/55601267/114476908-12639e80-9bb0-11eb-86af-b898ad6535fc.png)

## Additional context

Again, this is specifically if you haven't yet created or been added to a subscription or directory (or if, like me, you accidentally sign in with a personal account :D ).

**Comment by pavolum** [comment]
I cannot repro this as I fail to auth with an account with no subscriptions and the logic is in place to warn if no subscriptions are made so if I were to be able to auth and the api called returned 0 subscriptions then error text should appear. 

I will try and repro by using the electron build

**Comment by pavolum** [comment]
So I could not repro in dev mode because it does not let you auth with AZ CLI. In electron you can auth with an account with no subscriptions/directories and the error info renders as expeced. Going to follow up with @em to see if she can repro and if not we will close. 
![image](https://user-images.githubusercontent.com/22845013/116124205-fec93500-a691-11eb-9a8d-cb6dcc5a234d.png)

**Comment by pavolum** [comment]
Em has validated that the correct error is surfaced in this scenario and this issue can be closed
