### ISSUE TITLE
Prompted for Azure login twice in a row

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#6884]
## Describe the bug

When going to creating a publishing profile, I'm prompted to login. I successfully login, but the login panel pops up again. This happens inconsistently. If I close it the second time, I am already logged in. But it's confusing.

## Version

Version:  1.4.0-nightly.233776.7019ef0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
macOS

## To Reproduce

1. Go to add a publishing profile
2. Select create new resources
3. Get Azure login prompt, go through sign in successfully
4. A second prompt often appears immediately after (you can see "Sign out" in the modal behind in the screenshot below)

## Expected behavior

After successful login I should be back in the modal, not prompted to login again.

## Screenshots

![image](https://user-images.githubusercontent.com/55601267/114477944-0c6ebd00-9bb2-11eb-842e-102dfef60aab.png)

## Additional context

This doesn't always happen, but more often than not.

**Comment by a-b-r-o-w-n** [comment]
@GeoffCoxMSFT Just now seeing your previous comment. I'll test this again today.

**Comment by benbrown** [comment]
@a-b-r-o-w-n any thoughts on this?

**Comment by a-b-r-o-w-n** [comment]
My best guess at this point in time is that OneAuth is treating two authentication calls as separate sessions (one to get list of tenants, the other to get an arm token for the selected tenant).

**Comment by a-b-r-o-w-n** [comment]
I just tested this again on the latest and was only prompted once to login when creating a new publishing profile. @emivers8 can you try testing this?

**Comment by emivers8** [comment]
Still prompting twice on the latest nightly. If I close it now without going through auth again, I get this:

![image](https://user-images.githubusercontent.com/55601267/116147379-81eb8a80-a694-11eb-8c60-ba557da17591.png)

It's populating the azure directory, but gives me that error and doesn't populate the subscription so I'm blocked.

**Comment by a-b-r-o-w-n** [comment]
@emivers8 what version?

**Comment by emivers8** [comment]
Version:  2.0.0-nightly.239198.1de395f
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by emivers8** [comment]
(I also crashed the app by trying to double check that I had the latest while the provisioning modal was open.)

**Comment by benbrown** [comment]
Is this still happening?  Can this be fixed?  It has been hanging out in "in progress" for a long itme

**Comment by emivers8** [comment]
Didn't happen today. Maybe keep it open but assign to R14 so if I get it again I can update? It happens inconsistently, but apparently not to anyone else, so maybe not so important.
