### ISSUE TITLE
Sign in modal in provisioning flow

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#6885]
## Describe the bug
The sign in modal in provisioning flow appears as soon as user selects "configure resources", however we decided this was not the right behavior since user does not need Azure sign in for 'importing & hand off". Thus sign in modal should get triggered only when user selects "Create new resources" and clicks next on the modal

## Version
v1.4.0-nightly.233463.bc20573

## Browser

- [x] Electron distribution

## OS

- [x] macOS

<img width="1217" alt="Screen Shot 2021-04-12 at 5 15 28 PM" src="https://user-images.githubusercontent.com/67944302/114478551-599f5e80-9bb3-11eb-8da1-2747ef2ae2b8.png">

**Comment by Dewain27** [comment]
Duplicate Item.  Issue has been resolved in latest build.
