### ISSUE TITLE
Add resource fit and finish

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#6890]
![Frame 61661](https://user-images.githubusercontent.com/67944302/114479954-640f2780-9bb6-11eb-9f8b-421f085fb321.png)

- Learn more link: https://aka.ms/composer-publish-bot#create-new-azure-resources
- Q&A maker icon is missing in the list https://iconcloud.design/search/filter/Azure%20Icons/all/Q&A%20maker/e31aa438e-de64dd68d

**Comment by Dewain27** [comment]
@emivers8 has recommended that we leave this as is for width.  Only add the Learn More link.
