### ISSUE TITLE
Cannot create a new bot

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#6891]
<img width="1155" alt="Screen Shot 2021-04-12 at 5 51 04 PM" src="https://user-images.githubusercontent.com/67944302/114480601-b43ab980-9bb7-11eb-91c4-0df25b2223d2.png">

**Comment by rvinothrajendran** [comment]
@JaskeeratBedi-cmk Have you installed node.js ?

**Comment by Dewain27** [comment]
@JaskeeratBedi-cmk we need to get your Version and repro steps.  Please ensure that you have node.js installed as well.

**Comment by JaskeeratBedi-cmk** [comment]
Checked again today & was able to create new bot..
My new app version is: v1.4.0-nightly.233776.7019ef0
