### ISSUE TITLE
Error: req.body.path.replace is not a function when trying to connect to existing skill.

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6892]
Try to connect to existing skill by selecting it from filesystem.
Error message doesn't help troubleshoot the issue.

![image](https://user-images.githubusercontent.com/8867670/114480787-1693ba00-9bb8-11eb-954b-19aa23317180.png)

**Comment by scheyal** [comment]
Steps:
* create a skill
* Start a new (or open another solution)
* Add / Open an existing skill
* Boom

**Comment by srinaath** [comment]
Closing as fixed here #6800
