### ISSUE TITLE
publish profile with "" setting for some items will cause bot runtime error

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#6894]
- electron nightly latest (new adaptive runtime)
- create a bot 
- run bot successfully
- imported existing publish profile as below
![image](https://user-images.githubusercontent.com/43408889/114495771-4347e000-9c51-11eb-9490-dfb0f6042119.png)
- runt bot will hit "invalid URI: The format of the URI could not be determined"

With @luhan2017 's help, we found that either "<>" placeholder or "" setting in publish profile for cosmosDB and also other items will introduce this regression.

**Comment by GeoffCoxMSFT** [comment]
@Dewain27 Yes if the imported profile has bad values then the bot won't work.  To me this seems like by design. What change to the code is expected here to resolve this?

**Comment by hibrenda** [comment]
This used to work . so should we tolerant these bad values? at least we'd better support <> placeholder and "" setting.  Otherwise it will confuse customer once they hit above issues.

**Comment by luhan2017** [comment]
@GeoffCoxMSFT  Maybe we can fix that in composer by removing the settings with empty/placeholder value when merging the appsettings.json during publish.
