### ISSUE TITLE
Rocketship placement most prominent right, expected that to be notifications (as in neutral home)

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#6897]
## Describe the bug
Composer home shows my notifications in the app bar as most right. Once, I start to add/open a template the rocketship takes over the notifications place. I would expect notifications to be present in most right position consistently. 

## Version
![image](https://user-images.githubusercontent.com/43533472/114574728-8c685600-9c8a-11eb-89d0-1a31c04fb94f.png)

## Screenshots
home:
![image](https://user-images.githubusercontent.com/43533472/114574946-c2a5d580-9c8a-11eb-9d78-0fc8055907e3.png)

In design mode: 
![image](https://user-images.githubusercontent.com/43533472/114574904-b7eb4080-9c8a-11eb-9e5c-c0db04381836.png)

**Comment by emivers8** [comment]
Yep, this is designed to be consistent throughout the app. When you don't have a bot project open, the next steps should be this (learning is the same): 

![image](https://user-images.githubusercontent.com/55601267/114609722-f4e81080-9c53-11eb-8353-a6f1feeb49c6.png)

This should go away and be replaced with the normal next step contents once a bot project is open.
