### ISSUE TITLE
Localhost skill manifest is inaccessible in composer but it is in browser

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6899]
While developing a skill we need to access a localhost skill manifest. See below how skill manifest is available in browser but inaccessible in Composer.

![skillmanifest](https://user-images.githubusercontent.com/8867670/114579645-eb9a7c00-9c32-11eb-831c-fe24a9ccda1e.png)

**Comment by benbrown** [comment]
This is due to a recent change that caused the manifests to no longer be copied into wwwroot during local publish.

**Comment by tdurnford** [comment]
@benbrown if the skill manifest is no longer copied to the wwwroot, how are developers expected to access it going forward?

**Comment by cwhitten** [comment]
@luhan2017 can you look at this as part of the skill manifest updates

**Comment by luhan2017** [comment]
@scheyal, this is due to invalid json, missing a "," between endpoint local 3982 and local 3978. @VanyLaw can we correct the error message?
