### ISSUE TITLE
Provide the option to Rename the bot

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#6905]
## Describe the solution you'd like

give the option to rename the bot name

## Additional context

![rename](https://user-images.githubusercontent.com/16264167/114602162-955f2480-9c96-11eb-91c0-134804433150.jpg)

**Comment by cwhitten** [comment]
Hello @rvinothrajendran - thank you for the feature request. We'll add this to our backlog for now and seek to prioritize it. It does not sit on our current roadmap.

**Comment by SuryaKorivipaduPractice** [comment]
I'm also looking for this feature.
