### ISSUE TITLE
Edit publishing profile

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#6908]
When I try to edit my existing publishing profile, and want to create new resources, I am asked to configure resources. In this screen, everything is disabled & the region selection for Luis is not working ( see attached)

![Screen Shot 2021-04-13 at 11 46 40 AM](https://user-images.githubusercontent.com/67944302/114604717-1b0ab200-9c4e-11eb-8934-6fdfb9342751.png)

**Comment by benbrown** [comment]
I believe those fields are disabled because they are already set in a previous session.  It's weird that the current value is not displayed in those disabled

**Comment by GeoffCoxMSFT** [comment]
This is a result of a bug that was active when the profile was created where the tenant ID was not properly saved to the profile.  That bug is fixed so future profiles created will not have this behavior.
