### ISSUE TITLE
Missing LUIS error shows up when adding a skill & selecting orchestrator.

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6909]
* Go through add remote skill wizard. 
* Accept all or some intents
* Allow orchestrator to be recognizer in multibot scenarios
* accept
* Boom : missing LUIS key shows up. The bot worked fine before (don't remember if I already had LUIS keys or didn't need it due to using Orchestrator).

**Comment by scheyal** [comment]
Also, Orchestrator was not installed. (may be related).

**Comment by scheyal** [comment]
see #6910

**Comment by cwhitten** [comment]
@scheyal what recognizer type is used in the skill?
