### ISSUE TITLE
New add remote skill experience doesn't install Orchestrator

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6910]
* Go through adding new skill experience.
* Accept Orchestrator as default multibot root recognizer
* Boom: Recognizer doesn't get installed.

**Comment by cwhitten** [comment]
@luhan2017 is this part of the scenarios you are working on?

**Comment by cwhitten** [comment]
@VanyLaw https://github.com/microsoft/BotFramework-Composer/pull/6640 doesn't clarify if the Orchestrator package is also installed if necessary

**Comment by srinaath** [comment]
@taicchoumsft Does #6640 install the orchestrator package?

**Comment by taicchoumsft** [comment]
@srinaath, yes #6640 installs orchestrator package for the remote skill scenario if user selects it.

**Comment by taicchoumsft** [comment]
Discussed with @scheyal , closing this bug for now, will circle back when #6640 is in main.
