### ISSUE TITLE
Home Screen layout on desktop monitors needs some refinement

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#6913]
## Describe the bug
We should consider adjusting our media queries to better layout the home page on external monitors.  See attached screenshots

## Version
Version:  1.4.0-nightly.234673.12e1a8a
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. You'll need a system that has an external monitor.  The monitor I am testing against is a 27" external display
2. Launch Composer
3. Make the Composer application full screen

## Expected behavior
I would expect the Title to remain at the very top.
the Recent Bots, Resources, and Latest Visions to be left justified below the title
the What's new panel on the right to be width appropriate

## Screenshots
This is an example of the Home Screen displayed full screen on a 16" macBook

<img width="896" alt="Screen Shot 2021-04-13 at 12 32 58 PM" src="https://user-images.githubusercontent.com/733559/114610100-64f69680-9c54-11eb-9826-eddbf586507e.png">

This is an example of the Home Screen displayed full screen on a 27" external monitor
<img width="2553" alt="Screen_Shot_2021-04-13_at_12_34_13_PM" src="https://user-images.githubusercontent.com/733559/114610378-adae4f80-9c54-11eb-98c8-9019a2140812.png">

Here are some other media query breakpoints:
<img width="1282" alt="Screen Shot 2021-04-13 at 12 44 34 PM" src="https://user-images.githubusercontent.com/733559/114611551-03cfc280-9c56-11eb-930e-ee5459a54ef5.png">

**Comment by xiyangdesign** [comment]
This bug should go away when the next nightly build has the latest PR merge.

**Comment by cwhitten** [comment]
Closing as this is now in a shippable state
