### ISSUE TITLE
Selection of publish profile in connections tab: shows no pop-up to select 

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#6915]
## Describe the bug
The dropdown does not let me select my publishing profile, just showing plain text after selection of 'manage profile' 

## Version
![image](https://user-images.githubusercontent.com/43533472/114616840-69549b00-9cb8-11eb-959c-3a366d21be95.png)

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/114616735-44f8be80-9cb8-11eb-947e-5760f0a3f9eb.png)
By clicking on the "blue" action test manage profiles, I just get the plain text no pop up:
![image](https://user-images.githubusercontent.com/43533472/114616799-5c37ac00-9cb8-11eb-8dfe-c1a1ab4fb704.png)

**Comment by Dewain27** [comment]
Duplicate already fixed in daily build
