### ISSUE TITLE
Package manager search options is not working in the same format.

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#6916]
## Describe the bug

Package manager search options is not working in the same format.

## Version

Version:  1.4.0-nightly.234673.12e1a8a
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Refer the video
1. In the browse tab search the "welcome" & Its displaying "welcome" package
2. switch to another tab ... displaying all the option(search text is present & not to filter)
3. In same tab removed the search query
4. back to "Browse tab" display only welcome package(still showing search items but search text is empty)

## Expected behavior

Package manager search options should work same format 
Incase If user switch to different tab , clear the search text & display all the items or filter the package based on the search. ( vice - versa)

## Screenshots

https://user-images.githubusercontent.com/16264167/114617032-e4fa1c00-9ca7-11eb-9e0d-90ed1362fe1c.MP4

**Comment by benbrown** [comment]
Thanks for the bug report @rvinothrajendran.  We will include a fix for this in an upcoming release!
