### ISSUE TITLE
Publish: copy manifest URL copies the api/messages url - not the manifest one

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6917]
A. The copy manifest URL does not copy the manifest url rather the messages/api url. 
For example:
https://theskill.azurewebsites.net/api/messages
I expected the following:
https://theskill.azurewebsites.net/manifests/TheSkill-2-1-manifest.json

B. The text in the UI is truncated too early. (fit & finish).

See image:

![image](https://user-images.githubusercontent.com/8867670/114622203-82caf800-9c62-11eb-890a-79385fa12714.png)

**Comment by luhan2017** [comment]
@scheyal  which electron version are you using, we should fixed this in the private electron for skill experience which we shared in the skill v-team group.

**Comment by luhan2017** [comment]
should be fixed in the latest main branch.
