### ISSUE TITLE
Add dialog requires QnA

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6919]
Simple add dialog in a new solution results with:
 
(2 of 3, I think 1 was similar about LUIS, 3rd is the standard error below)
![image](https://user-images.githubusercontent.com/8867670/114628403-a7779d80-9c6b-11eb-8c5a-a911d45d37f8.png)

![image](https://user-images.githubusercontent.com/8867670/114628522-d4c44b80-9c6b-11eb-9dab-67e3f99c16ed.png)

**Comment by boydc2014** [comment]
@liweitian can you help take a look at this one?

**Comment by liweitian** [comment]
@scheyal, I cannot reproduce this on my side. But it seems the dialog you create does not have a name. 
The error should be No QNA FILE WITH NAME {a dialog name}. Could you introduce the steps you did to reproduce the bug and share the bot here would be helpful.

**Comment by boydc2014** [comment]
Close this as out-of-date
