### ISSUE TITLE
Skill: consumer cannot select endpoint in dropdown

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6921]
Add / connect  a remote skill with 3 endpoints
Create a new box to access externa resources: connect to a skill
Select an enpoint. 
Boom: It isn't selected
Bot fails accordingly

https://microsoft-my.sharepoint-df.com/:v:/p/eyals/EeHpy2H-j5lJs992ABOYgKwBde74okDJopAwuc1p6y-lvg?e=mKjnAF

**Comment by darrenj** [comment]
Looks like the same as #7153

**Comment by cwhitten** [comment]
Closing as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/7153
