### ISSUE TITLE
Composer white-screens if you add a non-supported or supported locale

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#6922]
## Describe the bug
If you add an unsupported locale folder to a project Composer white screens

## Version
Version:  1.4.0-nightly.234518.8e98823
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

N/A

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot project
2. In file explorer (or finder) navigate to the project
3. open the language-generation folder
4. make a copy of the `en-us` folder and rename it to `en-uk` 

## Expected behavior
I'd expect composer to give some kind of error/warning saying it's detected an unsupported locale type 

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/114629872-338ac480-9c6e-11eb-9e09-5452b35b6c2f.png)

## Additional context
The nasty part here is even if you delete the badly formatted folder, close and reopen composer the project still white screens. It appears as though the project is unrecoverable. I should also add this bug forces you to close and reopen composer since it's not possible to do anything else. 

Additional note:
I just tried adding a [supported locale](https://github.com/microsoft/BotFramework-Composer/blob/01d26ef7dd8f2add93674402912ef9d523b52392/Composer/packages/client/src/locales.ts#L10) (af-na) to a empty bot project and Composer white-screened again. 

Here's the project that I used.
[emptyLGTest.zip](https://github.com/microsoft/BotFramework-Composer/files/6307321/emptyLGTest.zip)

**Comment by cwhitten** [comment]
@sangwoohaan are you able to provide us a global error notification for these unseen scenarios?

**Comment by sangwoohaan** [comment]
Ok I will work on this.

**Comment by srinaath** [comment]
Closing this bug as it was a transient bug in one of the nightlies. For now, we can continue using the ErrorBoundary to show the unhandled exceptions. @sangwoohaan  what do you think? Do u see the need for a new design for surfacing global errors?
