### ISSUE TITLE
regex implementation in composer

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-Composer#6928]
Hi,

I have below javascript regex function  which will give only number from the given input string.
![image](https://user-images.githubusercontent.com/36945600/114662805-f2022400-9d16-11eb-9395-0c6e2e6b6e78.png)
Is there any suitable function related above present in composer. The same I want to implement in composer can you suggest me steps on achieving above scenario in composer..

Thanks....

**Comment by cwhitten** [comment]
Hello @madbeher - please use stackoverflow for these types of how-to questions. https://stackoverflow.com/questions/tagged/botframework

Thanks
