### ISSUE TITLE
Command failed: dotnet user-secrets init --project conversational_core1.csproj 'dotnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by pamidis** [microsoft/BotFramework-Composer#6930]
Hi,

while creating BOT using BotFramework-Composer.
Received this error message.
Please help.

![image](https://user-images.githubusercontent.com/82510609/114698773-10394580-9d52-11eb-9cce-bdf1614cf202.png)

![image](https://user-images.githubusercontent.com/82510609/114698629-e718b500-9d51-11eb-9e0e-9f1da9051bf7.png)

**Comment by benbrown** [comment]
Dotnet 3.1 is required to run Composer bots.

In our next release, this error will cause a nice popup warning about dotnet to appear rather than this error.
