### ISSUE TITLE
Whitescreen after project creation

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#6932]
## Describe the bug

Composer shows a whitescreen after creating a new project based on basic assistant or enterprise assistant template

## Version

1.4.0-nightly.234969

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Steps to reproduce the behaviour:

1. Create new Bot
2. Choose basic assistant template or enterprise assistant template
3. Wait for creation process to finish
4. Whitescreen is shown, have to restart Composer to get back to Composer UX

Note that the projects appear to be created, however opening any of the three projects created results in the white-screen

![image](https://user-images.githubusercontent.com/33519520/114721292-b4aa9000-9d30-11eb-98a7-9eb37561dc1f.png)

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/114711310-b4a59280-9d26-11eb-967d-6d477474ec98.png)

![image](https://user-images.githubusercontent.com/33519520/114713562-28e13580-9d29-11eb-88e2-f679c335468b.png)

**Comment by cwhitten** [comment]
Did not see the issue on:

```json
Version:  1.4.0-nightly.234673.12e1a8a
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```

I did see the issue on:

```json
Version:  1.4.0-nightly.234969.d950804
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```

with the following error in the console

```text
react-dom.production.min.js:5058 TypeError: Cannot read property 'type' of undefined
    at o (schemaUtils.js:25)
    at u (schemaUtils.js:83)
    at Object.t.discoverNestedPaths (schemaUtils.js:104)
    at f (walkAdaptiveDialog.js:36)
    at f (walkAdaptiveDialog.js:62)
    at f (walkAdaptiveDialog.js:62)
    at Object.t.walkAdaptiveDialog (walkAdaptiveDialog.js:16)
    at t.validateSchema (index.js:27)
    at diagnosticsPageSelector.ts:198
    at Array.forEach (<anonymous>)
Zl @ react-dom.production.min.js:5058
shared.ts:28 Error: {}
a @ shared.ts:28
api/publish/45146.374030741266/status/default:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api/publish/20173.78979893105/status/default:1 Failed to load resource: the server responded with a status of 404 (Not Found)
api/publish/9301.313915599963/status/default:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by cwhitten** [comment]
@yeze322 it looks like something crept in on the phase 2 migration pr that may be causing this.

**Comment by clearab** [comment]
Also seeing this for Calendar and People templates

**Comment by yeze322** [comment]
Located the problem, need to check the schema definition tomorrow.
