### ISSUE TITLE
Add button to translate text resources using external translation service

### ISSUE THREAD

**Issue by Clooney24** [microsoft/BotFramework-Composer#6933]
It would be helpful to be able to confige the integration of an external translation service (Microsoft Translator, DeepL, Google Translate) to translate text resources  in bot responses and user input sample phrases by just one click primary language in one or many secondary languages.

**Comment by cwhitten** [comment]
Hi @Clooney24 and thank you for the feature request! We'll consider this for our roadmap. No plans to implement this at the moment.
