### ISSUE TITLE
Notifications get hidden when rocket panel is open

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#6935]
Electron App: v1.4.0-nightly.234518.839bb23
Mac OS
Steps to reproduce

- create new bot
- create new publishing profile > create new resources > complete

The notifications are getting hidden under the rocket panel ( see attached)

Expected behavior is that once user is done with the modal, the rocket panel should close and user should be able to see notifications of their publishing profile being created.

![Screen Shot 2021-04-14 at 8 28 36 AM](https://user-images.githubusercontent.com/67944302/114737064-8199d980-9cfb-11eb-843c-421f30c9af1a.png)

**Comment by benbrown** [comment]
this has been fixed
