### ISSUE TITLE
Global notification when provisioning + publishing

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#6937]
Provisioning & publishing can take longish time. If user navigates to a different page in Composer, they should know that the application is still provisioning or publishing in the background.

![Screen Shot 2021-04-14 at 8 42 08 AM](https://user-images.githubusercontent.com/67944302/114739006-5adca280-9cfd-11eb-9b10-58c834d1b82e.png)

**Comment by cwhitten** [comment]
@JaskeeratBedi-cmk a notification gets sent to the global notifications panel when the process starts, and will persist on the screen until the user dismisses it, right? Are you expecting something different than this?

**Comment by JaskeeratBedi-cmk** [comment]
The notification panel once dismissed does not give any indication in the header ( i.e. no badge with status is visible when user moves to another page). This is something that we would like to improve moving into R14.

**Comment by mewa1024** [comment]
The UX behavior described in #7805 should fix this issue as well. Closing this as a dupe.
