### ISSUE TITLE
Using exported LG functions show as warning in Composer

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotFramework-Composer#6945]
## Describe the bug

When a function is exported from an LG file it can be used in trigger expressions.  Composer currently reports that as a warning.

## Version

Version:  1.4.0-nightly.234969.d950804
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce

This describes 

1. Create an empty bot
2. Add an exported function to common.lg
```
> !# @Namespace = form
> !# @Exports = priority

# priority
- ${3+4}
```
2. Click on Greeting trigger and change priority to `=form.priority()`
3. You get a warning even though it runs fine.

![image](https://user-images.githubusercontent.com/17637681/114754398-646e0680-9d0d-11eb-8090-ad4db7eb43db.png)

## Expected behavior

Exported functions should not get a warning.

## Additional context

Form generation will always get warnings because of this bug.

**Comment by chrimc62** [comment]
@cwhitten is this likely to be addressed in R14?  Or are you waiting for the export of all LG functions?

**Comment by cwhitten** [comment]
@chrimc62 I feel a potential design change in declarative layer is to model custom functions (and custom memory, for that matter). We aren't doing anything with this in R14.
