### ISSUE TITLE
Fonts incorrectly rendered during install screen on 4k monitor (Windows 10)

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6946]
## Describe the bug

When installing Composer on Windows with a 4k screen with 200% scaling, the installation screen looks quite poor. Note that these are default settings for physically large screens. 

All the fonts inside the setup window are rasterized and look incomplete. 

## Version

Nightly Build, 
BotFramework-Composer-1.4.0-nightly.234969.d950804-windows-setup.exe

## Browser

N/A, using the setup.exe to setup Composer

## OS

- [ ] macOS
- [x] Windows (All patched, up to date)
- [ ] Ubuntu

## To Reproduce

1. Install Composer on a Windows Machine with a 4k screen. 
2. The setup screen (graphic below) has fonts and graphics that are not properly rendered / scaled. 

## Expected behavior

* The "Bot Framework Composer Setup" words in the Window title are cleanly rendered. 
* The "Installing, please wait" text is not rendered correctly, nor is any of the text inside the window.

Clear fonts, clear graphics. 

## Screenshots
On the initial screen:
![image](https://user-images.githubusercontent.com/1165321/114754657-ad25bf80-9d0d-11eb-9be3-1d03528f0d9a.png)

On the final screen:
![image](https://user-images.githubusercontent.com/1165321/114755653-c0855a80-9d0e-11eb-862a-c8d795ff1792.png)

**Comment by srinaath** [comment]
@cleemullins We are currently using the default electron-builder experience in the installers. We could build our own UI screens here but it is a significant amount of work to override this.
