### ISSUE TITLE
Incorrect / Out of Date "What's New" section in nightly builds

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6947]
## Describe the bug

Fresh install of Composer Nightly build. The "What's new" section is quite out of date. 

Each of the "What's new" below needs to be revved. 

1. "Bot Framework Composer 1.3" 
2. Build 2020 updates
3. November 2020 - Conversational AI update
4. Conversational AI at Microsoft Ignite 2020

## Version

Latest Nightly build
BotFramework-Composer-1.4.0-nightly.234969.d950804-windows-setup.exe

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer
2. Read the "What's new" section.

## Expected behavior

Updated "What's new" text referencing Composer 1.4.x and Build 2021 events. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114756072-35f12b00-9d0f-11eb-9311-c208132e364c.png)

**Comment by srinaath** [comment]
@garypretty This content from the feed needs updating.

**Comment by garypretty** [comment]
Closing this as the content is driven by a feed and we will be updating this ahead of Build with more recent blog posts and videos.
