### ISSUE TITLE
Incorrect Bug Template

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6948]
## Describe the bug

The Bug Template here tells me to add in a SHA1 hash found in the about screen. 

Note: There are *2* about screens, and I didn't even see the Help | About screen. That screen also does not have a SHA hash. :) 

## Version

The "About" screen above does not have a SHA hash as described above. 

![image](https://user-images.githubusercontent.com/1165321/114756705-e2cba800-9d0f-11eb-9e42-29216b7b588b.png)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to the About screen in Composer. 
2. Notice there is no SHA hash, as the bug template says there should be. 

## Expected behavior

Accurate "How to report the version" text in the bug template. 

Note: Normally I would just update the template rather than filing a bug like this and making work for others, but I'm not sure what the behavior should be.

**Comment by srinaath** [comment]
Currently this info is available in system Help --> About menu. But makes sense to move it here.

**Comment by cleemullins** [comment]
There is no "SHA" anywhere on the "Help | About" menu. 

![image](https://user-images.githubusercontent.com/1165321/114913190-c3974e00-9dd5-11eb-9e5f-2281e326d78e.png)

**Comment by mewa1024** [comment]
Can we update the "Release" section of the page to include the nightly version, rather than 1.4.0:
![image](https://user-images.githubusercontent.com/39317542/115297528-214ad380-a111-11eb-85c8-7f139b5a17dd.png)

**Comment by srinaath** [comment]
Closing it as addressing in #7121
