### ISSUE TITLE
About screen has incorrect text 

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6952]
## Describe the bug

On the "About" screen there is text that reads: 
> "This Page contains detailed information about your bot. For security reasons, they are hidden by default. To test your bot or publish to Azure, you may need to provide these settings"

The "About" Tab, on the About screen DOES NOT contain any such information. 

This text should be on the "Application Settings" tab, not on the broader shared "About" screen. 

## Version

Nightly. 
BotFramework-Composer-1.4.0-nightly.234969.d950804-windows-setup.exe

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to About screen
2. Select the About Tab on the About screen
2. Read text on top, just under the word "About". See screen shot below. 
3. Wonder "Why is this text here'. 
4. Realize this text applies to the Application Settings tab, not the About tab. 

## Expected behavior

Have tis text only on the Application Settings tab. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114762958-24ac1c80-9d17-11eb-9e91-fbaceb6c726c.png)

**Comment by mewa1024** [comment]
Yikes. Please remove this text altogether. (@emivers8 I'm guessing it's okay for us to delete this text instead of moving it to the project settings section?)

**Comment by emivers8** [comment]
Uhhh yeah, I don't see any purpose for that. Good find, @cleemullins.

**Comment by srinaath** [comment]
Fixing in #7121
