### ISSUE TITLE
"About" is 3x redundant on the About Screen

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6953]
## Describe the bug

The word "About" shows up 3 times on the about screen. See screen shot below. This needs to be copy-edited and cleaned up. 

Note: There is *ALSO* a "Help | About" screen that is something different. These should be reconciled. 

## Version

Composer Nightly. 
BotFramework-Composer-1.4.0-nightly.234969.d950804-windows-setup.exe

## To Reproduce

1. Go to About screen
2. Read the word "About" 3 times. 

## Expected behavior

The design language here needs to be cleaned up. 

## Screenshots
![image](https://user-images.githubusercontent.com/1165321/114763695-f24eef00-9d17-11eb-8499-5ee0698874d8.png)

**Comment by srinaath** [comment]
Closing as we are encapsulating all About screen design issues #7121
