### ISSUE TITLE
Copying editing on About Screen missing "."

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6954]
## Describe the bug

On the about screen is the text:
> This Page contains detailed information about your bot. For security reasons, they are hidden by default. To test your bot or publish to Azure, you may need to provide these settings

There needs to be a "." at the end, after settings. 

## Version

Composer Nightly. 
BotFramework-Composer-1.4.0-nightly.234969.d950804-windows-setup.exe

## To Reproduce

1. Go to About screen. 
2. Read the text under "About"
3. Notice the missing "." at the end. 

## Expected behavior
Grammar cleanup. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114764212-84ef8e00-9d18-11eb-880c-9b92e0e7524c.png)

**Comment by srinaath** [comment]
Fixed here in #7030
