### ISSUE TITLE
Menu Items ("File", "Edit", "View", "Windows", "Help") do not honor Windows font / size selections

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6957]
## Describe the bug

The main menu across the top of Composer doesn't honor the Windows settings around fonts & sizes. 

In the screen shot below, see that:
1. The Menu in Composer is too small. 
2. The Menu in VS Code is quite a bit larger. 
3. The rest of the text in Composer is correct. 

## Version

Nightly Build.

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

My Windows settings around this are:
![image](https://user-images.githubusercontent.com/1165321/114766341-24ae1b80-9d1b-11eb-8172-4fd58c3e044a.png)

## Expected behavior

Menu item across the top should follow the Windows settings, similar to VS Code and other applications. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114765946-a3ef1f80-9d1a-11eb-9ecb-516d3b8ee741.png)

**Comment by srinaath** [comment]
@cleemullins VSCode uses HTML to render the top navigation menu. We use the electron-builder one. But definitely we will consider this in the upcoming releases.

**Comment by cleemullins** [comment]
@srinaath The other text on the screen ("Home" / "Design" / "Bot Responses" / etc) all honors the Windows sizes / zooming correctly. It's only the Menu items that appears to be incorrect.

**Comment by srinaath** [comment]
@cleemullins  Aah. Yep. https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/client/src/utils/pageLinks.ts#L34. The left nav we use HTML to drive the structure. 

The top nav we are using the native electron menu. https://github.com/microsoft/BotFramework-Composer/pull/4161/files#diff-c5a6dc260ef9f6a83f951ea701edbea94ce0ba7caf750a46d9501c56a970c576R71

**Comment by mewa1024** [comment]
(Removing the "UX Design" label since it sound like this is an Electron issue that needs no additional design work. Please @ mention me if that is not the case.)
