### ISSUE TITLE
MENUBAR ("File", "Edit", "View", etc) needs to follow standard app patterns

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6959]
## Describe the bug

The Windows standard is to have "File | New" and "File | Open" menu items. Composer has a menu, but the "File" menu only has exit. 

1. "File New" should be the same as clicking "New" on the main screen. 
2. "File Open" should be the same as clicking "Open" on the main screen. 

Teams solves this by eliminating the menu bar for their app. 
VS Code solves this by implementing "File | New" and "File | Open". 

## Version

![image](https://user-images.githubusercontent.com/1165321/114772503-bc633800-9d22-11eb-9e81-1c8146fc27cd.png)

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer. 
2. Observe the giant "+ New" in the middle of the screen. 
3. Go to the "File" Menu. 
4. There is no "New" item there. 

## Expected behavior
File New should be present. 
File Open should be present. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114772233-6abaad80-9d22-11eb-9543-f5976d779657.png)

**Comment by mewa1024** [comment]
@JaskeeratBedi-cmk created a design for the menu a semester ago. I think it addresses the File menu, as well as aligning the other menus with other Microsoft products. 

Image:
![image](https://user-images.githubusercontent.com/39317542/115285122-5ac81280-a102-11eb-9cda-49208790c4a8.png)

Link to the frame in Figma: 
https://www.figma.com/file/J3oIdXDmeBQbAe4a4PYbQc/Jaskeerat-s-files?node-id=3737%3A48

@srinaath, do you think can we get these changes in for R13?

**Comment by mewa1024** [comment]
(Removing the "UX Design" since the design work has been done.)

**Comment by cwhitten** [comment]
No plans to take this in R13

**Comment by mewa1024** [comment]
Okay that I labeled as R14 then?

**Comment by mewa1024** [comment]
Updated the menus to include Alt key shortcuts per #6960:

![image](https://user-images.githubusercontent.com/39317542/124066006-bbba7380-d9ec-11eb-8825-b147a9cdec90.png)

Figma file: https://www.figma.com/file/DQ8xiC9VMfPX0nb0MBmOIs/Composer-audit-mewa?node-id=406%3A407

**Comment by mewa1024** [comment]
Also reported in #4335
