### ISSUE TITLE
Call a remote skill

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#696]
## Task Track

Open Item
- 8/30 Depends on SDK

https://microsoft-my.sharepoint.com/:w:/r/personal/luhan_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B03AFB829-07F7-4764-823A-842531D987DC%7D&file=RemoteSkillFuncSpec.docx&action=default&mobileredirect=true

see microsoft/botbuilder-dotnet#2324

**Comment by luhan2017** [comment]
synced with Gabo, it is not fully ready yet, he will try to merge the final wave in master this week, and will keep up posted.

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2233
