### ISSUE TITLE
"Alt-f" doesn't open the "File" Menu (Windows only)

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6960]
## Describe the bug

The Alt-Keys around the Menu (File / Edit / View / etc) do not work. 

Pressing "Alt-F" should open the file menu. Pressing "Alt f + x" should exit the application. 

Windows guidelines standardize this, for each of the menu items. 

## Version

Nightly. 
![image](https://user-images.githubusercontent.com/1165321/114773114-7bb7ee80-9d23-11eb-81a9-9828ef605531.png)

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Composer.
2. Press "Alt-f"
3. Observe nothing happens. 

## Expected behavior
The "File" Menu is opened. From there I should be able to hotkey "New / Open / Exit" as standard across the Windows ecosystem.

**Comment by mewa1024** [comment]
the underlined letters are the Windows shortcuts Chris is talking about:
![image](https://user-images.githubusercontent.com/39317542/124056820-45f9dc00-d9db-11eb-8bc4-2bed360e4baf.png)

**Comment by mewa1024** [comment]
Adding designs for the Alt key shortcuts to design attached to #6959. Closing this issue as a dupe.
