### ISSUE TITLE
New Bot | "Cancel on Node.js required" | Ugly error

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6962]
## Describe the bug

1. Created a new bot. 
2. Received the "Node.js required" screeen.
3. ---->  _*** Pressed Cancel ***_
4. Get returned to the "Bot Template" screen
4. Created an Empty Bot
5. Received ugly error message 

```
If this problem persists, please file an issue on GitHub
Details
Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm root -g --prefix C:\Users\chris\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error 'npm' is not recognized as an internal or external command, operable program or batch file.
```

## Version

Nightly Build. 
![image](https://user-images.githubusercontent.com/1165321/114774870-84112900-9d25-11eb-97b2-adbabb62a39b.png)

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Created a new bot. 
2. Received the "Node.js required" screeen.
3. ---->  _*** Pressed Cancel ***_
4. Get returned to the "Bot Template" screen
4. Created an Empty Bot
5. Received ugly error message 

## Expected behavior

Pressing Cancel on the "Install Node.js" screen should not enable me to create a new bot. 

## Screenshots
![image](https://user-images.githubusercontent.com/1165321/114775060-b7ec4e80-9d25-11eb-8b92-3604ec597013.png)

![image](https://user-images.githubusercontent.com/1165321/114775100-c5093d80-9d25-11eb-951f-e665f1817fba.png)

![image](https://user-images.githubusercontent.com/1165321/114774777-647a0080-9d25-11eb-8715-838ba41c3df8.png)

**Comment by cwhitten** [comment]
@pavolum tagging you to troubleshoot

**Comment by Dewain27** [comment]
This is by design.  Clicking details states that you don't have node installed.
