### ISSUE TITLE
Composer hangs after running a bot and then trying to add a new trigger

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#6964]
## Describe the bug

Composer froze (Not Responding) after I tried to add and configure a new trigger.

## Version

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

(Note I was trying to collect information about a different issue, so these steps are non-standard and I haven't had a chance to reproduce.)

1. Set Composer's debug flag `set DEBUG=composer*`.
1. Run Composer from the command line.
1. Open an existing bot that uses a custom action.
1. Run the bot and interact with it until you hit the "Object reference not set to an instance of an object." that I was trying to debug.
1. Add a new trigger to the bot.
1. In the drop down, attempt to select the default, **Intent recognized**.
1. Error, Composer hangs. (Note, this behavior didn't reproduce when launching Composer from the desktop icon, without the debug flag set.

## Expected behavior

Composer doesn't hang.

## Screenshots

![image](https://user-images.githubusercontent.com/35047199/114777658-bc663680-9d28-11eb-8b49-ac2021aa4a61.png)

## Additional context

Dialog uses the Regex recognizer.

**Comment by srinaath** [comment]
@JonathanFingold We have tried to reproduce this error but we cannot.

**Comment by JonathanFingold** [comment]
@srinaath I'll see if I can reproduce today, and if so, I'll include the custom NuGet package.

**Comment by JonathanFingold** [comment]
@srinaath 
1. Wasn't able to reproduce the same behavior today, and was able to close Composer after trying.
1. **However**, now I can't ctrl+C out of the command prompt in which Composer was running, and closing Composer seems to have left a rogue process on my machine.

```output
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\v-jofin\source\repos\myBots\composer\empty_1\empty_1

2021-04-16T15:59:31.118Z composer:extensions:localpublish SETTING STATUS OF 2618.162179623229 to port 3983 and status 200
2021-04-16T15:59:32.258Z composer:bot-project Schemas directory found.
2021-04-16T15:59:32.261Z composer:bot-project Customized SDK schema found
2021-04-16T15:59:32.265Z composer:bot-project UI Schema found.
GET /api/publish/2618.162179623229/status/default/ff5041ff-991a-45f0-b0d4-ffef94ad34b0 200 63.595 ms - 72
2021-04-16T15:59:32.493Z composer:bot-project Schemas directory found.
2021-04-16T15:59:32.498Z composer:bot-project Customized SDK schema found
2021-04-16T15:59:32.500Z composer:bot-project UI Schema found.
PUT /api/projects/2618.162179623229/files/appsettings.json 200 71.467 ms - 34
POST /api/telemetry/events 200 0.779 ms - 2
POST /v3/conversations 201 1.942 ms - 302
POST /v3/conversations/50a86417-e742-4023-94b8-91534ca471da%7Clivechat/activities/14fd3ed0-cb9b-4b15-b63f-f59b8275bc75 200 1.164 ms - 45
POST /v3/conversations/50a86417-e742-4023-94b8-91534ca471da%7Clivechat/activities/14fd3ed0-cb9b-4b15-b63f-f59b8275bc75 200 0.728 ms - 45
POST /v3/directline/conversations/50a86417-e742-4023-94b8-91534ca471da%7Clivechat/activities 200 994.503 ms - 45
POST /api/telemetry/events 200 0.774 ms - 2
POST /v3/conversations/50a86417-e742-4023-94b8-91534ca471da%7Clivechat/activities/6b580430-51d2-47e1-b8f9-d58bf1bd8a0e 200 0.594 ms - 45
POST /v3/conversations/50a86417-e742-4023-94b8-91534ca471da%7Clivechat/activities/6b580430-51d2-47e1-b8f9-d58bf1bd8a0e 200 0.558 ms - 45
POST /v3/conversations/50a86417-e742-4023-94b8-91534ca471da%7Clivechat/activities/6b580430-51d2-47e1-b8f9-d58bf1bd8a0e 200 0.645 ms - 45
POST /v3/directline/conversations/50a86417-e742-4023-94b8-91534ca471da%7Clivechat/activities 200 116.062 ms - 45
POST /v3/conversations/50a86417-e742-4023-94b8-91534ca471da%7Clivechat/activities/f98384ec-7517-4f07-b691-3b6b59bf6403 200 0.606 ms - 45
POST /v3/conversations/50a86417-e742-4023-94b8-91534ca471da%7Clivechat/activities/f98384ec-7517-4f07-b691-3b6b59bf6403 200 0.669 ms - 45
POST /v3/conversations/50a86417-e742-4023-94b8-91534ca471da%7Clivechat/activities/f98384ec-7517-4f07-b691-3b6b59bf6403 200 0.539 ms - 45
POST /v3/directline/conversations/50a86417-e742-4023-94b8-91534ca471da%7Clivechat/activities 200 194.859 ms - 45
POST /api/telemetry/events 200 0.969 ms - 2
POST /api/telemetry/events 200 0.747 ms - 2
```

From task manager:
![image](https://user-images.githubusercontent.com/35047199/115052514-df145e80-9e92-11eb-8dec-ba04dd44336c.png)
