### ISSUE TITLE
Adaptive card response doesn't appear when called by a skill.

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6965]
I have an adaptive card in a skill. It submits a message that’s handled within the skill (right picture). 
When called as a bot it works fine (middle picture). 
When called from parent as a skill it fails (left picture). 
(maybe SDK issue, not sure)

![image](https://user-images.githubusercontent.com/8867670/114778704-0bf93200-9d2a-11eb-8d84-7d8911c85567.png)

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by cwhitten** [comment]
Closing as a how-to that was addressed offline
