### ISSUE TITLE
Not sure what Been Used means - Grammer?

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#6968]
## Describe the bug

When on the LG editing screen there is a column called "Been Used".  I think this means that it has been used in the project, but seems grammatically incorrect.
![image](https://user-images.githubusercontent.com/18688053/114779899-479cf780-9d3c-11eb-8cf3-bce36b933769.png)

## Version

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a Bot Project or Create a new one
2. Click on the Bot Responses navigation
3. See "Been Used"

## Expected behavior

To have a better description of this column.

**Comment by mewa1024** [comment]
related bug #7118

**Comment by mewa1024** [comment]
closing as dupe (more or less) or #7118
