### ISSUE TITLE
OnChooseIntent: AdaptiveCard template appears broken

### ISSUE THREAD

**Issue by taicchoumsft** [microsoft/BotFramework-Composer#6969]
## Describe the bug
1) Set up a brand new bot with LUIS/QnA, or Orchestrator/QnA, in the root dialog.
2) Add a `OnChooseIntent` trigger (aka intent disambiguation trigger)
3) Try creating a test condition where this trigger will be hit

Instead of seeing the adaptive card with choices, we get an error:

![image](https://user-images.githubusercontent.com/61705609/114780220-f127bd00-9d2b-11eb-817c-3053166cb30b.png)

Snip of error message, looks like `$schema` property is missing a value:
```
"empty_1.en-us.lg:Unexpected character at Path , line 3, position 15 when parsing 
 {
 "$schema",
 "version": "1.0",
 "type": "AdaptiveCard",
 "speak": "",
 "body": [
 {
 "type": "TextBlock",
 "text": "I'm not sure which one you mean.",
 "weight": "Bolder"
 },
 {
 "type": "TextBlock",
 "text": "Can you pick one ?",
 "separator": "true"
 },
 {
 "type": "Input.ChoiceSet",
 "placeholder": "Placeholder text",
 "id": "userChosenIntent",
 "choices": [
 {
 "title": "Test",
 "value": "luisResult"
 },
 {
 "title": "See an answer from the Knowledge Base",
 "value": "qnaResult"
 },
 {
 "title": "None of the above",
 "value": "none"
 }
 ],
 "style": "expanded",
 "value": "luis"
 },
 {
 "type": "ActionSet",
 "actions": [
 {
 "type": "Action.Submit",
 "title": "Submit",
 "data": {
 "intent": "chooseIntentCardResponse"
 }
 }
 ]
 }
 ]
 }
```

## Version
Nightly 235171
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by cwhitten** [comment]
@taicchoumsft, you're updating this template as part of the orchestrator disambiguation, right? can you include the fix for this in it?

**Comment by taicchoumsft** [comment]
OK thanks @cwhitten ,  I'll take care of this as part of that effort
