### ISSUE TITLE
Installed Node / Still seeing "Node JS Required" 

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6970]
## Describe the bug
1. Create a Bot
2. "Node Required"
3. Install Node. 
4. "Node Required" <--- Unexpected

After installing Node, I've got to exit/restart Composer to pickup the fact that Node is installed. 

## Version
Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Fresh install. 
2. Create a Bot
3. Get the "Install Node" Dialog
4. Install Node
5. Create a Bot
6. Get the "Install Node" Dialog  <-- Unexpected. Node is installed. See screen shot. 

## Expected behavior
Create a Bot should work. Node is installed. See screen shot. 

Note: If I Exit/Restart Composer things work. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114780317-13213f80-9d2c-11eb-8711-9d9da67bfad9.png)

**Comment by cwhitten** [comment]
@pavolum tagging you to troubleshoot this

**Comment by srinaath** [comment]
@pavolum We currently do something similar to check for our .NET dependency in which we do "Try Again" to check the PATH variable if its set with the newly installed .NET runtime. Can we do something similar for the Node JS dependancy. It looks like after Node Installation we need check again for its existence in code.
