### ISSUE TITLE
Formatting of descriptions of all bot templates is unexpected

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6972]
## Describe the bug

All templates shown in the "New Bot" screen have an odd indented section of text. This should be presented as standard HTML / Markdown. 

## Version

"Blank bot 1.0.0-rc3" (And all other templates)

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Click the "Create a new bot" link. 
2. Look at the template descriptions. 
3. Wonder why the formatting is odd, and if that means anything? 

## Expected behavior

Clean formatting. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114783726-018d6700-9d2f-11eb-8dda-b1bebdc81ac2.png)

If I look at VS Code Extensions (which is similar), I see clean formatting as I would expect:
![image](https://user-images.githubusercontent.com/1165321/114783306-cb4fe780-9d2e-11eb-9b15-af314a41cb76.png)

**Comment by clearab** [comment]
This section of text (and the indentation) is removed in the next release of the templates.
