### ISSUE TITLE
Horizontal Scroll Bar on Template Descriptions is incorrect

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6974]
## Describe the bug

The description for each template has a horizontal scroll bar that is incorrect. When scrolling to the right, it's all blank. 

Given this is Markdown / HTML and flows, we should avoid having a scroll bar here at all. 

## Version

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Click on "Create a new Bot"
2. Click on a template. 
3. Look at the horizontal scroll bar. 
4. Wonder why it's there5.
5. Scroll the scroll bar, and see it's all blank. 

## Expected behavior

No horizontal scroll bar

## Screenshots

Scrolled Left, things look correct. 
![image](https://user-images.githubusercontent.com/1165321/114783878-38fc1380-9d2f-11eb-9021-3dc60ba8b8dd.png)

Scrolled right, the window width was incorrectly sized. 
![image](https://user-images.githubusercontent.com/1165321/114784018-719bed00-9d2f-11eb-81c8-b7f163b8f028.png)

**Comment by clearab** [comment]
Definitely needs to be fixed, I think p1.5 for R13, p0 for r14 if for some reason this fix is more complex than it first appears and we can't get it in with r13.

**Comment by pavolum** [comment]
This should be auto fixed when the generators are republished Friday with the updated readmes that will result in the removal of non wrappable horizontal text.

**Comment by mewa1024** [comment]
(removing the "UX Design" label since the fix does not need further UI/UX design.)

**Comment by pavolum** [comment]
Closing this as it was resolved with the latest template RCs that have readme fixes and removed the 'code' text that caused horizontal overflow
