### ISSUE TITLE
Descriptive text on first page needs copy editing

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotFramework-Composer#6975]
## Describe the bug

All the text on the initial page reads like marketing and completely distracts from the task.

This is a complete mouthful of tech industry nonsense talk, disconcertingly switching from generalizations to specific technologies:

> "Bot Framework Composer is an open-source visual authoring canvas for developers and multi-disciplinary teams to build bots. Composer integrates LUIS and QnA Maker, and allows sophisticated composition of bot replies using language generation."

And this just reads as trust us, _we_ know best:

> "These examples bring together all of the best practices and supporting components we've identified through building of conversational experiences."

Sticking with this informal style, it would read as less patronizing to simply say "Examples to help get you started."

And this reads like an ad, don't look elsewhere, we have you covered:

> "Bot Framework provides the most comprehensive experience for building conversational applications."

## Version

Version: 1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Start composer - text on first page.

## Expected behavior

Clear task-oriented text that doesn't distract.

**Comment by mareekuh** [comment]
@cwhitten  and @johnataylor - the latest design does not have this copy.
