### ISSUE TITLE
"New Bot" with no selected template does... something. Should not be enabled. 

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6976]
## Describe the bug

When no template is selected, the "Next" button is enabled. When clicked, it's doing something but I don't know what. 

I would expect this to *only* be enabled if something is selected. 

If I click "Next" I'm taken to the next screen (see screen shot). 

**What was created appears to be "Empty Bot".**  However, "Empty Bot" isn't an actual template, so I don't know what/where this came from. Is this "Blank Bot"? 

## Version

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Click on "New Bot"
2. Observe that no template is selected
3. Press "Next"
4. Wonder which template what selected? 

## Expected behavior
"Next" should only be enabled if a template is selected. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114784549-3948de80-9d30-11eb-919c-915af4e42af8.png)

![image](https://user-images.githubusercontent.com/1165321/114785029-ef142d00-9d30-11eb-8ff5-0f6b5fe4c38e.png)

**Comment by clearab** [comment]
@pavolum it looks like the empty template is being selected by default, by the UI isn't picking up the selection?

**Comment by pavolum** [comment]
Yeah, it is desired behavior that it is picked up by default. I will make the change to ensure the UI represents this flow.
