### ISSUE TITLE
"Blank Bot" template created bot called "empty"

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6978]
## Describe the bug

Create a new bot, selecting the "Blank Bot" template. 

On the next screen (see screen shot), the default bot name is "empty". I would expect this to be "blank". Having the name default to "empty" doesn't seem correct.

## Version
Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Click on "Create a new bot"
2. Select the "Blank Bot" template
3. Observe the name of your new bot is "empty"
4. Wonder what "empty" was? 

## Expected behavior

I would expect my bot to be name "blank". Although, truth be told, that's not a great default name. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114785514-ab6df300-9d31-11eb-9f6a-b53d20232e4e.png)

![image](https://user-images.githubusercontent.com/1165321/114785587-c476a400-9d31-11eb-98a7-6001174e3738.png)

**Comment by clearab** [comment]
@pavolum I believe this is going to revert to the 'empty bot' template, however, I'm uncertain where the default naming for templates is being created/pulled from. If we open templates up to 3rd parties, how is the default name going to be populated?

**Comment by clearab** [comment]
Leaving this open, but resolution is blocked until naming is finalized (although my question above may present the possibility of an alternative solution, not sure)

**Comment by pavolum** [comment]
@clearab when will naming for templates be finalized?

Two aspects to this issue
- Display name needing to be changed - display name is now pulled from an external source so we can change that outside of composer releases. If that call to the external source fails it uses the hard coded names in Composer as a back up so the PR Chris had added here is still valid assuming his change to call it 'blank bot' reflects the final naming decision
- The default name autopopulated for your bot proj is not a one to one match to the template name itself. This is known and will not be fixes in R13

**Comment by pavolum** [comment]
Okay renaming of generators is tracked here:
https://github.com/microsoft/botframework-components/issues/932

This requires both a Composer and Components repo change. Peter and I are in communication and will have this resolved Friday when they push new RCs. Keeping this open for tracking
