### ISSUE TITLE
"Show Code" doesn't show Code it shows Schema

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotFramework-Composer#6980]
## Describe the bug

The top right of the central canvas has clickable text to "Show Code" however, when you click on it you see the JSON Schema.

On one level this is just terminology, but really this isn't code, or at least not in the sense that we use the word elsewhere. The problem is when we refer to code elsewhere (for example in documentation) its not clear what we are referring to anymore. For example what do we mean by "code-first" when we also like to refer to this JSON as Code?

It would be clearer, less ambiguous, to just say "Show Schema" and anyone brave enough to look at this (and edit it) won't be scared off with a word like "Schema."

## Version

Version: 1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Open any example. See "show code" on top right of canvas.

## Expected behavior

"Show Code" is ambiguous. Less ambiguous and more accurate would be "Show Schema"

**Comment by cwhitten** [comment]
This doesn't look like code to you?

```json
{
...
  "actions": [
        {
          "$kind": "Microsoft.Foreach",
          "index": "dialog.foreach.index",
          "value": "dialog.foreach.value",
          "actions": [
            {
              "$kind": "Microsoft.IfCondition",
              "actions": [
                {
                  "$kind": "Microsoft.SendActivity",
                }
              ],
              "elseActions": [
                {
                  "$kind": "Microsoft.TextInput",
                  "disabled": false,
                  "maxTurnCount": 3,
                  "alwaysPrompt": false,
                  "allowInterruptions": false,
                  "unrecognizedPrompt": "",
                  "invalidPrompt": "",
                  "defaultValueResponse": ""
                }
              ]
            }
          ]
...
}

**Comment by v-kydela** [comment]
The word schema may also be ambiguous, because a JSON schema normally means something like a template, defining the structure for a JSON document. So when you'd click "show schema" you wouldn't be looking at a schema, you'd be looking at the data that adheres to a schema.

**Comment by cwhitten** [comment]
Closing as a wont-fix, but assigning @mewa1024 to follow-up if necessary
