### ISSUE TITLE
All Templates say they are Yeoman Generators. Within Composer, this is (at best) confusing

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6981]
All the Template descriptions, in the VERY FIRST sentence, call themselves yeoman generators. 

I'm using Composer. I don't know, and don't care, what a yeoman generator is. It's quite misleading in this context, as within the umbrella of Composer they are NOT yeoman generators, as that's an implementation detail I don't care about. 

We should remove/suppress that text when shown in Composer. 

## Version

All rc-3 templates. 

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Click on a Template
2. Read the very first sentence
3. Wonder what Yeoman is, and why it would be shown to me in Composer

**Note**: I know what yeoman is. Given our taget audiance, I would not expect them to know, nor should they need to know.

## Expected behavior

No reference to yeoman inside the description. It's just confusing, as it's an internal implementation detail. 

## Screenshots

![image](https://user-images.githubusercontent.com/1165321/114787113-15879780-9d34-11eb-8875-4f2fc89c73a3.png)

**Comment by clearab** [comment]
Totally agree, this will be removed in the next publish of the template readme's.

**Comment by clearab** [comment]
Current versions of the readme's (including this fix) are available in the -components repo here: https://github.com/microsoft/botframework-components/tree/main/generators
