### ISSUE TITLE
In generated schema $designer property is often noise

### ISSUE THREAD

**Issue by johnataylor** [microsoft/BotFramework-Composer#6982]
## Describe the bug

Composer readily switches to show the underlying JSON Schema content. And it allows this to be edited and on doing so tracks those changes in the "left navigation" and "canvas" as you would expect. However, the JSON contains significant amounts of unnecessary and distracting noise under the $designer property. Removing this property when it only contains an "id" appears harmless: both the UI and the bot's functionality seem fine. And requiring this (or at least expecting it to be there) implies the person editing the Schema has to come up with these "id" values themselves - and yet that doesn't appear to be the case.

In other words there is this potentially powerful and self-consistent editing experience undermined by this noise in the JSON, its really not clear whether its intended to be safely editable or not with this.

## Version

Version: 1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Any canvas view, click "show code" and you see unnecessary $designer everywhere.

## Expected behavior

$designer properties that only contain an "id" don't need to be included in the JSON.

**Comment by cwhitten** [comment]
No plans to update or remove the $designer field. It's an open-ended field used for authoring in various scenarios.
