### ISSUE TITLE
No upgrade workflow when openning an older bot

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6985]
I opened an older unejected bot (era R11/12). I was never prompted for any updates (counter to the scenario doc instructions).

Using latest nightly:

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by Dewain27** [comment]
Being resolved in Migration #6526
