### ISSUE TITLE
Cannot create a new publish profile for a bot created through ABS

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#6988]
## Describe the bug

Created a bot service resource, and triggered open in composer.  When i get through to the point of creating a publish profile for my bot it fails upon typing the first character into the Add New, "Name" dialog with a syntax type error.

## Version

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1) Create Bot Service Bot, open in composer
2) Create New Composer Bot
3) Manage publish profiles
4) Add new
5) Type a character in the name box

<error>

## Expected behavior

No error; recent regressoion

## Screenshots

![image](https://user-images.githubusercontent.com/5997512/114791979-49ff5180-9d3c-11eb-9c6f-d10d4b57002d.png)

**Comment by cwhitten** [comment]
@luhan2017 can you take a look at this? I believe something has regressed in creation

**Comment by luhan2017** [comment]
@jameslew I can't reproduce this issue in my side, could you share more information here? which bot template are you creating? is there an abs-**** profile auto generated for you? you failed when Add new, not Edit the abs-*** one right? 
Here is my snapshot:

![image](https://user-images.githubusercontent.com/32191031/114807918-dd3a9480-9dd9-11eb-8d96-03ce7e963158.png)

**Comment by cwhitten** [comment]
@luhan2017 I'm able to recreate this using the blank bot template

**Comment by luhan2017** [comment]
Thanks, Chris, I can reproduce that now, after it is because after creating a bot from abs, it created an empty publish profile to the bot, I will investigate and fix that.

**Comment by jameslew** [comment]
I'm happy to help as well.  You can ping me at my inbox if you need; I don't hang out in the github very often.

**Comment by luhan2017** [comment]
@jameslew @cwhitten  Fixed, please try and let me know if it still not works.

**Comment by jameslew** [comment]
I assume this will be in the upcoming nightly, not in the one that dropped last night (based on the time of fix?)
