### ISSUE TITLE
ProvisionComposer.js needs to be ARM Templates

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#6989]
When creating a new Publishing Profile, there is a new hand-crafted replacement for "AZ CLI". This is perhaps not the best idea I've seen today. 

![image](https://user-images.githubusercontent.com/1165321/114793289-e1fe3a80-9d3e-11eb-9a44-16de692779dc.png)

This needs to be removed, and replaced with AZ CLI. This should simple be ARM templates, so that we work with everything across the Microsoft Ecosystem. 

Alternately, we need to review with the Azure Security Team, and examine other implications of this. The AZ CLI team will have significant interest in Microsoft shipping an alternate implementation of AZ CLI.

**Comment by clearab** [comment]
I was pretty confused when I saw this command as well, along with the publishing profile JSON being specific to our format, rather than just re-using the existing publishing profile formats that are available in xml.

**Comment by cwhitten** [comment]
Dewain can explain the scenario around this Share Resource Request dialog, but `provisionComposer.js` was not intended to live long, or be used outside of Composer and was replaced internally with the Azure Publish extension.

**Comment by benbrown** [comment]
This script is a wrapper around ARM templates. I discussed this with Dewain this morning - I think it will be possible to replace this with direct use of the ARM template and some additional documentation.

**Comment by clearab** [comment]
Would that mean we could drop this from the code that is scaffolded out for folks? That .js file shows up in the /Scripts folder, and I think is the source of the requirement for installing node in the provisioning process?

**Comment by sgellock** [comment]
I've talked this through with @benbrown and I'm punting this out of R13.  What we have, though not ideal, meets the bar, given the remaining calendar time
