### ISSUE TITLE
Unknown trigger hits parent instead of child (that has unknown trigger)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6991]
## Scenario
* Bot with child dialog.
* Prompt at child for user text input
* Enter utterance that should be detected as unknown
* Handle with recognizer (Orchestrator in my case)

## Results
Expected: Child dialog unknown trigger handles utterance
Actual: parent dialog unknown trigger handles utterance.

## Version
```
Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```

## Visuals
_Expecting child unknown trigger to fire_
![image](https://user-images.githubusercontent.com/8867670/114795538-a44fe080-9d43-11eb-8772-a187bc3c00f4.png)

 --
_Actual: parent trigger fires. Note also, 3 calls to recognizer_
![image](https://user-images.githubusercontent.com/8867670/114795620-d2352500-9d43-11eb-9b94-9b00dc14451e.png)

**Comment by scheyal** [comment]
__Update__:
* With LUIS recognizer at child the behavior is as expected.
* WIth Orchestrator at child, LUIS in parent the unexpected behavior reproduces.

![image](https://user-images.githubusercontent.com/8867670/114796019-c4cc6a80-9d44-11eb-90f2-5e2f9c433873.png)

**Comment by cwhitten** [comment]
This sounds like an orchestrator issue. Please work with that team if there is a bug to address.
