### ISSUE TITLE
Tighten up rocket panel UI

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#6993]
Just a few small updates for the rocket baby. Let me know before submitting to double check spacing/etc.

Figma: https://www.figma.com/file/tvENftrexoAYJngzsJxUbv/EmFig?node-id=3547%3A0 

![image](https://user-images.githubusercontent.com/55601267/114797112-4c1add80-9d47-11eb-9a7b-110f18b65d7e.png)

**Comment by lauren-mills** [comment]
We've been testing the enterprise assistant and have some feedback here based on a multi-bot project with skills. Here are some changes we were discussing. Could you let us know what you think or if any of these would be possible?

![image](https://user-images.githubusercontent.com/27976702/115451484-199f3380-a1d2-11eb-8f0f-3e3ea514e426.png)

**Comment by emivers8** [comment]
@lauren-mills Thanks for the feedback, as always. For the readme, we have an issue tracking that (#5779). For the Learning tab suggestions, if those docs exist it should be easy enough to add those, I think? (@pavolum) For everything else, probably good feedback for R14 when we intend to add state tracking (so we're not showing one million things at the same time). (@Dewain27 how do we want to track for R14?)

**Comment by elaine-chang** [comment]
For the Learning tab docs, those are being created, but I just created 3 aka.ms link for this so you can add. I will update those aka.ms to the official ones once they are published.

- Create a bot with Enterprise assistant template: http://aka.ms/CreateEnterpriseAssistantDoc
- Create a bot with Calendar template: http://aka.ms/CreateCalendarBotDoc
- Create a bot with People template: http://aka.ms/CreatePeopleBotDoc

FYI: @lauren-mills , @thomas-chung , @Quirinevwm

**Comment by benbrown** [comment]
https://www.youtube.com/watch?v=Wro3bqi4Eb8&ab_channel=Moraito

**Comment by elaine-chang** [comment]
@emivers8 explained that no customized links can be added under the Learning tab right now, so for now, we recommend to add the link to the Template Overview page that @darrenj is helping to write. I have created an aka.ms link as a placeholder (http://aka.ms/ComposerBotTemplateOverview). @darrenj can update its redirect once the official doc is ready.

**Comment by pavolum** [comment]
Okay I am going to tackle the rocket panel UI changes. For the additional requests that are being pushed back to R14, I have created this issue 
https://github.com/microsoft/BotFramework-Composer/issues/7408

I have also created an issue that Lauren and I discussed that may be in scope for R13 here
#7409
