### ISSUE TITLE
Package manager community option display both NuGet and community package information.

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#6996]
## Describe the bug

Package manager community option display both NuGet and community package information.

## Version

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

select community option in the package manager 

## Expected behavior

display only community package infomation.

## Screenshots

![image](https://user-images.githubusercontent.com/16264167/114800994-23243800-9d9b-11eb-9bc3-0de7f8717983.png)

## Additional context

Nuget option is wokring fine.

**Comment by clearab** [comment]
Partial duplicate of: https://github.com/microsoft/BotFramework-Composer/issues/6854

I believe the best solution here is to just remove the split in the feeds.

**Comment by clearab** [comment]
Closing this - per the linked Issue above we're going to be combining these two feeds.
