### ISSUE TITLE
Allow accessing files/dir on native OS file management

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#6997]
## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/16264167/114811127-d26a0a80-9dad-11eb-8b1d-a3fcbf14cd0c.png)

![image](https://user-images.githubusercontent.com/16264167/114811254-10672e80-9dae-11eb-805e-473784cb2f1e.png)

**Comment by benbrown** [comment]
@rvinothrajendran Thank you for the suggestions. It is tricky to open the native file explorer from the web, but it may be possible to do from inside the electron build.

We'll consider this for future releases.
