### ISSUE TITLE
UX - Wrong error message in Create a Bot project

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7003]
## Describe the bug

Enter the project name with empty string ( "space")  , its showing wrong error message
"Bot name cannot not start with a number "

## Version

Version:  1.4.0-nightly.235171.cfc0c11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1- Go to project template select blank bot 
2- In the name filed .. typo the space.

## Expected behavior

Error message should display  **name is required**

## Screenshots

![project](https://user-images.githubusercontent.com/16264167/114823580-ff291c80-9dc3-11eb-825a-caa4ed755fe2.png)

**Comment by kuacci** [comment]
Seems like the [validate](https://github.com/microsoft/BotFramework-Composer/blob/ef8eb11e2349838a03bf76d4ea3a4810d585f4e6/Composer/packages/client/src/components/CreationFlow/v2/DefineConversation.tsx#L157) function causing this error.
```ts
   const formConfig: FieldConfig<DefineConversationFormData> = {
    name: {
      required: true,
      validate: (value) => {
        if (!value || !nameRegexV2.test(`${value}`)) {
          // botName is used as used when generating runtime namespaces which cannot start with a number
          if (value && !isNaN(+value.toString().charAt(0))) {
            return formatMessage('Bot name cannot not start with a number');
          } else {
            return formatMessage('Spaces and special characters are not allowed. Use letters, numbers, or _.');
          }
        }
```

And following [place](https://github.com/microsoft/BotFramework-Composer/blob/ef8eb11e2349838a03bf76d4ea3a4810d585f4e6/Composer/packages/client/src/hooks/useForm.ts#L44) references the above validate function:
```ts
export function useForm<D extends object>(fields: FieldConfig<D>, opts: FormOptions = {}) {
  const [formData, setFormData] = useState(mapValues(fields, (f) => f.defaultValue ?? '') as D);
  const [formErrors, setFormErrors] = useState<FormErrors<D>>(mapValues(formData, () => undefined));

  const validateField = async (name: keyof D, fieldConfig: FormField, value: unknown): Promise<void> => {
    let error: string | undefined = undefined;

    if (fieldConfig.required && !value) {
      error = formatMessage('{name} is required', { name });
    } else if (!fieldConfig.required && !value) {
      return;
    } else if (typeof fieldConfig.validate === 'function') {
      error = await fieldConfig.validate(value);
    }
```

**Comment by Dewain27** [comment]
@rvinothrajendran thanks for the bug, I have put in into the queue to be addressed.
