### ISSUE TITLE
404 Error on QnA Maker bot Template Readme

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#7010]
## Describe the bug

When creating a new bot and you select the QnA Template you get a 404 in the template readme section as seen below:
![image](https://user-images.githubusercontent.com/18688053/114892012-00614600-9dd2-11eb-9316-db6a798cdf89.png)

## Version

Version:  1.4.0-nightly.235590.f4de79
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot
2. Select QnA Bot Template
3. See Error on screen

## Expected behavior

Contents for the readme should be displayed

**Comment by clearab** [comment]
@pavolum I deleted the old readme in the /docs folder, I'm guessing this is still pointed there rather than to the readme in the template/generator?
