### ISSUE TITLE
Skills: Offered intents when creating a skill do not include all from all dialogs although selected in wizard

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#7014]
## Repro
* Create a new bot with 2-3 dialogs each with several intents
* Test with, say LUIS or Orchestrator.
* Create a manifest to turn it into a skill
* Follow prompts...
* Select all dialogs
* Very few intents show up

## Version
```
Version:  1.4.0-nightly.235590.f4de79
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```

## Visuals
(_only few intents show up_)
![image](https://user-images.githubusercontent.com/8867670/114920351-33113b80-9dde-11eb-9ef9-a339899fc90e.png)

--
(_many more filled intents_)
![image](https://user-images.githubusercontent.com/8867670/114920625-7bc8f480-9dde-11eb-8ed7-e37037a6aeb0.png)

**Comment by scheyal** [comment]
One more visual

![image](https://user-images.githubusercontent.com/8867670/114921330-4d97e480-9ddf-11eb-8219-a700a369b39c.png)

**Comment by scheyal** [comment]
Moreover - I found that if I only select a child dialog in skill, it is not showing, rather only the parent (greetings) intents show up.

**Comment by luhan2017** [comment]
The two selection pages (select which dialogs are included in the skill manifest and select which tasks this skill can perform) are totally two separated concepts. 

@scheyal @darrenj @vivekkshankar Here are the list of triggers which are supported in composer for now:
![image](https://user-images.githubusercontent.com/32191031/118473336-6d069200-b73c-11eb-90d5-edd3a636fb4e.png)

And I have following questions which I want to clarify with you: 
- Dialogs are exposed as event activity, but currently it does not work. we need to create an event activity trigger and begins that dialog under this trigger to make it e2e work. And this is the confusing part, most of the uses assume that the selectable triggers are from the selected dialogs. 
- Some of the activity triggers maybe not needed, such as OnTypingActivity, OnMessageDelete/Update/ReactionActivity.
- OnEventActivity and OnInvokeActivity is not selectable through UX, I thought they are also widely used in skill scenarios.
- Do we want to expose QnA and ChooseIntent for skills?

**Comment by luhan2017** [comment]
Dupe with #7195
