### ISSUE TITLE
Low Pri: Text is clipped on Package Manager->Edit Feeds (Prer...)

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#7017]
## Describe the bug

Text is clipped in header of Edit Feeds..

## Version
Version:  1.4.0-nightly.235590.f4de79
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

- Click on Package Manager
- Click on Edit feeds
- UI will show clipped text.
- See "Prer..." as last column.

## Expected behavior
- Column header sized so we can read column header text.

## Screenshots

![image](https://user-images.githubusercontent.com/6182197/114936766-b8521b80-9df1-11eb-8e74-0221d29e5383.png)

**Comment by taicchoumsft** [comment]
Hi @clearab , not sure if you're already tracking this, this came up in Orchestrator internal bugbash as a general composer UX bug - no matter how you resize the `Edit Feeds` window, the word is always clipped.

**Comment by mewa1024** [comment]
Related to #7028 (@emivers8 able to tackle both issues with one redesign?)
