### ISSUE TITLE
"LUIS" is unnecessary in Composer's "create a trigger" dialog field "Wat is the name of this trigger (LUIS)"

### ISSUE THREAD

**Issue by hcyang** [microsoft/BotFramework-Composer#7019]
## Describe the bug

When we create a new trigger with the "Intent recognized" type, the second field is "What is the name of this trigger (LUIS"

That "(LUIS)" is unnecessary as LUIS is not the only intent recognizer in Composer.

![image](https://user-images.githubusercontent.com/370110/114943217-7f6a7480-9dfa-11eb-90b3-ac79c5eb97e7.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by taicchoumsft** [comment]
Hi @vivekkshankar , do you think you can provide some feedback here? Can we remove the `LUIS` word in the `Intent Recognized` dialog box?  It has to be generalized to Orchestrator/LUIS

**Comment by scheyal** [comment]
This is confusing and an easy fix. If you're using Orchestrator, seeing LUIS is misleading. Better nothing than misleading.

**Comment by vivekkshankar** [comment]
i agree.. should be ok to remove.

**Comment by taicchoumsft** [comment]
Ok Thanks @vivekkshankar , @scheyal , will get this done asap.
