### ISSUE TITLE
Switching Recognizer throws message box

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#7020]
## Describe the bug

When switching the Recognizer Type, 

## Version

Version:  1.4.0-nightly.235590.f4de79
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

- Load bot (using one from Tai)
- Set `Recognizer Type` to `Orchestrator recognizer`
- Message Box appears (see below)
- It then resets back the Default Recognizer

## Screenshots

![image](https://user-images.githubusercontent.com/6182197/114943474-e5ef9280-9dfa-11eb-9d30-837019a88266.png)

**Comment by cwhitten** [comment]
@daveta are you able to reproduce this on a fresh project with latest nightly?
