### ISSUE TITLE
Can't install any packages, error const

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7023]
## Describe the bug
Attempting to use package maanger to install packages fails.

## Version
1.4.0-nightly.235590.f4de79

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new project
2. Try to install any package from components package manager.

## Expected behavior

to install package.

## Screenshots
![image](https://user-images.githubusercontent.com/17789481/114954691-fcecaf80-9e0f-11eb-871d-fd8d52ee9962.png)

**Comment by cwhitten** [comment]
Looks like a tagging issue. Closing
