### ISSUE TITLE
Error message has bogus scroll bar

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7024]
## Describe the bug
When I fail to install package it has error message with scroll bar that doesn't seem to do anything other than look bad.

## Version

![image](https://user-images.githubusercontent.com/17789481/114954803-260d4000-9e10-11eb-820b-c3c89ffec5c0.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new project
2. try install package, it fails

## Expected behavior

Only have scrollbar if it's needed.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/114954757-12fa7000-9e10-11eb-8c57-702e8e09efb7.png)

**Comment by cwhitten** [comment]
I see the following on latest:

<img width="604" alt="Screen Shot 2021-04-20 at 3 57 35 PM" src="https://user-images.githubusercontent.com/1156704/115473811-39921f80-a1f1-11eb-9761-58425dccac23.png">


Preemptively closing. Please re-open if you continue to see this.
