### ISSUE TITLE
Name of package feed 'nuget' is misleading.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7025]
## Describe the bug

The name of the package feed **nuget** in visual studio would normally be ALL NUGET packages.  Ours is hooked up to just a feed of just microsoft official packages.

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to package manager and look at feeds

## Expected behavior

* **Microsoft components** - should be nuget filtered to Microsoft
* **Community components** - should be nuget filtered to Community 
* **All nuget** - should be all of nuget, no filter.  It is perfectly acceptable to add packages which are NOT components.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/114955157-df6c1580-9e10-11eb-9a9e-670dfaeb9e80.png)

**Comment by clearab** [comment]
We're collapsing the two NuGet feeds down into a single feed here #6854
