### ISSUE TITLE
Package manager knows what project is active, it should only show feeds for that environment

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7026]
## Describe the bug
The drop down shows all feeds, even though only some of them apply to my project type.  This is super confusing.  We should only show the feeds that are compatibile with the current open project.

## Version
![image](https://user-images.githubusercontent.com/17789481/114955230-088ca600-9e11-11eb-9acd-e64e988f3e32.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new projeect
2. go to project manager
3. look at feeds

## Expected behavior
If I have a csproj, then only show me NUGET feeds
If I have a JS project, then only show me NPM feeds
If I have a python project, then only show the pypy feeds
If I have a Java project, then only show me the JAR feeds.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/114955219-01659800-9e11-11eb-9f1d-13a2b8349bce.png)

**Comment by benbrown** [comment]
It will default to the appropriate feed based on the runtime language.

We decided to show the other languages as well but disable the ability to install them if they are not compatible.
