### ISSUE TITLE
Prer... Button activates when you click on a custom row, but is disabled when you try and click on it.

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7028]
## Describe the bug

The Prer... buttons (whatever those are) are disabled, until you click on a custom feed, then ALL of them are enabled, but when you try to click on them they are disabled again. Confusing as heck.
## Version

![image](https://user-images.githubusercontent.com/17789481/114955606-e6dfee80-9e11-11eb-99a7-bcb90eff78a7.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. createproject 
2. go to feeds
3. Prer.. buttons are disabled
4. click on a custom feed, **Pre...** buttons are enabled on ALL rows.

## Expected behavior
a. to be able to turn on and off "official" feeds
 
## Screenshots

![image](https://user-images.githubusercontent.com/17789481/114955754-39210f80-9e12-11eb-8098-0a4b6c9c1763.png)
![image](https://user-images.githubusercontent.com/17789481/114955795-505ffd00-9e12-11eb-8a6c-e86383b83903.png)

**Comment by benbrown** [comment]
A fix for this is in #8219! thanks for reporting this @tomlm
