### ISSUE TITLE
Update package text warning is a strong statement

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#7032]
## Describe the bug

The upgrade package warning text is misleading.

![image](https://user-images.githubusercontent.com/1139814/114956072-f3187b80-9e12-11eb-8713-22cb216e5662.png)

## Version

Version:  1.4.0-nightly.235590.f4de79
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. go to package manager
2. install a package
3. change the version of the package, and install that version
4. See warning text

## Expected behavior

Ideally, the warning should only be displayed if we detect conflicts, and should enumerate the detected conflicts. If that is not technically possible, we should at least change the error message to:

"Any changes you made to content (.dialog, .lu, .lg or .qna files) imported from this package will be overwritten. Do you want to continue?"

We should also add a "Learn more" link to a docs page with additional information on how updating package versions works.

**Comment by cwhitten** [comment]
@clearab  your suggested copy says the same thing in the dialog today, only more nuanced.

**Comment by clearab** [comment]
Kind of, but this warning is thrown on any package update, even one that does not contain declarative files, and ones for which there is no declarative file conflict. 

Users who are used to working with NuGet/npm packages in other systems would be confused - what changes? why would a nuget install cause me to lose data?

User who have never used NuGet packages before would be have no context to answer the "what changes" question either.

We need to answer the "what changes would cause me to lose what data" question more precisely, or only popup this warning when there are specific conflicts detected.

**Comment by mewa1024** [comment]
(@emivers8 fyi)
