### ISSUE TITLE
Core SDK Actions are missing from the UI

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7034]
## Describe the bug

These actions are missing from the UI:

DialogManagement:
* CancelDialog
* GetConversationReference
* ContinueConversation
* ContinueConversationLater

Looping
* GotoAction

Debugging
* DebugBreak

## Expected behavior

Those actions to be there.

**Comment by clearab** [comment]
@EricDahlvang I know you've been interested in this one!

**Comment by yeze322** [comment]
They don't have uischema defined, needs to be updated in dotnet runtime repo.

Refs another thread of Trigger kinds: https://github.com/microsoft/BotFramework-Composer/issues/7035#issuecomment-821047705

Needs to have another wave of SDK release. @cwhitten

**Comment by yeze322** [comment]
@tomlm Tom, I noticed `CancelDialog` and `CancelAllDialogs` have the same schema definition: [CancelDialog.schema](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.CancelDialog.schema) vs [CancelAllDialogs.schema](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.CancelAllDialogs.schema)

However, in the underlying implementation they are different from each other, where `CancelDialog.cancellAll` equals `false` and `CancelAllDialogs.cancellAll` equals `true`.
