### ISSUE TITLE
Core SDK Triggers are missing

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7035]
## Describe the bug

**OnContinueConversation** trigger is missing from the UI.
**OnCommandActivity** trigger is missing 
**OnCommandResultActivity** is missing.

## Version

![image](https://user-images.githubusercontent.com/17789481/114957258-82bf2980-9e15-11eb-8b0f-79f4cb6cdd96.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new projeect
2. go to trigger menu, try and find the missing triggers.

## Expected behavior

All triggers in the .schema files to be surfaced.

## Additional context

x

**Comment by yeze322** [comment]
I'm using nightly-236088, **OnCommandActivity** and **OnCommandResultActivity** appear under the trigger wizard:
![image](https://user-images.githubusercontent.com/8528761/115004063-01c96600-9ed9-11eb-925d-1eed24d482b4.png).


`OnContinueConversation` doesn't contain an uischema definition in dotnet repo. Requires an update on sdk runtime side.

cc @cwhitten
