### ISSUE TITLE
Location issue in Create a bot project

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7039]
## Describe the bug

Invalid path "Create a new folder" button gets enabled.

## Version

Version:  1.4.0-nightly.236088.ef8eb11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Refer the Screenshots

## Expected behavior

Create a new folder button should be disabled.

## Screenshots

Display error message thats fine & ok button gets disabled but create a new folder its enabled.

![allow1](https://user-images.githubusercontent.com/16264167/114983309-c0ad6380-9e90-11eb-8b2e-6f76f6f6f9dc.png)

Able to create a folder but the path does not exits & ok button gets enabled 

![allow2](https://user-images.githubusercontent.com/16264167/114983368-d3279d00-9e90-11eb-9b18-4c3d2074d638.png)

![allow3](https://user-images.githubusercontent.com/16264167/114983516-036f3b80-9e91-11eb-9f72-dfb8b37d6bfd.png)

Finally composer try to create a project & its shows the errror.

![allow4](https://user-images.githubusercontent.com/16264167/114983602-1bdf5600-9e91-11eb-89fa-9f7832aa9102.png)

**Comment by lauren-mills** [comment]
This will be included in the next release per @Dewain27

**Comment by pavolum** [comment]
This will be fixed prior to the next release

**Comment by cwhitten** [comment]
I find it odd that we've communicated that this will be addressed in an upcoming release, yet is a P2 on the milestone.
