### ISSUE TITLE
Components that contain only code and no schema do not show as installed in Package Manager

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#7043]
## Describe the bug

If a package contains only code (e.g. middleware etc) and no schema, then the Package, once installed through Package Manager, does not appear as installed and cannot be uninstalled / upgraded via Composer. @benbrown indicated this is because we are using schema to determine which packages are installed.

We need to look at another way of identifying which packages are installed, potentially through the package tag 'msbot-component'.

## To Reproduce

Install the Bot.Builder.Community.Components.Handoff.LivePerson package from the community.

## Expected behavior

The package should show as installed and be able to be uninstalled.

**Comment by carlosscastro** [comment]
@tomlm  and I ran into this as well. Furthermore, if the component has no schemas, the component does not get added to the 'runtimeSettings.components' collection, and thus not getting bootstrapped by the runtime.

**Comment by garypretty** [comment]
@benbrown  @carlosscastro I think #7243 fixes the issue where packages don't show as installed.  Will we need an additional fix to ensure that packages without schema are correctly added to the plugins sections in the appSettings?

**Comment by benbrown** [comment]
@garypretty this should cover both scenarios.
