### ISSUE TITLE
Data loss when cutting / copying & pasting response

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#7045]
## Describe the bug

Attempting to cut / paste (or copy / paste) a a 'Send a Response' action results in loss of the data within the action.

![Cut Paste Error](https://user-images.githubusercontent.com/3900649/115005461-c9f1fc80-9e9f-11eb-8635-7fc9e57b786e.gif)

## Version

Version:  1.4.0-nightly.236088.ef8eb11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by garypretty** [comment]
In addition to the above, whenever you try to do a cut / copy / delete on a dialog, the screen flips to the root dialog node, instead of remaining, in this case, on the BeginDialog node.

**Comment by garypretty** [comment]
Also seems like cut / copy might work between different dialogs but fails within the same dialog.

**Comment by boydc2014** [comment]
Note: related to navigation issues
