### ISSUE TITLE
Removing a dialog fails even after I confirm I want to continue

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#7046]
## Describe the bug

Trying to remove a dialog in use correctly prompts me before removing, but even if I confirm I want to continue the dialog is not removed.

![Remove Dialog Fails](https://user-images.githubusercontent.com/3900649/115006776-29044100-9ea1-11eb-97cd-352244c99a4c.gif)

**Comment by cwhitten** [comment]
@garypretty can you please provide versions in these reports? 

I cannot reproduce on latest

**Comment by garypretty** [comment]
@cwhitten Apologies for not including the version.  I just upgraded to latest and I can no longer repro this either.  Closing.
