### ISSUE TITLE
Package runtime dependency mismatch causes failure for bot to start

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#7047]
## Describe the bug
I created a bot that depended on the runtime package Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime 4.13.0-rc4.

I then used the Package Manager to install Microsoft.Bot.Components.AdaptiveCards 1.0.0-rc5.

Tried to start the bot but received an error due to a mismatch in package dependencies.

NU1605	Detected package downgrade: Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime from 4.13.0 to 4.13.0-rc4. Reference the package directly from the project to select a different version. 
 SeeWellCustomerService -> Microsoft.Bot.Components.AdaptiveCards 1.0.0-rc5 -> Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime (>= 4.13.0) 
 SeeWellCustomerService -> Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime (>= 4.13.0-rc4)	SeeWellCustomerService	C:\Bots\Microsoft\Demos\SeeWellCustomerService\SeeWellCustomerService\SeeWellCustomerService.csproj	1

**Comment by clearab** [comment]
Here's a thread on this topic that might help - https://github.com/NuGet/Home/issues/6306

**Comment by clearab** [comment]
@benbrown - this might be something that we don't have time to get done in R13. The solution for this we believe is to have composer validate the bot's runtime dependency during package install, and if necessary update the runtime dependency automatically. NuGet has a similar behavior.

**Comment by cwhitten** [comment]
Moving to P1
