### ISSUE TITLE
Unable to edit/delete publish profile

### ISSUE THREAD

**Issue by nikita-rane-22** [microsoft/BotFramework-Composer#7048]
When trying to edit the publish profile in composer, the screen turns blank.

Also, unable to delete the profiles.

**Comment by rvinothrajendran** [comment]
@nikita-rane-22 update OS and Composer version information better add image or video

**Comment by GeoffCoxMSFT** [comment]
@nikita-rane-22 Could you provide a little more information about this issue?  
- Are you using the latest published version of Composer or are you using the nightly builds?
- Which screen goes blank? The entire app or the wizard dialog?
- If you open the F12 dev tools (Ctrl+Shift+I in the desktop app), does the console report any script errors?

**Comment by Dewain27** [comment]
These items should be fixed in the next release.
