### ISSUE TITLE
UX Changes : Bot start and stop

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7049]
As user its not easy way to stop the bot , every time go to "Open start bot panel" and stop bot 

## Describe the solution you'd like
better add the button to stop the bot on the panel

![image](https://user-images.githubusercontent.com/16264167/115028515-3df2cb80-9ec5-11eb-8012-8882b1472bd3.png)

**Comment by benbrown** [comment]
@mewa1024 What do you think about this suggestion?

**Comment by mewa1024** [comment]
I agree, but adding @sangwoohaan since I think there was some history to how the stop mechanism ended up in the drawer. Sang, thoughts?
