### ISSUE TITLE
Keyboard shortcut is not working

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7050]
## Describe the bug

If am correct Keyboard shortcut Ctrl + c to stop the bot application then its seems to be is not working

## Version

Version:  1.4.0-nightly.236155.f2b2823
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Ctrl +c application not stopped.

## Expected behavior

Application should stop.

## Screenshots

https://user-images.githubusercontent.com/16264167/115030636-988d2700-9ec7-11eb-8584-bca1d7569a62.mp4

**Comment by pavolum** [comment]
@rvinothrajendran thank you for finding this. It is a little misleading. The console log assumes you are in the console where ctrlC would execute command termination. However it is rendered in Comoser where ctrl+c is the copy command. We will priorities and gauge whether a design change for this is needed.

@emivers8 Can you take this to the design team and see if it is a design change we should make in a future release.

**Comment by emivers8** [comment]
We'll take a look. Thanks @rvinothrajendran and @pavolum.

@mewa1024 FYI. We should include this in a discussion of keyboard shortcuts.

**Comment by tsuwandy** [comment]
@emivers8, should this be assigned a milestone?

**Comment by mewa1024** [comment]
Assigning this to R14. This is part of Composer clean up/alignment.

**Comment by cwhitten** [comment]
This will be a bit tricky to implement, as multiple bots can be running simultaneously in a project. While the runtime emits that ctrl+c will show down the process, it is implied that the user is in an active terminal bound to the single running bot.

Recommendation is not include this in a milestone until we have clarity on the prioritization of supporting this.
