### ISSUE TITLE
Custom input type not separated like default bot composer input type

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7056]
## Describe the bug

Created a custom input type . GUI is not separated like default bot composer input type
1. Right side panel display in the flat view , not tab wise like Bot Asks, User Input , other
2. Visual editor title is missing ( Ref the screenshots)

## Version

Version:  1.4.0-nightly.236155.f2b2823
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

code is available here : https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/pull/381/files

## Expected behavior

Should be separated like default bot composer input type

## Screenshots

![image](https://user-images.githubusercontent.com/16264167/115053506-7dc6ac80-9edf-11eb-9bbe-4b3effe7defe.png)

**Comment by cwhitten** [comment]
@rvinothrajendran the tabbed input type is a custom control bound to the Bot Framework SDK Input Dialogs. We do not expose the ability to reuse these tabs in custom actions like you have created at the moment.

In the future, we will expose additional tooling to customize this experience further for you. We'll keep this on the backlog as a feature-request.

**Comment by rvinothrajendran** [comment]
@cwhitten thanks for the information.
