### ISSUE TITLE
Test in Emulator option

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7057]
## Describe the bug

If emulator is not available in the PC ... If user click the "Test in Emulator" button , Its display default app open window but text is written in window its not clear. ( Ref the screen shot) 

## Version

Version:  1.4.0-nightly.236155.f2b2823
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Emulator should not be installed in the PC
2.  In the composer , click "Test in Emulator" button.

## Expected behavior

Text should be corrected  or provide the link to download the emulator.

## Screenshots

![image](https://user-images.githubusercontent.com/16264167/115060107-c2eedc80-9ee7-11eb-948d-5d8d9ee1c54f.png)

**Comment by cwhitten** [comment]
hello @rvinothrajendran and thanks for the bug report. we'll seek to address this in an upcoming release. putting on our product backlog for now.

**Comment by rvinothrajendran** [comment]
+ Incase there is no access Microsoft store .. popup window display like below 

![image](https://user-images.githubusercontent.com/16264167/115345288-e13a2e00-a1ae-11eb-936c-384ab8fe0025.png)
