### ISSUE TITLE
Remote skill triggers for skill fails when triggered from Root Bot

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#7059]
## Describe the bug
1. Exported a bot as a skill. 
2. Made sure MSAppId of the root bot is in allowed callers. 
3. The remote skill addition also added the skill's MsAppID in the allowedCaller section of the root bot. 
4. Configured ngrok on the Rootbot for the skill host endpoint. 
5. Started the bot. And used the trigger word to kickstart the trigger which the skill addition added. I keep getting a Module failed to load exception

https://skillbot-1.azurewebsites.net/manifests/SkillBot-2-1-manifest.json - manifest of skill
https://user-images.githubusercontent.com/13004779/115076185-0a0dab00-9eb1-11eb-972c-d8613464a0db.mov

## Version
Custom electron nightly from skills branch

**Comment by luhan2017** [comment]
This seems like an orchestrator issue, @taicchoumsft , have you ever met this issue before? "Failed to find or load model"

**Comment by taicchoumsft** [comment]
Hey @luhan2017 , yes that's an Orchestrator warning message.  I will load up the skills branch and diagnose this. 

In the "usual" workflow (single bot), on click of "Start Bot", we will download the language models into the user profile/BotFrameworkComposer folder.  We also write this data into orchestrator.settings file in generated folder. If these two are not present, or incorrectly set, we get this "failed to find or load model".

**Comment by taicchoumsft** [comment]
Hey @srinaath , was this done on a Mac?  Can you share the contents of your `BotFrameworkComposer/models` folder?  Is it empty? If there are subfolders, can you see if they contain a `model.onnx` file?  
Thanks @srinaath.

**Comment by srinaath** [comment]
![](https://user-images.githubusercontent.com/13004779/115636592-1e8fe000-a2c3-11eb-8446-efa0d8c35647.png)

I do not see the models folder here. @taicchoumsft . Maybe we can do a screenshare to see why Orchestrator never got installed?

**Comment by taicchoumsft** [comment]
Thanks @srinaath for repro and debug session.  This will be fixed in SDK with 4.13.1.  Linked issue: https://github.com/microsoft/botbuilder-dotnet/issues/5524

**Comment by cwhitten** [comment]
Closing in anticipation of https://github.com/microsoft/botbuilder-dotnet/issues/5524
