### ISSUE TITLE
Add new caller UI

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#7060]
## Describe the bug
What is the difference between Add new caller and Add caller

<img width="1031" alt="Screen Shot 2021-04-16 at 12 17 48 PM" src="https://user-images.githubusercontent.com/13004779/115076697-c9626180-9eb1-11eb-9799-b4fd5fd2b04a.png">

Version
Custom electron version from skill branch

**Comment by luhan2017** [comment]
This also exists in the latest nightly, @tdurnford , is this added by you? what is the difference between Add caller and Add new callder? And what should be the expected behavior.

**Comment by tdurnford** [comment]
@luhan2017 @srinaath There is no difference - there should only be one button. The design uses “Add new caller”

**Comment by tdurnford** [comment]
Might be resolved by https://github.com/microsoft/BotFramework-Composer/pull/7130

**Comment by pavolum** [comment]
It is resolved by #7065, this is being tracked in an issue linked to that PR so this is a duplicate issue. Closing this issue.
