### ISSUE TITLE
Dummy remote skill generated when publishing a manifest

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#7061]
## Describe the bug
A transient dummy remote skill is shown in the Project tree whenever I first try to publish a manifest.

## Version
Custom electron on build using skills branch

![MicrosoftTeams-image](https://user-images.githubusercontent.com/13004779/115077400-d6338500-9eb2-11eb-87c0-1a679e9393cf.png)

**Comment by luhan2017** [comment]
@srinaath Do you know how to reproduce this issue? I tried to reproduce this issue today, but failed. Any insights?
