### ISSUE TITLE
Incorrect root navigation after various authoring operations

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7066]
## Describe the bug
If you delete the last node in a flow the trigger you are working on is navigated away from to the dialog

## Version

![image](https://user-images.githubusercontent.com/17789481/115097520-ad75b480-9edf-11eb-813b-2cc2da418d5c.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Greeting trigger for root dialog, add custom action 
3. Delete
4. The flow you are navs away making it look like everything was deleted

## Expected behavior

The current view on the current trigger to be maintained.

## Screenshots
add custom event
![image](https://user-images.githubusercontent.com/17789481/115097583-edd53280-9edf-11eb-97e4-5af9c3090afd.png)
click delete
![image](https://user-images.githubusercontent.com/17789481/115097596-f6c60400-9edf-11eb-90aa-05531fa40ad3.png)
it navigates to dialog (away from trigger)
![image](https://user-images.githubusercontent.com/17789481/115097602-034a5c80-9ee0-11eb-9bfe-91343876f427.png)

**Comment by cwhitten** [comment]
This should be fixed in latest nightly
