### ISSUE TITLE
Recent bots list updated in single click

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7069]
## Describe the bug

Recent bots list is not updated in single click.

## Version

Version:  1.4.0-nightly.236319.b7f3fe8
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Refer the video

## Expected behavior

Single click list should be update.

## Screenshots

https://user-images.githubusercontent.com/16264167/115107048-ca09ff00-9f68-11eb-897c-70971b4327f9.mp4

**Comment by beyackle** [comment]
I've tested this out with the related PR (#7140) that looks like it should handle this, and it does, but there's a new problem. The list does update, solving the scenario above, but multi-bot projects are still a little weird. If I open a bot A with skills B and C, it will place B and C in the list ahead of A. This wouldn't be a great experience if a user puts more than four skills in a bot - the root bot would end up buried and inaccessible.

**Comment by beyackle** [comment]
Note: both #7140 and #7185 should merge in order to close this issue.
