### ISSUE TITLE
Tour should be 1st tile on Composer  'Home' page 

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7072]
I expected the Product Tour to be the fist tile in 'Tutorials' - why is it not?
If we only have 4 spots, I'd push Emulator to the 5th (Tour being 1st).

**Comment by garypretty** [comment]
@mareekuh are you referring to the 'Resources' cards on the home page? 

Can you clarify exactly where this Product Tour card would link to please?

**Comment by mareekuh** [comment]
Yeah - this is the onboarding experience that recently got fixed 
<img width="712" alt="Screen Shot 2021-04-18 at 10 44 56 AM" src="https://user-images.githubusercontent.com/48503434/115155100-3bae7f80-a033-11eb-8d57-e315db1e8ea0.png">

I am also reviewing the 'News' section and will be proposing [updates to the copy.] - could you take a look? (yellow section, E2E 2 tab)

(https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea)

**Comment by garypretty** [comment]
@mareekuh thanks.  Taken a scan and will dig in this week.  Some of the updates look straightforward, others I think we need to keep closer to the original, but we can sync this week.

On the product tour, I don't believe we can trigger the product tour - these cards are designed to link out to external content.  This is something we can consider for a future milestone though. I am not sure though that this is the best use of real estate, given the product tour is automatically on for new users and can also be re-enabled in settings.  Anybody looking at this section is likely look for additional content - plus this content is now planned to be updated over time as new tutorials / videos become available.

**Comment by mareekuh** [comment]
Ok cool -if it's turned on by default, that's great. (-:
I talked with Darren and Scott about the need to do a copy pass and they ok-ed and the 3 of us will figure out a way to do it. 
I am collecting the hi-pri flows in the xls so it's in a single place that can be reviewed and worked from. I used the E2E scenarios as a basis and will cross-check with what's in the Builds. Will send you a heads-up when sections are ready to review - trying to do a streamline/align across pages and feature crews vs change-for-change sake (-:

**Comment by mewa1024** [comment]
(more background about removing the product tour from the home page: Composer is no longer shipping with premade bot samples and instead is using the creation wizard. Our options were to provide a premade bot just for the purposes of the tour only, but that created complications in terms of saving the tour bot, or to just tour after the create flow. @xiyangdesign and I decided the latter option was cleaner at this time.)

**Comment by xiyangdesign** [comment]
Yes as @mewa1024 mentioned. 
- when the user lands on Composer for the first time (either through creation wizard, or opening a bot from Azure), they will see the rocket ship menu, product tour is the first item on the learning tab.
<img width="369" alt="image" src="https://user-images.githubusercontent.com/74994573/115305831-ca96c700-a11b-11eb-843a-16c9df6802ec.png">

- Additional benefit: opening bot from Azure/PVA may skip homepage and land on design page as their first time Composer experience. Product tour in rocket ship menu is more discoverable in this case.

**Comment by garypretty** [comment]
Closing this as tour being made available via the Rocketship.

**Comment by mareekuh** [comment]
@garypretty  and @mewa1024 The learning section is not very discoverable, and when it does get discovered, people likely are way past the need for a product tour. The most likely place and time where people run into it (other than when they first open composer) is on the home page when they are figuring out what to do next. I don't think there is harm in placing it there. Can we do so?
