### ISSUE TITLE
Clip copy and add ellipses if it doesn't fit the tile template

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7073]
In 1.4 nightly - 232669.4daad5c, Go to the home page.
Click 'Videos'
Notice that the copy from the tiles is too long and spills onto the canvas instead of getting clipped.

<img width="1054" alt="Screen Shot 2021-04-17 at 6 58 37 PM" src="https://user-images.githubusercontent.com/48503434/115131749-40315480-9faf-11eb-943f-2466a609b710.png">

Proposed:
Clip title to 34 characters
Limit description to 2 lines of copy ( Tile width: 253px). Add ellipses which, on click, show the full copy in a tooltip.
Limit button label to 34 characters.

Note: @xiyangdesign please check in with Randy to get a tile with a smaller thumbnail size - the current tiles have square thumbnails (vs the rectangular you have) which makes them too big and push too much content to below the fold. We do need to follow their guidelines, but need to get them to make a smaller tile size for us.

**Comment by cwhitten** [comment]
@mareekuh here is what I see on latest: 

Version:  1.4.0-nightly.236490.3735dd3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

<img width="1166" alt="Screen Shot 2021-04-18 at 7 43 54 AM" src="https://user-images.githubusercontent.com/1156704/115149644-d9955080-a019-11eb-925f-d3b130dd77fc.png">

**Comment by cwhitten** [comment]
Will preemptively close this. Reach out with additional questions/concerns. Thanks!

**Comment by mareekuh** [comment]
Sounds good, thank you... I'd do the close-open-reboot dance a few more times so I'm looking at the latest (-:
