### ISSUE TITLE
Export bot is not included package

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7074]
## Describe the bug

Export bot is not including package reference

## Version

Version:  1.4.0-nightly.236319.b7f3fe8
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1.	Created a new bot and added new package ex: “Microsoft.Bot.Components.Teams“
2.	Export the bot.
3.	(Import again) Open the exported bot in composer ,goto package manager check packagae is avaliable or not( the package is missing)

## Expected behavior

Package should be include.

## Screenshots

![image](https://user-images.githubusercontent.com/16264167/115135743-29c0e280-a01b-11eb-9e6b-f9a6df30a65d.png)

**Comment by benbrown** [comment]
@rvinothrajendran Looks like the export process only includes the assets directly managed by Composer, not the runtime and code files.

We'll consider an update to this for an upcoming release.

**Comment by benbrown** [comment]
@rvinothrajendran If you need an archive of your entire project, you should be able to zip the folder directly using your operating system.
