### ISSUE TITLE
Project open dialog is not refresh 

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7075]
## Describe the bug

Project open dialog is not refresh ( cancel and reopen )

## Version

Version:  1.4.0-nightly.236319.b7f3fe8
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1.	Open the project dialog (ex: c:\temp)
2.	Manually copy the new folder in c:\temp path
3.	Cancel & open the project dialog 
4.	Not showing the new folder (copied step 2)

## Expected behavior

Should show updated folder information

## Screenshots

![image](https://user-images.githubusercontent.com/16264167/115135994-09922300-a01d-11eb-99e3-06a429358f6a.png)

**Comment by cwhitten** [comment]
hello @rvinothrajendran and thanks for the bug report. we'll seek to address this in an upcoming release. putting on our product backlog for now.
