### ISSUE TITLE
Restart selected bot with single click

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7076]
## Is your feature request related to a problem? Please describe.

#7049

If multiple bot is running , there is no easy solution to restart the particular bot , current approach we have restart all the bots or stop and start selected bot.

![image](https://user-images.githubusercontent.com/16264167/115144257-02ced480-a04c-11eb-9e3d-76c5df3c7fe0.png)

## Describe the solution you'd like

If user has selected overall project 

![image](https://user-images.githubusercontent.com/16264167/115144402-b8018c80-a04c-11eb-922c-5d4ca8f20ce6.png)

If user selected particular bot then restart only particular bot instead of all

![image](https://user-images.githubusercontent.com/16264167/115144420-cb145c80-a04c-11eb-982c-35a40d7ccff6.png)

![image](https://user-images.githubusercontent.com/16264167/115144512-58f04780-a04d-11eb-9cc1-8356228f156d.png)

**Comment by benbrown** [comment]
@sangwoohaan Can you take a look at this? I believe this is as designed, but want to confirm with you.
