### ISSUE TITLE
Discoverability: On clicking "webchat" icon, initiate 'Start bot' if it's not already running

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7077]
When the user has not yet clicked 'start run bots', the webchat button is disabled, and in the diagnostics panel, webchat says ' No Web Chat activity yet ' but nothing is actionable so the user has to figure out what it's not working.

Expected:

1. Enable the 'webchat' icon and if the bot is not running yet, initiate "start run" automatically.
2. In the diagnostics panel, have an actionable item that initiates the bot running and shows the webchat.
. <img width="477" alt="Startbot_automatically_for_webchat" src="https://user-images.githubusercontent.com/48503434/115157590-eed0a600-a03e-11eb-90b1-c2aa77902344.png">
3. In the diagnostics panel, update the font size to be the same size as the label vs a large font size.
<img width="407" alt="ReduceFontsize_error_or_status_message" src="https://user-images.githubusercontent.com/48503434/115157585-e7a99800-a03e-11eb-953f-d109fa05642d.png">
7. 
8. 
9.

**Comment by mewa1024** [comment]
Good catch. It should be this:

![image](https://user-images.githubusercontent.com/39317542/115335546-457ad480-a152-11eb-8571-cc832cfa0bf4.png)

12px font. Link to the Figma spec:
https://www.figma.com/file/HwYEQoCmWbNrIDdCOmGvzN/bot-testing-BRAINS-storm?node-id=1087%3A17886

**Comment by mewa1024** [comment]
Adding screenshot for both messages, when the bot is not running and when bot is running but Web Chat is not open:
![image](https://user-images.githubusercontent.com/39317542/115474216-d5239000-a1f1-11eb-9daf-dd871dee89e3.png)

"Start your bot" is the same as clicking the "Start all bots button".
"Test in Web Chat" is the same as clicking the "Test in Web Chat" button from the runtime manager (the dropdown menu from the Start button).
