### ISSUE TITLE
Webchat toolbar buttons (and any other toolbar buttons that only have an icon and no label) need tooltip to show label

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7079]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by mewa1024** [comment]
@mareekuh is this a dupe of #7080?
