### ISSUE TITLE
Visual fix needed  - 'English (United States): please select standard Fluent look and feel 

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7081]
In the top header/toolbar, the selected language is indicated in an unusual custom control. As it's a custom icon, it will needs custom accommodation to support accessibility, theming, reflow and screen size changes, it does not set the correct expectations in terms of behavior, and shown even when not adding value.

1. - Most standard bots only support EN-US, so this control is not informative or actionable as it is the default and cannot be changed from this control
2.  The item is clickable and shows a dropdown but there is no indicator to set the expectation that is is clickable nor that it's a dropdown
3. This custom control with custom dark blue color stretches in odd ways: when increasing screensize, the unusual corner radii of the control stretch and increase vs remaining a fixed size following nine-grid button specs. 

Expected:
1. Only show when more than one language is supported and enabled
2. Choose a standard Fluent control that scales, adheres to Fluent (including accessibility guidelines), preferably not a dropdown 
3. Does not attract unnecessary attention (changing the language is a very specific, and un-frequent action and therefore does not deserve primary focus/real estate).

<img width="536" alt="ninegrid_button_spec" src="https://user-images.githubusercontent.com/48503434/115158644-078f8a80-a044-11eb-9f34-41c6f6dc3637.png">
<img width="622" alt="EN US custom control" src="https://user-images.githubusercontent.com/48503434/115158647-08c0b780-a044-11eb-852e-ec88cd406e24.png">

**Comment by mewa1024** [comment]
Will investigate in R14.
