### ISSUE TITLE
Bot response modality UI, detailed feedback

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7085]
1. - go to 'greeting' trigger
2. - Click '+' menu next to 'text" (bot responses)
3. - Notice that the menu has an instruction at the top (in blue)
4. And (i) buttons for each of the menu items, which means that every menu item has 2 click targets - I don't think this will pass accessibility)
5. Notice that when clicking any of the options in the menu, the following 
- The selected modality gets added (next to  the 'Text' tab)
- The selected modality is removed from the menu
- There is no button or other to remove the modality from the toolbar

Expected:
1. Menu should not have an instruction and definitely not in blue. The 'instruction' can be shown on hover over the + icon (aka tooltip)
2. Menu items are 1 click targets - remove the (i)
3. When clicking a menu item, add the modality to the 'tabs' next to 'Text'
4. Show the tooltip content (shown when clicking (i) as watermark text
5. Replace 'add <added modality> ' to 'Remove <added modality >
6. If the user clicks 'Remove <added modality > and no content was entered prior, just remove the tab (and switch the menu item back to 'Add <modality>; If the tabl DID have content, show an 'Are you sure to remove < Modality> and its content' y/n'

BTW I have no idea what 'accepting/ignoring/expecting' UI is all about...Simplify and use standard UI, please?

<img width="357" alt="Screen Shot 2021-04-18 at 3 14 38 PM" src="https://user-images.githubusercontent.com/48503434/115162784-47616c80-a05a-11eb-9d48-672956db0dfd.png">

<img width="344" alt="Screen Shot 2021-04-18 at 3 21 43 PM" src="https://user-images.githubusercontent.com/48503434/115162828-87c0ea80-a05a-11eb-8c8b-3ab9edc60fa5.png">

**Comment by mewa1024** [comment]
Thanks, @mareekuh. For any new bugs, can you use the "R13 bugbash" labels? I think that helps with triage.

**Comment by mewa1024** [comment]
Hi @mareekuh, adding screenshot to clarify your suggestions. Can you confirm/correct?

> 1. Menu should not have an instruction and definitely not in blue. The 'instruction' can be shown on hover over the + icon (aka tooltip)
> 2. Menu items are 1 click targets - remove the (i)

![image](https://user-images.githubusercontent.com/39317542/115323935-d6938080-a13d-11eb-900d-2dcc405f03db.png)

so instead there should be tooltip over the + button that says "Add response modality. Learn more." like this:

Hover:

![image](https://user-images.githubusercontent.com/39317542/115324762-4e15df80-a13f-11eb-99b6-312658108309.png)

Pressed:

![image](https://user-images.githubusercontent.com/39317542/115324902-8cab9a00-a13f-11eb-9a00-8536db45d7c2.png)

`4. Show the tooltip content (shown when clicking (i) as watermark text
`

so this text:

![image](https://user-images.githubusercontent.com/39317542/115325320-3a1ead80-a140-11eb-839a-0feb754fc018.png)

becomes this:

![image](https://user-images.githubusercontent.com/39317542/115325390-62a6a780-a140-11eb-827f-2c12806da028.png)

**Comment by sangwoohaan** [comment]
Addressed in https://github.com/microsoft/BotFramework-Composer/issues/7352
