### ISSUE TITLE
Package manager blank page( not always)

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7086]
## Describe the bug

Package manager sometimes show as blank view. but not always recreate

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

randomly click different views

## Expected behavior

view should be load

## Screenshots

![image](https://user-images.githubusercontent.com/16264167/115178234-26882e00-a0d1-11eb-9bd4-8d7ea4d734e9.png)

**Comment by benbrown** [comment]
@rvinothrajendran Thanks for the report. Do you know if any errors appear in your JS console when this happens?

I'll try to reproduce here.

**Comment by rvinothrajendran** [comment]
@benbrown oh missed that 😥

**Comment by GeoffCoxMSFT** [comment]
@rvinothrajendran Is your issue resolved? Could you include any console errors you see?

**Comment by rvinothrajendran** [comment]
@GeoffCoxMSFT seems to be working fine .. I'm not able to recreate this issue.
