### ISSUE TITLE
LUIS build fails with reason "undefined" after adding the 11th phrase list

### ISSUE THREAD

**Issue by mbinic** [microsoft/BotFramework-Composer#7089]
## Describe the bug

LUIS build fails with reason "undefined" after adding the 11th phrase list.

## Version

Version:  1.4.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to any intent trigger(s) and add 11 simple phrase lists
2. Click on 'Start Bot'
3. Once it fails to start, click on 'See Details'
4. See error "Luis build failed: undefined"

## Expected behavior

I expect to see an informative error message with a reason as to why it failed.
In this case, the luis.ai portal shows "BadArgument: The phraselist features allowed per model cannot exceed the limit 10.".

## Screenshots

![image](https://user-images.githubusercontent.com/3247708/115221109-9ca88700-a109-11eb-9e43-1d95c4f6c469.png)

**Comment by chrimc62** [comment]
This looks to be a bug in luis:build where the error is not being picked up properly.  @cosmicshuai  or @boydc2014  can you take a look?

**Comment by cosmicshuai** [comment]
![image](https://user-images.githubusercontent.com/17074777/115347135-9e467d80-a1e3-11eb-8ac9-9c679c42f549.png)
Trying to reproduce this in bf-cli. The luis:build command has returned the same error info as the Luis portal. Will look into the Composer code to see where neglect the error message.

**Comment by cosmicshuai** [comment]
https://github.com/microsoft/botframework-cli/pull/1214 
I have fixed it in the bf-cli, after it is merged, I will update the version in Composer. This would solve this issue.

**Comment by tsuwandy** [comment]
@cosmicshuai, has this issue been resolved with the fix in bf cli?

**Comment by cosmicshuai** [comment]
I have a pr for this in Composer
