### ISSUE TITLE
[Bot Runtime Migration] Run time error for "echo bot" with bot runtime migration 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#7090]
- create a bot based on composer legacy template (eg. echo bot)
- open with bot runtime migration branch 
- run bot will hit following errors
![image](https://user-images.githubusercontent.com/43408889/115234206-56741780-a14b-11eb-9b60-49893c8d73c1.png)

**Comment by benbrown** [comment]
Should be resolved by this commit: 

https://github.com/microsoft/BotFramework-Composer/pull/6526/commits/92ae67f766a6e5a112c2e312a317faee687aaaa1
