### ISSUE TITLE
[bot runtime migration] UX should show bot runtime type 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#7091]
- create a bot against legacy bot template 
- open in bot runtime migration branch
- start to convert old bot will hit following 
![image](https://user-images.githubusercontent.com/43408889/115234543-ba96db80-a14b-11eb-8b9f-2700f0637b03.png)

Runtime type should not be empty

**Comment by mewa1024** [comment]
Should be the same as creating a bot from scratch, right? Default set to "Azure Web Bot" and dropdown menu has Azure Web App and Azure Functions?
![image](https://user-images.githubusercontent.com/39317542/115301390-fc0c9400-a115-11eb-8557-270e0cd83f25.png)

(@benbrown ?)

**Comment by Dewain27** [comment]
Also need to add a required field *

**Comment by benbrown** [comment]
@pavolum  during migration, we should ALSO show the JS/Dotnet option as a dropdown here.

**Comment by sgellock** [comment]
Shiproom - will be included with the other migration work/PR

**Comment by pavolum** [comment]
Doing a PR into the migrate branch now, will add js/charp dropdown

**Comment by benbrown** [comment]
This was merged into the main migrate branch from #7460.
