### ISSUE TITLE
EventReceived Trigger not working in Bot Composer 1.4.0

### ISSUE THREAD

**Issue by LakshummaC** [microsoft/BotFramework-Composer#7097]
Hi Team,

This is what I have followed for handling an event sent from HTML file in Bot composer.

**_### In HTML:_**
```js
const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
    if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
        dispatch({
            type: 'WEB_CHAT/SEND_EVENT',
            payload: {
                name: 'getUserID',
                value: 'abcd'
            }
        });
    }
    return next(action);
});
```
### **_In Composer:_**

Added below trigger

![image](https://user-images.githubusercontent.com/76558423/115273316-056d1f00-a15d-11eb-807e-302d6da0ca5e.png)

![image](https://user-images.githubusercontent.com/76558423/115273436-2afa2880-a15d-11eb-8b8a-feb633725143.png)

Along with the above event trigger, I have Greeetings(ConversationUpdate) which will prompt the mainmenu of chatbot.

Composer not saving above HTML event value, Am I missed anything?

Tried turn.activity.value and other ways also but no use. I need solution ASAP.

Thanks much in advance,

**Comment by LakshummaC** [comment]
Any update on the above issue, other than assigning to persons?

**Comment by stevkan** [comment]
@LakshummaC, in addition to the values you have set above on the 'Event activity' trigger, can you also set the 'Run Once' property to `true` and test, again? I am finding that, if I have that property set to anything other than `true`, then I get the error 'Object reference not set to an instance of an object' returned. It's possible that this is getting masked somehow when you attempt the same. When set to `true`, I am able to trigger the `Event activity` from Web Chat and get the passed in value.

**Comment by LakshummaC** [comment]
@stevkan I tried as you said with 'Run once' as true but still the event is not getting triggered. Is that fine if In Main Project I have 'conversation Update(Greetings)' and 'Event Received' individually (Shown below), or do I need to add something?
![Uploading image.png…]()

**Comment by LakshummaC** [comment]
Hi @Stevenic after I did these changes the event if triggered.

1.Enabled below options in Greeting
![image](https://user-images.githubusercontent.com/76558423/115698889-bd2f4600-a382-11eb-8031-cfdd3dd561a4.png)

2.Enabled below options in Event Received
![image](https://user-images.githubusercontent.com/76558423/115698926-c6201780-a382-11eb-922c-3ef73bfcf97f.png)

and I am able to fetch value from front end HTML as shown below:
![image](https://user-images.githubusercontent.com/76558423/115698797-a4269500-a382-11eb-908f-e849f0850043.png)

But after reading the above screenshot Event value, I am prompting hero card options in **Greetings** which is not happening here.

It just read the event and nothing prompted from Greetings.

Why is that so?

**Comment by stevkan** [comment]
You don't want to set the Greeting's ConversationUpdate activity condition to `false`. Either leave it blank or set it to `true`. Setting it to `false` is telling it to never run. Also, for _this_  trigger, you do not want to set 'Run Once' to `true`. Keep its value as blank or set to `false`. Setting it to `true` I believe is telling it to run only on the first 'conversationUpdate' which I also believe is when the bot joins. So, it won't fire for a user joining.

![image](https://user-images.githubusercontent.com/18403946/115763707-9872a880-a359-11eb-9ace-b1e76cbade8f.png)

Regarding calling the hero card that is in the Greeting, the Greeting will _only_ fire on a 'conversationUpdate'. There isn't a way to send this from within Composer as the bot is typically responding to this event coming from an external source (i.e. Web Chat, Facebook, etc.) to indicate a member has joined. If you want to call the hero card, again, then you will need to move/copy it to a separate dialog that you can then call from within the Event activity.

**Comment by LakshummaC** [comment]
Thanks @stevkan , I have followed the approach as you said above. Issue is resolved. Thanks much for your support.
