### ISSUE TITLE
Dropdown list of publish profiles too narrow to disambiguate

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#7102]
## Describe the bug

If you go to the publish page and choose the publish profiles dropdown, it's too narrow to review.

## Version

Version:  1.4.0-nightly.236490.3735dd3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1) create two publish profiles with the same name for the first 8 characters of the dropdown and save
2) Try to disambiguate at runtime

## Expected behavior

Dropdown is appropriately wide for the content.

## Screenshots

![image](https://user-images.githubusercontent.com/5997512/115281075-78df4400-a0fd-11eb-9e76-858c2b588b63.png)

**Comment by mewa1024** [comment]
(@emivers8 , @JaskeeratBedi-cmk can we make the dropdown menu as wide as the max length for publishing profile names?)

**Comment by OEvgeny** [comment]
Fixed in newer releases
