### ISSUE TITLE
Open In Composer -> Connect to Existing Bot overwrites list of existing publish profiles

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#7104]
## Describe the bug

Created a bot and created two publish profiles.  As a testing experiment, I created a new Azure bot and told it to download in composer and chose "connect to existing bot".  The new publish profile was created, but my prior two were overwritten.

## Version

Version:  1.4.0-nightly.236490.3735dd3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create bot
2. Create publish profiles
3. Create a new bot in the Azure portal and choose open in composer
4. In composer, choose connect to existing bot
5. Process completes, but first two publish profiles are missing

## Expected behavior

Don't delete on write, or notify me so I can cancel in advance.

**Comment by cwhitten** [comment]
The requirements were to add to the list of profiles, not modify or delete any existing profiles. cc @luhan2017
