### ISSUE TITLE
Main dialog options work in sub-dialogs

### ISSUE THREAD

**Issue by vanshu86** [microsoft/BotFramework-Composer#7105]
## Describe the bug
Main Dialog triggers getting triggered in sub-dialogs – I set allow interruptions to true in sub-dialogs prompts with text, with this the triggers are working in sub-dialogs (otherwise they dont get hit), however if you are in a sub-dialog, pressing any main menu options also works, how can I change this behavior, with false the subdialog trigger also doesn’t work. 

## Version
1.4
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

Create trigger based sub-dialogs to the main dialog. 
Run emulator, the triggers not triggering the subdialogs, I had to enable allow interruptions to true, then this scenario worked. 
But after this even in sub-dialog context the main dialog triggers are working 

## Expected behavior
Subdialog trigger should just work without having to enable allow interruptions 
Main dialog triggers should not work in sub-dialog

## Screenshots

![image](https://user-images.githubusercontent.com/81776469/115282361-ffe0ec00-a0fe-11eb-86f7-a9873f56143c.png)

**Comment by cwhitten** [comment]
Hi @vanshu86 - this is actually by design with the interruptions system. Please see https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-help for explanation on this technique.
