### ISSUE TITLE
Clicking on "Enable Insights" in rocket menus takes us to microsoft.com

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/BotFramework-Composer#7108]
## Describe the bug

Clicking on "Enable Insight" in the rocket menu takes us to microsoft.com. The original linked aka.ms/botinsights seem to not be setup properly.

## Version

Version:  1.4.0-nightly.236155.f2b2823
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new Enterprise Assistance template
2. Click on "Enable Insight" link on the rocket menu in the right

## Expected behavior

Goes to Azure portal about Application Insights

## Screenshots

![image](https://user-images.githubusercontent.com/9922190/115286366-d8d8e900-a103-11eb-9033-3d6c433908c6.png)

**Comment by Dewain27** [comment]
Known issue awaiting doc to be written and then will update link to new location.

**Comment by Dewain27** [comment]
Got link updated to new doc.
