### ISSUE TITLE
Bot creation starting with Azure Bot doesn't populate initial publishing profile correctly

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#7109]
## Describe the bug

The bot's app ID is present in Azure, but isn't populated when I create a publishing profile.

## Version

Version:  1.4.0-nightly.236490.3735dd3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create Azure Bot resource
1. Open it in Composer
	- Create new Basic Conversation Bot.
	- **Q**:What's going on at the tail end, when I see the message "Created Successfully" and the spinner still goes for what seems like another minute?
1. Create LUIS key (login to Azure, twice)
1. Create publishing profile (login to Azure, again)
    1. Almost immediately confused.
        - **Q**: Why isn't some of this information already pre-populated?
        - Guess: I created the bot resource, and I still need to create the Azure AD app registration and Web App resource.
    1. **Error**: At the tail end of all the windows, it asks me to provide the _Bot Channels Registration_ ID or create a new one!
        - Azure already created an _Azure Bot_ app ID. Why is this missing from my bot's profile?

## Expected behavior

Information that Azure created should be pre-populated, at least the first time I create a publish profile.

## Screenshots

Waiting screen, where Composer seems to be doing...nothing?
![saved](https://user-images.githubusercontent.com/35047199/115290339-438c2380-a108-11eb-8ec6-aab8544fe449.png)

**Comment by Dewain27** [comment]
@emivers8 Looks like the key challenge here is the lack of clarity that project settings are setting up your local development environment and not the publishing profile and/or target.
