### ISSUE TITLE
Orchestrator package not showing up in package manager

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7112]
## Describe the bug

Orchestrator package doesn't show up in Package Manager - in the default npm feed. If you switch to community then it does show up but it's not a community package?

![image](https://user-images.githubusercontent.com/33519520/115296376-cb971b00-a152-11eb-9975-5cdb0a9710eb.png)

![image](https://user-images.githubusercontent.com/33519520/115296790-51b36180-a153-11eb-9318-3f0f1625c293.png)

## Version

1.4.0-nightly.236490

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to package manager
2. Orchestrator not shown
3. Switch to community feed

## Expected behavior

- Shows up in main feed

**Comment by taicchoumsft** [comment]
Current nuget query is `microsoft.bot.components+tags:msbot-component`.  

Suggest changing to `microsoft.bot+tags:msbot-content,msbot-recognizer,msbot-action`, these tags were added by @carlosscastro in SDK components. Does this work @benbrown , @peterinnesmsft ?

![image](https://user-images.githubusercontent.com/61705609/115470256-e1f0b580-a1ea-11eb-9eb6-abd987f7e8b0.png)

We probably should then remove Microsoft packages from community, that's probably another work item I think.

**Comment by benbrown** [comment]
I think all components, regardless of type, are supposed to have msbot-component.
