### ISSUE TITLE
language picker app menu looks un-clickable and tight

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#7116]
## Describe the bug
The language selector in app bar looks non-clickable, and very tight as a button. 
As a user would you understand to click on it. 

Suggest: show more button style (thicker) or tag styled button, potentially user chevron downwards (open trigger)  
![image](https://user-images.githubusercontent.com/43533472/115302133-5d5a5480-a162-11eb-9515-9ac808622e95.png)

## Version
Version:  1.4.0-nightly.236088.ef8eb11
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/115301543-9fcf6180-a161-11eb-81d5-26fda35b7692.png)

Thin and no visual clue it's clickable:
![image](https://user-images.githubusercontent.com/43533472/115301632-c42b3e00-a161-11eb-8d85-25017077f859.png)

**Comment by OEvgeny** [comment]
Fixed in the latest nightlies
