### ISSUE TITLE
Connecting speech resource during channel configuration doesn't bind speech key in Azure portal

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#7117]
## Describe the bug

Created a new bot and configured the speech channel in my bot in the composer including creating a new speech resource.  Once I navigated to Azure to review, I determined that the speech resource had not been associated with the speech channel in the ABS portal.

## Version

Version:  1.4.0-nightly.236490.3735dd3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create bot & publish profile
2. Publish to Azure
3. Go back and add the Speech channel, including creating a new speech resource
4. Publish and review in Azure portal

<Speech resource has not been bound to the speech channel>

## Expected behavior

Speech resource should be bound

**Comment by benbrown** [comment]
This is a bug in the portal itself, @jameslew. The key is sent via the API, but does not appear in the portal.

**Comment by cwhitten** [comment]
@jameslew please make sure this is tracked on the ABS side.

**Comment by Andrea-Orimoto** [comment]
We confirmed that Autumn on the ABS side is working on a fix for this.
