### ISSUE TITLE
Bot responses page: "Been Used" flag is confusing

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#7118]
## Describe the bug

The "Been Used" flag on the Bot Responses tab is confusing. It does not flag a template as being used, when it is in fact, well used. Notice in the screenshot below only the .lg section containing the pointer to the actual responses is marked as used.

![image](https://user-images.githubusercontent.com/1139814/115310131-2a906c00-a122-11eb-84a5-68feb9826db2.png)

## Version

Daily

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a Core with Language (conversational core) bot
2. Go to Bot Responses tab
3. Observe .lg file

## Expected behavior

If we have a flag for is some section of the .lg is used, it should indicate that the section is used.

**Comment by mewa1024** [comment]
(@sangwoohaan I know "Been used" was not the original design--is there a short term fix for this?)

**Comment by cwhitten** [comment]
Been used was in the original design, perhaps before Sangwoo joined the team.

**Comment by clearab** [comment]
I'm less worried about the "Been used" label, and more that the .lg sections with the underlines in the screenshot above have definitely been used (they are referenced by the sections with the check marks).

**Comment by mewa1024** [comment]
@clearab so are the Been Used flags marking only the templates are directly references by an Send Activity or prompt?

**Comment by clearab** [comment]
That seems to be the case - I think the point of that flag is to let me know if I could safely delete one of those sections or not. I definitely cannot delete the ones that are not flagged as "been used"

**Comment by mewa1024** [comment]
related: #6968

**Comment by mareekuh** [comment]
Original design had a flat list (across all dialogs) of all LG Content, just like LU (LU/LG were designed as similar as possible. The left nav includes 'all' * which is a flat list of all bot responses, allowing uses to go through the all content, add alternative, translate etc. but also jump to the dialogs in which the response is used so they see the copy in context.
The list view includes (body of page) the following columns for : Template name  | LG content | Used in... | Date modified

'Common' came in as a temporary solution as we could not yet do the 'all' list.
No idea where 'been used' came from. It should be: used in.

* requirement based on interviews with (Conversation) Content writers  for Cortana, Skylight, PVA and others).

**Comment by OEvgeny** [comment]
Closing, seems design changed. Feel free to reopen if still relevant
