### ISSUE TITLE
Bot Composer, LUIS, QnaMaker + Teams = Operation returned an invalid status code 'BadRequest'

### ISSUE THREAD

**Issue by venegasmi** [microsoft/BotFramework-Composer#7120]
## Describe the bug

I built a bot using the Bot Framework Composer with LUIS +QnAMaker and deployed it to Azure. On Azure Web Chat, it works perfectly fine. However, when adding Teams as a channel and testing it, it returns "Operation returned an invalid status code 'BadRequest'" after every message.

## Version
1.4.0
## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

1. Publish Bot to Azure
2. Go to Channels and add Teams
3. Click on Teams and launch on the desktop app
4. Ask something to the bot

## Screenshots

<img width="623" alt="Capture" src="https://user-images.githubusercontent.com/69607565/115313594-cd4fe700-a130-11eb-8190-9daee9173b8d.PNG">

## Additional context

All answers from the bot (texts and images) are retrieved from QnAMaker.

In Azure - Bot Channel Registration -> Channels -> Teams, there are a few warnings, all saying "Activity must include non empty 'text' field or at least 1 attachment"

**Comment by benbrown** [comment]
@venegasmi What format is the QNA response in?  Can you show the raw value of your QNA response here?

**Comment by venegasmi** [comment]
This is a screenshot from the qnas in QnAMaker, its just text or HTML for images. 

<img width="796" alt="bug" src="https://user-images.githubusercontent.com/69607565/115440569-1f464a80-a1cd-11eb-91fb-533324972252.PNG">

In the Bot Framework Composer, I just connect directly to QnAMaker.

<img width="341" alt="myintent" src="https://user-images.githubusercontent.com/69607565/115440640-3422de00-a1cd-11eb-9d04-683dc93f753d.PNG">

**Comment by benbrown** [comment]
@venegasmi thank you for the additional info! This will help us get to the root problem. It seems like something is mis-translating the QNA response into an empty message.

**Comment by venegasmi** [comment]
@benbrown I just realized that the problem was the suggested action card displaying 'Restart Conversation' option. I did not know that Teams doesn't support suggested action cards. Just changed it to a hero card and everything is working as expected. Thanks for wanting to help!

**Comment by benbrown** [comment]
thanks for following up, @venegasmi!
