### ISSUE TITLE
Add LUIS Key via "Handoff to admin" fails w/ broken link

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7124]
## Describe the bug

The link provided for "Detailed Instructions" redirects to the Microsoft.com page. 
https://aka.ms/bfcomposerhandoffluis

Network Trace shown here:
![image](https://user-images.githubusercontent.com/1165321/115321069-ef009c80-a137-11eb-97f9-34fa9e70891a.png)

## Browser

- [X] Electron distribution

## OS

- [X] Windows

## To Reproduce

Add LUIS key via Handoff to Admin:
![image](https://user-images.githubusercontent.com/1165321/115320865-81ed0700-a137-11eb-9b37-6de8fe38f737.png)

Read the instructions:
![image](https://user-images.githubusercontent.com/1165321/115320901-93ceaa00-a137-11eb-9474-9aa74cb839a8.png)

Follow the link:
https://aka.ms/bfcomposerhandoffluis

Observe the link has no instructions:
![image](https://user-images.githubusercontent.com/1165321/115320941-ab0d9780-a137-11eb-8f4e-0351c7842e59.png)

## Expected behavior

The link provide gives me instructions about what to do.

**Comment by Dewain27** [comment]
Known issue waiting for #7107 to be completed to allow for documentation to be created in #6258
