### ISSUE TITLE
"Learn More" link for "Create new LUIS resource" is missing

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7125]
## Describe the bug

On the screen for "Create New LUIS resources", there is text that says "Learn more". 

This text:
1. Is missing a "." at the end.
2. Has no Hyperlink associated with it. 

![image](https://user-images.githubusercontent.com/1165321/115321264-53236080-a138-11eb-86e3-1a41e7cf3122.png)

## Version

Version:  1.4.0-nightly.236875.b9e46c2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution

## OS
- [X] Windows

## To Reproduce

Add a new LUIS key via the Window:
![image](https://user-images.githubusercontent.com/1165321/115321402-92ea4800-a138-11eb-92cb-a10156773264.png)

Select a subscription. 
Select "Create new LUIS resources"
Read the text. 

## Expected behavior

A hyperlink that lets me learn more, as the text indicates.

**Comment by Dewain27** [comment]
Make hyperlink:
https://aka.ms/composer-luis-learnmore
