### ISSUE TITLE
UX on "Create new LUIS resources" screen

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7127]
## Describe the bug

Several UX issues on this screen:
![image](https://user-images.githubusercontent.com/1165321/115321884-a77b1000-a139-11eb-8caa-149e95975c41.png)

The issues are:
1. The "*" on the LUIS region and "resource name" text is a mystery. What does the "*" mean? 
2. The dialog is "LUIS resources" (plural), but the text is "Resource name" (singular). The previous screen calls this "resource" (singular) Which is it? The text across these screens needs to align. 

![image](https://user-images.githubusercontent.com/1165321/115322142-3556fb00-a13a-11eb-9f87-1186d43ff21a.png)

3. "Input your details below". I'm not picking any details. The text here needs some tweaking. 
4. The "Learn more" text (no ".") needs a hyperlink (I created a separate bug to track that). 
5. The "Resource group:" has a ":" at the end. The other fields do not.

The "Resource group" appears to be required, despite not having the "*" field. 
![image](https://user-images.githubusercontent.com/1165321/115333154-05b1ee00-a14e-11eb-9d86-558a92f93ab4.png)

## Version

Version:  1.4.0-nightly.236875.b9e46c2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by mareekuh** [comment]
@JonathanFingold  - I think these are updated, yes?

**Comment by JonathanFingold** [comment]
Some of the UI has changed, and some of the issues have been resolved, but at a minimum (as of Version:  2.0.0-nightly.260493.e017820) there's at least one remaining issue.

Repro steps:
1. Go to the **Configure your bot** view.
2. Select **Development resources**.
3. Select **Set up Language Understanding**.
4. Create and configure new Azure resources.
5. Select an Azure subscription.
6. See error: On the **Create Language Understanding resources** page, the **Azure resource group** field is not marked with a red asterisk to indicate it's required.

    ![image](https://user-images.githubusercontent.com/35047199/126563305-6186b65f-2b77-40bb-8503-96e7a99a3dd8.png)

You may want to close this and open a new tracking issue.

Not sure why I was asked to check on this one. :\

**Comment by JonathanFingold** [comment]
Oh, If you're asking about the docs getting updated. We're still waiting to update screen shots until the GA version of Composer for R14 is released.

**Comment by OEvgeny** [comment]
Closing as LUIS is getting deprecated and the bug is fixed
