### ISSUE TITLE
"Select LUIS keys" doesn't talk about keys. Conflating keys and resources

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7128]
## Describe the bug
The initial action item was "Add a LUIS key". The dialog is "Select LUIS keys". 
![image](https://user-images.githubusercontent.com/1165321/115322390-d776e300-a13a-11eb-94e2-8f62b9bbd310.png)

The screen calls them resources. 
![image](https://user-images.githubusercontent.com/1165321/115322251-7f3fe100-a13a-11eb-975c-92770a02f611.png)

When I go down the "Create new" path, they're still all resources, not keys:
![image](https://user-images.githubusercontent.com/1165321/115322311-a696ae00-a13a-11eb-80b7-e4f625070337.png)

Why did I go down the "Add a LUIS key" path, if I'm creating resources. The wording of this all needs to be revved. 

The final dialog has the same issues:
![image](https://user-images.githubusercontent.com/1165321/115332790-63920600-a14d-11eb-868c-ad50e5a5460d.png)

## Version

Version:  1.4.0-nightly.236875.b9e46c2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution

**Comment by mewa1024** [comment]
Hmm. But is what is actually saved to Composer the key string for the resource you created? So in that sense, is it correct as is? But does it need to be clearer? @emivers8 ?

**Comment by cleemullins** [comment]
@mewa1024  What's actually saved doesn't matter here - at least not to most users. The issue is the wording needs to be consistent, and to match the words that LUIS, QnA Maker, and Azure all use. 

A dialog about keys that has text all about resources (but not keys) is confusing.

**Comment by emivers8** [comment]
@mareekuh another thing to add to the copy list--context with regards to the need for alignment is important. I'll add to the spreadsheet.

**Comment by pavolum** [comment]
assigning to @mareekuh as she is consolidating all copy fixes in to a single issue

**Comment by mareekuh** [comment]
[Included in xls on 'Add LUIS' tab. 
](https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea
)In progress

**Comment by mareekuh** [comment]
Adding to this...
The 2nd field is labeled as LUIS key, but is the LUIS resource name...

![Screen Shot 2021-04-27 at 12 59 37 PM](https://user-images.githubusercontent.com/48503434/116305374-8bd6c180-a758-11eb-9f27-1a6fa355b031.png)

**Comment by mewa1024** [comment]
@cleemullins @mareekuh then I say we use "Resource" which is what we did for the UI in LUIS.ai, except for the UI that literally showed you the strings for your primary and secondary keys.

**Comment by mareekuh** [comment]
I am working on this here so we can see it all together in one place vs bug by bug
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

**Comment by mewa1024** [comment]
"key" was replaced with "resource" in Composer 2.0:
![image](https://user-images.githubusercontent.com/39317542/123052252-7a581180-d3b7-11eb-977f-45ff80dcf8ec.png)
