### ISSUE TITLE
Resource (LUIS / QnA) Dialogs can be closed during resource create

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7133]
## Describe the bug

While creating resources (QnA / LUIS) the Back/Next/Cancel buttons are greyed out. 

However the "X" in the top right remains functional. Closing this during resource creation seems to have unexpected consequences. 

![image](https://user-images.githubusercontent.com/1165321/115334085-94733a80-a14f-11eb-8a22-b90c8228e1a2.png)

## Version

Version:  1.4.0-nightly.236875.b9e46c2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by mewa1024** [comment]
(@emivers8 @JaskeeratBedi-cmk remove the X?)
