### ISSUE TITLE
Link for 'https://aka.ms/bfcomposerhandoffqnamaker' goes nowhere

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7134]
## Describe the bug

When creating a QnA Maker resource, I can select "Handoff to admin". 
![image](https://user-images.githubusercontent.com/1165321/115334520-66422a80-a150-11eb-8a74-5af123eae2c0.png)

When I do that, I get this screen:
![image](https://user-images.githubusercontent.com/1165321/115334544-71955600-a150-11eb-8ddd-d0a917a62842.png)

The URL https://aka.ms/bfcomposerhandoffqnamaker goes nowhere. 

## Version
Version:  1.4.0-nightly.236875.b9e46c2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by Dewain27** [comment]
#6258 has not been completed.  Once that is completed then the documentation link will be updated.  We are also awaiting #7107 to be completed to ensure that we can properly document.
