### ISSUE TITLE
Publishing Profile defaulting to Region:"East Asia" and Region for LUIS "West US"

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7135]
## Describe the bug
Adding a new publishing profile to an EA bot, is defaulting to a combination of East Asia and West US. 

My LUIS Resource was created in West US, so that makes sense. 

... but where is East Asia coming from? I would expect these to be co-located in the same region, or at least within the same Zone (East/West US). Having them be nonsensically located is going to end badly for my bot. 

![image](https://user-images.githubusercontent.com/1165321/115335470-23815200-a152-11eb-98e7-ef52fc5727f3.png)

## Version

Version:  1.4.0-nightly.236875.b9e46c2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by JaskeeratBedi-cmk** [comment]
For time being we have updated the UI for this modal to show clarity between the asks. However, the 1st region collects information for all resources like App insight, storage, channel registration etc..the 2nd is specifically for Luis

Additionally, Luis has a concept of '[public app](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-regions)' that allows for it to work across region, therefore the dropdown shows regions that are compatible..
That is at least what I understood..

![MicrosoftTeams-image (49)](https://user-images.githubusercontent.com/67944302/115921413-4fd9ee80-a430-11eb-830d-e8cfa7fa427e.png)

**Comment by OEvgeny** [comment]
Closing as not planned, LUIS is deprecated
