### ISSUE TITLE
Publishing Profile has 3 things? What are they? 

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7136]
## Describe the bug

When creating a new EA Bot, I click the "Create a Publishing profile". 

![image](https://user-images.githubusercontent.com/1165321/115335705-95599b80-a152-11eb-998c-01bc386c08a5.png)

There are 3 things there
1. "EA1" (which is what I just created)
2. People (A Skill, but I didn't get to name it, and didn't intentionally create it.)
3. Calendar (A Skill, but I didn't get to name it, and didn't intentionally create it.)

I actually have... no idea what to do with this. The docs don't help. 

This UX flow may need to be reconsidered. 

I expected to pick an Azure Subscription, perhaps create a new resource group, and have my Bot deployed. 

On one hand, I know this is a Bot + Skill + Skill. On the other hand, there's quite a bit here. Especially when trying to configure the profile. 

## Version

Version:  1.4.0-nightly.236875.b9e46c2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by mewa1024** [comment]
(@emivers8, @JaskeeratBedi-cmk address with docs for now?)

**Comment by OEvgeny** [comment]
Closing, UX updated
