### ISSUE TITLE
"Add resources" screen has incorrect / unexpected defaults 

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7138]
## Describe the bug

Adding resources to my publishing profile, the "Add resources" screen just has everything checked. The list here seems incorrect. For example:

1. Why is CosmosDB both Optional and Checked? Do I need it? Given my EA Bot will do "data things" I would expect to need storage, meaning this wouldn't be optional. Can I use Blob Storage instead as it's far cheaper? 
2. Why is "Azure Blob Storage" both optional and checked? Do I need this as well as CosmosDB? Can I just pick one? 
3. My EA Bot uses LUIS (at least I've configured it). Why is LUIS Authoring and Prediction both checked and optional? 
4. Why is "QnA Makers" Optional? Seems like I really need this. 
5. Why is CosmosDB the only state storage option?
6. Why is Azure Storage only allowed to be used for logs?

The UX on this screen seems incorrect. 

Based on the capabilities of my Bot, don't I need Qna, LUIS, and a Storage provider? 

![image](https://user-images.githubusercontent.com/1165321/115336353-e9b14b00-a153-11eb-89e7-dfc7bd4b3706.png)

## Version
Version:  1.4.0-nightly.236875.b9e46c2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by mewa1024** [comment]
(@JaskeeratBedi-cmk, @emivers8 )

**Comment by OEvgeny** [comment]
Closing as not planned, UX slightly changed. Feel free to reopen
