### ISSUE TITLE
Remove skill trigger or remove skill from project may remove other triggers 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#7144]
- create root bot
- add remote skill will automatically add skill trigger
- error 1 : remove skill trigger, sometimes greeting trigger will be removed as well
- error 2 : remove skill trigger (if it worked as expected), remove remote skill from project, greeting trigger will be removed as well

Can not stable repro error : 
- Repeat above steps , add intent recognized trigger after adding remote skill
- remove intent recognized trigger , then skill trigger is also removed

**Comment by cwhitten** [comment]
@hibrenda please assign to R13 if this has not been addressed.
