### ISSUE TITLE
Composer home screen flickering/resizing

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7145]
## Describe the bug

Odd, new behaviour with Composer on the home screen. When starting Composer and landing on the home screen it infinitely flickers/resizes - looks like the What's New section (below the fold) is appearing on the right and back to the bottom.

Hovering the mouse over the window increases the flicker rate.

## Version

1.4.0-NIGHTLY.236490

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Start Composer
2. Resize to have the what's new section not quite fit
3. Close Composer
4. Restart, observer flickering behaviour

## Expected behavior

No flickering

## Screenshots

https://user-images.githubusercontent.com/33519520/115393039-25dabf00-a1d9-11eb-9e18-312e3e0a083f.mp4

**Comment by cwhitten** [comment]
@darrenj do you see this on latest nightly?

**Comment by darrenj** [comment]
Fixed in most recent builds
