### ISSUE TITLE
Confirm Skill endpoints screen appears to be a dead-end (until provisioning happens)

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7148]
## Describe the bug

When making a bot available as a skill (which is not already published) provisioning/publishing is triggered. UX then moves to a confirm skill endpoints screen. This isn't proceedable (you can go back) and it's not clear what I should do next. I was patient, and after provisioning/publishing completed I spotted the UX had updated with the endpoint.

Think we need a spinner/modal dialog to communicate it's waiting.

## Version

1.4.0-nightly.237101

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/115397237-c9c66980-a1dd-11eb-985f-9757c81bb2b8.png)

**Comment by boydc2014** [comment]
@cwhitten we want to make this a P0 since it's blocking bug

**Comment by sgellock** [comment]
Shiproom - we have a PR, and we believe we can get that PR merged today.  Approved
