### ISSUE TITLE
Pre-built entities not supported when adding a remote skill

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#7151]
## Describe the bug

Adding a remote skill that uses pre-built entity an error is presented indicating that pre-built entities are not supported.

![image](https://user-images.githubusercontent.com/3900649/115398633-4443b900-a1df-11eb-829e-6e82c890e9a7.png)

## Version

Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Expected behavior

Pre-built entities should be supported.

cc @darrenj

**Comment by cwhitten** [comment]
This is a problem. Orchestrator's configuration on the LU syntax is driving the parser. Orchestrator does not support pre-built entities. 

I assume your skill uses LUIS, which does. So we have a mismatch. cc @darrenj

**Comment by boydc2014** [comment]
Seems like we need to be smart about the root dialog's recognizer config, if root dialog is using "orchestrator", we will use certain lu parser config, if not, we will use default lu parser config(for LUIS), is that right?

**Comment by garypretty** [comment]
@boydc2014 @luhan2017 Not sure if this is the same issue, but I also get an error when adding an entity in the create trigger dialog (my bot is using the default recognizer).

![image](https://user-images.githubusercontent.com/3900649/115683404-5001bd80-a34e-11eb-910c-085cf048d83f.png)

**Comment by boydc2014** [comment]
@VanyLaw is your PR covers the above scenario?
