### ISSUE TITLE
LU for Skill trigger once connected is malformed

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7152]
## Describe the bug

When connecting a Skill, when the LU file is retrieved from the Skill and added to an Orchestrator trigger the `>` notation is used for the intent rather than `#` as seen in the screenshot. This causes no training data to be applied to the intent.

Replacing > with # resolves the issue.

## Version

1.4.0-nightly.237101

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Add `https://djtest6.azurewebsites.net/manifests/djbfskill1-2-1-manifest.json` to a new bot project

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/115398827-76551b00-a1df-11eb-9735-f30aba6a5c92.png)

**Comment by luhan2017** [comment]
@darrenj I don't get your point here, when we add a remote skill, we just aggregated the utterances of the selected intents and merged them into one intent trigger. Do you mean we should change >weather to #weather?

**Comment by luhan2017** [comment]
I can't reproduce this issue in my side.
![image](https://user-images.githubusercontent.com/32191031/115651279-70854400-a35d-11eb-9125-04d509951eb2.png)

**Comment by darrenj** [comment]
Agreed, my mistake - Due to another bug (prebuilt entities) I introduced a typo :-(
