### ISSUE TITLE
SkillDialog action automatically added when connecting to a Skill cannot select Skill endpoint

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7153]
## Describe the bug

When connecting a Skill to an basic (empty) bot a trigger is added for the Skill. Within that trigger is a SkillDialog custom action. When testing you get a `Value cannot be null. (Parameter uriString)` error which appears to be because the Skill Endpoint selection isn't selected automatically (a bug) and cannot be manually selected.

## Version

1.4.0-nightly.237101

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Connect a skill to a Bot (e.g. https://djtest6.azurewebsites.net/manifests/djbfskill1-2-1-manifest.json)
2. Observe that the Skill endpoint setting on SkillDialog action in newly created trigger isn't set
3. Skill isn't invoked

## Screenshots

![image](https://user-images.githubusercontent.com/33519520/115402972-dcdc3800-a1e3-11eb-8cb2-a7dbf7f64805.png)

**Comment by luhan2017** [comment]
Synced with Darren offline, This can't be reproduced on the latest main branch, let me know if you have this reproduced.

**Comment by darrenj** [comment]
Just reopened as can repro in 2.0.0.nightly.239644.

- Create a Empty Bot
- Choose Add Skills
- Use this manifest: https://djtest6.azurewebsites.net/manifests/djbfskill1-2-1-manifest.json
- Finish the wizard
- Hit Start Bot
- Type Weather
- Observe error

![image](https://user-images.githubusercontent.com/33519520/116391463-1b42aa00-a817-11eb-9e0d-cbcf08b957d7.png)

Observe that Skill Manifest isn't set on action. Unable to select it in UK

![image](https://user-images.githubusercontent.com/33519520/116391535-344b5b00-a817-11eb-9f4c-72db4c15152b.png)

**Comment by sgellock** [comment]
Shiproom - approved

**Comment by tdurnford** [comment]
@darrenj @sgellock I am not able to reproduce this error in the latest nightly.
![May-03-2021 15-19-33](https://user-images.githubusercontent.com/17039790/116935067-102ab800-ac23-11eb-8651-e19067a5ee20.gif)

**Comment by sgellock** [comment]
Shiproom - @darrenj we're unable to repo.  Are you?

**Comment by tdurnford** [comment]
@darrenj @sgellock I'm not able to repro either. 

![image](https://user-images.githubusercontent.com/17039790/117015997-7e1cc100-acaf-11eb-959c-77ff94087fb1.png)

@darrenj Are you using ngrok to configure your Skill host endpoint URL?

![image](https://user-images.githubusercontent.com/17039790/117016087-98569f00-acaf-11eb-933f-1f78656f2c02.png)

**Comment by darrenj** [comment]
I reproed just now, and have been able consistently. 2.0.0-nightly.242275

![image](https://user-images.githubusercontent.com/33519520/117065926-fa4eed00-ad1f-11eb-92c9-302938b390b5.png)

Note the endpoint drop-down is blank, and I can't choose anything
![image](https://user-images.githubusercontent.com/33519520/117065827-dbe8f180-ad1f-11eb-9670-2e563962e89a.png)
..

**Comment by darrenj** [comment]
This is not even getting to the point of calling the skill so not ngrok, I did double check in case I was misreading the error message reason but even with ngrok configured and skillhostendpoint configured I get the same issue

**Comment by tdurnford** [comment]
@darrenj can you check your bot settings to make sure `runtimeSettings.skill['djbfskill1']` is set correctly? I'm not seeing this issue in the latest nightly - v2.0.0-nightly.242720.c3b8105  - using your weather skill.

**Comment by darrenj** [comment]
I can repro this in todays build. Just created a repro video and will share with @tdurnford

**Comment by cwhitten** [comment]
@darrenj this was auto-closed and a nightly is running for you test

**Comment by darrenj** [comment]
Confirmed fixed in #7475 

![image](https://user-images.githubusercontent.com/33519520/117348897-b1737180-aea2-11eb-9448-7efc711e9c56.png)
