### ISSUE TITLE
Can't write expression for Multi-choice question dialog

### ISSUE THREAD

**Issue by mbinic** [microsoft/BotFramework-Composer#7154]
## Describe the bug

I'm unable to write an expression for Multi-choice question dialog's "Array of choices" property, the UI seems to be broken.

## Version

Version:  1.4.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Open the 'AskingQuestionsSample' project
2. Click on the 'choiceinput' dialog's 'Dialog started' trigger
3. Click on the first dialog action, 'Prompt with multi-choice', then go to the 'User Input' tab
4. Scroll down to 'Array of choices'
5. Choose 'Write an expression' from the dropdown
6. See that there's no input field to write the expression into

## Expected behavior

I expect to see an input field and be able to write in an expression (returning an array of items).

## Screenshots

![image](https://user-images.githubusercontent.com/3247708/115401873-28461480-a1eb-11eb-8d60-6f608408bbde.png)

## Additional context

When opening an older project where the expression was already input, it displays as "simple choices" (screenshot below). Same happens if I open the sample's `choiceinput.dialog` file and add e.g. `"choices": "=select($choices, c, c.name)",`.
However, when I choose "simple choices" myself and input the expression there, the new bot just shows it as the first item's text.

![image](https://user-images.githubusercontent.com/3247708/115403915-21200600-a1ed-11eb-900f-1de895f14a70.png)

This might be another bug, certainly a bit off-topic, but including here for completeness:
When building the older bot with this Composer version and testing, this multi-choice question dialog seems to be broken, i.e. it won't accept values like "2nd", "the first one", "first", "3."... I can explain in more detail and provide more context. And it might also be that I'm not using it in the way it's meant to be used, but the [docs](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input#create-a-multiple-choice-action) don't go into details, especially when using the default/LUIS recognizer and allowing for interruptions.

**Comment by tdurnford** [comment]
@mbinic PR https://github.com/microsoft/BotFramework-Composer/pull/6906 resolves this issue, and the fix should be included in our upcoming release.
