### ISSUE TITLE
When testing a local bot connected to remote skills no guidance to configure tunnelling is shown

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7155]
## Describe the bug

When testing a local bot which is connected to remote skills it's important to ensure that we detect this situation and tell the developer that this isn't going to work unless they configure tunnelling (e.g. ngrok) and update the SkillHost endpoint. Otherwise HTTP connection errors are reported and it's not clear what's going on unless you know the skill communication pattern in detail.

## Version

1.4.0-nightly.237101

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Bot
2. Connect a skill (e.g. https://djtest6.azurewebsites.net/manifests/djbfskill1-2-1-manifest.json) 
3. Start Bot, observe the skills response isn't correctly retrieved, you get a 500 error reported.

## Expected behavior

- Detect that remote skills are configured in the project
- Warning when starting the project that remote tunneling will be needed in order for a locally tested bot to call remote skills
- Link to documentation or a window with a suggested ngrok command `ngrok http 3980 --host-header=localhost` (find the port that the bot is using locally!)

**Comment by vivekkshankar** [comment]
We should start the Connect to a skill experience with guidance on "prerequisites"

Like so if 1) we detect that ngrok is not installed + 2) there is no associated App ID and password (2 is unrelated to this issue but a consistent fix by showing provisioning as a prereq as below can tackle this too)

![image](https://user-images.githubusercontent.com/67671676/115934739-9c302900-a446-11eb-9498-af0dd28a3687.png)

If ngrok not installed + multiple publish profiles found then:

![image](https://user-images.githubusercontent.com/67671676/115934781-b407ad00-a446-11eb-8423-5b1d6f375c0b.png)

If ngrok installed but no publish profile 

![image](https://user-images.githubusercontent.com/67671676/115934845-d994b680-a446-11eb-9fe2-d6b3d2f6befd.png)

**Comment by darrenj** [comment]
Perfect, thanks Vivek!

**Comment by luhan2017** [comment]
@vivekkshankar we can't detect if the ngrok is installed or not, how about we just leverage the last screenshot you shared, and ask user to install if needed and run the command? Question: when do we want to show this pop up? do we want to add a check box saying: don't show it again?

**Comment by sgellock** [comment]
Shiproom - @cwhitten let's get crisp on min design to address the ngrok discover and notification issue

**Comment by sgellock** [comment]
Shiproom - this needs to be scoped to R13.

**Comment by vivekkshankar** [comment]
@sgellock @cwhitten The P0 R13 scope is as follows:

- We will show tunnelling software requirements via messaging on starting a bot.

![image](https://user-images.githubusercontent.com/67671676/116724365-6f739880-a995-11eb-8ad7-7bbc7793b6e0.png)

- The message will auto-populate the port number and dynamically adjust the syntax for the command based on the OS detected.

- This message will only shown only once on starting a bot to avoid making this messaging noisy. 

P1 scope 

- The user can find these instructions in the rocketship menu after dismissing the notification.

![image](https://user-images.githubusercontent.com/67671676/116724777-edd03a80-a995-11eb-8659-e7658f30dd89.png)

**Comment by sgellock** [comment]
Shiproom - let's do the MVP here for R13

**Comment by sgellock** [comment]
Shiproom - approved.  @a-b-r-o-w-n can you get this merged today please?  thank you
