### ISSUE TITLE
Orchestrator isn't firing for Skill related intents after skill connection

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7156]
## Describe the bug

When connecting a Skill to a new Empty Bot, Orchestrator is enabled as part of the skill connection flow but doesn't seem to fire for a given intent (e.g. weather). Switching to a different recognizer (LUIS) seems to show the same behaviour. Suspicion is that the trigger isn't being registered correctly.

## Version

1.4.0-nightly.237101

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create Empty Bot
2. Connect a skill - `https://djtest6.azurewebsites.net/manifests/djbfskill1-2-1-manifest.json`
3. Accept the default behaviour of using Orchestrator
4. Test the Bot - type in `Weather` and observe nothing triggers
5. Add an unknown intent handler to bot and observer weather drops through to unknown intent

## Expected behavior

Orchestrator to fire for skill related intents

**Comment by taicchoumsft** [comment]
Hey @darrenj ,  I am able to to the end to end scenario with Orchestrator - my root bot is able to receive messages from a skill

![image](https://user-images.githubusercontent.com/61705609/115495566-cd2d1580-a21c-11eb-9483-88000b87df6b.png)

Can you DM me with your bot so I can diagnose what happened?

**Comment by darrenj** [comment]
Thanks Tai - I've re-tested the same project on todays build and it's sprung into life. There was something odd going on with Composer on my machine yesterday, a reboot appears to have sorted it out. Will close this but reopen if I see the behaviour again
