### ISSUE TITLE
Publishing profile wrongly refer sign out

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7162]
## Describe the bug

If user did not sign in "Add a publishing profile" section its shows the sign out button

## Version

Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Refer the video

# Screenshots

https://user-images.githubusercontent.com/16264167/115416967-84636580-a1f8-11eb-9f78-f17df43fdb5c.mp4

**Comment by GeoffCoxMSFT** [comment]
@rvinothrajendran We are working on this and will have it fixed for the next release. You should see this fixed in a nightly this week.

**Comment by sgellock** [comment]
Shiproom - you guys merged a PR that didn't have a ship room approved issue.  let's follow the process or I'm going to ask you to back these out in the future.

I've assed Shiproom-Approved to keep the bookkeeping correct.  :-(
