### ISSUE TITLE
Add a publishing profile view is not in the same navigation concept

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7163]
## Is your feature request related to a problem? Please describe.

"Create new resources" and "Hand off to admin" view has a back button but "Import existing resources" back button is missing 

https://user-images.githubusercontent.com/16264167/115420680-a14d6800-a1fb-11eb-8725-131d402213fc.mp4

"Import existing resources" view also add the back button.

**Comment by rvinothrajendran** [comment]
@cwhitten not sure this is bug or feature request.

**Comment by cwhitten** [comment]
@Dewain27 FYI

**Comment by Dewain27** [comment]
Getting resolved in next release.

**Comment by Dewain27** [comment]
fixed in the latest build #7236
