### ISSUE TITLE
bug: Cannot type in response variations in Send a Response.

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#7165]
## Describe the bug
![image](https://user-images.githubusercontent.com/6182197/115424351-7dfeca80-a1b3-11eb-98fe-04bc2f106963.png)
I'm running from command line, I don't see any obvious error messages in the trace.

## Version

Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to any trigger.
2. Click on + to add a new shape.
3. Scroll down to 'Send a response'
4. Click in 'Response Variations'
5. Begin typing
6. See error below.

## Screenshots

![image](https://user-images.githubusercontent.com/6182197/115424452-92db5e00-a1b3-11eb-9e16-b82af73b7607.png)

**Comment by hatpick** [comment]
I can't repro this, would you please:
1. Attach a video?
2. Add steps you follow to run from command line?

Do other features of the app work? It seems like the local server is down.

**Comment by daveta** [comment]
@hatpick : 
If I create a new bot it works.  If I open an older bot (i'm using something from Tai called LargeOrchBot) it fails.
Feel free to close, this may be some interim build problem.

**Comment by hatpick** [comment]
Please create a new bug if it happens again with a new bot on our nightly builds.
