### ISSUE TITLE
Begin dialog action node does not render an expression correctly

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#7167]
## Describe the bug

When using an expression to begin a new dialog, the visual node treats the value as a dialog id and tries to link to it.

## Version

`v1.4.0-nightly.237101.f01cb52`

## Screenshots

![image](https://user-images.githubusercontent.com/3619060/115428612-6aedf980-a1b7-11eb-8cc0-1867b321438c.png)

**Comment by OEvgeny** [comment]
Looks like it was fixed in 2.x
