### ISSUE TITLE
Cannot access remote skill's LU file from manifest once published

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#7168]
## Repro
* Create a skill
* Publish the skill on Azure webapp
* Create a consumer
* Try to connect the skill
* Error: Skill's LU is inaccessible.
* Verify: Skill's LU is not available in browser either

## Example
* https://theskill.azurewebsites.net/manifests/TheSkill-2-1-manifest.json
* https://TheSkill.azurewebsites.net/manifests/skill-TheSkill.en-us.lu (referenced in manifest)

## Version
Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Visual

![image](https://user-images.githubusercontent.com/8867670/115441048-46008300-a1c5-11eb-9e0a-22c907463b76.png)

**Comment by luhan2017** [comment]
@scheyal are you creating a new bot from the template or using the old bot? This is a known issue before and we fixed in the template side last week.
Could you please try to create a new bot and see if this reproduces?

**Comment by luhan2017** [comment]
Close this issue, @scheyal, please reopen if needed.
