### ISSUE TITLE
Tooltips missing / incomplete on "Configure Resources" screeen

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7175]
## Describe the bug
The tool tips are missing and/or not-useful on the Configure Resource screen of the Azure Publishing Profile screen.

![image](https://user-images.githubusercontent.com/1165321/115450232-81547f00-a1d0-11eb-8111-d304afe5da84.png)

## Version

Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

To Duplicate:
1. Create a new Publishing Profile
2. "Create New Resources" 
3. Observe missing and/or not clear tooltips.

**Comment by OEvgeny** [comment]
UX Updated, closing as completed
