### ISSUE TITLE
Publish Targets dropdown not populated

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7179]
## Describe the bug

The Publish Profile dropdown is empty, despite having publish targets. 
![image](https://user-images.githubusercontent.com/1165321/115453049-0a20ea00-a1d4-11eb-9b87-3d270883cb38.png)

As you can see there, a publish profile does exist:
![image](https://user-images.githubusercontent.com/1165321/115453131-202eaa80-a1d4-11eb-995e-8bbd39123cee.png)

Note: These are *new* publish targets. I had created them then switched over to the publish screen. 

## Version

Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by GeoffCoxMSFT** [comment]
@cleemullins I'm having trouble reproducing this issue.  I created a new project, added 2 more skills, went to the publish page and created a file for each one then switched to the publish page.  

Did you create the projects and then reload composer, or did you do this all in one session?  Did you console show any errors? (We do not show projects that failed to load in the publish list)

**Comment by cwhitten** [comment]
Closing as fixed
