### ISSUE TITLE
Error: "Recieved an error from AAD. Code: 'invalid_grant' description: '(pii)'" when deploying.

### ISSUE THREAD

**Issue by MikeDxS** [microsoft/BotFramework-Composer#7181]
## Describe the bug
When I start deploying the bot to an Azure Web App, I get the error "Received an error from AAD. Code: 'invalid_grant' description: '(pii)'" in the browser console.

## Version

Version: 1.4.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Publish'
2. Select a bot and a publish profile of type "Publish bot to Azure Web App"
3. Click on "Publish selected bots"
4. Login.
5. See error.

## Expected behavior

Bot starts publishing bot to Azure Web App.

## Screenshots

![image](https://user-images.githubusercontent.com/31480904/115453626-76f0b000-a1e5-11eb-9deb-2179dd6425f1.png)
Error on URI: http://localhost:5000/api/auth/getARMTokenForTenant?tenantId=
## Additional context

The error only occurs in 1.4.0, I can publish bots in version 1.3.1

**Comment by anusharavindrar** [comment]
@MikeDxS, can you try to update to the latest nightly build of composer and publish again? You can go to the application settings page and check the early adopters toggle and then in menu bar, go to **Help > Check for Updates** to install the latest version.

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to re-open if issue persists.
