### ISSUE TITLE
Broken / Missing links in "Hand off to admin" scenarios

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7188]
## Describe the bug

Attempting to provision resources via the "Hand off to admin" scenario that's found on the publishing profile page. 

The "Learn More" link appears to be missing:
![image](https://user-images.githubusercontent.com/1165321/115474616-abb73400-a1f2-11eb-9223-f86895b01d0c.png)

Clicking "Learn More" results in a blank screen:
![image](https://user-images.githubusercontent.com/1165321/115474657-c38eb800-a1f2-11eb-96de-a4d380ccfb32.png)

The Link "https://docs.microsoft.com/en-us/composer/how-to-complete-provision-handoff" results in a 404. 
![image](https://user-images.githubusercontent.com/1165321/115474762-ffc21880-a1f2-11eb-9f1c-24dbbc3a52a6.png)

This link (the same) also results in a 404:
![image](https://user-images.githubusercontent.com/1165321/115474849-35670180-a1f3-11eb-8b1e-2a4a2c794bbb.png)

404, as seen here:
![image](https://user-images.githubusercontent.com/1165321/115474774-0cdf0780-a1f3-11eb-9d13-951507704840.png)

## Version

Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

**Comment by benbrown** [comment]
The part about this that is the 404 is just a matter of not having completed the aka.ms link.  @Dewain27 will do this once #7180 is merged.

@GeoffCoxMSFT  Is that the same link used in all three places? or is there another broken link?

**Comment by GeoffCoxMSFT** [comment]
I put in the link per Jas's reply in the figma.

**Comment by sgellock** [comment]
Dup of #7449
