### ISSUE TITLE
"Only one free account" - What to do?

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7199]
## Describe the bug

When creating a QnA Maker bot, I'm getting this error:
![image](https://user-images.githubusercontent.com/1165321/115491554-095c7800-a215-11eb-9ad7-c1913a896980.png)

I'm in a paid azure subscription ("team-dev-cmullins") that has many Azure resources. Why can't I create a QnA Maker resource? At the very least, can I get a link to a doc or another mechanism to fix this? Given this is very much a premier Bot Framework scenario, guidance here is important. 

(Note: I actually do not understand why I'm getting this.)

Is the best way around this to go to Azure, create a QnA Resource, and give it an S0 pricing tier? If so, can we explicitly enable this in the creation flow here? At the very least, tell me how to do this and give me a link. 

![image](https://user-images.githubusercontent.com/1165321/115492020-da92d180-a215-11eb-8981-58919981fbf9.png)

## Version

Version:  1.4.0-nightly.237101.f01cb52
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by darrenj** [comment]
Same as #6866

**Comment by cleemullins** [comment]
Dupe of #6866. Closing.
