### ISSUE TITLE
Provisioning App Registration for a Root Bot doesn't set the AppId/Password in local appsettings

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7206]
## Describe the bug

There are a number of scenarios where an AppId/Secret is required in order for certain features to work, remote skills is one as this is used for the S2S authentication.

When connecting a Root Bot to a remote skill, I chose to provision an App Registration which completed successfully.  However the generated AppId and Secret were not applied to my local bot configuration meaning that when starting the bot and trying to use remote skills they didn't work.

At this point the user doesn't have easy access to go find the AppId/secret unless they:
- go to the azure portal
- go to active directory
- go to app registrations
- search for the name of their created app
- go into secrets
- generate a new secret (can't see the password for something newly created)
- copy/paste into local bot settings along with AppId (there are a few Ids so confusion happens)

## Version

1.4.0-nightly.237504

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Empty Bot
2. Connect a remote skill: https://djtest6.azurewebsites.net/manifests/djbfskill1-2-1-manifest.json
3. Observe 401 error (no AppId/Secret)
4. Provision azure resources including app registration
5. start bot, same 401 error

## Expected behavior

The AppId and Secret to be applied to my local configuration so this scenario works. Or at the very least if we are concerned about side-affecting a users configuration provide an option after provisioning to apply these resources to my local configuration.

## Additional context

The same issue exists for telemetry, I can go ahead and provision AppInsights, launch my bot and can't run queries/analysis against telemetry as a developer which itself is a key problem. The same expected behaviour above should be used for this.

**Comment by mareekuh** [comment]
@Quirinevwm  - is this something you can take on given your experience in ABS, CMKs and Channels?
Also including you @emivers8 for visibility.

**Comment by Quirinevwm** [comment]
> @Quirinevwm - is this something you can take on given your experience in ABS, CMKs and Channels?
> Also including you @emivers8 for visibility.

Em mentioned she is looking at this with the team!

**Comment by darrenj** [comment]
Correct - you can't "get" a previously created password, further complicating the steps :-(

**Comment by GeoffCoxMSFT** [comment]
**Proposal**
One issue is having multiple publishing profiles.  Which one to use?  What if the user has appid/password values already? If we automatically copy the values how do we let the user know? 

We could allow them to more easily extract the appid/password pair from a publishing profile:

- Add a button near the fields in the settings page to 'Copy from publishing profile'
- A dropdown near the button listing the publishing profiles
- The click it and we confirm to overwrite any existing value 
- When confirmed we can extract the values from the profile and put them in the fields.

**Comment by darrenj** [comment]
Thanks Geoff, I would suggest we also highlight this opportunity once we complete provisioning as well. e.g. if it's a fresh new bot, I will in many cases want these settings locally. We should include the appInsights key as well with this proposal

**Comment by emivers8** [comment]
Design. May need copy tweaks.

![image](https://user-images.githubusercontent.com/55601267/116319850-15dc5580-a76c-11eb-94d1-54760d59d0f8.png)

**Comment by mewa1024** [comment]
For the copy in "Add from publishing profile", what about "Select the publishing profile with the Microsoft App ID and secret you'd like to use." ?

**Comment by darrenj** [comment]
@emivers8, @mewa1024 - Need the same UX but for Application Insights to resolve telemetry issues affected by same problem

**Comment by sgellock** [comment]
@GeoffCoxMSFT Shiproom-approved.
