### ISSUE TITLE
Create New QnA Maker resource screen rendering issue

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#7219]
## Describe the bug

When I use the Rocket Ship to create a new QnA Maker in a new resource group, I get a modal that is rendered too small.

![image](https://user-images.githubusercontent.com/18688053/115582171-4add3980-a28e-11eb-84ca-8fb8472ff926.png)

## Version

Version:  1.4.0-nightly.237504.97571e0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a QnA Maker template bot
2. Go to rocket ship and Click on Add a QnA Maker key
3. Try to create a new one in a new resource group
4. Get weird modal render

## Expected behavior

Modal renders large enough to fit the items needed to select

**Comment by benbrown** [comment]
Fixed by #7184
