### ISSUE TITLE
R13 Bug Bash: Provide more guidance on which template to choose in Composer New screen

### ISSUE THREAD

**Issue by elaine-chang** [microsoft/BotFramework-Composer#7221]
One of the top frustration from customer data is "confusion about development options". It's important for us to consider educating which template to pick in the New project menu in Composer. As 3rd party templates will also be supported in this list, there will be even more templates for users to consider choosing, and that may lead even more confusion. 

![image](https://user-images.githubusercontent.com/25210203/115590466-dacab580-a285-11eb-88c9-f13a92b2f3bc.png)

**Comment by emivers8** [comment]
Yeah, I think that's a good one. @Dewain27 @emgrol @elaine-chang recommendations for which docs page would be best here? Do we have one that introduces the concept of templates?

**Comment by elaine-chang** [comment]
I don't think such doc has been created yet but should be planned. @Dewain27

**Comment by emgrol** [comment]
@emivers8 @elaine-chang We don't have a doc planned for introducing templates; they're going to be described in the What's New and in relevant articles. If someone wants to write the doc they can do so and we'll put it into the TOC, but the writing team is at capacity right now and can only offer copy edits at this time.

**Comment by clearab** [comment]
I'm not sure what that doc would be trying to explain - what question would users have on this screen that we'd want to answer in a stand-alone docs page that wouldn't be answered by the individual template readme's?
