### ISSUE TITLE
ChoiceInput: Move Array of Choices property to the top of the User Input tab

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#7223]
We have data suggesting that users are experiencing friction when using the ChoiceInput prompt.  One of the things we suspect is causing this is having the Array of Choices property so far down the list of propertes.

Please move the Array of Choices property to the top of the User Input tap, right about the 'Property' property box.

![image](https://user-images.githubusercontent.com/3900649/107768126-e0f46100-6d2d-11eb-9538-8e3a0012acd7.png)

**Comment by peterinnesmsft** [comment]
This looks to be an ask for Composer. Transferring to the correct repo for triage.
