### ISSUE TITLE
Sign out link in Add new publishing profile

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#7235]
![create new](https://user-images.githubusercontent.com/67944302/115617680-8be14800-a2a6-11eb-8acb-e5475e41e605.png)
![hand off](https://user-images.githubusercontent.com/67944302/115618086-0e6a0780-a2a7-11eb-88d8-99056bc6e1ae.png)
![import](https://user-images.githubusercontent.com/67944302/115618091-10cc6180-a2a7-11eb-883d-ae12e4399ef7.png)

## Describe the bug

Clicking on Sign out link closes the modal. 

## Version
v.1.4.0

## Browser

- [ ] Electron distribution

## OS

- [ ] macOS

## Expected behavior

We do not need the sign out link till the time user has signed in, which happens in the next step.

**Comment by rvinothrajendran** [comment]
#7162

**Comment by Dewain27** [comment]
fixed in latest build
