### ISSUE TITLE
Can't add a remote skill; "Miss dispatch modal" message

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#7245]
## Describe the bug

I was given a URL to use for connecting to a remote skill, but it brought up this error message - does it mean "missing dispatch model"? What's a dispatch model, and how do I get one? I've been told that "dispatchModel" is no longer a required field in the manifest, but all the code in CreateSkilModal.tsx seems to be expecting one.

## Version

1.4.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Expected behavior

I should be able to import a skill given a URL, and I should expect the error message to make sense.

## Screenshots
![image](https://user-images.githubusercontent.com/61990921/115638395-2ea9be80-a2c7-11eb-8521-40be1cc7f6d8.png)

**Comment by luhan2017** [comment]
@vivekkshankar , could you please comment on this? if there is no dispatch model, how should we proceed.
- option1: don't show the select intent pop up, but still show edit trigger page with no utterances, user could still edit and we will create a trigger for user.
- option2: just add the skill to bot project, don't auto create trigger for skill.

**Comment by beyackle** [comment]
If it helps, the URL I was trying to import is this one: `https://onenote-dev.azurewebsites.net/manifests/OneNoteSync-2-1-preview-1-manifest.json`

**Comment by vivekkshankar** [comment]
@luhan2017 We should go with Option 1 and not show this error. User can author from triggering phrases scratch if authored then auto create the trigger else if left empty then dont auto create the trigger.

**Comment by vivekkshankar** [comment]
@luhan2017 We should go with Option 1. User can author from triggering phrases scratch if authored then auto create the trigger else  if left empty then
