### ISSUE TITLE
Fix yarn instructions

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#726]
Instructions for use of yarn should be more explicit about where/how to run it:

[BF]c:\workspace\botroot\Composer>yarn build
yarn run v1.15.2
error Couldn't find a package.json file in "c:\\workspace\\botroot\\Composer"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by emgrol** [comment]
Closing this now that the instructions have been clarified and are [live](https://github.com/microsoft/BotFramework-Composer/blob/master/docs/setup-yarn.md).
