### ISSUE TITLE
Template name should be Project name

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/BotFramework-Composer#7268]
## Version
April 19, 2021
![image](https://user-images.githubusercontent.com/43533472/115234231-12681f00-a119-11eb-8652-fea93183abd3.png)

## Describe the bug
Name of selected template, should be reflected/duplicated as the name for default Bot Project Name
"Blank bot" = "empty" -> should be "**blank_bot**"
"Basic conversational bot" = "Conversational_core" -> should be "**basic_conversational_bot**"
"Basic assistant" = "assistant_core" -> should be "**basic_assistant**"
"QnAMaker bot" = "qnasample" -> should be "**qnamaker_bot**"

(enterprise_assistant, people and calendar have naming in order)

## Screenshots
![image](https://user-images.githubusercontent.com/43533472/115234073-ed73ac00-a118-11eb-97aa-78f6c58c5349.png)
![image](https://user-images.githubusercontent.com/43533472/115234131-fc5a5e80-a118-11eb-99dd-c50e63ce4c44.png)
![image](https://user-images.githubusercontent.com/43533472/115234179-05e3c680-a119-11eb-84b8-1cc7f2d6d3f8.png)

**Comment by clearab** [comment]
The names are all changing - https://github.com/microsoft/botframework-components/issues/932

@pavolum can you take a look at this one? We'll need to align the default names with the new package/friendly names.

**Comment by pavolum** [comment]
yeah I am doing this now, this is being tracked here https://github.com/microsoft/BotFramework-Composer/issues/6978
Going to close this one as it is a duplicate
