### ISSUE TITLE
Telemetry: Need to capture recognizer selection (not showing up in latest analysis)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#7278]
We reviewed latest telemetry data and recognizer selection is not showing up (as far as we can tell).
We need to (a) verify that it is logged (correctly) (b) if not fix asap.

@garypretty  FYI

**Comment by tdurnford** [comment]
@scheyal We do not currently log telemetry for recognizer selection; however, we can easily add that before the next release.
