### ISSUE TITLE
[Bug Bash 04/22] Composer still makes user sign in too often

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#7284]
When I opened my Azure bot in Composer, it asked me to sign in. When I tried to provision resources for the bot, it asked me to sign in again. This is particularly strange because you can see in the screenshot that Composer seemed to already have my sign-in information and was just not using it.

![image](https://user-images.githubusercontent.com/41968495/115794855-9faeac00-a383-11eb-9f31-f9ccc74daa0d.png)

Signing in with Windows 10 desktop apps is a pain because they don't autofill your email address like browsers do, so the amount of times you're asked to sign in should be minimized. Composer should remember you forever and only require you to sign in again if you explicitly sign out, like Teams does.

**Comment by tonyanziano** [comment]
I think this has been alleviated with the implementation of the global app-level authentication and sign-in work.
