### ISSUE TITLE
QnA: bot with qna worked yesterday and broke after today's nightly upgrade

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#7287]
##Repro
My bot with QnA worked before today's nightly upgrade. Tried variations of manual
 settings change but it is still failing.

## Error
```
The given key ‘QnA_OrchestratorDispatch’ was not present in the dictionary.
```

##Migration
Also conside the experience for R12 users. Requires migration.

## Version

```
Version:  1.4.0-nightly.238265.5106247
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```

**Comment by Dewain27** [comment]
@scheyal we need more information on when this last worked and details on how to repro.

**Comment by darrenj** [comment]
@scheyal  Can you share your project if you still see the issue or repro steps? Otherwise, I suspect the wide ranging QnA changes in more recent builds have addressed the issue.
