### ISSUE TITLE
Provisioning modal | Asks for Luis region even when luis has already been added..

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#7288]
Even though I have provisioned new Luis & Q&A services when I come back to add more resources to this profile, I get asked to specify the region for luis. This seems odd, because I have already provided this information..

( attached screenshots)

<img width="1026" alt="Screen Shot 2021-04-22 at 4 27 05 PM" src="https://user-images.githubusercontent.com/67944302/115797053-d8e91b00-a387-11eb-971d-555834344749.png">
<img width="1058" alt="Screen Shot 2021-04-22 at 4 27 11 PM" src="https://user-images.githubusercontent.com/67944302/115797061-dd153880-a387-11eb-9ac2-8de3b00bc158.png">

**Comment by JaskeeratBedi-cmk** [comment]
Here is a design proposal to clean this. [Figma here](https://www.figma.com/file/J3oIdXDmeBQbAe4a4PYbQc/Jaskeerat-s-files?node-id=5746%3A93363)

![if all info is available](https://user-images.githubusercontent.com/67944302/115797761-945e7f00-a389-11eb-9a16-f50476973ab0.png)

**Comment by GeoffCoxMSFT** [comment]
Updated to P0 as the fix is to actually save the right information to the publishing profile.  Otherwise, the information is incomplete.  The UI was just behaving as expected due to the missing value.
