### ISSUE TITLE
R13 Bugbash: "Select a template" page needs text consistency cleanup for template names

### ISSUE THREAD

**Issue by elaine-chang** [microsoft/BotFramework-Composer#7290]
## Describe the bug

There are a bunch of text consistency issues for the "Select a template" page:
* Some with upper-case "Bot" and some with lower case "bot"
* Some template name ends with "Bot" or "bot", and some does not 
* Some with capitalized "A" in "Enterprise Assistant Bot", and some with lower case "a" in "Basic assistant"

## Version

![image](https://user-images.githubusercontent.com/25210203/115798471-2a46d980-a38b-11eb-873b-2e987cfc8ae0.png)

## Browser

- [ x] Electron distribution

## OS

- [x ] Windows

## To Reproduce

1. Go to Composer Homepage
2. Click "New"

## Expected behavior

consistent template names which is important in such professional software

## Screenshots

![image](https://user-images.githubusercontent.com/25210203/115798276-bad0ea00-a38a-11eb-8577-5d065f6f433b.png)

**Comment by elaine-chang** [comment]
BTW, this seems to be a regression as we had the following in the earlier version:
![image](https://user-images.githubusercontent.com/25210203/115802363-94fc1300-a393-11eb-96cc-2f97a5f1c2ad.png)

**Comment by clearab** [comment]
The names should all be changing to align - https://github.com/microsoft/botframework-components/issues/932
