### ISSUE TITLE
QnA Maker bot greets users as "Empty bot"

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7291]
Create a new QnA Maker bot, and the greeting is "Welcome to the EmptyBot sample"

![image](https://user-images.githubusercontent.com/1165321/115799734-eef9da00-a38d-11eb-97fb-6d6779d1ae0e.png)

## Version

Version:  1.4.0-nightly.238265.5106247
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by clearab** [comment]
Fixed here: https://github.com/microsoft/botframework-components/issues/895#event-4638342358

**Comment by nadiasorina** [comment]
Hi, can someone help me please? I'm trying to connect my bot from Bot Framework Composer with my kb from qna maker but i don't understand what i do wrong. 
![qna1](https://user-images.githubusercontent.com/64148448/116131133-ae26fb80-a6d4-11eb-9fad-ecb37c781aa0.PNG)
![qna2](https://user-images.githubusercontent.com/64148448/116131139-aff0bf00-a6d4-11eb-9495-5b712a52808f.PNG)
When i try to put the informations from my kb, this message appear.
![qna3](https://user-images.githubusercontent.com/64148448/116131293-df073080-a6d4-11eb-8708-ba38d8030c3f.PNG)
I'm waiting for your response. Thank you!
