### ISSUE TITLE
CI/CD Azure Devops Setup for Bot Composer 1.4.0

### ISSUE THREAD

**Issue by LakshummaC** [microsoft/BotFramework-Composer#7299]
Hi Team,

We would like to know, similar to Bot framework do we have Azure Devops setup option in Bot Composer which help multiple developers to work on same Project and support Agile methodology with CI/CD approach.

Let us know your inputs for one of our new Project.

Thanks in advance.

**Comment by LakshummaC** [comment]
Any update on the above request? We need it ASAP

**Comment by Dewain27** [comment]
Information on how to leverage Devops pipeline is being tracked in #6507
