### ISSUE TITLE
R13 Bugbash: After creating a publishing profile, the Notification window should open by default 

### ISSUE THREAD

**Issue by elaine-chang** [microsoft/BotFramework-Composer#7301]
## Describe the bug

Right now after creating a publishing profile, the notification panel is closed by default. It was not clear to me that the creation is actually in process, since when I clicked "done", there was almost nothing shown on the screen. Then I realized that I should open the Notification panel to check the progress. 
![image](https://user-images.githubusercontent.com/25210203/115827609-62690f00-a3c1-11eb-923a-8b037739432d.png)

## Version

![image](https://user-images.githubusercontent.com/25210203/115827648-701e9480-a3c1-11eb-88a8-9d6b796763a1.png)

## Browser

- [ x] Electron distribution

## OS

- [x ] Windows

## Expected behavior
Notification panel is open by default after user completes creating a publishing profile 
![image](https://user-images.githubusercontent.com/25210203/115827408-1a49ec80-a3c1-11eb-8468-81cf21d54505.png)

**Comment by Dewain27** [comment]
Resolved in latest build.
