### ISSUE TITLE
'Carousal' incorrectly overrides 'carousel' in back-end.

### ISSUE THREAD

**Issue by BellaDunnett** [microsoft/BotFramework-Composer#7309]
When adding a carousel as an attachment, the front-end uses the incorrect spelling 'carousal'. This overrides the code in the code editor to be: AttachmentLayout = carousal. Unless you manually change the spelling of 'carousal' to 'carousel' in the code editor, the feature does not work. 
![Carousel:Carousal Issue](https://user-images.githubusercontent.com/53485343/115897119-01d6e200-a454-11eb-8b62-1efd6d5cf8f0.png)

**Comment by tdurnford** [comment]
@BellaDunnett Thank you for catching that! This will be resolved in our upcoming release.
