### ISSUE TITLE
Write an Expression does not work under Araay of Choices on Multi-Choice

### ISSUE THREAD

**Issue by BellaDunnett** [microsoft/BotFramework-Composer#7310]
When offering the user a multi-choice question, there seems to be an issue with the '=Write an expression' function. When I select the option next to 'Array of Choices', the window in which to type disappears. It is therefore not possible to write an expression. See attachment for image.
![Write an Expression Issue](https://user-images.githubusercontent.com/53485343/115897293-2af77280-a454-11eb-9c6b-bd4890641ddf.png)

**Comment by hatpick** [comment]
@BellaDunnett Can you include what version of Composer on which platform you are using? Please fill in the provided bug template.

**Comment by tdurnford** [comment]
@BellaDunnett Thank you for reporting this issue. We recently merged PR https://github.com/microsoft/BotFramework-Composer/pull/6906 which resolves this issue, and it should be included in our upcoming release.
