### ISSUE TITLE
Integer Output Format Not Working

### ISSUE THREAD

**Issue by BellaDunnett** [microsoft/BotFramework-Composer#7312]
I have followed the documentation online which shows how to prompt the user for a number. However, this line does not seem to work in reality: "When using number prompts you can set the Output format to either float or integer." I have tried setting the Output format to '=integer', 'integer', and all of the integer functions that Composer allows. Is this a bug or is the documentation online incorrect?

**Comment by GeoffCoxMSFT** [comment]
@hatpick Could you check if the ask a number properties allow setting to float/integer?

**Comment by tdurnford** [comment]
@BellaDunnett @GeoffCoxMSFT @hatpick  When the Output property is undefined, everything works fine; however, when I set the value to `integer` or `float` - without quotes or an equal sign - the prompt only returns `0`. If I do use quotes or an equal sign, I get a runtime error.  I think this is an issue with the SDK.

#### Output `undefined`
![image](https://user-images.githubusercontent.com/17039790/116296261-3cdc5c80-a757-11eb-9b1a-cd43ac53de4a.png)


#### Output set to `integer` or `float`
![image](https://user-images.githubusercontent.com/17039790/116296033-f850c100-a756-11eb-8b80-bb518c502a4d.png)

#### Output set to `="integer"`
![image](https://user-images.githubusercontent.com/17039790/116296200-27ffc900-a757-11eb-81dc-1ef11c65a9c6.png)

**Comment by tdurnford** [comment]
@boydc2014 We believe this to be an issue Adaptive Expression. Can you please verify that is an issue?

**Comment by boydc2014** [comment]
@tdurnford I believe this is an issue with the document that didn't say it clear about how to use OutputFormat, the correct format is 
"=int(this.value)" or "=float(this.value)"

I've verified that both of those formats works in Composer  (except some validation issue blocking me from start that i have to start manually). 

for example if using =int(this.value)

![image](https://user-images.githubusercontent.com/3829387/117598070-8a09f680-b179-11eb-89ee-b16a60ee4bd5.png)

I will open issue for the validation issue. @BellaDunnett which document are you referring to?

**Comment by BellaDunnett** [comment]
Hi @boydc2014 I've been using this documentation: https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input
The relevant section is under 'Number input'.
