### ISSUE TITLE
Ubuntu: No way to clear Azure/Graph tokens once you've manually set them (and I can't find where they're stored)

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#7313]
## Describe the bug

Running composer on ubuntu; along the way I was asked to provide some tokens from AZ; which I did.  Later, i determined they may be the wrong ones (wrong account), and I cannot find a way to update or replace them.  We need a way to do so, or at least documentation about where they're stored so you can do it manually.

## Version

Version:  1.4.0-nightly.238522.13a82cf
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [X] Ubuntu

## To Reproduce

1. Install composer on linux
2. Create a bot
3. Create a publish profile; be asked to provide accessToken
4. Supply access token and save
5. Later decide you need to change the access token; note if this is tied to sign out, that's not working

## Expected behavior

Should be able to to sign out/clear tokens, or at least know where they are in a file so I can delete myself

**Comment by Dewain27** [comment]
Fixed in latest release.
