### ISSUE TITLE
Local host 3980 not working. Error message: timeout

### ISSUE THREAD

**Issue by HabeebunnishaMohammad** [microsoft/BotFramework-Composer#7314]
## Describe the bug

I am facing issue with the bot composer like (Local host 3980 not working: error message: timeout) when I run my bot after creating some dialogs. My bot composer version is 1.4.0 I created 11 dialogs . Is there any limitation for the creation of the dialogs? @KoradaRajesh

## Version

1.4.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
HI @HabeebunnishaMohammad The only error is a timeout? It should run with 11 dialogs. Are you able to share your bot (sanitized of personal/sensitive info) in a repository?

**Comment by HabeebunnishaMohammad** [comment]
Hi @dmvtech. Yes the only error is timeout. No, iam unable to share.

**Comment by dmvtech** [comment]
@HabeebunnishaMohammad There should not be an issue with the amount of dialogs, related to timeout. Can you give simple steps on how to reproduce? Without more to go on, there's not much we can do.

**Comment by HabeebunnishaMohammad** [comment]
@dmvtech Actually when I deleted the dialogs from my composer. It started running again. We I exceed my dialogs above 10. Its showing time out error.

**Comment by dmvtech** [comment]
Interesting. I'll try and reproduce. Is it only having the total amount of dialogs? Or do they need to be configured/connected in some manner? Do you have triggers for each dialog or are they being called from other dialogs? (i.e. is the scenario; dialog1 calls dialog2 calls dialog3....calls dialog11 ?)

**Comment by HabeebunnishaMohammad** [comment]
@dmvtech Yes, I do have triggers in each dialog and they are connected with each other. Some dialogs are not having triggers they are just connected with other dialogs so that I can have the continuous flow.

**Comment by dmvtech** [comment]
Hi @HabeebunnishaMohammad I am unable to reproduce this, but I tried with version `1.4.1`. 

Can you please test with `1.4.1` and see if it still has the same issue? If not, can you try with the simple [repo I used](https://github.com/dmvtech/ManyDialogs7314)? If it doesn't reproduce with that, can you please alter it and make it available so that I have a workable repro?

**Comment by dmvtech** [comment]
Hi @HabeebunnishaMohammad Can you provide an update?

**Comment by HabeebunnishaMohammad** [comment]
Hi @dmvtech. Yaa actually I tried doing with 1.4.1. Its not showing any issue like before.
