### ISSUE TITLE
Cleanup old runtime

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#7317]
I believe we can remove the old runtime code from Composer? If necessary, we could put it <somewhere> but I think we can remove it from the Composer electron app distribution? If not, we should identify what we need to do to get there.

**Comment by garypretty** [comment]
We should hold on this until the end of R13 - there is currently a decision to be made as to if Composer will support the old runtime along side the new or if we want to invest in having two versions be able to run at the same time. This is under review at the moment and a decision will be taken as a fast follow to R13.
