### ISSUE TITLE
check for updates doesn't show anything (likely when there are no updates)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#7322]
## Repro
* Use latest nightly
* Click on 'Check of updates'
* Error: nothing happens
* Expect: a message saying there are no updates (or update dialog).

## Version

Version:  1.4.0-nightly.238522.13a82cf
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by scheyal** [comment]
@cwhitten  FYI

**Comment by garypretty** [comment]
@scheyal this was a bug with one of the nightly builds.  To get past this you need into install another nightly manually, which you can find here -> https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.4.0-nightly.238846.6e872ca

**Comment by darrenj** [comment]
Tested, fixed in most recent release

![image](https://user-images.githubusercontent.com/33519520/116398075-46c99280-a81f-11eb-8965-e96ac7f7e608.png)
