### ISSUE TITLE
Multilingual: even when I have LU with spanish content, dual LU pane shows English in spanish side

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#7324]
## Repro
* Create a bot with multilingual (say en-us, es-mx) languages
* add es-mx content
* test bot --> works as expected
* Go to edit LU, select spanish - content shows in English. I was alerted that I lost my spanish content (luckily I wasn't but I was worried because I saw English in the spanish pane)

## Version
Version:  1.4.0-nightly.238522.13a82cf
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Visual
![image](https://user-images.githubusercontent.com/8867670/115911409-e69fae80-a422-11eb-8a25-81ba15beb994.png)

**Comment by darrenj** [comment]
Hi Eyal - I was playing about with this in a newly created bot for another localization issue. Can you repro with the latest build with a  newly created bot?

**Comment by sgellock** [comment]
Shiproom - @scheyal we need assistance with repro steps

**Comment by sgellock** [comment]
Shiproom - closing as we are unable to repro
