### ISSUE TITLE
Is nightly has stopped (Application settings is broken)

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7327]
## Describe the bug

Some of the information has missed in the application view .. No information has displayed after Form dialogs

## Version

Version:  1.4.0-nightly.238522.13a82cf
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Expected behavior

Some of the information has missed in the application view

## Screenshots

![image](https://user-images.githubusercontent.com/16264167/115914096-c64b1080-a471-11eb-871a-82193ba337c4.png)

**Comment by GeoffCoxMSFT** [comment]
@rvinothrajendran Could you update to the latest nightly? We've made a lot of changes to this for the upcoming release and you should see the remainder of the content.

**Comment by rvinothrajendran** [comment]
@GeoffCoxMSFT not able to update the new version so I installed released version back to the nightly build.

**Comment by Dewain27** [comment]
Issue resolved in latest nightly...
