### ISSUE TITLE
LUIS publishing process authorization failure

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7331]
## Describe the bug
There's an error in the LUIS publishing process specifically around the authorization header

## Version
Version:  1.4.0-nightly.238522.13a82cf
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

I don't know how to reproduce this since I don't know what I did wrong. This is related to #7329. 

All I've done was create an empty bot project, add a dialog, create publishing profile, and attempted to push. I can only assume it has something to do with the new azure cli commands that are required before creating a new publishing profile. 

## Expected behavior
Publishing should work

## Additional context
Here's the log:

---
"Accepted for publishing..."
---

---
"Abs settings incomplete, skip linking bot with webapp ..."
---

---
"appPasswordHint incomplete, return ..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"{\"name\":\"RequestError\",\"message\":\"TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\\\"Authorization\\\"]\",\"cause\":{\"name\":\"TypeError\",\"message\":\"Invalid character in header content [\\\"Authorization\\\"]\",\"stack\":\"TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\\\"Authorization\\\"]\\n    at ClientRequest.setHeader (_http_outgoing.js:488:3)\\n    at new ClientRequest (_http_client.js:221:14)\\n    at Object.request (https.js:309:10)\\n    at Object.request (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar\\\\node_modules\\\\agent-base\\\\patch-core.js:25:22)\\n    at Request.start (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:127834:36)\\n    at Request.end (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:128437:13)\\n    at end (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:127695:17)\\n    at Immediate._onImmediate (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:127707:9)\\n    at processImmediate (internal/timers.js:439:21)\"},\"error\":{\"name\":\"TypeError\",\"message\":\"Invalid character in header content [\\\"Authorization\\\"]\",\"stack\":\"TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\\\"Authorization\\\"]\\n    at ClientRequest.setHeader (_http_outgoing.js:488:3)\\n    at new ClientRequest (_http_client.js:221:14)\\n    at Object.request (https.js:309:10)\\n    at Object.request (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar\\\\node_modules\\\\agent-base\\\\patch-core.js:25:22)\\n    at Request.start (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:127834:36)\\n    at Request.end (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:128437:13)\\n    at end (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:127695:17)\\n    at Immediate._onImmediate (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:127707:9)\\n    at processImmediate (internal/timers.js:439:21)\"},\"options\":{},\"stack\":\"RequestError: TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\\\"Authorization\\\"]\\n    at new RequestError (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:84076:13)\\n    at Request.plumbing.callback (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:84196:26)\\n    at Request.RP$callback [as _callback] (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:84167:27)\\n    at self2.callback (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:127386:25)\\n    at Request.emit (events.js:210:5)\\n    at Request.start (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:127836:13)\\n    at Request.end (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:128437:13)\\n    at end (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:127695:17)\\n    at Immediate._onImmediate (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:127707:9)\\n    at processImmediate (internal/timers.js:439:21)\"}"
---

---
"{\"stack\":\"SyntaxError: Unexpected token T in JSON at position 0\\n    at JSON.parse (<anonymous>)\\n    at publishLuisToPrediction (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:255566:28)\",\"message\":\"Unexpected token T in JSON at position 0\"}"
---

---
"SyntaxError - Unexpected token T in JSON at position 0"
---

**Comment by OEvgeny** [comment]
LUIS in the path of depreciation. Feel free to reopen if you think the issue is still relevant
