### ISSUE TITLE
Z-Order of WebChat and Rocket Menu conflict

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7336]
## Describe the bug

1. Have the Rocket Menu open.
2. Start my bot.
3. Click on the "Test in Webchat" 
4. --> Bug is here Observe that the Webchat blade is not visible. 
5. Close the Rocket Menu
6. Observe the Webchat blade. 

In the screen shot below, I've clicked on the "test in webchat" button, but can't see the webchat blade. 

![image](https://user-images.githubusercontent.com/1165321/115928684-60439680-a43b-11eb-900d-3ed1aea20f36.png)

## Version
Version:  1.4.0-nightly.238698.3e4162
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by hatpick** [comment]
Duplicate #7263

**Comment by cleemullins** [comment]
closing as dupe.
