### ISSUE TITLE
Create a bot project defaults to dumping the files in my user folder

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#7337]
[originally from kevinfi https://fuselabs.visualstudio.com/botframework/_queries/edit/59896/]

1) Launch composer from Azure
2) Pick echo template
3) The default location is:  c:\users\<myusername>
! would've expected a separate required field for a folder to put it in
! would've expected the default to be Documents

It's going to be hard for folks to find their bots later on if it's not under Documents or some other linked folder like that.

**Comment by Andrea-Orimoto** [comment]
kevinfi submitted this in our ADO, I totally agree with this feedback.

**Comment by OEvgeny** [comment]
Thre is a folder selection tool in 2.x
