### ISSUE TITLE
Can't retrieve azure subscriptions when the bot is a dotnet function bot

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7343]
## Describe the bug
Composer has an error with trying to receive subscriptions. 

Related to: #7433

Might be related to #7329 and #7331

## Version
Version:  1.4.0-nightly.238522.13a82cf
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty bot via the template
2. Go to publish
3. create a new provisioning profile

## Expected behavior
It should be able to receive my profiles, but it can't

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/115932965-e2838900-a442-11eb-9dde-a8fbefb7c6cc.png)

**Comment by Virtual-Josh** [comment]
As one more weird thing it seems like this issue is related to a cached state. Once you see this error it prevents you from provisioning any new resources. However if you close and reopen composer it seemingly unblocks itself?

**Comment by darrenj** [comment]
FWIW - I can repro this on 2.0.0.nightly.239644

Given some other limitations with Azure functions we can discuss it being p0 in ship room

**Comment by benbrown** [comment]
Heads up @GeoffCoxMSFT - ship room wants this for r13

**Comment by Virtual-Josh** [comment]
Copying update from linked related ticket:

It appears the problem is once Composer expires your login credentials due to inactivity it doesn't subsequently reprompt you to login again. I was able to repro that twice yesterday with Geoff.

**Comment by GeoffCoxMSFT** [comment]
I have determined that the Azure tenant token expires (for me) after 1 hour.  From then on, the getTenants returns an empty array.

![image](https://user-images.githubusercontent.com/28762486/116599091-7b4f5400-a8dc-11eb-8052-f02def7a4f4f.png)

**Comment by GeoffCoxMSFT** [comment]
I have a proposed fix for this and will get a PR out once I can verify (it takes an hour).  Then Tony can review when he's back.
