### ISSUE TITLE
In Response editor, nothing lets me know I'm using LG Syntax

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7347]
## Describe the bug

When editing a response, there's a text box that has code in it. This text box appears to be LG Syntax. 

**I actually did not realize this was LG syntax.**

Include a UX that indicates this is LG syntax, and has a link to what LG syntax is and how it's applicable. 
![image](https://user-images.githubusercontent.com/1165321/115935253-a30b6b80-a447-11eb-835e-03b1c4e353b6.png)

Nothing here either:
![image](https://user-images.githubusercontent.com/1165321/115935481-1dd48680-a448-11eb-9eb6-e991bfeffeab.png)

The "Learn More" link does take me to an .lg page, but it's helpful. I'm trying to edit an adaptive card, why would I want a link to the LG page? 

## Version

Version:  1.4.0-nightly.238698.3e4162
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by garypretty** [comment]
Assigning to @mareekuh as she has been doing a copy review within Composer and I believe this is addressed as part of that.

**Comment by OEvgeny** [comment]
It says: "... can include Language Generation rules" which means LG syntax
