### ISSUE TITLE
Both "Learn More" links on Responses Page go to same place

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7349]
On the editing page of Bot Responses, both "learn more" links go to the same place. 
![image](https://user-images.githubusercontent.com/1165321/115937054-ba4c5800-a44b-11eb-92f6-802e91838d82.png)

## Version

Version:  1.4.0-nightly.238698.3e4162
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by cleemullins** [comment]
This one is also the same place:
![image](https://user-images.githubusercontent.com/1165321/115937532-0fd53480-a44d-11eb-853e-ddfa45fb4887.png)

**Comment by a-b-r-o-w-n** [comment]
@cleemullins Do you have a suggestion on where the links should take users?

**Comment by OEvgeny** [comment]
These are different in 2.x
