### ISSUE TITLE
Properties pane (right of the drawing canvas), scrolling does not work if the cursor if over the Monaco editor

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#7351]
## Describe the bug

In the properties pane, when my cursor is over the Monaco editor, scrolling seems to be turned off. The expected behavior is for the entire pane to scroll if the contents of the Monaco editor do not need to scroll. 

## Version

Version:  1.4.0-nightly.238698.3e4162
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to any dialog.
2. Add an "Ask a question > Multi-choice" action. 
3. In the properties pane on the right, select the "User Input" pivot.
4. Move the cursor over the "Expected responses" section.
5. Try to scroll the pane.

The pane does not scroll:

https://user-images.githubusercontent.com/39317542/115937011-a56fc480-a44b-11eb-8303-84d1ee80a858.mov

Without this behavior, the user might not realize there is more content below the Monaco editor, in particular for the Multi-Choice node.

## Expected behavior

I expect scroll to work from child element up to parent. So when I'm hovering over a multi-line input and it has enough content to scroll, I expect that element to scroll. If it doesn't have enough content to scroll, I expect the parent element (like a page or section) to scroll if it has enough content to scroll.  

Here's an example showing expected behavior:

https://user-images.githubusercontent.com/39317542/115937493-f8964700-a44c-11eb-94aa-5366ccbccfd4.mov

**Comment by zhixzhan** [comment]
Hi @mewa1024 , can you try #7357 to see it's expected behavior ?
