### ISSUE TITLE
Sign out experience in Provisioning modal

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#7355]
## Describe the bug

When user initiates provisioning, they need to signed in to Azure. However, for any reason, if user tries to sign out from Azure, we just close the modal without giving them any information about what will happen to their provisioning so far..

See attached gif-

![current sign out exp](https://user-images.githubusercontent.com/67944302/116000287-6acd6f80-a5a4-11eb-86c9-9cbf610ae694.gif)

## Version

1.4.0

## Browser

- [ ] Electron distribution

## OS

- [ ] macOS

## To Reproduce

Here is my proposed solution-
[Figma here](https://www.figma.com/file/J3oIdXDmeBQbAe4a4PYbQc/Jaskeerat-s-files?node-id=5770%3A66)

![sign out](https://user-images.githubusercontent.com/67944302/116000200-0f02e680-a5a4-11eb-93a7-db98c2d19264.jpg)

**Comment by Dewain27** [comment]
Duplicate #6561
