### ISSUE TITLE
Bot response includes an imported statement / comment

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#7364]
## Describe the bug

Created a new bot using the Basic Conversational Bot template.  The last response in the welcome message, shown in the response editor, has an imported comment contained within it, which is also shown at runtime.

Not sure if this is down to the LG Editor or a bug within the template content. 

@hatpick @srinaath could you take a look at this please?

cc @clearab can you let us know if you're already aware of this issue on the template side please.

![image](https://user-images.githubusercontent.com/3900649/116055959-26f66b00-a675-11eb-8d1b-4836c0935b98.png)

![image](https://user-images.githubusercontent.com/3900649/116056101-4e4d3800-a675-11eb-9c01-a805c306d02a.png)

## Version

Version:  1.4.0-nightly.239011.99a74b9
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by hatpick** [comment]
It's definitely not generated by "lg editor". @boydc2014 do you have any ideas?

**Comment by hatpick** [comment]
It's definitely not generated by "lg editor", perhaps runtime build or merging step. But Lg Editor can persist it to a variation, @tdurnford is on it.
