### ISSUE TITLE
Full message not displaying in adaptivecard

### ISSUE THREAD

**Issue by BeheraMadan** [microsoft/BotFramework-Composer#7365]
Hi,

I am fetching the answer  dynamically in below way and the message is a big paragraph. But whole message is not displaying it only showing 2 lines. To display the full message is there some other configuration needed please let me know.

code sample: 
```js
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "${dialog.api_response.content.answers[0].answer}",
                    "weight": "Bolder"
                }
            ]
        }
    ]
}
```

output: 
![image](https://user-images.githubusercontent.com/70739031/116071226-41e3d200-a6ab-11eb-8adc-d70c387cd3f0.png)

**Comment by stevkan** [comment]
@BeheraMadan, I'm looking into what other configurations might be necessary (if any). In the mean time, can you tell me which client you are using? Are you testing using the built-in Web Chat, Emulator, an external Web Chat client, or something else?

Also, which version of Composer are you running?

**Comment by BeheraMadan** [comment]
Hi,

Testing in emulator and composer version- v.1.4.0

Thanks..

**Comment by BeheraMadan** [comment]
Please close this issue.
I tried below and it works fine.

{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "TextBlock",
            "text": "${dialog.api_response.content.answers[0].answer}",
            "wrap": true,
            "maxLines": 1000
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "type": "Column",
                            "width": "auto",
                            "selectAction": {
                                "type": "Action.Submit",
                                "data": "Positive"
                            },

output:

![image](https://user-images.githubusercontent.com/70739031/116405453-4a740e00-a84d-11eb-86a9-614d39263fbb.png)


Thanks...

**Comment by stevkan** [comment]
Closing as resolved.
