### ISSUE TITLE
Add a LUIS key: choose from existing's next screen shows "Create a new LUIS resource"

### ISSUE THREAD

**Issue by elaine-chang** [microsoft/BotFramework-Composer#7390]
## Version
What package version of the SDK are you using.

## Describe the bug
Give a clear and concise description of what the bug is.

![image](https://user-images.githubusercontent.com/25210203/116150647-7c903f00-a698-11eb-95c5-0005c158065d.png)
![image](https://user-images.githubusercontent.com/25210203/116150715-9762b380-a698-11eb-8336-cf070f09377f.png)

## Expected behavior
If I chose "Choose from existing", the next screen's title should be something like "Select your LUIS resource" but not "Create a new LUIS resource".  

## To Reproduce
Composer home +New
Select a Template such as Enterprise Assistant Bot
After the project is loaded, click "Add a LUIS key" in rocket menu

**Comment by emivers8** [comment]
@Dewain27 @GeoffCoxMSFT @VamsiModem 

I don't think we saw this one, but I just confirmed. Wrong title on the add existing screen.

**Comment by Dewain27** [comment]
@benbrown Add to fit and finish work #7565

**Comment by pavolum** [comment]
I believe this has already been done

**Comment by pavolum** [comment]
Yes this has been resolved in main, closing the issue
