### ISSUE TITLE
Home page different if you have no bot open

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7397]
Go to composer home page
Notice that there is confusion if this is a neutral page, just to get started OR... I am just side-stepping activities on the bot I am currently working on.

Let's add clarity 
You're either working on a bot (create, settings, Content (bot responses/User input etc), or on the home page, not both.

Expected:
1. On the home page, when NO bot opened
    - [x] title bar: Shows product name only **[mewa: done in R13]**

      <img width="624" alt="Screen Shot 2021-04-26 at 8 25 44 PM" src="https://user-images.githubusercontent.com/48503434/116181448-75d0ee80-a6cf-11eb-93ee-9d3687bf22d2.png">

    - [ ] Toolbar : Open & New are active, Save-as is only active when one of the recent bots is selected/has focus
          <img width="346" alt="Screen Shot 2021-04-26 at 8 25 52 PM" src="https://user-images.githubusercontent.com/48503434/116181469-7c5f6600-a6cf-11eb-80d4-63b658180e61.png">

    - [ ] left nav/menu bar, only the following menu items are active:
      <img width="48" alt="Screen Shot 2021-04-26 at 8 25 59 PM" src="https://user-images.githubusercontent.com/48503434/116181487-83867400-a6cf-11eb-8106-0570a6238b16.png">
        - Home : (this is what the user is on) 
        - Create/Design: active (shows empty page, user can 'add' (create new bot) **[mewa: don't think we should take this without pressure from customers since it has technical implications. See comment below.]**
        - Package manager

2. On the home page, when a bot is opened
    - [x] title bar: Shows product name + bot name + language cannot be clicked/changed) **[mewa: done in R13]**
    - [ ] ~~Recent bot list: currently open bot is selected~~ **[mewa: don't think we should take this. We will need row selection to do actions on the bot like Remove from list, not to indicate to indicate what project you are in.]**
    - [ ] Toolbar : Open & New are active, Save-as is active and would allow renaming current bot; or which ever other bot is selected. If none selected, Save-as is not enabled.
    - [x] left nav/menu bar, all nav items are active and can be clicked/navigated to (applied to currently-open bot) **[mewa: already the experience]**

3. toolbar buttons on Home
    - [x] Create  (+ icon).  (Was: new) **[mewa: changed to + Create new in R13]**
    - [x] Open
    - [ ] Save as (only on selection of bots in the 'recent' list, or currently open bot)
    - [ ] Delete (only on selection of bots in the 'recent' list, or currently open bot) **[mewa: Not sure we should take this. Design for home page has delete action in contextual menu on the row, alongside a separate action to remove from MRU list. This makes it clear that Delete deletes the project/bot.]**
  
 -- 
 **mewa: "Save As" issue and proposed solution is tracked in #6808**

**Comment by mareekuh** [comment]
@sgellock  - per our discussion in chat the other day, this is what I recommend/expect
@mewa1024 -  what are your thoughts?

**Comment by sgellock** [comment]
We're going to need to consider fit and finish issues in the end game.  setting labels and milestones so it shows up on ship room

**Comment by mewa1024** [comment]
sorry for not reading this earlier. I don't think these aren't fit and finish issues--they're kind of significant UX issues which we couldn't tackle in R14. As far as the home page when no bot is open, @mareekuh, I think what you are suggesting is in effect if you have a blank bot open, but it is even blank-er then the empty/blank bot template. It's a reasonable expectation to be able to open a blank thing and then save it, but that's a bigger shift in the UX than fit and finish on the home page. My caveperson understanding is that this what would need to happen:

1. user opens Composer
2. user goes to Design page. would we surface the Creation wizard here? if not, it seems like this would have to happen
  - we create temporary project folder, .sln file (assuming they choose C# or we choose it for them), root bot folder with botproj file, .dialog file, etc
  - when the user makes changes, we autosave somewhere OR we ask them to choose a location at this point OR both

My guess is that this would be complicated, but @srinaath or @sgellock, please correct me if I'm wrong.
  
I left the "Save As" on the home page in case there are users who are accustomed to it being there from prior Composer releases. It acts the same as Composer 1.x--Saves the current bot project somewhere else. (Xi's design of the home page does provide for actions on individual bots in the MRU, but that was considered out of scope for R13.) 

If we are cleaning up the Save As button, can we take the changes suggested in #6808, which are fairly surgical?

**Comment by sgellock** [comment]
Shiproom - not taking for R13, moving to R14 for planning

**Comment by cwhitten** [comment]
@mewa1024 I believe in order to get this right we'll need an experience review from you or someone from the design team to step through the various user paths. Is this something you can coordinate soon? We can also consider punting this to R15.

**Comment by mewa1024** [comment]
@cwhitten Agree. I'd like to track this as a feature request instead. Added checkboxes to the original description to mark off the things that were addressed in other tickets, and changed the name to "Home page different if you have no bot open", since the "Save As" issue is described in bug #6808.

**Comment by OEvgeny** [comment]
Closing as home page design was revised
