### ISSUE TITLE
Package manager doesn't show

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7401]
## Describe the bug

When clicking package manager in the Composer UX with a new or existing project (regardless of template type) the package manager UX is not shown.

## Version

2.0.0-nightly.239644

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new project (any template) or open an existing one
2. Click package manager, nothing shows up.
3. Focus switches to package manager and then back to the existing active page

**Comment by cwhitten** [comment]
Addressed in https://github.com/microsoft/BotFramework-Composer/pull/7400
