### ISSUE TITLE
Erroneous PVA tooltip shown on the rocketship panel

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#7402]
## Describe the bug

When hovering the mouse over the rocketship panel, a tooltip referring to PVA is shown over each item.

![image](https://user-images.githubusercontent.com/3900649/116221194-4c52aa00-a745-11eb-9f5e-1b5c2e7ffd58.png)

## Version

Version:  2.0.0-nightly.239198.1de395f
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by cwhitten** [comment]
Addressed in https://github.com/microsoft/BotFramework-Composer/pull/7369
