### ISSUE TITLE
navigate to read me post creation when user selects Enterprise assistant

### ISSUE THREAD

**Issue by pavolum** [microsoft/BotFramework-Composer#7409]

**Comment by benbrown** [comment]
Is this still relevant? We added a button for the readme instead of opening it automatically.

**Comment by pavolum** [comment]
Yes removing this, Elaine and Lauren were playing the idea of making a case for this in R13 but have decided not to. 
The R14 goal for this item is still active in the r14 backlog category so closing this issue.
