### ISSUE TITLE
Error when publishing bot with LUIS from Composer

### ISSUE THREAD

**Issue by guendas** [microsoft/BotFramework-Composer#7413]
## Describe the bug
I was trying to publish a bot that uses LUIS. I added correctly all the keys and endpoints in the publishing profile (I was starting from existing resources published in westeurope) and I continue to get the same error: 

"Error - Failed to bind luis prediction resource to luis applications. Please check if your luisResource is set to luis prediction service name in your publish profile."

## Version

Version:  1.4.0

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Project Settings' -> 'Publishing Profile'
2. Click on 'Add new'
3. I'll add a name and select 'Publish Bot to Azure WebApp'
4. Click on 'Next: Configure resources'
5. Select 'Import Existing Azure Resources'
6. Copy paste in the section the JSON file generated from example and docs with all correct info on my resources
7. Click on 'Save'
8. Go to 'Publish' tab
9. Check my bot box and select the 'Publish target'
10. Click on 'Publish selected bots'
11. See error: 
"Error - Failed to bind luis prediction resource to luis applications. Please check if your luisResource is set to luis prediction service name in your publish profile."

## Expected behavior

Publish goes smoothly with no errors. I'm able to then test the bot from my WebApp for bots.

## Screenshots

![image](https://user-images.githubusercontent.com/14338080/116276992-55fc0200-a785-11eb-9000-c60327cc360b.png)

**Comment by a-b-r-o-w-n** [comment]
@guendas Can you share the JSON you used to import the resources? That will help us diagnose this better.

**Comment by a-b-r-o-w-n** [comment]
@guendas Is it possible to have you try this again with the nightly version of Composer?

**Comment by guendas** [comment]
@a-b-r-o-w-n Sure! I of course omitted the resources but here's the template. 

{
    "name": "MybotName",
    "environment": "dev",
    "runtimeIdentifier": "win-x64",
    "resourceGroup": "MybotRG",
    "botName": "MyuniquebotName",
    "subscriptionId": "MysubID",
    "region": "westeurope",
    "settings": {
        "luis": {
            "authoringKey": "authKeyCopiedFromAzure",
            "authoringEndpoint": "https://mycustomdomain-authoring.cognitiveservices.azure.com/",
            "endpointKey": "PublishinKeyCopiedFromAzure",
            "endpoint": "https://mycustomdomain.cognitiveservices.azure.com/",
            "region": "westeurope"
        },
        "MicrosoftAppId": "IdCopiedFromAzure",
        "MicrosoftAppPassword": "PasswordCopiedFromAAD"
    }
}

**Comment by dmvtech** [comment]
Investigating. Possibly related to #6482 or #7087

**Comment by darrenj** [comment]
I can repro this - when publishing a bot as a result of making a bot available as a skill

**Comment by sgellock** [comment]
@GeoffCoxMSFT the scenario is specific, not the mainline happy path.  so let's make sure we understand the repo steps.  Darren has a project he can use to repro it

**Comment by benbrown** [comment]
@guendas - I believe this may be because the name of your LUIS endpoint key does not match the expected pattern of [name]-[end]-luis.

Can you add `luisResourceName` field to your publishing profile, and set it to the name of your LUIs endpoint key resource?

**Comment by guendas** [comment]
@benbrown thanks a lot! That was the problem. It finally worked. Thank you so much :)

**Comment by lauren-mills** [comment]
Based on my testing, I think this will be a pretty common issue with bots containing multiple skills. If you want to share the LUIS resources between multiple bots (especially since there is a limit of 10 authoring resources per subscription), you may copy the keys between publishing profiles.

I would propose that we include the authoring resource name in the luis object in the profile by default so that if the user does copy and paste between profiles, this scenario will still work. Right now we're making an assumption about the relationship between the LUIS resource names and the profile name which is not very flexible.

**Comment by Gianfe** [comment]
I have the same @guendas's issue.  Adding luisResource field did not solve the problem.
Any suggestions?  

Regards, 
Gian Felice

**Comment by dmvtech** [comment]
@Gianfe Is your error the same exact one as:
> "Error - Failed to bind luis prediction resource to luis applications. Please check if your luisResource is set to luis prediction service name in your publish profile."

**Comment by dmvtech** [comment]
Closing as resolved. @Gianfe If you are still having problems, please open a new issue.

**Comment by dmvtech** [comment]
Discussion with @GeoffCoxMSFT: assigning to @Dewain27 for R14

**Comment by silviofx2** [comment]
> > "Error - Failed to bind luis prediction resource to luis applications. Please check if your luisResource is set to luis prediction service name in your publish profile."

@dmvtech I have the same error when I publish my bot with LUIS. I put this property (luisResource) in the publish profile but i get the same error.
My config is:

{
  "name": "GuidBot-v1",
  "environment": "composer",
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "Pruebas",
  "botName": "GuidBot-v1",
  "subscriptionId": "....033",
  "region": "westus",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": ""
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "",
      "authKey": "",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "",
      "container": ""
    },
    "luis": {
      "authoringKey": ".....b30c",
      "authoringEndpoint": "https://westus.api.cognitive.microsoft.com/",
      "endpointKey": "......7b26",
      "endpoint": "https://westus.api.cognitive.microsoft.com/",
      "region": "westus"
    },
    "qna": {
      "subscriptionKey": "",
      "endpoint": ""
    },
    "MicrosoftAppId": ".....ff54",
    "MicrosoftAppPassword": ".....KgI"
  },
  "luisResource": "GuidBotLuis",
  "hostname": "GuidBot-v1"
}

**Comment by cwhitten** [comment]
@Dewain27 is this being discussed somewhere else? On this ticket alone I don't see enough data for engineering to move forward on this in R14.

**Comment by Dewain27** [comment]
The original problem was resolved in Composer 2.0.  We have plans to adjust the selection of LUIS resources in the UX that should resolve this issue further as well.
