### ISSUE TITLE
Cannot edit bot while provisioning is occurring 

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7420]
## Version
Version:  2.0.0-nightly.239895.e3e1b3e
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot
2. Create a provisioning profile
3. While the provision is being created go to the designer and add a prompt
4. Click on the property field 

## Expected behavior
I should be able to interact with the rest of the app while provisioning is happening

## Screenshots
In this video I'm attempting to double click the fields to interact with them. You'll notice the text in the provisioning pop over will highlight on double click.

https://user-images.githubusercontent.com/50158775/116287571-6d1aff80-a745-11eb-936d-b90c09d72051.mp4

**Comment by vivekkshankar** [comment]
The UI should be accessible when notification toasts are open. 
@hatpick Is there   any other reason for blocking this (besides UI behaviour) such as not writing allowing local changes to be written while the bot is being priovisioned?
Nice catch again @Virtual-Josh

**Comment by sgellock** [comment]
Shiproom - approved.  please get PR reviewed and merged today.  thank you
