### ISSUE TITLE
[PVA] getting started blade should be updated to reflect PVA capabilities

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#7421]
- KEEP: edit what your bot says
- REMOVE: train your language model
- REMOVE: publish to dev ops
- SHOW: enable insights

**Comment by a-b-r-o-w-n** [comment]
@srinaath I thought that this was already taken care of but it looks like a regression. Can you confirm?

**Comment by srinaath** [comment]
So [fix: Empty Webchat inspector text and Disabling items in PVA context by srinaath · Pull Request #7241 · microsoft/BotFramework-Composer (github.com)](https://github.com/microsoft/BotFramework-Composer/pull/7241) I removed Add Connections, Add Packages and Enable Insights from the Get Started section. I could remove these items as well.

I didn't realize "Train your language model" and "Publish to devops" need to be removed from GetStarted section in PVA context. Can we not train the model with the PVA Default Recognizer?

**Comment by a-b-r-o-w-n** [comment]
@srinaath Yeah I remember that as well. The current ask is to hide those items and show the insights step.

**Comment by cwhitten** [comment]
I believe the POR was the disable the elements, not remove them entirely

**Comment by cwhitten** [comment]
Before we do this let's sync with the person who put together the ask

**Comment by srinaath** [comment]
@cwhitten I reached out to @vivekkshankar  and @benbrown on this. On the Get Started section it is to actually hide the lements and not disable

**Comment by srinaath** [comment]
[fix: Resolve PVA check logic missing by srinaath · Pull Request #7369 · microsoft/BotFramework-Composer (github.com)](https://github.com/microsoft/BotFramework-Composer/pull/7369) Updated the PR description here. I had them hidden in the PR yesterday. Sorry.
