### ISSUE TITLE
Composer doesn't add "*" to parent skill allowed callers when adding skills

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7422]
## Describe the bug
When you add a skill to a parent bot the `skills` -> `allowedCallers` property in app settings doesn't update to ["*"] (or the app ID of the skill) which prevents skills from working.

## Version
Version:  2.0.0-nightly.239895.e3e1b3e
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create and deploy an echo skill bot
2. Create a parent bot
3. Add a local skill to the parent
4. Add App ID & PW to the parent and skill
5. Add step for the parent to call the skill
6. Open in emulator and have the parent call the skill

## Expected behavior
This should just work.

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/116291011-f7b12e00-a748-11eb-8e9b-fdeee1dc5735.png)

![image](https://user-images.githubusercontent.com/50158775/116290883-cfc1ca80-a748-11eb-9f7a-52d93842bf67.png)

## Additional context
The skill throws a 500 if the `skills` -> `allowedCallers` isn't updated in app settings

**Comment by vivekkshankar** [comment]
@Virtual-Josh Great catch. But this is by design to prevent security issues. We try to communicate the need for the skill to have the root bot in the allowed caller list via copy but I think we could potentially do more.
We did intend to   validate if the root bot is in the skillbots allowed callers list as part of the release but this is not feasible currently.

**Comment by Virtual-Josh** [comment]
I agree this could be solved with documentation, but it's not at all obvious that the parent needs to have it's `allowedCaller` list updated after adding a remote skill. Composer auto-magically takes care of a lot of things, it violates expectations when the number of exceptions (that I've found so far) is 1.

**Comment by JonathanFingold** [comment]
We don't have such a restriction in an SDK-first skill. "*" is allowed and used in the manifests for the sample skill bots.
