### ISSUE TITLE
Update redirect link for Composer template overview doc's aka.ms link

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#7425]
We'd like to include a link to the new template overview docs page in the rocket panel. The aka.ms link has been created (https://aka.ms/ComposerBotTemplateOverview), it just needs to link to the right page.

@elaine-chang

**Comment by Dewain27** [comment]
@emivers8 I think I got this one already working for you.   Can you please confirm that this is still an issue?

**Comment by darrenj** [comment]
Appears to be resolved.
