### ISSUE TITLE
Create new LUIS resources modal shows buttons overlapping 'resource name'

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7428]
Create new LUIS resources, when launched from button on Settings page shows modal's buttons overlapping Resource name field. I've been clicking around quite a bit to capture content so I can't tell you the exact path )-:
I've attached a full screenshot for context incl build # - hope that helps at least a bit.
![Screen Shot 2021-04-27 at 12 27 27 PM](https://user-images.githubusercontent.com/48503434/116300894-44e6cd00-a754-11eb-9288-04ae83861fbf.png)

 

![Screen Shot 2021-04-27 at 12 23 04 PM](https://user-images.githubusercontent.com/48503434/116300419-bb36ff80-a753-11eb-9551-85cd1e3d0c5d.png)

**Comment by mareekuh** [comment]
Note - this is a show stopper - it doesn't allow me to enter a resource name so I am SOL.

**Comment by Dewain27** [comment]
@mareekuh please verify that you are on the latest nightly build.  This was supposed to be fixed in the latest.  If you are on the latest build, can you provide the build information for us to triage?

**Comment by benbrown** [comment]
This is quite an old version of the build! This is what this looks like now.

![Screen Shot 2021-04-30 at 11 23 07 AM](https://user-images.githubusercontent.com/729873/116724592-76ef6d80-a9a6-11eb-824e-e3ed4d7153d5.png)

**Comment by Dewain27** [comment]
Fixed in newest build
