### ISSUE TITLE
Home page: MRU should not list bots that were created or opened as part of a multi-bot project

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#7438]
## Describe the bug

The Home page MRU lists bots that were created or opened as part of a multibot project. This might lead a user to think we recommend editing those bot separately, when we don't. We would like the MRU to show only root bots or nonroot bots that were explicitly opened by choosing the Open control and navigating to the nonroot bot.

## Version

BotFramework-Composer-2.0.0-nightly.239895.e3e1b3e-mac.zip

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot and choose the Enterprise Assistant template.
2. When it is created, you will see this in your MRU:
![image](https://user-images.githubusercontent.com/39317542/116326647-cc930280-a779-11eb-9b98-116f7e36e95b.png)

## Expected behavior

Expected is to see only the root bot listed:

![image](https://user-images.githubusercontent.com/39317542/116326778-1845ac00-a77a-11eb-84ac-0bab2d8f0b93.png)

**Comment by sgellock** [comment]
MRU should list bot projects and not bots.  @beyackle can you do a spike to understand cost and risk.

**Comment by srinaath** [comment]
After the team discussion on this item the approach we take is 

The MRU list would show just the path to the Root Bot. For ex MRU would show `users/tester/enterprise_assistant/enterprise_assistant` and not `users/tester/enterprise_assistant` which is the folder containing the Root Bot, the sln file(if dotnet) and the other skills shipped in the template. The runtime templates does not give us enough information about the botproject (Root bot and its skills) structure for us to handle it in another way. Inside Composer, a botproject is just a virtual container holding 1 Root Bot and multiple skills.

 Any skills that are part of the solution would not be listed in the MRU. In addition, workflows to adding skills once inside the Design Page would not add an entry to the Recent Bot list. In the case where a user opens a bot which was a skill in a different template directly in Composer (for ex users directly opening the PeopleSkill thats part of the Enterprise template), in this context the PeopleSkill bot is a Root Bot and would be added to the MRU.
