### ISSUE TITLE
Offline - Templates and resources are not loading on Home page

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7441]
![Screen Shot 2021-04-27 at 7 07 24 PM](https://user-images.githubusercontent.com/48503434/116335565-efc6ad80-a78b-11eb-85cd-2b8556505c68.png)
![Screen Shot 2021-04-27 at 7 08 33 PM](https://user-images.githubusercontent.com/48503434/116335650-0c62e580-a78c-11eb-9007-3e5a605d5deb.png)
![Screen Shot 2021-04-27 at 7 09 01 PM](https://user-images.githubusercontent.com/48503434/116335682-1684e400-a78c-11eb-8ff9-7802ae2d807b.png)

**Comment by Dewain27** [comment]
Need to have an offline story / error handling

**Comment by OEvgeny** [comment]
Can't repro this on 2.x. The only issue are feed loading: it shows an empty feed, and bot creation which requires internet access
