### ISSUE TITLE
When adding a Skill to a project, if you have a dialog selected it adds it to the dialog not the root bot

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7448]
## Describe the bug

If you have a Bot with a dialog and have this dialog active when adding a Skill, the Skill trigger is incorrectly added to the dialog not the root Bot which is where Orchestrator is configured.

![image](https://user-images.githubusercontent.com/33519520/116399602-04a15080-a821-11eb-8826-e5d9c8a2cfa6.png)

## Version

2.0.0-nightly.240366

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot
2. Create a new dialog
3. Make this new dialog active
3. Add a skill  - e.g: https://djtest6.azurewebsites.net/manifests/djbfskill1-2-1-manifest.json

## Expected behavior

- Skill trigger added to root bot

**Comment by cwhitten** [comment]
@darrenj before we address this we need a PM owner to help reconcile your expectation with how recognizers compose with dialogs

**Comment by darrenj** [comment]
A recognizer is scoped to a root-bot or sub-dialog. With a mixed recognizer infrastructure triggered by adding a Skill (Orchestrator and LUIS) we made the decision to reinforce the recommend pattern of having triggers in the root dialog which then "begin" child dialogs. This ensures that the child dialogs continue to use the recognizer of their choice (e.g. LUIS) and are not side-affected by switching to Orchestrator which would for example mean dialogs that use entities would stop working. By registering skills at the root level (using Orchestrator) we side-step this issue.

Hence this issue related to the fact that if we allow you to register skills elsewhere we end up with a situation where existing functionality can be impacted by adding a skill/orchestrator. If were to ensure skill registration happened at the root we would avoid this.

There's a broader issue here too, when adding a dialog we don't apply the best practice (?) we have of having a trigger than uses begin dialog on a child dialog. This is something I think we should look at too.

Can you help take a look and my thoughts above @garypretty and land on a direction, perhaps short-term and longer term (r15)?

**Comment by garypretty** [comment]
Sync with @srinaath on this issue to ascertain if a short term fix to always add the trigger for a skill to the root was straightforward.  Srinaath confirms that this is the case and so I would like us to implement just that fix for R14. 

I am key not to increase scope for R14 at this stage, so we can track the issue of best practice use of a dialog and @cwhitten's broader point about recognizer composition in a future milestone.

**Comment by srinaath** [comment]
The line to add the fix https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/client/src/components/AddRemoteSkillModal/CreateSkillModal.tsx#L201. We need to pass the root dialog id here for the trigger to be added to the root dialog.

**Comment by cwhitten** [comment]
I see this needing to be special-cased around Orchestrator:

IF a user is adding a skill, AND Orchestrator is already configured at the root, OR this is the first skill the user is adding AND at the prompt decides to also add Orchestrator, we add it to the root bot.

I'd expect that the existing behavior would persist if they do not have Orchestrator configured and have not told Composer to install Orchestrator as part of adding a Skill.

This is special app-code that would sit on top of the framework, which is the issue we need to understand clearly: Should Composer only be adding Skills to the root dialog in all cases? This brings up some interesting scenarios to think about, like how a BF Package providing a dialog that calls a Skill would no longer be supported in Composer as it would be added as a child dialog and not the root. Do we want to be able to call a Skill from a Package? This in my mind would be the R15 thinking cc @darrenj  @garypretty

**Comment by boydc2014** [comment]
> I see this needing to be special-cased around Orchestrator:
> 
> IF a user is adding a skill, AND Orchestrator is already configured at the root, OR this is the first skill the user is adding AND at the prompt decides to also add Orchestrator, we add it to the root bot.
> 
> I'd expect that the existing behavior would persist if they do not have Orchestrator configured and have not told Composer to install Orchestrator as part of adding a Skill. However I could see the need to be flexible here in the short-term.
> 
> This is special app-code that would sit on top of the framework, which is the issue we need to understand clearly: Should Composer only be adding Skills to the root dialog in all cases? This brings up some interesting scenarios to think about, like how a BF Package providing a dialog that calls a Skill would no longer be supported in Composer as it would be added as a child dialog and not the root. Do we want to be able to call a Skill from a Package? This in my mind would be the R15 thinking cc @darrenj @garypretty

@cwhitten Made the logic specific to Orchestrator sounds reasonable to me, otherwise, it sounds like a big breaking change.  Should we move forward on the engineering side on this now or we want to wait till @darrenj or @garypretty  confirmation? 

If we can move forward, @lei9444 can you take this one?

**Comment by srinaath** [comment]
@darrenj Are we ok with this change? @lei9444 PR ensures to check the root dialog's recognizer is Orchestrator or if the user chooses Orchestrator in the recommendation modal and then adds the new skill caller trigger to it.

**Comment by mewa1024** [comment]
(@vivekkshankar fyi)

**Comment by darrenj** [comment]
Yes, this seems like a good way forward for now and give us time in R15 to think carefully about scenarios/patterns we want to support and those we want to encourage not!

Thanks all
