### ISSUE TITLE
PVA: User input and prompt for xxx should have Expected responses disabled

### ISSUE THREAD

**Issue by iMicknl** [microsoft/BotFramework-Composer#7451]
## Describe the bug

Lately there has been some nice work on making Composer more PVA friendly. As far as I know, you can't used 'user input' while having a PVA bot. This is currently still enabled in PVA, also in the prompts.

If this is not supported, it would be good to have this disabled.

## Version

Version:  2.0.0-nightly.240366.4a6ec2c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior

Unrelevant sections disabled with toast, or removed.

## Screenshots

![image](https://user-images.githubusercontent.com/1424596/116409674-5d2e1900-a834-11eb-91d8-006b9521898f.png)
![image](https://user-images.githubusercontent.com/1424596/116408598-476c2400-a833-11eb-83f5-bf538d90ca3b.png)
![image](https://user-images.githubusercontent.com/1424596/116410064-b433ee00-a834-11eb-9ae7-3a115ee2601e.png)

**Comment by cwhitten** [comment]
Hi @iMicknl - PVA does support .lu authoring, but only a subset of the syntax currently. You can however use the User Input  page in PVA-mode as it authors into .lu files.

I'm inclined to close this initially, but please do comment if you feel otherwise-or find a bug in this area that needs to be investigated.

**Comment by iMicknl** [comment]
Thanks for your reply, @cwhitten. Is there any documentation around this topic? I am not sure how this would work since it seems that you can't call the PVA NLU via Composer (#6048), thus which engine will execute these .lu files?

In which situations would you use the .lu files in PVA context? The trigger phrases to start a dialog are also not based on the .lu files.

**Comment by cwhitten** [comment]
Hi @iMicknl, 

By default, and when extending a PVA bot with Composer, the PVA NLU system is the default recognizer. This is what is wired into the .lu system. See the following screenshot:

<img width="1185" alt="Screen Shot 2021-05-03 at 4 12 36 PM" src="https://user-images.githubusercontent.com/1156704/116944894-35bbbf80-ac2b-11eb-9e09-4bae811ddb3c.png">

You cannot arbitrarily configure the PVA NLU for any bot, though. It needs to be a PVA-created bot.
