### ISSUE TITLE
After Azure functions are provisioned, adding resources shows it is still required

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#7453]
## Describe the bug

The Azure functions don't show as provisioned when they are if you run the provisioning wizard a 2nd time.

This is a one line bug in getExistingResources in the azurePublish extension.

## Version

main/

Version:  2.0.0-nightly.240366.4a6ec2c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create Azure functions empty bot (C#)
2. Create a publishing profile and provision
3. Edit publishing profile
4. Click add resources
5. Note the azure functions are required

## Expected behavior

Azure functions not listed as required as they are provisioned

**Comment by sgellock** [comment]
Shiproom: approved
