### ISSUE TITLE
Add 'msbot-middleware' tag

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#7454]
With the change to using tags as an additional way to determine if a package needs to be added to the components array in the appsettings file, we need to add `msbot-middleware` as an option (reference here is the LivePerson package, which only contains a middleware component - this isn't to unblock this specific package, but middleware packages in general).

**Comment by sgellock** [comment]
Shiproom:  this, among other things, breaks the handoff package scenario.
