### ISSUE TITLE
[PVA] Default Recognizer shows up twice

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#7468]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/3619060/116484075-2f999d80-a83d-11eb-9fea-bf727085badb.png)

**Comment by sgellock** [comment]
@a-b-r-o-w-n removing ship room approved, as it hasn't gone through ship room.  #gunslinger

**Comment by sgellock** [comment]
Shiproom - uncle Andy, please merge your PR after review
