### ISSUE TITLE
Add check for func runtime during creation to prevent downstream problems

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7471]
## Describe the bug
Function bots don't start. There's an error saying `'func' is not recognized as an internal or external command, operable program or batch file.`

## Version
Version:  2.0.0-nightly.240366.4a6ec2c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a dotnet echo function bot (via empty bot project template)
2. Create an echo trigger 
3. Create an echo dialog that just echos the activity
4. click start

## Expected behavior
The bot should start

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/116486258-08919a80-a842-11eb-870e-d663fac34e0f.png)

**Comment by Virtual-Josh** [comment]
Same issue applies to Node bots. The error looks slightly different, but appears to be the same at the top level:

```
Error occurred building the bot

'func' is not recognized as an internal or external command, operable program or batch file. events.js:292 throw er; // Unhandled 'error' event ^ Error: spawn func ENOENT at notFoundError (C:\Users\joratlif\ComposerSkills\4_28\NodeFunctionBot\NodeFunctionBot\node_modules\cross-spawn\lib\enoent.js:6:26) at verifyENOENT (C:\Users\joratlif\ComposerSkills\4_28\NodeFunctionBot\NodeFunctionBot\node_modules\cross-spawn\lib\enoent.js:40:16) at ChildProcess.cp.emit (C:\Users\joratlif\ComposerSkills\4_28\NodeFunctionBot\NodeFunctionBot\node_modules\cross-spawn\lib\enoent.js:27:25) at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) Emitted 'error' event on ChildProcess instance at: at ChildProcess.cp.emit (C:\Users\joratlif\ComposerSkills\4_28\NodeFunctionBot\NodeFunctionBot\node_modules\cross-spawn\lib\enoent.js:30:37) at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) { code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn func', path: 'func', spawnargs: [ 'start', '--port', '3980', '--urls', 'http://0.0.0.0:3980', '--SkillHostEndpoint', 'http://127.0.0.1:3980/api/skills' ] } npm ERR! code 1 npm ERR! path C:\Users\joratlif\ComposerSkills\4_28\NodeFunctionBot\NodeFunctionBot npm ERR! command failed npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c cross-env NODE_ENV=dev func start --port 3980 --urls http://0.0.0.0:3980 --SkillHostEndpoint http://127.0.0.1:3980/api/skills npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\joratlif\AppData\Local\npm-cache\_logs\2021-04-28T23_57_00_482Z-debug.log
```

**Comment by peterinnesmsft** [comment]
This looks to be due to not having [Azure Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash) installed and registered under PATH. This is a requirement in order to be able to run Azure Functions applications on both .NET and JS locally. This is typically installed by Visual Studio when installing with Azure Functions support, but otherwise needs to be installed separately.

This will need to be clearly documented so that other customers do not run into the same issue. @Virtual-Josh can you try installing locally and see if that addresses the issue for you?

**Comment by Virtual-Josh** [comment]
Installing the core tools resolves the issue for me.

**Comment by sgellock** [comment]
Shiproom - we should add a dependency check for Az func CLI.  Also we should add a message at the point of failure to also educate the user that a dependency is missing.
