### ISSUE TITLE
.gitignore for newly created bots should include generated directory

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/BotFramework-Composer#7473]
## Describe the bug

It appears that, upon creating a new bot through Composer, a .gitignore file is generated in the created project. As per the ask originally outlined in https://github.com/microsoft/botframework-components/issues/953:

[.gitignore](https://github.com/microsoft/botframework-components/blob/main/generators/generator-bot-adaptive/generators/app/templates/dotnet/webapp/.gitignore) should add an ignore setting to exclude the generated folder from source control.

```
# composer files
generated/
```

The generated folder contains files that are based on the current user settings and paths and that are not necessarily the same as the ones in others developers machines or the deployed server.

The content of this folder is regenerated every time composer runs based on other files that are tracked in source control and are not needed.

The CI/CD pipeline should also regenerate these files to make sure they point to the deployed models.

## Version

v2.0.0-nightly.240624.c8283fa

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Click the 'New' button on the Composer home screen.
2. Create a new bot using one of the presented templates.
3. Navigate to the directory containing the newly created bot.
4. Open the created .gitignore file.

## Expected behavior

.gitignore should contain the following or similar:

```
# Generated folder and contents produced by Bot Framework Composer.
generated/
```

## Screenshots

![image](https://user-images.githubusercontent.com/53846082/116512500-fda82b80-a87c-11eb-91f5-02aa180023fb.png)

## Additional context

Contents of the generated .gitignore for reference:

```
# prevent appsettings.json get checked in
**/appsettings.json
```

**Comment by sgellock** [comment]
Shiproom - approved this and the second half.  please ONLY do .gitignore changes as approved here.  let's not do anything with deploy scripts.
