### ISSUE TITLE
Unable to Publish Composer Bot App

### ISSUE THREAD

**Issue by BhattMeet98** [microsoft/BotFramework-Composer#7480]
Hello Everyone,

I am trying to publish my composer bot app in Azure.

I am referred below links of Microsoft for the same,

1. https://docs.microsoft.com/en-us/composer/tutorial/tutorial-introduction
2. https://docs.microsoft.com/en-us/composer/how-to-publish-bot

I have created a bot with add LUIS as mentioned in the above first link. then I follow the second link but got an error while publishing.
Also, I have created LUIS authoring cognitive service in Azure as mention in first link 

Please refer to error text,

---

"{\"name\":\"RequestError\",\"message\":\"Error: read ECONNRESET\",\"cause\":{\"name\":\"Error\",\"message\":\"read ECONNRESET\",\"stack\":\"Error: read ECONNRESET\\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27)\"},\"error\":{\"name\":\"Error\",\"message\":\"read ECONNRESET\",\"stack\":\"Error: read ECONNRESET\\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27)\"},\"options\":{},\"stack\":\"RequestError: Error: read ECONNRESET\\n    at new RequestError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:7891:13)\\n    at Request.plumbing.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:8127:26)\\n    at Request.RP$callback [as callback] (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:8098:27)\\n    at self2.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:51180:25)\\n    at Request.emit (events.js:210:5)\\n    at Request.onRequestError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:51720:11)\\n    at ClientRequest.emit (events.js:210:5)\\n    at TLSSocket.socketErrorListener (http_client.js:406:9)\\n    at TLSSocket.emit (events.js:210:5)\\n    at emitErrorNT (internal/streams/destroy.js:92:8)\\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"

---

---

"{\"name\":\"StatusCodeError\",\"statusCode\":400,\"message\":\"400 - \\\"{\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":\\\\\\\"BadArgument\\\\\\\",\\\\\\\"message\\\\\\\":\\\\\\\"The source completed without providing data to receive.\\\\\\\"}}\\\"\",\"error\":\"{\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"The source completed without providing data to receive.\\\"}}\",\"options\":{},\"response\":{\"statusCode\":400},\"stack\":\"StatusCodeError: 400 - \\\"{\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":\\\\\\\"BadArgument\\\\\\\",\\\\\\\"message\\\\\\\":\\\\\\\"The source completed without providing data to receive.\\\\\\\"}}\\\"\\n    at new StatusCodeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:7904:13)\\n    at Request.plumbing.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:8138:28)\\n    at Request.RP$callback [as callback] (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:8098:27)\\n    at Request.self2.callback (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:51180:25)\\n    at Request.emit (events.js:210:5)\\n    at Request.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:51928:13)\\n    at Request.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:51859:15)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"

---

---

"StatusCodeError - 400 - \"{\\\"error\\\":{\\\"code\\\":\\\"BadArgument\\\",\\\"message\\\":\\\"The source completed without providing data to receive.\\\"}}\""

---

Please refer to error screenshots,

![image_2021_04_29T10_39_48_475Z](https://user-images.githubusercontent.com/81350109/116543581-aac98500-a90b-11eb-9a78-7a9549018f85.png)
![image_2021_04_29T10_40_15_802Z](https://user-images.githubusercontent.com/81350109/116543595-adc47580-a90b-11eb-8b74-22977d434c10.png)

Please help me with the same as soon as possible.

Thanks in Advance.

**Comment by v-kydela** [comment]
@BhattMeet98 - Did you post this question? https://stackoverflow.com/questions/67316290/unable-to-publish-composer-bot-in-azure

**Comment by srinaath** [comment]
@BhattMeet98 Could you specify the version of Composer you are using and fill in the required details in the github issue template?

**Comment by BhattMeet98** [comment]
> @BhattMeet98 Could you specify the version of Composer you are using and fill in the required details in the github issue template?

i have used V1.4.0

**Comment by GeoffCoxMSFT** [comment]
@BhattMeet98 Could you review your appSettings.json file and look for the publishing profile settings (it looks like a long string of encoded JSON)?  See what the hostname is in that profile and verify it has the right casing as your provisioned web app.  Also please double check you are using the LUIS authoring key for authoring and the LUIS runtime key for runtime if your bot is leveraging LUIS.

**Comment by v-kydela** [comment]
@BhattMeet98 - Are you still working on this?
