### ISSUE TITLE
Composer nightly build won't start bots

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#7483]
## Describe the bug

The latest nightly build hangs on starting a bot

![image](https://user-images.githubusercontent.com/12264946/116565183-9ff2fe00-a8d3-11eb-8836-14a5ea109ac4.png)

## Version

Version:  2.0.0-nightly.240913.4390cd8
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] Windows

## To Reproduce

1. Get the nightly version mentioned above
2. Create an empty bot
3. Try to start it, it won't

**Comment by srinaath** [comment]
@gabog We have a rogue nightly in the pipeline. Pushing a stable nightly in a few minutes.
