### ISSUE TITLE
Update 2.0 links to point to 2.0 docs

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#7487]
This issue represents all the places we need to update links (Composer, Schema, etc.) to reference the correct docs version

**Comment by srinaath** [comment]
Level of Effort estimate  
https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions - All UI schema files that list "helplinks" need to be updated to build the consolidated UI schema which in turn is used by bf-dialog.  
2\. UI Plugins that override the UI Schema of Composer (32 occurrences)  
3\. Composer UI Components and unit test files (68 changes across 31 files)  
4\. Locale file (en-us.json) changes.

**Comment by sgellock** [comment]
Shiproom - eng needs the links.

**Comment by sgellock** [comment]
Shiproom - approved

**Comment by srinaath** [comment]
Based on the conversation with @cwhitten @Kaiqb, the solution we are leaning towards for this release is a tabbed approach. Using our existing example for conveying the point.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/13004779/117194864-75a0b500-ad99-11eb-8aeb-1445d12ef972.png)

We would have two tabs for v1.* and v2.*. The current aka.ms links in the UI Schema and Composer codebase landing on the v2.* tab selected. Users wanting to view the 1.* links would need to shift the tab.

Closing this ticket is a noop with the above approach.
