### ISSUE TITLE
Add template selection in add skills flow

### ISSUE THREAD

**Issue by pavolum** [microsoft/BotFramework-Composer#7490]
Need to allow users to select any non multi bot template in add new skills flow, new spec below 
https://www.figma.com/file/4kfahZUjBdrxdDGZih7PVP/Composer-1.5-E2E-flows?node-id=862%3A53941

Multibot templates will have the following tag `msbot-multibot-project`

**Comment by sgellock** [comment]
Shiproom - talked with Patrick. Approved.
