### ISSUE TITLE
"Add new" button in publish your bot page is too wide

### ISSUE THREAD

**Issue by hatpick** [microsoft/BotFramework-Composer#7491]
Check the screenshot below:

![Screen Shot 2021-04-29 at 11 21 06 AM](https://user-images.githubusercontent.com/1483492/116599607-2cee8500-a8dd-11eb-83e5-0a99430e670f.png)

This means that if I move my mouse to the far right side of the page at the same height as the button, I can click it and get to the publish modal.

**Comment by beyackle** [comment]
I noticed another related bug here - there's a reveal-arrow dropdown thing inside the rows under the Publish tab (that reveals the Publish history) but it isn't accessible without making the window extremely wide.

**Comment by beyackle** [comment]
I'll make a separate issue to track that one; for now I'll just fix the problem as stated here.

**Comment by sgellock** [comment]
Shiproom - we can live with this for R13.  moving to R14

**Comment by sgellock** [comment]
Shiproom - this issues was merged without approval.  sigh
