### ISSUE TITLE
Provisioning modal re-triggered after completion and screen blocked by notification that won't be dismissed

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#7492]
## Describe the bug

Note: this is a blocking bug. I have to restart Composer.

After creating an Azure bot resource in ABS, opening in Composer, and completing the creation of a publishing profile, a notification shows resources are being created as expected. Then when it completes, either successfully or unsuccessfully, a notification appears confirming the result, but the notification can't be dismissed and the "Edit publishing profile" modal reappears and also cannot be dismissed. I have to restart Composer.

The publishing profile modal not being dismissed seems to be related to #7429 (I can hit back, but next and X are blocked by the invisible container). That doesn't address, though, why the notification refuses to be dismissed or why the publishing profile pops up again.

## Version

Version:  2.0.0-nightly.240870.919a971
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

macOS 

## To Reproduce

1. Create and Azure bot resource in ABS, click "Open in Composer"
2. Select create new bot option
3. Click "complete publishing profile" in rocket menu
4. Go through the flow, don't select any optional resources
5. Click "create"
6. Allow the create process to finish
7. The notification confirmation pops up, as does the "Edit publishing profile" modal. Neither can be dismissed and you have to restart composer.

## Expected behavior

Should just get a notification, which can be dismissed. Publishing profile modal shouldn't pop up again without being initiated by the user.

## Screenshots

![image](https://user-images.githubusercontent.com/55601267/116600130-d0d83080-a8dd-11eb-9347-70a306898536.png)

Same thing happens with a partial completion:
![image](https://user-images.githubusercontent.com/55601267/116600194-e3eb0080-a8dd-11eb-8753-7a7b2a8d85ae.png)

## Additional context

@mareekuh also reporting experiencing this (we're both mac/electron users).

@Andrea-Orimoto fyi

**Comment by sgellock** [comment]
Thanks @emivers8 for further scoping this.  super helpful

**Comment by sgellock** [comment]
Shiproom - lets to a test pass with today's nightly to verify

**Comment by emivers8** [comment]
Same problem still occurring on Version:  2.0.0-nightly.241421.a3f796f

**Comment by emivers8** [comment]
Another interesting thing: The publishing profile modal is popping up unexpectedly every time I go back to the Publish page if I was last on the publishing profile pivot tab. (Doesn't happen if I was last on the publish tab.)

**Comment by hatpick** [comment]
@GeoffCoxMSFT @benbrown @emivers8 
As for not being able to click close the notification, it's because the current dialog that you are seeing is set to be blocking, Fabric will use a focus trap zone to swallow the clicks outside the dialog content and prevent them. 

On the other hand, if those dialogs are not blocking, clicking outside will dismiss them.

**Comment by emivers8** [comment]
> On the other hand, if we make those dialogs non blocking, clicking outside will dismiss them.

Yeah, we don't want that.

**Comment by sgellock** [comment]
+1 @emivers8 comment

**Comment by sgellock** [comment]
Shiproom - @GeoffCoxMSFT can you update the issue on what the plan is?

**Comment by benbrown** [comment]
I suspect the re-appearance of the publishing modal is due to the `completionRequired` attribute passed into the PublishTargets component.  I am not sure why it would RE-trigger, but I suspect this is the culprit.

I recently introduced this to allow for the modal to appear when users click to complete the ABS profile.  Using a #hash in the url, it navigates the user to the appropriate tab AND ALSO causes the modal to open.

**Comment by sgellock** [comment]
Shiproom:  approved - fixes a bad first experience with the new service to composer hand off flow for creating new bots

**Comment by GeoffCoxMSFT** [comment]
Per Scott's comment, labeling approved.
