### ISSUE TITLE
Installing a package while a bot is running results in multi-project build errors

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7498]
## Describe the bug
If you install a package while a bot is running the underlying process isn't fully killed. As a result Composer gets into a bad state where the `Restart bot` button becomes `Start bot` but there's already an process running. 

## Version
Version:  2.0.0-nightly.241057.db66154
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create or open a bot and start it
2. Install a package (I did the Teams package)
3. Note how the `Restart bot` button becomes `Start bot` after the package is installed
3. Click the `Start bot` button

## Expected behavior
The button should either be `Start bot` where the underlying process is actually killed, or it should be `Restart bot` assuming restart rebuilds with any delta in the packages

## Additional context

Error occurred building the bot

Message:
Command failed: dotnet build TeamsTest.csproj
Command:
dotnet build TeamsTest.csproj
Stack Trace:
Error: Command failed: dotnet build TeamsTest.csproj

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Output:
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

**Comment by benbrown** [comment]
Same as #5969

**Comment by sgellock** [comment]
Shiproom - let's get an agreed upon experience, and then take it from there

**Comment by mareekuh** [comment]
@emivers8 - experience discuss in Shiproom: Installing a package is still enabled, but we stop the running bot for the user to bypass this issue. Please chime in if needed.

**Comment by hatpick** [comment]
I think it's important to let the user know that installing a new package requires stopping their bot, if they agree, then composer stops their bot and continues with the installation, if not composer informs the user that they need to stop their running bot before any installation can happen.

**Comment by sgellock** [comment]
Shiproom - would like to see this in for R13, if we can make the date.

**Comment by tonyanziano** [comment]
@srinaath and I talked offline and are both looking at a possible solution for this.

There is already a hook exposed in Composer's client that stops a single running bot. Our plan is to add this to the Shell API and allow the package manager to call it before un / installing packages.

**Comment by sgellock** [comment]
Shiproom - approved

**Comment by SonalBannagare** [comment]
Hi Can anybody please help me creating a skill from scratch or creating a custom action in bot composer framework for any scenario from scratch? ?
