### ISSUE TITLE
Instructions user copies for IT Pro / Admin handoff are confusing

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#7507]
## Describe the bug

The instructions to copy and give to your admin are confusing. There is just enough information there to seem to be complete, but critical information is missing.

## Version

Version:  2.0.0-nightly.241057.db66154
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot.
2. Add a new publishing profile.
3. Choose the **Hand off to admin** option.
4. Copy the **Instructions for your Azure admin**.
5. Error, attempt to naively follow them.
   - The key missing bit of information is that I need to run this command from a specific directory, the bot's Scripts folder.
     - There is no way to point the admin to the specific bot location from the docs.
     - Composer, should have enough information to be able to include that in the instructions to the admin.
   - I presumably also need Node.js installed, which is also not mentioned.

## Expected behavior

1. If concrete steps are listed for the adimn, include enough information for them to complete the process, and only rely on the link to docs for additional information.
2. Include any prerequisites required for the tool chain.

## Additional context

@Dewain27 - this is related to #6258 

Here's the current copy:

> I am working on a Microsoft Bot Framework project, and I now require some Azure resources to be created. Please follow the instructions below to create these resources and provide them to me.
>
> 1. Follow the instructions at the link below to run the provisioning command (seen below)
> 2. Copy and paste the resulting JSON and securely share it with me.
>
> Provisoning Command:  
> node provisionComposer.js --subscriptionId <YOUR SUBSCRIPTION ID> --name <RESOURCE NAME> --appPassword=<16 CHAR PASSWORD> --location=westus --resourceGroup=<RESOURCE GROUP NAME> --createLuisResource=false --createLuisAuthoringResource=false --createCosmosDb=false --createStorage=false --createAppInsights=false --createQnAResource=false
>
> Detailed instructions:
> https://aka.ms/how-to-complete-provision-handoff

**Comment by JonathanFingold** [comment]
PS. Even with the information gleaned from the **Composer R13 – Publish & Provision** doc, I can't complete this process:
```
C:\Users\v-jofin\source\repos\myBots\composer\root2\root2\Scripts>node provisionComposer.js --subscriptionId "FUSE Temporary" --name v-jofin-root3 --appPassword="My>16-character_Password!" --location=westus --resourceGroup=v-jofin-skill2-rg --createLuisResource=false --createLuisAuthoringResource=false --createCosmosDb=false --createStorage=false --createAppInsights=false --createQnAResource=false
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'chalk'
Require stack:
- C:\Users\v-jofin\source\repos\myBots\composer\root2\root2\Scripts\provisionComposer.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:686:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:848:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:74:18)←[39m
    at Object.<anonymous> (C:\Users\v-jofin\source\repos\myBots\composer\root2\root2\Scripts\provisionComposer.js:3:15)
←[90m    at Module._compile (internal/modules/cjs/loader.js:955:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:811:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:723:14)←[39m
←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\v-jofin\\source\\repos\\myBots\\composer\\root2\\root2\\Scripts\\provisionComposer.js'←[39m
  ]
}
```

**Comment by benbrown** [comment]
@JonathanFingold you need to run npm install first.

This should be in the readme file located in the scripts folder

**Comment by Dewain27** [comment]
#6258 should resolve issue...

**Comment by JonathanFingold** [comment]
@benbrown  has me unblocked, but in the process opened one or two other issues.
