### ISSUE TITLE
Webchat inspector window hidden

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#7513]
## Describe the bug
The webchat inspector remains hidden due to a logic error of not checking for the webchat panel visibility. Hence, users can get stuck in a state where the Inspector panel always keeps showing "Bot is Running. Test in Webchat". 

<img width="1525" alt="Screen Shot 2021-04-29 at 5 28 43 PM" src="https://user-images.githubusercontent.com/13004779/116634296-7dcba100-a910-11eb-920f-dd3b4721ab4c.png">

Expected:
The text should disappear and the inspector should open automatically when the webchat panel is opened the first time

## Browser
main

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by sgellock** [comment]
Shiproom - @srinaath please merge your PR today, once reviewed.

**Comment by srinaath** [comment]
Thanks @sgellock
