### ISSUE TITLE
Label entity is not enable in create a trigger dialog

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#7517]
## Describe the bug

While creating trigger label entity is not enable in create a trigger dialog , Its possible only after created the trigger

## Version

Version:  2.0.0-nightly.241057.db66154
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Refer the screenshots 

## Screenshots

Create trigger label entity option is disable.

![image](https://user-images.githubusercontent.com/16264167/116656374-e0fb1900-a98c-11eb-8d19-b6e81274aa79.png)

![image](https://user-images.githubusercontent.com/16264167/116656417-f1ab8f00-a98c-11eb-9de4-2ebcf3d757f7.png)

**Comment by GeoffCoxMSFT** [comment]
@hatpick Can you see if this is an app state issue with the editor or a language server issue?  and then assign to the right person?

**Comment by hatpick** [comment]
@GeoffCoxMSFT the intent being created in that dialog does not get persisted to the LuFile, but instead gets persisted to a local state which means it wont get parsed and doesn't exist until they hit submit.

**Comment by hatpick** [comment]
@boydc2014 I understand why editing here does not persist it to LuFile (in case user cancels creation) but is there a way that the lu parser can parse the local state "on the fly" and provide parsed LuFile to the LuEditor?

(if not, it means that we can't have the assisted labeling with the floating menu) FYI @garypretty

**Comment by boydc2014** [comment]
> @boydc2014 I understand why editing here does not persist it to LuFile (in case user cancels creation) but is there a way that the lu parser can parse the local state "on the fly" and provide parsed LuFile to the LuEditor?
> 
> (if not, it means that we can't have the assisted labeling with the floating menu) FYI @garypretty

From lu parser perspective, it doesn't care where the data source is. It's just paring result given a certain input. We, from Composer side, controls the input to lu parser and handles the saving after we get a result. 

I'm not sure how this label entity feature is implemented today, but i think it should be doable. @zhixzhan can you help with this one?
