### ISSUE TITLE
Composer doesn't kill bots on shutdown

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#7521]
## Describe the bug

Composer is not consistently killing running bots on shutdown.  Gif of the behavior is below.  Oddly, you can also see that once Composer shuts down, a second bot process appears in task manager, which I cannot explain either.

Bot process in this case is ContosoInsurance.

## Version

Version:  2.0.0-nightly.240870.919a971
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

Windows 10

## To Reproduce

1. Open Composer, start the bot
2. Open task manager and find the bot process
3. Kill Composer with the x in the top right
4. Process doesn't end.

## Expected behavior

Composer should correctly kill the process when shutting down.

## Screenshots

![Composer Not Killing Bots on Shutdown](https://user-images.githubusercontent.com/3900649/116680375-80c3a180-a9a3-11eb-86b0-0e39ba31fd08.gif)

**Comment by darrenj** [comment]
Likely a repro for #7157

**Comment by scheyal** [comment]
We have many such instances. Switching projects, closing Composer, or hitting an unrelated bug are such examples and this is a regression from previous releases.

**Comment by scheyal** [comment]
So, just for more info/example a quick skim of processes on my computer shows 3 dangling processes:

[BF]c:\workspace\botroot\TempPlay>tasklist | findstr /i orch
OrchBB1.exe                 338976 Console                    1     65,540 K

[BF]c:\workspace\botroot\TempPlay>tasklist | findstr /i mood
MoodChecker.exe               2000 Console                    1     26,348 K
MoodChecker.exe             408780 Console                    1     58,244 K
MoodChecker.exe             408620 Console                    1    414,744 K

**Comment by scheyal** [comment]
To add to this, in terms of impact, it leads to very misleading experience. I restarted my bot (not composer) but emulator still shows the old behavior (prior to whatever I fixed). I had to kill the bot process, restart composer, and then it worked.

**Comment by sgellock** [comment]
Shiproom - let's bottom out an approach and see where we land on the calendar

**Comment by tonyanziano** [comment]
I can consistently repro this:

![image](https://user-images.githubusercontent.com/3452012/117066864-221d6100-acde-11eb-98c1-7a13b99c2e02.png)

That's after 2 shutdowns, so it leaves an orphaned process for each shutdown if there is a bot running.

**Comment by tonyanziano** [comment]
I am going to take a shot at implementing a listener on app quit that cleans up running bots.

**Comment by sgellock** [comment]
May the 4th be with you.

**Comment by sgellock** [comment]
Shiproom - approved.  please merge today.  thanks Tony
