### ISSUE TITLE
Qnamaker build failed: Cannot read property 'hostName' of undefined

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7522]
## Describe the bug

Added QnA to a Bot and selected an existing QnA resource, created yesterday (by Composer) for another bot. When starting the Bot I get the following error:

```
Sorry, something went wrong with publishing. Try again or exit out of this task.
Qnamaker build failed: Cannot read property 'hostName' of undefined
```
![image](https://user-images.githubusercontent.com/33519520/116685444-43164700-a9aa-11eb-8f8b-ab6e11376e8c.png)

This is what is in config - hostname is missing?
![image](https://user-images.githubusercontent.com/33519520/116685904-f7b06880-a9aa-11eb-9f86-5499cd30733b.png)

Resolved by going and finding the hostName and putting into config

## Version

2.0.0-nightly.241421

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a Bot
2. Add QnA (add a URL source)
3. From Rocket ship menu select QnA
4. Select an existing QnA resource
5. Hit Start

## Expected behavior

Bot to start

**Comment by sgellock** [comment]
Shiproom - lets try and repro

**Comment by benbrown** [comment]
I am not currently able to reproduce this using the same QNA maker Darren did.  He is going to try again as well.

**Comment by sgellock** [comment]
Shiproom - @darrenj we're unable to repro.  closing.  reopen if you are able to reproduce
