### ISSUE TITLE
Adding a QnAMaker knowledgebase to an existing Bot doesn't add a QnA Intent Recognized trigger

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7523]
## Describe the bug

I've got an existing Bot created using a template. I decided I wanted to add a KB, so through Composer added QnA - gave it a URL to build the KB from and it pulled the QNA down. I then selected an existing QNA resource in Azure, hit start (manually fixed #7522 by putting the hostname in) and I could see in trace that my QNA related question got routed to QnAMaker which replied but didn't see anything in the webchat window.

Digging in, spotted that the QnA Intent Recognized trigger hadn't been added, manually adding this resolved the issue. If I'm adding a QnA KB and this trigger is not active we should be adding this automatically or at least offering. Otherwise developers will be stuck with a Bot that doesn't appear to work and it's not obvious they need to add a trigger.

## Version

2.0.0-nightly.241421

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a Bot (empty template)
2. Through Composer, add a KB - provide a URL to a list of FAQs
3. Observe FAQ items in composer
4. Select existing LUIS resource
5. Hit start (be aware of #7522)
6. type a question and observe in trace that QnAMaker returns a response
7. No response in WebChat

## Expected behavior

- A QnAMaker trigger added as part of the add KB flow
- Alternatively a warning/error telling the user what they need to do (Above is strongly preferred)

**Comment by sgellock** [comment]
Shiproom - lets spike the fix, and then assess the code change risk to determine whether it's in or out of R13

**Comment by benbrown** [comment]
I have eyes on the solution for this.

**Comment by sgellock** [comment]
Shiproom - approved
