### ISSUE TITLE
Publish bot by importing existing resources or by handing off to an admin

### ISSUE THREAD

**Issue by mmiele** [microsoft/BotFramework-Composer#7524]
### Importing existing resources  
During the publishing process got this error: 
DEPLOY_ZIP_ERROR: The hostname is invalid, please check if hostname/name-environment matches your target resource (webapp/function) name.

### Handing off to an admin
When running the command:
node provisionComposer.js --subscriptionId <YOUR SUBSCRIPTION ID> --name <RESOURCE NAME> --appPassword=<16 CHAR PASSWORD> --location=westus --resourceGroup=<RESOURCE GROUP NAME> --createLuisResource=false --createLuisAuthoringResource=false --createCosmosDb=false --createStorage=false --createAppInsights=false --createQnAResource=false

Got this error:
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (botazure\Scripts\provisionComposer.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
'5jON-PI#-9O]' is not recognized as an internal or external command,
operable program or batch file.

## Version

Version:  2.0.0-nightly.241057.db66154
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1.	In the Azure portal create the Azure Bot resource.
2.	Save the App Id and the password.
3.	In the right pane select **Open in Composer** card.
4.	Once in Composer create a new bot or select an existing one.
5.	Select **Publish** in the left menu.
6.	In the *Publish your bots* pane, select the bot to publish.
7.	From the drop-down list (box) select **Manage Profiles**.
8.	Select **Add New**. 
9.	Add the required information.
10.	Select **Next**.

**Importing existing resources**
1.	Select **Import existing resources**. Read the instructions on the right side of the screen and select Next.
2.	In the pop-up window **Importing existing resources**, modify the JSON file content based on your resources’ information. Then select **Import**.

**Handoff to admin**
1.	Select **Hand off to admin**. Read the instructions on the right side of the screen and select **Next**.
2.	In the **Add resources** page, select the required and optional resources you want the admin to provision. Select **Next**.
3.	On the **Share resource request** page, copy the instructions and securely share them with your Azure admin. You will need your Azure admin to run the provisioning command and create the resources for you.

## Expected behavior

Be able to publish the bot to Azure.

**Comment by Dewain27** [comment]
Documentation for #6258 should fix this issue.  Documentation being updated currently.
