### ISSUE TITLE
[settings] Editing allowed caller moves cursor to the end of the text field

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-Composer#7535]
## Describe the bug
If you edit the middle of a string in the Allowed Callers list, the cursor moves to the end of the string on each key stoke. The component should be updated to use unique keys for each array item to prevent the field from being rerendered on each key stroke. 

## Version
Latest build from main

## Screenshots
![Apr-30-2021 14-08-34](https://user-images.githubusercontent.com/17039790/116749169-c4c3a000-a9bd-11eb-81d5-bb8fb3e1ae6b.gif)

**Comment by sgellock** [comment]
Shiproom - please merge today.
