### ISSUE TITLE
An Azure Function project is provisioned as 32-bit, but built as 64-bit: Won't run on Azure

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/BotFramework-Composer#7538]
An Azure Function project will be provisioned as 32-bit (the default because it's not explicit).  However, when the project is deployed, the build command specifies 64-bit.  When run, Azure will report:

System.Private.CoreLib: Could not load file or assembly 'DotnetFunctions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

1) Manually changing the Function App in Azure to 64-bit will correct the problem.
2) The deployment also work (with no change to the Azure resource) if VS Publish is used.  In this case, VS Publish is using "portable" (anycpu), and Deployment Mode as "framework-dependent", where the deploy build in Composer appears to be using 64-bit and "self-contained".

See:
https://github.com/microsoft/BotFramework-Composer/blob/main/extensions/runtimes/src/index.ts#L116

# Potential solutions:
1) Change the provisioning of the Functions App to 64-bit, and keep the build steps the same (or force 64-bit always)
2) Or, Change the deploy build to use anycpu and framework-dependent.

# Unknown by me:
1) Difference between self-contained and framework-dependent
2) Eric and I aren't sure if "portable" is the same as "anycpu"

# Steps to reproduce:
1) Create a functions bot (mine included LUIS, but I don't think this matters)
2) Provision and deploy.
3) Test via Web Chat in Azure
4) The Function App resource will display the load error.  Though I did have to configure Logs in the resource.

VS Publish uses these settings, which work with the current provisioning:
![vspublish](https://user-images.githubusercontent.com/1024902/116752488-43730a00-a9cb-11eb-83d7-e245e9d7607a.PNG)

**Comment by tracyboehrer** [comment]
One workaround is to manually change the provisioned Functiona App on Azure to 64-bit.  Further deployments from Composer don't change that, and will continue to work.

So this may not be a P0 for R13.

**Comment by sgellock** [comment]
Shiproom - let get a PR then assess

**Comment by tracyboehrer** [comment]
Will do.  Mostly likely this is a Composer change.  Either in how it's provisioned, or how its built.  Maybe something else. But we can get the right brains involved to figure out the best solution.

**Comment by benbrown** [comment]
There is a bug in Composer in the call made to build for functions.  It was passing in the win-64 build option.

Here is my proposed PR: #7557 

@peterinnesmsft  @tracyboehrer  Please let me know if this sounds like the correct change.
