### ISSUE TITLE
Update provisionComposer.js for handoff

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#7539]
The provisionComposer script used for the admin handoff could be tweaked for its new use case.  This pertains to the *zipped copy of the provision script* distributed for admin handoff that lives on Github.

MUST DO:
- [x] if specified, resourceGroup is used for name of several items, resulting in mismatch in the final publishing profile.   (We either need to fix this, or remove the resourceGroup parameter from the instructions, as this can cause broken profiles)
- [x] and add tenantId (recently added in Composer)

NICE TO HAVE:
- [x] remove accessToken field (not needed)
- [x] luisResource gets set even if luis is not created (no impact, but confusing)

**Comment by sgellock** [comment]
Shiproom - approved. scoped to GitHub asset

**Comment by sgellock** [comment]
Shiproom - approved
