### ISSUE TITLE
Composer UI does not adequately support action schemas containing for arrays of objects

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#7542]
## Describe the bug
I have a custom action that includes an Array property of type object.

Here is the JSON of what the completed array should look like:
```
[
     {
          "EmailAddress": {
                "Name": "Megan Bowen",
                "Address": "email@domain.com"
           }
     },
     {
          "EmailAddress": {
                "Name": "Joni Sherman",
                "Address": "email@domain.com"
           }
     }
]
```

I wrote the following schema:
```
"attendees": {
      "$ref": "schema:#/definitions/arrayExpression",
      "title": "Attendees",
      "description": "Event attendees",
      "oneOf": [
        {
          "type": "array",
          "title": "Attendees",
          "description": "Event attendees",
          "items": {
            "type": "object",
            "title": "Attendee",
            "description": "Microsoft Graph Attendee",
            "properties": {
              "EmailAddress": {
                "type": "object",
                "title": "Microsoft Graph Email Address",
                "description": "Email address",
                "properties": {
                  "Address": {
                    "type": "string",
                    "title": "Address",
                    "description": "Attendee email address"
                  },
                  "Name": {
                    "type": "string",
                    "title": "Name",
                    "description": "Attendee name"
                  }
                }
              }
            }
          }
        },
        {
          "$ref": "schema:#/definitions/equalsExpression"
        }
      ],
      "examples": [
        "=dialog.event.attendees"
      ]
    }
```

The Composer UI for this property shows like this:
![image](https://user-images.githubusercontent.com/27976702/116769614-3a496380-a9f2-11eb-86bd-a9b96fbf0ab0.png)

The shown UI does not give me any ability to fill in the Address and Name Property, and when I type anything into the box, the underlying JSON creates an array from the entered string and essentially adds garbage to my object.

I would expect to be either just have an Object Editor input for each ArrayItem with the EmailAddress json preconfigured with empty string, or to have a way of entering the Name and Address fields in input boxes.

## Version

Version:  2.0.0-nightly.239644.d95eef8
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by tdurnford** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/6633 Should resolve this issue
