### ISSUE TITLE
Difference between Microsoft App registration vs 'Azure bot' ?

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7546]
Create a new Assistant bot
Add LUIS key etc via rocket menu
Create provisioning profile
Create new
Notice that we do not ask for 'App registration' in the wizard.
Notice that in the 'review' screen, it lists 'Microsoft App registration ID'

As a user, I have no idea where this comes from. I am creating an AZURE bot, why do I need a MSFT app registration??
Can we call this Azure Bot registration?

(note : In R11 and in the documentation this is still called 'web app bot' but moving forward this will be Azure bot)
<img width="942" alt="Screen Shot 2021-05-01 at 2 06 04 PM" src="https://user-images.githubusercontent.com/48503434/116795202-07ea4580-aa88-11eb-94b0-88d90347dc25.png">
<img width="954" alt="Screen Shot 2021-05-01 at 2 09 45 PM" src="https://user-images.githubusercontent.com/48503434/116795203-091b7280-aa88-11eb-89e4-0a3a6138dbe3.png">
<img width="737" alt="Screen Shot 2021-05-01 at 2 11 49 PM" src="https://user-images.githubusercontent.com/48503434/116795204-09b40900-aa88-11eb-84f0-a3bd4f1b38cd.png">

 it asks for a n Microsoft App registration while we're registering an 'Azure bot' and are asking for App/Azure app ID in other places?

hy are we calling this a Microsoft App registration while we're registering an 'Azure bot' and are asking for App/Azure app ID in other places?

**Comment by Dewain27** [comment]
This is a Microsoft App Registration which is separate from Azure.  We need to discuss further how to make this easier to understand in the next release.

**Comment by CharingJC** [comment]
FYI: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-basics?view=azure-bot-service-4.0

**Comment by OEvgeny** [comment]
This seems solved
