### ISSUE TITLE
Javascript Function Bot MicrosoftAppId/Password empty environment variables

### ISSUE THREAD

**Issue by joshgummersall** [microsoft/BotFramework-Composer#7555]
## Describe the bug

Provisioning a JS function bot yields a function app with `MicrosoftAppId` and `MicrosoftAppPassword` environment variables both set to empty strings. This overrides the `appsettings.json` file and yields a bot that does not authenticate incoming messages.

## Version

`2.0.0-nightly.241915.204a82`

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty Node function bot
2. Deploy to Azure

## Expected behavior

No blank environment variables

## Additional context

Environment variables serve as the mechanism to override things in `appsettings.json`, so we should not rearrange the precedence. Moreover, logic should not be added to ignore empty strings because there could be a valid use case to override a setting with an empty string.

**Comment by benbrown** [comment]
This has been resolved in #7557

**Comment by sgellock** [comment]
Shiproom - az functions is P0 scenario for R13 - approved
