### ISSUE TITLE
[bubb] Teaching bubble for starting your bot not popping up

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#7560]
## Describe the bug

The teaching bubble prompting to start your bot after setting up LUIS/QnA isn't showing.

![image](https://user-images.githubusercontent.com/55601267/116919059-989a6000-ac05-11eb-8cd8-51727fe081ff.png)

## Version

Version:  2.0.0-nightly.241915.204a82
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
macOS

## To Reproduce

1. Create conversation core bot
2. Go through LUIS and QnA key setup from rocket menu, selecting existing resources
3. Should get a teaching bubble prompting to start my bot, but it's not popping up for me

cc @Dewain27

**Comment by benbrown** [comment]
This was a regression.  I have fixed this in #7567

**Comment by sgellock** [comment]
Shiproom - approved as part of Fit & Finish work today
