### ISSUE TITLE
Create + config fit + finish

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#7565]
**Five areas, in descending importance:**
1. Project settings
2. Rocket panel
3. Publishing page + modal
4. Create modal
5. Misc

Please let me know if there's questions and send screenshots!

Note: I'm submitting this in progress so @pavolum can get started.
 

Project settings
---

**General items:**

![image](https://user-images.githubusercontent.com/55601267/116928352-cdacaf80-ac11-11eb-87e2-8fd1f96ee2c5.png)

- [x] - Command buttons—should only be “delete bot”; get rid of the rest
- [x] - Title of page should be “Project settings”
- [x] - No page sub-title copy
- [x] - Move json switch to right side and make text smaller size (12 I think)
- [x] - Pivot menu items capitalize only first word (MSFT convention)--"Development resources" and "Skill configuration"
- [x] - More space between pivot menu and content--should be consistent on each tab
- [x] - Align content with pivot menu on left side
- [x] - Max width of inputs and text 580x in all tabs
- [x] - In all tables, headers should be semi-bold rather than bold

**Overview tab:**

![image](https://user-images.githubusercontent.com/55601267/116931263-a5bf4b00-ac15-11eb-8120-dddfa61c4168.png)

- [x] - "Readme" instead of "Read Me"

![image](https://user-images.githubusercontent.com/55601267/116931212-96d89880-ac15-11eb-8c42-a42eef917510.png)

- [x] - Nix tool tip

**Dev resources tab:**

![image](https://user-images.githubusercontent.com/55601267/116929124-d356c500-ac12-11eb-9f45-89e620e8f0ed.png)

- [x] - Ensure padding at bottom of page

**Connections:**

![image](https://user-images.githubusercontent.com/55601267/116929339-23358c00-ac13-11eb-9b82-013c9c0d54fc.png)
![image](https://user-images.githubusercontent.com/55601267/116929320-1c0e7e00-ac13-11eb-966b-50a4b098170c.png)
![image](https://user-images.githubusercontent.com/55601267/116930575-c89d2f80-ac14-11eb-8ea0-3ee52db738f6.png)

- [x] - "Almost there" bubb is the wrong component, should be the blue one
- [x] - Tighten up horizontal spacing between columns in tables
- [x] - Should "visited links" be underlined? Not sure that's the right link component for internal app links.
- [x] - Lower-case M in "Open manifest"

Rocket
---

![image](https://user-images.githubusercontent.com/55601267/116930335-7e1bb300-ac14-11eb-8648-a8d7e0b0e615.png)

- [ ] 
- [x] - Action item sub-text too small
- [x] - Tighten space between action items more (between bottom of sub-text and title of next item)

![image](https://user-images.githubusercontent.com/55601267/116930444-a3a8bc80-ac14-11eb-8518-746bbddbf38e.png)

- [x] - Sub-titles should be semi-bold

Publish
---

**Publish page**

![image](https://user-images.githubusercontent.com/55601267/116933103-f041c700-ac17-11eb-845a-92d5f063adf5.png)

- [x] - Align table with “Publish” (move to the right)
- [x] - Make drop down maybe twice as wide
- [x] - "Publishing profile"--lowercase on profile

![image](https://user-images.githubusercontent.com/55601267/116933257-28e1a080-ac18-11eb-85a8-cff1e039d127.png)

- [x] - Super long add button (#7491)
- [x] - Table needs line under header—should be consistent with table on publish tab
- [x] - Headers should be semi-bold rather than bold in tables
- [x] - Edit and delete buttons are too small, too high--align bottom with "azurePublish" in this example
- [x] - Align Target column content with header (move content right)
- [x] - Tighten spacing between edit and delete buttons

**Provisioning modal**

![image](https://user-images.githubusercontent.com/55601267/116934135-65fa6280-ac19-11eb-8b8e-a838d4d69938.png)

- [x] - "Learn more" move to top sentence after "...Microsoft Azure is required." and lowercase m

![image](https://user-images.githubusercontent.com/55601267/116933903-0dc36080-ac19-11eb-898e-bf3b846e5ffb.png)

- [x] - Error copy should be closer to the input it's for than the one below

![image](https://user-images.githubusercontent.com/55601267/116934009-364b5a80-ac19-11eb-8341-9f6b7cfb6d4f.png)

- [x] - Lowercase m

Create
---

![image](https://user-images.githubusercontent.com/55601267/116934410-cf7a7100-ac19-11eb-975f-dc197c6b6222.png)

- [x] - Semi-bold title on all screens
- [x] - Do we need description field? Can we remove it?
- [x]     - If so, maybe runtime type on right?
- [x] - Inputs same width (370px?)
- [x] - “Create new folder” under input
- [x] - Button should say “Create” instead of OK
- [x] - Back button to return to template selection screen
- [x] - Can we get a background or border around files?

Preferred:
![image](https://user-images.githubusercontent.com/55601267/116934579-005aa600-ac1a-11eb-8654-8ed090e072ea.png)

Misc
---

![image](https://user-images.githubusercontent.com/55601267/116934739-36982580-ac1a-11eb-9583-924c29f2067f.png)
- #7283 better error copy to tell user to reboot composer

**Comment by benbrown** [comment]
If possible, also include #7390

**Comment by benbrown** [comment]
If possibley, also #7578

**Comment by sgellock** [comment]
Shiproom - please contain this work to "no code changes"

**Comment by emivers8** [comment]
Add-on: Runtime manager should always be on top.

![image](https://user-images.githubusercontent.com/55601267/117044088-dc06d400-acc2-11eb-94f4-6192da788359.png)

**Comment by pavolum** [comment]
Note:

- [ ] add line under bot settings header

**Comment by pavolum** [comment]
Alright I have done everything except
- 
![image](https://user-images.githubusercontent.com/22845013/117076006-bc43d000-ad03-11eb-9438-effa85ee4440.png)
- DefineConversation: Back button to return to template selection screen
-  Tables in Connections tab has width that goes beyond parent container
