### ISSUE TITLE
Runtime Upgrade UX

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#7566]
## Description
This ticket documents the work done to push version 1.4.1 of Composer with the UX to show a breaking upgrade from v1.4.1 to v2.0 when Composer v2.0 releases.

The changes will be applied on the v1.4.1 branch

![Screen Shot 2021-05-03 at 2 37 08 PM](https://user-images.githubusercontent.com/13004779/116937066-8cba9800-ac1d-11eb-9cd7-563332a14224.png)

**Comment by sgellock** [comment]
Shiproom - migration is a P0 scenario - approved

**Comment by srinaath** [comment]
@sgellock using this ticket to get Composer's main rebased with 1.4.1 commits. Can merge the PR once I get the approval.

**Comment by srinaath** [comment]
Thanks @sgellock . PR is merged now.
