### ISSUE TITLE
Custom recognizer absent from Recognizer Type list

### ISSUE THREAD

**Issue by emgrol** [microsoft/BotFramework-Composer#7568]
## Describe the bug

The **Custom recognizer** doesn't appear in the **Recognizer Type** list.

## Version

Version:  2.0.0-nightly.241915.204a82
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Composer (latest nightly build)
2. Create a bot (I'm using the empty bot template)
3. Go to a dialog/bot project, click the drop-down list under **Recognizer Type**

## Expected behavior

Custom recognizer should appear as an option in the list

## Screenshots

![missing-custom-recognizer](https://user-images.githubusercontent.com/9682548/116940155-5d5a5a00-ac22-11eb-9216-c630b034211b.png)

**Comment by sgellock** [comment]
Shiproom - lets get a PR then we can assess for R13

**Comment by sgellock** [comment]
Shiproom - approved.  please merge today.
