### ISSUE TITLE
Fit  & finish - UI Copy | Chrome and left nav

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7569]
**Chrome & left nav UI Copy**
White cells = existing copy
Yellow/blue cells = new copy

Link to 'live' copy on 'Chrome & nav' tab: https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

![Home_copy](https://user-images.githubusercontent.com/48503434/116944142-be396080-ac29-11eb-857f-53f7e4076f71.png)

![Leftnav_copy](https://user-images.githubusercontent.com/48503434/116944516-7ff07100-ac2a-11eb-99f8-872dd2d5d833.png)

**Comment by sgellock** [comment]
Shiproom - assuming low risk fixes, and not removing any existing content, only replacing appropriately, approving as today is fit and finish day.  must be merged by EOD today

**Comment by sgellock** [comment]
Shiproom - approved.  @beyackle can you get this merged ASAP, we're going to kick off another nightly with these changes and a few more.
