### ISSUE TITLE
Fit & finish - UI Copy | Home page

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7570]
Fit & finish - UI Copy | Home page

White cells = existing copy
Yellow/blue cells = new copy
Orange = P0

Link to 'live' copy on 'Home page' tab: 
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

![Homepage_copy](https://user-images.githubusercontent.com/48503434/116946074-13777100-ac2e-11eb-934a-93e222d6f764.png)
![Home_Tutorials and videos](https://user-images.githubusercontent.com/48503434/116946071-12464400-ac2e-11eb-8833-7d3c070f66af.png)
![Home_whats new](https://user-images.githubusercontent.com/48503434/116946075-14100780-ac2e-11eb-9b7d-35c01dceff7e.png)

**Comment by sgellock** [comment]
Shiproom - approving as today is fit and finish day.  must be merged by EOD today
