### ISSUE TITLE
Fit & finish - UI Copy | Rocket menu

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7571]
Fit & finish - UI Copy | Rocket menu

White cells = existing copy
Yellow/blue cells = new copy
Orange = P0

![Rocketmenu](https://user-images.githubusercontent.com/48503434/116946931-4ae71d00-ac30-11eb-8a17-cf8fb240d8d4.png)

Link to 'live' copy on ' Rocketmenu ' tab: 
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

**Comment by benbrown** [comment]
Resolved by #7599

**Comment by sgellock** [comment]
Shiproom - approving as today is fit and finish day.  must be merged by EOD today

**Comment by mareekuh** [comment]
Added: Learn more tab.

![Uploading Learn more tab.png…]()
