### ISSUE TITLE
Fit & finish - UI Copy | Get LUIS

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7572]
Fit & finish - UI Copy | Get LUIS

White cells = existing copy
Yellow/blue cells = new copy
Orange = P0

Link to 'live' copy on 'Get LUIS ' tab: 
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

![GetLUIS](https://user-images.githubusercontent.com/48503434/116947193-f42e1300-ac30-11eb-93a8-585c41949c18.png)
![Share_resource](https://user-images.githubusercontent.com/48503434/116947201-f85a3080-ac30-11eb-91ee-485de1990090.png)

**Comment by sgellock** [comment]
Shiproom - approving as today is fit and finish day.  must be merged by EOD today
