### ISSUE TITLE
Fit & finish - UI Copy | Bot templates

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7573]
Fit & finish - UI Copy | Templates

White cells = existing copy
Yellow/blue cells = new copy
Orange = P0

Link to 'live' copy on ' Bot Templates ' tab: 
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

![People](https://user-images.githubusercontent.com/48503434/116948079-4a03ba80-ac33-11eb-8c72-b8266e79de68.png)
![Calendar](https://user-images.githubusercontent.com/48503434/116948080-4a9c5100-ac33-11eb-9cf7-e84664a398aa.png)
![EnterpriseAssistant](https://user-images.githubusercontent.com/48503434/116948082-4b34e780-ac33-11eb-9a25-d260cf48fdf1.png)
![Assistant](https://user-images.githubusercontent.com/48503434/116948083-4bcd7e00-ac33-11eb-93a2-e17caba147e9.png)
![QnAmaker](https://user-images.githubusercontent.com/48503434/116948084-4bcd7e00-ac33-11eb-9cb9-308e608d426a.png)
![Basic](https://user-images.githubusercontent.com/48503434/116948085-4c661480-ac33-11eb-9169-53fc2953f042.png)
![Empty](https://user-images.githubusercontent.com/48503434/116948086-4c661480-ac33-11eb-9073-9e976c4554ce.png)

**Comment by sgellock** [comment]
Shiproom - approving as today is fit and finish day.  must be merged by EOD today
