### ISSUE TITLE
Publish bot consistently hangs on 'Uploading zip file...' step

### ISSUE THREAD

**Issue by peterinnesmsft** [microsoft/BotFramework-Composer#7574]
## Describe the bug

Whenever attempting to publish a bot from Composer using a publishing profile, it consistently hangs on attempting to upload the zip file containing my bot to Azure App Service using Kudu Zip Deploy.

## Version

2.0.0-nightly.241057.db66154

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot with an existing configured publish profile.
2. Go to Publish tab.
3. Select publish profile, then click 'Publish selected bots'.
4. Click OK on the dialog that pops up.
5. Wait for step 'Uploading zip file... to <BotName-Environment>'.

## Expected behavior

Upload of zip should complete in a reasonable amount of time.

## Screenshots

![image](https://user-images.githubusercontent.com/53846082/116949996-9b627880-ac38-11eb-9a45-db0aa392bdb0.png)

## Additional context

I am continuing to have this issue on for both .NET Web App and Functions-based bots. The logs don't display anything useful in order to determine why it is hanging.

**Comment by Dewain27** [comment]
Trying to repro issue.  Currently, not something that we can reproduce.

**Comment by peterinnesmsft** [comment]
I think we can ignore this. I tried making some modifications to my network setup - it looks like the issue was most likely being caused by an incredibly low upload speed on my end.
