### ISSUE TITLE
Localized UI is only half implemented

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7576]
## Describe the bug
I changed the language in composer settings, and localization is spotty.

## Version

![image](https://user-images.githubusercontent.com/17789481/116951496-e3839a00-ac3c-11eb-8680-f7eb59fc174c.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
I changed the language to spanish:

## Screenshots

Home page is not localized
![image](https://user-images.githubusercontent.com/17789481/116951547-07df7680-ac3d-11eb-9832-e5cfe8ac5092.png)

Rocket page is not localized
![image](https://user-images.githubusercontent.com/17789481/116951562-12017500-ac3d-11eb-897e-c8bc4b33505c.png)

Start bot is not localized
![image](https://user-images.githubusercontent.com/17789481/116951565-188fec80-ac3d-11eb-9c91-4171a92cfb8c.png)

Some properties descriptions are localized and some not:
![image](https://user-images.githubusercontent.com/17789481/116951594-25acdb80-ac3d-11eb-84b8-02372fecf38c.png)

Some menu items are localized some are not:
![image](https://user-images.githubusercontent.com/17789481/116951640-3eb58c80-ac3d-11eb-8062-58b408df6ade.png)

Some debugger items are localized, and some are not:
![image](https://user-images.githubusercontent.com/17789481/116951671-5725a700-ac3d-11eb-8953-da45c03eed23.png)
![image](https://user-images.githubusercontent.com/17789481/116951686-60167880-ac3d-11eb-950e-a320ccbcd29a.png)

Title for QnA is not localized
![image](https://user-images.githubusercontent.com/17789481/116951717-7290b200-ac3d-11eb-9804-409cdc6e55ed.png)

Some settings are localized and some are not:
![image](https://user-images.githubusercontent.com/17789481/116951789-a8ce3180-ac3d-11eb-80d3-630999059f3a.png)
![image](https://user-images.githubusercontent.com/17789481/116951741-86d4af00-ac3d-11eb-8c31-3475b6583d49.png)
![image](https://user-images.githubusercontent.com/17789481/116951751-8dfbbd00-ac3d-11eb-955d-af24bbd722ea.png)
![image](https://user-images.githubusercontent.com/17789481/116951763-92c07100-ac3d-11eb-8c6d-bd065dac5835.png)
![image](https://user-images.githubusercontent.com/17789481/116951767-96ec8e80-ac3d-11eb-8ab9-3177073e68ad.png)
![image](https://user-images.githubusercontent.com/17789481/116951772-9b18ac00-ac3d-11eb-8e82-51db66a9e1e2.png)

Package Manager is not localized
![image](https://user-images.githubusercontent.com/17789481/116951807-bd122e80-ac3d-11eb-94f5-fc27c7dcc749.png)
![image](https://user-images.githubusercontent.com/17789481/116951815-c4d1d300-ac3d-11eb-9519-44083495b256.png)

![image](https://user-images.githubusercontent.com/17789481/116951868-e9c64600-ac3d-11eb-9a4c-f9e9d905cf07.png)

**Comment by cwhitten** [comment]
We periodically take batches generated from the Azure translation team, of which we will start a new batch today with the fit and finish work coming into the tree.
