### ISSUE TITLE
The language selector UX doesn't match rest of composer at all

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7582]
## Describe the bug

The language UX is from another planet.  
* The font size doesn't match anything in the ui
* The color doesn't match anything else in the UI
* The vertical height doesn't match anything else in the UI
* The style of it (rounded corners) doesn't match anything else in the UI.
* When you click on it, it shows a menu like box with a drop down in it.  Why doesn't the rest of the UI do this?
* The box points to a button which shows no selected state.  Contrast that with the "Start a bot menu" which changes color.

## Version

![image](https://user-images.githubusercontent.com/17789481/116951952-3e69c100-ac3e-11eb-8be1-8ff772baa21a.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior

Consistent design applied throughout the product.

## Screenshots

![image](https://user-images.githubusercontent.com/17789481/116953533-62c79c80-ac42-11eb-9644-f311cd7e132f.png)

![image](https://user-images.githubusercontent.com/17789481/116953682-b9cd7180-ac42-11eb-8aee-828546840249.png)

compare with this:
![image](https://user-images.githubusercontent.com/17789481/116953662-afab7300-ac42-11eb-936c-fe05577754a5.png)
![image](https://user-images.githubusercontent.com/17789481/116953674-b4702700-ac42-11eb-90f9-e112cde5ad3b.png)

**Comment by mareekuh** [comment]
I think this is a dupe?

**Comment by mewa1024** [comment]
related: #7733

**Comment by mewa1024** [comment]
related: #7116
