### ISSUE TITLE
Fit & finish - UI Copy | Provision and publish

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7583]
Fit & finish - UI Copy | Provision and publish

White cells = existing copy
Yellow/blue cells = new copy (replace existing copy with this)
Orange = P0 | MUST UPDATE

Link to 'live' copy on ' Provision and publish ' tab: 
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

![Create profile](https://user-images.githubusercontent.com/48503434/116956737-e1c0d300-ac4a-11eb-9ac6-b3fe4cf6c4d8.png)
![Generate instructions](https://user-images.githubusercontent.com/48503434/116956738-e2596980-ac4a-11eb-8b96-02a7adaadd5b.png)
![Provide details](https://user-images.githubusercontent.com/48503434/116956739-e2f20000-ac4a-11eb-8b8b-df295a51d4dd.png)
![Review](https://user-images.githubusercontent.com/48503434/116956740-e38a9680-ac4a-11eb-8e3e-445b076d04ac.png)
![Select additional services](https://user-images.githubusercontent.com/48503434/116956741-e38a9680-ac4a-11eb-9fef-773ea8563393.png)
![Configure and create](https://user-images.githubusercontent.com/48503434/116956742-e4bbc380-ac4a-11eb-9030-6096c19b91cb.png)
![Add new provisioning profile -  long](https://user-images.githubusercontent.com/48503434/116956743-e4bbc380-ac4a-11eb-9e37-3efa79f62cec.png)
![Publish to PVA](https://user-images.githubusercontent.com/48503434/116956745-e5545a00-ac4a-11eb-8266-4e5cb0248509.png)
![Add new provisoning profile - create](https://user-images.githubusercontent.com/48503434/116956746-e5545a00-ac4a-11eb-886e-fbf1f05e6b1e.png)
![Add new publishing profile_new](https://user-images.githubusercontent.com/48503434/116956747-e5ecf080-ac4a-11eb-9b73-16781109def4.png)
![Add publishing profile](https://user-images.githubusercontent.com/48503434/116956749-e5ecf080-ac4a-11eb-83a2-606ec2db20f4.png)

**Comment by sgellock** [comment]
Shiproom - approving as today is fit and finish day.  must be merged by EOD today

**Comment by sgellock** [comment]
Shiproom - approved.

**Comment by mareekuh** [comment]
@natalgar  - lmk if I can help and answer questions about the xls or find 'learn more' help links if needed.
