### ISSUE TITLE
Fit & finish - UI Copy | Open from ABS

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7584]
Fit & finish - UI Copy | Open from ABS

White cells = existing copy
Yellow/blue cells = new copy (replace original copy with this copy)
Orange = P0, must update

Link to 'live' copy on '  ' tab: 
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea
![OpeninComposerfromABS](https://user-images.githubusercontent.com/48503434/116957486-cf479900-ac4c-11eb-8e93-81ce39166624.png)

**Comment by sgellock** [comment]
Shiproom - approving as today is fit and finish day.  must be merged by EOD today
