### ISSUE TITLE
Fit & finish - UI Copy | Configure and manage your bot (settings)

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7585]
Fit & finish - UI Copy | Configure and manage your bot (settings)

White cells = existing copy
Yellow/blue cells = new copy (update and replace existing copy with this)
Orange = P0 (must update)

Link to 'live' copy on ' Configure and manage (settings) ' tab: 
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

![Development ](https://user-images.githubusercontent.com/48503434/116959132-834b2300-ac51-11eb-9254-a708827de1b2.png)
![Skills and localization](https://user-images.githubusercontent.com/48503434/116959133-847c5000-ac51-11eb-9d96-4d73887969aa.png)
![Connections](https://user-images.githubusercontent.com/48503434/116959135-8514e680-ac51-11eb-87b5-98da6822d9e8.png)
![Readme](https://user-images.githubusercontent.com/48503434/116959136-8514e680-ac51-11eb-830f-1224e09a1923.png)

**Comment by sgellock** [comment]
Shiproom - approving as today is fit and finish day.  must be merged by EOD today

**Comment by benbrown** [comment]
All of the COMPOSER pieces of this are done. 

@sgellock  there is one section in this area that pertains to the README files in the generators.  Who did you assign the otehr component-related copy tasks to?

**Comment by sgellock** [comment]
@benbrown me.  I'm in that repo now
