### ISSUE TITLE
Fit & finish - UI Copy | Create/connect to a skill incl. orchestrator

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7587]
Fit & finish - UI Copy | Create/connect to a skill incl. orchestrator

White cells = existing copy
Yellow/blue cells = new copy

Link to 'live' copy on ' Add a skill ' tab: 
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

![Enable orchestrator](https://user-images.githubusercontent.com/48503434/116964136-a54ba200-ac5f-11eb-8d7c-db76b99b98a2.png)
![ Create dialog](https://user-images.githubusercontent.com/48503434/116964138-a67ccf00-ac5f-11eb-8480-50782619fb70.png)
![Connect to skill](https://user-images.githubusercontent.com/48503434/116964139-a67ccf00-ac5f-11eb-9e6f-9580f23a703a.png)
![Which bots allowed](https://user-images.githubusercontent.com/48503434/116964141-a7156580-ac5f-11eb-8d5c-ba6703180bf5.png)
![Export as skill](https://user-images.githubusercontent.com/48503434/116964144-a7156580-ac5f-11eb-888e-40ed178f11ea.png)
![add menu - skill](https://user-images.githubusercontent.com/48503434/116964146-a7adfc00-ac5f-11eb-834d-5ae1a12bdc9e.png)

**Comment by sgellock** [comment]
Shiproom - approving as today is fit and finish day.  must be merged by EOD today

**Comment by sgellock** [comment]
Shiproom - approved.  @beyackle can you get this merged ASAP please?  thank you
