### ISSUE TITLE
Fit & finish - UI Copy | Add KB key, QnA Maker dialogs

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7588]
Fit & finish - UI Copy | Add KB key

White cells = existing copy
Yellow/blue cells = new copy, copy and replace old copy with this
Orange = Must update (P0)

Link to 'live' copy on 'Add KB key - QnA  ' tab: 
https://microsoft.sharepoint.com/:x:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7B6B1FACBD-B5FE-4AD2-A35B-995635C1696B%7D&file=glossary.xlsx&action=edit&mobileredirect=true&wdPreviousSession=36539654-a42b-4b87-be1b-de96507b4422&wdOrigin=TEAMS-ELECTRON.teams.undefined&cid=676cf454-61e0-4182-bd27-39044bb51cea

![Add_menu](https://user-images.githubusercontent.com/48503434/116966301-b21ec480-ac64-11eb-929d-ddf7b3b36d50.png)
![Add KB wizard](https://user-images.githubusercontent.com/48503434/116966304-b21ec480-ac64-11eb-9780-539afcf234db.png)
![KB progress](https://user-images.githubusercontent.com/48503434/116966305-b2b75b00-ac64-11eb-8856-463e050d166a.png)
![Select QnA keys - rocket](https://user-images.githubusercontent.com/48503434/116966306-b34ff180-ac64-11eb-9c75-36314e4b6719.png)

**Comment by sgellock** [comment]
Shiproom - approving as today is fit and finish day.  must be merged by EOD today
