### ISSUE TITLE
Session does not expire after restarting the bot in Telegram

### ISSUE THREAD

**Issue by parsalotfy** [microsoft/BotFramework-Composer#7590]
## Describe the bug

Hi, I use bot Composer to make Telegram bots. I don't use C# and sdk.
The problem is that when I have a question in a dialog, if user Stops the bot in the middle of that question, and start it again, it seems the session would not expire. And it does not start again.
How can I fix this problem **in bot composer** ?

I try to explain better in the following picture and gif :

Here is how I created the bot :

![image](https://user-images.githubusercontent.com/30390810/117000180-ef7f6280-acf5-11eb-82f7-578ef01429d3.png)

And here is what happens :

https://user-images.githubusercontent.com/30390810/117000529-72a0b880-acf6-11eb-8554-3c76b73a577f.mp4

## Version

Version:  1.4.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
Design a bot like below
![image](https://user-images.githubusercontent.com/30390810/117000180-ef7f6280-acf5-11eb-82f7-578ef01429d3.png)

 and test it on telegram (not in emulator). Stop the bot after it asks you the question. Do Not answer the question.

1. Connect bot to telegram (do NOT test on emulator)
2. Start the bot on telegram
3. Do not answer the question
4. Stop the bot
5. Start the bot

## Expected behavior

It is expected that, when you restart the bot , it starts from _Hi from unknown with Question_ sentence

## Screenshots

https://user-images.githubusercontent.com/30390810/117000529-72a0b880-acf6-11eb-8554-3c76b73a577f.mp4

**Comment by NGame1** [comment]
Stop bot and Restart bot options in Telegram only blocks/unblocks the Bot user.
It's not an action or something. You should handle ```/start``` command in your bot commands to move your bot from any state to the initial state or to some other action you want depending on what you need. 
Regards.

**Comment by dmvtech** [comment]
Closing this as it is correctly answered by @NGame1. The bot is unaware of the changes being made on the Telegram side. You would need to implement logic to change that in the bot.
