### ISSUE TITLE
Create new speech service not authenticating for create new

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#7597]
## Describe the bug

When trying to enable speech service on a publishing profile, the create new service option does not prompt for authentication.  It just sticks on screen with no way to go forward.

![image](https://user-images.githubusercontent.com/18688053/117029712-8cc1a300-acc4-11eb-884c-93e6585b7d19.png)

## Version

Version:  2.0.0-nightly.242275.686a144
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Empty bot
2. Create a new Publishing profile using new services
3. Publish bot to Publishing profile
4. Go to bot settings and Connections
5. Turn on speech channel
6. Select to create new service
7. No Auth prompt and you can't proceed

## Expected behavior

Should be asked to logon to Azure and/or use existing auth

**Comment by mewa1024** [comment]
Hit similar thing with LUIS and QnA today -- related? #7601

**Comment by Virtual-Josh** [comment]
Same #7602
