### ISSUE TITLE
Azure sign-in not working (I signed in, but the directory and subscription fields are disabled

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#7601]
## Describe the bug

In the creation, I signed into Azure, but when I go to add resources the Azure directory and Subscription fields are diabled.

## Version

Bot Framework Composer

Version:  2.0.0-nightly.242275.686a144
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Composer.
2. Click New.
3. Choose template. I chose Core with Qna.
2. After downloading templates, the create QnA modal appears and the Azure sign in appears over it:
![image](https://user-images.githubusercontent.com/39317542/117046021-0a85ae80-acc5-11eb-9f6f-96f829d15c7f.png)

3. Finish sign in.
4. Eventually I got an error that QnA maker failed.
5. Try to add QnA Maker by clicking the project settings page.
4. The modal appears with the direction and subscription grayed out:
![image](https://user-images.githubusercontent.com/39317542/117046522-a2839800-acc5-11eb-9f5c-e1311bc35ed5.png)

5. Same for the adding LUIS:
![image](https://user-images.githubusercontent.com/39317542/117046555-aa433c80-acc5-11eb-9c40-39cb3c67b7d4.png)
![image](https://user-images.githubusercontent.com/39317542/117046568-af07f080-acc5-11eb-98ed-6566e141f0f2.png)

**Comment by Virtual-Josh** [comment]
I have a similar issue #7602

**Comment by hatpick** [comment]
I tried the steps, it asked me to login two times (my outlook web app on the phone does that most of the time too), but eventually it was successful. I used my Microsoft account (not personal)
