### ISSUE TITLE
Azure function start command won't do a rebuild when code changes

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7606]
## Describe the bug

The existing command **func start --script-root bin\Debug\netcoreapp3.1** is using a command which **bypasses the building** of the project. 

This means that when you do things like add a new package it won't rebuild the project.

## Version

![image](https://user-images.githubusercontent.com/17789481/117051565-8b47a900-accb-11eb-914d-199f3dd9a13c.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Edit the startup.cs and put a typo in it.
2. form CLI run **func start --script-root bin\Debug\netcoreapp3.1**
It should fail and it doesn't because it is not building the project. 

## Expected behavior

There are several issues here: 
1. **func start** is the normal way start a function project, and it will build and start the project.  
2. ^^^ but this fails because **.botproj** and **.csproj** files confuse it and  **func start** has no way to specify the csproj file directly
3. To workaround func start csproj/botproj conflict we are using **func start --script-root bin\debug\netcoreapp3.1**
4. The issue with ^^^ is that it **bypasses building the project.** and using **bin\debug\netcoreapp3.1** is that it is **assuming that the platform** is netcoreapp3.1 

There are 2 solutions.  
1. The correct solution would be to move the .botproj file to be a peer to the .SLN file. This would allow us to use **func start** as it's designed to do.
2. The hack solution would be to change the command to do a dotnet build directly like this:
``` 
dotnet build {projectName}.csproj & func start --script-root bin/Debug/netcoreapp3.1
```
Where {projectName} is replaced with actual project file name.

We should do number 2 for now, and fix this properly in a future release.

**Comment by sgellock** [comment]
Shiproom - moved to R14

**Comment by sgellock** [comment]
Shiproom - validate the scenario by adding a package to the az func based bot project
