### ISSUE TITLE
Fit & finish - UI Copy | LG Editor

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7612]
Fit & finish - UI Copy | LG Editor

**Change the following:**
Bot Responses -> Bot responses (sentence cap)
Button: Switch to code editor -> Show code

Response Variations ->  Responses
Tooltip (old) : One of the variations added below will be selected at random by the LG library
Tooltip (new) :Response alternatives will be selected at random for a more dynamic conversation.

Button: Add new variation -> Add alternative 

---

Prompt for text (title) -> Ask a question - text
Button: Switch to code editor -> Show code

Bot Asks (tab) -> Bot response (sentence capitalization)
User input (tab) -> User input

Prompt for text ->  Ask a question - text
Tooltip (old) : Message to send to collect information
Tooltip (new): Ask a question to collect user input (text)

Response Variations ->  Responses
Button: Add new variation -> Add alternative 

---

Prompt for a number (title) -> Ask a question - number
Button: Switch to code editor -> Show code

Bot Asks (tab) -> Bot response (sentence capitalization)
User input (tab) -> User input

Prompt for text ->  Ask a question - number
Tooltip (old) : Message to send to collect information
Tooltip (new): Ask a question to collect user input (number)

Response Variations ->  Responses
Button: Add new variation -> Add alternative 

---

Prompt for a number (title) -> Ask a question - confirmation
Button: Switch to code editor -> Show code

Bot Asks (tab) -> Bot response (sentence capitalization)
User input (tab) -> User input

Prompt for text ->  Ask a question - confirmation
Tooltip (old) : Message to send to collect information
Tooltip (new): Ask a question to collect user input (confirmation)

Response Variations ->  Responses
Button: Add new variation -> Add alternative 

---

Prompt for multi-choice (title) -> Ask a question - multi choice
Button: Switch to code editor -> Show code

Bot Asks (tab) -> Bot response (sentence capitalization)
User input (tab) -> User input

Prompt for text ->  Ask a question - multi choice
Tooltip (old) : Message to send to collect information
Tooltip (new): Ask a question to collect user input (choice)

Response Variations ->  Responses
Button: Add new variation -> Add alternative 

---

Prompt for a file or an attachment (title) -> Ask a question - file or attachment
Button: Switch to code editor -> Show code

Bot Asks (tab) -> Bot response (sentence capitalization)
User input (tab) -> User input

Prompt for text ->  Ask a question - file or attachment
Tooltip (old) : Message to send to collect information
Tooltip (new): Ask a question to collect user input (file or attachment)

Response Variations ->  Responses
Button: Add new variation -> Add alternative 

---
Prompt for a date or a time -> Ask a question - date or time
Button: Switch to code editor -> Show code

Bot Asks (tab) -> Bot response (sentence capitalization)
User input (tab) -> User input

Prompt for text ->  Ask a question - file or attachment
Tooltip (old) : Message to send to collect information
Tooltip (new): Ask a question to collect user input (date or time)

Response Variations ->  Responses
Button: Add new variation -> Add alternative 

---

OAuth login -> Ask a question - OAuth login
Button: Switch to code editor -> Show code

Bot Asks (tab) -> Bot response (sentence capitalization)
User input (tab) -> User input

Default value response ->  Ask a question - OAuth login
Tooltip (old) : Message to send when max turn count if specified has exceeded and the default value is selected as the value
Tooltip (new): Ask a question to collect user input (OAuth login)

Response Variations ->  Responses
Button: Add new variation -> Add alternative 

---

---

Send a response to ask a question -> Ask a question - send activity
Button: Switch to code editor -> Show code

Bot Asks (tab) -> Bot response (sentence capitalization)
User input (tab) -> User input

Activity ->  Ask a question - send activity
Tooltip (old) : Activity to send
Tooltip (new): Ask a question to collect user input (send activity)

Response Variations ->  Responses
Button: Add new variation -> Add alternative 

---

**Comment by sgellock** [comment]
Shiproom - approved WITH CONDITIONS

this came in after we agreed to the scope of today's fit and finish work.  IF we can get this done AND merged by EOD today, then we'll take it.  If not, it will get moved out to R14

**Comment by mareekuh** [comment]
You guys rock

**Comment by mareekuh** [comment]
@tdurnford  - is there a way to do a search & replace for the 'Switch to code editor -> Show code' replacement?
And Switch to response editor -> Hide code
