### ISSUE TITLE
Fit and finish | sentence capitalization

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#7613]
![Screen Shot 2021-05-04 at 12 42 52 PM](https://user-images.githubusercontent.com/48503434/117060943-6dcc0c80-acd6-11eb-93dd-374c56296757.png)

![Screen Shot 2021-05-04 at 12 44 49 PM](https://user-images.githubusercontent.com/48503434/117061135-acfa5d80-acd6-11eb-9148-8d7e5f4f5e49.png)

**Comment by sgellock** [comment]
Shiproom - approved WITH CONDITIONS

this came in after we agreed to the scope of today's fit and finish work.  IF we can get this done AND merged by EOD today, then we'll take it.  If not, it will get moved out to R14
