### ISSUE TITLE
Put token auth behind a facade for auth (with tenant ID)

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#7626]
Extensions and UI components should not be aware that the user is prompted for tokens in the web app scenario.  This needs to be behind a facade that provide either token dialog or azure sign in.

**Comment by benbrown** [comment]
Various parts of the auth process are in play in the following files:

- [ ] ManageService.tsx
- [ ] ABSChannels.tsx
- [ ] PublishProfileDialog.tsx
- [ ] Publish.tsx
- [ ] azureProvisionDialog.tsx
- [ ] TenantPicker.tsx
