### ISSUE TITLE
Install composer v1.4 - yarn build error

### ISSUE THREAD

**Issue by Olakhrisat** [microsoft/BotFramework-Composer#7643]
Hello,

I was trying to install composer v1.4 and I got this error
![image](https://user-images.githubusercontent.com/59798587/117118652-b26cac00-ad99-11eb-9d76-7d61fd2f86e3.png)

I followed these steps:
$ git clone https://github.com/microsoft/BotFramework-Composer.git
$ cd BotFramework-Composer
$ cd Composer // switch to Composer folder
$ yarn install // install dependencies
$ yarn build // build extensions and libs
$ yarn startall // start client and server at the same time

and I updated yarn version to v1.21.1 and tried yarn tableflip command but I'm still facing the same issue

Can you please advise?

**Comment by cwhitten** [comment]
@Olakhrisat what version of Node do you have installed on your machine? Can you also use the C drive when building Composer instead of the D drive?

**Comment by Olakhrisat** [comment]
> @Olakhrisat what version of Node do you have installed on your machine? Can you also use the C drive when building Composer instead of the D drive?

thank you for your reply, the node version is v12.13.1
I used C drive and still got same issue
![image](https://user-images.githubusercontent.com/59798587/117260152-71d36800-ae57-11eb-8c48-0e8f6f4a1cf7.png)

**Comment by cwhitten** [comment]
@Olakhrisat Can you upgrade to Node version 14 and try again?

**Comment by Olakhrisat** [comment]
@cwhitten it works fine now, thank you for helping
