### ISSUE TITLE
bump wait-on to v5.3.0 to address axios vulnerability

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [microsoft/BotFramework-Composer#7647]
Vulnerability: https://snyk.io/vuln/SNYK-JS-AXIOS-1038255
Fixed by updating axios to >v0.21.1
Fixed in wait-on here: https://github.com/jeffbski/wait-on/commit/31334602a79f86d8d8580d84e80debbdbe9d905a (included in v5.2.1)

**Comment by sgellock** [comment]
Shiproom - approved.  security issue
