### ISSUE TITLE
Orchestrator is missing resources for function bots

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7653]
## Describe the bug
Orchestrator is missing a models folder when using function bots. 

## Version
Version:  2.0.0-nightly.242720.c3b8105
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty dotnet function bot 
2. Create provisioning profile for the bot
3. Add an intent dialog and trigger to the bot
4. Add orchestrator package
5. Start the bot
6. Send the bot a message to trigger the dialog

## Expected behavior
It should work

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/117204412-1ea0dd00-ada5-11eb-95af-a10bf5e8e5ea.png)

## Additional context
This is unconfirmed, but I'd imagine the underlying issue is similar to [this one ](https://github.com/microsoft/botframework-components/issues/1063)

**Comment by sgellock** [comment]
Shiproom: @taicchoumsft can you root cause this and then let's discuss and assess

**Comment by Virtual-Josh** [comment]
This doesn't repo on the current nightly build of Composer/orchestrator 4.13.1. When I tested the current version of orchestrator was an RC so maybe now that it's actually released it's better. If I can find a consistent repo for this issue I'll reopen/create a new ticket.
