### ISSUE TITLE
Exporting as a skill is broken

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7655]
## Describe the bug
The export as a skill is currently broken despite it looking like it works. 

## Version
Version:  2.0.0-nightly.242720.c3b8105
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty web app dotnet echo skill
2. add a echo dialog, and an intent trigger to wire up the dialog
3. create and publish the skill
4. export the bot as a skill
5. Create an empty web app dotnet parent bot
6. Add -> remote skill
7. enter the manifest url

## Expected behavior
The manifest should populate the skill data, but it throws an error.

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/117208087-9244e900-ada9-11eb-8df5-8249c8c69e3d.png)

## Additional context
It's unclear if the flow works if you create the bot, export as a skill, then create a provisioning profile vs creating the bot, creating the provisioning profile, then exporting as a skill. 

Here's the manifest url:
https://NWAEcho55.azurewebsites.net/manifests/NWAEcho55-2-1-manifest.json

**Comment by benbrown** [comment]
I believe this particular issue was related to the manifest URL above actually being a 404.

A valid manifest should work.

**Comment by benbrown** [comment]
I experienced failed skill publishes as well.

https://www.loom.com/share/88d081c5806c4f169700a8d1da042772

It seems that when using he "Export skill" flow, it does not always successfully create the manifest or complete the full process.

**Comment by benbrown** [comment]
Here is another video demonstrating strange behavior during the "Export as skill" flow when no publishing profile exists:

https://www.loom.com/share/2d7cb1a5bfee444faac3bc3f00c93491

This seems to fail in several ways:

* the skill manifest is never stored in the project
* at the end of the provisioning process, an error appeared that the publish failed
* however, the publish was still underway
* when the publish completed, the skill manifest was absent

**Comment by benbrown** [comment]
This *DOES* appear to work if the publishing profile already exists:

see here:
https://www.loom.com/share/6adfb808cbc740759ecf0a76d9ca2a5d

**Comment by sgellock** [comment]
Shiproom - the sequencing here matters.  If you create a publishing profile first, which causes a publish, then the share as a skill works as expected.  if on the other hand you don't create a pub profile first, but instead attempt to share as a skill, then we're broken

**Comment by sgellock** [comment]
Shiproom - also, if you share as a skill before publishing, you'll get this failure.  however, if you share the bot again, the flow will succeed

**Comment by darrenj** [comment]
I suspect that the change taken earlier this week to remove the odd blocking behaviour (whilst provisioning works) has created a side-affect in that the UX just goes away meaning you don't get the manifest URL.

**Comment by tdurnford** [comment]
When the Create Skill Modal redirects the user to provision a new profile, it fails to save the manifest first. I think we just need to update the redirect to save the manifest first.

**Comment by tdurnford** [comment]
It looks like we are publishing the bot immediately after creating the publishing profile instead of returning to the create skill manifest modal to let the user add the endpoints to the manifest before publishing. Is there a way to defer deploying after creating the publishing profile?

**Comment by sgellock** [comment]
Shiproom - @benbrown can you look at the PR and then let's assess

**Comment by sgellock** [comment]
Shiproom - approved.
