### ISSUE TITLE
Azure Functions is installed - not detected by Composer w/o restart

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Composer#7657]
## Describe the bug

1. Azure Functions tools NOT installed. 
1. Created a "Functions" Bot. 
1. Installed the latest Azure Functions package via the link. 
2. Hit "Cancel" on the screen.    <-- Bug. Composer should check/restest for the Functions tools. 
3. Created a new Functions Bot. 
4. Composer doesn't pickup the installation.  <-- Bug. Composer should check/retest for the functions toos. 

![image](https://user-images.githubusercontent.com/1165321/117210978-47c56b80-adad-11eb-9df1-7b671f7bf67b.png)

Still unable to create a Functions Bot. 

If I *RESTART* composer, the Functions package is picked up, and I can create the bot. 

## Version
Version:  2.0.0-nightly.242920.45439b5
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by srinaath** [comment]
@cle
