### ISSUE TITLE
[Ubuntu] Publish Profile and other Azure related activites fail; no sign in allowance or token collection provided

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#7658]
## Describe the bug

Upgraded to latest nightly electron build, running from WSL2 (Ubuntu) on my machine.  Working through creating a publish profile for my bot, I get to the page where I start defining which directory; however it doesn't see me as signed in; there's no sign-in or sign-out button, and I'm not asked for my tokens.

## Version

Version:  2.0.0-nightly.242920.45439b5
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [X] Ubuntu

## To Reproduce

1. Create a composer bot
2. Start creating a publish profile
3. Get to the stage where it lets you choose directory
Experienced: Dropdown is empty, and has error (or not), but no directory is chosen, and there's no login UI

## Expected behavior

To be able to be effectively signed to Azure to complete the task

## Screenshots

![image](https://user-images.githubusercontent.com/5997512/117211537-fa95c980-adad-11eb-9743-58b0561bc19a.png)

**Comment by hatpick** [comment]
@tonyanziano is this because there is no native oneauth library?

**Comment by tonyanziano** [comment]
Correct. Linux is not supported by OneAuth. Currently they only have libraries for Mac, Windows 32-bit and 64-bit.

@carlosscastro and I spoke offline and he said he would reach out in the future to the OneAuth team to see what their roadmap is for Linux.
