### ISSUE TITLE
Enabling Application Insight  with Bot Composer and does not get "LuisResult" or "QnAMaker" name in telemetry data. 

### ISSUE THREAD

**Issue by damlaalkan** [microsoft/BotFramework-Composer#7661]
When I enable the application insight with Bot Composer and set log personal information to true, I can see in Apllication Insight log in CustomEvents the log name "BotMessageReceived" and "BotMessageSend" but I cannot collect luis or qna data as in the document:

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-analytics-queries?view=azure-bot-service-4.0#total-intents-by-popularity 

How can I enable LUISResults and QnA Maker result in the telemetry data?

Thank you!

**Comment by tsuwandy** [comment]
@damlaalkan, could you try setting LogPersonalInformation setting in Composer to '=settings.runtimeSettings.telemetry.logPersonalInformation' and see if you can see data from Luis or QnA Maker?

**Comment by sgellock** [comment]
Shiproom:  assess if this causes SDK patch

**Comment by Zerryth** [comment]
@damlaalkan, try the following as a workaround

1. Go to your config in Composer
2. Toggle to JSON view of config
3. Verify that your settings includes something that looks like the following:

<details>
<summary>Click to see abbreviated config JSON</summary>

```json
  "luis": {
    "authoringEndpoint": "",
    "authoringRegion": "westus",
    "defaultLanguage": "en-us",
    "environment": "composer",
    "name": "CoreWithLanguage",
    "endpoint": "",
    "authoringKey": "63e7xxxxxxxxxxxxxxxxxxxxxxxx37a8",
    "endpointKey": ""
  },
  "qna": {
    "hostname": "",
    "knowledgebaseid": "",
    "qnaRegion": "westus",
    "endpointKey": "",
    "subscriptionKey": ""
  },
  "runtimeSettings": {
    "adapters": ...,
    "features": ...,
    "components": ..,
    "skills": ...,
    "storage": ...,
    "telemetry": {
      "logActivities": true,
      "logPersonalInformation": true,
      "options": {
        "connectionString": "InstrumentationKey=61bbxxxx-xxxx-xxxx-xxxx-xxxxxxxx8038;IngestionEndpoint=https://westus2-2.in.applicationinsights.azure.com/"
      }
    }
  },
      ...
  }
```

</details>

4. **As a workaround** , add `telemetry` object as a child of the entire config object, **sibling** to other settings like `luis` and `qna`, could you add telemetry settings directly:

```
{
    "qna": { ... }
    "luis": { ... }
    "telemetry": {
         logPersonalInformation: true
      }
}
```

5. Talk to your composer bot to create LUIS and QnA telemetry events
6. Query App Insights -- do a generous query at first, such as just querying for `customEvents`.
    * Note: you may need to wait 3 - 5 minutes after you've talked to your bot for the telemetry details to appear in Application Insights.
7. You should be able to see `LuisResult` and `QnAMakerRecognizerResult` events in App Insights

**Comment by EricDahlvang** [comment]
Hi @damlaalkan 

Closing this, since a workaround has been provided by @Zerryth and we've merged the fix which is planned to go out with the next patch release.

Thank you for raising this issue.

**Comment by Gupta-Keshav-001378461** [comment]
> @damlaalkan, try the following as a workaround
> 
> 1. Go to your config in Composer
> 2. Toggle to JSON view of config
> 3. Verify that your settings includes something that looks like the following:
> 
> Click to see abbreviated config JSON
> 1. **As a workaround** , add a copy of your `telemetry` object as a child of the entire config object, **sibling** to other settings like `luis` and `qna`:
> 
> ```
> {
>     "runtimeSettings": { ... },
>     "qna": { ... },
>     "luis": { ... },
>     "telemetry": {
>          logPersonalInformation: true,
>          ...
>       },
>     ...
> }
> ```
> 
> 1. Talk to your composer bot to create LUIS and QnA telemetry events
> 2. Query App Insights -- do a generous query at first, such as just querying for `customEvents`.
>    
>    * Note: you may need to wait 3 - 5 minutes after you've talked to your bot for the telemetry details to appear in Application Insights.
> 3. You should be able to see `LuisResult` and `QnAMakerRecognizerResult` events in App Insights

Hi @Zerryth I have tired the same workaround in Bot Composer 2.1.1. I am testing the bot locally and cannot see any app-insights logged for LuisResult. Am I missing something?
