### ISSUE TITLE
luis application name should be updated for migration bot

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#7663]
## Describe the bug

luis application name in settings should be updated as well 
![image](https://user-images.githubusercontent.com/43408889/117253004-49f4fc00-ae79-11eb-8444-672a18603b4d.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

0. Electron nightly latest
1. Migrate old bot to new bot

**Comment by liweitian** [comment]
Closed due to out-of-date
