### ISSUE TITLE
Need scroll bar in dialog selection page for skill exporting (if this page is required)

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#7665]
## Describe the bug

Need scroll bar in dialog selection page for exporting a bot as skill if we did not disable this page .
![image](https://user-images.githubusercontent.com/43408889/117255860-bb827980-ae7c-11eb-8cb3-e56e8e5b82fa.png)

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

**Comment by vivekkshankar** [comment]
I recommend we make the select all checkbox sticky at the bottom and outside the scrollable area.
I strongly recommend against putting the select all checkbox below the fold.

![image](https://user-images.githubusercontent.com/67671676/118075516-fa28a000-b364-11eb-83b5-81c8191fca58.png)

**Comment by luhan2017** [comment]
@vivekkshankar close this one, and we will follow your design to fix this issue. dup with #7780
