### ISSUE TITLE
Install package on a running bot cause bot start failure

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#7669]
## To reproduce

1. start a bot
2. install a package
3. go back to design page, start bot
4. see error

Manually kill the dotnet process will work
## Version

Latest electron nightly

## Expected behavior

Install package on a running bot should not cause bot start failure.

## Screenshots

![image](https://user-images.githubusercontent.com/3829387/117291492-aa982f00-aea1-11eb-93b1-9eaaadef8d92.png)

**Comment by hibrenda** [comment]
I can hit this at the first restart bot but can get pass if you restart again. This is similar to #7667 .

**Comment by boydc2014** [comment]
seems to be duplicated with https://github.com/microsoft/BotFramework-Composer/issues/7498
