### ISSUE TITLE
.gitignore is excluding appsetting.json 

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/BotFramework-Composer#7677]
The .gitignore in a bot project is ignoring appsettings.json.  This causes difficult issues to fix when checking out the bot.  Namely "runtime" and "runtimeSettings".  Without "runtime", Composer treats the project as old runtime.  Without "runtimeSettings", things like which components get loaded are lost.  This is a minimum.  There are all kinds of values in there that should be retained.

The real issue that was trying to be solved is protecting secrets.  For which another solutions needs to be added.  KeyVault.

**Comment by sgellock** [comment]
Shiproom - approved

**Comment by sgellock** [comment]
Shiproom - approved - aligning to existing platform norms
