### ISSUE TITLE
Configure page has moved below the Create one in navigation

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/BotFramework-Composer#7688]
## Describe the bug

The Configure tab has moved up below the Create tab, I scanned the fit & finish issues and couldn't find a mention if this is intentional. If so please close!

## Version

`v2.0.0-nightly.243234.8264ac4`
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot and observe that it has moved

## Screenshots

![image](https://user-images.githubusercontent.com/43043272/117367840-8d4e6b00-ae77-11eb-84fd-4dfdd10592b5.png)

## Additional context

.

**Comment by sgellock** [comment]
Shiproom - moving out to R14.  @emivers8 is this what you intended?

**Comment by mewa1024** [comment]
I think this was a request from @mareekuh. (@mareekuh keep it as is for now?)
