### ISSUE TITLE
Move publish profile settings into appsettings and support multiple environments

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#7690]
As I'm working with the publish profile and configuration of appsettings, I find that I am frequently hopping back and forth between the Publish and Configure tabs trying to copy keys and reuse resources between my three bot projects. It has led me to feel like all of the keys and settings etc should all live in the configure tab and have multiple versions for dev/production/etc.

This aligns more to how environment settings are done traditionally, would reduce the effort of navigating through multiple levels of UI to get the right keys in the right places.

Also, this would better enable developers to work on and publish skills.

RIght now, Composer automatically adds the local skill configuration to allow local development, but does not provide any support for updating to the published endpoints when you're ready to publish. But If I change my composer settings to the published endpoints, I lose the ability to debug locally. If we had development app settings and production appsettings, this could be solved and would work both locally and when published and not require me to constantly update the skill settings as I work.

**Comment by mewa1024** [comment]
(@JaskeeratBedi-cmk @emivers8 @vivekkshankar fyi)

**Comment by JaskeeratBedi-cmk** [comment]
Thanks for sharing this feedback.. This is the direction we want to take as next steps for provisioning & publishing..(Tagging @Dewain27 @benbrown & @GeoffCoxMSFT)
