### ISSUE TITLE
Core Assistant template project won't start due to a condition return type error

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7700]
## Describe the bug

Creating a Core Assistant project generates a project on disk, but then triggers the following error:

`In CoreAssistantDocs.triggers[3].actions[1]: Branch: Switch (multiple options): condition the return type does not match`
![image](https://user-images.githubusercontent.com/33519520/117447814-dfee5c80-af35-11eb-9512-21c8b6c82322.png)

## Version

2.0.0-nightly.243234

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create Core Assistant project
3. Click Start Bot

**Comment by frarin** [comment]
I got the same problem.

Version:
2.0.0-nightly.243450

**Comment by sgellock** [comment]
Shiproom - @ryanlengel can you take this one, assume we'll need another RC of the templates

**Comment by ryanlengel** [comment]
Acknowledged - investigating offline with Composer crew. This appears to be a validation error introduced by Composer (using the `=` character in conditions).

**Comment by sgellock** [comment]
Shiproom - approved.  assistant is P0
