### ISSUE TITLE
Intermittent `Cannot read property error of undefined` error on start bot

### ISSUE THREAD

**Issue by darrenj** [microsoft/BotFramework-Composer#7701]
## Describe the bug

Intermittently hitting this error when click start Bot. Clicking start bot right away results in things working. Then later on, no pattern it will spuriously throw this unhelpful error.

![image](https://user-images.githubusercontent.com/33519520/117448565-d1547500-af36-11eb-8881-a5eb47a6e55c.png)

## Version

![image](https://user-images.githubusercontent.com/33519520/117448704-f943d880-af36-11eb-9589-d25deb161770.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by sgellock** [comment]
Shiproom - intermittent issue.  working to get a consistent repro

**Comment by boydc2014** [comment]
Some context, there is a known issue in bf-lu that the error message is "undefined", and @cosmicshuai fixed it in bf-cli. Here is the PR picking up that change in composer https://github.com/microsoft/BotFramework-Composer/pull/7399. 

I guess this is the same issue in @darrenj's case.

**Comment by cosmicshuai** [comment]
![image](https://user-images.githubusercontent.com/17074777/117939663-dea89f80-b33a-11eb-916f-1b75c7b9db2d.png)
I tried to repro this issue by calling luis build several times concurrently. And in my branch of fixing the undefined error, it can displayed the correct error msg from luis portal.

**Comment by sgellock** [comment]
Shiproom - still looking for a reliable repro to understand, moving out to R14

**Comment by cosmicshuai** [comment]
Oneway I reproduce this issue:
1. Use a free tier Luis subscription key
2. Create a batch script and open 10 terminal tabs, run the script concurrently.
```
@echo off
FOR /L %%G IN (1,1,2) DO run luis:build -i a.lu --authoringKey xxxxxxxxxxxxxx --botName testBot
```

3. After a while, it will reach a API call limitation, then use Composer to do the start bot with the same luis key setting.

**Comment by cwhitten** [comment]
We believe https://github.com/microsoft/BotFramework-Composer/pull/7399 has addressed this. Closing for now. @darrenj please re-open if you continue to see this.
