### ISSUE TITLE
Publish from LUIS fails in Composer

### ISSUE THREAD

**Issue by smoothcoder04** [microsoft/BotFramework-Composer#7702]
## Describe the bug
We are currently using  DefaultAzureCredential from @azure/identity library to get token (new DefaultAzureCredential().getToken('https://management.azure.com/')).token) which we use to publish the changes from composer to LUIS.
This works fine when we try to publish changes from local machine but fails on Composer web app hosted on Azure. On investigating further, we found that the bearer token looks different for local and web app. The publish ultimately fails with error - SyntaxError - Unexpected token o in JSON at position 1 as we don’t get the response from LUIS back because of incorrect token.
This makes us think that the token generation isn’t working properly. We started looking into using managed identity implementation.
Our plan here is to publish the changes to LUIS & QnA without the prompt to authenticate the user again before publishing.

Any idea why this isn't working?
thanks

## Version
1.3.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows

**Comment by smoothcoder04** [comment]
Not sure if this is the right way but was able to resolve this issue using service principal - https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/service-prin-aad-token.
Let me know how you are planning to implement this item.

thanks

**Comment by ninggao** [comment]
@benbrown  Could you please take a look at this?

**Comment by ninggao** [comment]
@benbrown Could you please take a look at this, or route it to anyone who's appropriate?

**Comment by ninggao** [comment]
@benbrown @stevengum is looking at a similar issue https://github.com/microsoft/BotFramework-Composer/issues/7849. Do you think it's related?

**Comment by johnataylor** [comment]
@benbrown @stevengum any update on this?

**Comment by benbrown** [comment]
@smoothcoder04 where are you making the changes to the authentication mechanisms? Are you working in a fork of Composer, or within the plugin system?

**Comment by mrivera-ms** [comment]
@smoothcoder04, are you still getting this issue? Please let us know if we should close this item. Thank you.

**Comment by smoothcoder04** [comment]
@benbrown  made the changes in the fork

@mrivera-ms  no, we resolved it using service principal. Was curious to understand how you plan to implement.
Feel free to close this issue.

Thanks
