### ISSUE TITLE
Composer does not connect Emulator to bot when selecting "Test in Emulator" on MacOS

### ISSUE THREAD

**Issue by thomas-chung** [microsoft/BotFramework-Composer#7710]
## Describe the bug

I can confirm this problem only happens on macOS and not Windows. When a user creates a bot (e.g. empty) and hit run on macOS, then clicking "Test in Emulator", the Emulator starts but does not connect to the bot. The work around would be instructing the user to manually open the bot.

This behavior is different from Windows where the same step would result with Emulator connecting to the bot upon opening.

## Version

Version:  2.0.0-nightly.243450.6728c56
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot using a template (e.g. Empty)
2. Start the bot locally
3. Click "Test in Emulator"

## Expected behavior

Emulator opens, connects to bot, and user can start interacting with the bot.

**Comment by thomas-chung** [comment]
@tonyanziano It was 2.0.0-nightly.243450.6728c56

**Comment by tonyanziano** [comment]
@thomas-chung the Emulator and Composer are on different major versions. Which version of the **Emulator** are you using?
