### ISSUE TITLE
Unable to publish QnA bot using handoff to admin

### ISSUE THREAD

**Issue by emgrol** [microsoft/BotFramework-Composer#7711]
## Describe the bug

Unable to publish a QnA bot (created from the C# template) using the handoff to admin

## Version

Version:  2.0.0-nightly.243450.6728c56
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Composer.
2. Create a C# QnA bot from the template list.
3. Go through the handoff to admin process.
4. Create a publishing profile and publish using the JSON from the admin.

## Expected behavior

The bot should be published.

## Screenshots

![handoff-error](https://user-images.githubusercontent.com/9682548/117513116-e684d000-af45-11eb-8930-1c398791a289.png)

## Additional context

More information about handoff issues:
- The script in the current UI is missing an equal sign after `subscriptionID` and the `name` parameters. They may be optional, but this doesn’t match the [README](https://aka.ms/how-to-complete-provision-handoff).
- We tested this w/o the `resourceGroup` parameter since that was creating issues previously.
- Regardless of whether there’s an error or the handoff process succeeds, you need to CTRL+C out.

**Comment by Dewain27** [comment]
Same issue as #7466

**Comment by Dewain27** [comment]
Provided @emgrol with RBAC that needs to be set to make it work.  She will be testing in the morning.

**Comment by sgellock** [comment]
Shiproom - closing as this was a setup issue.  See @Dewain27's comment above.
