### ISSUE TITLE
'Error occurred when parsing expression' when pasting in response templates.

### ISSUE THREAD

**Issue by dmvtech** [microsoft/BotFramework-Composer#7713]
## Describe the bug

Pasting two response templates, one that calls a second, a parsing expression error happens even though the naming is correct. Re-naming or pasting over the top resolves the issue.

## Version
```
Version:  1.4.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

- Go into Common bot responses
- Paste the following at the bottom:

```
# testTemplate
[HeroCard 
   title = Samsung Galaxy S21 Ultra 5G 
   subtitle = From £75 a month with £49 upfront. 
   text = Samsung Galaxy S21 Ultra 5G captures life's moments perfectly with next generation cameras and cutting edge innovations. 
   images = https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNROcS2-s7YOPsgpQ_xgqxFog-Hr2HSWLvM_wggbOjmwCqR_kcQaLA1LuvgJUQq83-3nO4e8g&usqp=CAc 
   buttons = ${​​​​​​​​testTemplate2('imBack', 'Show more cards', 'Show more cards')}​​​​​​​​ 
]

# testTemplate2 (type, title, value)
 [CardAction
    Type = ${if(type == null, 'imBack', type)} 
    Title = ${title} 
    Value = ${value}
    Text = ${title}
  ]
```
- Receive the following error:
```

line 347:13 - line 347:85 Property 'buttons=${​​​​​​​​testTemplate2('imBack', 'Show more cards', 'Show more cards')}​​​​​​​​ ': Error occurred when parsing expression '​​​​​​​​testTemplate2('imBack', 'Show more cards', 'Show more cards')'. Cannot read property 'stateType' of undefined
```
- Even thought the name of the second template being called from the first is correct (`testTemplate2`); something is disconnected. 
- If I copy and paste the name over the existing line calling it, it resolves/fixes it.

## Expected behavior

Should be able to connect them since they are named the same without having to paste/rename.

## Screenshots

![errorparsingexpression](https://user-images.githubusercontent.com/43397658/117516183-3f0b9b80-af4d-11eb-9617-3c32de5d4c51.gif)

**Comment by hatpick** [comment]
More information for this bizarre behavior:

https://user-images.githubusercontent.com/1483492/118042325-ccbe0100-b328-11eb-8a92-1b0601935a84.mp4

**Comment by dmvtech** [comment]
Interesting! That would explain why I didn't see those in Notepad++ with `Show Hidden Characters` enabled. 

Also in VSCode, it doesn't show with both `Render White Space` and `Render Control Characters` enabled either ☹
