### ISSUE TITLE
Make 'Disable' button a toggle instead of a drop down

### ISSUE THREAD

**Issue by dmvtech** [microsoft/BotFramework-Composer#7714]
## Describe the solution you'd like

To disable an action after selecting, you click 'Disable' in the toolbar above, then down to click on 'Disable'. As it's already enabled, 'Enable' is already unavailable. With only two options (`Disable`|`Enable`), seems like we don't need a drop down, unless there are plans for more options. Can save a click by just being able to toggle between Disable/Enable with one click and just have the display name to switch dynamically. Similar to the `Start Bot`|`Restart Bot` button. 

![image](https://user-images.githubusercontent.com/43397658/117518316-20f56980-af54-11eb-8e53-075ad81f09b4.png)

Vaguely related: https://github.com/microsoft/BotFramework-Composer/issues/3950

**Comment by dmvtech** [comment]
Realized that it is possible to select multiple actions that may have a _mix_ of both enabled and disabled states. This makes more sense to have a drop-down; to set the entire group as one specific state. But, on the flip side; I usually don't select more than one state (I would most likely select multiple actions of one state to flip to the other). All that being said, maybe the option presented in 3950 is the ideal.

**Comment by mewa1024** [comment]
Hmm. When multiple items are selected and some are ON and some are OFF, I think the toolbar command should say "Enable" which will turn them all on. I don't think users should expect to be able to have a toggle that switches each individual item to its opposite state.

**Comment by dmvtech** [comment]
>  I don't think users should expect to be able to have a toggle that switches each individual item to its opposite state.

@mewa1024 Understood. Just my $0.02, but that is the scenario that I use the most. it is an extremely common scenario for me (say where I have two different actions that have a fair amount of configuration, but I only want to use one at a time). Happy to chat or have a call on Teams if you want more of my perspective.
