### ISSUE TITLE
Incorrect validation on OutputFormat blocks bot to start

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#7718]
When supporting customer on https://github.com/microsoft/BotFramework-Composer/issues/7312 i found that, the latest nightly's validation on outputFormat is wrong, causing a correct term fail to start bot

![image](https://user-images.githubusercontent.com/3829387/117598213-e8cf7000-b179-11eb-836b-c2850226e792.png)

**Comment by sgellock** [comment]
Shiproom - lets review the PR and assess risk
