### ISSUE TITLE
Image carousel with different images and buttons in Bot Framework Composer

### ISSUE THREAD

**Issue by NikulDevis** [microsoft/BotFramework-Composer#7719]
I'm new to Bot Framework Composer. I've been trying to create a image carousel based on https://github.com/microsoft/BotFramework-Composer/issues/2004. But I would like to know how to implement the same, but with different image at each loop and buttons underneath them.

**Comment by aparnaji** [comment]
If you want different images , you can try invoking different json cards and each adaptive card underlying can show different image

# Welcome-Message
[Activity
    Text = Welcome
    Attachments = @{json(XXXX-Card1())} | @{json(XXXX-Card2())} | @{json(XXXX-Card3())}
    AttachmentLayout = carousel
]
