### ISSUE TITLE
Cannot start composer after Installing Latest version

### ISSUE THREAD

**Issue by UmaPrelude** [microsoft/BotFramework-Composer#7721]
Hi,
I was using 1.3.1 desktop version in my machine after updating to 1.4.1, I am not able to run composer successfully, it stops in the loading screen itself.
After referring to Issue : microsoft/BotFramework-Composer#5073

I ran from command prompt and seeing the below errors, please recommend the solution for this issue.

"(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false". It will change to be "true" in Electron 9. For
more information please check #18397
(node:7488) UnhandledPromiseRejectionWarning: Error: The specified module could not be found.
\?\D:\Composer\InstallLocation\Bot Framework Composer\resources\app.asar.unpacked\node_modules\orchestrator-core\orchestrator-core.node
at process.func (electron/js2c/asar.js:140:31)
at process.func [as dlopen] (electron/js2c/asar.js:140:31)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
at Object.func (electron/js2c/asar.js:140:31)
at Object.func [as .node] (electron/js2c/asar.js:149:18)
at Module.load (internal/modules/cjs/loader.js:816:32)
at Module._load (internal/modules/cjs/loader.js:728:14)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717:26)
at Module.require (internal/modules/cjs/loader.js:853:19)
(node:7488) UnhandledPromiseRejectionWarning: Error: The specified module could not be found.
\?\D:\Composer\InstallLocation\Bot Framework Composer\resources\app.asar.unpacked\node_modules\orchestrator-core\orchestrator-core.node
at process.func (electron/js2c/asar.js:140:31)
at process.func [as dlopen] (electron/js2c/asar.js:140:31)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
at Object.func (electron/js2c/asar.js:140:31)
at Object.func [as .node] (electron/js2c/asar.js:149:18)
at Module.load (internal/modules/cjs/loader.js:816:32)
at Module._load (internal/modules/cjs/loader.js:728:14)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717:26)
at Module.require (internal/modules/cjs/loader.js:853:19)
(node:7488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function withou
t a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function withou
t a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will ter
minate the Node.js process with a non-zero exit code.
(node:7488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will ter
minate the Node.js process with a non-zero exit code."

Also immediately after installing new version i got this error as well.
![image](https://user-images.githubusercontent.com/65938026/117655893-49c86980-b1b5-11eb-92ef-c5adf1b392a5.png)

**Comment by srinaath** [comment]
@taicchoumsft The error says a missing "orchestrator-core". Seems like something we have seen before. Any ideas here?

**Comment by taicchoumsft** [comment]
Hi @UmaPrelude , can we try a few things?

1) Can you verify if the file "orchestrator-core.node" is present in the location that the app is looking for? `D:\Composer\InstallLocation\Bot Framework Composer\resources\app.asar.unpacked\node_modules\orchestrator-core\orchestrator-core.node`
2) Can you try installing the latest `vc_redist` from [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) for your platform?  Let us know if you run into any error messages at this step
3) If Composer still fails to launch, can you try re-installing 1.4.1 from [here](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.4.1)

**Comment by UmaPrelude** [comment]
> Hi @UmaPrelude , can we try a few things?
> 
> 1. Can you verify if the file "orchestrator-core.node" is present in the location that the app is looking for? `D:\Composer\InstallLocation\Bot Framework Composer\resources\app.asar.unpacked\node_modules\orchestrator-core\orchestrator-core.node`
> 2. Can you try installing the latest `vc_redist` from [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) for your platform?  Let us know if you run into any error messages at this step. Restart PC and try launching Composer again
> 3. If Composer still fails to launch, can you try re-installing 1.4.1 from [here](https://github.com/microsoft/BotFramework-Composer/releases/tag/v1.4.1)

Yes i can see the file.
![image](https://user-images.githubusercontent.com/65938026/117830656-781b7700-b291-11eb-811c-34f60dc7e731.png)


I tried both the steps as you mentioned in your response, still the issue is not resolved.

**Comment by taicchoumsft** [comment]
Hi @UmaPrelude , can you tell us what version of Windows you're using?  Is it 32 or 64-bit?

**Comment by taicchoumsft** [comment]
Thanks @UmaPrelude, I am unable to repro this issue - can you try these steps if you have some time.  

1) Download [Dependencies](https://github.com/lucasg/Dependencies) from here
2) Unzip in any location, and run `DependenciesGui.exe`
3) Open a location, and load up the file `D:\Composer\InstallLocation\Bot Framework Composer\resources\app.asar.unpacked\node_modules\orchestrator-core\orchestrator-core.node`.  You'll need to select 'All Files' in the File Explorer to be able to see the `orchestrator-core.node` file.
4) If you look up the `orchestrator-core.node` dependencies in the dependencies list, do you see any errors? A working install will look like this: 
![image](https://user-images.githubusercontent.com/61705609/117921151-1107bd80-b2a5-11eb-8601-ddcf843b0b37.png)
Please post any errors you see here, this will inform us what dependencies are not able to load on your machine.

**Comment by taicchoumsft** [comment]
@UmaPrelude , that might be ok.  If you expand the `orchestrator-core.node` entry, do you see errors?

**Comment by UmaPrelude** [comment]
> @UmaPrelude , that might be ok. If you expand the `orchestrator-core.node` entry, do you see errors?

No errors.

**Comment by taicchoumsft** [comment]
Hi @UmaPrelude , can you post a screenshot of the expanded section under `oc_abi.dll`?

**Comment by UmaPrelude** [comment]
> Hi @UmaPrelude , can you post a screenshot of the expanded section under `oc_abi.dll`?

![image](https://user-images.githubusercontent.com/65938026/118613878-ccb47a00-b7dc-11eb-8e22-7eef8daf3b1f.png)

**Comment by taicchoumsft** [comment]
Hey  @UmaPrelude , I'm at a loss here, the screenshots show that the resources actually have loaded successfully.  Can you try using Composer on a Win10 machine?  

Unfortunately, we really do recommend moving off Windows 7 and using Windows 10, per our docs [here](https://github.com/microsoft/BotFramework-Composer/blob/main/docs/1.3-supported-os.md).  Sincere apologies, there's not much I can do for support. 

Adding @daveta  and @tsuwandy  in case they can provide more help here.

**Comment by taicchoumsft** [comment]
Actually, maybe one more thing - can you make sure you've installed Node v12/v14 x64 bit and try again.

**Comment by UmaPrelude** [comment]
> Actually, maybe one more thing - can you make sure you've installed Node v12 or v14, 64-bit version and try starting Composer again.

Sorry for the delayed response.

I have upgraded to 12.22.1 from 12.16. Even then same issue.
Also when i try to install version 14, getting message as it is not supported for windows 7, and it is supported from win 8.1.

**Comment by chrimc62** [comment]
We recommend using supported versions.
