### ISSUE TITLE
Rocket panel action items in the wrong category/order

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#7735]
## Describe the bug

Current state shows "Publish your bot" and "Add connections" at the bottom of the panel, under the "Optional" category. Those items should be higher up in the "Recommended" category.

Current:
![image](https://user-images.githubusercontent.com/55601267/117736000-7f685500-b1ab-11eb-92dd-cbc8c38bc4d3.png)

Should be (minus copy updates and state of checkmark):
![image](https://user-images.githubusercontent.com/55601267/117736156-d706c080-b1ab-11eb-886c-218de05e65cd.png)

## Version

Version:  2.0.0-nightly.243997.543d0b4
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
macOS

## Additional context

This impacts discoverability for important flows, publishing and adding connections.

**Comment by sgellock** [comment]
Shiproom - moving out to R14
