### ISSUE TITLE
Creation flow needs to allow operating system choice for Az Functions

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#7738]
## Describe the bug
The creation flow for new bots when selecting az functions does not allow the user to choose Linux and today defaults to Windows.  

We need to provide an option to allow the user to select with OS they want to use with the func app, and we should also default to Linux.

I also just had a conversation around iisnode, and the recommendation is to run this on linux as well.  so, in addition to az func we need to consider the options and defaults for good ol' web apps too.

**Comment by benbrown** [comment]
See also: https://github.com/microsoft/BotFramework-Composer/issues/7505

**Comment by cwhitten** [comment]
@Dewain27 I've assigned this to you to find a dev owner for this you're driving it in the R14 Creation & Publishing board.

**Comment by GeoffCoxMSFT** [comment]
@sgellock  For R14 we're adding OS selection to provisioning. 
Here is the work item: https://github.com/microsoft/BotFramework-Composer/issues/8063.  

The user could choose a different OS for an Azure function for different deployments.  I think this alleviates the need to select the OS during creation time, correct?
