### ISSUE TITLE
Extract the build steps from Composer and move them to the runtime project itself

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#7741]
Currently, Composer has an internal definition of the steps needed to build, run and deploy the bot projects.  In some cases these are shared (LUIS and QNA steps), but in others they are specific to each runtime type.

This adds *magic* to the build/deploy process which is hard for developers to understand. It also makes the CI/CD pipeline and publishing story more complicated.

We should extract the LU build and other steps into configuration and move these into the bot project. Then, Composer can simply execute the prescribed actions without knowing the specifics.

**Comment by benbrown** [comment]
Assigning some folks here who I know have input on this!

**Comment by cwhitten** [comment]
Before the team dives into the technical details and implementation I'd like to assert the following for consideration as principles & constraints to align on that can act as a guide:

1. Composer uses core libraries published outside of the application to manage. This spans runtime, lu/language models, packages, skills, language & expression parsing (lu/lg/qna/adaptive-expressions), etc.
2. The bf-cli is the place where these core libraries are stored & published.
3. Customers can take these libraries and compose them with their own scenarios and are _extensible_.

Here are the constraints that I believe these core libraries all need to consider and support:

1. Access to a programming interface (typescript)
2. Active application/environment state is also an input parameter for dynamic data binding
3. Access to shared modules or a standard library is also important to avoid unnecessary complexity in the app code
4. A customer may want to extend or control this behavior for their custom use case.

If we can align on the above, here is the context of where things are today:

Build steps around `lubuild`, `qnamaker`, and `crosstrain` are already extracted into core libraries and should already be modeled appropriately. Using these in the BF CLI is documented here: https://github.com/microsoft/BotFramework-Composer/blob/main/docs/archived%20docs/how-to-process-language-models-with-CI-CD.md

What's missing is the following, and it may not be an exhaustive list:

1. Recognizer dialog generation, and the creation/management of the `/generated` folder.
2. Orchestrator has some build steps that should be moved into the `orchestrator` package in the cli around model snapshot generation.
3. Runtime execution and environment variables/settings that are constrained to the execution environment, i.e. functions has a convention, webapps has another convention, dotnet, node, etc. This is all hand-crafted and artisanal code inside Composer at the moment.
4. Composer also has handcrafted & artisanal code around adding/removing packages, templates, and skills.

_**A quick caveat around azure resource management & publishing**_: the Azure cli tool to deploy and management resources is _not_ the bf-cli. It is the az-cli. We're not in the business of recreating the az-cli in the bf-cli. The publishing scenarios need to be treated a bit differently. Composer houses the code to manage provisioning and deployment as _Composer Extensions_, which are NOT built into Composer like the above list is--these are independent packages that Composer takes a dependency on. Their source happens to live in the Composer github repository. It has been discussed to in the future move these to another project, but there are no short-term plans to do this.

**Comment by gabog** [comment]
I agree with the principles @cwhitten, one comment on https://github.com/microsoft/BotFramework-Composer/blob/main/docs/archived%20docs/how-to-process-language-models-with-CI-CD.md: 
There is still some magic in composer that I had to replicate in powershell to fully implement a pipeline that supports CI/CD for C# with Cross Train, LUIS, Orchestrator and QnAMaker.
There's an issue on BF cross train that I posted [here](https://github.com/microsoft/botframework-cli/issues/1221) and I had to build some [PowerShell utilities](https://github.com/gabog/ComposerCICDSamples/blob/main/build/yaml/templates/LUUtils.ps1) to replicate what composer does. Based on that:

- Here is a PowerShell verion of LUIS build: https://github.com/gabog/ComposerCICDSamples/blob/main/build/yaml/templates/Build-LUIS.ps1

- And here is what I had to do to replicate Orchestrator build: https://github.com/gabog/ComposerCICDSamples/blob/main/build/yaml/templates/Build-Orchestrator.ps1

Once we update cross train and we agree on the folder layout, I think we should be able to replace the powershell scripts above with simple BF CLI calls. 

Somehow related to this is to refine what sections of appsettings (and other config files) are needed, who writes them, who reads them and where do we store them.

**Comment by peterinnesmsft** [comment]
Thanks for opening this issue @benbrown - definitely want to be involved in helping to figure this out, so please keep me involved!

@cwhitten thanks for laying out principles and constraints. Principles all make sense and are reasonable in my view. On the constraints, I understand 1), but additional context on 2) - 4) would be helpful to make sure I fully understand what you're getting at. If you have any particular use cases or scenarios in mind based on current experience, I think illustrating those would be helpful.

I expect that there is going to be a lot of work involved overall in this, so would be good to sync with everyone assigned to this issue so we can figure out next steps on how to get the ball rolling for this. I assume we would want to lead with a formal outlining of the relevant scenarios and high-level requirements and go from there.
