### ISSUE TITLE
[UI bug] Onboarding experience bubble empty/broken

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#7753]
## Describe the bug

The fourth step in the onboarding experience for configure and publish opens a teaching bubble that's now empty. 

![image](https://user-images.githubusercontent.com/55601267/117879888-52c04600-b25c-11eb-9d86-2993df38d07f.png)
![image](https://user-images.githubusercontent.com/55601267/117879910-594ebd80-b25c-11eb-95d8-e7bb4e773dea.png)

In the first step it's also pointing at the wrong thing for the very first teaching bubble for the main dialog, I think.

![image](https://user-images.githubusercontent.com/55601267/117879991-708dab00-b25c-11eb-959f-7b3986bf52a7.png)

## Version

Version:  2.0.0-nightly.244329.667b93f
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
macOS

## Expected behavior

I'm not sure what the original copy was for this--perhaps @xiyangdesign has the original design.

**Comment by tdurnford** [comment]
@emivers8 I opened a PR to fix the empty teaching bubble. To your second point, the 'Main Dialog' teaching bubble is pointing to the right anchor. @xieofxie

**Comment by xiyangdesign** [comment]
Yes I think the "Main Dialog" teaching bubble is correct, although main dialog has the same name with the bot project which could be confusing.

**Comment by emivers8** [comment]
Perfect! Thank you @tdurnford and @xiyangdesign

**Comment by sgellock** [comment]
Shiproom - moving out of R13.  we're cutting RC candidates tomorrow.
