### ISSUE TITLE
Setup is one word not two in Development Resources

### ISSUE THREAD

**Issue by Dewain27** [microsoft/BotFramework-Composer#7755]
## Describe the bug

The words "set up" on the buttons for the Development Resources in Bot Settings needs to be "setup"

![image](https://user-images.githubusercontent.com/18688053/117882893-683f6b00-b270-11eb-9adb-ed1d42a12727.png)

## Version

Version:  2.0.0-nightly.243450.6728c56
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

**Comment by mareekuh** [comment]
By design 
Set up = verb
Setup = noun

The button is an action, not a noun.
