### ISSUE TITLE
UX for LG/LU syntax highlight

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#776]
need to be consistent for lu/lg all up view and also for inline editor

**Comment by zhixzhan** [comment]
Current color theme references vscode's recommend, use not more than 5 color (most-used by other languages) highlighting the document.

The color customization is written in this file:  
https://github.com/microsoft/BotFramework-Composer/blob/fc61812bf3456bcb93287eb81b1d26b7f423e66f/Composer/packages/lib/code-editor/src/languages/lg.ts#L112-L124

preview with color:

![image](https://user-images.githubusercontent.com/49866537/69135802-a8e37b80-0af4-11ea-8741-6873df2729bd.png)

**Comment by hibrenda** [comment]
@DesignPolice  need your suggestions

**Comment by DesignPolice** [comment]
Thanks @hibrenda and @zhixzhan we will discuss it this morning -

**Comment by hibrenda** [comment]
Need discussion for syntax highlighting (template vs func) @DesignPolice @cwhitten 
![image](https://user-images.githubusercontent.com/43408889/69950118-c7eb0000-152d-11ea-9618-c9084563a682.png)
![image](https://user-images.githubusercontent.com/43408889/69950181-e81abf00-152d-11ea-8697-8a583fef5b32.png)

**Comment by DesignPolice** [comment]
Thanks Brenda, I will touchbase with Chris and Vish on this to get some feedback - thanks M

**Comment by DesignPolice** [comment]
Attached are the colors that Dong and I looked at - I don't use code editors - so my thought was that we should use Fabric colors that align with the default colors in Visual Studio. 

Making it as consistent as possible. If @cwhitten or @vishwacsena can help me verify that.

<img width="607" alt="Screen Shot 2019-12-02 at 4 34 35 PM" src="https://user-images.githubusercontent.com/45223620/70006909-7dfd1c80-1523-11ea-904a-a069fbb66130.png">

**Comment by DesignPolice** [comment]
I talked to @tdurnford and he pulled up the default Visual Studio coloring - they have a variety of themes which would be a nice add for us in the future. Here is their base color on white. So maybe I can just sample colors from this in the Fabric palette - does anyone have issues with that? I don't think it is beautiful, but with only one option I think it should be familiar to start with.

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/45223620/70022255-6be1a500-1548-11ea-926b-eb7aafb379f6.png)

**Comment by boydc2014** [comment]
> I talked to @tdurnford and he pulled up the default Visual Studio coloring - they have a variety of themes which would be a nice add for us in the future. Here is their base color on white. So maybe I can just sample colors from this in the Fabric palette - does anyone have issues with that? I don't think it is beautiful, but with only one option I think it should be familiar to start with.
> 
> ![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/45223620/70022255-6be1a500-1548-11ea-926b-eb7aafb379f6.png)

No problem at all with keyword as blue, and string literal as dark red (right?), it's just we have more stuff, like template-name, and function(template-ref), we also need some color for that

**Comment by boydc2014** [comment]
This is a good example our colors today
![image](https://user-images.githubusercontent.com/3829387/70027582-697d5a80-15dd-11ea-9d40-37d7742f4bc1.png)

**Comment by DesignPolice** [comment]
okay. After some frustration, I went through and checked colors on Visual Studio default colors, that hit contrast numbers. These descriptions came from @boydc2014 chatting about the different options. 

so looking at the two attachments these are Composer colors, that hit contrast numbers, that are pretty similar to this VS default. There are lots of options built in to the Monaco editor that help with Accessibility  

https://github.com/Microsoft/monaco-editor/wiki/Monaco-Editor-Accessibility-Guide

So lets try plugging these colors in and see how v14 looks in reality 
![Screen Shot 2019-12-03 at 11 39 20 AM](https://user-images.githubusercontent.com/45223620/70083935-34174380-15c2-11ea-9fe3-b865103e5ed6.png)
![Screen Shot 2019-12-03 at 11 39 03 AM](https://user-images.githubusercontent.com/45223620/70083951-3b3e5180-15c2-11ea-8fed-5a610043f0f0.png)



thanks

**Comment by cwhitten** [comment]
addressed in https://github.com/microsoft/BotFramework-Composer/pull/1706
