### ISSUE TITLE
Truncated trigger/dialog names should show full name on hover state

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#7760]
## Describe the bug

Truncated strings in the list of trigger/dialog names (navigation pane?) should display the full string on hover. Instead for some reason we actually truncate them *more* when you hover your mouse over them.

## Version

Daily

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot
2. Resize the left pane so names are truncated
3. Observe behavior

## Expected behavior

I do not have to resize the pane to see the full name.

## Screenshots

![image](https://user-images.githubusercontent.com/1139814/117888386-d8e18a00-b266-11eb-8cdf-ad597edc6ef9.png)

**Comment by mareekuh** [comment]
Resolution:
1. nav pane should be resizable.
2. hover over and click on the name should show the full name?

**Comment by clearab** [comment]
The pane is definitely resizable, but it would be really awesome if on hover the whole name was displayed in a bubble. We actually truncate even more for some reason on hover.

**Comment by mareekuh** [comment]
@vivekkshankar - I think you have already spec'ed this somewhere. Could you add the link to this bug so we can get this on the backlog to get fixed/implemented?

**Comment by mewa1024** [comment]
Example from VS Code:
![image](https://user-images.githubusercontent.com/39317542/124334301-8a0bee80-db4b-11eb-82de-c0ba02526c4d.png)


https://user-images.githubusercontent.com/39317542/124334323-9b54fb00-db4b-11eb-8904-8ca7021af59d.mov

Can we follow this behavior?
