### ISSUE TITLE
Mouse hover for trigger/dialog names

### ISSUE THREAD

**Issue by clearab** [microsoft/BotFramework-Composer#7761]
## Describe the bug

The mouse hover that changes the cursor to the hand version indicating I can click on something is applied only to the text of the trigger/dialog name, rather than the entire selectable area.

## Version

Daily

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot
2. Mouse over any trigger or dialog name
3. Move mouse cursor back and forth across selectable area
4. Observe error

## Expected behavior

The mouse cursor changes to indicate a selectable area for the entire selectable area.

**Comment by vivekkshankar** [comment]
@mareekuh fyi for design backlog
