### ISSUE TITLE
OAuth Login change in behaviour

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#7768]
## Describe the bug

When we use OAuth Login card in Bot Composer, Post deployment, it is giving a code to enter into bot, where the text box does not come up in the Bot

## Version

![image](https://user-images.githubusercontent.com/26645750/117930737-e42bc880-b2ed-11eb-9575-2aa273dddb27.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Dialog -> Trigger -> Add External Resources -> OAuth Login
2. Add the required title etc. , In web bot set up the app registration with the scopes
3. Deploy the bot , Test it, Bot gives the login card -> click on it page redirects to another page and which gives a code
4. But OAuth Login card will not have option to enter this code.

## Expected behavior

This was not the behavior previously. This is new behavior.

## Screenshots

![image](https://user-images.githubusercontent.com/26645750/117938961-1e4d9800-b2f7-11eb-83a0-594116cef78b.png)

## Additional context

![image](https://user-images.githubusercontent.com/26645750/117939193-5ce35280-b2f7-11eb-9baf-c68d10713464.png)

**Comment by luhan2017** [comment]
@aparnaji Please just try to input this code as a new message to the bot.
