### ISSUE TITLE
[MCS-DE] Telemetry Action migrated to Custom Action by Bot Upgrade process

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#7772]
When I do the upgrade of my Bot with the 2.0.0 nightly the "Telemetry Track Action" is moved to the Custom Action section and disabled.
![image](https://user-images.githubusercontent.com/31212469/117989493-abffa680-b33c-11eb-9bef-86c63169b9a6.png)

![image](https://user-images.githubusercontent.com/31212469/117989578-bb7eef80-b33c-11eb-95c7-ec7facbd5c7e.png)

After I remove the "disabled" in the code view on all these actions they are shown as default action again and work:
```
          "disabled": true
```

@garypretty

**Comment by cwhitten** [comment]
@goergenj after migrating the project, you need to update all of the instances of TelemetryTrackEvent to TelemetryTrackEventAction in the Dialog's "Show code" view, like so:

```json
  {
    "$kind": "Microsoft.TelemetryTrackEventAction",
    "$designer": {
    "id": "HT9fp1"
  }
```

**Comment by cwhitten** [comment]
Closing, but please do reach if you still experience issues.

**Comment by goergenj** [comment]
@cwhitten That was already done before the migration. Also as described it works after I remove the "**_disabled_**" after the migration. So this is not the root cause.

{
          "$kind": "Microsoft.TelemetryTrackEventAction",
          "$designer": {
            "id": "Vg6kAK",
            "name": "Create LogDialogStep"
          },
          "properties": {
            "LogDialogStep_Number": "00020",
            "LogDialogStep_Type": "WelcomeTrigger",
            "LogDialogStep_Current": "Welcome Dialog",
            "Botname": "=conversation.botName",
            "Botchannel": "=conversation.channel"
          },
          "eventName": "LogDialogStep"**_,
          "disabled": true_**
        },
