### ISSUE TITLE
[MCS-DE] Bot needs to be migrated after every open of the Composer

### ISSUE THREAD

**Issue by goergenj** [microsoft/BotFramework-Composer#7773]
Every time I open the Composer the Bot Migration wizard starts on already migrated Bots.

![image](https://user-images.githubusercontent.com/31212469/117989493-abffa680-b33c-11eb-9bef-86c63169b9a6.png)

@garypretty

**Comment by boydc2014** [comment]
Hi, @goergenj, are you opening up the new migrated bot or the previous old bot?  Migration isn't transforming the bot in place to avoid a permanent damage, so it's in a new location when you config the converting process.

**Comment by goergenj** [comment]
@boydc2014 The already migrated Bot.

Approach:

1. Open Composer
2. Open old Bot
3. Migrate old Bot and open new migrated copy
4. Fix appsettings which are lost in migration
5. Fix TelemetryTrackAction (see: https://github.com/microsoft/BotFramework-Composer/issues/7772)
6. Fix runtime settings (see: https://github.com/microsoft/BotFramework-Composer/issues/7769)
7. Run migrated Bot locally
8. Close Composer
9. Open Composer
10. Open new migrated copy of Bot
11. Composer opens the "Convert your project" wizard

**Comment by cwhitten** [comment]
Hello @goergenj - this is due to the workaround you are employing on #7769 here https://github.com/microsoft/BotFramework-Composer/issues/7769#issuecomment-839700469

This is working as expected so we will close this issue. We have asked for some of your bot assets to reproduce the issue on #7769

**Comment by goergenj** [comment]
@cwhitten I sent you a copy of the project in teams.
