### ISSUE TITLE
Number input, Expected responses editing is broken

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#7779]
## Describe the bug

The **Expected responses** field is now a single line property with no intuitive way [if any] to provide a multi-line .lu format value.

## Version

Version:  2.0.0-nightly.244572.8406071
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Add a **Prompt for a number** action
2. Go to the **User input** tab in the action's properties pane.
3. See error: **Expected responses** is now a one-line input field, with the watermark mangled and no way to use the Enter key to create a multi-line value.

## Expected behavior

This field should allow multi-line values (.lu format).

## Screenshots

![image](https://user-images.githubusercontent.com/35047199/118057453-e53a1580-b340-11eb-96bf-0f06df8c8fd7.png)

**Comment by boydc2014** [comment]
I can't repro this when using defaultRecognizer? But i can see this in regex recognizer. @JonathanFingold are you using default recognizer or the regex recognizer?

**Comment by boydc2014** [comment]
If this is regex, then it is expected by current design, because regex recognizer doesn't depends on lu file, so we purposely make it a one line input for the pattern, and we will serialize the pattern into .dialog file directly (instead of .lu file).  What we need to do is maybe update the placeholder to make it clear. The control itself looks right to me.

**Comment by boydc2014** [comment]
To shiproom: this is probably not a P0.

**Comment by sgellock** [comment]
Shiproom - moving out of R13

**Comment by JonathanFingold** [comment]
@boydc2014 , yes, I had set the dialog to use a RegEx recognizer.

1. Some context sensitive help text associated with this field would be helpful.
2. Replacing the placeholder/watermark text would also be helpful.

**Comment by cwhitten** [comment]
We can take a placeholder/copy update. I'd like @garypretty to weigh in on what that copy should say.

**Comment by OEvgeny** [comment]
I wasn't able to reproduce the issue
