### ISSUE TITLE
[UI bug] [Skills] Select all checkbox not visible in select dialog and trigger screen

### ISSUE THREAD

**Issue by vivekkshankar** [microsoft/BotFramework-Composer#7780]
![image](https://user-images.githubusercontent.com/67671676/118061923-c50f5400-b34a-11eb-9739-b3fc99543cc7.png)

**Expected UI:** 
- Replace circular checkbox with standard checkbox control
- Place select all checkbox in-line as shown in mock
- Select all by default

![image](https://user-images.githubusercontent.com/67671676/118062006-ea9c5d80-b34a-11eb-8f81-6b94127c333c.png)

**Comment by hibrenda** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/7665

**Comment by darrenj** [comment]
Why is Unknown Intent being include in the list? There was a debate about this and advertising things a skill **cannot** do doesn't make sense to put in a manifest as this will then indicate to a caller that these utterances **are** supported by a skill?

**Comment by sgellock** [comment]
Shiproom - lets sit on this and if there is a reason to crack the composer bits we can consider rolling this one in.

**Comment by sgellock** [comment]
Shiproom - since we are cracking composer bits today with other P0 issues, let's take this Fit and Finish issue.  Approved.
