### ISSUE TITLE
The "Learn More" teaching bubble for MS Teams obscures the "Open Manifest" link

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#7786]
## Describe the bug

Immediately after enabling MS Teams, a teaching bubble appears to highlight the need for further action.  However, this bubble obscures the manifest link that appears once enabled, making it easy to miss.

![Screen Shot 2021-05-13 at 11 14 54 AM](https://user-images.githubusercontent.com/729873/118154436-ab1e5180-b3dc-11eb-84d6-81c98a892173.png)

![Screen Shot 2021-05-13 at 11 15 09 AM](https://user-images.githubusercontent.com/729873/118154446-ad80ab80-b3dc-11eb-9e2e-2d4cb19d5687.png)

## Version

Release: 2.0.0-nightly.245007.8406071

**Comment by sgellock** [comment]
Shiproom - moving out of R13

**Comment by cwhitten** [comment]
@emivers8 would you be the right contact on what we should change this to? Options are limited and we would be constrained to what the popover component allows us to do as far as anchoring on an element.

**Comment by OEvgeny** [comment]
Doesn't happen anymore
