### ISSUE TITLE
MS Teams instructions do not mention manifest generator

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#7787]
## Describe the bug

The "Learn more" instructions for the MS Teams channel do not mention the ability to download a pre-build manifest and import it into App Studio.   We should call out this option, perhaps as a replacement to the current instructions that describe creating a new manifest by hand.

See here:
https://github.com/microsoft/BotFramework-Composer/blob/main/docs/preview%20features/ms-teams.md

**Comment by sgellock** [comment]
Shiproom - Gifts for you Dewain
