### ISSUE TITLE
Composer install should say what version of nodejs it requires

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#7791]
## Describe the bug

Installing Composer on a Mac without nodejs, it gives you a popup to install NodeJS but doesn't provide guidance it should be version 12 or 14.  

## Version

Version:  2.0.0-nightly.245007.8406071
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Install Composer on Mac 15 (Intel)
2. Click on "Create New"
3. See image below.

## Expected behavior

Should list expected versions (ie, nodejs 10/12/14)

## Screenshots

![image](https://user-images.githubusercontent.com/6182197/118165222-e74fb300-b3d8-11eb-9f07-5289f2162a67.png)

## Additional context

This check in general is a bit odd.  It happens when you click "Create New".  At that time, I haven't registered intent to use C# or NodeJS.  I'm assuming the nodejs it requires is in case it needs to generate a nodejs bot, and not for the Composer runtime itself - it's clearly running.

**Comment by sgellock** [comment]
Shiproom - you can run the tools on any shipping version of nodejs.
