### ISSUE TITLE
Mac requires Brew to install Azure Functions

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#7798]
## Describe the bug
Was under impression Composer could not rely on Brew for our customers.  One of our dependencies requires it, may rethink the restriction.

On Mac, if you create an Azure Function, you need to install a package.
![image](https://user-images.githubusercontent.com/6182197/118168374-a5287080-b3dc-11eb-886a-95b07b75db9b.png)

  > **NOTE**: It would be nice to specify **which version** of Azure Functions is required.
  
When you click on the link, it sends you [here](https://www.npmjs.com/package/azure-functions-core-tools).  
  > **NOTE**: Brew only listed method of installing Azure functions.
![image](https://user-images.githubusercontent.com/6182197/118168545-d0ab5b00-b3dc-11eb-9cef-67707f3769e2.png)

## Version

Version:  2.0.0-nightly.245007.8406071
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Install Composer
2. Create New Azure Function-based bot.

**Comment by sgellock** [comment]
shiproom - by design
