### ISSUE TITLE
[bugbash 5/13] What is the "Microsoft Application Registration" in the "Add resources" screen of the publishing profile?

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#7802]
## Describe the bug
Not sure what this is...
![image](https://user-images.githubusercontent.com/17152540/118171520-27666400-b3e0-11eb-82bf-dd6079f16aed.png)

It's not in the resulting resources in my resource group
![image](https://user-images.githubusercontent.com/17152540/118171587-406f1500-b3e0-11eb-855f-c5e553ac7d03.png)

## Version
Release: 2.0.0-nightly.245007.8406071

**Comment by dmvtech** [comment]
This is the Azure Active Directory application that gets created and that the Bot Channels Registration is dependent on. It's not exactly a 'resource' and won't be listed in a resource group, but here:
https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps
