### ISSUE TITLE
[Bugbash 5/13] Can't create/edit publishing profiles for skills

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#7804]
I opened a bot I created in a nightly version of composer a few days ago with publishing profiles already created for my two skill bots and when I go to edit them, I get this screen:

![image](https://user-images.githubusercontent.com/27976702/118172882-c049af00-b3e1-11eb-82b2-d433dbe1d9f0.png)

When I try to add a new publishing profile to the skill, I am unable to select a Publishing Target. 

This flow still works for the root bot, but not the skill bots

**Comment by benbrown** [comment]
![Screen Shot 2021-05-14 at 9 00 03 AM](https://user-images.githubusercontent.com/729873/118281411-cb104c80-b492-11eb-9c20-961cb38e8f0f.png)

This shows the blank publishing target

**Comment by benbrown** [comment]
The root cause of this is that the list of available publishing types is loaded per-project, and only loaded for the root project.

The fix is to load the publishing target types when the projectId of this component changes.

**Comment by sgellock** [comment]
Shiproom - approved.
