### ISSUE TITLE
bug: Double notifications render if you get a new notication when notification pane is open

### ISSUE THREAD

**Issue by pavolum** [microsoft/BotFramework-Composer#7805]
## Describe the bug

If you get a notificiation while the notification pane is open then you get redundant notifications

## Version
245007.8406071 (nightly used in 5/13 bug bash)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

Have noficication pane open and do any action that causes a notification to come in

## Expected behavior

If notification pane is open then new notifications should only render within the pane, not in the pane and as an alert calloout

## Screenshots

![image](https://user-images.githubusercontent.com/22845013/118173272-5b02b780-b3fb-11eb-9a42-d95e196a85a3.png)

**Comment by cwhitten** [comment]
@mewa1024 engineering needs UX expectations here before we address this

**Comment by mewa1024** [comment]
Can we follow the Azure portal notifications model?  You can see it in action here: [https://df.onecloud.azure-
test.net/#blade/SamplesExtension/SDKMenuBlade/hubsnotifications](url)


https://user-images.githubusercontent.com/39317542/121758377-f9a33680-cad5-11eb-8fb2-f3323cdb4ac6.mov



If the notifications pane is closed, show the new notification as a toast. If the pane is open, do not show any new notifications as toasts.

**Comment by mewa1024** [comment]
more detail here if needed: https://www.figma.com/file/DQ8xiC9VMfPX0nb0MBmOIs/Composer-audit-mewa?node-id=784%3A30224

**Comment by OEvgeny** [comment]
I can't repro, closing. Feel free to reopen
