### ISSUE TITLE
Mac C# Az Functions / EmptyBot  with Orchestrator fails to run locally

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#7806]
## Describe the bug

  > **NOTE**: Same bot works locally on Mac C# with **WebApp**.  Only occurs on **Az Functions** as runtime.

Running locally, the bot can't seem to load Orchestrator model, even though model path referenced exists.  This **same bot works using WebApp runtime.**

## Version

Version:  2.0.0-nightly.245007.8406071
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create Azure Function Empty Bot
2. Install Orchestrator package
3. Add trigger (ie, "pets"), add phrases (ie, "- dog, - cat").
4. Add response to trigger (ie, "You have pets!").
5. Run Bot locally

## Expected behavior

No error, just like Web App

## Screenshots

![image](https://user-images.githubusercontent.com/6182197/118178128-6ef0ee00-b3e8-11eb-9ae7-c3613ddf63bd.png)

**Comment by daveta** [comment]
Ben and Peter looking at this..

**Comment by sgellock** [comment]
Shiproom - Az Func has ephemeral storage.  we need to address this post build

**Comment by cwhitten** [comment]
@taicchoumsft assigning to you for tracking -- if this is tracked elsewhere feel free to link and close.

**Comment by taicchoumsft** [comment]
Tracked in #8064 and #8065, closing this one.
