### ISSUE TITLE
Exporting node WA as skills throws deploy error

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7809]
## Describe the bug
Exporting node web apps as skills has a zip deploy error for invalid hostname

## Version
Version:  2.0.0-nightly.245007.8406071
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an node empty bot web app bot
2. Create a provisioning profile for the bot
3. While the provisioning is going on add an echo trigger and dialog
4. After the provision finishes publish the bot
5. once the bot is published export the bot as a skill
6. only select the echo trigger and dialog

## Expected behavior
This should work

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/118182941-67ccde80-b3ee-11eb-986e-e2e1918256c1.png)

![image](https://user-images.githubusercontent.com/50158775/118182974-6ef3ec80-b3ee-11eb-8c05-ad8e5d2dc88f.png)

## Additional context
There's other issues with deploying node bots, but this is the only one where the zip deploy error is thrown.

I should add I was able to repo this with a fresh bot to rule out Composer being in some weird state. Here's the log from Composer:

---
"Accepted for publishing..."
---

---
"Abs settings incomplete, skip linking bot with webapp ..."
---

---
"appPasswordHint incomplete, return ..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"Assigning to luis app id: c3937102-19a2-42e9-b7ba-c9f9e6ca1539"
---

---
"Luis Publish Success! ..."
---

---
"Creating build artifact..."
---

---
"Build artifact ready!"
---

---
"Publishing to Azure ..."
---

---
"Uploading zip file... to NWAEcho513z"
---

---
"{\"name\":\"DEPLOY_ZIP_ERROR\",\"message\":\"The hostname is invalid, please check if hostname/name-environment matches your target resource(webapp/function) name\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:255547:25)\\n    at createCustomizeError2 (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:255552:10)\\n    at BotProjectDeploy.deployZip (C:\\\\Users\\\\joratlif\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:256037:15)\"}"
---

---
"DEPLOY_ZIP_ERROR - The hostname is invalid, please check if hostname/name-environment matches your target resource(webapp/function) name"
---

**Comment by sgellock** [comment]
Shiproom - zip deploy is notorious for presenting this error.  a retry tends to fix it.

**Comment by Virtual-Josh** [comment]
I repo'd this 3 times in a row with 2 different bots

**Comment by Virtual-Josh** [comment]
Same issue happens for node function bots

**Comment by sgellock** [comment]
Shiproom - if we crash composer bits, we'll consider taking an error message update for this, and possibly more.

**Comment by sgellock** [comment]
Shiproom - for R13, we're going to make a fix that bubbles up the correct error.  Then we have some more resilient code changes we can do post R13.  Goeff will have a PR for the error handling coming today.

**Comment by sgellock** [comment]
Shiproom - we should do this in the very next release
