### ISSUE TITLE
[telemetry] Missing data collection settings on server prevents telemetry from being logged to App Insights

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-Composer#7813]
## Describe the bug
In some instances of Composer, the user's data collection settings are missing in the data.json. As a result, even when the user has telemetry enabled, the server does not log those events to App Insights. This issue is causing data loss and gaps in our data collection.

## Version
Latest nightly

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## Expected behavior
Composer should update the server's user settings when each new session begins so that the server has the most current setting.

**Comment by sgellock** [comment]
Shiproom - let's do a private build for @garypretty to verify this Pr doesn't regress any other core telemetry

**Comment by sgellock** [comment]
Shiproom - private bits have been verified.  approved.
