### ISSUE TITLE
In a RegEx Trigger the text for the expression is inconsistent in creation and editing flows

### ISSUE THREAD

**Issue by gremlin529** [microsoft/BotFramework-Composer#7816]
## Describe the bug

When you create a new RegEx Trigger the dialog that comes up says "Please input regEx pattern" once it's created the UX says "Trigger phrases" for the same value, these should be consistent (preferably both containing RegEx) 

## Version

2.0.0-nightly.245007.8406071

## Browser

Stand alone windows app

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to initial dialog
2. make it a regex bot
3. Click on Add new trigger
4. Add the new trigger, observe dialog text during creation
5. Now look at created page for trigger and observer

## Expected behavior

consistency and clarity in naming

## Screenshots

![CreateATrigger](https://user-images.githubusercontent.com/56889386/118188823-d7929780-b3f5-11eb-97bf-29eb97bdda26.png)
![EditATrigger](https://user-images.githubusercontent.com/56889386/118188835-db261e80-b3f5-11eb-868c-9f73e18f4f5d.png)

**Comment by srinaath** [comment]
We have a PR open to fix this ticket @gremlin529 . Thanks.
