### ISSUE TITLE
The AskForUserInput doc missing instructions on "value" and "expected responses" field.

### ISSUE THREAD

**Issue by xiyangdesign** [microsoft/BotFramework-Composer#7822]
## Describe the bug
The [Ask for user input doc](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input#text-input) aims to help users achieve the goal highlighted below. However, without instructions on setting "value" and "expected responses" fields, it could be challenging to achieve this goal.
<img width="774" alt="image" src="https://user-images.githubusercontent.com/74994573/118200714-a53f6500-b40a-11eb-9cf8-4266c667ff9f.png">

For example.

- **bot**: what's your name?
- **user**: my name is Zoidberg
- **bot**: hello Zoidberg 

## Expected behavior
Add instructions such as below:

in value field: '=@username'
in expected responses field: 
-My name is {@username=Zoidberg}

@mareekuh  FYI

**Comment by sgellock** [comment]
Shiproom - docs issue for R13.

**Comment by emgrol** [comment]
Putting this on hold while I strategize with @JonathanFingold and @erhopf about the best way to present this information.

**Comment by JonathanFingold** [comment]
The article has been edited. @xiyangdesign - does the current organization in the [create a text input action](https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input?tabs=v2x#create-a-text-input-action) section address your original concern?

**Comment by xiyangdesign** [comment]
Yeah. This new article works. Thanks for updating @JonathanFingold !
