### ISSUE TITLE
How to get the list of entities returned from LUIS?

### ISSUE THREAD

**Issue by dinhlan300** [microsoft/BotFramework-Composer#7825]
When I enter a synonym of an entity in Bot Framework Composer. It will return an array of Entities like this
![image](https://user-images.githubusercontent.com/13560859/118218121-00239b80-b4a1-11eb-9c1e-5eff2a8a28cf.png)

How can I extract the list of entities and turn it into a question with options? I want to make sure Bot will confirm with the customer when LUIS not sure what species of product they are asking for.

I'm working on Bot Framework Composer v1.4.0.

**Comment by sgellock** [comment]
Shiproom - moving this out of R13

**Comment by lauren-mills** [comment]
Hi @dinhlan300, you should be able to get all the instances of a recognized entity from your LUIS result using this syntax "=@@entityName". This returns an array object if there is more than one value for a given entity.

You can also access the full recognition result at the default "turn.recognized" scope.

**Comment by dinhlan300** [comment]
@lauren-mills Thank you so much. It's worked
I appreciate it.
