### ISSUE TITLE
error pop up for duplicated skill

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#7827]
## Describe the bug

Add duplicated skill will pop up following :
![image](https://user-images.githubusercontent.com/43408889/118228828-6dddc080-b4bd-11eb-98a1-3aae13a82aa0.png)

We'd better pop up other info. @vivekkshankar . This looks like a composer bug instead of error notification to user.

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

**Comment by sgellock** [comment]
Shiproom - @hibrenda can you please connect with @cwhitten and review the labeling expectations for incoming bugs?  If issues are not labeled correctly they run the risk of being lost during the final review leading up to the release.

**Comment by sgellock** [comment]
Shiproom - moving out of R13

**Comment by vivekkshankar** [comment]
@luhan2017 We chould preempt this error and show message in the manifest URL field.
If the user adds the same manifest URL show an inline message "This skill has already been added".
Do we have this issue for local skills too?

**Comment by luhan2017** [comment]
@vivekkshankar , Yes, here is the error message for local bot. 
![image](https://user-images.githubusercontent.com/32191031/119759590-1850dd00-bedb-11eb-9906-a85eb0dde68f.png)

**Comment by luhan2017** [comment]
@vivekkshankar, could you help design on the local add skill experience for duplicated skill? what should the pop up error message looks like?
