### ISSUE TITLE
Delete properties properties list should not require user to press the Enter key

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#7840]
## Describe the bug

Can enter a property to delete, but it doesn't take unless you also press Enter.

## Version

Version:  2.0.0-nightly.245345.48d2167
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Add a **Delete properties** action to a dialog.
2. Edit the action's properties.
3. Error: notice that the property doesn't take unless you press Enter.
    - In most other actions, pressing Enter is not required. You only have to add text and then click outside the input box.
    - Even with this action. Once an input box is recognized as having a value, you can change that value and have it stick without having to press Enter first.

## Expected behavior

The semantics of user input boxes is as consistent as possible throughout the product.

## Additional context

- The vertical ellipsis has hover text for the empty input box, but not for an input box that already has a value.

  ![image](https://user-images.githubusercontent.com/35047199/118335858-615d6600-b4c5-11eb-96e4-019369b21a4b.png)

**Comment by tdurnford** [comment]
PR #https://github.com/microsoft/BotFramework-Composer/pull/6633 resolves this issue and will be included in the R14 release.
