### ISSUE TITLE
Composer Helper eats up CPU on Mac

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#7844]
## Describe the bug
The Composer spins up some renderer which eats up a lot of CPU.  Even when composer isn't actively up.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/6182197/118399824-d5a61f80-b613-11eb-9334-36b748337511.png">

## Version

Version:  2.0.0-nightly.245007.8406071
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Run Composer
2. Kill Composer
3. Look at Activity Monitor
## Expected behavior

Not eat up so much CPU

**Comment by sgellock** [comment]
Shiproom - we're not seeing this.  @daveta any more repro steps you can share?

**Comment by daveta** [comment]
Working in clearer script..

**Comment by sgellock** [comment]
Shiproom - closing until we can get a repro
