### ISSUE TITLE
Luis not working

### ISSUE THREAD

**Issue by vboluarte** [microsoft/BotFramework-Composer#7845]
I have a bot with three dialogs. When i test it on the composer it works fine, buut once published the bot stops recognizing sub dialogs triggers, just main triggers. Why is this happening?

**Comment by v-kydela** [comment]
Thank you for the report, @vboluarte 

It sounds like you're saying you have some LUIS intent triggers in multiple dialogs but the intents are only getting triggered in the main dialog even when it's not the active dialog. Is that correct?

Please provide the following:

1. A minimal code example
2. Repro steps
3. Screenshots

**Comment by vboluarte** [comment]
Yes, that is what im saying. The bot works fine in the emulator, the child dialogs triggers as expected; But once published in Azure it stops triggering. Im working in the Bot framework composer. 

1.- What kind of code do you need?
{
  "$kind": "Microsoft.AdaptiveDialog",
  "$designer": {
    "id": "BiAK8i",
    "name": "recordar_contra_dialogo",
    "description": ""
  },
  "autoEndDialog": true,
  "defaultResultProperty": "dialog.result",
  "triggers": [
    {
      "$kind": "Microsoft.OnBeginDialog",
      "$designer": {
        "name": "BeginDialog",
        "description": "",
        "id": "oZf7vu"
      },
      "actions": [
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "85aHeu"
          },
          "activity": "${SendActivity_85aHeu()}"
        },
        {
          "$kind": "Microsoft.ConfirmInput",
          "$designer": {
            "id": "OpqZtu"
          },
          "defaultLocale": "es-es",
          "disabled": false,
          "maxTurnCount": 2,
          "alwaysPrompt": true,
          "allowInterruptions": true,
          "unrecognizedPrompt": "",
          "prompt": "${ConfirmInput_Prompt_OpqZtu()}",
          "choiceOptions": {
            "includeNumbers": true,
            "inlineOrMore": ", or ",
            "inlineOr": " or ",
            "inlineSeparator": ", "
          },
          "property": "user.confirmation",
          "confirmChoices": [
            "si",
            "no"
          ],
          "defaultValue": false
        },
        {
          "$kind": "Microsoft.IfCondition",
          "$designer": {
            "id": "htegQL"
          },
          "condition": "equals(user.confirmation,true)",
          "elseActions": [
            {
              "$kind": "Microsoft.SendActivity",
              "$designer": {
                "id": "A747qb"
              },
              "activity": "${SendActivity_A747qb()}"
            },
            {
              "$kind": "Microsoft.SendActivity",
              "$designer": {
                "id": "CTDHct"
              },
              "activity": "${SendActivity_CTDHct()}"
            },
            {
              "$kind": "Microsoft.EndDialog",
              "$designer": {
                "id": "XRT3v1"
              }
            }
          ]
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "2fW2lD"
          },
          "activity": "${SendActivity_2fW2lD()}"
        },
        {
          "$kind": "Microsoft.TextInput",
          "$designer": {
            "id": "KqLbYs"
          },
          "disabled": false,
          "maxTurnCount": 3,
          "prompt": "${TextInput_Prompt_KqLbYs()}",
          "property": "user.correo",
          "invalidPrompt": "${TextInput_InvalidPrompt_KqLbYs()}",
          "validations": [
            "or(and(contains(this.value,'@'), contains(this.value,\".com\")), contains(this.value,\"cancelar\"))"
          ],
          "defaultValueResponse": "${TextInput_DefaultValueResponse_KqLbYs()}",
          "defaultValue": "invalido",
          "allowInterruptions": true,
          "alwaysPrompt": true
        },
        {
          "$kind": "Microsoft.SwitchCondition",
          "$designer": {
            "id": "6FrI4m"
          },
          "condition": "user.correo",
          "cases": [
            {
              "value": "invalido",
              "actions": [
                {
                  "$kind": "Microsoft.SendActivity",
                  "$designer": {
                    "id": "DycOpl"
                  },
                  "activity": "${SendActivity_DycOpl()}"
                },
                {
                  "$kind": "Microsoft.SendActivity",
                  "$designer": {
                    "id": "K66aNr"
                  },
                  "activity": "${SendActivity_K66aNr()}"
                },
                {
                  "$kind": "Microsoft.EndDialog",
                  "$designer": {
                    "id": "PDnnP8"
                  }
                }
              ]
            }
          ]
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "TbL3fx"
          },
          "activity": "${SendActivity_TbL3fx()}"
        },
        {
          "$kind": "Microsoft.TextInput",
          "$designer": {
            "id": "ZZW8T6"
          },
          "disabled": false,
          "maxTurnCount": 3,
          "alwaysPrompt": true,
          "allowInterruptions": true,
          "prompt": "${TextInput_Prompt_ZZW8T6()}",
          "property": "user.dni",
          "defaultValue": "invalido",
          "validations": [
            "length(this.value)==9",
            "isInteger(substring(this.value,0,7))",
            "isString(substring(this.value,7,1))"
          ],
          "invalidPrompt": "${TextInput_InvalidPrompt_ZZW8T6()}"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "K13onl"
          },
          "activity": "${SendActivity_K13onl()}"
        },
        {
          "$kind": "Microsoft.IfCondition",
          "$designer": {
            "id": "oB5tur"
          },
          "condition": "=equals(user.dni,'invalido')",
          "actions": [
            {
              "$kind": "Microsoft.SendActivity",
              "$designer": {
                "id": "daWSzU"
              },
              "activity": "${SendActivity_daWSzU()}"
            },
            {
              "$kind": "Microsoft.DeleteProperties",
              "$designer": {
                "id": "NHZFEV"
              },
              "properties": [
                "user.dni",
                "user.correo",
                "user.confirmation"
              ]
            },
            {
              "$kind": "Microsoft.EndDialog",
              "$designer": {
                "id": "krVQvN"
              }
            }
          ]
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "a61b4y"
          },
          "activity": "${SendActivity_a61b4y()}"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "ySrkiw"
          },
          "activity": "${SendActivity_ySrkiw()}"
        },
        {
          "$kind": "Microsoft.DeleteProperties",
          "$designer": {
            "id": "q0qnku"
          },
          "properties": [
            "user.correo",
            "user.confirmation",
            "user.dni"
          ]
        }
      ],
      "priority": 1
    },
    {
      "$kind": "Microsoft.OnIntent",
      "$designer": {
        "id": "eLfNlq",
        "name": "cancelarContra"
      },
      "intent": "cancelarContra",
      "actions": [
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "l6gnWa"
          },
          "activity": "${SendActivity_l6gnWa()}"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "ceUtaI"
          },
          "activity": "${SendActivity_ceUtaI()}"
        },
        {
          "$kind": "Microsoft.EndDialog",
          "$designer": {
            "id": "Sw1qUz"
          }
        }
      ],
      "condition": "=#cancelarContra.score>=0.6",
      "priority": 7
    },
    {
      "$kind": "Microsoft.OnIntent",
      "$designer": {
        "id": "rst1wl",
        "name": "prueba"
      },
      "intent": "prueba",
      "actions": [
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "B71489"
          },
          "activity": "${SendActivity_B71489()}"
        }
      ],
      "condition": "=#prueba.score>=0.6",
      "priority": 9
    }
  ],
  "generator": "recordar_contra_dialogo.lg",
  "recognizer": "recordar_contra_dialogo.lu.qna",
  "id": "recordar_contra_dialogo"
}
that is the json for the child dialog.

2.- Repro steps:
     -Create a new composer project
     -Add some triggers to the main dialog
     -Add a child dialog and add some triggers.
     -Publish it into azure
     -try the bot in Azure.

3.- Some captures

![Screen Shot 05-18-21 at 09 24 AM](https://user-images.githubusercontent.com/81149767/118609486-168c6880-b7bb-11eb-97cd-25da65eadfa9.PNG)


The child dialog is "recuperar_contra_dialogo"

Maybe it is related to the Luis names

![Screen Shot 05-18-21 at 09 25 AM](https://user-images.githubusercontent.com/81149767/118609513-1d1ae000-b7bb-11eb-9bfe-05678ef8e75f.PNG)

**Comment by vboluarte** [comment]
Hello, i have solved the problem. Child dialog LUIS was published in Staging Slot, but it has to be on production slot in order to work once the bot is published
![Screen Shot 05-19-21 at 10 36 AM](https://user-images.githubusercontent.com/81149767/118782184-232dc100-b88e-11eb-8726-e484486a5e2b.PNG)
