### ISSUE TITLE
turn.repeatedIds should not be a default adaptive expression element

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#7846]
## Describe the bug

The `turn.repeatedIds` property is not intended to be used by developers.

## Version

Version:  2.0.0-nightly.245812.dc07be4
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to any property that can take an adaptive expression.
2. Edit the expression and use the **insert property reference** widget.
3. Expand the `turn` scope.
4. See error: `turn.repeatedIds` is displayed as an option.
    - I have no idea when getting or setting this property would ever be relevant.

## Expected behavior

Don't expose properties that we don't want users to use.

## Screenshots

![image](https://user-images.githubusercontent.com/35047199/118534239-dadf9900-b6fd-11eb-9b9e-4f49ac344b2c.png)

## Additional context

We should not expose UI where the description in the docs will need to be "for internal use only."

**Comment by mewa1024** [comment]
(Removing the "UX Design" label -- not a design team call whether this property is relevant. If it is not relevant, seems fine to remove it.)
