### ISSUE TITLE
Publish with LUIS get Error when running in Azure

### ISSUE THREAD

**Issue by CopenhagenJames** [microsoft/BotFramework-Composer#7849]
When you publish a new Bot with LUIS enabled you get a 

Response status code does not indicate success: 404 (Not Found).

## Describe the bug

Basic WeatherBot with LUIS published and error above is generated.

It works fine in Composer but not when deployed.

## Version

Version 1.4.1

## Browser

Currently using Edge

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Publish completed WeatherBot demo
2. Run in Azure Bot service Test
3. Error is displayed

**Comment by ninggao** [comment]
@stevkan do you think this one is related to https://github.com/microsoft/BotFramework-Composer/issues/7702 ?

**Comment by stevkan** [comment]
@CopenhagenJames, can you list which version of Composer it is that you are using? If you look deeper into any generated logs or Application Insights, do you see any expanded details regarding the error that can be shared?

**Comment by CopenhagenJames** [comment]
I'm using 1.4.1. I'll have to look at the logs.

Sincerely,



James Lawrence

Senior Cloud Solutions Architect



________________________________

**Comment by CopenhagenJames** [comment]
So, I just downloaded the update version 2.0 and the error is now gone.

So what ever changed seems to have been a fixe for my issue.

Thank You,


James D. Lawrence
PMP(r) Senior Cloud Solutions Architect | Azure Platform Evangelist
520 686-4303 (m)
MBA | MS Computer Science | MS Cyber Security | MCSD | MCAD
Email: ***@***.******@***.***>


[A picture containing diagram  Description automatically generated]<https://www.youracclaim.com/badges/60909be4-283c-44a2-a5ea-dfec024b71a5/public_url> [Diagram  Description automatically generated with medium confidence] <https://www.youracclaim.com/badges/bbc871a3-66b8-486b-9449-d4239405fcb0/public_url>   [Application  Description automatically generated] <https://www.youracclaim.com/badges/32b833f0-7a48-4abd-bd86-855e39d7ba5e/public_url>   [story-impact-learning-to-connect-and-compel] <https://www.youracclaim.com/badges/321aa97e-f50c-4053-8352-d46b1d705f96/public_url>   [Icon  Description automatically generated] <https://www.youracclaim.com/badges/0d3e0fba-4974-4126-8c41-4071c013eab8/public_url>
[microsoft-certified-azure-fundamentals (1)]<https://www.youracclaim.com/badges/737b36e0-eed3-47d7-8f7e-540849f81000/public_url>  [A picture containing diagram  Description automatically generated] <https://www.youracclaim.com/badges/c333efd2-47a7-4e74-93d1-f6d76aa31641/public_url>   [Text, icon  Description automatically generated] <https://www.youracclaim.com/badges/8ebc416e-ed18-49ba-8750-a0f743e5b93a/linked_in_profile>   [microsoft-certified-azure-administrator-associate] <https://www.youracclaim.com/badges/516a1404-f296-4428-b40b-81727a60eb6f/linked_in_profile>   [Diagram  Description automatically generated] <https://www.youracclaim.com/badges/6574aeb3-bc97-4650-96d0-db279d2ea51f/public_url>   [microsoft-certified-azure-developer-associate] <https://www.youracclaim.com/badges/0f817590-ba82-4389-a558-ba0b29efe488/linked_in_profile>   [Text  Description automatically generated] <https://www.youracclaim.com/badges/28633103-910c-47f1-b720-9eb1e367f1ea/public_url>   [microsoft-certified-azure-devops-engineer-expert] <https://www.youracclaim.com/badges/ba63ab91-ad0f-4b0f-9cd1-967ba4f0a6d1/public_url>
[A picture containing text, sign  Description automatically generated] [A picture containing application  Description automatically generated] <https://www.youracclaim.com/badges/e939c13b-b3e0-4fd7-a977-33be63114559/public_url>

  [Graphical user interface, application  Description automatically generated]   [Graphical user interface, application  Description automatically generated]   [comptia-security-ce-certification] <https://www.youracclaim.com/badges/c6ddbca1-8aab-4ff2-8932-c205ff64e78d/public_url>

**Comment by stevkan** [comment]
I'm glad to hear that. Closing this issue as resolved.

**Comment by CopenhagenJames** [comment]
Cool

Sincerely,



James Lawrence

Senior Cloud Solutions Architect



________________________________
