### ISSUE TITLE
Export as skill is missing a learn more link

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#7851]
## Describe the bug

The learn more link is missing from the allowed callers page of the "Export as skill" modal. See below:

![Screen Shot 2021-05-17 at 3 55 55 PM](https://user-images.githubusercontent.com/729873/118555686-8dc4ec80-b728-11eb-96ce-5386228b2d85.png)

## Version

2.0.0-test

**Comment by alanlong9278** [comment]
@vivekkshankar  Could u pls give me the link of `Learn more`, thanks

**Comment by vivekkshankar** [comment]
I dont think we have a separate doc covering "which bots can access this skill".
Until we do we can link to the the doc here https://docs.microsoft.com/en-us/composer/how-to-publish-skill?tabs=v2x
Step 5 talks about this.

**Comment by alanlong9278** [comment]
> I dont think we have a separate doc covering "which bots can access this skill".
> Until we do we can link to the the doc here https://docs.microsoft.com/en-us/composer/how-to-publish-skill?tabs=v2x
> Step 5 talks about this.

Use the same link to `select trigger`, `select dialog` & `allow callers` pages
