### ISSUE TITLE
Add skill via manifest fails to load remote LU

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#7852]
## Describe the bug

While connecting to a remote skill, the step that is supposed to import the remote LU files fails an error that says "get remote file fail" and requires me to put in my own LU for the skill trigger

![Screen Shot 2021-05-17 at 3 45 00 PM](https://user-images.githubusercontent.com/729873/118555797-b6e57d00-b728-11eb-9ef4-4c25fd7d266b.png)

## Version

2.0.0-test

**Comment by luhan2017** [comment]
@benbrown, could you check if the url in the skill manifest is accessible or not? This could probably because the runtime does not exposed the .lu file in the api?

**Comment by benbrown** [comment]
The manifest was available, and the LU files that were linked were also available via HTTP.

**Comment by benbrown** [comment]
This occurs with a standard skill published from Composer using the "Export as skill" option

**Comment by luhan2017** [comment]
@benbrown Could you help check if this still could be reproduced? I tested several times on my side, they were all working well.  Any thing special in your mind to reproduce this issue?

**Comment by VanyLaw** [comment]
Can not reproduced too, can test it after this PR #8146
