### ISSUE TITLE
Composer doesn't add the skillendpoint to appsettings if you don't start the bot

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7856]
## Describe the bug
Composer doesn't add the `skillHostEndpoint` to app settings until you start the bot.

This might be a P1 since it's critical, but not its importance is less clear. 

## Version
Version:  2.0.0-nightly.246099.8fa93
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a skill bot, provision, and make a manifest
2. Create an dotnet wa parent bot, and provision
3. Add the skill as a remote skill
4. Publish the bot

Note: Do not start the bot before publishing

## Expected behavior
This should work, however 

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/118712876-28c7d000-b7d6-11eb-8e71-f40cabb4f77a.png)

## Additional context
If you start the bot locally the runtime will fill in the `skillHostEndpoint` property and everything works as expected. The odds are low that customers hit this, but it's very opaque if someone does.

**Comment by Virtual-Josh** [comment]
I haven't checked all the other combinations, but it seems reasonable this issue exists for all other bot types.

**Comment by sgellock** [comment]
Shiproom - moved out of R13
