### ISSUE TITLE
Scripts/compileExtensions.js:84 syntax error

### ISSUE THREAD

**Issue by zachgoz** [microsoft/BotFramework-Composer#7859]
## Describe the bug

The ? in packageJSON?.main seems to be causing an issue:
<img width="633" alt="Screen Shot 2021-05-18 at 10 49 58 AM" src="https://user-images.githubusercontent.com/3943365/118725345-d69aa500-b7fd-11eb-9f38-cf603acd22b4.png">

## Version
2.0.0-test
Node v12.20.0
<img width="613" alt="Screen Shot 2021-05-18 at 5 30 54 PM" src="https://user-images.githubusercontent.com/3943365/118726151-e961a980-b7fe-11eb-89d3-0c04d0a42a89.png">

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. git clone https://github.com/microsoft/BotFramework-Composer.git
2. cd BotFramework-Composer
3. yarn install 
4. yarn build

## Expected behavior

Install composer successfully

## Screenshots

<img width="633" alt="Screen Shot 2021-05-18 at 10 49 58 AM" src="https://user-images.githubusercontent.com/3943365/118726360-3180cc00-b7ff-11eb-8f8e-d38747c7f3bb.png">
<img width="617" alt="Screen Shot 2021-05-18 at 11 11 25 AM" src="https://user-images.githubusercontent.com/3943365/118726408-46f5f600-b7ff-11eb-9f1a-bd3f9946c989.png">

## Additional context

When I remove the **?** install works fine. I also have to update the "mongodb-client-encryption" to ^1.2.0 for the install to work. Otherwise I see the following error when running yarn install and yarn build : 
<img width="617" alt="Screen Shot 2021-05-18 at 11 11 25 AM" src="https://user-images.githubusercontent.com/3943365/118726645-9b997100-b7ff-11eb-8de7-0d1e3483cce3.png">

**Comment by srinaath** [comment]
@zachgoz This seems to be an issue with building with Node 12 version. Could you try with the Node LTS version and see if this issue reproes there?

**Comment by zachgoz** [comment]
@srinaath Thanks, using node 14.17.0 sorts out the compileExtensions issue. However I still see the mongoStorage install issue unless I remove the yarn lockfile and update to "mongodb-client-encryption": "^1.2.0". 

<img width="675" alt="Screen Shot 2021-05-19 at 10 30 05 AM" src="https://user-images.githubusercontent.com/3943365/118833209-46a53b80-b88f-11eb-9cb7-7871b9b2bc79.png"> 

<img width="1360" alt="Screen Shot 2021-05-19 at 10 29 18 AM" src="https://user-images.githubusercontent.com/3943365/118833190-43aa4b00-b88f-11eb-9f46-3861b75e502c.png">

**Comment by ninggao** [comment]
Hi @benbrown Could you please take a look at this issue?

**Comment by benbrown** [comment]
@zachgoz thanks for the report. I will look into updating the dependencies in that sample extension to resolve this.

I am not able to reproduce this error -- does this occurs during the main `yarn build` process or are you reproducing the error by building the mongoStorage extension directly?

**Comment by zachgoz** [comment]
@benbrown yes this occurs when running the main yarn build process after cloning the repo or downloading release source.

**Comment by benbrown** [comment]
@zachgoz thanks for confirming.  Do you happen to have a very old set of xcode tools by any chance? It appears like some part of the mongo crypt package is failing to compile.

**Comment by zachgoz** [comment]
<img width="635" alt="Screen Shot 2021-05-21 at 5 25 27 PM" src="https://user-images.githubusercontent.com/3943365/119199778-acddba00-ba59-11eb-8579-13d385d01a33.png">

I am not running the latest version, I can try updating this.

**Comment by zachgoz** [comment]
I upgraded xcode tools but still see the same issue:

<img width="625" alt="Screen Shot 2021-05-24 at 3 27 42 PM" src="https://user-images.githubusercontent.com/3943365/119397786-a1ca9a00-bca4-11eb-9e12-4c601c87fa8c.png">

<img width="1318" alt="Screen Shot 2021-05-24 at 3 26 35 PM" src="https://user-images.githubusercontent.com/3943365/119397663-7647af80-bca4-11eb-96a8-681d719a86ac.png">

**Comment by hatpick** [comment]
@zachgoz before you do ```yarn``` and ```yarn build``` (since you recently switched to later version of node) make sure you remove all the node_modules from extensions. For example delete ```node_modules``` under ```BotFramework-Composer/extensions/mongoStorage``` path

**Comment by chrimc62** [comment]
Closed due to inactivity.  If you still have an issue, please reopen.
