### ISSUE TITLE
Update to 1.4.1 Publishing on wrong tenant

### ISSUE THREAD

**Issue by ctharmon722** [microsoft/BotFramework-Composer#7860]
Since updating to 1.4.1 (although I haven't published anything new with 1.4), I go to publish a new profile and I get the following error...

## To Reproduce

1. In composer, project setting, click "Add new publish profile"
2. Entered a name and selected the publish target of "Publish bot to Azure Web App (Preview)"
3. Configure resources: select Create new Azure resources
4. Selected my subscription, Hostname and location (WestUS)
5. Review & Create, accepted defaults except removed Cosmos DB and QnAMaker
6. Azure fails provisioning

## Result

Provision failure
CREATE_RESOURCES_ERROR - Error - The subscription 'XXXXXXXXXXXXXXXXXXXXX' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled. detail message can see provision.ConvoBot.log in your bot folder

The subscription listed is an old subscription that has been canceled. There is an active subscription and when I created some bots in Version 1.3 I was able to publish them no problem

I can not find anywhere that I put in a subscription number or why it would be calling that one.

**Comment by ctharmon722** [comment]
@cwhitten last time you knew instantly what was wrong when I updated to version 1.4 and was having a runtime error. Wondering if you had any idea why with the update to 1.4 (maybe only 1.4.1) it defaults to a random tenant/subscription. In this case it was a subscription that has been canceled? 

To add a little more information, I rolled back to 1.3, and could publish just fine.

**Comment by ninggao** [comment]
@dmvtech Could you please take a look at this issue?

**Comment by dmvtech** [comment]
Hi @ctharmon722 

> I can not find anywhere that I put in a subscription number or why it would be calling that one.

Can you please go to the bot settings, then switch to `Advanced Settings View (json)` and look for the section titled `publishTargets`. In there, find the target you are using and look for the `configuration`. Does the information there look correct? Does it show the old/defunct `subscriptionId`? If so, can you update to the active subscription and try? Might want to check the other settings as well.

**Comment by ctharmon722** [comment]
@dmvtech because the provision fails the publishTargets is empty. There is nowhere to put in the subscription to change this. Where can I put this subscription in so it tries to write to the correct place?

I have also tried following everything on this page
ttps://docs.microsoft.com/en-us/composer/how-to-publish-bot?tabs=v1x
(which is not actually the correct step by step)
I have also tried to use the manual instructions from this page https://docs.microsoft.com/en-us/composer/how-to-publish-bot?tabs=v1x
and I get the following error
"Error - Failed to bind luis prediction resource to luis applications. Please check if your luisResource is set to luis prediction service name in your publish profile."
Even though everything is hooked up correctly.

**Comment by dmvtech** [comment]
Hi @ctharmon722 It would typically looks _something like_ the following, where `configuration` contains the stringified json of the publishing profile:
```
  "publishTargets": [
    {
      "configuration": "{\n  \"name\": \"REDACTED\",\n  \"environment\": \"composer\",\n  \"subscriptionId\": \"REDACTED\",\n 
      \"resourceGroup\": \"REDACTED\",\n  \"botName\": \"REDACTED\",\n  \"hostname\": \"REDACTED\",\n  
      \"runtimeIdentifier\": \"win-x64\",\n  \"region\": \"REDACTED\",\n  \"settings\": {\n    \"applicationInsights\": {},\n    
      \"luis\": {},\n    \"qna\": {},\n    \"MicrosoftAppId\": \"REDACTED\",\n    \"MicrosoftAppPassword\": \"REDACTED\"\n  }\n}",
      "name": "REDACTED",
      "type": "azurePublish",
      "lastPublished": "2021-03-03T04:37:42.776Z"
    }
```

But if publish targets is empty, then that old/stale subscription ID hast to be coming from somewhere else. You can try to look at the local storage (_Developer Tools->Application_) and see if that is stored somewhere there. Optionally, you can clear out **all** local storage, in which you may have to re-set properties on some bots after doing so.

> and I get the following error
"Error - Failed to bind luis prediction resource to luis applications. Please check if your luisResource is set to luis prediction service name in your publish profile."
Even though everything is hooked up correctly.

Do you have two separate LUIS authoring and prediction resources? Or are you using a combination resource?

**Comment by ctharmon722** [comment]
@dmvtech 
I do understand what the publishTargets should look like because it has worked with other bots before the switch over to 1.4.0. However, this one does not have any of the configurations in there right now because the publishTarget is blank. It is blank because it is always pulling from the old subscription. 

I am willing to clear out my local storage, but where do I find it? Where are (Developer Tools->Application)? I don't see them anywhere in composer.

I have two separate LUIS resources. One for authoring, and one for prediction.

**Comment by dmvtech** [comment]
> I am willing to clear out my local storage, but where do I find it? Where are (Developer Tools->Application)? I don't see them anywhere in composer.

The keyboard shortcut `Ctrl+shift+i`. I'm assuming you're using the Electron version (downloadable, installable program) of Composer and that you haven't cloned the repo and built it yourself. But the keyboard shortcut should work either way. In the Electron version you can also find the developer tools under the `View` menu.

I'm very interested to see if clearing the local storage resolves this. Thanks for trying.

**Comment by ctharmon722** [comment]
@dmvtech 
I cleared out the local and then all storage. It still defaults to the disabled account. Any other place this subscription/tenant might live in memory? You are correct, I use the downloadable/installable program?

I would switch to 2.0, but we use custom actions...

**Comment by dmvtech** [comment]
Do you actually see the old/false tenant id in the local storage? should be listed as `composer:tenantId`. If so, are you able to edit it to the correct one? Can you also check the Session Storage as well please? Can you also run the following from a console on your machine: `az account show` and see if that tenant ID shows up there?

**Comment by ctharmon722** [comment]
I did see it in the local storage, but was not able to edit it. 
I think you hit the nail on the head, the 'az account show' shows my old tenant. How do I change that? Where is that coming from/stored?

**Comment by dmvtech** [comment]
@ctharmon722 

Do the following:
`az logout`
`az login`

After that it should give you the same results as `az account show` would. I'm not 100% sure this is connected, but worth a shot at this point.

**Comment by dmvtech** [comment]
HI @ctharmon722 Any updates?

**Comment by ctharmon722** [comment]
It still isn't working. I have logged out, logged back in, and it shows the correct account when I use az account show

It is very frustrating because absolutely everywhere else I don't have this problem, and I don't have it in 1.3.

I was hoping the next version would clear this up, but then 2.0 came out. We can't use 2.0 because we use custom actions. As of last weekend I rolled our Composer back to 1.3, and published that way. It worked perfectly.

**Comment by dmvtech** [comment]
Hi @ctharmon722 Thanks for testing and your patience. We have no idea what might be happening here.

As a test; would it be possible for you to copy of your bot and test it out in 2.0? I'm mostly curious to see if this issue still persists for you in 2.0 as well. If you need to remove/isolate your custom action out of that, that is fine. I understand this might take additional steps as well, as you have to to publish to a _new_ bot to ensure you're not publishing over the top of your current bot. 

There are steps that can be taken to port the custom action to 2.0, so if we can confirm this behavior does not exhibit for you in 2.0, that might be the most appropriate route. Alternatively, if 1.3 is working for you and you are not ready to move to altering your custom action for 2.0, staying on that version for the time being might be the better option for now.

**Comment by ctharmon722** [comment]
@dmvtech I was able to create resources in 2.0 no problem. It did have the old subscription in there (I don't own it, so I can't seem to get rid of it), but unlike in 1.4 and 1.4.1 I could choose which I wanted to use. Just to clarify, 1.3 published to the correct one without doing anything. I am not sure because the correct one is what I am always signed in on or if it is because it is my default. The only thing I can guess is that 1.4 and 1.4.1 use the oldest subscription? Obviously, that is a guess.

Based on the documentation, the custom actions can't be ported over. I would love if they could, but right now we read a SQL database and write out responses based on the data in the database. This seemed to be an unsupported feature in Composer.

**Comment by dmvtech** [comment]
@ctharmon722 You mention not owning the subscription. But if you go into the Azure portal, do you have a default subscription set? If so, is it the correct one that you want to publish to, or another? Please try setting the default subscription to the one you wish to publish to and then try.

**Comment by ctharmon722** [comment]
@dmvtech, the default subscription is the subscription that I want it to publish to. Which is why I think it publishes fine with 1.3, and since 2.0 asks, any bot that we don't use custom actions for should be fine too.

**Comment by dmvtech** [comment]
Hi @ctharmon722 Apologies for the delay. Still at a loss on why this would be happening. 

@GeoffCoxMSFT Any thoughts on this one?

**Comment by tonyanziano** [comment]
@GeoffCoxMSFT can you provide any comments on this issue?

**Comment by dmvtech** [comment]
@ctharmon722 

As this issue is no longer exhibiting in 2.0.0 or later (due to how we handle and understand multiple tenants), and we are unable to reproduce the issue on our end; you will need to live with the workaround you have, or port your custom action over. Our apologies for the inconvenience.
