### ISSUE TITLE
issues with update-schema script

### ISSUE THREAD

**Issue by praveenvavilla** [microsoft/BotFramework-Composer#7862]
## Describe the bug

I am using nightly composer and I see below error when try to run update-schema script 
.\update-schema.ps1
Running schema merge.
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\Users\prvavill\AppData\Roaming\npm\node_modules\@microsoft\botframework-cli\bin\run'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
Schema merge failed. Restoring previous versions.
PS D:\Kustofeatures\bot\GaiaTestCustomActions\GaiaTestCustomActions\schemas> .\update-schema.ps1
Running schema merge.
module.js:487
    throw err;
    ^

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] Windows

**Comment by boydc2014** [comment]
@praveenvavilla   can you share your project setup and the previous steps before you run update-schema?

@benbrown is this update-schema still needed when doing custom actions?

**Comment by praveenvavilla** [comment]
I noticed that there is a error while installing bot framework cli, may be this is an issue here 
![image](https://user-images.githubusercontent.com/55256942/118744853-ec15cc00-b809-11eb-966e-a21d3e54c5e8.png)

**Comment by srinaath** [comment]
@praveenvavilla What node version are you currently on? The botframework-cli needs Node 12 version to run on.

**Comment by ninggao** [comment]
@srinaath Thanks for the prompt reply. Please continue helping the customer on this issue.

**Comment by srinaath** [comment]
Closing this ticket. Connected with customer offline and the issue was with the Node version being in 8.0.
