### ISSUE TITLE
Load skill manifests from any location

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#7864]
In composer 2.x a user can load a manifest from an http or https endpoint only, but this should be the only way. 

Manifests describe the skill operations but they don't necessarily need to be exposed on an http endpoint, we do this in samples for convenience but a skill provider may choose not to do this and send the manifest and related files to the consumer offband. In this case, I should be able to load the manifest from the file system if I need to. 

![image](https://user-images.githubusercontent.com/12264946/118800267-bb677e00-b86d-11eb-8ecd-fd24c56228ba.png)

Also, I think manifests and related lu files should be stored locally with the bot project once the skill is added and only be rechecked when the developer chooses to (sort of like a decision to update nuget packages). Right now, composer tries to retrieve the manifest every time I open the project and that shouldn't be necessary once a skill has been added and a copy of the manifest and lu files are stored with the botproj.

![image](https://user-images.githubusercontent.com/12264946/118799920-4dbb5200-b86d-11eb-90f0-ea67fcdbabc2.png)

**Comment by luhan2017** [comment]
@vivekkshankar , let's follow up on this requirement offline.
