### ISSUE TITLE
Allowed callers UI doesn't update when you switch between bots

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#7866]
## Describe the bug
In Configure, the allowed callers list UI does not update when you switch between bots

Root bot:
![image](https://user-images.githubusercontent.com/27976702/118863527-dcdb6080-b893-11eb-8a4c-a85a422f8b1c.png)

Click to skill bot:
![image](https://user-images.githubusercontent.com/27976702/118863602-f41a4e00-b893-11eb-9fc3-235f7177290c.png)

Actual value in json:
```
    "skills": {
      "allowedCallers": [
        "f56540b8-cc76-461f-930a-b9e1c5f307b7"
      ]
    },
```

The UI doesn't refresh until you click another tab and go back:
![image](https://user-images.githubusercontent.com/27976702/118863757-25931980-b894-11eb-8551-bbac1dac9c22.png)

## Version
Version:  2.0.0-nightly.246170.8fa93
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by srinaath** [comment]
@luhan2017 This could get a bit confusing if the allowList is showing stale values and the user wondering why the skill connection is not working.

**Comment by tdurnford** [comment]
It looks like the selected project id isn’t updating correctly. I’ll take a look.
