### ISSUE TITLE
when running update schema there are 2 packages with the same name

### ISSUE THREAD

**Issue by jamalsia** [microsoft/BotFramework-Composer#7877]
## Describe the bug

when running
sh ./update-schema.sh

i am getting 
`
Running schema merge on nodejs runtime.
Finding component files
Error conflicting definitions of Microsoft.IDialog.schema
  botbuilder-dialogs-declarative: /Users/vanilla/git_repo/AOSREbot/runtime/node_modules/botbuilder-ai/node_modules/botbuilder-dialogs-declarative/schemas/Microsoft.IDialog.schema
  botbuilder-dialogs-declarative: /Users/vanilla/git_repo/AOSREbot/runtime/node_modules/botbuilder-dialogs-declarative/schemas/Microsoft.IDialog.schema`

## Version

1.4.1
## Browser

Emulator
Teams

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to runtime foloder
2. run npm i -g @microsoft/botframework-cli ; npm run build
3. go to schemas folder 
4. run sh ./update-schema.sh

## Expected behavior

the schema to be updated successfully

## Screenshots
![image](https://user-images.githubusercontent.com/25248608/119108118-c3fbb800-ba17-11eb-9b17-03997dd371e6.png)
![image](https://user-images.githubusercontent.com/25248608/119108169-d1b13d80-ba17-11eb-8025-f98ed2d4f63c.png)
![image](https://user-images.githubusercontent.com/25248608/119108203-dd046900-ba17-11eb-9162-8de37a6d6e63.png)

![image](https://user-images.githubusercontent.com/25248608/119107970-a75f8000-ba17-11eb-88b3-e8307b8c3ba6.png)
![image](https://user-images.githubusercontent.com/25248608/119108060-b8a88c80-ba17-11eb-8c20-e42052d57529.png)

## Additional context

`{
  "$schema": "https://raw.githubusercontent.com/microsoft/botframework-sdk/master/schemas/component/component.schema",
  "type": "object",
  "title": "Component kinds",
  "description": "These are all of the kinds that can be created by the loader.",
  "oneOf": [
    {
      "$ref": "#/definitions/AkaDiagErrStrDialog"
    },
    {`
[.....]
`  "definitions": {
    "AkaDiagErrStrDialog": {
      "$role": "implements(Microsoft.IDialog)",
      "title": "AkaDiagErrStr",
      "description": "This will return the translated CDN Error String",
      "type": "object",
      "$package": {
        "name": "node-runtime",
        "version": "1.0.0"
      },`

**Comment by jamalsia** [comment]
this comes from the definition here :
![image](https://user-images.githubusercontent.com/25248608/119110898-75035200-ba1a-11eb-87bd-2897e2733372.png)

**Comment by jamalsia** [comment]
is this solved in composer 2.0?

**Comment by jamalsia** [comment]
interesting. it seems that in the bot composer the folder is src and in azure the folder is lib
in azure:

`D:\home\site\wwwroot\lib\src\mycustomdialog\.config
`
in bot composer in macos (works):

`newbot_repo/runtime/src/mycustomdialog/.config
`


code snippet:

`        myfilePath = path.resolve('src/mycustomdialog','.config');
`

**Comment by ninggao** [comment]
@stevkan Could you please route it appropriately?

**Comment by anusharavindrar** [comment]
@jamalsia, thanks for reporting this. I will attempt a repro on my end. Also, have you tried this only on Mac or you get the same error on Windows as well? Can you specify what version of the MacOS are you on?

**Comment by srinaath** [comment]
@jamalsia Does using the powershell script generate the same error for you as well?

**Comment by jamalsia** [comment]
@srinaath , no sorry, i used the bash script only

**Comment by anusharavindrar** [comment]
Having issues with reproducing the issue on my Mac. Will update the thread with more details as soon as I am able to get a successful repro.

**Comment by anusharavindrar** [comment]
@jamalsia, I am not able to repro the issue on my Mac. I just created a new bot from the Echo Bot template, downloaded a new copy of the runtime code and ran the above commands. My Mac OS version is Catalina(v10.15.4). Here are the details,

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/48731427/119879549-33721b80-bee0-11eb-9b89-f3f73a94b8b1.png)
![image](https://user-images.githubusercontent.com/48731427/119880022-ada2a000-bee0-11eb-9d79-7e2a9ed79097.png)

 Can you try once with any other bot and see if the issue persists? Also, can you give it a go with the latest Composer version and update your findings?

**Comment by jamalsia** [comment]
thanks @anusharavindrar . just to be sure did you install both 
`botbuilder-dialogs-declarative`  and `botbuilder-ai` when testing?

**Comment by anusharavindrar** [comment]
@jamalsia, yes installed both `botbuilder-dialogs-declarative` and `botbuilder-ai` while testing. Also, what version of the node are you on?


![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/48731427/119887056-8223b380-bee8-11eb-9567-064a2ee3df8f.png)

**Comment by jamalsia** [comment]
ok Thank you @anusharavindrar . then please close the ticket.
Reinstalling botbuilder-ai fixed the issue.
