### ISSUE TITLE
2.0.0 Version "speech" setting is not work.

### ISSUE THREAD

**Issue by junewoo-cv** [microsoft/BotFramework-Composer#7878]
## Describe the bug

Bot Composer 2.0.0 Speech settings do not work properly in the composer.
When `voiceFontName` is set, it is applied as the default voice.

Reference 
https://docs.microsoft.com/en-us/composer/concept-speech?tabs=v2x

## Version

2.0.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Configure your bot'
2. Click on Advanced Setting View'
3. Set value 'setSpeak' in `runtimeSettings in features` 
4. Not work

**Comment by hatpick** [comment]
@junewoo-cv would you please add steps to repro, what do you expect to happen and what's actually happening?

**Comment by ninggao** [comment]
@stevkan Could you please route it appropriately?

**Comment by junewoo-cv** [comment]
Sorry, I saw your reply late.

I restarted Bot Composer several times, so I don't know the exact way to operate normally.
It's working normally at the momentarily.

**Comment by v-kydela** [comment]
@junewoo-cv - Is your issue resolved? Should we close it?

**Comment by junewoo-cv** [comment]
> @junewoo-cv - Is your issue resolved? Should we close it?

yes, Thank you for your reply
