### ISSUE TITLE
Publishing bot giving error  'invalid_grant' description: '(pii)' 

### ISSUE THREAD

**Issue by nikhilmalik9997** [microsoft/BotFramework-Composer#7879]
While publishing when I login, it gives the following error:-
 Recieved an error from AAD. Code: 'invalid_grant' description: '(pii)' correlation id: 'd395e2a0-60f1-4680-9c58-ee96baef3fd7' suberror: 'basic_action.
In the publish configuration file I have added the subscription Id, luis authoring key, resource group access token etc. but still this issue is coming.

**Comment by hatpick** [comment]
@nikhilmalik9997 are you sure you have entered the right username when prompted to login?

**Comment by hatpick** [comment]
@nikhilmalik9997 are you sure you have entered the correct username (no typos, etc.) when prompted to login?

**Comment by ninggao** [comment]
@anusharavindrar Could you please help the customer on this issue?

**Comment by anusharavindrar** [comment]
@nikhilmalik9997, what version of the composer are you on? Can you attach a screenshot of the error you are getting? Also, as stated in the above comment, can you double check if you have entered the correct username?

**Comment by nikhilmalik9997** [comment]
@anusharavindrar  Yes, I am entering the correct username. I am working on  bot framework version 1.4.1. I have also attached the screenshot of the error for your reference.
![Screenshot (9)](https://user-images.githubusercontent.com/26502483/119319568-3da1d900-bc98-11eb-9e1a-ab3cb4b3f34d.png)

**Comment by anusharavindrar** [comment]
@nikhilmalik9997, I am able to reproduce the issue on v1.4.1. Can you try upgrading to the latest version and give it a go? In the menu bar, go to Help > Check for updates and install the latest version and try publishing the bot. I am able to login without the above error in the latest version **v2.0.0-nightly.247300.1b9d669**

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to reopen if the issue persists.
