### ISSUE TITLE
"Unable to cast" error when using a luis intention 

### ISSUE THREAD

**Issue by gabrielguarisa** [microsoft/BotFramework-Composer#7880]
## Describe the bug

Every time a message is evaluated by a LUIS trigger, the following error is returned: 

`Unable to cast object of type ‘System.Int64’ to type ‘System.Int32’.`

This project was created in version 1.4.1 and converted to version 2.0. In the previous version the project works without any problems.

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Screenshots

This error happens in all intent triggers registered in my bot.
Below are images with an example of this happening in an intention. 

### Error message
![Error message](https://user-images.githubusercontent.com/11513141/119148740-2c9c6200-ba23-11eb-8b90-72cf12c159bf.PNG)

### Dialog structure
![Dialog structure](https://user-images.githubusercontent.com/11513141/119148828-450c7c80-ba23-11eb-9511-adadbbbce3de.PNG)

### Intent settings
![Intent settings](https://user-images.githubusercontent.com/11513141/119148939-62414b00-ba23-11eb-9d71-b28d8735d536.PNG)

**Comment by v-kydela** [comment]
Thank you for the report, @gabrielguarisa. I would like to help and I have a few questions.

1. Are you able to reproduce the problem when creating a new bot in Composer 2.0?
2. If not, can you copy your project and then modify it to create a minimal example of the problem?
3. Can you help us reproduce the problem by providing a sample project with repro steps?

We've seen this kind of issue before, though not in Composer: https://github.com/microsoft/botbuilder-dotnet/issues/1859

**Comment by gabrielguarisa** [comment]
@v-kydela thanks for the reply. 

I followed your suggestion and tried to create a new bot in composer 2.0. And I accidentally found out why this problem was happening . It has no connection with LUIS (should I change the title of this issue?). 

I am using the delay activity before the text messages, in a similar way to what is suggested [here](https://github.com/microsoft/BotFramework-Composer/issues/4406#issuecomment-711430180). But the casting error happens when setting the delay time on a variable.

The project created with the reproduction of the error: [bot.zip](https://github.com/microsoft/BotFramework-Composer/files/6542315/bot.zip)

![casting error](https://user-images.githubusercontent.com/11513141/119566989-24755700-bd82-11eb-948c-43a55290d4a6.PNG)

**Comment by v-kydela** [comment]
@gabrielguarisa - Thank you for the sample. I can reproduce the problem now, and I believe it is related to the problem I linked to before. It looks like the new cloud adapter reintroduced the problem with [this line](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/CloudAdapterBase.cs#L79):

> ```c#
> var delayMs = (int)activity.Value;
> ```

I'll work on a PR to fix this. I see two possible workarounds for now:

1. Bypass the variable, replacing `${user.typingSpeed}` with `${1000}`
2. Get your exported runtime to use a Bot Framework adapter instead of a cloud adapter

**Comment by gabrielguarisa** [comment]
Thank you for your help. I will test the suggested approaches.
