### ISSUE TITLE
Updated to 2.0 and now can't open Bot because conversion fails

### ISSUE THREAD

**Issue by jporletto** [microsoft/BotFramework-Composer#7881]
Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm root -g --prefix C:\Users\joporlet\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error 'npm' is not recognized as an internal or external command, operable program or batch file.

**Comment by garypretty** [comment]
It looks like you need to install Node.js, which includes NPM, which cannot be found. If you install 14.17 from here -> https://nodejs.org/en/ that should resolve the error.

**Comment by jporletto** [comment]
Installed Node.js and it was able to successfully convert to 2.0. Thanks!
