### ISSUE TITLE
ONNX Multilingual model failed to load , Bot is failing Failed to find or load Model with path 

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#7892]
## Describe the bug

Multi Lingual Bot using orchestrator model (ONNX) is failing with error 
Failed to find or load Model with path C:\home\site\wwwroot\model\pretrained.20210205.microsoft.dte.00.06.unicoder_multilingual

## Browser

- [ ] Chrome
- [ ] Edge

## OS

- [ ] Windows

## To Reproduce

1. Create Bot in Composer
2. Added Skill (another Bot) , which brought in Orchestrator models
3. Added multi lingual  capabilities into the Bot'
4. Runtime Bot fails with the below 
Failed to find or load Model with path C:\home\site\wwwroot\model\pretrained.20210205.microsoft.dte.00.06.unicoder_multilingual
5. Fails in emulator as well .. Path is local path when deployed to Azure , above path is given
## Expected behavior
6. English language works in same bot, This issue occurs when other locale is selected

7. additional info: My Root dialog uses Orchestrator recognizer and immediate next dialog where it fails uses Regular expression recognizer/ i tried with orchestrator also and it fails there as well

## Screenshots

![image](https://user-images.githubusercontent.com/26645750/119235727-7cfae900-bb23-11eb-8cf3-ca7cdc278900.png)
![image](https://user-images.githubusercontent.com/26645750/119235776-a7e53d00-bb23-11eb-84e8-7017db42454c.png)

**Comment by taicchoumsft** [comment]
Hi @aparnaji ,  thanks for the bug report. 

1) Does multilingual work when you test a bot locally? 

2) If the failure is happening only when you deploy multilingual bot to Azure, can you help us verify on your Azure deployment, if that folder `C:\home\site\wwwroot\model\pretrained.20210205.microsoft.dte.00.06.unicoder_multilingual` exists?  Can you show a screenshot or dump of its directory contents?

Can you also help us to look at `C:\home\site\wwwroot\generated\orchestrator.settings.json` on your Azure deployment and post its contents here? You can access this information by using **Kudu** or **App Service Editor** in Azure - docs [here](https://social.technet.microsoft.com/wiki/contents/articles/36467.understanding-the-azure-app-service-editor.aspx)

Thanks @aparnaji

**Comment by aparnaji** [comment]
Hi @taicchoumsft 
Thanks for the fix , It helped 
1. My bot failed locally as well 
2. Your fix of including **/*.model in <Bot Project>.csproj file locally fixed the issue and now the Bot is working locally and in Azure as well

**Comment by taicchoumsft** [comment]
Thanks for confirming that the fix works @aparnaji , we will fix this in a patch release so this manual step does not need to be taken.

**Comment by taicchoumsft** [comment]
Tracking [Components#1129](https://github.com/microsoft/botframework-components/issues/1129) that will close this issue.
