### ISSUE TITLE
Sidebar has outdated information

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/BotFramework-Composer#7897]
_Please close this if it's duplicate_

## Describe the bug

The sidebar of the Composer 2.0.0 has an outdated version information. 

![image](https://user-images.githubusercontent.com/16351038/119339601-b3c43100-bcd4-11eb-914b-95befa5438cd.png)

## Version

2.0.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

Windows 10

**Comment by garypretty** [comment]
Thanks @arafattehsin - this will be getting updated tomorrow when our Build post goes live. Thanks again!
