### ISSUE TITLE
Referenced link in template Readme.md opens in the Composer window

### ISSUE THREAD

**Issue by hatpick** [microsoft/BotFramework-Composer#7908]
## Version

Version:  2.0.0-nightly.247300.1b9d669
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create new
2. Select "Core Bot with Language"
3. On the right side, click LUIS in ```Create a simple conversational bot with Azure Language Understanding (LUIS)```
4. Notice how it opens LUIS.ai within the same window

## Expected behavior

Open the url in the system default browser.

## Additional context

It's a bug in react-markdown, updating to the latest version fixes the issue:
[https://codesandbox.io/s/amazing-goldberg-3youf](https://codesandbox.io/s/amazing-goldberg-3youf)
The link above demonstrates the issue, update the react-markdown dependency to the latest version and try again to see it fixed.

**Comment by pavolum** [comment]
Issue was not resolved. Initially it seems like an easy fix to just update the version of react-markdown however that leads to dependency hell as the newer version of react-markdown has dependencies that conflict with other dependencies.

**Comment by benbrown** [comment]
@pavolum did this get resolved in the end with our updates to the readme file formats? I believe so...

**Comment by pavolum** [comment]
Yes it did, closing now
