### ISSUE TITLE
Bot Does not Speak

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#7914]
## Describe the bug
Bot developed using the composer is not speaking, however it is recognizing the intents that the user utters

## Version
Version:  2.0.0-nightly.247300.1b9d669
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Chrome
- [ ] Edge

## OS

- [ ] Windows

## To Reproduce

1. Go to Bot Dialog
2. Add Speech options for Dialog
3. Bot does not speak out
4. Bot in emulator nor in web chat

## Screenshots

Bot should be able to utter all text given in speech both in Emulator and web chat, additional to text utterances

**Comment by someonelikeTIM** [comment]
I may be having the same issue on composer v2.0.0 stable using the "Core Bot with Language" (NodeJS) Template. The bot only responds with the original bot responses from the template even though I have changed them.

**Comment by srinaath** [comment]
@aparnaji Is your input to the bot in Webchat through text or speech? The expectation should be that the bot response will be in the same modality as the input even if the Speech modality is enabled for that response.

**Comment by srinaath** [comment]
@someonelikeTIM The parent issue seems unrelated to the problem in your bot. Could you track your concern in a different ticket?

**Comment by srinaath** [comment]
@garypretty Can you weigh in on this ticket?

**Comment by garypretty** [comment]
@aparnaji Can you please provide more information so that @srinaath and the team can diagnose / investigate you issue.  Please provide steps to reproduce the problem including what channel / tool you are expecting to hear the bot speak through. e.g. which channels are you using?

**Comment by aparnaji** [comment]
@srinaath Your response "The expectation should be that the bot response will be in the same modality as the input even if the Speech modality is enabled for that response." helped. I modified my web chat java script also to send a input to read the message and used azure speech services
