### ISSUE TITLE
Skill documentation missing intended link

### ISSUE THREAD

**Issue by gremlin529** [microsoft/BotFramework-Composer#7915]
## Describe the bug

In the concept-skills documentation https://docs.microsoft.com/en-us/composer/concept-skills

At the bottom of the first section **About Skills** the last sentence says:

  You should already be familiar with [bot design in Composer][TODO.md] 

I believe there is missing information on this line.

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x ] Edge

## OS

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

**Comment by JonathanFingold** [comment]
@gremlin529 Thanks for catching this. In the future, please open Composer doc bugs in the MicrosoftDocs/Composer-docs repo. They are more likely to be addressed in a timely fashion there. A fix is in Composer-docs-pr [PR 550](https://github.com/MicrosoftDocs/composer-docs-pr/pull/550).

**Comment by JonathanFingold** [comment]
Article is updated.
