### ISSUE TITLE
"Remove this trigger" should have a confirmation dialog

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#7920]
## Describe the bug

From the bot project tree, clicking "Remove this trigger" removes the trigger without any confirmation dialog. This is inconsistent with "Remove this dialog" which shows a confirmation dialog".

## Version

Bot Framework Composer

Version:  2.0.0-nightly.247623.340809f
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to the project tree.
2. Next a trigger, click on '....' and "Remove this trigger"
3. The trigger is removed. Also, any response templates that are used in that trigger (and only in that trigger) are removed.

## Expected behavior

I'd expect a modal that says: "This will delete the trigger and its contents. Do you wish to continue?" (I expect a confirmation 
## Screenshots

Here is the analogous screen from deleting a dialog:

![image](https://user-images.githubusercontent.com/39317542/119582242-1a028f80-bd79-11eb-9717-419116fe9e56.png)

**Comment by mewa1024** [comment]
@mareekuh @vivekkshankar any reason why we shouldn't warn people before deleting a trigger?

**Comment by mewa1024** [comment]
(need to check for other destructive actions that have no Undo)

**Comment by vivekkshankar** [comment]
@mareekuh FYI for UX backlog
