### ISSUE TITLE
Something went wrong!

### ISSUE THREAD

**Issue by coder4321** [microsoft/BotFramework-Composer#7921]
whenever I click anywhere on bot framework composer, it displays a prompt stating something went wrong.
Please help asap. Its a blocker for me.

**Comment by stevkan** [comment]
Can you list which version of Composer you have installed?

Also, are there any other error messages displayed? If you click View >> Toggle developer tools in the menu bar, you can check the developer's console for any other errors being reported.

Lastly, have you tried uninstalling / reinstalling or updating to the current 2.0.0 version (if running an older version)?

**Comment by stevkan** [comment]
Closing due to lack of response. Please feel free to re-open if the issue persists or you have new details to provide.

**Comment by victorlamana** [comment]
I have the same issue
