### ISSUE TITLE
Settings-Development resources: where does Composer store the entered values locally?

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#7924]
I tried to make changes on the values from Composer UI, but did not notice any file changes.
Would you please help clarify where Composer store these inputs locally? as there are value of secrets involved and we would like to have an idea of where they are, assuming it's in clear text.

![image](https://user-images.githubusercontent.com/44714043/119639333-37544f80-bdb3-11eb-96a9-a548cf20a04f.png)

**Comment by dmvtech** [comment]
Hi @dawwa They are kept in the `Local Storage` memory of the browser/electron application. You can find this By going to Developer Tools->Sources.

**Comment by dmvtech** [comment]
Closing as answered.
