### ISSUE TITLE
Bot fails to start on first attempt after opening Composer.

### ISSUE THREAD

**Issue by someonelikeTIM** [microsoft/BotFramework-Composer#7926]
## Describe the bug

Bot fails to start on first attempt after opening Composer.

```
Sorry, something went wrong with publishing. Try again or exit out of this task.

ENOTEMPTY: directory not empty, rmdir 'C:\...\generated
```

It works the second time but never the first time after opening composer.

## Version

Version:  2.0.0-nightly.247767.2ec0472
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

[ x ] Windows

## To Reproduce

1. Launch fresh instance of Composer
2. Start Bot
![image](https://user-images.githubusercontent.com/40400490/119695356-14aa5100-be1c-11eb-99f9-a88376eb7a91.png)
3. Bot status goes to failed and error message shows up in Output 
![image](https://user-images.githubusercontent.com/40400490/119693975-ce082700-be1a-11eb-9ac7-aae4f0c6354c.png)
![image](https://user-images.githubusercontent.com/40400490/119694779-8afa8380-be1b-11eb-9ffc-10fefd97b465.png)
4. Start bot again and it works.

## Expected behavior

It should start the first time.

**Comment by cwhitten** [comment]
@someonelikeTIM can you provide a bit more information about your project? Which technology is used? NodeJS? Are you able to upload the project here for us to take a look?

**Comment by someonelikeTIM** [comment]
@cwhitten yes NodeJS. I've barely customized the template so I can upload it no problem. Which file(s)/folder(s) would you like me to upload?

**Comment by anusharavindrar** [comment]
@someonelikeTIM, can you export your entire bot as a zip and attach here for us to take a look?
![image](https://user-images.githubusercontent.com/48731427/119860640-63fb8a80-becb-11eb-945f-c25fde99e476.png)

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to reopen if the issue persists.
