### ISSUE TITLE
Add LUIS "List Entity" creation modal to LU Editor

### ISSUE THREAD

**Issue by hatpick** [microsoft/BotFramework-Composer#7931]
Similar to Luis

**Comment by hatpick** [comment]
@JaskeeratBedi-cmk any updates on designs for this?

**Comment by JaskeeratBedi-cmk** [comment]
@mewa1024 will be taking this one

**Comment by hatpick** [comment]
@mewa1024 any progress?

**Comment by mewa1024** [comment]
Figma mockups: https://www.figma.com/file/DQ8xiC9VMfPX0nb0MBmOIs/?node-id=695%3A2923

![image](https://user-images.githubusercontent.com/39317542/121462920-2cc6b800-c966-11eb-8a36-9f27f436ad3d.png)
