### ISSUE TITLE
New UX to switch recognizer type

### ISSUE THREAD

**Issue by luhan2017** [microsoft/BotFramework-Composer#7935]
![image](https://user-images.githubusercontent.com/32191031/119759246-8052f380-beda-11eb-8b87-331bb21507fb.png)

https://www.figma.com/file/MDwHWFVT2Cth9yFzazJxCB/Orchestrator-%26-Skills-R13-and-beyond?node-id=463%3A16035

**Comment by boydc2014** [comment]
Design is ready

**Comment by tdurnford** [comment]
@luhan2017 @boydc2014 Why are we putting the recognizer selection in a modal instead of just having it inline in the form? Adding the 'Change' button is a whole new concept in the form that user's are not accustom to, and there is plenty of space in the form for the UI.

**Comment by luhan2017** [comment]
@vivekkshankar , could you comment on this?

**Comment by cwhitten** [comment]
ping @vivekkshankar
