### ISSUE TITLE
Whenever MS App Password contains | operator, Composer gives an error message

### ISSUE THREAD

**Issue by prafuldhone** [microsoft/BotFramework-Composer#7937]
Whenever MS App Password contains | (pipe) operator, Composer gives an error message.

For eg: if my password is "H2Uc_|^Ax.j(+3m>NVVx]DOx9", it gives following error message.
<img width="772" alt="ComposerError" src="https://user-images.githubusercontent.com/20317538/119782197-800e2480-bee9-11eb-9a70-ec1352c0c247.png">

**Comment by srinaath** [comment]
Closing this as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/7936. A PR is already out to fix this issue.
