### ISSUE TITLE
How to view an existing QnA KB to Composer

### ISSUE THREAD

**Issue by MarcoWirtl** [microsoft/BotFramework-Composer#7940]
Hi, 
I have an existing QnA KB in the Portal, I want to view my QnA Pairs in Composer.
How to import the existing Pairs?

Currently, I'm receiving the answers in Emulator when starting from Composer. So I am connected correctly with the right KB.
I want to edit the pairs straight out of Composer.
Any help?

**Comment by srinaath** [comment]
@MarcoWirtl We are planning to add a feature to import pairs from an existing qna kb. We will link this ticket to a feature ticket that we are using to track the feature.

**Comment by srinaath** [comment]
Closing as feature tracked here https://github.com/microsoft/BotFramework-Composer/issues/7981
