### ISSUE TITLE
Bot composer 2.0 issue with converting a bot

### ISSUE THREAD

**Issue by KyonCode** [microsoft/BotFramework-Composer#7944]
Hello,

updated composer to 2.0 and converted bot (v 1.4).  

When try to Start Bot receive this error:

Error occurred building the bot

POST401/v3/directline/conversations/52e009da-8fa8-463e-95ab-48aa09d95111%7Clivechat/activities
An error occurred validating the Microsoft App Id and Microsoft App Password.
AADSTS7000216: 'client_assertion', 'client_secret' or 'request' is required for the 'client_credentials' grant type.

App id and Microsft are retrieved automatically.

Thank you for any help!

**Comment by KyonCode** [comment]
Ok now I moved to this error:

npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR!

**Comment by anusharavindrar** [comment]
@KyonCode, do you get any additional error in the dev console(in the menu bar, go to View > Toggle Developer Tools)? Does this happen with all the bots or just this specific bot? Can you also check if your client secret is expired? Also, are you on the Desktop version of the Composer?

**Comment by anusharavindrar** [comment]
Closing the issue. Please feel free to re-open if issue persists.
