### ISSUE TITLE
Orchestrator/LUIS: Disambiguation trigger should behave similarly

### ISSUE THREAD

**Issue by taicchoumsft** [microsoft/BotFramework-Composer#7945]
Related to issue [Component#1015](https://github.com/microsoft/botframework-components/issues/1015).  

This ticket tracks the investigation and Composer related changes to have the `OnChooseIntent` trigger behave similarly for Orchestrator and LUIS.

There were a couple of proposed solutions in the above issue, we will investigate and see which is feasible for R14.

**Comment by boydc2014** [comment]
Status: design

**Comment by OEvgeny** [comment]
Closing as not planned as LUIS is on the deprecation path
