### ISSUE TITLE
Debug Panel: Watch variables

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#7948]
This ticket tracks work on a new feature that helps looking at how state is changing as users interact with their bot – something similar to what PVA have and akin to the ‘watch’ feature within Visual Studio.

In Composer, initial thoughts on the feature involve choosing a variable to watch from any of these paths (currently used for intellisense) https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/server/src/services/project.ts#L111. In addition, we also track all the variables that a user creates in the memory while building the bot. 

The following are initial set of questions to answer in order to begin implementing a solution to watch changes to the above variables during a conversation with the bot.

1. Could we use “Bot State” trace to track memory or should we rely on a different approach?

2.  A  “Bot State” trace is sent for every turn but  essentially any changes the bot code makes to the tracked variables in the temporary scope (dialog, turn or maybe a custom temporary scope) are never sent as a trace unless a dialog contains multiple turns. The trace that comes at the end of the turn if the dialog has ended shows only the data in more permanent scope (conversation, user) as the dialog data has already been popped out of the stack.

3. The current  “Bot State” trace does not divulge any info about the turn scope. @johnataylor  had mentioned that it would be a problem to send this value due to this data not being persisted.

Cc @mrivera-ms @johnataylor @garypretty @cwhitten @tonyanziano

**Comment by tonyanziano** [comment]
Confirming points 2 & 3:

![image](https://user-images.githubusercontent.com/3452012/120526070-a9b5c880-c38d-11eb-88fd-0e3703bf68a7.png)

This is the Bot State trace sent immediately after printing the `dialog.blah` and `turn.blah` values from their scopes. Only the `user` scope is persisted.

**Comment by srinaath** [comment]
Recalibrating the deliverables based on timelines based on conversation with @garypretty . 
**P0** - Composer would need the turn state  in each Bot state trace in R14. Exposing the turn state alone would be a huge game changer as developers can watch for recognizer info etc.

**P1** - Exposing the dialog information can be pretty complex considering the scenario nested dialogs. This scenario will accrue a lot more value once Step by Step debugging is implemented Composer giving the user the ability to stop at breakpoints and expose the dialog info at that stopped point.

**Comment by johnataylor** [comment]
The SDK change has been merged.

**Comment by tonyanziano** [comment]
Thanks for the update @johnataylor

**Comment by garypretty** [comment]
@tonyanziano @srinaath We need to add the following telemetry events for the new watch tab please.

Event Name: StateWatchPropertyAdded
Fires when a user adds a property to watch.
Should include a custom property called 'property' which contains the property path being watched.

Event Name: StateWatchPropertyRemoved
Fires when a user adds a property to watch.
Should include a custom property called 'property' which contains the property path being removed.

**Comment by tonyanziano** [comment]
This was addressed in #8151
