### ISSUE TITLE
Trigger order can be significant, UI needs to let me rearrange the triggers

### ISSUE THREAD

**Issue by tomlm** [microsoft/BotFramework-Composer#7952]
## Describe the bug

I need to be able to reorder the trigger definitions.

## Version

2.0.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create multiple intents
2. Try and change the order, you can't.

## Expected behavior
That I can change the order of triggers without having to resort to editing json

**Comment by lauren-mills** [comment]
Seconded!

**Comment by mkfah809** [comment]
I tried to change the order of them, but I couldn't. I had to specific dialog to start the trigger with. ( That will make specific trigger popup before)

**Comment by victorlamana** [comment]
Yeah this is much needed, changind dialog order would help too
