### ISSUE TITLE
There is no longer a project settings tab, but we still refer to one

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#7954]
## Describe the bug

The following notification appears when you publish a skill, yet I cannot find a _project settings_ tab anywhere:

> Keep this URL handy to share it with other developers to use in their bot projects. You can find this URL in the project settings tab.

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Publish a skill for the first time and see the cited notification.
1. Errors:
    1.  Try to find a **Project settings** tab anywhere in the UI; I cannot find one.
    2. Try to find the remote manifest URL in the UI (beyond the notification); I cannot find it.

## Expected behavior

1. We don't refer to UI elements that don't exist. (If they are simply hard to find, then describe where to find them.)
2. The remote skill manifest URL is recoverable without having to leave Composer.

## Screenshots

![project-settings](https://user-images.githubusercontent.com/35047199/120046864-fbde9e80-bfc7-11eb-96e1-547ce03a1799.png)

**Comment by luhan2017** [comment]
@vivekkshankar , need your input here, should we say "in the publish tab"?

**Comment by mewa1024** [comment]
Can we avoid referring to parts of the app by name and instead use something more generic? In this case, can we change "in the project settings tab" to just "in your project settings" and link to the appropriate section?

The generic text means we won't have to update the text if we change the name of the tab in the future, and the link will avoid any ambiguity about what section we are talking about.

**Comment by vivekkshankar** [comment]
Fair point @mewa1024. Let's actually drop the second line and keep it clean "Keep this URL handy to share it with other developers to use in their bot projects.". 

(If we hear feedback that this URL is hard to find going forward, we can as a remedy redirect to the publish page on copy (to teach the user where to find it) or give an action to view URL which does the redirect)
