### ISSUE TITLE
Copy Paste in canvas does not work and throws

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#7958]
## Describe the bug

Copy does not seem copying anything, nothing seems happening when I selected an item in the canvas and then clicked Copy.
When Ctrl+V, an error pops up, and seems like even when the clip board is empty, the error still pops up

## Version

2.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

![image](https://user-images.githubusercontent.com/44714043/120097025-113bf180-c0ca-11eb-9b23-0c381fe74f29.png)

![image](https://user-images.githubusercontent.com/44714043/120097040-257fee80-c0ca-11eb-98c6-e29f963db529.png)

**Comment by srinaath** [comment]
@dawwa We also observed that the shortcuts are not working. Are you able to Paste 
![Screen Shot 2021-06-01 at 9 47 30 AM](https://user-images.githubusercontent.com/13004779/120361439-adc6e500-c2be-11eb-816c-9f38c713422e.png) using this control. 

In addition, we are not able to repro the error that is pasted above. Could you share a zipped version of the bot for us to try and repro the error.

**Comment by srinaath** [comment]
@lei9444 PR would perform the following. Ctrl + c or Cmd +c would copy the assets below to the clipboard. On Ctrl + v, we would do the following
1. If some actions are selected, paste it to the end of the last selected action
2. if there is no selected action, paste it to the end of the current dialog
