### ISSUE TITLE
Upgraded Bot Framework Composer to v2.0.0 and unable to open my previous projects

### ISSUE THREAD

**Issue by chandsalam1108** [microsoft/BotFramework-Composer#7960]
Upgraded Bot Framework Composer to v2.0.0 and unable to open my previous projects.

Prompted with following message:
This project was created in an older version of Composer. To open this project in Composer 2.0, we must copy your project and convert it to the latest format. Your original project will not be changed.

While converting I'm getting following error:
Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm root -g --prefix C:\Users\achand\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error 'npm' is not recognized as an internal or external command, operable program or batch file.

**Comment by zhixzhan** [comment]
Hi @chandsalam1108 what is the node version are you using ? Can you please try re-install node v14+ ?

**Comment by Gassano** [comment]
@chandsalam1108 i also got same error.  anyway i did [ + create new ] first,  i was required to install node.js. after install it i can convert my previous project.

**Comment by chandsalam1108** [comment]
> @chandsalam1108 i also got same error. anyway i did [ + create new ] first, i was required to install node.js. after install it i can convert my previous project.
