### ISSUE TITLE
CAN'T OPEN BOT FRAMEWORK COMPOSER V2.0

### ISSUE THREAD

**Issue by victorlamana** [microsoft/BotFramework-Composer#7964]
Hello! Title is self explanatory. I'm working on a bot on Power Virtual Agents and can't open Bot Framework Composer no matter what (It's stuck on "Starting server").

I followed the tutorial of installation on Framework Composer page and installed the SDK and the Bot Emulator, and they both seem to be working ( I can even open Framework Emulator). But when I try to open Framework Composer, be it by Virtual Agents or simply by clicking on it on the desktop, it always gets stuck on the "Starting server" message.

I tried without VPN, with VPN, disabled proxy and the results are always the same... I opened the bot on CMD and found the following error message on log ( I dont know how to fix it, but I think it is a good starting point nonetheless):

C:\Users\lamanv\AppData\Local\Programs\Bot Framework Composer>
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:3668) UnhandledPromiseRejectionWarning: Error: The specified module could not be found.
\\?\C:\Users\lamanv\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\node_modules\orchestrator-core\orchestrator-core.node
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
(node:3668) UnhandledPromiseRejectionWarning: Error: The specified module could not be found.
\\?\C:\Users\lamanv\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\node_modules\orchestrator-core\orchestrator-core.node
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
(node:3668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
"Bot Framework Composer.exe""Bot Framework Composer.exe"

What should I do? Has anyone had a similar issue?

Any help is appreciated, thanks a lot!!!

**Comment by taicchoumsft** [comment]
Hi @victorlamana , thanks for reporting the issue. This error is due to some native dependencies not being able to load on your system.  Can you give us a little more information on the environment you're using?  Is this Windows 7/8/10?

**Comment by victorlamana** [comment]
Hello @taicchoumsft !!!! :)

I'm using Windows 10 Enterprise Build 1809

Is there something manual I can try to do to brute-force and open it?

**Comment by taicchoumsft** [comment]
Hi @victorlamana , can you try installing the latest `vc_redist.x64.exe` package from [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0), reboot, then try re-opening Composer again?

If you are also running an older version of Visual Studio (older than VS2019), can you update that and try again as well?

**Comment by victorlamana** [comment]
Hello, good morning @taicchoumsft. I'll try it later today and i'll report the results, thanks a lot

**Comment by victorlamana** [comment]
Installing vc_redist worked! Now I can open the program :)

Thanks @taicchoumsft !!!!!
