### ISSUE TITLE
[Something went wrong...] when pressing [Show code]

### ISSUE THREAD

**Issue by GrindstoneLZX** [microsoft/BotFramework-Composer#7965]
## Describe the bug

I meet an issue, when I try to press [Show code], it only shows [Something went wrong] error and is always showing [Loading...].
Some other panel have similar issue.
Could you take a look? Thank you!

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Bot responses'
2. Click on 'Show code'

## Screenshots

![image](https://user-images.githubusercontent.com/18130064/120280374-3018ce80-c2ea-11eb-8527-b13ea265d23f.png)

**Comment by zhixzhan** [comment]
@GrindstoneLZX when you open the browser console, did you see this js load error ?
![image](https://user-images.githubusercontent.com/49866537/120288255-96a1ea80-c2f2-11eb-8fe0-bc16b3e2f14d.png)

**Comment by srinaath** [comment]
@GrindstoneLZX Are you running Composer inside a virtual machine?

**Comment by GrindstoneLZX** [comment]
Hello, thank you for your reply!
@zhixzhan  Yes, I can see the error. Here is my screen shot:
![image](https://user-images.githubusercontent.com/18130064/120419474-25674380-c395-11eb-9e7d-c0ee3316c689.png)

@srinaath Hello, I am running on my local desktop computer, not a virtual machine.
