### ISSUE TITLE
"Hand off to an administrator" feature with provisionComposer.js generates faulty resources

### ISSUE THREAD

**Issue by Kai-Wen** [microsoft/BotFramework-Composer#7966]
**The resources generated with provisionComposer.js seems buggy**
[How to manually provision Azure resources for your Composer project](https://github.com/microsoft/BotFramework-Composer/tree/main/Provisioning#how-to-manually-provision-azure-resources-for-your-composer-project)

Example command:
node provisionComposer.js --subscriptionId=<subId> **--name=kevin-azbot-handofftest** --appPassword=<pswd> --location=japaneast **--resourceGroup=kevin-testRG2** --createLuisResource=false --createLuisAuthoringResource=false --createCosmosDb=false --createStorage=false --createAppInsights=true --createQnAResource=false

JSON output:
{
  "name": "kevin-azbot-handofftest",
  "environment": "dev",
  **"hostname": "kevin-testRG2",**
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "---------------------------"
    },
    "MicrosoftAppId": "-----------------------------------",
    "MicrosoftAppPassword": "--------------------------------"
  },
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "kevin-testRG2",
  "botName": "kevin-azbot-handofftest",
  "region": "japaneast",
  "subscriptionId": "---------------------------------------",
  "tenantId": "----------------------------"
}

1. Resource names are not formatted  properly:
Expected resource name: the same as bot name
Current resource name: **resource group** name
![image](https://user-images.githubusercontent.com/28392630/120276304-1a54da80-c2e5-11eb-9905-9d7de72b38b3.png)

2. Host name is registered with **resource group** name as well
Expected message endpoint: https://<bot_name>.azurewebsites.net/api/messages
Current message endpoint: https://<resource_group>.azurewebsites.net/api/messages
![image](https://user-images.githubusercontent.com/28392630/120276612-80d9f880-c2e5-11eb-878b-eaed80abb61d.png)

## Version

Bot Composer v2.0 / provisionScripts.zip #7563

**Comment by srinaath** [comment]
@GeoffCoxMSFT  Could you take a look at this ticket?

**Comment by GeoffCoxMSFT** [comment]
@benbrown I see that the resourceGroupName is used repeatedly in the templates and throughout the provisioning JS code.  Let's chat about it when you are back.

**Comment by johnataylor** [comment]
@Kai-Wen thanks for reporting this issue, our team is looking into it.

**Comment by Kai-Wen** [comment]
> @Kai-Wen thanks for reporting this issue, our team is looking into it.

Any updates? Thanks

**Comment by GeoffCoxMSFT** [comment]
I'm still looking into it.  The templates were written awhile back, so I'm having to decipher them first.  I'll get back to you as soon as I find the root cause.

**Comment by GeoffCoxMSFT** [comment]
@Kai-Wen You can grab the provisioning script and template updates from this PR to try out locally or you can wait for a nightly composer build after this PR is in and pull it from there.

**Comment by Kai-Wen** [comment]
@GeoffCoxMSFT  
### provisionComposer.js

1. I think the "**-${environment}**" for "hostname" should not appear in the profile 
=> (Import existing resource in composer will fail)
2. Not sure about the "**-${environment}-**" in "luisResource"

![image](https://user-images.githubusercontent.com/28392630/122090383-4bcbbb00-ce3a-11eb-8ca9-cdd0d759d47b.png)
