### ISSUE TITLE
Azure bot framework composer new deployment authentication

### ISSUE THREAD

**Issue by riftek** [microsoft/BotFramework-Composer#7967]
when adding a new deployment. on authentication to deploy, composer cant find my email unless I put a false name and enter another email. of which authenticates but throws an error of the previous non existent name not being found.

Windows 10

I have filled in all the relevant data for importing existing resources.

here is the message I get when trying to use my work account
![image](https://user-images.githubusercontent.com/30284512/120430915-01493980-c378-11eb-9643-57d9c6b8994c.png)

**Comment by johnataylor** [comment]
@tonyanziano can you comment

**Comment by tonyanziano** [comment]
@riftek can you please include the following in your issue:

1. Screenshots of what you are seeing
2. Logs / Error messages
3. Reproduction steps (if possible)

**Comment by tonyanziano** [comment]
@riftek can you please follow these steps to enable debugging output in Composer, and then try to login again and reproduce this issue?

1. Open a shell / cmd terminal
2. Navigate to Composer's installation directory
3. run the following command `set DEBUG=composer*`
4. Start composer from the terminal `"Bot Framework Composer.exe"`

You should now see a lot of output in the terminal window while Composer starts up.

Please try to login and then once it fails, copy all of that output and paste it here.

**Comment by riftek** [comment]
Thank you.
we eventually sorted it out by creating a new bot and resources..
and we have to authenticate and deploy with a private microsoft account that needs to be linked with our work active directory.
mainly we could not get old azure bot to work with new azure.

**Comment by tonyanziano** [comment]
Great, glad to hear you got it resolved.
