### ISSUE TITLE
Multilingual Hero Card and Suggestions  not working in  Non English Locale

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#7969]
## Describe the bug
Can not show Hero Card and Suggestions in applied locale

## Version

Version:  2.0.0-nightly.247623.340809f
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Chrome
- [ ] Edge

## OS

- [ ] Windows

## To Reproduce

1. Go to Bot Dialog
2.Create a Hero card , select Locale other than english
3. Run the Bot , The text is not rendered in non english locale
4.  However non english locale works for text responses, adaptive cards.

## Expected behavior

Want to show suggestions and Hero Card also in Non english locale

**Comment by dmvtech** [comment]
Hi @aparnaji I believe this is a known limitation at this point. I will try and confirm that for you.

To make sure I have fidelity with exactly what you are doing; would you mind sharing your hero card and suggested actions? As well as your dialog, if possible. (`.lg` and `.dialog`)

**Comment by dmvtech** [comment]
@aparnaji I'm still not sure if the scenario is what you are experiencing, but I was able to get the following to work for Hero card and suggested actions for en-us and de-de locales.

## German

### Hero card
```
# SendActivity_lCvsFu()
-${HeroCard()}

# HeroCard()
[HeroCard
   title = BotFramework Heldenkarte
   subtitle = Wenn keine Option zum Erneuern Ihres Action Pack-Abonnements im Partner Center angezeigt wird, überprüfen Sie bitte den Status Der Partnerüberprüfung im Profil Ihrer Organisation:
   text = 1. Navigieren Sie zu Ihren Kontoeinstellungen. Wählen Sie organisation sr3 aus. Wählen Sie dann die Registerkarte "Legal", dann "Partner".

]
```
### Suggested actions
```
# TextInput_Prompt_i8ntdH()
[Activity
    Text = ${TextInput_Prompt_i8ntdH_text()}
    SuggestedActions = Erste | Zweite | Dritte
]

# TextInput_Prompt_i8ntdH_text()
- Was denkst du?
```

## English

### Hero card
```
# SendActivity_lCvsFu()
-${HeroCard()}

# HeroCard()
[HeroCard
   title = BotFramework Hero Card
   subtitle = If you do not see an option to renew your Action Pack Subsription in Partner Center, please check your partner verification status in your orgianization's profile:
   text = 1. Navigate to your account settings\r2. Select organization\r3. Then choose legal, then "Partner" tab.
]
```
### Suggested actions
```
# TextInput_Prompt_i8ntdH()
[Activity
    Text = ${TextInput_Prompt_i8ntdH_text()}
    SuggestedActions = First one | Second | Third
]

# TextInput_Prompt_i8ntdH_text()
- What do you think?
```

**Comment by dmvtech** [comment]
Hi @aparnaji Just checking in. Do the above suggestions work for you?

**Comment by aparnaji** [comment]
Yes it worked, Thanks

**Comment by dmvtech** [comment]
Great! Closing as resolved.
