### ISSUE TITLE
Child dialog not triggering function with a single user utterance

### ISSUE THREAD

**Issue by BellaDunnett** [microsoft/BotFramework-Composer#7970]
As it currently stands, it seems that it is not possible to enable a child dialog to check its triggers without a second user utterance. For example, if a user says 'I want to know the date my contract ends' this would match the intent recognized trigger #contractDetails on the main dialog. At this point, I can begin the child dialog Contract_Details. 

What I would like to then happen is that the user gets the response and conversation flow defined in the intent recognized trigger #contractDates. I do not want to use the 'Begin Dialog' trigger and ask the user to repeat their question about their contract.

Is there a way of doing this? It isn't a great user experience to have to ask the user to repeat themselves when they've already told the bot what they specifically want. I also don't fully understand the benefits of having separate LUIS models if I have to define every intent on the main dialog  as well. 

Additionally, if the user says something vague like 'I need information on my contract' then I would expect this to match my #contractDetails intent and then match the child trigger of the unrecognized intent Contract_Details. I could then build a dialog flow that asks the user to clarify their contract query. This also does not work as I require the 'Begin Dialog' trigger under the child dialog Contract_Details. 

![Screenshot 2021-05-27 at 17 49 00](https://user-images.githubusercontent.com/53485343/120329124-70c11980-c2e3-11eb-9706-aa0f0213662d.png)

**Comment by srinaath** [comment]
@jwiley84 Could you take a look at this ticket?

**Comment by srinaath** [comment]
Related https://github.com/microsoft/BotFramework-Composer/issues/5532

**Comment by lauren-mills** [comment]
Hi @BellaDunnett, you should be able to achieve the scenario you want by just deleting the beginDialog trigger.

**Comment by jwiley84** [comment]
@BellaDunnett does Lauren's solution work for you?

**Comment by BellaDunnett** [comment]
Hi @lauren-mills I've tried deleting the beginDialog trigger, but I then get no response from the bot. It seems to go to the correct child dialog and then get lost. The same happens if I have intent recognised triggers or an unknown intent trigger - they don't work if I've deleted the beginDialog trigger.

**Comment by lauren-mills** [comment]
I was able to get it working in a test bot. In your "Begin a new dialog" action, do you have the activityProcessed property set to false?

**Comment by BellaDunnett** [comment]
@lauren-mills Thank you! This fixed the issue. Thanks for your help.
