### ISSUE TITLE
Adaptive Cards as choice options in multi-choice prompt

### ISSUE THREAD

**Issue by AndreaPisc** [microsoft/BotFramework-Composer#7971]
I have searched around but cannot find a solution to my issue. 

I am trying to add adaptive cards as choices in the multi-choice prompt. IT seems to me that this is not possible.
Can anyone please confirm or otherwise explain how to add the cards accordingly?

As alternatives, i have used HeroCards so far. But the request is a carousel of Adaptive Cards.

Thank you in advance!

**Comment by anusharavindrar** [comment]
@AndreaPisc, can you elaborate more on what you are trying to do(maybe screenshots of what you have tried so far)? If you are looking for adding an adaptive card as a choice in the multi-choice prompt, [here](https://docs.microsoft.com/en-us/composer/how-to-send-cards?tabs=v2x#the-responding-with-cards-example) is the documentation which makes use of the Responding with Cards template where the Unknown intent trigger contains a Prompt with multi-choice action and incorporates cards into your bot.

**Comment by AndreaPisc** [comment]
@anusharavindrar thanks for replying. I have seen the documentation, and i am able to use adaptive cards as regular response. However, my issue is to have adaptive cards as choices in the multi-choice prompt. In the RespondingwithCards template, the Unknown trigger does incorporate the cards, but when the trigger is enabled, the user choices are displayed as numbered list
![image](https://user-images.githubusercontent.com/84070962/120660002-2ed0d880-c487-11eb-9659-95cd95a7b23c.png)
What if i want to create adaptive cards of each of this choices and prompt them in a carousel? I already tried HeroCards in structured choice, but real Adaptive Cards.
I hope this made my question a bit more clear. Thanks in advance for your help.

**Comment by anusharavindrar** [comment]
@AndreaPisc, what channel are you using? Also, can you elaborate on if you are trying to use Adaptive Card actions or Adaptive Card inputs?

**Comment by AndreaPisc** [comment]
@anusharavindrar sorry but i am not sure, what do you mean with channel? 
I am trying to use Adaptive Card with Action.Submit button. 

Currently, in the emulator, i have the following:
![image](https://user-images.githubusercontent.com/84070962/121325184-aed8c180-c911-11eb-82ac-cd8ead40beae.png)

But the goal is to know if it is possible to change the HeroCard choices in AdaptiveCards with an Action.Submit button.
I am not sure how else i can explain this :)

Thanks again for you help!

**Comment by v-kydela** [comment]
@AndreaPisc - A bot channel is the chat platform that's sending messages to the bot. Are you using Web Chat or Teams?

It sounds like you're saying you want a choice input in Composer to display an Adaptive Card instead of a hero card. Is that correct? Why do you want to use an Adaptive Card instead of a hero card?

**Comment by v-kydela** [comment]
@AndreaPisc - Are you still working on this?

**Comment by AndreaPisc** [comment]
@v-kydela Currently i am trying to design the chat in  Composer and work on it in Emulator. There is no platform yet.
Adaptive cards in multiple choice prompt was just a request from the customer. I was just asking if it was a possibility and how.
Hero cards are ultimately fine too.

You can consider this issue closed unless there is no other feasible option
