### ISSUE TITLE
Exported C# bots don't run using the default behaviors imposed by Composer

### ISSUE THREAD

**Issue by ryanisgrig** [microsoft/BotFramework-Composer#7973]
## Describe the bug

When I export a C# bot and use the default name `BOTNAME_export`, it fails to start out of the box because the .csproj file does not match the bot name.

## Version

Version:  2.0.0-nightly.247623.340809f
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create any bot
2. Export it and keep the default name with "_export" appended to it.
3. Extract the bot_export .zip file.
4. Open bot_export and start running.
5. The bot fails because it is looking for `bot_export.csproj` but the .csproj file was not renamed, I have to update the command in configuration.

## Expected behavior

A couple of options:
1. As part of the export flow, the `runtime.command` should update the .csproj with the new name.
2. When opening a bot, run a validation check that ensures the .csproj file has the same name as what is referenced in the command. If not, it shows up as a validation warning or part of the rocket pane?

## Screenshots
![image](https://user-images.githubusercontent.com/43043272/120360271-6be96f00-c2bd-11eb-80d2-9712cbdea780.png)

**Comment by tonyanziano** [comment]
@boydc2014 is this something STCA can take a look at?

**Comment by LeeParrishMSFT** [comment]
Closing for lack of update/progress.
