### ISSUE TITLE
Have intent recognizer interrupt a user prompt

### ISSUE THREAD

**Issue by Karric** [microsoft/BotFramework-Composer#7974]
I'm using Composer/Emulator/LUIS exclusively. I don't see a way to allow the recognizer to interrupt a user prompt.

Bot details:
- Bot has a trigger for "current time" LUIS intent
- This triggers a particular dialog
- I have the standard Welcome dialog configured too, which asks the user for their name.

Current Experience:
- Welcome event; bot asks the user their name via 'prompt for text'
- User responds by saying "what time is it?"
- If I validate the input (against prebuilt name entity) then it rejects the message above, asking for a valid name

Desired Experience:
- Ideally there'd be some way to bypass the prompt and just invoke the dialog attached to the 'current time' trigger as if the prompt wasn't there.

**Comment by lauren-mills** [comment]
Hi @Karric, there is a property called "allowInterruptions" under Other > Prompt Configurations that allows you to configure whether a prompt is interruptible or not. You can set it to true or false, or provide a more complex expression like "=turn.recognized.score > 0.8" for example, that gives you control over your interruption. You can also add an expression as a condition onto your OnIntent trigger that can give you more control over that trigger, such as requiring specific entities.

**Comment by thomas-chung** [comment]
Hi @Karric! Just wondering if you have tried the above suggestion and whether it helped.

**Comment by stevengum** [comment]
Thank you @Karric for filing the issue. I'm closing issue as a solution was provided via @lauren-mills' reply: https://github.com/microsoft/BotFramework-Composer/issues/7974#issuecomment-852409986.
