### ISSUE TITLE
How to parse JSON object using foreach loop on Bot Composer

### ISSUE THREAD

**Issue by jrdamiano** [microsoft/BotFramework-Composer#7975]
**Describe the solution you'd like**
When I get a JSON object from an HTTP API request I need to iterate through it to read/extract its values.

**Additional context**
I get JSON object containig LUIS response (attrached file JSON.txt) and I can display intents by using this expresion: ${jPath(dialog.resultadoLuis.content, '..intents')} but on trying to loop through it with foreach loop (attached screenshot) nothing happens :(

![image](https://user-images.githubusercontent.com/64700432/119829048-1d258900-befb-11eb-9143-46aaae0bc338.png)

[JSON.txt](https://github.com/microsoft/botframework-components/files/6554074/JSON.txt)

.

**Comment by lauren-mills** [comment]
Hi @jrdamiano, I believe the reason you can't loop through is because the intents property in the JSON you attached is an object, not an array. 

Are you required to use the HTTP Action, or are you just trying to get the full list of intents back from your LUIS recognizer?

**Comment by chrimc62** [comment]
@jrdamiano you can achieve this by adding a SetProperty where you set another properties value to `indicesAndValues($resultAdoLuis.content)`.  This will convert an object to an array of objects where each element has an `index` field for the key and a `value` field for the value. 
Ideally foreach you should be able to do this by using an expression as your foreach property, i.e. `=indicesAndValues($resultAdoLuis.content)`.  This is not possible today, but I created a tracking issue for that feature.  https://github.com/microsoft/botbuilder-dotnet/issues/5619

**Comment by jrdamiano** [comment]
@chrimc62 I have also found a way to convert object in array doing this into a SetProperty:
=foreach(dialog.resultadoLuis.content.prediction.intents, x, x.key)

Thanks for your help! I hope tracking issue for that feature is ready in short time ;)
