### ISSUE TITLE
Importing an existing QNA Maker KB

### ISSUE THREAD

**Issue by srinaath** [microsoft/BotFramework-Composer#7981]
Initial thoughts on the workflow 

1. An update to the Create a QnA Maker KB modal to provide a 3rd option (in addition to import from URL and start from scratch), to import from an existing KB. 

2. If the user chooses this option, they would be prompted to select a subscription / resource group / qna Maker resource (Reuse existing views from the Settings page for the QNA KB action and build on it to add a view to list the Kbs and download the content when choosing a KB) (this might prompt the user to authenticate)

3. Once we have the QnA subscription, we can get a list of KBs associated with it with a single API call (see Cognitive Services APIs Reference (microsoft.com)).

4. The user selects a KB and then we can import the existing content in .qna format with a single call -> e.g. https://westus.api.cognitive.microsoft.com/qnamaker/v4.0/knowledgebases/a39be546-b70a-4d04-91e9-72faf031fd42/Prod/qna?qnaformat=true.

The QNA portal API’s are available to fetch KBs in a subscription and pull the content as .qna format and persist them locally. 
In R14 the timeline is pretty tight to venture into any scenarios involving syncing between remote portal kb and local kb. The current understanding is the content in Composer would always trump what is in the portal as it would just write the local file contents into the remote portal without accounting for lastAccessed timestamp etc.

**Comment by SharmaHarsh7** [comment]
Also, there are few more issues I found:

1. No mechanism to get LUIS/QnA Maker portal changes from remote to local.
1. If multiple developers are working on same project and they change language models, the changes are getting overwritten.

**Comment by garypretty** [comment]
@srinaath we need to add appropriate telemetry to this feature.  Below are the changes I would like to us to make and events we need to add.

We already have events AddNewKnowledgeBaseStarted and AddNewKnowledgeBaseCompleted.  For the AddNewKnowledgeBaseCompleted event we need to add a custom property called 'source' and this should have one of 3 values - 'url' (if importing from a url), 'none' (if the kb is started from scratch) or 'kb' (if the content is imported from a kb).

I would like to add an additional event to this flow called AddNewKnowledgeBaseError which should be fired if an error occurs during the KB creation process (with a property 'error' containing the exception or error code if possible).

Then, for the new refresh content flow we should add two new events UpdateKnowledgeBaseStarted,  UpdateKnowledgeBaseCompleted and UpdateKnowledgeBaseError - again the completed event should have a property for the source.

Given I think both flows will utilize the same code, we need to be careful to fire the right events depending on if the user is creating vs updating.
