### ISSUE TITLE
Add rich text editor for QnA Knowledgebase

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#7982]
## Summary
QnAmaker.ai has a rich text editor for authoring answers. for parity. We are adding this feature exactly as is to the "Knowledge QnA)" page in Composer for parity.

## Reference

This is the experience in QnAMaker.ai:

https://user-images.githubusercontent.com/39317542/120389305-1c1c9f00-c2e1-11eb-97c7-9caf8f015ad0.mov

**Comment by hatpick** [comment]
this is a dup of #7932
