### ISSUE TITLE
Link selected bot activities between Web Chat and Log Panel

### ISSUE THREAD

**Issue by tonyanziano** [microsoft/BotFramework-Composer#7983]
**P0's**
- [x] Selecting an activity displayed in the Web Chat panel should inspect the activity in the log panel
- [x] Inspecting an activity in the log panel should select an activity in the Web Chat panel

This should resemble how the Emulator behaves.

**Comment by mewa1024** [comment]
Discussed offline with Tony, but for reference the design is to change the border to black, 2px thick for the message being inspected:
![image](https://user-images.githubusercontent.com/39317542/120720679-5b81f180-c481-11eb-9259-e456b27b8ea1.png)
![image](https://user-images.githubusercontent.com/39317542/120720757-794f5680-c481-11eb-8bee-dfc1e6f5ecd8.png)
