### ISSUE TITLE
Telemetry not logging Personal Information after publishing from V2.0.0 .

### ISSUE THREAD

**Issue by thrapai** [microsoft/BotFramework-Composer#7990]
## Describe the bug
After upgrading Composer to v2.0.0 I was no longer able to log Personal Information on App Insights. I need to log the _Question_ from LuisResult and the _fromName_ from BotMessageReceived.

As shown in the Documentation:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-analytics-queries?view=azure-bot-service-4.0#schema-of-bot-analytics-instrumentation

**What I used to get on v1.4.0:**
- BotMessageReceived Event:
![image](https://user-images.githubusercontent.com/61385201/120475294-d976c780-c3b1-11eb-9439-9b65ac00419f.png)

- LuisResult Event:
![image](https://user-images.githubusercontent.com/61385201/120467432-db885880-c3a8-11eb-9d41-f70de1cee5b8.png)

**Currently on v2.0.0**
- I am no longer able to get the information indicated with red in the above screenshots.
- BotMessageReceived Event:
![image](https://user-images.githubusercontent.com/61385201/120474592-0e364f00-c3b1-11eb-837b-1b8c29453474.png)
- LuisResult Event:
![image](https://user-images.githubusercontent.com/61385201/120468388-d4ae1580-c3a9-11eb-8b49-c2848a080dd5.png)

**Things I've tried:**
- I have added the ```logPersonalInformation``` property in appsettings:
```
{
   ...
    "telemetry": {
       "logPersonalInformation": true,
       "logActivities": true
   },
   ...
}
```
- I Also tried adding it in runtimeSettings:
```
{
   ...
   "runtimeSettings": {
      ...
      "telemetry": {
         "logPersonalInformation": true,
         "logActivities": true,
      },
      ...
   },
   ...
}
```
- The _instrumentationKey_ and _connectionString_ are correct.

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Enable logPersonalInformation for Telemetry.
2. Publish
3. Test the bot on Teams
4. View analytics on App insights

**Comment by tonyanziano** [comment]
@taicchoumsft or @tdurnford any thoughts?

**Comment by taicchoumsft** [comment]
Hi @thrapai , thanks for reporting this Composer bug, I can indeed repro this. 

The `=runtimeSettings.telemetry.logActivities` and `=runtimeSettings.telemetry.logPersonalInformation` settings are the right ones to set if you created a brand new bot in Composer 2.0.  

These two settings are somehow being stripped out only when publishing to Azure (locally these two settings should be preserved, so when testing locally telemetry appears to work).

A proposed workaround for now is to create a new file called `appsettings.production.json` in the `settings` folder of your project (the `production` word is special and used by default if you haven't set the `ASPNETCORE_ENVIRONMENT` on Azure, Composer does not modify this environment) , and [add](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.1) this:
![image](https://user-images.githubusercontent.com/61705609/120545214-3919a680-c3a3-11eb-90a8-08379984eb17.png)

`appsettings.production.json`
```json
{
  "runtimeSettings": {
    "telemetry": {
      "logActivities": true,
      "logPersonalInformation": true
    }
  }
}
```

**Comment by thrapai** [comment]
Thanks for your reply @taicchoumsft!

I confirm the ```"Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime``` is at version ```4.13.2```.

Indeed the settings are being stripped only when publishing to Azure. When testing localy on emulator, all the required information are logged properly.

**The proposed workaround solved my issue**. Everything is logged properly now. Thanks for your assistance!

**Comment by johnataylor** [comment]
Add Exempt label as we have a milestone for this.
