### ISSUE TITLE
build error when MicrosoftAppPassword contains a '|' symbol

### ISSUE THREAD

**Issue by Bolleman** [microsoft/BotFramework-Composer#7994]
## Describe the bug

Error occurred building the bot

Message:
Command failed: func settings add MicrosoftAppPassword WRh=@BqPlb0D:wvchm]u!y|H%JI
'H%JI' is not recognized as an internal or external command,
operable program or batch file.
Command:
func settings add MicrosoftAppPassword WRh=@BqPlb0D:wvchm]u!y|H%JI
Stack Trace:
Error: Command failed: func settings add MicrosoftAppPassword WRh=@BqPlb0D:wvchm]u!y|H%JI
'H%JI' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Output:
Killed:
Code:
255
Stderr:
'H%JI' is not recognized as an internal or external command,
operable program or batch file.

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

Electron distribution

## OS

Windows10

## To Reproduce

Add MicrosoftAppID and MicrosoftAppPassword to a bot and restart.  Build fails with error message above.  Based on the specifics of the error notification, I tried simply deleting the '|' character from the AppPassword and it builds fine.  Of course, this generates a 401 Unauthorized as you would expect.   This AD app registration was originally created during the creation of an Azure Bot instance.  This could just be coincidence, but when I created another Azure Bot instance with an automatically generated app registration it also generated another password containing a '|', which threw the same error.  However, when I create the AD app and client secret / app password separately, the passwords don't have this symbol, and accordingly work fine.   

## Expected behavior

No error.

**Comment by tonyanziano** [comment]
Hello @Bolleman ,

Thanks for reporting the issue. This has already been fixed via #7938 and should be available in the latest [nightly release of Composer](https://github.com/microsoft/BotFramework-Composer-nightlies/releases)
