### ISSUE TITLE
BotFramework Composer Crashes MAC when selecting to web chat or test in Emulator the Enterprise People Bot

### ISSUE THREAD

**Issue by AlexanderPBrown** [microsoft/BotFramework-Composer#7995]
Downloaded and followed the instructions to configure the Enterprise People Bot on MacBook Pro Bot Framework Composer. Bot will start successfully using the Run button. However, attempting to open Web Chat or Emulator to test will crash the entire computer.

## Version

Version:  2.0.0

Electron: 8.2.4

Chrome: 80.0.3987.165

NodeJS: 12.13.0

V8: 8.0.426.27-electron.0

## Browser

For Bot Framework Composer, I am accessing it through the application, not a browser directly.  I'm not sure if that means the Electron Distribution or not because I don't know what that is. 
- [ ? ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ x ] macOS

## To Reproduce

1. Download and configure EnterprisePeople Sample
2. Click on 'Run Bot' in upper right.
3. When Started, Click on the link to "Open Web Chat" or "Test in Emulator"
4. Notice Machine crashes / reboots.

## Expected behavior

Machine should not reboot/crash

## Additional context

It is possible that the permissions that require Admin Consent are not granted to the app.

**Comment by AlexanderPBrown** [comment]
After downloading Emulator 2.13 and running it independently, the "Test in Emulator" link does not Crash OS. The Web Chat still crashes it.

**Comment by tonyanziano** [comment]
Hey @AlexanderPBrown ,

When you say you upgraded to 2.13 of the Emulator I assume you mean 4.13. In that case, were you previously on 4.12?

I'm asking because the current version of Composer embeds version 4.12 of Web Chat, as does 4.12 Emulator. However, Emulator 4.13 embeds version 4.13 of Web Chat.

So maybe it is the version of Web Chat that is crashing your computer. If so, then perhaps we can just bump the version of Web Chat embedded in Composer from 4.12 to 4.13 and it will hopefully not crash your computer anymore.

**Comment by AlexBrownShi** [comment]
You are correct.  How can we upgrade the Web Chat in composer to v 4.13?  

APB

**Comment by tonyanziano** [comment]
We will have to make a PR to bump it up in the Composer source, and then it will be available in a nightly build.

Let me discuss the upgrade with my team and get back to you.

**Comment by AlexanderPBrown** [comment]
No rush, i think the emulator has the features i need.

**Comment by tonyanziano** [comment]
@AlexanderPBrown we are tracking this work in #8032 and will try to get it into the nightly builds some time this week for you to test.

**Comment by tonyanziano** [comment]
@AlexanderPBrown sorry for the delay.

There is a PR out (#8141) containing the version bump to Web Chat. Once that gets merged, the following nightly build will contain the fix and you should be able to use that version to verify the fix.

I will update this thread once that build is available.

**Comment by srinaath** [comment]
The PR has been merged. The lates nightly should have the bump in Webchat.
