### ISSUE TITLE
'YV50ic' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by SharmaHarsh7** [microsoft/BotFramework-Composer#8002]
## Describe the bug

I recently installed Bot Composer 2.0.

Whenever I try to create a bot project (c#) which has LUIS and/or QnA Maker integrated with it, it gives me below error:
![image](https://user-images.githubusercontent.com/8860380/120669070-ba109500-c4ac-11eb-8fc5-6e9a0ebef364.png)

## Version

2.0.0

## OS

- [ ] Windows

**Comment by tonyanziano** [comment]
@jwiley84 can you see if you can reproduce this? If so we can follow up with someone on the Runtime team.

**Comment by jwiley84** [comment]
I am unable to repro this with the following steps: 
- Brand new installation (as of this morning) of composer, and pre-existing LUIS keys I already had. 
- Brand new installation (as of this morning) of composer, and pre-existing QnA keys I already had. 

@SharmaHarsh7 , did you use pre-existing keys or did you create new resources with composer?

**Comment by SharmaHarsh7** [comment]
@jwiley84  I did a fresh installation again of Bot Composer latest version (2.0.0).

Created a new project with the 'Core Assistant Bot' template:
(For other first three templates it is working)

![image](https://user-images.githubusercontent.com/8860380/120886346-1d183e00-c60b-11eb-983b-2fd87ee53169.png)

Configured LUIS as below, tried both method (manual copy paste and Set up **Language Understanding button**):
![image](https://user-images.githubusercontent.com/8860380/120886413-71bbb900-c60b-11eb-85d0-53d7bbd2d38b.png)

did same for QnA Maker and App ID and Password (again tried auto retrieval and manual typing):
![image](https://user-images.githubusercontent.com/8860380/120886460-ae87b000-c60b-11eb-94e3-a2ba42914884.png)

After doing this all, when I run the project it creates models in the LUIS and QnA Maker portal but gives the error as I mentioned above after some time.

I have even updated the Powershell Core/DotNetCore and other NPM packages required

**Comment by SharmaHarsh7** [comment]
One more behavior I observed is that.. it works, if you create a new bot and create all the resources from bot composer only.

**Comment by srinaath** [comment]
@SharmaHarsh7 What happens if you try to start the bot using the dotnet command line commands? Does it throw the same error.

In addition, `YV50ic` can you confirm if this substring is a part of your LUIS key or Qna key or a portion of the LG template names?
![Screen Shot 2021-06-09 at 9 52 25 AM](https://user-images.githubusercontent.com/13004779/121396640-6cf74d80-c908-11eb-8e9b-16db16d9889c.png)

**Comment by SharmaHarsh7** [comment]
No, that string is not part of anything in the entire solution.

I too, initially thought the same and searched but that is not there, there are other strings with same length.

For command line, I will test and share the output with you.

**Comment by jwiley84** [comment]
@SharmaHarsh7 Have you been able to test this via command line?

**Comment by SharmaHarsh7** [comment]
@jwiley84  it is not working at all.

**Comment by dmvtech** [comment]
> it is not working at all.

@SharmaHarsh7 Can you share the command line that you tried? What error is it throwing when you try and launch the runtime from command line?

> One more behavior I observed is that.. it works, if you create a new bot and create all the resources from bot composer only.

Can you explain this part more? By resources you mean existing Azure resources (not existing LUIS applications and QnA KBs)?

**Comment by dmvtech** [comment]
Hi @SharmaHarsh7 Checking in. Can you help me with the questions above?

**Comment by dmvtech** [comment]
Closing due to lack of response. If you are still having issues and need assistance, please comment and give more info per the above questions.

**Comment by SharmaHarsh7** [comment]
The issue was because of NodeJS 12 when I tried with 14 it worked.
