### ISSUE TITLE
Multilingual lu editing issue

### ISSUE THREAD

**Issue by daveta** [microsoft/BotFramework-Composer#8003]
## Describe the bug

Users can't currently independently edit language specific .lu files.

For example, if I enter utterances for "English", and then switch to "Spanish", whatever I typed in "English" shows up in "Spanish".
If I then edit "Spanish", it also updates "English".

This occurs in the "Create" pane, and not the "User Input" pane.
![image](https://user-images.githubusercontent.com/6182197/120688253-bacb0c00-c457-11eb-9ec9-db02b28e07ff.png)

## Version

Version:  2.0.0-nightly.249166.11a45cf
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Add "Spanish" language by clicking "Configure"->Localization
2. While in "English" add some trigger phrases.
3. Switch to "Spanish"
4. Notice the English trigger phrases are present.  Delete them and add some Spanish phrases.
5. Switch back to "English".
6. Notice the English trigger phrases are gone, replaced by the Spanish phrases.

## Expected behavior

Be able to independently edit different locales.

**Comment by boydc2014** [comment]
@zhixzhan could you help take a look, looks like a bug, once we have the lu intent created, we shouldn't overwrite content anymore.

Note that, it could be an issue with this hoisted editor's state (rather than the underlying data).

**Comment by zhixzhan** [comment]
@boydc2014 fixed in #8009

**Comment by daveta** [comment]
Curious if automated test cases could be added?
