### ISSUE TITLE
Integral web chat is not consistent with locale nor giving correct language responses

### ISSUE THREAD

**Issue by dmvtech** [microsoft/BotFramework-Composer#8015]
## Describe the bug

When running webchat from within Composer on a secondary locale, it is not consistent on what is being used/returned. When set to German (Germany), the send box and timestamp are correct, but other responses are not. Running in Emulator with `de-de` works fine and as expected.

## Version

Version:  2.0.0-nightly.249166.11a45cf
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create bot with secondary language/locale.
2. Run bot and test with secondary language
3. Notice responses are not from correct language.
4. Test in Emulator with locale set and notice working as expected.

## Expected behavior

When running web chat under a certain language, bot should be using that locale and responses coming from that language.

### Failing in Composer web chat
![image](https://user-images.githubusercontent.com/43397658/120852037-89713f80-c52e-11eb-801d-4517fb4fce1b.png)

### Working in Emulator
![image](https://user-images.githubusercontent.com/43397658/120852096-9c840f80-c52e-11eb-990c-0eca25d47980.png)

**Comment by dmvtech** [comment]
Fixed as of:

```
Version:  2.0.0-nightly.255969.45d2dd7
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```

Thanks @srinaath

**Comment by srinaath** [comment]
thanks @dmvtech for checking.
