### ISSUE TITLE
Skill Not working when deployed using CI/CD Pipelines.

### ISSUE THREAD

**Issue by rahul-8437008949** [microsoft/BotFramework-Composer#8019]
When I deploy my skill directly from composer to azure Skill works fine and I can see my manifest at the URL for remote skill manifest. But when I deploy my skill using CI/CD Pipelines on the same resources I can see the changes I made to functioning the bot(the bot works fine) but Remote skill URL stops working(I cant see my remote manifest). Can someone help with this.

**Comment by rahul-8437008949** [comment]
@v-kydela @cwhitten can you help me with this please. Do I need to make changes in the pipeline to make the manifest work?

**Comment by luhan2017** [comment]
@rahul-8437008949, could you please try to copy the generated manifest/lu files to the wwwroot folder, then it can be accessed by url.

**Comment by rahul-8437008949** [comment]
Thanks @luhan2017 It Worked.
