### ISSUE TITLE
NodeJS - Error sending Cards - "Error: args[0].trim is not a function"

### ISSUE THREAD

**Issue by bosens** [microsoft/BotFramework-Composer#8020]
## Describe the bug

NodeJS bot to send a respond using Cards. 
Starting the bot using Web chat results with the message "bot encountered an error or bug", the trace reviles the message "Error: Error: args[0].trim is not a function {SendActivity_Greetings}  Error occured when evaluating 'Attachments=${json(SendActivity_Greeting_attachment)}"

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Chrome
- [ ] Edge

## OS

* Windows 10 Pro (20H2) x64

## To Reproduce

1. To ensure that the issue was not with my laptop setup, a clean laptop (Win10 Pro 64bit) was used. Installed NodeJS 14.17.0 and Bot Composer 2.0.0
2. Created a new NodeJS 'Empty Bot'  
3. Modified the generated Greeting "Send a response" from Text to add Attachments of 'ThumbnailCard'
4. 'Add new attachment' -> 'Create from template' -> 'Thumbnail card' - (updated required fields)
5. Started the bot and accessed it using the inbuilt Web Chat where the bot abends straightaway 
6. The error occurs for other cards 

## Expected behavior

Able to respond with cards

## Screenshots

![20210607-BotComposer-NodeJs-SendActivity-ThumbnailCard-Error](https://user-images.githubusercontent.com/14006974/120946452-e879c300-c77f-11eb-9330-119e9ecdf033.png)

## Additional context

The error occurs no matter the card type (Adaptive, Hero, etc.)

**Comment by srinaath** [comment]
@bosens Could you send the zipped assets of the bot for us to repro. In addition, are you able to see the same error on an Azure C# bot?

**Comment by stevkan** [comment]
@bosens, in addition to sending your zipped assets, can you also try the following? Using this setup, I was able to successfully send a thumbnail card using the Node Empty bot template.

**In Greeting trigger => Send a response**
```js
[Activity
    Attachments = ${ThumbnailCard()}
]
```

**In Bot Responses => Common**
- Add a new template
- Change the template name to "#ThumbnailCard"
- Click the menu options for the line (the three vertical dots) and select Edit
- Delete the default line of code, and copy and paste the below code into the editor window
    - _Please see my note at the bottom regarding a possible bug and how to avoid it_
- Run the bot. It should generate a card in Web Chat like the attached image I included
```js
[ThumbnailCard
    title = BotFramework Thumbnail Card
    subtitle = Microsoft Bot Framework
    text = Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.
    image = https://sec.ch9.ms/ch9/7ff5/e07cfef0-aa3b-40bb-9baa-7c9ef8ff7ff5/buildreactionbotframework_960.jpg
    buttons = Get Started
]
```

![image](https://user-images.githubusercontent.com/18403946/121252500-ecc7de00-c85c-11eb-9fb5-b752a758e6ae.png)

@srinaath, I encountered a possible bug while successfully performing the above. When I went into Bot Responses => Common and added a new template, I changed the template name then went to edit the template using the Edit option. I used Ctrl + A to select all the present text and pasted the above thumbnail code in its place. When I went to run the bot, I got the below error. Navigating back to Common and selecting Show Code revealed that the default "-TemplateValue" was still present. This line of code is not visible from the editor alone, only from Show Code. I deleted the line of code and was then able to run the bot without error.

> Empty_Bot_0_node.en-us.lg:[Error] C:\Users\Steven\source\Composer\Empty_Bot_0_node\Empty_Bot_0_node\bin\Debug\netcoreapp3.1\language-generation\en-us\common.en-us.lg line 1:0 - line 1:16: Unexpected content: ‘-TemplateValue’. Expecting a comment, template definition, import statement or option definition.


![image](https://user-images.githubusercontent.com/18403946/121253427-f271f380-c85d-11eb-8853-893736686af7.png)

**Comment by bosens** [comment]
> @bosens Could you send the zipped assets of the bot for us to repro. In addition, are you able to see the same error on an Azure C# bot?

@srinaath, No issues when using C#. Attached is the zipped file of the details requested

.

**Comment by bosens** [comment]
@stevkan reviewing your information I was able to overcome the issue by modifying the generated code in the **Send a response** by selecting the **Show Code** and removing the function call to 'json()' surrounding the template name. 

Generated:  
  [Activity
       Attachments=${json(SendActivity_Greeting_attachment)} 
  ]

Modified: 
  [ Activity 
       Attachments=${SendActivity_Greeting_attachment} 
  ]
