### ISSUE TITLE
Bot Framework Composer Create Azure Bot Error

### ISSUE THREAD

**Issue by joshchiang0309** [microsoft/BotFramework-Composer#8021]
## Describe the bug

Unable create new Azure bot 

## Version

Bot Framework Composer V2.0.0

## Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Bot Framework Composer V2.0.0'
2. Click on 'publish selected bot'
3. select "Create new resources" 
4. type all info after I get Error

## Screenshots

![thumbnail_e](https://user-images.githubusercontent.com/44658649/120965444-7c0abe00-c797-11eb-83fc-c36c6deedb61.png)
## Additional context

Bot Framework Composer Log
{
  "profileName": "PHDbot",
  "jobId": "45c5e34d-527f-4b46-9880-6259d413f348",
  "projectId": "41077.96056147765",
  "time": "2021-06-07T01:05:22.164Z",
  "log": [
    "Creating Azure resources...",
    "Checking the Existence of the Resource Group ...",
    "Creating Resource Group ...",
    "> Creating App Registration ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:255547:25)\\n    at createCustomizeError2 (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:255552:10)\\n    at BotProjectProvision.createApp (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:256989:17)\"}",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:255547:25)\\n    at createCustomizeError2 (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:255552:10)\\n    at BotProjectProvision.createApp (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:256989:17)\"}. See provision.PHDbot.log in your bot folder"
  ]
}

**Comment by srinaath** [comment]
@GeoffCoxMSFT Have you seen this error before?

**Comment by GeoffCoxMSFT** [comment]
The provisioning tried several times before failing.  I've tried reproducing, but I haven't seen it happen.  Without a network trace it is hard to know what the real error was (BTW - we are working on surfacing the real error in the next release).  It could be any of the operation timed out, there was a permissions problem, a resource with that name already existed, or some other networking error.

**Comment by mrivera-ms** [comment]
@joshchiang0309, if you can submit a network trace for further investigation, please reopen the issue.
