### ISSUE TITLE
Error on creating empty bot + cannot port older project over

### ISSUE THREAD

**Issue by Jin825** [microsoft/BotFramework-Composer#8022]
## Describe the bug

After installation of new version, am now unable to convert older projects to new version.
Am also unable to create a new chatbot from scratch, error message as shown below:

Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: `Command failed with ENOENT: npm root -g --prefix C:\Users\Me\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error spawnSync cmd.exe ENOENT`

## Version
![image](https://user-images.githubusercontent.com/44352353/120974826-289e6d00-c7a3-11eb-8120-e52007041214.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

After updating:
1. Go to 'Home'
2. Click on 'Create new' and create an empty bot
3. See error

## Expected behavior

Should have created an empty bot when starting from scratch.

## Screenshots

![image](https://user-images.githubusercontent.com/44352353/120975309-a82c3c00-c7a3-11eb-83fe-aeaa9254f2bc.png)

## Additional context

Am unsure if nodejs is the cause of issue: have tried to install latest version 14.17 but it does not seem to show in the versions listed in "About"

**Comment by srinaath** [comment]
@Jin825 Could you confirm if npm is in your PATH evironment variable?

**Comment by dmvtech** [comment]
The following PowerShell should give you a quick answer:

```powershell
$env:path.split(";") | select-string node
```

For me, this gives something like:
`C:\Program Files\nodejs\`

**Comment by Jin825** [comment]
Hi All, yes I got the same result as @cwhitten.

Personally have reinstalled node and input in npm into env variables before posting error

**Comment by dmvtech** [comment]
Thank you @Jin825 

We're still looking into this. Stand by.

**Comment by srinaath** [comment]
@Jin825 A couple things you can try to help us debug this issue.
1. Could you try doing a global install of any npm package using the `npm -g` syntax in you command line.
2. Could you try the above command that is erroring out directly in the command line and see if there is any difference between running as admin vs running as a user.

**Comment by dmvtech** [comment]
@Jin825 Are you able to do any of the above as suggested by Srinaath?

**Comment by dmvtech** [comment]
Hi @Jin825 Just checking in again. Please let me know if you still need assistance. And if so; what are the answers to the above questions.

**Comment by dmvtech** [comment]
Closing due to lack of response. If you are still having issues and need assistance, please try the above suggestions and let us know the findings.
