### ISSUE TITLE
HaTs telemetry items 

### ISSUE THREAD

**Issue by cwhitten** [microsoft/BotFramework-Composer#8029]
- [x] Mechanism for displaying a banner/notification in Composer to show to the users a prompt to complete a survey

- [x] Ability to dynamically generate the survey link parameters populated with values from composer usage (for example Version) & (survey link itself would be stable and hardcoded)

- [x] Ability to store some of the characteristics required for the trigger mechanism in local composer storage&nbsp;(e.g.&nbsp;count of sessions)

**Comment by beyackle** [comment]
This is nearly done - #8078 will address all of the issues at once because it was easier to just group them all together into a batch instead of trying to shuttle between fixing the cards or the URL generation separately.
