### ISSUE TITLE
Output format field error when accepting input numbers from the user

### ISSUE THREAD

**Issue by mmiele** [microsoft/BotFramework-Composer#8033]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Composer.
2. In a dialog prompt the user for a number.
3. In the **Output format** field in the drop down menu select **Write an expression**.
![image](https://user-images.githubusercontent.com/2974753/121258643-015ba480-c864-11eb-8ce0-3f9ffee85874.png)
4. Select the **fx** tab, then in the drop down menu select **Conversion->int**. 
![image](https://user-images.githubusercontent.com/2974753/121259158-99f22480-c864-11eb-9917-8ad99128fc12.png)
5. This produces the following format **=int(value)**.
![image](https://user-images.githubusercontent.com/2974753/121259510-1258e580-c865-11eb-9923-46542a946014.png)
6. Also an error is issued.
![image](https://user-images.githubusercontent.com/2974753/121259734-50eea000-c865-11eb-87b6-3472c4e5442e.png)

## Expected behavior
The Output field format should be **int(this.value)**. No equal sign and *value* prefixed with *this*.  See next screenshot.

## Screenshots

![image](https://user-images.githubusercontent.com/2974753/121260240-ebe77a00-c865-11eb-838d-79a9bc004f53.png)

## Additional context
Please see documentation PR: https://github.com/MicrosoftDocs/composer-docs-pr/pull/568.

**Comment by mewa1024** [comment]
to clarify,

`"outputFormat": "int(this.value)"`

is fine, but 

`"outputFormat": "=int(this.value)"`

causes the error. Is this the correct behavior? If so, then we will correct the UI to remove the instruction to "= Write an expression". And a validation error message below the field would be good too.

**Comment by boydc2014** [comment]
https://github.com/microsoft/BotFramework-Composer/pull/7722 should fix that

**Comment by srinaath** [comment]
@mewa1024 Actually this is not something to do with using the equals symbol. 
`"int(this.value)"` evaluated to a string whereas `"=int(this.value)"` evaluated to a number which our compiler complained.

The core reason for this is, the schema for outputFormat property in our current codebase uses ref to expression which expects a return type of string 

![Screen Shot 2021-06-10 at 10 00 11 AM](https://user-images.githubusercontent.com/13004779/121566768-aeecc600-c9d2-11eb-9f9c-cdae72bcb108.png)

Essentially, @lei9444 PR linked here checks if the type is of expression and checks if there is a oneOf in the schema. If there is none we can assume that the return type need not be forced to a string and it could return number or other data types.
