### ISSUE TITLE
Adding a new QnA Knowledge Base causes "QnA Build Error: undefined" failure

### ISSUE THREAD

**Issue by snapfisher** [microsoft/BotFramework-Composer#8049]
## Describe the bug

When creating a new QnA Knowledge Base from the Knowledge (QnA) Page, starting the bot causes an error: QNA Build: Undefined and the Knowledge base is not published.  This is a small sample knowledge base with just a few entries.  I can not get this to work at all.

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x ] Edge (Chromium)

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go into a working bot
2. Go to the knowledge base page, create a new knowledge base
3. Add a few questions and responses
4. Start the bot

Note: the QnA maker key was correctly entered in the publishing section

## Expected behavior

The bot should run, the knowledge base should be published

**Comment by tonyanziano** [comment]
@snapfisher in the settings / configuration tab, there is a input field where you need to enter your subscription key:

![image](https://user-images.githubusercontent.com/3452012/121564539-69c79480-c9d0-11eb-9437-869a54ae5eac.png)

Have you done this?

**Comment by snapfisher** [comment]
Yes.  The only thing strange, is that after this, I decided that I would just create the KB in QnA Maker and import it – just so I can move forward.  The QnA resource gave me an error that there were “no endpoint keys found”, which is odd because the resource has been in existence for months and months.

I’m going to start over, with a new resource.  Add QnA capability to a new bot, vs. the existing one – which, BTW, was a composer V1 bot which was auto-converted, if that makes any difference.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by snapfisher** [comment]
Starting from scratch, with a new bot (core + QnA) and a new QnA service in Azure, it seems to work fine.  So, either:

1. It was a problem with the QnA resource (???, but there was an issue)
2. It had to do with the conversion from V1 composer bot to V2 composer bot
3. The bot was never integrated correctly with the QNA template when it was created, which was months and months ago.

I no longer have the QnA resource, but if you want to see the bot itself, I can pass it over to you internally.

I think -- even if determining what occurred is fruitless -- there are two definite takeaways:

1. Error: Undefined is bad.  That should never happen
2. There is not good documentation on how you would convert a composer bot that was not integrated with QnA into one that is integrated.  I read the docs and thought the KB should just magically be published.

**Comment by tonyanziano** [comment]
@snapfisher Thanks a lot for the detailed info! Glad to hear you got around it. We will investigate and see if we can figure out what happened, or at the very least reevaluate the documentation.

**Comment by anusharr** [comment]
We reviewed the docs and figured that the issue was most likely something to do with how the existing bot was configured.
