### ISSUE TITLE
Composer needs to support AAD Cert auth with Luis model

### ISSUE THREAD

**Issue by praveenvavilla** [microsoft/BotFramework-Composer#8052]
Hi,

Since Luis added support for AAD App auth with Luis model, can you please add support in composer to query Luis using AAD App Auth instead of using Luis key . this will avoid incidents due to key expiry 

Thanks

**Comment by boydc2014** [comment]
Note: the prerequisites for this issue is for ABS to support LUIS auth with AAD.

**Comment by OEvgeny** [comment]
Closing as LUIS is on the path to deprecation
