### ISSUE TITLE
Create a bot project page has inconsistent UI

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#8053]
## Describe the bug

The instructions on the page reference a description field that is...missing, apparently.

## Version

Version:  2.0.0-nightly.250890.7a45a55
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Select **Create new** (+) on the home page.
2. Choose a template, such as the C# **Core Bot with Language** and select **Next**.
3. See error: instructions read, "Specify a name, description, and location for your new bot project." However, there is no longer a description field on this page.

## Expected behavior

The page and the instructions are in sync.

## Screenshots

![image](https://user-images.githubusercontent.com/35047199/121601388-bc1dab00-c9fa-11eb-95c8-4e2e408b157a.png)

**Comment by cwhitten** [comment]
Hey @benbrown if this isn't on your radar for R14 can you move it to R15?
