### ISSUE TITLE
Monaco editor for LU should show an error if user tries to name an entity with a reserved name

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#8055]
## Describe the bug

In the Monaco editor for LU, I can define an entity with the same name as a LUIS prebuilt. LUIS doesn't allow you to have custom entities of the same name as prebuilt entities, so it would be good to show a validation message.

## Version

Version:  2.0.0-nightly.246170.8fa93
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to the trigger phrases and add a list entity using the same name as a LUIS prebuilt.
2. There is no indication that this name is reserved:

![image](https://user-images.githubusercontent.com/39317542/121607520-086de880-ca05-11eb-80f5-5ec32c66b10c.png)

3. You only see an error when you try to start the bot:
![image](https://user-images.githubusercontent.com/39317542/121607712-5aaf0980-ca05-11eb-86b5-07062f524e13.png)

## Expected behavior

Since we know that some names are reserved in LUIS, can we the LU language server show an error underneath the Monaco editor when an entity is defined with a reserved name? Similar to this:
![image](https://user-images.githubusercontent.com/39317542/121608222-59321100-ca06-11eb-98df-162b2a933c7a.png)
but with message text like 

> L10:5 - L10:9 Invalid entity name. The name "age" is reserved for a prebuilt entity.

**Comment by cosmicshuai** [comment]
I am trying to solve it in bf-lu package, once the PR is merge in cli repo. I will update the bf-lu version in Composer.
