### ISSUE TITLE
Publishing profile not finding directories

### ISSUE THREAD

**Issue by SomervilleA** [microsoft/BotFramework-Composer#8057]
When trying to create a publishing profile it is not finding my directories although my Azure portal has multiple directories

Showing no directories found when creating the publishing profile

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Add new publishing profile
2. Click on create new resource
3. Sign into Azure account

## Expected behavior

Directories to be available through the drop down menu

## Screenshots

![composer](https://user-images.githubusercontent.com/85746179/121689724-e041c080-cabc-11eb-9e1a-a93f42b2e04e.JPG)

**Comment by cwhitten** [comment]
Hi @SomervilleA, could there have been an issue when were signing-in in the application? This can happen when there was an error when attempting to sign-in. 

Could you close and re-open Composer, and attempt to create the publishing profile again?

**Comment by SomervilleA** [comment]
Composer has been closed and re opened multiple times with no difference.

I have tried multiple times to create the publishing profile but always returns the above result/error

**Comment by SomervilleA** [comment]
@cwhitten @GeoffCoxMSFT any update?

**Comment by SomervilleA** [comment]
@cwhitten @GeoffCoxMSFT any update?

**Comment by SomervilleA** [comment]
@cwhitten any update?

**Comment by anusharavindrar** [comment]
@SomervilleA, I just tried the steps on v2.0.0 and I didn't encounter any issues. Do you get any additional error on the Dev Console(Click on `View` > `Toggle Developer Tools`) when you try to add a new publishing profile and sign in to Azure? Also, one more thing to try is to re-install the v2.0.0 and see if you still get the error.
