### ISSUE TITLE
[Managed LU] Implement complicated sample bot with managed LU 

### ISSUE THREAD

**Issue by hibrenda** [microsoft/BotFramework-Composer#806]
Please reference 
https://github.com/microsoft/BotFramework-Composer/issues/733

https://microsoft.sharepoint.com/:w:/r/teams/ConversationalAI785/_layouts/15/Doc.aspx?sourcedoc=%7BD4BE6F56-9089-45C2-8815-192E66786A0C%7D&file=Language%20Understanding%20in%20Bot%20Framework%20Designer.docx&action=default&mobileredirect=true&cid=0d3c9409-ede4-4fac-8da0-7fcd9545b58a

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2284
