### ISSUE TITLE
Investigate cost and behavior of app/function start up when running npm install post-deployment

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#8061]
Reports from Orchestrator team is that the start up is very slow for web apps and functions.  They suspect this is due to the npm install occurring on the Azure box.  

This is part of figuring out the work to support deployments of bots that use Orchestrator where the target OS does not match the Composer OS.

**Comment by benbrown** [comment]
For the record, right now, the npm install does NOT occur on the Azure box.  We do it locally, then bundle the node_modules folder as part of the deployed artifact.
