### ISSUE TITLE
Add operating system choice when provisioning

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/BotFramework-Composer#8063]
The user needs to be able to select different operating system(s) for the web app or azure function rather than being forced to Windows.

- [x] Update the provisioning UI to capture OS selection
- [x] When provisioning leverage OS selection to provision the web app/function on the right OS.
- [x] Dynamically recommend an OS based on the bot project

**Comment by JaskeeratBedi-cmk** [comment]
Working design file here- https://www.figma.com/file/J3oIdXDmeBQbAe4a4PYbQc/Jaskeerat-s-files?node-id=5927%3A0

Attached is the proposed updated workflow. Needs some copy review with PM.
![Screen Shot 2021-06-17 at 8 39 47 PM](https://user-images.githubusercontent.com/67944302/122502788-29f24580-cfac-11eb-928a-39986b9553de.png)

**Comment by Dewain27** [comment]
@GeoffCoxMSFT  Design has been completed
https://www.figma.com/file/J3oIdXDmeBQbAe4a4PYbQc/Jaskeerat-s-files?node-id=5927%3A0

**Comment by JaskeeratBedi-cmk** [comment]
The Runtime Type selection needs to be preselected to the recommended runtime type. Based on team's feedback, Azure Web App is the recommended choice that needs to be pre-selected.

**Comment by GeoffCoxMSFT** [comment]
@JaskeeratBedi-cmk  - This is the wrong issue.  This is the OS one, not the runtime type one.  I'll find the other and reactivate :)
