### ISSUE TITLE
Missing state saving with BlobStorage in Node v2.0.0

### ISSUE THREAD

**Issue by Dan-Bai** [microsoft/BotFramework-Composer#8072]
I have BlobStorage configured in appsettings. I can see conversationstate blob files in storage but nothing for userstate. The conversationstate files only contain lastAccess property and an empty DialogStateProperty.dialogStack. The conversations are ran from emulator and webchat.

**Comment by anusharavindrar** [comment]
@Dan-Bai, can you elaborate more on how you have implemented Blob storage? If you could provide the repro steps, that would be helpful.

**Comment by Dan-Bai** [comment]
@anusharavindrar 
I created a new Node bot with template "Core Bot with QnA Maker".
Added a simple QnA element "hello:goodbye".
Added a help intent trigger which begins a new dialog that sends a text response.
In app settings under runtimeSettings.storage is set to BlobsStorage.
At root level, BlobsStorage is set with appropriate connection string and container name.

After running the bot a few times I can see emulator%2Fconversation%2F files in the container.
Inside the files I see _lastAccess and empty DialogStateProperty.dialogStack

**Comment by mrivera-ms** [comment]
@anusharavindrar, do you have any updates?

**Comment by v-kydela** [comment]
@Dan-Bai - Can you link to any documentation you've followed? Where did you learn to set `"BlobsStorage"` as the value for `runtimeSettings.storage`? Are you really using `BlobsStorage` rather than `BlobStorage`? How did you learn how to set the connection string and container name?

Also, can you explain what your expected behavior is? Do you expect the dialog stack to be populated even when you're not in the middle of a multi-turn dialog? Do you expect user state to be in the same container as conversation state?

**Comment by v-kydela** [comment]
@Dan-Bai - Are you still working on this?

**Comment by Dan-Bai** [comment]
@v-kydela I was digging through the source code and came across this [code in npm](https://github.com/microsoft/botbuilder-js/blob/fec4bfe6e6b6092d9303e49ef3197c1c1ca9b019/libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts#L147). I have verified that I'm using BlobsStorage. I learned setting the connection string and container name from looking through the code as well. I expected there to be a conversation state and user state file. I'm also using multi-turn dialog but have not seen the dialog stack being populated. From the code it looked like user state and conversation state are stored in the same container.

**Comment by v-kydela** [comment]
Thanks, @Dan-Bai. Given that what you're doing isn't documented, can you explain the last repro step in more detail? I need to know how you did this:

> At root level, BlobsStorage is set with appropriate connection string and container name.

**Comment by Dan-Bai** [comment]
@v-kydela After digging through this [code](https://github.com/microsoft/botbuilder-js/blob/fec4bfe6e6b6092d9303e49ef3197c1c1ca9b019/libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts#L147) I set runtimeSettings.storage to BlobsStorage. I noticed configuration is the root object, I created a new object "BlobsStorage" at the same level as runtimeSettings. Looking at this [line](https://github.com/microsoft/botbuilder-js/blob/fec4bfe6e6b6092d9303e49ef3197c1c1ca9b019/libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts#L151) I added and populated both properties to BlobsStorage. 

I noticed that the same storage container is used for both userState and conversationState from this [line](https://github.com/microsoft/botbuilder-js/blob/fec4bfe6e6b6092d9303e49ef3197c1c1ca9b019/libraries/botbuilder-dialogs-adaptive-runtime/src/index.ts#L140)

**Comment by v-kydela** [comment]
@Dan-Bai - Okay, this explains the process you went through to figure out how to implement Blob Storage since it's undocumented, but I still need to know what your appsettings.json ended up looking like. You say you made a "BlobsStorage" object at the root level. Does that mean your appsettings.json looked like this?

```json
{
  "customFunctions": [],
  "defaultLanguage": "en-us",
  "defaultLocale": "en-us",
  "importedLibraries": [],
  "BlobsStorage": {
    "connectionString": "",
    "containerName": ""
  },
```

Also, your repro steps don't mention your LUIS and QnA configuration, but when I create a core bot with QnA I see errors regarding a missing LUIS key, LUIS region, and QnA Maker subscription key. Did you put those in your appsettings.json as well?

Finally, I need to make sure I understand the problem you're describing. It sounds like you're reporting two problems in one. The first problem is that the conversation state doesn't contain the information it should, notably the dialog state. The second problem is that the user state doesn't even exist. Is that correct? If you're expecting user state to be created in your storage, what data do you expect to be written to user state?

**Comment by Dan-Bai** [comment]
@v-kydela My appsettings.json does look like that.

And yes, I added NLU credentials as well.

It could potentially be two problems. You are correct about those. From our userstate produced by v1.4.1 we are seeing *id*, *realId*, and *document* as part of the JSON object stored in userstate file.

**Comment by v-kydela** [comment]
@Dan-Bai - I've come to understand that your storage configuration is only meant to be added through the automatic deployment process and isn't meant to be configured manually. Do you still encounter the same problems when you leave the storage configuration out of appsettings.json until you let the deployment process add it for you?

@joshgummersall - Could you please see if there's a problem in the Node runtime concerning the blob storage configuration? The docs suggest that there are some differences in the different SDK's regarding blob storage classes: https://docs.microsoft.com/azure/bot-service/bot-builder-howto-v4-storage#blob-storage-implementation

**Comment by Dan-Bai** [comment]
@v-kydela By automatic deployment are you referring to starting the bot from Bot Composer, publishing the bot to Azure, or deployment with Azure DevOps? I still have the same problem when starting from Bot Composer, before I added the BlobsStorage configurations I was not getting any files in storage. After adding the configuration I started to see partial filled conversationstate files. My team is not publishing to Azure from Bot Composer and not using Azure DevOps either.

**Comment by v-kydela** [comment]
@Dan-Bai - I'm talking about [this](https://docs.microsoft.com/composer/how-to-publish-bot#create-new-azure-resources):

![image](https://user-images.githubusercontent.com/41968495/123676047-47b77a00-d7f8-11eb-9db6-937706e1e29c.png)

**Comment by joshgummersall** [comment]
@Dan-Bai, I just set up a brand new bot with Blob Storage. My (truncated for brevity) `appsettings.json` file looks like:

```json
{
  ...,
  "runtimeSettings": {
    ...,
    "storage": "BlobsStorage",
    ...
  },
  "BlobsStorage": {
    "connectionString": "DefaultEndpointsProtocol=https;AccountName=${_OMITTED_};AccountKey=${_OMITTED_};EndpointSuffix=core.windows.net",
    "containerName": "emptybot"
  },
  ...
}

```

I created a dialog that sets `user.foo` to `"bar"` on `Microsoft.OnUnknownIntent` like so:
```json
{
  "$kind": "Microsoft.OnUnknownIntent",
  "$designer": {
    "id": "mb2n1u"
  },
  "actions": [
    {
      "$kind": "Microsoft.SetProperty",
      "$designer": {
        "id": "74lYqi"
      },
      "property": "user.foo",
      "value": "='bar'"
    },
    {
      "$kind": "Microsoft.SendActivity",
      "$designer": {
        "id": "kMjqz1"
      },
      "activity": "${SendActivity_DidNotUnderstand()}"
    }
  ]
}
```

And I can confirm that both conversation and user state are persisted properly in Azure:

<img width="1449" alt="Screen Shot 2021-06-28 at 11 36 23 AM" src="https://user-images.githubusercontent.com/1235378/123687308-a0d9da80-d805-11eb-9605-a371bc5d7152.png">
<img width="977" alt="Screen Shot 2021-06-28 at 11 36 32 AM" src="https://user-images.githubusercontent.com/1235378/123687318-a505f800-d805-11eb-89e0-640a902855fc.png">
<img width="927" alt="Screen Shot 2021-06-28 at 11 36 38 AM" src="https://user-images.githubusercontent.com/1235378/123687330-a9caac00-d805-11eb-81f9-5da71b7b54ec.png">

**Comment by Dan-Bai** [comment]
@v-kydela We aren't provisioning the from Bot Composer, it's done through our own terraform scripts. 

@joshgummersall Thank you for the information, I will double check. What would I need to do to populate the dialogstack field in conversationstate?

**Comment by Dan-Bai** [comment]
@joshgummersall  @v-kydela Thank you for the help
