### ISSUE TITLE
Add comment fields to each action and dialog

### ISSUE THREAD

**Issue by Clooney24** [microsoft/BotFramework-Composer#8074]
I want to comment my actions and dialogs in dialog designer as I comment code in c#. 

I would like to have an text input at each action and dialog to store those comments without any impact on bot behaviour, just text, so I can store explainations to help other team members understand what this action is for or what problem it solves because it's not always clear why a special condition is asked or a special property is set

**Comment by cwhitten** [comment]
Hi @Clooney24 - the team is working on implementing a feature that enables this. We anticipate the first version of this shipping in our next release (July 2021).

This is tracked here: https://github.com/microsoft/BotFramework-Composer/issues/7977

**Comment by cwhitten** [comment]
Closing this. Please follow #7977
