### ISSUE TITLE
Default SKU for QNA Maker Search Service is S0 and burns through MSDN credits

### ISSUE THREAD

**Issue by bluechiperic** [microsoft/BotFramework-Composer#8076]
Problem: Default SKU for QNA Maker Search Service is S0 and burns through MSDN credits

Solution: Default search service SKU to Free

The Bot Framework composer creates the QNA Maker Search service with a standard SKU by default (which runs at $250/month).  It would be great if it gave the option to specify which SKU you wanted, or defaulted to the Free SKU since you can't downgrade the service without deleting it and re-creating it.  Most deployments from the composer app will be for development environments, and it burns through the MSDN benefit rather quickly! :-)

**Comment by bluechiperic** [comment]
The Bot Framework composer creates the QNA Maker Search service with a standard SKU by default (which runs at $250/month).  It would be great if it gave the option to specify which SKU you wanted, or defaulted to the Free SKU since you can't downgrade the service without deleting it and re-creating it.  Most deployments from the composer app will be for development environments, and it burns through the MSDN benefit rather quickly! :-)

**Comment by Dewain27** [comment]
The publishing profile defaults to S0 as there are limitations that can happen with doing F0 by default.  When provisioning for local development the default is F0.  So, this is by design.  You can change the setting in the Azure portal post provisioning and change the pricing tier to F0 if desired.  Just be aware that you will have a maximum of 3 KBs for the service.

**Comment by Dewain27** [comment]
Also, most of the cost is tied to the Search service, however you can use another search service instance for your QnA Maker instance. Here is an article to show you how to do this:
https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/configure-qna-maker-resources?tabs=v1
