### ISSUE TITLE
JPath is failing with '?'

### ISSUE THREAD

**Issue by jamalsia** [microsoft/BotFramework-Composer#8081]
## Describe the bug
i was following the JPATH documentation:
`jPath(jsonStr, path)`

using JPATH is failing while the path is condition:
`=jPath(dialog.product_users, "$.content[?(@.standardAccountUPN ==='my.user@email.com')].standardAccountUPN")`

value:"DialogContextError: $.content[?(@.standardAccountUPN ==='my.user@email.com)].standardAccountUPN is not a valid path + Error: Unexpected token "?""

## Version

1.4.1 
## Browser

- [ ] Electron distribution
- [ x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

if I use 
$.content --> is ok
but if I use :
$.content[?(@.standardAccountUPN ==='my.user@email.com')].standardAccountUPN --> fails with error

value:"DialogContextError: $.content[?(@.standardAccountUPN ==='my.user@email.com)].standardAccountUPN is not a valid path + Error: Unexpected token "?""

the JSON in dialog.product_users is:
`{
  "headers": {
    "connection": "close",
    "content-encoding": "gzip",
    "content-length": "3073",
    "content-type": "application/json; charset=utf-8",
    "date": "Tue, 15 Jun 2021 10:24:24",
    "request-context": "appId=cid-v1:34374a3a-b72f-40f5-b94d-64cc0a66f783",
    "vary": "Accept-Encoding",
    "x-cache": "CONFIG_NOCACHE",
    "x-powered-by": " Awesomeness ;), ASP.NET"
  },
  "statusCode": 200,
  "reasonPhrase": "OK",
  "content": [
    {
      "key": "uyj4967-wdfs-dfaf-fddfsf-xxxxxx_ProductMaho",
      "text": "my name",
      "objectId": "xxxxxxx-bbbbb-dddddd-yyyyy-xxxxxxxxxxx",
      "firstName": "my",
      "lastName": "user",
      "fullName": "my.user",
      "email": "my.user@email.com",
      "standardAccountUPN": "my.user@email.com",
      "status": "OK",
      "userAccess": []
    },
    {
      "key": "bbbbbb-hoiu-dfaf-ioiwfd-xxxxxx_ProductMaho",
      "text": "my2 name",
      "objectId": "xxxxxxx-bbbbb-dddddd-yyyyy-xxxxxxxxxxx",
      "firstName": "my2",
      "lastName": "user",
      "fullName": "my2 user",
      "email": "my2.user@email.com",
      "standardAccountUPN": "my2.user@email.com",
      "status": "OK",
      "userAccess": []
    }
  ]
}`

## Expected behavior

JPATH should return the value as [Azure JPATH](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#jPath) and tested by Eg : https://jsonpath.com/ validator

## Screenshots
setting the json property 
![image](https://user-images.githubusercontent.com/25248608/122041001-623d2c80-cdd0-11eb-9038-bc0e778ae2f8.png)

setting the json JPATH rule:
![image](https://user-images.githubusercontent.com/25248608/122043946-d5946d80-cdd3-11eb-8451-96d3b9fb588e.png)

error when running:
![mkg](https://user-images.githubusercontent.com/25248608/122099779-4d7d8a80-ce0a-11eb-9fac-a7b425ac15bb.png)

the result is valid as it was tested in jsonpath . Valid result in jsonpath:
![image](https://user-images.githubusercontent.com/25248608/122040927-4e91c600-cdd0-11eb-8108-8190c5bba47d.png)

**Comment by cosmicshuai** [comment]
Due to the gap between JavaScript and C#, the query path in jpath are different, in JS, you should write
```
jPath(dialog.product_users, ".content{.standardAccountUPN === 'my.user@email.com'}.standardAccountUPN[0]")
```
This will achieve the same result.

**Comment by jamalsia** [comment]
thank you ! @cosmicshuai

**Comment by jamalsia** [comment]
thank you ! @cosmicshuai
