### ISSUE TITLE
unable to return property as a multiple choice option

### ISSUE THREAD

**Issue by jessthorne** [microsoft/BotFramework-Composer#8084]
Whilst using the Prompt with multi-choice feature, i am unable to call properties previously set as options. The value is not being returned. 

Steps to reproduce the behaviour: 
1. create a multiple choice response. text: I have found several products on your account. Which one are you interested in setting up a repayment plan for?
2. create user input choice using the simple choice feature. choice should be: ${conversation.productCurrent[0]} and ${conversation.productCurrent[1]} (note these values were set at the start of the dialog. ${conversation.productCurrent[0]} =="Mobile" ${conversation.productCurrent[1]} == "Broadband"
3. test it
4. see error (screenshots attached)

Excepted behaviour: 
able to call back the properties as a user input

<img width="392" alt="Screenshot 2021-06-15 at 14 30 30" src="https://user-images.githubusercontent.com/49563377/122062143-0af68680-cde7-11eb-9256-5fd060590ca8.png">
<img width="375" alt="Screenshot 2021-06-15 at 14 30 20" src="https://user-images.githubusercontent.com/49563377/122062147-0c27b380-cde7-11eb-8d26-790b6f61b04c.png">
being able to add multiple different conditions to one value

**Comment by dmvtech** [comment]
Hi @jessthorne This is a limitation with choice prompts. Specifically with **Simple** or **Structured** choices.

What you need to do is use an _expression_. Simply, you can just call that array such as:
`=${conversation.productCurrent}`

Example:
![image](https://user-images.githubusercontent.com/43397658/122132966-b1935500-cdf0-11eb-96c4-97dd3b67da9b.png)

You can of course be more dynamic/thorough with it and put it in a [template](https://docs.microsoft.com/en-us/azure/bot-service/language-generation/language-generation-structured-response-template?view=azure-bot-service-4.0) if needed.

**Comment by jessthorne** [comment]
Hi, thank you for your response. when i follow this pattern i get a warning (see attached) 
<img width="1210" alt="Screenshot 2021-06-16 at 17 22 09" src="https://user-images.githubusercontent.com/49563377/122257019-816ab580-cec7-11eb-872d-4231bc409eec.png">

**Comment by dmvtech** [comment]
Looks like your property is just text (`test`). Needs to be an array.

![image](https://user-images.githubusercontent.com/43397658/122268013-69c40a80-ce90-11eb-9663-48f092118c19.png)

![image](https://user-images.githubusercontent.com/43397658/122268057-77799000-ce90-11eb-8281-26c1963fe5f2.png)

```json
        {
          "$kind": "Microsoft.SetProperty",
          "$designer": {
            "id": "KM6BUY"
          },
          "value": [
            "Mobile",
            "Broadband"
          ],
          "property": "conversation.productCurrent"
        },
```

**Comment by dmvtech** [comment]
@jessthorne I'm closing this as it seems that it answers your question/situation. If not, please le us know.

**Comment by jessthorne** [comment]
Thank you - is it possible to have 2 options calling the stored property and one being text? 
e.g. 
![Screenshot 2021-06-18 at 16 15 01](https://user-images.githubusercontent.com/49563377/122582954-a63e6480-d050-11eb-8b9a-e03c66e901d3.png)

Thanks!

**Comment by dmvtech** [comment]
Yes. You would need to use [templates](https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lg-file-format?view=azure-bot-service-4.0#templates) and [adaptive expression functions](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0) to accomplish that.

**Comment by jessthorne** [comment]
@dmvtech i am unable to make ${conversation.MSISDN.product_list} appear in different buttons, is this possible?

![Screenshot 2021-06-25 at 17 27 36](https://user-images.githubusercontent.com/49563377/123457867-46aa0100-d5dc-11eb-912f-479e3e0ae457.png)
![Screenshot 2021-06-25 at 17 25 22](https://user-images.githubusercontent.com/49563377/123457869-47db2e00-d5dc-11eb-9daa-27415115d881.png)
