### ISSUE TITLE
Do not allow multiple identical triggers

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#8089]
## scenario
Composer allows one to specify multiple identical triggers. 
There's no value and it can lead to user confusion. 
Add validation to prevent that.

## version
Version:  2.0.0-nightly.251679.4774893
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## visual

![multitrigger](https://user-images.githubusercontent.com/8867670/122118340-c2d26680-cddc-11eb-9db3-e9c47fcffdbf.png)

**Comment by mkfah809** [comment]
is there any way to go from greeting trigger, to Test trigger directly?
