### ISSUE TITLE
FNF: "Dialog interface" section has nonstandard use of 'More' control (...)

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#8111]
Version
![Screen Shot 2021-06-16 at 10 40 27 AM](https://user-images.githubusercontent.com/48503434/122268004-67fa4700-ce90-11eb-844d-71ecef143c93.png)

Template: Core bot with language
Menu item:  Create
Area: property pane section, 'Dialog interface'

The default for input/output is empty
When adding a new input, 3 fields appear and one, poorly aligned triple dot icon with a single action: Remove
Typically, triple dot menus apply to the (single) field it is associated with.
If a single action applies to more than one thing, it should visually indicate that.

Note: maybe there will be more then 1 item (remove) in the menu when adding multiple inputs, but I cannot test that as the 'new' button is not working for me.

![Screen Shot 2021-06-15 at 11 38 52 AM](https://user-images.githubusercontent.com/48503434/122268581-14d4c400-ce91-11eb-9b2e-bc62088af59a.png)

**Comment by tdurnford** [comment]
@mareekuh Since this creates an object, you have to set the key before you can add another item. All keys must be unique, so we cannot add two items with the same key.

**Comment by mewa1024** [comment]
(needs a new design)

**Comment by mareekuh** [comment]
Agreed. (-:

**Comment by mewa1024** [comment]
(changing the title to shift emphasis on the "Dialog interface" section of the UI, rather than the ...)
