### ISSUE TITLE
Package Manager filters should be consistent

### ISSUE THREAD

**Issue by sgellock** [microsoft/BotFramework-Composer#8119]
## Describe the bug
We have two community filters available in package manager.  They are:
community. packages
JS community packages

We should use the ".NET" prefix for the .NET community packages filter name.  So the drop down would have:
.NET community packages
JS community packages

For extra credit, I would advocate the the "JS community packages" should actually be "JavaScript community packages"

## Version
Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser
- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch composer
2. Create a new or open an existing bot project
3. Navigate to package manager
4. Expand the package manager filter dropdown
5. Note naming inconsistencies mentioned above.

## Expected behavior
If we are going to use programming language designations for the filters, and I believe we should, we should use them consistently.

**Comment by clearab** [comment]
The additional filters on package feeds have been removed.
