### ISSUE TITLE
unable to create logic to return a certain number of cards based on the output of an API

### ISSUE THREAD

**Issue by jessthorne** [microsoft/BotFramework-Composer#8124]
I am calling an API where i get a set of information back as an object (e.g. screenshot)
<img width="475" alt="Screenshot 2021-06-17 at 18 01 55" src="https://user-images.githubusercontent.com/49563377/122442115-20f67980-cf96-11eb-924a-568c1efe0499.png">
with the value:  
"bill_number": "2",
i then want to create logic that means because 2 instances of bills have been returned from the API (because thats the value of "biill_number") the next response from the bot should be 2 cards (in a carousel) with each card displaying different pieces of information: card 1 to display the values of bill number 1 and card 2 to display the values for bill number 2 

similarly if the value of "bill_number": "2", returned when calling the API again was 4, i want the logic to then create 4 cards 

I am unable to find the logic to create this. 

I am using the desktop version of Composer version 2.0.0 on macOS

**Comment by mrivera-ms** [comment]
@jessthorne, thank you for opening this issue. For product behavior, how-to, or general understanding questions, please use Stackoverflow. https://stackoverflow.com/search?q=bot+framework
