### ISSUE TITLE
OAuth input action's Text property has a mangled example value

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#8125]
## Describe the bug

Example value for the OAuth login action's Text property is mangled.

## Version

- v2.0.0 release (noticed in)
- 2.0.0-nightly.251925.4e0cf11 (also in the nightly)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot and add an OAuth prompt action to a trigger.
2. Look at the properties for the action.
3. Error: Notice that the example for the **Text** property reads `ex. Please sign in., y, z)`.

## Expected behavior

The example/watermark does not mangle the sample values from the schema file.

See the [OAuthInput.Schema](https://github.com/microsoft/botbuilder-dotnet/blob/449a89e71dde3b2967a6cda8456f5fe4c2693df4/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Dialogs/Microsoft.OAuthInput.schema#L25-L33) file:
```json
        "text": {
            "$ref": "schema:#/definitions/stringExpression",
            "title": "Text",
            "description": "Text shown in the OAuth signin card.",
            "examples": [
                "Please sign in. ",
                "=concat(x,y,z)"
            ]
        },
```

## Screenshots

![image](https://user-images.githubusercontent.com/35047199/122452350-06a0a980-cf5e-11eb-893f-b5dd13c4e761.png)

**Comment by mareekuh** [comment]
I agreed it's wrong - do you have a proposal for what it should be?
@cwhitten @Jeffders

**Comment by JonathanFingold** [comment]
I think this is an issue on the Composer side, in that when Composer renders the `example` array as a watermark it appears to be trying to expand the information as an expression instead of as a literal. Given the input, I'd expect the watermark to look something like:
```
ex: Please sign in., =concat(x,y,z)
```
Which ends up looking a bit confusing. However, adding quotes around the example values would be confusing in a different way.
```
ex: "Please sign in.", "=concat(x,y,z)"
```
This might be the least confusing, but would require more interpretation of the array on Composer's end.
```
ex: "Please sign in.", =concat(x,y,z)
```
I think this points to a design issue around examples for any property that takes an adaptive expression.

**Comment by mewa1024** [comment]
Can we show just the first example?

![image](https://user-images.githubusercontent.com/39317542/122618039-493bb200-d042-11eb-9de2-7f0386cc26bb.png)
 

I think of any the options for showing multiple examples are potentially confusing.

**Comment by JonathanFingold** [comment]
@mewa1024 - The source for the watermark comes from strings in the .NET SDK library (the .schema file). This is an example of a mangled watermark. There are probably others.

My guess is that requests for changes to the example values should be directed to the SDK team, but changes to how they are rendered should be directed to the Composer team.
