### ISSUE TITLE
Copy update: Replace Azure Hosting with App Service

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#8127]
![Screen Shot 2021-06-17 at 12 06 25 PM](https://user-images.githubusercontent.com/67944302/122458232-71ed7a00-cf64-11eb-8c11-fe131d30a59a.png)

Azure Hosting needs to be replaced with App Service as defined in the documentation here- https://docs.microsoft.com/en-us/composer/how-to-provision-azure-resources

**Comment by Dewain27** [comment]
![image](https://user-images.githubusercontent.com/18688053/122605880-ad0fac00-d03d-11eb-9bfa-9acaffa37e77.png)
See Design
