### ISSUE TITLE
Luis build failed: Cannot read property 'versionId' of undefined

### ISSUE THREAD

**Issue by t-yuchenqian** [microsoft/BotFramework-Composer#8132]
## problem
I suddenly failed to build my bot locally, but can still deploy it to the Azure. I'm unaware of what was changed. When I try to build the bot, I get this error:
```
Luis build failed: Cannot read property 'versionId' of undefined
```

## version
v1.4.1

## system
Windows 10

## settings
![image](https://user-images.githubusercontent.com/86090795/122502561-6f088d00-d029-11eb-9f72-9daccfbd57f2.png)

**Comment by anusharavindrar** [comment]
@t-yuchenqian, can you elaborate on the steps you are following to build your bot? Do you get any additional error on the Composer Dev tools( go to View > Toggle Developer Tools)? One more thing to try is to re install the v1.4.1 of Composer and give it a go or upgrade to the latest version and see if you still get the same error?

**Comment by t-yuchenqian** [comment]
@anusharavindrar, the steps I built my bot:
1. open the project.
![image](https://user-images.githubusercontent.com/86090795/123025267-f29cf200-d40c-11eb-9d36-ac9059fea0ae.png)
2. start bot. 
![image](https://user-images.githubusercontent.com/86090795/123025310-05172b80-d40d-11eb-9a2c-4bed17941c45.png)

Yes I got some additional errors in the Dev Tools, but it seems unrelated to this problem: 
![image](https://user-images.githubusercontent.com/86090795/123025590-64753b80-d40d-11eb-95b0-bae6add6151d.png)

I've tried reinstall the v1.4.1 composer, but the issue still exists. I'm afraid I can't upgrade to the latest version since it tells me that it will transform the project to another format.

My LUIS credentials should be alright, because I can deploy it to the Azure successfully.

**Comment by t-yuchenqian** [comment]
When I build the bot, I got a 400 error: 
![image](https://user-images.githubusercontent.com/86090795/123048133-a5cb1280-d430-11eb-91cf-d849ce36d061.png)
And the response is 
```
{"message":"Luis build failed: Cannot read property 'versionId' of undefined"}
```

**Comment by anusharavindrar** [comment]
@t-yuchenqian, are you making use of a custom runtime? If yes, then can you try and see if you can run the bot outside of composer? If not using a custom runtime, then can you make a copy of the entire bot folder & open the bot in the same 1.4.1 version and see if it still throws an error? One more thing to try is to clear out the local storage and see if the issue persists.

**Comment by t-yuchenqian** [comment]
Resolved.
