### ISSUE TITLE
Bot Composer Bot hand off to Microsoft Teams

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#8133]
Is there a way we can handoff Bot Composer bot to Microsoft teams chat so that the agent can chat from teams and end user can use Bot.

**Comment by mrivera-ms** [comment]
@aparnaji, thank you for opening this issue. For product behavior, how-to, or general understanding questions, please use Stackoverflow. https://stackoverflow.com/search?q=bot+framework
