### ISSUE TITLE
GCC: Import from PVA with PVA GCC tenant fails with "Something went wrong during import: Error: Request failed with status code 500"

### ISSUE THREAD

**Issue by aaronba** [microsoft/BotFramework-Composer#8134]
## Describe the bug

When trying to import an existing GCC PVA bot into Bot Framework Composer, the import does not succeed.
This works with a PVA Commercial bot.

POST /api/import/pva/authenticate?payload=% .. 200
POST /api/import/pva?payload= .. 500
[27528:0618/115620.576:INFO:CONSOLE(360)] "Something went wrong during import: Error: Request failed with status code 500", source: http://localhost:5000/static/js/15.8ccd0b2d.chunk.js (360)

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

Edge

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X ] Edge

## OS

- [ ] macOS
- [ X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'https://gcc.powerva.microsoft.us'
2. Open the bot 'test'
3. Select the down arrow and choose 'Open in Bot Framework Composer'
4. You should get a popup that says "This site is trying to open Bot Framework Composer"
5. Select 'Open'
The bot Framework Composer opens but the PVA Bot is not imported.

## Expected behavior

The bot Framework Composer opens and the PVA bot is imported so I can add dialogs and triggers etc.

**Comment by tonyanziano** [comment]
We need to add some code that checks for the GCC base URL and then point OneAuth to authenticate against the corresponding PVA GCC AAD app.

I'm working on it now.

**Comment by tonyanziano** [comment]
I've made changes to the Composer code to allow for this authentication path. We are waiting on PVA to give our 1P AAD app consent to access theirs.

My branch can be found here: https://github.com/microsoft/BotFramework-Composer/tree/toanzian/pva-gcc

**Comment by tonyanziano** [comment]
The authentication issue has been fixed, but there was a new, unrelated bug introduced into the tree in the last week that is breaking the import from PVA scenario.

We know what is causing the bug, and are investigating how to solve it.

**Comment by tonyanziano** [comment]
The other bug breaking the PVA import scenario should be fixed by #8181 and in tonight's nightly build, along with the GCC fix.
