### ISSUE TITLE
operation not permitted

### ISSUE THREAD

**Issue by anukrati1507** [microsoft/BotFramework-Composer#8137]
operation mkdir for bot formation not permitted

**Comment by anusharavindrar** [comment]
@anukrati1507, can you specify at which step you are getting the error(repro steps or screenshot)? Also, can you follow the bug template and provide all the needed information(bug description, composer version, browser, OS, repro steps)?

**Comment by anusharavindrar** [comment]
Closing the issue. Feel free to re-open if issue persists.

**Comment by fitprotracker** [comment]
Just FYI,  
I received this error on the first attempt to publish a bot. I got the error denied. 

then I tried to publish the second time and it went through.  

Video to show the error before starting second time.
https://share.fitprotracker.com/04uxg2p4
