### ISSUE TITLE
Local Issue Certificate Error

### ISSUE THREAD

**Issue by rprecioso** [microsoft/BotFramework-Composer#8138]
I am having an issue with the tool. This has been an issue even in the emulator and I think it's the same issue with this error.

`Could not load component list:Error https://schemas.botframework.com/schemas/component/v1.0/component.schema: unable to get local issuer certificate Error Microsoft.QnAMakerDialog: Cannot extend component because it is not included Error Microsoft.QnAMakerDialog: Cannot set property 'const' of undefined *** Could not merge components ***`

I honestly don't have any knowledge on the issuer certificate, I have done some googling already and not of them is helping. 

![image](https://user-images.githubusercontent.com/47111908/122660956-30eda380-d1b8-11eb-8e9e-e855aa86a2a2.png)

**Comment by dmvtech** [comment]
@rprecioso Are you able to browse to `https://schemas.botframework.com/schemas/component/v1.0/component.schema` in a browser from the same machine?

**Comment by dmvtech** [comment]
Closing as inactive. If you still are having issues, please comment on whether you can reach those schema URIs in a browser.
