### ISSUE TITLE
Search for 'Bot' in Azure Portal should put Azure Bot in first (vs 3rd) place

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#8152]
<img width="790" alt="Screen Shot 2021-06-21 at 11 02 13 AM" src="https://user-images.githubusercontent.com/48503434/122807473-78d7fd80-d280-11eb-913f-3450a2154741.png">

When searching for 'Bot', the Azure Web App bot comes first in the list- this one is incompatible with Composer and should be replaced by Azure Bot -> Azure Bot should be in first place.

(I know this should be in the Azure ADO but github tends to get more traction & response).

**Comment by garypretty** [comment]
Hi Marieke.  I agree with the idea here, but as you say above, this is not the right place for this issue, especially as the service folks are not very active in GitHub. Please instead start a thread with Andrea and I and we can take it from there.

**Comment by garypretty** [comment]
I started a thread @mareekuh
