### ISSUE TITLE
Update Open from ABS modal copy

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#8166]
## Describe the bug

The copy on the modal shown when you open from ABS needs to be updated.

![absopenmodal](https://user-images.githubusercontent.com/3900649/122963938-a905c600-d37e-11eb-931e-b4eae294d37b.png)

Please amend this copy to the following.

**Title:** Choose a bot project for your Azure Bot
**Subtext:** Use your Azure Bot resource with a new or existing bot project. You can publish your bot project directly to Azure, using the publishing profile created for you. Learn more.
**Option 1:** Create a new bot project
**Option 2:** Use an existing bot project

The learn more link should link to https://docs.microsoft.com/en-us/composer/quickstart-create-bot-with-azure (we probably need an aka.ms link for this if we don't already have one for use in Composer).

FYI @JonathanFingold as our docs will need to be updated following this change in R14 and the screenshots over there already look out of date anyway https://docs.microsoft.com/en-us/composer/quickstart-create-bot-with-azure.

**Comment by mewa1024** [comment]
Can the title say "Choose a bot project for your Azure Bot" (remove the "Create /")? There are a few places in the UI where we tell the user to choose something and among the choices is the ability to create a new thing.

@mareekuh for copy review

**Comment by mareekuh** [comment]
Oh I like that! Good idea!

From: mewa1024 ***@***.***>
Date: Wednesday, June 23, 2021 at 8:06 PM
To: microsoft/BotFramework-Composer ***@***.***>
Cc: Marieke Iwema ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/BotFramework-Composer] Update Open from ABS modal copy (#8166)

Can the title say "Choose a bot project for your Azure Bot" (remove the "Create /")? There are a few places in the UI where we tell the user to choose something and among the choices is the ability to create a new thing.

@mareekuh<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmareekuh&data=04%7C01%7Cmariekei%40microsoft.com%7C49ea0a8f4e464e19d88008d936bd0da2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637601007889431940%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C6itrHMojj8Qi0VCfI5ssf7bKeFi4%2B93FlF2K8uZWz4%3D&reserved=0> for copy review

**Comment by mewa1024** [comment]
For the subtext, possible to shorten a little? maybe like:

> Use your Azure Bot resource with a new or existing bot project. Later, you can publish your project directly to your Azure Bot resource by using the publishing profile we have created for you. Learn more

**Comment by garypretty** [comment]
Thanks @mewa1024 - good suggestions.

I have amended the title as per your comment and I have updated the sub copy, with a slight tweak from your suggestion, to 

_Use your Azure Bot resource with a new or existing bot project. You can publish your bot directly to Azure, using the publishing profile created for you. Learn more._

@srinaath please note the tweak in copy - I have updated the copy at the top of the issue for ease. Thanks.

**Comment by beyackle** [comment]
I've linked https://aka.ms/composer-abs-quickstart to that URL in the docs.
