### ISSUE TITLE
Wrong word in ABS create dialog

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#8170]
Seems like this should say "a new bot" instead of "a new conversation"

![image](https://user-images.githubusercontent.com/698939/122984704-28c96b80-d352-11eb-8cfe-39eeb8e5ed38.png)

**Comment by srinaath** [comment]
@mewa1024

**Comment by mareekuh** [comment]
@JonathanFingold  -  I used 'conversation' on purpose as the user has already created a 'new bot' in ABS, so creating another 'new bot' is confusing here. Do you remember what we landed on? I believe this was a discussion back and forth in Teams?

**Comment by mewa1024** [comment]
I think the wording in the description of #8166 was the final copy:

> Title: Choose a bot project for your Azure Bot
Subtext: Use your Azure Bot resource with a new or existing bot project. You can publish your bot project directly to Azure, using the publishing profile created for you. Learn more.
Option 1: Create a new bot project
Option 2: Use an existing bot project

**Comment by JonathanFingold** [comment]
@mareekuh I don't remember. My preference would be for accuracy over simplicity. I don't think we need to explain everything here, but the words we use should allow a user to search the docs and get a good hit. Searching on "conversation" in this context will not get you the search results you want.
