### ISSUE TITLE
Unable to get a value for KnowledgeBaseId from state - Emulator & Composer

### ISSUE THREAD

**Issue by jnair7291** [microsoft/BotFramework-Composer#8186]
Finally after clearing browser cache it worked - by @aparnaji 

you are testing your bot on emulator? how come clearing browser cache solved this issue? makes no sense to me. 

![image](https://user-images.githubusercontent.com/11803138/123244724-cca54980-d501-11eb-8705-ab886e0c6b4c.png)

Despite giving knowledgebaseid , endpointkey in composer advanced view setting, the bot does not pick up QnA from QnA maker. 

![image](https://user-images.githubusercontent.com/11803138/123245029-14c46c00-d502-11eb-9f2e-97a0a5c394a9.png)

_Originally posted by @aparnaji in https://github.com/microsoft/BotFramework-Composer/issues/6392#issuecomment-797666641_

**Comment by dmvtech** [comment]
This issue can happen by creating a bot using the '**Core Bot with QnA Maker**' template or by adding a QnA KB trigger, _without_ creating or authoring the KB with questions. If you create questions, this should work.

With Composer, there are two general approaches/options to using QnA:
1) Create and author your KB from Composer. This is the recommended approach at this time. This will allow to use the more robust and dynamic QnA intent, etc. This is documented here:
https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb?tabs=v2x#edit-a-knowledge-base

2) Use the 'Connect to a QNA Knowledgebase' action. While this is better for accessing a KB that is already in place/production, the limitation of this option is great. This is documented here:
https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot?tabs=v2x


As a workaround (if you need to use existing KB content), you can; export the questions from an existing KB and convert those to .qna for use and testing. Let me know if you need the steps to do that.

This behavior is in flux and work is being done to make this less painful and more clear and straightforward. Current work being done to import existing KB can be tracked here:
https://github.com/microsoft/BotFramework-Composer/issues/7981

Please confirm that if you create QnA pairs in Composer, and test those, that it works.

**Comment by srinaath** [comment]
@jnair7291 Could you confirm if you are not able to reproduce the error once you add a qna pair to your knowledge base.

**Comment by jnair7291** [comment]
@srinaath  the error still persists. I have switched to bot framework sdk development since I could not get a reason for not hitting my qna kb. But with bot sdk, it is working fine. do you want me to look into details or follow any steps? (other than what has been mentioned , here and with the previous thread)

**Comment by srinaath** [comment]
@jnair7291 Is it possible for you to zip up the bot assets?
In addition, following are steps to try
1. Could you provide info around the Composer version you are using, Operating System.
2. If you are on a previous version of Composer could you check if running on the latest version resolves the issue?
3. Could you check if the qnmaker.ai portal the knowledge base that would have been published when you started the bot?

**Comment by srinaath** [comment]
@jnair7291 Were you able to debug this furthur?

**Comment by dmvtech** [comment]
Closing due to lack of response. If you are still having issues, please respond with the answers to the above queries and we will reopen.
