### ISSUE TITLE
UI fixes for new auth experience

### ISSUE THREAD

**Issue by emivers8** [microsoft/BotFramework-Composer#8243]
1. Error code copy. Get a list of potential error code so we can provide user friendly copy OR, if we determine those aren't useful to the user, just have copy say, "Sign in failed. Please try again."

![image](https://user-images.githubusercontent.com/55601267/124167838-315c2900-da59-11eb-882e-db4b9e1c1f5b.png)

2. Copy should say "sign in", no hyphen. (Azure's convention.) Also, the failure notification has a little X icon--should success have a green check icon?

![image](https://user-images.githubusercontent.com/55601267/124168073-7f712c80-da59-11eb-9a5c-78170d912a0a.png)

3. Hitting “okay” after switching directories triggers the above sign-in confirmation again. Should be a “You've successfully switched directories” notification.

4. The post-login switch directories dialog needs an X and a cancel button.

![image](https://user-images.githubusercontent.com/55601267/124168271-c4955e80-da59-11eb-9724-e9fffd3c1db0.png)

5. Increase space between rocket and avatar.

![image](https://user-images.githubusercontent.com/55601267/124168371-e42c8700-da59-11eb-9935-21766569d75e.png)

**Comment by benbrown** [comment]
1. Done - i will console the error out for expert users and debugging, but the message just says failed, try again.
2. Done
3. Done
4. Will do my best on this one but... to achieve this might take more than we want to do right now. Will report back!
5. Done

Also: Made the notifications close after 5 seconds

These are included in the main pr.

**Comment by benbrown** [comment]
4. Done!

**Comment by benbrown** [comment]
These are all fixed in #8114
