### ISSUE TITLE
Publishing Profile - Add New - Import missing JSON attribute for LUIS

### ISSUE THREAD

**Issue by Todd442** [microsoft/BotFramework-Composer#8244]
## Describe the bug

Adding a new publishing profile to a project, select import, JSON schema generated is missing an attribute need to deploy SUCCESSFULLY with LUIS.

## Version
2.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ 93.0.926] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. select publish
2. select Publishing Profile tab
3. Click "Add new"
4. Select "Import"
5. Window pop with schema is missing  "luisResource": XXXXXXXXXX-luis" element at end of schema... will result in a failed deployment if you specify the other LUIS elements in the doc. 

## Expected behavior

 "luisResource": ""
-Should be last element in JSON
## Screenshots
BROKEN
![image](https://user-images.githubusercontent.com/7561232/124167889-062e0580-da6a-11eb-976c-d8fa44c8ae5e.png)

CORRECT
![image](https://user-images.githubusercontent.com/7561232/124168456-cc113380-da6a-11eb-873d-3b8cd1545a43.png)

**Comment by srinaath** [comment]
@Todd442 Thanks for spotting it. We will be adding the field to the default schema of the publishing profile
