### ISSUE TITLE
Add telemetry event for user opting in or out of telemetry.

### ISSUE THREAD

**Issue by garypretty** [microsoft/BotFramework-Composer#8245]
## Describe the feature

Log a new telemetry event when someone opts in or out of telemetry when presented within the initial modal dialog. 

Event should be called **TelemetryOptInOut** and add a custom property should be added to the event called **enabled** -  which is set to true if they opt in and false if they opt out. 

If the user opts in then we can send any cached events (handoff / session start), along with this new event, and all can contain all of the global properties we currently send.

If the user opts out, we should only send this single event (drop the cached ones) and the event should not contain the Id for the user.

**Comment by tdurnford** [comment]
At the moment, the user id is added to the Application Insights envelope right before the event is sent. There is a mechanism to filter out PII; however, this filter is applied to every telemetry event. 

If we want to remove certain properties likes the user id based on the telemetry event and the given properties, we'll have to add a new mechanism to avoid writing custom logic. I propose we add a `filterProperties` map to the [Composer/packages/types/src/telemetry.ts](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/types/src/telemetry.ts) file that allows us to define a set of properties or a function that returns a set of properties to filter out for that telemetry event.

Then in the [Composer/packages/server/src/services/telemetry.ts](https://github.com/microsoft/BotFramework-Composer/blob/9413a18047189de04e5b4827b0c7bcae2ac6ad60/Composer/packages/server/src/services/telemetry.ts#L90) file, we can simply retrieve the filtered properties based on the telemetry event name and add it to the existing logic to remove PII.

### [Composer/packages/types/src/telemetry.ts](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/types/src/telemetry.ts)
```typescript
 type BaseProperties = {
  sessionId?: string;
  userId?: string;
  composerVersion: string;
  toolName: string;
  architecture: string;
  cpus: number;
  memory: number;
}

type FilterProperties = Partial<
  {
    [TN in TelemetryEventName]:
      | string[]
      | ((properties: (TelemetryEvents[TN] extends undefined ? never : TelemetryEvents[TN]) & BaseProperties) => string[] | undefined);
  }
>;

export const filterProperties: FilterProperties = {
  TelemetryOptInOut: ({ enabled, source }) => {
    /**
     * If the user opts out of telemetry from the data collection prompt,
     * remove the userId from the Application Insights envelope
     */
    if (!enabled && source === 'prompt') {
      return ['userId'];
    }
  },
};
```

### [Composer/packages/server/src/services/telemetry.ts](https://github.com/microsoft/BotFramework-Composer/blob/9413a18047189de04e5b4827b0c7bcae2ac6ad60/Composer/packages/server/src/services/telemetry.ts#L90)
```diff
+ const getFilteredProperties = filterProperties[data.baseData.name]
+ const filteredProperties = typeof getFilteredProperties === 'function' ? getFilteredProperties() : getFilteredProperties;

// remove PII
- for (const property of piiProperties) {
+ for (const property of [...piiProperties, ...(filteredProperties || [])]) {
  if (data.baseData.properties[property] !== undefined) {
    delete data.baseData.properties[property];
  }
}
```

@srinaath Thoughts?

**Comment by srinaath** [comment]
@tdurnford I like the elegant approach to decide what properties to include/not include based on the event type and would be the ideal solution we shoot for, but i feel for R14 we could settle for a simple exclude PII property for this TelemetryOptInOut event name alone.
