### ISSUE TITLE
Add ability to test an HTTP request from Composer without the bot running

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#8246]
## Is your feature request related to a problem? Please describe.

Not precisely. I'd like to verify I have a valid HTTP request configured without needing to run the bot, which would add other complicating factors.

## Describe the solution you'd like

Some way to test the HTTP request from within Composer, filling in variable references as necessary.

## Describe alternatives you've considered

Not sure what would make sense without adding a link to another tool and populating some of the HTTP request values in the tool.

**Comment by victorlamana** [comment]
This is a nice request, as of today I test my http requests on Postman but it would be nice to have a built-in test on Composer
