### ISSUE TITLE
Provision failure - App create failed!

### ISSUE THREAD

**Issue by victorlamana** [microsoft/BotFramework-Composer#8249]
## Describe the bug

Hello Microsoft Team! Could you please help me on this issue?
Thanks a lot!

Provision failure
{"name":"CREATE_APP_REGISTRATION","message":"App create failed! Please file an issue on Github.","stack":"Error\n at new CustomizeError (C:\\Program Files\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:255547:25)\n at createCustomizeError2 (C:\\Program Files\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:255552:10)\n at BotProjectProvision.createApp (C:\\Program Files\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:256989:17)"}. See provision.Azure-Lab.log in your bot folder

## Version

2.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X ] Edge

I don't think browsers make a difference here
## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Publish'
2. Click on 'Publish Profile'
3.Create a new publish profile

## Expected behavior

Create the publish profile

**Comment by luhan2017** [comment]
@victorlamana , it usually happens when the graph token is not valid, could you double check if you input a valid graph token? 

![image](https://user-images.githubusercontent.com/32191031/124212586-ccb8d100-db21-11eb-9a29-f5a18336c7d8.png)

**Comment by victorlamana** [comment]
hello @luhan2017 i never saw this screen on Composer. I'm not sure if we're talking about the same thing:

![image](https://user-images.githubusercontent.com/52974336/124304379-fd0c6980-db39-11eb-8869-5b13150824b6.png)

My error happens when creating a publishing profile through this screen

![image](https://user-images.githubusercontent.com/52974336/124304457-1dd4bf00-db3a-11eb-903d-878134a73163.png)

**Comment by victorlamana** [comment]
{
  "profileName": "Azure-LAB",
  "jobId": "2d6fe7e4-8891-404d-bdaa-8bba985238bb",
  "projectId": "88677.19435279138",
  "time": "2021-07-02T17:50:22.042Z",
  "log": [
    "Creating Azure resources...",
    "Checking the Existence of the Resource Group ...",
    "Use the Resource Group: ldc-covid-aid at northeurope",
    "> Creating App Registration ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:255547:25)\\n    at createCustomizeError2 (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:255552:10)\\n    at BotProjectProvision.createApp (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:256989:17)\"}",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:255547:25)\\n    at createCustomizeError2 (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:255552:10)\\n    at BotProjectProvision.createApp (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:256989:17)\"}. See provision.Azure-LAB.log in your bot folder"
  ]
}


this is the error log I generated right now trying to recreate the error

Thanks for all the help until now

**Comment by natalgar** [comment]
We've added some additional logging that should help debug this issue. @victorlamana If you go to Composer's App Settings and enable "Early Adopters" you'll be able to update to the pre-release version with the logging.

I'm going to close this issue since we have a duplicate issue open to track it: #8283
