### ISSUE TITLE
BUG "Luis build failed: Cannot read property 'utterances' of undefined" after training on LUIS.ai

### ISSUE THREAD

**Issue by victorlamana** [microsoft/BotFramework-Composer#8255]
## Describe the bug

Hello! I'm sorry to open another ticket despite having another one opened for another issue, but this one seems like a bigger problem.

When I create any bot (both C# and Node.js) on Composer, if I create the apps on luis.ai through composer (by creating dialogs and entities) as shown on the picture below:

![image](https://user-images.githubusercontent.com/52974336/124317458-9729dd00-db4d-11eb-902b-7c003002a4d0.png)

After I train and publish the AI through LUIS.ai, the bot on Composer becomes unresponsible, I can't even start the bot because of the following error message:

![image](https://user-images.githubusercontent.com/52974336/124317538-b88ac900-db4d-11eb-86d6-0632f1645c1f.png)

I saw some topics on the error and they ended on the agreement that the "solution" is to delete the conversation apps on Luis.ai and recreate them again through Composer (by restarting the bot). This made the trick for me, the bot works now but I lost all my work on LUIS.ai. What is the point of training an AI through LUIS if I can't use it on Composer after that? Am I missing something? 

Is there another solution to this bug? 

## Version
2.0
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty bot on composer
2. Create some dialogs and entities
3. Connect to luis.ai through the bot settings -> development resources button
4. Train the AI on luis.ai and publish a new version of the AI
5. Try to restart the bot 

## Expected behavior

Bot restarts with new AI from luis.ai

## Screenshots

![image](https://user-images.githubusercontent.com/52974336/124317988-61392880-db4e-11eb-9cf6-61669d52bd3a.png)

## Additional context

I love the application, Composer and the fast replies Microsoft gives on Github. I truly hope these bugs get fixed because Composer is a great platform for chatbot development

**Comment by dmvtech** [comment]
Hi @victorlamana 

This is a current limitation. As it stands now, there is no bi-directional support for either LUIS or QnA within Composer. This is being addressed and future releases will have this ability. For now; you must author and train from within Composer.

**Comment by victorlamana** [comment]
hello @dmvtech thanks for the explanation! :)

Could you please send a link for the documentation where it talks about training AI within Composer? I didn't find it. The only thing I managed to find was how to create the expected responses, is it something beyond this functionality?

![image](https://user-images.githubusercontent.com/52974336/124989113-2be07f00-e015-11eb-9919-8329cd2ea415.png)

**Comment by victorlamana** [comment]
Hello, is this the function to train the bot on Emulator? Doesn't seem to be working to me =C

![image](https://user-images.githubusercontent.com/52974336/125691496-82ca1d59-5965-4067-a43c-fca6a0c1dee7.png)

Thanks for all the help until now =)

**Comment by victorlamana** [comment]
hello?

**Comment by dmvtech** [comment]
Hi @victorlamana Apologies for the delay!

> The only thing I managed to find was how to create the expected responses, is it something beyond this functionality?

Correct, that is the way you train the LUIS model.


> Could you please send a link for the documentation where it talks about training AI within Composer? 

Yes. Please see documentation here:
https://docs.microsoft.com/en-us/composer/concept-language-understanding?tabs=v2x

For further clarification and simplification, per that document:

> LU has the following characteristics when used in Bot Framework Composer:
> 
> LU is training data for the LUIS recognizer.
> LU is authored in the inline editor or in User Input using the .lu file format.
> Composer currently supports LU technologies such as LUIS


If you need to extract/move/etc stuff between an existing LUIS app and .lu files (or other variances of that situation), you could also use the [Bot Framework CLI](https://github.com/microsoft/botframework-cli) tool.

And to address:
> What is the point of training an AI through LUIS if I can't use it on Composer after that? Am I missing something?

LUIS has been around for quite some time, well before Composer. Additionally, it can be used outside and independent of bots or Composer. Composer is quite new and we are still working to make it more a seamless integration when using LUIS. Obviously, it's not quite there yet.

Let me know if you have further questions or if I can provide further clarification.

**Comment by victorlamana** [comment]
Hello @dmvtech , thanks for the explanation!! I'll close the issue

Once again, thanks for all the support  :)
