### ISSUE TITLE
I cannot open my advanced settings in bot composer. After the new update whenever I click to view my bots Json file it will only be displayed in a tiny strip and I cannot edit it in any way.

### ISSUE THREAD

**Issue by deon1010** [microsoft/BotFramework-Composer#8256]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
@deon1010 Would you be able to provide a screenshot of the issue?

**Comment by cwhitten** [comment]
Hi @deon1010 what version of Composer are you using?

**Comment by deon1010** [comment]
![Settings error](https://user-images.githubusercontent.com/56408334/124644463-4cb3a380-de60-11eb-9ac6-580cdfd4efe7.PNG)

This is what it looks like.

**Comment by deon1010** [comment]
> Hi @deon1010 what version of Composer are you using?

Im using version 2.0.0-nightly
