### ISSUE TITLE
Incident 246896943 : [CSS][investigating 6/28] App create failed when publishing from composer desktop 2.0 with new resources

### ISSUE THREAD

**Issue by VamsiModem** [microsoft/BotFramework-Composer#8259]
## Describe the bug

The customer is publishing bot with LUIS from Composer desktop 2.0 with the option "Create new resources". The publish fails with the below error, which I describe in the repro steps.  

## Browser

- [ x ] Electron distribution

## To Reproduce

He signs into composer, creates a new publishing profile, chooses the tenant with multi factor auth enabled and tries to publish and gets the below error.

{"name":"CREATE_APP_REGISTRATION","message":"App create failed! Please file an issue on Github.","stack":"Error\n at new CustomizeError (c:\\users\\nishant.k.srivastava\\appdata\\local\\programs\\bot framework composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:255547:25)\n at createCustomizeError2 (c:\\users\\nishant.k.srivastava\\appdata\\local\\programs\\bot framework composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:255552:10)\n at BotProjectProvision.createApp (c:\\users\\nishant.k.srivastava\\appdata\\local\\programs\\bot framework composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:256989:17)"}. See provision.DSSCitizenServiceBotDev.log in your bot folder

## Expected behavior

LUIS Resource should be published successfully.

## Additional context

please refer to this [incident](https://portal.microsofticm.com/imp/v3/incidents/details/246896943/home) for more information.

**Comment by Shameeritc** [comment]
I am also facing the same issue for a basic bot provisioning.

**Comment by victorlamana** [comment]
I have the same issue too and opened another ticket here
