### ISSUE TITLE
Add QnA action documentation to composer

### ISSUE THREAD

**Issue by simer99** [microsoft/BotFramework-Composer#828]
Following to be done: 

1. Documentation for Samples
2. Documentation for QnA Action in Composer
3. Any blogs

WIP  : 
[Detailed doc](https://microsoft.sharepoint.com/:w:/t/stci/teams/relevance/EZwsOgUfK2pEom-XNqafUmEB6XE2KEfkCqrGXwrly2LoWg?e=1BaF2a)

**Comment by diberry** [comment]
@simer99 Anything left to do or can this be closed?
