### ISSUE TITLE
NodeJS bot fails to start on windows

### ISSUE THREAD

**Issue by Brent-Higgins** [microsoft/BotFramework-Composer#8287]
## Describe the bug

On Windows when we try to start a bot the bot fails to start with a SIGTERM error from npm install.
This occurs due to additional packages in package.json to facilitate CI/CD requirements causes npm install to take 90+ seconds.
## Version
Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. modify package.json to include the following
```
 "dependencies": {
    "@microsoft/botframework-cli": "^4.12.0-dev.20210115.2b00408",
    "botbuilder-ai-luis": "4.13.4-preview",
    "botbuilder-ai-qna": "4.13.4-preview",
    "botbuilder-dialogs-adaptive-runtime": "4.13.4-preview",
    "botbuilder-dialogs-adaptive-runtime-integration-express": "4.13.4-preview",
    "cross-env": "latest",
    "sonarqube-scanner": "^2.8.0"
  },
  "devDependencies": {
    "@types/chai": "^4.2.18",
    "@types/mocha": "^8.2.2",
    "@types/sinon": "^10.0.2",
    "botium-bindings": "^2.1.8",
    "botium-connector-directline3": "0.0.26",
    "chai": "^4.3.4",
    "dotenv": "^10.0.0",
    "mocha": "^9.0.0",
    "mochawesome": "^6.2.2",
    "nyc": "^15.1.0",
    "sinon": "^11.1.1",
    "ts-node": "^10.0.0",
    "typescript": "^4.3.2"
  }
```
2. click start bot

## Expected behavior

Bot can start even if npm install is slow

## Additional context

This is occurring on windows PCs behind an enterprise firewall using an internal npm artifactory mirror.
This is caused by 120 second timeout on bot start that is hardcoded into composer.
On Mac our npm install is taking ~30 seconds on windows it is taking >=90 seconds.
We can start the bot in cmd prompt.
Running npm install in the repo manually does not solve the issue.
Access to public npm is blocked by corporate policy.
We can usually get the bot to start if we do not have the extra dependencies.
With above configuration 100% reproduction rate across multiple computers on VPN and corporate network.

**Comment by a-b-r-o-w-n** [comment]
@Brent-Higgins thanks for the report. We will increase the timeout for our upcoming release.
