### ISSUE TITLE
Enable or Disable spell check in Luis from Composer

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/BotFramework-Composer#8292]
I'm trying to disable spell check in Luis from the certain step of flows in the composer before querying to Luis is this feature available as of now?

**Comment by a-b-r-o-w-n** [comment]
@KoradaRajesh can you elaborate on what you are trying to do? Do you want to disable the Luis spell check from a dialog action within the bot flow? Or something else?

**Comment by KoradaRajesh** [comment]
@a-b-r-o-w-n Yes, exactly I want to disable the Luis spell check from a dialog action with in the flow.

**Comment by hcyang** [comment]
Hi @KoradaRajesh, here is the LUIS documentation (https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-tutorial-bing-spellcheck) on enabling Bing Spell check during authoring or runtime endpoint.
Furthermore, here is the LUIS programmatic API on enabling and disable spell-check: https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5ae32174d5b81c02cc64c6d3
