### ISSUE TITLE
When provisioning any bot through Composer, MicrosoftAppPw is not saved in profile

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/BotFramework-Composer#8303]
## Describe the bug
When I provisioned my Azure Functions resources through the Composer provisioning flow, I saw that the app password was not included in my created publishing profile. Even after providing the pw in the profile and appsettings, I was getting authentication errors until I provided it manually in the Azure Functions resource settings in Azure here: 

![image](https://user-images.githubusercontent.com/27976702/125005841-9db6c980-e011-11eb-9334-a06c1085adbe.png)

**Note**: this issue also applies to web apps so all bots are affected.

## Version

Version:  2.0.0-nightly.257298.f833d8e
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by joshgummersall** [comment]
I saw this with both functions and web apps just now.
