### ISSUE TITLE
3rd party triggers don't get pretty display names

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#8310]
When you add a 3rd party trigger to your bot it adds the component name to the tree instead of the pretty name. I've tried several different 3rd party packages and they all have the same issue.

![image](https://user-images.githubusercontent.com/698939/125134726-b03a0d00-e0bc-11eb-8f78-a2fe3acbad2a.png)

**Comment by a-b-r-o-w-n** [comment]
@Stevenic The component author can provide a ui schema to set this name. I believe this has been shipped with the latest packages. Can you try with the latest package (1.1.0)?

**Comment by Stevenic** [comment]
@a-b-r-o-w-n here's the UI schema for that trigger... Am I missing a property? I set the label:

```json
{
  "$schema": "https://schemas.botframework.com/schemas/ui/v1.0/ui.schema",
  "form": {
    "order": [
      "verb",
      "condition",
      "*"
    ],
    "hidden": [
      "actions"
    ],
    "label": "Action.Execute (invoke activity)",
    "subtitle": "Handle Action.Execute"
  },
  "trigger": {
    "label": "Action.Execute (invoke activity)",
    "submenu": {
      "label": "Adaptive Cards",
      "prompt": "Which action type?",
      "placeholder": "Select an action type"
    }
  }
}
```

**Comment by Stevenic** [comment]
Looks to be fixed in nightly builds.
