### ISSUE TITLE
Bot on localhost:3993 not working, error message: timeout

### ISSUE THREAD

**Issue by jolo1000** [microsoft/BotFramework-Composer#8317]
## Describe the bug

Bot on localhost:3993 not working, error message: timeout

## Version
Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [x ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

Install:
- Bot Framework Composer 2.0.0 for OSX
- Dot net framework SDK ver. 3.1.410 for
- OSX is Mojave 10.14.6 (18G103)

Then 
- create an empty bot in the Bot Framework 
- start the bot

result is this error message:

warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
Error occurred building the bot

Bot on localhost:3993 not working, error message: timeout

This happens with every provided example.

**Comment by anusharavindrar** [comment]
@jolo1000, do you get the above warning in the output window or as a pop-up when you start the bot? Can you attach a screenshot of the error message? Also, do you get the same error for every other template? I tried to create an empty bot on Composer 2.0.0 on MacOS and when I start the bot, the status shows "Running" and I am able to test on the Emulator and Web Chat, except that I get the above warning in the output window.
