### ISSUE TITLE
QnAMaker dialog: Load from file UI confusion

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#8323]
## Issue
UI suggests that I can load from a local file but entrybox suggests entering a URL and no way to invoke local file selection (i.e. in windows file explorer). At this stage, user is left with "how do I load my local file?"

## Visual

![image](https://user-images.githubusercontent.com/8867670/125337647-1d8baf00-e304-11eb-8a02-f7b0473b201e.png)

**Comment by scheyal** [comment]
Version:

Version:  2.0.0-nightly.258070.287a4dc
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by srinaath** [comment]
@scheyal  we are updating the copy here now.

**Comment by vivekkshankar** [comment]
Recommended text: 

**Text in radio selection:** "Create new knowledge base from URL"
**Text in description**: "Select this option if you want to create a knowledge base from content hosted online such as an FAQ or document link (.csv, .xls or .doc format)"

@srinaath @boydc2014 @zhixzhan
