### ISSUE TITLE
Dialog description should be added as a note

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#8327]
The description added when creating a new dialog should get promoted to being the dialogs note.  I personally never fill this field in because it doesn't show up anywhere. Now that we have notes there's a place for it in the UX. 

![image](https://user-images.githubusercontent.com/698939/125349636-a27dc500-e312-11eb-9927-f4a261796d96.png)

![image](https://user-images.githubusercontent.com/698939/125349834-dfe25280-e312-11eb-93a3-19ef9b087972.png)

**Comment by vivekkshankar** [comment]
+1 Thats a great idea and I think we can use the note to show this.
