### ISSUE TITLE
Allow multi-line notes

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#8328]
I was expecting that I'd have the ability to create multi-line comments. :(

![image](https://user-images.githubusercontent.com/698939/125350197-4a938e00-e313-11eb-8bf8-461ff40a0256.png)

**Comment by Stevenic** [comment]
Ok it's just weird that if I type enough text the note edit box turns into a multi-line input... I'm fine with that behavior but there's a bug that pressing \<enter> while in single-line mode doesn't immediately expand to multi-line mode. You have to type a bunch of characters before it goes to multi-line 

![](https://user-images.githubusercontent.com/698939/125350857-3734f280-e314-11eb-9dd2-2a764bcd835a.png)

**Comment by vivekkshankar** [comment]
@Stevenic Nice catch. We are using an off the shelf fluent control for multiline input and this is the behavior it comes with.
https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield (Multi line auto expand)

We could replace this control with other an auto height adjust control but I dont think we still get the enter to expand field functionality. Also, we need to check if we can retain  the behavior of the note occupying minimum height for short comments and when not in focus.  

@a-b-r-o-w-n What are your thoughts on using the "auto-height adjusting multiline field" with the default height set to one line? I also think we don't think need to show the resize control for this field.

![image](https://user-images.githubusercontent.com/67671676/125383042-9f52fb00-e34b-11eb-9541-43e6b09fa8d8.png)
