### ISSUE TITLE
Notes: text wrap issue when pressing "show more"

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#8331]
Really long note text doesn't wrap properly when pressing "show more"

![image](https://user-images.githubusercontent.com/698939/125351444-f12c5e80-e314-11eb-9dad-329768bf9b93.png)

**Comment by a-b-r-o-w-n** [comment]
@Stevenic this only happens when actively pressing the show more / less button?

**Comment by Stevenic** [comment]
@a-b-r-o-w-n  yes

**Comment by Stevenic** [comment]
Although I haven't tried with just a single comment that's a long string of text

**Comment by Stevenic** [comment]
You don't even get the "Show More" unless there's multiple tokens or line breaks

![](https://user-images.githubusercontent.com/698939/125355171-8c273780-e319-11eb-8b28-1e76864cc997.png)
