### ISSUE TITLE
Connecting to a skill should not add the appId of the skill to the allowed callers list

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#8335]
## Describe the bug

The AppIDs of skills consumed by a bot are implicitly trusted by the runtime (this change went into the 4.14.x of the runtime) so it doesn't need to be added to the allowed lists. 

## Version

Version:  2.0.0-nightly.258070.287a4dc
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty bot and configure the appId and password so we can connect to a skill
2. Add a skill using a skill manifest.
3. The appId of the skill will show up in the skill configuration tab:
![image](https://user-images.githubusercontent.com/12264946/125352556-6b69dc80-e32f-11eb-9c8e-bb54f1d6dc6b.png)
4. This is not needed and can be removed starting with 4.14.x

## Expected behavior

The appId of the added skill should not be added to the allowed callers list, this is only needed when I write a skill in composer. 
When I'm just consuming skills, this section should look like this:
![image](https://user-images.githubusercontent.com/12264946/125352939-e632f780-e32f-11eb-9821-e55fe450554b.png)

**Comment by vivekkshankar** [comment]
@gabog This is good for the overall skills expeirence. Just to clarify are we saying that allowed callers only need to be configured for skills and the not the parent bot calling the skill ?

**Comment by gabog** [comment]
That's correct @vivekkshankar, [this PR](https://github.com/microsoft/botbuilder-dotnet/pull/5684) by @LeeParrishMSFT, adds an AllowedSkillsClaimsValidator that will automatically "trusts" any skill connected to the host bot, it basically pulls the list from the list of configured skills. This takes precedence over any allowed callers configured.

Based on the current implementation of the runtime, I composer bot can by a consumer or a skill but not both. If it is a consumer the allowed callers list will be ignored and will be inferred from the configured skills.

If it is a skill then you shouldn't be able to consume other skills and the user should populate the allowed callers list.

Maybe we can support both in the future but that's not possible with the current runtime.
