### ISSUE TITLE
Watch variable not showing value

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#8336]
## Scenario
1. Add watch variable to a simple empty bot (Node.js)
2. Prompt and echo variable's value to verify it is filled
3. Watch pane doesn't show value (not available)

_remark_: I may be doing something wrong, but wanted first to go to what I felt is the intuitive expectation to see value when I run it.

### Webchat

![image](https://user-images.githubusercontent.com/8867670/125352936-c04d2900-e316-11eb-825b-6f6e9c05112e.png)

### Emulator

![image](https://user-images.githubusercontent.com/8867670/125352741-811ed800-e316-11eb-8648-52dff6920258.png)

**Comment by srinaath** [comment]
@scheyal The way traces are working currently, the BotState trace exposes the dialog information only if it has more than 1 prompt. The Watch feature currently implemented is more of a passive watch, in the sense that we rely on what the latest botstate trace has. What is happening here is the code in the dialog is completely run and the dialog context is popped out of the stack by the time trace is sent. This is an expected limitation of the feature. @garypretty

**Comment by xiyangdesign** [comment]
+1 on what @scheyal described, although it showed undefined, instead of "not available"
