### ISSUE TITLE
Problems with form-dialog property box

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#8339]
## Expected behavior

There should be explicit confirm/cancel buttons of some kind instead of trusting a user to discover that clicking outside the box confirms it and the only way to "cancel" addition of a property is to confirm it, then find "Delete" in the kebab menu.

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/125352925-bcb9a200-e316-11eb-89fc-0b59b6ee7bce.png)

**Comment by hatpick** [comment]
I think the current UX works pretty well for this iteration, we may or may not consider changing it in the future.
when you (as user) learn how to use it, it's pretty straightforward.
