### ISSUE TITLE
Form dialog Money type dropdown is clumsy

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#8340]
## Expected behavior

Currencies should have unambiguous names (e.g. `US Dollar (USD)` instead of just ` Dollar` in the middle of other currencies all named "dollar"). Also, more-commonly-used currencies (USD, yen, euro, etc.) should probably be at the top.

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/125353746-cb548900-e317-11eb-89e2-e9102ced89e9.png)

**Comment by vivekkshankar** [comment]
Agree that the names should be unambiguous. I don't think we can assume which currencies are more used than others since that depends on the customer and the intended geo of their end user. Just my 2 cents.

**Comment by hatpick** [comment]
@chrimc62 I think these are coming from LUIS too right?
