### ISSUE TITLE
Problems pane defaults settings should be to show both errors and warning and all bots

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#8345]
## Describe the bug

The Problems pane should be not remember settings when you switch bots. It should reset to show all errors, all warnings, and for all bots each time you open a bot in Composer.

## Version

2.0.0-nightly.258070.287a4dc

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open any bot that does not have multiple bots.
2. Go back to the home page.
4. Open an enterprise assistant bot.
5. Open Problems pane and see that the pane is filtered to just the root bot.

## Expected behavior

The Problems pane defaults should be reset to show everything (errors, warning, all bots) whenever I (re-)open a bot.

## Screenshots

https://user-images.githubusercontent.com/39317542/125354199-5fbeeb80-e318-11eb-9e6c-fed556645038.mov

**Comment by garypretty** [comment]
Agreed path forward here is to always have an 'All' option in the filter, regardless of if you have only one or more than one bot.

All will be the default value.

We should reset this filter to all on Project Open, to ensure the filter is set back to all if you open more than one bot in the same session.

@mewa1024 @vivekkshankar can you clarify the above aligns with your thinking please?

**Comment by mewa1024** [comment]
agree!
