### ISSUE TITLE
Form dialog has mysterious "dynamiclist" property type

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#8346]
Every other entry in the list of types has a tooltip with a short helpful description, but `dynamiclist` sticks out as an all-lowercase entry of run-together words with a tooltip (that I couldn't capture in a screenshot) that just reads "dynamiclist".

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/125354407-9d237900-e318-11eb-98d2-312f829628a7.png)

**Comment by hatpick** [comment]
@chrimc62 Perhaps forgot to add description to the $generator? Also, maybe use "Dynamic List" instead
