### ISSUE TITLE
Manifest version in exporting as a skill should be 2.2

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#8347]
As part of R14, we added support for relative files in skill manifests 2.2, the default version should be 2.2
![image](https://user-images.githubusercontent.com/12264946/125354943-678b8980-e332-11eb-9b8a-210a5b74d6dc.png)

And the schema in the generated manifest should be 2.2
![image](https://user-images.githubusercontent.com/12264946/125354649-0bc10080-e332-11eb-8bee-22c0a41fe171.png)

**Comment by luhan2017** [comment]
@alanlong9278, let's remove the manifest version selection and take 2.2 as a default.
