### ISSUE TITLE
The version of the bot property should be used in the manifest path, not the skill manifest version

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#8352]
When I create a manifest for my bot, the **manifest version** is used in the path of the generated manifest URL,, we should probably use the bot version, not the manifest version for this.

The manifest version is implicit in the $schema attribute of the manifest file. 

If I try to generate a manifest based on these options:
![image](https://user-images.githubusercontent.com/12264946/125355457-1203ac80-e333-11eb-87b0-77fd13916243.png)

The manifest URL will look like: 
https://composerbugbashrg.azurewebsites.net/manifests/PVAAsASkill001-2-1-manifest.json

It should have been something like (note the 1-0 in the URL
https://composerbugbashrg.azurewebsites.net/manifests/PVAAsASkill001-1-0-manifest.json

**Comment by luhan2017** [comment]
@gabog, @vivekkshankar  by using the version as the manifest name, do you want to keep all the historical manifest versions locally? currently, we only keep one manifest file for each schema version, the name is to distinguish the schema versions. Later we will remove the schema version selection and always use version 2.2 as the default, in that case, we may always keep one manifest locally, and name it just "manifest.json". Will it work for you?
