### ISSUE TITLE
Form dialog for temperature has unusual/obsolete units and bad tooltips

### ISSUE THREAD

**Issue by beyackle** [microsoft/BotFramework-Composer#8353]
## Expected behavior

The usual C and F should be there, and maybe K and R can stay, but I have my doubts anyone is going to ask a chatbot to specify a temperature in Delisle degrees (which I had to figure out on my own because these entries just have the letters themselves as tooltips without telling what they stand for).

## Screenshots

![image](https://user-images.githubusercontent.com/61990921/125355771-4454e000-e31a-11eb-85f4-69737fbb2050.png)

**Comment by hatpick** [comment]
@chrimc62 
Better title for generator? e.g. F -> Fahrenheit (F)

**Comment by chrimc62** [comment]
The problem is that these are the actual enum values that are returned by LUIS and they need to match.  To fix this, I think we would have to change the UI code to be able to use .uischema to control this.  With that change, I could update the generator to generate the appropriate fragment.
