### ISSUE TITLE
watch: "user." drops from intelisense menu

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#8359]
I had a "user." entry on the watch panels intelisense menu but then it dropped off after I restarted the bot:

![image](https://user-images.githubusercontent.com/698939/125359584-59803d80-e31f-11eb-90ba-e6dd82d0fb14.png)

**Comment by cwhitten** [comment]
@Stevenic can you give us some repro steps to better diagnose this?

**Comment by mewa1024** [comment]
Is this because there is only one "user" property and once it's added the "user" menu is removed from the picker?

https://user-images.githubusercontent.com/39317542/125499275-0139e7a5-f912-4bec-80d6-38124a7176fc.mov

**Comment by Stevenic** [comment]
That could be... I'll close for now
