### ISSUE TITLE
[R14 bugbash] Resizing the Composer window gets ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/BotFramework-Composer#8361]
Resizing Composer from full screen, I got a popup saying "ResizeObserver loop ..." ... "ResizeObserver loop limit exceeded".

What I did: 
Composer was on its "Home" page.
The window was maximized on my computer screen.
I moved it over to my external monitor. It maximized itself.
I clicked the resize button in top right corner. Error occurred.

**Comment by srinaath** [comment]
@zhixzhan Can you take a stab at it in your daytime?

**Comment by zhixzhan** [comment]
> @zhixzhan Can you take a stab at it in your daytime?

Sure, I will

**Comment by srinaath** [comment]
@BruceHaley Do you have a consistent repro for this error? If so could we do a screenshare?

**Comment by hatpick** [comment]
From the bug report, it says it was in home page, ResizeObserver for breadcrumb is in DesignPage, @zhixzhan are you sure that PR fixes this issue?
