### ISSUE TITLE
watch: panel crashes when watching a variable name used in multiple dialogs

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#8362]
I created a test bot with two dialogs. The first dialog has 2 inputs that save their results to `dialog.result.name` and `dialog.result.age`. After collecting those inputs the first dialog calls a second dialog which has 2 inputs that save their results to `dialog.result.name` and `dialog.result.years`. The output gets saved to a `dialog.result.company` property by the first dialog.

Everything goes as expected when stepping through the first dialog and even the second dialog.  While in the first dialog I see the values for name & age and when I step into the second dialog those get replaced with name & year. When the second dialog is done, however, the watch panel blows up with this error:

![image](https://user-images.githubusercontent.com/698939/125360857-55edb600-e321-11eb-90d4-0a1f10dcb0d1.png)

**Comment by cwhitten** [comment]
@GeoffCoxMSFT we think an issue may remain in the splitter component

**Comment by srinaath** [comment]
Closing as a dupe of #8362. We are going to look to migrate to the lates of gcox/splitter component in which the ResizeObserveLoop would not exist.
