### ISSUE TITLE
Web Chat log opens when you click on a card, making it difficult to use Watch

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#8365]
## Describe the bug

When you click on a message, the Web Chat log was designed to show you the log item that corresponds to that message. This can cause problems if you are watching a conversation with cards: if your Watch pivot is selected, when you click on a button or element in a card, the Web Chat pivot becomes selected so the Watch pivot is hidden.

## Version

2.0.0-nightly.258070.287a4dc

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open a bot with cards, like Enterprise Assistant.
2. Open the Watch pane and add some variables.
3. Start your bot and interact with the cards.
4. You will see that when you click on a card, that card become in focus and the Web Chat pivot becomes active (hiding the Watch pane), and the log related to the card is selected.

## Expected behavior

1 - When clicking on a button or input in a card, do not select the message.
2 - When clicking on a message, select the corresponding Web Chat log item, but do not make the Web Chat pivot the selected pivot.

## Screenshots

https://user-images.githubusercontent.com/39317542/125357469-88e17b00-e31c-11eb-8890-f047768164bb.mov

**Comment by mewa1024** [comment]
@srinaath @tonyanziano Are the two fixes suggested in the Expected Behavior doable?

**Comment by tonyanziano** [comment]
P0 was fixed with #8391, the P1 is still active. Reopening and swapping the P1 label in

**Comment by tonyanziano** [comment]
It turns out that #8391 also fixed the P1 issue, because selecting an activity via the Web Chat test panel no longer switches debug panel tabs.

![FixedCardBehavior](https://user-images.githubusercontent.com/3452012/125873487-78ee58c3-4d82-4a06-a8c4-bcab78a53081.gif)
