### ISSUE TITLE
Bot's Windows process not closed when Composer is closed

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/BotFramework-Composer#8370]
Related? https://github.com/microsoft/BotFramework-Composer/issues/7157

## Describe the bug

Bot `.exe` process doesn't close when Composer does.

## Version

Version:  2.0.0-nightly.258070.287a4dc
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Start bot
2. Note in Task Manager that `mybot.exe` is running
3. Close Composer by clicking the X at the top-right of the window
4. Note in Task Manager that `mybot.exe` is *still* running

## Expected behavior

Bot process will close when Composer closes.

## Additional context -  Odd?

Oddly, if you start the bot on say port `3980` and when performing the steps above, you can start up a completely different bot in VS or VS Code on the same port without error. The odd part about it is that although the new bot appears to be on port `3980` as well, messages will go to the bot that was started in Composer.

**Comment by srinaath** [comment]
@mdrichardson Yep. They are related. We will have to work on a more graceful VSCode style handling of cleaning up dangling processes.
