### ISSUE TITLE
List entities should appear in the "Insert entity" dropdown along with prebuilt entities and have the same interactions

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#8371]
## Describe the bug

When you create new list entity (either with the new UI or by the .lu syntax), the list entity should appear in the "Insert entity" dropdown along with prebuilt entities. Otherwise, the user might try to label with the entity, which causes a blocking error.

## Version

2.0.0-nightly.258070.287a4dc

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to a response editor.
2. Create a list entity (either by typing or by using the "Add entity" dropdown.
2. After you have created the entity, label with this syntax:
    `this is an utterance with the {listentity=example entity}`
3. You will see an error:
    ![image](https://user-images.githubusercontent.com/39317542/125369734-ba187600-e331-11eb-9591-08759e55213e.png)

## Expected behavior

- The error should tell me that I should insert the list entity rather than label. It should not tell me to use roles (which are an advanced feature in LUIS.)
- The list entity should appear in the "Insert entity" menu:
![image](https://user-images.githubusercontent.com/39317542/125369959-37dc8180-e332-11eb-9cce-a7d18ff0bcaa.png)
- the error should appear below the response editor in which it occurs. The error in this case pointed me to the wrong trigger:
    
https://user-images.githubusercontent.com/39317542/125370468-57c07500-e333-11eb-9115-7635b0b44bc3.mov

**Comment by hatpick** [comment]
@boydc2014 Can you or someone from your side look into the issues @mewa1024 mentioned about the diagnostics?
