### ISSUE TITLE
Switching active language doesn't update trigger phrase window

### ISSUE THREAD

**Issue by gabog** [microsoft/BotFramework-Composer#8374]
## Describe the bug

Switching the active language on a multilanguage doesn't seem to update the trigger phreases window

## Version

Version:  2.0.0-nightly.258070.287a4dc
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty bot and configure it to support multiple languages:
![image](https://user-images.githubusercontent.com/12264946/125389330-0afa8f80-e36f-11eb-892c-ba5bc4f3da56.png)
2. Create an intent trigger for the default language and add a couple of utterances:
![image](https://user-images.githubusercontent.com/12264946/125389457-3da48800-e36f-11eb-85cc-019f4adc462b.png)
3. Switch to another language from the language selector at the top of the screen:
![image](https://user-images.githubusercontent.com/12264946/125389535-59a82980-e36f-11eb-8aae-29581e3950ee.png)
4. The trigger phrases for the intent will continue to show the trigger phrases for the previous language 

## Expected behavior

I would expect the trigger phrases to reflect the selected language

## Additional notes
Something similar happens for Send Activity actions:
![image](https://user-images.githubusercontent.com/12264946/125389845-d89d6200-e36f-11eb-9897-b47a6f9eff6c.png)

![image](https://user-images.githubusercontent.com/12264946/125389876-e521ba80-e36f-11eb-9a61-e1d33ef48f98.png)

**Comment by srinaath** [comment]
Im able to repro this as well. Marking it a P0.
