### ISSUE TITLE
[PVA] Error during handover between composer dialoges

### ISSUE THREAD

**Issue by tamasschmolcz** [microsoft/BotFramework-Composer#8376]
Hello,

I try to start from a existing composer dialog to an other composer dialog within a PVA environment and get the error message below.

I try to understand what value is meant, as the dialog, I want to transfer to, does not require any pre-filled values. Thanks in advance!

Error message:

Sorry, the bot can't talk for a while. It is something that the owner of the bot needs to address. Error code: 2023. Entertainment ID: KHF352tM1PsAMDdINHjyb3-m. Time (UTC): 07/13/2021 06:12:40. Value cannot be null.

Parameter name: dialogId

## Describe the bug

see description above

## Version

2.0.0

## Browser

- [X] Edge

## OS

- [X] Windows 10

## To Reproduce

----

## Expected behavior

Transfer works seemslessy and the question from new dialog is displayed.

## Screenshots

PVA dialogs:

![image](https://user-images.githubusercontent.com/48097252/125403205-8da63d80-e3b5-11eb-8b3e-d1cd131eee07.png)

Dialog I want to transfer from

![image](https://user-images.githubusercontent.com/48097252/125402626-ea552880-e3b4-11eb-9d7d-d1b4ec3474cf.png)

Dialog I want to transfer to

![image](https://user-images.githubusercontent.com/48097252/125402393-a7935080-e3b4-11eb-88f6-c3062004ad0c.png)

**Comment by srinaath** [comment]
We are looking to get a repro @tamasschmolcz

**Comment by tamasschmolcz** [comment]
@srinaath Is there any further action from my side needed? Happy to help.

**Comment by tonyanziano** [comment]
@tamasschmolcz we are unable to reproduce this issue on our end.

To clarify, you have a bot that:

- has a Composer dialog
- this Composer dialog eventually calls another Composer dialog using a BeginDialog action

If the above are true, is it possible for you to share your bot assets with us so we can debug?

**Comment by tamasschmolcz** [comment]
@tonyanziano I have solved it now by putting the affected part in a dedicated dialog, as the need emerged, that I need to use the "Hast du weitere Fragen?" dialog for other dialogs as well.

But yes you understand the situation correctly. + the dialog are uploaded and executed with a PVA (PVA Composer Integration).

So case can be closed. If I face it again, I'll let you know asap + providing bot assets.

Btw. can you have a look at my question at https://github.com/microsoft/BotFramework-Composer/discussions/8320  ?

I am heavily using the PVA Composer Integration Features, which have been released recently and want to max out the possibilities :).

Appreciate your help so far in my cases!
