### ISSUE TITLE
LU Editor - Warning shown on a new editor with no content (only place holder)

### ISSUE THREAD

**Issue by hatpick** [microsoft/BotFramework-Composer#8392]
## Describe the bug

LU language server shows warning for a new LU editor with no content and no interactions from user:

```L17:0 - L17:27 no utterances found for intent definition: "# TextInput_Response_hrdwg8"Refer to the syntax documentation here.```

## Version

Latest on main.

## Browser

1. Create an empty but
2. Add "Ask a question/Text" node.
3. Select "User input(text)" so you can see an LU editor in the property editor on the right.
4. Observe that with a placeholder all commented out, LU server is throwing a warning.

## Expected behavior

Dont show warning for an editor that user hasn't interacted with and has only comments or no content.

## Screenshots

![Screen Shot 2021-07-13 at 4 04 08 PM](https://user-images.githubusercontent.com/1483492/125536112-964fec3a-fd9a-481b-aa96-47d464d55af7.png)

**Comment by gabog** [comment]
Hi @cwhitten, excluding this one from DRI, please review and see if it needs to be added to the composer's backlog or closed
