### ISSUE TITLE
Opening projects should start with child dialogs collapsed

### ISSUE THREAD

**Issue by Stevenic** [microsoft/BotFramework-Composer#8409]
When you open an existing project, the tree view starts with every single dialog expanded. For large project this could result in hundreds of events being displayed. This would be like VS Studio/Code starting with every project folder expanded. We should either start with all child dialogs closed (leave the root expanded) or remember the previous sessions expansion state. I personally find myself going through and closing every dialog on startup, just so I can make better sense of my projects structure.
  
![image](https://user-images.githubusercontent.com/698939/125731580-c7f5fa5f-d5d9-42eb-b884-90e98efe6a02.png)

**Comment by srinaath** [comment]
In addition, implementing a solution for this would help with the performance. Currently, the entire project tree with all the dialogs, triggers across root bots and skills are rendered on start. Instead we could go for a more lazily loaded project tree and load the assets inside a dialog on expanding. @mewa1024 @vivekkshankar

**Comment by vivekkshankar** [comment]
I think expanding the root (selecting a first trigger like we do currently) while closing all child dialogs might be the way to go for now.

I feel addressing scale here is the key issue and there are def. other things to consider and user test going forward, 
- Remembering previous selections
- Auto collapsing dialogs not selected
- Lazy loading
