### ISSUE TITLE
Issue with accessing a Power Virtual Agent Property using Composer

### ISSUE THREAD

**Issue by tamasschmolcz** [microsoft/BotFramework-Composer#8422]
## Describe the bug

I want to set a Power Virtual Agent property in Composer. I use the "set a property" composer function to set the PVA property "powervirtualagent.buergerbueroContact"

![image](https://user-images.githubusercontent.com/48097252/125915438-09d1e5c0-34af-4343-8986-f1375fdc6273.png)

The mentioned property is used in a specific PVA flow initially.

![image](https://user-images.githubusercontent.com/48097252/125915540-3a33ccd3-0484-4af9-b6b6-0eac698d8246.png)

The PVA throws the error "Cannot convert variable new_variable"

A problem occurred while running the Composer dialog. Cannot convert variable new_variable_f0ed4e95838e44bfa65eb28d87f2238e_eb6e3060e7d94d9a9f964566d67cd344 to a namedEntity

Do I do anything wrong?

Thank you

## Version

2.0.0

## Browser

- [X] Edge

## OS

- [X] Windows 10

## To Reproduce

see bug description above

## Expected behavior

The property value is set in Composer, so I can skip several questions in the PVA topic flow to output a specific information.

**Comment by iMicknl** [comment]
@tamasschmolcz the PVA screenshot below, is that your 'Burgerburo' flow? Could it be that you are using this property within Composer, before it is created in Power Virtual Agents?

If that is the case, I am not sure if this is a supported scenario. https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer#use-and-update-power-virtual-agents-variables-in-bot-framework-composer
Someone from the team can hopefully respond on the supported scenarios.

**Comment by tamasschmolcz** [comment]
@iMicknl Yes I think that could be issue. That would be a pitty, if the flow needs to executed before.

Do you know, if I also can access Composer properties via PVA flow?

**Comment by tonyanziano** [comment]
There appears to be a bug on the PVA side, and I have filed an issue with them.

I will follow up on this thread with any updates.

**Comment by tamasschmolcz** [comment]
@tonyanziano Thanks! could also clarify my question, whether there is a way to access Composer properties from a PVA flow? And if not, do exist plans to allow this in the future?

**Comment by benbrown** [comment]
@tonyanziano any news on this?

**Comment by tonyanziano** [comment]
I just pinged the PVA team and they are still investigating.

**Comment by tracyboehrer** [comment]
@tonyanziano any news on this?

**Comment by tonyanziano** [comment]
@tamasschmolcz It turns out that this is currently an unsupported scenario in PVA and is by design, because when using a mutli-choice prompt in PVA it actually stores the value as a ClosedListType variable in the back-end. In Composer, when you are trying to set the property, you are using a string, which is a type mismatch and that is what causes the error.

It might eventually be supported in the future, but for now it is by design.
