### ISSUE TITLE
[skills] Import Skill LU Editor shows errors for valid LU

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-Composer#8423]
## Describe the bug
While adding a new skill from a zipped manifest, the LU Editor shows  multiple LU errors because the intent names are commented out which is correct for this scenario. 

## Version
Latest nightly

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Add a new skill from this [zipped manifest](https://github.com/microsoft/BotFramework-Composer/files/6832268/FirstBot_test_manifest.zip)

## Expected behavior
The LU Editor should not show any errors while importing a new skill if the LU is valid

## Screenshots
![image](https://user-images.githubusercontent.com/17039790/125983288-31af7ef4-6d22-46db-a165-583ae3135cd0.png)

## Additional context
@EricDahlvang @gabog

**Comment by luhan2017** [comment]
@tdurnford could you try the latest nightly? Both zhixiang and I tried and didn't reproduce this issue in the latest nightly.

**Comment by tdurnford** [comment]
@luhan2017 Looks like this is resolved in the latest nightly.
