### ISSUE TITLE
Product Tour: Publish setup has no description

### ISSUE THREAD

**Issue by Vivihung** [microsoft/BotFramework-Composer#8424]
## Describe the bug
After installing desktop composer, the Product Tour about publishing the bot has empty instruction. 

## Version
Desktop Composer for Windows.
Version: 2.0.0
SDK runtime package: 4.12.0

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Fresh install the desktop Composer app in Windows. The tutorial mode will auto-popup. Go through each step until reach the publish instruction.

## Expected behavior
There should be description in the pop-up bubble about publishing a bot.

## Screenshots
![image](https://user-images.githubusercontent.com/4814277/126007800-2b83e74f-4bd0-4359-97d5-2bdc9e9d730a.png)

## Additional context
(none)

**Comment by tdurnford** [comment]
@Vivihung This is resolved in the latest Composer Nightly, and the fix will be included in our upcoming release. Thank you for reporting the issue!

![image](https://user-images.githubusercontent.com/17039790/126012259-9e1a4816-9278-4533-8746-1e6bfcb7c224.png)
