### ISSUE TITLE
The resource 'qna_maker' already exists in location 'westeurope' in resource group 'name'. A resource with the same name cannot be created in location 'westus'

### ISSUE THREAD

**Issue by geo-msft** [microsoft/BotFramework-Composer#8427]
## Describe the bug
When provisioning new resources from composer desktop 2.0, the provision partially completes because of this error 

<i> The resource 'compo19july' already exists in location 'westeurope' in resource group 'compo19july'. A resource with the same name cannot be created in location 'westus' </i> 

when it reaches the QnA maker provisioning step. 

## Version

Version:  2.0.0-nightly.257298.f833d8e
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new publish profile in Composer
2. Choose Create New Resources, 
3. Create a new resource group, and resources, using the same name for both the resource group and resource details. Region: West Europe 
4. Select all required resources (additionally selecting the optional ones makes no difference)
5. Wait for the provisioning to be done. 

## Actual result 
The QnA maker resource does not get created because the provision fishes with this error 

![image](https://user-images.githubusercontent.com/57954688/126117114-dcbd6937-2b3d-4ea6-9f76-a4c3e986954c.png)

The log file in the folder does not provide additional info: 

{
  "profileName": "Profile19thJune",
  "jobId": "a028f8fa-18d4-4f5a-9477-9ca7df17c47d",
  "projectId": "92093.46661602269",
  "time": "2021-07-19T06:47:04.425Z",
  "log": [
    "Creating Azure resources...",
    "Checking the Existence of the Resource Group ...",
    "Creating Resource Group ...",
    "> Creating App Registration ...",
    "Start to add password for App, Id : 805d667a-e619-4c52-b8b2-f4869bae63aa",
    "> Create App Registration Success! ID: 805d667a-e619-4c52-b8b2-f4869bae63aa",
    "Deploying Web App Resource ...",
    "Deploying Bot Resource ...",
    "Deploying Application Insights Resource ...",
    "> Linking Application Insights settings to Bot Service ...",
    "> AppInsights AppId: dffd36d1-f253-4914-9151-28e97ca30da0 ...",
    "> AppInsights InstrumentationKey: 39aa1e0e-937a-43cd-9161-763c719c5241 ...",
    "> AppInsights ApiKey: at1fxbo45g44zs8gxrdrls1ks8upjhvolfngcbvt ...",
    "> Linking Application Insights settings to Bot Service Success!",
    "Deploying Blob Storage Resource ...",
    "Deploying Luis Authoring Resource ...",
    "Deploying Luis Resource ...",
    "Deploying QnA Resource ...",
    "{\"stack\":\"Error: The resource 'compo19july' already exists in location 'westeurope' in resource group 'compo19july'. A resource with the same name cannot be created in location 'westus'. Please select a new resource name.\\n    at new RestError2 (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:129632:26)\\n    at C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:130565:27\\n    at async AzureResourceMananger.deployQnAReource (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:225173:33)\\n    at async BotProjectProvision.create (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:226009:36)\\n    at async AzurePublisher.asyncProvision (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:226408:34)\",\"message\":\"The resource 'compo19july' already exists in location 'westeurope' in resource group 'compo19july'. A resource with the same name cannot be created in location 'westus'. Please select a new resource name.\",\"code\":\"InvalidResourceLocation\",\"statusCode\":409,\"request\":{\"body\":\"{\\\"location\\\":\\\"westus\\\",\\\"sku\\\":{\\\"name\\\":\\\"S1\\\",\\\"tier\\\":\\\"Standard\\\",\\\"size\\\":\\\"S1\\\",\\\"family\\\":\\\"S\\\",\\\"capacity\\\":1}}\"},\"response\":{\"body\":\"{\\\"error\\\":{\\\"code\\\":\\\"InvalidResourceLocation\\\",\\\"message\\\":\\\"The resource 'compo19july' already exists in location 'westeurope' in resource group 'compo19july'. A resource with the same name cannot be created in location 'westus'. Please select a new resource name.\\\"}}\"},\"body\":{}}",
    "{\"name\":\"CREATE_QNA_ERROR\",\"message\":\"Error - The resource 'compo19july' already exists in location 'westeurope' in resource group 'compo19july'. A resource with the same name cannot be created in location 'westus'. Please select a new resource name.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:224307:25)\\n    at createCustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:224312:10)\\n    at AzureResourceMananger.deployQnAReource (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:225306:13)\"}",
    "Provisioning completed 7 items before encountering a problem. {\"name\":\"CREATE_QNA_ERROR\",\"message\":\"Error - The resource 'compo19july' already exists in location 'westeurope' in resource group 'compo19july'. A resource with the same name cannot be created in location 'westus'. Please select a new resource name.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:224307:25)\\n    at createCustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:224312:10)\\n    at AzureResourceMananger.deployQnAReource (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:225306:13)\"}. See provision.Profile19thJune.log in your bot folder"
  ]
}

## Expected behavior
The provision should be successful.

**Comment by geo-msft** [comment]
If west europe is not a valid region for the qna maker, I believe the error message should be clearer. Plus, a hover over button suggesting QnA maker available regions would be great.

**Comment by srinaath** [comment]
@geo-msft While provisioning the QNA resource, if you have already published the qna resource in a particular region, the name of the qna resource needs to be unique across regions. Could you try using the existing QNA resource to publish again and see if that works?

**Comment by geo-msft** [comment]
I did not previously provision that resource, I started the deployment with 'Create new resources' in the publish profile.

**Comment by natalgar** [comment]
@geo-msft and I were able to reproduce this 
Steps to reproduce the behavior:

1. Create a new publish profile in Composer
2. Choose Create New Resources, 
3. Create a new resource group, and resources, using the same name for both the resource group and resource details. Region: West Europe 
4. Select all required resources (additionally selecting the optional ones makes no difference)
5. Wait for the provisioning to be done. 
![Uploading image.png…]()

**Comment by natalgar** [comment]
@geo-msft We're doing a little more investigation here before pushing a fix.
