### ISSUE TITLE
Accessing Composer variables

### ISSUE THREAD

**Issue by tamasschmolcz** [microsoft/BotFramework-Composer#8428]
Hello,

I have nothing found in documentation, but it seems, PVA can access Composer Properties?  I did nothing intentionally, but PVA access the Composer variable "buergerbuero". In my example it contains already a value, so the PVA flow question around the location is skipped. 

Does this mean, any composer property with scope "user.", can be access via the scope "bot.property" in PVA?

![image](https://user-images.githubusercontent.com/48097252/126130394-3bc4899f-3886-4dac-80ea-8935e4897d5c.png)

**Comment by tonyanziano** [comment]
Hello @tamasschmolcz ,

As far as I know, variables set within Composer memory scopes (`user`, `dialog`, `turn`) are not accessible within the PVA authoring canvas.

Composer should only be able to access and modify global variables stored in PVA via the `virtualagent` memory scope, but the other scopes will not be exposed.

Maybe @babrekel or @abharath27 can confirm.

**Comment by tamasschmolcz** [comment]
@tonyanziano yes thats my understanding as well, so I am wondering about my current experience .

**Comment by tonyanziano** [comment]
Sounds good.

If you do happen to succeed in reproducing the issue again, can you please list the minimum number of steps you followed in order to reproduce the issue?
