### ISSUE TITLE
Set a property: value - Bug Warning?

### ISSUE THREAD

**Issue by AndreCorreiaInspire** [microsoft/BotFramework-Composer#8429]
Hi!

I have a user.vacation_days property representing an array with datetime objects and I'm trying to set the turn.vacation_list property to store the same but beautified objects to then show them to the user, keeping the user property intact.

I achieved my goal with the operation showing in the image below, it works just fine like I want it to. However, Composer recognizes it as a warning that won't go away.

![setapropertybug](https://user-images.githubusercontent.com/87659329/126181526-6445d0d0-51d2-456b-b2c8-9450226bb008.PNG)

Removing the '=' from the value field seems to clear the warning but then the property will instead save a string of that exact query instead of my intended beautified datetime objects.

I'm working on Windows and this is my installed Composer's About prompt:

```
Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```

I apologize if this has been issued before. I'd like to know if this issue is simply a bug I can ignore or if there's an actual reason behind the warning and/or a corresponding fix.

**Comment by srinaath** [comment]
@AndreCorreiaInspire Could paste the entire expression that your are trying to set in that action for us to evaluate the return data type?

**Comment by AndreCorreiaInspire** [comment]
Hello @srinaath I did manage to fix this by creating a bot response under a Common namespace "customFn" with the template: 

```# beautifyRequest(vacation_list)
- ${join(select(vacation_list, x=> beautDate(x)), '\n\n')}```

The transDate.beautDate(x) operation was part of another namespace I had prior to finding this warning. As of now I just add ${customFn.beautifyRequest(user.vacation_days)} to a response field and everything is good.

As you requested however, this is the expression I was using before to set the property:

```turn.vacation_list = join(select(user.vacation_days, x=> transDate.beautDate(x)), '\n\n')```

And as part of my previous "transDate" namespace, I should have included these when I first created the issue as well:

# beautDate(timestamp)
- ${addOrdinal(dayOfMonth(timestamp))} of ${getMonthText(month(timestamp))} ${year(timestamp)}

# getMonthText(monthInt)
- SWITCH: ${monthInt}
- CASE: ${1}
    - January
-CASE: ${2}
    - February
- CASE: ${3}
    - March
-CASE: ${4}
    - April
- CASE: ${5}
    - May
-CASE: ${6}
    - June
- CASE: ${7}
    - July
-CASE: ${8}
    - August
- CASE: ${9}
    - September
-CASE: ${10}
    - October
- CASE: ${11}
    - November
-DEFAULT:
    - December
