### ISSUE TITLE
Error when create new bot

### ISSUE THREAD

**Issue by AdriVazquez** [microsoft/BotFramework-Composer#8431]
Hi, 
I want to create a new Node _Core Bot with Language_ bit I get an error: 
`Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with ENOENT: npm root -g --prefix /home/XXX/BotFrameworkComposer/.yo-repository --loglevel error spawnSync npm ENOENT`
I'm using Ubuntu 18.04. I have check my node and npm version: `npm -v      6.14.11`  `node -v     v14.8.0` but it is still failing. What can I do?

**Comment by arotena** [comment]
I have the same problem with the Bot Framework Composer v0.0.2

**Comment by dmvtech** [comment]
Hi @AdriVazquez and @arotena 

If you are running the standalone electron/app, and not running your own build of Composer, can you please got to the `Help->About` menu, then click `copy`. That should give more version info. For example, I have:

```
Version:  2.0.0-nightly.260069.26b6d19
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```

@tonyanziano

**Comment by AdriVazquez** [comment]
Hi, this is my info:

```
Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```

**Comment by tonyanziano** [comment]
I was not able to reproduce this on the most recent Nightly version on Ubuntu 18.04.3 LTS with Node 16.4.1 and npm v7.18.1.

Can you please try the [most recent nightly release found here](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.0.0-nightly.260069.26b6d19)?

![image](https://user-images.githubusercontent.com/3452012/126382758-0f57c806-8218-49d1-8ca0-879921697ef6.png)

**Comment by tonyanziano** [comment]
@AdriVazquez @arotena How do you both normally start your `.AppImage` apps? Do you double click the shortcut after making it executable?

If so, please try starting your Composer installation via the terminal as a workaround.

1. Open a terminal tab
2. Navigate to where Composer is installed
3. run the command `./BotFramework-Composer-<version>-linux-x86_64.AppImage`

**Comment by arotena** [comment]
Perfect @tonyanziano this works for me. Thank you!!

**Comment by AdriVazquez** [comment]
@tonyanziano That is! 
running the command works for me. Although it would have been a good way from the beginning, I had not thought about it because I followed the instructions in https://docs.microsoft.com/en-us/composer/install-composer?tabs=linux. 
Thank you

**Comment by hatpick** [comment]
@arotena @AdriVazquez Would you please tell us how did you install NodeJs on your Ubuntu?

**Comment by arotena** [comment]
Hi @hatpick 
I follow this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04-es) with the option 3
The result of `which node` in my terminal is: `/home/xxxxx/.nvm/versions/node/v12.2.0/bin/node`

**Comment by hatpick** [comment]
@arotena the reason you have the original issue is that node is not on your PATH (env variable) when you run Composer normally. In order for nvm to manage multiple versions of node, it needs to keep the executables under .nvm and then add it to current user profile PATH. 
Ubuntu runs AppImage apps in a different context that does not load your user bash profile. So as a result it's not aware of the path that nvm uses for executables. To fix that, you need to create a couple of symlinks to make node and npm available for all users:

```bash
sudo ln -s `which node` "/usr/local/bin/node"
sudo ln -s `which npm` "/usr/local/bin/npm"
```
