### ISSUE TITLE
Package Manager does not work with private feeds with authentication

### ISSUE THREAD

**Issue by mhtmht** [microsoft/BotFramework-Composer#8432]
## Describe the bug

Error in package manager when trying to access private Nuget feed hosted on Azure DevOps Artifacts

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Start Composer
2. Go to Package Manager
3. Click Edit feeds
4. Add a new private Nuget feed - in this case it is Azure DevOps Artifacts based Nuget feed
5. Click Done
6. Select newly added private Nuget feed from the feed dropdown menu
7. See the resulting error message in popup. Result is HTTP Status code 401 - Unauthorized.

## Expected behavior

Able to access private Nuget feed by either setting up needed credentials in bot project or by input through Composer interaction.

## Screenshots

Sample of error message

![composer-nuget-auth-error-20210718](https://user-images.githubusercontent.com/1146203/126312086-9cf81e9e-7230-4771-96e1-a720afc63751.png)

## Additional context

Private Nuget feed works without issues when used from PowerShell/Terminal

**Comment by benbrown** [comment]
@mhtmht Are you able to use a feed with the authentication details included? Composer does not support feeds that require interactive login to access.

**Comment by mhtmht** [comment]
> @mhtmht Are you able to use a feed with the authentication details included? Composer does not support feeds that require interactive login to access.

Good to now that interactive login is not supported for package manager. Might be good to highlight that in documentation as interactive login for provisioning might confuse other adventurers also.

I have not as I'm aware of how to pass the needed information to Nuget. Is there an example somewhere that I could take a look at? If not then this might also be a good addition to documentation. Until/if interactive login is supported.

**Comment by mhtmht** [comment]
@benbrown
In reference to my last comment any pointers on how to pass the authentication details with the feed url through Composer?

As a work around we are hosting a local feed but the ability to use private feeds with authentication would be super helpful in bigger development teams.

**Comment by benbrown** [comment]
@mhtmht sorry for the delay in my response here -- 

Azure devops artifact feeds do not support the inline authentication. However, myget feeds do -- is it possible to use that system?

**Comment by srinaath** [comment]
@mhtmht Did you try swapping the feed to use MyGet instead of ADO?

Closing this ticket due to inactivity,
