### ISSUE TITLE
Composer loses PVA topics

### ISSUE THREAD

**Issue by tamasschmolcz** [microsoft/BotFramework-Composer#8433]
## Describe the bug

From time to time Bot framework composer loses all known PVA Topics and I need to restart the tool or sync composer from scratch, initiating the sync via PVA center. I did not find a certain patter yet, but maybe there are logs for analyziation?

## Version

v2.0.0

## Browser
- [X] Edge

## OS
- [X] Windows 10

## To Reproduce

I just uses composer regulary and after a while and syncs, the PVA topics are gone and I see only "cryptic" numbers in my dialogues, where PVA topics are involved.

## Expected behavior

Not loosing PVA topics.

**Comment by srinaath** [comment]
@tamasschmolcz
1. During this process, is there any topic from PVA that gets imported at all into Composer?
2. Could you paste a screenshot of the Design Page post import in Composer?
3. Could you share the environment, Bot ID and tenant ID for us to dig into the PVA logs. It should be inside the botfolder/settings/appsettings.json under the key publishTargets?

**Comment by tamasschmolcz** [comment]
@srinaath  Not sure we are at the same page. I am loosing the PVA topics after a while without any action (sync etc.).  Just by using Composer ( though it did not happen today). Doing a restart and new sync helps to re-import all PVA topics.

botId: f0ed4e95-838e-44bf-a65e-b28d87f2238e
tenantId:81814973-9a47-4fb4-8feb-139dcaef5bc8

**Comment by srinaath** [comment]
@tamasschmolcz 
This bug does not seem to be related to PVA @tamasschmolcz . Could you give us some detailed repro steps and screenshots of the Composer  Design Page post the import process?

**Comment by tamasschmolcz** [comment]
I have not experienced issue anymore. I suppose it is/was a local problem.

Thanks anyway.
