### ISSUE TITLE
How can I check for a LUIS intent to validate a user text prompt?

### ISSUE THREAD

**Issue by lshade** [microsoft/BotFramework-Composer#8438]
My dialog prompts a user for text input, and I want to validate that the user's response was in 1 of 2 LUIS intents. These aren't intents that trigger new dialogs. How can I add these new intents inside Composer and validate that the user said something that matched to one of them?

**Comment by lshade** [comment]
Is the answer to edit the LU code in the User input blade?

**Comment by lshade** [comment]
Update. I got it working with this validation rule
![image](https://user-images.githubusercontent.com/16640521/126409986-ba8a45f3-55d6-4c54-a862-058759725504.png)

Please let me know if there was a more straight-forward way to do this.

**Comment by anusharavindrar** [comment]
@lshade, the above validation rule method which you used is the best suited way to validate the user's response. Please refer to https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input?tabs=v2x#prompt-settings-and-validation and https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather?tabs=v2x#set-validation-rules for more details.
