### ISSUE TITLE
[Skills workflow] Removing skill from an empty bot shows error for missing LUIS keys

### ISSUE THREAD

**Issue by tdurnford** [microsoft/BotFramework-Composer#8442]
## Describe the bug
Removing skill from an empty bot shows error for missing LUIS keys

## Version
Version:  2.0.0-nightly.260493.e017820
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce

1. Add PVA Skill to an empty bot in Composer
2. Do not opt in to use orchestrator 
2. Remove Skill
3. Observe the error

## Expected behavior
Composer should not require LUIS Key/Region for an empty bot

## Screenshots
![image](https://user-images.githubusercontent.com/17039790/126535137-8e655acf-d957-4d27-a2d1-124bd33c04bc.png)

**Comment by luhan2017** [comment]
I found that is not a skill specific issue and it can't be consistently reproduced, I tried to add a trigger and remove it, the trigger name also remains in the lu file. 

In an empty bot, I added a trigger "aaaaaaa" and a skill "Skill Test Marina", then I remove "Skill Test Marina" and "aaaaaaa", Here is what I see from the lu editor: 
![image](https://user-images.githubusercontent.com/32191031/126584198-a8ad08f0-8628-463b-b03d-3cce9c8b9383.png)
 
@boydc2014 @lei9444 @zhixzhan
