### ISSUE TITLE
Do While Loop in Composer

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/BotFramework-Composer#8448]
## Describe the bug

My apologies if it is there but I am not able to find a way to implement **Do While** functionality to my Composer. I think it'd be a great feature. 

I tried to edit the _dialog.foreach.index_ in the foreach loop as a workaround but this did not work for me. 

Is there a way to achieve it?

## Version

v2.0.0-nightly(x.x.x)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
Hi @arafattehsin You can accomplish this with a custom action.

Please see one example here:
https://github.com/EricDahlvang/AdaptiveDoWhile

Also some more details/samples/info/background here:
https://github.com/microsoft/BotBuilder-Samples/pull/3114
https://github.com/EricDahlvang/BotFramework-Composer/pull/3
https://github.com/microsoft/BotFramework-Composer/issues/4761

**Comment by arafattehsin** [comment]
Thanks @dmvtech - I will try to fork this and deploy this to my local feed. It may not be super user friendly for everyone to deploy this though esp. for those who are focusing more on the low code creation.

**Comment by arafattehsin** [comment]
Unfortunately, when I tried to put it in the dialog, I started getting `Object set to no reference..` and then just to try I put it in the Greeting trigger, I got this;

![image](https://user-images.githubusercontent.com/16351038/126758486-ea22a227-ac8a-41ae-b773-22c1b68871be.png)

I also tried to debug it by attaching a process but it did not reach there.

**Comment by EricDahlvang** [comment]
Hi @arafattehsin 

Unfortunately, I don't think we have an example of a custom DoWhile component using the new sdk BotComponent dependency injection automatic registration.  

Also, it should no longer be necessary to modify the Composer source, but it should be possible to define the flow type within the .uischema:

```
"flow": {
    "widget": "ForeachWidget",
    "nowrap": true,
    "loop": {
      "widget": "ActionCard",
      "body": "=action.condition"
    }
  }
```

If you are using the old registration method, and not BotComponent, then it will be necessary to add code to the consuming project to register the component programatically. 

Are you able to share your implementation in an example project?

**Comment by arafattehsin** [comment]
Hi @EricDahlvang 

Thanks for your response. I've got the action from this [link](https://github.com/microsoft/BotBuilder-Samples/commit/bdcd59956f40a9b17a557ca830f1bf68b143f765) and built it, add it to my local nuget and install it in Composer like just another new package (using BotComponent, I think) 

After adding it, I can see the package is there;

![image](https://user-images.githubusercontent.com/16351038/127398332-eada726a-179e-4a03-9d6e-5f51c94033ef.png)

Then I tried to use it in my bot; 

![image](https://user-images.githubusercontent.com/16351038/127398405-e7cb89be-c990-4b2e-a9fa-f1b3fc8f8978.png)

I have set the loop's condition as true. Question's `always prompt` property is set to true as well.

![image](https://user-images.githubusercontent.com/16351038/127398533-2bf05d95-862b-4c63-8f9a-02407413b911.png)

I get this response;

![image](https://user-images.githubusercontent.com/16351038/127398971-f6dc654e-8382-4aa5-9a59-e15c9ea8068a.png)

Okay then I thought it must be some condition so I changed the condition in the loop as below;

![image](https://user-images.githubusercontent.com/16351038/127399095-7d30ee98-9a93-4efb-9280-2b076206fc6e.png)

But again;

![image](https://user-images.githubusercontent.com/16351038/127399143-581c71b1-cbc0-462e-89b8-07e1ba7421d2.png)

P.S. I'm using Composer v.2.1.0 now.

**Comment by EricDahlvang** [comment]
Custom action component registration is different in the new bot runtime (Composer v2.1.0)

If your DoWhile action is within a referenced project, then use `BotComponent`:
```cs
    public class UnileverCoreBotComponent : BotComponent
    {
        public override void ConfigureServices(IServiceCollection services, IConfiguration configuration)
        {
            services.AddSingleton<DeclarativeType>(sp => new DeclarativeType<DoWhile>(DoWhile.Kind));
        }
    }
```

Otherwise, if it is in the same project then I think it just needs to be registered with DI as `DeclarativeType`:

```cs
services.AddSingleton<DeclarativeType>(sp => new DeclarativeType<DoWhile>(DoWhile.Kind));
```

This ensures the adaptive runtime is able to find the code to execute for the declarative 'DoWhile.Kind`

This documentation might also be helpful:
https://docs.microsoft.com/en-us/composer/how-to-create-packages

**Comment by arafattehsin** [comment]
Thanks Eric - I just realized that BotComponent part, it makes clear to me now. 🤘

I am closing this issue and open up a feature request later.
