### ISSUE TITLE
Unable to publish virtual agents to azure

### ISSUE THREAD

**Issue by asaha7070** [microsoft/BotFramework-Composer#8453]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by srinaath** [comment]
@asaha7070 This isn't currently supported. PVA bots are imported into Composer with their publishing profiles already set. We have a work item to block creation of a new profile in this scenario. Closing this as a dupe of https://github.com/microsoft/BotFramework-Composer/issues/8453
