### ISSUE TITLE
Publish as skill failed: publishing from desktop 2.0 with new resources

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#8457]
## Describe the bug

Tried to publish a bot as a skill, but got a provisioning error.

## Version

Version:  2.0.0-nightly.260742.141dd34
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create and test a skill locally.
    - I left the skill bot running, because Composer should be able to clean house.
2. Export the bot as a skill. 
    1. Fill in the fields on the **Export your skill** page.
    2. Select the root dialog of the skill on the **Select dialogs** page.
    3. Don't select any of the triggers on the **Select triggers** page. (The one I want to use is not listed.)
    4. On the **Which bots can connect to this skill?** page, select **Add allowed callers** and set it to `*`.
3. Create a publishing profile for the skill
    - Publish to Azure, create new resources, deselect all optional resources, use Windows.
    - When prompted, sign in to my account.
    - Wait for Composer to provision and publish the skill.
4. See error.

***This error has been anonymized and formatted for readability***

```json
{
  "name": "CREATE_APP_REGISTRATION",
  "message": "Add application password failed! Please file an issue on Github.",
  "stack": "Error
    at new CustomizeError (...\AppData\Local\Programs\v1Composer\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\dist\extension.js:269071:25)
    at createCustomizeError (\AppData\Local\Programs\v1Composer\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\dist\extension.js:269076:10)
    at BotProjectProvision.createApp (...\AppData\Local\Programs\v1Composer\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\dist\extension.js:270602:17)"
}
```

## Expected behavior

Composer provisions and publishes the skill. I have been able to publish a skill in the past.

## Additional information

1. Stop all bots and try to re-export the skill as a skill.
2. Error: Nothing happens.
    - Composer should clean up resources if the provisioning attempt failed. I should not be left in some indeterminate state.
3. It gets better:
    1. Go to the **Configure your bot** view.
    2. Switch to advanced settings.
    3. Manually add back in the `"*"` that Composer removed from the allowed callers list.
    4. Switch back to the **Create** view.
    5. Error: Composer automatically now drops into the export as a skill workflow.

**Comment by JonathanFingold** [comment]
I finally got the skill published, but Composer still ripped out "*" from the allowed callers list. Not ideal.

**Comment by luhan2017** [comment]
@JonathanFingold I can't reproduce this issue from my side. This is not a skill specific issue, please refer to #8283. This could caused by insufficent permission to create the App or the app creation api instability.  @GeoffCoxMSFT for awareness.

**Comment by JonathanFingold** [comment]
I'll close for now and open a new issue if I hit this behavior again.
