### ISSUE TITLE
Array Object Properties Not Persisting Outside of Dialog

### ISSUE THREAD

**Issue by Cameron-Gonzalez** [microsoft/BotFramework-Composer#8459]
## Describe the bug

So I have an array, let's call it `user.questions` that I want to persist throughout the user's interaction with the bot. Every time I add an item to the array, I first create the item by creating a `dialog.question` with `dialog.question.index` and `dialog.question.text` properties, then push this item to the `user.questions` array.

When I am in a separate dialog, I go through each item using a foreach item node and want to send a response with the `dialog.foreach.value.index` and `dialog.foreach.value.text`, since each value in the foreach loop should be the item itself with the stored properties. I essentially just want the properties to persist across dialogs as objects do in normal applications. Is there another way of doing this that I am not aware of?

I understand I can use this process if I have set properties of an item and pushed to an array within the same dialog, but why wouldn't the same be true for data that should persist throughout the user's interaction?

## Version

v2.0.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an item by using the set properties node, and set at least two properties
2. Push the item to a user.array
3. In a separate dialog, use the foreach item node to iterate through the user.array
4. Use the send a response node to send the "Property: ${dialog.foreach.value.property}"
5. Notice that in the response, "Property:" will be sent as the response, since the dialog.foreach.value.property does not exist.

## Expected behavior

I would be able to access persistent data of array item properties in different dialogs.

**Comment by taicchoumsft** [comment]
Thanks @Cameron-Gonzalez for this detailed report.  @hatpick  , @srinaath , do you have any thoughts on this?

**Comment by dmvtech** [comment]
Hi @Cameron-Gonzalez 

It might be something slightly different in how you've set up your properties. I am able to get it to work. Let me share my bot with you and see if you can find any differences.

**Comment by dmvtech** [comment]
@Cameron-Gonzalez  Try my bot and see if it works for you.
https://github.com/dmvtech/testpropsinarray

If so, see if you can discern what the difference might be (or if I completely misunderstood the situation).

**Comment by dmvtech** [comment]
Closing as answered. If you are still having issues, please comment with updates and I can reopen.
