### ISSUE TITLE
Error during publishing a bot

### ISSUE THREAD

**Issue by mohsenualam** [microsoft/BotFramework-Composer#8461]
I was able to consistently modify and publish a bot to Azure, which was developed using Composer. I did some modification today, but receiving this error while trying to publish the bot:

> "These required resources have not been provisioned: Microsoft Language Understanding Authoring Account,Microsoft Language Understanding Prediction Account"

I haven't used any LU/LUIS features. The recent changes that I made don't have anything to do with LU.

## Version
Version:  2.0.0-nightly.261016.3eeeccc
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] Windows

**Comment by hatpick** [comment]
@mohsenualam what were the "modifications" you made?

**Comment by mohsenualam** [comment]
I just added a few new triggers and dialogues using same structures as existing ones.

However, I was able to fix it. My root dialogue's Recognizer was set to Regular Expression and all other dialogue's Recognizer was set to Default; this settings worked well with earlier version. I had to change all dialogue's Recognizer to Regular Expression, then I was able to publish the bot.

**Comment by hatpick** [comment]
Yeah the default recognizer uses Luis, you need to set them to Regex.
Sounds like your issue is fixed, closing it.
