### ISSUE TITLE
Is multi-level menu supported?

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#8462]
The following syntax seems providing a root menu spot, is there someway I can make more than two levels of menu to organize our components?

{
  "$schema": "https://schemas.botframework.com/schemas/ui/v1.0/ui.schema",
  "menu": {
    "submenu": ["My Bot Actions"]
  }
}

**Comment by tonyanziano** [comment]
@dawwa this is possible, please refer to our [new UI Schema documentation](https://github.com/microsoft/BotFramework-Composer/blob/main/docs/ui-schema.md#action-menu) to see how to accomplish this.

The example from the docs:

```JSON
{
  "menu": {
    "submenu": ["Microsoft Teams", "Get Teams Info"]
  }
}
```

Output:

![image](https://user-images.githubusercontent.com/3452012/127200523-d2c86ed6-55d1-4e70-802f-939a74538750.png)
