### ISSUE TITLE
Community package filter is missing in Package manager

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#8465]
## Describe the bug

Community package filter is missing in Package manager

## Version

Version:  2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Screenshots
![image](https://user-images.githubusercontent.com/16264167/126871299-f1489717-77f2-4543-ab54-a5e10ee56bbf.png)

**Comment by benbrown** [comment]
@rvinothrajendran the default nuget and npm feeds now contain any package with the msbot-component tag. This includes packages published by the community.  The community feeds found in earlier preview builds has been combined with this one.

You can create your own feed using different criteria using the "Edit Feeds" button in the toolbar.

Let me know if I am somehow misunderstanding.
