### ISSUE TITLE
Link to termplates doc gives 404

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#8473]
1. - Go to Composer docs
2. - go to '[Create your first bot with a template' ](https://docs.microsoft.com/en-us/composer/quickstart-create-bot?tabs=v2x)
3. Click ' template' 
4. Get 404 instead of documentation
See screenshots below

Im on a Mac, Chrome browser.

![Screen Shot 2021-07-26 at 10 38 40 AM](https://user-images.githubusercontent.com/48503434/127034022-06d94160-d147-492f-b12f-7b5fa80707c2.png)
![Screen Shot 2021-07-26 at 10 38 24 AM](https://user-images.githubusercontent.com/48503434/127034033-bec6e95e-2373-4b07-82aa-95e630627fb5.png)

**Comment by JonathanFingold** [comment]
This is a known issue and being tracked via https://github.com/MicrosoftDocs/composer-docs/issues/149.
