### ISSUE TITLE
Can't connect to remote skill: "Cannot read property 'default' of undefined"

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#8479]
## Describe the bug

Create a local root and a local skill bot, then publish and try to connect to the remote skill. Get mysterious behavior and error message:

> **Cannot read property...**  
> If this problem persists, please file an issue on GitHub  
> Details  
> Cannot read property 'default' of undefined

## Version

Version:  2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Get your ducks in a row.
2. Go to the **Create** view.
3. Select **Add** > **Connect to a skill**.
4. On the **Add a skill** page, add your remote manifest URL and select **Next**.
5. Error: Watch as you get a "Loading" message that then disappears, leaving you mysteriously with an enabled **Cancel** button and a disabled **Next** button.
    - Select **Cancel** to see the error that was being hidden by the **Add a skill** page.
    - Details: "Cannot read property 'default' of undefined"

## Expected behavior

1. If there is an error in the process, Composer reports it in a way that is visible to the user.
2. The root bot was consuming the skill locally without a problem, so it should be able to consume the remote one, too.
    - Guessing this is an issue with the generated manifest; so
3. The skill manifest Composer generates should not generate errors that keep the skill from being usable.

## Additional context

Here's the published manifest. Hazarding a guess, perhaps the issue is with line 5 (`{},`).

```json
{
  "$schema": "https://schemas.botframework.com/schemas/skills/v2.2/skill-manifest.json",
  "$id": "EchoSkill-77f2d105-09dc-4a69-bc4f-2da24dfff8dd",
  "endpoints": [
    {},
    {
      "protocol": "BotFrameworkV3",
      "name": "EchoSkill-0726",
      "endpointUrl": "https://v-jofin-echoSkill-0726.azurewebsites.net/api/messages",
      "description": "<description>",
      "msAppId": "5f0328b4-d4f0-45d1-ad56-035f5801571e"
    }
  ],
  "name": "EchoSkill",
  "version": "0.9.2",
  "publisherName": "me",
  "activities": {
    "EchoSkill": {
      "type": "event",
      "name": "startSkill"
    }
  }
}
```

**Comment by JonathanFingold** [comment]
Indeed, the following work around fixed my problem, but I don't want to instruct users to do this as a matter of course:

1. Copy the skill manifest from the remote URL.
2. Replace the local skill manifest with the copied one.
3. Remove the empty object from the endpoints list.
4. Republish the skill.
5. Now, you can can add the remote skill to your root bot project via the manifest. 🤦‍♂️

**Comment by srinaath** [comment]
@luhan2017 We are able to see this empty object inside the endpoints array when exporting the bot as a skill is done with no triggers selected. Could we try to resolve this?

**Comment by JonathanFingold** [comment]
Verified that the fix works for my test skill.
