### ISSUE TITLE
PVA "System Fallback function" not triggered from within Composer Dialog Interruption

### ISSUE THREAD

**Issue by tamasschmolcz** [microsoft/BotFramework-Composer#8482]
Not sure it is an expected behaviour: I set the "Allow Interruption" Flag to "True". This allows me to call a different PVA Topic without any problem from within a composer dialog. But I am not able to trigger the PVA System Fallback function, which is linked to qnamaker based on power automate. The System fallback works fine in general.

I am about to integrate now the Fallback via an "Unknown intent" + HTTP request towards qnamaker in composer directly. However I am still curious, what is the problem with the approach above.

Thanks

## Version

v2.1.0

## Browser

- [X] Edge

## OS

- [X] Windows

## Expected behavior

Allowing ChitChat / interruption during dialog via PVA System fallback function.

**Comment by tamasschmolcz** [comment]
I have the same experience, when using an "unknown intent" trigger build with composer, it is not triggered within a dialog. Flag "allow interruptions" is set to "True" . The given value should trigger it, as the value is not a an expected answer in the context of the dialog. Do I misinterpret the functionality?

**Comment by srinaath** [comment]
@tamasschmolcz We are investigating this today. The fallback topic is the equivalent of an Unknown Intent trigger implementation of Composer and hence if the interruption is not picked up by utterances of any topic it should be delegated to the Fallback Topic.

**Comment by tamasschmolcz** [comment]
@srinaath thanks ! apart from the issue -following your post ,  does this mean the „unknown intent  trigger“ in composer has no function due to the availability of the pva system fallback?

**Comment by tamasschmolcz** [comment]
@srinaath  @taicchoumsft   I tested the "unknown intend" functionality.

Scenario :  PVA Fallback Topic and "unknown intent" trigger in composer is setup.

"Unknown intent" Composer  trigger takes precedence over the Fallback topic. If removed, Fallback topic works.

However, as soon as I am in a "dialog" path and an input is expected, it is impossible to trigger one of them. The bot forces me to answer the expected answer, though "allows interruption" is activated.

Is this an expected behaviour?

**Comment by tamasschmolcz** [comment]
@srinaath  @taicchoumsft   I tested the "unknown intent" throughrly.

Scenario :  PVA Fallback Topic and "unknown intent" trigger in composer is set.

A PVA topic(dialog) uses the Fallback Topic.  An "Unknown intent" Composer trigger is used by an Composer dialog. So in an PVA / Composer Bot integration scenario, for both "dialoges" type the appropriate "Unknown Intent" trigger needs to be set. A "Composer" created dialog cannot use the Fallback Topic and vice versa.

However, as soon as I am in a _composer_ created "dialog" and an input is expected, it is impossible to trigger the "Unknown Intent" trigger. The bot forces me to answer the expected answer, though "allows interruption" is activated. The "unknown intent" trigger is linked to the main dialog.

Is this a bug or expected behaviour?

**Comment by taicchoumsft** [comment]
Hi @tamasschmolcz , thanks for the great investigation.  

I will dig deeper into the PVA fallback vs Composer/BF unknown intent implementations to see if we can eventually remove confusion around the two.

>However, as soon as I am in a composer created "dialog" and an input is expected, it is impossible to trigger the "Unknown Intent" trigger. The bot forces me to answer the expected answer, though "allows interruption" is activated. The "unknown intent" trigger is linked to the main dialog.

[This is expected behavior](https://github.com/microsoft/botbuilder-dotnet/issues/5071#issuecomment-819167633).  If you're in a multi-turn prompt with a user (for instance when asking for input), the unknown intent will not fire. 

An explanation and workaround was posted in the link attached (using the None intent, but please note the caveat pointed out in the linked comment)

**Comment by tamasschmolcz** [comment]
@taicchoumsft Thanks for the link, that makes sense !

But there is one thing left/difference left, which I saw  yesterday during the test. When being in a composer created dialog, striking out the given three attempts , the system uses the default value to move on. Can‘t I instruct the Bot to check now the „unknown intent“ trigger? And if nothing is found or the „unknown intent“ dialog is done, then the normal dialog is resumed and the default value is used? 

In a PVA topic the fallback is used after 2 attempts as described in the system options there.

**Comment by taicchoumsft** [comment]
Hi @tamasschmolcz , yes good catch it seems there is some extra work needed to wire up the retry prompt to the unknown trigger the way PVA does it.

It isn't ideal, but you can accomplish what you want with an if-else block following the input and a emitting a custom event that you can set to the unknownintent event. 

Something like this: 
![image](https://user-images.githubusercontent.com/61705609/127907554-7e48456a-07a2-411f-b44f-e7db3843dad5.png)

Let us know if this works well enough for this use case.
