### ISSUE TITLE
ECONNRESET error when publishing to existing resources

### ISSUE THREAD

**Issue by bradrlaw** [microsoft/BotFramework-Composer#8489]
## Describe the bug
Publishing from composer fails with a ECONNRESET error when attempting to publish to existing resources.  A large client is experiencing this behavior and we cannot see any information that could help debug / resolve the issue.

--- "{\"name\":\"DEPLOY_ZIP_ERROR\",\"message\":\"There was a problem publishing bot assets (zip deploy). {\\\"stack\\\":\\\"Error: read ECONNRESET\\\\n at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27)\\\",\\\"message\\\":\\\"read ECONNRESET\\\",\\\"code\\\":\\\"ECONNRESET\\\",\\\"config\\\":{}}\",\"stack\":\"Error\\n at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer 2_1_0\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269071:25)\\n at createCustomizeError (C:\\\\Program Files\\\\Bot Framework Composer 2_1_0\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269076:10)\\n at BotProjectDeploy.deployZip (C:\\\\Program Files\\\\Bot Framework Composer 2_1_0\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269587:13)\"}" --- --- "DEPLOY_Z11:57

## Version

Version:  2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a publish profile using existing created resources
2. Attempt to deploy the bot

## Expected behavior

The bot should deploy successfully

**Comment by srinaath** [comment]
@bradrlaw To help us understand the ticket furthur could you lets us know the size of the zipped assets being published and if its consistenly reproable. In addition, on the azure portal can you go check in the Advanced tools --> Tools --> zip Deploy UI. This interface should show real time logs as you publish the zip to azure.


![Screen Shot 2021-07-29 at 9 40 59 AM](https://user-images.githubusercontent.com/13004779/127531547-2a6b5df8-f024-4b5b-b805-0f1630ec1462.png)

![Screen Shot 2021-07-29 at 9 42 30 AM](https://user-images.githubusercontent.com/13004779/127531637-970b2247-7c1d-430c-bebd-3ff69e38754d.png)

**Comment by rakudtar** [comment]
@bradrlaw @srinaath I was also facing the same issue after upgrading the composer to 2.1.0. 

After spending some time i was able to figure out that when we select "Import Existing resource" while creating creating publish profile, it is not updating the configuration properly under: **configure your bot in composer --> Enable Advance settings view(json) --> publishTargets --> configuration**

![image](https://user-images.githubusercontent.com/88212361/127712759-fc0ecb5c-6544-4784-876b-f42212a07445.png)


**Configuration when used "Import Existing resource"**

 "configuration": "{\"name\":\"name\",\"environment\":\"composer\",\"tenantId\":\"#####-86f1-####-91ab-#####\",\"hostname\":\"App service name\",\"runtimeIdentifier\":\"win-x64\",\"resourceGroup\":\"resource Group\",\"botName\":\"bot Name\",\"subscriptionId\":\"#######-eee4-#####-935f-#######\",\"region\":\"southcentralus\",\"appServiceOperatingSystem\":\"windows\",\"scmHostDomain\":\"\",\"luisResource\":\"\",\"settings\":{\"applicationInsights\":{\"InstrumentationKey\":\"\",\"connectionString\":\"\"},\"cosmosDb\":{\"cosmosDBEndpoint\":\"\",\"authKey\":\"\",\"databaseId\":\"botstate-db\",\"containerId\":\"botstate-container\"},\"blobStorage\":{\"connectionString\":\"\",\"container\":\"\"},\"luis\":{\"authoringKey\":\"\",\"authoringEndpoint\":\"\",\"endpointKey\":\"\",\"endpoint\":\"\",\"region\":\"westus\"},\"qna\":{\"subscriptionKey\":\"\",\"endpoint\":\"\"},\"MicrosoftAppId\":\"App ID\",\"MicrosoftAppPassword\":\"Password\"}}"



I updated the configuration manually as below and it worked, i was able to deploy the bot with the profile created using "Import Existing resource" 


**"configuration": "{\n  \"name\": \"Botname\",\n  \"environment\": \"composer\",\n  \"tenantId\": \"Your Tenant ID\",\n  \"subscriptionId\": \"Your subscription ID\",\n  \"resourceGroup\": \"Your resource Group\",\n  \"botName\": \" Botname \",\n  \"hostname\": \"App service name\",\n  \"runtimeIdentifier\": \"win-x64\",\n  \"region\": \"Region\",\n  \"appServiceOperatingSystem\": \"windows\",\n  \"settings\": {\n    \"applicationInsights\": {},\n    \"luis\": {},\n    \"qna\": {},\n    \"MicrosoftAppId\": \"Your MicrosoftAppId \", \n    \"MicrosoftAppPassword\": \"Your MicrosoftAppPassword\"\n  }\n}"**

**Comment by anusharr** [comment]
Closing due to no response. Please feel free to reopen if issue persists.

**Comment by bradrlaw** [comment]
Please see the other issue filed, we cannot import resources anymore.  Composer is failing with a schema error at our client site and our machines.

https://github.com/microsoft/BotFramework-Composer/issues/8523
