### ISSUE TITLE
Skill added from zipped manifest files causes manifest URL to be broken in Composer

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#8490]
## Describe the bug

I've added a skill by using a zipped manifest. When I try to view the Manifest URL link in Composer for the skill, Composer opens a link in my browser that fails to resolve.

## Version

Version:  2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Follow initial instructions for importing a skill from a zipped manifest.
    - Create an empty bot and provision it.
    - Add a skill from a zip file.
    - The skill is added to the project.
1. Select the remote skill.
1. In the properties pane, see that the **Manifest URL**, **Endpoints**, and **Activities** properties all have what look like reasonable values.
1. Select the skill's manifest URL.
1. Error: Composer opens a browser tab for the bot that just just has a loading status that never completes.
    - If I work backward from the endpoint URL and construct what the remote skill manifest URL should be, that works correctly.

## Expected behavior

Either:
1. Show the local manifest file, locally in Composer, without opening the browser, or
1. Attempt to construct the remote manifest URL from the local manifest file, and open that, if it exists.

The first option is probably the best, since the skill developer may not have exposed a remote skill manifest.

## Screenshots

The link in Composer that takes me...nowhere?
![image](https://user-images.githubusercontent.com/35047199/127379507-967b8ebd-0d1c-4e68-8f4e-4df804171e1e.png)

Where the link in Composer takes me:
![image](https://user-images.githubusercontent.com/35047199/127377172-52bfffcd-075e-43f2-8794-09f63682e80b.png)

The actual remote manifest:
![image](https://user-images.githubusercontent.com/35047199/127379624-65aed772-7e80-46e3-b5bf-4d599b2f384e.png)

## Additional context

Having a hyperlink that goes nowhere is not a good feature.

**Comment by luhan2017** [comment]
@vivekkshankar , Do you have suggestion on this?
