### ISSUE TITLE
Issue Publishing Bot Framework Composer to Azure

### ISSUE THREAD

**Issue by Intelliteckai** [microsoft/BotFramework-Composer#8493]
When I try publishing the bot to Azure, I get the error

<img width="1151" alt="Screenshot 2021-07-26 at 12 20 16" src="https://user-images.githubusercontent.com/87998355/127523318-753103ed-36a2-4a33-a790-d4da97e9a7fc.png">

**Comment by srinaath** [comment]
@Intelliteckai Could you follow the issue template we currently have indicating the version of Composer, OS etc.

**Comment by Intelliteckai** [comment]
@srinaath I thought i was following the issues template on here as i used the "other" template. i didn't think the bug or feature request templates were appropriate. Do you have a particular one in mind? 

The version of the composer is 2.0.0, the operating system is mac os.
When you ask for the publishing profile, do you mean the .json file?

**Comment by Intelliteckai** [comment]
{
  "name": "smartdesk1",
  "environment": "Azure DevTest",
  "tenantId": "ba3c42f4-8aa0-47e6-a3d2-81faec4e7f4b",
  "hostname": "smartdesk1",
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "virtualDesk-RG",
  "botName": "smartdesk1",
  "subscriptionId": "4e81d975-8fdc-4321-a0fd-f7669f448db7",
  "region": "UK South",
  "appServiceOperatingSystem": "windows",
  "scmHostDomain": "",
  "luisResource": "smartdesk-PredictionResource",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "83d31d31-f927-4c9e-8774-0c7518886f51",
      "connectionString": "InstrumentationKey=83d31d31-f927-4c9e-8774-0c7518886f51;IngestionEndpoint=https://uksouth-1.in.applicationinsights.azure.com/"
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "",
      "authKey": "",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "",
      "container": ""
    },
    "luis": {
      "authoringKey": "04c6185c939e4c8aa4122f6907463c30",
      "authoringEndpoint": "https://westeurope.api.cognitive.microsoft.com/",
      "endpointKey": "b8e7284f0182469fa9f5bb851a9ca833",
      "endpoint": "https://westeurope.api.cognitive.microsoft.com/",
      "region": "westeurope"
    },
    "qna": {
      "subscriptionKey": "",
      "endpoint": ""
    },
    "MicrosoftAppId": "25b7394b-e09e-461c-920c-c058aa6fb0b6",
    "MicrosoftAppPassword": ""
  }
}

**Comment by srinaath** [comment]
@Intelliteckai I just deleted your previous comment due to sensitive info exposed in a public github repo.

**Comment by srinaath** [comment]
So, wht you had pasted was the appsettings.json. The publishing profile is in this view when hit "Edit". Its basically the data that is required to publish to azure. If you can "redact" sensitive data and paste the profile we could see what properties are missing in the profile. Another step to try is what is documented here https://github.com/microsoft/BotFramework-Composer/issues/8489. Basically checking the logs to get us a bit more information.
![Screen Shot 2021-07-29 at 12 08 33 PM](https://user-images.githubusercontent.com/13004779/127551631-26c5e87b-1d87-4d84-8e69-41d6ddeff669.png)

**Comment by Intelliteckai** [comment]
can you please be specific about what you need. I am not too familiar with the bot composer or azure bot service itself. 
there isn't any useful information from the diagram above. 
on clicking edit i get 3 options; create new resources, import existing resources or hand off to admin. I already have a bot in azure so i am using the import existing resource, so when i click next i get the json file. That's why i thought you want the  json file. 
So please which of the options should i follow?

**Comment by stevkan** [comment]
@Intelliteckai, to get to the publishing profile:

1. Click the 'Edit' button shown in the image above.
2. Select 'Import existing resources' and click 'Next'
3. Click into the frame that is housing the JSON
4. Copy and paste the JSON here ("redact" any sensitive data)

![image](https://user-images.githubusercontent.com/18403946/127697115-84de0425-59e9-41fb-a421-b9fa738dd989.png)

**Comment by Intelliteckai** [comment]
![image](https://user-images.githubusercontent.com/87998355/127774959-20c827f4-8642-4072-bd55-3e1938b234e6.png)

**Comment by Intelliteckai** [comment]
![image](https://user-images.githubusercontent.com/87998355/127775107-fc2ac6e3-1dd1-445e-beba-e6397373cda6.png)

**Comment by stevkan** [comment]
@Intelliteckai, I see that the "region" value is showing `UK South` when it should be `uksouth`. Can you update the profile and try and again to see if this is the source of the issue?

**Comment by Intelliteckai** [comment]
hi @stevkan i made this suggested change with your colleague Georgiana yesterday morning and the result it the same. 
As this is a development environment and bot, I have decided to trash the build and start again.
It has taken too much time and I am under time pressures.

I have removed the bot and all related cognitive services, please close this ticket.
