### ISSUE TITLE
Issue with multiple-choice questions after publishing

### ISSUE THREAD

**Issue by victorlamana** [microsoft/BotFramework-Composer#8495]
After I succesfully published my bot, both of my multiple-choice questions stopped sending the question prompt to the user (it only sends the answer array). On Composer it still works normally tho

Print on the web:
![image](https://user-images.githubusercontent.com/52974336/127556295-86c55444-00f1-491a-beda-8f503bdf9849.png)

Composer print with the question prompt:

![image](https://user-images.githubusercontent.com/52974336/127556399-12b9d1b4-f1f0-4d17-9e10-14f4375e3f66.png)

V2.1

## Browser

- [x ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create node.js bot on composer
2. create multiple-choice question with array for the answers
3. publish bot on azure and test it on webapp

## Expected behavior

Show the question prompt 

## Additional context

This is weird, am I doing something wrong? This seems like a bug

**Comment by victorlamana** [comment]
Tried on the Azure portal and same results:

![image](https://user-images.githubusercontent.com/52974336/127571028-e87724f5-0c64-402c-b379-53ca1a733c36.png)

Any help is appreciated

**Comment by victorlamana** [comment]
I fixed the issue by deleting and recreating both of the multiple-choice question nodes. But the problem still exists and I can't replicate the problem on Composer/Emulator, it only appears after I publish the bot (which is very worrying)

**Comment by victorlamana** [comment]
Update: Changing anything on these nodes bugs their visualization on Emulator and after publishing them, I need to recreate these nodes every time I make a change on this dialog

**Comment by anusharr** [comment]
@victorlamana, after recreating the multiple-choice question nodes, do you still get the issue on Composer and Test in Web Chat? Also, can you attach a screenshot of how the prompt appears after you recreate the question nodes on Emulator and Composer? Let me attempt a repro on my end and update my findings.

**Comment by victorlamana** [comment]
Hello, I'll try to recreate the bug later today :)

Q:
" after recreating the multiple-choice question nodes, do you still get the issue on Composer and Test in Web Chat?"
A: No, after I recreate them the problem is fixed (I think the bug is related to changing information within these nodes, it's what I'll try to do when recreating the bug)

Q: Also, can you attach a screenshot of how the prompt appears after you recreate the question nodes on Emulator and Composer?
A: Yes, will provide that in a couple hours when there is some free time here, thanks for the reply =D

**Comment by victorlamana** [comment]
I have not been able to reproduce the problem for some reason, I'll close the issue and I reopen it or open another one referencing this one if the error happens

Thanks a lot once again everyone
