### ISSUE TITLE
File or attachment input: After asking for image input, it is remaining in pending state, then fails

### ISSUE THREAD

**Issue by humak** [microsoft/BotFramework-Composer#8496]
Hello, 

I am using Composer v2.1.0 nightly. 
Version:  2.1.0-nightly.261240.6039ff3
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

I am trying to ask for user input to get an image from the user. Following the tutorial here: https://docs.microsoft.com/en-us/composer/how-to-ask-for-user-input?tabs=v2x#create-an-attachment-input-action
Nevertheless, it is remaining in a pending state for a long time, then fails. So, I never get the chance to reach the image sent by the user.
![image](https://user-images.githubusercontent.com/14835957/127568406-af973261-e296-4857-bb38-0c571669c3c5.png)
('Gönderiliyor' is 'Sending' state)
![image](https://user-images.githubusercontent.com/14835957/127568484-dedcebb4-bc24-414c-a468-794e6fbc78de.png)
('Gönderme başarısız. Yeniden Dene.' is 'Failed. Try Again' state)

Firstly, I want to successfully send the image. 
Then, I want to reach that image, but I couldn't find any information on documentation about how these images are being stored and how to access them.
Can you please help & direct me to handle image attachments correctly?

**Comment by stevkan** [comment]
@humak, can you tell me what client you are using for testing? It looks like it is Web Chat. Is this the built-in WC, a separate instance running outside of Composer, or something else?

**Comment by stevkan** [comment]
@humak, I have actually experienced this problem for quite some time with a standard SDK bot in Emulator. However, the issue hasn't expressed itself with colleagues when they tried, so I have left it alone. Testing in Composer reveals the same. It's important to note that Composer basically picked up the Emulator code for the Web Chat implementation. So, if there is an issue in Emulator, then it's no surprise it's in Composer Web Chat, as well. I should add that this has never hindered the flow of the conversation with the bot. For me, it's only been a matter of seeing the activity _report_ being unsuccessful. Not actually being unsuccessful.

Could you do me a favor and try one of the BotFramework-WebChat [samples](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples#web-chat-hosted-samples) and see if it works OK for you there, as it does for me? You will need to either setup a process for generating a token to then be used in Web Chat or just supply your DirectLine secret in place of the token (only do this for local testing - never for production). You can reference this [post](https://stackoverflow.com/a/60120299/3962636) on how to setup a token generating server, if of interest.

In the meantime, I'm going to use Fiddler to see if I can determine where the break is in Composer Web Chat/Emulator vs. regular Web Chat.

**Comment by stevkan** [comment]
@humak, is this still an issue for you? Were you able to try sending an attachment via a Web Chat sample successfully? Regarding Fiddler, I've had a few issues trying to run it due to a previous trace session's setup that isn't unloading correctly. I'll hopefully have that corrected today when I meet with a colleague to diagnose my own problem and, therefore, hope to have a response on that point.

**Comment by stevkan** [comment]
@tonyanziano,

Using Fiddler, I passed a photo into both Emulator and Web Chat and compared their respective requests/responses. In each of the attached images, the left side is while using Emulator and the right side is while using Web Chat.

There are some differences between the two.  However, the most notable is the response is empty when using Emulator whereas Web Chat includes headers and an id object.

![image](https://user-images.githubusercontent.com/18403946/129797694-12d5203f-978b-46e9-bfd2-d6942d240183.png)
![image](https://user-images.githubusercontent.com/18403946/129797701-f5e0ba1d-d8d9-40b5-84d1-963bbfaf015b.png)
![image](https://user-images.githubusercontent.com/18403946/129797706-c13f2f3d-f871-41e3-89f4-f17ae052e1a6.png)

Can you advise on what the next step should be or if there is someone that should move forward owning this, at this point? Happy to help, if I can.

**Comment by tonyanziano** [comment]
@stevkan I think the next step would be to figure out how the SDK handles the prompt for attachment input action. It seems like the mock Direct Line logic in the Emulator & Composer is not giving the bot what it is expecting in order to complete the prompt.

After looking at the Direct Line API docs for [uploading an attachment](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-4.0#upload-and-send-files), maybe that activity ID that is returned is used to complete the prompt, and the mock Direct Line is not returning that piece of information.

**Comment by stevkan** [comment]
PR #[2287](https://github.com/microsoft/BotFramework-Emulator/pull/2287) in the BotFramework-Emulator repo should fix the issue.

**Comment by stevkan** [comment]
@humak, the above referenced PR has been merged. The fix will be part of the next published version of Emulator.
