### ISSUE TITLE
Issue with QnAMaker Response

### ISSUE THREAD

**Issue by aparnaji** [microsoft/BotFramework-Composer#8498]
## Describe the bug

Issue with QnAMaker Response if there is processing on the question

## Browser

- [ ] Chrome

## OS

- [ ] Windows

## To Reproduce

1. As the user to enter question via  "Prompt For Text"
2. For the response sending to a HTTP request to do some processing
3. Invoked the Connect to QnA after this HTTP Call
4. The QnA is not running on HTTP Response
5. It is running on the text the user gave initially , not the HTTP Response, even though the QnA maker is given later or it gives fall back answer

## Expected behavior

QnAmaker should be able to be invoked after HTTP 

## Screenshots

![image](https://user-images.githubusercontent.com/26645750/127659995-bf41f177-81b5-489d-8aa3-af4450745f4b.png)

**Comment by anusharr** [comment]
@aparnaji, can you specify what version of the Composer you are on? Do you get any additional error on the dev console while running the bot? Also, can you attach a screenshot of the chat/response you are getting?

**Comment by benbrown** [comment]
@aparnaji can you provide us some more information about this issue? We're not clear what the actual problem is yet.

**Comment by anusharr** [comment]
Closing the issue due to no response. Please feel free to re-open if issue persists.
