### ISSUE TITLE
Complex condition not working with Branch if/else

### ISSUE THREAD

**Issue by tamasschmolcz** [microsoft/BotFramework-Composer#8499]
Hi,

I did some tests with a complex condition using Branch "if/else" :

dialog.topic != 'Hund an-/abmelden' || dialog.topic != 'Anderes Thema'

It does not resolve to False, when  the mentioned topics are choosen. However, when reducing the condition to a simple one:

dialog.topic != 'Hund an-/abmelden'

It works absolutely fine. I also tried the prebuiltin operators - same result.

## Version

v.2.1.0

## Browser

Edge

## OS

Windows 10

## Expected behavior

"False" is choosen, when Input is matching the shown topics.

## Screenshots

![image](https://user-images.githubusercontent.com/48097252/127689624-a6a8608b-59cb-4ee8-9c10-02a65144c75b.png)

**Comment by benbrown** [comment]
@boydc2014 Hey Dong can you have someone take a look at this Adaptive Expression issue? Thanks

**Comment by boydc2014** [comment]
> @boydc2014 Hey Dong can you have someone take a look at this Adaptive Expression issue? Thanks

Sure, looking at it.

**Comment by hibrenda** [comment]
yes. we can repro.

**Comment by dmvtech** [comment]
@tamasschmolcz

Are you wanting?:
`dialog.topic != 'Hund an-/abmelden' && dialog.topic != 'Anderes Thema'`

**Comment by tamasschmolcz** [comment]
Guys @hibrenda is right - looking again at it , I worked at the bot during late hours at this time and did not see the obvious :-(.  Problem solved ;-).
