### ISSUE TITLE
Webchat control in bot composer not handling image attachments URL properly

### ISSUE THREAD

**Issue by mishrapratyush** [microsoft/BotFramework-Composer#8500]
## Describe the bug

I want the bot to process images that are sent via attachment. So after asking for images to attach, I am trying to send the attachments URL to my service to process the image. 
If using webchat control in the composer the URL produced by attachments[0].contentURL looks like this: "http://localhost:5000/v3/attachments/guid/views/original" but if you click on this URL, it doesn't open up the image that was assigned.

However doing the same in emulator works where the URL looks like this: "https://62d305bd9099.ngrok.io/v3/attachments/guid/views/original"

## Version

Composer: v2.1.0-nightly.26212.19cdc4

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ X] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

1. Use Image attachment prompt and set the property to dialog.attachments
2. Attach and image
3. Respond back with the value dialog.attachments[0].ContentUrl
4. Try clicking the URL produced

## Expected behavior

URL should be of the actual image uploaded

**Comment by srinaath** [comment]
Closing this ticket as we are looking to integrate an on demand tunnel here.
https://github.com/microsoft/BotFramework-Composer/issues/7985
