### ISSUE TITLE
Cannot create new bot

### ISSUE THREAD

**Issue by afamanigbo** [microsoft/BotFramework-Composer#8505]
Any attempt to create a new bot gives an error Command failed: dotnet build

.NET and .NET core installed on the machine.

Any ideas what the problem could be?

**Comment by dmvtech** [comment]
hi @afamanigbo 

It might be an issue with nuget sources (as I have had this issue and seen [here](https://github.com/microsoft/BotFramework-Composer/issues/7876#issuecomment-881082316)).

Can you try to see if you can create a bot outside of Composer using the following steps?:

- npm install -g yo
- npm install -g @microsoft/generator-bot-empty
- yo @microsoft/bot-empty "EmptyBotTest"
- cd EmptyBotTest
- dotnet build

**Comment by afamanigbo** [comment]
Thanks, this worked for me. Turns out it was a nuget package source issue!

**Comment by dmvtech** [comment]
Great! I think I will create a bug so that if this issue happens we have a better error message available!

**Comment by dmvtech** [comment]
Actually, I'm not able to reproduce anymore. Might have been fixed in 2.1.x. What version are you running @afamanigbo ?
