### ISSUE TITLE
Weatherbot displays wrong fahrenheit temperature

### ISSUE THREAD

**Issue by toribnax** [microsoft/BotFramework-Composer#8507]
## Describe the bug
Going through the tutorial and I noticed that the weatherbot was displaying the wrong temperature by about 20 degrees as seen here:
![image](https://user-images.githubusercontent.com/47404440/127879451-cda90490-1b7e-4e63-8de4-69564b2d9e40.png)
![image](https://user-images.githubusercontent.com/47404440/127879527-1d08d26f-8e9f-495b-8e26-48ecf46f1872.png)

I went searching into why this was happening, and I found that the formula provided in the tutorial is slightly off. 
I switched the Fahrenheit formula from:
_dialog.fahrenheit =round((9/5 * (dialog.kelvin-273)) + 32,0)_

to:
_dialog.fahrenheit = =round((9 * (dialog.kelvin-273)/5) + 32)_

and now it displays the correct temperature. 
![image](https://user-images.githubusercontent.com/47404440/127880015-4f3103e5-e9ea-465e-b118-0013562ffa95.png)

## Version
2.0.0-nightly.260742.141dd34

## Browser
- [ ] Chrome

## OS
- [ ] Windows

**Comment by anusharr** [comment]
@toribnax, I followed the weather bot [tutorial](https://docs.microsoft.com/en-us/composer/tutorial-create-weather-bot) and got the following results on v2.0.0:
![weather 3](https://user-images.githubusercontent.com/48731427/128099783-78ded417-037f-486f-a428-6d83a6d4658e.png)
![weather4](https://user-images.githubusercontent.com/48731427/128099787-876e1fa6-f081-4d98-b839-18f4fa8103a1.png)
![weather 6](https://user-images.githubusercontent.com/48731427/128099790-8a4dfe86-eb51-47ff-995b-10bd480f81ac.png)
![weather 5](https://user-images.githubusercontent.com/48731427/128099792-c8d66139-f581-413f-a363-1db245901fcb.png)

Can you attach the link to the tutorial you are following?

**Comment by toribnax** [comment]
@anusharr It seems like I was using an old version of the tutorial, as the new version works me now. Thanks for clarifying!
