### ISSUE TITLE
Accessable Default value in LG template

### ISSUE THREAD

**Issue by tamasschmolcz** [microsoft/BotFramework-Composer#8510]
Hi,

it would be a nice thing, if I could access the "Default value" in "Prompt configuration" before moving on to the next node.

I would like to use a standard LG template around the "Default response", when the user has maxed out the "Max turn count", and say something like "As you have not provide the right value, I have choosen ${defaultValue} for you" .

**Comment by dmvtech** [comment]
@tamasschmolcz Thank you for submitting this. I haven't found any simple workarounds myself either. I'll continue to look at it and if I come up with nothing, we will proceed with considering for a feature.

**Comment by tamasschmolcz** [comment]
Great, thanks @dmvtech

**Comment by dmvtech** [comment]
@tamasschmolcz You can look at the [source code](https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Microsoft.Bot.Builder.Dialogs/Memory/Scopes). Otherwise, you suggest changes on the documentation itself.
