### ISSUE TITLE
Uncaught syntax error...

### ISSUE THREAD

**Issue by michael-vogt-avanade** [microsoft/BotFramework-Composer#8515]
## Describe the bug

I am following a basic exercise to learn to use Composer.   I have made no changes to the text.  After I install the Help and Cancel Packages, and create a new trigger and try and change the 'Allow Interruptions' property for the Help trigger... i get an error...
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '#root[4i5cOe].allowInterruptions-list2' is not a valid selector.

I inspected the version of the package in the exercise, it is 1.0.0... I first tried the latest package 1.1.2    so I returned to 1.0.0...   the error is still there.  
## Version

I am using Bot Framework Composer v2.1.0 
## Browser

- [ ] Electron distribution
- [X ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

Follow the exercise on...

https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-help?tabs=v2x

get to the part where you are building the dialogs for Help and Cancel... and have to introduce Allow Interruptions.....

**Comment by srinaath** [comment]
@michael-vogt-avanade At what point do you get the error? Is it aftere starting the bot or is it during design time?

**Comment by michael-vogt-avanade** [comment]
Good Morning Srinaath,

I get the error during design time, when instructions from the exercise tell me to go to the Other tab, down to the Allow Interruptions pull-down and change the value from False to True....    the error displays immediately, and every time I attempt this.

The exercise instructions illustrate that they used the ver1.0.0 package...         so I tried that too - all versions of the package cause the same error.

It confuses me because its a 'syntax' error... and I have looked carefully  through all my steps leading up to this... and they are all copy-pasting instructions directly from the exercise...    it is only the attempt to change False->True properties that triggers the error.

Can your staff successfully complete this same exercise without error?

Mike
________________________________
From: Srinaath Ravichandran ***@***.***>
Sent: Wednesday, August 4, 2021 11:55 AM
To: microsoft/BotFramework-Composer ***@***.***>
Cc: Michael Vogt ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/BotFramework-Composer] Uncaught syntax error... (#8515)


@michael-vogt-avanade<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmichael-vogt-avanade&data=04%7C01%7Cmichael.vogt%40avanade.com%7C0f6267094bfd44f4ebba08d95768a8f6%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637636929299328010%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aBH%2BrW24AjgaFsCTjRLQdg5tVaGP%2BvNiZjpH9QBMiWA%3D&reserved=0> At what point do you get the error? Is it aftere starting the bot or is it during design time?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FBotFramework-Composer%2Fissues%2F8515%23issuecomment-892817054&data=04%7C01%7Cmichael.vogt%40avanade.com%7C0f6267094bfd44f4ebba08d95768a8f6%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637636929299328010%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CMnZA0IsdoZlfrZC08ezLrf7Z5NxQGa69NVqF%2BvbQwc%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATCJBAIG6GJPTXVSBOY54ETT3FWH5ANCNFSM5BPLWIGA&data=04%7C01%7Cmichael.vogt%40avanade.com%7C0f6267094bfd44f4ebba08d95768a8f6%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637636929299337967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1%2FT4amwYNADaPEwi%2B0LpmSes2SfFMhYH4oykDKNm%2FSQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.vogt%40avanade.com%7C0f6267094bfd44f4ebba08d95768a8f6%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637636929299337967%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Metx5VymzfJHwvSfNRHgXiAzDjUwvgTKG91jLXIenvE%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmichael.vogt%40avanade.com%7C0f6267094bfd44f4ebba08d95768a8f6%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637636929299347920%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0bomLoV0A9XTH9Ju0yZUYZYJmgdcMWbTbfVfDcgW6RI%3D&reserved=0>.

**Comment by benbrown** [comment]
@srinaath this seems like something going awry inside the Composer client code. Can someone on your team check it out?

**Comment by dmvtech** [comment]
I am not able to reproduce with Composer 2.1.0 and the help&cancel package 1.0.0. But when using the help&cancel package 1.1.2, I get an issue where the bot is stuck trying to start. Same issue as listed [here](https://github.com/microsoft/BotFramework-Composer/issues/8521), I believe.

**Comment by michael-vogt-avanade** [comment]
I will return to the exercise, and repeat it again from the very start.   I will use help and cancel 1.0.0.

When you ran your test, did you also follow the 'weatherbot' exercise, or just try and test the help&cancel package some other way?

I am trying to isolate where any 'syntax' error may have come up - i wrote no new code of my own, all of the code/snippets/settings were copy-pasted/directly from the exercise text.

I appreciate your repeated help trying to work through this.

mIke
________________________________
From: Dana V ***@***.***>
Sent: Friday, August 6, 2021 3:16 PM
To: microsoft/BotFramework-Composer ***@***.***>
Cc: Michael Vogt ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/BotFramework-Composer] Uncaught syntax error... (#8515)


I am not able to reproduce with Composer 2.1.0 and the help&cancel package 1.0.0. But when using the help&cancel package 1.1.2, I get an issue where the bot is stuck trying to start. Same issue as listed here<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FBotFramework-Composer%2Fissues%2F8521&data=04%7C01%7Cmichael.vogt%40avanade.com%7C0317316a4e1a48b701ad08d9591707f1%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637638777716820686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZxqiYCSfa7JtKoTaYnxBkwvJZMnOWUBOF%2FQKwfvY%2Fl8%3D&reserved=0>, I believe.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FBotFramework-Composer%2Fissues%2F8515%23issuecomment-894496510&data=04%7C01%7Cmichael.vogt%40avanade.com%7C0317316a4e1a48b701ad08d9591707f1%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637638777716820686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V7bYmh%2BOxt4z1iDQeqGdbeQ0XhGUowiznPAx893WneU%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATCJBAJ6SFVM2JF3BKIGXZDT3Q7ITANCNFSM5BPLWIGA&data=04%7C01%7Cmichael.vogt%40avanade.com%7C0317316a4e1a48b701ad08d9591707f1%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637638777716830641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OkFmVMI%2FgxQOSUbzPrvtByyE0jcU81KvTAzqectOZSo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.vogt%40avanade.com%7C0317316a4e1a48b701ad08d9591707f1%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637638777716830641%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CjLx4itanlFE7Q2fXAB6yKvCUF6fgTEtQgD63IAJU20%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmichael.vogt%40avanade.com%7C0317316a4e1a48b701ad08d9591707f1%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637638777716840599%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=q3YYBUJc7cAi6Wcp08AJrC%2BsysR9UzAm2FH9IkBBpjU%3D&reserved=0>.

**Comment by dmvtech** [comment]
> When you ran your test, did you also follow the 'weatherbot' exercise, or just try and test the help&cancel package some other way?

I just tried adding the package in an empty bot. But I just tried again within the weatherbot example and I get the same as I did before. Unable to reproduce.

**Comment by michael-vogt-avanade** [comment]
thank you.

i will repeat the weatherbot exercise, and see if i had made some error in copy-pasting any instructions.

m
________________________________
From: Dana V ***@***.***>
Sent: Tuesday, August 10, 2021 6:05 PM
To: microsoft/BotFramework-Composer ***@***.***>
Cc: Michael Vogt ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/BotFramework-Composer] Uncaught syntax error... (#8515)


When you ran your test, did you also follow the 'weatherbot' exercise, or just try and test the help&cancel package some other way?

I just tried adding the package in an empty bot. But I just tried again within the weatherbot example and I get the same as I did before. Unable to reproduce.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FBotFramework-Composer%2Fissues%2F8515%23issuecomment-896368737&data=04%7C01%7Cmichael.vogt%40avanade.com%7C8a35dea52a974c1fc65508d95c5349a6%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637642335075979612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cNQhcWrewcKbXlZ5Yy7Vlm6DFoAPcYUnvudHePibFIs%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATCJBAO3AZAXGKRB6U4G223T4GWB5ANCNFSM5BPLWIGA&data=04%7C01%7Cmichael.vogt%40avanade.com%7C8a35dea52a974c1fc65508d95c5349a6%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637642335075979612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TFnOeAk9V4VaUnYWsPR9zlmqq0rtnh4kV%2BM55H6ZCLA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.vogt%40avanade.com%7C8a35dea52a974c1fc65508d95c5349a6%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637642335075989578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wXfNin5K9YO%2FtUNCoRxBhZbyTMDpqTDnvurzezUS5u0%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmichael.vogt%40avanade.com%7C8a35dea52a974c1fc65508d95c5349a6%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637642335075989578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BI9FLuTE8FgROrN1UeKtfJOl08BRY%2BhNZHfXPHdAoqA%3D&reserved=0>.

**Comment by cpolanish** [comment]
Also getting this issue in 2.1 on an existing bot I've been working on.

**Comment by dmvtech** [comment]
I'm able to reproduce this now.

**Comment by michael-vogt-avanade** [comment]
is there an explanation or way to correct this?
________________________________
From: Dana V ***@***.***>
Sent: Thursday, August 12, 2021 5:39 PM
To: microsoft/BotFramework-Composer ***@***.***>
Cc: Michael Vogt ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/BotFramework-Composer] Uncaught syntax error... (#8515)


I'm able to reproduce this now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FBotFramework-Composer%2Fissues%2F8515%23issuecomment-898015923&data=04%7C01%7Cmichael.vogt%40avanade.com%7C8ef0dc4a5faf438a867008d95de20d69%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637644047737233603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=24qHLOKCfI9FdPReD0NXTzrnLu4UcRq%2BE7mGxcpraPE%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATCJBAOTR727E6QZLMEGRS3T4RESHANCNFSM5BPLWIGA&data=04%7C01%7Cmichael.vogt%40avanade.com%7C8ef0dc4a5faf438a867008d95de20d69%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637644047737233603%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5nCs2bJKQB4grJq2hmbA3wGmfvfOLDjzGKcHFVJv%2BYg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.vogt%40avanade.com%7C8ef0dc4a5faf438a867008d95de20d69%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637644047737243561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qMQ5LzW%2F8iU6VN3oOVaRK41zAIzDf9ct0JBc2bb4CWU%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmichael.vogt%40avanade.com%7C8ef0dc4a5faf438a867008d95de20d69%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637644047737243561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V0yKgYXSDZkeZ%2FvxVIT7b7gtcmp3%2FDQUqnOQS0LcbGo%3D&reserved=0>.

**Comment by michael-vogt-avanade** [comment]
Help me understand the recent email chain.     I had heard from DanaV that you were able to reproduce my error...  then a few days later, I received email that the case/ticket was closed.

I did not receive any explanation nor solution to my problem.    Did something get sent that I am not recognizing?

Thanks

Mike
________________________________
From: Srinaath Ravichandran ***@***.***>
Sent: Monday, August 16, 2021 3:03 PM
To: microsoft/BotFramework-Composer ***@***.***>
Cc: Michael Vogt ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/BotFramework-Composer] Uncaught syntax error... (#8515)


Closed #8515<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FBotFramework-Composer%2Fissues%2F8515&data=04%7C01%7Cmichael.vogt%40avanade.com%7C9c345f31efe847fdd7c108d960f0f72d%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637647410324245409%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3NeLT6dSGJTW1Gd6kyl1ClnqShhJbRkWmGd0WtkykkM%3D&reserved=0> via #8560<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FBotFramework-Composer%2Fpull%2F8560&data=04%7C01%7Cmichael.vogt%40avanade.com%7C9c345f31efe847fdd7c108d960f0f72d%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637647410324245409%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vuXTS8ITnJDqj2GuC5jijuDo9M5o5x1zq7ZhrdfnDn4%3D&reserved=0>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FBotFramework-Composer%2Fissues%2F8515%23event-5165157276&data=04%7C01%7Cmichael.vogt%40avanade.com%7C9c345f31efe847fdd7c108d960f0f72d%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637647410324255365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=newYHwggiUv7J6ukdV7tprTTgeVQU%2BslKyOLieOw0Q0%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATCJBAPL6VZ5WK6THNH26FTT5FVKNANCNFSM5BPLWIGA&data=04%7C01%7Cmichael.vogt%40avanade.com%7C9c345f31efe847fdd7c108d960f0f72d%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637647410324265318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=twynJEjqzdIe1%2BxK9MCvaJZFZROja84zCh7l1TRDmmc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmichael.vogt%40avanade.com%7C9c345f31efe847fdd7c108d960f0f72d%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637647410324265318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LG3%2B9pcx97tvDXcvgRRPFXfeawavj%2FqDI2ldfZ16r2g%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmichael.vogt%40avanade.com%7C9c345f31efe847fdd7c108d960f0f72d%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637647410324275272%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=luWYOpzqalzg7Ndmfmws%2Fr%2F8MflA3HBEGyi3yn8wwH0%3D&reserved=0>.

**Comment by srinaath** [comment]
@michael-vogt-avanade 
https://github.com/microsoft/BotFramework-Composer/pull/8560 fixed this ticket. This fix would be available if you use our early adopters feed or in a patch release which we would make soon.

![Screen Shot 2021-08-16 at 4 58 45 PM](https://user-images.githubusercontent.com/13004779/129643430-4f131124-a9e8-4666-b7db-838df53a6de4.png)
