### ISSUE TITLE
Keep showing Starting bot...

### ISSUE THREAD

**Issue by nguyenhuy200900** [microsoft/BotFramework-Composer#8521]
## Describe the bug

BF Composer can not start the bot and keep showing Starting bot... Even when I restart the computer, the problem still exist.
![image](https://user-images.githubusercontent.com/77385199/128171955-35c375ab-875d-4e4d-8bd8-0d99ee5e7e7a.png)

## Version

Version:  2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- Microsoft Edge
- Chrome

## OS

- [x] Windows

**Comment by srinaath** [comment]
@nguyenhuy200900 Could you open the bot folder and run the sln file in Visual Studio? Essentially we want to see if the bot is able to run outside the context of Composer.

**Comment by nguyenhuy200900** [comment]
Yes, it is possible @srinaath thank you very much.

![image](https://user-images.githubusercontent.com/77385199/128480046-fc4db093-c1e0-40c1-a850-e2819766a135.png)

**Comment by gabog** [comment]
Hi @nguyenhuy200900, are you still having issues with composer?
