### ISSUE TITLE
Bot composer Environment variables.

### ISSUE THREAD

**Issue by pannerselvam-yaltech** [microsoft/BotFramework-Composer#8522]
In previous code version of bot framework we were using environment variable in Azure app service. Now i am using Bot composer and i couldn't maintain any user credentials and url links. what should do for it?

**Comment by dmvtech** [comment]
Hi @pannerselvam-yaltech 

You can access items listed from configuration/settings by using the `settings` memory scope. See [here](https://docs.microsoft.com/en-us/composer/ref-memory-variables?tabs=v2x#the-scopes) for more information.

So, in Composer you can specify something like `"MyCustomSetting": "some_value"` in the settings and then access that in Composer bot with something like `${settings.MyCustomSetting}`.

**Comment by dmvtech** [comment]
Closing as answered.

**Comment by pannerselvam-yaltech** [comment]
Thanks for help. It's working.
