### ISSUE TITLE
Multilingual bot works in web chat but not emulator

### ISSUE THREAD

**Issue by dinobrago** [microsoft/BotFramework-Composer#8524]
## Describe the bug

I created a multilingual bot in English and Spanish in Composer

## Version
Version:  2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

Emulator: v:4.13.0

## Browser 

- [ ] Electron distribution
- [X ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

Create a multilingual bot as described in https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language.
I created a bot in English and Spanish. 
Select the added language as the default. 
Start the bot. 
In the web-chat (launched from Composer), the bot matches the language selected in Composer.

In the emulator (launched from Composer), the bot is always in English and does not switch between languages.  
Restarting the bot after setting the language does not change the outcome. 

## Expected behavior

A default language is selected in Composer.  The emulator should match the selected language set in Composer.

**Comment by dmvtech** [comment]
To test the bot in Spanish with Emulator, you will need to change the Local in the Emulator's settings. Composer does not set the locale for the bot when it is opened in (sent to) Emulator.

If you need to test both locales in Emulator, you can open the bot with one locale, then open another instance of Emulator, change the locale, then open the bot. 

FYI, there is a [feature request](https://github.com/microsoft/BotFramework-Emulator/issues/2268) created to have the option to set locale, per open bot, in Emulator.
