### ISSUE TITLE
any() expression not available in 2.1?

### ISSUE THREAD

**Issue by Clooney24** [microsoft/BotFramework-Composer#8536]
I used the any() expression in 1.4 without problems. In Composer 2.1 it is marked as a warning with a hint that's not a built-in function?

![image](https://user-images.githubusercontent.com/14079908/128683793-1067be9e-e165-40c9-9c6e-cc4a5e8c4f11.png)

Version:  2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by gabog** [comment]
Hi @cwhitten / @srinaath, can you guys take a look at this one please?

Thanks

**Comment by compulim** [comment]
@cwhitten looks likes a solid bug. I will exempt it from daily DRI.

**Comment by ceciliaavila** [comment]
Closing as the fix was introduced in #9486
