### ISSUE TITLE
Enable interruptions error

### ISSUE THREAD

**Issue by fitprotracker** [microsoft/BotFramework-Composer#8545]
## Describe the bug

Going through the Display weather tutorial and at the Enable interruptions (https://docs.microsoft.com/en-us/composer/tutorial-create-weather-bot#enable-interruptions) I get an error when try to change he value to true.

video walkthrough:  https://share.fitprotracker.com/2Nul2w4k

## Version

Bot Framework Composer v2.1.0

**Comment by cwhitten** [comment]
hello @fitprotracker - we're able to reproduce this and are looking at a fix soon. This will be addressed in an upcoming release.

**Comment by dmvtech** [comment]
Linking other ticket/same issue: https://github.com/microsoft/BotFramework-Composer/issues/8515

**Comment by lei9444** [comment]
Hi, @cwhitten I can reproduce this.
composer will throw this error only when the action designer id is start with a digit. 
![image](https://user-images.githubusercontent.com/39758135/129356804-ff1b7700-7b94-4cfd-8f84-374c374c954f.png)

I think querySelector doesn't support ID selectors that start with a digit.
I am working on fixing this issue.

**Comment by fitprotracker** [comment]
Is there a work around that I can do/change to get through the tutorial?

I am excited to learn tech.

Can I try a new project to generate a different id?

Thanks

**Comment by lei9444** [comment]
Hi @fitprotracker you can delete the Text action first and add a new one, If the action designer id is not start with digit, I think it works well.
