### ISSUE TITLE
Does orchestrator use Luis patterns? 

### ISSUE THREAD

**Issue by spallinti1** [microsoft/BotFramework-Composer#8549]
We are in the process of replacing dispatcher with Orchestrator. We are seeing some odd behavior with orchestrator.
 
Does orchestrator use Luis patterns? 
 
We have a pattern Search {Query} in search skill and it doesn’t recognize this as pattern, Instead it looks at it as an Intent.
  
We added luis apps to orchestrator using below command
 
bf orchestrator:add -t luis --id <luis-app-id> --endpoint <luis-endpoint> -k <luis-subscription-key> -v <luis-app-version> --routingName l_<luis-app-
name>
 
We generated the model and created the orchestrator.
 
Is there anything else we need to do for orchestrator to recognize luis patterns.

**Comment by daveta** [comment]
FYI: We're preparing some documentation update here:
https://github.com/microsoft/botframework-sdk/pull/6360

**Comment by cwhitten** [comment]
Closing, please follow https://github.com/microsoft/botframework-sdk/pull/6360
