### ISSUE TITLE
Bot Composer won't start

### ISSUE THREAD

**Issue by lshade** [microsoft/BotFramework-Composer#8550]
## Describe the bug

I've been using v2.1 with no issue, until my computer crashed with a blue screen yesterday. Now, the application won't start. I tried uninstalling and reinstalling. I tried installing vcredist and rebooting as mentioned in https://github.com/microsoft/BotFramework-Composer/issues/7964

## Version

2.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Run v2.1 Bot Composer application

## Expected behavior

Composer should start

## Screenshots

![image](https://user-images.githubusercontent.com/16640521/129234584-bcd7f122-28ea-4e85-aaf9-d9f5153f0b52.png)
![image](https://user-images.githubusercontent.com/16640521/129235268-62686607-5854-4f6f-aba0-34f64ef983d3.png)

## Additional context

The error in the logs I got after running `start set DEBUG=composer*`:

```
(node:536) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (node:536) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (node:536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cwhitten** [comment]
Hi @lshade, can you give us all of the logs that show up when you start Composer with the DEBUG flag?

**Comment by tonyanziano** [comment]
You might also want to try clearing Composer's cached Electron folder which should be located here:

`%appdata%/@bfc/electron-server`

For me this is:

`C:\Users\tonya\AppData\Roaming\@bfc\electron-server`

![image](https://user-images.githubusercontent.com/3452012/129237801-abd0b722-dc80-4e21-ba1b-6bfece216fa8.png)

You can just delete the entire folder and Composer will repopulate it on start.

**Comment by tonyanziano** [comment]
@lshade can you do me a favor and go to `<%appdata%>/BotFrameworkComposer` and upload the `data.json`, `extensions.json` and `extensions-settings.json` files you see there?

![image](https://user-images.githubusercontent.com/3452012/129242408-b42776b2-2f68-43ad-beec-a5c5fd374955.png)

**Comment by lshade** [comment]
Yes here they are [AppData_Roaming_BotComposer_json.zip](https://github.com/microsoft/BotFramework-Composer/files/6977434/AppData_Roaming_BotComposer_json.zip)

**Comment by lshade** [comment]
Ok I renamed them and Composer didn't start still

Here are those json files now:
[AppData_Roaming_BotComposer_json_and_backup.zip](https://github.com/microsoft/BotFramework-Composer/files/6977531/AppData_Roaming_BotComposer_json_and_backup.zip)

Here are the logs:
[lshade bot composer debug logs after backup change.txt](https://github.com/microsoft/BotFramework-Composer/files/6977533/lshade.bot.composer.debug.logs.after.backup.change.txt)

**Comment by tonyanziano** [comment]
Ok all of them look good except for `extensions.json` -- that one looks like it has a weird encoding and VS Code can't even read it. Try renaming that one to `_backup`, the other 2 should be fine.

**Comment by lshade** [comment]
That fixed it! Just renamed `extensions.json` to `extensions_backup.json` and started Composer. Thank you!

**Comment by tonyanziano** [comment]
Awesome! Glad to hear it. Going to close this issue now.
