### ISSUE TITLE
Custom package not working

### ISSUE THREAD

**Issue by jcmorara** [microsoft/BotFramework-Composer#8559]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Composer'
2. Click on 'Package Manager'
3. Select local nuget feed
3. Try to install a custom nuget package

## Expected behavior

Custom nuget package to be added to the chatbot

## Additional context

The nuget package contains the sample MultiplyDialog custom action with the corresponding .schema and component files.

![Composer Issue](https://user-images.githubusercontent.com/88945358/129457391-13bfce96-3d1e-4d2d-90fb-b39f3aed1c4f.PNG)

**Comment by anusharr** [comment]
@jcmorara, what version of the Composer are you on? Also, does this happen with other custom nuget packages or just this specific package? Do you get any additional error on the dev console(Ctrl+Shift+I)?

**Comment by jcmorara** [comment]
I'm using Composer v2.1.0. This happened first with a package with some custom actions. Then I created the [MultiplyDialog custom action](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions) and created a [package](https://docs.microsoft.com/en-us/composer/how-to-create-packages) following Microsoft documentation, but I got the same error. No issues with built-in NuGet packages.
Find attached dev console error.
![dev console](https://user-images.githubusercontent.com/88945358/129753843-aa02e799-3660-4324-8e89-c2d6828d61ae.PNG)

**Comment by anusharr** [comment]
@jcmorara, I followed the documentation linked above and was able to successfully install the package. I created the **MultiplyDialog** custom action and then created and published the **DialogAndTriggerPackage** in the local feed.  Investigating further. Also, did you get any error or warning when you created or published your package in the command prompt?

**Comment by jcmorara** [comment]
It's working fine now. The issue was caused by an existing project reference to the CustomAction project, which generated conflict.
After removing the reference I was able to install the NuGet package.
