### ISSUE TITLE
Composer fails to start a bot, when the bot project's folder was renamed

### ISSUE THREAD

**Issue by dgancho** [microsoft/BotFramework-Composer#8564]
## Describe the bug
When a folder containing the bot project was renamed, the Composer fails to start that bot anymore, just hangs at "Starting bot...: forever.

## Version
Release 2.1.0
Version 4.12.0
/there is no build SHA on the Composer about page/

## Browser
- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS
- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce
1. Start Composer, select Create new, select C# "Empty Bot" template
2. Name the bot "Empty" (default for the template), select Azure Web App runtime (default for the template)
3. Select a location to save, I selected `C:\Users\UserName\source\Temp\`
4. Click Create. When the bot is ready, hit Start bot and verify default greeting in the webchat:
![Screenshot1](https://user-images.githubusercontent.com/9956329/129657954-568bcb9f-2b02-4af7-84bb-a8d5e7c363d2.PNG)
5. Stop the bot and exit the Composer. Kill `Empty.exe` bot process (as it's not exiting as it should)
6. Rename the folder containing bot project, in my case:
`C:\Users\UserName\source\Temp\Empty\Empty` => `C:\Users\UserName\source\Temp\Empty\Renamed`
7. Start Composer, navigate to the Renamed folder and open the bot:
![Screenshot2](https://user-images.githubusercontent.com/9956329/129658667-07d04d1c-8a51-4339-8ebd-cfae8e0cbe4f.PNG)
8. Load the bot and click "Start bot". It never starts and no error is displayed:
![image](https://user-images.githubusercontent.com/9956329/129658866-5c454d3f-b466-428b-af56-448d705bd510.png)

## Expected behavior
The Composer should be able to start a bot project irrespective of the name of the parent folder

## Additional context
none

**Comment by srinaath** [comment]
@dgancho Thanks for the report. We are able to repro this bug as well.

**Comment by pavolum** [comment]
UPDATE: in local env able to repro sporadically. When I am able to repro I am seeing the following error in the dev console;
```[start:server:dev] GET /api/publish/81911.68349515765/status/default/fc96aea7-1fff-40a6-a5f3-f49c665545a8 202 103.422 ms - 39
[start:server:dev] (node:46896) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stdout' of undefined
[start:server:dev]     at LocalPublisher2.removeListener (C:\Users\pavolum\source\repos\BotFramework-Composer\extensions\localPublish\dist\extension.js:29683:13)
[start:server:dev]     at C:\Users\pavolum\source\repos\BotFramework-Composer\extensions\localPublish\dist\extension.js:29730:20
[start:server:dev]     at runMicrotasks (<anonymous>)
[start:server:dev]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[start:server:dev] (Use `node --trace-warnings ...` to show where the warning was created)
[start:server:dev] (node:46896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[start:server:dev] (node:46896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by pavolum** [comment]
Triage findings:
- There was a missing null check that led to Composer hanging and giving no meaningful error message. The PR associsated with this issue adds the null check, this will likely resolve ieesues #8547 and #8573
- When that null check is added you get meaningful error messages
- When the bot project is opened, the botProject.name variable is set to the name of the containing dir (which was renamed manually). 
- That botProject.name is then used in composer as the variable for the csproj file. However the csproj file name was never changed, just the containing dir so this leads to a 'file not found error' 

Potential solutions
1. Tell users not to mess with dir names and make not code change to account for this manual intervention
2, Set BotProject.name to the name of the .csproj file in the dir when the bot is opened, not the name of the containing dir
3. When Composer detects the dir name is changed then change the .csproj file name to match the now changed dir name AND alter the content within the .sln file to reference the newly named .csproj

**Comment by pavolum** [comment]
@dgancho below is a workaround to enable you to rename the bot project folder without breaking the solution:
1. Rename the .csproj file in the root of your bot proj to same name you renamed your bot dir.
![image](https://user-images.githubusercontent.com/22845013/130285940-8a931559-bbec-4735-b304-8dcb0ab2ce1f.png)
2. Update the run command value to use your new .csproj name in appsettings file for your bot in settings/appsettings.json
![image](https://user-images.githubusercontent.com/22845013/130286118-10a4c748-408c-461f-bfce-a4ca6c6b07bf.png)
3. Edit the solution file in a text editor and update the path the the .csproj file
![image](https://user-images.githubusercontent.com/22845013/130286228-22872c05-f3b4-49c6-8e29-45998ba3dfe2.png)
![image](https://user-images.githubusercontent.com/22845013/130286278-2e69aa13-2d90-4967-a49a-66f8560e4579.png)

**Comment by pavolum** [comment]
I have added an issue to track the addition of the workaround to our docs page 
https://github.com/microsoft/BotFramework-Composer/issues/8588
