### ISSUE TITLE
Install Error while trying to install a package from Bot composer - Package manager

### ISSUE THREAD

**Issue by nasshaik** [microsoft/BotFramework-Composer#8567]
If this problem persists, please file an issue on GitHub
Details
A problem occured during the install of this Component: Error Cannot create property '$bundled' on string '<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src="http://182.79.218.34:8080/webadmin/deny/index.php?dpid=15&dpruleid=11&cat=107&dplanguage=-&url=http%3a%2f%2f185%2e199%2e108%2e153%2fdraft%2d07%2fschema" width="100%" height="100%" frameborder=0></iframe>' *** Could not merge components ***

**Release: 2.1.0-nightly.263527.c15ee70**

**Comment by srinaath** [comment]
@nasshaik Thanks for the report. This is a known issue. We are tracking this in another ticket. #8533.
