### ISSUE TITLE
Can't merge the schema files

### ISSUE THREAD

**Issue by MahmoudHamdy00** [microsoft/BotFramework-Composer#8569]
## Describe the bug
when merging the schema it gets this error `Error connect ETIMEDOUT` 

## Version
Bot Framework Composer 2.1.0

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to `<bot folder>\schemas`
2. run the update schemas script
then it gets this error

## Screenshots
![image](https://user-images.githubusercontent.com/42287052/129788635-aac169ae-f7fd-4eb0-9c2f-53bb442c9e34.png)

**Comment by srinaath** [comment]
@MahmoudHamdy00 Are you running Composer behind a proxy?
The bf dialog merge tool tries to fetch some schema definitions and it looks like the network seems to be blocking it. Could you zip your bot assets as well if possible for us to try on our end. Im assuming you built a custom action and trying to merge it using the update schema script?

**Comment by LeeParrishMSFT** [comment]
Closed due to lack of response.
