### ISSUE TITLE
Cancel all dialogs not processing any activity after cancel all dialogs activity

### ISSUE THREAD

**Issue by praveenvavilla** [microsoft/BotFramework-Composer#8583]
Hi,

I created test bot to see if cancel all dialogs is working or not (after I see issue with it in our bot) and looks like it is not processing any activity after cancel all dialogs activity.

 
![image](https://user-images.githubusercontent.com/55256942/130127086-0e9d1061-475a-4e75-8a32-276bec71a448.png)

I do not see cancelled all dialogs message after cancel dialogs activity

transcript:

[cancelalldialogs.zip](https://github.com/microsoft/BotFramework-Composer/files/7017108/cancelalldialogs.zip)

Please let me know if I am missing anything here?

Thanks
Praveen V

**Comment by joshgummersall** [comment]
Canceling all active dialogs includes the current dialog, so processing halts immediately. This is the expected behavior.

**Comment by praveenvavilla** [comment]
hi @joshgummersall 

if I want to have signout in the middle of any dialog flow (I will have many dialogs) , do you recommend to do the below in sign out   trigger

- sign out
- cancel all dialogs

**Comment by joshgummersall** [comment]
That sounds right to me, yes.

**Comment by praveenvavilla** [comment]
got it thank you for confirming
