### ISSUE TITLE
Not able to enable allow interruption to true in composer for a choice prompt

### ISSUE THREAD

**Issue by tushaar9027** [microsoft/BotFramework-Composer#8595]
![image](https://user-images.githubusercontent.com/10369409/130588029-b324e78d-6d32-4ec5-85e5-a00b13a5e846.png)
Attaching th screenshot of the issue

**Comment by srinaath** [comment]
Closing this ticket as the bug has been resolved in the latest nightly.
https://github.com/microsoft/BotFramework-Composer/pull/8560
