### ISSUE TITLE
SyntaxError when allowing interruptions

### ISSUE THREAD

**Issue by MrVictorX** [microsoft/BotFramework-Composer#8596]
## Describe the bug

Hello, I've been testing and learning to use the bot framework and I've been using consistently the framework without changing any source code by hand, as I was implementing a cancel dialog to interrupt any current dialog flow and I wasn't being able to cancel it when the user types cancel, then I found a section when prompting text to allow interruptions
![image](https://user-images.githubusercontent.com/41481449/130597398-0caeb2de-c046-4fdc-9698-9db6d03dde48.png)

It has a default of false and I wanted to change it to true, when opening the dropdown list this error shows up
![image](https://user-images.githubusercontent.com/41481449/130597532-08ad7236-6f6a-4449-b7e2-3559a0dab7e8.png)

Any idea of what the cause is? I couldn't find anything

## Version

Bot Framework Composer v2.1.0

**Comment by srinaath** [comment]
@MrVictorX This is a known bug. We have already resolved it in this PR https://github.com/microsoft/BotFramework-Composer/pull/8560. If you can wait for our next patch release in a few weeks you can grab the change or you can immediately get the fix by using the Composer nightlies (Early adopter
![Screen Shot 2021-08-24 at 9 36 09 AM](https://user-images.githubusercontent.com/13004779/130655424-8a09982e-3dba-4074-b426-b19c76a93a33.png)
).
