### ISSUE TITLE
QnA Knowledge base page in Composer has 2 'view code' options - inconsistent experience that cannot be solved by documentation

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#8599]
In composer, nightly build from Aug 22

Start a new bot with

1.  Language
2. Set up LUIS and QnA
3. Create a new KB from scratch using the wizard (aka: point to a website)
4. KB is set up.
5. Go to the far right side of the page, and click 'view code' 
 

> EXPECTED: just like all other View Code buttons (Bot responses, User input, Property Editor and Settings), JSON view (monaco editor) of the KB. However, what shows is just the path of the KB I connected to (In my case wish.org)

6. Go to the left side of the body of the page, right under the 'Question' header. Notice a pen as well as a '...' icon.
7. Also notice that the title of the KB in the listview is BLUE, not black, per FLUENT
8.. Click the '...' icon: nothing happens
EXPECTED : just like everywhere else in Windows, a '...'button opens up a 'more options' menu. However, here it is disabled and instead the Pen icon brings up this menu.

9. Click the 'pen' icon to get to the 'more options' menu
10. Notice the 'view code' option in the menu
11. View code option switches the entire body of the page to the JSON view of the KB. 
EXPECTED: this action is expected to happen from the 'view code' option on the upper right side. 
EXPECTED: if there are two options with the exact same label, the same thing should happen.

WHY DOES THIS NEED TO BE FIXED?
- Doc writers cannot document 2 buttons with the same name and label with different behavior on the same page
- There is a strong precedence set in Composer with the 'view source' button in the upper right: to show the JSON. There is no reason why the KB page should do something different.
- The behavior is already working - it's mapped to the wrong button.
- 

PROPOSED FIXES - see images:
1. on 'View code' from the upper right, show the JSON view of the full KB
2. change the KB titles in the list to BLACK (vs blue) - per FLuent spec
3. remove the pen icon
4. make the '...' icon active
5. on click of the '...' show the menu
6. in the menu, replace 'view code' with 'view source'
7. on clicking 'view source', show the PATH of the knowledge base source. (note : same behavior as currently happens on 'view code' in the upper right corner of the body of the page.

![Screen Shot 2021-08-23 at 4 42 34 PM](https://user-images.githubusercontent.com/48503434/130654297-e129e299-8976-406a-bca0-f793c99b3124.png)
![Screen Shot 2021-08-23 at 4 42 23 PM](https://user-images.githubusercontent.com/48503434/130654304-8ffef9e1-8807-4915-8cf1-f6110da4c954.png)
![Screen Shot 2021-08-23 at 4 42 14 PM](https://user-images.githubusercontent.com/48503434/130654306-a6268c21-519c-4d10-a2c0-424e7807f29b.png)

**Comment by JonathanFingold** [comment]
@vivekkshankar Let me know when changes have made it into the nightly build.
