### ISSUE TITLE
Is there a way to change bot language dynamically? turn.activity.locale changes the next upcoming response only.

### ISSUE THREAD

**Issue by shivamguptaram** [microsoft/BotFramework-Composer#8606]
locale ,user.locale and conversation.locale also didn't work.

**Comment by shivamguptaram** [comment]
I am using emulator right now, I am changing the turn.activity.locale by using 'set property' in composer 

![image](https://user-images.githubusercontent.com/27141073/131461373-722560ec-76a7-4136-94ae-194be4cf5240.png)

**Comment by stevkan** [comment]
@shivamguptaram, thank you for your patience. It's important to remember that properties that are part of the `turn` scope are transient and only live for the duration of the turn. If you want to set a property that will live for the duration of the dialog, conversation, or per user, then you should use one of those buckets. You can read more about memory scopes [here](https://docs.microsoft.com/en-us/composer/concept-memory?tabs=v2x#properties-and-memory-scopes).

If you are trying to set the property based on the locale of the user, that property lives in `turn.activity.locale` which is typically set by the user's client. For instance, if I set Emulator's locale to `de-DE`, this is what I see, when I input some text:

**Emulator:**
```js
{
  "channelData": {
    "clientActivityID": "1631199154675txu47qhvdwg",
    "clientTimestamp": "2021-09-09T14:52:34.675Z"
  },
  "text": "Hello",
  "textFormat": "plain",
  "type": "message",
  "channelId": "webchat",
  "from": {
    "id": "c35f0132-bf29-4b75-92e8-7c1ddd60904f",
    "name": "User",
    "role": "user"
  },
  "locale": "de-DE",
  "localTimestamp": "2021-09-09T07:52:34.675-07:00",
  "localTimezone": "America/Los_Angeles",
  "timestamp": "2021-09-09T14:52:34.675Z",
  "entities": [
    {
      "requiresBotState": true,
      "supportsListening": true,
      "supportsTts": true,
      "type": "ClientCapabilities"
    }
  ]
}
```

Please try changing the "bucket" away from `turn` to one of those I listed above and try again.

**Comment by stevkan** [comment]
Closing as resolved. If the issue persists, please feel free to reopen.
