### ISSUE TITLE
SyntaxError - Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by metkhoo** [microsoft/BotFramework-Composer#8608]
## Describe the bug
This error is generated when attemptingh to publish a sample "EnterprisePeople" BOT to Azure.
The Bot works locally (albeit very slowly) in Bot Framework Emulator 4.1.4.0 
Error Message displayed is:

SyntaxError - Unexpected token u in JSON at position 0

Seems to imply mal formed JSON but I can't see the problem...

All resources exist.  
Grabbing at straws here but could it be that the "region" I selected is "uksouth" whereas LUIS and QNA are in "westus"?

## Version
Composer details
Version: 2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0 
V8: 8.0.426.27-electron.0

The NodeJS value is strange since a Windows "CMD" console C>node -v dispolays C>v14.15.0

## Browser
Chrome: 92.0.4515.159 (Officak Build) (64-bit)
Edge: 92.0.902.78 (Official build) (64-bit)

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ x] Firefox
- [ x] Edge

## OS

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Publish'
2. Click on my Bot name
3. Select the publishing profile
4. Click "Publish selected bots" button at top
5. See error in the "Message" column

## Expected behavior
Expect to see the BOT published

## Additional context

This is a test bot only
The JSON in the publishing profile is does not appear to be incorrect but I understand from "https://www.codegrepper.com/code-examples/javascript/unexpected+token+u+in+json+at+position+0" that this message is thrown up attempting to parse the JSON.

I can't see an issue.  I have remove the keys but here is the JSON:

{
  "name": "EnterprisePeople6a",
  "environment": "composer",
  "tenantId": "{redacted}",
  "hostname": "EnterprisePeople6",
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "EnterpriseBOTS",
  "botName": "EnterprisePeople6",
  "subscriptionId": "{redacted}",
  "region": "uksouth",
  "appServiceOperatingSystem": "windows",
  "scmHostDomain": "",
  "luisResource": "EnterprisePeople6-luis",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "{redacted}",
      "connectionString": "InstrumentationKey={redacted};IngestionEndpoint=https://uksouth-0.in.applicationinsights.azure.com/"
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "https://enterprisepeople6.documents.azure.com:443/",
      "authKey": "{redacted}",
      "databaseId": "botstate-db",
      "containerId": "botstate-container",
      "collectionId": "botstate-collection"
    },
    "blobStorage": {
      "connectionString": "{redacted}",
      "container": "transcripts",
      "name": "enterprisepeople6"
    },
    "luis": {
      "authoringKey": "{redacted}",
      "authoringEndpoint": "https://westus.api.cognitive.microsoft.com/",
      "endpointKey": "{redacted}",
      "endpoint": "https://westus.api.cognitive.microsoft.com/",
      "region": "westus"
    },
    "qna": {
      "subscriptionKey": "{redacted}",
      "endpoint": "https://westus.api.cognitive.microsoft.com/"
    },
    "MicrosoftAppId": "{redacted}",
    "MicrosoftAppPassword": "{redacted}"
  }
}

**Comment by anusharr** [comment]
@metkhoo, I just tried creating a new EnterprisePeople bot and was able to successfully publish the bot without any errors. As per what you mentioned above, what value did you select for the Language Understanding region in the **Configure** part? The JSON shows as "westus".
