### ISSUE TITLE
composer bot support for whatsapp

### ISSUE THREAD

**Issue by madbeher** [microsoft/BotFramework-Composer#8612]
Hi,

Does composer bot supports whatsapp channel. If yes could you please provide the documentation link
related to whatsapp based on that I will proceed for crating a bot for my project.

Thanks,
Madan

**Comment by csmuthukuda** [comment]
@tracyboehrer sorry for jumping in but we are facing the exact same problem with our js based bot created with composer..can you please guide me through some resources or tutorials that I can follow about how to connect a community built adapter(ex: Twilio Whatsapp) with our bot.

**Comment by srinaath** [comment]
@garypretty Is there any documentation related to this?

**Comment by tracyboehrer** [comment]
@clearab What is the status of documentation around custom adapters in Adaptive Runtime?

**Comment by srinaath** [comment]
@garypretty Any info around custom adapters for Whatsapp?

**Comment by compulim** [comment]
@garypretty Ping.

**Comment by luzeunice** [comment]
Hi !  I want to integrate to whatsapp using twilio. But Im lost . Any help ?
