### ISSUE TITLE
Publish not working when using existing resources

### ISSUE THREAD

**Issue by DeependraKhangarot** [microsoft/BotFramework-Composer#8613]
## Describe the bug

When I am using existing resources and publishing the bot it's failing with the below message:

"DEPLOY_ZIP_ERROR - There was a problem publishing bot assets (zip deploy)."

## Version

v2.1.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- Windows

## To Reproduce

1. Go to 'Publish'
2. Click on 'Publishing Profile'
3. Click on 'Add new', provide Name, and select "Publish to Azure" as publishing target.
4. Click 'Next'
5. Select 'Import existing resources' 
6. Click 'Next'
7. Add existing resources
8. Click 'Import'
9. Go to 'Publish'
10. Select Bot 
11. Click' 'Publish selected bots'

## Expected behavior

The bot should publish on Azure

## Screenshots

<img width="587" alt="PublishingError" src="https://user-images.githubusercontent.com/16593272/131120459-29d3f0e0-73d6-492f-aae1-a72ae98f0dfd.png">

## Additional context

Below is the log for the same:

"Accepted for publishing..."
"Abs settings incomplete, skip linking bot with webapp ..."
"appPasswordHint incomplete, return ..."
"Building the bot app..."
"Build succeeded!"
"start publish luis"
"Assigning to luis app id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
"Luis Publish Success! ..."
"Creating build artifact..."
"Build artifact ready!"
"Publishing to Azure ..."
"Uploading zip file... to XXXXXXX"

"{\"name\":\"DEPLOY_ZIP_ERROR\",\"message\":\"There was a problem publishing bot assets (zip deploy). {\\\"stack\\\":\\\"Error: getaddrinfo ENOTFOUND XXXXXXX.\\\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)\\\",\\\"message\\\":\\\"getaddrinfo ENOTFOUND xxxxxxx.\\\",\\\"code\\\":\\\"ENOTFOUND\\\",\\\"config\\\":{}}\",\"stack\":\"Error\\n    at new CustomizeError (c:\\\\users\\\\XXXXXXX\\\\appdata\\\\local\\\\programs\\\\bot framework composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269071:25)\\n    at createCustomizeError (c:\\\\users\\\\xxxxxxx\\\\appdata\\\\local\\\\programs\\\\bot framework composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269076:10)\\n    at BotProjectDeploy.deployZip (c:\\\\users\\\\xxxxxxx\\\\appdata\\\\local\\\\programs\\\\bot framework composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:269587:13)\"}"

"DEPLOY_ZIP_ERROR - There was a problem publishing bot assets (zip deploy). {\"stack\":\"Error: getaddrinfo ENOTFOUND XXXXXXX.\\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)\",\"message\":\"getaddrinfo ENOTFOUND XXXXXXX.\",\"code\":\"ENOTFOUND\",\"config\":{}}"

**Comment by srinaath** [comment]
@DeependraKhangarot  This is a know bug. We have resolved the bug in this PR https://github.com/microsoft/BotFramework-Composer/pull/8532. You should not be seeing this error in the latest nightly of Composer (Early adopters setting).

**Comment by DeependraKhangarot** [comment]
@srinaath Could you please share where we can look for known issue as we are proposing Bot Composer to our clients and looking at known issues will help us in deciding in which scenario this will work and where not.

**Comment by srinaath** [comment]
@DeependraKhangarot We did a minor release of Composer 2.1.1. Could you try checking if you still see the issue?

**Comment by DeependraKhangarot** [comment]
and the same case with 2.1.1 also.

**Comment by FANMixco** [comment]
> and the same case with 2.1.1 also.

Indeed, this is still hapenning.
