### ISSUE TITLE
missing locale support for option texts and mess up in rtl languages

### ISSUE THREAD

**Issue by Clooney24** [microsoft/BotFramework-Composer#8614]
Hi, I use bot composer 2.1 with several languages.
In some of the languages, the yes/no options generated from bot are in the selected language. In others languages, they always are in English.

For example Spanish, German, French is fine but in Italian, Russian, Hebrew, Arabic, always "(1) Yes / (2) No" is generated.

Would be nice if we at least would get an option to store those options in target languages somewhere in common.lg or somewhere else.

And in rtl languages like Arabic or Hebrew, the output looks messed up like "Yes / (2) No (1)" while 1 is yes and 2 is no - but if I copy that in an translater it is translated correctly. I'm not sure about as I'm not an rtl-expert, but can't imagine how this can be correct. (yellow marks in screenshot)

![image](https://user-images.githubusercontent.com/14079908/131145690-1eae6a7f-4f48-4066-a179-db06e383a547.png)

Version:  2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by dmvtech** [comment]
> Hi, I use bot composer 2.1 with several languages.
> In some of the languages, the yes/no options generated from bot are in the selected language. In others languages, they always are in English.
> 
> For example Spanish, German, French is fine but in Italian, Russian, Hebrew, Arabic, always "(1) Yes / (2) No" is generated.

Correct. You can see that in the ConfirmInput, that we [only have a set amount of languages](https://github.com/microsoft/botbuilder-dotnet/blob/fe483b10756d1aa9a8072a5667ccbfdc22febbb9/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/ConfirmInput.cs#L31) preconfigured. 

You could add those languages to your **_own_** build of that class/library, then use that in your bot. Additionally; you could add the changes and submit a PR for that. I don't know if just adding additional lines/languages would be enough. i.e. If there are other aspects that need to be in place regarding other languages, but it might be worth a try.

> Would be nice if we at least would get an option to store those options in target languages somewhere in common.lg or somewhere else.

I do agree that would be nice. Please open a [feature request](https://github.com/microsoft/BotFramework-Composer/issues/new?assignees=&labels=feature-request%2C+Needs-triage&template=bot-framework-composer-feature-request.md&title=) with this suggestion to see if it would be considered.

> And in rtl languages like Arabic or Hebrew, the output looks messed up like "Yes / (2) No (1)" while 1 is yes and 2 is no - but if I copy that in an translater it is translated correctly. I'm not sure about as I'm not an rtl-expert, but can't imagine how this can be correct. (yellow marks in screenshot)

I think this would be easy enough if configuring those additional languages; you would just flip the order. (maybe not the best design, but would work in a pinch).

**Comment by dmvtech** [comment]
Closing as answered. Feel free to open a feature request as needed.
