### ISSUE TITLE
Allow Interruptions

### ISSUE THREAD

**Issue by ryuzaki4337** [microsoft/BotFramework-Composer#8617]
I'm trying to create a bot that asks the country name and gets the capital of that country. I wanted to add an interruption after asking the country's name, so that it cancels my request, with some message. But when I'm trying to change the "Allow Interruptions" option in the Prompt Configurations section, I'm facing this issue. Can anyone please help me regarding this? Thanks in Advance

"Uncaught SyntaxError...
If this problem persists, please file an issue on GitHub
Details
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '#root[9Nvo37].allowInterruptions-list2' is not a valid selector."

![image](https://user-images.githubusercontent.com/56956409/131239855-da3a1844-518d-487d-9d42-c96a7e4dbb4f.png)

**Comment by srinaath** [comment]
@ryuzaki4337 This bug has been resolved here https://github.com/microsoft/BotFramework-Composer/pull/8560. It should be fixed in the latest nightly. We also plan to release a patch in a few weeks that should also contain this fix.
Ref https://github.com/microsoft/BotFramework-Composer/issues/8515.
