### ISSUE TITLE
modify appsettings.json for a published bot in azure

### ISSUE THREAD

**Issue by afahmy11** [microsoft/BotFramework-Composer#8623]
hi 

is it possible to modify the appsettings.json file after publishing the bot to azure? i have a settings.mytoken that i am using in the bot which i need to update in the file when it is changed

**Comment by dmvtech** [comment]
Hi @afahmy11 Do you want to modify the actual appsettings.json file? or do you just want to change the settings. If the latter; you can just modify/add/change the settings in the application's (App Service) configuration.

![image](https://user-images.githubusercontent.com/43397658/131720645-52bdbfd0-20d0-447c-be97-2c7733074493.png)

If you want to update the file itself, you can use either make changes and re-publish, or you can use some of the built in tools in Azure. Such as `App Service Editor` or `Kudu` underneath `Advanced Tools`.

Using the app service's Configuration settings is the best and recommended.

**Comment by afahmy11** [comment]
thanks dana
i tried this but unfortunately it didn't get the new value.
in my appsettings.json file i have added mytoken[] which i can reach in the bot by referencing "settings.mytoken"
in azure i have added my token with the new value but still in runtime i am getting the old value saved in the appsettings file
![2021-09-02 at 9 59 AM](https://user-images.githubusercontent.com/49028761/131805738-9934d732-03ce-4ac1-81c3-1e0f6f121f79.jpg)

![2021-09-02 at 10 10 AM](https://user-images.githubusercontent.com/49028761/131807414-6356831a-a6dc-4b2a-b512-c33a9f58afd0.jpg)

![2021-09-02 at 10 09 AM](https://user-images.githubusercontent.com/49028761/131807123-aa453e9f-a6aa-4e40-95cf-73257506d1b2.jpg)

**Comment by dmvtech** [comment]
@afahmy11 Ah; I didn't realize your setting was an array (I assumed just a string). Did you try the other routes? (Republishing or going through the azure portal to update the appsettings.json?)

**Comment by afahmy11** [comment]
thanks i used the App Service Editor to edit the file
