### ISSUE TITLE
Trying to get input form with submit button in PVA

### ISSUE THREAD

**Issue by alok-kumar** [microsoft/BotFramework-Composer#8635]
I am trying to get input form with submit button. as per the example given in the MS Doc -
https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example4  
where we can take input from user and submit it in SP list. but unable to get the form. Json is correct I already checked it on https://adaptivecards.io/
only the thing -${StartTrialForm()} command is written in attachment which is not working. 

Version:  2.1.0-nightly.266986.c355633
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Chrome
- [ ] Edge

## OS

 [ ] Windows

I am looking for 
![image](https://user-images.githubusercontent.com/7149269/132187979-812f641c-1627-4277-b603-587457a97a14.png)

![Capture](https://user-images.githubusercontent.com/7149269/132287069-eacea580-8070-4caf-8755-1fe1d26374d0.JPG)

**Comment by dmvtech** [comment]
Hi @alok-kumar Can you confirm that you are in the `Show Code` form of the editor? Such as:
![image](https://user-images.githubusercontent.com/43397658/132922503-461aefb6-befa-4eca-9054-259b3884c397.png)

And not the `response editor`, such as:
![image](https://user-images.githubusercontent.com/43397658/132922600-0df45c4b-78bc-4d6f-b572-424df45052ad.png)

Do you have any unknown intents configured (as per example 3)?

**Comment by dmvtech** [comment]
If using the response editor, it needs to be:
`-${json(StartTrialForm())} `

Instead of:

`-${StartTrialForm()}`

Another way would be to use the following in `Show Code`:
```
[Activity
    Attachments = ${json(StartTrialForm())}
]
```

**Comment by dmvtech** [comment]
I've filed a documentation bug: https://github.com/MicrosoftDocs/power-platform/issues/890

I'll go ahead and close this. Please let me know if that does not resolve the issue for you.
