### ISSUE TITLE
I failed to build the Bot when adding QnA Maker with Bot Framework Composer

### ISSUE THREAD

**Issue by laurence-lin** [microsoft/BotFramework-Composer#8636]
I've build a chatbot with Bot Framework Composer using LUIS backend, and everything works fine until I decided to add QnA functions to it.

I'd previously built an QnA bot with QnA Maker and published it, and I'd made sure it's working fine when I connected it to LINE on mobile phone. It could answer the question properly when I ask questions on LINE.

Then I tried to connect the QnA knowledge base to existing chatbot, I configured the QnA subscription key in Configurations.  However, when I start the bot it shows error:

```
Sorry, something went wrong with publishing. Try again or exit out of this task.

QnA Maker build failed: This error may indicate that your Search service requires an upgrade. For information about the Search service limits, see here: https://docs.microsoft.com/en-us/azure/search/search-limits-quotas-capacity
```

It seems my subscription plan is reaching a limit, what should I do to make it work?

Thank you

**Comment by stevkan** [comment]
This doc outlines the limits placed on the QnA Maker service. You can compare your service to these limits. If you suspect you have reached the limit for your subscription plan, then you will need to increase the tier of the plan or wait until the limit resets for the period.

**Comment by stevkan** [comment]
Closing as resolved.
