### ISSUE TITLE
Trace Activities from Custom Actions not logged in App Insights

### ISSUE THREAD

**Issue by lshade** [microsoft/BotFramework-Composer#8637]
## Describe the bug

I am sending trace activities in Custom Action code that the composer bot calls. 

`await dc.Context.SendActivityAsync(new Activity(type: ActivityTypes.Trace, label: result ? "SmsAction SUCCESS" : "SmsAction FAILED", value: smsMessage));`

The custom action is working as expected, and in local development I'm able to see the trace activities (in the emulator and in the WebChat tab in composer.) After deploying to Azure with this in appsettings, I do not see any traces in that App Insights resource:

```
   "telemetry": {
      "logActivities": true,
      "logPersonalInformation": false,
      "options": {
        "instrumentationKey": "<key>"
      }
    },
```

## Version

v2.1.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Use custom action that sends trace activity
2. Verify it's working from your composer dialog
3. Deploy to Azure with telemetry settings
4. Search App Insights logs for the trace activity

## Expected behavior

Trace activity from Custom Action should be logged in App Insights.

**Comment by tonyanziano** [comment]
@lshade are you seeing other activity being recorded in your App Insights instance? Is it just the custom action trace that's missing?

**Comment by lshade** [comment]
C# and yes, I'm able to see other traces and customEvents
![image](https://user-images.githubusercontent.com/16640521/132386872-dc345aff-c6a2-4f1b-af0f-8659eeca0f38.png)
![image](https://user-images.githubusercontent.com/16640521/132386916-4753e969-76e4-46cd-a6f7-4dbb06730ee2.png)

When I search for the custom action log, I see a couple customEvents, but no traces
![image](https://user-images.githubusercontent.com/16640521/132387071-ae165a16-0221-46be-98d4-7fe0f26ba11f.png)

**Comment by tonyanziano** [comment]
Hey @lshade ,

I spoke with a teammate and they informed me that Trace activities are only for debugging and are not logged to App Insights because they contain the entire dialog stack JSON and could have some state data that should not be persisted to the instance.

I think the way to go is to [use the TelemetryLoggerMiddleware](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0&tabs=javascript) inside of your custom action -- configured with your App Insights credentials.

I will try to confirm this and get more details.

**Comment by Stevenic** [comment]
@lshade  look at this code example for how to log telemetry events within a custom action:

https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/TelemetryTrackEventAction.cs#L93

**Comment by lshade** [comment]
Thank you! Changing it to `TelemetryClient.TrackEvent("SmsAction", dictionary);` worked like in the example
