### ISSUE TITLE
Not able to add the custom bot template with the help of composer extension. 

### ISSUE THREAD

**Issue by akshaykc27** [microsoft/BotFramework-Composer#8644]

**Comment by dmvtech** [comment]
Hi @akshaykc27 Can you give some more info here? What Composer extension are you referring to? Is there an error? Do you have a screen shot? Are there specific steps you can give for us to try and reproduce the issue?

**Comment by akshaykc27** [comment]
![addbottemplate](https://user-images.githubusercontent.com/47749983/133037339-7b24e584-c4e1-4355-8fe2-e70a2ad04488.png)

@dmvtech the documentation does not give a clear picture where exactly should one add this code snippet to add a custom bot template.

**Comment by dmvtech** [comment]
@akshaykc27 Are you building your own version of Composer, or are you using the downloaded/Electron version?

**Comment by dmvtech** [comment]
You might want to follow [this document](https://github.com/microsoft/BotFramework-Composer/blob/main/extensions/sample-ui-plugin/README.md) and see if you can get the Simple UI plugin working.

Regarding this part:

> To see a working sample in action, just navigate to /sample-ui-plugin/package.json in this directory and change the `composer.enabled` property to `true`, and the `composer.contributes.views.page-DISABLED` key to `page`.

I only had to do the first part (change the `composer.enabled` property to `true`).

**Comment by akshaykc27** [comment]
Thank you the first part worked. I tried enabling the custom routes and its working 👍  but in the same package when I try to add a Bot template using composer.addBotTemplate it does not list in the templates while creating a bot.

**Comment by dmvtech** [comment]
Thank you @akshaykc27. Are you able to share your extension/template?

**Comment by akshaykc27** [comment]
I'm just trying to add another template and load it locally with the help of the addBotTemplate extension that's not working apparently.

**Comment by compulim** [comment]
@dmvtech I believe you got some guidance on this one. Please let us know otherwise. 🙂

**Comment by dmvtech** [comment]
Hi @akshaykc27 I apologize for the delay.

Unfortunately, you can no longer add templates using the extension mechanism. My apologies. 

In the next release, you will be able to add your own feed to point to, to allow you to create bots from that. This would need to be a npm-compatible feed, and won't support a local feed.

For now, you can create your own template based off of the [Empty bot (or any other) template](https://github.com/microsoft/botframework-components/tree/main/generators) and then generate bots using Yeoman, then they can be opened in Composer.
