### ISSUE TITLE
oauth - How to change the behavior of the "Sign In" button of the OAuthCard to just open the URL without redirect

### ISSUE THREAD

**Issue by nahlaGit** [microsoft/BotFramework-Composer#8658]
## Version

V2.1.1

## Browser

- [ ] Electron distribution
- [* ] Chrome
- [ ] Safari
- [ ] Firefox
- [ *] Edge

## OS

- [ ] macOS
- [* ] Windows
- [ ] Ubuntu

## Expected behavior

get token from authcard without go to redirect url and copy the code manually .I would expect the page to redirect to my bot with a token 

## Screenshots

![image](https://user-images.githubusercontent.com/57720132/132963439-09342002-548c-49b2-bedf-dc9cde34a5ae.png)

## Additional context

i use framework composor for my bot
deply my bot in a intanet page with directline

**Comment by stevkan** [comment]
@nahlaGit, please try sending a Signin card instead of using the OAuth prompt/dialog. You can reference [the docs](https://docs.microsoft.com/en-us/composer/how-to-send-cards?tabs=v2x#signincard) on how to achieve this. In this way, you can specify the URL to follow without having to include a redirect.

**Comment by nahlaGit** [comment]
@stevkan thans for your replay but how i can get token from  Signin card in framework composor?

![image](https://user-images.githubusercontent.com/57720132/133593736-1e4ec4e6-1fba-476a-902e-bc18a156f088.png)
![image](https://user-images.githubusercontent.com/57720132/133593824-89ce9f0a-372d-4b23-9706-42166b9684b9.png)

how i get the content token like with the oauth card 
![image](https://user-images.githubusercontent.com/57720132/133595588-b39bc259-f041-498e-baed-5eedcd404a86.png)

**Comment by nahlaGit** [comment]
@stevkan thhans for your replay but how i can get token from Signin card in framework composor?
![image](https://user-images.githubusercontent.com/57720132/133596078-0b3c80dc-1300-4be4-9e12-c2f7e2abb7f0.png)
![image](https://user-images.githubusercontent.com/57720132/133596148-7a5d3742-05c8-47bc-b411-e789307ccbd0.png)

i need to get token like with the oauth card

**Comment by nahlaGit** [comment]
This bug stops my whole project. Need at least working work around to use directline in sp site and to authenticate,
 at least how can I handle verification code?
i use this [direcline sample]( https://github.com/withum-digital/directline-bot-extension-blog)  to deply my bot in my sharpoint site but 
i get this error "Taking longer than usual to connect." when i use  the directline enhance feature
![image](https://user-images.githubusercontent.com/57720132/133598555-8874fb57-f044-4383-b172-772098c7f12e.png)

![image](https://user-images.githubusercontent.com/57720132/133598174-cf8a4915-bc4e-46b6-812c-c5d046077952.png)

![image](https://user-images.githubusercontent.com/57720132/133597920-940c1341-71e9-468b-8f69-017de5e3bc8d.png)

**Comment by stevkan** [comment]
@nahlaGit, thank you for your patience. I will be taking a look at this, today. So, I hope to post some kind of response in the issue by the end of it for you. A question for you about it, though.

I, more or less, get why using the Signin Card doesn't work. Regarding the flow, is it that you are just trying to not have the magic code pop up? Are you trying to provide an SSO experience for your users? What is the goal and why are you trying to avoid the redirect URL?

**Comment by nahlaGit** [comment]
@stevkan thanks for your help,yes i try to not have the magic code pop up and i use this tutorial [linksso](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso?tutorial-step=3) to make sso exprience for users,it works good in teams but in sharepoint site it give me the magic code pop up .

**Comment by stevkan** [comment]
@nahlaGit, let me connect with a colleague who is much more familiar with SharePoint than I am. I will provide an update when I know more.

**Comment by nahlaGit** [comment]
@stevkan thanks

**Comment by nahlaGit** [comment]
@stevkan thanks your for your answer but now i have another two diffrents probelme:
1) when i user gulp serve --nobrowser i get this in my site
![image](https://user-images.githubusercontent.com/57720132/139753174-da8efba9-d0b0-4706-82e0-94ed237fbc06.png)

error 404
![image](https://user-images.githubusercontent.com/57720132/139753350-dea358d3-d029-4939-80c9-e9c2fc6a8dd5.png)

error 403:
![image](https://user-images.githubusercontent.com/57720132/139753213-daa6ad6e-3c3f-449a-93b9-ba28ca970d14.png)

in your exemple project they said that i should replace:

- Edit "BotFrameworkChatPopupApplicationChat.tsx" file to set your bot endpoint (`props.botEndpoint`) directly like `https://YOUR_BOT.azurewebsites.net` for testing purpose (instead of setting it in the Tenant Wide Extensions list):

    ```ts
    generateToken(props.botEndpoint, md5(userId)).then((token: string) => { //change props.botEndpoint to the endpoint directly if you want to test it
    if (token) {
        setDirectLine(createDirectLine({ token }));
    }
    });
    ```

- Edit "BotSignInToast.tsx" file to set your AAD scope uri(`scopeUri`) with `api://YOUR_APP_ID` directly like `api://123a45b6-789c-01de-f23g-h4ij5k67a8bc` for testing purpose:

    ```ts
    return tokenProvider.getToken(scopeUri, true).then((token: string) => {
    ```

- Add the following config to ./config/package-solution.json:
    ```diff
        "webApiPermissionRequests": [
    +     {
    +       "resource": "<YOUR_APP_ID>",
    +       "scope": "<YOUR_AAD_SCOPE_NAME>"
    +     }
        ],
    ```


2)but when i use just gulp serve i get nothing in my page and i have this like issue : 
![image](https://user-images.githubusercontent.com/57720132/139753790-e1160021-e1b6-4797-9cae-110b33ce0dda.png)



how i can fix it and make it work plz

**Comment by nahlaGit** [comment]
@stevkan  hello i have another question about composor  how i can get token from Signin card in framework composor?
# SigninCard
[SigninCard
    text = BotFramework Sign-in Card
    buttons = ${cardActionTemplate('signin', 'Sign-in', 'https://login.microsoftonline.com/')}
]

![image](https://user-images.githubusercontent.com/57720132/140081978-91a965ea-ce9c-422c-b5d9-a986478b23bf.png)

**Comment by stevkan** [comment]
Regarding the problems you are experiencing in trying to implement the [Bot Framework SSO](url) solution, you will need to reach out to the team that built that solution for assistance on it. I don't know enough about SharePoint to know how the different components connect or share data/resources. There is a GitHub repo for the solution, [react-bot-framework-sso](https://github.com/pnp/sp-dev-fx-extensions/tree/main/samples/react-bot-framework-sso), where I would recommend you file an issue.

As for the 'SigninCard' problem, please create a new issue for that question. This way each filed GitHub issue is tied to one discussion.

**Comment by stevkan** [comment]
@nahlaGit, I don't believe it is possible to get the token from a Signin Card, presently. Being able to do so I think would work if you coupled the login process on a page with sending a proactive message back to the bot via a script. This also assumes you have some control over the page's auth process.

However, at this time, Composer does not support receiving incoming proactive messages. (For understanding, a proactive message is a message sent to the bot from an external source. For example, clicking a buy button on page might send a message to a bot starting a conversation in Teams with the user with information about that product.)

As it is, I cannot think of another way this could work.

**Comment by stevkan** [comment]
Closing this as resolved.
