### ISSUE TITLE
Why QnAMakerRecogniser creates intent on Luis?

### ISSUE THREAD

**Issue by mohd-ismail-siddiqui** [microsoft/BotFramework-Composer#8672]
@luhan2017 As I can see in one of my bot project where I have used both LUIS and QnAMaker. When I built the project and run it. I have seen in Luis app, there is an intent like DeferToRecognizer_QnA_VirtualTravelAssistant.

But When I created another project, where I have added one more intent (except Greeting and Unknown) i.e. QnA Intent Recognized, then I observed that there is no LUIS created and no intent found.

Please help me to understand this.

**Comment by luhan2017** [comment]
Could you provide more information, share your bot here or check if you set recognizer type to other types(Regex or Orchestrator)?

**Comment by mohd-ismail-siddiqui** [comment]
[BotSampleLuis](https://github.com/mohd-ismail-siddiqui/BotSampleLuis)
[VirtualTravelAssistantQnA](https://github.com/mohd-ismail-siddiqui/VirtualTravelAssistantQnA)

Thanks @luhan2017  for quick response and it make some sense but still facing issues like when I change the recognizer of Main dialog from Default -> Regex then QnA Intent Recognizer stop working. 

Also I am facing another issue where I have define some multi-choice option for user and for each option I have defined intent recognizer trigger. But the issue is when I click on any option at one time it only show the same option as utterance and nothing happened but when i click second time then it will trigger particular intent. 

Could you please help me. I have attached link for both bot sample solutions.

**Comment by mohd-ismail-siddiqui** [comment]
@luhan2017 @srinaath : Do you need any further information in order to resolve this issue.

**Comment by luhan2017** [comment]
@mohd-ismail-siddiqui, It is by-desige that Regex recognizer is just for language understandin, QnA is not supported when you select Regex recognizer. 

For the multi-choice options, try to set AllowInterruptions to true and try again.
![image](https://user-images.githubusercontent.com/32191031/134476369-e5b75d51-a8a6-40e1-b171-1fdda6220477.png)

**Comment by mohd-ismail-siddiqui** [comment]
Thanks @luhan2017 for this response. It make sense.
