### ISSUE TITLE
Localization Change Causes Publishing Problem (also not working on Emulator)

### ISSUE THREAD

**Issue by humak** [microsoft/BotFramework-Composer#8673]
## Describe the bug

My bot is working properly on the composer web chat whether the default language is English or Turkish. But on Emulator, it is only working properly when the default language is English. When I change the language to Turkish, it is not working on the Emulator.

It also causes problems in the Publishing phase, if the bot is not working on the Emulator, it is not working after publishing too.

## Version

Version:  2.1.0-nightly.266986.c355633
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
(experienced the same issue on the stable version too)

Emulator: 4.13.0

## Browser

- Edge

## OS

- Windows

## To Reproduce

1. Change your localization settings, make Turkish default language
2. Try on webchat, it will work properly 
3. Try on Emulator, it will possibly fail (no answers)
4. Try to publish, if it is successfully published, try from Azure Portal, it will not work properly (no answers)

## Screenshots

1. When localization is English: it works on emulator

![image](https://user-images.githubusercontent.com/14835957/133767296-be547437-958a-41a5-8dce-2b5d058353fe.png)

2. Turkish case: it works on webchat but not on Emulator

![image](https://user-images.githubusercontent.com/14835957/133767684-899eb1df-9312-425e-b4db-5a8775366455.png)

## Additional context

We spend so much time trying to understand why it fails after publishing and not responds, thats how we discovered that, when it stays on English as default, it works after publishing too, and emulator of course.

**Comment by srinaath** [comment]
![Screen Shot 2021-09-17 at 11 04 25 AM](https://user-images.githubusercontent.com/13004779/133833852-4fb413f8-c71b-4be9-acbd-365a2d64b987.png)

@humak This is an emulator setting that needs to be changed to the locale that you want the bot to respond to. The current locale set on Composer does not get set on Emulator when we use the operation "Open in Emulator" from Composer.

**Comment by humak** [comment]
We tried your solution and it worked on Emulator. Thank you so much!

We still couldn't reach the published bot from Azure Portal WebApp Chat.
Do you have any suggestion about how we can add this language parameter during/after publishing bot to Azure WebApp? Since these problems are connected and similar, I think we are also missing some point during publishing phase.

**Comment by dmvtech** [comment]
> We still couldn't reach the published bot from Azure Portal WebApp Chat.
> Do you have any suggestion about how we can add this language parameter during/after publishing bot to Azure WebApp? Since these problems are connected and similar, I think we are also missing some point during publishing phase.

Hi @humak Are you referring to `Test in WebChat` or full WebChat?

The locale of the browser should be the thing that is telling WebChat and the bot what locale should be used. For example, in Emulator, you can see what locale is being sent:
```json
{
  "type": "conversationUpdate",
  "membersAdded": [
    {
      "id": "______________________________",
      "name": "Bot"
    },
    {
      "id": "______________________________",
      "name": "User"
    }
  ],
  "from": {
    "id": "______________________________",
    "name": "User",
    "role": "user"
  },
  "locale": "de-de",
  "serviceUrl": "http://localhost:64085"
}
```

Are you able to test with a browser using both English and Turkish locales?

**Comment by dmvtech** [comment]
Related: https://github.com/microsoft/BotFramework-Emulator/issues/2268

**Comment by humak** [comment]
Hi @dmvtech , maybe I can explain better with this example.

1. I have a bot build in Bot Composer , the localization is Turkish. It works in local webchat.
![image](https://user-images.githubusercontent.com/14835957/134311940-e6f9a98a-6113-4da0-964b-34d2f5d7859e.png)

2. It works in the Emulator when we changed the locale as you suggested:
![image](https://user-images.githubusercontent.com/14835957/134312000-337eca88-31bd-4acf-9a54-9d9470cffe20.png)

3. Then we publish bot to Azure. And In the Azure Bot APP Test Webchat , the bot is not running.
![image](https://user-images.githubusercontent.com/14835957/134312117-98a59189-daf3-4b9e-b56d-1d686e64ef19.png)

We got this error when we publish the bot to Azure as locale tr-TR (Turkish.)
![image](https://user-images.githubusercontent.com/14835957/134312182-7e67f2f3-c0eb-43b4-b817-ea198b6d08ed.png)

When the bot’s locale is en-us (english), it works.
The question is : Should we add a property to publishing profile when we are publishing in Turkish? We can send you the publishing profile as json.

**Comment by dmvtech** [comment]
@humak 

When you publish, it will publish all locales that you have created/configured. Just to confirm; you did not remove `en-US` locale from the bot, correct?. 

So, my _assumption_ is that there is something wrong with the published bot, **regardless** of locale. The `Test in WebChat` and Azure portal are obviously running in English (I'm assuming `en-US`).

One thing you can do is [use Ngrok and test your local running bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0) through the `Test in WebChat` tool. This will confirm that everything but the bot running in Azure (App Service) is working correctly.

Otherwise:

- Have you tried _re_-publishing?
- Gateway timeout usually means the bot was running long. Does it do anything at the beginning (of the conversation start), that might take a long time (API call, etc)?

**Comment by dmvtech** [comment]
Hi @humak. Have you tried any of the above? Any answers to the questions above?

**Comment by dmvtech** [comment]
Closing due to lack of response. Please comment with answers to above questions if you still need assistance.
