### ISSUE TITLE
Starting bot emulation takes 2,5 minutes each time

### ISSUE THREAD

**Issue by hiviq** [microsoft/BotFramework-Composer#8685]
## Describe the bug

Currently developing a bot, the starting time of 2,5 minutes for the emulation is putting a huge delay on top of the development each day. Can you advise how I can identify the cause?

## Version

2.1.1

## Browser

- [X] Edge

## OS
- [X] Windows

**Comment by tamasschmolcz** [comment]
I located the issue, not sure why yet, but Composer imported all Questions from my QnA KB with every sync (8000 intents sentences+).

So I removed the QnA Stuff and brought it down to 30 seconds. Still investating the QnA issue. Might open a seperate case.
