### ISSUE TITLE
Adaptive card is not rendering again once already populated

### ISSUE THREAD

**Issue by venkatraj109** [microsoft/BotFramework-Composer#8691]
**Technologies used:-**
1. Bot Composer Framework - v1.3.1
2. Angular, node
3. Azure bot direct line

**Requirement:-**
Need to collect address information from the customer and validate it. If entered address is invalid then ask user again to get valid address.

**The steps which I followed to achieve:-**
1. Used Adaptive Card Form to collect address details from the customer through azure bot direct line.
2. Stored those entered address details in **conversation** state for future use.
3. Passing those address details to backend for validation (Access external resources - Send an HTTP request).
4. If address is valid then proceeding furtherly.
5. If address is not valid then am trying to repopulating the same Adaptive Card Form.

**Issue that am facing:-**
As mentioned in point number 5 above, when am trying to repopulating the same adaptive card form its not populating and its simply skipped and moved next step.

**Adaptive Card Form:-**

#AddressAdaptiveCard
```
[Activity
    Attachments = ${json(addressAdaptivecardjson())}
]
```

#addressAdaptivecardjson
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
         {
            "type": "TextBlock",
            "text": "Text here...",
            "wrap": true,
            "weight": "default",
            "horizontalAlignment": "left"
        },
        {
            "type": "TextBlock",
            "weight": "default",
            "text": "Text here....",
            "horizontalAlignment": "left",
            "wrap": true
        },
        {
            "type": "TextBlock",
            "text": "Click on Submit once you fill all these details in the following form.",
            "wrap": true,
            "weight": "default",
            "horizontalAlignment": "left"
        },
        {
            "type": "Input.Text",
            "label": "Name",
            "style": "text",
            "id": "shipToName",
            "isRequired": true,
            "value": "${turn.Activity.From.name}",
            "errorMessage": "Name is required."
        },
        {
            "type": "Input.Text",
            "label": "Phone Number",
            "style": "Tel",
            "id": "shipPhoneNumber",
            "isRequired": true,
            "errorMessage": "Phone number is required."
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "Input.Text",
                    "label": "Email Address",
                    "style": "Email",
                    "id": "shipEmailAddress",
                    "regex": "^[A-Za-z0-9._%+-]+[A-Za-z0-9._%+-]*[A-Za-z0-9._%+-]*@[a-z0-9]+.[a-z]{2,4}$",
                    "isRequired": true,
                    "value": "${turn.Activity.From.id}",
                    "errorMessage": "Please enter a valid email address"
                }
            ]
        },
        {
            "type": "Input.Text",
            "label": "Address Line 1",
            "style": "text",
            "id": "shipAddressLineOne",
            "isRequired": true,
            "errorMessage": "Address Line 1 is required."
        },
        {
            "type": "Input.Text",
            "label": "Address Line 2",
            "style": "text",
            "id": "shipAddressLineTwo",
            "errorMessage": "Address Line 2 is required."
        },
        {
            "type": "Input.Text",
            "label": "City Where Label will be Shipped",
            "style": "text",
            "id": "shipCity",
            "isRequired": true,
            "errorMessage": "City is required."
        },
        {
            "type": "Input.Text",
            "label": "State Where Label will be Shipped",
            "style": "text",
            "id": "shipState",
            "errorMessage": "State is required."
        },
        {
            "type": "Input.Text",
            "label": "Country Where Label will be Shipped",
            "style": "text",
            "id": "shipCountry",
            "isRequired": true,
            "errorMessage": "Country is required."
        },
        {
            "type": "Input.Text",
            "label": "Zip Code",
            "style": "text",
            "id": "shipZipCode",
            "isRequired": true,
            "errorMessage": "Zip Code is required."
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit"
        }
    ]
}
```

Used below code, in dialog.
`- ${AddressAdaptiveCard()}`

Please suggest me to resolve the issue or Is there any alternative way to achieve this?

**Comment by compulim** [comment]
[Adaptive Cards data templating](https://docs.microsoft.com/en-us/adaptive-cards/templating/) may help on populating data. But I am unsure if Composer support data templating.

Anyone from the Composer team know about this? It's also same as the "Sample Data Editor" in the [Adaptive Card designer](https://adaptivecards.io/designer/).

**Comment by venkatraj109** [comment]
Thanks for your reply @compulim.

Seems its required platform SDK as mentioned in above link you shared. But, not sure how to add SDK in bot framework composer to use Adaptive Cards Data Templating. 

Is bot composer supports platform SDK? Suggest me if anybody knows.

**Comment by compulim** [comment]
@tonyanziano @a-b-r-o-w-n do you know if Composer support data templating?

I mean, the following screenshot from Adaptive Card designer, do we support this feature?

![image](https://user-images.githubusercontent.com/1622400/134722932-07168b0f-08cf-4666-9287-4dcf198196dc.png)

If yes, how can it be done? (Maybe a StackOverflow question)

If no, how can we populate data in an Adaptive Cards? Should we ask the customer to dupe the card?

**Comment by a-b-r-o-w-n** [comment]
@venkatraj109 Composer does support data binding when creating adaptive cards using the [LG syntax](https://docs.microsoft.com/en-us/composer/concept-language-generation?tabs=v2x). In order to update an adaptive card that has already been rendered, you would need to use the `Update activity` action and resend the adaptive card json.
![image](https://user-images.githubusercontent.com/3619060/134935875-20d3a744-205b-4369-945f-7768508e189d.png)

**Comment by venkatraj109** [comment]
@a-b-r-o-w-n, In my case is Update Activity required?

My actual issue is when I try to render the Adaptive Card(-${AddressAdaptiveCard()}), its not showing. its just skipped into next step.

![Screenshot (203)](https://user-images.githubusercontent.com/5449915/135031363-45b2c354-103b-4a5e-ad3f-9db2192fc4b3.jpg)

**Comment by venkatraj109** [comment]
@a-b-r-o-w-n I am using Bot Framework Emulator and Web Chat.

As per the docs [https://docs.microsoft.com/en-us/composer/concept-memory?tabs=v2x](url), Update Activity is not supporting for Bot Framework Emulator and Web Chat.

![Screenshot (8)](https://user-images.githubusercontent.com/5449915/135043981-fe1a57e9-460b-401a-977c-81400f35c432.png)

**Comment by a-b-r-o-w-n** [comment]
@venkatraj109 Composer will not re-prompt by default if the property already has a value, in this case `conversation.shipToName`. Try updating the `Always prompt` option to true or deleting the value from state before prompting.

![Screen Shot 2021-09-28 at 10 00 10 AM](https://user-images.githubusercontent.com/3619060/135132480-4031894f-1802-403d-974b-c0ed9002a638.png)

**Comment by venkatraj109** [comment]
@a-b-r-o-w-n I have implemented the same approach and my issue was fixed. Thanks for your help.
