### ISSUE TITLE
Suggested actions are not showing up after publishing to Microsoft Teams

### ISSUE THREAD

**Issue by eda-ayan** [microsoft/BotFramework-Composer#8693]
## Describe the bug

We designed a bot on Bot Framework Composer and we published the bot with EN-US local. It is successfully working on Teams. Nevertheless, we cannot see the suggested actions at any point on Teams. We can see and use suggested actions successfully on Composer WebChat and the Emulator. 

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Edge

## OS

- [ ] Windows

## To Reproduce

1. Create suggested actions on bot
2. Try on WebChat and Emulator, it will work properly with suggested actions
3. Publish your bot and add to Teams
4. Try on Teams.

## Expected behavior

When tried on Teams, suggested actions are not showing up on our case. We want to be able to use them in Teams. 

## Screenshots

On Composer WebChat:
![image](https://user-images.githubusercontent.com/25666677/134522440-72b6eab3-ffa2-490c-bc39-a9b9067e2693.png)

On Emulator:
![image](https://user-images.githubusercontent.com/25666677/134522693-47f6790a-c435-475d-9b30-23b7d889231d.png)

On Teams:
![image](https://user-images.githubusercontent.com/25666677/134522254-57f687f3-a883-4b73-aa18-270de49f8951.png)

**Comment by jwiley84** [comment]
hi @eda-ayan 

Suggested Actions aren't supported by Teams:

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#action-support-by-channel
