### ISSUE TITLE
Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm root -g --prefix C:\Users\Dragon boy\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error 'npm' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by catvboy** [microsoft/BotFramework-Composer#8694]
## Describe the bug

Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm root -g --prefix C:\Users\Dragon boy\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error 'npm' is not recognized as an internal or external command, operable program or batch file.

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by anusharr** [comment]
Similar to reported in #8634. Can you verify you have both NodeJS and npm installed on your machine?Also, can you specify your npm version and confirm if npm is in your PATH environment variable?

**Comment by anusharr** [comment]
Closing due to no response.
