### ISSUE TITLE
need help regarding connecting to remote skill bot 

### ISSUE THREAD

**Issue by saif177** [microsoft/BotFramework-Composer#8695]
i am trying to connect composer with remote skill but there are some issues i am facing 

1.  unable to distinguish from values that has to be filled in 'import existing resources' 
![Screenshot (45)](https://user-images.githubusercontent.com/73467925/134617531-d69e2bcd-41f2-4b31-9e6c-261e459ab381.png)

can anyone please help me to find difference between **autheringkey** and **endpointkey** , **authoringEndpoint** and **endpoint** .

thank you

**Comment by saif177** [comment]
I am using Empty bot template . hope that is not an issue

**Comment by anusharr** [comment]
@saif177, can you elaborate on the steps you are following? If you use the `Set up Language Understanding` in the `configure` part and select `Use existing resources` option and login with your credentials, the it will show the authoring key and region and you need to select `Done` as mentioned in the [documentation](https://docs.microsoft.com/en-us/composer/how-to-add-luis?tabs=v2x). Generally, you head over to your LUIS portal and click on the app and then select "Manage > Azure Resources > Authoring Resource', where the primary key is the Authoring key and the endpoint URL is the authoringEndpoint.
