### ISSUE TITLE
Error when Create new 'Intent recognized Trigger' and insert phrases into popup

### ISSUE THREAD

**Issue by AntonioChiancone** [microsoft/BotFramework-Composer#8696]
## Describe the bug
When i create a new Intent Recognized Trigger, i can't submit when insert the phrases.

> ![log1](https://user-images.githubusercontent.com/8851915/134648914-b57309e0-b3a5-4da3-9163-4a26049f9939.JPG)
> ![log2](https://user-images.githubusercontent.com/8851915/134648950-11a8eda5-5c02-477c-9010-5a430e430b7d.JPG)

I can submit without phrases, after creation, i can insert phrases.

> ![log3](https://user-images.githubusercontent.com/8851915/134648972-15f9f4a1-1aa9-42d6-8097-f11674337aef.JPG)

## Version
Version:  2.1.1-nightly.268315.fa80e82
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS
- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Chatbot > Create'
2. Click on 'Create a trigger'
3. Scroll down to 'Intent Recognized'
4. Type an phrase and see error on typo 
5. Submit without phrases

## Screenshots

Error
![log2](https://user-images.githubusercontent.com/8851915/134648069-4dd86789-c9fb-4db7-84b0-873ada5a1288.JPG)

**Comment by dmvtech** [comment]
Hi @AntonioChiancone Are you typing in all the phrases, or are you pasting? I am not able to reproduce myself.

I'm wondering if maybe it might be a hidden or zero width space character(s) [`\u200b`]. See [this](https://github.com/microsoft/BotFramework-Composer/issues/7713#issuecomment-840087306) thread/comment for more info.

**Comment by dmvtech** [comment]
Closing due to lack of response. If you are still having this issue and need assistance; please comment with the answers to the above questions.
