### ISSUE TITLE
can we connect existing skill bot that is been coded with bot framework not composer and connect it to the bot composer?

### ISSUE THREAD

**Issue by saif177** [microsoft/BotFramework-Composer#8697]
hi, I am trying to to remote skill bot that I created using bot framework and **not composer** and I published it on azure.  now I want to connect that bot to my bot composer but I am unable to do that . can anyone please help me with that? 

here are the steps that I followed 

![Bot Framework Composer (v2 1 1) 2021-09-24 17-16-46](https://user-images.githubusercontent.com/73467925/134670563-212c7366-2876-49eb-8fab-bbbba9a199b0.gif)

**Comment by anusharr** [comment]
@saif177, can you specify what version of Composer you are on? Did you update the root bot to access the remote skill? Also, can you double check if you missed out on any step in the [documentation](https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill?tabs=v2x)?

**Comment by saif177** [comment]
@anusharr i am currently using 2.1.1 . and here is manifest file that I am using . please help me with it . 

[TestSkill_manifest.txt](https://github.com/microsoft/BotFramework-Composer/files/7229664/TestSkill_manifest.txt)

**Comment by tonyanziano** [comment]
@saif177 after adding the skill manifest to your Composer bot, you need to add a trigger that then calls a "Begin Skill Dialog" to actually jump into the skill flow that you imported. Please give that a shot.
