### ISSUE TITLE
Cannot create new project on Mac

### ISSUE THREAD

**Issue by sidecus** [microsoft/BotFramework-Composer#8700]
## Describe the bug

Cannot create new project on Mac. Below error is returned when doing so:

![image](https://user-images.githubusercontent.com/4399408/134890481-27a441bc-9ebd-449d-a7df-2a608eaf2231.png)

Running below command manually leads to file not found error (w/ or w/o elevated privilege):
```npm install -g --prefix /Users/xxx/BotFrameworkComposer/.yo-repository --loglevel error --no-optional @microsoft/generator-bot-core-language@1.1.2```

npm verb stack Error: ENOENT: no such file or directory, lstat '/Users/xxxx/BotFrameworkComposer/.yo-repository/lib'
npm ERR! enoent ENOENT: no such file or directory, lstat '/Users/xxxx/BotFrameworkComposer/.yo-repository/lib'
npm ERR! enoent This is related to npm not being able to find a file.

## Node/Npm version
```
/ » node --version 
v15.6.0
------------------------------------------------------------
/ » npm --version
7.4.0
```

## Version

2.1.1

## OS

- [ x] macOS

**Comment by sidecus** [comment]
Here is the detailed error when running the npm install command in the terminal directly:

```
npm verb stack Error: ENOENT: no such file or directory, lstat '/Users/xxxx/BotFrameworkComposer/.yo-repository/lib'
npm ERR! enoent ENOENT: no such file or directory, lstat '/Users/xxxx/BotFrameworkComposer/.yo-repository/lib'
npm ERR! enoent This is related to npm not being able to find a file.
```

**Comment by sidecus** [comment]
Adding more info.

1. I manually created the ```/.yo-repository/lib``` directory, and it passed that stage - npm install now finishes.
2. However it ran into another error complaining that "dotnet build xxx.csproj" failed. The project was not created at all and target folder was empty.
3. Found errors in the console window so I called the api/status api to see more details. There are many errors like below:
```
warning NU3028: Package 'System.Security.Principal.Windows 4.3.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
```
4. Checked my .Net SDK version:
```
  ~/repos » dotnet --version
  5.0.101
```
5. Upgraded .Net SDK:
```
  ~/repos » dotnet --version
  5.0.401
```

Now at least the project is successfully and composer can open it.

**Comment by benbrown** [comment]
@sidecus thanks for the additional info. Did upgrading the .net version resolve the build errors?

The lib sub-folder is normally created automatically by the npm install process. I am surprised you had to created it manually. Did it create the .yo-repository folder normally?

**Comment by sidecus** [comment]
@benbrown - .yo-repository was created but lib sub-folder was not. manually creating it resolved the npm install issue.

**Comment by tonyanziano** [comment]
Closing this as it looks like upgrading .NET and manually creating the `/lib/` folder in `/.yo-repository/` resolved the issue.
