### ISSUE TITLE
Showing Error : dotnet build MenuBot.csproj

### ISSUE THREAD

**Issue by mapur081999** [microsoft/BotFramework-Composer#8703]
I installed the Bot Framework Composer , with all the tools required as prerequisite. On creating a new bot I am getting error.

Error is : dotnet build MenuBot.csproj

![Screenshot (284)](https://user-images.githubusercontent.com/91449513/135024860-5f134129-e9df-46c3-a3b4-b82d3c913ddb.png)

**Comment by dmvtech** [comment]
Hi @mapur081999 

This might be a problem with your nuget sources. But you should try a few things to try and identify the actual problem.

Please see the comment [here](https://github.com/microsoft/BotFramework-Composer/issues/7876#issuecomment-881082316).

Try and see if you can create and build a bot from Yeoman template and see if that works (alternatively, just use the `dotnet nuget list source` command to see if nuget.org is enabled).

**Comment by dmvtech** [comment]
Closing due to lack of reply. Please comment with specifics if you still need assistance.
