### ISSUE TITLE
Upgrade to OneAuth/MSAL 1.36. Fixes Sign in error: Account Switch Detected

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/BotFramework-Composer#8711]
Sign in throws Account Switch Detected error. The latest version of OneAuth fixes this. To unblock customers, update composer dependency to 1.36 and do a patch release whenever possible.

ICM ref; 262551756

**Comment by tonyanziano** [comment]
This is being tracked at #8708

**Comment by tonyanziano** [comment]
Closed via #8712
