### ISSUE TITLE
Problem while converting skill from Composer 1.4.x to Composer 2.x.x

### ISSUE THREAD

**Issue by KunalKene1797** [microsoft/BotFramework-Composer#8715]
## Describe the bug

We have a Bot Composer 1.4.1 skill, we faced problems while converting it to the new Composer 2.x.x skill. The Composer skill we are using has a custom runtime with additional features supporting our requirements. After we got the "EISDIR: illegal operation on a directory" error. We looked up this issue and found a few that are related to this issue, no luck though (https://github.com/microsoft/BotFramework-Composer/issues/7444, https://github.com/microsoft/BotFramework-Composer/issues/7373). 

After opening the new converted project which had errors on conversion, saw errors throughout the skill about missing schemas and unsupported dialogs. (Screenshots attached below)

We were also wondering, what the standard conversion from 1.4.x to 2.x.x actually does other than adding the new adaptive runtime. If that's something that can be done manually.

**Things we've tried:** using other versions of NPM, starting composer with different privileges, with different subversions of bot composer 2.1.

## Version

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Launch Bot Composer 2.1.1.

2. Open an existing 1.4.x based skill.

3. Click on "Convert".

4. Create a new bot project with the following settings. (unlike what's in issue https://github.com/microsoft/BotFramework-Composer/issues/7373)

![image](https://user-images.githubusercontent.com/8381101/135615630-4081c0f4-9004-4b43-bb81-0aee64e6e295.png)

## Expected behavior

For it to at least convert the bare minimum of what's possible with automated conversion.

## Screenshots

![Screenshot (92)](https://user-images.githubusercontent.com/8381101/135611060-8df2313c-a733-4e2e-bde0-5957bda6b236.png)

![Screenshot (93)](https://user-images.githubusercontent.com/8381101/135611074-8016d41b-a9ef-4788-b9c6-88e40c561612.png)

![image](https://user-images.githubusercontent.com/8381101/135615525-5e113a20-76b3-4299-93a1-ed9602d28194.png)

**Comment by tonyanziano** [comment]
@luhan2017 do you happen to know anything about why this would be happening? Or do you know who would know more about converting legacy skill bots?

**Comment by luhan2017** [comment]
@KunalKene1797, could you please share your skill with me? Then I can debug it locally. I need to know 
- does your bot project include remote skills? The first screenshot looks like that your remote skill is not correctly loaded.
- does your skill have customer actions enabled? The second screenshot looks like that your sdk schema is malformed.
