### ISSUE TITLE
Composer: Create new bot > Immediate error

### ISSUE THREAD

**Issue by rrgrimm** [microsoft/BotFramework-Composer#8717]
## Describe the bug
I just installed Composer v2.1.1 and Node.JS. I am new to bot. I clicked "Create a new bot from start" and immediately got this error:

rror calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm root -g --prefix C:\Users\rgrimm\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error 'npm' is not recognized as an internal or external command, operable program or batch file.

## Version
2.1.1

## Browser
Edge Beta

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x ] Edge

## OS
Windows 11

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

See above description for steps.

## Expected behavior

After clicking the Create a new bot from start button, I was expecting to choose a template to get going.

**Comment by tonyanziano** [comment]
Hi @rrgrimm ,

Do you have `npm` and `NodeJS` installed on your machine? This is a prerequisite of using Composer as seen in the [README](https://github.com/microsoft/BotFramework-Composer/blob/main/README.md#prerequisites)

You can check by opening up a command line window or terminal of your choice and typing:

`npm -v`  and `node -v`
