### ISSUE TITLE
can't create a new bot - Azure web app (windows)

### ISSUE THREAD

**Issue by cvb23515** [microsoft/BotFramework-Composer#8718]
## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
@cvb23515 Can you share an error or a screenshot? We need more information to go on.

**Comment by dmvtech** [comment]
Closing until there is more information to go on. If you still need assistance with this, please provide more information so that we can help troubleshoot.
