### ISSUE TITLE
DEPLOY_ZIP_ERROR - Service Unavailable

### ISSUE THREAD

**Issue by drguthals** [microsoft/BotFramework-Composer#8724]
## Describe the bug

When attempting to deploy a bot from Bot Composer, I can successfully provision the resources in Azure, but when I Publish I get the error:

<img width="170" alt="Screenshot of the error in Bot Composer that says DEPLOY_ZIP_ERROR and calls out that the service is unavailable. It also says StatusCode 503" src="https://user-images.githubusercontent.com/1314285/135905760-b0fc7768-f13b-4381-a98c-de9bd4f9a2c7.png">

When I go to my Azure resource in the Portal, I see an error on the Channels pane:
`There was an error sending this message to your bot: HTTP status code ServiceUnavailable`

## Version

Version:  2.0.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot
2. Provision Azure Resources in Bot Composer
3. Publish Bot

## Expected behavior

Bot is published and has an available channel for testing

**Comment by tonyanziano** [comment]
Could be related to #8707

**Comment by drguthals** [comment]
@tonyanziano - I was thinking that, but that one seemed to have an issue with acquiring the address? Whereas mine simply said the service wasn't available.

Definitely could still be related though

**Comment by gabog** [comment]
Closing this one since it seems to have been a sporadic issue
