### ISSUE TITLE
Unable to create a bot using BotFramework-Composer using Node

### ISSUE THREAD

**Issue by Vasudev-2308** [microsoft/BotFramework-Composer#8730]
Hi, I've been trying to create a bot using the composer tool and have tried multiple times but this error 

**Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm install -g --prefix** 

Persists all the time 

Just for an info
My Node Version :- 14.17.6
My Npm version :- 7.24.0

**Comment by tonyanziano** [comment]
Hi @Vasudev-2308 ,

Do you have the ability to run Composer as administrator and if so, have you tried that?

Another thing you might want to try is creating your bot in a folder outside of the `/Users/` folder.

Alternatively, you might be able to try and run yeoman on the bot templates directly, outside of Composer and see if that works. Then you can point Composer to open the generated bot.

**Comment by Vasudev-2308** [comment]
Hey, Thanks for replying . 
I did try to run the composer as an Administrator and the location where I'm trying to create the bot is
**"C:\Users\SVasudev\Desktop\Bot"**  where I have downloaded the Composer in another folder in the same directory 
i.e  **"C:\Users\SVasudev\Desktop\Bot\Bot Framework Composer"** 
but I'm getting the same issue.

**Comment by Vasudev-2308** [comment]
Also I tried to build an empty bot using **"yo botbuilder"** command and try to point that to the composer but there isn't any progress.

**Comment by Vasudev-2308** [comment]
The Error I'm getting constantly is this
Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm install -g --prefix C:\Users\SVasudev\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error --no-optional @microsoft/generator-bot-core-language@1.1.2

NPM and Node are installed on my system as I had mentioned before
