### ISSUE TITLE
Images are not redering in Hero Card for locale tr-TR

### ISSUE THREAD

**Issue by ashokdevlabs** [microsoft/BotFramework-Composer#8732]
## Describe the bug
We have created Multilingual bot with multiple options in choice set. one of the option is to display images which is specified in Azure Table storeage. 

We have created bot in Portugese and Turkish languages. I am able to see images for portugese language but not for Turkish language. we are using directline channel for this.

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [x] Firefox
- [x] Edge

## OS 

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot in Turkish language
2. Use directline to see the response from bot
3. Pass the locale as tr-TR
4. See error in browser console

## Expected behavior

Should display the hero card with proper details

## Screenshots

![image](https://user-images.githubusercontent.com/71652470/136228160-180be191-32df-448b-987b-e9618023834e.png)

![image](https://user-images.githubusercontent.com/71652470/136229468-e2908dd0-0c37-41b5-a415-789abeb4f119.png)

Hero card is displaying as below

![image](https://user-images.githubusercontent.com/71652470/136228308-bf4cd9f3-0173-4166-b547-f42b9c06bb5a.png)

**Comment by compulim** [comment]
@tonyanziano I am sending this back. 🤣

It seems related to the Composer.

Ultimately, it fetched `null` instead of images. So, Web Chat couldn't show any.

You can look at @ashokdevlabs comment above to see.

**Comment by ashokdevlabs** [comment]
Hi @tonyanziano,

I am still facing this issue with Herocards. Attaching the sample solution and screenshots for reference.

![image](https://user-images.githubusercontent.com/71652470/137635479-dd3c9967-bf1d-4a3f-91d3-265cca513058.png)

![image](https://user-images.githubusercontent.com/71652470/137635526-b2e8073a-a3f9-4343-af9f-ffd2635afec2.png

[EmptyTestBot.zip](https://github.com/microsoft/BotFramework-Composer/files/7360381/EmptyTestBot.zip)
)

Could you please suggest me how to fix this issue? Thanks in advance

**Comment by ashokdevlabs** [comment]
@tonyanziano  Is there any update on this issue?

**Comment by Danieladu** [comment]
@ashokdevlabs Sorry for blocking you. It is a bug in Adaptive-Expression library.
There are some particular cases in the comparison of uppercase/lowercase of language Turkish.
reference: https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings#string-comparisons-that-use-the-current-culture
```
For nearly all Latin alphabets, including U.S. English, the character "i" (\u0069) is the lowercase version of the character "I" (\u0049). 
This casing rule quickly becomes the default for someone programming in such a culture. 
However, the Turkish ("tr-TR") alphabet includes an "I with a dot" character "İ" (\u0130), which is the capital version of "i". 
Turkish also includes a lowercase "i without a dot" character, "ı" (\u0131), which capitalizes to "I". 
This behavior occurs in the Azerbaijani ("az") culture as well.
```

The work around is to change all the "Image" to "image" in expression, that suppose to work.

![Screenshot 2021-10-20 140350](https://user-images.githubusercontent.com/7289268/138037178-99dd9311-7196-4257-91fb-889ac33ef596.png)


![image](https://user-images.githubusercontent.com/7289268/138036893-0a0eb71d-c5fc-4b5d-b0e3-545fc54a548c.png)

**Comment by lauren-mills** [comment]
Looks like this workaround solves the customer's immediate issue. Do we have the SDK bug fix tracked separately? If so, I will close this issue.

@Danieladu, @tonyanziano

**Comment by EricDahlvang** [comment]
@lauren-mills yes, the fix has been merged: https://github.com/microsoft/botbuilder-dotnet/pull/5925

closing
