### ISSUE TITLE
Deploy_ZIP_ERROR while publishing bot

### ISSUE THREAD

**Issue by Gupta-Keshav-001378461** [microsoft/BotFramework-Composer#8733]
I am trying to publish a bot from bot composer. But every time I try to publish the bot I get the following error : 

![Screenshot (17)_LI](https://user-images.githubusercontent.com/59747943/136594917-c0be7448-0b4f-4a75-ab27-3732213c8143.jpg)

I have tried to publish on 2.1.1 and 2.1.nightly versions as well I am getting the same error.

**Comment by tonyanziano** [comment]
@natalgar can you take a look at this since you are investigating similar zip deploy issues?
