### ISSUE TITLE
$schema is incorrect for examples

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotFramework-Composer#875]
The current samples point to ../../app.schema which does not exist.  We should make sure it does in order to support tooling and visual studio code.  It should point to the SDK schema, i.e. 
"$schema": "https://raw.githubusercontent.com/microsoft/botbuilder-dotnet/4.Future/schemas/sdk.schema"
Since composer is a private repo, we cannot point to the composer checked-in schema but we could point to the relative schema, i.e.
  "$schema": "../../../Composer/packages/server/schemas/sdk.schema"

**Comment by luhan2017** [comment]
As composer is already a published repro, we can point the schema to 
https://raw.githubusercontent.com/microsoft/BotFramework-Composer/master/Composer/packages/server/schemas/sdk.schema
@cwhitten, @yochay, @hibrenda  let's discuss with the team in our next standup meeting, probably we can make it in R7

**Comment by cwhitten** [comment]
addressed in #875
