### ISSUE TITLE
Custom Language Generation files imported via package are not detected by Composer

### ISSUE THREAD

**Issue by KenO-2147** [microsoft/BotFramework-Composer#8752]
## Describe the bug

I am attempting to import a custom NPM-based Composer package containing dialogs and language generation files, following documentation [here](https://docs.microsoft.com/en-us/composer/how-to-manage-packages?tabs=node#to-use-the-cli-to-manage-packages) and [here](https://github.com/microsoft/BotFramework-Composer/tree/main/extensions/packageManager).

The imported language generation files could not be found when attempting to import the files in Bot Responses, in ``common.lg`` like so: ``[import](MyLGFile.lg)``  The error message is ``L3:0 - L3:16 File not found``.

## Version

Version:  2.1.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Updated (10/26/2021):**

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new package with the ``exported`` folder at root, per doc [1](https://docs.microsoft.com/en-us/composer/how-to-create-packages) and [2](https://github.com/microsoft/BotFramework-Composer/tree/main/extensions/packageManager#build-your-own-packages).
2. Place each custom dialog folder in the ``exported`` folder. Place the custom language generation files, in an ``en-us`` folder, in the ``exported`` folder.
3. Import and install the package to the Composer bot via the Bot Framework CLI, per [docs](https://docs.microsoft.com/en-us/composer/how-to-manage-packages?tabs=node#to-use-the-cli-to-manage-packages):
3a. In the bot directory, run `npm install --save [some package]`.
3b. Run `bf dialog:merge package.json --imports ../dialogs/imported --output ../schemas/sdk`
4. Open the bot in Composer and attempt to import the language generation files in ``common.lg`` in Bot Responses, like so: ``[import](MyLGFile.lg)``
5. You will receive the error message: ``L3:0 - L3:16 File not found``.

## Expected behavior

The imported language generation files should be detected by Composer.

**Comment by lauren-mills** [comment]
@KenO-2147 when you open the bot in Composer after installing the package, can you see your dialog in the Create tab and your LG file in your "Bot Responses" tab?

**Comment by KenO-2147** [comment]
Thanks for the reply. The imported dialog does show up, but the imported language generation files do not (see screenshots below).  My understanding is that if you're creating a custom language generation file, independent of any dialog, you have to add an `[import]` statement to Common before the file appears under Bot Responses.  So I would expect to not see my imported LG file until I attempt to add the `[import]` statement.

<img width="1298" alt="Screen Shot 2021-11-02 at 1 53 37 PM" src="https://user-images.githubusercontent.com/92955005/139950123-d572e9f9-f716-4608-934c-ab488ec3a3df.png">

<img width="1298" alt="Screen Shot 2021-11-02 at 1 53 50 PM" src="https://user-images.githubusercontent.com/92955005/139950140-ba0bc156-c66e-4d21-bc65-686cfafb0d3b.png">

**Comment by lauren-mills** [comment]
Can you try adding the import statement, closing Composer, then reopening and seeing if you still see the error? It may not be refreshing correctly.

**Comment by KenO-2147** [comment]
@lauren-mills Thanks for the reply.  I still see the error if I add the import statement, restart Composer, and reopen the project.

**Comment by lauren-mills** [comment]
Any chance you could remove your keys and attach a .zip of the project?

**Comment by KenO-2147** [comment]
@lauren-mills The example project and package are attached, thanks for taking a look.

[ExampleBot.zip](https://github.com/microsoft/BotFramework-Composer/files/7523573/ExampleBot.zip)
[example-package.zip](https://github.com/microsoft/BotFramework-Composer/files/7523574/example-package.zip)

**Comment by lauren-mills** [comment]
@KenO-2147, I think I may have figured it out. For your individual LG file, it needs to be in a folder named "language-generation" inside your package. Then it will show up in the Bot Responses tab and you can import it into other files without errors.

![image](https://user-images.githubusercontent.com/27976702/141827600-e44ecb20-2930-40ee-937d-eacc1664ef49.png)

**Comment by KenO-2147** [comment]
Wonderful, that works for me.  Thank you for the help, it is much appreciated.
