### ISSUE TITLE
advanced-bot-framework-composer-example1 Problem with json

### ISSUE THREAD

**Issue by TheTrees123** [microsoft/BotFramework-Composer#8758]
## Describe the bug
When I tried the first example of the bot framework composer [advanced-bot-framework-composer-example1](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example1), I was not able to add the json code without error.

JSON code:
`# Chicken()
-Chicken`

OR JSON code
`import](common.lg) # Chicken() -Chicken`

Error always on first sign: _Expected a JSON object, array or literal. json(0)_

## Version
v.2.1.1

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

[advanced-bot-framework-composer-example1](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer-example1)

## Expected behavior
It should work without a problem/error.

## Screenshots
![BotFrameworkComposer_Error](https://user-images.githubusercontent.com/93117930/138652781-2bb185a8-307c-437e-b453-29f9670506e1.jpg)

**Comment by johnataylor** [comment]
@stevkan any update on this?

**Comment by TheTrees123** [comment]
Is there a solution yet?

**Comment by stevkan** [comment]
@TheTrees123, thank you for your patience. I am looking at the example above and hope to have a response before the end of day, today.

**Comment by stevkan** [comment]
@TheTrees123, @tonyanziano

Unfortunately, I was not able to repro the issue. I went thru the steps as described and was able to create, publish, and run without any errors reported.

**Comment by tonyanziano** [comment]
@TheTrees123 can you try to just create an Empty bot, then in the Greeting trigger, add a single "Send Response" node that executes a template?

Ex:

![image](https://user-images.githubusercontent.com/3452012/145495495-19cd7c24-deb0-4440-b796-ec279a8c156b.png)

![image](https://user-images.githubusercontent.com/3452012/145495559-569a551d-dbc2-47a5-ab89-e7d051aa36d0.png)

![image](https://user-images.githubusercontent.com/3452012/145495580-bb4915d7-0b6e-4837-adbb-ddedd1b6d4c0.png)

**Comment by tracyboehrer** [comment]
@TheTrees123 Did Tonys suggestion help?

**Comment by TheTrees123** [comment]
When I opened the Bot Framework Composer this time I was asked to install **Node.js** and **.Net Core SDK.** This solved the problem.
