### ISSUE TITLE
Error calling npm to fetch template

### ISSUE THREAD

**Issue by Gurunarendra46** [microsoft/BotFramework-Composer#8764]
error is showing like 
"Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with ENOENT: npm root -g --prefix C:\Users\azureuser\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error spawnSync cmd.exe ENOENT"

**Comment by stevkan** [comment]
Closing as duplicate.
