### ISSUE TITLE
Bot Composer: Refer to app service settings for application insights

### ISSUE THREAD

**Issue by Erry91** [microsoft/BotFramework-Composer#8765]
I have a bot developed with Composer (v. 2.1.1) tht I have deployed in two different resource groups. 
I want to log its activities and messages with Application Insights, and I have configured for this reason my app service with a global configuration setting:

`settings:applicationInsights:InstrumentationKey = <my-instrumentation-key>`
`settings:applicationInsights:connectionString = <my-connection-string>`

**Note**: I have other global settings for QnA and LUIS resources for example and they work fine with this setup (see screen below).
![image](https://user-images.githubusercontent.com/6703817/139275106-d4c348e8-2bf6-48fd-84f0-7ab038b86bd5.png)

**Problem**: application insights doesn't log with this configuration, and so far the only option that seems to work is to hardcode the connection string into the appsettings.json file of the bot, like so:
![image](https://user-images.githubusercontent.com/6703817/139274618-058c8afe-7a43-40f6-a128-7d3600710cc6.png)

**Question/Issue**: is it possible to insert in this appsetting file a reference to my global settings, or is it possible to just override whatever I write in here? It is annoying to have this value hardcoded in the appsettings since I would have to move it from one environment to the other if I want to be sure to log into Application Insights for each environment.

Thank you in advance.

**Comment by dmvtech** [comment]
Sorry. Use `runtimesettings:telemetry:options:connectionString`. I just tested it and it worked for me.

**Comment by Erry91** [comment]
@dmvtech Thank you I can confirm that works for me too. I can also use this scope hierarchy to override other runtime settings, may there be need for it.
