### ISSUE TITLE
Unable to sign in to Azure: Account Switch Detected

### ISSUE THREAD

**Issue by dmcguire12** [microsoft/BotFramework-Composer#8766]
## Describe the bug

When I try signing into my Azure account through my University email account, I go through all the regular steps of signing in, only to receive an error saying "Account Switch Detected" and "We were unable to verify your account. Please sign in for ___ or cancel and try a different account.". A box also pops up on the right saying "Sign in failed: Failed to fetch"

## Version

2.1.1

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Bot Framework Composer
2. Click on profile in top right
3. 'Sign in to your Azure account'
4. Go through the process of signing in

## Expected behavior

To successfully sign in to Bot Composer with my Microsoft account.

## Additional context

The same credentials work fine for logging into Outlook, Word, etc.

**Comment by msomanathan** [comment]
@benbrown - Looks like a student account is unable to sign in to composer using their school account. Is this an issue with composer not accepting certain account types, or, would this be an issue with their school tenant's configuration settings?

**Comment by msomanathan** [comment]
@dmcguire12 - you might be running into the issue here: https://github.com/microsoft/BotFramework-Composer/issues/8711.

Could you please try to upgrade to the most recent version and try again? Thanks!

**Comment by dmcguire12** [comment]
It was an issue on my end with the university email. I was supposed to use an alternate address. Thanks for looking into this though!

**Comment by benbrown** [comment]
Thank you for following up @dmcguire12
