### ISSUE TITLE
Create new Empty bot - .NET SDK installation is required which has already been installed

### ISSUE THREAD

**Issue by osedakov-amc** [microsoft/BotFramework-Composer#8770]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows 10
- [ ] Ubuntu

## Screenshots

![image](https://user-images.githubusercontent.com/46485395/140031992-902e3a22-d9b8-4768-b1b6-921852b80441.png)

**Comment by lauren-mills** [comment]
Hi @osedakov-amc, can you provide your Composer version? Also, if you are on an x64 machine, can you try installing the x64 version of the .NET Core SDK [here](https://dotnet.microsoft.com/download/visual-studio-sdks)?

**Comment by dmvtech** [comment]
@osedakov-amc Can you also share the output of the following commands:

1. `dotnet --info`
2. `dotnet nuget list source`

**Comment by osedakov-amc** [comment]
@lauren-mills @dmvtech Yes, sure. After uninstalling old SDK versions this issue becomes to an error. It appears every time when I try to create a new empty bot
![image](https://user-images.githubusercontent.com/46485395/140276494-544dac81-a9e3-4998-9cfc-136794cf25d3.png)
![image](https://user-images.githubusercontent.com/46485395/140276651-79096721-3343-4dc3-8c93-0a437751ba86.png)
![image](https://user-images.githubusercontent.com/46485395/140276767-48b114d5-eff7-4dfd-bd5c-de216949ae0d.png)
![image](https://user-images.githubusercontent.com/46485395/140276868-22796ce0-e000-4422-b862-e599ca5580d5.png)

**Comment by dmvtech** [comment]
HI @osedakov-amc If you run `dotnet build` from the bot's project directory, does it throw a more useful error?

**Comment by dmvtech** [comment]
Closing due to lack of response. If you are still experiencing the issue and need assistance, please comment or reopen.
