### ISSUE TITLE
QnA Maker: How to not source control KB content?

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#8774]
**Scenario**
I created a QnA Service and add a KB for it.
I added the KB through Composer to my Skill bot project.
Then Here is what gets generated.

As you can see below, the entire KB content is imported into file content under the source folder.
Are the intention here is to source control the KB content, for security and privacy concerns, we're not supposed to have KB content in source code, instead we would like to manage it in QnA Maker Portal. 

**Question: What's the right way to use QnA Maker without having the actual KB content in source control?**
I understand LUIS is ok to be source controlled as it's just utterance samples and language patterns, but KB has the actual content which is customer data, we cannot make it into source code.

![image](https://user-images.githubusercontent.com/44714043/140440163-5293f382-d3ef-4c49-b1eb-4a601568cee9.png)

**Comment by dawwa** [comment]
Ping.

**Comment by dmvtech** [comment]
Hi @dawwa 

> Question: What's the right way to use QnA Maker without having the actual KB content in source control?

With declarative/Composer bots; there is a fair amount of content/data that is on the file system. Not just QnA KB, but LG and dialogs as well. It is part of the design. There is not a out-of-box way to accomplish what you are wanting other than not authoring QnA from Composer but just using the QnA _action_. 

One workaround might be to re-publish your bot with the `.qna` file removed. Once the bot and KB are initially published, you would need to remove the .qna file, republish using .zip deployment such as specified [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp).

**Comment by dmvtech** [comment]
Per discussion with @dawwa; closing.
