### ISSUE TITLE
QnA Maker: What is this guid in the generated qnamaker.settings.composer.westus.json?

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#8775]
There is this json file gets generated if the bot is with KB connnected.
e.g., In MyComposerSkill.csproj under this path, $\MyComposerSkill\generated\qnamaker.settings.composer.westus.json

**Question**
I've verified it's not my KB Id, not the QnA maker subscription Id, not the endpoint key.
So I'm confused what Id this is, and whether I need care about it.

![image](https://user-images.githubusercontent.com/44714043/140440354-d15cb502-1e4d-4f86-840d-76965a0eab74.png)

**Comment by dawwa** [comment]
ping.

**Comment by dmvtech** [comment]
Hello @dawwa 

There are two routes for using QnA in Composer.

---

One is to use an action (not a _dialog_) to make an specific/explicit call to QnA with an action. This is described in the [Add QnA to your bot](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot?tabs=v2x) article. This route does not allow any authoring or two-way connectivity (again; just a way to query QnA from an action). There is no publishing available with this route.

The other is to author QnA from Composer and utilize the QnA triggers/recognizers/dialogs. This allows and **requires** authoring from Composer, as well as recognition of QnA intents and dialog triggers. This is described in the article [Create a QnA Maker knowledge base.](https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb?tabs=v2x) With this, publishing is required and does happen.

---

When doing the latter, and Composing your KB from QnA, this ID *is* the ID of the KB. But not the one of your _existing_ KB. It is of the new KB that is created **by** Composer.

**Comment by dmvtech** [comment]
Per discussion with @dawwa; closing.
