### ISSUE TITLE
Failing pipeline buildAndDeployDotNetWebApp.yaml stage "Deploy Azure Web App"

### ISSUE THREAD

**Issue by dabedin** [microsoft/BotFramework-Composer#8780]
## Describe the bug

Encountering error in the Azure DevOps pipeline _\yaml\templates\buildAndDeployDotNetWebApp.yaml_ at the stage _displayName: "Deploy Azure Web App: ${{ parameters.webAppName }}".
with the message "##[error]Error: No package found with specified pattern: /home/vsts/work/1/s/output/zipDeploy/dbsilvidetest.zip<br/>Check if the package mentioned in the task is published as an artifact in the build or a previous stage and downloaded in the current job."
```
Full output:
Starting: Deploy Azure Web App: dbsilvidetest
==============================================================================
Task         : Azure Web App
Description  : Deploy an Azure Web App for Linux or Windows
Version      : 1.187.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azurewebapptroubleshooting
==============================================================================
Got service connection details for Azure App Service:'dbsilvidetest'
##[error]Error: No package found with specified pattern: /home/vsts/work/1/s/output/zipDeploy/dbsilvidetest.zip<br/>Check if the package mentioned in the task is published as an artifact in the build or a previous stage and downloaded in the current job.
Finishing: Deploy Azure Web App: dbsilvidetest
```

## Version
Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

See above and below description

## Expected behavior

FWIW, given that the previous step (and all the other steps) completed successfully I was not expecting issue in the deployment to Azure.  Here the output from _Publish build artifacts_ step.
```
Starting: Publish build artifacts
==============================================================================
Task         : Publish build artifacts
Description  : Publish build artifacts to Azure Pipelines or a Windows file share
Version      : 1.192.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-build-artifacts
==============================================================================
Async Command Start: Upload Artifact
Uploading 1 files
File upload succeed.
Upload '/home/vsts/work/1/s/output/zipDeploy' to file container: '#/15136736/BuildArtifacts-44'
Associated artifact 17 with build 44
Async Command End: Upload Artifact
Finishing: Publish build artifacts
```

## Additional context

I retrieve the sample pipilines from https://github.com/gabog/ComposerCICDSamples, only change applied I commented the "Publish QnA Maker KBs" in _build\yaml\templates\buildAndDeployModels.yaml_.
The bot has already been successfully published from Bot Composer to Azure.

**Comment by saikumaru** [comment]
Any update on this please?
I still couldn't find a solid document on build and release pipeline for composer built bots.

@dabedin please can you let us update.

**Comment by erquirogasw** [comment]
Hi @dabedin , we reviewed this issue and found that the sample was moved to the [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples/blob/main/composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSample/build/yaml/buildAndDeploy.yaml) repo.
We were able to configure and run the pipeline with no issues. Also, the deployed webApp worked as expected.
@tracyboehrer , we think this issue can be closed.
