### ISSUE TITLE
Issue In Publish After Migrating Bot To 2.1.1 Composer Version

### ISSUE THREAD

**Issue by UmaPrelude** [microsoft/BotFramework-Composer#8783]
Hi,

We developed a bot in composer 1.3.1 version. We migrated it to 2.1.1 bot project.
Included a middleware, we are able to run the bot in emulator.
When we are trying to publish the bot, we get the following error. If we get some clue it will help.
![image](https://user-images.githubusercontent.com/65938026/140756747-7a99e7f4-25d2-4ae1-9cee-18442dc1b47e.png)

**Comment by UmaPrelude** [comment]
I used different project for middleware and after that I am to publish.
Closing this issue. But it would be great if we get a proper error message for various scenarios like this.

**Comment by ryanlengel** [comment]
Hey @UmaPrelude, glad you got it working! If I'd have a guess it may have been a mismatch with SDK versions (going from 1.3.1 to 2.1.1).  Thank you for the feedback - we'll have our project planning team consider this for a future release.
