### ISSUE TITLE
Package Manager - Unable to Install any package

### ISSUE THREAD

**Issue by prajwal-ainapur** [microsoft/BotFramework-Composer#8797]
Followed the weather bot tutorial and built the whole bot. When i tried to install help and cancel package, am not able to install any package from the manager. The following is the error:

`Could not load component list:Error Cannot create property '$bundled' on string '<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style>`

How can this be fixed?

**Comment by anishprasad01** [comment]
Hi @prajwal-ainapur,

Could you please provide me some more information about your setup and your project so that we can try to figure out what's going on?

Here's a list of things I'd like to know to start out with:

- What runtime are you using (.NET or Node)?
- What version of said runtime are you using?
- What version of Composer are you using?
- How are you launching Composer?
- What are OS and CPU are you running?
- Did you make any modifications to the weather bot, or did you follow the tutorial exactly?
- Does your setup meet all of the Composer system requirements on the following pages?
  - https://github.com/microsoft/BotFramework-Composer/blob/main/docs/supported-os.md
  - https://docs.microsoft.com/en-us/composer/install-composer
- Is there anything else unique about your setup or system configuration that it might be helpful to know?

**Comment by prajwal-ainapur** [comment]
Hi @anishprasad01,

Please find the response below...

What runtime are you using (.NET or Node)?
-> Using .NET
What version of said runtime are you using?
-> .NET core runtime 3.1.21
What version of Composer are you using?
-> I am using composer v2.1.1
How are you launching Composer?
-> On my local machine
What are OS and CPU are you running?
-> Windows 10 Enterprise 21H1 and Intel 8thGen i5
Did you make any modifications to the weather bot, or did you follow the tutorial exactly?
-> Followed the exact steps and even installed the versions mentioned there
Does your setup meet all of the Composer system requirements on the following pages?
-> Yes, all system requirements are met
Is there anything else unique about your setup or system configuration that it might be helpful to know?
-> This is an office laptop. So similar restrictions that all IT companies provide

**Comment by anishprasad01** [comment]
The only other thing I can think of is potentially an issue related to your company's firewall or some other type of content blocker that might prevent you from accessing the servers offering the needed content. I attempted to repro on my Intel Windows 10 machine with the same .NET and Composer versions and had no issues. 

Each enterprise will have different standards regarding what they might block on their employees' computers. I suggest you take a look and potentially check with your IT department. Are you by any chance able to attempt this on a personal machine? If it works on your personal machine, then we can be even more certain that some sort of content blocking is occurring.

**Comment by prajwal-ainapur** [comment]
Tried installing packages through different network. Didn't work. One weird observation. json-schema.org is opening up on chrome browser but not edge browser. I presume, if i can access json-schema, the package install should run smoothly. What could be the reason for difference in access behavior?

**Comment by anishprasad01** [comment]
It's hard to say, but I suspect a browser configuration issue might be at play. I am able to open json-schema.org on Edge. Let's see what happens on your personal system.

**Comment by prajwal-ainapur** [comment]
Hi @anishprasad01,

Tried same setup on my personal system. It's working as expected. Seems to be some network/firewall issue on office laptop. Can we have some sort of work around for this dependency maybe in the form of downloading the schema during composer installation itself or something of that sort?

**Comment by anishprasad01** [comment]
In terms of workarounds, I can think of two straightforward options.

1. You can copy the bot to your personal machine, install the packages, and move the bot back to your work device.
2. You can download the NuGet package directly from the package repository online, and add the files to the bot's folder manually. For example, here is the page for the [HelpAndCancel](https://www.nuget.org/packages/Microsoft.Bot.Components.HelpAndCancel/) package.

The steps to do so would be something along these lines:

1. Download the package
2. Use a tool like 7zip or similar to extract the archive
3. Navigate to the `dialogs` folder in your bot. It should be somewhere like `<Your Bot Name> -> <Your Bot Name> -> dialogs`
4. Create a folder named `imported`, if it doesn't already exist.
5. Within `imported`, create a folder with the precise name of the package, making sure to include `.` and capitalization as needed. You can copy this name directly off the NuGet download page. For example, `Microsoft.Bot.Components.HelpAndCancel`.
6. Within the directory you extracted in step 2, navigate to the `exported` directory, and copy its contents to the new folder you created in step 5.
7. Open Composer and load your bot, the new dialogs should be there.

Note that adding packages manually without the use of the Package Manager is **not a seamless process**. All of the links and connections that the manager might create for you won't necessarily be made, and if your system is missing any dependencies, you'll have to acquire them manually. Help and Cancel is also a pretty simple package that adds some basic dialogs. A more complex package might not be quite so easy to add.

Your best bet might be to either try option one, or contact your IT department and see if you can figure out what aspect of your office computer's setup is preventing you from installing packages. Are any of your colleagues able to install packages?

**Comment by prajwal-ainapur** [comment]
Thank you @anishprasad01 for your detailed inputs. Closing this issue as alternate solution is working.
