### ISSUE TITLE
"\"\" is not a valid LUIS application id."

### ISSUE THREAD

**Issue by owenpww** [microsoft/BotFramework-Composer#8799]
## Describe the bug
For any and all intents, bot responds with "\"\" is not a valid LUIS application id." or  “” is not a valid LUIS application id.
## Version
Release: 2.1.1 (from Bot Framework Composer in Settings > About)

## Browser
- [ ] Electron distribution
- [ /] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ /] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty bot in composer
2. Set bot's Language Understanding to Default (LUIS)
3. Link Unknown Intent to QnA maker knowledge base made on QnA Maker Portal
4. Create another intent linked to a new dialog (any intent and dialog)
5. Create a new publishing profile and publish (at this point bot works both locally and in Test in Web Chat on Azure Portal)
6. Create CI/CD pipeline using steps in https://docs.microsoft.com/en-us/composer/how-to-cicd
7. Commit composer bot to Azure repo linked to pipeline.
8. Run pipeline on latest commit.
9. Go to Test in Web Chat for your bot on the Azure Portal
10. See error when any message is sent to the bot

## Expected behavior
Bot to work, recognizing created intents and triggering appropriate dialogs, similar to when it runs locally and when published using the publishing profiles and publish button on Composer.
## Screenshots
![image](https://user-images.githubusercontent.com/93670080/142239658-144b7928-aa7d-46d6-b131-84f1ea1f74de.png)
![image](https://user-images.githubusercontent.com/93670080/142238671-6d3db0d8-71ea-4500-83fd-e40d7dd6f8e7.png)

## Additional context
The two images above are from two different bots. I thus am able to replicate the error I got on my first bot (first picture) on the second bot. The first bot is the actual bot I want to get running. The second bot is merely to test whether I can replicate the bot and if not, what differences there are between the bots to help me debug.

Both bots work fine on local machine or when publishing using the Publish button in composer (manual publishing). What I want to achieve is a CI/CD pipeline to publish the bot on every commit to particular branches. The pipelines themselves show no errors and always say successful. Additionally, when I look at the logs from the Application Insights provisioned to the bot, it does not record these "not a valid LUIS app ID" as errors but as 200 success when in fact an error should have been logged to Insights (I created an Error occurred intent for the first bot that emits a Telemetry event then sends a response to user telling them an error occurred (see response in first image). Whenever an error occurs, it only sends me the response but does not log a telemetry event like it did for previous errors I encountered.).

**Comment by owenpww** [comment]
It seems like the problem is in the pipeline since running the bot locally and publishing from Composer work just fine. I'm not sure if this is the source of the issue because I can't seem to find any documentation or code online showing where you would add the LUIS app ID in the CI/CD pipeline but in the yaml templates included in the above Azure documentation on creating pipelines for your Azure Bot, the LUIS app ID is accepted as a parameter in the main yaml for the pipeline but it's not passed to any of the templates so maybe it's not being used at all?

![image](https://user-images.githubusercontent.com/93670080/142264717-3fab02e9-9d32-4edf-a3f8-5484be081d3c.png)
![image](https://user-images.githubusercontent.com/93670080/142264269-868ea96e-1e47-4abc-9fd5-efc7eb2dbecc.png)

**Comment by dmvtech** [comment]
@owenpww Thank you for all the info. I'm not sure what is happening but I will attempt to reproduce and investigate.

**Comment by benbrown** [comment]
@owenpww You are likely creating a different set of LUIS applications during the CI/CD publishing process than would be used when testing and developing locally. These IDs get written to a generated/ folder during that process, and should be part of the final deployed assets. Can you confirm that this is the case?

Have you configured the prediction resource in those apps? (see below)
https://docs.microsoft.com/en-us/composer/how-to-cicd#configure-your-luis-prediction-resources-first-time-only

**Comment by dmvtech** [comment]
hi @owenpww Can you confirm you configured the prediction resources per the documentation linked above? Are you still having the issue?

**Comment by owenpww** [comment]
Hi @dmvtech I fixed the issue by creating app settings for the luis-related settings in the app service page of my bot. Thank you!
