### ISSUE TITLE
Choice prompt's choice cannot support multi languages

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#880]
Currently choice prompt only expect string as options. In code, it is easy to be localized, but in composer, there is no way to set a localized string as choice option.
![image](https://user-images.githubusercontent.com/16643193/65018189-10e1de00-d95b-11e9-9d2d-0e9ffbf63383.png)

**Comment by vishwacsena** [comment]
Tracked via https://github.com/microsoft/botbuilder-dotnet/issues/2387
