### ISSUE TITLE
Custom Actions Documentation is available only in C#

### ISSUE THREAD

**Issue by jamalsia** [microsoft/BotFramework-Composer#8803]
## Describe the bug

Custom actions HTML documentation is available only for C# but not for Javascript as it used to in 1.4
## Version
Testing

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

NA

## OS

NA

## To Reproduce

1. Go to https://docs.microsoft.com/en-gb/composer/how-to-create-custom-actions
2. documentation is only applicable to C#

## Expected behavior

Documentation applicable to JavaScript like in 1.4
## Screenshots
![image](https://user-images.githubusercontent.com/25248608/142465901-1b179e78-a579-4d8b-94cd-6bd5cf2b3569.png)

**Comment by johnataylor** [comment]
The Composer runtime (aka Adaptive Dialogs) is only available in C# and therefore the documentation is only available for the C# release. "Custom Actions" are part of this runtime.

There have been preview JavaScript implementations of this stack, however, at the current time there is no plan to take these to a production release state.
