### ISSUE TITLE
No Greeting No Response after Publish

### ISSUE THREAD

**Issue by mukdenchild** [microsoft/BotFramework-Composer#8808]
Suddenly started from yesterday, Bot had no response no greeting on MS Team and Azure web chat test after publish in composer. The publish was success without error msg. Local tests on Composer and emulator were fine. Reverted code to previous versions (fully validated on Team and web chat only 2 days ago) and published again, no luck, still no greeting no response no error.
Anybody had similar experience? Did MS make some bad updates on Azure bot service yesterday?

**Comment by dmvtech** [comment]
@mukdenchild I'm investigating to see if there are any known issues on the service. Can you confirm you are still experiencing the issue?

As a side note; welcome messages should only ever work once per user, per bot. But they should work every time in Test in Web Chat.

**Comment by mukdenchild** [comment]
@dmvtech Tested once again today and still had the issue. No error msg during deploy. After deploy, no response, and the bot web app url has HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure. I have spent hours to rebuild my bot all the way from an empty bot template, and the rebuilt one is working.

**Comment by mukdenchild** [comment]
@dmvtech Tested once again today and still had the issue. No error msg during deploy. After deploy, no response, and the bot web app url has HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure. I have spent hours to rebuild my bot all the way from an empty bot template, and the rebuilt one is working.

**Comment by dmvtech** [comment]
@mukdenchild 

> After deploy, no response, and the bot web app url has HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure

To clarify; you're talking about the `wwwroot\default.htm` page, or the /api/messages endpoint? If the former, this points more to the application itself, and not the Bot Service. But that is interesting that it suddenly happened. 

Are there any issues showing up in the Channels blade for Teams or WebChat?

It's really strange that there are no errors publishing, but still not working either. You _could_ try to publish via Visual Studio (select option to remove additional/extraneous files) or [az cli zip deployment](https://docs.microsoft.com/en-us/azure/bot-service/powershell/bot-builder-powershell-quickstart?view=azure-bot-service-4.0). Alternatively, you could try removing the content from the azure portal (App Service console, advanced tools, etc), then republishing; I'm curious to see if that might clear it up.

**Comment by mukdenchild** [comment]
The 502.5 is on web app default html page. The bot runs fine on emulator and composer, and no error showing up on web chat and team, just no response. Also I manually cleaned up the app container using console and republished but didn't work. I use VS to build the custom action class and unit tests but have only published thru composer so far. I will try to publish thru VS when back to office and let you know. Thank you.

**Comment by mukdenchild** [comment]
Updates:
Downgraded Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime, Version 4.15.0 to 4.14.1 on both bot main project and library class. Deployed again. This solved the issue. 
Somehow the Azure web app isn't very compatible with 4.15.0.

**Comment by dmvtech** [comment]
Thank you @mukdenchild for the info/findings. I'll be looking into this further.

What version of Composer was used to create the bot and what version was Composer when you published the bot and the issue occurred?

**Comment by gabog** [comment]
Hi @mukdenchild, can answer @dmvtech question so he can try to reproduce the issue?

**Comment by mukdenchild** [comment]
V2.1.1 only.
