### ISSUE TITLE
Custom Action: const value not set unless app refresh

### ISSUE THREAD

**Issue by MatteoMUni** [microsoft/BotFramework-Composer#8809]
## Describe the bug
Consider a `.schema` like the one below (will produce something like Choice Input's `choices`).

```json
{
  "$schema": "https://schemas.botframework.com/schemas/component/v1.0/component.schema",
  "$role": "implements(Microsoft.IDialog)",
  "title": "My Custom Action",
  "type": "object",
  "properties": {
    "arg1": {
      "title": "Arg1",
      "additionalProperties": true,
      "oneOf": [
        {
          "type": "object",
          "title": "first option",
          "properties": {
            "type": {
              "const": "first-option"
            },
            "foo": {
              "$ref": "schema:#/definitions/stringExpression",
              "title": "Foo",
              "description": "Description"
            },
            "bar": {
              "$ref": "schema:#/definitions/stringExpression",
              "title": "Bar",
              "description": "Description"
            }
          }
        },
        {
          "type": "object",
          "title": "second option",
          "properties": {
            "type": {
              "const": "second option"
            },
            "baz": {
              "$ref": "schema:#/definitions/stringExpression",
              "title": "Baz",
              "description": "Description"
            }
          }
        }
      ]
    }
  }
}
```

and associated `.uischema`:
```json
{
  "$schema": "https://schemas.botframework.com/schemas/ui/v1.0/ui.schema",
  "form": {
    "properties": {
      "arg1": {
        "hidden": [
          "type"
        ]
      }
    }
  }
}
```

**If you pick either of the two options in `oneOf` array (`first option` or `second option`) after a dialog using the custom action has been loaded, constant property `type` will not be set in associated `.dialog` file.**

## Version
2.1.1
Tested also in main (latest commit when writing this issue: `f426bba`)

## Browser
- [x] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty bot
2. Create a custom action using the `.schema` and `.uischema` above
3. Use the custom action in a dialog
4. Change from `first option` to `second option` in `arg1` selector (near property label in composer)
5. Check generated `.dialog`, you will have
   ```json
   "$kind": "MyCustomAction",
   "$designer": {
     "id": "ABC123"
   }
   ```
6. On page refresh, if you select the custom action (triggering focus event) will also be set:
   ```json
   "arg1": {
     "type": "first-option"
   }
   ```

## Expected behavior
`type` should be set every time an option from `oneOf` array is selected

## Screenshots
Not applicable

## Additional context
Not applicable

## Possible (quick) fix
Just add `value` to array of dependencies of `useEffect` [here](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/adaptive-form/src/components/SchemaField.tsx#L66)
To check, retake the steps in **To Reproduce**

**Comment by benbrown** [comment]
@MatteoMUni we will try to reproduce this. Have you seen this behavior with any other field or field type?

**Comment by MatteoMUni** [comment]
Nope
I tried with `stringExpression`, `objectExpression`, etc. but are all types that require user's input and thus, field value is updated immediately

**Comment by benbrown** [comment]
@a-b-r-o-w-n Is it necessary to set a default value for this type of field?

**Comment by a-b-r-o-w-n** [comment]
@MatteoMUni your proposed fix seems reasonable. Can you submit a PR?

**Comment by dmvtech** [comment]
Hi @MatteoMUni Are you able to submit a pull request for this?

**Comment by MatteoMUni** [comment]
Yes, I will ASAP

**Comment by tdurnford** [comment]
@MatteoMUni Have you been able to open PR yet?

**Comment by MatteoMUni** [comment]
@tdurnford @dmvtech @a-b-r-o-w-n 
Just opened with another account
