### ISSUE TITLE
Custom Actions: ability to differentiate between different objects in oneOf array

### ISSUE THREAD

**Issue by MatteoMeil** [microsoft/BotFramework-Composer#8810]
## Is your feature request related to a problem? Please describe.
Consider a schema like this:
```json
{
  "$schema": "https://schemas.botframework.com/schemas/component/v1.0/component.schema",
  "$role": "implements(Microsoft.IDialog)",
  "title": "My Custom Action",
  "type": "object",
  "properties": {
    "arg1": {
      "title": "Arg1",
      "additionalProperties": true,
      "oneOf": [
        {
          "type": "object",
          "title": "first option",
          "properties": {
            "$$type": {
              "const": "first-option"
            },
            "foo": {
              "$ref": "schema:#/definitions/stringExpression",
              "title": "Foo",
              "description": "Description"
            },
            "bar": {
              "$ref": "schema:#/definitions/stringExpression",
              "title": "Bar",
              "description": "Description"
            }
          }
        },
        {
          "type": "object",
          "title": "second option",
          "properties": {
            "$$type": {
              "const": "second option"
            },
            "baz": {
              "$ref": "schema:#/definitions/stringExpression",
              "title": "Baz",
              "description": "Description"
            }
          }
        }
      ]
    }
  }
}

```
When `second option` is picked from `oneOf` array, Composer won't recognize it the next time you edit custom action's properties, presenting every time the first element in `oneOf` array, namely `first option`.

## Describe the solution you'd like
To overcome this problem, I suggest to discriminate between different options using `$$type` property defined in the schema and treat it as a hidden field.
This is also consistent with [Components' JSON schema definition](https://schemas.botframework.com/schemas/component/v1.0/component.schema) and can be implemented with little effort:
You can just add the following code [here](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/adaptive-form/src/components/fields/OneOfField/utils.ts#L146)
```typescript
if (valueType === 'object' && value?.$$type) {
  return (
    options.find((o) => {
      const $$type = o.data.schema.properties.$$type;
      return $$type.const === value.$$type || $$type.const === value.$$type;
    }) || options[0]
  );
}
```
and change the condition [here](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/adaptive-form/src/utils/getOrderedProperties.ts#L80) from:
```typescript
!orderedFieldSet.has(p) && !p.startsWith('$')
```
to
```typescript
!orderedFieldSet.has(p) && (!p.startsWith('$') || p === '$$type')
```

## Describe alternatives you've considered
Not applicable

## Additional context
Reference to issue #8809 because it's a similar scenario and requires it to be closed before addressing this feature request

**Comment by mrivera-ms** [comment]
Hello @MatteoMeil and thank you for engaging with the Composer project. We'll take this issue as a feature request and add it to the backlog for prioritization. We do not have an ETA at this time for when this feature will be available.
