### ISSUE TITLE
Not able to install Microsoft.Bot.Components.HelpAndCancel package in Bot framework composer v2.1.1.

### ISSUE THREAD

**Issue by skcodesingit** [microsoft/BotFramework-Composer#8811]
Not able to install Microsoft.Bot.Components.HelpAndCancel package in Bot framework composer v2.1.1. Getting below error

A problem occured during the install of this Component: Error Cannot create property '$bundled' on string '<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src="http://182.79.218.34:8080/webadmin/deny/index.php?dpid=15&dpruleid=11&cat=107&dplanguage=-&url=http%3a%2f%2f185%2e199%2e110%2e153%2fdraft%2d07%2fschema" width="100%" height="100%" frameborder=0></iframe>' *** Could not merge components ***

**Comment by anishprasad01** [comment]
Hi @skcodesingit,

There is already an [open issue](https://github.com/microsoft/BotFramework-Composer/issues/8797) regarding this problem. Could I ask that you contribute to the discussion on that thread by answering the same questions I asked of the user who posed the question?

I am closing this issue in favor of the existing thread.
