### ISSUE TITLE
Send File/Image type attachment from user to bot on Teams group chat through Composer

### ISSUE THREAD

**Issue by SwetalinaGitHub** [microsoft/BotFramework-Composer#8812]
We are trying to upload attachment from user to bot developed using bot composer. While trying to read the content url of the attachment uploaded through teams group chat, we do not get any content url.  The content url appears blank. 
Kindly suggest.
Below is the snippet :
{
"contentType": "text/html",
"contentUrl": null,
"content": "
"<img" "itemscope=\"png\"",
"src=\"https://us-api.asm.skype.com/v1/objects/0-eus-d7-6aaf03b8f4c12140b9d0d5ee35522c33/views/imgo\"" "alt=\"image\"",
"itemtype=\"http://schema.skype.com/AMSImage\"" "width=\"444.44444444444446\"",
"height=\"250\"" "id=\"x_0-eus-d7-6aaf03b8f4c12140b9d0d5ee35522c33\"",
"itemid=\"0-eus-d7-6aaf03b8f4c12140b9d0d5ee35522c33\"" "style=\"vertical-align:bottom\">",
", " "name\": null, \"thumbnailUrl\": null } ] }"
}

**Comment by stevkan** [comment]
@SwetalinaGitHub, unfortunately I am unable to repro the issue you are encountering. Are you able to provide details on how you setup the attachment file input in your dialog (properties you filled out, etc.) or a copy of your bot that I can test against?

**Comment by SwetalinaGitHub** [comment]
@stevkan Below is the screenshot of the dialog in composer. Also sharing the screenshot of object files while testing the bot through personal scope and group chat scope respectively. 
Through the same bot composer solution, image upload is working properly and we get the object of the image. While it does not work in the group scope.
<img width="906" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/37922616/142978979-26846a8e-1b55-4a78-ac4e-1ae7a6ffb91b.png">
<img width="957" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/37922616/142978987-5d8ff678-ab63-468b-8e50-61a154b469c5.png">
<img width="284" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/37922616/142978989-8fd78b3d-7bf6-467c-b121-41cd42c5a2ca.png">

**Comment by stevkan** [comment]
@SwetalinaGitHub, thank you for your patience. I am still unable to repro the issue.

Can you tell me what version of Composer you are running?
Is this a C# or JS build for your bot?
And, the image you are attempting to send, what is the size of the image file?
Are any other errors reported in Composer either under Problems or Output?

**Comment by shrutinehra** [comment]
Even I am facing the same issue. Sometimes content URL is blank in the teams and sometimes it works fine. 
I am using bot composer 2.0.0. (Windows OS) , C#, I tried pdf, word document but was not able to find the pattern when it's failing and when it's passing. 

The only thing for sure is when a word document has "+" in the name it's failing all the time but without it also it fails sometimes.

![image](https://user-images.githubusercontent.com/10381482/146041696-f2c90f38-9aa7-4268-87a4-bbdb3bb070ab.png)

![image](https://user-images.githubusercontent.com/10381482/146041753-72dadd55-7daa-41ff-aa08-d24e4637e4db.png)

**Comment by shrutinehra** [comment]
@stevkan Were you able to reproduce the issue?

**Comment by msomanathan** [comment]
@stevkan Could you please provide an update to this issue?

**Comment by stevkan** [comment]
@shrutinehra, apologies for the delay and thank you for your patience. I am now able to repro the issue. When sending a Word doc where the file name ends with a '+', the file's content information is not being added to the Attachments array. However, when the file name is just alphanumerics, the file's content information is added. I've only tested a handful of times; at this point, the outcome has been consistent in each case.

I'm going to dig deeper into this to see if I can isolate the cause. I will update you when I know more.

**Comment by stevkan** [comment]
Testing a JS SDK bot via Teams produced the same results. However, testing in Emulator, Test in Web Chat, and Web Chat (hosted on a web app) all functioned correctly when using either a Composer bot or a JS SDK bot.

**Comment by stevkan** [comment]
Did additional testing by running Fiddler and monitoring requests/responses. Sent attachments in Teams and could see them in the responses for both messages sent to and not to a bot. However, that only displays the attachments as they were sent between the client and the Teams server. Not surprisingly, as the connection between the Teams server and the Teams connector in ABS is not visible, I am unable to determine if the issue lies on the Teams side or the ABS side.

**Comment by stevkan** [comment]
@clearab, could you take a look at this or connect this to the right Teams person to handle?

**Comment by clearab** [comment]
I believe there might be two issues happening here - an encoding issue with file names including some special characters, and also that sending/receiving files in Teams is **only** support in the personal scope. Do those two issues account for the failures y'all are seeing, or is there another case to be aware of?

More info on sending/receiving files in Teams can be found here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4

**Comment by axelsrz** [comment]
Closing this one due to inactivity, @SwetalinaGitHub feel free to re-open this issue if you still experience problems.
