### ISSUE TITLE
Response status code does not indicate success: 403 (Forbidden).

### ISSUE THREAD

**Issue by so0325** [microsoft/BotFramework-Composer#8813]
## Describe the bug

Bot works OK locally with Composer, but not when deployed to Azure, sending the response "Response status code does not indicate success: 403 (Forbidden).". By elimination, this happens when there is more than one Dialog that use NLU. Bot Composer forces the creation of an additional LUIS instance when you create a new Dialog. However, the file 'appsettings.json' is never updated upon building, and there is no documentation of how to reference more than 1 LUIS instance in said file.

## Version

Release: 2.1.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot with at least 2 dialogs that use NLU
2. Deploy on Azure
3. Test the bot with Bot Framework Emulator
4. See error "Response status code does not indicate success: 403 (Forbidden)."

## Expected behavior

Expected some documentation about how to configure 2+ LUIS instances since it is Composer who forces the creation of an additional LUIS instance. Or the compilation method to generate a complete apsettings.json file.

## Additional context

Generated apsettings.json after building (LUIS cut):

`{  "luis": {
    "authoringEndpoint": "",
    "authoringRegion": "westeurope",
    "defaultLanguage": "es-es",
    "endpoint": "",
    "environment": "composer",
    "name": "BotName"
  },
  "MicrosoftAppId": "",}`

Manually filled apsettings.json so that it works with the main LUIS instance once deployed on Azure:

`{"luis": {
    "endpointKey": "AAA",
    "authoringEndpoint": "",
    "authoringRegion": "westeurope",
    "defaultLanguage": "es-es",
    "endpoint": "",
    "environment": "composer",
    "name": "BotName",
    "BotName_es_es_lu": {"appId": "BBB"}
  },
  "MicrosoftAppId": "CCC",
  "MicrosoftAppPassword": "DDD",}
`

Where A/B/C/D details are censored keys and IDs.

**Comment by dmvtech** [comment]
Hi @so0325 

>  By elimination, this happens when there is more than one Dialog that use NLU. Bot Composer forces the creation of an additional LUIS instance when you create a new Dialog.

To clarify; Yes: Composer creates a new/different LUIS app for each dialog that uses NLP. 

>  However, the file 'appsettings.json' is never updated upon building, and there is no documentation of how to reference more than 1 LUIS instance in said file.
 
Can you clarify what you mean by building? Are you just re-building/running your bot in Composer? You must **re-publish** for the appropriate steps to happen and for the appsettings.json to be updated.
 
 Mine shows correctly after adding LU in dialogs and publishing: 
 
 ```
   "luis": {
   ..........
    "TwoDiagsWithLUIS8813_en_us_lu": {
      "appId": "40a32d61-faef-40cf-94e5-xxxxxxxxxxx"
    },
    "PickMusic_en_us_lu": {
      "appId": "a20fee69-224c-4fb9-b88a-xxxxxxxxxxx"
    },
    "PickFood_en_us_lu": {
      "appId": "1aafbf06-e76e-4aba-b9ca-xxxxxxxxxxx"
    }
 ```

**Comment by dmvtech** [comment]
To further clarify; this should work without having to make any changes to the settings.

**Comment by so0325** [comment]
Thank you for your reply.

Yes, I meant re-building/running. It makes sense that apsettings is generated during publishing process, but I have been unable to publish it either with new resources or using resources already created. Therefore I resorted to manually configuring each Azure service to deploy my bot.

Thank you for the LUIS settings example. Writing it like that + manually Publishing my secondary LUIS on the LUIS website made my bot finally work.

I will close this issue since this change worked for me.
