### ISSUE TITLE
LUIS Language Supports Error (Turkish)

### ISSUE THREAD

**Issue by cankanat** [microsoft/BotFramework-Composer#8820]
LUIS service supports Turkish but it gives an error in the Composer.

https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-language-support

## Version

- 2.1.1

## Browser

-  Chrome

## OS

- Windows

## Screenshots

![image](https://user-images.githubusercontent.com/17693535/144173902-b83a137a-7212-4797-a613-d7c6e1c46430.png)

**Comment by stevkan** [comment]
@cankanat, if you haven't already, can you please try passing in 'tr-tr' for the locale setting?

**Comment by cankanat** [comment]
> 

thank you @stevkan, it worked
