### ISSUE TITLE
How to begin a dialog with a variable value as the dialog name

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#8821]
I setup the Event activity with the dialog name as the Activity Value, and then have an expression of `=turn.activity.value` in Dialog name field, but does not seem working as it results in a Null Ref exception in the BotController.cs

**What would be the correct way to dynamically begin a dialog with the given name through a variable?**

<img width="688" alt="image" src="https://user-images.githubusercontent.com/44714043/144199947-242ee98e-0d25-4cfe-b04e-32338c6f8a68.png">

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/44714043/144200152-6b6e148c-6734-49c4-8655-1beb3a2b93ac.png">

**Comment by anishprasad01** [comment]
Hi @dawwa,

I am a little confused by your approach here. As I understand it, your goal is to choose and start a dialog based on what the user types, correct? For example, if I have a travel booking bot, I might want to start one dialog if the user says they want to book an international flight and I might start a different dialog if they say they want to book a cross-country train journey, and so on.

If this is indeed the behavior you want, why do you wish to store the user's answer in a variable and start a dialog based on that? Do you have specific functionality that requires you to do it this way?

The generally accepted pattern for Composer would be to create a trigger for each dialog with several trigger phrases and then start the corresponding dialog within that trigger. This would enable you to sidestep storing the user's input, avoid your user needing to perfectly match the name of the dialog, and allow you to easily modify the various trigger phrases that your user could enter to start a dialog.

You can achieve this in Composer using LUIS, RegEx, or a few other methods.

For reference, here are some helpful docs:

- [Controlling conversation flow](https://docs.microsoft.com/en-us/composer/how-to-control-conversation-flow?tabs=v2x#begin-a-new-dialog). This document explains how to start dialogs and such.
- [Creating a simple weather bot](https://docs.microsoft.com/en-us/composer/tutorial-create-weather-bot). This tutorial covers various core concepts including switching dialogs with RegEx and LUIS. I highly recommend going through it if you haven't already.

**Comment by dawwa** [comment]
@anishprasad01, the context behind this is to initiate a proactive message based on an event activity instead of user intent trigger.

`To create a BotChat.DirectLine object for BotChat.App, and post an event activity in client side code. Then in the bot code, respond to the event with the desired proactive message.`

As seen in the comment below.
https://github.com/microsoft/botframework-sdk/issues/4245#issuecomment-369311452

**Comment by anishprasad01** [comment]
I think I understand what you're trying to do now. Let me investigate further and get back to you.

**Comment by anishprasad01** [comment]
@dawwa 

It seems to be that there is an issue with how Composer deals with DialogSets internally. The `NullReferenceException` you're getting is likely because the bot cannot find the dialog in question, and not because of any issue with the user's input.

However, there is a workaround. This [issue thread](https://github.com/microsoft/botbuilder-dotnet/issues/5790#issuecomment-881774645) outlines a workaround that involves creating a dummy event that you never call and invoking all of your dialogs in it. Then, invoking the dialog with the input format `=turn.activity.value` in the Dialog name field of your original event should result in the behavior you're looking for.

**Comment by EricDahlvang** [comment]
Hello @dawwa  and thank you for engaging with the Composer project.  Supporting the "dialogs" array in the Composer ui would be a new feature request. We'll take this issue as a feature request and add it to the backlog for prioritization. We do not have an ETA at this time for when this feature will be available.
