### ISSUE TITLE
Bot Composer - Language Generator - Stress testing - App is down after starting the app without any crash (memory or CPU) 

### ISSUE THREAD

**Issue by Olakhrisat** [microsoft/BotFramework-Composer#8824]
V2.00-test

## Browser

-  [ ] Electron distribution
- Chrome
- Safari
- Firefox
- Edge

## OS

- [ ] macOS
- Windows
- [ ] Ubuntu

## To Reproduce

1. we build a large bot with a lots of scenario on composer
2. publish composer on azure with P2V3 app plan service
2. run a stress test
3. bot is down without any memory or cpu issues
4. collect memory dump

## Expected behavior

bot run normally

## Screenshots
after investigation I found an issue with "RunSync" function, the thread is locked here after number of requests

![image](https://user-images.githubusercontent.com/59798587/144210829-f8ea48a3-eae5-4ff0-8709-171c675ccec0.png)

so I commented this function
![image](https://user-images.githubusercontent.com/59798587/144210949-b51d54c7-1121-4427-8e01-9d9a81b9d339.png)

![image](https://user-images.githubusercontent.com/59798587/144210978-23427318-4a10-45c5-8a24-909d96e7e7e7.png)
![image](https://user-images.githubusercontent.com/59798587/144210995-fe2f3207-d035-4e1e-8727-7099baa4870b.png)

and re-run a stress testing again and everything works fine

please advise, is this code will affect areas that I did not notice? is my workaround will break some other code? and is there any other solution to fix this issue?

**Comment by axelsrz** [comment]
This is being tracked in an internal icm

**Comment by gabog** [comment]
This should be addressed in the upcoming 4.15.1.
