### ISSUE TITLE
Response status code does not indicate success: 403 (Quota Exceeded). LUIS Standrad Plan

### ISSUE THREAD

**Issue by yodanielo** [microsoft/BotFramework-Composer#8825]
![Ashampoo_Snap_miércoles, 1 de diciembre de 2021_18h23m52s_012_](https://user-images.githubusercontent.com/1326867/144330236-758051ce-37f6-42b2-a0c6-878db6282389.png)
## Describe the bug

I've configured LUIS with standard plan S0, it was working fine until today, suddently we've received the following error: Response status code does not indicate success: 403 (Quota Exceeded).
We have double checked the LUIS configuration to make sure we have the standard plan and we've discarded it's due to sourcecode error.

## Version

We are using Bot Framework Composer v2.1.1
Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Execute the bot with bot emulador o webchat

## Expected behavior

![Ashampoo_Snap_miércoles, 1 de diciembre de 2021_18h23m12s_011_](https://user-images.githubusercontent.com/1326867/144330175-d2b7257c-b33e-4384-ac86-2f97c618ce6c.png)

**Comment by axelsrz** [comment]
Hello @yodanielo thanks for logging this. Can you confirm if you are using both authoring and prediction endpoints instead of just authoring.

**Comment by dmvtech** [comment]
Hi @yodanielo Are you able to confirm the above per Axel?

**Comment by yodanielo** [comment]
I don't know how to confirm it, I have understood that both of them have to work together, actually in bot compposer I have only set the authorng service.

**Comment by dmvtech** [comment]
Hi @yodanielo 

In your bots `Advanced` settings (json view), you should find something like:
```json
  "luis": {
    "authoringEndpoint": "",
    "authoringRegion": "",
    "defaultLanguage": "en-us",
    "endpoint": "",
    "environment": "",
    "name": "",
    "authoringKey": "",
    "endpointKey": ""
  },
```

You would want both the authoring values entered but aslo the `endpointKey` and `endpoint` values for the prediction endpoint.

**Comment by yodanielo** [comment]
![image](https://user-images.githubusercontent.com/1326867/146444630-5a9d989b-2b54-404b-8b70-b9ab8b9c1715.png)

**Comment by dmvtech** [comment]
@yodanielo Can you add your _prediction_ endpoint key to the `endpointKey` value and then test to see if you still get the same issue?

**Comment by dmvtech** [comment]
Closing due to lack of response. Please comment or reopen if you still need assistance.
