### ISSUE TITLE
Log to console not logging to console

### ISSUE THREAD

**Issue by rbnswartz** [microsoft/BotFramework-Composer#8826]
## Describe the bug

Log to Console doesn't log to console output.

## Version

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an empty bot from the c# template
2. In any of the dialogs add a Log to console action with a log message
3. Run the bot, open the output window, and trigger the dialog

## Expected behavior

When the Log to console action runs it should write out to the host console visible in the output window.

## Screenshots

![image](https://user-images.githubusercontent.com/724704/144450365-ab8297cf-4e2b-42af-9d31-0801507b8c98.png)

## Additional context

Maybe I have something configured wrong but I would expect an out of the box template to be configured correctly

**Comment by benbrown** [comment]
I can reproduce this issue. I do not see messages from the `log to console` action on the console in Composer or from the terminal.  

@rbnswartz You can enable the `send trace activity` option and these messages will appear in the `Web Chat` output in Composer.

**Comment by dmvtech** [comment]
I can as well. Also tested with Node runtime. No logging in console.

**Comment by benbrown** [comment]
It appears that this action does not directly log to the console - it logs to the configured telemetry provider (app insights) and can send trace activities. 

Here is the implementation in C#:
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/LogAction.cs#L88

Here is a doc about setting up trace listeners:
https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/how-to-create-and-initialize-trace-listeners

**Comment by rbnswartz** [comment]
@benbrown Thanks, I'll have to implement one of those. Probably should change the name of the action so that people don't expect things to be logged to the console, and have nothing show. It would help alleviate potential confusion.

**Comment by benbrown** [comment]
@rbnswartz I agree!
