### ISSUE TITLE
Azure credentials wrong after deploying with Azure CLI

### ISSUE THREAD

**Issue by owenpww** [microsoft/BotFramework-Composer#8831]
## Describe the bug
Hello I created 2 bots with Bot Framework Composer and I have been successfully testing them on Composer, Emulator and ngrok. I also have been successfully publishing them to Azure initially with the Publish function on Composer but now with a CI/CD pipeline on an Azure project.

My problem is that, in trying to implement a feature, I wanted to determine if it would be better if we switched over to a Bot Framework SDK bot should it be easier to implement and relatively easy to do all the work we've previously done on it. After following this https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=csharp%2Cuserassigned exactly (for Javascript Bot), I was successfully able to implement the feature and deploy the bot to Azure. However, when I tried to test my Composer bots locally again, they no longer were working. Moreover, when I went to the Azure Bot resource for these two bots and I click Manage on their app ID's Azure gives me an error saying the apps couldn't be found. It keeps giving me an error saying that the App ID and password are not found on the tenant. When I try to publish the bots using composer, I get prompted to log in and then it tells me my tenant xxxx is not found. What is strange is that the tenant ID the error is telling me cannot be found is not my home tenant neither my other tenant (I only have two tenants confirmed).

Additionally, I cannot even test the SDK bot locally anymore either (neither on emulator or on ngrok) because of a 401 error (but I can deploy and test it on Azure with the same Azure CLI commands that messed up my Azure credentials). It keeps telling me the app ID and password are incorrect when I know them to be true because I queried this endpoint https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token?= with the exact same app ID and password and it came back successful.

I think the Azure credentials stored on my computer or stored somewhere locally is messing up all my bots. I've tried clearing the cookies, cache and storage on Composer, deleting the contents of .azure dir and az logout but nothing has helped. Azure doesn't even give me the chance to specify what directory or tenant I want to choose when it prompts me to login. Whenever I login, it just assumes this weird tenant ID I've never seen before. Please help me. I cannot test any of the bots (composer or sdk) locally because of these sign in issues.

## Version
Release: 2.0.0

## Browser
- [ ] Electron distribution
- [/ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
- [/ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce
1. Create a bot using composer 
2. Deploy bot (either using CI/CD pipeline on Azure or Publish button in Composer)
3. Create a bot using JS SDK
4. Deploy using Azure CLI

## Expected behavior
Deployment of SDK bot without affecting the composer bots I had previously created

## Screenshots
Error when testing SDK bot locally
![image](https://user-images.githubusercontent.com/93670080/144694707-438c6b63-7563-4cb0-b870-bb08922d8359.png)
Error when testing Composer bot locally in Composer
![2021_12_03_0vv_Kleki](https://user-images.githubusercontent.com/93670080/144694754-004bc17d-fd17-41db-832e-a770f8a01894.png)
Error when testing Composer bot locally in Emulator
![image](https://user-images.githubusercontent.com/93670080/144694784-03d7ed91-cc36-45e8-8913-02c99c1e82f4.png)
Error logging in to Azure from Composer
![2021_12_03_0vz_Kleki](https://user-images.githubusercontent.com/93670080/144694840-467257e6-bfa4-461f-bd46-5cce56900707.png)
Error when clicking "Manage" on the app ID of the Azure Bot resource of the Composer bot
![2021_12_03_0w1_Kleki](https://user-images.githubusercontent.com/93670080/144694912-b656b2a7-2360-49ee-9802-15b052d31d58.png)

**Comment by benbrown** [comment]
@owenpww the app id and password are managed inside Composer inside the bot settings. Have you confirmed that they are correctly listed there?

Something else to try - Composer has a cache that stores the most recently used Tenant. This may be causing the problem.  You can remove this value by going to the developer tools inside Composer, navigating to Application, Local Storage. Then remove the "composer:tenantId" key.

**Comment by owenpww** [comment]
![image](https://user-images.githubusercontent.com/93670080/144900808-5155c457-9c0b-4cdc-b5f2-7fede35a2c30.png)
![image](https://user-images.githubusercontent.com/93670080/144900910-c34989e1-f15b-4459-9ca0-c0e2c92bf30f.png)
Tenant ID seems to be empty in Dev Tools in Composer

**Comment by owenpww** [comment]
This might be useful also. There seems to be a failed request at /getTenants.
![image](https://user-images.githubusercontent.com/93670080/144901095-0432a23e-cf1b-45fd-a779-f682d35d9790.png)

**Comment by benbrown** [comment]
Have you logged OUT of the Azure CLI?

**Comment by owenpww** [comment]
@benbrown Yes, I initially created the app registrations through Composer. Yes, I've literally tried deleting everything I can find which could be related to Azure/Composer and still the issues persist. When I click on the line for the getTenants error, it doesn't show any additional details.

I logged into azure cli using az login very recently and have not logged out since.

**Comment by benbrown** [comment]
can you run `az account tenant list` and see if this tenant id appears?

**Comment by benbrown** [comment]
@owenpww ok, well that rules out that as a source of problems. HRRM!

I'll get back to you asap.

**Comment by owenpww** [comment]
Thanks @benbrown!

**Comment by owenpww** [comment]
Hello @benbrown, I've been able to isolate that the problem is some local setting on my machine. I was able to briefly borrow another machine and when I downloaded Composer and logged into Azure through the Composer UI, it gave no errors and was able to detect and bring up all my directories, subscriptions, etc. Having this in mind, would you please be able to help me clear out or basically reset all my Azure and Composer settings on my local machine? I'm not able to use any other machine for work in place of my current machine. I tried deleting the Composer folder and application, reinstalling and updating Composer, deleting its local storage and all the cache and cookies, deleting the contents of my `<user>/.azure` dir, tried a few Azure CLI commands like `az logout`, `Clear-Credentials`, etc. and it still seems to be giving me these tenant errors from this unknown tenant ID.

Do you have any other updates from your end either? These are just my findings though I think they're useful in finding a path to the solution.

**Comment by benbrown** [comment]
There is a `BotFrameworkComposer` folder that contains some settings and a cache of the templates. This is in your root user folder on a Mac, or in `AppData/BotFrameworkComposer` on a Windows machine.

@cwhitten are there any other places a tenant setting might be hiding as far as you know?

**Comment by owenpww** [comment]
Hello @benbrown yes, I've already deleted this in the past together with deleting and reinstalling and updating Bot Framework Composer.

**Comment by benbrown** [comment]
@owenpww there might be one more, see here:  https://github.com/microsoft/BotFramework-Composer/issues/8550#issuecomment-897807008

**Comment by owenpww** [comment]
@benbrown Hmmm would you happen to know where this is on Mac? I can't find either `@bfc` or `electron-server`

**Comment by cwhitten** [comment]
@owenpww you can find it here:

/Users/${user}/Library/Application Support/@bfc

**Comment by owenpww** [comment]
Still didn't seem to fix it unfortunately. Should I maybe try to delete `/.dotnet`, `/.nuget`, `/.aspnet`, `.netrc`?

**Comment by owenpww** [comment]
Hello @benbrown and @cwhitten, I was able to login successfully through composer by clearing all data for all time in my Chrome browser and clearing all windows-related keys in apple keychain. However, whenever I try to provision resources through Composer, the Azure Bot resources still show the app not found error on Azure Portal.

**Comment by benbrown** [comment]
@owenpww i am glad that you were able to resolve the login issue!

I am not sure how the app registration is getting lost -- do you see the resulting app id and secret stored in your configuration?

**Comment by owenpww** [comment]
@benbrown Yes in the publish profile in Composer! But when I go to Azure Portal, go to the corresponding Azure Bot resource and click Manage on the application ID, it gives me that same Not Found error I showed above.

I tried creating an Azure Bot manually (i.e. a singular Azure Bot without the other resources needed like App Service, App Insights, etc.) and it seems like the differences I immediately notice between this manually created Azure Bot and the one created by Composer as part of its automatic provision function is that in Configure, the manual Azure Bot has the Bot Type (multitenant) and the automatically created bot does not have this field at all. Likely related to this, when I go to Azure Active Directory, I can only see the manually created Azure Bot under App Registrations and not the automatically created one.

I think something really got changed on my tenant when I used the deploy command from the Azure CLI. I have not recalled using Azure AD prior to these Azure AD-related issues and I never got these issues with the Composer-provisioned resources before.

**Comment by owenpww** [comment]
Hello @benbrown just found out another person on my team is experiencing the same tenant issues (showing the exact same mystery tenant ID that neither of us know of). I guess even if I found a resolution that clears the errors on my machine, there is still some hosted/global configuration that is causing errors for other people.

Do you have any updates?

**Comment by owenpww** [comment]
Hello @benbrown we have uncovered more issues. For teammate A who keeps getting the tenant issues, he is experiencing them both on composer and any Azure-related application (QnA maker, Azure Portal, etc.). This is different from what I experienced in that I only got these tenant issues on Composer but not in my browser when I would go to various Azure applications. Another teammate, teammate B is not experiencing these tenant not found issues but both he and teammate A are starting to see old inactive tenants when they go to their list of tenants instead of tenants X and Y which is what we all had at the start of development.

Any updates on your end?

**Comment by benbrown** [comment]
Hi @owenpww thanks for the updates. I don't have any news from my side yet.

Your teammates are seeing these weird tenant behaviors _outside of Composer?_

**Comment by owenpww** [comment]
@benbrown yes. They have noticed it on Azure Portal and QnA maker portal.

**Comment by owenpww** [comment]
Hello @benbrown are there any updates on your side? I am concerned of the depth of the impact since I'm not quite sure where the issue is coming from and what it affects.

**Comment by benbrown** [comment]
I don't have any new info, but I can assure you that neither Composer itself nor the BF cli tools  make any changes to your Azure tenant settings or anything like that. The only resources that are involved are those that are explicitly listed in your configuration, and only to configure the bot.

**Comment by owenpww** [comment]
Do you think the tenant-related parameters could have changed the settings on our subscription (and subsequently the resources in it)? I think that is possible given what you have said and the details required for the Azure CLI [commands](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp%2Cuserassigned).

**Comment by benbrown** [comment]
What tenant-related parameters are you referring to?

**Comment by owenpww** [comment]
From rereading the doc, it seems like tenant ID but with that alone couldn't the other parameters (ex. tenant type: single-tenant, multi-tenant) affect the settings on the tenant?

**Comment by benbrown** [comment]
@owenpww I was not able to find any explicit link to this type of change to any tenant setting - not in the BF cli or Composer tooling.

It might be possible that something in the main `azure cli` had some impact on your tenant.. .but I doubt it would happen automatically. 

Is this still occurring for you? Have you unblocked your Bot Framework Composer problem?

**Comment by owenpww** [comment]
The issue is still occurring but we found a workaround by creating a new account and using that account to recreate all of our services and resources. We cannot use any of our other accounts to do this unfortunately. Hopefully your team can find the solution for this issue as I only followed the Azure documentation and got these errors. It's entirely possible someone doing the same thing will run into the same issue.

**Comment by carlosscastro** [comment]
Hello @owenpww is this unblocked on your side?

**Comment by owenpww** [comment]
Hello @carlosscastro yes with the workaround I mentioned. It works but of course it would be better not to be confined to using the hack.

**Comment by mrivera-ms** [comment]
Closing as resolved.
