### ISSUE TITLE
Node version display on Help>About does not reflect installed node version

### ISSUE THREAD

**Issue by metkhoo** [microsoft/BotFramework-Composer#8832]
## Describe the bug

When using Bot Composer 2.1.1, the About shows a different version of node js compared to the version actually being used.

## Version

![BotAbout](https://user-images.githubusercontent.com/18167332/144745658-bd9cb36f-3c5e-4415-9e4b-d1a5a5143616.jpg)

## OS
- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Help > About'
2. Compare to "CMD" "node -v"

## Expected behavior
Expected to see the same node.js version as the underlying OS

## Screenshots

![node14](https://user-images.githubusercontent.com/18167332/144745728-f64d417c-68c0-43a2-af62-4efce02d9a09.jpg)

**Comment by benbrown** [comment]
@metkhoo the node version listed in the about screen is the one that is used internally by Electron to power the internals of Composer.  It is different than your system Node version.
