### ISSUE TITLE
Bot Framework - Composer

### ISSUE THREAD

**Issue by Olakhrisat** [microsoft/BotFramework-Composer#8833]
Hi All,

I want to connect my composer bot with Instagram,

any idea of how this can be done?

**Comment by benbrown** [comment]
@Olakhrisat We do not have direct support for Instagram. 

In order to do this, you would need to create a custom adapter and install it into your bot as a component.

There are several examples here:
https://github.com/microsoft/botbuilder-dotnet/tree/main/libraries/Adapters
