### ISSUE TITLE
Question about certain functionalities

### ISSUE THREAD

**Issue by rajeshdagdevir** [microsoft/BotFramework-Composer#8835]
Hello.
I have two questions.

1. Arrays
Let's say I make a loop and in that loop I keep asking the user for text input. How can I add these inputs to a list/array so I can re-use it later?

2. ML Entity
Is it possible to extract and re-use the value of a ML entity in a intent recognized activity? Lets say my input is i want to call {number=123} now; how can I extract that "123"?

**Comment by benbrown** [comment]
1. You can create use the `edit an array property` action to push, pop and take other array operations on variables

2. The ML entity will only be in scope for the turn during which it was recognized - so if you want to keep it, use the set property action to store it in the dialog or user scope.

**Comment by benbrown** [comment]
The entity should be available as a variable called `@entityName` -- for example `@number` or `@zipcode`

**Comment by aresdesigns** [comment]
> The entity should be available as a variable called `@entityName` -- for example `@number` or `@zipcode`

Ben, thank you VERY MUCH for your reply. I have one final questin. I am using the Composer Core Assistant Template.
Can I somehow get my bots "code"? The project itself only has like dialog files. I want to add CosmoDB functionality to my bot. How can this be done with the Core Assistant Template? I found this good tutorial https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp
but how do I implement it for a composer bot? Do I have to initialize everything in the bot project or in a custom action?

**Comment by tracyboehrer** [comment]
@rajeshdagdevir For most of those, you'd likely need to write a custom action.  The Microsoft.Bot.Components.Graph Component might help you with the Outlook Calendar API.  The docs are light on that, but you can check out the Actions.  It is possible to make HTTP calls from Composer via "Access external resources:Send an HTTP request".  But the service you need must support REST calls.
