### ISSUE TITLE
Cannot extract entity value from turn.recognized

### ISSUE THREAD

**Issue by aresdesigns** [microsoft/BotFramework-Composer#8838]
Hello.
I have a intent recognized where I try to print the value of the entitiy.
When I for example send ${turn.recognized.entities}, I get:

{
“lgType”: “Activity”,
“text”: {
"$instance": {},
"friends": [
  [
    "jackson"
  ]
]
}
}

How can I get "jackson" out of there? When I try ${turn.recognized.entities[0]} or ${turn.recognized.entities.text} or anything farther than entities, I get an error occurred.

regards

**Comment by benbrown** [comment]
You should be able to refer to the entity directly as `@friends` and so `@friends[0]` would contain your value.

**Comment by aresdesigns** [comment]
> You should be able to refer to the entity directly as `@friends` and so `@friends[0]` would contain your value.

It doesnt work. I tried to send the values as message in the corresponding intent reognized with ${turn.recognized.entities.@friends[0]} / ${turn.@friends[0]} / ${turn.recognized.@friends[0]}

does this only work for ml entities or list entities too?

**Comment by benbrown** [comment]
Sorry, not `turn.recognized.entities.@friends` but just `@friends`

**Comment by aresdesigns** [comment]
> Sorry, not `turn.recognized.entities.@friends` but just `@friends`

jesus christ. it worked. thank you man. is there a doc for this? didnt find anything online. i feel very stupid

**Comment by benbrown** [comment]
Don't feel stupid! It's not always obvious what to look for.

It's here in the docs about language models:
https://docs.microsoft.com/en-us/composer/how-to-define-intent-entity?tabs=v2x#define-a-language-model

**Comment by benbrown** [comment]
Let me know if I can help with anything else! I'm going to close this issue for now.

**Comment by dmvtech** [comment]
@aresdesigns  This section regarding shorthand notations in the docs is nice to have handy as well:
https://docs.microsoft.com/en-us/composer/concept-memory?tabs=v2x#memory-scope-shorthand-notation
