### ISSUE TITLE
Trigger an intent manually 

### ISSUE THREAD

**Issue by ridasaleem0** [microsoft/BotFramework-Composer#8839]
Hi, 
I wanted to know if there is a way to trigger an intent manually within a dialog instead of the user invoking it. @dmvtech

**Comment by aresdesigns** [comment]
You can create a custom event where you start a new dialogue. and where you want to trigger manually you just -> external access -> emit custom event

**Comment by dmvtech** [comment]
hi @ridasaleem0 Please clarify on how you want to trigger the intent. Does the suggestion by @aresdesigns fit your requirement? If not, please give more specifics on the scenario and what you are wanting to accomplish.

**Comment by ridasaleem0** [comment]
So basically I have 2-3 intents doing the same thing and for some reason, I cannot combine their training data together. Every time "x" intent is detected, I want the "y" intent to invoke and carry out its subsequent flow. 
Does that make sense? 
@dmvtech @aresdesigns

**Comment by ridasaleem0** [comment]
@aresdesigns I am not sure I fully grasp your concept. Can you maybe align it with my above explanation? Thank you.

**Comment by ridasaleem0** [comment]
Also on a completely different topic, **=turn.recongnised.intent** with **or condition** in an **If block** could help us segregate between various intent flows? I am trying but it always takes me to true condition and never false? 

![Screenshot from 2021-12-08 11-47-49](https://user-images.githubusercontent.com/65173498/145161772-cabf598c-6186-4766-8e23-7e5f69930176.png)

**Comment by dmvtech** [comment]
Hi @ridasaleem0 Thank you for the follow up.

> I have 2-3 intents doing the same thing

Can you expound more on this? Do you have multiple `Intent Recognized` triggers that have similar trigger phrases?  

> and for some reason, I cannot combine their training data together. 

My apologies, I'm not quite understanding. 

> Every time "x" intent is detected, I want the "y" intent to invoke and carry out its subsequent flow.

When the `x` intent is detected; that causes that trigger to run. Can you run whatever dialog that `y` trigger should run explicitly by using `Begin a dialog` action? You could even test off of an `if` action and check some memory variable, if you needed some sort of logic.


If you are able to share your bot (sanitized of personal and sensitive info) that shows the behavior and specific examples of what you are trying to get to work, that might be the best route to a solution. You could put the simple/repro bot in a repository and invite me.

**Comment by dmvtech** [comment]
Closing due to lack of response and reproducible sample. If you still need assistance with this; please provide more information or a sample on the current bot logic. Please comment or reopen if needed.

**Comment by rd-devvv** [comment]
Hi @dmvtech, I'm trying to do something similar
I have a registration trigger I prompt for values then send API
First API I retrieve email password currency then call API and post.
Second API I retrieve first name, last name, DOB, address, etc... then call another API and post
If my First API response fail I want to repeat all the process(intent) like begin from the first dialog all the way to end
If Second API fail I want to start from get first name then continue all the way to the last dialog
In other ways I want to restart the whole intent or restart it from a certain dialog in it and continue
I tried replace dialog but it takes that dialog only but doesn't continue the process with the rest after it like getting email password so on, then hit API .

Hope it's clear,
Thank you in advance
