### ISSUE TITLE
Does Composer extension works in downloaded desktop version of Composer IDE?

### ISSUE THREAD

**Issue by gitathrun** [microsoft/BotFramework-Composer#8841]
Hi, It is a great feature for developers to extend Composer IDE with customisation, but after reading through this page, I am not clear about following point:

1. Is there any quick start guide with snapshot that can lead developer to run and see the difference of an extension? such as the Sample-ui-plug example, directly show us the difference with/without of an extension?
2. There are different version of Composer, like downloaded windows app, mac app and web app version, I am wandering does this Composer extension feature works for all version or only the web app version? I have created a subdirectory "extension" in my windows app Composer and copy paste the Sample extension into the directory, but windows app Composer startup and there is no difference before/after, can anyone explain whether the Composer extension support all Composer version? and guide on how to setup?
Thanks!

**Comment by gabog** [comment]
Hi @gitathrun can you send us the link to the page you are referring to?

**Comment by gitathrun** [comment]
hi, @gabog following two pages:
https://docs.microsoft.com/en-us/composer/concept-extension
https://docs.microsoft.com/en-us/composer/how-to-use-extensions

Those two web pages explains the basic about Composer Extension, they mentioned Composer extension is a Javascript module, but did not mention whether the extension could work with Downloaded desktop Composer IDE which I think it is based Electron. 

I currently got some examples of extension running in web app version Composer IDE such as the web route and Sample-UI-plugin, but some of the example, especially the Publish related example, although I have changed composer.enable to "true", but from the IDE UI, I did not see any different, I am think if it is possible for the document page could have some snapshot that indicates the difference in UI if the publish related extension is enabled?

Many thanks

**Comment by stevkan** [comment]
@gitathrun, I'm assuming you mean the desktop app of Composer when you mention "Composer IDE". If so, yes, extensions can be loaded in. The location of the extensions folder depends on the method of install you choose.

- If you chose to install for all users, then the folder should be located here: `C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\extensions`
- If you chose to install only for the current user, then the folder should be located here: `C:\Users\Steven Kanberg\AppData\Roaming\BotFrameworkComposer\extensions`

Please be aware that detecting whether an extension loaded or not mostly depends on the kind of extension you have included. For instance, the GitHub Auth extension displays during or right after load requiring you to sign in. The Sample UI plugin displays as a button (if I remember correctly) in the left menu context at the bottom (i.e. below Create, Configure, User input, etc.). Creating a custom runtime template extension will display custom template options when starting to create a new bot.

**Comment by gitathrun** [comment]
Hi, @stevkan , thanks for the tip, Yes, it works I have saved my bundled extension directory into `C:\Users\Steven Kanberg\AppData\Roaming\BotFrameworkComposer\extensions` directory and config the "composer.enabled=true" then the desktop composer loaded and show the custom UI button.

my bundled extension directory
![image](https://user-images.githubusercontent.com/22137687/146021671-518b6ee5-4f03-44e7-a05c-6e7731f61074.png)
The custom ui button show in web app
![image](https://user-images.githubusercontent.com/22137687/146022779-a01b0ede-2408-45cd-8be3-cc68ba2ba111.png)

But when I tried with custom publish extension, the publish page is the same with the default one, so I am bit confused, if anyone could post snapshot about the custom publish page looks like and the different between composer.enabled true/false?

Thanks!

**Comment by stevkan** [comment]
@gitathrun, I haven't tested the custom publish extension, yet. I will take a look at it and get back to you.

**Comment by tdurnford** [comment]
@stevkan Can you please provide an update on your progress?

**Comment by msomanathan** [comment]
@stevkan Could you please provide an update to this issue?

**Comment by stevkan** [comment]
@gitathrun, thank you for your patience. The Custom Publish extension provides other publishing alternatives (as defined by you in the extension) for you to select from.

When the extension is added and enabled, the publishing targets dropdown will display the newly added publishing options. As you can see below, I added a "Publish Using Custom UI" target as well as a duplicate. Neither extension is configured to actually publish, at this point. But, the extension _is_ working by displaying the options.

![image](https://user-images.githubusercontent.com/18403946/153260375-3963a516-f7e9-417f-a8f2-2907b3d2e6ef.png)

![image](https://user-images.githubusercontent.com/18403946/153260386-12738355-fa37-4aa7-af98-47bb02b21d13.png)

To test this, you can copy the "[azurePublish](https://github.com/microsoft/BotFramework-Composer/tree/main/extensions)" extension into either of the directory folders I previously mentioned (depending on how you installed Composer).

**Comment by stevkan** [comment]
Closing as resolved. If the issue persists or you have new details to provide, please feel free to re-open the issue.
