### ISSUE TITLE
error al publicar mi perfil 

### ISSUE THREAD

**Issue by lagiomAce** [microsoft/BotFramework-Composer#8847]
## Describe the bug
error de provision al cargar el perfil de publicacion.
{"name":"CREATE_APP_REGISTRATION","message":"App create failed! Please file an issue on Github.","stack":"Error\n at new CustomizeError (C:\\Program Files\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:269072:25)\n at createCustomizeError (C:\\Program Files\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:269077:10)\n at BotProjectProvision.createApp (C:\\Program Files\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:270570:17)"}. See provision.azureBot.log in your bot folder

## Version

  2.1

## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

**Comment by gabog** [comment]
Hi @lagiomAce, can you please share the contents of the provision.azureBot.log file mentioned in the stack trace above?

**Comment by gabog** [comment]
Closing this one due to inactivity, feel free to re-open.
