### ISSUE TITLE
bot framework

### ISSUE THREAD

**Issue by HarshitSingh11** [microsoft/BotFramework-Composer#8860]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
If you have an actual issue or bug, please enter pertinent information on the issue and steps to reproduces. I am closing this until that is available.
