### ISSUE TITLE
Azure account Login Issue when trying to publish the bot from Bot Framework Composer

### ISSUE THREAD

**Issue by poojarkpatel** [microsoft/BotFramework-Composer#8861]
When I try to publish the bot from Bot Framework Composer with ID assigned by my organization, it gives me following error message. 
```
Error 
Unfortunately, this application does not currently support your work or school’s regional cloud environment. 
Alternatively, you could use a Microsoft personal account. Don’t have one? Create a Microsoft personal account for free 
```
However, I am able to login and access my Azure account from portal.azure.com 

I have faced this issue several times

**Comment by delafu** [comment]
I have the same problem. Is there any work around?

**Comment by delafu** [comment]
Now It's working. Thanks!
