### ISSUE TITLE
Provisioning - The spinning activity indicator keep spinning forever

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#8869]
I was trying the doc below and the spinning activity indicator keep spinning forever, is this a bug or expecting user to terminate it manually?

https://github.com/microsoft/BotFramework-Composer/tree/main/Provisioning

![image](https://user-images.githubusercontent.com/44714043/147052854-f0e9e3af-d88a-4c13-86e9-d96c3a6c2d6d.png)

**Comment by dmvtech** [comment]
@dawwa I am able to reproduce the same. I doubt this is the expected behavior (a bug. Shouldn't expect the user to terminate it manually).

I'll see if I can find an easy fix.

**Comment by dmvtech** [comment]
Found the issue and submitted PR as you can see linked above. You can overwrite your script with [this](https://raw.githubusercontent.com/microsoft/BotFramework-Composer/dmvtech-provisioningscripts/Provisioning/provisioningComposer.js) to remedy the issue.
