### ISSUE TITLE
Combining the values of properties into a single property 

### ISSUE THREAD

**Issue by HugzBatman19** [microsoft/BotFramework-Composer#8870]
To whom it may concern,

I am relatively new to Microsoft Bot Composer. I've been experimenting with adaptive expressions, arrays and objects. I am working on a prototype "Smoothie Maker" bot as an experiment that will provide a template for another work related project. Essentially, the user inputs two choices of fruit - the two user inputs are asked sequentially - both of which are stored in the property 'user.choice.first' and 'user.choice.second' respectively. Then, through 'set a property', I intended to store both of these inputs in the single property 'user.smoothie'. Then, a new dialog with a multiple options switch would start, where depending on the value of user.smoothie e.g 'Apple,Pear', it would send a response thanking the user for making that respective smoothie. 

In the 'Set a Property', I tried a combination of things:
- join(createArray('getProperty("user.choice.first")', 'getProperty("user.choice.second")'), ',')
- createArray(user.choice)

I keep getting back - Object reference not set to an instance of an object. 

If anyone could provide assistant whether the above is possible in bot framework, that would be really helpful.

**Comment by dinobrago** [comment]
If you want an array from two properties Use Set Property in the flow as below with user.choices set to 
```
=createArray(user.choice.first,user.choice.second)
```
![image](https://user-images.githubusercontent.com/41213271/147139317-ebdb1b7d-2417-4af7-9e13-3bee1820dae7.png)

**Comment by dinobrago** [comment]
A better way to do it would be to push the answers into an answer array when you're asking the questions. That way, you don't have to bother with choice1, choice2, ... choiceN. When you are collecting the answers in the dialog, Instead of "Set a Property", use "Edit an Array Property", type of change = push, and save each answer in an array coming out of the dialog. Then you'll have all the answers in one array and you don't have to limit their choices to an arbitrary number. 

Let's say you collect the answer into dialog.answer. You can push this into dialog.answers as follows:
![image](https://user-images.githubusercontent.com/41213271/147141960-0ac474a8-257a-456e-8c7d-2daa9309023d.png)

**Comment by dinobrago** [comment]
You may have to set "always prompt" = true in the dialog configuration if you reuse, for example, "dialog.answer" to collect your information. If "dialog.answer" has a value in it , the next dialog will assume that the user has already answered the question (unless always prompt = true).

**Comment by HugzBatman19** [comment]
Here is what I have whipped up so far (always prompt has been set to true) - there are two user inputs of fruit asked:

**Question**
![image](https://user-images.githubusercontent.com/96521463/147182286-f502ea8c-2af7-4afd-88d8-de299554c402.png)

**Array**
![image](https://user-images.githubusercontent.com/96521463/147182437-c453fb06-7366-481e-bef4-d21ccd7b2828.png)

The next step is to use the array in a Switch (Multiple Options). However, the emulator stops after asking the two questions, so I believe there is an issue with the values. It only likes strings. Could I use the join() function at any point to combine all of it into a string? The emit event part is just to organise the responses in another separate dialog.

![image](https://user-images.githubusercontent.com/96521463/147182632-453ab5e5-27a7-46bc-a94e-84be8c85170b.png)

**Comment by stevkan** [comment]
@HugzBatman19, you can achieve what you are wanting thru the use of [adaptive expressions prebuilt functions](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0) that are passed into the condition field of switch statement.

First, be aware that I am working from the point of the user's selections having already been stored in an array. `user.answers`.

This bit of code uses the prebuilt functions ([if](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#if), [and](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#and), and [contains](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#contains)). Essentially, it checks the array to see if it contains any of the possible fruit combinations for a match. If a match is made, then it returns a string representing the array.

**Here is the code you will want to include:**
`if(and(contains(user.answers, "Apple"),contains(user.answers, "Pear")), "ApplePear", if(and(contains(user.answers, "Apple"),contains(user.answers, "Banana")), "AppleBanana", if(and(contains(user.answers, "Pear"),contains(user.answers, "Banana")), "PearBanana", "NoSelection")))`

**Here is the code broken down for readability:**
```js
if (
    and(
        contains(user.Answers, "Apple"),
        contains(user.Answers, "Pear")
    ),
    "ApplePear",
    if (
        and(
            contains(user.Answers, "Apple"),
            contains(user.Answers, "Banana")
        ),
        "AppleBanana",
        if (
            and(
                contains(user.Answers, "Pear"),
                contains(user.Answers, "Banana")
             ),
            "PearBanana",
            "NoSelection"
        )
    )
)
```

When a match is made in the adaptive expression based on the array ("Apple" and "Pear") and a string value is returned ("ApplePear"), that returned value is then compared against the cases in the switch statement. When a match is made in the switch, then the associated action is run.

![image](https://user-images.githubusercontent.com/18403946/147613353-e2521c16-0a88-42ce-b1a4-673b6247ff39.png)

![image](https://user-images.githubusercontent.com/18403946/147613399-4ec2ef28-4e92-47b0-9e3c-8cb568d68e92.png)

![promptValueToArray](https://user-images.githubusercontent.com/18403946/147613958-fa0e4b73-8bd7-42ba-aae8-e82286d0d242.gif)

**Comment by stevkan** [comment]
Closing as this should solve your issue.
