### ISSUE TITLE
Unable to find SMS Trascripts

### ISSUE THREAD

**Issue by gerald560** [microsoft/BotFramework-Composer#8872]
## Describe the bug

When looking inside blob storage we are unable to find the SMS transcripts only the webchat ones. 

## Version
Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce

1. We have a Composer bot that we are not deploying manually via a publish profile, but instead followed the documentation here:
https://docs.microsoft.com/en-us/composer/how-to-cicd
2. We have also deployed Azure Communications Services (SMS) with event grid see doc here https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/sms/handle-sms-events

## Expected behavior

We wanted to see the transcripts of SMS in blob storage

## Screenshots

![image](https://user-images.githubusercontent.com/12697408/147262839-3eff057a-0354-4e26-9dab-54a5822470d4.png)

expecting to see an SMS folder however even inside webchat we don't see the transcripts

**Comment by LeeParrishMSFT** [comment]
This seems to be an issue that would be better reported to the [Azure Communications Services](https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858) (SMS) team. The Bot Framework team doesn't have any insights into the workings of this product.

**Comment by gerald560** [comment]
nice pawn off.... what if the transcript didn't show using Twilio? or Facebook messenger? or ms teams? what makes your answer even worse is that it's an MS product!!

**Comment by LeeParrishMSFT** [comment]
@gerald560 if your issue is asking why you aren't seeing the webchat transcript we can assist with that, but for the ACS side of things we can't really assist in that we don't have any way to see what might be happening inside that product. Are you not getting a transcript for the webchat?

**Comment by gerald560** [comment]
No what I am saying is that if your product offer integration with various Chanels than you need to super them. Otherwise don’t offer them.

**Comment by carlosscastro** [comment]
Closing this issue, given that @LeeParrishMSFT's recommendation is correct - we don't have control over those transcripts in this repository. Thanks!
