### ISSUE TITLE
Copy a botframework composer project

### ISSUE THREAD

**Issue by jst84** [microsoft/BotFramework-Composer#8874]
Hi, is there a quick way to clone a composer project, changing name and relative infos?

thanks!

**Comment by dmvtech** [comment]
Hi @jst84 and thank you for engaging with the Composer project. There is currently no way to do this other than opening the bot in an editor and doing a find/replace on the name and info you wish to change. We'll take this issue as a feature request and add it to the backlog for consideration/prioritization. We do not have an ETA at this time for whether this will be accepted or possible, nor when this feature will be available if it is.
