### ISSUE TITLE
Group the json bot conversations into only one

### ISSUE THREAD

**Issue by fougere44** [microsoft/BotFramework-Composer#8877]
Hi Everyone,

I have a problem with my storage conversation from my bot in Azure Portal . Indeed, with this code in the index.ts file, i can save a conversation.
```
const adapter = new BotFrameworkAdapter({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
});
```
```
const transcriptStore = new BlobsTranscriptStore("name_of_your_chaine_string_storage_account", "name_of_your_container");
const transcriptMiddleware = new TranscriptLoggerMiddleware(transcriptStore);
adapter.use(transcriptMiddleware);
```

This is what i get in the Azure Portal :
![image](https://user-images.githubusercontent.com/58083670/147763330-4c4b0e66-8a6a-4a57-89c0-6aca70b3ff45.png)

One json file is generated for one action (actions are composed with questions and answers), and i would like to have only one json file with the entire all conversation, do you know how could we do this ?

Thanks for help ! :)

**Comment by munozemilio** [comment]
Hello @fougere44, we track questions in Stackoverflow. Could you please post it there?
