### ISSUE TITLE
CICD Azure Devops or Visual Studio

### ISSUE THREAD

**Issue by PrimeAltariz** [microsoft/BotFramework-Composer#8879]
## Describe the bug

I have done compilations from Azure Devops Pipeline and also test compilation from Visual Studio, but I see that the output contains fewer files than the one published directly from BF Composer.

![image](https://user-images.githubusercontent.com/34049303/147838328-25e0dcfd-e40e-4f5d-ad5a-5d9542338665.png)

## Version

![image](https://user-images.githubusercontent.com/34049303/147838320-c472b2e6-8192-442e-8765-1cad448bc97e.png)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. I generate the necessary resources in Azuew (App service plan, app service, Azure bot, MS Luis and QNA Maker)
2. In azure devops generate a pipeline integrating the compilation example from https://github.com/gabog/ComposerCICDSamples/tree/main/build/yaml
3. I perform conversation tests. Later I connect by FTP to the App Service that contains the bot to download what is generated

**Comment by stevkan** [comment]
@PrimeAltariz, I will be taking a look at this today and should have a response for you before the EOD.

**Comment by tdurnford** [comment]
@stevkan Any updates on this?

**Comment by PrimeAltariz** [comment]
Good afternoon!
I was doing some compilation tests, after doing the compilation described, and placing all the corresponding app settings in the Azure App Service, the bot responded correctly.

However I still don't understand if the missing DLLs are affecting the implementation. According to the tests of the bot, everything seems to work normally

**Comment by stevkan** [comment]
@PrimeAltariz, no, the "missing" files shouldn't be a concern. The process by which Composer deploys versus Visual Studio (or other processes) is different which is why you see additional files. There is nothing wrong with either deployment.
