### ISSUE TITLE
Host Azure Bot Composer on Azure Portal as SaaS to save effort for hosting bot composer on VM. 

### ISSUE THREAD

**Issue by liyubupt** [microsoft/BotFramework-Composer#8884]
## Is your feature request related to a problem? Please describe.

It costs some effort to set up azure bot composer on VM. Using a VM is not aligned with cloud strategies of many enterprises. Some enterprises use only PaaS. 

## Describe the solution you'd like

Manage Azure Bot Service on Azure as Software as a Service. Whenever a azure bot is provisioned, the hosting environment and azure composer should be provisioned and the URL for Azure composer should be available on the Azure bot.

**Comment by anishprasad01** [comment]
Hi @liyubupt,

As I understand it, you want to be able to run an instance of Composer in Azure without using a VM? Have you looked into using an [Azure Web App](https://azure.microsoft.com/en-us/services/app-service/web/) instead? You can automate deployments and it's a fair bit simpler than setting up a VM.

**Comment by Toleikis** [comment]
> Hi @liyubupt,
> 
> As I understand it, you want to be able to run an instance of Composer in Azure without using a VM? Have you looked into using an [Azure Web App](https://azure.microsoft.com/en-us/services/app-service/web/) instead? You can automate deployments and it's a fair bit simpler than setting up a VM.

Could someone document the process of hosting Bot Composer as a web app in Azure? Our team is interested in this as well and we have no option of using VM's for this purpose.

**Comment by liyubupt** [comment]
@anishprasad01 thanks for your answers! being able to host azure bot composer on Azure web app is definitely really cool. I was rather asking if you plan to manage azure bot composer as a software as a service and provide as a browser based application. Like synapse,  you could develop in browser without any need to install or deploy anything.

**Comment by anishprasad01** [comment]
@liyubupt

Ah, I understand now. Unfortunately, I don't believe there are any plans to offer Composer as a separate Azure SaaS service at this time.

@Toleikis 

I will pass your feedback on to the team.
