### ISSUE TITLE
Unable to open PVA bot in Composer

### ISSUE THREAD

**Issue by sarul84** [microsoft/BotFramework-Composer#8887]
## Describe the bug

Sometimes when I try to open PVA bot in composer using "Open in Bot Framework Composer", it just opening composer but not proceeding further.

Sometimes it's asking Azure login but after entering email id nothing happens. If try to use Sign in to your azure account also it's throwing Forbidden error.

## Version

V2.1.1

## Browser

N/A

- [ ] Electron distribution
- [ x] Chrome
- [ ] Safari
- [ ] Firefox
- [x ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by ramfattah** [comment]
Hi @sarul84  -- Thanks, looking into this issue.

**Comment by ramfattah** [comment]
Hi @sarul84, I was able to successfully open the PVA bot in Composer by doing the following:

1) Install **latest** version of Composer. [Download here](https://github.com/microsoft/BotFramework-Composer/releases)
2) Sign-in to [Power Virtual Agents](https://powervirtualagents.microsoft.com/en-us/)
3) Go to the Topics tab on the left navbar and select the down-arrow symbol next to + New topic.

![](https://docs.microsoft.com/en-us/power-virtual-agents/media/composer_openinbotframeworkcomposerbutton_dropdown.png)

Please refer to the official documentation to [Extend your bot with Bot Framework Composer here](https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer#access-bot-framework-composer-from-within-power-virtual-agents).

**Comment by sarul84** [comment]
I am getting below error message sporadically when I try above said option. I am not sure what causes this error. I closed PVA, composer, killed cef browser instances in task manager and waited for 10 mins before trying again. That worked sometime but mostly getting same error, need to logoff / login to make it work again.
 
![image](https://user-images.githubusercontent.com/33111213/149918574-080560ef-dcd6-4d6c-96aa-cfc715a0a66a.png)

**Comment by ramfattah** [comment]
Closing this for now as you were able to make it work after logoff / login. Feel free to re-open if you are still having issues.

**Comment by sarul84** [comment]
@ramfattah - are you saying the steps I mentioned were fix for this? Any plan to investigate further to identify the exact root cause?
