### ISSUE TITLE
Unable to run update-schema.ps1 

### ISSUE THREAD

**Issue by piechk** [microsoft/BotFramework-Composer#8888]
When attempting to add the custom action ([https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions)). The final step of merging the two schema files is failing. 

if I update the script and change "!**/generated" to "!../generated" I am able to remove some errors.  Doing this will remove the first block of errors. 
![image](https://user-images.githubusercontent.com/96060366/148833832-f130351a-0594-4672-9379-9bd7bfd21a8f.png)

I also have removed a orphaned dialog that seems to resolve other issues but still have issues remaining. With the AcsSMSAdapter
![image](https://user-images.githubusercontent.com/96060366/148834026-a0606a2b-c6e7-4821-b0bf-a06114cbfb29.png)

I also attempted to copy from the sample custom action project from here [https://github.com/microsoft/BotBuilder-Samples/tree/main/composer-samples/csharp_dotnetcore/projects/CustomAction/MultiplyDialog](https://github.com/microsoft/BotBuilder-Samples/tree/main/composer-samples/csharp_dotnetcore/projects/CustomAction/MultiplyDialog) This still had the exact same issues with the PowerShell script for merging the custom schema.

**Comment by ramfattah** [comment]
Hi @piechk -- Thanks, looking into it.

**Comment by ramfattah** [comment]
Hi @piechk, 
1) What is your BF Command Line Interface (CLI) version? 
     * type `bf -v` in termal to find bf version
2) I created "Core Bot with Language" in composer(v2.1.1) and followed the [Create custom actions docs here](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions) and I was able to repro this issue. Though, my stack trace error was similar this issue-> #8501

#

I found a [work around here](https://github.com/microsoft/BotFramework-Composer/issues/8501#:~:text=Line%2011%2C%20change%20%22!**/generated%22%20to%20%22!../generated%22%20and%20add%20%22!../dialogs/imported%22) and was able to merge schema successfully.  

* In your bot directory, find the schemas folder, and open `update-schema.ps1`
* Line 11, change "!**/generated" to "!../generated" and add "!../dialogs/imported"

Example
```diff
bf dialog:merge "*.schema" "!**/sdk-backup.schema" "*.uischema" "!**/sdk-backup.uischema" "!**/sdk.override.uischema" "!../generated" "../*.csproj" "../package.json" "!../dialogs/imported" -o $SCHEMA_FILE
```

Try these steps and let me know if this quick work around works for you.

**Comment by piechk** [comment]
I will give this a try. My version is @microsoft/botframework-cli/4.14.1 win32-x64 node-v14.17.5.

**Comment by piechk** [comment]
After attempting PowerShell fix. The error message I received was as follows: 

![image](https://user-images.githubusercontent.com/96060366/150138116-44f4178f-8d9a-4e0c-8f98-ac5e8d90d272.png)

**Comment by ramfattah** [comment]
Closing this issue as similar one is posted here. https://github.com/microsoft/BotFramework-Composer/issues/8501

**Comment by ramfattah** [comment]
@piechk, let's continue this discussion in the issue link above. Also, please list the steps to reproduce the behavior.
