### ISSUE TITLE
Starting bot in Bot Framework Composer 2.1.1 is really slow 

### ISSUE THREAD

**Issue by zsoli** [microsoft/BotFramework-Composer#8889]
Starting the bot in Composer takes a really long time, about 7-8 minutes. Is there a log we could check to see what is taking so long, or is there something we could try to make it build faster? We use the Emulator a lot for debugging. 

Thank you,
Zsolt

**Comment by anishprasad01** [comment]
Unfortunately, large bots simply take time to load in Composer. There isn't really a workaround for this beyond not closing the Composer window. The more content in a bot, the longer it will take.

**Comment by anishprasad01** [comment]
As there is no workaround for this, I'm going to close this issue. If you identify a bug relating to this or have a new problem, please comment or open a new issue as appropriate.
