### ISSUE TITLE
Bot wont publish to Linux, windows works fine.

### ISSUE THREAD

**Issue by drmanhatin** [microsoft/BotFramework-Composer#8890]
## Describe the bug
Bot wont publish to Linux, windows works fine.

## Version
v.2.1.1

## OS

Windows

## To Reproduce

1. Create bot 
2. Deploy to windows
3. Deploy to linux
4. ????
5. No success

## Expected behavior
Deploy succeeds

## Screenshots
```

---
"Accepted for publishing..."
---

---
"Abs settings incomplete, skip linking bot with webapp ..."
---

---
"appPasswordHint incomplete, return ..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"Creating build artifact..."
---

---
"Build artifact ready!"
---

---
"Publishing to Azure ..."
---

---
"Uploading zip file... to linboter"
---

---
"Waiting for zip upload processing."
---

---
"Waiting for zip upload processing. Receiving changes."
---

---
"Waiting for zip upload processing. Building and Deploying '346716b47f384e128e48bed99fafeb69'."
---

---
"Waiting for zip upload processing. Building and Deploying '346716b47f384e128e48bed99fafeb69'."
---

---
"Waiting for zip upload processing. Building and Deploying '346716b47f384e128e48bed99fafeb69'."
---

---
"Waiting for zip upload processing. "
---

---
"Waiting for zip upload processing. "
---

```
etc etc etc

## Additional context
Only "out of the ordinary" thing I am using is a custom adapter.

**Comment by dmvtech** [comment]
Hi @drmanhatin Is this with a C# or Node runtime?

**Comment by ryub3n** [comment]
This issue still exists. I used Node runtime. Works with windows but not with Linux.

**Comment by dmvtech** [comment]
Was able to reproduce issue. Will be linking other issues here and updating with progress.

**Comment by dmvtech** [comment]
Adding log of my repro. 
[error_log_sanitized.txt](https://github.com/microsoft/BotFramework-Composer/files/7961107/error_log_sanitized.txt)

**Comment by dmvtech** [comment]
@benbrown Can you take a look at this one and give some feedback? Any idea who might be a good resource to further investigate or take ownership?

**Comment by tracyboehrer** [comment]
This does appear to be a limitation in the preview version of the JavaScript support in Composer.  Windows is the suggested workaround until this support is GA'd.

**Comment by mgateno** [comment]
Same issue here. Any news on a possible solution?

**Comment by Brankec** [comment]
Same issue here with C# project... Any possible solution? Can I manually deploy this without the use of composer or something?

**Comment by mgateno** [comment]
I was able to make it publish by creating the resources manually and editing the json file with the corresponding information. The wizard seems to fail for some reason.

**Comment by Brankec** [comment]
> I was able to make it publish by creating the resources manually and editing the json file with the corresponding information. The wizard seems to fail for some reason.

Could you please elaborate the steps to do this?

**Comment by mgateno** [comment]
Not at my computer now but using the import option you will be presented with a json template that you will be able to edit to use the information for your subscription, app ID, LUIS resource ID etc

**Comment by Brankec** [comment]
> Not at my computer now but using the import option you will be presented with a json template that you will be able to edit to use the information for your subscription, app ID, LUIS resource ID etc

Oh, that. I am aware of that json file. That is what I'm currently using for windows but it doesn't work for linux deployment. Are there properties that must be filled to work on linux but aren't a necessity on windows? I can also paste you a censored version of my json file.

**Comment by mgateno** [comment]
AFAIK pretty much everything except in the settings section where the App ID is required but the other settings depend on whether or not your bot is using things like LUIS, QNA, Cosmos DB, App Insights, etc. You might double check if you have the correct App ID
![image](https://user-images.githubusercontent.com/20447575/187727512-237ddcbf-9dff-4be1-bc31-fa50e865eb0a.png)

**Comment by mgateno** [comment]
I forgot to mention that you need to delete the sections you are not using from the JSON flie.

**Comment by Brankec** [comment]
> I forgot to mention that you need to delete the sections you are not using from the JSON flie.

I did what you said however I still get the same issue. Here is a censored version of my json file. 
![image](https://user-images.githubusercontent.com/33580274/187859474-839016ba-8533-4481-add5-a8bb5107d9d7.png)

**Comment by mgateno** [comment]
This is my json file

![image](https://user-images.githubusercontent.com/20447575/188154287-d0c2d60d-5e13-4815-b073-5342ed363780.png)
![image](https://user-images.githubusercontent.com/20447575/188154389-f8c3fc8e-d477-4600-a4cd-e3b739d3458c.png)
