### ISSUE TITLE
RootBot throws "Error invoking the skill id: “msAppID” at “messages endpoint” (status is 500)" after successful completion of the invoked skill, when skill becomes a skill consumer.

### ISSUE THREAD

**Issue by rishabh7k** [microsoft/BotFramework-Composer#8891]
## Describe the bug
RootBot throws "Error invoking the skill id: “msAppID” at “messages endpoint” (status is 500)" after successful completion of the invoked skill, when skill becomes a skill consumer. 

## Version

v2.1.1

## OS

- [ ] Windows

## To Reproduce

1. Create TestRootBot and TestSkillBot1,TestSkillBot2
2. Add TestSkillBot2 as skill to TestSkillBot1, and add TestSkillBot1 as skill to TestRootBot.
3. TestRootBot ->TestSkillBot1 -> TestSkillBot2
4. Run TestRootBot, it invokes all skills correctly but throws error status 500 when control hits the TestRootBot

## Expected behavior

TestRootBot successfully calls TestSkillBot1, which later successfully invokes TestSkillBot2, but when control hits back to the TestRootBot, it throws an error status 500, after successfully invoking all the skills. The error is thrown only when the skill becomes a skill consumer, i.e in our case TestSkillBot1 is a skill to TestRootBot and a skill consumer to TestSkillBot2.

## Screenshots

TestRootBot : 

![image](https://user-images.githubusercontent.com/47751904/149127168-79b35ed6-ce2a-4fb2-9e27-ea9a294fad0b.png)

TestSkillBot1 :

![image](https://user-images.githubusercontent.com/47751904/149127367-439910eb-e08a-4182-8c8a-c118c1203bd6.png)

TesSkillBot2 :

![image](https://user-images.githubusercontent.com/47751904/149127501-fbdc7c25-d6e6-42e5-b0af-73460c5e1d30.png)

Error Message, after successful completion of flow of all Bots :

![image](https://user-images.githubusercontent.com/47751904/149128946-f50c513b-dd9d-4a60-befb-7b5d6cec0bcf.png)

## Additional context

If we directly invoke TestSkillBot2 from either TestSkillBot1 or TestRootBot it does not throw any error. But if we call TestSkillBot2 through any skill bot (in our case TestSkillBot1) it throws an error status 500 when control hits TestRootBot.

**Comment by dmvtech** [comment]
Hi @rishabh7k 

I'm assuming that you have configured `allowedCallers` correctly for TestSkillBot1 and TestSkillBot2, correct?

Are all 3 of these published to Azure or somewhere else `public`, or just running locally?

**Comment by rishabh7k** [comment]
Hello @dmvtech 
Yes, the allowedCallers are correctly configured with the right appIDs. if you see the chat screenshot, everything is actually working correctly, TestRootBot invokes TestSkillBot1 which invokes TestSkillBot2, but the moment the control hits back to TestRootBot it throws the error message.

The TestRootBot is running locally and the two skill bots are running on our company's on-premise servers. SkillHostEndpoints of all three bots have also been configured accordingly.

**Comment by rishabh7k** [comment]
Hello @dmvtech 

Is there a temporary work around regarding this issue? Or something we can do from our end in an attempt to fix the error?

**Comment by rishabh7k** [comment]
UPDATE

Deployed TestSkillBot1 and TestSkillBot2 to Azure, TestRootBot is still local. Still gives the same error.

**Comment by dmvtech** [comment]
Thanks @rishabh7k Sorry for the delay. I'm investigating to see I can reproduce and find any workarounds or bugs.

**Comment by rishabh7k** [comment]
Hi @dmvtech 

We have managed to find a workaround for this issue. Turns out if you Prompt a Confirmation/Text/Number etc at the end of the TestSkillBot1 (TestRootBot ->**TestSkillBot1** -> TestSkillBot2), it takes the input for the prompt and returns back to TestRootBot and does not throw the error.

**Prompt in TestSkillBot1:**

![image](https://user-images.githubusercontent.com/47751904/151755853-08cc1936-076d-48c6-b6b3-ac0c22b80207.png)

**Running TestRootBot:**

![image](https://user-images.githubusercontent.com/47751904/151756202-37ba87cb-94c3-4442-a4a1-f8628a010339.png)

This is more of a temporary fix at this point and cannot be applied for all Skill projects that follow a 3 level deep Root-Skill structure. We'd like your assistance to find a conclusive solution for this.

We're open to having this discussion over a Teams or Zoom call if you want more in depth details about this issue.

**Comment by dmvtech** [comment]
hi @rishabh7k 

I have created a root that calls a skill1, which calls a skill2. I am invoking the skills via events. Such as [described in documentation](https://docs.microsoft.com/en-us/composer/how-to-export-a-skill?tabs=v2x#add-an-event-received-trigger). I'll try and see if i can modify to just use begin dialog such as you are and see if that behaves any differently. 

Also; I see you are ending dialogs with 1end dialog1 action, but are the skill dialogs set to auto end as well?

**Comment by rishabh7k** [comment]
Hi @dmvtech 

Yes, I've been using Begin dialog in all my skill bots, it works perfectly without causing any issues. I also rectified the end dialog, by changing Auto End dialog to false. After these changes, it still throws the same error.

**Comment by dmvtech** [comment]
Thanks for your patience @rishabh7k. I am able to reproduce a similar issue, but mine is getting a 401 instead of 500. I'm continuing to troubleshoot and will update when I have findings to share.

**Comment by rishabh7k** [comment]
Hello @dmvtech If you're having trouble reproducing the issue, I can email you a .zip for all three bot projects and you can deploy them and test it.

**Comment by dmvtech** [comment]
Hi @rishabh7k Apologies for the delay. I have a repro, but if you wouldn't mind sharing a .zip (or just adding them all to a repository on github), that might be useful too. 

Can you also **_test_** by setting allowed callers to allow any?
```json
      "allowedCallers": [
        "*"
      ]
```

**Comment by rishabh7k** [comment]
Hello @dmvtech , I've added all the three bot projects to my repo at https://github.com/rishabh7k/testskillbots . You can use these to reproduce the error.

**Comment by rishabh7k** [comment]
> Thanks for your patience @rishabh7k. I am able to reproduce a similar issue, but mine is getting a 401 instead of 500. I'm continuing to troubleshoot and will update when I have findings to share.

About the error 401 you're facing, try adding the TestRootBot appId in skillsConfig of TestSkillBot1 as shown in the image below.

**appsettings.json of TestSkillBot1:**
![image](https://user-images.githubusercontent.com/47751904/157923586-bb9beb6d-9869-4ac2-ae4f-82645f29cc84.png)

**Comment by gabog** [comment]
Hi @rishabh7k, in the current implementation, composer bots can either be skill consumers or skills but they can't be both, so the scenario you are trying to test won't work reliably and is not supported. Sorry for the inconvenience.
