### ISSUE TITLE
Bot Framework composer is not accepting custom question answering as QNA

### ISSUE THREAD

**Issue by puhakju** [microsoft/BotFramework-Composer#8896]
## Describe the bug
As i am opening new project "Core bot with QNA Maker" and inserting QNA maker subsription key i get error :
**Sorry, something went wrong with publishing. Try again or exit out of this task.

Qnamaker build failed: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.****

I try to connect to existing azure resource(language) that i have already made and i get error. 

<img width="504" alt="image" src="https://user-images.githubusercontent.com/1107553/149318578-5f17bb65-ce46-4b93-904e-f11545c1817a.png">

also i cannot create "old" qna service anymore in https://www.qnamaker.ai/ 

## Version

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to configure bot
2. Click on Set up Qna maker
3. Scroll down to azure and connect to existing service language service

## Screenshots
<img width="435" alt="image" src="https://user-images.githubusercontent.com/1107553/149319092-0aab3f0e-c168-4604-8de7-48a5b04502ab.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/1107553/149319136-69b20e11-ef12-4e14-ab7d-d89ff83ed807.png">
<img width="935" alt="image" src="https://user-images.githubusercontent.com/1107553/149319345-b75adad2-2569-41e5-a966-501b72fc5394.png">

**Comment by tdurnford** [comment]
Hello @puhakju and thank you for engaging with the Composer project. We'll take this issue as a feature request and add it to the backlog for prioritization. We do not have an ETA at this time for when this feature will be available.
