### ISSUE TITLE
How to pass dynamic values in header and body for "Send and Http request" action in composer.

### ISSUE THREAD

**Issue by tushaar9027** [microsoft/BotFramework-Composer#8897]
I am trying to call microsoft translator service and i am storing user text in dialog.userquery but in post request  body 

{"text" : ${dialog.userquery}}

Its not accepting this.....please help

**Comment by FANMixco** [comment]
You need to choose `string` and later, you configure the **JSON** in the **Response type**:

<img width="342" alt="Screen Shot 2022-01-16 at 17 29 32" src="https://user-images.githubusercontent.com/1666156/149668771-5b3c3084-7bff-415e-bd5f-c493b5750d71.png">

**Comment by tushaar9027** [comment]
Hi FanMixco , i was able to apss the variables after changing the body type to json object that was the issue. Selecting body as string was the issue actually
