### ISSUE TITLE
ChannelData set in composer not coming in directline recieve activity

### ISSUE THREAD

**Issue by tushaar9027** [microsoft/BotFramework-Composer#8903]
## Describe the bug
I need to send channeldata from composer to directline receive activity so far if i try setting channeldata like this it is available in composer but no received in receive activity of channel data

Tried implementing like this but it didn't help
turn.activity.channelData.eoc = false

## Version
composer 2.1.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior
Channel Data should be available in bot responses in  directline recieve activity as it is available in sdk first bot when queried using directline api

**Comment by dmvtech** [comment]
Hi @tushaar9027 

> I need to send channeldata from composer to directline receive activity so far if i try setting channeldata like this it is available in composer but no received in receive activity of channel data

My apologies; can you please clarify on what you are attempting to accomplish and what the need is? Is this using Webchat as a client or a custom directline client? Can you clarify on what you mean by `directline receive activity` ?

**Comment by tushaar9027** [comment]
> 

Hi Dmvtech , 

there is a custom node web app i have created in azure in which i am trying to get the chatbot responses using the directline  api ...this custom connector connects further to a third party vendor....

By Directline recieve activity i mean this http request to get bot responses using directline
https://directline.botframework.com/v3/directline/conversations/${convid}/activities?watermark=${watermark}

where convid and watermark will dynamically inserted based on what is stored in azure storage.

The response i get from directline api is 
Recieve Activity Response Activities :  [
  {
    type: 'message',
    id: 'am1bVupNuGFcYF0Yw9RCy-eu|0000000',
    timestamp: '2022-01-23T04:28:12.6439381Z',
    serviceUrl: 'https://directline.botframework.com/',
    channelId: 'directline',
    from: { id: 'tushar.arora@example.com' },
    conversation: { id: 'am1bVupNuGFcYF0Yw9RCy-eu' },
    text: 'weather',
    sessionID: '4f58aced-8627-4daf-b523-6acfe0295468',
    messageId: '72d8898f-97fb-4e7f-87a7-59ad95f553c68'
  },
  {
    type: 'message',
    id: 'am1bVupNuGFcYF0Yw9RCy-eu|0000003',
    timestamp: '2022-01-23T04:28:24.1074588Z',
    channelId: 'directline',
    from: { id: 'ComposerDemo1', name: 'ComposerDemo1' },
    conversation: { id: 'am1bVupNuGFcYF0Yw9RCy-eu' },
    text: 'Please enter the city,country ?',
    speak: 'Please enter the city,country ?',
    inputHint: 'expectingInput',
    replyToId: 'am1bVupNuGFcYF0Yw9RCy-eu|0000000'
  }
]


you see in the second activity this is response from composer bot we can see the input hint but there is channeldata property in the response but in bot i have set the **turn.activity.channelData.eoc = true** 

![image](https://user-images.githubusercontent.com/10369409/151040234-3aee7a42-b68b-4830-b9c6-085b65c63601.png)

**Comment by dmvtech** [comment]
You won't be able to set the channelData properties from Composer. ChannelData is normally handled by the channel (`Channel=>Bot`. Not `Bot=>Channel`). So that the bot has information about the channel, and can handle certain logic per channel. 

> with v3 version and the channeldata was coming in bot responses recieved from directline endpoint

Your bot was _sending_ channelData to a directline client?

**Comment by EricDahlvang** [comment]
It is possible to send channel data from composer with a structed lg template:

![image](https://user-images.githubusercontent.com/11055362/152034227-9cd04c50-540e-4b83-82c9-d4de3e445c38.png)

![image](https://user-images.githubusercontent.com/11055362/152034302-31f36f83-d8f6-4b81-a662-7fa494ab0a5d.png)

If the goal is to send channel data with every outgoing message from the bot, this could be accomplished with a middleware component hooking into all outgoing activities.

**Comment by dmvtech** [comment]
Thanks @EricDahlvang I didn't even think of that. @tushaar9027 Let us know if that works for you.

**Comment by tushaar9027** [comment]
Hi  @EricDahlvang , Thanks for providing with the approach , i will try this out give me a couple of days will check and let you guys know if the approach also works with directline recieve activity end point.

By the way is there any good video for explaining how to implement middleware for composer in node js . Official documentation explains it with c#

**Comment by dmvtech** [comment]
@tushaar9027 

> By the way is there any good video for explaining how to implement middleware for composer in node js . Official documentation explains it with c#

I don't know of any off-hand, but I will take a look to see if I can find anything. As you know, Node JS runtime for Composer bots is in preview. At this point, there is no current ETA set for moving to GA.

**Comment by dmvtech** [comment]
I'm closing this as it seems you have an appropriate solution for setting the channelData from within Composer. I wasn't able to find any examples of implementing middleware within Composer node runtime.
