### ISSUE TITLE
Error while publishing a bot from Bot Framework Composer in a Linux env

### ISSUE THREAD

**Issue by FANMixco** [microsoft/BotFramework-Composer#8915]
## Describe the bug

I'm having issues when I am using my existing resources and publishing my bot to a **Linux env** because it is failing with the below error:

> "DEPLOY_ZIP_ERROR - There was a problem publishing bot assets (zip deploy)."

## Version

v2.1.1 and  v2.1.1-nightly.285734.f5208f0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Publish'
2. Click on 'Publishing Profile'
3. Click on 'Add new', provide Name, and select "Publish to Azure" as publishing target.
4. Click 'Next'
5. Select 'Import existing resources'
6. Click 'Next'
7. Add existing resources
8. Click 'Import'
9. Go to 'Publish'
10. Select Bot
11. Click' 'Publish selected bots'

## Expected behavior

The bot should be published on Azure even if it takes over an hour. As an alternative, it should provide a message of how to publish it manually or through another tool.

#### v2.1.1

<img width="1280" alt="Screen Shot 2022-01-15 at 23 07 13" src="https://user-images.githubusercontent.com/1666156/149639177-28c750c3-c408-4aea-9900-8ba747caedbb.png">

<img width="1280" alt="Screen Shot 2022-01-15 at 23 04 39" src="https://user-images.githubusercontent.com/1666156/149639116-9ec04277-e4a5-45b7-907c-e395ca7e6949.png">

### v2.1.1-nightly.285734.f5208f0

<img width="1280" alt="Screen Shot 2022-01-16 at 00 30 23" src="https://user-images.githubusercontent.com/1666156/149641064-5301d706-9d2a-4618-b8d2-3c22b0701ce8.png">

<img width="1280" alt="Screen Shot 2022-01-16 at 00 30 35" src="https://user-images.githubusercontent.com/1666156/149641070-ee157c62-bc1b-4eee-ba0e-a58d9b0f2554.png">

<img width="1280" alt="Screen Shot 2022-01-16 at 00 30 41" src="https://user-images.githubusercontent.com/1666156/149641073-0a9635c3-49ad-46f6-be2d-52ea21469514.png">

## Additional context

1. I'm not using any VPN or special network configuration. The latest was on my personal Mac and network.
2. I have tried in two different networks with the same error.
3. It takes over an hour to throw the error. **It should take less than an hour ideally.** There should be some feature that double-checks that after X time something might be suspicious or wrong.
4. It has been reported more than once without any solution and just closed because of "inactivity".
    - https://github.com/microsoft/BotFramework-Composer/issues/8613
    - https://github.com/microsoft/BotFramework-Composer/issues/8707
5. The same bug happens in the latest nightly build: [2.1.1-nightly.285734.f5208f0](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/download/v2.1.1-nightly.285734.f5208f0/BotFramework-Composer-2.1.1-nightly.285734.f5208f0-mac.zip)
6. **It works in Windows.**

**Comment by dmvtech** [comment]
Hi @FANMixco 

- Is this a C# bot or Node?
- Are you publishing to a Linux or Windows app service plan?
- Are you using a Multi tenant bot or a Single tenant?

**Comment by FANMixco** [comment]
Hi @dmvtech ,

Since it's 100% created by composer, I can see the following:
- C#
- Linux
- Single tenant

All were created by the Composer.

**Comment by FANMixco** [comment]
Hi @dmvtech, I found the issue is when you deploy it to a **Linux** env, I was able to deploy it to Windows.

**Comment by dmvtech** [comment]
Able to reproduce. Closing in lieu of #8890. Please monitor there for progress.
