### ISSUE TITLE
Failing pipeline buildAndDeployModels.yaml stage @"Publish LUIS" 

### ISSUE THREAD

**Issue by 462sai** [microsoft/BotFramework-Composer#8918]
Hi Team,

please, help us on below

We are facing issue while publishing the LUIS via the pipeline. Encountering error in the Azure DevOps pipeline as below

"no such file or directory, stat '/home/vsts/work/1/Build-LUIS.ps1"

Note:  we have fallowed the https://docs.microsoft.com/en-us/composer/how-to-cicd documentation for configuration

attached the screen shot for the yaml folder structure
![Yaml-files](https://user-images.githubusercontent.com/82943451/149964275-27e7185f-0f99-4fce-884f-24f4e90a06c9.PNG)

Regards,
Saiprasad.

**Comment by saikumaru** [comment]
can you please share the logs of the step that failed?

This folder path`/home/vsts/work/1/`
is equivalant to your base folder of your repo, so you need to provide a precise path where the powershell script lies.

Wherever it failed, this would be a better way to have accessed that script.
`/home/vsts/work/1/build/yaml/templates/Build-LUIS.ps1`

**Comment by saikumaru** [comment]
The documentation provided is not the best one. But you most probably messed up at the place where you are assigning your variables- ProjectDirectory and Projectname

@EricDahlvang - it would be great if you can unmask the data assigned to the variables on pipeline. It gets tricky for a first timer to figure it out from the document.
https://docs.microsoft.com/en-us/composer/how-to-cicd#create-the-pipeline
![variables 1](https://user-images.githubusercontent.com/44021002/150358337-c25701b7-01bb-4916-80fc-f82399f85c6c.png)

**Comment by dmvtech** [comment]
@462sai Please confirm the config per @saikumaru suggestion above and share logs.

@saikumaru That is a great suggestion (have bogus/sample values to see what they might look like or formatted). Please suggest such a change on the documentation page (at the bottom; `Feedback for this page`).

**Comment by dmvtech** [comment]
@462sai Are you still having issues with a failed pipeline? Did any of the suggestions above help at all?

**Comment by dmvtech** [comment]
Closing assuming it is resolved. Please comment or reopen if further assistance is still needed.
