### ISSUE TITLE
Dynamic multiple choice from an Array

### ISSUE THREAD

**Issue by sarul84** [microsoft/BotFramework-Composer#8919]
I am getting Multi choice (Hero card) as a dynamic array and the array is in below format. I tried to extract options value from this json for array of choice.

```
{
	  "lgType": "Activity",
	  "text": [
		{
		  "options": "Microsoft"
		},
		{
		  "options": "IBM"
		},
		{
		  "options": "Google"
		},
		{
		  "options": "Facebook"
		},
		{
		  "options": "Something Else"
		}
	  ]
	}
```

The below expression is not giving me an empty values. Please help me on this.

```
=flatten(foreach(where(json(conversation.init_json), x => x.key == "text"), item => foreach(item.value, choice => choice.value)))
```

**Comment by dmvtech** [comment]
Hi @sarul84 Just to be clear; you are _only_ getting null/empty values. You do actually want to retrieve the values (`Microsoft`, `IBM`, etc), correct?

**Comment by dmvtech** [comment]
You just need to change `choice.value` to `choice.options`. `choice` is an object, not an array.

```
=flatten(foreach(where(json(conversation.init_json), x => x.key == "text"), item => foreach(item.value, choice => choice.options)))
```

**Comment by sarul84** [comment]
Thank you so much @dmvtech. It did magic.
