### ISSUE TITLE
Bot Framework Composer can't find Node.js (Ubuntu)

### ISSUE THREAD

**Issue by seredenkov** [microsoft/BotFramework-Composer#8921]
## Describe the bug

Bot Framework Composer requires the installation of Node.js, but the Node.js is installed.

## Version

Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [x] Ubuntu

## To Reproduce

1. Go to 'Home'
2. Click on 'Create new'
3. See error

## Expected behavior

use the existing Node.js and don't show the error message

## Screenshots

![image](https://user-images.githubusercontent.com/1897946/150112673-76fe228f-3e8b-489d-aa0c-cc38d5d0dc01.png)

**Comment by seredenkov** [comment]
as it turned out, error only when using `nvm`
if we don't use `nvm`, then the `Composer` works fine.

But I would like, of course, that the use of `nvm` does not cause problems for the `Composer`

**Comment by anishprasad01** [comment]
Hi @seredenkov,

Just to confirm, did you select the node version using the command `nvm use`? I have Node v14.18.2 installed using nvm and I haven't had any issues getting Composer to create a new bot.

**Comment by seredenkov** [comment]
> did you select the node version using the command nvm use

Hello, @anishprasad01 
Yes, I did it.

>  I have Node v14.18.2 installed using nvm

 maybe, in addition to nvm, you also have node.js installed in the usual way?

**Comment by anishprasad01** [comment]
I've confirmed that I did not. I've only installed it in Ubuntu via `nvm`. Have you tried uninstalling all Node installs and then installing via `nvm`?

**Comment by seredenkov** [comment]
No, I haven't tried it, I don't see the point in it (because it was possible to succeed without deleting nodes)
The issue was that while the correct version of node was installed and selected in `nvm`, the composer still did not see this node.
After I installed the node without nvm, the composer worked correctly.
