### ISSUE TITLE
Ability for multiple users to edit the bot without overrides

### ISSUE THREAD

**Issue by saikumaru** [microsoft/BotFramework-Composer#8924]
## Describe the solution you'd like
We would expect the composer bot to be editable by multiple people.
The bot once published to the portal should be possible to be retrieved by 2nd or other team member before she/he updates her/his changes.

## Describe alternatives you've considered
GIT or any SCM tool to be used for pulling a latest copy
Carefully publish only after being sure of a latest commit on local composer

## Additional context
I have seen issues being tracked for multi user, but it isnt clear as to how this feature has to be used or whether they are completely implemented yet
https://github.com/microsoft/BotFramework-Composer/issues/1330
https://github.com/microsoft/BotFramework-Composer/issues/1916

@benbrown @cwhitten @hibrenda - appreciate your inputs please

**Comment by EricDahlvang** [comment]
Hi @saikumaru 

This functionality is currently available in Power Virtual Agents:

https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer
https://docs.microsoft.com/en-us/composer/pva/overview-composer-pva

**Comment by saikumaru** [comment]
Thank you @EricDahlvang .
This kind of limits the usage of composer tool for low-code users. We know composer is much more powerful and flexible than PVA, and this feature will allow a greater embracement of this and to scale the bot seamlessly.

We could well use composer just as an IDE, but unfortunately every edit causes an override to remote NLU/QnA models. So, as a resolution at least please consider adding documentation on "good practices for collaborative development" using composer.
