### ISSUE TITLE
Missing app registration on Composer Publish

### ISSUE THREAD

**Issue by rajeshdagdevir** [microsoft/BotFramework-Composer#8925]
Missing app registration on Composer Publish

Hello again.
I have encountered very nasty bug.
When I publish bot via composer all resources get created as intended. Bot gets app id and app pasword and it works perfect. Now i tried to add further functionality like key vault. for that I need to add my bot app to keyvault policy. but app registration cannot be found. i am in correct aad or tenant, app registrations is completely empty. furtemore, if I press on "manage" above app id in azure bot configuration window it takes me to page Not found | Certificates & secrets and says "The application was not found. If the application was just created, wait a few minutes and refresh the page. [z/kxNKcCTREsLLA0iZdC/P]"

what can I do? i uninstalled composer and everything reinstalled. same problems.
also, when I create new ressources, i deselect all optional resources, but for some reason he still creates app insight despite me unclicking app insights.

## Version

2.1.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

no idea if someone can reproduce

## Expected behavior

i expect app id or registration to be found in azure so i can modify options like secrets.

**Comment by ramfattah** [comment]
Hi @rajeshdagdevir -- let's do the following steps:

1) Confirm if you are in the correct Azure directory.
     <img src="https://i.imgur.com/5Piqx0c.png" alt="" width="400"/>

2) In Azure Portal, go to Azure Active Directory, on left navbar click 'App registrations' and check if your app is listed.

**Comment by ramfattah** [comment]
Hi @rajeshdagdevir -- let's do the following steps:

1) Confirm if you are in the correct Azure directory.
     <img src="https://i.imgur.com/aykrKRN.png" alt="" width="400"/>

2) In Azure Portal, go to Azure Active Directory, on left navbar click 'App registrations' and check if your app is listed.

**Comment by rajeshdagdevir** [comment]
hello.
i am in the right aad. i checked everything and reg is missing.
I somewhat fixed it by creating new registration and bot registration myself so it work for now.
quick different question. what is difference between skill bot and custom action? doesnt do both the same thing?

**Comment by ramfattah** [comment]
Hi @rajeshdagdevir, glad you were able to find a fix.
#

What is difference between skill bot and custom action:
1) **Skill** is a dialog type that allows bot-to-bot communication. Ex: Your bot can directly call on the functionality of another bot. 
     * [Documentation on Skill here](https://docs.microsoft.com/en-us/azure/bot-service/skills-conceptual?view=azure-bot-service-4.0)
2) **Custom Actions:** In Composer, besides these built-in actions such as **Send a response, Ask a question, and Create a condition.** Additional actions can be added through packages or by creating components that includes custom actions.
     * [Documentation on Custom Actions here](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions)

I am closing this one for now, feel free to re-open if you are still having issues.
