### ISSUE TITLE
Is there any way to implement list cards in bot composer?

### ISSUE THREAD

**Issue by BhagyashreeC-Hexaware** [microsoft/BotFramework-Composer#8933]
Hi, I am trying to implement list cards in bot composer as we are having this type of card implementation in MS teams, is there any way to implement list cards in bot composer?
List card provides functionality like scroll bar, etc. is there any alternative for similar to list card?

Sample List Card
{
      "contentType": "application/vnd.microsoft.teams.card.list",
      "content": {
        "title": "Manage your sevice desk related activities here.",
        "items": [
          {
            "type": "resultItem",
            "title": "Incident",
            "subtitle": "",
            "tap": {
              "type": "imBack",
              "value": "Incident"
            },
            "icon": "{{url}}"
          },
          {
            "type": "resultItem",
            "title": "Service Request",
            "subtitle": "",
            "tap": {
              "type": "imBack",
              "value": "Service Request"
            },
            "icon": "{{url}}"
          },
          {
            "type": "resultItem",
            "title": "Home ",
            "subtitle": "",
            "tap": {
              "type": "imBack",
              "value": "Home"
            },
            "icon": "{{url}}"
          }
        ]
      }
    }

![listcard](https://user-images.githubusercontent.com/68320411/150916013-54c61731-086e-4f9b-8f58-7125e94c68e0.png)

List card with scroll bar, image and title
![image](https://user-images.githubusercontent.com/68320411/150916185-9bdc2e20-5d15-485f-af91-57f8a41c9227.png)

Our requirement is:
1)List card should contain items like title and image
2)Action should happen when we click on the item 
3)Need scroll bar if the items are more than the adaptive card height

**Comment by stevkan** [comment]
Closing as resolved.
