### ISSUE TITLE
Unable to deploy Published bot

### ISSUE THREAD

**Issue by prajwal-ainapur** [microsoft/BotFramework-Composer#8939]
I had few permission related issues due to my account being a one from organization. So decided to make use of "Import using existing resources". Please find the .json below that was used to create the publishing profile.
```json
{
  "name": "convAISubAuto",
  "environment": "dev",
  "tenantId": "TENANT_ID",
  "hostname": "subAutoConvAI", #Same as azure bot name
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "chatbot",
  "botName": "subAutoConvAI", #Same as azure bot name
  "subscriptionId": "SUB_ID",
  "region": "westus",
  "appServiceOperatingSystem": "windows",
  "scmHostDomain": "",
  "luisResource": "convAIBoth",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "",
      "connectionString": ""
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "",
      "authKey": "",
      "databaseId": "botstate-db",
      "containerId": "botstate-container"
    },
    "blobStorage": {
      "connectionString": "",
      "container": ""
    },
    "luis": {
      "authoringKey": "***",
      "authoringEndpoint": "***",
      "endpointKey": "***",
      "endpoint": "***",
      "region": "eastus"
    },
    "qna": {
      "subscriptionKey": "***",
      "endpoint": "***"
    },
    "MicrosoftAppId": "APP_ID", #Taken from Azure bot configurations screen
    "MicrosoftAppPassword": "***" #Taken from secret generated during app registration
  }
}
```
The bot is getting published successfully. However, when i click on "Test in Web Chat" option inside the Azure Bot Resource, i am getting blank screen.

Also, inside the configuration for Azure bot... The endpoint mentioned was https://host_name/api/messages. I had to mention it as the field was blank.

Is there any issue with my publishing profile's JSON file?

**Comment by dmvtech** [comment]
@prajwal-ainapur I don't see anything apparent with your provisioning settings. I am investigating some other publishing issues and will link if we find they are the same issue. Do you know what type of app your bot is? (multitenant, singletenant or user-assigned managed identity)

**Comment by dmvtech** [comment]
@prajwal-ainapur 

Just to confirm, in the publishing pane of Composer you see success such as:
![image](https://user-images.githubusercontent.com/43397658/151633767-2d9b4645-bf46-4eb5-92f0-254a30b2c009.png)


But the messaging endpoint for the bot configuration was blank and the bot does not respond at all (Test in Web Chat)?

**Comment by dmvtech** [comment]
Hi @prajwal-ainapur Do you still need assistance?

**Comment by dmvtech** [comment]
Closing due to lack of response. If you still need assistance, please comment and we can reopen and continue.
