### ISSUE TITLE
Get this error when trying to create new Enterprise Assistant Bot

### ISSUE THREAD

**Issue by Markyboy944** [microsoft/BotFramework-Composer#8944]
## Describe the bug

When trying to create a new Enterprise Assistant Bot, it fails with the following error:

Error hit when instantiating remote template: C:\Users\mhard\AppData\Roaming\BotFrameworkComposer\.yo-repository\node_modules\@microsoft\generator-bot-enterprise-assistant\generators\app\templates\botName.sln:6 4| VisualStudioVersion = 16.0.30503.244 5| MinimumVisualStudioVersion = 10.0.40219.1 >> 6| Project("{<%= projectType %>}") = "<%= botName %>", "<%= botName %>\<%= botName %>.csproj", "{<%= botProjectGuid %>}" 7| EndProject 8| Project("{<%= projectType %>}") = "Calendar", "Calendar\Calendar.csproj", "{<%= calendarProjectGuid %>}" 9| EndProject projectType is not defined

## Version

V2.1.1. of composer

## OS

Windows 10

## To Reproduce

Do "Create New"
Choose the "Enterprise Assistant Bot" template
I change the name, but keep the default "Azure Web App"
I have tried various folder locations, including c:\ but they all fail

**Comment by ramfattah** [comment]
Hi @Markyboy944 -- thanks, looking into this issue.

**Comment by ramfattah** [comment]
Looks like this is a known bug. Closing this issue. Let's continue this here #8927
