### ISSUE TITLE
"Send task module URL response" is showing blank screen

### ISSUE THREAD

**Issue by BhupathiK-Hexaware** [microsoft/BotFramework-Composer#8947]
Hi, I am trying to implement task module in bot composer. I have installed the bot-components-teams package.
 
![image](https://user-images.githubusercontent.com/87963223/151490080-c53efd02-71ec-4beb-be7f-4cee9d94cf87.png)

I am using the “On task module fetch” trigger to implement the task module. In that I am using the “send task module as a url response”
 
![image](https://user-images.githubusercontent.com/87963223/151490103-16de1fb1-7682-469a-aaef-e846d849cac2.png)

Here are the configuration which I am setting:
 
![image](https://user-images.githubusercontent.com/87963223/151490129-eae3c328-64db-4246-a4e5-9804bb26f0a9.png)

First I wanted to show a static url and I have white listed the domain details in the manifest as I am using MS teams to test the task module.
 
![image](https://user-images.githubusercontent.com/87963223/151490150-4fa3c295-2e0d-484e-9deb-c47e3242b721.png)

After doing all those things also I am getting the empty Task Module.
![image](https://user-images.githubusercontent.com/87963223/151495454-5e0a360b-925f-4aed-8a68-c1565966d82d.png)

I was trying to implement a dynamic URL. We are using encodeURIComponent() in our code, how to encode the URL in bot composer?

**Comment by ramfattah** [comment]
Hi @BhupathiK-Hexaware, I'm investigating this issue.

**Comment by ramfattah** [comment]
@BhupathiK-Hexaware 

Thanks for your patience, have you tried using "[uriComponent](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#uricomponent)" to encode the url?

**Comment by selvaduraiece** [comment]
@ramfattah  - I tried passing uriComponent but no luck 
![image](https://user-images.githubusercontent.com/40558980/156048992-0345ef27-8b82-4e0c-9732-ce3f47afe687.png)
