### ISSUE TITLE
Interruption handling in 'QnAMaker dialog' 

### ISSUE THREAD

**Issue by JayHB1** [microsoft/BotFramework-Composer#8948]
Hello, 
We have a built-in 'QnAMaker dialog' in composer to configure knowledgebase. 
![image](https://user-images.githubusercontent.com/91305025/151495930-6646abcb-0eb1-4430-a1cf-094118c18607.png)
If there is a multi turn question in knowledgebase,  'QnAMaker dialog' displays all the follow up prompts in the chat window. But instead of clicking on any of the follow up prompt, if user types some other question then bot is not considering it as an interruption. It should now search for luis at the root level but bot is directly showing the answer 'Sorry, I did not find an answer'. It seems that bot is still in 'QnAMaker dialog' only and is not interrupted. 
Can we handle this kind of interruption for 'QnAMaker dialog' in case of a multi turn question in knowledgebase. Also, after completing interruption it should not resume from where it left and should not show original qna follow up prompts in the chat window.

Also, as a workaround to handle the interruption, rest api i.e. qnamaker generate answer api can be used. For 'QnAMaker dialog', telemetry gets logged automatically in the app insights just by providing instrumentation keys in the settings file. But if we use rest api instead of 'QnAMaker dialog', then can we log the qna maker related telemetry in the app insights using default telemetry settings. 

Also, can we send a custom question to 'QnAMaker dialog', by storing question in a property like in turn.activity.text.

Thank you.

**Comment by dmvtech** [comment]
Hi @JayHB1 

Using the QnAMaker action/dialog, you will only be able to query a QnA maker with a specific question.  This is a very simple and straightforward implementation and is often just used in the Unknown intent trigger to handle something that is not already handled elsewhere in the bot logic.
That is what you have setup, but here is info on that for clarity:
https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot?tabs=v2x

If you want to have a more robust implementation of QnA (with or without LUIS) and be able to have interruptions, etc, then you will need to author and provision the KB from within Composer itself. An example can be seen by creating a new bot using the `Core Bot with QnA Maker` template. You can also find more info here:
https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb?tabs=v2x

These are 2 different and separate approaches to using QnAMaker. 

> Also, can we send a custom question to 'QnAMaker dialog', by storing question in a property like in turn.activity.text.

If you are referring to the [QnA custom question answering feature](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/custom-question-answering) that is in _preview_, then that is not yet supported in the bot framework. That being said, you can use stored properties to send to QnA maker with either of the above scenarios or through using an HTTP action.

**Comment by dmvtech** [comment]
Hi @JayHB1 I hope the above explanation helps with your question. I am going to close this, but if you have further questions or I misinterpreted the issue/question, please comment and I will reopen if needed.
