### ISSUE TITLE
Dialog names in Power BI template for App insights telemetry for a bot created in Bot Composer

### ISSUE THREAD

**Issue by JayHB1** [microsoft/BotFramework-Composer#8949]
Hello,

We have a bot created in Bot composer and default telemetry is enabled by providing app insights instrumentation key.
We have a sample Power BI template to use for bot analytics as provided in below url. 
https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/
After configuring Power BI template, it seems that there is junk data getting logged in the report such as dialog names are not valid. Please find below screenshot for the reference. 
![image](https://user-images.githubusercontent.com/91305025/151506900-bec645b6-67c3-4e2c-be5b-5064353edd04.png)
![image](https://user-images.githubusercontent.com/91305025/151506947-ce9ad888-bb39-4577-b16c-a02e898c1203.png)

As shown in above image, if else conditions, property names, send activities etc are appearing in dialog names list. 
This issue was not there when bot was created using virtual assistant template. 
Is there any difference in default telemetry data logging for bot created in composer vs bot created using sdk.

Thank you.

**Comment by dmvtech** [comment]
Hi @JayHB1 

> As shown in above image, if else conditions, property names, send activities etc are appearing in dialog names list.

Yes, in adaptive dialogs, those things (actions) are also dialogs. There is nothing in the runtime that will filter out logging those versus other dialogs.

> This issue was not there when bot was created using virtual assistant template.

Yeah, it was not using adaptive dialogs.

> Is there any difference in default telemetry data logging for bot created in composer vs bot created using sdk.

Yes. Well, kind of. Composer is using adaptive dialogs (declarative). You can create code-first bots using adaptive dialogs (no longer recommended), and those will have the same behavior. A code-first bot using the SDK and legacy/waterfall dialogs will not.

Our recommendation is altering the Application Insights query to filter out the information you do not wish to have surfaced.
