### ISSUE TITLE
Unable to sign in with Azure Account in Bot Framework Composer

### ISSUE THREAD

**Issue by nityakalyan** [microsoft/BotFramework-Composer#8952]
Hi 

I am able to log in to my azure account in portal.azure.com successfully and have an Active Azure Directory.

While I was trying to log in using my Azure account in Bot Framework Composer, I get the below error

"Sign in failed: No Azure Directories were found"

![image](https://user-images.githubusercontent.com/36395514/151783726-c24d810c-b5fe-4138-9cd0-8a4f63ef43e7.png)

Could you please help me what could be the possible reason

**Comment by anishprasad01** [comment]
Hi @nityakalyan,

Could you tell us a bit more about you situation?

- What OS are you running?
- Do you have more than one Azure directory connected to your account?
- Are you behind a proxy or any other middleware that might be interfering?
- What type of account is this? (Work or school?)

**Comment by nityakalyan** [comment]
Hi Anish

- I am running on Windows 10

- Yes, I have two Azure directories connected to my account. I tried to switch to both of these directories at a time and checked but the same issue occurs again

- Yes

- Its a 'work' account

Thanks
Kalyan
