### ISSUE TITLE
Composer bot not deploying to azure with orchestrator(intent) as recognizer

### ISSUE THREAD

**Issue by tushaar9027** [microsoft/BotFramework-Composer#8964]
## Describe the bug
While deploying the composer bot built in node js  to azure with orchestrator package installed i get this error.

Error got :-  Error: EPERM: operation not permitted, unlink 'D:\CDS\MySupportComposerDev\MySupportComposerDev\node_modules\@microsoft\orchestrator-core\onnxruntime.dll'

## Version
Bot Framework Composer v2.1.1-nightly.289561.47e9e4b

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
Windows 11

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior
The bot should be successfully deployed to Azure without any error like in other recognizers.

## Screenshots

![image](https://user-images.githubusercontent.com/10369409/152411683-2b73c755-4104-4821-886c-b04ac25cee20.png)

**Comment by msomanathan** [comment]
@dmvtech Could you please check if this issue is similar to the other issues you are looking into composer? Thanks!

**Comment by dmvtech** [comment]
Hi @tushaar9027 

I wasn't able to reproduce this (I can share my steps).

- Are you deploying to a Windows or Linux app service plan?
- What version of the BF cli are you using? (`bf -v`)
- Did you provision the resources through Composer or externally?

**Comment by dmvtech** [comment]
I realized my testing was poor. I made changes and am now getting a _**different**_ error:


```
---
"Accepted for publishing..."
---

---
"Linking bot with webapp ..."
---

---
"appPasswordHint incomplete, return ..."
---

---
"Building the bot app..."
---

---
"{\"stack\":\"Error: Error: [2022-02-08T22:01:20.190Z] ERROR-MESSAGE: \\\"LabelResolver.addBatch(): Failed adding error:\\\", error={}\\n    
at Builder.<anonymous> (C:\\\\Users\\\\<USERPROFILE>\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar\\\\node_modules\\\\@bfc\\\\server\\\\build\\\\models\\\\bot\\\\builder.js:88:27)\\n    
at Generator.throw (<anonymous>)\\n    
at rejected (C:\\\\Users\\\\<USERPROFILE>\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar\\\\node_modules\\\\@bfc\\\\server\\\\node_modules\\\\tslib\\\\tslib.js:112:69)\",\"message\":\"Error: [2022-02-08T22:01:20.190Z] ERROR-MESSAGE: \\\"LabelResolver.addBatch(): Failed adding error:\\\", error={}\"}"
---

---
"Error - Error: [2022-02-08T22:01:20.190Z] ERROR-MESSAGE: \"LabelResolver.addBatch(): Failed adding error:\", error={}"
---
```

I'll continue investigation. If you can confirm the BF cli version, that would be great.

**Comment by pramodphamax** [comment]
![Orchestrator](https://user-images.githubusercontent.com/87850728/153444327-71f4d20a-418a-4037-94b9-76be9816bbc7.PNG)
The code works on local; When deployed to azure it Application has thrown an uncaught exception and is terminated:
Error: \\?\C:\home\site\wwwroot\node_modules\botbuilder-ai-orchestrator\node_modules\@microsoft\orchestrator-core\orchestrator-core.node is not a valid Win32 application.

\\?\C:\home\site\wwwroot\node_modules\botbuilder-ai-orchestrator\node_modules\@microsoft\orchestrator-core\orchestrator-core.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\home\site\wwwroot\node_modules\botbuilder-ai-orchestrator\lib\orchestratorRecognizer.js:37:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)

**Comment by tushaar9027** [comment]
@pramodphamax my error is different one ,

Error: EPERM: operation not permitted, unlink 'D:\CDS\MySupportComposerDev\MySupportComposerDev\node_modules@microsoft\orchestrator-core\onnxruntime.dll

I did some further investigation and this basically means that somewhere this file is open or used by some other process which was restricting it to be deployed to azure. Unfortunately i was not able to find which process was using the file because according to me everything was closed and i killed all the processes even but may be some windows cache issue.

Let me try creating a new bot and try the same thing in that , it might solve the issue.

Thanks for the help you guys are putting in.

**Comment by dmvtech** [comment]
Hi @tushaar9027 

> Could you please let me know how to find out check which application has locked this file (i am using the node js empty bot template)

I don't know for sure, but you might try some of the suggestions seen here:
https://www.winhelponline.com/blog/find-process-locked-file-openfiles-utility/

I am no longer able to reproduce any issue with **_publishing_** in regards to orchestrator (**other** than the [known issue](https://github.com/microsoft/BotFramework-Composer/issues/8890) with not being able to publish to Linux app service plan hosts). I am able to publish node orchestrator bot to Windows App Service Plan. BUT it does not run. Still investigating that part. However, I am also now using 2.1.2 version of Composer.

- Can you please confirm if your app service plan is Windows or Linux?
- Can you upgrade to version `2.1.2` and see if you still have issues?

**Comment by dmvtech** [comment]
As this is not specific to Composer, I am closing this to track in this issue:
https://github.com/microsoft/botframework-sdk/issues/6462

Please follow that for resolution.
