### ISSUE TITLE
Unable to create the Bot with Composer.. Always throwing this error

### ISSUE THREAD

**Issue by subhashkotu** [microsoft/BotFramework-Composer#8966]
## Describe the bug

Bot composer doesn't create the project with the 'Enterprise Assistant Bot'

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Composer'
2. Click on 'Create a new bot to get started'
3. Select 'Enterprise Assistant Bot'
4. Select the destination path
5. Click on Create

## Expected behavior

Project should be created

## Screenshots

**Error Message**: 
Error hit when instantiating remote template: C:\Users\ABCD\AppData\Roaming\BotFrameworkComposer\.yo-repository\node_modules\@microsoft\generator-bot-enterprise-assistant\generators\app\templates\botName.sln:6 4| VisualStudioVersion = 16.0.30503.244 5| MinimumVisualStudioVersion = 10.0.40219.1 >> 6| Project("{<%= projectType %>}") = "<%= botName %>", "<%= botName %>\<%= botName %>.csproj", "{<%= botProjectGuid %>}" 7| EndProject 8| Project("{<%= projectType %>}") = "Calendar", "Calendar\Calendar.csproj", "{<%= calendarProjectGuid %>}" 9| EndProject projectType is not defined

**Comment by lauren-mills** [comment]
Hi @subhashkotu this is a known issue and we are working to publish the fix ASAP. I will update this when it is in.

**Comment by lauren-mills** [comment]
Version 1.2.2 of the Enterprise Assistant template has been published and is available in Composer. Please try again and let us know if this resolves your issue!

**Comment by gdl-reif** [comment]
Sorry to hijack the issue: I encounter the same issue "Error hit when instantiating remote template: Trying to copy from a source that does not exist: \projects\Bots\CoreWithQnA\CoreWithQnA\botName.csproj" when trying to create any kind of bot. Using Release:2.1.1-nightly.289819.d04ceae

**Comment by johnataylor** [comment]
closing this as resolved please reopen if this is not the case
