### ISSUE TITLE
Dynamic QnA strict filters do not work

### ISSUE THREAD

**Issue by ryub3n** [microsoft/BotFramework-Composer#8983]
## Describe the bug

Dynamic strict filters do not work for QnAMaker. 
The only value it's accepting is a string.
Unable to change the value type.

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [x] macOS Monterey 12.2
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot with QnAMaker KB (Connect to QnA Knowledge Base) that has metadata.
2. Accept an input from the user that is stored as a property to pass on to QnAMaker as a strict filter

## Expected behavior

Dynamic QnA strict filters should work

## Screenshots
Imagine user.b is a property that is sent based on user's selection. I want to pass this as a strict filter but it doesn't work.
<img width="345" alt="image" src="https://user-images.githubusercontent.com/24279903/153206294-d548e91c-4bcc-496d-9fad-11f62794009b.png">

Setting the value to a string works but passing it dynamically like above doesn't. 

## Additional context

The 'QnA Intent recognized' trigger dialog doesn't have the option to even set the strict filter so we had to use the 'Connect to QnA Knowledge Base' option only to find out we can't accomplish what we want.

**Comment by ryub3n** [comment]
A user had commented about the same on another issue but it has not been addressed. https://github.com/microsoft/BotFramework-Composer/issues/3026#issuecomment-999132018

**Comment by ramfattah** [comment]
Hi @ryub3n - please add `=` in the value property? example: `=${user.b}`

try the above step, let me know if this works.

**Comment by ryub3n** [comment]
Hi @ramfattah , I had tried that but it didn't work.

**Comment by ramfattah** [comment]
Hi @ryub3n,

Have you had a chance to look at this issue? https://github.com/microsoft/botbuilder-dotnet/issues/5721
I believe this might be the workaround? https://github.com/microsoft/botbuilder-dotnet/issues/5721#issuecomment-877407041

**Comment by ramfattah** [comment]
Hi @ryub3n,

Have you had a chance to look at this issue? https://github.com/microsoft/botbuilder-dotnet/issues/5721
This might be the workaround? https://github.com/microsoft/botbuilder-dotnet/issues/5721#issuecomment-877407041

**Comment by ramfattah** [comment]
Hi @ryub3n, any updates?

**Comment by ryub3n** [comment]
@ramfattah , didn't work. No option to choose expression.
<img width="351" alt="Screenshot 2022-02-23 at 11 58 43 PM" src="https://user-images.githubusercontent.com/24279903/155388257-5382abea-759f-477f-a27e-18745ad880f4.png">

**Comment by ramfattah** [comment]
Hello @ryub3n, 

This feature is not yet supported in Composer. We'll take this issue as a feature request and add it to the backlog for prioritization. We do not have an ETA at this time for when this feature will be available.
