### ISSUE TITLE
Orchestrator and entities - is this a limitation?  If so what's the solution?

### ISSUE THREAD

**Issue by metkhoo** [microsoft/BotFramework-Composer#8992]
One of the great features in LUIS is the ability to extract entities from utterances.  Things like:  "I need a new phone" with the list entity containing "phone" (with synonyms of iphone, andriod etc).
With the entities extracted, a BOT dialog can then process on the basis of knowing already that the user wants a phone. 
If I use Orchestrator my current understanding is that it can't ever extract entities.  If so then the orchestrator dispatching pattern seems very limited.
Have I understood this correctly?

**Comment by dmvtech** [comment]
Hi @metkhoo You have. Using orchestrator as a recognizer is somewhat of a middle ground between a regex recognizer and a full LUIS recognizer. You will be able to use intents, but entities are not available.

**Comment by metkhoo** [comment]
@dmvtech - Thanks for the clarification!
