### ISSUE TITLE
OAuth Login button does not show up

### ISSUE THREAD

**Issue by jcmorara** [microsoft/BotFramework-Composer#9000]
## Describe the bug

Since yesterday the login button does not show up in 2 chatbots published in Azure that previously worked fine. The turn.token value is null.

## Version

v2.1.2

## Browser

- [ ] Electron distribution
- [ X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Bot Composer
2. Create "Access external resources"->"OAuth login" Action
3. Configure Azure authentication as described in this link: [https://docs.microsoft.com/en-us/composer/how-to-use-oauth?tabs=v2x](How to use OAuth)
4. Publish chatbot in Azure
5. Execute chatbot and see the issue

## Expected behavior

Login button appears

## Screenshots

![image](https://user-images.githubusercontent.com/88945358/154268846-13f44846-cb8e-42de-b966-a0925e925e0a.png)
![image](https://user-images.githubusercontent.com/88945358/154269019-989a4767-2919-4cad-9bc8-80f5d7a6e8f8.png)

**Comment by rodriguesnich** [comment]
I'm experiencing the same issue, we aren't able to access our resources, since the token isn't returned

**Comment by dmvtech** [comment]
@jcmorara @rodriguesnich 

Can you guys confirm that this is still an issue? Apparently there were some outages recently as seen here: https://github.com/microsoft/botframework-sdk/issues/6466

**Comment by jcmorara** [comment]
Our bots seem to be working now.
Thanks for the notice @dmvtech

**Comment by rodriguesnich** [comment]
> @jcmorara @rodriguesnich
> 
> Can you guys confirm that this is still an issue? Apparently there were some outages recently as seen here: [microsoft/botframework-sdk#6466](https://github.com/microsoft/botframework-sdk/issues/6466)

Same to me, everything is working now, thank you
