### ISSUE TITLE
Composer looking for a LUIS app that doesnt exist

### ISSUE THREAD

**Issue by saikumaru** [microsoft/BotFramework-Composer#9005]
## Describe the bug

The composer fails to publish the bot due to this error.
![image](https://user-images.githubusercontent.com/44021002/154954024-b482e62b-b038-47cc-94ee-31988bf4f43e.png)

"Failed to bind LUIS prediction resource..."

## Version
2.1.2

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Deploy a composer build bot with LUIS
2. Delete the LUIS app created(I am not exactly sure if this is what caused it)
3. Redeploy the bot from composer

## Expected behavior
The composer should create the new LUIS app

## Additional context
The LUIS app the composer is looking for doesn't exist, but it is also not clear where is the composer picking the App-Id from?

Logs

```
---
"{\n  \"stack\": \"Error: Request failed with status code 400\\n    at createError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:105969:17)\\n    at settle (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:105983:14)\\n    at IncomingMessage.handleStreamEnd (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:106970:13)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\",\n  \"message\": \"Request failed with status code 400\",\n  \"config\": {}\n}"
---

---
"{\"stack\":\"Error: Failed to bind luis prediction resource to luis applications. Please check if your luisResource is set to luis prediction service name in your publish profile.\\n            Luis App ID: dsds-d-s-d--d2437; Luis Authoring Key: 798dsdsddsd; AzureSubscriptionID: 33dsddd69db ResourceGroup: ddddormation-platform; AccountName: ddddt-luis; Location: westeurope.\\n            Response Status: 400; Error Code: BadArgument; Error Message: Cannot find an application with the ID dsdsdsd. \\n    at publishLuisToPrediction (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276586:17)\",\"message\":\"Failed to bind luis prediction resource to luis applications. Please check if your luisResource is set to luis prediction service name in your publish profile.\\n            Luis App ID: dsdsdsd; Luis Authoring Key: dsdsdds; AzureSubscriptionID: dssdsd ResourceGroup: gdsdsfrrfformation-platform; AccountName: dsdsdInfoBot-luis; Location: westeurope.\\n            Response Status: 400; Error Code: BadArgument; Error Message: Cannot find an application with the ID fdfddfbe2fdfd. \"}"
---

---
"Error - Failed to bind luis prediction resource to luis applications. Please check if your luisResource is set to luis prediction service name in your publish profile.\n            Luis App ID: fdfdfdfddf; Luis Authoring Key: 7fdfdfd2fcf8; AzureSubscriptionID: fdfdfdfb ResourceGroup: fdfdfdfation-platform; AccountName:fdfdfdfoBot-luis; Location: westeurope.\n            Response Status: 400; Error Code: BadArgument; Error Message: Cannot find an application with the ID fdfdfdfd826be2437. "
---
```

**Comment by saikumaru** [comment]
After a bit of struggle, landed at this script which is doing the publish

https://github.com/microsoft/BotFramework-Composer/blob/6a6a24aee59e7906ed5da5b45669c9877359f273/extensions/azurePublish/src/node/luisAndQnA.ts

Which picks up files matching luis.settings prefix. The composer picks the old files from debug or release folder. After I deleted these folders and republished the bot, it went on fine.

@anishprasad01 - please can you confirm if this is expected or if its expected to rebuild the project by cleaning up release and debug folders?

**Comment by dmvtech** [comment]
Hi @saikumaru 

> Delete the LUIS app created(I am not exactly sure if this is what caused it)

Do you know how exactly you deleted it and from where? I just deleted it from the LUIS portal. But I was able to publish successfully and it was re-created.

> Which picks up files matching luis.settings prefix. The composer picks the old files from debug or release folder. After I deleted these folders and republished the bot, it went on fine. Can you confirm if this is expected or if its expected to rebuild the project by cleaning up release and debug folders?

Again; it depends on how things got deleted/removed/etc. Where there changes to the bot between the first publish->removal and second publish? I think we need more steps to understand what happened and be able to say what is expected or not.

**Comment by saikumaru** [comment]
Thank you for your response. I am unable to recreate this due to lack of environment access to try a different sandbox.
But here are things I had been doing

1. Pickup a composer template with LUIS, using C# Azure functions runtime,
2. Create a trigger for new intent recognition, and add relevant utterances.
3. Create a new dialog to be begun when this intent is recognized.
4. In the new dialog add a "Prompt for text" with "expected responses" under user input.
5. Now observer two LUIS apps would be created on LUIS.ai portal. App-A for the parent dialog, App-B for the child dialog in "4".
6. I went ahead and deleted the app(App-B) that had underlying utterances for "4".
7. Removed the "expected responses" from dialog in "4".
8. Tried republishing and I couldnt, due to above error. I also couldnt find earlier created App-A but new appId existed.

Also to note, the composer is tracked on a git repo, but bin folder is ignored. It could also be case that Build folders could have had any dates which could be forward dated compared to others when making a fresh pull and then re-publish?

Effectively the release and debug folders(named "generated") had two apps with their App-Ids in the json, both of which dint exist on the portal.
And the project folder had just a single AppID in the generated folder.


I however tried recreating this by updating manually the JSON in debug and release generated folders, but when I hit publish I see a new challenge, may be un-related and the publish is stuck at this point for >5min
![image](https://user-images.githubusercontent.com/44021002/155144401-7b718435-dbed-4775-af27-9110e65eca4f.png)
But the JSON files remained the same, i.e. at values I manually edited to.

I will further update my observations on this issue once I recover from above error.

**Comment by Greg-Ro** [comment]
I have a similar problem with my bot. I did exactly the same steps as saikumaru mentioned above. 

@dmvtech I removed the publishing profile and re-created ("importing exisiting ressource") a new one. But get still the same error:
![image](https://user-images.githubusercontent.com/59090516/159893707-b14eea38-4e79-4b4d-a619-a3885e5fb02b.png)

Do you have any recommendations for further investigations?

**Comment by saikumaru** [comment]
can you search your whole folder to find out which file has that App-ID ?
My solution was to delete your bin folder and rerun your bot on composer.

**Comment by Greg-Ro** [comment]
I found the folder with the App-ID. Its in bin > release > netcoreapp3.1 > win-x64 > generated
Did you deleted the hole bin folder, @saikumaru?

**Comment by saikumaru** [comment]
Yes the whole bin folder

**Comment by Greg-Ro** [comment]
Thank you @saikumaru, it worked perfectly fine!

**Comment by dweeb1937** [comment]
Thank you for this. Had the same issue switching a bot over from one LUIS resource to another. Can confirm deleting whole **bin** folder is the way to go. Just deleting folders related to the dialog causing the problem does not work.
