### ISSUE TITLE
'Break out of loop' does not work 

### ISSUE THREAD

**Issue by javier-mora** [microsoft/BotFramework-Composer#9006]
## Describe the bug

I am trying to stop a loop with the 'Break out of loop' action using a condition. But the loop doesn't stop.

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Add an 'Loop: For each item' action 
2. Add an 'Branch: if/else' action inside the loop
3. Add an 'Break out of loop' action inside the condition

## Expected behavior

The loop is expected to stop

## Screenshots

![image](https://user-images.githubusercontent.com/27820968/155027021-0b80bc11-4d57-41a0-9e4f-2d284fabd0fa.png)
![image](https://user-images.githubusercontent.com/27820968/155027654-a9b8a2de-bd79-4222-a943-6b03b80cd91d.png)

**Comment by ramfattah** [comment]
@javier-mora 

Thanks for raising this issue.

I was able to reproduce this issue of 'Break out of loop' not working. Here is my my [.dialog file](https://gist.github.com/ramfattah/54f26d02d8e537181aec657b0951deba) containing the loop and condition to break out of the loop.  

Here are the steps I took to repro:
1) Opened empty bot Composer 2.1.2 -  [Download here](https://github.com/microsoft/BotFramework-Composer/releases)
2) Create a new Dialog named "LoopDialog"
3) In the new Dialog, I created a "set property" action with the value being an array of numbers
     <img src="https://i.gyazo.com/522c8c68feb108c6affd4de20d9ff583.png" width="400"/>
4) Follow the above "[steps to repro](https://github.com/microsoft/BotFramework-Composer/issues/9006#:~:text=To%20Reproduce,See%20error)" given in the issue.
4) In project's greeting trigger, begin a new dialog of "LoopDialog" we created and start bot.

Here is my composer output:
<img src="https://i.gyazo.com/769cbdd9859a5e6bc9a468132916bac9.png" width="800"/>

**Comment by ramfattah** [comment]
@javier-mora, I will report back when I find more information about this.

**Comment by ramfattah** [comment]
There is a pull-request for this issue. https://github.com/microsoft/botbuilder-dotnet/pull/6223

Thank you @EricDahlvang for the PR!
