### ISSUE TITLE
OAuth Card not shown at all in Microsoft Teams

### ISSUE THREAD

**Issue by rmgitting** [microsoft/BotFramework-Composer#9009]
## Describe the bug

We are creating a bot that is authenticating with ADv2 and it uses the Graph API to perform some tasks.
When they user asks for something for example: My Profile, the bot checks if the user is authenticated then performs the task, otherwise it asks the user to sign in if the user is not authenticated (authentication token is null).
So it is performing just as expected when tested in webchat or through the emulator, however when tested on teams the card with the sign in button is not shown at all, the bot just hangs there doing nothing and showing nothing.
Like shown in this screenshot
![image](https://user-images.githubusercontent.com/17496441/155209521-b0c07863-577d-4596-a89b-f1adb5b3b234.png)
Here it is shown the token is null, and it is entering the authentication dialog, we are printing that for debugging just to see that the flow is going into that dialog.
In that dialog it is supposed to show the please sign in card with the sign in button, but nothing at all happens.

Actually we created another bot, you just tell it sign in, and it will trigger the authentication dialog to sign you in, it does nothing else. On web and emulator it is working fine, on teams nothing really happens.

![image](https://user-images.githubusercontent.com/17496441/155208124-f88fe42c-6b8c-4882-81cc-b8c2fee6b8ed.png)
Here the button is shown just fine
![image](https://user-images.githubusercontent.com/17496441/155208231-5e0daf99-40d9-45ff-b1ae-c9e6edaf582d.png)
On teams nothing happens, the bot is doing nothing at all.

We tried this by calling the bot by its ID and by creating a Teams app and using the App Manifest, it is still the same.
Even though it shouldn't matter at this stage, at least the button should be shown regardless of how we are using the bot.

## Version

v2.1.1

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

We did nothing special, it is just about using the OAuth activity in Composer and let it be shown normally on Teams.
We created a bot in composer, used the OAuth activity, linked it to an Application that we have created in active directory where we have given the needed permissions
We deployed the bot to Azure
We enabled the Teams Channel
Clicked on the Open on Teams button (again even with app manifest it is the same)
Triggered the authentication dialog but it is just not shown at all (the sign in card). The bot just does nothing.

On web channel or emulator it is working just fine but Teams it is not.

## Expected behavior

To show the sign in button on Teams, so users can authenticate and use the bot.

**Comment by anishprasad01** [comment]
Hi @rmgitting,

I just attempted to reproduce your scenario but was unable to. I created a Composer bot using the default `OAuth login` action and communicated with the bot on the Teams desktop app, and I got a login prompt.

Perhaps you could double check the [user auth](https://docs.microsoft.com/en-us/composer/how-to-use-oauth?tabs=v2x) docs page to see if anything is missing in your bot?

Additionally, it is important to note that while the login prompt should appear regardless, it will *not* function correctly without installing the bot as an app.

**Comment by rmgitting** [comment]
> Hi @rmgitting,
> 
> I just attempted to reproduce your scenario but was unable to. I created a Composer bot using the default `OAuth login` action and communicated with the bot on the Teams desktop app, and I got a login prompt.
> 
> Perhaps you could double check the [user auth](https://docs.microsoft.com/en-us/composer/how-to-use-oauth?tabs=v2x) docs page to see if anything is missing in your bot?
> 
> Additionally, it is important to note that while the login prompt should appear regardless, it will _not_ function correctly without installing the bot as an app.

Thanks for your reply. To be honest it was working fine at some point, the login button was shown but then suddenly it stopped, and also as I told you we tried a whole new bot just with the login button and it is not shown for me neither my colleagues. Outside of teams like on webchat or emulator, it works just fine. I am not sure what would be the issue. We can try to create a whole new AD app and add it and see if this works. But still I don't understand what is the issue.

**Comment by anishprasad01** [comment]
If no changes were made to your bot, perhaps changes were made to your Teams environment?

**Comment by rmgitting** [comment]
> If no changes were made to your bot, perhaps changes were made to your Teams environment?

The problem is that we tested one bot on our tenant, and  another one on another tenant (the client) but both performed the same way of not showing the login button, on our teams and theirs

**Comment by anishprasad01** [comment]
One more basic troubleshooting step to try. Let's verify that the Azure configuration is correct. Additionally, there is a separate document on [SSO in Teams bots](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#develop-an-sso-teams-bot) that might be more specific and helpful here.

**Comment by anishprasad01** [comment]
@rmgitting,

Also, double check that in your app manifest, you have `token.botframework.com` in your `validDomains`, as shown in this [Teams auth code sample](https://github.com/microsoft/BotBuilder-Samples/blob/14ed6ea596aa84d2b561d00f58f828ae8cc1a89a/samples/csharp_dotnetcore/46.teams-auth/TeamsAppManifest/sso_manifest.json#L45). This is an easy-to-miss requirement for auth to work.
