### ISSUE TITLE
20% of conversations do not have customEvents logged in App Insights

### ISSUE THREAD

**Issue by lshade** [microsoft/BotFramework-Composer#9010]
## Describe the bug

We have a bot running in production and are using the `customEvent` logs in app insights to report on the conversations.

We noticed about 2,000 out of the 10,000 total conversations per day do not have `customEvents` logged, only `requests`, `dependencies`, and `pageViews`. We were able to verify from call recordings that these conversations go through dialogs in the bot, but no `customEvents` are logged to report on them.

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Our client app is using the DirectLine Web Socket to send and receive messages to the bot in Azure. There are plenty of conversations that do have customEvents logged, but about 20% do not. I'm available to screenshare to show some examples if needed.

## Expected behavior

customEvents logged every time to explain what messages were sent from the bot during the conversation.

**Comment by EricDahlvang** [comment]
This is possibly due to sampling: https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling

Please turn sampling off, and let us know.

**Comment by lshade** [comment]
Turning off sampling worked. I added this to Startup:
```
public void ConfigureServices(IServiceCollection services)
{
    // ...

    var aiOptions = new Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions();
    aiOptions.EnableAdaptiveSampling = false;
    services.AddApplicationInsightsTelemetry(aiOptions);

    //...
}
```

Now when I run this query in App Insights, it shows 100% retention
```
union customEvents
| where timestamp > ago(1d)
| summarize RetainedPercentage = 100/avg(itemCount) by bin(timestamp, 1h), itemType
| sort by timestamp asc 
```

Thanks!
