### ISSUE TITLE
Does Composer support a 'Conversational Language Understanding' project from the new Language service in Cognitive Services?

### ISSUE THREAD

**Issue by joshtbcr** [microsoft/BotFramework-Composer#9015]
## Describe the bug

All tutorials show samples of the classic LUIS (from luis.ai), but none of them from the new Language service (language.cognitive.azure.com).
https://docs.microsoft.com/en-us/composer/how-to-add-luis?tabs=v2x#update-luis-keys

_Azure Cognitive Services for Language unifies three individual language services in Cognitive Services - Text Analytics, QnA Maker, and Language Understanding (LUIS)._
https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/overview#:~:text=Azure%20Cognitive%20Service%20for%20Language%20is%20a%20cloud%2Dbased%20service,REST%20APIs%2C%20and%20client%20libraries.

## Version

Using Bot Composer 2.x

## Browser

- [ ] Electron distribution
- [ X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to settings in composer and try to add Language Understanding
2. Click on region and WestUS2 is not available

Or... try to modify the JSON advanced settings with the keys, it returns error

Or... login to Azure and the Language service is not an option

## Expected behavior

It should be able to connect to new LUIS

## Screenshots

![image](https://user-images.githubusercontent.com/32825882/155441488-54bf46ea-f5f7-444e-997c-509b92919110.png)

Even the selectable regions from composer do no match with the available regions in the new service. When changing it manually in the JSON, it does not work.

![image](https://user-images.githubusercontent.com/32825882/155449440-52b0404b-cee6-44c2-977c-98addcd73013.png)

Conversational Language Understanding is only available in 2 regions: West US 2 and West Europe
https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/conversational-language-understanding/service-

**Comment by anishprasad01** [comment]
Hi @joshtbcr,

At this time, Composer does not support the new Azure services unifying QnA and LUIS with other products. The standalone  QnA and LUIS resources continue to be available, so you would need to use them when building a Composer bot.

**Comment by davidmw** [comment]
Are there any plans to migrate Composer to the new Language service in Cognitive Services - is this on the roadmap? Hate to start new projects using 'classic LUIS' if there are better options coming.

**Comment by anishprasad01** [comment]
At this time, I have no new information to share regarding future roadmaps. Code-first bots have support for the new resources, if you are interested in using them.

**Comment by pablodiloreto** [comment]
Hello Team! In a few weeks, QnA Maker will no longer allow you to create new knowledge bases. Is there an update on Custom Question Answering support in the Bot Framework Composer?

**Comment by Leong-Qi-Jin** [comment]
> Hello Team! In a few weeks, QnA Maker will no longer allow you to create new knowledge bases. Is there an update on Custom Question Answering support in the Bot Framework Composer?

Agreed. May I know when will there be support for Azure Cognitive Services for Language in Bot Framework Composer?
