### ISSUE TITLE
@teams @microsoft@botservice This action can't be performed since the app does not exist or has been uninstalled in Teams Desktop 

### ISSUE THREAD

**Issue by TarakSivakoti** [microsoft/BotFramework-Composer#9018]
![image](https://user-images.githubusercontent.com/25145223/156143805-457c5929-7147-4af7-a039-fac6a5637b5e.png)
In browser, I'm unable to see the issue.
added valid domains: 

"validDomains": [
    "token.botframework.com",
    "*.ngrok.io",
    "dev.azure.com",
    "login.microsoftonline.com"
  ],

could anyone help me soon , getting struck at deployment process.

**Comment by anishprasad01** [comment]
Hi @TarakSivakoti,

Have you created an app manifest and installed it in Teams? You must create an app manifest and install the app for OAuth logins to work properly. If you simply click the "Open in Teams" link in the Channels menu in Azure, this will not work correctly. You can see any of the Teams bot samples for instructions on how to create one. Here's [one](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/57.teams-conversation-bot).

**Comment by TarakSivakoti** [comment]
I have solved this and closed the bug:
solutions are version issues, bot framework is not supporting .net 5.O
solutions :
```
<!--Do not change the TargetFramework for bot-->
//current
	<PropertyGroup>
	  <TargetFramework>netcoreapp3.1</TargetFramework>
	  <LangVersion>latest</LangVersion>

//used previously		
    <!--<TargetFramework>net5.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <StartupObject>XYZ</StartupObject>-->

  </PropertyGroup>
```
