### ISSUE TITLE
Root dialog recognizer type gets reset to Default from Orchestrator when adding a new dialog

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#9022]
## Version

2.1.2

## To Reproduce

1. Create a new project from Template "EnterpriseAssistant"
2. Confirm the recognizer type of root dialog "EnterpriseAssistant" is **_Orchestrator_** 
3. Add a new dialog "MyFirstDialog"
4. The recognizer type of root dialog "EnterpriseAssistant" is changed to **_Default_** upon the new dialog gets added

## Expected behavior

The recognizer type of root dialog "EnterpriseAssistant" remains unchanged as **_Orchestrator_** 

## Screenshots
![recognizertypeChange](https://user-images.githubusercontent.com/44714043/156493497-502f8983-a8db-4c4b-9218-27d0505e8097.gif)

**Comment by ramfattah** [comment]
Hi @dawwa, I'm investigating this issue.

**Comment by ramfattah** [comment]
Hi @dawwa, thanks for raising this. I was able to reproduce this issue. We'll add this bug to the backlog for future iterations. We do not have an ETA at this time.
