### ISSUE TITLE
Not able install packages on composer

### ISSUE THREAD

**Issue by Tejaspshetty19** [microsoft/BotFramework-Composer#9023]
## Describe the bug

I am running composer on Node.js environment and I get this error every time I tried to install any package.

## Version

I am using v2.1.2

## OS
I am using Windows 10
And I have latest version of Node.js installed

Please find the attached screenshot of the error.
![image](https://user-images.githubusercontent.com/100895770/156701341-9f85df49-b5ef-466c-8dfe-37465ccd28de.png)

**Comment by ramfattah** [comment]
Hey @Tejaspshetty19, Thank you for engaging in the Composer project. We'll add this work item to the backlog for future iterations. We do not have an ETA at this time for when this bug will be fixed.
