### ISSUE TITLE
Portable Edition for Windows

### ISSUE THREAD

**Issue by FANMixco** [microsoft/BotFramework-Composer#9026]
## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

A Zip file or a Portable Installer that allows you to install the app in any Pendrive.

## Describe alternatives you've considered

I installed it in a Pendrive, and it works fine, but I'd rather have a Zip that I can install and doesn't create dependencies in Windows. The Bot Framework Composer seems to be a completely independent app.

## Additional context

N/A

**Comment by FANMixco** [comment]
Any news?

**Comment by OEvgeny** [comment]
You could build the version from sources without any dependencies installed by the installer on the machine

Not perfect, but should work for the use-case
