### ISSUE TITLE
Wrap the text in the button of QnAmaker hero card

### ISSUE THREAD

**Issue by Levis0045** [microsoft/BotFramework-Composer#9030]
## Is your feature request related to a problem? Please describe.

When active learning is triggered, the QnAmaker hero card can not wrap the text in the buttons with (...). This behavior don't allow us to completely see the question returned.

## Describe the solution you'd like

We would like to able wrap the text in the button. We also want some options to control the behavior of this hero card. Actually all is done automatically.

## Describe alternatives you've considered

Something which could be better is to have manual control of this bahavior.

## Additional context

- ActiveLearning functionality
- QnAmaker hero card

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/13846122/157051502-d0bf6c73-746c-4887-a853-57e9b3602ed8.png)

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/13846122/157052027-71391490-c7b6-499d-9db1-c199fa144b5d.png)

![Capture du 2022-03-07 15-20-17](https://user-images.githubusercontent.com/13846122/157051743-c49068ec-3b76-4f92-9820-25a0aea04cb3.png)

**Comment by timoleo23** [comment]
Hi, is there a way to override the card sent by the QnA maker component? I don't think Hero cards supprot "text wrap" on buttons which mean that the workaround is to use an Adaptive Card instead - Here is an example to do that:

{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "Please select an option"
                }
            ]
        },
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "Option 1 - Click on this text to submit your action - This text will be wrapped to the next line automatically ",
                    "selectAction": {
                        "type": "Action.Submit",
                        "data": {
                            "response": 1
                        }
                    }
                }
            ]
        },
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "Option 2 - Click on this text to submit your action - This text will be wrapped to the next line automatically ",
                    "selectAction": {
                        "type": "Action.Submit",
                        "data": {
                            "response": 2
                        }
                    }
                }
            ]
        }
    ]
}

**Comment by tingting0118** [comment]
Hi @timoleo23 , thanks for your answer. But in composer, we have to use the type "imback" to continue de qna dialog (otherwise we have to change too much codes in module package), do you know how to add "imback" in adaptive card ? Because we have this error with your example + imback:
![image](https://user-images.githubusercontent.com/56673470/157895309-8240ae4c-b5c7-4421-9855-657112bf8672.png)
We would like to have another example of adaptive card with "imback", thanks for your help!
PS: With idea of this issue: https://github.com/microsoft/BotFramework-WebChat/issues/616 , we use actually  a carousel for those suggestion cards(because imback is automatically in hero card):
![image](https://user-images.githubusercontent.com/56673470/157896483-6733546a-ae23-414b-b9ae-772b7d2908b9.png)
it's better than before but the UI is not friendly to the users, so we still want to find a solution with adaptive card.

**Comment by timoleo23** [comment]
Hi @tingting0118 , you can use this specific format that only works with Adaptive Cards for Microsoft Teams.
Here, you can control the message back displayed to the user and the value returned to the bot.
Documentation is here - https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=json#adaptive-cards-with-messageback-action

```JSON
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.4",
    "body": [
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "Please select an option"
                }
            ]
        },
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "Option 1 - Click on this text to submit your action - This text will be wrapped to the next line automatically ",
                    "selectAction": {
                        "type": "Action.Submit",
                        "data": {
                            "response": 1
                        }
                    }
                }
            ]
        },
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "Option 2 - Click on this text to submit your action - This text will be wrapped to the next line automatically ",
                    "selectAction": {
                        "type": "Action.Submit",
                        "title": "Click me for messageBack",
                        "data": {
                            "msteams": {
                                "type": "messageBack",
                                "displayText": "I clicked this button",
                                "text": "text to bots",
                                "value": { "response" : 2 }
                            }
                        }
                    }
                }
            ]
        }
    ]
}
```

**Comment by Levis0045** [comment]
Hi @timoleo23, thanks for this response. 


But the problem there is Bot Composer Interface. Your suggestion requiert for us to update the internal code of Microsoft libraries (npm packages). We have implemented your suggestion,  but this type **messageBack** requiert a value or **imBack** type doesn't requiert a value. imBack type respond to this problem.  How can we update the library to implement your solution ? 

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/13846122/158359608-ed7c0e4c-5676-485f-8697-a3c4063173a4.png)

Do you have a zip example of your projet that we can test with ? Please consider the fact that we work with Bot Framework Composer sofware (Ubuntu version) not with Bot services (with native typescript code).

**Comment by timoleo23** [comment]
Here is the Adaptive Card format with imBack
However, I don't know if we can supercharge the built-in QnA maker component in Bot Composer and I'd differ this question to the Microsoft support team.

```JSON
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.4",
    "body": [
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "Please select an option"
                }
            ]
        },
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "Option 1 - Click on this text to submit your action - This text will be wrapped to the next line automatically ",
                    "selectAction": {
                        "type": "Action.Submit",
                        "data": {
                            "response": 1
                        }
                    }
                }
            ]
        },
        {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "Option 2 - Click on this text to submit your action - This text will be wrapped to the next line automatically ",
                    "selectAction": {
                        "type": "Action.Submit",
                        "title": "Click me for messageBack",
                        "data": {
                            "msteams": {
                                "type": "imBack",
                                "title": "More",
                                "value": "Show me more"
                            }
                        }
                    }
                }
            ]
        }
    ]
}
```

**Comment by tingting0118** [comment]
@timoleo23, thanks for your idea, that helps a lot!  Here is the codes for the developper who has the same question **in Bot Composer** :
1. open the script in path `YourProject/node_modules/botbuilder-ai/lib/qnaCardBuilder.js"`
2. Just modify the function `getSuggestionsCard(suggestionsList, cardTitle, cardNoMatchText)`
**-> option 1.1 - Adaptive Card for Teams**
/!\ **That will not work in Composer when you test, but it will work with Teams**
3. Here is the code to change:
 `static getSuggestionsCard(suggestionsList, cardTitle, cardNoMatchText) {
        if (!Array.isArray(suggestionsList)) {
            throw new Error('Missing suggestionsList');
        }
        if (!cardTitle) {
            throw new Error('Missing cardTitle');
        }
        if (!cardNoMatchText) {
            throw new Error('Missing cardNoMatchText');
        }
        const cardls=[ {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": cardTitle,
                    "weight": "Bolder"
                }
            ]
        }];
        suggestionsList.forEach((suggestion) => {
            cardls.push({
                "type": "RichTextBlock",
                "inlines": [
                    {
                        "type": "TextRun",
                        "text": "👉 " + suggestion,
                        "selectAction": {
                            "type": "Action.Submit",
                            "title": suggestion,
                            "data": {
                            "msteams": {
                                "type": "imBack",
                                "title": suggestion,
                                "value": suggestion
                            }
                        }
                            }
                        }
                
                ]
            });
        });
        cardls.push({
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "❗ " + cardNoMatchText,
                    "selectAction": {
                        "type": "Action.Submit",
                        "title": cardNoMatchText,
                        "data":  {
                            "msteams": {
                                "type": "imBack",
                                "title": cardNoMatchText,
                                "value": cardNoMatchText
                            }
                        }
                        }
                    }
            
            ]
        });

        const card=botbuilder_core_1.CardFactory.adaptiveCard({
              "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
              "type": "AdaptiveCard",
             "version": "1.2",
             "body": cardls});
        const message = botbuilder_core_1.MessageFactory.attachment(card);
       return message;
    }`
**-> option 1.2 - Adaptive Card for WebChat**
3. Here is the code to change:
 `static getSuggestionsCard(suggestionsList, cardTitle, cardNoMatchText) {
        if (!Array.isArray(suggestionsList)) {
            throw new Error('Missing suggestionsList');
        }
        if (!cardTitle) {
            throw new Error('Missing cardTitle');
        }
        if (!cardNoMatchText) {
            throw new Error('Missing cardNoMatchText');
        }
        const cardls=[ {
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": cardTitle,
                    "weight": "Bolder"
                }
            ]
        }];
        suggestionsList.forEach((suggestion) => {
            cardls.push({
                "type": "RichTextBlock",
                "inlines": [
                    {
                        "type": "TextRun",
                        "text": "👉 " + suggestion,
                        "selectAction": {
                            "type": "Action.Submit",
                            "title": suggestion,
                            "data": suggestion
                            }
                        }
                ]
            });
        });
        cardls.push({
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "❗ " + cardNoMatchText,
                    "selectAction": {
                        "type": "Action.Submit",
                        "title": cardNoMatchText,
                        "data":  cardNoMatchText
                        }
                    }
            
            ]
        });

        const card=botbuilder_core_1.CardFactory.adaptiveCard({
              "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
              "type": "AdaptiveCard",
             "version": "1.2",
             "body": cardls});
        const message = botbuilder_core_1.MessageFactory.attachment(card);
       return message;
    }`
**-> option 2 - Carousel**
3. codes to modify:
        `const cardlist=[];
        suggestionsList.forEach((suggestion) => {
            cardlist.push(botbuilder_core_1.CardFactory.heroCard(undefined, suggestion,undefined, [{
                value: suggestion,
                type: 'imBack',
                title: "Ask it",
            }]));
        });
        cardlist.push(botbuilder_core_1.CardFactory.heroCard(undefined,undefined,[{
            value: cardNoMatchText,
            type: 'imBack',
            title: cardNoMatchText,
        }]));
        const message = botbuilder_core_1.MessageFactory.carousel(cardlist,cardTitle)`

4. `Save the script and restart the bot in composer.`

**Comment by freistli** [comment]
To display wrapped QnA prompts text in .Net Composer Project, can consider updating Language Generation (bot response) to display proper adaptive card for WebChat & Teams, and then modify the response action in QnA Maker dialog canvas. 

I can make it work with below are detailed steps:

1. In Bot Composer, click **Bot Responses**
2. Click **Common**
3. Click the main dialog (suppose your QnA is in the dialog)
4. Click **Show Code**
5. Paste below three section LG code into the Editor

```
# getResponseWithPrompts(answer, prompts)
-```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "${answer}",
            "wrap": true
        }
    ,   
       ${getButtonList(prompts)}
    ]
}```

# getButtonList(prompts)
- ${join(foreach(prompts, u, if(turn.Activity.channelId == 'msteams' ,getButtonWrapTextItemTeams(u.displayText, u.id) ,getButtonWrapTextItemWeb(u.displayText, u.id))), ',')}
```
```
# getButtonWrapTextItemWeb(value, id)
-```
{
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "${value}",
                    "selectAction": {
                        "id": "${id}",
                        "type": "Action.Submit",
                        "data": "${value}"
                    }
                }
            ]
}```
```

```
# getButtonWrapTextItemTeams(value, id)
-```
{
            "type": "RichTextBlock",
            "inlines": [
                {
                    "type": "TextRun",
                    "text": "${value}",
                    "selectAction": {
                        "type": "Action.Submit",
                        "title": "Click me for messageBack",
                        "data": {
                            "msteams": {
                                "type": "imBack",
                                "title": "More",
                                "value": "${value}"
                            }
                        }
                    }
                }
            ]
        }```
```
A UI sample in my composer when I update the common LG (bot responses):
![image](https://user-images.githubusercontent.com/8623897/164357719-da9554d5-4c09-4a56-bb3d-f3360aab8d02.png)

6. Click **Create** in the left navigation panel

7. Click **QnA Intent Recognized trigger**

8. In the Dialog canvas, select the **Prompt for Text" action (currently it uses SuggestedAction)

9. In the Properties pane, in the **Bot Response** part, click **Show code**
10. Replace the code with below content

```
[Activity

    Attachments = ${json(getResponseWithPrompts(@answer, turn.recognized.answers[0].context.prompts))}

]
```
The UI sample in my composer:

![image](https://user-images.githubusercontent.com/8623897/164358765-5bbee7ca-bab2-4264-8b7e-4d981a79ebc0.png)

With above steps, you will see Composer and Teams can proper wrapped text with imback type

In **Composer Web Chat**

<img src="https://user-images.githubusercontent.com/8623897/164358955-720318bc-91d9-44c8-8e66-6120cfddcc24.png"  width="300"/>

In **Teams**
![image](https://user-images.githubusercontent.com/8623897/164359018-6b305e68-c824-4425-b2d5-3bf0dd68c381.png)

When I work on this method, also referred one previous discussion https://github.com/microsoft/botbuilder-dotnet/issues/5149, after some modification, its main part can work well in current composer version QnA.
