### ISSUE TITLE
Unable to add QnA Maker knowledge base to Composer bot

### ISSUE THREAD

**Issue by PeterPekanovics** [microsoft/BotFramework-Composer#9034]
When trying to add a QnA Maker knowledge base to a chatbot, on the 'Choose a knowledge base to import' screen I can't select and add my KB. Cursor turns into a crossed through circle when hovering over the KB, and 'Next' button is greyed out.
![image](https://user-images.githubusercontent.com/100796571/157294691-2f742908-4b1f-4fc2-9330-056f8ce2e3f2.png)
The KB is in Finnish language, which I know isn't supported by LUIS, however the QnA Maker service does support that language, and I can also create a working bot from the knowledge base.
Why can't I add this KB to my bot?
Composer version: 2.1.2.
Not dependent on platform.

**Comment by PeterPekanovics** [comment]
I managed to add the knowledge base, only needed to add Finnish language in the Composer settings.
However, now I can't publish the bot:
![image](https://user-images.githubusercontent.com/100796571/157688399-257ce5b5-4adc-44e2-b950-14b5f575bed9.png)
QnA Maker is set up inside Composer, the key and endpoints are provided, and also saved in appsettings.json
What else do I need to do to 'Provision' a QnA Maker service?

**Comment by stevkan** [comment]
@PeterPekanovics, were you able to publish the bot prior to adding the Finnish language and/or adding the knowledge base? In other words, could you publish without QnA Maker having been setup?

With regards to the above, when you added Finnish, were you speaking about in the bot's configure screen under Localization? Or, in the Composer settings under Composer language?

If under Localization, which language do you have set as default? If Finnish, can you set English back as the default and try again?

**Comment by pekanovics** [comment]
Hi @stevkan, thanks for replying,
I was able to publish the bot prior to adding a QnA knowledge base.
I could add the Finnish QnA KB after I added Finnish language in the Localization screen. Default language is still set to English.

**Comment by stevkan** [comment]
@pekanovics, apologies for the delayed response. Unfortunately, I am not able to repro the issue you are experiencing with publishing. I followed what I believe are the same steps you did:

1. Provision and publish a bot (without QnA or KB).
2. Imported Finnish KB (including adding the Finnish language under Localization)
3. Added QnAMaker to the publishing profile
    - Clicked the profiles "Edit" button
    - Selected Create new resources and clicked "Next"
    - Clicked "Next" to advance thru Configure resources
    - Selected QnA Maker service and clicked "Next"
    - Clicked "Create" to advance thru Review resources to be created
4. Waited for provisioning to complete
5. Selected the "Publish" tab and published the bot

Are these the same steps you followed? If not, can you try what I outlined above?

**Comment by PeterPekanovics** [comment]
@stevkan Thanks for the response! I think I might have missed adding the QnA Maker to the publishing profile.
However, I eventually decided to go a completely different route, and just called the QnA Maker service through an HTTP request. That actually works much better for me, as I might need to move that QnA Maker resource to our customers Azure acoount.

**Comment by innovacion-now** [comment]
Hello! I'm looking for how to do "call the QnA Maker service through an HTTP request."
I'm able to call it via terminal with CURL but still now with Bot Composer.

**Comment by PeterPekanovics** [comment]
You need to create a new "Send an HTTP request" dialog from the "Access external resources" dropdown.
To the Url field, you need to enter the Url found on the CURL tutorial.
To the body, you put your question.
To the header, you create a key-value pair:
Key: "Authorization"
Value: "Endpointkey YOUR_ENDPOINT_KEY"
