### ISSUE TITLE
Cant sign in to my Azure resource from Bot Composer when i set up LUIS for my bot

### ISSUE THREAD

**Issue by Ncane-bit** [microsoft/BotFramework-Composer#9046]
![image](https://user-images.githubusercontent.com/68059522/157675882-fb05988a-4f4b-4b8f-a057-1ae7803abaa8.png)

**Comment by ramfattah** [comment]
Hi @Ncane-bit, thank you for raising this. We are investigating this issue.

**Comment by ramfattah** [comment]
Hi @Ncane-bit

Are you using composer version 2.1.2? if so, could you please uninstall it and install the previous version of Composer version 2.1.1 to see if you are still getting this error? 

Download Composer version 2.1.1 [Here](https://github.com/microsoft/BotFramework-Composer/releases/tag/v2.1.1) and try to log in again.

Let me know if this worked. Thanks

**Comment by Ncane-bit** [comment]
Hi @ramfattah 
yes i was using v2.1.2 i just unistalled it,i'm installing v2.1.1  i'll let youknow if this fixes the issue

**Comment by ramfattah** [comment]
Sounds good, thanks

**Comment by Ncane-bit** [comment]
Seems like it's been fixed, thank you...
So if i update Composer to the latest version is it not going to give me the same issue again?

**Comment by ramfattah** [comment]
There are several known sign-on issues in the latest composer version. For now, using 2.1.1 is a workaround.

**Comment by ramfattah** [comment]
I am closing this one for now, @Ncane-bit please feel free to re-open if you are still having issues.

**Comment by Ncane-bit** [comment]
Thank you @ramfattah you may close it.
