### ISSUE TITLE
Hero card text is not rich text in MS teams

### ISSUE THREAD

**Issue by afahmy11** [microsoft/BotFramework-Composer#9065]
hi

i am using Hero card as a response in my bot. the card text is formatted correctly when using it from the web client but in microsoft teams it is shown as plain text. is there a way to enable this in MS Teams?

**Comment by stevkan** [comment]
@afahmy11, Unfortunately, no, it is not possible to format a text response, specifically, as rich text. However, this doc, [Format Cards in MS Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?msclkid=af9f3c53ab9911eca45881fef9a07c08&tabs=adaptive-md%2Cconnector-html), discusses how you can pass in Markdown and/or HTML in a card response. You _may_ be able to apply CSS inline styling to the HTML, but I don't know how much of that Teams will honor or ignore.

**Comment by afahmy11** [comment]
thank you, the Markdown styling isn't working with Teams but the HTML one worked
