### ISSUE TITLE
Expire Conversation in Composer

### ISSUE THREAD

**Issue by tingting0118** [microsoft/BotFramework-Composer#9080]
## Unable to expire a conversation in composer with node js

We develope our bot in composer with template Node js and we want to expire the conversation after 5 minutes without interaction.  I found this [tutorial](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiig_jMuOv2AhUSrxoKHY3YBOkQFnoECAgQAw&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DCgaHW5t4XCU&usg=AOvVaw0Ah870lNsm5Zz2W34p81FH) but it's unable to use nuget to install the package Bot.Builder.Community.Components.Tigger.ExpireConversation.3.1.1.nupkg because we don't use C#. There is no this option with npm, so do you know how to expire a conversation in composer ?
It's not difficult in this [document](https://docs.microsoft.com/fr-fr/azure/bot-service/bot-builder-howto-expire-conversation?view=azure-bot-service-4.0&tabs=csharp) but in composer I can't find the same script. 
Not sure if this is something I can configure in Composer or in Azure...

Thank a lot for your help!

**Comment by ramfattah** [comment]
hello @tingting0118, I'm investigating this.

**Comment by ramfattah** [comment]
Looks like this is a community package, have you tried creating an issue in the `Bot Builder Community` repo?

Here is link to the community repo: https://github.com/BotBuilderCommunity
