### ISSUE TITLE
Invalid Response body at PowerVA Unexpected end of JSON input

### ISSUE THREAD

**Issue by eawong-coca-cola** [microsoft/BotFramework-Composer#9087]
## Describe the bug

When trying to publish my bot framework composer to PVA, I get invalid JSON response body with unexpected end of JSON input. Sometimes it gets pushed and sometimes it does not, but the weird thing is that it generates another publish history item that just never stops running after it fails, it's in the screenshot below.

## Version

v2.1.2
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X ] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

1. Open Bot Framework Composer from PVA
2. Login
3. Make update
4. Publish to Bot

## Expected behavior

It should just give you a green check BUT

Gives an error as listed below (unexpected end of json input) and in the logs it gives no detail, and has a second publish start running in the history and has yet to stop

## Screenshots

<img width="890" alt="image" src="https://user-images.githubusercontent.com/68547125/161273935-f638b239-2217-4245-8eb4-1eddce0cb822.png">

**Comment by eawong-coca-cola** [comment]
So I may have resolved this, but what I did was uninstall 3 times and try different versions, until I just resintalled another time and it works. What is the error typically related too?

**Comment by ramfattah** [comment]
Hey @eawong-coca-cola, Thanks for reaching out. 

I've seen some publishing issues before, have not seen this error message before, perhaps it could be related to some parsing issues? Glad you were able to resolve this. 

May I ask, which version of Composer did you switch to for the fix?

**Comment by eawong-coca-cola** [comment]
I thought as much as well - could it be parsing coming back from PVA? I couldn't find errors in composer specifically.

I was originally on v2.0.0 then upgrade to v2.1.2 then back down to v2.1.1 then back up and that was the 'resolution'

**Comment by ramfattah** [comment]
Sweet! thanks for sharing. I'll keep this quick solution in mind.

> could it be parsing coming back from PVA?

Based on the error message, that's what I'm thinking as well. 

As upgrading Composer solved this issue, I'm closing this ticket for now. @eawong-coca-cola, please re-open if you face this issue again. Thanks!

**Comment by yagizhanarslanakinci** [comment]
Same problem here, any upgrade or downgrade didnt solve the problem for me. Also i have composer dialogs acting crazy together with this problem. Most of the time they throw error code 3000 and when i trace to the point they do, its totally random. In a case if they throw error in a loop, next time error is before they send a http request etc. No consistency for me to track if there is a problem or not.
