### ISSUE TITLE
Error in publishing composer bot to Azure app service

### ISSUE THREAD

**Issue by JayHB1** [microsoft/BotFramework-Composer#9102]
Hello,

I am getting below error while publishing bot to Azure app service. 
![image](https://user-images.githubusercontent.com/91305025/162012408-d2ceec80-a390-4078-957f-58b0f644934e.png)

Can you please help to resolve above error. 

Thank you.

**Comment by dmvtech** [comment]
hi @JayHB1 Can you see if you can deploy the zip with the azure cli? From the project folder, you should see a *.zip file. Run the following from a command line:
`az webapp deployment source config-zip --resource-group "<resource-group-name>" --name "<name-of-web-app>" --src "<project-zip-path>"` with the appropriate values replaced.

**Comment by dmvtech** [comment]
Hi @JayHB1 My apologies for the delay.

If the same is happening with azure cli, then this is an environment/configuration issue. Please pursue other troubleshooting avenues with regards to azure cli/Windows/networking/certificates. Once resolved through Azure cli, then test again in Composer. If at that point it still fails in Composer but not in Azure cli, please comment here and we can continue.
