### ISSUE TITLE
Array problem

### ISSUE THREAD

**Issue by axelekenberg** [microsoft/BotFramework-Composer#9106]
Hi! I did a select adaptive expression on an array from an api where i wanted to get all numbers from arrays. Although i only get Null on each number from bot response... PLEASE HELP!

**Comment by dmvtech** [comment]
Hi @axelekenberg 

Can you give some sample data here? We need more info to be able to assist.

- What is your adaptive expression?
- What does the array returned from the api look like?

**Comment by dmvtech** [comment]
Closing due to lack of response and information.
