### ISSUE TITLE
Adaptive card form just works once after submitted

### ISSUE THREAD

**Issue by fernandofas** [microsoft/BotFramework-Composer#9113]
## Describe the bug

Hi there,
I have a few adaptive cards on my Power Virtual Agent bot for different reasons and all of them are forms sending the data to my email through Power Automate.
So, I after filling up the first form from the first adaptive card and submit, I want to fill up another form which is also an adaptive card.
Before the form appears, the bot is giving me the result of the submitted form already.
Is there a way to avoid this conflict?

Reference:
https://powerusers.microsoft.com/t5/General/Adaptive-card-form-just-works-once-after-submitted/m-p/1533953#M3455

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

I recorded the issue here: https://www.kapwing.com/videos/624ec3eee62d030067e2aa06

## Expected behavior

Open another form and send the data.

**Comment by ramfattah** [comment]
Hey @fernandofas -- I'm investigating this.

**Comment by ramfattah** [comment]
@fernandofas 

* Are you able to share a screen snippet of your adaptive dialogs flow design in PVA? 
* Could you please provide a series of steps to reproduce this issue? This will help me better assist you. [Referenced here](https://github.com/microsoft/BotFramework-Composer/blob/main/.github/ISSUE_TEMPLATE/bot-framework-composer-bug.md#:~:text=To%20Reproduce,See%20error)
* By any chance, were you following any documentation? if so, could you please share that doc? 

Thanks.

**Comment by ramfattah** [comment]
@fernandofas 

Glad you were able to find a resolution. 

Closing this one for now, please re-open if needed.
