### ISSUE TITLE
Can not create bots with Node Version 17

### ISSUE THREAD

**Issue by koanplaned** [microsoft/BotFramework-Composer#9114]
Hi,

I can not start my (previously working) bots any longer and also can not create new bots with Composer version 2.1.2 on macOS 12.2.1 (Monerey).

When creating a new bot, I receive following message:
<img width="339" alt="Bildschirmfoto 2022-04-11 um 16 21 04" src="https://user-images.githubusercontent.com/34692365/162760323-f0a0fa16-3430-4bb9-af9f-27b5cf5aa0e0.png">

When starting my bots, I receive following message:
<img width="582" alt="Bildschirmfoto 2022-04-11 um 16 21 42" src="https://user-images.githubusercontent.com/34692365/162760400-a3421cb6-f685-4520-928c-4654136bde9a.png">
 
The second error indicates, that I'm using "an unsupported engine" (node version 17 instead of 10/12/14/16):
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.7.0',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16' },
npm WARN EBADENGINE   current: { node: 'v17.2.0', npm: '8.1.4' }
npm WARN EBADENGINE }
```
But I'm pretty sure, that I already started the bot with my current Node version, because I didn't update it recently. Also, there is an additional error that says, that "dev should not be set in the command line options - where could I adjust that?

```
npm WARN invalid config only="dev" set in command line options
npm WARN invalid config Must be one of: null, prod, production
```

Thanks in advance for your help,
Stefan

**Comment by stevkan** [comment]
Node.js uses a two-track system for managing current, inactive releases and current, active releases. Current, active releases are represented by even numbered versions (10, 12, 14, 16). Current, inactive releases are represented by odd numbered versions (17, for example). After 6 months, current, inactive releases are bumped (17 => 18) which then become the current, active release. It is at this time that the current, inactive release (version 17) is discontinued. You can read more [here](https://nodejs.org/en/about/releases/).

It is for this reason that Node.js v17 is not supported by Composer. It is recommended you install either version 16 for bot development.

**Comment by koanplaned** [comment]
Hi @stevkan,

thank you very much, I didn't knew this and this fixed my issues. 

For Mac users: To "downgrade" your current Node installation to latest current, active release, you just need to visit the official NodeJS website, download the macOS installer and re-install NodeJS (no need to uninstall NodeJS first).
