### ISSUE TITLE
Bot Framework Composer - can't integrate / extend Bot Framework Composer from Power Virtual Agent

### ISSUE THREAD

**Issue by mbjtv** [microsoft/BotFramework-Composer#9122]
Application is opening but it's not functional, in a private network setting do you have list of websites that we need to define internally? application ports need to open?

Is Bot framework composer pass thru proxy or by direct connections?

We can't integrate / extend Bot Framework Composer from Power Virtual Agent

**Comment by dmvtech** [comment]
hi @mbjtv Can you please give some more details? What do you mean by not functional? Can you share any screenshots or error messages?

**Comment by mbjtv** [comment]
> hi @mbjtv Can you please give some more details? What do you mean by not functional? Can you share any screenshots or error messages?
<img width="390" alt="Signin Error_Azure" src="https://user-images.githubusercontent.com/103226554/165217282-a12be85d-b263-4744-8e5e-105b0a0db3bb.PNG">
<img width="234" alt="Signin Error" src="https://user-images.githubusercontent.com/103226554/165217301-28fa127b-de8f-42da-9c5c-f0583ce7b95a.PNG">

**Comment by mbjtv** [comment]
<img width="247" alt="Error Importing Topics to Composer" src="https://user-images.githubusercontent.com/103226554/165217553-afb8611e-ff43-4d49-bc90-74f5f39a0948.PNG">

**Comment by mbjtv** [comment]
Unable to import topics from PVA to Composer

**Comment by dmvtech** [comment]
So, to clarify you have created a PVA bot and are opening it in Composer via:
![image](https://user-images.githubusercontent.com/43397658/166844042-fc23414b-0eea-4c6d-8200-357a15539680.png)


Then when it starts to open in Composer, you get prompted to log, but then receive the error above? Does this happen for new+very simple bot? Are you able to log into http://portal.azure.com and confirm you are part of one or more Azure active directories?

**Comment by mbjtv** [comment]
> So, to clarify you have created a PVA bot and are opening it in Composer via: ![image](https://user-images.githubusercontent.com/43397658/166844042-fc23414b-0eea-4c6d-8200-357a15539680.png) - **Yes, also observed that the application require admin user. Composer already installed but keeps prompting to download and install the app. Did not encountered this using admin user**
> 
> Then when it starts to open in Composer, you get prompted to log, but then receive the error above? Does this happen for new+very simple bot? Are you able to log into http://portal.azure.com and confirm you are part of one or more Azure active directories? - **Yes, it prompted me to login. Then it will try to import the topics from PVA to Composer. This happened to any bot. I was able to login to http://portal.azure.com**

**Comment by dmvtech** [comment]
> Yes, observed that the application require admin access. Composer already installed but keeps prompting to download and install the app.

Composer is prompting to re-download and re-install Composer? What version (`Help->About`) is Composer? Are you able to create (non-PVA) bots from within Composer itself without issue?

**Comment by mbjtv** [comment]
> > Yes, observed that the application require admin access. Composer already installed but keeps prompting to download and install the app.
> 
> Composer is prompting to re-download and re-install Composer? What version (`Help->About`) is Composer? Are you able to create (non-PVA) bots from within Composer itself without issue?

- Yes, Composer is prompting to re-download and re-install. But did not encounter when using Admin access. BTW tried different versions 2.0.0 - 2.1.1 and 2.1.2
![image](https://user-images.githubusercontent.com/103226554/167528199-3cb32f4a-ed45-49ba-b081-fa3122a2442b.png)
- Unable to create (non-PVA) bots from within Composer. See error 
![image](https://user-images.githubusercontent.com/103226554/167528889-a450f338-5a4f-4070-95a2-b5d4b7de690a.png)

- Can you confirm if we need to define the following via Internet/Proxy or Direct Connections?
![image](https://user-images.githubusercontent.com/103226554/167528740-c13c522e-45c8-480e-86cc-a81fec244816.png)
![image](https://user-images.githubusercontent.com/103226554/167528801-9d4d4f34-8fd1-4569-aec2-d9a214ca0f85.png)
Reference: https://docs.microsoft.com/en-us/power-virtual-agents/requirements-quotas

**Comment by mbjtv** [comment]
Can you also check this 
![image](https://user-images.githubusercontent.com/103226554/167546151-4356d675-5a84-4c83-8359-46834f30b3e4.png)

**Comment by mbjtv** [comment]
Hi @dmvtech can you help also provide details how we can login in to Azure using Bot Framework Composer? See error 
![image](https://user-images.githubusercontent.com/103226554/167775590-83e0b03e-3b20-48d6-bed3-cf414278e0a9.png)

Please take note that I don't have issue in signing in portal.azure.com. but saw logs connecting to this site 
![image](https://user-images.githubusercontent.com/103226554/167776816-411e2ca7-7a26-4f1b-9e53-78c1103a757d.png)

**Comment by dmvtech** [comment]
@mbjtv 

Can you run the following on your machine and let me know the results?

- `npm -v`
- 'node -v`

I'm not sure about the proxy config. But let me investigate and find out for you.

**Comment by mbjtv** [comment]
> 

![image](https://user-images.githubusercontent.com/103226554/168205813-108e3910-a7dc-4f51-8efb-04e62ab90b6e.png)

**Comment by AlexChongMicrosoft** [comment]
We checked the AAD login record, didn't find the interactive login. But some non-interactive login records. May I know whether there is some audit log of Bot composer?

**Comment by gabog** [comment]
@AlexChongMicrosoft, sent you an internal email
