### ISSUE TITLE
How to escape a sequence or replace a Json response in bot framework composer?

### ISSUE THREAD

**Issue by Elsa2604** [microsoft/BotFramework-Composer#9127]
Bot framework Composer Version: 2.1.1
Platform : Windows

I'm getting dynamic response as (double \ ) in the Name field 
```json
[
  {
    "Name": "\\Jack",
    "Age": "13"
  },
  {
    "Name": "Paul",
    "Age": "74"
  },
  {
    "Name": "Jim",
    "Age": "48"
  },
  {
    "Name": "\\Diana",
    "Age": "73"
  },
  {
    "Name": "Black",
    "Age": "35"
  }
]
```

But when I try to pass this in dropdown adaptive card.. It is throwing Bad JSON Sequence \J.

Adaptive Template in lg response:

```
# GetCard(collection)
[Activity
     Attachments = ${json(NameCard(collection))}
]
```

```
# NameCard(collection)
-```
{
  "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
      "type": "Input.ChoiceSet",
      "id": "CompactSelectVal",
      "label": "Please select your soldto",
      "style": "compact",
      "isRequired": true,
      "errorMessage": "This is a required input",
      "placeholder": "Please choose",
       "choices":[
       ${join(foreach(collection, item, NameSubmitAction(item)),',')}
       ]
         }
     ],
       "actions": [
    {
      "type": "Action.Submit",
      "title": "OK"
    }
  ]
}```
```
                                
```
# NameSubmitAction(item)
-```
{
  "title": "${item.Name} - ${item.Age}",
  "value": "${item.Name}"
}```
```

![image](https://user-images.githubusercontent.com/104147442/164470541-77176d74-a233-4f9e-8858-fcbe81124b90.png)

**Comment by dmvtech** [comment]
Able to reproduce. Investigating.

**Comment by dmvtech** [comment]
You can strip off the `\\` characters after getting the response. 

So, let's say you get the response and store in the property `dialog.theResponse`. You can then use a `Set Property` action (let's say to `dialog.myNewProperty`) with the following expression:

`=select(dialog.theResponse, x, setProperty(x, 'Name', replace(x.Name,'\\','')))`

Then use that new property to pass in to `NameCard(dialog.myNewProperty)`

The expression uses the `select`, `setProperty` and `replace` prebuilt functions.
https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions

**Comment by dmvtech** [comment]
Closing as solution given.
