### ISSUE TITLE
Filter array by string variable

### ISSUE THREAD

**Issue by dweeb1937** [microsoft/BotFramework-Composer#9130]
I'd like to be able to filter an array by a string variable. I've tried the Edit an array property with a hard-coded value and it works great.
```
"changeType": "push",
"itemsProperty": "user.array2",
"value": "=where(json(user.apiResponse.content).value,x,x.myKey=='magazine')"
```
However when I set the value of x.myKey to equal user.myFilter and make the value of user.myFilter 'magazine', it fails. (If the value of user.myFilter is null then the filter works.) 

This issue raises two questions: 
1. filtering by a string variable seems useful: could that functionality be requested or is this a bug?
2. if not 1, then do others have suggestions of how I make a subarray matching criteria?

**Comment by dmvtech** [comment]
Hi @dweeb1937 I'm not quite sure but am investigating. Can you share an example of the array? What data type is `user.myFilter`?

**Comment by dweeb1937** [comment]
Thank you. Sure can. As I say, replacing the myFilter with a string literal results in success. 

user.myFilter evaluates to "myFilter": "'magazine'":
```
            {
              "$kind": "Microsoft.SetProperty",
              "$designer": {
                "id": "phHz18"
              },
              "property": "user.myFilter",
              "value": "'${dialog.forEachAdvice.value.name}'"
            }
```
Array is like this:```

        "apiResponse": {
          "statusCode": 200,
          "reasonPhrase": "OK",
          "headers": {
            "Cache-Control": "no-cache",
            "Transfer-Encoding": "chunked",
            "Server": "Windows-Azure-Table/1.0",
            "x-ms-request-id": "someid",
            "x-ms-version": "2019-02-02",
            "X-Content-Type-Options": "nosniff",
            "Date": "Tue, 26 Apr 2022 21:55:34 GMT"
          },
          "content": {
            "odata.metadata": "https://someurl",
            "value": [
              {
                "odata.etag": "W/\"datetime'2022-04-20T02%3A22%3A07.7976772Z'\"",
                "PartitionKey": "somekey",
                "RowKey": "step10",
                "Timestamp": "2022-04-20T02:22:07.7976772Z",
                "adviceKey": "magazine",
                "footer": "somefooter",
                "isNewPanel": false,
                "linkText": "somelink",
                "live": true,
                "name": "magazine-2",
                "order": 2,
                "substepsCount": 4,
                "tag": "step",
                "title": "sometitle"
              },
              {
                "odata.etag": "W/\"datetime'2022-04-20T02%3A22%3A07.8256612Z'\"",
                "PartitionKey": "somekey",
                "RowKey": "step11",
				...
			  },
				...
            ]
          }
        }
```

**Comment by dmvtech** [comment]
Hi @dweeb1937 

Thank you for the follow up information. A couple more questions:

1. Are you using the .NET/C# or Javascript/Node version of the runtime?
2. Does `user.myFilter` evaluate to `'magazine'` or `magazine` ?

With the [expression playground](https://playgroundclient.azurewebsites.net/), I am able to get it to work using:

### Expression
`where(json(user.apiResponse.content).value, x, x.myKey==user.myfilter)`

### Data
```json
{
  "user": {
    "myfilter": "magazine",
    "apiResponse": {
      "content": {
        "value": [
          {
            "PartitionKey": "somekey",
            "Timestamp": "2022-04-20T02:22:07.7976772Z",
            "myKey": "magazine"
          },
          {
            "PartitionKey": "anotherkey",
            "Timestamp": "2021-03-20T02:22:07.7976772Z",
            "myKey": "newspaper"
          }
        ]
      }
    }
  }
}
```

But that only works for the .Net version. For Javascript I get an error:
`args[0].trim is not a function`

**Comment by dweeb1937** [comment]
Thanks Dana. Interesting. Yes. I am using .Net. 
I had assumed from the documentation that I needed to wrap the variable in single quotes, so I was doing that. 
Once I took that away, it worked as expected.
Not sure about Javascript and don't know if you want to keep this open because of that so I have not closed it.
Thank you again and apologies for the trouble. 
Regards
DW
