### ISSUE TITLE
When I try to start a new dialog from another one I get "activityProcessed the return type does not match"

### ISSUE THREAD

**Issue by irwinwilliams** [microsoft/BotFramework-Composer#9131]
## Describe the bug
Using the a template that starts with the Greeting, Cancel and Help Dialogs.  I tried to start a new dialog using the Dialog Management menu and got this error, 
"Begin a new dialog: activityProcessed the return type does not match "
## Version
Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ *] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [* ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to plus sign to add new step to the Welcome Dialog
2. Click on Dialog Management > Begin a new dialog
3. Select a dialog you've created

## Expected behavior
Dialog should be linked to without problem

**Comment by ramfattah** [comment]
Hello @irwinwilliams, I'm investigating this.

**Comment by ramfattah** [comment]
Hey @irwinwilliams 

On a fresh Composer 2.1.2 install, I'm not able to reproduce this issue. 
![image](https://user-images.githubusercontent.com/38049078/165144224-6df435be-a5ee-462a-9390-ee719128e6b1.png)

Video Demo: https://i.gyazo.com/83d4d861e44521d80e64e24b48a8be5a.mp4

#

Perhaps I'm missing something from my end, any additional steps I shall follow to reproduce this issue?
Also, are you using C# or Node (Preview) templates in composer?
