### ISSUE TITLE
Composer unable to find LUIS files after publish

### ISSUE THREAD

**Issue by ryub3n** [microsoft/BotFramework-Composer#9132]
## Describe the bug

After publishing the Calendar bot in the Enterprise Assistant template, Composer is giving errors saying it cannot find the file

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [x] Safari
- [ ] Firefox
- [x] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Successfully deploy the Enterprise Assistant template
2. Add trigger phrases to an intent for the Calendar skill and successfully publish it
3. Close the bot solution and re-open it

## Expected behavior

It shouldn't be throwing errors as the files do exist.

## Screenshots
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/24279903/165061070-7a558183-376c-4a27-8d70-24632cfba538.png">

Files exist in the respective folders but Composer is confused.

**Comment by ramfattah** [comment]
Hey @ryub3n, I'm investigating this.

**Comment by ramfattah** [comment]
@ryub3n 

Update: I was able to reproduce this issue.

Here are the steps I took:
1) Created an Enterprise Assistant Template from the following documentation https://docs.microsoft.com/en-us/composer/templates/enterprise-assistant-tutorial
2) From the `Calendar` skill, I clicked on `OnIntent (CreateEvent)` trigger
3) Added the following trigger phrase ` - ram event`
4) After closing composer and re-opening the trigger, I get the following error
     ![image](https://user-images.githubusercontent.com/38049078/165194703-18d59bfb-e315-4c33-b773-244637aa8bfc.png)

**Comment by ryub3n** [comment]
@lauren-mills - Thank you. I will try it out.

**Comment by ryub3n** [comment]
The fix works. Thanks!
