### ISSUE TITLE
Unable to get a value for KnowledgeBaseID from State

### ISSUE THREAD

**Issue by tamasschmolcz** [microsoft/BotFramework-Composer#9134]
## Describe the bug

I have  fully restored previously developed Composer Bot. I was able to re-created the Azure resources and  to re-published the bot. This included QnA maker and LUIS content. All good so far. But I am now facing an issues with the QnA-Maker connection.

When triggering a QnA Maker driven dialog, I receive the error-message:

"Unable to get a value for KnowledgeBaseID from State"

I have already triple-checked the appsetting.json etc. . All values are set and correct. I also tried to hardcoded the KB-ID in the composer dialog, but it did not help. Do you have any further ideas?

Thanks

## Version

v.2.1.2

## Browser

- [X] Edge

## OS

- [X] Windows

## Expected behavior

Dialog is followed as designed.

## Screenshots

![image](https://user-images.githubusercontent.com/48097252/165512355-2518ece8-7ad3-4659-a483-f93a043a5510.png)

![image](https://user-images.githubusercontent.com/48097252/165512764-aa6bbcf5-aef8-4c51-a0c4-9d5c9d335384.png)

**Comment by tamasschmolcz** [comment]
Btw. I also took care that there have been running the latest bot-process, when testing different configuration.

**Comment by tamasschmolcz** [comment]
Hi @anishprasad01 , yes it was actually the first thing I did before republishing the bot again.

**Comment by tamasschmolcz** [comment]
@anishprasad01 I was able to re-deploy the bot with the original composer version - this was too obivious ;). Thanks

**Comment by Rohan1203** [comment]
I'm deploying the composer bot in heroku and getting the same.
