### ISSUE TITLE
Getting "" is not a valid LUIS application id. error when trying to use forms dialog in bot composer

### ISSUE THREAD

**Issue by PrajwalNaik2027** [microsoft/BotFramework-Composer#9136]
**Continuation of bug  #9123** 
## Describe the bug
![image](https://user-images.githubusercontent.com/103985127/165672324-eab950c2-bf6f-42dd-a676-60a738d1a8c7.png)
Getting "" is not a valid LUIS application id. error when trying to use forms dialog in bot composer, even though LUIS details is provided in composer. 
Since, I am unable to run the bot from composer. I was using vs code to do so. But facing the above error due to it.
I tried to reproduce the steps with other bots and on other machines but the error still exists.

## Version

Bot Framework Composer (v2.1.2)

**Comment by PrajwalNaik2027** [comment]
Hi @dmvtech when I am trying to run the bot via vs code, it is not creating an app in the LUIS portal like it dose when it is ran via composer. To supply the LUIS prediction resource we first need to create an app in the LUIS portal right? Correct me if  I am wrong and please provide the relative information I need to know to run the bot successfully

**Comment by dmvtech** [comment]
Correct. It will not create the apps outside of Composer. I wasn't sure if this had once created the apps in LUIS (like perhaps you ran once in Composer, but could no longer). If the apps aren't get created with Composer or when you run it, you'll need to create them and line everything up within `\generated\luis.settings.composer.<REGION>.json`.

**Comment by PrajwalNaik2027** [comment]
Hi @dmvtech, no the app was never created from the composer, the file \generated\luis.settings.composer.<REGION>.json is not present in the bot folder. What should I do?

**Comment by PrajwalNaik2027** [comment]
Hi @dmvtech we are making bots for costumer purpose so need the procedure to be simpler. Could you tell me by what time will form dialog be available as a permanent feature in composer, and we need not run it via vs code.

**Comment by johnataylor** [comment]
There are no plans to add this to Composer as a first-class feature at this time. You can either use code or you can extend your Composer solution with code. You can write reusable Custom Actions for example.
