### ISSUE TITLE
Problems with datediff

### ISSUE THREAD

**Issue by taoofstefan** [microsoft/BotFramework-Composer#9142]
Hello,

I am trying to get the number of days difference between two dates. I get the dates via user input in the format YYYY-MM-DD.

I save them in dialog.checkin and dialog.checkout.

![image](https://user-images.githubusercontent.com/36883480/166119896-0003dfbc-d32f-4b18-81ce-81f2597fb09e.png)
(same setup for dialog.checkout)

When I try this:

`{
          "$kind": "Microsoft.SetProperty",
          "$designer": {
            "id": "4Cb8Ct"
          },
          "property": "dialog.nights",
          "value": "dateTimeDiff(${dialog.checkout}, ${dialog.checkin})"
}`

![image](https://user-images.githubusercontent.com/36883480/166119870-129cf956-b3ca-4819-8e55-c32f38ea4f81.png)

I get the following error message:

roomBooking.en-us.lg:dateTimeDiff(dialog.checkout, dialog.checkin) must have two ISO timestamps. [SendActivity_0ooqX2_text] Error occurred when evaluating expression. [SendActivity_0ooqX2] Error occurred when evaluating expression. [__temp__eecbdb65cf354c5e851dde10721cd305] Error occurred when evaluating expression., roomBooking.en-us.lg:dateTimeDiff(dialog.checkout, dialog.checkin) must have two ISO timestamps. [SendActivity_0ooqX2_text] Error occurred when evaluating expression. [SendActivity_0ooqX2] Error occurred when evaluating expression. [__temp__c0051c0681864be8a1f0ea78b289be61] Error occurred when evaluating expression.

What did I do wrong?

Thanks in advance. This is very new and I've got a lot to learn.

**Comment by lauren-mills** [comment]
Hi, @taoofstefan, you probably need to run your date values through [formatDateTime()](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#formatdatetime) to make sure they are using a standard format. 

You can just wrap your datetime in that method to get the default format (which I think should work for your case), or provide your own format depending on your scenario. Hope that helps!

**Comment by taoofstefan** [comment]
Thank you @lauren-mills this helped. My output format is now:

`formatDateTime(this.value[0].Value, 'dd-MM-yyy', 'de-DE')`

 I am still stuck on what I actually want to achieve, find the difference between the two dates.

When I set the property dialog.nights as mentioned above I get this output:

`dateTimeDiff(25-05-2022, 20-05-2022)`

How do I get the difference of the 2 dates (here 5)? Maybe my approach is wrong

**Comment by lauren-mills** [comment]
Ah, I see. DateTimeDiff() returns the difference between the two dates in ticks (and integer representation of time). You can convert that value to days using the ticksToDays() method. 

So ticksToDays(dateTimeDiff(25-05-2022, 20-05-2022)) should give you the number 5 as a result. 

For more info on the datetime methods available, you can refer to [this documentation.](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#date-and-time-functions)

**Comment by taoofstefan** [comment]
Thank you so much, I made it work.

In this case, the method really seems to only accept the full ISO format to make the changes as I wanted them.

**Comment by Akas371** [comment]
what's is the final expression you have used. I am getting  same error

**Comment by taoofstefan** [comment]
> what's is the final expression you have used. I am getting same error

I did it like this in my case. First I captured the two dates in this format (check-in and check-out dates in my use case):

`=formatDateTime(this.value[0].Value, 'yyyy-MM-ddTHH:mm:ss.fffZ', 'de-DE')`

and then I did formate the dateTimeDiff with the check-out and -in dates, using the ticksToDays value (in a new property):

`=ticksToDays(dateTimeDiff(dialog.checkout, dialog.checkin))`

I hope this is clear, let me know if you have further questions.

**Comment by Akas371** [comment]
Many Thanks!!. It's working now. 
Is it possible to calculate only the working days as the difference between two dates and remove the non- working days(weekend) and holidays.

**Comment by Akas371** [comment]
Sure, I'll share it here.
