### ISSUE TITLE
For publishing taking too much time still not publishing.

### ISSUE THREAD

**Issue by kishan2** [microsoft/BotFramework-Composer#9149]
Issue - For publishing taking too much time still not publishing.

![image](https://user-images.githubusercontent.com/22518920/166690864-e1719058-459f-4b10-a7e0-8517c91fb8dd.png)

Description - When i am publishing my changes via Bot framework it takes too much time and still not publishing, also not getting any error.

Bot framework version  
Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

Please provide any work around , since 4 hours i am getting this issue before that i was able to publish.

**Comment by kishan2** [comment]
@dmvtech  since 3 hours it is publishing also not getting any error , please see below screen shot for reference. 

![image](https://user-images.githubusercontent.com/22518920/166750143-ab5d2c39-1d91-48e5-a227-60f6ef21c626.png)

**Comment by dmvtech** [comment]
> I am working Power virtual agent and create PVA from bot framework and publishing to PVA(Azure). it may be window

Ah, okay. That's not it then.

Have you tried closing composer and attempting to republish? Are you able to upgrade to v`2.1.2` and test if that still doesn't work?

**Comment by kishan2** [comment]
@dmvtech Yes I tried to close bot composer multiple times since yesterday but still not able to publish.
Also one of my colleagues working on v2.1.2 and he is also facing same issue.

**Comment by kishan2** [comment]
@dmvtech  please suggest a solution or any work around

**Comment by dmvtech** [comment]
Hi @kishan2 

Please reproduce the error when running with the debug flag for Composer and then send the output of the terminal.

Here are the steps:
- Go to Composer's install location (mine is at C:\Users{username}\AppData\Local\Programs\Bot Framework Composer)
- Open a terminal here
- run `set DEBUG=composer*`
- run the executable from the terminal Ex. "Bot Framework Composer.exe"

**Comment by kishan2** [comment]
@dmvtech  I followed above steps but not able to execute from terminal getting below error.
![image](https://user-images.githubusercontent.com/22518920/167345230-c929b622-3cb6-41eb-b247-eb2ed47df92f.png)

**Comment by dmvtech** [comment]
Hi @kishan2 

Please surround the exe name with quotes `"`.

For example:

`C:\users\YC252RA\AppData\Local\Programs\"Bot Framework Composer.exe"`

**Comment by kishan2** [comment]
[termainalLog.zip](https://github.com/microsoft/BotFramework-Composer/files/8672245/termainalLog.zip)
@dmvtech  Thanks for guidance. Now i am able to run exe file in terminal and I have attached terminal log. Please see

**Comment by LizethRegules** [comment]
Facing the same problem. Yesterday working fine. Today haven't been able to publish to PVA.

**Comment by kishan2** [comment]
@dmvtech @LizethRegules   my issue has been resolve now I am able to publish my bot changes from bot framework.
I dont know what was the problem

**Comment by LizethRegules** [comment]
> @dmvtech @LizethRegules my issue has been resolve now I am able to publish my bot changes from bot framework. I dont know what was the problem

@kishan2 may I ask you how are you connected from BFC to PVA? I get an error of self signed certificate, but I do not want to publish to Azure, only to PVA, so I'm wondering if you have an Azure subscription that you are connecting to BFC?

**Comment by gabog** [comment]
it seems the original issue reported by @kishan2 self healed, closing this one
