### ISSUE TITLE
Self Hosting instructions require corrections.

### ISSUE THREAD

**Issue by Parakleta** [microsoft/BotFramework-Composer#9157]
https://docs.microsoft.com/en-us/composer/how-to-host-composer

Step g. for installing the dotnet packages needs a semicolon or double ampersand before the `dpkg`

**Comment by Parakleta** [comment]
Also, I couldn't get step b to work without first using the `nodesource` instructions from https://github.com/nodesource/distributions#deb, and step c was redundant after that.

**Comment by ramfattah** [comment]
investigating.

**Comment by ramfattah** [comment]
Hey @JonathanFingold, 

Looks like the following doc needs some minor updating? 
https://docs.microsoft.com/en-us/composer/how-to-host-composer

#

### Proposing the following changes:

b. Install Node.js
> Note: If you are unable to install Nodejs, you may need to use the `nodesource` instructions from https://github.com/nodesource/distributions#deb

```bash 
apt install nodejs 
```

g. Get the updated Ubuntu packages for dotnet.

```bash 
wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb
```
