### ISSUE TITLE
HTTP Request - GET - Content/Body should send or field should be hidden

### ISSUE THREAD

**Issue by sammydeprez** [microsoft/BotFramework-Composer#9158]
## Describe the bug

When making use of the HTTP Request block following issue happens:
When doing a GET request to an API the Content/Body is not send to the endpoint.

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS
- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a HTTP Request task in your bot that GETs data from an REST Endpoint. Fill in the body field
2. Check the trace and notice that the body/content is not used.
3. Change to POST and notice it will be available in the trace.

## Expected behavior

Body or Content should always be send to the endpoint when the field is filled in the UI

### GET trace
Variables
![image](https://user-images.githubusercontent.com/14163485/167855138-92bf66b7-e707-42e3-8e5a-d6abffc93cce.png)
Result
![image](https://user-images.githubusercontent.com/14163485/167854951-26efa9ea-59ec-47ae-af72-5e77beac8fea.png)

### POST trace
Variables
![image](https://user-images.githubusercontent.com/14163485/167855340-0f196704-8cee-4c92-87d8-c98e3ddf4e53.png)

Result
![image](https://user-images.githubusercontent.com/14163485/167854714-65a9ba7f-235c-42d2-bb8c-23fc11ea1046.png)

**Comment by dmvtech** [comment]
Hi @sammydeprez 

Typically (historically) [GET](https://httpwg.org/specs/rfc7231.html#GET) requests _do not_ include a body, where methods like POST and PUT do. That is why it has been implemented in this manner. Although there have been [changes](https://httpwg.org/specs/rfc7231.html#rfc.section.B) that will allow for it:

> To be consistent with the method-neutral parsing algorithm of [RFC7230], the definition of GET has been relaxed so that requests can have a body, even though a body has no meaning for GET. (Section 4.3.1)

As this is working as designed, I would recommend using POST instead. But if you **require** the use of GET with a body for your application, we can change this to a feature request and see if that can be implimented.

**Comment by ceciliaavila** [comment]
Closing as the PR with the fix was merged in BotBuilder-DotNet.
