### ISSUE TITLE
Push to PVA is not working. 

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/BotFramework-Composer#9159]
## Describe the bug

Usually when I push the bot framework composer to PVA I had no problem, but lately it appears as loading for until an hour and does nothing. Pull from selected profiles shows no problem, it brings the latest version of my PVA, but the push never completes. 
![image](https://user-images.githubusercontent.com/100951593/167864967-91d02d26-cc16-4f11-9a7d-b7e6c2297171.png)

## Browser

Microsoft Edge

## OS

Windows

## To Reproduce

1. Go to Bot Framework composer
2. Click on Pull form selected bots a PVA
3. Do some changes, create a trigger for example.
4. Push changes to PVA.
5. See error

## Expected behavior

I expect to be able to push changes to my PVA like I used to before.

**Comment by LizethRegules** [comment]
This is the error message it appears after 30 minutes or so. I used to see that error message, then try again and then it worked, but now not even that. 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/100951593/167870922-4a9569f9-1343-41c5-a40a-4578a0dc53d0.png">

**Comment by dmvtech** [comment]
Thank you @LizethRegules. 

I'm linking a similar issue in case they are the same root cause: https://github.com/microsoft/BotFramework-Composer/issues/9149

We will investigate and let you know what we find.

**Comment by LizethRegules** [comment]
@dmvtech Hi
The problem still persists on my side. Were there any rule changes in how to publish the Bot Framework Composer? 
I used to only pull form PVA (which still works)
Made some changes
Publish bot to PVA with just one click, but now it won't work. 

After about 30  minutes of waiting, it appears an error message like the one I posted above talking about self signed certificate in the certificate chain. Am I missing permissions or licensing? Could you please help me solve this. Thank, you

**Comment by LizethRegules** [comment]
@dmvtech @ryanlengel 
Actually, it looks like several of them are still loading after 2 days. And the error message in the log only says internal error. 
Problem started on 5.11.22 at 8:33am CT. 

<img width="715" alt="image" src="https://user-images.githubusercontent.com/100951593/168284722-d971daa4-cd8b-45f9-b5bb-cfa16baf9404.png">

**Comment by dmvtech** [comment]
Hi @LizethRegules apologies for the delay. Due to the error regarding the self-signed certificate; is there a way you can try and isolate this further? 

- Is there a firewall that is being used between the client machine and the cloud? If so, is there a way to bypass that temporarily as a test?
- Does this reproduce from other machines?
- Are you aware of any self-signed certificates being used on the client machine, firewall, or anywhere on your network?

**Comment by LizethRegules** [comment]
Problem was when importing the bot for the first time to BFC. One must be careful when saving it in the local machine. 
Problem got solved in my side. Closing this issue
