### ISSUE TITLE
Any Luis "training" on luis.ai is lost when republishing the BOT

### ISSUE THREAD

**Issue by metkhoo** [microsoft/BotFramework-Composer#9160]
## Describe the bug

Any LUIS.AI training is lost if you republish the bot.

## Version

v2.1.2

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS
- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce

Steps to reproduce the behaviour:
1. Create a BOT with LUIS language understanding
2. Create trigger with three phrases
3. Send a simple response
4. Test the bot with the three phrases
5. Go to "luis.ai" portal and login
6. Look for intents and add a new phrase.  Train Test and publish
7. Go back to bot check that new phrase works
8. Republish the bot
9. Try the new phrase (it wont work)
10. Go to luis.ai portal - you will see that the added phrase has gone.

## Expected behaviour
Republishing the bot would ADD to the phrases not remove any existing ones
How is it possible to "Train" Luis with BOT Composer?

## Screenshots
N/A

**Comment by UAWILSO** [comment]
I don't think this is a bug, but I agree this would be a nice thing to have, if we were able to edit/deploy the intents to our Bots from the LUIS portal.

**Comment by metkhoo** [comment]
I thought that a there would be an option somewhere in the "settings" JSON that allowed control of it do we could do an initial deploy and then just control it from the LUIS portal (or something like that).   Does no such setting exist?

**Comment by metkhoo** [comment]
I would have thought adding that would be fairly trivial since it basically means "publish without LUIS update"

**Comment by ryanlengel** [comment]
Hello @metkhoo, Bot Framework Composer uses LU files as the source of truth. So any changes that you make in the LUIS portal will need to be copied back into Composer. You can export your LU files from the portal by:
- Go to applications page
- Select your application
- Select the Export dropdown from the menu
- Select Export as LU
