### ISSUE TITLE
Cannot publish BFC to PVA

### ISSUE THREAD

**Issue by LizethRegules** [microsoft/BotFramework-Composer#9168]
## Describe the bug

Before the 10th of May, I was able to pull my PVA to BFC and publish from BFC to PVA. I have never had an Azure subscription. Nonetheless, I was able to do that. Now, I keep getting the same error message that I cannot use a self signed certificate chain. 

## Version

v2.1.2

## Browser

Microsoft Edge

## OS

Windows

## Expected behavior

I want to be able to publish my BFC bot to PVA. I don't want to publish it to Azure, only to PVA. 
I am only using BFC to create Adaptive cards through HTTP requests, and then all the other steps are done in PVA. 

## Screenshots

![image](https://user-images.githubusercontent.com/100951593/168606327-c46c9732-3b87-4e3a-b6a9-3fab9eef3074.png)

**Comment by LizethRegules** [comment]
If this helps somehow:

I tried editing publishing profile and won't show me my environments in power platform when I click log-in.
<img width="578" alt="image" src="https://user-images.githubusercontent.com/100951593/168648308-e937504b-f5f6-432e-8f2d-5fdd4594783c.png">
<img width="552" alt="image" src="https://user-images.githubusercontent.com/100951593/168648367-5af211db-acc0-4a15-831e-f1f4de390128.png">

**Comment by LizethRegules** [comment]
If I create a new publishing profile it only allows me to connect to Azure. It won't show the option to publish to PVA
<img width="545" alt="image" src="https://user-images.githubusercontent.com/100951593/168649804-8a457521-e21d-426a-a03f-761e1f643eaf.png">

**Comment by dmvtech** [comment]
Known issue. Cause yet to be determined. Linking to existing issue: https://github.com/microsoft/BotFramework-Composer/issues/9159
