### ISSUE TITLE
"Bot Framework Composer" is damaged and can't be opened.

### ISSUE THREAD

**Issue by claudiutomescu** [microsoft/BotFramework-Composer#9191]
## Can't open BotFrameworkComposer on macOS Monterey

I've downloaded the binaries for the Bot Framework Componser v2.0.0 for Mac, and I'm trying to run it but I'm getting the error message  ["Bot Framework Composer" is damaged and can't be opened. You should move it to Trash.]
I've rebooted my Mac, I've installed the latest updates and re-checked dependencies, but still no go.

## Version

The file downloaded is BotFrameworkComposer-2.0.0-mac.zip
There is a newer version which I found linked from Microsoft Learn pages which is BotFrameworkComposer-2.1.2-mac.zip but I'm facing the exact same issue with that one.

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

macOS Monterey 12.4 (Intel-powered 2019 MacBook Pro)

## To Reproduce

1. Go to 'https://github.com/microsoft/BotFramework-Composer/'
2. Click on 'Download Composer for Mac' (https://aka.ms/bf-composer-download-mac)
3. Extract the "Bot Framework Composer.app" and move it to Applications folder
4. Open Applications folder and click "Bot Framework Composer"

## Expected behavior

Bot Framework Composer should start. Instead I'm getting an error message: "Bot Framework Composer" is damaged and can't be opened. You should move it to Trash.

## Screenshots

![image](https://user-images.githubusercontent.com/1310010/169052964-fb3cff26-24ed-4d40-a54e-38aeab93e269.png)

**Comment by ramfattah** [comment]
Hey @claudiutomescu 

I was able to open Composer using the link from [step 2](https://github.com/microsoft/BotFramework-Composer/issues/9191#:~:text=Click%20on%20%27Download%20Composer%20for%20Mac%27%20(https%3A//aka.ms/bf%2Dcomposer%2Ddownload%2Dmac))

After opening, it prompted me to update:
![image](https://user-images.githubusercontent.com/38049078/169195842-e2fc430e-3d50-4bf2-9753-a7c2a62de943.png)


I'm using `macOS Monterey version 12.3.1`
<img src="https://user-images.githubusercontent.com/38049078/169196013-68d66392-481e-4b28-b4a0-e73e92864cc7.png" width="500"/>

#

I don't think this is a bug within Composer.

Have you had a chance to look at this [apple StackExchange solution?](https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t)

**Comment by claudiutomescu** [comment]
Hey @ramfattah

Thank you for your quick response. After reading the 2 articles you shared above and trying the `xattr` on the app with no success, I've ended up re-downloading the .zip archive and this time the app worked properly without having to do anything at all.

**Comment by ramfattah** [comment]
Glad to hear it's working properly.

**Comment by ramfattah** [comment]
Closing this one for now, @claudiutomescu feel free to re-open if you are still having issues.
