### ISSUE TITLE
Adaptive cards $when not actioned by bot framework composer in webchat or emulator

### ISSUE THREAD

**Issue by dweeb1937** [microsoft/BotFramework-Composer#9205]
## Describe the bug

I'm using Bot Framework Composer to make a chat bot. When using an adaptive card, json elements should be [conditionally hidden](https://docs.microsoft.com/en-us/adaptive-cards/templating/language#conditional-layout-with-when) when the following exists
`"$when": "False"`
However that doesn't seem to happen in emulator or webchat. 

Is this a bot framework issue?

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows 10 pro
- [ ] Ubuntu

## To Reproduce

1. Create adaptive card attachment for send response.
2. Add an textblock saying Hi, and include a $when line set to false.
3. Run the bot and you'll still see Hi.
4. You can try setting value of $when to "${1==2}", "False", "false", "FALSE", it will still show.

## Expected behavior

Should not see Hi.

## Additional context

```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
		{
            "type": "TextBlock",
            "text": "Hi 1=2",
            "spacing": "Small",
            "size": "Default",
            "wrap": true,
            "$when": "${1==2}"
        }, 
        {
            "type": "TextBlock",
            "text": "Hi false",
            "spacing": "Small",
            "size": "Default",
            "wrap": true,
            "$when": "false"
        }, 
        {
            "type": "TextBlock",
            "text": "Hi False",
            "spacing": "Small",
            "size": "Default",
            "wrap": true,
            "$when": "False"
        }, 
        {
            "type": "TextBlock",
            "text": "Hi FALSE",
            "spacing": "Small",
            "size": "Default",
            "wrap": true,
            "$when": "FALSE"
        }
	]
}
```

**Comment by dmvtech** [comment]
Hi @dweeb1937 Thank you for reporting this.

Unfortunately, adaptive card templating is not yet implemented in the SDK.

Please see more info here:

- https://github.com/microsoft/BotFramework-Composer/issues/8798
- https://github.com/microsoft/botframework-sdk/issues/6477
