### ISSUE TITLE
File explorer stopped working

### ISSUE THREAD

**Issue by jelleDK** [microsoft/BotFramework-Composer#9206]
## Describe the bug

I can't start any new project or open an existing project due to file explorer not showing up. As you can see in the below screenshots.
![image](https://user-images.githubusercontent.com/57387033/169807708-0d27c463-c60c-47e3-8c3c-8dbdd4b2b89a.png)
![image](https://user-images.githubusercontent.com/57387033/169807773-a6f5511d-57fe-4aaf-b9cf-f44b8dba84f6.png)

## Version
![image](https://user-images.githubusercontent.com/57387033/169807959-d0190efc-9340-4ebc-b3a8-1d4530047acb.png)

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Really don't know what happend. Stopped working all of a sudden. have already deleted/reinstalled

## Expected behavior

Show a file explorer

**Comment by anishprasad01** [comment]
Hi @jelleDK,

I have a couple suggestions you can try.

- Clear any type of cache for the program.
- Try the reinstall to a different directory.
- If you selected "Install for all users", try to install just for your user, or vice versa.
- If you have controlled folder access or other security settings that may prevent Composer from accessing your filesystem, disable them for the Composer application alone.

**Comment by jelleDK** [comment]
> Hi @jelleDK,
> 
> I have a couple suggestions you can try.
> 
> * Clear any type of cache for the program.
> * Try the reinstall to a different directory.
> * If you selected "Install for all users", try to install just for your user, or vice versa.
> * If you have controlled folder access or other security settings that may prevent Composer from accessing your filesystem, disable them for the Composer application alone.

Hi Thanks for the reply.

Clearing "all site data" did the trick for me.

Thanks a lot!
