### ISSUE TITLE
Add Custom Commands application as a skill in Bot framework composer application

### ISSUE THREAD

**Issue by ridasaleem0** [microsoft/BotFramework-Composer#9212]
The documentation (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-commands-integrate-remote-skills) gives an idea about how to export the Custom Commands application as a skill, however, there is no skills tab available in the Speech studio under Custom commands settings. 

Is there a way to export our commands app as a skill inside the bot framework application?

**Comment by ridasaleem0** [comment]
Any leads? @stevkan

**Comment by stevkan** [comment]
@ridasaleem0 - Unfortunately, the BotFramework Team does not have any control over Cognitive Services Speech Studio nor what features they choose to support or not support. If you are experiencing an issue with the Speech Studio application or its documentation, you will need to open an issue with that team in their repo or related forum.
