### ISSUE TITLE
Something went wrong error when clicking on Show Code feature

### ISSUE THREAD

**Issue by prateek1406** [microsoft/BotFramework-Composer#9216]
## Describe the bug
Not able to see the code view when I click on "Show Code" feature button. Also, same issue is there when I am clicking to edit an attachment card to send a response in the form of a card.

When clicking on show code, an error box is showing that "Something Went Wrong", Please report an issue on Github. Also, not able to edit the card attachment which I am trying to send as a response in the form of a card.

## Version
2.1.2

## Browser
Microsoft Edge

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- Edge

## OS
Windows- 64bit

- [ ] macOS
- Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'any project you created'
2. Click on any dialog
3. Click on 'Show Code'

## Expected behavior
It should show the code view of the respective dialog.

## Screenshots
<img width="960" alt="Screenshot 2022-05-31 113334" src="https://user-images.githubusercontent.com/30924463/171103729-41d92be4-a578-4fbb-aab7-7ff274f9959d.png">
<img width="958" alt="Screenshot 2022-05-31 113122" src="https://user-images.githubusercontent.com/30924463/171103736-9a1b3423-04ed-4d3f-b387-f437975c288a.png">
<img width="947" alt="Screenshot 2022-05-31 113146" src="https://user-images.githubusercontent.com/30924463/171103741-a0b2a3cf-5ff2-47cb-a379-7d0ccd17ad77.png">
<img width="960" alt="Screenshot 2022-05-31 113221" src="https://user-images.githubusercontent.com/30924463/171103747-17dd818e-3db7-4939-8a95-590aea09ea70.png">
<img width="957" alt="Screenshot 2022-05-31 113246" src="https://user-images.githubusercontent.com/30924463/171103750-50b26922-fab8-4fa5-ba94-f81703037cce.png">

## Additional context
Please help me in finding the solution to this issue.

**Comment by dmvtech** [comment]
Hi @prateek1406 

Can you first try clearing the local cache/storage and then see if it still happens?

Here are the steps:

1. View->Toggle Developer Tools
2. Application tab
3. Storage
4. Clear site data
5. Close Composer
6. Reopen Composer and the bot
7. Try showing code

![image](https://user-images.githubusercontent.com/43397658/171694556-80d5367f-0edb-4f38-9c96-717b36acc4f6.png)

**Comment by dmvtech** [comment]
Closing due to lack of reply. If assistance is still needed, please comment and we can reopen.

**Comment by maru55** [comment]
![image](https://user-images.githubusercontent.com/37395784/229985355-a3ecc87f-7028-4e52-8663-3231fd76a175.png)

Still issue exists, i am unable to paste the code it is showing loading..

![image](https://user-images.githubusercontent.com/37395784/229985448-965e5a4b-7726-4e5d-9ff6-088a97439ac9.png)
