### ISSUE TITLE
Adaptive Card Data binding

### ISSUE THREAD

**Issue by Ikhan24** [microsoft/BotFramework-Composer#9218]
Hi I am bringing a string variable from Power automate from PVA and wanted to data bind that array of strings into an Adaptive card I have made. I Passed the string in botframework composer through a Json function however the output of the variable is giving the following output as shown below instead of making it into an array of strings
![image](https://user-images.githubusercontent.com/32466509/171438405-251872c6-23cc-43b5-aeff-ef30552a40f2.png)
How do I bind this data to my adaptive card choice set. Please do let me know. 

Thanks!

**Comment by dmvtech** [comment]
hi @Ikhan24 

Can you give a bit more data or examples? How exactly are you passing a string through a Json function? If you can provide examples (doesn't have to be exact data/value) on what this string may look like before hand, how the assigning/function is done and what the expected outcome should look like will help a lot.
