### ISSUE TITLE
LG resources are not deleted when the referenced actions are deleted

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#922]
## Version
What version of the Emulator are you using.

## Describe the bug
When delete a step, I hope related LG resource can be deleted too. But currently, the related LG cannot be deleted. 

## To Reproduce
1. Create a step with LG
2. Delete this step
3. Check LG editor, the LG item is still there.

## Expected behavior
Related LG should be removed with step.

## Additional context

[bug]

**Comment by yeze322** [comment]
closed by #1580
