### ISSUE TITLE
Unable to pass Content-Type : application/json as header in Http request in bot framework composer

### ISSUE THREAD

**Issue by Elsa2604** [microsoft/BotFramework-Composer#9220]
In Postman, when I try to pass these headers, I'm able to get the response as expected
![tempsnip](https://user-images.githubusercontent.com/104147442/171686234-210f33bc-0594-401e-9e75-21cedeb7601e.png)

But, In Bot composer, when I passed the Content-Type in header, It is throwing 406 status code.
![0](https://user-images.githubusercontent.com/104147442/171686518-fc9677a5-cec2-43cf-804d-bfae1479d0de.png)
![1](https://user-images.githubusercontent.com/104147442/171686757-71096729-bb97-4ec5-9f19-c54efc74426e.png)

![2](https://user-images.githubusercontent.com/104147442/171686980-771c3e94-dc3d-49ee-a53c-b7209a16e8f8.png)

**Comment by dmvtech** [comment]
hi @Elsa2604 

First, the the `Send an HTTP request` action already has a Content Type field. Is there a reason you are not using that?
![image](https://user-images.githubusercontent.com/43397658/172263001-91b19810-15d0-449e-a2a3-72a1dbb2abe3.png)

Secondly; it appears that the action _does_ use the `Content Type` field when the request is a **POST**. But ignores it (and your own specified Content Type header when it is a **GET** request. 

I will investigate further to see what may be the cause.

**Comment by dmvtech** [comment]
@Elsa2604 Are you sending content in your GET request?

**Comment by Elsa2604** [comment]
> @Elsa2604 Are you sending content in your GET request?

No, Content type in send an HTTP request is "contentType" (which is optional) but i want to send the header as "Content-Type"

**Comment by dmvtech** [comment]
The 'contentType' field is the internal (to Composer/botframework) name. Which, in the end, is what is populated into 'content-type'. It's optional and will be populated as `application/json` if so.  If you want `content-type`, use the `Content type`/`contentType` field.

**Comment by dmvtech** [comment]
Hi @Elsa2604 Are you able to use the built in field to apply the content-type header?

**Comment by Elsa2604** [comment]
> Hi @Elsa2604 Are you able to use the built in field to apply the content-type header?

No @dmvtech

**Comment by Elsa2604** [comment]
I  used another approach by internally calling this api using another api

**Comment by Elsa2604** [comment]
Thank you @dmvtech
