### ISSUE TITLE
Unable to open shared composer files in a different system

### ISSUE THREAD

**Issue by vidyakdil** [microsoft/BotFramework-Composer#9222]
If we share the entire composer file to a team mate and try to open it in their system, the dialogs are not running. If we click on the start button after opening dialogs in composer, it's keeping on loading but not starting the dialogs

**Comment by dmvtech** [comment]
hi @vidyakdil How are you sharing the bot? Is this something you just copied and gave to the teammate? Or are you putting on a file share, github repro, etc?

**Comment by vidyakdil** [comment]
We zipped the entire folder and shared the same with the team.

**Comment by dmvtech** [comment]
Thank you @vidyakdil.

Can you confirm that all settings in Composer have been re-added or confirmed in place? For example, 'MicrosoftAppPassword` doesn't get saved to the appsettings.json file, so it must be re-added (if being used).

Do you see any errors in the Problems section (lower left of Composer)?

Can you try (with Composer closed) removing content from the `bin` and `obj` folders and then loading and starting the bot in Composer?

**Comment by dmvtech** [comment]
Closing due to lack of response. If you still need assistance with this issue, please confirm you tried the above steps and supply any additional information or error messages.

**Comment by vidyakdil** [comment]
Hi, issue was with packages. I uninstalled the packages and re installed them in the bot and bot started to work
