### ISSUE TITLE
Priority broken for RegexRecognizer

### ISSUE THREAD

**Issue by davhdavh** [microsoft/BotFramework-Composer#9223]
## Describe the bug

RegexRecognizer are always processed "in order", but it is impossible to change that order using the Priority.

Example:

```
"recognizer": {
    "$kind": "Microsoft.RegexRecognizer",
    "intents": [
      {
        "intent": "cancel",
        "pattern": "^(?:cancel|quit|stop|end)"
      },,
      {
        "intent": "MyCommand",
        "pattern": "."
      },
      {
        "intent": "help",
        "pattern": "^(?:/|--?)?(?:support|advice|help|\\?)(\\s+(?<helpon>.+))?"
      }
    ]
```
Will always trigger "MyCommand" even if typing "help".
Changing Priority in UI for "MyCommand" adds a '"priority": 99999'  in the commands' json, but does not alter the order of the commands in the RegexRecognizer section.
![image](https://user-images.githubusercontent.com/1201165/173024734-24b88660-0be3-4135-b8f2-a0e37032e1cc.png)

(Another smaller bug, if you added a priority and then unsets it, it actually always sets it to 0)
(Another documentation bug, is that it is not defined what the order is when a priority is not set)

## Version
2.1.2

## To Reproduce

1. Set recognizer to Regex
2. Add 2 intents with some catchall expression
3. Set priority on 1 higher than the other and swap around as needed
4. See only one of the intents are ever executed no matter the priority (or lack thereof)

**Comment by anishprasad01** [comment]
Hi @davhdavh,

Thank you for the report. We're aware of this issue, and we'll add it to the backlog for prioritization. We do not have an ETA at this time for when a fix will be available.

**Comment by ceciliaavila** [comment]
We created issue [#6434](https://github.com/microsoft/botbuilder-dotnet/issues/6434) in BotBuilder-DotNet to address this issue.
