### ISSUE TITLE
Multi language responses not showing up in certain languages

### ISSUE THREAD

**Issue by jelleDK** [microsoft/BotFramework-Composer#9227]
## Describe the bug

I'm currently developing a chatbot that is available in 4 languages. I started by adding all the responses in English (default language), now when I wanted to add the translation for the other languages (being Dutch, Spanish and Chinese). I noticed some of the responses that were used in English disappeared when trying to add the dutch translation.

## Version
Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Create a bot with different languages. Add English text, when switching to dutch to add translation response disappears.

## Expected behavior

Possibility to add the translation of the message.

## Screenshots
Text available for translation in Spanish

![image](https://user-images.githubusercontent.com/57387033/173319988-598004e0-0fb6-4fc1-a7e1-f33de791c5ac.png)

Text disappeared in Dutch
![image](https://user-images.githubusercontent.com/57387033/173320129-de4f62b4-413b-400d-9819-77de12476179.png)

**Comment by stevkan** [comment]
@jelleDK, I'll attempt a repro of this. If possible, could you supply a copy of your bot? Having this would help isolate where the cause might be.

**Comment by stevkan** [comment]
@jelleDK, as you re-opened the issue, are you needing continued help on this?
If so...

> @stevkan Unfortunately i can't give out a copy of the bot.

Are you able to create a simple bot that reproduces the issue that you can post here?

**Comment by jelleDK** [comment]
> 

I’m unable to reproduce this issue

**Comment by tdurnford** [comment]
@jelleDK If you re-encounter this issue, please feel free to reopen or file a new issue.

**Comment by jelleDK** [comment]
> @jelleDK If you re-encounter this issue, please feel free to reopen or file a new issue.

I still have this issue, the only thing I said is that I'm at the moment not able to create a blank project and recreate this issue.

**Comment by sammydeprez** [comment]
Hi @stevkan , together with @jelleDK  we made a little video about what to us is still a bug

[Video](https://cronos-my.sharepoint.com/:v:/g/personal/dekeuje_cronos_be/ERfHEbOMF7FKuWcG6x47A0MBi9fCkUZzHfx6gIUjwDQkIw?e=EwahUJ)

Notice that the responses are used in the other language but is still not showed in the translation function.

**Comment by cwhitten** [comment]
Hi @sammydeprez - the workaround in the video is the option available to you. At the time of creating a new language, all templates will be copied over automatically for you, but any templates manually created afterwards will also need to be created manually across all languages.
