### ISSUE TITLE
Create New Bot using Bot composer throw an error process.chdir()

### ISSUE THREAD

**Issue by EmadKhella** [microsoft/BotFramework-Composer#9249]
I am attempting to create new bot using Bot composer and I got an error message that 
**Error hit when instantiating remote template: process.chdir() is not supported in workers**

## Version
I tried with version 2.1.2 and down grade to 2.1.1 but same issue in both

## Steps to reproduce the behavior:

1. Go to 'Bot composer Home'
2. Click on 'create new'
3. See error

## Screenshots
![image](https://user-images.githubusercontent.com/54295822/174722663-08f90f70-4a4c-491e-9dd5-14e91ebfbc1b.png)

**Comment by anishprasad01** [comment]
Hi @EmadKhella,

The error message suggests that at some point in the bot creation process, the script is attempting to change directories, but this operation is unsupported in your environment. 

- Where are you trying to run Composer?
- What language runtime is this?
- What OS?

**Comment by EmadKhella** [comment]
hi @anishprasad01,

- I am trying to run composer on my local machine "C:\Users\<userprofile>\Bots" after install all pre-requisites.
- Runtime type "Azure Web App".
- "Windows 10"

**Comment by EmadKhella** [comment]
Hi @anishprasad01,
I changed the path to different path out of my profile and it is working perfectly.
I assume that composer does not accept any folders under user profile .

**Comment by MelinaCodez** [comment]
I have this same problem, it does not let create the project under \Users\user profile folder\

**Comment by bytejan** [comment]
Got the same issue on macOS, for both, the desktop and web version.

**Comment by EmadKhella** [comment]
> Got the same issue on macOS, for both, the desktop and web version.

hi @bytejan,
try to change the project path out of your user profile folder . I believe it will work

**Comment by bytejan** [comment]
Hi @EmadKhella 

Thank you for the fast reply, it works indeed!

Still weird since the bot framework composer asked for permission at the beginning for the user directory. So you would expect that it would be the other way around (that it would not work in other folders).

I still think it is a bug, but at least I can continue :)

**Comment by adrwh** [comment]
I had written multiple bots inside /Volumes/dev (not in my user profile) and as of today I am now getting this same chdir() error.

I can however create Bots in my user profile folder (/Users/username/bot), go figure.
