### ISSUE TITLE
Bot Deployment for Bot Framework Composer

### ISSUE THREAD

**Issue by ahmedmahmoudR** [microsoft/BotFramework-Composer#9251]
"Bot Framework Composer" can be deployed on premises or is mandatory to deploy on Azure only ?
If yes could you please provide any reference for that.

Thanks

**Comment by dmvtech** [comment]
@ahmedmahmoudR You can host Composer on premises, it is not mandatory to deploy to Azure. I will see if I can find any pertinent documentation for you.

**Comment by ahmedmahmoudR** [comment]
Hello @dmvtech 
Any Update

**Comment by dmvtech** [comment]
Hi @ahmedmahmoudR 

Apologies for the delay. There are no specific directions for hosting on premises (or even in Azure).

The basic instructions for running Composer with a local build (as opposed to running the Electron client on a machine) can be found here:
https://github.com/microsoft/BotFramework-composer#build-composer-locally
