### ISSUE TITLE
QnAmaker multi-turn prompts don't show on Teams, Composer prompts do

### ISSUE THREAD

**Issue by sgooderham** [microsoft/BotFramework-Composer#9252]
I am making a chatbot using Composer that calls a QnAMaker knowledge base that contains multi-turn prompts. These prompts work fine when tested in Composer, Web Chat, and QnAMaker itself:

![1](https://user-images.githubusercontent.com/105870364/175030291-76de9a69-85e7-4ff7-93eb-1eb368a41bf7.png)

When testing the bot in Teams, however, the prompts don't appear:

![3](https://user-images.githubusercontent.com/105870364/175030312-2f5e57b5-dfc4-421a-9f29-41f779cb7961.png)

I have tried using the Teams channel in the bot resource, as well as connecting it to a Teams app through the App Studio, and neither of them produce the prompts. I can't find anything specific to multi-turn integration with Teams in the documentation so am unsure why this would be happening?

Prompts created within Composer do appear in Teams:

![image](https://user-images.githubusercontent.com/105870364/175030591-b60375a0-f96c-4cf6-9451-6fe9bbef4de7.png)

So it is only QnAMaker multi-turn prompts that are causing this problem. However, there are no settings in QnAmaker or Teams that relate to this, so it must be something that needs changing in Composer to get it to work. Any help would be appreciated.

**Comment by anishprasad01** [comment]
Hi @sgooderham,

It may be that the QnA Maker implementation of multi-turn prompts is not supported in Teams. Have you attempted to run the Bot Framework multi-turn prompts sample? Does it work in your Teams environment?

**Comment by anishprasad01** [comment]
This might also be because Suggested Actions are not supported in Teams. You may have to simply make use of something other the QnA multi-turns. The Teams samples should provide guidance there.
