### ISSUE TITLE
Pass Bot Composer variables values to PVA (Power Virtual Agent)

### ISSUE THREAD

**Issue by adeelnazir786** [microsoft/BotFramework-Composer#9254]
We are able to access all variables from PVA (Power Virtual Agent) to Bot Framework Composer using ${virtualagent.VARIABLE_NAME_HERE}, as mentioned in the documentation.

https://docs.microsoft.com/en-us/power-virtual-agents/advanced-bot-framework-composer

![image](https://user-images.githubusercontent.com/60339149/175247659-286d1735-7df6-4c67-b748-dff7defa9739.png)

The concern is, that we need to get new variables created in composer back into PVA (Power Virtual Agent). How it would be possible?

For example:
From PVA (Power Virtual Agent), I've called the composer there I've created a for-loop to ask many questions. Now I need all user answers stored in variables back into PVA (Power Virtual Agent). for further process.

**Comment by dmvtech** [comment]
I am investigating.

**Comment by adeelnazir786** [comment]
In addition to the above question,
I've called a composer from PVA (Power Virtual Agent). In the composer, I've loop with questions. At the end of the loop, I want to return all user answers JSON lists back to Power Virtual Agent. That is something essential for us... 
Please help to find out the solution.

**Comment by adeelnazir786** [comment]
Any updates?

**Comment by dmvtech** [comment]
Hi @adeelnazir786 Unfortunately not. I thought the `External sources can set values` property would get it to work, but it doesn't seem to be working for me. I'm continuing to investigate and will update as soon as I have some findings.

**Comment by dmvtech** [comment]
Ok, my problem was that I didn't save within PVA 🤦🏻‍♂️.


So, I have this working. The `External sources can set values` seems to work for me.

Here's what I have in PVA:
![image](https://user-images.githubusercontent.com/43397658/176541850-cf8a8d35-518d-4b16-94a3-d2f57c70efe6.png)


And here Composer:
![image](https://user-images.githubusercontent.com/43397658/176541691-8ce5e653-e891-4ed9-9e15-52bd5d9436ce.png)

And here is the result:
![image](https://user-images.githubusercontent.com/43397658/176541732-7c3b7fbb-2a8e-4d73-92ca-c88eeb095a14.png)

**Comment by dmvtech** [comment]
Hi @adeelnazir786 Did that work for you?

**Comment by dmvtech** [comment]
Closing as answered. If this did not resolve the issue for you, please comment with more information and we can reopen.

**Comment by adeelnazir786** [comment]
The single-question answer is working fine. 
Can you please create a list of questions and call into the loop... 
try to ask 2 or 3 questions in the loop and push them into 1 variable dynamically.
I need the list of questions' answers list in a single variable.
