### ISSUE TITLE
Skill integration with Root bot

### ISSUE THREAD

**Issue by Sfinks7s1** [microsoft/BotFramework-Composer#9262]
Please help me how to correctly integrate a root bot with a skill bot if they both have a dependency on different luis configurations and have different triggers for processing this or that intent.
Root bot and skill both are created using bot composer.
I see several options for solving the issue:
1) merging expressions for luis in the root bot and, accordingly, triggers should also be located in the root bot
2) separate use. Root boot + root luis \ skill bot + skill luis (but how? Orchestrtator?)

**Comment by dmvtech** [comment]
Hi @Sfinks7s1 

> how to correctly integrate a root bot with a skill bot if they both have a dependency on different luis configurations and have different triggers for processing this or that intent.

What do you mean by correctly integrate? Both root and the skill are bots in their own right and can have different LUIS configurations/applications as you have said. Can you elaborate on an example of what you are looking to handle?


> merging expressions for luis in the root bot and, accordingly, triggers should also be located in the root bot separate use. Root boot + root luis \ skill bot + skill luis (but how? Orchestrtator?)

Again; I'm unclear on the specifics of what you are looking to accomplish. Please give a short, simple example.

**Comment by Sfinks7s1** [comment]
> Hi @Sfinks7s1
> 
> > how to correctly integrate a root bot with a skill bot if they both have a dependency on different luis configurations and have different triggers for processing this or that intent.
> 
> What do you mean by correctly integrate? Both root and the skill are bots in their own right and can have different LUIS configurations/applications as you have said. Can you elaborate on an example of what you are looking to handle?
> 
> > merging expressions for luis in the root bot and, accordingly, triggers should also be located in the root bot separate use. Root boot + root luis \ skill bot + skill luis (but how? Orchestrtator?)
> 
> Again; I'm unclear on the specifics of what you are looking to accomplish. Please give a short, simple example.

Bots created using bot composer:

root bot + luis 1 + trigger (intent 1)
+
skill bot + luis 2 + trigger (intent 2)
=
The message from the user for recognition is sent only to "luis 1" from the root bot and is not sent to "luis 2" for recognition.

There is a root bot connected to "luis 1" and containing the trigger "intent 1", as well as a skills bot connected to "luis 2" and containing a trigger on "intent 2".
I add a skill to the root bot and expect that the phrase intended for processing "luis 2" will send to "luis 2", and the trigger from the skill will work on the received "intent 2" from "luis 2"
But this does not happen.
Maybe something needs to be corrected in the configs or somehow use the orchestrator?

**Comment by dmvtech** [comment]
hi @Sfinks7s1 

When you implement a `Connect to a skill` action from the root bot, you can configure the setting `Allow interruptions`.  

When this is set up to `false`, any utterance or interaction to the skill will stay in that skill. Nothing said to the skill will be handled by the root bot. On the converse, if set to `true`, then the root bot will be 'listening' to any communication/utterance and will be handling it before sent on to the skill (if appropriate).

Depending on the above setting and "where you are" in the conversation/bot, that will determine how it is handled. For further example, if you are in the skill (haven't ended/exited yet) and the utterance 'intent 1' comes to it, then that can be either handled by a trigger or an unknown intent. If a user is in the root bot and wants the utterance `intent 2` to go to the skill; then just put a trigger in the root that will then start the skill (which will then handle it).

If you are able to share an example bot (in a github repro ideally), that might help us understand the scenario you are describing. I can also make changes to explain any solutions.

**Comment by dmvtech** [comment]
Hi @Sfinks7s1 Did any of the above info help? Are you able to share an example or sample?

**Comment by dmvtech** [comment]
Closing due to lack of reply.
