### ISSUE TITLE
Limited trace output from bot

### ISSUE THREAD

**Issue by Sfinks7s1** [microsoft/BotFramework-Composer#9263]
Good day!
I created a bot using bot composer. 
After launching the bot, I see a lot of traces. 

![image](https://user-images.githubusercontent.com/5566636/175934562-71671c36-118f-4e3d-b160-4639dd216624.png)

How do I limit the output to warning messages only (for example)?
I understand it should be in appsettings?

**Comment by Sfinks7s1** [comment]
> @Sfinks7s1, can you elaborate on where the traces are displaying? Are the traces showing in the Output tab in Composer or are you seeing this somewhere else?

in output tab and in elastic/kibana after deploy bot in corporate place.

**Comment by stevkan** [comment]
@Sfinks7s1 - thank you for your patience. There is a possible workaround that I am investigating. I will keep you posted on what I find.

**Comment by stevkan** [comment]
@Sfinks7s1 - I'm still not sure where you are seeing that logging. When I check the Output tab in Composer, I am not seeing logging of that type.

![image](https://user-images.githubusercontent.com/18403946/177630952-425b360e-c55a-4266-bb5e-936999fda7b6.png)

However, there are two places in the bot's settings that may affect the logging you are encountering, if the above is accurate. If you click 'Configure' for your bot and then toggle on the Advanced Settings View option, you will see the bot's JSON settings. In there, you can alter both the "Logging" as well as the "Telemetry".

Logging is a top-level property and should look like the below. You can change the values which will affect the general logging for the bot seen in the above image.

```JSON
"Logging": {
  "LogLevel": {
    "Default": "Information",
    "Microsoft": "Warning",
    "Microsoft.Hosting.Lifetime": "Information"
  }
}
```

Telemetry is located under "runtimeSettings" which is another top-level property and will look like the below. You can change the "logActivities" and "logPersonalInformation" property values to either `true` or `false`. These affect the types of data that is sent to Application Insights. You can read more about these in this doc, [Add telemetry to your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0&tabs=csharp).

```JSON
"telemetry": {
  "logActivities": true,
  "logPersonalInformation": false,
  "options": {
    "connectionString": "InstrumentationKey=0f5b8dea-6f83-4ab2-940a-bc4014a97903;IngestionEndpoint=https://westus2-2.in.applicationinsights.azure.com/"
  }
}
```

Outside of those two options, I think the only other filtering you could do would be in Application Insights, itself. But, if it's logging in Composer you are trying to work around, I wouldn't expect this to affect that.

**Comment by Sfinks7s1** [comment]
@stevkan Thank you so much for your research. The fact is that the bot was designed in the corporate template of the project and there was a module running through the dependencies, which wrote all this extra trace. Extra tracing is not a bot problem.
