### ISSUE TITLE
How can I use skills without publishing them to Azure?

### ISSUE THREAD

**Issue by Sfinks7s1** [microsoft/BotFramework-Composer#9264]
Good day!

Scenario:
1) created root bot and added local skill bot. With bot composer.
2) created azure bots in Azure for root and skill bots.
3) I want to use skill bot by url from root bot. Is it possible to create a manifest without publishing skills in Azure? Without a manifest, I can't add skill to root bot via bot composer.

Can I edit or create a manifest in Azure without publishing skills?

**Comment by dmvtech** [comment]
hi @Sfinks7s1 Let me double check on this and get back to you.

To clarify; you have created the skill in Azure, but you don't want to publish it yet. But you want to want to consume a local skill in the root bot. Is the root bot published yet?

**Comment by Sfinks7s1** [comment]
I have solved this problem. 

Created the manifest.json locally manifest.json and zipped
`{
  "$schema": "https://schemas.botframework.com/schemas/skills/v2.2/skill-manifest.json",
  "$id": "Skill-0007e413-af70-4e4d-83e1-c09d32d3c000",
  "endpoints": [
    {
      "protocol": "BotFrameworkV3",
      "name": "skill",
      "endpointUrl": "https://......./api/messages",
      "description": "<description>",
      "msAppId": "0000cc009-7dda-4bb3-b226-c5cb16464000"
    }
  ],
  "name": "skill",
  "version": "0.1",
  "publisherName": "skill",
  "activities": {
    "Skill": {
      "type": "event",
      "name": "Skill"
    },
    "Auth": {
      "type": "event",
      "name": "Auth"
    },
    "Login": {
      "type": "event",
      "name": "Login"
    },
    "conversationUpdate": {
      "type": "conversationUpdate"
    }
  }
}`

![image](https://user-images.githubusercontent.com/5566636/176146932-a50c795b-e597-499d-ac53-eec1f92cfdd1.png)
