### ISSUE TITLE
Compliance - Security: add semmle when project is made public

### ISSUE THREAD

**Issue by yochay** [microsoft/BotFramework-Composer#927]
more info https://fuselabs.visualstudio.com/Composer/_workitems/edit/37134 and https://fuselabs.visualstudio.com/Composer/_workitems/edit/36999
https://fuselabs.visualstudio.com/Composer/_workitems/edit/36998

**Comment by a-b-r-o-w-n** [comment]
https://lgtm.com/projects/g/microsoft/BotFramework-Composer
