### ISSUE TITLE
Bot Framework Composer is Unable to send HTTP request to localhost

### ISSUE THREAD

**Issue by rahuloo7** [microsoft/BotFramework-Composer#9273]
## Describe the bug
External HTTP call is not working for both localhost as well as graphql servers too. It's resulting in "An error occurred posting activity to the bot. Internal Server Error" in the web chat interface.
On GraphQL
while making the post request with body of type object

{
  "operationName": null,
  "variables": {},
  "query": "<query>"
}
is resulting in 400 bad request but it's working well with postman and other tools. I have tried different approaches too but it didn't help.

## Version
2.1.2

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to DialogFlow and choose any trigger
2. Click on Add (+) ->Access external resources ->  Send an HTTP request -> fill in the details ->Start the bot
3. Scroll down to Web Chat

## Expected behavior

I was expecting a json response back but it was failing to make the connection. I have tried the same url every where and it is working.

## Screenshots
<img width="445" alt="bot-framework-issue" src="https://user-images.githubusercontent.com/17781906/176900112-77f8bb1b-adcb-4493-9821-8b5479f76421.PNG">

**Comment by ramfattah** [comment]
Hi @rahuloo7, I'm investigating this one.

**Comment by ramfattah** [comment]
Hi @rahuloo7,

Looks like I'm not able to reproduce this issue. 

I successfully made an HTTP GET request to GitHub API by following this doc 
https://docs.microsoft.com/en-us/composer/how-to-send-http-request?tabs=v2x

HTTP GET request (Access external resources):
![image](https://user-images.githubusercontent.com/38049078/177475713-13aeae2a-21ec-446d-be3c-ff66bec4b794.png)

Output:
![image](https://user-images.githubusercontent.com/38049078/177476252-0c4c8083-3dd5-4a9f-88bd-5d080f5df812.png)

**Comment by rahuloo7** [comment]
It's not working when i am trying to connect to **localhost**. for ex: url: https://localhost:3000/data

**Comment by rahuloo7** [comment]
**Another issue**
When i am making **external API** call to a **Graphql** endpoint with a **body of type object.** it was not workingg especially when i am passing in the query, otherwise it's working. The same query is working well again on postman.

**Comment by rahuloo7** [comment]
![image](https://user-images.githubusercontent.com/17781906/177876152-d792937c-24de-4df4-becd-be332843271a.png)

**Comment by ramfattah** [comment]
Hi @rahuloo7, thanks for the update.

I'm not able to reproduce this issue. Created API with ASP.NET Core; [documentation here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio).

Tested Composer 2.1.2 HTTP request with the following:
* `localhost` API request
* `POST` request, body of type object


localhost HTTP POST request works as expected:
![image](https://user-images.githubusercontent.com/38049078/178896899-c966aecd-58d5-4ce3-8287-83585e79211c.png)
