### ISSUE TITLE
Twitter adapter in bot composer nodejs

### ISSUE THREAD

**Issue by diegofn** [microsoft/BotFramework-Composer#9275]
How can I install the twitter adapter in a bot based on nodejs in composer app?

## Version
Composer version 2.1.2 

## Browser
- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Click on 'bot' built on NodeJS
2. Click on package-manager
3. Search adapter-twitter

I expect that the adapter-twitter is avaiable and 
https://www.npmjs.com/package/@botbuildercommunity/adapter-twitter

## Screenshots

![Screen Shot 2022-07-04 at 1 44 52 PM](https://user-images.githubusercontent.com/981273/177205337-f7e51f03-7342-46bb-9da2-297805cf3c03.png)

**Comment by stevkan** [comment]
@diegofn, these [docs](https://docs.microsoft.com/en-us/composer/how-to-create-packages) explain how to build a package for use in Composer. Unfortunately, they don't explain how to do this for an NPM package which is what I am looking into. I'll let you know what I find.
