### ISSUE TITLE
Index based input for web chat Multi-Choice user input confuses UX 

### ISSUE THREAD

**Issue by davidmw** [microsoft/BotFramework-Composer#9276]
## Describe the bug

I need to provide a small series of sequentially numbered choices to the user -- ideally in the Multi-Choice control.

Example series:  Grade 5, Grade 6, Grade 7, Grade 8, Grade 9

Ideally the user could tap one of the options as a suggestedAction button or could type any of the following to input Grade 5 as response:  5, Grade 5

If I create the array of choices as a Structure Choices it is easy to specify synonyms like: 5, Grade5.  The intended value of Grade 5 will be returned when either synonym is input.

However the default behaviour of supporting the input of the choice index of the desired item is problematic.  User types '4' and will be unintentionally setting a value of 'Grade 8.'

If the choice array is presented as a text list we get: 1) Grade 5, 2) Grade 6, 3) Grade 7, 4) Grade 8, 5) Grade 8.  If the index numbers are hidden (or not) this index input support is a very odd thing to enable by default on this control.  When I type a 5 I mean Grade 5, not Grade 8.

The Multi-Choice control would be more useful and flexible if index-based input is an optional configuration property. If disabled then all small integer input would be an unknown response unless specifically provided as choice name or synonym.

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ X] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ X] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
Hi @davidmw 

> The Multi-Choice control would be more useful and flexible if index-based input is an optional configuration property. If disabled then all small integer input would be an unknown response unless specifically provided as choice name or synonym.

You can both disable numbers (ex: `5`) and ordinals (ex: `Fifth`) in the prompt. 
![image](https://user-images.githubusercontent.com/43397658/177883881-7701019b-d417-4efe-b8fd-2673e18427a3.png)

Code:
```json
"recognizerOptions": {
  "recognizeOrdinals": false,
  "recognizeNumbers": false
 {
```

**Comment by davidmw** [comment]
@dmvtech That is a big help - completely missed these in the recognizes section. Thanks!
