### ISSUE TITLE
Error calling npm to fetch template.\

### ISSUE THREAD

**Issue by k5reeves** [microsoft/BotFramework-Composer#9286]
I am receiving the following error when attempting to create a new bot.  Anyone have any idea how to resolve?

Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm install -g --prefix

Microsoft Edge on Windows 10

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

**Comment by dmvtech** [comment]
Thank you @k5reeves 

Can you run the following command in an empty directory from a terminal? This is to ensure that npm is working normally:

`npm install @microsoft/generator-bot-empty`

Once complete, let me know if it was successful, or share what the error message is. Then you can delete that folder and it's contents.

**Comment by k5reeves** [comment]
***@***.***

Keith Reeves | Experience Design Manager, Knowledge Management | Learning Solutions | UnitedHealthcare
(office)  763-283-2326  | (email)  ***@***.******@***.***>
[LS_Expect Differently_email sig_v1]

**Comment by dmvtech** [comment]
Hi @k5reeves 

I don't know if something went wrong, but I don't see the results from the terminal. All I see in your response is:

`***@***.***`

**Comment by k5reeves** [comment]
C:\Users\kreeves4>npm install @microsoft/generator-bot-empty
npm notice
npm notice New major version of npm available! 7.13.0 -> 8.14.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.14.0
npm notice Run npm install -g ***@***.******@***.***> to update!
npm notice

up to date, audited 708 packages in 3s

36 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Keith Reeves | Experience Design Manager, Knowledge Management | Learning Solutions | UnitedHealthcare
(office)  763-283-2326  | (email)  ***@***.******@***.***>
[LS_Expect Differently_email sig_v1]

**Comment by dmvtech** [comment]
Hi @k5reeves 

Apologies for the delay. Can you please run the following, then re-launch Composer and then try again?
`npm install -g npm@8.14.0`

**Comment by dmvtech** [comment]
Closing due to lack of response. If assistance is still needed, please comment with the findings and we will reopen.

**Comment by k5reeves** [comment]
I’m not having any luck getting it to work.  I now have the most up to date versions of npm and NodeJS but am still getting the exact error below.

npm install -g –prefix C:\Users\kreeves4\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error --no-optional @microsoft/generator-bot-empty@*



Keith Reeves | Experience Design Manager, Knowledge Management | Learning Solutions | UnitedHealthcare
(office)  763-283-2326  | (email)  ***@***.******@***.***>
[LS_Expect Differently_email sig_v1]
