### ISSUE TITLE
Bot created using Composer is not logging the Telemetry track events to the Application insights.

### ISSUE THREAD

**Issue by SandeepBhagoji202** [microsoft/BotFramework-Composer#9303]
**I have a Chatbot built using Core Bot with QnA Maker Template from composer. I have added the Telemetry track event actions to log some of the Custom properties. But , I don't see any of those events getting logged to the azure application insights.**

**Version - v(2.1.2)**

**Browser**

- [ ] Chrome
- [ ] Edge

 **OS**

- [ ] Windows

**Steps to reproduce the behavior:**

1. To create a sample Bot with  "Core bot with QnA maker" template using Composer.
2. Add telemetry event action to any of the properties and Load the events to the Azure application insights.

**Additional Information:**

 I have a  FAQ Chatbot built using "Empty bot" template and It loads all the telemetry track events to the app Insights. But I don't see the same Behavior in this Chatbot built using "Core bot with QnA Maker" .

**Comment by ramfattah** [comment]
Hi @SandeepBhagoji202, I'm investigating this one.

**Comment by SandeepBhagoji202** [comment]
Thanks @ramfattah .

**Comment by SandeepBhagoji202** [comment]
Hi @ramfattah  , I don't actually think the problem is with Template because I happened to check that the Telemetry track events and all the Pageviews  were logging properly in the last month. But as of now , I don't see any telemetry track events or Pageviews getting logged in. I can only see the Parent Dialog getting logged as a single page view. Even most of the custom events are not loaded. 

Could you please let me know this.

**Comment by SandeepBhagoji202** [comment]
Yes @ramfattah  , I did update the Adaptive runtime package to 4.16.1. Earlier It was  4.15.2 and even with this runtime, I didn't see these pageviews , telemetry track events and some of the custom events logging. So I updated the runtime version to 4.16.1 to see if they might log.

**Comment by ramfattah** [comment]
Hi @SandeepBhagoji202, thanks for the update.

Is telemetry not being logged in specific area in the dialog? Or is it not working at all? 
I will attempt to reproduce this issue today using Core bot with QnA maker template today and report back. Thanks.

**Comment by ramfattah** [comment]
Hi @SandeepBhagoji202, 

I was able to reproduce this issue.

Ran the following tests in `Greeting` trigger:
1. Add telemetry track event **outside** of foreach loop
     * Works in application insights
3. Add telemetry track event **inside** foreach loop
     * Doesn't work in application insights


Example, Composer set up:
![image](https://user-images.githubusercontent.com/38049078/179161337-60203574-8511-4280-a608-ac449ddbdf69.png)


Custom Telemetry Track event is working fine outside of foreach loop
![image](https://user-images.githubusercontent.com/38049078/179161405-60a953ef-eba3-477a-8f2b-fc5e36825477.png)

**Comment by ramfattah** [comment]
This issue is related to https://github.com/microsoft/botbuilder-dotnet/issues/6367
> After upgrading Composer's Bot.Builder.Dialogs.Adaptive.Runtime to any version greater than 4.15.0, telemetry does not seem to work inside for each loop and child dialogs.

There is pull-request for this issue that was merged `jun, 30, 2022` (14 days as of now): 
https://github.com/microsoft/botbuilder-dotnet/pull/6391

**Comment by msomanathan** [comment]
This issue will be fixed in the upcoming release as part of the PR #6391.
