### ISSUE TITLE
Unknown Errors Allow Interruptions the return type does not match

### ISSUE THREAD

**Issue by SyedAhmadFarooqGillani** [microsoft/BotFramework-Composer#9304]
## Describe the bug
![image](https://user-images.githubusercontent.com/93131627/178956129-f6ecdd8f-36ec-41d2-a6c2-4628b94aeb7b.png)
![image](https://user-images.githubusercontent.com/93131627/178956195-ccc1163c-4c53-4284-a040-5a7062b4c5cb.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by SyedAhmadFarooqGillani** [comment]
Those errors are automatically removed after few days only 3 left.This is the issue with composer itself it is unable to check that code is right.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SyedAhmadFarooqGillani** [comment]
It is automatically solved now after a couple of days. I think the composer itself is having some bug issues.

**Comment by ramfattah** [comment]
Thanks for the update. Closing this issue. @SyedAhmadFarooqGillani, please re-open if needed.

**Comment by saikrishna-dev** [comment]
Hi @ramfattah, I am experiencing the same bug now, I built using composer, published my bot then when I psuhed my composer code to my repo using Visual studio, i came back to composer and foudn 15 errors on my Prompt blocks with same error and for prompt configurations. Any fix for this?
