### ISSUE TITLE
validation and key-word extraction in the same user input 

### ISSUE THREAD

**Issue by chia-lun** [microsoft/BotFramework-Composer#9310]
## Describe the bug

I have been trying to do validation (other-> validation->validation rules) and key word extraction (in user input) but the entity extraction somehow did not work (the entity is extracted but the property was not set to the value). I tried to track it with the bot framework emulator and found out every time the entity extraction is conducted, the LuisV3 trace happens twice one right after another (I assume the second time the entity extraction is set to an empty string, but not sure about it). 

I also have a question about the order of validation and entity extraction that is not directly related to this bug: which is goes first? Will the user input get extracted first and then validated?

## Version

- Bot framework composer (v2.1.2) <br />
- SDK v4

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new question 
2. In 'User Input', set `property` to `user.email`, `value` to `=coalesce(@email)`, add `@ prebuilt email` in expected reponses
3. I think we can forget about validation for now as it works on my end (it is just a regex email validation)

## Expected behavior

 The property should be set to the extracted entity and get validated. 

## Screenshots

This is the section for reproduction of the bug: <br />
<img width="997" alt="Screen Shot 2022-07-15 at 2 42 44 PM" src="https://user-images.githubusercontent.com/54944966/179627582-a52902af-7b4b-4ef0-b315-6660aa1b184c.png">

<br />
Here you can see the first time the entity did get extracted:
<br />
<img width="1333" alt="Screen Shot 2022-07-15 at 2 42 00 PM" src="https://user-images.githubusercontent.com/54944966/179627611-156ef82c-3169-44bb-9e1f-371f74d7a48a.png">

<br />
But the second time the entity is set to an empty string:
<br />
<img width="1332" alt="Screen Shot 2022-07-15 at 2 42 10 PM" src="https://user-images.githubusercontent.com/54944966/179627633-a90d10e1-57a9-402a-a077-7dd58abe3f2e.png">

**Comment by dmvtech** [comment]
I am investigating.

**Comment by dmvtech** [comment]
Hi @chia-lun Apologies for the delay. I am still investigating this.

**Comment by chia-lun** [comment]
No worries! Thank you for taking time to investigate.

**Comment by dmvtech** [comment]
Hi @chia-lun 

> Will the user input get extracted first and then validated?

That is correct. But you should use `turn.extracted.text` instead of `user.email`.


Regarding the two LUIS traces, do you have interruptions enabled on the prompt for text or dialog?

**Comment by dmvtech** [comment]
Hi @chia-lun 

Do you still need assistance on this issue?

**Comment by dmvtech** [comment]
Closing due to lack of reply. If you still need assistance on this, please comment with the pertinent information and we can reopen to continue.
