### ISSUE TITLE
There was a problem publishing bot assets (zip deploy)

### ISSUE THREAD

**Issue by iamkhan001** [microsoft/BotFramework-Composer#9311]
Hi there,

I'm trying to deploye my bot on azure but I'm getting this error every time i try to upload.

Please help on this

```"{\"name\":\"DEPLOY_ZIP_ERROR\",\"message\":\"There was a problem publishing bot assets (zip deploy). \\\"Getting status of zip upload processing failed. {\\\\\\\"stack\\\\\\\":\\\\\\\"Error: Request failed with status code 403\\\\\\\\n at createError (C:\\\\\\\\\\\\\\\\Program Files\\\\\\\\\\\\\\\\Bot Framework Composer\\\\\\\\\\\\\\\\resources\\\\\\\\\\\\\\\\app.asar.unpacked\\\\\\\\\\\\\\\\extensions\\\\\\\\\\\\\\\\azurePublish\\\\\\\\\\\\\\\\dist\\\\\\\\\\\\\\\\extension.js:105969:17)\\\\\\\\n at settle (C:\\\\\\\\\\\\\\\\Program Files\\\\\\\\\\\\\\\\Bot Framework Composer\\\\\\\\\\\\\\\\resources\\\\\\\\\\\\\\\\app.asar.unpacked\\\\\\\\\\\\\\\\extensions\\\\\\\\\\\\\\\\azurePublish\\\\\\\\\\\\\\\\dist\\\\\\\\\\\\\\\\extension.js:105983:14)\\\\\\\\n at IncomingMessage.handleStreamEnd (C:\\\\\\\\\\\\\\\\Program Files\\\\\\\\\\\\\\\\Bot Framework Composer\\\\\\\\\\\\\\\\resources\\\\\\\\\\\\\\\\app.asar.unpacked\\\\\\\\\\\\\\\\extensions\\\\\\\\\\\\\\\\azurePublish\\\\\\\\\\\\\\\\dist\\\\\\\\\\\\\\\\extension.js:106970:13)\\\\\\\\n at IncomingMessage.emit (events.js:215:7)\\\\\\\\n at endReadableNT (_stream_readable.js:1183:12)\\\\\\\\n at processTicksAndRejections (internal/process/task_queues.js:80:21)\\\\\\\",\\\\\\\"message\\\\\\\":\\\\\\\"Request failed with status code 403\\\\\\\",\\\\\\\"config\\\\\\\":{}}\\\"\",\"stack\":\"Error\\n at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276418:25)\\n at createCustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276423:10)\\n at BotProjectDeploy.deployZip (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276954:13)\"}"------"DEPLOY_ZIP_ERROR - There was a problem publishing bot assets (zip deploy). \"Getting status of zip upload processing failed. {\\\"stack\\\":\\\"Error: Request failed with status code 403\\\\n at createError (C:\\\\\\\\Program Files\\\\\\\\Bot Framework Composer\\\\\\\\resources\\\\\\\\app.asar.unpacked\\\\\\\\extensions\\\\\\\\azurePublish\\\\\\\\dist\\\\\\\\extension.js:105969:17)\\\\n at settle (C:\\\\\\\\Program Files\\\\\\\\Bot Framework Composer\\\\\\\\resources\\\\\\\\app.asar.unpacked\\\\\\\\extensions\\\\\\\\azurePublish\\\\\\\\dist\\\\\\\\extension.js:105983:14)\\\\n at IncomingMessage.handleStreamEnd (C:\\\\\\\\Program Files\\\\\\\\Bot Framework Composer\\\\\\\\resources\\\\\\\\app.asar.unpacked\\\\\\\\extensions\\\\\\\\azurePublish\\\\\\\\dist\\\\\\\\extension.js:106970:13)\\\\n at IncomingMessage.emit (events.js:215:7)\\\\n at endReadableNT (_stream_readable.js:1183:12)\\\\n at processTicksAndRejections (internal/process/task_queues.js:80:21)\\\",\\\"message\\\":\\\"Request failed with status code 403\\\",\\\"config\\\":{}}\""---```

**Comment by dmvtech** [comment]
Closing due to lack of response.
