### ISSUE TITLE
Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. 

### ISSUE THREAD

**Issue by ADongol** [microsoft/BotFramework-Composer#9317]
## Describe the bug

I have the npm installed, but when I do create composer this error is being spit out all the time.

Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. 

Full error message: Command failed with exit code 1: npm install -g --prefix C:\Users\adongol\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error --no-optional @microsoft/generator-bot-empty@*

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
@ADongol To clarify; this is when you are attempting to create a new bot? (if so; C# or node?). Or are you getting this error when attempting to install Composer itself?

**Comment by dmvtech** [comment]
Closing due to lack of response.
