### ISSUE TITLE
Clarify trigger name usage

### ISSUE THREAD

**Issue by boydc2014** [microsoft/BotFramework-Composer#932]
In our trigger wizzard design, we require a "name" for each trigger type. 

The issue is:
1. If this is not a "intent trigger", it's highly likely no trigger with same type (because same type trigger with only fire the first one), so that trigger type can be used to identify this trigger, and it's very clearly to use trigger type instead of an arbitrary name. 

2. If this is a "intent trigger",  i'm not sure how we handle the confusion between trigger name with "intent name"

My feeling is if trigger name can't be added in a consistent way, it's more confusing than being helpful.  

My proposal is we remove trigger name from new trigger wizzard.  On the left nav, we can show intent name of intent trigger, and trigger type for other type of trigger.

**Comment by sangwoohaan** [comment]
Closing this since the name fields are removed from the trigger wizards for now, but we should circle back to this issue in the future once Managed LU is in place.
