### ISSUE TITLE
Declare @ ml <entityname> or is it not needed anymore?

### ISSUE THREAD

**Issue by adrwh** [microsoft/BotFramework-Composer#9326]
I have done some tests creating custom entities using `@ ml <entityname>` and not using it.  Both work, so is it better to declare the `@ ml <entityname>` or is it not needed?

I have two triggers setup, NameA and NameB.  As you see below, I have declared the `@ ml nameB` statement for trigger NameB but not for trigger NameA.

User Input/Utterances
```
# NameA
- triggerA {nameA1 = andrew}
- triggerA {@ nameA2 = andrew}
- triggerA {@nameA3 = andrew}

# NameB
- triggerB {nameB1 = andrew}
- triggerB {@ nameB2 = andrew}
- triggerB {@nameB3 = andrew}

@ ml nameB
```

I have added the `Send a response` action and sent the values stored in the `@nameA[1,2,3]` and `@nameB[1,2,3]` entities.  Upon running the bot, and triggering both intents, the `@nameA[1,2,3]` and `@nameB[1,2,3]` are both stored correctly.

<img width="762" alt="Screen Shot 2022-08-02 at 5 31 30 PM" src="https://user-images.githubusercontent.com/11284765/182477625-13d74f59-7dae-4a2b-bee8-2fc711c71cf6.png">

<img width="772" alt="Screen Shot 2022-08-02 at 5 31 38 PM" src="https://user-images.githubusercontent.com/11284765/182477647-061bc6c6-e678-4d91-aec3-d546186c5ef0.png">

Is adding the `@ ml <entityname>` no longer relevant?

**Comment by dmvtech** [comment]
hi @adrwh 

If it's going to be very simple/basic as you have it above, then no. You don't need it.

If you are going to be using stuff like roles/features, then yes.
https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lu-file-format?view=azure-bot-service-4.0#entity-definitions

**Comment by dmvtech** [comment]
Closing as answered.
