### ISSUE TITLE
Bot Composer crashes when using Throw Exception activity

### ISSUE THREAD

**Issue by ZepHakase22** [microsoft/BotFramework-Composer#9327]
## Description

Within a trigger choose Debugging Options -> Throw Exception.
Try to assign a constant object to the Error Value.
Bot Composer freezes.
If the object is previously assigned to a property and then that property is assigned to the Error Value it works perfectly.

## Version

Version:  2.1.2-nightly.314453.6e43cf5
Electron: 14.2.6
Chrome: 93.0.4577.82
NodeJS: 14.17.0
V8: 9.3.345.20-electron.0

## Browser

- [X] Chrome
- [X] Edge

## OS

- [X] Windows

**Comment by dmvtech** [comment]
I can reproduce this as well.

**Comment by tdurnford** [comment]
@ceciliaavila Can you provide up on this?

**Comment by ceciliaavila** [comment]
> @ceciliaavila Can you provide up on this?

Hi @tdurnford, this issue is on our backlog. We'll be tackling it this week.
Thanks.

**Comment by johnataylor** [comment]
@ZepHakase22 we have a fix in the works for this, thanks.

**Comment by ceciliaavila** [comment]
Fix available in linked PR (pending merge).
