### ISSUE TITLE
Substring function contains wrong tooltip information

### ISSUE THREAD

**Issue by johnkm516** [microsoft/BotFramework-Composer#9331]
## Describe the bug

On bot framework composer, hovering over the substring function shows an outdated tooltip : 

![image](https://user-images.githubusercontent.com/10858008/182777743-8b3a06d9-cd79-4e48-9649-b01577011543.png)

The substring function in fact has the following parameters : substring(string, startPos, **length**).
`endPos` is incorrect. 
Also, a length from the startPos that surpasses the length of the string will generate an out of range exception, not be taken as the max length of the string. 

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by LeeParrishMSFT** [comment]
Thanks for the feedback, we will queue this to be corrected in a future release.
