### ISSUE TITLE
Unable to create new BOT

### ISSUE THREAD

**Issue by mys2kor** [microsoft/BotFramework-Composer#9333]
## Unable to create new BOT
I get the error `Command failed: dotnet build Empty.csproj` (here 'Empty' is the name of the bot)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

I am working behind a firewall. I have Px (https://github.com/genotrance/px) as the Proxy
I think this is probably only difference between a regular set-up and mine
I have followed all the instructions as give in the BCF documentation

## Expected behavior

A new bot project should be created

## Screenshots

![grafik](https://user-images.githubusercontent.com/109787441/183073858-e16f28b9-d894-49ba-81e2-5669ae3e7dd3.png)

## Additional context

I have had a lot of issues since the wanted to use BFC.
I reported the original issue I faced here https://github.com/microsoft/BotFramework-Composer/issues/9328
I resolved this issue be doing the following 
a.	When installing BFC (2.1.1 or 2.1.2), we need Px to be running, else it will not install.
b.	However, during the launch of BFC, Px SHOULD NOT be running!!! Else we get the error I shared with you.
c.	When logging into BFC (we have to login every time we launch the application!), we again need Px to be running else we get ‘No Azure Directories Found” error.

Also, When I close the program the window to install is popping up ! Not sure why but it does !!!

These issues may be linked, hence I mentioned this. I have wasted 3 complete days trying to get BFC working. 
I am being asked to look for other alternatives for creating a Bot since I am not able to get BFC working. Please help.

**Comment by tracyboehrer** [comment]
This is corrected with the 1.4.1 Empty Bot template published about 30 minutes ago.

**Comment by mys2kor** [comment]
In the tool still 1.4.0 is showing.
![grafik](https://user-images.githubusercontent.com/109787441/183106734-a72cd8b9-a5cc-4fbc-839c-229bc2532747.png)

**Comment by tracyboehrer** [comment]
Try restarting Composer.  I'm not exactly sure when that is refreshed.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/1024902/183107183-b6bb0454-8a98-4e11-915a-bb2b880b9f32.png">

**Comment by mys2kor** [comment]
I restarted & below is what I see (version number is missing)

![grafik](https://user-images.githubusercontent.com/109787441/183107482-ec149f82-b84f-4fda-bfef-16caf6591a59.png)
