### ISSUE TITLE
Build Error When Creating Empty Bot

### ISSUE THREAD

**Issue by hamin123** [microsoft/BotFramework-Composer#9334]
## Describe the bug
When creating a new bot project with empty bot template on Windows 11 with Bot Framework Composer, I get the following error 👎 Command failed: dotnet build Empty.csproj

dotnet build issue with empty template

## Version
Version : 2.1.2

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [Y ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS
Windows 11

- [ ] macOS
- [Yes ] Windows
- [ ] Ubuntu

**Comment by tracyboehrer** [comment]
This should be corrected with the latest publish of the 1.4.1 Empy Bot template.  This happened about 30 minutes ago.
