### ISSUE TITLE
Branch: Switch (multiple options) : default option is not executing 

### ISSUE THREAD

**Issue by kishan2** [microsoft/BotFramework-Composer#9350]
I am using switch condition in bot framework composer and asking to customer "If you wish to leave a message in order to be called back, please press 1, otherwise please hold the line. Thank you.".

below is my logic in bot framework composer.

![image](https://user-images.githubusercontent.com/22518920/184847826-adb5ad6a-af84-4b4d-9651-c01b1f9b4819.png)

When customer is pressing 1 then it is working but when customer is not pressing any key then it should  go in to  default condition and execute logic but this is  not working as expected. 

Kindly provide any suggestion I have to achieve below logic.

"If you wish to leave a message in order to be called back, please press 1, otherwise please hold the line. Thank you"

if customer not pressed any key then it should execute default condition or please let me know how I can identified that customer has not pressed any key.

**Comment by stevkan** [comment]
@kishan2 - Thank you for your patience. Can you tell me what type of property `conversation.customerdecision` is when it is storing the customer's decision (or lack of)? Is it a boolean, string, or number?

Also, is a default value being assigned to `conversation.customerdecision` at any point?

Can you post your bot's logic that handles the above?

**Comment by kishan2** [comment]
@stevkan 

whole logic are below.

![image](https://user-images.githubusercontent.com/22518920/185275490-45e7df85-eced-4a56-9f8a-78aca5e380e2.png)
![image](https://user-images.githubusercontent.com/22518920/185275511-8136ad01-b95e-4ba5-8c0c-7721fae73435.png)
  

below are my answer 

when it is storing the customer's decision (or lack of)? Is it a Boolean, string, or number?  - ****_**I am not sure where to declare this, can you please provide any link or docs where I can see how to declare user input as Boolean, string or number?****_**


Also, is a default value being assigned to conversation.customerdecision at any point?  **_No @stevkan  I am not sure how to set this as default value in bot framework composer._**


**my requirement is when user has not pressed anything then it should in to default condition.**
Please advise.

**Comment by stevkan** [comment]
@kishan2 - Thank you for your patience. From what I gather from your post, you are trying to detect when a set amount of time has passed without the user responding to a prompt.

> if customer not pressed any key then it should execute default condition or please let me know how I can identified that customer has not pressed any key.

I have researched this and, unfortunately, given the available tools this is not possible. As it is, there is no way to interrupt a prompt to run some other action detecting user input.

That being said, you do have a couple options available to you depending on your circumstances:

1. You could create a [custom action](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions) that would function as a choice prompt, but with a built-in timer option. This would likely take a fair amount of work, but it is an option.
2. If you plan on using Web Chat as the user's client, you could set a timer there that would then provide a default response following the prompt after _x_ amount of time had passed. This is only available for [Web Chat](https://github.com/microsoft/BotFramework-WebChat) and not other clients/channels.
