### ISSUE TITLE
Unable to launch Bot Framework Composer (Struck at "server starting" screen)

### ISSUE THREAD

**Issue by nisarkhan916** [microsoft/BotFramework-Composer#9352]
- Already installed desktop version of composer(c#) was working completely fine.
- When we launch composer from PVA console  --> Logged in successfully with the Microsoft AD Account on consent --> After these steps also the composer was launched successfully.
- Here when we restart the system --> Tried to launch the composer directly or from PVA Console --> Getting struck at "**server starting**" screen.

Attaching the screenshot for reference...
![image](https://user-images.githubusercontent.com/64094893/185057421-ca7671d6-4dc9-49df-a2b6-01b90a2ff54b.png)

- In the below screenshot you can check the error shown while logging In from PVA.
![image](https://user-images.githubusercontent.com/64094893/185057484-4d15bfab-4ab1-4a9a-b2be-9aa3fab89da3.png)

Thanks in advance...

**Comment by dmvtech** [comment]
Hi @nisarkhan916 

> Here when we restart the system --> Tried to launch the composer directly or from PVA Console --> Getting struck at "server starting" screen.

To clarify; when you are attempting to re-launch a bot from Composer on its own, or Composer from PVA, you get a Server Starting screen, and _then_ you get the **Something Went Wrong** error? But when you first launch Composer from PVA, login, etc; it works fine that time.

**Comment by nisarkhan916** [comment]
Hey @dmvtech,

The composer via PVA was launched and then it asked for my creds, then on creds submission i got  **something went wrong error** but still it was logged in and the composer was working fine.

After a system restart i am unable to launch composer at all

**Comment by dmvtech** [comment]
Thank you @nisarkhan916 

Can you please (attempt to) run Composer in debug mode. I want to see what the debug output looks like when it fails.

- Go to Composer's install location (mine is at C:\Users{username}\AppData\Local\Programs\Bot Framework Composer)
- Open a terminal here
- run `set DEBUG=composer*`
- run the executable from the terminal Ex. "Bot Framework Composer.exe"

Once it fails, copy the output from the terminal and paste it here.

**Comment by nisarkhan916** [comment]
Hey @dmvtech,

Here is the output from the terminal 

`(node:28376) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (node:28376) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (node:28376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:28376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by dmvtech** [comment]
Can you ensure you have the (newest) C++ redistributable installed? Please see more information here: https://stackoverflow.com/questions/72447436/bot-framework-composer-stuck-on-starting-server

**Comment by dmvtech** [comment]
Closing due to lack of response. Please comment and confirm whether the redistributable resolved the issue and we will reopen.
