### ISSUE TITLE
Set Human Handoff event context from Composer

### ISSUE THREAD

**Issue by dinobrago** [microsoft/BotFramework-Composer#9357]
## Describe the bug
This could be a documentation issue. 

In the Human Handoff event, there is a context that allows you to send information to another package.

Paraphrased from the [documentation ](https://docs.microsoft.com/en-us/composer/concept-agent-handoff)

When using the Send a handoff activity action, to trigger handoff, you can optionally provide a JSON object within the Context property input box in the right hand pane. 

When I attempt to pass dynamic information to the context, it is interpreted as a literal string rather than the value a local user variable. 

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
## Browser

- [ ] Electron distribution
- [ X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X ] Windows
- [ ] Ubuntu

## To Reproduce

Set the context of the Human Handoff event to something equivalent to the following:

```
{
  "Name": "${user.name}",
  "Issue": "${user.issue}"
}
```

The string passed to the app is "${user.name}"

## Expected behavior

Expected the value of user.name to be passed. 

## Screenshots

![image](https://user-images.githubusercontent.com/41213271/185683726-9102ffea-a3ee-44ee-9f32-69722dea1490.png)

![image](https://user-images.githubusercontent.com/41213271/185684061-329396d9-9b83-4e1a-a999-cd289910b97e.png)

**Comment by dmvtech** [comment]
Thank you @dinobrago 

I am investigating further.

**Comment by dmvtech** [comment]
I am able to reproduce. I can also confirm that setting the context via an expression (like `=conversation.dynamicvalues`) does not work. It does work **in that** it will set the value to be the dynamic value, but still doesn't implement the replacement/string interpolation:

```
    "value": {
      "Name": "$conversation.dynamicname",
      "Issue": "$conversation.dynamicissue"
    },
```

**Comment by ceciliaavila** [comment]
@munozemilio Closing as it was corrected by linked PR. Will require SDK release.
