### ISSUE TITLE
DEPLOY_ZIP_ERROR with status code 403 after one hour delay deploying Core Bot with Language starter template to Linux App Service

### ISSUE THREAD

**Issue by IntegerMan** [microsoft/BotFramework-Composer#9360]
## Describe the bug

Bot Framework Composer v2.1.2 has consistently encountered failures from Azure trying to publish new bots targeting Linux plans. This can be replicated in Bot Framework Composer v2.1.2 by creating a new bot using C# and the "Core Bot with Language" template, then going to create a new publish preset, publishing as a web app on Linux in US West with LUIS on US West.

After choosing to create new resources and a new resource group using only the minimally required components, the profile is created and the resources are created on Azure. However, actually publishing causes 45-90 minutes of wait time after the zip uploads, followed by a JSON-based failure message indicating 403 status code (presumably unauthenticated).

Publishing bots to Windows app service plans work following the exact same workflow, but costs significantly more.

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new bot using C# and the "Core Bot with Language" template in Bot Framework Composer specifying Azure Web App as the runtime type
2. Click on Publish on the sidebar
3. Click on Publishing profile on the tab strip
4. Click on add new
5. Name it "ThisWillFail" or whatever
6. Select publishing target of Publish Bot to Azure
7. Specify Create new resources and click Next
8. Login as needed
9. Select your subscription
10. Choose to create a new resource group and name it something distinct, e.g. this-will-fail
11. Specify Linux as the operating system
12. Specify ThisWillFail or similar as the resource name
13. Specify West US as the region. This will also set LUIS region to West US
14. Click Next
15. Uncheck all optional resources
16. Click Next
17. Click Create
18. Wait for the resources to be provisioned and the profile to appear
19. Note: you can also set up Language Understanding for the bot in the sidebar at this point, it doesn't matter if you do or don't
20. Click on the Publish tab
21. Check your bot and specify the publish target
22. Click Publish Selected Bots
23. Click OK
24. Observe long wait time after upload of Zip file in the "waiting for zip upload processing" step. This takes ~45 minutes or so.
25. Observe DEPLOY_ZIP_ERROR failure message with 403 status code.

Note that these steps do not reproduce the error when targeting Windows.

## Expected behavior

Working app deployed to Azure on a Linux app service and ready to be interacted with.

## Screenshots

Uploading Process:

![image](https://user-images.githubusercontent.com/5049957/187055004-165fd3e0-62cf-4526-b6ce-abef9810035d.png)

Failure Message (after significant delay):
![image](https://user-images.githubusercontent.com/5049957/187056221-2923abc4-2ad0-44a4-8645-fc96948d3e03.png)

## Additional context

I am an individual running chatbots for fun and to teach others about Azure. I want the cheapest available "always on" resource to embed in my low traffic personal website and blog and Windows would run me $50 / month ($600 yearly) whereas Linux would be roughly $150 yearly,

**Comment by dmvtech** [comment]
This is a known issue. Please see more information here: https://github.com/microsoft/BotFramework-Composer/issues/8890

**Comment by axelsrz** [comment]
Closing due to duplication
