### ISSUE TITLE
New Language Services support in Bot Framework Composer (custom question answering + conversational language understanding)

### ISSUE THREAD

**Issue by pablodiloreto** [microsoft/BotFramework-Composer#9362]
When I want to use "Azure Cognitive Services for Language" services (exactly "Custom Question Answering + Conversational Language Understanding") in Bot Framework Composer, I can not. In a few weeks QnA Maker will no longer accept to create any new resource.

### Discussed in https://github.com/microsoft/BotFramework-Composer/discussions/9361

<div type='discussions-op-text'>

<sup>Originally posted by **pablodiloreto** August 28, 2022</sup>
In a few weeks (Octuber 1st, 2022), QnA Maker will no longer support new QnA Maker resources. We will have to use the new services of "[Azure Cognitive Services for Language](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/overview)". This new services are not yet supported by Bot Framework Composer, and there is no news or estimated dates for this support to be guaranteed. Could I get information about the future of Bot Framework Composer and the support for these new Azure services? There are many clients who have chosen to use this no-code IDE and a few weeks before the end of the QnA Maker cycle (new resources), there is no clear information.

In other discussions ([here](https://github.com/microsoft/BotFramework-Composer/issues/9190) and [here](https://github.com/microsoft/BotFramework-Composer/issues/8896)), there is no clear answer on this topic.

#8896 #9190 </div>

**Comment by pablodiloreto** [comment]
Thank you for your answer on this topic @cwhitten . Considering my experience and feedback with clients, I believe that being able to create cognitive FAQs and intent recognition using capabilities using no-code and native Azure services is one of the main values in Bot Framework Composer. I understand that from October 1st, we will not be able to do it from the tool. Hopefully the roadmap can be revised to integrate them again.

**Comment by tom-lokulus** [comment]
@axelsrz - Could you provide an update on where this issue is going? Microsoft appears to be ignoring #9058 which is asking the same question and now this has been closed without comment? It feels like we are getting very close to losing the ability to incorporate knowledge bases into Bots built with  Composer and we don't know what Microsoft's intentions are.

**Comment by mukdenchild** [comment]
If qnamaker no longer accepts new input and Bot Composer doesn't support the replacing Custom Question Answering, the entire product of Bot Composer is near useless, and months of time we spent on the learning curves for Bot Composer goes meaningless. This is a very good example how MS replaces products so often without proper plans. I am still waiting on a solution.

**Comment by stephanbisser** [comment]
@cwhitten please share some more infos on this. What will happen to Composer if QnA Maker is not letting us creating new resources? Can Composer then still use the QnA feature backed into it? This is extremely for a lot of customers who have adopted Composer and who cannot are do not want to go the PVA path

**Comment by Prerana-acce** [comment]
Any update on this? I echo with @stephanbisser , we have client projects running for 2+ years on Bot Composer. In my opinion is not a feature , its something that should be considered as part of Language Studio roll off . It puts all the projects working in production on Composer in pickle! @cwhitten  please let us know if any update on this issue or if you have work around for the same. The QnA Maker portal doesn't work anymore with KB size 20K plus, we disparately want to move to Language Studio . Any tips & response would be highly appreciated.

**Comment by ScrewdriverHyena** [comment]
Please reconsider this approach, as PVA doesn't provide the flexibility that Composer does. I'd much rather not have to recreate a large bot project on a non-microsoft platform. QnA is an essential part of Bot Composer and should work moving forward.

**Comment by cwhitten** [comment]
Hi everyone,

As a quick update to not feel "in the dark", we've been discussing this internally for some time now and are putting a plan together to share with the community. Thank you for your feedback. Please stay tuned.

**Comment by Prerana-acce** [comment]
Thanks for the update. Meanwhile anyone looking for a workaround , we replaced the QnAMakerDialog by making actual Rest API calls to the Language Studio Custom Question Answering. Its working fine. 

Happy Coding!

**Comment by pablodiloreto** [comment]
Great news @cwhitten ! Thank you for taking the feedback. We are waiting for the news!

Thank you @Prerana-acce  also for sharing your experience. I was exploring a similar path :-).

**Comment by fausttiger** [comment]
> Thanks for the update. Meanwhile anyone looking for a workaround , we replaced the QnAMakerDialog by making actual Rest API calls to the Language Studio Custom Question Answering. Its working fine.
> 
> Happy Coding!

In Composer 2.1.2, I still see only 'Language Understanding' and "QnA Maker' in configuration... how are you adding/caling   Custom Question Answering (or other Language Studio options)?

Tony

**Comment by cwhitten** [comment]
Hi everyone - please see the following github post for guidance and updates on this issue. Thanks

https://github.com/microsoft/BotFramework-Composer/issues/9400
