### ISSUE TITLE
Default option is not executing in Branch: Switch (multiple options)

### ISSUE THREAD

**Issue by shrungarevidya** [microsoft/BotFramework-Composer#9365]
When customer is typing different than this below two option then default condition is not executing. After typing text 4 times at the 4th time my default condition is executing.(For Commercial Support and Technical Product-related Support (e.g. cutting data or tool recommendations) its working proper).

Kindly check this.  

![image](https://user-images.githubusercontent.com/50614932/187390754-efed785d-4329-48e8-b736-e7f26d201932.png)

**Comment by ramfattah** [comment]
Hi @shrungarevidya, I'm investigating this issue.

**Comment by ramfattah** [comment]
Hi @shrungarevidya, 

I was not able to reproduce this issue.

The default condition is executing in the switch statement.

https://user-images.githubusercontent.com/38049078/188503384-e8b7e023-405e-40e8-b534-8dee7e57b5bf.mp4



Switch statement setup:
![image](https://user-images.githubusercontent.com/38049078/188503571-f11dd795-4818-493f-b2af-7537998789e4.png)


#

> After typing text 4 times at the 4th time my default condition is executing.


Could you please verify if the `Max turn count` is set to 1?  
![maxTurnCount](https://user-images.githubusercontent.com/38049078/188503808-5da56749-a5d8-4025-8924-eac4f66a1a51.png)

**Comment by shrungarevidya** [comment]
Thank you for your solution it worked for me.
