### ISSUE TITLE
[IcM] Unable to publish the Luis enabled bot using composer failing with "Error - Luis build failed: Cannot read property 'error' of undefined"

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-Composer#9374]
> This is a bug from IcM ticket 333282736.
> When this bug is triaged, please assign the IcM ticket to the bug owner.
> When this bug is resolved, please resolve the IcM ticket.
> For customer communication, please refer to the IcM ticket.

## Describe the bug

Unable to publish the Luis enabled bot using composer failing with "Error - Luis build failed: Cannot read property 'error' of undefined" 

```
{
  "stack": "Error: Luis build failed: Cannot read property 'error' of undefined\n    at Builder.<anonymous> (C:\\Users\\PA20230966\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar\\\node_modules\\@bfc\\server\\build\\models\\bot\\builder.js:88:27)\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\PA20230966\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar\\\node_modules\\@bfc\\server\\\node_modules\\tslib\\tslib.js:112:69)",
  "message": "Luis build failed: Cannot read property 'error' of undefined"
}
---
---
"Error - Luis build failed: Cannot read property 'error' of undefined"
```

Formatted the error stack for clarity:

```
Error: Luis build failed: Cannot read property 'error' of undefined
    at Builder.<anonymous> (C:\Users\PA20230966\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\@bfc\server\build\models\bot\builder.js:88:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\PA20230966\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\@bfc\server\node_modules\tslib\tslib.js:112:69)
```

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Screenshots

Able to publish the normal echo bot issue only observed with Luis bot.

intermittently getting below message when open bot. 

![image](https://user-images.githubusercontent.com/1622400/189409018-8118984b-c303-455e-88bf-46f17e9cac53.png)

![image](https://user-images.githubusercontent.com/1622400/189409027-4dc05327-2189-4ad4-8b5e-8557221a59aa.png)

**Comment by BruceHaley** [comment]
Eric points out that #9057 of March 17 is likely about the same error: Error: "TypeError - Cannot read property 'findIndex' of undefined".

**Comment by BruceHaley** [comment]
The IcM lacks any repro information. I tried a couple of scenarios and got an error, but not the error reported in the IcM:

I created a bot using the Node template Core Bot With Language. Using a publishing profile that targeted a Windows App Service, the bot deployed successfully. Using a publishing profile that targeted a Linux App Service, the bot deployment never completed.

**Comment by anishprasad01** [comment]
As per customer, the issue was a long file path with spaces. a shorter path with no spaces resulted in successful publishing.
