### ISSUE TITLE
Error trying to add QnA Spanish Knlwledge Base

### ISSUE THREAD

**Issue by jpd21122012** [microsoft/BotFramework-Composer#9375]
## Describe the bug
When creating a QnABot and trying to add an Existing Knowledge Base made in Spanish Language it doesn't appear the checkbox to add into the bot.

## Version
2.1.2

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Home
2. Click on Create new
3. Into C# tab click on "Core Bot with QnA Maker"
4. Click on Next
5. Modify the bot name if you want and then click on Next
6. Type the name for the knowledge base and click on Next
7. Select "Import existing knowledge base from QnA maker portal"
8. Click on Next
9. Select your Azure subscription
10. Select QnA existing resource
12. Here you cannot select the knlowledge base made on Spanish Language

## Expected behavior

Be able to select Spanish Knowledge Base
## Screenshots
![image](https://user-images.githubusercontent.com/25286017/189417457-0a70c7c7-4dec-4753-bd80-c449921822c8.png)

**Comment by dmvtech** [comment]
Hi @jpd21122012 

Is the bot [created/configured to use both English and Spanish](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language?tabs=v2x)? Or if the bot is only configured to use one language, is it English or Spanish?

**Comment by jpd21122012** [comment]
Hello @dmvtech when creating bot for first time it doesn't prompt for Bot Language/Localization, by default is on (English United States), but then I've created a new bot skipping QnA credentials, changed the Language to Spanish and adding the QnA Key and a new Knowledge Base linked to QnA existing KB, and it worked, but it's a little but trickier to achieve this function working with other languages

**Comment by dmvtech** [comment]
Thank you @jpd21122012 

I'm still working on reproducing the behavior and investigating. Thank you for your patience.

**Comment by dmvtech** [comment]
Hi @jpd21122012 

After further investigation, we can confirm that this is expected. It's understandable that it's not the ideal behavior, but it is required to have the (same/correct) locale available for Composer to be able to add the needed language KB so that it can create the appropriate dialogs, etc.

Thank you for bringing this behavior to our attention.
