### ISSUE TITLE
if condition always return false

### ISSUE THREAD

**Issue by RaziaSulthanaB** [microsoft/BotFramework-Composer#9376]
Trying to compare two string expressions .It always returns false eventhough values are equal

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## Additional context
![image](https://user-images.githubusercontent.com/89798970/189428653-900b5596-caa1-423c-b747-bcafdb99fc13.png)

**Comment by RaziaSulthanaB** [comment]
![image](https://user-images.githubusercontent.com/89798970/189431110-7a1eba9b-6432-4a5f-8ef4-6b7c264854b7.png)

**Comment by anishprasad01** [comment]
Hi @RaziaSulthanaB,

Have you tried printing out those string values to see what they actually are? The spacing, letter case, or other details may not actually be the same. `=equals(arg1, arg2)` should work for strings.

**Comment by RaziaSulthanaB** [comment]
Trim helped fixing the issue .String has spaces at the end
