### ISSUE TITLE
Error calling npm to fetch template

### ISSUE THREAD

**Issue by k5reeves** [microsoft/BotFramework-Composer#9379]
While creating a new bot and downloading template, I receive the following error:

Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm install -g --prefix C:\Users\kreeves4\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error --no-optional @microsoft/generator-bot-core-language@*

Version 2.1.2
Browser: Microsoft Edge

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

Windows 10

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

![Capture](https://user-images.githubusercontent.com/17990339/190007639-a643cdc5-a9c2-4fae-b515-eebeb7c9384e.PNG)

Expected behavior

I expected a new empty bot to be developed to allow customization.

Screenshots

 Additional context

Node.js v16.14.2
npm@8.14.0

**Comment by dmvtech** [comment]
Hi @k5reeves 

Can you please test by creating a folder on your desktop and naming it 'testtemplate' and the running the following from the terminal:
`npm install -g --prefix C:\Users\kreeves4\Desktop\testtemplate --loglevel error --no-optional @microsoft/generator-bot-core-language@*`

Let me know if that succeeds or what the error is if it fails.

**Comment by dmvtech** [comment]
@k5reeves 

That seems to be a certificate/networking/firewall issue. Please see more information here, might be a good place to start:
https://stackoverflow.com/questions/44428566/npm-error-unable-to-get-issuer-cert-locally-how-to-generate-a-pem-file-from-a#:~:text=npm%20ERR%21%20code%20UNABLE_TO_GET_ISSUER_CERT_LOCALLY%20This%20error%20means%20that,is%20the%20certificate%20used%20by%20one%27s%20HTTPS%20proxy.

**Comment by rahulmakwana92** [comment]
> Hi @k5reeves
> 
> Can you please test by creating a folder on your desktop and naming it 'testtemplate' and the running the following from the terminal: `npm install -g --prefix C:\Users\kreeves4\Desktop\testtemplate --loglevel error --no-optional @microsoft/generator-bot-core-language@*`
> 
> Let me know if that succeeds or what the error is if it fails.

I was getting the same error and issue. I tried the above command and it succeeded.
![image](https://github.com/microsoft/BotFramework-Composer/assets/47862637/2ea748f1-990c-484b-96d6-2607acc31eed)
What to do next ? I still get this error : 
![image](https://github.com/microsoft/BotFramework-Composer/assets/47862637/1c54f96f-a7f6-406f-b0f4-217134028527)
