### ISSUE TITLE
Bot Composer - store transcripts in different container

### ISSUE THREAD

**Issue by nickfrancis** [microsoft/BotFramework-Composer#9381]
I have been working on storing transcripts in Blob Storage.

I am also using Blob Storage to hold documentation that the Bot retrieves.

Is it possible to reference two different containers in my settings & start up script so that I can store transcripts in a different container to where my documentation is stored?

Currently my code looks like this:

In my runtime settings:
"blobTranscript": {
        "connectionString": "xxxxxxxx",
        "containerName": "documentation"

In my publishing config file:

    "blobStorage": {
      "connectionString": "xxxxxxx",
      "container": "documentation",
      "name": "xxxxxxxx"
    },

could I change the runtime settings containerName to "transcripts" & add a second Blob Storage to my config file pointing to that container?

**Comment by ramfattah** [comment]
Hi @nickfrancis, we are investigating.

**Comment by ramfattah** [comment]
Hey @nickfrancis  thank you for engaging with the Composer project. We'll take this issue as a feature request and add it to the backlog. We do not have an ETA at this time for when this feature will be available.
