### ISSUE TITLE
How to block user Input from customer

### ISSUE THREAD

**Issue by shrungarevidya** [microsoft/BotFramework-Composer#9390]
How to prevent ,customer typing . In my scenario I am using multiple option then if customer typing something before that option then its directly routing to default condition. Any solution for this?
![image](https://user-images.githubusercontent.com/50614932/192206643-22f71b37-0963-476f-bbfe-d17080738b0f.png)

![image](https://user-images.githubusercontent.com/50614932/192206731-45fd4132-887e-4ac0-ac90-6ec648bca20a.png)

**Comment by stevkan** [comment]
@shrungarevidya - Disabling/removing the user's ability to access the send box is specific to each client used. The above images suggest you are using Web Chat, but that could just be your testing in Composer.

In the end, if Web Chat is (one of) the client(s) to be used, then yes there is a workaround for this. Any other clients, for example Teams, Facebook, Slack, etc., will require you to look over the respective docs for available options.

That being said, each prompt (i.e. the "Ask a question" actions) has an "Expected responses" section located under User input, as shown below. You can define what type of responses are acceptable here. If the user types in a response that doesn't conform to the presented options, then the user is re-prompted according to the rules you specify in the "Prompt Configurations" section under Other.

![image](https://user-images.githubusercontent.com/18403946/192383404-61509a19-45e1-44a9-9ea7-72c4aed5a8e9.png)

**Comment by shrungarevidya** [comment]
@stevkan , Can you please elaborate more or do you have any docs or reference link for this ?

**Comment by stevkan** [comment]
This section, [Add a Language Model in Composer](https://learn.microsoft.com/en-us/composer/how-to-define-intent-entity?tabs=v2x#add-a-language-model-in-composer), in this [doc](https://learn.microsoft.com/en-us/composer/how-to-define-intent-entity?tabs=v2x) discusses using the Expected responses field. For a full understanding, it is worth reading that entire doc.

To be clear, you don't need to specifically use Language Understanding to use this field. In my test, I created a simple multi-choice prompt that asked for you to pick your favorite color and provide the options Blue, Green, and Red. Then, in the Expected responses section, I added:

```txt
- blue
- green
- red
```

If I typed any other value, then I was re-prompted to select one of the three. You can specify the number of times to re-prompt in the Other section and a default answer to be returned if one is never selected.
