### ISSUE TITLE
QnA Migration to Language Services

### ISSUE THREAD

**Issue by CLNELATU** [microsoft/BotFramework-Composer#9391]
How does Composer support from 1st October for creating new QnA KB's, since the QnA maker is getting deprecated.

**Comment by jpd21122012** [comment]
I have the same question

**Comment by nghivo** [comment]
Hi all,
Please see new update from Microsoft here. 

https://github.com/microsoft/BotFramework-Composer/issues/9400

**Comment by cwhitten** [comment]
Hi everyone - please see the following github post for guidance and updates on this issue. Thanks

https://github.com/microsoft/BotFramework-Composer/issues/9400
