### ISSUE TITLE
Get OAuth access token from Activity.ChannelData in Bot Framework Composer 

### ISSUE THREAD

**Issue by hannadeng** [microsoft/BotFramework-Composer#9410]
I'd like to know if there's a way to get OAuth access token from Activity.ChannelData in Bot Composer, then pass the value to the property turn.token. The final purpose is to skip the OAuth login card. 

 ![image](https://user-images.githubusercontent.com/103932765/198285984-1a4add0c-df88-4425-ba83-bd613ac1aced.png)

The background is we need to implement SSO for an web chat bot embedded in a website. 

Microsoft Bot Framework SDK already provides a node.js sample ([07.advanced-web-chat-apps/c.sso-for-intranet/](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/07.advanced-web-chat-apps/c.sso-for-intranet)) which implements chat bot SSO, that is, if the user signed in to the website, then no need to sign in to the bot again for Graph API calls. The main technique is that on the website page where renders web chat bot, store the oauthAccessToken in webchat channeldata,  'Piggyback' the access token on every outgoing activity, then on the bot side, read the oauthAccessToken from activity.channelData. 

Thus my questions is how to get activity.channelData value in the Bot Composer? Is there any variable binding to the object? 

code on website:
        
         const oauthAccessToken = window.sessionStorage.getItem('OAUTH_ACCESS_TOKEN'); 

        // Piggyback the access token on every outgoing activity.
         const store = WebChat.createStore({}, ({ dispatch }) => {   
            return next => action => {    
              if (action.type === 'DIRECT_LINE/POST_ACTIVITY' && oauthAccessToken) {
                // For convenience, we are using a package called "simpleUpdateIn" to patch activity.
                action = simpleUpdateIn(
                  action,
                  ['payload', 'activity', 'channelData', 'oauthAccessToken'],
                  () => oauthAccessToken
                );
              }
              return next(action);
            };
          });

code on bot side: 
          
        // Handler for "message" activity
          bot.onMessage(async (context, next) => {
    const { activity: { channelData: { oauthAccessToken } = {} } = {} } = context;

    if (oauthAccessToken) {
      // For async operations that are outside of BotBuilder, we should use proactive messaging.
      const reference = TurnContext.getConversationReference(context.activity);

      await context.sendActivity({ type: 'typing' });

      // We are using .then() here to detach the background job.
      fetchMicrosoftGraphProfileName(oauthAccessToken).then(async name => {
        // When the Microsoft Graph profile is fetched, send a welcome message.
        const adapter = createBotAdapter();

        await adapter.continueConversation(reference, async context => {
          await context.sendActivity({
            text: `Welcome back, ${name} (via Azure AD).`
          });
        });

      });
    } else {
      await context.sendActivity(`Please authenticate before continuing.`);
    }

    await next();
        });

Additionally, if there's other way to bypass the OAuth card in Bot Composer with the website SSO, it's also great!

**Comment by stevkan** [comment]
@hannadeng, I'm looking into this and will get back to you shortly with a response.

**Comment by stevkan** [comment]
Closing as this is now being tracked internally via an IcM.

**Comment by nghivo** [comment]
Hi @stevkan 
As @hannadeng has helped to collaborate with you and the PG team for the internal problem, we can close this ticket.
We have a pressing need for a solution to this problem since when the Bot and our website employ SSO with Microsoft OAuth, the end user experience with the sign-in button is poor.

Thanks and regards,
Nghi
