### ISSUE TITLE
Not having slack API scope im:read results in error

### ISSUE THREAD

**Issue by RamkumarManavalan** [microsoft/BotFramework-Composer#9412]
Hello team,

I have used the Bot Framework Composer (details below) to build a bot and have enabled Slack Channel too (after following the steps mentioned in https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0):

Details of the Composer version I use:
Version: 2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

My slack app is currently being reviewed by the slack team who have insisted that I do not need the im:read permission scope because I have the im:history permission scope already. But when I remove the im:read scope from my slack app configuration, messages sent by user in slack to my bot are not processed by the Azure Bot Service because Slack returns an error that im:read scope is needed. Please find attached screenshot and the exception payload (collected from Azure Service logs) below:
 
{
  "StatusCode": 502,
  "Response": {
    "error": {
      "code": "ServiceError",
      "message": "Slack API error",
      "innerHttpError": {
        "statusCode": 200,
        "body": {
          "ok": false,
          "error": "missing_scope",
          "needed": "im:read",
          "provided": "channels:history,channels:read,chat:write,files:read,files:write,groups:history,groups:read,im:history,mpim:history,team:read,users:read,users:read.email"
        }
      }
    }
  },
  "ClassName": "Microsoft.Bot.Schema.APIException",
  "Message": "Slack API error",
  "Source": "SlackChannel",
  …..
}

I went back to the slack review team and showed the error above to confirm that im:read scope is indeed required. However, they responded back saying: "After some investigating, we believe your code may still include the conversations.members method which you don't need to see messages in the DM, which causes the error you helpfully provided for us via email when im:read is removed. Please remove the use of conversations.members if it is not needed. Alternatively, you can keep that in but please update the im:read scope in your submission with the necessary reason."

So, I would like to know the exact reason why conversations.members method (which requires im:read scope) is called from within the bot framework code. I can mention this reason and convince the slack review team. Please help.

**Comment by anishprasad01** [comment]
Hi @RamkumarManavalan,

I took a look at the [Slack Adapter code](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/1d5a98b2781fa3cef0b4a605c1c841e48d6e4891/libraries/Bot.Builder.Community.Adapters.Slack), and I cannot find any instance of the adapter trying to reach the `https://slack.com/api/users.conversations` endpoint by default. Are you able to trace or log what your application is doing to see if and when that endpoint is accessed?

Additionally, [`im:read`](https://api.slack.com/scopes/im:read) is also required for a few other operations. You could check to see if your bot is performing any of these tasks.

**Comment by RamkumarManavalan** [comment]
Thank you @anishprasad01  for your response. I use the bot framework composer and I have written one custom function for base64 encoding of files. In any of these code, I dont call any slack API. Since I am using composer, I am not able to trace/debug the adapter code.

**Comment by anishprasad01** [comment]
Then maybe we need to examine the functions your bot performs. Is there anything your bot does where it might try to get the IDs of the people in a conversation or in a team to message them, or something similar? The adapter essentially just converts Bot Framework activities to Slack and vice versa, so perhaps one of these operations requires `im:read` on the slack side.

There are also three other endpoints that require the `im:read` scope. Did your Slack teams specify why they though it was `conversations.members`?

**Comment by RamkumarManavalan** [comment]
I double-checked and I can confirm that my code does not use any slack method/API directly. So, it should be in the slack adapter code only. 
Slack team have not specified any reason on why they thought it was conversations.members. I can check with them. But the slack team needs the reason why im:read scope is required for the slack adapter.

**Comment by anishprasad01** [comment]
> I double-checked and I can confirm that my code does not use any slack method/API directly.

Your code would not do so directly. The adapter's job is to convert Bot Framework activities into Slack events and Slack events to Bot Framework activities. If your bot ever needs to make use of one of the API methods or events that use the `im:read` scope on the Slack side (as seen [here](https://api.slack.com/scopes/im:read)), then Slack will request the `im:read` scope. 

For example, if you create a Direct Message with a user on the Bot Framework side, the adapter will convert that for Slack to understand and create a DM. However, creating a DM on the Slack side requires the `im:read` scope.

If any functions such as interacting with Direct Messages, listing conversations, checking which conversations a user is part of, or any other functions in the `im:read` scope documentation, then that scope will be required.

The scopes that Slack asks for depend on what functionality your application includes. The adapter's job is just to translate between Bot Framework and Slack.
