### ISSUE TITLE
Request size is too large 

### ISSUE THREAD

**Issue by nghivo** [microsoft/BotFramework-Composer#9414]
Hi Support team,
We use Assistant bot template with People bot and we got below issue, can you help how to solve this issue?

Response status code does not indicate success: RequestEntityTooLarge (413); Substatus: 0; ActivityId: 2c80a4c6-429d-4bab-82ab-b0eed973dc94; Reason: (Message: {“Errors”:[“Request size is too large”]}

ActivityId: 2c80a4c6-429d-4bab-82ab-b0eed973dc94, Request URI: /apps/e77cbcf6-3068-496d-94e2-e75125488806/services/7849df96-c06b-4858-8df2-a960140fd513/partitions/cb27c912-666f-47ca-bed6-afaae88d76e9/replicas/133083093073346336p/, RequestStats: Please see CosmosDiagnostics, SDK: Windows/10.0.14393 cosmos-netstandard-sdk/3.15.2);

Thanks and regards,

**Comment by anishprasad01** [comment]
Hi @nghivo,

[CosmosDB Error 413](https://learn.microsoft.com/en-us/rest/api/cosmos-db/http-status-codes-for-cosmosdb#:~:text=413%20Entity%20too%20large) is thrown when the document size of your request exceeds 2MB. To resolve the issue, you need to check those instances in your bot where you are communicating with CosmosDB and reduce the amount of data in each request to remain within the 2MB limit.
