### ISSUE TITLE
Is botframwork composer suport in PVA Bot new release

### ISSUE THREAD

**Issue by goutham54** [microsoft/BotFramework-Composer#9421]

**Comment by stevkan** [comment]
@goutham54, I see what you mean. The functionality isn't present in the preview of the updated PVA. Let me look into this and I will get back to you.

**Comment by stevkan** [comment]
@goutham54, keeping in mind that the next version of PVA is in public preview and features are subject to change, the ability to open a Composer bot from PVA (preview) is not currently supported. The developers have not finalized the user story on integrating Composer Topics, at this time.

As a reminder, given that the next version of PVA is in public preview, it is strongly recommended that any bot that is in production, or being developed for production, should continue to use the legacy PVA experience until PVA (preview) moves to general availability.
