### ISSUE TITLE
insert the User_Id when we authorized with SSO

### ISSUE THREAD

**Issue by nghivo** [microsoft/BotFramework-Composer#9424]
## Describe the bug
Hi,
I think my question should be linked to the issue https://github.com/microsoft/BotFramework-Composer/issues/9410 when it is resolved. My question is, if SSO done, would the user_id field in the Application Insights be replaced with the actual user log in?

## Version
#9410 

## Browser

- [ ] Electron distribution
- [ x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## Additional context

![2022-11-17 12_42_42-Window](https://user-images.githubusercontent.com/10294750/202375082-967dc1fd-8787-40d4-be0f-aa32629dab0d.png)

**Comment by ramfattah** [comment]
Thanks @nghivo, we are investigating.

**Comment by nghivo** [comment]
Hi @ramfattah ,
How is it going with the investigation?

**Comment by ramfattah** [comment]
Hey @nghivo,

When Authentication is enabled in Composer bot, 
by default, the **user_id** column in Application Insights seems show channel name appended with some id:
Ex: `{ channelName }-{ id }`

![image](https://user-images.githubusercontent.com/38049078/204357531-271c7456-f3f9-4522-aff9-673b55531f28.png)

Investigating further on what is the appended `{ id }` in the user_id field.

**Comment by nghivo** [comment]
Hi @ramfattah ,
We need to see the real user that has been authorized by SSO.
Can we?

**Comment by ramfattah** [comment]
Hi @nghivo,

Tested teams sample [app-sso](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso) with telemetry logging added to the bot.

The `user_Id` field in application insights is channelId + userId:

![image](https://user-images.githubusercontent.com/38049078/204997384-8bc89f02-ff50-45bd-b9e9-10bfcdb3e1ad.png)


[integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs L74-L75](https://github.com/microsoft/botbuilder-dotnet/blob/156639122967f1004a23c322f223a1803d896fc5/libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs#L74-L75)
```c#
  // Set the user id on the Application Insights telemetry item.
    telemetry.Context.User.Id = channelId + userId;
```

[TelemetryBotIdInitializer.cs](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetryBotIdInitializer.cs) class sets the user ID.

**Comment by ramfattah** [comment]
@nghivo, does that help answer your question? 

Please let me know if you have any questions.
Thanks.

**Comment by nghivo** [comment]
Hi @ramfattah ,
Not at all what I'm asking. In my situation, when the **Bot Framework Compose** allowed the signed-in user, I need to record the User Name, for example, Nghi Vo, into the User Id or any custom field in the Application Insight.

**Comment by ramfattah** [comment]
Hi @nghivo, any status update on this?

**Comment by nghivo** [comment]
Hi @ramfattah ,
We added the logPersonalInformation flag into true, but still cannot find the fromName in Application Insights.

Is it due to the middleware has not yet in implemented?

Thanks

**Comment by nghivo** [comment]
Hi @ramfattah ,
Can Microsoft build a package so that we can easy to install directly from Package Manager for this extension?

Thanks and regards,

**Comment by ramfattah** [comment]
Hi @nghivo,

> Is it due to the middleware has not yet in implemented?

I didn't add or implement any middleware, I just turned the `logPersonalInformation` property to true.

**Comment by ramfattah** [comment]
@nghivo, 

I tested this using Teams; perhaps other channels yield different results. 

Investigating further on that. Will report back soon.
Thanks.

**Comment by nghivo** [comment]
Hi @ramfattah ,
Yes, I found that Ms Team it can capture the From Name as your mention, but our target is using webchat.

Thanks,

**Comment by ramfattah** [comment]
Hi @nghivo, 

I'm also not able to capture the user name when using WebChat.
Perhaps there might be additional SSO configuration we might have to do to make this work in WebChat.

Investigating further, will report back soon.
Thanks.

**Comment by ramfattah** [comment]
Hi @nghivo, 

Thanks for your patience. 
I've created a Components NuGet Package that can be installed directly in Composer to solve this issue.

Please follow the readme to install and setup the package: 
https://github.com/ramfattah/ComposerGraphTelemetry#readme

Let me know if this helps.

In case of any issues or questions, please let me know. Thanks.

**Comment by nghivo** [comment]
Thank you so much @ramfattah , let us try with us and confirm to you today.

**Comment by ramfattah** [comment]
Thanks @nghivo, looking forward to feedbacks.

**Comment by nghivo** [comment]
Hi @ramfattah ,
Can you support to check with Shanghai team, we still cannot use with the Bot template Enterprise (Root bot, Calendar Bot and People Bot) with SSO flow?

Thanks,

**Comment by ramfattah** [comment]
Hi @nghivo,

The Enterprise Assistant Bot utilizes the [Microsoft.Bot.Components.Graph](https://www.nuget.org/packages/Microsoft.Bot.Components.Graph/) package.

Can you verify if you have this package installed:
![MicrosoftBotComponentsGraph](https://user-images.githubusercontent.com/38049078/213099930-a0b2cbd4-0ff2-4696-acab-7d3b5d319cac.png)

If yes, then you can track the user name using Composer's custom built in action called "[Telemetry - track event](https://learn.microsoft.com/en-us/composer/how-to-capture-telemetry?tabs=v2x#the-application-insights-action:~:text=The%20Application%20Insights,to%20the%20event.)".

If verified package "Microsoft.Bot.Components.Graph" is installed, sharing this possible solution to track user name in application insights:

1. Add an OAuth Login action and configure with your Azure Bot OAuth connection name 
3. Below the OAuth Login action, add "Microsoft Graph - Get Signed-in User's Profile" action in Microsoft Graph menu
    1. Result Property: `turn.result`
    2. Token: `turn.token.token`
4. Below, click '+' and add "Telemetry - track event" from Debugging options menu 
    1. Event name: `MSFTGraph`
    2. Key: `fullUserName`
    3. Value: `${turn.result.displayName}`
5. Run the bot If login was successful, check application insights for the following query:
    ```sql
    customEvents 
    | where name == "MSFTGraph"
    ```

#

Below, attached is a demo bot sample that captures current logged in user's full name in application insights using telemetry track event action:
[GetTokenFromWebChatAndTrackTelemetry.zip](https://github.com/microsoft/BotFramework-Composer/files/10442872/GetTokenFromWebChatAndTrackTelemetry.zip)

For that sample to work, please provide the following properties:
1. Application Insights connection string
2. MicrosoftAppId
3. MicrosoftAppPassword
4. OAuth Connection Name

Example:
<img src="https://user-images.githubusercontent.com/38049078/213103552-85384faa-73bf-4fa8-9e3e-d38e33e2c2a2.png" width="60%"></img>
<img src="https://user-images.githubusercontent.com/38049078/213104449-245b6ae0-8ba9-48e2-bb5c-04e99b8a2215.png" width="60%"></img>

**Comment by ramfattah** [comment]
Let me know if the helps.
Happy to answer additional questions.

Thanks.

**Comment by ramfattah** [comment]
@nghivo, any status update on this?

**Comment by nghivo** [comment]
Hi @ramfattah,
Sorry for my late reply with long Lunar new year event.

We have tested and it works very well. We can close this ticket and thank you so much.

Best regards,

Nghi
