### ISSUE TITLE
Uncaught error in Bot Framework Composer while clicking on Show Code

### ISSUE THREAD

**Issue by smithah** [microsoft/BotFramework-Composer#9431]
When i open the "Toggle Developer Tools" i see 11 errors . The installation of Bot Composer is within a wvd (Windows Virtual Deskotp)
Version of Bot Framework Composer is v2.0.0. Please let me know how to fix this issue.
![error_msg](https://user-images.githubusercontent.com/28997203/203243914-dcb5f913-0ecc-4f71-be38-29a33445bc0f.jpg)

**Comment by dmvtech** [comment]
Hi @smithah Are you able to open the `policies.dialog` file outside of Composer and verify that it is valid json?

**Comment by smithah** [comment]
If i open the policies from the localhost url , the show code opens up fine without the loading issue, but when i open it up from the tool it continues to say loading ...but doesn't go further.

But the drawback of the making the changes in the localhost url of the bot composer is , it asks for a token each time , i try to publish the changes done in the bot composer.


![image](https://user-images.githubusercontent.com/28997203/203453847-f3e472b5-bf01-4efd-acd8-33bd1b46c61c.png)

**Comment by smithah** [comment]
I have two setups of Bot composer :
1) one in production which is inside a wvd (Windows Virtual Desktop) here the bot composer tool is coming up with errors.
(not user if there is any blocking happening in wvd , when i launch from the tool - but it seems to open up fine if localhost url is used) - So unable to debug this and fix the issue.

2) Second in a local machine where its working fine without issues.

Need to get the production Bot composer setup to work.

**Comment by dmvtech** [comment]
@smithah Sorry for the delay. 

> one in production which is inside a wvd (Windows Virtual Desktop) here the bot composer tool is coming up with errors.
(not user if there is any blocking happening in wvd , when i launch from the tool - but it seems to open up fine if localhost url is used) - So unable to debug this and fix the issue.

Can you try and clear the cache from the Developer Tools (in the Composer tool)?

**Comment by smithah** [comment]
Tried clear of cache from Developer tools it still doesn't work.

**Comment by dmvtech** [comment]
When you upgraded to `2.1.2` did you uninstall `2.0.0` first? (you shouldn't have needed to. just curious)

Have you tried uninstalling Composer and then clearing the install folder, then reinstalling?

**Comment by dmvtech** [comment]
@smithah Any update? Does uninstalling and clearing the folder help at all?

**Comment by smithah** [comment]
Right now using bot composer through browser, the tool still has issues. Managing it with the browser now as a workaround.

**Comment by dmvtech** [comment]
Running Composer from Windows Virtual Desktop was not something that was tested for during development. At this point we have no plans to support Windows Virtual Desktop as supported environment. Please continue to use the workaround until further notice.
