### ISSUE TITLE
any feature available in adaptive card where while user enters the text in input field the other element text should change

### ISSUE THREAD

**Issue by premmand** [microsoft/BotFramework-Composer#9438]
I have requirement where I need to find the text length as user enters the text and show how many remaining characters he has maximum to enter in input field.I dont see any out of the box function on adaptive card is there.any suggestions on this???

**Comment by dmvtech** [comment]
This is an adaptive card question, not specific to Composer.

As this is not a bug, I would suggest asking a question (or perhaps searching for existing question) on [StackOverflow](https://stackoverflow.com/questions/tagged/adaptive-cards) with the appropriate adaptive cards tag/label. If you find that this is a bug, you can open an issue in the [Adaptive Cards repository](https://github.com/microsoft/AdaptiveCards).
