### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'config')

### ISSUE THREAD

**Issue by smithah** [microsoft/BotFramework-Composer#9440]
## Describe the bug

Getting the below error message on Bot Composer Framework on loading.

"Uncaught TypeError: Cannot read properties of undefined (reading 'config')"

## Version

BotFramework-Composer-2.1.2-nightly.326984.a27c3e5-windows-setup

## Browser

- [ ] Chrome

## OS

- [ ] Windows

## To Reproduce

1.Install the Bot composer Framework.
2. Launch it from Power Virtual Agent.
3. The reported error is seen.
4. The Show code window doen't work it remains at loading.

**Comment by smithah** [comment]
![error](https://user-images.githubusercontent.com/28997203/205556017-0acdc81e-42a9-4fca-b8b0-2f99c945fa8e.jpg)

**Comment by anishprasad01** [comment]
Hi @smithah,

Is there a specific reason you're using the nightly? Did this issue reproduce for you on a stable release?

**Comment by smithah** [comment]
Yes the same issue is seen even on the stable release of version 2.2.1.

**Comment by anishprasad01** [comment]
I was unable to reproduce this error with a PVA bot in Composer 2.1.2 stable on Windows.

Please double check that you are logged in properly, have permissions to perform the task, and check if you have any proxies or other controls on your computer that may be preventing this from working.

**Comment by smithah** [comment]
This happens only on a wvd(Windows Virtual Desktop) provided by the company and on my local laptop it works fine.There are proxy restrictions in wvd then what sites should be allowed in wvd so i can get the bot framework to work. Please let me know.

**Comment by smithah** [comment]
This is the other issue which i have raised

https://github.com/microsoft/BotFramework-Composer/issues/9431

**Comment by anishprasad01** [comment]
Azure Virtual Desktops support both Azure Firewall and proxy servers within the VD. You might first try checking to see if PVA or Composer-related domains are blocked.

**Comment by smithah** [comment]
How do i check the domains being used by PVA and Bot composer?

**Comment by smithah** [comment]
I installed the stable version 2.2.1 of Bot Composer. And added the Bot Composer Framework to the allowed list of app in Windows Firewall. This is the setting now, please let me know what more needs to be enabled

![image](https://user-images.githubusercontent.com/28997203/206700028-f5011004-2278-48bc-94cb-b6f300b54c1d.png)

**Comment by smithah** [comment]
Allowed both the Domain and the Private option for bot composer, still facing issues with cannot load config and the Show code not opening at all.

![image](https://user-images.githubusercontent.com/28997203/206703710-3edd4b54-199c-4981-9b72-42b912856bd7.png)

**Comment by anishprasad01** [comment]
This is within the Virtual Desktop, but what about the Azure Firewall or Network Security Group? This might involve your IT administrator, but let's double check before we go that far.

**Comment by smithah** [comment]
Checking on enabling the 'Public' option to be enabled for Bot Composer Framework. Will update once that is set.

**Comment by smithah** [comment]
Got the 'Public' too enabled for the Bot Composer Framework inside WVD. 

![image](https://user-images.githubusercontent.com/28997203/207003982-08c3c94d-6109-407f-8eaf-775b2934208d.png)

Still the below error is seen and the Show Code doesn't load

![image](https://user-images.githubusercontent.com/28997203/207004333-85d82555-3618-4e5f-8118-933faa88d152.png)

**Comment by anishprasad01** [comment]
Have you checked the settings *outside* the Virtual Desktop? Azure may be blocking access to more than a small preset number of domains. This behavior has also likely been configured by your IT department.

If you've tried the settings inside the VD and local testing is working, then you need to check the Azure controls.

**Comment by smithah** [comment]
https://learn.microsoft.com/en-us/power-virtual-agents/requirements-quotas#required-services

Following this will update you.

**Comment by anishprasad01** [comment]
If running Composer as a web app in the browser works, you can use that instead. The desktop application is just an electron front-end for the web app. Functionality is identical.

**Comment by smithah** [comment]
The dialog published from webapp, does not get triggered from Power Virtual Agent Topic.

**Comment by anishprasad01** [comment]
If everything works on your local machine, are you able to get permission to use that for development? I'm not sure Composer was ever designed to work in a locked-down environment like AVD.

**Comment by smithah** [comment]
No the development work needs to be done only on the WVD within the company, as there is some customer sensitive data to be used in Chat bot. 

Given internet access to WVD, Ensured that the Bot Composer has Public, Private and Domain enabled. And the installer installed in Admin Rights. 

After all this the Bot composer still comes up with the same error.

**Comment by anishprasad01** [comment]
One more question: Does this issue only occur when you are editing a PVA bot, or does it also happen for a purely Composer bot?

**Comment by smithah** [comment]
It happens on composer launch.

**Comment by anishprasad01** [comment]
Thanks for clarifying. I'm following up with the Composer team.

**Comment by anishprasad01** [comment]
@smithah

I have a list of required endpoints:
```
*.blob.storage.azure.net 
*.data.microsoft.com
dc.services.visualstudio.com
registry.npmjs.org 
api.nuget.org
botbuilder.myget.org
schemas.botframework.com
```
Please add these domains to the allowlist in your firewall and/or proxy settings and try again. These domains need to be allowed both into and out of the AVD. Adding these to the allowlist may require the assistance of your Azure subscription administrator, depending on your permission level.

**Comment by smithah** [comment]
Right now using bot composer through browser, the tool still has issues. Managing it with the browser now as a workaround.

**Comment by smithah** [comment]
Allowed full internet access on wvd.

**Comment by anishprasad01** [comment]
So it works through the browser within the Virtual Desktop, but not through the electron frontend, even with those domains allowed?

**Comment by anishprasad01** [comment]
Due to the identification of the browser app as a workaround and inactivity, I'm closing this issue. If you need more help with this, please feel free to reopen this issue and we'll be happy to help.
