### ISSUE TITLE
Composer needs .NET Core SDK error message but I already have it installed.

### ISSUE THREAD

**Issue by ekye0512** [microsoft/BotFramework-Composer#9442]
## Describe the bug

Hi, I am trying to just create a basic bot through the Azure Bot Composer. There was a problem with node.js so I tried to create through the C# bot template but I continually get an error message saying .Net is required even though I have already installed it. 
## Version

Composer Version Release: 2.1.2

- [ ] Electron distribution
- [ X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

- [ X] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior

I expect the bot to be able to be created similarly to how I created the bot with the node.js version. 

<img width="918" alt="Screen Shot 2022-12-06 at 7 52 34 PM" src="https://user-images.githubusercontent.com/38061754/206084667-90e76c9a-6b09-4fac-a80b-e2c7c0688715.png">

Thank you!

**Comment by anishprasad01** [comment]
Hi @ekye0512,

Run [`dotnet --list-sdks`](https://learn.microsoft.com/en-us/dotnet/core/install/how-to-detect-installed-versions?pivots=os-macos) to ensure you have installed a [supported .NET SDK version](https://learn.microsoft.com/en-us/composer/install-composer?tabs=windows#install-net-core-sdk). 

It's not clear from your report if you have installed just the .NET runtime or the entire SDK. You require the full SDK to build software with .NET.

**Comment by ekye0512** [comment]
> 

Hi I tried running that in the terminal and just got "zsh: command not found: dotnet
eric@Erics-MacBook-Air-6 ~ % ".

**Comment by anishprasad01** [comment]
Then you do not have the .NET SDK properly installed. Please follow the instructions to [install the .NET SDK](https://learn.microsoft.com/en-us/dotnet/core/install/macos) on your machine. 

`.NET 6.0` is the latest LTS release, and I would recommend you install that version.
