### ISSUE TITLE
Enable luis reference in composer 

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/BotFramework-Composer#945]
## Version
What version of the Emulator are you using.

## Describe the bug
To support managed LU interruption scenario, luis reference support are needed:
``` 
## Interruptions
- [AcceptEventEntry intent](../Main/Main.lu#AcceptEventEntry)
- [ChangeCalendarEntry intent](../Main/Main.lu#ChangeCalendarEntry)
- [CheckAvailability intent](../Main/Main.lu#CheckAvailability)
- [ConnectToMeeting intent](../Main/Main.lu#ConnectToMeeting)
- [CreateCalendarEntry intent](../Main/Main.lu#CreateCalendarEntry)
- [DeleteCalendarEntry intent](../Main/Main.lu#DeleteCalendarEntry)
- [Time Remaining intent](../Main/Main.lu#TimeRemaining)
```
With current ludown, composer cannot recognize luis intent reference for now. Please ensure this scenario can be supported with bf-luis.

![image](https://user-images.githubusercontent.com/16643193/65563234-89f4bd00-df7b-11e9-9275-24b744d5e46b.png)

**Comment by hibrenda** [comment]
addressed in #1608
