### ISSUE TITLE
The OAuth prompt doesn't go away after the permission is given to the bot.

### ISSUE THREAD

**Issue by thashu0424** [microsoft/BotFramework-Composer#9457]
The OAuth prompt doesn't go away after the permission is given to the bot. This prompt keeps showing even after the user has given the permissions. 
<img width="627" alt="Screenshot 2022-12-23 175120" src="https://user-images.githubusercontent.com/52147960/209350750-2c53044a-f913-467e-997c-9f55e5b54136.png">
And when clicked on continue this error comes up .
![fec2a186-3f59-43c2-bcd4-ba2aa1b4a95f](https://user-images.githubusercontent.com/52147960/209350831-18a6d827-dde6-4773-8edd-93d743268a7e.png)

**Comment by dmvtech** [comment]
Closing in lieu of https://github.com/microsoft/BotBuilder-Samples/issues/3858
