### ISSUE TITLE
Unable to increase the MaxDepth of the JSON Serialization (Newtonsoft)

### ISSUE THREAD

**Issue by RamkumarManavalan** [microsoft/BotFramework-Composer#9458]
I have used the Bot Framework Composer to build my bot. It is based on DotNet (TargetFramework: netcoreapp3.1). Details of the Composer version I use: Version: 2.1.1, Electron: 8.2.4.

In addition to enabling Slack, Skype and Teams, I have enabled Webex too via Bot.Builder.Community.Adapters.Webex adapter. 

I get the error below whenever my DialogStack exceeds a certain nested limit:
The reader’s MaxDepth of 64 has been exceeded. Path ‘DialogState.dialogStack.$values[0].state._adaptive.actions.$values[0].dialogStack.$values[0].state._adaptive.actions.$values[0].dialogStack.$values[0].state._adaptive.actions.$values[0].dialogStack.$values[0].state._adaptive.actions.$values[0].dialogStack.$values[0].state._adaptive.actions.$values[0].dialogStack.$values[0].state._adaptive.actions.$values[0].dialogStack.$values[0].state._adaptive.actions.$values[0].dialogStack.$values[0].state.options.choices[0]’.

I debugged a little and found that whenever the nesting level of dialogStack exceeds 8 in conversation.DialogState, the I get into the error above. From various documentations, I understood that I can overwrite this limit to a larger value by adding the below line in the ConfigureServices method of the Startup Class (Startup.cs).

services.AddControllers().AddNewtonsoftJson(options => {
    options.SerializerSettings.MaxDepth = 256; 
});

However, the above ended up not solving my issue. Any quick help will be highly appreciated.

Notes:
- I have this package reference in my csproj file: PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.20"
- I written a couple of custom functions which require me to use the below:
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;

**Comment by johnataylor** [comment]
@ramfattah can you verify that the snippet shown in the readme notes is correct. Thanks.

https://github.com/microsoft/botbuilder-dotnet/releases/tag/4.17.1

**Comment by RamkumarManavalan** [comment]
Thank you @johnataylor.

I tried a similar one (without the AddHttpClient()). After your response, I tried your code snippet and it did not work. The entire Startup.cs is pasted below. I tried with a higher value like 128 too, which didn't work either.


`
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime.Extensions;
using Microsoft.Bot.Builder.Integration.AspNet.Core;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Bot.Builder.Community.Adapters.Webex;
using System;

namespace ComplianceCowBot
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddHttpClient().AddControllers().AddNewtonsoftJson(options =>
            {
                options.SerializerSettings.MaxDepth = HttpHelper.BotMessageSerializerSettings.MaxDepth;
            });
            services.AddSingleton<IBotFrameworkHttpAdapter, WebexAdapter>();
            services.AddBotRuntime(Configuration);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseDefaultFiles();

            // Set up custom content types - associating file extension to MIME type.
            var provider = new FileExtensionContentTypeProvider();
            provider.Mappings[".lu"] = "application/vnd.microsoft.lu";
            provider.Mappings[".qna"] = "application/vnd.microsoft.qna";

            // Expose static files in manifests folder for skill scenarios.
            app.UseStaticFiles(new StaticFileOptions
            {
                ContentTypeProvider = provider
            });
            app.UseWebSockets();
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}
`

**Comment by ramfattah** [comment]
Thanks for the update @RamkumarManavalan. 
We are investigating further.

**Comment by RamkumarManavalan** [comment]
Any updates, team? Thanks.

**Comment by tracyboehrer** [comment]
Can you try SDK version 4.19.1?  There were some MaxDepth issues corrected in 4.19.0.  You'll likely have to edit the csproj directly.

**Comment by ramfattah** [comment]
Hi @RamkumarManavalan,

Have you had a chance to update the `Bot.Builder` NuGet packages to 4.19.1 to see if that fixes this issue?

**Comment by johnataylor** [comment]
@RamkumarManavalan please reopen this if you are still having problems. Thanks.

**Comment by SanKumar0632** [comment]
> Hi @RamkumarManavalan,
> 
> Have you had a chance to update the `Bot.Builder` NuGet packages to 4.19.1 to see if that fixes this issue?

updating the `Bot.Builder` package to latest version resolved the issue for me

**Comment by Madhav980** [comment]
@tracyboehrer @johnataylor @RamkumarManavalan @rampaged @SanKumar0632 ,can some one help me how to update the Bot.Builder , i am having issues in the bot composer, Thanks!!

**Comment by tracyboehrer** [comment]
@Madhav980 If you are using DotNet, then update the csproj Microsoft.Bot.* packages to the latest version 4.21.2.  If you are still having problems, open a new issue in this repo.
