### ISSUE TITLE
trying to send file from composer bot to SDK bot

### ISSUE THREAD

**Issue by hkrish27** [microsoft/BotFramework-Composer#9459]
Hi,
We are trying to build a live agent connectivity through our bot. The Parent bot is a composer bot and it has various features and one of them is to connect with live agent. This live agent connectivity is a skill bot built using SDK. Now in a scenario that we may need the user to send files in between their conversation with agent. The file should reach to skill bot code, and from there we have to upload them into our own server through API and the download URL will be notified to agent.
We are facing issues to achieve this.
1. we are able to send/receive text messages to and from agent through the above architecture. But not able to see the file in Skillbot end
2. Since the composer bot connects the conversation to Skill bot (Agent), not sure where the file is being received / transferred in parent bot.
3. The file upload isn't a fixed place in the conversation so we can't use the file/attachment prompt in composer.
Someone please help us to move forward.

**Comment by dmvtech** [comment]
> we are able to send/receive text messages to and from agent through the above architecture. But not able to see the file in Skillbot end

Are you able to tell, within the skillbot, if the incoming activity has any `attachments` within it?

**Comment by hkrish27** [comment]
> 

Actually no. We are able to see it in Parent bot. not in Skill bot

**Comment by sw-joelmut** [comment]
Hi @dmvtech.
If it's ok with you, we'll review this issue.

Thanks.

**Comment by dmvtech** [comment]
Thanks @sw-joelmut I was attempting to get this up and working, but was (obviously) still struggling to do so. Thank you.

**Comment by erquirogasw** [comment]
Hi @hkrish27. We were able to send files using these bots. Let us know if you are using another implementation so we can continue reviewing it.
[SimpleHostBotComposer.zip](https://github.com/microsoft/BotFramework-Composer/files/10447605/SimpleHostBotComposer.zip)
[EchoSkillBot.zip](https://github.com/microsoft/BotFramework-Composer/files/10447607/EchoSkillBot.zip)

**Comment by dmvtech** [comment]
Hi @hkrish27 Any updates? Were you able to get this working? Did the samples linked above help at all?

**Comment by dmvtech** [comment]
Closing due to lack of response. Please let us know if you are still experiencing issues (even with the above samples) and we will reopen.
