### ISSUE TITLE
Unable to open url in same tab after clicking an adaptive card

### ISSUE THREAD

**Issue by abhishekkumar717** [microsoft/BotFramework-Composer#9465]
Version:  2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

I am trying to implement a feature where I want to open a url in the same tab and not in a seperate tab upon clicking of adaptive card action button. I saw several other tickets which were opened for the same but couldn't understand what is the final solution to this and how to achieve this either from the Bot Framework side or webchat script side(not sure if this is possible).

![image](https://user-images.githubusercontent.com/120561285/211725106-d944c1f1-f69b-4df5-a43b-03389b1d4c64.png)

**Comment by anishprasad01** [comment]
Hi @abhishekkumar717,

I have two questions for you:

1. Opening in a new tab is standard behavior across the web. Can I ask why you wish to change this?
2. Could you please provide links to the similar issues you're referring to?

**Comment by abhishekkumar717** [comment]
Hi @anishprasad01 , I was refering to https://github.com/compulim/BotFramework-WebChat/blob/0b946bd8cde46c7fa7ce39270f1026d5dbff1d5f/samples/18.customization-open-url/index.html, I have found the solution anyways, thanks for your time.
