### ISSUE TITLE
Bug : Bot composer - web chat throws an exception connecting to Form Recognizer

### ISSUE THREAD

**Issue by rvinothrajendran** [microsoft/BotFramework-Composer#9492]
## Describe the bug

Bot composer - web chat throws an exception
In Bot Framework Emulator is working fine.

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [X] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1 . Connect to Form Recognizer(written custom action) 
2.  Upload the file via Web chat ( In bot composer) throws an exception

**Invalid request.

Status: 400 (Bad Request)

ErrorCode: InvalidRequest

Content:

{“error”:{“code”:“InvalidRequest”,“message”:“Invalid request.”,“innererror”:{“code”:“InvalidContent”,“message”:“The file is corrupted or format is unsupported. Refer to documentation for the list of supported formats.”}}}

Headers:

x-envoy-upstream-service-time: 393

apim-request-id: 523579a1-9792-40f4-95f9-9ed02011c29b

Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

X-Content-Type-Options: nosniff

x-ms-region: REDACTED

Date: Sun, 22 Jan 2023 15:03:48 GMT

Content-Length: 221

Content-Type: application/json; charset=utf-8**

## Expected behaviour 

It should work like Bot Framework Emulator

## Screenshots

https://user-images.githubusercontent.com/16264167/213924071-a1e127ea-dea7-458f-a138-9b6bd8cdcbe5.mp4

**Comment by stevkan** [comment]
@rvinothrajendran, thank you for your patience while I look into this. I'll post an update as soon as I know more after testing.

**Comment by sw-joelmut** [comment]
Hi @stevkan, we were able to reproduce the issue by following these two videos ([part 1](https://www.youtube.com/watch?v=8a7ccWuxgKE), [part 2](https://www.youtube.com/watch?v=PFo8QYW4vFE)).
If there's no problem, we could continue reviewing it.

**Comment by axelsrz** [comment]
@sw-joelmut is everything in place to merge the fix for this issue?

**Comment by sw-joelmut** [comment]
> @sw-joelmut is everything in place to merge the fix for this issue?

Hi @axelsrz, yes!, the linked PR #9501 is ready to be merged, thanks.
