### ISSUE TITLE
build fails on Mac M1 following instructions

### ISSUE THREAD

**Issue by davehorton** [microsoft/BotFramework-Composer#9496]
## Describe the bug
Followed install instructions with latest from main branch:

```bash
  git clone https://github.com/microsoft/BotFramework-Composer.git
  cd BotFramework-Composer
  cd Composer # switch to Composer folder
  yarn install # install dependencies
  yarn build # build extensions and libs
  yarn startall # start client and server at the same time
```
Failed immediately:
```bash
$ yarn startall # start client and server at the same time
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/Users/dhorton/beachdog-enterprises/beachdog-networks/git/BotFramework-Composer/Composer/packages/server/build/init.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

## Version
latest main (commit 77255fb10)

see above, doesn't start

## Browser
not getting that far

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [X ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

see above

## Expected behavior

product launches correct

**Comment by anishprasad01** [comment]
Hi @davehorton,

If you checkout the latest stable tag, it should work. Try the following:

1. Clone a fresh copy of Composer
2. Change into the directory and run `git checkout tags/v2.1.2`
3. Follow the instructions from here to build and run as normal

**Comment by davehorton** [comment]
thanks that worked!
