### ISSUE TITLE
[CSS] PRO | COMPOSER | In <dialogName>.triggers[0].actions[0]: Text: alwaysPrompt the return type does not match

### ISSUE THREAD

**Issue by ramfattah** [microsoft/BotFramework-Composer#9517]
ICM https://portal.microsofticm.com/imp/v3/incidents/details/367589004/home

[PROBLEM DESCRIPTION]
The customer developed their bot in Composer.

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

Customer receives this error: 
`In <dialogNmae>[0].actions[0]: Text: alwaysPrompt the return type does not match`
![image](https://user-images.githubusercontent.com/38049078/220834793-462d3f1c-989d-4735-8c58-0190c07b6b5b.png)

Attached is reproducible .zip composer bot:
[sampleRepro.zip](https://github.com/microsoft/BotFramework-Composer/files/10798022/VM-Credit-Card-VA_export.zip)

**Comment by ramfattah** [comment]
Hi @ceciliaavila,

Using Composer 2.1.1 resolved this issue. 
We need help as to why the issue is occurs in latest composer version.

We are always recommending customers to use the latest version to remain supported and have the bug fixes and product improvements. Asking to downgrade will not be fair, and at one point, they will require to upgrade their Composer version in the future. We need help to determine whether its failing due to a recent change (so they can change their validation statement) , or if this is a regression, that can fail for other customers too. 

Can it be related to below fix somehow, since that is the only one effecting the validation.ts?
PR:https://github.com/microsoft/BotFramework-Composer/pull/8566 
![image](https://user-images.githubusercontent.com/38049078/220472899-c8f01e77-e118-48ae-b20c-2ff00dafcf4f.png)


Appreciate your help on this.
Let me know if you have any questions.

Thanks.

**Comment by ramfattah** [comment]
Hey @ceciliaavila 

Sharing this update from internal engineer:

> I 've just built & tested the 2.1.2 build after changing this line
``` js
case 'string': {
      returnType = checkStringExpression(exp, types.length === 1 && types[0] === ReturnType.String);
      //returnType = checkStringExpression(
      //  exp,
      //  types.some((type) => type & ReturnType.String)
      //);
```
>Error's have gone:
![image](https://user-images.githubusercontent.com/38049078/220725756-d1c050bf-4d7e-4427-a6e3-c02a68ab65c5.png)
So, i think this is the part where it cause the problem.
Hope this helps"

**Comment by ceciliaavila** [comment]
Hi @ramfattah, thanks for the help. We are still analyzing this because these errors don't appear in normal composer bots, we think the problem could be related to PVA exported bots. We'll let you know as soon as we have news.

**Comment by ramfattah** [comment]
Thanks @ceciliaavila, I will verify if customer has exported the bot from PVA.

Will report back soon.

**Comment by erquirogasw** [comment]
Hi @ramfattah.
We were able to identify why the errors are happening, it is due to the `dialog.result.isAccountNumberValid` property being configured as a string instead of a boolean.
Although the errors are not related to the change, we will continue exploring why this is happening.
As a workaround, changing the property type to boolean and restarting Composer, makes the error disappear.

![image](https://user-images.githubusercontent.com/64815358/222184668-ce6c0929-1be4-440b-a799-f7e67234d115.png)

**Comment by ramfattah** [comment]
Thanks for your investigation @erquirogasw.

We will deliver this update to the customer. 
Much appreciated.

**Comment by ramfattah** [comment]
Hey @erquirogasw, 

Initially, looks like there are 3 errors showing when we open the bot in Composer 2.1.2:
![image](https://user-images.githubusercontent.com/38049078/222541917-cda6729e-2253-4c8a-b300-832e01bf160c.png)


We changed the dialog property to boolean instead of string:
![image](https://user-images.githubusercontent.com/38049078/222542057-cba38522-5ee4-4879-80c9-48c6442bcd1d.png)

Restarted Composer, 2 errors were resolved, 1 still remaining:
![image](https://user-images.githubusercontent.com/38049078/222542338-9001383d-5ec3-46fa-8d6d-d60c48681052.png)


Perhaps the last remaining error is given for the "User Input"? 
Error -  `In <dialog>.triggers[0].actions[0]: Text: alwaysPrompt the return type does not match `
![image](https://user-images.githubusercontent.com/38049078/222543298-8ec6d697-6814-447c-a3e4-02acd579ccdc.png)

**Comment by erquirogasw** [comment]
@ramfattah We noticed the same behavior when we didn't change the type of the < dialog > property in both _Set a property_ and _Set properties_ actions.

![image](https://user-images.githubusercontent.com/64815358/222734568-ef51f057-de69-445b-937a-df4e5fed3d8f.png)

**Comment by ramfattah** [comment]
Thank you @erquirogasw for the PR.
