### ISSUE TITLE
TextInput(Prompt for text) inherited from InputDialog fails to handle messageReaction type Activity

### ISSUE THREAD

**Issue by dawwa** [microsoft/BotFramework-Composer#9519]
## Describe the bug
The symptom is that the bot keeps prompting upon messageReaction type Activity received, as the `InputState` is recognized as `Missing` in the `OnRenderPromptAsync` method of  `Microsoft.Bot.Builder.Dialogs.Adaptive.Input.InputDialog`.

## To Reproduce

1. Create a dialog that has a step of prompting for text
2. Enable the WebChat Message Reaction, see sample at https://github.com/microsoft/BotFramework-WebChat/tree/fa77780c3bc1bfd03c6a2f70f8a63a53f123582b/samples/05.custom-components/d.reaction-buttons
3. Add a trigger for handling the Message Reaction Activity in Composer.
   ![trigger](https://user-images.githubusercontent.com/44714043/220556418-9236e678-0888-44fd-8acd-48d39a7122b7.png)

5. Try the Message Reaction - the bot would prompt upon every time the message reaction is clicked.
   ![reprompt](https://user-images.githubusercontent.com/44714043/220555058-f2d7a2dc-b65e-4e62-a53a-a4170c5be20b.gif)

6. Add the following code right before the return of the `OnRenderPromptAsync` method of  `Microsoft.Bot.Builder.Dialogs.Adaptive.Input.InputDialog`.  (You can modify the `Microsoft.Bot.Builder.Dialogs.Adaptive.Input.TextInput` class which is the `Prompt for text` Action in Composer, and override this method)
   ```csharp
      if (string.Equals(dc.Context.Activity.Type, "messageReaction", StringComparison.InvariantCultureIgnoreCase))
      {
         msg.Text = null;
      }
   ```
7. Try again, the unwanted prompt is omitted.
   ![noreprompt](https://user-images.githubusercontent.com/44714043/220555187-d8c852cf-8d48-4823-b6ad-7813f175bfe8.gif)

## Expected behavior
**The Bot should not prompt for a received messageReaction type Activity.**

**Or if there is a way to somehow make the messageReaction trigger to only process the reaction, and not let it further interfere with the current active dialog**, which is a more desired way to address this, please help provide an example if it's feasible.

**Comment by anishprasad01** [comment]
Having looked into this, the workaround of suppressing the prompt text is a good one. If it's working in the bot, then that should be an acceptable solution.
