### ISSUE TITLE
Azure Sign-In Failed: No azure directories were found. 

### ISSUE THREAD

**Issue by dlhall2376** [microsoft/BotFramework-Composer#9526]
Since upgrading to 2.1.2, I am now getting “Azure sign in failed. No Azure Directories found. I am unable to do any development with adaptive cards without this.

Tried restarting multiple times, no change.
I am able to log into my device, [make.powerapps.com](http://make.powerapps.com/), and Custom Q & A without issue.
Other devs are able to log into the same instance without issue from their devices
This started on 2/27
I am seeing all the data, and can pull from the bot profile, but I cannot publish new changes.
I am not seeing any options on how to login differently.
I rolled back to 2.1.1 and am still seeing the same issue

**Comment by dmvtech** [comment]
Hi @dlhall2376 Can you try clearing the local cache (`View-Toggle Developer Tools->Application->Storage->Local Storage` and clear anything below that) and restarting Composer and logging in anew?

**Comment by dmvtech** [comment]
Closing due to lack of response.
