### ISSUE TITLE
Unable to add two PVA bot skills through bot framework composer with the option connect to a skill

### ISSUE THREAD

**Issue by pckyn** [microsoft/BotFramework-Composer#9528]
## Describe the bug

We are able to add a PVA bot skill in bot composer successfully. When we try add another PVA skill, the below error is thrown in bot composer.
"This operation cannot be completed. The skill is already part of the Bot Project"
## Version

2.1.2
## Browser

Chrome

- [ ] Chrome

## OS

macOS
- [ ] macOS

## To Reproduce

1. Go to 'Bot Framework Composer'
2. Click on 'Connect to a skill'
3. Select PVA bot manifest zip file

## Screenshots

<img width="478" alt="image" src="https://user-images.githubusercontent.com/126873481/222705817-ae40751b-1582-49e1-93a5-a2df1ea1a2b3.png">

**Comment by pckyn** [comment]
@johnataylor , @dmvtech - Hello, did you get a chance to look into the issue. It blocks my work and unable to proceed further. Thanks.

**Comment by dmvtech** [comment]
Hi @pckyn Apologies for the delay. I am investigating and will update with findings shortly.

**Comment by dmvtech** [comment]
I can confirm this behavior and reproduce. Not sure if it is expected or not. 

@ceciliaavila Can you please comment or investigate further?

**Comment by ceciliaavila** [comment]
Hi @dmvtech, we'll add this one to our backlog, we should be tackling it next week.
Thanks!

**Comment by pckyn** [comment]
@ceciliaavila - Thank you for the update!! 
When would this fix be released? Any expected date? thanks

**Comment by ceciliaavila** [comment]
Hi @pckyn, I don't know the release date, maybe @tracyboehrer can help us with that.
