### ISSUE TITLE
What about the future of Bot Composer ?

### ISSUE THREAD

**Issue by CeBonVieuxZdoud** [microsoft/BotFramework-Composer#9534]
Hello everyone, i was wondering about Bot Composer support of Microsoft's new technologies from Azure Cognitive Services For Language and bot composer's future as a whole.

While searching answers i saw two comments that made me hesitant :
- [https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/conversational-language-understanding/how-to/migrate-from-luis?tabs=luis-portal](url) in this article where João Carlos Santos said as of 12/05/22 "there are no plans to integrate CLU in Bot Composer as LUIS was" in the comments 
- [https://github.com/microsoft/BotFramework-Composer/issues/9400](url) in this issue where Dewain27 said as of 10/18/22 "CLU guidance will be coming in the months ahead"

Is the situation of Bot Composer update clearer now and if yes, is the project on standby (as João said in the article) or not ?
Thank you.

**Comment by CharlieEvert** [comment]
Also interested in knowing this. It seems like it may be deprecated in favor of power virtual agents.

**Comment by jameslew** [comment]
Hello, sorry for the delay in responding.

The Bot Framework composer is in released state and continues to get production support in terms of bug fixes and security updates.  We do not have plans to introduce additional features and capabilities currently.

Given the composer is extensible and customers can provide their own recognizers, it's feasible that you might consume CLU within your composer bot, however we do not have plans for more native integration than that.

As @CharlieEvert mentioned, we do have ongoing investments to bring the richness of the Bot Framework Composer into Power Virtual Agents; the first iteration of which is in preview today.

**Comment by CeBonVieuxZdoud** [comment]
Good to know, thank you !

**Comment by raviraushanweb** [comment]
Thank you for sharing the update.
