### ISSUE TITLE
Unable to create Publishing Profile in Bot Framework Composer, Loading ...screen remains forever.

### ISSUE THREAD

**Issue by smithah** [microsoft/BotFramework-Composer#9540]
Following this link to Publish a Bot Framework Composer Bot to Azure, but the Publishing Profile screen remains in the Loading screen forever. Please let me know how to debug or solve this

Bot Framework Composer is V.2.1.2

https://learn.microsoft.com/en-us/composer/how-to-publish-bot?tabs=v2x

![image](https://user-images.githubusercontent.com/28997203/226109797-2588ed72-3dae-4566-9ed0-d9f7810ed92f.png)

It remains in the above screen with Loading forever...Not sure how to solve or overcome this.

**Comment by dmvtech** [comment]
Hi @smithah 

In the console window where you have started/running Composer, can you see any debug information or errors listed there?

**Comment by dmvtech** [comment]
Closing due to lack of response.
