### ISSUE TITLE
how to reference sub property with dashes in name?

### ISSUE THREAD

**Issue by fausttiger** [microsoft/BotFramework-Composer#9545]
I have API response stored in property 
dialog.api_response

one property in json package has dashes in its property name 
apim-request-id

I can't determine anyway to extract the value because of the dashes...

either get parsing errors or nulls

• ${dialog.api_response.apim-request-id}
• set property with value  =dialog.api_response.apim-request-id
• =${getProperty(dialog.api_response, 'apim-request-id')}

escaping doesn't work either
apim\\-request\\-id
apim/-request/-id

how should this work ??

example from response json:
...
"x-envoy-upstream-service-time": "907",
"apim-request-id": "4c73bfb0-cb90-43df-8c49-25c06d093fa5",
"Strict-Transport-Security": "max-age=31536000; includeSubDomains; preload",
...

**Comment by dmvtech** [comment]
I can reproduce and not able to find any workarounds. Potential bug.

**Comment by dmvtech** [comment]
Scratch that. I think you can use jpath. Try something like: `jPath(api_response, 'apim-request-id')`

If object is:
```
{
  "api_response": {
    "apim-request-id": "Success!"
  }
}
```

Tested here:
https://expressioneditor2.azurewebsites.net/

**Comment by fausttiger** [comment]
doing a quick test in Composer...   it doesn't work 
(note debugging withing Composer app..  web chat or emulator)

- Call API... results in dialog.api_response


- display json package, 
    ${dialog.api_response, 'apim-request-id'}

- try extraction with jPath... it doesn'w work

   ${jPath(dialog.api_response, 'apim-request-id')}

ERROR: 
CQA_Bot.en-us.lg:there is no matching node for path: apim-request-id in the given JSON [SendActivity_HBBp0M_text] Error occurred when evaluating expression.


![image](https://user-images.githubusercontent.com/905135/228536581-a3bdc179-efc9-4a83-8820-deaf13de7b89.png)


> Scratch that. I think you can use jpath. Try something like: `jPath(api_response, 'apim-request-id')`
> 
> If object is:
> 
> ```
> {
>   "api_response": {
>     "apim-request-id": "Success!"
>   }
> }
> ```
> 
> Tested here: https://expressioneditor2.azurewebsites.net/

**Comment by dmvtech** [comment]
If `dialog.api_response` is something like:

```
{
  "text": {
    "statusCode": 200,
    "reasonPhrase": "OK",
    "headers": {
      "apim-request-id": "28fc8073-a271-488f-b0cf-f0dc6661d44d"
    }
  }
}
```

Then I believe you should be doing:
`${jPath(api_response.text.headers, 'apim-request-id')}`

You need to get the `headers` object of the `text` object of the dialog.`api_response` object.





### Here is a quick test I did that worked for me (not using API call, just a manually created object):
![image](https://user-images.githubusercontent.com/43397658/229952535-8cc18eb9-4ca4-454e-af04-ed970ea5445d.png)

```
    {
      "$kind": "Microsoft.OnUnknownIntent",
      "$designer": {
        "id": "mb2n1u",
        "comment": "This trigger fires when an incoming activity is not handled by any other trigger."
      },
      "actions": [
        {
          "$kind": "Microsoft.SetProperties",
          "$designer": {
            "id": "Ta8i1C"
          },
          "assignments": [
            {
              "property": "dialog.myobj",
              "value": {
                "api_response": {
                  "apim-request-id": "Success!"
                }
              }
            }
          ]
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "kMjqz1",
            "comment": "It is recommended to show a message to the user when the bot does not know how to handle an incoming activity and provide follow up options or a help message."
          },
          "activity": "${jPath(dialog.myobj.api_response, 'apim-request-id')}"
        }
      ]
    }
```

**Comment by fausttiger** [comment]
> Then I believe you should be doing: `${jPath(api_response.text.headers, 'apim-request-id')}`
> 
> You need to get the `headers` object of the `text` object of the 'dialog.api_response` object.

I thought that was what I'm doing with jPath...   the  Send And HTTP Request has  JSON indicated as the result type... unless somehow it's placing the  result property not property as a JSON object...  I'll have to test.

All other properties extract fine..   dialog.api_response.xxxx.yyyy  ;  only the property with dashes.


![image](https://user-images.githubusercontent.com/905135/229966856-098004bf-4b21-41b5-9e5b-0bf6c2300cae.png)

![image](https://user-images.githubusercontent.com/905135/229966412-d97551a0-8d48-49b2-a741-84ccbf0b4e91.png)

**Comment by dmvtech** [comment]
> unless somehow it's placing the result property not property as a JSON object

Yeah, you need to understand what the response looks like and then go from there. Any luck with further testing?

**Comment by dmvtech** [comment]
Closing due to lack of response. If you need further assistance, please update with additional information and we will reopen and continue.
