### ISSUE TITLE
CLU and CICD for BotFramework Composer

### ISSUE THREAD

**Issue by duncan-at-hicksons** [microsoft/BotFramework-Composer#9548]
Hi there

Not sure if this is a feature request or a documentation request.

We've been using a CICD pipeline with BotFramework Composer based on the [MS guide here](https://learn.microsoft.com/en-us/composer/how-to-cicd).

It seems that [this is the function](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-app-service-settings-v1?view=azure-pipelines) that does the work.

We've been able to cut across to CLU readily enough locally, but keen to know about guidance on updating the CICD. Am I right there are at least three parts to that transition?
1. Remove QnA and LUIS references.
2. Prevent the templates/buildAndDeployModels.yaml from building models for these services.
3. Add in CLU references.

In relation to 3, the following CLU data appears on each *.dialog and the dialogName needs to be appended to the project name. (How) can we get CICD to add this data?

>  "recognizer": {
> 	  "$kind": "Microsoft.CluRecognizer",
>           "projectName": "projectName-**dialogName**",
>           "endpoint": "https://CLU-ENDPOINT-HERE.cognitiveservices.azure.com/",
>           "endpointKey": "CLU-KEY-HERE",
>           "deploymentName": "Name"
> 	}

Be great to have anyone's advice, tips, experience, links to documentation.

**Comment by ceciliaavila** [comment]
Closing as the new sample was included in the BotBuilder-Samples repository.
https://github.com/microsoft/BotBuilder-Samples/tree/main/composer-samples/csharp_dotnetcore/pipelines/CICDPipelineSampleCLU
