### ISSUE TITLE
Something went wrong error when clicking on Show Code feature  in Bot compose

### ISSUE THREAD

**Issue by maru55** [microsoft/BotFramework-Composer#9552]
Getting issue when opening bot composer, suggest me any  solution:

![image](https://user-images.githubusercontent.com/37395784/229996367-0ae73101-555e-4729-9117-e97b4bd63a3b.png)

After clicking on show code, still same issue showing loading like shown below:

![image](https://user-images.githubusercontent.com/37395784/229996572-ae022147-54cd-4b12-8b6f-e6da389742a2.png)

 go to any project
Add dialogue
Click on show code
 you will get this issue

Cleared cite data as well, still issue existed.

**Comment by dmvtech** [comment]
Hi @maru55 

Can you please `Show Developer Tools` from the `View` menu and then check in the developer tools console and see if there are any errors showing there.

**Comment by maru55** [comment]
![image](https://user-images.githubusercontent.com/37395784/230272742-5929290e-e570-49cb-95e5-5f2200b1ca07.png)
Yes, i am facing this problem in developer console.

**Comment by dmvtech** [comment]
Thank you. 

- What version of Composer are you using?
- What operating system?

**Comment by maru55** [comment]
Composer Version: Release: 2.1.2

OS:
Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   1.38 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	23BA2816-4CE0-4184-8FF3-4F1FD0921B5B
Product ID	00329-10181-00522-AA230
System type	64-bit operating system, x64-based processor

**Comment by MyNameIsTakenOMG** [comment]
I'm using the desktop version of Bot composer. Just couldn't show the code, instead, keep showing the error dialog:
<img width="960" alt="Capture" src="https://github.com/microsoft/BotFramework-Composer/assets/44120999/71101025-2ee0-44b2-8bbc-e0c075ec8ace">

**Comment by OEvgeny** [comment]
Please refer to the #9745

**Comment by dmvtech** [comment]
Closing as resolved. If the nightly version does not resolve the issue, please comment here and we can revisit.
