### ISSUE TITLE
Adaptive Card containing Action Button(OpenUrl) not waiting for User to Click

### ISSUE THREAD

**Issue by abhishekkumar717** [microsoft/BotFramework-Composer#9553]
Version v2.1.1

I am trying to develop a PVA integrated bot in Bot Framework Composer. I want to display an adaptive card which contains only one Action Button(OpenUrl) and is intended to redirect to a different url on other tab. Currently, the system does not wait for the user to click on the button(in contrast for a multi-choice hero card), and the next set of responses starts displaying. I want the bot to wait until the user clicks on the adaptive card(Action OpenUrl) button.

I tried displaying the adaptive card as an attachment for a response. In this case, the system does not wait for the user to click on the adaptive card button and displayed next responses.

I also tried displaying the adaptive card as an attachment to user prompt(Ask a question-Text). In this case, the system waits even after the user clicks on the adaptive card button, and the flow remains stuck forever although user is redirected to a new tab.

Could you please suggest a possible solution for this, alternatively is there a way to use a "Hero Card"  for redirecting to other url, when it is clicked.

**Comment by dmvtech** [comment]
Hi @abhishekkumar717 

There is no event/activity going back to the bot once the button is clicked with an `OpenURL` action (unlike an `action.submit`). The only thing that is all happening is on client side. So, unfortunately, there is any way to accomplish what you are attempting to do. You could do something like follow up sending the card with a confirmation prompt ("_Did you click the URL button:_ YES NO"). 

The only other thing I can think of is that if you can get an `action.submit` to happen (so the bot gets an activity) when they click on the `openurl`, then you could handle that in the bot. But you would need to figure that out on the adaptive card side of things.
