### ISSUE TITLE
error downloading template

### ISSUE THREAD

**Issue by Deepsheta** [microsoft/BotFramework-Composer#9561]
Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm root -g --prefix C:\Users\deeps\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error 'npm' is not recognized as an internal or external command, operable program or batch file.

**Comment by dmvtech** [comment]
Hi @Deepsheta 

Can you verify the versions of node and npm installed by running the following:

- `npm -v`
- `node -v`

**Comment by dmvtech** [comment]
Closing due to lack of response.
