### ISSUE TITLE
error installing npm install

### ISSUE THREAD

**Issue by Benja1512** [microsoft/BotFramework-Composer#9565]
npm ERR! code ENOENT npm ERR! syscall open npm ERR! path C:\Users\Ford/package.json npm ERR! errno -4058 npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Ford\package.json' npm ERR! enoent This is related to npm not being able to find a file. npm ERR! enoent npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Ford\AppData\Local\npm-cache\_logs\2023-04-23T17_26_26_361Z-debug-0.log

install 👍 

npm config set legacy-peer-deps true

later install
 npm i react-facebook-login

then 
install your npm

install npm!

start working!
happy day!

**Comment by Benja1512** [comment]
![image](https://user-images.githubusercontent.com/103325697/233856170-29aafbaa-01bf-4021-a821-109948e2396e.png)

**Comment by Benja1512** [comment]
![image](https://user-images.githubusercontent.com/103325697/233856225-5e72d06a-b8e5-4629-80ef-528183f360f5.png)

**Comment by ramfattah** [comment]
Hi @Benja1512, 

Thank you for your patience. I'm investigating this issue.

**Comment by ramfattah** [comment]
Hi @Benja1512, 

Is this issue occurring when building composer from 'main' branch? 

if yes, the Composer source project uses 'yarn' to install dependencies. 
[Here is the documentation](https://github.com/Microsoft/BotFramework-Composer#build-composer-locally) to build and run the Composer project locally.


If no, could you please provide more context about your issue and the steps to reproduce?
