### ISSUE TITLE
Getting an error when building the bot composer using "yarn start"

### ISSUE THREAD

**Issue by AlexChongMicrosoft** [microsoft/BotFramework-Composer#9566]
## Describe the bug

Following the doc https://learn.microsoft.com/en-us/composer/build-composer-from-source?tabs=windows, I tried to build the composer. But I get an error that "Connot find module '/home/msft/AlexDemo/BotFramework-Composer/Packages/server/build/init.js'"

## Version

2.1.2

## Browser

Edge.

## OS

 Ubuntu 20.04

## To Reproduce

Following this doc https://learn.microsoft.com/en-us/composer/build-composer-from-source?tabs=maxos
1.git clone https://github.com/microsoft/BotFramework-Composer.git
2.cd BotFramework-Composer/Composer
3.yarn install
4.yarn build
5.yarn startall. Then the error happens

## Expected behavior

The bot composer should be built and start.

## Screenshots

![image](https://user-images.githubusercontent.com/45751478/233941060-d164d5eb-7c79-4b8f-91a0-71530543490f.png)

## Additional context

I check https://github.com/microsoft/BotFramework-Composer/tree/main/Composer/packages/server, don't see the build folder.

![image](https://user-images.githubusercontent.com/45751478/233941317-5ebd2383-b609-4615-8b69-a4fb60c120e0.png)

**Comment by AlexChongMicrosoft** [comment]
@OEvgeny , thanks for reply. 

The yarn build gave me the output as below. I don't see a real error message but a warning "Browserslist: caniuse-lite is outdated". I ran npx browserslist@lateset --update-db, but still failed to run yarn start.

![image](https://user-images.githubusercontent.com/45751478/234155083-2ecc4a09-98f3-44a7-be63-92a24c8e3992.png)

**Comment by anishprasad01** [comment]
I am able to successfully build and run Composer in WSL with the following software versions:

* Ubuntu 22.04.1 LTS
* Node 14.21.3
* Yarn 3.2.1

I receive the following message in my terminal after `yarn build` completes:
```
Compiled successfully! Run "yarn startall" to start the web application & test runtime.
```

**Comment by OEvgeny** [comment]
@AlexChongMicrosoft Thank you for the screenshot

It looks like the compilation stopped due to either lack of available memory, or other hardware issue. I wonder why it didn't show the error message though.

**Comment by AlexChongMicrosoft** [comment]
@OEvgeny interesting, it's a VM hardware issue. If so, it's hard to verify this because it's hard for me to create another Linux machine for now. Once I'm available, I will try to create a testing Azure VM with linux for test.

Thanks for your help in this report. Feel free to close it for now. I will request your help if I face the same issue in a good Azure VM. Thanks in advance.

**Comment by OEvgeny** [comment]
You're welcome!

Closing for now, feel free to reopen with more details
