### ISSUE TITLE
Invalid json response body error in publish & composer dialogs fail in PVA

### ISSUE THREAD

**Issue by yagizhanarslanakinci** [microsoft/BotFramework-Composer#9568]
## Describe the bug

Bot Framework Composer fails to publish in most of the cases. Sometimes i achieve it by pulling and pushing several times until i get lucky (pull is a requirement as it says bot is not synched at a point usually). There is an issue that situation is fixed by version 2.1.1, tried but didn't help my case. Also my composer dialogs fail at random points currently. I mean totally random btw, sometimes in a loop, sometimes before a http request, sometimes when its initializing a variable. Composer dialogs throw error code 3000, which didnt lead to anything for me.

## Version

v2.1.1

## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a PVA agent
2. Create dialogs using Composer
3. Publish (and test using PVA test bot)

## Expected behavior

Error code 3000 in dialogs and publish fails

**Comment by dmvtech** [comment]
Hi @yagizhanarslanakinci 

Can you please test by using the most recent nightly build and let us know if you still have failures using that as well?
https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/

**Comment by dmvtech** [comment]
Hi @yagizhanarslanakinci

Sorry for the delay. Can you expound on 'later slowly fades away'?

**Comment by dmvtech** [comment]
Closing due to lack of response.
