### ISSUE TITLE
LU default copy should show sample

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Composer#957]
Currently, LU by default says : >To learn more about the LU file format, read the documentation at > https://github.com/Microsoft/botbuilder-tools/blob/master/packages/Ludown/docs/lu-file-format.md#lu-file-format

Issue: 

- the link is not clickable
- the github page has a bunch of info, all I need to know is what to type to get started.
- I already gave the trigger a name (getweather), this should be shown 

Much more useful would be :
#Getweather  
- < add a sentence or word that the user can say to trigger 'Getweather' >
- < add an alternative way to say the same sentence or word to trigger 'Getweather' >

**Comment by cwhitten** [comment]
To implementer:

1. When a new LU field is configured from a trigger, provide an empty intent definition with some comments showing some examples. 

```
> add some example phrases to trigger this intent:
> - please tell me the weather
> - what is the weather like in {city=Seattle}
```
2. This needs to be visible for _all_ inline LU editors (trigger wizard, forms, prompts, all-up LU page)

**Comment by hibrenda** [comment]
Meanwhile, we could provide the sample for entity definition as well.
```
> entity definitions
@ ml city
```

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2712
