### ISSUE TITLE
Problem with the body of http request post

### ISSUE THREAD

**Issue by ValentinCham** [microsoft/BotFramework-Composer#9572]
Hello,
I try to send an http request (post) with a body like this : 
```
{
"message": "string",
"userId": "string",
"conversationId": "string"
}
```
But i have this error :   "Unsupported Media Type".
I have put as Content type : application/json so for me it should work but no ...
![image](https://user-images.githubusercontent.com/70703240/234981571-a757d3f9-be5b-4bc1-9181-796db5b984a1.png)
I have try this but i can't put this function in body.
Can you help me ?
if you have any questions don't hesitate :)

**Comment by dmvtech** [comment]
Hi @ValentinCham 

I assume it works if you hardcode the values in the body?

**Comment by dmvtech** [comment]
Closing due to lack of response.
