### ISSUE TITLE
Composer + Telephony Package encode locale string with "\", making them non-funtional

### ISSUE THREAD

**Issue by jameslew** [microsoft/BotFramework-Composer#9573]
## Describe the bug

When you put SSML tags inside of the speech variant node, occasionally a locale string needs to be included - say en-US.  The Composer unfortunately is encoding those strings with a "\", making them non-functional:

<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="en\-US">
<voice name="en\-US\-AriaNeural">
<lang xml:lang="en-US">Please press 1 for English or 2 for Spanish.</lang>
<break time="5000ms"/>
<break time="5000ms"/>
<break time="5000ms"/>
<break time="5000ms"/>
<lang xml:lang="en\-US">Stop Silence</lang>
</voice>
</speak>

We need to not encode these tags in the edit box, or decode them as well so they stay functional.
## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Add the telephony package
Add a multi-choice with silence detection node
Add a speech variant
Paste the following into the box:

<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="en-US">
<voice name="en-US-AriaNeural">
<lang xml:lang="en-US">Please press 1 for English or 2 for Spanish.</lang>
<lang xml:lang="en-US">Stop Silence</lang>
</voice>
</speak>

Nave away and back to the node; it shows encoded locales.

## Expected behavior

No Encoding applied

## Additional context

Impacts users of Dynamics Omnichannel trying to build voice skills for DTMF handling.

**Comment by JhontSouth** [comment]
We have been able to replicate the issue, but only when using multi-line SSML tags. This issue was reported [here](https://github.com/microsoft/BotFramework-Composer/issues/9441), but the [PR](https://github.com/microsoft/BotFramework-Composer/pull/9444) with the fix is not yet merged.

**Comment by tracyboehrer** [comment]
Duplicate
