### ISSUE TITLE
Provision failure

### ISSUE THREAD

**Issue by rhalbheer** [microsoft/BotFramework-Composer#9575]
## Describe the bug
My subscription is connected to a passwordless Microsoft consumer account.
Initially, I tried to provision from a AAD-joined machine but was unable to log in to start with (up to the point, where the app crashed).

I now tried on an unmanaged machine. I could authenticate and start a publishing profile. 
When it executes, it fails. (see the logs below)

## Version
2.1.2

## Browser
Edge

## OS
Windows 11

## To Reproduce
Publish
create Publishing Profile
Add New
Publish to Azure
Create new resources
Select the existing Subscription and the Existing RG
De-select all the optional components

## Expected behavior
Deploy the bot 

## Additional context
This is the error message:
```
{"name":"CREATE_APP_REGISTRATION","message":"App create failed! Please file an issue on Github.","stack":"Error\n at new CustomizeError (C:\\Users\\roger\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:276418:25)\n at createCustomizeError (C:\\Users\\roger\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:276423:10)\n at BotProjectProvision.createApp (C:\\Users\\roger\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:277931:17)"}. See provision.rha-ba-bot.log in your bot folder
```

And this is the content of the log:
`{
  "profileName": "ba-bot",
  "jobId": "d4b5180e-4b0a-4db4-bc72-a7714af7d20e",
  "projectId": "94447.42802876871",
  "time": "2023-05-05T12:52:35.774Z",
  "log": [
    "Creating Azure resources...",
    "Checking the Existence of the Resource Group ...",
    "Use the Resource Group: rg-ba-bot at eastus",
    "> Creating App Registration ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed after 3 retries. Error: Request failed with status code 500",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Users\\\\roger\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276418:25)\\n    at createCustomizeError (C:\\\\Users\\\\roger\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276423:10)\\n    at BotProjectProvision.createApp (C:\\\\Users\\\\roger\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:277931:17)\"}",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Users\\\\roger\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276418:25)\\n    at createCustomizeError (C:\\\\Users\\\\roger\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276423:10)\\n    at BotProjectProvision.createApp (C:\\\\Users\\\\roger\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:277931:17)\"}. See provision.ba-bot.log in your bot folder"
  ]
}`

**Comment by anishprasad01** [comment]
Hi @rhalbheer,

I'm able to reproduce this, though it does not appear to be specific to passwordless accounts, but to MSA accounts in general. Looking in to next steps.

**Comment by ceciliaavila** [comment]
> @ceciliaavila,
> 
> Could you look into this? Composer is unable to provision Azure resources on personal/MSA accounts, though this should be supported.
> 
> I'm able to reproduce this with a basic empty bot on both password-enabled and passwordless MSA accounts. Work & school accounts are unaffected.

Hi @anishprasad01, we added this to our backlog and we'll be tackling it next week. Thanks!

**Comment by ceciliaavila** [comment]
Hi @anishprasad01, @rhalbheer,
We tried to repro the issue using a personal MSA. In our case, the deployment failed with a 401 error when creating the App Registrations.
We solved this by granting the **_Application Administrator_** role to our AD account.
Additionally, we had to register _Microsoft.Web_ and _Microsoft.BotService_ resource providers in the subscription to be able to create the Web App and the App Service.
With these configurations in place, we created the Azure resources and deployed the bot successfully.
Are we missing something? Do you have these permissions in your account?
![image](https://github.com/microsoft/BotFramework-Composer/assets/44245136/9aac04e9-db88-4f2b-8fb9-44a7b9c3503a)

**Comment by anishprasad01** [comment]
I have Application Administrator and Microsoft.BotService, but I did not have Microsoft.Web. I will register this provider and attempt the deployment again.

**Comment by rhalbheer** [comment]
I did not have Application Administrator.
However, when I am creating a publishing profile, I create new resources, I try to log in - before I get prompted in my authenticator app, the Bot Framework Composer crashes with the following event. 
This might be unrelated as I cannot even authenticate currently

```
Log Name:      Application
Source:        Application Error
Date:          16.05.2023 22:46:03
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          xxxxxxxx
Computer:      xxxxxxxx
Description:
Faulting application name: Bot Framework Composer.exe, version: 2.1.2.27508, time stamp: 0x5e9f0152
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000200000003
Faulting process id: 0x0x7460
Faulting application start time: 0x0x1D988372E0ED9F2
Faulting application path: C:\Users\xxxxxxx\AppData\Local\Programs\Bot Framework Composer\Bot Framework Composer.exe
Faulting module path: unknown
Report Id: 1a9f71cd-d75d-4980-9442-c7e329c8cd77
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-05-16T20:46:03.9343721Z" />
    <EventRecordID>5352</EventRecordID>
    <Correlation />
    <Execution ProcessID="37956" ThreadID="368" />
    <Channel>Application</Channel>
    <Computer>xxxxxxxxx</Computer>
    <Security UserID="S-1-12-1-2723588067-1287575777-1784178083-3514307553" />
  </System>
  <EventData>
    <Data Name="AppName">Bot Framework Composer.exe</Data>
    <Data Name="AppVersion">2.1.2.27508</Data>
    <Data Name="AppTimeStamp">5e9f0152</Data>
    <Data Name="ModuleName">unknown</Data>
    <Data Name="ModuleVersion">0.0.0.0</Data>
    <Data Name="ModuleTimeStamp">00000000</Data>
    <Data Name="ExceptionCode">c0000005</Data>
    <Data Name="FaultingOffset">0000000200000003</Data>
    <Data Name="ProcessId">0x7460</Data>
    <Data Name="ProcessCreationTime">0x1d988372e0ed9f2</Data>
    <Data Name="AppPath">C:\Users\xxxxxxxxx\AppData\Local\Programs\Bot Framework Composer\Bot Framework Composer.exe</Data>
    <Data Name="ModulePath">unknown</Data>
    <Data Name="IntegratorReportId">1a9f71cd-d75d-4980-9442-c7e329c8cd77</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>
```

**Comment by ceciliaavila** [comment]
Hi @rhalbheer,
Not having the **_Application Administrator_** role should be causing the original issue, as it's required to create App Registrations in Azure.
As for the new error, the c0000005 exception code means a memory access violation. It sounds like a different problem, not Composer related.
