### ISSUE TITLE
Unable to Integrate composer bot(which is using CLU custom recognizer) with Bot Framework SDK Bot Solution (C#)

### ISSUE THREAD

**Issue by srinath555** [microsoft/BotFramework-Composer#9579]
Hi Team, 

I want to Integrate a composer CLU Bot in Bot Framework SDK Bot Solution(c#).
So I've created a composer language bot and added CLU as custom recognizer to it and then i've added some logic to my bot framework SDK Bot solution to consume the composer dialogs, But I'm facing an issue with the CLU Recognizer package (https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/ConversationLanguageUnderstanding/dotnet).
![image](https://github.com/microsoft/BotFramework-Composer/assets/26254940/3f9e2a16-72df-45fd-b7c5-bfbaa2ee67d2)

If we use the above package in our bot source code then we need to upgrade the **bot builder**  nuget package version to **>= 4.18.1**, if we do that then it is leading to the below error while executing the code.
![image](https://github.com/microsoft/BotFramework-Composer/assets/26254940/640ec3f0-1748-4611-b496-d895763164e4)

(Note: this same source code is working fine with other composer bots which are not using the CLU Custom Recognizer because the Bot Builder version is 4.8.0 for the other bots).  

So, to describe the issue in short, if we use CLU Custom Recognizer package for composer bots which is expecting the Bot.Builder version >=4.18 but when composer dialogs added to source code,  it is expecting the Bot.Builder version = 4.8.0 otherwise it is throwing the exception as shown in the above image.

Please help me to resolve this issue ASAP, Thanks in advance!

**Comment by anishprasad01** [comment]
Hi @srinath555,

Are you trying to use Adaptive Composer Dialogs directly in an SDK bot, as opposed to calling the Composer bot as a skill? Additionally, are you directly updating version 4.8 to 4.18?

**Comment by srinath555** [comment]
Yes @anishprasad01, I'm using adaptive compose dialogs directly on an SDK bot. It is working for other composer file, but when we add clu package it is throwing error because bot builder is upgrading to 4.18.
