### ISSUE TITLE
DirectLine WebSocket channel sending OPTIONS /api/messages and causing 405

### ISSUE THREAD

**Issue by lshade** [microsoft/BotFramework-Composer#9582]
## Describe the bug

We recently deployed a small .lg file change to our BotComposer bot using Azure Pipelines, and successfully tested it in the WebChat and Telephony channels; however, the DirectLine WebSocket channel is now unable to communicate with the bot. We are seeing a 405 error in App Insights. It looks like it's sending an OPTIONS request to our /api/messages endpoint and no POSTs.

## Version

v2.1.2

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

I'm available to screenshare.

**Comment by dmvtech** [comment]
Hi @lshade 

The 405 for OPTIONS is not something of concern. That can be seen in normal, functioning bots in all sorts of channels. But not sending POSTs obviously is problematic.

- Are there no other errors other than the 405? 
- When you say `DirectLine WebSocket channel`, do you mean the basic `Direct Line` channel or the `Direct Line Speech` channel?

**Comment by lshade** [comment]
Hi @dmvtech ,

I searched through our production logs and our bot running in prod in this channel does not have any logs showing OPTIONS requests.

- Correct, there are no other errors
- Not Direct Line Speech. We're using a third party channel and they have gone off of this documentation for a websocket connection: https://learn.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-receive-activities?view=azure-bot-service-4.0#receive-activities-via-websocket-stream
    -  They said they haven't changed anything in their implementation to cause this. I had them switch to use our Dev bot's DirectLine secret, and the errors went away. We deployed the same bot code to Dev and Test
