### ISSUE TITLE
Bot failed to start

### ISSUE THREAD

**Issue by frgregb** [microsoft/BotFramework-Composer#9586]
## Describe the bug
The Bot status is "Failed" 

I am trying to start the weather bot (of the tutorials) .. .it was working fine till the section of reading the weather via and HTTP request to "openweather".  
The return of the request was correct. 
Then after doing the steps to install Cancel and Help, and then add an "Attachment" to report the output of the HTTP request to get the weather, then the Bot would not start. 

## Version

I am using version 2

## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by frgregb** [comment]
Thank you Steven,
I was able to resolve the problem, I think it was an oversight on my part.

**Comment by stevkan** [comment]
Closing as resolved.
