### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by davidcg96** [microsoft/BotFramework-Composer#9590]
Hi, im working in a Bot and there are random things with composer.
I have main dialog with intents (welcome, cancel)
First, with LUIS if i create a new dialog and add an user promp like ask->text. 
example:
main dialog -Bot: welcome to your bot
main dialog -user: hello
welcome dialog -Bot: ¿what is your name?
welcome dialog -User: cancel

in this moment with LUIS, the bot recognize the intent "cancel" what is defined but if i use CLU its imposible that the bot can reconigze the intent. 

Second, I create new dialog with multiple options and suggest buttons (sign-in, talk-cancel).
example;
main dialog -Bot: welcome to your bot
main dialog -user: hello
welcome dialog -Bot: ¿what is your name?
welcome dialog -User: david
NewDialog -Bot: The options to do are: suggest(sign-in, talk, cancel)
NewDialog -user: cancel

now in this moment, when i push cancel, redirect me to dialog cancel of the packet helpandcancel. this finaly all active dialog but always remains in cancel dialog. if I delete cancel all active dialog and i use reemplaze this dialog to main. this action not work.

my questions are two:

how can i implemented cancel action with CLU??? 
How can i implemented intents with Clu in all new dialogs??

**Comment by anishprasad01** [comment]
Hi @davidcg96,

> now in this moment, when i push cancel, redirect me to dialog cancel of the packet helpandcancel. this finaly all active dialog but always remains in cancel dialog. if I delete cancel all active dialog and i use reemplaze this dialog to main. this action not work.

Could you please elaborate on what exactly you're doing here, and what is and isn't working? I'm not exactly clear on that.
