### ISSUE TITLE
Error starting bot

### ISSUE THREAD

**Issue by JurgenPostelmans** [microsoft/BotFramework-Composer#9591]
## Describe the bug

I installed the Bot Framework Composer and created a new Bot. Tried to run it and it immediately failed.
The output window displays the following info..

/Users/<XXX>/Projects/CSI/CSIBOT/CSIBOT/CSIBOT.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
/Users/<XXX>/Projects/CSI/CSIBOT/CSIBOT/CSIBOT.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

**Error occurred building the bot**

You must install or update .NET to run this application. App: /Users/<XXX>/Projects/CSI/CSIBOT/CSIBOT/bin/Debug/netcoreapp3.1/CSIBOT Architecture: x64 Framework: 'Microsoft.AspNetCore.App', version '3.1.0' (x64) .NET location: /usr/local/share/dotnet/x64 The following frameworks were found: 6.0.12 at [/usr/local/share/dotnet/x64/shared/Microsoft.AspNetCore.App] Learn about framework resolution: https://aka.ms/dotnet/app-launch-failed To install missing framework, download: https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=osx.13-x64

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ x] macOS
- [ ] Windows
- [ ] Ubuntu

## Expected behavior

The bot should start running and not fail to start.

**Comment by dmvtech** [comment]
Hi @JurgenPostelmans 

Can you please run the following in a terminal and share the output?:
`dotnet --info`

**Comment by JurgenPostelmans** [comment]
Hi @dmvtech,

Below is the full output of `dotnet --info`. As you can see I have .NET 7(and 6) installed. In the documentation it says 'Install .NET Core SDK 3.1 or later.'. So this should be ok.

NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.302/

Host:
  Version:      7.0.5
  Architecture: arm64
  Commit:       8042d61b17

.NET SDKs installed:
  6.0.404 [/usr/local/share/dotnet/sdk]
  6.0.408 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

**Comment by dmvtech** [comment]
Hi @JurgenPostelmans 

Apologies for the delay.  It looks to be the issue described here and here.

Can you try and update the following line in your `.csproj` file:
`<TargetFramework>netcoreapp3.1</TargetFramework>`

To:
`<TargetFramework>net6.0</TargetFramework>`

and then try again?

I will look further into getting the template updated to the same.

**Comment by JurgenPostelmans** [comment]
That did indeed solve my problem! 

Thanks
