### ISSUE TITLE
Package Manager Error

### ISSUE THREAD

**Issue by varMrHYDRA** [microsoft/BotFramework-Composer#9594]
1. Unable to download or search packages in Nugget. Also unable to use search feature.
![image](https://github.com/microsoft/BotFramework-Composer/assets/121287138/99c71cc2-3a0f-40bc-af50-0aa4d07c7a1f)
2. Sometimes It just kept installing.
![image](https://github.com/microsoft/BotFramework-Composer/assets/121287138/f249fd2f-4d3a-47fc-a184-bd30ff32719a)
3. Unable to use sometime gets this error.
![image](https://github.com/microsoft/BotFramework-Composer/assets/121287138/d3af52ac-0f2e-4114-af45-929eadad602d)

**Comment by anishprasad01** [comment]
Hi @varMrHYDRA,

Could you please provide more details, such as any specific error messages? It is impossible to investigate the issue without any clues as to what problem you are experiencing.

**Comment by obaidmuneer** [comment]
@anishprasad01 
am getting the same error while installing botbuilder-ai-orchestrator
Error
`Command failed: npm install --loglevel=error --save botbuilder-ai-orchestrator npm ERR! code 1 npm ERR! path C:\Users\Obaid Muneer\Desktop\azure_bot\demo\demo\node_modules\@microsoft\orchestrator-core npm ERR! command failed npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install npm ERR! response status 404 Not Found on https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.14.4-node-v108-win32-x64.tar.gz npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.14.4-node-v108-win32-x64.tar.gz npm ERR! node-pre-gyp ERR! install error npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://bcmodelsprod.azureedge.net/native/orchestrator-core-v4.14.4-node-v108-win32-x64.tar.gz npm ERR! node-pre-gyp ERR! stack at C:\Users\Obaid Muneer\Desktop\azure_bot\demo\demo\node_modules\@mapbox\node-pre-gyp\lib\install.js:67:15 npm ERR! node-pre-gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5) npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22621 npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Obaid Muneer\\Desktop\\azure_bot\\demo\\demo\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" npm ERR! node-pre-gyp ERR! cwd C:\Users\Obaid Muneer\Desktop\azure_bot\demo\demo\node_modules\@microsoft\orchestrator-core npm ERR! node-pre-gyp ERR! node -v v18.16.0 npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10 npm ERR! node-pre-gyp ERR! not ok npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Obaid Muneer\AppData\Local\npm-cache\_logs\2023-06-11T15_00_30_135Z-debug-0.log`
