### ISSUE TITLE
CLU option not displaying in Bot Composer

### ISSUE THREAD

**Issue by ykr22** [microsoft/BotFramework-Composer#9596]
Hi team,

Earlier we are using LUIS and planning to migrate to CLU.

We have trying to publish the profile with CLU but we are not getting the option.

PFA 

![image](https://github.com/microsoft/BotFramework-Composer/assets/90302824/15b3c0d4-a54b-44a3-ac9d-ff65c2ce56a4)
<img width="445" alt="CLU" src="https://github.com/microsoft/BotFramework-Composer/assets/90302824/c690a599-8991-4a84-97a0-f14ea79689f9">

**Comment by anishprasad01** [comment]
@ykr22,

This is not the intended deployment process for CLU. 

You would instead install the [CLU Recognizer](https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/ConversationLanguageUnderstanding/dotnet), which would itself need to be deployed before you can configure it in your bot. The README in the recognizer explains how to install the package and configure it for your Composer bot. You will not be able to re-deploy CLU changes through Composer.
