### ISSUE TITLE
Error in creating new bot in bot framework composer

### ISSUE THREAD

**Issue by testrepro** [microsoft/BotFramework-Composer#9605]
I am getting this error

Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: `npm install -g --prefix /Users/nikhil/BotFrameworkComposer/.yo-repository --loglevel error --no-optional @microsoft/generator-bot-empty@1.4.2`

I have nodejs yarn and .net sdk installed still getting this error

**Comment by anishprasad01** [comment]
Hi @testrepro,

I am unable to reproduce your issue with either a C# or Node template on Composer 2.1.2.

Perhaps you could try manually running the failing command and check what error message it may provide?

**Comment by bk2012** [comment]
I also gets the same issue, Node version v18.16.0 and npm 9.5.1. Bot Framework composer version v2.12

**Comment by anishprasad01** [comment]
@bk2012,

I am running the same versions and do not face this issue. Are you behind a restrictive proxy or firewall? Are you able to reach npm to download packages?

**Comment by testrepro** [comment]
@anishprasad01 

How do i check if npm is able to reach to download packages, i am running bot framework composer on macbook with m1 chip and I am getting problem on mac only, in windows it works perfectly

**Comment by anishprasad01** [comment]
@testrepro,

Ah, that would be it. Composer does not support M1/M2 chips.
