### ISSUE TITLE
Luis build failed: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by Kmaczek** [microsoft/BotFramework-Composer#9611]
My colleagues cant use Bot Composer v2.1.2 or bot framework emulator.

Starting chat results in 

```
Sorry, something went wrong with publishing. Try again or exit out of this task.
Luis build failed: Cannot read property 'error' of undefined
```

They might be behind proxy, and they are on a machine with strict organizational network controls.
What we can do to remediate this?

Its similar to this one: https://github.com/microsoft/BotFramework-Composer/issues/9600

**Comment by ramfattah** [comment]
Hi @Kmaczek, I'm looking into this.

**Comment by ramfattah** [comment]
Hi @Kmaczek, 

Since they might be behind proxy that is not allowing the Node.js runtime to make certain external network calls. You can get around this temporarily by running a shell or command prompt before starting the composer application from same terminal window.

On Windows, run:

```powershell
SET NODE_TLS_REJECT_UNAUTHORIZED=0
```

On Mac, run: 

```zsh
 export NODE_TLS_REJECT_UNAUTHORIZED=0
```


then, start composer from same terminal window by running:
```powershell
& '.\Bot Framework Composer.exe'
```
![image](https://github.com/microsoft/BotFramework-Composer/assets/38049078/b0bfa36d-899b-4a3f-affa-ead5bbc64c99)


Let me know if this solves the issue. Thanks.

**Comment by Kmaczek** [comment]
@ramfattah Thank you, I will let them know

**Comment by Kmaczek** [comment]
@ramfattah This did not helped, but we have more info now

This are my logs when I click Start bot:
[working_chatbot.log](https://github.com/microsoft/BotFramework-Composer/files/12260567/working_chatbot.log)

This are colleague 1, with proxy/security
[Chatbot_console.txt](https://github.com/microsoft/BotFramework-Composer/files/12260625/Chatbot_console.txt)

This are from colleague 2, with proxy/security
[composer_log.txt](https://github.com/microsoft/BotFramework-Composer/files/12260637/composer_log.txt)

There is one cert issue
```
ApplicationInsights:CorrelationIdManager [
  Error: self signed certificate in certificate chain
      at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
      at TLSSocket.emit (events.js:210:5)
      at TLSSocket._finishInit (_tls_wrap.js:794:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
    code: 'SELF_SIGNED_CERT_IN_CHAIN'
  }
]
```

Then some project feed fails with 404
`GET /api/projects/feed 404`

And build fails with 400
`POST /api/projects/39856.60175929109/build 400`

**Comment by ramfattah** [comment]
Thank you @Kmaczek, looking into this further.

**Comment by ramfattah** [comment]
@Kmaczek, 

To clarify, are you using the [ConversationLanguageUnderstanding](https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/ConversationLanguageUnderstanding) recognizer package?

Could you please provide the steps to reproduce this issue?

**Comment by ramfattah** [comment]
@Kmaczek 

We might need to enable "debug mode" for Composer to capture the full logs on this "luis build failed" error.

Could you please run Composer in Debug mode via terminal, then attempt to reproduce the issue and send us the logs dive more into this issue?

To enable and run Composer in debug mode, please follow these step-by-step instructions.

1) Completely close Composer if already open
2) Go to Composer's install location (mine is at C:\Users{username}\AppData\Local\Programs\Bot Framework Composer)
3) Open a terminal in that directory
4) run `set DEBUG=composer*`
5) run the executable from the terminal. 
     * Ex: in Windows command prompt: run `"Bot Framework Composer.exe"`

> <strong>Important<strong>: You have enabled debugging successfully if you see prefixed `composer:____`  in the log:

![image](https://user-images.githubusercontent.com/38049078/162352571-ce46251e-872a-4c0a-a322-814ce35503a7.png)

#

We will take a look at the log to see what is the cause of this issue.
Let me know if you have any questions. Thanks.

**Comment by Kmaczek** [comment]
> @Kmaczek,
> 
> To clarify, are you using the [ConversationLanguageUnderstanding](https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/ConversationLanguageUnderstanding) recognizer package in your composer bot?
No
> 
> Are you facing this issue when attempting to publish or chat to the bot? Could you please provide the steps to reproduce this issue?
When starting bot
![image](https://github.com/microsoft/BotFramework-Composer/assets/1743813/b704af70-0248-438f-975a-0f813e979ab0)

Steps to reproduce:
1. Open Bot Framework Composer v2.1.2
2. Make sure config is correct (LUIS)
3. Click button **Start bot**

> 
> Also if you are indeed behind a proxy, have you had a chance to follow the Configure a proxy server documentation? https://docs.microsoft.com/en-us/composer/configure-composer-proxy?tabs=windows

No, we will try this

**Comment by Kmaczek** [comment]
@ramfattah 
Please find below logs of my colleague 
[composer_debug.txt](https://github.com/microsoft/BotFramework-Composer/files/12462847/composer_debug.txt)

**Comment by ramfattah** [comment]
Thank you @Kmaczek, we are looking into the logs.

**Comment by ramfattah** [comment]
@Kmaczek,

Looks like the error message shows that a request to GitHub failed due to a self-signed certificate in the certificate chain.

```vim
composer {
    "message": "request to https://raw.githubusercontent.com/microsoft/BotFramework-Composer/main/templates.json failed, reason: self signed certificate in certificate chain",
    "type": "system",
    "errno": "SELF_SIGNED_CERT_IN_CHAIN",
    "code": "SELF_SIGNED_CERT_IN_CHAIN",
    "stack": "FetchError: request to https://raw.githubusercontent.com/microsoft/BotFramework-Composer/main/templates.json failed, reason: self signed certificate in certificate chain\n    at ClientRequest.<anonymous> (C:\\Users\\user_name\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar\\node_modules\\@bfc\\server\\node_modules\\node-fetch\\lib\\index.js:1461:11)\n    at ClientRequest.emit (events.js:210:5)\n    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n    at TLSSocket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
```

Hypothetically, setting `NODE_TLS_REJECT_UNAUTHORIZED` to 0 "_should_" bypass this issue temporarily during development . 
I think you've already tried this and [configuring a proxy server](https://learn.microsoft.com/en-us/composer/configure-composer-proxy?tabs=windows), but it seems those steps haven't resolved the issue. 

Could you try the following suggestions to see it helps:
1. In Composer, create fresh new Echo Bots in both `C#` and `Node.js`, then run each bot to see if the issue repro's.
2. If you're running Composer in a containerized environment, make sure it has access to the external network.
3. Ensure that the environment variables (ex: `SET NODE_TLS_REJECT_UNAUTHORIZED=0`) are correctly set in the same terminal session where you are running Composer.

**Comment by Kmaczek** [comment]
@ramfattah 

SET NODE_TLS_REJECT_UNAUTHORIZED=0
Worked when we tried today again! 

I'm not sure why it didn't worked the first time, we probably missed something. 
Anyway big thanks for your help and patience.

**Comment by ramfattah** [comment]
SWEET!!! Glad to hear it @Kmaczek.
