### ISSUE TITLE
Failure to create new project

### ISSUE THREAD

**Issue by muntazirnaqvi** [microsoft/BotFramework-Composer#9616]
## Describe the bug

Bot Framework Composer does not seem to work when creating a new "Empty Bot"

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Edge

## OS

- [ ] Windows

## To Reproduce

1. Open Bot Framework Composer
2. Click on **+ Create New**
3. Select **Empty Bot**, click **Next**
4. Enter **Name** and **Location** and select **Runtime Type** as Azure Web App
5. Error occurs

## Expected behavior

A template for Empty Bot should be generated.

## Screenshots

<img width="217" alt="Capture" src="https://github.com/microsoft/BotFramework-Composer/assets/69722122/592312bd-9ada-4844-9d97-a3d6d8fc4c15">

## Additional context

The error first occured while doing the Lab on Microsoft Learn. Tried running the Composer outside the lab environment also - on a Mac. The same error appears.

**Comment by ramfattah** [comment]
Hi @muntazirnaqvi, 

Asking clarifying questions:
1. What operating system does this issue reproduce in? 
2. Is this a dotnet or node.js Composer bot?

**Comment by muntazirnaqvi** [comment]
Hi @ramfattah,

1.  This issue reproduces in Microsoft Learn lab environment which has Windows 10 Enterprise. A colleague tried on macOS also, the issue reproduces there as well.
2. It's a dotnet Composer bot (as you may see from the error screenshot, "dotnet build" fails)

**Comment by dabor238** [comment]
I'm trying to do the wheather bot project but I'm having the same error: 

##Error
If this problem persists, please file an issue on [GitHub](https://github.com/microsoft/BotFramework-Composer/issues)
Details
Command failed: dotnet build weather_bot.csproj


##OS
Windows 10 

##Composer
Installed the .net core SDK 3.1.32
Installed node v18.17.0 via nvm and npm 9.6.7

**Comment by dabor238** [comment]
> 

So I tryed to create the template with node framework and it worked well. The problem is just with dotnet framework template.

**Comment by ramfattah** [comment]
Hi @muntazirnaqvi, 

I'm not able to reproduce this issue using the latest version of [Composer 2.1.2](https://github.com/microsoft/BotFramework-Composer/releases) when creating a dotnet bot.

Windows 11
Node v18.16.0
DotNET SDKs installed: [ 3.1 & 7.0 ]
![image](https://github.com/microsoft/BotFramework-Composer/assets/38049078/7b5a24df-5cd3-44ad-b0b5-b9755f4b5412)

**Comment by ramfattah** [comment]
Hey @muntazirnaqvi,

Could you please run Composer in Debug mode via terminal and send us the logs to further investigate this issue? 


To enable and run Composer in debug mode for a more detailed analysis of its operations, carefully follow these step-by-step instructions provided below.

1) Completely close Composer if already open
2) Go to Composer's install location (mine is at C:\Users{username}\AppData\Local\Programs\Bot Framework Composer)
3) Open a terminal in that directory
4) run `set DEBUG=composer*`
5) run the executable from the terminal. 
     * Ex: in Windows command prompt: run `"Bot Framework Composer.exe"`

> <strong>Important<strong>: You have enabled debugging successfully if you see prefixed `composer:____`  in the log:

![image](https://user-images.githubusercontent.com/38049078/162352571-ce46251e-872a-4c0a-a322-814ce35503a7.png)

#

We will take a look at the log to see what is the cause of this issue.
Let me know if you have any questions. Thanks.

**Comment by ramfattah** [comment]
Thanks @dabor238, 

Could you please run Composer in Debug mode via terminal and send us the logs to further investigate this issue?

**Comment by muntazirnaqvi** [comment]
@ramfattah 
The issue does not reproduce anymore (Compoer v2.0.0) for me. Perhaps it was some transiet bug. 
My guess is that there was an issue with downloading the bot template, because it failed at "Downloading template" stage. Anyway, no problems now. 
Thanks.
