### ISSUE TITLE
Bot checking user's inactivity duration(upon user's response)

### ISSUE THREAD

**Issue by SanKumar0632** [microsoft/BotFramework-Composer#9617]
I am currently building a bot using node.js, the composer should have a native feature to create triggers that can do this: when the user replies to the bot after a period of time, it should be able to check the difference between the 'last replied' time stamp and current timestamp, then follow defined actions, if the difference(milliseconds) exceeds a defined value. And this should work on each response from the user.

## Describe alternatives you've considered

What I am trying to do now is that I have created an "Activity Received" Trigger in composer and defined a **custom activity type** in the **"Activity Type"** field. Now in the web-chat interceptor code, I am checking differences between the last timestamp when the user sent a message and the current timestamp(when the user replies after a while) if it exceeds a value, the js code will send a custom activity of the type that I defined in composer earlier, using the fetch API(with post method) and the URL `https://directline.botframework.com/v3/directline/conversations/${conversationId}/activities`. This works but this ruins the web-chat UI and also the flow defined in composer for the conversation.

**Comment by MrHYDRA-6469** [comment]
@SanKumar0632 ,I need little help.
So you are ending or expiring conversation on posting this endpoint -https://directline.botframework.com/v3/directline/conversations/${conversationId}/activities
