### ISSUE TITLE
error @microsoft/bf-orchestrator@4.14.0-rc0: The CPU architecture "arm64" is incompatible with this module.

### ISSUE THREAD

**Issue by AhmedNaguib20** [microsoft/BotFramework-Composer#9623]
try to install botFramework-composer locally and I get this error 
error @microsoft/bf-orchestrator@4.14.0-rc0: The CPU architecture "arm64" is incompatible with this module.
on Apple M1 Pro (macOS ventura version 13.4.1)

**Comment by ramfattah** [comment]
Thanks @AhmedNaguib20, I'm looking into this.

**Comment by tracyboehrer** [comment]
Orchestratator relies on native C/C++ libraries, and we don’t support M1 or M2.  We don't have plans to explicitly support them going forward.
