### ISSUE TITLE
"InputDialog is missing Prompt" appears when inserting the code from OAuth authentication

### ISSUE THREAD

**Issue by cpendery** [microsoft/BotFramework-Composer#9624]
## Describe the bug

When trying to use the OAuth Card to a bot deployed in Azure, I'm getting the error `InputDialog is missing Prompt.`. Seems similar to https://github.com/microsoft/BotFramework-Composer/issues/8258. The bot works fine when connecting via a deployed version of the [BotFramework-WebChat](https://github.com/microsoft/BotFramework-WebChat). We are using the `AAD v2 with Certificates (Preview)` Service Provider for the OAuth

## Version
Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge
- [x] Bot Emulator

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce
1. Create a bot using the `Blank` bot template
2. Add an OAuth Card that uses an `AAD v2 with Certificates (Preview)` Service Provider
3. Deploy to Azure App Service
4. Connect to the Bot via Bot Emulator
5. Login to the bot & paste the code in the chat
6. View the error message that occurs

## Expected behavior

Login should actually work

**Comment by ramfattah** [comment]
Thanks for your patience @cpendery, we are investigating.

**Comment by ramfattah** [comment]
Hi @cpendery, thank you for your patience.

1. Is this issue channel specific? Example, does this issue only occur in Emulator? 
2. In Azure Bot portal, does the "Test Connection" work as expected?
    ![image](https://github.com/microsoft/BotFramework-Composer/assets/38049078/0c53c581-2f3c-4dc2-8795-49c7c658efc5)

**Comment by cpendery** [comment]
Hi @ramfattah the issue actually resolved for some reason. Just for future reference test connection did work as expected, but it wasn't channel specific.
