### ISSUE TITLE
{"name":"CREATE_APP_REGISTRATION","message":"App create failed! Please file an issue on Github.","stack":"Error\n at new CustomizeError (D:\\Apps\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:276418:25)\n at createCustomizeError (D:\\Apps\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:276423:10)\n at BotProjectProvision.createApp (D:\\Apps\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:277931:17)"}. See provision.botazure.log in your bot folder

### ISSUE THREAD

**Issue by Prabakaran2596** [microsoft/BotFramework-Composer#9630]
## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
@Prabakaran2596 

Please answer the following:

- What version of Composer are you running?
- What OS is Composer running on?
- What version of the Bot Framework SDK is the bot running?
- Is it a dotnet or node runtime bot?
- Is the user that is logged in and publishing a guest of the tenant being used, or is it the users home directory?
