### ISSUE TITLE
Ignore is not considered a function in triggers

### ISSUE THREAD

**Issue by chrimc62** [microsoft/BotFramework-Composer#964]
## Describe the bug
Conditions for triggers include a custom function 'ignore(bool)'.  The expression validation code is not aware of that function and so composer reports it as an error.  (Although it runs fine.)  

## To Reproduce
1. Open the sandwich bot
2. Click on OrderSandwich then OnDialogEvent
3. The constrain is shown as invalid

## Expected behavior
The expression should not be invalid and the expression editor should support the ignore function as well for intellisense.

## Screenshots
![image](https://user-images.githubusercontent.com/17637681/65800891-8bb1b280-e12c-11e9-90b2-192dc77d05ab.png)

## Additional context
The ignore is necessary to mark parts of the condition that are unique to that trigger.  Without this function in some cases all triggers are unique and we cannot get the specialization behavior we want since every trigger would be considered unique.  In this case, the mechanism used for keeping rules from continually firing has this issue and that is why it is wrapped in an ignore function.
[bug]

**Comment by cwhitten** [comment]
Closing as this is a core-lib issue (expressions). @vishwacsena is tracking
