### ISSUE TITLE
Basic install won't run Empty Bot

### ISSUE THREAD

**Issue by jb-dev1** [microsoft/BotFramework-Composer#9642]
## Describe the bug

Install to Windows 10 22H2 device using default options with firewall allowed on private and public networks. Bot Framework Composer won't run any bots, and it won't even run the most basic, unmodified Empty Bot. I get an error starting the bot. The error message is "Local bot runtime manager, Status failed". When I click See details I am directed to Output which is blank.  Please note that an older version of 2.0.0 successfully runs on my other Windows 10 machine. 

## Version

2.1.2

## OS
- [X] Windows

## To Reproduce

1. Install version 2.1.2
2. Create new bot, Runtime type Azure Web App
3. Select empty bot
4. Without modifications, run the bot

## Expected behavior

Bot should run

**Comment by dmvtech** [comment]
@jb-dev1 

Please get additional logging information while reproducing the issue. Here are the steps:

- Go to Composer's install location (mine is at C:\Users\{username}\AppData\Local\Programs\Bot Framework Composer)
- Open a terminal here
- run `set DEBUG=composer*`
- run the executable from the terminal Ex. "Bot Framework Composer.exe"

After reproducing the issue, send the output contents of the terminal.

**Comment by dmvtech** [comment]
Closing due to lack of response.
