### ISSUE TITLE
Bot.Builder.Community.Components.CallDialogs Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by surlicki** [microsoft/BotFramework-Composer#9645]
I'm facing problem when trying to use CallDialogs which was installed as package of Bot.Builder.Community.Components. When I'm adding Dialogs to action "Add a dialog to call" and all necessary features as described in instruction, I always facing the "Object reference not set to an instance of an object." Can you suggest the solution for this issue?

## Version

2.1.2

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to Package manager.
2. Install "Bot.Builder.Community.Components.CallDialogs"
3. Add a dialog with name "DialogToCall".
4. Inside Begin new dialog add Send response.
5. Inside mother dialog press +, go to Dialog management and Add a dialog to call.
6. In Dialogs property add property
7. In Dialog name add created dialog name "DialogToCall"
8. Run the flow

## Expected behavior

Dialogs should be added to property as array of dialogs.

## Screenshots

![Issue](https://github.com/microsoft/BotFramework-Composer/assets/136600734/3083d40c-cf9c-4879-802c-b5b4b7695ab4)

**Comment by rvinothrajendran** [comment]
Please rebuild the project in VisualStudio and then check the exact issue. After that, share the exact issue details

**Comment by surlicki** [comment]
Project was multiple time rebuild in VS. Still the same issue.
![Capture](https://github.com/microsoft/BotFramework-Composer/assets/136600734/72703877-644e-488d-a166-b78fbf6e1b6a)

**Comment by dmvtech** [comment]
Please open an issue in the correct repository:
https://github.com/botbuildercommunity/botbuilder-community-dotnet
