### ISSUE TITLE
Unable to Create Bots

### ISSUE THREAD

**Issue by 12Vaibhav2** [microsoft/BotFramework-Composer#9647]
The below is the error being shown

If this problem persists, please file an issue on [GitHub](https://github.com/microsoft/BotFramework-Composer/issues)
Details
Error hit when instantiating remote template: Cannot find module '../../index' Require stack: - C:\Users\varmava\AppData\Roaming\BotFrameworkComposer\.yo-repository\node_modules\@microsoft\generator-bot-empty\node_modules\@microsoft\generator-bot-adaptive\generators\app\index.js - C:\Users\varmava\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\node_modules\@bfc\server-workers\node_modules\yeoman-environment\lib\store.js - C:\Users\varmava\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\node_modules\@bfc\server-workers\node_modules\yeoman-environment\lib\environment.js - C:\Users\varmava\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\node_modules\@bfc\server-workers\lib\workers\templateInstallation.worker.js

**Comment by dmvtech** [comment]
Please share the version info from Composer's `Help->About` menu
