### ISSUE TITLE
unable to install openai packages

### ISSUE THREAD

**Issue by volkanbt06** [microsoft/BotFramework-Composer#9650]
Hello,

I can't install any Openai package from the packages manager. I'm on bot composer v2.1.2. I'm getting the following error:

Command failed: dotnet add testLuisBot.csproj package "AzureAI.Community.OpenAI.Bot.Builder.Prompt" --version="1.0.7" --source="https://api.nuget.org/v3/index.json"

**Comment by stevkan** [comment]
@volkanbt06 - I was able to repro this issue. Looking at the [Nuget package](https://www.nuget.org/packages/AzureAI.Community.OpenAI.Bot.Builder.Prompt/1.0.7) online, I see that it is built using .NET 7.  To make this package work in Composer (or more specifically, in the bot), you will need to

- [Install](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) the .NET 7 SDK (and any dependencies)
- Update the [YOUR-BOT].csproj file to use the .NET 7 runtime by changing the target framework to "net7.0". The code should look like this:
```c#
<PropertyGroup>
    [ ... ]
    <TargetFramework>net7.0</TargetFramework>
    [ ... ]
</PropertyGroup>
```
At this point, the Nuget package should install. I, and a coworker, were both able to successfully install the package via the Composer package manager after the above changes were made.

If the steps above don't immediately resolve the problem, you can try initially running `dotnet build` in the .csproj directory to build the project.

As this should resolve your issue, I am going to close this as resolved. If the issue persists, please feel free to reopen this.
