### ISSUE TITLE
Don't auto capitalize boolean properties

### ISSUE THREAD

**Issue by Nicolaasjvv** [microsoft/BotFramework-Composer#9652]
## Describe the bug

When a property is manually set to a lowercase boolean, the composer will automatically capitalise the value (so "true" becomes "True"). This causes issues when the property is used in POST Bodies, as uppercase boolean values are not valid JSON.

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

None. Using Bot framework emulator to test.

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Recreate the following dialog:
![image](https://github.com/microsoft/BotFramework-Composer/assets/14290628/753c1059-8bd1-46f9-a62d-2e688653aec2)
2. Test on emulator, see results below:
![image](https://github.com/microsoft/BotFramework-Composer/assets/14290628/79cc0dbd-231d-41d9-8c68-cb12be3fec75)

## Expected behavior

Properties set as lowercase Booleans should remain lowercase when recalled/used later in the flow. Or, Booleans should by default be lowercase.

## Screenshots

See reproducing steps above.

**Comment by ramfattah** [comment]
Thanks @Nicolaasjvv, we are looking into this.

**Comment by ramfattah** [comment]
Thanks @Nicolaasjvv, 

I'm able to reproduce this issue:
![image](https://github.com/microsoft/BotFramework-Composer/assets/38049078/c4a398d7-71a3-4437-8f32-5a6985dd874b)

**Comment by ramfattah** [comment]
Discussing internally with the engineering team.

**Comment by ramfattah** [comment]
hey @Nicolaasjvv, 

To address the JSON validity concern in POST bodies, here are two workarounds:
1. Bypass the boolean type and set directly as a string: 
    1. Example: `dialog.testResults = "true"`

2. Leverage Adaptive Expressions' `string()` function: 
    1. Example: `${string(dialog.testResults)}`
    2. This will convert the boolean value to its string representation, either "true" or "false".
    3. Here is [documentation](https://learn.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#string) for Adaptive Expression pre-built string() function
    4. Screenshot: 
         ![image](https://github.com/microsoft/BotFramework-Composer/assets/38049078/77fc1d38-d887-4f02-bf8b-024b52cc8b10)

**Comment by ramfattah** [comment]
Closing with workaround.
