### ISSUE TITLE
Error while publishing a bot

### ISSUE THREAD

**Issue by ProsenjitPa** [microsoft/BotFramework-Composer#9655]
Getting the following error while publishing a bot

{"name":"CREATE_APP_REGISTRATION","message":"App create failed! Please file an issue on Github.","stack":"Error\n at new CustomizeError (E:\\Softwares\\BotComposer\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:276418:25)\n at createCustomizeError (E:\\Softwares\\BotComposer\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:276423:10)\n at BotProjectProvision.createApp (E:\\Softwares\\BotComposer\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:277931:17)"}. See provision.azurebotdeploy.log in your bot folder
```[tasklist]
### Tasks
```

**Comment by dmvtech** [comment]
@ProsenjitPa 

Please answer the following:

- What version of Composer are you running?
- What OS is Composer running on?
- What version of the Bot Framework SDK is the bot running?
- Is it a dotnet or node runtime bot?
- Is the user that is logged in and publishing a guest of the tenant being used, or is it the users home directory?

**Comment by dmvtech** [comment]
Closing due to lack of response.
