### ISSUE TITLE
Error Creating App Service

### ISSUE THREAD

**Issue by WasanthaK** [microsoft/BotFramework-Composer#9658]
{
  "profileName": "Evo",
  "jobId": "3a7acda1-7d40-4090-864c-4b8982cef1af",
  "projectId": "15055.727788750173",
  "time": "2023-10-07T04:52:59.901Z",
  "log": [
    "Creating Azure resources...",
    "Checking the Existence of the Resource Group ...",
    "Creating Resource Group ...",
    "> Creating App Registration ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed, retrying ...",
    "App create failed after 3 retries. Error: Request failed with status code 401",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276418:25)\\n    at createCustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276423:10)\\n    at BotProjectProvision.createApp (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:277931:17)\"}",
    "{\"name\":\"CREATE_APP_REGISTRATION\",\"message\":\"App create failed! Please file an issue on Github.\",\"stack\":\"Error\\n    at new CustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276418:25)\\n    at createCustomizeError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276423:10)\\n    at BotProjectProvision.createApp (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:277931:17)\"}. See provision.Evo.log in your bot folder"
  ]
}

**Comment by ramfattah** [comment]
Thanks @WasanthaK 

* Which version of Composer are you using?
* Is this a C# .NET or Node.js Composer bot?

**Comment by dmvtech** [comment]
Closing due to lack of response.
