### ISSUE TITLE
[Hackathon] "Prompt with multi-choice"'s options show up as empty boxes in suggested actions

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Composer#966]
## Version
Build SHA 6a74f46

## Describe the bug
[not a consistent repro]

## To Reproduce
1. Add a prompt with multi-choice in a dialog
2. Set the "List Style" to SuggestedAction
3. Add a choice
4. Run the bot
5. The suggested action shows up properly
6. Delete the option and add a new one
7. re-run the bot
8. suggested action is now empty and there is no way to get it back working

## Expected behavior
Text should always show up

## Screenshots
![image](https://user-images.githubusercontent.com/17152540/65801169-4cd02c80-e12d-11e9-805f-339b551d2ca3.png)

![image](https://user-images.githubusercontent.com/17152540/65801194-59ed1b80-e12d-11e9-8993-03464f7235b6.png)

[bug]

**Comment by vishwacsena** [comment]
Dropping SDK label. This to me looks to be a composer serialization issue. @cwhitten @a-b-r-o-w-n

**Comment by a-b-r-o-w-n** [comment]
@vishwacsena The sdk schema needs to include the card action schema so that Composer can render the appropriate UI.
