### ISSUE TITLE
Could not load component list:Error certificate has expired *** Could not merge components ***

### ISSUE THREAD

**Issue by AlexGrossi** [microsoft/BotFramework-Composer#9662]
I can't install Microsoft.Bot.Components.Recognizers.CLURecognizer. Every time I try to install it throws the error. I tried installing the latest nightlies with no success.

I am using Release 2.1.2, SDK runtime packages 4.12.0
I am using Chrome on Windows.

## To Reproduce

1. Go to the package manager
2. Search for Microsoft.Bot.Components.Recognizers.CLURecognizer
3. Try to install

## Expected behavior

The package to install

![image](https://github.com/microsoft/BotFramework-Composer/assets/148442215/7c576606-e043-43f2-9fa5-eb2244c4f6cc)

**Comment by Hwiet** [comment]
I have the same issue

**Comment by dmvtech** [comment]
Thank you for reporting this. This is a known issue and fixed in one of the nightly builds. The latest [v2.1.3-nightly.364675.1a93f21](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.1.3-nightly.364675.1a93f21) has this fix.

**Comment by dmvtech** [comment]
@AlexGrossi Can you please confirm whether the 2.1.3 nightly fixes the issue for you or not?

**Comment by buddhics** [comment]
> @AlexGrossi Can you please confirm whether the 2.1.3 nightly fixes the issue for you or not?

I have checked and it is working for me now.

**Comment by tecsancalb** [comment]
I'm having the same issue. Trying with 2.1.3.

**Comment by piniouf** [comment]
I also get this error when I open the Package Manager:

![image](https://github.com/microsoft/BotFramework-Composer/assets/51211314/a492ccad-d3f5-40c7-84d8-ea0da933557a)


Or when I cancel the error and try and install packages:

![image](https://github.com/microsoft/BotFramework-Composer/assets/51211314/7e462892-7c0d-4347-8094-14ddedb756bd)

I'm using 2.1.2 with Windows 11. I will update to 2.1.3 and report back...

**Comment by piniouf** [comment]
> Thank you for reporting this. This is a known issue and fixed in one of the nightly builds. The latest [v2.1.3-nightly.364675.1a93f21](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.1.3-nightly.364675.1a93f21) has this fix.

Update to this build fixed the issue for me.

**Comment by ViktorDronov** [comment]
same issue on a nightly build
![image](https://github.com/microsoft/BotFramework-Composer/assets/107995419/d4b774ef-927b-4f02-8b81-27985b5015be)

**Comment by jdavis-leasehawk** [comment]
I am a new user and just installed Bot Framework Composer and it self-updated to v2.1.2 and I'm also getting this error, just opening the Package Manager menu item.
![image](https://github.com/microsoft/BotFramework-Composer/assets/59490349/7af80348-7e9c-4f36-9b92-83053e7eaf8b)

Bad taste in my mouth already

**Comment by simonpain** [comment]
Still having this same issue today on current v2.1.2 meaning I can't easily complete the tutorial at https://learn.microsoft.com/en-us/composer/tutorial-create-weather-bot#add-interruptions-to-the-conversation-flow

**Comment by OEvgeny** [comment]
Please refer to #9745

**Comment by nevenamilenkovic02** [comment]
> Still having this same issue today on current v2.1.2 meaning I can't easily complete the tutorial at https://learn.microsoft.com/en-us/composer/tutorial-create-weather-bot#add-interruptions-to-the-conversation-flow

Same...

**Comment by dmvtech** [comment]
hi @nevenamilenkovic02 Any luck?

**Comment by dmvtech** [comment]
Closing due to lack of response. If you still need assistance, please comment with the requested information and we can continue.

**Comment by ViktorDronov** [comment]
> [@nevenamilenkovic02](https://github.com/nevenamilenkovic02) Can you please try the newest nightly version and let us know if that resolves the issue or not.

Could you provide any link?

**Comment by ViktorDronov** [comment]
@dmvtech https://github.com/microsoft/BotFramework-Composer-Nightlies/tags
There no new nightly builds
issue exist globally what reported here multiple times
