### ISSUE TITLE
Cannot create Bot on Azure Functions

### ISSUE THREAD

**Issue by BenjaminGraziadei223946** [microsoft/BotFramework-Composer#9663]
I want to create a Bot on Azure Functions, but i always get a Error Command failed: dotnet build Empty.csproj. However i installed the .net, installed the azure function thingy (func-cli-x64.msi) and also looked up my nuget: Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
and i believe this is right. I also tried creating it in the cmd with these commands:
npm install -g yo
npm install -g @microsoft/generator-bot-empty
yo @microsoft/bot-empty "EmptyBotTest"
cd EmptyBotTest
dotnet build

which works but i get warnings and then when trying to import the bot to the framework i get this message: Error Processing Schema
Cannot convert undefined or null to object.

However i dont get a error if i try making the bot without the function and using the web, but i dont want that.

## Version

Composer v2.1.2

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Actually nothing special just downloaded the app and all the things said before and the error occured the first time i tried creating a bot using the functions.

## Screenshots

![image](https://github.com/microsoft/BotFramework-Composer/assets/112875479/3dde0f52-f7c7-4751-b12a-43bd2d64d386)

**Comment by dmvtech** [comment]
> I also tried creating it in the cmd with these commands:
> npm install -g yo
> npm install -g @microsoft/generator-bot-empty
> yo @microsoft/bot-empty "EmptyBotTest"
> cd EmptyBotTest
> dotnet build

This is actually creating an Azure Web App bot, not an Azure Functions bot. You can verify by looking at the code and the `.csproj` file.

> which works but i get warnings and then when trying to import the bot to the framework i get this message: Error Processing Schema
> Cannot convert undefined or null to object.

Hmm. Not sure about that. I was able to run `yo` and then `dotnet build` and no issues here. Here is my output for `dotnet --info` in case you want to compare.

> I want to create a Bot on Azure Functions, but i always get a Error Command failed: dotnet build Empty.csproj

For the issue with creating an Azure Functions bot from within Composer, please try and installing the tools via npm. Can you please run `npm list -g --depth=0` and verify what (if any) packages you have installed for `azure-functions-core-tools`. The bot template uses v3, so you should at least have v3, but v4 should work as well.

If you have none, please install either v3 or v4 using the npm commands listed here:
https://www.npmjs.com/package/azure-functions-core-tools

Then re-launch Composer and try again.

**Comment by dmvtech** [comment]
Closing due to lack of response.
