### ISSUE TITLE
Bot Framework Composer server start is looping (unexpected end of JSON)

### ISSUE THREAD

**Issue by neis-lotte** [microsoft/BotFramework-Composer#9668]
## Describe the bug
You can see "`Server starting`" screen after that nothing happens. Opening the Bot Framework Composer with terminal only shows the `Syntaxerror : "UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input"`. 

## Version

- Bot Framework Composer `2.1.3-nightly.364675.1a93f21`
- node.js `14.17.3 LTS`
- npm `9.6.5`

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Download [Bot Framework Composer nightly build](https://teams.microsoft.com/l/message/19:7816e398-6fe4-4b02-b6a4-34a9ed357640_fb71605f-6e5b-4e78-b5e2-d41bc6715a60@unq.gbl.spaces/1699527393941?context=%7B%22contextType%22%3A%22chat%22%7D)
2. Start Bot Framework Composer

(there are no more information to reproduce)

## Expected behavior
Bot Framework Composer should show all Bots.

## Screenshots
![image](https://github.com/microsoft/BotFramework-Composer/assets/138685841/612919b8-7e35-49d6-8d6a-ee890945b8b8)

![image](https://github.com/microsoft/BotFramework-Composer/assets/138685841/8b252d6a-a961-4977-a85f-6304ff8e303d)

## Additional context

```Log
(node:11276) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at migrateStore (C:\ProgramData\Bot Framework Composer\resources\app.asar\node_modules\@bfc\server\build\store\store.js:17:31)
    at Object.<anonymous> (C:\ProgramData\Bot Framework Composer\resources\app.asar\node_modules\@bfc\server\build\store\store.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:1130:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:987:32)
    at Module._load (internal/modules/cjs/loader.js:828:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1011:19)
    at require (internal/modules/cjs/helpers.js:88:18)
(Use `Bot Framework Composer --trace-warnings ...` to show where the warning was created)
(node:11276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[16124:1109/113309.015:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
```

**Comment by dmvtech** [comment]
@neis-lotte Is this still happening for you? I am not able to reproduce the issue.

**Comment by OEvgeny** [comment]
@neis-lotte try uninstalling both, "Bot Framework Composer" and "Bot Framework Composer Test", then install the fresh Nightly from [here](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases) and see if it helps.

The default location for the nightly is `C:\Users\%USER%\AppData\Local\Programs\Bot Framework Composer Test` and from the screenshots provided it seems you're running regular composer build.

**Comment by OEvgeny** [comment]
@neis-lotte try moving the file located in `C:\Users\%USER%\AppData\Roaming\BotFrameworkComposer\data.json` where `%USER%` is your windows computer username, somewhere else and see if it fixes the issue.

Looks like the file got corrupted which prevents Composer from start

**Comment by neis-lotte** [comment]
So my Pc got a shotdown while running the program, after that it did not work. Now after resetting my PC everything works fine. But Thank You, Next Time I'll try.
