### ISSUE TITLE
Could not merge components  Bot Framework Composer.

### ISSUE THREAD

**Issue by kcabral817** [microsoft/BotFramework-Composer#9674]
Why should I spend time searching for a problem?  If the problem is already identified, it should be already fixed.  
Package Manager Erro...
If this problem persists, please file an issue on [GitHub](https://github.com/microsoft/BotFramework-Composer/issues)
Details
Could not load component list:Error certificate has expired *** Could not merge components ***

## Describe the bug
Package Manager Erro...
If this problem persists, please file an issue on [GitHub](https://github.com/microsoft/BotFramework-Composer/issues)
Details
Could not load component list:Error certificate has expired *** Could not merge components ***

The clear and concise description is provided by the error.  If that is not enough, call your boss.  

## Version

2.1.2

## Browser

Edge

## OS

- [ ] Windows 

## To Reproduce

Open bot framework composer
on the left side of your screen, select the package manager
Viola!!!!!! error.

## Expected behavior

I have misplaced expectations that MS software will work.  On the outside chance it does, I do not expect an error describing an expired certificate.  

## Additional context

The context is the poor testing, poor documentation, the poor updates to the website, and just a general poor experience dealing with anything remotely related to Azure, MS.  The only reason why Sql server is still around is that it was originally purchased from sybase.  Other than that, EVERY SINGLE SOFTWARE solutions turns to a dumpster fire.  If you can create any more rabbit holes in your documentation, it would take a team of experts and a 1st year project manager to pull off.  Nothing is straight forward.  Between the deprecated, but still referenced, documentation and software, the continued bugs, and wholesale rewrites that occur, its surprising that MS is still in business.  But alias, I give it time.  See you in annuals of history.

**Comment by YuZeSun0203** [comment]
I am experiencing the same issue these days

**Comment by tracyboehrer** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/9665
