### ISSUE TITLE
Adaptive Card Tables - Bot Composer

### ISSUE THREAD

**Issue by LarryLeonidas** [microsoft/BotFramework-Composer#9680]
## Describe the bug
It would seem Composer 2.1.2 is unable to render Tables. Screenshot below.

Please confirm

![image](https://github.com/microsoft/BotFramework-Composer/assets/3912134/b60102b0-4c0c-4c29-98d7-26a779dd1fba)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by RupenAnjaria** [comment]
Yes, I am experiencing the same.

**Comment by dmvtech** [comment]
Composer uses webchat as a base for the chat client. This is a known issue and can be monitored here:
https://github.com/microsoft/BotFramework-WebChat/issues/4626
