### ISSUE TITLE
Bot Framework Composer - Azure Blob SAS Link Accessibility

### ISSUE THREAD

**Issue by Mohanraj27v** [microsoft/BotFramework-Composer#9681]
## Browser

- [ ] Chrome
- [ ] Edge

## OS

- [ ] Windows

## Additional context

I am using Bot Composer to process the user input in my azure function and receive the link as an response. when I test my function app in the local vs code, I could able to download the file link which was obtained from the blob account[pubic]. 

**Bot composer version** - 2.1.2
**Nodejs version** - 20.9.0
**dotnet version** - 3.1.426

But when I receive it in my composer and tried to dowload the file, I got the below authentication request error. I am not sure why it is poping up. 

**This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:f7a5bc0c-c01e-002c-27cc-34a105000000 Time:2023-12-22T11:43:51.3776591Z</Message>
<AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail>
</Error>**

It seems like, when the bot composer tried to invoke the url, the request authentication is failed from the bot composer.

**Comment by rampaged** [comment]
Hi @Mohanraj27v,

Are you able to provide the steps to reproduce this issue?

**Comment by Mohanraj27v** [comment]
@rampaged , the issue got resolved. the problem was while parsing the request url, the composer tends to parse the text content along with the link, so that eventually the link was not working.
