### ISSUE TITLE
Composer Deployments Failing Consistently

### ISSUE THREAD

**Issue by LarryLeonidas** [microsoft/BotFramework-Composer#9682]
## Describe the bug
Attempting to deploy a generic bot to our Azure environment with Composer. We created the Publish Profile and created Azure Resources directly from within Composer. Azure Resources are created successfully. When attempting to deploy we receive the error below. I've tried this several times, with various resource options (i.e. including and omitting LUIS).

## Version
v2.1.2

## Browser

- [ x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x ] Windows
- [ ] Ubuntu

## Screenshots
![image](https://github.com/microsoft/BotFramework-Composer/assets/3912134/66c379ca-9e90-4a33-b156-4bb48237f841)

**Comment by rampaged** [comment]
Hi @LarryLeonidas, thanks for your patience.

1) What version of Composer are you using?
2) Is this a C# (dotnet) or JS (Node.js) Composer bot?

**Comment by LarryLeonidas** [comment]
> Hi @LarryLeonidas, thanks for your patience.
> 
> 1. Have you had a chance to deploy using the [latest Composer nightly version ](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases) instead of 2.1.2 to see if it addresses this issue?
> 2. Is this a C# (dotnet) or JS (Node.js) Composer bot?

Sorry for the delay here, missed the notification from rampaged's response. This was for a NodeJS bot. 

However, we've moved away from using Composer for deployments/publishing and using ARM/CLI etc. We'll look for an updated version of Composer. Hope it gets better, we're looking forward to it!
