### ISSUE TITLE
Bot Framework Composer Package Manager Error

### ISSUE THREAD

**Issue by AbhishekRavi95** [microsoft/BotFramework-Composer#9686]
Facing these issues whenever I open the Bot framework composer:
a) A problem occurred during the install of this Component: Error Request failed with status code 403 *** Could not merge components ***
b) Bot framework not getting connected to Github for downloading packages
c) Couldn't complete the update: Error: Cannot download "https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/dowload/v2.1.3-nightly-364675.1a93f21/electron.exe" status 404:

**Comment by rampaged** [comment]
Using Composer v2.1.3 nightly solved the issue from my end.

Could you please try to use the latest Composer nightly version to see if that address this issue? 

1) Uninstall your current Composer 
2) Install the latest version of **Composer nightly** for your OS here:
https://github.com/microsoft/BotFramework-Composer-Nightlies/releases

Let me know if you have any questions.
Thanks.

**Comment by tracyboehrer** [comment]
https://github.com/microsoft/BotFramework-Composer/issues/9665
