### ISSUE TITLE
[Hackathon] Control is not returned to main dialog after sub-intent is handled

### ISSUE THREAD

**Issue by p-nagpal** [microsoft/BotFramework-Composer#969]
[WeatherBotRepro.zip](https://github.com/microsoft/BotFramework-Composer/files/3664513/WeatherBotRepro.zip)
## Version
4.5.2

## Describe the bug
See attached Weather bot sample for a repro. The bot gets location and date from the user to lookup weather. The main dialog hands off the handleWeatherAnswer intent to extract the location and date from the users answer. I expect that the control will return to the main flow once the handleWeatherAnswer finishes execution but what I see is that the control doesn't return to main dialog . All the steps in the Main Dialog after receiving the user's answer for weather are not executed. 

## To Reproduce
1. Open the weather bot in Composer and start the bot project
2. Start the bot in emulator and ask "Weather in Seattle today"
3. Note that the bot doesn't handle missing location or time. 
4. Notice that the bot repeats the question and will return a default JSON response for weather
5. I also expect that the bot returns to the main flow and sends the text "Looking up weather information" and a second HTTP call to weather API.

## Expected behavior
Control returns to the main flow once the sub-intent has been handled.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
Cannot repro this with the latest bits. @p-nagpal can you try again and re-activate if you continue to see this issue?
