### ISSUE TITLE
Can't publish my bot from bot framework composer

### ISSUE THREAD

**Issue by OsamaAbdelhameed** [microsoft/BotFramework-Composer#9693]
## Describe the bug

in my bot framework composer while I was trying to publish my bot, I got "Your subscription list is empty, please add your subscription, or login with another account." 
I still have a free subscription running in my azure portal

## Screenshots

![Screenshot (1049)](https://github.com/microsoft/BotFramework-Composer/assets/57057405/62bf0a66-9822-4812-8a67-6de3a2e80a18)

**Comment by rampaged** [comment]
Have you tried to logout and sign in again to see if that addresses this issue? 

Also try clearing Composer cache/data/cookies to see if that helps.


<img width="1148" alt="Screenshot 2024-02-01 at 8 11 00 PM" src="https://github.com/microsoft/BotFramework-Composer/assets/38049078/30c1ce5c-6465-4e8f-92bb-92ee6206488f">


<img width="875" alt="Screenshot 2024-02-01 at 8 11 24 PM" src="https://github.com/microsoft/BotFramework-Composer/assets/38049078/babd4b55-1e1d-429d-822b-1fb9b1303a36">


<img width="816" alt="Screenshot 2024-02-01 at 8 12 29 PM" src="https://github.com/microsoft/BotFramework-Composer/assets/38049078/f5618864-afda-42f7-8efa-64fdb71a1c22">

**Comment by dmvtech** [comment]
Closing due to lack of response.
