### ISSUE TITLE
Provision Failure in publishing by creating a new resource as well as using the existing resource

### ISSUE THREAD

**Issue by Tz611** [microsoft/BotFramework-Composer#9697]
## There is a **Provision failure** in publishing my bot to Azure bot service. The error occurs in both using the existing resource and creating a new resource. 

![image](https://github.com/microsoft/BotFramework-Composer/assets/159101530/215a5d35-b754-4c99-8916-dc7647eebadd)

The error message is as follows:
Provision failure
{"name":"CREATE_APP_REGISTRATION","message":"App create failed! Please file an issue on Github.","stack":"Error\n at new CustomizeError (D:\\Workspace (SAYA)\\ChatBot\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:276418:25)\n at createCustomizeError (D:\\Workspace (SAYA)\\ChatBot\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:276423:10)\n at BotProjectProvision.createApp (D:\\Workspace (SAYA)\\ChatBot\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions\\azurePublish\\dist\\extension.js:277931:17)"}. See provision.Saya_Bot.log in your bot folder

P.S. I have also tested the solutions provided in the case #8283 , like assigning application administrator and application developer. Besides, I have also use the contributor role in subscription resource.

Thus, could you please help me with the detailed step-by-step methods to solve this error?

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [Yes ] Chrome
- [ ] Safari
- [Yes] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [Yes ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Publish >> Add New >> Create publishing profile by existing one as well as creating a new one'
2. Click on 'Next'
See Error

## Expected behavior

Provision Success and Publishing Success

## Screenshots

![image](https://github.com/microsoft/BotFramework-Composer/assets/159101530/b63410db-9026-4696-8b2f-899524753766)

![image](https://github.com/microsoft/BotFramework-Composer/assets/159101530/89ef4d71-0214-4f49-813e-333e832efb2c)

![image](https://github.com/microsoft/BotFramework-Composer/assets/159101530/08b9c5cc-6405-4461-b710-b16d3331e5f3)

**Comment by OEvgeny** [comment]
@Tz611 could you provide the `provision.Saya_Bot.log` as well?

**Comment by Tz611** [comment]
@OEvgeny This is the log file of the provision.
![image](https://github.com/microsoft/BotFramework-Composer/assets/159101530/df723969-506d-4700-876f-b3635ebb8eaf)

I think there is an error in provision, that's why I could not publish the bot in other ways also.

**Comment by dmvtech** [comment]
@Tz611 

> assigning application administrator and application developer. Besides, I have also use the contributor role in subscription resource.

Is the account in question part of the _home tenant_, or is it a _guest_? (regardless of permissions)

**Comment by Tz611** [comment]
@dmvtech, It is a tenant account.
Besides, the error code is 401 
![image](https://github.com/microsoft/BotFramework-Composer/assets/159101530/6bd0a628-1c64-473a-ba7b-7102492260c7)

This is the error log from provision file.

**Comment by OEvgeny** [comment]
Closing due inactivity, feel free to reopen

**Comment by AakashNakarmi** [comment]
If someone have encountered same issue and have reached this point.
Do check these following things to fix this error:

1. Check if Botservice resource is registered. Go to Subscriptions> Your Subscription > Resource provider > Microsoft.Botservice . If not registered, register it.

![Image](https://github.com/user-attachments/assets/82ebdea7-9af5-4f2f-ab0a-7dea06a721d9)

2. Check if the user account have sufficient permissions to create the app. Go to Microsoft Entra ID > Users > Select User > Assigned Roles. If you have not access, create a user and assign roles as application administrator and application developer.

![Image](https://github.com/user-attachments/assets/e80f2593-37d4-4b46-8dd6-5a7b82ef1ffb)
