### ISSUE TITLE
Typing indicator doesn't work for old Teams

### ISSUE THREAD

**Issue by a1exwang** [microsoft/BotFramework-Composer#9700]
## Browser

- [ ] Electron distribution
- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create an simple bot from teams toolkit

2. Add following code

```js
class TeamsBot extends TeamsActivityHandler {
  constructor() {
    super();

    this.onMessage(async (context, next) => {
      console.log("Running with Message Activity.");
      for (let i = 0; i < 10; i++) {
        await context.sendActivity({type: "typing"})
      }
      await context.sendActivity("Echo: " + context.activity.text); 
      await next();
    });
  }
}
```

3. Sideloading in old Teams web client

4. Send "hello" to bot

5. After a while, I received `Echo: hello` from bot but no typing indicator.

## Expected behavior

I can see typing indicator. A few days ago, it works in old Teams.

May relate to https://github.com/microsoft/BotFramework-Composer/issues/9679

**Comment by stevkan** [comment]
@a1exwang - Thank you for your patience. There are a couple things to note, here.

1. Due to a Teams outage last week, the typing indicator was disabled for both classic as well as the new Teams apps. The typing indicator is slowly being reenabled across different groups and regions. I do not have a specific ETA on when it will be reenabled for you.

2. With regards to your code posted above, you wouldn't see the typing indicator in this scenario, anyhow. The reason being the following activity (i.e., the 'echo' response) is running too soon for the typing indicator to show. In other words, there is no reason for the typing indicator to show because there is no delay experienced that would necessitate the typing indicator to show.

To demonstrate this, I will send only the typing activity, like below, using Web Chat as the client. You will see the typing indicator display for the default five seconds.

```js
this.onMessage(async (context, next) => {
      console.log("Running with Message Activity.");
      await context.sendActivity({type: "typing"})
      await next();
    });
```

![disableOAuthPromptACButton](https://github.com/microsoft/BotFramework-Composer/assets/18403946/4294f7cf-e151-4114-9d7f-84484ce354a6)

To that end, while you can use the 'typing' activity, the preferred method for implementing the typing indicator is to use the 'ShowTypingMiddleware' middleware, like below, in the index.js. This middleware has internal logic that allows you to control the delay (how long it waits before sending the indicator) and period (how long it sends the indicator for):

```js
const adapter = new CloudAdapter(botFrameworkAuthentication);

[ ... ]

adapter.use(new ShowTypingMiddleware(500, 1000));
```

The code you posted, in some scenarios, can actually cause the bot to produce an error.

**Comment by a1exwang** [comment]
> @a1exwang - Thank you for your patience. There are a couple things to note, here.
> 
> 1. Due to a Teams outage last week, the typing indicator was disabled for both classic as well as the new Teams apps. The typing indicator is slowly being reenabled across different groups and regions. I do not have a specific ETA on when it will be reenabled for you.
> 2. With regards to your code posted above, you wouldn't see the typing indicator in this scenario, anyhow. The reason being the following activity (i.e., the 'echo' response) is running too soon for the typing indicator to show. In other words, there is no reason for the typing indicator to show because there is no delay experienced that would necessitate the typing indicator to show.
> 
> To demonstrate this, I will send only the typing activity, like below, using Web Chat as the client. You will see the typing indicator display for the default five seconds.
> 
> ```js
> this.onMessage(async (context, next) => {
>       console.log("Running with Message Activity.");
>       await context.sendActivity({type: "typing"})
>       await next();
>     });
> ```
> 
> ![disableOAuthPromptACButton](https://private-user-images.githubusercontent.com/18403946/304597681-4294f7cf-e151-4114-9d7f-84484ce354a6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDg0OTIsIm5iZiI6MTcwODQwODE5MiwicGF0aCI6Ii8xODQwMzk0Ni8zMDQ1OTc2ODEtNDI5NGY3Y2YtZTE1MS00MTE0LTlkN2YtODQ0ODRjZTM1NGE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA1NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNjdlOWJmMDk0NTgyM2IwZjAwMWE3MWRlNTIyNjhiYWViNmJlZmIzODQxMzI0NGZjZmI5MDJlZmMzMzlmZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EtAPh8c_etzMNtuDcddzS1Rijc9Pri-AQQQGxtV1F4U) [ ![disableOAuthPromptACButton](https://private-user-images.githubusercontent.com/18403946/304597681-4294f7cf-e151-4114-9d7f-84484ce354a6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDg0OTIsIm5iZiI6MTcwODQwODE5MiwicGF0aCI6Ii8xODQwMzk0Ni8zMDQ1OTc2ODEtNDI5NGY3Y2YtZTE1MS00MTE0LTlkN2YtODQ0ODRjZTM1NGE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA1NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNjdlOWJmMDk0NTgyM2IwZjAwMWE3MWRlNTIyNjhiYWViNmJlZmIzODQxMzI0NGZjZmI5MDJlZmMzMzlmZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EtAPh8c_etzMNtuDcddzS1Rijc9Pri-AQQQGxtV1F4U) ](https://private-user-images.githubusercontent.com/18403946/304597681-4294f7cf-e151-4114-9d7f-84484ce354a6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDg0OTIsIm5iZiI6MTcwODQwODE5MiwicGF0aCI6Ii8xODQwMzk0Ni8zMDQ1OTc2ODEtNDI5NGY3Y2YtZTE1MS00MTE0LTlkN2YtODQ0ODRjZTM1NGE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA1NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNjdlOWJmMDk0NTgyM2IwZjAwMWE3MWRlNTIyNjhiYWViNmJlZmIzODQxMzI0NGZjZmI5MDJlZmMzMzlmZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EtAPh8c_etzMNtuDcddzS1Rijc9Pri-AQQQGxtV1F4U) [ ](https://private-user-images.githubusercontent.com/18403946/304597681-4294f7cf-e151-4114-9d7f-84484ce354a6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDg0OTIsIm5iZiI6MTcwODQwODE5MiwicGF0aCI6Ii8xODQwMzk0Ni8zMDQ1OTc2ODEtNDI5NGY3Y2YtZTE1MS00MTE0LTlkN2YtODQ0ODRjZTM1NGE2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA1NDk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNjdlOWJmMDk0NTgyM2IwZjAwMWE3MWRlNTIyNjhiYWViNmJlZmIzODQxMzI0NGZjZmI5MDJlZmMzMzlmZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EtAPh8c_etzMNtuDcddzS1Rijc9Pri-AQQQGxtV1F4U)
> 
> To that end, while you can use the 'typing' activity, the preferred method for implementing the typing indicator is to use the 'ShowTypingMiddleware' middleware, like below, in the index.js. This middleware has internal logic that allows you to control the delay (how long it waits before sending the indicator) and period (how long it sends the indicator for):
> 
> ```js
> const adapter = new CloudAdapter(botFrameworkAuthentication);
> 
> [ ... ]
> 
> adapter.use(new ShowTypingMiddleware(500, 1000));
> ```
> 
> The code you posted, in some scenarios, can actually cause the bot to produce an error.

@stevkan Thanks for the clarification.

1. Tried your code 
   ```
   this.onMessage(async (context, next) => {
      console.log("Running with Message Activity.");
      await context.sendActivity({type: "typing"})
      await next();
    });
   ```
    It seems the typing indicator feature still hasn't enabled for my testing org.

2. Thanks for let me know `ShowTypingMiddleware` is the recommended way. I will let our customers know.

**Comment by atmoraes1** [comment]
The decision to disable the typing indicator for Teams is outrageous.

We use that to provide a smooth user experience and now a lot of customers are complaining.

It should be reenabled again ASAP.

**Comment by ill-yes** [comment]
Same here. Any updates so far?

**Comment by atmoraes1** [comment]
Coming back here to say when using the ShowTypingMiddleware we are receiving BadRequests all the time, we had to change our code to stop using it. Again, that is unacceptable.

**Comment by AdiOLI** [comment]
Are there any updates on plans to enable the typing indicator since it was disabled 3 months ago?

**Comment by stevkan** [comment]
Closing as the issue has been resolved as of release of Microsoft Teams, version 24033.813.2773.520.
