### ISSUE TITLE
Internal server error 500 when accessing from WebChat and other integrated channels

### ISSUE THREAD

**Issue by Tz611** [microsoft/BotFramework-Composer#9703]
I have built the bot from node template in bot framework composer and then published to the resource that was newly created, in Azure Portal. However, when I access the bot via webchat and integrated telegram channel, there is internal server error 500 whenever I send message to the bot in the Azure bot service. The screenshot of the error is attached below.
![image](https://github.com/microsoft/BotFramework-Composer/assets/159101530/9b43427f-0792-4862-8f71-2be39efb8f30)

## Version
Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [yes ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [yes ] Windows
- [ ] Ubuntu

## To Reproduce

1. Go to 'Azure Portal then click the Resource where the bot is registered, and then click the bot, then click on "Test in Webchat"'
2. Send a trigger message and No response from the bot
4. when I see the logs in the webchat channel, the above included screenshot of errors occur.

## Expected behavior

Since I have created the flow and triggers in the bot with Bot Framework Composer, there should be return message from the bot whenever I send a trigger message.

## Screenshots

![image](https://github.com/microsoft/BotFramework-Composer/assets/159101530/d326c9d9-ef1d-4569-9c93-afee61b2c502)

![image](https://github.com/microsoft/BotFramework-Composer/assets/159101530/d208ed2b-96d1-46b0-961f-6e2b0c68e33d)

## Additional context

When I tested with the bot from Csharp template, there is no error like this and the testing in the Webchat as well as from integrated telegram went smoothly.
This error is occurring in the bot created from the node template. Thus, is the error relating to the node modules?
I already checked my firewall from my device and the bot framework composer is also allowed.

How can I solve that internal server error 500?

**Comment by OEvgeny** [comment]
@Tz611 does the bot work locally? If it doesn't this may be the cause. Did you publish straight from the template without any changes?

**Comment by amangit007** [comment]
internal server error means you bot app is crashing so I am assuming your bot code is running on Azure web app then you must go to advance tools=> kudu=>check default docker logs there you might find the actual reason of app crashing.
