### ISSUE TITLE
Issue with accessing the adaptive cards in PVA that has used bot framework composer for adaptive cards

### ISSUE THREAD

**Issue by Rekhanjalir** [microsoft/BotFramework-Composer#9704]
I am using a chatbot that has an issue with the adaptive cards in which adaptive cards are visible in the PVA test bot feature but the same is not visible in the teams channel.

**Comment by OEvgeny** [comment]
@Rekhanjalir are you setting up the channel using PVA experience? Seems unrelated to Composer.

**Comment by dmvtech** [comment]
Closing due to lack of response.
