### ISSUE TITLE
Can't Create on Bot Framework Composer

### ISSUE THREAD

**Issue by YebeltalAbebe** [microsoft/BotFramework-Composer#9724]
## Describe the bug

Command failed: dotnet build Empty.csproj Unhandled exception. System.ObjectDisposedException: Cannot write to a closed TextWriter. Object name: 'StreamWriter'. at System.IO.StreamWriter.<ThrowIfDisposed>g__ThrowObjectDisposedException|77_0() at System.IO.StreamWriter.WriteLine(String value) at Microsoft.DotNet.Installer.Windows.TimestampedFileLogger.Dispose(Boolean disposing) at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient.OnProcessExit(Object sender, EventArgs e) at System.AppContext.OnProcessExit()

## Version

v2.1.2

## Browser

- [ ] Chrome

## OS

- [ ] Windows
-

**Comment by creme-des-cremes** [comment]
there's a problem also no reply from my chatbot  after running i don't know what to do may you help me versions 2.1.2 browser chrome os:windows

**Comment by ilhamfadhil14** [comment]
I used `BotFramework-Composer-2.1.3-nightly.364675.1a93f21` and still experienced same thing.

```
$ node -v
v14.21.3

$ npm -v
8.5.4

$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

![image](https://github.com/microsoft/BotFramework-Composer/assets/80385722/d1e9e410-2405-4273-bcc1-9f1735c521b8)

**Comment by dmvtech** [comment]
@ilhamfadhil14 

What happens if you try and build outside of Composer:
`dotnet build <projectname>.csproj`

**Comment by kratkaericd** [comment]
I am also seeing this error trying to create a project using the Azure Function runtime, but an Azure Web App runtime creates.


> @ilhamfadhil14
> 
> What happens if you try and build outside of Composer: `dotnet build <projectname>.csproj`


I cannot find where the files are created locally to directly build the project. There are no files created at the "Location" specified in the creation dialog.
 
 
![image](https://github.com/microsoft/BotFramework-Composer/assets/11743265/216b5b19-55ba-43c0-badd-a7c9082f9953)

**Comment by ilhamfadhil14** [comment]
> @ilhamfadhil14
> 
> What happens if you try and build outside of Composer: `dotnet build <projectname>.csproj`

Hi @dmvtech ,

I tried but at that time still failed.

I have an update. I have successfully running bot composer, but i do not know why it resolved itself. I have tried bunch of uninstall, reinstall .NET, node. install visual studio and install .NET from there.

**Comment by dmvtech** [comment]
> I am also seeing this error trying to create a project using the Azure Function runtime, but an Azure Web App runtime creates.
> 
> > @ilhamfadhil14
> > What happens if you try and build outside of Composer: `dotnet build <projectname>.csproj`
> 
> I cannot find where the files are created locally to directly build the project. There are no files created at the "Location" specified in the creation dialog.
> 


I'm not quite sure about that. If you cannot find the files at the location you are telling Composer to create them at, then something is severly broken. The bot folder is not there at all? Or only contains a few files?

**Comment by kratkaericd** [comment]
> I'm not quite sure about that. If you cannot find the files at the location you are telling Composer to create them at, then something is severly broken. The bot folder is not there at all? Or only contains a few files?

Nada, nothing, zilch, no folder, no files.

**Comment by kratkaericd** [comment]
The bot does not successfully start.

Tried the root, saw the c:\composertest folder get created, saw a subfolder and a composertest.sln file created, watched Bot Framework composer try to compile, then fail as stated above, and now the files and folders don't exist on my hard drive, so it appears it all gets removed on failure.

![image](https://github.com/user-attachments/assets/9ed3cf65-5bbe-487f-8a4f-57072ea2c827)

**Comment by dmvtech** [comment]
@kratkaericd 

Since your issue is related to Azure Functions, are you able to create an Azure function (not necessarily a bot) outside of Composer? For example; can you create a basic http function with Visual Studio Code? I'm wondering if maybe some prerequisite is missing for the Functions. Then, as you said, when it fails Composer just removes the folder.

You can also try getting additional logging during a reproduction of the failure.
- Go to Composer's install location (mine is at C:\Users\{username}\AppData\Local\Programs\Bot Framework Composer)
- Open a terminal here
- Run `set DEBUG=composer*`
- Run the executable from the terminal Ex. "Bot Framework Composer.exe"
- Reproduce issue and send output of the terminal

**Comment by kratkaericd** [comment]
@dmvtech Thank you for your help with this. Yes, I create, author, and run Azure Functions locally nearly all day and every day. At this point we decided to move on to a different technology than Bot Framework, so thank you for trying to help, but we won't use this product anymore.
