### ISSUE TITLE
Error Calling npm to fetch template.

### ISSUE THREAD

**Issue by thegreenguy4201** [microsoft/BotFramework-Composer#9734]
Receiving an error when I try to create a Core Assistant Bot saying "Error calling npm to fetch template......." I've installed npm and node.  

Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm install -g --prefix C:\Users\mwmin\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error --no-optional @microsoft/generator-bot-core-assistant@*

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ X] Chrome

## OS

- [ X] Windows

## To Reproduce

1. Go to Bot Framework Composer Home Page
2. Click on 'Create a new bot to get started'
3. Scroll down to 'Core Assistant Bot' and select
4. Click Next
5. Update Project Name
6. Click Download Template
7. Error Reads as Follows: Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 1: npm install -g --prefix C:\Users\mwmin\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error --no-optional @microsoft/generator-bot-core-assistant@*

**Comment by dmvtech** [comment]
Under Composer's main settings; for Template Feed Url, do you have `https://registry.npmjs.org/-/v1/search?text=generator+keywords:bf-template+scope:microsoft` configured?

**Comment by thegreenguy4201** [comment]
I'm very new to this and don't know what you're asking.  How can I confirm is it is configured?

**Comment by dmvtech** [comment]
@thegreenguy4201 No worries. 

Hope this helps:
![image](https://github.com/microsoft/BotFramework-Composer/assets/43397658/0c411311-b3e0-44ea-b076-5efda6321985)


Just wanted to see if yours matches what is in my screenshot above.

**Comment by thegreenguy4201** [comment]
Yes.  Mine matches your screenshot

**Comment by OEvgeny** [comment]
Please refer to the issue #9745

**Comment by dmvtech** [comment]
Closing as likely resolved in nightly. If you are still having issues, please comment and we can reopen/continue.
