### ISSUE TITLE
Failure while installing composer using yarn

### ISSUE THREAD

**Issue by amangit007** [microsoft/BotFramework-Composer#9735]
While installing the composer i am getting the following error at step yarn install. 

ending chunk from error messages : 

` YN0002: │ react-dev-utils@npm:9.1.0 doesn't provide typescript (p27e3f), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ react-dev-utils@npm:9.1.0 doesn't provide webpack (p58b59), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ swagger-parser@npm:10.0.3 doesn't provide openapi-types (p54c62), requested by @apidevtools/swagger-parser
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 1s 775ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:1.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ z-schema@npm:5.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zip-stream@npm:4.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zod@npm:1.11.17 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A5.4.2#~builtin<compat/typescript>::version=5.4.2&hash=7ad353: Cannot apply hunk #1
➤ YN0000: └ Completed in 3m 13s
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.14.11 must be built because it never has been before or the last one failed
➤ YN0007: │ styled-components@npm:4.4.1 [bc1cf] must be built because it never has been before or the last one failed
➤ YN0007: │ electron@npm:14.2.6 must be built because it never has been before or the last one failed
➤ YN0007: │ nodemon@npm:2.0.15 must be built because it never has been before or the last one failed
➤ YN0007: │ cypress@npm:7.7.0 must be built because it never has been before or the last one failed
➤ YN0007: │ bufferutil@npm:4.0.6 must be built because it never has been before or the last one failed
➤ YN0007: │ utf-8-validate@npm:5.0.8 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.15.2 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.25.3 must be built because it never has been before or the last one failed
➤ YN0007: │ @microsoft/orchestrator-core@npm:4.14.4 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.20.3 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.14.38 must be built because it never has been before or the last one failed
➤ YN0007: │ abort-controller-es5@npm:2.0.1 [6b544] must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.20.3 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.12.1 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.18.3 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0009: │ @microsoft/orchestrator-core@npm:4.14.4 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\Lenovo\AppData\Local\Temp\xfs-f7c33b53\build.log)
➤ YN0007: │ p-defer-es5@npm:2.0.1 [7cf8f] must be built because it never has been before or the last one failed    
➤ YN0007: │ markdown-it-attrs-es5@npm:2.0.2 [c172f] must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 6m 36s`

I have 
node version as :  20.11.1
yarn as : 1.22.22
dotnet SDK as: 8.0.204
visual c++ : 14.38

**Comment by OEvgeny** [comment]
What's the command you're using? Composer is not intended to be installed this way

**Comment by amangit007** [comment]
I am following the steps given in readme.md which are

```bash
git clone https://github.com/microsoft/BotFramework-Composer.git
cd BotFramework-Composer
cd Composer # switch to Composer folder
yarn install # install dependencies
yarn build # build extensions and libs
yarn startall # start client and server at the same time 
```
this error comes at yarn install stage

**Comment by OEvgeny** [comment]
@amangit007 I see. In order to build Composer this way, you have to use node v14, otherwise, you'll get the error:
> ➤ YN0009: │ @microsoft/orchestrator-core@npm:4.14.4 couldn't be built successfully (exit code 1

The problem is that `@microsoft/orchestrator-core` doesn't provide builds for newer NodeJS versions.

**Comment by amangit007** [comment]
What is the other way?

**Comment by OEvgeny** [comment]
@amangit007 the other way is to use prebuilt binaries

**Comment by amangit007** [comment]
Ok, your solution helped. Thank you
