### ISSUE TITLE
Bot Framework Composer Command failed : dotnet build while creation of new empty bot

### ISSUE THREAD

**Issue by Shailesh-TMO** [microsoft/BotFramework-Composer#9738]
When trying to create a new empty bot using Composer in C#, it is giving an error **Command failed : dotnet build**. Subsequently it is not creating any project inside the folder. But on the error message it is showing project file name (Test.csproj).

If anyone has faced this issue, please let me know the resolution.
Your help would be great.

**Comment by dmvtech** [comment]
@Shailesh-TMO 

Can you please run the following command and share the results: `dotnet --info`

Can you also try and run the command from the bot project location:
`dotnet build <projectname>.csproj`

**Comment by dmvtech** [comment]
Closing due to lack of response. If assistance is still needed, please comment with pertinent information and we will continue.
