### ISSUE TITLE
Can't set "Max turn count" to 0

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [microsoft/BotFramework-Composer#9739]
Hi,
I have the following error or maybe it is a feature. When I set the "Max turn count" value in an "User Input Choice" to 1, then after 120 seconds my bot in the webchat automatically answers the question. Maybe it is an idle timeout, I don't know. Does anybody know is this a bug or a feature. I'm aksing that, because I want to disable this automatism. I tried to set this value to 0, but it doesn't work. Can I set the timeout manually to another value?
![2024-04-30 16_05_30-Bot Framework Composer (v2 1 2)](https://github.com/microsoft/BotFramework-Composer/assets/35596604/47b54c5f-9657-4e4f-9e0f-00f4a32ec512)
![2024-04-30 16_05_50-Bot Framework Composer (v2 1 2)](https://github.com/microsoft/BotFramework-Composer/assets/35596604/c1fb056b-7248-4e6d-9c27-67137798d0d7)

**Comment by andreas-sommer-engenious** [comment]
Sorry, I forgot one detail. It always happens with the directline extension and not in the emulator.

**Comment by dmvtech** [comment]
@andreas-sommer-engenious 

By 'directline extension` you mean you can reproduce this in something like basic Web Chat? Does it reproduce in the Azure portal `Test in Web Chat`?

**Comment by dmvtech** [comment]
Closing due to lack of response. If assistance is still needed, please comment with pertinent information and we will continue.
