### ISSUE TITLE
[Hackathon] HTTP Request variable definition/usage should be made less error prone.

### ISSUE THREAD

**Issue by RustyDes** [microsoft/BotFramework-Composer#974]
**Is your feature request related to a problem? Please describe.**
When using the Composer component to make an HTTP request (Integrations-->Http Request), the variable that is definted will not receive the body of the response but instead will receive an object that has a content property (among others) which can be used to retrieve the response from the webservice. Discoverability of "you have to add .content" to the variable name would help.

**Describe the solution you'd like**
- Ideally when I use variables I should get intelisense.
- Additionally when defining the variable that receive the result of the HTTP Request, it could show me right under the name of the variable that
<variableName>.content is what I should use to access the answer.
- Finally, if I try to use <variableName> directly without a .<Something>, highlight the fact that this is likely not what I want.

There may be better solutions.

**Describe alternatives you've considered**

**Additional context**

**Comment by vishwacsena** [comment]
@sangwoohaan @mareekuh - Thoughts on how we can educate users on what to expect here? Dropping SDK label.

**Comment by mareekuh** [comment]
Suggested solution:
- Add instructional text directly below the title:
Provide object property to be retrieved from the webservice. 
- Add intelisense
- In 'watermark' text inside the field,  include an example that includes " .content" 

@zxyanliu - please review copy above and provide recommendations for improvement

**Comment by zxyanliu** [comment]
@mareekuh 
This is my suggestion on this particular thread:

![UX-http-request](https://user-images.githubusercontent.com/32497439/79385735-ed493b00-7f1d-11ea-954e-4c8347b0af98.png)

I also double checked the _Learn more_ is pointing to the [Composer doc](https://docs.microsoft.com/composer/how-to-send-http-request) on this topic. 

![image](https://user-images.githubusercontent.com/32497439/79385871-22558d80-7f1e-11ea-970d-a4f9a1a11482.png)

**Comment by mareekuh** [comment]
If we just had 2 lines of instructional text + a link to more info (vs 4 rows), what would it be?

**Comment by zxyanliu** [comment]
Like this?

![UX](https://user-images.githubusercontent.com/32497439/79405399-2a76f280-7f49-11ea-8d81-658b60151df0.png)

The _Learn more_ link is already in the same properties panel on top, which might be sufficient.

**Comment by mareekuh** [comment]
How about:

"This property will contain the result of the HTTP request as deserialized object (JSON) or string and includes: statusCode, reasonPhrase, Content and Headers."

Hmm that's long too. But maybe less error/guess-prone for the user?

**Comment by zxyanliu** [comment]
@mareekuh yeah, this might be too long. I find the current design to include the help text on the property field is helpful. I don't have a better idea except pointing users to the [doc](https://docs.microsoft.com/en-us/composer/how-to-send-http-request#add-a-send-an-http-request-action).

**Comment by mareekuh** [comment]
imo better long(ish) than none... So what's the long(ish) text your propose?

**Comment by zxyanliu** [comment]
@mareekuh sorry I did not make myself clear. I can propose some help text for **Result Property** like the following. Specifically, I added this sentence: The values can be accessed via .content for example. I think users need to know how to access the value of this property. This should be sufficient for users in this scenario, but on the condition that they click the **?** sign to read the help text. 

**Result Property**: 
"A property to store the result of this action. The result can include any of the 4 properties from the HTTP response: statusCode, reasonPhrase, content, and headers. If the content is JSON it will be a deserialized object. The values can be accessed via .content for example."

![UX-Result Property](https://user-images.githubusercontent.com/32497439/79808233-0b4ddb80-8322-11ea-8e49-0aa8338f29ee.png)

**Comment by a-b-r-o-w-n** [comment]
@vishwacsena do you know if the shape of this result will be consistent across the different sdk languages?

**Comment by vishwacsena** [comment]
I believe so. @luhan2017 does the `HTTPAction` implementation for JS keep the same shape for the result?

**Comment by mareekuh** [comment]
Looks good (-:

**Comment by luhan2017** [comment]
> I believe so. @luhan2017 does the `HTTPAction` implementation for JS keep the same shape for the result?

Yes, they are the same. In the JS side, we are using the C# declarative test cases to make sure they have consistent behavior.

**Comment by mareekuh** [comment]
@zxyanliu - @hibrenda - did this get updated/implemented?

**Comment by hibrenda** [comment]
not yet. Assigned @alanlong9278 to fix the pop up message.
