### ISSUE TITLE
create new bot

### ISSUE THREAD

**Issue by prabhu0910** [microsoft/BotFramework-Composer#9741]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by dmvtech** [comment]
@prabhu0910 Please add more context if you need assistance with creating a new bot in Composer. We can then reopen and assist you.
