### ISSUE TITLE
composer is showing white screen

### ISSUE THREAD

**Issue by raynould-comportement** [microsoft/BotFramework-Composer#9744]
![im2](https://github.com/microsoft/BotFramework-Composer/assets/141298300/f2f24e8c-dc16-43aa-a8ce-0bb7c62fa56f)
![im1](https://github.com/microsoft/BotFramework-Composer/assets/141298300/add3fd32-f9cf-4494-91a6-f92e06844290)

**Comment by raynould-comportement** [comment]
tried of reinstalling it the issue is still their

**Comment by OEvgeny** [comment]
Please refer to the issue #9745

**Comment by dmvtech** [comment]
Closing as resolved. Please reopen if you are continuing to experience the issue.
