### ISSUE TITLE
Error certificate has expired *** Could not merge components ***

### ISSUE THREAD

**Issue by luisdoprado** [microsoft/BotFramework-Composer#9746]
I using Microsoft.Bot.Components.Telephony

If this problem persists, please file an issue on [GitHub](https://github.com/microsoft/BotFramework-Composer/issues)
Saiba mais
A problem occured during the install of this Component: Error certificate has expired *** Could not merge components ***

![image](https://github.com/microsoft/BotFramework-Composer/assets/43001118/5c30b0d3-f340-4f34-90f5-3940269cf44f)

**Comment by dmvtech** [comment]
Hi @luisdoprado 

What version of Composer are you using? If not already, can you try installing the newest nightly version and test again?
https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.1.3-nightly.364675.1a93f21

**Comment by luisdoprado** [comment]
Good morning,

Thank you for your support, I installed the version you suggested and it worked!

A big hug,
Luís

De: Dana V ***@***.***>
Enviada em: quarta-feira, 22 de maio de 2024 15:06
Para: microsoft/BotFramework-Composer ***@***.***>
Cc: luisdoprado ***@***.***>; Mention ***@***.***>
Assunto: Re: [microsoft/BotFramework-Composer] Error certificate has expired *** Could not merge components *** (Issue #9746)


Hi @luisdoprado<https://github.com/luisdoprado>

What version of Composer are you using? If not already, can you try installing the newest nightly version and test again?
https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.1.3-nightly.364675.1a93f21

-
