### ISSUE TITLE
Recognizer is invoked Twice for the same user message 

### ISSUE THREAD

**Issue by SanKumar0632** [microsoft/BotFramework-Composer#9750]
## Describe the bug

When user replies to the bot's question(prompt made using "Ask a question" option an prompt config "Allow interruptions" set to true), the recognizer set for the bot is running twice.

## Version

2.1.3-nightly.364675.1a93f21

## To Reproduce

1. Create a prompt using the "Ask a question" action
2. Set the prompt configuration "Allow interruptions" to true
3. Start the bot and reply to the prompt created
4. You will see that the recognizer runs twice

## Video

https://github.com/microsoft/BotFramework-Composer/assets/122610382/3d456671-58c8-4d0b-989b-ff19b7a0f541

## Additional context

It may affect the response time of bot as I am using a REST api based custom recognizer for the bot.

**Comment by dmvtech** [comment]
What version of the SDK is the bot running? Does it reproduce with version `4.22.7`? (assuming you're using C$)

**Comment by dmvtech** [comment]
Are you able to share your bot/dialogs? I understand you have a custom recognizer, but I just want to see how the dialogs and triggers are laid out.

**Comment by dmvtech** [comment]
Closing due to lack of response. If assistance is needed, please share the requested information and we can continue.
