### ISSUE TITLE
Luis build failed: Cannot read property 'error' of undefined 

### ISSUE THREAD

**Issue by dev-proc** [microsoft/BotFramework-Composer#9752]
Hello.

I was trying to edit an existing bot but couldn't run it locally for testing because I got an error:

> Sorry, something went wrong with publishing. Try again or exit out of this task.
> Luis build failed: Cannot read properties of undefined (reading 'error')

![image](https://github.com/microsoft/BotFramework-Composer/assets/2794562/7df7acb2-0d38-4d58-997b-911882e8acd8)

Tested in 2.1.2 and latest 2.1.3-nightly.364675.1a93f21 (Windows 11)
Debug logs are attached: [composer_20240606.log](https://github.com/user-attachments/files/15687208/composer_20240606.log)

I checked these issues [9611](https://github.com/microsoft/BotFramework-Composer/issues/9611) [9600](https://github.com/microsoft/BotFramework-Composer/issues/9600) before submitting the new one. There are no errors like in the first case. Could you provide a test request to check if it's a network limitation?

**Comment by OEvgeny** [comment]
Do you have needed resources created? https://learn.microsoft.com/en-us/azure/ai-services/luis/how-to/publish

**Comment by dev-proc** [comment]
Yes, created and connected. It's working bot. I just needed to do some changes, but Composer refuses to build my old project. 
![image](https://github.com/microsoft/BotFramework-Composer/assets/2794562/308c119b-0f0a-4489-b3f8-4794b215c77c)

**Comment by dmvtech** [comment]
@dev-proc Is this a bot that you are just testing locally using existing LUIS (authoring) resources? Or is this a bot+LUIS that has already been provisioned and published?

**Comment by dmvtech** [comment]
Closing due to lack of response. If assistance is still needed, please comment with pertinent information and we will continue.
