### ISSUE TITLE
Opening package manager gives this error

### ISSUE THREAD

**Issue by Namrata-github** [microsoft/BotFramework-Composer#9756]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by Namrata-github** [comment]
If this problem persists, please file an issue on [GitHub](https://github.com/microsoft/BotFramework-Composer/issues)
Details
Could not load component list:Error certificate has expired *** Could not merge components

**Comment by OEvgeny** [comment]
Assuming you're not using the latest nightly #9745
