### ISSUE TITLE
Command: dotnet build Weatherboat.csproj is failed

### ISSUE THREAD

**Issue by Namrata-github** [microsoft/BotFramework-Composer#9758]
Command:
dotnet build Weatherboat.csproj
Stack Trace:
Error: Command failed: dotnet build Weatherboat.csproj

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Output:
Microsoft (R) Build Engine version 16.7.3+2f374e28e for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\Users\namrata.s.dattani\Downloads\Generatative AI\AzureBot\Boats\Weatherboat\Weatherboat\Weatherboat.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
  All projects are up-to-date for restore.
C:\Users\namrata.s.dattani\Downloads\Generatative AI\AzureBot\Boats\Weatherboat\Weatherboat\Weatherboat.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
Controllers\SkillController.cs(26,45): error CS0115: 'SkillController.ReplyToActivityAsync(string, string, Activity)': no suitable method found to override [C:\Users\namrata.s.dattani\Downloads\Generatative AI\AzureBot\Boats\Weatherboat\Weatherboat\Weatherboat.csproj]
Controllers\SkillController.cs(44,45): error CS0115: 'SkillController.SendToConversationAsync(string, Activity)': no suitable method found to override [C:\Users\namrata.s.dattani\Downloads\Generatative AI\AzureBot\Boats\Weatherboat\Weatherboat\Weatherboat.csproj]

Build FAILED.

C:\Users\namrata.s.dattani\Downloads\Generatative AI\AzureBot\Boats\Weatherboat\Weatherboat\Weatherboat.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\Users\namrata.s.dattani\Downloads\Generatative AI\AzureBot\Boats\Weatherboat\Weatherboat\Weatherboat.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
Controllers\SkillController.cs(26,45): error CS0115: 'SkillController.ReplyToActivityAsync(string, string, Activity)': no suitable method found to override [C:\Users\namrata.s.dattani\Downloads\Generatative AI\AzureBot\Boats\Weatherboat\Weatherboat\Weatherboat.csproj]
Controllers\SkillController.cs(44,45): error CS0115: 'SkillController.SendToConversationAsync(string, Activity)': no suitable method found to override [C:\Users\namrata.s.dattani\Downloads\Generatative AI\AzureBot\Boats\Weatherboat\Weatherboat\Weatherboat.csproj]
    2 Warning(s)
    2 Error(s)

Time Elapsed 00:00:04.15
Killed:
Code:
1

**Comment by dmvtech** [comment]
Please give the output of the following command from a terminal window:
`dotnet --info`

**Comment by dmvtech** [comment]
Closing due to lack of response.

**Comment by levn2** [comment]
Had this issue today, opened project in VS and updated libraries and the error is gone.
