### ISSUE TITLE
Application insights are not getting logged for Azure FAQ bot

### ISSUE THREAD

**Issue by beesettysai** [microsoft/BotFramework-Composer#9762]
Hi Team,

I have a Azure FAQ bot, to which I have integrated the application insights. I was just able to see the server and Activity requests. But I want to view the question entered by user and also answer response and the QNA score. Is there a way we can achieve this. I have a language service as a source and I have downloaded the bot source code directly from the azure bot.

**Earlier we had a QnA bot which is using LUIS and it is web application bot for that I was able to observe the questions and answers getting logged to application insights, but not for the one above.

Could you please help on this.
```[tasklist]
### Tasks
```

**Comment by dmvtech** [comment]
@beesettysai  I know this issue is old, but did you find a solution yet?
