### ISSUE TITLE
Unable to publish bot consistently - composer crashes

### ISSUE THREAD

**Issue by sdalviuob** [microsoft/BotFramework-Composer#9765]
## Describe the Bug

When attempting to publish a bot using Composer, the process progresses to the "Creating build artifacts" or "uploading zip file" stage and then abruptly closes without completing the publishing process. This issue prevents consistent deployment of the bot to Azure.

## Version

- Composer Version: 2.1.3-nightly.364675.1a93f21

## OS

- Windows

## To Reproduce

Steps to reproduce the behaviour:

1. Open Bot Composer on Windows.
2. Create or load an existing bot project.
3. Navigate to the "Publish" section.
4. Initiate the publish process to Azure.
5. Observe as the process reaches the "Creating build artifacts" or "uploading zip file" stage.
6. The Composer application closes unexpectedly before the bot is published.

## Expected Behaviour

The bot should publish to Azure consistently without the Composer application closing unexpectedly.

## Additional Context

- This issue occurs intermittently; sometimes, the bot publishes without issue, while other times, Composer crashes during the process.
- Restarting Composer occasionally resolves the issue, but the fix is not consistent.

**Comment by dmvtech** [comment]
@sdalviuob  Are you still experiencing this issue?
