### ISSUE TITLE
zain

### ISSUE THREAD

**Issue by zain-blip** [microsoft/BotFramework-Composer#9766]
## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by zain-blip** [comment]
zaub

**Comment by dmvtech** [comment]
Closing due to lack of detail. Please add more detail if you actually need help with a problem.
