### ISSUE TITLE
Error creating a new project and publishing (LUIS)

### ISSUE THREAD

**Issue by elbrinner** [microsoft/BotFramework-Composer#9767]
## Describe the bug

When trying to publish the project from composer I get the following error:

Provision partially completed
Provisioning completed 3 items before encountering a problem. {"name":"CREATE_LUIS_AUTHORING_RESOURCE_ERROR","message":"Error - The subscription does not have QuotaId/Feature required by SKU 'F0' from kind 'LUIS.Authoring' or contains blocked QuotaId/Feature.","stack":"Error\n at new CustomizeError (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276418:25)\n at createCustomizeError (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276423:10)\n at AzureResourceMananger.deployLuisAuthoringResource (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:277226:13)"}. See provision.testev6.log in your bot folder

LOG:
{
  "profileName": "testev6",
  "jobId": "bd5af691-74fb-4bee-90b0-02ade1e5a540",
  "projectId": "39513.61535147306",
  "time": "2024-09-02T11:22:01.555Z",
  "log": [
    "Creating Azure resources...",
    "Checking the Existence of the Resource Group ...",
    "Use the Resource Group: BRI_TEST at francecentral",
    "> Creating App Registration ...",
    "Start to add password for App, Id : 6d300de1-7cce-4ddc-a7f8-3XXXX,
    "> Create App Registration Success! ID: 6d300de1-7cce-4ddc-a7f8-3cf2c42a4f6f",
    "Deploying Web App Resource ...",
    "Deploying Bot Resource ...",
    "Deploying Luis Authoring Resource ...",
    "{\"stack\":\"Error: The subscription does not have QuotaId/Feature required by SKU 'F0' from kind 'LUIS.Authoring' or contains blocked QuotaId/Feature.\\n    at new RestError2 (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:180915:26)\\n    at /Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:181850:27\\n    at async AzureResourceMananger.deployLuisAuthoringResource (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:277202:28)\\n    at async BotProjectProvision.create (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:278113:46)\\n    at async AzurePublisher.asyncProvision (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:278539:34)\",\"message\":\"The subscription does not have QuotaId/Feature required by SKU 'F0' from kind 'LUIS.Authoring' or contains blocked QuotaId/Feature.\",\"code\":\"SpecialFeatureOrQuotaIdRequired\",\"statusCode\":400,\"request\":{\"body\":\"{\\\"kind\\\":\\\"LUIS.Authoring\\\",\\\"location\\\":\\\"westeurope\\\",\\\"sku\\\":{\\\"name\\\":\\\"F0\\\"}}\"},\"response\":{\"body\":\"{\\\"error\\\":{\\\"code\\\":\\\"SpecialFeatureOrQuotaIdRequired\\\",\\\"message\\\":\\\"The subscription does not have QuotaId/Feature required by SKU 'F0' from kind 'LUIS.Authoring' or contains blocked QuotaId/Feature.\\\"}}\"},\"body\":{}}",
    "{\"name\":\"CREATE_LUIS_AUTHORING_RESOURCE_ERROR\",\"message\":\"Error - The subscription does not have QuotaId/Feature required by SKU 'F0' from kind 'LUIS.Authoring' or contains blocked QuotaId/Feature.\",\"stack\":\"Error\\n    at new CustomizeError (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276418:25)\\n    at createCustomizeError (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276423:10)\\n    at AzureResourceMananger.deployLuisAuthoringResource (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:277226:13)\"}",
    "Provisioning completed 3 items before encountering a problem. {\"name\":\"CREATE_LUIS_AUTHORING_RESOURCE_ERROR\",\"message\":\"Error - The subscription does not have QuotaId/Feature required by SKU 'F0' from kind 'LUIS.Authoring' or contains blocked QuotaId/Feature.\",\"stack\":\"Error\\n    at new CustomizeError (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276418:25)\\n    at createCustomizeError (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276423:10)\\n    at AzureResourceMananger.deployLuisAuthoringResource (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:277226:13)\"}. See provision.testev6.log in your bot folder"
  ]
}

When trying to create the resource in the Azure portal, it does not allow me, indicating that the name is not available no matter how much I change it.

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ x] Windows
- [ ] Ubuntu

## To Reproduce

<img width="963" alt="Captura de pantalla 2024-09-02 a las 13 18 02" src="https://github.com/user-attachments/assets/4d797bb7-4066-4a97-8d9a-e7e237bcbe8c">
<img width="937" alt="Captura de pantalla 2024-09-02 a las 13 21 57" src="https://github.com/user-attachments/assets/a054f5af-95f2-4a35-abfe-346f926c48a3">
<img width="1430" alt="Captura de pantalla 2024-09-02 a las 13 23 02" src="https://github.com/user-attachments/assets/23f604a0-05fb-4c27-9a4b-da0de84ffbca">

1. Create new project in composer 2.1.2
2. Publish

## Expected behavior

Que se cree el recurso y que publique mi código del bot en el App Services.

## Screenshots

When I try to create the resource manually to apply the subsequent configuration, it doesn't work for me. I've tried with Luis (old) and with Azure AI service for Language.

**Comment by dmvtech** [comment]
This is due to LUIS being depreciated. Do not use Composer to provision LUIS or other language resources at this time. I'm not sure the option will be removed, but I will check into that.

You will need to provision CLU or CQA resources outside of Composer and then utilize them in the dialogs.

**Comment by elbrinner** [comment]
Thanks,

By creating the resources by hand in Azure and publishing them outside of composer I can work normally.

I think I should update composer to use the new Azure resources and not Lus.

Regards
