### ISSUE TITLE
EPERM: operation not permitted, mkdir 'C:/Users/Empty'

### ISSUE THREAD

**Issue by Kylerobson23232323** [microsoft/BotFramework-Composer#9768]
Trying to create my first chat bot and i keep getting this error. Any help would be appreciated 

If this problem persists, please file an issue on [GitHub](https://github.com/microsoft/BotFramework-Composer/issues)
Details
Error hit when instantiating remote template: EPERM: operation not permitted, mkdir 'C:/Users/Empty'

**Comment by dmvtech** [comment]
What is the location/path of the bot you are trying to create?

**Comment by dmvtech** [comment]
Closing due to lack of response. Please comment with pertinent information if assistance is still needed.
