### ISSUE TITLE
Bot framework composer selecting global for CosmoDB instead of local, it fails starting of bot using cosmo

### ISSUE THREAD

**Issue by vosnie-77** [microsoft/BotFramework-Composer#9778]
Sorry, something went wrong with publishing. Try again or exit out of this task.

Qnamaker build failed: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.

**Comment by dmvtech** [comment]
@vosnie-77 Did you get past this?

Composer bots should work fine with Serverless CosmoDB. Just set configuration similar to below and ensure the partition key is `/id`.

```json
"runtimeSettings": {
    "storage": "CosmosDbPartitionedStorage",
  "CosmosDbPartitionedStorage": {
    "authKey": "<AUTHKEY>",
    "cosmosDbEndpoint": "<ENDPOINT>",
    "databaseId": "<DATABASE>",
    "containerId": "<COLLECTIONID>"
  },
```

**Comment by dmvtech** [comment]
Closing as solution given.
