### ISSUE TITLE
[Hackathon] Composer should support parallel instances

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#980]
**Is your feature request related to a problem? Please describe.**
When developing bots, it's often helpful to have multiple bots open side by side so you can compare your own code to sample code, etc. We cannot do this in Composer without encountering unexpected behavior.

**Describe the solution you'd like**
The name of the bot you have open should be part of the path, so instead of http://localhost:3000/home it should be http://localhost:3000/ToDoBot/home for example. This could help in allowing different bots to be open in different browser tabs.

**Comment by hibrenda** [comment]
addressed in #2023 
close this as composer can open parallel instances and #1330 addressed the remaining issues.
