### ISSUE TITLE
[Hackathon] Composer Home: Create from scratch vs Create from Empty Bot template? 

### ISSUE THREAD

**Issue by elaine-chang** [microsoft/BotFramework-Composer#981]
## Version
N/A

## Describe the bug
At the Composer Home page: It's not clear what's the difference between creating from scratch vs creating from the Empty Bot template. 

## To Reproduce
1. Go to Composer Home
2. Click on '+New' 
3. You will see the following option (see screenshot)

## Expected behavior
If creating from scratch is the same as creating from the Empty Box template, I'd suggest removing the "Empty Box" template to reduce confusion. 

## Screenshots
![image](https://user-images.githubusercontent.com/25210203/65805546-cfabb400-e13a-11e9-859b-b101b97301c1.png)

**Comment by cwhitten** [comment]
Closing as duplicate
