### ISSUE TITLE
[Hackathon] Property naming conventions are unclear

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#985]
## Describe the bug
Some places use an example property format like `$birthday` (with a dollar sign) and some places use an example property format like `user.age` (with a period). It's unclear what the difference is or which is preferred.

## Expected behavior
The proper way to name properties should be clear and unambiguous.

## Screenshots
![image](https://user-images.githubusercontent.com/41968495/65806158-316d1d80-e13d-11e9-8055-59418cca03a0.png)
![image](https://user-images.githubusercontent.com/41968495/65806180-3fbb3980-e13d-11e9-9550-d70f4139b235.png)

[bug]

**Comment by vishwacsena** [comment]
Dropping SDK label. This is purely UA issue that we should address in composer.

**Comment by cwhitten** [comment]
@vishwacsena the placeholders & examples in these fields come off of the schema. Are you saying we shouldn't be using those?

**Comment by cwhitten** [comment]
Working "as designed". Closing for now.
