### ISSUE TITLE
[Hackathon] We should be able to resize panels

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Composer#987]
**Is your feature request related to a problem? Please describe.**
We often cannot see the whole names of triggers because the left panel is too narrow:
![image](https://user-images.githubusercontent.com/41968495/65806493-a42ac880-e13e-11e9-84f8-e1a8949fe2f2.png)

**Describe the solution you'd like**
We should be able to adjust the size of panels.

**Describe alternatives you've considered**
Scrollbars could be an alternative.

**Comment by cwhitten** [comment]
To implementer:

1. Allow resizable panes for left nav, flow editor, form editor. Serialize box boundaries to the browser's local storage, and load this data every time the application is mounted.

**Comment by xieofxie** [comment]
Add skill-reported to indicate it is also required by skills team.
Also maybe we could also support form editor as it may be too crowded:

![image](https://user-images.githubusercontent.com/2876650/77635142-1153d500-6f8d-11ea-9241-051087d3f2ff.png)

**Comment by cwhitten** [comment]
addressed via https://github.com/microsoft/BotFramework-Composer/pull/2552
