### ISSUE TITLE
[hackathon]Changing Recognizer Type deletes user's Handle Conversation Update settings

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/BotFramework-Composer#989]
Repro:
In sample ToDoBot,

1) Click 'Design Flow' in main nav bar.
Form editor shows 'Recognizer Type' 'Regular Expression'.
Below that are listed a number of intents and their patterns.
2) In the 'Recognizer type' dropdown, select 'None'.
Actual: Below are listed a number of blank 'Handle an Intent' items and an 'Add' button at bottom.
Expected: Don't understand the purpose of the blank intents. Is this a bug?
3) In the 'Recognizer type' dropdown, select 'Regular Expression'.
Actual: Below, all the categories, the 'Regex patterns to intents', etc. are all blank.
Expected: The settings originally listed under 'Recognizer Type' 'Regular Expression' would remain. Now they are gone.

The only way I was able to restore all the lost settings was to delete the workspace, re-clone the repo, and rebuild Composer.
I consider this a major 'gotcha' for the user: Losing all his work just for changing a selection and then restoring it.

I recall reporting this same bug at the previous hackathon. It evidently has not been fixed.

**Comment by cwhitten** [comment]
Closing as fixed.
